### ISSUE TITLE
[Bug] jsStrategy: 'bigVendors', 不生效

### ISSUE THREAD

**Issue by tangwenru** [umijs/umi#10004]
## What happens?

```
// 不生效
codeSplitting: {
    jsStrategy: 'bigVendors',
  }
```

## Mini Showcase Repository(REQUIRED)

<img width="638" alt="image" src="https://user-images.githubusercontent.com/14308021/206441249-f668f8e9-c771-495b-ade6-66fa014fe994.png">

## Context

- **Umi Version**: 4.0.35
- **Node Version**: v16.15.0

**Comment by fz6m** [comment]
`jsStrategy` 所指代的分包策略是指对 `node_modules` 里的第三方依赖进行的分包行为，并不指代全部的分包行为。

umi4 本身自带按页拆包，所以产物不会是一个，如果你需要打包成一个文件，参考 [可以关闭 dynamicImport 吗？](https://umijs.org/docs/introduce/faq#%E5%8F%AF%E4%BB%A5%E5%85%B3%E9%97%AD-dynamicimport-%E5%90%97)
