### ISSUE TITLE
[Feature Request] 简化初始化 umi 脚手架的操作

### ISSUE THREAD

**Issue by mysteryven** [umijs/umi#10011]
## Background

在文档的 [说明](https://umijs.org/docs/tutorials/getting-started#%E5%88%9B%E5%BB%BA%E9%A1%B9%E7%9B%AE) 中，现在初始化脚手架需要两步：

```bash
mkdir myapp && cd myapp
pnpm dlx create-umi@latest
```

这个命令好像有点长到难以记住。

## Proposal

希望直接一行命令完成创建：

```bash
pnpm create umi
```

接下来如果没有指定文件名，可以直接有默认的文件名：

```bash
? Project name: > umi-project # 增加对文件名的选择
? Pick Umi App Template > Simple App
```

## Additional context

目前已经支持 `pnpm create umi [project-name]` 的形式，不过可能有点隐藏，有些同学可能不知道。

**Comment by fz6m** [comment]
业界里本身共识就是 后面可带可不带文件夹名的。

如果感觉容易产生疑惑，可以把文档优化下，改成 `pnpm create umi my-app`

**Comment by zjfresh** [comment]
加 `[folder]` 候选的语法更友好吧，再配个提示就更好了（`不加文件夹名称时以当前目录进行初始化`）

昨天初始化按照 umi-max 的说明就搞错了，在 projects/* 下跑了 npx create-umi@latest，这种命令一旦搞错回退成本可能会很高……

```bash
npx create-umi@latest
```
![image](https://user-images.githubusercontent.com/28496323/206829545-d47a5d56-2352-4985-895d-17baaab5b06d.png)

**Comment by fz6m** [comment]
报一下 npm 版本，我试了 v8 和 v9 都可以的。

<img src='https://user-images.githubusercontent.com/59400654/206897549-05d6b037-8c4d-4d79-90cf-3dd3530e39d4.png' width='300' />

**Comment by mysteryven** [comment]
node: v18.12.1
npm: 8.19.2

我使用的不是 `npx create-umi name`。而是 `npm create umi@latest`。

运行  vite 的起步命令没有问题 `npm create vite@latest` ，但是 umi 的不可以 `npm create umi@latest`，但是 [npm 文档](https://docs.npmjs.com/cli/v9/commands/npm-init) 说是等价的

报错信息：
```bash
ENOTEMPTY: directory not empty, rename '/path/to/.npm/_npx/2c52c20452535a0f/node_modules/@umijs/utils' 
-> '/path/to/.npm/_npx/2c52c20452535a0f/node_modules/@umijs/.utils-ipVeybw0'
```


可能只是我的电脑不行，不过不行也没关系，我平常也不用 npm，测试 npm 的原因只是本来想更新一下文档来着。

**Comment by Redish101** [comment]
#12516

**Comment by 003d** [comment]
这个调整在一个git仓库目录初始化项目的场景下，是不是很难受
业界里本身共识是不是这样的，mkdir myapp && cd myapp
加 [folder] 候选的语法更友好吧
@Redish101 @sorrycc

**Comment by Machiavellid** [comment]
> 这个调整在一个git仓库目录初始化项目的场景下，是不是很难受 业界里本身共识是不是这样的，mkdir myapp && cd myapp 加 [folder] 候选的语法更友好吧 @Redish101 @sorrycc

附议
