### ISSUE TITLE
🐛[BUG]umi3升级到umi4，ProForm下的<Form.Item>无法获取上下文，报错Can not find FormContext. Please make sure you wrap Field under Form；

### ISSUE THREAD

**Issue by titld** [umijs/umi#10018]
ProForm里面引入自定义组件<Form.Item>，
![image](https://user-images.githubusercontent.com/57819648/206701698-6e9f7dd9-84ef-4248-941c-8dfc0834a769.png)
此时没有问题；但是如果我把
![image](https://user-images.githubusercontent.com/57819648/206701723-181c8f57-f9b9-48a9-aa2b-72b1a75bba3c.png)
这一部分抽出来，封装成一个插件'@umijs/plugin-my-demo'，插件导出`MyPlugins`组件（真实的插件，从自定的插件中导出），然后以组件的方式引入
```js
import { MyPlugins } from '@umijs/plugin-my-demo';
<ProForm><MyPlugins /></ProForm>
```
就会破坏原有的Form结构，会报错：【Antd】Warning: Can not find FormContext. Please make sure you wrap Field under Form；
在umi3当中没有问题，但在umi4中就会出错而无法使用，是不是umi插件机制有问题，拿不到context？

© 版本信息
ProComponents 版本: 2.3.19
ProForm 版本：2.2.7
umi 版本 4.0.34

**Comment by fz6m** [comment]
关于 pro component 的打开方式和使用问题，可以在 https://github.com/ant-design/pro-components 反馈，这里仅供反馈 umi 问题。
