### ISSUE TITLE
v2中刷新浏览器后global.less中样式丢失

### ISSUE THREAD

**Issue by iceberg211** [umijs/umi#1002]
dev开发中刷新浏览器会造成global.less中样式丢失，这个时候保存一下global.less编译一次才能生效。

**Comment by sorrycc** [comment]
> dev开发中刷新浏览器会造成global.less中样式丢失

怎么重现？原因应该不是刷新浏览器，刷新浏览器不会修改 dev 生成的样式文件的。

**Comment by hazeFlame** [comment]
因为首页的index.css变成了umi.css
你需要自己改一下

**Comment by iceberg211** [comment]
@sorrycc  准确说global.less的权重降低了，导致没有覆盖ant的样式。
在ant design pro里面就可以重现，修改models引起的刷新也会导致样式权重降低.

**Comment by hazeFlame** [comment]
对，权重降低也是一个问题，好多css失效

**Comment by Z-wave** [comment]
为什么我把global.css改成global.less会报错？

**Comment by sbyps** [comment]
求快速修复这个bug

**Comment by hazeFlame** [comment]
@sorrycc 这个问题修了嘛

**Comment by xiaohuoni** [comment]
@dilidili global的权重应该要大于antd自带样式的权重。

**Comment by handycode** [comment]
@dilidili 我也认同 @xiaohuoni 的看法： 'global的权重应该要大于antd自带样式的权重。'

**Comment by xiaohuoni** [comment]
css类同名的情况下，global的权重应该要大于antd自带样式的权重,小于page样式的权重。

**Comment by xiaohuoni** [comment]
node_module里面的样式，打成一个css文件，如a.css。然后项目中的样式打成一个b.css.这样global.css里面的内容，应该是放在b.css头部。然后页面上加载样式文件的顺序是a.css b.css。

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/pull/1279

**Comment by sorrycc** [comment]
@xiaohuoni @iceberg211 https://github.com/umijs/umi/issues/1649#issuecomment-448170459 有方案有效吗？

**Comment by xiaohuoni** [comment]
@sorrycc 和`#root` 包裹应该是一样的吧，按需加载，还是有问题的吧，还是说，我没理解这个方案？

**Comment by sorrycc** [comment]
我理解的是，加了 root 之后，优先级不是最高了吗？那就算先载入不也应该没有问题？

**Comment by xiaohuoni** [comment]
现在的表现是，加了root可以处理优先级问题，但是按需加载，好像会重新引入antd的样式，最终生效的是antd的样式

**Comment by iShawnWang** [comment]
emmmmmm, 我这里遇到了 global.less 不生效的问题... 审查元素, 并没有 global 里面的 全局样式... 有自查的建议吗... ?

**Comment by luckyyyyy** [comment]
@sorrycc  这个问题似乎依然还是存在？
