### ISSUE TITLE
react umi 项目升级antd v5后，项目报错运行不起来

### ISSUE THREAD

**Issue by Curry3O** [umijs/umi#10025]
这个项目中用到了@ant-design/pro-layout库中的一些组件（例如：PageContainer等）。报错原因是因为src下的 .umi 文件夹中有个文件引入了antd中不存在的主题less文件导致的（@import '~antd/es/style/themes/default.less';）
![image](https://user-images.githubusercontent.com/51936110/206842294-2c97bbd7-3227-44c0-b6d7-7e7ab10433bc.png)

package.json文件：
<img width="461" alt="image" src="https://user-images.githubusercontent.com/51936110/206842325-d3762bac-2b32-4e73-9ab2-116726295078.png">

请问这个问题需要如何解决？

**Comment by haobarry** [comment]
> 这个项目中用到了@ant-design/pro-layout库中的一些组件（例如：PageContainer等）。报错原因是因为src下的 .umi 文件夹中有个文件引入了antd中不存在的主题less文件导致的（@import '~antd/es/style/themes/default.less';） <img alt="image" width="1762" src="https://user-images.githubusercontent.com/51936110/206842468-7ae3ce02-fa8f-484e-a3ee-b8c6f591b7c9.png">
> 
> package.json文件： <img alt="image" width="461" src="https://user-images.githubusercontent.com/51936110/206842325-d3762bac-2b32-4e73-9ab2-116726295078.png">
> 
> 请问这个问题需要如何解决？

同问题
解决了没：》？

**Comment by fz6m** [comment]
umi 3 是不支持 antd 5 的，不维护了，建议升级到 umi 4
