### ISSUE TITLE
how to load .node file in umi？

### ISSUE THREAD

**Issue by GuoxiongZhang** [umijs/umi#10037]
1. I use N-API to generate .node file
2. it works normally in js.
like this:  
let { setPrinter } = require('./build/Release/napi_printer.node');
console.log(setPrinter('printerName', 210, 297));
3. add node-loader at .umirc.ts
chainWebpack(config) {
config.module.rule('node-loader')
.test(/\.(node)$/)
.use('node-loader?name=[path][name].[ext]')
.loader('node-loader')
.end()
}
4. import .node file at index.tsx
import {setPrinter} from './napi_printer.node';
5. use this function at component
console.log(setPrinter) ; // output is undefined
6. I also try to use require in index.tsx, also got undefined.

**Comment by fz6m** [comment]
给最小复现看看
