### ISSUE TITLE
[Bug]umi3.5.35在部分安卓7手机上build之后打开白屏

### ISSUE THREAD

**Issue by CassielLee** [umijs/umi#10042]
## What happens?
umi3.5.35版本，创建项目然后build之后部署到测试环境之后打开白屏，控制台报错：umi.js文件的第35行 Uncaught SyntaxError: Unexpected token )

## Mini Showcase Repository(REQUIRED)
https://github.com/z-Joy/umi-demo
https://codesandbox.io/s/focused-tamas-qv3csu?file=/package.json
就是官网的demo，没有添加任何其他配置或者只依赖

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
1、yarn create @umijs/umi-app
2、yarn build
3、部署到测试环境

**Expected behavior** 1. 2.
错误日志：umi.js文件第35行，Uncaught SyntaxError: Unexpected token )
![image](https://user-images.githubusercontent.com/26957138/207219775-3166473c-4175-4af5-a552-274937604c6f.png)

## Context

- **Umi Version**:3.5.35
- **Node Version**:14.16.0
- **Platform**:安卓7 浏览器内核55

**Comment by CassielLee** [comment]
已经提供最小复现仓库了，为何还是要关闭？

**Comment by CassielLee** [comment]
> 
https://github.com/z-Joy/umi-demo

**Comment by xiaohuoni** [comment]
可以通过 targets 配置支持低版本浏览器，比如尝试加上 
```
   targets: {
       ie: 9,
    },
```

**Comment by CassielLee** [comment]
> 可以通过 targets 配置支持低版本浏览器，比如尝试加上
> 
> ```
>    targets: {
>        ie: 9,
>     },
> ```

配置了也不行，我们测试了多种机型发现主要是华为品牌，安卓7及以下版本的手机页面白屏，错误都是是同一个：打包生成的umijs文件第35行，Uncaught SyntaxError: Unexpected token )
