### ISSUE TITLE
[Bug] umi4 useSearchParams 或 history.location.search 获取url上的query丢失字符

### ISSUE THREAD

**Issue by Xierruisi** [umijs/umi#10052]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

<img width="859" alt="image" src="https://user-images.githubusercontent.com/51395487/207407943-b0a2f737-9928-4648-974a-1a7a7e7c68ad.png">

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/51395487/207408126-c7ad1a75-dbeb-4354-a416-30377c95285f.png">

## Context

- **Umi Version**: 4.0.23
- **Node Version**: 16.16.0
- **Platform**: macos edge

**Comment by fz6m** [comment]
附加 url query 的时候提前 `encodeURIComponent(string)` 转义一下。

```ts
  encodeURIComponent('a+b')
```
