### ISSUE TITLE
[Bug] umi 4 开启exportStatic后直接访问二级路由404

### ISSUE THREAD

**Issue by qinhuaihe** [umijs/umi#10061]
## What happens?

开启exportStatic后打包发布网站，在浏览器中访问`http://localhost:8523/home/`后跳转到`http://localhost:8523/home/test`可以正常显示，但是直接访问`http://localhost:8523/home/test`会显示404.

![WeChat Screenshot_20221214203623](https://user-images.githubusercontent.com/18019463/207601025-1f403e41-5dbe-4e1d-9c6d-282a0fd5a889.png)

![WeChat Screenshot_20221214203646](https://user-images.githubusercontent.com/18019463/207600431-9c856635-fdbc-46e0-a530-e0baead4ddd5.png)

## Mini Showcase Repository(REQUIRED)

> [问题复现仓库](https://github.com/qinhuaihe/umi4-export-static-bug)

## Context

- **Umi Version**: @umijs/max 4.0.36
- **Node Version**: 14.17.4
- **Platform**: windows 10

**Comment by tsuyoii** [comment]
请问一下解决了嘛，这问题很头疼啊，刷新一下页面就白屏

**Comment by fz6m** [comment]
如有问题，需要给一个最小复现。
