### ISSUE TITLE
[Feature Request] 支持ant5 StyleProvider

### ISSUE THREAD

**Issue by leshalv** [umijs/umi#10075]
https://ant.design/docs/react/customize-theme-cn#%E5%85%BC%E5%AE%B9%E6%80%A7%E8%B0%83%E6%95%B4

**Comment by fz6m** [comment]
在 `src/app.tsx` 的 [`rootContainer`](https://umijs.org/docs/api/runtime-config#rootcontainerlastrootcontainer-args) 可以自己包一层

**Comment by fz6m** [comment]
通过 [`rootContainer`](https://umijs.org/docs/api/runtime-config#rootcontainerlastrootcontainer-args) 添加新的 Provider ，通过 [运行时配置](https://umijs.org/docs/max/antd#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE) 修改 antd 主题。

**Comment by susanforme** [comment]
> 通过 [`rootContainer`](https://umijs.org/docs/api/runtime-config#rootcontainerlastrootcontainer-args) 添加新的 Provider ，通过 [运行时配置](https://umijs.org/docs/max/antd#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE) 修改 antd 主题。
![image](https://user-images.githubusercontent.com/51266600/217449294-529a6f90-2ce0-4de1-bed1-bf98f4e2a229.png)

app.tsx 导出报错
```tsx
export const antd = (memo) => {
  console.log('antd', memo);
  return memo;
};
```

**Comment by UmbraCi** [comment]
> 通过 [`rootContainer`](https://umijs.org/docs/api/runtime-config#rootcontainerlastrootcontainer-args) 添加新的 Provider ，通过 [运行时配置](https://umijs.org/docs/max/antd#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE) 修改 antd 主题。

可否给个例子呢，StyleProvider不知道在哪儿可以导入
