### ISSUE TITLE
umi4 中 class组件中路由match用什么替换

### ISSUE THREAD

**Issue by jiangkaifree** [umijs/umi#10083]
## What happens?

你好。我在升级迁移umi， 关于[迁移文档](https://umijs.org/docs/introduce/upgrade-to-umi-4#match) 中， 路由 `match` 在 function 中 能够使用 `useMatch` , 请问 class 组件中如何替换

**Comment by jiangkaifree** [comment]
在[这里](https://umijs.org/docs/api/api#matchpath)  找到了相关的 api 替换，后续是否考虑加入到 升级相关文档中。因为个人看来这将会是一个 在升级当中不可避免的问题

**Comment by fz6m** [comment]
class 组件外面包一下 function 组件，在函数组件里拿到再透传给 class 组件就行，做一个 HOC ，类似 `withRouter` 。

```ts
class Component {}
export default withRouter(Component)
```
