### ISSUE TITLE
antd pro6 紧凑模式不生效

### ISSUE THREAD

**Issue by pkaq** [umijs/umi#10100]
antd: {
    compact: true
  },

开启msfu不生效 不开启直接报错

**Comment by pkaq** [comment]
- ./node_modules/form-render/es/widgets/antd/timeRange.js:1:0-35

**Comment by fz6m** [comment]
antd 5 的主题需要运行时来改了，`.umirc.ts` 配置文件改不了。

等待 PR 合入后每周四新发版本（最早 12 月 22 日）即可实现你的需求。（ #10051 ）
