### ISSUE TITLE
[Bug] umi4 router路由配置icon需要重启项目icon才显示

### ISSUE THREAD

**Issue by HavocZhang** [umijs/umi#10107]
在ant-design-pro中
umi4 router路由配置icon需要重启项目icon才显示
![image](https://user-images.githubusercontent.com/27353058/208443292-36874e88-17b2-4bc9-9169-f7b59e11d9d0.png)
![image](https://user-images.githubusercontent.com/27353058/208443382-ae7055c5-d5b0-48af-9dea-bf2a5e69016e.png)

## Context

![image](https://user-images.githubusercontent.com/27353058/208443643-1eadafde-f7bc-4470-b788-6831c7fc2a9d.png)

**Comment by BoyYangzai** [comment]
@xiaohuoni 快来修bug😭

**Comment by xiaohuoni** [comment]
详见 https://github.com/umijs/umi/issues/10137

**Comment by nede-amber** [comment]
> 在ant-design-pro中 umi4 router路由配置icon需要重启项目icon才显示 ![image](https://user-images.githubusercontent.com/27353058/208443292-36874e88-17b2-4bc9-9169-f7b59e11d9d0.png) ![image](https://user-images.githubusercontent.com/27353058/208443382-ae7055c5-d5b0-48af-9dea-bf2a5e69016e.png)
> 
> ## Context
> ![image](https://user-images.githubusercontent.com/27353058/208443643-1eadafde-f7bc-4470-b788-6831c7fc2a9d.png)

这个问题我也遇到，是框架问题吗？

**Comment by fz6m** [comment]
如有不能热更新的问题可以把 umi 的依赖升级到最新版本再试试。

如还有问题，需要给一个最小复现。
