### ISSUE TITLE
用了ejs文件onClick点击事件不生效

### ISSUE THREAD

**Issue by 1320611670** [umijs/umi#10101]
所有点击事件不生效

## Mini Showcase Repository(REQUIRED)
https://github.com/1320611670/officialwebsite
> 

## How To Reproduce
![image](https://user-images.githubusercontent.com/77874445/208343063-9d39e758-bfdf-4fee-baab-76a2c063be48.png)
![image](https://user-images.githubusercontent.com/77874445/208343196-33c92b24-23f4-4c06-b822-f8d0028b648e.png)

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:   "^3.5.35"
- **Node Version**: v16.16.0
- **Platform**: win11

**Comment by BoyYangzai** [comment]
我跑了你的项目，打印正常 Click事件正常
![image](https://user-images.githubusercontent.com/94534613/208416100-ba2ad49c-1542-4bbf-9507-cfea8952d7d2.png)
