### ISSUE TITLE
[Umi4] 在function中使用状态管理数据 

### ISSUE THREAD

**Issue by GuanJdoJ** [umijs/umi#10117]
1 umi4提供了useModel数据流来管理全局数据，但hook无法在getInitialState/封装axios函数等中使用
2 umi3中提供了getDvaApp方法协助获取dva实例，但是在@umi/max中没有此方法导出

版本："@umijs/max": "^4.0.36"

希望官方能在max中提供一个类似getDvaApp的方法，能让我们在函数中使用

**Comment by fz6m** [comment]
任意地方都能使用的方案：https://umijs.org/docs/max/valtio
