### ISSUE TITLE
[Bug] 自动生成的类型文件pluginConfig.d.ts有错误 

### ISSUE THREAD

**Issue by baihech** [umijs/umi#10125]
"umi": "^4.0.36",
.umi/core/pluginConfig.d.ts
https://github.com/umijs/umi/pull/69 runtimePublicPath?: {

}
https://github.com/umijs/umi/issues/92 runtimePublicPath?: boolean

如果按照文档 https://v3.umijs.org/zh-CN/config#runtimepublicpath 配置，会提示类型错误，runtimePublicPath应为Object

Mini Showcase Repository(REQUIRED)
无

How To Reproduce
无

**Comment by baihech** [comment]
这样会导致，build后，只会加载umi.chunk.js，不会加载其他的css和js，也获取不到runtimePublicPath变量

**Comment by mysteryven** [comment]
你安装的是 V4，好像应该看 V4 的文档：https://umijs.org/docs/api/config#runtimepublicpath

**Comment by fz6m** [comment]
See #10124
