### ISSUE TITLE
[Bug] 自动生成的类型pluginConfig.d.ts错误

### ISSUE THREAD

**Issue by baihech** [umijs/umi#10124]
## What happens?

"umi": "^4.0.36",
.umi/core/pluginConfig.d.ts
#69 runtimePublicPath?: {

}
#92 runtimePublicPath?: boolean

如果按照文档 https://v3.umijs.org/zh-CN/config#runtimepublicpath 配置，会提示类型错误，runtimePublicPath应为Object

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
这个功能在开启 `qiankun: {}` 的时候会自动打开，如果确实有手动开启的需求，可以这么开启：

```ts
  runtimePublicPath: {}
```
