### ISSUE TITLE
[Bug] routes 里修改 icon 后图标不会重加载

### ISSUE THREAD

**Issue by fz6m** [umijs/umi#10137]
## Mini Showcase Repository(REQUIRED)

与 layout 插件一起使用时，`icon` 字段的修改不会刷新生效。因为 `appData.routes` 不会刷新。

```ts
  routes: [
     {
         path: '/',
         icon: 'smile' // 修改后不会刷新生效
     }
  ]
```

## Context

- **Umi Version**: 4.0.40

**Comment by xiaohuoni** [comment]
重复了 https://github.com/umijs/umi/issues/10107
具体原因是 在 api.onGenerateFiles 里面二次生成的时候获取到的 api.appData 是初始值的问题，早上群里有讨论，说用 getRoutes 获取 route ，但我觉得不合理

**Comment by vominhtrius** [comment]
hi @xiaohuoni ,
I want to ask you, does umij max support icons in submenu or not? i tried it and it only shows in the parent menu.
Thanks.

```js
 {
      path: '/admin-management',
      name: 'admin-mgt',
      access: 'isAdmin',
      icon: 'SettingOutlined',
      routes: [
        {
          name: 'users',
          path: '/admin-management/users',
          component: './admin-mgt/users',
          icon: 'UserOutlined',
        },
        {
          name: 'login-histories',
          path: '/admin-management/login-histories',
          component: './admin-mgt/login-histories',
          icon: 'HistoryOutlined',
        },
        {
          name: 'finances',
          path: '/admin-management/finances',
          component: './admin-mgt/finances',
          icon: 'TagsOutlined',
        },
      ],
    },
```

<img width="279" alt="image" src="https://user-images.githubusercontent.com/19206968/209696860-b8dafcf3-5182-4d17-a76d-fd3eacf69cee.png">
