### ISSUE TITLE
[Bug]  ant design pro 脚手架使用微应用的子应用的警告这个问题， 不能正常渲染

### ISSUE THREAD

**Issue by 3338606790** [umijs/umi#10132]
<Router basename="/web-ebook-editor-v5"> is not able to match the URL "/scan/t4yyl" because it does not start with the basename, so the <Router> won't render anything.

config.ts的配置

 qiankun: {
    slave: {
    },
  },

- **Umi Version**:  "@umijs/max": "^4.0.33",

**Comment by fz6m** [comment]
给最小复现看看。
