### ISSUE TITLE
[Bug] ant配置无效d@5 theme 

### ISSUE THREAD

**Issue by hihuangwei** [umijs/umi#10145]
## What happens?

ant配置无效d@5 theme 

## Context

- **Umi Version**: 4.0.40
- **Node Version**: 
- **Platform**:

**Comment by fz6m** [comment]
See [运行时配置](https://umijs.org/docs/max/antd#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE)

**Comment by hihuangwei** [comment]
> See [运行时配置](https://umijs.org/docs/max/antd#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE)

在 antd pro@6  依然无法生效

**Comment by hihuangwei** [comment]
https://github.com/ant-design/ant-design-pro/issues/10413

**Comment by fz6m** [comment]
antd pro 需要按照 pro 的 layout 的方法配置，和 antd 无关。
