### ISSUE TITLE
code splitting的建议

### ISSUE THREAD

**Issue by Jeephe** [umijs/umi#1015]
目前只对dynamic import的组件打包产生独立文件，但是该组件直接或间接引用的组件，仍然被提到vendors文件中。对于比较大的项目，不分割文件，vendors会很大，如果每一组件都dynamic import，这样产生的文件太多，每个文件又很小，也不利于性能。
所以，能否考虑，如果一个子业务，有一个目录，一个入口组件，引用了该目录下的其他组件，打包的时候，将这个目录的相关文件打包在一个文件中。

**Comment by sorrycc** [comment]
有个性需求的可通过 chainWebpack 配置 optimization.splitChunks，文档参考 https://webpack.js.org/plugins/split-chunks-plugin/。
