### ISSUE TITLE
[Bug] @umijs/max和umi的4.x版本有什么区别呢？

### ISSUE THREAD

**Issue by wangzhengbo** [umijs/umi#10154]
@umijs/max和umi的4.x版本有什么区别呢？项目中package.json中需要配置依赖哪个？src中导入需要用哪个？
我看umi的example中2者都有用到

**Comment by fz6m** [comment]
这是两个东西，max === umi + 一堆插件内置了 。

所以用 umi 自己配插件也可以变成 max 。详见 [使用插件](https://umijs.org/docs/guides/use-plugins#%E4%BD%BF%E7%94%A8%E6%8F%92%E4%BB%B6)

如果是用的 `umi` 就是导入 `umi` ，如果是 `@umijs/max` 那就是导入 `@umijs/max` ，两者不能共存。

**Comment by wangzhengbo** [comment]
> 这是两个东西，max === umi + 一堆插件内置了 。
> 
> 所以用 umi 自己配插件也可以变成 max 。详见 [使用插件](https://umijs.org/docs/guides/use-plugins#%E4%BD%BF%E7%94%A8%E6%8F%92%E4%BB%B6)
> 
> 如果是用的 `umi` 就是导入 `umi` ，如果是 `@umijs/max` 那就是导入 `@umijs/max` ，两者不能共存。

我依赖中配置的@umijs/max, 使用pnpm安装的依赖。代码中import使用的umi，也是可以的。

**Comment by fz6m** [comment]
尽量不要这么用，这是一个隐式依赖。
