### ISSUE TITLE
[Feature Request] umi4打包进度显示

### ISSUE THREAD

**Issue by wangru-chen** [umijs/umi#10159]
## Background

umi4打包没有进度显示，空等对用户不友好

## Proposal

希望能有进度显示或者提供自定义的文档

**Comment by fz6m** [comment]
在 #10197 完成，等待下次发版即可使用。

**Comment by wangru-chen** [comment]
> 在 #10197 完成，等待下次发版即可使用。

现在首次编译和第二次编译的时间基本没有差别，umi4去除了缓存功能吗

**Comment by fz6m** [comment]
因为 webpack5 物理缓存需要考虑很多 edge case ，要和具体业务场景结合，很容易出现缓存不失效的问题。

如果需要，现在需要手动配置开启。

之前也有人问过这个问题，之后考虑我会补充下配置物理缓存的文档。

**Comment by wangru-chen** [comment]
> 因为 webpack5 物理缓存需要考虑很多 edge case ，要和具体业务场景结合，很容易出现缓存不失效的问题。
> 
> 如果需要，现在需要手动配置开启。
> 
> 之前也有人问过这个问题，之后考虑我会补充下配置物理缓存的文档。

手动怎么配置开启啊，期待有文档可以解惑答疑
