### ISSUE TITLE
umi4 build产物不能静态访问，白屏

### ISSUE THREAD

**Issue by QDyanbing** [umijs/umi#10164]
import { defineConfig } from '@umijs/max';
import routes from './routes';

export default defineConfig({
  npmClient: 'yarn',
  antd: {},
  model: {},
  routes,
  mfsu: { shared: { react: { singleton: true } } },
  locale: { default: 'zh-CN', antd: true },
  hash: true,
  title: '静态测试',

  runtimePublicPath: {},
  publicPath: './',
  exportStatic: {},
});

 runtimePublicPath: {},
  publicPath: './',
  exportStatic: {},
这三个参数无论怎么调整也做不到，build包点击html文件打开看到页面效果。一直白屏

https://github.com/QDyanbing/umifix

**Comment by fz6m** [comment]
1. 你给的最小复现 `umi dev` 跑不起来，请给一个 `umi dev` 真正可以跑起来的，且含有你所描述问题的最小复现。

2. 我删掉了一些文件，构建了之后是可以正常运行的。

**Comment by QDyanbing** [comment]
https://github.com/QDyanbing/umifix 已经调整了

**Comment by fz6m** [comment]
根据最新的仓库，我试了下：

```bash
  pnpm i
  pnpm build
  pnpm i -g serve
  serve ./dist
```

是没有问题的，可以正常访问产物，如果你是直接点击 html 查看，spa 应用是做不到的，必须依靠服务提供，他可能是本地的任意一种服务提供工具，也可能是服务器上的 nginx 等。

**Comment by QDyanbing** [comment]
我的本意就是希望不启服务来达到访问html页面的，umi3版本是可以的；加了exportStatic配置是能直接打开html页面的

**Comment by fz6m** [comment]
如果直接点开的话，当前路径是 file ，路由是匹配不上的。

**Comment by hql1070** [comment]
> 我的本意就是希望不启服务来达到访问html页面的，umi3版本是可以的；加了exportStatic配置是能直接打开html页面的

你好👋 你的问题解决了吗？

**Comment by zhangxinyong12** [comment]
他的意思是没有服务器托管静态资源吧。你可以用http-server
