### ISSUE TITLE
[Bug] Umi v4.0.40 重装依赖后，项目就无法运行了。

### ISSUE THREAD

**Issue by leshalv** [umijs/umi#10162]
Umi v4.0.40

<img width="704" alt="image" src="https://user-images.githubusercontent.com/30397655/209741378-becdc4ea-214d-48ef-a940-2d2ea5bdbb98.png">

**Comment by leshalv** [comment]
@stormslowly

**Comment by stormslowly** [comment]
@leshalv  复现方式有吗？

**Comment by leshalv** [comment]
> @leshalv 复现方式有吗？

使用 https://github.com/ant-design/ant-design-pro.git master 分支可复现。

**Comment by fz6m** [comment]
我升级到 `4.0.40` 后可以启动起来。

**Comment by leshalv** [comment]
很奇怪，感觉不是版本问题，降低max版本也不行。

**Comment by fz6m** [comment]
给一个最小复现看看，或者尝试关闭 `mfsu: false` 再看看有没有问题。

**Comment by leshalv** [comment]
> 给一个最小复现看看，或者尝试关闭 `mfsu: false` 再看看有没有问题。

使用 https://github.com/ant-design/ant-design-pro.git master 分支重装依赖运行可复现。

**Comment by leshalv** [comment]
关闭 mfsu:false 也不行

<img width="635" alt="image" src="https://user-images.githubusercontent.com/30397655/209896222-10da22a1-3170-4f4b-b4c9-7262796ea800.png">

**Comment by fz6m** [comment]
我这里没复现你说的问题，拉取 master 最新代码后：

```bash
  rm -rf ./pnpm-lock.yaml
  pnpm i
  pnpm start
```

正常运行。

**Comment by leshalv** [comment]
> 我这里没复现你说的问题，拉取 master 最新代码后：
> 
> ```shell
>   rm -rf ./pnpm-lock.yaml
>   pnpm i
>   pnpm start
> ```
> 
> 正常运行。

用yarn

**Comment by fz6m** [comment]
我是用 yarn v1 也是可以安装依赖运行的。

**Comment by leshalv** [comment]
> 我使用 yarn v1 也是可以安装依赖运行的。

奇怪，我mac，yarn版本1.22.19，nodejs版本v16.14.2

**Comment by leshalv** [comment]
我升级到node18也不行
