### ISSUE TITLE
[Bug] 切换路由微应用页面不更新

### ISSUE THREAD

**Issue by 426-330** [umijs/umi#10167]
更新Umi4后，使用路由绑定引入子应用时，在页面中通过事件切换路由时，子应用的页面没有更新，刷新页面正常
![image](https://user-images.githubusercontent.com/2107423/209889870-fe53d157-c6a3-4afa-8d93-8c54b542b5c1.png)

我的配置

`{
    sandbox: false,
    apps: [
      {
        name: 'workflow', // 唯一 id
        entry: IS_DEV ? 'http://localhost:8882' : '/apps/workflow', // html entry
        props: {
          ...getQiankunMasterState(),
        },
      },
      {
        name: 'visualization', // 唯一 id
        entry: IS_DEV ? 'http://localhost:8881' : '/apps/visualization', // html entry
        props: {
          ...getQiankunMasterState(),
        },
      },
    ],
    routes: [
      {
        path: '/apps/workflow/*',   //加不加 /* 都不行
        microApp: 'workflow',
        microAppProps: {
          autoSetLoading: true,
          wrapperClassName: 'app-wrapper',
          loader: (loading) => (loading && <PageLoadingComp />)
        }
      },
      {
        path: '/apps/visualization/*',   //加不加 /* 都不行
        microApp: 'visualization',
        microAppProps: {
          autoSetLoading: true,
          wrapperClassName: 'app-wrapper',
          loader: (loading) => (loading && <PageLoadingComp />)
        }
      },
    ],
    externals: {
      react: 'var window.React',
      'react-dom': 'var window.ReactDOM',
    },
  }`

**Comment by fz6m** [comment]
需要给一个最小复现。

**Comment by 426-330** [comment]
> 需要给一个最小复现。

Umi3好好的，更新就不行了。。。
