### ISSUE TITLE
请教umi的运行时配置

### ISSUE THREAD

**Issue by lovesL** [umijs/umi#10172]
## Background
我是来请教的 我很好奇几个运行时的函数是怎么实现 因为我觉得很有用  我经常用到 希望能简单解答一下 ，或是有没有相关文档贴个地址。  谢谢

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by fz6m** [comment]
给一个具体的业务场景或者需求场景，不明白你问的要解决什么问题，多提供一些上下文信息。
