### ISSUE TITLE
umi@2x图片编译后访问出问题

### ISSUE THREAD

**Issue by xyezir** [umijs/umi#1017]
重现步骤：
1、在jsx中import head from '../../assets/head.jpg'
2、img src 引用 {head}
3、npm run dev -> 通过egg plugin集成的umi ，运行 umi dev
4、访问浏览器，看到head.jpg编译后的图片变成了bg_new.jpg
具体看截图
head.png 是长这样的
![image](https://user-images.githubusercontent.com/5794890/45132126-4d182580-b1c2-11e8-8c97-0901dc4a46df.png)
访问的时候找不到图片，其实是因为head.jpg变成了bg_new.jpg
![image](https://user-images.githubusercontent.com/5794890/45132144-5dc89b80-b1c2-11e8-8249-08dd8e84390f.png)
访问图片浏览器截图
![image](https://user-images.githubusercontent.com/5794890/45132156-69b45d80-b1c2-11e8-90e7-4fcfd7fd4638.png)

**Comment by sorrycc** [comment]
看不出问题，感觉是和 egg 结合时出的问题，不是 umi 的问题。

**Comment by okoala** [comment]
应该访问 8000 端口，7001 是 egg 的

**Comment by popomore** [comment]
图片的应该也走 publicPath?
