### ISSUE TITLE
发版后，页面不刷新会报错，希望能监听这种异常，方便提示用户刷新页面

### ISSUE THREAD

**Issue by junegod** [umijs/umi#10170]
<img width="2575" alt="image" src="https://user-images.githubusercontent.com/2197929/209892922-5bc1ef8a-cf2c-4041-a7c8-21f93db44360.png">

**Comment by fz6m** [comment]
开启 [hash](https://umijs.org/docs/api/config#hash) 模式后，不要对 `index.html` 文件做缓存策略或者每次都校验缓存（请配置你的 nginx 或者与公司网关、运维联系），保证每次用户获取的 `index.html` 都是最新的。

**Comment by junegod** [comment]
> 

你是没明白，刷新页面肯定好了，我这是没刷新，index.html都没重新请求啊

**Comment by fz6m** [comment]
需要给一个最小复现排查问题。

**Comment by junegod** [comment]
> 需要给一个最小复现排查问题。

https://github.com/umijs/umi/issues/10171 看这个吧
