### ISSUE TITLE
自定义layout组件，props里拿不到config的routes，没办法自己实现菜单的渲染？

### ISSUE THREAD

**Issue by Johnnnnboy** [umijs/umi#10177]
## Background

项目中需要多个layout布局

## Proposal

项目中有多种layout的需求，那么就需要自定义layout组件，在layout组件内自己实现头部，菜单，底部。现在的问题在于layout组件的props是空的拿不到config的routes，这种情况下如何拿到routes并实现菜单的渲染呢？

## Additional context

![image](https://user-images.githubusercontent.com/107901138/209898204-b170d0db-8712-41e2-b8d4-a0c50261ca23.png)

**Comment by twinkle77** [comment]
umi3. 升级到 um4 会有这个问题，props 拿不到 route 信息了

我在看能不能通过 useAppData 来做

**Comment by SilentFlute** [comment]
可以通过`useLocation`来实现, 详情可查看文档: [react router_useLocation](https://reactrouter.com/en/main/hooks/use-location)

**Comment by fz6m** [comment]
[`useAppData`](https://umijs.org/docs/api/api#useappdata) 、[`useSelectedRoutes`](https://umijs.org/docs/api/api#useselectedroutes) ，从这些里面可以获取到，详见文档。

**Comment by SilentFlute** [comment]
> 

可以可以, 这也是个方法, 我都没留意到, 学到了

**Comment by SilentFlute** [comment]
> [`useAppData`](https://umijs.org/docs/api/api#useappdata) 、[`useSelectedRoutes`](https://umijs.org/docs/api/api#useselectedroutes) ，从这些里面可以获取到，详见文档。

可以可以, 这也是个方法, 之前都没留意到, 学到了

**Comment by SilentFlute** [comment]
> [`useAppData`](https://umijs.org/docs/api/api#useappdata) 、[`useSelectedRoutes`](https://umijs.org/docs/api/api#useselectedroutes) ，从这些里面可以获取到，详见文档。

可以可以, 之前都没留意到, 也是个方法, 学到了

只是我试了下, `useSelectedRoutes`, 获取当前路径命中的所有路由信息, 获取到的结果永远包含最外层的`/src/layout`, 然后才到`children`, 也就是获取到的结果是父路由和子路由, 这是合理的, 只是对于想直接获取到子路由做判断的情形似乎有些冗余了, 不如获取当前的位置信息, 也就是`location`信息来得直观
