### ISSUE TITLE
umi build 生成文件 __common-umi.e279e21c.async.js ，在 GitHub Page 无法加载

### ISSUE THREAD

**Issue by ThaddeusJiang** [umijs/umi#102]
使用 umi build 生成文件，部署到 GitHub Page 后无法正常显示。

error:
<img width="1054" alt="screen shot 2018-02-07 at 8 05 35" src="https://user-images.githubusercontent.com/17308201/35890676-1113f584-0be4-11e8-91f6-d4c22babcd2f.png">

<img width="1081" alt="screen shot 2018-02-07 at 8 04 37" src="https://user-images.githubusercontent.com/17308201/35890750-64b44de2-0be4-11e8-881b-2b060ac906c9.png">

github:
<img width="427" alt="screen shot 2018-02-07 at 8 58 47" src="https://user-images.githubusercontent.com/17308201/35890950-2aa82294-0be5-11e8-8f30-8a5eef2c51de.png">

**Comment by sorrycc** [comment]
是文件名的原因，辨识不出来？

**Comment by ThaddeusJiang** [comment]
是的，Chrome 和 Firefox 好像不会加载 `__common-umi.*.js` 文件。

我手动修改了文件名后，正常显示了。
<img width="1019" alt="screen shot 2018-02-07 at 9 06 35" src="https://user-images.githubusercontent.com/17308201/35891226-8cccc686-0be6-11e8-867a-b4a9264c3131.png">

**Comment by sorrycc** [comment]
所以，不能前面带两个下划线？

**Comment by ThaddeusJiang** [comment]
是的，前面带两个下划线的 js 文件，不能加载。

**Comment by sorrycc** [comment]
https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/
