### ISSUE TITLE
[Bug] 项目部署后404页面不显示

### ISSUE THREAD

**Issue by wangru-chen** [umijs/umi#10204]
## What happens?

项目部署后访问错误路由，显示空白页，应显示404页面

## Mini Showcase Repository(REQUIRED)

代码地址 https://github.com/wangru-chen/demo_umi4.git

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
`routes` 配置式路由需要自己配一个 `/*` 的路由匹配 404 ，没有自带 404 的这种机制。

**Comment by jintangWang** [comment]
![image](https://user-images.githubusercontent.com/12557847/215267184-cd6a19e8-06c3-458e-9794-04f23b689711.png)
这文档胡写的呢

**Comment by BosenY** [comment]
> ![image](https://user-images.githubusercontent.com/12557847/215267184-cd6a19e8-06c3-458e-9794-04f23b689711.png) 这文档胡写的呢

![image](https://user-images.githubusercontent.com/16064272/215306321-fe19c74d-cfb4-42e8-8c21-8e561fd602f2.png)
配置里面这样写一下即可

**Comment by jintangWang** [comment]
> > ![image](https://user-images.githubusercontent.com/12557847/215267184-cd6a19e8-06c3-458e-9794-04f23b689711.png) 这文档胡写的呢
> 
> ![image](https://user-images.githubusercontent.com/16064272/215306321-fe19c74d-cfb4-42e8-8c21-8e561fd602f2.png) 配置里面这样写一下即可

是的
