### ISSUE TITLE
[Bug] 使用pnpm安装项目，项目报错

### ISSUE THREAD

**Issue by leshalv** [umijs/umi#10214]
使用pnpm安装项目，项目报错

[ERROR] Cannot start service: Host version "0.15.18" does not match binary version "0.14.36"

<img width="836" alt="image" src="https://user-images.githubusercontent.com/30397655/210715871-4f96b324-5679-46f0-b722-323810555b48.png">

**Comment by fz6m** [comment]
给一下复现看看。这个问题把 `umi-presets-pro` 升级到 `"umi-presets-pro": "^2.0.0"` 来解决。

**Comment by fz6m** [comment]
我用 pro 脚手架创建了一个新项目，升级到 `4.0.41` 的 umi 依赖，没有这个 mock 报错。

**Comment by leshalv** [comment]
> 我用 pro 脚手架创建了一个新项目，升级到 `4.0.41` 的 umi 依赖，没有这个 mock 报错。

找到问题，如果配置   openAPI: [] 会出现这个错误，删除就好了。

**Comment by mashirozx** [comment]
> 我用 pro 脚手架创建了一个新项目，升级到 `4.0.41` 的 umi 依赖，没有这个 mock 报错。

麻烦把 umirc 发一份来看看呗

**Comment by leshalv** [comment]
经过排查应该是 requestRecord 未配置导致的，事实上我并不需要开启这个配置，这里应该优化下。

**Comment by leshalv** [comment]
> 可以到 [umi-presets-pro](https://github.com/umijs/umi-presets-pro) 反馈下，`@umijs/request-record` 这个插件的开启机制是只要配了 `proxy` 就会默认开启，但是我没找到 `@umijs/request-record` 的代码仓库。

我也没找到代码仓库....
