### ISSUE TITLE
[Bug] umi/max 菜单配置icon不生效，显示成字符串

### ISSUE THREAD

**Issue by dinglino1** [umijs/umi#10217]
## What happens?
如题
![image](https://user-images.githubusercontent.com/25605948/210755788-3a18e20a-ba61-4526-bb3d-7afbf00bc61e.png)
![image](https://user-images.githubusercontent.com/25605948/210755841-61d78fcf-398a-4b13-812b-22628565daac.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:4.036
- **Node Version**:16.14
- **Platform**:

**Comment by fz6m** [comment]
在 #10137 跟进。
