### ISSUE TITLE
官网首页跳转文档，然后点浏览器的返回上一页就失效

### ISSUE THREAD

**Issue by dong-lufei** [umijs/umi#10216]
[返回](https://umijs.org/) 
点击 Docs  跳到 https://umijs.org/docs/introduce/introduce，然后此时点谷歌浏览器左上角的左箭头返回上一页失效

**Comment by fz6m** [comment]
因为 docs 按钮跳的是 `/docs` ，`/docs` 重定向到了 `/docs/introduce/introduce` ，所以 back 按钮只能返回 `/docs` ，没法返回 `/` 。

欢迎提 PR 优化。

**Comment by mysteryven** [comment]
我周末试试 ~
