### ISSUE TITLE
[Bug] 设置了 publicPath，本地调试资源访问路径问题

### ISSUE THREAD

**Issue by hzyhbk** [umijs/umi#10225]
## What happens?
umi3项目中配置了 publicPath，本地启动，访问资源时通过 `http://localhost:8000/path/umi.js` 或 `http://localhost:8000/umi.js`都能访问到 js 文件

umi4项目中配置了 publicPath，本地启动，**只能**通过 `http://localhost:8000/path/umi.js` 访问到 js 文件，通过`http://localhost:8000/umi.js` 访问就返回了 index.html 的内容

## 期望
umi4 项目配置了 publicPath 也能访问到根目录`http://localhost:8000/umi.js`下的资源

**Comment by fz6m** [comment]
umi4 中是正确的行为，`publicPath` 的定义就是资源提供的路径。

**Comment by hzyhbk** [comment]
那 umi4 的项目有办法通过插件实现类似 umi3 的行为吗?只需要本地调试的时候可以通过 `http://localhost:8000/path/umi.js` 或者 `http://localhost:8000/umi.js` 访问到 `umi.js` 和 `umi.css`

**Comment by fz6m** [comment]
可以，自己写个 middleware ，用项目级插件 `${projectRoot}/plugin.ts` ：

```ts
import { IApi } from https://github.com/umijs/umi

export default (api: IApi) => {
  api.onBeforeMiddleware(({ app }) => {
    app.use((req, res, next) => {
      // req.url === '/umi.js'
      // ... 请求 `publicPath/umi.js` 响应 or redirect 重定向
    })
  })
}
```

**Comment by hzyhbk** [comment]
万分感谢，解决了我的问题~~
