### ISSUE TITLE
[Bug] umi@4.0.42 版本，本地启动和热更新的时候控制台不会有Compiled的提示

### ISSUE THREAD

**Issue by sereinDS** [umijs/umi#10222]
## What happens?

______________
umi@4.0.42 版本，本地启动和热更新的时候控制台都不会有Compiled的提示了，在编辑代码时不知道自己的保存已经生效了。
关联PR：#10197 , 在这个PR对应的commit中 移除了ProgressPlugin

具体如下图所示
![image](https://user-images.githubusercontent.com/46836745/210938253-627164eb-9327-47aa-bd1d-4725e30f935e.png)
umi@4.0.41 及之前的版本是有的
![image](https://user-images.githubusercontent.com/46836745/210937884-06b9a638-7201-4721-af01-e0e442cfad6c.png)

## Mini Showcase Repository(REQUIRED)
umi最简单的demo，但是mfsu设置为false
[git: umi-simple-demo-mfsu-false](https://github.com/sereinDS/umi-simple-demo-mfsu-false)

## How To Reproduce
启动项目并触发热更新

## Context
- **Node Version**: v14.17.6
- **Platform**: macOS 12.13.1

**Comment by AkaraChen** [comment]
我这边跑了下复现，实际上的情况是 compiled 提示没了，无论 mfsu 开没开，不过 mfsu 开的时候热更新还是会打印 `skip buildDeps`

**Comment by liangskyli** [comment]
新增 build 流程下会出现构建进度条----应该是这个提交改动引起的

**Comment by sereinDS** [comment]
> 我这边跑了下复现，实际上的情况是 compiled 提示没了，无论 mfsu 开没开

确实是这样的，因为那个提交添加了构建阶段env === 'production'的 webpackBar之后，把ProgressPlugin删掉了(＞人＜;)
