### ISSUE TITLE
[Feature Request] @umijs/lint 支持 typescript 4.9 

### ISSUE THREAD

**Issue by chenzhenjia** [umijs/umi#10223]
package.json
```
    "@umijs/lint": "^4.0.34",
    "@umijs/max": "^4.0.33",
    "typescript": "^4.9.4",
```
执行eslint --fix 会报警告，并且好像没有效果

```
> eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src 

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.9.0

YOUR TYPESCRIPT VERSION: 4.9.4

Please only submit bug reports when using the officially supported version.

```
我看到 `@typescript-eslint/typescript-estree` 已经支持 typescript 4.9 了 typescript-eslint/typescript-eslint#5688

**Comment by andyFang94** [comment]
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0

YOUR TYPESCRIPT VERSION: 5.2.2

Please only submit bug reports when using the officially supported version. 



@chenzhenjia 
更新速度太快了  再来一版
