### ISSUE TITLE
如何实现依赖性models的初始化

### ISSUE THREAD

**Issue by zhangqianliang** [umijs/umi#1023]
现在有一个需求：
全局layouts的models app.js请求加载一些服务的配置信息。然后在其他children页面依赖models app.js的配置信息来请求具体的数据。请问这中依赖其他model数据的需求如何实现？谢谢。🙏。

现在直接在a页面的model层select app 的数据都是空的。设置延时的话，太不友好了。谢谢。🙏。

**Comment by zhangqianliang** [comment]
@xiaohuoni 有这方面的文档吗？谢谢。

**Comment by xiaohuoni** [comment]
@zhangqianliang 感觉我的方案也是临时性的。我是这么处理的。路由/指向了一个空的页面（有一个loadding图标），然后触发监听，发起全局model里面的一个方法，等待数据完成，跳转到之前路由/指向的页面。

**Comment by xiaohuoni** [comment]
@sorrycc 老大再看一眼吧！嘻嘻嘻

**Comment by sorrycc** [comment]
在 #1051 跟进，我觉得 #1051 应该能解决这个问题。
