### ISSUE TITLE
[Bug] yarn dev 可以正常启动 yarn build 报错

### ISSUE THREAD

**Issue by Huhui-coder** [umijs/umi#10230]
## What happens?
yarn dev 可以正常启动 yarn build 报错
<img width="918" alt="image" src="https://user-images.githubusercontent.com/37322200/210997031-5a04a7cd-a0da-4276-8ae6-7b46216549f5.png">

## Mini Showcase Repository(REQUIRED)

https://github.com/i4de/iThings-admin-react/tree/framework-update

## How To Reproduce

git clone https://github.com/i4de/iThings-admin-react.git
git checkout framework-update
yarn 
yarn build

## Context

- **Umi Version**:     "@umijs/max": "^4.0.0",
- **Node Version**: node/14.19.1
- **Platform**: macos

**Comment by fz6m** [comment]
你这个项目有私有源，并且太大了，我启动不起来，给一个最小复现。

你这个是 SPA 的话不需要 `exportStatic` 这个选项，删了再构建看看。

**Comment by zhengzhou** [comment]
我也遇到这个问题，排查发现routes配置中有个route没设置path

**Comment by fz6m** [comment]
如还有问题，提一个新 issue 给一个可以跑起来的最小复现，先关闭了。
