### ISSUE TITLE
自定义路由 Routes

### ISSUE THREAD

**Issue by yuandapeng** [umijs/umi#1025]
开发环境中，使用umirc.js 配置routes ，在routes中配置Routes权限路由无效

**Comment by xiaohuoni** [comment]
请问你怎么配置的

**Comment by yuandapeng** [comment]
umirc.js

![image](https://user-images.githubusercontent.com/11659997/45217739-c3f31280-b2d7-11e8-8c74-90d6a7799207.png)

.umi/router.js

![image](https://user-images.githubusercontent.com/11659997/45217775-e4bb6800-b2d7-11e8-99e6-b2d6f2067f67.png)

项目结构
![image](https://user-images.githubusercontent.com/11659997/45217789-f866ce80-b2d7-11e8-8872-3b571340020c.png)

**Comment by xiaohuoni** [comment]
没有Routes，这个配置吧？

**Comment by yuandapeng** [comment]
![image](https://user-images.githubusercontent.com/11659997/45250009-c6e41680-b35c-11e8-9fc2-ff1572a8e235.png)

**Comment by xiaohuoni** [comment]
这个routes是外面的，不是umi-plugin-react里面的
https://umijs.org/zh/guide/router.html#%E9%85%8D%E7%BD%AE%E5%BC%8F%E8%B7%AF%E7%94%B1
把你umi-plugin-react里面的routes拿到外面就可以了
