### ISSUE TITLE
[umi@2] umi -v 会执行调用或执行 .umirc.js 文件

### ISSUE THREAD

**Issue by amily4555** [umijs/umi#1026]
![image](https://user-images.githubusercontent.com/2802841/45194676-a47fc980-b286-11e8-8109-0f9466d62b19.png)

如图，因为我的umirc中需要读取一些环境变量，所以调用错误

**Comment by amily4555** [comment]
另 启动或编译的时候 读取了2次 umirc.js 文件

![image](https://user-images.githubusercontent.com/2802841/45195153-df82fc80-b288-11e8-8a43-9eabb7275954.png)

**Comment by amily4555** [comment]
```
const env = process.env.MRI_ENV;
const device = process.env.MRI_DEVICE;
```
需要从环境变量读一些信息

-- 

使用 cross-env MRI_ENV=test MRI_DEVICE=pc umi -v 或 umi dev 就没有问题

--

问题关键是 umi -v 怎么会去读取 umirc.js 信息，是不是没有走相关信息判断？

**Comment by sorrycc** [comment]
`umi -v` 即 `umi version`，是通过插件实现的，读取 `.umirc` 是正确的逻辑，你需要在 `.umirc` 里做兼容处理。
