### ISSUE TITLE
[Bug] monorepo formily less resolver error

### ISSUE THREAD

**Issue by nfwyst** [umijs/umi#10263]
<img width="1500" alt="截屏2023-01-10 18 58 14" src="https://user-images.githubusercontent.com/35720450/211533705-2ed7ea3d-d7cb-47dc-b752-23378b5ec04d.png">

找不到样式文件

**Comment by fz6m** [comment]
给一个最小复现看看

**Comment by dayuy** [comment]
项目的less文件中使用 "～antd/..."：
`@import '~antd/lib/modal/style/index.less';`
会出现报错信息：
`
Webpack resolver error details:
resolve '~antd/lib/modal/style/index.less' in 'work/console/src'
  Parsed request is a module
  using description file: work/console/package.json (relative path: ./src)
    using description file: work/console/package.json (relative path: ./src/~antd/lib/modal/style/index.less)
      no extension
        work/console/src/~antd/lib/modal/style/index.less doesn't exist
      .less
        work/console/src/~antd/lib/modal/style/index.less.less doesn't exist
      .css
        work/console/src/~antd/lib/modal/style/index.less.css doesn't exist
      as directory
        work/console/src/~antd/lib/modal/style/index.less doesn't exist
    resolve as module
`
依赖版本：
 @umijs/max@4.0.47
 @umijs/bundler-webpack@4.0.47

**Comment by dayuy** [comment]
> 给一个最小复现看看

项目的less文件中使用 "～antd/..."：
`@import '~antd/lib/modal/style/index.less`;
会出现报错信息：
`Webpack resolver error details: resolve '~antd/lib/modal/style/index.less' in 'work/console/src' Parsed request is a module using description file: work/console/package.json (relative path: ./src) using description file: work/console/package.json (relative path: ./src/~antd/lib/modal/style/index.less) no extension work/console/src/~antd/lib/modal/style/index.less doesn't exist .less work/console/src/~antd/lib/modal/style/index.less.less doesn't exist .css work/console/src/~antd/lib/modal/style/index.less.css doesn't exist as directory work/console/src/~antd/lib/modal/style/index.less doesn't exist resolve as module`
依赖版本：
@umijs/max@4.0.47
@umijs/bundler-webpack@4.0.47

**Comment by xiaohuoni** [comment]
antd 版本是 5.x 吧？

**Comment by fz6m** [comment]
`antd` 5 的话，升级一下最新版本的 `umi` 依赖看一下，在 antd 5 中是 css in js 生成样式，无需手动导入任何 antd 样式，css 和 ts 中写的 antd style import 都可以去掉。

**Comment by nfwyst** [comment]
> `antd` 5 的话，升级一下最新版本的 `umi` 依赖看一下，在 antd 5 中是 css in js 生成样式，无需手动导入任何 antd 样式，css 和 ts 中写的 antd style import 都可以去掉。

@formily/antd 这个 package 中使用了 import 的方式

**Comment by fz6m** [comment]
那就降级项目中的 `antd` 依赖版本到 4 ，全局只有唯一的 antd 。
