### ISSUE TITLE
[Bug] umi4 模块联邦的接入方，远端模块报dispatcher找不到的错误

### ISSUE THREAD

**Issue by SunQi0415** [umijs/umi#10262]
"@umijs/max": "^4.0.21",（导出方和接入方，都使用的这个版本）
我在模块联邦的导出组件中使用useModel，内部源码报错，求助下大佬

报错信息如下：
<img width="527" alt="Screenshot 2023-01-10 at 6 41 02 PM" src="https://user-images.githubusercontent.com/14801485/211530175-6c52ead3-5f9f-4e6c-912b-ef346a866b10.png">
<img width="523" alt="Screenshot 2023-01-10 at 6 41 18 PM" src="https://user-images.githubusercontent.com/14801485/211530200-1ce82d7b-19e0-4fc3-8091-4bf9a1b62524.png">

```javascript
import { useModel } from '@umijs/max';
const { setCurrentAction, openModal } = useModel('visualizer');
```

**Comment by stantoxt** [comment]
发布之后报这个错怎么处理
