### ISSUE TITLE
[Bug] umi4 模块联邦的接入方，远端模块报dispatcher找不到的错误

### ISSUE THREAD

**Issue by SunQi0415** [umijs/umi#10270]
## What happens?

我在模块联邦的导出组件中使用useModel，内部源码报错

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

1. 导出方
配置：
```javascript
mf: {
    name: 'mfAdminWeb',

    // 配置 MF 共享的模块
    shared: {
      react: {
        singleton: true,
        eager: true,
        requiredVersion: '^17.0.0',
      },
      'react-dom': {
        singleton: true,
        eager: true,
        requiredVersion: '^17.0.0',
      },
    },
  },
```
目录结构：
<img width="368" alt="Screenshot 2023-01-11 at 11 10 06 AM" src="https://user-images.githubusercontent.com/14801485/211709078-2df8409c-2467-426a-992c-7f2e58df557c.png">

导出的组件：
```javascript
import { useModel } from '@umijs/max';
```

3. 接入方
配置：
```javascript
mf: {
    remotes: [
      {
        name: 'mfAdminWeb',
        entry: 'http://localhost:8081/remote.js',
      },
    ],
    // 配置 MF 共享的模块
    shared: {
      react: {
        singleton: true,
        eager: true,
        requiredVersion: '^17',
      },
      'react-dom': {
        singleton: true,
        eager: true,
        requiredVersion: '^17',
      },
    },
  },
```

接入的代码：
```javascript
import { safeMfImport } from '@umijs/max';

const { HomepageVisualizer } = await safeMfImport('mfAdminWeb/components', {
  default: null,
});

const App = ( ) => {
  return (
    <div>
      <HomepageVisualizer />
    </div>
  );
} 
```

## How To Reproduce

**Steps to reproduce the behavior:** 
同时启动两个项目，代码按照上面的步骤

**Expected behavior**

![image](https://user-images.githubusercontent.com/14801485/211709715-20c6a179-5c14-445c-9948-3d4f73b3ed85.png)## Context
![image](https://user-images.githubusercontent.com/14801485/211709742-82c3a1ef-d2e6-4240-a750-07397da8cc46.png)

- **Umi Version**: 4.0.21
- **Node Version**: 16.14.2
- **Platform**:  Google Chrome 108.0.5359.124 (Official Build) (arm64)

**Comment by stantoxt** [comment]
我通过 max build 发布之后，报这个错，dev状态运行正常
`Uncaught TypeError: Cannot read properties of null (reading 'dispatcher')
    at Je (p__pc__index.30f1326f.async.js:formatted:1034:23)
    at Yn (p__pc__index.30f1326f.async.js:formatted:1728:21)
    at yu (umi.a89407da.js:77:19935)
    at Cc (umi.a89407da.js:79:44917)
    at Oc (umi.a89407da.js:79:40560)
    at _c (umi.a89407da.js:79:40488)
    at Hs (umi.a89407da.js:79:40342)
    at Uu (umi.a89407da.js:79:36622)
    at yc (umi.a89407da.js:79:35573)
    at W (umi.a89407da.js:79:86703)`
23行 对应` var r = (0,l.useContext)(Qe), e = r.dispatcher, s = (0, l.useRef)(a);`
21行对应`, o = Je("@@initialState")`

**Comment by stantoxt** [comment]
主要是 混用了 umi plugin 和umi/max导致的问题，同意成max 发布就可以了

**Comment by iwalking11** [comment]
同样的问题，全部用umi/max还是没有解决

**Comment by stormslowly** [comment]
问题应该是在于 你用了 model 功能，model 是基于 React Context ，但是 mf 无法拿到 host 应用的 Host 的所以 useModel 就会有问题。
建议使用 Valtio 做数据流管理。
