### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by wojoc** [umijs/umi#10278]
**umi3.5.36 使用@alitajs/keep-alive**
import * as app from '@/app';
提示找不到@/app

![image](https://user-images.githubusercontent.com/65233821/211964201-b54feabb-ce62-47e7-b0c0-2e7c6fe05d52.png)

umi3出现一直找不到@/app的情况，删除依赖包重新install依旧报错，望回复，感谢

## Context
- **umi 3.5.36**:
- **node v16.16.0**:
- **Platform**:

**Comment by fz6m** [comment]
可以到这里问问 https://github.com/alitajs/alita

**Comment by a992681784** [comment]
@fz6m 请问下 umi4有计划加上keepalvie功能吗？感觉在某些场景下还有很有用的

**Comment by fz6m** [comment]
没有计划， [alita](https://github.com/alitajs/alita/blob/master/packages/plugins/src/keepalive.ts) 的插件应该可以满足 keepalive 需求的。
