### ISSUE TITLE
[Feature Request] Export ModuleFederationPlugin from @umijs/bundler-webpack

### ISSUE THREAD

**Issue by hstarorg** [umijs/umi#10280]
## Background

When I use `@umijs/bundler-webpack` to build a react app with module federation, I used the code like:
```js
const { build } = require('@umijs/bundler-webpack');
const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederationPlugin');
```
But I get an error: "block.getRootBlock is not a function", error detail see: https://github.com/webpack/webpack/issues/14577
The reason is that more than one webpack version are in build process.

## Proposal

Export `ModuleFederationPlugin` from `@umijs/bundler-webpack` package, then I can import `ModuleFederationPlugin` like code: 
```
const { build, ModuleFederationPlugin } = require('@umijs/bundler-webpack');
```
## Additional context
When I lock the local webpack version same to `@umijs/bundler-webpack`, the build is ok.

**Comment by fz6m** [comment]
在 `build` 的 `chainWebpack` 方法里可以拿到 webpack 实例，这里面取：

```ts
build({
  chainWebpack(config, { webpack }) {
    config.plugin('mf-custom').use(webpack.container.ModuleFederationPlugin)
  }
})
```
