### ISSUE TITLE
[Bug] Umi4 用chainwebpack配置raw-loader后不生效，umi3正常

### ISSUE THREAD

**Issue by luangm** [umijs/umi#10299]
## What happens?

Umi4 用chainwebpack配置raw-loader后不生效，import bpmn文件只能得到一个文件名而不是里面的内容

## Mini Showcase Repository(REQUIRED)

https://github.com/luangm/umi-raw-loader-test

## How To Reproduce

1. 创建umi4项目：npx create-umi
2. 安装raw-loader：npm i raw-loader --save-dev
3. 配置chainwebpack：
  chainWebpack(config) {
    console.log("Chaining Webpack");
    config.module.rule('bpmn').test(/\.bpmn$/).use('raw').loader('raw-loader');
  }
4. 代码里import process1.bpmn，然后打印：
import bpmn from "@/process1.bpmn";
console.log("bpmn:", bpmn);

//打印结果：/static/process1.91ae5921.bpmn

## Context

- **Umi Version**: 4.0.44
- **Node Version**: v19.4.0
- **Platform**: MacOSX

**Comment by fz6m** [comment]
webpack 5 里没有 `raw-loader` 了，这是新的配置方法：

```ts
// .umirc.ts

export default {
  chainWebpack(config) {

    const REG = /\.bpmn$/

    config.module.rule('asset').exclude.add(REG).end();

    config.module
      .rule('bpmn')
      .test(REG)
      .type('asset/source')
      .end()

  },
};
```

FYI ：

 - [Umi4 ：怎么自定义 loader](https://umijs.org/docs/introduce/faq#%E6%80%8E%E4%B9%88%E8%87%AA%E5%AE%9A%E4%B9%89-loader)

 - [Asset Modules](https://webpack.js.org/guides/asset-modules/)
