### ISSUE TITLE
[Feature Request] esbuild 升级到 0.17.0

### ISSUE THREAD

**Issue by fz6m** [umijs/umi#10305]
## Background

esbuild 0.17.0 语法有 Breaking change ，需要改动所有使用 watch 的地方。

参考：https://github.com/evanw/esbuild/releases/tag/v0.17.0

做法：

1. 升级所有 esbuild 到 0.17.0

2. 改动所有 esbuild watch 的地方到新语法

**Comment by fz6m** [comment]
目前 vite 已 breaking 到 esbuild 0.17.x ，https://github.com/vitejs/vite/pull/11908

这个升级应该加上日程， @Chastrlove 如果有空的话，这个 PR 可以重开一下，没时间的话后面我来搞也行。

**Comment by Chastrlove** [comment]
> 目前 vite 已 breaking 到 esbuild 0.17.x ，[vitejs/vite#11908](https://github.com/vitejs/vite/pull/11908)
> 
> 这个升级应该加上日程， @Chastrlove 如果有空的话，这个 PR 可以重开一下，没时间的话后面我来搞也行。

新开了一个PR，xn review 下
