### ISSUE TITLE
[Feature Request] requestInterceptor支持异步

### ISSUE THREAD

**Issue by Hincex** [umijs/umi#10303]
## Background

请求拦截前会注入token，但是token的获取是异步的
``` ts
  async function requestInterceptor(url: string, options: RequestOptionsInit) {
    const token = await StorageUtil.get(TOKEN);
    ...
}
```
``` ts
// 这里的类型不匹配
export const request = {
  requestInterceptors : [requestInterceptor]
}
```
## Proposal
希望能修改一下类型

**Comment by fz6m** [comment]
你这里的请求发的时候都要去请求一次 token ，不合理的。

建议在应用启动的时候 `getInitialState` 中拿到 token ，set 到 [valtio](https://umijs.org/docs/max/valtio) 全局数据存储或者 local storage 里，之后从 local storage 或者 valtio 里同步的取。

**Comment by Hincex** [comment]
> 你这里的请求发的时候都要去请求一次 token ，不合理的。
> 
> 建议在应用启动的时候 `getInitialState` 中拿到 token ，set 到 [valtio](https://umijs.org/docs/max/valtio) 全局数据存储或者 local storage 里，之后从 local storage 或者 valtio 里同步的取。

`token`就是启动时候获取的 然后存储到了`storage` 只是因为用的是`localforage`这个库 他的获取是异步的 所以 才会有这个需求

**Comment by cp-apple** [comment]
+1，希望支持异步，我们有类似需求，需要在请求前处理异步数据..

**Comment by MANNIX-CHEN** [comment]
+1 我们也有数据源是需要异步获取的。

**Comment by esymeptoo** [comment]
这种场景可以初始化的时候获取token再初始化request插件
伪代码：
```
function setJwtToken(token) {
  request.interceptors.request.use() => {})
}
getToken().then((token) => { 
  setJwtToken(token)
})
```

**Comment by KelleyYe** [comment]
也遇到这个问题，因为请求的时候需要判断token是否过期，如果过期了需要先刷新一次token，拿到最新的token再用来继续完成之前的请求工作

**Comment by travisnguyen20** [comment]
+1. I got same issue as you @KelleyYe. Axios accepts Promise type as well. Please fix
