### ISSUE TITLE
[Bug] 页面报错后卡死，developer console 错误页面不显示

### ISSUE THREAD

**Issue by sogud** [umijs/umi#10312]
## What happens?

代码错误后页面报错后卡死，developer console 错误页面不显示
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/sogud/umi/commit/2211c238ec3bc2c39c8b79a1b2ff7b93cb937944
运行examples ant-design-pro 后复现
## How To Reproduce

https://github.com/sogud/umi/commit/2211c238ec3bc2c39c8b79a1b2ff7b93cb937944

4.0.40 版本不会复现
## Context

- **Umi Version**: 4.0.46
- **Node Version**: 14x
- **Platform**: macos

**Comment by fz6m** [comment]
这个变量不存在，所以会挂，代码需要是正常的逻辑。

**Comment by weicong** [comment]
安装  react-error-overlay@6.0.9 (锁定版本)
```
# NPM
npm install --save-dev react-error-overlay@6.0.9 --force

# YARN
yarn add react-error-overlay@6.0.9 --dev
```

package.json 增加
```
  "resolutions": {
    "react-error-overlay": "6.0.9"
  },
```

ps. 最好重新安装一遍依赖。

**Comment by enson0131** [comment]
是不是 iframe 覆盖了整个页面了？

**Comment by fz6m** [comment]
最新版本 `4.0.47` 不会有这个问题了。
