### ISSUE TITLE
[Bug] 打包后 不能本地打开

### ISSUE THREAD

**Issue by Gponder** [umijs/umi#10321]
## What happens?
打包后的文件不都是静态文件么，为什么本地都打不开呢？

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
有路由，本地打开匹配不上路由，需要本地起一个服务来分发静态文件。
