### ISSUE TITLE
[Bug] react query 插件 Windows 路径错误

### ISSUE THREAD

**Issue by fz6m** [umijs/umi#10323]
### 问题

react-query 插件 Windows 下路径错误

_Originally posted by @weicong in https://github.com/umijs/umi/issues/10253#issuecomment-1397942889_

### 解法

https://github.com/umijs/umi/blob/76ef321fee7f80b1bd385f7f3401c1c8585d92d1/packages/plugins/src/react-query.ts#L64-L65

https://github.com/umijs/umi/blob/76ef321fee7f80b1bd385f7f3401c1c8585d92d1/packages/plugins/src/react-query.ts#L108

https://github.com/umijs/umi/blob/76ef321fee7f80b1bd385f7f3401c1c8585d92d1/packages/plugins/src/react-query.ts#L132

https://github.com/umijs/umi/blob/76ef321fee7f80b1bd385f7f3401c1c8585d92d1/packages/plugins/src/styled-components.ts#L40

以上四处需要添加 `import { winPath } from '@umijs/utils'` ，参考：

https://github.com/umijs/umi/blob/76ef321fee7f80b1bd385f7f3401c1c8585d92d1/packages/plugins/src/valtio.ts#L21-L23

测试 windows 下能否跑通。

同时确认该部分逻辑能否在 win 下生效：

https://github.com/umijs/umi/blob/76ef321fee7f80b1bd385f7f3401c1c8585d92d1/packages/plugins/src/react-query.ts#L39

如果两者路径格式不一样，考虑用 `winPath` 处理。

**注：为防止重复 PR ，若认领该问题，请先在本 issue 回复 “认领”**

**Comment by BBBigCat** [comment]
认领
