### ISSUE TITLE
[Bug] mfsu 拦截 .json 并有缓存的问题

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#10329]
如何复现？

1、git clone git@github.com:sorrycc/weekly.git
2、安装依赖
3、把 mfsu 开回来，npx umi config set mfsu {}
4、npx umi dev
5、访问 /posts.json 。
6、修改 public/posts.json 文件
7、刷新 /post.json，会发现改动没有生效，期望是改动生效

而如果把 mfsu 关闭，重复 5-7 是会生效的。

**Comment by stormslowly** [comment]
pr  提了~ 

workardound 
 * 用 mfsu: { strategy: "normal"}
or

* 手动的删除下 `node_modules/.cache/mfsu/post.json`  如果 msfu 重建构建又会copy
```bash
$ls node_modules/.cache/mfsu/*.json | grep MFSU -v | xargs rm 
```

and  i drunk right now wish you good luck
