### ISSUE TITLE
[Feature Request] React package 里的homepage设置在umi里怎么操作

### ISSUE THREAD

**Issue by jmy2022** [umijs/umi#10328]
## Background

服务区有多个项目。默认代码是放在根目标，显然不能满足项目需求。所以要为没个项目设置homepage。
/project1/index.html
/project2/index.html

**Comment by fz6m** [comment]
`base` 和 `publicPath` 根据需求配置。

**Comment by jmy2022** [comment]
base  在最新版本设置无效啊，大兄弟

**Comment by jmy2022** [comment]
publicPath 生效了，base无效

**Comment by jmy2022** [comment]
> 

如果是这样，那么这个问题也算解决了
