### ISSUE TITLE
.umirc.mock.js与约定式mock互斥

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#1032]
现在的表现是：当存在.umirc.mock.js文件时，mock文件夹下的全部文件都失效。
这一点在文档中没有提到，当从umi1.x升级到2.0时，很容易出现错误。
```
Error: SyntaxError: Unexpected token < in JSON at position 0
```

**Comment by xiaohuoni** [comment]
@sorrycc 是在文档中说明，还是删除.umirc.mock.js的影响

**Comment by sorrycc** [comment]
删除 `.umirc.mock.js` 吧，这个文件不需要了。
