### ISSUE TITLE
[Bug] 本地dev运行没问题，也可以正常编译，然后放在linux centos上宝塔运行之后，有时候https访问会直接白屏。

### ISSUE THREAD

**Issue by xLikeWATCHDOG** [umijs/umi#10330]
本地dev运行没问题，也可以正常编译，然后放在linux centos上宝塔运行之后，有时候https访问会直接白屏。

复现：
1.访问https会白屏，后台报TypeError。https://appeal.kinomc.net//
![image](https://user-images.githubusercontent.com/73741466/213912681-924025c1-2f2a-4dc2-b79c-577cc0aa18e6.png)
2.正常访问http就没事了，http://appeal.kinomc.cn/
3.目前情况大概是，https大部分都访问不了。但是http大部分的都能访问，但是如果一旦出现一次白屏错误，强制刷新也无济于事。依然不行，但是无痕浏览是可以的。
![image](https://user-images.githubusercontent.com/73741466/213912761-ea6540e3-3112-4b15-ae48-aa96149f5f51.png)
![image](https://user-images.githubusercontent.com/73741466/213912772-59a16136-f074-4c13-ba17-fe679007f49f.png)

源代码：https://github.com/xLikeWATCHDOG/frontend-appeals

- **Umi Version**:4.0.46
- **Platform**:Linux Centos

**Comment by fz6m** [comment]
这个属于运维方面的问题。

先确定好你的 https 证书哪里来，简单的有 let's encrypt 、从域名提供商处申请、宝塔自助申请、CF 边缘证书等。

确定好证书之后进行 nginx 配置，可以在 bt 上可视化配置导入你的证书，或者手动把证书放到 Nginx 配置目录，再手动改 nginx 配置，同时保证你的站点是强制 https 的，所有的 http 请求自动跳 443 ，服务器要开 80 + 443 两个端口，确定没有被防火墙或服务器提供商安全组限制。

除此之外，SPA 还需要 nginx 重定向策略，自己研究下 try_files 配置，如果你确定了你是 https 站点，应该无法 http 访问的，所有 http 都会强制升级到 https ，不存在你说的这种开了 https ，还能访问 http 的情况。

**Comment by xLikeWATCHDOG** [comment]
如果依然访问不了，那就http://67.230.165.237/
我也不知道为什么，是我部署的问题吗？
本来部署好之后，直接访问appeal.kinomc.net/appeal，
会显示404，然后就弄了伪静态，就解决了。
我是按照https://blog.csdn.net/weixin_43408077/article/details/119617516 来部署的。
![image](https://user-images.githubusercontent.com/73741466/213913012-31c85b3f-f9cc-4f6c-8e37-a39e51cd34dc.png)
![image](https://user-images.githubusercontent.com/73741466/213913018-f2df80fd-ddf4-436e-8e82-f4494c0b03e9.png)
![image](https://user-images.githubusercontent.com/73741466/213913037-225fbb95-20f3-490b-a1f1-54d4f355104f.png)

**Comment by xLikeWATCHDOG** [comment]
> 这个属于运维方面的问题。
> 
> 先确定好你的 https 证书哪里来，简单的有 let's encrypt 、从域名提供商处申请、宝塔自助申请、CF 边缘证书等。
> 
> 确定好证书之后进行 nginx 配置，可以在 bt 上可视化配置导入你的证书，或者手动把证书放到 Nginx 配置目录，再手动改 nginx 配置，同时保证你的站点是强制 https 的，所有的 http 请求自动跳 443 ，服务器要开 80 + 443 两个端口，确定没有被防火墙或服务器提供商安全组限制。
> 
> 除此之外，SPA 还需要 nginx 重定向策略，自己研究下 try_files 配置，如果你确定了你是 https 站点，应该无法 http 访问的，所有 http 都会强制升级到 https ，不存在你说的这种开了 https ，还能访问 http 的情况。

行，我试试。

**Comment by xLikeWATCHDOG** [comment]
> 
谢谢大佬，目前已经差不多解决啦~
但是还有一些很神奇的现象，因为appeal.kinomc.net，那个域名，是cloudflare的。所以进去似乎是不用在宝塔部署证书，直接https的。然后就会出现这个问题。
然后我按照你的方法，把cn的那个域名（不是cf的），部署了证书，并且强制https了。就可以正常访问了！
不太明白为什么cf的那个不行。

**Comment by xLikeWATCHDOG** [comment]
> > 
> 
> 谢谢大佬，目前已经差不多解决啦~ 但是还有一些很神奇的现象，因为appeal.kinomc.net，那个域名，是cloudflare的。所以进去似乎是不用在宝塔部署证书，直接https的。然后就会出现这个问题。 然后我按照你的方法，把cn的那个域名（不是cf的），部署了证书，并且强制https了。就可以正常访问了！ 不太明白为什么cf的那个不行。

问题解决了，仓库我就关公开了，然后议题也关了。
