### ISSUE TITLE
[Bug] 组件里使用useModel 在lexical编辑器里调用会出现TypeError: Cannot read properties of null (reading 'dispatcher')

### ISSUE THREAD

**Issue by WuJiY** [umijs/umi#10334]
自定义了个上传组件，里面使用了 max 的 useModel ，然后在lexical里使用上传组件 会报错
<img width="702" alt="截屏2023-01-27 15 19 01" src="https://user-images.githubusercontent.com/183884/215030241-3ce6221a-0586-49fc-a4a6-dfb708f6b0c6.png">

**Comment by WuJiY** [comment]
这关闭的也太快了😂😂😂

**Comment by yijinc** [comment]
我也碰到这样的问题，在app.tsx 使用 报错，在其它组件使用正常

**Comment by yijinc** [comment]
> 

app.tsx 我使用 React.useXXX 是没有问题的。 useModel 便报错。

那如何在app.jsx 使用 全局状态呢？ 现在有个 configProvider 需要在最外层使用，数据不能用 useModal  难道只能使用其它数据流了嘛

**Comment by fz6m** [comment]
可以使用 [`valtio`](https://umijs.org/docs/max/valtio) ，支持在任意地方使用，或者把全局数据的操作和使用放到 layout 去处理。

**Comment by BurnhamZhang** [comment]
> 可以使用 [`valtio`](https://umijs.org/docs/max/valtio) ，支持在任意地方使用，或者把全局数据的操作和使用放到 layout 去处理。

layout 里面使用useModel也报相同的错误

**Comment by fz6m** [comment]
需要给一个最小复现。

**Comment by crazyair** [comment]
> 需要给一个最小复现。

我也遇到了，麻烦看下 https://github.com/crazyair/antd5/tree/umi-use-model

**Comment by crazyair** [comment]
@stormslowly 帮忙看下 https://github.com/crazyair/antd5/tree/umi-use-model，如何能在 App 使用 useModel，umi3 升级 umi4 不想改数据流方案

**Comment by fz6m** [comment]
如上面回答所述，不可以在 [`src/app.tsx`](https://github.com/crazyair/antd5/blob/5bf5cb13904a80ab30f25cf574b99067e3006615/src/app.tsx#L28) 内的 `rootContainer` 中使用 `useModel` ，因为 root 节点最外层没有数据流的 context 上下文。

上述回答中描述的 “可以在 layout 中使用” ，指的是 `src/layouts/index.tsx` 自定义自己的 layout 中可以使用。

除此之外，可以尝试在 `src/app.tsx` 中，在 `innerProvider` 层级包裹自定义 context 来使用 `useModel` ：

```ts
// src/app.tsx

export const innerProvider = (children) => {
  return <CustomContext>{children}</CustomContext>
}
```

`innerProvider` 的层级比数据流所在的 context 要低，所以可以取到数据流上下文，需要注意的是，此处的 `App` 不应该是 antd 的 `App` ，勿添加 antd 的 `App` 。

**Comment by linhuiw** [comment]
@fz6m 遇到了同样的问题，完全没有看懂上面这个回答的意思？
这个要怎么解决么？

**Comment by crazyair** [comment]
useModal 不放 app.tsx，放 router.ts 里的 wrappers 里，就没问题了

**Comment by shanyijin** [comment]
> 如上面回答所述，不可以在 [`src/app.tsx`](https://github.com/crazyair/antd5/blob/5bf5cb13904a80ab30f25cf574b99067e3006615/src/app.tsx#L28) 内的 `rootContainer` 中使用 `useModel` ，因为 root 节点最外层没有数据流的 context 上下文。
> 
> 上述回答中描述的 “可以在 layout 中使用” ，指的是 `src/layouts/index.tsx` 自定义自己的 layout 中可以使用。
> 
> 除此之外，可以尝试在 `src/app.tsx` 中，在 `innerProvider` 层级包裹自定义 context 来使用 `useModel` ：
> 
> ```ts
> // src/app.tsx
> 
> export const innerProvider = (children) => {
>   return <CustomContext>{children}</CustomContext>
> }
> ```
> 
> `innerProvider` 的层级比数据流所在的 context 要低，所以可以取到数据流上下文，需要注意的是，此处的 `App` 不应该是 antd 的 `App` ，勿添加 antd 的 `App` 。

请问 innerProvider 怎么不维护到文档里呢

**Comment by fz6m** [comment]
可以，关于这个特殊场景欢迎提 PR 添加到文档里。
