### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by Ancisuce** [umijs/umi#10336]
## What happens?

umi4 + antd5 设置暗黑主题后，收起侧边栏。多子菜单情况下，侧边菜单栏弹框背景色未跟随主题变动，字体颜色正常。
![image](https://user-images.githubusercontent.com/16064629/215243131-71ab0d7c-1817-4474-826c-88399625511f.png)
![image](https://user-images.githubusercontent.com/16064629/215243196-41c89d88-ea7f-41ea-8b1b-f955792ca4c9.png)

## Mini Showcase Repository(REQUIRED)

官方案例就是
## How To Reproduce

执行yarn create umi，选择antd，在app.ts中设置为暗黑主题
![image](https://user-images.githubusercontent.com/16064629/215243231-3fc8b6fe-3884-453d-b86b-882c3f921fe8.png)

## Context

- **Umi Version**: ^4.0.47
- **Node Version**: 16
- **Platform**:  windows/pnpm

**Comment by fz6m** [comment]
试一下升级 `@ant-design/pro-components` 到最新版本。如果还不行，可以到这里 https://github.com/ant-design/pro-components 反馈问问。
