### ISSUE TITLE
[Bug] UMI3 升级到UMI4打包报错

### ISSUE THREAD

**Issue by HuangRan** [umijs/umi#10342]
## What happens?
UMI3 升级到UMI4打包报错:
umi.js:9616:306366: ERROR: Transforming async generator functions to the configured target environment ("chrome80", "es2015") is not supported yet
umi.js:379454:1: ERROR: Transforming async generator functions to the configured target environment ("chrome80", "es2015") is not supported yet

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**  UMI MAX:
- **Node Version** NODE 16:
- **Platform**  WINDOWS:

**Comment by fz6m** [comment]
Umi 4 默认用 esbuild 压缩，不兼容非现代浏览器，你指定的 targets 太旧了，解法见：[非现代浏览器兼容](https://umijs.org/blog/legacy-browser) 。
