### ISSUE TITLE
[Bug]  Umiv4安装@umijs/plugins后再装antd5报一堆 Can't resolve 'rc-xxxx' 错误

### ISSUE THREAD

**Issue by codeHung** [umijs/umi#10341]
## What happens?

Umi v4.0.47 安装@umijs/plugins@4.0.47 后再装antd5.16报错

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

Umi v4.0.47 安装@umijs/plugins@4.0.47 后再装antd5.16，然后npm run dev 报出很多Module not found: Error: Can't resolve 'rc-* 错误。
https://github.com/umijs/umi
[antd](https://ant.design/docs/react/practical-projects-cn)
## How To Reproduce

我是参考antd V5官方的教程安装的，教程链接和截图如下

复现链接 
[antd](https://ant.design/docs/react/practical-projects-cn)

### 报错截图：

```
error - ./node_modules/antd/es/_util/placements.js:1:0-54
Module not found: Error: Can't resolve 'rc-tooltip/es/placements' in 'D:\project\zytcli-umi4-template\node_modules\antd\es\_util'
error - Error: ERROR in ./node_modules/antd/es/_util/placements.js 1:0-54
Module not found: Error: Can't resolve 'rc-tooltip/es/placements' in 'D:\project\zytcli-umi4-template\node_modules\antd\es\_util'
 @ ./node_modules/antd/es/tooltip/index.js 15:0-48 117:32-45
 @ ./node_modules/antd/es/index.js 60:0-47 60:0-47
 @ ./node_modules/.cache/mfsu/mf-va_antd.js 1:0-78 1:0-78
 @ container entry ./antd[0]

ERROR in ./node_modules/antd/es/_util/wave/WaveEffect.js 2:0-34
Module not found: Error: Can't resolve 'rc-motion' in 'D:\project\zytcli-umi4-template\node_modules\antd\es\_util\wave'
 @ ./node_modules/antd/es/_util/wave/useWave.js 1:0-42 5:4-18
 @ ./node_modules/antd/es/_util/wave/index.js 8:0-32 22:19-26
 @ ./node_modules/antd/es/switch/index.js 17:0-33 50:51-55
 @ ./node_modules/antd/es/index.js 53:0-45 53:0-45
 @ ./node_modules/.cache/mfsu/mf-va_antd.js 1:0-78 1:0-78
 @ container entry ./antd[0]

ERROR in ./node_modules/antd/es/alert/index.js 15:0-34
Module not found: Error: Can't resolve 'rc-motion' in 'D:\project\zytcli-umi4-template\node_modules\antd\es\alert'
 @ ./node_modules/antd/es/index.js 2:0-43 2:0-43
 @ ./node_modules/.cache/mfsu/mf-va_antd.js 1:0-78 1:0-78
 @ container entry ./antd[0]
```

## Context

- **Umi Version**: 4.0.47
- **Node Version**: 4.0.47
- **Platform**: win 10

**Comment by codeHung** [comment]
### umirc 配置如下

**Comment by codeHung** [comment]
删掉node_modules重新安装一遍后，就正常了

**Comment by xiaohuoni** [comment]
要注意相关包的版本是否对应。另外这个文档 mock 部分有一处错误，如果你也注意到，可以看看这里 https://github.com/ant-design/ant-design/pull/40436

**Comment by fz6m** [comment]
1. 使用 npm v9 最新版本尝试一下。

2. 早期的 npm 存在依赖提升覆盖随机的问题，`@umijs/plugins` 也含有 antd ，所以你手动安装的 antd 不一定被提升上来，推荐使用 pnpm 安装依赖。
