### ISSUE TITLE
[Bug] 升级文档有问题

### ISSUE THREAD

**Issue by SakuraYou** [umijs/umi#10349]
## What happens?

v3 升级 v4 的官方文档中，依赖处理这一节

"devDependencies": {
+   "@umijs/max": "^4.0.0",
-   "umi": "^3.0.0",
-   "@umijs/preset-react": "^1.2.2"
  }

devDependencies 中不存在 "umi": "^3.0.0", 该依赖在 v3 版本通过快速上手，会安装在 dependencies: { "umi": "^3.5.36" }。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
是一个意思，就是需要升级 umi 依赖版本。
