### ISSUE TITLE
[Bug] build之后/index结尾的路由被替换成/

### ISSUE THREAD

**Issue by zqh-china** [umijs/umi#10362]
## What happens?

umi项目，在`yarn dev/start`时能够正确匹配到`.umirc.js`或`config/config.js`里面配置的`routes`（配置式路由），但是`yarn build`后，`/index`路由失效，被替换成了`/`

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

● 创建一个项目文件夹，在其中执行`yarn create @umijs/umi-app`
● 执行`yarn`安装依赖
● 在`src/pages/`下新建`/user/login.jsx`，在`.umirc.js`中新增一条路由 `{ path: '/user/login', component: '@/pages/user/login' }`（作为对照组）
● 执行`yarn build`，并切换到生成的`dist/`下执行`serve -s`
● 访问`/user/login`可以正常显示，访问`/index`异常，并且浏览器地址处被替换成了`/`
经测试只要是`/index`结尾的路由，在打包后末尾的`/index`都会被替换成`/`，但是`yarn dev/start`时无此问题
```js
// .umirc.js
import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  routes: [
    { path: '/index', component: '@/pages/index' },
    { path: '/user/login', component: '@/pages/user/login/login' },
    // { path: '/', redirect: '/user/login' },
  ],
  fastRefresh: {},
});
```

## Context

- **Umi Version**: 3.5.0
- **Node Version**: 16.13.0
- **Platform**: windows10家庭中文版 22H2

**Comment by xiaohuoni** [comment]
关联 https://github.com/umijs/umi/pull/10333 ？
