### ISSUE TITLE
[Bug] mfsu loading failed

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#10368]
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/35128/215927491-702be02b-ccd1-4384-8403-80c994846c5c.png">

复现步骤，

1、https://github.com/umijs/umi/tree/master/examples/max
2、npm run dev
3、访问 /app1

报错如上图。

**Comment by stormslowly** [comment]
/app1  是用来测试本地8001 端口微应用的，如果本应用也刚才起在 8001，会重复加载 mfsu 的 remote 导致以上错误。
换一个端口启动，就可以避免此问题
