### ISSUE TITLE
[Bug] 开启乾坤后报错

### ISSUE THREAD

**Issue by HuangRan** [umijs/umi#10363]
## What happens?

主应用使用umimax SPA  ，子应用使用umimax MPA的形式，主应用加载子应用时报错。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your 
main:https://github.com/HuangRan/max-main.git
child:https://github.com/HuangRan/umi-child.git

## How To Reproduce

主应用配置：
![image](https://user-images.githubusercontent.com/8411877/215720957-62cc2911-e61d-4426-b858-2651801f195c.png)
![image](https://user-images.githubusercontent.com/8411877/215720980-f2d27209-2cc7-4e03-8514-7eb9654c6926.png)
子应用配置：
![image](https://user-images.githubusercontent.com/8411877/215721045-b2952286-d26d-4d32-940b-f9a525165494.png)

## Context

- **Umi Version**:max
- **Node Version**:16.17.0
- **Platform**:Windows

**Comment by HuangRan** [comment]
> ## What happens?
> 主应用使用umimax SPA ，子应用使用umimax MPA的形式，主应用加载子应用时报错。
> 
> ## Mini Showcase Repository(REQUIRED)
> > Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your
> > main:https://github.com/HuangRan/max-main.git
> > child:https://github.com/HuangRan/umi-child.git
> 
> ## How To Reproduce
> 主应用配置： ![image](https://user-images.githubusercontent.com/8411877/215720957-62cc2911-e61d-4426-b858-2651801f195c.png) ![image](https://user-images.githubusercontent.com/8411877/215720980-f2d27209-2cc7-4e03-8514-7eb9654c6926.png) 子应用配置： ![image](https://user-images.githubusercontent.com/8411877/215721045-b2952286-d26d-4d32-940b-f9a525165494.png)
> 
> ## Context
> * **Umi Version**:max
> * **Node Version**:16.17.0
> * **Platform**:Windows

报错信息如下：
![image](https://user-images.githubusercontent.com/8411877/215721428-c33e0595-600c-48d8-89a5-b08e712b5344.png)

**Comment by fz6m** [comment]
MPA 不支持 qiankun ，目前应用场景仅限部分 H5 页面和静态站点生成器。需要用 qiankun 的话代表是一个重型应用，无需使用 MPA 。
