### ISSUE TITLE
umi 4 crossorigin 在配置 publicPath之后失效

### ISSUE THREAD

**Issue by codingdogs** [umijs/umi#10379]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by codingdogs** [comment]
Umi Version:4.0.47
Node Version:16.13.0
Platform: mac

**Comment by codingdogs** [comment]
```
export default {
  npmClient: 'pnpm',
  crossorigin:true,
  hash: true,
  // publicPath:"http://xx.com/"
};

```

**Comment by fz6m** [comment]
`publicPath` 在开发的时候没必要设定，同时 `crossorigin` 是给本地 local 脚本使用的，不会作用带网址 url 的脚本 `<script />` 标签上。

但是有一种方法可以给你想要的匹配值加上 `crossorigin` ：

```ts
// .umirc.ts

export default {
  crossorigin: {
    includes: [
      /domain\.com/
    ]
  },
  publicPath: 'https://domain.com/',
}
```
