### ISSUE TITLE
[Bug] 如何在路由配置中动态的添加某些接口数据

### ISSUE THREAD

**Issue by Longder** [umijs/umi#10372]
实际需求中需要在左边菜单增加一个比如跳外链http的菜单按钮，
`
  {
    path: 'https://xxxxxxxx',
    name: 'visual',
    icon: 'link',
    access: 'visualFilter',
  },
`
实际中也能够跳转。
如果path的内容需要动态，比如需要从当前的windows的location里面内容拼接，请问大佬如何实现？因为尝试直接写window是不行的，预估使用request获取也不行。
曾考虑过通过其他方式，比如配置app.tsx中的RuntimLayout配置中在菜单下面追加，也有一个links的配置是支持，但是是加在了整个菜单的左下角。
请问如何实现向所有菜单最下面动态追加一个跳外链的菜单项呢？

**Comment by fz6m** [comment]
umi 有运行时修改路由表的方法，[patchClientRoutes](https://umijs.org/docs/api/runtime-config#patchclientroutes-routes-) 。

`src/app.tsx` 通过 `export layout` 应该可以定制 [ProLayout](https://procomponents.ant.design/components/layout) 。

研究下 ProLayout 吧，看看能不能定制外链的菜单。

**Comment by fz6m** [comment]
如果要改某个路由的组件，需要改对应的 `element` ，并用 `<Suspense />` 包起来，可参考 https://github.com/umijs/umi/discussions/9717#discussioncomment-4078053

如有问题，需要给一个最小复现。

**Comment by fz6m** [comment]
这里的 patch client routes 意思是：在应用运行时修改路由，而不是在一开始就写死。但打包器不知道要打包哪些路由，所以所有已知路由需要有映射表，根据唯一标识 patch 增添、修改
