### ISSUE TITLE
[Bug] umi4 mf 模块联邦，共享模块使用 umi 插件 request 时报错，不能读取 applyPlugins

### ISSUE THREAD

**Issue by zhengshuai1001** [umijs/umi#10373]
## What happens?

umi4 mf ，模块联邦，对外共享某一个页面，该页面使用 umi 的插件 request 发请求。结果 umi 代码报错。

该页面当常规页面使用时，umi 的 request 可以正常使用。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

**umi4 examples ，mf-host 和 mf-remote 官网示例代码，新增 request 代码就能复现。**

https://github.com/zhengshuai1001/mf_demo

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

remote 配置

![image](https://user-images.githubusercontent.com/9513530/215987250-f864e99a-bdbe-408c-b797-d3d12e5d7ebd.png)

remote 代码

![image](https://user-images.githubusercontent.com/9513530/215990039-3c157eb7-b768-4521-a9bc-1935fa6045ef.png)

remote 页面

![image](https://user-images.githubusercontent.com/9513530/215987425-4af49050-36af-4a0f-a3ba-05948c228c07.png)

host 配置

![image](https://user-images.githubusercontent.com/9513530/215987630-a7df196b-3315-4e84-bddc-5574e24d5d29.png)

host 代码

![image](https://user-images.githubusercontent.com/9513530/215987734-52066678-af6c-465d-aa8e-99bc88268d63.png)

host 页面

![image](https://user-images.githubusercontent.com/9513530/215987832-b99956fe-5f02-4885-8258-460490dc83dd.png)

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0.42
- **Node Version**: v16.15.1
- **Platform**: macOS,Edg/109

**Comment by stormslowly** [comment]
预期内，目前的解法，需要导出的联邦模块不要使用 umi/request  采用其他的方式请求。
