### ISSUE TITLE
[Bug] umi4 开启qiankun 子应用如果是umi4开发的,子应用页面一开始正常后面会卡住,不能滚动.

### ISSUE THREAD

**Issue by woshiku110** [umijs/umi#10384]
我使用umi4作为qiankun主应用,其中有一个子应用是umi4开发,发现umi4开发的子应用正常使用,但有时候滚动突然没了,页面卡住,页面可见区域正常使用,却无法滚动页面,想问下这是什么原因?

**Comment by fz6m** [comment]
是在开发时，还是 build 完在线上有此问题？

可以提供一个最小复现看看。
