### ISSUE TITLE
[Bug]umi/max编译core文件夹下生成的history.ts文件，basename为什么解析不到？

### ISSUE THREAD

**Issue by IamMeMF** [umijs/umi#10385]
详细复线步骤：
1.config文件中配置了base：‘/manage/’
2.执行umi max命令
3.生成的.umi文件夹下的history.ts文件 ，有个变量basename：string = ‘/’，按umi3的规则，basename的值应该是’/manage/‘
4.所以导致编译完成后在浏览器打开localhost:8000/时，浏览器打开的地址变成了localhost:8000/manage/manage/***
![step01](https://user-images.githubusercontent.com/80817603/216329008-c2388b59-9d0f-4094-824a-ca6c38b621a6.png)
![step02](https://user-images.githubusercontent.com/80817603/216329007-0f6e427a-8545-4656-8a68-73e42fe0879c.png)

![step03](https://user-images.githubusercontent.com/80817603/216329020-373c68c7-9a30-4496-b9da-d356f952b36b.png)

**Comment by fz6m** [comment]
这个地方初始值是 `/`，后面在运行时改成了你配置里的 basename ，有问题的话，给一个最小复现看看。

**Comment by IamMeMF** [comment]
我的配置里面是base：’/manage/‘，运行时 ’/‘ 没有变成’/manage/‘
