### ISSUE TITLE
[Bug] umi4 layout 重复输出 html 结构

### ISSUE THREAD

**Issue by yoguang** [umijs/umi#10392]
## What happens?
自定义layout HTML 结构中出现两次 自定义的头部标签
![image](https://user-images.githubusercontent.com/24262038/216524629-3065eda9-b54b-44c3-8e21-1cc9afbf401f.png)

layout
```jsx
import { Layout } from 'antd';
import { Outlet } from '@umijs/max';

const { Content, Sider, Header } = Layout;
export default function Page() {
  return (
    <div style={{ padding: 20 }}>
      <Header style={{ background: 'rgba(0,0,0,0.19)' }}>Header</Header>
      <Sider style={{ background: 'rgba(0,0,0,0.19)' }}>Sider</Sider>
      <Content>
        <Outlet />
      </Content>
    </div>
  );
}
```

.umirc.ts
```js
import { defineConfig } from '@umijs/max';

export default defineConfig({
  antd: {},
  access: {},
  model: {},
  initialState: {},
  request: {},
  layout: false,
  routes: [
    {
      path: '/',
      redirect: '/home',
    },
    {
      path: '/table',
      component: 'Table',
    },
    {
      path: '/',
      component: '@/layouts/index',
      routes: [
        { path: 'home', component: '@/pages/Home' },
        { path: 'access', component: '@/pages/Access' },
      ],
    },
  ],
  npmClient: 'pnpm',
});

```

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/yoguang/umi4-layout-repeat-html

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0.47
- **Node Version**: v14.16.0
- **Platform**: macOS

**Comment by cike8899** [comment]
我也遇到了一样的问题，layout文件中的header会重复显示，只好在layouts层面加个`layout: false`

![image](https://github.com/umijs/umi/assets/8089971/a9022668-2fab-4b72-ba3d-c11cb18cca4a)
