### ISSUE TITLE
[Bug] @umijs/max 执行`postintall`报没有loader，No loader is configured for ".sss" files: public/theme/dark.sss

### ISSUE THREAD

**Issue by MatrixAge** [umijs/umi#10393]
## What happens?

![image](https://user-images.githubusercontent.com/25472851/216528023-6c57c00e-6203-4f45-9070-db295b28a715.png)

postinstall还检查业务代码吗？这个问题在之前的版本从来没出现过，一直在关注umi和更新最新版本，但是没有重新pnpm install过，直到今天ci报警了，显示报这个错。线下在自己电脑上删除了node_modules就复现了。

很疑惑，难道是业务代码不能随便引用public下的静态文件，是这个原因导致setup失败的？

看打印记录，setup是不会执行打包相关流程的：

![image](https://user-images.githubusercontent.com/25472851/216528848-84c7a5bd-4432-4edd-9ebb-b110558d1cf4.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/YaoApp/xgen/tree/main/packages/xgen

## How To Reproduce

见上文描述。

## Context

- **Umi Version**: @umijs/max@^4.0.48
- **Node Version**: 18.4.0
- **Platform**: macos

**Comment by MatrixAge** [comment]
暂时先用dirty的手段处理了，让项目先跑通：

![image](https://user-images.githubusercontent.com/25472851/216538657-7314fb62-e5a0-447f-8289-2e976ba5ec1f.png)
![image](https://user-images.githubusercontent.com/25472851/216538734-7e687a3d-c25c-47f1-b6d6-a305c730ab5c.png)

**Comment by qxz123456** [comment]
![image](https://user-images.githubusercontent.com/120540501/216539139-a2a66afa-35d0-4b19-a371-40dd1c05adf6.png)
我这也遇到相同的问题了，package.json里配置的umijs/max版本号前面带^，导致install时有最新版本 会更新到最新版本，结果就裂开了，我把版本回退到4.0.42就好了

**Comment by MatrixAge** [comment]
> 

主要是用了swc的一些自定义配置，没法回退到4.0.42版本了，不过这个问题应该还是比较普遍的，等修复吧，不能因噎废食。

**Comment by MatrixAge** [comment]
https://github.com/umijs/umi/commit/eee430bdf59af9785597f7c44371247cc6335d35

这个commit没有解决问题，要不把`externalsExtensions `作为配置暴露出来好了，外部的配置和内部的配置进行合并，这样就能满足各种各样assert的场景了。

**Comment by MatrixAge** [comment]
> ![image](https://user-images.githubusercontent.com/120540501/216539139-a2a66afa-35d0-4b19-a371-40dd1c05adf6.png) 我这也遇到相同的问题了，package.json里配置的umijs/max版本号前面带^，导致install时有最新版本 会更新到最新版本，结果就裂开了，我把版本回退到4.0.42就好了

折腾了半天，它dev和build的时候竟然还要执行prepare，这下子只能回退到4.0.42了。
