### ISSUE TITLE
打包指定文件到其他目录

### ISSUE THREAD

**Issue by zhuanglong** [umijs/umi#1039]
怎样才能把 umi.js 打包到 static 目录
![baidushurufa_2018-9-9_15-11-58](https://user-images.githubusercontent.com/19422011/45262169-2ec15c80-b444-11e8-8171-09cf6818dec8.png)

**Comment by concefly** [comment]
https://umijs.org/zh/config/#outputpath

**Comment by xiaohuoni** [comment]
outputPath 只是指定输出目录，不是她说的将这些文件放到static。现在不支持这个功能
