### ISSUE TITLE
重新安装依赖的时候An unexpected error occurred: "https://registry.npmmirror.com/@umijs/utils/-/utils-4.0.49.tgz: Request failed \"404 Not Found\"".

### ISSUE THREAD

**Issue by WilliamTian0987** [umijs/umi#10402]
Arguments: 
  /usr/local/bin/node /Users/mine/.yarn/bin/yarn.js

PATH: 
  /Users/mine/Documents/projs/ABCMeal/venv/bin:/Users/mine/.yarn/bin:/Users/mine/.config/yarn/global/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$GOPATH/bin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/mine/.yarn/bin:/Users/mine/.config/yarn/global/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/bin:/Users/mine/.cargo/bin

Yarn version: 
  1.22.5

Node version: 
  18.7.0

Platform: 
  darwin arm64

Trace: 
  Error: https://registry.npmmirror.com/@umijs/utils/-/utils-4.0.49.tgz: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (/Users/mine/.yarn/lib/cli.js:696:66)
      at new ResponseError (/Users/mine/.yarn/lib/cli.js:802:124)
      at Request.<anonymous> (/Users/mine/.yarn/lib/cli.js:67058:16)
      at Request.emit (node:events:513:28)
      at module.exports.Request.onRequestResponse (/Users/mine/.yarn/lib/cli.js:141626:10)
      at ClientRequest.emit (node:events:513:28)
      at HTTPParser.parserOnIncomingClient (node:_http_client:674:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
      at TLSSocket.socketOnData (node:_http_client:521:22)
      at TLSSocket.emit (node:events:513:28)

npm manifest: 
  {
    "name": "ant-design-pro",
    "version": "6.0.0-beta.1",
    "private": true,
    "description": "An out-of-box UI solution for enterprise applications",
    "scripts": {
      "analyze": "cross-env ANALYZE=1 max build",
      "build": "max build",
      "deploy": "npm run build && npm run gh-pages",
      "dev": "npm run start:dev",
      "gh-pages": "gh-pages -d dist",
      "i18n-remove": "pro i18n-remove --locale=zh-CN --write",
      "postinstall": "max setup",
      "lint": "npm run lint:js && npm run lint:prettier && npm run tsc",
      "lint-staged": "lint-staged",
      "lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
      "lint:fix": "eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src ",
      "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
      "lint:prettier": "prettier -c --write \"src/**/*\" --end-of-line auto",
      "openapi": "max openapi",
      "playwright": "playwright install && playwright test",
      "prepare": "husky install",
      "prettier": "prettier -c --write \"src/**/*\"",
      "serve": "umi-serve",
      "start": "cross-env UMI_ENV=dev max dev",
      "start:dev": "cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev max dev",
      "start:no-mock": "cross-env MOCK=none UMI_ENV=dev max dev",
      "start:pre": "cross-env REACT_APP_ENV=pre UMI_ENV=dev max dev",
      "start:test": "cross-env REACT_APP_ENV=test MOCK=none UMI_ENV=dev max dev",
      "test:e2e": "node ./tests/run-tests.js",
      "tsc": "tsc --noEmit"
    },
    "lint-staged": {
      "**/*.{js,jsx,ts,tsx}": "npm run lint-staged:js",
      "**/*.{js,jsx,tsx,ts,less,md,json}": [
        "prettier --write"
      ]
    },
    "browserslist": [
      "> 1%",
      "last 2 versions",
      "not ie <= 10"
    ],
    "dependencies": {
      "@ant-design/icons": "^4.7.0",
      "@ant-design/pro-components": "^2.3.13",
      "@umijs/route-utils": "^2.1.3",
      "antd": "^4.23.3",
      "braft-editor": "^2.3.9",
      "classnames": "^2.3.2",
      "lodash": "^4.17.21",
      "moment": "^2.29.4",
      "omit.js": "^2.0.2",
      "rc-menu": "^9.6.4",
      "rc-util": "^5.24.4",
      "react": "^17.0.0",
      "react-captcha-code": "^1.0.7",
      "react-dev-inspector": "^1.8.1",
      "react-dom": "^17.0.0",
      "react-helmet-async": "^1.3.0"
    },
    "devDependencies": {
      "@ant-design/pro-cli": "^2.1.0",
      "@playwright/test": "^1.26.1",
      "@types/classnames": "^2.3.1",
      "@types/express": "^4.17.14",
      "@types/history": "^4.7.11",
      "@types/lodash": "^4.14.186",
      "@types/react": "^17.0.0",
      "@types/react-dom": "^17.0.0",
      "@types/react-helmet": "^6.1.5",
      "@umijs/fabric": "^2.11.1",
      "@umijs/max": "^4.0.24",
      "@umijs/openapi": "^1.7.0",
      "cross-env": "^7.0.3",
      "cross-port-killer": "^1.4.0",
      "detect-installer": "^1.0.2",
      "eslint": "^7.32.0",
      "gh-pages": "^3.2.0",
      "husky": "^7.0.4",
      "lint-staged": "^10.0.0",
      "mockjs": "^1.1.0",
      "prettier": "^2.7.1",
      "swagger-ui-dist": "^4.14.2",
      "typescript": "^4.8.4",
      "umi-presets-pro": "^1.0.5",
      "umi-serve": "^1.9.11"
    },
    "engines": {
      "node": ">=12.0.0"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by fz6m** [comment]
cnpm 很慢，还没从 npm 上游更新，可以手动去点一下 sync ，或者 `cnpm sync some-package`

**Comment by WilliamTian0987** [comment]
> 

这个方法倒是没试过,然后换了官方指定的pnpm,然后重新拉去一套就可以了
![14ACDFE4](https://user-images.githubusercontent.com/48847346/216604863-f2a45cd6-7d53-4ebc-b46c-d2b72ad712d7.png)
