### ISSUE TITLE
使用umi执行umi g page index发生Error: Cannot find module 'resolve-cwd'异常

### ISSUE THREAD

**Issue by free-pan** [umijs/umi#1042]
试过的umi版本:
2.0.3
2.0.2

我知道这是说缺少模块resolve-cwd模块, 但我要怎么安装呢?

我试过:`npm i -g resolve-cwd`也试过在项目文件件中执行`npm i resolve-cwd`但最终执行`umi g page index`时都会出现Error: Cannot find module 'resolve-cwd'异常

另外:
我按照umi的官网方式使用tyarn安装umi时,老是提示这个异常:
`error An unexpected error occurred: "http://localhost:8081/repository/taobao-npm-repo/archiver/-/archiver-2.1.1.tgz: connect ECONNREFUSED 127.0.0.1:8081".`

我知道这是我之前使用neus搭建的镜像代理, 但我已经使用如下方式清除了代理设置
`npm config set registry null`
`yarn config set registry null`

最后我甚至已经将node, npm以及node_modules整个删除, 但yarn重装之后依然是`error An unexpected error occurred: "http://localhost:8081/...`(npm和cnpm是正常的)

有查看过`~/.yarnrc`和`~/.npmrc`都是默认值

请问我这到底是什么地方出现了问题?

**Comment by free-pan** [comment]
第一个问题我自己解决了, 将~/node_modules下的所有文件都删除了,然后重新安装了一次umi, 就没有这个问题了,

但是yarn的问题依旧

**Comment by sorrycc** [comment]
看起来不是 umi 的问题了，yarn 可以去 yarn 官网找解决方案。
