### ISSUE TITLE
[Bug] umi4 mf 模块联邦，共享模块使用 umi 插件 qiankun 时报错

### ISSUE THREAD

**Issue by zhengshuai1001** [umijs/umi#10443]
## What happens?

umi4 mf ，模块联邦，对外共享某一个页面，该页面使用 umi 的插件 qiankun 微前端时， umi 代码报错。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

**umi4 examples ，mf-host 和 mf-remote 官网示例代码，新增开启 qiankun 代码就能复现。**

https://github.com/zhengshuai1001/mf_demo

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

remote 配置

![image](https://user-images.githubusercontent.com/9513530/217171605-3a8bc0fa-b956-43a9-88f4-564793d220ae.png)

remote 页面

![image](https://user-images.githubusercontent.com/9513530/217171698-9f0b63c0-f823-4e9e-89f7-2da2cf217750.png)

host 配置

![image](https://user-images.githubusercontent.com/9513530/217171814-277c31ea-c4c0-476d-b1fd-0f5432f45d40.png)

host 页面，报错

![image](https://user-images.githubusercontent.com/9513530/217171930-e6f8f6d7-91b1-45f3-b180-08a31d96a662.png)

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
关闭 `mfsu: false` 即可。

寄汤来了，德艺双馨 P 老师快来看看这个问题， @stormslowly  🌹

**Comment by xiaoxiong77** [comment]
> 关闭 `mfsu: false` 即可。
> 
> 寄汤来了，德艺双馨 P 老师快来看看这个问题， @stormslowly 🌹

想问一下，现在有解决方案吗，还是必须要关闭mfsu吗？

**Comment by fz6m** [comment]
目前最新版本 mf 可以和 qiankun 一起使用了，先关闭了。

如有问题，请附带一个最小复现重开一个 issue。

**Comment by fbixiaoyu** [comment]
> 目前最新版本 mf 可以和 qiankun 一起使用了，先关闭了。
> 
> 如有问题，请附带一个最小复现重开一个 issue。

主应用umi4max，子应用webpack4 vue2；本地运行，主应用默认开启mf会报错Unhandled Rejection (Error): Container initialization failed as it has already been initialized with a different share scope，关闭mf会不停发起请求刷新主应用页面
![image](https://github.com/umijs/umi/assets/40888647/e921c484-1b91-4bd9-8a7b-ffeabcb8041b)

while loading

**Comment by fz6m** [comment]
这个问题是 mfsu 导致的吗，试试关闭 mfsu 呢？

**Comment by fbixiaoyu** [comment]
> 这个问题是 mfsu 导致的吗，试试关闭 mfsu 呢？

关闭mfsu,不停发起请求刷新页面

打开msfu，主应用报错Unhandled Rejection (Error): Container initialization failed as it has already been initialized with a different share scope，定位到代码是多次init，导致oldscope和 sharescore不是一个作用域，就抛错了。

**Comment by fz6m** [comment]
没能复现你说的问题，详见 https://github.com/umijs/umi/issues/11797#issuecomment-2214558211
