### ISSUE TITLE
Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead.

### ISSUE THREAD

**Issue by wzxm** [umijs/umi#1044]
Parsing error: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead.

使用修饰器无法在 class 中间使用 export 关键字？我看了 ES6 的文档，是可以这么写的呀。

![image](https://user-images.githubusercontent.com/13127730/45286699-1a9b5f00-b519-11e8-92c6-933753e57369.png)

**Comment by sorrycc** [comment]
请给重现步骤。

**Comment by wzxm** [comment]
![image](https://user-images.githubusercontent.com/13127730/45287414-cbeec480-b51a-11e8-9b33-df4df5d4288f.png)
正常编写代码就会出现，不确定是否跟 .eslintrc 有关。

**Comment by Mr-jiangzhiguo** [comment]
你应该是跟新了vscode的eslint插件了,
eslint的相关依赖是需要特定的版本的,
依赖版本不对应也会出现问题,
你可以尝试添加配置
`.eslintrc`:
```
      "parserOptions": {
        "ecmaFeatures": {
          "legacyDecorators": true
        }
      }
```

**Comment by sorrycc** [comment]
这是 eslint 抛的错，和 umi 没啥关系。

**Comment by OPY-bbt** [comment]
添加了eslint配置在vscode里不会报错，但是编译不过。
￼￼￼
![image](https://user-images.githubusercontent.com/16717283/55449721-3b371d80-55ff-11e9-9c75-e3aac469afd8.png)
