### ISSUE TITLE
[Bug] app.ts中antd配置MenuItem的样式token未生效

### ISSUE THREAD

**Issue by lppoi** [umijs/umi#10459]
## What happens?

1.colorTextMenuSelected不生效。
![image](https://user-images.githubusercontent.com/64509267/217730498-b92a2136-afa1-4f2b-a1da-2069f16e111a.png)

2.在config.ts中修改theme:{components:{}}内修改Menu的token依然无效，别的组件修改token正常。

3.如何对默认LayoutContent的样式进行修改，默认有padding 想改为0，除了使用main{padding-inline:0 !import}还有其他方法吗？

- **Umi Version**:4.0.50
- **Node Version**:16.10.0
- **Platform**:Windows10

**Comment by fz6m** [comment]
layout 有自己的主题修改方法，和 antd 原配置无关，详见 https://procomponents.ant.design/components/layout
