### ISSUE TITLE
umi 的 MicroApp 能否像qiankun的loadMicroApp 方法一样动态加载微应用

### ISSUE THREAD

**Issue by cx91** [umijs/umi#10456]
umi4中的 MicroApp 方法能否像 qiankun 的loadMicroApp 方法一样动态加载微应用(不用提前注册微应用)

**Comment by cx91** [comment]
umi4 中 MicroApp 组件引入方式只需要name属性，能否像qiankun中 loadMicroApp 方法一样传入entry等属性 动态加载呢。
umi4 MicroApp:
`
import { MicroApp } from 'umi';
 
export default () => {
  return <MicroApp name="app1" />;
};
`
qiankun loadMicroApp:
`
import { loadMicroApp } from 'qiankun';
import React from 'react';

class App extends React.Component {
  containerRef = React.createRef();
  microApp = null;

  componentDidMount() {
    this.microApp = loadMicroApp({
      name: 'app1',
      entry: '//localhost:1234',
      container: this.containerRef.current,
      props: { brand: 'qiankun' },
    });
  }
  render() {
    return <div ref={this.containerRef}></div>;
  }
}
`

**Comment by fz6m** [comment]
看一下这个 example ，不用 `MicroApp` ，用 `loadMicroApp` 也可以的：

https://github.com/umijs/umi/blob/38af70f897d021feb89e1e4c0c8c10f4805fc552/examples/qiankun-master/pages/manual-slave.tsx#L1-L25

**Comment by cx91** [comment]
> 看一下这个 example ，不用 `MicroApp` ，用 `loadMicroApp` 也可以的：
> 
> https://github.com/umijs/umi/blob/38af70f897d021feb89e1e4c0c8c10f4805fc552/examples/qiankun-master/pages/manual-slave.tsx#L1-L25

我知道，但我想的是 用umi4 提供的MicroApp组件加载未注册的子应用，不用再自己去写loading状态那些了

**Comment by fz6m** [comment]
可以在 qiankun 运行时逻辑里注册应用，详见：https://umijs.org/docs/max/micro-frontend#%E5%9F%BA%E4%BA%8E%E9%85%8D%E7%BD%AE%E7%9A%84%E9%80%9A%E4%BF%A1

**Comment by xc1427** [comment]
> 看一下这个 example ，不用 `MicroApp` ，用 `loadMicroApp` 也可以的：
> 
> https://github.com/umijs/umi/blob/38af70f897d021feb89e1e4c0c8c10f4805fc552/examples/qiankun-master/pages/manual-slave.tsx#L1-L25

会有问题。如果默认是不开 externalQiankun 的，如果项目自己装了qiankun，可能导致存在两个版本的 qiankun。一个是 umi 运行时插件使用的，一个是项目自己装的。

是不是最好让内置的 qiankun 也导出一个 loadMicroApp 方法供外部使用会比较鲁邦 ？
