### ISSUE TITLE
websocket proxy not support

### ISSUE THREAD

**Issue by AlexanderChen1989** [umijs/umi#1045]

**Comment by xiaohuoni** [comment]
Check your configuration. ‘proxy’ is available.

**Comment by AlexanderChen1989** [comment]
![image](https://user-images.githubusercontent.com/2957936/45294987-bcc64180-b52f-11e8-8d53-54c238f77491.png)

**Comment by AlexanderChen1989** [comment]
![image](https://user-images.githubusercontent.com/2957936/45294992-c780d680-b52f-11e8-8d55-739ed5c91c42.png)

**Comment by sorrycc** [comment]
Proxy is supported by [http-proxy-middleware] (https://github.com/chimurai/http-proxy-middleware) and only supports http.

**Comment by Enzozzzz** [comment]
> ![image](https://user-images.githubusercontent.com/2957936/45294992-c780d680-b52f-11e8-8d55-739ed5c91c42.png)

@AlexanderChen1989 这个问题怎么解决的呀
