### ISSUE TITLE
[Bug] 页面主体区域怎么加入公共组件

### ISSUE THREAD

**Issue by mac-boss** [umijs/umi#10463]
## What happens?

现在每个页面都是直接获取的，能否在页面主体部分再套一层layout组件，而不是每个页面单独写ProLayout组件。
<img width="3360" alt="image" src="https://user-images.githubusercontent.com/1262247/217768499-06a3e379-96e9-4daf-96a7-3d73ca5b1c27.png">

## Context

- **Umi Version**:3.5.0
- **Node Version**:12.16.0
- **Platform**:macos

**Comment by fz6m** [comment]
用 [wrappers](https://umijs.org/docs/guides/routes#wrappers) 。

**Comment by mac-boss** [comment]
> 用 [wrappers](https://v3.umijs.org/zh-CN/docs/routing#wrappers) 。

解决了，👍
