### ISSUE TITLE
[Feature Request]  页面主体区域怎么加入公共组件

### ISSUE THREAD

**Issue by mac-boss** [umijs/umi#10464]
## Background

现在每个页面都是直接获取pages文件里的文件，能否在页面主体部分再套一层layout组件，而不是每个页面单独写ProLayout组件。
![image](https://user-images.githubusercontent.com/1262247/217771875-e1b0cb38-2819-4917-906c-d055adb13392.png)

## Proposal

在app.tsx文件里的layout对象里加入一个方法返回一个页面主体的组件

**Comment by fz6m** [comment]
配置式路由，用 wrappers ，详见文档。
