### ISSUE TITLE
@umijs/max defineConfig 的  dynamicImport loading 没有了， 进入页面一片空白

### ISSUE THREAD

**Issue by 3338606790** [umijs/umi#10470]
```js
import { defineConfig } from '@umijs/max'
```

defineConfig 的  dynamicImport 没有了， 导致进入页面一片空白
dynamicImport是取消了吗？怎么设置自定义的loading页面？

@umijs/max "^4.0.33" 
"antd": "^5.1.0",

**Comment by fz6m** [comment]
在 [`src/loading.tsx`](https://umijs.org/docs/guides/directory-structure#loadingtsxjsx) 。

**Comment by merabtenei** [comment]
> In [`src/loading.tsx`](https://umijs.org/docs/guides/directory-structure#loadingtsxjsx).

Page is still blank when getInitialState is fetching data asyncronously. Take for example a new Ant Design Pro project with Umi Max and just set :
```
export async function getInitialState(): Promise<any> {
  await new Promise((resolve) => setTimeout(resolve, 5000));
  return {};
}
```
This will produce a blank screen for 5 seconds despite defining a loading.tsx in "src" folder.

**Comment by fz6m** [comment]
You need config the `initialState.loading` and make sure it is full screen loading :

```ts
// .umirc.ts

  initialState: {
    loading: '@/loading'
  },
```

recommend to config a full screen loading component instead of a common loading.

```ts
// .umirc.ts

  initialState: {
    loading: '@/loadingFullScreen'
  },
```
