### ISSUE TITLE
手动配置route的方式，如何做到model的按需加载

### ISSUE THREAD

**Issue by tolerance-go** [umijs/umi#1047]
我用的是 pro 脚手架，路由配置不是文件约定的形式而是集中配置，但是在 .umi/DvaContainer.js 中，model 都提前注册了，model 和页面文件的关系没有变呀，所以这个是临时文件就是这样生成的还是 model 按需加载失败了，如果失败了，请问了集中配置路由的方式如何开启 model 按需加载呢

**Comment by sorrycc** [comment]
配置式和约定式一样的，都用 https://umijs.org/plugin/umi-plugin-react.html#dynamicimport 开启。
