### ISSUE TITLE
钉钉安卓端css样式不兼容

### ISSUE THREAD

**Issue by bianchengsuixiang** [umijs/umi#10484]
升级到umi4之后，钉钉安卓端出现了样式不兼容现象（antd也升级到v5版本，react也升级到了v18），在ios上没问题

**Comment by fz6m** [comment]
#### antd

antd 5 的样式默认是 modern 的，参考 [这个](https://ant.design/docs/react/compatible-style-cn) 章节可以降低 css 兼容性，但不确定降级后是否足够。

antd 5 的产物是 es6 的，需要确定你的环境是否支持 es6 。

如果没有确定的基准，建议使用 antd 4 。

#### react

react 18 是不支持 ie 的，如果没有确定的基准，建议使用 react 17 。

#### umi

兼容低版本浏览器见 https://umijs.org/blog/legacy-browser
