### ISSUE TITLE
[umi@2] 关于 router 的值 与 umi@1.x 不一致的问题

### ISSUE THREAD

**Issue by amily4555** [umijs/umi#1049]
umi1.x 的时候 router(umi/router) 带有属性 location 等其他信息
![105511536646363_ pic_hd](https://user-images.githubusercontent.com/2802841/45341913-e1252b00-b5ce-11e8-9bfa-f59069068beb.jpg)

umi@2  的router却没有带相关信息
![105491536646363_ pic](https://user-images.githubusercontent.com/2802841/45342000-2e090180-b5cf-11e8-9e6d-cd5908262912.jpg)

请问 umi@2 是否会和 umi@1 的router 保持一致？

若不保持一致，是否会提供方法在 非 component 中获取到 location 等其他相关信息？

**Comment by amily4555** [comment]
查了下  umi@2 特意对 router 的调用结果做了限制

umi@1.x 是直接返回 g_history 对象


![image](https://user-images.githubusercontent.com/2802841/45344180-99ee6880-b5d5-11e8-80b5-b369a14c5ccb.png)

**Comment by amily4555** [comment]
建议 多返回一个 location,  特别在特别是需要在非component里，异常好用

**Comment by Jetsly** [comment]
@amily4555 
```
window.g_history.location
```
其实还是可以用这个的

**Comment by sorrycc** [comment]
location 直接去 window.location 不就好了吗？

**Comment by xiaohuoni** [comment]
@sorrycc 没看到这些全局变量的文档说明？

**Comment by xiaohuoni** [comment]
@sorrycc 看混了，还以为类似dispatch。之前使用的window.g_app._store.dispatch也没看到说明。
