### ISSUE TITLE
cross-env not work

### ISSUE THREAD

**Issue by halodong** [umijs/umi#10499]
## What happens?

在 package.json 中配置了 
```
 "scripts": {
    "dev": "cross-env UMI_ENV=dev max dev",
}
```
不过没有生效， 请问是不是还需要其他配置。
相关文档： https://umijs.org/docs/guides/env-variables
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

max 脚手架启动的项目。

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
 "@umijs/max": "^4.0.50",
- **Node Version**:
v14.18.3
- **Platform**:
macOS monterey 12.5

**Comment by fz6m** [comment]
`UMI_ENV` 指定成 dev 、prod、test 其实是没用的，默认就会读 `config.dev.ts`  ，详见 https://umijs.org/docs/guides/env-variables#umi_env

**Comment by halodong** [comment]
> `UMI_ENV` 指定成 dev 、prod、test 其实是没用的，默认就会读 `config.dev.ts` ，详见 https://umijs.org/docs/guides/env-variables#umi_env

解决了，感谢
