### ISSUE TITLE
Support nested router

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#105]
Use react-router-config

ref: 

* https://github.com/ReactTraining/react-router/tree/master/packages/react-router-config
* https://medium.com/airbnb-engineering/server-rendering-code-splitting-and-lazy-loading-with-react-router-v4-bfe596a6af70

**Comment by sorrycc** [comment]
> WIP

## 方案

把有嵌套规则的 routesConfig 渲染到页面上。

e.g. routesConfig

```js
[
  { path: '/', exact: true, component }
  { path: '/list', component,
    routes: [
      { path: '/list', exact: true, component },
      { path: '/list/$id', exact: true, component },
    ],
  }
]
```

由于 react-router-config 必须有 root 节点，所有需要套一层 layout。layouts/index.js 存在时用它，不存在时用一个假的。转换为：

```js
[
  component: './layouts/index.js',
  routes: [/* OLD_ROUTES */]
]
```

由于需要处理 component、按需编译和按需加载，所以得把 routesConfig 输出到页面上，（用字符串注释配置数据占位，然后用 JSON.stringify 转成 JSON，再用 String.prototype.replace 替换应该会简单些）

```js
const routes = [
  {
    component: 'require("./xxxxxx")',
    routes: [...]
  }
];
```

**Comment by zjxpcyc** [comment]
react-router-config 可能有不支持动态加载的问题

**Comment by huangshunping** [comment]
@sorrycc 云谦

我今天发现配置了page.js后，别的路由就不生成了，然后找到了这里，建议把下面这段话放到官方的文档里面。也是一种约定

```
注意：

不要用 page.js，因为用了 page.js 就不会往下找了
有 page.js 时同级目录下 _layout.js 不生效，因为没有必要
用 umi-plugin-routes 忽略一些不需要作为路由的文件，比如 models/**/*.js
有 layout 时会嵌套一层，没有则拍平
```
