### ISSUE TITLE
首屏加载显示骨架的常规写法报错

### ISSUE THREAD

**Issue by ZhaoHaiPengPro** [umijs/umi#1050]
首屏加载时为了解决白屏问题 使用了自定义的入口模板 在模板中加入了静态skeleton
document.ejs如下:
![image](https://user-images.githubusercontent.com/15197204/45342901-e0da5f00-b5d1-11e8-9462-5c7ddbc2cfc8.png)
运行报错如下:
![image](https://user-images.githubusercontent.com/15197204/45342959-036c7800-b5d2-11e8-85b0-eb124cb23acb.png)
请问各位大神
1 后续是否会支持这种写法
2 是否有更优雅的方式解决首屏加载白屏的问题

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/921
https://github.com/umijs/umi/pull/972
