### ISSUE TITLE
如何是 build 之后的代码不发生压缩，即函数、变量等名称不发生改变

### ISSUE THREAD

**Issue by yuribrown** [umijs/umi#10503]
因为需要将 build 之后的文件与其它英语程序结合使用，代码压缩后，不便于查看报错、调试

**Comment by fz6m** [comment]
`compress=none umi build`

**Comment by yuribrown** [comment]
> `COMPRESS=none umi build`

您好，谢谢！请问这个应该在哪里配置啊？

**Comment by yuribrown** [comment]
试了一下，可以在 .env 中配置 COMPRESS=none
