### ISSUE TITLE
[Bug] umi4 的 menu access 刷新之后，页面仍为 403 不刷新

### ISSUE THREAD

**Issue by tizips** [umijs/umi#10513]
UMI4 的 Menu 通过 initialState 判断 access。在 initialState 经过前几次的其他数据更新之后，再更新权限数据并进行路由权限判断，此时页面不会更新为正常应该显示的页面，依旧显示的为 403 页面

![WX20230214-164747@2x](https://user-images.githubusercontent.com/19277632/218684955-271fa99c-3665-4a88-a117-d169872c3bf3.png)

**Comment by fz6m** [comment]
`getInitialState` 如果是异步获取的，在执行完前页面不能渲染内容，需要条件判断展示 loading ，等真正确保你所有需要的数据准备好后再开始渲染主应用。

**Comment by tizips** [comment]
我有尝试直接设置 menu 的 loading 属性，但是没法通过 initialState 内容来判断。

之后根据 menu 的 params 属性，来判断  initialState 的内容变动，调用 request 另外达到 menu 的 loading 属性修改，但是在加载之后主应用内容依旧是无法变更的，仍然显示为 403 页面。

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/19277632/218914461-7ea86d37-9ad0-4b98-949d-8dff0c453c5d.png">

**Comment by fz6m** [comment]
你的场景比较特定，通过文本很难理解，如还有问题，请给一个最小复现。

**Comment by tizips** [comment]
仓库：https://github.com/tizips/uper-admin

复现地址：http://localhost:8000/site/admin

**Comment by fz6m** [comment]
预期在 `getInitialState` 就已经获取完全部初始状态了，之后 `initialState` 不会发生更改，因为 `getInitialState` 结束后就开始渲染了，而你后面还要异步的请求接口去改 `initialState` 的话，这个时候已经渲染完了，自然是不可取的。

解决办法：

1. 在 `getInitialState` 就把所有可能用到的数据获取完毕，不要后续再 set 修改 `initialState`

2. 如果都写在 `getInitialState` 不方便，可以上一层 `dataflowProvider` ，在这里面获取 initial state 数据，异步请求没得到结果前不要渲染 children ，展示 loading 。

```tsx
// app.tsx

export const dataflowProvider = (children) => {
  return <Provider>
    {children}
  </Provider>
}
```

**Comment by tizips** [comment]
好的，谢谢
