### ISSUE TITLE
[Feature Request] request caching in umi4

### ISSUE THREAD

**Issue by merabtenei** [umijs/umi#10515]
## Background

In umi3 request were made with umi-request which supported cache. In umi4 as stated in the documentation, umi-request was deprecated and Axios is used instead.

## Proposal

Is there currently any way for requests caching in umi4 ?
If not we can use 3rd party libraries like axios-cache-adapter but we would need to have more control over the way AxiosInstance is created.

**Comment by fz6m** [comment]
umi 4 recommends using [`react-query`](https://github.com/TanStack/query) to provide caching / mutate / loading etc.

**Comment by xXAvoraXx** [comment]
> umi 4 recommends using [`react-query`](https://github.com/TanStack/query) to provide caching / mutate / loading etc.

安裝這個插件後可以繼續使用use request嗎？

**Comment by fz6m** [comment]
不可以，现在不推荐使用 use request 了，现代数据流中更推荐使用 react-query 。

**Comment by xXAvoraXx** [comment]
> 不可以，现在不推荐使用 use request 了，现代数据流中更推荐使用 react-query 。

從“@umijs/max”導入{請求}； 基本上都是使用axios。 我測試了它是否可以與 useQuery 一起使用並且它有效。
import { request } from "@umijs/max"; It basically uses axios. I tested if it would work with useQuery and it worked.


```
export async function getCountriesRequest() {
    const msg = await request<API.DataResultType<DTOS.CountryDto[]>>('/api/constant/GetCountries', {
      method: 'GET',
    });
    return msg;
}

  const { isLoading: loadingCountries, isSuccess, data: countries, refetch: runCountries } = useQuery(['query'], getCountriesRequest, {
    enabled: false,
    retry: 2,
  });
```
