### ISSUE TITLE
[Bug] 按照umi上的qiankun配置以后报错

### ISSUE THREAD

**Issue by mac-boss** [umijs/umi#10519]
## What happens?

按照文档配置以后报错

在底座里点击子应用的路由以后报错
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/1262247/218938164-4e99de42-22dd-41df-9a4a-31a6f5235bf6.png">

## How To Reproduce

底座 `config/config.ts` 里添加了

```
qiankun: {
    master: {
      apps: [
        {
          name: 'cashier',
          entry: '//localhost:8001',
        }
      ],
    },
  },
```

`routes.ts` 里添加了

```
{
    name: 'cashier',
    path: '/cashier/ant-design-pro/*',
    microApp: 'cashier',
  },
```

子应用 `config/config.ts` 里添加了
```
 qiankun: {
    slave: {},
  },
```

## Context

- **Umi Version**: 4.x
- **Node Version**:16.19.0
- **Platform**:macos

**Comment by fz6m** [comment]
给一个最小复现。

**Comment by mac-boss** [comment]
> 给一个最小复现。

解决了，关闭mfsu即可，需要注意的是，最新版本的不能是注释掉就关闭了，而是要标记为false，也就是mfsu: false,

**Comment by fz6m** [comment]
可以看一下这个问题是不是和 `mf` 必须显示关闭 mfsu 一样，qiankun 也被影响到了 @stormslowly  🌹
