### ISSUE TITLE
[Bug] umi应用使用npm link的方式调试npm包，热更新失效

### ISSUE THREAD

**Issue by amibug** [umijs/umi#10545]
## What happens?

使用npm link的方式在umi应用中调试dumi组件。 dumi组件通过father dev开启 build:watch， umi应用中的node_module实时更新，但是umi应用热更新失效。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

请参考 [最小重现Demo](https://github.com/amibug/umi-npmlink)

## How To Reproduce
1.  组件开发
```bash
$ cd mockjs
$ npm install
$ npm run build:watch
$ npm link
```

2.  组件在umi应用中调试
```bash
$ cd umiApp
$ npm install
$ npm link mockjs
$ npm run start
```

## Context

- **Umi Version**: 4.0.52
- **Node Version**: 16.6.0
- **Platform**: macOs

**Comment by amibug** [comment]
冒昧问下：有人在跟进处理吗？

**Comment by fz6m** [comment]
尝试下 pnpm + link 的方式：

```ts
// package.json

  "dep-name": "link:/absolute/path/to/pkg/root"
```

**Comment by amibug** [comment]
> 尝试下 pnpm + package.json link 的方式：
> 
> ```ts
> // package.json
> 
>   "dep-name": "link:/absolute/path/to/pkg/root"
> ```

测试无效

**Comment by fz6m** [comment]
配置排除下要调试的包名：

```ts
// .umirc.ts

export default {
  mfsu: {
    exclude: ['package-name']
  },
}
```

**Comment by noxxxxxxxx** [comment]
> 配置排除下要调试的包名：
> 
> ```ts
> // .umirc.ts
> 
> export default {
>   mfsu: {
>     exclude: ['package-name']
>   },
> }
> ```

如果没有开启 mfsu 要如何配置？

**Comment by fz6m** [comment]
有一个 [`extraBabelIncludes`](https://umijs.org/docs/api/config#extrababelincludes) 的配置，把你的包名或者正则配进去，让 babel 去额外编译这个包试试。

**Comment by Snorlaxx-plot** [comment]
同问

> 有一个 [`extraBabelIncludes`](https://umijs.org/docs/api/config#extrababelincludes) 的配置，把你的包名或者正则配进去，让 babel 去额外编译这个包试试。

同问，import CCLayout from "main/src/features/layout";我目前使用两种方法：1.   mfsu: {
    exclude: ["main"],
  },
  extraBabelIncludes: ["main"], 2.   monorepoRedirect: { srcDir: ["../src"] }, main中代码更新后都无法触发热更新，不知道是否有更好的解决办法？
