### ISSUE TITLE
我想二次封装useAppData，但是里面的属性没有类型导出

### ISSUE THREAD

**Issue by seafronthu** [umijs/umi#10547]
## What happens?
我想封装useAppData的routes，但是该类型没有导出。

## Mini Showcase Repository(REQUIRED)
https://github.com/seafronthu/product-management/blob/main/src/layouts/OutermostLayout.tsx

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
```javascript
let clientRoutesObj: { [key: string]: IClientRoute } | null = null;
const getClientRoutesObj = (clientRoutes: IClientRoute[]) => {
  if (clientRoutesObj) {
    return clientRoutesObj;
  }
  clientRoutesObj = {}
  const datas = [...clientRoutes]
  while (datas.length) {
    const data = datas.pop()
    if (data.children) {
      datas.push(...data.children)
    }
    clientRoutesObj[data.path] = data
  }
  return clientRoutesObj
}
```
**Expected behavior** 1. 2.
![image](https://user-images.githubusercontent.com/50374650/219872429-a695952b-2374-47fb-810e-70bf78fe6ccb.png)

## Context

- **Umi Version**: 4.0.52
- **Node Version**: v16.4.0
- **Platform**: MacOs

**Comment by fz6m** [comment]
这个类型还不够完善，现在没放出来，如有需要可使用 [工具类型](https://www.typescriptlang.org/docs/handbook/utility-types.html) 获取。

**Comment by seafronthu** [comment]
> 这个类型还不够完善，现在没放出来，如有需要可使用 [工具类型](https://www.typescriptlang.org/docs/handbook/utility-types.html) 获取。

```javascript
type UseAppDataType = ReturnType<typeof useAppData>
type IClientRouteType = UseAppDataType["clientRoutes"][0]
```
