### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by Chill7773** [umijs/umi#10541]
## What happens?
架构变换，运行时配置的菜单样式变化

## Mini Showcase Repository(REQUIRED)
 我将umi版本升级到4以后，样式没有出现问题（旧版antd-pro的样式）。
![image](https://user-images.githubusercontent.com/39217534/219588138-375a580c-c2b3-4b12-b747-e77f66a8722a.png)

但是我将项目迁移到monorepo架构的项目中时，出现了样式问题（旧版样式变成了新版样式）。
![image](https://user-images.githubusercontent.com/39217534/219588031-727f14ba-8eaa-481a-9a6d-1e809c393adb.png)

然后我发现了两个ant pro-components的版本
<img width="483" alt="image" src="https://user-images.githubusercontent.com/39217534/219588852-ed13417e-d71b-4b3f-99c6-785e03b3c718.png">

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

1. 执行`pnpm dlx create-umi@latest`, 下载antd-pro模版
2. 进行antd组件降级
```bash
+   "@ant-design/pro-components": "^1",
+   "antd": "^4"
```
3. 安装依赖构建 则旧版样式生效
4. 项目修改为monorepo架构，旧版组件失效

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version*4.0.52*:
- **Node Version*16*:
- **Platform*macOS*:

**Comment by fz6m** [comment]
需要给最小复现。
