### ISSUE TITLE
[Bug] 　微前端下路由和全局布局的菜单样式不匹配

### ISSUE THREAD

**Issue by Chill7773** [umijs/umi#10557]
## What happens?
微前端路由和全局布局菜单组件匹配问题

路由配置如下：
```js
export default [
  {
    path: '/user/login',
    layout: false,
    name: 'login',
  },
  {
    path: '/audit',
    name: '审核管理',
    icon: 'audit',
    routes: [
      {
        path: '/audit',
        redirect: '/audit/homepage',
      },
      {
        name: '我的首页',
        path: '/audit/homepage',
        icon: 'home',
        component: './Home',
      },
      {
        name: '审核任务',
        path: '/audit/reviewtasks',
        component: './Home',
      },
      { component: './404' },
    ],
  },
  // 微前端断点管理
  {
    path: '/system/*',
    name: '系统管理',
    icon: 'menu',
    microApp: 'system',
  },

  {
    path: '/',
    redirect: '/audit',
  },
  { path: '/*', component: './404' },
];

```

![image](https://user-images.githubusercontent.com/39217534/220265213-e4483baf-58d9-4ea0-adfe-0809c106f571.png)

以上`系统管理`菜单项没有高亮

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/Chill7773/umi-bug

## How To Reproduce

- clone `https://github.com/Chill7773/umi-bug`

- 执行`pnpm i`

- 启动子应用 `npm run dev:child`

- 启动主应用 `npm run dev:main`

- 进入`http://localhost:8000/#/system/account`

- 发现bug
**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: ^4.0.52
- **Node Version**: 16
- **Platform**: macOS

**Comment by Chill7773** [comment]
好像是 因为 `path: '/system/*',` 导致的。更换为`path: '/system'`可以解决。但是这样微应用配置无法生效。

使用组件和子路由的方式又有一堆bug。。。

**Comment by fz6m** [comment]
```ts
  {
    path: '/system',
    name: '系统管理',
    icon: 'menu',
    routes: [
      {
        path: '/system/',
        microApp: 'system',
      },
      {
        path: '/system/*',
        microApp: 'system',
      },
    ],
  },
```

**Comment by YuZongYangHi** [comment]
> ```ts
>   {
>     path: '/system',
>     name: '系统管理',
>     icon: 'menu',
>     routes: [
>       {
>         path: '/system/',
>         microApp: 'system',
>       },
>       {
>         path: '/system/*',
>         microApp: 'system',
>       },
>     ],
>   },
> ```

解决了么？

**Comment by Chill7773** [comment]
> microApp: 'system',

解决是解决了 但是会进入子应用两次，明显看见子应用在闪烁

**Comment by Chill7773** [comment]
> > ```
> >   {
> >     path: '/system',
> >     name: '系统管理',
> >     icon: 'menu',
> >     routes: [
> >       {
> >         path: '/system/',
> >         microApp: 'system',
> >       },
> >       {
> >         path: '/system/*',
> >         microApp: 'system',
> >       },
> >     ],
> >   },
> > ```
> 
> 解决了么？
解决是解决了 但是会进入子应用两次，明显看见子应用在闪烁
