### ISSUE TITLE
[Bug] MFSU x Valtio 报错

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#10560]
复现步骤：

1、git clone umijs/umi 后切换到 sorrycc-14dt 分支（如果这个分支没了，那应该是已合并到 master）
2、修改 ui/.umirc.ts，删除 `mfsu: false`
3、执行 pnpm --filter @umijs/ui dev，报错如下

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/35128/220275402-52d3c275-d635-4596-8be3-ed34280e327e.png">

期望：

不报错。

**Comment by stormslowly** [comment]
https://github.com/umijs/umi/blob/master/packages/mfsu/src/babelPlugins/awaitImport/checkMatch.ts#L11-L16

valito 的位置 packages 之外，所以就认定成项目依赖， 然后就 React 多实例了。

解法 1

把 libs 也放进 `isUmiLocalDev` ([PR](https://github.com/umijs/umi/pull/10594)) or 把  valito 目录 挪进 packages  (PR)[https://github.com/umijs/umi/pull/10595]

解法 2（临时）

` mfsu: { shared : {react: { singleton: true , strictVersion: false}}}`

**Comment by fz6m** [comment]
mfsu 可以默认配置 react singleton true 吗，因为 react 必然要是单实例的。

**Comment by stormslowly** [comment]
react 就需要两边都编译 有一定的性能损耗

**Comment by fz6m** [comment]
react 只有 10kb ，相比损耗貌似出现这个问题的概率要大一些。

**Comment by stormslowly** [comment]
可以考虑  benchmark 看下 决定搞不搞
