### ISSUE TITLE
mini-css-extract-plugin报错

### ISSUE THREAD

**Issue by yoyooyooo** [umijs/umi#1056]
![menu saveimg savepath20180911192352](https://user-images.githubusercontent.com/18062745/45357802-03806e00-b5fa-11e8-866e-4c136973e765.jpg)
我用create-umi新建的空项目第一次能打开页面，多编译几次就会出现这个错误，不用create-umi也会这样，但是我老项目不会遇到这问题，哪里姿势不对么。
不是文档提到的那种可以无视的警告，，直接报错页面也错误了。。

**Comment by sorrycc** [comment]
怎么复现？

**Comment by yoyooyooo** [comment]
@sorrycc 有点玄学，我反复建过好几个空项目，遇到过刚创建一开始好的，我也没加什么东西，build了一下，回头稍微改几个字多编译了几次就出现了这问题，但是不是每次都会遇到。
家里和公司电脑都出现过同样的图片里的错误。现在想刻意复现又不出错了。

**Comment by xiaohuoni** [comment]
Mac和Windows上反复重试了很多次，都无法重现，有问题再reopen吧
