### ISSUE TITLE
webpack的 mode配置成development，target设置es2020才生效

### ISSUE THREAD

**Issue by AnitaTang** [umijs/umi#10572]
## What happens?

编译打包umi工程的时候，umi工程的js代码中用到了es2020中的bigint类型，打包的时候需要设置webpack的target支持es2020，
但是需要同时设置webpack mode为development才生效，设置成production不生效。所以想了解下为啥webpackmode必须设置
为development，能不能修改成production？
  chainWebpack(memo, { env, webpack }) {
    memo.mode('production');
    memo.target(['web', 'es2020']);
  },
![20230222165248](https://user-images.githubusercontent.com/4083548/220570149-ff9b32d3-cb84-490d-b330-1f154e7996d5.jpg)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
重现仓库： https://github.com/AnitaTang/umi_test

tnpm run build即可重现

## Context

- **Umi Version**: v4
- **Node Version**:18
- **Platform**: mac os

**Comment by fz6m** [comment]
需要调整压缩器：

```ts
// .umirc.ts

  jsMinifier: 'terser'
```

**Comment by AnitaTang** [comment]
谢谢，验证通过。能给解释下为啥是这样吗？

**Comment by mmzzli** [comment]
export default {
  headScripts: [
    'http://polyfill.alicdn.com/v3/polyfill.min.js',
  ],
  legacy: {},
};
我用这个解决了问题
