### ISSUE TITLE
[Feature Request]umi3升级到umi4后 如何配置devServe的devMiddleware，现在都不支持了

### ISSUE THREAD

**Issue by huliang1996618** [umijs/umi#10571]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by xiaohuoni** [comment]
这里？ https://umijs.org/docs/api/plugin-api#addmiddlewares

**Comment by fz6m** [comment]
参考 [devServer 选项怎么配置](https://umijs.org/docs/introduce/faq#devserver-%E9%80%89%E9%A1%B9%E6%80%8E%E4%B9%88%E9%85%8D%E7%BD%AE) ，通过一些配置，理论上可以支持你想要的。
