### ISSUE TITLE
window.onerror  开发环境可以触发  线上生产环境无法触发

### ISSUE THREAD

**Issue by YunFan68** [umijs/umi#10578]
window.onerror = function(msg,url,line,col,error){
// 开发环境可以触发  线上生产环境无法触发
        console.log(error.stack)
}

**Comment by fz6m** [comment]
看一下你是不是有其他的监控库或者 sdk 把这个事件早就拦截过一次了，或者错误在开发触发，但在生产被捕获不触发。
