### ISSUE TITLE
umi/link onClick 在 TS 下报错

### ISSUE THREAD

**Issue by dreamerblue** [umijs/umi#1058]
```<Link to="/user" onClick={onLinkClick}>User</Link>```

编译后的 JS 可以正常运行，但是 onClick 传入 `<Link>` 会导致 TS 报错：

error TS2339: Property 'onClick' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Link> & Readonly<{ children?: ReactNode; }> & Readonly<{ to: string | { pathname: string; search?: string; hash?: string; state?: any; }; replace?: boolean; innerRef?: Function; title?: string; id?: string; className?: string; }>'.

想请教下如何解决？

**Comment by xiaohuoni** [comment]
umi/link只是用来做声明方式的路由跳转，不要使用onClick。
有点击需求的话可以这样使用
```
<Link to="/user"><button onClick={onLinkClick}> User </button></Link>
```

**Comment by dreamerblue** [comment]
了解了谢谢。

**Comment by dreamerblue** [comment]
> umi/link只是用来做声明方式的路由跳转，不要使用onClick。
> 有点击需求的话可以这样使用
> 
> ```
> <Link to="/user"><button onClick={onLinkClick}>User</button></Link>
> ```

@xiaohuoni 
经测试这样写没有效果，\<button\> 上的点击事件无法被触发，只能触发父元素 \<Link\> (\<a\>) 上的点击事件。

使用了 antd 的代码片段：
```
<Menu.Item key="/user">
    <Link to="/user"><button onClick={onLinkClick}>User</button></Link>
</Menu.Item>
```

**Comment by farashraid** [comment]
解决了吗我也遇到相同问题了

**Comment by dreamerblue** [comment]
> 解决了吗我也遇到相同问题了

可以考虑从 react-router-dom 引入 Link 来使用。它的 typings 比较全面。

**Comment by xiaohuoni** [comment]
```
export {
  Link,
  ...
} from 'react-router-dom';
```

**Comment by farashraid** [comment]
> > 解决了吗我也遇到相同问题了
> 
> 可以考虑从 react-router-dom 引入 Link 来使用。它的 typings 比较全面。

感谢,我最后用了,prolayout的onchange事件来代替link的点击

**Comment by farashraid** [comment]
> https://github.com/umijs/umi/blob/b1fc715e421a9c9ab9036d9708c8335f438b5dae/packages/runtime/src/index.ts#L2
> 
> ```
> export {
>   Link,
>   ...
> } from 'react-router-dom';
> ```

感谢,我最后用了,prolayout的onchange事件来代替link的点击
