### ISSUE TITLE
[Task] routeProps 文档与测试用例补全

### ISSUE THREAD

**Issue by fz6m** [umijs/umi#10584]
## 任务

1. 补全 `routeProps` 使用文档于 [路由 > 约定式路由](https://umijs.org/docs/guides/routes) 章节。

2. 补充一个 e2e 测试用例。

cc @AdoKevin ，如有兴趣继续参与，欢迎继续 PR 。

## 来源

              @AdoKevin  这个新的 feature 可以加一些 example 来示例 和 e2e 用例保护下

_Originally posted by @stormslowly in https://github.com/umijs/umi/issues/10527#issuecomment-1441120103_

**Comment by AdoKevin** [comment]
@fz6m  https://github.com/umijs/umi/pull/10593 已经添加， 但有两个问题。
1. 文档暂时写的开启方式为约定式路由默认开启， 配置式路由手动开启，具体的配置方式修改还没有完成？
2. 我有注意到在routeProps导出的属性中，禁止了`layout` 属性，我的理解这个是为了禁用全局layout的，这里禁止是出于什么考虑呢？
