### ISSUE TITLE
请问进行redirect跳转如何获取query参数

### ISSUE THREAD

**Issue by free-pan** [umijs/umi#1059]
路由配置:
```
routes: [
        {
            path: '/', component: 'Index',
            routes: [//示例路由配置, 实际要删除
                {path: '/', component: 'api-detail/ApiDetail'},
                {path: '/:tagKey/:apiKey', component: 'api-detail/ApiDetail'},
                {path: '/redirect/:tagKey/:apiKey', redirect: '/:tagKey/:apiKey'}
            ]
        },
    ]
```

`{path: '/redirect/:tagKey/:apiKey', redirect: '/:tagKey/:apiKey'}`

实际跳转时的地址: 

`/redirect/11/26?type=product&price=12`

进行redirect之后

`/redirect/11/26`

redirect的时候我要怎样把`?type=product&price=12`这一段也带过去,或者说我在redirect之后的页面,
怎样才能再次获取到`type`和`price`的值

**Comment by sorrycc** [comment]
按我理解，这个声明式的 redirect 做不了，在需要跳转的地方用命令式的 `require('umi/router').push` 或 `require('umi/router').replace` 吧。

**Comment by zbh876325764** [comment]
这个分支合并被阻止了? 那这个问题怎么解决?
