### ISSUE TITLE
[Bug] 使用tailwindcss后ant样式被覆盖

### ISSUE THREAD

**Issue by wulibaibao** [umijs/umi#10599]
## What happens?

**使用tailwind后ant部分样式被覆盖，如何处理优先级？**

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
你可能需要 `preflight` （ https://github.com/umijs/umi/issues/9565#issuecomment-1285185630 ）

或者不使用 `@tailwind base;`
