### ISSUE TITLE
按官网示例创建项目一行代码没改build后白屏

### ISSUE THREAD

**Issue by mike8625** [umijs/umi#10591]
## What happens?

使用 yarn create umi,  然后选择 antd pro 那个, 然后镜像选taobao, 完成后啥也没干 直接 npm run build, build出来的页面在http://localhost开头的地址下显示白屏,f12 看啥信息也没有.
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0.52
- **Node Version**: 16.17
- **Platform**: win10

**Comment by mike8625** [comment]
npm run dev是可以显示的

**Comment by fz6m** [comment]
给一个完整操作有问题的视频看看，帮助排查问题。
