### ISSUE TITLE
Support load env with dotenv

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#106]
ref:

* https://github.com/sorrycc/roadhog/pull/186
* https://github.com/motdotla/dotenv

action:

* [x] read env from .env
* [x] set to process.env
* [ ] pass to DefinePlugin

**Comment by sorrycc** [comment]
umi@2 里已支持。

**Comment by nelhu** [comment]
> umi@2 里已支持。

how to load specific dotenv file when more dotenv files exists
