### ISSUE TITLE
[Bug] umi4配置路径runtimePublicPath

### ISSUE THREAD

**Issue by coderew** [umijs/umi#10600]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 
<img width="422" alt="image" src="https://user-images.githubusercontent.com/20498067/221137261-6f470e41-6ec1-4d84-bd97-009f4d14958c.png">

**Expected behavior** 
报错：
`AssertionError [ERR_ASSERTION]: Invalid config values: runtimePublicPath
Invalid value for runtimePublicPath:
"value" must be of type object`

## Context

- **Umi Version**:4.0.0-rc.22
- **Node Version**:
- **Platform**:mac os

**Comment by fz6m** [comment]
这个选线不要自己配置，他是 qiankun 子应用会自动启用的，自己配置没用。

**Comment by coderew** [comment]
> 这个选项不要自己配置，他是 qiankun 子应用会自动启用的，自己配置没用。

嗯，设置runtimePublicPath:{}, pathPath为cdn路径，部署到线上后，qiankun主应用拉子应用的异步静态资源，路径并没有替换成cdn路径：

<img width="889" alt="image" src="https://user-images.githubusercontent.com/20498067/221214449-a908c702-9bfe-4176-8aaa-af25b02f8fef.png">
非异步静态资源替换成了public Path，正常情况下，异步静态资源前面的路径也应该替换成cdn路径，但是并没有，请问是什么原因呢？

**Comment by fz6m** [comment]
给一个最小复现看看。

**Comment by coderew** [comment]
我的问题跟这个issue一样：https://github.com/umijs/umi/issues/8733。但是不知道怎么解决

**Comment by bingyang519** [comment]
> 我的问题跟这个issue一样：#8733 但是不知道怎么解决

已解决
https://github.com/umijs/umi/issues/4352#issuecomment-2022620239
