### ISSUE TITLE
umi新建项目并build后页面空白

### ISSUE THREAD

**Issue by Shen-Shuyi** [umijs/umi#10613]
### Discussed in https://github.com/umijs/umi/discussions/10612

<div type='discussions-op-text'>

<sup>Originally posted by **Shen-Shuyi** February 27, 2023</sup>
新建了umi项目, 且未添加任何自己的代码, start可以正常看到Page Index页面, 但build后双击index.html页面空白
一开始显示报错找不到umi.css和umi.js, 手动修改index.html将`/umi.css`,`/umi.js`改为`./umi.css`和`./umi.js`后报错消失且能正常下载到css和js文件, 但页面依然空白, 此时控制台没有任何报错, 网络也没有异常, 请问是什么原因?  
umi版本3.5.37
使用pnpm install下载依赖包</div>

**Comment by sorrycc** [comment]
双击不能打开时 feature ...
