### ISSUE TITLE
出现全局window.error或者promise.reject，页面就会卡死（捕捉了也一样）

### ISSUE THREAD

**Issue by Aug-Sunrise** [umijs/umi#10611]
"dependencies": {
    "axios": "^1.3.4",
    "dplayer": "^1.27.1",
    "echarts": "^5.4.1",
    "hls.js": "^0.14.17",
    "lodash": "^4.17.21",
    "react-vant": "^3.1.5",
    "umi": "^4.0.53",
    "use-immer": "^0.8.1",
    "vconsole": "^3.15.0",
    "zustand": "^4.3.3"
  },
  "devDependencies": {
    "@types/dplayer": "^1.25.2",
    "@types/lodash": "^4.14.191",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "@umijs/plugins": "^4.0.53",
    "postcss-px-to-viewport-8-plugin": "^1.2.0",
    "prettier": "^2",
    "prettier-plugin-organize-imports": "^2",
    "prettier-plugin-packagejson": "^2",
    "tailwindcss": "^3",
    "typescript": "^4.1.2"
  }

https://user-images.githubusercontent.com/51350414/221453900-e8392399-71e6-449d-a040-53595cff421a.mov

**Comment by fz6m** [comment]
把 `mfsu: false` 关了，再观察下是哪个文件发出的报错，去那个文件排查是哪部分逻辑导致了这个问题。

目前可以看到 `page-nine.tsx:18` 这个文件对应的 onLogout 造成了这个问题。

**Comment by Aug-Sunrise** [comment]
> 把关`mfsu: false`了，再察看下是哪个文件发出的报错，去那个文件排查是哪个部分分发导向了这个问题。
> 
> 之前可以看到`page-nine.tsx:18`这个文件对应的onLogout 生成了这个问题。

报错是我故意抛出的，是因为我想知道为什么promise.reject和window.error的错误会导致umi卡死(~.~)

**Comment by Aug-Sunrise** [comment]
> 把 `mfsu: false` 关了，再观察下是哪个文件发出的报错，去那个文件排查是哪部分逻辑导致了这个问题。
> 
> 目前可以看到 `page-nine.tsx:18` 这个文件对应的 onLogout 造成了这个问题。


https://user-images.githubusercontent.com/51350414/222052618-b4fc9b19-7669-4349-88f4-83dc8fab97e3.mov

报错之后，页面卡死，大约会在几秒钟后恢复正常，目前已使用vite重写（同样的代码和依赖，重写之后没有出现类似问题）
