### ISSUE TITLE
[Bug] max 初始化后的项目在移动设备窗口大小下，菜单无法关闭

### ISSUE THREAD

**Issue by conorzhong** [umijs/umi#10616]
## What happens?

max 初始化后的项目在移动设备窗口大小下，菜单无法关闭

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

pnpm create umi 选择 max 模板

https://github.com/conorzhong/umi-bug-report-202202271324

## How To Reproduce

**Steps to reproduce the behavior:** 
1. 缩放到汉堡菜单出现
2. 点击汉堡
<img width="566" alt="image" src="https://user-images.githubusercontent.com/39456642/221480624-0174e3f0-2296-4ddc-b718-21433fdccd68.png">
3. 菜单无法关闭
<img width="493" alt="image" src="https://user-images.githubusercontent.com/39456642/221480944-e9029b25-3133-463e-ae44-8bae7d01cbef.png">

**Expected behavior**
1. 可以关闭菜单

## Context

- **Umi Version**: 4.0.53
- **Node Version**: 14.18.2
- **Platform**: MBP M2 Ventura 13.1

**Comment by fz6m** [comment]
我没遇到你这个问题，是真机？尝试升级最新的 umi 4 版本，如果还有问题，再开 issue 反馈。

<img src='https://user-images.githubusercontent.com/59400654/229113085-ab55384b-ba60-4ba0-b332-5f035ce5e638.gif' width='35%' />
