### ISSUE TITLE
在scss文件中保存，vscode-stylelint插件就会报错

### ISSUE THREAD

**Issue by beilo** [umijs/umi#10610]
## What happens?

一进入scss文件，vscode的stylelint插件就会报错。错误提示如下：
Stylelint: Could not find "stylelint-scss". Do you need the "configBasedir" or "--config-basedir" option?
<img width="454" alt="image" src="https://user-images.githubusercontent.com/19225489/221415314-3c4586c8-376a-4d9e-8680-1383fc7967bf.png">

stylelint相关的插件只有
```json
// package.json
   "stylelint": "^15.1.0",
    "stylelint-scss": "^4.4.0",
```

```js
// .stylelintrc.js代码如下
module.exports = {
  extends: require.resolve('umi/stylelint'),
  configBasedir: './',
};
```

已经存在的老项目（非umi，没有这个问题。猜测是stylelint版本过高导致？
或许说不用这个vscode插件了？有什么更好的替代品吗？

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
[umi-codemao-mobile.zip](https://github.com/umijs/umi/files/10833858/umi-codemao-mobile.zip)
这是我的最小代码复现，
可以进入`src/pages/index.scss`这个文件点击保存。
报错插件为：https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:"umi": "^4.0.52"
- **Node Version**:v16.19.0
- **Platform**: mac

**Comment by fz6m** [comment]
umi 内置的 stylelint 规则不支持 scss ，只默认支持 less 。

**Comment by beilo** [comment]
@fz6m 如果要支持scss，我需要做些什么处理呢？
还是说，拥抱less？

**Comment by fz6m** [comment]
不建议使用 stylelint ，目前只有组件库会用 stylelint ，同时发展趋势是 css in js ，这个工具逐渐被淘汰了。
