### ISSUE TITLE
[Bug] umi3 upgrade to umi4 by max: Cannot read properties of undefined (reading 'applyPlugins')

### ISSUE THREAD

**Issue by custs21113** [umijs/umi#10629]
## What happens?

当使用max将umi3升级至umi4时，开启国际化后报错。
![image](https://user-images.githubusercontent.com/38849744/221741578-002c14cc-51b7-424d-bbeb-902b3a7665cf.png)

**Expected behavior** 1. 2.

依照https://umijs.org/docs/introduce/upgrade-to-umi-4  升级项目，并开启国际化就会报这个错误。
## Context

- **Umi Version**:4
- **Node Version**:14.19.1
- **Platform**:win

**Comment by fz6m** [comment]
升级到最新的 umi 版本 `4.0.53` 看下，如还有问题，需提供一个最小复现。

**Comment by wshuhua** [comment]
这个有解决吗
