### ISSUE TITLE
[Feature Request] 支持配置 react-intl 的 onError 钩子

### ISSUE THREAD

**Issue by hyzx86** [umijs/umi#10626]
## Background

这个错误很烦人。。因为我的菜单是动态加载的，可能加载出来的时候国际化还没处理好
实际上最终呈现的翻译效果是没问题的，但是控制台一堆的这种报错 其它内容都给顶上去了

[React Intl] Missing message: "menu.home" for locale: "zh-CN", using default message as fallback. 

文档中提到  ： 在底层，国际化插件基于 [react-intl](https://github.com/formatjs/formatjs/tree/main/packages/react-intl) 封装，并支持它的所有接口，详情可见[此文档](https://github.com/formatjs/formatjs/blob/main/website/docs/react-intl/api.md)。

是不是可以通过配置 这个事件钩子 来消除错误呢？
请教如何修改，如果目前不能修改是否可以开放这些参数配置？谢谢！

## onError
Allows the user to provide a custom error handler. By default, error messages are logged using console.error if NODE_ENV is not set to production.

**Comment by hyzx86** [comment]
我这么改 是生效的，但。。正确的方法是~？

![image](https://user-images.githubusercontent.com/15613121/221597558-f6b74ac6-ef83-4b9d-a07c-1be2c6ff6282.png)

**Comment by fz6m** [comment]
#10766 支持了，更新最新 umi 版本即可，文档在 [自定义选项配置](https://umijs.org/docs/max/i18n#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%80%89%E9%A1%B9%E9%85%8D%E7%BD%AE)

**Comment by hyzx86** [comment]
用上了，不错，真香~ 再也不用为这个 打补丁了
