### ISSUE TITLE
ant-design-pro项目中部署后window.g_app._store.dispatch无效

### ISSUE THREAD

**Issue by sp0cket** [umijs/umi#1063]
umi build后把生成的文件丢到nginx下
nginx配置：
```
location / {
     try_files $uri /index.html;
}
```
当触发401错误时`request.js`中调用的`window.g_app._store.dispatch`没有任何反应，控制台也没有报错信息
但是在本地`umi dev`时正常

**Comment by xiaohuoni** [comment]
build之后，用serve本地启动试看看。

**Comment by xiaohuoni** [comment]
我试了一下ant-design-pro，好像没有这个问题

**Comment by sp0cket** [comment]
本地serve也没触发dispatch，只有个401的提示，直接下载的ant-design-pro的2.0 release

**Comment by sp0cket** [comment]
额 我打开dashboard返回401 就只有右上角弹框  在`login.js`中的logout第一行加了log也没触发过打印   但是`umi dev`都正常触发

**Comment by sp0cket** [comment]
我改成任何异常调用也是  完全不触发  和我本地环境有关么？
我这边环境：
```
>npm -v
6.2.0
>umi -v
2.0.2
```

**Comment by xiaohuoni** [comment]
你用pro，build之后没有数据的。

**Comment by sp0cket** [comment]
`你用pro，build之后没有数据的。`
什么意思？  我改了baseurl，而且即使没有数据返回的是404  也会进catch error的

**Comment by xiaohuoni** [comment]
你再看看，反正这个没什么问题

**Comment by zsio** [comment]
@sp0cket 请问问题解决了吗

**Comment by sp0cket** [comment]
@zsio 解决了  把Login的model提到全局的

**Comment by sp0cket** [comment]
https://github.com/ant-design/ant-design-pro/issues/2225
