### ISSUE TITLE
[Task] 优化 max 性能

### ISSUE THREAD

**Issue by fz6m** [umijs/umi#10645]
### 问题

经反馈，`max g` 运行需要 8s （#10642）

#### 环境

antd-pro + max （包含 `umi-presets-pro`）

#### 原因

和配置文件关系不大，主要在于模块预读取的瓶颈。

#### Umi

 - [x] umi 仓库性能模块导入优化 #10646

优化前：

![screenshot_2023-03-01_14-41-33](https://user-images.githubusercontent.com/59400654/222063868-aa0ac967-3e74-469d-8488-df29d6008bbb.png)

优化后：

![screenshot_2023-03-01_14-27-34](https://user-images.githubusercontent.com/59400654/222063914-361b8ba0-ed63-48b2-9bd4-b32b0b47deaa.png)

#### openapi

需要 lazy import prettier 的导入，代码见 [`src/util.ts`](https://github.com/chenshuai2144/openapi2typescript/blob/5b51c674f5fc01d69db7cb39f4cd8f362c2a7395/src/util.ts#L7) ：

```diff
- import * as prettier from 'prettier';
+ require('prettier') // 在使用时再导入
```

 - [x] [openapi](https://github.com/chenshuai2144/openapi2typescript) 优化 。cc @chenshuai2144 （ PR 见 https://github.com/chenshuai2144/openapi2typescript/pull/98 ）
 - [x] openapi 发版后，`max-plugin-openapi` 与 `umi-presets-pro` 提升版本发版，否则对于升级用户他们的底层 `@umijs/openapi` 版本不会变化，cc @chenshuai2144

#### umi-presets-pro

 - [x] umi 新版本发布后 > alita 升级 umi 依赖版本 > alita 发版后 > umi-presets-pro 升级 alita 依赖发新版本，否则升级用户他们的底层 alita 版本不会变化。cc @chenshuai2144 、@xiaohuoni ，PR 见 https://github.com/umijs/umi-presets-pro/pull/12

#### alita

 - [x] 待 umi 发版后，[alita](https://github.com/alitajs/alita) 依赖的 umi 版本升级即可，~~建议不要锁~~，cc @xiaohuoni （ PR 见 https://github.com/alitajs/alita/pull/520 ）

### 来源

Discussed in https://github.com/umijs/umi/discussions/10642

<div type='discussions-op-text'>

<sup>Originally posted by **doornot** March  1, 2023</sup>

**Comment by xiaohuoni** [comment]
> umi 新版本发布后 > alita 升级 umi 依赖版本 > alita 发版后 > umi-presets-pro 升级 alita 依赖发新版本，否则升级用户他们的底层 alita 版本不会变化。

用户直接重新安装，应该就会装到最新版本，因为 umi-presets-pro 里面没锁版本

> [alita](https://github.com/alitajs/alita) 依赖的 umi 版本升级即可，建议不要锁

umi 发版本之后，需要确认内部的组件是否有影响，确认没影响之后，才会统一升 umi。所以依旧是锁的

**Comment by fz6m** [comment]
> 用户直接重新安装，应该就会装到最新版本，因为 umi-presets-pro 里面没锁版本

由于间接依赖的大版本号仍然符合原来的设定，所以 pnpm 这种包管理器是不会提升仍符合 semver 范围的间接依赖版本的，故升级底层依赖一定要严格提升顶层依赖内的版本，这也是 changesets 要解的问题（会严格提升上游依赖内的版本号，保证用户升级时底层依赖也会升级），同时在 umi 里现在用了 `workspace:*` + `pnpm publish` 也可以彻底解这个问题了。

所以这次的性能提升，还是跟进完整个链路的版本提升，这样好。

> umi 发版本之后，需要确认内部的组件是否有影响，确认没影响之后，才会统一升 umi。所以依旧是锁的

合理，没有意见。

**Comment by xiaohuoni** [comment]
等待最后一步 umi-presets-pro 发版

**Comment by xiaohuoni** [comment]
https://www.npmjs.com/package/umi-presets-pro/v/2.0.3 已发版
