### ISSUE TITLE
[Bug] clickToComponent 报错

### ISSUE THREAD

**Issue by WongYuYe** [umijs/umi#10649]
## Mini Showcase Repository(REQUIRED)

Option+Click 部分组件报错
![image](https://user-images.githubusercontent.com/23697313/222066225-81c6d3d7-11ee-4c10-8461-e68212733552.png)
![image](https://user-images.githubusercontent.com/23697313/222066271-47894710-a797-4a32-8984-2e42826d90f1.png)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0.51
- **Node Version**: v16.14.2
- **Platform**: mac os

**Comment by fz6m** [comment]
目前只支持 vscode 。
