### ISSUE TITLE
[Bug] SelectLang render 为空

### ISSUE THREAD

**Issue by giscafer** [umijs/umi#10650]
## What happens?

![image](https://user-images.githubusercontent.com/8676711/222099221-d6c221f0-26c0-4dd8-b287-0be4afcacc58.png)

![image](https://user-images.githubusercontent.com/8676711/222099358-db00653d-0fca-4c36-9e35-58c918379ff0.png)

## How To Reproduce

配置locale，然后执行` yarn dev`，查看生成的 plugin-locale 代码

## Context

- **Umi Version**: Umi v4.0.15
- **Node Version**: 16.18.0
- **Platform**: Windows10

**Comment by fz6m** [comment]
最小复现给一个。

**Comment by giscafer** [comment]
自己实现了。没开启locale插件

**Comment by lihao6666** [comment]
同样遇到这个问题

**Comment by fz6m** [comment]
这种情况一般是没识别到语言文件，注意 `locales/*` 下面的语言文件完整性和语法规范性，可以参考 [ant-pro](https://github.com/ant-design/ant-design-pro) 里的。
