### ISSUE TITLE
打包后运行缺少publicPath

### ISSUE THREAD

**Issue by zly-smile** [umijs/umi#10651]
## 打包后的文件除了umi.js 有publicPath，其他文件无法访问

例如说我们打包后要把前端代码传到oss上，oss会有一个链接，服务器要渲染oss的这个链接地址，就需要用到把publicPath替换成oss地址，打包后的文件 有umi.js 和其他async.js，index.html 引用了umi.js，访问时报错

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/29395810/222109373-2f6462f8-2041-47df-a662-34fe2974312f.png">

## Context

- **Umi Version**:  4.0.53
- **Node Version**:  16.15.0
- **Platform**: c

**Comment by hongfaqiu** [comment]
这样配置试试
```ts
  history: {
    type: 'hash'
  },
  publicPath: './',
```
不要配置runtimePublicPath，或者设置为false
