### ISSUE TITLE
[Bug] umi4集成@arcgis/core，如果引入css文件后，地图无法加载

### ISSUE THREAD

**Issue by 18310880751** [umijs/umi#10676]
## What happens?
在umi4中集成@arcgis/core，不引入css文件，地图能加载，但是地图的控件样式有问题，引入css文件后地图加载没反应了,umi3里一切正常。最近升级ant design pro 6时发现的问题。

在umi4中集成@arcgis/core，不引入css文件，地图能加载，但是地图的控件样式有问题，引入css文件后地图加载没反应了
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/18310880751/umigis

`import '@arcgis/core/assets/esri/themes/light/main.css';
import Map from '@arcgis/core/Map';
import SceneView from '@arcgis/core/views/SceneView';
import { useEffect } from 'react';

const Test: React.FC = () => {
  useEffect(() => {
    const map = new Map({
      basemap: "osm",
    });
    const view = new SceneView({
      container: "map3DContainer",
      map,
      zoom: 13,
      center: [118.75069, 31.94153]
    })
  })
  return (
    <div id="map3DContainer" style={{ width: '100%', height: '100%', border: '1px' }} />
  );
};

export default Test;`

这段代码，如果将第一行的css注释上，地图能加载，但是打开注释，地图就加载不了了。在umi3上都正常，umi4有这种情况

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:4.0.55
- **Node Version**:v16.16.0
- **Platform**:
- "@arcgis/core": "^4.26.4",

**Comment by fz6m** [comment]
需要最小复现。

**Comment by 18310880751** [comment]
> 仓库是空的，需要最小复现。

仓库提交上代码了，麻烦查看一下。pages/index.tsx文件里第一行css引入如果注释掉，地图是可以加载的

**Comment by fz6m** [comment]
样式是成功引入生效的，只不过你引入这个主题他不能用 `100%` 这种长度单位，因为父元素没有元素撑开，100% 其实是 0 ，你换个绝对单位或者 vw / vh ，或者放在撑开的父元素里就可以了。
