### ISSUE TITLE
在app.ts中使用getDvaApp的问题

### ISSUE THREAD

**Issue by G-02** [umijs/umi#10680]
## What happens?
render函数中使用getDvaApp

目前需求是，在render中使用接口请求，存储在dva中，接口请求成功后，调用getDvaApp有时为null，有时找得到，目前稳定浮现的场景是接口响应快时，可以获取到getDvaApp，接口响应慢（通过控制台调节网络速度），打印getDvaApp为null
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce
export function render(oldRender: any) {
  const app1 = getDvaApp();
  console.log(app1); // null
  getServerMenus().then((res) => {
    if (res.code === RequestCode.Success) {
      const app = getDvaApp();
      console.log('app', app); // null
      setTimeout(() => {
        app?._store.dispatch({
          type: 'global/saveState',
          payload: {
            menuData: res.data,
          },
        });
      }, 10);
    }
  });
  oldRender();
}
**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
dva 不维护不建议用了，换 [valtio](https://umijs.org/docs/max/valtio) 或者 [jotai](https://github.com/pmndrs/jotai) 吧。

**Comment by G-02** [comment]
umi后续会集成这两个库吗
