### ISSUE TITLE
[Bug] 添加全局加载组件报错

### ISSUE THREAD

**Issue by selye** [umijs/umi#10684]
## What happens?

umi4中使用全局加载组件运行时报错

编译时生成的.umi文件中import路径为 import Loading from 'D:\test\1\4.0.54\src\loading.tsx';  
会提示报错： Can not resolve dependence : 'D:        est.0.54srcloading.tsx', please install it
目测是转义字符出错，导致引入组件报错

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce
**steps1**: 在src目录下新建loading.tsx文件  
**steps2**: 执行命令 yarn start 报错

## Context

- **Umi Version**: 4.0.55
- **Node Version**: v16.13.0
- **Platform**: windows

**Comment by fz6m** [comment]
已在 #10669 修复，cc @sorrycc  可以发一个新版本吗，这个问题导致 win 上的 `loading.tsx` 不可用，已经有两个人反馈了。
