### ISSUE TITLE
配置项，hash可以默认为true吗？

### ISSUE THREAD

**Issue by zhangxinyong12** [umijs/umi#10697]
发布后用户反馈还是老页面，存在缓存，检查代码和查阅文档后发现，hash默认为false。不理解为啥默认是false。
nginx配置通常是这样的：
 location / {
            try_files $uri $uri/ /index.html =404;
            expires 0;
            if ( $uri ~* \.(css|jpg|png|gif|ico|js|woff|woff2|ttf|svg|json)$ ) {
                expires max;
            }
            if ($uri ~* \.(html)$) {
                add_header Cache-Control    "private, no-store, no-cache, must-revalidate, proxy-revalidate";
            }
        }

**Comment by fz6m** [comment]
可以自己封一个插件修改下默认配置，选项默认值改了就 breaking change 了

**Comment by zhangxinyong12** [comment]
> 可以自己封装一个插件修改下默认配置，选择默认值修改了就breaking change了

可以增加个提示吗？当监测到是false的时候。用户打包的时候，打印个提示信息，要不然只能经历一次缓存事故才知道。比如我就是这样。
