### ISSUE TITLE
[Bug] http proxy转发的Http头中origin参数问题

### ISSUE THREAD

**Issue by dayongxie** [umijs/umi#10690]
## What happens?

我将代理转发到了django后台， 配置如下
```
proxy: {
    target: "http://127.0.0.1:8000",
    changeOrigin: true
}
```
post请求会将origin改为“http://127.0.0.1:8000/"
origin多了个符号斜杠'/', 导致django的跨域判断host和origin不一致

正常的Origin应该是不带/的吧

**Comment by fz6m** [comment]
给最小复现看看。

**Comment by dayongxie** [comment]
我已经另开了issue #10692 
提交了pr #10699
