### ISSUE TITLE
[Feature Request] plugin-locale should extraLocales(antd, momentLocale) when addLocale

### ISSUE THREAD

**Issue by rozbo** [umijs/umi#10694]
## Background
当需要合并服务端的字典时，手动又调用了 addLocale.
而现在的逻辑是
https://github.com/umijs/umi/blob/55d6adf4b9d8949ca507a8d329920dedbf70ec25/packages/plugins/libs/locale/localeExports.tpl#L89-L100
message可以合并，但是像antd这样却不可以合并，那这样就非常不方便了。
## Proposal
希望可以考虑像message一样，考虑到合并的可能。

**Comment by rozbo** [comment]
附上目前的解决方案(邪道)：
app.tsx
```ts
export function i18nProvider(container, opts) {
    return <AbpLocale>{container}</AbpLocale>
}
```
abpLocale.tsx
```ts
import {localeInfo} from "@@/plugin-locale/localeExports";

export default ({child})=>{
    localeInfo[langName].message = Object.assign({}, localeInfo[langName].messages, realMap)
    return <>{child}</>
}
```

**Comment by xiaohuoni** [comment]
antd 需要合并什么内容？不是很理解问题，能不能给个实例说明一下，你现在遇到的问题？

**Comment by rozbo** [comment]
举一个栗子，当服务端也存在一个 zh-CN的语言配置，但是如果此时你调用了addLocale，但是服务端没有momentLocale， antd，这些额外配置，此时就会丢失这些配置。

我觉可能像message一样，做个合并比较好。

**Comment by rozbo** [comment]
简单点来说，就是当你
```
addLocale('zh-CN', messagesFormServer, {})
```
message可以和本地的合并，但是第三个参数extraLocales不会被合并，而是直接置空了。。
这个显然不太合理吧。。

**Comment by xiaohuoni** [comment]
@rozbo 是我没理解你说的内容吗？

> 第三个参数extraLocales不会被合并，而是直接置空了

为什么要置空？

给个代码和说明你想要的效果吧？

**Comment by rozbo** [comment]
> 为什么要置空？


> 一般情况我们不会调整 antd 内的翻译文案，如需调整，可以自己注意下，这部分文案有限，写死或者拉取到项目里固定也可以。

@xiaohuoni @fz6m 不知道是不是我没表达清楚。。。😂
我也不想置空啊，我也不想修改啊。。。而是插件现在逻辑就要求必须完整传递这些值，不然给置空了。
你们看这个代码

```ts
 const { momentLocale, antd } = extraLocales || {}; 
```
如果不传，直接就是空，如果传了就用你传的， 这就要求必须让用户去传这个antd的配置，但是其一用户怎么获取到这个是一个问题，二是用户一般也没有修改这个的场景，所以这里让用户传明显就是个负担，我觉得插件这里应该合并下原有的 antd和momentLocale比较合理

**Comment by xiaohuoni** [comment]
你的意思是 使用了 addLocale 之后，原有的 momentLocale 和 antd 配置丢失了是吧？

**Comment by rozbo** [comment]
对的，还是你简练
准确的说，是用户不明确传递，这些值就会丢失
