### ISSUE TITLE
[Bug] useModel 提示 Module '"umi"' has no exported member 'useModel'.

### ISSUE THREAD

**Issue by xiaoliu1990** [umijs/umi#10709]
版本："@umijs/max": "^4.0.52",
.umirc.ts 配置
export default defineConfig({
  title: '加载中...',
  alias: {
    '@': resolve(__dirname, 'src'),
  },
  hash: true,
  history: {
    type: 'hash',
  },
  icons: { autoInstall: {} },
  outputPath: buildPath,
  publicPath:  '/',
  routes:[],
})
在目录
src/pages/login/index.ts里面引入
import {  useModel } from 'umi'
报错：Module '"umi"' has no exported member 'useModel'

![YQY~~6}2P@}X164O3OAE3VK](https://user-images.githubusercontent.com/17424034/223910534-6e39e85d-c0f6-4b35-b561-544da70c53b5.png)

**Comment by fz6m** [comment]
max 项目要从 `@umijs/max` 引入。
