### ISSUE TITLE
useModel 使用 useIntl报错

### ISSUE THREAD

**Issue by QDyanbing** [umijs/umi#10702]
useModel 使用 useIntl报错

复现仓库如下：
https://github.com/QDyanbing/useIntl

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/66234749/223610338-eac80932-ee91-4bd8-84ed-ce98c02a5846.png">

**Comment by a1352723557** [comment]
希望是最小化的改动，如果使用valtio的话 我该怎么最小化改造我的项目，把所有useModel里需要国际化的文案改造成支持的样子？ @fz6m

**Comment by QDyanbing** [comment]
项目比较大了不太好切换数据流；影响比较大

**Comment by fz6m** [comment]
i18n 的文案应该直接在组件里用 i18n 的 hooks 获取，不应该放到 useModel 里，useModel 是一个数据流，不应该存文本，如果有少量国际化文本可以自己考虑放到全局数据流里，再从全局数据里取。
