### ISSUE TITLE
模块联邦相关配置（mf），在生产环境报错

### ISSUE THREAD

**Issue by lisleyang** [umijs/umi#10704]
## What happens?

umi4，下载官方仓库examples文件夹下的 mf-remote 和 mf-host 文件夹；

分别`npm run dev`，然后运行，没有任何问题，可以工作；

然而运行 `npm run build`, 然后使用http-server分别起服务以后，会报错，mf-host提示`Shared module is not available for eager consumption`， mf-remote能正常获取到。

这个我理解是加载顺序的问题，但已经按照官方仓库配置了eager，按道理不应该再次出现。

## Mini Showcase Repository(REQUIRED)

参照官方仓库/examples下的mf-remote和mf-host即可复现。

我自己也建了一个仓库

https://github.com/lisleyang/umi-mf-issue

## How To Reproduce

cd mf-remote && npm run build
cd mf-remote/dist && http-server . -p 9000

cd mf-host && npm run build
cd mf-host/dist && http-server .

此时会报错

`Shared module is not available for eager consumption`

## Context

- **Umi Version**: 4
- **Node Version**: 14.20
- **Platform**: mac

**Comment by txp1035** [comment]
端口不对，你试试运行`http-server -p=9000`

**Comment by txp1035** [comment]
> ## What happens?
> umi4，下载官方仓库examples文件夹下的 mf-remote 和 mf-host 文件夹；
> 
> 分别`npm run dev`，然后运行，没有任何问题，可以工作；
> 
> 然而运行 `npm run build`, 然后使用http-server分别起服务以后，会报错，mf-host提示`Shared module is not available for eager consumption`， mf-remote能正常获取到。
> 
> 这个我理解是加载顺序的问题，但已经按照官方仓库配置了eager，按道理不应该再次出现。
> 
> ## Mini Showcase Repository(REQUIRED)
> 参照官方仓库/examples下的mf-remote和mf-host即可复现。
> 
> 我自己也建了一个仓库
> 
> https://github.com/lisleyang/umi-mf-issue
> 
> ## How To Reproduce
> cd mf-remote && npm run build cd mf-remote/dist && http-server . -p 9000
> 
> cd mf-host && npm run build cd mf-host/dist && http-server .
> 
> 此时会报错
> 
> `Shared module is not available for eager consumption`
> 
> ## Context
> * **Umi Version**: 4
> * **Node Version**: 14.20
> * **Platform**: mac

端口不对，你试试运行http-server -p=9000。也可以去代码搜索改端口设置

**Comment by txp1035** [comment]
![image](https://user-images.githubusercontent.com/9554297/223683264-beb11251-6170-437d-98e5-3671de35d06f.png)

**Comment by txp1035** [comment]
![image](https://user-images.githubusercontent.com/9554297/223683319-6f46c49f-fd59-4c5d-aba0-90091b8fffa1.png)

**Comment by txp1035** [comment]
![image](https://user-images.githubusercontent.com/9554297/223683359-ccf6afbc-00fd-49c3-9054-e30775b714b3.png)

**Comment by txp1035** [comment]
![image](https://user-images.githubusercontent.com/9554297/223683662-b4c01492-f7ba-4184-bcd6-33aa2565ce42.png)

**Comment by lisleyang** [comment]
@txp1035 大佬，应该不是端口的问题，remote.js是能拿到的。

您能帮忙跟进一下这个问题么？我们在dev环境已经构建了一些组件，准备上线发现了这个问题。

需要的话您可以私聊我

**Comment by txp1035** [comment]
> @txp1035 大佬，应该不是端口的问题，remote.js是能拿到的。
> 
> 您能帮忙跟进一下这个问题么？我们在dev环境已经构建了一些组件，准备上线发现了这个问题。
> 
> 需要的话您可以私聊我

![image](https://user-images.githubusercontent.com/9554297/223699738-2c7e9ca6-35ca-448a-bab9-77441f3ee617.png)
在看，你的错误码和我这个一样不

**Comment by lisleyang** [comment]
@txp1035 一模一样，感谢🙏

**Comment by txp1035** [comment]
> @txp1035 一模一样，感谢🙏

我看了下是加载react的时候出了错误，关掉share可以运行了，具体原因还在查，这块不是我负责的，我需要时间看下代码
![image](https://user-images.githubusercontent.com/9554297/223720516-c3b20726-ef7d-4139-b3d9-6552ac177941.png)

**Comment by txp1035** [comment]
> @txp1035 一模一样，感谢🙏

你们项目关掉共享模块会不会很慢？关掉mf-host的共享模块可以正常运行
![image](https://user-images.githubusercontent.com/9554297/223723497-43e6a9c8-21c1-47f1-b62c-fb3746c8e819.png)

**Comment by fz6m** [comment]
有空可以看下这个问题 @stormslowly  🌹

**Comment by lisleyang** [comment]
@txp1035 @stormslowly 两位大佬，这个bug现在有进度了么？我理解，这个解决不了，umi的整个mf相关功能是无法使用的。

我们团队这边，在npm run dev的时候开发了几周的组件，现在部署不了，很崩溃。

**Comment by stormslowly** [comment]
你关掉 shared 中 eager 的配置 试试看

**Comment by lisleyang** [comment]
@stormslowly 感谢，我看webpack的文档也是建议这种思路，而不是绑定eager。
现在eager有问题，但是确实没在umi的文档找到怎么异步起动。

**Comment by stormslowly** [comment]
> @stormslowly 感谢，我看webpack的文档也是建议这种思路，而不是绑定eager。 现在eager有问题，但是确实没在umi的文档找到怎么异步起动。

这个 eager 不是 shared 的 eager 的意思，

你先这么配置下

在 host 端 新建 .umirc.prod.ts   or config/config.prod.ts  
内容 

```ts
export {
mfsu:false
}
```
重新构建 host 端，然后试试

**Comment by lisleyang** [comment]
@stormslowly 

试了下确实可以。

那我是不是可以这样，根据环境变量，来区分mfsu的配置。如果生产环境的话就关闭mfsu，这样不会影响mf的功能。

这样的话对构建结果会不会有其他影响？没有的话我们就先这么救急，后面您在慢慢看下。

**Comment by stormslowly** [comment]
你就这么配置就行   umi 会根据环境变量来合并对应的环境的配置文件，如果你在 dev 阶段  .prod.ts 是不生效的 
`*.prod.ts` 文件提交到代码库即可。

**Comment by lisleyang** [comment]
明白，那我关了

**Comment by fz6m** [comment]
感觉是一个坑，建议在源码根本解决掉：https://github.com/umijs/umi/pull/10721#issuecomment-1463761121

**Comment by liangchaofei** [comment]
> 

方便加个联系方式吗

**Comment by liangchaofei** [comment]
> 明白，那我关了

方便加个联系方式吗
