### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by sanfire86626** [umijs/umi#10706]
## What happens?
import  {connect} from 'umi';

导入 connect报错
## Mini Showcase Repository(REQUIRED)
<img width="908" alt="image" src="https://user-images.githubusercontent.com/18204322/223722951-3526b611-8c80-4ffa-9df0-b4ba447eae93.png">

**Comment by fz6m** [comment]
umi 默认没有集成 dva ，需要从 `@umijs/max` 导入（如果你用了 max ）。

**Comment by sanfire86626** [comment]
import {connect} from 'umi'import {connect} from ***@***.***/max'
都不行啊，麻烦解决下吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月8日(星期三) 晚上9:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [umijs/umi] [Bug] say something (Issue #10706)





 
umi 默认没有集成 dva ，需要从 @umijs/max 导入（如果你用了 max ）。
