### ISSUE TITLE
umi2.x build之后的hash值可以指定吗

### ISSUE THREAD

**Issue by rongj** [umijs/umi#1070]
打包之后的js和css文件hash值都不同，还有`p__application__management__models__managementAlarm.js.0b32286a.async.js`这种形式，怎么指定版本号或者改成[name].[ext]?v=2.0这样的形式呢

**Comment by sorrycc** [comment]
hash 值是根据文件内容自动生成的，不能指定。

**Comment by ChaseChan** [comment]
@sorrycc 那请问怎么让打包后的umi.js可以有hash值呢？
