### ISSUE TITLE
引入 useModel 提示 Module '"umi"' has no exported member 'useModel'.

### ISSUE THREAD

**Issue by xiaoliu1990** [umijs/umi#10710]
版本："@umijs/max": "^4.0.52",
.umirc.ts 配置
export default defineConfig({
title: '加载中...',
alias: {
'@': resolve(__dirname, 'src'),
},
hash: true,
history: {
type: 'hash',
},
icons: { autoInstall: {} },
outputPath: buildPath,
publicPath: '/',
routes:[],
})
在目录
src/pages/login/index.ts里面引入
import { useModel } from 'umi'
报错：Module '"umi"' has no exported member 'useModel'
![YQY~~6}2P@}X164O3OAE3VK](https://user-images.githubusercontent.com/17424034/223910788-4d6c06d2-726c-46d3-b1a1-92231c29932d.png)

**Comment by Zhulan520** [comment]
.umirc.ts文件中
export default {
  plugins: ["@umijs/plugins/dist/model"],
  model: {},
};
