### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by 8708798** [umijs/umi#10727]
<img width="275" alt="image" src="https://user-images.githubusercontent.com/42125669/224471878-1a99d5b1-ae4a-4820-bd2d-3b23d2beb881.png">
设置了none，代码在start的时候依然会压缩，这边如何关闭代码压缩

**Comment by fz6m** [comment]
开发是不会有压缩的，构建时通过 [COMPRESS](https://umijs.org/docs/guides/env-variables#compress) 关闭压缩。
