### ISSUE TITLE
 用umi4 开启https一直报错 Error: [HTTPS] mkcert not found

### ISSUE THREAD

**Issue by pxim** [umijs/umi#10732]
用umi4 开启https一直报错 Error: [HTTPS] mkcert not found
可是我明明已经安装了，-v版本，where mkcert 都有结果
![FKCCCNJGSCT}Y{NH8N59T(K](https://user-images.githubusercontent.com/5111701/224599903-679c4ba0-15cb-47ab-9b09-284ac4ff2634.png)
全局和项目都安装mkcert了
![image](https://user-images.githubusercontent.com/5111701/224600466-0c8da332-1f68-49e4-ba60-25bc64205a75.png)

报错信息：
![image](https://user-images.githubusercontent.com/5111701/224600670-104c3e3c-a725-449b-a870-32dd47f6800f.png)

**Comment by robint-liu** [comment]
删除 npm 安装的 mkcert，然后按照[官方安装教程提示](https://github.com/FiloSottile/mkcert?tab=readme-ov-file#installation)安装，然后重新执行 umi 命令即可
