### ISSUE TITLE
登录页面（无法再浏览器上进行debugger调试）

### ISSUE THREAD

**Issue by FTW-001** [umijs/umi#10737]
在Pages->User->Login->index.tsx   在点击登录按钮时进行debugger，在浏览器调试的时候遇到下面的问题，我再拉取最新代码后没有修改过任何配置
![image](https://user-images.githubusercontent.com/61999790/224663002-1fd91d97-248a-4765-afcc-5949cd898fcc.png)
![image](https://user-images.githubusercontent.com/61999790/224665708-fc848e53-1ba3-49c5-b1ea-eb5a4b0db25f.png)

**Comment by fz6m** [comment]
需要给一个视频演示操作，帮助排查问题。
