### ISSUE TITLE
[Feature Request] simple app如何像dva一样快速配置国际化

### ISSUE THREAD

**Issue by YBY2020** [umijs/umi#10735]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by fz6m** [comment]
dva 不维护了，不推荐使用。

国际使用 `@umijs/plugins/dist/locale` 插件，参考 [i18n](https://umijs.org/docs/max/i18n) 。

全局存储推荐使用 [valtio](https://umijs.org/docs/max/valtio) 或者 [jotai](https://github.com/pmndrs/jotai) 。

**Comment by YBY2020** [comment]
> dva 不维护了，不推荐使用。
> 
> 国际使用 `@umijs/plugins/dist/locale` 插件，参考 [i18n](https://umijs.org/docs/max/i18n) 。
> 
> 全局存储推荐使用 [valtio](https://umijs.org/docs/max/valtio) 或者 [jotai](https://github.com/pmndrs/jotai) 。

抱歉是我没有表达清楚问题，我的意思是，如果在创建项目初始选择了`simple app`模式，那么此时umi是没有内置国际化插件的，如您给的参考，是umi/max的内容，而如果我想新增此配置，以dva为例，使用`yarn umi g dva`即可一键配置，但国际化我没有找到类似这样的一键配置

**Comment by fz6m** [comment]
See https://umijs.org/docs/guides/use-plugins

```ts
// .umirc.ts

export default {
  plugins: ['@umijs/plugins/dist/locale'],
  locale: {}
}
```

umi 配置插件就是 max 一样的功能，max 是由一个个插件组成的。
