### ISSUE TITLE
[Bug] 用umi4 开启https一直报错 Error: [HTTPS] mkcert not found

### ISSUE THREAD

**Issue by pxim** [umijs/umi#10731]
## What happens?

用umi4 开启https一直报错 Error: [HTTPS] mkcert not found
可是我明明已经安装了，-v版本，where mkcert 都有结果
![FKCCCNJGSCT}Y{NH8N59T(K](https://user-images.githubusercontent.com/5111701/224599903-679c4ba0-15cb-47ab-9b09-284ac4ff2634.png)
全局和项目都安装mkcert了
![image](https://user-images.githubusercontent.com/5111701/224600466-0c8da332-1f68-49e4-ba60-25bc64205a75.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
[mkcert](https://github.com/FiloSottile/mkcert) 是一个 Go 的工具，要单独安装，可以帮你便捷开启 https 。

**Comment by pxim** [comment]
umi4里应该这样配置，
![image](https://user-images.githubusercontent.com/5111701/229661134-1deb37f4-82c7-44a4-8a66-88f1dfa57ca6.png)

是文档不清晰

**Comment by robint-liu** [comment]
删除 npm 安装的 mkcert，然后按照官方安装教程提示安装，然后重新执行 umi 命令即可
