### ISSUE TITLE
[Feature Request] Umi 的 Antd 插件需升级适配 Antd 5

### ISSUE THREAD

**Issue by mysteryven** [umijs/umi#10745]
## Background

Umi Max 项目默认安装 Antd 5 后，原有的一些配置无效或导致命令行报错。下面是已经发现的。

[`dark`](https://umijs.org/docs/max/antd#dark) 、[`compact`](https://umijs.org/docs/max/antd#compact) 开启会报错：

```bash
fatal - Error: Cannot find module 'antd/dist/theme'
```

[`import`](https://umijs.org/docs/max/antd#import) 无效：

```bash
fatal - please change config antd.import to false, then start server again
```

## Proposal

1. 增加对 Antd 5 的适配
2. 按照提示，对于 `import` 是否可以考虑删除了

**Comment by fz6m** [comment]
antd v5 不用配这俩选项就行。

**Comment by Wxh16144** [comment]
是否可以考虑把 `dark` 和 `compact` 也兼容到 antd5？或者我们在 umijs antd plugin 的文档中补充说明一下？

**Comment by fz6m** [comment]
最新版本 `4.0.76` 已经支持了 antd 5 的 `dark` 和 `compact` 选项。

当开启了该选项后，会自动给 antd 5 config provider 添加对应的主题算法，这要求必须同时开启 `configProvider` 选项才能生效：

```ts
  antd: {
    // compact: true,
    dark: true,
    configProvider: {}
  }
```

若使用了 [`export antd`](https://umijs.org/docs/max/antd#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE) 运行时配置修改主题算法，则以该运行时修改后的结果为准：

```ts
// app.ts

import { theme } from 'antd'

export const antd = (config) => {
  config.theme = {
    // 若修改了运行时配置，则以此处为准，优先级更高
    algorithm: theme.compactAlgorithm 
  }
  return config
}
```

注：

1. 若使用 `umi` + `@umijs/plugins` ，需要确保这两个依赖都升级到最新版本。

2. 若不显示安装 antd ，将使用 umi 内置的 antd 5 版本，该版本可能比较落后，如果你需要使用更新的特性，请显示的安装 antd 5 到 `package.json` 。
