### ISSUE TITLE
[Bug] 使用 Antd 插件时，`appConfig` 没有类型提示

### ISSUE THREAD

**Issue by mysteryven** [umijs/umi#10744]
## What happens?

设置 antd 属性时，[`appConfig`](http://localhost:8001/docs/max/antd#appconfig) 没有类型提示

```ts
 antd: {
    appConfig: {},
    ^^^ The expected type comes from property 'antd' which is declared here on type 'ConfigType'
  }
```

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://stackblitz.com/edit/node-htwcrw?file=.umirc.ts (只是为了不触发关闭问题，这个例子跑不起来，但是代码就是下面这样)

```ts
import { defineConfig } from '@umijs/max';


export default defineConfig({
  antd: {
     // antd <App /> valid for version 5.1.0 or higher, default: undefined
     appConfig: {}
  },
});
```

## How To Reproduce

**Steps to reproduce the behavior:**

查看 `.umirc.ts` 文件

**Expected behavior** 

期待不报错，并且给出 **具体** 的类型提示

## Context

- **Umi Version**: 4.0.57
- **Node Version**: v18.12.1
- **Platform**: macos

**Comment by fz6m** [comment]
这个选项的 PR 刚合进去，还没发版，可以用今天发的临时版本 `4.0.0-canary.20230314.1` 或者等这周四发版后升级。
