### ISSUE TITLE
[Bug] 初始化项目提示Cannot find module 'cross-spawn'!

### ISSUE THREAD

**Issue by Deja-vuuu** [umijs/umi#10758]
## What happens?

执行 pnpm dlx create-umi@latest 提示

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/27748682/225276121-47f96b17-56cf-48fe-8377-485eeb081914.png">

**Comment by fz6m** [comment]
已在最新版本 `4.0.59` 修复。
