### ISSUE TITLE
[Bug] umi3x不能安装antd5x么？

### ISSUE THREAD

**Issue by Deja-vuuu** [umijs/umi#10767]
### 版本
 "antd": "^5.3.1",
  "umi": "^3.3.6"
### 报错
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/27748682/225553640-c173b5e4-073e-4a52-a6c7-4f33ed088e4f.png">

### 复现代码
https://codesandbox.io/p/sandbox/ancient-cdn-int9su?welcome=true&file=%2FREADME.md

**Comment by fz6m** [comment]
自己 fork 一份 antd 插件支持 antd 5 吧，umi 3 不加新功能了。
