### ISSUE TITLE
umi3 升级到 umi4以后 proxy 代理问题

### ISSUE THREAD

**Issue by killdada** [umijs/umi#10760]
![image](https://user-images.githubusercontent.com/16487810/225291276-37f92c95-a1ea-4f10-b6f5-d1ce4ec9648f.png)

原先umi3，配置如上图，disableHostCheck: true ， 本地开发没有跨域问题

升级以后 disableHostCheck参数不存在，不支持，导致请求 403， 如果注释掉下面的headers，get请求正常，post请求403

可以怎么调整配置解决这个问题？

**Comment by fz6m** [comment]
给一个最小复现看看。

**Comment by killdada** [comment]
![image](https://user-images.githubusercontent.com/16487810/225488058-e25c7840-14c9-450d-879d-4e04f3ac5f45.png)

解决了，通过onProxyReq 设置请求头正常了，不知道为啥之前的配置升级以后不生效

**Comment by pxim** [comment]
> ![image](https://user-images.githubusercontent.com/16487810/225488058-e25c7840-14c9-450d-879d-4e04f3ac5f45.png)
> 
> 解决了，通过onProxyReq 设置请求头正常了，不知道为啥之前的配置升级以后不生效

![image](https://github.com/umijs/umi/assets/5111701/7910d6a9-e280-4fd1-b0d4-34d56fb1379b)
umi最新版本，我这样配置也不行，心力交瘁
