### ISSUE TITLE
[Bug] MFSU 开启 mpa 使用 react 报错

### ISSUE THREAD

**Issue by o-oasis** [umijs/umi#10765]
## What happens?
使用umi4的mpa模式，在本地调试时，import react出错，页面提示 
`TypeError: Cannot read properties of null (reading 'useEffect')`

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/o-oasis/umi-mpa-test

## How To Reproduce

**Steps to reproduce the behavior:** 
1. yarn start 后通过 http://localhost:8000/docs.html 访问
2. 页面报错 `TypeError: Cannot read properties of null (reading 'useEffect')`

**Expected behavior** 
1. 可正常渲染页面

## Context

- **Umi Version**: 4.0.55
- **Node Version**: 14.20.0
- **Platform**: windows10

**Comment by fz6m** [comment]
@stormslowly 有时间可以看下这个问题 🌹

**Comment by stormslowly** [comment]
@o-oasis  这下面的方法绕过下

 在 dev 环境关闭 `mpa`  e.g. `map: process.env.NODE_ENV==='dev': false? {}`

mpa 是另外一个套 webpack 我需要看下怎么结合。

**Comment by stormslowly** [comment]
@o-oasis 
更加 mfsu 的方式是这样配置下
```
  mfsu: {
    include: ['react-dom/client']
  }
}
```

原理很简单，现在 app 的项目入口无法触达到 `src/.umi/mpa/docs.tsx` 所以里面的依赖 (react-dom) 没有被 mfsu 分析到
之后我会提个 PR 尝试修复下。

**Comment by sy0209360** [comment]
新建的项目 .umirc.ts 配置 mpa后，docs.html就404了
