### ISSUE TITLE
[Bug] MFSU 无法与 wasm 一起使用

### ISSUE THREAD

**Issue by fz6m** [umijs/umi#10777]
## What happens?

MFSU 无法与 wasm 一起使用

我们需要保证四组用例通过，展开如下：

#### 1. wasm config + mfsu

有配置 wasm ，开启 mfsu ，导入 wasm ，得到 wasm 的 object 方法模块。

> 🔴 现状 ：运行失败

#### 2.  mfsu

没配置 wasm ，开启 mfsu ，导入 wasm ，得到 wasm url

> 🔴 现状 ：运行失败

#### 3. wasm config + `mfsu: false`

配置 wasm ，不开启 mfsu ，导入 wasm ，得到 wasm 的 object 方法模块。

> 🟢 现状 ：运行成功

#### 4.  `mfsu: false`

没配置 wasm ，关闭 mfsu ，导入 wasm ，得到 wasm url

> 🟢 现状 ：运行成功

## Mini Showcase Repository(REQUIRED)

https://github.com/MoeYc/umi-mfsu-bug-when-using-wasm

## How To Reproduce

1. pnpm i
2. pnpm dev

## Context

- **Umi Version**: 4.0.61
- **Node Version**: 18
- **Platform**: macos

## 召唤

辛苦有时间了看下 @stormslowly  🌹

**Comment by stormslowly** [comment]
* case 1.2 在 PR 合并前建议  `mfsu: { exclude: ['包名']}` 绕过

* case 1 : PR 合并后，可以正常使用

* case 2 如果是用 asyncWebAssembly 建议继续使用 exclude 的方式 , 因为项目这侧不知道 mf 导出的是不是一个 async 模块。

* case 2 如果要使用 syncWebAssembly 可以使用 mfsu ，但需要为 mfsu 配置 chainwebpack， 项目 chainwebpack 配不配  syncWebAssembly 都可以
```ts
  mfsu: {
  chainWebpack(config) {
    config.set('experiments', {
      ...config.get('experiments'),
      syncWebAssembly: true
    })
    const REG = /\.wasm$/
    config.module.rule('asset').exclude.add(REG).end();
  },
```

**Comment by stormslowly** [comment]
@xiaohuoni  @xiaohuoni  遇事不决，不要关 MFSU ， 通过 MFSU exclude 和 shared 两板斧绕过。

**Comment by xiaohuoni** [comment]
好难，感觉 mfsu 就 pshu 大佬会用了
