### ISSUE TITLE
[Bug] 开发 插件时，发现api.onStart 会多次执行

### ISSUE THREAD

**Issue by adw2022** [umijs/umi#10773]
## 背景
开发 插件时，发现api.onStart 会多次执行，期望只执行一次

## 复现

```ts
// plugin.ts
import { IApi } from 'umi';

export default (api: IApi) => {
	api.onStart(()=>{
		console.log('Local Plugin');
	});
};

```
![image](https://user-images.githubusercontent.com/111497598/225846168-056576ae-4f6d-4b61-8a5b-64c6ca23d7ae.png)

如上图所示，执行了两次

## 环境

- **Umi Version**: v4.0.61
- **Node Version**: v16.15.0
- **Platform**: MacBook Pro

**Comment by fz6m** [comment]
在 mfsu 里会运行一次，那是另外一个线程，无需关心第二次打印，如果影响视野，可以先关掉 mfsu: false 进行开发。
