### ISSUE TITLE
[Bug] Umi Max: TS 5.0.2 下 .umi/core/pluginConfig.ts 报错

### ISSUE THREAD

**Issue by mashirozx** [umijs/umi#10785]
## What happens?

tsc报错：Function type notation must be parenthesized when used in a union type.

似乎是 ts 5 的问题， @ts-nocheck 无法忽略这个问题：

![image](https://user-images.githubusercontent.com/16148054/226248120-921f9060-7ecf-45ad-9c19-3c6074fa1944.png)

加上个括号就行了：

```ts
externals: { [x: string]: any } | string | ((...args: any[]) => unknown);
```

## Mini Showcase Repository(REQUIRED)

https://github.com/mashirozx/umi-max-ts-error

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

1. npx create-umi@latest
2. 更新到ts 5.0.2
3. max setup
4. pnpm run tsc
5. 你会看到：
<img width="863" alt="image" src="https://user-images.githubusercontent.com/16148054/226248480-c23fefbf-0249-42bd-86fb-2fecf5ebd893.png">

## Context

- **Umi Version**:
```
"dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "^2.0.1",
    "@umijs/max": "^4.0.61",
    "antd": "^5.0.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "husky": "^8.0.1",
    "lint-staged": "^13.0.3",
    "prettier": "^2.7.1",
    "prettier-plugin-organize-imports": "^2",
    "prettier-plugin-packagejson": "^2",
    "typescript": "5.0.2"
  }
```

- **Node Version**: 18/16
- **Platform**: macos

**Comment by mashirozx** [comment]
又试了一下，不是ts 5的问题，是@umijs/max 4.0.61的问题，降级到 4.0.57就好了

**Comment by xierenyuan** [comment]
修复了 待发版解决

**Comment by fz6m** [comment]
可以先用 `4.0.0-canary.20230320.1` 这个今天发的临时版本，本周四发版后升级即可。或者往下降一个版本号。
