### ISSUE TITLE
umirc 配置支持 ant-design Icon 自定义 svg 图标

### ISSUE THREAD

**Issue by amily4555** [umijs/umi#1078]
因为对 chainWebpack 不是很熟悉；

```
const svgRule = config.module.rule('svg');
        svgRule.uses.clear();
        svgRule.test(/\.svg(\?v=\d+\.\d+\.\d+)?$/)
            .include
                .add('src')
                .end()
            .use('babel')
            .loader('babel-loader')
            .end()
            .use('svgr')
            .loader('@svgr/webpack')
            .options({
                babel: false,
                icon: true
            });

```

我做了如上的配置，是希望获得下面的效果

![image](https://user-images.githubusercontent.com/2802841/45490586-16ca3f80-b79a-11e8-881f-f963f0e3f56b.png)

但是我这边获得还是 base64 的东西

![image](https://user-images.githubusercontent.com/2802841/45490619-2ba6d300-b79a-11e8-96e4-7ea1240cb88d.png)

**Comment by RanQiwu** [comment]
urlLoaderExcludes: [/\.svg$/],
  chainWebpack(config) {
    config.module
      .rule('svg')
      .test(/\.svg(\?v=\d+\.\d+\.\d+)?$/)
      .use([
        {
          loader: 'babel-loader',
        },
        {
          loader: '@svgr/webpack',
          options: {
            babel: false,
            icon: true,
          },
        },
      ])
      .loader(require.resolve('@svgr/webpack'));
  },

**Comment by amily4555** [comment]
@RanQiwu 设置通过 3q

格式化下 楼上的代码

```js
urlLoaderExcludes: [/.svg$/],

    chainWebpack(config) {
        config.module
            .rule('svg')
            .test(/.svg(\?v=\d+.\d+.\d+)?$/)
            .use([
                {
                    loader: 'babel-loader'
                },
                {
                    loader: '@svgr/webpack',
                    options: {
                        babel: false,
                        icon: true
                    }
                }
            ])
            .loader(require.resolve('@svgr/webpack'));
    }
```

**Comment by sorrycc** [comment]
svg 为什么要走 babel-loader?

**Comment by mahy50** [comment]
umi 3.0 参考 #4035
