### ISSUE TITLE
className赋予连写的样式不起作用

### ISSUE THREAD

**Issue by cabinhero** [umijs/umi#1079]
我在项目中自定义了custom.css文件然后再组件里import ''./custom.css,按照下列的代码书写样式不起作用：
```html
<div className="zoom-btns button circle raised disable" />
```
(代码要加代码块，不然显示不良好哦！！)
需要其他配置参数吗？我之前在其他项目里不管是引入less或css都可以这样连写操作。

**Comment by xiaohuoni** [comment]
https://www.npmjs.com/package/classnames
你可以使用上面这个模块解决这个问题 非umi问题

**Comment by cabinhero** [comment]
问题出在上面的import ''./custom.css" 不起作用，不是下面连写的问题。但我不知道为啥这样不行，以前的项目里都可以这种方式import进css或less文件,

**Comment by sorrycc** [comment]
因为默认开启了 css modules，需要按照 css modules 的约定使用。
