### ISSUE TITLE
umi/max的useRequest的ready无效

### ISSUE THREAD

**Issue by 13554599576** [umijs/umi#10799]
```javascript
  const [selectDataOpen, setSelectDataOpen] = useState(true);
  const layerGroupsRequest = useRequest(() => Promise.resolve(1), {
    ready: selectDataOpen,
    refreshDeps: [selectDataOpen],
    onSuccess: (data) => {
      console.log(data);
    },
  });
```

selectDataOpen从true变为false的情况下，即使设置了ready，依旧会触发请求。
但是当我不使用umi/max的useRequest，替换为ahooks的useRequest时候，则不会出现此bug。

**Comment by daydayhappychao** [comment]
https://github.com/alibaba/hooks/issues/1780

ahooks useRequest 早期的一个bug，ahooks 中已被修复，想办法升级一下 umi 依赖的 @ahooksjs/useRequest  到最新版的 ahooks 下的 useRequest 即可
