### ISSUE TITLE
关于useRequest的ready无效的问题

### ISSUE THREAD

**Issue by 13554599576** [umijs/umi#10798]
```javascript
  const [selectDataOpen, setSelectDataOpen] = useState(true);
  const layerGroupsRequest = useRequest(() => Promise.resolve(1), {
    ready: selectDataOpen,
    refreshDeps: [selectDataOpen],
    onSuccess: (data) => {
      console.log(data);
    },
  });
```

selectDataOpen从true变为false的情况下，即使设置了ready，依旧会触发请求。

**Comment by xXAvoraXx** [comment]
> 不推荐用 useRequest 了，已经不维护了，现在推荐使用 [`react-query`](https://umijs.org/docs/max/react-query)

Why? useRequest looks very useful. But the react-query you suggested has a more primitive writing style.
