### ISSUE TITLE
试图导入public路径下的图片，报 Can't resolve错误

### ISSUE THREAD

**Issue by heyizhiyuan** [umijs/umi#10800]
在采用@umijs/max 4.0.52开发时，想要导入`public/logo.svg`这个图片，时报错: `Can't resolve './logo.svg' in '/coding/project/csjslib/react-template/antd-pro-template-v5/src/layouts'`.
工程的目录如下图
<img width="277" alt="image" src="https://user-images.githubusercontent.com/39208129/226503612-827efa76-8fe6-4fb7-b235-9d8fd7a063a2.png">
我是在BaseLayout.jsx这个文件中导入的，导入的代码是`import Logo from './logo.svg';`

**Comment by fz6m** [comment]
`public` 下面的是直接拷贝的静态资源，不能导入，只能通过 url 绝对路径使用，如果要导入，把图片放到 src 下面直接导入。

**Comment by sansheng741** [comment]
> `public` 下面的是直接拷贝的静态资源，不能导入，只能通过 url 绝对路径使用，如果要导入，把图片放到 src 下面直接导入。

![image](https://github.com/umijs/umi/assets/38903744/b969c774-9411-4d61-ba93-53fd8b14e7be)
对于这种方式也会报错
![image](https://github.com/umijs/umi/assets/38903744/bb868a45-bc20-483a-84a7-17a56698b6ba)
![image](https://github.com/umijs/umi/assets/38903744/460f91f5-a176-43eb-a728-a38afd18d6de)
