### ISSUE TITLE
在js文件里import引入.glsl文件，但是没有解析成功

### ISSUE THREAD

**Issue by WaterSeeding** [umijs/umi#10803]
我想在umi.js开发框架下的react.js文件里，使用import引入.glsl文件，但是没有注入全部内容，只是解析到以一串字符串

虽然我使用chainWebpack引用了插件['raw-loader', 'glslify-loader']，但还是没有起作用
如图所示：
![image](https://user-images.githubusercontent.com/31184164/226525469-03405c19-de55-4781-b2c7-1261e7efa970.png)
![image](https://user-images.githubusercontent.com/31184164/226525480-f62b7b79-e9ef-486b-bb61-4e1f9e2e1448.png)
![image](https://user-images.githubusercontent.com/31184164/226525499-5de1c39f-50c5-408d-84c5-98fed8ceb0d0.png)
![image](https://user-images.githubusercontent.com/31184164/226525508-69da35a9-3d5d-44c1-a7d3-a2d5df0b2e15.png)
![image](https://user-images.githubusercontent.com/31184164/226525660-106a2906-4c58-4167-9643-236e5db51171.png)
![image](https://user-images.githubusercontent.com/31184164/226525523-5ca69cca-7d0b-42ea-9e28-8d7912ea3f4b.png)

之所以没有使用string形式来添加glsl，是因为.glsl文件代码可以高亮，查看方便

麻烦大佬帮忙看看，这是我的代码
[Earth.zip](https://github.com/umijs/umi/files/11025211/Earth.zip)

**Comment by fz6m** [comment]
See https://github.com/umijs/umi/issues/10802#issuecomment-1477687135

需要最小复现 repo 地址

**Comment by WaterSeeding** [comment]
> ```ts
> // .umirc.ts
> 
> export default {
>   chainWebpack(config) {
> 
>     const GLSL_REG = /\.(glsl|vs|fs)$/;
> 
>     config.module.rule('asset').exclude.add(GLSL_REG).end();
> 
>     config.module
>       .rule('glslify')
>       .test(GLSL_REG)
>       .exclude.add(/node_modules/)
>       .end()
>       .use('raw-loader')
>       .loader('raw-loader')
>       .end()
>       .use('glslify-loader')
>       .loader('glslify-loader')
>       .end();
>   },
> };
> ```
Thank you so much, 大佬
