### ISSUE TITLE
我在js文件里import引入.glsl文件，但是解析失败

### ISSUE THREAD

**Issue by WaterSeeding** [umijs/umi#10802]
我想在umi.js开发框架下的react.js文件里，使用import引入.glsl文件，但是没有注入全部内容，只是解析到以一串字符串

虽然我使用chainWebpack引用了插件['raw-loader', 'glslify-loader']，但还是没有起作用
如图所示：
![image](https://user-images.githubusercontent.com/31184164/226524682-42ec5867-0bd6-4948-8f28-6186e5e2eba5.png)
![image](https://user-images.githubusercontent.com/31184164/226524370-16123dac-a713-4ec9-9770-3f4c7f7714e3.png)
![image](https://user-images.githubusercontent.com/31184164/226524776-04111769-fb0c-4b10-8b0c-398f078223a1.png)
![image](https://user-images.githubusercontent.com/31184164/226524812-2b307f34-c7d9-4585-b349-887810bdccfe.png)
![image](https://user-images.githubusercontent.com/31184164/226524441-ba8c16ed-ca11-493b-9cfe-95ff85abff75.png)

之所以没有使用string形式来添加glsl，是因为.glsl文件代码可以高亮，查看方便
麻烦大佬帮忙看看

**Comment by WaterSeeding** [comment]
还缺少什么信息，我正想提交代码给你们看看

**Comment by WaterSeeding** [comment]
[Earth.zip](https://github.com/umijs/umi/files/11025196/Earth.zip)

**Comment by fz6m** [comment]
什么 umi 版本，需要给一个最小复现 repo 地址，给的压缩包信息不足。

**Comment by WaterSeeding** [comment]
> 什么 umi 版本，需要给一个最小复现 repo 地址，给的压缩包信息不足。

![image](https://user-images.githubusercontent.com/31184164/226786903-c2202007-8abb-4e5d-bcde-ea4e0c12f45b.png)
您好，我使用的是@umijs/fabric的库
