### ISSUE TITLE
请求增加 umi/locale 的ts类型定义文件

### ISSUE THREAD

**Issue by j3r0lin** [umijs/umi#1080]
umi/locale包是根据插件动态生成的，可以在 umi 包中增加 locale.d.ts 来识别类型吗？

**Comment by Jetsly** [comment]
@sorrycc 要么在`umi-plugins-locale`中添加声明，然后在`tsconfig.json`里面添加下面的配置
```
 "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "umi/locale": ["./node_modules/umi-plugins-locale"]
    }
  }
```

**Comment by sorrycc** [comment]
@yutingzhao1991

**Comment by yutingzhao1991** [comment]
我觉得可以在 `https://github.com/DefinitelyTyped/DefinitelyTyped` 这里里面添加 `umi`，umi-plugin-locale 的内容对应添加到 `umi/locale` 中。这个以后可以做为一个 umi 的约定。比如以后如果新增一个 `umi-plugin-i18n` 的插件，那么它应该用别名 `umi/i18n` 来暴露自己的方法，对应也添加 type 到 `umi/i18n` 下面。

**Comment by Jetsly** [comment]
@yutingzhao1991 其实这样就和声明文件写umi包里面一样了，因为没有`@type/umi/locale`的包，只能有
`@type/umi`的包，就会把所以的插件的都写到一个包里面了，
https://github.com/umijs/umi/pull/1036#issuecomment-419839347
变成了这个老问题，所以我当初是写了一个`declare module 'umi/locale'`声明文件

**Comment by yutingzhao1991** [comment]
我理解之前那个讨论里面就是说要建一个声明包把所有插件的声明都放到 `@typpes/umi` 里面吧？应该我们去提一个 PR 到 https://github.com/DefinitelyTyped/DefinitelyTyped ？

我理解错了？

**Comment by sorrycc** [comment]
还是解耦吧，倾向于用 2 楼的方案。插件的声明放 umi 库里有点奇怪，另外还有版本之类的问题。

**Comment by Jetsly** [comment]
@sorrycc 其实如果你们的包名是`@umi/locale`,就可以写一个这个包了，可惜是`umi/locale`
