### ISSUE TITLE
@umijs/lint依赖@stylelint/postcss-css-in-js已被弃用

### ISSUE THREAD

**Issue by usercao** [umijs/umi#10815]
![image](https://user-images.githubusercontent.com/13760476/226824914-910816d6-ef0f-46d9-b504-e7e4bfb5dd44.png)

![image](https://user-images.githubusercontent.com/13760476/226824971-69098a95-eb47-4f44-bad6-b78e0efba18d.png)

This syntax is deprecated. Please refer to the [Stylelint v15 migration guide](https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-15.md).

**Comment by fz6m** [comment]
弃用了没关系的，这是以前 fabric 配置迁移过来的，影响使用吗，给一个不支持的例子看看。

**Comment by usercao** [comment]
不影响使用，就是yarn的时候会报警告
