### ISSUE TITLE
pnpm dlx create-umi@latest 即可复现 增加 pnpm add @ant-design/pro-layout 即可复现

### ISSUE THREAD

**Issue by gaoyangy** [umijs/umi#10818]
pnpm dlx create-umi@latest 即可复现 增加 pnpm add @ant-design/pro-layout 即可复现

_Originally posted by @gaoyangy in https://github.com/umijs/umi/issues/10817#issuecomment-1479133255_

**Comment by fz6m** [comment]
pro-components 是依赖 pro-layout 的，但他没锁，所以你安装最新的 pro-components 就行了，他会自己下载最新的 pro-layout ，如果有更特殊的需求，自己加下 alias 重定向下 pro-layout 。

**Comment by gaoyangy** [comment]
所以 我如果想 plugin-layout 使用 pro-layout 的固定版本, 而不是 pro-components 依赖的版本的话, 就要 alias pro-components 这样 umi 生成的时候就会 应用 pro-layout 的固定版本 是这个意思吗
