### ISSUE TITLE
[Bug] 我在antd项目中编写软件 lint后 umi总是生成一个错误 TS1385

### ISSUE THREAD

**Issue by Cc28256** [umijs/umi#10828]
## What happens?

我在antd项目中编写代码 lint后 umi总是生成一个错误 TS1385
![image](https://user-images.githubusercontent.com/50364169/227155877-e7d72626-5ddc-4e3e-9cd7-89e5550173c9.png)

我可以强行修改添加括号使其不报错
![image](https://user-images.githubusercontent.com/50364169/227155018-fb77837a-9421-4cc8-b599-8ce4b71f4c93.png)

但是npm run start后他还是会自动生成 error
我不知道这是umi的问题还是antd还是我的问题？
虽然他不影响执行 但是lint之后看起来很烦
我该如何解决

## Context

- **Umi Version**:
- umi@4.0.61
- **Node Version**:
- v18.15.0
- **Platform**:
- windows 10

**Comment by fz6m** [comment]
升级下 umi 版本，这个版本有个类型问题，很抱歉。
