### ISSUE TITLE
[Bug] umi4 创建项目typescript为5.0.0版本，.umi moduleResolution:"bundler"导致vscode不识别

### ISSUE THREAD

**Issue by wmy94827** [umijs/umi#10827]
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/25683492/227145409-ab428430-2cd7-4fe7-b257-afc9de8db371.png">
<img width="520" alt="image" src="https://user-images.githubusercontent.com/25683492/227145438-e5568d10-c8ed-41f9-9980-0aee08d62914.png">
[Bug] umi4 创建项目typescript为5.0.0版本，.umi moduleResolution:"bundler"导致vscode不识别

**Comment by fz6m** [comment]
1. 升级 vscode 版本

2. 安装 typescript nightly 插件

3. 手动降级 package.json 里的 ts 到 ^4.0.0

任何一个方法都可以满足你的需求，推荐做 1 。

**Comment by caicai1998** [comment]
> 1. 升级 vscode 版本
> 2. 安装 typescript nightly 插件
> 3. 手动降级 package.json 里的 ts 到 ^4.0.0
> 
> 任何一个方法都可以满足你的需求，推荐做 1 。

![image](https://user-images.githubusercontent.com/64702233/227447539-c920bdc9-643d-47c3-b1ef-02cbc932a159.png)
还是一样的不行啊怎么回事

**Comment by line126** [comment]
> > 1. 升级 vscode 版本
> > 2. 安装 typescript nightly 插件
> > 3. 手动降级 package.json 里的 ts 到 ^4.0.0
> > 
> > 任何一个方法都可以满足你的需求，推荐做 1 。
> 
> ![image](https://user-images.githubusercontent.com/64702233/227447539-c920bdc9-643d-47c3-b1ef-02cbc932a159.png) 还是一样的不行啊怎么回事

![image](https://user-images.githubusercontent.com/43329257/227988936-55c9e3a7-5909-40fd-abd8-1378cc497d16.png)
选择一下 typescript 版本
