### ISSUE TITLE
为什么不支持删除部分国际化语言？

### ISSUE THREAD

**Issue by carveybunt** [umijs/umi#10844]
## Background
国际化语言默认的选项太多，有些并不是我们所需要的。
我尝试注释掉 `/src/.umi/plugin-locale/localeExports.ts` 中不需要的语言，但是重启服务 `yarn start:no-mock` 又自动回复默认。

## Proposal

设置移除部分语言的方法。

## Additional context

至少允许注释部分语言的代码，并且不会被回复默认。

**Comment by fz6m** [comment]
你创建了几种语言的 json 文件就会生成几种，需要提供一个最小复现。

**Comment by carveybunt** [comment]
> 你创建了几种语言的 json 文件就会生成几种，需要提供一个最小复现。

多谢，已解决。直接删除 `/src/locales` 下的 `json` 文件即可。
