### ISSUE TITLE
fetch一个.pag本地文件，怎么获取？挺急的

### ISSUE THREAD

**Issue by bibiehy** [umijs/umi#10841]
win10系统，umi@3.x
想要 fetch 一个 pag_1.pag 文件，不知道怎么获取？项目等着上线，麻烦看到回复一下，谢谢了

项目地址：https://github.com/bibiehy/testPAG.git

![image](https://user-images.githubusercontent.com/35096473/227429835-db07e28d-7e04-4e46-a73a-9fad46baf125.png)

这个文件没加载进来，从大小可以看的出来

![image](https://user-images.githubusercontent.com/35096473/227429957-8473afb1-d9e7-4ce5-8519-68633e923be6.png)

**Comment by xierenyuan** [comment]
放到 public 文件下
![image](https://user-images.githubusercontent.com/7599351/227444832-9ba2fce5-3afb-43a9-a283-cfedb75adfc8.png)

**Comment by bibiehy** [comment]
> 放到 public 文件下 ![image](https://user-images.githubusercontent.com/7599351/227444832-9ba2fce5-3afb-43a9-a283-cfedb75adfc8.png)

这。。确实，感谢！
