### ISSUE TITLE
umi4新建global.less 在umi.ts 没有自动引入

### ISSUE THREAD

**Issue by zhxhdean** [umijs/umi#10854]
version: 4.0.62

新建global.less文件，重新编译后，在 目录.umi/umi.ts 中没有引入global.less文件， 运行的页面中也没有global.less样式

**Comment by fz6m** [comment]
需要放在 `src/global.less` ，如果没有 src 就放在项目根目录下面。如还有问题，需要给一个最小复现。

**Comment by pxim** [comment]
> 需要放在 `src/global.less` ，如果没有 src 就放在项目根目录下面。如还有问题，需要给一个最小复现。

在最新版本里，我建了global.ts，也没有自动引入，global.ts是在src下面的

**Comment by fz6m** [comment]
`src/global.ts` 是全局脚本，如果有问题，需要给一个最小复现帮助排查问题。
