### ISSUE TITLE
多环境配置无效，获取不到环境变量啊

### ISSUE THREAD

**Issue by carveybunt** [umijs/umi#10851]
`@umijs/max` 设置环境变量：

```env
// .env.development
REACT_APP_API_BASEURL = http://xxx.test/api
```
```ts
// config/config.dev.ts
REACT_APP_API_BASEURL: 'http://xxx.test/api';
```

```tsx
console.log('dev', process?.env?.REACT_APP_API_BASEURL);
```
打印结果 `undefined` 。

搞不懂 `umi` 的环境变量设置的机制到底是什么。其他语言直接使用 `.env` 就可以设置了，现在我按照 [umi 环境变量文档](https://umijs.org/docs/guides/env-variables) 设置，也获取不到 `REACT_APP_API_BASEURL`变量。

**Comment by fz6m** [comment]
umi 约定只有 `UMI_APP_` 开头的环境变量会自动加载到项目中，如果你使用了其他的环境变量也想在项目中使用，需要定义到 [define](https://umijs.org/docs/api/config#define) 里。

**Comment by carveybunt** [comment]
> umi 约定只有 `UMI_APP_` 开头的环境变量会自动加载到项目中，如果你使用了其他的环境变量也想在项目中使用，需要定义到 [define](https://umijs.org/docs/api/config#define) 里。

多谢，但是定义在 define 里面了，依旧 undefined 。

```ts
// config.dev.ts
import { defineConfig } from 'umi';

export default defineConfig({
  define: {
    REACT_APP_API_BASEURL: 'http://xxx.test/api',
    UMI_APP_API_BASEURL: 'http://xxx.test/api',
  },
});
```

```tsx
// app.tsx
console.log('REACT_APP_API_BASEURL', process.env.REACT_APP_API_BASEURL);
console.log('UMI_APP_API_BASEURL', process.env.UMI_APP_API_BASEURL);
```
两个变量打印依旧 `undefined`啊。而且也不能直接在 `.env.development` `.env.production`里面直接定义啊。 用 `vue`的时候直接都是在 `.env` 里面定义，多方便。

**Comment by fz6m** [comment]
define 的传参和 webpack Define Plugin 是一样的，需要填完整 `process.env.REACT_APP_API_BASEURL` 。

**Comment by carveybunt** [comment]
不懂，不能像 `VUE` 一样直接获取？

**Comment by kaishuige** [comment]
@fz6m 如何配置 dev跟production 环境配置呢

**Comment by fz6m** [comment]
需要给一个最小复现

**Comment by gitdust** [comment]
> @fz6m 如何配置 dev跟production 环境配置呢

+1，看了半天文档，没找到怎么区分环境配置

**Comment by linwenqiangll** [comment]
https://cloud.tencent.com/developer/article/2206851   终于找到方案了，心累啊

**Comment by Deja-vuuu** [comment]
+1 确实挺复杂的。

**Comment by LunarEdeg** [comment]
> https://cloud.tencent.com/developer/article/2206851 终于找到方案了，心累啊

+1

**Comment by Greaki** [comment]
<img width="841" height="473" alt="Image" src="https://github.com/user-attachments/assets/7f4c24b5-06a6-489c-8a51-01b2bab15ba7" />
