### ISSUE TITLE
umi4 的 request 能 axios 一点吗？

### ISSUE THREAD

**Issue by carveybunt** [umijs/umi#10850]
## Background

`vue` 使用 `axios` 很方便简介，但是看了 `umiRequest`  的相关代码和配置后，完全没有了 `axios` 的 `promise`踪影。首先说明我刚从 `vue` 转 `react`，表达有误的地方，请谅解。

## Proposal

拦截器，完全没有体现出拦截器的作用。而且不能再框架的拦截器里面使用 `promise` 。而在 `page` 中还要进行判断。如：

```tsx
const handleSubmit = async (values: API.LoginParams) => {
    try {
      // 登录
      const msg = await login({ ...values, type });
      if (msg.status === 'ok') {
        const defaultLoginSuccessMessage = intl.formatMessage({
          id: 'pages.login.success',
          defaultMessage: '登录成功！',
        });
        message.success(defaultLoginSuccessMessage);
        await fetchUserInfo();
        const urlParams = new URL(window.location.href).searchParams;
        history.push(urlParams.get('redirect') || '/');
        return;
      }
      console.log(msg);
      // 如果失败去设置用户错误信息
      setUserLoginState(msg);
    } catch (error) {
      const defaultLoginFailureMessage = intl.formatMessage({
        id: 'pages.login.failure',
        defaultMessage: '登录失败，请重试！',
      });
      console.log(error);
      message.error(defaultLoginFailureMessage);
    }
```
直接在拦截器里面「响应拦截器」里面做相应的状态拦截，直接使用 `promise` 的 `.then()` 进行下一步操作 `state` 不好吗？可能是我接触 react 事件不长，没弄懂其中的道理。

## Additional context

可以的话，希望 `umi4` 的 `request` 更方便简化，或者支持开发者移除 `request` 继而可以编写自己的 `axios` 。

**Comment by fz6m** [comment]
现在不推荐用 use request 了，axios 或者是 fetch 底层自己根据公司接口规范封装下，请求层用 [react-query](https://umijs.org/docs/max/react-query) 。

**Comment by fz6m** [comment]
axios / fetch 是底层用来发请求的，但只要是涉及到查询，就会有竟态问题，筛选条件切换了请求新的 api ，和之前的 api 结果谁先到达不一定，所以一定要使用一款避免竟态的工具，比如 swr 或者 react-query 。
