### ISSUE TITLE
你们环境变量到底要怎么设置？

### ISSUE THREAD

**Issue by carveybunt** [umijs/umi#10855]
## What happens?
又说支持`.env`，设置了又获取不到！按照你们配置文档来设置，获取了又报`ts`错误。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/carveybunt/pro-env

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

```env
// .env
APP_BASE_URL = 'http://www.xxx.ccc'
```
```env
// .env.developement
APP_BASE_URL = 'http://www.yyy.ccc'
```

![截屏2023-03-27 11 04 03](https://user-images.githubusercontent.com/37894474/227830847-6198f74e-bfa2-4f5e-8e29-7dff337f0320.png)
![截屏2023-03-27 11 05 41](https://user-images.githubusercontent.com/37894474/227830959-2bd4773f-fdb6-45b1-8605-1315d8854755.png)

![截屏2023-03-27 11 04 50](https://user-images.githubusercontent.com/37894474/227830851-63e8d84b-a6a7-4640-afdd-b43cc13d947f.png)

到底要怎样才能从`.env`中设置和获取到对应的变量？

## Context

- **Umi Version**: "@umijs/max": "^4.0.52"
- **Node Version**: 16.16.0
- **Platform**: MacOS 12.5

**Comment by fz6m** [comment]
```bash
# .env
APP_BASE_URL="xxx"
```

```ts
// .umirc.ts

export default {
  define: {
      'process.env.APP_BASE_URL': process.env.APP_BASE_URL
  }
}
```

新建 `global.d.ts`：

```ts
// global.d.ts

declare namespace NodeJS {
  interface ProcessEnv {
    readonly NODE_ENV: 'development' | 'production'
    readonly APP_BASE_URL: string
  }
}
```

**Comment by carveybunt** [comment]
一个环境变量搞那么复杂，vue vite nextjs 都能直接用，而且这还只是一个，多个还玩啥。果断弃坑……
