### ISSUE TITLE
指定UMI_ENV下多环境的环境变量获取不到

### ISSUE THREAD

**Issue by RichadoM** [umijs/umi#10863]
根据官方文档写法以及两个搜索到的issue修改了部分写法，一直获取不到
``` javaScript
// package.json
  "scripts": {
    "dev:pre": "cross-env UMI_ENV=pre umi dev",
  },
```

``` javaScript
// config.pre.ts
export default {
  define: {
    'process.env.REDIRECT_URL': 'www',
  },
};

```

``` javaScript
// app.ts
console.log(process.env.REDIRECT_URL, 'env'); // process.env下只有一个值为dev的环境变量，REDIRECT_URL为 undefined
};

```

文件有umirc，是因为umirc影响到了config不生效？
可是文档里又没有umirc中怎么设置环境变量中的写法

小小吐槽一下，环境变量这块，issue里提到的命名路径写全，文档里根本没提。。虽然按着改了也不好使。。
这块加个示例不好吗，说了umirc优先级高，又没说umirc里怎么设置环境变量，说根据UMI_ENV会识别config，又没说config里要怎么写。。

**Comment by fz6m** [comment]
需要给一个最小复现。

**Comment by RichadoM** [comment]
最小复现指的是什么？我上面贴的代码应该够用了

package.json下，指定了dev:pre中的UMI_ENV为pre

在根目录下创建了config.pre.ts，内容是上面第二块代码块

然后在项目业务代码中，打log输出process.env，仅有NODE_ENV一个变量

**Comment by fz6m** [comment]
[`UMI_ENV`](https://umijs.org/docs/guides/env-variables#umi_env) 是加载不同环境配置的约定，是 node 层的，但他不会注入到项目里。

项目里的环境变量属于 browser runtime 层，要通过 webpack 注入，这在 umi 里是 [`define`](https://umijs.org/docs/api/config#define) 选项，所以正常的环境变量要在项目里用：需要先在外部指定（他可能来自于命令行，或 `.env` 配置文件），之后加载到 node 里，之后通过 `define` 注入到项目里。

所以如果你要用 `process.env.UMI_ENV` ，就需要：

```ts
// .umirc.ts

export default {
  define: {
    'process.env.UMI_ENV': process.env.UMI_ENV
  }
}
```

不可以把所有的 node 环境变量都默认注入到项目里，因为环境变量太多了，会污染项目，所以每次都手动指定，你会发现这是比较麻烦的，因此所有的脚手架都会有一个约定，会自动加载某些前缀开头的 node 环境变量到 runtime 里，这在 umi 里是 `UMI_APP_` 开头的环境变量，这些环境变量一经指定会自动进入 `define` 可以在项目里使用，业界参考的其他例子比如 `REACT_APP_` / `VUE_APP_` 。

同时，webpack 的 define 插件只是 replace 功能，决定了 `process.env.XXX` 和 `process.env` 是不一样的，所以当你使用时应该注意。

最后，现在有一部分用户更偏向于指定非 process.env 开头的变量，比如 `__DEV__` ，但要不要用 `process.env` 开头取决于个人。

无论如何，如果想要在 TS 里有这些环境变量的类型提示，是需要手动编写类型文件进行全局声明的。
