### ISSUE TITLE
[Bug] 微前端下，自定义子应用Loading，Loading状态一直为true

### ISSUE THREAD

**Issue by ALL-STACK** [umijs/umi#10867]
## What happens?
微前端下，自定义子应用Loading，子应用加载后，Loading状态一直为true
![image](https://user-images.githubusercontent.com/24264872/228498652-a8aa0610-c2b6-4415-956d-68c6ecb36d42.png)
![image](https://user-images.githubusercontent.com/24264872/228498717-ae8c94e8-f0fd-4256-a239-119f4d3d5a2e.png)

## Mini Showcase Repository(REQUIRED)
https://github.com/ALL-STACK/umi-qiankun-master
https://github.com/ALL-STACK/umi-qiankun-slave1

## How To Reproduce
pull仓库后下载依赖，start 后可复现

## Context

- **Umi Version**: v4.0.63
- **Node Version**: v16.19.0
- **Platform**: windows，chrome

**Comment by fz6m** [comment]
See https://github.com/umijs/umi/pull/10870#issuecomment-1488587511

需要添加 `autoSetLoading` 或者自己在子应用里 setLoading(false) 。
