### ISSUE TITLE
支持配置 chunks、scripts、headScripts、metas 和 links

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#1086]
e.g.

```js
export default {
  plugins: [
    ['umi-plugin-react', {
      chunks: ['vendor', 'umi'],
      scripts: [
        { src: 'http://cdn/a.js' },
        { src: '<%= PUBLIC_PATH %>a.js' },
        { content: `alert('a');` },
      ],
      headScripts: [],
      metas: [
        { charset: 'utf-8' },
      ],
      links: [
        { rel: 'stylesheet', href: 'http://cdn/a.css' },
      ],
    }],
  ],
}
```

说明：

* chunks 默认是 `['umi']`，可修改，比如做了 vendors 依赖提取之后，会需要在 umi.js 之前加载 vendors.js
* headScripts 放在 `<head>` 里，在 umi.js 之前
* scripts 在 umi.js 后面
* scripts、headScripts 以及 links 的 href 属性，支持 publicPath 变量
* 可使用 `<%= PUBLIC_PATH %>` 指向 publicPath

**Comment by Jeephe** [comment]
请问这个功能将在哪个版本发布

**Comment by sorrycc** [comment]
下个版本。

**Comment by dengfuping** [comment]
需要更新下 `umi-plugin-react` 的配置文档

**Comment by xlei1123** [comment]
![image](https://user-images.githubusercontent.com/17528531/68914608-13fe1c80-079a-11ea-913d-73203b757cb6.png)
这个地方是vendors
