### ISSUE TITLE
[Bug] mountElementId 在 mpa 模式下不生效？

### ISSUE THREAD

**Issue by dingff** [umijs/umi#10872]
## What happens?

mountElementId 在 mpa 模式下无效
## Mini Showcase Repository(REQUIRED)
https://github.com/dingff/umi-template

## How To Reproduce
1. yarn dev

## Context

- **Umi Version**: 4.0.52
- **Node Version**: 14.21.3
- **Platform**: macos

**Comment by zenotsai** [comment]
现在默认是 `root`，没读取 `.umirc` 中的配置

你可以用[页面级配置](https://umijs.org/docs/guides/mpa#configjson)来实现想要的效果

```js
// src/pages/Index/config.json
{
  "mountElementId": "test"
}

```

**Comment by dingff** [comment]
> 现在默认是 `root`，没读取 `.umirc` 中的配置
> 
> 你可以用[页面级配置](https://umijs.org/docs/guides/mpa#configjson)来实现想要的效果
> 
> ```js
> // src/pages/Index/config.json
> {
>   "mountElementId": "test"
> }
> ```
不能统一设置吗，我要每个页面都去设置一下吗？
