### ISSUE TITLE
[Bug] mf 不能和 qiankun 一起使用

### ISSUE THREAD

**Issue by ALL-STACK** [umijs/umi#10888]
## What happens?
按照官方文档配置模块联邦失败，引入remote组件就报错
![image](https://user-images.githubusercontent.com/24264872/229075083-a34805a2-84bb-43a3-80c0-b6e9fe8593d0.png)
![image](https://user-images.githubusercontent.com/24264872/229075271-288343fc-01ad-4280-a518-7714f606f142.png)

## Mini Showcase Repository(REQUIRED)
https://github.com/ALL-STACK/umi-qiankun-master.git
https://github.com/ALL-STACK/umi-qiankun-slave1.git

## How To Reproduce
安装依赖，start就会出现

## Context

- **Umi Version**: latest
- **Node Version**: v16.19.0
- **Platform**: window10，chrome

**Comment by fz6m** [comment]
参考下 [mf-host](https://github.com/umijs/umi/tree/master/examples/mf-host) 和 [mf-remote](https://github.com/umijs/umi/tree/master/examples/mf-remote) ，这个是能跑通的。

这个 mf 并不是正式功能，没有在文档菜单里放出来，自己研究下吧。

**Comment by ALL-STACK** [comment]
> 参考下 [mf-host](https://github.com/umijs/umi/tree/master/examples/mf-host) 和 [mf-remote](https://github.com/umijs/umi/tree/master/examples/mf-remote) ，这个是能跑通的。
> 
> 这个 mf 并不是正式功能，没有在文档菜单里放出来，自己研究下吧。

 我就是看的mf-host和mf-remote￣□￣｜｜

**Comment by fz6m** [comment]
`mf` 现在和 `qiankun` 一起用的时候不能开启 `mfsu` ，需要都关掉 `mfsu: false` 。

这个是已知问题，还有一例反馈（ #10443 ）

有时间了辛苦看下 cc @stormslowly 🌹

**Comment by ALL-STACK** [comment]
> `mf` 现在和 `qiankun` 一起用的时候不能开启 `mfsu` ，需要都关掉 `mfsu: false` 。
> 
> 这个是已知问题，还有一例反馈（ #10443 ）
> 
> 有时间了辛苦看下 cc @stormslowly 🌹

关掉后提示：You need to export lifecycle functions in slave2 entry
![image](https://user-images.githubusercontent.com/24264872/229330260-9795db4e-79bf-4188-b2b9-65e1880d22e0.png)

**Comment by fz6m** [comment]
@stormslowly  mf 改了异步入口之后是不是就没法和 qiankun 一起用了，这个方案没推是有这方面考虑么，有解法么。

如果没解，qiankun + mf 得禁掉。

**Comment by xiaoxiong77** [comment]
> `mf` 现在和 `qiankun` 一起用的时候不能开启 `mfsu` ，需要都关掉 `mfsu: false` 。
想问一下，现在有解决方案吗，还是必须要关闭mfsu吗？
