### ISSUE TITLE
umi4.0.64根据官网流程初始化报错的问题

### ISSUE THREAD

**Issue by Vantown** [umijs/umi#10898]
![eea057c057bec82ac08b55f6cfb8215e](https://user-images.githubusercontent.com/29136022/229850041-fa3306e7-d9c4-496c-9aaa-3347a446f509.png)
![fa6228d7e0a7f24befa498ec448f589f](https://user-images.githubusercontent.com/29136022/229850100-a02c40fc-99f3-4abc-9b8d-c004290e5317.jpg)
![99fafb09677e11b6e2ec5f3c288e978a](https://user-images.githubusercontent.com/29136022/229850200-67c75209-f3b3-4d6b-9873-2fabbc9565bd.jpg)

node16.20.0+npm8.19.4+pnpm8.1.1+cnpm7.1.1+npminstall5.8.1+umi4.0.64
用官网流程初始化项目，试过pnpm和cnpm及yarn初始化以后运行项目的时候都在umijs内部报错了，postcss不是umi内置自己处理的吗？报这个错是什么原因呢，试了下手动安装上也不行

**Comment by Vantown** [comment]
![28834d7bbd9a358e124b6a2bdbdea008](https://user-images.githubusercontent.com/29136022/229852645-6ba4a21e-1a69-4d69-aef7-3ba40c3812d1.jpg)
官网示例的报错

**Comment by fz6m** [comment]
目测是被这个项目文件夹父级某个位置的 postcss 配置文件影响了，你找一下有没有。

**Comment by Vantown** [comment]
> 目测是被这个项目文件夹父级某个位置的 postcss 配置文件影响了，你找一下有没有。

父级没有web项目了，这个是新建的web项目文件夹，别的项目都是和这个同级别的

**Comment by fz6m** [comment]
我没能复现，需要给一个最小复现。

**Comment by fz6m** [comment]
在 #10913 跟进

**Comment by fz6m** [comment]
目前在 #10913 给出了几种本地可以先自己解决的方法，同时也在积极应对 pnpm v8 的问题，这个 issue 先关了。
