### ISSUE TITLE
[Feature Request] umi4动态加载glb文件，经常失败

### ISSUE THREAD

**Issue by pxim** [umijs/umi#10896]
## Background

 umi4动态加载glb文件，经常失败

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by pxim** [comment]
我用了这个帖子里的解决方案，https://www.cnblogs.com/kevinN/p/16600312.html ，还是不行

**Comment by fz6m** [comment]
[怎么自定义 loader](https://umijs.org/docs/introduce/faq#%E6%80%8E%E4%B9%88%E8%87%AA%E5%AE%9A%E4%B9%89-loader)

**Comment by pxim** [comment]
> [怎么自定义 loader](https://umijs.org/docs/introduce/faq#%E6%80%8E%E4%B9%88%E8%87%AA%E5%AE%9A%E4%B9%89-loader)

配置，还不能解决问题，应该不是这个原因

**Comment by pxim** [comment]
如果不是为了mpa，真不想升级4，一堆bug

**Comment by fz6m** [comment]
需要给一个最小复现

**Comment by pxim** [comment]
> 需要给一个最小复现

https://github.com/pxim/umi4-mpa-bug.git
这个是复现仓库，
dev模式下，打开 https://localhost:8000/webxr-demo.html 这个也面后，kira.glb，default.glb 模型，偶发性，经常性 的加载失败（如果没出bug，多f5刷新几次这个页面，就有bug了）
![image](https://user-images.githubusercontent.com/5111701/234189396-453bfe91-5931-4489-a339-0549f62815aa.png)


build模式下，永远是正常，正确的，所以必定是dev有bug
http://127.0.0.1:5500/build/webxr-demo/index.html
![image](https://user-images.githubusercontent.com/5111701/234189686-e65d0892-79c0-43e1-be94-8a16168c4b36.png)

**Comment by fz6m** [comment]
应该是已知的一个问题，参考 [`https`](https://umijs.org/docs/api/config#https) 关闭 http2 解决。
