### ISSUE TITLE
[Bug] 按官网运行umi 失败

### ISSUE THREAD

**Issue by zozopen** [umijs/umi#10897]
![image](https://user-images.githubusercontent.com/23204297/229727341-610c9341-0be2-4829-9a74-5efee3473204.png)

![image](https://user-images.githubusercontent.com/23204297/229727361-5d909dda-fc40-4480-9b5b-358ee2fa30a8.png)

不知道是不是我电脑问题，麻烦大佬帮手看看

**Comment by fz6m** [comment]
提供一下复现操作步骤
