### ISSUE TITLE
```bash

### ISSUE THREAD

**Issue by congwa** [umijs/umi#10895]
```bash
# .env
APP_BASE_URL="xxx"
```

```ts
// .umirc.ts

export default {
  define: {
      'process.env.APP_BASE_URL': process.env.APP_BASE_URL
  }
}
```

新建 `global.d.ts`：

```ts
// global.d.ts

declare namespace NodeJS {
  interface ProcessEnv {
    readonly NODE_ENV: 'development' | 'production'
    readonly APP_BASE_URL: string
  }
}
```

_Originally posted by @fz6m in https://github.com/umijs/umi/issues/10855#issuecomment-1484498364_

**Comment by congwa** [comment]
APP_BASE_URL 怎么区别 development 和 production 呢

**Comment by fz6m** [comment]
根据 [`UMI_ENV`](https://umijs.org/docs/guides/env-variables#umi_env) 的不同，会加载不同的环境配置文件，比如 `.umirc.prod.ts` / `.umirc.dev.ts` 等，在不同的配置文件 define 不同的值就可以了。

**Comment by zhangxinyong12** [comment]
> 根据 [`UMI_ENV`](https://umijs.org/docs/guides/env-variables#umi_env) 的不同，会加载不同的环境配置文件，比如 `.umirc.prod.ts` / `.umirc.dev.ts` 等，在不同的配置文件 define 不同的值就可以了。

![image](https://github.com/umijs/umi/assets/29941627/d5838cf6-2397-47a4-b694-a71d68f6db6a)
我要这样写吗？不能写在 .env.dev /.env.prod 文件里面吗？

**Comment by fz6m** [comment]
在环境变量文件里定义的变量（如 `.env.dev` ）只是会被自动加载到 node 中，比如：

```ts
// .env.dev
TEST=123
```

也就意味着在 umi 配置文件里可以通过 `process.env.TEST` 使用，但并不代表可以在 webpack 项目 browser 的环境中使用：

```ts
// config/config.ts

console.log(process.env.TEST)
```

如果你要在项目 browser 环境中也能用到，可以：

```ts
// config/config.ts

  define: {
    'process.env.TEST': process.env.TEST
  }
```

这样就可以让 `.env` 中的变量在项目中使用到了。

可以发现这种方式是比较繁琐的，所以有一个自动加载到项目 browser 中的环境变量命名约定：

```ts
// .env
UMI_APP_TEST=123
```

以 `UMI_APP_` 为前缀的，定义在环境变量文件 `.env` 中的环境变量，无需再写到 `define` 中，即可在项目中使用 `process.env.UMI_APP_TEST`
