### ISSUE TITLE
模块联邦，本地开发没问题，部署到线上就提示加eager

### ISSUE THREAD

**Issue by ALL-STACK** [umijs/umi#10906]
## What happens?
开启模块联邦，本地开发没问题，配置eager后还是报错，线上提示：umi.js:143 [import-html-entry]: error occurs while executing entry script
![image](https://user-images.githubusercontent.com/24264872/230293102-49ea6064-4693-4142-946b-f6957696006f.png)
线上是成功加载remote.js的，但还是报错
![image](https://user-images.githubusercontent.com/24264872/230293852-1388dd67-3d3e-4de6-9c60-8a6470b60aca.png)
请问是对部署文件层级有要求吗？线上是这样部署的：
![51a9602b1c954afe60b73e66973ece5](https://user-images.githubusercontent.com/24264872/230295150-ff508518-b06b-46cc-9ba9-dfd1b0e94a60.png)
![f3ab1685cadc245c25e6527292627f7](https://user-images.githubusercontent.com/24264872/230295180-9b462805-e37a-4e25-b76d-8d80f75fb63c.png)
![25aeff4ce65655b86e3fca0f21c0f91](https://user-images.githubusercontent.com/24264872/230295200-3705a733-313c-4949-afc9-5f7f56728860.png)
本地调试，只要不使用remote模块，线上就不会报错：
![image](https://user-images.githubusercontent.com/24264872/230301219-ad2e1a5f-b68e-4371-9783-40b8c36fce61.png)

## Mini Showcase Repository(REQUIRED)
https://github.com/ALL-STACK/umi-qiankun-master
https://github.com/ALL-STACK/umi-qiankun-slave1

## How To Reproduce
按照以上层级部署即可触发报错

## Context

- **Umi Version**: latest
- **Node Version**: 16.19.0
- **Platform**: window10, chrome

**Comment by fz6m** [comment]
duplicate #10888 

qiankun 目前不能和 mf 一起用，使用 mf 时需要关闭 `mfsu: false` ，另外 mf 属于未正式公开的功能，如有后续，在 #10888 跟进吧。

**Comment by ALL-STACK** [comment]
> duplicate #10888
> 
> qiankun 目前不能和 mf 一起用，使用 mf 时需要关闭 `mfsu: false` ，另外 mf 属于未正式公开的功能，如有后续，在 #10888 跟进吧。

不关闭还好，关闭后提示：[qiankun]: You need to export lifecycle functions in nebula-web-dev entry
![image](https://user-images.githubusercontent.com/24264872/230374676-02431114-ab68-4afa-a199-7d1b5b98389e.png)

**Comment by fz6m** [comment]
用 mf 的时候，qiankun 是不能用的。

**Comment by ALL-STACK** [comment]
> 用 mf 的时候，qiankun 是不能用的。

坐等兼容

**Comment by fz6m** [comment]
看一下 [mf-host](https://github.com/umijs/umi/tree/master/examples/mf-host) 、[mf-remote](https://github.com/umijs/umi/tree/master/examples/mf-remote) 这俩例子，我试了下主应用提供组件，子应用获取父应用的 mf 组件，可以用的。

需要注意的是 context 不通用，即 mf 的组件需要独立，用不了外部的 context 数据。

**Comment by WhatIsSpark** [comment]
> 看一下 [mf-host](https://github.com/umijs/umi/tree/master/examples/mf-host) 、[mf-remote](https://github.com/umijs/umi/tree/master/examples/mf-remote) 这俩例子，我试了下主应用提供组件，子应用获取父应用的 mf 组件，可以用的（最新版本）。
> 
> 需要注意的是 context 不通用，即 mf 的组件需要独立，用不了外部的 context 数据。

子应用内容更改后，会热更新到主应用上吗？

**Comment by fz6m** [comment]
现在不支持 mf 热更新，这也是 mf 的缺点之一，据说 mf 下一个版本会做类型提示和热更新，预计 2024 年完成，建议现在不要使用 mf 功能。

**Comment by WhatIsSpark** [comment]
没事这个问题，我们自行解决了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月09日 11:27 |
| 收件人 | umijs/umi ***@***.***> |
| 抄送人 | 十年人间 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [umijs/umi] 模块联邦，本地开发没问题，部署到线上就提示加eager (Issue #10906) |

现在不支持 mf 热更新，这也是 mf 的缺点之一，据说 mf 下一个版本会做类型提示和热更新，预计 2024 年完成，建议现在不要使用 mf 功能。
