### ISSUE TITLE
[Bug] 安装后 pnpm dev，排版错乱

### ISSUE THREAD

**Issue by LiMao00** [umijs/umi#10907]
## What happens?

安装后 pnpm dev，排版错乱

## Mini Showcase Repository(REQUIRED)

> 最小重现 https://gitee.com/limao-xs/del-issue-umi

## How To Reproduce
pnpm dlx create-umi@latest

依次选择：
Ant Design Pro (more plugins and ready to use features)
pnpm (recommended)
taobao (recommended for China)

pnpm dev
样式错乱
![image](https://user-images.githubusercontent.com/99939885/230313412-7b6c40b2-aee0-4ad6-a440-22ca53b9a727.png)

猜测：
你们的模板没有上传 pnpm-lock.yaml 文件（pnpm dlx create-umi@latest 下来是没有的），导致版本错乱

by the way：
这个问题几周之前就发现了

## Context

- **Umi Version**:"@umijs/max": "^4.0.64",
- **Node Version**:v16.14.2
- **Platform**: windows chrome

**Comment by fz6m** [comment]
在 #10913 跟进

**Comment by fz6m** [comment]
目前在 #10913 给出了几种本地可以先自己解决的方法，同时也在积极应对 pnpm v8 的问题，这个 issue 先关了。
