### ISSUE TITLE
乾坤插件，使用umi4项目主应用，umi3项目为子应用时本地调试报错，有解决方案吗

### ISSUE THREAD

**Issue by milu-ad** [umijs/umi#10917]
## What happens?

实践乾坤，将依赖于umi3的旧项目作为子应用嵌入到使用umi4启动的新项目中，嵌入后主子应用都可用，但控制台循环出现如下报错：

<img width="793" alt="image" src="https://user-images.githubusercontent.com/52789051/230528494-21b4d9d0-4e1d-47cc-8455-9be909e56f48.png">
<img width="791" alt="image" src="https://user-images.githubusercontent.com/52789051/230528507-df4f1c0c-13e9-4cf8-b9d1-96b94cfa179c.png">
<img width="710" alt="image" src="https://user-images.githubusercontent.com/52789051/230528557-f1080350-b9aa-47fb-9cc6-bd7f58b17d12.png">

系统页面存在如下报错提示（但主子应用都能正常运行）：
<img width="685" alt="image" src="https://user-images.githubusercontent.com/52789051/230528518-9c445778-fc58-4394-999c-0b2c1b02ffee.png">

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

新建umi4项目作为主应用，umi3项目作为子应用，使用乾坤插件即可

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
这个是你自己的接口或者是代理配置吧，自己想办法解决下。或者给一个最小复现。
