### ISSUE TITLE
[Bug] 根据umi4官方文档安装带有antd-design-pro的项目，antd-design-pro布局样式异常

### ISSUE THREAD

**Issue by NieShiyi** [umijs/umi#10910]
## What happens?
根据umi4官方文档安装带有antd-design-pro的项目， 界面antd-design-pro布局和样式异常
参照文档：https://umijs.org/docs/tutorials/getting-started

## Mini Showcase Repository(REQUIRED)
https://github.com/NieShiyi/umi4-antdpro-style
（readme文档里有具体的问题描述）
> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
直接启动项目 pnpm start
**Expected behavior** 1. 2.
期望antd-design-pro的样式和布局是正常显示

## Context
1. 根据umi4文档 执行`pnpm dlx create-umi@latest`
2. 选择pnpm、taobao、antd-design-pro
3. pnpm start启动项目，显示如下布局样式混乱的界面
![image](https://user-images.githubusercontent.com/35129125/230373364-b537a845-f1f0-4dab-b5e0-a68f22a27670.png)

- **Umi Version**:  4.0.64  
- **Node Version**: 16.17.0  
- **Platform**: windows10

**Comment by fz6m** [comment]
在 #10913 跟进

**Comment by NieShiyi** [comment]
主要是pnpm v8 导致安装依赖的版本有问题，发现在umi的配置文件中设置theme主题样式也有问题

**Comment by fz6m** [comment]
目前在 #10913 给出了几种本地可以先自己解决的方法，同时也在积极应对 pnpm v8 的问题，这个 issue 先关了。
