### ISSUE TITLE
`@umijs/plugins`会导致项目react主版本从18.2.0降低为17.0.2

### ISSUE THREAD

**Issue by AprildreamMI** [umijs/umi#10922]
## What happens?

`umi4`通过`npm`安装`@umijs/plugins`会导致**项目`react`主版本从18.2.0降低为17.0.2**

## 步骤
1. 通过umi4初始化一个项目
2. 观察node_modules中react版本为18.2.0
3. 在项目中`npm i @umijs/plugins -D `
4. 观察node_modules中react版本变为17.0.2

## Context

- **Umi Version**: 4.0.64
- **Node Version**: 16.15.0
- **Platform**:

**Comment by fz6m** [comment]
这个应该是老 npm 的问题，旧 npm 是存在幽灵依赖和隐形依赖的，同时谁先后安装就用谁的，所以依赖有非常多不确定性。

因此现在推荐都使用 pnpm 。

**Comment by AprildreamMI** [comment]
node版本是16，按道理不算老。如果先安装ant,ant安装了react18.2.0，再安装`@umijs/plugins`也会把版本降低到17.0.2，不管先后安装，只要安装了`@umijs/plugins`都会把版本降低到17.0.2，可以看下最小实现：https://github.com/AprildreamMI/umi4-mini-repository-1

> 这个应该是老 npm 的问题，旧 npm 是存在幽灵依赖和隐形依赖的，同时谁先后安装就用谁的，所以依赖有非常多不确定性。
> 
> 因此现在推荐都使用 pnpm 。
