### ISSUE TITLE
@umijs/plugins会导致项目react主版本从18.2.0降低为17.0.2

### ISSUE THREAD

**Issue by AprildreamMI** [umijs/umi#10923]
## What happens?
umi4通过npm安装@umijs/plugins会导致项目react主版本从18.2.0降低为17.0.2

## Mini Showcase Repository(REQUIRED)

https://github.com/AprildreamMI/umi4-mini-repository-1.git

## How To Reproduce

1. 通过umi4初始化一个项目
2. 观察node_modules中react版本为18.2.0
3. 在项目中npm i @umijs/plugins -D 
4. 观察node_modules中react版本变为17.0.2

## Context

Umi Version: 4.0.64
Node Version: 16.15.0
Platform: win10

**Comment by fz6m** [comment]
See #10121 10922
