### ISSUE TITLE
关于plugin.ts对比以前的document.ejs

### ISSUE THREAD

**Issue by Vantown** [umijs/umi#10921]
问题1：以前的document.ejs里可以用<%= content.config.publicPath%>来实现生产环境和开发环境的资源差异化加载，现在用plugin的modify.HTML或addHTMLHeadScripts怎么实现呢？我看window和this都没有，直接用这个变量也引不过去。
问题2：以前在document.ejs还能实现一种功能就是在首页根据不同域名加载不同客户端的js，比如指定域名加载钉钉sdk，指定域名加载飞书sdk，现在在plugin里也没法取window了

**Comment by fz6m** [comment]
如果要动态随环境调整 publicPath 在配置文件里判断下 `process.env.NODE_ENV` 再改 [`publicPath`](https://umijs.org/docs/api/config#publicpath) 就行。

如果要随环境或参数注入一些脚本什么的，可以用 [scripts](https://umijs.org/docs/api/config#scripts) 、[headScripts](https://umijs.org/docs/api/config#headscripts) 、[styles](https://umijs.org/docs/api/config#styles) 、[links](https://umijs.org/docs/api/config#links) 等等，一般情况你用不到插件去修改 html ，全部在配置文件就能解决。

**Comment by Vantown** [comment]
> 如果要动态随环境调整 publicPath 在配置文件里判断下 `process.env.NODE_ENV` 再改 [`publicPath`](https://umijs.org/docs/api/config#publicpath) 就行。
> 
> 如果要随环境或参数注入一些脚本什么的，可以用 [scripts](https://umijs.org/docs/api/config#scripts) 、[headScripts](https://umijs.org/docs/api/config#headscripts) 、[styles](https://umijs.org/docs/api/config#styles) 、[links](https://umijs.org/docs/api/config#links) 等等，一般情况你用不到插件去修改 html ，全部在配置文件就能解决。

就是没法像以前那种直接用变量占位符了，需要自己用process.env.NODE_ENV判断运行环境再多引用地址做修改是吧？那我知道了多谢
