### ISSUE TITLE
[Bug] UMI@3.5.39 本地开发正常，build打包后部署服务器上无法打开页面，页面白屏，没报错，model里的路由监听也不生效

### ISSUE THREAD

**Issue by DearGaz** [umijs/umi#10931]
## What happens?
1. 原来umi2.0，按引导升级到umi 3 (v3.5.39)
2. 开发模式下能正常打开页面
3. build之后部署到服务器上，页面空白，console里没有报错
![image](https://user-images.githubusercontent.com/41284640/230865966-4e62a580-7165-4899-aaf7-1c9fe39c63f8.png)
4. dva model的subscriptions添加了路由监听，但是控制台并没有任何输出
![image](https://user-images.githubusercontent.com/41284640/230866350-1b94ff69-698b-478a-b197-14ee1adb8a6e.png)
5. 服务器部署目录是/test/pages/，配置的base也是/test/pages/
![image](https://user-images.githubusercontent.com/41284640/230866112-5b6bdb8f-bad4-49c3-88e8-0631945a8c74.png)
 Showcase Repository(REQUIRED)
## Mini

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:3.5.39
- **Node Version**:v14.17.5
- **Platform**:Windows 10

**Comment by fz6m** [comment]
1. umi 3 不维护了，建议升级到 umi 4 。

2. 没必要打包完在线上调试，本地 build 完对 dist 手动起一个服务测试下到底哪里有问题（比如 nginx / [`serve`](https://www.npmjs.com/package/serve) 等工具），没有报错大概率是路由没匹配上，匹配了个空的路由。

**Comment by DearGaz** [comment]
@fz6m
1. umi 4 对项目的改动太大了，也很担心会出现各种意料之外的问题。目前对升级持观望态度
2. 倒也不是直接丢到线上了，其实是在本地，但重点是不知道如何测试，比如如何知道umi支持的路由有哪些；model文件是否被注册了（主要是subscriptions的路由监听居然没有任何反应，但按约定式model目录结构，打开的地址是合法model，这在2.0中也一直是正常的）；当然最重要的是，本地测试时如何判断当前打开的路由地址是合法的或者是umi支持的路由呢，看约定式路由的基本特征是满足的，根据相关配置的说明描述，也是符合配置逻辑的（约定式路由和model的组织方式是沿用2.0版本的风格的）
3. 升级到3.0版本，还有一个奇怪的现象，开发模式下把publicPath配成`./` 实际打出来的umi.js. umi.css文件居然全部是模板文件的html内容，所以不得不在开发环境下配成/而在测试或生产环境下配成`./`（因为我的站点部署目录并非根目录，相对路径更方便）但这让人很费解（以及后续代码的维护上）—— 希望第3点能给第2点带来一些线索
4. 这一系列的升级其实就是为了解决 2.0引入web   worker异常的问题（#10900），如果有在2.0版本下支持web worker的思路和建议，真感激不尽🤝
