### ISSUE TITLE
[Bug] type.ts里的js加载都到闭包里去了

### ISSUE THREAD

**Issue by Vantown** [umijs/umi#10934]
3.x放在document.ejs里的很多方法包括jssdk都是通过window.xx调用的，现在换成type.ts以后，这些库都被放到闭包里去了，这样外面无法调用了，还有什么别的方式可行吗？
![image](https://user-images.githubusercontent.com/29136022/230902889-ec0b3e8a-a27e-4fb3-85d9-e7ee8747c7a5.png)

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4

**Comment by Vantown** [comment]
> umi 3 不维护了，建议升级到 umi 4

是4.x啊，我是用的4.x的plugin.ts加载的，那不没document.ejs了吗？我现在就是用的4.x的plugin.ts加载的以前在document.ejs里声明的一些变量和方法，但是打包的时候全到闭包里去了

**Comment by fz6m** [comment]
闭包是指啥，修改产物 html 吗，用 headScripts 、scripts 、links 等选项添加字符串就可以了，参考 [这里](https://umijs.org/docs/api/config#headscripts) 。

**Comment by Vantown** [comment]
> 闭包是指啥，修改产物 html 吗，用 headScripts 、scripts 、links 等选项添加字符串就可以了，参考 [这里](https://umijs.org/docs/api/config#headscripts) 。

就像我第一张截图那样pathname本来是在window上，后面还有很多变量和方法，现在打包的时候这些被套在一个闭包里了
!(function(){const path = ....})();
像我现在放在modifyHTML里是可以拿到publicPath的这样实现了以前的document.ejs里的<%= context.config.publicPath %>打包不同环境不用引用的问题，要是放到headScript里了之后，除了在不同打包config文件里配置不同的引用地址还有别的方式吗？

**Comment by Vantown** [comment]
![lADPKH7Rzoyv_gTNBaDNB4A_1920_1440](https://user-images.githubusercontent.com/29136022/230935507-5b81e1f5-53af-4360-ab2e-f548a4371a8d.jpg)
放到headScriptheadScripts里以后打包的时候还是被改动了

**Comment by fz6m** [comment]
这个问题在 #10904 被解决，但还没发版，等待本周四下一次发版吧，全局变量可以明确指定 `window.xxx` 使用。

**Comment by Vantown** [comment]
> 这个问题在 #10904 被解决，但还没发版，等待本周四下一次发版吧，全局变量可以明确指定 `window.xxx` 使用。

好的好的，多谢
