### ISSUE TITLE
[Bug] @umijs/max 4.0.51 以后包引用路径在macOS下大小写不一致

### ISSUE THREAD

**Issue by yw-mao** [umijs/umi#10933]
## What happens?

@umijs/max 4.5.1 以后包引用路径在MacOS下大小写不一致

## How To Reproduce

4.0.51及以后版本截图
![image](https://user-images.githubusercontent.com/88931049/230888903-4b1aecc1-741a-407e-8605-a2d583b43cbd.png)

4.0.50正常
![image](https://user-images.githubusercontent.com/88931049/230889200-b4bbd2f7-b8df-4a7c-8aa9-07d496685682.png)

## Context

- **Umi Version**: 4.0.51+
- **Node Version**: 18
- **Platform**: mac OS 13.1

其他依赖版本
- @ant-design/pro-components: 2.4.4
- antd: 5.4

**Comment by fz6m** [comment]
给一个最小复现看看。
