### ISSUE TITLE
[Bug] 创建umi4项目后出现的一些问题antd、config

### ISSUE THREAD

**Issue by rookiesBody** [umijs/umi#10949]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: @4.0.64
- **Node Version**:
- **Platform**:

What is actually happening?
1. 下载umi4项目后，antd menu组件异常不能使用
2. 删除.umirc文件后，config/config.ts 异常不能使用，保留,umirc文件正常
3. 因为第一种情况的出现，所以我自己安装了antd@4 版本后，组件可以使用了但是antd默认样式引入失效
  测试demo：
[demo.zip](https://github.com/umijs/umi/files/11206912/demo.zip)

**Comment by fz6m** [comment]
umi 是最简版的项目模板，没有 antd 、locale 、qiankun 等等功能，这些是 max 里的。

要不就创建 max 直接用，要不就参考 [文档](https://umijs.org/docs/guides/use-plugins#%E4%BD%BF%E7%94%A8%E6%8F%92%E4%BB%B6) 自己在 umi 上面配一下才能用对应的功能。

**Comment by rookiesBody** [comment]
感谢回复，今天又试了几次还是有点问题，还是回退到umi3吧
