### ISSUE TITLE
[Bug] 在umi3.5 ssr模式下，开启locale会报navigator is not defined , at getLocale

### ISSUE THREAD

**Issue by lyhjob2019** [umijs/umi#10940]
在umi3.5 ssr模式下，开启locale会报navigator is not defined , at getLocale
/config/config.ts:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/55875049/231080844-1fbefd17-303e-4821-acbe-1e6a59183078.png">

终端：
<img width="596" alt="image" src="https://user-images.githubusercontent.com/55875049/231076432-6b5faba7-7e33-4aeb-8730-9a3a0c52b93e.png">

这是/src/.umi/plugin-locale/localeExports.ts 中的getLocale 方法
<img width="759" alt="image" src="https://user-images.githubusercontent.com/55875049/231076686-93e9cac7-8b10-4e7f-b9d3-950e7b735cd9.png">

## Context

- **Umi Version**: ^3.5.39 
- **Node Version**: v14.17.3
- **Platform**:

**Comment by peterleng** [comment]
出现了同样的问题，纯umi + react的网页在开启 ssr之后，报 referenceerror: navigator is not defined； 而且根本不是自己写的代码无法进行服务端判断来规避这个问题

**Comment by fz6m** [comment]
umi 3 不维护了，如需 SSR 建议使用 nextjs

**Comment by gujiaxuan** [comment]
这个解决了吗，同问

**Comment by iemi** [comment]
这问题到现在都没解决？这垃圾框架怎么会有人在用啊

**Comment by lyhjob2019** [comment]
不要用这个框架最好，它的ssr是完全失效的。这些bug就算你修复了也毫无意义，纯粹浪费时间。













在 2024-11-21 01:16:28，"iemi" ***@***.***> 写道：

这问题到现在都没解决？这垃圾框架怎么会有人在用啊
