### ISSUE TITLE
ts错误没有显示出来，错误的代码还是编译通过

### ISSUE THREAD

**Issue by allan-hx** [umijs/umi#1094]
![image](https://user-images.githubusercontent.com/37947922/45617116-e6d5b180-baa3-11e8-8358-225b7a0f9911.png)

使用ts的时候： 如图代码应该是要有异常抛出来的，但是命令行显示的还是正常的，通过了编译

![image](https://user-images.githubusercontent.com/37947922/45617180-171d5000-baa4-11e8-8dfd-1bfcd5d85d71.png)
版本：2.0.3

**Comment by sorrycc** [comment]
参考 https://umijs.org/guide/env-variables.html#fork-ts-checker
