### ISSUE TITLE
[Bug] v4.0.64 可能引入了问题 [esbuildHelperChecker] Found conflicts in esbuild helpers: v (5880.3ae36eee.async.js, 8401.e78bd970.async.js), please set esbuildMinifyIIFE: true in your config file.

### ISSUE THREAD

**Issue by chzhuo** [umijs/umi#10959]
我使用 v4.0.64 编译项目，然后报错：
![image](https://user-images.githubusercontent.com/10919124/231674105-651f35bc-7baf-4595-80c0-409368e13565.png)

我使用 v4.0.63 编译项目成功：
![image](https://user-images.githubusercontent.com/10919124/231674213-1a861908-0a44-4d08-bbd2-9807a359bff8.png)

我怀疑是这个 MR 引起的问题：https://github.com/umijs/umi/pull/10859

我构建的环境（我在mac和linux ci 机器上都是这个问题）：
``` Dockerfile
FROM alpine:3.17 AS BUILDER
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories \
    && apk add --no-cache --virtual .build-deps make git gcc nodejs yarn
```

由于项目东西比较多，所以不太好抽一个可复现的 demo。不知道有没有人可以通过上面的信息找到问题。

**Comment by fz6m** [comment]
开一下这个选项 `esbuildMinifyIIFE: true` ，这是 esbuild 压缩器和异步分包同时用可能有的一个副作用（全局变量命名冲突），umi 会自动检测这个副作用。

**Comment by xlorne** [comment]
esbuildMinifyIIFE: true 在哪里设置？

**Comment by xlorne** [comment]
知道了，是在config/config.ts下：
```
// https://umijs.org/config/
import {defineConfig} from '@umijs/max';
import defaultSettings from './defaultSettings';
import proxy from './proxy';
import routes from './routes';

const {REACT_APP_ENV} = process.env;

export default defineConfig({
  esbuildMinifyIIFE: true,

  ...
```

**Comment by Yyunfan** [comment]
@fz6m 加了esbuildMinifyIIFE 会导致build后，exposes暴露给其它应用使用模块联邦时候会出现 挂载在全局 下的远程模块变量提示 init is not a function

**Comment by fz6m** [comment]
参考 #10602 ，这是一个已知问题，`esbuildMinifyIIFE` 会套一层自执行 iife 函数来解决 esbuild 压缩变量冲突问题。

目前的解决办法二选一：

1. 不使用默认的 esbuild 压缩，调整 `jsMinifier` 为 `terser` 。

2. mf 默认会从 `global` 上获取，当使用了 `esbuildMinifyIIFE` 时，需要改为从 `window.xxx` 上获取。

如有兴趣，欢迎提出 PR 帮助解决 #10602 。

如还有问题，需要提供一个最小复现。

**Comment by Yyunfan** [comment]
thx，暂时先用terser 替代 esbuild，后面研究下有没好的办法

**Comment by haobarry** [comment]
@fz6m 开了, 用的pro antdesign 脚手架起的项目, 报错   Invalid config keys: esbuildMinifyIIFE

**Comment by t634146397** [comment]
这两种方式都试了，本地正常build，jenkins就不行了

**Comment by t634146397** [comment]
> 参考 #10602 ，这是一个已知问题，`esbuildMinifyIIFE` 会套一层自执行 iife 函数来解决 esbuild 压缩变量冲突问题。
> 
> 目前的解决办法二选一：
> 
> 1. 不使用默认的 esbuild 压缩，调整 [`jsMinifier`](https://umijs.org/docs/api/config#jsminifier-webpack) 为 `terser` 。
> 2. mf 默认会从 `global` 上获取，当使用了 `esbuildMinifyIIFE` 时，需要改为从 `window.xxx` 上获取。
> 
> 如有兴趣，欢迎提出 PR 帮助解决 #10602 。
> 
> 如还有问题，需要提供一个最小复现。
这两种方式都试了，本地正常build，jenkins就不行了

**Comment by t634146397** [comment]
> 参考#10602，这是一个已知问题，`esbuildMinifyIIFE`会套层自执行 iife 函数来解决 esbuild 压缩变量冲突问题。
> 
> 目前的解决办法二选一：
> 
> 1. 不使用默认的esbuild压缩，调整[`jsMinifier`](https://umijs.org/docs/api/config#jsminifier-webpack)为`terser`。
> 2. mf默认会从`global`上获取，当使用了的`esbuildMinifyIIFE`时候，需要改为从`window.xxx`上获取。
> 
> 如果有兴趣，欢迎提出 PR 帮助解决#10602。
> 
> 如还有问题，需要提供一个最小的还原。



这两种方式都试了，本地正常build，jenkins就不行了

**Comment by fz6m** [comment]
如果是环境问题，需要自己排查下，比如基础库是否缺失，nodejs 版本，pnpm 版本等。

**Comment by t634146397** [comment]
@fz6m 这两种方式都试了，本地正常build，jenkins就不行了

> 如果是环境问题，需要自己排查下，比如基础库是否欠缺，nodejs版本，pnpm版本等。

👌

**Comment by t634146397** [comment]
> 如果是环境问题，需要自己排查下，比如基础库是否欠缺，nodejs版本，pnpm版本等。

还有一个问题，前天jenkins构建都好好的，昨天就不行了，在这期间也没有安装任何依赖 这是咋回事呀

**Comment by fz6m** [comment]
排查下 jenkins 是不是有缓存之类的问题吧，看下构建完整日志，依赖是否都正确的安装了等，另外看下是否存在 lock 文件，lock 文件是否生效了，是不是安装的 node 、pnpm 版本号不一致等。

**Comment by JimWang-happy** [comment]
> 这两种方式都试了，本地正常build，jenkins就不行了

请问这个有解决了吗，怎么解决的?
![image](https://github.com/umijs/umi/assets/76657138/08b86a8c-fb5d-49bb-8c72-bf89acd580d8)
![image](https://github.com/umijs/umi/assets/76657138/666672b8-1e1c-4da8-a64d-e2ed95a78d58)

**Comment by t634146397** [comment]
> > 这两种方式都试了，本地正常build，jenkins就不行了
> 
> 请问这个有解决了吗，怎么解决的? ![image](https://private-user-images.githubusercontent.com/76657138/322730962-08b86a8c-fb5d-49bb-8c72-bf89acd580d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTA1MzEsIm5iZiI6MTcxMzI1MDIzMSwicGF0aCI6Ii83NjY1NzEzOC8zMjI3MzA5NjItMDhiODZhOGMtZmI1ZC00OWJiLThjNzItYmY4OWFjZDU4MGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA2NTAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMGJhOGM5ZWY5ODU1ZTA4MDdhY2VhZTFlNmU0M2QxN2M2OGQ3MDA5ZmEyYjRmZTFmNmY4Zjg1OWQ3MDljODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eAhNkylBAHTfVmciH63npEXWuzbFHHSs_WaHc4B3lcI) ![image](https://private-user-images.githubusercontent.com/76657138/322731436-666672b8-1e1c-4da8-a64d-e2ed95a78d58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTA1MzEsIm5iZiI6MTcxMzI1MDIzMSwicGF0aCI6Ii83NjY1NzEzOC8zMjI3MzE0MzYtNjY2NjcyYjgtMWUxYy00ZGE4LWE2NGQtZTJlZDk1YTc4ZDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDA2NTAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MTk0MjNlZWVmNTExZWJjYmQ2OTE3ZTdmNWQwNzNkNjAyNDMxYTRkMDhiN2Q5NzhjNmRjODQ3MWVmZTRlMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LU1tkt2ncyZtD8HbGAycCobh5i6zNpRBAF_s-RfEcdg)

我用/* 压缩方式 esbuild打包会打包失败 */
  jsMinifier: 'terser',

**Comment by fz6m** [comment]
如果报错，根据报错提示里说的，加上这个配置：`esbuildMinifyIIFE: true` 即可。
