### ISSUE TITLE
[Feature] src/icons 支持 二级目录

### ISSUE THREAD

**Issue by fz6m** [umijs/umi#10956]
### 功能

如题，目前只支持 1 级里直接放 `xxx.svg` 。

### Discussed in https://github.com/umijs/umi/discussions/10953

<div type='discussions-op-text'>

<sup>Originally posted by **hanzebang** April 12, 2023</sup>
![image](https://user-images.githubusercontent.com/46307343/231407570-ebddf075-2ba4-4f83-992e-c72e39eed01c.png)
比如这种，现在应该还不支持</div>

**Comment by xiaohuoni** [comment]
这要怎么读？
`local:p1/home1` ?
