### ISSUE TITLE
[Bug]umi3在app.tsx中使用patchClientRoutes 报异常 register failed, invalid key .

### ISSUE THREAD

**Issue by mizhicangyue** [umijs/umi#10967]
umi3在app.tsx中使用patchClientRoutes 报异常 register failed, invalid key .
之前使用patchRoutes是没问题的，换成了patchClientRoutes 就不好使，重新装包了也不行。

**Comment by xierenyuan** [comment]
> umi3在app.tsx中使用patchClientRoutes 报异常 register failed, invalid key . 之前使用patchRoutes是没问题的，换成了patchClientRoutes 就不好使，重新装包了也不行。

umi3 没有 patchClientRoutes 吧  umi4 有
