### ISSUE TITLE
动态路由构建菜单成功 切换菜单报错

### ISSUE THREAD

**Issue by 308787520huanhuan** [umijs/umi#10961]
![image](https://user-images.githubusercontent.com/3348828/231680133-e24c8368-17c3-4ad5-a5b7-71b20cc7c7c6.png)
![image](https://user-images.githubusercontent.com/3348828/231680395-5bfc85a9-0491-4ff3-ae17-17ec910f7f12.png)
![image](https://user-images.githubusercontent.com/3348828/231680749-78d6eb6c-7097-4b9c-b516-5496c10aff0a.png)
![image](https://user-images.githubusercontent.com/3348828/231680806-137d4d2e-3547-43c5-bf01-9b876904c7c7.png)
现在的问题是启动 跳转登录页面 登录成功跳转list后 页面不显示 并且报错 刷新后又能正确渲染页面 但是切换菜单的时候又会出现同样的问题 
![image](https://user-images.githubusercontent.com/3348828/231681628-2d5941e8-bf78-492e-94d1-83bb940aaee4.png)
![image](https://user-images.githubusercontent.com/3348828/231681779-a8d01efc-73c6-42d1-9ca1-05bee2d418f8.png)

**Comment by fz6m** [comment]
动态路由需要维护完整的路由映射表，不能在 `import('xxx')` 里使用变量，不知道要打包哪些内容。

**Comment by seanlsr** [comment]
umi3下能正常工作。umi4有大佬可以解决么

**Comment by seanlsr** [comment]
可以试下用React.cloneElement
![image](https://github.com/umijs/umi/assets/34623428/32e28670-77b6-4b13-9e23-0c91d004d204)
