### ISSUE TITLE
有关deps下esbuild-linux-64问题

### ISSUE THREAD

**Issue by theDoinb** [umijs/umi#10974]
## What happens?

有没什么可以绕过这个东西？

## Mini Showcase Repository(REQUIRED)

> 内网的东西，不知道怎么重现，因为源也是他们内网提供的地址，但是翻了下他们的库确实是有这个包的

## How To Reproduce

在linux底下打包就会报错，除了这个包，其他包似乎下载没问题，因为是内网的东西，看不到到具体，
但是我猜测是node_modules底下找不到  esbuild-linux-64 这个包，有没什么办法可以解决，或者跳过这个....
```
Trying to download "https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.12.15.tgz"
316    2023-04-13 17:05:20 Failed to download "https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.12.15.tgz": connect ENETUNREACH 104.16.26.35:443

npm ERR! request to https://registry.yarnpkg.com/esbuild-linux-64 failed, reason: connect ENETUNREACH 104.16.16.35:443
```

## Context

- **Umi Version**:4.0.38
- **Node Version**:18.15.0
- **Platform**:linux

**Comment by fz6m** [comment]
你第一次初始化项目的时候，本地 yarn 没有用淘宝源，是官方 yarnpkg 源，在你的服务器上没有代理速度很慢，所以下载包失败了。

解决方案：在本地 `yarn.lock` 里搜一下 yarnpkg ，看看有多少，改回国内源之后，刷一下 lock 文件。

或者在服务器上开启代理。

**Comment by theDoinb** [comment]
> 你第一次初始化项目的时候，本地 yarn 没有用淘宝源，是官方 yarnpkg 源，在你的服务器上没有代理速度很慢，所以下载包失败了。
> 
> 解决方案：在本地 `yarn.lock` 里搜一下 yarnpkg ，看看有多少，改回国内源之后，刷一下 lock 文件。
> 
> 或者在服务器上开启代理。

脑壳疼，实际上我并没有上传lock到那边，yarn源地址是客户那边提供的，本地其实Linux底下有用淘宝源测过是没问题的，但是在那边服务器上就会报这个错，那边是内网所以是不能用淘宝源的，本地Linux的node_modulues下是有esbuild-linux-64这个包，我想按node依赖查找是最近的node_modules下去找，所以我估计他上边yarn install后没有，但实际去看了他那个源，确实存在esbuild-linux-64-0.12.15.tgz这个东西，所以就麻了，着想怎么能跳过这个包。

现在比较猥琐的做法就是直接把打包编译后的文件的丢上去了...

**Comment by fz6m** [comment]
可以看看他有什么版本的 esbuild ，然后 yarn resolution 一下，现在 umi 4 在 `0.16.x` 都是没问题的（未来如果升到 `0.17.x` 可能有 Breaking change ）。

如果你自己本地传 esbuild 二进制的话，以后升级 umi 4 的时候需要关注下，如果升到了 `0.17.x` 你也要换。

**Comment by theDoinb** [comment]
> 可以看看他有什么版本的 esbuild ，然后 yarn resolution 一下，现在 umi 4 在 `0.16.x` 都是没问题的（未来如果升到 `0.17.x` 可能有 Breaking change ）。
> 
> 如果你自己本地传 esbuild 二进制的话，以后升级 umi 4 的时候需要关注下，如果升到了 `0.17.x` 你也要换。

好吧，我这边暂时也没没什么办法，手上也还有其他东西，后续再试试吧，感谢

**Comment by kkkakkk** [comment]
@theDoinb 你好，请问该问题后来解决了嘛，我这边也遇到了几乎一模一样的问题，我是umi升级3.5之后使用webpack5，在内网jenkins上构建报了该错误～
