### ISSUE TITLE
[Feature Request] 自定义的umi g component  支持增加文件

### ISSUE THREAD

**Issue by panjunqiu** [umijs/umi#10977]
## Background

使用umi g component --eject 释放了组件的模版，想增加一些组件文档的模版，发先再次创建并没有生成，umi g page 自定义的模版却可以增加文件。
查看代码发现：
![image](https://user-images.githubusercontent.com/15853835/232197398-e85852c8-6b7c-4dbd-b6b5-782c1434174f.png)
模版处理指定了两个特定的文件。
page命令是拷贝了模版目录
## Proposal

是否可以修改umi g compoment 也是拷贝目录，方便释放后增加文件？

**Comment by fz6m** [comment]
可以看下这个有没有兴趣 @mysteryven 🌹

**Comment by mysteryven** [comment]
很乐意 😄
