### ISSUE TITLE
umi4，errorHandler 这个如何关闭，我自己写的响应拦截没用

### ISSUE THREAD

**Issue by haobarry** [umijs/umi#10986]
文档上面说 `如果你觉得这种方式进行错误处理过于繁琐，可以直接在拦截器中实现自己的错误处理。`=

我自己写拦截器，错误拦截不到错误呀？？

**Comment by fz6m** [comment]
这里指的是 axios 可以有响应拦截器，在 request 里本质上还是用的 axios 包装后的方法。

**Comment by sunshineLing** [comment]
遇到了同样的问题，responseInterceptors和errorHandler都配置了，接口状态302的时候，errorHandler捕捉到错误，但是status不是302，而是0，responseInterceptors却没有触发。
