### ISSUE TITLE
如何修复npm audit的漏洞

### ISSUE THREAD

**Issue by haonanu** [umijs/umi#11002]
### Discussed in https://github.com/umijs/umi/discussions/11000

<div type='discussions-op-text'>

<sup>Originally posted by **haonanu** April 19, 2023</sup>
UMI3 执行npm audit后 found 10 vulnerabilities (2 low, 4 moderate, 3 high, 1 critical) in 2617 scanned packages.
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ node-fetch is vulnerable to Exposure of Sensitive            │
│               │ Information to an Unauthorized Actor                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ node-fetch                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.6.7                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ umi-request                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ umi-request > isomorphic-fetch > node-fetch                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1091239                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ node-fetch is vulnerable to Exposure of Sensitive            │
│               │ Information to an Unauthorized Actor                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ node-fetch                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.6.7                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @umijs/plugin-dva                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @umijs/plugin-dva > dva > isomorphic-fetch > node-fetch      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1091239                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Prototype Pollution in immer                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ immer                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=9.0.6                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @umijs/plugin-dva                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @umijs/plugin-dva > dva-immer > immer                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1089281                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ critical      │ Prototype Pollution in immer                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ immer                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=9.0.6                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @umijs/plugin-dva                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @umijs/plugin-dva > dva-immer > immer                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1089656                     │
└───────────────┴──────────────────────────────────────────────────────────────┘</div>

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4
