### ISSUE TITLE
[Bug] 十万火急！本地运行正常，build到线上访问不了！

### ISSUE THREAD

**Issue by whaty** [umijs/umi#11003]
十万火急！本地运行正常，build到线上访问不了！

今天本地调试好的功能，build上线之后，报如下错误，然后页面白屏，无法访问任何页面！
<img width="1760" alt="image" src="https://user-images.githubusercontent.com/26294919/233146012-e508c250-df00-4dd7-8289-d30c93f2eba7.png">

**Comment by fz6m** [comment]
需要给一个最小复现，或者定义一下 `devtool: 'source-map'` 看看是哪一行跑错了。

**Comment by whaty** [comment]
> 需要给一个最小复现，或者定义一下 `devtool: 'source-map'` 看看是哪一行跑错了。

`devtool: 'source-map'`这一行加到哪里

**Comment by fz6m** [comment]
配置文件里，三个排查方向：

1. 开启 `devtool: 'source-map'` ，本地构建完 `pnpm umi preview` 启动生产模拟，看下哪里报错了。

2. 开启 `devtool: 'source-map'` ，发到预发环境，看看哪里报错了（注意生产不要留 `.map` 文件）

3. 开启 `COMPRESS=none` 发到预发或线上，看看哪里报错了（这是临时方法，排查完不要定义这个变量了）

以上的所有方法，如果不想发到线上，就本地 charles 拦截映射下到本地 map locale 等手段，做到本地调试线上。
