### ISSUE TITLE
升级到umi2.0后，只要找不到模块，cpu就会100%

### ISSUE THREAD

**Issue by dly667** [umijs/umi#1100]
升级到umi2.0后，只要找不到模块，cpu就会100%
![_20180918165940](https://user-images.githubusercontent.com/26707226/45676692-e94c1000-bb64-11e8-88e7-e29d8a015a42.png)
![_20180918170241](https://user-images.githubusercontent.com/26707226/45676700-ec470080-bb64-11e8-94cd-76eeb321647c.png)

**Comment by sorrycc** [comment]
是不是开了 hardSource? windows 下关了这个吧。
