### ISSUE TITLE
[Bug] 4.0.55 导入tailwindcss.js 报错

### ISSUE THREAD

**Issue by majiajue** [umijs/umi#11019]
at Object.schema [as tailwindcss] (F:\chatgpt-web\node_modules\@umijs\plugins\dist\tailwindcss.js:32:20)
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0.55
- **Node Version**: 18
- **Platform**: react

**Comment by fz6m** [comment]
需要给一个最小复现。
