### ISSUE TITLE
[Feature Request] 4.0.66版本中unocss生成异常

### ISSUE THREAD

**Issue by magao1991** [umijs/umi#11014]
@umijs/max及@umijs/plugins两个包升级到最新版本4.0.66后，编译生成的src/.umi/uno.css文件中生成的样式代码不全面，缺失了在unocss.config.ts文件中配置的自定义transformers、rules、presetWind、presetWind等样式规则，切换成4.0.62后正常

**Comment by fz6m** [comment]
See #11013

**Comment by fz6m** [comment]
目前 umi 的 tailwindcss / unocss 插件是侧载方式实现的，所以有一些功能缺失，如需完整的功能，可以不使用 umi 的插件，自己根据官网的文档配置 postcss 或 webpack 插件即可。

Refer：https://github.com/umijs/umi/issues/11403#issuecomment-2026736996
