### ISSUE TITLE
在没有 "node" 模块解析策略的情况下，无法指定选项 "-resolveJsonModule"。

### ISSUE THREAD

**Issue by YangJianFei** [umijs/umi#11010]
umi4使用：pnpm dlx create-umi@latest创建的模板报错
在没有 "node" 模块解析策略的情况下，无法指定选项 "-resolveJsonModule"。

第一步：pnpm dlx create-umi@latest
选择：ant pro 
选择：pnpm
选择：taobao

第二步：pnpm run dev

然后vacode的tsconfig.json报错：
在没有 "node" 模块解析策略的情况下，无法指定选项 "-resolveJsonModule"。

环境：
win11
"@umijs/max": "^4.0.66",
node：v16.19.1
pnpm：8.3.0

**Comment by fz6m** [comment]
没遇到你这个问题，升级你的 vscode 版本（内置 TS 引擎太旧了），或者用当前项目工作区的 TS 版本作为引擎（右下角配置）。

**Comment by zhangxinyong12** [comment]
node16.7 .我也遇到这个提示了。怎么解决的？vscode版本是最新的。

**Comment by zhangxinyong12** [comment]
> node16.7 .我也遇到这个提示了。怎么解决的？vscode版本是最新的。

{
  "extends": "./src/.umi/tsconfig.json",
  "compilerOptions": {
    "moduleResolution": "node"
  }
}

这样好像可以。

**Comment by YangJianFei** [comment]
或者重新安装vscode也可以

> > node16.7 .我也遇到这个提示了。怎么解决的？vscode版本是最新的。
> 
> { "extends": "./src/.umi/tsconfig.json", "compilerOptions": { "moduleResolution": "node" } }
> 
> 这样好像可以。

**Comment by zhangxinyong12** [comment]
> 

vscode设置的自动更新。应该是最新的吧
