### ISSUE TITLE
[Feature Request] say something

### ISSUE THREAD

**Issue by biuge** [umijs/umi#11012]
## Background

1. 我用alita 依赖了umi 
2. umi依赖了react-route 6.3.0的版本
3. 然后你们回复的是 6.3.0去掉了Prompt 链接在下
https://github.com/umijs/umi/discussions/10237#discussioncomment-4625915
4. 现在6.10.0版本已经加回了prompt
5. 所以求求umi升级到6.10吧 在这磕头了
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by fz6m** [comment]
See #11011
