### ISSUE TITLE
引入tailwindcss导致antd样式失效

### ISSUE THREAD

**Issue by strongyc** [umijs/umi#11023]
## What happens?

引入tailwindcss导致antd样式失效，按钮变成白色无显示
![image](https://user-images.githubusercontent.com/51156342/233826295-a795aa47-1d91-43db-854f-807a69448734.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
See https://github.com/umijs/umi/issues/10599#issuecomment-1443657062
