### ISSUE TITLE
[Bug] locale antd 类型修正

### ISSUE THREAD

**Issue by fz6m** [umijs/umi#11029]
### 问题

locale 生成的代码中，`antd` 类型和文档中的 case 对不上。

代码中：

https://github.com/umijs/umi/blob/662b16a7e754d58df1f4eab0b5907c206337a0ff/packages/plugins/templates/locale/localeExports.tpl#L71-L84

[文档](https://umijs.org/docs/max/i18n#addlocale-%E5%8A%A8%E6%80%81%E6%B7%BB%E5%8A%A0%E5%A4%9A%E8%AF%AD%E8%A8%80%E6%94%AF%E6%8C%81) 中：

```ts
import { addLocale } from 'umi';
import zhTW from 'antd/es/locale/zh_TW';
 
addLocale(
  'zh-TW',
  {
    welcome: '歡迎光臨 Umi 的世界！',
  },
  {
    momentLocale: 'zh-tw',
    antd: zhTW,
  },
);
```

### 解决

以文档为基准，修正 `string` 为 `import('antd/es/locale').Locale` 。

### 其他

认领请回复认领防止冲突。

**Comment by mysteryven** [comment]
认领，预计今天晚上或者明天做一下
