### ISSUE TITLE
[Feature Request] 请问哪里能编写最先的异步逻辑吗，可阻塞后续执行的那种

### ISSUE THREAD

**Issue by CaanDoll** [umijs/umi#11027]
## Background

使用远程接口获取配置，在app.ts里就会用到相关配置了。getInitialState不满足，他是在app.ts里声明的
## Proposal

是否能在global.ts中支持异步回调后再执行app.ts

**Comment by fz6m** [comment]
不一定非要在 `app.ts` 里用上，只要你展示 loading ，在数据准备好再渲染应用就不会有问题，从而你的数据获取时机有很多选择。

几个推荐的时机，[render](https://umijs.org/docs/api/runtime-config#renderoldrender-function) 开始的时候，getInitialState ，或者全局 `layouts/index.tsx` 。

**Comment by CaanDoll** [comment]
可是我qiankun的配置里需要远程数据支持 qiankun配置又只能在app.ts里配

**Comment by CaanDoll** [comment]
https://github.com/CaanDoll/umi-report/tree/main
这里我打印了几个值，可以看到models居然最先执行，其次是qiankun函数，最后才是getInitialState。那getInitialState就不是最先执行的函数。。就无法达到在这里获取配置的能力
![image](https://user-images.githubusercontent.com/23540471/234778291-dbedc45c-92be-49bc-8f4c-0702964f4f3d.png)

**Comment by fz6m** [comment]
昂，这是个异步函数，阻塞住去加载配置就行：

```ts

const sleep = (time: number) => new Promise((resolve) => setTimeout(resolve, time));

export const qiankun = async ()=>{
  await sleep(2000); // 模拟加载配置
  return {
    apps: [],
  }
}
```

**Comment by CaanDoll** [comment]
问题不是这个呀 问题是这几个执行顺序的问题，getInitialState在qiankun、models之后，这不符合他的名字呀

**Comment by fz6m** [comment]
state 指的是 react 里的 state ，qiankun 是用来加载运行时配置的，配置永远是最先加载的，加载完配置才开始渲染，渲染启动应用，开始初始化 react state 。
