### ISSUE TITLE
MicroAppWithMemoHistory 无了？

### ISSUE THREAD

**Issue by xuguanqun** [umijs/umi#11037]
```tsx
import { MicroAppWithMemoHistory } from '@umijs/max';

MicroAppWithMemoHistory undefined
```
"@umijs/max": "^4.0.66"

**Comment by fz6m** [comment]
有的，开启 qiankun.master 后才有，参考文档 [MicroAppWithMemoHistory](https://umijs.org/docs/max/micro-frontend#microappwithmemohistory--%E7%BB%84%E4%BB%B6%E5%BC%95%E5%85%A5%E5%AD%90%E5%BA%94%E7%94%A8) 。
