### ISSUE TITLE
[Bug] "@umijs/mfsu": "^4.0.66" 不支持 webpack: 4.46

### ISSUE THREAD

**Issue by bqxu** [umijs/umi#11036]
##  单独 "@umijs/mfsu": "^4.0.66" 不支持 webpack: 4.46

```shell 
TypeError: import_webpack.util.cleverMerge is not a function
```

## Context

webpack 4.x 的util 就提供 cleverMerge， 官方文件不支持的话，建议也更新一下。不要误导大家。

**Comment by fz6m** [comment]
umi 4 默认最低使用 webpack 5 ，如有 webpack 5 问题，可以提供一个最小复现。
