### ISSUE TITLE
Module '"@umijs/max"' has no exported member 'useModel'.ts(2305)

### ISSUE THREAD

**Issue by he1237596** [umijs/umi#11044]
## What happens?

Module '"@umijs/max"' has no exported member 'useModel'.ts(2305)
按照umi3的官方文档内拉取antd-pro模板完成，启动项目OK，各功能正常，但是eslint有警告，Module '"@umijs/max"' has no exported member 'useModel'.ts(2305)

![image](https://user-images.githubusercontent.com/28428495/234490736-7f98d9a6-f5be-49a8-a72a-39404d906102.png)
![image](https://user-images.githubusercontent.com/28428495/234490814-5c50a68b-5fa5-42ba-9bf4-eb223626dc2d.png)

**Comment by CyberQin** [comment]
另外，如果复制项目的时候，把src/.umi也复制过去了的话，在新项目里也会报这个，因为model在.umi是用的绝对路径，不是相对路径，导致新项目路径指向错误。请清理.umi和.umi-production两个文件夹，再max setup。
