### ISSUE TITLE
[Bug] app.jsx 配置的render 和onRouteChang 执行顺序？？

### ISSUE THREAD

**Issue by Xujalg** [umijs/umi#11043]
## What happens?

我会在render 里面设置  session 但会偶发性的设置不成功  但onRouteChang  一定成功的是为什么？ 如何修改这个问题是 

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
export function onRouteChange({ location, routes, action }) {
    // 存一下上个页面的唯一标识
    storage.session.get('accessId') && storage.session.set('oldAccessId', storage.session.get('accessId'));
    // 存一下当前页面的标识
    storage.session.set('accessId', guid());
    storage.session.set('test', 'test');
}
export function render(oldRender) {
    console.log('render函数执行了')

    storage.session.set('xjltest2', 'xjltest2');
}
## Context

- **Umi Version**: 3.5.35
- **Node Version**: v16.18.0
- **Platform**: pc

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4

**Comment by Xujalg** [comment]
> umi 3 不维护了，建议升级到 umi 4
所以请问 是umi3 引起的这个问题吗？ 我很想知道这个原因是什么😀
