### ISSUE TITLE
在运行时配置 antd 模块中使用 useModel('@@initialState') 报错 

### ISSUE THREAD

**Issue by KuangPF** [umijs/umi#11042]
## What happens?
在配置 antd 运行时配置中，使用 `useModel('@@initialState')` 获取 `initialState`，程序抛出以下错误：

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/20694238/234333468-b1bfc70f-7ef4-4296-adf6-1d99f6aa3e10.png">

## Mini Showcase Repository(REQUIRED)
https://github.com/umijs/umi/tree/master/packages/create-umi/templates/max
```sh
$ npx create-umi@latest
? Pick Umi App Template › - Use arrow-keys. Return to submit.
    Simple App
❯   Ant Design Pro
    Vue Simple App
```
使用官网提供的 @umijs/max 脚手架即可复现该问题。

## How To Reproduce
在运行时配置 antd 中使用 `useModel('@@initialState')`
```tsx
export const antd = (memo) => {
  const { initialState } = useModel('@@initialState');
  return memo;
};
```
## Context

- **Umi Version**: 4.0.66
- **Node Version**: 18.12.1
- **Platform**: macOS 13.2

**Comment by fz6m** [comment]
这个地方是函数，不是 hooks ，名字就能看得出来不是 use 开头的，所以不能用 react hooks 。

**Comment by KuangPF** [comment]
但为啥像 layout 里面就可以使用 use Model 呢

**Comment by fz6m** [comment]
只要是 react 组件内就可以用 hooks ，这里只是一个初始化函数，不是 react 组件。
