### ISSUE TITLE
[Bug] Umi3 升级 Umi4(umi/max) 后 getLocale报错

### ISSUE THREAD

**Issue by SneakerHD** [umijs/umi#11057]
## [Bug] Umi3 升级 Umi4(umi/max) 后 getLocale报错

umi + @umijs/preset-react 组合开发 升级到umi4后，发现getLocale()报错 `ypeError: Cannot read properties of undefined (reading 'applyPlugins')`，无法正确获取本地设置的多语言信息

参考官网升级 https://umijs.org/docs/introduce/upgrade-to-umi-4
## Mini Showcase Repository(REQUIRED)

```
import {
  setLocale, getAllLocales, getLocale, addLocale,
} from 'umi';

getLocale()
```

## How To Reproduce

**@umijs/max:** "^4.0.0".

**Node ** "v16.15.0".

**Comment by fz6m** [comment]
umi 4 里分两种，`umi` 是没有任何插件的，`max` 是有一堆内置插件的，这个场合你应该用 `@umijs/max` ，把以前的 `umi` 依赖卸载了，安装最新的 `@umijs/max` 。

然后保证 `locale: {}` 是打开的，就有 i18n 功能了。

以前的 `@umijs/preset-xxx` 可以卸载掉，现在都内置不需要了。

导入的时候从 `@umijs/max` 导入方法使用。

可以初始化一个 max (脚手架选 antpro) 项目对比着迁移。

如还有问题，需要提供一个最小复现。
