### ISSUE TITLE
[Bug] mix路由重定向问题

### ISSUE THREAD

**Issue by INTKILOW** [umijs/umi#11056]
umijs max 中 
app.tsx设置
    breadcrumbRender: false,
    layout: 'mix',
    fixedHeader: true,
    splitMenus: true,
    fixSiderbar: true,

umirc.ts 路由配置设置

  routes: [
    {
      path: '/',
      redirect: '/home',
    },
    {
      path: '/home',
      component: './Home',
    },

    {
      path: '/system',
      routes: [
        {
          path: '/system/menus',
          component: './System/Menus',
        },
        {
          path: '/system',
          redirect:'/system/menus'
        },
      ],
    },
  ],
这样设置，第一次我我在home 上，点击上面的菜单能/system->定向到/system/menus，然后在切换到home，再点system就不能重定向到/system/menus了，我该怎么配置才行？？

**Comment by fz6m** [comment]
需要给一个最小复现。

**Comment by seanlsr** [comment]
> 

![image](https://github.com/umijs/umi/assets/34623428/d1f1615f-474f-4bfb-b6bc-1dfdf80c3b82)
@fz6m

**Comment by fz6m** [comment]
需要给一个代码仓库的最小复现
