### ISSUE TITLE
umi2.0部署问题

### ISSUE THREAD

**Issue by dly667** [umijs/umi#1105]
使用 exportStatic: { },编译后，部署到线上环境。刷新浏览器就会在url中自动添加“/”，导致路由无法匹配。请问大神怎么处理？
![1537348407](https://user-images.githubusercontent.com/26707226/45743856-99864b00-bc2f-11e8-9685-0a60facd390b.png)
![1537348433](https://user-images.githubusercontent.com/26707226/45743858-9c813b80-bc2f-11e8-8138-bc524d98b601.png)
![1537348448](https://user-images.githubusercontent.com/26707226/45743861-9d19d200-bc2f-11e8-9ec4-18da8912de44.png)

**Comment by sorrycc** [comment]
给可重现代码？

**Comment by dly667** [comment]
你好，这是代码。https://github.com/dly667/runscity_github

**Comment by sorrycc** [comment]
![111](https://user-images.githubusercontent.com/35128/46853385-761a7e80-ce30-11e8-952c-4c2191fb4bd1.gif)

抱歉，这么迟才回复。我试了下你的 demo，跑不起来，所以自己建了个例子，但是 1) 刷新页面不会自动带 `/` 后缀 2) 手动输入 `/users/` 也是可以匹配到。

有问题再 reopen 。
