### ISSUE TITLE
Plugin import can't be resolved

### ISSUE THREAD

**Issue by 1067011734** [umijs/umi#1106]
我想在ant-design-pro加载antd-mobile，安装了babel-plugin-import,但提示Plugin import can't be resolved，求助，代码如下：
plugins: [
    [
      'umi-plugin-react',
      {
        antd: true,
        dva: {
          hmr: true,
        },
        locale: {
          enable: true, // default false
          default: 'zh-CN', // default zh-CN
          baseNavigator: true, // default true, when it is true, will use `navigator.language` overwrite default
        },
        dynamicImport: {
          loadingComponent: './components/PageLoading/index',
        },
        polyfills: ['ie11'],
        ...(!process.env.TEST && os.platform() === 'darwin'
          ? {
              dll: {
                include: ['dva', 'dva/router', 'dva/saga', 'dva/fetch'],
                exclude: ['@babel/runtime'],
              },
              hardSource: true,
            }
          : {}),
      },
    ],
    ['import', { libraryName: 'antd-mobile', style: 'css' }],
  ],
  define: {
    APP_TYPE: process.env.APP_TYPE || '',
  },

**Comment by leitongda** [comment]
同问

**Comment by dyyliao123** [comment]
有解决吗？
