### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by FishBlanche** [umijs/umi#11060]
"@umijs/plugin-qiankun": "^2.4.2",
"@umijs/plugin-sass": "^1.1.1",
"@umijs/preset-react": "^1.8.0",
"umi": "^3.5.0"
![umi1](https://user-images.githubusercontent.com/19261291/234827178-0a5ced30-891f-4fb7-8a77-f6eccf7dd472.png)

![umi2](https://user-images.githubusercontent.com/19261291/234826983-89ba9537-1cfb-48c5-91ed-837728021129.png)
56e57283b5.png)

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4
