### ISSUE TITLE
关于编译部署

### ISSUE THREAD

**Issue by SimpleFun** [umijs/umi#1107]
由于项目页面非常多，开发完成后页面数量应该在 **5000** 个左右，启动、修改代码后加载时间都非常的久，并且还会出现内存溢出无法启动的现象，有没有大神有相关的解决方案？？？？

**Comment by sorrycc** [comment]
方便把项目发我看下？比较感兴趣 5000 个页面是什么样的。

**Comment by SimpleFun** [comment]
是一个业务管理系统，代码拷贝不出来，并且目前正在开发中，页面数量还没那么多。能不能告知一下怎么去实现这个按需编译？另外我申请加入钉钉群，还在微信加了您好友，能否通过一下，谢谢^_^!

**Comment by sorrycc** [comment]
umi@2 已经不支持按需编译，因为还没有遇到那么复杂的项目，像 antd-pro 这样的项目，开 dll 和 hardSource 之后二次启动时间只需要 7s。

所以，没有可复现的项目我没法定位问题，应该帮不上你什么。有问题可以再 reopen。

**Comment by leohxj** [comment]
@sorrycc 我看 [Roadmap for 2.x](https://github.com/umijs/umi/issues/1365) 里面又提到将按需编译加回来？到底后面 umi 提供按需编译的功能么，按需编译会有什么副作用么，为什么要去掉，而不是作为默认关闭的特性？
