### ISSUE TITLE
使用约定式路由，如何做重定向呢

### ISSUE THREAD

**Issue by nanianlisao** [umijs/umi#11086]
两个需求
1. 使用约定式路由，如何做重定向， 不希望仅仅因为这个功能就切换到配置路由
2. 假如使用约定式路由的情况下，假如需要根据目录来做打包，可以实现吗？ 比如有个目录是toC、有个是toB， 希望打包时通过环境变量控制究竟打哪些包。（不考虑到使用monorepo的情况下 有办法实现吗）

**Comment by fz6m** [comment]
手动在这个路由里 navigate 就可以，可以用 `useNavigate` ，`history.push` ，[`<Navigate />`](https://reactrouter.com/en/main/components/navigate) 等方式来重定向，这些方法都可以从 `umi` 导入。

第二个问题没明白你的意思，需要给一个最小复现。
