### ISSUE TITLE
[Bug] umi4 添加qiankun报错 Loading chunk vendors-node_modules_umijs_bundler-webpack_client_client_client_js failed

### ISSUE THREAD

**Issue by NiuSailong** [umijs/umi#11081]
## What happens?

使用umi4.0.67版本配置微前端MicroAppWithMemoHistory后会出现
Loading chunk vendors-node_modules_umijs_bundler-webpack_client_client_client_js failed.
错误

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

<img width="971" alt="image" src="https://user-images.githubusercontent.com/48142793/235683542-407b16b9-6e83-417b-bc3d-ba4788a145dc.png">
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/48142793/235683293-e1245f5b-2471-4254-b8bd-7fb3f824cf83.png">
<img width="916" alt="image" src="https://user-images.githubusercontent.com/48142793/235683043-cf0c0e54-8bcc-4ff5-b297-4a3cfbbe9319.png">
<img width="930" alt="image" src="https://user-images.githubusercontent.com/48142793/235684348-84c29c24-3f74-4c0e-b5b6-5ff5f035f1cb.png">

<img width="755" alt="image" src="https://user-images.githubusercontent.com/48142793/235683786-e3a39a5d-fe7f-4890-9db4-f7b97591d649.png">
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/48142793/235683997-a6d36532-1e7a-48d8-80c9-f3eaacd7a269.png">
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/48142793/235684717-886a280d-5d78-4c3e-be03-33714974a262.png">

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

1.单独运行主项目和微前端终端项目都没有问题
2.主项目加上微前端后会报错

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by ztx7051** [comment]
我也遇到同样的问题的，请问大佬解决了么
