### ISSUE TITLE
改进浏览器兼容（Polyfills）方案

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#1108]
## 使用

内置，用户在 `.umirc.js` 里配 `targets`，比如：

```js
targets: {
  chrome: 58,
  ie: 11,
},
```

然后这个配置就用到 polyfills、JS 语法、postcss 。

## 默认 targets

```js
{
  chrome: 49,
  firefox: 45,
  safari: 10,
  edge: 13,
  ios: 10,
}
```

用户配的 targets 会对此进行 merge 而非覆盖。

## 方案

babel

1. 新增 `targets` 配置，https://babeljs.io/docs/en/babel-preset-env#targets
2. `src/pages/.umi/umi.js` 里引入 `@babel/polyfill`
3. `@babel/preset-env` 配 `useBuiltIns: 'entry'`
4. babel 转化时自动引入对应浏览器所需要的 polyfills

misc

1. 有一些额外的补丁，比如 setprototypeof，根据用户配的 `targets` 在 umi 里处理掉
2. deprecated umi-plugin-polyfills
3. deprecated browserslist 配置

**Comment by afc163** [comment]
这个靠谱多了，还可以适应 electron、node 等各种环境。

babel runtime 和 core-js 会自带么？

**Comment by sorrycc** [comment]
@afc163 会。babel-runtime 出包含 helper 方法，通过 useBuiltIns: 'entry' 自动引入针对浏览器的 core-js 补丁。

**Comment by starsoul666** [comment]
targets配置如下；
targets: {
    ie: 11,
    firefox: 52,
  },

firefox不支持Promise#finally方法，polyfill并没有引入finally的polyfill，配置以后还需要手动引入core-js里面的包吗？

**Comment by Valar103769** [comment]
> 

+1

**Comment by helloann** [comment]
umi4

没配置targets，也是不支持Promise#finally方法
