### ISSUE TITLE
[Bug] umi4 添加qiankun报错 Loading chunk vendors-node_modules_umijs_bundler-webpack_client_client_client_js failed

### ISSUE THREAD

**Issue by NiuSailong** [umijs/umi#11080]
## What happens?
使用umi4.0.67版本配置微前端MicroAppWithMemoHistory后会出现
Loading chunk vendors-node_modules_umijs_bundler-webpack_client_client_client_js failed.
错误
单运行主项目和微前端终端项目都没有问题

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

1. 主项目配置
`
<MicroAppWithMemoHistory
        name={'appname'}
        url={'/home'}
      />
`
`
qiankun: {
  master: {
    apps: [
      {
        name: 'appname',
        entry: '//localhost:7001', 
      },
    ],
  },
}
`
2. 微前端
package.json
`
"name": "appname",
`
umirc
`
qiankun: {
    slave: {},
  },
`
**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by IronManSuper** [comment]
请问一下，你解决了吗

**Comment by DroganC** [comment]
目前也是遇到了这个问题 有解决办法吗
