### ISSUE TITLE
[Feature Request] umi各个钩子函数执行的时机问题

### ISSUE THREAD

**Issue by CaanDoll** [umijs/umi#11088]
## Background

https://github.com/umijs/umi/issues/11027 还是这个问题的衍生

## Proposal

models文件执行也在render后执行

## 最小复现
https://github.com/CaanDoll/umi-report/tree/main
可以看到这个顺序，models文件的执行在最开始优于render执行，会让异步配置的初始化很苦恼
![image](https://user-images.githubusercontent.com/23540471/236156572-8bdc9fb7-d3cf-435e-9caf-00443223970a.png)

**Comment by fz6m** [comment]
1. 在这个 `app.ts` 文件里的都是运行时配置，代表了 `配置` ，所以你可以在这里面使用异步函数来异步获取远程的配置。

2. 配置的加载顺序永远是最先的，加载完配置才会开始 render 应用，所以 render 是最后执行的，这是符合预期的。

3. 如果你需要在 render 前获取一些配置，只需在对应的配置函数中异步加载即可，否则请转移到 layout 层去加载这些配置，加载完成后再条件允许渲染，而不是在全局获取。

4. 目前不会调整这些顺序，因为是 Breaking change ，自己调整下加载方案吧。
