### ISSUE TITLE
[Bug] umi 4 使用connectMaster获取不到数据

### ISSUE THREAD

**Issue by NiuSailong** [umijs/umi#11096]
## What happens?

在umi4 中使用MicroAppWithMemoHistory传入globalData到微前端项目，在微前端项目中使用connectMaster接受props，获取到的数据为{0: {}}， 没有拿到golbalData数据。我看umi4自动引入了qiankun-plugin插件，就没有下载单独的npm包。是需要其他配置吗？
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

<img width="692" alt="image" src="https://user-images.githubusercontent.com/48142793/236595743-0348121e-9bf5-47b7-9027-02ceb8a913eb.png">
<img width="566" alt="image" src="https://user-images.githubusercontent.com/48142793/236595837-62a519b6-2333-4207-bfb8-211b4b3fc571.png">
<img width="310" alt="image" src="https://user-images.githubusercontent.com/48142793/236595852-5fd1ecfe-b918-4ad6-b767-41994896ed53.png">

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

1. `<MicroAppWithMemoHistory
       name=''
       url=''
        globalData={{name:'1'}}
      />`
2. `const BasicLauput = (props = {}) => {console.log(props)} export default connectMaster(BasicLayout)`

## Context
- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
没有 `globalData` ，只有 [`globalState`](https://umijs.org/docs/max/micro-frontend#%E4%B8%BB%E5%BA%94%E7%94%A8%E9%80%8F%E4%BC%A0%E6%95%B0%E6%8D%AE) ，需要给一个最小复现。

**Comment by NiuSailong** [comment]
https://github.com/NiuSailong/micro-web.git
https://github.com/NiuSailong/saas-web.git

**Comment by NiuSailong** [comment]
> 没有`globalData`，只有[`globalState`](https://umijs.org/docs/max/micro-frontend#%E4%B8%BB%E5%BA%94%E7%94%A8%E9%80%8F%E4%BC%A0%E6%95%B0%E6%8D%AE)，需要给一个最小的恢复。

https://github.com/NiuSailong/micro-web.git
https://github.com/NiuSailong/saas-web.git

**Comment by fz6m** [comment]
传递数据依赖于 model 数据流，子应用需要开启 `model: {}`

**Comment by NiuSailong** [comment]
> 传送数据依赖于模型数据流，子应用需要开启`model: {}`

当我开启hash设置base之后，运行项目。有办法直接打开base形式的/home页面吗？
当使用默认base: '/'是可以直接进入到/home页面的。

**Comment by fz6m** [comment]
需要提供更详细的上下文描述，给一个最小复现，不太明白你的场景。

**Comment by NiuSailong** [comment]
> 需要提供更详细的上下文字描述，给一个最小的恢复，不太明显你的场景。

还是上面那两个项目。
我在使用默认base的时候启动项目，会默认打开我的重定向路由
但是我不用默认的，我修改了，我用非根目录的情况。我这时候启动项目只能显示一个localhost：8000，连hash路由都看不到，#也没有。
我想在配置base为非根目录的情况下，运行项目启动，也能自动打开我的重定向路由。
我在项目里配置的base："/saas/"，当我启动项目在浏览器打开，希望得到一个：localhost：8000/saas/#/saas/home。不希望只有localhost：8000

**Comment by fz6m** [comment]
目前 hash 路由做不到，可以尝试自己在插件里用 [`api. addBeforeMiddlewares`](https://umijs.org/docs/api/plugin-api#addbeforemiddlewares) 添加一个中间件，在开发时将 `/` 重定向到 base 。
