### ISSUE TITLE
[Bug] umi 4 使用connectMaster获取不到数据

### ISSUE THREAD

**Issue by NiuSailong** [umijs/umi#11098]
## What happens?

在umi4中使用MicroAppWithMemoHistory传入globalData到微前端项目，在微前端项目中使用connectMaster接收props，获取到的数据为{0: {}}，没有拿到golbalData数据。我看umi4自动引入了qiankun-plugin插件，就没有单独下载的npm包。是需要其他配置吗？

## Mini Showcase Repository(REQUIRED)

![image](https://user-images.githubusercontent.com/48142793/236599468-972260e2-ed43-40b3-bba4-4207052fdeeb.png)
![image](https://user-images.githubusercontent.com/48142793/236599471-1e291dda-2631-4765-b1a2-593704729ff8.png)
![image](https://user-images.githubusercontent.com/48142793/236599474-6f4cfa53-3d96-403b-ac81-c6c49091db91.png)

## How To Reproduce

1. `<MicroAppWithMemoHistory name='' url='' globalData={{name:'1'}} />`
2. `const BasicLauput = (props = {}) => {console.log(props)} export default connectMaster(BasicLayout)`

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
See #11096
