### ISSUE TITLE
[ERROR] [plugin esbuildAliasPlugin] Can't resolve /.umi/plugin-model in .umi\plugin-access

### ISSUE THREAD

**Issue by jasonwang1109** [umijs/umi#11092]
从Umi3 升级到 Umi4 出现下面错误，不知道怎么fix，有解决办法吗？

[ERROR] [plugin esbuildAliasPlugin] Can't resolve 'F:/xxx/src/.umi/plugin-model' in 'F:\xxx\src\.umi\plugin-access'

    node_modules/enhanced-resolve/lib/Resolver.js:309:17:
      309 │       const error = new Error("Can't " + message);
          ╵                     ^
This error came from the "onResolve" callback registered here:

    node_modules/@umijs/preset-umi/dist/features/prepare/esbuildPlugins/esbuildAliasPlugin.js:89:16:
      89 │           build.onResolve({ filter: filter2 }, async (args) => {

The plugin "esbuildAliasPlugin" was triggered by this import

    src/.umi/plugin-access/runtime.tsx:6:25:
      6 │ import { useModel } from '@@/plugin-model';
        ╵                          ~~~~~~~~~~~~~~~~~

fatal - Error: Build failed with 1 error:

 errors: [
    {
      detail: [Error],
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: 'esbuildAliasPlugin',
      text: "Can't resolve 'F:/xxx/src/.umi/plugin-model' in 'F:\\xxx\\src\\.umi\\plugin-access'"
    }
  ],

**Comment by fz6m** [comment]
把 `umi` 换成 `@umijs/max` ，因为 umi 4 本身不带任何插件了，而 max 才包含以前那些 access 和 model 插件；另一种方法是安装 `umi` 和 `@umijs/plugins` [手动配置启用](https://umijs.org/docs/guides/use-plugins#%E4%BD%BF%E7%94%A8%E6%8F%92%E4%BB%B6)以前那些插件。

**Comment by curiousbabyMz** [comment]
一样的问题，解决了吗？

**Comment by fz6m** [comment]
如有问题，需要给一个最小复现。

**Comment by Tlionsir** [comment]
在配置文件  .umirc.ts 中配置 modle: {}，即可生成运行时 src/.umi/plugin-model 文件夹，问题解决。

**Comment by Tlionsir** [comment]
> 如有问题，需要给一个最小复现。

[文档需要更新吧。](https://umijs.org/docs/max/access)
export default {
  access: {},
  // access 插件依赖 initial State 所以需要同时开启
  initialState: {},
  // 这两项还同时依赖：
  model: {},
};

**Comment by johnsmithsren** [comment]
umijs的文档简直是烂出天际了，文档多且新旧混合，不要指望文档，靠脑子加这里issue还有点希望，最好就不要升级或者不要用这个umi了，我是没办法，之前入了坑。
umi@4 开宗明义的那句话是最有用的，umi@4 舍弃了暗箱定义，都需要直接配置来开启，我也遇到了上面的问题。
我遇到的流程起因是，从umi@3 升级到umi@4。建议照着升级文档舍弃umi，用max，对那些用了umi 插件的比较友好，例如我。
首先，舍弃umi，照着升级文档去使用@umijs/max，然后umirc中需要配置
  access: {},
  initialState: {},
  model: {},
  locale: {
    baseNavigator: true,
    baseSeparator: '-',
    default: 'zh-CN',
    useLocalStorage: true,
    title: false,
  }

我这边就可以跑了，umi@3的那些插件都可以删掉，max已经集成了插件，只需要配置开启。上面这个报错主要是model:{} 这个配置引起的。如果还有其他问题，就在配置里面加对应的配置，应该就能解决。
