### ISSUE TITLE
[Bug] `RunTimeLayoutConfig` 下面的`ProLayoutProps` 类型都没有了

### ISSUE THREAD

**Issue by mashirozx** [umijs/umi#11095]
## What happens?

`RunTimeLayoutConfig` 下面的`ProLayoutProps ` 都没有了

![image](https://user-images.githubusercontent.com/16148054/236591803-9edbec2f-20e7-4fc1-afd2-9350e8f88c57.png)

## Mini Showcase Repository(REQUIRED)

https://github.com/MashiroArchive/umi-bug-report  **RunTimeLayoutConfig分支**

请看这里的类型，ProLayoutProps的属性都丢失了：

https://github.com/MashiroArchive/umi-bug-report/blob/RunTimeLayoutConfig/src/app.tsx#L59

## How To Reproduce

更新到最新的umi、antd全家桶

运行tsc

我怀疑是这里的问题：https://github.com/umijs/umi/commit/1942b057cf32f751b7b4f81e55a99e6cdf7f0eec#diff-74761255022fc1c438c3fd635f3f79653f5878ef059d22b5e2e4b5dc87ee0f6eR328

cc: @fz6m 

## Context

- **Umi Version**: @umijs/max. 4.0.67
- **Node Version**: v18.16.0
- **Platform**:macos13

**Comment by fz6m** [comment]
使用这个仓库更新到最新的 umi 版本后，没遇到你这个问题。

1. 需要提供更多上下文信息，如包管理器是 pnpm 还是 yarn / npm 等。

2. 检查你的 IDE 版本和对应 TS 引擎的版本，检查 `tsconfig.json` 和工作区位置是否正确。

**Comment by bingwe** [comment]
VS Code不能对 `ProLayoutProps` 类型智能提示，但是能正常运行。@umijs/max版本为 v4.0.68 、node版本为v16.19.1

![image](https://github.com/umijs/umi/assets/24208275/d981ec90-be50-4095-8121-3f3e64073e5b)

**Comment by mashirozx** [comment]
> VS Code不能对 `ProLayoutProps` 类型智能提示，添加属性pure时，在输入过程中不能给出任何提示，但是能正常运行。@umijs/max版本为 v4.0.68 、node版本为v16.19.1
> 
> ![image](https://user-images.githubusercontent.com/24208275/237920968-fdff21aa-4047-40db-9f04-8eb7d1082fc8.png)

是pro-components的问题，layout里面的好多类型变成了 `export declare type`，无法全局declare也无法import

**Comment by bingwe** [comment]
> 



> 

解决方法是降低pro-components版本？目前版本是2.4.14

**Comment by bingwe** [comment]
> > VS Code不能对 `ProLayoutProps` 类型智能提示，添加属性pure时，在输入过程中不能给出任何提示，但是能正常运行。@umijs/max版本为 v4.0.68 、node版本为v16.19.1
> > ![image](https://user-images.githubusercontent.com/24208275/237920968-fdff21aa-4047-40db-9f04-8eb7d1082fc8.png)
> 
> 是pro-components的问题，layout里面的好多类型变成了 `export declare type`，无法全局declare也无法import

`2.3.58` 亲测可以，`2.4.0` 就会出现该问题，目前先把版本定死吧

**Comment by fz6m** [comment]
到 [pro-components](https://github.com/ant-design/pro-components/issues) 反馈一下吧，这个地方类型操作合并嵌套的一层一层的，很容易出问题

**Comment by bingwe** [comment]
> 到 [pro-components](https://github.com/ant-design/pro-components/issues) 反馈一下吧，这个地方类型操作合并嵌套的一层一层的，很容易出问题
新版本 `2.4.15` 已修复
