### ISSUE TITLE
[Feature Request] Umi 中是否可以使用类似 react-snap 这样的预渲染工具；或者有类似的方式实现？

### ISSUE THREAD

**Issue by ruoduan-hub** [umijs/umi#11097]
## Background
- 在 Umi 使用 React 生态的工具 类型“ react-snap ” 等 ,   对网站 SEO预渲染等优化；或者有什么其他技术手段可以实现类似功能呢？

**Comment by fz6m** [comment]
Umi 是 CSR 的 SPA ，同时 `react-snap` 是一个 4 年前非常老旧的方案，目前不推荐使用预渲染等方法 ，这会导致水合节点不一致应用出问题，如有 ssr 场景，推荐使用 nextjs 。
