### ISSUE TITLE
WEBStorm IDEA Cannot  support alias 

### ISSUE THREAD

**Issue by xgj1988** [umijs/umi#1109]
WEBStorm IDEA Cannot  support alias  .
for example :
 import PageHeader from '@/components/PageHeader';

默认别名@是src 目录，但是在webstorm 里面，我其实想用鼠标左键进入这个JS。但是进不去。。而且也没有自动路径提示。

**Comment by wangxingkang** [comment]
这个肯定点不进去啊

**Comment by sorrycc** [comment]
新建 `webpack.config.js`，内容如下：

```
module.exports = {
  resolve: {
    alias: {
      '@': require('path').resolve(__dirname, 'src'),
    },
  },
};
```

**Comment by xgj1988** [comment]
@sorrycc   3Q

**Comment by smithyj** [comment]
@sorrycc @xgj1988 为什么我还是不行

**Comment by xgj1988** [comment]
@smithyj 我现在也不行了，。

**Comment by smithyj** [comment]
@xgj1988 ts 的话得配置下 paths

**Comment by xgj1988** [comment]
@smithyj  你的可以了吗？？你说的ts 是typescript 吗？

**Comment by smithyj** [comment]
可以 但是 css 与 img 引入还是存在问题

**Comment by xgj1988** [comment]
@smithyj  你是怎么做的呢？

**Comment by mgss** [comment]
需要配置webstorm下的preference -> language & frameworks -> javascript -> webpack 路径到更目录下的webpack.config.js

**Comment by wjttzd** [comment]
可以使用vue里的配置文件。路径如下：
项目路径\node_modules\@vue\cli-service\webpack.config.js

**Comment by xgj1988** [comment]
更新到新版本就可以了。。

**Comment by shx996** [comment]
webstorm是没问题的，vscode如何解决？用了几个插件仅仅是能提示路径，但是引入代码毫无提示，点击路径也跳转不了。

**Comment by miaozilong** [comment]
@shx996 vscode自动加载插件 不需要

**Comment by shx996** [comment]
@miaozilong 我是说@路径都不能识别。自动加载插件是什么意思？书写的时候提示插件并且自动引入？这个功能webstorm也有，而且主动引入的路径是替换之后的@，反而vscode只能用相对路径来引入。不知道我是否理解你的意思？

**Comment by xblcity** [comment]
@shx996 老哥你解决了吗？我也是用的Path Intellisense 插件只能提示路径，但是VS Code识别不了，无法跳转

**Comment by shx996** [comment]
@xblcity 没法解决，根本找不到插件。现在vscode和webstorm还是有差距，webstorm这方面不用愁。

**Comment by xblcity** [comment]
@shx996 我的可以用了，需要在package.json同级文件夹新建jsconfig.json文件配置一下，然后重启vs code，[链接](https://stackoverflow.com/questions/47181037/vscode-intellisense-does-not-work-with-webpack-alias)

**Comment by kdyzm** [comment]
> 可以使用vue里的配置文件。路径如下：
> 
> ```
> 项目路径\node_modules\@vue\cli-service\webpack.config.js
> ```

这是正解
