### ISSUE TITLE
ts5中的新版decorators无法正常运行

### ISSUE THREAD

**Issue by WisestCoder** [umijs/umi#11103]
umi新版已经支持ts5，ts5已经支持新版的decorators，但umi内置的babel插件还是老版的decorators。
手动在.umirc中引入新版的decorators插件
```
extraBabelPlugins: [
    ["@babel/plugin-proposal-decorators", { "version": "2023-01" }]
  ]
```
会报错，报错如下：
```
Module build failed (from ./node_modules/@umijs/bundler-webpack/compiled/babel-loader/index.js):
Error: Cannot use the decorators and decorators-legacy plugin together
```

**Comment by fz6m** [comment]
目前没有计划支持官方标配 deco ，和 TS 的 deco 相比十分逊色，不推荐使用。

如有 deco 需求，可以使用 TS 标准的 deco 。

**Comment by WisestCoder** [comment]
@fz6m 我使用的就是TS5.0新出的标准的deco，具体可以看这里：https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#decorators

源码 https://github.com/umijs/umi/blob/master/packages/babel-preset-umi/src/index.ts#L82，这里装饰器的babel插件配置是还是legacy版本

umi配置现在貌似也无法修改umi内置的babelOpts

**Comment by fz6m** [comment]
这里的就是 ecma 标准的官配 deco ，是原 TS deco 的超级阉割版本，功能上没有优势，目前没有计划支持。
