### ISSUE TITLE
devServer自己宕机

### ISSUE THREAD

**Issue by yokyj** [umijs/umi#1110]
[2018-09-21T02_14_35_627Z-debug.log](https://github.com/umijs/umi/files/2403685/2018-09-21T02_14_35_627Z-debug.log)

以上是log文件

基本上umi dev过一两个小时就会挂掉

项目环境是这样搭建的： dva-cli 1.0.0beta  ，然后修改依赖umi的版本到最新，插件改成umi-plugin-react

**Comment by sorrycc** [comment]
`umi dev` 不是给生成用的，你用这个来跑服务？

**Comment by yokyj** [comment]
没有啊，就只是作开发环境

**Comment by sorrycc** [comment]
这个问题比较难排查，日志看不出问题。。估计和内存泄露，或者一些 webpack 插件没有控制好内存有关。我还没试过一两个小时一直开着。
