### ISSUE TITLE
Umi 4 request 里的form request 怎么做？

### ISSUE THREAD

**Issue by jasonwang1109** [umijs/umi#11100]
umi-request 针对 requestType 为 'form' 时，通过 qs.stringify 对 options.data 进行默认处理。

Umi 4 有类似的功能吗？

**Comment by fz6m** [comment]
现代数据流更推荐自己封装 axios 或 fetch 作为底层请求库，上层用 [react-query](https://umijs.org/docs/max/react-query) ，不再推荐使用 umi request 、use request 等方案。
