### ISSUE TITLE
[Bug] umi@4.0.67版本window.publicPath失效

### ISSUE THREAD

**Issue by 7ingning** [umijs/umi#11101]
## What happens?

umi@4.0.67版本window.publicPath失效

## Mini Showcase Repository(REQUIRED)

在.umirc文件配置publicPath值
用4.0.67版本build，控制台输出window.publicPath返回undefined
![image](https://user-images.githubusercontent.com/131357495/236613627-9b60bd02-b6f4-4bc2-b511-d9b60b5e2866.png)
用4.0.64版本build，控制台输出window.publicPath返回正确的值
![8d4c36c08d881efd0649ff0f3294c70c](https://user-images.githubusercontent.com/131357495/236613707-b8b80b82-0fdc-4532-b013-a19119d71dd0.png)

## How To Reproduce

在.umirc文件配置publicPath值
用4.0.67版本build，控制台输出window.publicPath返回undefined
![image](https://user-images.githubusercontent.com/131357495/236613627-9b60bd02-b6f4-4bc2-b511-d9b60b5e2866.png)

## Context

- **Umi Version**: 4.0.67
- **Node Version**: 16.16.0
- **Platform**: chrome

**Comment by fz6m** [comment]
`publicPath` 这个全局的值一般和 qiankun 主子应用有关，这需要主应用挂载子应用通过 `runtimePublicPath` 接收，是 umi qiankun 插件的一个约定，并不是特性，不建议使用。

如果有在代码中使用 publicPath 的需求，可以通过 `define` 把它注入再用。
