### ISSUE TITLE
请问build项目时如何才能去除代码里面的注释

### ISSUE THREAD

**Issue by XanderXueMingJi** [umijs/umi#1111]
我目前需要打包一个umi没有, 请问如何配置.webpackrc.js, 才能是打包后的文件没有代码注释?

**Comment by sorrycc** [comment]
代码里的注释默认就会去掉的吧，怎么重现？

**Comment by XanderXueMingJi** [comment]
谢谢, 代码里的注释默认是会去掉的, 只是我的问题在项目的根文件里, (用ejs写的html代码)在开发过程中写了点注释, 其实要删除的注释不多, 想保留它

**Comment by sorrycc** [comment]
@XanderXueMingJi 所以是要保留还是删除？给可重现步骤再 reopen 吧。

**Comment by sorrycc** [comment]
@sbyps 可以用 https://babeljs.io/docs/en/next/babel-plugin-transform-remove-console
