### ISSUE TITLE
[Bug] 从umi3升级到umi4后，package.json中配置type='module', .cjs.js文件无法被正确解析

### ISSUE THREAD

**Issue by iwalking11** [umijs/umi#11110]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/iwalking11/umi4-cjs-bug
## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
1.引入@aliyun-sls/web-track-browser包 该包的package.json配置如下： 
![image](https://user-images.githubusercontent.com/14257970/236765735-9ec9fd22-1850-4629-81b4-f7a01c16fb5a.png)

2.项目中通过esm方式引用该包

import SlsTracker from "@aliyun-sls/web-track-browser";
项目启动后浏览器报错：
![image](https://user-images.githubusercontent.com/14257970/236765778-6bc23c0c-a383-466c-805b-4f0816adfb30.png)

删除该包package.json中的type='module'，项目重新启动后可以正常访问。

**Expected behavior** 1. 2.
原则上，.cjs.js后缀的文件应该按照commonjs的规则解析，但是这里被type='module'的优先级覆盖了，按照esm解析了

## Context

- **Umi Version**:4.0.67
- **Node Version**:16
- **Platform**:web

**Comment by fz6m** [comment]
给这个库提一个 PR 修复这个问题，或者用 [`pnpm patch`](https://pnpm.io/cli/patch) 一下这个包的代码先用着。
