### ISSUE TITLE
[umi@2.0.2] Uncaught SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by amily4555** [umijs/umi#1112]
![image](https://user-images.githubusercontent.com/2802841/45866615-fe6aae00-bdb3-11e8-90cb-2b83f254b7c7.png)

![image](https://user-images.githubusercontent.com/2802841/45866669-1c381300-bdb4-11e8-93f7-3123957410ef.png)

- 这个跟我之前提过的 issues 非常类似 #574 
- 在 umi@1.3 之后消失 在 umi@2.0.2 之后又经常出现，时不时，不是一直有

**Comment by sorrycc** [comment]
怎么重现？关闭 hard source 试试？

**Comment by zero1five** [comment]
同样遇到这个问题， "umi": "^2.0.0",  请问是什么原因导致的

**Comment by zero1five** [comment]
"umi"，"umi-plugin-react" 都降到2.0.0-beta 可以解决这个问题

**Comment by tearsofphoenix** [comment]
我的重现方式：
1、在a分支运行umi dev
2、切换项目到另一分支b
3、切换回a分支，此时即出现该bug
a分支与b分支没有项目配置的不同，仅有少量业务组件的差异。
怀疑是切换过程中umi内部缓存被破坏但umi没有识别到该不同，因而再也无法构建出正确的dll.js。
试过上述删除缓存、删除.umi文件、清理系统缓存，甚至升级系统，都无法解决该问题。
系统：macOS 10.14，Node：v8.11.3，npm: 6.1.0

**Comment by tearsofphoenix** [comment]
另一种解决办法：
1、`npm i --save <随便一个什么库>`
2、`npm start`
3、移除刚才安装的库

**Comment by sorrycc** [comment]
是 hard-source-webpack-plugin + webpack@4.9.1 的问题，可以先禁用，参考 https://github.com/mzgoddard/hard-source-webpack-plugin/issues/443

**Comment by amily4555** [comment]
babel cache 应该同时关闭才可以正常使用

**Comment by superlbr** [comment]
从2.1.2升级到2.2，生产环境，出现页面白屏
`Uncaught SyntaxError: Unexpected token <`
吓坏了，赶紧降回去，好了。然后又升回去，也好了，怪了。。。
