### ISSUE TITLE
[Bug] umi4 build部署之后，页面代码里面存在2个root节点和2个script标签

### ISSUE THREAD

**Issue by cescxu0712** [umijs/umi#11129]
## What happens?

umi4 build之后部署到服务器上，打开网址发现index.html里面有2个root节点和2个<script src="/umi.js">，如下面图1
<img width="463" alt="企业微信截图_16837054572640" src="https://github.com/umijs/umi/assets/13554748/f6ae0079-fbf9-4d65-ae3b-6bd9a869ba6b">
但是在build之后dist目录的index.html里面又是只有1个root节点和1个script ，如下面图2
<img width="630" alt="企业微信截图_1683705609705" src="https://github.com/umijs/umi/assets/13554748/0c88baa8-ec89-4639-a86f-5b685a098851">
如果是本地启动的话就是正常的，只有1个root节点和1个script，请问这个是什么原因导致的，nginx的配置也是按照brower来进行的。如下面图3
<img width="469" alt="企业微信截图_16837087642492" src="https://github.com/umijs/umi/assets/13554748/bc96ac49-7070-4e85-8112-30615014fbfd">

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:4.0.67
- **Node Version**:14.21.3
- **Platform**:windows 11

**Comment by fz6m** [comment]
需要给一个最小复现。

**Comment by cescxu0712** [comment]
> 需要给一个最小复现。

抱歉，代码现在无法上传，现在判断下来构建出来的产物是OK的，但是通过站点访问就出了问题，这之间的链路可能问题，服务器使用的NGINX
