### ISSUE TITLE
[Bug] hook组件使用connect之后外部无法识别其props属性

### ISSUE THREAD

**Issue by vannvan** [umijs/umi#11123]
code

## Mini Showcase Repository(REQUIRED)

> 最小可复现仓库 https://github.com/vannvan/umi-demo

## How To Reproduce

![](https://p.ipic.vip/96vxfj.png)

如上图，当组件使用`connect`之后，外部无法识别其props

## Context

- **Umi Version**:  @umijs/max
- **Node Version**: v16.14.2
- **Platform**: Mac

**Comment by fz6m** [comment]
1. dva 太老了，里面没有可以推断的 TS 类型，所以这个地方没有类型。

2. dva 不维护了，不推荐继续使用，现代数据流推荐使用 [react-query](https://umijs.org/docs/max/react-query) 处理请求，[valtio](https://umijs.org/docs/max/valtio) 、[jotai](https://github.com/pmndrs/jotai) 处理全局数据。
