### ISSUE TITLE
Missing class properties transform

### ISSUE THREAD

**Issue by fangbicheng** [umijs/umi#11122]
<img width="795" alt="image" src="https://github.com/umijs/umi/assets/20126429/f4d0debb-2503-4ab2-a1cc-fc89afd0d7c9">
<img width="561" alt="image" src="https://github.com/umijs/umi/assets/20126429/8db90e31-ff51-43c0-9f6e-2514f3ecd9bb">

**Comment by fangbicheng** [comment]
帮忙看下，急

**Comment by fz6m** [comment]
上下文信息太少了，不懂要干啥，需要给一个最小复现。

**Comment by fz6m** [comment]
dumi 的内容到 [dumi](https://github.com/umijs/dumi) 仓库反馈吧。
