### ISSUE TITLE
[Bug] 一个页面权限的bug，access中的函数返回的路由路径不完整

### ISSUE THREAD

**Issue by Lands-1203** [umijs/umi#11139]
在access.ts文件中，返回的路由地址只有一半，比如我有一个页面的地址是/business/repayment，但是在页面权限判断的函数上返回的是repayment，这样就导致我没办法判断用户是否存在这个页面的权限。（不能使用只判断一半的方式）
另外，如果在路由上，都写完整的路径是这个函数返回的就是完整的路径，像下面这样写树形，权限判断的函数里面就是不完整的。
在umi3中是没有这个问题的，之前的umi3做的项目没有这个问题，umijs@max有这个问题
![image](https://github.com/umijs/umi/assets/61341868/7d478098-4afe-4b57-b449-ebe1488d40dc)
![image](https://github.com/umijs/umi/assets/61341868/8ba42944-2006-437b-a989-778e69aed055)

**Comment by fz6m** [comment]
是原模原样传递的，如果判断依据不够，可以用其他的属性判断或者添加其他的标识键，都会传递过来的。
