### ISSUE TITLE
[Bug] index.js:1 [import-html-entry]: error occurs while executing normal script http://localhost:9000/commonService

### ISSUE THREAD

**Issue by jlv-xjtu** [umijs/umi#11149]
报错位置：
(function(){;with(window.proxy){(function(Array,ArrayBuffer,Boolean,constructor,DataView,Date,decodeURI,decodeURIComponent,encodeURI,encodeURIComponent,Error,escape,EvalError,Float32Array,Float64Array,Function,hasOwnProperty,Infinity,Int16Array,Int32Array,Int8Array,isFinite,isNaN,isPrototypeOf,JSON,Map,Math,NaN,Number,Object,parseFloat,parseInt,Promise,propertyIsEnumerable,Proxy,RangeError,ReferenceError,Reflect,RegExp,Set,String,Symbol,SyntaxError,toLocaleString,toString,TypeError,Uint16Array,Uint32Array,Uint8Array,Uint8ClampedArray,undefined,unescape,URIError,valueOf,WeakMap,WeakSet,window,self,globalThis,requestAnimationFrame){;<!DOCTYPE html><html><head>

<!D 这个地方哦

mf: {
    shared,
    remotes: [
      {
        name: 'common',
        entry: '/commonService',
      },
    ],
  },

proxy:
'/commonService/': {
      target: 'A', 
      pathRewrite: { '^/commonService': '' },
      changeOrigin: true,
    },

远程共享仓库common 使用无误，在主应用引用过
在qiankun子应用使用报错：
报错1
index.js:1 [import-html-entry]: error occurs while executing normal script http://localhost:9000/commonService
报错2
Uncaught SyntaxError: Unexpected token '<' (at commonService:1:640)
    at eval (<anonymous>)
    at evalCode (mf-dep____vendor.06961f5c.async.js:165126:31)
    at geval (mf-dep____vendor.06961f5c.async.js:164490:55)
    at exec (mf-dep____vendor.06961f5c.async.js:164519:13)
    at schedule (mf-dep____vendor.06961f5c.async.js:164545:9)
    at mf-dep____vendor.06961f5c.async.js:164556:14
    at new Promise (<anonymous>)
    at mf-dep____vendor.06961f5c.async.js:164555:12
## Context

- **Umi Version**: 4.0.59
- **Node Version**: 16.6.0
- **Platform**: web

**Comment by fz6m** [comment]
需要给一个最小复现
