### ISSUE TITLE
[Bug] when i use Vite on dev, the chorme devtools thorw a err:caught SyntaxError: The requested module '/node_modules/.pnpm/invariant@2.2.4/node_modules/invariant/browser.js?v=cebd3f47' does not provide an export named 'default' (at index.module.js?v=cebd3f47:1:459)

### ISSUE THREAD

**Issue by d602221169** [umijs/umi#11158]
## What happens?

I create a umi max with pnpm,when i use vite on dev, the chorme devtools throw a error:(caught SyntaxError: The requested module '/node_modules/.pnpm/invariant@2.2.4/node_modules/invariant/browser.js?v=cebd3f47' does not provide an export named 'default' (at index.module.js?v=cebd3f47:1:459))
## Mini Showcase Repository(REQUIRED)

create step: pnpm dlx create-umi@latest → ant design pro→pnpm →taobao
setting: just add "vite:{}"to"umirc.ts"
my env:
windows11
chrome112.0.5615.50
node16.15.0
umijs/max 4.0.69

**Comment by fz6m** [comment]
duplicate #10212

现在 vite 模式还不支持 windows 使用
