### ISSUE TITLE
[Bug] qiankun子应用，app.tsx入口配置getInitialState导致子应用无法加载

### ISSUE THREAD

**Issue by Minya01** [umijs/umi#11153]
当前项目为qiankun html entry方式的子应用。
在项目中的入口文件app.tsx配置getInitialState：
```ts
export async function getInitialState(): Promise<{
  currentUser?: API.CurrentUser;
}> {
  const ticket = getUrlParam('ticket');
  if (ticket) {
    setTicket(ticket);
  }
  const fetchUserInfo = async () => {
    let res: any = { result: { username: '' } };
    // TODO: 如果有需要，需要从主应用传参到子应用
    if (!isQianKun) {
      try {
        let sessionId = getSessionId();
        if (!sessionId) {
          const ret = await apiGetSessionId();
          sessionId = ret.result;
        }
        setSessionId(sessionId);
        res = await queryCurrentUser();
      } catch (error) {
        console.log(error);
      }
    }
    return res.result;
  };
  const currentUser = await fetchUserInfo();
  return {
    currentUser,
  };
}
```

问题：
1、配置getInitialState函数后在主应用中无法加载子应用，注释掉getInitialState函数后可以正常加载。
2、直接打开子应用链接，可以正常使用getInitialState函数，无报错。
3、"umi": "^3.5.0",也无此问题。

![image](https://github.com/umijs/umi/assets/19857248/3bdc73ba-8926-4a69-9283-e876107a02e0)
## Context

- **Umi Version**: "@umijs/max": "^4.0.33"
- **Node Version**: v16.13.2
- **Platform**: Mac nginx/docker nginx

**Comment by fz6m** [comment]
是可以都使用的，如果有有问题，需要给一个最小复现。

**Comment by Minya01** [comment]
配置COMPRESS=none，不会有问题。去掉这个配置就会报错。

**Comment by Minya01** [comment]
找到原因了，非常感谢

**Comment by Minya01** [comment]
测试发现，在getInitialState函数里，发起request请求，requst不直接使用import { request } from '@umijs/max'，而是使用umi-request就会出现这个问题。
