### ISSUE TITLE
[Bug] umi/max中，在.umirc.ts文件中启用antd，并添加configProvider相关配置，启动项目会报错

### ISSUE THREAD

**Issue by 18310880751** [umijs/umi#11156]
## What happens?

umi/max中，在.umirc.ts文件中启用antd，并添加configProvider相关配置，启动项目会报错
![1684395096059](https://github.com/umijs/umi/assets/41846153/dd321cd0-4bfb-4caf-bb1c-0a5ea7016461)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
https://github.com/18310880751/max.git

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

直接启动，就可以看到相关错误了

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
提供的复现仓库不存在

**Comment by xiaohuoni** [comment]
@stormslowly cc

**Comment by spt110** [comment]
> 提供的复现仓库不存在
https://github.com/umijs/umi/issues/9522   
在这里找到的解决方案，新版本没有解决

**Comment by 18310880751** [comment]
> 提供的复现仓库不存在

https://github.com/18310880751/max.git  这个直接运行应该就能复现

**Comment by fz6m** [comment]
需要提供一个会报错的最小复现仓库，帮助排查问题。

上面给出的仓库链接打开是空的。

**Comment by 18310880751** [comment]
> 需要提供一个会报错的最小复现仓库，帮助排查问题。
> 
> 上面给出的仓库链接打开是空的。

忘记将库公开了，现在应该能看到了

**Comment by fz6m** [comment]
这里从 antd 导入的 `theme` 本质上是函数，没法在纯静态的 `.umirc.ts` 配置里使用，动态的内容可以在运行时配置修改，参考：[运行时配置](https://umijs.org/docs/max/antd#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE)

这里感觉可以检测下，如果用户配了 `configProvider.theme` 最好提示下应该在运行时配置， cc @xiaohuoni

**Comment by xiaohuoni** [comment]
@fz6m 只有引用了 antd 才会有异常，在这里可以配置常规的静态数据，感觉，antd@5 相关配置，都转到运行时配置就好。
