### ISSUE TITLE
[Bug] umi4  打包 导致部分代码没有编译 ES5的代码 ，导致低版本游览器不能正常运行

### ISSUE THREAD

**Issue by lei14370** [umijs/umi#11165]
## What happens?
<img width="583" alt="image" src="https://github.com/umijs/umi/assets/24383279/9d85e36e-553a-4308-adc1-73a3948a0c78">

## Mini Showcase Repository(REQUIRED)
<img width="679" alt="image" src="https://github.com/umijs/umi/assets/24383279/9cd5e897-b289-494a-9bef-68d09831a8a0">
具体问题 就是 @umijs/preset-umi 的devToolAppDist/umi.js 的代码不会编译，导致低版本游览器不能正常运行
> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
umi 4 默认打包产物支持现代浏览器，如需兼容请查看：[非现代浏览器兼容](https://umijs.org/blog/legacy-browser)
