### ISSUE TITLE
[Bug] 关于 favicons 默认站点图标的去除？

### ISSUE THREAD

**Issue by JSQ180** [umijs/umi#11178]
## 关于 favicons 默认站点图标的去除？

官方文档对于 `favicons` 的描述如下
![image](https://github.com/umijs/umi/assets/112090173/dcbe9ef0-58c0-431f-ad7b-8106b2132fbb)

编辑器显示 favicons 可选参数如下：
![image](https://github.com/umijs/umi/assets/112090173/d5ef830f-6ef1-4300-b0c1-9bffecf6b2d8)

当我尝试设置 favicons 为 undefined | false 时，站点默认图标并未去除。  
若仅去除默认站点图标，而不添加新图标进行替代，则应该如何设置？

## Context

- **4.0.68**:
- **18.16.0**:
- **Goolgle**:

**Comment by fz6m** [comment]
如果你没配置 `favicons` 也没有约定的 `src/favicons.ico` 文件，在开发时默认会显示 umi 的 logo ，构建完的 html 里是不会有任何 favicons 的 head 的。
