### ISSUE TITLE
这个区域我使用actionsRender：false不生效

### ISSUE THREAD

**Issue by LiuChang0725** [umijs/umi#11170]
### Discussed in https://github.com/umijs/umi/discussions/11168

<div type='discussions-op-text'>

<sup>Originally posted by **LiuChang0725** May 19, 2023</sup>
getInitialState我看只能去掉名字，我看链接文档上没有说明，或者怎么去掉这整个区域
![image](https://github.com/umijs/umi/assets/37528714/155f39d5-4cf4-498d-bdbf-7b016e0d41b7)
</div>

**Comment by fz6m** [comment]
See #11168

**Comment by LiuChang0725** [comment]
请看我的评论： https://github.com/umijs/umi/discussions/11168
