### ISSUE TITLE
tsconfig.json 中 `moduleResolution` 的值是错的

### ISSUE THREAD

**Issue by dream2023** [umijs/umi#11174]
官方命令初始化后：

![image](https://github.com/umijs/umi/assets/19297757/4306ed9b-38d9-4727-a0e4-70492d4b7099)

出错原因：

![image](https://github.com/umijs/umi/assets/19297757/9228e9a1-2669-47da-a0f2-fc046a912db4)

官方文档中并没有这个值：

![image](https://github.com/umijs/umi/assets/19297757/2ac36d9b-42e4-42bf-9ca7-89168c32a09b)

当我改为这个值，就好了：

![image](https://github.com/umijs/umi/assets/19297757/d28434c4-c46a-45c5-944a-47e5973bc1d2)

![image](https://github.com/umijs/umi/assets/19297757/4f5fe4c7-e298-4dda-8b41-abe212c0b5f1)

**Comment by fz6m** [comment]
项目的 TS 版本是 v5 ，但是 vscode 使用的引擎版本是旧版本。

解决方法：升级 vscode 版本或者配置使用当前项目的 TS 作为 IDE 引擎
