### ISSUE TITLE
刷新页面导致父级路由重复渲染

### ISSUE THREAD

**Issue by puhanjie** [umijs/umi#11187]
## What happens?

路由嵌套时候，刷新页面会让父级的路由组件都重复渲染，如下图，我在该路由路径上执行刷新页面后，控制台输出一下路由组件的执行情况，但是我预期的是右边红字部分的输出结果，请问这是bug还是react自身的一个特性呢？
![image](https://github.com/umijs/umi/assets/43885789/9b4c9142-486d-4788-bc93-821571085a1b)

## Mini Showcase Repository(REQUIRED)

>  [最小重现](https://github.com/puhanjie/umi-test)（https://github.com/puhanjie/umi-test）

1.执行 pnpm install 安装依赖
2.执行 pnpm dev 启动项目
3.地址栏输入：http://[localhost:8000/docs/test](http://localhost:8000/docs/test)，访问应用，然后再执行刷新页面，就会输出如上图所示的结果

## Context

- **Umi Version**: 4.0.69
- **Node Version**: 18.16.0

**Comment by fz6m** [comment]
`<Outlet />` 渲染嵌套子路由的时候会触发重渲染，所以 Layout 会执行一次，这是预期的。

**Comment by fz6m** [comment]
由于 umi 提供了各种快捷的能力，如 react router v6 没有的外置 history ，约定式的 layout ，约定式路由，一键开关插件等，所以内部大量代码来提供这些快捷能力便于快速的启动开发一个项目，最终的结果是层级嵌套的很深，我们没法保证组件的渲染次数严格符合 预想中 的那样，会产生多次渲染是正常的；由于现代浏览器已经足够快，react 性能也足够好，使用 react 的群体也足够足够大，所以重渲染几次不是问题。
