### ISSUE TITLE
umijs 如何 使用nprogress 

### ISSUE THREAD

**Issue by xgj1988** [umijs/umi#1118]
以前用dva可以这么使用。
import React from 'react';
import { connect } from 'dva';
import NProgress from 'nprogress';

const App= ({ app, loading }) => {

    let currHref = '';
    const href = window.location.href;    // 浏览器地址栏中地址
    if (currHref !== href) {  // currHref 和 href 不一致时说明进行了页面跳转
        NProgress.start();    // 页面开始加载时调用 start 方法
        if (!loading.global) {  // loading.global 为 false 时表示加载完毕
            NProgress.done();  // 页面请求完毕时调用 done 方法
            currHref = href;   // 将新页面的 href 值赋值给 currHref
        }
    }
        
}

但是因为umijs 和dva整合之后，上面那个代码都不需要了。。那么如何使用呢？

**Comment by sorrycc** [comment]
还是以前那样用，umi + dva 只是把 model 注册部分约定化了，其他不变。

**Comment by jinjinwa** [comment]
> 还是以前那样用，umi + dva 只是把 model 注册部分约定化了，其他不变。

请问下，这段代码应该写在哪里？ umi现在只有src/app.js , export 一个config对象

**Comment by jinjinwa** [comment]
没事了。研究了一下，写在layout／xxx 里面，解决了。嘻嘻

**Comment by xgj1988** [comment]
@jinjinwa  代码贴出来一下撒。。或则私聊我一下。。

**Comment by jinjinwa** [comment]
> @jinjinwa 代码贴出来一下撒。。或则私聊我一下。。

https://github.com/jinjinwa/umi-antd-mobile/blob/master/src/layouts/BasicLayout.js
可参考下我的项目

**Comment by xgj1988** [comment]
@jinjinwa  OK.,但是我觉得你应该把currHref写成 BasicLayout的属性。this.currHref= '';
