### ISSUE TITLE
umi4.0.24版本以后使用qiankun嵌入微应用拉取到资源但是主应用菜单下未渲染waringindex.js:42  because it does not start with the basename, so the <Router> won't render anything.

### ISSUE THREAD

**Issue by AloneZL** [umijs/umi#11185]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.
[](url)

umi4.0.24版本以后使用qiankun嵌入微应用拉取到资源但是主应用菜单下未渲染

![image](https://github.com/umijs/umi/assets/49380865/ffa97891-f4bc-497f-a721-9c04deed5d24)
![image](https://github.com/umijs/umi/assets/49380865/5012876a-cbf5-4042-ac17-8bbb8b0acea3)
![image](https://github.com/umijs/umi/assets/49380865/e6a1b675-d858-433d-8db3-2c2463532b35)
![image](https://github.com/umijs/umi/assets/49380865/5b6c7ce6-196d-4a50-9a68-06bee9872b92)

## Context

- **Umi Version**:>4.0.24
- **Node Version**:v14.21.3
- **Platform**:

**Comment by fz6m** [comment]
需要给一个最小复现仓库链接。
