### ISSUE TITLE
[Bug] request 提交formData 数据时，Content-Type 自动指定为multipart/form-data;

### ISSUE THREAD

**Issue by liukefu2050** [umijs/umi#11193]
如下代码提交登陆表单，获取后台token

```
export async function login(body: API.LoginParams, options?: { [key: string]: any }) {

  const formData = new FormData();
  formData.append('username', body.username||"");
  formData.append('password', body.password||"");
  formData.append('grant_type', body.grant_type);
  formData.append('tenantId', body.tenantId);

  return request<API.LoginResult>('/auth/oauth2/token', {
    method: 'POST',
    headers: {
      Authorization: 'Basic OTVUeFNzVFBGQTN0RjEyVEJTTW1VVkswZGE6RnBId0lmdzR3WTkyZE8=',
      'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
    },
    //requestType: 'form',
    data: formData,
    ...(options || {}),
  });
}
```
请求中指定Content-Type ，并不会起作用，Content-Type会自动指定为multipart/form-data 类型。然而后台接口却只支持application/x-www-form-urlencoded;

同时，加上requestType: 'form', 一句，同样Content-Type 没有改变
@umijs/max 切换到最新版本，问题依然存在。

依赖版本号：
    "@umijs/fabric": "^2.14.1",
    "@umijs/lint": "^4.0.52",
    "@umijs/max": "^4.0.59",

请问这种情况下，我如何改变Content-Type 到 application/x-www-form-urlencoded
（已征求后台，后台不方便改成multipart/form-data 或json格式 ）

谢谢~

重现步骤：

# use npm
npm i @ant-design/pro-cli -g
pro create myapp

Select the version of umi

🐂 Use umi@4 or umi@3 ? (use arrow keys)
❯ umi@4 
选择umi 4
修改登陆接口

**Comment by fz6m** [comment]
目前不建议使用 request / use request 旧方案了。

更建议使用现代的数据流方案：使用 [valtio](https://umijs.org/docs/max/valtio) / [jotai](https://github.com/pmndrs/jotai) 管理全局数据、自己维护 axios / fetch 请求底层 + [react-query](https://umijs.org/docs/max/react-query) 做请求状态管理。
