### ISSUE TITLE
[Bug] umi4打包拆分的js都在head里了，能否像umi3那样放到body里？

### ISSUE THREAD

**Issue by Vantown** [umijs/umi#11190]
## What happens?

umi4通过splitChunk拆分出来的js全到head里了

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

git仓库地址https://codesandbox.io/s/jsx-feng-ge-de-api-antd-5-5-1-forked-gbvbe6

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

用这个配置打包就会把node_module里的都打包到head里，只有umi是在body里面，而且用html-webpack-plugin也不生效

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
See #11189

**Comment by Vantown** [comment]
> See #11189

现在我们的应用做的有点大，我把资源都放到body里在umi那附近加载，body开始的地方放个加载动画，这样不会有白屏等待的时间，我们的应用打完包将近10M，等加载完时间有点长了，所以挪到body里加载好一些；有没有什么方式可以控制最终打包出来的资源在html出现的位置呢？
