### ISSUE TITLE
global.less can't work

### ISSUE THREAD

**Issue by dly667** [umijs/umi#112]
creat a new project use umi,when under development  there accures a problem:
Module not found: Can't resolve 'E:BlockChainAdminsrcglobal.less' in 'E:\BlockChainAdmin\src\pages\.umi'

the global.less is auto imported like this,but it can't work successfuly, what  anything else sholud config?
  
import('E:\BlockChainAdmin\src\global.less');

**Comment by sorrycc** [comment]
It's may be a windows path problem.

**Comment by dly667** [comment]
ok了

**Comment by dly667** [comment]
https://github.com/umijs/umi/commit/4ebf004d26efe7b8cc72a60b78f28c8c0646a029

  Update available 1.0.0-rc.5 → 1.0.0-rc.18    │
   │           Run npm i -g umi to update   更新到18就可以了
