### ISSUE TITLE
[Bug] useRequest 无法返回数据

### ISSUE THREAD

**Issue by kaneruan** [umijs/umi#11206]
<img width="648" alt="image" src="https://github.com/umijs/umi/assets/13065289/2ca9f773-1b41-4635-9440-807b475f1358">
version: @umijs/max

**Comment by fz6m** [comment]
在 `useRequest` 里，这个函数行为必须是异步的，这种手写同步是不行的，另外默认从 [`data`](https://umijs.org/docs/max/request#%E6%9E%84%E5%BB%BA%E6%97%B6%E9%85%8D%E7%BD%AE) 中获取，如果你要获取原始返回值，得自己改下配置。

同时，现代数据流更推荐使用 [react-query](https://umijs.org/docs/max/react-query) 管理请求状态，[valtio](https://umijs.org/docs/max/valtio) / [jotai](https://github.com/pmndrs/jotai) 管理全局数据，不推荐 use request 。
