### ISSUE TITLE
[Bug] umi创建新项目，build后发现没有tree-shaking

### ISSUE THREAD

**Issue by nisnaker** [umijs/umi#11205]
问题如题，复现步骤如下：
`yarn create umi` 创建新项目，版本目前最新，4.0.69
```ts
// 新增 src/utils.ts
export function aaa(s: string){
  return s + 'aabbcc'
}

export function bbb(s: string){
  return s + 'ddeeff'
}
```
```ts
// 修改 src/pages/index.tsx
import { aaa } from "../utils";

export default function HomePage() {
  aaa('c') // 主要是多了这一行
  ...
  return ()
}
```
``` shell
yarn build
grep ddeeff dist/p__index.async.js
```
发现有bbb函数的代码`ddeeff`，并没有被“摇”掉：
```js
"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[866],{2772:function(f,o,r){r.r(o),r.d(o,{default:function(){return l}});var c=r.p+"static/yay.7d162f31.jpg";function i(s){return s+"aabbcc"}function p(s){return s+"ddeeff"}var t=r(5893);function l(){return i("c"),(0,t.jsxs)("div",{children:[(0,t.jsx)("h2",{children:"Yay! Welcome to umi!"}),(0,t.jsx)("p",{children:(0,t.jsx)("img",{src:c,width:"388"})}),(0,t.jsxs)("p",{children:["To get started, edit ",(0,t.jsx)("code",{children:"pages/index.tsx"})," and save to reload."]})]})}},5251:function(f,o,r){var c;var i=r(7294),p=Symbol.for("react.element"),t=Symbol.for("react.fragment"),l=Object.prototype.hasOwnProperty,s=i.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner,m={key:!0,ref:!0,__self:!0,__source:!0};function y(u,e,_){var n,d={},a=null,h=null;_!==void 0&&(a=""+_),e.key!==void 0&&(a=""+e.key),e.ref!==void 0&&(h=e.ref);for(n in e)l.call(e,n)&&!m.hasOwnProperty(n)&&(d[n]=e[n]);if(u&&u.defaultProps)for(n in e=u.defaultProps,e)d[n]===void 0&&(d[n]=e[n]);return{$$typeof:p,type:u,key:a,ref:h,props:d,_owner:s.current}}c=t,o.jsx=y,o.jsxs=y},5893:function(f,o,r){f.exports=r(5251)}}]);
```

**Comment by nisnaker** [comment]
怎么又给我关了，我觉得已经是 “最小重现” 了

**Comment by nisnaker** [comment]
@fz6m 您好，我发现issue被打了 duplicate 标签，是因为 #11204 被关闭了，那个issue我反馈的是entry里的不会被shake，后来发现和entry没有关系，正常的pages代码就有这个问题，然后也不知道那个被关闭的issue你们会不会再看，才新建了本issue。

**Comment by fz6m** [comment]
明白你的意思了，umi 4 默认使用 esbuild 进行代码压缩，这会获得更快的性能，但会放弃一部分 tree shake ，因为现代网速已经不需要过多关注代码优化，更注重构建效率。

如果需要比较准确的 tree shake ，可以回到以前的 terser 压缩器：

```ts
  jsMinifier: 'terser'
```

**Comment by nisnaker** [comment]
> 明白你的意思了，umi 4 默认使用 esbuild 进行代码压缩，这会获得更快的性能，但会放弃一部分 tree shake ，因为现代网速已经不需要过多关注代码优化，更注重构建效率。
> 
> 如果需要比较准确的 tree shake ，可以回到以前的 terser 压缩器：
> 
> ```ts
>   jsMinifier: 'terser'
> ```

好的，非常感谢，我是看esbuild官方有tree shake选项，然后各种改.umirc.ts都没用，以为是umi的bug，报歉打扰啦~

**Comment by fantasy525** [comment]
这,,,为了获得更快的打包性能，放弃tree-shaking，现代网速都很快了...

**Comment by fantasy525** [comment]
> 

什么是放弃一部分tree shaking啊？是压根没启用esbuild app.js --tree-shaking=true 还是怎么回事方便解释下吗？

**Comment by fantasy525** [comment]
> 



> > 明白你的意思了，umi 4 默认使用 esbuild 进行代码压缩，这会获得更快的性能，但会放弃一部分 tree shake ，因为现代网速已经不需要过多关注代码优化，更注重构建效率。
> > 如果需要比较准确的 tree shake ，可以回到以前的 terser 压缩器：
> > ```ts
> >   jsMinifier: 'terser'
> > ```
> 
> 好的，非常感谢，我是看esbuild官方有tree shake选项，然后各种改.umirc.ts都没用，以为是umi的bug，报歉打扰啦~

@nisnaker 是没有压根没设置esbuild开启tree-shaking吗？

**Comment by fz6m** [comment]
esbuild 几乎无法 tree shaking ，当使用 esbuild 时，相当于放弃了 tree shaking 。

**Comment by vaclock** [comment]
> esbuild 几乎无法 tree shaking ，当使用 esbuild 时，相当于放弃了 tree shaking 。

请教一下，esbuild 几乎无法 tree shaking 这句话怎么理解，esbuild不是也支持treeshaking吗
