### ISSUE TITLE
src/locales/zh-CN.ts中定义语言内容时，使用嵌套对象方式定义{a: {b: 'xxx'}}，但是无法正确通过“a.b”取用显示

### ISSUE THREAD

**Issue by NieShiyi** [umijs/umi#11208]
## What happens?

src/locales/zh-CN.ts中定义语言内容时，使用嵌套对象方式定义{a: {b: 'xxx'}}，但是无法正确通过“a.b”取用显示

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/NieShiyi/umi-feedback/tree/umi4-locale-object

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

根据umi官方文档[https://umijs.org/docs/max/i18n#%E6%A0%BC%E5%BC%8F%E5%8C%96%E5%AD%97%E7%AC%A6%E4%B8%B2描述，支持定义语言内容时，使用对象包裹的方式如下：](https://umijs.org/docs/max/i18n#%E6%A0%BC%E5%BC%8F%E5%8C%96%E5%AD%97%E7%AC%A6%E4%B8%B2%E6%8F%8F%E8%BF%B0%EF%BC%8C%E6%94%AF%E6%8C%81%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80%E5%86%85%E5%AE%B9%E6%97%B6%EF%BC%8C%E4%BD%BF%E7%94%A8%E5%AF%B9%E8%B1%A1%E5%8C%85%E8%A3%B9%E7%9A%84%E6%96%B9%E5%BC%8F%E5%A6%82%E4%B8%8B%EF%BC%9A)

```
格式化字符串
您可能想要在多语言翻译中动态插值，那么可以像这样编写多语言内容：

// src/locales/zh-CN.ts
export default {
    user: {
      welcome: '{name}，今天也是美好的一天！',
    },
};
// src/locales/en-US.ts
export default {
   user: {
    welcome: '{name}, what a nice day!',
   },
};
//使用如下：
import { FormattedMessage } from 'umi';
 
export default function Page() {
  return (
    <p>
      <FormattedMessage id="user.welcome" values={{ name: '张三' }} />
    </p>
  );
};

//如果您希望通过 intl 对象来实现，那么可以这样对它赋值：
import { useIntl } from 'umi';
 
export default function Page() {
  const intl = useIntl();
  const msg = intl.formatMessage(
    {
      id: 'user.welcome',
    },
    {
      name: '张三',
    },
  );
 
  return <p>{msg}</p>;
};
```
**但是我使用以上方式“user.welcome”取不到，显示的还是“user.welcome”字符串**

## Context

- **Umi Version**:  4.0.64及以上（@umijs/max）
- **Node Version**: v16.17.0
- **Platform**: windows

**Comment by hongfaqiu** [comment]
这是umijs国际化插件的问题，可以自己写一个方法转换一下json
```ts
function flattenMessages(
  nestedMessages: Record<string, any>,
  prefix = '',
) {
  return Object.keys(nestedMessages).reduce(
    (messages: Record<string, any>, key) => {
      let value = nestedMessages[key];
      let prefixedKey = prefix ? `${prefix}.${key}` : key;

      if (typeof value === 'string') {
        messages[prefixedKey] = value;
      } else {
        Object.assign(messages, flattenMessages(value, prefixedKey));
      }

      return messages;
    },
    {},
  );
}
```

另外国际化插件和antd强绑定了，我觉得不太好，所以自己参考[next-intl](https://github.com/amannn/next-intl)写了一个国际化工具

**Comment by NieShiyi** [comment]
> 这个地方不支持嵌套的，

**Comment by NieShiyi** [comment]
> 这是umijs国际化插件的问题，可以自己写一个方法转换一下json
> 
> ```ts
> function flattenMessages(
>   nestedMessages: Record<string, any>,
>   prefix = '',
> ) {
>   return Object.keys(nestedMessages).reduce(
>     (messages: Record<string, any>, key) => {
>       let value = nestedMessages[key];
>       let prefixedKey = prefix ? `${prefix}.${key}` : key;
> 
>       if (typeof value === 'string') {
>         messages[prefixedKey] = value;
>       } else {
>         Object.assign(messages, flattenMessages(value, prefixedKey));
>       }
> 
>       return messages;
>     },
>     {},
>   );
> }
> ```
> 
> 另外国际化插件和antd强绑定了，我觉得不太好，所以自己参考[next-intl](https://github.com/amannn/next-intl)写了一个国际化工具
针对这个对象的方式，umi应该在他的源代码中可以实现封装

**Comment by 1316346949** [comment]
> 这是umijs国际化插件的问题，可以自己写一个方法转换一下json
> 
> ```ts
> function flattenMessages(
>   nestedMessages: Record<string, any>,
>   prefix = '',
> ) {
>   return Object.keys(nestedMessages).reduce(
>     (messages: Record<string, any>, key) => {
>       let value = nestedMessages[key];
>       let prefixedKey = prefix ? `${prefix}.${key}` : key;
> 
>       if (typeof value === 'string') {
>         messages[prefixedKey] = value;
>       } else {
>         Object.assign(messages, flattenMessages(value, prefixedKey));
>       }
> 
>       return messages;
>     },
>     {},
>   );
> }
> ```
> 
> 另外国际化插件和antd强绑定了，我觉得不太好，所以自己参考[next-intl](https://github.com/amannn/next-intl)写了一个国际化工具

这个方法用在哪里？app.ts吗

**Comment by hongfaqiu** [comment]
> > 这是umijs国际化插件的问题，可以自己写一个方法转换一下json
> > ```ts
> > function flattenMessages(
> >   nestedMessages: Record<string, any>,
> >   prefix = '',
> > ) {
> >   return Object.keys(nestedMessages).reduce(
> >     (messages: Record<string, any>, key) => {
> >       let value = nestedMessages[key];
> >       let prefixedKey = prefix ? `${prefix}.${key}` : key;
> > 
> >       if (typeof value === 'string') {
> >         messages[prefixedKey] = value;
> >       } else {
> >         Object.assign(messages, flattenMessages(value, prefixedKey));
> >       }
> > 
> >       return messages;
> >     },
> >     {},
> >   );
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 另外国际化插件和antd强绑定了，我觉得不太好，所以自己参考[next-intl](https://github.com/amannn/next-intl)写了一个国际化工具
> 
> 这个方法用在哪里？app.ts吗

可以参考一下这个目录https://github.com/hongfaqiu/umijs4-with-antd5-tailwindcss/tree/main/src/locales

**Comment by 1316346949** [comment]
> > > 这是umijs国际化插件的问题，可以自己写一个方法转换一下json
> > > ```ts
> > > function flattenMessages(
> > >   nestedMessages: Record<string, any>,
> > >   prefix = '',
> > > ) {
> > >   return Object.keys(nestedMessages).reduce(
> > >     (messages: Record<string, any>, key) => {
> > >       let value = nestedMessages[key];
> > >       let prefixedKey = prefix ? `${prefix}.${key}` : key;
> > > 
> > >       if (typeof value === 'string') {
> > >         messages[prefixedKey] = value;
> > >       } else {
> > >         Object.assign(messages, flattenMessages(value, prefixedKey));
> > >       }
> > > 
> > >       return messages;
> > >     },
> > >     {},
> > >   );
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 另外国际化插件和antd强绑定了，我觉得不太好，所以自己参考[next-intl](https://github.com/amannn/next-intl)写了一个国际化工具
> > 
> > 
> > 这个方法用在哪里？app.ts吗
> 
> 可以参考一下这个目录https://github.com/hongfaqiu/umijs4-with-antd5-tailwindcss/tree/main/src/locales

搞定了，谢谢
