### ISSUE TITLE
[Bug] qiankun 浏览器兼容问题

### ISSUE THREAD

**Issue by consistent-k** [umijs/umi#11207]
## What happens?
<img width="768" alt="ac2886171f82744626cac0f814bba666" src="https://github.com/umijs/umi/assets/67736912/7053de87-cbdc-4bfa-a12f-7bffc57cf534">

## Mini Showcase Repository(REQUIRED)

>  使用Chrome49 版本打开部署好的 qiankun应用 报错如上图所示
检索后发现可能是 proxy-compare包的问题： https://github.com/dai-shi/proxy-compare/pull/8

## How To Reproduce
主应用和子应用均配置：
   targets: {
        chrome: 49
    },
    legacy: {}
后build，部署之后使用Chrome49 版本打开即可发现如图错误

## Context

- **Umi Version: 4.0.69
- **Node Version: 16
- **Platform: windows Chrome

**Comment by fz6m** [comment]
qiankun 不包含这个 `proxy-compare` 。

你用了 `valtio` 吗，这个库需要现代浏览器，不支持这么旧的，如果要兼容这种旧浏览器，换用一种老的全局数据流方案把，比如 redux 。
