### ISSUE TITLE
配置 lessOptions 不生效

### ISSUE THREAD

**Issue by lhbxs** [umijs/umi#11201]
我用的是 @umijs/max，组件是 antd 5.0 

配置项： 
lessLoader: {
    lessOptions: {
      modifyVars: {
        '@ant-prefix': 'fant'
      },
    },
  },
  
  我项目里面引用了一个三方组件库，组件的 less 文件 是这么写的
  @ant-prefix: ant;

.fr-hide-label > .@{ant-prefix}-form-item-row > .@{ant-prefix}-form-item-label {
  visibility: hidden;
}

我项目使用了 prefixCls，这样就会导致组件的样式失效，所以通过配置 lessLoader来使得变量名 从  @ant-prefix: ant =》  @ant-prefix: fant

但是没有效果，运行的时候，我看 这部分 css 还是 ant 开头的

**Comment by fz6m** [comment]
仔细看一遍 antd 5 文档吧， antd 5 是 css in js 方案，和 less / scss 这些无关。
