### ISSUE TITLE
umi build打包时忽略指定文件

### ISSUE THREAD

**Issue by yansuan** [umijs/umi#1120]
因为有项目需要部署多个，提供给不同的公司使用，需要配置不同的参数，比如api服务器之类的参数，这种如何处理？

**Comment by okoala** [comment]
通过环境变量 UMI_ENV 加载不同的配置

**Comment by yansuan** [comment]
麻烦给个例子吧  谢谢

**Comment by yansuan** [comment]
这个配置编译后不能修改，还是编译前的配置文件，我需要部署时修改配置文件

**Comment by okoala** [comment]
你可以根据环境编译多份或者配置做成动态的从  window 中获取~

**Comment by a758801405** [comment]
你好，后来解决了吗，我也有类似的需求

**Comment by Josie-ljw** [comment]
> 这个配置编译后不能修改，还是编译前的配置文件，我需要部署时修改配置文件

这个问题解决了吗？我也有类似的需求，需要暴露一个baseUrl出去，打包后，可以修改config文件的baseUrl值，达到请求不通域名的场景

**Comment by zhangheng0317** [comment]
我是这样配置的,在document.ejs文件中手动添加一个config.js,
![image](https://github.com/user-attachments/assets/24b6d2a7-2fe1-4ce3-a1f1-318d29c14631)
然后在项目中使用
![image](https://github.com/user-attachments/assets/fc42fcc1-af9e-40f8-ab1e-a3c86dfe33f5)
config.js类似这样
![image](https://github.com/user-attachments/assets/c39b904d-eee1-45e9-af9f-82accfea8a0e)
