### ISSUE TITLE
无法关闭开发模式下的错误页，使用自定义的错误页

### ISSUE THREAD

**Issue by vscing** [umijs/umi#11200]
![Dingtalk_20230526123823](https://github.com/umijs/umi/assets/20698627/1bbd84c3-f21e-4f37-b209-016a4e512d5c)
开发模式下的错误页，无法进行关闭配置。使用自定义的错误页

- **Umi Version**: v4.0.42
- **Node Version**: 16.18.1

**Comment by fz6m** [comment]
如果包了 error boundary ，且是 error boundary 能承接住的 react 错误，在这个报错页面按 esc 或者右上角叉关掉就可以看到 error boundary 效果了。

这个页面不支持关闭，它在开发时是为了明确提醒你有错误的，在生产中不会有。
