### ISSUE TITLE
umi2 部署到非根目录

### ISSUE THREAD

**Issue by DXDZY** [umijs/umi#1121]
umi2 部署到非根目录 设置base后 ，页面无法打开
![image](https://user-images.githubusercontent.com/15250383/45930081-b8c2f800-bf0f-11e8-963f-43ef0378ffb6.png)
![image](https://user-images.githubusercontent.com/15250383/45930083-cd9f8b80-bf0f-11e8-80e1-fb6d6d928620.png)

**Comment by DXDZY** [comment]
编译时抱这个错
![image](https://user-images.githubusercontent.com/15250383/45934173-217d9500-bf4f-11e8-9f09-2a2c5ed8a6e8.png)

**Comment by okoala** [comment]
你 hardSource: false 看看

**Comment by DXDZY** [comment]
@okoala 这个不是umi 里的配置啊，配置上会报错
![image](https://user-images.githubusercontent.com/15250383/45945384-2e77a400-bfa2-11e8-80f3-0665aa268356.png)

**Comment by DXDZY** [comment]
@okoala 好的感谢
