### ISSUE TITLE
[Bug] Module '"umi"' has no exported member 'Icon'.

### ISSUE THREAD

**Issue by himushroom** [umijs/umi#11215]
## What happens?

使用
`import { Icon } from 'umi';`
提示Module '"umi"' has no exported member 'Icon'.（模块“"umi"”没有导出的成员“Icon”）

下面是官网中的描述，按照以下步骤无法导出Icon，目前使用的是umi4.x
![image](https://github.com/umijs/umi/assets/19682322/40e3fa8c-8385-4074-8814-666744608979)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

`https://codesandbox.io/p/sandbox/umi-icons-bp6zbr?file=%2Fsrc%2Fpages%2FHome%2Findex.tsx%3A1%2C1`

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0.69
- **Node Version**: v16.14.2
- **Platform**: windows 
- **Browser**: Google Chrome 113.0.5672.127

**Comment by fz6m** [comment]
需要在配置里开启后才能用：

```ts
  icons: {}
```

如果是 umi 项目，从 `umi` 导入，如果是 max 项目，从 `@umijs/max` 导入。
