### ISSUE TITLE
[Bug] ssr 未处理 base

### ISSUE THREAD

**Issue by PeachScript** [umijs/umi#11233]
## What happens?

开启 `ssr` 后输出产物中的前端路由链接 `href` 没有正确的 `base` 前缀

## How To Reproduce

**Steps to reproduce the behavior:** 

1. Umi 脚手架开启 `ssr` + `exportStatic` 配置项
2. 配置 `base` 和 `publicPath` 均为 `/a/`
3. 配置 `outputPath` 为 `dist/a`
4. 执行构建
5. 托管 `dist` 目录并通过浏览器访问 `/a` 路径下的应用
6. 检查源代码中前端路由连接的 `href` 值会发现不是 `/a/` 前缀

**Expected behavior**

前端路由连接的 `href` 值为 `/a/` 前缀

关键代码位置：https://github.com/umijs/umi/blob/master/packages/renderer-react/src/server.tsx#L17

## Context

- **Umi Version**: 4.x
- **Node Version**: 16.x
- **Platform**: macOS

**Comment by Wxh16144** [comment]
> 6\. 检查源代码中前端路由连接的 `href` 值会发现不是 `/a/` 前缀

确实不是 `/a/` 前缀, 但是启动 dist server 后点击 href 还是正常跳转了的, 这是一个 bug 吗?

**Comment by PeachScript** [comment]
是 bug，点击能正确跳转应该是因为 react-router 劫持了超链接默认行为，但对于搜索引擎（SEO）或浏览器（新窗口打开）来说，链接就是错误的了

**Comment by Wxh16144** [comment]
好, 交给我试试

**Comment by xlei1123** [comment]
我现在用的3.5也遇到了这个问题，添加base后，ssr渲染 无法成功，并且控制台总是报`did not match`错误
