### ISSUE TITLE
求PWA配置教学

### ISSUE THREAD

**Issue by sl5310** [umijs/umi#1123]
请问是否有人配置出pwa，可以参考一下，找了很多例子但就是一直不成功，但是路径一直不对，尝试了
document.ejs 加上  `<link rel="manifest" href="／manifest.json" />` ，`<link rel="manifest" href="/public/public/manifest.json" />` 尝试了很多但就一直不对

**Comment by jeffrey-fu** [comment]
https://umijs.org/zh/guide/html-template.html#%E9%85%8D%E7%BD%AE%E6%A8%A1%E6%9D%BF
umi2.1.2+

**Comment by QianDingwei** [comment]
你好请教你一下，你的pwa实现了嘛，麻烦赐教

**Comment by xiaohuoni** [comment]
umi@3 暂不支持 pwa

**Comment by QianDingwei** [comment]
那umi@2支持的化，serviceworker如何配置，如何写，想参考一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "陈小聪"<notifications@github.com&gt;; 
发送时间: 2020年4月13日(星期一) 下午5:51
收件人: "umijs/umi"<umi@noreply.github.com&gt;; 
抄送: "1370336125"<1370336125@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [umijs/umi] 求PWA配置教学 (#1123)





 
umi@3 暂不支持 pwa
