### ISSUE TITLE
[Bug] umijs 从v3 升级到v4, chainwebpack使用output.filename 后本地运行白屏

### ISSUE THREAD

**Issue by feiaaa** [umijs/umi#11232]
如题，目的是要把js打到static文件夹里。
chainwebpack中，v3情况下正常。如下
```
const staticDir='static';
// 修改js输出目录
  config.output.
  filename(`${staticDir}/js/[name].[contenthash:8].js`)
  .chunkFilename(`${staticDir}/js/[name].[contenthash:8].chunk.js`);
```

同样的代码在升级后，如果用了到filename就会白屏，并且在浏览器-查看网页源代码中，未看到对umi.js的引用，只能将filename注释。
注释后又无法将umi.js代码打到js文件夹里，而是在根目录。

如果既要将umi.js打到```/static/js ```文件夹中，又要保持在localhost中正常显示，该如何修改代码？

ps：是否关闭 mfsu 都是上述一样的效果。

- **Umi Version**:4.0.0
(
    "@umijs/fabric": "^2.0.5",
    "@umijs/max": "^4.0.0",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/preset-ant-design-pro": "^1.0.1",
    "@umijs/preset-ui": "^2.0.9",
    "umi-request": "^1.0.8",
)

- **Node Version**:v16.14.0
- **Platform**: macos

**Comment by fz6m** [comment]
umi 4 不支持自定义输出文件结构。

**Comment by JasonDRZ** [comment]
请问不支持自定义输出文件结构的点是什么呢？为了 MFSU ？还是多构建内核通用配置？

**Comment by chengYuanXiang11** [comment]
推荐打包之后把文件复制到对应目录上面

**Comment by chengYuanXiang11** [comment]
推荐打包之后把文件复制到对应目录上面

例如
 { 
 base: '/a1/',
  publicPath: '/12/'
}
则在dockerfile中需要加入

COPY --from=builder /app/dist /usr/share/nginx/html/a1

**Comment by chengYuanXiang11** [comment]
😤
