### ISSUE TITLE
[Bug] pnpm8 install安装出多个antd版本

### ISSUE THREAD

**Issue by lovewinders** [umijs/umi#11249]
## 问题描述
pnpm 8.6.0：pnpm install会安装出2个antd版本，这样会因版本导致下图很多报错

#### antd pro v6项目根目录 package.json
```
"dependencies": {
    "@ant-design/icons": "^4.8.0",
    "@ant-design/pro-components": "^2.5.5",
    "@umijs/route-utils": "^4.0.1",
    "antd": "^5.5.1" // 版本v5
  },
```

#### 问题定位：umi/max 源码dependencies竟然固定为"antd": "^4.20.6"导致的

![image](https://github.com/umijs/umi/assets/22837419/09507423-a4dd-411e-9799-bb81c881cf5b)

## 分析报错

[复现分析链接](https://github.com/ant-design/pro-components/issues/7181)
## Context
![image](https://github.com/umijs/umi/assets/22837419/f67e4aa5-07eb-415b-9a5e-5aacbf118b40)

## 解决方案
方案1:移除umi/max package.json中dependencies "antd": "^4.20.6"

- **Umi Version**: 最新
- **Node Version**: v18
- **Platform**: mac os

**Comment by fz6m** [comment]
有很多人不显示的安装 antd ，所以会用到内部 `@umijs/plugins` 自带的 antd 版本，如果要用你自己的 antd ，你就显示安装，alias 会自动识别唯一定位 antd 的，不会有多 antd 的问题。

**Comment by fz6m** [comment]
显示安装：在你的项目 `package.json#dependencies` 里如果有 antd 依赖，就是 “显示“ 的安装，此时以你安装的版本为准，不会使用内部 antd 。

alias ：会自动识别默认配置，无需手动干预。
