### ISSUE TITLE
[Bug] pnpm install  .../node_modules/esbuild postinstall$ node install.js Error: Expected "0.17.19" but got "0.16.17"

### ISSUE THREAD

**Issue by leshalv** [umijs/umi#11244]
今天使用pnpm重新安装依赖，失败，.../node_modules/esbuild postinstall$ node install.js 报错：Error: Expected "0.17.19" but got "0.16.17"

**Comment by fz6m** [comment]
升级 umi 到最新版本，把 node_modules 删了再重装依赖看看，如还有问题，需要提供更多的上下文信息，给一个最小复现。
