### ISSUE TITLE
[Bug] say something 运行项目一直报错  控制台却没错误

### ISSUE THREAD

**Issue by xiguachao** [umijs/umi#11245]
![image](https://github.com/umijs/umi/assets/99702809/353a9cb0-125a-479d-b58c-00ae50df15ba)
![image](https://github.com/umijs/umi/assets/99702809/9f63ef8e-fcbb-4b85-bab7-1e9f54edc784)

![image](https://github.com/umijs/umi/assets/99702809/041b1c10-9aca-40ef-bd5f-504f212f1453)

**Comment by xiguachao** [comment]
有没有大佬帮帮忙 删除依赖 删除umi缓存都试过好多次了 node版本也切换过  都没用

**Comment by xierenyuan** [comment]
关闭 mfsu 看看

**Comment by xiguachao** [comment]
> 关闭 mfsu 看看

给大佬磕一个

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4 。
