### ISSUE TITLE
运行后 控制台报错

### ISSUE THREAD

**Issue by sleepPanda1030** [umijs/umi#11247]
![image](https://github.com/umijs/umi/assets/25787392/452cc042-4b8f-440c-b3d5-1e444b96bad4)

**Comment by fz6m** [comment]
这个是选项废弃的警告，不影响使用，如果你想去掉，就把 layout 和自带的模板代码删掉就行。

**Comment by sleepPanda1030** [comment]
我对照了 这个版本package.json的文件，发现这个废弃警告出现之前的依赖引用和出现之后的依赖引用，所下载的依赖版本不一样，比如废弃之前"@ant-design/pro-components": "^2.4.4"，确实下载的是2.4.4版本，但是警告出现之后下载的是"@ant-design/pro-components": "^2.5.5"，这些警告是创建项目之后，没有其他操作的情况下，直接运行项目就出现的警告
