### ISSUE TITLE
[Bug] 使用token修改layout颜色不生效

### ISSUE THREAD

**Issue by ideaviewes** [umijs/umi#11255]
## What happens?
[Bug] 使用token修改layout颜色不生效

## Mini Showcase Repository(REQUIRED)

https://github.com/ideaviewes/mini-showcase-token-useless.git

## How To Reproduce

git clone https://github.com/ideaviewes/mini-showcase-token-useless.git
cd antdpro-token-useles
tyarn
tyarn start

登录进去，
我改了app.tsx文件，在里面设置了token，但是不生效
## Context

- **Umi Version**: 4.0.52
- **Node Version**: v18.16.0
- **Platform**:win10 x64

**Comment by fz6m** [comment]
看一下 `config.ts` 里的 layout 静态配置，被 `token: {}` 覆盖了运行时配置，删了就好了。

**Comment by ideaviewes** [comment]
好的
