### ISSUE TITLE
umi build  uglifyjs-webpack-plugin生成文件太长

### ISSUE THREAD

**Issue by Zmoonpie** [umijs/umi#1125]
window环境 ，umi build 在构建服务中mode_modules/.cache/uglifyjs-plugin/content-v2/sha512/72/9e中 文件名太长，每次删除又不是很方便，有什么解决方案吗 ？

**Comment by sorrycc** [comment]
试试配 `uglifyJSOptions: { cache: false }`，参考 https://github.com/webpack-contrib/uglifyjs-webpack-plugin#cache

**Comment by Zmoonpie** [comment]
我设置了也不起作用
