### ISSUE TITLE
yarn create umi  error command failed

### ISSUE THREAD

**Issue by zcrman** [umijs/umi#1126]
执行yarn create umi  报错：具体如下：
success Installed "create-umi@0.3.1" with binaries:
      - create-umi
'D:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
error Command failed.
Exit code: 1
Command: D:\Program Files\nodejs\node_global\bin\create-umi
Arguments:
Directory: E:\ReactProject\umjs_ant_electron_grasp_gather
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

请问是哪里出问题了，具体怎么解决

**Comment by sorrycc** [comment]
环境变量 PATH 里需添加 `yarn global bin` 的路径。
