### ISSUE TITLE
[Bug] umijs3的plugin-layout插件依赖的antd版本过高导致控制台报错

### ISSUE THREAD

**Issue by wellsmitch** [umijs/umi#11260]
App.js 运行时配置layout时，开启logout字段后控制台报错
![1686296518477](https://github.com/umijs/umi/assets/42932079/5104fc00-9696-44f1-946a-06f23f227d5e)

![1686296585394](https://github.com/umijs/umi/assets/42932079/a5f088d0-b433-4a28-a495-76e6c3738d6e)
![1686296650048](https://github.com/umijs/umi/assets/42932079/164c94b8-3472-485d-9902-6f729e076a19)
![1686296767849](https://github.com/umijs/umi/assets/42932079/c968a254-0365-469c-8eed-a80cdc055900)
如何控制plugin-layout依赖的antd的版本

**Comment by fz6m** [comment]
在你的项目本身的 `package.json` 里安装一下固定版本的 antd ，就会用你自己版本的了。
