### ISSUE TITLE
[Bug] 请问下umijs 3.5.17 项目里面配置了alias，别名不生效,这个是怎么回事儿呢

### ISSUE THREAD

**Issue by dxfstart521** [umijs/umi#11262]
请问下umijs 3.5.17 项目里面配置了alias，在开发环境启动一直加载不到文件，别名没有生效。这个是怎么回事儿呢

<img width="1306" alt="image" src="https://github.com/umijs/umi/assets/31570901/5fd737be-1aad-499e-9a86-b2d771bbaa34">

<img width="1332" alt="image" src="https://github.com/umijs/umi/assets/31570901/dd5fb80f-0d8a-4dcb-a0da-53215039cced">

<img width="1064" alt="image" src="https://github.com/umijs/umi/assets/31570901/2c2c6b5a-8a3a-4c28-80e8-34cc0006bc5e">

**Comment by fz6m** [comment]
你这个 `config.ts` 所在的目录里没有 `public` 文件夹，路径拼接的有误，尝试下 `path.join(__dirname, '../public')` 吧。
