### ISSUE TITLE
useRequest 拦截器

### ISSUE THREAD

**Issue by xiaonan132142** [umijs/umi#11264]
caught (in promise) TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at dispatchXhrRequest (mf-dep____vendor.f83c36c9.js:286564:32)
    at new Promise (<anonymous>)
    at xhrAdapter (mf-dep____vendor.f83c36c9.js:286534:10)
    at dispatchRequest (mf-dep____vendor.f83c36c9.js:287427:10)
d

配置

requestInterceptors: [
    (url, options) => {
      // const language = getLocale();
      options.headers = { ...options.headers,token:''};

      if (options.method === 'get') {
        options.params = { ...options.params, webSiteId: 1 };
      } else {
        options.data = { ...options.data, webSiteId: 1 ,method:'POST' };
      }
      console.log({ ...options, url })
      return { ...options, url };
    },
  ],

**Comment by katoto** [comment]
这个错误异步设置拦截器引起的吧

**Comment by fz6m** [comment]
关于异步请求拦截器和响应拦截器的问题，现在 umi 4 最新版本 `4.1.2` 是已经支持了 use request 的异步拦截器配置了。

**Comment by Taurues** [comment]
> caught (in promise) TypeError: Cannot read properties of undefined (reading 'toUpperCase') at dispatchXhrRequest (mf-dep____vendor.f83c36c9.js:286564:32) at new Promise () at xhrAdapter (mf-dep____vendor.f83c36c9.js:286534:10) at dispatchRequest (mf-dep____vendor.f83c36c9.js:287427:10) d
> 
> 配置
> 
> requestInterceptors: [ (url, options) => { // const language = getLocale(); options.headers = { ...options.headers,token:''};
> 
> ```
>   if (options.method === 'get') {
>     options.params = { ...options.params, webSiteId: 1 };
>   } else {
>     options.data = { ...options.data, webSiteId: 1 ,method:'POST' };
>   }
>   console.log({ ...options, url })
>   return { ...options, url };
> },
> ```
> 
> ],

你好 请问这个问题解决了吗 我也遇到了一样的问题

**Comment by Taurues** [comment]
> 关于异步请求拦截器和响应拦截器的问题，现在 umi 4 最新版本 `4.1.2` 是已经支持了 use request 的异步拦截器配置了。

我是umi3.5升级到umi4.2，按照官网的升级步骤升级的。然后requet这里配置还是umi3.5的，运行就报这个错误  TypeError: Cannot read properties of undefined (reading 'toUpperCase')。
