### ISSUE TITLE
[Bug] 显式安装 antd 后，将 antd 卸载，使用内置插件的 antd，丢失了 antd 的类型

### ISSUE THREAD

**Issue by AmAzing129** [umijs/umi#11272]
使用 umi + pnpm
![image](https://github.com/umijs/umi/assets/115673583/17cd63b2-9141-43b9-9b5a-6749e36feaca)
![image](https://github.com/umijs/umi/assets/115673583/0775d7a4-3084-41fb-9c29-f16b27f61161)

**Comment by fz6m** [comment]
如果你要用 antd 导入，就需要显示安装，才能有类型，不然 IDE 不知道去哪找类型。

之所以你不安装会用内置的，是因为 layout 里用了 antd ，如果你不导入，就没必要显示安装。

另外用内置的是不安全的，不是所有的包管理工具都能确保间接依赖的版本稳定性，手动显示确定是最安全的。
