### ISSUE TITLE
umi3 启动项目的时候报错找不到Module not found: Error: Can't resolve 'core-js-pure/features/global-this' in 'C:\Project\mall-cms-fe\node_modules\umi\node_modules\@umijs\preset-built-in\bundled\@pmmmwh\react-refresh-webpack-plugin\client'

### ISSUE THREAD

**Issue by liushuhui** [umijs/umi#11279]
## What happens?

umi3 启动项目的时候报错找不到Module not found: Error: Can't resolve 'core-js-pure/features/global-this' in 'C:\Project\mall-cms-fe\node_modules\umi\node_modules\@umijs\preset-built-in\bundled\@pmmmwh\react-refresh-webpack-plugin\client'

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:3.5.36
- **Node Version**:v16.19.0
- **Platform**:window
- npm:9.6.0
<img width="639" alt="710f9922d9084d9c05c615542c88c0f0" src="https://github.com/umijs/umi/assets/26155477/d55022b0-ab9a-491e-8b03-6e5c204b7631">

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4
