### ISSUE TITLE
[Bug] access配置没有阻止用户无权限的页面

### ISSUE THREAD

**Issue by konayukis** [umijs/umi#11283]
## What happens?

需求类似于权限路由：主要用于切换新老功能

一组互斥开关`new`和`old`分别用户开启新/旧功能
```
// acess.ts
export default function (initialState) {
  // 增加商行级别配置，使用老结算，enableOldSettlement=true，默认false
  const { old= false }  = initialState || {};
 
  return {
    old,
    new: !old
  };
}

// route.config.js
{
 path: '/odd',
 component:  '/odd'，
 access: 'notnew',
 routes: [....]
}

{
 path: '/new',
 component:  '/new'，
 access: 'new',
 routes: [....]
}
```

## Mini Showcase Repository(REQUIRED)

`new`和`old`的开关生效，但是可以使用页面路由访问无权页面  例如：access 为 new时 通过'/old'还是可以访问旧页面

![image](https://github.com/umijs/umi/assets/70825886/3c7ab04b-1924-480e-9fa7-5faadb388f7d)

并没有像文档中的渲染 Layout 插件内置的权限错误页面，而是直接进入无权限的页面

## Context

- **Umi Version**:  3.x
- **Node Version**: 14.18.0
- **Platform**: chorme

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4
