### ISSUE TITLE
[Bug] UmiJS 4版本 与yarn workspace集成，当子项目名称存在@时报错

### ISSUE THREAD

**Issue by wangchaoHeart** [umijs/umi#11286]
## What happens?
UmiJS与yarn workspace集成，当子项目名称存在@时报错。Windows下会报错，其他平台没测试。

当子项目package.json的name存在@时，yarn install 安装依赖时报错

## Mini Showcase Repository(REQUIRED)
https://github.com/wangchaoHeart/umi4_workSpace_bug 
 
> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

1.从https://github.com/wangchaoHeart/umi4_workSpace_bug 下载下代码
2.在项目根目录执行yarn install安装依赖
此时就会报错

Directory: C:\Users\wangc\Desktop\333\umi4_workSpace_bug\node_modules\@umi4-test\componentsOutput:
node:internal/modules/cjs/loader:1024  throw err;
  ^

Error: Cannot find module 'C:\Users\wangc\Desktop\333\umi4_workSpace_bug\node_modules\node_modules\umi\bin\umi.js'    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
    at Function.Module._load (node:internal/modules/cjs/loader:866:27)    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {

## Context

- **Umi Version**:4.0.7
- **Node Version**: v18.15.0
- **Platform**:windows11

**Comment by fz6m** [comment]
Umi 更推荐使用 pnpm workspace 。

这个项目的 lerna 版本太旧了，换最新的再尝试下吧。

**Comment by wangchaoHeart** [comment]
> Umi 更推荐使用 pnpm workspace 。
> 
> 这个项目的 lerna 版本太旧了，换最新的再尝试下吧。

非常感谢你的回答，我已经把项目改成用pnpm workspace的方式了，一切都正常运行，谢谢
