### ISSUE TITLE
.umi 文件夹下 tsconfig.json 文件  paths 应该包含 umi 内置及配置的  alias

### ISSUE THREAD

**Issue by Jerry-qiqi** [umijs/umi#11280]
## Background

当我使用 import { useSelector } from '@umijs/max' 时，useSelector 类型错误问题

## Proposal

内置和配置项的 alias 应该在 tsconfig.json 模版中 的paths 字段体现

## Additional context

<img width="1341" alt="image" src="https://github.com/umijs/umi/assets/47138111/6e48ec71-c03f-4b1d-8cae-b112f92839e4">

**Comment by fz6m** [comment]
你看到的 `dva` 、`antd` 等内部插件添加的 alias 是为了定位依赖唯一性使用的，所有的 dva 方法都在 umi 导出了，所以你只需要从 umi 导入使用即可。

**Comment by Jerry-qiqi** [comment]
@fz6m 这个dva 通过alias 方式引入，但是ts paths 里面没有映射，外部也没有安装dva 这个包, 类型丢失了呀

**Comment by fz6m** [comment]
手动安装一下 dva 吧，因为 dva 早就不维护了，现在不推荐使用了。

现在推荐的现代数据流方案是全局数据用 [Jotai](https://github.com/pmndrs/jotai) / [valtio](https://umijs.org/docs/max/valtio) 管理，请求数据流用 [react-query](https://umijs.org/docs/max/react-query) 。
