### ISSUE TITLE
layouts文件state状态改变时，在以下情况下会触发pages页面重新 mount

### ISSUE THREAD

**Issue by SwordsmanYao** [umijs/umi#1129]
复现条件：
  1.layouts中使用 antd 的 Layout组件
  2.pages对应目录下有 _layout.tsx 文件
  
删除 antd 的 Layout组件 或 删除 _layout.tsx 文件，都不会出现此问题

复现demo： https://github.com/SwordsmanYao/kmx-ui-next-platform/tree/issue-layout
操作：
  1.进到 http://localhost:8000/list
  2.点击‘转换’按钮
结果：
  列表被重新加载了
期望：
  列表不会重新加载

**Comment by dilidili** [comment]
我觉得这个应该是由于 antd 的 Layout 组件是一个 ContextProvider, 而 React 在 ```updateClassInstance``` 的过程中默认 context 总是被修改过：
```js
  // The context might have changed so we need to recalculate it.
  if (hasContext) {
    invalidateContextProvider(workInProgress, Component, true);
  }
```
导致 children 全部被重绘。再加上 list/_layout 中使用了鉴权路由造成的 Component 重建，最后导致了重新 mount。

一种解决方案就是把 Layout 组件放到 state update 影响不到的地方，比如：
https://github.com/SwordsmanYao/kmx-ui-next-platform/blob/issue-layout/src/layouts/index.tsx
```
export default withRouter(connect()((props) => <Layout><Layouts {...props} /></Layout>));
```

**Comment by SwordsmanYao** [comment]
@dilidili 布局里用了两个 Layout，拿不出来的，看看后面如果解不了的话只能改成 div自己写了
