### ISSUE TITLE
[Bug] yarn create umi failed

### ISSUE THREAD

**Issue by GreenYun** [umijs/umi#11309]
## What happens?

`yarn create umi` failed due to:

```
Internal Error: root-workspace-0b6124@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
```

## Mini Showcase Repository(REQUIRED)

There will be no showcase repos because project creation failed.

This is a repo for scripts creating a new project: https://github.com/GreenYun/show

## How To Reproduce

**Steps to reproduce the behavior:**

1. Run `yarn create umi` in any empty directories
2. Select any app template (I have tried `Simple App` and `Ant Design Pro`)
3. Pick `yarn` as Npm Client
4. Pick `npm` as Npm Registry

**Expected behavior**

Project creation success

## Context

- **Umi Version**: 4.0.17 (Seems so)
- **Node Version**: 20.3.0
- **Yarn Version**: 3.6.0
- **Platform**: MacOS AND Linux

## Other information

I have also tried `pnpm` as Npm Client, with project creation succeeding with warnings but building failing on error. It seems that some of the dependencies broke.

**Comment by fz6m** [comment]
umi 4 只支持 yarn 1.x / pnpm 6+ / npm 8+
