### ISSUE TITLE
[Bug] configprovider label => right

### ISSUE THREAD

**Issue by 0x457** [umijs/umi#11308]
## What happens?

单独用provider去包裹一个formitem上时，label的文本变成了右对齐。
![WechatIMG12](https://github.com/umijs/umi/assets/5813610/a35454bf-e96f-4aa7-b6e7-38fa8612b329)

## Context

- **Umi Version**:4.0.71
- **Node Version**:18.16.0
- **Platform**:window11
![WechatIMG9](https://github.com/umijs/umi/assets/5813610/480fc5a9-3de7-4159-a70a-9e0f3b7439b9)

**Comment by fz6m** [comment]
使用了 layout 布局后，不能自己包 config provider 和自定义 antd ，这些在 layout 内部被预设好了。

如果需要使用 token ，可以通过 `useTheme` 获取。

如有问题，到 [pro component](https://github.com/ant-design/pro-components) 反馈吧。
