### ISSUE TITLE
[Bug] src下的loading.tsx不生效

### ISSUE THREAD

**Issue by snail-climb** [umijs/umi#11310]
源码如下：
const Loading: React.FC = () => {
  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        height: "100%",
        minHeight: "420px",
      }}
    >
      {/*<img src="<%= context.config.publicPath + 'img/logo/logo.png' %>" alt="logo" width="256" />*/}
      <div className="page-loading-warp">
        <div className="ant-spin ant-spin-lg ant-spin-spinning">
          <span className="ant-spin-dot ant-spin-dot-spin">
            <i className="ant-spin-dot-item"></i>
            <i className="ant-spin-dot-item"></i>
            <i className="ant-spin-dot-item"></i>
            <i className="ant-spin-dot-item"></i>
          </span>
        </div>
      </div>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "center" }}>
        {/*<img*/}
        {/*  src="<%= context.config.publicPath + 'img/logo/logo.svg' %>"*/}
        {/*  width="32"*/}
        {/*  style="margin-right: 8px"*/}
        {/*/>*/}
        {/*<%= context.config.layout.title %>*/}
      </div>
    </div>
  );
};

export default Loading;

**Comment by fz6m** [comment]
需要给一个最小复现

**Comment by snail-climb** [comment]
我用的umi max，所有的版本包括antd antdpro都是最新版的，loading.tsx内容就是一个非常基础的官方示例，代码如下：
import { Spin } from 'antd';

const App: React.FC = () => <Spin />;

export default App;
我把浏览器网速调的很低，刷新时显示的是空白页，并没有显示加载状态

**Comment by fz6m** [comment]
给一个最小复现仓库看看吧，我把最新的 [ant-pro](https://github.com/ant-design/ant-design-pro) 仓库克隆下来，加了 `src/loading.tsx` 是有效的。

**Comment by snail-climb** [comment]
仓库是这个，麻烦啦，https://github.com/snail-climb/dolphin-web

**Comment by fz6m** [comment]
我创建了一个 `src/loading.tsx` ：

```tsx
// src/loading.tsx

import { Spin } from "antd";

export default function Page() {
  return (
    <Spin
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
      }}
      spinning
    ></Spin>
  );
}
```

然后访问页面 `http://localhost:9000/#/login` 是可以看到 loading 效果的。

`src/loading.tsx` 这个文件只能控制所有页面的按需加载动画，不能控制你自己写的页面里的，进入到某个页面后，这个 loading 就没有了，如果这个时候你异步加载地图，地图还没加载好的时候是白屏的，你需要自己展示 loading ，等加载好了再展示页面。

**Comment by snail-climb** [comment]
明白了，感谢
