### ISSUE TITLE
react-flow compile error 

### ISSUE THREAD

**Issue by lyan-ap** [umijs/umi#11327]
Failed to compile
./node_modules/@reactflow/node-resizer/dist/esm/index.js 45:38
Module parse failed: Unexpected token (45:38)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const getPointerPosition = useGetPointerPosition();
|     const defaultPosition = variant === ResizeControlVariant.Line ? 'right' : 'bottom-right';
>     const controlPosition = position ?? defaultPosition;
|     useEffect(() => {
|         if (!resizeControlRef.current || !id) {

## reproduce
```
yarn create @umijs/umi-app
```

index.tsx file, put the simplest react-flow code as follows:

```

import styles from './index.less';
import ReactFlow, { Controls, Background } from 'reactflow';

export default function IndexPage() {
  return (
    <div>
      <h1 className={styles.title}>Page index</h1>
      <ReactFlow>
        <Background />
        <Controls />
      </ReactFlow>
    </div>
  );
}


```

## minimal reproduce

[https://stackblitz.com/edit/stackblitz-starters-qdzrak?file=package.json](https://stackblitz.com/edit/stackblitz-starters-qdzrak?file=package.json
)

**Comment by fz6m** [comment]
这个命令是 umi 3 的新建项目命令，umi 3 不维护了，最新的创建项目命令是：

```bash
  pnpm create umi my-app
  # or
  yarn create umi my-app
```
