### ISSUE TITLE
当我把dynamicImport关闭后，线上加载打包出来的资源会报require is not defined

### ISSUE THREAD

**Issue by linzhixin** [umijs/umi#11328]
这是umi ts的配置
![image](https://github.com/umijs/umi/assets/24630964/d9f40a3d-49ef-466f-9fda-4411269ac1b1)

这是线上的报错
![image](https://github.com/umijs/umi/assets/24630964/1f4bdcbf-a34b-46e0-8748-d67ce9d12459)

**Comment by fz6m** [comment]
vite 构建的时候用的是 rollup ，vite 是 first esm 的，没有 cjs 的 require ，你的 babel 插件都不会在 vite 模式下生效。

把 `vite: {}` 去掉，或者仅在开发时开启（如果你认为 vite 开启后有明显收益的话，但不推荐开启，这个选项更多是给 vue 项目使用的）
