### ISSUE TITLE
如何清除 umi 的缓存 ? 

### ISSUE THREAD

**Issue by vaynevayne** [umijs/umi#11322]
升级 antd5 的过程中, 重新执行 yarn run dev 
报错

```jsx
 error  in ./src/pages/realtime/real_time_data/index.tsx

Module not found: Error: Can't resolve 'antd/es/time-picker/style' in '/Users/vayne/wmqj/bi-v3/src/pages/realtime/real_time_data'
```

代码里并没有这个 import 文件, 这是缓存问题吗?

**Comment by fz6m** [comment]
把 `babel-plugin-import` 去掉，`antd.import` 去掉，antd 5 是 css in js 没有实体 css 样式了，默认按需使用，不需要 babel 插件了。

如果还有问题，需要给一个最小复现。

**Comment by vaynevayne** [comment]
config.js 里 没看到我有自己使用过 babel-plugin-import,只有个 umi/meta 啥的
