### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by mgserss** [umijs/umi#11335]
## What happens?

为了使用StyleProvider ，把版本从4.0.56更新到latest，但是运行时一直报没有找到cssinjs，于是运行 pnpm install @ant-design/cssinjs -S 后，还是一样报没有找到cssinjs

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: v4.0.71
- **Node Version**: v16.8.0
- **Platform**: windows

**Comment by fz6m** [comment]
如果你用的是 umi antd 插件或者 max ，可以更新到最新的 umi / max 版本，通过 [`antd. styleProvider`](https://umijs.org/docs/max/antd#styleprovider) 来配置解决。

如果你是自己的 antd ，就自己在运行时配置 [rootContainer](https://umijs.org/docs/api/runtime-config#rootcontainerlastrootcontainer-args) 自己套一层。

如还有问题，需要提供一个最小复现。
