### ISSUE TITLE
在vue3+typescript+vite中如何使用@umijs/max-plugin-openapi

### ISSUE THREAD

**Issue by apchenjun** [umijs/umi#11332]
我用了这些插件都不能正常使用，是在vue中部能用还是用别的插件代替了。
@umijs/max-plugin-openapi
@umijs/plugin-openapi
@umijs/openapi

**Comment by fz6m** [comment]
目前几乎所有的插件都不支持 vue 项目，umi 是 react 的框架，vue 支持只是一个小 feature ，来帮助企业内统一脚手架，使用 vue 时，你需要自己编写、解决扩展问题。
