### ISSUE TITLE
umi max 打包后

### ISSUE THREAD

**Issue by totoago** [umijs/umi#11337]
打包后可以是
![image](https://github.com/umijs/umi/assets/65659988/712c80c1-de7c-4a2a-9ab8-41b0e4ef2100)
这4个文件吗？

**Comment by fz6m** [comment]
不可以，但是你可以通过添加额外的 [babel 插件](https://umijs.org/docs/introduce/faq#%E5%8F%AF%E4%BB%A5%E5%85%B3%E9%97%AD-dynamicimport-%E5%90%97) 来关闭自动拆包，可以避免一大堆 `.js` 文件被拆出来，尽可能汇总到一个 `umi.js` 文件里。这种方法不能避免图片等资源被自动拆出来，除非你确定可以承担风险（确定本地构建一定生成这几个文件），否则产物应该整体去部署。
