### ISSUE TITLE
[Bug] 配置runtimePublicPath: {},异步加载的静态文件请求路径没有更新为window.publicPath

### ISSUE THREAD

**Issue by DouDou-Ya** [umijs/umi#11339]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
需要给一个最小复现。

**Comment by siadou** [comment]
我也遇到了一样的问题，设置了publicPath为/public/，mfsu加载入口文件的path没有替换为window.publicPath，仍然是/public/。publicPath 是‘/’的时候是正常的，版本是v3.5.40

**Comment by fz6m** [comment]
umi 3 已经不维护了，建议升级到 umi 4
