### ISSUE TITLE
使用dva + umi 生产环境打包出错

### ISSUE THREAD

**Issue by xiaomei628** [umijs/umi#1133]
生产环境打包出错如下：
<img width="918" alt="wx20180926-160211 2x" src="https://user-images.githubusercontent.com/15361002/46065808-ab26a000-c1a5-11e8-9735-3521355f770f.png">

请问怎么处理这个错误

**Comment by sorrycc** [comment]
这是 umi@1 吧？参考 https://github.com/sorrycc/blog/issues/68

**Comment by xiaomei628** [comment]
我安装了es5-imcompatible-version,在.webpackrc.js配置了es5ImcompatibleVersions: true,打包还是一样的错误

**Comment by sorrycc** [comment]
`COMPRESS=none umi build` 后打开 umi.js 的第 40460 行，看下是什么。（40460 来自你上面的错误日志）

**Comment by xiaomei628** [comment]
使用了dva-model-extend，才导致报错的，有什么包可以替代它的吗

**Comment by xiaomei628** [comment]
我使用dva-model-extend来进行model合并，不过引用那个model，会报这个错，不知道为什么
![image](https://user-images.githubusercontent.com/15361002/46073011-6fe09d00-c1b6-11e8-9319-1847bca43492.png)
![image](https://user-images.githubusercontent.com/15361002/46073034-7b33c880-c1b6-11e8-99e3-fbcb33fa8fb6.png)
在开发环境下没错，不知道为啥打包就不行了

**Comment by xiaomei628** [comment]
打包里面错误代码：
![image](https://user-images.githubusercontent.com/15361002/46073203-d665bb00-c1b6-11e8-84a3-df0ee65e367d.png)

**Comment by sorrycc** [comment]
> 在开发环境下没错，不知道为啥打包就不行了

因为打包时会做压缩。

**Comment by xiaomei628** [comment]
就是不知道为什么引用那个model来进行合并的时候，会出现这个问题，不引就不会
