### ISSUE TITLE
[Bug] 配置了runtimePublicPath: {}，异步加载的文件路径不是window.publicPath

### ISSUE THREAD

**Issue by DouDou-Ya** [umijs/umi#11340]
## What happens?

Config.ts文件 配置了生产环境下runtimePublicPath: {},项目打包使用默认的异步加载，打包部署后只有index.html 文件引用的文件调用路径正常，前缀为 window.publicPath，异步加载的静态文件请求路径没有更新为window.publicPath，使用的依然是window.location 的地址
## Mini Showcase Repository(REQUIRED)

![e24f77d573bfd6f894a372dc6c1b16c](https://github.com/umijs/umi/assets/37927327/d20629b0-0663-44e9-b885-39fb3f34438a)

举例如下：
打印的window.publicPath：https://baidu.com/
js的请求路径：https://baidu.com/umi.js
*.async.js的请求路径为：https://******.com/*.async.js   (******为项目环境host)

## How To Reproduce

config.ts文件

`import { defineConfig } from 'umi';
export default defineConfig({
  publicPath:'https://baidu.com/',
  runtimePublicPath: {}
})
`

global.tsx 文件

`if(预发){
window.publicPath=‘https://dev.baidu.com/’
}else if(正式){
window.publicPath=‘https://baidu.com/’
 }
`

## Context

- **Umi Version**:4.0.71
- **Node Version**:14.15.0
- **Platform**:

**Comment by fz6m** [comment]
`global.ts` 的时机已经是 webpack 启动代码之后，umi 应用启动之前了，需要更早的时机全局设定 `publicPath` ，放在 `headScripts` 里：

```ts
  runtimePublicPath: {},
  headScripts: [
    'window.publicPath = "http://domain.com/"',
  ]
```

**Comment by iWATCHDOG** [comment]
> `global.ts` 的时机已经是 webpack 启动代码之后，umi 应用启动之前了，需要更早的时机全局设定 `publicPath` ，放在 `headScripts` 里：
> 
> ```ts
>   runtimePublicPath: {},
>   headScripts: [
>     'window.publicPath = "http://domain.com/"',
>   ]
> ```

这么设置了，没有用啊，还是丢失啊

**Comment by fz6m** [comment]
如有问题，需要给一个最小复现。

**Comment by tanabalu** [comment]
> > `global.ts` 的时机已经是 webpack 启动代码之后，umi 应用启动之前了，需要更早的时机全局设定 `publicPath` ，放在 `headScripts` 里：
> > ```ts
> >   runtimePublicPath: {},
> >   headScripts: [
> >     'window.publicPath = "http://domain.com/"',
> >   ]
> > ```
> 
> 这么设置了，没有用啊，还是丢失啊
> 
> publicPath: './', runtimePublicPath: {}, headScripts: [ 'window.publicPath = "./"', ],

看看这篇文章：https://www.jianshu.com/p/c880b59823a6

我也遇到了同样的问题，子应用的index.html和umi.[hash].js/css都能访问到，到chunk资源时publicPath就丢失了。
我原始的entry配置是：`/scql`，服务端会自动把这个路径重定向到`/scql/static/index.html`，所以我的主资源可以访问到，但是chunk资源publicPath路径丢失。我是看了这篇文章发现了端倪：

![image](https://github.com/umijs/umi/assets/26920071/3bacdebf-5363-43c1-bfd8-c78b04e4732f)

我的entry配置是`/scql`，按照这个说法，qiankun会删掉`scql`这个路径去拼接资源访问，也就是索引chunk资源时直接使用了`/`根路径，这跟我的情况相匹配。

于是我直接把entry改成了`/scql/static/index.html`，同样按照上述说法，qiankun拼接url的时候把`index.html` 被删掉了，然后我所有的chunk资源都是用了`/scql/static`这个路径来拼接，既达成了主入口访问的目的，也达成了chunk资源访问路径无误的目的。
