### ISSUE TITLE
[Bug] hash模式下，touch事件路由跳转，路由历史栈丢失

### ISSUE THREAD

**Issue by bingyang519** [umijs/umi#11342]
背景：
APP端内h5开发，在Android的webview中发现此问题。在手机百度浏览器APP中复现，在电脑端Chrome和edge手机模式下，偶尔复现。

问题：
打开页面 a,  通过touch事件触发a页面某个元素，跳转到路由b，然后手机侧滑返回。此时并未返回到a页面，而是返回到了上上页面。

操作环境：
umi最新版，hash路由模式
华为p40，鸿蒙3
手机百度版本：13.35.0.11

复现代码：
https://github.com/bingyang519/umi-demo

复现步骤：

1. 访问 /test
2. 点击 test
3. 浏览器返回

复现视频：
https://github.com/bingyang519/umi-demo/blob/main/%E6%BC%94%E7%A4%BA.mp4

**Comment by fz6m** [comment]
可以看看构建完的产物有没有这个问题。

umi 是一个面向中后台 toB 、构建 SPA 的框架，不适合构建手机端项目。

另外，如果普通路由没有问题，就不要用 hash 路由。

**Comment by bingyang519** [comment]
> 
1、构建产物有问题
2、嗯
3、用不用hash路由跟业务有关，这个得根据项目情况。
