### ISSUE TITLE
umiMax版本中的微前端架构接入子应用的页面缓存问题。

### ISSUE THREAD

**Issue by HangCloud** [umijs/umi#11356]
通过内置的qiankun接入了一个子应用，然后在主应用的路由当中配置了对应路由，路由渲染在主应用的tab页卡当中，主应用的路由在tab切换时，组件不会重复加载(应用正常)，子应用的页面在tab激活时，会重新加载，导致页面重新渲染、状态丢失、接口重新请求等问题。查看dom结构发现有销毁。问题是怎么缓存子应用的页面内容。

**Comment by HangCloud** [comment]
请问有相应的配置可以实现子应用页面缓存吗？在文档中没有发现相应配置。

**Comment by fz6m** [comment]
react 现在没有 keep alive 的设计，所以 react 应用目前都没有正常的缓存方法，不建议使用页面缓存。

**Comment by HangCloud** [comment]
> react 现在没有 keep alive 的设计，所以 react 应用目前都没有正常的缓存方法，不建议使用页面缓存。

主应用引入子应用的页面作为主应用的tab页卡之一，在tab切换到其他卡片时，子应用进行了销毁，这样会引起不必要的消耗，有合适的解决方案吗？

**Comment by fz6m** [comment]
去 [qiankun](https://github.com/umijs/qiankun) 研究下吧。

共存的时候，memory history 路由应该可以解这个问题，在这个情况下每个子应用不会影响 url 路由，但缺点是刷新页面就丢失路由了，可能需要 local storage 等方法暂存一下。

另外也可以不用 qiankun ，其他的基于 iframe 的微前端方案也有共存的方法，可以自己调研下。
