### ISSUE TITLE
[Bug]  Cannot destructure property 'winPath' of 'import_umi.utils' as it is undefined.

### ISSUE THREAD

**Issue by Khadhiri786** [umijs/umi#11359]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce
After updating umijs version 3.5.23 to 4.0.72. I'm getting error while doing yarn start.
`import {  utils } from 'umi';
const { winPath } = utils;
`
Error
![image](https://github.com/umijs/umi/assets/60467237/3e77b5dc-499f-432c-a3e1-4c34acae08f1)

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0.72
- **Node Version**:16.20
- **Platform**: windows

**Comment by fz6m** [comment]
Try remove `node_modules` and reinstall, maybe it didn't resolve to the correct dependencies.

**Comment by tnsivanagarajan** [comment]
Hi @fz6m 

I'm also facing the same issue.

I have done the below steps but no luck

1. Delete the node modules folder.

2. `yarn cache clean`

3. Delete the yarn lock file.

4. `yarn cache list`

5. `yarn install`

6. `yarn start` 

Facing the same error once after updating the umi version v3 to v4

  [cause]: TypeError: Cannot destructure property 'winPath' of 'import_umi.utils' as it is undefined.

`import { defineConfig, utils } from 'umi';`

`const { winPath } = utils;`

**Comment by fz6m** [comment]
In Umi 4, you should import `winPath` from 'umi/plugin-utils' :

```ts
import { winPath } from 'umi/plugin-utils'
```

**Comment by Khadhiri786** [comment]
@fz6m  I tried this
`import { winPath } from 'umi/plugin-utils'`
I'm getting this error.
![image](https://github.com/umijs/umi/assets/60467237/53857367-52d8-4507-9049-427b05d747b6)

**Comment by buquan** [comment]
> ```ts
> umi/plugin-utils
> ```

请教个问题，`import { winPath } from '@umijs/utils';` 我这么引入也可以，但是node_modules里并没有这个文件夹，执行`max dev`时候这个路径大概是怎么转化的

**Comment by fz6m** [comment]
如果你没显示的安装 `@umijs/utils` 还能导入，说明你用的是 npm / yarn 这种有幽灵依赖的，你导入了不一定哪个版本、哪个依赖附属的幽灵依赖，所以你可以偷偷的不规范使用（如果要显示导入来用的话，还是应该显示安装）。

或者你就直接导入 `umi/plugin-utils` ，这个文件里面就是 re export `export * from '@umijs/utils'` ，用了 `umi` 依赖的 `@umijs/utils` ，这样可靠一些，因为 umi 依赖的 `@umijs/utils` 版本和 `umi` 本身一样。

**Comment by buquan** [comment]
@fz6m 我项目用的pnpm，找了一圈node_modules真的没有，升级umi4后，很奇怪就能用😂
