### ISSUE TITLE
使用 hash router ，配置 base后打开白屏 <Router basename="/demo"> is not able to match the URL "/"

### ISSUE THREAD

**Issue by JoMartinezZhu** [umijs/umi#11351]
## What happens?
使用 hash router ，配置 base后打开白屏，浏览器控制台报warning：
 <Router basename="/demo"> is not able to match the URL "/"

## Mini Showcase Repository(REQUIRED)

最小重现：使用 pnpm dlx create-umi@latest 创建一个 antd-pro 项目修改config.ts 为：
`import { defineConfig } from '@umijs/max';

  export default defineConfig({
    antd: {},
    access: {},
    model: {},
    initialState: {},
    request: {},
    layout: {
      title: '@umijs/max',
    },
    routes: [
      {
        path: '/',
        redirect: '/home',
      },
      {
        name: '首页',
        path: '/home',
        component: './Home',
      },
      {
        name: '权限演示',
        path: '/access',
        component: './Access',
      },
      {
        name: ' CRUD 示例',
        path: '/table',
        component: './Table',
      },
    ],
    base: '/demo/',
    hash: true,
    history: {
      type: 'hash',
    },
    npmClient: 'pnpm',
  });`

然后 pnpm start，打开浏览器就会白屏

https://github.com/JoMartinezZhu/umi4-demo.git

- **@umijs/max**:  ^4.0.72
- **Node Version**: 16.20.1
- **Platform**: mac intel

**Comment by fz6m** [comment]
hash 路由需要自己访问正确的地址，比如 `http://localhost:8000/#/demo/` 、`http://localhost:8000/#/demo/table`
