### ISSUE TITLE
[Bug] umi@4 不用max难道就不能使用运行时的request配置？

### ISSUE THREAD

**Issue by flycocke** [umijs/umi#11350]
在src/app.tsx 加了
export const request = {
  timeout: 1000,
  // other axios options you want
  errorConfig: {
    errorHandler(){
    },
    errorThrower(){
    }
  },
  requestInterceptors: [],
  responseInterceptors: []
};
就直接报错了
Unhandled Rejection (Error): register failed, invalid key request from plugin

**Comment by fz6m** [comment]
umi 4 本身没有带任何额外的插件，max 是 umi 4 + 内置了很多插件可以即开即用，如果图方便，就直接用 max ，按需打开插件。

umi 4 单独使用插件的方法在 [这里](https://umijs.org/docs/guides/use-plugins) ：

```bash
  pnpm i -D @umijs/plugins
```

```ts
// .umirc.ts

export default {
  plugins: ['@umijs/plugins/dist/request'],
  request: {}
}
```
