### ISSUE TITLE
[Bug]umi3开启workerLoader后报错

### ISSUE THREAD

**Issue by fssh** [umijs/umi#11352]
package.json中配置如下：
"umi": "^3.5.14",
 "@umijs/preset-react": "^1.8.22",
 "@umijs/test": "^3.5.14",

.umirc中配置workerLoader:{}

启动服务会报错：
![image](https://github.com/umijs/umi/assets/18034841/047f6527-e7fa-49d1-98e3-f413153968b4)

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4
