### ISSUE TITLE
[Bug] umi中的pro-components依赖能去掉吗？ 升级umi4多了个pro-components， 我只用pro-layout这一个插件。能否像umi3那样按需引入？

### ISSUE THREAD

**Issue by pc110** [umijs/umi#11361]
umi中的pro-components依赖能去掉吗？ 升级umi4多了个pro-components， 我只用pro-layout这一个插件。能否像umi3那样按需引入？

umi3的引入方式
![1688480138594](https://github.com/umijs/umi/assets/29336835/b28d41ba-42a8-42b2-a9d6-e8e139406dea)
node_modules中没有pro-components
![1688480211629](https://github.com/umijs/umi/assets/29336835/c2afd409-8aea-42cd-8e69-cd6dc52b84dd)

升级umi4后，多了个pro-components，
![bd619a324aea8d6c3c3e6b1f9f43687](https://github.com/umijs/umi/assets/29336835/207d3d94-578c-406f-9ddb-8c9eb6dd4fdd)
![4c48356fbd930fda1ddad2a51749f00](https://github.com/umijs/umi/assets/29336835/392f8f4e-c5b4-4c82-8dcb-3b870c2d728f)

能去掉这个pro-components依赖吗？

**Comment by fz6m** [comment]
如果你用了 umi layout 插件（max 项目），这个 layout 就需要依赖 pro component ，不用在意它背后是如何依赖的。

如果你发生了 react 多实例问题，可以尝试升级 umi 至最新版本，排查下是不是依赖错乱导致的，删除 `node_modules` 重装依赖，再尝试看看行不行。

如果还不行，可以尝试关闭 `mfsu: false` 。

最后还有问题的话，需要提供一个最小复现帮助排查问题。
