### ISSUE TITLE
[Bug] umi4新版本创建的项目，左侧菜单样式混乱

### ISSUE THREAD

**Issue by pc110** [umijs/umi#11362]
选中二级菜单，收起展开侧边栏的时候，有文字重影
请看视频：
https://github.com/umijs/umi/assets/29336835/74ab8e4f-7e8f-4da2-9ef1-11008adf29dc

**Comment by fz6m** [comment]
这个是 pro components 的 layout 细节问题，去 [pro-components](https://github.com/ant-design/pro-components) 反馈或者 PR 解决吧。
