### ISSUE TITLE
[Bug] useRouteMatch,connect is not working while upgrading umijs v4

### ISSUE THREAD

**Issue by Khadhiri786** [umijs/umi#11369]
## What happens?
While upgrading umijs v3 to umijs v4, I'm getting error

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
See #11368
