### ISSUE TITLE
[Bug] AssertionError [ERR_ASSERTION]: Invalid config keys: dva, locale

### ISSUE THREAD

**Issue by Khadhiri786** [umijs/umi#11367]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce
I'm gettting issue while upgrading umijs v3 to umijs v4

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:4.0.72
- **Node Version**:16
- **Platform**: windows

**Comment by fz6m** [comment]
```bash
  pnpm i -D @umijs/plugins
```

```ts
// .umirc.ts

export default {
  plugins: [
    '@umijs/plugins/dist/dva'
  ],
  dva: {}
}
```

For all plugins see [packages/plugins/src](https://github.com/umijs/umi/tree/master/packages/plugins/src)
