### ISSUE TITLE
umi 目前不兼容 react-tap-event-plugin ， 移动端项目使用

### ISSUE THREAD

**Issue by devmsg** [umijs/umi#1136]
umi 目前不兼容 react-tap-event-plugin ， 移动端项目使用

`injectTapEventPlugin = require("react-tap-event-plugin");
injectTapEventPlugin();`

怎么解决呢？

**Comment by devmsg** [comment]
![image](https://user-images.githubusercontent.com/15261658/46073642-15484080-c1b8-11e8-8130-49787edc66af.png)

**Comment by devmsg** [comment]
![image](https://user-images.githubusercontent.com/15261658/46073654-1d07e500-c1b8-11e8-96f0-76d059ec70fd.png)

**Comment by sorrycc** [comment]
这个插件已经 deprecated，并且不支持 react@16.4 及以上版本，你可以在项目中依赖 react@16.3 解决。
