### ISSUE TITLE
[Bug] 需要完全删除o

### ISSUE THREAD

**Issue by oxygen-xx** [umijs/umi#11378]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
这种情况一般是 npm / yarn 的依赖错乱引起的，umi 更推荐使用 pnpm ，不会有这种情况。

如有问题，需要提供一个最小复现。

**Comment by oxygen-xx** [comment]
> 这种情况一般是 npm / yarn 的依赖错乱引起的，umi 更推荐使用 pnpm ，不会有这种情况。
> 
> 如有问题，需要提供一个最小复现。

我发现，pnpm也有问题，最近从8.8.0升级到8.9.2之后，我的项目必须重复的引入所有的ant-pro-components包，包括dayjs才可以pnpm start来启动。  我以为这是pnpm或ant pro components的关系，就把所有的版本都回退了。结果还是解决不了这个问题。如果删除了node_modules，用yarn重新安装，完全没有任何问题。  如果删除了node_modules，再用pnpm安装，到是可以安装，但是pnpm start就起不来了，报
error - AssertionError [ERR_ASSERTION]: dependence not found: dayjs
node_modules/.pnpm/@umijs+mfsu@4.0.83/node_modules/@umijs/mfsu/dist/dep/dep.js:90:31

**Comment by fz6m** [comment]
如果你有一份正确的 pnpm lock 文件，能正常运行项目，再升级新的 pnpm 版本，lock 文件不会因此而改变，因为 pnpm v8 没有影响 lock 文件格式的改动，所以和 pnpm 版本号无关，因为 lock 文件是正确的，那么每次安装的依赖都是固定的。

所以你需要在正常运行项目的时候，正确生成一份 lock 文件才可以保证项目正常。

假如你有 pnpm lock 文件还运行的好好的，换成 yarn 去重新安装依赖，这个时候没有 yarn lock 文件，它就会全部安装最新版本的依赖，可能存在 Breaking change ，所以不可以这么做，会发生隐患，假如你发现最新的依赖是没问题的，那你就手动升级一下 package.json 里可能存在问题的依赖的版本到最新再 pnpm i 。

另外确保你使用的是最新的 umi 版本，假如你用了 pro components ，最好手动显示安装一份到 package.json ，这样使用的就是你安装的这个依赖，更安全。

另外如果提示 mfsu not found 依赖这样的报错，可以尝试删掉 `node_modules/.cache` 再重启下项目，排除 mfsu 缓存问题，如果还有问题，可以给一个最小复现，或者关闭 `mfsu: false` 。
