### ISSUE TITLE
[Bug] 需要完全删除node_modules才可以编译正确

### ISSUE THREAD

**Issue by oxygen-xx** [umijs/umi#11379]
## What happens?
每次编译后，我们发现，在表单提交后，日期格式是这样的：{"$L"=>"zh-cn", "$y"=>2023, "$M"=>6, "$D"=>6, "$W"=>4, "$H"=>9, "$m"=>8, "$s"=>32, "$ms"=>379}
只有完全的删除node_modules再次重新yarn install，再编译才可以让日期字段提交的时候格式正确。

有一些细节需要说明，在升级其它组件时，比如pro-components，antd等等，我们并没有关闭服务，而是直接yarn install的。
上面的日期格式问题，必须要完全删除node_modules再编译的问题，已经存在很久了。但不是每次动态升级组件时都发生，但偶尔是会发生，一但发生这种情况，不删除node_modules目录根本不行，删除.umi相关目录也解决不了问题。

## Context

- **Umi Version**:     "@umijs/max": "4.0.72",
- **Node Version**:  v18.16.1
- **Platform**: MacOS 13.4.1

**Comment by fz6m** [comment]
这种情况一般是 npm / yarn 的依赖错乱引起的，umi 更推荐使用 pnpm ，不会有这种情况。

如有问题，需要提供一个最小复现。

**Comment by oxygen-xx** [comment]
> 

不能百分百的复现。现在我们只有换pnpm试试了。
但是用yarn，这种情况经常发生。yarn 版本是 1.22.19 
那后期转pnmp吧。
