### ISSUE TITLE
Umi tests return exit code 0 after failing tests

### ISSUE THREAD

**Issue by ja573** [umijs/umi#1137]
Running tests using umi 2.0.3 always returns exit code 0, regardless of the tests results.

```
$ node --version
v10.11.0
$ npm --version
6.4.1
```

```
$ npm test # umi test
[...]
Test Suites: 1 failed, 9 passed, 10 total
Tests:       1 failed, 43 passed, 44 total
Snapshots:   0 total
Time:        23.888s
Ran all test suites.
$ echo $?
0
```

**Comment by ja573** [comment]
Thank you for fixing this @sorrycc - may I ask in which release are you planning to include the change?

**Comment by sorrycc** [comment]
umi@2.1.0, it's planned to be released tomorrow.
