### ISSUE TITLE
[Feature Request] getInitialState能否从app.ts的default取

### ISSUE THREAD

**Issue by PopperLi** [umijs/umi#11384]
## Background

我有N多项目需要维护同一份运行时配置，所以打算抽象为一个依赖包通过一个函数导出所有配置。结果发现`getInitialState`不生效，
看了下`initial-state`的逻辑发现配置仅从`@/app`的`exports`中获取，既然umi中支持`defineApp`导出运行时配置，那么`getInitialState`是否也能放到里面？

虽然export * 也可以解决此类问题，但还是希望能够得到支持。

## Proposal

建议运行时配置`getInitialState`支持在`default`对象中导出。

**Comment by fz6m** [comment]
目前 `defineApp` 的实现有缺陷，不能支持在里面使用 `getInitialState` ，所以应该 `export const getInitialState` 这样具名导出来使用。

如果你有相同的逻辑，就这样写吧：

```ts
// src/app.ts

import { createGetInitialState } from 'your-package'

export const getInitialState = createGetInitialState({
  // config ...
})
```
