### ISSUE TITLE
[Bug] qiankun子应用配置publicPath，部分js加载时路径丢失

### ISSUE THREAD

**Issue by puddingnet** [umijs/umi#11388]
## What happens?

子应用配置了publicPath，主应用加载子应用时，umijs可以带路径加载成功，vendor等js加载时，请求地址丢失了publicPath，导致加载失败

## Mini Showcase Repository(REQUIRED)

https://github.com/puddingnet/umi-max-qiankun.git

## How To Reproduce

1. 主应用 master 运行 pnpm start，端口8000
2. 子应用 slave 运行 pnpm start，端口8001
3. 访问地址：http://localhost:8000/slave

报错：
Unhandled Rejection (ChunkLoadError): Loading chunk vendors-node_modules_pnpm_umijs_bundler-webpack_4_0_72_styled-components_6_0_2_typescript_5_1-49330c failed.
(missing: http://localhost:8001/vendors-node_modules_pnpm_umijs_bundler-webpack_4_0_72_styled-components_6_0_2_typescript_5_1-49330c.async.js)

从网络请求中看到 http://localhost:8001/vendors-node_modules_pnpm.......js 请求路径没有publicPath 

## Context

- **Umi Version**: 4.0.72
- **Node Version**: v16.14.2
- **Platform**: Windows

**Comment by fz6m** [comment]
仓库是空的，需要给一个最小复现。

**Comment by puddingnet** [comment]
> 仓库是空的，需要给一个最小复现。

已push代码

**Comment by fz6m** [comment]
在 qiankun 的约定里，应用的异步资源应该从 `window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__` 开始加载，这个值在 umi 里固定是子应用配置里的 `entry: '//localhost:8001/'` ，于是他会去 `//localhost:8001/some.async.js` 加载，这是不对的，正确的位置是 `//localhost:8001/slave-path/some.async.js` ，所以这个地方不符合约定。

所以我们要把 `entry` 改成 `//localhost:8001/slave-path/` ，这样才能让异步资源加载正确。

但这么做时，你要确保在生产环境里 `//domain.com/slave-path/` 能获取到子应用的 `index.html` ，如果 `/slave-path/*` 这个产物资源目录里就有这个 `/slave-path/index.html` 是可以的，如果没有（自己改了产物结构），需要通过 nginx 重写到对应的 `index.html` 。

**Comment by ambres** [comment]
@fz6m ,您好，我也有存在相同的问题，现在是index.html正确加载，umi.[hash].js也是正确加载的，publicPath都是生效的，只有通过umi.[hash].js读取的**.[hash].async.js并未拼接publicPath。
比如我子应用入口是www.xx.com/auth。
1.www.xx.com/auth/index.html加载正常
2.通过www.xx.com/auth/index.html加载的www.xx.com/auth/umi.[hash].js加载正常
3.通过www.xx.com/auth/umi.[hash].js加载分包文件**.[hash].async.js不正常，正确路径是www.xx.com/auth/**.[hash].async.js，但现在加载的是www.xx.com/**.[hash].async.js，缺失了publicPath

**Comment by ambres** [comment]
@fz6m 已解决，参考 #11340 ， 
headScripts: [
    { src: '/scripts/loading.js', async: true },
    'window.publicPath = "http://xxx.com/auth/"',
    'window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__ = "http://xxx.com/auth/"'
  ],
