### ISSUE TITLE
react-transition-group在hash路由下无效

### ISSUE THREAD

**Issue by liuyongjin** [umijs/umi#1138]
react-transition-group在hash路由下无效，在browser路由模式下有效
![image](https://user-images.githubusercontent.com/27352340/46083497-2acb6380-c1d4-11e8-865e-55fe559500e9.png)

![image](https://user-images.githubusercontent.com/27352340/46083467-1dae7480-c1d4-11e8-8c04-24699ad95c89.png)

**Comment by sorrycc** [comment]
请给出可重现的库。

**Comment by liuyongjin** [comment]
不懂，哈哈，不过问题解决了，好像是Key的问题
