### ISSUE TITLE
[Bug] Node modules issue after upgrading umijs v3 to v4.

### ISSUE THREAD

**Issue by Khadhiri786** [umijs/umi#11385]
## What happens?
![image](https://github.com/umijs/umi/assets/60467237/5bff625e-948d-437f-81d5-f970f5a0bc8e)
![image](https://github.com/umijs/umi/assets/60467237/c2173d3f-9de9-48d6-bc79-cc2351ec02bc)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:4.0.72
- **Node Version**:16
- **Platform**: windows

**Comment by fz6m** [comment]
In umi 4, you should remove all `@umijs/plugin-xxx` packages and install `@umijs/plugins` and enable it.

```bash
  pnpm i -D @umijs/plugins
```

```ts
export default {
  plugins: [
    '@umijs/plugins/dist/antd'
  ],
  antd: {} // same as `@umijs/plugin-antd`, you should remove `@umijs/plugin-antd`
}
```

**Comment by Khadhiri786** [comment]
@fz6m  I'm getting this issue now after added the changes.
![image](https://github.com/umijs/umi/assets/60467237/3b0fe4cb-f28b-46c8-a05d-f91db142f505)
