### ISSUE TITLE
[Bug] 开发模式下，开启mfsu,  extraBabelIncludes参数不生效；

### ISSUE THREAD

**Issue by codertony** [umijs/umi#11380]
## What happens?
monorepo项目，希望umi项目能够编译解析 包含@km-r的依赖组件；

package.json
```
  "dependencies": {
    "umi": "^4.0.72",
    "@km-r/home-block": "workspace:*"
  },
```

umi配置：
```
{
  mfsu: {
    esbuild: true,
  },
  extraBabelIncludes: [/@km-r/],
}
```
extraBabelIncludes参数没有效果，没有热更新；
如果设置mfsu为false，则正常；

## Context

- **Umi Version: 4.0.72
- **Node Version: v16.16.0
- **Platform: window10

**Comment by fz6m** [comment]
`mfsu.esbuild` 开启的时候依赖用的是 esbuild 来转译的，没走 babel ，把这个选项去掉或者关闭 mfsu 看看。

另外可以尝试下排除处理这个依赖：

```ts
  mfsu: {
    exclude: ['@km-r/home-block']
  }
```

如还有问题，需要给一个最小复现。
