### ISSUE TITLE
[Bug] Node modules error while upgrading umijs v3 to v4

### ISSUE THREAD

**Issue by Khadhiri786** [umijs/umi#11387]
## What happens?
![image](https://github.com/umijs/umi/assets/60467237/64dbfb91-cbb5-4d54-bd0d-33c1ee2bc6f5)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:4.0.72
- **Node Version**:16
- **Platform**:windows

**Comment by fz6m** [comment]
You don't need the `@umijs/plugin-antd/node_modules/antd`, now we use the manually installed `.less` style file in `antd`:

```bash
  pnpm i -D antd@^4
```

```diff
- @import '~@umiis/plugin-antd/node_modules/antd/lib/style/themes/default.less";
+ @import 'antd/lib/style/themes/default.less";
```

If there are still problems, please provide a minimal reproduction

**Comment by Khadhiri786** [comment]
@fz6m  I don't have path in node modules as `@import 'antd/lib/style/themes/default.less';`
