### ISSUE TITLE
Extend page generator

### ISSUE THREAD

**Issue by lemol** [umijs/umi#1139]
I'm developing a plugin that needs new files to be generated on calling the page generator. For example: the command `umi generate page index` instead of creating the usal files, I need my plugin to create aditional files also.

Is it posible to do this with umi plugin development?

**Comment by lemol** [comment]
I ended up writing a new generator `api.registerGenerator('my:page', {})` that extends the page generator in this way:

```js
import pageGenerator from 'umi-build-dev/lib/plugins/commands/generate/page';

export default api => {
  const PageGenerator = pageGenerator(api);

  return class Generator extends PageGenerator {
    writing() {
      super.writing();
    }
  }
}
````

So I can use it with `umi generate my:page users`, and I think it is ok for me.

**Comment by sorrycc** [comment]
Yes, this is the recommended way.
