### ISSUE TITLE
[Feature Request] 怎么做到用户登录后，根据用户权限动态加载路由，然后刷新路由配置？

### ISSUE THREAD

**Issue by konayukis** [umijs/umi#11395]
## Background

怎么做到用户登录后，根据用户权限动态加载路由，然后刷新路由配置？
示例中只有渲染前根据 `patchClientRoutes ` 修改路由配置，程序渲染完之后怎么手动修改路由？

## Proposal
在程序运行的任意节点，支持手动修改路由、重新加载路由配置

**Comment by jiajiaxing1** [comment]
> See #11394
> 
> 不支持在程序运行中更改路由表，只能刷新页面重载，在 `patchClientRoutes` 里更改路由表。
> 
> 或者把所有路由都开放出来但是根据用户权限来隐藏菜单，之后页面内容用 auth context 包一层鉴权防止直接访问。

请教一下 ‘或者把所有路由都开放出来但是根据用户权限来隐藏菜单’ ，用户权限其实也是需要在登录之后才能获取到，在初始化render的时候还是获取不到，所以有没有可以在代码层可以手动重新render的方法呐？ 不然还是只能reload整个页面体验不太好

**Comment by fz6m** [comment]
不可以在运行时刷新路由表，reload 重新刷新页面是必须的，为此我们可以在 `render` 时先去获取这个用户拥有的路由列表，之后在 `patchClientRoutes` 阶段添加好这个用户的路由表。

当获取路由表时，用户可能没有权或者权过期了，此时根据响应码跳转到登录页面登录，登录结束后刷新页面回跳（可以拼接 redirect url 在路径上）。

**Comment by jiajiaxing1** [comment]
好滴 了解了，目前就是觉得reload的体验不太好，看来reload是必须的

**Comment by jianshe** [comment]
@jiajiaxing1 你好 想问一下 这个最后用reload方式来解决了嘛 我也觉得这种方案很不好，这样写浏览器还会给予弹窗提示：重新加载此网站？系统可能不会保留您所做的修改！ 你那边有更好的解决方案嘛 求教。

**Comment by jiajiaxing1** [comment]
> jianshe

最终采用的location.replace

**Comment by crizydevl** [comment]
有点无语
