### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by lvbukai86** [umijs/umi#11397]
## What happens?

 D:\code\TMS-admin\src\.umi\uno.css Unknown word

  44 | [checked~="\?"]:checked{animation:__un_qm 0.5s ease-in-out alternate infinite;}
  45 | @keyframes __un_qm{0%{box-shadow:inset 4px 4px #ff1e90, inset -4px -4px #ff1e90}100%{box-shadow:inset 8px 8px #3399ff, inset -8px -8px #3399ff}}
> 46 | [disabled~="\?"]:disabled{animation:__un_qm 0.5s ease-in-out alternate infinite;}ase-in-out alternate infinite;}
     |                                                                                  ^

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

当我在 <ProCard gutter={8} title={renderTitle()}>编写renderTitle()的方法时报错以下错误，重启后消失。

日志如下：
{"level":50,"time":1688981865315,"pid":11584,"hostname":"LAPTOP-5RJMHJUP","msg":"./src/.umi/uno.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].oneOf[1].use[1]!./node_modules/@umijs/bundler-webpack/compiled/postcss-loader/index.js??ruleSet[1].rules[4].oneOf[1].use[2]!./src/.umi/uno.css"}

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
给一个最小复现看看。

**Comment by lvbukai86** [comment]
触发时间不固定，热更新代码的时候经常报这个错，重开后消失

---Original---
From: ***@***.***&gt;
Date: Mon, Jul 10, 2023 21:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [umijs/umi] [Bug] say something (Issue #11397)




 
给一个最小复现看看。
