### ISSUE TITLE
[Bug] 编译报错 esbuild minniy failed

### ISSUE THREAD

**Issue by starkbtc** [umijs/umi#11402]
## What happens?

esbuild minify failed, please change jsMinifier or upgrade target:
e.g. 
  jsMinifier: 'terser'
   or
  jsMinifierOptions: {
    target: ['chrome80', 'es2020']
  }
P.S. compatible with legacy browsers: https://umijs.org/blog/legacy-browser

fatal - Error: ERROR in 336.4400f260.async.js
336.4400f260.async.js from Terser plugin
Transform failed with 52 errors:
336.4400f260.async.js:12208:39: ERROR: Big integer literals are not available in the configured target environment ("chrome80", "es2015")
336.4400f260.async.js:12208:45: ERROR: Big integer literals are not available in the configured target environment ("chrome80", "es2015")
336.4400f260.async.js:12208:52: ERROR: Big integer literals are not available in the configured target environment ("chrome80", "es2015")
336.4400f260.async.js:12223:31: ERROR: Big integer literals are not available in the configured target environment ("chrome80", "es2015")
336.4400f260.async.js:12223:37: ERROR: Big integer literals are not available in the configured target environment ("chrome80", "es2015")
...
Error: Transform failed with 52 errors:
336.4400f260.async.js:12208:39: ERROR: Big integer literals are not available in the configured target environment ("chrome80", "es2015")
336.4400f260.async.js:12208:45: ERROR: Big 

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
默认使用的 esbuild 压缩器目标是 es6 ，所以不支持 Big int ，根据控制台报错提示，你需要改用 terser 来压缩，或者提高 esbuild 压缩产物目标都可以。

```ts
esbuild minify failed, please change jsMinifier or upgrade target:
e.g.
  // 🟢 换压缩器
  jsMinifier: 'terser'
or
  // 🟢 提高压缩产物版本
  jsMinifierOptions: {
    target: ['chrome80', 'es2020']
  }
```

**Comment by jaluik** [comment]
上面的解决方案貌似会调整target的版本。如果是esbuild 关于big int报错，并且不想调整target的话，可以试试这个：
```
  jsMinifierOptions: {
     supported: {
        'bigint': false,
      },
  }
```

**Comment by jiyu-sheng** [comment]
> 上面的解决方案貌似会调整target的版本。如果是esbuild 关于big int报错，并且不想调整target的话，可以试试这个：
> 
> ```
>   jsMinifierOptions: {
>      supported: {
>         'bigint': false,
>       },
>   }
> ```

这个试下来好像不 work
