### ISSUE TITLE
[Bug] 开启tailwindcss配置之后，无法在less文件中使用theme方法

### ISSUE THREAD

**Issue by vkboo** [umijs/umi#11401]
## What happens?

开启tailwindcss配置之后，无法在less文件中使用theme方法

## Mini Showcase Repository(REQUIRED)

https://github.com/vkboo/demos-umi4-issue-tailwindcss

- **Umi Version**: @umijs/max: "4.0.69"
- **Node Version**: v16.20.0
- **Platform**: M2 macOS Version 13.4.1

**Comment by fz6m** [comment]
目前 umi 的 tailwindcss / unocss 插件是侧载方式实现的，所以有一些功能缺失，如需完整的功能，可以不使用 umi 的插件，自己根据官网的文档配置 postcss 或 webpack 插件即可。

Refer：https://github.com/umijs/umi/issues/11403#issuecomment-2026736996
