### ISSUE TITLE
[Bug] 运行时配置 getInitialState 未生效

### ISSUE THREAD

**Issue by xhangjun** [umijs/umi#11409]
## What happens?

运行时配置 getInitialState 作为 defineApp 入参的字段给出时未生效。

* 在 defineApp 中定义时 getInitialState 未执行
![1 ts](https://github.com/umijs/umi/assets/53827639/840020f5-3c61-4605-8455-2ad6599afc37)

* 直接导出 getInitialState 时正常
![2 ts](https://github.com/umijs/umi/assets/53827639/5e44826c-6ac4-4135-837d-5e8d4d40ef60)

## Mini Showcase Repository(REQUIRED)

https://codesandbox.io/s/admiring-dawn-5hcxk8

**Comment by fz6m** [comment]
这个是已知问题，`getInitialState` 比较特殊，只能独立的具名导出，使用 `export const getInitialState` 。

不可以用到 `defineApp` 里 ，已有相关规范 PR #9708 ，先把它独立出来吧。
