### ISSUE TITLE
[Bug]  umi4配置antd中的compact后Cannot find module 'antd/dist/theme'

### ISSUE THREAD

**Issue by Heyunzhen** [umijs/umi#11418]
## 问题描述

我在使用项目时遇到了一个问题，具体如下：

umi4配置antd中的compact后Cannot find module 'antd/dist/theme'

## 复现步骤

开启antd功能，配置项配置antd下compact为true开启紧凑模式
yarn dev
Cannot find module 'antd/dist/theme'
## 预期行为
项目运行

## 实际行为

Cannot find module 'antd/dist/theme'

## 代码示例

import { defineConfig } from "@umijs/max";
import zhCN from 'antd/locale/zh_CN';
export default defineConfig({
  model:{},
  initialState:{},
  antd: {
    configProvider: {
      locale:zhCN
    },
    style: 'less',
    appConfig: {},
    compact:true
  },
  routes: [
    { path: "/", component: "index" },
    { path: "/docs", component: "docs" },
  ],
  npmClient: 'yarn',
});

```javascript
// 在这里插入你的代码示例

**Comment by fz6m** [comment]
antd 5 的 `compact` 还没兼容，在运行时 [`export antd`](https://umijs.org/docs/max/antd#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE) 里手动改 `algorithm` 吧。

**Comment by Heyunzhen** [comment]
谢谢您的回复，对了，还有个问题，我发现如果我没有在umirc.ts中写configProvider:{}，那么export antd根本不会运行到，这一点我不知道是我遇到的单独问题们还是确实存在

**Comment by fz6m** [comment]
是的，目前必须开启 `configProvider` 才能用。

**Comment by fz6m** [comment]
最新版本的 umi 已经兼容了 antd 5 的 `dark` / `compact` 选项，使用方式详见：https://github.com/umijs/umi/issues/10745#issuecomment-1681640434
