### ISSUE TITLE
[Bug] Node Modules Path Error

### ISSUE THREAD

**Issue by Khadhiri786** [umijs/umi#11415]
## What happens?
 I have added reference path as `@import 'antd/lib/style/themes/default.less';`
It's not in my node modules path
For More reference ,Please check below screenshot
![image](https://github.com/umijs/umi/assets/60467237/c4013a8c-9db2-4cfa-b2ce-c52ebee0d952)
#11387 

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by Khadhiri786** [comment]
@fz6m  Currently we are using and 5.2.3 version. I need to fix this issue. I have upgraded from v4 to v5

**Comment by fz6m** [comment]
antd v5 using css-in-js, just remove antd `.less` import and enable umi v4 antd plugin:

```bash
  pnpm i -D @umijs/plugins
```

```ts
// config/config.ts

export default {
  plugins: ['@umijs/plugins/dist/antd'],
  antd: {}
}
```
