### ISSUE TITLE
[Bug] useModel命名空间问题

### ISSUE THREAD

**Issue by Heyunzhen** [umijs/umi#11416]
import yayJpg from '../assets/yay.jpg';

import {useModel} from "@umijs/max"
export default function HomePage() {
  const {name} = useModel("global")
  return (
    <div>
      <h2>Yay! Welcome to umi!</h2>
      <p>
        <img src={yayJpg} width="388" />
      </p>
      <p>
        To get started, edit <code>pages/index.tsx</code> and save to reload.
      </p>
    </div>
  );
}

命名空间报错  类型“string”的参数不能赋给类型“never”的参数

复现步骤

yarn create umi 

选择simpleApp

卸载 umi 安装umi/max

umirc.js启用model

src下创建models文件夹创建index.ts的model

在首页引入@umijs/max 中的useModel

使用useMode('nameSpace') //Error  TS:类型“string”的参数不能赋给类型“never”的参数

页面报错 Cannot read properties of undefined (reading 'name')

**Comment by fz6m** [comment]
给个最小复现看看。
