### ISSUE TITLE
umi如何配置多环境

### ISSUE THREAD

**Issue by sky185959** [umijs/umi#1142]
环境有开发环境、测试环境、生成环境等 ，比如我用.umirc.local.js 表示开发环境，  .umirc.test.js表示测试环境   .umirc.prod.js表示生成环境，我如何配置环境变量，配置不同的环境接口域名也不同，官网文档感觉描述的也不清楚，请大家赐教

**Comment by sky185959** [comment]
> https://umijs.org/zh/config/#define
> 可以使用 define

![qq 20180927181549](https://user-images.githubusercontent.com/11226694/46139597-87388c80-c281-11e8-92d4-da8e126a086e.png)
我现在也使用 define配置环境变量了，现在如果编译根据不同的配置编译配置文件

**Comment by weishijun14** [comment]
package.json:
```
"start": "cross-env UMI_ENV=cloud APP_TYPE=site umi dev",
“build": "cross-env UMI_ENV=prod umi build",
```
config/config.cloud.js + config/config.prod.js + config/config.js .

done!

**Comment by tang2016** [comment]
定义的环境变量如何在其他文件中获取呢

**Comment by weishijun14** [comment]
@tang2016 
config.prod.js:
```
define: {
  process.env.a = 1
}
```
xxx.js:
```
console.log(process.env.a)   // 1
```

**Comment by NicholasNC** [comment]
1、安装 `cross-env` 插件

2、在 `.umirc.js` 文件中添加
```

// ref: https://umijs.org/config/
export default {

  define: {
    // 添加这个自定义的环境变量
    "process.env.LW_ENV": process.env.LW_ENV, // * 本地开发环境：dev，测试服：test，正式服：pro
  },

}
```

3、然后在 `package.json`文件的 scripts 中添加 `"start": "cross-env LW_ENV=awegew umi dev",`

**Comment by tonyjt** [comment]
修改了define里面的内容，npm run start 开发的时候，相关文件还是用的老的配置... 

必须用到配置的文件有更新才能起效果，有点难

**Comment by Zegapaiz** [comment]
环境变量有缓存啊，不是从命令上获取的最新的，配置文件有变动才会更新，有点难受

**Comment by grunmin** [comment]
在同个工程目录里面同时启动多个环境, 在构建的时候会互相影响, 请问是否有解决方案.
不是端口号冲突之类, 而是在代码里面根据UMI_ENV不同require不同的依赖, 在多个环境同时开启的时候共用一个编译缓存路径导致先启动的环境异常.

**Comment by lpy681** [comment]
package.json里面加上  UMI_ENV=xxx 这个xxx对应config.xxx.js
```
"start": "cross-env UMI_ENV=dev APP_TYPE=site umi dev",
"qa": "cross-env UMI_ENV=qa APP_TYPE=site umi dev",
```
如图
![image](https://user-images.githubusercontent.com/25508777/53692993-37339800-3dd4-11e9-8808-07bdeeaec31d.png)

然后config.xxx.js里面写↓
```
export default {
  define: {
    // 添加这个自定义的环境变量
    "process.env.UMI_ENV": process.env.UMI_ENV, // * 本地开发环境：dev，qa环境：qa，生产环境prod
 "process.env.name": '自定义name',
  },
}
```
页面中使用的时候
```
console.log(process.env.UMI_ENV) // run start的时候显示dev。run qa的时候显示qa
console.log(process.env.name) // 自定义name
```

**Comment by cfkxzsat** [comment]
define的变量在docker容器里，build并没有替换。有人遇到过这个问题吗

**Comment by EdifierCN** [comment]
> 在同个工程目录里面同时启动多个环境, 在构建的时候会互相影响, 请问是否有解决方案.
> 不是端口号冲突之类, 而是在代码里面根据UMI_ENV不同require不同的依赖, 在多个环境同时开启的时候共用一个编译缓存路径导致先启动的环境异常.

我也是一个项目通过命令打不同的包，有解决方式吗？

**Comment by wulinjie122** [comment]
我一个需求，我的静态文件都是放在阿里云OSS上的，我想把OSS的地址放在环境变量里，根据不同环境加载不同的OSS地址。
```jsx
<img id="site_logo" src={process.env.ossAddress + '/images/logo.jpg'} alt="Image" style={{ width: 180 }} />
```

**Comment by wulinjie122** [comment]
可以了，感谢各位，下面是我的配置，直接在.umirc.local.ts文件里，添加一段这样的配置：
```
// .umirc.local.ts
define: {
    OSS_END_POINT: 'https://www.xxx.oss-cn-shanghai.aliyuncs.com'
  }
```
需要注意的是，可能需要重启，`yarn start`，在typescript文件里直接使用变量即可生效：
```jsx
<img id="site_logo" src={OSS_END_POINT + '/images/logo01.png'} alt="Image" style={{ width: 180 }} />
```

**Comment by gbyuxia** [comment]
> 在同个工程目录里面同时启动多个环境, 在构建的时候会互相影响, 请问是否有解决方案. 不是端口号冲突之类, 而是在代码里面根据UMI_ENV不同require不同的依赖, 在多个环境同时开启的时候共用一个编译缓存路径导致先启动的环境异常.

我也碰到奇怪的地方，
"build-sit": "cross-env UMI_ENV=sit max build",
"build-uat": "cross-env UMI_ENV=uat max build",
"build-prod": "cross-env UMI_ENV=prod max build",
根目录下分别有.umirc.sit.ts、.umirc.uat.ts、.umirc.prod.ts，里面分别
define: {
'process.env.UMI_ENV': 'sit' //（ 'uat'/'prod'）
},
然后在src目录下的app.ts里
const env = process.env;
const UMI_ENV = env.UMI_ENV;
console.log('UMI_ENV',UMI_ENV);            //UMI_ENV sit //如果运行build-uat则是UMI_ENV uat
console.log('process.env.UMI_ENV',process.env.UMI_ENV);            //process.env.UMI_ENV prod——就是这个”prod“不符合预期

**Comment by AmberAAA** [comment]
> > 在同个工程目录里面同时启动多个环境, 在构建的时候会互相影响, 请问是否有解决方案. 不是端口号冲突之类, 而是在代码里面根据UMI_ENV不同require不同的依赖, 在多个环境同时开启的时候共用一个编译缓存路径导致先启动的环境异常.
> 
> 我也碰到奇怪的地方， "build-sit": "cross-env UMI_ENV=sit max build", "build-uat": "cross-env UMI_ENV=uat max build", "build-prod": "cross-env UMI_ENV=prod max build", 根目录下分别有.umirc.sit.ts、.umirc.uat.ts、.umirc.prod.ts，里面分别 define: { 'process.env.UMI_ENV': 'sit' //（ 'uat'/'prod'） }, 然后在src目录下的app.ts里 const env = process.env; const UMI_ENV = env.UMI_ENV; console.log('UMI_ENV',UMI_ENV); //UMI_ENV sit //如果运行build-uat则是UMI_ENV uat console.log('process.env.UMI_ENV',process.env.UMI_ENV); //process.env.UMI_ENV prod——就是这个”prod“不符合预期


# 环境变量

引用环境变量主要是为了解决，各个环境参数不一致的情况，比如测试环境与正式环境的API网关不一样，OSS地址不一样等。

更改环境变量之前，需要参考一下两篇文档：

1. [UMI环境变量](https://umijs.org/docs/guides/env-variables#%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)
2. [配置：define](https://umijs.org/docs/api/config#define)

**为兼容linux与window平台，建议采用cross-env在命令行中设置系统环境变量**

其原理时，通过指定[UMI_ENV](https://umijs.org/docs/guides/env-variables#umi_env)，让UMI加载不同的配置文件，在不同的配置文件中使用define定义各个环境的变量。


## 默认情况

在默认情况下，开发环境`npm run dev`会默认加载`.umirc.dev.ts`这个配置文件，打包`npm run build`时，会默认加载`.umirc.prod.ts`这个配置文件。因此：

**根据当前环境的不同，dev, prod, test 配置文件会自动加载，不能将 UMI_ENV 的值设定成他们。**

## 打包多个环境

如果打包时，需要多个环境，如`sit`，`uat`，`cn`时，则考虑使用`UMI_ENV`添加多个构建脚本。实施步骤：
1. 安装`cross-env`:
  ```bash
  yarn add cross-env -D
  ```

2. 扩充构建脚本`package.json`
  ```json
  {
    "script": {
      "build:sit": "cross-env UMI_ENV=sit npm run build",
      "build:uat": "cross-env UMI_ENV=uat npm run build"
    }
  }
  ```
3. 在根目录添加对应的配置文件`.umirc.prod.sit.ts`,`.umirc.prod.uat.ts`。

**Comment by saikete** [comment]
我想问一下，vite项目可以通过这样的配置在启动命令中加载不同的环境变量，umi最新版本我看了几遍文档，是只能通过UMI_ENV去走环境变量吗，没办法通过设置启动命令配置文件读.env.serve.test文件配置里面的变量吗？
<img width="603" alt="image" src="https://github.com/umijs/umi/assets/45237450/5514e627-07f3-439c-bef8-d194ab9edf34">
