### ISSUE TITLE
umi3.5  defineConfig 配置路由 之后   react页面的警告如何消除

### ISSUE THREAD

**Issue by liu136149** [umijs/umi#11424]
## What happens?

使用defineConfig 配置路由页面发出警告
devScripts.js:6523 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
注销路由或者 设置hideInMenu: true警告消失

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/liu136149/umi-seed

## How To Reproduce
启动项目就会出现警告
**Steps to reproduce the behavior:** 1. 2.
把config/config.ts内的routes注销 警告就消失
**Expected behavior** 1. 2.

## Context

- **Umi Version**:  3.5.41
- **Node Version**: 14.13.1
- **Platform**: win10

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4
