### ISSUE TITLE
[Bug] umi 添加插件报错

### ISSUE THREAD

**Issue by yijinc** [umijs/umi#11420]
## What happens?

umi 添加手动 添加 plugin 报错：

```bash
dev
> umi dev

fatal - Error: Register plugin /Users/xxx/project/node_modules/@umijs/plugin-model/lib/index.js failed, since Cannot read properties of undefined (reading 'winPath')

```

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: latest
- **Node Version**: 16
- **Platform**:

**Comment by fz6m** [comment]
在 umi 4 中，所有的插件不再是 `@umijs/plugin-xxx` 了，都放到 `@umijs/plugins` 了，通过如下方式使用：

```bash
  pnpm i -D @umijs/plugins
```

```ts
// .umirc.ts

export default {
  plugins: ['@umijs/plugins/dist/model'],
  model: {}
}
```

所有可用的插件可以在 [packages/plugins](https://github.com/umijs/umi/tree/master/packages/plugins/src) 找到。

同时以前的 `@umijs/plugin-xxx` 依赖都可以卸载了。
