### ISSUE TITLE
[Bug] umi3 + qiankun 使用 webpack5 的 模块联邦报错

### ISSUE THREAD

**Issue by xiaoxiong77** [umijs/umi#11429]
## What happens?

umi3.5.41 + qiankun 中开启 webpack5 的模块联邦功能

## Mini Showcase Repository(REQUIRED)

https://github.com/xiaoxiong77/umi3Test
https://github.com/xiaoxiong77/umi3Test1

## How To Reproduce

1、依次在两个项目执行，yarn 以及 yarn start；
2、访问 http://localhost:8000/
3、页面出现如下报错
![20230718-154624](https://github.com/umijs/umi/assets/35364483/6df8b03a-51d7-4f63-b450-99fe6d2fd8a9)

## Context

- **Umi Version**: 3.5.41
-  **@umijs/plugin-qiankun**: 2.43.3

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4
