### ISSUE TITLE
Umi3.x默认的html模版,有做异步加载吗？具体代码那里体现？

### ISSUE THREAD

**Issue by cddChang** [umijs/umi#11425]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4

**Comment by cddChang** [comment]
那么升级后的 umi4.0 的默认html模版有做异步加载吗？ 具体代码体现在哪儿 ？
