### ISSUE TITLE
[Bug] 开启local配置，使用chrome浏览器无痕模式报错

### ISSUE THREAD

**Issue by WangHuagang** [umijs/umi#11421]
## 问题描述

在`.umirc.ts`中配置了`  locale: {
    antd: true,
  },`，将项目编译部署到第三方服务器上，以iframe的方式嵌入进一个网页，使用chrome浏览器的无痕模式打开嵌入该iframe的网页时，控制台报错，导致项目白屏；（非无痕模式是正常的）
![image](https://github.com/umijs/umi/assets/23147530/8c819516-e618-4f62-979b-b626b3246add)

初步判断是在判断能否使用localStorage时判断条件不够，导致报错：
![image](https://github.com/umijs/umi/assets/23147530/0bfc076e-1552-451d-b549-fbd56d625276)

### 临时解决方案
chrome中设置【允许所有cookie】
![image](https://github.com/umijs/umi/assets/23147530/69ebd389-7ef4-4c2e-a101-260f72b7a4d8)

## How To Reproduce

见上述描述

## Context

- **Umi Version**: 3.5.36
- **Node Version**: 14.18.0
- **Platform**:

**Comment by fz6m** [comment]
umi 3 不再维护了，建议升级到 umi 4

**Comment by kGe-z** [comment]
@fz6m 在关闭第三方cookie的情况下，升级umi4，存在无法设置当前locale的问题

**Comment by kGe-z** [comment]
umi4 的 locale 看起来并不是在 .umirc.ts 设置默认语言，而是根据浏览器语言进行设置
