### ISSUE TITLE
umi4使用antd运行时配置修改了但是页面没有任何变化

### ISSUE THREAD

**Issue by Heyunzhen** [umijs/umi#11422]
## What happens?

        使用umi4 antd运行时配置修改了黑色主题以及国际化，全部未生效
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

import {RuntimeAntdConfig} from "umi"
import zhCN from 'antd/locale/zh_CN';
import { theme } from 'antd';
  export async function getInitialState(): Promise<{ name: string }> {
    return { name: '@umijs/max'};
  }
 
export const antd:RuntimeAntdConfig = (memo) => {
  memo.theme ??= {};
  memo.theme.algorithm = theme.darkAlgorithm ; // 配置 antd5 的预设 dark 算法
  memo.locale = zhCN 
  memo.appConfig = {
    message: {
      // 配置 message 最大显示数，超过限制时，最早的消息会被自动关闭
      maxCount: 3,
    }
  }
  console.log(memo)
  return memo;
};
## Context

- **Umi Version**:4.0.72
- **Node Version**:18.16.0
- **Platform**:PC 谷歌浏览器

**Comment by fz6m** [comment]
给一个最小复现吧，如果使用了 max 的 layout ，他本身是 [pro component](https://procomponents.ant.design/components/layout) ，所以需要用到 pro component 的 Settings 等方式来修改 layout 的样式和 token 、算法等。
