### ISSUE TITLE
[Feature Request] prettier-plugin-organize-imports 改为 peerDependencies

### ISSUE THREAD

**Issue by onlyling** [umijs/umi#11427]
## Background

在 `prettier@2.x` 的开发环境下使用 `dumi@2.x`，`prettier-plugin-organize-imports` 会自动添加上去（The plugin will be loaded by Prettier automatically. No configuration needed.） ，导致与自身项目一些 eslint 规则冲突，被迫把 `prettier` 升级到 `3`，同时把 `eslint-plugin-prettier` 升级到 `5`。

## Proposal

把 prettier-plugin-organize-imports 改为 peerDependencies，或者还有其他兼容方案？

**Comment by fz6m** [comment]
配置 `pluginSearchDirs: false` 看看，prettier 旧文档都下线了，如果可以的话，尽量用新版本吧，没差多少。
