### ISSUE TITLE
[Bug] umi4 使用@umijs/preset-vue 时，支持mpa模式吗？

### ISSUE THREAD

**Issue by wuhaoxiangfau** [umijs/umi#11438]
在使用@umijs/preset-vue，同时开启mpa，dev阶段就报错。

`export default defineConfig({
  npmClient: 'pnpm',
  presets: [require.resolve('@umijs/preset-vue')],
  mpa: {
    entry: {
      index: 'src/pages/index/index.vue'
    }
  }
});`

`fatal - AssertionError [ERR_ASSERTION]: webpack config 'entry' value must be a string or an object.`

- **Umi Version**:4.0.72
- **Node Version**:16.15.0
- **Platform**: mac

**Comment by xierenyuan** [comment]
不支持 可以根据  modifyEntry 扩展下 具体可参考 packages/preset-umi/src/features/mpa/mpa.ts 实现一个 vue mpa 即可
