### ISSUE TITLE
[Bug] routes配置重定向问题

### ISSUE THREAD

**Issue by Heyunzhen** [umijs/umi#11434]
## What happens?

配置routes
  routes: [
    { path: "/", component: "index",name:'首页',hideInMenu:true },
    { 
      path: "/docs",
      name:'文档',
      redirect:'/docs/list',
      routes:[
        {
          path: "/docs/list",
          name:'文档列表',
          component:'docs'
        },
        {
          path: "/docs/docschildren",
           component: "@/pages/docschilden",
           name:'文档详情',
           hideInMenu:true,
           parentKeys: ['/docs/list']
      },
      ]
    },
    { path: "/doc111s", component: "docs",name:'还有一级' },
  ],
  由于配置了layout会展示面包屑，所有点击进入文档列表后，面包屑展示为文档/文档列表
  面包屑点击文档，我希望重定向至文档列表,为什么配置了redirect到文档列表，但是报错为栈溢出
  
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
  ## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
  缺陷重现github仓库地址： https://github.com/Heyunzhen/Umi4-

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

    yarn  安装依赖
    
    选择 yarn dev:test启动不要选择yarn dev
    
    点击文档列表则会复现

## Context

- **Umi Version**: "@umijs/max": "^4.0.72",
- **Node Version**:18.16.0
- **Platform*谷歌浏览器*:

**Comment by fz6m** [comment]
在嵌套路由的时候，父路由不能配置 `redirect` ，这会导致进入任何一个嵌套子路由都经过父路由走重定向。

需要把路由拆开写，具体可以参考 antd-pro 的[路由表](https://github.com/ant-design/ant-design-pro/blob/753945ec3d561a81851c3d6861b365f0a837c711/config/routes.ts#L39)。

**Comment by Heyunzhen** [comment]
如果路由表是在后端返回，那么在后台创建的时候就要这么创建？

**Comment by wangsanshao** [comment]
嵌套很多的时候，需要最上面的父路由直接redirect到最里面的第一个子路由，还是会出现上面的问题，这个怎么解决

**Comment by wangsanshao** [comment]
export default [
  {
    path: '/',
    component: '@/layouts/BaseLayout',
    routes: [
      {
        path: '/',
        redirect: '/welcome',
      },
      {
        path: '/welcome',
        name: '欢迎',
        icon: 'HomeOutlined',
        routes: [
          {
            path: '/welcome',
            name: '欢迎',
            icon: 'HomeOutlined',
            component: '@/pages/Welcome',
          },
          {
            path: '/test',
            name: '欢迎',
            icon: 'HomeOutlined',
            component: '@/pages/',
          },
        ],
      }
     ]
  }
]这种也是不行的，只要访问了 "/" 根路径，就会一直报这个错
index.js:1 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.

**Comment by fz6m** [comment]
我用如下的配置是没问题的，访问 `/` 就跳转到 `/demo` 了：

```ts
  routes: [
    {
      path: '/',
      routes: [
        {
          path: '/',
          redirect: '/demo'
        },
        {
          path: '/demo',
          component: './Home'
        }
      ]
    }
  ],
```

如有问题，需要给一个有问题的最小复现。

**Comment by wangsanshao** [comment]
```javascript
export default [
  {
    path: '/',
    component: '@/layouts/BaseLayout',
    routes: [
      {
        path: '/',
        redirect: '/welcome',
      },
      {
        path: '/welcome',
        name: '欢迎',
        icon: 'HomeOutlined',
        routes: [
          {
            path: '/welcome',
            name: '欢迎',
            icon: 'HomeOutlined',
            component: '@/pages/Welcome',
          },
          {
            path: '/test',
            name: '欢迎',
            icon: 'HomeOutlined',
            component: '@/pages/',
          },
        ],
      }
     ]
  }
]
``` 

可以正常跳转，只是控制台会有
![image](https://github.com/umijs/umi/assets/14011258/c6f66d9a-660e-4700-b0e9-b2aa50dc9b0e)
