### ISSUE TITLE
请求添加配置实现 create-react-app 形式的 css-module

### ISSUE THREAD

**Issue by xiaoxiangmoe** [umijs/umi#1143]
请求添加配置实现 create-react-app 形式的 css-module。即：

`[name].module.(css|less|scss)` 生成的 classname 为 `[filename]_[classname]__[hash]`;
`[name].(css|less|scss)`生成的 classname 为 `[classname]`。

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-modules-stylesheet

**Comment by lcexc** [comment]
正好也有这个需求。顺便问下,可不可以让开发者添加自定义的webpack配置?

**Comment by xiaohuoni** [comment]
@lcexc https://umijs.org/zh/config/#chainwebpack 你要找的是这个吗？

**Comment by sorrycc** [comment]
可以这样配：

```js
export default {
  disableCSSModules: true,
  cssModulesWithAffix: true,
}
```
