### ISSUE TITLE
使用mf 子模块使用 @umijs/max 里面的方法无效

### ISSUE THREAD

**Issue by 18613109040** [umijs/umi#11440]
在umijs 官方demo  /examples/mf-remote/exposes/Counter 
![image](https://github.com/umijs/umi/assets/18108674/40f6ac56-4236-4293-82b3-3fa40675f75f)

单独运行可以输出 history

在 /examples/mf-host/src/pages/raw-mf-component.tsx 
下 history 为 undefined

**Comment by fz6m** [comment]
在 umi 中，umi 本身的方法是不可以在依赖包、mf 这些第三方的组件中使用的，仅限于在项目内的代码使用，所以你的组件应该是纯净解耦的，如果必须要依赖，可以通过 props 传递。
