### ISSUE TITLE
4.0.72 版本依然存在"启动后，Ctrl-C 关闭进程时报错"问题

### ISSUE THREAD

**Issue by Vision010** [umijs/umi#11445]
机器环境：Window WSL Ubuntu 20

4.0.72 版本依然存在这个问题

_Originally posted by @Vision010 in https://github.com/umijs/umi/issues/6009#issuecomment-1645454849_

在 monorepo 下会影响 c-c 后的命令输入，需要再次进行 c-c 后恢复正常

终端当前行进入 sh 模式，再次 c-c 或者回车后的下一行恢复正常，延迟退出 sh 了？

**Comment by fz6m** [comment]
1. 需要提供下更详细的上下文信息，如 node 、npm / yarn 版本号等。

2. umi 4 更推荐使用 pnpm 。

3. umi 4 里的逻辑和 umi 3 里是一样的，如果 3 中没有问题，需要给一个能稳定的最小复现看看。
