### ISSUE TITLE
[Bug] umi4+qiankun 主应用设置publicPath和base以后，子应用无法显示

### ISSUE THREAD

**Issue by daisybaicai** [umijs/umi#11447]
## What happens?
1. 主应用为master，在config.js里面设置了publicPath和base为/admin/,
2. 然后在主应用的config.js里面写入配置qiankun: {master: {}},子应用也是umi4的，设置了qiankun的子应用相关配置
3. app.js里面配置了子应用的地址
```
// src/app.ts
export const qiankun = {
  apps: [
    {
      name: 'slave',
      entry: '//localhost:5555',
    },
  ],
};
```
4. 在路由部分，分别用了三种方法，就是官网里面的示例，
- 路由绑定引入子应用
- <MicroApp /> 组件引入子应用
- <MicroAppWithMemoHistory /> 组件引入子应用

均无法显示子应用

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/daisybaicai/qiankun-demo-test

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

1. 安装master和slave两个仓库，然后npm install npm run start
2. 然后主应用是5000端口，登录账号密码 admin 123456,然后进入平台页面，里面的三个tab分别是官网里面的三种实现，点击都无法显示，右侧都是空白，没有显示子应用的页面
![image](https://github.com/umijs/umi/assets/25605435/12beefc8-fcac-437a-9b70-1180bcc41183)

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by daisybaicai** [comment]
@fz6m 感谢，问题已经都解决，就是想问一下，改完以后，控制台在点击第一和第二个菜单的情况下，都会出现warning，这块是需要修改吗？
![image](https://github.com/umijs/umi/assets/25605435/3accd630-9ef1-49a9-81cb-0acf8ffc70f1)

**Comment by fz6m** [comment]
这个不用管他，在切换重新挂载子应用的一瞬间会有路由匹配不上的时刻，主应用会发出警告。
