### ISSUE TITLE
umi 4.0.72 mpa模式，代码有wasm文件，build后预览路径出错

### ISSUE THREAD

**Issue by pxim** [umijs/umi#11454]
## Background

umi 4.0.72 mpa模式，代码有wasm文件，build后出错
dev 模式正常
![image](https://github.com/umijs/umi/assets/5111701/6de2b500-9fbd-4240-9366-2649de05271b)

prod 报错截图

![image](https://github.com/umijs/umi/assets/5111701/9a1446a2-f4e7-481a-be04-a3ff10eefad1)
![image](https://github.com/umijs/umi/assets/5111701/97b8f14d-3936-4660-89c2-ba16785449c8)

该如何操作，才能打包后，wasm也是正确的相对路径

#

**Comment by fz6m** [comment]
需要给一个最小复现看看你是怎么加载失败的。
