### ISSUE TITLE
umi4.0.72  base: './'  页面一片空白

### ISSUE THREAD

**Issue by pxim** [umijs/umi#11451]
## Background
umi3 配置  base: './', 一切OK。

umi4 4.0.72 配置  base: './',
会报错：mf-dep____vendor.3f85375c.js:421742 <Router basename="/."> is not able to match the URL "/" because it does not start with the basename, so the <Router> won't render anything.
页面一片空白

如果不配置base，build的页面，如下图方式预览时，也是一片空白（umi3这种预览方式配置base后是ok的）
![image](https://github.com/umijs/umi/assets/5111701/c133fa80-758d-4938-a92c-f64e3ada9008)

**Comment by xiaohuoni** [comment]
可以用环境变量配置开发的时候不配置，publicPath 也是一样的

**Comment by fz6m** [comment]
`base` 是路由前缀，url 上没有 `./` 这种，你指的是加载 相对的资源 ，需要配置 `publicPath` ，没必要配置 `base` ，除非你部署在子路径上才需要配置 `base` ：

```ts
  publicPath: process.env.NODE_ENV === 'development' ? '/' : './'
```

**Comment by pxim** [comment]
> 可以用环境变量配置开发的时候不配置，publicPath 也是一样的

> 可以用环境变量配置开发的时候不配置，publicPath 也是一样的

这样配置了，dev正常了，build后页面一片空白，也没报错，搞不懂

**Comment by pxim** [comment]
import { defineConfig } from "umi";
import path from 'path';
import moment from 'moment';

export default defineConfig({
  routes: [
    { path: "/", component: "index" },
  ],
  npmClient: 'yarn',
  alias: {
    '@packages': path.resolve(__dirname, 'src/packages'), //@components
    // '@': path.resolve(__dirname, 'src'),
  },
  //设置代码中的可用变量。属性值会经过一次 JSON.stringify 转换。
  define: {
    Version: moment().format('YYYYMMDDHHmmss'),
    resPath: '.',
  },

  proxy: {
    '/api': {
      'target': 'https://127.0.0.1:50501',
      'changeOrigin': true,
      'pathRewrite': { '^/api': '' },
    }
  },

  outputPath: 'build',
  hash: true,
  base: process.env.NODE_ENV === 'development' ? '/' : './',
  publicPath: process.env.NODE_ENV === 'development' ? '/' : './',
  manifest: {
    basePath: process.env.NODE_ENV === 'development' ? '/' : './',
  },

  deadCode: {}, 
  https: {
    "key": path.join(__dirname, 'cert.key'),
    "cert": path.join(__dirname, 'cert.crt'),

    http2: false,
  },

});

**Comment by pxim** [comment]
> `base` 是路由前缀，url 上没有 `./` 这种，你指的是加载 相对的资源 ，需要配置 `publicPath` ，没必要配置 `base` ，除非你部署在子路径上才需要配置 `base` ：
> 
> ```ts
>   publicPath: process.env.NODE_ENV === 'development' ? '/' : './'
> ```

你搞错了，publicPath我配置了，就是base的问题

**Comment by xiaohuoni** [comment]
非根目录部署，要配置对应的目录，不是配 `./` 吧？
`./` 配置一般用在那些静态资源容器

**Comment by pxim** [comment]
> 非根目录部署，要配置对应的目录，不是配 `./` 吧？ `./` 配置一般用在那些静态资源容器

是的，静态资源服务器，相对路径
![image](https://github.com/umijs/umi/assets/5111701/274d217b-e512-4a36-a044-7e6666f96634)
在这种服务器下，都能启动观看的

**Comment by xiaohuoni** [comment]
所以你在非根目录部署，要跟着改配置。

**Comment by maoxiao0627** [comment]
最后怎么解决的呀

**Comment by xiaohuoni** [comment]
配置 https://umijs.org/docs/api/config#base
搜索关键字，非根目录部署
