### ISSUE TITLE
umi 4.0.72 build后，非根目录启动 页面空白 publicPath已设置 ./

### ISSUE THREAD

**Issue by pxim** [umijs/umi#11452]
## Background

umi 4.0.72 build后，非根目录启动 页面空白
publicPath已设置 process.env.NODE_ENV === 'development' ? '/' : './'
![image](https://github.com/umijs/umi/assets/5111701/6a6e1aa4-ee60-4584-b853-a68fbff417be)

Demo：[web5.zip](https://github.com/umijs/umi/files/12167592/web5.zip)

.umirc.ts
```
import { defineConfig } from "umi";
import path from 'path';

export default defineConfig({
  routes: [
    { path: "/", component: "index" },
    { path: "/docs", component: "docs" },
  ],
  npmClient: 'yarn',

  outputPath: 'build',
  hash: true,

  publicPath: process.env.NODE_ENV === 'development' ? '/' : './',
  manifest: {
    basePath: process.env.NODE_ENV === 'development' ? '/' : './',
  },

  runtimePublicPath: {},

  https: {
    "key": path.join(__dirname, 'cert.key'),
    "cert": path.join(__dirname, 'cert.crt'),

    http2: false,
  },
});

```

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/11451#issuecomment-1651045750

**Comment by fz6m** [comment]
当你设定 `publicPath` 为 `./` 时，只是决定了资源从相对路径进行加载，并不能决定路由匹配。

假定你通过一个工具提供了服务，在 `http://domain.com/prefix/a/b` 上，资源加载是没问题的，但是路由匹配不上，如同 https://github.com/umijs/umi/issues/11451#issuecomment-1650870552 中所说的，你还需要配置 `base` 为实际 url 的前缀才能让应用的路由匹配命中，这里 `base` 是 `/prefix/a/b` 。

对于大部分的子路径部署场景，我们往往将 `base` 和 `publicPath` 配置成一样的值：

```ts
  publicPath: '/prefix/a/b',
  base: '/prefix/a/b',
```

从而确保资源和路由都是正确的。

当你真的不确定路由前缀时，你可以使用 [`hash`](https://umijs.org/docs/api/config#history) 路由：

```ts
  history: { type: 'hash' }
```

这样路由匹配就和 `/prefix/a/b` 无关了，而是取决于 `hash` ，比如 `/prefix/a/b#some-path` 。

注：你可以通过 `pnpm umi preview` 来启动验证产物，使用其他的工具在本地启动服务时，不确保他们都是正确的，一切以真正部署到线上域名后能否运行为准（一般是 nginx ）。
