### ISSUE TITLE
antd插件配置问题修改theme.token,

### ISSUE THREAD

**Issue by ksh033** [umijs/umi#11464]
## What happens?

配置样式token，webapck编译出错
## Mini Showcase Repository(REQUIRED)
> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
import { defineConfig } from '@umijs/max';
export default defineConfig({
  antd: {
    theme:{
      token:{}
    
    }
  },
  targets: {
    ie: 11,
  }})

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- 4.0.7
- **Node Version**:
- 16
- **Platform**:
- windows

**Comment by fz6m** [comment]
配置里的选项只能配静态值，动态值和函数要在运行时配，参考 [`export const antd`](https://umijs.org/docs/max/antd#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE) 。
