### ISSUE TITLE
[Bug] models文件夹下使用useParams始终是空值

### ISSUE THREAD

**Issue by vkboo** [umijs/umi#11462]
<img width="585" alt="image" src="https://github.com/umijs/umi/assets/17156560/45123118-f85e-465c-8bf6-2c7cc5af03e2">
如图，在页面有params的情况下，在models下的文件使用useParams获取的params始终是`{}`.这是bug还是feature？有解决的打算吗？谢谢

**Comment by fz6m** [comment]
`useModel` 这个方案是持久化的 fiber 在全局之外，没在应用的 context 之下，所以没法取路由的东西，因为不管你有没有运行 `useModel` ，他都会一直存在。

所以这种局部化的数据应该在局部 hooks 或局部 react context 里解决。

或者你可以尝试使用局部化的 model 方案 [hox](https://github.com/umijs/hox) 。

**Comment by vkboo** [comment]
了解，谢谢推荐。

**Comment by vkboo** [comment]
@fz6m  你推荐的Hox很好用！但是还有与Umi结合使用还有一个疑问：我应该把`HoxProvider`放在哪里？
1. 放在 layout.tsx 中，这样的话，如果某一个页面路由配置了`layout: false`，那这个页面就没法访问HoxProvider内的数据了；
2. 放在 app.tsx 中的 `export const rootContainer = () => <HoxProvider />` 这里，可以解决上面第1条的问题，新的问题是，这时候 HoxProver对应的store文件没法访问umi中的`useParams`等路由相关信息了。

望解答，谢谢🙏

**Comment by fz6m** [comment]
放到 [`wrappers`](https://umijs.org/docs/guides/routes#wrappers) 里吧，他和 layout 一样都是包了一层在路由外面。

hox 他是一个局部性的数据管理方案，所以不应该全局就放一个 hox provider ，否则他就变成全局数据流方案了（全局共享数据建议使用 [jotai](https://github.com/pmndrs/jotai) 、[valtio](https://umijs.org/docs/max/valtio) 等。

对于局部来说，就是在某个局部领域包一个 hox 来提供这个区域的数据和行为，所以他应该有很多个。
