### ISSUE TITLE
umi 的history.push相关问题

### ISSUE THREAD

**Issue by chenJJ-88** [umijs/umi#11460]
umi 4 是已经将    history.push({
      pathname: 'xxxxxx',
      query: {
        pageType: 'add',

      },
    })
这种query跳转传参废弃了吗？以前都可以用，现在没法使用，有什么可替代的方案嘛，state传参没有持久性，一刷新就没了

**Comment by fz6m** [comment]
手动拼一下到 url query 上带着走吧，可以用 qs 库序列化。

**Comment by xiaohuoni** [comment]
或者开兼容配置 historyWithQuery:{}
