### ISSUE TITLE
[Bug] umi 4.0.73配置proxy无效

### ISSUE THREAD

**Issue by pxim** [umijs/umi#11467]
## What happens?

umi 4.0.73配置proxy无效
看了 https://umijs.org/docs/introduce/faq#devserver-%E9%80%89%E9%A1%B9%E6%80%8E%E4%B9%88%E9%85%8D%E7%BD%AE 这个文章，
已经配置
![image](https://github.com/umijs/umi/assets/5111701/a4dc34a6-bca0-48f4-9efd-ab9a3d57f15e)
和 添加了plugin.ts
![image](https://github.com/umijs/umi/assets/5111701/53137660-d8dd-47d6-bee4-73c57a631579)
都无效，报错
![image](https://github.com/umijs/umi/assets/5111701/bab5b6ee-4d9d-4a62-b27d-0e66b14213b1)
![image](https://github.com/umijs/umi/assets/5111701/004d80a1-aed4-422b-b901-e5728ef7ae55)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

demo：https://gitee.com/pxi/umi4.0.73-proxy-invalid2.git

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

umi dev

## Context

- **Umi Version**: 4.0.73
- **Node Version**: v16.20.1
- **Platform**: win10

**Comment by pxim** [comment]
测试的服务端接口，是对的，
![image](https://github.com/umijs/umi/assets/5111701/9c4e0462-1016-41c9-8c09-7e08fe7d9f45)

**Comment by fz6m** [comment]
你把 `/api` 这个前缀干掉了，所以请求的是 `/login/test` ，写成 `/api/api/login/test` 吧。

**Comment by pxim** [comment]
确实是这个原因😓，谢谢了
