### ISSUE TITLE
[Bug] vscode 类型提示好慢，别的ts项目没有问题，一点即出

### ISSUE THREAD

**Issue by doom-9** [umijs/umi#11473]
用create-umi@latest 创建的项目，vscode 类型提示好慢，别的ts项目没有问题，一点即出

https://github.com/umijs/umi/assets/110001160/5714cf17-fb14-4a94-becd-f8c32f32a4e9

**Comment by fz6m** [comment]
在项目根目录打开 Vscode ，让这个 Vscode 窗口只有你这一个项目，减少需要索引的文件加快速度。

如果感觉很卡或者提示不出来，就 cmd + shift + p 输入 restart typescript server ，这个经常需要用。

另外确认下你右下角 IDE 使用的 TS 引擎版本，预期是项目内的 ts 版本而不是 IDE 本身的版本，或者用 TS nightly 插件用日更版也可以。

如果实在不行，就 cmd + shift + p 输入 reload 窗口。

**Comment by doom-9** [comment]
我试一下，谢谢

**Comment by doom-9** [comment]
用yarn装依赖类型提示很慢，换成pnpm后就正常了 @fz6m

**Comment by Mrcxt** [comment]
umi很垃圾的，换vite吧

**Comment by hhfu001** [comment]
> 用yarn装依赖类型提示很慢，换成pnpm后就正常了 @fz6m

确实，我从npm切换到pnpm就正常了。

**Comment by ZhangJiaWeiready** [comment]
我这边用的pnpm安装依赖，vscode那些代码提示也是很慢，然后稍微改一行代码vscode得编译几十s，然后时间长了电脑还崩溃，
