### ISSUE TITLE
[Bug] config下的icon不显示

### ISSUE THREAD

**Issue by samous0726** [umijs/umi#11476]
![image](https://github.com/umijs/umi/assets/25798093/497fce3a-b40c-4547-b6b0-29a54351389b)

<img width="305" alt="image" src="https://github.com/umijs/umi/assets/25798093/618f2a73-cbf4-41d1-9902-0126f850c4b8">

菜单的路由配置在umirc里 页面展示用的umi max的layout

**Comment by fz6m** [comment]
现在的 layout 不支持二级包括以上深度级别的菜单带 icon 。
