### ISSUE TITLE
[Bug] 希望umi4多页签条宽度能自适应

### ISSUE THREAD

**Issue by ghuan** [umijs/umi#11470]
## What happens?
我在ant design pro 项目中启用umi4的多页签功能，发现页签过多时，右侧多个页签将无法显示，虽然有鼠标滚动，但是貌似页签条宽度还是过长，建议宽度能自适应，并且能有一个关闭当前页签的功能，
另外，ant design pro 提供了黑色主题功能，切换黑色主题后，页签条bar背景颜色没有动态修改为黑色。
也许这两个问题都是pro切换设置，未动态渲染多页签的原因

## How To Reproduce

1. 创建pro项目：pro create myapp
2. 配置启用多页签：
```
//开启多页签
  keepalive: [/./],
  tabsLayout: {
  hasDropdown: true,
  hasFixedHeader: true,
  },
```
3. npm install,npm start 启动
4. 多开几个菜单，切换黑色主题

## Context

- **Umi Version**: 4.0.73
- **Node Version**: 18.0
- **Platform**: windows10
![image](https://github.com/umijs/umi/assets/15809971/f4237069-8392-43e2-b67b-0a203a857e43)

**Comment by fz6m** [comment]
你用的是 alita 的 keepalive 吗，到 [这里](https://github.com/alitajs/alita) 来反馈吧。
