### ISSUE TITLE
无法重新执行umi dev命令的问题

### ISSUE THREAD

**Issue by free-pan** [umijs/umi#1147]
系统环境: mac osx 10.13.6
磁盘已格式化为: APSF(加密)

之前未升级系统未将磁盘格式化为APSF格式时，是没问题。

现在的情况是, 第一次执行`umi dev`时可以正常启动(有观察到:`node_modules`目录会生成`.cache`的隐藏文件夹)，然后关闭,再次执行`umi dev`命令，web console会提示:`Uncaught SyntaxError: Unexpected token {            umi.js:48413 `错误

实际的错误指向的是这行代码:

```
/* harmony default export */ __webpack_exports__["default"] = (undefinedfunction (valid, message) {
```
最后那个大括号打了个X

现在的解决办法是，每次执行`umi dev`命令之前，手动删除`node_modules/.cache`文件夹

**Comment by free-pan** [comment]
![image](https://user-images.githubusercontent.com/37232676/46140569-0d55d280-c284-11e8-92ef-736a754e721d.png)

**Comment by xiaohuoni** [comment]
感觉和你格式化没多大关系，你可以搜索一下，好像有看到别的iss，我手机页面查看，没有搜索

**Comment by xiaohuoni** [comment]
可以试试关闭hardSource

**Comment by Renderz** [comment]
相同问题, 关闭hardSourceOK. 升级到umi2.1似乎也OK了.

**Comment by xiaohuoni** [comment]
以下三个方案，任选其一
1.手动删除node_modules/.cache文件夹，可以处理这个问题
2.设置hardSource: false
3.升级umi到2.1
