### ISSUE TITLE
有钩子函数 让我在Route.Provider下面 layout的上面添加自定义的Provider嘛

### ISSUE THREAD

**Issue by ErnestWangZuNian** [umijs/umi#11486]
如下图所示  我想在中间区域加一个自定义的Provider
![image](https://github.com/umijs/umi/assets/11648360/d58f4502-24d5-4a80-97e6-49e477a46498)

**Comment by fz6m** [comment]
在运行时用 [`patchRoutes`](https://umijs.org/docs/api/runtime-config#patchroutes-routes-) patch 下 layout 的路由吧，可以用 id 判断，给 pro layout 包一层。

或者指定成 `layout: false` ，手动套一下 `@@/plugin-layout/Layout.tsx` 和你自己的 provider ，可以用 [`wrappers`](https://umijs.org/docs/guides/routes#wrappers) 。

**Comment by ErnestWangZuNian** [comment]
您好，我已收到邮件，我会尽快处理的。。。
