### ISSUE TITLE
[Feature Request] 如何在umi4 中配置wepack的showEslintErrorsInOverlay属性

### ISSUE THREAD

**Issue by daisybaicai** [umijs/umi#11488]
## Background

在umi4中开启这个属性，然后在eslint设置了一些规则，比如eslint unused 变量的时候，页面会报错，提示这个eslint 规则，然后达到类似页面上出现这样的效果
![image](https://github.com/umijs/umi/assets/25605435/268c7186-c0c2-4488-9e44-7511819c9ee0)

## Proposal

当前我是在修改这个chainWebpack，然后这样设置不对，请求解答应该如何设置

```javascript
  chainWebpack(memo, { env, webpack }) {
    memo.showEslintErrorsInOverlay.set(true);
  },
```
<img width="606" alt="image" src="https://github.com/umijs/umi/assets/25605435/d21473f0-1636-4277-a443-162cee32b71b">

**Comment by sorrycc** [comment]
你好，umi 不支持这个功能。
