### ISSUE TITLE
umi build报错core-js dependencies were not found

### ISSUE THREAD

**Issue by ljj0915** [umijs/umi#11494]
"umi": "2.13.13",
"umi-plugin-ga": "^1.1.3",
"umi-plugin-react": "^1.4.2"
"core-js": "^3.1.4",

chainWebpack: (config) => {
    config.module.rule('compile').test(/\.m?jsx?$/).use('babel')
      .loader('babel-loader')
      .options({
        presets: [
          ['@babel/preset-env', { modules: false, "corejs": "3", "useBuiltIns": "entry", "loose": true  }],
          '@babel/preset-react' 
        ],
        plugins: [
          ['@babel/plugin-proposal-decorators', { legacy: true }] // 添加这行
        ]
      });

}
![image](https://github.com/umijs/umi/assets/62496386/d8659f23-a6df-4c95-98f2-9e81f6340e28)

参考了：https://github.com/umijs/umi/issues/2657
但是我umi版本应该已经修复了这个问题，为什么还会有这个现象？
umi版本对应的umi-build-dev版本是1.18.5，里面的core-js是2.6.9

**Comment by fz6m** [comment]
umi 2 不维护了，建议升级到 umi 4
