### ISSUE TITLE
在没有了index.html后如何引用Iconfont?

### ISSUE THREAD

**Issue by xjl271314** [umijs/umi#115]
如何加载类似阿里巴巴图标库的css iconfont

**Comment by sorrycc** [comment]
可以定制 html 模板，然后在模板里引入。

## 修改默认模板

新建 `pages/document.ejs`，umi 约定如果这个文件存在，会作为默认模板，内容上需要保证出现 `<div id="root"></div>`。

## 针对特定页面指定模板

配置 `.umirc.js`

```js
{
  "pages": {
    "/": { document: "./a.ejs" },
    "/list": { document: "./b.ejs" }
  }
}
```

优先级是：pages 里指定 > pages/document.ejs > umi 内置模板。

**Comment by xjl271314** [comment]
thanks,it is settled.
