### ISSUE TITLE
SSR是否可在生产环境使用？

### ISSUE THREAD

**Issue by witcsmartian** [umijs/umi#11503]
## Background

umi4自2022年6月发布以来，官方文档上说：[SSR 目前还处于实验性特性，不建议在生产环境使用，若发现问题可即时在 [issue](https://github.com/umijs/umi/issues) 反馈]。

## Proposal

1、ssr生产环境是否可用？
2、若目前生产环境不可用，是否有支持的计划？若可以使用，请补充下umi文档

**Comment by fz6m** [comment]
不建议使用，当需要 SSR 时应该使用 Nextjs

**Comment by ShinChven** [comment]
next.js 简直一tuo

我还在用umijs3.5做 SSR，求4.0完善一下！

**Comment by wonghan** [comment]
> 不建议使用，当需要 SSR 时应该使用 Nextjs

请问现在的 umi@4.6.0 版本可以使用SSR吗？
还是推荐使用 umi v3版本 或者 nextjs？
