### ISSUE TITLE
[Feature Request] umi4.0支持监听文件变化实时构建吗

### ISSUE THREAD

**Issue by GuanErShuiShou** [umijs/umi#11504]
umi4.0支持监听文件变化实时构建吗?umi3.0我记得是支持的

**Comment by fz6m** [comment]
umi 是构建业务应用项目的，如果要构建包相关，使用 [father](https://github.com/umijs/father) 吧。

**Comment by GuanErShuiShou** [comment]
> umi 是构建业务应用项目的，如果要构建包相关，使用 [father](https://github.com/umijs/father) 吧。

业务应用也有这个要求，我司是涉及到千牛业务的需要将html放入里面才能使用千牛的api

**Comment by fz6m** [comment]
不支持。
