### ISSUE TITLE
[Bug] 使用 @emotion/babel-preset-css-prop 插件报错

### ISSUE THREAD

**Issue by Enivia** [umijs/umi#11501]
## How To Reproduce

- config
```
extraBabelPresets: ['@emotion/babel-preset-css-prop']
```
- 启动项目
- 报错
Cannot find module 'file:///.../node_modules/@emotion/babel-preset-css-prop/dist/emotion-babel-preset-css-prop.cjs.mjs' (While processing: D:\Work\data-lineage-html\node_
modules\@emotion\babel-preset-css-prop\dist\emotion-babel-preset-css-prop.cjs.mjs)

## Context

- **Umi Version**: 4.0.27
- **Node Version**: 18.16.0
- **Platform**: Windows

**Comment by fz6m** [comment]
先这么用吧：

```ts
  extraBabelPresets: [
    path.join(
      path.dirname(require.resolve('@emotion/babel-preset-css-prop/package.json')),
      'dist/emotion-babel-preset-css-prop.cjs.js'
    )
  ],
```
