### ISSUE TITLE
[Bug] umi4下载@umijs/plugin-antd-mobile插件后在.umirc中配置antdMobile: {     hd: true,   },报错fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: antdMobile

### ISSUE THREAD

**Issue by againF** [umijs/umi#11505]
## What happens?

umi4下载@umijs/plugin-antd-mobile插件后在.umirc中配置antdMobile: {     hd: true,   },报错fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: antdMobile

**Comment by fz6m** [comment]
[umijs/plugins](https://github.com/umijs/plugins) 这个仓库里的插件都是仅能在 umi 3 使用的，不能在 umi 4 使用。

大部分原来的插件在 `@umijs/plugins/dist/*` 内置了，比如 `@umijs/plugins/dist/locale`（ i18n ） ，但这个插件没有内置，如果你要用这个插件，自己看下源码改一下支持 umi 4 吧。
