### ISSUE TITLE
umi-plugin-local 为 <= ie9 自动处理 Intl 补丁

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#1151]
# 重现步骤
umi配置
```js

export default {
  plugins: [
    ['umi-plugin-react', {
      routes: {
        exclude: [
          /exclude/,
        ],
      },
      dva:true,
      antd: true,
      polyfills: ["ie9"],
      locale: {
          enable: true, // default false
          default: 'zh-CN', // default zh-CN
          baseNavigator: true, // default true, when it is true, will use `navigator.language` overwrite default
      },
    }],
  ],
}
```
约定目录
```bash
├── /locales/   
│ ├── zh-CN.js   
│ └── en-US.js    
```
如果在ie9-10上出现
```js
[React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.
```
最新的兼容方案是放到了target 里面了，考虑到umi的版本更新时间和线上项目暂时稳定为主，不适合跟进升级测试版本，所以可以简单的使用一下的方法处理一下。
# 临时解决方案
```bash
yarn add intl
```
src/global.js
```js
import 'intl'
```
另外使用antd-pro的朋友，如果出现find方法错误的，
可以在``src/global.js``增加
```js
import 'core-js/es6/array';
```

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/1146
https://github.com/umijs/umi/issues/993
https://github.com/ant-design/ant-design-pro/issues/2422
https://github.com/ant-design/ant-design-pro/issues/2297
https://github.com/ant-design/ant-design-pro/issues/2149

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/issues/2431

**Comment by sorrycc** [comment]
我觉得应该在 umi-plugin-local 里检测 targets 配置，如果 targets.ie <= 10，则自动加上补丁。 @yutingzhao1991

**Comment by xiaohuoni** [comment]
intl不在babel里面

**Comment by sorrycc** [comment]
1. intl 不在 ecma 标准里, babel 不包含
2. 用户没有用 umi-plugin-locale，通常是不需要 intl 的补丁的，不应该加上
