### ISSUE TITLE
[Bug] doc-调试文档

### ISSUE THREAD

**Issue by peterlxb** [umijs/umi#11522]
## What happens?

按照官方文档提供的调试插件进行调试，里面的配置直接复制进去，正则匹配会报错，

`
{
  "proxy": [
    // 数组的第 0 项的资源会被第 1 项目替换
    [
      "https://www.myproject.com/umi.2c8a01df.js",
      "http://127.0.0.1:8000/umi.js"
    ],
    // 使用正则可以方便处理分包情况下 js 资源的加载
    [
      "https://www.myproject.com/(.*\.js)",
      "http://127.0.0.1:8000/$1",
    ],
    // 如果需要验证视觉表现，不要忘记替换 css 资源
    [
      "https://www.myproject.com/umi.ae8b10e0.css",
      "http://127.0.0.1:8000/umi.css"
    ]
  ]
}
`
然后按照文档的信息进行调试，完全没法用，即没有报错，也没有提示，作为这么多人用的产品，文档能不能及时更新？

**Comment by fz6m** [comment]
proxy 配置项的用法详见 [文档说明](https://umijs.org/docs/api/config#proxy) 。
