### ISSUE TITLE
[Bug] logout 默认退出登录按钮的文案无法修改，无法进行本地化适配

### ISSUE THREAD

**Issue by Wei0809** [umijs/umi#11524]
## What happens?
现在的按钮文案是写死的，没有跟随antd配置语言，也不能进行本地化适配，而rightRender貌似又不能只修改logout部分的内容
![image](https://github.com/umijs/umi/assets/43309547/048d23df-3ca1-42b5-bd52-c45e984ef0d0)

**Comment by fz6m** [comment]
如果目前需要国际化 layout 里面的，参考 https://github.com/umijs/umi/issues/9767#issuecomment-1313351148 手动 copy 一份来实现吧。

这个问题在 #9767 跟进。
