### ISSUE TITLE
[Bug] .umirc.ts 配置  qiankun 的 master 后，开发热更新失效

### ISSUE THREAD

**Issue by guokegit** [umijs/umi#11531]
# 在umi3应用中，加载另一个umi3应用，功能实现正常，但是热更新失效。
定位发现 在 .umirc.ts 配置  qiankun 的 master 后，开发热更新就失效，浏览器报错 “typeerror: cannot read properties of undefined (reading 'foreach')     at startworkonpendinginteractions”，将master 值配置为 undefined，就可正常热更新

### .umirc.ts

```
qiankun: {
    slave: {
      shouldNotAddLibraryChunkName: true,
    },
    master:  {
      apps: [{
        name: 'app1',
        entry: 'https://xxx/xxx'
      }]
    }
  },
```

### 热更新编译完成后，浏览器不刷新，报错如下
<img width="572" alt="image" src="https://github.com/umijs/umi/assets/26155396/5d7bae7a-fc46-4620-9087-9e93a26069a8">

### umi版本
`"umi": "^3.5.19"`

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4
