### ISSUE TITLE
React constructor  this.props    undefined

### ISSUE THREAD

**Issue by yuandapeng** [umijs/umi#1153]
**umi 配置：**
umi-plugin-polyfill  ->  ie9
经过测试：
**IE9、IE10**
React constructor  this.props    undefined

**Comment by sorrycc** [comment]
用 umi@2.1 的 targets 配置吧。

**Comment by yuandapeng** [comment]
ok

**Comment by yuandapeng** [comment]
@sorrycc  我用了最新版本的还是不可以！

**Comment by Evin-An** [comment]
我的也不行   : 无法获取未定义或 null 引用的属性“route”，props为undefined
![image](https://user-images.githubusercontent.com/29926597/62918387-08cdd600-bdd2-11e9-857a-d57700fb03b8.png)
![image](https://user-images.githubusercontent.com/29926597/62918441-2f8c0c80-bdd2-11e9-87a3-ba7fdd250806.png)
