### ISSUE TITLE
[Bug] umi v3版本，使用pnpm install， pnpm 执行 umi dev, 提示This dependency was not found

### ISSUE THREAD

**Issue by ClintLee1101** [umijs/umi#11535]
## umi v3版本，使用pnpm install， pnpm 执行 umi dev, 提示This dependency was not found

报错提示如下：This dependency was not found:

 /Users/用户名/umi-ts-app-master/src/.umi/plugin-initial-state/models/initialState in ./src/.umi/plugin-model/Provider.tsx
 生成的.src目录下并没有该文件

git仓库地址：https://github.com/hanyueqiang/umi-ts-app 可使用这个仓库地址进行复现
重现步骤：
pnpm install
pnpm start

-**umi**: "^3.1.3",
-**node**: v16.20.0,
-**Platform**: macOS

**Comment by ClintLee1101** [comment]
![image](https://github.com/umijs/umi/assets/21055736/5a5e8c8d-fa82-4c4f-a936-d1bab273d93d)


npm安装依赖 ，npm start 不会有该问题

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4
