### ISSUE TITLE
[Bug] 设置了request 的 timeout，请求无法超时cancel

### ISSUE THREAD

**Issue by KeyToLove** [umijs/umi#11546]
## What happens?
```js
import { request } from 'umi';

export async function someRequest(data) {
  return request(`xxx`, {
    method: 'POST',
    data,
    timeout: 2000 //  <-   这里设置超时时间
  });
}

客户端浏览器无法在在指定的timeout时cancel请求，请求会已经走完知道服务端响应

umi版本  "umi": "^3.5.0"

```

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4
