### ISSUE TITLE
[Bug] An error occurs when using @@/plugin-request in getInitialState.

### ISSUE THREAD

**Issue by 662** [umijs/umi#11544]
## What happens?

An error occurs when using @@/plugin-request in getInitialState.

> Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'UseRequestProvider')

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/see/next/line
https://codesandbox.io/p/sandbox/silent-fire-wd6kxm

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

```shell
npx create-umi@latest demo
# Ant Design Pro
# npm
# taobao

cd demo

echo 'import { request } from '@@/plugin-request'
export async function getInitialState() {
  const data = await request('https://api.github.com')
  return { data }
}
' > ./src/app.ts

npm run dev
```

## Context

- **Umi Version**: 4.x
- **Node Version**: 18.x
- **Platform**: Macos 13.x

**Comment by fz6m** [comment]
所有的方法需要从 `@umijs/max` 里导入：

```ts
import { request } from '@umijs/max'
```

上面给的 github repo url 404 找不到，如还有问题，给一个能打开的 repo 链接。

**Comment by 662** [comment]
> 所有的方法需要从 `@umijs/max` 里导入：
> 
> ```ts
> import { request } from '@umijs/max'
> ```
> 
> 上面给的 github repo url 404 找不到，如还有问题，给一个能打开的 repo 链接。

Github 的链接是用来骗 bot 的。
下一行的 codesandbox 可以直接看到结果

![image](https://github.com/umijs/umi/assets/13599186/820ad39d-94aa-4651-8736-14d5ab8676d4)

**Comment by 662** [comment]
@umijs/max 中的 request 确实可用

仅插件二次封装之后的会出问题

**Comment by 662** [comment]
没注意 @umijs/max 中的 request 就是来自 .umi 目录

关了。
