### ISSUE TITLE
['[contenthash:8]' is hard code] can you let customers to choose what they want?

### ISSUE THREAD

**Issue by bernie-shi** [umijs/umi#11543]
## Background

there is a website that needs to be embedded in the main subject(Micro front end), the website need to set the CORS response header.  browsers caches the files and these files have no expired date or If-no-modified, no-cache, response header related config, so these no changed file still have no latest response header, especially the CORS header, that cause page blank problem, I try to use 'config.output' , it did work, but I need to change CSS also, and 'mini-css-extract-plugin' is worked but these cause two same files, and CSS files which chunkfileName was set to new is not linked with the HTML(entry), so it failed, and not elegant

## Proposal

I hope you can give a way let me to custom my content hash

## Additional context

<img width="596" alt="image" src="https://github.com/umijs/umi/assets/130951707/e71e452c-b7d3-472a-9e3c-d040339faa0e">
<img width="619" alt="image" src="https://github.com/umijs/umi/assets/130951707/49166a3b-f7b5-4110-8926-266ce3f4a704">

**Comment by bernie-shi** [comment]
> 目前不支持自定义 hash ，如果 hash 有影响，就不要开 hash ，转为使用 `publicPath` 等方法区分，比如 `/v${pkg.version}/` 作为 `publicPath` 路径，这样就会从 `/v1.0.0/umi.js` 或 `/v1.1.1/umi.js` 加载了，如果要自定义响应头，根据 location 正则匹配在 nginx set 下 header 吧；或者固定一个匹配符 `/cors-assets/` 作为 `publicPath` （ `/cors-assets/umi.hash.js` ） ，然后正则匹配给含有这个路径的 `.js` 和 `.css` 资源都加上 header 。

但是publicPath会影响我项目的发布流程，而且还要配置nginx，挺麻烦吧，而且如果加这个也不算是一件难事吧？

**Comment by bernie-shi** [comment]
尤其是多项目引入的，还有固定的链接地址（对外的），总不能通知所有人都要改吧

**Comment by bernie-shi** [comment]
@fz6m 麻烦帮忙提供个优化的小版本可以吗？

**Comment by innocces** [comment]
you can use a random string for hashSalt to update hash info.
