### ISSUE TITLE
项目创建报错

### ISSUE THREAD

**Issue by hyl1374961656** [umijs/umi#11547]
npm和yarn的方式都是同样的错
![image](https://github.com/umijs/umi/assets/56420042/157eacb7-38aa-4f5b-822c-a9aebeb18653)
![image](https://github.com/umijs/umi/assets/56420042/720b8c0c-3f67-41f6-85e1-5fe186d2aacd)

**Comment by fz6m** [comment]
目前只支持在 TTY 能交互的终端里创建项目，因为有选项你需要自己选，尝试以下命令创建项目或者换一个终端：

```bash
  pnpm create umi my-app --default
```
