### ISSUE TITLE
umi^4.0.53中theme 引入ts文件对象无法热更新

### ISSUE THREAD

**Issue by lixiaoshun** [umijs/umi#11545]
## What happens?
直接在config文件更新 theme，可以热更新，但是引入变量后，在变量里面修改，无法热更新，
设置mfsu:false，也无效
![image](https://github.com/umijs/umi/assets/42568595/338bdef5-48d4-45dc-8def-be242499fc48)

## How To Reproduce
1.在theme.ts文件内修改主题色，后
npm run start 无效果
![image](https://github.com/umijs/umi/assets/42568595/9086abbb-59dc-46ef-b56c-0b55d7583ae2)

2、在config中直接修改，主题色改变（只要config中有更改，就能触发热更新）

## Context

- **Umi Version**:4.0.53
- **Node Version**:16.0.0
- **Platform**:macOS

**Comment by fz6m** [comment]
仅 `config.ts` 的更改会被自动检测重启 umi 进程，其他导入的文件不支持。

**Comment by lixiaoshun** [comment]
重新run start还会保留上次的编译结果，即使删除.umi文件夹

**Comment by fz6m** [comment]
如有问题，需要给一个最小复现。

**Comment by lixiaoshun** [comment]
git地址:  https://github.com/lixiaoshun/num-test.git 

theme.ts中修改主题色后，从新npm run start无效

![image](https://github.com/umijs/umi/assets/42568595/04261873-ef97-4606-a3c6-23ecca92ba4d)

**Comment by fz6m** [comment]
是 `@primary-color` ，可 [参考文档](https://umijs.org/docs/api/config#theme) 。

**Comment by lixiaoshun** [comment]
使用@primary-color还是不可以，在theme.ts文件中，修改主题色，npm run start不会更新，但是build又没有问题

**Comment by BingruLin** [comment]
删node_modules/.cache最稳；mpa工程里手动保存global.less也没法更新
