### ISSUE TITLE
子应用打包后部分文件路径访问没有拼接publicPath

### ISSUE THREAD

**Issue by chen-jieyi** [umijs/umi#11542]
## What happens?
![image](https://github.com/umijs/umi/assets/35585258/b3dac40e-8a85-452b-baa7-1576704e3bec)
![image](https://github.com/umijs/umi/assets/35585258/fb6c54ca-bfe4-4236-9621-ea681bb16afc)

.umirc.ts 配置
{
  mfsu: false,
  antd: {},
  access: {},
  model: {},
  initialState: {},
  request: {},
  layout: false,
  npmClient: 'yarn',
  hash: true,
  history: {
    type: 'hash',
  },
  publicPath: process.env.NODE_ENV === 'production' ? '/system/' : '/',
  base: '/system',
  qiankun: {
    slave: {},
  },
  inlineLimit: 2000,
}
配置了public path 部署时大部分页面都有拼接 就两个文件没拼接到这个 导致访问不到报404 
（手动在浏览器加上/system是能访问到的）

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: @umi/max 4.0.75
- **Node Version**: 18.17.1
- **Platform**:

**Comment by fz6m** [comment]
根据 qiankun 的 [描述](https://qiankun.umijs.org/zh/faq#b-%E4%BD%BF%E7%94%A8-webpack-%E9%9D%99%E6%80%81-publicpath-%E9%85%8D%E7%BD%AE) ，尝试把 `publicPath` 配置成绝对 url 路径 `//domain.com/system/` 看下。

如还有问题，需要给一个最小复现。
