### ISSUE TITLE
typescript跑测试的时候报错，Cannot read property 'createTransformer' of undefined

### ISSUE THREAD

**Issue by lulusir** [umijs/umi#1154]
版本2.1

测试代码如下
```
it('test', () => {
  expect(1).toBe(1)
})
```
下面是报错信息
```
Test suite failed to run

    TypeError: Cannot read property 'createTransformer' of undefined

      at ScriptTransformer._getTransformer (node_modules/jest-runtime/build/script_transformer.js:232:28)
```

**Comment by xiaohuoni** [comment]
<img width="337" alt="wx20180928-143820 2x" src="https://user-images.githubusercontent.com/11746742/46191996-2b770d80-c32c-11e8-999b-ea47da5f51b4.png">
删除重装试试，或者给个重现demo？

**Comment by xiaohuoni** [comment]
@sorrycc 
https://github.com/umijs/umi/blob/72ebdbd7ab2a3e7121e2d676785ce53e9b41a5cc/packages/umi-test/src/index.js#L26
这里同样使用``'\\.tsx?$': require.resolve('./transformers/jsTransformer'),``不会报错，且可以测试通过。

**Comment by xiaohuoni** [comment]
感觉都使用jstransformer能跑通，估计是用例太简单了

**Comment by sandwich99** [comment]
@alipay/bigfish ^2.0.0-beta.22 是兼容 ts 测试的

umi 最新版挂了
