### ISSUE TITLE
[Bug] 按照官方文档从Electron模板创建项目失败

### ISSUE THREAD

**Issue by yangliuyu** [umijs/umi#11548]
按照文档 https://umijs.org/docs/guides/getting-started#%E4%BB%8E%E6%A8%A1%E6%9D%BF%E5%88%9B%E5%BB%BA%E9%A1%B9%E7%9B%AE
创建electron项目失败

<img width="1196" alt="image" src="https://github.com/umijs/umi/assets/1361821/77138cc6-f36c-46d6-a36f-c88d75d9108f">

Umi version: latest 4.0.76?
Node version: v18.17.0
Platform: MacOS 12.6

如果选择pnpm+taobao源也报错
<img width="902" alt="image" src="https://github.com/umijs/umi/assets/1361821/ddf6e90b-885a-4b7f-b94f-88c57147848b">

创建electron项目还有别的推荐方式吗？

**Comment by fz6m** [comment]
看一下这个 [仓库](https://github.com/xiefengnian/umijs-electron-plugin) ，如有问题，可以向对应仓库 owner 资讯。
