### ISSUE TITLE
[Bug] 关闭第三方Cookie后，无法设置当前locale

### ISSUE THREAD

**Issue by kGe-z** [umijs/umi#11555]
## What happens?
浏览器关闭第三方Cookie后，无法通过 setLocale 设置当前locale，或者说需要通过其他方式来设置默认的语言，比如 URL

通过 setLocale 设置再进行refresh后，react-intl 的 locale 和 message 还是没有更改

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

1. 浏览器关闭第三方Cookie
2. 通过setlocale设置其他语言
3. 刷新页面

## Context

- **Umi Version**: 4 
- **Node Version**: 16.14.0
- **Platform**: windows/macos

**Comment by fz6m** [comment]
语言标识存在 local storage 里，如果用户不允许 cookie 则不能存储用户信息，一是 local storage 可能不可用，二是无痕浏览器下次 local storage 也会丢失，无法持久保存。

如有特殊需求，可以自己 copy 一份 `./src/.umi/plugin-locale/localeExports.ts` 中的 `getLocale` 代码去掉 `cookieEnabled` 判断，然后在 `app.ts` 里 `render` 前获取到当前的 locale 然后 `setLocale` 进去：

```ts
// src/app.ts
import { setLocale } from '@umijs/max'

export const render = (oldRender: any) => {
  // e.g. 
  setLocale('en-US')
  oldRender()
}
```

这种方法不能避免 local storage 不可用或者无痕浏览器不保存 local storage 的情况，可以尝试自己根据浏览器语言偏好获取或者根据用户登录选择从服务端获取。
