### ISSUE TITLE
[Bug] 最新版 4.0.77 发布的 @umijs/bundler-webpack 有问题

### ISSUE THREAD

**Issue by cklwblove** [umijs/umi#11563]
## What happens?

最新发布的 @umijs/bundler-webpack 包，版本 4.0.77 有问题。package.json 文件里依赖出现了 `workspace:*`，导致安装失败

![image](https://github.com/umijs/umi/assets/5652022/bc1d0d3f-e59a-4c23-9910-1620d380e803)
 

@umijs/

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by Chrisyjs** [comment]
+1 !!!

**Comment by PeachScript** [comment]
抱歉发包出现了异常，v4.0.78 已修复
