### ISSUE TITLE
[Bug] 必然会引入的 antd/reset.css 文件, 在micro项目下, 会覆盖 cssInJs的样式

### ISSUE THREAD

**Issue by vocing** [umijs/umi#11565]
micro 会给css、less文件加前缀，但是 cssInJs 不会，这样cssInJs的权重就被覆盖了，导致样式问题，如果可以把该reset文件做成cssInJs挂载就更好了
![image](https://github.com/umijs/umi/assets/33081977/c0b7b291-16e8-447f-9b53-35bee94b6163)

**Comment by fz6m** [comment]
如果使用自动给子应用样式表添加前缀的方式，不可避免的会存在问题，在你的应用体系中，应该通过 class prefix 、css in js 、css modules 等方式做好样式隔离，避免采用自动处理样式表的方案。
