### ISSUE TITLE
[Bug] patchClientRoutes in android alipay can not render child route

### ISSUE THREAD

**Issue by Fog3211** [umijs/umi#11566]
## What happens?

1、在安卓支付宝内，使用`patchClientRoutes`来动态修改路由的时候，无法匹配到子路由，只能展示出根目录的layout
2、我在 `patchClientRoutes` 把unshift方法换成了直接对数组第一项进行替换，就可以匹配到路由了（但是最玄学的是，如果pages下面的目录超过了10个【比如新增一个 `/pages/z/index.tsx` 文件 】，就又匹配不到了）

<img width="468" alt="image" src="https://github.com/umijs/umi/assets/23151576/b1bb695c-64f5-41cc-aa26-d05cb676d7d8">
<img width="461" alt="image" src="https://github.com/umijs/umi/assets/23151576/6fc88c9c-d317-4f41-b2fb-89545a37ebd9">

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

[复现仓库地址](https://github.com/Fog3211/android-alipay-umi-routes-reproduction)

## How To Reproduce

[测试页面在线地址](https://android-alipay-umi-routes-reproduction.vercel.app/)

使用安卓支付宝扫码进入页面，发现子路由部分没有被渲染，其他平台的PC浏览器和ios上面表现都是正常的。

## Context

- **Umi Version**: 4.0.74
- **Node Version**:   16.16.0
- **Platform**: macos + android 12

支付宝版本10.5.16，安卓12版本的iQOO neo3，应该是对所有安卓都是一样的，拿公司的安卓测试机看也是有问题的

**Comment by fz6m** [comment]
1. 目前国内安卓应用内浏览器内核都是厂商自行定制的，无法表现一致。

2. umi 是一个面向中后台的 SPA 应用框架，不适用于构建手机端页面。

3. 尝试使用 [hash](https://umijs.org/docs/api/config#history) 路由，[mpa](https://umijs.org/docs/guides/mpa) 多页应用来在手机端展示页面。

4. 尝试参考 [`非现代浏览器兼容`](https://umijs.org/blog/legacy-browser) 提升应用对低版本浏览器的兼容性。
