### ISSUE TITLE
[Bug] outlet 导不进来，版本3.5.41

### ISSUE THREAD

**Issue by TomLilione** [umijs/umi#11569]
## What happens?

<img width="314" alt="截屏2023-08-26 12 33 49" src="https://github.com/umijs/umi/assets/47802577/402efac1-dc1b-4d7e-9355-58b557be3efd">
如图所示，倒入失败，运行时报undifined
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
umi 3 没有 `Outlet` ，这个是 umi 4 的。

umi 3 已经不维护了，建议升级到 umi 4
