### ISSUE TITLE
[Bug] @umijs/bundler-webpack@ 4.0.77 npm install 安装失败

### ISSUE THREAD

**Issue by j3r0lin** [umijs/umi#11562]
## What happens?

最新版本 @umijs/bundler-webpack@ 4.0.77  package.json 中包含了错误的 dependency `"@umijs/babel-preset-umi": "workspace:*",`

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
`4.0.77` 是一个错误的版本，目前已经发布正常的 `4.0.78` 版本，可以使用最新的版本。

cc @PeachScript 老师可以给 `4.0.77` unpublish 一下或者打一下 deprecated 标识 🌹
