### ISSUE TITLE
[Bug] chain-webpack  config.output.assetModuleFilename ts支持出错

### ISSUE THREAD

**Issue by day-xue** [umijs/umi#11574]
## What happens?

自定义打包静态目录文件夹名字修改时发现问题

![image](https://github.com/umijs/umi/assets/95938844/2d7b7476-aee9-44c4-918f-063b24b5352d)

类型定义出错 应为assetModuleFilename

**Comment by fz6m** [comment]
umi 4 不支持自定义产物目录结构，你可以根据版本号分文件夹在 cdn / oss 上托管。
