### ISSUE TITLE
[Feature Request] 在运行时能够获取 base

### ISSUE THREAD

**Issue by maquannene** [umijs/umi#11588]
## Background

运行时获取 base；

集成微前端插件时，会有这样的代码注入，能够获取到 base
![image](https://github.com/umijs/umi/assets/8757564/6d037c57-48d3-4eb3-8725-bb140304bc63)

但是不开启微前端插件，就没有 api 能够获取 base 了。

## Proposal

某些场景下需要 base 进行一些逻辑判断；

**Comment by maquannene** [comment]
另外，不是很希望通过 define 的方式，多一个变量来获取 base，因为 base 很有可能是运行时的 html 去动态设置修改 routeBase 的，用法不是很固定。

**Comment by fz6m** [comment]
在项目根目录创建一个项目级插件 `plugin.ts` ：

```ts
import type { IApi } from '@umijs/max'; // or import from 'umi'

export default (api: IApi) => {
  api.onGenerateFiles(() => {
    api.writeTmpFile({
      path: 'core/basenameRuntime.ts',
      noPluginDir: true,
      content: `
export const modifyClientRenderOpts = (ctx) => {
    window.__basename = ctx.basename;
    return ctx;
}
            `,
    });
  });

  api.addRuntimePlugin(() => ['@@/core/basenameRuntime.ts']);
};
```

`modifyClientRenderOpts` 是 render 前最后一次修改和查看配置的时机。
