### ISSUE TITLE
[Bug] 构建后页面报错，偶发性

### ISSUE THREAD

**Issue by DroganC** [umijs/umi#11587]
### wath happend 

页面报错
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'call')

启动后页面会报如上错误，把src/loading删了又好了

```js
// src/loading.tsx
import Loading from '@/components/Loading'
export default Loading;
```

**Comment by fz6m** [comment]
看下你的 `@/components/Loading` 这个组件的导入链路是不是有循环依赖了，一般 `undefined` 就是循环依赖。

可以尝试使用 [umi-plugin-circular-check](https://github.com/umijs/umi-plugin-circular-check) 插件自动扫描一下。

如有问题，可以给一个最小复现。

**Comment by xiaoxuehai** [comment]
这个问题好几个issue了，有解决吗

**Comment by omnifj** [comment]
也遇到了，本地构建调试没问题，部署到线上也是这个错误
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'call')
排查，最后什么也没做就又好了
玄学
