### ISSUE TITLE
升级到4.0.78后，每次开机前几次tailwindcss都报错

### ISSUE THREAD

**Issue by xiaoliu1990** [umijs/umi#11591]
每次电脑关机后开机前几次启动较慢的时候都会出现：tailwindcss generate failed after 5 seconds，please check your tailwind.css and  tailwind.config.js，然后start几次以后，只要启动了一次，今天之内不关电脑的话，就不会在出现了。
目前我这边用的架子必现。

![Snipaste_2023-09-01_09-30-00](https://github.com/umijs/umi/assets/17424034/4ffce2cb-86f0-4fb9-9481-af9e49b33465)

## Context

- **Umi Version**:4.0.78
- **Node Version**:v16.18.0
- **Platform**:

**Comment by fz6m** [comment]
umi 4 已经快 2 年了，内置的 tailwind 和 unocss 的插件已经是很老的功能了，一直没有维护，现在相关生态和功能已经发生了较大变化，目前建议把内置的 tailwind 插件关了，然后自己参考 tailwind 官网 [postcss](https://tailwindcss.com/docs/installation/using-postcss) 的使用方式配置一下来用。

**Comment by axinya001** [comment]
> tailwind

那为什么不考虑升级呢？
