### ISSUE TITLE
[Bug] 4.x request工具获取不到自定义响应头

### ISSUE THREAD

**Issue by LuckLin520** [umijs/umi#11605]
## What happens?

4.x request工具获取不到自定义响应头

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

版本：
"@umijs/max": "^4.0.78"
代码：
  // 响应拦截器
  responseInterceptors: [
    (response) => {
      // 拦截响应数据，进行个性化处理
      console.log(response);
      debugger
      return response;
    },
  ],
 结果：
![image](https://github.com/umijs/umi/assets/33896086/532d25d0-2d38-4377-b634-84212ea71753)
![image](https://github.com/umijs/umi/assets/33896086/d2b43464-03f2-4af0-969f-a8e9aa4b7e7a)

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
要获取自定义响应头需要接口响应头中添加 [Access-Control-Expose-Headers](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) 。
