### ISSUE TITLE
[Bug] ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with ENOENT: umi g

### ISSUE THREAD

**Issue by yudar1024** [umijs/umi#11607]
# error 
<img width="608" alt="image" src="https://github.com/umijs/umi/assets/1061851/ef7dda46-aca1-4203-9ee1-fb7fa5cbfddf">

## How To Reproduce
1 pnpm dlx create-umi@latest, in the process choose use ant design pro
2 pnpm umi g

```shell
❯ pnpm umi g
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command failed with ENOENT: umi g
spawn umi ENOENT
```
## Context

- **Umi Version**:
```json
dependencies": {
    "@ant-design/icons": "^5.2.6",
    "@ant-design/pro-components": "^2.6.16",
    "@umijs/max": "^4.0.79",
    "antd": "^5.8.6"
  },
  "devDependencies": {
    "@types/react": "^18.2.21",
    "@types/react-dom": "^18.2.7",
    "husky": "^8.0.3",
    "lint-staged": "^14.0.1",
    "prettier": "^3.0.3",
    "prettier-plugin-organize-imports": "^3.2.3",
    "prettier-plugin-packagejson": "^2.4.5",
    "typescript": "^5.2.2"
  }
```
- **Node Version**: v18.16.0
- **Platform**: mac m2

**Comment by fz6m** [comment]
看一下你的 pnpm 版本是多少，max 的话应该用 `pnpm max g` 。

**Comment by yudar1024** [comment]
> 看一下你的 pnpm 版本是多少，max 的话应该用 `pnpm max g` 。

pnpm 8.3.1 

应该改一下文档（文档里是pnpm umi g)，pnpm max g 正常。
