### ISSUE TITLE
[Bug] 约定式路由，部署到静态服务器以后怎么以html的形式访问

### ISSUE THREAD

**Issue by qyjandroid** [umijs/umi#11617]
## What happens?

约定式路由，部署到静态服务器以后。
不能以***/index.html访问，必须使用 http://192.168.11.111/apage/ 这样访问，怎么配置一下可以使用 http://192.168.11.111/apage/index.html 这样的形式去访问？

## Mini Showcase Repository(REQUIRED)

配置如下：
![image](https://github.com/umijs/umi/assets/6645414/500516c1-fdbe-4abc-af3a-db95d50aea6e)

## Context

- **Umi Version**: 4.0.79
- **Node Version**: 18.15.0
- **Platform**: linux

**Comment by fz6m** [comment]
See #11616

**Comment by qyjandroid** [comment]
![image](https://github.com/umijs/umi/assets/6645414/39cc1985-34a8-4896-9dc1-9725dd5a1c12)
![image](https://github.com/umijs/umi/assets/6645414/50f0a159-3c29-4185-b513-e6bb54d174a9)

我看了一眼，直接不以html访问，也会自动找html文件，但是root节点为空

**Comment by fz6m** [comment]
SPA 要求将所有请求都重写到 `index.html` ，如果你需要以 `index.html` 附加在路径上访问，除了需要修改 nginx 配置，还需要确保你的路由匹配才能渲染内容，`/` 和 `/index.html` 是不同的路由，如果路由不匹配则无法渲染内容，或者考虑采用 hash 路由。
