### ISSUE TITLE
umi test seems to kill development server halfway through

### ISSUE THREAD

**Issue by ja573** [umijs/umi#1161]
I am running tests using the script provided by ant-design-pro https://github.com/ant-design/ant-design-pro/blob/master/tests/run-tests.js, which starts a development server and then executes the tests.

At runtime, the server starts properly, and can be accessed on localhost:8000 - but at some point during the process the server exists, making all e2e tests result in a `net::ERR_CONNECTION_REFUSED at http://localhost:8000`.

The problem seems to be related to today's release: umi@2.1.0

**Comment by ja573** [comment]
Running `npm start` and then `npm test` works fine

**Comment by ja573** [comment]
I guess that running `npm test` returns a signal at some point, making the process watching exit

**Comment by ja573** [comment]
This hack https://github.com/ant-design/ant-design-pro/commit/1dd86e7 seems to fix the issue. The problem seems to be that tests are triggered multiple times, running simultaneously. This script watches for tests to finish in order to kill the development server - so when multiple tests are trigger, as soon as one exits, the development server stops, leaving the other test processes without a development server.

Have there been any changes recently that could mistakenly run umi test multiple times?

**Comment by chenshuai2144** [comment]
In China, fix_puppeteer runs very slowly and maybe should make a new image

**Comment by ja573** [comment]
> In China, fix_puppeteer runs very slowly and maybe should make a new image

I'm note quite sure what you mean by this - I don't see how fix_puppeteer could affect umi test
