### ISSUE TITLE
约定式路由部署静态服务器，怎么以html的形式访问

### ISSUE THREAD

**Issue by qyjandroid** [umijs/umi#11616]
## What happens?

约定式路由，部署到静态服务器以后。
不能以***/index.html访问，必须使用 http://192.168.11.111/apage/ 这样访问，怎么配置一下可以使用 http://192.168.11.111/apage/index.html访问呢？
在不改动nginx的情况下。

## Context

- **Umi Version**: 4.0.79
- **Node Version**: 18.15.0
- **Platform**:

**Comment by fz6m** [comment]
这是你的 nginx 把所有请求都转发到了 `index.html` ，需要先判断有没有这个文件，没有的话 404 再转发到这个文件，自己调整下 nginx 吧。

**Comment by qyjandroid** [comment]
> 这是你的 nginx 把所有请求都转发到了 `index.html` ，需要先判断有没有这个文件，没有的话 404 再转发到这个文件，自己调整下 nginx 吧。

![image](https://github.com/umijs/umi/assets/6645414/5461e99d-8481-4970-ba6e-5d6739ff00f6)

访问到html文件了，但是root节点为空，也没有报错信息
![image](https://github.com/umijs/umi/assets/6645414/18d52b88-8078-483d-8dbf-d55490cca365)
