### ISSUE TITLE
[Bug] RequestConfig 配置了 baseURL 不生效

### ISSUE THREAD

**Issue by baiwumm** [umijs/umi#11610]
## What happens?

![image](https://github.com/umijs/umi/assets/40554571/f779af70-4c49-47cd-b7af-f74e6650af88)
![image](https://github.com/umijs/umi/assets/40554571/0a543c0b-3f5c-4901-a6b6-a532136d5db2)
![image](https://github.com/umijs/umi/assets/40554571/96cef47d-5b2b-477a-a4c7-2bc63f253902)
请求接口没有添加上前缀，但在 request 添加就可以，请问是我配置不对吗，我看 umi 文档说这些配置会透传给 Axios，
![image](https://github.com/umijs/umi/assets/40554571/f14f43a3-826d-4be4-8d15-c7ef275da21e)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by liuhao-hrbust** [comment]
要http开头吧

**Comment by fz6m** [comment]
是 `export const request = { baseURL: '/api1' }` ，我试了可以的，如有问题，需要给一个最小复现。
