### ISSUE TITLE
[Bug] 产线发现root节点没有内容

### ISSUE THREAD

**Issue by qyjandroid** [umijs/umi#11618]
## What happens?

本地运行正常，build以后，访问出现空白页面，发现root节点为空。

我配置了publicPath

## Mini Showcase Repository(REQUIRED)

![image](https://github.com/umijs/umi/assets/6645414/6b76e0b1-98cf-44d4-b024-c9d3cd4ac030)

我这样配置以后发现加载完 umi.js以后，不会再加载sr_pages_index.sync.js 了

![image](https://github.com/umijs/umi/assets/6645414/bab16d4e-69e8-417a-891c-41a12ef2547b)

## Context

- **Umi Version**:4.0.79
- **Node Version**: 18.15.0
- **Platform**: linux

**Comment by qyjandroid** [comment]
![image](https://github.com/umijs/umi/assets/6645414/e7c9d4f3-e547-410d-a875-22cedae5d32d)

**Comment by qyjandroid** [comment]
![image](https://github.com/umijs/umi/assets/6645414/2879a3c1-391f-41d4-a90b-fa5d9ba037a4)

**Comment by qyjandroid** [comment]
有没有人给回复啊

**Comment by fz6m** [comment]
需要给一个不加载内容的最小复现。
