### ISSUE TITLE
[Bug] 档描述去使用icon 不生效.

### ISSUE THREAD

**Issue by LukerSpringtree** [umijs/umi#11628]
## What happens?
按照文档描述去使用icon 不生效.
<img width="750" alt="image" src="https://github.com/umijs/umi/assets/9697295/09c65cf8-c88f-40a6-bcd2-7ea77be87d08">

## Mini Showcase Repository(REQUIRED)
> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
[仓库
](https://github.com/LukerSpringtree/umi-icon-dynamicroute-bug)[
](https://github.com/LukerSpringtree/umi-icon-dynamicroute-bug)

文档中使用 import { Icon } from 'umi';, 
应该更新为 import { Icon } from '@umijs/max';
使用的方法根本不生效.

## How To Reproduce
我项目里面有两个Icon 页面一个 Icon 一个DynamicIcon
顾名思义, Icon是静态路由, DynamicIcom 是动态加载路由.
<Icon icon='local:xxx' />
在静态路由失效.
**Steps to reproduce the behavior:** 1. 2.
1. 点击路由观察代码即可复现.
**Expected behavior** 1. 2.

[
](https://github.com/umijs/umi/issues/11624))

这Issue 评论有定位出来的原因~
## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
动态加载的方式无法使用 icons 这个约定式的方案，因为完全是动态的没法扫描到，解决方式有两个，维护完整的动态路由表：

```ts
const ROUTES_MAP = {
  '/path': React.lazy(() => import(`@/pages/DynamicIcon`)),
  // ...
}
```

或者手动的去添加你要使用的那些图标：

```ts
// .umirc.ts

  icons: {
    include: ['local:rice', ...]
  }
```

如果觉得不方便，就手动导入图标路径得到 url 使用吧，这样更方便。

**Comment by perintery** [comment]
@fz6m 可以， 但是建议文档上补充好， 这些说明

**Comment by yaxiong2** [comment]
`// .umirc.ts

  icons: {
    include: ['local:rice', ...]
  }`
@fz6m 我在配置文件中解析所有本地icons到include里，编译报错【Parse config file failed】。不能在配置文件里写这种吗？

**Comment by yaxiong2** [comment]
```
// .umirc.ts

  icons: {
    include: ['local:rice', ...]
  }
```
@fz6m 可以在配置文件里使用require解析本地icon到include吗

**Comment by fz6m** [comment]
可以在 `.umirc.ts` 内写 node 脚本读取 `src/icons` 里你想要自动加载的目录里所有文件的列表，构造一个 `local:xxx` 的列表放到 `include` 即可。

**Comment by fz6m** [comment]
自己在任意的位置维护路径与 icon 的映射表，然后 patch 到动态路由表里。

**Comment by fz6m** [comment]
需要给一个最小复现
