### ISSUE TITLE
patchClientRoutes的路由如何像静态路由一样 做路由懒加载 有推荐的方式嘛

### ISSUE THREAD

**Issue by ErnestWangZuNian** [umijs/umi#11626]
### Umi 4 默认按页拆包，从而有更快的页面加载速度 静态路由确实是这样 如果是patchClientRoutes动态添加的路由如何实现路由懒加载 自己去懒加载包 官方有推荐的方式嘛

**Comment by ErnestWangZuNian** [comment]
您好，我已收到邮件，我会尽快处理的。。。

**Comment by fz6m** [comment]
可以参考 https://github.com/umijs/umi/discussions/9717#discussioncomment-4078053 ，所有动态添加的路由映射表里的导入都写成懒加载就可以自动分包了 `React.lazy(() => import('./path/to/component'))`

**Comment by ATacoo** [comment]
@fz6m  我看了你的https://github.com/umijs/umi/discussions/9717#discussioncomment-4078053 这个例子。 我这边遇到一个棘手的问题是 需要在登陆后根据用户获取服务器的路由。但是问题是 登陆后 patchClientRoutes 这个方法不触发了。

**Comment by ErnestWangZuNian** [comment]
您好，我已收到邮件，我会尽快处理的。。。

**Comment by fz6m** [comment]
每次刷新用户权限（如登录完设定了 cookie 、local storage 等）后，需要刷新页面重新加载应用，目前无法手动执行 patchClientRoutes 方法。

通常情况下我们在独立的登录页或者 sso 登录，登录完跳转回来或者刷新页面就可以带着权限进入应用，此时 patch 路由的方法就可以按照预期执行了。
