### ISSUE TITLE
[Bug] Icon 本地使用有问题

### ISSUE THREAD

**Issue by LukerSpringtree** [umijs/umi#11624]
## What happens?
按照文档描述去使用icon 不生效.
<img width="897" alt="image" src="https://github.com/umijs/umi/assets/9697295/1026fcd9-af65-46a7-a5ff-337ff40cd931">

## Mini Showcase Repository(REQUIRED)
1.  文档中使用  import { Icon } from 'umi';, 应该更新为 import { Icon } from '@umijs/max';
2. 使用的方法根本不生效.

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
额

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
需要给一个不生效的最小复现。
