### ISSUE TITLE
[Bug] umi3升级umi4后base不能再html中动态设置了?

### ISSUE THREAD

**Issue by chongdongkongjian** [umijs/umi#11638]
## What happens?
在umi3升级到umi/max后，不会再向html文件注入以下脚本：
```html
  <script>
    window.routerBase = "DynamicRoute/";
  </script>
  <script>
    window.publicPath =
      window.resourceBaseUrl || "DynamicRoute/";
  </script>
```
之后我通过`.umirc.ts`注入了代码
```ts
const bathPath = 'DynamicRoute/';
{
base: bathPath,
publicPath: bathPath,
headScripts: [
    `window.routerBase = "${bathPath}";`,
    `window.publicPath =window.resourceBaseUrl || "${bathPath}";`,
  ],
}
```
然后路由会匹配不上，页面白屏
## Mini Showcase Repository(REQUIRED)
之后尝试使用plugin.ts修改运行时配置，
```ts
// plugin.ts
import { IApi } from '@umijs/max';

export default (api: IApi) => {
  api.onGenerateFiles(() => {
    api.writeTmpFile({
      path: 'core/basenameRuntime.ts',
      noPluginDir: true,
      content: `
        export const modifyClientRenderOpts = (ctx) => {
          ctx.basename=window.routerBase;
          return ctx;
        }
      `,
    });
  });

  api.addRuntimePlugin(() => ['@@/core/basenameRuntime.ts']);
};

```
路由匹配没问题了，但是history.push跳转会跳转到DynamicRoute/ ,而不是替换后的路由，又导致路由匹配不上
## How To Reproduce

无报错

## Context

- **Umi Version**:Umi/max v4.0.80
- **Node Version**: v20.5.1

**Comment by fz6m** [comment]
如果要动态修改 `base` ，可以使用正文中描述的 `export const modifyClientRenderOpts` 这个代码片段。

如果要动态修改 `publicPath` ，需要开启 `runtimePublicPath: {}` 并且添加 `window.publicPath = ...` 。

在 umi 4 里使用的是 react router v6 ，react router v6 的设计不再包含 history ，切换路由的方法变成了：

```ts
// https://umijs.org/docs/api/api#usenavigate
import { useNavigate } from 'umi'

const nav = useNavigate()

nav('/path/to/route')
```

这个 react router v6 的导航方法必须在 hooks 里使用，是包含 base 的。

本来 react router v6 是不提供 history 的，但 umi 4 做了 hack 兼容加入了 `history` ，但区别在于 `history` 不是应用内的，所以 `history` 的切换路由方法都不会自动添加 base ，如果你要让 history 的方法也自带 base ，可以考虑 patch history 的方法：

```ts
export const modifyClientRenderOpts = (context) => {
  const h = context.history
  const originPush = h.push
  const originReplace = h.replace
  h.push = (...args) => {
   // args[0] = base + args[0]
   originPush.apply(h, args)
  }
  h.replace = (...args) => {
    originReplace.apply(h, args)
  }
  return context
}
```

只需要在正文的代码片段内添加这段代码到 `modifyClientRenderOpts` 即可。
