### ISSUE TITLE
[Feature Request] 请求umi导出valtio的ref方法

### ISSUE THREAD

**Issue by hexf00** [umijs/umi#11635]
## Background

https://umijs.org/docs/max/valtio

Umi 在 4.0.23 中加入了 Valtio 插件作为一种内置数据流方案，但是未提供 `ref` api，部分对象（如DOM对象）被 Valtio 代理会报错，`ref` api 包裹后的对象不会走 proxy，缺失该机制要求对编码实现还是有比较大的影响，另外，Valtio 不支持从2个库各使用一部分api，希望导出这种基础和必要的能力。

## Proposal

请求添加 valtio  的 `ref` 作为导出项，请求作出评估。或者有什么方法可以访问到 `ref` api。

## Additional context

- umi/valtio 源码文件 https://github.com/umijs/umi/blob/master/packages/plugins/src/valtio.ts
- ref 说明文档 https://github.com/pmndrs/valtio#holding-objects-in-state-without-tracking-them
- https://github.com/pmndrs/valtio/issues/61
- https://github.com/pmndrs/valtio/issues/178
- 报错1 https://github.com/pmndrs/valtio/issues/220
- 报错2 https://github.com/pmndrs/valtio/issues/271
- Valtio 不支持从2个库各使用一部分api https://github.com/pmndrs/valtio/discussions/706

**Comment by fz6m** [comment]
欢迎 PR 添加所需的导出成员并升级 valtio 版本，代码在 https://github.com/umijs/umi/tree/master/libs/valtio

**Comment by sorrycc** [comment]
Fixed.
