### ISSUE TITLE
[Feature Request] umi3升级umi4后base不能再html中动态设置了?

### ISSUE THREAD

**Issue by chongdongkongjian** [umijs/umi#11639]
## What happens?
在umi3升级到umi/max后，不会再向html文件注入以下脚本：
```html
  <script>
    window.routerBase = "DynamicRoute/";
  </script>
  <script>
    window.publicPath =
      window.resourceBaseUrl || "DynamicRoute/";
  </script>
```
之后我通过`.umirc.ts`注入了代码
```ts
const bathPath = 'DynamicRoute/';
{
base: bathPath,
publicPath: bathPath,
headScripts: [
    `window.routerBase = "${bathPath}";`,
    `window.publicPath =window.resourceBaseUrl || "${bathPath}";`,
  ],
}
```
然后路由会匹配不上，页面白屏
## Mini Showcase Repository(REQUIRED)
之后尝试使用plugin.ts修改运行时配置，
```ts
// plugin.ts
import { IApi } from '@umijs/max';

export default (api: IApi) => {
  api.onGenerateFiles(() => {
    api.writeTmpFile({
      path: 'core/basenameRuntime.ts',
      noPluginDir: true,
      content: `
        export const modifyClientRenderOpts = (ctx) => {
          ctx.basename=window.routerBase;
          return ctx;
        }
      `,
    });
  });

  api.addRuntimePlugin(() => ['@@/core/basenameRuntime.ts']);
};

```
路由匹配没问题了，但是history.push跳转会跳转到DynamicRoute/ ,而不是替换后的路由，又导致路由匹配不上
## How To Reproduce

无报错

## Context

- **Umi Version**:Umi/max v4.0.80
- **Node Version**: v20.5.1

**Comment by fz6m** [comment]
See #11638

**Comment by chongdongkongjian** [comment]
@fz6m 如果我想在普通函数(非组件)中编程试跳转路由，应该使用什么API

**Comment by fz6m** [comment]
在 umi 4 中使用的是 react router v6 ，react router v6 只提供了在 hooks 里进行路由跳转的 `const nav = useNavigate(); nav('/path/to/router')` 方法，理论上所有的路由跳转都应该在 hooks 中按规范进行，但 umi hack 了 react router v6 ，暴露了 `history` ，所以你也可以在任意的地方使用 `history.push` 来跳转路由，他们的区别是 `history.xxx` 的路由跳转方法不会自动包含 `base` ，所以如果你的应用配置有 `base` ，在使用 `history` 的方法跳转时需要自己加上 `base` 。
