### ISSUE TITLE
umi4作为子应用集成到主应用后, 如何避免子应用的antd样式被主应用antd覆盖

### ISSUE THREAD

**Issue by wwang5-cloud** [umijs/umi#11640]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
考虑更改 antd 样式的 prefix ，可自行搜索相关文章。
