### ISSUE TITLE
[Bug] favicons 配置不生效

### ISSUE THREAD

**Issue by poyiding** [umijs/umi#11642]
## What happens?

umi@4.0.26 配置 favicons 不生效
## Mini Showcase Repository(REQUIRED)
![image](https://github.com/umijs/umi/assets/15643321/1804443c-f4a6-45dd-b911-303418295ecb)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce
 .umirc.ts 配置  favicons: ['/favicon.png'] 无效
**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:  umi@4.0.26
- **Node Version**: 16. 19.1
- **Platform**:

**Comment by fz6m** [comment]
参考下 [文档](https://umijs.org/docs/api/config#favicons) ，要配成 `['/favicon.ico']`
