### ISSUE TITLE
[Feature Request] @umi/max Qiankun 微前端运行时注册子应用支持动态修改

### ISSUE THREAD

**Issue by nishino-tsukasa** [umijs/umi#11654]
## Background

子应用配置信息 apps 由接口返回，接口有鉴权。只有用户登录后才能调用此接口获取配置信息

## Proposal

希望能提供相关 api，支持运行时注册子应用动态修改，而不是只能在启动时执行获取

**Comment by kuitos** [comment]
see https://umijs.org/docs/max/micro-frontend#%E8%BF%90%E8%A1%8C%E6%97%B6%E6%B3%A8%E5%86%8C%E5%AD%90%E5%BA%94%E7%94%A8

**Comment by fz6m** [comment]
在 render 的时候调用接口获取到配置之后，在 qiankun 运行时配置里动态注册就可以了：

```ts
// src/app.ts

let config = null;

export const render = async (oldRender: any) => {
  config = await api()
  oldRender()
}

export const qiankun = {
  // use config ...
}
```
