### ISSUE TITLE
[Bug] headScripts失效

### ISSUE THREAD

**Issue by liukai3586** [umijs/umi#11662]
![1695195268176](https://github.com/umijs/umi/assets/69024107/6ab98ae6-7c0f-4893-8f6c-b5437d438057)

如上图当我设置qiankun master后 首次加载的loading状态就不生效了，移除qiankun以及设置qiankun slave均是正常的，

**Comment by liukai3586** [comment]
我的版本
"@umijs/max": "^4.0.52",

**Comment by fz6m** [comment]
需要给一个最小复现仓库。

**Comment by liukai3586** [comment]
https://gitee.com/dik-sxqi/test-loading.git 这是最小复现仓库/config/config.ts

**Comment by liukai3586** [comment]
/config/config.ts 注释这个文件里下面的代码就可以正常加载loading 
  qiankun: {
    master: {
    }
  }

**Comment by fz6m** [comment]
对于 qiankun 主子应用，他们的根节点 id 不再是 `root` ，比如主应用是 `root-master` ，当同屏有多个主子应用时，他们的根节点 id 还可能不同，所以如果你有相应的需求，应该使用实际的根节点 id 。

**Comment by liukai3586** [comment]
了解了 多谢
