### ISSUE TITLE
[Bug] 4.0 配置了mfsu: { exclude: ['包名'] } 报错

### ISSUE THREAD

**Issue by rccq17mj** [umijs/umi#11660]
## What happens?

pnpm 项目，umi4 配置了mfsu: { exclude: ['包名'] } 报错

![image](https://github.com/umijs/umi/assets/29419878/32988dc0-995d-4a15-9ca9-2ac9b7f24749)

export default {
    ...
    mfsu: {
        exclude: ['@foundbyte/town-revitalize'],
    }
} as IConfigFromPlugins & IConfig;

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
如有问题，需要给一个最小复现。
