### ISSUE TITLE
copy配置项运行npm run build时报错

### ISSUE THREAD

**Issue by littleQing** [umijs/umi#1166]
//配置
copy: [
  {
    from: path.resolve(__dirname, '../dist'),
    to: path.resolve(__dirname, '../fuck')
  }
]
//报错
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.0.0 build: `umi build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2018-09-29T04_00_44_239Z-debug.log

**Comment by xiaohuoni** [comment]
你这样子一编写一遍拷贝应该是不行吧？你直接设置outputPath:'/fuck'

**Comment by littleQing** [comment]
感谢，编译时拷贝确实不行，设置output Path是正解。感谢大神回复！
