### ISSUE TITLE
[Feature Request] 期望在cssRules文件中添加stylus配置

### ISSUE THREAD

**Issue by tanshenghu** [umijs/umi#11665]
## 期望在cssRules文件中添加stylus配置
- 以前umi3.x版本中可通过插件plugin里有 createCSSRule 可以自行添加配置样式
- 在umi4里面没有createCSSRule了，在源码里面发现你们对于css预编译less、sass、scss默认情况都有支持，唯独stylus没有支持。因为stylus写法简洁清爽，比较受青睐，希望后期umi团队能添加进来

**Comment by fz6m** [comment]
这个在 #11655 支持了，最早在这周四（2023年9月21日）发版后就可以使用。
