### ISSUE TITLE
[Bug] 报错"Uncaught DOMException", 在动态路由情况下, 会有上述的报错.

### ISSUE THREAD

**Issue by LukerSpringtree** [umijs/umi#11675]
## What happens?

报错如下:
<img width="927" alt="image" src="https://github.com/umijs/umi/assets/9697295/86deeebe-f37d-411a-9007-bfe989ecd6e3">

- 动态路由,  在跳转路由的时候, 会有上述报错,;
- 刷新之后, 就好了.

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/LukerSpringtree/umi-icon-dynamicroute-bug
登录~

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
需要给一个可以复现正文中报错的最小复现仓库链接。
