### ISSUE TITLE
[Bug] 配置base之后，路由会叠加两次base

### ISSUE THREAD

**Issue by frankcou** [umijs/umi#11676]
## What happens?
前提：我只有一个路由地址，为/booking
配置base为`/aaaaaaaaaaaaa/`之后，访问localhost:4118/aaaaaaaaaaaaa/booking，会跳转到`localhost:4118/aaaaaaaaaaaaa/aaaaaaaaaaaaa/booking`

浏览器显示警告：`No routes matched location "/aaaaaaaaaaaaa/booking" `

## Mini Showcase Repository(REQUIRED)
这个是我config.local.ts的配置：
```ts
import { defineConfig } from '@umijs/max';

export default defineConfig({
  publicPath: '/',
  base: '/aaaaaaaaaaaaa/', 
  chainWebpack(memo, args) {
    return memo;
  },
});
```
config.ts配置：
```ts
import { defineConfig } from '@umijs/max';
import zhCN from 'antd/locale/zh_CN';

const title  = 'ffff'
export default defineConfig({
  title, 
  layout: { title }, // 全局layout配置
  access: {},
  model: {},
  initialState: {},
  request: {},
  clickToComponent: { editor: 'vscode' },
  autoCSSModules: true, 
  outputPath: 'booking-app-admin',
  history: { type: 'browser' },
  publicPath: '/booking-app-admin/', // 资源位置
  base: '/booking-app-admin/', //基础路由
  hash: true,
  // routes: routes,
  mfsu: {
    esbuild: true, //首次启动更快,但二次编译不会有物理缓存
  },
  analyze: {
    analyzerMode: 'server', //server, static, json, disabled
  },
  npmClient: 'cnpm',
});

```

相关依赖：

## Context
- @umijs/max: 4.0.67
- **Umi Version**:
- **Node Version**: 20.2.0
- **Platform**: windows 11

**Comment by fz6m** [comment]
我使用最新版本 `4.0.81` 的 umi 依赖时，没遇到这个问题，当你配置了 `base` 为 `/aaaaaaaaaaaaa` 时，访问 `/` 路径会自动跳转到 `/aaaaaaaaaaaaa/` ，这是符合预期的。

如有问题，需要给一个可以复现的仓库链接。

**Comment by yoke0104x** [comment]
> aaaaaaaaaaaaa

我知道这个问题是为什么，是因为跳转时不是/xxx/xxx的路由而是用了location.pathname 导致的

**Comment by zhubincode** [comment]
> 怎么解决的
