### ISSUE TITLE
umi 编译后托管到cloudflare报错

### ISSUE THREAD

**Issue by keer6** [umijs/umi#11671]
如题，正常是可以访问的，放到Nginx下也可以。但是一旦放到cloudflare托管就报错，如图
![image](https://github.com/umijs/umi/assets/33250972/e5727910-de0d-4541-8be7-1b12712c5632)

**Comment by keer6** [comment]
![image](https://github.com/umijs/umi/assets/33250972/87f6f598-2ffb-4d38-996e-204c81c5e167)

去网上查了一下，好像是因为cloudflare开启了压缩导致的

- Cf-Bgj: minify - 这个字段表示该响应经过了 CF-BGJ（Brotli and Gzip combined）压缩。
- CF-Cache-Status: HIT - 这个字段表示该响应是从缓存中获取的，而不是从源服务器实时获取的。
- Cf-Polished: origSize=995512 - 这个字段表示该响应经过了 CF-Polished 优化，其中 "origSize" 表示原始响应的大小，单位为字节。
- Content-Encoding: br - 这个字段表示该响应使用了 Brotli 压缩算法进行压缩，提高传输效率。
- Vary: Accept-Encoding - 这个字段指示响应根据请求中的 Accept-Encoding 头部信息来选择适当的压缩算法。

![企业微信截图_16867975599279](https://github.com/umijs/umi/assets/33250972/75ce7d46-9f38-45dd-8bd7-b635b4130d5f)

但是去配置了一下，好像也没用，有朋友 碰到类似问题或者解决办法吗？

**Comment by hanxiaolong-github** [comment]
解决了吗？我也遇到同样的问题。我觉得不是cloudflare 的问题。我用cloudflare 流量到nginx 所在服务器的ip 上是可以的，但是我cloudflare 流量到 aws 的负载均衡上就抱着个错。然后我用godaddy也是同样的问题。

**Comment by jcai** [comment]
@keer6 同样的问题，您解决了吗？如何解决的？谢谢！

**Comment by fz6m** [comment]
如有问题，自行调研 SPA 如何在 CF 相关基础设施（pages、worker 等可能都有所不同）如何部署即可，因为 umi 本质是一个 SPA ，类似的还有 create-react-app 、vue-cli 、vite 等通常构建产物均为 SPA ，部署方法相同。

**Comment by keer6** [comment]
> @keer6 同样的问题，您解决了吗？如何解决的？谢谢！

我没限定依赖的版本，所以跟着最新的一直升级，上次出了这个事我就一直用的Nginx转发的。
但是我这周发现部署到CF以后没问题了，要不你试试把lock文件删了，升级到最新的看看？
我也期待你的实验结果。
