### ISSUE TITLE
编译ts,错误信息不全，缺少路径

### ISSUE THREAD

**Issue by niaoge** [umijs/umi#1167]
刚将项目升级到2.0,
原来在1.0下没有报错文件，在2.0上，yarn run dev时报错了，但是错误的文件没都带路径，都是index.tsx,model.ts，无法定位。如下所示
 ERROR  Failed to compile with 2 errors

 error  in index.tsx

[tsl] ERROR in index.tsx(67,48)
      TS1005: ',' expected.

 @ ./src/pages/.umi/router.js 200:17-45
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js

 error  in model.ts

[tsl] ERROR in model.ts(41,49)
      TS1138: Parameter declaration expected.

 @ ./src/pages/.umi/initDva.js 38:3-84
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js

**Comment by sorrycc** [comment]
和 #1178 重复了，提供一个可重现的库上来吧。
