### ISSUE TITLE
[Feature Request] 每个页面配置单独的多语言文件, 通过namespace加载多语言文件

### ISSUE THREAD

**Issue by starkbtc** [umijs/umi#11674]
## Background
多语言文件太大了，希望能为每个页面配置单独的多语言文件

## Proposal

比如`locale\zh-CN\` 下配置`home.json`, `settings.json`...., 
希望能像`next-i18n`那样通过nameSpace加载相应的语言文件：
`const { t } = useTranslation(['common', 'home', 'settings']);`

**Comment by fz6m** [comment]
umi 是一个 react 的面向中后台的 SPA 应用框架，所以默认面向拥有现代浏览器且现代网络的用户，产物体积不再是关注点，如面临有性能或体积需求的 C 端页面或手机端页面时，则不建议使用 umi ，可以使用 nextjs 。
