### ISSUE TITLE
umi + qiankun 微前端，使用cloudflare 域名，刷新页面抱错502.

### ISSUE THREAD

**Issue by hanxiaolong-github** [umijs/umi#11678]
有两个应用 frame 和 oms 。
frame config 配置是这样：
 {
    path: '/',
    redirect:'/oms'
  },
  {
    path:'/oms/*',
    microApp:'oms',
    microAppProps: {
      autoSetLoading: true,
    },
  }
访问 frame url "xxx.com", 系统自动跳转到 "xxx.com/oms" 这个时候是能够work的。
但是我在浏览器中直接刷新 xxx.com/oms cloudflare 返回 502 
我把cloudflare 的域名换成 godaddy 的却没问题。cloudfalre 里面的 内容压缩，加速 我也都关闭了。
<img width="1415" alt="image" src="https://github.com/umijs/umi/assets/80157042/41b3e2cf-f266-49ed-a740-71ae7d92284b">

**Comment by fz6m** [comment]
涉及到第三方平台请自行排查，比如先确定子应用的 js 、css 资源通过 url 能否正常访问，主应用访问时是否可以正确获取到子应用的 `index.html` ，CF 的安全策略等。

**Comment by hanxiaolong-github** [comment]
@fz6m 你好，我用阿里云的域名也是同样的问题。

环境：
**Umi Version: latest:
**Node Version: 16.0:
**Platform: ubuntu 22:

master 操作步骤：

1. 安装nvm：sudo apt install curl
                      curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
                      source ~/.profile
2. 安装node 16.0 nvm install 16.0
                             nvm use 16.0

3. 安装 nginx  sudo apt-get install nginx 

4. 下载 umi max: mkdir app && cd app
                             npx create-umi@latest
                             选择->antd prod->cnpm->taobao
5. 修改 .umirc.ts:
    export default defineConfig({
      antd: {},
      access: {},
      model: {},
      initialState: {},
      request: {},
      layout: {
        title: '@umijs/max',
      },
      routes: [
        {
          path: '/',
          redirect: '/oms',
        },
        {
    	    path:'/oms/*',
    	    microApp:'oms',
    	    microAppProps: {
      		    autoSetLoading: true,
   	     },
        }
      ],
      qiankun: {
      master: {
        apps: [
          {
            name: 'oms',
            entry: '//test-node.testhello.shop',
            credentials: 'include',
          }
        ],
      },
    },
      npmClient: 'cnpm',
    });

6. 编译程序并且复制到 nginx 运行目录下面，重启nginx：
          npm run build 
          cp -r ./dist/* /var/www/html 
          sudo systemctl restart nginx
7. 把从阿里购买的域名(http://test-admin.testhello.shop)解析到该服务器上。

node 操作步骤：

1. 安装nvm：sudo apt install curl
                      curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
                      source ~/.profile
2. 安装node 16.0 nvm install 16.0
                             nvm use 16.0

3. 安装 nginx  sudo apt-get install nginx 

4. 下载 umi max: mkdir app && cd app
                             npx create-umi@latest
                             选择->antd prod->cnpm->taobao
5. 修改 nginx 配置 
            sudo vi /etc/nginx/sites-enabled/default 

   server {
	    listen 80 default_server;
	    listen [::]:80 default_server;
    
	    # SSL configuration
	    #
	    # listen 443 ssl default_server;
	    # listen [::]:443 ssl default_server;
	    #
	    # Note: You should disable gzip for SSL traffic.
	    # See: https://bugs.debian.org/773332
	    #
	    # Read up on ssl_ciphers to ensure a secure configuration.
	    # See: https://bugs.debian.org/765782
	    #
	    # Self signed certs generated by the ssl-cert package
	    # Don't use them in a production server!
	    #
	    # include snippets/snakeoil.conf;
    
	    root /var/www/html;
    
	    # Add index.php to the list if you are using PHP
	    index index.html index.htm index.nginx-debian.html;
    
	    server_name _;
    
	    location / {
		     add_header Access-Control-Allow-Origin http://test-admin.testhello.shop;
        add_header Access-Control-Allow-Headers "*";
        add_header Access-Control-Allow-Methods "*";
        add_header Access-Control-Allow-Credentials 'true';
        expires -1;                          # 首页一般没有强制缓存
        add_header Cache-Control no-cache;
		    # First attempt to serve request as file, then
		    # as directory, then fall back to displaying a 404.
		    try_files $uri $uri/ =404;
	    }
    
	    # pass PHP scripts to FastCGI server
	    #
	    #location ~ \.php$ {
	    #	include snippets/fastcgi-php.conf;
	    #
	    #	# With php-fpm (or other unix sockets):
	    #	fastcgi_pass unix:/run/php/php7.4-fpm.sock;
	    #	# With php-cgi (or other tcp sockets):
	    #	fastcgi_pass 127.0.0.1:9000;
	    #}
    
	    # deny access to .htaccess files, if Apache's document root
	    # concurs with nginx's one
	    #
	    #location ~ /\.ht {
	    #	deny all;
	    #}
    }
    
    
    # Virtual Host configuration for example.com
    #
    # You can move that to a different file under sites-available/ and symlink that
    # to sites-enabled/ to enable it.
    #
    #server {
    #	listen 80;
    #	listen [::]:80;
    #
    #	server_name example.com;
    #
    #	root /var/www/example.com;
    #	index index.html;
    #
    #	location / {
    #		try_files $uri $uri/ =404;
    #	}
    #}

 6. 编译程序并且复制到 nginx 运行目录下面，重启nginx：
          npm run build 
          cp -r ./dist/* /var/www/html 
          sudo systemctl restart nginx

7. 把从阿里购买的域名(http://test-node.testhello.shop)解析到该服务器上。


这个时候我访问 http://test-admin.testhello.shop 程序自动跳转到 http://test-admin.testhello.shop/oms/home 并且运行成功。
但是我刷新 http://test-admin.testhello.shop/oms/home 这个页面就抱错 502 Bad Gateway
奇怪的是：我把godaddy 的域名解析到这两个服务器上运行确实ok的。

**Comment by fz6m** [comment]
spa 在刷新页面的时候需要自动 fallback 到 `index.html` ：

```conf
  try_files $uri $uri/ /index.html;
```

这个地方的 `/index.html` 看看行不行，如果还不行酌情调整下文件位置，让它 fallback 回产物的 `index.html` 就行。

**Comment by hanxiaolong-github** [comment]
try_files $uri $uri/ /index.html;  还是不行。
我觉得不是 fallback 的问题，按照我上面的配置应该最后显示 404 页面，但是显示的是502 Bad Gateway。

我在 .umirc.ts 里面加上 history:{type:'hash'} 是可以了。但是访问路由http://test-admin.testhello.shop/ 自动跳转到 http://test-admin.testhello.shop/#/oms/home。多了个 '#'
@fz6m

**Comment by fz6m** [comment]
hash 里的东西不算在路径里，服务端看不到，所以 `/#/path/to/xxx` 本质还是 `/` 这个路径，现在根路径 `/` 是好的，在这个路径访问可以正常跳转 SPA 内的路由，但在非根路径刷新有问题，这说明没有将请求 fallback 到 `index.html` ，一定是 fallback 的问题，在这上面排查就可以，最终的结果应该是访问任何的 `/*` 都打到 `index.html` 上。

**Comment by hanxiaolong-github** [comment]
try_files $uri $uri/ /index.html; 这样是对的。我刚才有个其他的地方忘记改了。已解决。
