### ISSUE TITLE
headScripts失效

### ISSUE THREAD

**Issue by liukai3586** [umijs/umi#11670]
![image](https://github.com/umijs/umi/assets/69024107/04c30b74-ff54-4a54-a60f-6cede4279d70)

##最小复现仓库
https://gitee.com/dik-sxqi/test-loading.git 

## 复现
/config/config.ts 注释这个文件里下面的代码就可以正常加载loading
qiankun: {
master: {
}
}

**Comment by fz6m** [comment]
See https://github.com/umijs/umi/issues/11662#issuecomment-1730058362
