### ISSUE TITLE
[Bug] openapi集成失败，报api.addMiddewares is not a function错误

### ISSUE THREAD

**Issue by yqw19920724** [umijs/umi#11683]
我设置的openapi
import { join } from 'path';

const openApiConfig = {
    requestLibPath: "import { request } from 'umi'",
    // 或者使用在线的版本
    // schemaPath: "https://gw.alipayobjects.com/os/antfincdn/M%24jrzTTYJN/oneapi.json",
    schemaPath: join(__dirname, 'openApi.json'),
    mock: false,
}

export default openApiConfig

运行 yarn max openapi后，报错
fatal - TypeError: api.addMiddewares is not a function
    at _default (/Users/chenfeng/Desktop/code/umi/node_modules/@umijs/plugin-openapi/lib/index.js:118:7)
    at Service.initPlugin (/Users/chenfeng/Desktop/code/umi/node_modules/@umijs/core/dist/service/service.js:463:40)
    at Service.run (/Users/chenfeng/Desktop/code/umi/node_modules/@umijs/core/dist/service/service.js:259:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Service.run2 (/Users/chenfeng/Desktop/code/umi/node_modules/umi/dist/service/service.js:65:12)
    at async run (/Users/chenfeng/Desktop/code/umi/node_modules/umi/dist/cli/cli.js:57:7)
fatal - A complete log of this run can be found in:
fatal - /Users/chenfeng/Desktop/code/umi/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
error Command failed with exit code 1.

**Comment by fz6m** [comment]
umi 4 的 openapi 插件在 [这个仓库](https://github.com/umijs/umi-presets-pro/tree/master/packages/max-plugin-openapi) ，以前 `@umijs/plugin-xxx` 的插件均不适用于 umi 4 ，你可以用 umi-presets-pro 这个预设，包含了 [很多](https://github.com/umijs/umi-presets-pro/blob/master/packages/umi-preset-pro/src/index.ts) 实用的功能。

**Comment by zyk2891** [comment]
那怎么通过scripts启动啊？原来plugin-xxx启动命令是umi oepnapi,现在又没有max openapi。

**Comment by zyk2891** [comment]
我看antd-pro里面脚手架的openapi启动命令是max openapi,那为什么我在自己项目里手动安装@umijs/max-plugin-openapi和@umijs/max,没办法用max openapi启动

**Comment by fz6m** [comment]
如果你要在 umi 4 里独立集成 openapi 这个功能，可以单独配置：

```bash
  pnpm add -D
```

```ts
// .umirc.ts

  plugins: ['@umijs/max-plugin-openapi'],

  // ↓ 取自 https://github.com/ant-design/ant-design-pro/blob/master/config/config.ts#L137C3-L150C5
  openAPI: [
    {
      requestLibPath: "import { request } from '@umijs/max'",
      // 或者使用在线的版本
      // schemaPath: "https://gw.alipayobjects.com/os/antfincdn/M%24jrzTTYJN/oneapi.json"
      schemaPath: join(__dirname, 'oneapi.json'),
      mock: false,
    },
    {
      requestLibPath: "import { request } from '@umijs/max'",
      schemaPath: 'https://gw.alipayobjects.com/os/antfincdn/CA1dOm%2631B/openapi.json',
      projectName: 'swagger',
    },
  ],
```

仓库位置在：https://github.com/umijs/umi-presets-pro/tree/master/packages/max-plugin-openapi

然后可以用 `umi openapi` 这样，无需安装 `@umijs/max`

**Comment by zyk2891** [comment]
对 我想问的就是如果单独集成了openapi，安装好@umijs/max-plugin-openapi之后，如何通过scripts启动openapi？如果直接执行umi openapi，就会报错umi undefined，max openapi也报错，我记得因为之前有说umi和umi/max不能同时安装，所以应该也不需要安装umi吧

**Comment by zyk2891** [comment]
好的 我明天试试 谢谢大佬

**Comment by zyk2891** [comment]
解决了，可能是我全局装了umi或者是pnpm add -D swagger-ui-dist之后成功的，原来没全局装umi之前会报umi不是一个可运行程序
