### ISSUE TITLE
自定义子应用的loading一直为true,设置了autoSetLoading，但是这个loading一直存在，是利用样式盖住了，但是如果层级不够的话，盖不住这个loading，可以改成loading为false，直接删掉这个loading dom吗

### ISSUE THREAD

**Issue by WebSealinda** [umijs/umi#11689]
![image](https://github.com/umijs/umi/assets/29306863/5be952f2-8db9-4f7b-b172-8781fa362aba)

**Comment by fz6m** [comment]
自定义一下 loading 组件吧，最新版本的 umi 4 在 [`qiankun.master.defaultLoader`](https://umijs.org/docs/max/micro-frontend#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8A%A0%E8%BD%BD%E5%8A%A8%E7%94%BB) 这个选项里可以自己定义一个 loading 组件，这个组件会收到 loading 这个状态的 props ，判断下如果不 loading 就不渲染。
