### ISSUE TITLE
jest-enzyme 失效

### ISSUE THREAD

**Issue by tolerance-go** [umijs/umi#1168]
https://codesandbox.io/s/3yqp199n11

https://github.com/FormidableLabs/enzyme-matchers/tree/master/packages/jest-enzyme

**Comment by tolerance-go** [comment]
![image](https://user-images.githubusercontent.com/37258382/46242508-8a0bbc80-c3fc-11e8-9a60-a98d295531e4.png)

**Comment by sorrycc** [comment]
不熟悉 enzyme，可以试试 react-test-renderer。
