### ISSUE TITLE
[Bug] umimax + qiankun 子应用通过路由绑定引入 无法显示

### ISSUE THREAD

**Issue by lis-soft** [umijs/umi#11686]
主应用和子应用都是通过umimax 创建，通过路由绑定引入子应用如果不能 * 通配的方式 ，子应用加载成功但无法显示，下面是复现代码

复现仓库地址 ：https://gitee.com/leeSn6/umimax-qiankun
clone地址： https://gitee.com/leeSn6/umimax-qiankun.git

![image](https://github.com/umijs/umi/assets/73830471/ebec8d3e-a80b-41d9-a31d-bef2cfb1417b)

**Comment by lis-soft** [comment]
![image](https://github.com/umijs/umi/assets/73830471/e5aa87aa-601e-475c-abcf-89d46e07d77a)

**Comment by fz6m** [comment]
```ts
// routes

  {
    name: '低代码平台',
    path: '/low-code',
    component: '@/components/LowCode',
    routes: [
      {
        name: '渲染器',
        path: '/low-code/home',
      },
      {
        name: '编辑器',
        path: '/low-code/editor',
      },
    ],
  },
```

```ts
// src/components/LowCode/index.tsx

import { MicroApp, useRouteProps } from '@umijs/max';

export default function Page() {
  const props = useRouteProps();

  return <MicroApp name="low-code" url={props.path} />;
}
```

**Comment by lis-soft** [comment]
按您的修改了，还是提示no routes ,

**Comment by lis-soft** [comment]
> ![image](https://user-images.githubusercontent.com/73830471/270278957-e5aa87aa-601e-475c-abcf-89d46e07d77a.png)


按您的修改了，还是提示no routes ,

**Comment by lis-soft** [comment]
> ```ts
> // routes
> 
>   {
>     name: '低代码平台',
>     path: '/low-code',
>     component: '@/components/LowCode',
>     routes: [
>       {
>         name: '渲染器',
>         path: '/low-code/home',
>       },
>       {
>         name: '编辑器',
>         path: '/low-code/editor',
>       },
>     ],
>   },
> ```
> 
> ```ts
> // src/components/LowCode/index.tsx
> 
> import { MicroApp, useRouteProps } from '@umijs/max';
> 
> export default function Page() {
>   const props = useRouteProps();
> 
>   return <MicroApp name="low-code" url={props.path} />;
> }
> ```

按您的修改了，还是提示 no routes

**Comment by lis-soft** [comment]
> ```ts
> // routes
> 
>   {
>     name: '低代码平台',
>     path: '/low-code',
>     component: '@/components/LowCode',
>     routes: [
>       {
>         name: '渲染器',
>         path: '/low-code/home',
>       },
>       {
>         name: '编辑器',
>         path: '/low-code/editor',
>       },
>     ],
>   },
> ```
> 
> ```ts
> // src/components/LowCode/index.tsx
> 
> import { MicroApp, useRouteProps } from '@umijs/max';
> 
> export default function Page() {
>   const props = useRouteProps();
> 
>   return <MicroApp name="low-code" url={props.path} />;
> }
> ```

按您的修改了，还是提示no routes  ，已提交gitee

**Comment by fz6m** [comment]
修正 `src/components/LowCode/index.tsx` 为以下内容即可：

```ts
import { MicroApp, useRouteProps } from '@umijs/max';

export default function Page() {
  const props = useRouteProps();

  return <MicroApp name="low-code" base='/low-code' />;
}
```

参考 [<MicroApp /> 组件引入子应用](https://umijs.org/docs/max/micro-frontend#microapp--%E7%BB%84%E4%BB%B6%E5%BC%95%E5%85%A5%E5%AD%90%E5%BA%94%E7%94%A8)

**Comment by lis-soft** [comment]
> 修正 `src/components/LowCode/index.tsx` 为以下内容即可：
> 
> ```ts
> import { MicroApp } from '@umijs/max';
> 
> export default function Page() {
>   return <MicroApp name="low-code" base='/low-code' />;
> }
> ```
> 
> 参考 [ 组件引入子应用](https://umijs.org/docs/max/micro-frontend#microapp--%E7%BB%84%E4%BB%B6%E5%BC%95%E5%85%A5%E5%AD%90%E5%BA%94%E7%94%A8)

感谢，已经可以了，但是我想通过 路由匹配引入子应用的方式 替代上面的方案，能实现吗

**Comment by fz6m** [comment]
`路由匹配引入子应用的方式` 是啥意思，你可以在路由表里添加一些自定义键值对，然后用 `useRouteProps` 取出来放到 `<MicroApp name={props.microAppName} base={props.microAppBase} />` 做到这个子应用展示区域的通用化。

**Comment by lis-soft** [comment]
> `路由匹配引入子应用的方式` 是啥意思，你可以在路由表里添加一些自定义键值对，然后用 `useRouteProps` 取出来放到 `<MicroApp name={props.microAppName} base={props.microAppBase} />` 做到这个子应用展示区域的通用化。

好的，感谢
