### ISSUE TITLE
[Bug] 当history.push使用state传递函数时，useLocation()无法获取state

### ISSUE THREAD

**Issue by helloJincheng** [umijs/umi#11699]
## What happens?
当使用  `  history.push('/demo/list-data/detail', { name: 1, getData: () => {} });`state里面的属性是方法的时候，跳转界面后使用useLocation()无法获取state
![image](https://github.com/umijs/umi/assets/27672145/18ff7f43-e877-47ad-9249-5a614be48fbc)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:4.0.48
- **Node Version**: 16
- **Platform**: mac

**Comment by fz6m** [comment]
在 react router 中，路由 state 参数无法传递函数。
