### ISSUE TITLE
onRouteChange 路由没有变化只是url变了也触发了

### ISSUE THREAD

**Issue by junegod** [umijs/umi#11696]
## What happens?

onRouteChange 路由没有变化只是url变了也触发了，原来没这问题
比如url从 /console/log/serviceLog/list?a=1 变成 /console/log/serviceLog/list?a=2也会触发onRouteChange 

使用ahooks的`useUrlState`来改变的url
```typescript
const [urlParams, setUrlParams] = useUrlState<>();
```

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/vkboo/demos-umi4-issue-tailwindcss

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

在app.tsx中配置

```typescript
export function onRouteChange({ location }: any) {
  // 解决首页不跳转到根路径bug
  if (location.pathname === '/') {
    history.push('/');
  }
  // 检查版本变化
  CheckVersion();
}
```

## Context

- **Umi Version**: 4.0.81
- **Node Version**: 18.12.1
- **Platform**: mac\windows

**Comment by fz6m** [comment]
路由分三部分，url、search、hash，把 `search` 参数改了也等于路由变化了，如果需要判断 url 变化，自己判断一下 `onRouteChange` 回调参数里 `location.pathname` 是否变化。

**Comment by junegod** [comment]
> 路由分三部分，url、search、hash，把 `search` 参数改了也等于路由变化了，如果需要判断 url 变化，自己判断一下 `onRouteChange` 回调参数里 `location.pathname` 是否变化。

我怎么判断呢，你回传的几个参数里拿不到旧的location，我没法比较

**Comment by junegod** [comment]
@fz6m

**Comment by fz6m** [comment]
把上一次的 location 保存一下。

```ts
let prevLocation = null;

export const onRouteChange = () => {
  // prevLocation = ...
}
```

**Comment by junegod** [comment]
感谢
