### ISSUE TITLE
text: 'Expected ">" but found "/"'[Bug] say something

### ISSUE THREAD

**Issue by liushunli** [umijs/umi#11701]
![image](https://github.com/umijs/umi/assets/12014406/85ab5121-465b-45e8-9ed9-62826a23fbce)
![image](https://github.com/umijs/umi/assets/12014406/61c37d04-fb16-4d82-bd4b-44bfcb05e36b)

<img width="560" alt="1696121526387" src="https://github.com/umijs/umi/assets/12014406/e4cb831a-9662-45bf-906f-5467384d9a93">

为什么按照官方文档配置，这个组件引入就是有问题

**Comment by fz6m** [comment]
See #11700
