### ISSUE TITLE
```tsx

### ISSUE THREAD

**Issue by liushunli** [umijs/umi#11703]
menu: {
      locale: false,
      params: {
        menuData: initialState?.menuData
      },
       request: async (params: any, defaultMenuData: any) => {
         // 这里可以调接口, params变化调用request
         console.log(params,'dd')
         console.log(defaultMenuData)
        const newmenu= []
        return newmenu // 和defaultMenuData数据类型一样
       },
    },

为啥不能直接用这个，这个怎么用

**Comment by fz6m** [comment]
数据结构详情查看 type 提示。
