### ISSUE TITLE
关于配置式路由Path路径的问题

### ISSUE THREAD

**Issue by acpplife** [umijs/umi#1170]
你好！
请问比如根目录路由path定义为/home，那么下面的所有子路由都必须是/home/**结构的吗？现在的情况是非这种页面直接到404了。因现有路由路径已和数据库权限关联不方便修改，有什么办法可以支持非/home的路由吗？
项目改造，急~谢谢！
![](https://gt-toolbox.oss-cn-beijing.aliyuncs.com/gt-toolbox/0e0d6f36-3acc-4de9-80ad-d5b949b4d200.png)

**Comment by acpplife** [comment]
因后台菜单较多，后期也随时可能改变菜单结构，如果必须要修改路由的话每次调整菜单实在太麻烦了。

**Comment by xiaohuoni** [comment]
没听懂

**Comment by sorrycc** [comment]
没理解啊，重新组织下问题描述再 reopen 吧。

**Comment by acpplife** [comment]
你好，不好意思是我的描述问题。问题是这样的。
```
{
      name: 'a',
      path: '/a',
      routes: [
        {
          name: 'ab',
          path:'/a/ab'
        },
        {
          name: 'b',
          path:'/b'
        },
      ]
}
```
假如路由是这么定义的，path为'/a'的routes必须是'/a'开头的吗？现在我这儿的现象是下面的'/b'的路由直接到404页面了。还是我的写法有问题呢？
@sorrycc 大神

**Comment by sorrycc** [comment]
`/a` 下不应该有 `/b`，不能这么用，`/b` 只能放在外面。

**Comment by acpplife** [comment]
好的，谢谢~
请问下我们现在有需求用户可以自己编辑菜单结构层级，那现在这种情况下好像是实现不了的。有什么办法可以解决吗？谢谢！
@sorrycc

**Comment by usernameisMan** [comment]
```
{
      name: 'a',
      path: '/a',
      routes: [
        {
          name: 'ab',
          path:'/a/ab',
            routes: [
             {
                name: 'abc',
                path:'/a/ab/abc',
                hideInMenu: true
             },
            ]
        },
      ]
}
```
我是这样就 提示 umi development 404 page了 /a/ab有页面 /a/ab/abc 就挂了

**Comment by 86100488z** [comment]
> ```
> {
>       name: 'a',
>       path: '/a',
>       routes: [
>         {
>           name: 'ab',
>           path:'/a/ab',
>             routes: [
>              {
>                 name: 'abc',
>                 path:'/a/ab/abc',
>                 hideInMenu: true
>              },
>             ]
>         },
>       ]
> }
> ```
> 
> 我是这样就 提示 umi development 404 page了 /a/ab有页面 /a/ab/abc 就挂了

我也遇到了老铁 请问有解决方案么

**Comment by Sayid1** [comment]
垃圾路由，嵌套几层就不行了

**Comment by sorrycc** [comment]
是 bug，可先通过给每个有 routes 的加能精确匹配的路由解决，比如：

```
export default {
  routes: [
    {
      path: '/a',
      component: 'a',
      routes: [
        { path: '/a', component: 'index' },
        {
          path: '/a/ab',
          component: 'ab',
          routes: [
            { path: '/a/ab', component: 'index' },
            { path: '/a/ab/abc', component: 'abc' }
          ],
        },
      ],
    },
  ],
};
```

示例：

[sorrycc-DmDJLY.zip](https://github.com/umijs/umi/files/3812358/sorrycc-DmDJLY.zip)
