### ISSUE TITLE
[Bug] srcTranspiler是否支持“none”这个选项？

### ISSUE THREAD

**Issue by PopperLi** [umijs/umi#11727]
## What happens?

https://github.com/umijs/umi/blob/master/packages/bundler-webpack/src/types.ts 中配置了`Transpiler`支持`“none”`的配置，但(实现代码中)[packages\bundler-webpack\src\config\javaScriptRules.ts]并没有支持`“none”`这个配置，导致`config.srcTranspiler`会报错: `Error: Unsupported srcTranspiler none.`。

## How To Reproduce

1. 配置`config.srcTranspiler = 'none'`
2. `$ pnpm max build`

**Comment by fz6m** [comment]
暂不支持 `none` 选项，因为不转译后续可能出问题。
