### ISSUE TITLE
import **.css中报Can't resolve 文件错误

### ISSUE THREAD

**Issue by sillyfeng** [umijs/umi#1172]
我在项目里有用到semantic-ui。然后page中引用了 `import 'semantic-ui-css/semantic.min.css` 
这个css文件中，会以相对路径来引用他目录下 themes文件夹下的font文件。
但是在 **.umirc.js**中有配置  **cssLoaderOptions: { modules: true }** 的话启动的时候会报 _Can't resolve..._的错误
重现连接: https://codesandbox.io/s/3rk3zv51z1

**Comment by sorrycc** [comment]
那为啥要配 `modules: true` ?

**Comment by sillyfeng** [comment]
@sorrycc  这个是项目里的一个页面，其他的页面还是要用到`className`。如果这种是正常的话，我就想办法引用cdn的css吧。
项目是在`ant-design-pro`的基础上开发的，之前`roadhog`下没有问题。

**Comment by sorrycc** [comment]
我觉得应该是不支持这样配吧，统一要么用 css modules，要么不用。

**Comment by rendongsc** [comment]
@sillyfeng 解决了吗？我也遇到相同的问题了。
