### ISSUE TITLE
未配置target，build的代码，带有箭头函数

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#1173]
<img width="855" alt="wx20180929-175114 2x" src="https://user-images.githubusercontent.com/11746742/46244369-a0bc0e80-c410-11e8-8b1a-be0a99eb291d.png">
测试了google和Safari都可以访问。不知道需不需要处理！

**Comment by xiaohuoni** [comment]
什么配置也不用改，直接升级最新的umi，执行build就可以重现

**Comment by sorrycc** [comment]
默认的浏览器版本配地比较高，这些语法并不需要转换，所以没有问题。
