### ISSUE TITLE
[Bug] useSnapshot的ts type 变成了any

### ISSUE THREAD

**Issue by Pulset** [umijs/umi#11737]
## What happens?

升级4.0.62版本之后，useSnapshot的TS类型变成了any，4.0.61版本正常
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

<img width="567" alt="image" src="https://github.com/umijs/umi/assets/21022593/3f91e93c-9281-4b98-a3c1-a35a3a7db7d2">

## Context

- **Umi Version**: v4.0.62
- **Node Version**: v16.20.2
- **Platform**: mac

**Comment by fz6m** [comment]
升级到最新的 Umi 4 版本吧，注意 cmd/ctrl + shift + p 输入 restart ts 来重启一下 TS 服务器防止 IDE 类型识别抽风。

**Comment by Pulset** [comment]
> 升级到最新的 Umi 4 版本吧，注意 cmd/ctrl + shift + p 输入 restart ts 来重启一下 TS 服务器防止 IDE 类型识别抽风。

我本身用的就是umi4，安装4.0.61版本就正常，4.0.62到最新的版本就有问题，我这边是必现的

**Comment by fz6m** [comment]
确保你的 umi 版本是最新的，IDE 版本是最新的，IDE 正确配置了使用项目内的 ts 引擎（ vscode 在右下角配置 ts 引擎路径），`tsconfig.json` 是正确的没有自行修改过，可以自己生成一个新的项目对比下哪里有区别，是不是新项目还有这个问题。

如还有问题，需要给一个最小复现。
