### ISSUE TITLE
[Bug] global.ts中document无法触发DOMContentLoaded事件

### ISSUE THREAD

**Issue by tom-chanafanghua** [umijs/umi#11738]
## What happens?
global.ts中document无法触发DOMContentLoaded事件

## Mini Showcase Repository(REQUIRED)
https://github.com/tom-chanafanghua/umiDemo

## Context

- **Umi Version**  v4.0.85
- **Node Version**: 16.17.0
- **Platform**: window

**Comment by fz6m** [comment]
在 react 应用里就摒弃掉原生事件这个概念了，不应该在项目代码里监听原生事件，如果需要监听非事件代理过的原生事件，可以写到全局 [`headScripts`](https://umijs.org/docs/api/config#headscripts) 配置里。
