### ISSUE TITLE
[Bug] 4.0.86 版本热更新出问题了

### ISSUE THREAD

**Issue by xiaoliu1990** [umijs/umi#11744]
## What happens?
下载我上传的包，启动项目后，打开地址
http://localhost:8000/#/list
刚进来是可以打开的，然后随便找一个antd 4版本的组件，加进去，保存后，热更新就报错了

## Context
![Snipaste_2023-10-16_18-24-16](https://github.com/umijs/umi/assets/17424034/b738128e-4e64-43e6-8758-1ecf5bbae1a1)
下载包：

[pcts-v4.zip](https://github.com/umijs/umi/files/12915122/pcts-v4.zip)

- **Umi Version**: 4.0.86
- **Node Version**:16.18.0
- **Platform**: window 10系统 Google Chrome 117.0.5938.150版本 浏览器

**Comment by fz6m** [comment]
现在 max 的内置 antd 插件默认使用的是 antd 5 ，当你需要 antd 4 时，需要手动安装具体的版本到 `package.json` ，这样才会使用你自己安装的版本。

**Comment by MasterBran** [comment]
@xiaoliu1990 真实原因是某些场景下mfsu产生了多个React实例，修复方案在官网搜索MFSU也能找到，在.umirc.ts中添加设置` mfsu: {
    shared: {
      react: {
        singleton: true,
      },
    },
  },`
