### ISSUE TITLE
子项目里面打包出来的css加载顺序变化

### ISSUE THREAD

**Issue by WebSealinda** [umijs/umi#11742]
第一次加载子应用的顺序在其他样式后面
![image](https://github.com/umijs/umi/assets/29306863/b57bc667-0e31-425e-840b-da8530f18349)
第一次加载子应用的顺序在其他样式前面，我定义了一个a标签样式，导致被qiankun-head里面自带的a标签样式覆盖了

![image](https://github.com/umijs/umi/assets/29306863/260fb3bc-c612-41b3-b221-41bfd364d61b)

**Comment by fz6m** [comment]
由于 qiankun 默认不样式隔离，这可以防止弹窗位置不合理的问题，所以不应该编写会干扰到全局样式的 css ，或者保持每个应用都是一致的 ui 库，对于组件样式应该统一使用 css modules / css in js 来隔离。
