### ISSUE TITLE
[Bug] umi@3 下路由路径问题

### ISSUE THREAD

**Issue by qiujie8092916** [umijs/umi#11746]
## What happens?
在路由配置里：
``` js
[{
	// ...
	component: '@@/plugin-AA/layout',
	// ...
}]
```

最终会被转成 `/Users/xxx/Documents/project/xxx/src/pages//Users/xxx/Documents/project/xxx/src/.umi/plugin-AA/layout`

1. 会先被`core/lib/Route/Route.js`转成`/Users/xxx/Documents/project/xxx/src/pages/@@/plugin-AA/layout`  
``` js
if (
      route.component &&
      !opts.isConventional &&
      typeof route.component === 'string' &&
      !route.component.startsWith('@/') &&
      !path.isAbsolute(route.component)
    ) {
      route.component = winPath(join(opts.root, route.component));
    }
```
2. 再被`plugin-ui-blocks/lib/ui/utils.js`转成`/Users/xxx/Documents/project/xxx/src/pages//Users/xxx/Documents/project/xxx/src/.umi/plugin-AA/layout`  
```js
const routeComponent = route.component
          ?.replace('@@', paths.absTmpPath)
          ?.replace('@', paths.absSrcPath);
        const component = isAbsolute(routeComponent)
          ? require.resolve(routeComponent)
          : require.resolve(join(cwd, routeComponent));
```

**Expected behavior**
希望可以在路由的 `component`支持引用临时文件夹`@@`下的路径
正确返回`/Users/xxx/Documents/project/xxx/src/.umi/plugin-AA/layout`
## Context

- **Umi Version**: 3.5.37
- **Node Version**: 16.18.0
- **Platform**: macOS 13.0.1

**Comment by fz6m** [comment]
你给它包一下不行吗，反正 `@@/` 就是 `@/${process.env.NODE_ENV === 'production' ? '.umi-production' : '.umi'}/` 。

umi 3 不维护了，建议升级到 umi 4 。

**Comment by qiujie8092916** [comment]
> 你给它包一下不行吗，反正 `@@/` 就是 `@/${process.env.NODE_ENV === 'production' ? '.umi-production' : '.umi'}/` 。
> 
> umi 3 不维护了，建议升级到 umi 4 。

在 umi 4 中，路由里的 component 组件会先加载吗，加载的时候貌似临时文件还没写到 .umi？

**Comment by fz6m** [comment]
写临时文件的命令是 `umi setup` ，有 `"postinstall": "umi setup",` 这个命令的话，在你启动 dev 前一定会生成好临时文件，所以启动服务的时候临时文件一定是在的。

**Comment by qiujie8092916** [comment]
`umi setup` umi 命令同样执行在配置加载之后，加载配置的时候也会加载路由的配置（会读取路由里的 component 指向的文件）这时候还没到真正执行 setup 命令吧

**Comment by fz6m** [comment]
如有问题，需要给一个最小复现。
