### ISSUE TITLE
[Bug] 10557的解决方案会产生新的问题

### ISSUE THREAD

**Issue by Chill7773** [umijs/umi#11753]
## What happens?
https://github.com/umijs/umi/issues/10557
解决方案会使得子应用加载两次，从而产生闪烁

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
如果不想配置菜单，可以自己针对某些路径的路由定义一个组件，在组件里用 [`<MicroApp />`](https://umijs.org/docs/max/micro-frontend#microapp--%E7%BB%84%E4%BB%B6%E5%BC%95%E5%85%A5%E5%AD%90%E5%BA%94%E7%94%A8) 渲染自己想要的东西。

**Comment by Chill7773** [comment]
> [`<MicroApp />`](https://umijs.org/docs/max/micro-frontend#microapp--%E7%BB%84%E4%BB%B6%E5%BC%95%E5%85%A5%E5%AD%90%E5%BA%94%E7%94%A8)

[<MicroApp />](https://umijs.org/docs/max/micro-frontend#microapp--%E7%BB%84%E4%BB%B6%E5%BC%95%E5%85%A5%E5%AD%90%E5%BA%94%E7%94%A8)显示不出来

**Comment by Chill7773** [comment]
> > [`<MicroApp />`](https://umijs.org/docs/max/micro-frontend#microapp--%E7%BB%84%E4%BB%B6%E5%BC%95%E5%85%A5%E5%AD%90%E5%BA%94%E7%94%A8)
> 
> 显示不出来

使用<MicroAppWithMemoHistory /> 正常显示
