### ISSUE TITLE
umijs 是否支持webpack5的resolve.fallback属性，“当正常解析失败时，重定向模块请求”

### ISSUE THREAD

**Issue by ljmCoder** [umijs/umi#11751]
umijs 是否支持webpack5的resolve.fallback属性，“当正常解析失败时，重定向模块请求”

尝试通过chainwebpack进行配置。 发现chainwebpack目前并不支持这一操作。

请教各位，是我使用错误？或者有其他解决办法吗

![image](https://github.com/umijs/umi/assets/41459781/5a3584bd-c3fe-48c7-ad83-0659a9fe4c7b)
![image](https://github.com/umijs/umi/assets/41459781/13e76be5-9f96-442c-b266-8829750d68e0)

**Comment by fz6m** [comment]
See #11750
