### ISSUE TITLE
[Bug] npm 包中含有 import XX from umi; 在 umi4 项目中使用此组件时会报错

### ISSUE THREAD

**Issue by liuwenzhuang** [umijs/umi#11754]
## What happens?

使用 max 的模板项目时使用到了一个组件，此组件中使用了 umi 中提供的能力，如 `import { useLocation } from 'umi';` ，当此组件被安装到模板项目中后，使用 `yarn dev` 启动项目访问页面时会出现以下错误：

```bash
TypeError: Cannot read properties of undefined (reading 'call')
__webpack_require__
https://tmy3dr-8000.csb.app/mf-va_remoteEntry.js:1304:42
./src/.umi/exports.ts
https://tmy3dr-8000.csb.app/src_umi_umi_ts.async.js:1790:110
__webpack_require__
https://tmy3dr-8000.csb.app/mf-va_remoteEntry.js:1304:42
./node_modules/lwz-component-with-umi/dist/components/index.js
https://tmy3dr-8000.csb.app/mf-dep____vendor.8fc77bc7.js:176214:61
__webpack_require__
https://tmy3dr-8000.csb.app/mf-va_remoteEntry.js:1304:42
./node_modules/lwz-component-with-umi/dist/index.js
https://tmy3dr-8000.csb.app/mf-dep____vendor.8fc77bc7.js:176238:69
__webpack_require__
https://tmy3dr-8000.csb.app/mf-va_remoteEntry.js:1304:42
./node_modules/.cache/mfsu/mf-va_lwz-component-with-umi.js
https://tmy3dr-8000.csb.app/mf-dep____vendor.8fc77bc7.js:9048:80
__webpack_require__
https://tmy3dr-8000.csb.app/mf-va_remoteEntry.js:1304:42
(anonymous function)
https://tmy3dr-8000.csb.app/mf-va_remoteEntry.js:583:105
__webpack_require__.m.<computed>
webpack:/umi4/webpack/runtime/remotes loading:2535
```

经测试关闭 mfsu，此错误消失。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://codesandbox.io/p/sandbox/polished-bash-tmy3dr?file=%2Fsrc%2Fpages%2FHome%2Findex.tsx)，并上传到你的 GitHub 仓库

https://github.com/liuwenzhuang/umi4-mfsu-error-package-with-umi

## How To Reproduce

1. 使用 max/umi4 生成的模板项目
2. 安装并使用包含 umi 引入的组件，如测试组件 lwz-component-with-umi
3. 启动服务，访问页面报错

## Context

- **Umi Version**: >4.0.0
- **Node Version**: 16
- **Platform**: 所有

**Comment by fz6m** [comment]
umi 导入是应用内才可以用的，不可以在第三方包内使用 umi 导入。

如果要跳路由，直接从 `react-router-dom` 里导入 `useLocation` 就可以了，umi 内置的路由就是 react router v6 。

另外可以从 props 传递下去对应的方法，如 history 等。

**Comment by 662** [comment]
把含业务逻辑的组件抽象到npm包，然后跨项目使用，这应该是常规场景。

但由于 @umijs/max 以及 plugins/request 的存在，外部包如果想要获得统一的请求逻辑，就不得不基于 umi 构建，引用来自 @umijs/max 的 request。

有什么办法可以在这样做的情况下开启mfsu吗。

**Comment by fz6m** [comment]
如前文所述，目前的设计是没法在第三方包里用 umi 导入的，所以你的第三方内容应该是纯的，不包含 umi 的内容，比如是一些使用 fetch / axios 请求接口的请求方法，或者是直接根据数据展示的组件。

另外 umi 里的 request 是为了兼容 umi 3 时代旧的而保留下来的，现代数据流已经不再推荐使用 umi request 和 dva ，而是使用 [react-query](https://tanstack.com/query/latest) 管理请求状态，使用 [jotai](https://github.com/pmndrs/jotai) / [valtio](https://github.com/pmndrs/valtio) 管理全局数据，这些方案和 umi 无关，只要 context 统一就可以复用。

**Comment by 662** [comment]
> 如前文所述，目前的设计是没法在第三方包里用 umi 导入的，所以你的第三方内容应该是纯的，不包含 umi 的内容，比如是一些使用 fetch / axios 请求接口的请求方法，或者是直接根据数据展示的组件。
> 
> 另外 umi 里的 request 是为了兼容 umi 3 时代旧的而保留下来的，现代数据流已经不再推荐使用 umi request 和 dva ，而是使用 [react-query](https://tanstack.com/query/latest) 管理请求状态，使用 [jotai](https://github.com/pmndrs/jotai) / [valtio](https://github.com/pmndrs/valtio) 管理全局数据，这些方案和 umi 无关，只要 context 统一就可以复用。

好的，我们也正在考虑迁移到基于 context provider 的垮项目组件。
