### ISSUE TITLE
如何独立跑插件本身的单测

### ISSUE THREAD

**Issue by ACERY1** [umijs/umi#1175]
试了一下

在本仓库的`/packages/umi-plugin-react`目录下运行 umi test，会报错。

报错原因：

net::ERR_CONNECTION_REFUSED at http://localhost:12352/

是需要先用umi dev 启动相应插件下的test目录下的测试页面吗？

**Comment by sorrycc** [comment]
可以加参数只跑指定的文件。

```bash
$ npm run debug *.test.js
```
