### ISSUE TITLE
部署在 ubuntu 22 上，访问后页面Bundling 卡

### ISSUE THREAD

**Issue by hanxiaolong-github** [umijs/umi#11758]
## What happens?

我在 ubuntu 22 上面部署了一个新的 umi max 项目，启动后发现页面 bunding 总是卡。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

因为是用的新项目，无法提供最小重现。 可以访问 http://54.176.58.165 来查看

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

1. 安装nvm：sudo apt install curl 
                      curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
                      source ~/.profile 
2. 安装node 16.0 nvm install 16.0
                              nvm use 16.0
3. 打开 80 端口: sudo apt install authbind
                            sudo touch /etc/authbind/byport/80
                            sudo chown root /etc/authbind/byport/80
                            sudo chmod 755 /etc/authbind/byport/80
4. 下载 umi max: mkdir app && cd app 
                             npx create-umi@latest
                             选择->antd prod->cnpm->taobao 
5. 修改 package.json 项目启动到 80 端口："dev": "PORT=80 max dev"
6. 启动项目 nohup authbind --deep npm run dev ,项目启动成功.

## Context

- **Umi Version: latest:
- **Node Version: 16.0:
- **Platform: ubuntu 22:

**Comment by hanxiaolong-github** [comment]
最后发现是ubuntu 配置太低了。

**Comment by fz6m** [comment]
你要用自己的服务器云开发吗，考虑用 vscode remote ssh 连接服务器开发吧（可以参考 [这篇](https://blog.csdn.net/qq_21567385/article/details/109349438) 文章，自己再搜索相关资料），vscode 会自动帮你做环境的配置和建立。
