### ISSUE TITLE
约定式路由，注释添加Route，如下情况失效

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#1176]
有效：在umi-examples\routes\layouts\index.js中设置
```js
/**
 * Routes:
 *   - ./routes/PrivateRoute.js
 */
```
无效：在umi-examples\routes\layouts\Breadcrumbs.js中同上设置无效
在umi-examples\routes\中可以重现

应用场景是在\layouts\index.js中根据pathname做布局区分，登录页面一个layout，其他页面一个layout
```js
 let { pathname } = location;
  pathname = pathname.startsWith("/") ? pathname : `/${pathname}`;
  if (openPages && openPages.includes(pathname)) {
    return <div style={{ height: "100%" }}>{children}</div>;
  }else{
    return <Breadcrumbs/>
 }
```

**Comment by sorrycc** [comment]
Breadcrumbs 不是路由组件，肯定无效啊。

**Comment by xiaohuoni** [comment]
不是路由组件无效这个我理解，我的意思是，现在存在这样的应用场景，我要怎么样解决这个问题？

**Comment by sorrycc** [comment]
Breadcrumbs 里用 `./routes/PrivateRoute.js` 包以下再渲染输出。
