### ISSUE TITLE
[Bug] @umijs/max与umi中均无createAxios、requestHandle方法？

### ISSUE THREAD

**Issue by zhilianbi520** [umijs/umi#11779]
## What happens?
`
import type { RequestConfig } from 'umi';
import { createAxios, requestHandle } from '@umijs/max';
`
## How To Reproduce
想在项目中自定义封装多个不同request请求，引入以上方法，提示均无该方法？

来源信息参考链接:https://github.com/umijs/umi/pull/11341
![14C134AD-923F-43CB-AC94-9EB8EE7064B8](https://github.com/umijs/umi/assets/16549630/dbb5b790-3869-426b-bfe4-8e95e6e2915c)

## Context
- **Umi Version**:4.0.52
- **Node Version**:16.13.0
- **Platform**:macOS

**Comment by fz6m** [comment]
`request` 有选项可以传入一些自定义的配置，比如添加统一的 header 等，你再封装一层就可以。

另外不推荐使用 request 、dva 了，这些是兼容旧 umi 3 保留的古老功能，现代数据流更推荐使用 [react-query](https://umijs.org/docs/max/react-query) 做请求状态管理，底层用自己编写的 axios / fetch ，用 [valtio](https://umijs.org/docs/max/valtio) / [jotai](https://github.com/pmndrs/jotai) 做全局数据流管理。
