### ISSUE TITLE
[Bug] 有新发版后，点击页面就会报：Refused to execute script from 'http://xxx.com/umi.2e2c80e0.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by NARUTOyuyang** [umijs/umi#11786]
## What happens?
Refused to execute script from 'http://xxx.com/umi.2e2c80e0.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

## Mini Showcase Repository(REQUIRED)
有新发版后，点击页面就会报：Refused to execute script from 'http://xxx.com/umi.2e2c80e0.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context
UMI: 3.5.0 

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4
