### ISSUE TITLE
[Bug] umi 4.0.83 局域网 无法访问本地 启动的项目

### ISSUE THREAD

**Issue by Donlei** [umijs/umi#11787]
umi 4.0.83在 局域网 无法访问本地 启动的项目，老版本的3.5.20 可以在局域网访问本地启动的项目
![1698119366910](https://github.com/umijs/umi/assets/24711571/d61a046c-f69c-499a-aac6-a6c936b52d99)

- **Umi Version**:4.0.83
- **Node Version**:18.17.1
- **Platform**: windows 11

**Comment by fz6m** [comment]
要公开到局域网上，配置 host 后启动 `HOST=0.0.0.0 umi dev` 。

**Comment by Donlei** [comment]
> 要公开到局域网上，配置 host 后启动 `HOST=0.0.0.0 umi dev` 。

请问 在windows  系统  host  文件中 配置 ？
![1698657326321](https://github.com/umijs/umi/assets/24711571/e5c83ed2-499c-4ca8-a92d-1f23832446d4)
@fz6m

**Comment by fz6m** [comment]
如果是 windows ，使用如下方式启动项目暴露到本地局域网上即可：

```bash
  pnpm add -D cross-env
```

```ts
// package.json
  "scripts": {
     // or cross-env HOST=0.0.0.0 max dev
    "dev": "cross-env HOST=0.0.0.0 umi dev"
  }
```

**Comment by Donlei** [comment]
> 如果是 windows ，使用如下方式启动项目暴露到本地局域网上即可：
> 
> ```shell
>   pnpm add -D cross-env
> ```
> 
> ```ts
> // package.json
>   "scripts": {
>      // or cross-env HOST=0.0.0.0 max dev
>     "dev": "cross-env HOST=0.0.0.0 umi dev"
>   }
> ```
"dev": "cross-env HOST=0.0.0.0 umi dev" 无法启动 ，'umi' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
cross-env HOST=0.0.0.0 max dev能正常启动 ，但是 局域网 还是无法 访问 ，请问 还有 其他地方 需要 配置 ？
![1698718748897](https://github.com/umijs/umi/assets/24711571/5715ea1a-9549-47d2-8e85-28109673ff41)
@fz6m

**Comment by fz6m** [comment]
如果配置了 `HOST` 之后还是不能局域网访问，就要排查下自己的局域网和设备问题了，比如是否有代理影响，局域网 IP 是否访问正确，访问者是否真的和本机在一个局域网环境等。

**Comment by Donlei** [comment]
> 如果配置了 `HOST` 之后还是不能局域网访问，就要排查下自己的局域网和设备问题了，比如是否有代理影响，局域网 IP 是否访问正确，访问者是否真的和本机在一个局域网环境等。

同样的环境，umi3.5.20却能 正常访问。没有代理影响、IP也是对的，处于同一个 局域网环境，频段也一样的，但是 4.0.83就是 不能访问。
@fz6m

**Comment by fz6m** [comment]
如有问题，需要给一个最小复现，或者完整的复现视频。

可以尝试换一台机子和一个网络环境试试，因为这个功能是正常的，需要自己排查下自己环境的问题，如果认为是源码有 edge case ，欢迎 debug 找到后 PR 。
