### ISSUE TITLE
2.1.1以下几个问题

### ISSUE THREAD

**Issue by niaoge** [umijs/umi#1178]
今天把项目从umi1.3升级到2.1.1，暂时发现以下几个问题
1.typescipt中，src/pages/role/index.tsx,src/pages/role/model.ts有代码错误，编译没通过，但是错误提示中没有带文件路径，只是 index.tsx,model.ts错误,在umi中，pages下面都是index.model，因此无法定位错误文件，需要把项目里的所有的index.tsx和model.ts都打开查找，很不方便
2.生产环境中
  a.index.html中 .<script src="staticumi.js"> 应该是 ./static/umixxxxx.js, 无论我设置 publicPath: 'static',或 publicPath: 'static/',都生成staticumi.js
  b.dll没起作用。不知道是不是我没有配置成功的原因，只生成了一个umi.js,有5M多,这个在生产环境中无法接受，以前1.3中的 umi.xxxx.js,page_xxx.index.js不见了，我下载 https://github.com/zuiidea/antd-admin ,这个项目sorrycc也参与了，但是编译生产环境也是只有umi.js，也是5M多.
  c.plugins中的 modifyHTMLScript 不见了，我查了下源代码，现在改为 modifyHTML ,但是我配置后也没起到效果，不知道有没有2.0的sample？

**Comment by sorrycc** [comment]
1. 我查下原因
2.a 看你的配置应该是要部署到任意路径？参考 https://umijs.org/zh/guide/deploy.html#html-%E5%90%8E%E7%BC%80
2.b dll 只在 dev 时有效，umi@1 也是如此
2.c https://umijs.org/zh/plugin/develop.html 这里搜 addHTML 前缀和 modifyHTML 前缀的关键字，也可以在源码里搜相关的，插件里都有用到的

**Comment by sorrycc** [comment]
有问题再 reopen 。
