### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by RiseToTop** [umijs/umi#11796]
请教下，我使用了umi4的代理功能，代理了后端服务的接口，但后端服务关闭后，会导致整个网站打不开，把代理关掉就好了，有什么解决办法吗

**Comment by fz6m** [comment]
数据加载不了应用挂了，需要确保数据一定有，如果接口挂了没法调试，可以在本地把接口响应成 mock 数据，但是你要准备一套假数据用来调试，正常情况下应该确保后端 api 在 开发 or 测试环境 都是可用的，实在不行再走 mock 平台或者本地 mock 数据。
