### ISSUE TITLE
umi4，老项目升级如何在src/layout/index.tsx文件中获取到路由配置

### ISSUE THREAD

**Issue by tanshenghu** [umijs/umi#11790]
umi4，老项目升级如何在src/layout/index.tsx文件中获取到路由配置数据
以前umi3会有props的，里面包含路由数据，如今所有组件都没有了props数据，请问，layout怎么处理，难道只能在app.tsx里用插件配置的形式吗？如果我想关闭这种插件配置的形式，走老的src/layout/index.tsx这种方式是不是只能自己单独import并处理路由数据？
还有目前app.tsx配置layout的形式优先级非常高，与自己写src/layout/index.tsx的这种方式不互斥，有两个layout，不过这个没什么关系自己可以取舍，最大问题就是假如我不想用配置的形式去设置layout，如何获取到路由数据？

**Comment by fz6m** [comment]
### 路由信息

umi 4 用的是 [react-router v6](https://reactrouter.com/en/main) ，获取路由的方式和 react router v6 一样，比如 `useLocation` / `useNavigate` ，可以做到路由的常规操作和信息获取，但只能在 hooks 内使用。

另外 umi 还提供了全局 `history` 可以直接导入使用：

```ts
import {  history } from 'umi'
``` 

需要注意的是，当配置了 `base` 后全局 history 的路径信息与应用内 react-router 的方法获取的稍有不同。

### class component

对于 class 组件，可以自己写一个函数调用 `useLocation` 等获取到路由信息再通过 props 传递下去变成 HOC ，就可以兼容了。

### 兼容模式

除此之外，你还可以开启 [`reactRouter5Compat: {}`](https://umijs.org/docs/api/config#reactrouter5compat) 来恢复一些以前的行为，让升级迁移更容易：

```ts
// .umirc.ts
  reactRouter5Compat: {},
  historyWithQuery: {}
```

### 嵌套路由

在 react router v6 中嵌套路由出口需要使用 `<Outlet />` 来展示，不再是 `props.children` 。
