### ISSUE TITLE
[Bug] qiankun mf 同时使用时报错

### ISSUE THREAD

**Issue by csic21** [umijs/umi#11797]
## What happens?

qiankun + mf + 普通webpack项目打包出的模块联邦使用起来会报错，主应用或者子应用单独使用时打包到生产环境都没有问题，报错信息如下
Uncaught (in promise) Error: Container initialization failed as it has already been initialized with a different share scope
    at Object.i (remoteEntry.js:2:1534620)
    at He (umi.js:578:1074)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 1)
![image](https://github.com/umijs/umi/assets/99160430/099d5778-4fcb-4921-a7c4-71eec05114ec)

## Mini Showcase Repository(REQUIRED)

可提供步骤如下

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

任意一个webpack库配置如下
```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const { ModuleFederationPlugin } = require('webpack').container;
const deps = require('./package.json').dependencies;

const federationConfig = {
  name: 'opsc',
  filename: 'remoteEntry.js',
  exposes: {
    './XXX': './src/components/XXX',
  },
  shared: {
    react: { singleton: true, eager: true, requiredVersion: '18.2.0' },
    'react-dom': { singleton: true, eager: true, requiredVersion: '18.2.0' },
    antd: { singleton: true, eager: true, requiredVersion: '5.10.2'},
  }
};

module.exports = {
  resolve: {
    extensions: ['.js', '.jsx', '.ts', '.tsx'],
  },

  entry: './src/index.js',
  output: {
    publicPath: 'http://localhost:8001/remote/',
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },
  mode: 'production',
  module: {
    rules: [
      {
        test: /\.(js|mjs|jsx|ts|tsx)$/,
        include: path.resolve('./src'),
        loader: 'esbuild-loader',
        options: {
          loader: 'tsx',
        },
      },
    ],
  },
  plugins: [
    // ...
    new ModuleFederationPlugin({
      ...federationConfig,
    }),
    new HtmlWebpackPlugin({
      template: './src/index.html',
    }),
  ],
};
```
umi 主应用
```
{
...
  qiankun: { master: {} },
  mfsu: false,
  mf: {
    remotes: [
      {
        name: 'opsc',
        entry: 'http://localhost:8001/remote/remoteEntry.js',
      },
    ],
    shared: {
      react: { singleton: true, eager: true, requiredVersion: '18.2.0' },
      'react-dom': { singleton: true, eager: true, requiredVersion: '18.2.0' },
      antd: { singleton: true, eager: true, requiredVersion: '5.10.2' },
    },
  },
...
}
```
umi 子应用
```
  qiankun: {
    slave: {},
  },
  mfsu: false,
  mf: {
    remotes: [
      {
        name: 'opsc',
        entry: 'http://localhost:8001/remote/remoteEntry.js',
      },
    ],
    shared: {
      react: { singleton: true, eager: true, requiredVersion: '18.2.0' },
      'react-dom': { singleton: true, eager: true, requiredVersion: '18.2.0' },
      antd: { singleton: true, eager: true, requiredVersion: '5.10.2' },
    },
  },
```
按以上配置后，能够成功访问主应用并调用模块联邦，子应用也可以。但是主应用引入子应用时，就会出现图上报错
## Context

- **Umi Version**:     "@umijs/max": "^4.0.86",
- **Node Version**:  16
- **Platform**: linux

**Comment by fz6m** [comment]
现在模块联邦有一个内置的实验性功能 [`mf: {}`](https://umijs.org/docs/max/mf) 可以一键开启，在 [`examples/mf-host`](https://github.com/umijs/umi/tree/master/examples/mf-host) 、 [`examples/mf-remote`](https://github.com/umijs/umi/tree/master/examples/mf-remote) 有例子可以参考，里面也是开启了 qiankun 的。

这个内置的 mf 功能做了不少处理，如果你需要 MF 功能最好用这个内置的，如果非要自己配，读一下这个功能的 [源码](https://github.com/umijs/umi/blob/master/packages/plugins/src/mf.ts) 然后参考着改吧。

**Comment by csic21** [comment]
@fz6m 一样的问题，有两个host的时候就会出现问题，主应用和子应用消费mf,单独访问都是没问题的
![image](https://github.com/umijs/umi/assets/99160430/b2d1ce32-2bad-4628-a1b9-8d8ec02970ae)

**Comment by csic21** [comment]
@fz6m 看了一下产物umijs这里init多次，有办法解决吗
![image](https://github.com/umijs/umi/assets/99160430/dc95907b-57d2-49dd-876d-81965549e78c)

**Comment by fz6m** [comment]
如有问题，需要提供一个最小复现。

**Comment by xuebigshuai** [comment]
这个很好复现的，子应用通过模块联邦使用其他公共模块，自又通过模块联邦暴露模块给基座应用使用。基座中使用子应用暴露的模块，然后再加载子应用，同时配置shared功能，就会出现上面的报错。是因为模块联邦默认的init 方法，会判断贡献的资源是否来自同一出处。不相同就throw error 了。

**Comment by xuebigshuai** [comment]
> @fz6m 看了一下产物umijs这里init多次，有办法解决吗 ![image](https://user-images.githubusercontent.com/99160430/278199190-dc95907b-57d2-49dd-876d-81965549e78c.png)



> @fz6m 一样的问题，有两个host的时候就会出现问题，主应用和子应用消费mf,单独访问都是没问题的 ![image](https://user-images.githubusercontent.com/99160430/278189378-b2d1ce32-2bad-4628-a1b9-8d8ec02970ae.png)

问下，你这个问题解决了没？ 我目前不是通过shared共享依赖，是直接通过window共享，很恶心的一种方式

**Comment by fz6m** [comment]
如有问题，需要给一个最小复现。

另外模块联邦作者在近期会进行彻底的重构新版本发布，以前的 mf 将很难得到生命周期保障，请酌情使用。

**Comment by csic21** [comment]
> > @fz6m 看了一下产物umijs这里init多次，有办法解决吗 ![image](https://user-images.githubusercontent.com/99160430/278199190-dc95907b-57d2-49dd-876d-81965549e78c.png)
> 
> > @fz6m 一样的问题，有两个host的时候就会出现问题，主应用和子应用消费mf,单独访问都是没问题的 ![image](https://user-images.githubusercontent.com/99160430/278189378-b2d1ce32-2bad-4628-a1b9-8d8ec02970ae.png)
> 
> 问下，你这个问题解决了没？ 我目前不是通过shared共享依赖，是直接通过window共享，很恶心的一种方式

通过业务解决了，主应用只充当基座，不消费模块联邦，只使用子应用消费。

**Comment by xuebigshuai** [comment]
> > > @fz6m 看了一下产物umijs这里init多次，有办法解决吗 ![image](https://user-images.githubusercontent.com/99160430/278199190-dc95907b-57d2-49dd-876d-81965549e78c.png)
> > 
> > 
> > > @fz6m 一样的问题，有两个host的时候就会出现问题，主应用和子应用消费mf,单独访问都是没问题的 ![image](https://user-images.githubusercontent.com/99160430/278189378-b2d1ce32-2bad-4628-a1b9-8d8ec02970ae.png)
> > 
> > 
> > 问下，你这个问题解决了没？ 我目前不是通过shared共享依赖，是直接通过window共享，很恶心的一种方式
> 
> 通过业务解决了，主应用只充当基座，不消费模块联邦，只使用子应用消费。

我今天也想着只要子应用通过模块联邦使用公共的，基座就不用了，但我们的业务不支持，基座必须要用子应用提供的模块。

**Comment by xuebigshuai** [comment]
> 如有问题，需要给一个最小复现。
> 
> 另外模块联邦作者在近期会进行彻底的重构新版本发布，以前的 mf 将很难得到生命周期保障，请酌情使用。

这在模块联邦嵌套使用的时候就会复现，在qiankun的issue里面也有这个提问[qiankun_MF](https://github.com/umijs/qiankun/issues/2105)

**Comment by fbixiaoyu** [comment]
请问解决了吗，我也出现了，本地serve就会出现，把mf关掉，主应用就会一直重复请求刷新页面

**Comment by fz6m** [comment]
mf v1 版本已经过时了，可以看看 qiankun 和 mf v2 版本一起用是否还存在此问题（目前 umi 4 还不支持直接使用 mf v2 ，请在其他框架内尝试）。

**Comment by fbixiaoyu** [comment]
> mf v1 版本已经过时了，可以看看 qiankun 和 mf v2 版本一起用是否还存在此问题（目前 umi 4 还不支持直接使用 mf v2 ，请在其他框架内尝试）。

子应用vue2 webpack4，未开启mf。

**Comment by fbixiaoyu** [comment]
> mf v1 版本已经过时了，可以看看 qiankun 和 mf v2 版本一起用是否还存在此问题（目前 umi 4 还不支持直接使用 mf v2 ，请在其他框架内尝试）。

子应用vue2 webpack4，未开启mf。

主应用umi4/max，默认开启的mfsu会导致共享联邦报错，定位是多次init，oldscope不等于sharescore，抛错。
关闭mfsu之后，主应用不停请求文件，刷新页面。

**Comment by fz6m** [comment]
没能复现你说的问题，以下是我的操作步骤：

1. 我使用非 umi 脚手架新建了一个 react 的应用（webpack 打包，这里用 vue 还是 react 都是一样的，只要是非 umi 即可），并参考 qiankun 官方文档，修改了项目入口和导出的生命周期函数，修改了 webpack 打包配置。

2. 新建了一个 umi 4 max 主应用，打开 `qiankun: { master: {} }` ，打开 `mf: {}` 。

3. 新建一个加载子应用的页面：

    ```ts
    import React, { useRef, useEffect } from 'react';
    import { loadMicroApp } from 'qiankun';
    export default function ManualSlavePage() {
      const divRef = useRef<HTMLDivElement>(null);
    
      useEffect(() => {
        console.log(loadMicroApp);
    
        const app = loadMicroApp({
          name: 'slave',
          container: divRef.current!,
          entry: 'http://127.0.0.1:9527',
        });
    
        app?.update?.({});
    
        console.log(app);
    
        return () => {
          app.unmount();
        };
      }, []);
    
      return <div ref={divRef}></div>;
    }
    ```


4. 子应用是正常加载显示的，没有报错。

**Comment by csic21** [comment]
最近通过使用kmi解决该问题，现在已经支持基座和子应用同时使用远程模块，umi4这块内容肯定是有问题
