### ISSUE TITLE
dynamicRoot: true 时在 windows 下前置路径为 undefined

### ISSUE THREAD

**Issue by clown-helang** [umijs/umi#1179]
umirc中添加 exportStatic 配置ie兼容就出现问题了
![image](https://user-images.githubusercontent.com/20653395/46252285-8b3ef700-c499-11e8-9004-58cee8ecab07.png)
![image](https://user-images.githubusercontent.com/20653395/46252296-ad387980-c499-11e8-8455-893a5f6cdc38.png)
![image](https://user-images.githubusercontent.com/20653395/46252304-baedff00-c499-11e8-83b4-c685a91a9763.png)

去掉配置即可正常兼容
![image](https://user-images.githubusercontent.com/20653395/46252313-d0632900-c499-11e8-8049-1654b113d6cc.png)

**Comment by yutingzhao1991** [comment]
看上去是 `requestAnimationFrame` 不支持导致的。

可以配置 targets 来添加  ie9 的 polyfills

```js
export default {
  targets: {
    ie: 9,
  }
}
```

@sorrycc 动态加载有依赖 requestAnimationFrame 这个？

**Comment by xiaohuoni** [comment]
@yutingzhao1991 看他配置应该是已经添加了target

**Comment by clown-helang** [comment]
添加了targets配置，上面截图配置中有，很好复现。

**Comment by sorrycc** [comment]
`requestAnimationFrame` 不属于语言特性，不在 `@babel/polyfill` 的处理范围之内，先在 `global.js` 里手动引入 `raf/polyfill` 解决吧。

**Comment by clown-helang** [comment]
问题似乎并不只是 requestAnimationFrame 造成的。设置 htmlSuffix 和 dynamicRoot 为 true，在ie10及以下 script 和 link 的引用地址都变了
![image](https://user-images.githubusercontent.com/20653395/46986457-1b2fa280-d122-11e8-8144-4a3c7d6c07d4.png)
可以看到都变成了 undefined/ .... 请问这是怎么回事儿。
我也添加了global.js且引入了 raf/polyfill 
![image](https://user-images.githubusercontent.com/20653395/46986526-7a8db280-d122-11e8-8e0b-f44c94f5bcb6.png)
下面是我的 umirc 配置
![image](https://user-images.githubusercontent.com/20653395/46986569-b294f580-d122-11e8-9130-7580080d3ece.png)
@sorrycc
