### ISSUE TITLE
[Bug] overrides.less 相对路径加载错误

### ISSUE THREAD

**Issue by fz6m** [umijs/umi#11800]
### 来源

Discussed in https://github.com/umijs/umi/discussions/11795

<div type='discussions-op-text'>

<sup>Originally posted by **skyblue** October 25, 2023</sup>
@umijs/max 从4.0.86升级到4.0.87 后
overrides.less里使用的
`background-image: url('assets/bg.png');`
报错
`Module not found: Error: Can't resolve 'assets/bg.png' in '/src/.umi/core'`
</div>

### ~~补充问题（已解决）~~

~~当 `overrides.less` 书写等效于空的样式时，会因无法生成而报错，如：~~

```css
body {}
```

**Comment by sorrycc** [comment]
新增一例：

overrides.css 里 `@import './index.less'`，会报错。
