### ISSUE TITLE
[Bug] 默认打包产物依然包含momentjs，文档缺失moment2dayjs

### ISSUE THREAD

**Issue by csic21** [umijs/umi#11807]
## What happens?

![image](https://github.com/umijs/umi/assets/99160430/669997e1-e476-4597-a93e-4fe75fe7ef00)
之前文档有moment2dayjs https://umijs.org/docs/max/moment2dayjs
现在访问是404，但api是可以正常使用，想问一下是否以后会取消，为什么删除了呢
## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

打包时添加ANALYZE=1查看产物

## Context

- **Umi Version**:  "@umijs/max": "^4.0.87",
- **Node Version**: 14
- **Platform**: linux

**Comment by fz6m** [comment]
这是一个黑盒操作，不够清真，更推荐迁移到纯净的单一方案，而不使用隐性的兼容。
