### ISSUE TITLE
找不到模块“@umijs/max”。你的意思是要将 "moduleResolution" 选项设置为 "node"，还是要将别名添加到 "paths" 选项中?

### ISSUE THREAD

**Issue by pingguoping** [umijs/umi#11802]
找不到模块“@umijs/max”。你的意思是要将 "moduleResolution" 选项设置为 "node"，还是要将别名添加到 "paths" 选项中?

**Comment by fz6m** [comment]
确保 `tsconfig.json` 是正确的情况下，运行 `pnpm max setup` 生成临时文件后就可以修复初始缺失类型的问题。

如还有问题，需要给一个最小复现。

**Comment by heaven-hub** [comment]
其实就是vs code的版本过低，内置的ts识别错误，更新一下vs code就行
