### ISSUE TITLE
[Bug] 菜单上的icon，突然不显示了？

### ISSUE THREAD

**Issue by zhangxinyong12** [umijs/umi#11809]
<img width="298" alt="1d012876308af6bbf58663871d90013" src="https://github.com/umijs/umi/assets/29941627/ce758b27-833f-4749-bfbd-588f71eb588c">
<img width="537" alt="0939b8d3623af9eac04139a713fd94b" src="https://github.com/umijs/umi/assets/29941627/35b7c21b-178a-46ff-b4be-2866dee60fed">

**Comment by zhangxinyong12** [comment]
哦、我找到了。之前项目再app.tsx 使用了动态menu

**Comment by astfn** [comment]
> 哦、我找到了。之前项目再app.tsx 使用了动态menu

动态路由如何使icon正确展示呢？

**Comment by fz6m** [comment]
在动态路由的 patch 时，手动将 icon 的图标 react 组件添加到路由表内，可参考 layout 插件的 `./src/.umi/plugin-layout/runtime.tsx` 内 `patchRoutes` 部分的逻辑，就是将文本 icon 字符串转为 react element 的过程。

或者尝试在菜单的 label 文本上添加 icon 。
