### ISSUE TITLE
[Feature Request] 有没有办法修改插件顺序在内置插件之前

### ISSUE THREAD

**Issue by csic21** [umijs/umi#11813]
## Background

在使用微前端子应用时，想要动态给父应用传递菜单且带有国际化翻译，但如果手动修改runtime里面的rootContainer则没办法获取国际化的provider，如果在layout做，当路由带上了base或没有匹配到的时候也不能提前获取菜单，根本走不到这个layout里边。有没有办法让自己写的插件运行在内置插件前面呢。

## Proposal

想要在内置插件之前插入rootContainer，比如在LocaleProvider之前就插入自己的Provider，这样可以获取到LocaleProvider的context

**Comment by fz6m** [comment]
默认 `locale: {}` 这个 i18n 插件会把 provider 插到 `i18nProvider` 这个层级里，如果想要获取这个 provider 的信息，把自己的东西插到更低级别的 `innerProvider` 即可：

```ts
// app.tsx

export const innerProvider = (children) => {
  return <SelfProvider>{children}</SelfProvider>
}
```

如还有问题，需要给一个最小复现。

**Comment by fanjiawei** [comment]
> 默认 `locale: {}` 这个 i18n 插件会把 provider 插到 `i18nProvider` 这个层级里，如果想要获取这个 provider 的信息，把自己的东西插到更低级别的 `innerProvider` 即可：
> 
> // app.tsx
> 
> export const innerProvider = (children) => {
>   return <SelfProvider>{children}</SelfProvider>
> }
> 如还有问题，需要给一个最小复现。

为啥文档里搜不到这个属性呢
