### ISSUE TITLE
[Bug] 在umijs中无法通过Reflect.getMetadata获取到design:type的值

### ISSUE THREAD

**Issue by superchenwb** [umijs/umi#11815]
## 在umijs中无法通过Reflect.getMetadata获取到design:type的值

>  [最小重现](https://github.com/superchenwb/umi-bug)

```typescript
import "reflect-metadata";

function Prop() {
  return function (target: object, propertyKey: any) {
    const type = Reflect.getMetadata("design:type", target, propertyKey);
    console.log("--type", type);
  };
}

class User {
  @Prop()
  id: string = "";

  @Prop()
  age: number = 0;
}
```

demo很简单，打印的type是undefined。

查找过其他的issue [支持将处理ts|tsx的loader变更为ts-loader，ts-loader支持getCustomTransformers，通过该方法，可以在umi中使用@deepkit/type #9425](https://github.com/umijs/umi/issues/9425)

尝试通过chainWebpack设置ts-loader，也会报错
```typescript
  chainWebpack(config) {
    config.module
      .rule("jsx-ts-tsx")
      .use("ts-loader")
      .loader(require.resolve("ts-loader"))
      .after("babel-loader")
      .options({
        getCustomTransformers: () => ({
          before: [
            require("react-refresh-typescript")(),
            // typeCompiler.transformer,
          ],
          // afterDeclarations: [typeCompiler.declarationTransformer],
        }),
        configFile: join(__dirname, "./tsconfig.json"),
      });
  }
```
错误如下：
`error - ./src/.umi/umi.ts
Module build failed (from ./node_modules/.pnpm/registry.npmjs.org+ts-loader@9.5.0_typescript@5.2.2/node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for D:\gant-codespace\umi-bug\src\.umi\umi.ts.
    at makeSourceMapAndFinish (D:\gant-codespace\umi-bug\node_modules\.pnpm\registry.npmjs.org+ts-loader@9.5.0_typescript@5.2.2\node_modules\ts-loader\dist\index.js:55:18)
    at successLoader (D:\gant-codespace\umi-bug\node_modules\.pnpm\registry.npmjs.org+ts-loader@9.5.0_typescript@5.2.2\node_modules\ts-loader\dist\index.js:42:5)
    at Object.loader (D:\gant-codespace\umi-bug\node_modules\.pnpm\registry.npmjs.org+ts-loader@9.5.0_typescript@5.2.2\node_modules\ts-loader\dist\index.js:23:5)`

**Comment by fz6m** [comment]
这是 babel 的一个已知问题吧，试试 [babel-plugin-transform-typescript-metadata](https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata) 这个插件，我用了下可以获取到：

```ts
// .umirc.ts

  extraBabelPlugins: [
    'babel-plugin-transform-typescript-metadata'
  ]
```

**Comment by superchenwb** [comment]
太感谢了，感谢大佬。我查了好几天的资料了，都没找到法子。我大致知道用应该是使用babel编译的时候，少了一些东西，就是不知道design:type到底从哪来的
