### ISSUE TITLE
[BUG] Sequence Expression in umi3 cause error.

### ISSUE THREAD

**Issue by Mistrain-y-y** [umijs/umi#11819]
Recently, I'm using babel-plugin-istanbul, which will generate code with Sequence Expression (Comma Operator). And encountered a problem (I simplify it):

```ts
import {Form} from 'antd';

let a = 1;
const b = (a++, Form);// use Comma Operator
```

I think `Form` should be like these:
<img width="381" alt="image" src="https://github.com/umijs/umi/assets/72647648/ff562b18-5da7-43d5-89b2-395e1c6865b3">

But I get these code:
<img width="687" alt="image" src="https://github.com/umijs/umi/assets/72647648/5fa9306c-7631-4635-a472-21d4d80fc9b1">

Error:
![image](https://github.com/umijs/umi/assets/72647648/3a84ee0c-5a0a-468d-b24b-a053a377f1ca)

I found the same issue in babel-plugin-import, but I don't know how to fix it when I use umi3. I use umi@3.5.41.
[feat: conditional expression supports comma operator #593](https://github.com/umijs/babel-plugin-import/pull/593)

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4 。

**Comment by Mistrain-y-y** [comment]
But is there any solution for this problem?
