### ISSUE TITLE
如何跟tauri 进行集成？

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [umijs/umi#11822]
## Background

如何跟tauri 进行集成？
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by fz6m** [comment]
社区里有一些有志人士提供了一些模板，比如 https://github.com/xiefengnian/umijs-electron-plugin ，还可以在 github 搜 `umi electron` 关键词找一找综合看一下，参考类似的方式看看什么方式能与 tauri 集成。

**Comment by liuhuapiaoyuan** [comment]
嗯，就当普通项目集成就好了
