### ISSUE TITLE
cached files not invalidating

### ISSUE THREAD

**Issue by madisvain** [umijs/umi#1182]
The filenames do not have any hashing and after a new deployed build the files are not updated for users without disabling browser cache.

I'm using PWA but service-worker with precache-manifest is not even loaded by the brower. The current build can be found here: https://www.requestbin.app/

```javascript
// ref: https://umijs.org/config/
export default {
  plugins: [
    // ref: https://umijs.org/plugin/umi-plugin-react.html
    ['umi-plugin-react', {
      antd: true,
      dva: true,
      dynamicImport: true,
      title: 'Requestbin app - Collect, inspect & debug HTTP requests',
      dll: true,
      pwa: true,
      routes: {
        exclude: [],
      },
      hardSource: true,
    }],
  ],
  proxy: {
    "/api": {
      target: "http://localhost:5000",
      changeOrigin: true
    }
  }
}
```

**Comment by xiaohuoni** [comment]
Whether to enable the hash file suffix. https://umijs.org/config/#hash

**Comment by madisvain** [comment]
@xiaohuoni thank you and sorry I completely missed this boolean in the documentation. This is exactly what I was looking for.
