### ISSUE TITLE
Umi好像并没有内置valtio

### ISSUE THREAD

**Issue by jockiech** [umijs/umi#11825]
![WeChat8d360671ce8db68b8008528c164fca90](https://github.com/umijs/umi/assets/38551182/15fc20f5-ffe1-42bc-a5c5-df7f4a82310a)
如图，umi好像并没有如文档所说内置valtio

**Comment by fz6m** [comment]
根据 [umi valtio](https://umijs.org/docs/max/valtio) 这个文档说明，只有 max 内置了，普通 umi 项目要用的话，得额外安装：

```bash
  pnpm add -D @umijs/plugins
```

```ts
// .umirc.ts

  plugins: ['@umijs/plugins/dist/valtio'],
  valtio: {}
```

另外可以直接安装 `valtio` 库本身来直接用，目前 umi 的 valtio 也只是重新导出了 valtio 的方法。
