### ISSUE TITLE
[Bug] 根据官网配置自定义头，无效

### ISSUE THREAD

**Issue by haochenhh** [umijs/umi#11830]
根据官网配置自定义头，无效，配置在app.ts文件中，版本是4.x

![image](https://github.com/umijs/umi/assets/22142365/ef29a50e-60e0-4dec-a4eb-ab707770a949)

**Comment by fz6m** [comment]
jsx 必须书写在以 `x` 为结尾的文件中，此处需要修改为 `app.tsx`
