### ISSUE TITLE
[Bug] umi使用ProLayout组件，获取不到路由信息

### ISSUE THREAD

**Issue by YH-82** [umijs/umi#11849]
## What happens?

在最新的umi框架中，使用ant-design/components的ProLayout组件，在组件中获取不到路由信息

## Mini Showcase Repository(REQUIRED)

复现代码：https://github.com/YH-82/umi4-ProLayout-

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
启动项目，然后进入到这个页面
![image](https://github.com/umijs/umi/assets/81352993/3adbd1a7-3e44-48bc-b630-5c3b42c662b3)
可以看到左侧菜单是空的
<img width="1365" alt="image" src="https://github.com/umijs/umi/assets/81352993/6587dda5-608f-42cf-a1bf-ddbbec9e41f7">

由上图可以看到，ProLayout 其实是读取的 props 中的 route 和 location。这两个属性是 umi 默认注入的。

但是实际上拿不到route和location

Layout/index.tsx
```
import { Outlet } from "@umijs/max"
import { ProLayout } from "@ant-design/pro-components";

export default function Layout(props) {
    console.log(props);
   // 在这里打印的props是{}
    return (
        <ProLayout
            menuDataRender={menuList => {
                // 在这里打印的menuList是[]，但是这里不应该是对应路由的子路由列表吗，或者路由的列表应该怎么获取呢
                console.log('menuList', menuList);
                return []
            }}
        >
            <Outlet />
        </ProLayout>

    )
}
```
.umirc.ts
```
import { defineConfig } from '@umijs/max';

export default defineConfig({
  antd: {},
  access: {},
  model: {},
  initialState: {},
  request: {},
  routes: [
    {
      path: '/',
      redirect: '/home',
    },
    {
      name: '首页',
      path: '/home',
      component: './Home',
    },
    {
      name: '测试',
      path: '/',
      component: './Layout',
      routes: [
        {
          name: '权限演示',
          path: '/access',
          component: './Access',
        },
        {
          name: ' CRUD 示例',
          path: '/table',
          component: './Table',
        },
      ]
    },


  ],
  npmClient: 'pnpm',
});

```

**Expected behavior** 1. 2.
期望的结果是，左侧可以显示菜单项「权限演示」和「CRUD 示例」，如下图
![image](https://github.com/umijs/umi/assets/81352993/44865cc6-8e31-4e2b-8904-c189f53aad1b)

## Context

- **Umi Version**:
- "@umijs/max": "^4.0.87",
- **Node Version**:
- v16.20.1
- **Platform**:
macOS

**Comment by fz6m** [comment]
umi 框架能获取到路由信息，这些信息要经过一些处理才能形成菜单，和菜单联动，这些功能内置在 `layout: {}` 这个插件里了：

```ts
// .umirc.ts

  layout: {}
```

打开这个选项就会自动使用 pro layout 创建 layout 和菜单。

如果要自己全面定义 layout ，则可以参考 `src/.umi/plugin-layout` 里面的实现自己 copy 选取需要的。

**Comment by YH-82** [comment]
> umi 框架能获取到路由信息，这些信息要经过一些处理才能形成菜单，和菜单联动，这些功能内置在 `layout: {}` 这个插件里了：
> 
> ```ts
> // .umirc.ts
> 
>   layout: {}
> ```
> 
> 打开这个选项就会自动使用 pro layout 创建 layout 和菜单。
> 
> 如果要自己全面定义 layout ，则可以参考 `src/.umi/plugin-layout` 里面的实现自己 copy 选取需要的。

感谢回复！还有个问题请教一下，按照以上demo那样去实现自定义layout，图标无法正常显示出来，是否只能通过menuRender来自定义菜单了呢？
```
import { defineConfig } from '@umijs/max';

export default defineConfig({
  antd: {},
  access: {},
  model: {},
  initialState: {},
  request: {},
  routes: [
    {
      path: '/',
      redirect: '/home',
    },
    {
      name: '首页',
      path: '/home',
      component: './Home',
    },
    {
      name: '测试',
      path: '/',
      component: './Layout',
      layoutName: 'BasicLayout',
      routes: [
        {
          name: '权限演示',
          path: '/access',
          // ！！！！在这里添加了图标
          icon: 'Home',
          component: './Access',
        },
        {
          name: ' CRUD 示例',
          path: '/table',
          component: './Table',
        },
      ]
    },


  ],
  npmClient: 'pnpm',
});
```
图标无法正常显示，而是显示成了文字，请问这里应该怎么做的呢？期待您的回复
![image](https://github.com/umijs/umi/assets/81352993/7607fec8-0c4b-478b-8cf1-c63e651a7fe5)

**Comment by fz6m** [comment]
图标使用 `icon: 'xxx'` 进行配置，支持 antd icons ，可参考 [ant-design-pro](https://github.com/ant-design/ant-design-pro/blob/master/config/routes.ts) 的路由表。
