### ISSUE TITLE
[Bug] windows启用vite后无法正常启动项目 

### ISSUE THREAD

**Issue by Lemonade1172** [umijs/umi#11847]
## What happens?

启用 vite 模式后，启动项目后报错
控制台 Uncaught SyntaxError: The requested module '/node_modules/invariant/browser.js?v=9e0587bb' does not provide an export named 'default'

## Mini Showcase Repository(REQUIRED)

[repo](https://github.com/urielvan/umi-vite-jsx)

## How To Reproduce

执行 npm start  #之后在浏览器中打开，无法正常显示页面

## Expected behavior
和使用 webpack 时一样可以正常打开页面

## Context
Umi Version: 4.0.74
Node Version: 18.9.0
Platform: win10

问题同[#10212](https://github.com/umijs/umi/issues/10212#issue-1520140831)，但已升级到后续一个解决Windows问题的版本，问题依然存在

**Comment by fz6m** [comment]
vite 属于实验性功能，目前对 win 的支持有些问题，在 #11847 跟进吧，如果可能的话，可以不开启 vite 模式或使用 linux 、mac 开发。
