### ISSUE TITLE
[Bug] 官方文档描述有问题，4.x二维码

### ISSUE THREAD

**Issue by fancysh** [umijs/umi#11841]
## What happens?

官方文档存在问题，并且二维码失效了，希望能够补充

## How To Reproduce
https://umijs.org/blog/umi-4-rc

## Context
<img width="883" alt="WeChat0f75def42565eeb34abcdf377efd9e71" src="https://github.com/umijs/umi/assets/30859260/acee8035-9ec4-4b01-b313-661ac92a9446">

- **Umi Version**: 4.0.87

**Comment by xiaohuoni** [comment]
这是发布记录，现在没有这个群了，直接加 umi 的群就好。[feedback.umijs.org](https://feedback.umijs.org/)
