### ISSUE TITLE
umi项目在火狐浏览器中使用window.location.href或者a标签无法跳转新页面

### ISSUE THREAD

**Issue by wukongyang** [umijs/umi#11859]
**需求：在页面中需要使用 window.location.href='https://www.baidu.com'  这样的api的跳转其他网页地址，但是在火狐浏览器中无法正常跳转。已经测试过其他浏览器（如谷歌）可正常跳转，使用其他React框架在火狐浏览器中可正常跳转。使用npm create umi新建的umi项目也无法在火狐浏览器中跳转，使用ip或者localhost同样无法跳转，window和Mac也无法跳转**
<img width="1418" alt="image" src="https://github.com/umijs/umi/assets/54463146/bde532e5-7cca-4066-a073-80f773e46959">
**新建的umi项目即在pages/index.tsx中添加了几句测试代码，在火狐浏览器也无法正常跳转，包括初始页面中跳转github的按钮，也无法正常跳转。**
<img width="885" alt="image" src="https://github.com/umijs/umi/assets/54463146/da528035-c335-4ea4-ab6a-a20952698186">

## Context

- **Umi Version：4.0.88**:
- **Node Version：v18.16.0**:
- **react：17.x**:

**Comment by wukongyang** [comment]
火狐浏览器版本：116.0.3

**Comment by fz6m** [comment]
See https://github.com/umijs/umi/discussions/11858#discussioncomment-7538399
