### ISSUE TITLE
[Bug] dev环境 umi.ts 中react报错

### ISSUE THREAD

**Issue by Peanutbear** [umijs/umi#11863]
报错内容 react-dom.development.js:25626 Uncaught TypeError: Cannot read properties of undefined (reading 'isBatchingLegacy')
<img width="839" alt="image" src="https://github.com/umijs/umi/assets/35757547/c26b0804-b93b-4ad6-a711-8cb40543a591">

umi 版本 3.5.41
React 版本 18.2.0

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4
