### ISSUE TITLE
开启ssr 的预渲染， 打包后的html文件，运行后 页面闪现后丢失

### ISSUE THREAD

**Issue by qianchangstyle** [umijs/umi#11865]
开启ssr 的预渲染， 打包后的html文件，运行后 页面闪现后丢失

官方提供的 demo 搭建， 只是改了这里
import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  routes: [
    { path: './', component: '@/pages/index' },
  ],
  fastRefresh: {},
  ssr: {
    devServerRender: false,
  },
  exportStatic: {

  }
});

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4 。

umi 是一个基于 react 主要面向企业中后台 pc 端的 SPA 框架，如有 SSR 需求，建议使用 nextjs 。
