### ISSUE TITLE
[Bug] Encountered a build error 'out of memory' when building on AWS Amplify. Is there any way to reduce memory usage?

### ISSUE THREAD

**Issue by linyongping** [umijs/umi#11869]
## What happens?

I want to depoly a umijs 4 with antd pro on aws amplify but  encountered  error "out of memory", 
The ci server is docker image on a host with 4 vCPU, 7GB memory. 

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your 
there is no reproduce repo to provide.

## Context

- **Umi Version**: 4.0.52
- **Node Version**: 16
- **Platform**: aws amplify ci server. docker image on a host with 4 vCPU, 7GB memory. 
- used pnpm as package maager

**Comment by fz6m** [comment]
你是指什么阶段内存不够了，和大多数前端 SPA 项目一样，umi 的产物只是一个单页应用，需要和 Nginx 一起部署服务，所以你需要在本地或者云里把 umi 项目构建好，得到 js / css / html 的产物，再把这个产物和 nginx 之类能提供 web 服务的镜像一起部署。

一个 docker 构建脚本参考：

```bash
# 使用 node 镜像
FROM node as builder

# 准备工作目录
RUN mkdir -p /app/client
WORKDIR /app/client

# 复制 package.json
COPY package*.json /app/client/

# 安装目录 （安装 pnpm 过程略）
RUN pnpm i

# 复制文件
COPY . /app/client/

# 构建
RUN pnpm build

# 准备 nginx
FROM nginx

# 自定义 nginx 设置文件
RUN rm /etc/nginx/conf.d/default.conf
# 请自行准备好自己的 nginx 配置
COPY nginx.conf /etc/nginx/nginx.conf

# 从 React container 里复制构建出来的文件
COPY --from=builder /app/client/build /usr/share/nginx/html

# 添加运行权限
RUN chown nginx.nginx /usr/share/nginx/html/ -R

# 暴露端口
EXPOSE 80
```
