### ISSUE TITLE
开启ssr 的预渲染， 打包后的html文件，运行后 页面闪现后丢失

### ISSUE THREAD

**Issue by qianchangstyle** [umijs/umi#11866]
## What happens?

https://github.com/umijs/umi/issues/11865

## Mini Showcase Repository(REQUIRED)

demo仓库地址： https://github.com/qianchangstyle/umidemo

## How To Reproduce

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
> 已线下沟通。

看了下你前面的聊天记录，你访问的是 /dist。/dist 下没路由的，你需要在 dist 下启静态 server，然后访问 / 。

我试了下是正常的。

<img width="389" alt="image" src="https://github.com/umijs/umi/assets/35128/1754319f-1fb0-474c-a1e6-ea8427bfe0b6">
