### ISSUE TITLE
[Bug] presets走三方包失败

### ISSUE THREAD

**Issue by DroganC** [umijs/umi#11872]
三方包导出
```js 
export default ()=>{
      return {
            plugins:[]
    }
}
```
umi/config里引入
```
{
...,
presets:['@npm/plugins']
}
```

报错：key plugins is already registered by xxxxx， plugin from undefined register failed.

**Comment by DroganC** [comment]
但是本地工程里直接用是可以得

**Comment by fz6m** [comment]
应该是没定义 key 或者 key 重复了，需要确保插件间的唯一性：

```ts
api.describe({
    key: 'unique-key',
  });
```

如还有问题，需要给一个最小复现。

**Comment by DroganC** [comment]
> 应该是没定义 key 或者 key 重复了，需要确保插件间的唯一性：

感谢指导；另外想请教一下，插件和默认config的优先级。
是不是插件集的优先级会覆盖掉config里的其他的配置

**Comment by fz6m** [comment]
你指的 config 是指啥，正常情况下插件一般拥有自己的配置项，自己通过 `api.userConfig` 可以获取，之后做一些插件自己的行为。

如果你想控制 `modifyWebpackConfig` / `modifyDefaultConfig` / `modifyConfig` 等等这些行为 api 的执行顺序，可以写成：

```ts
api.xxx({
  fn: () => {},
  stage: Infinity // -Infinity ... ，如果都是 Infinity 则后加载的靠后
})
```

可以参考 [`preset-umi`](https://github.com/umijs/umi/tree/master/packages/preset-umi) / [`plugins`](https://github.com/umijs/umi/tree/master/packages/plugins) 这两个目录里的插件了解 api 的使用。
