### ISSUE TITLE
[Bug] proxy 代理 OPTIONS 请求无数据

### ISSUE THREAD

**Issue by houkunlin** [umijs/umi#11875]
## What happens?

在开发环境使用 proxy 代理后端请求时，遇到 OPTIONS 请求类型的接口无法获得数据，返回了 HTTP 204 并且无内容数据，经过查看后端日志，请求并未到达后端。
![image](https://github.com/umijs/umi/assets/12333292/8a7855bc-b321-4f0c-9b97-d95d533a3501)

而直接请求后端时是正常有数据的
![image](https://github.com/umijs/umi/assets/12333292/ff115b7f-6e54-4f8e-89ed-8a29979a3ee4)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
目前 proxy 由于 cors 的设定，所有 options 请求都只会返回 204 ，绝大多数场景下不会需要 options 获取数据，如果有自己的需求，可以自己再起一个服务或者用其他本机代理软件（如 charles 、switch omega 、 whistle 等）把 options 请求单独代理出去。
