### ISSUE TITLE
[Bug] 文档写的是真垃圾

### ISSUE THREAD

**Issue by hu25594759** [umijs/umi#11879]
![image](https://github.com/umijs/umi/assets/92702721/8b65d684-dbd3-48cb-ae95-21236272e1b7)
![image](https://github.com/umijs/umi/assets/92702721/fd5eec34-f948-492a-9f27-d339164105eb)

既然已经移除了umi，为什么配置里又是：import { defineConfig, utils } from 'umi';

这文档真是一言难尽

**Comment by fz6m** [comment]
无论是 max 还是 umi 的项目，从 `@umijs/max` 或者 `umi` 导入都是内容相同的，区别是有没有类型提示，这里的类型提示可能与使用的包管理器有关，如果是打平的存在幽灵依赖，可能从 `umi` 导入也有类型提示。

另外，如果是 umi 3 的项目，理论上都应该升级为 `max` ，统一从 `@umijs/max` 导入内容，但也可以升级为 `umi` 4 ，然后自己配置插件达到想要的功能，从而无需更改导入。

**Comment by wadjxjh** [comment]
终于有人吐槽这个问题了。版本更新，文档却不是最新的，起码有很多地方还是cv的之前文档
