### ISSUE TITLE
[Bug] SSR error: Cannot read properties of null (reading 'applyPlugins')

### ISSUE THREAD

**Issue by hrjoyce1990** [umijs/umi#11876]
<img width="747" alt="image" src="https://github.com/umijs/umi/assets/34337914/9b9e6a8e-0456-465e-83bd-d15ef92e02b4">

开启ssr后 npm run dev 报错。
**规避错误方法：将umirc.ts里的antd配置，theme token去掉即不会报错。**

umirc.ts
  export default defineConfig({
  antd: {
    theme: {
      token: {
        colorBgLayout: '#fff',
      },
    },
  },
  access: {},
  model: {},
  initialState: {},
  request: {},
  layout: {},
  routes,
  ssr: {},
  npmClient: 'pnpm',
});
## Context

- **Umi Version** 4.0.88:

**Comment by fz6m** [comment]
ssr 是实验性特性，如需 ssr ，建议使用更全面的 nextjs 。
