### ISSUE TITLE
[Bug] 升级umi4报错  Cannot read properties of undefined (reading 'call')     at options.factory (react refresh:6:1)

### ISSUE THREAD

**Issue by z1811021** [umijs/umi#11887]
升级到umi4 报错
<img width="866" alt="image" src="https://github.com/umijs/umi/assets/15137711/5ec5ab93-3772-4b46-b0d9-f3fc2cfdfbd7">
<img width="563" alt="image" src="https://github.com/umijs/umi/assets/15137711/66001ff5-5118-4874-b914-fbc0febc0c78">

## Context

- **Umi Version**: 4.0.88
- **Node Version**:  18
- **Platform**: PC

**Comment by fz6m** [comment]
如果有问题，需要给一个最小复现。
