### ISSUE TITLE
[Feature Request] Umi中接入wujie微前端生命周期改造

### ISSUE THREAD

**Issue by webwyb** [umijs/umi#11895]
## Background

在Umi框架中接入微前端方案 [Wujie](https://wujie-micro.github.io/doc/guide/start.html#%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F%E6%94%B9%E9%80%A0) 

其中采用wujie单例模式时涉及到子应用生命周期的改造，即组件unmount时通知给wujie

## Proposal

umi 增加对应的函数或入口，支持开发者感知组件卸载的声明周期

![image](https://github.com/umijs/umi/assets/23635787/71a4560b-0147-477a-8450-a84200025265)

## Additional context

如umi框架开发者有其他解决方案，请指教

**Comment by fz6m** [comment]
你可以参考 umi [qiankun 插件](https://github.com/umijs/umi/blob/master/packages/plugins/src/qiankun.ts) 的实现，和这里是一样的，umi 本身有一个 `render()` 方法，qiankun 插件会把它用 promise 挂起一直不调用，等到 qiankun 主应用来启动这个应用 mount 的时候再调用挂载上去，卸载的时候同样也是用 react dom 之类的方法去卸载的（react 18 有所不同）；另外你可以启动两个 umi 的 qiankun 主、子应用看下 `./src/.umi/plugin-qiankun-*` 相关的代码，是可以纯依靠编写一个 umi 插件来实现你的需求的。
