### ISSUE TITLE
[react-router-dom] react-router-dom啥时候支持6.4.0以上

### ISSUE THREAD

**Issue by decSunshineHe** [umijs/umi#11893]
## Background

现在依赖的react-router-dom是6.3.0，不支持6.4.0以上，2022 年9月发布的 [v6.4.0](https://link.juejin.cn/?target=https%3A%2F%2Fgithub.com%2Fremix-run%2Freact-router%2Freleases%2Ftag%2Freact-router%25406.4.0) 版本，引入 createBrowserRouter/createHashRouter 、<RouterProvider> 等Data API

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

## Additional context

希望官方早点支持哇

**Comment by jiankafei** [comment]
由于二方包里无法直接引用 umi，但同时又需要类似的功能，怎么搞？

**Comment by jiankafei** [comment]
> 虽然没有升级，但是目前没有什么问题，由于 umi 要提供外置 history （沿袭 umi 3 用法，[参考文章](https://sakina.blog.csdn.net/article/details/126945139)），这只能使用旧 browser router ，你所说的那些新的 router 类型是用不了的。
> 
> 所以和目前最新的 react router 的差异我理解在于一些 remix 带来的的高级功能和部分新 api ，但 `Async` / `Awaited` / data loader 等等这些都是需要和 browser data router 结合的，旧 browser router 用不了，出于上面描述的原因这部分差异可以忽略不计。
> 
> 一个比较热点的需求是 prompt ，因为在 v6.x 非 beta 版的时候 RR 不自带 prompt 了，但我们也有一个解决方案，参考：[#10237](https://github.com/umijs/umi/discussions/10237)
> 
> 综上，目前还没有一个很紧急的理由去升级路由，升级了之后我们还要考虑是否存在 Breaking change 。

那意思是后面不升级新的路由模式了？没有 umi5 了？没有计划了？

**Comment by zhenyu-dev** [comment]
> 虽然没有升级，但是目前没有什么问题，由于 umi 要提供外置 history （沿袭 umi 3 用法，[参考文章]


参考文章链接失效了，想了解下为啥要沿用remix history
