### ISSUE TITLE
umi-test 无法跑指定文件的单测

### ISSUE THREAD

**Issue by ACERY1** [umijs/umi#1189]
场景如下：
在项目根目录有一个test文件，里面有各插件的单测实例，想要运行单独的某个单测实例，出现了如下的情况：

![image](https://user-images.githubusercontent.com/19555547/46389332-c5abcc80-c703-11e8-9a13-acb64deab0b3.png)

本来只想运行 hd.e2e.js，结果还运行了另外一个插件的单测，项目里面只有两个插件，也就是说运行了所有的单测实例。

这种情况如何解决？

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/46852446-9f85db00-ce2d-11e8-9906-c72c3e15c453.png)

试了下不能重现，提供一个简单的可重现例子再 reopen 。
