### ISSUE TITLE
多语言项目ssr渲染时怎么自定义getLocale

### ISSUE THREAD

**Issue by tdw143** [umijs/umi#11890]
## What happens?
多语言项目ssr渲染时，在服务端时通过解析请求路径中的语言信息设置setLocale，但是要怎么自定义getLocale，现在是通过全局属性处理，但是在并发下会出现语言错乱的情况，要怎么处理呢？

// BaseLayout.jsx
BaseLayout.getInitialProps = async (ctx) => {
  if (ctx.isServer) {
    const { lang, originPath } = parseUrlPath(
      ctx.req?.url ||
        ctx.history.location.pathname + ctx.history.location.search,
    );
    setLocale(lang, false);
  }
}

// app.js
global.localeFromUrl = undefined;
export const locale = {
  default: 'en-US',
  getLocale: () => {
    if (isBrowser()) {
      if (!global.localeFromUrl) {
        global.localeFromUrl =
          parseUrlPath(location.pathname + location.search)?.lang || 'en-US';
      }
      return global.localeFromUrl;
    } else {
      return global.localeFromUrl || 'en-US';
    }
  },
  setLocale: ({ lang, realReload, updater: updater }) => {
    moment.locale(lang);
    setIntl(lang);
    global.localeFromUrl = lang;
  },
};

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
umi 3 不维护了。如需使用 ssr ，建议迁移到更全面的 nextjs 。
