### ISSUE TITLE
[Bug] yarn build 之后将 html/js/css 放到 iframe 中执行，出现空白页面

### ISSUE THREAD

**Issue by snksos** [umijs/umi#11896]
## yarn build 之后将 html/js/css 放到 iframe 中执行，出现空白页面

运行之后控制台：
![image](https://github.com/umijs/umi/assets/7006708/a987e675-d317-4782-96be-1b077bce0fab)

文件目录：
<img width="257" alt="image" src="https://github.com/umijs/umi/assets/7006708/d853c2b9-8061-4786-8bfb-8b3ba2a24545">

**Comment by fz6m** [comment]
首先要确保不在 iframe 里这个产物经过 nginx 等方式来提供服务是可以正常显示的，之后再把这个 url 嵌入到你想要的地方，同时需要确保相关的 csp 安全头允许这种行为。

如有问题，需要给一个最小复现。
