### ISSUE TITLE
在pages/index/models/count.js中使用subscriptions报错

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#119]
count.js
```js
export default {
  namespace: 'count',
  state: 0,
  subscriptions: {
    setup({ dispatch, history }) {
      return history.listen(({ pathname, query }) => {
        if (pathname === '/') {
          //do somethins
        }
      });
    },
  },
  reducers: {
    increase(state) {
      return state + 1;
    },
    decrease(state) {
      return state - 1;
    },
  },
};
```
访问http://localhost:8001/

## TypeError: Cannot read property 'listen' of undefined
setup
D:/umi/examples/with-dva/src/pages/index/models/count.js:8
   5 | setup: function setup(_ref) {
   6 |   var dispatch = _ref.dispatch,
   7 |       history = _ref.history;
 > 8 |   return history.listen(function (_ref2) {
   9 |     var pathname = _ref2.pathname,
  10 |         query = _ref2.query;
  11 | 
View compiled

**Comment by sorrycc** [comment]
不能重现，我在 https://github.com/umijs/umi/blob/master/examples/with-dva-enable-plugin/src/pages/index/models/count.js 试了下，是正常的。

**Comment by sorrycc** [comment]
先关了，有问题再 reopen 。
