### ISSUE TITLE
用代理post传的参数接收不了啊。。

### ISSUE THREAD

**Issue by sskcal** [umijs/umi#1190]
用proxy设置的代理，POST是无法取到参数的，有解决办法吗？

**Comment by zjxpcyc** [comment]
具体点

**Comment by xiaohuoni** [comment]
umi的版本号多少，升级到最新还存在问题，再reopen吧

**Comment by Evanlai8** [comment]
同上，umi版本 v2.1.1,
返回了200，但是post并没有成功
有没有办法可以看到传到后台的真实请求

**Comment by zjxpcyc** [comment]
@Evanlai8  post 没有成功应该不会有 200 返回。你看下你的服务容器的日志，比如 tomcat ，nginx 。然后再让后端的人跟踪下数据流，或者你用 chrome F12 或者 fiddler 之类的软件跟踪下网络请求看看。

我印象里面，好像 java 部分的框架对发送 json 数据好像是不能直接拿到的。不搞 java 不太懂。

**Comment by xiaohuoni** [comment]
@Evanlai8 建议你使用文档里面的测试接口 http://jsonplaceholder.typicode.com/users 先测试一下前端的代码

**Comment by githubmann** [comment]
很好理解，就是 body 参数没有被 http-proxy-middleware 传过去；需要自己配置。
