### ISSUE TITLE
[Bug] umi3和umi4 history.location.pathname和history.location.createHref方法在设置了base后表现不一致

### ISSUE THREAD

**Issue by wenlei0617** [umijs/umi#11904]
文档中umi3升级到umi4中并没有提到history方法做了修改，导致以下行为完全不一致了。这应该是升级bug？为什么要修改呢？

// umi3 base 配置 /template
history.createHref({ pathname: '/test' }); // 打印为 /template/test
// 当前路径为/template/test时
history.location.pathname;  // 打印为 /test

// umi4 base 配置 /template
history.createHref({ pathname: '/test' }); // 打印为 /test
// 当前路径为/template/test时
history.location.pathname;  // 打印为 /template/test

## Context

- **Umi Version**: 4.0.88
- **Node Version**: 16
- **Platform**: mac

**Comment by fz6m** [comment]
参考 https://github.com/umijs/umi/issues/10849#issuecomment-1826606385 ，自行替换下使用的地方代码即可，目前 react router v6 的设计是全 hooks 式的，是大势所趋，应该尽早摆脱对 history 的依赖。
