### ISSUE TITLE
[Bug] shouldNotModifyDefaultBase. 没有生效

### ISSUE THREAD

**Issue by Yalhu** [umijs/umi#11902]
## What happens?
umi4 配置qiankun 子应用shouldNotModifyDefaultBase 没有生效。

```js
qiankun: {
    slave: {
      // enable: true,
      shouldNotModifyDefaultBase: true,
    },
  },
```
子应用使用antd模版创建的项目，应该不需要再安装qiankun 和qiankun 插件。
手动安装qiankun插件，添加配置后，项目运行报错。
```js
plugins: [
    '@umijs/plugin-qiankun'
  ],
```

## Context
"@umijs/max": "^4.0.71"
- **Umi Version**:
- **Node Version**: v14.19.0
- **Platform**: mac os

**Comment by fz6m** [comment]
`@umijs/plugin-xxx` 是 umi 3 的插件，umi 4 不需要，把 `@umijs/plugin-xxx` 依赖和配置全部去掉就可以。

如果你用 max ，常用插件都自带内置了，不需要自己配，直接打开 `qiankun: {}` 就行。

Umi 4 的可配项可以参考 [微前端](https://umijs.org/docs/max/micro-frontend) 文档。

**Comment by Yalhu** [comment]
> `@umijs/plugin-xxx` 是 umi 3 的插件，umi 4 不需要，把 `@umijs/plugin-xxx` 依赖和配置全部去掉就可以。
> 
> 如果你用 max ，常用插件都自带内置了，不需要自己配，直接打开 `qiankun: {}` 就行。
> 
> Umi 4 的可配项可以参考 [微前端](https://umijs.org/docs/max/micro-frontend) 文档。

打开 qiankun添加shouldNotModifyDefaultBase 配置项，没有生效。。

添加@umijs/plugin-qiankun 是因为上面没有生效才加的。已经去掉了。

**Comment by fz6m** [comment]
`shouldNotModifyDefaultBase` 的选项位置在 `qiankun.slave.shouldNotModifyDefaultBase` 。

如还有问题，需要给一个最小复现。

**Comment by fz6m** [comment]
`shouldNotModifyDefaultBase` 是用来控制独立开发时 base 是否自动添加 `/${package.json#name}` 的，默认情况下，独立启动时会展示在 `/${package.json#name}/path/xxx` 下面。

如果你不想要 `<script>window.publicPath =window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__ | ...` ，需要配置 `qiankun.slave.shouldNotModifyRuntimePublicPath: true` 。

**Comment by Yalhu** [comment]
配置`qiankun.slave.shouldNotModifyRuntimePublicPath: true`，应用单独打开， 动态加载的资源路径（666.d75d3333.async.js）就不是配置的PublicPath，而是当前页面路径，引入有问题。

**Comment by fz6m** [comment]
如还有问题，需要提供上下文信息和给一个最小复现的仓库。

**Comment by Yalhu** [comment]
base路由怎么在乾坤子应用自动添加前缀，比如xxx.com/supapp/home？单独打开应用的话，可以不加前缀 xxx.com/home。
背景：主应用（非qiankun）需要根据路径去加载相应子应用。

现象：好像`qiankun.slave.shouldNotModifyDefaultBase` 配置并不是针对乾坤（子）应用的。
临时方案：目前是base配置是固定的。

希望：应用路由base 如果只在主应用中打开，添加前缀。

**Comment by fz6m** [comment]
给子应用配置 `shouldNotModifyDefaultBase: true` ：

```ts
// .umirc.ts

  qiankun: { slave: { shouldNotModifyDefaultBase: true } }
```

父应用：

```ts
// .umirc.ts

  routes: [
    {
      name: 'app1',
      path: '/app1/*',
      microApp: 'app1',
    },
  ],
  qiankun: {
    master: {
      apps: [
        {
          name: 'app1',
          entry: '//localhost:7001',
        },
      ],
    },
  },
```

以上这个例子可以实现在主应用打开 `app1` 这个菜单或者对应的子应用路径就可以加载子应用，如果单独打开子应用 `http://localhost:7001` 就可以直接访问子应用。

当然在生产部署时，主子应用的域名不能是一个（或者自己想办法写 nginx 规则分流）。

至于你说的 publicPath 问题，需要自己尝试配置和调试解决，通常我们会把 publicPath 配成 cdn 域名，这样所有资源都走 cdn 不会有路径不清晰的问题，如果你是模板机、虚拟机提供资源，要自己调试和修订 nginx 分流规则等方式来实现。

另外当你需要在某个路径下展示某个子应用时，可以把这个路径改为通配 `/subpath/*` ，手动写一个组件来展示子应用，参考 [`<MicroApp />`](https://umijs.org/docs/max/micro-frontend#microapp--%E7%BB%84%E4%BB%B6%E5%BC%95%E5%85%A5%E5%AD%90%E5%BA%94%E7%94%A8) 。
