### ISSUE TITLE
[Bug] umi4 Error: Cannot find module '@umijs/plugins/dist/unocss'

### ISSUE THREAD

**Issue by RoyKwok94** [umijs/umi#11908]
## What happens?

umi4 如何到底怎样使用unocss,我跟着文档 操作，可是还是报 Cannot find module '@umijs/plugins/dist/unocss'，文档中提到
安装 plugin-unocss
安装 unocss 及 @unocss/cli
可是没有 plugin-unocss这个包啊，究竟在哪个环节出问题，还是说MAX才支持，纯净的umi不支持

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

创建个纯净 umi 工程，跟着文档配置unocss 就出现了 Error: Cannot find module '@umijs/plugins/dist/unocss'
## Context

- **Umi Version**: "4.0.88"
- **Node Version**:v16.20.1
- **Platform**: win

**Comment by fz6m** [comment]
unocss 和 tailwind 这俩功能是很久以前做的功能了，一直没维护。因为 unocss 和 tailwind 那个时候和现在对比使用方式有了较大的变化，所以目前不建议使用 umi 自带的 tailwind 和 unocss 插件了，直接根据 unocss 和 tailwind 的官网的接入方式自己配置 postcss 插件或者 webpack 插件等方法使用就可以。

**Comment by gitdust** [comment]
> unocss 和 tailwind 这俩功能是很久以前做的功能了，一直没维护。因为 unocss 和 tailwind 那个时候和现在对比使用方式有了较大的变化，所以目前不建议使用 umi 自带的 tailwind 和 unocss 插件了，直接根据 unocss 和 tailwind 的官网的接入方式自己配置 postcss 插件或者 webpack 插件等方法使用就可以。

大佬们把官网文档更新下，配了半天不行才找到这里...
