### ISSUE TITLE
[Bug] umi 2.x 版本 

### ISSUE THREAD

**Issue by YangBo29** [umijs/umi#11909]
## What happens?
今天umi 2.x 版本 再安装jsdom 这个依赖的时候，出现如图问题
![image](https://github.com/umijs/umi/assets/12638036/e255debf-591a-452e-a075-d12b7ecc707c)
尝试锁定umi版本无效，应该是内部依赖没有锁定小版本，导致jsdom 发布23.0.0版本后出现了，node 版本不得小于18的限制。
这个有办法再umi内部锁定么

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by YangBo29** [comment]
你说的问题我清楚， 现在的这个项目node18的版本是无法正常使用的，升级umi尝试过，不过升级后的情况不太符合我们的预期，而且项目比较庞大，开发任务重，短期能不太能迁移。既然不维护了那也没有办法了。目前是增加了yarn.lock 但是来保证打包。再想想其他办法吧。问题肯定是jsdom。因为昨天他们周日刚发的新版本，说明了必须要求node18以上

**Comment by taoWcode** [comment]
我今天也遇到类似的问题，维护一个三年前的umi2.0老项目，不知道哪个依赖添加了jsdom依赖。我发现项目没有.gitinore忽略了lock文件。
但是这个项目一直是在线上跑的，于是去服务器把yarn.lock拿回来，重新安装依赖就可以了。

**Comment by taoWcode** [comment]
我今天也遇到类似的问题，维护一个三年前的umi2.0老项目，不知道哪个依赖添加了jsdom依赖。我发现项目没有.gitinore忽略了lock文件。
但是这个项目一直是在线上跑的，于是去服务器把yarn.lock拿回来，重新安装依赖就可以了。

**Comment by YangBo29** [comment]
umi 里面的测试模块引入了这个依赖，umi 外层锁定了版本，但是内部依赖没有锁定版本，导致jsdom升级23.0 出现了这个问题，问题是外部无法锁定umi版本，就很难受。我们这个项目是4年前的项目了。没时间做重构，所以现在只能靠lock来解决这个问题

**Comment by githubCK** [comment]
这么旧的版本，还要求用很高版本的node，明显是属于官方的bug。请务必修复，很多旧的项目新人参与维护都起不来了，别说靠lock来解决，那个是错误的行为

**Comment by smeltH** [comment]
确实是官方的 bug  可使用resolutions解决
<img width="985" alt="image" src="https://github.com/umijs/umi/assets/41537970/7f2942be-e57e-4cdd-adc3-fd8b9fb52b4e">

**Comment by YangBo29** [comment]
是的 我现在也是通过 resolutions 去锁定jsdom的版本了
