### ISSUE TITLE
umi4 为什么ant-design-pro 项目在使用了selectLang之后，一更新就页面卡死，

### ISSUE THREAD

**Issue by zlymweb** [umijs/umi#11911]
![image](https://github.com/umijs/umi/assets/18113970/2618fc55-2e3e-48b3-b32b-63faffc896fc)
![image](https://github.com/umijs/umi/assets/18113970/e524b511-eee3-4b4c-9387-99885a77441b)

我在项目中一加上SelectLang,跑起来之后一旦对页面做个修改保存就会页面卡死，过了一会页面就会显示内存溢出，这是什么问题呢？不用selectLang就正常。。

**Comment by fz6m** [comment]
需要给一个最小复现。
