### ISSUE TITLE
[Bug] AssertionError [ERR_ASSERTION]: chunk of react-vendors not found.

### ISSUE THREAD

**Issue by xiaoguoyao** [umijs/umi#11918]
## AssertionError [ERR_ASSERTION]: chunk of react-vendors not found.

**有且只有windows平台会出现此问题！！！**
1、使用的是umi3x的版本：3.5.41
2、在.umirc.ts文件上面配置分包
3、通过npm start或者umi dev启动项目，成功后访问localhost:8000，项目挂了并且访问不了了

**报错截图如下**
![image](https://github.com/umijs/umi/assets/51302614/0674d48c-9be5-4aa4-bfad-cd1081e68a47)

## 分包的配置如下：
![image](https://github.com/umijs/umi/assets/51302614/73af1461-65b9-4ca6-83e3-4f6ac47fa851)
![image](https://github.com/umijs/umi/assets/51302614/ea7d6efc-b641-49b6-a633-59be2bd2bd7d)
![image](https://github.com/umijs/umi/assets/51302614/e64909b1-bd7c-4e50-aa0f-cc22e341357e)
![image](https://github.com/umijs/umi/assets/51302614/421bd6d9-06a1-4b86-9585-71888c12ecd7)

## Context

- **Umi Version**:3.5.41
- **Node Version**:v16.10.0
- **Platform**:windows

**Comment by xiaoguoyao** [comment]
经过排查是路径问题windows和mac的路径字符串，导致没有分包成功，然后估计umi拿的是vendors里写的配置去拿不到分包，所以导致出错，倒是项目直接崩溃没有友好提示，有点懵

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4
