### ISSUE TITLE
启动经常出现tailwind check error [Bug] say something

### ISSUE THREAD

**Issue by WuJiY** [umijs/umi#11912]
```
info  - Umi v4.0.88
info  - Preparing...
info  - [plugin: ./node_modules/.pnpm/@umijs+plugins@4.0.88_@babel+core@7.23.3_@types+react-dom@18.2.17_@types+react@18.2.39_antd@4_yqo6kuwxq74zvm5dygthrpnuf4/node_modules/@umijs/plugins/dist/tailwindcss] tailwindcss service started
😄 Hello PRO
error - [plugin: ./node_modules/.pnpm/@umijs+plugins@4.0.88_@babel+core@7.23.3_@types+react-dom@18.2.17_@types+react@18.2.39_antd@4_yqo6kuwxq74zvm5dygthrpnuf4/node_modules/@umijs/plugins/dist/tailwindcss] tailwindcss generate failed after 5 seconds, please check your tailwind.css and tailwind.config.js
```
## Context

- **Umi Version**:4.0.88
- **Node Version**:20
- **Platform**:windows

**Comment by fz6m** [comment]
unocss 和 tailwind 这俩功能是很久以前做的功能了，一直没维护。

因为 unocss 和 tailwind 那个时候和现在对比使用方式有了较大的变化，故目前不建议使用 umi 自带的 tailwind 和 unocss 插件了。

如果要使用 tailwind 和 unocss ，直接根据 unocss 和 tailwind 的官网的接入方式自己配置 postcss 插件或者 webpack 插件等方法使用就可以。

**Comment by WuJiY** [comment]
好的  谢谢

**Comment by nnmax** [comment]
> unocss 和 tailwind 这俩功能是很久以前做的功能了，一直没维护。
> 
> 因为 unocss 和 tailwind 那个时候和现在对比使用方式有了较大的变化，故目前不建议使用 umi 自带的 tailwind 和 unocss 插件了。
> 
> 如果要使用 tailwind 和 unocss ，直接根据 unocss 和 tailwind 的官网的接入方式自己配置 postcss 插件或者 webpack 插件等方法使用就可以。

能否把这些建议放到官方文档里？而不是在出现问题的时候再来 GitHub 上寻找解决方案的时候说不推荐使用。

**Comment by tylerrrkd** [comment]
> um

@fz6m Hi 大佬，我在 `@umijs/max` 项目中遇到了相同问题，我按 `tailwindcss` 推荐的方式( [`postcss`](https://tailwindcss.com/docs/installation/using-postcss) )去配置时，会出先构建时间超级久（一次十几分钟）的问题，然后我一旦删除 `postcss.config.js` 文件(里面仅包含 `tailwindcss` 和 `autoprefixer` 两项配置)时就会恢复到正常构建时间。尝试各种方法：升级 `@umijs/max` `tailwindcss` 或者 使用 `@umijs/max` 自带的 `tailwind` 配置都无法解决这个问题。请问有什么方法可以解决么？

```typescript
import { defineConfig } from "@umijs/max";

import routes from "./routes";

export default defineConfig({
  access: {},
  model: {},
  initialState: {},
  request: {},
  npmClient: "pnpm",
  hash: true,
  metas: [
    {
      name: "viewport",
      content: "width=375, user-scalable=no, viewport-fit=cover",
    },
    {
      name: "renderer",
      content: "webkit",
    },
  ],

  targets: {
    android: 5,
    ios: 7,
    chrome: 58,
  },
  clickToComponent: {},
  crossorigin: {},
  routes,
  locale: {
    antd: false, // 如果项目依赖中包含 `antd`，则默认为 true
    baseNavigator: false,
    baseSeparator: "-",
    default: "en",
    title: true,
    useLocalStorage: true,
  },
  forkTSChecker: {},
  jsMinifier: "terser",
});
```
