### ISSUE TITLE
打包后base 没了？

### ISSUE THREAD

**Issue by zhangxinyong12** [umijs/umi#11917]
![image](https://github.com/umijs/umi/assets/29941627/70516554-edbe-48d4-9ce3-cfdae38a0bd4)
我看wen文档上说是这样说。
`
export default defineConfig({
  base: '/admin/',
});
`

当我查看打包后的index.html
![image](https://github.com/umijs/umi/assets/29941627/825713a0-2b56-403e-a302-b15db2104e3d)
我希望是/admin/umi.js 这样的？是我那个地方使用不对吗？

**Comment by fz6m** [comment]
`base` 是指运行时路由的基础路径前缀，比如运行在域名的子路径 `https://domain.com/prefix/` 上，这时候就需要 `base: '/prefix/'` ，但是你的资源不一定从哪里来，资源的加载路径要配置 [`publicPath`](https://umijs.org/docs/api/config#publicpath) ，比如：

```ts
// .umirc.ts

  publicPath: process.env.NODE_ENV === 'production' ? '//cdn.domain.com/oss/bucket/project/version/' : '/'
``` 

这时候资源就会从 `//cdn.domain.com/oss/bucket/project/version/umi.js` 加载。

如果你的资源和运行 url 子路径是一样的，那就把 base 和 publicPath 配成一样的即可，具体可自己探索是否产物正常和部署后展示正常即可。

**Comment by zhangxinyong12** [comment]
> `base` 是指运行时路由的基础路径前缀，比如运行在域名的子路径 `https://domain.com/prefix/` 上，这时候就需要 `base: '/prefix/'` ，但是你的资源不一定从哪里来，资源的加载路径要配置 [`publicPath`](https://umijs.org/docs/api/config#publicpath) ，比如：
> 
> ```ts
> // .umirc.ts
> 
>   publicPath: process.env.NODE_ENV === 'production' ? '//cdn.domain.com/oss/bucket/project/version/' : '/'
> ```
> 
> 这时候资源就会从 `//cdn.domain.com/oss/bucket/project/version/umi.js` 加载。
> 
> 如果你的资源和运行 url 子路径是一样的，那就把 base 和 publicPath 配成一样的即可，具体可自己探索是否产物正常和部署后展示正常即可。

ok。明白了。文档能再说明一下就更好了。我刚开始理解错意思了。

**Comment by zhangxinyong12** [comment]
感谢
