### ISSUE TITLE
建议添加支持 br 压缩

### ISSUE THREAD

**Issue by sishen654** [umijs/umi#11922]
![image](https://github.com/umijs/umi/assets/65691266/112a15cc-4b74-4418-8f45-f95c2937701a)

**Comment by fz6m** [comment]
和大多数 SPA 前端应用一样，umi 的构件产物是纯静态的 js / css 等文件，当你把这些静态资源通过 nginx 等方式部署到生产环境后，采用什么压缩方式是由你的资源提供服务决定的，和 umi 无关。

故需要修改 Nginx 配置或 cdn 配置等方式来实现；当然，有一些网关代理如 CF 也可以做到，请自行研究。
