### ISSUE TITLE
`umi`里面怎么添加`storybook`

### ISSUE THREAD

**Issue by tangweikun** [umijs/umi#1192]

**Comment by sorrycc** [comment]
我们会写一个 umi-plugin-storybook 来做这件事。

**Comment by zikkeung** [comment]
> 我们会写一个 umi-plugin-storybook 来做这件事。

1年了，umi-plugin-storybook开发出来了吗

**Comment by GloriaCHL** [comment]
> 我们会写一个 umi-plugin-storybook 来做这件事。

2年了，umi-plugin-storybook开发出来了吗？还是有其他替代方案？

**Comment by xiaohuoni** [comment]
使用dumi https://d.umijs.org/

**Comment by fuzhongfeng** [comment]
4年了，umi-plugin-storybook开发出来了吗？还是有其他替代方案？

**Comment by rexleimo** [comment]
5年了，umi-plugin-storybook开发出来了吗？还是有其他替代方案？

**Comment by fangfa135** [comment]
> 使用dumi https://d.umijs.org/

dumi2也不能集成在项目里，对于非组件库项目太难了
