### ISSUE TITLE
umijs 的request怎么监听响应码302 重定向的状态呢？

### ISSUE THREAD

**Issue by cangsnage** [umijs/umi#11929]
怎么监听接口响应状态码
![1700480825182](https://github.com/umijs/umi-request/assets/25116493/9e08a90e-06c2-48b7-8126-761d2904465c)

设置这个页没办法前端进行操作？
![f26f819b6c5d263d0bb3a0a2ee5e7f5](https://github.com/umijs/umi-request/assets/25116493/c3c49199-cc95-4021-a467-80398c61f846)

**Comment by fz6m** [comment]
在响应拦截器里处理一下吧：

```ts
request('/test', {
  // method: 'POST',
  // data: {},
  // ↓ 防止非 200 报错
  validateStatus: () => true,
  responseInterceptors: [(r) => {
    r.data._rawResponse = r
    return r
  }],
})
```

可以把这个方法包装一下用于那些可能 302 的接口。

**Comment by sunshineLing** [comment]
302是不会被相应拦截器捕获的
