### ISSUE TITLE
[Bug] openapi生成的ts文件名变成全部小写开头

### ISSUE THREAD

**Issue by totoro52** [umijs/umi#11934]
## What happens?
电脑A：
![Snipaste_2023-12-05_16-17-13](https://github.com/umijs/umi/assets/25952444/e5f0c112-c157-4a23-bcc2-a0cd6a1e0284)
电脑B：
![Snipaste_2023-12-05_16-17-25](https://github.com/umijs/umi/assets/25952444/c92c6f46-ab0e-4b55-aa63-866ea3909567)
在两台电脑上使用同一套源码同一套接口地址开发，生成出来的接口文件偶尔是大写开头偶尔是小写开头，官方文档提供的信息太少，没办法切入分析，我想知道可以自定义配置规则吗

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
openapi 的插件在这个 [仓库](https://github.com/umijs/umi-presets-pro) ，到对应的仓库看一下源码找找原因或者在那边发 issue 询问吧。
