### ISSUE TITLE
extraBabelIncludes里面写了需要编译的依赖react-monaco-editor，但是编译完依旧带着可选链

### ISSUE THREAD

**Issue by luckylight** [umijs/umi#11937]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.5
- **Node Version**:
- **Platform**:

由于客户自带的是低版本的谷歌浏览器，需要对react-monaco-editor进行额外的编译处理，但是处理完之后，umi.js中还是带着可选链
![image](https://github.com/umijs/umi/assets/20329459/f4b98cc1-2e58-40ab-8f0f-7709354b3c0c)
![B@ASD5Y)`@~8R@8}SD00O8P](https://github.com/umijs/umi/assets/20329459/bd6196d7-06d4-4e50-80ed-80c1770bd229)

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4
