### ISSUE TITLE
[Bug] Simple App 模板项目中，js文件import时无提示对应包export的值

### ISSUE THREAD

**Issue by lin-pwd** [umijs/umi#11944]
## What happens?

项目为ts模式时，项目的js文件import时无提示
`import {} from 'umi'` 例如在js/jsx文件中引入umi包的某个值，在 `{}` 中键入 `h` 不会提示 'history'；在ts/tsx文件则正常反应

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

复现仓库: https://github.com/lin-pwd/umi-js-import-issue

## How To Reproduce

**Steps to reproduce the behavior:**
1. 拉取上述仓库地址后，`npm i`
2. vscode 打开项目，全局搜索 `NOTE:` 会出现两处地方，分别按其说明尝试键入内容
![image](https://github.com/umijs/umi/assets/139846841/a277b59f-70a6-46b3-9411-fc4a0fe63aa0)

**Expected behavior:** 开发工具正常提示包导出的值

## Context

- **Umi Version**: v4.0.89
- **Node Version**: v16.15.0
- **Platform**: Windows 10 19044.2846

**Comment by fz6m** [comment]
js 文件是否有代码提示取决于 `jsconfig.json` ，目前社区绝大多数框架均已默认使用 ts 模板，故不推荐继续使用 js 编写代码，请自行探究。
