### ISSUE TITLE
 umi3升级umi4

### ISSUE THREAD

**Issue by liujie3612** [umijs/umi#11941]
有很多项目是用的umi3开发，默认是router5，umi4用了router6 导致很多异常，我现在想用router5，看了reactRouter5Compat这个配置，但是依然没生效，为什么router5没做成插件让我自己决定何时使用呢？

![image](https://github.com/umijs/umi/assets/9972008/d4e477c9-30b3-4603-a287-bb32d49eba07)

**Comment by fz6m** [comment]
参考 [`reactRouter5Compat`](https://umijs.org/docs/api/config#reactrouter5compat) 的文档，这个功能只是为了让组件 props 带上以前一样的 `location` 等路由信息，只有这一个作用，一般会与 [`historyWithQuery`](https://umijs.org/docs/api/config#historywithquery) 同时使用。

如果你需要 `props.xxx` 上的路由信息和 `history.query` ，那就需要这两个选项，否则不需要；在使用时，需要注意边缘情况，详见文档说明。
