### ISSUE TITLE
[Bug] 使用webpack-assets-manifest插件时运行yarn start报错

### ISSUE THREAD

**Issue by JarvisArt** [umijs/umi#11948]
## What happens?

![image](https://github.com/umijs/umi/assets/38420763/d701f652-d0b5-48bf-bfa4-c2ed91775ca7)

![image](https://github.com/umijs/umi/assets/38420763/f959106c-0444-40ff-9192-01297641adec)

## Mini Showcase Repository(REQUIRED)
```ts
import { defineConfig } from '@umijs/max';
import WebpackAssetsManifest from 'webpack-assets-manifest';
import routes from './routes';

export default defineConfig({
  antd: {},
  access: {},
  model: {},
  initialState: {},
  request: {},
  routes,
  npmClient: 'yarn',
  manifest: false,
  chainWebpack(memo) {
    memo.plugin('webpack-assets-manifest').use(
      new WebpackAssetsManifest({
        output: '../assets/asset-manifest.json',
        writeToDisk: true,
        entrypoints: true,
        entrypointsUseAssets: true,
      }),
    );
  }
});
```

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
```ts
   memo.plugin('assets-manifest-plugin').use(
      require('webpack-assets-manifest')
   );
```
