### ISSUE TITLE
当前最新版本没有导出react-router的ScrollRestoration

### ISSUE THREAD

**Issue by kylvia** [umijs/umi#11940]
## Background

react-router的最新版本增加了些新的功能，希望umi能同步更新下~

**Comment by fz6m** [comment]
umi 4 是没法使用 data router 的方法的。

因为 react router v6 是不支持外置 history 的，所有的路由方法都需要通过 hook 调用，这有一些不便。

但 umi 4 为了兼容 umi 3 可以在任意地方使用 `history` 去操作路由，所以 hack 了 react router v6 的 `BrowserRouter` ，他和现在的 react router 中的 data router 不是一个东西。

下面简单介绍一下 data router 和 BrowserRouter 。

#### RR 简单介绍

现在的 react router v6 有 `BrowserRouter` 和 `createBrowserRouter` 两个东西，其中 `BrowserRouter` 是 v6.4 之前的路由，可以把它当成 legacy 路由，这就是 umi 4 现在使用的，其中 `createBrowserRouter` 是 v6.4 之后的路由，是现在默认推荐使用的路由创建方案，它也叫 data router ，现在所有的 react router v6 特性都是基于 data router 做的，所以 `ScrollRestoration` 等 data router only 的 api 是没法在 legacy 旧路由里用的，同时因为 data router 不支持外置 history ，所以是一个比较大的 Breaking change ，综合一些考量，umi 4 不会切换路由的类型到 data router 了。
