### ISSUE TITLE
[Feature Request] 能否在没有Access时不隐藏菜单？

### ISSUE THREAD

**Issue by EnochRen** [umijs/umi#11946]
## Background

目前在获取不到Antdpro和plugin-access配合下配置路由的access时，菜单会直接隐藏该项

## Proposal

不想隐藏，可以点击菜单项，点击后显示403页面

**Comment by fz6m** [comment]
不要配路由表的 `access` ，给路由增加一个 layout 或者 wrapper ，在这里面用 `<Access />` 或 `useAccess` 方法在运行时判断下有没有权限，如果要取路由表配置内容，可以用 [`useRouteProps`](https://umijs.org/docs/api/api#userouteprops) 或者 [`useSelectedRoutes`](https://umijs.org/docs/api/api#useselectedroutes) 方法来帮助你辅助判断。
