### ISSUE TITLE
umi4 不支持 sse流式请求 请求是 全量返回， 不是分段返回

### ISSUE THREAD

**Issue by beewolf233** [umijs/umi#11958]
## What happens?

使用umi4 
在做一个 chatGPt 聊天对话框  希望返回的信息是   sse 一点点返回过来的， 实际情况 全量返回

let server_url = 'http://192.168.56.105:8008'

/***
 * http请求(流式响应处理)
 * @param url
 * @param data
 * @param func
 * @returns {Promise<void>}
 */
请求方法如下
async function readChatbotReply(url,data={},func) {
    const response = await fetch(server_url+url, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json;charset=UTF-8',
        },
        timeout:15000,
        body: JSON.stringify(data)
    });

  const readableStream = response.body;
  if (readableStream) {
    const reader = readableStream.getReader();
    let first = true
    while (true) {
      const { value, done } = await reader.read();
      if (done) {
        break;
      }

      const chunkValue = new TextDecoder().decode(value);
      // 流式返回的信息，在这里处理您的业务
      func(first,chunkValue)
      first = false
    }
    // Stream fully consumed
    reader.releaseLock();
  }
}

由于 chatGpt接口 很私密， 这里 接口相关 无法给到，  sse调用方法如上， 在普通 index.html 中 是可以 使用成功的， 在umi4中， 只能全量返回 

index.html 代码如下
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Stream API Test</title>
<script>
async function sendPostRequestAndGetStream(url, token, body) {
  const headers = new Headers({
    'Logintoken': token,
    'Content-Type': 'application/json'
  });

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: headers,
      body: JSON.stringify(body)
    });

    if (!response.ok) {
      throw new Error(`Server returned status code ${response.status}`);
    }

    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    const output = document.getElementById('output');

    while (true) {
      const { value, done } = await reader.read();
      if (done) break;
      const text = decoder.decode(value);
      output.textContent += text;
    }
  } catch (error) {
    console.error('Fetch failed:', error);
    output.textContent += `\nError: ${error.message}`;
  }
}

function handleSubmit(event) {
  event.preventDefault();
  const url = document.getElementById('url').value;
  const token = document.getElementById('token').value;
  const content = document.getElementById('content').value;
  const body = {
    "scene": "COMMON_CHAT",
    "chatId": "1111111",
    "content": content
  };
  sendPostRequestAndGetStream(url, token, body);
}
</script>
</head>
<body>
<h1>Stream API Tester</h1>
<form id="streamForm" onsubmit="handleSubmit(event)">
    <label for="url">URL:</label>
    <input type="text" id="url" name="url" value="chatJpt链接 replace" required>
    <br><br>
    <label for="token">Login Token:</label>
    <input type="text" id="token" name="token" value="token replace" required>
    <br><br>
    <label for="content">Content:</label>
    <input type="text" id="content" name="content" required>
    <br><br>
    <button type="submit">Send Request</button>
</form>

<h2>Output:</h2>
<pre id="output"></pre>

</body>
</html>

**Comment by xiaohuoni** [comment]
@microsoft/fetch-event-source

**Comment by fz6m** [comment]
umi 框架只是提供了构建项目的功能，和你的代码逻辑无关。

关于 sse 、ws 等网络通信方式，它的处理方式和你的代码逻辑、使用的请求方式、请求库等有关，可自行学习相关文档进一步了解，或通过 gpt 、已有的参考项目等方式查询示例。

**Comment by fz6m** [comment]
关于 SSE 不能流式返回的问题，增加了一个 `UMI_DEV_SERVER_COMPRESS=none umi dev` 的环境变量来关闭影响 SSE 的压缩中间件，用于 SSE 的测试，预计在下个版本可用。

See #12144

**Comment by legend80s** [comment]
solution https://github.com/umijs/umi/issues/12144
