### ISSUE TITLE
[Bug] Umi4 qiankun使用antd中modal、notification、drawer的api创建功能切换应用后样式丢失且无法关闭

### ISSUE THREAD

**Issue by csic21** [umijs/umi#11951]
## What happens?

Umi4 qiankun使用antd中modal、notification、drawer的api创建功能切换应用后样式丢失且无法关闭，把sandbox关闭以后问题也会消失，使用umi3创建的项目没有这个问题，也不需要关闭sandbox。

补充说明umi版本关系：
主应用是umi3，子应用是umi4 没有这个问题
主应用是umi3，子应用是umi3 没有这个问题
主应用是umi4，子应用是umi4 问题发生
主应用是umi4，子应用是umi3 问题发生

![image](https://github.com/umijs/umi/assets/99160430/6bab3849-2d19-4a7e-be3e-5f7120364dc8)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/csic21/umi4-qiankun-demo

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

安装demo 并启动，点击按钮可以看到效果

## Context

- **Umi Version*4.0.89*:
- **Node Version*16*:
- **Platform*linux*:

**Comment by fz6m** [comment]
antd 5 已不在推荐使用全局的 notification / message 等方法，因为这些方法的上下文等存在问题，所以需要通过 `<App />` 包裹应用并且以 `App.useApp()` 的 hooks 方式来使用（ [参考文档](https://ant.design/components/app-cn) ），这可以通过如下方式：

```ts
// .umirc.ts

  antd: {
    configProvider: {},
    appConfig: {}
  },
```

```ts
import { Button, notification, App } from 'antd';
import styles from './index.less';

export default function IndexPage() {

  const app = App.useApp()

  return (
    <div>
      <h1 className={styles.title}>Page index</h1>
      <Button
        onClick={() => {
          app.notification.error({
            message: '123',
            description: '456',
            onClose: () => {
               // ...
            },
          });
        }}
      >
        go
      </Button>
    </div>
  );
}
```

来使用。

另外跳转路由不应该使用原生 history ，应该使用主应用的 history 做全局跳转，可以通过把主应用的 history 通过主子应用传值（详情参考文档）或挂载到全局，然后在子应用获取到来进行路由跳转，而不是使用原生 api 。
