### ISSUE TITLE
[Bug] srcTranspiler 使用Babel、esbuild的时候 会把antd-mobile的 css前缀去掉 

### ISSUE THREAD

**Issue by day-xue** [umijs/umi#11965]
## What happens?
srcTranspiler 使用Babel、esbuild的时候 会把antd-mobile的 css前缀去掉 
用swc正常

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
<img width="303" alt="image" src="https://github.com/umijs/umi/assets/95938844/bc649328-12b3-4f21-8860-2fda3aa676c9">
这个mask 我看antd-mobile 源码里面有 --webkit- 前缀 但是实际检查元素没有

现在我换成swc 就有了

<img width="316" alt="image" src="https://github.com/umijs/umi/assets/95938844/c7407645-d242-426f-b8d2-8efc65046c6b">

不是最新版的浏览器最初是不支持 mask这个属性 必须得加 前缀

想问问这是bug 还是转换器的问题 需要配置啥吗？ 

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
给一个最小复现看看，我在代码里编写的 mask 是保留了 `-webkit-mask` 的。

**Comment by day-xue** [comment]
> 给一个最小复现看看，我在代码里编写的 mask 是保留了 `-webkit-mask` 的。

我试了一下 发现了问题是mfsu的问题

<img width="576" alt="image" src="https://github.com/umijs/umi/assets/95938844/652a7b05-2651-40df-8122-99825ac4b09e">

**Comment by day-xue** [comment]
https://github.com/day-xue/umi-test

**Comment by day-xue** [comment]
@fz6m  麻烦看下 谢谢！！

**Comment by fz6m** [comment]
如果你使用了 esbuild 这种现代构建工具去加速开发和构建，意味着都是以现代浏览器为基准的，mask 本来在现代浏览器是可用的，所以会被去除，如果你要考虑兼容性问题，就不需要配置：

```diff
- srcTranspiler: "esbuild",
- mfsu: {
-   esbuild: true,
- },
```

去掉之后是有 `-webkit` 的：

<img src='https://github.com/umijs/umi/assets/59400654/61694fe3-b0bd-4b92-be35-6b2e254d28d1' width='40%' />

**Comment by day-xue** [comment]
> 如果你使用了 esbuild 这种现代构建工具去加速开发和构建，意味着都是以现代浏览器为基准的，mask 本来在现代浏览器是可用的，所以会被去除，如果你要考虑兼容性问题，就不需要配置：
> 
> ```diff
> - srcTranspiler: "esbuild",
> - mfsu: {
> -   esbuild: true,
> - },
> ```
> 
> 去掉之后是有 `-webkit` 的：
> 
> <img alt="" width="40%" src="https://private-user-images.githubusercontent.com/59400654/292537922-61694fe3-b0bd-4b92-be35-6b2e254d28d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0OTQ0NjIsIm5iZiI6MTcwMzQ5NDE2MiwicGF0aCI6Ii81OTQwMDY1NC8yOTI1Mzc5MjItNjE2OTRmZTMtYjBiZC00YjkyLWJlMzUtNmIyZTI1NGQyOGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA4NDkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYzQ3NTkxMmQ5MDFiNzdkY2FkOTNhODQyNjU3ODM1MDI0M2Q3NmNkMmU0MjJjODE2NDI1ZDFlNTQxNWUyNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ERwv5UWfYiHkD5yjT-Wcmt0nCjOFnhykzKqyBMN2kx4">

<img width="578" alt="image" src="https://github.com/umijs/umi/assets/95938844/6059e165-f7b1-4c4b-b6ed-be2eda58502a">
 mask这个 支持的最新版浏览器太少了。。。
