### ISSUE TITLE
[Bug] wsl 环境，clipboardy 有严重的性能问题

### ISSUE THREAD

**Issue by shengbeiniao** [umijs/umi#11967]
## What happens?

采用 wsl 开发时，搭建了一个最简单的 umi 项目，但启动的时候发现编译完，到开放端口监听，中间有接近3分钟的延时

![image](https://github.com/umijs/umi/assets/3301995/818d90ff-5c12-4745-89b2-250dc2d9be10)

debug umi 源码后发现，是 clipboardy 的问题，具体行数为
https://github.com/umijs/umi/blob/879d66cfd2945ef97416c86034f2a0a52130b4f0/packages/preset-built-in/src/plugins/commands/dev/devCompileDone/DevCompileDonePlugin.ts#L46-L47

顺着源码发现，umi 针对 clipboardy 用 Object.defineProperty 做了重新封装

![image](https://github.com/umijs/umi/assets/3301995/fd42b1bc-303b-4511-bca6-728f0b6a62d6)

这其中可能会导致性能问题

## Mini Showcase Repository(REQUIRED)

在 wsl 环境下写了个最小 test case，直接引用 clipboardy 没问题，但引用封装后的就会卡主

// const clipboardy = require('clipboardy')

const {clipboardy} = require('@umijs/utils')

clipboardy.writeSync('http://localhost:9000');

const result = clipboardy.readSync();

console.log(result)

## Context

- **Umi Version**: umi@3.5.41
- **Node Version**: v16.20.2
- **Platform**: WSL 环境，Ubuntu 22.04.3 LTS
![image](https://github.com/umijs/umi/assets/3301995/c56ed069-a1ab-4501-9cbb-f42e774f33d0)

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4 。
