### ISSUE TITLE
umi@2打包路由问题

### ISSUE THREAD

**Issue by Luxiaoshi** [umijs/umi#1197]
umi@1的时候，打包分为一个html文件和static文件夹，
但是升级到2后去除了static文件夹，导致所有的文件都在dist目录下了，
因此当我再像以前一样放入flask的static文件夹下时会产生路径不匹配的错误
![image](https://user-images.githubusercontent.com/8713879/46652010-6141af00-cbd4-11e8-9249-fc5631767db7.png)

而我希望的路径是localhost:5000/static/vendors.js
不知在umi.js这个文件中是否可以配置引用其他js文件时的路径

**Comment by yykoypj** [comment]
> umi@1的时候，打包分为一个html文件和static文件夹，
> 但是升级到2后去除了static文件夹，导致所有的文件都在dist目录下了，
> 因此当我再像以前一样放入flask的static文件夹下时会产生路径不匹配的错误
> ![image](https://user-images.githubusercontent.com/8713879/46652010-6141af00-cbd4-11e8-9249-fc5631767db7.png)
> 
> 而我希望的路径是localhost:5000/static/vendors.js
> 不知在umi.js这个文件中是否可以配置引用其他js文件时的路径

https://umijs.org/zh/config/#outputpath
