### ISSUE TITLE
[Feature Request] core-js need support es 2024

### ISSUE THREAD

**Issue by MissNanLan** [umijs/umi#11975]
## Background

目前[es 2024](https://github.com/tc39/proposals/blob/main/finished-proposals.md)出来了

<img width="1175" alt="image" src="https://github.com/umijs/umi/assets/22790863/e0605d43-7149-408a-ae53-9a7245b40f47">

而umi 4中的core-js版本是[3.28.0](https://github.com/zloirock/core-js/blob/v3.28.0/packages/core-js/package.json), 这个版本最高支持到es 2023

<img width="594" alt="image" src="https://github.com/umijs/umi/assets/22790863/7c83b11b-8a2a-46e9-a699-3ebfff54fd5d">

造成的问题是 只要使用了es 2024 的 api, 在低版本浏览器会报错

<img width="1198" alt="image" src="https://github.com/umijs/umi/assets/22790863/97119a09-6e60-40c7-9a8d-704a7eddf5c6">

## Proposal

1、升级 core-js的版本为[3.34.0](https://github.com/zloirock/core-js/releases/tag/v3.34.0)

2、[@babel/preset-env](https://www.babeljs.cn/docs/babel-plugin-transform-unicode-sets-regex) 也需要升级

**Comment by fz6m** [comment]
发布于 umi v4.1.0
