### ISSUE TITLE
[Bug] 暗黑主题下, 从黑色的加载页面切换到黑色的网站主页面时有一个白色的闪屏, 浅色主题也有但不明显

### ISSUE THREAD

**Issue by 21pages** [umijs/umi#11974]
## What happens?

使用的umi max和antd pro, 暗黑主题下, 从黑色的加载页面切换到黑色的网站主页面时有一个白色的闪屏, 浅色主题也有但不明显, 黑色的加载页面是通过 headScripts: [{ src: '/scripts/loading.js', async: true }], 设置的.

## Mini Showcase Repository(REQUIRED)

最小示例 https://github.com/21pages/umimax-antdpro-dark-theme-loading-transition-whitescreen-splash 这个示例是用https://umijs.org/docs/max/introduce 创建, 仅添加了加载页, 并修改主题为黑色, https://github.com/21pages/umimax-antdpro-dark-theme-loading-transition-whitescreen-splash/commit/0403d6bafb8d346b875e426afd38427bb149e03b

https://github.com/umijs/umi/assets/14891774/2a4089eb-4c1d-418a-969d-7ec4177fe925

## How To Reproduce

**Steps to reproduce the behavior:** 
1. 运行示例代码
2. 刷新浏览器网页

**Expected behavior** 
没有白色的闪屏

## Context

- **Umi Version**:
  "dependencies": {
    "@ant-design/icons": "^5.0.1",
    "@ant-design/pro-components": "^2.4.4",
    "@umijs/max": "^4.0.89",
    "antd": "^5.4.0"
  },
- **Node Version**: v18.16.0
- **Platform**: windows 11

**Comment by fz6m** [comment]
按照你这个项目里，加载流程是：

1. 展示你的 `loading.js` 内容（黑色）→ 

2. 你的 `loading.js` 内容被 react 去除准备创建节点，这个瞬间展示的是空的 body → 

3. react 开始创建节点，懒加载应用，展示 `src/loading.tsx` 加载组件 → 

4. 懒加载结束，展示真正的应用内容

可以看到虽然 1 / 4 是黑色的背景，但 2 / 3 不是，所以要让 2 / 3 里的背景也是黑的，考虑手动给 body 变黑：

```ts
// .umirc.ts

  // https://umijs.org/docs/api/config#styles
  styles: [
    'body { background: #000; }'
  ],
```

这样就可以了，3 中的加载组件是 `src/loading.tsx` ，这是应用内的通用加载组件，有没有都可以，如果你需要的话就自己弄一个让他背景是黑的。

**Comment by rustdesk** [comment]
谢谢，解释得有条有理
