### ISSUE TITLE
[Bug] 我配了一个pro的环境，为了切换测试和生产地址，yarn start:dev 没问题，yarn start:pro 就出问题了

### ISSUE THREAD

**Issue by taofeifanIT** [umijs/umi#11979]
## What happens?
我配了一个pro的环境，为了切换测试和生产地址，yarn start:dev 没问题，yarn start:pro 就出问题了
fatal - Error: Invalid command pro, it's not registered.

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

![image](https://github.com/umijs/umi/assets/42193371/dd6d8613-49fb-44a3-9807-e8a3c022f3f5)
![image](https://github.com/umijs/umi/assets/42193371/76474ab4-e8ac-4c13-9b61-29a568d41a9a)
![image](https://github.com/umijs/umi/assets/42193371/dacdc78d-1f0d-4ffb-8cac-970a953619f3)

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by day-xue** [comment]
只设置UMI_ENV 就可以读取config.pro.ts 文件了

**Comment by taofeifanIT** [comment]
> 只设置UMI_ENV 就可以读取config.pro.ts 文件了

![image](https://github.com/umijs/umi/assets/42193371/448acd49-52ed-416a-9961-e894d8412e06)
感谢，我这样写确实就可以了

**Comment by taofeifanIT** [comment]
![image](https://github.com/umijs/umi/assets/42193371/0d3212a7-efba-43f5-b23b-b7127fac4af8)
改成这种格式虽然不报错了，但是启动的项目还是dev环境

**Comment by taofeifanIT** [comment]
> 只设置UMI_ENV 就可以读取config.pro.ts 文件了

大佬，还在吗，可以给个写法吗

**Comment by fz6m** [comment]
你说的环境是指哪个环境。

如果你希望区分不同的环境有不同的全局变量，通过不同的 `UMI_ENV` 值来启动项目：

```bash
  cross-env UMI_ENV=pro umi dev
```

这会使用 `config.dev.${UMI_ENV}.ts` （ 此处是 `config.dev.pro.ts` ）这个配置文件的配置，并且和 `config.dev.ts` 的配置经过合并后，得到最终配置，假如你在开发环境 `dev` 下有：

```ts
// config.dev.ts

  define: { SOME_VAR: 'dev' }
```

那么我可以在 `config.dev.pro.ts` 中设定：

```ts
// config.dev.pro.ts

  define: { SOME_VAR: 'pro' }
```

这样就可以做到在以 pro 环境启动时，这个全局变量 `SOME_VAR` 的值跟随环境改变了，因为 `config.dev.pro.ts` 配置的优先级更高，关于配置优先级 [查看这里](https://umijs.org/docs/guides/env-variables#umi_env) 。

注：`umi dev` 这个命令其实就是 `UMI_ENV=dev umi dev` ，一般我们通过不同的 `UMI_ENV` 命令行参数来启动不同的环境，从而加载不同的配置。
