### ISSUE TITLE
 ERROR: The JSX syntax extension is not currently enabled

### ISSUE THREAD

**Issue by kudenv** [umijs/umi#11971]
## What happens?

While defining srcTranspiler: 'esbuild', and turning on it in mfsu : {esbuild: true}
.js files is stil not compiled 

Module build failed (from ./node_modules/@umijs/mfsu/dist/loader/esbuild.js):
Error: Transform failed with 1 error:
*.e.js: 22:4: ERROR: The JSX syntax extension is not currently enabled
## Mini Showcase Repository(REQUIRED)

in .umijs file 
const __config__ = { 
 mfsu: {
    esbuild: true   
  },
  srcTranspiler: 'esbuild',
srcTranspilerOptions: {
    esbuild: {                    
        loader: {
            'js': 'jsx',    
        },
        jsx: 'automatic'    
    }
  }
}

then

yatn dev 

any default project from scalfolding 
**Expected behavior** 1. 2.

expected what *.js files will be transpiled 
like .\node_modules\.bin\esbuild ./pages/page.js --bundle --loader:.js=jsx
## Context
package json file
{
  "private": true,
  "author": "",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git+"
  },
  "version": "0.0.1",
  "scripts": {
    "dev": "max dev",
    "build": "max build",
    "postinstall": "max setup",
    "setup": "max setup",
    "start": "npm run dev"
  },
  "dependencies": {   
    "classnames": "^2.3.2",
    "react-icons": "^4.12.0"   
  },
  "devDependencies": {        
    "@ant-design/icons": "^5.2.6",
    "@types/react": "^18.2.37",
    "@types/react-dom": "^18.2.15",
    "@umijs/max": "^4.0.88",
    "antd": "^5.11.1",
    "mockjs": "^1.1.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "rimraf": "^5.0.5"
  },
  "lint-staged": {
    "*.{js,jsx,css,less}": [
      "max lint --fix",
      "git add"
    ]
  }
}

**Comment by fz6m** [comment]
If you want to write `React JSX Element`, the file must end with `.jsx` / `.tsx` ( not `.js` )
