### ISSUE TITLE
[Bug] getDvaApp returns undefined

### ISSUE THREAD

**Issue by hasakilol** [umijs/umi#11985]
## What happens?

`getDvaApp()` in app.ts returns `undefined`

my config is like:

{
  dva: {},
  initialState: {},
  model: {},
  layout: {},
  ...
}

In app.ts `getInitialState()`, I want to dispatch some action. So I called `getDvaApp()`, but it returns `undefined`.

## Context

- **Umi Version**: 4.0.89
- **Node Version**: 16

**Comment by fz6m** [comment]
没法在 `getInitialState` 里使用 `getDvaApp` ，因为 initial state 的 context 层级高于 dva 的 context 层级，这个时候 dva 还没初始化。
