### ISSUE TITLE
[Feature Request] getDvaApp() returns undefined

### ISSUE THREAD

**Issue by hasakilol** [umijs/umi#11987]
What happens?
my config is like:

{
dva: {},
initialState: {},
model: {},
layout: {},
...
}

In app.ts getInitialState(), I want to dispatch some action. So I called getDvaApp(), but it returns undefined.

In app.ts getInitialState(), I want to dispatch some action. So I called getDvaApp(), but it returns undefined.

Mini Showcase Repository(REQUIRED)
No need.

Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

How To Reproduce
Steps to reproduce the behavior: 1. 2.

npm create umi
In app.ts, call getDvaApp()
Expected behavior 1. 2.
getDvaApp() is not undefined.

Context
Umi Version: 4.0.89
Node Version: 16
Platform: win 10

**Comment by fz6m** [comment]
See #11985
