### ISSUE TITLE
[Feature Request] allow to search layout menu

### ISSUE THREAD

**Issue by hasakilol** [umijs/umi#11999]
## Background

umi seems not supporting searching menu according to user input. It's not efficient when there are many menus in the layout.

## Proposal

allow to filter menus according to user input.

## Additional context

![Snipaste_2023-12-25_17-21-25](https://github.com/umijs/umi/assets/46310359/67db01d1-a1e3-4805-b40a-3257bec0dec9)

**Comment by fz6m** [comment]
这个 layout 只是为了符合快速开发的需要提供的默认预设，他的本质是 [pro components](https://procomponents.ant.design/) 中的 `<ProLayout />` ，如果你需要搜索菜单等更高级的功能，就自己完整的编写自己的 layout 布局吧，不要开启 `layout: {}` 这个功能，然后自己根据路由表构造菜单，位置在 `src/layouts/index.ts` ，可以参考 `src/.umi/plugin-layout/*` 中的内容和 api 来编写，或者自己写成插件都可以。
