### ISSUE TITLE
[Feature Request] useNavigationType is not export 

### ISSUE THREAD

**Issue by Pulset** [umijs/umi#11996]
## Background

I want to get navigationType by useNavigationType.But umi don't export useNavigationType from react-router 
## Proposal

export useNavigationType from react-router

**Comment by fz6m** [comment]
如果你需要这个，你可以直接安装 `react-router-dom` 然后导入（仅用来提示类型，和版本号无关），umi 会自动把 react-router 和 react-router-dom 通过 alias 定位到内部自己锁定版本的路由依赖，所有可以从 umi 导入的 react-router-dom 方法也都是 re export 而已。

**Comment by Pulset** [comment]
> 如果你需要这个，你可以直接安装 `react-router-dom` 然后导入（仅用来提示类型，和版本号无关），umi 会自动把 react-router 和 react-router-dom 通过 alias 定位到内部自己锁定版本的路由依赖，所有可以从 umi 导入的 react-router-dom 方法也都是 re export 而已。

我安装了react-router-dom 6.22.3版本，但是提示没有导出useNavigation。是不是umi内部把react-router-dom的版本锁了？

**Comment by fz6m** [comment]
可以改 `react-router-dom` 的版本，只要自己加一下 `react-router` / `react-router-dom` 的 alias 就好了。

我看了下，你提到的 [`useNavigation`](https://reactrouter.com/en/main/hooks/use-navigation) 的这个 api ，是 data router 专用的，即使改了 `react-router-dom` 的版本也是用不了的。umi 4 因为要外置 history ，所以用的不是 data router ，是老式的 browser router ，因为 react router v6 把 history 这个概念砍掉了，但 umi 3 里是有全局 history 可以任意跳转路由的，为了让升级 umi 4 更方便，所以还是保留了 history ，采用的 react router v6 的 browser router + hack history 的方式，所以 data router 的特性以及 api 都是用不了的。

**Comment by Pulset** [comment]
所以你们不打算引入 data router 了，是吗

**Comment by fz6m** [comment]
因为无法较好的外置 history ，所以从技术上是无法更换 Data router 的。

在 umi 3 到 umi 4 的升级过程中，把 react router 从 v5 升级成了 v6 ，但 v6 相较 v5 变化很大（比如 history 、data router、嵌套子路由、配置选项等），这给很多项目造成了升级困难，经过较长的时间后（到 2023 年），综合来看把 react router 升级为 v6 是有些失败，不满足预期的。

之后在 umi 5 的研发中可能不会使用 react router 了，或者继续保留相同的 react router ，因为路由的改动对项目升级时的影响太大了，加上近年来 react router 已经完全沦为了 remix 的附属品，全部为 remix 服务，几乎不再迭代大众级别的特性了，早期在预加载方面新增的各种 loader 使用起来也没有那么灵活，功能上不如 tanstack router ，加上更多人转投 nextjs 和 RSC ，未来 react router 应该是会走下坡路的，存在地位会不断下降。

同时，由于 SPA 的数据加载优化是非常有限的，react router 提供的 data router 预加载用法也比较限制，最终都会造成瀑布请求，所以如果希望提升性能或者加载速度，使用 nextjs 和 RSC 才是大势。
