### ISSUE TITLE
patchClientRoutes 动态路由问题

### ISSUE THREAD

**Issue by TigerSong45** [umijs/umi#11997]
## 背景
您好，我当前需要实现动态路由的配置。我发现，如果未在config.ts中配置路由，框架会自动根据pages目录生成一套路由。这种情况下，只要输入存在的路由，浏览器就可以正常访问。我尝试在配置文件中给routes赋值[]。此时我在patchClientRoutes方法中动态赋值给routes，菜单能够正常显示，但对应的页面却报错“Noroutes matched location "/***"”。原因在于patchClientRoutes返回的routes中只有一个routes。没有对应的children，页面就无法正常显示。麻烦帮忙解答一下如何解决该问题。
![image](https://github.com/umijs/umi/assets/34497983/146f4b39-b35b-45ed-8ff5-ae35732a87d3)

**Comment by fz6m** [comment]
[`patchClientRoutes`](https://umijs.org/docs/api/runtime-config#patchclientroutes-routes-) 是一个在运行时修改路由表的功能，在修改的时候要符合一定的格式才行，你可以先自己配一些嵌套路由看一下数据结构，然后参照着构造出来 patch 进去就行。

**Comment by Arima-s** [comment]
自己构造这个结构 不好使啊。。官方能贴点demo或者 给一些方法暴露出来吗？
![20240807-172051](https://github.com/user-attachments/assets/709e60b3-3793-4a12-8e4c-4c3975c91498)
