### ISSUE TITLE
[Bug] [Bug]umi-max 集成 @umijs/max-plugin-openapi 插件报错如：Cannot read properties of undefined (reading 'version') 

### ISSUE THREAD

**Issue by zhaoming1995** [umijs/umi#11998]
### 添加了umi-openapi插件，之后运行pnpm openapi，报错如下

D:\workbench\Admin-Sys\demo>pnpm openapi

> demo@v1 openapi D:\workbench\Admin-Sys\demo
> max openapi

Using openapi Plugin
D:\workbench\Admin-Sys\demo\node_modules\.pnpm\@umijs+openapi@1.9.4\node_modules\@umijs\openapi\dist\serviceGenerator.js:231
        this.version = info.version;
                            ^

TypeError: Cannot read properties of undefined (reading 'version')
    at new ServiceGenerator (D:\workbench\Admin-Sys\demo\node_modules\.pnpm\@umijs+openapi@1.9.4\node_modules\@umijs\openapi\dist\serviceGenerator.js:231:29)
    at D:\workbench\Admin-Sys\demo\node_modules\.pnpm\@umijs+openapi@1.9.4\node_modules\@umijs\openapi\dist\index.js:71:30
    at Generator.next (<anonymous>)
    at fulfilled (D:\workbench\Admin-Sys\demo\node_modules\.pnpm\tslib@2.6.2\node_modules\tslib\tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.17.0
 ELIFECYCLE  Command failed with exit code 1.

求助如何解决?

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## package.json
  "dependencies": {
    "@ant-design/charts": "^2.0.3",
    "@ant-design/icons": "^5.2.6",
    "@ant-design/pro-components": "^2.6.43",
    "@umijs/max": "^4.0.89",
    "@umijs/max-plugin-openapi": "^2.0.3",
    "antd": "^5.12.3",
    "swagger-ui-dist": "^5.10.5"
  },
## Context

- **Umi Version**:
- 4.0.89
- **Node Version**:
- v18.17.0
- **Platform**:

**Comment by fz6m** [comment]
max openapi 的源码在这个 [仓库](https://github.com/umijs/umi-presets-pro/tree/master/packages/max-plugin-openapi/src) ，可以自己去看下源码位置是缺少了什么，貌似这个插件需要你的 `package.json` 中有 `name` 和 `version` 。

**Comment by zyk2891** [comment]
我也遇到了

**Comment by MeetYifan** [comment]
使用 @umijs/openapi 库也发现类似报错，断点调试发现如果 **authorization** 为 `undefined` 时请求会异常。

1. 可以在配置文件 `openapi2ts.config.ts` 或者 `.openapi2tsrc.ts` 中主动设置 `authorization: ''`；
2. 修改源码，地址 @umijs/openapi/dist/indexjs：
2.1. 可以给方法参数以默认值：`const getSchema = (schemaPath, authorization = '') => {}`；
2.2. 或者修改方法内 header 声明：`const header = authorization ? { authorization } : {}` 。

**Comment by xinqisong** [comment]
看一下后台的文档是否开启外部访问

![Image](https://github.com/user-attachments/assets/fa8959ee-50db-4833-9ab8-38c3cc3e192d)
