### ISSUE TITLE
[Bug]  ssr 模式下 使用 plugin-locale 错误

### ISSUE THREAD

**Issue by draco-china** [umijs/umi#11990]
## What happens?

umi 4 启用 @umijs/plugins/dist/locale  配置会出现以下错误

TypeError: Cannot read properties of null (reading 'applyPlugins')

## How To Reproduce

.umirc.ts 配置
```ts
export default defineConfig({
  ssr: {},
  locale: {
    antd: false,
    baseNavigator: false,
    baseSeparator: '-',
    default: 'zh-CN',
    title: true,
    useLocalStorage: false,
  },
  plugins: [
    '@umijs/plugins/dist/locale',
  ],
});

```
错误日志
![image](https://github.com/umijs/umi/assets/22271474/218d8f84-b0e2-4c6a-9621-b96cae474f44)

## Context

- **Umi Version**: 4.090
- **Node Version**: v18.19.0
- **Platform**: Windows 11

**Comment by fz6m** [comment]
ssr 是一项实验性功能，不能与其他 umi 插件一起使用，如你有需要 ssr 的场景，建议使用 nextjs 。
