### ISSUE TITLE
[Bug] git commit 控制台报错  Environment key "es2022" is unknown

### ISSUE THREAD

**Issue by gt-hanyao** [umijs/umi#12005]
## What happens?

报错信息
Oops! Something went wrong! :(

ESLint: 7.32.0

Error: .eslintrc.js » /Users/mac/项目目录/node_modules/@umijs/max/eslint.js:
        Environment key "es2022" is unknown

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your 

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

删除node_modules重新 npm install 之后，再提交代码，被husky - pre-commit hook拦截了

## Context

- **Umi Version**: 4.0.88
- **Node Version**: 16.20.2
- **Platform**: macOs

**Comment by fz6m** [comment]
如有问题，需要给一个完整的最小复现仓库和操作步骤。
