### ISSUE TITLE
[Bug] umi3.x如何生产环境使用mock

### ISSUE THREAD

**Issue by Yokee-X** [umijs/umi#12009]
### umi3.x如何在生产环境使用mock数据？
想在生产环境上做演示，请求接口报错，而是请求资源的形式

**Comment by fz6m** [comment]
要不你把 mock 数据的逻辑抽取出来一起复用，在演示的时候起一个 express 服务提供 mock 接口就行。

umi 3 不维护了，建议升级到 umi 4 。
