### ISSUE TITLE
[Bug] qiankun 父应用如何给子应用同步数据。

### ISSUE THREAD

**Issue by consistent-k** [umijs/umi#12006]
```js
// src/app.ts
export function useQiankunStateForSlave() {
  const [globalState, setGlobalState] = useState<any>({
    slogan: 'Hello MicroFrontend',
  });

  return {
    globalState,
    setGlobalState,
  };
}
```
使用官方这段代码进行父子应用通信，求问在父应用其他页面中，如何能调用这里的函数 将异步请求的数据设置给子应用。

**Comment by fz6m** [comment]
他本质上是一个 umi 中的数据流 model ，可以用 `useModel('@@qiankunStateForSlave')` 取到，然后修改，这个 model 是持久的。

**Comment by wuhanjun** [comment]
> 他本质上是一个 umi 中的数据流 model ，可以用 `useModel('@@qiankunStateForSlave')` 取到，然后修改，这个 model 是持久的。

如果子应用不是使用umi，怎么获取父应用数据的更新？子应用中监听onGlobalStateChange并没有触发

**Comment by fz6m** [comment]
如果子应用不是 umi ，就使用 qiankun 原生的方法加载即可，和独立使用 qiankun 一个道理，比如用 `loadMicroApp` 加载子应用，然后在 props 里传给子应用数据，具体方法查看 qiankun 文档吧，这种情况就和 umi 无关了。

不想走 qiankun props 传递的话，或者通过全局总线做订阅更新也行。
