### ISSUE TITLE
Umi Max 中的errorConfig里面的 errorHandler 与 errorThrower

### ISSUE THREAD

**Issue by zhumeng2019s** [umijs/umi#12014]
![image](https://github.com/umijs/umi/assets/53611371/37762635-a3b6-4875-88e1-a1e2e8d26005)
### 首先没太理解这段文字  
![image](https://github.com/umijs/umi/assets/53611371/fa4f7e3e-9075-4b5d-95ca-72f9406ed9a4)
### 代码里面  success 设置成  false 来触发 errorThrower 
![image](https://github.com/umijs/umi/assets/53611371/bf800b59-3fba-4145-b79f-24eb07e90d11)
![image](https://github.com/umijs/umi/assets/53611371/a61a155e-463d-4858-8be3-291180ead307)
### 修改完成后  errorThrower  加上 throw error。 
![image](https://github.com/umijs/umi/assets/53611371/497503af-6a38-4668-96c2-950c1294549d)

**Comment by yycang** [comment]
我也遇到了，我用的useRequest，当加上throwOnError: true时errorHandler就没法捕获到错误

btw，umi max中的useRequest包还是2年前的2.8.15版本，可不可以更新一下

**Comment by fz6m** [comment]
现在 umi 4 中的 request 是为了延续 umi 3 升级而保留的上古功能，现代数据流不推荐使用 use request 、dva ，而使用 [jotai](https://github.com/pmndrs/jotai) / [valtio](https://umijs.org/docs/max/valtio) 管理全局状态，[react-query](https://github.com/TanStack/query) / [swr](https://github.com/vercel/swr) 管理请求状态。

**Comment by guomingchao-booker** [comment]
> 现在 umi 4 中的 request 是为了延续 umi 3 升级而保留的上古功能，现代数据流不推荐使用 use request 、dva ，而使用 [jotai](https://github.com/pmndrs/jotai) / [valtio](https://umijs.org/docs/max/valtio) 管理全局状态，[react-query](https://github.com/TanStack/query) / [swr](https://github.com/vercel/swr) 管理请求状态。

问题你这个和umi3效果也不一致啊，那保留他有啥意义，文档上写的实际都跑不起来
