### ISSUE TITLE
[Bug]umi3.x如何生产环境使用mock

### ISSUE THREAD

**Issue by Yokee-X** [umijs/umi#12010]
## What happens?

umi3如何在生产环境使用mock数据

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

这个是生产环境，请求api时更像是请求资源地址
![image](https://github.com/umijs/umi/assets/66291693/b4ccb1d3-15a6-4bfa-bea0-914f8bbc2fd2)
这个是开发环境
![image](https://github.com/umijs/umi/assets/66291693/4418c9a2-ee45-4ef0-9fda-7c70436d15ee)

## Context

- **Umi Version**:3.5.17
- **Node Version**:16.19.0
- **Platform**:React17

**Comment by fz6m** [comment]
See #12009
