### ISSUE TITLE
从服务端请求的菜单 可以实现redirect 功能吗 或者提供个demo 

### ISSUE THREAD

**Issue by ssjshengjie** [umijs/umi#12016]
![image](https://github.com/umijs/umi/assets/56914431/bf558a11-5ae5-481a-ad23-22dbfb0d1586) 模拟从后端请求路由 redirect 无法使用

**Comment by fz6m** [comment]
如果需要在应用运行时动态添加路由，推荐使用 [`patchClientRoutes`](https://umijs.org/docs/api/runtime-config#patchclientroutes-routes-) 方法，代码可参考 https://github.com/umijs/umi/discussions/9717#discussioncomment-4078053 ，在 patch 时，可以自己修改路由展示什么内容，如果需要重定向，就展示一个 `<Redirect />` 即可（从 `umi` 导入） 。

**Comment by ssjshengjie** [comment]
![image](https://github.com/umijs/umi/assets/56914431/0c78d7d8-56ea-497a-9adc-f1333f48256d)
大佬 我这边是用的 mix 模式  切割菜单 我想实现 点击一级菜单 跳到 二级菜单下 目前 我是用patchClientRoutes 没有办法 判断这个重定向有没有权限

**Comment by fz6m** [comment]
在上文我给的代码例子里，应用启动时先去请求接口获取到这个用户所有的有权限的路由表，然后 patch 修改路由菜单，这样得到的都是这个用户有权限的菜单，所以需要自行事先把这个用户拥有的权限先确定好再在 patch 时过滤掉。
