### ISSUE TITLE
[Bug]  URL scheme "webpack" is not supported.

### ISSUE THREAD

**Issue by yiyi17** [umijs/umi#12024]
## What happens?
![image](https://github.com/umijs/umi/assets/25927480/9a284b6e-b343-4f2f-a1a9-3e092d7f4437)

##

在 config 中导出了新的变量,然后其他组件使用即可复现

```js

export const PROJECT_NAME = 'xxx-webapp';

export default defineConfig({})

```

## Context

umi4

## 补充
测试了 webpack 中是支持从配置文件引用一个变量的，这块是 umi 处理的原因？

**Comment by yiyi17** [comment]
测试了 webpack 中是支持从配置文件引用一个变量的，这块是 umi 处理的原因？

**Comment by fz6m** [comment]
项目中 `src/*` 的代码运行环境是 browser 浏览器，而本地 umi 相关的配置文件运行环境是 node cjs ，他们无法公用，除非你把需要公用的变量提取成纯的单独一个文件，然后让两者都导入这个文件（比如在配置文件和项目中共享路由表，提取一份纯的 `routes.ts` ）。

**Comment by yiyi17** [comment]
`项目中 src/* 的代码运行环境是 browser 浏览器`

umi项目中 config 下的除了 config.ts 其他也是浏览器环境可用的，

只有 config.ts 这个文件不能被共用，是 umi 对这个文件有什么特殊的处理吗？

我测试了 webpack 打包会进行直接的把变量转为值，umi 做不到的原因是什么呢？

**Comment by fz6m** [comment]
`config/config.ts` 与根目录下的 `.umirc.ts` 是 umi 的配置文件，只能运行在 node 的 cjs 中，不可以运行在 browser 浏览器中，如果需要将某文件的配置共享到 node 与 browser ，参考上文中的回复将其抽取为一份纯的文件再在两边导入即可。
