### ISSUE TITLE
build打包配置codeSplitting无效

### ISSUE THREAD

**Issue by yangjiaqiao** [umijs/umi#12022]
## What happens?
在项目中config.ts文件中，增加分包策略配置：`codeSplitting: { jsStrategy: "granularChunks" }`。但是打包后的结果并没有进行分包，是需要注意什么问题吗？打包出来的umi.js文件也很大。
![image](https://github.com/umijs/umi/assets/51978469/6a2eb3ec-61f1-4ff2-84a1-7726e50f3cab)
配置文件配置代码： 
![image](https://github.com/umijs/umi/assets/51978469/1cfd7562-0678-48fc-86a8-24c6987704e0)

## Context
- **Umi Version**: 4.0.69
- **Node Version**: v18.18.0

**Comment by MissNanLan** [comment]
https://github.com/umijs/umi/discussions/11884 可以参考这个

**Comment by fz6m** [comment]
这要看你是不是在入口或者全局上共用引入了某些较大的依赖，比如组件库、编辑器、图标库、过多的 i18n 文件等，可以使用 [`ANALYZE=1`](https://umijs.org/docs/guides/env-variables#analyze) 来分析下打包产物组成，如果是第三方库导致的，延后到具体使用的页面懒加载即可，或者这个库就是很大需要每个页面都使用到（如组件库），如果是 i18n ，可以参考楼上的评论。

**Comment by fz6m** [comment]
`ANALYZE` 是一个环境变量，当存在这个环境变量的时候就会开启分析打包产物的功能，运行以下命令即可：

```bash
  ANALYZE=1 pnpm max build
```

或者新增一个：

```ts
// package.json

  "scripts": {
    "build:analyze": "ANALYZE=1 max build"
  }
```

如果你是 windows ，则需要使用 `cross-env ANALYZE=1 ...` 。

**Comment by zxq08** [comment]
> `ANALYZE` 是一个环境变量，当存在这个环境变量的时候就会开启分析打包产物的功能，运行以下命令即可：
> 
> ```shell
>   ANALYZE=1 pnpm max build
> ```
> 
> 或者新增一个：
> 
> ```ts
> // package.json
> 
>   "scripts": {
>     "build:analyze": "ANALYZE=1 max build"
>   }
> ```
> 
> 如果你是 windows ，则需要使用 `cross-env ANALYZE=1 ...` 。

感谢，使用大佬提供的命令确实可以。但是遇到了新问题

**Comment by fz6m** [comment]
参考 [代码拆分指南](https://umijs.org/blog/code-splitting) 手动拆分部分较大的依赖（如编辑器、图表等，按需加载），或将部分库变为 external umd 加载（如 react 、react-dom、图表库 echarts 等）。

如有问题，需要给一个最小复现。

**Comment by linhf123** [comment]
我想打包成一个 umijs 和 umicss，但是使用下面两种配置关闭 `splitChunks` 都没生效，可以帮忙看一下吗 @fz6m 
![image](https://github.com/user-attachments/assets/11c5e359-0f4b-436a-a41c-cdcf87cf9f74)
