### ISSUE TITLE
[Bug] build error why？try install  dayjs

### ISSUE THREAD

**Issue by Sumxx** [umijs/umi#12020]
info  - Memory Usage: 647.41 MB (RSS: 760.86 MB)
fatal - Error: ERROR in ./node_modules/.pnpm/@ant-design+pro-utils@2.15.1_antd@5.12.5_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/pro-utils/es/conversionMomentValue/index.js 3:0-55
Module not found: Error: Can't resolve 'dayjs/plugin/quarterOfYear' in 'E:\um\node_modules\.pnpm\@ant-design+pro-utils@2.15.1_antd@5.12.5_react-dom@18.2.0_react@18.2.0\node_modules\@ant-design\pro-utils\es\conversionMomentValue'
 @ ./node_modules/.pnpm/@ant-design+pro-utils@2.15.1_antd@5.12.5_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/pro-utils/es/index.js 8:0-97 52:0-56:151 52:0-56:151 52:0-56:151 52:0-56:151
 @ ./node_modules/.pnpm/@ant-design+pro-layout@7.17.15_antd@5.12.5_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/pro-layout/es/ProLayout.js 10:0-120 174:28-46 284:16-29 401:2-18 460:20-35 524:18-27
 @ ./node_modules/.pnpm/@ant-design+pro-layout@7.17.15_antd@5.12.5_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/pro-layout/es/index.js
 @ ./src/layouts/index.tsx 1:0-51 10:27-36
 @ ./src/.umi-production/core/route.tsx 81:23-101
 @ ./src/.umi-production/umi.ts 11:0-41 28:17-26

ERROR in ./node_modules/.pnpm/@ant-design+pro-utils@2.15.1_antd@5.12.5_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/pro-utils/es/parseValueToMoment/index.js 2:0-63
Module not found: Error: Can't resolve 'dayjs/plugin/customParseFormat' in 'E:\um\node_modules\.pnpm\@ant-design+pro-utils@2.15.1_antd@5.12.5_react-dom@18.2.0_react@18.2.0\node_modules\@ant-design\pro-utils\es\parseValueToMoment'
 @ ./node_modules/.pnpm/@ant-design+pro-utils@2.15.1_antd@5.12.5_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/pro-utils/es/index.js 40:0-55 52:0-56:151
 @ ./node_modules/.pnpm/@ant-design+pro-layout@7.17.15_antd@5.12.5_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/pro-layout/es/ProLayout.js 10:0-120 174:28-46 284:16-29 401:2-18 460:20-35 524:18-27
 @ ./node_modules/.pnpm/@ant-design+pro-layout@7.17.15_antd@5.12.5_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/pro-layout/es/index.js
 @ ./src/layouts/index.tsx 1:0-51 10:27-36
 @ ./src/.umi-production/core/route.tsx 81:23-101
 @ ./src/.umi-production/umi.ts 11:0-41 28:17-26
    at finalCallback (E:\um\node_modules\.pnpm\@umijs+bundler-webpack@4.0.88_typescript@5.2.2_webpack@5.89.0\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:62945:32)
    at E:\um\node_modules\.pnpm\@umijs+bundler-webpack@4.0.88_typescript@5.2.2_webpack@5.89.0\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:62962:13
    at Hook.eval [as callAsync] (eval at create (E:\um\node_modules\.pnpm\@umijs+bundler-utils@4.0.88\node_modules\@umijs\bundler-utils\compiled\tapable\index.js:1:7682), <anonymous>:35:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\um\node_modules\.pnpm\@umijs+bundler-utils@4.0.88\node_modules\@umijs\bundler-utils\compiled\tapable\index.js:1:4851)
    at onCompiled (E:\um\node_modules\.pnpm\@umijs+bundler-webpack@4.0.88_typescript@5.2.2_webpack@5.89.0\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:62960:21)
    at E:\um\node_modules\.pnpm\@umijs+bundler-webpack@4.0.88_typescript@5.2.2_webpack@5.89.0\node_modules\@umijs\bundler-webpack\compiled\webpack\index.js:63704:17
    at _next0 (eval at create (E:\um\node_modules\.pnpm\@umijs+bundler-utils@4.0.88\node_modules\@umijs\bundler-utils\compiled\tapable\index.js:1:7682), <anonymous>:16:1)
    at eval (eval at create (E:\um\node_modules\.pnpm\@umijs+bundler-utils@4.0.88\node_modules\@umijs\bundler-utils\compiled\tapable\index.js:1:7682), <anonymous>:26:1)
fatal - A complete log of this run can be found in:
fatal - E:\um\node_modules\.cache\logger\umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
 ELIFECYCLE  Command failed with exit code 1.

**Comment by fz6m** [comment]
因为 pnpm 是防止幽灵依赖的，所以如果你没显示安装 dayjs ，手动安装下。

如果已经安装了，需要看下你的写法问题，如还有问题，需要给一个最小复现。

**Comment by fz6m** [comment]
如果有问题，需要给一个最小复现。

看你的日志是 `@ant-design/pro-utils` 这个包的问题，要找下为啥依赖了他，找到他的源头，可以试试 `pnpm why @ant-design/pro-utils` ，找到直接依赖之后尝试升级下依赖版本（可能是 pro component 依赖的），如果还不行就去 [ant pro component](https://github.com/ant-design/pro-components) 的仓库反馈。

**Comment by Sumxx** [comment]
应该不是antd的问题，我现在把环境迁移到vite了可以正常build，
![image](https://github.com/umijs/umi/assets/1875780/b6d03fb4-64da-45ec-89c2-82e4327897e3)
看上去像是ant-design/pro-layout导致的
