### ISSUE TITLE
umijs3.5中使用web worker如何配置？

### ISSUE THREAD

**Issue by JasonHuo-J** [umijs/umi#12028]
## What happens?
我在umijs中使用了web worker，并且在config中开启了webpack5:{}和workerLoader:{},但是在浏览器中出现Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Promise')的报错

主进程
`useEffect(() => {
    const myworker = new Worker(new URL('./worker.worker.js', import.meta.url));
    myworker.onmessage = (e: any) => {
      console.log(e.data);
    };
    myworker.onerror = (e) => {
      console.log(e);
    };
    myworker.onmessageerror = (e) => {
      console.log(e);
    };
    myworker.postMessage('index.ts');
  }, []);`

worker进程
`self.onmessage = (e) => {
  console.log('worker.ts', e);
  postMessage('worker.ts');
};
`
config配置
`  webpack5: {},
  workerLoader: {},`

报错信息
![image](https://github.com/umijs/umi/assets/56123635/c2f72181-d214-4db7-8aee-66b9efe9c981)

我在原生html中使用了同样的方法进行调用是没有问题的，希望能帮助查看一下原因

`
    <script>
      const worker = new Worker('./worker.js');
      worker.onmessage = (e) => {
        console.log(e);
      };
      worker.postMessage('index.html');
    </script>

`

`self.onmessage = (e) => {
  console.log(e);
  postMessage('worker.js');
};
`

![image](https://github.com/umijs/umi/assets/56123635/8274c9b2-16ea-4d8d-bcdf-5288769591d6)

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4

**Comment by hardmanhong** [comment]
> umi 3 不维护了，建议升级到 umi 4

umi/max 4.0.11中应该怎么使用 worker
```
new Worker(new URL('./worker.js', import.meta.url));
```
提示报错
```
Module build failed (from ./node_modules/@umijs/mfsu/dist/loader/esbuild.js):
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
```

**Comment by fz6m** [comment]
升级到最新版本的 umi 再试试，如果还不行，就开一个 issue 给一个最小复现帮助排查问题。

**Comment by ruoduan-hub** [comment]
➕ 1  umi 中如何使用 web worker 呢 ？

```
chainWebpack(memo, { env, webpack }) {
    memo.module
      .rule('worker')
      .test(/\.worker\.js$/)
      .use('worker-loader')
      .loader('worker-loader')
      .end();
  },
```

以上传统方式好像不行

**Comment by fz6m** [comment]
如果 worker 使用有问题，可以新开一个 issue ，需要给一个最小复现。

**Comment by ruoduan-hub** [comment]
已解决 [参考](https://www.ruoduan.cn/React-use-WebWorker/)  ～ 😉
