### ISSUE TITLE
[Bug] umi4不开启页面级分包，就只有打包成一个umijs，开启后无法灵活控制分包内容

### ISSUE THREAD

**Issue by wenlei0617** [umijs/umi#12033]
当前使用umi4，会自动对layouts\wrapper进行分包并且对页面分包。这样导致的问题是，加载到页面的时候已经很久了。对于lighthouse和用户体验都不友好。整个页面本身可以并行请求加载，当前配置导致瀑布流，LCP会明显延后。是否可以提供一个像umi3一样的自定义打包的方式 。当前也不确定umi4为什么要这样设计。我理解根据不同的场景，分包策略都是不同的，没有所谓的最优解。当前的限制对于其他场景来说过于约束无法自定义

**Comment by fz6m** [comment]
umi 4 默认情况对每个路由的页面会分包，这样访问单个页面的时候只会加载这个页面需要的 js 资源，是最少最优的，如果你通过某种途径关闭了这种自动分包行为，则需要手动分包，在你想要分包的所有地方添加 `React.lazy(() => import('./path/to/component'))` 并展示在 `<Suspense />` 内即可。

**Comment by wenlei0617** [comment]
> umi 4 默认情况对每个路由的页面会分包，这样访问单个页面的时候只会加载这个页面需要的 js 资源，是最少最优的，如果你通过某种途径关闭了这种自动分包行为，则需要手动分包，在你想要分包的所有地方添加 `React.lazy(() => import('./path/to/component'))` 并展示在 `<Suspense />` 内即可。

页面级分包没有问题，但是umijs中的node_modules，我想要把拆分成2个js，现在是不可以的 。一个umijs太大了 。很影响加载

**Comment by wenlei0617** [comment]
> > umi 4 默认情况对每个路由的页面会分包，这样访问单个页面的时候只会加载这个页面需要的 js 资源，是最少最优的，如果你通过某种途径关闭了这种自动分包行为，则需要手动分包，在你想要分包的所有地方添加 `React.lazy(() => import('./path/to/component'))` 并展示在 `<Suspense />` 内即可。
> 
> 页面级分包没有问题，但是umijs中的node_modules，我想要把拆分成2个js，现在是不可以的 。一个umijs太大了 。很影响加载

@fz6m 这个有办法解决吗？

**Comment by fz6m** [comment]
如果你指的是某个 `node_modules` 中第三方库很大，就在使用到这个库的页面或组件里，将这个库导入变成懒加载即可；如果你指的是 umi 本身的 runtime 很大，这是正常的，因为 umi 是一个 react 的面向企业中后台 pc 端的 SPA 框架， react 应用都是 120kb 起步的，加上 core-js 的 polyfill 所以至少有几 M 的初始大小，如果你还使用到了某些组件库，由于这些组件库在每个页面都会用到，所以自然会包含到 `umi.js` 中，组件库是非常大的，所以最终 `umi.js` 的大小在 10 M 以内都是正常的。

如果你要考虑 To C 或者需要提高访问性能的 h5 等场景，建议使用 nextjs 或其他框架。

**Comment by Babyfaceqian** [comment]
> umi 4 默认情况对每个路由的页面会分包，这样访问单个页面的时候只会加载这个页面需要的 js 资源，是最少最优的，如果你通过某种途径关闭了这种自动分包行为，则需要手动分包，在你想要分包的所有地方添加 `React.lazy(() => import('./path/to/component'))` 并展示在 `<Suspense />` 内即可。

请问有什么方式可以关闭自动分包行为吗？

**Comment by javanoclaw** [comment]
@fz6m 有没有一个选项可以配置首页不分包

**Comment by fz6m** [comment]
没有，如果想自定义分包粒度，唯一的选择是关闭默认分包，手动对每个页面编写 `React.lazy(() => import('./path/to/component.tsx'))`。
