### ISSUE TITLE
配置scripts后js会排在umi.js后面照成变量找不到

### ISSUE THREAD

**Issue by su1924** [umijs/umi#12038]
scripts: ['/axios.min.js'],
  esbuildMinifyIIFE: true, // 修复 esbuild 压缩器自动引入的全局变量导致的命名冲突问题。
  externals: {
    axios: 'axios',
  },

设置scripts的时候，打包build后axios的js会排在umi.js后面造成变量找不到报错，开发模式正常。
希望改成排在umi.js前面

**Comment by fz6m** [comment]
如果要放到头部，需要用 [`headScripts`](https://umijs.org/docs/api/config#headscripts) ，如果你需要把某些依赖 external 掉，参考 [`externals`](https://umijs.org/docs/api/config#externals) 配置。

**Comment by wenlei0617** [comment]
> 如果要放到头部，需要用 [`headScripts`](https://umijs.org/docs/api/config#headscripts) ，如果你需要把某些依赖 external 掉，参考 [`externals`](https://umijs.org/docs/api/config#externals) 配置。

就不能放在body后面，umi前面吗？放在headScripts会阻塞html加载，并不友好

**Comment by HaoChenxin** [comment]
```typescript
export default (api: IApi) => {
  api.modifyHTML($ => {
    // 调整 script 标签
    const scripts = $('script').toArray()
    const umiScript = scripts.find(el => $(el).attr('src')?.includes('umi.'))
    const otherScripts = scripts.filter(el => el !== umiScript)
    $('script').remove()
    otherScripts.forEach(el => $('body').append(el))
    if (umiScript) $('body').append(umiScript)
    // 压缩代码
    let html = $('html').html() ?? ''
    html = html
      .split('\n')
      .map(line => line.trim())
      .filter(line => line.length > 0)
      .join('')
      .replace(/>\s+</g, '><')
    $('html').html(html)
    return $
  })
}
```
