### ISSUE TITLE
加载页面时有时候一直显示loading，手动刷新可恢复[Bug] say something

### ISSUE THREAD

**Issue by huyongtao-cmd** [umijs/umi#12043]
## What happens?
访问页面会偶尔会出现一直loading的情况，手动刷新浏览器后才能显示正常的页面

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context
<img width="1398" alt="企业微信截图_28ecacaf-fbe6-41a0-ba55-aaa187fad6cc" src="https://github.com/umijs/umi/assets/71239740/4b194a25-298d-4c5f-a6f1-b296ce74972b">

- **Umi Version**: 3.X
- **Node Version**: v16.14.1
- **Platform**:

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4 。
