### ISSUE TITLE
[Feature Request] 如何创建umi的模板 类似cra可以自己写一个template push到npm上就可以拉取

### ISSUE THREAD

**Issue by day-xue** [umijs/umi#12049]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by fz6m** [comment]
目前不具备这种功能，未来可能也不会支持（之前有做过这个外部模板的功能，但是没有被认可）。

如果需要模板，可以把模板放到 git 仓库里每次 clone 即可，或者自己做一个拷贝生成文件的 cli 工具，自行简单解决即可。
