### ISSUE TITLE
[Bug] umijs 4.0.90 定义require('@/statics/img/no-data.png')错误

### ISSUE THREAD

**Issue by xiaoliu1990** [umijs/umi#12042]
![Snipaste_2024-01-09_18-25-48](https://github.com/umijs/umi/assets/17424034/d456017a-bca5-42b0-b432-247feaad9927)
![Snipaste_2024-01-09_18-28-10](https://github.com/umijs/umi/assets/17424034/2c8210bf-4cc5-4ec8-a104-a3796b818aa9)
我如果直接在
constants\index.ts里面定义常量用来获取本地图片，就会报 Error: Cannot find module '@/statics/img/no-data.png'；
但是我如果放到其他名称的文件里面又不会报错，如下图：这样就可以启动，而且也可以import { NO_DATA_IMG } from '@/constants/img'这样引用
![Snipaste_2024-01-09_18-30-13](https://github.com/umijs/umi/assets/17424034/52da622c-44de-4aa1-ac89-08a4977e2a14)
![Snipaste_2024-01-09_18-31-29](https://github.com/umijs/umi/assets/17424034/e7209575-b331-4d33-9dd9-4899fab9e7c9)
希望能够直接写在index.ts这个文件里面，而不是说定义一个文件，在单独引用这个文件

**Comment by fz6m** [comment]
项目内 `src/*` 的代码应该写成 esm 格式的，获取一个图片的 url 需要使用 import ：

```ts
// constants/index.ts
import imageUrl from '@/assets/image.png'

// ...

// use
<img src={imageUrl} />
```

我看你的报错好像是在 `.umirc.ts` 里也导入了 `constants/index.ts` ，这是不可以的，因为配置文件是运行在 node cjs 中的，而 `src/*` 下面的代码是运行在 browser 浏览器中的。

如还有问题，需要给一个最小复现。
