### ISSUE TITLE
[Bug] 样式多加载多次

### ISSUE THREAD

**Issue by crazyair** [umijs/umi#12047]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/crazyair/antd5/tree/two-css

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

1. yarn start
2. 查看 `title___xIGPY` 样式
3. 调试面板出现2次 `title___xIGPY` 样式

![image](https://github.com/umijs/umi/assets/7971419/3754d2c0-f03d-4874-aa3d-fbf453442dbc)

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
在 umi 4 中，所有的页面都会自动按页拆包，并且携带它们自己页面拥有的全部资源， `/home` 和 `/home/demo` 是两个不同的页面，这两个页面都用到了 `<Guide />` 组件，所以他们的 js、css 资源都会重复携带一份，是符合预期的。

这是目前默认的分包配置决定的，无法自行修改，如果想共用这个组件的 js 、css 资源，可以把导入 `Guide` 的方式换为 `React.lazy(() => import('@/components/Guide/Guide'))` 懒加载，然后展示在 `Suspense` 中，这样人为的拆分 `Guide` 就可以得到资源重用了。

在 webpack 中有一种分包配置是在某个文件夹内的组件当共用 n 次后会被自动拆分，但目前 umi 4 不具有这种分包策略，而是按页自动拆分。

**Comment by crazyair** [comment]
恩，我的项目关掉分包了，因为感觉切换页面比较慢，还不如一个 2M 的 umi.js，先加载完在预览页面，切换页面就很快了
