### ISSUE TITLE
umi3动态路由导入组件时使用变量路径报错找不到模块： React.lazy(() => import(`@/pages${path}`))

### ISSUE THREAD

**Issue by Agr-0Z** [umijs/umi#12048]
component: forwardRef(() => (
          <React.Suspense fallback={<div>Loading...</div>}>
            {React.createElement(
              React.lazy(() => import(`@/pages${path}`)),
            )}
          </React.Suspense>
        )),
        通过import动态导入组件时报错找不到模块，但如果把路径写死的话页面就能正常渲染，我能确保路径没有出现问题。

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4
