### ISSUE TITLE
copy 功能是 [`copy-webpack-plugin`](https://github.com/webpack-contrib/copy-webpack-plugin) 这个插件实现的，如果要以文件内容作为 hash ，应该使用 `contenthash` ，这也是 webpack 中的一个 hash 种类，关于更多内容，请阅读 copy-webpack-plugin 插件的 readme 文档。

### ISSUE THREAD

**Issue by crazyair** [umijs/umi#12057]
copy 功能是 [`copy-webpack-plugin`](https://github.com/webpack-contrib/copy-webpack-plugin) 这个插件实现的，如果要以文件内容作为 hash ，应该使用 `contenthash` ，这也是 webpack 中的一个 hash 种类，关于更多内容，请阅读 copy-webpack-plugin 插件的 readme 文档。

_Originally posted by @fz6m in https://github.com/umijs/umi/issues/12052#issuecomment-1890913388_

还想回复感谢下，不让回复了。。。

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/7971419/296544262-3dadcde2-56ce-4e82-addd-e4fae80ff350.png">
            

另外想问下 umi config 的 hash: true 是 contentHash 吗

**Comment by fz6m** [comment]
不客气。
