### ISSUE TITLE
[Bug] 访问 public 下文件失败

### ISSUE THREAD

**Issue by crazyair** [umijs/umi#12050]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

文档站说用 `/image.png` 访问
![image](https://github.com/umijs/umi/assets/7971419/8544a653-8400-43ff-bf82-e172341133d6)

我这样使用
![image](https://github.com/umijs/umi/assets/7971419/f2503022-1089-40e8-b996-3df13d4b2474)

报错
![image](https://github.com/umijs/umi/assets/7971419/bd7dc121-518f-4adb-a046-e520566e821b)

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by crazyair** [comment]
另外，怎么给 public 的文件加 hash？

**Comment by cnyballk** [comment]
backgroundImage:"/umi.png"

**Comment by crazyair** [comment]
> backgroundImage:"/umi.png"

这里是测试写的 png，我其实要用的是 js 文件，需要用 import 引入

**Comment by cnyballk** [comment]
不行的，要不就在html里引入，为啥不放在src下import？

**Comment by crazyair** [comment]
> 不行的，要不就在html里引入，为啥不放在src下import？

我本来放 assets 下，但是发现，hash 会变？

**Comment by fz6m** [comment]
静态资源分两种，一种是项目内的，一般放在 `src/*` 下面，比如 `src/assets/image.png` ，使用方式是：

```ts
import imageUrl from '@/assets/image.png'

// ...

<img src={imageUrl} />
```

这种导入是自动就可以获取 url ，直接使用即可，并且带有 hash ，使最推荐的使用方式。

另一种静态资源是只拷贝到产物中去的，放在 `public/*` 下面，这里面的所有文件会被直接拷贝到构建产物目录里，不会加 hash ，一般用于固定不变的东西，使用时需要以绝对 url 使用，比如：

```ts
// 假如有一个 public/image.png

// css
background: url('/image.png');
```

但是这种方式除了没有 hash ，还不会携带 base ，假如你部署到非根目录的网站上，路径可能就是 `/${base}/image.png` ，此时需要手动修改代码使用到这些绝对资源的地方，不推荐这么使用。

理论上除了固定不变的资源（ 如 `favicon` ，某些名字不同的 js 脚本，如 `jquery.v1.0.0.js` ）外，所有静态资源都推荐放到项目中直接 `import` 导入。

**Comment by crazyair** [comment]
我是用 antd 的
 ```ts
import iconUrl from '@/assets/icon.js';
Icon.createFromIconfontCN({ scriptUrl: iconUrl });
```
因为是用 import 引入，所以 icon.js 会被打包到 umi.js，会有 icon.js 没有改动，src 其他文件改动，也会导致 umi.xx.js hash 变化，比较不好，所以希望改成 copy icon.js 方式，目前我是用这样修改的
src/app.ts
```ts
Icon.createFromIconfontCN({ scriptUrl: `${process.env.ICON_PATH}` });
```
.umirc.ts
```ts
const iconHash = createHash('md5').update(fs.readFileSync('icon.js')).digest('hex').slice(0, 8);

export default defineConfig({
    define: {
        'process.env.PUBLIC_PATH': publicPath,
        'process.env.ICON_PATH': `${publicPath}icon.${iconHash}.js`, // icon 文件地址
    },
    copy: [{ from: 'icon.js', to: `dist/icon.${iconHash}.js` }],
    extraBabelPlugins: process.env.NODE_ENV === 'production' ? ['babel-plugin-dynamic-import-node'] : [],
    ...
```

**Comment by crazyair** [comment]
另外还有个疑问，在用 `import iconUrl from '@/assets/icon.js';` 引用，打印 inconUrl  是 `{}`，不知道为什么能给 `Icon` 注册成功
