### ISSUE TITLE
[Bug] build hash 会一直变？

### ISSUE THREAD

**Issue by crazyair** [umijs/umi#12052]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/crazyair/antd5/tree/hash

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

1. yarn build 
2. 查看 `dist/demo.b89ed8b4.js` hash 的值
3. 修改 `src/pages/Table/index.tsx` 内容
4. 再次 yarn build
5. 查看 `dist/demo.d17cfde2.js` hash 的值变了 

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by seeintea** [comment]
文件内容变了 hash 跟着变很正常的吧

**Comment by crazyair** [comment]
> 文件内容变了 hash 跟着变很正常的吧

demo 是 copy 的，是单独的

**Comment by fz6m** [comment]
copy 功能是 [`copy-webpack-plugin`](https://github.com/webpack-contrib/copy-webpack-plugin) 这个插件实现的，如果要以文件内容作为 hash ，应该使用 `contenthash` ，这也是 webpack 中的一个 hash 种类，关于更多内容，请阅读 copy-webpack-plugin 插件的 readme 文档。
