### ISSUE TITLE
[Bug] umi4 root节点预置内容，加载过程中会先显示预制html之后白屏再显示

### ISSUE THREAD

**Issue by panjunqiu** [umijs/umi#12066]
## What happens?

html模版中默认写入了静态首页，目的是加快首屏的时间，但出现先显示静态HTML内容，白屏，再显示页面的过程，即使通过配置将js打包成一个umi.js，问题也存在。类似项目umi3没有白屏，umi4有白屏

打包成一个umi.js的配置
extraBabelPlugins:
    process.env.NODE_ENV === 'production' ? ['babel-plugin-dynamic-import-node'] : [],

## Mini Showcase Repository(REQUIRED)
https://github.com/panjunqiu/sample-umi4

## How To Reproduce
1.返回的html中插入umi.js和umi.css，并在root 节点内预制一些内容
2.刷新页面，预制内容显示 ==> 变白屏（若分包时间挺长，部分包也有白屏，期望部分包不白屏） ==> 正常显示

## 初步分析
umi内部使用了如下代码包裹组件,
``` jsx
function RemoteComponent(props: any) {
  const Component = props.loader;
  return (
    <React.Suspense fallback={<props.loadingComponent />}>
      <Component />
    </React.Suspense>
  );
}
```

默认的loadingComponent是一个空白div组件
```jsx
function DefaultLoading() {
  return <div />;
}
```

## 期望
1.是否可以增加类似 dynamicImport的配置，关闭动态加载的同时，去掉React.Suspense
2.或者有其他更好的解决方案吗？ 感谢

## Context

- **Umi Version**: 4.0.88
- **Node Version**: 16.18.1
- **Platform**: mac chrome

**Comment by fz6m** [comment]
现在 umi 4 中可能会因加载白屏的时机有以下几个：

1. 刚打开页面，还没加载 `umi.js` ：这个时候就只有访问看到的 html 内容而已，但 SPA 是个空的节点，要等 `umi.js` 加载完毕后才能开始渲染，如果觉得此处需要添加 loading ，可以通过 [`headScripts`](https://umijs.org/docs/api/config#headscripts) 添加一个外置的 js 脚本，在这个脚本里 query select 找到 root 节点然后手动添加 loading 样式和内容即可。

    但通常来说我们不会去添加这个，因为网页打开还没加载好就是白的在几乎所有网站都是这样的，如果需要更好的、更快的展示内容，应该使用 ssr ，而 umi 是一个 react 的企业中后台 pc 端为主的 SPA 框架，所以不适合在你这个场景使用 umi ，建议使用 nextjs 。

2. 分包 Suspense 导致的加载白屏：在 umi 4 中默认所有页面按页分包，这意味着你直接访问某个页面时获取到的 js 、css 资源是最少，最快的，但当切换路由，访问其他页面的时候会白一下，这个时候是去加载新的 js chunk 了，可以在项目里添加一个 `src/loading.tsx` 来控制这个白屏的时候展示的 loading 。

**Comment by panjunqiu** [comment]
> 现在 umi 4 中可能会因加载白屏的时机有以下几个：
> 
> 1. 刚打开页面，还没加载 `umi.js` ：这个时候就只有访问看到的 html 内容而已，但 SPA 是个空的节点，要等 `umi.js` 加载完毕后才能开始渲染，如果觉得此处需要添加 loading ，可以通过 [`scripts`](https://umijs.org/docs/api/config#scripts) 添加一个外置的 js 脚本，在这个脚本里 query select 找到 root 节点然后手动添加 loading 样式和内容即可。
>    但通常来说我们不会去添加这个，因为网页打开还没加载好就是白的在几乎所有网站都是这样的，如果需要更好的、更快的展示内容，应该使用 ssr ，而 umi 是一个 react 的企业中后台 pc 端为主的 SPA 框架，所以不适合在你这个场景使用 umi ，建议使用 nextjs 。
> 2. 分包 Suspense 导致的加载白屏：在 umi 4 中默认所有页面按页分包，这意味着你直接访问某个页面时获取到的 js 、css 资源是最少，最快的，但当切换路由，访问其他页面的时候会白一下，这个时候是去加载新的 js chunk 了，可以在项目里添加一个 `src/loading.tsx` 来控制这个白屏的时候展示的 loading 。

我先简单描述下背景：我们站点整体是SPA，但是部分页面需要做静态化，我们的方案是需要静态化的部分链接会通过工具自动抓图SPA渲染后的页面HTML，在访问这些页面的时候html的root阶段是包含了正常页面内容的。基于这个背景，我调整了配置，把js打成了一个umi.js，所以以上第1点：root中是有内容的；第2点：我改成打包成一个umi.js了还是有白屏。

**Comment by ayahua** [comment]
> > 现在 umi 4 中可能会因加载白屏的时机有以下几个：
> > 
> > 1. 刚打开页面，还没加载 `umi.js` ：这个时候就只有访问看到的 html 内容而已，但 SPA 是个空的节点，要等 `umi.js` 加载完毕后才能开始渲染，如果觉得此处需要添加 loading ，可以通过 [`scripts`](https://umijs.org/docs/api/config#scripts) 添加一个外置的 js 脚本，在这个脚本里 query select 找到 root 节点然后手动添加 loading 样式和内容即可。
> >    但通常来说我们不会去添加这个，因为网页打开还没加载好就是白的在几乎所有网站都是这样的，如果需要更好的、更快的展示内容，应该使用 ssr ，而 umi 是一个 react 的企业中后台 pc 端为主的 SPA 框架，所以不适合在你这个场景使用 umi ，建议使用 nextjs 。
> > 2. 分包 Suspense 导致的加载白屏：在 umi 4 中默认所有页面按页分包，这意味着你直接访问某个页面时获取到的 js 、css 资源是最少，最快的，但当切换路由，访问其他页面的时候会白一下，这个时候是去加载新的 js chunk 了，可以在项目里添加一个 `src/loading.tsx` 来控制这个白屏的时候展示的 loading 。
> 
> 我先简单描述下背景：我们站点整体是SPA，但是部分页面需要做静态化，我们的方案是需要静态化的部分链接会通过工具自动抓图SPA渲染后的页面HTML，在访问这些页面的时候html的root内是包含了正常页面内容的，这样我们有可以将部分页面静态化，而且不需要做整站的SSR改造。基于这个背景，我调整了配置，把js打成了一个umi.js，所以以上第1点：root中是有内容的；期望解决的事第2点，我打包成一个umi.js了不希望有白屏。我门同时有还未改造的umi3项目，没有白屏，umi4项目白屏，排查umi代码后怀疑是React.Suspense引起

您好，请问你这个问题有解决了吗？我现在也是打包成一个umijs，但是首次切换页面还是会有白屏。
