### ISSUE TITLE
加了兼容ie9，但是切换到ie还是会报错

### ISSUE THREAD

**Issue by zqm2014** [umijs/umi#1206]
// ref: https://umijs.org/config/
export default {
  plugins: [
    // ref: https://umijs.org/plugin/umi-plugin-react.html
    ['umi-plugin-react', {
      antd: true,
      dva: true,
      dynamicImport: true,
      title: 'umidemo',
      dll: true,
      // pwa: true,
      routes: {
        exclude: [],
      },
      polyfills: ['ie9'],
      hardSource: false,
    }],
  ],
}

错误：
SCRIPT1003: 缺少 ':'
umi.js (19657,9)

**Comment by jayguojianhai** [comment]
怎么解决的 我也遇到这个问题了

**Comment by qianduanMortal** [comment]
同样的问题。

**Comment by qianduanMortal** [comment]
升级了umi到最新版本， 并且配置了targets，解决了大部分报错。
`[React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.`
现在还有一个报错。
按照[https://github.com/umijs/umi/issues/1151](url)的解决办法，因为我用的ant-pro， 所以并没有global.js入口。

**Comment by xiaohuoni** [comment]
@qianduanMortal 新建一个src/global.js 最新的local应该修复了intl的问题

**Comment by jin-benben** [comment]
想问下您的问题解决了吗?我也遇到同样的报错，targets也是配置过的

**Comment by qianduanMortal** [comment]
> @qianduanMortal 新建一个src/global.js 最新的local应该修复了intl的问题

用xiaohuoni的方法可以解决 。 问题关闭了哈。
