### ISSUE TITLE
[Bug] Link 不传 pathname 不显示内容

### ISSUE THREAD

**Issue by crazyair** [umijs/umi#12079]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库  https://github.com/umijs/umi/issues/12079

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

以下不显示内容，但是不配置 pathname 也没有类型提示，导致项目用到的不好排查
```
<Link to={{ search: 111}}>aaa</Link>
```

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
如有问题，需要给一个最小复现仓库帮助排查。
