### ISSUE TITLE
umi4白屏问题，急急急！！！

### ISSUE THREAD

**Issue by Zt834000** [umijs/umi#12071]
function RemoteComponent(props: any) {
  const Component = props.loader;
  return (
    <React.Suspense fallback={<props.loadingComponent />}>
      <Component />
    </React.Suspense>
  );
}

function DefaultLoading() {
  return <div />;
}

umi4有个loading，是个空白，去不掉，造成白屏现象，
目标：去掉白屏现象

**Comment by fz6m** [comment]
umi 4 默认按页分包，这样单独访问一个页面所需要下载的 js 资源是最少的，分包的时候 react 要求包裹在 `Suspense` 里，所以当切换到新的路由会有加载白屏的过程，通过创建一个 `src/loading.tsx` 可以自定义加载组件。
