### ISSUE TITLE
如何给body添加类名？

### ISSUE THREAD

**Issue by weeptao** [umijs/umi#12086]
我需要给body添加类名，但是现在没有html文件，请问我该如何给body添加类名。
我使用tailwindCss，夜间模式需要给body添加dark:bg-black。

**Comment by fz6m** [comment]
写一个项目级插件 `plugin.ts` 用 `modifyHTML` 方法可以修改产物的 html 中任意内容，参考：https://github.com/umijs/umi-next/issues/868#issuecomment-1151088426

或者在运行时 `src/global.ts` 里手动操作 `document.body` 去修改节点。

**Comment by zhangyezeng** [comment]
@fz6m 你好，https://github.com/umijs/umi-next/issues/868#issuecomment-1151088426 这个已经404不能访问了...
