### ISSUE TITLE
[Bug] :root 设置 var 在生产环境失效

### ISSUE THREAD

**Issue by crazyair** [umijs/umi#12089]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/crazyair/antd5/tree/antd-mobile

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

1. pnpm start 查看 `aaa` 颜色是红色
2. pnpm build & pnpm preview 后预览查看 `aaa` 是蓝色

在 global.less 覆盖的 `--adm-color-primary` 被 `antd-mobile` 覆盖了

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by crazyair** [comment]
https://mobile.ant.design/zh/guide/theming 这里提示使用2个 `:root:root`，但是不知道 umi 这个为什么开发环境跟编译环境不一致？

**Comment by fz6m** [comment]
这个是由于 mfsu 为了提升启动速度，预构建了依赖，导致样式加载顺序和 webpack 构建整个应用不一致导致的，仅在开发时有这个问题，解决方法可以关闭 `mfsu: false` ，或者需要覆盖样式时，都写到 [`overrides.less`](https://umijs.org/docs/guides/directory-structure#overridescsslesssassscss) 里。

**Comment by crazyair** [comment]
:root 不能写到 overrides.less 里，不能给他加 body
