### ISSUE TITLE
[Bug] 关闭dynamicImport的配置办法无效

### ISSUE THREAD

**Issue by chj-damon** [umijs/umi#12087]
## What happens?

按照[https://github.com/umijs/umi/issues/8930](https://github.com/umijs/umi/issues/8930)的配置想要关闭`dynamicImport`功能，实际测试下来发现不管是`dev`还是`build`，最后都会生成很多除`umi.js`之外的文件，跟umi3里的`dynamicImport: false`效果相差甚远。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/chj-damon/umi4dynamicImportRepo

## How To Reproduce

**Steps to reproduce the behavior:** 
1. pnpm install
2. pnpm build

**Expected behavior**
dist目录下只应该有一个`umi.js`的JavaScript文件

## Context

- **Umi Version**: 4.1.1
- **Node Version**: v18.15.0
- **Platform**: MacOS 14.1.2 Chrome 版本 120.0.6099.234（正式版本） (arm64)

**Comment by fz6m** [comment]
umi 4 里是默认按页分包，每个异步块都会产生一个 js ，这样在访问每个页面的时候需要加载的 js 和 css 资源是最少最优的。

如果你不需要默认按页分包，就可以参考 FAQ 里的这种配置方法取消这个机制：

```ts
  extraBabelPlugins: process.env.NODE_ENV === 'production' 
    ? ['babel-plugin-dynamic-import-node'] 
    : []
```

我用你提供的 repo 构建试了一下，产物只有 `index.html` / `umi.js` / `umi.css` ，没有多余的 `xxx.async.js` 异步分包了，这个插件只是用来取消 js 的分包机制的，如果你用到了静态资源（比如图片等），这些东西还是会单独生成到产物目录里的 `static/*` 下面；理论上我们不应该在意产物有什么结构，应该将整个构建产物 `dist/*` 都用来部署，如果需要按版本区分，只需要以版本号为命名分目录管理产物即可。

如有问题，需要给一个实际可以复现的最小复现仓库。

**Comment by chj-damon** [comment]
啊？我在我本地测试的，不管是用pnpm还是yarn安装的依赖，最后打包出来的都跟你的不一样。
![image](https://github.com/umijs/umi/assets/4902684/1b162297-cdc7-4319-a116-89e94b85a809)

为什么会这样？

**Comment by chj-damon** [comment]
我找另一个朋友在他电脑上跑了一下，看到的结果也是
<img width="831" alt="image" src="https://github.com/umijs/umi/assets/4902684/1477382c-f57b-4420-90d5-d31508c4dd35">

**Comment by chj-damon** [comment]
@fz6m

**Comment by fz6m** [comment]
在你的示例项目里，并没有添加这一段配置：

```ts
// .umirc.ts

  extraBabelPlugins: process.env.NODE_ENV === 'production' 
    ? ['babel-plugin-dynamic-import-node'] 
    : []
```

看一下是不是你的项目里没有添加这个配置吧。

**Comment by chj-damon** [comment]
这个配置的意思是生产环境启用嘛，但是我的意思是想要不管生产环境还是开发环境，都不开启。所以我直接配的[]

这样不行吗？

**Comment by fz6m** [comment]
默认情况，就是不配置的话，umi 4 会默认按页拆包，产物就是一堆 js ；如果你想要产物不自动分包了，就要配置 `babel-plugin-dynamic-import-node` 这个 babel 插件，开启了这个插件才能抑制分包；之所以配制成仅在生产才开启是因为开发时如果一个 `umi.js` 太大了每次都要更新下载很大的体积，对开发热更新不友好。

如上文所述，如果配置 `[]` 其实就是和 `默认情况` 啥也不配一样，会默认拆包。

**Comment by chj-damon** [comment]
非常感谢！

**Comment by katoto** [comment]
extraBabelPlugins: ['babel-plugin-dynamic-import-node']

为啥还是不行呢

**Comment by fz6m** [comment]
如有问题，需要给一个最小复现。

**Comment by nanianlisao** [comment]
@fz6m 

请教一下大佬， 如果需要能自定义 某些路由 不进行拆包，但是又希望使用约定式路由的方式， 有什么推荐方案吗？ 例如 layout 希望不参与拆包， 或者类似关于约定式路由的设计，有什么方案吗。 clientLoader 这种方式感觉不太适用
