### ISSUE TITLE
[Bug] 使用 umi max，自定义布局出现两个 Layout 重叠

### ISSUE THREAD

**Issue by jiayongchang** [umijs/umi#12085]
config 中设置 layout：fasle，
src 下面新建 layouts/index.tsx并引入 ProLayout，简单配置之后，主要是为了实现自定义菜单，出现两个 layout 布局重叠的情况，而且是一模一样的菜单，说明并不是由 routes 自动渲染出来的，
<img width="1040" alt="image" src="https://github.com/umijs/umi/assets/67669980/2bf4b14f-0ff5-4347-97a6-19b7cbfba085">
<img width="209" alt="image" src="https://github.com/umijs/umi/assets/67669980/1cd5bc5b-4440-44b7-af7f-5df0f24f99de">

**Comment by fz6m** [comment]
自动 layout 是 umi 自带的一个功能，可以自动帮你根据路由表 + `ProLayout` 来生成一个 layout ，这样方便快速建立一个后台项目，配置文件里 `layout: {}` 打开了就会启用这个功能，参考 [layout](https://umijs.org/docs/max/layout-menu) 这个配置文档，你可以在 `src/app.tsx` 里去配置，这些选项会传递给 `ProLayout` ，从而你就可以自定义这个布局了：

```ts
// src/app.tsx

export const layout = () => {
  return {
    // ...
  }
}
```

自动生成的 layout 文件在 `src/.umi/plugin-layout/Layout.tsx` ，你可以自己研究下里面的传递逻辑。

如果你认为自带的 layout 还是不满足你的需求或者需要完全自定义 layout ，就把 `layout: {}` 这个功能去了，然后自己建一个 `src/layouts/index.tsx` ，但根据路由表去生成路由菜单和 icon 等逻辑这些如果你需要的话就要自己去写了，可以参考 `src/.umi/plugin-layout/Layout.tsx` 去 fork ，copy 了改。

或者写一个 umi 插件来生成自己的 layout ，可参考已有的 [layout](https://github.com/umijs/umi/blob/master/packages/plugins/src/layout.ts) 插件。
