### ISSUE TITLE
[Bug] npx max lint 无法检测错误调用字段

### ISSUE THREAD

**Issue by lynn1286** [umijs/umi#12082]
## What happens?

https://github.com/umijs/umi/assets/40122311/0ff8307b-f6a6-44c9-8a9a-79ea837d1f68

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by lynn1286** [comment]
还有就是这种eslint如何追加插件？我想要对导入的顺序进行排序，但是格式化冲突了

https://github.com/umijs/umi/assets/40122311/267ea8c3-a5d6-4568-ad1d-3bf0fe456b87

**Comment by lynn1286** [comment]
![image](https://github.com/umijs/umi/assets/40122311/0955e8f3-24ae-44ca-84ad-8dd22f7f218c)

**Comment by fz6m** [comment]
如果是语法类型等错误需要 tsc 去检验，可运行 `tsc --noEmit` 确保源码没有出现类型错误、引用错误这种问题；或者使用 [`fork-ts-checker-webpack-plugin`](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin) 插件确保构建过程中没有 TS 报错。

格式化冲突的问题在 https://github.com/umijs/umi/discussions/12077#discussioncomment-8177845 回复了。

如上文中链接中回复所述，umi 内置的 lint 規則只有非常少的简陋规则，要判断你这个变量到底是全局的 `styles` 还是 `define` 等 webpack 功能注入的，eslint 并不知道，只能通过和 ts 联动检验引用是否符合 ts 规则并报错（联动 ts 做检验的参考 [typescript-eslint](https://typescript-eslint.io/) 自行学习），但如本回复一开始提到的，为了避免这些繁琐的配置和学习成本，建议直接使用 `tsc` 做类型检测。
