### ISSUE TITLE
chorme 80浏览器，引入antd样式丢失的问题。

### ISSUE THREAD

**Issue by gaomAndximi** [umijs/umi#12099]
## What happens?

chorme 80浏览器，引入antd样式丢失的问题。
一开始我用的antd5.0，高版本浏览器没有问题，但是切换到80版本后，发现**按钮TSET**的样式失效，发现是:where()导致的问题，我就把antd版本降到4，理论上来说应该没有使用where了，但是样式还是失效了。我又根据之前某个issue调整了umi的配置，但是还是不行。

## How To Reproduce

![package](https://github.com/umijs/umi/assets/56968677/ee4da42a-ab44-4940-89b8-3682025d523c)
![umirc](https://github.com/umijs/umi/assets/56968677/c59a5cf4-66ea-45c1-9041-32e79dd2b134)
![页面](https://github.com/umijs/umi/assets/56968677/2810e9c9-1fb8-438c-b611-af36122b0566)

## Context
版本号如上图所示。

**Comment by fz6m** [comment]
### 如何验证兼容性

你配置的 `legacy` / `jsMinifier` / `cssMinifier` 这些都是在生产构建时才生效的，没法在开发时去验证，因为如果开发时做了这些兼容的行为，会额外增加很多编译过长，启动会非常慢，热更新也很慢，是没法开发的，所以如果你要验证生产效果，应该构建完了再验证。

一种本地构建完启动验证的方法是：

```bash
  pnpm umi build
  pnpm umi preview
  # 注：如果你用的是 max ，就把命令换成 pnpm max build
``` 

注：这种本地验证方式是启动的 localhost ，如果涉及到和域名相关的 cookie 权限等，需要你自己用代理工具处理（代理工具介绍略，请自行学习，若搞不定就把它发上测试环境验证吧）。

以上是推荐的验证低版本浏览器的方式。

### （不推荐）如何本地验证兼容性

如果你要本地开发时验证，可以尝试：

```ts
// .umirc.ts

  legacy: {
    buildOnly: false,
  },
  mfsu: false
```

然后就会编译全部源码在本地看下兼容性了，但这种配置开启了之后，如上文所述，编译时间会很长，并且热更新等也会时间较长，不容易开发。

这种在本地验证的方式是不推荐的，因为现代 webpack 5 等工具在开发时会有用于开发时的代码，这些用于开发运行时的代码不一定是兼容旧版本浏览器的，所以还是应该根据上文中推荐的验证方式，在构建完再验证。

### 补充内容

无论你是哪种这种方式，都不能 100% 确定是兼容旧版本浏览器的，因为 umi 4 是一个 react 的面向企业中后台 pc 场景的框架，如果你要兼容很旧的浏览器，不建议使用 umi （ 建议使用 vue 2 ）。

另外，通过学习 [非现代浏览器兼容](https://umijs.org/blog/legacy-browser) 并配置加入一些 polyfill 来进一步提高兼容的鲁棒性。

### 其他

如果你要用 antd 5 ，默认是生成的现代 css ，所以有 `where` / `is` 等语法，但如果你要兼容旧一点的浏览器（但不能太旧），也是有相应的配置方法的：

```ts
// .umirc.ts

  antd: {
    styleProvider: {
      hashPriority: 'high',
      legacyTransformer: true,
    },
  }
```

详情查看 [`styleProvider`](https://umijs.org/docs/max/antd#styleprovider) 配置项说明与 antd 关于 [样式兼容](https://ant.design/docs/react/compatible-style-cn) 的文档来学习了解更多内容。

**Comment by gaomAndximi** [comment]
我实验了下，使用antd5的话，可以参考antd官网浏览器样式兼容的方案解决。如果事antd4的话，需要手动引入antd.less文件也可以解决。

**Comment by gaomAndximi** [comment]
@fz6m 请问有交流群吗？
