### ISSUE TITLE
[Feature Request] renderClient 能否返回 app 实例？手动 render 时想要获取到 app 实例，因为需求是在指定时机手动销毁 app 实例

### ISSUE THREAD

**Issue by guoqiwen8** [umijs/umi#12097]
## Background

项目需求是在指定时机渲染以及手动销毁 app 实例，所以希望可以在手动 render 后先能获取到 app 实例，这样在 React 18 中才能使用 root.unmount()方法销毁

## Proposal

希望能对在packages/renderer-react/src/browser.tsx中的renderClient方法中的
`if (ReactDOM.createRoot) {
root = ReactDOM.createRoot(rootElement);
root.render();
return;
}`
修改为
`if (ReactDOM.createRoot) {
root = ReactDOM.createRoot(rootElement);
root.render();
return root;
}`
这样我就可以在app.tsx文件中的 render 方法里 拿到 root了，像这样：
`export const render = (oldRender) => {
const root = oldRender();
};`
## Additional context
经尝试，现在的oldRender()返回的是undefined，让我无法使用root.unmount()进行app销毁

**Comment by fz6m** [comment]
See #12096
