### ISSUE TITLE
[Bug] 子应用切换后 appName 会变成 [appName]_1

### ISSUE THREAD

**Issue by asyncguo** [umijs/umi#12094]
## What happens?

当多个子应用来回切换时，从第二个子应用切回第一个子应用，子应用的appName会自动加1，应该是触发了 genAppInstanceIdByName
<img width="301" alt="image" src="https://github.com/umijs/umi/assets/37094714/e316f975-0cda-45b1-8ca9-38452aa83d1a">
<img width="577" alt="image" src="https://github.com/umijs/umi/assets/37094714/e98a75ff-7ae0-4353-ad0a-ddd6d0a3e1d0">

## Mini Showcase Repository(REQUIRED)

>  [最小重现](https://github.com/asyncguo/umi-qiankun-demo)

触发了 genAppInstanceIdByName ，从而导致了appName发生了变化，目前不太清楚什么情况下会触发globalAppInstanceMap未清除
```js
export const genAppInstanceIdByName = (appName: string): string => {
  const globalAppInstanceMap = getGlobalAppInstanceMap();
  if (!(appName in globalAppInstanceMap)) {
    nativeGlobal.__app_instance_name_map__[appName] = 0;
    return appName;
  }

  globalAppInstanceMap[appName]++;
  return `${appName}_${globalAppInstanceMap[appName]}`;
};
```

## How To Reproduce

1. 来回切换子应用，再次切换到app1时就会触发
2. 切换过程中会动态更新主应用的菜单（因为业务上是动态从子应用获取的，case里只是mock了更新操作）

## Context

- **Umi Version**: 4.1.1
- **Node Version**: 14.21.2
- **Platform**: Mac OS

**Comment by asyncguo** [comment]
找到原因了，因为子应用 `app1` 第二次打开时，主应用的DOM结构发生了变化，导致qiankun中的计算出的`containerXPath`会发生变化，从而导致`appConfigPromiseGetterMap`获取不到缓存，重新执行了`loadApp`，获取到的`appInstanceId`会自动+1

<img width="1046" alt="image" src="https://github.com/umijs/umi/assets/37094714/df5fd8ad-29e7-4ef0-bbbf-77c7c9462142">

[源码定位](https://github.com/umijs/qiankun/blob/77331e8100100223e903c56b6383f69727f267b8/src/apis.ts#L162)
```js
if (container) {
  // using appName as cache for internal experimental scenario
  if ($$cacheLifecycleByAppName) {
    const parcelConfigGetterPromise = appConfigPromiseGetterMap.get(name);
    if (parcelConfigGetterPromise) return wrapParcelConfigForRemount((await parcelConfigGetterPromise)(container));
  }

  if (containerXPath) {
    const parcelConfigGetterPromise = appConfigPromiseGetterMap.get(appContainerXPathKey);
    if (parcelConfigGetterPromise) return wrapParcelConfigForRemount((await parcelConfigGetterPromise)(container));
  }
}

const parcelConfigObjectGetterPromise = loadApp(app, userConfiguration, lifeCycles);
```

**Comment by fz6m** [comment]
这个并不影响你的使用，如果 qiankun 源码有问题，想办法看看 qiankun 角度怎么解吧。

**Comment by HLDipsy** [comment]
请问你怎么解决的，我这在子页面刷新后在切换才会+_1， 然后因为多了_1，报错找不到容器 Wrapper element for xxx is not existed

**Comment by asyncguo** [comment]
> 请问你怎么解决的，我这在子页面刷新后在切换才会+_1， 然后因为多了_1，报错找不到容器 Wrapper element for xxx is not existed

配置下 `$$cacheLifecycleByAppName` 试试。

**Comment by HLDipsy** [comment]
> > 请问你怎么解决的，我这在子页面刷新后在切换才会+_1， 然后因为多了_1，报错找不到容器 Wrapper element for xxx is not existed
> 
> 配置下 `$$cacheLifecycleByAppName` 试试。

在哪里配置这个呢，我是这样注册的 qiankun: {
    master: {
      // 注册子应用信息
      apps: [
        {
          name: 'app1', // 唯一 id
          entry: '//localhost:7001', // html entry
        }
      ],
    },
  },

**Comment by asyncguo** [comment]
> > > 请问你怎么解决的，我这在子页面刷新后在切换才会+_1， 然后因为多了_1，报错找不到容器 Wrapper element for xxx is not existed
> > 
> > 
> > 配置下 `$$cacheLifecycleByAppName` 试试。
> 
> 在哪里配置这个呢，我是这样注册的 qiankun: { master: { // 注册子应用信息 apps: [ { name: 'app1', // 唯一 id entry: '//localhost:7001', // html entry } ], }, },

```js
{
  qiankun: {
    master: {
      ...,
      "$$cacheLifecycleByAppName": true
    }
  }
}
```

**Comment by HLDipsy** [comment]
> ```js
> "$$cacheLifecycleByAppName": true
> ```

可以，感谢，这个配置是啥意思呀，没找到解释

**Comment by asyncguo** [comment]
> > ```js
> > "$$cacheLifecycleByAppName": true
> > ```
> 
> 可以，感谢，这个配置是啥意思呀，没找到解释

qiankun 内部会缓存子应用初始化信息的，在 re-mount 时会复用上次初始化好的子应用，默认情况下是通过子应用在主应用下的 DOM 路径 xpath 获取的，主应用结构发生变化就会导致获取不到上次的子应用，而 $$cacheLifecycleByAppName 参数会通过子应用 name 进行缓存，只要子应用 name 不变，就可以直接复用上次的。

**Comment by HLDipsy** [comment]
> > > ```js
> > > "$$cacheLifecycleByAppName": true
> > > ```
> > 
> > 
> > 可以，感谢，这个配置是啥意思呀，没找到解释
> 
> qiankun 内部会缓存子应用初始化信息的，在 re-mount 时会复用上次初始化好的子应用，默认情况下是通过子应用在主应用下的 DOM 路径 xpath 获取的，主应用结构发生变化就会导致获取不到上次的子应用，而 $$cacheLifecycleByAppName 参数会通过子应用 name 进行缓存，只要子应用 name 不变，就可以直接复用上次的。

这个配置只在本地启动的父、子应用才有用，本地连线上还是报错，在子页面切换切换其他子页面就报错
![90bcf3a81cf9915bfbd943960d1853b](https://github.com/umijs/umi/assets/112858085/2b7666ba-1af6-429a-97e8-c4ced944d6d3)


，本地连线上是跨域的，我在注册子应用的时候配置为 entry：/micro/， 然后配了代理匹配到/micro/时代理到线上的应用的地址，
