### ISSUE TITLE
[Feature Request] preview 增加支持 env 配置

### ISSUE THREAD

**Issue by crazyair** [umijs/umi#12090]
## Background
![image](https://github.com/umijs/umi/assets/7971419/fd8ebc15-6adb-4d8b-aaf4-6d1e8d6d15cc)

preview 支持了这3个，但是不支持 `env` 配置，导致设置的 `HOST='local.xxx.yyy'` 没生效
## Proposal

执行 `umi preview` 后输出 `ready - App listening at http://localhost:4173` 希望输出 `ready - App listening at http://local.xxx.yyy:4173`

**Comment by fz6m** [comment]
这个 preview 功能只是非常简单的一个本地预览，需要域名的话直接用 charles 、whistle 等代理工具代理这个域名的请求到本地 preview 的地址就好了。
