### ISSUE TITLE
renderClient 能否返回 app 实例？手动 render 时想要获取到 app 实例，因为需求是在指定时机手动销毁 app 实例

### ISSUE THREAD

**Issue by guoqiwen8** [umijs/umi#12096]
## Background

项目需求是在指定时机手动销毁 app 实例，所以希望可以在手动 render 后获取到 app 实例，这样在 React 18 中才能使用 root.unmount()方法

## Proposal

/**
 *  执行 react dom 的 render 方法
 * @param {RenderClientOpts} opts - 插件相关的配置
 * @returns void
 */
export function renderClient(opts: RenderClientOpts) {
  const rootElement = opts.rootElement || document.getElementById('root')!;
  const Browser = getBrowser(opts, <Routes />);
  // 为了测试，直接返回组件
  if (opts.components) return Browser;

  if (opts.hydrate) {
    ReactDOM.hydrateRoot(rootElement, <Browser />);
    return;
  }

  if (ReactDOM.createRoot) {
    root = ReactDOM.createRoot(rootElement);
    root.render(<Browser />);
    return;
  }
  // @ts-ignore
  ReactDOM.render(<Browser />, rootElement);
}

希望该方法中对于
 if (ReactDOM.createRoot) {
    root = ReactDOM.createRoot(rootElement);
    root.render(<Browser />);
    return;
  } 
**可以将 return 修改为 return root**。

这样我就可以在app.tsx文件中的 render 方法里 拿到 root了，像这样：
export const render = (oldRender) => {
 const root = oldRender();
};

**Comment by fz6m** [comment]
从 umi 导入 `__getRoot` 这个方法，可以直接拿到 root
