### ISSUE TITLE
[Bug] 直接打开带.html后缀的路由，页面内content会404

### ISSUE THREAD

**Issue by ahnuchen** [umijs/umi#12098]
## What happens?
打开这个链接：[https://ahnuchen.tech/react/index.html](https://ahnuchen.tech/react/index.html)， 内容出现404，点击导航栏的路由能正常显示

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
打开https://ahnuchen.tech/react/index.html

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version*2.2.13*:
- **Node Version*18.14*:
- **Platform*windows*:

**Comment by fz6m** [comment]
umi 2 不维护了，建议升级到 umi 4 。

对于一个 SPA 来说，所有的请求应该在 nginx 或者网关里专门配置 fallback 到 `index.html` （搜索 `SPA nginx 配置` 了解更多），所以他是没有 `index.html` 这种古时的单页面 html 访问方式的，访问 `/` 就是在访问应用的根路由（首页），访问 `/index.html` 就是在访问应用的 `/index.html` 这个路由，很明显我们没有 /index.html` 这种路由（除非你创建一个 `/index.html` 路由），因为 SPA 的访问都会被 fallback 到 `index.html` 这个文件，所以对于 SPA 来说，请求路径不会出现 `.html` 这种路径式对文件的访问。

有关更多信息，请搜索 SPA 自行学习。
