### ISSUE TITLE
使用umi小米饭 出现镜像源过期      

### ISSUE THREAD

**Issue by Abengate** [umijs/umi#12109]
## What happens?

出现镜像源过期   我已经切换了新的镜像源，显示的还是以前淘宝的 说是
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
![49e859ad2b6c46a740ad1582e899e22](https://github.com/umijs/umi/assets/122261591/13501ef6-e7be-4626-b19e-e6b8c5b772ed)

- **Platform**:

**Comment by fz6m** [comment]
你应该只换了 npm 的配置里的源，但是 lock 文件里的旧域名没改，这样还是从旧地址下载会报错，需要更新 lock 文件。

用 [npmmirror-quick](https://www.npmjs.com/package/npmmirror-quick) 这个包跑一下更新 lock 文件吧。

**Comment by Abengate** [comment]
问题描述：

我已按照教程上的操作了一遍，但结果还是不如意，我删除了node_modules这个模块，在重新安装 还是出现以下问题，yarn.lock中没有旧的镜像源。


npm ***@***.***/preset-ui -D&nbsp;


这个问题在我创建 ant design pro 项目 使用&nbsp;npm ***@***.***/preset-ui -D&nbsp; 也会出现同样的问题


图例：







&nbsp;


?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月3日(星期六) 凌晨1:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [umijs/umi] 使用umi小米饭 出现镜像源过期       (Issue #12109)





 
你应该只换了 npm 的配置里的源，但是 lock 文件里的旧域名没改，这样还是从旧地址下载会报错，需要更新 lock 文件。
 
用 npmmirror-quick 这个包跑一下更新 lock 文件吧。

**Comment by fz6m** [comment]
上文回复的比较混乱，看不清信息。

如果你的下载是因为 lock 文件里有旧的镜像源域名导致下载失败的问题，用 nq 这个工具可以更新为最新的域名地址，再把 node_modules 删了重新安装就行，如果还是下载不下来，就说明不是 lock 文件的问题，得自己排查下是不是网络问题或者其他原因。

如还有问题，需要给一个更清晰完整的上下文描述。
