### ISSUE TITLE
fatal - Error: Register plugin F:/Java/BI/BI-frontend/node_modules/@umijs/plugin-run/dist/index.js failed, since _core(...).Logger is not a constructor

### ISSUE THREAD

**Issue by notjuli** [umijs/umi#12101]
# 报错信息
start:dev启动项报错信息如下
![1](https://github.com/umijs/umi/assets/97144636/84d89347-bc09-4c27-866f-71b63593b718)
# package.json
![image](https://github.com/umijs/umi/assets/97144636/83bff241-9472-4016-b3f4-1eb760744f76)

**Comment by fz6m** [comment]
看看本地 node 版本是多少吧，umi 4 最低要求 `node >= 14`

如有问题，需要给一个最小复现，另外提供标准的 issue 必备内容和上下文。
