### ISSUE TITLE
start:dev启动项目后报错Cannot find module './TableList' from 'F:/Java/BI/BI-frontend/src/pages'

### ISSUE THREAD

**Issue by notjuli** [umijs/umi#12100]
# 报错信息
![微信图片_20240128181953](https://github.com/umijs/umi/assets/97144636/ea1046c6-8587-4030-ba3c-f8e4fccf2938)
# 依赖版本信息
![QQ图片20240128182657](https://github.com/umijs/umi/assets/97144636/532a648a-440d-4a13-8ea3-7235503908b8)

**Comment by fz6m** [comment]
目测是配置里的 `routes` 路由表配错了，你配了 `./TableList` 这个路由文件，但是在 `src/pages/*` 下面没有这个路由文件，自己根据报错排查一下吧。
