### ISSUE TITLE
[Bug] plugin api api.modifyHTML path param not right when build

### ISSUE THREAD

**Issue by yutingzhao1991** [umijs/umi#12108]
## What happens?

插件的方法 `api.modifyHTML` 传入的函数接收到的第二个参数在构建的情况下不正确

## Mini Showcase Repository(REQUIRED)

```
import { IApi } from 'umi';

// 修改 html 的 title
const htmlTitles: {
  [key: string]: string;
} = {
  '/home/know-your-customer': 'Identity (KYC)',
  '/home/node-service': 'Web3 Node Service',
  '/home/contract-review': 'Smart Contract Review',
  '/home/know-your-transaction': 'Know Your Transaction',
  '/home/privacy-oriented-verification': 'Privacy-oriented Verification',
  '/home/appchain': 'AppChain',
};

// https://github.com/umijs/umi-next/issues/868
export default (api: IApi) => {
  api.modifyHTML(($, params) => {
    console.log('get path', params);
    const { path } = params;
    if (htmlTitles[path]) {
      $('head title').text(`ZAN - ${htmlTitles[path]}`);
    }
    return $;
  });
};
```

umi build 看日志 path 得到的全部是 `/`。 umi dev开发的时候是好的。

![image](https://github.com/umijs/umi/assets/1061968/517b878d-1346-46d5-a791-3ef0ac0dc8e8)

## Context

- **Umi Version**: 4.1.1
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
因为请求的时候是根据请求的 path 到开发 server 里，这个时候知道请求是啥路径，所以有值；但构建的时候只产出一个 `index.html` 的 SPA ，这个 path 就固定是 `/` 了，因为产物是纯静态的和路径无关。

我看了下这个地方是 2 年前搞的一个参数，这个参数应该没用，是个冗余的想法，现在大家都只用这个 `modifyHTML` api 的第一个参数修改 html 产物，如有兴趣可以 PR 删掉这个第二个参数。

因为只有一个 `index.html` 的产物，还是往 script 里写一个路径和你想要的值映射的 map 把，这样在代码里就能取到了。

**Comment by yutingzhao1991** [comment]
> 因为请求的时候是根据请求的 path 到开发 server 里，这个时候知道请求是啥路径，所以有值；但构建的时候只产出一个 `index.html` 的 SPA ，这个 path 就固定是 `/` 了，因为产物是纯静态的和路径无关。
> 
> 我看了下这个地方是 2 年前搞的一个参数，这个参数应该没用，是个冗余的想法，现在大家都只用这个 `modifyHTML` api 的第一个参数修改 html 产物，如有兴趣可以 PR 删掉这个第二个参数。
> 
> 因为只有一个 `index.html` 的产物，还是往 script 里写一个路径和你想要的值映射的 map 把，这样在代码里就能取到了。

exportStatic 配置的时候就会有多个 html 了
