### ISSUE TITLE
[Bug] 希望可以将 umi3 的 cssnano 更新到 5.1.2 以上，解决了 tailwindcss 在生产环境下 css 变量被移除的问题

### ISSUE THREAD

**Issue by linyxria** [umijs/umi#12107]
## 问题

umi3 tailwindcss 在生产环境下 backdrop-filter 等某些样式不生效

## 环境

- **Umi Version**: 3.5.40
- **Node Version**: 16.18.1
- **Platform**: macOS 14.3

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4 。
