### ISSUE TITLE
umi建站在insight上测试性能分数低，Total Blocking Time和Script Evaluation的时间长

### ISSUE THREAD

**Issue by guijuzhejiang** [umijs/umi#12112]
umi建的网站在insight上做了性能测试，TBT和Script Evaluation都要等几秒，导致性能很低，请教各位大侠有没有什么提高性能的方法吗？

缩短 JavaScript 执行用时 2.4 秒

![截图 2024-02-02 11-03-52](https://github.com/umijs/umi/assets/57936895/c44fb96f-febf-41d0-93ba-dd8f46918662)

最大限度地减少主线程工作 3.0 秒

![image](https://github.com/umijs/umi/assets/57936895/40b5c50e-a2d3-4381-88fc-13ca580646ad)

**Comment by guijuzhejiang** [comment]
@fz6m 感谢回复，产品2C的，看来选错框架了，不过已经做好了，还能抢救一下吗？

**Comment by devmsg** [comment]
> umi 是一个 react 的面向企业中后台 pc 端开发的 SPA 框架，为了快速成型内置了较多的运行时代码和模板代码，同时 antd 等组件库都是比较大的，在 toB 开发时使用的动画库、图表库、表单库等都是体积比较大的，场景要求决定了 umi 的产物体积就是大的，但在网速过剩的 B 端场景下这不是问题。
> 
> 你提到的速度问题，由于 SPA 本来就是单标签慢的，加上产物体积很大运行需要较长时间渲染，所以应用速度就是慢的，所以当你需要考虑速度、性能、首屏渲染、H5 等场景时，不建议使用 umi ，应该使用支持 SSR 的 nextjs 。

这个回答很蛋疼呀

**Comment by guijuzhejiang** [comment]
@devmsg 何止蛋疼，我蛋碎了我。做了一年的项目，最后发现第一步就走错了。

**Comment by witcsmartian** [comment]
> @devmsg 何止蛋疼，我蛋碎了我。做了一年的项目，最后发现第一步就走错了。

==
