### ISSUE TITLE
umi3.5.21版本开启mfsu后，useModel注册失败

### ISSUE THREAD

**Issue by fengliner** [umijs/umi#12117]
umi版本3.5.21
config.ts配置了mfsu: {}
项目启动正常，浏览器打开页面报错，看报错信息像是useModel注册失败

![image](https://github.com/umijs/umi/assets/6862756/5567af4f-374d-466b-8a55-e21f21c143c3)

**Comment by fz6m** [comment]
1. umi 3 不维护了，建议升级到 umi 4 

2. 如果 mfsu 有问题，就不要开 mfsu 了吧，umi 3 的 mfsu 还是不够那么完善的

**Comment by fengliner** [comment]
> 1. umi 3 不维护了，建议升级到 umi 4
> 2. 如果 mfsu 有问题，就不要开 mfsu 了吧，umi 3 的 mfsu 还是不够那么完善的

升级umi4有点困难。但是又想优化umi3项目的热更新时间，目前10秒+，还有什么好方法吗

**Comment by fz6m** [comment]
应该主要是需要编译的代码太多引起的，你在开发时单独配一个 routes 路由表的配置，这里面只包含 layout 和你需要开发的路由页面，这样代码就少了，我记得上百个路由的项目只能这样。

**Comment by fengliner** [comment]
> 应该主要是需要编译的代码太多引起的，你在开发时单独配一个 routes 路由表的配置，这里面只包含 layout 和你需要开发的路由页面，这样代码就少了，我记得上百个路由的项目只能这样。

 目前应用是用的约定式路由。开发时单独配置一个routes路由，是说开发时使用配置时路由吗，编译的时候只会编译routes配置的文件吗？
