### ISSUE TITLE
[Bug] 当public目录为空时，使用npm start会报错 ERROR in unable to locate 'D:/.../public/**/*' glob

### ISSUE THREAD

**Issue by start-wankai** [umijs/umi#12119]

**Comment by start-wankai** [comment]
当public目录为空时，使用npm start会报错 ERROR in unable to locate 'D:/.../public/**/*' glob

**Comment by fz6m** [comment]
我新建了一个 umi 4 项目，然后创建了一个空的 public 目录，启动项目一切正常。

如有问题，需要给一个最小复现。
