### ISSUE TITLE
umi@2路由按需加载无效？

### ISSUE THREAD

**Issue by NexxLuo** [umijs/umi#1211]
build 打包时，没有根据路由生成对应的文件，而是大部分生成到了vendor.async.js中。具体如下图：

1   .umi/router.js中自动生成的路由
![1](https://user-images.githubusercontent.com/18549980/46723442-6f61ff00-ccaa-11e8-845e-f8f00d4af159.png)

2. .umirc.js配置
     
![2](https://user-images.githubusercontent.com/18549980/46723464-7f79de80-ccaa-11e8-9415-ab5b39682f98.png)

umi-plugin-react的配置试过很多种，包括配置level什么的，均无效

3. 最终生成的文件
![3](https://user-images.githubusercontent.com/18549980/46723475-899bdd00-ccaa-11e8-84c0-a5f1edd20bd2.png)

**Comment by sorrycc** [comment]
为啥会有 libs 这些？给个可重现的例子吧。

**Comment by NexxLuo** [comment]
> 为啥会有 libs 这些？给个可重现的例子吧。

项目内容太多，不太好给例子。初步判断，可能是因为特殊的目录结构导致的引用问题。目前用splitChucks处理了
