### ISSUE TITLE
[Bug] clientLoader方法在二级目录模式下第一次不执行

### ISSUE THREAD

**Issue by aofong** [umijs/umi#12124]
## What happens?

将项目部署到`二级目录` 如：`http://127.0.0.1:8000/dist/ `后

首页`/src/pages/index.jsx`中的`clientLoader`方法在页面第一次打开的时候不会触发

发现新版本不会像`umi@3.x`版本那样跳到`hash`地址去`http://127.0.0.1:8000/dist/#/`

我尝试将`http://127.0.0.1:8000/dist/ `手动改成`http://127.0.0.1:8000/dist/#/`后`clientLoader`方法会触发执行

请问下，怎么解决这个问题？生产环境是需要将项目部署到`二级目录`的，目前是通过`nginx`代理的

## How To Reproduce
`.umirc.ts`
```
{
  npmClient: 'pnpm',
  base: '/',
  publicPath: process.env.NODE_ENV === 'production' ? './' : '/',
  hash: true,
  history: { type: 'hash' },
  alias: { '@': '/src' },
  define: { 'process.env.DevProxyServer': process.env.DevProxyServer },
  clientLoader: {},
  apiRoute: { platform: '' },
  codeSplitting: { jsStrategy: 'granularChunks' },
  targets: { chrome: 49 },
  legacy: {},
}
```
<img width="604" alt="image" src="https://github.com/umijs/umi/assets/3070161/6d301674-6e7f-45a3-b031-f9b404733033">

## Context

- **Umi Version**:4.1.1
- **Node Version**:v16.20.0
- **Platform**:mac

**Comment by fz6m** [comment]
如果要把站点部署到子路径，需要配置和子路径一样的值到 `base: '/dist'` ，不然路由会匹配不上。

如还有问题，需要给一个最小复现。
