### ISSUE TITLE
[Bug] antd 和 vite 同时开启后样式无法按需编译

### ISSUE THREAD

**Issue by showonne** [umijs/umi#12128]
## What happens?

umi plugin antd 中开启 vite 后会直接 import 全量的 antd 样式文件：
<img width="696" alt="image" src="https://github.com/umijs/umi/assets/9353213/57665d34-4223-48dc-8f16-40696ed110fa">
项目中使用 `vite-plugin-imp` 这类插件按需编译样式无法生效  

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce
同时开启 antd 插件和 vite，并在 vite 中使用 `vite-plugin-imp` 插件

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:  4.0.67
- **Node Version**: 20
- **Platform**: MacOS

**Comment by fz6m** [comment]
这个问题你觉得如何解决比较好。

我觉得就算全量编译也没差多少，反正 antd 的项目都属于中后台，产物体积上并没有要求；

考虑也用到表格、表单等大部分组件，其实也并不能削减多少按需的体积；

其次 vite 构建分包不是很理想，不如 webpack 更好；

另外如果要使用 vite ，可以用 vite 本身，umi 5 就放弃 vite 这个功能了，现在用 vite 主要是支援一些 vue umi 的项目，支持的插件也不多，并不是长久之计。

**Comment by showonne** [comment]
我是用 create umi 生成的 antd 的项目模板，但实际上也没用模板的默认布局，所以暂时将 antd 插件关了，css 上会少个 ~30kb
我直接关 issue 吧，感觉也不需要解决
