### ISSUE TITLE
umi 配置 workspace 错误

### ISSUE THREAD

**Issue by xu756** [umijs/umi#12120]
截图

<img width="1585" alt="image" src="https://github.com/umijs/umi/assets/84982391/31fc12cb-a76a-4274-8ab0-b1f1f7ea847c">

配置 mfsu 

```typescript
mfsu: {
        exclude: ['@editor/editor'],
    },
```
使用

``` typescript
import EditorJS, { API, BlockMutationEvent } from '@editor/editor';
export default () => {
    const e = new EditorJS({
        holder: 'editor',
        onChange(api: API, event: BlockMutationEvent | BlockMutationEvent[]) {
            console.log(event);
        },
    });

    return (
        <>
            <div id="editor"></div>
        </>
    );
};

```

目录如下

<img width="377" alt="image" src="https://github.com/umijs/umi/assets/84982391/e2312c24-a72e-4f6f-b38a-db49dcc44c18">

报错 
<img width="909" alt="image" src="https://github.com/umijs/umi/assets/84982391/5dd02be0-cad1-4103-aae1-3072d480918e">

**Comment by fz6m** [comment]
需要确保你的那个子包的 `package.json#name` 是 `@editor/edtior` ，然后这个子包的入口设定符合能被正确解析的规范。

如果还有问题，需要给一个最小复现仓库。
