### ISSUE TITLE
最新版本支持动态注册 model 吗

### ISSUE THREAD

**Issue by kycool** [umijs/umi#1212]
- 需求：是否可以全局注册
因为后台数据表比较多，想根据后台数据表的配置，动态生成 model 然后注册到全局中，是否可以呢，

例如通用的 crud，期望根据表的配置，共用一套生成 model 的方法，然后按需动态注册到全局中

- 需求：局部注册
有些 model 只是局部的使用，不需要全局注册，是否可以局部注册，使用完可以卸载；或者说已经支持了，有链接可以参考吗，谢谢

@sorrycc 辛苦了

**Comment by sorrycc** [comment]
动态注册 dva 的 model 吗？应该可以这样 `window.g_app.model(YOUR_MODEL)`。

**Comment by sorrycc** [comment]
有问题再 reopen 。
