### ISSUE TITLE
umi 使用 packages 怎么配置子包 

### ISSUE THREAD

**Issue by xu756** [umijs/umi#12125]
项目含有多个子包。 packages/react  packages/core. packages/web. web 是umi项目，我在web里面使用 上面两个包，怎么连接不上，提示需要安装， 
<img width="373" alt="image" src="https://github.com/umijs/umi/assets/84982391/5f79636d-d953-4647-af4e-4b65f5ef1e50">

vite 有alias 配置重定向，umi怎么配置

![image](https://github.com/umijs/umi/assets/84982391/25db083c-b857-47a2-9cc7-399853e98d9d)

**Comment by fz6m** [comment]
把这个包名添加到 `mfsu.exclude` 排除掉，就可以修改自动更新了：

```ts
// .umirc.ts

  mfsu: { exclude: ['@note/react'] }
```

不过如果你的源码是 ts 写的，你要同步编译出来 js 产物才能热更新，所以 `monorepoRedirect` 这个功能就是用来重定位到 ts 源码的，把这个功能打开之后就会自动添加 alias 到其他子包去了，更多说明详见文档：

```ts
  monorepoRedirect: {}
```
