### ISSUE TITLE
添加运行时插件 怎么使用

### ISSUE THREAD

**Issue by ACERY1** [umijs/umi#1213]
![image](https://user-images.githubusercontent.com/19555547/46731718-02f0fb00-ccbe-11e8-9010-2d74f0b011b7.png)

文档如图，不知道具体怎么使用。

**Comment by ACERY1** [comment]
目前采用的办法是先在插件里写
```
api.addRuntimePlugin(path.resolve(__dirname, './log.js'))
api.addRuntimePluginKey('log')
```
然后在组件内写
```
import runtimePlugin from 'umi/_runtimePlugin'
runtimePlugin.apply('log',{})
```

这样的方式是否正确？

**Comment by sorrycc** [comment]
是的，具体可以参考 umi-plugin-dva。
