### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by wuhanjun** [umijs/umi#12134]
## What happens?

父应用使用umi，子应用vue普通项目，使用@umijs/plugin-qiankun，父应用更新数据，子应用如何接收？不是通过onGlobalStateChange吗？

父应用代码
```
<MicroAppWithMemoHistory
    autoCaptureError
    loader={loader}
    globalState={sqlInfo}
    dispatch={dispatch}
    name={MicroAppEnum.FetchTool}
  />
```

子应用代码
```
export async function mount(props) {
    props.onGlobalStateChange((newState) => {
        console.log('child-app', newState);
    });
    render(props);
}
```
父应用中globalState数据更新，子应用内onGlobalStateChange的回调函数并不会调用，但是子应用内update生命周期会触发。

## Context

- **Umi Version**: 4.1.1
- **Node Version**: v16
- **Platform**: chrome
- 子应用vue2.x

**Comment by fz6m** [comment]
如果子应用不是 umi ，这种情况应该使用 qiankun 导入的原生方法去加载子应用，比如 `loadMicroApp` ，这个时候就和 umi 无关了，所有 umi qiankun 插件默认提供的路由功能、数据流功能都是用不了的，如果你需要这些，主子应用应该都是 umi 比较方便，否则非 umi 的子应用就和 umi 无关来看待。
