### ISSUE TITLE
umi@3.5开启webpack5之后build失败，dev正常

### ISSUE THREAD

**Issue by fengliner** [umijs/umi#12131]
umi版本3.5.21，开启webpack5之后，umi dev正常，umi build报错

![image](https://github.com/umijs/umi/assets/6862756/665a6560-b118-4eb1-872c-d18173518363)

**Comment by fz6m** [comment]
1. umi 3 不维护了，建议升级到 umi 4 

2. 如果 webpack 5 用不了就别用了吧，本来 umi 3 就是 webpack 4 为主的，umi 4 才是 webpack 5 。
