### ISSUE TITLE
升级umi4 markdown引入有问题

### ISSUE THREAD

**Issue by wangsanshao** [umijs/umi#12149]
## What happens?
升级完umi4,

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by wangsanshao** [comment]
> ## What happens?
> 升级完umi4, `import md from './index.md' console.log('md', md) // 此时是带publicpath的路径 `umi3 `import md from './index.md' console.log('md', md) // 此时是markdown源码 `
> 
> ## Mini Showcase Repository(REQUIRED)
> > Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
> 
> ## How To Reproduce
> **Steps to reproduce the behavior:** 1. 2.
> 
> **Expected behavior** 1. 2.
> 
> ## Context
> * **Umi Version**:
> * **Node Version**:
> * **Platform**:

**Comment by fz6m** [comment]
你的预期是导入 md 文件获得啥内容，默认情况啥也不配，在 umi 4 里会把 md 文件当成静态资源，获得一个 url 。

如果你需要导入 md 渲染出来，需要进行 mdx 的配置，参考 #11966

**Comment by fz6m** [comment]
webpack5 开始就不存在 `url-loader` / `raw-loader` / `file-loader` 了，需要用 `type` 来替代，参考 [Asset Modules](https://webpack.js.org/guides/asset-modules/) ，如果你要使用 `raw-loader` ，直接 `.test().type('asset/source')` 即可。
