### ISSUE TITLE
umi4编译后的产物js文件统一放到js文件夹，css文件统一放到css文件夹，image文件统一放到image文件夹

### ISSUE THREAD

**Issue by ywzou** [umijs/umi#12142]
umi4编译后的产物js文件统一放到js文件夹，css文件统一放到css文件夹，image文件统一放到image文件夹

**Comment by fz6m** [comment]
因为一些历史原因，现在的结论是不支持这么做，请保证产物的结构完整性，不建议私自修改产物结构。

如果觉得不好管理，可以按版本分目录来管理。

FYI：

 - https://github.com/umijs/umi/discussions/9887#discussioncomment-6123788
