### ISSUE TITLE
Umi4.0每次部署完毕后，通过URL访问生产环境项目一直是老版本，存在缓存情况，请问哪里可以修复这个问题？

### ISSUE THREAD

**Issue by shujun222** [umijs/umi#12155]
## What happens?
这里有一个同样的问题: https://github.com/umijs/umi/issues/9793
按照步骤，并没有解决我的问题, 所以new issue, 希望大佬们重新研究解决下。

**1. 遇到的问题：**
发版后有时会出现下面报错
![image](https://github.com/umijs/umi/assets/45231907/4766cd11-a318-4bd2-b775-1b79c0b9b861)

**2. 复现步骤**
这是一个必现问题，对于任何umijs项目都可以复现。
为了方便模拟发版，我就在本地使用serve作为服务器。

1. 启动服务，清空浏览器缓存并访问
yarn build
serve -s dist
我的应用现在有两个菜单：菜单A(/bmsys/station/list),  菜单B(/bmsys/station/aimode)
地址栏访问菜单A: http://localhost:3000/bmsys/station/list，
> 地址栏内请求url的方式，直接访问了服务器index.html, 返回了/umi.4b06d708.js
这个js应该是route.js的编译吧，里面有url和具体每个页面的JS的映射: 
点击菜单A: 加载 p__bmsys__station__list__index.2fc6da56.async.js
点击菜单B: 加载 p__bmsys__station__aiMode__index.11111111.async.js

只访问菜单A, 不要去点击菜单B, 那么浏览器缓存里目前是没有菜单B(p__bmsys__station__aiMode__index.11111111.async.js)

2. 停止服务，修改页面B，再打包并启动服务
因为页面B修改了，此时文件的hash值发生了变化，产生了新的文件名
菜单B: p__bmsys__station__aiMode__index.22222222.async.js

3. 关键点在于：点击菜单并不发起新请求，而是使用umi.4b06d708.js中存的路由js映射关系去拉对应的页面js。
此时点击菜单栏B,  还是访问原来的名称p__bmsys__station__aiMode__index.11111111.async.js，浏览器又没有这个文件缓存，向服务器发起请求，自然就报开头的错误了

**3. 解决办法**
方法一：

> [fz6m](https://github.com/fz6m) commented [on Nov 16, 2022](https://github.com/umijs/umi/issues/9793#issuecomment-1316856524)
Error screenshot: 的报错给一个具体的复现步骤看看。

我这么改了没效果呢？
1. 发版后，点击菜单切换时还是使用老的路由文件映射关系；
2. 禁用了nginx的缓存，会影响网站访问速度

方法二：是否可以点击菜单切换时，也重新请求一遍index.html, 这样就能更新路由和js文件映射关系了
没找到实现办法

方法三：当出现上述报错时，自动刷新页面 
要做到这一点，就得捕获到这个异常了，在app.tsx中找到了配置
`export const layout: RunTimeLayoutConfig = ({ initialState, setInitialState }) => {
     return {
         .......
         ErrorBoundary: MyErrorBoundary,
    }
}
`

> 自定义MyErrorBoundary对ChunkLoadError类型错误进行处理：
if (String(error).includes("ChunkLoadError")) {
      location.reload();
}

`import { Result } from 'antd';
import React, { ReactNode } from 'react';
interface MyErrorBoundaryProps {
  children: ReactNode;
}
interface MyErrorBoundaryState {
  hasError: boolean;
  errorInfo: string;
}
class MyErrorBoundary extends React.Component<MyErrorBoundaryProps, MyErrorBoundaryState> {
  state: MyErrorBoundaryState = {
    hasError: false,
    errorInfo: "",
  };
  static getDerivedStateFromError(error: Error) {
    return { hasError: true, errorInfo: error.message };
  }
  componentDidCatch(error: Error, errorInfo: React.ErrorInfo) {
    // 可以在这里记录错误信息，或者发送错误日志到后台
    console.error('ErrorBoundary caught an error:', error, errorInfo);
    // 这个特殊的错误，自动刷新页面
    if (String(error).includes("ChunkLoadError")) {
      location.reload();
    }
  }
  render() {
    if (this.state.hasError) {
      return (
        <Result
          status="error"
          title="Something went wrong"
          extra={this.state.errorInfo}
        />
      );
    }
    return this.props.children;
  }
}
export default MyErrorBoundary;`
可以解决此文件找不到的报错问题
但是依旧存在这么一个问题吧？
假设我一开始菜单A, 菜单B都点击了, 浏览器内就同时缓存了A.js, B.js了，页面B修改重新打包后名称变为了B2.js
此时点击菜单B，加载的是B.js，不刷新页面是没法看到新修改的内容B2.js的

**Comment by MachoManCk** [comment]
Hello, loser programmer。
Since you can ask this question, it means that you are not suitable for the front-end position

**Comment by fz6m** [comment]
得先确认缓存问题，因为资源带 hash 的前端项目，js / css 资源一般配置长期缓存（因为有 hash 是唯一的），而 html 是不缓存的，所以你提到的每次发版后用户还访问旧的 html 就不存在了，只要刷新一下页面得到的就是最新的 html ，会去加载最新的资源；需要你排查一下 cdn 或者 nginx 等资源提供的地方缓存规则。

根据上文描述，假如不是缓存问题，那有一个时机，就是在你发版时，同时有用户正在旧页面上浏览着，而你的 js 、css 资源又是全量替换，旧资源这个时候就没有了，那这个小概率的场景就会发生加载旧异步 js 错误，解决方案参考：#11920 、#10171 。

**Comment by deerLoves** [comment]
> 得先确认缓存问题，因为资源带 hash 的前端项目，js / css 资源一般配置长期缓存（因为有 hash 是唯一的），而 html 是不缓存的，所以你提到的每次发版后用户还访问旧的 html 就不存在了，只要刷新一下页面得到的就是最新的 html ，会去加载最新的资源；需要你排查一下 cdn 或者 nginx 等资源提供的地方缓存规则。
> 
> 根据上文描述，假如不是缓存问题，那有一个时机，就是在你发版时，同时有用户正在旧页面上浏览着，而你的 js 、css 资源又是全量替换，旧资源这个时候就没有了，那这个小概率的场景就会发生加载旧异步 js 错误，解决方案参考：#11920 、#10171 。

问题是用户把/user/login给挂收藏夹了，导致每次发完版，用户从收藏夹打开，就报错。umi.[hash].js 带了hash值，请问这个怎么处理呢？

**Comment by QingShan-Xu** [comment]
> > 得先确认缓存问题，因为资源带 hash 的前端项目，js / css 资源一般配置长期缓存（因为有 hash 是唯一的），而 html 是不缓存的，所以你提到的每次发版后用户还访问旧的 html 就不存在了，只要刷新一下页面得到的就是最新的 html ，会去加载最新的资源；需要你排查一下 cdn 或者 nginx 等资源提供的地方缓存规则。
> > 根据上文描述，假如不是缓存问题，那有一个时机，就是在你发版时，同时有用户正在旧页面上浏览着，而你的 js 、css 资源又是全量替换，旧资源这个时候就没有了，那这个小概率的场景就会发生加载旧异步 js 错误，解决方案参考：#11920 、#10171 。
> 
> 问题是用户把/user/login给挂收藏夹了，导致每次发完版，用户从收藏夹打开，就报错。umi.[hash].js 带了hash值，请问这个怎么处理呢？

你得找服务器原因, 请求头, google一下
