### ISSUE TITLE
[Bug] 当我把dynamicImport关闭后，访问页面会报Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by ayahua** [umijs/umi#12151]
我使用[#8930](https://github.com/umijs/umi/issues/8930#issue-1334129574)的方法，关闭了dynamicImport，但是启动项目后访问应用报错。
这是umi配置
![image](https://github.com/umijs/umi/assets/36917157/97c01d58-2aa9-4d08-a2a6-24e3dd5cc0d4)

这是报错信息
![image](https://github.com/umijs/umi/assets/36917157/6b99239c-9340-419e-9eff-f71e6939d8a0)

**Comment by ayahua** [comment]
我现在根据环境只在线上开启了这个配置，本地开发没有问题了，热更新也正常。但是线上首次切换页面还是会有一闪而过的白屏，后续再切换页面就正常了，感觉好像还是在按需加载一样，但是看资源请求是只有一个umijs了。

**Comment by fz6m** [comment]
默认 umi 4 是按页分包，每次切换新的页面都会去加载这个新页面的 js 分包，所以有一个加载过程，这个过程展示的加载组件可以在 `src/loading.tsx` 配置。

如果就是希望产物只有 `umi.js` 、`umi.css` 而不是很多异步分包文件的话，应该仅对生产开启这个 babel 插件。

至于你第一次加载白屏的原因，由于 SPA 本来就是一个单节点 html ，所以只有在 `umi.js` 加载完毕，并且 js 逻辑执行完毕，然后 react 才能开始渲染节点，才能看到内容，如果把自动分包关了，`umi.js` 就会包括所有路由的所有代码，即使你访问的页面用不到的代码都会全部下载完才开始渲染，所以这个过程可能是比较耗费时间的，需要检查下 js 产物的体积，如果你不希望自动分包，就要承担产物体积很大第一次加载很慢这种风险（或使用 hash + cache 响应头、CDN、gzip 压缩等加速 js 的下载）；如果产物没那么大（js 文件 5M 以内），就要看看到底是什么原因导致的。

如果你的产物只有 `umi.js` / `umi.css` ，那么闪屏肯定不是由于异步分包引起的，应该从加载速度慢，渲染速度慢或代码问题上排查。

如还有问题，需要给一个最小复现。
