### ISSUE TITLE
Mock file parse failed  regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by kennedy0527** [umijs/umi#1215]
umi version: 2.1.1
在Mock file內
使用async 便會噴出這個error

mock/a.js
```javascript
async function A () {
...
}

export default {
  'GET /api/test': A
}
```

試過在global.js 內 import '@babel/polyfill'; 

一樣無法解決

想請問該如何解決這個問題？

**Comment by sorrycc** [comment]
mock 里只能是 `(req, res) => {}`，不能用 async 吧，就算支持了也用不了。
