### ISSUE TITLE
[Bug] 允许css样式使用下划线分隔

### ISSUE THREAD

**Issue by cjdxhjj** [umijs/umi#12152]
## What happens?

本地开发测试好了，提交代码时报了大量lint错误导致无法提交
![5e2c9b6af393bf3d987c40f4409f136](https://github.com/umijs/umi/assets/5616997/c9312ef1-396e-4e2e-82e4-2e252073ddd9)
![image](https://github.com/umijs/umi/assets/5616997/adaa4677-ef9d-42a2-9c06-384112d5da29)
lint期望样式名称为displayNone或display-none,但是display-none样式名在tsx里会报错
![c75cdce9eebd50a20d994671f755586](https://github.com/umijs/umi/assets/5616997/878a1228-1ced-489f-b7e5-fff8f271dee7)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.1.2
- **Node Version**: 20
- **Platform**: windows 10

**Comment by 303394539** [comment]
less里面的中线分割符的lint要求属于正常的规范，在代码里引入应该用驼峰或者xx['xx-xx']。

**Comment by cjdxhjj** [comment]
但是style[''xx-xx']太丑了吧

**Comment by cjdxhjj** [comment]
不是说less里的中线有问题，我是说默认应支持下滑线

**Comment by 303394539** [comment]
想不使用的规范在本地stylelintrc关闭掉或者修改就可以了。规范如果不是因为stylelint升级必须改变的话，官方是很难修改来影响全局的，这也不是bug。只是习不习惯的问题。

**Comment by PeachScript** [comment]
默认 lint 规则允许短横线 `.my-btn` 和小驼峰 `.myBtn` 两种命名方式，分别适用于普通 CSS 和 CSS Modules（`styles.myBtn`），这也是社区的通用实践，Umi 不会对默认规则做修改

你的项目中如果一定要使用下划线，可以在 `.stylelintrc.js` 里自定义相关规则，具体步骤可参考 Stylelint 官方文档
