### ISSUE TITLE
如何配置才能使 js 和 css 文件同步加载呢？

### ISSUE THREAD

**Issue by leshalv** [umijs/umi#12157]
<img width="550" alt="image" src="https://github.com/umijs/umi/assets/30397655/7678374f-6d3a-4f58-8385-ee4fad0b6278">

**Comment by fz6m** [comment]
默认 umi 4 是自动按页分包，这样在你访问某个页面时需要下载的 js / css 资源是最少最优的。

不建议关闭异步分包，如果有特殊情况，参考 [可以关闭 dynamicImport 吗？](https://umijs.org/docs/introduce/faq#%E5%8F%AF%E4%BB%A5%E5%85%B3%E9%97%AD-dynamicimport-%E5%90%97) 关闭，但这会导致单文件 `umi.js` 产物体积很大，加载速度可能比较慢。

**Comment by zhongbo320** [comment]
但是异步加载且不允许修改的情况下，会导致异步加载的js可能获取一些初始化的数据获取不到，那该怎么办呢，确实不能关闭dynamicImport，但是也不允许直接在head里面异步加载chunk js
