### ISSUE TITLE
[Bug] Error tailwindcss generate failed when starting the project

### ISSUE THREAD

**Issue by izfei** [umijs/umi#12167]
## What happens?

Unable to start project
yarn start
info  - [plugin: ./node_modules/@umijs/plugins/dist/tailwindcss] tailwindcss service started
Rebuilding...
error - [plugin: ./node_modules/@umijs/plugins/dist/tailwindcss] tailwindcss generate failed after 5 seconds, please check your tailwind.css and tailwind.config.js
Done in 19.57s.

OS:windows
Node: v16.18.1
Umi v4.1.2
Tailwindcss: v3.4.0

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
你是通过 turborepo 并发启动的项目吗？

如有问题，需要提供一个最小复现。

**Comment by ngechu** [comment]
I am getting the same error, I am on fedora linux using umi max,the error occurs irregulary that is why it is so hard to replicate.

**Comment by ngechu** [comment]
> I am getting the same error, I am on fedora linux using umi max,the error occurs irregulary that is why it is so hard to replicate.

For any one who is still getting this error, try going back to an earlier branch version which was working , run it and then checkout to your latest branch. note: Do not stop the running project, just checkout. It has worked for me.
