### ISSUE TITLE
高危模块预警

### ISSUE THREAD

**Issue by soonyh** [umijs/umi#12164]
## What happens?

@umijs/preset-umi@4.1.2 依赖了高危模块vite@4.3.1

建议Upgrade to version 4.3.9 or later   

## Mini Showcase Repository(REQUIRED)

yarn audit

## How To Reproduce

yarn audit

![image](https://github.com/umijs/umi/assets/2361325/0eda4c03-c59d-4514-9bc9-3315418fcfa2)

## Context

- **Umi Version**:  4.1.2
- **Node Version**: 18.18.2
- **Platform**: pc

**Comment by fz6m** [comment]
欢迎 PR 升级 vite 依赖的版本到 v4 最新。
