### ISSUE TITLE
[Bug] umiJs4.0下使用exportStatic不起作用

### ISSUE THREAD

**Issue by gaomeng965** [umijs/umi#12160]
## What happens?

 umiJs4.0下使用exportStatic不起作用，所有打包出来的 预渲染的 html文件的内容一模一样，并且跟主页面的html内容一样，只有一个空节点，如下图，文档里面也没有相关描述需要配置别的地方啊。 4.0是不支持吗，不支持的话文档里面能介绍一下吗？
 
![image](https://github.com/umijs/umi/assets/22706391/e055d7bb-85b6-4161-b467-0ec7e92696ec)

 
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context
import { defineConfig } from '@umijs/max';
import routes from './routes';

export default defineConfig({
  antd: {},
  access: {},
  model: {},
  initialState: {},
  request: {},
  alias: {
    '@': '/src',
  },
  favicons: ['/favicon.png'],
  layout: {
    title: 'LifeOS',
  },
  routes,
  npmClient: 'yarn',
  tailwindcss: {},
  exportStatic: {
    extraRoutePaths: ['/home'],
  },
});
- **Umi Version**: "@umijs/max": "^4.1.2",
- **Node Version**: v16.18.1
- **Platform**:  window10

**Comment by fz6m** [comment]
默认 SPA 产物只有一个 `index.html` ， `exportStatic` 这个配置开启后，只是会按照路由表每个路径生成一个 html 而已，并不会渲染里面的内容，如果需要内容，需要配置 ssr ：

```ts
// .umirc.ts

  exportStatic: {},
  ssr: {
    builder: 'webpack'
  },
```

开启 ssr 时就要遵循 ssr 的使用规范，比如 window 不能出现在非浏览器阶段等，这意味着绝大部分 组件、第三方包、代码等 都必须支持 ssr 或者做了 ssr 兼容后才能使用。

注：如果你是 max 的应用并且使用了自带 layout 等功能，这些功能的代码都是不支持 ssr 的，因为这些功能都是后台相关的，没有 SEO 的需要，所以都是 csr only，无法和 ssr 一起使用。
