### ISSUE TITLE
[Bug] keepalive相关的文档在哪？

### ISSUE THREAD

**Issue by hengyanqwe** [umijs/umi#12169]
## What happens?

看见max已经带了，加上keepalive的配置就能用了，但是keepalive相关的文档在哪？官网上找不到，如果用的是第三方的库也不知道链接在哪/

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

看见max已经带了，加上keepalive的配置就能用了，但是keepalive相关的文档在哪？官网上找不到，如果用的是第三方的库也不知道链接在哪/

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

看见max已经带了，加上keepalive的配置就能用了，但是keepalive相关的文档在哪？官网上找不到，如果用的是第三方的库也不知道链接在哪/

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
See #12168
