### ISSUE TITLE
config 被 babel 转换，但是没有插入 polyfill

### ISSUE THREAD

**Issue by tolerance-go** [umijs/umi#1217]
在 config/config 使用 async/await 语法，运行 umi dev 提示 `ReferenceError: regeneratorRuntime is not defined`

**Comment by tolerance-go** [comment]
手动加入了 `import '@babel/polyfill';` 但是 config 文件不支持函数形式配置

**Comment by tolerance-go** [comment]
为什么把 runtime 关掉啊
https://github.com/umijs/umi/blob/b56ffa0ac2baedd945806eee19df17ff25afc804/packages/umi-build-dev/src/registerBabel.js#L42

**Comment by sorrycc** [comment]
config/config.js 不要使用 async/await 语法吧。
