### ISSUE TITLE
[Feature Request] 有没有nx + umi的monorepo demo

### ISSUE THREAD

**Issue by Crown1991** [umijs/umi#12176]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by tonywu6** [comment]
Hi! 我们有一个项目在用

https://github.com/secretflow/secretpad-frontend/blob/main/nx.json

**Comment by fz6m** [comment]
nx 是 monorepo 管理工具，和项目的脚手架是什么无关，自行探索使用方法即可。
