### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by shwzh** [umijs/umi#12179]
引入国际化，在文件中引入useIntl 中报错，查了文档需要这样引用

import { useIntl } from 'umi'

这样umi 没有在package.json中，就安装了umi

安装之后useIntl还是报错，报没有导出useIntl 模块

![image](https://github.com/umijs/umi/assets/25242043/3ce0d8f9-8581-484a-9b75-5c662f07a25a)

bing并且在运行的时候，会报umi 和 umijs/max 不能同时存在

![image](https://github.com/umijs/umi/assets/25242043/97f128aa-a29c-49cc-816d-7f00f39127aa)

**Comment by fz6m** [comment]
要先决定好你是要用 max 还是 umi ，两者的区别是 umi 不自带任何插件（如 antd / locale 等，需要手动配置），而 max 自带了这些，依赖数量不一样。

决定好之后，`package.json` 只能安装 `umi` 或 `@umijs/max` 其中一个，你这里都安装了就会报错了。

umi 的插件配置方式参考 https://github.com/umijs/umi/issues/8576#issuecomment-1984957794 。
