### ISSUE TITLE
[Bug] umi/max 4.1.2，想使用dva 无法导出 connect

### ISSUE THREAD

**Issue by siegaii** [umijs/umi#12172]
[Bug] umi/max 4.1.2，想使用dva 无法导出 connect, 请问我是直接安装 dva 导入connect好还是不推荐使用dva，还是这就是一个bug，还是文档没有更新，用起来很迷。

第一次用umi还是想拥抱umi的生态的,不是很懂如果是我用错了文档位置找错了可以贴一下正确使用的文档吗

## How To Reproduce

```ts
const LoginPage: React.FC = (props: any) => {
  console.log('props: ', props);
  return <div>login</div>;
};

export default connect(({ user }) => ({ // Cannot find name 'connect'.
  user,
}))(LoginPage);

```
![image](https://github.com/umijs/umi/assets/40651327/f1468b20-22e0-4f3e-bef8-85aceddcff0c)

## Context

- **Umi Version**: 4.1.2
- **Node Version**: 18、20
- **Platform**: macos 14.3.1

**Comment by siegaii** [comment]
是我用错了，没有开启dva插件配置，不过希望能更新一下相关文档给出 hooks 组件的用法案例，新手文档读起来有点迷

**Comment by liyi563257046** [comment]
你好我想问你一下，开启dva插件配置入口在哪里啊，我找不到配置文件

**Comment by chillJyx** [comment]
> 你好我想问你一下，开启dva插件配置入口在哪里啊，我找不到配置文件

应该在config里 dva: {}

**Comment by onepisYa** [comment]
> > 你好我想问你一下，开启dva插件配置入口在哪里啊，我找不到配置文件
> 
> 应该在config里 dva: {}

另外 vscode 你配置之后、也有会提示找不到 connect 、建议重新 `npm run start` 就好了。
