### ISSUE TITLE
[Feature Request] keepalive相关文档在哪啊？

### ISSUE THREAD

**Issue by hengyanqwe** [umijs/umi#12170]
## Background

看见max已经带了，加上keepalive的配置就能用了，但是keepalive相关的文档在哪？官网上找不到，如果用的是第三方的库也不知道链接在哪/

## Proposal

看见max已经带了，加上keepalive的配置就能用了，但是keepalive相关的文档在哪？官网上找不到，如果用的是第三方的库也不知道链接在哪/

## Additional context

看见max已经带了，加上keepalive的配置就能用了，但是keepalive相关的文档在哪？官网上找不到，如果用的是第三方的库也不知道链接在哪/

**Comment by fz6m** [comment]
See #12168

**Comment by codedart2018** [comment]
配置上，我明显感觉页面响应速度慢了！

**Comment by fz6m** [comment]
1. keepalive 不是 umi 官方提供的功能，目前是一个社区功能，来自于 [`alita`](https://github.com/alitajs/alita/blob/master/packages/plugins/src/keepalive.ts) ，同时也默认在 ant pro 的预设里提供，因为有一些情况 tab 太多可能确实需要这个功能。

2. react 官方目前没有正式的 keepalive 解决方案，所以目前社区存在的各种 keepalive 方案都是大家想各种办法 hack 来实现的，一定存在各种问题，所以只能在一个可用的范围内正常运行，根据使用的解决方案库的不同，可用性的范围也是不同的，所以使用 keepalive 就要承受一定的风险和预期，在一定范围内使用。

3. 如果感觉 keepalive 对开发速度造成影响了，可以在开发时不打开这个功能，设定 `keepalive: process.env.NODE_ENV === 'development' ? false : {}` 。

**Comment by ayahua** [comment]
请问哪里看的支持keepalive了？为啥我配置了之后，报Invalid config keys: keepalive？是需要用别的插件吗？我没有开启antd pro。

**Comment by zhangxinyong12** [comment]
> 请问哪里看的支持keepalive了？为啥我配置了之后，报Invalid config keys: keepalive？是需要用别的插件吗？我没有开启antd pro。

如何解决的？我也遇到这个提示了 。就使用了umijs，没有使用max
