### ISSUE TITLE
[Bug] 4.1.3 版本构建报错

### ISSUE THREAD

**Issue by showonne** [umijs/umi#12185]
## What happens?

<img width="908" alt="image" src="https://github.com/umijs/umi/assets/9353213/4abdb852-08ac-4963-8d58-bd8e0edace95">

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

复现步骤：执行 build 命令

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- umi: 4.1.3
- node.js: 18.15.0

**Comment by PeachScript** [comment]
是 vite 构建吗

**Comment by showonne** [comment]
> 是 vite 构建吗

是的

**Comment by PeachScript** [comment]
> 是的

好的，的确没覆盖到 vite 的场景，感谢反馈，我已经把 latest 回滚了，待会儿再发个 patch

**Comment by fz6m** [comment]
@PeachScript 

以下场景需不需要也验证下？之前我没试过这些情况：

1. MPA 模式；
2. SSR ；
3. exportStatic；
4. 只有一个路由这一个页面的应用；
5. 没有任何分包的应用（通过 [babel 插件](https://umijs.org/docs/introduce/faq#%E5%8F%AF%E4%BB%A5%E5%85%B3%E9%97%AD-dynamicimport-%E5%90%97) 或 [`routeLoader: cjs`](https://umijs.org/docs/api/config#routeloader) 的方式）；

**Comment by PeachScript** [comment]
@fz6m 很全面👍 

1 和 5 我在 PR 里加了跳过逻辑；2 和 3 不影响，之前在 dumi 里测试过，水合可以提速；4 可以正常工作

**Comment by PeachScript** [comment]
v4.1.4 已修复
