### ISSUE TITLE
[问题]: Umijs 如何动态话配置router 的排列顺序呢 ? #12177

### ISSUE THREAD

**Issue by Dssssds** [umijs/umi#12181]
## 问题
* umi4, 使用了 getInitialState 和 access.ts 进行了 router 的权限控制.
* 但是如何进行, router 侧边栏排列顺序的自定义呢.

## 最终效果如图:
![image](https://github.com/umijs/umi/assets/17268259/18e0e9a8-9dad-47ad-993f-b129934afd34)

**Comment by fz6m** [comment]
See https://github.com/umijs/umi/discussions/12177#discussioncomment-8714806
