### ISSUE TITLE
[Bug] 本地热更新第二次后报错

### ISSUE THREAD

**Issue by Emensionyu** [umijs/umi#12189]
## What happens?

我把项目的umi升级到4.0后，本地第一次热更新可以，第二次会出现一个报错，ncaught (in promise) ScriptExternalLoadError: Loading script failed.(error: https://10.242.144.172:7788/mf-va_remoteEntry.js)，

mfsu: {
    esbuild: true,
  },
## Context
- **Umi Version**:4.1.2
- **Node Version**:v16.16.0
- **Platform**:mac

**Comment by fz6m** [comment]
如果你要升级 umi 3 到 4 的话，除了参考现有文档，网上搜索相关文章和资料以外，最好新建一个 umi 4 项目一点一点往里挪，如果一整个拿进来问题可能很多你不好处理也没有头绪。

如果你这里 mfsu 出了问题，就先把 `mfsu: false` 关了，等 mfsu 关闭的情况应用不报错了，再开启它看看有什么问题。

如还有问题，需要给一个最小复现。
