### ISSUE TITLE
[Bug] [技术问题]: Umijs 如何动态话配置router 的排列顺序呢 ?

### ISSUE THREAD

**Issue by Dssssds** [umijs/umi#12182]
### 最终效果如以下图片:
![image](https://github.com/umijs/umi/assets/17268259/836205cf-498f-460d-89a5-f2cbdcb3f81a)

## 工程环境

- **Umi Version**: 4.*
- **Node Version**: 20.11.*
- **Platform**: mac

**Comment by fz6m** [comment]
See https://github.com/umijs/umi/discussions/12177#discussioncomment-8714806
