### ISSUE TITLE
[Bug] umi4.1 开启ssr 按照umi git仓库下的express demo 编写server.js，运行提示 ReferenceError: Request is not defined

### ISSUE THREAD

**Issue by s13382570** [umijs/umi#12199]
## What happens?
问题截图
![image](https://github.com/umijs/umi/assets/41321033/e9d6f7d9-8c98-47e9-a0dc-de0eb788afd7)

错误类型
(node:79370) UnhandledPromiseRejectionWarning: ReferenceError: Request is not defined

有没有使用umi4.1的，服务如何才能正常运行umi4.1打包的代码

**Comment by fz6m** [comment]
你指的 express 的 demo 是哪个，给一个最小复现看看吧。
