### ISSUE TITLE
[Bug] useModel使用问题

### ISSUE THREAD

**Issue by ZeXinWork** [umijs/umi#12195]
![image](https://github.com/umijs/umi/assets/71616798/22255ddf-8050-4d25-a601-860cf19c9825)
结构如下 代码使用方式为   const { gameConfig, setGameConfig } = useModel('Game.gameConfig');    结果报错 类型“"Game.gameConfig"”的参数不能赋给类型“"@@initialState"”的参数

**Comment by fz6m** [comment]
如果识别不到，参考文档的约定扫描范围看一下：https://umijs.org/docs/max/data-flow

如还有问题，需要给一个最小复现。
