### ISSUE TITLE
umi4如何调用getDvaApp或者有没有别的方法

### ISSUE THREAD

**Issue by jws132** [umijs/umi#12190]
import { getDvaApp } from 'umi';
const dispatch = getDvaApp()._store.dispatch;

**Comment by zmm2tysu** [comment]
> 注：使用 [react-query](https://umijs.org/docs/max/react-query) / [swr](https://github.com/vercel/swr) 管理请求状态，而不再使用与 redux 相关的工具。

请问这里的管理请求状态是啥意思？是指请求loading吗 @fz6m

**Comment by fz6m** [comment]
现代请求库帮你 管理了请求的 loading 态、避免竟态问题、失败自动重试、自动重新请求 等，不使用请求库项目的体验会很差，所以绝大多数项目都会使用请求库，比如 swr / react-query 。

**Comment by bxter** [comment]
我用dva，如何在应用一启动就能发出dispatch请求，触发，现在我找不到能初始化请求的地方，我的场景是需要应用启动，发起一个请求全局元数据的，然后保存到model里
我用的umi max

**Comment by fz6m** [comment]
参考 [全局初始状态](https://umijs.org/docs/max/data-flow#%E5%85%A8%E5%B1%80%E5%88%9D%E5%A7%8B%E7%8A%B6%E6%80%81) ，在应用启动时，会等待 `getInitialState` 这个函数获取应用的全局信息，请求完会放到一个叫 `@@initialState` 的 model 里可以直接用，然后应用会开始渲染，这个期间如果请求 api 花费时间较长，使用 `src/loading.tsx` 定义全局加载动画。
