### ISSUE TITLE
umi@2 build之后页面空白，没有任何报错

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#1219]
问题：在一个项目中，umi dev，开发表现正常。执行umi build之后，部署后页面空白，没有任何错误提示。

尝试修复：尝试了之前提到过的方法，都无法修复，排查了不是部署的问题。

最后只好手动定位，重复的umi build。最终确定是由于组件的propTypes中使用了其他组件的propTypes的属性。

重现Demo：https://github.com/umi-cli-test/proptypes
重现步骤：
./src/components/Head.js

```
7  static propTypes = {
8    ...Title.propTypes,
9    paddingCorner:Label.propTypes.paddingCorner
10   // paddingCorner:PropTypes.number
11 };
```
如上诉所示，在Head的propTypes中使用了Label的propTypes，umi dev可以渲染页面。umi build 页面空白。

如下修改后，umi build后页面正常：
./src/components/Head.js

```
7  static propTypes = {
8    ...Title.propTypes,
9    // paddingCorner:Label.propTypes.paddingCorner
10   paddingCorner:PropTypes.number
11 };
```
重现Demo：https://github.com/umi-cli-test/proptypes

**Comment by sorrycc** [comment]
看了会，没看出问题原因。你不用 umi，用 create-react-app 试试，会不会也有这个问题？

**Comment by sorrycc** [comment]
这应该没 umi 没啥关系。

**Comment by dilidili** [comment]
和 umi 没关系，原因在 https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/issues/29 这个 issue 中有说明。简单解决方案是修改下 extends ParentClass 的名称，如：

```js
import React from "react";
import PropTypes from "prop-types";
import Component from "./Title";
import Label from "./Label";

export default class Head extends Component {
  static propTypes = {
    ...Title.propTypes,
    paddingCorner:Label.propTypes.paddingCorner
    // paddingCorner:PropTypes.number
  };
  static defaultProps = {
    title: "hello"
  };
}
```
