### ISSUE TITLE
[Bug] 如果在构建时添加了 `antd: {}` 空对象的配置时，antd 的运行时配置不会被执行

### ISSUE THREAD

**Issue by nnmax** [umijs/umi#12201]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
在 #12202 完成。
