### ISSUE TITLE
[Bug] @umijs/max 项目 app.ts 中的 layout 函数在项目运行成功后执行了 2 次

### ISSUE THREAD

**Issue by tanqin** [umijs/umi#12205]
## What happens?

@umijs/max 项目 app.ts 中的 layout 配置函数在项目运行成功后执行了 2 次，按理说只需要执行 1 次才对。

## How To Reproduce
创建一个最简单的 @umijs/max 项目，将 app.ts 的代码替换为如下内容：
```tsx
import { RunTimeLayoutConfig } from '@umijs/max'

export async function getInitialState(): Promise<{ name: string }> {
  return { name: '@umijs/max' }
}

export const layout: RunTimeLayoutConfig = () => {
  console.warn('layout executed...')

  return {
    layout: 'mix'
  }
}
```
运行项目，发现 `layout executed...` 打印了 2 次，如下图：
![image](https://github.com/umijs/umi/assets/63828394/9889221c-627a-4ddb-8328-583256b130ad)
这个 layout 运行时配置函数不应该只需要执行 1 次吗？

## Context

- **Umi Version**:  "@umijs/max": "^4.1.2"
- **Node Version**: 16.17.1
- **Platform**: windows10

**Comment by fz6m** [comment]
在各种运行时的配置里，除了特殊的，比如 `getInitialState` 这种初始化默认状态等只会运行一次以外，其他的都是不确保运行几次的，因为他就和一个 props 一样，是一个 config 配置，一个配置或者说属性不应该因为触发了几次读取就造成不一样的结果，如果每次读取不一样，说明存在预期之外的副作用，这是不应该的。

如果代码中不存在意外的副作用，无论调用多少次，这里获取到的 config 结果都应该是一致的，所以运行几次并不重要，就好像一个 prop 属性可能被很多地方都读取触发 get 一样。
