### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by linyufei123** [umijs/umi#12206]
$umi g tailwindcss
info  - Write package.json
set config:tailwindcss on /Users/umi/playground/.umirc.ts
set config:plugins on /Users/umi/playground/.umirc.ts
info  - Update .umirc.ts
info  - Write tailwind.config.js
info  - Write tailwind.css

执行命令 报错

**Comment by fz6m** [comment]
在你提供的这个日志打印完的最后一步就是自动去安装依赖了，如果无法安装，可能是找不到当前的包管理工具，可以看下你的 umi 配置文件里有没有 `npmClient` 这个配置。

如果还有问题，需要给一个最小复现。
