### ISSUE TITLE
[Bug] @umijs/max 项目 .env.development 配置的环境变量不生效，.env 中的环境变量才生效 

### ISSUE THREAD

**Issue by tanqin** [umijs/umi#12207]
## What happens?

@umijs/max 项目 .env.development、env.production 文件配置的环境变量不生效，但将其放到 .env 文件中环境变量可以生效，导致我无法为开发环境和生产环境配置不同的环境变量值。
目前我的解决的方案是在 `config/` 目录下新建 `config.development.ts` 和 `config.production.ts` 文件，安装开发依赖 cross-env，修改 `package.json` 中的脚本指令，如下图：
![image](https://github.com/umijs/umi/assets/63828394/411681ac-658d-4751-9742-1733df3658d2)
虽然这种做法可以解决问题，但是 .env.development、env.production 文件不生效，就导致我的一部分配置放置到 .env 文件中（比如`PORT=3000` 和 `DID_YOU_KNOW=none`），另一部分又放到 `config/` 目录下，有很强的割裂感。

## How To Reproduce
同样一个环境变量值`UMI_APP_MY_TOKEN="aaa:aaa"`，放在 `.env` 文件中，可以通过 `process.env.UMI_APP_MY_TOKEN`访问到，但是放到 `config.development.ts` 或 `config.production.ts` 文件，就访问不到了。

## Context

- **Umi Version**:  "@umijs/max": "^4.1.2"
- **Node Version**: 16.17.1
- **Platform**: windows10

**Comment by fz6m** [comment]
要区分 nodejs 用的环境变量和 browser 里用的是不一样的，从以下几个渠道：

1. `.env` 系列环境变量文件里声明的变量

2. 启动命令行声明的变量：如 `cross-env XXX=yyy umi dev`

这些变量默认会注入到 nodejs 环境，只能在 umi 配置文件里通过 `process.env.XXX` 使用。

如果要在项目里使用，那就是 browser 环境，他不会通用 nodejs 的变量，不然就乱套了，必须要手动注入想要的变量到项目里，通过 [`define`](https://umijs.org/docs/api/config#define) 配置。

你会发现还要多 `define` 注入一次比较麻烦，所以就有了 `UMI_APP_` 这个前缀的变量自动会被 define 注入到项目里的约定，省去了这个麻烦。

以上所描述的，基本上对任何一个 cli 工具都通用，只不过他们的注入配置项，或者约定的自动注入前缀不同，如 `VUE_APP` 、`REACT_APP` 等，具体请自行学习。
