### ISSUE TITLE
umi-plugin-dll在生成dll文件时webpackConfig中缺少publicPath

### ISSUE THREAD

**Issue by ClarkXia** [umijs/umi#1221]
如题，publicPath原先默认为'/'，开启dll选项后umi.dll.js里面的publicPath将变为空
`
<img src="/static/img.png" />
变为
<img src="static/img.png" />
`

**Comment by sorrycc** [comment]
为啥会用 dll 转换项目本地文件？

**Comment by ClarkXia** [comment]
> 为啥会用 dll 转换项目本地文件？

是引用了第三方类库，其中的有部分实现如下
`
import Img from './img.png';
export default () => <img src={img} />;
`
在dll配置时没有exclude掉的话 类似加载图片的方式都会有问题
