### ISSUE TITLE
[Bug] umi4 clickToComponent 会触发点击事件

### ISSUE THREAD

**Issue by jrr997** [umijs/umi#12214]
## What happens?

使用 umi4 的 clickToComponent 功能，Alt + 鼠标左键点击某个元素时，会触发这个元素的点击事件。如果是按钮的话，就会触发按钮的点击事件，从而触发业务逻辑，这在大部分情况会造成麻烦。
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.
我的期望是不要触发元素的点击事件。可以参考([react-dev-inspector](https://github.com/zthxxx/react-dev-inspector))

## Context

- **Umi Version**: 4.1.4
- **Node Version**: 16.20.1
- **Platform**: MacOS 14.3 (23D56)

**Comment by fz6m** [comment]
这个功能用的是 [click-to-component](https://github.com/ericclemmons/click-to-component) 这个库，因为它是个第三方包，所以可能不维护了或者发生一些问题，但这只是个辅助的小功能，你不用它就行了。

如果你想要一个其他的更好的 inspect 检查工具，就自己配置对应的工具来使用就行，有些工具比如你提到的 react-dev-inspector 也有 umi 4 配置的例子可以参考，具体请自行研究。
