### ISSUE TITLE
[Bug] @umijs/utils not found during install

### ISSUE THREAD

**Issue by SquirrelCorporation** [umijs/umi#12213]
## What happens?

Since the latest updates, a clean install is impossible and throw 

`
278.4 fatal - Error: Register plugin /client/node_modules/@umijs/request-record/dist/cjs/index.js failed, since Cannot find module '@umijs/utils'
278.4 Require stack:
278.4 - /client/node_modules/@umijs/request-record/dist/cjs/index.js
278.4 - /client/node_modules/@umijs/max/node_modules/@umijs/core/dist/service/plugin.js
278.4 - /client/node_modules/@umijs/max/node_modules/@umijs/core/dist/service/pluginAPI.js
278.4 - /client/node_modules/@umijs/max/node_modules/@umijs/core/dist/index.js
278.4 - /client/node_modules/@umijs/max/node_modules/umi/dist/service/service.js
278.4 - /client/node_modules/@umijs/max/node_modules/umi/dist/cli/cli.js
278.4 - /client/node_modules/@umijs/max/node_modules/umi/dist/index.js
278.4 - /client/node_modules/@umijs/max/dist/cli.js
278.4 - /client/node_modules/@umijs/max/bin/max.js
278.4     at Plugin.apply (/client/node_modules/@umijs/max/node_modules/@umijs/core/dist/service/plugin.js:76:15)
278.4     at Service.initPlugin (/client/node_modules/@umijs/max/node_modules/@umijs/core/dist/service/service.js:463:33)
278.4     at Service.run (/client/node_modules/@umijs/max/node_modules/@umijs/core/dist/service/service.js:259:18)
278.4     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
278.4     at async Service.run2 (/client/node_modules/@umijs/max/node_modules/umi/dist/service/service.js:65:12)
278.4     at async run (/client/node_modules/@umijs/max/node_modules/umi/dist/cli/cli.js:56:7) {
278.4   [cause]: Error: Cannot find module '@umijs/utils'
278.4   Require stack:
278.4   - /client/node_modules/@umijs/request-record/dist/cjs/index.js
278.4   - /client/node_modules/@umijs/max/node_modules/@umijs/core/dist/service/plugin.js
278.4   - /client/node_modules/@umijs/max/node_modules/@umijs/core/dist/service/pluginAPI.js
278.4   - /client/node_modules/@umijs/max/node_modules/@umijs/core/dist/index.js
278.4   - /client/node_modules/@umijs/max/node_modules/umi/dist/service/service.js
278.4   - /client/node_modules/@umijs/max/node_modules/umi/dist/cli/cli.js
278.4   - /client/node_modules/@umijs/max/node_modules/umi/dist/index.js
278.4   - /client/node_modules/@umijs/max/dist/cli.js
278.4   - /client/node_modules/@umijs/max/bin/max.js
278.4       at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
278.4       at mod._resolveFilename (/client/node_modules/@umijs/max/node_modules/umi/dist/service/requireHook.js:13:26)
278.4       at Module._load (node:internal/modules/cjs/loader:983:27)
278.4       at Module.require (node:internal/modules/cjs/loader:1230:19)
278.4       at require (node:internal/modules/helpers:179:18)
278.4       at Object.<anonymous> (/client/node_modules/@umijs/request-record/dist/cjs/index.js:35:20)
278.4       at Module._compile (node:internal/modules/cjs/loader:1368:14)
278.4       at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
278.4       at Module.load (node:internal/modules/cjs/loader:1205:32)
278.4       at Module._load (node:internal/modules/cjs/loader:1021:12) {
278.4     code: 'MODULE_NOT_FOUND',
278.4     requireStack: [
278.4       '/client/node_modules/@umijs/request-record/dist/cjs/index.js',
278.4       '/client/node_modules/@umijs/max/node_modules/@umijs/core/dist/service/plugin.js',
278.4       '/client/node_modules/@umijs/max/node_modules/@umijs/core/dist/service/pluginAPI.js',
278.4       '/client/node_modules/@umijs/max/node_modules/@umijs/core/dist/index.js',
278.4       '/client/node_modules/@umijs/max/node_modules/umi/dist/service/service.js',
278.4       '/client/node_modules/@umijs/max/node_modules/umi/dist/cli/cli.js',
278.4       '/client/node_modules/@umijs/max/node_modules/umi/dist/index.js',
278.4       '/client/node_modules/@umijs/max/dist/cli.js',
278.4       '/client/node_modules/@umijs/max/bin/max.js'
278.4     ]
278.4   }
278.4 }
278.7 fatal - A complete log of this run can be found in:
278.7 fatal - /client/node_modules/.cache/logger/umi.log
278.7 fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
`

<img width="541" alt="Screenshot 2024-03-18 at 10 44 01" src="https://github.com/umijs/umi/assets/161006161/ba96d837-6d11-4239-bf3d-64370a7d50e5">
<img width="718" alt="Screenshot 2024-03-18 at 10 43 55" src="https://github.com/umijs/umi/assets/161006161/c788fa6c-c48c-4453-a00b-0302c9af9795">
<img width="939" alt="Screenshot 2024-03-18 at 10 43 43" src="https://github.com/umijs/umi/assets/161006161/af4c0ba0-fa0e-4b8c-9096-17f191803632">

(Repo: https://github.com/SquirrelCorporation/SquirrelServersManager)

## Context

- **Umi Version**: latest
- **Node Version**: latest
- **Platform**: Ubuntu & Macos

**Comment by fz6m** [comment]
实际上你不需要安装 `@umijs/utils` 这个包到你的 package.json 里，如果依赖有问题，就把 node_modules 删了再重新安装一遍试试吧。
