### ISSUE TITLE
如果是swagger 2.0的文档，可以使用这个生成api文件吗？我试了下生成会失败。如果把文件下载下来改成json然后加上openapi：'3.1.0'配置可以生成，但是有的get接口的参数没有生成定义，为空 

### ISSUE THREAD

**Issue by wangyuan0108** [umijs/umi#12227]
如果是swagger 2.0的文档，可以使用这个生成api文件吗？我试了下生成会失败。如果把文件下载下来改成json然后加上openapi：'3.1.0'配置可以生成，但是有的get接口的参数没有生成定义，为空 

在另一个库提了，但是咩有人回应

https://github.com/chenshuai2144/openapi2typescript/issues/145

**Comment by fz6m** [comment]
这个属于专有化的工具，和 umi 仓库本身无关，主要看 openapi 这个插件生成的逻辑是怎样的，支不支持你要的也要看里面源码或者用到的依赖库才知道。

如果你发现有问题，就去看下源码探究下吧。
