### ISSUE TITLE
可否提供umi2.0+electron的开发模板

### ISSUE THREAD

**Issue by wangxingkang** [umijs/umi#1222]

**Comment by sorrycc** [comment]
如果有时间，我会更新下 https://github.com/umijs/umi-example-electron ，欢迎 PR。

**Comment by wangxingkang** [comment]
查看源码roadhog的作用就是将`src/main/index.js`编译至`app/dist/main.js` umi 应该可以直接支持，请个思路替换一下

**Comment by leftstick** [comment]
提供下我的思路和配置：[Hosts Master](https://github.com/leftstick/hosts-high)。

umi: `^2.12.8`
electron: `^7.1.7`

**Comment by WangJM001** [comment]
基于Umi的Electron框架，一行命令(pnpm create poros)生成Electron应用，快速开发、打包， 集成了各种功能，方便好用，感兴趣的可以看下，欢迎Star，项目还在不断迭代中。
https://github.com/porosjs/poros
