### ISSUE TITLE
[Feature Request] 改进 prepare 阶段的性能问题

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#12224]
## Background

![image](https://github.com/umijs/umi/assets/35128/dc0d038f-9ce0-4714-8a52-b0f294e0007c)

某个非典型项目，执行 umi setup，总耗时 1m6s，其中 1m1s 的时间都在做 deepClone。

注释掉这段代码的前后对比。

<img width="620" alt="image" src="https://github.com/umijs/umi/assets/35128/d84fbc34-1217-4843-89a0-14eef6168b12">

代码在 https://github.com/umijs/umi/blob/a278fad/packages/preset-umi/src/features/prepare/prepare.ts#L23 。

## Proposal

应该不需要做 deep clone。

**Comment by fz6m** [comment]
这里 clone 后续把 `file.contents` 删了，如果不 clone 的话，其他用 prepare 钩子的函数里这个 `buildResult` 参数里面就没有 `contents` 了，所以目测得想个其他的方法，另外 `delete` 其实也是比较耗性能的操作。

**Comment by stormslowly** [comment]
这部分的信息只有 mfsu 在用，可以直接用引用；删除 content 的初衷估计想尽快释放这部分的内存。如果一直挂在 appData 上相当于多存了一份代码。

**Comment by xusd320** [comment]
yuyanAssets watch mode, 进入到 mako bundler 之前 delay 3s, mako bundler 反而能快个 2s 多，也是这个 deepClone 造成的
