### ISSUE TITLE
[Bug]Umi max项目作为monorepo子项目时，执行max setup报错

### ISSUE THREAD

**Issue by ZH-seven** [umijs/umi#12232]
## What happens?
在**windows**下

使用yarn提供的workspace的功能，将umi max创建的项目作为子项目时

执行yarn拉取依赖，会触发"postinstall": "max setup"，然后执行报错
![image](https://github.com/umijs/umi/assets/24790960/c23eb67c-c82a-437c-abc5-c34642b9e703)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

复现仓库：https://github.com/ZH-seven/test-umi-monorepo.git
windows执行yarn会报错

## Context

- **Umi Version**: 最新版本 umi max
- **Node Version**: 16
- **Platform**: windows

**Comment by ZH-seven** [comment]
mac下无此问题

**Comment by fz6m** [comment]
1. 可能是 node 版本太低了，因为 [node 16](https://github.com/nodejs/Release) 去年就不维护了，有安全问题也不会更新了，如果是新项目，直接用 node 18 或者 20 就可以（ node 18 明年就不维护了 ），如果是旧项目，升级到 node 16 的最新版本看看，理论上 16 和 18 没太大区别。

2. 我看你这里的路径是 `D: \test-umi-monorepo\test-umi-monorepo\node_modules\node_modules\umi\bin\umi.js'` ，有两个 node_modules ，依赖可能不对，要不删了 node_modules 重新安装下依赖看看。

3. 你提供的仓库链接打不开。

4. 如果要用 yarn workspace ，最好用 yarn v4 版本。

如还有问题，需要给一个最小复现。

**Comment by ZH-seven** [comment]
@fz6m

**Comment by ZH-seven** [comment]
@fz6m 感谢回复
1. node 18也试了，还是有问题
2. 不是依赖问题，试过多次了，感觉是这个命令在找路径时的问题，出现了双层的node_modules
3. 仓库忘记设置可见了，已打开
4. yarn 使用的1.22.22，实际上workspace的功能没啥问题，依赖可以正常拉取，yarn workspace umiProj run start也能正常启动umi项目，只是max setup这个命令执行报错

**Comment by fz6m** [comment]
我没有 win 的设备，没法本地调试，你可以调试一下看看是哪里报错导致的。
