### ISSUE TITLE
yarn create umi 创建项目失败

### ISSUE THREAD

**Issue by BestKai** [umijs/umi#12233]
使用 yarn create umi 创建项目失败
![image](https://github.com/umijs/umi/assets/8436462/4fe0e552-33a2-419c-a7b9-4a456491b304)
![image](https://github.com/umijs/umi/assets/8436462/0093f04e-2685-46d1-8764-b0c7c714c7c3)
node 版本是16
husky 9最低要求node18

**Comment by fz6m** [comment]
所谓的 node 16 是兼容 umi 3 的旧项目升级，存在 node 14 和 16 的项目，而初始化一个新的 umi 4 项目，没有历史包袱，所以使用 node 18 或 20 即可。

由于 node 16 已经不维护了，未来有任何安全问题都是隐患，包括 github actions 、vercel 等都已经在废止对旧版本 node 的使用，所以新项目不应该使用旧的有隐患的 node 版本，应该用现在的最新版本。

另外对于 husky 来说，v9 是最新版本，我们应该生成的都是最新的东西，而不是继续提供旧一个大版本的东西。

如果对此处 husky 有加强的想法，可以提一个 PR ，在创建模板时识别用户用的是 16 还是 >=18 ，之后动态生成不同版本的 husky 。

**Comment by songshenma** [comment]
> node 16 已经不维护了，未来有任何安全问题都是隐患，包

咨询下，umi3.5在pnpm node18下支持么，本地报错一直过不去，如果18对umi3.5不友好，是否需要在yarn pnpm 等都锁定16或者14的版本
