### ISSUE TITLE
[Bug] 启动项目编译时，请求 js 文件，不要返回 devtools 的 bundle stats html 页面

### ISSUE THREAD

**Issue by bytemain** [umijs/umi#12235]
## Background

我们是一个 egg 写的 ssr 页面，是直接用 scripts 标签加载的 `${HOST}/umi.js` 这个文件，在 umi4 下，未编译完成时请求这个地址会返回一个 html 页面，会导致解析 js 失败
![CleanShot 2024-03-26 at 16 22 36@2x](https://github.com/umijs/umi/assets/13938334/748d6ebd-d6bc-469f-9773-f5c7123627eb)

## Proposal

希望能通过环境变量关掉，现在可以用 `process.env.OKAM` 关掉，但是会带来其他的一些副作用

**Comment by 303394539** [comment]
或者可以直接api.skipPlugins(['devTool']); 直接不启动这个过程，然后自己再定制

**Comment by PeachScript** [comment]
应该可以通过 ContentType 是否为 HTML 来决定是否跳过，交给 webpack 来处理

**Comment by bytemain** [comment]
request 似乎没有 ContentType 的概念？能否直接判断用户请求的 path 结尾为 js/css 等就跳过

**Comment by PeachScript** [comment]
> request 似乎没有 ContentType 的概念

我说错了，是 accept，类似：https://github.com/umijs/umi/blob/fb73a285c32d31ea45da2bb2ba7b096fcc8bb453/packages/server/src/server.ts#L175

**Comment by fz6m** [comment]
确定这么改可以解决问题吗。

因为现代浏览器的 accept 是一大串：

<code>text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7</code>

浏览器去请求一个 `/umi.js` 既然会带上这个 accept ，还是会得到 devtools 的加载页面。

**Comment by bytemain** [comment]
是的，判断 accept header 解决不了我的问题，那我还是希望有一个环境变量或者 config 中的配置想来控制这个能力

**Comment by fz6m** [comment]
由于现代浏览器 `accept` 都是推测式的一大串内容，所以对于 html 还是 js 没有本质的区别，所以 `accept` 是区分不了 html 还是 js 的。

我目测这里用环境变量开关或者判断下请求是不是 `.js` 结尾较好，因为此处想解的问题只是 `请求非 HTML 不要给我返回 loading 的 HTML 页面，正常阻塞就好` 。

**Comment by shanyijin** [comment]
> 或者可以直接api.skipPlugins(['devTool']); 直接不启动这个过程，然后自己再定制

老白！！我来试试你这个点子
