### ISSUE TITLE
[Bug]umi$4.1.5 使用@umijs/plugin-qiankun@2.25.2 报错

### ISSUE THREAD

**Issue by jadestarzuo** [umijs/umi#12242]
umi4 官网 npx create-umi@latest 新建项目之后

- **Node Version**: v14.21.3
"umi": "^4.1.5",
"@umijs/plugin-qiankun": "^2.25.2",

![image](https://github.com/umijs/umi/assets/25679725/4adb3ceb-d020-4c17-8e55-708c41c11ac6)

.umirc.ts 文件增加配置：
plugins: ["@umijs/plugin-qiankun"],
  // 支持qiankun
  qiankun: {
    slave: {},
  },

之后执行
npm install  或者 npm  start 
都提示以下错误：
<img width="888" alt="image" src="https://github.com/umijs/umi/assets/25679725/ab0e2039-f577-486b-a5dc-0701cce5a65a">

fatal - Error: Register plugin /Users/zyx/workspace/bigdata/odin-home/node_modules/@umijs/plugin-qiankun/lib/index.js failed, since Cannot read property 't' of undefined

切换为node16.20.0
执行install的时候,提示：
<img width="649" alt="image" src="https://github.com/umijs/umi/assets/25679725/cfef574a-7585-4cba-b488-a1ea6380cece">

咨询gpt，得出结论是 @umijs/plugin-qiankun@2.44.1 ，兼容版本是umi@3

有没有遇到类似问题的大佬，给看看呢？

**Comment by sorrycc** [comment]
@umijs/plugin-qiankun 是 umi 3 使用的，umi 4 的 qiankun 插件应该是 `@umijs/plugins/dist/qiankun`。

**Comment by jadestarzuo** [comment]
> @umijs/plugin-qiankun 是 umi 3 使用的，umi 4 的 qiankun 插件应该是 `@umijs/plugins/dist/qiankun`。

你这么一说，我想起来，刚才试了下，我卸载@umijs/plugin-qiankun ，改成install  @umijs/plugins，然后就能根据这个路径@umijs/plugins/dist/qiankun  找个qiankun
