### ISSUE TITLE
[Bug] umi4 如何关闭懒加载

### ISSUE THREAD

**Issue by shanhexi** [umijs/umi#12259]
现在我的应用为桌面端应用，并且前端启动之前首先要起java，因此我有足够多的时间加载js资源
我应该如何取消懒加载，让js资源可以在java启动的过程中全部加载进来

**Comment by fz6m** [comment]
参考 [可以关闭 dynamicImport 吗？](https://umijs.org/docs/introduce/faq#%E5%8F%AF%E4%BB%A5%E5%85%B3%E9%97%AD-dynamicimport-%E5%90%97) ，在生产构建时，开启该 babel 插件即可。
