### ISSUE TITLE
umi路由的和react-router 4表现不一致？

### ISSUE THREAD

**Issue by shend** [umijs/umi#1226]
我目前在使用`antd pro`，配置了这么一段路由：
```js
      // test
      {
        path: '/tests',
        name: 'tests',
        icon: 'experiment',
        component: './Test',
        exact: true,
        routes: [
          {
            path: '/tests/:id([0-9]+)',
            component: './Test',
          },
        ],
      },
```
然后我发现这种情况下无法访问到`/tests/100`，每次访问都出现404错误。

但是我在其他项目中使用`react-router 4`时配置的如下路由就能正常访问到`/tests/100`：
```js
  <Switch>
    <Route exact path='/tests' component={Test} />
    <Route path='/tests/:id([0-9]+)?' component={Test} />
  </Switch>
```

请问我应该怎么配置umi的路由才能实现和react-router 4一样的功能。

**Comment by sorrycc** [comment]
把 `exact: true` 删了，这样匹配不到 `/tests/100` 的，react-router@4 也一样。

**Comment by shend** [comment]
umi删除了`exact: true`后访问`/tests/100`实际匹配的是`/tests`；react-router@4删除之后也是只会匹配到`/tests`，所以react-router@4正常工作需要`exact: true`。
