### ISSUE TITLE
[Bug] useModel 类型“xxxx”的参数不能赋给类型“Namespaces”的参数。

### ISSUE THREAD

**Issue by gongdaxia** [umijs/umi#12260]
umi 版本为  umi/max  4.1.6;
nodejs 版本  18.17.1
出现的问题，自定义的hooks使用useModel，无法识别，
报错
**类型“xxxxx”的参数不能赋给类型“Namespaces”的参数。**
![image](https://github.com/umijs/umi/assets/24599830/fa65f7f1-9e52-4899-b79a-8277623ebe14)
![image](https://github.com/umijs/umi/assets/24599830/5241a44e-bd2d-41ec-8cbe-c864e1e22bec)
但是同时实例的global可以识别
![image](https://github.com/umijs/umi/assets/24599830/2d7fb17b-8dd7-4e5f-9c8b-e15e9540d23e)
我的useCount.ts 和 global内容几乎一致
如果是bug，请尽快解决，如果是我写的有问题，请帮忙说明一下

**Comment by fz6m** [comment]
model 文件要符合 [这些位置](https://umijs.org/docs/max/data-flow#%E5%88%9B%E5%BB%BA-model) 才能被自动加载。

关于没有类型提示的问题，你得把项目启动起来，或者运行 `pnpm max setup` 生成一次临时文件，这个临时文件里包含了最新的类型提示，不然你新建的 model 文件不会生成类型提示，所以就报错了。
