### ISSUE TITLE
layout布局rightContentRender问题

### ISSUE THREAD

**Issue by goo-lz** [umijs/umi#12262]
import { RunTimeLayoutConfig } from '@umijs/max';

export const layout: RunTimeLayoutConfig = (initialState) => {
  return {
    // 常用属性
    title: 'Ant Design',
    logo: 'https://img.alicdn.com/tfs/TB1YHEpwUT1gK0jSZFhXXaAtVXa-28-27.svg',

    // 默认布局调整
    rightContentRender: () => <RightContent />,
    footerRender: () => <Footer />,
    menuHeaderRender: undefined,

    // 其他属性见：https://procomponents.ant.design/components/layout#prolayout
  };
};

默认布局调整无法设置，提示报错无法运行

**Comment by fz6m** [comment]
如果你想调布局版式的话，有个 `layout` 的选项，可以配 `layout: 'mix'` 之类的。

本质上 max 自带的这个 layout 就是 [`ProLayout`](https://procomponents.ant.design/components/layout#api) ，可以看这个链接里的文档和选项，自己试着配一配，弄出来自己想要的样子。

如还有问题，需要给一个最小复现。
