### ISSUE TITLE
layout布局右侧rightContentRender无法添加

### ISSUE THREAD

**Issue by 2122321321** [umijs/umi#12269]
![微信图片_20240408205526](https://github.com/umijs/umi/assets/115085561/ed7bafd0-a4e1-4b00-b3a6-1882e058e212)

export const layout: RunTimeLayoutConfig = () => {
  return {
    title: '',
    logo: 'https://img.alicdn.com/tfs/TB1YHEpwUT1gK0jSZFhXXaAtVXa-28-27.svg',
    layout: 'mix',
    rightContentRender: () => <RightAndFooter />,
  };
};
但是在 <RightAndFooter />处报错
Parsing error: '>' expected.eslint
“RightAndFooter”表示值，但在此处用作类型。是否指“类型 RightAndFooter”?

**Comment by fz6m** [comment]
如果要写 jsx 节点的语法，文件后缀必须是 tsx ，改一下后缀名。
