### ISSUE TITLE
我想用@umijs/max 开发H5的项目，有没有什么项目模版可以参考

### ISSUE THREAD

**Issue by MaybeQHL** [umijs/umi#12273]
ant-mobile、getInitialState、数据流、请求....

**Comment by fz6m** [comment]
不建议使用到 h5 。

umi 是一个 react 的以企业中后台 pc 端开发为主要场景的框架，为了快速菜单成型和一键开关各种功能，默认包含了大量的模板代码和运行时，这在使用上很便利、效率高，但产物体积默认较大，考虑到 to B 中后台场景也会同时使用一些较大体积的组件库、表单库、图表库等，所以完整项目的产物一般都很大，而大部分情况企业内网速又不是限制条件。

但如果用到 h5 ，在网速上可能没有那么快，同时产物较大体积不适合更快的加载显示，体验不是最优的；另外企业用户的电脑浏览器版本较高，所以 umi 默认构建产物是只兼容现代浏览器的，如果在手机上，浏览器兼容情况会再恶化一些，虽然不至于达到 “非现代” 的情况，但不是一个完美的方案。

综上所述，目前手机端 h5 我个人还是推荐使用 v 系相关的框架（指 vue 或各种类似、基于 vue 做的小程序框架、跨端框架等）或者 nextjs 。
