### ISSUE TITLE
多个子应用菜单切换时白屏

### ISSUE THREAD

**Issue by shijunfeng** [umijs/umi#12277]
示例代码中home和home1为同一个子应用，home2为另外一个子应用 ，先加载那个子应用另外一个子应用菜单就是白屏，控制台输出找不到路由
![image](https://github.com/umijs/umi/assets/17823594/aaa2f38d-24b6-4991-b9bb-67a361cf7b7e)

示例代码地址如下：
https://github.com/shijunfeng/umimax-qiankun

**Comment by fz6m** [comment]
你的示例代码里 master 下面没有源码，是空的。

如果你要用内置的 layout 菜单功能，则这个菜单只能在主应用上使用，子应用不可以使用，因为 layout 这个功能底层使用的是 `ProLayout` ，这个组件的样式不支持在页面上显示多个，预期主应用有路由菜单，而子应用只展示自己的内容，没有菜单；如果你需要主子应用都有菜单，并且在一个页面上嵌套展示，则需要自己实现自己的菜单，可以不用 layout 这个功能，关闭即可 `layout: false` ，路由表信息可以参考 `src/.umi/plugin-layout/*` 下面的方法来获取。

如还有问题，需要给一个可以运行的最小复现。

**Comment by shijunfeng** [comment]
抱歉，我已更新代码，我的需求是主子应用全部使用umimax+antd,主子应用都可以单独打开，子应用的菜单是否显示可以通过主应用传递参数来解决，目前测试代码中我直接关闭了子应用的菜单，现在的问题是主应用挂载两个子应用后先点击哪个子应用菜单再点击另外一个子应用的菜单就白屏，从控制台输出看，切换菜单时没有走子应用的mount事件只是把上一个子应用umount掉了。

**Comment by shijunfeng** [comment]
> 你的示例代码里 master 下面没有源码，是空的。
> 
> 如果你要用内置的 layout 菜单功能，则这个菜单只能在主应用上使用，子应用不可以使用，因为 layout 这个功能底层使用的是 `ProLayout` ，这个组件的样式不支持在页面上显示多个，预期主应用有路由菜单，而子应用只展示自己的内容，没有菜单；如果你需要主子应用都有菜单，并且在一个页面上嵌套展示，则需要自己实现自己的菜单，可以不用 layout 这个功能，关闭即可 `layout: false` ，路由表信息可以参考 `src/.umi/plugin-layout/*` 下面的方法来获取。
> 
> 如还有问题，需要给一个可以运行的最小复现。

抱歉，我已更新代码，我的需求是主子应用全部使用umimax+antd,主子应用都可以单独打开，子应用的菜单是否显示可以通过主应用传递参数来解决，目前测试代码中我直接关闭了子应用的菜单，现在的问题是主应用挂载两个子应用后先点击哪个子应用菜单再点击另外一个子应用的菜单就白屏，从控制台输出看，切换菜单时没有走子应用的mount事件只是把上一个子应用umount掉了。能帮忙给看一下吗？

**Comment by fz6m** [comment]
看了下，两个地方需要调整。

1. 路由表是精确匹配的，用微前端的那个配置得是通配才行，不然就匹配不上路由了：

    ```ts
        {
          name: '子应用home2',
          path: '/home1/*',
          microApp: 'myslave2',
        }
    ```

2. 没必要自己在运行时 patchClientRoutes 去改微前端路由的节点内容，因为路由表里 `microApp` 这个选项就已经是默认的约定了，如果你配了这个选项，就会自动以你这个路径作为 base ，之后附带上子应用的路由，比如 `/home1/*` 的时候，`/home1/some-route` 就是匹配的子应用 `/some-route` 这个路由，不要自己去干预它的内容；

    如果你要用 `<MicroApp />` 这种自己渲染子应用的方式，就不要用 `microApp` 这个内置约定，换一个其他的名字，然后你再 patch 了自己改自己要的，或者你配一个组件，在这个组件里用 `<MicroApp />` 渲染也是可以的，通过 [`useRouteProps`](https://umijs.org/docs/api/api#userouteprops) 、[`useSelectedRoutes`](https://umijs.org/docs/api/api#useselectedroutes) 等 api 可以拿到路由表里的信息（自己渲染的时候如果不达预期，就自己多调试下 props ）。

上面说的这些其实 [文档](https://umijs.org/docs/max/micro-frontend) 里都有，如果想更自由的使用 umi 微前端这个功能，建议完整阅读一次。

**Comment by shijunfeng** [comment]
> 看了下，两个地方需要调整。
> 
> 1. 路由表是精确匹配的，用微前端的那个配置得是通配才行，不然就匹配不上路由了：
>    ```ts
>        {
>          name: '子应用home2',
>          path: '/home1/*',
>          microApp: 'myslave2',
>        }
>    ```
> 2. 没必要自己在运行时 patchClientRoutes 去改微前端路由的节点内容，因为路由表里 `microApp` 这个选项就已经是默认的约定了，如果你配了这个选项，就会自动以你这个路径作为 base ，之后附带上子应用的路由，比如 `/home1/*` 的时候，`/home1/some-route` 就是匹配的子应用 `/some-route` 这个路由，不要自己去干预它的内容；
>    如果你要用 `<MicroApp />` 这种自己渲染子应用的方式，就不要用 `microApp` 这个内置约定，换一个其他的名字，然后你再 patch 了自己改自己要的，或者你配一个组件，在这个组件里用 `<MicroApp />` 渲染也是可以的，通过 [`useRouteProps`](https://umijs.org/docs/api/api#userouteprops) 、[`useSelectedRoutes`](https://umijs.org/docs/api/api#useselectedroutes) 等 api 可以拿到路由表里的信息（自己渲染的时候如果不达预期，就自己多调试下 props ）。
> 
> 上面说的这些其实 [文档](https://umijs.org/docs/max/micro-frontend) 里都有，如果想更自由的使用 umi 微前端这个功能，建议完整阅读一次。

我明白你的意思，我之所以要精准匹配是因为需要严格控制路由权限，没法使用通配符。然后我加前缀是为了避免多个子应用路由重复的问题，例如两个子应用都有home路由，其实官网的示例中的那种形式我个人认为对于一个管理系统是没有太大意义的，管理系统都需要严格控制路由及菜单的权限，另外会将多个子应用的路由进行重组到不同的父级菜单下或嵌套，简单的管理系统上升不到微前端，但凡拆应用搞微前端的业务功能都需要精准的权限控制和路由重组统一再主应用进行控制。而不是官网的那种样子每个点开都有自己的菜单。

**Comment by shijunfeng** [comment]
> 我明白你的意思，我之所以要精准匹配是因为需要严格控制路由权限，没法使用通配符。然后我加前缀是为了避免多个子应用路由重复的问题，例如两个子应用都有home路由，其实官网的示例中的那种形式我个人认为对于一个管理系统是没有太大意义的，管理系统都需要严格控制路由及菜单的权限，另外会将多个子应用的路由进行重组到不同的父级菜单下或嵌套，简单的管理系统上升不到微前端，但凡拆应用搞微前端的业务功能都需要精准的权限控制和路由重组统一再主应用进行控制。而不是官网的那种样子每个点开都有自己的菜单。

我的菜单和路由都是需要动态加载的，目前都在数据库中，也就是说需要根据主应用匹配的权限决定加载哪些子应用、菜单和路由，我的目标是1：精准控制主应用根据权限加载哪些路由，2：精准控制主应用根据权限加载哪些菜单我如果要实现我想要的结果，是不是要弃用prolayout自己写一个layout，重写一下菜单和跳转，这样的话能解决问题么？或我怎么才能达到我想要的结果呢？

**Comment by fz6m** [comment]
目前最常见的动态路由的做法是在渲染应用前先请求 api 获取到此用户拥有的路由表，然后在 [`patchClientRoutes`](https://umijs.org/docs/api/runtime-config#patchclientroutes) 内更改此用户的路由表，最终体现到到菜单上就是此用户只看到拥有权限的菜单（例子可以在 `patchClientRoutes` 的说明文档处找到，或参考 https://github.com/umijs/umi/discussions/9717#discussioncomment-4078053 ）。

如果你希望有一个细致的、根据权限来的路由表，则不应该使用静态配置路由到配置文件（ `.umirc.ts` / `config/config.ts` ）的方式，而是按如上所述请求获取后来动态修改路由表，如果要渲染子应用，在对应组件内展示 qiankun 的 `<MicroApp />` 即可。

你提到的这种场景：

> 没法使用通配符 / 根据主应用匹配的权限决定加载哪些子应用

都可以在应用运行时修改路由表实现。

**Comment by shijunfeng** [comment]
> 目前最常见的动态路由的做法是在渲染应用前先请求 api 获取到此用户拥有的路由表，然后在 [`patchClientRoutes`](https://umijs.org/docs/api/runtime-config#patchclientroutes) 内更改此用户的路由表，最终体现到到菜单上就是此用户只看到拥有权限的菜单（例子可以在 `patchClientRoutes` 的说明文档处找到，或参考 [#9717 (comment)](https://github.com/umijs/umi/discussions/9717#discussioncomment-4078053) ）。
> 
> 如果你希望有一个细致的、根据权限来的路由表，则不应该使用静态配置路由到配置文件（ `.umirc.ts` / `config/config.ts` ）的方式，而是按如上所述请求获取后来动态修改路由表，如果要渲染子应用，在对应组件内展示 qiankun 的 `<MicroApp />` 即可。
> 
> 你提到的这种场景：
> 
> > 没法使用通配符 / 根据主应用匹配的权限决定加载哪些子应用
> 
> 都可以在应用运行时修改路由表实现。

是的，正式的项目肯定是要通过api获取的，你看到的代码是个示例，没必要mock一个，所以在.umirc.ts静态配置，仅体现了现在的问题，我想表达的是子应用的路由我不能使用通配符，因为问我要精准的权限控制，需要加载哪些路由是需要从api获取的。现在的问题多个子应用，先点击哪个子应用的菜单，另外一个就是白屏的问题，应该怎么解决？

**Comment by shijunfeng** [comment]
感觉没讨论到点上，能留个联系方式么？

**Comment by fz6m** [comment]
如果不使用通配符，将无法匹配到子应用的路由造成白屏，如果你不想使用通配符，使用上文提到的 patchClientRoutes 自行添加该用户拥有的所有具体路径的路由即可；如果要控制菜单展示，配置 layout 的 [request](https://procomponents.ant.design/components/layout#menu) 选项即可 ：

```ts
// src/app.tsx

export const layout: RunTimeLayoutConfig = () => {

  return {

    menu: {
      request: async (params, defaultMenuDat) => {
        const menuExcludeDynamicRoutes = defaultMenuDat.filter(i => !i.path?.startsWith('/test'))

        // ↓ 这里手动构造出来你想要最终展示的菜单样子
        const firstDynamicMenu = defaultMenuDat.find(i => i.path === '/test')
        menuExcludeDynamicRoutes.push({
          ...firstDynamicMenu,
          path: '/test',
          name: '...',
        })

        return menuExcludeDynamicRoutes;
      },
    },
  };
};

export const patchClientRoutes = ({ routes }: any) => {
  const layoutRoute = routes.find((i: any) => i.id === 'ant-design-pro-layout')

  pathList.map((path) => {
    layoutRoute.routes.push({
      name: '...',
      path,
      id: path,
      element: <div>{path}</div>,
    })
  })
  return routes;
}

const sleep = (time: number) => new Promise((resolve) => setTimeout(resolve, time));

export const render = async (originRender: any) => {
  await sleep(1000);
  pathList = ['/test1', '/test2', '/test3']

  originRender();
}
```

如还有问题，自己想办法调试下吧。
