### ISSUE TITLE
从1.1.1升级到2.1.1后按需编译文件变大，编译代码相同

### ISSUE THREAD

**Issue by kingyu** [umijs/umi#1229]
升级到umi@2.1.1后，使用umi build 编译后（都配置了dynamicImport），编译文件大小如图所示
![image](https://user-images.githubusercontent.com/5800811/46853130-d65cf080-ce2f-11e8-8ef7-96b3bd7a4f9c.png)

这个vendors.async.js到底是编译了什么进去了

umi@2.1.1的umiirc.js 配置

`const path = require("path");`
`export default {`
  `plugins: [`
      ` [`
      `"umi-plugin-react",`
      `{`
        `dva: true,`
        `antd: true,`
        `hd: true,`
        `dynamicImport: {`
          `webpackChunkName: true,`
        `},`
        `routes: {`
          `exclude: [`
            `/model\.(j|t)sx?$/,`
            `/service\.(j|t)sx?$/,`
            `/models\//,`
            `/components\//,`
            `/services\//`
          `]`
        `}`
      `}`
    `]`
 ` ],`
  `targets: {`
    `ie: 11,`
 ` },`
  `alias: {`
    `components: path.resolve(__dirname, "src/components"),`
    `utils: path.resolve(__dirname, "src/utils"),`
    `services: path.resolve(__dirname, "src/services"),`
    `models: path.resolve(__dirname, "src/models"),`
    `themes: path.resolve(__dirname, "src/themes"),`
    `images: path.resolve(__dirname, "src/assets")`
  `},`
  `copy: [`
    `{`
      `from: "src/assets/vconsole.min.js",`
      `to: "js/vconsole.min.js"`
    `}`
  `],`
  `}`
`};`

**Comment by sorrycc** [comment]
用 `ANALYZE=1 umi build` 分析下看多在哪里。

**Comment by kingyu** [comment]
哈哈 自己傻了  import { Button,Icon } from 'antd-mobile';  写成 import { Button,Icon } from 'antd';

去除后减少了500多KB，还是没gzip的
