### ISSUE TITLE
退出登录后，重新进入某个页面，页面报错

### ISSUE THREAD

**Issue by zhaoyanga** [umijs/umi#12298]
![1713346817131](https://github.com/umijs/umi/assets/71998720/eec5d3aa-cf85-447e-93e9-71a15a848777)
刷新后重新进入就是正常

**Comment by zhaoyanga** [comment]
部分页面会这样，出错误的页面放个ProTable都会这样

**Comment by zhaoyanga** [comment]
找了下问题，部分页面使用antd-Pro的组件就会出现这个问题

**Comment by zhaoyanga** [comment]
不用keep-alive包就没事

**Comment by fz6m** [comment]
react 里面现在没有真正意义上的 keep alive ，目前的各种 keep alive 都是想方设法的做一些 hack 设计，所以自然会在某些场景下出现问题。

比如你这里退出登陆后应该直接跳到登录页，而不是还回到系统，如果继续回到系统，之前 keep alive 的组件还是以前的状态和现在不匹配，就可能发生问题，要解决这个问题，得理解你用的 keep alive 原理是哪一种 hack 模式，之后根据这种 hack 模式去调整代码，或者放弃 keep alive ，或者退出登录后就不要返回系统，或者再想一些其他的方法，比如退出登录后不要 keep alive 、或者重置组件 key 重新渲染、或者把 keep alive 缓存清理了等。
