### ISSUE TITLE
[Bug] 父子通信，子应用 通过useModel('@@qiankunStateFromMaster') 获取到的参数是 undefined

### ISSUE THREAD

**Issue by pengyandong** [umijs/umi#12294]
## What happens?
父子通信，子应用拿不到参数

父应用传递参数 type  

import React from 'react'
import { MicroAppWithMemoHistory  } from 'umi';

const Demo: React.FC = () => {
  const [type, setType] = React.useState<any>('Hello MicroFrontend');

  React.useEffect(() => {
    console.log('type=>>>>>', type)
  }, [type])

  return (
    <>
      <MicroAppWithMemoHistory
        name="myapp"
        url="/myapp/access"
        type={type}
        setType={setType}
      />

      <MicroAppWithMemoHistory
        name="yumc-ec-version"
        url="/configManage/systemManage"
        type={type}
        setType={setType}
      />
    </>
  );
};

export default Demo;

子应用接收参数 控制台打印 undefined
import { PageContainer } from '@ant-design/pro-components';
import React from 'react'
import { Access, useAccess } from '@umijs/max';
import { useModel } from 'umi';
import { Button } from 'antd';

const AccessPage: React.FC = (props) => {
  const access = useAccess();
  const masterProps = useModel('@@qiankunStateFromMaster');
  console.log('masterProps=>>>子应用', masterProps)
  const handleClick = () => {
    masterProps?.setType && masterProps.setType({
      time: new Date()
    })
    console.log(111111)
  }

  return (
    <PageContainer
      ghost
      header={{
        title: '权限示例',
      }}
    >
      <Access accessible={access.canSeeAdmin}>
        <Button onClick={handleClick}>只有 Admin 可以看到这个按钮</Button>
      </Access>
    </PageContainer>
  );
};

export default AccessPage;

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi 3.5.0**:
- **Node 16.18.0**:
- **Platform**:

**Comment by pengyandong** [comment]
图片上传不上去，控制台打印是undefiend

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4 。
