### ISSUE TITLE
项目语法错误，项目就停了，不能自动重新启动

### ISSUE THREAD

**Issue by woaiyhl** [umijs/umi#12302]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
目前语法错了就中断项目运行这种问题，只会发生在 `src/app.ts` 和 umi 配置文件吧，这两个也不经常改，改好再重新启动吧。

如还有问题，需要给一个最小复现。
