### ISSUE TITLE
[Bug] umirc title 国际化不生效

### ISSUE THREAD

**Issue by red-chen** [umijs/umi#12308]
## What happens?

国际化标题不生效

## Mini Showcase Repository(REQUIRED)

1. 参考官方文档，设置标题国际化：https://umijs.org/docs/max/i18n#%E6%A0%87%E9%A2%98%E5%9B%BD%E9%99%85%E5%8C%96

2. 设置
```
// src/locales/zh-CN.ts
export default {
    'site.title': 'Geo - 控制台',
    'menu.security.title': "安全中心",
};
```

```
// .umirc.ts
export default defineConfig({
  locale: {
    antd: true,
    // 默认使用 src/locales/zh-CN.ts 作为多语言文件
    default: 'zh-CN',
    baseSeparator: '-',
    baseNavigator: true,
    title: true
  },
  layout: {
    title: 'site.title',
  },
  title: 'site.title',
  routes: [
    {
      path: '/',
      redirect: '/home',
    },
    {
      name: '首页',
      path: '/home',
      component: './Home',
    },
    {
      name: '权限演示',
      path: '/access',
      component: './Access',
    },
    {
      name: '安全中心',
      path: '/table',
      component: './Table',
      title: 'menu.security.title'
    },
  ],
}
``` 

效果
![image](https://github.com/umijs/umi/assets/4748095/0a1426e2-3dbb-4b16-8ee4-a1edc3016657)

## Context

- **Umi Version**: 4.1.9
- **Node Version**: v20.12.1
- **Platform**:macOS 版本14.2.1

**Comment by fz6m** [comment]
这个文档指的标题是当前网页的标题，不是 layout 左上角那个标题，左上角这个你在运行时 layout 配置里增加 `title` 然后用 `FormattedMessage` 取一下就行，没必要配静态 `layout.title` 了。
