### ISSUE TITLE
[Feature Request] umi4支持{htmlSuffix:true} 输出xxx.html的文件

### ISSUE THREAD

**Issue by flgame** [umijs/umi#12301]
## Background
之前有很多项目使用umi3.x，并使用`exportStatic: { htmlSuffix: true }`输出xxx.html静态文件，现在很多地方配置的url都是`http://a.b/xxx/xxx.html`。
现在想升级到4.x，但是不支持输出xxx.html静态文件，如果路由变化很多地方需要修改，希望能支持生成之前的路由格式。

## Proposal
目前有个解决方案是在nginx层做路由转换，但还是希望umi4.x能够支持`exportStatic: { htmlSuffix: true }`，输出和umi3.x一致的静态文件。

或者各位大神有其它的建议么？

**Comment by fz6m** [comment]
在 umi 4 的项目里添加 `exportStatic: {}` 配置即可为每个路由生成一个 html ，注意这种情况对路由写法有一定限制。

**Comment by fz6m** [comment]
目前 umi 4 不支持自定义成 `xxx.html` 的。

如果对 html 产物有特别偏好，应该是更偏好变成一个文档站，应该选择一款 ssg 的文档站方案，比如 vitepress 、rspress 、docusaurus 、nextra 等。

如果对 seo 有特别偏好，由于 umi 是一个 react 的以企业中后台 pc 端开发为主的 SPA 框架，这种情况使用 nextjs 更好。

**Comment by flgame** [comment]
@fz6m 没什么偏好，只是3.0是这样配置的，url已经分发到各系统了。 还有现在这种spa的路由模式需要后台配置支持，无法在不配置try_files的情况下直接直接通过web服务器访问，这是不合理的

**Comment by fz6m** [comment]
如有特殊需求，欢迎 PR 新增此功能。

**Comment by flgame** [comment]
@fz6m 已提PR
