### ISSUE TITLE
[Bug] umi4添加qiankun.slave后，资源访问404

### ISSUE THREAD

**Issue by 1620165757** [umijs/umi#12311]
## What happens?
前提：子应用单独访问，没有主应用，项目名：demo
子应用添加qiankun.slave = {}后，本地环境无异常，但是通过max build、max preview访问会提示umi.js 404
http://localhost:4172/umi.js访问该文件404，如果改为http://localhost:4172/demo/umi.js能正常访问

<img width="985" alt="image" src="https://github.com/umijs/umi/assets/22805742/c12f2b1e-ce3f-4cac-8cc1-d5397bccebb6">
<img width="620" alt="image" src="https://github.com/umijs/umi/assets/22805742/faa255f2-9c0d-451c-9a4e-ce581fd3a5cd">

## Context

- **@umi-max Version**: 4.1.2
- **Node Version**: 6.16.0
- **Platform**: macOS Ventura 13.2.1

**Comment by fz6m** [comment]
这个问题，是因为 preview 这个命令，只是为了在本地临时验证用的，而且绝大多数情况应用涉及到 鉴权、域名 等情况，本地是验证不了的，所以用的人也非常少，现在比较简陋。

目前 preview 的时候，资源都是在 `base` 上提供的，因为 qiankun slave 默认会把 base 改为当前的 `package.json#name` ，所以资源就在 `/${package.json#name}/umi.js` 上提供了，在这个场景这是不对的（但绝大多数情况，一个应用部署在域名子路径下，多数情况下子路径 `base` 都和资源提供路径 `publicPath` 配成一样的了）。

如有兴趣，欢迎 PR 修订此问题，源码在 `packages/preset-umi/src/commands/preview.ts` 。

**Comment by 1620165757** [comment]
> 这个问题，是因为 preview 这个命令，只是为了在本地临时验证用的，而且绝大多数情况应用涉及到 鉴权、域名 等情况，本地是验证不了的，所以用的人也非常少，现在比较简陋。
> 
> 目前 preview 的时候，资源都是在 `base` 上提供的，因为 qiankun slave 默认会把 base 改为当前的 `package.json#name` ，所以资源就在 `/${package.json#name}/umi.js` 上提供了，在这个场景这是不对的（但绝大多数情况，一个应用部署在域名子路径下，多数情况下子路径 `base` 都和资源提供路径 `publicPath` 配成一样的了）。
> 
> 如有兴趣，欢迎 PR 修订此问题，源码在 `packages/preset-umi/src/commands/preview.ts` 。

谢谢答复，我现在遇到的问题是，我把umi3项目升级到umi4，配置了qiankun.slave = {}，本地访问的时候会自动在域名后面加上package.json#name。但是我部署到nginx测试环境的时候，域名后面没用package.json#name，需要手动加上才能访问，请问这个需要怎么解决？

**Comment by fz6m** [comment]
现在的默认设定就是当你开启了 `qiankun.slave` 的时候，这个应用套在主应用里，没有额外的 base ，而独立访问是会多额外的 base 的，这是方便了区分子应用、并可以独立访问子应用，如果不需要这个行为，可能你并不需要 `qiankun.slave` 这个选项，没必要让他作为子应用。

配置项是有的，可通过 `qiankun.slave.shouldNotModifyDefaultBase: true` 控制 `base` ，通过 `qiankun.slave.shouldNotModifyRuntimePublicPath` 控制 `window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__` 。

**Comment by 1620165757** [comment]
> 现在的默认设定就是当你开启了 `qiankun.slave` 的时候，这个应用套在主应用里，没有额外的 base ，而独立访问是会多额外的 base 的，这是方便了区分子应用、并可以独立访问子应用，如果不需要这个行为，可能你并不需要 `qiankun.slave` 这个选项，没必要让他作为子应用。
> 
> 配置项是有的，可通过 `qiankun.slave.shouldNotModifyDefaultBase: true` 控制 `base` ，通过 `qiankun.slave.shouldNotModifyRuntimePublicPath` 控制 `window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__` 。

好的，感谢
