### ISSUE TITLE
[Bug] umi4 取消了 document.ejs 模板，原来使用 <%= publicPath %> 设置的静态资源路径，在 headScript 中使用什么方式设置

### ISSUE THREAD

**Issue by Yang-yibu** [umijs/umi#12318]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by vkboo** [comment]
> `publicPath` 可以直接配置，如果是动态的，可以插入一个修改 `window.publicPath` 的 [headScripts](https://umijs.org/docs/api/config#headscripts) ，并打开 [`runtimePublicPath`](https://umijs.org/docs/api/config#runtimepublicpath) ，之后你可以构建观察产物 html 。

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/79ebdfc6-79ab-4827-8482-92104c943e38">

(问题就是如图的注释中，原始代码库如附件，谢谢解答
[qiankun-slave-app2.zip](https://github.com/user-attachments/files/17041395/qiankun-slave-app2.zip)
)
