### ISSUE TITLE
[Bug] UMI4  MPA开启报错 Can't resolve './src' in 'D:\workspace\extensions'

### ISSUE THREAD

**Issue by snailsdream** [umijs/umi#12314]
## 目录

> 最小重现
GitHub [最小重现](https://github.com/snailsdream/chrome-extensions)，

## How To Reproduce

** 运行npm run build

** 提示如下内容
![image](https://github.com/umijs/umi/assets/19227029/d84f544e-22ca-4297-a0f2-99f26f252f44)

** 配置文件如下

```js
import { defineConfig } from "umi";

export default defineConfig({
  routes: [
    { path: "/", component: "index" },
    { path: "/docs", component: "docs" },
  ],
  mpa: {
    entry: {
      docs: 'src/pages/docs.tsx',
      index: 'src/pages/index.tsx'
    },
  },
  npmClient: 'npm',
});

```

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by snailsdream** [comment]
Umi Version: 4.1.10
Node Version: 20.12.2
Platform: windows

**Comment by fz6m** [comment]
看看是不是 entry 下面的路径要去掉 `src` 的前缀。

如还有问题，需要给一个最小复现。

**Comment by snailsdream** [comment]
最小重现就是上面那个哈，https://github.com/snailsdream/chrome-extensions
不过问题解决了。使用simple版本的umi会报错，我切换到了max版本就正常了

**Comment by fz6m** [comment]
mpa 是个没什么人用的功能，主要用于一些很特殊的 h5 页面，我都忘记怎么使用了 - -

 mpa 只是一个小功能，现在并不支持配置路由文件在哪，强约定所有的路由必须形成一个 `src/pages/${path}/index.tsx` 的结构，比如 `/docs.html` 就需要在 `src/pages/docs/index.tsx` ，其他的同理。

你这里配置的：

```ts
  mpa: {
    entry: {
      docs: { 
         // 这里是给这个页面特殊配置使用的，不能配成字符串
      }
    },
  },
```

关于可用的特殊配置，可以参考文档：[MPA 模式](https://umijs.org/docs/guides/mpa) ，还有 mpa 的 [example](https://github.com/umijs/umi/tree/master/examples/mpa) 。
