### ISSUE TITLE
[Bug] umi4配置cssLoader报错

### ISSUE THREAD

**Issue by chanceyliu** [umijs/umi#12313]
项目需要样式使用小驼峰的形式定义，像官方案例那样：
`import React from 'react';

import styles from './index.less'; // .bar-foo { font-size: 16px; }

export default () => <div className={styles.barFoo}>Hello</div>;
// => <div class="bar-foo___{hash}">Hello</div>`

参照配置如下：
<img width="418" alt="image" src="https://github.com/umijs/umi/assets/50861437/3b25385b-7a7c-49d4-b891-0ccdf85f98ec">
报错如下：
<img width="1312" alt="image" src="https://github.com/umijs/umi/assets/50861437/80eddc82-76ea-472e-8e6c-49dab255c420">

**Comment by fz6m** [comment]
你指的是 `modules.exportLocalsConvention` 这个选项吗，能配置的选项要参考 css-loader 的 [readme](https://github.com/webpack-contrib/css-loader)  。
