### ISSUE TITLE
[Bug] umi4 local svg cannot be loaded.

### ISSUE THREAD

**Issue by chj-damon** [umijs/umi#12322]
## What happens?

我在umi4环境下加载一个本地的地图svg数据，作为echarts地图的底图使用，但是看效果没有加载成功。同样的加载方式，用umi3没有这个问题。

加载方式是：
```js
import chinaSvg from './map/china.svg';
```

使用方式：
```js
useEffect(() => {
    window
      .fetch(chinaSvg)
      .then(res => {
        return res.text();
      })
      .then(e => {
        echarts.registerMap('chinaSvg', { svg: e });
        if (!echartsRef.current) {
          const echartsDom = document.getElementById('echartsMap')!;
          echartsRef.current = echarts.init(echartsDom);
        }
      });
  }, []);
```

## Mini Showcase Repository(REQUIRED)

umi4下的效果是这样：
![image](https://github.com/umijs/umi/assets/4902684/5af5551b-2cc2-4f27-846d-678803595748)

umi3下的效果是这样：
![image](https://github.com/umijs/umi/assets/4902684/65ed2bad-8378-4872-a9e1-d2a40bdbb4b5)

另外就是，如果我把local svg改成一个线上的svg地址，umi3和umi4都能够正常加载。

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

复现地址：
umi4: https://github.com/chj-damon/umi4LocalSvgRepo

umi3: https://github.com/chj-damon/umi3LocalSvgRepo

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

直接clone之后install 并 start就可以看到效果

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
svg 的图会自动过一遍 svgo 默认压缩，svgo 会去掉不需要的属性，绝大时候是没问题的，但你这个场景 echarts 应该是需要这些属性的，可以关掉 `svgr: false` 。

或者细致配置一下 svgr 的优化选项，防止去掉 svg 里面的属性，但你这种场景其实 svg 的静态资源只占一小部分，对 svg 的优化收益不大，可以直接关了 svgr 。

svgo 压缩后会变成什么样，可以参考 [在线 svgo 压缩](https://www.zhangxinxu.com/sp/svgo/) 。

**Comment by chj-damon** [comment]
非常感谢！
