### ISSUE TITLE
[Bug] 子路由上配置的图标，在菜单上显示不出来

### ISSUE THREAD

**Issue by bxter** [umijs/umi#12321]
我用的umi@max的默认生成的工程，在routes上设置图标icon，第一层图标是可以正常显示的，但是第二级的图标不生效

配置和效果如图：
![image](https://github.com/umijs/umi/assets/59326851/7cbaf648-320c-4cdf-9044-d8e061ae6952)
<img width="546" alt="image" src="https://github.com/umijs/umi/assets/59326851/921e05b7-55c0-400d-8bc6-713bf7e982db">

这是不是个bug

**Comment by bxter** [comment]
who can help me? thks

**Comment by Wu-kung** [comment]
> who can help me? thks

并不是个 bug。显示子级菜单icon需要在 `src/app.tsx` 中 `layout` 设置。

可以参考如下代码：

```js
import { RunTimeLayoutConfig } from '@umijs/max';

export const layout: RunTimeLayoutConfig = (initialState) => {
  return {
    menuItemRender: (menuItemProps, defaultDom) => {
      // 支持二级菜单显示icon
      return (
        <Link to={menuItemProps.path}>
          <div style={{ display: 'flex' }}>
            <span style={{ paddingRight: '8px' }}>{menuItemProps.pro_layout_parentKeys
              && menuItemProps.pro_layout_parentKeys.length > 0 &&
              menuItemProps.icon}</span>
            {defaultDom}</div>
        </Link>
      )
    },
  }
};
```

![20240423105454](https://github.com/umijs/umi/assets/22555105/4e2e44fd-f0b3-47b1-8136-9429994d5a2a)

**Comment by bxter** [comment]
感谢！
还有个菜单问题, 我配置了微前端，这个在菜单出不来，但是实际能访问，这又是什么需要自己配置么
![image](https://github.com/umijs/umi/assets/59326851/a752b997-526a-45b5-bf09-ea8fd731731d)
<img width="786" alt="image" src="https://github.com/umijs/umi/assets/59326851/b20b4b6f-3702-45cb-bbee-32a90011bae2">
<img width="782" alt="image" src="https://github.com/umijs/umi/assets/59326851/b4c691f1-b5ea-4ee7-be0f-6a1df24812ef">

**Comment by fz6m** [comment]
如还有问题，需要给一个最小复现。

**Comment by sp4rkw** [comment]
> > who can help me? thks
> 
> 并不是个 bug。显示子级菜单icon需要在 `src/app.tsx` 中 `layout` 设置。
> 
> 可以参考如下代码：
> 
> ```js
> import { RunTimeLayoutConfig } from '@umijs/max';
> 
> export const layout: RunTimeLayoutConfig = (initialState) => {
>   return {
>     menuItemRender: (menuItemProps, defaultDom) => {
>       // 支持二级菜单显示icon
>       return (
>         <Link to={menuItemProps.path}>
>           <div style={{ display: 'flex' }}>
>             <span style={{ paddingRight: '8px' }}>{menuItemProps.pro_layout_parentKeys
>               && menuItemProps.pro_layout_parentKeys.length > 0 &&
>               menuItemProps.icon}</span>
>             {defaultDom}</div>
>         </Link>
>       )
>     },
>   }
> };
> ```
> 
> ![20240423105454](https://private-user-images.githubusercontent.com/22555105/324672697-4e2e44fd-f0b3-47b1-8136-9429994d5a2a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzA4MzMsIm5iZiI6MTcyMTAzMDUzMywicGF0aCI6Ii8yMjU1NTEwNS8zMjQ2NzI2OTctNGUyZTQ0ZmQtZjBiMy00N2IxLTgxMzYtOTQyOTk5NGQ1YTJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA4MDIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYjM2NGIyM2EwZjM1ZGI1NmU0NDRlNGFjZTA4Nzk3YzhmYjliZWY2OGM3ODI1NDIyNTBjM2RjZjNlZDI5MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YJ-bSCEtglqGc6uUqTRE86vhMOreS-ZcaQ1U04PqbOY)

建议代码，可以规避layout: 'mix', 模式下的显示错乱问题
```
menuItemRender: (menuItemProps, defaultDom) => {
      // 支持二级菜单显示icon
      return (
        <Link to={menuItemProps.path}>
          <div style={{ display: 'flex' }}>
            {menuItemProps.pro_layout_parentKeys && menuItemProps.pro_layout_parentKeys.length > 1 && (
              <span style={{ paddingRight: '8px' }}>
                {menuItemProps.icon}
              </span>
            )}{defaultDom}</div>
        </Link>
      );
    },
```

**Comment by en-o** [comment]
我这样设置编译器直接报错
![image](https://github.com/user-attachments/assets/90c921bf-8800-41dc-821a-12e275609c6d)

**Comment by hwqlet** [comment]
> 我这样设置编译器直接报错 ![image](https://private-user-images.githubusercontent.com/45027672/359779290-90c921bf-8800-41dc-821a-12e275609c6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NTExNzIsIm5iZiI6MTczMDk1MDg3MiwicGF0aCI6Ii80NTAyNzY3Mi8zNTk3NzkyOTAtOTBjOTIxYmYtODgwMC00MWRjLTgyMWEtMTJlMjc1NjA5YzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDAzNDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3OWNkZGUyYmNkYzgwODk0ZjFkMDUyZGNhOTViMjMyNWEwZTlhOTBjZWNmMjc1NWZhOGYwNWM4Yjg0NGEwMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Lh56o-6A4-iCyGJxb1KO-ItefIZvZZ6W55s2SQadsmA)

你需要把app.ts重命名为app.tsx

**Comment by Farley-Chen** [comment]
> 如还有问题，需要给一个最小复现。

子路由无法使用icon参数的问题，是否需要在官方文档中进行说明？我感觉可以在文档中提一下
