### ISSUE TITLE
MicroAppLink微前端qiankun框架跳转

### ISSUE THREAD

**Issue by JOKER-GU621** [umijs/umi#12320]
MicroAppLink 跳转到主应用时，Windows系统里运行时，不退出账号静置大概四五个小时后出现跳转失败，并报错，错误如下：
![截图](https://github.com/umijs/umi/assets/54068162/a56f598f-53ab-40ef-a6f7-502b779f72e4) 地址栏会加上子应用的name名并无法跳转

**Comment by JOKER-GU621** [comment]
![image](https://github.com/umijs/umi/assets/54068162/e8187b06-b646-4c16-9b63-48584521df3e)

**Comment by fz6m** [comment]
如果有问题，需要给一个会报错的最小复现。
