### ISSUE TITLE
[Bug] 在umi3中使用antd5.12.4的版本，当使用 watermark 的组件的时候会报错

### ISSUE THREAD

**Issue by fu1996** [umijs/umi#12335]
## What happens?
在umi3中使用antd5.12.4的版本，当使用 watermark 的组件的时候会报错。如下：
![image](https://github.com/umijs/umi/assets/42232973/c1008558-ea3b-4d25-811b-cfc82fcc9943)

在umi3中使用antd5.12.4的版本，当使用 watermark 的组件的时候会报错，但是使用Button 组件，一切正常
## Mini Showcase Repository(REQUIRED)

地址如下：https://github.com/fu1996/umi3-antd5.git

## How To Reproduce

**Steps to reproduce the behavior:**  在node 18版本以上，yarn 安装依赖，然后直接运行npm start 即可

**Expected behavior**  期望Watermark 组件正常显示

## Context

- **Umi Version**: 3.5.41
- **Node Version**:18.18
- **Platform**:mac pro 13 arm64

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4
