### ISSUE TITLE
PWA Manifest

### ISSUE THREAD

**Issue by caoguoli** [umijs/umi#12347]
umi版本 4.1.10 ，如何配置  PWA Manifest 实现便捷应用下载？

**Comment by fz6m** [comment]
如果你需要把应用变成 pwa 的话，和 umi 本身无关，因为 umi 构建用的是 webpack ，所以只需要寻找把 webpack 的项目变为 pwa 的方法即可。

一般情况只需要采用社区已有的一些 pwa 插件，添加到 webpack 里（这在 umi 中通过 [`chainWebpack`](https://umijs.org/docs/api/plugin-api#chainwebpack) 来修改 webpack 配置），然后再添加一些搭配代码，就可以达到预期。

**Comment by caoguoli** [comment]
config.plugin('WebpackPWAManifest')
      .use(require('webpack-pwa-manifest'), [{
        name: '我的PWA应用',
        short_name: 'PWA应用',
        icons: [
          {
            src: require.resolve('./src/favicon.jpg'),
            sizes: [72, 96, 144, 192],
            purpose: 'any maskable'
          }
        ]
      }])
      
      使用配置不生效，大佬们帮忙看看哪里的问题

**Comment by fz6m** [comment]
```ts
// .umirc.ts

import pkg from './package.json'
const pwaInfo = {
  name: 'My Progressive Web App',
  shortName: 'MyPWA',
  description: 'My awesome Progressive Web App!',
  backgroundColor: '#ffffff',
  themeColor: '#ffffff',
  filename: `manifest.${pkg.version}.json`
}

// ...

  links: [
    {
      rel: 'manifest',
      href: `/${pwaInfo.filename}`
    }
  ],
  metas: [
    {
      name: 'apple-mobile-web-app-title',
      content: pwaInfo.name
    },
    {
      name: 'apple-mobile-web-app-capable',
      content: 'yes'
    },
    {
      name: 'apple-mobile-web-app-status-bar-style',
      content: 'default'
    },
    {
      name: 'theme-color',
      content: pwaInfo.themeColor,
    }
  ],
  chainWebpack(config) {
    config.plugin('webpack-pwa-manifest').use(
      WebpackPwaManifest,
      [ 
        {
          filename: pwaInfo.filename,
          name: pwaInfo.name,
          short_name: pwaInfo.shortName,
          description: pwaInfo.description,
          background_color: pwaInfo.backgroundColor,
          theme_color: pwaInfo.themeColor,
          ios: true,
          icons: [
            {
              src: './src/assets/icon.png',
              sizes: [96, 128, 192, 256, 384, 512]
            }
          ]
        }
      ]
    )
  }
```

因为 Umi 没有 html-webpack-plugin ，pwa 这个 webpack 插件只能生成 manifest.json 产物但是没法插入关联的 html 标签，所以里面的标签要用 umi 配置手动加到 html 里。

↑ 这个配置在生产构建时生效即可，自己用 `process.env.NODE_ENV` 条件配置下。
