### ISSUE TITLE
[有些需要跟组件，如何使用] 

### ISSUE THREAD

**Issue by renjiali** [umijs/umi#12341]
import { ParallaxProvider } from 'react-scroll-parallax';
const AppContainer = () => (
  <ParallaxProvider>
    <Router>
      <App />
    </Router>
  </ParallaxProvider>
);
但是umi是不存在的

**Comment by renjiali** [comment]
???

**Comment by fz6m** [comment]
根组件是啥，你创建一个 context 不行吗，给一个最小复现看看吧。
