### ISSUE TITLE
@umi/max 的国际化 配置不生效

### ISSUE THREAD

**Issue by bxter** [umijs/umi#12345]
我按照文档开启了国际化
0、用最新的umijs/max的工程
![image](https://github.com/umijs/umi/assets/59326851/ef5acdd6-d15b-40a9-abc6-ca9c54c161d0)
1、建目录文件
![image](https://github.com/umijs/umi/assets/59326851/3547073c-6a5b-47c5-9cd3-d42d214b8bcc)
2、.umirc.ts 打开配置
![image](https://github.com/umijs/umi/assets/59326851/9a328ff6-7f84-444e-a486-7b9613270e6d)
3、页面文件使用时候，报错
![image](https://github.com/umijs/umi/assets/59326851/39d99023-5868-4b37-8e15-8116b2dcbaf6)
4、报错信息
<img width="833" alt="image" src="https://github.com/umijs/umi/assets/59326851/a60db70c-473c-4304-ad92-ad7ff8640a09">

我重启应用很多次，也是报这个
React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.

我对rootContainer进行了自定义，是不是这个原因呢？
![image](https://github.com/umijs/umi/assets/59326851/8f29ae24-5dda-49be-a922-1487e3313e0a)

弄了好久不知道原因，急切寻求帮助，谢谢，谢谢！！

**Comment by Wu-kung** [comment]
可以改用 `useIntl` 实现国际化，示例：

```tsx
import { Modal, Button } from 'antd';
import { useIntl, FormattedMessage } from '@umijs/max';

const Page = () => {
  const intl = useIntl();
  const content = intl.formatMessage({ id: 'common.ok' });
  const handleClick = () => {
    Modal.confirm({
      title: 'test',
      content,
      onOk: () => {},
    });
  };
  return <Button onClick={handleClick}>test</Button>;
};
```

**Comment by bxter** [comment]
@Wu-kung 
感谢你的讲解，我试验了下，确实如此。

但是，还是有个问题，你的这种方法，用在标准的组件上是正常的，但是如果用在List的组件上，好像就不对了
我的组件写法如下， 用在listItem里面的组件，
![image](https://github.com/umijs/umi/assets/59326851/77ead5bd-05e8-421c-9625-768e14f4b5b5)

十分感谢你的帮助！！

**Comment by Wu-kung** [comment]
> @Wu-kung 感谢你的讲解，我试验了下，确实如此。
> 
> 但是，还是有个问题，你的这种方法，用在标准的组件上是正常的，但是如果用在List的组件上，好像就不对了 我的组件写法如下， 用在listItem里面的组件， ![image](https://private-user-images.githubusercontent.com/59326851/326706256-77ead5bd-05e8-421c-9625-768e14f4b5b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjE3NjYsIm5iZiI6MTcxNDQ2MTQ2NiwicGF0aCI6Ii81OTMyNjg1MS8zMjY3MDYyNTYtNzdlYWQ1YmQtMDVlOC00MjFjLTk2MjUtNzY4ZTE0ZjRiNWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA3MTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZWU1MDg1YTExZTEyZmQwNTUwNTkxNzk5OGYyMGM5YWI3YmEzMmYyNzU2ZGI3ZWQzMDhjMjA3NGYyZDU1YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2mh-5oipsz0VgZ6nZ9QbR4sPX_fLJx2sVeXNcgkroOM)
> 
> 十分感谢你的帮助！！

是因为你未创建一个 `contextHolder` 插入子节点中。仔细观察我给出的示例，详情页可参考 [antd官网](https://ant-design.gitee.io/components/modal-cn#modalusemodal)。

**Comment by bxter** [comment]
看懂了，thks
