### ISSUE TITLE
[Bug] MSFU构建模式在项目 type: "module" 的模式下，commonjs 的构建产物的依赖会出现 default 嵌套问题

### ISSUE THREAD

**Issue by 1ncounter** [umijs/umi#12344]
## What happens?

MSFU构建模式在项目 type: "module" 的模式下，commonjs 的构建产物的依赖会出现 default 嵌套问题
![image](https://github.com/umijs/umi/assets/19562558/3d0b3850-96f8-42bc-9f04-29ecef34f079)

## Mini Showcase Repository(REQUIRED)

https://github.com/1ncounter/bug-reproducible-for-umi

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

1. pnpm i && pnpm start
2. open localhost:8000

## Context

- **Umi Version**: 4.1.10
- **Node Version**: 16.18.1
- **Platform**: macos

**Comment by fz6m** [comment]
不可以指定 esm 的 `"type": "module"` ，因为这个项目不是一个使用 html esm module 来导入依赖的项目（比如 vite 那种才可以）。
