### ISSUE TITLE
[Bug] umi@4.1.10版本使用权限Hook报错

### ISSUE THREAD

**Issue by Liu-code3** [umijs/umi#12356]
## 一、项目背景
- 在umi@4.1.10+ts@5.0.3中

## 二、项目文件中使用
- 在src/wrappers/auth.tsx中使用useAccess报错问题， 报错信息为模块“"umi"”没有导出的成员“useAccess”。ts(2305)
![image](https://github.com/umijs/umi/assets/100696868/d74b29bb-bf9b-4ae8-8dcc-374de584000e)
- 按照 `https://umijs.org/docs/max/access#useaccess`这里的文档配置的
- 以为是vscode栈溢出问题、退出然后打开项目也还是这样

**Comment by xierenyuan** [comment]
https://umijs.org/docs/max/access 有引用权限插件吗

**Comment by Liu-code3** [comment]
## 引用了如下插件
![image](https://github.com/umijs/umi/assets/100696868/ab600e58-5c8b-4d8e-9922-81c32b6ad4f3)

**Comment by xierenyuan** [comment]
> ## 引用了如下插件
> ![image](https://private-user-images.githubusercontent.com/100696868/328147811-ab600e58-5c8b-4d8e-9922-81c32b6ad4f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTEyODUsIm5iZiI6MTcxNDk5MDk4NSwicGF0aCI6Ii8xMDA2OTY4NjgvMzI4MTQ3ODExLWFiNjAwZTU4LTVjOGItNGQ4ZS05OTIyLTgxYzMyYjZhZDRmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxMDIzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTQ0NWUxZjc2ZTJjM2IwYTczZTc2NWIyMzQ3NWM2NjJhZDdlODUyZGZkYTQ2NWIxZDgyZDJiMjJiOTQzNWIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2spd-l2ut0xuvrDD5qyBLhXt4aipjOAwlBbFKIdtjzA)

需要打开一下 配置一下
 access: {},
  model: {},
  initialState: {
  },

**Comment by Liu-code3** [comment]
您好 您的图片我看不见了 能说一下插件名字 谢谢您

**Comment by fz6m** [comment]
```ts
// .umirc.ts

  plugins: [
    '@umijs/plugins/dist/access',
    '@umijs/plugins/dist/initial-state',
    '@umijs/plugins/dist/model',
  ],
  access: {},
  model: {},
  initialState: {},
```

**Comment by Liu-code3** [comment]
问题已经解决了，谢谢您，但是这个配置为什么没在文档中体现出来呢？或者是我读文档的方式错误了吗？还请指正一下

**Comment by fz6m** [comment]
因为通常使用这些 umi 自带的插件功能的用户都会使用 max 这个合集（max 是 umi + 各种 umi 提供的 plugin 的合集，从而无需再自己安装 `@umijs/plugins` 并添加 `plugins` 配置，只需要一键开启即可使用对应的功能），所以如果要用到多个 umi 提供的插件功能的话，建议初始化一个 max 的项目，因为自己配各种 plugin 是比较繁琐的（比如需要注意关联关系，前后顺序等）。
