### ISSUE TITLE
ant-design-pro的样式 全局覆盖不掉

### ISSUE THREAD

**Issue by bxter** [umijs/umi#12353]
我新建的@Max的项目，我需要覆盖掉list.item的默认样式
padding-left:24px, padding-right:24px
<img width="769" alt="image" src="https://github.com/umijs/umi/assets/59326851/415e44b7-7d9d-4d62-88e1-fe753fbd6ff1">
但是我在global.less或者overrides.less 文件中去覆盖这个样式都无法生效
<img width="891" alt="image" src="https://github.com/umijs/umi/assets/59326851/a6d075b5-597a-4609-b890-b252ea564c1b">
我直接内联样式是可以生效的
<img width="1087" alt="image" src="https://github.com/umijs/umi/assets/59326851/9b39cc49-30f6-4253-acad-931e367e5339">

但是我希望全局能覆盖生效，因为类似的配置List我很多页面都有，每个都要去改太麻烦了。

这个问题能怎么解决呢？？ 十分感谢你的帮助，thks

**Comment by fz6m** [comment]
权重应该不够，看下控制台里你添加的这个 css 是不是被删除线划掉了，试着添加选择器的数量（原来它是很长一串，这里面每个类的权重都会累加，最终会比你指定的一个类名的权重高）来提高权重，或者使用 `!important` 。

如还有问题，需要给一个最小复现。
