### ISSUE TITLE
umi/examples/mfsu-independent不能启动

### ISSUE THREAD

**Issue by webLiang** [umijs/umi#12359]
<img width="1245" alt="image" src="https://github.com/umijs/umi/assets/38065991/c160c99f-3388-4cc5-ac28-6e722ff27bc6">

**Comment by stormslowly** [comment]
你马赛克掉的模块找不到，确认下它是否有 package.json文件，且有 main 字段。

如果还有问题 提供最小复现

**Comment by webLiang** [comment]
好的 已经单独copy不用示例包的就可以了
