### ISSUE TITLE
[Bug] 现在已经umi4.1.0版本啦 能同步更新一下umi文档吗

### ISSUE THREAD

**Issue by Liu-code3** [umijs/umi#12352]
## What happens?

请同步更新一下umi文档，交流群二维码也过期了。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
cc @sorrycc 

辛苦更新下 https://fb.umijs.org/ 的信息和二维码吧。
