### ISSUE TITLE
如何配置环境变量

### ISSUE THREAD

**Issue by xjf348060793** [umijs/umi#1235]
想要根据不同的环境使用不同的api前缀 以及一系列不同的变量，看了看文档里面的环境变量的配置好像不是一回事，该如何实现

**Comment by sorrycc** [comment]
你说的是 [define](https://umijs.org/config/#define) 配置?

**Comment by xjf348060793** [comment]
define 昨天试过了  但是 打印process  找不到， define定义的变量是挂载到哪个全局对象上的

**Comment by sorrycc** [comment]
define 里的 key 是什么，代码里就写什么。具体可以查下 webpack 关于 DefinePlugin 的文档。

**Comment by xjf348060793** [comment]
谢谢大佬耐心回复，感激不尽
