### ISSUE TITLE
umi4.x 配置base之后，history.push 跳转相对路径不生效

### ISSUE THREAD

**Issue by amibug** [umijs/umi#12377]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

config.ts 配置
```
export default{
  base: '/xyz/',
  routes: [
      {
        path: '/course/create/1',
        title: '1',
      },
      {
        path: '/course/create/2',
        title: '2',
      },
      {
        path: '/course/create/3',
        title: '3',
      },
      {
        path: '/course/create/4',
        title: '4',
      },
    ],
}
```

如果在localhost:8000/xyz/course/create/1 页面中

1. 使用相对路由的方式跳转 ```history.push('./2')```页面会跳转到 localhost:8000/xyz/.2 ，非 localhost:8000/xyz/course/create/2  

2. 使用```history.push('/course/create/2')``` 可正确跳转到 localhost:8000/xyz/course/create/2

## Context

- **Umi Version**: 4.0.89
- **Node Version**:  18.0.0
- **Platform**: mac ios

**Comment by fz6m** [comment]
我修复了下，但调试发现 history 使用相对路径跳转时，当前路径最后有没有 `/` 是会影响跳转结果的。

比如 url path 是 `/a/b` 时，react router 原生提供的 `useNavigate` 跳转 `navigate('./c')` 得到的是 `/a/b/c` 
当 url path 是 `/a/b/` 时，`navigate('./c')` 得到的也是 `/a/b/c` ，尾 slash 不影响结果。

但，比如 url path 是 `/a/b` 时， `history.push('./c')` 得到的是 `/a/c` 
url path 是 `/a/b/` 时， `history.push('./c')` 得到的是 `/a/b/c` 。

以上这两种表现不一致，在没有设定系统的统一尾 slash 标准化的情况下， 这种不一致的行为是有问题的，使用 history 时，它只是一个比较底层的 web history （对原生 history 封装了一下）而已，不应该使用相对路径跳转，而 react router 是一个高级的路由库，它内部兼容了这些相对路径跳转，所以结果是一致的。

我们没法接受不确定的结果，如果要跳相对路径，就统一用 react router 的 `useNavigate` 方法吧。
