### ISSUE TITLE
从v3升级到v4  No matching export in "src/.umi/exports.ts" for import "useModel"

### ISSUE THREAD

**Issue by qiyaozu** [umijs/umi#12378]
<img width="625" alt="image" src="https://github.com/umijs/umi/assets/23499946/c0a973e9-81bb-4fb4-b847-4e5a730488cf">

**Comment by Wu-kung** [comment]
清空缓存，重装依赖试下呢。
```bash
rm -rf node_modules && rm -rf src/.umi && pnpm install
```

**Comment by qiyaozu** [comment]
其实这个步骤我已经做过了  还是你不行

**Comment by Wu-kung** [comment]
> 其实这个步骤我已经做过了 还是你不行

抱歉，`useModel` `useIntl` 是 `@umi/max` 内置的能力。如果使用了 `@umijs/max` 可以使用 `max` 命令来替换 `umi`。

详细可参考：https://umijs.org/docs/introduce/upgrade-to-umi-4

**Comment by fz6m** [comment]
umi 4 分为 `umi` 和 max (`@umijs/max`) ，前者不内置任何插件，如果需要 model / dva 等功能要自己添加这些插件，后者内置了一堆插件，方便直接开启使用。

普通 umi 项目要使用某个功能，只要安装 `@umijs/plugins` 然后配一下就行了，参考：[使用插件](https://umijs.org/docs/guides/use-plugins#%E4%BD%BF%E7%94%A8%E6%8F%92%E4%BB%B6)

**Comment by zhishuzhiqin** [comment]
defineConfig. 打开设置：
model: {},
