### ISSUE TITLE
1.import { history, request } from 'umi';

### ISSUE THREAD

**Issue by shao-mingxuan** [umijs/umi#12373]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by shao-mingxuan** [comment]
1.import { history, request } from 'umi';
2.import request, { extend, RequestOptionsInit } from 'umi-request';
这两种 umi自带的请求，如果后端默认返回 success =false；前端是拿不到数据吗？
目前做的一些测试，请求后端返回的接口 success=false；这是在同一个接口的情况下，
1.从umi 解构的request 是拿不到数据，直接走的是catch方法，
2.但是从umi-request 解构的request就能拿到 success=false的这种情况，前端then方法能拿到
3.从umi-request 解构的request ，使用extend实例去请求，有的时候也是拿不到 success =false的这种情况
目前就是这三种情况，前提是没有配置错误处理和响应拦截。
 从官方umi框架，约定好的接口返回success=false，是错误处理，但是出现上边的第二个情况，这是什么问题。

**Comment by fz6m** [comment]
这是俩不一样的东西，从 umi 导入的 request 和在 umi 里对 request 进行的配置，是一套的，底层用的 @ahooksjs/use-request 。

umi-request 是另一个东西，这俩完全不一样，所以行为、配置什么的是有差异的。

建议使用内置的这个 umi 导入的 request ，文档在 [这里](https://umijs.org/docs/max/request) 。

这个 request 可能还不能满足现代数据流的需求，因为现代请求都用 react-query 或 swr 了，所以你可以把它套在 RQ / swr 里用，或者自己再配个新的 axios 都行。
