### ISSUE TITLE
[Bug] Linux环境打包后，chunk中出现React，导致报错：ReferenceError: React is not defined

### ISSUE THREAD

**Issue by GhostFJ** [umijs/umi#12372]
## What happens?
Linux环境打包后，chunk中出现React，导致报错：ReferenceError: React is not defined

1. 环境：
本地：
- mbp m1 v13.2.1 (22D68)
- node ：v16.17.1

线上：
- Linux Qoffline101005 5.4.119-19-0009.1 #1 SMP Sun Jan 23 23:20:30 CST 2022 x86_64 x86_64 x86_64 GNU/Linux
- node：v16.20.2

项目：umi4 + antd pro
代码相同（直接git clone），配置、nginx配置相同，dist产物不同

结果：
线上直接打包 npm run build后访问，报错：
![image](https://github.com/umijs/umi/assets/35386856/307090c5-b2f2-4ebb-958e-7067ef3c1120)

![image](https://github.com/umijs/umi/assets/35386856/af80fe24-8c6f-4c55-8860-1207b08ed95d)

直接使用mac本地打包后的dist，正常访问
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: umijs/max 4
- **Node Version**: v16.20.2
- **Platform**: Linux Qoffline101005 5.4.119-19-0009.1 #1 SMP Sun Jan 23 23:20:30 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by flycj** [comment]
我也是使用 umijs/max 4，新建的项目，本地运行后，出现这个错误了，主要是 and-design/pro-layout报的错，请问您是如何解决的呢？

**Comment by GhostFJ** [comment]
> 我也是使用 umijs/max 4，新建的项目，本地运行后，出现这个错误了，主要是 and-design/pro-layout报的错，请问您是如何解决的呢？

降级pro-components到2.6.48

**Comment by fz6m** [comment]
pro component 出了啥问题，我初始化一个新的 umi 项目后安装最新版本 pro component ，使用后打包构建预览没问题的
