### ISSUE TITLE
PUBLIC_PATH is not defined

### ISSUE THREAD

**Issue by tolerance-go** [umijs/umi#1238]
umi@2.2.0-beta.2

```bash
ReferenceError: ejs:9
    7|     <meta http-equiv="X-UA-Compatible" content="ie=edge">
    8|     <title>Document</title>
 >> 9|     <link rel="stylesheet/less" type="text/css" href="<%= PUBLIC_PATH %>hotTheme/index.less" />
    10|     <script>
    11|         window.less = {
    12|             async: false,

PUBLIC_PATH is not defined
```

这个版本不是已经支持了 <%= PUBLIC_PATH %>

config 如下，我定义 define 还是不行
```js
export default {
  plugins: [
    [
      "umi-plugin-react",
      {
        antd: false,
        dva: {
          hmr: true,
          immer: true
        }
      }
    ]
  ],
  base: "antd-themes-editor/",
  publicPath: "antd-themes-editor/",
  outputPath: "docs",
  exportStatic: true,
  disableCSSModules: true,
  cssModulesWithAffix: true,
  define: {
    "process.env.PUBLIC_PATH": "antd-themes-editor/"
  }
};
```

**Comment by xiaohuoni** [comment]
https://webpack.js.org/plugins/define-plugin/
https://umijs.org/zh/config/#define

**Comment by tolerance-go** [comment]
@xiaohuoni https://github.com/umijs/umi/pull/1183

最新版下，如果要在 `document.ejs` 中注入变量的推荐方式是什么呢？

**Comment by tolerance-go** [comment]
目前有效的方式只有使用命令行参数

```bash
 "build": "PUBLIC_PATH=/antd-themes-editor/ umi dev",
```
document.ejs 中使用 `process.env.PUBLIC_PATH`

**Comment by xiaohuoni** [comment]
推荐方式要@sorrycc

**Comment by sorrycc** [comment]
`<%= context.publicPath %>` 可以直接用的，参考 https://umijs.org/guide/html-template.html#configure-the-template

**Comment by tolerance-go** [comment]
@sorrycc 
![image](https://user-images.githubusercontent.com/37258382/46912236-763a8b80-cfa2-11e8-84d5-6e2775e9f9ad.png)

测试发现配置中的 publicPath 在 context.config 中，context.publicPath 不知道是什么含义

**Comment by sorrycc** [comment]
以 context.publicPath 为准，dev 模式下 publicPath 是写死 `/` 的，不可修改。
