### ISSUE TITLE
[Bug] openapi生成的services中的数据类型

### ISSUE THREAD

**Issue by amone-bit** [umijs/umi#12381]
## What happens?

我的后端是fastapi，代码如下图
![image](https://github.com/umijs/umi/assets/62925104/11baa369-4309-4366-98ee-6501ba0df495)
我还尝试过`str | None`的写法，也是同样的效果
我用umi的openapi插件生成service，但是它生成的类型是这样的
![image](https://github.com/umijs/umi/assets/62925104/bda40df7-9c2b-4f24-bf06-ebc3e2a2e075)
我期待的是这样的
![image](https://github.com/umijs/umi/assets/62925104/2f100419-5b7a-478b-8c1e-0b27c2f92284)
我不知道是我使用有问题还是umi本身有问题

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
![image](https://github.com/umijs/umi/assets/62925104/1f953ad3-ab18-4f5b-b4d1-5dcceff29915)

- **Node Version**:
- **Platform**: Windows

**Comment by fz6m** [comment]
`@umijs/max-plugin-openapi` 的源码在 [这里](https://github.com/umijs/umi-presets-pro/tree/master/packages/max-plugin-openapi) 。

我没用过这个插件，可以看看他可不可以定制，如果觉得不符合自己的要求，可以 PR 或者 fork 一份发布了自用，因为这个插件作者很忙基本没空更新。
