### ISSUE TITLE
[Bug] useModel 怎么关闭隐式调用

### ISSUE THREAD

**Issue by gebaoyuanandy** [umijs/umi#12390]
我在目录定义一个models，然后里面有一个请求，需要登录以后才能发起请求。可是我发现，在我未调用 useModel的情况下，函数依然被触发了，导致报错，请问有什么方法只有在使用的时候才触发吗？
> 如下函数，登录以后我使用的时候才让其发出请求，可是我发现只要打开页面，我还没有调用  useModel('handlingOptions')的情况下，就已经被执行了。
```
export default function handlingOptions() {
  console.log('被调用:');
  const { data = [] } = useRequest(APIS.chuliyijianzidianbiao.listDictionaryByParamUsingPost);
  return {
    all: data
      .filter((item) => item.sceneType == 'currency')
      .map((item) => {
        return {
          label: item.noteName,
          value: item.noteCode,
        };
      }),
  };
}
```

**Comment by fz6m** [comment]
所有的 model 都是持久化、并且全局的，在整个应用生命周期内都存活，并且在应用启动的时候就会初始化了，它是一个全局的概念，不是局部的 model ，从而这个持久化的 model 可以在任意地方被调用并且分享状态。

如果你需要的局部行为、局部状态，在业务局部用 react context 即可，这样到了这个局部才会调用；或者不要在 model 内使用 useEffect 默认执行的副作用，而是在未来某个时机再去执行对应的初始化操作；或者使用 [hox](https://github.com/umijs/hox) 局部化 model 的库；或者不使用 model 类数据库（因为 model 是上古的数据流方案），现代数据流更推荐使用 [jotai](https://github.com/pmndrs/jotai) / [valtio](https://umijs.org/docs/max/valtio) / [zustand](https://github.com/pmndrs/zustand) 管理全局状态，使用 [react-query](https://umijs.org/docs/max/react-query) / [swr](https://github.com/vercel/swr) 管理请求状态。
