### ISSUE TITLE
[Bug] Proxy can't support WebSocket and make umi crashed

### ISSUE THREAD

**Issue by ZenkieBear** [umijs/umi#12399]
## What happens?

When I configured the proxy with an `ws` option, and send the WebSocket request to devServer, the devServer crashed:
```sh
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Socket instance at:
    at Socket.onerror (internal/streams/readable.js:750:14)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

## Mini Showcase Repository(REQUIRED)
https://github.com/ZenkieBear/umi-proxy-ws-crashing

## How To Reproduce
1. Install the NPM dependencies and start the dev server.
```sh
npm i
npm start
```
2. Make a WebSocket request to dev server.
- You can use a api-tool to send the request, such like Postman. The url should be: `ws://localhost:8000/ws/api/v1/test`
- Or just visit the home page: `http://localhost:8000`, then you will see the crashing information in the terminal.

## Context

- **Umi Version**: 3.5.41
- **Node Version**: 14.21.3
- **Platform**: macOS Sonoma 14.4.1

**Comment by ZenkieBear** [comment]
If you remove the `/ws` proxy, everything works right.

**Comment by fz6m** [comment]
umi 3 不维护了，建议升级到 umi 4 。
