### ISSUE TITLE
[Feature] 优先使用用户安装的 `babel-plugin-react-compiler`

### ISSUE THREAD

**Issue by fz6m** [umijs/umi#12404]
### 说明

新增功能：`forget` 功能在使用 `babel-plugin-react-compiler` 时，优先使用用户安装的 `babel-plugin-react-compiler` ，如果用户没安装，再使用内置的，因为这个包经常发版，内置的版本很容易陈旧。

更多说明见 https://github.com/umijs/umi/pull/12396#discussion_r1605818073

PR Welcome ，认领请先留言避免重复提交。

**Comment by fz6m** [comment]
另可新增 `forget.experiment.enableCompilerWithReact18` 选项，参考此 [文章](https://jherr2020.medium.com/react-compiler-with-react-18-1e39f60ae71a) 与此 [gist](https://gist.github.com/poteto/37c076bf112a07ba39d0e5f0645fec43) 代码片段，新增实验性 react 18 使用 react compiler ，调整如下：

1、在开启此选项时 check react 是否为 v18

2、开启此选项时给出明显警告，因为 react compiler 发言人 [不推荐](https://x.com/potetotes/status/1793248011239170156) 此种行为，只是权宜之计

3、把需要的 runtime 内容，写一个临时文件，然后配制成 `@/.umi/plugin-xxx/reactCompilerRuntime.js` 的方式导入。

**Comment by rjl-cli** [comment]
> ### 说明
> 新增功能：`forget` 功能在使用 `babel-plugin-react-compiler` 时，优先使用用户安装的 `babel-plugin-react-compiler` ，如果用户没安装，再使用内置的，因为这个包经常发版，内置的版本很容易陈旧。
> 
> 更多说明见 [#12396 (comment)](https://github.com/umijs/umi/pull/12396#discussion_r1605818073)
> 
> PR Welcome ，认领请先留言避免重复提交。
wrappers的代码在哪里可以查看？
umi非常好，但是，对于一些特殊的组件库，如react-scroll-parallax
使用是非常不便的。
最好的是，引入umi的wrappers 的逻辑代码。但是我并没有找到，能否告诉我在哪里？

**Comment by zFitness** [comment]
> enableCompilerWithReact18
这个配置项没有生效，react18使用forget模式会报错

**Comment by fz6m** [comment]
因为 `enableCompilerWithReact18` 这个功能没实现呢，这是一个 feature request 提案，还没落地。
