### ISSUE TITLE
设置了 base ，public 资源在本地服务下路径没有相应改变

### ISSUE THREAD

**Issue by tolerance-go** [umijs/umi#1240]
config.js
```js
base: "antd-themes-editor/",
```
![image](https://user-images.githubusercontent.com/37258382/46908480-f1298500-cf55-11e8-8c37-104ebd083a17.png)

![image](https://user-images.githubusercontent.com/37258382/46908491-13230780-cf56-11e8-9ea7-16c74ac95f6e.png)

如果有疑问可以@我继续补充issue内容，不要就close掉 @xiaohuoni

**Comment by xiaohuoni** [comment]
抱歉

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/637
提问的时候，尽量描述清楚，不然还是会被我直接close。
你补充完问题，我会再reopen。不需要再发一个。

**Comment by tolerance-go** [comment]
👌不过 reopen 这个操作是不是有点多余呢，我相信大部分 issue 提问者在问题得到答案之后是会主动 close 掉所提 issue 的，这样是不是也能节省维护者的部分精力；关于提问内容的质量，因为角度局限关系，这是一个沟通的过程，any way 官方 close 蛮伤感情的😫

**Comment by sorrycc** [comment]
你没理解 base 和 publicPath 的区别，

1. base 只和路由有关，publicPath 影响资源文件的访问
2. base 和 publicPath 的配置只在 build 时有效，umi dev 写死为 /，不可配

**Comment by tolerance-go** [comment]
谢谢 @sorrycc  的回答，非常明白，根据建议新建了 `.umirc.build.js` 文件，只在构建阶段修改 `publicPath` 和 `base`，希望这个 issue 可以帮助到其他有相同问题的人，再次感谢 @xiaohuoni

**Comment by xiaohuoni** [comment]
@tolerance-go 太随意的提问我才会关闭。有讨论的都是等到结束的时候关闭。umi暂时没有加入iss管理。你看看antd那些。很随意的问题，都是发出来直接被机器人close掉的

**Comment by tolerance-go** [comment]
@xiaohuoni 互相理解，umi 真的很棒！

**Comment by zhouwenwu30** [comment]
流量

**Comment by youngjuning** [comment]
antd 提个issues 太难了 @xiaohuoni

**Comment by xiaohuoni** [comment]
@youngjuning 趁 umi 还没加机器人，先多提点 issues 吧 ！（憨厚）
