### ISSUE TITLE
[Bug] umi^4.2.5怎么把id="app" 自定义其他名称，比如叫id="app1"

### ISSUE THREAD

**Issue by hejiaqian** [umijs/umi#12403]
## What happens?

umi^4.2.5怎么把id="app" 自定义其他名称，比如叫id="app1",rootElement怎么传入自定义的dom
相关通过npx create-umi@latest 搭建的简单的项目模板

## How To Reproduce

![image](https://github.com/umijs/umi/assets/39544880/8a0f0162-ad45-4cde-a752-e9f413743e9b)

**Comment by Wxh16144** [comment]
https://umijs.org/docs/api/config#mountelementid
<img width="466" alt="image" src="https://github.com/umijs/umi/assets/32004925/bedf279b-4660-4f4d-82ad-0cd991619ce0">

**Comment by hejiaqian** [comment]
> https://umijs.org/docs/api/config#mountelementid <img alt="image" width="466" src="https://private-user-images.githubusercontent.com/32004925/331452425-bedf279b-4660-4f4d-82ad-0cd991619ce0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTc5MTcsIm5iZiI6MTcxNTkxNzYxNywicGF0aCI6Ii8zMjAwNDkyNS8zMzE0NTI0MjUtYmVkZjI3OWItNDY2MC00ZjRkLTgyYWQtMGNkOTkxNjE5Y2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDAzNDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZDdhZGM2ZTBmNjNmZDRkYTAyNzgzN2UwNTJjZmIxN2E2YWE1ZTVmNTQzYWUzMDJmNzBhNGJjZjcyMzJjZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-d8CB8-kRKF5P4_ya7GVJvPs3xXIZC7tC7vbhFCIaxg">

非常感谢
