### ISSUE TITLE
umijs 怎么打包配置多个页面呢？

### ISSUE THREAD

**Issue by cangsnage** [umijs/umi#12402]
## Background

umijs打包配置一个index.html和index2.html文件，我想问下这个应该用entry来配置入口文件么，因为我这边看文档并么有？

## Proposal

我希望的打包后index.html打开的文件菜单是a菜单，index2.html菜单是b菜单
![image](https://github.com/umijs/umi/assets/25116493/6e60e38e-4ee8-472a-93d6-536a8ee80597)
![image](https://github.com/umijs/umi/assets/25116493/58d8698c-8e20-416a-a305-d54b71a46903)
显示不同菜单应该怎么做呢

**Comment by fz6m** [comment]
通常情况下，umi 打包不了多个页面，因为 umi 是个 SPA 的框架，产物只有一个 `index.html` ，所有的请求都要 fallback 到这个 html 上，在 nginx 里的配置是 try_files ，所以就不需要多个 html 了。
