### ISSUE TITLE
[Feature Request] 支持 qiankun 多实例的保活

### ISSUE THREAD

**Issue by asyncguo** [umijs/umi#12415]
## Background

在实践 qiankun 多实例的保活时，遇到的问题是子应用在切换过程中会丢失子应用状态。

<img width="640" alt="image" src="https://github.com/umijs/umi/assets/37094714/8ae9912b-c2db-4b7f-b87c-337c13213118">

[代码仓库](https://github.com/asyncguo/qiankun-multi-instance)

主应用保活子应用的实现：

```tsx
import { Link, Outlet, useOutlet, useRouteProps } from 'umi';
import styles from './index.less';
import { useRef } from 'react';

export default function Layout() {
  const cache = useRef<{
    microApp: string
    element: React.ReactElement<any, string | React.JSXElementConstructor<any>> | null
  }[]>([])
  const element = useOutlet()

  const routeProps = useRouteProps()
  const { microApp } = routeProps

  if (!cache.current.find(r => r.microApp === microApp)) {
    cache.current.push({
      microApp,
      element
    })
  }
  
  return (
    <div className={styles.navs}>
      <ul>
        <li>
          <Link to="/app1">app1</Link>
        </li>
        <li>
          <Link to="/app2">app2</Link>
        </li>
      </ul>

      {
        cache.current.map((app) => {
          return (
            <div
              key={app.microApp}
              hidden={app.microApp !== microApp}
              style={{ border: '1px solid' }}>
              {app.element}
            </div>
          )
        })
      }
    </div>
  );
}

```

经过排查发现是 umi 的 [BrowserRoutes](https://github.com/umijs/umi/blob/master/packages/renderer-react/src/browser.tsx#L41) 内部会监听 history 的变化，而  BrowserRoutes 触发的重新渲染会导致 react-router 的 [Router](https://github.com/remix-run/react-router/blob/7759e8e2912eb69f6dd63b2906490831a2154cfd/packages/react-router/lib/components.tsx#L481) 返回的内容为 null，从而在上一个子应用在重新激活时会进行重新渲染，最后导致状态丢失。

从 react-router 的 Router 来看，具体原因是因为 pathname 和 basename 不匹配时返回 null ，进而导致 Router 组件返回 null。

```tsx {3, 7}
export function Router({
  basename: basenameProp = "/",
  children = null,
  location: locationProp,
  navigationType = NavigationType.Pop,
  navigator,
  static: staticProp = false,
  future,
}: RouterProps): React.ReactElement | null {
  ...

  let locationContext = React.useMemo(() => {
    // pathname 和 basename 不匹配时返回 null ，进而导致 Router 组件返回 null
    let trailingPathname = stripBasename(pathname, basename);
    if (trailingPathname == null) {
      return null;
    }

    return {
      location: {
        pathname: trailingPathname,
        search,
        hash,
        state,
        key,
      },
      navigationType,
    };
  }, [basename, pathname, search, hash, state, key, navigationType]);

  warning(
    locationContext != null,
    `<Router basename="${basename}"> is not able to match the URL ` +
      `"${pathname}${search}${hash}" because it does not start with the ` +
      `basename, so the <Router> won't render anything.`
  );

  if (locationContext == null) {
    return null;
  }

  return (
    <NavigationContext.Provider value={navigationContext}>
      <LocationContext.Provider children={children} value={locationContext} />
    </NavigationContext.Provider>
  );
}
```

## Proposal

期望可以在 umi 的 [BrowserRoutes](https://github.com/umijs/umi/blob/master/packages/renderer-react/src/browser.tsx#L41) 监听 history 的变化时，支持在 basename 和 pathname 不匹配时不再进一步监听 history 的变化。或者给个配置，让用户控制是否执行重新渲染。类似这种：

```diff
function BrowserRoutes(props) {
...
const { history } = props;
  const [state, setState] = React.useState({
    action: history.action,
    location: history.location,
  });
- useLayoutEffect(() => history.listen(setState), [history])
+ useLayoutEffect(() => history.listen((payload) => {
+  if (payload.location.pathname.startsWith(props.basename)) {
+     setState(payload)
+  }
}), [history, props.basename]);
...

}
```

**Comment by jafshare** [comment]
项目里碰到一样的问题，希望官方可以解决

**Comment by fz6m** [comment]
这要看 qiankun 官方有没有针对多实例去提供解决方案，如果不是 qiankun 的 design 范围内，就属于个人的需求，需要自己想办法解决。

框架要做的是一个通用解决方案，如果这个行为是 edge case、或很特殊、受众很少的情况下，提供这种自定义意义不大。

如果 qiankun 没有在官方设计里提供多实例的解决方向的话，最好避开这种使用场景，或者就自己想办法 hack ，然后自己承担风险。

假如就以你提到的这段逻辑自定义的话：

```ts
useLayoutEffect(() => history.listen((payload) => {
  if (payload.location.pathname.startsWith(props.basename)) {
     setState(payload)
  }
```

你可以尝试在一个较早的时机复写 `history.listen` 方法，来实现一些可能的 hack ，比如在 `modifyClientRenderOpts` 里面：

```ts
// app.ts

export const modifyClientRenderOpts = (context: any) => {
  console.log('context: ', context)
  return context
}
```

**Comment by asyncguo** [comment]
> 这要看 qiankun 官方有没有针对多实例去提供解决方案，如果不是 qiankun 的 design 范围内，就属于个人的需求，需要自己想办法解决。
> 
> 框架要做的是一个通用解决方案，如果这个行为是 edge case、或很特殊、受众很少的情况下，提供这种自定义意义不大。
> 
> 如果 qiankun 没有在官方设计里提供多实例的解决方向的话，最好避开这种使用场景，或者就自己想办法 hack ，然后自己承担风险。
> 
> 假如就以你提到的这段逻辑自定义的话：
> 
> ```ts
> useLayoutEffect(() => history.listen((payload) => {
>   if (payload.location.pathname.startsWith(props.basename)) {
>      setState(payload)
>   }
> ```
> 
> 你可以尝试在一个较早的时机复写 `history.listen` 方法，来实现一些可能的 hack ，比如在 `modifyClientRenderOpts` 里面：
> 
> ```ts
> // app.ts
> 
> export const modifyClientRenderOpts = (context: any) => {
>   console.log('context: ', context)
>   return context
> }
> ```

是的，目前个人解决方案也是在 `modifyClientRenderOpts` 里拦截了 `history.listen`。

不过从 qiankun 现在的多实例沙箱来说，好像并没有对 `history` 做严格隔离，只是做了 `patch `。
