### ISSUE TITLE
[Bug] umi3升级umi4遇到的微前端问题

### ISSUE THREAD

**Issue by 4innocent** [umijs/umi#12429]
Unhandled Rejection (TypeError): Cannot read properties of null (reading 'applyPlugins')
_callee5$
.map-web-/src/.umi/plugin-qiankun-slave/lifecycles.ts:46
  43 |   return normalizedHistory;
  44 | }
  45 | 
> 46 | async function getSlaveRuntime() {
  47 |   const config = await getPluginManager().applyPlugins({
  48 |     key: 'qiankun',
  49 |     type: ApplyPluginsType.modify,

这是我的配置文件
// https://umijs.org/config/
import { defineConfig } from '@umijs/max';
import proxy from './proxy';

const { REACT_APP_ENV } = process.env;

export default defineConfig({
  base: '/map/',
  hash: true,
  dva: {},
  locale: {
    // default zh-CN
    // default: 'zh-CN',
    // default true, when it is true, will use `navigator.language` overwrite default
    // antd: true,
    // baseNavigator: true,
  },
  targets: {
    ie: 11,
  },
  // umi routes: https://umijs.org/docs/routing
  routes: [],

  qiankun: {
    slave: {},
  },
  // Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme: {
    // ...darkTheme,
    'primary-color': '#1890ff',
  },
  // @ts-ignore
  title: false,
  ignoreMomentLocale: true,
  proxy: proxy[REACT_APP_ENV || 'dev'],
  manifest: {
    basePath: '/',
  },
  outputPath: 'map-web',
  publicPath: '/map-web/',
});

貌似乾坤插件没有初始化成功

**Comment by fz6m** [comment]
在升级 umi 3 到 4 的过程中，建议新开一个 umi 4 的新项目，然后一点点往里挪，如果整体一下子升级，可能有很多问题不知道如何入手排查，更多信息、文档、升级经验等 请在搜索引擎搜索。

如果你认为 qiankun 有问题，可以先参考以前的 qiankun 配置样子先起两个空的项目试一下能不能关联运行起来，也许就能发现问题。

如还有问题，需要给一个最小复现。

**Comment by yll0910** [comment]
你的主题色theme更改生效嘛！！

**Comment by fz6m** [comment]
如果在运行时想动态更改 antd provider 的值，比如改主题 token ，可以使用 `useAntdConfigSetter` 这个 api ，实例见：`examples/with-antd-5/pages/index.tsx` 。
