### ISSUE TITLE
[Bug] umi4启动时的动画

### ISSUE THREAD

**Issue by jinxiangqiang** [umijs/umi#12438]
可以关闭启动时碗那个动画嘛，在qiankun启动子应用时，会导致主应用闪烁

## Context

- **Umi Version**: 4.2.9
- **Node Version**: 18
- **Platform**: mac

**Comment by fz6m** [comment]
这只是开发时会显示的，不影响生产，闪烁下不会有啥问题。

如必须关闭，可以参考 https://github.com/umijs/umi/issues/12235#issuecomment-2022213891 尝试下。
