### ISSUE TITLE
umi 添加国际化后 本地正常 线上报错 页面空白"umi": "^3.4.8",

### ISSUE THREAD

**Issue by Johnnnnboy** [umijs/umi#12446]
"umi": "^3.4.8",
最近项目需要国际化 用了umi的多语言方案 
本地跑没有问题但是部署线上之后页面打开是空白的
控制台有一个报错，编译后的代码不知道怎么排查有大佬遇到过吗，求指教
<img width="648" alt="image" src="https://github.com/umijs/umi/assets/107901138/be52615b-a52d-4a9d-ba07-79fc256fad6e">
<img width="448" alt="image" src="https://github.com/umijs/umi/assets/107901138/73788576-8998-41af-ba2c-42d759f7266d">

_Originally posted by @Johnnnnboy in https://github.com/umijs/umi/discussions/12445_

**Comment by fz6m** [comment]
See https://github.com/umijs/umi/discussions/12445#discussioncomment-9844428
