### ISSUE TITLE
[Feature Request] chainWebpack 配置devServer.set 无效

### ISSUE THREAD

**Issue by pxim** [umijs/umi#12442]
## Background

根据不同的 环境配置，dev时更换使用不同的public目录，

## Proposal

 "umi": "^4.1.2",版本下，.umirc.ts里配置
```
  chainWebpack(config: any, { webpack }) {
    config.devServer.set('contentBase', './public-demo');
  },
```
更改public目录，发现无效，dev后，资源引用的还是public文件夹下的，不是/public-demo文件夹下的！
请问怎么解决？

## Additional context

- **Umi Version**: 4.1.2
- **Node Version**: v16.20.2
- **Platform**: win10

**Comment by fz6m** [comment]
目前只支持在 `./public` 目录下存放静态资源。
