### ISSUE TITLE
[Bug] umijs/max  max dev 报错 TypeError: The 'compilation' argument must be an instance of Compilation

### ISSUE THREAD

**Issue by Seventysevendays** [umijs/umi#12443]
## umijs/max  max dev 启动报错 TypeError: The 'compilation' argument must be an instance of Compilation

- **Umi Version**: 4.0.70
- **Node Version**: 16.20.1

**Comment by fz6m** [comment]
是自己安装了 webpack 依赖吗，看起来好像是出现了 webpack 多实例问题，删掉 `node_modules` 然后重新安装依赖试试吧。

可以使用 `pnpm why webpack` 查看当前项目有几个 webpack ，正常情况一个也不会有，因为 umi 4 预打包了 webpack 。

如还有问题，需要给一个最小复现看看。

**Comment by Echol136** [comment]
> ## umijs/max max dev 启动报错 TypeError: The 'compilation' argument must be an instance of Compilation
> * **Umi Version**: 4.0.70
> * **Node Version**: 16.20.1

你这个解决了吗，遇到了一样的问题
