### ISSUE TITLE
[Bug] 关于umi3.5x 开启webpack5后 static文件中图片丢失问题 求助！

### ISSUE THREAD

**Issue by ynmlqdl** [umijs/umi#12454]
**我们启动一个新umi项目，升级为webpack5 配置如下:**

![image](https://github.com/umijs/umi/assets/90737076/9c293d39-6e4b-42c2-82e3-a998635a48bf)

**然后导入一张背景图，写在less中，此时看到图片是有的**

![image](https://github.com/umijs/umi/assets/90737076/d4bfac2d-77ef-400e-bbd2-1d4c2e2551f4)
![image](https://github.com/umijs/umi/assets/90737076/2fb11ec5-f0ca-456b-b962-9489651d8b6f)
![image](https://github.com/umijs/umi/assets/90737076/a3365d51-0471-47d1-b182-1bac05d5b1cc)

**然后去less样式文件把这个背景图随便交换下位置 然后控制台Ctrl+c快速关闭项目 然后重新npm start启动项目后，图片就没了，浏览器的source里连static文件夹都不存在了。**

![image](https://github.com/umijs/umi/assets/90737076/6a383d54-ab13-4d7e-81b2-b66d4036e142)
![image](https://github.com/umijs/umi/assets/90737076/a4135192-35cf-4fb0-9a87-cf25f1e9f8cd)
![image](https://github.com/umijs/umi/assets/90737076/241dabaf-32f0-488d-82a8-86a4c2473668)

**求助大佬这个是什么问题导致的？webpack5的问题还能修复吗？有没有什么解决办法?**

## Context

- **Umi Version**: 3.5.41
- **Node Version**: v14.17.3
- **Platform**: windows

**Comment by fz6m** [comment]
umi 3 已经不维护了，建议升级到 umi 4 。

**Comment by ynmlqdl** [comment]
> umi 3 已经不维护了，建议升级到 umi 4 。

没有别的办法吗？升级暂时还不太方便。
