### ISSUE TITLE
umi3升级umi4后，项目启动报错：ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION is not defined

### ISSUE THREAD

**Issue by welmers** [umijs/umi#12450]
ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION is not defined
![1717665224478](https://github.com/umijs/umi/assets/49261109/b617b5c2-6c2c-4e94-b166-6ca6c0a699a1)

**Comment by fz6m** [comment]
在升级 umi 3 到 4 的过程中，建议新开一个 umi 4 的新项目，然后一点点往里挪，如果整体一下子升级，可能有很多问题不知道如何入手排查，更多信息、文档、升级经验等 请在搜索引擎搜索。

如还有问题，给一个最小复现看看吧。
