### ISSUE TITLE
在umi3升级umi4过程中, 执行max setup 时 generate files 过程报错

### ISSUE THREAD

**Issue by undefined996** [umijs/umi#12463]
Error: [BABEL] xxx\polyfill.ts: @babel/helper-compilation-targets: 'false' is not a valid value for 'targets.edge'. (While processing: "xxx\\node_modules\\.pnpm\\@umijs+bundler-utils@4.2.11\\node_modules\\@umijs\\bundler-utils\\compiled\\babel\\preset-env.js")

报这个错, 有什么解决思路么?

**Comment by fz6m** [comment]
应该是配置文件的 `targets` 里配置了 `targets.edge: false` ，这里不允许 boolean 值，去掉这个值就好了。

在升级 umi 3 到 4 的过程中，建议新开一个 umi 4 的新项目，然后一点点往里挪，如果整体一下子升级，可能有很多问题不知道如何入手排查，更多信息、文档、升级经验等 请在搜索引擎搜索。
