### ISSUE TITLE
[Bug] 在pnpm workspace中使用umi4，更新本地依赖包后，umi加载不到新代码

### ISSUE THREAD

**Issue by ijisen** [umijs/umi#12464]
## What happens?

在pnpm workspace中使用umi4，本地依赖包更新后，umi加载不到新代码.

修改 workspace 本地依赖的代码后，并重新编译打包，node_module里面的代码都已经更新了， 但在浏览器里面还是缓存数据， 即使删掉了项目里面所有的node_module,重新安装重启服务后还是拿不到最新的数据。

同样的配置在next服务里面是能够即使更新的。

![image](https://github.com/umijs/umi/assets/16643507/648139e4-0932-4c6c-8b26-7405d2210af7)
![image](https://github.com/umijs/umi/assets/16643507/973b6212-383f-4b6c-89c2-5d0b74cc400b)

**Comment by ijisen** [comment]
本地代码仓中都没有找到相关信息： 1.0.21， 但重启服务还是会显示1.0.21，并不是最新值。
![image](https://github.com/umijs/umi/assets/16643507/0763ffdd-c747-476a-b467-27c875ce3446)

**Comment by rjl-cli** [comment]
wrappers的代码在哪里可以查看？

**Comment by rjl-cli** [comment]
s傻逼umi

**Comment by ijisen** [comment]
> wrappers
https://github.com/ijisen/pnpm-changeset

**Comment by ijisen** [comment]
> wrappers的代码在哪里可以查看？

https://github.com/ijisen/pnpm-changeset

**Comment by rjl-cli** [comment]
wrappers的代码在哪里可以查看？
umi非常好，但是，对于一些特殊的组件库，如react-scroll-parallax
使用是非常不便的。
最好的是，引入umi的wrappers 的逻辑代码。但是我并没有找到，能否告诉我在哪里？

**Comment by ijisen** [comment]
> wrappers

还米有使用

**Comment by fz6m** [comment]
See https://github.com/umijs/umi/discussions/11382#discussioncomment-6373148

如还有问题，请新提一个 issue 。
