### ISSUE TITLE
[Bug] vscode启动umi项目，js/ts插件无法初始化成功，导致项目卡死，电脑卡顿，严重影响开发。

### ISSUE THREAD

**Issue by Mrcxt** [umijs/umi#12472]
umi版本："@umijs/max": "^4.0.68",
包管理器：pnpm

猜测：
<img width="407" alt="image" src="https://github.com/umijs/umi/assets/16064831/992eabdb-b692-4571-a592-6d421b162d64">
<img width="1396" alt="image" src="https://github.com/umijs/umi/assets/16064831/0bb29001-209d-4331-bdfe-0864fba172f1">
会不会是tsconfig中的paths路径太长导致的？或说这几个paths有必要吗？用户自己自定义不好吗？

**Comment by xiaohuoni** [comment]
不用猜测，你外面的 tsconfig 改一下，试试

**Comment by Mrcxt** [comment]
> 不用猜测，你外面的 tsconfig 改一下，试试

我把外面的tsconfig中的extends注释了，依然无法正常初始化项目，

**Comment by Mrcxt** [comment]
实测，添加 "include": ["src", "types"],可规避

**Comment by Mrcxt** [comment]
试了多种方法均无效，无法正常开发。而且这个问题遇到过多次了。偶尔会自己好。

**Comment by fz6m** [comment]
如果遇到 IDE 类型提示失败的问题。

1. 先确保 vscode 是最新版本的。

2. vscode 右下角的 TypeScript ，选择使用本仓库内的 TS 引擎版本。

3. 确保当前打开的 vscode 窗口就是这个项目的根目录，避免多项目干扰 vscode 识别。

4. 确保运行过 `pnpm i` ，此时会自动生成临时文件和继承使用的 `tsconfig.json` 。

5. 如项目内出现类型识别失败的问题，按下 cmd / ctrl + shift + p ，输入 restart TS 选择重启 ts 服务器。
