### ISSUE TITLE
[Bug] global.less 定义不生效

### ISSUE THREAD

**Issue by bxter** [umijs/umi#12475]
我创建的最新umi max工程， 4.1.8
我加入global.less文件，定义一个全局颜色
![image](https://github.com/umijs/umi/assets/59326851/1dcc78cc-c27f-4f09-8cde-6db969224e16)
然后在页面中引用
![image](https://github.com/umijs/umi/assets/59326851/1b994bb7-d568-4e99-9e08-b72c9d61f743)
但是编译启动失败
![image](https://github.com/umijs/umi/assets/59326851/7c07e73c-aa6b-4b72-af9a-782ee47185bd)

--
请问是还需要什么配置选项没加么？？ thks

**Comment by fz6m** [comment]
`src/global.less` 是一个全局样式文件，这里面的 css 变量会被注入到产物里，所以在任何地方可以使用，而并不代表这里面的 less 变量会被全局分享，因为 less 变量和 js 变量一样，需要导入对应的 less 文件才可以使用的，你可以创建一个专门存放 less 变量的 less 文件，每次都 import 导入这个 less 文件来使用共通的 less 变量。

关于更多信息，可查看 less 官网、文档、搜索引擎获取信息。

**Comment by xujiewocao** [comment]
我是global.less样式文件不生效了，开启了msfu
