### ISSUE TITLE
[Bug] 内置tailwindcss报错

### ISSUE THREAD

**Issue by QingXiaoCheng** [umijs/umi#12477]
## What happens?
使用umi内置tailwindcss后启动报错
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.
1、npx create-umi@latest 新创建一个umi项目，start 启动可正常启动
2、umi g tailwindcss生成 Tailwind CSS 和安装相应的依赖后start启动报错，报错信息如下
info  - [plugin: ./node_modules/@umijs/plugins/dist/tailwindcss] tailwindcss service started
error - [plugin: ./node_modules/@umijs/plugins/dist/tailwindcss] tailwindcss generate failed after 5 seconds, please check your tailwind.css and tailwind.config.js

## Context

- **Umi Version**: 4.2.11
- **Node Version**: 18.15.0
- **Platform**: windows

**Comment by fz6m** [comment]
我新建了一个 umi 项目，运行这个命令，可以正常使用 tailwind 。

如还有问题，需要给一个最小复现。

**Comment by Travis-1996** [comment]
![image](https://github.com/user-attachments/assets/06aabe89-39a8-4e86-8792-688dd52cba12)
![Uploading WeChat1d98c9c9ae98b831433a44933a3957fb.png…]()

**Comment by tylerrrkd** [comment]
got the same problem, any friend knows how to resolve it?

```bash
info  - [plugin: @umijs/plugins/dist/tailwindcss] tailwindcss service started

Rebuilding...
info  - [MFSU][eager] worker init, takes 1125ms
error - [plugin: @umijs/plugins/dist/tailwindcss] tailwindcss generate failed after 5 seconds, please check your tailwind.css and tailwind.config.js
```

**Comment by Travis-1996** [comment]
yes, you can remove   tailwindcss: {} form config, and use new plugin deal with tailwindcss， i important app.tsx 
const plugin = require('tailwindcss/plugin')

module.exports = {
  plugins: [
    plugin(function({ addUtilities, addComponents, e, config }) {
      // Add your custom styles here
    }),
  ]

**Comment by komorebi-cqd** [comment]
当我使用umi^4.4.2的版本时会出现这个问题，tailwindcss会运行不了
![2](https://github.com/user-attachments/assets/3a2a973c-38db-4ce6-b2e9-8d3abe62146a)
使用umi^4.0.52去运行这个问题神奇的消失了，我不知道为什么
![3](https://github.com/user-attachments/assets/1fe2f745-174f-4837-8eda-f53eaa57fd24)
