### ISSUE TITLE
期望保留umi3的特性，使用自定义的parentId，id

### ISSUE THREAD

**Issue by jinxiangqiang** [umijs/umi#12471]
## Background

{
path: 'portDocks',
name: '港区',
component: '@/pages/baseData/portDocks',
icon: 'smile',
id: 20240418002010,
parentId: 20240418002,
}

实际.umi中的route:    "38":{"path":"","name":"港区","icon":"smile","id":"38","parentId":"39","originPath":"portDocks"}

## Proposal

期望保留umi3的特性，使用自定义的parentId，id

如： 
"20240418002010":
{"path":"","name":"港区","icon":"smile","id":"20240418002010","parentId":"20240418002","originPath":"portDocks"}

## Additional context

![image](https://github.com/umijs/umi/assets/21325727/29f93a8f-28b2-4587-baef-879c667aa8e4)

**Comment by jinxiangqiang** [comment]
如果我需要自定义，是修改哪个文件

**Comment by fz6m** [comment]
这个值不可以修改，内部需要这个值构建路由树，修改了就用不了了。
