### ISSUE TITLE
[Bug] 使用 umi max 的 “UMI_ENV=22222  max dev” 启动项目 被项目中的 .env 文件 UMI_ENV=333 覆盖了，请问现在环境变量的优先级有调整吗？

### ISSUE THREAD

**Issue by lzbabd** [umijs/umi#12478]

**Comment by fz6m** [comment]
你的 `.env` 文件里面有 `UMI_ENV` 这个变量吗，这个变量目前的设定只能在命令行运行的时候指定，它会决定使用哪个额外的配置，不可以在配置文件里设定。

配置文件的优先级相关详见 [UMI_ENV](https://umijs.org/docs/guides/env-variables#umi_env) 。
