### ISSUE TITLE
chrome v125 打开控制台后 tailwindcss和css-module样式出错

### ISSUE THREAD

**Issue by jiayechao** [umijs/umi#12481]
chrome v125 打开控制台后 tailwindcss和css-module样式出错

![image](https://github.com/umijs/umi/assets/16872226/265f031e-02fc-4df9-8bf6-850225c9451c)

打开控制台后
![79ab3fb97dc903b96e0436676ae76a0](https://github.com/umijs/umi/assets/16872226/47c375ba-da2a-473b-a11a-fd5dc011db46)

- **Umi Version**: 4.1.4
- **Node Version**: 16
- **Platform**: windows

**Comment by fz6m** [comment]
这张截图上，tailwind 的样式都是存在的，是啥问题啊。

如还有问题，需要给一个最小复现。
