### ISSUE TITLE
[Bug] api.writeTmpFile 不能写非字符串类型文件

### ISSUE THREAD

**Issue by qiujie8092916** [umijs/umi#12480]
## What happens?
插件调用 api.writeTmpFile 打算写一个 png 到临时文件夹里
```ts 
 api.writeTmpFile({
	content: fs.readFileSync(join(__dirname, './pages/assets/403.png')),
	path: `pages/assets/403.png`,
});
```
报错 `content.trim is not a function`
https://github.com/umijs/umi/blob/d610bc983d90a6251204d603a9cf66d10faa1cac/packages/preset-umi/src/registerMethods.ts#L114

## Context

- **@umijs/max**: 4.0.64
- **Node Version**: 16.18.0
- **Platform**: mac

**Comment by fz6m** [comment]
这种情况，你直接 copy 过去就行，因为写临时文件这个 api 的设定是以后每次代码有变化的时候都会重新执行一次（因为可能随着用户代码的不同，生成不一样的临时文件内容），而像静态图片文件，永远不会改变的就直接 copy 过去就行。

以下是写的位置一个参考：

```ts

  api.onGenerateFiles(() => {
    const writePath = path.join(
      api.paths.absTmpPath,
      `plugin-${api.plugin.key}`,
      'file.ts',
    )
    // 如果不存在，write 
  })

```
