### ISSUE TITLE
[Bug] umimax 安装unocss报错

### ISSUE THREAD

**Issue by tbtnb** [umijs/umi#12482]
## What happens?
package.json
<img width="473" alt="image" src="https://github.com/umijs/umi/assets/60879811/fad49c6c-bd5c-4670-a369-402f78662ed0">
.umirc.ts
<img width="645" alt="image" src="https://github.com/umijs/umi/assets/60879811/07617d4b-5406-44d0-a254-817d69e65219">

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce
安装unocss后

## Context
错误日志
Module not found: Error: Can't resolve '/Users/bit/Desktop/zhuixing/uva-frontend/src/.umi/uno.css' in '/Users/bit/Desktop/zhuixing/uva-frontend/src/.umi'

- **Umi Version**: umi/max@4.2.13
- **Node Version**: 20.13.1
- **Platform**:

**Comment by fz6m** [comment]
我参考这个文档：[umi 使用 unocss](https://umijs.org/docs/guides/styling#%E4%BD%BF%E7%94%A8-unocss) 试了一下，可以正常使用 unocss 。

如还有问题，需要给一个最小复现。
