### ISSUE TITLE
 使用tailwind生成器生成配置后

### ISSUE THREAD

**Issue by wang-qyy** [umijs/umi#12486]
## 
<img width="805" alt="image" src="https://github.com/umijs/umi/assets/66990199/3bc86060-e089-4378-8ab8-8f3891a2e129">

> [测试代码](https://github.com/wang-qyy/umi_v4) 

## Context

- **umi  Version**: 4.2.13
- **Node Version **: 18.18.0

**Comment by fz6m** [comment]
mpa 不支持 tailwindcss 。

umi 提供的 mpa 是一个最小版本的分页构建功能，一般用于极少数的 h5 页面，不支持各种其他的功能选项。
