### ISSUE TITLE
路由带/能正常访问，不带就无法访问

### ISSUE THREAD

**Issue by wangjun10** [umijs/umi#12488]
## What happens?
打包后发到测试环境后，出现不带斜杠就无法访问页面。
比如访问地址：http://x.x.x.x:31068/agent，点击浏览器的刷新按钮，会自动跳转到
http://x.x.x.x/agent/  导致页面无法访问。
如果访问http://x.x.x.x:31068/agent/，带上斜杠/，那么就能正常访问。
请问如何解决呀？

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
-     "@umijs/fabric": "^4.0.1",
    "@umijs/max": "^4.2.5",
    "@umijs/plugin-model": "^2.6.2",
- **Node Version**:
- v18.18.0
- **Platform**:

**Comment by fz6m** [comment]
请自行研究并调整网关或 nginx 的配置，可能是配置不支持这种情况。
