### ISSUE TITLE
[Bug] legacy模式下css颜色转换错误，不支持禁用colormin

### ISSUE THREAD

**Issue by richardkc** [umijs/umi#12491]
## bug：legacy 模式下colormin转换hsla取整，导致结果有偏差

过程如下：

css：
![image](https://github.com/umijs/umi/assets/48274462/6b06ffac-9e6e-48d3-b3d4-4c1101dc5cb8)
在正常编译下，结果如下：
![image](https://github.com/umijs/umi/assets/48274462/87eb958a-31c3-4ad1-999d-a309d2a7e527)
开启 legacy 后：
![image](https://github.com/umijs/umi/assets/48274462/8c4cff17-e1c9-497d-8144-9255e481eddb)
![image](https://github.com/umijs/umi/assets/48274462/19295a61-071e-4607-829c-cfa841997604)

而 hsla(0,0%,85%,.8) 实际色值为 rgba(217, 217, 217, 0.8)。目前尝试了多种方法，没法在 umi 的框架下单独禁用 colormin，除非将整个 css 压缩禁用掉。

## 期望：
增加 colormin 的可控配置项

## 参考：
[postcss-colormin: incorrect "colormin"'s color conversion](https://github.com/cssnano/cssnano/issues/819)

**Comment by fz6m** [comment]
使用 css 变量避开被转换。

**Comment by richardkc** [comment]
> 使用 css 变量避开被转换。

项目需要支持低版本浏览器，不能使用css变量。。。

**Comment by fz6m** [comment]
```ts
// .umirc.ts

  cssMinifierOptions: {
    preset: [
      'default',
      {
        colormin: false,
      },
    ],
  },
  legacy: {},
```
