### ISSUE TITLE
通过注释扩展路由，改变路由query，会导致该路由重新渲染

### ISSUE THREAD

**Issue by feibi** [umijs/umi#1249]
重现步骤：
1. 点击button1, state.show: true
2. 点击botton2, location.query.a: true, 此时 state.show会还原为false 

重现代码：

```js
//pages/exapmle/index.js

/*
 *  title: 'example'
 */
import React, { Component } from 'react';
import { withRouter } from 'dva/router';
import router from 'umi/router';

class Example extends Component {
  state = {
    show: false,
  };
  handleClick = () => {
    this.setState({
      show: !this.state.show,
    });
  };

  handleChangeQuery = () => {
    const { location } = this.props;
    const { pathname, query } = location;
    router.push({ pathname, query: { a: !query.a } });
  };
  render() {
    return (
      <div>
        {this.state.show ? 'show' : 'hidden'}
        <button onClick={this.handleClick}>button1</button>
        <button onClick={this.handleChangeQuery}>button2</button>
      </div>
    );
  }
}

export default withRouter(Example);
```

> 添加title注释,改变location的query,当前路由会重新渲染，导致组件内的state重置。去掉title注释不会有此现象

**Comment by feibi** [comment]
@sorrycc  在线编辑器总是加载失败，给个git仓库 地址吧 `https://github.com/feibi/umi-test.git `, 辛苦了~

**Comment by sorrycc** [comment]
![a](https://user-images.githubusercontent.com/35128/46999645-cbb89900-d158-11e8-894d-0b080bec5dd7.gif)

试了下你提供的库，也没有重现。。

**Comment by feibi** [comment]
这么诡异的吗。。

- 操作系统: window10
- 浏览器:  69.0.3497.100（正式版本） （64 位）
- node版本: v10.1.0


#### 执行步骤
1. git clone 
2. yarn
3. npm start
> 刚才重新拉代码，按照上面步骤，问题还是存在的。。

![bug](https://user-images.githubusercontent.com/16058286/47009696-b864f800-d16f-11e8-817c-a76d505474c9.gif)

**Comment by feibi** [comment]
最新 umi@2.2.3 版本，已经无此问题
