### ISSUE TITLE
[Bug] 内置tsconfig.json @umijs/max配置无法正确的出现智能提示

### ISSUE THREAD

**Issue by zhouzyc** [umijs/umi#12499]
## What happens?
1.如图在 @umijs/max存在时
![image](https://github.com/umijs/umi/assets/18420689/c4fe8ab0-a0d0-497e-b9ef-7946d442165d)
2.智能提示的导入路径为@/.umi/exports
![image](https://github.com/umijs/umi/assets/18420689/1e41a987-bd0f-4058-87d4-d9a7d0bc5a77)
3.删除 @umijs/max的配置
![image](https://github.com/umijs/umi/assets/18420689/b167d12e-ccf8-40ea-a954-4a4024906d7a)
4.正确的出现提示
![image](https://github.com/umijs/umi/assets/18420689/0c8dcafb-9fe4-471d-a1d9-aa23db886d63)

## Mini Showcase Repository(REQUIRED)

https://gitee.com/JS-VeryHappy/vh-admin-template-default.git

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: @umijs/max:4.2.13
- **Node Version**: v20.12.0
- **Platform**: windows pnpm

**Comment by fz6m** [comment]
这个问题我没复现，可能只在 windows 上存在，或者和 Vscode 的下拉框提示的优先级配置有关。

**Comment by zhouzyc** [comment]
麻烦有windows的同学看看

**Comment by sorrycc** [comment]
<img width="571" alt="image" src="https://github.com/umijs/umi/assets/35128/938de560-a5a1-4535-b5d9-ff9ee41e5488">

这里手动把 `\\` 改成 `/` 可以修复吗？

**Comment by zhouzyc** [comment]
@sorrycc 试了下还是不行，附上操作
![tutieshi_640x419_20s](https://github.com/umijs/umi/assets/18420689/cb1d3e91-1adb-4697-a0b1-d4d418aba519)

**Comment by fz6m** [comment]
也许解决方式是把 `@umijs/max` 的别名放到 `paths` 的第一个位置？这样试试呢。

**Comment by zhouzyc** [comment]
> 也许解决方式是把 `@umijs/max` 的别名放到 `paths` 的第一个位置？这样试试呢。

我试过了好像不行

**Comment by crazyair** [comment]
不错，提供复现了，就好解决了
