### ISSUE TITLE
[Bug] 路由preload和qiankun一起使用造成的bug

### ISSUE THREAD

**Issue by consistent-k** [umijs/umi#12495]
## What happens?
升级umijs/max到最新（4.2.13） 部署后发现js和css资源加载异常，排查后得知可能是preload route提交导致的。

## Mini Showcase Repository(REQUIRED)

https://github.com/consistent-k/umi-demo

## How To Reproduce
1、将示例代码库中的主应用（base）和子应用（child）分别进行编译
2、使用nginx启动（仓库内有示例nginx，需要修改一些路径即可）
3、访问主应用路由 /child/detail
4、打开控制台观察加载情况

<img width="1407" alt="image" src="https://github.com/umijs/umi/assets/67736912/3437a25f-3bc4-40e0-a791-5ca8d45992e4">

5、排查配置项后得知。child的.umirc.ts中
<img width="796" alt="image" src="https://github.com/umijs/umi/assets/67736912/a6f6680e-6d18-4f87-bd72-3dea4a8eea2c">
此处配置如果修改为不是 /child 上图加载资源就是正常或者将child的umi降级回到4.1.0也可以正常加载，请排查一下这个配置项是否有错。

补充：child的base配置为 /child是为了单独访问子应用的时候保持和通过主应用访问一样的路径，项目正常运行了一年多了。

## Context

- **Umi Version**: 4.2.13
- **Node Version**: 20
- **Platform**: Mac OS Chrome最新

**Comment by consistent-k** [comment]
补充：child的base配置为 /child是为了单独访问子应用的时候保持和通过主应用访问一样的路径，项目正常运行了一年多了。

**Comment by consistent-k** [comment]
怀疑是这个pr导致的 https://github.com/umijs/umi/pull/12234 求 @fz6m 大佬帮忙定位一下 影响了我这边多个项目的正常使用

**Comment by zhengzhuang96** [comment]
+1

**Comment by consistent-k** [comment]
@sorrycc 云谦哥 这个bug有空帮忙看一下不

**Comment by fz6m** [comment]
我用你的仓库试了下，没遇到你说的问题，以下是我的步骤：

### 子应用 child

1. 去掉 `src/app.ts` / `src/public-path.ts` ，这俩文件没用，只要我在 `/static-child-web/*` 上提供静态资源就可以了，不需要修改 qiankun 。

2. 构建项目，得到 `dist/static-child-web` 。

3. 在 `http://localhost:8000/child` 上提供网站，在 `http://localhost:8000/static-child-web` 上提供资源，最简 nginx 配置部分如下：

```conf
        root /path/to/child/dist;

        location /child {
            add_header 'Access-Control-Allow-Origin' '*' always;
            try_files $uri $uri/ /static-child-web/index.html;
        }

        location /static-child-web/ {
            add_header 'Access-Control-Allow-Origin' '*' always;
            alias /path/to/child/dist/static-child-web/;
        }
```

4. 访问 `http://localhost:8000/child` 和 `http://localhost:8000/child/detail` ，正常。

### 主应用 base

1. 修改 `src/app.ts` ，entry 先改为本地地址，用于验证：

```ts
export const qiankun = () => {
    return {
        apps: [
            {
                name: 'app1',
                entry: 'http://localhost:8001/static-child-web/index.html',
            }
        ]
    };
};
```

2. 构建项目，在 `http://localhost:8002` 上提供服务，在 `http://localhost:8002/static-base-web/*` 提供资源：

```conf
        root /path/to/base/dist;
        
        location / {
            try_files $uri $uri/ /static-base-web/index.html;
        }

        location /static-base-web/ {
            alias /path/to/dist/static-base-web/;
        }
```

为保证用例最小化，去掉了反代，直接访问 `8001` 能跑通道理一样的。

3. 访问 `http://localhost:8002/child` 正常，能看到子应用，控制台 preload 资源加载正常。

**Comment by fz6m** [comment]
如还有问题，需要给一个会报错的复现。

**Comment by consistent-k** [comment]
> 我用你的仓库试了下，没遇到你说的问题，以下是我的步骤：
> 
> ### 子应用 child
> 1. 去掉 `src/app.ts` / `src/public-path.ts` ，这俩文件没用，只要我在 `/static-child-web/*` 上提供静态资源就可以了，不需要修改 qiankun 。
> 2. 构建项目，得到 `dist/static-child-web` 。
> 3. 在 `http://localhost:8001/child` 上提供网站，在 `http://localhost:8001/static-child-web` 上提供资源，最简 nginx 配置部分如下：
> 
> ```
>         root /path/to/child/dist;
> 
>         location /child {
>             add_header 'Access-Control-Allow-Origin' '*' always;
>             try_files $uri $uri/ /static-child-web/index.html;
>         }
> 
>         location /static-child-web/ {
>             add_header 'Access-Control-Allow-Origin' '*' always;
>             alias /path/to/child/dist/static-child-web/;
>         }
> ```
> 
> 4. 访问 `http://localhost:8001/child` 和 `http://localhost:8001/child/detail` ，正常。
> 
> ### 主应用 base
> 1. 修改 `src/app.ts` ，entry 先改为本地地址，用于验证：
> 
> ```ts
> export const qiankun = () => {
>     return {
>         apps: [
>             {
>                 name: 'app1',
>                 entry: 'http://localhost:8001/static-child-web/index.html',
>             }
>         ]
>     };
> };
> ```
> 
> 2. 构建项目，在 `http://localhost:8002` 上提供服务，在 `http://localhost:8002/static-base-web/*` 提供资源：
> 
> ```
>         root /path/to/base/dist;
>         
>         location / {
>             try_files $uri $uri/ /static-base-web/index.html;
>         }
> 
>         location /static-base-web/ {
>             alias /path/to/dist/static-base-web/;
>         }
> ```
> 
> 为保证用例最小化，去掉了反代，直接访问 `8001` 能跑通道理一样的。
> 
> 3. 访问 `http://localhost:8002/child` 正常，能看到子应用，控制台 preload 资源加载正常。

回复：
首先，我按照你的配置配了确实没问题，但是按照我实际业务的需求需要稍作修改就会有问题，这些修改也是我这边必须做的，以下是复现步骤。

1、base里apps下的entry 我不能配置为 完整的http://localhost:8001/static-child-web/index.html 我配置成了 /static-child-web 因为涉及到个不同客户的不同服务器部署，模块ip和端口是不固定的。

2、因为要提供最小示例，所以我在base里加了反向代理，实际部署时候这里是由k8s的ingress处理。

3、我按照你的提示去掉了child下的 src/app.ts 和  src/public-path.ts 构建

4、将两个模块启动后发现如下报错：
![image](https://github.com/umijs/umi/assets/67736912/1743c395-8cd5-4224-92d5-7c1e54936e79)

5、恢复 child下的 src/app.ts 和  src/public-path.ts 后构建 服务恢复正常访问 但是观察network的请求存在重复加载。
![image](https://github.com/umijs/umi/assets/67736912/59bc5038-e641-46d9-9571-18f5a0ad1d5b)
第一个地址是异常的 这个路径没有加子应用的publicpath前缀 
![image](https://github.com/umijs/umi/assets/67736912/1f4054e7-fc56-4f2b-86de-a3b017d48f9b)
第二个资源为正常
![image](https://github.com/umijs/umi/assets/67736912/7bead140-71c6-400d-89b8-c07245c96103)

**Comment by fz6m** [comment]
因为上面提供的步骤可以正常跑起来应用，所以应该以这个最小成功例子为准，之后的增量改动尽量避免破坏这个最小成功例子的配置。

1、qiankun 的 entry 应该配置为绝对路径，避免各种问题，如果你不知道完整路径，应该通过环境变量注入或者 `window.location` 等方式获取来构造完整的路径。

2. 在原来 `src/app.ts` 里修改 qiankun 等内部值是不可取的，这不是正常的标准用法，不要这么使用。
