### ISSUE TITLE
umi4不能使用react-router-dom里的useblocker这个api  报错

### ISSUE THREAD

**Issue by HelenTim** [umijs/umi#12513]
我看了一下很可能是react-router-dom版本引发的，6.3没有这个api，6.24这个版本有

**Comment by fz6m** [comment]
`useBlocker` 只能在 data router 下使用，而 umi 4 使用的不是 Data router ，是 v6 早期版本的 browser router ，所以无法使用这个 api 。

如需 block 类似的功能，参考 https://github.com/umijs/umi/discussions/10237#discussioncomment-4625915

**Comment by kokiy** [comment]
我看最新的react router 6.26.0 好学没有说有data router 的限制了,大佬能帮忙看一下吗 @fz6m

**Comment by kokiy** [comment]
> `useBlocker` 只能在 data router 下使用，而 umi 4 使用的不是 Data router ，是 v6 早期版本的 browser router ，所以无法使用这个 api 。
> 
> 如需 block 类似的功能，参考 [#10237 (reply in thread)](https://github.com/umijs/umi/discussions/10237#discussioncomment-4625915)
这个是无法自定义组件的

**Comment by jiankafei** [comment]
我们的项目开发二方包，不能直接引用umi（import { history } from 'umi'), 所以需要用到 react-router 的 useBlocker api，什么时候升级react-router？
