### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by lsy934127847** [umijs/umi#12514]
![image](https://github.com/umijs/umi/assets/72968089/ff875d2e-0809-441a-a356-733bd0034787)

使用useModel 为啥触发不了组件 render ？

**Comment by lsy934127847** [comment]
虽然引用对象变了， 但是对比的时候没有发生改变。 在使用useState 的时候 正常。 说明useModel 在值的处理上拦截了一层？

**Comment by fz6m** [comment]
如有问题，需要给一个最小复现。
