### ISSUE TITLE
umi项目不支持在css文件中使用tailwind的`@apply`指令？

### ISSUE THREAD

**Issue by gmqiyue** [umijs/umi#12526]
### Discussed in https://github.com/umijs/umi/discussions/12524

<div type='discussions-op-text'>

<sup>Originally posted by **gmqiyue** July  3, 2024</sup>
我使用pnpm create umi aproject创建的新项目，通过`pnpm exec umi g tailwindcss`添加配置后，src目录下的所有css文件使用`@apply`指令，构建出的代码没有被解析转译（如下图：
![image](https://github.com/umijs/umi/assets/87467755/b153f08d-d7f5-4b2b-b4b8-003def48289b)
</div>

**Comment by fz6m** [comment]
See #12524
