### ISSUE TITLE
[Feature Request] 希望能更新一下依赖包

### ISSUE THREAD

**Issue by caijf** [umijs/umi#12528]
![image](https://github.com/umijs/umi/assets/5070722/940a2782-f9b6-4f15-b662-219a20670ddf)

**Comment by fz6m** [comment]
dva / ahooks request 等依赖是 umi 3 遗留的插件附带的，这些功能已经很久不维护了，但为了适配 umi 3 升级 4 ，所以这些上古功能还是保留了下来，如没有必要，不再推荐使用这些功能。

**Comment by caijf** [comment]
如果没有使用这些功能，可以提供个方案移除这些依赖吗？

**Comment by fz6m** [comment]
1. 把 umi 仓库的 `packages/plugins` 里面的源码全部 copy 出来，之后挑选需要的插件和依赖留下，其余的删掉，自己发布一个插件包。

2. 使用 umi ，而不是 max （因为 max 内置了 `@umijs/plugins`），之后安装你发布的插件包，在配置文件内使用这些 `plugins` 即可。

**Comment by caijf** [comment]
官方可以更新下面几个包的 `package.json` 吗？
 
 ```text
 @umijs/plugins
ahooksjs/use-request
dva-loading
dav
```

例如 `dva` 

改之前
```diff
"peerDependencies": {
-  "react": "15.x || ^16.0.0-0",
-  "react-dom": "15.x || ^16.0.0-0"
},
```
改之后
```diff
"peerDependencies": {
+  "react": "15.x-18.x",
+  "react-dom": "15.x-18.x"
},
```

改动不大，貌似也没有什么副作用。
