### ISSUE TITLE
[Bug] 开启vite配置后，项目编译直接报错终止

### ISSUE THREAD

**Issue by yzfpf** [umijs/umi#12537]
## What happens?

![image](https://github.com/umijs/umi/assets/170693014/7cc64e96-fb03-48a5-a34c-eb8e4db34310)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.3.1
- **Node Version**:20.11.1
- **Platform**:macOS

**Comment by fz6m** [comment]
如有问题，需要给一个会报错的最小复现。

**Comment by lzw10168** [comment]
我也碰到了, 解决了吗 哥们

**Comment by songlairui** [comment]
我也碰到了。。。 这样的报错看不出来信息。


我的出错效果： 在现有项目的配置，添加一个 vite:{ }, 空配置，就会这样。


但报错信息，看起来不像是需要一个默认的配置。而是解析配置的时候就报错了。
