### ISSUE TITLE
[Feature Request] @@/core/history 增加对 basename 的导出

### ISSUE THREAD

**Issue by purple-force** [umijs/umi#12540]
## Background

在写一个通用的响应拦截器插件，在登录失效情况下，原先是用 history.push 到本工程内的 '/login' 路由页面。现在需要新打开独立的登录页，在存在路由前缀(.umirc.ts 中配置 base)、微前端子应用等场景下，没有 basename，无法拼接完整的跳转链接

## Proposal

[export { history };](https://github.com/umijs/umi/blob/c72de1ed677604608fac587084c5697ef5a81217/packages/preset-umi/templates/history.tpl#L74) 这里增加 basename 的导出。这样在自定义插件中即可通过 import { basename } from '@@/core/history' 获取 basename

**Comment by fz6m** [comment]
需要配置文件配置的 `base` 值的话，比较好的方式是在配置文件里把这个值用 [`define`](https://umijs.org/docs/api/config#define) 注入，之后项目里通过 `process.env.XXX` 使用。

**Comment by purple-force** [comment]
> 需要配置文件配置的 `base` 值的话，比较好的方式是在配置文件里把这个值用 [`define`](https://umijs.org/docs/api/config#define) 注入，之后项目里通过 `process.env.XXX` 使用。

子应用场景下呢？需要用 父应用 base + 子应用前缀，规则可能有很多，而从 history 里导出则比较直接。
