### ISSUE TITLE
[Bug] pnpm 安装的依赖过多导致 useModel 无法智能提示 @umijs/max

### ISSUE THREAD

**Issue by crazyair** [umijs/umi#12545]
## What happens?

使用 vscode 编辑器，代码中编写 `useModel('usexxx')`，鼠标 hover 到 useModel 上，快速修复没有`从 @umijs/max 引入提示`
如果 pnpm 是用 v6 是没问题的，但是用 v8.15.3 则失效

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/crazyair/umi （本仓库没用，重要的是你要用 pnpm v8 安装依赖）

如果是用了 corepack，这可以在 pacakge.json 中增加 `"packageManager": "pnpm@8.15.3"`，然后 install

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:latest
- **Node Version**:latest
- **Platform**:mac

**Comment by crazyair** [comment]
试了下，pnpm v9.5.0 也不可以，不知道 pnpm 改还是 umi 改
问题原因是
正确的
```ts
    "@umijs/max": [
        "/Users/crazyair/test/umi-max/node_modules/.pnpm/umi@4.3.1_c3f540743a6b941a5c25988f5eaba7d7/node_modules/umi"
      ],

```

错误的

```ts
"@umijs/max": [
        "/Users/crazyair/test/umi-max/node_modules/.pnpm/umi@4.3.1_c3f540743a6b941a5c25988f5eaba7d7/node_modules/umi"
      ],
```

**Comment by crazyair** [comment]
@fz6m 麻烦看下这个

**Comment by crazyair** [comment]
复现出来了 https://github.com/crazyair/umi-max-use-model-bug

**Comment by crazyair** [comment]
是 `dependencies` 安装的依赖过多，比如现在 17 个，就会无法推导类型

**Comment by PeachScript** [comment]
这周已发版，该 PR 下周发

**Comment by crazyair** [comment]
> 这周已发版，该 issue 对应 PR 下周发

一天发2个版本啊

**Comment by PeachScript** [comment]
@Jinbao1001 给 @zombieJ 补了个版本，他既要 Mako 也要改 node_modules 做调试

**Comment by crazyair** [comment]
@fz6m 等会，我验证了下，@umijs/max 的路径变成了 `../../node_modules/xxx` 然后自己又突然变成了 `/Users/xxx`

**Comment by crazyair** [comment]
> @fz6m 等会，我验证了下，@umijs/max 的路径变成了 `../../node_modules/xxx` 然后自己又突然变成了 `/Users/xxx`

知道了，更新 4.3.5 后，路径正确了，但是改 src 代码触发了 start 的刷新，导致又恢复回去了
