### ISSUE TITLE
请问 umi 的入口文件在哪里？

### ISSUE THREAD

**Issue by sphawkcn** [umijs/umi#1254]
由 create-react-app 或者  dva-cli 创建的样板文件中都有一个名为 index.js 的入口文件。

一般在这里可以做一些需要在进入系统时就初始化的全局性工作，比如：读取 localStorage 里面的 token，来确定用户是否已经登录，如果已经登录则用 token 里面的信息设置当前用户等等工作。

但是由 npm create umi 生成的样板文件中找不到 index.js 入口文件，虽然有一个 /src/pages/inde.js，但是这个是普通的页面文件，而非入口文件。

请问：类似上面提到的在进入系统时就需要初始化的全局性工作，在 umi 里面应该怎么做呢？先行谢过。

**Comment by sorrycc** [comment]
入口文件在 `src/pages/.umi/umi.js`，这是一个临时文件，由 umi 自动生成。

**Comment by sorrycc** [comment]
> 类似上面提到的在进入系统时就需要初始化的全局性工作，在 umi 里面应该怎么做呢？

如果和渲染无关，可以放 `src/global.js` 里；如果需要做一些异步的事情，然后才渲染页面，可以新建 app.js，通过导出的 render 方法进行定制，参考例子 https://github.com/umijs/umi/blob/master/packages/umi/test/runtime/app.js#L5

**Comment by roc2539** [comment]
@sorrycc 这里app.js，通过导出的 render 方法进行定制，可有详细文档介绍？我看到antd Pro里面也有这些代码。取得是mock数据，我们自己写后台接口的时候，是通过这个接口返回用户的权限码？ 不对吧。

**Comment by hamger** [comment]
> > 类似上面提到的在进入系统时就需要初始化的全局性工作，在 umi 里面应该怎么做呢？
> 
> 如果和渲染无关，可以放 `src/global.js` 里；如果需要做一些异步的事情，然后才渲染页面，可以新建 app.js，通过导出的 render 方法进行定制，参考例子 https://github.com/umijs/umi/blob/master/packages/umi/test/runtime/app.js#L5

这个地址错误

**Comment by BearGS** [comment]
> > 类似上面提到的在进入系统时就需要初始化的全局性工作，在 umi 里面应该怎么做呢？
> 
> 如果和渲染无关，可以放 `src/global.js` 里；如果需要做一些异步的事情，然后才渲染页面，可以新建 app.js，通过导出的 render 方法进行定制，参考例子 https://github.com/umijs/umi/blob/master/packages/umi/test/runtime/app.js#L5

地址错误

**Comment by Lynn0108** [comment]
https://github.com/umijs/umi/blob/master/packages/umi/test/fixtures/build/runtime-plugins/app.js

**Comment by raxxarr** [comment]
可以考虑通过 umi 插件方式实现，它会更「早」一些：
https://umijs.org/zh/plugin/develop.html#addentrycodeahead

**Comment by wangliguang** [comment]
我想给网站添加一个script标签，用来做数据统计，统计平台说要添加到<Body>标签里，但umi里压根找不到html文件，请教一下该如何处理

**Comment by huangchaosysu** [comment]
> 我想给网站添加一个script标签，用来做数据统计，统计平台说要添加到Body标签里，但umi里压根找不到html文件，请教一下该如何处理 @sorrycc

参考这里?
https://umijs.org/zh/guide/html-template.html#%E4%BF%AE%E6%94%B9%E9%BB%98%E8%AE%A4%E6%A8%A1%E6%9D%BF

**Comment by liuxiuqian** [comment]
如何在 qiankun 的微应用中导出 导出 bootstrap、mount、unmount 三个生命周期钩子。官方要求是配置在 webpack 的 entry js。在 umi 的项目中找不到 入口文件。不使用 @umijs/plugin-qiankun @sorrycc 

报错信息是没有 导出生命周期函数
![image](https://user-images.githubusercontent.com/19403902/84728872-dfb73c80-afc4-11ea-93da-aa879b37f56f.png)

**Comment by BlancheXu** [comment]
> 如何在 qiankun 的微应用中导出 导出 bootstrap、mount、unmount 三个生命周期钩子。官方要求是配置在 webpack 的 entry js。在 umi 的项目中找不到 入口文件。不使用 @umijs/plugin-qiankun @sorrycc
> 
> 报错信息是没有 导出生命周期函数
> ![image](https://user-images.githubusercontent.com/19403902/84728872-dfb73c80-afc4-11ea-93da-aa879b37f56f.png)

请问这个不使用插件 @umijs/plugin-qiankun的情况下解决了嘛？

**Comment by Hquestion** [comment]
> 如何在 qiankun 的微应用中导出 导出 bootstrap、mount、unmount 三个生命周期钩子。官方要求是配置在 webpack 的 entry js。在 umi 的项目中找不到 入口文件。不使用 @umijs/plugin-qiankun @sorrycc
> 
> 报错信息是没有 导出生命周期函数
> ![image](https://user-images.githubusercontent.com/19403902/84728872-dfb73c80-afc4-11ea-93da-aa879b37f56f.png)

通过插件@umi/plugin-qiankun

**Comment by Hquestion** [comment]
> 如何在 qiankun 的微应用中导出 导出 bootstrap、mount、unmount 三个生命周期钩子。官方要求是配置在 webpack 的 entry js。在 umi 的项目中找不到 入口文件。不使用 @umijs/plugin-qiankun @sorrycc
> 
> 报错信息是没有 导出生命周期函数
> ![image](https://user-images.githubusercontent.com/19403902/84728872-dfb73c80-afc4-11ea-93da-aa879b37f56f.png)

应该只能通过插件才能修改到入口文件吧？我最近也遇到这个问题，umi2版本，qiankun2版本，没找到合适的插件

**Comment by zszjy** [comment]
> > 我想给网站添加一个script标签，用来做数据统计，统计平台说要添加到Body标签里，但umi里压根找不到html文件，请教一下该如何处理 @sorrycc
> 
> 参考这里?
> https://umijs.org/zh/guide/html-template.html#%E4%BF%AE%E6%94%B9%E9%BB%98%E8%AE%A4%E6%A8%A1%E6%9D%BF

这个链接打不开呢

**Comment by sunsmeil** [comment]
> > > 我想给网站添加一个script标签，用来做数据统计，统计平台说要添加到Body标签里，但umi里压根找不到html文件，请教一下该如何处理 @sorrycc
> > 
> > 
> > 参考这里?
> > https://umijs.org/zh/guide/html-template.html#%E4%BF%AE%E6%94%B9%E9%BB%98%E8%AE%A4%E6%A8%A1%E6%9D%BF
> 
> 这个链接打不开呢

https://umi-git-tweak-now-action-site.umijs.vercel.app/zh/guide/html-template.html#%E4%BF%AE%E6%94%B9%E9%BB%98%E8%AE%A4%E6%A8%A1%E6%9D%BF 用这个

**Comment by lsky-walt** [comment]
> > 如何在 qiankun 的微应用中导出 导出 bootstrap、mount、unmount 三个生命周期钩子。官方要求是配置在 webpack 的 entry js。在 umi 的项目中找不到 入口文件。不使用 @umijs/plugin-qiankun @sorrycc
> > 报错信息是没有 导出生命周期函数
> > ![image](https://user-images.githubusercontent.com/19403902/84728872-dfb73c80-afc4-11ea-93da-aa879b37f56f.png)
> 
> 应该只能通过插件才能修改到入口文件吧？我最近也遇到这个问题，umi2版本，qiankun2版本，没找到合适的插件

请教一下，umi2版本 ，使用qiankun2之后如何解决的？

**Comment by yzkkunshao** [comment]
umi2的话可以参考这个https://v2.umijs.org/zh/guide/runtime-config.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%9C%89%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE%EF%BC%9F
