### ISSUE TITLE
[Bug] 无法获得 responseInterceptors 重试失败请求的结果

### ISSUE THREAD

**Issue by ace-han** [umijs/umi#12542]
## What happens?
无法获得 responseInterceptors 重试失败请求的结果

按照文档 https://umijs.org/docs/max/request 在 `app.ts` 定制了 `request` 的 `responseInterceptors`, 但是 `const userInfo = await getUserInfoViaUmi()` 得不到 重试后的结果

业务中用到了 JWT 的认证体系 refresh token 的机制，涉及`access token` 过期后通过 `token refresh` api 刷新`access token`， 重放失败的request， 但却导致原始方法调用的地方得不到即使正确返回的结果

根据axios 的文档进行同样的 `interceptors.response.use` 却是没有问题的

具体可以主要refer to以下文件

https://github.com/ace-han/umi-res-interceptor-error-demo/blob/main/src/pages/Home/index.tsx
https://github.com/ace-han/umi-res-interceptor-error-demo/blob/main/src/utils/umi-request.ts
https://github.com/ace-han/umi-res-interceptor-error-demo/blob/main/src/utils/axios-request.ts
https://github.com/ace-han/umi-res-interceptor-error-demo/blob/main/src/services/demo/AuthController.ts
https://github.com/ace-han/umi-res-interceptor-error-demo/blob/main/mock/authAPI.ts

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

为方便排查

按照文档 https://umijs.org/docs/guides/getting-started 进行项目 初始化

```shell
pnpm dlx create-umi@latest
Packages: +40
++++++++++++++++++++++++++++++++++++++++
Progress: resolved 40, reused 38, downloaded 2, added 40, done
┌   create-umi 
│
○  Pick Umi App Template
│  Ant Design Pro
│
○  Pick Npm Client
│  pnpm
│
○  Pick Npm Registry
│  taobao
│
└  You're all set!


   ╭─────────────────────────────────────────────────────────────────╮
   │                                                                 │
   │                Update available! 9.4.0 → 9.5.0.                 │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v9.5.0   │
   │                Run "pnpm add -g pnpm" to update.                │
   │                                                                 │
   │        Follow @pnpmjs for updates: https://x.com/pnpmjs         │
   │                                                                 │
   ╰─────────────────────────────────────────────────────────────────╯

Downloading antd@5.19.1: 9.65 MB/9.65 MB, done
 WARN  14 deprecated subdependencies found: @floating-ui/react-dom-interactions@0.3.1, @formatjs/intl-unified-numberformat@3.3.7, @formatjs/intl-utils@2.3.0, @humanwhocodes/config-array@0.11.14, @humanwhocodes/object-schema@2.0.3, @stylelint/postcss-css-in-js@0.38.0, @types/history@5.0.0, flatten@1.0.3, glob@7.2.3, inflight@1.0.6, intl-messageformat-parser@3.6.4, react-router-redux@5.0.0-alpha.9, rimraf@3.0.2, stable@0.1.8
Packages: +1300
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading @umijs/mako-darwin-arm64@0.7.4: 14.25 MB/14.25 MB, done
Progress: resolved 1350, reused 1243, downloaded 45, added 1300, done
node_modules/.pnpm/es5-ext@0.10.64/node_modules/es5-ext: Running postinstall script, done in 59ms

> @ postinstall /Users/ace/workspace/ace/umi-res-interceptor-error-demo
> max setup

info  - [你知道吗？] 如果你需要使用 Tailwind CSS, max g tailwindcss 就可以一键完成配置，详见 https://umijs.org/docs/guides/generator#tailwind-css-配置生成器
info  - generate files
info  - Preparing...

> @ prepare /Users/ace/workspace/ace/umi-res-interceptor-error-demo
> husky


dependencies:
+ @ant-design/icons 5.3.7
+ @ant-design/pro-components 2.7.10
+ @umijs/max 4.3.1
+ antd 5.19.1

devDependencies:
+ @types/react 18.3.3
+ @types/react-dom 18.3.0
+ husky 9.0.11
+ lint-staged 13.3.0 (15.2.7 is available)
+ prettier 2.8.8 (3.3.2 is available)
+ prettier-plugin-organize-imports 3.2.4 (4.0.0 is available)
+ prettier-plugin-packagejson 2.5.0
+ typescript 5.5.3

# ... some dependencies warning output...

Done in 21.9s

# add axios
pnpm add axios
 WARN  14 deprecated subdependencies found: @floating-ui/react-dom-interactions@0.3.1, @formatjs/intl-unified-numberformat@3.3.7, @formatjs/intl-utils@2.3.0, @humanwhocodes/config-array@0.11.14, @humanwhocodes/object-schema@2.0.3, @stylelint/postcss-css-in-js@0.38.0, @types/history@5.0.0, flatten@1.0.3, glob@7.2.3, inflight@1.0.6, intl-messageformat-parser@3.6.4, react-router-redux@5.0.0-alpha.9, rimraf@3.0.2, stable@0.1.8
Packages: +2
++
Progress: resolved 1352, reused 1290, downloaded 0, added 2, done

dependencies:
+ axios 1.7.2

# ... some dependencies warning output...

Done in 3.4s
```

以下是方便重现的 github 与 stackblitz
https://github.com/ace-han/umi-res-interceptor-error-demo
https://stackblitz.com/~/github.com/ace-han/umi-res-interceptor-error-demo

## How To Reproduce
点击对应的Button 突发用不同方案进行 request 查看页面的结果, 如下图
**Steps to reproduce the behavior:** 1. 2.
![umi_demo](https://github.com/umijs/umi/assets/1177332/347cc1f8-944b-4274-82e7-5a11ec36d4cc)

![umi_failed](https://github.com/umijs/umi/assets/1177332/d282ba49-886c-4025-81f0-dafe1f16c8ee)

**Expected behavior** 1. 2.
可以得到重试后的结果

![axios_ok](https://github.com/umijs/umi/assets/1177332/c1dad99e-d34e-4f12-a597-de9d8976a021)

## Context

- **Umi Version**: 4.3.1
- **Node Version**: v20.12.1
- **Platform**: MacOS M1 14.3.1

**Comment by fz6m** [comment]
我试了这个最小实例是可用的，请求重放或者做啥异步操作都可以，基于这个改造吧（不要使用 `then` ，仓库里的代码看的头大了）：

```ts
  useEffect(() => {
    const func = async () => {
      const r = await request('/111')
      console.log('r: ', r);
    }
    func()
  }, [])
```

```ts
// src/app.ts

const sleep = (time: number) =>
  new Promise((resolve) => setTimeout(resolve, time));

export const request: RequestConfig = {
  responseInterceptors: [
    [
      (r) => {
        return r;
      },
      async (e) => {
        console.log('e: ', e);

        await sleep(1000);

        const res = await req('/api/v1/queryUserList');

        return res;
      },
    ],
  ],
};

```

**Comment by accaolei** [comment]
@ace-han 你解决了吗？

**Comment by ace-han** [comment]
> @ace-han 你解决了吗？

没有。

根据 @fz6m 的说法， 错误原因应该出现在代码里的嵌套 return Promise(resolve, reject)里， 没有再往这个方向钻下去了

考虑到是 access_token , refresh_token的场景，既然responseInterceptors 后置检查的想法用不了，那就改成用 requestInterceptors 每次前置检查access_token 有没有过期来实现了。

这个方案能用，只是每次请求前都打开了access_token 看有没有过期，多了一层计算

**Comment by Versatileyouth** [comment]
折腾我好久 好的解决方法了

**Comment by Versatileyouth** [comment]
> > 折腾我好久 终于解决了
> 
> 怎么解决的，用的是responseInterceptors 方式解决不？

我这边也是碰到刷新token请求重试后拿不到后端返回的原始数据,包一层data就好了
<img width="558" alt="image" src="https://github.com/user-attachments/assets/0d102718-aaa6-40e6-8a16-bdf01fab6b77">

**Comment by ace-han** [comment]
> > > 折腾我好久 终于解决了
> > 
> > 
> > 怎么解决的，用的是responseInterceptors 方式解决不？
> 
> 我这边也是碰到刷新token请求重试后拿不到后端返回的原始数据,包一层data就好了 <img alt="image" width="558" src="https://private-user-images.githubusercontent.com/167152747/361625141-0d102718-aaa6-40e6-8a16-bdf01fab6b77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDg4MzAsIm5iZiI6MTcyNDc0ODUzMCwicGF0aCI6Ii8xNjcxNTI3NDcvMzYxNjI1MTQxLTBkMTAyNzE4LWFhYTYtNDBlNi04YTE2LWJkZjAxZmFiNmI3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwODQ4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjM0NDk4OWIzMDRjNjUzYWY2NjQzYzAyZjYzNTE1YmUxOTViY2UxZWMzZjhkN2U0NjIzMDQyYWY2NThmY2E4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.apetW7yFrcgtA0TLe-iAeQFVRPa7QtZqt0nSKIA_SYA">

@Versatileyouth 谢谢大神提点

@fz6m 我尝试了 @Versatileyouth 的方法，确实能获得重试后的返回值了，具体改动可以参见这个commit https://github.com/ace-han/umi-res-interceptor-error-demo/commit/de68f558be151dadb1157627d2d1bff81d439b4e


是不是可以说明 umijs 的request responseInterceptors 其实是有问题的，为什么要包多一层 [`{data: r}`](https://github.com/ace-han/umi-res-interceptor-error-demo/blob/de68f558be151dadb1157627d2d1bff81d439b4e/src/utils/umi-request.ts#L96) 呀，没有任何文档有提及哦

https://github.com/ace-han/umi-res-interceptor-error-demo/blob/de68f558be151dadb1157627d2d1bff81d439b4e/src/utils/umi-request.ts#L96

**Comment by Versatileyouth** [comment]
@ace-han 或许是因为这个
<img width="918" alt="image" src="https://github.com/user-attachments/assets/645872af-6402-418e-82ab-3b6bee7c9cf9">
