### ISSUE TITLE
[Bug] umi3.5.15版本开启mfsu时控制台只有警告无报错，但是没有办法打开项目，空白页面

### ISSUE THREAD

**Issue by IsDyh01** [umijs/umi#12548]
## What happens?

"umi": "^3.5.15",
@umijs/preset-ui": "^2.2.9"
"@umijs/plugin-blocks": "^2.2.2"
当开启mfsu时控制台会有如下警告：
[MFSU] require('D:/×××/node_modules/@umijs/plugin-ui-blocks/lib/sdk/flagBabelPlugin/GUmiUIFlag.js') found in D:\×××\src\.umi\umi.ts, which will broken the MFSU prebuild match, please change to esm module import.     
[MFSU] require('D:/×××/node_modules/@umijs/preset-ui/lib/bubble') found in D:\×××\src\.umi\umi.ts, which will broken the MFSU prebuild match, please change to esm module import.
即在src下的临时文件.umi下的umi.ts中出现require().default的用法

## Mini Showcase Repository(REQUIRED)

目前无法复现

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:3.5.15
- **Node Version**:12.22.12
- **Platform**:win10

**Comment by fz6m** [comment]
umi 3 已经不维护了，建议升级到 umi 4 。

umi 3 版本的 mfsu 做的并不完善，不建议开启，如果想用 mfsu 还是升级到 umi 4 吧。

**Comment by IsDyh01** [comment]
感谢回复！

**Comment by IsDyh01** [comment]
您好，可以加一下您好友吗，想咨询您一些问题
