### ISSUE TITLE
[Bug] 热更新后总是会重新载入页面

### ISSUE THREAD

**Issue by tuyangJs** [umijs/umi#12549]
## Mini Showcase Repository(REQUIRED)
根据文档创建完项目 https://ant.design/docs/react/use-with-umi-cn
只要一修改页面内容，它热更新后就会重新载入页面
## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

 https://ant.design/docs/react/use-with-umi-cn
![QQ_1720523532652](https://github.com/umijs/umi/assets/38270397/f611cc49-2d92-43fb-81c8-e22dc06c8462)

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
如果改了路由，就会重新启动应用，自动刷新页面。

如果是普通更改代码，是热更新，如有问题，需要给一个最小复现仓库和操作流程描述。
