### ISSUE TITLE
[Bug] 路由配置导入别名后报错

### ISSUE THREAD

**Issue by jinxiangqiang** [umijs/umi#12554]
## What happens?

{
        path: 'list',
        name: '列表',
        component: () => import('@reco/workOrder'),
        icon: 'smile',
        id: 20240524002001,
        parentId: 20240524002030,
}
报错信息：
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received function component

## Mini Showcase Repository(REQUIRED)

https://stackblitz.com/edit/vitejs-vite-zc88xe?file=.umirc.ts

## Context
希望能通过别名导入其他路径的文件

- **Umi Version**: 4.3.1
- **Node Version**:  v20.15.0
- **Platform**: macOS

**Comment by xierenyuan** [comment]
{
      path: 'list',
      name: '列表',
      component: '@reco/workOrder',
      icon: 'smile',
      id: 20240524002001,
      parentId: 20240524002030,
    }, 配置成字符串就行  默认支持按需加载

**Comment by jinxiangqiang** [comment]
字符串page以外的获取不到

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月10日 21:35 |
| 收件人 | umijs/umi ***@***.***> |
| 抄送人 | 金相强 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [umijs/umi] [Bug] 路由配置导入别名后报错 (Issue #12554) |

{
path: 'list',
name: '列表',
component: ***@***.***/workOrder',
icon: 'smile',
id: 20240524002001,
parentId: 20240524002030,
}, 配置成字符串就行 默认支持按需加载

**Comment by fz6m** [comment]
路由表 `routes` 里的 `component` 这个字段，只能配置字符串，可以是 `./DirName` ，相对路径代表从 `src/pages` 开始找，也就是 `src/pages/DirName/index.tsx` ，写成绝对路径也可以。

如果想用 alias ，只支持使用 `@/` 开头，从 `src` 开始找，比如 `@/pages/xxx`
