### ISSUE TITLE
[Bug] umi max的环境变量疑问，求助

### ISSUE THREAD

**Issue by bxter** [umijs/umi#12556]
我用的umi max最新版，我的工程需要在日常开发环境 和 线上环境有个不同的配置，写法如下：
.umirc.ts 文件中，我需要根据环境加载不同的路径
![image](https://github.com/umijs/umi/assets/59326851/009d09ca-6468-4558-9b4d-78d88d862aee)

现在碰到的问题，
1、在.env 文件中，定义的变量，功能是正常的，.umirc.ts文件能读到这个变量设置上去
![image](https://github.com/umijs/umi/assets/59326851/8e4b18ec-5419-49de-9f76-410c76ce0322)

2、如果我把.env文件的这个变量关掉，我想通过config/config.dev.ts 文件来配置，.umirc.ts 文件读不到
![image](https://github.com/umijs/umi/assets/59326851/284a5a77-478b-4aca-a0fc-07cf1b793ac7)

3、我仔细的看了下环境变量文档的说明
<img width="1312" alt="image" src="https://github.com/umijs/umi/assets/59326851/0063775a-b0c8-4bbe-821d-c8f108c40ef7">

我的理解，怎么样，都会去读config.dev.ts 这个扩展配置文件的吧
我用的命令是 pnpm start, 
![image](https://github.com/umijs/umi/assets/59326851/09db6a9d-07ac-4a6f-8d61-d50253fc3805)

不太明白，这里到底是什么问题造成的，十分感谢你的帮助

**Comment by xierenyuan** [comment]
define 配置如果需要 通过 process.env.xx 获取的话 需要配置为 define: { 'process.env.REACT_APP_ENRY_BASE': 'xxx' } 参考 https://umijs.org/docs/api/config#define  现在的配置方式可以通过 REACT_APP_ENRY_BASE 访问

**Comment by bxter** [comment]
![image](https://github.com/umijs/umi/assets/59326851/a95bdd4b-6de4-4d28-b8da-38151f918484)

如果直接用REACT_APP_ENRY_BASE ，直接编译时候，就报错了，不知道怎么能过去，感谢帮助

**Comment by bxter** [comment]
![image](https://github.com/umijs/umi/assets/59326851/b9d5118c-6dab-4bde-af63-b83b316c71f4)
另外这种写法，我也试验了，也是不能
报错界面如下：
<img width="850" alt="image" src="https://github.com/umijs/umi/assets/59326851/d3d58804-d3f0-458a-a6b0-13a3d7dd654a">

**Comment by xierenyuan** [comment]
> ![image](https://private-user-images.githubusercontent.com/59326851/347407925-a95bdd4b-6de4-4d28-b8da-38151f918484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTg2MzQsIm5iZiI6MTcyMDYxODMzNCwicGF0aCI6Ii81OTMyNjg1MS8zNDc0MDc5MjUtYTk1YmRkNGItNmRlNC00ZDI4LWI4ZGEtMzgxNTFmOTE4NDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEzMzIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MDUxYmMyNTE4MTA2YzlmNmY0N2EwYzQ2OGU1YjhmMzgyYTVlMDA4Y2E3NTgwZTAxNTBkY2UyNjkyYTJiMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rDUufpIzFYV7c6T6b09myWYAPgSsGUss7LXRd98kzco)
> 
> 如果直接用REACT_APP_ENRY_BASE ，直接编译时候，就报错了，不知道怎么能过去，感谢帮助

这不需要改你代码改就行

**Comment by bxter** [comment]
没懂？
// config.dev.ts
```
export default defineConfig({
  define: {
    REACT_APP_ENTRY_IOT: '//localhost:8005',
  },
});
```

// .umirc.ts
```
{
  master: {
    apps: [
      {
        name: 'base',
        entry: REACT_APP_ENTRY_BASE,
        credentials: true,
      },
    ],
  }
```
我应该怎么写呢， 感谢

**Comment by fz6m** [comment]
上面讨论的比较乱。

在环境变量配置文件里定义的变量，比如 `.env` 里写的，是属于 nodejs 环境的变量，这些变量都会被加载到 `.umirc.ts` 里（这个配置文件也在 nodejs 环境下运行），可以在 umi 配置文件里通过 `process.env.XXX` 取到。

但是你的项目本身是个 browser 环境，需要把 nodejs 的环境变量按需要注入到 browser 的项目里才能用，就使用 [`define`](https://umijs.org/docs/api/config#define) 这个选项才能注入。

在配置 `define` 的时候，配成啥 key ，就必须在项目里用一样的 key ，如果配成 `process.env.XXX` 的话，就必须用 `process.env.XXX` ，配成 `XXX` ，项目里就必须用 `XXX` ，但是用 `XXX` 这种的话，是没有类型提示的（因为他就是一个全局变量了，在 TS 里必须声明这个陌生的全局变量才不会类型报错），配置类型提示是比较麻烦的，配置方法详见 define 的 [文档](https://umijs.org/docs/api/config#define) 。

所以 `define` 里一般我们都配 `process.env.XXX` 。

也就是说你的变量必须要先在 nodejs 环境里，才能配置 `define` 到项目，除了 `.env` 可以自动注入到 nodejs 外，还可以在启动时命令行上加环境变量，就可以自动注入到 nodejs 环境。

综上，你会发现一个变量从 nodejs 到项目，要先写到 `.env` 里，再写到 `.umirc.ts` 里，比较麻烦，所以大多数脚手架，比如 CRA / vue-cli 等，都会约定一个前缀，符合这个前缀的 nodejs 环境变量会自动注入到 browser 项目里，省去配置 `define` 了，在 umi 里就是 `UMI_APP_` 这个前缀，只要在 `.env` 里写这个前缀的变量，默认就可以在项目里通过 `process.env.UMI_APP_XXX` 获取到。

但 `.env` 环境变量其实是有一定限制的，目前只支持 `.env` ，不适合更多环境了，所以 开发时、生产时 ，超过这两种情况，还是直接在命令行上标注不同的环境变量吧，用不同命令构建即可。

至于 `UMI_ENV` ，它是一个读取特定环境配置的设定，如果有 `UMI_ENV` ，就会额外读取一些 umi 的配置文件（优先级和列表正文中你也看到了），从而实现一定的不同环境有不同配置（比如不同的 `define`），需要注意的是 `UMI_ENV` 不能读取 `.env.${UMI_ENV}` 。

上面是这些配置的详细说明。

如果你想根据不同环境有不同 url ，还是写几个 `UMI_ENV` 的启动命令，然后 `.umirc.prod.${UMI_ENV}.ts` 的优先级就更高，从而配不同的 `define` 即可，或者就直接在 `.umirc.ts` 里读 `process.env.UMI_ENV` 然后注入不同的 `define` 吧，省去搞好几个配置文件了。

**Comment by bxter** [comment]
十分感谢你的帮助， 我感觉我都懂了，但是试验下来看起来好像并没有
```
如果你想根据不同环境有不同 url ，还是写几个 UMI_ENV 的启动命令，然后 .umirc.prod.${UMI_ENV}.ts 的优先级就更高，从而配不同的 define 即可，或者就直接在 .umirc.ts 里读 process.env.UMI_ENV 然后注入不同的 define 吧，省去搞好几个配置文件了。
```
我想喜爱用UMI_ENV命令方案，
我的操作如下:
1、引入cross-env ， 修改启动命令
![image](https://github.com/umijs/umi/assets/59326851/934d907d-c683-453a-a027-5eb0e5d5fea5)
![image](https://github.com/umijs/umi/assets/59326851/c3c13489-d674-4c9c-a3c8-25707bb0e219)

2、定义config/config.xx.ts 配置文件，
我复制了3个 ，里面内容都是下图所示
![image](https://github.com/umijs/umi/assets/59326851/3ca07285-1c2e-48f8-b8ae-7df0fddd3a61)

3、.umirc.ts 文件使用
![image](https://github.com/umijs/umi/assets/59326851/17f9c015-6c59-4e69-94d9-fb13c553fcff)

===>>
但是实际山启动后，页面的反馈是还是没有获取到值
<img width="1045" alt="image" src="https://github.com/umijs/umi/assets/59326851/9032987d-a57f-4ac6-a57c-cc9c4a04d7bb">

我很有迷糊了，我没看出来我还缺少那个步骤

**Comment by wowsummer** [comment]
遇到同样的问题，官方直接给个示例不一目了然么！！！！

**Comment by A-birdFlyHigner** [comment]
<img width="931" height="427" alt="Image" src="https://github.com/user-attachments/assets/79679018-5a87-4708-8596-e10111e5efd8" />
