### ISSUE TITLE
[Bug] 用户把/user/login给挂收藏夹了，导致每次发完版，用户从收藏夹打开，就报错。

### ISSUE THREAD

**Issue by deerLoves** [umijs/umi#12558]
用户把/user/login给挂收藏夹了，导致每次发完版，用户从收藏夹打开，就报错。
umi.[hash].js 带了hash值，每次发完版之后，用户从收藏夹打开的时候，找不到上一个hash文件，页面直接报错，用户得自己手动刷新一次才行。请问这个怎么处理呢？

**Comment by sorrycc** [comment]
没理解这个问题，带 hash 的是 js，又不是 html。html 访问收藏时带 hash 的 js，下次访问时应该还是这个。除非你每次发布把之前带 hash 的 js 文件在线上删除了。。这种情况下就不要用 hash。
