### ISSUE TITLE
[Bug] 4.3.1以上热更新失效

### ISSUE THREAD

**Issue by zcSkr** [umijs/umi#12565]
## What happens?
umijs/max 4.3.1以上版本 热更新失效。

## Mini Showcase Repository(REQUIRED)

https://github.com/zcSkr/umi_fastRefresh.git

## How To Reproduce

Step1： create-umi myapp
Step2:  运行后修改页面上的文字，明显看到网页Reload了

## Context

- **Umi Version**: 4.3.5
- **Node Version**: 20.12.2
- **Platform**: macOS

**Comment by sorrycc** [comment]
Try umi@4.3.6, we have reverted related PRs. Checkout  https://github.com/umijs/umi/releases/tag/v4.3.6 for details.
