### ISSUE TITLE
[Feature Request] 可否支持下 在 build 阶段屏蔽某些目录下的导入检查

### ISSUE THREAD

**Issue by prui** [umijs/umi#12571]
## Background

app.ts
```ts
// @ts-nocheck
import {ABC, BCD} from './.test'
console.log(BCD, ABC);
```
./.test
```ts
export const BCD = {}
```

我的理解 ABC 这不合理导入报错是正常的，只是基于我们项目特殊性，所以需要屏蔽.test 这个文件下的导入报错检查，可以理解为需要 // @ts-nocheck 这个跳过检查的注释生效

**Comment by day-xue** [comment]
这个和umi无关吧 可以修改tsconfig.json的exclude试试
