### ISSUE TITLE
[Bug] base不为空时使用`hash router`导致`react-router`报错且仍引用根目录下的资源文件

### ISSUE THREAD

**Issue by Redish101** [umijs/umi#12577]
## What happens?

base不为空时使用`hash router`导致`react-router`报错:
```
<Router basename="/dashboard"> is not able to match the URL "/" because it does not start with the basename, so the <Router> won't render anything.
```
且生成的html中仍然引用根目录下的资源文件而非`/base/umi.js`等。

## Mini Showcase Repository(REQUIRED)
[redish101/umi-hash-route-demo](https://github.com/Redish101/umi-hash-route-demo)

## Context

- **Umi Version**: ^4.2.10
- **Node Version**: v20.15.0
- **Platform**: macos

**Comment by stormslowly** [comment]
从你的提供的信息看，应该是非根目录部署的场景，也许你需要配置 [publicPath](https://umijs.org/docs/api/config#publicpath) 来支持非根路径的资源访问
