### ISSUE TITLE
umi-max qiankun 接入部署环境中，刷新路由直接进入子应用部署项目中

### ISSUE THREAD

**Issue by xileliu** [umijs/umi#12578]
主应用umi max 配置：
`apps: [
		{
			name: 'app2',
			entry: '/tenant/org1101/nntl/client/poss/hto1/section/',
			activeRule: '/tenant/org1101/nntl/client/poss/hto1/section',
		},
	],`

主应用base: /tenant/org1101/nntl/client/poss/hto1/
子应用：history: createWebHistory(“/tenant/org1101/nntl/client/poss/hto1/section/”),

主子应用的nginx配置：
主：
`
location ^~ /tenant/org1101/nntl/client/poss/hto1/ {
     try_files $uri $uri/ /tenant/org1101/plat/web/hto1/index.html;
}
location /tenant/org1101/plat/web/hto1/ {
    proxy_pass http://frontend.dev.onmc.top;
}`
子：
`location  ^~ /tenant/org1101/nntl/client/poss/hto1/section/ {
	try_files $uri $uri/ /tenant/org1101/poss/web/section/index.html;
}
location /tenant/org1101/poss/web/section/ {
	proxy_pass http://frontend.dev.onmc.top;
}`

问题描述：
当我去访问：https://dev.onmc.top/tenant/org1101/nntl/client/poss/hto1/section/orgm/deptManagement;手动刷新页面的时候直接进入到子应用中。

根绝官方qiankun 提供的部署文档中说明了我目前的情况描述：
![image](https://github.com/user-attachments/assets/d5c9a035-f330-4909-b771-7a6b5c5341a5)
我开始设置如上面的配置activeRule: '/tenant/org1101/nntl/client/poss/hto1/section', 但是看了umi Max qiankun 似乎没有这个参数，
想看一下官方这中应该怎么设置

**Comment by stormslowly** [comment]
这个应该是一个部署配置的问题，从你提供的 nginx 配置看，访问直接命中了子应用的路由，所以直接渲染了子应用；
或许你应该只需要配置一个主应用的 spa 的 nginx 配置，子应用只提供静态文件服务即可。

**Comment by xileliu** [comment]
> 这个应该是一个部署配置的问题，从你提供的 nginx 配置看，访问直接命中了子应用的路由，所以直接渲染了子应用； 或许你应该只需要配置一个主应用的 spa 的 nginx 配置，子应用只提供静态文件服务即可。

是的，目前是子应用配置的nginx调整了一下，基本就是给定local /xxxx/childrenA，然后子应用的history base 直接写 和 主应用nginx 的path 一致，
