### ISSUE TITLE
[umi@2.1.2] 不存在的资源，访问不报404，反而报 200 ok 

### ISSUE THREAD

**Issue by amily4555** [umijs/umi#1257]
![image](https://user-images.githubusercontent.com/2802841/46997776-2b13aa80-d153-11e8-9404-3ad7f2a392d3.png)

![image](https://user-images.githubusercontent.com/2802841/46997810-4e3e5a00-d153-11e8-9a3d-2b3972f39aa0.png)

![image](https://user-images.githubusercontent.com/2802841/46997821-58605880-d153-11e8-8247-71ec36596192.png)

**Comment by sorrycc** [comment]
这在目前来说是符合预期的，所有不存在的地址都会 fallback 到 index.html 。

**Comment by amily4555** [comment]
但是这样跟生产环境相悖，不好进行调试 测试··
