### ISSUE TITLE
执行umi ui，报错如下：Invalid command ui, it's not registered.

### ISSUE THREAD

**Issue by waxeia** [umijs/umi#12582]
我已经手动安装了依赖yarn add @umijs/preset-ui -D，但是重启项目无法显示umi ui的小图标。于是手动启动，执行指令：umi ui，报错如下：
![image](https://github.com/user-attachments/assets/6b74997c-a4d6-4ebc-874d-6e1ddbf4fcdb)

**Comment by stormslowly** [comment]
只有 umi@3  `ui`  umi@4 无此命令
