### ISSUE TITLE
[Bug] umi4 使用access+model+initial-state在运行时报错

### ISSUE THREAD

**Issue by Nice-PLQ** [umijs/umi#12588]
## What happens?
使用 Umi4 + @umijs/plugins。

报错信息：
<img width="1492" alt="image" src="https://github.com/user-attachments/assets/afecf6fa-8da2-44ab-9000-b235b83b5221">

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

config.ts配置：
```
  plugins: [
    '@umijs/plugins/dist/tailwindcss',
    '@umijs/plugins/dist/request',
    '@umijs/plugins/dist/initial-state',
    '@umijs/plugins/dist/model',
    '@umijs/plugins/dist/access',
  ],
  request: {},
  access: {},
  model: {},
  initialState: {},
```

## Context

- **Umi Version**: 4.3.6
- **Node Version**: 18
- **Platform**: macOS

**Comment by Wu-kung** [comment]
可尝试配合 [layout](https://umijs.org/docs/max/layout-menu) 插件你可以很简单的实现针对某些页面的权限控制。

```ts
plugins: [
    '@umijs/plugins/dist/layout',
    '@umijs/plugins/dist/initial-state',
    '@umijs/plugins/dist/model',
    '@umijs/plugins/dist/access',
],
layout: {},
access: {},
model: {},
initialState: {},
```

**Comment by Nice-PLQ** [comment]
已解决，是因为我创建了`src/access.ts`，但是没有默认导出一个方法导致的，增加默认导出就可以了
