### ISSUE TITLE
[Bug] mac yarn global add umi $ umi -v 报错

### ISSUE THREAD

**Issue by panshuangqing** [umijs/umi#12587]
mac 基本安装和查看版本报错

<img width="568" alt="image" src="https://github.com/user-attachments/assets/6a19f12d-4150-4d3c-9b4e-ebe82a08dc2b">

<img width="573" alt="image" src="https://github.com/user-attachments/assets/62cfe1ed-ac13-4556-a847-77c0d52dab1a">

fatal - Error: Invalid command ui, it's not registered.
    at Service.run (/opt/homebrew/lib/node_modules/umi/node_modules/@umijs/core/dist/service/service.js:264:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Service.run2 (/opt/homebrew/lib/node_modules/umi/dist/service/service.js:65:12)
    at async Object.run (/opt/homebrew/lib/node_modules/umi/dist/cli/cli.js:56:7)
fatal - A complete log of this run can be found in:
fatal - /Users/houyanan/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by Jinbao1001** [comment]
umi版本等信息提供一下. 最好有个最小复现.
