### ISSUE TITLE
[Bug] umi@1.2.6 umi build 无响应

### ISSUE THREAD

**Issue by tshanchuan** [umijs/umi#12592]
## What happens?
六年前老项目被人刨坟要卖掉。发现无法打包。
现在问题是： umi dev 本地可以正常运行。umi build 一直等待，没有报错也不输出日志。
项目过大业务繁多，不想升级到其他版本。看看各位同学有没有遇到过。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
[admin.zip](https://github.com/user-attachments/files/16369702/admin.zip)
业务代码已上传

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

![image](https://github.com/user-attachments/assets/017d89de-ee8f-44e8-82f1-0d0322780237)
![image](https://github.com/user-attachments/assets/691a5cb0-99f9-4ded-b8f3-33ffdb35e3b5)
``` json
{
  "private": true,
  "scripts": {
    "start": "umi dev",
    "build": "umi build"
  },
  "dependencies": {
    "@babel/polyfill": "^7.0.0-beta.44",
    "ant-design-pro": "^1.3.0",
    "babel-eslint": "^8.2.2",
    "babel-plugin-emotion": "^9.1.0",
    "babel-plugin-import": "^1.7.0",
    "babel-polyfill": "^6.26.0",
    "dva": "^2.1.0",
    "dva-loading": "^1.0.4",
    "image-compressor.js": "^1.1.3",
    "immutability-helper": "^2.7.0",
    "js-cookie": "^2.2.0",
    "maptalks": "0.39.8",
    "moment": "^2.20.1",
    "npm": "^5.8.0",
    "npm-check": "^5.7.1",
    "numeral": "^2.0.6",
    "q": "^1.5.1",
    "qs": "^6.5.1",
    "query-parse": "^2.0.0",
    "rc-form": "^2.2.0",
    "react-bmap": "^1.0.69",
    "react-cropper": "^1.0.1",
    "react-infinite-scroller": "^1.1.3",
    "react-transition-group": "^2.3.1",
    "react-wx-images-viewer": "^1.0.6",
    "socket.io-client": "^2.1.0",
    "to": "^0.2.9",
    "umi-plugin-dva": "^0.3.0",
    "umi-plugin-polyfill": "^0.1.1",
    "update": "^0.7.4"
  },
  "devDependencies": {
    "eslint": "^4.14.0",
    "eslint-config-umi": "^0.1.1",
    "eslint-plugin-flowtype": "^2.34.1",
    "eslint-plugin-import": "^2.6.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.7.0",
    "husky": "^0.12.0",
    "umi-plugin-es5-imcompatible-versions": "^0.1.0",
    "umi-plugin-routes": "^0.1.2"
  },
  "proxy": "https://rmc-admin.qiansun.online/api/"
}

```
## Context

- **Umi Version**:1.2.6
- **Node Version**: 10.24.1
- **Platform**: Win 11

**Comment by tshanchuan** [comment]
![image](https://github.com/user-attachments/assets/50187a27-47d7-40ee-b580-244dade5e6ed)

**Comment by sorrycc** [comment]
需要复现步骤，没复现看不了。

**Comment by tshanchuan** [comment]
[admin.zip](https://github.com/user-attachments/files/16369699/admin.zip)

**Comment by tshanchuan** [comment]
> 需要复现步骤，没复现看不了。

Windows下 build无响应，有网友在Mac下 可以build

**Comment by tshanchuan** [comment]
解决了，umi-plugin-dva 换成 0.9.1版本
npm install umi-plugin-dva@0.9.1 --save-dev
