### ISSUE TITLE
targets的兼容性问题

### ISSUE THREAD

**Issue by hehongwei44** [umijs/umi#1259]
设置targets这个属性,链接为：https://umijs.org/zh/config/#targets，当设置为9或者10时，用IE11的仿真器设置对应的文档模式为9或者10时，浏览器报错。

**Comment by haifn** [comment]
我看到文档介绍有写，一键兼容ie9，是基于umi-plugin-polyfill ； 
还有包括 umi2.1.x 配置里的：targets:{ie:11}；
两种配置均无法实现ie（11）兼容

还有ant Des Pro 也是无法在ie环境下兼容

@sorrycc

**Comment by hehongwei44** [comment]
> dom 层或其他的并没有包含在内
那怎样设置能兼容IE9呢

**Comment by sorrycc** [comment]
antd-pro 在 ie11 下我测过兼容性的。

**Comment by sorrycc** [comment]
@hehongwei44 看报错，少什么补丁加什么。

**Comment by xiaohuoni** [comment]
@hehongwei44 pro应该都无法兼容ie9，flex布局，好想不兼容ie9.
