### ISSUE TITLE
[Bug] getLocale 获取的语言字符串有错误

### ISSUE THREAD

**Issue by zcSkr** [umijs/umi#12595]
## What happens?
getLocale() 预期是“zh-CN”。实际是“zh”
![image](https://github.com/user-attachments/assets/51a228e5-ec9a-48c3-897d-eb101e4c5399)

## Mini Showcase Repository(REQUIRED)

> https://github.com/zcSkr/umi_getLocale.git

## How To Reproduce

**Steps to reproduce the behavior:** 
1）create-umi demo
2）pnpm start
3）console.log(getLocale())

**Expected behavior** 
zh-CN

## Context

- **Umi Version**: 4.3.9
- **Node Version**: 20.12.2
- **Platform**: macOS

**Comment by Wu-kung** [comment]
未复现。（Umi v4.3.10）
![image](https://github.com/user-attachments/assets/df83a39f-3ac0-4af5-a640-dd41bbf6f653)

**Comment by zcSkr** [comment]
> 未复现。（Umi v4.3.10） ![image](https://private-user-images.githubusercontent.com/22555105/352025588-df83a39f-3ac0-4af5-a640-dd41bbf6f653.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTcyMDQsIm5iZiI6MTcyMTg5NjkwNCwicGF0aCI6Ii8yMjU1NTEwNS8zNTIwMjU1ODgtZGY4M2EzOWYtM2FjMC00YWY1LWE2NDAtZGQ0MWJiZjZmNjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA4NDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MDJmMGE3ZWYyYTZmYWI2OGVlOTJkZTJlNzQwYmQzNjQ1MTk4MGIyMGY4OTVmNGRjN2VlODg4ODQ2YzFkM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i1SAJVOaMOddU9g6VOdVgmqmMhhMYKracX7dLl6fkkk)

![image](https://github.com/user-attachments/assets/a149e5a8-93a7-49d4-85ed-4b97efe2f9ea)
Safari 未复现，Chrome复现
![image](https://github.com/user-attachments/assets/0f4564f5-5e42-4cf7-a0ca-720c86dc2f5a)

**Comment by zcSkr** [comment]
同事mac Mini一样的浏览器版本没复现，正在排查电脑原因

**Comment by zcSkr** [comment]
已找到原因
![image](https://github.com/user-attachments/assets/9c50c7fe-7228-410d-bf04-91dea9a468b3)
