### ISSUE TITLE
When will SSR open to version 4.3.10? How can I use other methods instead?

### ISSUE THREAD

**Issue by SailorArthur** [umijs/umi#12605]
I'm using version 4.3.10 and am experiencing SEO issues that need to be handled via SSR! But don't know of a solution to replace it at the moment. Any help would be appreciated, thanks!

**Comment by Jinbao1001** [comment]
add config ->  ssr: {}

**Comment by SailorArthur** [comment]
> add config ssr: {}.
> 
> if the script run dev working well.
> 
> exportStatic: {} may be necessary when using build script.

Can you provide a link to the relevant ssr api documentation? Thank you very much!

**Comment by Jinbao1001** [comment]
the official documentation of ssr takes some time to produce, and we still have some internal plug-ins that have not been fully adapted. If you have any questions, you can directly consult here~
