### ISSUE TITLE
关于配置合并的疑问

### ISSUE THREAD

**Issue by ACERY1** [umijs/umi#1260]
场景：目录下有两个配置文件（目录下既有.umirc.js和.umirc.local.js的情况），期望配置可以合并。

效果：配置没有合并，如plugin字段只是选择了两个配置文件中的其中一个plugin里的属性。

![image](https://user-images.githubusercontent.com/19555547/47001926-34eedb00-d15e-11e8-961c-9e2de2b5face.png)

源码中的这一段代码中的 extend 应该是个深克隆，其中包括了通过“modifyDefaultConfig”注册的插件和 .umirc.js , congfig/config.js , 以及正则匹配匹配到的文件。

理论上应该是合并配置。

但是效果看起来却是替换字段，是bug吗？

测试用例如图：

![image](https://user-images.githubusercontent.com/19555547/47002769-6f597780-d160-11e8-84f5-937668339457.png)

**Comment by okoala** [comment]
@ACERY1  目前配置合并走的是和 egg 配置合并一致的逻辑，数组是覆盖的~ https://eggjs.app/zh-cn/basics/config.html#%E5%90%88%E5%B9%B6%E8%A7%84%E5%88%99 
这样比较好管理，不然数组一层层下去，配置就不好控制。

**Comment by ACERY1** [comment]
理解了，谢谢~
我close掉issue
