### ISSUE TITLE
[Feature Request] 能支持@linaria/react吗，项目用了@linaria/react，但是添加linaria对应的webpack loader和babel preset后，编译报错了

### ISSUE THREAD

**Issue by objHua** [umijs/umi#12609]
## Background
"@linaria/react": "^6.2.1",
"@wyw-in-js/babel-preset": "^0.5.4",
"@wyw-in-js/webpack-loader": "^0.5.4",
"umi": "~4.0.57",

## Proposal

按linaria文档在.umirc extraBabelPresets 和 chainWebpack添加了对应的preset和webpack loader
`	extraBabelPresets: ['@wyw-in-js'],
	chainWebpack: (config) => {
		config.module
			.rule('@wyw')
			.test(/\.ts$/)
			.use('@wyw-webpack')
			.loader('@wyw-in-js/webpack-loader');
	},`
运行后很多ts代码报语法错误

## Additional context
![image](https://github.com/user-attachments/assets/5afce8b8-9ed1-4af0-a0d7-09d14e3f06e3)

**Comment by PeachScript** [comment]
看报错和 Umi 框架本身无关，是 @linaria/react 的 loader 不支持 TypeScript 导致的，需要看下 @linaria/react 官方的文档指南，如何支持编译 TypeScript 文件

**Comment by objHua** [comment]
> 看报错和 Umi 框架本身无关，是 @linaria/react 的 loader 不支持 TypeScript 导致的，需要看下 @linaria/react 官方的文档指南，如何支持编译 TypeScript 文件

这个我看了下，确实需要额外添加ts-loader，但是umi已经内置了ts相关插件，搞不明白为啥在添加了@linaria/react的webpack-loader后仍然报错，另外需要说明的是，添加@linaria/react的babel preset也是同样报错，不同的是@linaria/react的babel preset是在extraBabelPresets配置的，感觉和loader和babel执行顺序有关
