### ISSUE TITLE
使用umi-v4.1.1出现css缓存

### ISSUE THREAD

**Issue by yy-xiaoxin** [umijs/umi#12615]
使用 :global 对antd的已有样式进行重写，重写后发现样式不符合本意，就删除了这份样式，但后续发现我删除的这份样式仍然生效，并且还有具体的文件位置（mf-dep____vendor...），而且我把.umi文件删了重新start，还是如此！
最后发现还得删除node_modules里面的.cache文件，我觉得这不是又变复杂了吗？以前是.umi删了就可以，现在又来一个.cache，为了热更新速度往依赖包加缓存？这是不是有点治标不治本了？

**Comment by y779102260** [comment]
没人解决这个问题？

**Comment by y779102260** [comment]
关闭mfsu能解决：mfsu: false
