### ISSUE TITLE
umi css重复打包的问题

### ISSUE THREAD

**Issue by 750973092** [umijs/umi#1261]
umi在pages目录下引入多个地方引入同一个scss文件会重复打包，该怎么解决呢

**Comment by sorrycc** [comment]
给个可复现的例子，详细描述下问题吧。

**Comment by 750973092** [comment]
我是一个组件对应一个scss的，但我还有一个公共的scss文件，我封装了常用的class类，
然后可以每个scss都可以引用这个封装的SCSS文件
但问题就是每个文件引入公共的文件会重复打包，但如果不引入就@extend报找不到这个类

**Comment by sorrycc** [comment]
打包出来的结果有很多重复的样式定义吗？

**Comment by 750973092** [comment]
是的

**Comment by 750973092** [comment]
每引入多少次就重复打包多少次

**Comment by sorrycc** [comment]
https://github.com/webpack-contrib/sass-loader/issues/145
参考看下有没有解决方案，这是 sass-loader 和 sass 的问题了。

**Comment by youxfans** [comment]
// common.less
body {border: 10px}

//a.less
@import ''common.less'
//b.less 
@import ''common.less'
//c.less 
@import ''common.less'

打包过后

style.css
body {border: 10px}
body {border: 10px}
body {border: 10px}
