### ISSUE TITLE
Ant Design Pro 模板运行后控制台报错

### ISSUE THREAD

**Issue by yxplus1116** [umijs/umi#12624]
### Discussed in https://github.com/umijs/umi/discussions/12623

<div type='discussions-op-text'>

<sup>Originally posted by **yxplus1116** August  7, 2024</sup>
findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference
莫非是 react 版本问题? </div>

**Comment by PeachScript** [comment]
是 warning？

**Comment by yxplus1116** [comment]
> 是 warning？

不是warning.
而是 error
![image](https://github.com/user-attachments/assets/a76fdabe-e14c-4cb5-9a3d-30c62fe21371)

**Comment by PeachScript** [comment]
看 message 是 warning，只是 react 以 error 形式打印了 message，应该不影响实际运行

这个问题可以反馈到 ant-design-pro 项目里，看上去和 pro-components 的实现有关系，Umi 这里的 issue 就先关闭了

**Comment by yzkkunshao** [comment]
不用protable就行，table那个页面有
