### ISSUE TITLE
[Feature Request] patchClientRoutes 动态 路由 

### ISSUE THREAD

**Issue by Arima-s** [umijs/umi#12627]
按照官方的文档，参照routes数据结构，动态添加的路由，渲染不出指定页面
![20240807-172051](https://github.com/user-attachments/assets/b0aea1f0-fe24-41d7-ba81-8591e488e3fa)
![20240807-173214](https://github.com/user-attachments/assets/1fb23d8d-49ea-422c-83c5-f66eae9ea6b8)
😂 该怎么搞啊

背景：
1、侧边栏菜单，是主应用渲染的，目前写死在主应用，想改造成 接口下发。
2、尝试在patchClientRoutes内改造routes，按照部分issues内的示例方法，行不通。 主应用 "@umijs/max": "4.3.10"

**Comment by Arima-s** [comment]
好使的...好使了

**Comment by yangqi0519400** [comment]
> 好使的...好使了

请问下是参考的哪条issue呢，或者参考下你的写法，我这边也没渲染出来
