### ISSUE TITLE
紧急 umi4 使用 qiankun 不能正确加载问题

### ISSUE THREAD

**Issue by xiaoshengwpp** [umijs/umi#12628]
使用 umi4 主应用和子应用 版本"@umijs/max": "^4.3.11"
主应用和子应用都是相同的版本
需求想要在主应用 菜单 加载子应用中的某个路由页面
主应用 config 配置
`
export default defineConfig({
  qiankun: {
    master: {
      apps: [
        {
          name: 'app1',  
          entry: '//localhost:9999',
        },
      ],
    },
  },
...
})
`
主应用路由配置
`export default [
   ...,
    {
        name:'子应用日志页面',
        path: '/app1/logs',
        microApp: 'app1',
     }
]`

子应用配置
`export default defineConfig({
  qiankun: {
    slave: {},
    
  },})`
子应用路由
`{
    path: '/logs',
    name: '操作日志',
    component: './List',
    //layout: false,
  },`

配置完成 主应用 效果：
<img width="1495" alt="image" src="https://github.com/user-attachments/assets/c30af553-62c9-40f6-be8b-5f53cf7a794b">
点击子应用日志页面后 不符合预期效果 
再次点击概览页面 还会出现 错位情况
<img width="682" alt="image" src="https://github.com/user-attachments/assets/4cee1631-a327-461e-b6a5-7c51780e1650">
要刷新后才正常
这个要怎么解决

**Comment by xiaohuoni** [comment]
太潦草了，看不出来问题，给个demo吧
或者你先看下 https://github.com/umijs/umi/tree/master/examples/qiankun-master

**Comment by xiaoshengwpp** [comment]
文档写的用法不对 要去掉子应用前缀才行
