### ISSUE TITLE
router.push时url可以不展示参数吗？

### ISSUE THREAD

**Issue by zhaokera** [umijs/umi#1262]
router.push({
              pathname: 'home/CallBack',
              query: {
                aaa: 'bbb',
                callBack: () => this._callBack(),
              }
})
比如传参数过去的时候
浏览器里面url的地址是：http://localhost:8000/home/CallBack?aaa=bbb&callBack=str%20%3D%3E%20this._callBack%28str%29
能不能传参数的时候，url不变化？

**Comment by sorrycc** [comment]
用法不对。query 会被转换为字符串，不能放函数的。
