### ISSUE TITLE
[Bug] @umijs/max不知道从何处编译得来的产物： preload_helper.[hash].js

### ISSUE THREAD

**Issue by pomelo-chuan** [umijs/umi#12637]
## What happens?

@umijs/max@4.3.12 打包得到这个产物：preload_helper.[hash].js，但是在控制台输出并没有这个产物

## Mini Showcase Repository(REQUIRED)

最小复现demo： https://github.com/pomelo-chuan/umijs-test

## How To Reproduce

1. 使用umi脚手架生成 `@umijs/max` 空项目，使用在umirc里添加了  `qiankun: { slave: {} }`
2. 执行 `npm run build`
3. 控制台输出，没有 `preload_helper.[hash].js` 这个产物

```shell
info  - File sizes after gzip:

  189.96 kB  dist/609.99b4a8f6.async.js
  155.31 kB  dist/umi.081dc383.js
  132.36 kB  dist/458.961685f1.async.js
  8.52 kB    dist/879.b520c329.async.js
  3.79 kB    dist/p__wechat-auth.eaa67f85.async.js
  1.21 kB    dist/umi.7422b84d.css
  654 B      dist/layouts__index.95a7eb29.async.js
  445 B      dist/p__index.acdf69f4.async.js
  132 B      dist/layouts__index.59724945.chunk.css
```

4. 查看 `dist` 文件夹，有 `preload_helper.[hash].js` 这个产物

```shell
├── 229.eb378a30.async.js
├── 505.5304b341.async.js
├── 692.73868467.async.js
├── 715.6705d0d3.async.js
├── 810.e8994860.async.js
├── 83.991580a6.async.js
├── 909.31a89c68.async.js
├── 937.437fd6de.async.js
├── index.html
├── layouts__index.5200e1e7.async.js
├── layouts__index.b6683f1c.chunk.css
├── p__Access__index.7c58e1b3.async.js
├── p__Home__index.3717d6e1.async.js
├── p__Home__index.f96fbea3.chunk.css
├── preload_helper.0956a814.js
├── p__Table__index.96c9d6f7.async.js
├── t__plugin-layout__Layout.5012e1ab.chunk.css
├── t__plugin-layout__Layout.c2826d74.async.js
├── umi.277b1e59.css
└── umi.e86d6cdb.js
```

5. 查看 `index.html`，有 `preload_helper.[hash].js` 这个资源

```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://demo.com/umi.277b1e59.css">
<script>window.publicPath = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__ || "https://demo.com/";</script>
<script src="https://demo.com/preload_helper.0956a814.js"></script>
</head>
<body>
<div id="root"></div>
<script src="https://demo.com/umi.e86d6cdb.js" entry></script>
</body>
</html>
```

## Context

- **Umi Version**:  4.3.12
- **Node Version**: 20
- **Platform**: x86 ubuntu 24 lts

## 补充信息

[类似被关闭工单](https://github.com/umijs/umi/issues/12604)

**Comment by stormslowly** [comment]
ref to this feature: packages/preset-umi/src/features/routePreloadOnLoad/routePreloadOnLoad.ts

**Comment by sorrycc** [comment]
preload_helper.x.js 是 feature，这个文件会用到的。如果你不需要，可以试试通过 `routePreloadOnLoad: false` 配置关闭此功能。

**Comment by gt-chenzheqi** [comment]
`routePreloadOnLoad: false` 这个配置没有生效。
我们公司内部使用了一个 webpack 插件：在构建结束后，将 output 的文件上传到 oss 中；因为这个**额外**生成的文件，脱离了 webpack 的构建流程，导致插件检测不到，也就不会上传到 oss，最终导致我们通过修改 publichPath 访问的`preload_helper`并不存在，因为 oss 上并没有这个文件。

**Comment by hebingqian420** [comment]
> `routePreloadOnLoad: false` 这个配置没有生效。 我们公司内部使用了一个 webpack 插件：在构建结束后，将 output 的文件上传到 oss 中；因为这个**额外**生成的文件，脱离了 webpack 的构建流程，导致插件检测不到，也就不会上传到 oss，最终导致我们通过修改 publichPath 访问的`preload_helper`并不存在，因为 oss 上并没有这个文件。

老哥，我们也是类似场景，我们开了runtimePublicPath，请问你咋解决的呢？

**Comment by xiaoxuehai** [comment]
这个问题解决了吗？

**Comment by zhangkaisi** [comment]
怎么解决的呢？

**Comment by dongfg** [comment]
配置没用，给一个临时方法

```shell
sed -i '/<script src="\/preload_helper\.[a-f0-9]\+\.js"><\/script>/d' index.html
```
