### ISSUE TITLE
umi怎样显示本地svg图标？

### ISSUE THREAD

**Issue by wasay001** [umijs/umi#1264]
为了显示本地svg图标，要怎么配置

**Comment by wasay001** [comment]
哈哈，自己解决了。

1）.umirc.js添加：
    // 添加 url-loader 的 exclude
    urlLoaderExcludes: [/.svg$/],

    // 添加 loader
    chainWebpack(config) {
        config.module.rule('svg')
            .test(/\.svg$/i)
            .use('svg-sprite-loader')
            .loader(require.resolve('svg-sprite-loader'))
    },

2）自定义组件：

const SvgIcon = ({ type, className = '', size = 'md', ...restProps }) => {

    return (
        <svg
            className={`am-icon am-icon-${type.default.id} am-icon-${size} ${className}`}
            {...restProps}
        >
            <use xlinkHref={`#${type.default.id}`} />
        </svg>
    );
};

export default SvgIcon;

 3）显示图标：

import SvgIcon from '../../../components/svgIcon';

<SvgIcon type={require('../../../assets/svg/set.svg')} />

**Comment by wangxingkang** [comment]
这样会有点麻烦  可以利用 require.context 讲svg全部引入  可参考https://github.com/jiumao-fe/react-admin-template 的配置 思路一致

**Comment by xiaohuoni** [comment]
@wangxingkang @wasay001 https://github.com/umijs/umi/pull/1263
