### ISSUE TITLE
[Bug] umi在linux环境中编译时在执行umi setup时报错

### ISSUE THREAD

**Issue by chenyuanjing** [umijs/umi#12647]
![37c85854-f182-43a1-a8b6-6dff38f203aa](https://github.com/user-attachments/assets/b3f3c12c-82b2-4d00-a929-37d223099ffc)

**Comment by sorrycc** [comment]
<img width="812" alt="image" src="https://github.com/user-attachments/assets/006b5f0c-5887-41ec-a7a6-1e199839f24d">
这个脚本报错了，应该是刚好打印到了这里。
