### ISSUE TITLE
[Bug] 打包后报错Refused to execute script from 'http://xxx.com/28.c8419f82.async.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by bbeas** [umijs/umi#12650]
## What happens?

使用umi3.5构建的应用，打包后使用nginx进行部署，部署发版后打开某一个页面有概率表现为一直处于loading态，需要手动刷新页面甚至刷新多次才能看到正常的页面。
![image](https://github.com/user-attachments/assets/d1bf647f-dcdb-4e68-8559-ae97aadf3dad)

打开控制台发现报错信息：
`Refused to execute script from 'http://xxx.com/xxx.c8419f82.async.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

## Mini Showcase Repository(REQUIRED)

涉及到打包部署到线上，比较难提供一个复现repo

## How To Reproduce

1. 改动代码，通过jenkins打包部署
2. 打开某一个页面，发现上述报错
3. 点开控制台，发现上述报错的js文件已失效xxx.c8419f82.async.js，点开后会显示404。如果这时打开一个全新的正常页面，会发现中间的hash值已更改。

初步判断应该是js静态资源已经发生了更改，而浏览器里存的还是旧文件，所以服务器无法找到旧文件，因此返回了一个404的html错误页面。

由于是企业历史项目，升级到umi4可能并不是一个好的选择。如果可以让umi不要一直loading，跳转到其他页面也是可以的。请问有没有什么解决方案或者解决思路可以提供？

## Context

- **Umi Version**: 3.5.42
- **Node Version**: 14.17.0
- **Platform**: macOS + Chrome

**Comment by sorrycc** [comment]
http://xxx.com/xxx.c8419f82.async.js 你需要确保这个文件能访问到，这个是框架之外的事情了。

**Comment by XijueYZ** [comment]
> ## What happens?
> 使用umi3.5构建的应用，打包后使用nginx进行部署，部署发版后打开某一个页面有概率表现为一直处于loading态，需要手动刷新页面甚至刷新多次才能看到正常的页面。 ![image](https://private-user-images.githubusercontent.com/29697116/358960488-d1bf647f-dcdb-4e68-8559-ae97aadf3dad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDIzMDUsIm5iZiI6MTcyOTUwMjAwNSwicGF0aCI6Ii8yOTY5NzExNi8zNTg5NjA0ODgtZDFiZjY0N2YtZGNkYi00ZTY4LTg1NTktYWU5N2FhZGYzZGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDA5MTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MTJmMGQwNjBhYWUyYjZiMTFiZDIzZWRkMmIyZGIyNDc4MjU0MTVjNGNkNTRkNzNlNTAxYWQzMDJmOGRjMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K-LtAqcSY8saACZmYSMJiVCdfHmNTEkufkxuIrt6UQ8)
> 
> 打开控制台发现报错信息： `Refused to execute script from 'http://xxx.com/xxx.c8419f82.async.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`
> 
> ## Mini Showcase Repository(REQUIRED)
> 涉及到打包部署到线上，比较难提供一个复现repo
> 
> ## How To Reproduce
> 1. 改动代码，通过jenkins打包部署
> 2. 打开某一个页面，发现上述报错
> 3. 点开控制台，发现上述报错的js文件已失效xxx.c8419f82.async.js，点开后会显示404。如果这时打开一个全新的正常页面，会发现中间的hash值已更改。
> 
> 初步判断应该是js静态资源已经发生了更改，而浏览器里存的还是旧文件，所以服务器无法找到旧文件，因此返回了一个404的html错误页面。
> 
> 由于是企业历史项目，升级到umi4可能并不是一个好的选择。如果可以让umi不要一直loading，跳转到其他页面也是可以的。请问有没有什么解决方案或者解决思路可以提供？
> 
> ## Context
> * **Umi Version**: 3.5.42
> * **Node Version**: 14.17.0
> * **Platform**: macOS + Chrome

请问你们是怎么解决的呀
