### ISSUE TITLE
本地化文件的建议支持对象形式

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#1265]
比如
export default{
 menu:{
   home:"首页",
   setting:"设置”
 },
 validation:{
   require:'必填',
   phone:'必须为手机号码'
 }
}

使用的时候formatMessage({ id: 'menu.home' })
这样便于分层也可以少写一些代码

**Comment by sorrycc** [comment]
@yutingzhao1991

**Comment by yutingzhao1991** [comment]
现在国际化是基于 react-intl 这个实现的，我的想法是不要做太多定制化的修改。这个特性感觉可以考虑建议 react-intl 来支持。
