### ISSUE TITLE
[Bug]history type设置为hash 本地运行页面空白

### ISSUE THREAD

**Issue by zhibo59** [umijs/umi#12654]
## What happens?

base:'./',
  publicPath: process.env.NODE_ENV === 'production' ? './' : '/',
  history: {
    type: 'hash',
  },
  routes: [
    { path: "/", component: "index" },
    { path: "/successResult", component: "successResult" },
    { path: "/sign", component: "sign" },
    { path: "/successSignResult", component: "successSignResult" },
    {
      path: '*',
      component: '404', // 你可以定义一个404组件
    },
  ],
.umirc.ts文件配置了history type = hash 之后本地run dev 运行后页面空白页，控制台报错mf-dep____vendor.875dd5b9.js:81882 <Router basename="/."> is not able to match the URL "/" because it does not start with the basename, so the <Router> won't render anything.

![image](https://github.com/user-attachments/assets/7fca3620-40ec-47fe-816f-7434cd828f96)
![image](https://github.com/user-attachments/assets/ad253bab-b629-4f6e-b0a8-84009952d7b2)

## Context

- **Umi Version**:4.0.76
- **Node Version**:14.17.0
- **Platform**:

**Comment by sorrycc** [comment]
base 删掉试试，`is not able to match the URL "/" because it does not start with the basename, so the won't render anything.` 报错信息很明确了，因为路由没有匹配上。
