### ISSUE TITLE
开启 mako 后，proxy 失效

### ISSUE THREAD

**Issue by caoxuccc** [umijs/umi#12671]
## What happens?

不开启 mako 时，proxy 配置的代理正常生效，开启后，代理失效，所有接口都 404

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by leshalv** [comment]
+1

**Comment by liyang1234567890** [comment]
一样，请问有解决方法了吗
