### ISSUE TITLE
动态加载路由，报错：TypeError: Cannot read properties of null (reading 'useMemo')

### ISSUE THREAD

**Issue by caoxuccc** [umijs/umi#12673]
## What happens?

动态加载路由，报错：TypeError: Cannot read properties of null (reading 'useMemo')

## Mini Showcase Repository(REQUIRED)
<img width="915" alt="image" src="https://github.com/user-attachments/assets/01545c9f-62dc-4b81-97e0-84f979a6afab">
<img width="1262" alt="image" src="https://github.com/user-attachments/assets/36f2f569-fdf7-493d-bd45-32bb9f431f2b">

![image](https://github.com/user-attachments/assets/44de4d95-1678-4086-85ed-03bf024c256b)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by Jinbao1001** [comment]
看下 react 和 react-dom 的版本, 是不是有多版本依赖.
