### ISSUE TITLE
[Bug] [文档] 官网访问网络不稳定

### ISSUE THREAD

**Issue by ByYogi** [umijs/umi#12676]
2024-09-02 21:00 ~ ?? 
我在上海访问文档加载缓慢。

这是站长工具测试截图
[ping umijs.org](https://ping.chinaz.com/umijs.org/docs/guides/mock)

![screenshots](https://github.com/user-attachments/assets/3e5e138c-1836-4738-a0be-8334c1cb74bc)

![image](https://github.com/user-attachments/assets/905b0952-9b84-4c56-9764-f3bac0edd8b7)
![image](https://github.com/user-attachments/assets/6093a74a-23dc-4829-92bc-464370b82d00)

**Comment by PeachScript** [comment]
Umi 官网托管在 Vercel，没有国内加速，暂时无解

**Comment by ctcx** [comment]
> Umi 官网托管在 Vercel，没有国内加速，暂时无解

慢也就算了，关键是经常打不开啊，开代理都打不开，你主要用户在国内，你就不能托管到阿里云么？
