### ISSUE TITLE
配置式路由报404

### ISSUE THREAD

**Issue by chj-damon** [umijs/umi#1268]
路由配置如下：
```javascript
export default [
  {
    path: '/',
    component: '../layouts/BasicLayout',
    // Routes: ['src/pages/Authorized'], // 所有的子路径都会被这个拦截
    routes: [{ path: '/', component: './homepage' }],
  },
  {
    path: '/user',
    component: '../layouts/UserLayout',
    routes: [
      { path: '/user', redirect: '/user/login' },
      { path: '/user/login', component: './user/login' },
    ],
  },
];
```
在`pages`文件夹下也有`user`文件夹，以及`login.js`，但是在应用启动时，访问`http://localhost:8000/user/login`却提示：
`There's not a page yet at /user/login. 
Create a React.js component in your pages directory at src/pages/user/login.js and configuire the route in config file then this page will automatically refresh to show the new page component you created.`

代码我是按照`ant-design-pro`里面的写法。请问是哪里配置漏了吗？

**Comment by sorrycc** [comment]
把 `/user` 的路由放前面，不然会先匹配到 `/`，然后他的子路由里没有 `/users`，所以 404。

**Comment by Zhou-Bill** [comment]
同样有问题

![image](https://user-images.githubusercontent.com/13554001/47976631-4177ab00-e0ee-11e8-86ae-58410c5609b9.png)

我pages/目录下有a/list.js   但访问`localhost:8000/a`的时候同样报404 但要是放外面访问`localhost:8000/list` 就可以访问，这是为什么
