### ISSUE TITLE
[Bug] umimax 启用mako后，unocss报错

### ISSUE THREAD

**Issue by OneWafer** [umijs/umi#12686]
## What happens?

package.json
<img width="453" alt="iShot_2024-09-06_16 32 43" src="https://github.com/user-attachments/assets/e226603f-8568-45a6-8521-53a2615bf9f6">
config/config.ts
<img width="526" alt="iShot_2024-09-06_16 33 20" src="https://github.com/user-attachments/assets/bad75bc0-16c7-4eb8-87f5-96fc1ab70c4e">

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce
开启mako后刷新页面

## Context
Module not found: Can't resolve '/Users/onewafer/Desktop/Fantec_Git/jarvis-cloud-web/src/.umi/uno.css'
<img width="1055" alt="image" src="https://github.com/user-attachments/assets/b6cb64d0-fd7b-47f7-8afa-897e8d6e4f20">
![image](https://github.com/user-attachments/assets/b3506aab-0b1f-4577-b2f9-6cc8a6752f83)

- **Umi Version**:umi/max@4.3.19
- **Node Version**:v20.12.2
- **Platform**:macOS 14.6.1 (23G93)

**Comment by OneWafer** [comment]
不开启mako时正常，开启后才会报错

**Comment by xiaohuoni** [comment]
![image](https://github.com/user-attachments/assets/ea6148f0-4d7c-4fce-ab41-1ee829d46379)

在 [with-unocss](https://github.com/umijs/umi/tree/master/examples/with-unocss) 里面试了，没什么问题 。应该还有其他原因，可以给一个复现
