### ISSUE TITLE
umi dev 启动阶段的编译需要一个进度显示在命令行

### ISSUE THREAD

**Issue by huangcheng1** [umijs/umi#12682]
## Background

![image](https://github.com/user-attachments/assets/bfbff08f-f710-42b0-b768-de19858a041e)

## Proposal

![image](https://github.com/user-attachments/assets/c9d3dabb-7b62-4a97-a68a-e2ee12170fe6)

## Additional context

因为模版文件是自定义的，所以界面上的进度无法显示，希望在命令行调试和打包都有进度，方便查看是否已经完成。

**Comment by Jinbao1001** [comment]
什么模板文件是自定义的 ?

**Comment by huangcheng1** [comment]
@Jinbao1001 html文件模版，我们的做法是通过域名 A.com/index.html，里面插入localhost:8000/umi.js的标签来进行本地调试启动。index.html是固定模版。

**Comment by Jinbao1001** [comment]
可以试试用 `mako` 构建.
