### ISSUE TITLE
[Bug] umi4中 import alarm from "/static/acop_screw_alarm.png"加载public下的图片会提示找不到图片

### ISSUE THREAD

**Issue by hnldlsjzt** [umijs/umi#12696]
## What happens?

umi4中 import alarm from "/static/acop_screw_alarm.png"加载public下的图片会提示找不到图片。
但我在另一个 umi4 的项目中，这样做又是正常的。

## Mini Showcase Repository(REQUIRED)

使用的代码：
import ref_dryer_alarm from '/static/ref_dryer_alarm.png';

报错提示：
error - ./src/pages/editor/components/materials/components/monitor/devices/__deviceImg__/deviceMap.ts:25:0-58
Module not found: Error: Can't resolve '/static/ref_dryer_alarm.png' in 'C:\Users\user\Work\deeplogic.designer\src\pages\editor\components\materials\components\monitor\devices\__deviceImg__'

public下的图片：
![image](https://github.com/user-attachments/assets/15e3035a-2712-4775-81bc-4f8e33cfb9e1)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

`export default defineConfig({
  publicPath: '/',
  title: 'DeepLogic',
  // codeSplitting: { jsStrategy: 'granularChunks' },
  extraBabelPlugins: ['babel-plugin-dynamic-import-node'],
  alias: {
    '@': require('path').resolve(__dirname, 'src'),
    '@utils': require('path').resolve(__dirname, 'src/utils'),
    '@layouts': require('path').resolve(__dirname, 'src/layouts'),
    '@assets': require('path').resolve(__dirname, 'src/assets'),
    '%config': require('path').resolve(__dirname, 'src/utils/config.js'),
    '%request': require('path').resolve(__dirname, 'src/utils/request.js'),
    '%common': require('path').resolve(__dirname, 'src/utils/common.js'),
    '%rights': require('path').resolve(__dirname, 'src/utils/rights.js'),
    '%lesscommon': require('path').resolve(__dirname, 'src/pages/common.less'),
    '@components': require('path').resolve(__dirname, 'src/components'),
    '@hooks': require('path').resolve(__dirname, 'src/hooks'),
  },
  plugins: ['@umijs/plugins/dist/dva', '@umijs/plugins/dist/antd'],
  mock: false,
  mfsu: false,
  dva: {},
  antd: {},
  lessLoader: {
    modifyVars: {
      ...mapToken,
      ...v4Token,
      ...v5Token,

      // 编辑器相关Token
      editorHeaderHeight: 48,
      editorPageTabsHeight: 50
    }
  },
  codeSplitting: {
    jsStrategy: 'granularChunks'
  },
  cssMinifier: 'esbuild',
  cssMinifierOptions: {
    minifyWhitespace: true,
    minifySyntax: true
  },
  jsMinifier: 'terser',
  jsMinifierOptions: process.env.BUILD_ENV
    ? {
        compress: {
          warnings: false,
          drop_console: true, //console
          drop_debugger: false,
          pure_funcs: ['console.log'] //移除console
        }
      }
    : {},
  chainWebpack: (config: any) => {
    config.module.rule('ignore-md-files').test(/\.md$/).use('ignore-loader').loader('ignore-loader').end();
    config.cache({
      type: 'filesystem',
      buildDependencies: {
        config: [__filename]
      }
    });
    // ... 其他配置
  },
  devtool: 'eval',
  hash: true,
  proxy: {
    '/_api': {
      target: 'http://192.168.124.4:32801',
      changeOrigin: true,
      ws: true,
      pathRewrite: { '^/_api': '' }
    },
    '/_core': {
      target: 'http://192.168.124.4:32889',
      changeOrigin: true,
      ws: true,
      pathRewrite: { '^/_core': '' }
    },
    '/_viewer': {
      target: 'http://192.168.124.4:32800/_viewer',
      changeOrigin: true,
      ws: true,
      pathRewrite: { '^/_viewer': '' }
    }
  }
});
`

## Context

- **Umi Version**: 4.1.8
- **Node Version**: v20.11.1
- **Platform**: windows11

**Comment by hnldlsjzt** [comment]
这是另一个项目的配置，在这个项目下这样使用，是正常的。配置如下:
export default defineConfig({
  routes: [
    { path: '/404', component: '404' },
    { path: '/:pid', component: 'index' },
    { path: '/:pid/:pageid', component: 'index' },
    { path: '/signin', component: 'auth/signin' },
    { path: '/*', component: '404' }
  ],
  alias: {
    '@': require('path').resolve(__dirname, 'src'),
    'src': require('path').resolve(__dirname, 'src'),
    '@assets': require('path').resolve(__dirname, 'src/assets')
  },
  npmClient: 'npm',
  dva: {},
  plugins: ['@umijs/plugins/dist/dva', '@umijs/plugins/dist/antd'],
  lessLoader: {
    modifyVars: {
      ...mapToken,
      ...v5Token
    }
  },
  jsMinifier: 'terser',
  jsMinifierOptions: process.env.BUILD_ENV
    ? {
        compress: {
          warnings: false,
          drop_console: true, //console
          drop_debugger: false,
          pure_funcs: ['console.log'] //移除console
        }
      }
    : {},
  cssMinifier: 'cssnano',
  chainWebpack: (config: any, { env }) => {
    //   config.cache({
    //    type: 'filesystem',
    //    buildDependencies: {
    //     config: [__filename],
    //   },
    //  });
    if (env === 'production') {
      config.cache({
        type: 'filesystem',
        store: 'pack',
        buildDependencies: {
          config: [__filename],
          tsconfig: [join(__dirname, 'tsconfig.json')],
          packagejson: [join(__dirname, 'package.json')],
          umirc: [join(__dirname, '.umirc.ts')]
          // 🟡 其他可能会影响项目的配置文件路径，其内容变更会使缓存失效
        }
      });
    }
    config.resolve.extensions.add('.jsx');
    // 为文件名添加 hash
    config.output.filename('[name].[contenthash].js');
    // 后续等 vite 重构的组态工程发布后，开发以下代码，不加文件hash
    // // 处理图片文件
    // config.module
    //   .rule('images')
    //   .test(/\.(png|jpe?g|gif|svg|webp)$/)
    //   .type('asset/resource') // 使用 asset/resource 处理图片
    //   .set('generator', {
    //     filename: 'static/[name][ext]', // 图片文件添加 contenthash 以确保唯一性
    //   });

  },
  hash: true,
  proxy: {
    '/_api': {
      target: 'http://192.168.124.4:32801',
      changeOrigin: true,
      ws: true,
      pathRewrite: { '^/_api': '' }
    },
    '/_core': {
      target: 'http://192.168.124.4:32889',
      changeOrigin: true,
      ws: true,
      pathRewrite: { '^/_core': '' }
    }
  }
});

Context
- Umi Version: 4.1.10
- Node Version: v20.11.1
- Platform: windows11

**Comment by xiaohuoni** [comment]
不应该直接找产物中的 static。你可以引用项目文件夹的图片，会根据图片的大小做不同的处理，比如小图片会被以 base64 的数据存储。你也可以尝试改改 inlinelimit 配置，让所有的图片都拷贝到产物目录，或许也能找到，但不建议 https://umijs.org/docs/api/config#inlinelimit

**Comment by hnldlsjzt** [comment]
为什么要放在 public 下呢？
因为不想打包这些图片，不想加文件名后面加 hash。所有把图片放在 public 下了。所以 inlinelimit  可能解决不了这个诉求。
但更奇怪的是，在其他 umi 工程里可以直接使用 public 下的图片，但这个工程下就提示找不到

**Comment by hnldlsjzt** [comment]
@xiaohuoni
