### ISSUE TITLE
umi3.5当项目过大时热更新速度太慢(进度条会卡在copy-webapck-plugin 92% 这里一段时间)，如何优化和解决热更新时间过长的问题？

### ISSUE THREAD

**Issue by IsDyh01** [umijs/umi#12692]
## What happens?

![image](https://github.com/user-attachments/assets/04f4d6ae-8afc-4cae-b356-ad3f7eb0fe69)

![image](https://github.com/user-attachments/assets/434d7f6e-2516-472d-9c5d-f7e538b54fcc)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
由于是公司项目，目前还无法复现。

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- Umi Version : 3.5
- Node Version: 12
- Platform: window

**Comment by Jinbao1001** [comment]
升级 `umi 4`, 并开启 `mako` 构建

**Comment by Jinbao1001** [comment]
[升级到 Umi 4](https://umijs.org/docs/introduce/upgrade-to-umi-4) 参考升级文档进行升级. 

[路由兼容配置](https://umijs.org/docs/api/config#reactrouter5compat)

**Comment by IsDyh01** [comment]
感谢解答！！
