### ISSUE TITLE
[Bug] windows下antdpro项目开启mako后 Invalid Unicode escape sequence

### ISSUE THREAD

**Issue by echoyl** [umijs/umi#12694]
## What happens?

1.配置如果设置base 直接无法访问
2.去掉base后启动报如下错误，请问下是哪里配置错了吗？
![image](https://github.com/user-attachments/assets/fe3132de-819d-4ef0-8734-6e16dad05ec9)
![image](https://github.com/user-attachments/assets/cec5f4cc-175c-4635-87c5-167921ff9156)

## Context

- **Umi Version**:v4.3.20
- **mako Version**:v0.8.11

**Comment by liuwenzhuang** [comment]
反斜杠需要 `\\` 转义

**Comment by darylltee** [comment]
I have the same error

**Comment by phoema** [comment]
+1

**Comment by hj458377603** [comment]
+1

**Comment by xiaohuoni** [comment]
相同的 issues https://github.com/umijs/mako/issues/1580
