### ISSUE TITLE
[Bug] 路由path携带参数后跳转404

### ISSUE THREAD

**Issue by xiaoxuehai** [umijs/umi#12698]
## What happens?

1.第一种情况
![image](https://github.com/user-attachments/assets/a5de0028-2c02-4c07-be85-33ec97269ced)
如上图，路由配置中携带静态search参数时，页面会跳转至404页面，无法识别该路由
2.第二种情况
![image](https://github.com/user-attachments/assets/da67f913-9c41-45ff-ac83-419528cbd522)
![image](https://github.com/user-attachments/assets/a50c6469-ee87-4956-8bfb-5cbca09c4e75)
![image](https://github.com/user-attachments/assets/770b0554-2f26-402e-b4e6-e6e5f6ddd7ae)
如上图，路由配置中不携带参数时，在app.tsx layout menu中手动给路由path拼接参数时，菜单点击跳转404，但是刷新后正常，目测携带参数时跳转没有触发视图更新

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
配置的时候可以使用 `/list/:id` 
 layout 相关的配置，可能需要看看 https://pro.ant.design/zh-CN/docs/advanced-menu/
