### ISSUE TITLE
umi 4.3.20 在windows 使用mako 出现异常信息

### ISSUE THREAD

**Issue by Nokecy** [umijs/umi#12709]
× Bad character escape sequence, expected 4 hex characters
     ╭─[node_modules\antd\es\locale?context&glob=**\*:262:1]
 262 │ './tr_TR.d': () => require('D:/Develop\React\landun_tms_web\node_modules\antd\es\locale\tr_TR.d.ts'),
 263 │ './tr_TR.js': () => require('D:/Develop\React\landun_tms_web\node_modules\antd\es\locale\tr_TR.js'),
 264 │ './tr_TR': () => require('D:/Develop\React\landun_tms_web\node_modules\antd\es\locale\tr_TR.js'),
 265 │ './uk_UA.d.ts': () => require('D:/Develop\React\landun_tms_web\node_modules\antd\es\locale\uk_UA.d.ts'),
     ·                                                                                           ──
 266 │ './uk_UA.d': () => require('D:/Develop\React\landun_tms_web\node_modules\antd\es\locale\uk_UA.d.ts'),
 267 │ './uk_UA.js': () => require('D:/Develop\React\landun_tms_web\node_modules\antd\es\locale\uk_UA.js'),
 268 │ './uk_UA': () => require('D:/Develop\React\landun_tms_web\node_modules\antd\es\locale\uk_UA.js'),
     ╰────

**Comment by sorrycc** [comment]
这个修复了，今天 Umi 会更新一版修复这个问题。

**Comment by Nokecy** [comment]
@sorrycc  同样的问题  4.3.23

**Comment by xushanpei** [comment]
解决了吗这个问题, 遇到了同样的问题
