### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by HongLingJin1994** [umijs/umi#12713]
## This error happened while installing the dependencies of dva@2.5.0-beta.2

> win10环境，node版本18.17.0，pnpm版本8.15.4.

## 复现步骤

** 执行pnpm dlx create-umi@latest
** 选Ant Design Pro
** pnpm
** npm

Downloading registry.npmmirror.com/@umijs/mako-win32-x64-msvc/0.8.11: 16.33 MB/16.33 MB, done
 ERR_PNPM_UNEXPECTED_PKG_CONTENT_IN_STORE  Package name mismatch found while reading {"integrity":"sha512-xIp7/apCFJuUHdDLWe8O1HIkb0kQrOMb/0u6FXQjemHn/ii5LrIzU6bdECnsiTF/GjZkMEKg1xdiZwNqDYlZ6g==","tarball":"https://registry.npmmirror.com/path-to-regexp/-/path-to-regexp-1.9.0.tgz"} from the store. This means that the lockfile is broken. Expected package: path-to-regexp@1.9.0. Actual package in the store by the given integrity: path-to-regexp@1.8.0.   

This error happened while installing the dependencies of dva@2.5.0-beta.2
 at react-router-dom@4.3.1
 at react-router@4.3.1

## Context

- **Umi Version**:4.3.20
- **Node Version**:18.17.0
- **Platform**:win10

**Comment by telanflow** [comment]
我也碰到这个问题，Umi Version:4.3.21

**Comment by telanflow** [comment]
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/39300e3c-c27f-4340-b9b9-6a79c4c8a90e">

**Comment by telanflow** [comment]
> 我也碰到这个问题，Umi Version:4.3.21

回退到Umi Version: 4.3.20 版本 正常。

@stormslowly

**Comment by HongLingJin1994** [comment]
咱们的报错还不太一样，我的本来就是4.3.20版本。
![image](https://github.com/user-attachments/assets/cee4931a-3949-4e10-b647-ad2ae4b0abc3)

**Comment by Ghh118** [comment]
> 咱们的报错还不太一样，我的本来就是4.3.20版本。 ! [image] (https://private-user-images.githubusercontent.com/64454641/369739563-cee4931a-3949-4e10-b647-ad2ae4b0abc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODQ2MjUsIm5iZiI6MTcyNzA4NDMyNSwicGF0aCI6Ii82NDQ1NDY0MS8zNjk3Mzk1NjMtY2VlNDkzMWEtMzk0OS00ZTEwLWI2NDctYWQyYWU0YjBhYmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA5Mzg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYjg4ZDJkNDhiY2QxZDJjMDczMWUxMTM4Mjg1ZTg4NzA4MzUzNDEyOWY3ZDFkNmE4NTViNWM1ZTgyNzQxNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9-DF3gf7v8POQh6naUsvxrbp4BZo3QKq62acGmx3wWk)

改好了吗  我的报错跟你一模一样

**Comment by flgame** [comment]
遇到同样的问题，后来发现是用了taobao的源，不知道什么原因把**path-to-regexp 1.8版本 和 1.9版本的压缩包调换了**，导致和压缩包里package.json中版本不一致。
可以清除pnpm缓存换源重新安装

**Comment by wuanke** [comment]
同遇到这个问题。npm i直接报错了
