### ISSUE TITLE
form表单-fromItem rules-pattern一触发页面就特别的卡-同时network里面umi.js自动增加

### ISSUE THREAD

**Issue by zhaohang1993** [umijs/umi#1272]
版本
 dva：3.9.0
 umi：1.3.18
 antd：3.9.0
问题描述
antd_form_formItem下面的pattern正则属性一触发页面就变的特别卡 同事network里面umi.js一直在增加
截图：
![webwxgetmsgimg](https://user-images.githubusercontent.com/28669210/47069605-eacf2d80-d221-11e8-82f3-d0a2533549d4.jpg)
![webwxgetmsgimg 2](https://user-images.githubusercontent.com/28669210/47069673-15b98180-d222-11e8-8156-96c11ab74fdc.jpg)

**Comment by sorrycc** [comment]
提供可复现的库吧。

**Comment by zhaohang1993** [comment]
from表单验证时。使用的正则。需要我把项目目录发给您吗




| |
111
|
|
邮箱：zhaohang_pic@163.com
|

Signature is customized by Netease Mail Master

在2018年10月17日 15:45，chencheng (云谦) 写道：

提供可复现的库吧。

**Comment by sorrycc** [comment]
是的，最好是一个简化后的可复现仓库，我安装依赖后 `npm start` 就能复现的。
