### ISSUE TITLE
[Bug] umi配置中开启keepalive后，在开启mako模式后不兼容

### ISSUE THREAD

**Issue by phoema** [umijs/umi#12722]
config.ts中：
  /**
   * @name 多tab缓存页
   * @description 正则匹配需要缓存的页面，至少两个/abc/
   * @doc 
   */
  keepalive: [/^(?:[^\/]*\/){2}[^\/]*/],
  /**
  * @name 多tab缓存页
  * @description hasCustomTabs:手动处理tab
  * @doc 
  */
  tabsLayout: { hasCustomTabs: true },
  mfsu: false,
  mako: {},

页面启动后浏览器报错：
![image](https://github.com/user-attachments/assets/e71aa3e0-ff59-4809-b8f3-94562c5244af)

node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom.production.min.js:188 TypeError: Cannot read properties of null (reading 'applyPlugins')

config中注释掉keepalive、tabsLayout，页面能正常打开。

## Context

- **Umi Version**: 4.3.24
- **Node Version**: 20
- **Platform**: windows

**Comment by xiaohuoni** [comment]
关注这里就好，实验性功能 https://github.com/alitajs/alita/issues/671
