### ISSUE TITLE
[Bug] umiMax下  Mako在windows下运行不起来

### ISSUE THREAD

**Issue by PikachuGits** [umijs/umi#12738]
## What happens?
![Snipaste_2024-10-16_10-51-50](https://github.com/user-attachments/assets/d2cb8fcc-f498-47e0-b053-71ee9f5571ec)

通过  pnpm dlx create-umi@latest 命令创建的新项目
配置mako: {}, 
![config0](https://github.com/user-attachments/assets/df9cb538-51c2-40a1-8578-66076d48e1fe)

运行 pnpm run dev 后会在20% 终止,并且没有任何报错信息

umi版本v4.3.26

**Comment by LeonHardtll** [comment]
我把 @umijs/max 的版本降到 4.3.24 就能运行了，最新版不知道有什么问题，期待官方修复

**Comment by tangbzai** [comment]
@umijs/max 4.3.28 修复了

**Comment by phoema** [comment]
+1
![image](https://github.com/user-attachments/assets/4a94be58-be02-40d4-9cb0-52b7416a2447)

**Comment by tangbzai** [comment]
4.3.28 卡 65% 的问题我在 mako 项目那边提 [issus](https://github.com/umijs/mako/issues/1668) 了

**Comment by xiaohuoni** [comment]
mako 的 window 支持还未完成，相关问题，请关注 mako 那边的进度
