### ISSUE TITLE
[Bug] 配置history hash模式 与base 问题

### ISSUE THREAD

**Issue by Ricky816845** [umijs/umi#12746]
![image](https://github.com/user-attachments/assets/578e3444-ccfa-4443-a837-1a84ff6edb79)

![image](https://github.com/user-attachments/assets/6b5ca5d6-dcd2-4c9a-ab08-2d844d717b03)

这个路由拼的不对吧 ？
/a/b 不应该在hash里啊

**Comment by purple-force** [comment]
base 是前端路由的前缀，如果是 hash 路由，当然是在 hash 里了。

**Comment by purple-force** [comment]
> ![image](https://private-user-images.githubusercontent.com/20158450/377753798-578e3444-ccfa-4443-a837-1a84ff6edb79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDEyNDIsIm5iZiI6MTcyOTUwMDk0MiwicGF0aCI6Ii8yMDE1ODQ1MC8zNzc3NTM3OTgtNTc4ZTM0NDQtY2NmYS00NDQzLWE4MzctMWE4NGZmNmVkYjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDA4NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MmE0MjljNWExMzBmMzE2NjIyYTZmYTJkMWJlNmQ3OTkxMTE4ZDllODJkNTE1MGIyYWZkYjFkZDVkMGE0YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4nKybj9hT8Pysjou7LfkvRrnZvU5fTF072VNwkjORnc)
> 
> ![image](https://private-user-images.githubusercontent.com/20158450/377753948-6b5ca5d6-dcd2-4c9a-ab08-2d844d717b03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDEyNDIsIm5iZiI6MTcyOTUwMDk0MiwicGF0aCI6Ii8yMDE1ODQ1MC8zNzc3NTM5NDgtNmI1Y2E1ZDYtZGNkMi00YzlhLWFiMDgtMmQ4NDRkNzE3YjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDA4NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4N2M2OTZhOTZhMDc0ZDFhZjlhY2Q0YTcyMTNmMjQ1OTQzYjlmMGEyOWY0ODIxMzk2YTFjYzQ0NTZmY2EwZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YXu9Hg-qcx2TG7xwsIyOvxBssGjY_e3KTDg-lmRprIQ)
> 
> 这个路由拼的不对吧 ？ /a/b 不应该在hash里啊

base 是前端路由的前缀，如果是 hash 路由，当然是在 hash 里了。

**Comment by Ricky816845** [comment]
> base 是前端路由的前缀，如果是 hash 路由，当然是在 hash 里了。

那我要部署在非根目录，还要hash路由模式，要怎么配置？ 这个是ant design pro的模板

**Comment by Ricky816845** [comment]
明白了，用PublicPath
