### ISSUE TITLE
[Feature Request]  升级一下 react-router-dom  可以用原生的 useBlocker 

### ISSUE THREAD

**Issue by kokiy** [umijs/umi#12743]
## Background

 我们的项目有这样一个需求,如果用户填写了部分表单,想要回退时候给他提示 是否放弃修改. 需要用找个useBlocker 

## Proposal

 可以正常还用useBlocker ,无需任何魔法

**Comment by hualigushi** [comment]
暂不考虑升级
参考 https://github.com/umijs/umi/discussions/10237#discussioncomment-4625915 自己实现下

**Comment by hth520** [comment]
太赞了，#10237解决了我的问题
