### ISSUE TITLE
如何配置入口文件index.js

### ISSUE THREAD

**Issue by curry-wxj** [umijs/umi#1274]
想有一个 src/index.js 入口文件，在这个js文件中 我可以去初始化资源。 可以在页面还未加载的时候 去加载配置文件等等。
设置chainWebpack时会报错
  chainWebpack: config => {
    config.entry('index')
    .add('src/index.js')
    .end()
  },
This dependency was not found:
* src/index.js in multi src/index.js
To install it, you can run: npm install --save src/index.js

**Comment by sorrycc** [comment]
参考 #1254
