### ISSUE TITLE
[Feature Request] umi3中无法使用xlsx插件。

### ISSUE THREAD

**Issue by Nikehu98** [umijs/umi#12757]
## Background

在我的umi项目中需要用到导出列表为Excel的需求。于是在项目中安装了xlsx插件，但是无法被识别并使用。

## Proposal

yarn add xlsx

import * as XLSX from "xlsx";

## Additional context

页面报错：devScripts.js:6523 [@umijs/runtime] load component failed Error: Module "./xlsx" does not exist in container.
while loading "./xlsx" from webpack/container/reference/mf

**Comment by Jinbao1001** [comment]
无法复现

1. 尝试清除 `node_modules/.cache` 文件.
2. 关闭mfsu -> `mfsu: false`

如果还有问题请提供复现仓库.

**Comment by sjl-inQF** [comment]
遇到了同样的问题，删掉nodemodule，重新npm i也还是不行呢
