### ISSUE TITLE
[Bug] "@umijs/max": "^4.3.28",创建的新项目会控制台会出现Warning: findDOMNode is deprecated and will be removed in the next major release. 

### ISSUE THREAD

**Issue by bigCongee** [umijs/umi#12756]
第一步
yarn create umi

第二步
yarn dev

启动项目后控制台会出现
Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node Error Component Stack

应该如何解决,谢谢

**Comment by xu756** [comment]
Same issue here. Stable as well.

**Comment by ljy0062** [comment]
Same issue here. Stable as well.

**Comment by ljy0062** [comment]
No more than two menus can appear in the left menu bar. An error will be reported when more than two items appear
