### ISSUE TITLE
[Bug] install click-to-component error

### ISSUE THREAD

**Issue by purple-force** [umijs/umi#12763]
## What happens?

click-to-component 刚发布了 1.1.2 版本，umi 内置插件依赖该包实现 clickToComponent 功能，安装依赖报错 
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in xxxxx//ode_modules/click-to-react-component/package.json

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

已提 issue，遇到同样问题请跟踪 https://github.com/ericclemmons/click-to-component/issues/93 

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by wulibaibao** [comment]
config.ts注释掉clickComponent，删除.umi，重新install，也不行。。。

**Comment by purple-force** [comment]
> config.ts注释掉clickComponent，删除.umi，重新install，也不行。。。
可以先在 click-to-components 的 pkg 里手动自己添加下

**Comment by seesawz** [comment]
遇到了同样的错误，在流水线全云端构建的情况下，理想操作是只能回退版本了吗

**Comment by seesawz** [comment]
> 可以先在 click-to-components 的 pkg 里手动自己添加下

除了自己修改版本号，没有其他的解决办法吗？

**Comment by purple-force** [comment]
> > 可以先在 click-to-components 的 pkg 里手动自己添加下
> 
> 除了自己修改版本号，没有其他的解决办法吗？

patch-package 这包也可临时顶下

**Comment by MarioJames** [comment]
`@umijs/preset-umi ` 包刚发了最新版本 `4.3.29`，重新更新下依赖就好了

**Comment by seesawz** [comment]
> > > 可以先在 click-to-components 的 pkg 里手动自己添加下
> > 
> > 
> > 除了自己修改版本号，没有其他的解决办法吗？
> 
> patch-package 这包也可临时顶下

感谢🙏

**Comment by zhaodengping** [comment]
How can I solve this proble?

**Comment by seesawz** [comment]
> How can I solve this proble?我该如何解决这个问题？

update umi version

**Comment by zhaodengping** [comment]
> > How can I solve this proble?我该如何解决这个问题？
> 
> update umi version

非常感谢，我把umi升级到4.4.4，已经正常打包了。然后我翻了umi发布日志，发现在4.3.29解决的这个问题，umi日志是：https://github.com/umijs/umi/releases；
再次感谢！
