### ISSUE TITLE
[Feature Request] 在开启qiankun时，使用路由缓存

### ISSUE THREAD

**Issue by jinxiangqiang** [umijs/umi#12760]
## Background

目前我使用的是umi4,缓存使用的https://github.com/irychen/keepalive-for-react   ，它是基于route 6的，我希望它能缓存qiankun的状态，但是实际无法缓存

## Proposal

我希望我能通过开启某个参数，支持route6的qiankun的缓存

**Comment by xiaohuoni** [comment]
keepalive-for-react 这个库看起来本身也不支持微应用，你可以去这里讨论 https://github.com/irychen/keepalive-for-react/issues/14
