### ISSUE TITLE
inlineLimit配置为0无效的问题 

### ISSUE THREAD

**Issue by Jokergga** [umijs/umi#12766]
在.umirc.ts 配置 inlineLimit 为 0 时，inlineLimit 还是 10000 字节走的打包图片文件
配置：
![image](https://github.com/user-attachments/assets/e697c875-e449-4c98-a70a-eabdeda2cad5)
打包结果：
![image](https://github.com/user-attachments/assets/2e777b4a-7c96-4c8d-97a7-4f66503526d8)
如图，assets 目录下的静态资源打包成了 base64

**Comment by sorrycc** [comment]
Fixed via https://github.com/umijs/umi/pull/12768
