### ISSUE TITLE
[Bug] 开启mako和unocss的情况下，启动失败

### ISSUE THREAD

**Issue by AdoKevin** [umijs/umi#12777]
## What happens?

在启用mako和unocsss后，npm run dev 启动时，提示  `.umi/uno.css` 文件找不到, 但实际上这个文件是存在的。

![image](https://github.com/user-attachments/assets/f5b0c5d8-58a3-46b2-bb38-cfba0aaf5ac2)

这个问题之前我看别人在 #12686 也反馈过 ，但是issue 关闭了。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/AdoKevin/umi/tree/bug_report_unocss_with_mako

其实也只是基于with_unocss 添加了mako: {}

![image](https://github.com/user-attachments/assets/62e384d3-debc-4de2-9829-e7707ad6afbe)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.3.30
- **Node Version**: v20.18.0
- **Platform**: linux X64

**Comment by stormslowly** [comment]
盲猜下 是不是 unocss 还没有编译好 mako 就去 require 了， 你看看能不能先单独跑下 unocss 把 css 文件先生成了。

**Comment by AdoKevin** [comment]
大概还是插件时序导致的，但是尝试了把uno.css文件先放在那，在 run dev 还是报错。
