### ISSUE TITLE
[Bug] 使用Umijs4框架打包的dist文件部署到线上环境，umi.js文件2.6M，加载速度非常缓慢，如何解决？

### ISSUE THREAD

**Issue by wq1997** [umijs/umi#12786]
图片如下：
![image](https://github.com/user-attachments/assets/51e52ee8-738f-411f-b25c-f458c08125c5)

**Comment by keer6** [comment]
/**
   * @name 执行umi拆包策略
   * @description 这会按照一定的优化策略进行自动分包
   * @doc https://umijs.org/blog/code-splitting#%E5%88%86%E6%9E%90%E4%BA%A7%E7%89%A9%E6%9E%84%E6%88%90
   */
  codeSplitting: {
    jsStrategy: 'granularChunks',
  },
