### ISSUE TITLE
[Bug] npm install error: [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/fy/code/demo_web/node_modules/click-to-react-component/package.json

### ISSUE THREAD

**Issue by yfboot** [umijs/umi#12787]
## What happens?
执行npm install时，报错ant-design-pro@6.0.0 postinstall,同样的package.json文件，之前可以，最近突然安装失败，所有使用 umi 构建的项目都会安装失败，报错这个
> max setup

fatal - Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/fy/code/demo_web/node_modules/click-to-react-component/package.json

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

下面是完整的终端报错信息：

> ant-design-pro@6.0.0 postinstall
> max setup

fatal - Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/fy/code/demo_web/node_modules/click-to-react-component/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:365:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:589:7)
    at resolveExports (node:internal/modules/cjs/loader:556:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:596:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1014:27)
    at Function.mod._resolveFilename (/Users/fy/code/demo_web/node_modules/umi/dist/service/requireHook.js:13:26)
    at Function.resolve (node:internal/modules/cjs/helpers:125:19)
    at clickToComponent_default (/Users/fy/code/demo_web/node_modules/@umijs/preset-umi/dist/features/clickToComponent/clickToComponent.js:51:52)
    at Service.initPlugin (/Users/fy/code/demo_web/node_modules/@umijs/core/dist/service/service.js:463:40) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
fatal - A complete log of this run can be found in:
fatal - /Users/fy/code/demo_web/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
npm ERR! code 1
npm ERR! path /Users/fy/code/demo_web
npm ERR! command failed
npm ERR! command sh -c -- max setup

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fy/.npm/_logs/2024-11-18T15_58_02_423Z-debug-0.log

## Context

- **Umi Version**: 4.1.0
- **Node Version**: v16.20.2 
- **npm version**: 8.19.4

- **Platform**: react 18.2.0

**Comment by yfboot** [comment]
修改代码仓库地址

**Comment by purple-force** [comment]
https://github.com/umijs/umi/issues/12763

**Comment by yfboot** [comment]
问题已经解决。
[原因]umi依赖的click-to-react-component更新了版本。
[解决方式]
1）在项目的package.json中dependencies目录下或者devDependencies(推荐放在这个层级下)层级下添加指定的版本依赖
经过验证，"click-to-react-component": "1.1.0" 或者 "click-to-react-component": "1.0.8"都可解决
2）可以直接去项目中,node_modules/click-to-react-component/package.json 中，exports层级下增加     "require":"./src/index.js", 即可解决（经过验证）

**Comment by xiaohuoni** [comment]
// package.json
  "resolutions": {
    "click-to-react-component":"1.1.0"
  }

**Comment by LeeZChuan** [comment]
在楼主的建议之上锁定了部分umi的版本，便生效了
` "dependencies": {
    "@ant-design/icons": "^4.8.1",
    "@ant-design/pro-components": "2.6.48",
    "@umijs/route-utils": "2.2.2",
    "antd": "^5.13.2",
    "antd-style": "^3.6.1",
    "classnames": "^2.5.1",
    "lodash": "^4.17.21",
    "moment": "^2.30.1",
    "omit.js": "^2.0.2",
    "querystring": "^0.2.1",
    "quill": "^2.0.2",
    "rc-menu": "^9.12.4",
    "rc-util": "^5.38.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-helmet-async": "^1.3.0"
  },
  "devDependencies": {
    "click-to-react-component": "1.0.8",
    "@ant-design/pro-cli": "^3.3.0",
    "@testing-library/react": "^13.4.0",
    "@types/classnames": "^2.3.1",
    "@types/express": "^4.17.21",
    "@types/history": "^4.7.11",
    "@types/jest": "^29.5.11",
    "@types/lodash": "^4.14.202",
    "@types/react": "^18.2.48",
    "@types/react-dom": "^18.2.18",
    "@types/react-helmet": "^6.1.11",
    "@umijs/fabric": "2.14.1",
    "@umijs/lint": "4.1.1",
    "@umijs/max": "4.1.1",
    "cross-env": "^7.0.3",
    "eslint": "^8.56.0",
    "express": "^4.18.2",
    "gh-pages": "^3.2.3",
    "husky": "^7.0.4",
    "jest": "^29.7.0",
    "jest-environment-jsdom": "^29.7.0",
    "lint-staged": "^10.5.4",
    "mockjs": "^1.1.0",
    "prettier": "^2.8.8",
    "react-dev-inspector": "^1.9.0",
    "swagger-ui-dist": "^4.19.1",
    "ts-node": "^10.9.2",
    "typescript": "^5.3.3",
    "umi-presets-pro": "2.0.3",
    "umi-serve": "1.9.11"
  },
  "engines": {
    "node": ">=12.0.0"
  },
  "resolutions": {
    "click-to-react-component": "1.0.8"
  }`

**Comment by weiblank** [comment]
> 问题已经解决。 [原因]umi依赖的click-to-react-component更新了版本。 [解决方式] 1）在项目的package.json中dependencies目录下或者devDependencies(推荐放在这个层级下)层级下添加指定的版本依赖 经过验证，"click-to-react-component": "1.1.0" 或者 "click-to-react-component": "1.0.8"都可解决 2）可以直接去项目中,node_modules/click-to-react-component/package.json 中，exports层级下增加 "require":"./src/index.js", 即可解决（经过验证）

添加"require":"./src/index.js"可以解决了 万分感谢
