### ISSUE TITLE
[Bug] 'headScripts' 中的脚本不应该强制添加 crossOrigin: anonymous

### ISSUE THREAD

**Issue by gin-lsl** [umijs/umi#12794]
https://github.com/umijs/umi/blob/898d61fc9a99a553160cbc17d628eaec13dae86a/packages/renderer-react/src/html.tsx#L103

这样无法将 crossOrigin 删掉。设置为空也会有这个 attribute，值相当于 anonymous

**Comment by xiaohuoni** [comment]
是不是可以设置成 [use-credentials](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Attributes/crossorigin#use-credentials)

**Comment by gin-lsl** [comment]
我试了下，只要有这个属性，而无论值是什么，浏览器就会进行 CORS 检查。而我们需要加载第三方脚本。
