### ISSUE TITLE
[Bug] Link prefetch is not working

### ISSUE THREAD

**Issue by afc163** [umijs/umi#12790]
## What happens?

https://umijs.org/docs/api/api#link 中提到 Link 的 `prefetch` 属性：

> 若开启了 `prefetch` 则当用户将鼠标放到该组件上方时，Umi 就会自动开始进行跳转路由的组件 js 文件和数据预加载。

```jsx
<Link to="/url" prefetch>link</Link>
```

实际测试效果无效。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/afc163/umi-link-prefetch-bug

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

1. `git clone https://github.com/afc163/umi-link-prefetch-bug`
2. `cd umi-link-prefetch-bug && pnpm i`
3. `pnpm start` 并访问 http://127.0.0.1:8000/
4. 将鼠标 hover 到 Docs 上，观察 devtools 中的网络面板。

![Nov-19-2024 22-43-47](https://github.com/user-attachments/assets/4cb2f942-1886-46a7-88e1-dd5ccc671ace)

- 预期：鼠标 hover 到 docs 上时，`p__docs.async.js` 就会预加载。
- 实际：点击的时候才加载。

## Context

- **Umi Version**: 4.3.34
- **Node Version**: v22.8.0
- **Platform**: MacOS

**Comment by sorrycc** [comment]
看了下，

1、这功能需要加两个配置。

```ts
routePrefetch: {},
manifest: {},
```

2、但是加了之后目前也无法工作，之前的实现有问题，我需要调整下数据结构换一种实现。

**Comment by afc163** [comment]
4.3.35 好像还是有问题。

**Comment by afc163** [comment]
另外，routePrefetch 文档中找不到。

**Comment by afc163** [comment]
routePrefetch 开启时，Link 的 `prefetch` 默认为 true 如何？这样不用一个个去加。
