### ISSUE TITLE
约定式路由如何生成layout所需的嵌套菜单

### ISSUE THREAD

**Issue by senjyouhara** [umijs/umi#12801]
![image](https://github.com/user-attachments/assets/34ff4654-75e5-4f90-863b-28dc0bff864c)

![image](https://github.com/user-attachments/assets/7b15e9cc-9745-46df-801a-aaa45bfc7274)

我菜单结构是这样的，希望能生成这样的菜单，但因为约定式路由会进行扁平化导致生成的路由是这样

![image](https://github.com/user-attachments/assets/d983ba2c-602b-424d-a362-9c4824a0db1c)

如何能生成嵌套结构的菜单呢

layout配置如下
```
export const layout: RunTimeLayoutConfig = () => {
    return {
        title: config.title,
        logo: config.logo,
        layout: 'mix',
        fixedHeader: true,
        fixSiderbar: true,
        rightContentRender: () => <RightContent />,
        contentStyle: {
            padding: 16,
            height: `calc(100vh - 56px)`,
            overflow: 'auto',
        },
        // 其他属性见：https://procomponents.ant.design/components/layout#prolayout
    };
};
```

还有个问题如何约定菜单展示的排序

**Comment by jk4235** [comment]
菜单是你自己控制的,onClick的时候history.push到对应的路由就行了

**Comment by Taurues** [comment]
<img width="1249" alt="image" src="https://github.com/user-attachments/assets/b629698e-68c7-48b6-8a55-dd62b870fa0f" />
参考pro-layout组件这里自己配置路由，去自定义展示菜单。
