### ISSUE TITLE
[Bug] umi v4.3.36 丢失useAntdConfig, useAntdConfigSetter这两个hooks

### ISSUE THREAD

**Issue by Done-L** [umijs/umi#12826]
## What happens?

在使用useAntdConfig, useAntdConfigSetter两个方法时报错TypeError: (0 , umijs_max__WEBPACK_IMPORTED_MODULE_6_.useAntdConfigSetter) is not a function；
![image](https://github.com/user-attachments/assets/05683de1-ffea-4ed8-ba41-abcc5246af9e)

import * as UmiModule from 'umi'
console打印UmiModule里面没有这两个hook
![image](https://github.com/user-attachments/assets/d753670e-efd8-4d29-a392-d899ebd9b089)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: v4.3.36
- **Node Version**:v18.20.3
- **Platform**:

**Comment by xiaohuoni** [comment]
有重现嘛？是不是antd插件没用上？

**Comment by Done-L** [comment]
antd插件有用上的，依赖下载后引入打印就可以看到有没有了，后面我没再打印过，你们可以关注一下是否有这两个hook

**Comment by xiaohuoni** [comment]
未重现，有问题再 reopen
