### ISSUE TITLE
约定式路由，在有 _layout.js 时 layout.js 无效

### ISSUE THREAD

**Issue by wzxm** [umijs/umi#1283]

**Comment by wzxm** [comment]
![image](https://user-images.githubusercontent.com/13127730/47196705-736ddb00-d394-11e8-8dd1-e6e4f4a6c6bf.png)
![image](https://user-images.githubusercontent.com/13127730/47196711-7e287000-d394-11e8-83e3-d050e8b72aff.png)

**Comment by sorrycc** [comment]
没理解你的问题，`layout.js` 指哪个？
