### ISSUE TITLE
[Bug] UMI-MAX 引入monaco后本地开发异常，关闭mfsu后正常

### ISSUE THREAD

**Issue by cjianyu361** [umijs/umi#12830]
相关依赖
![image](https://github.com/user-attachments/assets/65c8d397-780d-4da6-96ee-e7950df6f59b)
相关配置
![image](https://github.com/user-attachments/assets/949959e3-5a87-4f89-bc48-045187dd5814)
异常
![image](https://github.com/user-attachments/assets/c146ef02-b92a-4b0f-bad8-3d01aa99be7e)

**Comment by Jinbao1001** [comment]
1.  删除 node_modules/.cache 文件测试下是否正常. 
2.  使用 mako: {}, 提升构建速度.
