### ISSUE TITLE
[Bug] 环境变量无法正常生效

### ISSUE THREAD

**Issue by xiaoxuehai** [umijs/umi#12836]
## What happens?
新增环境变量文件后，环境变量无法正常获取

## Mini Showcase Repository(REQUIRED)

![image](https://github.com/user-attachments/assets/3182946e-51fe-431d-8eee-e6a9fe3626a6)
![image](https://github.com/user-attachments/assets/8f18ffdd-22a0-422e-8e37-af15c924abe5)

## How To Reproduce

1.如上图，新增了.env.demo环境变量文件
2.启动命令中将REACT_APP_ENV和UMI_ENV设置为'demo'
3.在浏览器环境中通过process.env.UMI_APP_TEST_URL无法正常获取到环境变量，console.log(process.env.UMI_APP_TEST_URL)是undefined

## Context

- **Umi Version**: "@umijs/max": "^4.1.10"
- **Node Version**: 20.12.2
- **Platform**: windows

**Comment by sorrycc** [comment]
在源码里使用的环境变量，需要通过 define 配置传进去。路径是这样 package.json > .umirc.ts > src 。

**Comment by xbsheng** [comment]
可以试下这个插件，能实现你需要的功能~  ： https://www.npmjs.com/package/@xbsheng/umi-plugin-env
