### ISSUE TITLE
[Bug] 开启mako后 移除console的插件失效

### ISSUE THREAD

**Issue by consistent-k** [umijs/umi#12845]
## What happens?
开启mako后 移除console的插件失效  求问mako模式下应该怎么配置可以实现移除console 、注释等代码
搜了一下 npm https://www.npmjs.com/search?q=mako-plugin 没发现有什么插件 求问官方有配置项吗

## Mini Showcase Repository(REQUIRED)

![image](https://github.com/user-attachments/assets/d6c9d002-4978-40f7-847f-300fca6a837a)

## How To Reproduce

```ts
import { defineConfig } from '@umijs/max';

export default defineConfig({
    mako: {},
    extraBabelPlugins: ['transform-remove-console'],
});

```

## Context

- **Umi Version**: v4.3.36
- **Node Version**: v22.4.1
- **Platform**: Macos

**Comment by Jinbao1001** [comment]
rust 构建不支持 babel 插件
mako 官方 rust native 插件会在近期开放出来(目前在内部测试

**Comment by consistent-k** [comment]
> rust 构建不支持 babel 插件 mako 官方 rust native 插件会在近期开放出来(目前在内部测试

求问有可以用的插件了吗
