### ISSUE TITLE
路由path里配置外链

### ISSUE THREAD

**Issue by quanpower** [umijs/umi#1284]
在用umi与antd pro 2的时候，想在pro的菜单里点下跳转到其他后台。现在在pro的路由配置route.config.js配置如下      {
        path: '/status',
        icon: 'block',
        name: 'status',
        routes: [
          {
            path: 'http://www.baidu.com',
            name: 'configure',
            // component: './Status/Status',

          },

然而得到的route为：
exact: true
name: "configure"
path: "/status/http:/www.baidu.com"

修改哪里可以在判断为外链绝对路径的时候不再拼接路径，直接把设置的http://www.baidu.com返回？谢谢！

**Comment by sorrycc** [comment]
这个是 pro 实现 menu 时的问题，和 umi 没啥关系。
