### ISSUE TITLE
[Bug] 文档图表相关链接404

### ISSUE THREAD

**Issue by openapphub** [umijs/umi#12854]
## What happens?

网站上链接时效 404.

## Mini Showcase Repository(REQUIRED)

阅读umi max 文档，发现图表相关两个示例链接失效。

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

打开链接：https://umijs.org/docs/max/charts，[上手文档](https://charts.ant.design/zh/docs/manual/getting-started)和[图表示例](https://charts.ant.design/zh/examples/gallery)。 这两个链接失效

<img width="853" alt="image" src="https://github.com/user-attachments/assets/d2d46a05-dea5-4fa6-906a-eb0bbf545ab4" />

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by Jinbao1001** [comment]
感谢反馈, 已更正.
