### ISSUE TITLE
[Bug] 配置式嵌套不生效

### ISSUE THREAD

**Issue by Farley-Chen** [umijs/umi#12863]
## What happens?

当父路由中指定component时，嵌套子路由指定的component不生效

如

```typescript
routes: [
        {
            path: "/app",
            component: "./index",
            routes: [
                // 显示的组件仍然是./index
                {
                    path: "/app/docs",
                    component: "./docs"
                }
            ]
        },
        // 以下配置可以正常工作
        // {
        //     path: "/app",
        //     component: "./index",
        // },
        // {
        //     path: "/app/docs",
        //     component: "./docs"
        // },
    ],
```

## Mini Showcase Repository(REQUIRED)

[UMI嵌套路由不生效案例](https://github.com/Farley-Chen/umi-nested-route-minimal-reproducible-example.git)

## How To Reproduce

参见What happens?

## Context

- **Umi Version**: 4.4.2
- **Node Version**: v20.16.0
- **Platform**: windows11

**Comment by xiaohuoni** [comment]
组件中要用才能显示子组件，路由也是一样的。
https://github.com/Farley-Chen/umi-nested-route-minimal-reproducible-example/pull/1

**Comment by Farley-Chen** [comment]
> 组件中要用才能显示子组件，路由也是一样的。 [Farley-Chen/umi-nested-route-minimal-reproducible-example#1](https://github.com/Farley-Chen/umi-nested-route-minimal-reproducible-example/pull/1)

为啥案例上，父组件没有<Outlet/>，也能正确的路由？不是很理解

**Comment by Farley-Chen** [comment]
我是后端，对前端知识不是很熟

**Comment by Farley-Chen** [comment]
> 组件中要用才能显示子组件，路由也是一样的。 [Farley-Chen/umi-nested-route-minimal-reproducible-example#1](https://github.com/Farley-Chen/umi-nested-route-minimal-reproducible-example/pull/1)

我刚查了一下，好像Outlet是渲染嵌套路由组件用的，也就是说父路由本身不需要这个组件就能正确匹配嘛？

**Comment by Farley-Chen** [comment]
> 组件中要用才能显示子组件，路由也是一样的。 [Farley-Chen/umi-nested-route-minimal-reproducible-example#1](https://github.com/Farley-Chen/umi-nested-route-minimal-reproducible-example/pull/1)

我看了react router的文档，也就是说，我在umi中进行如下配置

```json
{
      path: "/app/docs",
      component: "./docs"
}
```
或者
```json
{
            path: "/app",
             // 这里去掉外面的component
            routes: [
                {
                    path: "/app/docs",
                    component: "./docs"
                }
            ]
}
```

本质上都是在react router里配置了一个父路由

而父路由，在react router中是可以直接匹配的，如果要渲染子路由对应的组件，需要在父路由中使用<Outlet/>作为占位符

所以向我之前那样会只渲染父路由组件，没有子路由组件
