### ISSUE TITLE
[Feature Request] targets should support browserslist

### ISSUE THREAD

**Issue by li-jia-nan** [umijs/umi#12867]
## Background

- https://github.com/react-component/father-plugin/pull/10

![image](https://github.com/user-attachments/assets/e8dfa98a-bed0-48e8-9bd5-41455613be70)

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by sorrycc** [comment]
Duplicated as https://github.com/umijs/umi/issues/12865
