### ISSUE TITLE
约定式路由的标题在使用路由切换动画时无法正确设置

### ISSUE THREAD

**Issue by Slebee** [umijs/umi#1287]
如题，在使用react-transition-group 或  rc-tween-one 时都会出现，刚切换的时候title是被正确设置了，但是动画结束后会被设置成default title,如：
默认标题:  头
A页( 标题：头A)
B页(标题: 头B)
A -> B 过程中，title变化  头A -> 头B -> 头
无法正确设置

**Comment by Slebee** [comment]
不知道怎么搞在线umi的demo
找到原因了，是因为pages下的index.js 的 Redirect 造成的
我上传了个最简化的代码[ umi-title](https://github.com/Slebee/umi-title)
这样一来还是有点蛋疼，通过 /访问默认页面的时候 Redirect还是需要的，还是说有其他写法可以避开？
@xiaohuoni @sorrycc

**Comment by sorrycc** [comment]
@yutingzhao1991 看下。

**Comment by sorrycc** [comment]
修复了，更新依赖试试。
