### ISSUE TITLE
build后umi.js可以不包含src下面的内容吗？

### ISSUE THREAD

**Issue by jayguojianhai** [umijs/umi#1291]
![image](https://user-images.githubusercontent.com/15603321/47279223-327afe00-d602-11e8-8530-96bd495e2068.png)
.umirc.js
/**
 * author     : jayguo
 * createTime : 2018-09-29 14:07
 */
const path = require("path");
export default {
  plugins: [
    ['umi-plugin-react', {
      antd: true,
      dva: {
        hmr: true,
      },
      title: 'mdt-web',
      dll: false,
      pwa: false,
      hardSource: false,
      locale: {
        default: 'zh-CN'
      },
      dynamicImport: {
        webpackChunkName: true,
        loadingComponent: './components/PageLoading',
      },
      chunks: ['vendors', 'umi'],
    }],
  ],
  chainWebpack(config) {
    config.optimization.splitChunks({
      cacheGroups: {
        vendors: {
          name: 'vendors',
          chunks: 'all',
          test: /[\\/]node_modules[\\/](react|react-dom|react-router|react-router-dom)[\\/]/,
        },
        commons: {
          name: 'commons',
          chunks: 'async',
          minChunks: 2,
          minSize: 0,
        },
      },
    });
  },
  define: {
    'process.env.hostname': 'http://202.101.157.220/',
  },
  alias: {
    '@utils': path.resolve(__dirname, 'src/utils/'),
    '@assets': path.resolve(__dirname, 'src/assets/'),
    '@components': path.resolve(__dirname, 'src/components/')
  },
  theme: {
    'base-color': '#6190E8',
    'base-header-bg': '#1646A2',
    'base-a-color': '#fff',
  },
  targets: {
    ie: 9,
  },
  routes: [
    {
      path: '/',
      component: '../layouts',
      routes: [
        {
          path: '/login',
          component: './login',
        },
        {
          path: '/moxtra/:meetId/:tid/:token/:type',
          component: './moxtra',
        },
        {
          path: '/home',
          component: './home',
        }
      ]
    }
  ],
  disableCSSModules: true,
  hash: true,
  ignoreMomentLocale: true,
}

**Comment by xiaohuoni** [comment]
@jayguojianhai 请问这个图怎么弄出来的？

**Comment by Renderz** [comment]
> @jayguojianhai 请问这个图怎么弄出来的？

ANALYZE=1 umi build

**Comment by sorrycc** [comment]
Duplicated #1290
