### ISSUE TITLE
less文件引用本地图片报错

### ISSUE THREAD

**Issue by TingHsi** [umijs/umi#1295]
**less文件引用本地图片报错**

=====问题的分割线=====

**编译报错图**
![image](https://user-images.githubusercontent.com/20589521/47287801-112c0900-d626-11e8-873b-270808c220be.png)

**本地代码**
![image](https://user-images.githubusercontent.com/20589521/47288059-fd34d700-d626-11e8-9779-999b7fe00926.png)

=====注释后的分割线=====

**尝试注释错误部分代码后**
![image](https://user-images.githubusercontent.com/20589521/47288120-42590900-d627-11e8-9465-8ab49dc4dfe9.png)

**编译通过**
![image](https://user-images.githubusercontent.com/20589521/47288111-38cfa100-d627-11e8-94b8-1d5c27ebaa0d.png)

=====npm start模式的分割线=====

**相同的代码在开发模式下并未抛错**
![image](https://user-images.githubusercontent.com/20589521/47288182-94019380-d627-11e8-8fad-e81955cb399b.png)

**使用浏览器控制台可以看到文件成功的转到了 static 下**
![image](https://user-images.githubusercontent.com/20589521/47288188-99f77480-d627-11e8-9359-3b4801c43e0f.png)

=====编译报错log文件的分割线=====

[2018-10-22T09_56_56_735Z-debug.log](https://github.com/umijs/umi/files/2500970/2018-10-22T09_56_56_735Z-debug.log)

**Comment by TingHsi** [comment]
翻了一下老的issue，看到 #165 里面说public会自动打包。

所以把资源从插件目录移到了public，编译成功了。

`  .pageType404{
    .imgEle {
      background-image: url('**/public/**404.svg');
    }
  }

  .pageType403{
    .imgEle {
      background-image: url('**/public/**403.svg');
    }
  }

  .pageType500{
    .imgEle {
      background-image: url('**/public/**500.svg');
    }
  }`


**但是CSS中引用的地址没有变成根目录**

![image](https://user-images.githubusercontent.com/20589521/47289218-43406980-d62c-11e8-9ff8-2d3bd4bd59d0.png)

而且插件中的文件分开存放维护性也不是很好。

**Comment by TingHsi** [comment]
还是 #165 里面说src里面需要被引用才会打包，所以绕了个弯子。

还真把问题把解决了


```
  .pageType404{
    .imgEle {
      background-image: url('../Exception/assets/404.svg');
    }
  }

  .pageType403{
    .imgEle {
      background-image: url('../Exception/assets/403.svg');
    }
  }

  .pageType500{
    .imgEle {
      background-image: url('../Exception/assets/500.svg');
    }
  }
```

![image](https://user-images.githubusercontent.com/20589521/47290119-8ef51200-d630-11e8-9672-0099147cf016.png)

**Comment by sorrycc** [comment]
试了下，不能重现，给个最简可复现的例子。

**Comment by sorrycc** [comment]
[sorrycc-aa6qGX.zip](https://github.com/umijs/umi/files/2503837/sorrycc-aa6qGX.zip)

**Comment by myGitZone** [comment]
您好，我在打包的时候，也碰到这个问题，发现是componets目录下面的组件中
![default](https://user-images.githubusercontent.com/19903630/47413714-a1db2400-d7a1-11e8-874d-2d47fd111cdc.png)。就会报错，找不到图片资源，将图片放到src目录的assets中就可以

**Comment by sorrycc** [comment]
@myGitZone 传一个可复现的例子上来。

**Comment by myGitZone** [comment]
[ceshi.zip](https://github.com/umijs/umi/files/2509531/ceshi.zip)
您好，这是我自己写的一个简单例子,当组件文件中通过background: url(./images/navbg.png);加载图片，开发环境下是没问题的，只有打包的时候会报错，找不到文件

**Comment by sorrycc** [comment]
删除 config/config.js 里的 cssnano 配置。

**Comment by myGitZone** [comment]
谢谢。麻烦了
