### ISSUE TITLE
其它服务器直接引用 umi 资源的时候热更新会请求失败

### ISSUE THREAD

**Issue by yutingzhao1991** [umijs/umi#1298]
比如我在 http://127.0.0.1:7001 上面引用 umi 的 js  http://127.0.0.1:8000/umi.js 这时候热更新会去请求 http://127.0.0.1:7001 导致报错。

希望热更新的地址能够不受到服务器的地址影响。

**Comment by sorrycc** [comment]
试试。

```bash
$ SOCKET_SERVER=http://127.0.0.1:8000/ umi dev
```

**Comment by Instanced** [comment]
似乎没有效果啊 ，

**Comment by Instanced** [comment]
发现关闭 `hardSource` 便可以了。
