### ISSUE TITLE
动态路由跳转的问题

### ISSUE THREAD

**Issue by Dollyn** [umijs/umi#1300]
典型的列表详情页面，路由 /article/details/:id
在列表页面用Link可以正常跳转，
但是在详情页面如果要跳转到相关的另外一个artile的详情的话，没有反应，
例如 在/article/details/0 页面上有一个链接   /article/details/1
点这个链接是没有用的

可能是因为同一个组件的原因， 可能只能通过监听地址变化来刷新了，但是找不到相关的文章，dva对subscrib讲的也非常简单了，能否有人提供一个监听地址变化的几行代码？

**Comment by sorrycc** [comment]
请提醒可复现例子。

**Comment by Dollyn** [comment]
我们的项目是在antd-pro上改的，尝试在umi-examples/routes/ 基础上修改，

users/$id$.js
```
import { Link } from 'umi/link'

export default ({ match }) =>
  <div>
    <h1>/users/{match.params.id}</h1>
    <Link to="/users/123">/users/123</Link>
  </div>

```

只是加了一个Link，直接就报错了。
半路出家的，可能我犯了个低级错误？

**Comment by Dollyn** [comment]
根据目前的研究，可能不是Link本身的问题？ url是成功变了，但是因为是同一个component，没有触发componentDidMount()，所以没有重新去fetch数据，所以用Link组件是不行的。 

如果自己router.push, 并且同时自己dispatch去获取数据的话，按浏览器的回退按钮的时候又不能重新获取了。 所以我觉得可能需要监听地址栏的变化，想知道有没有关于这种场景的最佳实践？

在antd-pro基础上的复现：
1. git clone https://github.com/ant-design/ant-design-pro.git route-example
2. 修改config/router.config.js:
```
      {
				path: '/article',
				name: 'article',
				icon: 'profile',
				routes: [
					{ path: '/article', redirect: '/article/overview' },
					{
						path: '/article/overview',
						name: 'overview',
						component: './Article/Overview',
					},
					{
						path: '/article/details/:id',
						name: 'details',
						component: './Article/Details',
						hideInMenu: true
					},
				]
			},
```

3. 添加相关的文件
目录结构：
```
src/pages/Article/
src/pages/Article/Detail.js
src/pages/Article/Overview.js
src/pages/Article/models
src/pages/Article/models/article.js
src/pages/Article/models/details.js
```
相关文件的代码：
[article.zip](https://github.com/umijs/umi/files/2513386/article.zip)

**Comment by chenshuai2144** [comment]
监听 props 里面的 params修改就好了。

**Comment by Dollyn** [comment]
@chenshuai2144 怎么监听有没有文档或者示例代码可以参考？

**Comment by Dollyn** [comment]
找不到监听props的方法， 最终用了subscriptions监听地址的方法来实现的。
在models中添加

```
effects: {...},
reducers: {...},
subscriptions: {
		setup({ dispatch, history }) {
			history.listen(({ pathname }) => {
				const match = pathToRegexp('/article/details/:id').exec(pathname);
				if (match) {
					const id = match[1];
					// dispatch action with userId
					dispatch({
						type: 'fetch',
						payload: {id}
					});
				}
			});
		},
	},
```

**Comment by chenshuai2144** [comment]
componentDidUpdate

**Comment by ouzhou** [comment]
想了一下我还是用了在model里监听url变化用pathToRegexp去取值
因为我感觉在组件的componentDidUpdate调用反而很复杂，要满足组件只能在加载时调用dispatch，同时在同个组件下不调用多次

**Comment by ouzhou** [comment]
componentDidUpdate也可能会导致调用多次

**Comment by wfnuser** [comment]
我觉得用useEffect写起来会很简单
