### ISSUE TITLE
如何配置404.js呢

### ISSUE THREAD

**Issue by blllld** [umijs/umi#1301]
按照约定式路由，在 /src/pages下添加/404.js，在用serve预览时，并不能配置成功
并且除了index页面，其他页面也不能显示。
望告知

**Comment by blllld** [comment]
![404](https://user-images.githubusercontent.com/43157877/47340434-cadfb400-d6d0-11e8-9467-1d9e90a92ca1.png)
![image](https://user-images.githubusercontent.com/43157877/47340450-dc28c080-d6d0-11e8-8ed7-00b317be4e74.png)
![image](https://user-images.githubusercontent.com/43157877/47340458-e2b73800-d6d0-11e8-8af8-37455666071e.png)

**Comment by sorrycc** [comment]
参考 https://umijs.org/zh/guide/faq.html#build-%E5%90%8E%E8%AE%BF%E9%97%AE%E8%B7%AF%E7%94%B1%E5%88%B7%E6%96%B0%E5%90%8E-404%EF%BC%9F

**Comment by ouweiya** [comment]
我这时这样, 就不是跳到自定义 404页面, 感觉被戏弄了!
