### ISSUE TITLE
关于同类型项目，必须每个项目都下载引用包node_modules的问题，是否可以开放包共享？

### ISSUE THREAD

**Issue by breathss** [umijs/umi#1305]
![image](https://user-images.githubusercontent.com/12314536/47349666-aa225900-d6e6-11e8-857c-5c08dc7e2906.png)
[](url)

操作一个项目要下载很大的包，其实引用包内容都是一致的，
请问有没有什么解决思路，我用umi已经有一段时间了，这个问题现在一直困扰着我。。

**Comment by xiaohuoni** [comment]
lerna

**Comment by breathss** [comment]
之前用yarn workspaces 来实现类似的操作，发现umi 取react 及相关部分，是指定了目录的，
这块针对node_modules 路径获取，能不能抽象出来一个参数来指定获取，我在umi 的webpack 设置也做了处理，发现打包时直接就卡死不动了、
请问有没有计划做这部门的一个功能？

**Comment by dkvirus** [comment]
这是 npm 包管理器的问题吧，不像 maven 有本地公用仓库。。
npm 社区开了一个新工程 tink，说是npm升级版本的包管理器，貌似有想法整本地公用仓库的意思。

**Comment by breathss** [comment]
> 这是 npm 包管理器的问题吧，不像 maven 有本地公用仓库。。
> npm 社区开了一个新工程 tink，说是npm升级版本的包管理器，貌似有想法整本地公用仓库的意思。
是啊，全部放全局又可能会有版本冲突、局部的共性没法体现。。

**Comment by sorrycc** [comment]
有多种方案，可以多试试，

* lerna
* yarn workspace
* yarn pnp

**Comment by huxiaoqiao** [comment]
请问有解决方案吗？
