### ISSUE TITLE
子页面的model加载不出来，找不到

### ISSUE THREAD

**Issue by yf900914** [umijs/umi#1306]
文件结构如下图
![image](https://user-images.githubusercontent.com/21993568/47357287-d515a880-d6f8-11e8-820f-f3b27302d6bf.png)
找不到的模块是
![image](https://user-images.githubusercontent.com/21993568/47357344-fececf80-d6f8-11e8-88a0-47b922340d7c.png)

platformMonitor.js与sourceMonitor.js都是SystemMonitor的两个子页面，路由的配置是‘/dashboard/systemMonitor/platform’和‘/dashboard/systemMonitor/source’，
![image](https://user-images.githubusercontent.com/21993568/47399975-bbfb0f00-d76d-11e8-8f77-46627b87adc4.png)
这个model的namescape: 'platformMonitor',state中定义了变量hardwareList,在子页面
![image](https://user-images.githubusercontent.com/21993568/47400020-0a101280-d76e-11e8-8d8d-032ac64aea66.png)
中通过下面的方是引入
![image](https://user-images.githubusercontent.com/21993568/47400121-6b37e600-d76e-11e8-9c76-a27f3d64c53c.png)
最终页面总是hardwareList为undentifid,models 的设置是按照文档中描述设置的
![image](https://user-images.githubusercontent.com/21993568/47400203-d2559a80-d76e-11e8-908b-27ec52194425.png)

**Comment by breathss** [comment]
开发的时候没有问题。貌似我在发布编译的时候，这种子model 会报异常，只有放到公用的models才解决这个问题的，

**Comment by shirleyYing** [comment]
没有跨路由使用，

**Comment by lmikoto** [comment]
同样遇到这个问题，请问你解决了吗 @shirleyYing

**Comment by 104gogo** [comment]
+1。感觉是目录层级深了没也找到 model，换个位置就找到了。
