### ISSUE TITLE
jekins 编译环境 webpack 输出 会有大量以下格式信息，能关闭吗？

### ISSUE THREAD

**Issue by mrzzcn** [umijs/umi#1309]
> ant-design-pro@2.1.0 build /var/jenkins_home/workspace/f2e/beta/pc-business-platform
> umi build

Compiling

● webpack █████████████████████████ compiling (0%)  
 

(node:31216) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
Compiling

● webpack █████████████████████████ building modules (10%) 1/2 modules 1 active
  babel-loader › src/pages/.umi-production/umi.js

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
Compiling

● webpack █████████████████████████ building modules (10%) 2/2 modules 0 active
 

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
Compiling

● webpack █████████████████████████ building modules (10%) 2/7 modules 5 active
  babel-loader › src/pages/.umi-production/initHistory.js

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
Compiling

● webpack █████████████████████████ building modules (10%) 3/9 modules 6 active
  node_modules/umi-plugin-dva/lib/runtime.js

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
Compiling

● webpack █████████████████████████ building modules (10%) 3/10 modules 7 active
  node_modules/@babel/runtime/helpers/interopRequireDefault.js

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
Compiling

**Comment by okoala** [comment]
设置 CI=true 的环境变量

**Comment by mrzzcn** [comment]
Ths!
