### ISSUE TITLE
hd px2rem 内联样式无效

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#1312]
主要代码：
```js
export default {
  plugins: [
    [
      "umi-plugin-react",
      {
        dva: true,
        antd: true,
        hd: true,
      }
    ]
};
```
```html
<div>
    <div
      style={{
        fontSize: "66px"
      }}
    >
      Index Page
    </div>
    <div className={styles.nom}>Index Page</div>
  </div>
```
```css
.nom{
    font-size: 66px
}
```
<img width="338" alt="wx20181024-144953 2x" src="https://user-images.githubusercontent.com/11746742/47411696-2cb92000-d79c-11e8-8fb2-5d49cb581d39.png">

[重现demo](https://github.com/umi-cli-test/hd-no-work)

**Comment by sorrycc** [comment]
内联样式覆盖不到的，不走 postcss 。

**Comment by xiaohuoni** [comment]
@sorrycc 能不能在js或jsx之前做处理。不然实际使用中很奇怪

**Comment by sorrycc** [comment]
做不了，js 不走 postcss 的。

**Comment by xiaohuoni** [comment]
在webpack，/.(js|jsx)?$/这样babel-loader之前（webpack从右往左）加一个loader把需要转变的px进行替换，这里有一个方案https://www.jianshu.com/p/83bb5e97bdf3

**Comment by xiaohuoni** [comment]
@sorrycc

**Comment by sorrycc** [comment]
我觉得先不用支持这种场景，最佳实践是写在 css 文件里，有需要可以实现一个 umi 插件来做。

**Comment by LukerSpringtree** [comment]
哈哈哈

**Comment by GKLL** [comment]
最后是怎么解决内联样式的呢

**Comment by xiaohuoni** [comment]
@GKLL 我们这里现在是不让自己写，如果真的需要动态的，用工具类自己转了下 rem 单位
