### ISSUE TITLE
umi 类似vue inspect的功能

### ISSUE THREAD

**Issue by luxueyan** [umijs/umi#1314]
我想查看完整webpack配置，好通过chainwebpack配置一下个性化功能

**Comment by xiaohuoni** [comment]
先看vue的实现，主要是打印了webpack配置，根据参数，对配置做了过滤
![default](https://user-images.githubusercontent.com/11746742/47496081-6d8e6300-d888-11e8-8194-f24a48d60c8e.png)

**Comment by xiaohuoni** [comment]
umi是不是除了上面的功能，需不需要再增加其他的。
比如：
- cwd: 运行脚本的地址,
- pkg:项目package.json
- commands:所有以注册的命令行
- pluginHooks:插件钩子
- pluginMethods:插件方法
- config:umi配置
- plugins:用到的插件

**Comment by xiaohuoni** [comment]
感觉插件的两个清单，在编写插件的时候，会很有用处。
- pluginHooks:插件钩子
- pluginMethods:插件方法
其他我罗列的，感觉没什么用，都可以在项文件中查看
