### ISSUE TITLE
是否支持将 JS 和 CSS 打包到不同的文件夹

### ISSUE THREAD

**Issue by MillionQW** [umijs/umi#1316]
现在打包出来的文件都是和index.html在同一个目录，可不可以修改配置，让 JS文件 打包到 JS 文件夹，CSS文件打包到 CSS 文件夹？

**Comment by sorrycc** [comment]
暂不支持。

**Comment by MillionQW** [comment]
了解了，想再问问，现在打包出来的 index.html 里 umi.js 和 umi.css 的引入路径是 "/umi.css"，有没有办法改成 "./umi.css"呢？

**Comment by JaymzZh** [comment]
v4 有支持这个么？

**Comment by fz6m** [comment]
umi 4 不支持 js 和 css 打包到不同的文件夹，不能自定义产物结构。

**Comment by xiaoxuehai** [comment]
2025了    现在支持了吗  这么简单一个功能  很多人都提issue了
