### ISSUE TITLE
请问一下 extraBabelPlugins 这个属性有没有详细说明

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#1317]
然后没有转成es5的库，除了pr到es5-imcompatible-versions这个项目，之外还有没有什么方法，通过配置，达到同样的效果。
现在是有一个自己写的测试库，没有转es5。

**Comment by sorrycc** [comment]
配 extraBabelIncludes，参考 https://umijs.org/config/#extrababelincludes

**Comment by xiaohuoni** [comment]
@sorrycc 试过了，修改node_modules/es5-imcompatible-versions/package，项目可以正常运行。配置extraBabelIncludes,运行时报错
```base
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-plugin-whale-rn' from '/Users/xiaohuoni/
Documents/GitHub/Killer-Whale'
```
其中whale-rn是我的测试库名字

**Comment by sorrycc** [comment]
extraBabelIncludes 里项的内容参考 https://webpack.js.org/configuration/module/#condition 。

**Comment by xiaohuoni** [comment]
有用例吗？配置
```js
extraBabelPlugins:[{
    test: /whale-rn$/
  }]
```
又报错，不知道这个结构该怎么写
```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/xiaohuoni/Documents/GitHub/Killer-Whale/src/pages/.umi/umi.js: .test is
 not a valid Plugin property
```

**Comment by sorrycc** [comment]
是 `extraBabelIncludes`。

**Comment by xiaohuoni** [comment]
```
extraBabelIncludes:[/whale-rn/]
```
配置如上处理了

**Comment by shengbeiniao** [comment]
extraBabelIncludes没用，只监听了jsx文件，[umi source](https://github.com/umijs/umi/blob/76f151d3f491d22946e0abe43fa6049823a01b8a/packages/af-webpack/src/getConfig/index.js#L209)一个有用的配置


子应用umi配置
```
  chainWebpack: (config => {
    // 编译components目录
    config.module.rule('js').include.add(path.resolve(__dirname,'../components/src'))
  }),
```
微前端开发，采用yarn workspace

components，package.json设置main为src/index.js

**Comment by vecold** [comment]
import path from 'path';
extraBabelIncludes: [
    path.resolve(__dirname, '../node_modules/../../../.........../xxxx.js')
  ],
 
 hope helps guys
