### ISSUE TITLE
React 16.6 出现 Cannot read property 'displayName' of null

### ISSUE THREAD

**Issue by fattypanda** [umijs/umi#1319]
**- 安装 react@16.6.0 之后出现以下问题**
![qzpcvxnlcnncrmf0dhlqyw5kyvxbchbeyxrhxfjvyw1pbmdcrgluz1rhbgtcmjkxotu3ndaxx3yyxeltywdlrmlszxncmtu0mdqznzk3mdy2nf9dmzc2mjmwoc1cqta3ltriogetqundri05q0e1rke4rdrbmjiucg5n](https://user-images.githubusercontent.com/17585231/47474562-123d8000-d84a-11e8-8131-ef5aaae19792.png)
![qzpcvxnlcnncrmf0dhlqyw5kyvxbchbeyxrhxfjvyw1pbmdcrgluz1rhbgtcmjkxotu3ndaxx3yyxeltywdlrmlszxncmtu0mdqznzk3mdy3nl81muyxqkyzqs1dnejgltq2otqtoeu0qi01mthgmtmyrtg1q0qucg5n](https://user-images.githubusercontent.com/17585231/47474565-14074380-d84a-11e8-9c84-1ccb408b9145.png)
**- react@16.5.2 并无问题**
![qzpcvxnlcnncrmf0dhlqyw5kyvxbchbeyxrhxfjvyw1pbmdcrgluz1rhbgtcmjkxotu3ndaxx3yyxeltywdlrmlszxncmtu0mdqzoda3nzgxnl8zm0ixn0q3ni1dqtuxltriytgtodywqy05odu1mjk1mkqxq0eucg5n](https://user-images.githubusercontent.com/17585231/47474574-22555f80-d84a-11e8-9807-067f9345d428.png)
**- 问题原因分析**
react-devtools 在获取组件名称时失败而导致的异常，不影响代码使用，但会导致无法使用 react-devtools

**Comment by sorrycc** [comment]
react-dev-tools 问题，在 https://github.com/facebook/react-devtools/pull/1175 跟进吧。
