### ISSUE TITLE
访问根目录跳转后如何带上params

### ISSUE THREAD

**Issue by zonzpoo** [umijs/umi#1321]
访问的url为http://127.0.0.1/?code=xxxx
经过： { path: '/', redirect: '/dashboard/analysis' } 
直接跳转到http://127.0.0.1/dashboard/analysis

请问在config上如何配置才能跳转后带上code=xxx ，变成http://127.0.0.1/dashboard/analysis?code=xxxx
或者在跳转前能取到code的值先做处理？

thanks!

**Comment by xiaohuoni** [comment]
这个应该要手动处理
