### ISSUE TITLE
SSR & Pre Rendering 方案

### ISSUE THREAD

**Issue by xiaoiver** [umijs/umi#1330]
## SSR

相关 [ISSUE](https://github.com/umijs/umi/issues?utf8=%E2%9C%93&q=ssr)：[#377](https://github.com/umijs/umi/issues/377) [#628](https://github.com/umijs/umi/issues/628)

### 使用方法

首先通过 `umi-plugin-ssr` 插件开启 SSR 功能：
```js
// .umirc.js

plugins: [
    ['umi-plugin-ssr', {
        // nodeExternalsWhitelist: []
        // 其他配置项待定
    }],
]
```

然后在服务端脚本中使用插件暴露的 `express` 或者 `koa` 中间件：

```js
// server.js

const { render } = require('umi-plugin-ssr');
const app = require('express')();

// 启动 Umi，这里可能需要暴露 API
// 例如：umi.start();

// 使用中间件
app.use(render);
```

### 实现思路

重要的修改包括：
* 在已有 `ClientEntry` 的基础上新增针对 `ServerEntry` 的 Webpack 构建流程，修改 `target: 'node'` `output.libraryTarget: 'commonjs2'`等等
* 服务端**预取数据**。在页面组件中引入约定好的生命周期钩子。例如 Nuxt 中的 [`asyncData()`](https://nuxtjs.org/api/)，Next 中的 [`getInitialProps()`](https://nextjs.org/learn/basics/fetching-data-for-pages)
* 使用 [ReactDOMServer](https://reactjs.org/docs/react-dom-server.html)，将初始状态 `initialState` 注入 HTML
* 在 Client 端 dva 同步初始状态 `initialState`，进行 [`hydrate()`](https://reactjs.org/docs/react-dom.html#hydrate)

可能遇到的问题：
* 目前 Umi 只能通过命令启动构建，可能需要**暴露可编程使用的 API**？
* 在 SSR 模式下，通常我们不希望将 `node_modules` 中的依赖打包进 server bundle 中，因此需要使用 Webpack `externals` 配置项。但是在某些场景下，我们还是需要将部分特定的依赖打包进来，这时就需要使用白名单了。例如在服务端渲染场景下常常遇到的一个问题是，某些第三方依赖使用了 `document`, `window` 这样在 Node.js 环境中不存在的对象。为了保证服务端渲染正常运行，通常使用 `resolve.alias` 引导 Webpack 使用空的 stub 对象，此时一定要同时在 `nodeExternalsWhitelist` 中加入该依赖。
* 配合 PWA 中 ServiceWorker 使用时，不同于 SPA 只有一个 HTML，不可能把每个页面都加进预缓存列表。之前在 [Vue SSR 中使用 ServiceWorker](https://xiaoiver.github.io/coding/2017/11/12/SSR-%E4%B8%AD%E7%9A%84%E7%A6%BB%E7%BA%BF%E5%8F%AF%E7%94%A8-%E4%B8%89.html) 时整理了一些通用的思路。

## Pre Rendering

某些 SPA 中存在一部分需要 SEO 的重要静态页面，并不需要做整站 SSR。
Pre Rendering 本身依赖于 SSR 方案，在构建时将路由静态化成为对应的 HTML 文件。

使用方法的话可以在约定/配置式路由基础上扩展。
```js
/**
 * title: Index Page
 * prerender: true
 * Routes:
 *   - ./src/routes/a.js
 *   - ./src/routes/b.js
 */
```

## 参考资料

[Nuxt 中的 PreRender](https://nuxtjs.org/guide#static-generated-pre-rendering-)
[Vue SSR 中使用 ServiceWorker](https://xiaoiver.github.io/coding/2017/11/12/SSR-%E4%B8%AD%E7%9A%84%E7%A6%BB%E7%BA%BF%E5%8F%AF%E7%94%A8-%E4%B8%89.html)

**Comment by xiaohuoni** [comment]
关注

**Comment by DomenLee** [comment]
及时雨

**Comment by devmsg** [comment]
repost

**Comment by anshengme** [comment]
关注下

**Comment by HaishengLiang** [comment]
Mark

**Comment by ClarkXia** [comment]
关注SSR方案

**Comment by i5ting** [comment]
ssr中间件有2种解法

1）获得res.locals.webpackStats

通过webpack-dev-server用的webpack-dev-middleware，配置

app.use(middleware(compiler, { serverSideRender: true }))

因为umi内置了webpack-dev-server，如果我能够获得webpackStats，就不需要获得webpack config

如果大家有好想法也可以试试

2）通过代码去获取webpack config。

原理跟umi inspect原理一样。

// 获取webpack配置信息
const webpackConfig = require('umi-build-dev/lib/getWebpackConfig').default(service);

const compiler = webpack(webpackConfig);

// 测试webpack执行情况
compiler.run((err, stats) => {/* ...处理结果 */
  if (err) console.dir(err)

  console.dir(stats)
})

通过这种方法能够取到compiler，已实现

**Comment by afc163** [comment]
+1

Pre Rendering 对于 h5 和静态 landing 站点的 SEO 和性能意义巨大。

**Comment by okoala** [comment]
同构最麻烦的一点就是数据在页面上是 double 的，一份是原 json 数据，一份是渲染好的数据。

**Comment by ibmsoft** [comment]
有没有支持的时间节点呢？

**Comment by ycjcl868** [comment]
+1 Watching，PreRendering 能满足大部分对外站点，可参照 [gatsby](https://www.gatsbyjs.org/)

![image](https://user-images.githubusercontent.com/13595509/52607148-287e5300-2eb0-11e9-9856-ac88b34bbd55.png)

**Comment by ql434** [comment]
mark

**Comment by superbogy** [comment]
强烈的需求啊

**Comment by i5ting** [comment]
这几天在折腾midway和umi整合，尽快放出来一个版本

**Comment by anshengme** [comment]
@i5ting 狼叔有实现umi的SSR嘛？

**Comment by superbogy** [comment]
保持关注

**Comment by chiaweilee** [comment]
👍

**Comment by awakenin** [comment]
关注着

**Comment by smithyj** [comment]
期待 umi ssr 啊

**Comment by perany** [comment]
mark,期待！

**Comment by perany** [comment]
求umi整合SSR的demo

**Comment by furylee** [comment]
两个月过去了,有什么音信没

**Comment by i5ting** [comment]
@furylee 已经实现了，pr在内部review

**Comment by hanwenbo** [comment]
@i5ting 狼叔威武  等待体验ing....

**Comment by wangxingkang** [comment]
关注

**Comment by zadzbw** [comment]
快点出吧 next.js缺陷很多啊

**Comment by hpf1908** [comment]
预计什么时候放出来呢？很需要ssr

**Comment by jinfei** [comment]
期待ssr

**Comment by zhangyuang** [comment]
mark
内部review中

**Comment by chenqincheng** [comment]
关注中，希望早点放出来。狼叔牛批

**Comment by HadiChen** [comment]
mark，期待中

**Comment by laketea** [comment]
mark

**Comment by BosenY** [comment]
mark

**Comment by shizhiqian** [comment]
mark

**Comment by philina** [comment]
期待ing，狼叔威武

**Comment by ycjcl868** [comment]
@philina 已经发布了    
docs: https://umijs.org/zh/config/#ssr
demo: [umi-example-ssr-with-egg](https://github.com/umijs/umi-example-ssr-with-egg) [umi-example-ssr](https://github.com/umijs/umi-example-ssr)
