### ISSUE TITLE
umi build 出现 insert google analysis

### ISSUE THREAD

**Issue by ZevveZ** [umijs/umi#1331]
umi dev不会有这个问题，如何在umi build 的时候移除google analysis？

**Comment by sorrycc** [comment]
umi 应该没有加 `google analysis`，你是不是配了 https://github.com/umijs/umi-plugin-ga ?

**Comment by sorrycc** [comment]
https://github.com/umijs/umi-plugin-ga/blob/03735781a2e13aeb1bc0363064f9993b1ffb76ab/src/index.js#L8

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/issues/2672
