### ISSUE TITLE
使用UMI这个框架开发，在使用git提交代码，总是会出现这个错误

### ISSUE THREAD

**Issue by srrrr** [umijs/umi#1332]
![image](https://user-images.githubusercontent.com/5070841/47542868-f43b5280-d911-11e8-85b9-965ce3969888.png)
只有把.git\hooks\pre-commit删掉才能提交，是怎么回事？

**Comment by xiaohuoni** [comment]
这个与umi无关。代码规范问题，你项目里面运行，npm run precomit,能看到详细的修改意见
