### ISSUE TITLE
如何更改部署路径?

### ISSUE THREAD

**Issue by top-soft** [umijs/umi#1341]
一台nginx跑多个不同的前端项目，html/project1,html/project2 ...  通过上层nginx去做分发
刚接触umi，运行build打出的文件 看了下路径只能部署在/下面，请问如何配置，支持部署路径?
nginx-1.14.0\html\project1
1.async.js
 1.chunk.css
2.async.js
2.chunk.css
index.html
static/
umi.css
umi.js

通过http://localhost:80/project1访问

**Comment by sorrycc** [comment]
参考 https://umijs.org/guide/deploy.html

**Comment by pkaq** [comment]
@sorrycc  亲测 配置项无论如何更改 输出的html中均为 /umi.css
