### ISSUE TITLE
引用 svg 作为 react 组件输出，会提示：React无法识别DOM元素上的`pId`

### ISSUE THREAD

**Issue by lvzegeng** [umijs/umi#1344]
index.js:2178 Warning: React does not recognize the `pId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `pid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by sorrycc** [comment]
请提供可复现的库。

**Comment by sorrycc** [comment]
有问题再 reopen 。

**Comment by tab16360** [comment]
的确，icon svg是从iconfont下载的
import { ReactComponent as DingweiSVG } from 'assets/img/dingwei.svg';
...render () {
...<DingweiSVG height={15} width={15}/>...
}

console警告：
index.js:2178 Warning: React does not recognize the `pId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `pid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by AttackXiaoJinJin** [comment]
将所有svg里的p-id属性全部去掉就可以了
