### ISSUE TITLE
How to provide extraReducers and extraEnhancers when using umi-plugin-dva?

### ISSUE THREAD

**Issue by robert-claypool** [umijs/umi#1347]
My application is a fork of Ant Design Pro v2, therefore it depends on dva, and dva is loaded with `umi-plugin-dva`.

Now I want to provide additional reducers from [`kepler.gl`](https://github.com/uber/kepler.gl/blob/master/README.md#basic-usage), and it seems that [`extraReducers`](https://github.com/dvajs/dva/blob/master/docs/API.md#extrareducers) is the way:

```JavaScript
import keplerGlReducer from 'kepler.gl/reducers';
const app = dva({
  extraReducers: {
    kepler: keplerGlReducer,
  },
});
```

Likewise, I need to provide `extraEnhancers`.

Is this possible when using `umi-plugin-dva`? Do we have access to `extraReducers` and `extraEnhancers` properties if `umi-plugin-dva` loads and configures dva?

**Comment by xiaohuoni** [comment]
you can use dva-plugin in `src/dva.js`.
you can see [with-dva/src/dva.js](https://github.com/umijs/umi-examples/blob/master/with-dva/src/dva.js)

**Comment by xiaohuoni** [comment]
```js
import { message } from 'antd';

export function config() {
  return {
    extraReducers: {
        form: formReducer,
    },
  };
}
```

**Comment by xiaohuoni** [comment]
@robert-claypool 
https://github.com/umijs/umi/issues/249
