### ISSUE TITLE
启用hd方案后，移动端适配有问题。

### ISSUE THREAD

**Issue by hopperhuang** [umijs/umi#135]
启用hd方案后，css文件，写入宽度750px，在chrome浏览器中调试，ipone7plus等大屏幕手机，并没有铺满屏幕。Galaxy5s小屏幕手机却宽度过大。

ip 7 plus 下的表现：

![yht0il7 0whrx m9yr dmc](https://user-images.githubusercontent.com/20254356/36591118-e228151c-18cb-11e8-96a8-1ecea8c5fb38.png)

元素宽度：1125px
![j_od _6785nv 2y4u8 cj1t](https://user-images.githubusercontent.com/20254356/36591200-298d6a7e-18cc-11e8-8580-4f02020a693c.png)

而页面的总宽度（document.documentElement.clientWidth）为1242px (414 * 3)

css样式正确转为 750px 已成功编译转化为7.5rem

glaxy5s下的表现:
![_ cf9 k ki sk xd s70tf](https://user-images.githubusercontent.com/20254356/36591282-78f8a9ac-18cc-11e8-95f9-c6c98674de67.png)

元素宽度： 1125px
而页面的宽度（document.documentElement.clientWidth）只有1080px(360 * 3)

epxected: 在css文件写入width: 750px，在移动端，元素会铺满整个屏幕的宽度。

初步猜想为baseFontSize的计算有问题。
在ip 7 plus下，将html标签的font-size改写成：165.6px(150 * 414/375)，7.5rem为满屏。
表现如下：
![image](https://user-images.githubusercontent.com/20254356/36591605-805030f2-18cd-11e8-9b2f-9fccf7859071.png)

页面宽度为1242px

查看了umi中Hd方案的源码： https://github.com/umijs/umi/tree/master/packages/umi-build-dev/src/plugins/hd/template

在ip7 plus的情况下，如果按照vw.js的方法去setFontSize将会得到正确的base-font-size
docEl.style.fontSize =_baseFontSize / _psdWidth * docEl.clientWidth * rate + 'px' = 100 / 750 * 414 * 3 = 165.6
如果按照flex.js的方法去setFontSize将会得到
 doc.documentElement.style.fontSize = _baseFontSize / 2 * dpr * _fontscale + 'px' = 100 / 2 * 3 * 1= 150

ip7 plus的baiseFontSize 为 150px

![image](https://user-images.githubusercontent.com/20254356/36591886-6112636c-18ce-11e8-8472-ed79ca80aedb.png)

也就是说，view.js中的代码并没有生效。

在galaxy5s中也是这样，baseFontSize也是150px

在index.js中，会进行一个条件判断，根据条件来setFontSize

```
if (document.documentElement.clientWidth >= 750) {
  vw(100, 750);
} else {
  flex();
}
```

疑惑的是，为什么要判断clientWidth是否大于750呢？是否这个判断条件导致，所有适配方案都只走了flex.js而，没有跑vw.js的代码，而产生的Bug呢？？

**Comment by sorrycc** [comment]
问了下无线的同学 750 哪来的，得到的回答是 "iphone6页面宽度。iOS 两倍分辨率"，这是我们内部的默认搞定方案，后面还会支持其他的方式，参考 #99

**Comment by hopperhuang** [comment]
@sorrycc  要确定的问题是，是否这个条件判断导致了vw.js的代码并没有走呢？如果走了vw.js的代码的话，算出来的rem值应该是正确的。ip7 plus的rem是165.6，galaxy5s的rem值是144。现在是，无论什么机型，只根据dpr去算rem（明显是走flex.js的代码)，3倍屏幕的rem就是3/2*100 = 150。

**Comment by sorrycc** [comment]
在 #99 跟进。

**Comment by xiaohuoni** [comment]
@fangk https://github.com/umijs/umi/issues/387

**Comment by xiaohuoni** [comment]
> document.documentElement.clientWidth >= 750
> 这个 clientWidth 我怀疑如果页面先设置了 viewport, 会导致判断错误.
这句话让我想起来，之前做h5游戏的时候，游戏是放在iframe中运行的，当iframe中的viewport和外层的viewport不同时会有适配问题。

**Comment by watsonhaw** [comment]
@hopperhuang 您现在还怎么处理这个问题的，我也是用了6/7/8plus来测试但是得到的都是150px的font-size

**Comment by bobbychan** [comment]
@watsonhaw 我的解决方法是把document.ejs里的viewport删掉就正常了
