### ISSUE TITLE
如何配置devServer

### ISSUE THREAD

**Issue by luxueyan** [umijs/umi#1352]
貌似没有暴露devserver的配置，我想做如下配置怎么做
```javascript
devServer: {
    open: process.platform === 'darwin',
    host: '0.0.0.0',
    port: 8081,
    https: false,
    hotOnly: true,
    overlay: {
      warnings: true,
      errors: true
    }
}
```

**Comment by sorrycc** [comment]
你想配什么？https、port、host、open 都可以配的，其他不能配，详见 https://umijs.org/guide/env-variables.html

**Comment by luxueyan** [comment]
@sorrycc  我想配置overlay，感觉还是都暴露出来的好。我想把eslint的警告信息页抛出到页面提示

**Comment by sorrycc** [comment]
overlay 已经内置了，不用配的。

**Comment by Kaijun** [comment]
@luxueyan 请问最后解决了吗？ 我通过 chainWebhook 修改 devServer 的 overlay 配置也没有生效

**Comment by luxueyan** [comment]
我也没处理！umi貌似没设置eslint-loader，自己设置一下应该可以吧

**Comment by dongze1213** [comment]
> 你想配什么？https、port、host、open 都可以配的，其他不能配，详见 https://umijs.org/guide/env-variables.html

怎么配DEV允许跨域请求？

**Comment by szy1000** [comment]
> 我也没处理！umi貌似没设置eslint-loader，自己设置一下应该可以吧

你设置可以了吗 我还是设置不成功

**Comment by szy1000** [comment]
> 我也没处理！umi貌似没设置eslint-loader，自己设置一下应该可以吧

你设置可以了吗 我还是设置不成功

**Comment by sujingclg** [comment]
建议还是把devServer也放开吧，毕竟文档上配置一章这么写的，要不一般人都不太能注意到用环境变量的

**Comment by HuaHeShang1** [comment]
overlay配置不了，建议还是放开吧

**Comment by xuemengfei** [comment]
@sorrycc 如果 devServer 不能自定义，那就在[文档](https://umijs.org/zh/config/#devserver)里写清楚吧，别直接一个链接链到 webpack 官方了……

**Comment by blueju** [comment]
> 你想配什么？https、port、host、open 都可以配的，其他不能配，详见 https://umijs.org/guide/env-variables.html

地址已失效，新地址：https://umijs.org/docs/env-variables

**Comment by linxiaowu66** [comment]
为啥不能放开devServer的配置？我想配置个中间件都没法子了

**Comment by junglehuang** [comment]
> 你想配什么？https、port、host、open 都可以配的，其他不能配，详见 https://umijs.org/guide/env-variables.html

请问怎么配置 overlay

**Comment by junglehuang** [comment]
> @sorrycc 我想配置overlay，感觉还是都暴露出来的好。我想把eslint的警告信息页抛出到页面提示

后面处理吗？

**Comment by qianyuhouse0326** [comment]
how to set compress to false?

**Comment by BaiyanAlwaysOnline** [comment]
how to set compress to false?

**Comment by Mahoo12138** [comment]
> 为啥不能放开 devServer 的配置？我想配置个中间件都没法子了

中间件可以使用暴露出来的 beforeMiddlewares 配置，但是我想操作 webpack 的 websocket；使用 config 中的 chainWebpack 和插件 api 中的 chainWebpack 都没法配置，想借助 webpack 的 ws 做一些开发环境的自定义通信。
