### ISSUE TITLE
在界面所有css、js为加载完前，怎么在index.html的root节点中加一个全局的loading，来优化用户体验

### ISSUE THREAD

**Issue by xiaomei991** [umijs/umi#1353]
在界面所有css、js为加载完前，怎么在index.html中加一个全局的loading，来优化用户体验，要实现这个功能，umi中要怎么配置

**Comment by xuqianjin** [comment]
定制一下ejx渲染模板..应该可以

**Comment by xiaomei991** [comment]
> 定制一下ejx渲染模板..应该可以
有没有简单例子可以参考下，看了下umi的文档，试验了下，打包后，root节点下还是没有东西

**Comment by xiaomei991** [comment]
> 定制一下ejx渲染模板..应该可以

有没有简单例子可以参考下，看了下umi的文档，试验了下，打包后，root节点下还是没有东西

**Comment by caixmi** [comment]
可以看看这个：[(https://juejin.im/post/5b506ae0e51d45191a0d4ec9)]

**Comment by caixmi** [comment]
[可以看看这个]((https://juejin.im/post/5b506ae0e51d45191a0d4ec9))
