### ISSUE TITLE
dva项目中model使用异步请求时,样式丢失

### ISSUE THREAD

**Issue by wakeup153** [umijs/umi#1356]
使用create-umi创建的dva项目, 在model中加入异步请求时样式丢失,取消加入样式恢复.

**Comment by wakeup153** [comment]
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: xiaohuoni <notifications@github.com>
发送时间: Tuesday, October 30, 2018 11:24:58 AM
收件人: umijs/umi
抄送: gsc; Author
主题: Re: [umijs/umi] dva项目中model使用异步请求时,样式丢失 (#1356)


给个demo

―

**Comment by wakeup153** [comment]
> 给个demo

https://github.com/wakeup153/gxdl.git

**Comment by xiaohuoni** [comment]
@wakeup153 没有home的model？

**Comment by wakeup153** [comment]
@xiaohuoni 
是页面model, src/pages/home文件夹内

**Comment by wakeup153** [comment]
@xiaohuoni  我找到原因了,我在 src/utils/request.js  中使用了antd的消息提示组件, 导致样式丢失

**Comment by xiaohuoni** [comment]
@wakeup153 什么样式丢失？我这重现不了

**Comment by wakeup153** [comment]
@xiaohuoni 将我项目clone下来,然后取消model里面的注释, https://github.com/wakeup153/gxdl.git

**Comment by xiaohuoni** [comment]
@wakeup153 就是你的项目，有没有注释，页面都一样

**Comment by xiaohuoni** [comment]
@wakeup153 重新看了一下，还是没看到有什么差别，没问题的话，这个问题关了吧
