### ISSUE TITLE
求助求助，项目打包后静态资源文件路径配置问题

### ISSUE THREAD

**Issue by xiaomei991** [umijs/umi#1357]
项目打包后静态资源文件路径配置问题，如何将/iconfont变成./iconfont，具体要使用哪个配置项
![image](https://user-images.githubusercontent.com/20355401/47692045-6de38100-dc2f-11e8-9d63-1b51f51f6835.png)

**Comment by sorrycc** [comment]
请给个可复现的库。

**Comment by xiaomei991** [comment]
> 请给个可复现的库。

之前是我引用的问题，修改了一下引用方式就行了
