### ISSUE TITLE
umi-plugin-dva     Cannot read property 'RENDER' of undefined

### ISSUE THREAD

**Issue by wupeng123456** [umijs/umi#1360]
![default](https://user-images.githubusercontent.com/26238791/47698367-0b4bae80-dc4a-11e8-9737-63fa9caa7797.JPG)
这个怎么解决？

**Comment by sorrycc** [comment]
升级到 umi@2 吧。

**Comment by wupeng123456** [comment]
> 升级到umi @ 2吧。

升级了

**Comment by wupeng123456** [comment]
> 应该是umi和插件不匹配导致的，需要把umi相关依赖升级到最新。

升级了也没有用，windows8.1的系统，不知道为什么？

**Comment by sorrycc** [comment]
参考 umijs.org 上的升级文档。
