### ISSUE TITLE
support tree shaking

### ISSUE THREAD

**Issue by jaredleechn** [umijs/umi#1364]
ref https://webpack.js.org/guides/tree-shaking/

**Comment by jaredleechn** [comment]
tree shaking 有几个[要求](https://webpack.js.org/guides/tree-shaking/#conclusion)，其中一个是不能使用 babel 把 ES module import 转换为 commonJS 的 require，然后由 webpack 自己去搞，我试了下 umi 的最小 demo，尝试把 [这行](https://github.com/umijs/umi/blob/master/packages/babel-preset-umi/src/index.js#L76) 改成 false，也没成功

**Comment by yutingzhao1991** [comment]
cc @ikobe

**Comment by concefly** [comment]
导出 stats.json 可以发现，所有 es 模块最后都变 cjs 引用了，这样 tree shaking 就无法起作用了

![image](https://user-images.githubusercontent.com/6647656/47708540-3db8d400-dc69-11e8-8686-64c4d5c81fbe.png)

**Comment by sorrycc** [comment]
应该是要配成 `modules: false` 就好了， @jaredleechn 不生效注意清下缓存？

**Comment by Leonard-Li777** [comment]
是否还要去掉 babel-plugin-dynamic-import-node ?

**Comment by jaredleechn** [comment]
`modules: false` 后有一个 break，就是 `umirc.js` 的写法不可以 `import` & `export default` 了

这个其实也是合理的，写给 node 读的配置文件，应该是 commonJS

**Comment by sorrycc** [comment]
@jaredleechn 这个可以区分的，一个给 node（@babel/register） 用，一个给 webpack 用。

**Comment by dilidili** [comment]
@sorrycc 项目中的 package.json 的 ```sideEffects``` umi 要不要也提供默认值 ```false```
