### ISSUE TITLE
在umi中怎么使用自己写的redux-middleware

### ISSUE THREAD

**Issue by zengyunchun** [umijs/umi#1368]
如题

**Comment by sorrycc** [comment]
参考 https://umijs.org/zh/guide/with-dva.html#%E9%85%8D%E7%BD%AE%E5%8F%8A%E6%8F%92%E4%BB%B6，在 `src/app.js` 里通过 `export const dva = { config: {  } }` 配置。

**Comment by ivanberry** [comment]
src/app.js 是需要自己新建吗？ 现在只有一个src/layouts/app.js
