### ISSUE TITLE
umi error: Module build failed

### ISSUE THREAD

**Issue by XanderXueMingJi** [umijs/umi#1369]
npm:  6.4.1;
umi: 2.1.1;
dva: 2.4.0;

im trying load css, but fail to load, message error :
1:
in ./src/fonts/socialshare/styles.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve 'fonts/iconfont.eot' in 'C:\Users\Administrator\Documents\wisy_backend\src\fonts\socialshare'

2:
in ./src/fonts/wisy-icon-font/styles.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve 'fonts/wisy.eot' in 'C:\Users\Administrator\Documents\wisy_backend\src\fonts\wisy-icon-font'

style-loader and css-loader 2 does not work?

The solution I found on the Internet is related to webpack. How can I solve it in UMI?

**Comment by sorrycc** [comment]
Please provide a reproducible repo.

**Comment by XanderXueMingJi** [comment]
Thank you, I have solved the problem of path setting.

**Comment by twilroad** [comment]
> Thank you, I have solved the problem of path setting.

How to fix it?

**Comment by Jansora** [comment]
> > Thank you, I have solved the problem of path setting.
> 
> How to fix it?

1: open `/config/config.js`
2: find key: `cssLoaderOptions`
3: change `modules:ture`  -> `modules:false`

everything is ok.
