### ISSUE TITLE
umi build在window和linux下打包 代码 文件大小不一样

### ISSUE THREAD

**Issue by RisingSunYZ** [umijs/umi#1374]
我同样的代码 在windows下build 是可以使用的,在linux build后访问报错,而且 打包的umi.js也和windows下大小不一致

**Comment by sorrycc** [comment]
报什么错？

**Comment by RisingSunYZ** [comment]
umi.3c27c56e.js:1 Error: Reducer "index" returned undefined during initialization. If the state passed to the reducer is undefined, you must explicitly return the initial state. The initial state may not be undefined. If you don't want to set a value for this reducer, you can use null instead of undefined.

@sorrycc 
貌似是 state未初始化的原因
但是我本地可以启动,而且 本地window打包后 将dist文件传到服务器上也是可以的,只有在linux环境下 打包后访问报错,linux 下 打包控制台也显示build success了

**Comment by RisingSunYZ** [comment]
antd 由1.0 升级到 antd pro2.0的项目 @sorrycc

**Comment by sorrycc** [comment]
检查下有没有叫 `index` 的 model 。

**Comment by RisingSunYZ** [comment]
没有 @sorrycc

**Comment by RisingSunYZ** [comment]
开发的时候 看到这条 我就手动给删除了 index.js


删除 models/index.js#
在 umi 中，挂载了 dva 的插件之后 models 下的文件会被默认当做 dva model 引入，所以不再需要在 models/index.js 中来手动挂载 model，可以直接删除该文件。

**Comment by sorrycc** [comment]
不能定位问题，需要给一个可复现的库。

**Comment by qiyx2019** [comment]
"umi": "^2.2.1"版本可复现
