### ISSUE TITLE
how can i create myself router.js file?

### ISSUE THREAD

**Issue by promohammadreza** [umijs/umi#1377]
I used umi version 2 and antd pro version 2 for my app.
when we want add a new route to app we should add our route in router.config.js and umi create route.js file in `src/pages/.umi`, and we know each route can have authority of user permission's array.
In my project, We have very role and all of them is define by admin role our some of other role in dashboard. So all of the role come from the api and should be use in authority.
But i can't do anything in umi.
Is there anyway to do this in umi?
I thought it might be better if I created the router.js file, But how do I do this in the project with umi?

**Comment by sorrycc** [comment]
so, what you want is to modify the route at runtime?

**Comment by promohammadreza** [comment]
yes, I want to be able to get the value of each route authority's from the api.

**Comment by sorrycc** [comment]
I'll try to write a demo for this scenes.

**Comment by promohammadreza** [comment]
@sorrycc 
Thank you so much.. Please Let me know if you did it.

**Comment by sajadshafizadeh** [comment]
Ok buddy @sorrycc ... Hey ..! I'm Shafizadeh, @promohammadreza's coworker. I just want to make the main problem more clear .. you know, we have some roles, they will be generated dynamically. So we cannot put them as an array under each route (`authority` key) in the `router.config.js`. We want to make that file when the user logs in. What we've done is storing the whole system rolling accessibilities in the localstorage when the user logs in. But sadly we cannot access localstorage data inside `router.config.js` file to apply roles in that file. Any idea how should we handle such a thing? Thank you in advance.

**Comment by sorrycc** [comment]
[sorrycc-8Xn9Hm.zip](https://github.com/umijs/umi/files/2534955/sorrycc-8Xn9Hm.zip)

**Comment by sajadshafizadeh** [comment]
Thank you @sorrycc ... we will take a look at it.

**Comment by promohammadreza** [comment]
Sorry to ping you again @sorrycc , I tested your code and worked well .. thank you. Just there is a minor issue. Please take a look at this function;

```
export function patchRoutes(routes) {
  routes[0] = {
    ...routes[0],
    ...(authRoutes[routes[0].path] || {}),
     };
}
```

You've used the `0` key of routes array. So in the following routes, it will be applied only to the first item of the array:

// router.js (which is generated by router.config.js)
let routes = [
  {
    "path": "/user",
    "component": dynamic({ whatever }),
    "authority": [],
  },
  {
    "path": "/",
    "component": dynamic({ whatever }),
    "authority": [],
  }
]
```

Now I'm overwriting the authorities using an API: 

```
 '/api/auth_routes': {
    "/user": {authority: ['user']},
    '/': { authority: ['admin'] },
  }, 
```

See? It has two items, both `/user` and `/`. But your code applies the `authority` only to the `/user` route. since that function uses `routes[0]`, just the `0` key. Any idea how can I make it working for all returned routes from the API? Should I put a loop on it?

**Comment by sorrycc** [comment]
`routes[0]` is for demo, feel free to modify the routes as you wish.
