### ISSUE TITLE
umi build 静态资源文件夹不对

### ISSUE THREAD

**Issue by luxueyan** [umijs/umi#1379]
执行build以后，所有的css和js都不在static目录下，如下图：配置了publicPath也不管用
![image](https://user-images.githubusercontent.com/1555552/47787433-d9ba0c80-dd49-11e8-8272-046ec2b28877.png)

**Comment by okoala** [comment]
https://umijs.org/config/#outputpath

**Comment by xiaohuoni** [comment]
@okoala outputpath是配置输出目录。他的意思应该是dist里面的文件没有整理。

**Comment by xiaohuoni** [comment]
@luxueyan 这应该是配置了按需加载，所以这些文件比较多。没有配置按需加载的时候，umi.js/umi.css也是在这个层级目录下面的，所以应该没有什么问题

**Comment by luxueyan** [comment]
但是 文件多， 我想js能在js目录  css能在css目录，不知道能不能做到

**Comment by sorrycc** [comment]
@luxueyan 目前没法做到这一点。

**Comment by luxueyan** [comment]
@sorrycc  还有个问题，为什么build之后的文件没有 文件指纹，在哪里配置

**Comment by younth** [comment]
为啥不能配置js/css输出路径呢 @sorrycc
