### ISSUE TITLE
pwa service-worker.js 注册路径无法定义

### ISSUE THREAD

**Issue by huanz** [umijs/umi#1380]

**Comment by sorrycc** [comment]
@xiaoiver 有空看下。

**Comment by xiaoiver** [comment]
Workbox 生成 Service Worker 有两种模式，可以通过 Umi Config 中 `pwa.workboxPluginMode` 配置：
1. `GenerateSW` 模式，根据配置生成全新 Service Worker，这也是 Umi 默认的
2. `InjectManifest` 模式，以已有 Service Worker 为基础，构建时注入预缓存列表

构建时和路径相关的配置项有两个：
1. 在 `InjectManifest` 模式中，输入 Service Worker 路径可以通过 `swSrc` 配置
2. 两种模式下输出到构建产物的路径，通过 `swDest` 配置
```js
pwa: {
  // 开启注入模式
  workboxPluginMode: 'InjectManifest',
  workboxOptions: {
    importWorkboxFrom: 'local',
    // 读取已有 service-worker 路径
    swSrc: join(__dirname, 'src/my-custom-service-worker.js'),
    // 输出到构建产物路径
    swDest: 'sw.js'
  }
}
```

但是现在注册 service-worker 存在两个问题：
1. 没有拼接上 `publicPath`，会导致配置了 `publicPath` 的场景下找不到路径
2. 没有使用 `swDest` 作为注册路径

这俩问题稍后会修复，@huanz 请问你遇到的问题是这个吗？

**Comment by huanz** [comment]
@xiaoiver 我遇到的问题是 2 个，定义的 `swDest` 没用，注册那里依然是 `/service-worker.js`

**Comment by huanz** [comment]
@xiaoiver 还有个问题是 `src/manifest.json` 里面定义的 icons src 引用的本地文件并没有被处理

**Comment by xiaoiver** [comment]
icons src 的问题是这样的，像图标这类静态资源可以放在 `public/` 下，Umi 会自动拷贝到构建产物里。

**Comment by huanz** [comment]
@xiaoiver 我目前是放在了 src/assets 目录

**Comment by xiaoiver** [comment]
我觉得 `src/assets` 下放的是“未编译的静态资源”，比如 Nuxt 里管这个叫 [“资源目录”](https://zh.nuxtjs.org/guide/directory-structure#%E8%B5%84%E6%BA%90%E7%9B%AE%E5%BD%95) ，而另一类静态资源 Nuxt 建议放在[“静态文件目录”](https://zh.nuxtjs.org/guide/directory-structure#%E9%9D%99%E6%80%81%E6%96%87%E4%BB%B6%E7%9B%AE%E5%BD%95)，构建时只需要简单拷贝过去。像 icon 图标这种个人觉得属于后者，你觉得呢？

**Comment by QianDingwei** [comment]
大佬，麻烦问一下，umi中的serviceworker是如何配置的
