### ISSUE TITLE
'react' should be listed in the project's dependencies.

### ISSUE THREAD

**Issue by weishijun14** [umijs/umi#1381]
request.js: 
![image](https://user-images.githubusercontent.com/20705423/47833413-90170380-ddd5-11e8-899c-5fa1e0443730.png)

package.json:
![image](https://user-images.githubusercontent.com/20705423/47833429-a6bd5a80-ddd5-11e8-8a88-d647949707cc.png)

eslinrc:
![image](https://user-images.githubusercontent.com/20705423/47833430-b046c280-ddd5-11e8-9873-521f32f29475.png)

> Out of box, dependencies such as: dva, dva-loading, dva-immer, path-to-regexp, object-assign, react, react-dom are built in, so that you don't have to worry about them

**As above pics, I use eslint and it has something wrong, I must to install dva package?**

**Comment by sorrycc** [comment]
Disable the eslint rule, or isntall related packages.
