### ISSUE TITLE
afwebpack-config's path lookup problem under yarn workspace

### ISSUE THREAD

**Issue by xiaoxiangmoe** [umijs/umi#1387]
A reproducible example as follows：

https://github.com/xiaoxiangmoe/umi-monorepo

Error：
```
error     Plugin built-in:plugins/afwebpack-config initialize failed
```

My Environment:

* yarn 1.12.1
* node 11.0.0
* macOS 10.14 (18A391)

------
If you delete the dependency of antd & ant-design-pro, the problem disappears.

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/48035682-19e11b00-e1a0-11e8-84b3-5b6959dc5c55.png)
