### ISSUE TITLE
约定式路由 如何进行权限控制

### ISSUE THREAD

**Issue by curry-wxj** [umijs/umi#1389]
layout/index.js配置
/**
 * authority: [user,admin],
 * Routes:
 *   - ./src/page/authorized.js
 */
无效果
为什么刷新页面时 不进入 src/page/authorized.js页面

**Comment by xiaohuoni** [comment]
这是什么设置？

**Comment by curry-wxj** [comment]
通过注释扩展路由 对layout/index.js无效， 那如何给layout/index.js配置权限路由
/**
 * authority: [admin, user]
 * Routes:
 *   - ./src/page/authorized.js
 */

**Comment by curry-wxj** [comment]
![image](https://user-images.githubusercontent.com/30777163/47849940-72b25b80-de0e-11e8-90d5-a99f6495a7f1.png)
这样的配置式路由，  通过约定式路由 如何实现  我的是 layouts/index.js

**Comment by curry-wxj** [comment]
![image](https://user-images.githubusercontent.com/30777163/47850006-b6a56080-de0e-11e8-886c-2739a0609672.png)
zheyang
这样配置给layout/index.js无效

**Comment by xiaohuoni** [comment]
这个应该是有效的。你可以直接试试插件umi-plugin-authorize

**Comment by curry-wxj** [comment]
好的 可以生成了 谢谢。
![image](https://user-images.githubusercontent.com/30777163/47851414-857b5f00-de13-11e8-91a1-7d9bbc6e546f.png)
/user/login 也有权限路由   "Routes": [require('../authorized.js').default] ，
![image](https://user-images.githubusercontent.com/30777163/47851459-ab086880-de13-11e8-848e-18e4ff6dab3c.png)
这个无法实现跳转怎么办？

**Comment by clean222** [comment]
@curry-wxj 解决了吗？

**Comment by curry-wxj** [comment]
解决了~ @clean222

**Comment by clean222** [comment]
@curry-wxj 你怎么解决的？我约定式路由，遇到了相同的问题。

**Comment by curry-wxj** [comment]
需要自己写一段 代码，  通过location.pathname 找到对应约定式路由的配置信息
配置如下：
/**
 * icon: distribution
 * authority: admin
 */
就可以拿到 authority,  传给 官方的Authorized组件，进行权限控制
   <Authorized
          authority={routerConfig.authority}
         noMatch={<Exception type="403" />}
   >
@clean222

**Comment by clean222** [comment]
@curry-wxj 不好意思，打扰了
我的问题是让这个authority不对登录进行进行权限控制?
你的意思是给/user/login的加个authority，当进入 Authorized进行判断
if(children.props.location.pathname="/user/login"){
  return <Authorized authority={routerConfig.authority} noMatch={}/>？？这个判断怎么写
  }
return (
   <Authorized authority={children.props.route.authority} noMatch={<Redirect to="/user/login" />}>
    {children}
  </Authorized>
