### ISSUE TITLE
目录路由生成问题

### ISSUE THREAD

**Issue by ouxu** [umijs/umi#139]
+ `services` 和 `models` 文件夹也会产生对应路由
+ 包含 `:id` 这种变量路由其他路由会被覆盖，建议调整优先级，将变量作为最后匹配项

见下图 umi 生成的路由文件

![image](https://user-images.githubusercontent.com/19731728/36707952-9ea06e24-1bab-11e8-884c-792f072c991d.png)

**Comment by sorrycc** [comment]
> services 和 models 文件夹也会产生对应路由

目录下有 page.js 吗？有 page.js 就不会继续往下找路由了。

**Comment by ouxu** [comment]
业务场景是 `/contests` 有页面，需要自己的 models， `/contests/:id` 也有页面，把 `contests/index.js`
 改成 `page.js` 后无法生成 `/contests/:id` 的路由。

**Comment by pengfeiWang** [comment]
还是没仔细看文档

$file_name 的文件会生成对应路径, /contests/:file_name

**Comment by daqi** [comment]
$id可以是目录，pages/contests/$id/page.js
