### ISSUE TITLE
antd打包问题，能不打包@ant-design这个图标库吗，项目中没用到Icon，打包后，还多了500多k

### ISSUE THREAD

**Issue by xiaomei991** [umijs/umi#1390]
![image](https://user-images.githubusercontent.com/20355401/47849925-61694f00-de0e-11e8-981b-c820bd5edbb4.png)

**Comment by sorrycc** [comment]
这是 antd 的问题，请到 antd 的 issue 咨询，好像最新版已经解决这个问题了。
