### ISSUE TITLE
ie11兼容问题

### ISSUE THREAD

**Issue by tanwenchao** [umijs/umi#1394]
import 'core-js/es6/promise'
import 'core-js/es6/set';
import 'core-js/es6/map';
import 'core-js/es6/object';
import 'core-js/es6/number';
import 'core-js/es6/array';

import 'raf/polyfill'
import 'url-polyfill'
在global.js引入了这些包还是有兼容问题

.umirc.js配置
import { resolve } from 'path'
export default {
  history: 'hash',
  plugins: [
    // ref: https://umijs.org/plugin/umi-plugin-react.html
    'umi-plugin-polyfill',
    ['umi-plugin-react', {
      antd: true,
      dva: true,
      dynamicImport: true,
      polyfills: ['ie9'],
      title: '',
      dll: false,
      pwa: false,
      routes: {
        exclude: [],
      },
      hardSource: false,
    }],
  ],
  alias: {
    api: resolve(__dirname, 'src/api'),
    assets: resolve(__dirname, 'src/assets'),
    config: resolve(__dirname, 'src/config'),
    services: resolve(__dirname, 'src/services'),
    utils: resolve(__dirname, 'src/utils'),
    components: resolve(__dirname, 'src/components'),
    libs: resolve(__dirname, 'src/libs')
  },
  theme: {
    "@primary-color": "#00aaf7"
  }
}

WARNING!!
umi-plugin-polyfills is deprecated, use config.targets instead.
npm run build的时候抛出警告

**Comment by sorrycc** [comment]
参考 https://umijs.org/config/#targets

**Comment by tanwenchao** [comment]
targets: {
    ie: 11,
 }
这样配置了 其他的就不用管了吗

**Comment by superchow** [comment]
> targets: {
> ie: 11,
> }
> 这样配置了 其他的就不用管了吗

设置 `ie: 7` 也不行，感觉只支持 11

**Comment by miaozilong** [comment]
> > targets: {
> > ie: 11,
> > }
> > 这样配置了 其他的就不用管了吗
> 
> 设置 `ie: 7` 也不行，感觉只支持 11

肯定不行啊  umi都不支持ie7呀
