### ISSUE TITLE
Disable default mocking

### ISSUE THREAD

**Issue by lemol** [umijs/umi#1395]
I'm using the `mock` folder to place files for graphql mocking. I don't need the default http mocking behaviour.

It displays the following error message on console:

```
×  error     Mock file parse failed
Unexpected identifier
```

Is it posible to disable this error message?

**Comment by xiaohuoni** [comment]
https://umijs.org/guide/env-variables.html#mock
```bash
$ MOCK=none umi dev
```

**Comment by lemol** [comment]
@xiaohuoni thank you for the answer.

The problem with this solution is that I'm using the same MOCK env variable to define if it will mock the graphql link or not.
When the graphql link is mocked then MOCK != none.

**Comment by sorrycc** [comment]
Try to use another env variable for graphql link mock?
