### ISSUE TITLE
including react-mapbox-gl in the project prevents umi global style in dev server

### ISSUE THREAD

**Issue by ramireznoy** [umijs/umi#1396]
Trying to integrate mapbox to an UMI project caused some serious issue: global styles are no longer being loaded. It is even verifiable in the ant-design-pro demo.
To replicate the issue, first verify the global is just fine, set on it something like:
`html,
body,
#root {
  height: 100%;
  color: red
}`
then, after doing `yarn start`, red fonts are visible in the top of the page:
<img width="1679" alt="screen shot 2018-11-01 at 7 46 38 pm" src="https://user-images.githubusercontent.com/11444758/47891073-e81e2c00-de0e-11e8-983f-cfd77a165be1.png">
Now, install react-mapbox-gl:
`yarn add mapbox-gl react-mapbox-gl`
now just run the project
`yarn start`
The global style is gone and there is a padding in the page body:
<img width="1680" alt="screen shot 2018-11-01 at 7 49 22 pm" src="https://user-images.githubusercontent.com/11444758/47891183-5c58cf80-de0f-11e8-8c65-4c4273270a7e.png">
Now if you remove just react-mapbox-gl:
`yarn remove react-mapbox-gl`
Everything works just as expected. Also if you build the project, the global styles are back!
Why is that happening even without using anything from the new packages?

**Comment by sorrycc** [comment]
Please give a simple and reproducible repo, I tried it and can't reproduce your problem.
[sorrycc-Vyj0P2.zip](https://github.com/umijs/umi/files/2541346/sorrycc-Vyj0P2.zip)

**Comment by ramireznoy** [comment]
Hi! Thank you for the quick response. I created my project using `yarn create umi`. You can check the issue here: https://github.com/ramireznoy/umi-issue.
As you can see, global styles are not being used. But if you remove the mapbox dependencies or build the project, then globals are back

**Comment by sorrycc** [comment]
In case of dll related problems, please `exclude` the problematic package.
