### ISSUE TITLE
如何单独配置图片路径

### ISSUE THREAD

**Issue by jamielhf** [umijs/umi#1398]
线上环境 图片是走其他cdn的，有没有类似publicPath的配置项，或者可以配置webpack的图片那块的loader?

**Comment by sorrycc** [comment]
图片走 cdn 为啥不直接传好写线上 url ?

**Comment by jamielhf** [comment]
这样是可以，只是在开发的时候不太方便，如果要修改或者新增图片，就要先上传到服务器上。是否可以考虑放出更多的可配置项。

**Comment by luoboding** [comment]
我的做法是每次build的时候动态注入一个环境变量的js文件:
injector.js:
`
const fs = require('fs');

const { argv } = process;
const customizedArgv = argv.slice(2);
const argvMap = {};
customizedArgv.forEach((item) => {
  const key = item.slice(0, item.indexOf('='));
  const value = item.slice(item.indexOf('=') + 1);
  Object.assign(argvMap, {
    [key]: value,
  });
});
const cdn = argvMap['cdn'];
const injectString = `
const config = {
  cdn: '${cdb}',
};
export default config;
`;
fs.writeFileSync('./src/env.config.js', injectString);
`
node injector.js cdn=cdnUrl & yarn start

**Comment by sorrycc** [comment]
#1409 支持 cssPublicPath，等下个版本试试。
