### ISSUE TITLE
Strip json quotes for custom routes props

### ISSUE THREAD

**Issue by lemol** [umijs/umi#1407]
The route configuration defined as `yaml` anotation on page file  parsed as object with string values. [Example](https://umijs.org/guide/router.html#extending-routing-by-annotation):

```js
/**
 * title: Index Page
 * Routes:
 *   - ./src/routes/a.js
 *   - ./src/routes/b.js
 */
```

is parsed as:

```js
[
  { path: '/', component: './index.js',
    title: 'Index Page',
    Routes: [ './src/routes/a.js', './src/routes/b.js' ],
  },
]
```

Sometime it is necessary to pass config information that is not a string, for example, to be parsed as:

```js
[
  { path: '/', component: './index.js',
    header: () => xxxx, // <- THIS IS NOT A STRING
  },
]
```

This can be achieved easily, since there is already a file `stipJSONQuotes.js` which exposes a function that do this for the `component` field. So, if we find a convention, e.g, that proprities that starts with `$` will be parsed as they are (not as a string), then this can be implemented easily.

Do you think this can be useful feature to be added to umijs?

I can submit a pull request.

**Comment by sorrycc** [comment]
I think it's ok, pr is welcome.
