### ISSUE TITLE
Electron 应该如何配置路径

### ISSUE THREAD

**Issue by stoneWeb** [umijs/umi#1410]
Electron loadURL http://localhost:8000/ 正常
``` javascript
mainWindow.loadURL('http://localhost:8000/')
```
umi build后 loadURL 本地路径 页面空白，js 不执行，我应该如何配置？
``` javascript
mainWindow.loadURL(url.format({
      pathname: path.join(__dirname, '../../view/index.html'),
      protocol: 'file:',
      slashes: true
 }))
```

**Comment by tianxiangbing** [comment]
@stoneWeb 怎么解决的啊？

**Comment by devin-yuan** [comment]
配置文件`history`改为`hash`

**Comment by theprimone** [comment]
路由使用 hash 模式就行了，history 应该只能在部署到 web 服务器后才能使用

**Comment by WangJM001** [comment]
基于Umi的Electron框架，一行命令(pnpm create poros)生成Electron应用，快速开发、打包， 集成了各种功能，方便好用，感兴趣的可以看下，欢迎Star，项目还在不断迭代中。
https://github.com/porosjs/poros
