### ISSUE TITLE
通用 css modules 方案

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#1417]
## 使用

a.css

```css
.a { color: red; }
```

b.css

```css
.b { color: red; }
```

a.js

```js
import styles from './a.css';
import './b.css';
```

打包 a.js，输出 css，

```
.a___6ESeB { color: red; }
.b { color: red }
```

## 方案

分两步，

### 一、通过 babel 插件处理 js 里的 css/less/sass/scss 引用

比如：

```js
import styles from './a.css';
import './b.css';
```

转换为：

```js
import styles from './a.css?cssModules';
import './b.css';
```

至于为啥不转换为 `import styles from 'css-loader?modules!./a.css';`，因为还有 postcss、extract css、css-hot-loader 等需要处理，而且 postcss 的 options 里还有函数，不能通过字符串的方式传递。

### 二、`module.rules` 里处理带 `?cssModules` query 的资源，走 css modules

示例：

```js
const rule = webpackConfig.module
  .rule('css')
  .test(/\.css$/);

applyCSSRules(
  rule.oneOf('CSSModules').resourceQuery(/cssModules/),
  { cssModules: true, less: true },
);
applyCSSRules(
  rule.oneOf('noCSSModules'),
  { cssModules: false, less: true },
);
```

## 兼容考虑

由于会有 break change，所以通过额外的配置项 `autoCSSModules` 开启，等 umi@3 时默认开启。

## 参考

* https://github.com/facebook/create-react-app/tree/master/packages/babel-plugin-named-asset-import
* https://webpack.js.org/configuration/module/#rule-resourcequery
* https://github.com/babel-utils/babel-plugin-tester

**Comment by xiaohuoni** [comment]
style里面的样式要不要考虑一起处理了o(*￣︶￣*)o

**Comment by xiaoxiangmoe** [comment]
@sorrycc 为什么不使用`cssModulesWithAffix`解决呢？

```
export default {
  disableCSSModules: true,
  cssModulesWithAffix: true,
}
```

------

因为如果根据 import 来区分，当遇到 
```
import styles from './a.css';
import './a.css';
```
的情况下（即需要 named import，又需要 side effect import）:

* 我们不能简单通过css文件名来判断其是否会污染全局的环境
* 产生的代码，会有一份无 module 前缀的，一份有 module 前缀的 class name

这种表现，会比较奇怪。

**Comment by sorrycc** [comment]
```js
import styles from './a.css';
import './a.css';
```

这不是正确的用法吧。

**Comment by xiaoxiangmoe** [comment]
@sorrycc 这的确不是正确的用法。

但是这有如下问题：
* 用法不容易被检查出来。
* 编译产生的副作用（类名的变化）依赖于调用方，看起来不是很合理。

create-react-app 这种通过文件名是否带`.module.(scss|less|css)`来区分的方案更合理，唯一的缺点就是文件名长了点。

**Comment by sorrycc** [comment]
> 误用的用法不容易被检查出来

误用后没有效果不就知道了吗？

> 编译产生的副作用（类名的变化）依赖于调用方，看起来不是很合理。

我觉得是合理的。create-react-app 处理 svg 也是这个逻辑，比如 `import { ReactComponent } from './a.svg'` 会被处理成 React 组件。

**Comment by xiaoxiangmoe** [comment]
@sorrycc https://github.com/mrmckeb/typescript-plugin-css-modules

有些第三方插件默认对 `.module.css` 开启 css-module 支持。

**Comment by wangxingkang** [comment]
@sorrycc 这个功能大概什么时间上线

**Comment by rainbowMorelhahahah** [comment]
这方案我觉得不行， 还有默认 为什么要开启 css modules  这是有病的做法

**Comment by rainbowMorelhahahah** [comment]
```
import '../common/less/barnd.less';
```
写法
```

@import "./default.less";
.banner {
    background: url(https://gw.alipayobjects.com/zos/rmsportal/okhVRKJXxQpbpKGtKneS.svg) no-repeat center top;
    background-size: contain;
    overflow: hidden;
    font-family: PingFang SC, Helvetica Neue For Number, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Hiragino Sans GB, Microsoft YaHei, Helvetica Neue, Helvetica, Arial, sans-serif;
    .page {
        max-width: 1248px;
    }
    .logo {
        background: url(https://gw.alipayobjects.com/zos/rmsportal/khXpcyRYlACLokoNTzwc.svg) no-repeat;
        width: 127px;
        height: 110px;
        margin: 86px auto 40px;
    }
    & &-anim {
        margin: 0 auto 64px;
        height: 600px;
        box-shadow: 0 20px 32px rgba(1, 4, 8, .12);
        background: #fff;
        border-radius: 8px;
        &-elem {
            .banner-bg {
                width: 100%;
                height: 100%;
                position: absolute;
                top: 0;
                left: 0;
                overflow: hidden;
                background-position: center;
                background-repeat: no-repeat;
            }
        }
    }
    .seeconf {
        &-wrap {
            text-align: center;
            color: @banner-text-color;
            .banner-button {
                margin: 64px 0 26px;
                .ant-btn {
                    height: 35px;
                    line-height: 35px;
                    border-radius: 35px;
                    background: #2354eb;
                    box-shadow: 0 7px 13px #91a5f2;
                    padding: 0 28px;
                    font-size: 12px;
                    a {
                        text-decoration: none;
                    }
                }
            }
        }
        &-en-name {
            margin: 140px 0 0;
            font-size: 12px;
            line-height: 32px;
        }
        &-title {
            margin: 16px 0 24px;
            font-size: 56px;
            line-height: 68px;
            text-indent: 2px;
            font-weight: 600;
            color: #02063D;
        }
        &-cn-name {
            font-size: 18px;
        }
    }
    &-button {
        .ant-btn {
            color: #fff;
            border: none;
        }
    }
}

```

编译后
```
/* stylelint-disable at-rule-empty-line-before,at-rule-name-space-after,at-rule-no-unknown */
/* stylelint-disable no-duplicate-selectors */
/* stylelint-disable */
/* stylelint-disable declaration-bang-space-before,no-duplicate-selectors,string-no-newline */
.barnd__banner___IkHrG {
  background: url(https://gw.alipayobjects.com/zos/rmsportal/okhVRKJXxQpbpKGtKneS.svg) no-repeat center top;
  background-size: contain;
  overflow: hidden;
  font-family: PingFang SC, Helvetica Neue For Number, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Hiragino Sans GB, Microsoft YaHei, Helvetica Neue, Helvetica, Arial, sans-serif;
}
.barnd__banner___IkHrG .barnd__page___19R0U {
  max-width: 1248px;
}
.barnd__banner___IkHrG .barnd__logo___2J6Lp {
  background: url(https://gw.alipayobjects.com/zos/rmsportal/khXpcyRYlACLokoNTzwc.svg) no-repeat;
  width: 127px;
  height: 110px;
  margin: 86px auto 40px;
}
.barnd__banner___IkHrG .barnd__banner-anim___2XSRf {
  margin: 0 auto 64px;
  height: 600px;
  box-shadow: 0 20px 32px rgba(1, 4, 8, 0.12);
  background: #fff;
  border-radius: 8px;
}
.barnd__banner___IkHrG .barnd__banner-anim-elem___3AU3D .barnd__banner-bg___3d6h5 {
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
  overflow: hidden;
  background-position: center;
  background-repeat: no-repeat;
}
.barnd__banner___IkHrG .barnd__seeconf-wrap___1ZR80 {
  text-align: center;
  color: #5C6899;
}
.barnd__banner___IkHrG .barnd__seeconf-wrap___1ZR80 .barnd__banner-button___1EiwB {
  margin: 64px 0 26px;
}
.barnd__banner___IkHrG .barnd__seeconf-wrap___1ZR80 .barnd__banner-button___1EiwB .barnd__ant-btn___3dZj5 {
  height: 35px;
  line-height: 35px;
  border-radius: 35px;
  background: #2354eb;
  box-shadow: 0 7px 13px #91a5f2;
  padding: 0 28px;
  font-size: 12px;
}
.barnd__banner___IkHrG .barnd__seeconf-wrap___1ZR80 .barnd__banner-button___1EiwB .barnd__ant-btn___3dZj5 a {
  text-decoration: none;
}
.barnd__banner___IkHrG .barnd__seeconf-en-name___Yi2mc {
  margin: 140px 0 0;
  font-size: 12px;
  line-height: 32px;
}
.barnd__banner___IkHrG .barnd__seeconf-title___2BLq5 {
  margin: 16px 0 24px;
  font-size: 56px;
  line-height: 68px;
  text-indent: 2px;
  font-weight: 600;
  color: #02063D;
}
.barnd__banner___IkHrG .barnd__seeconf-cn-name___2QoLk {
  font-size: 18px;
}
.barnd__banner-button___1EiwB .barnd__ant-btn___3dZj5 {
  color: #fff;
  border: none;
}


/*# sourceMappingURL=p__index.chunk.css.map*/
```

还不是一样被便宜了。。。 你这也叫通用？

**Comment by wangxingkang** [comment]
@rainbowMorelhahahah 这个还没上线吧

**Comment by rainbowMorelhahahah** [comment]
> @rainbowMorelhahahah 这个还没上线吧

Issue on 6 Nov 2018 · 9 comments  我看时间 以为上线了

**Comment by hankaibo** [comment]
@wangxingkang 有具体上线日期没？

**Comment by hankaibo** [comment]
@sorrycc 有具体上线日期没？

**Comment by wangxingkang** [comment]
可以先使用 https://github.com/alitajs/umi-plugin-packages/tree/master/packages/umi-plugin-css-modules 解决

**Comment by wangxingkang** [comment]
通用css modules 方案尝试  https://github.com/wangxingkang/webpack-chain-study/tree/master/examples/auto-css-modules

**Comment by tsaowe** [comment]
#### 给 umi 项目添加以 styleName 为类名转化的方法(默认使用less文件)

- 1 yarn add babel-plugin-react-css-modules postcss-less
- 2 在~/config/config.js中添加 
```
  ...
  extraBabelPlugins: [
    [
      'react-css-modules',
      {
        'exclude': 'node_modules',
        'generateScopedName': '[name]__[local]___[hash:base64:5]',
        'filetypes': {
          '.less': {
            'syntax': 'postcss-less',
          },
        },
      },
    ],
  ],
  ...
```
- 3 在jsx文件中 import './style.less'

**Comment by ywy94ywy** [comment]
> #### 给 umi 项目添加以 styleName 为类名转化的方法(默认使用less文件)
> * 1 yarn add babel-plugin-react-css-modules postcss-less
> * 2 在~/config/config.js中添加
> 
> ```
>   ...
>   extraBabelPlugins: [
>     [
>       'react-css-modules',
>       {
>         'exclude': 'node_modules',
>         'generateScopedName': '[name]__[local]___[hash:base64:5]',
>         'filetypes': {
>           '.less': {
>             'syntax': 'postcss-less',
>           },
>         },
>       },
>     ],
>   ],
>   ...
> ```
> 
> * 3 在jsx文件中 import './style.less'

老兄，sass怎么搞处理啊，我用了babel-plugin-react-css-modules postcss-scss，生成的类名还是对应不上。
另外sass的全局变量该怎么加入UMI呢

**Comment by xiaoxiangmoe** [comment]
1

**Comment by sorrycc** [comment]
已在 umi@3 中实现。

**Comment by fengqingdoufu** [comment]
> #### 给 umi 项目添加以 styleName 为类名转化的方法(默认使用less文件)
> * 1 yarn add babel-plugin-react-css-modules postcss-less
> * 2 在~/config/config.js中添加
> 
> ```
>   ...
>   extraBabelPlugins: [
>     [
>       'react-css-modules',
>       {
>         'exclude': 'node_modules',
>         'generateScopedName': '[name]__[local]___[hash:base64:5]',
>         'filetypes': {
>           '.less': {
>             'syntax': 'postcss-less',
>           },
>         },
>       },
>     ],
>   ],
>   ...
> ```
> 
> * 3 在jsx文件中 import './style.less'

哥们，问一下 我再项目中按照你这个配置，还需要配置其他吗 打包完以后styleName没有被处理，还是当成属性输出了

**Comment by huanhuan1989** [comment]
cssLoaderOptions:{
    modules: true,
    localIdentName: '[local]'
  }
试试

**Comment by diveDylan** [comment]
考虑支持ts的自动提示么，集成typescript插件 [typescript-plugin-css-modules](https://github.com/mrmckeb/typescript-plugin-css-modules)，觉得这个超赞 @sorrycc

**Comment by williamyorkl** [comment]
> 

大佬, 按照这个配置还是 negative.....  和下面这位大佬呈现的现象和这个一模一样, 还有什么配置 miss 了么  :-)
https://github.com/umijs/umi/issues/4859

**Comment by williamyorkl** [comment]
> #### 给 umi 项目添加以 styleName 为类名转化的方法(默认使用less文件)
> * 1 yarn add babel-plugin-react-css-modules postcss-less
> * 2 在~/config/config.js中添加
> 
> ```
>   ...
>   extraBabelPlugins: [
>     [
>       'react-css-modules',
>       {
>         'exclude': 'node_modules',
>         'generateScopedName': '[name]__[local]___[hash:base64:5]',
>         'filetypes': {
>           '.less': {
>             'syntax': 'postcss-less',
>           },
>         },
>       },
>     ],
>   ],
>   ...
> ```
> 
> * 3 在jsx文件中 import './style.less'

大佬, 按照这个配置还是 negative..... 和下面这位大佬呈现的现象和这个一模一样, 还有什么配置 miss 了么 :-)
#4859
