### ISSUE TITLE
Feature Request: 'umi eject' 

### ISSUE THREAD

**Issue by heya-aron** [umijs/umi#1418]
Before I start, great work with Umi! 

I'm asking for a feature request to have something similar to create-react-app where a developer can execute a 'npm eject' command that will output the webpack config file and confer control of webpack over to the dev. This would be a really useful feature to have, and I see that this is something other developers are interested in. 

E.g. 
https://github.com/sorrycc/blog/issues/55 (comments by @jiangzm and @WeiJieGitHub) 

I also saw that this was a concern brought up in Roadhog via GH Issue, and @sorrycc said that eject was not in the plan for Roadhog. I'm curious if this decision has changed with his involvement in Umi.

**Comment by sorrycc** [comment]
`umi eject` will not be considered in the near future, this priority is relatively low.

**Comment by heya-aron** [comment]
Thanks for the prompt response. Would you guys be open to a PR that addresses it?
