### ISSUE TITLE
[HMR] css reload failed

### ISSUE THREAD

**Issue by afc163** [umijs/umi#1420]
```
[HMR] css reload http://127.0.0.1:8000/umi.css
```

less 修改后控制台有这个信息，但是样式不生效。

http://github.com/ant-design/ant-design-pro

**Comment by sorrycc** [comment]
试过 umi 本身的项目没有问题，迟点我再试试 antd 的。

**Comment by sorrycc** [comment]
firefox 有问题，chrome 没问题，具体原因待查。

**Comment by xiaohuoni** [comment]
有没有可能是antd-pro-merge-less或者antd-theme-webpack-plugin的问题？
