### ISSUE TITLE
mock DELETE  

### ISSUE THREAD

**Issue by yuandapeng** [umijs/umi#1431]
mock 使用restful 接口 delete  的时候获取不到 body 中的参数

**Comment by sorrycc** [comment]
请给可浮现的仓库。

**Comment by yuandapeng** [comment]
我是在with dva example 中做的
mock/api.js
export default {
    "DELETE /api/noBody/":(req,res)=>{
        console.log(req.body);
        res.json({
            body:req.body
        });
    }
}
//发起delete请求
<Button
        onClick={() => {
         fetch("/api/noBody",{
             body:JSON.stringify({
                 noBody:"yes"
             }),
             method:"DELETE"
         })
        }}
      >
        noBody
      </Button>

**Comment by yuandapeng** [comment]
![image](https://user-images.githubusercontent.com/11659997/48190344-6f265380-e37d-11e8-978f-66c0292e3170.png)

**Comment by codering** [comment]
http delete本来就不支持传body
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE

**Comment by yuandapeng** [comment]
我给你的截图你看到了吗? body里面是可以获取到参数的，我觉得是你封装的问题

**Comment by codering** [comment]
dva用fetch，你用jquery来说问题不好吧

**Comment by yuandapeng** [comment]
我用axios 的delete 也是一样的获取不到

**Comment by yuandapeng** [comment]
![image](https://user-images.githubusercontent.com/11659997/48322615-78583e80-e663-11e8-9eb5-adab6dc8f127.png)

**Comment by codering** [comment]
嗯，我的错，没仔细看文档。 
应该是我记混了，我是开发后端的，我在用spring的过程中就遇到delete传了body也会被丢弃的情况，所以当时认为不支持这样的用法， sorry。

另：我不是这个工具开发者。

**Comment by fordguo** [comment]
from the code
https://github.com/umijs/umi/blob/c5805e90e5d846eda1a30348a45f77cbdf11a351/packages/umi-build-dev/src/plugins/mock/createMockMiddleware.js#L11

Mock data does not support `delete body`

**Comment by wangxingkang** [comment]
网上查了下  http delete 请求 是否支持body传参 説法不一 ，大神们 是什么意见！

**Comment by wangxingkang** [comment]
@yuandapeng const BODY_PARSED_METHODS = ['post', 'put', 'patch'];  添加上 delete就可以拿到

**Comment by yuandapeng** [comment]
thank
