### ISSUE TITLE
umi test如何测试models里effects的方法

### ISSUE THREAD

**Issue by XanderXueMingJi** [umijs/umi#1432]
umi: 2.1.1
在models里, 我该怎么写test文件?

**Comment by sorrycc** [comment]
这和 umi 没有什么关系，model 还是对象，之前怎么测还是怎么测。

**Comment by XanderXueMingJi** [comment]
之前项目测试(sgag), 主要是测试actions, reducer, 现在umi的主体操作集中在models文件了, 不知道怎么下手

**Comment by XanderXueMingJi** [comment]
对于组件的测试, 其中我写了expect(wrapper.find('Button').length).toBe(1); 在组件内我有引用antd的Button, 但console.log结果是0, 请问这是怎么回事?
