### ISSUE TITLE
2.0.3model问题

### ISSUE THREAD

**Issue by devmsg** [umijs/umi#1435]
umi版本:   "^2.0.3"

目前遇到以下问题（讨论）

1. modal的按需加载
描述：假如有2个model针对不同的路由A,B. A路由加载完毕（Amodel也相应加载完毕），从A跳入B，在B的modal访问A的model无效（activeType: nsp+type）
2. 路由 涉及到的model问题
描述：
假如目前的路由
![image](https://user-images.githubusercontent.com/15261658/48248695-58dacf00-e433-11e8-9249-24f687d0876e.png)
--pages
--------a
------------a1
-----------------a1model
------------a2
-----------------a2model
------------a3
-----------------a3model

a1model 、a2model、a3model 中都注册了同名的effects,  在watcher的情况下，切换路由会导致全部的同名effects执行!(目前判断是take时机的问题)
![image](https://user-images.githubusercontent.com/15261658/48249016-8bd19280-e434-11e8-9189-ca287efa8dfe.png)
三个model都会进行stopActionType的监听，

**Comment by xiaohuoni** [comment]
监听应该都是全局监听的吧，不是要在监听里面判断路由，来区分吗？还是我理解错误？
