### ISSUE TITLE
更好的修改配置路由的方式

### ISSUE THREAD

**Issue by yutingzhao1991** [umijs/umi#1438]
当前 block 命令在添加完成区块之后如果是配置路由那么会修改配置，这块的逻辑实现在 https://github.com/umijs/umi/blob/master/packages/umi-build-dev/src/utils/writeNewRoute.js 是基于 esprima 把配置解析成为 ast 后实现的，这段逻辑后面也会用到 generate 上面。不过现在这个存在一些问题还有待完善：

1. 逻辑太复杂，直接操作 ast 的代码可读性很差
2. 没有考虑路由的 layout

关于 1 我觉得可以封装下 esprima 提供更方便的操作方式，可以看看有没有现成的包。比如可以像下面这样用：

```js
parse(code).getExport('default').getProperty('routes').isArray().inserNode('{}').write();
```

关于 2 可以扩展 `--name` 的配置，当用户传入一个 path 时可以对应的把区块插入到 path 对应的 layout 下。

**Comment by yutingzhao1991** [comment]
cc @clock157

**Comment by clock157** [comment]
学习了一下 ast 相关的东西，分享一个[小工具](https://astexplorer.net/)。
我通过实现 layout path 试了下手：https://github.com/clock157/umi/commit/ff8d43566f37a2a14e0aa7230945bb8b150f7c82
稍后我把这整块逻辑再优化下。
