### ISSUE TITLE
yarn 安装出错，麻烦检查下 package.json dependencies

### ISSUE THREAD

**Issue by zysam** [umijs/umi#1446]
Couldn't find any versions for "scheduler" that matches "^16.6.2"
? Please choose a version of "scheduler" from this list: (Use arrow keys)
---
warning umi-plugin-react > umi-plugin-dva > dva > react-router-redux@5.0.0-alpha.9: This project is no longer maintained.
[3/5] 🚚  Fetching packages...
error http://registry.npm.taobao.org/@types/react-router-dom/download/@types/react-router-dom-4.3.1.tgz: Integrity check failed for "@types/react-router-dom" (computed integrity doesn't match our records, got "sha1-TCYZ/CTE+ofJ/Rj0+0pD/mP71cY=")
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

相关 package.json 来自 `ant-design-pro`

```
"umi-plugin-react": "^1.2.0"
```

yarn version : v1.12.3

**Comment by sorrycc** [comment]
https://github.com/facebook/react/issues/14208
react 的问题。
