### ISSUE TITLE
PWA build different output

### ISSUE THREAD

**Issue by sl5310** [umijs/umi#1447]
I am to run `npm run build` on local,

this is the output
`File sizes after gzip:`
`671.25 KB  dist/umi.js`
`43.66 KB   dist/umi.css`
`2.39 KB    dist/pwacompat.min.js`
`1.46 KB    dist/precache-manifest.e0f1fd9695f6089d67a7d45231fa938f.js`
`570 B      dist/service-worker.js`

npm version: 6.4.1

but when i going to `npm run build` on server
this is the output
`File sizes after gzip:`
`691.35 KB  dist/umi.js`
`43.57 KB   dist/umi.css`
`1.38 KB    dist/precache-manifest.cf5b8c4232e71656adc91f29dbca8feb.js`
`548 B      dist/service-worker.js`

npm version: 6.4.1

it is less `2.39 KB    dist/pwacompat.min.js` and doesn't generate `manifest.json`

**Comment by sorrycc** [comment]
How to reproduce it?
