### ISSUE TITLE
尝试React 16.7用带Hook的函数组件重写Class组件，this.props该怎么处理？

### ISSUE THREAD

**Issue by zwl1619** [umijs/umi#1451]
尝试React 16.7用带Hook的函数组件重写Class组件，this.props该怎么处理？
比如umi-antd-mobile中的BasicLayout.js文件第22行：
https://github.com/jinjinwa/umi-antd-mobile/blob/master/src/layouts/BasicLayout.js
   
像下面这样写对吗？但是不太清楚改写后props该传什么值？
```
function BasicLayout(props) {
//...
  const { children, location, loading } = props;
//...
}
```

**Comment by sorrycc** [comment]
和 umi 无关，自己研究下吧。

**Comment by xiaohuoni** [comment]
Hook用来做内部state的吧，和props不冲突吧？
