### ISSUE TITLE
model里面的错误不会显示在控制台

### ISSUE THREAD

**Issue by hqzh** [umijs/umi#1452]
比如我在model里面console.log(a),a is undefined不会显示在控制台,,而是直接Antd message了一条错误信息,这种错误应该只要显示在控制台就好了吧

**Comment by sorrycc** [comment]
这是因为你加了全局的 onError，可以在 onError 里打印出来。

**Comment by hqzh** [comment]
`import { message } from 'antd';

export function config() {
  return {
    onError(err) {
      err.preventDefault();
      message.error(err.message);    //dva.js这里作怪
    },
    initialState: {
      // global: {
      //   text: 'hi umi + dva',
      // },
    },
  };
}`
