### ISSUE TITLE
文档的基本配置页面，plugins项为什么要两个umi-plugin-react？

### ISSUE THREAD

**Issue by zwl1619** [umijs/umi#1453]
文档的基本配置页面，plugins项为什么要两个umi-plugin-react？就是下面截图红框里面：

![image](https://user-images.githubusercontent.com/13177997/48465224-1c391a00-e81d-11e8-95bd-acdee679e34b.png)
文档：https://umijs.org/zh/config/#%E5%9F%BA%E6%9C%AC%E9%85%8D%E7%BD%AE

**Comment by yutingzhao1991** [comment]
只是一个说明，说明插件可以直接配置插件名称，也可以传入数组用于支持第二个参数为插件配置。不过这里确实容易误导。
