### ISSUE TITLE
如何给路由加一个全局钩子，例如页面跳转时判断token是否存在，没有则重定向到登录页

### ISSUE THREAD

**Issue by himatthew** [umijs/umi#1454]
实现类似vue-router的beforeEach功能

**Comment by ikobe** [comment]
试一下这个： https://umijs.org/zh/guide/router.html#%E6%9D%83%E9%99%90%E8%B7%AF%E7%94%B1

**Comment by xiaohuoni** [comment]
试一下这个https://github.com/xiaohuoni/umi-plugin-authorize
