### ISSUE TITLE
为什么我生成.umi下面的文件少了呢

### ISSUE THREAD

**Issue by xgj1988** [umijs/umi#1457]
我生成的文件有
DvaContainer.js
LocaleWrapper.jsx
router.js
umi.js

但是antd design pro 下面的文件有

DvaContainer.js
initDva.js
initHistory.js
LocaleWrapper.jsx
polyfills.js
router.js
umi.js 
少了好多。

**Comment by yutingzhao1991** [comment]
.umi 下面都是临时文件，没用到相关功能是不会有的，这个没关系。

**Comment by xgj1988** [comment]
@yutingzhao1991  但是我的项目和antd design pro 一样，为什么在IE下面运行不了，。报错，错误内容为  SCRIPT438: 对象不支持“find”属性或方法

**Comment by xiaohuoni** [comment]
@xgj1988 设置target

**Comment by xgj1988** [comment]
@yutingzhao1991  不行哦
