### ISSUE TITLE
希望在umi-build-dev的getRouteConfigFromDir里添加/index/xxxx  -> /xxxx/规则

### ISSUE THREAD

**Issue by dxcweb** [umijs/umi#1459]
已经存在的规则  
// /xxxx/index -> /xxxx/
  newPath = newPath.replace(/\/index$/, '/');

希望改为
// /xxxx/index -> /xxxx/ or /index/xxxx  -> /xxxx/
newPath = newPath.replace(/\/index/, '');

**Comment by sorrycc** [comment]
`/index/xxxx -> /xxxx/` 这个规则看起来很奇怪，为啥会有这需求？

**Comment by dxcweb** [comment]
下面生成出来的router的结构。我希望 /index/news等不需要加//index/这一级也可以正常访问
[
  {
    path: '/',
    component: './index/_layout',
    routes: [
      { path: '/', component: './index/index' },
      { path: '/index/news', component: './index/news' },
      { path: '/index/video', component: './index/video' },
      ...
    ]
  },
  {
    path: '/admin',
    component: './admin/_layout',
    routes: [...]
  }
];

**Comment by sorrycc** [comment]
需求比较特殊，你可以自行通过插件实现。
