### ISSUE TITLE
publicPath 出bug了吗？

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#1460]
在pro的项目里面配置publicPath:"/abc/"
执行build之后，请求的文件是/abc/umi.js但是实际上生成的没有放到abc文件夹下面
<img width="275" alt="wx20181115-165444 2x" src="https://user-images.githubusercontent.com/11746742/48541241-2cbdc300-e8f7-11e8-93fb-e2c46326c741.png">

**Comment by sorrycc** [comment]
就是这样的，要放到 /abc/ 下需要配 outputPath 。

**Comment by xiaohuoni** [comment]
只配置publicPath:"/abc/"，发布部署会提示
找不到相关文件

**Comment by sorrycc** [comment]
publicPath 和输出路径无关，也可以看下 webpack 的文档。

**Comment by mrqi** [comment]
类似问题，npm run start 后，设置的publicPath也无效，访问的资源路径依然是 根目录。。如 publicPath:"/cloud/", localhost:port/访问，加载的umjjs文件依然在根目录下 /umi.js，我一定是哪里不对吧？

**Comment by mrqi** [comment]
Sorry,我说的是ant design pro。。。。

**Comment by theprimone** [comment]
@xiaohuoni 你好，我也遇到了这个问题，请问解决了吗？

配置了 `publicPath: '/public/'` 之后编译生成的文件如下：

```
dist/
  -js/
  -images/
  -index.html
  -umi.css
  -umi.js
```

`index.html` 中 `umi.css` 和 `umi.js` 都会带上 `/public/` 前缀。现目前我的临时解决方案是自己新建一个 `public/` 目录把 `umi.css` 和 `umi.js` 放进去 \_(:3J∠)\_

**Comment by cheogo** [comment]
@theprimone publicPath 改变的是访问地址，输出地址需要使用 outputPath
