### ISSUE TITLE
lint插件化机制提个建议

### ISSUE THREAD

**Issue by younth** [umijs/umi#1475]
之前是 `@ali/def` 的重度使用者，最近用 umi 开发一个项目，感觉很nice。希望把默认把 `.eslintrc` 干掉把，用 `umi lint src`这种形式提供下支持。另外 `vue`要是能支持该多美好

**Comment by younth** [comment]
另外。是不是可以在支持 mock跟proxy能同时运行，有这种需求，部分数据走mock部分走proxy

**Comment by xiaohuoni** [comment]
mock和proxy现在是支持同时的使用的吧？
vue的话，https://github.com/umijs/umi-plugin-vue 现在有一个这个。
当前版本的.eslintrc应该是没有的吧，下个版本要加回来。https://github.com/umijs/umi/issues/1365

**Comment by yutingzhao1991** [comment]
lint 这个在内部 bigfish（基于 umi） 是有这样的功能的，可以了解下看看。之前还有考虑要不要把 lint 这块给开源。

**Comment by younth** [comment]
@xiaohuoni 刚试了下，mock跟proxy可以同时。mock优先，没问题了。。
