### ISSUE TITLE
feat: 支持 -w 选项

### ISSUE THREAD

**Issue by Aladdin-ADD** [umijs/umi#1476]
`umi build -w`可以将构建结果输出到磁盘。

背景：我们的项目是 (b)egg + antd-pro（前后端是在一个仓库）。

为了解决本地开发的问题，启动命令拆分为:
+ 启动 antd-pro: `umi dev -w` （输出到 egg 的public目录）
+ 启动 egg：`egg dev`

或者，有其它建议？\(^o^)/~

**Comment by sorrycc** [comment]
欢迎 pr。

**Comment by yutingzhao1991** [comment]
应该最好有一个 egg 的插件，能够直接通过 `egg dev`  就能启动最好。或者是不是能够在 egg 那边把HTML 的请求转发过来也能解决这个问题。

cc @popomore

**Comment by popomore** [comment]
https://github.com/eggjs/egg-ant-design-pro

**Comment by Aladdin-ADD** [comment]
oops, missed it, thanks!
