### ISSUE TITLE
开启dynamicImport: true,不写 namespace 的 model 在 build 之后被注册为 undefined

### ISSUE THREAD

**Issue by masquevil** [umijs/umi#1483]
我写的目录结构是：

```
├── pages
│   └── martin
│       ├── index.js
│       └── models
│           └── martin.js
```

model 里没有写 namespace，然后在 `index.js` 里调用 `export default connect(({ martin }) => ({ martin }))(Page);`。

在 `yarn start` 的时候可以看到正常的效果，但在 `yarn build` 后得到的 martin 是 undefined。且调用 `window.g_app._store.getState()` 可以看到结果为 `{ ..., "undefined": [我真正的martin] }`。
如果在 model 里写上 namespace，则 build 后的结果正确。

文档上的介绍是：
- 按目录约定注册 model，无需手动 app.model
- 文件名即 namespace，可以省去 model 导出的 namespace key

所以想知道这是一个 bug，还是有哪些步骤被我遗漏了？

**Comment by masquevil** [comment]
https://github.com/masquevil/umi-demo
umi 的版本是 2.2.7

**Comment by masquevil** [comment]
试了一下 with-dva，因为 `list/models/a.js` 里面是有 namespace 的，如果去掉 namespace，则也会在 umi build 时变成 undefined，umi dev 时正常。

**Comment by xiaohuoni** [comment]
@masquevil 一样的操作，还是可以的。你不可以的demo，发给我看看？

**Comment by xiaohuoni** [comment]
我试试，我刚刚是设置了，最外层的  disableDynamicImport: true,

**Comment by zouliang073** [comment]
我也是这个问题，搞了半天，才明白

**Comment by sorrycc** [comment]
急用可以用 umi@beta 。

**Comment by grunmin** [comment]
@sorrycc 那个beta? 我试了beta.6也不行

**Comment by Vultur** [comment]
dynamicImport: false 或者不设置可解决。

**Comment by wangjianio** [comment]
umi 2.3.2  遇到同样问题，使用 ant design pro

`umi-plugin-react` 插件配置了

```
dynamicImport: {
    loadingComponent: './components/PageLoading/index',
},
```

页面级 model 不写 namespace 会出现这个问题，

手动指定 namespace 可解决。

**Comment by CynthiaNC** [comment]
不设置 dynamicImport 即可，build 出来就是可以的

**Comment by wangyichen1064431086** [comment]
> umi 2.3.2 遇到同样问题，使用 ant design pro
> 
> `umi-plugin-react` 插件配置了
> 
> ```
> dynamicImport: {
>     loadingComponent: './components/PageLoading/index',
> },
> ```
> 
> 页面级 model 不写 namespace 会出现这个问题，
> 
> 手动指定 namespace 可解决。

请问下这个问题现在解决了吗？ 我这里发现还是需要手动指定 namespace
