### ISSUE TITLE
umi-plugin-react hd高清开启字体、高度变小

### ISSUE THREAD

**Issue by dongkang1993** [umijs/umi#1485]
750的设计稿，hd开启后字体为何变小了一倍，容器高度也是一样

**Comment by xiaohuoni** [comment]
375

**Comment by dongkang1993** [comment]
非常感谢 @xiaohuoni

**Comment by dongkang1993** [comment]
750是iphone6页面宽度，iOS 两倍分辨率，要在每个页面加
  componentDidMount(){
    if (document.documentElement.clientWidth >= 750) {
        vw(100, 375);
      } else {
        flex();
      }
  }

@PuShaoWei

**Comment by Nose407** [comment]
> 750是iphone6页面宽度，iOS 两倍分辨率，要在每个页面加
> componentDidMount(){
> if (document.documentElement.clientWidth >= 750) {
> vw(100, 375);
> } else {
> flex();
> }
> }
> 
> @pushaowei

这个是在什么地方添加的呢？我添加上去怎么不对？

**Comment by m9rco** [comment]
@Nokecy 这个是在`hd`插件里的逻辑

**Comment by m9rco** [comment]
需要把其引入进来，不过我后来取消这种方式了，侵入太多
