### ISSUE TITLE
Umi project stuck on umi dev in windows 10

### ISSUE THREAD

**Issue by macashok** [umijs/umi#1486]
Hello,  I am working on a enterprise level umi project. The project builds and runs perfectly fine on macbook. However on windows 10, it never builds and gets stuck on umi dev forever. Also, there are no error logs that can help me to identify issue. 
 The project has the below configuration. Any help is greatly appreciated.

"umi": "^1.3.18",
 "umi-plugin-dva": "^0.6.3",
  "umi-plugin-polyfill": "^0.2.0",
 "umi-plugin-routes": "^0.1.2",

**Comment by sorrycc** [comment]
Try `DEBUG = umi * umi dev` and show me the error log.

**Comment by branchesgit** [comment]
dumi stuck  when config copy 
xpress:router:layer new '/' +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 0.0.0.0 +6s
  portfinder:testPort entered testPort(): trying 0.0.0.0 port 8001 +6s
  portfinder:testPort done w/ testPort(): OK 0.0.0.0 port 8001 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 8001 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 127.0.0.1 +1ms
  portfinder:testPort entered testPort(): trying 127.0.0.1 port 8001 +1ms
  portfinder:testPort done w/ testPort(): OK 127.0.0.1 port 8001 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 8001 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is ::1 +0ms
  portfinder:testPort entered testPort(): trying ::1 port 8001 +0ms
  portfinder:testPort done w/ testPort(): OK ::1 port 8001 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 8001 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 192.168.3.44 +0ms
  portfinder:testPort entered testPort(): trying 192.168.3.44 port 8001 +0ms
  portfinder:testPort done w/ testPort(): OK 192.168.3.44 port 8001 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 8001 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 169.254.9.1 +1ms
  portfinder:testPort entered testPort(): trying 169.254.9.1 port 8001 +1ms
  portfinder:testPort done w/ testPort(): OK 169.254.9.1 port 8001 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 8001 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is 192.168.30.20 +0ms
  portfinder:testPort entered testPort(): trying 192.168.30.20 port 8001 +0ms
  portfinder:testPort done w/ testPort(): OK 192.168.30.20 port 8001 +0ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 8001 +0ms
  portfinder:getPort in eachSeries() iteration callback: host is null +0ms
  portfinder:testPort entered testPort(): trying null port 8001 +0ms
  portfinder:testPort done w/ testPort(): OK null port 8001 +2ms
  portfinder:getPort in eachSeries() iteration callback testPort() callback with a success for port 8001 +2ms
  portfinder:getPort in eachSeries() result callback: openPorts is [ 8001, 8001, 8001, 8001, 8001, 8001, 8001 ] +0ms
