### ISSUE TITLE
打包后的缓存问题

### ISSUE THREAD

**Issue by Veigar-C** [umijs/umi#1489]
貌似.js 没有像图片那样加1800.64b69f2 类似字符串，用nginx跑起来后得清掉浏览器缓存才能看到

**Comment by sorrycc** [comment]
配置 hash: true 。

**Comment by Veigar-C** [comment]
好的，谢谢

**Comment by huangronggod** [comment]
@sorrycc 加了hash后，依然要清除浏览器缓存才能看到最新的界面，还有其它的什么方法吗，请问

**Comment by wangxingkang** [comment]
刷新浏览器 就可以了吧
