### ISSUE TITLE
Compiling... ghost did not leave

### ISSUE THREAD

**Issue by yangbin1994** [umijs/umi#149]
https://github.com/umijs/umi/issues/29

umi:
1.0.1
@local

macOSX:
ProductName:	Mac OS X
ProductVersion:	10.13.1
BuildVersion:	17B1003

npm
5.6.0

node
v8.9.1

**Comment by sorrycc** [comment]
* 考虑在 Compiling... 时自动联系 node 端定时 `touch touer.js` 来解决
