### ISSUE TITLE
【建议】是否在umi package 中添加一个  index.d.ts

### ISSUE THREAD

**Issue by amily4555** [umijs/umi#1493]
每次 webstorm IDE 自动引入都类似 如下

![image](https://user-images.githubusercontent.com/2802841/48822246-46e41f00-ed97-11e8-87de-538b2b162fbd.png)

每次都需手动修改路径，有点难受 ~~

**Comment by amily4555** [comment]
在今天新发布的 webstorm 2018.3 中修改了这个 bug, 能自动的引入；

但还有一个不友好的是 如果我在 一个 ts 文件中引入多个 umi 组件或方法的时候 

![image](https://user-images.githubusercontent.com/2802841/48936390-c152a180-ef45-11e8-917a-0364fc498f56.png)

友好的自动引入期望为 

```
import {dynamic, router, Redirect, Link, NavLink } from 'umi';
```

**Comment by xiaohuoni** [comment]
@amily4555 这个要怎么做？

**Comment by amily4555** [comment]
我提交个PR吧， umi 上 d.ts 文件都是手写的吧

**Comment by amily4555** [comment]
see pr #1516

**Comment by xiaohuoni** [comment]
学习了。只要写了正确的type文件，就可以正确自动引入是吗？

**Comment by sorrycc** [comment]
Close via #1516

**Comment by amily4555** [comment]
resubmit PR 

Close via #1536
