### ISSUE TITLE
umi 支持使用 react@16.7.0 吗？

### ISSUE THREAD

**Issue by yuler** [umijs/umi#1497]
![image](https://user-images.githubusercontent.com/6996341/48852690-debe2900-ede8-11e8-999f-97274cbcb852.png)

目前默认的是 react@16.6.3

**Comment by sorrycc** [comment]
支持，`yarn add react@16.7.0-alpha.2 react-dom@16.7.0-alpha.2`，然后重启 `umi dev` 就好。
