### ISSUE TITLE
hope cli adds help information.

### ISSUE THREAD

**Issue by yangbin1994** [umijs/umi#150]
```bash
$ umi help
Unknown script help.
```

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/commit/3abd91dd0b7973c5f446676bf407425e7109818c

**Comment by xiaohuoni** [comment]
这个添加了，但是还可以补充的更完整。就先不关闭了。

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/44246111-0496c900-a20f-11e8-92b2-4d11bdaa2d73.png)
