### ISSUE TITLE
约定方式的路由怎么用面包屑？

### ISSUE THREAD

**Issue by nanhualyq** [umijs/umi#1504]
看了官网文档的这个例子，是配置方式的routes，那约定方式的routes从哪里可以拿到呢？
谢谢指教。
![image](https://user-images.githubusercontent.com/6212850/48896134-d82fc000-ee81-11e8-9631-f6c3863192f3.png)

**Comment by Instanced** [comment]
props能拿到

**Comment by wangxingkang** [comment]
我以前的做法是额外去配置和路径相关的数据类似
```
export default {
  '/dashboard': {
     name: '首页'
  }
}
```

配合约定式路由去实现面包屑，会有点麻烦
