### ISSUE TITLE
请教个关于嵌套路由的问题

### ISSUE THREAD

**Issue by ChenAt** [umijs/umi#1505]
![image](https://user-images.githubusercontent.com/13502799/48897452-1a0e3580-ee85-11e8-8bdf-6679c96d1065.png)

请问菜单 path 一定需要与父 path 一层一层相加吗？ 拿这个 Articles 页面举例子，我 path 能不能写个绝对路径，比如  /aaa/bbb/ccc 呢？ 但是又要保持嵌套关系，用于菜单生成以及看起来比较直观。

我们公司之前有个旧的 react 项目，现在想集成 umi  的方式，但希望页面旧路径能保留，请问有什么思路吗？

**Comment by sorrycc** [comment]
1. 里面的必须是外面的子集，因为会先匹配外面，然后再进去匹配里面的
2. 路径可以写相对路径，会自动把上一级的 path 拼接进去的
