### ISSUE TITLE
AssertionError: Invalid key dva from plugin 如何搞,有没有人遇见过.

### ISSUE THREAD

**Issue by RockyLiys** [umijs/umi#1506]
![image](https://user-images.githubusercontent.com/4220440/48899205-ef72ab80-ee89-11e8-8d2e-ad432ff677b2.png)
![image](https://user-images.githubusercontent.com/4220440/48899253-10d39780-ee8a-11e8-92c0-2ebd8684f4dc.png)

不知道,怎么出错了,我那里配置错误了
我的config.js
export default {
  plugins: [
    // ref: https://umijs.org/plugin/umi-plugin-react.html
    ['umi-plugin-react', {
      antd: true,
      dva: {
        immer: true
      },
      dynamicImport: true,
      title: 'Antd-web',
      dll: false,
      routes: {
        exclude: [
          /model\.(j|t)sx?$/,
          /service\.(j|t)sx?$/,
          /models\//,
          /components\//,
          /services\//,
        ],
      },
      hardSource: false,
    }]
  ],
  sass: {
    test: /\.sass$/,
    loaders: ["style", "css?sourceMap", "postcss", "resolve-url",  
    {
      loader: "sass-loader",
      options: {
        sourceMap: true,
        indentedSyntax: true
      }
    }]
  },
  // 路由配置
  routes: pageRoutes,
  // Theme for antd
  // https://ant.design/docs/react/customize-theme-cn
  theme: {
    'primary-color': defaultSettings.primaryColor,
  }
}

**Comment by huhanhaha** [comment]
楼主解决没有？？我也遇到了

**Comment by eruca** [comment]
me too

**Comment by White-Lee** [comment]
try
`npm install --save umi-plugin-react`
then config the plugin in `.umirc.js` 
```
export default {
  plugins: [
    [
      'umi-plugin-react',
      {
        dva: true,
      },
    ]
  ],
};
```

**Comment by White-Lee** [comment]
try
`npm install --save umi-plugin-react`
then config the plugin in `.umirc.js` 
```
export default {
  plugins: [
    [
      'umi-plugin-react',
      {
        dva: true,
      },
    ]
  ],
};
```

**Comment by pgliuya** [comment]
仔细查下.umirc.js配置文件，有没有特殊符号之类的。

**Comment by Hellovolcanoofficial** [comment]
部分文件以.开头，vscode等编辑器可以看到但是文件系统finder等看不到，漏掉就会与这个错误啦

**Comment by chen-kosile** [comment]
你用的typescript的吗，在.umirc.tsx 中将dva改为true就可以了

**Comment by bincute** [comment]
> 你用的typescript的吗，在.umirc.tsx 中将dva改为true就可以了。今天用umi也碰到了

不行呀，而且这样改dva属性下面的配置怎么办？

**Comment by gdchent** [comment]
"devDependencies": {
    "umi-plugin-react": "1.8.4"
  }
把版本号改为1.8.4看看

**Comment by lwbweb** [comment]
dva2+的版本可以设置为dva:true，3+的版本不行

**Comment by xrkffgg** [comment]
组件名称不要使用 app 关键字
