### ISSUE TITLE
使用动态路由时 lint-staged 如何匹配校验

### ISSUE THREAD

**Issue by Vultur** [umijs/umi#1507]
```
"lint-staged": {
    "**/*.{js,jsx,less}": [
      "prettier --write",
      "git add"
    ],
    "**/*.{js,jsx}": "npm run lint-staged:js",
    "**/*.less": "stylelint --syntax less"
  }
```

该配置会提示 `No files matching the pattern "/Users/Documents/.js" were found.`

**Comment by xiaohuoni** [comment]
这两个东西会冲突吗？？

**Comment by Vultur** [comment]
> 这两个东西会冲突吗？？

ESLint 校验通不过

**Comment by yutingzhao1991** [comment]
两点：

- `.umi` 里面的内容应该 eslint 中忽略掉
- `/Users/Documents/.js` 这个找不到应该是个错误，只是 lint 查出来的，本身和 lint 没有关系

**Comment by GGwujun** [comment]
@sorrycc 动态路由真的有问题，以$开头的动态文件eslint在匹配的时候找不到路径。建议这个动态路由符号自己可以配置，如果不用eslint检测那就没问题，如果要的话就感觉好坑

**Comment by sorrycc** [comment]
是 lint-stage 的 bug 吧。

**Comment by sorrycc** [comment]
`$` 前缀确实和 bash 有些冲突，下个版本可以和 nuxt.js 类似，用 `_` 前缀。

**Comment by weishijun14** [comment]
如何解决？

**Comment by tw-yaxu** [comment]
我这里也出现了这个问题，`$`标识符在bash里会被当成变量处理，所以以它为前缀的名称会变为空。现在有解决的办法吗？

**Comment by Lynn0108** [comment]
> `$` 前缀确实和 bash 有些冲突，下个版本可以和 nuxt.js 类似，用 `_` 前缀。

请问现在解决了吗？

**Comment by CooCleC** [comment]
这个问题现在有什么解决方案么？？

**Comment by CooCleC** [comment]
@sorrycc 请问这个问题需要怎么解决？

**Comment by songchengen** [comment]
我倒腾出来了，lint-stage的执行换成配置文件，修改一下执行脚本就行，代码如下


.lintstagedrc.js
```javascript
module.exports = {
  '**/*.less': 'stylelint --syntax less',
  '**/*.{js,jsx,ts,tsx}': files => {
    return `npm run lint-staged:js ${files.map(file => file.replace(/\$/g, '\\$')).join(' ')}`;
  },
  '**/*.{js,jsx,tsx,ts,less,md,json}': ['prettier --write'],
};
```

取了个巧，有更好的方式望告知🐶

**Comment by CooCleC** [comment]
@songchengen umi3.0更换了$为[]，可能会解决这个问题

**Comment by songchengen** [comment]
@CooCleC 一时半会儿不会切换到3，而且umi3的动态可选路由也还没有解决方案
