### ISSUE TITLE
umi对项目的名称识别有问题,如(umi.html)关联不到loader

### ISSUE THREAD

**Issue by Liuqing650** [umijs/umi#152]
目前umi对项目的名称识别有问题
如果使用dva创建一个项目名称为: umi.demo 
```
dva new umi.demo
```
这个项目中就关联不到loader，导致import .png/.svg出错。

错误信息如图

![](https://liuqing650.github.io/view/umi/issue/umi.demo.png)

如果创建项目名称为: umi-demo，

```
dva new umi-demo
```

那将一切完好.

**Comment by sorrycc** [comment]
我试了下用 `umi.demo` 作为项目名，然后在 jsx 里这样引 png 文件，没发现问题。

```
<img src={require('../assets/umi.png')} />
```

你是 mac 还是 windows ?

**Comment by Liuqing650** [comment]
很抱歉，我写错项目名字了。
用的是windows 和 ubuntu ，
刚刚在 ubuntu 中分别新建了两个项目

一个项目 `umi.demo` **正常**

一个项目 `demo.html`  **异常**

两个项目下 `pages/index.js` 中都是下面的代码， 结果如上加粗文字所示。
猜测应该是文件夹后缀 `.html` 引起的问题

```
import React from 'react';
import { connect } from 'dva';
import styles from './index.css';

function IndexPage() {
  return (
    <div className={styles.normal}>
      <img src={require('../assets/yay.jpg')} />
    </div>
  );
}

IndexPage.propTypes = {
};

export default connect()(IndexPage);
```

`demo.html`  异常页面结果图
![](https://liuqing650.github.io/view/umi/issue/umi-require.png)
