### ISSUE TITLE
umi2 umi dev为什么不显示错误信息？

### ISSUE THREAD

**Issue by AdmireWang** [umijs/umi#1522]
![image](https://user-images.githubusercontent.com/5096573/48965856-2d91db80-f000-11e8-9a9c-debf4343f650.png)
升级了umi2，umi dev时报错，只显示错误数量，不显示错误信息，为什么会这样？

**Comment by okoala** [comment]
window 下还是用 git bash 吧~

**Comment by wangwii** [comment]
我也遇到同样的错误，请问要怎么查看具体的报错愿意呢？
```umi dev ```
<img width="661" alt="Screen Shot 2019-06-14 at 01 26 10" src="https://user-images.githubusercontent.com/1000834/59454471-beb58c00-8e44-11e9-97fa-b3bdfd712565.png">

``` umi build```
<img width="661" alt="Screen Shot 2019-06-14 at 01 26 59" src="https://user-images.githubusercontent.com/1000834/59454504-d260f280-8e44-11e9-8935-00bbaa5b6c1a.png">

**Comment by yuxiang660** [comment]
我遇到同样的问题，请问有解决方案吗？没有具体报错信息，很影响排错。请问大神们有什么办法吗？
我的环境如下：
---
umi:  2.13.3
Windows: Microsoft Windows [Version 10.0.19041.21]
---
