### ISSUE TITLE
请问这个配置是如何简化reducer的编写的

### ISSUE THREAD

**Issue by DXDZY** [umijs/umi#1524]
![image](https://user-images.githubusercontent.com/15250383/48978766-d36e4480-f0eb-11e8-8b58-c107abbaa11f.png)

**Comment by DXDZY** [comment]
如果配置了这个，reducer要怎么写那

**Comment by dengfuping** [comment]
@DXDZY [dva-immer](https://github.com/dvajs/dva/tree/master/packages/dva-immer) 底层是 `immer`，参考 [immer 文档](https://github.com/mweststrate/immer) 即可。
