### ISSUE TITLE
If the package is in devDependencies, it will report the error.

### ISSUE THREAD

**Issue by chenshuai2144** [umijs/umi#1525]
eslint 只能判断代码中不引用devDependencies 中的包，需要一个新的脚本来判断 不使用的包在devDependencies中

**Comment by sorrycc** [comment]
和 umi 有关？

**Comment by sorrycc** [comment]
你是指 dll 构建的那个报错？umi 没有包含 eslint 的。

**Comment by chenshuai2144** [comment]
嗯，dll 中构建的包如果在 devDependencies 报错找不到，这个很影响体验

**Comment by sorrycc** [comment]
这个在处理错误提示的时候统一处理下吧。
