### ISSUE TITLE
今天突然发现两个警告，无从下手

### ISSUE THREAD

**Issue by jiahangLee** [umijs/umi#1526]
1、
A parser-blocking, cross site (i.e. different eTLD+1) script, http://t.cn/EvlonFh, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
2、
Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.

**Comment by xiaohuoni** [comment]
这是啥？

**Comment by jiahangLee** [comment]
本地测试的时候都没有出现，放到nginx里面就报错了
第一个是说不应该在渲染后使用document.write()
第二个是接着上面说不能写入
想看看有没有人也遇到过。。。
😢

**Comment by jiahangLee** [comment]
有点尴尬，是我的服务器崩了，cpu占用99%，服务器反应过慢会有这个问题
