### ISSUE TITLE
umi test no console.log info

### ISSUE THREAD

**Issue by ycjcl868** [umijs/umi#1528]
`umi test` not show `console.log` info

![image](https://user-images.githubusercontent.com/13595509/49052711-0158a380-f228-11e8-9b9f-1b6a3e85b280.png)

**Comment by xiaohuoni** [comment]
@sorrycc 好像日志都有这个问题，会被刷掉。

**Comment by xiaohuoni** [comment]
@ycjcl868 https://umijs.org/zh/guide/env-variables.html#clear-console

**Comment by xiaohuoni** [comment]
@ycjcl868 这个可以吗？
