### ISSUE TITLE
npm run build时出现错误

### ISSUE THREAD

**Issue by XanderXueMingJi** [umijs/umi#1529]
版本: umi: 2.1.1

内容: 你好, 我的项目在本地开发时能正常运行, 但是在运行npm run build时报错, 错误提示是
Module build failed (from ./node_modules/_mini-css-extract-plugin@0.4.5@mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve 'fonts/demo.woff'
可是fonts里有demo.woff这个文件, 本地测试时能正常引用到图标, 请问这是怎么回事?

**Comment by sorrycc** [comment]
请给可复现仓库。

**Comment by XanderXueMingJi** [comment]
谢谢你, 刚刚我解决的, 用到的"@/"来设置路径, 倒是能成功了,

**Comment by Jansora** [comment]
1: open `/config/config.js`
2: find key: `cssLoaderOptions`
3: change `modules:ture`  -> `modules:false`

everything should be ok.
