### ISSUE TITLE
在 .umirc.js 里开启 hash: true，yarn start + yarn build 后 yarn start 图片消失

### ISSUE THREAD

**Issue by masquevil** [umijs/umi#1530]
依次执行下面的操作

```bash
yarn create umi      # 功能全选中
yarn
vim .umirc.js           # 增加 hash: true
yarn start                # 此时如果用浏览器访问，可以看见图片
yarn build
yarn start
# 在浏览器中访问 http://localhost:8000/ 发现图片消失
```

**Comment by sorrycc** [comment]
`yarn build` 引起的？不做 build 就不会出现这问题？

**Comment by masquevil** [comment]
> `yarn build` 引起的？不做 build 就不会出现这问题？

噢，又试了一下，不做 build 也会出现。第一次 yarn start 停止后，再 yarn start 就出现问题了。
那看来跟 https://github.com/umijs/umi/issues/1157 这个问题一样了

**Comment by sorrycc** [comment]
复现了。

**Comment by sorrycc** [comment]
hardSource 的问题，先关闭这个插件吧。

**Comment by Verten** [comment]
借个issue问一下，
yarn start之后，打开浏览器访问，console warning
`index.js:2178 Warning: Failed prop type: BasicLayout: prop type `children` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
    in BasicLayout (created by LoadableComponent)
    in LoadableComponent (created by Route)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by _default)
    in Switch (created by _default)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by _default)
    in _default
    in Provider (created by DvaContainer)
    in DvaContainer
__stack_frame_overlay_proxy_console__ @ index.js:2178`

这个是啥原因？

**Comment by cc504156085** [comment]
1、开启项目，yarn start 界面正常显示，更换 assets 中对应的图片 
2、重新刷新界面，页面背景图显示正常 
3、ctrl+c 关闭运行 
4、yarn start 重新运行项目
5、新改的背景图片正常显示，原来的其他背景图片隐藏不见了报如下错误
    Failed to load resource: the server responded with a status of 404 (Not Found)
    left-dq.f195e2ae.png:1          Failed to load resource: the server responded with a status of 404 (Not Found)
    left-green.2f2c5db6.png:1          Failed to load resource: the server responded with a status of 404 (Not Found)
    left-purple.370f03a3.png:1          Failed to load resource: the server responded with a status of 404 (Not Found)
    left-xmlb.7453c9cc.png:1          Failed to load resource: the server responded with a status of 404 (Not Found)
    right-software.ba248da2.png:1          Failed to load resource: the server responded with a status of 404 (Not Found)
    right-safe.058240e8.png:1          Failed to load resource: the server responded with a status of 404 (Not Found)
6、删除 src 下面的.umi 后，重新 yarn start 界面背景图片显示正常
