### ISSUE TITLE
umi 不是内部或外部命令 =>faq补充

### ISSUE THREAD

**Issue by caohaijiang** [umijs/umi#1533]
在centos中,使用sudo 其他账号,安装出现这个错误. 
使用root 账号安装就ok了. 在linux中,用什么账号安装这个要注意了.有关系.

**Comment by xiaohuoni** [comment]
是因为账号下安装环境的问题吧

**Comment by caohaijiang** [comment]
是的.

**Comment by sorrycc** [comment]
centos 下安装和 mac 下并没啥区别，注意权限问题，别用 sudo。
