### ISSUE TITLE
public文件夹中图片路径问题

### ISSUE THREAD

**Issue by qianduanMortal** [umijs/umi#1542]
public/images中的图片，页面中引用方式为:
`<image src=‘/images/xx.png’>;`
最终项目部署在非根目录下(/dist/)。 因此配置中
```
{
    root:/dist/,
    publicPath:'/dist/'
}
```
但是此时访问不到图片。
感觉publicPath并没有应用到组件中。
如果这种方式不对，那么正确的图片引用方式是什么。

**Comment by sorrycc** [comment]
publicPath 配成 `/dist/`，那图片的地址就是 `/dist/images/xx.png` 吧。

**Comment by qianduanMortal** [comment]
> publicPath 配成 `/dist/`，那图片的地址就是 `/dist/images/xx.png` 吧。

好像并不是的，src上没有加上publicPath的路径。

**Comment by qianduanMortal** [comment]
额，解决了再关闭吧。 问题都没解决也关闭。
