### ISSUE TITLE
less.min.js

### ISSUE THREAD

**Issue by lijiangwei** [umijs/umi#1545]
打包后的代码index.html引用了less.min.js文件，引用的是cdn的文件，部署到内网时请求不到这个文件，这个文件的地址可以配置吗？

**Comment by sorrycc** [comment]
less.min.js 哪里来的？umi 没有这个逻辑。

**Comment by Nokecy** [comment]
@lijiangwei  用的Ant Design Pro吧 ?

**Comment by lijiangwei** [comment]
<!DOCTYPE html><html lang="en"><head><link rel="stylesheet" href="/display/datax/umi.css"><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DataX</title><link rel="icon" href="/favicon.ico" type="image/x-icon"><script src="js/data-set.min.js"></script><script>window.routerBase = "/display/datax/";</script></head><body><div id="root"></div><script src="/display/datax/umi.js"></script></body></html>

这个是win系统上打包后的index.html

<!DOCTYPE html><html lang="en"><head><link rel="stylesheet" href="/display/datax/umi.css"><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DataX</title><link rel="icon" href="/favicon.ico" type="image/x-icon"><script src="js/data-set.min.js"></script><script>window.routerBase = "/display/datax/";</script></head><body>
    <link rel="stylesheet/less" type="text/css" href="/color.less" />
    <script>
      window.less = {
        async: false,
        env: 'production'
      };
    </script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js"></script>
        <div id="root"></div><script src="/display/datax/umi.js"></script></body></html>

这个是在linux系统上打包后的index.html，这个是多了一个less.min.js的引用

**Comment by lijiangwei** [comment]
@Nokecy 不是，用的umi

**Comment by xiaohuoni** [comment]
编译的时候注释掉
```
//  chainWebpack: webpackPlugin,
```
