### ISSUE TITLE
css 删除注释无效

### ISSUE THREAD

**Issue by liaobin312716** [umijs/umi#1546]
扩展 cssnano 的配置， 增加 `{"discardComments": {"removeAll": true}}` 了依旧没有效果。

参考了 https://github.com/cssnano/cssnano/issues/90 加了 `filterPlugins: false` 也没有效果。

直接修改依赖里的 node_modules/af-webpack/lib/getConfig/css.js 里的
```
require('cssnano')({
      preset: ['default', {
        mergeRules: false,
        filterPlugins: false,
        discardComments: {
          removeAll: true,
        },
        // ref: https://github.com/umijs/umi/issues/955
        normalizeUrl: false
      }]
    })
```
也没有删除成功

**Comment by xiaohuoni** [comment]
build之后生效的吧？

**Comment by lin09** [comment]
我 webpack4 遇到 postcss-loader 在 sass-loader 的后面（use: [..., 'sass-loader', 'postcss-loader']）时，cssnano 没有任何效果。use: [..., 'postcss-loader', 'sass-loader']这样cssnano就有效果

**Comment by liaobin312716** [comment]
其他插件导致，故关闭issue
