### ISSUE TITLE
build到线上后报错umi.js:1 Uncaught (in promise) TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by jerryyan1990** [umijs/umi#1551]
使用最新的ant design pro，开发项目，本地无任何错误信息，build到线上后其中一个页面报这个错误。
![bug](https://user-images.githubusercontent.com/12929365/49206463-1cc0db80-f3ed-11e8-847c-31e737e307a9.png)

**Comment by xiaohuoni** [comment]
debug

**Comment by Veveue** [comment]
[targets](https://umijs.org/zh/config/#targets)配置试试

**Comment by jerryyan1990** [comment]
神了个奇了，还没改今天自己好了....

**Comment by NgeKaworu** [comment]
emmm
我把umi-plugin-react放到dependencies下重新打包就好了

**Comment by liudonghua123** [comment]
我也是遇到这个问题，很奇怪

**Comment by rainjm** [comment]
同

**Comment by zhangyanan0525** [comment]
我现在依然有这个问题，偶发的报错，没有解决。请大神指点下

**Comment by rainjm** [comment]
> 我现在依然有这个问题，偶发的报错，没有解决。请大神指点下

@zhangyanan0525 可能是models的问题, 尝试把pages里面跨目录（多个地方使用，并且不是同一目录下面）使用的models移到src下面的models文件夹里面。

**Comment by c305333655** [comment]
我也遇到了这个问题，TypeError: Cannot read property 'Consumer' of undefined
开发环境正常，build之后功能报错，触发不了网络请求、方法undefine

**Comment by xiaohuoni** [comment]
@c305333655 
不是一个问题，你这个问题，是因为升级了react-router

**Comment by helsonxiao** [comment]
依然有这个问题，umi 版本为 2.2.1 ，开发环境一切正常，nginx 部署后好几个页面都报这个错。

**Comment by asevenm** [comment]
同遇到这个问题，有什么有效的解决方式吗？

**Comment by helsonxiao** [comment]
> 同遇到这个问题，有什么有效的解决方式吗？

可以试试配置 hash: true 令缓存失效，我觉得这种东西应该默认 true 啊

**Comment by asevenm** [comment]
> > 同遇到这个问题，有什么有效的解决方式吗？
> 
> 可以试试配置 hash: true 令缓存失效，我觉得这种东西应该默认 true 啊
感觉不像是缓存的问题，我们目前是采用资源应用的时候加上版本号令缓存失效的

**Comment by mt3925** [comment]
# https://github.com/webpack/webpack/issues/8996

**Comment by xoptimal** [comment]
该问题, 仍然存在, 莫名其妙~  develop是正常的, build 后就会报这个错误,  之前都是好的 ... 没改任何配置就出现这个问题

**Comment by shanjuqiuming2019** [comment]
有人解决了吗？同遇到，解决不了

**Comment by zstared** [comment]
清除游览器缓存就好了

**Comment by mstao** [comment]
> > 同遇到这个问题，有什么有效的解决方式吗？
> 
> 可以试试配置 hash: true 令缓存失效，我觉得这种东西应该默认 true 啊

请问，ant-design-pro 这个在哪里配置呢
