### ISSUE TITLE
配置路由不生效 

### ISSUE THREAD

**Issue by luoandy** [umijs/umi#1552]
![image](https://user-images.githubusercontent.com/20121275/49208542-00c03880-f3f3-11e8-9ecf-10669869abbc.png)

**Comment by xiaohuoni** [comment]
看.umi下面的router解析完的样子

**Comment by luoandy** [comment]
![image](https://user-images.githubusercontent.com/20121275/49209128-9c05dd80-f3f4-11e8-8df8-920c743628b3.png)

**Comment by sorrycc** [comment]
给可复现仓库吧。

**Comment by cieldon32** [comment]
遇到一样的问题， 愁啊
