### ISSUE TITLE
抱歉第一步就跑歪了，'umi' is not recognized

### ISSUE THREAD

**Issue by foreverZ133** [umijs/umi#1555]
如图，好像没啥问题的样子，但报出 'umi' is not recognized，大佬求教

![umi 安装报错](https://user-images.githubusercontent.com/22021589/49212353-c8bdf300-f3fc-11e8-91e6-d4945cc96bdc.png)
![问题机器系统配置](https://user-images.githubusercontent.com/22021589/49212436-fefb7280-f3fc-11e8-9aa5-223b52f8c5c1.png)

**Comment by sorrycc** [comment]
执行 `tyarn global bin`，把输出配到 PATH 变量里。

**Comment by SienaSantos** [comment]
same problem with me

![image](https://user-images.githubusercontent.com/15723000/54520215-2aea3600-49a3-11e9-95ef-b5f231b98da2.png)

**Comment by FamingHou** [comment]
`npm install -g umi`

**Comment by kambleaa007** [comment]
NO USE @sorrycc 
How to fix this issue,

![image](https://user-images.githubusercontent.com/19818679/70694988-c5836580-1ce6-11ea-8440-1cd22da43ba2.png)

**Comment by kambleaa007** [comment]
quick fix is this,
inside script of package.json
add
    "predeploy": "npm run build",
    "deploy": "gh-pages -d build"

and add 
"homepage": "https://kambleaa007.github.io/React-Stuff", 

![image](https://user-images.githubusercontent.com/19818679/70695595-1ba4d880-1ce8-11ea-8f12-0c0c57e62e18.png)

**Comment by kambleaa007** [comment]
Now facing issue

![image](https://user-images.githubusercontent.com/19818679/70695732-56a70c00-1ce8-11ea-891a-d0df367b3b53.png)
