### ISSUE TITLE
Cannot get latest af-webpack from npm

### ISSUE THREAD

**Issue by colingaj** [umijs/umi#1558]
I am trying to install latest af-webpack dependency but I keep getting a webpack-dev-server version of 3.1.5. Your code on github does not seem to match what is on the npm server. Can you please update? We need to get the latest version of the webpack-dev-server (3.1.10 according to your package.json in af-webpack directory).

**Comment by sorrycc** [comment]
af-webpack in master is not published yet, please wait for next publish. Or you can try the resolutions in package.json.
