### ISSUE TITLE
如何在gobal.less中取得修改后的less变量

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#1559]
在less中取得，antd的less变量，怎么解决随着主题切换颜色
https://github.com/ant-design/ant-design-pro/issues/3020#issuecomment-443052097

**Comment by sorrycc** [comment]
theme 里配置的不能直接用？

**Comment by xiaohuoni** [comment]
动态变更无效。你可以看看，附带的那个问题。

**Comment by sorrycc** [comment]
我不熟动态变更，可以问下 @chenshuai2144 。这和 umi 没啥关系，这里先关了。

**Comment by xiaohuoni** [comment]
好的

**Comment by RivanLuo** [comment]
> 我不熟动态变更，可以问下 @chenshuai2144 。这和 umi 没啥关系，这里先关了。

问题都没解决，怎么老是关issue

**Comment by xiaohuoni** [comment]
@RivanLuo pro那边跟进
