### ISSUE TITLE
feature request: umi build --mode=development --watch

### ISSUE THREAD

**Issue by masquevil** [umijs/umi#1560]
本地开发自带服务器是很方便，但有时候会用远程开发，使用已经配置好的域名，则不需要启动服务器。
大概看了一下源码，好像目前没有办法通过简单修改 package.json 的 script 满足需求。

希望提供：

1. develop 模式构建的功能
2. watch 模式构建

以上都是在不启动 server 的情况下。

**Comment by masquevil** [comment]
已解决，可以通过修改 env 文件：[.env 和环境变量](https://umijs.org/zh/guide/env-variables.html)

**Comment by zywcode** [comment]
@masquevil 还是不支持watch啊？
