### ISSUE TITLE
#BUG# location.query 解析问题

### ISSUE THREAD

**Issue by smithyj** [umijs/umi#1562]
```
?current=1&search[title2][0]=344&search[title2][1]=33&search[title]=344"
```
> 如上，是地址栏的参数串
### 改造前的代码
![image](https://user-images.githubusercontent.com/9820142/49275468-56a9e480-f4b6-11e8-9cbc-cab3ec597658.png)
### 改造前的结果
![image](https://user-images.githubusercontent.com/9820142/49275376-19dded80-f4b6-11e8-97dd-efc67db91e51.png)

### 改造后的代码
![image](https://user-images.githubusercontent.com/9820142/49275416-3a0dac80-f4b6-11e8-8a31-434e091c8998.png)
### 改造后的结果
![image](https://user-images.githubusercontent.com/9820142/49275319-ebf8a900-f4b5-11e8-9a25-1aa3abf21bdf.png)

**Comment by smithyj** [comment]
@sorrycc @xiaohuoni

**Comment by xiaohuoni** [comment]
👍

**Comment by xiaohuoni** [comment]
@sorrycc 这个是umi中处理的吗？我感觉解析后的比较友好

**Comment by xiaohuoni** [comment]
@sorrycc 修改这里吗？
https://github.com/umijs/umi/blob/25f86b67c90988f4bbca7b5911b896c9894f8904/packages/umi/src/renderRoutes.js#L17

**Comment by exvu** [comment]
你可以在进阶教程中的运行时配置中配置onRouteChange
![image](https://user-images.githubusercontent.com/25115931/54626459-278ea180-4aac-11e9-8419-009083be036f.png)
