### ISSUE TITLE
dev模式，node_modules中引用less后，umi.css中只包含node_modules下的样式

### ISSUE THREAD

**Issue by NicoKam** [umijs/umi#1566]
因为刚好有一个组件，是在js中引用了样式
`import from "./xxxx.less";`

项目开启了antd支持，也写了很多less样式。在没有install该组件的情况下，umi.css是包含了antd和项目的样式（大约有8000多行）。但install之后，umi.css只有100多行了，只有该组件的样式。

使用umi build后生成的umi.css则是正常的。@sorrycc 求帮助

**Comment by NicoKam** [comment]
哦我说的组件是写在dependencies

**Comment by NicoKam** [comment]
写了个Demo，测试了下，主要原因是dll插件的问题，如果开启了dll就会导致样式被覆盖。可以拿例子试一下，里面的样式是丢失了的
https://github.com/NicoKam/umi-dependencies-test

**Comment by amily4555** [comment]
me too 开启了dll, 
component import less 失效

**Comment by QSQ1989** [comment]
我也遇到了，有临时解决措施吗？

**Comment by caowenjin2** [comment]
我也遇到了这个问题，除了关闭dll之外有其他办法吗？😂

**Comment by sorrycc** [comment]
在 #915 跟进，同一个问题。

**Comment by sorrycc** [comment]
> 我也遇到了这个问题，除了关闭dll之外有其他办法吗？😂

可以 exclude 有问题的依赖。

**Comment by honghaozhilian** [comment]
关闭dll也不能解决，怎么办
