### ISSUE TITLE
加载svg图片报错ModuleNotFoundError

### ISSUE THREAD

**Issue by cassiewang01** [umijs/umi#1570]
用了[jsoneditor](https://github.com/josdejong/jsoneditor)，需要在文件中引入 jsoneditor/dist/jsoneditor.min.css文件，引入方式如下：
`import 'jsoneditor/dist/jsoneditor.min.css';`

但在npm run start时报错如下：
```
ERROR  Failed to compile with 1 errors                                                                                                               14:34:59

 error  in ./node_modules/_jsoneditor@5.26.2@jsoneditor/dist/jsoneditor.min.css

Module build failed (from ./node_modules/_mini-css-extract-plugin@0.4.4@mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve 'img/jsoneditor-icons.svg'

```
尝试在config/plugin.config.js中加入如下配置，还是报错

```
    config.module.rule('svg')
      .test(/\.svg(\?v=\d+\.\d+\.\d+)?$/)
      .use('url-loader')
      .loader(require.resolve('url-loader'));

```

正常在项目中用svg图，是需要怎么配置才可以？为什么我的不行？

帮忙看下，谢谢

**Comment by xiaohuoni** [comment]
```js
import { ReactComponent as Rice } from './rice.svg';

export default function() {
  return (
    <div>
      <h1>Page index</h1>
      <Rice width="120" height="120" />
    </div>
  );
}
```
https://github.com/umijs/umi/pull/1263

**Comment by lyj1994** [comment]
> 用了[jsoneditor](https://github.com/josdejong/jsoneditor)，需要在文件中引入 jsoneditor/dist/jsoneditor.min.css文件，引入方式如下：
> `import 'jsoneditor/dist/jsoneditor.min.css';`
> 
> 但在npm run start时报错如下：
> 
> ```
> ERROR  Failed to compile with 1 errors                                                                                                               14:34:59
> 
>  error  in ./node_modules/_jsoneditor@5.26.2@jsoneditor/dist/jsoneditor.min.css
> 
> Module build failed (from ./node_modules/_mini-css-extract-plugin@0.4.4@mini-css-extract-plugin/dist/loader.js):
> ModuleNotFoundError: Module not found: Error: Can't resolve 'img/jsoneditor-icons.svg'
> ```
> 尝试在config/plugin.config.js中加入如下配置，还是报错
> 
> ```
>     config.module.rule('svg')
>       .test(/\.svg(\?v=\d+\.\d+\.\d+)?$/)
>       .use('url-loader')
>       .loader(require.resolve('url-loader'));
> ```
> 正常在项目中用svg图，是需要怎么配置才可以？为什么我的不行？
> 
> 帮忙看下，谢谢

老哥最后如何解决的，我也遇到了

**Comment by Jansora** [comment]
> > 用了[jsoneditor](https://github.com/josdejong/jsoneditor)，需要在文件中引入 jsoneditor/dist/jsoneditor.min.css文件，引入方式如下：
> > `import 'jsoneditor/dist/jsoneditor.min.css';`
> > 但在npm run start时报错如下：
> > ```
> > ERROR  Failed to compile with 1 errors                                                                                                               14:34:59
> > 
> >  error  in ./node_modules/_jsoneditor@5.26.2@jsoneditor/dist/jsoneditor.min.css
> > 
> > Module build failed (from ./node_modules/_mini-css-extract-plugin@0.4.4@mini-css-extract-plugin/dist/loader.js):
> > ModuleNotFoundError: Module not found: Error: Can't resolve 'img/jsoneditor-icons.svg'
> > ```
> > 尝试在config/plugin.config.js中加入如下配置，还是报错
> > ```
> >     config.module.rule('svg')
> >       .test(/\.svg(\?v=\d+\.\d+\.\d+)?$/)
> >       .use('url-loader')
> >       .loader(require.resolve('url-loader'));
> > ```
> > 正常在项目中用svg图，是需要怎么配置才可以？为什么我的不行？
> > 帮忙看下，谢谢
> 
> 老哥最后如何解决的，我也遇到了

1: open `/config/config.js`
2: find key: `cssLoaderOptions`
3: change `modules:ture`  -> `modules:false`

everything should be ok.
