### ISSUE TITLE
请教：如何确保在拿到一些远程数据初始化 redux state 之后才渲染页面？

### ISSUE THREAD

**Issue by sphawkcn** [umijs/umi#1579]
用的技术栈是 umi + dva ，我了解到在 umi 中如果需要在渲染前就做完的一些异步操作可以新建 app.js，通过导出的 render 方法进行定制，比如：

```javascript
export function render(oldRender) {
  console.log('wait for 1s');
  setTimeout(() => {
    console.log('do render');
    oldRender();
  }, 1000);
}
```

但是，在这个 app.js 里面似乎无法获取 redux 的 state，也没有 dispatch 方法。

如果这些初始化工作是需要从远程获取数据（ dispach effects），或者需要把数据填充到 redux 的 state 中（dispach  reducers），等这些数据初始化工作完成之后才开始渲染页面，该如何做呢？还请指教，先行谢过大大指点。

补充：之前用 create-react-app 的时候，以上数据初始化工作是在 index.js 入口文件里做的，因为这个文件里导入了 redux store， 所以可以用 dispatch。

**Comment by yutingzhao1991** [comment]
最简单的方法就是在最外层的路由组件里面判断数据是否 ready 就好。或者可以用权限路由 https://umijs.org/zh/guide/router.html#%E6%9D%83%E9%99%90%E8%B7%AF%E7%94%B1

**Comment by sphawkcn** [comment]
> 最简单的方法就是在最外层的路由组件里面判断数据是否 ready 就好。或者可以用权限路由 https://umijs.org/zh/guide/router.html#%E6%9D%83%E9%99%90%E8%B7%AF%E7%94%B1

测试了下权限路由，不能满足这种需求。可能你还没理解我的意思。我测试权限路由并不能在远程获取一些初始化数据之后才渲染，他会立刻渲染，而这个时候初始化数据可能还没获取到。

权限路由是在已经获取到初始化数据之后再用的，这个时候就可以根据已经存在的初始化数据来确定如何渲染。

现在的问题是：希望远程获取到数据之后，数据完全到达本地 redux state 中后，才开始渲染。

**Comment by sphawkcn** [comment]
我觉得这种需求应该是很普遍啊。
举个例子，任何一个需要登录才能使用的管理系统，都不希望在用户登录之后，随手按 F5 刷新一下就被踢出系统。
那么就必须在用户按了刷新之后，在系统初始化的时候，还没渲染之前，就读取本地的浏览器的 Token 获取用户信息，再提交用户信息到远程服务器获取用户的权限信息，等获取到权限信息之后，再根据这些权限信息才能判断如何来渲染用户的界面。

**Comment by Renderz** [comment]
> 我觉得这种需求应该是很普遍啊。
> 举个例子，任何一个需要登录才能使用的管理系统，都不希望在用户登录之后，随手按 F5 刷新一下就被踢出系统。
> 那么就必须在用户按了刷新之后，在系统初始化的时候，还没渲染之前，就读取本地的浏览器的 Token 获取用户信息，再提交用户信息到远程服务器获取用户的权限信息，等获取到权限信息之后，再根据这些权限信息才能判断如何来渲染用户的界面。

页面正常渲染. 顶级组件mount的时候获取登录信息, 如果失败就跳转. 
还可以做一个loading蒙版, 还没返回的时候显示loading.

**Comment by sphawkcn** [comment]
> > 我觉得这种需求应该是很普遍啊。
> > 举个例子，任何一个需要登录才能使用的管理系统，都不希望在用户登录之后，随手按 F5 刷新一下就被踢出系统。
> > 那么就必须在用户按了刷新之后，在系统初始化的时候，还没渲染之前，就读取本地的浏览器的 Token 获取用户信息，再提交用户信息到远程服务器获取用户的权限信息，等获取到权限信息之后，再根据这些权限信息才能判断如何来渲染用户的界面。
> 
> 页面正常渲染. 顶级组件mount的时候获取登录信息, 如果失败就跳转.
> 还可以做一个loading蒙版, 还没返回的时候显示loading.

谢谢指点，我懂了，之前对 React 理解不够透。

**Comment by RZD15** [comment]
pages/umi/umi.js 可作为入口文件

**Comment by code33** [comment]
> pages/umi/umi.js 可作为入口文件

十分感谢, 比如我要手动引入一个websocket.js 这样的文件,请问如何操作,感谢!
