### ISSUE TITLE
关于 "Compiling..."

### ISSUE THREAD

**Issue by panlw** [umijs/umi#158]
按照“快速上手”步骤进行，走到"创建第一个页面"，却没有出现"Index Page"，而一直停留在"Compiling..."，不知道是怎么回事。

> 运行环境: macOS 10.11.6, node v8.9.4, umi v1.0.1

**Comment by panlw** [comment]
$ umi -v
1.0.1
@local

**Comment by sorrycc** [comment]
在 umi@1.0.3 里已修复。

**Comment by 314172670** [comment]
![image](https://user-images.githubusercontent.com/23290703/39745007-a40b73f4-52d8-11e8-9e94-d6d13192762c.png)
uim dev 启动后一直是compiling，怎么回事，要手动刷新才会渲染

**Comment by xiaohuoni** [comment]
看一下你的umi版本

**Comment by 314172670** [comment]
1.2.6呢

**Comment by xiaohuoni** [comment]
感觉可以提一个iss @314172670  我这里，umi dev
```js
D:\umi-examples\with-dva>npm start

> @ start D:\umi-examples\with-dva
> umi dev


```
没反应

**Comment by xiaohuoni** [comment]
@314172670  你试试执行一下umi build 之后什么表现

**Comment by 314172670** [comment]
@xiaohuoni  和原来一样，运行之后还是compiling

**Comment by xiaohuoni** [comment]
那你提个新的iss吧，在这里好难找。然后要提供一个可重现demo（😊）
