### ISSUE TITLE
Global.css overrided by dynamicImport plugin

### ISSUE THREAD

**Issue by mediatec-software** [umijs/umi#1581]
If dynamicImport import is enabled, antd library overrides styles from globals.css
Is it possible to change this loading queue order? Without dynamicImport vendors styles placed in top of umi.css. This behaviour difference causes problems with overwriting some styles of third-party libraries.

### Dev
![image](https://i.gyazo.com/0734c0f3fc8f5e46e93dc1b907bc1605.png)

### Build
![image](https://user-images.githubusercontent.com/5726970/49448316-adcaf480-f7e9-11e8-9184-651e66fa47eb.png)

**Comment by sorrycc** [comment]
Duplicated #1002
