### ISSUE TITLE
umi build后 vendors.js和umi.hash.js 为啥有相同的文件包？我的使用方法不对吗？

### ISSUE THREAD

**Issue by zhangfaliang** [umijs/umi#1583]
umi build后 vendors.js和umi.hash.js 为啥有相同的文件包？我的使用方法不对吗？
![image](https://user-images.githubusercontent.com/17559536/49488072-23819f80-f880-11e8-9024-28ed1edce352.png)

**Comment by sorrycc** [comment]
看不出来问题，是打重复了，还是分别引入了 lodash 里面不同的内容？
