### ISSUE TITLE
部署到非根目录

### ISSUE THREAD

**Issue by qianduanMortal** [umijs/umi#1586]
配置项。 
```
{
base:'/opls-manager/',
publicPath:'/opls/manager/'
}
```
nginx文件存放位置。
/data/nginx/opls/manager/
nginx配置：
location /opls-manager {
index index.html;
root /data/nginx/opls;
try_files $uri /manager/index.html;
}

访问路径。  domain/opls-manager;
结果：nginx 404；

期望结果：
如何将代码放置到/opls/manager两层目录下。  而只访问/opls-manager一层。  即：domain/opls-manager；

**Comment by zjxpcyc** [comment]
看看 Nginx 错误日志，映射到什么位置。但是配置  `base` 参数 `/path/` 这种形式也是不好的，换个路由又不支持了。

我这边一般的做法是，使用相对路径打包。然后 nginx 配置的时候 不使用 root 指令, 使用 alias 代替。我的几个 vue 项目都是这样处理的，可以任意放目录，访问路径也可以任意指定

**Comment by sorrycc** [comment]
参考部署文档，https://umijs.org/guide/deploy.html
