### ISSUE TITLE
自定义3级路由会404

### ISSUE THREAD

**Issue by sillyfeng** [umijs/umi#1589]
项目是在`Ant-design-pro` 的基础上开发的。router为自定义路由的方式。

> 在`config目录`下有 `router.config.js`， 然后在`config.js`中引用自定义router
但是由于菜单比较多，现在把每个菜单下的路由都分别定义在不同的文件中，然后在`router.config.js`中import使用.
_类似A菜单下路由定义在A.router.js,B在B.router.js中，然后在 `router.config.js`中`import A from a.router.js`_

目前遇到的问题是，如果在A中存在`三级路由`**类似 /A/A1/add**这种的时候，就会在访问的时候报**404**.
但是如果把A中的路由直接写到`router.config.js`中的话可以正常访问。

> 目前所使用的umi版本为`2.2.7`

**Comment by sillyfeng** [comment]
@yutingzhao1991 
但是实际情况跟你说的有点差别

> 目前我的路由是这个样子
`{path:'/a/a1', component: '' }  {path: '/a/a1/detail', component: ''}  `

以上的路由，如果我直接定义到 `router.config.js`中 ，可以正常访问 _`/a/a1/detail`_
如果我把他定义到一个**单独的文件**,然后在`router.config.js`中**import**使用的话，就是**404**

**Comment by sillyfeng** [comment]
@yutingzhao1991 
刚刚我又确定了一下，实际情况跟你说的有点差别

> 目前我的路由是这个样子
` {path:'/a/a1', component: '' } {path: '/a/a1/detail', component: ''}`
以上的路由，如果我直接定义到 `router.config.js`中 ，可以正常访问 _`/a/a1/detail`_
如果我把他定义到一个**单独的文件**,然后在`router.config.js`中`import`使用的话，就是**404**

**Comment by sillyfeng** [comment]
不过还是想知道一下在引用文件以跟直接在`router.config.js`中引用为啥会有不一样的反应

**Comment by xiaohuoni** [comment]
引用文件？是什么

**Comment by sillyfeng** [comment]
@xiaohuoni 就是我把`router`安装菜单拆分到一个个单独的文件里了，然后在 `router.config.js`中以`import`方式引用进来

**Comment by xiaohuoni** [comment]
这个应该没啥问题吧，只要不要重复定义路由就好了

**Comment by sillyfeng** [comment]
我的锅，测试了半天原来发现我脚本里的路由写的不太对。。。。
