### ISSUE TITLE
uglifyjs压缩报错

### ISSUE THREAD

**Issue by zhouyi318** [umijs/umi#1590]
哪位大佬可以帮我看一下是那个模块的问题，谢谢！
![image](https://user-images.githubusercontent.com/24410466/49556960-01038b00-f941-11e8-8307-e10741d5d8fc.png)

![image](https://user-images.githubusercontent.com/24410466/49556951-f21cd880-f940-11e8-9731-a2922e811456.png)

**Comment by concefly** [comment]
带上 COMPRESS=none 环境变量，重新 build，然后在未压缩的构建产物里找下 punc 关键字

**Comment by zhouyi318** [comment]
> 带上 COMPRESS=none 环境变量，重新 build，然后在未压缩的构建产物里找下 punc 关键字

在构建产物中并没有找到包含 punc 关键字内容啊

**Comment by zhouyi318** [comment]
antd pro 开启代码压缩，和为报同样的错误哦。
![image](https://user-images.githubusercontent.com/24410466/49579661-dbe63b00-f987-11e8-8404-3d6acbf6efcb.png)

**Comment by sorrycc** [comment]
参考 https://www.bilibili.com/video/av37573841/

**Comment by ikobe** [comment]
B 站学习资料真是多

**Comment by xiaohuoni** [comment]
已投币，哈哈哈
