### ISSUE TITLE
配置 base时，指定的模板不再生效

### ISSUE THREAD

**Issue by tgy3300** [umijs/umi#1594]
我现在创建一个新页面
src/pages/Test/Index.js

该Index.js如何使用自己的 document.ejs

**Comment by tgy3300** [comment]
针对特定页面指定模板
WARNING

此功能需开启 exportStatic 配置，否则只会输出一个 html 文件。

TIP

优先级是：路由的 document 属性 > src/pages/document.ejs > umi 内置模板

配置路由的 document 属性。

比如约定式路由可通过注释扩展 document 属性，路径从项目根目录开始找，

/**
 * document: ./src/documents/404.ejs
 */

文档中的这个，我始终没明白，求指导

**Comment by sorrycc** [comment]
哪里不明白？

**Comment by tgy3300** [comment]
就是具体怎么做

**Comment by xiaohuoni** [comment]
不是说了具体怎么做了吗？在文件头部加注释

**Comment by tancyan** [comment]
同问下，我现在的目录结构是pages->(document.ejs, 404.ejs, index.tsx, A->(index.tsx))，想要实现在A目录下的index.tsx使用404.ejs,在A的index.tsx里面加了/**
 * document: ./pages/404.ejs
 */这个注释不起作用，还是调用的默认document.ejs，但如果把那段注释加到pages->index.tsx，这个注释就起作用了，我是哪里没有配置对吗？

**Comment by tancyan** [comment]
> 哪里不明白？



> 哪里不明白？

同问下，我现在的目录结构是pages->(document.ejs, 404.ejs, index.tsx, A->(index.tsx))，想要实现在A目录下的index.tsx使用404.ejs,在A的index.tsx里面加了/**

document: ./pages/404.ejs
*/这个注释不起作用，还是调用的默认document.ejs，但如果把那段注释加到pages->index.tsx，这个注释就起作用了，我是哪里没有配置对吗？

**Comment by ZhaoHaiPengPro** [comment]
遇到类似问题 
当.umirc中配置 base时，指定的模板不再生效，一直在用默认的；
如果不配置base，指定的模板工作正常 @xiaohuoni
