### ISSUE TITLE
pages 目录多嵌套一层，线上部署页面无法访问

### ISSUE THREAD

**Issue by xiaomei991** [umijs/umi#1595]
目录结构如下：
![image](https://user-images.githubusercontent.com/20355401/49621548-d6790700-fa00-11e8-9293-8d91afc70626.png)

访问报错如下：
![image](https://user-images.githubusercontent.com/20355401/49621585-13dd9480-fa01-11e8-8ac6-a109be7106b8.png)
打包js文件都在dist目录，访问时多了一层home，请问是什么问题？
部分配置如下：
![image](https://user-images.githubusercontent.com/20355401/49621687-8d758280-fa01-11e8-876b-adcd4719e8c7.png)

**Comment by sorrycc** [comment]
看不出问题，给可复现的例子吧。

**Comment by xiaomei991** [comment]
> 看不出问题，给可复现的例子吧。

`https://github.com/xiaomei991/umiTest.git`
这个是弄的一个小demo，部署到线上打开如下，不知道是不是我配置的问题，麻烦帮忙看下：
![image](https://user-images.githubusercontent.com/20355401/49632646-6f277b00-fa31-11e8-8cf4-0a95ba0c1eaa.png)

**Comment by Veveue** [comment]
应该是部署的问题, hash模式下正常

**Comment by xiaomei991** [comment]
@xiaohuoni 这个看到了，不过当时不知道怎么解决，现在去试试hash模式，看看效果

**Comment by xiaohuoni** [comment]
@Veveue 不是部署的问题，部署问题应该与设置的test有关，而不是与路由home这些有关

**Comment by xiaomei628** [comment]
@xiaohuoni 使用hash模式可以，但是不使用hash模式的话，要怎么去配置才行，这个还不懂

**Comment by xiaohuoni** [comment]
@sorrycc 我也不懂，我觉得是一个bug？

**Comment by sorrycc** [comment]
base 为 `/test`，publicPath 为啥要配成 `./`，应该也用 `/test/` 吧。

**Comment by xiaohuoni** [comment]
> base 为 /test，publicPath 为啥要配成 ./，应该也用 /test/ 吧。

这两个都一样的化，那要两个干什么？

**Comment by xiaomei628** [comment]
@sorrycc 因为线上部署不在根目录下，所以把默认的publicPath #/ 变成 #./  ,这个是修改打包完成之后index.html文件匹配的是当前文件夹下，而不是根目录。
![image](https://user-images.githubusercontent.com/15361002/49845662-8df78a00-fe02-11e8-9b3c-dafe0c1a5ef2.png)

**Comment by sorrycc** [comment]
@xiaohuoni @xiaomei628 publicPath 用绝对路径吧，不要用相对路径。

**Comment by xiaomei628** [comment]
好，我去试试
