### ISSUE TITLE
you should not use exportStatic with dynamic route

### ISSUE THREAD

**Issue by beeant0512** [umijs/umi#1596]
\node_modules\umi-build-dev\lib\routes\patchRoutes.js:73
    throw new Error(`you should not use exportStatic with dynamic route: ${route.path}`);
    ^

Error: you should not use exportStatic with dynamic route:

**Comment by jzoe** [comment]
@sorrycc @xiaohuoni @chenshuai2144 使用 ant-design-pro 遇到了同样的问题，添加的动态路由如下：

```
     {
            path: '/my/project/:id',
            name: 'detail',
            component: './my/Project/$id.js',
            hideInMenu: true,
          },
```

试过 `component: './my/Project/$id'` 也是一样的错误。

**Comment by hy08** [comment]
在配置中，你应该配置了"exportStatic": {},这个属性，去掉就好了
