### ISSUE TITLE
路由跳转外链

### ISSUE THREAD

**Issue by syaivin** [umijs/umi#1598]
@sorrycc 您好，五米的路由都是自动生成的，想了很多办法菜单还是不能跳转到外链；有办法设置吗？
![qq 20181207175548](https://user-images.githubusercontent.com/13479047/49640915-b91c5b00-fa49-11e8-954c-e8434009e432.jpg)

**Comment by wangxingkang** [comment]
使用配置式路由不就可以了

**Comment by wangxingkang** [comment]
类似这种
```
{ path: '/user', redirect: 'https://www.baidu.com' }
```
试一试

**Comment by Veveue** [comment]
虽然路由是动态生成的  但是左边这个菜单和umi没有关系吧

**Comment by sorrycc** [comment]
是的，菜单和 umi 没啥关系。你可以给路由加上一些属性，然后生成菜单时判断是否做外链。

**Comment by pxim** [comment]
> @wangxingkang 谢谢，我看看~

这个需求，你解决了没，我现在同样有这个需求
