### ISSUE TITLE
umi g page

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#1600]
umi g page home
现在生成的文件结构是
```sh
├── home.css
└── home.js
```
改成下面的目录结构，会不会好一点？？
```sh
.
└── home
    ├── index.css
    └── index.js
```

**Comment by sorrycc** [comment]
用 `umi g page home/index` 就好了吧。

**Comment by xiaohuoni** [comment]
还能这样用？？然后，umi的相关命令，没有文档的吧？

**Comment by amily4555** [comment]
在 TS 中 我喜欢这样
```
.
└── home
     |── home.less
     |── home.tsx
     |—— index.ts
```
对IDE 特友好·

**Comment by amily4555** [comment]
![image](https://user-images.githubusercontent.com/2802841/49943863-f722ee80-ff23-11e8-942b-bcb4b2fa82ac.png)
