### ISSUE TITLE
npm test 报错

### ISSUE THREAD

**Issue by wjjhhh** [umijs/umi#1601]
FAIL  src/utils/index.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    F:\new-ecommerce\ecommerce\src\utils\index.test.js:13
    import React from "react";
    ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/_jest-runtime@23.6.0@jest-runtime/build/script_transformer.js:403:17)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        15.487s
Ran all test suites.
npm ERR! Test failed.  See above for more details.

请问是还要配置jest.config.js吗，有具体配置吗

**Comment by wjjhhh** [comment]
应该是出现了jsx语法就报这个错了

**Comment by sorrycc** [comment]
参考 ant-design-pro，目前用起来好像没有问题。

**Comment by sorrycc** [comment]
加上这行试试，https://github.com/ant-design/ant-design-pro/blob/master/jest.config.js#L2

**Comment by wjjhhh** [comment]
老铁，我用的是https://github.com/zuiidea/antd-admin.git 这哥们的项目，更新了最新的貌似没问题了，打扰了
