### ISSUE TITLE
如果菜单是后端返回的，umi中如何注册这些菜单路由？

### ISSUE THREAD

**Issue by m430** [umijs/umi#1606]
目前的需求是业务菜单是全部是由后端数据返回，前端拿到菜单需要注册到前端的路由中，umi的文档中所有的路由配置方式都是静态注册的方式，请问这个怎么解决呢？
@sorrycc

**Comment by m430** [comment]
@sorrycc

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi-examples/tree/master/runtime-routes-appjs 看看这个，不行就在model里面管理
