### ISSUE TITLE
使用umi项目中使用出现部分文件的对象展开语法未编译

### ISSUE THREAD

**Issue by ethanbear** [umijs/umi#1612]
# 使用umi dev
![image](https://user-images.githubusercontent.com/8637919/49777105-f0d11e80-fd39-11e8-8286-1e178c8f70e2.png)

# 在浏览器端查看
![image](https://user-images.githubusercontent.com/8637919/49777098-eb73d400-fd39-11e8-8baf-088bf94ed8ef.png)

编译出来后的文件，明显部分同样的对象展开语法使用了runtime/helpers/objectSpread方法替换了。但有些文件却还是保持...方式，导致浏览器报错了。

**Comment by Veveue** [comment]
报错的这个是第三方的库还是你自己项目中的

**Comment by ethanbear** [comment]
@Veveue 项目中的代码

**Comment by Veveue** [comment]
检查一下 `merInfo`这个的类型看看

**Comment by ethanbear** [comment]
@Veveue 有没有肯能是使用了不同的编译器导致的；参考了这个pr: https://github.com/umijs/umi/issues/528

**Comment by ethanbear** [comment]
@Veveue 是对象
![image](https://user-images.githubusercontent.com/8637919/49777727-aa30f380-fd3c-11e8-8493-5225f7e3e12e.png)

**Comment by ethanbear** [comment]
低级错误了，数组里面展开对象key-value值作为数组元素的用法本身就有问题
