### ISSUE TITLE
错误提示问题

### ISSUE THREAD

**Issue by hanwenbo** [umijs/umi#1614]
我发现当我随便写个内容跑不通时在命令行的显示区域没有编译的错误提示，请问如果报错了去哪里看呢？
比如：我在页面里引入这个内容，但我实际没有import ，在命令行和浏览器都没有提示错误
@connect(({ list, loading }) => ({
    list,
    loading: loading.models.list,
}))

**Comment by sorrycc** [comment]
给可复现例子？出错时正常情况下会在浏览器和命令行里同时报错。

**Comment by xiaohuoni** [comment]
@sorrycc 老大，他的意思是，没有报错。

**Comment by sorrycc** [comment]
我理解使用了 connect，但是没有 import 他，正常情况下应该是会报错的吧。

**Comment by hanwenbo** [comment]
@sorrycc 编译的时候确实没报错，我稍后给您例子哈，我还在转我们的项目到umi上，还没提交到github分支，提交好了我在这个issue里圈您。

**Comment by hanwenbo** [comment]
@sorrycc  云老师，https://github.com/mojisrc/fashop-admin/tree/v2 我最近用您的优秀dva+umi基本写的差不多了，您可以测试下v2这个分支，找个page把{ connect }去掉，编辑不会报错，还有就是给props = { list }，这样定义一个键值并且不赋值 也不报错 会一直白屏，我在教umi的时候 很多新手学生遇到这两个问题都很难排错，因为没任何提示 ，目前是让大家一个个删除 直到找到问题，这不太方便  对新手很困难

**Comment by sorrycc** [comment]
试了下，这是运行时的报错，所以白屏是正常的，然后在控制台里会有报错。

![image](https://user-images.githubusercontent.com/35128/50758425-2ae00280-129d-11e9-97f0-f4004943fb06.png)

例子：[sorrycc-3eqmKT.zip](https://github.com/umijs/umi/files/2732040/sorrycc-3eqmKT.zip)

**Comment by sorrycc** [comment]
不过 #1770 能解决这个，具体在 #1770 跟进。

**Comment by xiaohuoni** [comment]
这个例子压缩包，后缀的随机数是怎么弄出来的！

**Comment by sorrycc** [comment]
每次我需要一个临时目录，都会执行：

```bash
$ cd `mktemp -d /tmp/sorrycc-XXXXXX`
```
