### ISSUE TITLE
dynamicImport loading组件展示问题

### ISSUE THREAD

**Issue by onpaik** [umijs/umi#1616]
1. dynamicImport 配置了 loadingComponent，但是loading出现的方式是先在左上角，没有样式，然后展示出了应有的样式，貌似有点体验不好，
2. 示例如下，使用了antd的spin组件，经过测试umi自带loading也是这种情况
 https://onzmz.com/loading

可以看见先在左上角，然后才出现在正中间，有什么改进的地方吗

**Comment by sorrycc** [comment]
请给可复现仓库。

**Comment by onpaik** [comment]
解决了，样式没有引入
