### ISSUE TITLE
很多 Could not freeze 

### ISSUE THREAD

**Issue by hanwenbo** [umijs/umi#1618]
当我加入一些js文件后，这个编译就会提示很多如下的提示：
它并不影响使用，只是会挡住上面有问题的提示。
我搜索了网上的资源清理删除 node_modules cache 就好了，这似乎是个bug，需要让官方看到并优化
![image](https://user-images.githubusercontent.com/5869741/49852857-47b12380-fe20-11e8-9360-6d6a8a04dccb.png)

**Comment by sorrycc** [comment]
删除 `node_modules/.cache` 然后重启 `umi dev`。
