### ISSUE TITLE
路由配置能否进行开放，方便自由定义

### ISSUE THREAD

**Issue by smithyj** [umijs/umi#162]
同题

**Comment by sorrycc** [comment]
_route.json 不行吗？

**Comment by smithyj** [comment]
或许增加一个routes.js会更好

**Comment by smithyj** [comment]
routes.js内容可以如下
import { Route,Switch } from 'umi/router';
import Dashbord from './Pages/Dashboard';
import User from './Pages/User';

export default () => (
    <Layout>
        <Switch>
            <Router exact path="/" component={Dashbord} />
            # 可以在 user 下进行路由嵌套
            <Router path="/user" component={Dashbord} />
        </Switch>
    </Layout>
)

**Comment by smithyj** [comment]
routes.js内容可以如下
```
import { Route,Switch } from 'umi/router';
import Dashbord from './Pages/Dashboard';
import User from './Pages/User';

export default () => (
    <Layout>
        <Switch>
            <Router exact path="/" component={Dashbord} />
            # 可以在 user 下进行路由嵌套
            <Router path="/user" component={Dashbord} />
        </Switch>
    </Layout>
)
```

**Comment by sorrycc** [comment]
routes.js 会支持的，尽量这周会确定路由改进的方案下来。
