### ISSUE TITLE
docz 集成后有多个 webpack 导致报错

### ISSUE THREAD

**Issue by clock157** [umijs/umi#1622]
原因：
afWebpack 锁定了版本，docz 使用最新的版本。导致 umi dev 会报错

临时方案：
目前才有的有两个临时解决方案:
yarn 使用 resolutions 锁定webpack 到 umi 的版本
npm 使用 npm-force-resolutions

但是两个方案都不太好，需要更好的解决。

**Comment by clock157** [comment]
> 为什么两个 webpack 版会导致问题？ 

![image](https://user-images.githubusercontent.com/4002237/49931046-f167e180-ff00-11e8-82a6-818d7e33fb11.png)

重现方式就是用不是最新的umi 安 docz 必现。

**Comment by amily4555** [comment]
删掉 node_module 包 ，重新安装下 就好了··

**Comment by amily4555** [comment]
我也出现了相同的问题

@sorrycc  view [you have react-scripts and webpack, so you have 2 webpacks. Please have a look at your node_modules which version of webpack is being installed! It should be > 4.25](https://stackoverflow.com/questions/53227877/progressplugin-typeerror-cannot-read-property-tap-of-undefined)

简单的说 两个版本的webpack 不能包含 webpack@4.25.0 这个区间

@clock157 可以把 af-webpack 升级到最新的一个版本过渡下

**Comment by clock157** [comment]
是的， af-webpack  已升级到最新，暂时没有问题，这个 issue 先关了，后面再关注。
