### ISSUE TITLE
根据现有的umi的配置项可以对输出文件加上hash值，那么如何对输出文件加上版本号呢？

### ISSUE THREAD

**Issue by zhilianbi520** [umijs/umi#1624]
根据现有的umi的配置项可以对输出文件加上hash值，那么如何对输出文件加上版本号呢？
相关配置是如何的，希望有小伙伴帮忙解答下。。
期望的输出文件的文件名为文件名+hash+版本号

**Comment by sorrycc** [comment]
不能加版本号，hash 就够了。需要版本号的话可以加在前面的文件夹上，通过 outputPath 配置。

**Comment by zhilianbi520** [comment]
> 不能加版本号，hash 就够了。需要版本号的话可以加在前面的文件夹上，通过 outputPath 配置。

好的～！了解～多谢～1

**Comment by JayenLee** [comment]
能不能在.js后面加上?s=jfjsldjfsdljf 这种参数
