### ISSUE TITLE
再次进入页面的时候，如何快速重置model中state的数据

### ISSUE THREAD

**Issue by xiaomei628** [umijs/umi#1629]
再次进入页面的时候，如何快速重置model中state的数据

**Comment by yutingzhao1991** [comment]
再次 dispatch 一个 action，执行一个重置 state 的 reducer 就行。

**Comment by xiaomei628** [comment]
@yutingzhao1991 我就是想问下有没有全局的处理方法，不然每个页面写一个，感觉还是很麻烦的

**Comment by yutingzhao1991** [comment]
可以写个方法封装下 dva model。或者写一个 dva 的插件，或者看看有没有什么 redux 插件能够支持类似的功能的。

**Comment by xiaomei628** [comment]
@yutingzhao1991 有没有办法获取dva  model里面state的初始值
