### ISSUE TITLE
Support revert block

### ISSUE THREAD

**Issue by yutingzhao1991** [umijs/umi#1631]
当前可以使用 `umi block blank` 这样的方法来下载区块，但是当发现区块下载错误的时候就需要人肉删除，很麻烦，需要添加 `umi block revert` 这样的命令来撤销最近一次的区块操作。

**Comment by yutingzhao1991** [comment]
想到的方案是：

在 `.umi` 中存放区块的文件信息和被覆盖的项目代码，当执行 revert 的时候把它们恢复。

**Comment by afc163** [comment]
用 git 来操作如何？add 的时候自动提交到 git 里。

**Comment by yutingzhao1991** [comment]
> 用 git 来操作如何？add 的时候自动提交到 git 里。

可以考虑，不过有两个问题：

- 没有 git 的项目是不是就不考虑这个操作了。
- 如果用户当前代码有未提交的怎么办，也帮忙提交了？

**Comment by afc163** [comment]
> 没有 git 的项目是不是就不考虑这个操作了。

这个不考虑。

> 如果用户当前代码有未提交的怎么办，也帮忙提交了？

那应该不添加，或者不提交 git。

**Comment by chenshuai2144** [comment]
git 会让用户感觉有点奇怪的，还是 rm 来的方便，维护一个更新的文件列表就好了
