### ISSUE TITLE
调试启动时 .umirc 中配置base后 路由中指定的.ejs模板不再生效，一直使用默认的

### ISSUE THREAD

**Issue by ZhaoHaiPengPro** [umijs/umi#1634]
按照文档在某个路由中指定.ejs模板, 
.umirc 配置开启静态，browser 路由
npm start 启动

如果不配置base，路由指定的模板可以工作正常；

当.umirc中配置 base时，路由指定的模板不再生效，一直在用默认的.ejs；

**Comment by ZhaoHaiPengPro** [comment]
生成的 .uri 下的 router.js 中有document属性 是正确的
npm run build 生成的文件中 对应那个路径下的index.html 是正确的
之前是nginx转发配置有问题 更正后 生产环境部署可以正常工作

问题转化为 调试启动时 配置base 指定ejs模板 不生效

**Comment by sorrycc** [comment]
请给可复现的 git 仓库。

**Comment by xiaohuoni** [comment]
和这个是一个问题吗？https://github.com/umijs/umi/issues/1594

**Comment by ISyangk** [comment]
我是在config文件中配置的，没有base，模版的生效后，又恢复为了默认的。是什么情况呢？
