### ISSUE TITLE
生产环境支持 dll

### ISSUE THREAD

**Issue by ikobe** [umijs/umi#1635]
现在 dll 配置是在本地开发环境才生效。在某些场景下，线上环境也是需要 dll 的，可以减少同一次 webpack 构建的使用内存（防止 OOM），且可以一定程度上将相对稳定的部分走 CDN 缓存

**Comment by sorrycc** [comment]
不用 externals 了？

**Comment by ikobe** [comment]
external 不是长久的解决方案，因为会隔断时间就 OOM 一次

**Comment by sorrycc** [comment]
这个先 hold，等 @何幻 那边的方案，需要做的时候再开 issue 吧。

**Comment by ikobe** [comment]
好
