### ISSUE TITLE
umi-plugin-locale support dynamic load locale resource

### ISSUE THREAD

**Issue by yutingzhao1991** [umijs/umi#1638]
当前 locales 下的资源是全量打包的，需要做下动态加载。

**Comment by onpaik** [comment]
新写了个组件，不知道满足你的条件不

https://www.npmjs.com/package/umi-lib-paik

**Comment by sorrycc** [comment]
@onpaik 看起来不错。

**Comment by onpaik** [comment]
统一在了一个包里
https://www.npmjs.com/package/umi-plugin-locale-paik
