### ISSUE TITLE
项目开发完，打包时umi.js和vender.async.js有重复模块

### ISSUE THREAD

**Issue by 269957022** [umijs/umi#1639]

**Comment by 269957022** [comment]
![image](https://user-images.githubusercontent.com/23145969/49990836-081e3f00-ffba-11e8-9c63-962e4744a135.png)

**Comment by 269957022** [comment]
想问一下是否其中包含重复代码，有没有什么可以优化的方向

**Comment by sorrycc** [comment]
这是 webpack 配置的问题，和 umi 没有直接关系。可以搜索下 webpack splitchunks，比如用 vendors 提取公共依赖。
