### ISSUE TITLE
如何实现页面返回不刷新

### ISSUE THREAD

**Issue by sppsun** [umijs/umi#1642]
大家好，目前使用umi框架结合react-mobile做一个小项目，如何实现页面后退不刷新呢？比如列表页-》详情页，当从详情页返回时不刷新列表页，目前总是刷新重新读取数据库。谢谢。

**Comment by xiaohuoni** [comment]
应该不会刷新，你看看，你的获取数据时机对不对

**Comment by sppsun** [comment]
我是在didMount中设置的数据，不知道是不是搞错了。另外，后来通过link to _blank 解决了问题。谢谢。

**Comment by wang777777** [comment]
@xiaohuoni 我想问下怎么不刷新？获取数据 didMount 没错啊

**Comment by singagain** [comment]
> @xiaohuoni 我想问下怎么不刷新？获取数据 didMount 没错啊

你解决了吗？我也遇到这个问题

**Comment by xiaohuoni** [comment]
@singagain https://github.com/umijs/umi/issues/3091
