### ISSUE TITLE
Working on dev, crash on production build. 在生产上造成崩溃

### ISSUE THREAD

**Issue by CristhianUNSa** [umijs/umi#1643]
Hi, my app is just working perfect on my dev environment (npm start).

But when I deploy the dist folder to production (after umi build) , it seems that my initial state on the redux store is not set, and I have some errors showing me that a variable, that should be and object with 2 keys (my model), is undefined.

My initial state on the model:
![image](https://user-images.githubusercontent.com/12214429/50005822-78ad6780-ff8a-11e8-94b4-020bff06ac5f.png)

What I see on the production output:
![image](https://user-images.githubusercontent.com/12214429/50005833-806d0c00-ff8a-11e8-8313-98b41c16a667.png)

As I said, this is just working fine while developing.

Any ideas?

Thank you very much.

**Comment by xiaohuoni** [comment]
是否配置了
```
dva: {
          immer: true
        }
```

**Comment by CristhianUNSa** [comment]
我一直有同样的结果

I'm getting the same result. I will investigate further.

**Comment by CristhianUNSa** [comment]
这是一个页面级模型问题。 由于umi的惯例，它适用于开发（我不喜欢它，因为我好几天都在寻找解决方案，但这也是我的坏处）。
这是有关此按需加载（仅限生产）功能的文档
https://umijs.org/guide/with-dva.html#registering-models

It was a page-level model problem. It works on development because of the convention of umi (I don't like it because I wasted several days looking for a solution but it is my bad too).
This is the documentation about this load on demand (production only) feature:
https://umijs.org/guide/with-dva.html#registering-models
