### ISSUE TITLE
区块的使用场景？

### ISSUE THREAD

**Issue by zwl1619** [umijs/umi#1644]
看了一下[区块](https://umijs.org/zh/guide/block.html)的文档 ，里面说到：

1、区块是指页面级别的可复用的代码
2、区块只是用于开发时新建页面时的提效工具
3、区块要实际应用都需要针对项目需求去修改最后的代码

可是还是不太明白区块的使用场景和怎么使用？能否举个例子？

**Comment by sorrycc** [comment]
等正式版的文档和视频吧。
