### ISSUE TITLE
怎么配置less？

### ISSUE THREAD

**Issue by zwl1619** [umijs/umi#1645]
脚手架里面的css文件，因为我要使用antd-mobile，所以怎么都是写成less文件，那么怎么设置打包less文件呢？

**Comment by wangxingkang** [comment]
不需要设置 直接支持

**Comment by xiaohuoni** [comment]
改一下文件名就可以了

**Comment by dragooncjw** [comment]
使用了less发现不能和css文件一样 `import xxx from 'xxx.less'`，这样会报错，而且我直接使用了`import 'xxx.less'`之后，className引用发现没有效果，有没有大神能解答一下

**Comment by wangxingkang** [comment]
可以这样用的啊 开启了 css module import '***.less'肯定没法用

**Comment by dragooncjw** [comment]
那我该怎么设置呀

**Comment by wangxingkang** [comment]
不适用css module 的话 可以直接关闭  具体看 umi文档

**Comment by wangxingkang** [comment]
import xxx from 'xxx.less' 这种应该是没问题的 ，可以提供个最小仓库 看下

**Comment by dragooncjw** [comment]
你好，我已经将错误放到我的仓库上了：https://github.com/dragooncjw/less_error.git，错误文件位置在src/layouts/index.tsx。里面的import styles from 'test.less'命令行出错了。

**Comment by dragooncjw** [comment]
你好，我已经将错误放到我的仓库上了：https://github.com/dragooncjw/less_error.git 
错误文件位置在src/layouts/index.tsx。里面的import styles from 'test.less'命令行出错了。

**Comment by bldf** [comment]
在 types.d.ts中添加 declare module '*.less'; 就可以了

**Comment by dragooncjw** [comment]
非常感谢，我已经解决了这个问题

**Comment by hackftz** [comment]
怎么解决的？

**Comment by hackftz** [comment]
<img width="679" alt="image" src="https://user-images.githubusercontent.com/33424860/187154170-50e0d09e-1e47-44ef-9690-93ab49d7eb97.png">

**Comment by fz6m** [comment]
> <img alt="image" width="679" src="https://user-images.githubusercontent.com/33424860/187154170-50e0d09e-1e47-44ef-9690-93ab49d7eb97.png">

```bash
  pnpm i -D less
  # npm i -D less
```

**Comment by hackftz** [comment]
> > <img alt="image" width="679" src="https://user-images.githubusercontent.com/33424860/187154170-50e0d09e-1e47-44ef-9690-93ab49d7eb97.png">
> 
> ```shell
>   pnpm i -D less
>   # npm i -D less
> ```

i want to bundle the less files to css files, or I only have to install the `less` and `less loader`, let the project to bundle less files?

**Comment by hackftz** [comment]
like antd
