### ISSUE TITLE
如何实现keep alive功能

### ISSUE THREAD

**Issue by sppsun** [umijs/umi#1646]
大家好，咨询下umi框架中如何实现vue中keep alive类似功能？谢谢。

**Comment by xiaohuoni** [comment]
keep alive是什么功能？

**Comment by sppsun** [comment]
这个是vue里面的功能，我的目的是达到goBack时不要总是刷新，因为总是刷新导致长列表浏览体验很差。

**Comment by hzcdt** [comment]
楼主，你最终是怎么实现在umi框架里使用缓存路由的？
