### ISSUE TITLE
build后，src目录下assets目录中的图片资源没有打包到dist目录下

### ISSUE THREAD

**Issue by huachaoliu** [umijs/umi#165]
１使用场景：根目录下的public目录的图片资源可以打包，src目录下的assets目录中图片资源打包丢失．

２操作系统：ubuntu 16.10

**Comment by sorrycc** [comment]
* public 下的文件无需引用会自动 copy 过去
* 非 public 下的文件需被引用才会打包

**Comment by sorrycc** [comment]
有问题再 reopen 。
