### ISSUE TITLE
What is the suggested way for styling antd components when css modules is enabled?

### ISSUE THREAD

**Issue by theshire-io** [umijs/umi#1651]
For example, consider this:

```
import styles from './test.less';
...
<section className={styles.cards}>
          <Row gutter={16}>
            <Col span={8}>
              <Card title="Sample Card">
                <p>Test</p>
              </Card>
             </Col>
         </Row>
</section>
```

```
// test.less
.cards {
    .ant-card-body {
      min-height: 170px;
      display: flex;
      justify-content: center;
      align-items: center;
    }
}

```

CSS Modules by design will transform `.ant-card-body` to a different name and so it will not match. What is the suggested way for dealing with this situation w.r.t umi and antd?

**Comment by mediatec-software** [comment]
Hi, you should use :global decorator for this.

`.cards {
    :global(.ant-card-body) {
      min-height: 170px;
      display: flex;
      justify-content: center;
      align-items: center;
    }
}`

**Comment by mediatec-software** [comment]
Docs: https://github.com/css-modules/css-modules#exceptions

**Comment by theshire-io** [comment]
Awesome, thank you very much @mediatec-software !
