### ISSUE TITLE
APP_ROOT 指定源代码目录后样式及路由出现问题

### ISSUE THREAD

**Issue by zhangchen2397** [umijs/umi#1654]
修改源代码目录的目的是为了将前后端代码放在一起统一管理，如下结构：

```
src
 |_ client
 |    |_ assets
 |    |_ layouts
 |    |_ pages
 |    |_ components
 |_ server
```

使用的测试代码是 https://github.com/umijs/umi-examples/tree/master/with-nav-and-sidebar

通过增加 `APP_ROOT` 环境变量 `APP_ROOT=src/client umi dev` 执行后，发现样式错乱、路由不工作。

去掉 `client` 这一层目录，直接 `umi dev` 全部都是正常的，这种情况除了增加 `APP_ROOT=src/client` 配置外，还需要额外的配置吗？暂没找到相关的文档。

**Comment by yutingzhao1991** [comment]
你的 package.json 在哪？可能是依赖没找到的原因。

**Comment by yutingzhao1991** [comment]
可以提供一个复现的代码仓库吗？

**Comment by zhangchen2397** [comment]
https://github.com/zhangchen2397/testumi

这里可以复现

**Comment by zhangchen2397** [comment]
> 你的 package.json 在哪？可能是依赖没找到的原因。

初步看，增加了 `APP_ROOT` 后，配置文件 `.umirc.js` 找不到导致，我把 `.umirc.js` 移到 `src/client/.umirc.js 下就 OK 了。

**Comment by yutingzhao1991** [comment]
`.umirc.js` 应该是要在 APP_ROOT 对应的目录下。

**Comment by zhangchen2397** [comment]
> `.umirc.js` 应该是要在 APP_ROOT 对应的目录下。

嗯 多谢了，最好文档中给个说明，不然使用起来比较困惑。
