### ISSUE TITLE
我引入了一个第三方的sdk，应该如何避免sdk 被二次打包

### ISSUE THREAD

**Issue by tmzhenzheng** [umijs/umi#1655]
我引入了一个第三方的sdk，应该如何避免sdk 被二次打包

**Comment by xiaohuoni** [comment]
试试：放到public中，或者其他文件配置[copy](https://umijs.org/zh/config/#copy) 手动拷贝，在[模版html](https://umijs.org/zh/guide/html-template.html#html-%E6%A8%A1%E6%9D%BF)中，添加引用

**Comment by sorrycc** [comment]
还可以试试 externals 配置。
