### ISSUE TITLE
打包静态文件之后部署报404的问题

### ISSUE THREAD

**Issue by yanranxiaoxiaoshu** [umijs/umi#1656]
https://github.com/umijs/umi/issues/296     这个最终是如何解决的呢？ hashHistory不生效，配置exportStatic就不能使用动态路由了。fallback这个方案可以用node来实现吗？

**Comment by xiaohuoni** [comment]
hashHistory改成了 history: 'hash'

**Comment by xiaohuoni** [comment]
https://umijs.org/zh/guide/faq.html#build-%E5%90%8E%E8%AE%BF%E9%97%AE%E8%B7%AF%E7%94%B1%E5%88%B7%E6%96%B0%E5%90%8E-404%EF%BC%9F
