### ISSUE TITLE
extraBabelIncludes not use babel plugin in extraBabelPlugins

### ISSUE THREAD

**Issue by yutingzhao1991** [umijs/umi#1658]

**Comment by yutingzhao1991** [comment]
master 上也有这个问题，其实我想为什么 extraBabelIncludes 要使用 `babelOptsForDeps` 而不是直接用 `babelOpts` 这个呢？

**Comment by yutingzhao1991** [comment]
> extraBabelPlugins 可以加，但不能一致，比如依赖里的不需要加 babel transform runtime 。

有的 extraBabelPlugins 这个里面加的可能就是项目的源代码，比如和 egg 一起用的时候的一些前后端共用的代码目录。感觉应该和 src 里面代码对应的 babel 完全配置一致。

**Comment by sorrycc** [comment]
改用 `babelOpts` 吧。
