### ISSUE TITLE
如何使用web worker

### ISSUE THREAD

**Issue by ParnDeedlit** [umijs/umi#1661]
# 问题描述
在参考  [怎么在 ES6+Webpack 下使用 Web Worker](https://juejin.im/post/5acf348151882579ef4f5a77) 时出现 
> 报错 "window is not defined"
# webpack对应的解决方式
只需要在 webpack 的配置文件下的 output 下，加一个属性对：globalObject: 'this'

``` js
output: {
  path: DIST_PATH,
  publicPath: '/dist/',
  filename: '[name].bundle.[hash:8].js',
  chunkFilename: "[name].chunk.[chunkhash:8].js",
  globalObject: 'this',
}
```

上面的教程是讲解使用webpack的方式

# 请问umi如何使用Web Worker
有对应的参考教程吗？ 谢谢解答？

**Comment by sorrycc** [comment]
这是 webpack 配置的问题，你通过 chainWebpack 修改 output 的配置就好了。

**Comment by lulu116** [comment]
请问umi如何使用Web Worker？
通过chainWebpack修改 webpack 配置，里面都是一些插件使用，怎么加output呢。
