### ISSUE TITLE
如何在入口文件更新state

### ISSUE THREAD

**Issue by Lynn0108** [umijs/umi#1662]
如果想在入口文件做鉴权，但是鉴权信息别的地方也要用到，拿到鉴权信息之后想要保存在state里，app.js好像没有dispatch方法，要怎么保存呢？

**Comment by xiaohuoni** [comment]
```
window.g_app._store.dispatch
```
试试这个

**Comment by Lynn0108** [comment]
@xiaohuoni 请问在app.js哪里可以用这个方法呢？我看_store是null
![image](https://user-images.githubusercontent.com/25974463/53464490-66b96c00-3a85-11e9-877c-04bf102b3f05.png)

**Comment by zhaozhaoyang** [comment]
> ```
> window.g_app._store.dispatch
> ```
> 
> 试试这个

window.g_app._store.dispatch 这个是取得数据是响应式的吗？
