### ISSUE TITLE
Define Plugin still doesn't work when HardSource is true

### ISSUE THREAD

**Issue by heya-aron** [umijs/umi#1672]
A few months ago @Jetsly introduced a bug in PR #1071  and a fix in PR #1072 , however, these changes have not a made a difference. 

I edited define as such: 
```
const apiUrls = {
  production: '1',
  staging: '2',
  dev: '3',
  local: '4',
};
. . .
define: {
    APP_TYPE: process.env.APP_TYPE || '',
    ENV: apiUrls[process.env.TEST],
  },
```

If I console.log `ENV` in any part of my application, I'll usually get the same value despite passing in a different value for `process.envTEST`. This examples comes strictly out of ant-design-pro, and it happens despite the change made in #1072 . 

Just to be clear, I'm only using files on config/ without dedicated .umirc config files.

**Comment by dannyzix** [comment]
Wow that was good?

**Comment by sorrycc** [comment]
Just disable hardSource, it has too many problems.
