### ISSUE TITLE
如何才能动态增加路由？

### ISSUE THREAD

**Issue by undefinedor** [umijs/umi#1673]
目前有个项目,想在登录成功后,请求后端接口，返回路由信息，动态添加到router中。。
因为是使用的ant design pro 的脚手架。。所以路由配置是在`config/router.config.js`  接着会在`src/pages/.umi` 会生成一份 router.js。
但是.umi的是会被覆盖的。所以。我如何才能在config/router.config.js 中 通过后端接口 动态增加路由呢？

**Comment by CoolBerry** [comment]
有同样的疑问

**Comment by iceberg211** [comment]
config/router.config.js 最终会导入到BasicLayout.js之中，在BasicLayout.js之中操作数组

**Comment by peterlxb** [comment]
在BasicLayout里面处理那个数组，只是隐藏了，用户输入相应的url路径还是能访问到页面。

**Comment by zaibinzhang** [comment]
有同样的疑问并且做过各种尝试都无效

**Comment by yunuo-tech** [comment]
有同样的疑问

**Comment by exvu** [comment]
> 参考这个例子，https://github.com/umijs/umi-examples/tree/master/runtime-routes-appjs
能不能在model或者是运行后更新路由并重新渲染呢？

**Comment by BANG666** [comment]
> 目前有个项目,想在登录成功后,请求后端接口，返回路由信息，动态添加到router中。。
> 因为是使用的ant design pro 的脚手架。。所以路由配置是在`config/router.config.js` 接着会在`src/pages/.umi` 会生成一份 router.js。
> 但是.umi的是会被覆盖的。所以。我如何才能在config/router.config.js 中 通过后端接口 动态增加路由呢？

请问解决这个问题了吗

**Comment by AnZhiYu** [comment]
同样的疑问

**Comment by CliffKnight** [comment]
> > 参考这个例子，https://github.com/umijs/umi-examples/tree/master/runtime-routes-appjs
> > 能不能在model或者是运行后更新路由并重新渲染呢？

done

**Comment by shanshiping** [comment]
同样的疑问
