### ISSUE TITLE
socket.io 代理

### ISSUE THREAD

**Issue by jiechud** [umijs/umi#1674]
在umirc.js 配置socket.io  proxy 不生效
```
'/socket.io': {
      ws: true,
      target: ''
    }
```

我用 webpacke-dev-server 测试是可以的

**Comment by sorrycc** [comment]
怎么复现？给个完整例子？

**Comment by jiechud** [comment]
我明天提供一个demo

**Comment by jiechud** [comment]
现在umi 没有沙箱环境，我写了一个demo， 包含 umi 和 webpack-dev-server的
代码地址 [umi-proxy-socket](https://github.com/jiechud/umi-proxy-socket) README.md 有启动描述

### webpack-dev-server 使用

[配置](https://github.com/jiechud/umi-proxy-socket/blob/master/webpack-dev-server-socket/webpack.config.js#L13)
```
    devServer: {
        port: '8080',
        proxy: {
          '/socket.io': {
            ws: true,
            target: 'http://www.jiechud.site:3000'
          }
        }
    },
```
[使用方法](https://github.com/jiechud/umi-proxy-socket/blob/master/webpack-dev-server-socket/index.js#L4)
```
socket.on('request', (msg) => {
        const div = document.createElement('div')
        div.innerHTML = msg
        document.querySelector('.box').append(div)
        console.log('msg', msg)
  })
```

### umi 使用

[配置](https://github.com/jiechud/umi-proxy-socket/blob/master/umi-socket/.umirc.js#L23)
```
 proxy: {
    "/socket.io": {
      "target": "http://www.jiechud.site:3000/",
      "ws": true,
    }
  },
```
[使用方法](https://github.com/jiechud/umi-proxy-socket/blob/master/umi-socket/src/pages/demo.js#L13)
```
 socket.on('request', (msg) => {
        const { data } = this.state;
        data.push(msg);
        this.setState({
          data: [...data],
        })
        console.log('msg', msg)
      })
```

现在umi表现的是通过轮询去拿信息，没有通过websocket获取。截图如下：
![image](https://user-images.githubusercontent.com/9709396/50323803-6301ea00-0516-11e9-8516-6598f4602a6d.png)

**Comment by sorrycc** [comment]
有解决吗？试了下发现 socket server 挂了。

**Comment by jiechud** [comment]
@sorrycc  端口冲突了，服务启动起来了。目前还没有解决。
用了一个折中的办法，加了个环境变量。
```
let origin = `http://${window.location.host}`;
if (process.env.NODE_ENV === 'development') {
  origin = process.env.SOCKET_URL;
}
```

**Comment by sorrycc** [comment]
看了下实现，proxy 换了种方式实现，因为 proxy 还要支持 hmr ，所以目前没有做 ws 的支持，这个优先级比较低，issue 我关了。感兴趣的话可以直接提 PR。

**Comment by sorrycc** [comment]
看了下实现，proxy 换了种方式实现，因为 proxy 还要支持 hmr ，所以目前没有做 ws 的支持，这个优先级比较低，issue 我关了。感兴趣的话可以直接提 PR。

**Comment by jiechud** [comment]
好的，能给点解决的思路吗，我研究下，看能不能解决

**Comment by maosong** [comment]
@jiechud 问题有解决吗？我也有类似问题 #3255

**Comment by jlsky** [comment]
我是在 ant design pro 里面使用原生的websocket，我现在能发送数据，也能收到数据。但是不知道如何把数据送到models或者react组件中。
//service file
const wsurl = 'ws://ip:8810/wx/ws/scope';
const heartbeat = 56; // nginx default 60s timeout
let live = 0; // == heartbeat, ping。unit: second。
let ws = {}; // WebSocket

const wsopen = () => {
  console.log('onopen');
  ws.onmessage = ({ data }) => { // ws connecting, readyState == 0
    const result = JSON.parse(data);
    console.log('onmessage');
  };
  ws.onerror = event => {
    console.log(event);
  };
};

// action as callback ，这个我不会写。
export const listen = action => {
  console.log('action');
  //todo
};

export const send = msg => {
  ws.send(msg);
  live = 0;
};

const wsinit = () => {
  if (ws.readyState !== 0 || ws.readyState !== 1) {
    try {
      ws = new window.WebSocket(wsurl);
      console.log(ws.readyState);
      wsopen();
    } catch (err) {
      //
    }
  }
};

setInterval(() => {
  if (ws.readyState === 1) {
    if (live > heartbeat) {
      ws.send(''); // as ping
      live = 0;
    } else {
      live += 1;
    }
  } else {
    wsinit();
    live = 0;
  }
}, 990);

//model中的部分。import * as socket from '@/services/xxx';
effects: {
    sendmsg({ msg }) {
      console.log('from btn to models');
      socket.send(msg);  // 即service中的
    },
  },

**Comment by maosong** [comment]
@jlsky 我这边的问题已经解决了，也是不依赖webpack的proxy，用socket.io直接连接。

要访问全局状态，可以使用umijs的window.g_app，如果在app.js的render中拿到window.g_app，是未初始化的，这个要注意。

**Comment by tangseng** [comment]
@jlsky 我这边是通过传递dispatch来实现的，仅供参考~

这是某个model文件
```
export default {

  //...

  effects: {
    * socket({ dispatch }: any, { select }: any) {
      const state = yield select(({ xxx }: any) => xxx);

      const ws = new WebSocket(`ws://127.0.0.1:8888`);

      ws.addEventListener('open', () => {
        dispatch({
          //...
        });
      });

      ws.addEventListener('message', (event: any) => {
        dispatch({
          type: 'xxx/updateState',
          payload: event,
        });
      });

      ws.addEventListener('close', () => {
        dispatch({
          //...
        });
      });
    }
  },
  
  subscriptions: {
    socket({ dispatch }: { dispatch: any; history: any; }) {
      dispatch({
        type: 'socket',
        dispatch,
      });
    }
  } ,
};
```

**Comment by undoZen** [comment]
我是通过实现一个小插件来给 umi 的 dev server 打上一个 socketio 的 patch
