### ISSUE TITLE
改进 umi/locale 的提示问题

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#1675]
## 方案

之前是

```js
import { formatMessage } from 'umi/locale';
```

直接用 umi-plugin-locale 的情况下，改成

```js
import { formatMessage } from 'umi-plugin-locale';
```

如果用 umi-plugin-react，则加一层转发，

```js
import { formatMessage } from 'umi-plugin-react/locale';
```

对用户暴露的是最后一个写法，虽然有点长，但目前没有更好的方案了。

## 相关

* #1499

**Comment by sorrycc** [comment]
@leftstick 有没有兴趣实现下？

**Comment by yutingzhao1991** [comment]
还有一个问题，是不是 antd 也应用 `umi-plugin-react/antd` 这样的方式来用，这样项目就不需要安装 antd 了。

**Comment by sorrycc** [comment]
是的，antd、dva 等都是这样，可以一起改了。

**Comment by sorrycc** [comment]
umi-plugin-react 有点长，后续可以考虑改个名。

**Comment by leftstick** [comment]
@sorrycc  有点慌啊，等大佬动手先，我跟着打酱油^^

**Comment by leftstick** [comment]
我有个问题比较好奇该如何解决，既然`.d.ts`文件应该由插件`umi-plugin-locale`自己提供，那它该如何暴露在`umi-plugin-react/locale`路径下？

`umi-plugin-locale/lib/locale`模块可以通过修改`webpack. alias`来提供暴露路径，`.d.ts`用`postInstall`拷贝到`umi-plugin-react`下面去？

**Comment by amily4555** [comment]
其实插件什么的 可以考虑用 ts 来开发；
ts 类型约束 来写底层代码很爽的·

**Comment by yutingzhao1991** [comment]
关于 `umi-plugin-react/antd` 名字太长，不好看的问题是不是可以在 npm 上面搞一个 scope `@umi` 然后插件的包都发里面。用法就变成 `@umi/react/antd` 这样了。

**Comment by wangxingkang** [comment]
@umi + 1
