### ISSUE TITLE
怎样支持http2拆分代码？

### ISSUE THREAD

**Issue by songdun** [umijs/umi#1678]
问题背景：
希望能将项目拆分为适合http2的包，使用webpack插件AggressiveSplittingPlugin将原来的 chunk 分成更小的 chunk

尝试代码：
按照 webpack-chain 文档，在plugin.config.js文件里添加了如下代码：
`
config
  .plugin('AggressiveSplittingPlugin')
  .use(webpack.optimize.AggressiveSplittingPlugin, [{
    minSize: 30000, // 字节，分割点。默认：30720
    maxSize: 50000, // 字节，每个文件最大字节。默认：51200
  }]);
`
文件整体代码为：
<img width="539" alt="qq20181219-173208 2x" src="https://user-images.githubusercontent.com/15406103/50211615-0a1a4080-03b4-11e9-854a-7b6ff10c295d.png">

但是报错：
dev环境
<img width="811" alt="qq20181219-172643 2x" src="https://user-images.githubusercontent.com/15406103/50211485-bad41000-03b3-11e9-80dd-b47bc7576f96.png">

build环境
<img width="315" alt="qq20181219-172811 2x" src="https://user-images.githubusercontent.com/15406103/50211473-b4de2f00-03b3-11e9-89ee-aa37125557be.png">

是因为限制了文件最大值和最小值而破坏了umi本身吗？该怎么处理？

**Comment by songdun** [comment]
是啊 umi好像被拆散了 那其他项目在部署http2的时候是怎么操作的呢？ 按照现有的默认打包后 最开始只有5个并发请求 使用http2和http1.1没什么区别 提现不出http2的特性

**Comment by sorrycc** [comment]
我没用过这个插件，我们的业务好像还没有到需要做这种极致优化的阶段。

**Comment by songdun** [comment]
现在就是觉得umi.js的gzip压完有400k左右 如果网不好的话还是会慢 所以想看下有没有其他更好的优化方法

**Comment by sorrycc** [comment]
可以分析下为啥拆完后没有 umi.js 。

**Comment by songdun** [comment]
我理解的是 需要一个完整的umi.js文件 但是这个文件正常打包是400k  
而AggressiveSplittingPlugin插件的配置项 配置最大的文件为50000字节 超过就会被拆 于是一个umi.js可能被拆成了umi-1.js umi-2.js umi-3.js...这样 但是 某个初始文件在初始化系统时又需要饮用umi.js这个文件 这可能和umi自身框架的打包工具相关

**Comment by amily4555** [comment]
我记得 umi 拆分一直有问题，我在 umi@v1 时代就想拆分了···||

**Comment by 104gogo** [comment]
umi3.0还是没有解决这个问题。。
