### ISSUE TITLE
antd-mobile的样式出不来

### ISSUE THREAD

**Issue by lpp18** [umijs/umi#1681]
项目安装antd-mobile之后样式出不来，
![image](https://user-images.githubusercontent.com/22489347/50216002-91b97c80-03bf-11e9-8ee0-c38921233cdd.png)
官方文档说配了这个就行了，
还需要什么配置吗？

这是我的项目配置
![image](https://user-images.githubusercontent.com/22489347/50216330-70a55b80-03c0-11e9-8281-a770e0479e32.png)

**Comment by sorrycc** [comment]
参考 https://github.com/umijs/umi-examples/tree/master/eleme-demo 。如果还是不能，提供可复现例子再 reopen 。
