### ISSUE TITLE
.umirc.js中配置了排除 models目录，没有生效是什么原因呢？

### ISSUE THREAD

**Issue by tuozq** [umijs/umi#1682]
![image](https://user-images.githubusercontent.com/31910328/50266984-b154b180-0460-11e9-85b1-a77d8c859bc0.png)

![image](https://user-images.githubusercontent.com/31910328/50266879-4e631a80-0460-11e9-9b18-1790700b1008.png)

./umi/router.js 中还是生成了 models目录下的js

**Comment by sorrycc** [comment]
可能是 windows 下的 bug， @xiaohuoni 有空验证下吗？

**Comment by xiaohuoni** [comment]
mac和window都试了没有问题

**Comment by xiaohuoni** [comment]
@tuozq 把你的demo，发出来看看，可以吗

**Comment by sorrycc** [comment]
给复现仓库有再 reopen 。
