### ISSUE TITLE
使用umi-plugin-react插件内置的antd无法externals出antd

### ISSUE THREAD

**Issue by sciice** [umijs/umi#1689]
在`umi-plugin-react`插件内启用`antd: true`打包后大小：
<img width="333" alt="2" src="https://user-images.githubusercontent.com/45462433/50288722-ab32f500-04a1-11e9-8332-8f89d7327bf1.png">

注释掉`antd`后打包后的大小：
<img width="396" alt="1" src="https://user-images.githubusercontent.com/45462433/50288714-a79f6e00-04a1-11e9-9605-4511a118c0a3.png">

仓库地址 ：

https://github.com/sciice/umi-antd

**Comment by sorrycc** [comment]
参考 https://webpack.js.org/configuration/externals/ 用函数或者正则，因为 antd 实际上会被解析为 `antd/es/xxx`。

**Comment by sciice** [comment]
好的，我去试试！先关掉
