### ISSUE TITLE
px2rem-loader @import 引入css 无法编译

### ISSUE THREAD

**Issue by xwjune** [umijs/umi#1691]
.umirc.js配置新增
chainWebpack(config) {
config.module
      .rule('compile')
        .test(/\.(js|jsx|css|scss|less)$/)
        .exclude
          .add('node_modules')
          .end()
        .use('webpack-px-to-rem')
          .loader('webpack-px-to-rem')
          .options(JSON.stringify({
            basePx: 37.5,
            min: 1,
            floatWidth: 6,
          }));
}
通过@import引入的(css|scss|less)文件，px没有编译成rem

**Comment by xwjune** [comment]
@sorrycc 大神如果看到，帮忙解决，不胜感激

**Comment by LukerSpringtree** [comment]
> @xwjune 开启hd，有这个功能
 ## https://github.com/umijs/umi/issues/706

我不想都转, 我 样式文件里面有几个 px 的值不要转.怎么设置呢?

"px2rem-loader" 这个loader 有在后面备注 /* no */  这样的方式可以不转

这个 hd 有类似的处理方法吗 ?

**Comment by sanshuiwang** [comment]
> @xwjune 开启hd，有这个功能

现在umi3 没有hd啦，怎么处理？？？
