### ISSUE TITLE
How to use with rematch?

### ISSUE THREAD

**Issue by eparizzi** [umijs/umi#1698]
I want to use umi with rematch instead of dva.

I've found [this plugin](https://www.npmjs.com/package/umi-plugin-rematch), but it's not working. Says `RENDER is undefined` during plugin initialization.

Is there a non-plugin way to call rematch init() and pass the initialized store to the app container? 
There isn't an `index.js` in umi setup so I guess that's auto-generated by umi into `.umi` folder. Any way to override that without a plugin?

**Comment by xiaohuoni** [comment]
https://github.com/daqi/umi-plugin-rematch/issues/1

**Comment by xiaohuoni** [comment]
There is no official plug-in yet.You can wait for the author to fix [it](https://github.com/daqi/umi-plugin-rematch/issues/1).Or refer to [umi-plugin-dva](https://github.com/umijs/umi/tree/master/packages/umi-plugin-dva) and finish one by yourself.

**Comment by jerexyz** [comment]
Maybe this will help you.
https://github.com/jerexyz/umi-plugin-rematch
