### ISSUE TITLE
开启了hmr后编译不了！

### ISSUE THREAD

**Issue by rendongsc** [umijs/umi#1710]
````
dva: {
     hmr: true,
  }
````
![qq20181226-164453](https://user-images.githubusercontent.com/12553638/50439618-b1a3ef80-092d-11e9-9455-65c24b4b1021.png)
![qq20181226-164529](https://user-images.githubusercontent.com/12553638/50439626-b5377680-092d-11e9-972a-4e6c626690fa.png)
 hmr: 设置成false是OK 的！
说明：这个跟文件名中的分隔符没有关系的。

**Comment by xiaohuoni** [comment]
在https://github.com/umijs/umi-examples/tree/master/with-dva 测试了不存在这个问题，说明一下环境和重现步骤
