### ISSUE TITLE
开启高清方案hd:true选项后，第三方组件被缩放

### ISSUE THREAD

**Issue by XuChunxiao** [umijs/umi#1717]
由于hd会根据dpr设置scale，第三方组件使用的px单位的相关样式会被缩放(缩小)。目前的想法是把第三方组件的px处理成rem，部分三方组件样式容易覆盖的好处理，但是部分是动态计算的，不好处理。想咨询一下关于这个问题的正确处理方式。

**Comment by xiaohuoni** [comment]
尽量使用移动端的第三方样式吧，

**Comment by XuChunxiao** [comment]
> 尽量使用移动端的第三方样式吧，

用的是antd mobile,不过遇到一些antd mobile不支持功能点，如datepicker不支持秒，如需要用到highcharts等。目前看的话，我这种情况是不是不使用umi的hd方案是最佳选择了？

**Comment by xiaohuoni** [comment]
antd mobile 应该能很好的兼容吧。如果存在你说的问题，去mobile社区提bug吧

**Comment by XuChunxiao** [comment]
antd mobile高清适配目前没发现什么问题(除了功能上的限制不得不用三方的)
和antd mobile相关的已经提了，但待解决日期未知，和antd mobile无关的，暂无法处理
先用别的方案了，close。
