### ISSUE TITLE
Beeping Sound on file changes.

### ISSUE THREAD

**Issue by cristian-eriomenco** [umijs/umi#1720]
Each time there is a webpack rebuilt, a windows beeping sound happens. Any ideas how to turn this off? It doesn't happen on raw webpack.

Windows: 10
CLI: CMD or Powershell
Umi version: 2.2.7

**Comment by sorrycc** [comment]
There will be a sound if something goes wrong. Do you mean it produce sound when rebuild is successful?

**Comment by cristian-eriomenco** [comment]
@sorrycc Can i turn this behaviour off? I prefer not to hear any sounds even when it fails.

**Comment by cristian-eriomenco** [comment]
@sorrycc Just to clarify again. It does beep when it fails. I want to turn beeping off so it never beeps no matter what the build result is? Can you please point me out if there is an option?

**Comment by sorrycc** [comment]
I'll add a environment variable to turn this off.

**Comment by cristian-eriomenco** [comment]
Fantastic! Thank you so much!
