### ISSUE TITLE
提升.env.local设置的环境变量优先级

### ISSUE THREAD

**Issue by liuwf2012** [umijs/umi#1727]
https://github.com/umijs/umi/commit/0743744f4d2ef8474107ad660a5195cb0201b3b6#diff-ef8f7c256d5fe475b02815765b07e6a4

从这次递交的逻辑，环境变量的优先级最终为 ：cross-env > .env > .env.local

是否 cross-env > .env.local > .env 会更合理一些

**Comment by sorrycc** [comment]
同意。

**Comment by sorrycc** [comment]
想了想，我觉得 `.env.local` 比 `.env` 优先级高会更合理些。。
