### ISSUE TITLE
dev模式下node_modules下面模块样式丢失

### ISSUE THREAD

**Issue by QSQ1989** [umijs/umi#1728]
封装了一些常用模块，打成npm包安装后使用，没有样式，从安装好的包文件直接copy到src下引入样式正确

**Comment by QSQ1989** [comment]
@sorrycc 是默认的配置less-loader忽略了node_modules文件夹吗？

**Comment by sorrycc** [comment]
原因是 node_modules 下不处理 css modules 的，推荐用 create-umi 创建 library 的脚手架，已提供组件调试和打包提供。

**Comment by sorrycc** [comment]
原因是 node_modules 下不处理 css modules 的，推荐用 create-umi 创建 library 的脚手架，已提供组件调试和打包提供。

**Comment by NexxLuo** [comment]
遇到了同样的问题，使用umi-library发布的npm包中存在css modules，安装后样式丢失。现在有解决方案吗？
