### ISSUE TITLE
配置dll为true，antd message组件样式无法正常引入

### ISSUE THREAD

**Issue by hongzelin** [umijs/umi#1733]
配置dll：true，antd message组件的样式没有被引入，导致message组件有问题，当把dll配置去掉后，message组件就没有问题了，样式正常引入。其他antd的组件目前没有发现有该问题。

**Comment by wangxingkang** [comment]
我也遇到了  umi 是最新版本

**Comment by LayGit** [comment]
同遇到此问题，我 umi 项目引用了 [https://github.com/LayGit/lay-editor](https://github.com/LayGit/lay-editor)
在 lay-editor 中引用了 rc-tools 和 部分 rc 组件，配置 dll 的情况下，部分组件样式无法正常加载，global.less 样式也无法正常加载。
去掉引用 lay-editor，即使配置 dll 也可以正常加载 global.less 里的样式
是否 rc-tools 或者 部分 rc 组件存在不兼容？antd 也是引用的 rc 组件
umi v2.3.2
umi-plugin-react v1.3.2

**Comment by sorrycc** [comment]
给一个可复现的简单仓库？

**Comment by sorrycc** [comment]
在 #915 跟进，同一个问题。

**Comment by hongzelin** [comment]
> 给一个可复现的简单仓库？

大神，请接收。https://github.com/hongzelin/dll-verification
