### ISSUE TITLE
umi-dva-user-dashboard 中图片路径问题

### ISSUE THREAD

**Issue by xlsdg** [umijs/umi#174]
https://github.com/umijs/umi-dva-user-dashboard 中 build 生成的文件路径问题。

`package.json` 文件:

```json
{
  "private": true,
  "scripts": {
    "start": "umi dev",
    "build": "umi build",
    "lint": "eslint --ext .js src test",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "dva": "^2.1.0",
    "umi": "^1.0.5",
    "umi-plugin-dva": "^0.3.0"
  },
  "devDependencies": {
    "eslint": "^4.18.2",
    "eslint-config-umi": "^0.1.3",
    "eslint-plugin-flowtype": "^2.46.1",
    "eslint-plugin-import": "^2.9.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.7.0",
    "husky": "^0.14.3"
  }
}

```

**Comment by xlsdg** [comment]
![image](https://user-images.githubusercontent.com/1203305/37077088-5a6ede42-2214-11e8-88f3-326dca43fb97.png)

![image](https://user-images.githubusercontent.com/1203305/37077104-6d3013fc-2214-11e8-9f00-727fa424eb6b.png)

**Comment by xlsdg** [comment]
尝试添加 [publicPath](https://github.com/xlsdg/umi-dva-antd-starter/blob/master/.webpackrc.js)，但是 build 生成的 `index.html`，`umi.js` 路径无法访问。

**Comment by sorrycc** [comment]
在 .webpackrc 里配置 publicPath，指向静态资源所在的路径，比如 `/static/`。
