### ISSUE TITLE
umi block add 模块，出现内存溢出

### ISSUE THREAD

**Issue by guihua** [umijs/umi#1740]
异常出现步骤：
1.项目运行正常出现：I am a umi block!
2.umi block list 正常：
![block list ](https://user-images.githubusercontent.com/3782324/50579471-2fad4c80-0e80-11e9-9e1a-4d1a41305332.png)
3.umi block add ant-design-pro/Analysis 异常：
![block add 模块](https://user-images.githubusercontent.com/3782324/50579550-f0cbc680-0e80-11e9-881d-b12eb02719c5.png)

**Comment by sorrycc** [comment]
执行 `DEBUG=umi* umi block add ant-design-pro/Analysis` 再给个日志？

**Comment by guihua** [comment]
![umi1](https://user-images.githubusercontent.com/3782324/50583461-53828980-0ea4-11e9-93c4-e03f4ad30783.png)
![umi2](https://user-images.githubusercontent.com/3782324/50583462-541b2000-0ea4-11e9-809d-3bfc0c592659.png)
![umi3](https://user-images.githubusercontent.com/3782324/50583464-54b3b680-0ea4-11e9-8905-3132b6d646f5.png)

**Comment by guihua** [comment]
@sorrycc 日志已经附上

**Comment by sorrycc** [comment]
使用 block 之前，这个项目也是用 npm 安装的依赖吗？

**Comment by guihua** [comment]
尝试用 yarn 和 cnpm 均失败，然后用 npm 成功了
