### ISSUE TITLE
Document devServer configuration

### ISSUE THREAD

**Issue by theshire-io** [umijs/umi#1742]
`devServer` is [implemented](https://github.com/umijs/umi/pull/1028/commits/95f50ba8aff82a62004b51b907b8e5153c9cc80c) but not documented. This is extremely useful when running the dev server inside Docker because otherwise webpack can't detect file changes and re-compile.

This is what worked for me on `.umirc.js`:
```
  devServer: {
    watchOptions: {
      ignored: /node_modules/,
      poll: true,
      aggregateTimeout: 300,
    }
  },
```

**Comment by dviluk** [comment]
Thank you!
