### ISSUE TITLE
单独使用 af-webpack 报错

### ISSUE THREAD

**Issue by 104gogo** [umijs/umi#1744]
运行 af-webpack/dev 方法，报错信息如下：
![image](https://user-images.githubusercontent.com/8522646/50583710-dc4df500-0ea5-11e9-842e-a2ecdde0607b.png)
配置代码：
```javascript
const path = require('path');
const dev = require('af-webpack/dev').default;
const getConfig = require('af-webpack/getConfig').default;

const cwd = process.cwd();
const babel = path.resolve(__dirname, './babelrc.js');

const webpackConfig = getConfig({
  cwd,
  entry: '../site/index.js',
  babel,
});

dev({ webpackConfig });
```
这些依赖包不应该在安装 af-webpack 时，一起安装了吗？

**Comment by sorrycc** [comment]
这是你项目的依赖吧？

**Comment by 104gogo** [comment]
我换成直自己写的 webpack.config 配置就没问题。那我再检查下。

**Comment by 104gogo** [comment]
https://github.com/104gogo/es6-test/tree/af-webpack

**Comment by 104gogo** [comment]
https://github.com/104gogo/es6-test/tree/af-webpack
还是不行，我提交了一个测试代码，start 命令是使用的 af-webpack，start1 是项目里面的 webpack 配置。
@sorrycc 你可以试试

**Comment by leftstick** [comment]
首先`const babel = path.resolve(__dirname, './babelrc.js');`这句话好像就有点问题，我总觉得根据[https://github.com/umijs/umi/blob/master/packages/af-webpack/src/getConfig/index.js#L115-L135](https://github.com/umijs/umi/blob/master/packages/af-webpack/src/getConfig/index.js#L115-L135)的用法，应该改成：

`const babel = require(path.resolve(__dirname, '..', '.babelrc.js'));`

**Comment by 104gogo** [comment]
```javascript
const path = require('path');
const dev = require('af-webpack/dev').default;
const getConfig = require('af-webpack/getConfig').default;

const cwd = process.cwd();
const babel = path.join(cwd, '.babelrc.js');
const entry = path.join(cwd, 'site/index.js');

const webpackConfig = getConfig({
  cwd,
  entry,
  babel,
});

dev({ webpackConfig });
```

**Comment by sorrycc** [comment]
传参少很多，参考 [umi-build-dev 里的用法](http://github.com/umijs/umi/blob/92581cae3edde9e353ff397800e4fb104a9ebc45/packages/umi-build-dev/src/plugins/commands/dev/index.js#L92)，另外直接用 af-webpack 不是推荐的用法，遇到问题需要自己对比排查解决。

**Comment by 104gogo** [comment]
建议把 af-webpack 的文档补一下
