### ISSUE TITLE
 添加 normalize.css 依赖   global.scss样式没有引入

### ISSUE THREAD

**Issue by wangxingkang** [umijs/umi#1745]
添加 normalize.css 依赖 就会出现这个问题  umi.css 只会包含normalize.css中的样式

_Originally posted by @wangxingkang in https://github.com/umijs/umi/issues/1739#issuecomment-450809913_

**Comment by wangxingkang** [comment]
代码并没有 引入的操作

**Comment by sorrycc** [comment]
可最简可复现仓库吧。

**Comment by wangxingkang** [comment]
稍等

**Comment by wangxingkang** [comment]
@sorrycc https://github.com/wangxingkang/umi-example

**Comment by sorrycc** [comment]
[dll](https://github.com/wangxingkang/umi-example/blob/master/.umirc.js#L14) 的配置里 exclude 掉 `normalize.css`，

```
exclude: [
  'normalize.css'
],
```
