### ISSUE TITLE
ts can't set webpackChunk false

### ISSUE THREAD

**Issue by ycjcl868** [umijs/umi#1748]
```
// .umirc.js
// https://github.com/ycjcl868/jsx2css/blob/master/.umirc.js
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

export default {
  base: '/jsx2css/',
  publicPath: '/jsx2css/',
  outputPath: './site',
  chainWebpack(config, { webpack }) {
    config.plugin('moncaco').use(new MonacoWebpackPlugin());
  },
  plugins: [
    ['umi-plugin-react', {
      antd: true,
      dva: false,
      pwa: false,
      dynamicimport: {
        webpackChunkName: false,
      },
    }],
    ['umi-plugin-gh-pages'],
  ]
}

```

I run `umi build`

but chunkName always existed.

![image](https://user-images.githubusercontent.com/13595509/50590303-5641a680-0ec5-11e9-82cd-ea7346d7b45c.png)

[Github repo](https://github.com/ycjcl868/jsx2css), `npm run site:build`

**Comment by sorrycc** [comment]
49 in 49.async.js is not webpackChunkName, if you don't want use the number, set webpackChunkName to true.

**Comment by ycjcl868** [comment]
oh, it's because of `moncaco` in my project, chunk so many files.
