### ISSUE TITLE
关于alias的问题

### ISSUE THREAD

**Issue by gouding** [umijs/umi#1749]
![image](https://user-images.githubusercontent.com/13016673/50590460-1929e400-0ec6-11e9-8fd3-ef2d1c3e140f.png)
请问这个该怎么去配置，还需要写webpack.config.js吗，有了.umirc.js应该只会读这个配置吧，我按文档加了后，然后通过相对路径去加载会报错。求解，谢谢

**Comment by wangxingkang** [comment]
```
// .umirc.js
 alias: {
    Utilities: resolve(__dirname, 'src/utilities/'),
    Templates: resolve(__dirname, 'src/templates/')
  },
```

不需要配置吧  一般 都在 src目录下  src umi内置为@

**Comment by gouding** [comment]
> ```
> // .umirc.js
>  alias: {
>     Utilities: resolve(__dirname, 'src/utilities/'),
>     Templates: resolve(__dirname, 'src/templates/')
>   },
> ```
> 不需要配置吧 一般 都在 src目录下 src umi内置为@

哦 谢谢 我刚试了下  确实是支持默认@的

但在.umirc.js里直接配置alias:{} 这个貌似不可以

**Comment by llh1187** [comment]
> > ```
> > // .umirc.js
> >  alias: {
> >     Utilities: resolve(__dirname, 'src/utilities/'),
> >     Templates: resolve(__dirname, 'src/templates/')
> >   },
> > ```
> > 
> > 
> > 不需要配置吧 一般 都在 src目录下 src umi内置为@
> 
> 哦 谢谢 我刚试了下 确实是支持默认@的
> 
> 但在.umirc.js里直接配置alias:{} 这个貌似不可以

可以的，我就是直接在.umirc.js里面配置的，但是把配置复制黏贴到config目录下之后，反而不起作用了。（我已经删掉了.umirc.js文件了）

**Comment by awefeng** [comment]
> > > ```
> > > // .umirc.js
> > >  alias: {
> > >     Utilities: resolve(__dirname, 'src/utilities/'),
> > >     Templates: resolve(__dirname, 'src/templates/')
> > >   },
> > > ```
> > > 
> > > 
> > > 不需要配置吧 一般 都在 src目录下 src umi内置为@
> > 
> > 
> > 哦 谢谢 我刚试了下 确实是支持默认@的
> > 但在.umirc.js里直接配置alias:{} 这个貌似不可以
> 
> 可以的，我就是直接在.umirc.js里面配置的，但是把配置复制黏贴到config目录下之后，反而不起作用了。（我已经删掉了.umirc.js文件了）

有解决吗 单独拎出来好像都不行

**Comment by YingJiangHui** [comment]
> > > > ```
> > > > // .umirc.js
> > > >  alias: {
> > > >     Utilities: resolve(__dirname, 'src/utilities/'),
> > > >     Templates: resolve(__dirname, 'src/templates/')
> > > >   },
> > > > ```
> > > > 
> > > > 
> > > > 不需要配置吧 一般 都在 src目录下 src umi内置为@
> > > 
> > > 
> > > 哦 谢谢 我刚试了下 确实是支持默认@的
> > > 但在.umirc.js里直接配置alias:{} 这个貌似不可以
> > 
> > 
> > 可以的，我就是直接在.umirc.js里面配置的，但是把配置复制黏贴到config目录下之后，反而不起作用了。（我已经删掉了.umirc.js文件了）
> 
> 有解决吗 单独拎出来好像都不行

__dirname 获取到的是当前目录 即：project/path/config
