### ISSUE TITLE
样式文件警告Could not freeze ..... Cannot read property 'hash' of undefined

### ISSUE THREAD

**Issue by StoneNN** [umijs/umi#1751]
![qs](https://user-images.githubusercontent.com/33950681/50622195-6352aa00-0f46-11e9-8a56-d9bf8e214e01.png)
...... "umi": "^2.3.2"......
删除node_modules./cash,重启umi dev，并没有消除这些警告，但是不会影响代码运行。

**Comment by leftstick** [comment]
关了`hardSource`吧，用`hardSource: false`

**Comment by taichiyi** [comment]
如果还不行的话，就把dll给注释了[https://umijs.org/plugin/umi-plugin-react.html#dll](dll)
