### ISSUE TITLE
umi+egg 官方 demo 支持在移动端打开调试吗？

### ISSUE THREAD

**Issue by hanzichi** [umijs/umi#1752]
以 umi+egg 整合的官方 demo 为例 <https://github.com/eggjs/examples/tree/master/assets-with-umi>，在 pc 上可以用 `npm run dev` 命令，然后打开 <http://localhost:7001> 即可看到页面，如何能在移动端打开这个 demo？

目前做的尝试是首先将 <http://localhost:7001> 改成 ip+7001 的形式在移动端打开，但是因为页面引用了 <http://localhost:8000/umi.js>，还是打不开。然后看到有 [配置](https://github.com/eggjs/examples/blob/master/assets-with-umi/config/config.default.js)，我把 http://127.0.0.1:8000 改成 ip+8000，也没啥用

问题就是，这个 demo 怎么改能在移动端打开？还是不支持呢？

谢谢

**Comment by xiaohuoni** [comment]
@okoala hi man

**Comment by okoala** [comment]
@hanzichi 你可以使用 8000 端口在移动端调试。步骤：

1. 调整 config.defaut.js，删除 SOCKET_SERVER 和 PUBLIC_PATH 配置
2. `ifconfig en0|awk '/inet /{print $2}'` 找出当前 IP

然后通过  ip:8000 来访问应用

**Comment by hanzichi** [comment]
@okoala  你好，这样做，demo 确实是可以运行的，但是 ip:8000 启动的只是前端应用吧？实际上还需要后端的 egg 服务，而且 [index.html](https://github.com/eggjs/examples/blob/master/assets-with-umi/app/view/index.html) 也还是需要的，会在该 html 中注入一些别的东西供页面调用

**Comment by hanzichi** [comment]
我的理解，页面中会注入 127.0.0.1:8000/umi.js  的文件，但是移动端打开的话这个请求代理不过去，所以目前这种架构方式做不到移动端打开，不知道理解有没有误

**Comment by sorrycc** [comment]
没理解移动端和 PC 端有何区别？请求为何要代理？不是直接请求的前端 server 的端口么？

**Comment by hanzichi** [comment]
@sorrycc 云大好。项目用的是 egg+umi，用的 [这个 demo](https://github.com/eggjs/examples/tree/master/assets-with-umi) 当作脚手架扩展开来的，并不是一个单纯的用的 umi 的 SPA。所以项目起的端口是 egg 的 7001，但是 egg-view-assets 引用的 html 文件中的地址是 localhost:8000/umi.js 的形式，mobile 上打不开 

简单地说就是如何在移动端打开 https://github.com/eggjs/examples/tree/master/assets-with-umi

@okoala  的方法只是打开了前端页面，后端环境还是需要的

所以，感觉这个 issue 可能应该提到 egg 去，感觉是 egg-view-assets 集成 umi 的问题

**Comment by sorrycc** [comment]
localhost:8000/umi.js 打不开，可以找找地方改成 `ip:8000/umi.js`。

**Comment by hanzichi** [comment]
@sorrycc  试过，不行，一直提示 disconnet from the devServer, try to reconnet，然后一直刷新

**Comment by sorrycc** [comment]
> disconnet from the devServer, try to reconnet

报这个错误是因为 socket server 不对，额外配置下 SOCKET_SERVER 就好了。

**Comment by hanzichi** [comment]
@sorrycc SOCKET_SERVER  是配置成本地 pc ip 么？试了下不行 

HMR=none 是在 `devServer` 下配置么？试了下也不行 ..

**Comment by sorrycc** [comment]
都是环境变量。
