### ISSUE TITLE
访问根目录地址时报TypeError: reactRouter.Router.computeRootMatch is not a function

### ISSUE THREAD

**Issue by missjing** [umijs/umi#1754]
bigfish工程，访问  http://localhost:8001/  时直接抛错了

![image](https://user-images.githubusercontent.com/2724034/50636222-4216ab80-0f90-11e9-8197-481547b78f8b.png)

查了下网上的说法是，react-router-config 4.4应与react-router4.4来匹配使用
https://github.com/ReactTraining/react-router/issues/6492

看umi-build-dev里的确是版本不匹配的，https://github.com/umijs/umi/blob/master/packages/umi-build-dev/package.json#L46

**Comment by sorrycc** [comment]
给可复现的仓库？

**Comment by missjing** [comment]
> 给可复现的仓库？

http://gitlab.alipay-inc.com/wealthprod/fund-research

我也去问下bigfish的同学

**Comment by sorrycc** [comment]
重现了，配置了 exportStatic，没有 layout，没有 `/` 路由时会报这个错。

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/57679061-0934c480-765d-11e9-9d44-09c9d122237a.png)


UC 下重现了
