### ISSUE TITLE
router push时提示组件未定义

### ISSUE THREAD

**Issue by baifernlover** [umijs/umi#1755]
我想用state路由传参，当这样定义时  
var path = {
      pathname:"/mycustomer/customerdetail?dd_stick=true",
      state:rowData,
    }
    router.push(path);
会报
![image](https://user-images.githubusercontent.com/5907268/50669917-1c76ba00-1003-11e9-853c-eb77b5b6cf2e.png)

当采用下面的方式定义时，就没有问题了
var path = {
      pathname:"/mycustomer/customerdetail",
      state:rowData,
    }
    router.push(path);

**Comment by sorrycc** [comment]
pathname 不能包含 query，query 用 query 属性传。比如

```js
router.push({
  pathname: '/mycustomer/customerdetail',
  query: { dd_stick: true },
  state: rowData
});
```
