### ISSUE TITLE
能不能build时，输入参数？例如build时候，传入base和public路径。

### ISSUE THREAD

**Issue by JevonYang** [umijs/umi#1756]
能不能build时，输入参数？例如build时候，传入base和publicPath路径。

**Comment by imhele** [comment]
`umi config set publicPath /`

**Comment by JevonYang** [comment]
> `umi config set publicPath /`

比如说，我是同一套代码，但是要部署两套环境，但是现在通过baseUrl区分（比如ip:80/dev和ip:80/uat）,通过nginx来配置实现？具体是怎么配置？

**Comment by imhele** [comment]
你可以这样设置 script
```json
{
  "build:dev": "umi config set base /dev/ && umi config set outputPath ./dist/dev && umi build",
  "build:uat": "umi config set base /uat/ && umi config set outputPath ./dist/uat && umi build",
  "build": "yarn build:dev && yarn build:uat"
}
```
关于 `nginx` 配置，可以参考 [AntD Pro 文档](https://pro.ant.design/docs/deploy#use-nginx)

**Comment by JevonYang** [comment]
> > 你可以这样设置 script
> > ```json
> > {
> >   "build:dev": "umi config set base /dev/ && umi config set outputPath ./dist/dev && umi build",
> >   "build:uat": "umi config set base /uat/ && umi config set outputPath ./dist/uat && umi build",
> >   "build": "yarn build:dev && yarn build:uat"
> > }
> > ```
> > 
> > 
> > 关于 `nginx` 配置，可以参考 [AntD Pro 文档](https://pro.ant.design/docs/deploy#use-nginx)
> > 只需要把 `location / {}` 这部分再 copy 一份，分别配上 `location /dev {}` 和 `location /uat {}` ，再改一下 `try_files` 指向的静态文件路径即可。
> 
> 谢谢，我去试试

没有问题，解决需求，感谢！

**Comment by ldwonday** [comment]
这个参数不行了吗？？？？
![image](https://user-images.githubusercontent.com/4630157/164204418-9bebf008-2e42-4725-bf88-f807a377ec5a.png)
