### ISSUE TITLE
define中设置process.env.NODE_ENV不起作用

### ISSUE THREAD

**Issue by zhangyanan0525** [umijs/umi#1757]
### 我的项目分3个环境：
开发：development,
生产线：production,
测试线：test

### 我的问题：
1.process.env.NODE_ENV只能是development或production吗？
2.我需要用UMI_ENV来代替process.env.NODE_ENV吗？
![image](https://user-images.githubusercontent.com/20139082/50686372-237be780-1058-11e9-9d30-6492ac8bc704.png)

### 以下是我的代码截图：
![image](https://user-images.githubusercontent.com/20139082/50685936-473e2e00-1056-11e9-8359-56ae1bc96340.png)

**Comment by sorrycc** [comment]
`process.env.NODE_ENV` 是写死的，dev 时为 `development`，build 时为 `production`。

**Comment by coldice945** [comment]
@sorrycc 只解释了原因，没说解决方法。
如果想改变 process.env.NODE_ENV，在 package.json 里的 script 里设置。比如上面的例子
```
"build:test": "cross-env NODE_ENV=test umi build",
```

**Comment by amundsen-roald** [comment]
因为umi默认NODE_ENV是写死的，只有两个值。@coldice945的方案是对的。

**Comment by andyliu-417** [comment]
> @sorrycc 只解释了原因，没说解决方法。
> 如果想改变 process.env.NODE_ENV，在 package.json 里的 script 里设置。比如上面的例子
> 
> ```
> "build:test": "cross-env UMI_ENV=test umi build",
> ```
> 
> ![files](https://user-images.githubusercontent.com/18394852/71151941-042d9880-2270-11ea-9128-6298fc2cfc8c.png)
> 
> ```
> export default {
>   define: {
>     //  添加下面的环境变量
>     "process.env.UMI_ENV": process.env.UMI_ENV,
>   },
> }
> ```
> 
> 在页面中使用环境变量的时候
> 
> ```
> console.log(process.env.UMI_ENV);
> ```

umi3中，UMI_ENV也已经被占用。
需要再换一个常量名字。
define里的定义没有必要。
