### ISSUE TITLE
选择ant design pro创建项目，自动路由不起作用

### ISSUE THREAD

**Issue by zhihelive** [umijs/umi#1758]
问题1：
选择ant design pro创建项目，类似next.js的自动路由不起作用。比如在pages下创建about.js或about/index.js，然后访问/about，显示403，这算bug吗

问题2：
通过umi block add 添加的区块都会显示在导航栏，但其实有些像UserLogin、UserRegister、ResultSuccess等等这样的区块不应该出现在导航栏。是否有什么配置可以避免这一点？
而且像UserLogin、UserRegister是被添加在内页里面的，并非单独的一个页面或布局。

问题3：
通过umi block add 添加的区块都是添加在pages下的一级目录，并且作为一级页面。但有些区块可能是二级，或者三级的，这无法添加。

很多东西文档都没说清楚，求解。

**Comment by xiaohuoni** [comment]
问题1:pro使用的是配置式路由，在项目中做了权限判断，不在配置中的，都会被重定向到403.

**Comment by xiaohuoni** [comment]
@yutingzhao1991 剩下的和block相关的问题，等这个小哥哥，有空的时候，看看吧

**Comment by zhihelive** [comment]
也就是说通过ant design pro创建的项目是不支持自动路由的，都需要手动配置，是这样吗？

**Comment by sorrycc** [comment]
是的，ant design pro 本身选的是配置式路由。
