### ISSUE TITLE
关于Use umi with dva中model的问题。

### ISSUE THREAD

**Issue by fenghome** [umijs/umi#1761]
umijs指南中说：model 分两类，一是全局 model，二是页面 model。全局 model 存于 /src/models/ 目录，所有页面都可引用；页面 model 不能被其他页面所引用。可是我测试在page目录下的页面model可以被其他页面引用啊？

**Comment by sciice** [comment]
开发模式下可以

**Comment by xiaohuoni** [comment]
开发模式的时候，page下的model也会被全量引入。发布的话，不实用按需加载的话，其实也可以跨页面使用，只是容易出错所有说页面 model 不能被其他页面所引用。
