### ISSUE TITLE
在 .umirc.js 中添加 routes后，yarn start 报错

### ISSUE THREAD

**Issue by yizhiyuyou** [umijs/umi#1771]
1.yarn create umi
2.到相应目录 yarn
3.在 .umirc.js 中添加 routes
![_20190107192129](https://user-images.githubusercontent.com/46235748/50765638-7a302e00-12b1-11e9-9b8b-1b63a7e91fed.png)
4.yarn start 
随后就报错了。
![_20190107191601](https://user-images.githubusercontent.com/46235748/50765424-cf1f7480-12b0-11e9-9436-f7b9e45c83ac.png)

可复现[仓库](https://github.com/jiaming743/umiBugRecurrent)

Your OS: Windows 10
Node.js version: 10.12.0

**Comment by sorrycc** [comment]
已修复，等下个版本更新，或者删除[这个配置](https://github.com/jiaming743/umiBugRecurrent/blob/master/.umirc.js#L13)。
