### ISSUE TITLE
runtime里面需要获取是否开启了按需加载，和设置的loading页面

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#1775]
需要在patchRoutes中，获取
```js
 dynamicImport: {
        loadingComponent: './components/PageLoading/index',
      },
```
不知道怎么获取，不然开启按需加载，动态添加路由就没有按需加载的功能了

**Comment by sorrycc** [comment]
需求是什么？为什么要在运行时知道这一点？

**Comment by xiaohuoni** [comment]
pro的一个方案测试---直接从服务端获取routes
你可以看一下这个分支 https://github.com/ant-design/ant-design-pro/tree/runtime-routes
如果用户开启了按需加载，理论上从服务端获取了路由，应该保留按需加载。
其他的问题我发在了 https://github.com/ant-design/ant-design-pro/pull/3317
老大都帮忙看一看

**Comment by sorrycc** [comment]
patchRoutes 是运行时，取不到编译时的变量的。
