### ISSUE TITLE
clone ant design pro 还是 create umi

### ISSUE THREAD

**Issue by speed1speed1** [umijs/umi#1776]
现在如果要使用 ant design pro 究竟是要 直接 git clone ant design pro 还是要 create umi 再透过 Block 加载 ant design pro 哪个比较建议呢

因为我发现 umi 这边是不会跟着 ant design pro 更新样板的
所以有可能 ant design pro更新了 可是 umi 的 template 还是旧的
这样我就必须回去 ant design pro 那裡查

另外 git clone ant design pro 的情况下就无法使用 umi block 了
这个未来会统一成都是採用 block 方式加载吗

**Comment by yutingzhao1991** [comment]
目前 pro 官方应该是 `git clone ant design pro` 这个方案，后续 `create umi 再透过 Block 加载 ant design pro` 这个会作为新的官方方案。

后面 umi 那边的区块会回头过来放到 pro 中作为 v4 版本来维护，也会持续更新。

umi block 任何 umi 的项目都可以用，哪怕你是 clone 的现在 pro master 上的代码。

**Comment by yutingzhao1991** [comment]
可以参考 https://www.yuque.com/ant-design/ant-design-pro/lmgc46

**Comment by speed1speed1** [comment]
Thanks.
Close this issue.
