### ISSUE TITLE
public下的文件，打包时被拷贝，但是没有作用？

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#1779]
```js
import styles from './index.css';
import config from '../../public/config.json'

export default function() {
  return (
    <div className={styles.normal}>
      <div className={styles.welcome} />
      <ul className={styles.list}>
        <li>To get started, edit <code>{config.api_url}</code> and save to reload.</li>
        <li><a href="https://umijs.org/guide/getting-started.html">Getting Started</a></li>
      </ul>
    </div>
  );
}
```
这里引用了config文件，build的时候，也被复制到了dist目录下。
但是修改它，页面无效。
是不是，在引用的时候，已经拷贝了一份打包进去了。
那放在大文件放在public目录下，好想失去了意义？
[configapp.zip](https://github.com/umijs/umi/files/2736299/configapp.zip)
重现步骤：修改config.json，部署无效
希望：可以有效，就能轻松实现，在编译后修改配置了。

**Comment by sorrycc** [comment]
config.json 的内容在 build 之后是打包在 umi.js 里的，dist/config.json 这个文件没有用。要在构建之后的配置，可以在 html 里做，或者搞一个 js 文件，在所有的 html 里引用他。

**Comment by xiaohuoni** [comment]
老大，那设计public目录的用途是啥？

**Comment by yutingzhao1991** [comment]
public 是存放静态资源的，你如果想要 config.json 能够修改后生效的话，应该是在页面中异步的去加载它，这样每次都是会拉去到最新的内容。你现在这样的话 config.json 是被打包到 js 中的，发布了就不会再更新。

**Comment by xiaohuoni** [comment]
那这里的静态资源其实只适用于一种情况。
那就是在模版文件html里面直接使用，而不通过webpack编译的内容。
与我原先预想的不同，那我看过好几个项目，在这里存放了，省市区数据（一个大约2M的数据包），然后再项目中使用它，我还一直以为是合理的！😓

**Comment by felix9ia** [comment]
> config.json 的内容在 build 之后是打包在 umi.js 里的，dist/config.json 这个文件没有用。要在构建之后的配置，可以在 html 里做，或者搞一个 js 文件，在所有的 html 里引用他。

既然public目录来的类似config.json静态文件都被打包到了umi.js当中，
问题①： 那为啥build打包时还要把public目录下的文件复制到dist目录下？
问题②：如何配置能够不让这些public的文件复制到dist目录下？手动删除？

@sorrycc @yutingzhao1991

**Comment by D-KaiDi** [comment]
我目前也遇到了同样的问题，项目上需要在public下面提供一个可配置的js文件，但是打包后发现已经被打包进umi.js了。没有办法动态配置我想要的参数了。只能按照 @sorrycc 大佬提供的方法在HTML中再异步加载一遍吗？
