### ISSUE TITLE
我在做umi+dva+cesium的demo,有些问题

### ISSUE THREAD

**Issue by ch-liuzhide** [umijs/umi#1793]
[先贴上cesium,不了解的可以去看看，简单来说就是基于webgl的三维球]
官网：https://cesiumjs.org/
实例沙盒：https://cesiumjs.org/Cesium/Apps/Sandcastle/

**那么问题来了**
1. 和umi的兼容
官方推荐了webpack教程
https://cesiumjs.org/tutorials/cesium-and-webpack/

磕磕碰碰搞了3个晚上，愣是搞不定，原因归结为我对umi封装的webpack不会用，以及我是菜鸟。

**我把它搞到git上去了** https://github.com/ch-liuzhide/cesium-umi-dva.git** 在branch-v0.1
希望大佬帮我看下配置，指导下😘

快速看我代码里的配置文件
config/config.js
`// https://umijs.org/config/
// https://umijs.org/zh/plugin/umi-plugin-react.html#pwa
import webpackPlugin from './plugin.config';
var path = require('path');
const plugins = [
  ['umi-plugin-react', {
    antd: true,
    dva: true,
    dynamicImport: true,
    title: 'cesiumtest',
    dll: false,
    hardSource: true,
    routes: {
      exclude: [
        /components/,
      ],
    },
  }],
];

export default {
  // add for transfer to umi
  plugins,
  publicPath:"/",
  chainWebpack: webpackPlugin,
};
`

config/plugin.config.js  (最不了解的就是这个文件，没办法和官方推荐的webpack统一，又不写和umi冗余的配置)

`const cesiumSource = 'node_modules/cesium/Source';
const cesiumWorkers = '../Build/Cesium/Workers';
const CopywebpackPlugin = require('copy-webpack-plugin');
const path = require('path');
const webpack = require('webpack');

export default config => {
  config.merge({
    plugins: [
      // new HtmlWebpackPlugin({
      //   template: 'src/index.html'
      // }),
      // Copy Cesium Assets, Widgets, and Workers to a static directory
      new CopywebpackPlugin([ { from: path.join(cesiumSource, cesiumWorkers), to: 'Workers' } ]),
      new CopywebpackPlugin([ { from: path.join(cesiumSource, 'Assets'), to: 'Assets' } ]),
      new CopywebpackPlugin([ { from: path.join(cesiumSource, 'Widgets'), to: 'Widgets' } ]),
      new webpack.DefinePlugin({
        // Define relative base path in cesium for loading assets
        CESIUM_BASE_URL: JSON.stringify('')
      })
    ],
  });
//感觉这些和umi重复了或者不该在这里配置
  // config
  //   .entry('app')
  //   .add('src/layouts/index.js')
  //   .end()
  //   .output
  //   .path('dist')
  //   .filename('[name].bundle.js')
  //   .sourcePrefix(' ')
  //   .end()
  //   .amd({
  //     // Enable webpack-friendly use of require in Cesium
  //     toUrlUndefined: true,
  //   })
  //   .end()
  config.resolve.alias
    .set('cesium', cesiumSource)
  //
  // config.module
  //   .rule('style')
  //   .test(/\.css$/)
  //   .use(['style-loader', 'css-loader'])
  //   .loader(['style-loader', 'css-loader'])
  //   .end();
  //
  // config.module
  //   .rule('url-loader')
  //   .test(/\.(png|gif|jpg|jpeg|svg|xml|json)$/)
  //   .use('url-loader')
  //   .loader('url-loader')
  //   .end();
};
`

现状：我能npm run start 成功，但是在页面引入cssium时
`import styles from './index.css';
import React from 'react';
var Cesium = require('cesium/Cesium');
require('cesium/Widgets/widgets.css');`

报错找不到cesium,猜测是alias没有配置正确

@sorrycc @all-passer-by

**Comment by sorrycc** [comment]
webpack 配置参考 https://umijs.org/zh/config/#chainwebpack ，cesium 的问题不是 umi 的边界，是 webpack 的配置方式问题，请自己查阅文档解决。
