### ISSUE TITLE
约定式路由是不是应该默认屏蔽.test.js

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#1794]
```js
routes:{
        exclude:[/\.test\.(j|t)sx?$/]
      },
```
pages目录下的.test文件是不是应该默认不被解析成路由？
![image](https://user-images.githubusercontent.com/11746742/50946757-d4a9d400-14d5-11e9-89bf-6c8ad9cecde9.png)

**Comment by afc163** [comment]
`.spec.js` too.
