### ISSUE TITLE
项目部署到非根路径，webservice-worker.js路径错误

### ISSUE THREAD

**Issue by iceberg211** [umijs/umi#1795]

**Comment by iceberg211** [comment]
congfig配置如下： ` { manifest: {
    basePath: '/web/',
  },
  base: '/web',
  publicPath: "/web/"}`

可是在请求的时候，webservice-worker.js请求路径为跟路径

**Comment by sorrycc** [comment]
@xiaoiver

**Comment by xiaoiver** [comment]
@iceberg211 ，我自己测试了一下，应该是你的 `base` 需要改成 `/web/`。在注册 ServiceWorker 拼接路径时会用到，在你的例子中就会是 `/web/service-worker`：
<img width="688" alt="2019-01-11 5 53 31" src="https://user-images.githubusercontent.com/3608471/51026633-e9679400-15c9-11e9-9815-99ad6919be44.png">

这是我的配置：
```javascript
export default {
  base: '/dist/',
  publicPath: '/dist/',
  plugins: [
    ['umi-plugin-react', {
      pwa: {
        manifestOptions: {
          srcPath: path.join('src', 'manifest.json')
        },
        workboxPluginMode: 'InjectManifest',
        workboxOptions: {
          importWorkboxFrom: 'local',
          swSrc: path.join('src', 'sw.js'),
          swDest: 'my-dest-sw.js',
        }
      },
    }],
```

**Comment by rannawang** [comment]
遇到差不多的问题，试了上面的方法，还是不成功，直接从域名下面去加载service-worker.js，而不是从下面文件夹下面去加载这个文件，导致文件找不到
