### ISSUE TITLE
最新版的umi脚手架构建项目, 以下这几个样板可以分别介绍以下吗 ?  除了ant-design-pro知道是什么意思外, 其他的都代表啥 ?

### ISSUE THREAD

**Issue by mofengfs** [umijs/umi#1796]
![image](https://user-images.githubusercontent.com/16655229/50953887-bd77e000-14ef-11e9-8440-ca1e9667d75f.png)

**Comment by xiaohuoni** [comment]
这个在脚手架里提问会好些https://github.com/umijs/create-umi/issues/24
