### ISSUE TITLE
umi微前端方案

### ISSUE THREAD

**Issue by linyuliang** [umijs/umi#1797]
请问，umi能支持微前端么？例如使用single-spa实现微前端。

**Comment by xiaohuoni** [comment]
你指的是它吗https://github.com/umijs/umi-example-monorepo

**Comment by linyuliang** [comment]
看说明，是的，我现在是用ant design pro开发，前端想拆分出子系统模块，按需加载
[https://github.com/umijs/umi-example-monorepo](https://github.com/umijs/umi-example-monorepo) 这个库文档不是太完善呀，我先看下代码，看看是否能用起来

**Comment by xiaohuoni** [comment]
有问题，在reopen

**Comment by Fantasy9527** [comment]
@linyuliang 
如果你有需要,可以参照我的文章接入single-spa:
https://alili.tech/archive/9xuojm75d2a/

**Comment by linyuliang** [comment]
> @linyuliang
> 如果你有需要,可以参照我的文章接入single-spa:
> https://alili.tech/archive/9xuojm75d2a/

非常感谢：）
