### ISSUE TITLE
Umi + Typescript 使用mock 浏览器访问发生404

### ISSUE THREAD

**Issue by aijiacy** [umijs/umi#1798]
**环境版本：**
node: v10.15.0
npm: v6.4.1
umi: 2.3.2
umi-plugin-react: 1.3.2

**项目构建**
项目使用create-umi 创建的普通项目 增加 antd dva 
增加typescript支持，项目js文件全部转换为ts、tsx文件。

**发现问题**
mock 配置后，使用浏览器访问直接进入404开发页面。

**Comment by aijiacy** [comment]
https://github.com/aijiacy/umi-ts.git

**Comment by aijiacy** [comment]
> 给一个可复现的仓库？
https://github.com/aijiacy/umi-ts.git

**Comment by sorrycc** [comment]
mock 文件目前还不支持 ts 格式。

**Comment by aijiacy** [comment]
> mock 文件目前不支持 ts 格式。

好的，OK

**Comment by ye4241** [comment]
为啥的用了ts的是正常的？
引入了 mockjs+@types/mockjs后，直接用了user.ts。
然后，貌似一切正常。。。

```typescript
import { mock } from 'mockjs';

export default {
  'GET /api/users': { users: [1, 2] },
  // GET POST 可省略
  '/api/users/1': { id: 1 },
  'GET /api/tags': mock({
    'list|100': [{ name: '@city', 'value|1-100': 50, 'type|0-2': 1 }],
  }),
};
```

![image](https://user-images.githubusercontent.com/6803102/63747458-c8924b80-c8d9-11e9-950d-74b6f8f0248a.png)
