### ISSUE TITLE
能否手动控制 react 启动时间

### ISSUE THREAD

**Issue by skioll** [umijs/umi#180]
因部分需求，需要异步获取部分信息后才可展示页面，能否手动控制react启动时间

**Comment by sorrycc** [comment]
在 page component 里控制 render 返回的内容不能解决吗？

**Comment by skioll** [comment]
@sorrycc 那样的话需要每个page都添加，因为初始访问页面可能并非index

**Comment by sorrycc** [comment]
在 layouts/index.js 里处理呢？

**Comment by skioll** [comment]
这样是可以的  感谢
