### ISSUE TITLE
关于targets的ie11兼容

### ISSUE THREAD

**Issue by Veigar-C** [umijs/umi#1800]
项目：antd pro
环境：IE11
在targets中加了ie:11，登陆时报错如下（但是刷新页面居然进去首页了）：
对象不支持“remove”属性或方法
对象不支持“repeat”属性或方法

是没有做语法转换吗？
项目有remove的地方，第三方组件的都支持ie9+，
还有就是antd引入的less.min.js和data-set.js，但是好像去掉也报错，
主要登陆成功跳转时页面就空了，刷新后可以进入首页是可以正常使用的

**Comment by sorrycc** [comment]
remove 和 repeat 是什么方法？这些并不是 es 规范里的东西。

**Comment by sorrycc** [comment]
请提供可复现仓库。
