### ISSUE TITLE
oauth回调怎么处理?

### ISSUE THREAD

**Issue by ityao** [umijs/umi#1814]
在pro.ant.design的login那加上了微信扫一扫的扫码登录,
微信服务器端oauth回来的时候调用/api/web/oauth的路径,
但这个在浏览器中被from ServiceWorker接管了, 变成显示pro.ant.design的首页
应该怎么忽略掉这些路径让可以回调呢?

**Comment by sorrycc** [comment]
自己处理 `/api/web/oauth` 的请求就好了，和 umi 没啥关系。

**Comment by ityao** [comment]
有关系啊, 这个应该是在浏览器里面传回去给后端服务器接口解释那code的, 不是在pro.ant.design的前端页面处理的
