### ISSUE TITLE
umi.js中 展开运算符报错

### ISSUE THREAD

**Issue by 81777268** [umijs/umi#1820]
已经根据文档正确配置了 targets 并且浏览器版本低于配置项 却依然 报错；

![image](https://user-images.githubusercontent.com/26462331/51020338-3bec8480-15b9-11e9-9070-d3cfcf439d4f.png)

![image](https://user-images.githubusercontent.com/26462331/51020353-4870dd00-15b9-11e9-9770-ba5ca4800e92.png)

![image](https://user-images.githubusercontent.com/26462331/51020410-6a6a5f80-15b9-11e9-826d-614b91685ff0.png)

**Comment by sorrycc** [comment]
同一个问题不要新开 issue，在之前的 issue 里回复就好了。
