### ISSUE TITLE
global 样式失效

### ISSUE THREAD

**Issue by yyjazsf** [umijs/umi#1825]
和 #1002 不一样，引入某些插件后 umi.css 会丢失所有全局样式，并被引入的插件样式覆盖。多次遇到。

比如 `yarn add monaco-editor` 这个插件，引入后，生成的umi.css全部都是这个插件的样式，全局样式丢失。上次还有一个插件也是，忘了名字

**Comment by sorrycc** [comment]
给复现仓库。

**Comment by yyjazsf** [comment]
@sorrycc [链接](https://github.com/yyjazsf/umi-issue-demo) 
如果config 里面没有 仓库里面的 plugins就正常（umi.css 上面是插件样式，下面是全局样式，不太合理），我后来加了 plugins 就和我描述的一致

**Comment by yyjazsf** [comment]
试了一下去掉dll 就ok了

**Comment by noyobo** [comment]
楼主已提供复现仓库，是否可以看下？同样遇到该问题，关闭 dll 后正常。 @sorrycc
