### ISSUE TITLE
Can umi support "debugger for chrome " in VSCode?

### ISSUE THREAD

**Issue by kala888** [umijs/umi#1827]
step1, with default configuration
```
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```

step2, start
![image](https://user-images.githubusercontent.com/1215976/51081227-b89c7180-1725-11e9-9fa3-a73b71616991.png)

step3, view page in chrome, got 404
(the path works fine when start the service with "yarn start")
![image](https://user-images.githubusercontent.com/1215976/51081234-f8fbef80-1725-11e9-9c05-3aa244f9bfb4.png)

**Comment by kala888** [comment]
@sorrycc 哦，那个是端口冲突了。。。我再测试，用8000端口，
VScode配置, 似乎没有把umi启动起来。
```
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8000",
            "webRoot": "${workspaceFolder}"
        }
    ]
}

```

**Comment by sorrycc** [comment]
这个应该算工具问题，我觉得还是从工具层找解决方案，或者能够明确说明需要 umi 做什么。

**Comment by logtaillu** [comment]
debugger for chrome本身不会启动项目的，
yarn start启动项目后，把configurations的url填成项目的url，再启动debugger；
但是umi的source-map和原始的代码不一样，vscode调试会行错位
![test2](https://user-images.githubusercontent.com/12798000/51246269-01258a80-19c5-11e9-9def-abd53e444dad.png)
