### ISSUE TITLE
能动态注册model吗? 访问当前页只挂载用到的， 不是一次性全部加载了

### ISSUE THREAD

**Issue by y2891663091** [umijs/umi#183]
项目用的 umi+antd+dva;
访问首页，发现pages目录下所有的model都已经注册挂载到state里面了。
能访问当前页只挂载当前页的model吗？ 因为项目很大，可能有几百上千个model

**Comment by 6691** [comment]
因为一次性加载的model 实在太多，我想 dev 模式下也可以动态加载model，不知道怎么处理？
我安装umi 下来默认版本是 "umi-plugin-dva": "^0.1.0"，有更高版本?

**Comment by sorrycc** [comment]
dev 模式下动态加载还不支持，下个版本吧。
