### ISSUE TITLE
多页面项目如何配置多个入口？不提供entry的配置吗？

### ISSUE THREAD

**Issue by chuiliu** [umijs/umi#1830]
项目需要有多个入口，之前在使用dva的时候，可以这样配置多入口，`"entry": "src/pages/*.js"`，umi不知道怎么实现。

**Comment by rendongsc** [comment]
基于我们实际项目情况，单页项目最大问题就是一个模块的升级需要整个重新打包整个系统。。
比较大的系统一个模块内按单页部署，多模块用多页部署是比较合理的架构。
umi怎么配置希望官方文档写一些具体示例。

**Comment by xiaohuoni** [comment]
@sorrycc entry这个不是不让配置的吗？

**Comment by sorrycc** [comment]
@rendongsc 你的情况是多个单页应用的组合？

**Comment by rendongsc** [comment]
@sorrycc 是多个单页应用的组合，模块路由在服务端实现的。
/app/app1(单页应用，n个页面，n个功能)
/app/app2(单页应用，n个页面，n个功能)
希望app1、app2可以独立打包。

**Comment by xiaohuoni** [comment]
@rendongsc https://github.com/umijs/umi-plugin-mpa/

**Comment by sorrycc** [comment]
@xiaohuoni 他的这个场景不适用于 umi-plugin-mpa。

**Comment by yutingzhao1991** [comment]
他这个应该是 monorepo 吧？

**Comment by USTCLX** [comment]
所以想问一下，一个大的系统，分了很多子系统，每个子系统是一个SPA，用UMI可以开发这样的一个大系统吗？还是说用UMI单独开发每一个子系统。那是不是有点儿浪费，每个子系统之间有很多公用的组件和module。请问大家一般是怎么处理这样的场景的？

**Comment by yutingzhao1991** [comment]
共用的组件和 model 肯定是要抽出来复用的，要么类似 https://github.com/umijs/umi-example-monorepo 这个放到一个仓库中，要么就是抽出来作为 npm 包。

**Comment by zemzheng** [comment]
> 所以想问一下，一个大的系统，分了很多子系统，每个子系统是一个SPA，用UMI可以开发这样的一个大系统吗？还是说用UMI单独开发每一个子系统。那是不是有点儿浪费，每个子系统之间有很多公用的组件和module。请问大家一般是怎么处理这样的场景的？

我这边最近刚处理这个问题，利用 chainWebpack 将公用代码的路径配置到 rule 里面去： https://blog.ziey.me/2019/05/17/multi-umi-project-common/

**Comment by LukerSpringtree** [comment]
> > 所以想问一下，一个大的系统，分了很多子系统，每个子系统是一个SPA，用UMI可以开发这样的一个大系统吗？还是说用UMI单独开发每一个子系统。那是不是有点儿浪费，每个子系统之间有很多公用的组件和module。请问大家一般是怎么处理这样的场景的？
> 
> 我这边最近刚处理这个问题，利用 chainWebpack 将公用代码的路径配置到 rule 里面去： https://blog.ziey.me/2019/05/17/multi-umi-project-common/

能提供一个github  的 rep 吗?

**Comment by liufeisprit** [comment]
设置UMI_ENV 比如设置UMI_ENV=prod 然后在配置不同的config.prod.js 可以设置不同的打包命令 配置不一样的打包方式

**Comment by warmhug** [comment]
https://github.com/umijs/umi-example-monorepo 这里提到的 “路由分包” 和 “component 分包” 都还能 work 吗？有没有更简单的方案支持呀？

**Comment by jiyingzhi** [comment]
这个问题解决了吗

**Comment by karrynew** [comment]
问题解决了吗

**Comment by karrynew** [comment]
> 这个问题解决了吗

你解决了吗

**Comment by pxim** [comment]
> dynamicImport



> 



> @sorrycc 是多个单页应用的组合，模块路由在服务端实现的。 /app/app1(单页应用，n个页面，n个功能) /app/app2(单页应用，n个页面，n个功能) 希望app1、app2可以独立打包。

这个问题你解决了没，umi3自带没有这个功能
