### ISSUE TITLE
umi dev 重新启动经常报错！急急急！！！

### ISSUE THREAD

**Issue by gjfsoft** [umijs/umi#1831]
重新用 umi dev 启动会经常报这个错误，一旦报错，图片就加载不出来，求助！！！

报错内容见图片：
<img width="977" alt="default" src="https://user-images.githubusercontent.com/46661313/51093904-032ff380-17e3-11e9-9676-51a8e254494f.png">

**Comment by sorrycc** [comment]
禁用 hardSource 。
