### ISSUE TITLE
Proxy代理无法保持session

### ISSUE THREAD

**Issue by zhoumh1988** [umijs/umi#1838]
### 获取验证码图片：
![image](https://user-images.githubusercontent.com/7434920/51103474-c7664f80-181d-11e9-9b24-b621abbaf139.png)

### 请求接口：
![image](https://user-images.githubusercontent.com/7434920/51103468-c0d7d800-181d-11e9-92a9-16dd2a09e7a6.png)

### 获取验证码图片：
![image](https://user-images.githubusercontent.com/7434920/51103523-fc72a200-181d-11e9-94ca-f08b4abd3a59.png)

### 请求接口：
![image](https://user-images.githubusercontent.com/7434920/51103533-098f9100-181e-11e9-9a1e-798db6be1588.png)

我的proxy设置如下
```js
{
  ...
  "proxy": {
    "/api": {
      "target": "http://{host}:{port}",
      "changeOrigin": true
    }
  },
  ...
}
```

**Comment by sorrycc** [comment]
试试直接用 webpack-dev-server 会不会有此问题？

**Comment by zhoumh1988** [comment]
？？？没解决为啥就把问题给关了？！

**Comment by Fea-Sin** [comment]
> 试试直接用 webpack-dev-server 会不会有此问题？

umi  如何配置 webpack-dev-server
在 umi start 中 --port=8080可以使用，--host=xxxx 无法生效
这个如何配置，大神求指示
