### ISSUE TITLE
引入外部模块monaco-editor报错

### ISSUE THREAD

**Issue by shepiguai** [umijs/umi#1842]
![_df0d4197-4864-41f7-b191-811cfebff944](https://user-images.githubusercontent.com/25193960/51153929-f4ae0e80-18ac-11e9-9d8f-fcd470043ac6.png)
error  in ./node_modules/monacoeditor/esm/vs/editor/standalone/browser/quickOpen/quickOutline.css
不知道怎么配置cssModulesExcludes

**Comment by yyjazsf** [comment]
monaco-editor 有个es引入教程，有个webpack插件

**Comment by shepiguai** [comment]
> monaco-editor 有个es引入教程，有个webpack插件

我引过那个插件了monaco-editor-webpack-plugin，还是报一样的问题

**Comment by yyjazsf** [comment]
https://github.com/yyjazsf/umi-issue-demo  你那这个仓库对比下？这个没这个问题，吧config 里面的plugins注释掉

**Comment by shepiguai** [comment]
> https://github.com/yyjazsf/umi-issue-demo 你那这个仓库对比下？这个没这个问题，吧config 里面的plugins注释掉

我是在ant design pro里面引入的monaco-editor，只要npm install monaco-editor，就会报这个错，这个plugin我也引了，和你config写的差不多

**Comment by sorrycc** [comment]
参考 https://github.com/yyjazsf/umi-issue-demo 解决吧，这个不是 umi 的范围了，或者能明确排查出哪里有 bug，然后提 issue umi 来改。
