### ISSUE TITLE
开启hashHistory后start出错，build出错

### ISSUE THREAD

**Issue by wsdqr001** [umijs/umi#1847]
因为业务需求，需要在生成环境开启base配置。但是部署后刷新页面出现404的情况，因为每刷新一次URL都会多一个base。为了解决这个问题，按照官网配置，开启了hashHistory选项。config.js和.umirc.js两种方式都尝试了，但是都会报错。报错信息如下：

PS 通过history: 'hash',刷新时路由仍然会自动变化。
比如：/atlas/#/ 会自动变成 /atlas/#/atlas/

@sorrycc 
![qq 20190115163359](https://user-images.githubusercontent.com/6917707/51168186-80db2880-18e3-11e9-903a-929c99434d2b.png)

**Comment by sciice** [comment]
`history: 'hash'`

**Comment by wsdqr001** [comment]
> `history: 'hash'`

谢谢，这个方法试了下，不会报错了，但是刷新页面仍然会改动URL。

**Comment by sorrycc** [comment]
刷新后手动访问 `/`。

**Comment by wsdqr001** [comment]
> 刷新后手动访问 `/`。

这个也是相当粗暴了额
