### ISSUE TITLE
打包css 跟js文件能打包到不同的文件夹吗？

### ISSUE THREAD

**Issue by jayguojianhai** [umijs/umi#1855]
目前所有的文件都在dist目录，需求是css文件在dist/css文件下，js文件在dist/js目录，可以支持吗？

**Comment by sorrycc** [comment]
你好，目前不支持。

**Comment by Gzbox** [comment]
@sorrycc   您好  目前这个需求  UMI支持了吗 ？
或者说我是否可以自己配置？
