### ISSUE TITLE
umi -v报错了

### ISSUE THREAD

**Issue by wulinjie122** [umijs/umi#1856]
```shell
$ umi -v
/bin/sh: /d/nodist/bin/bin/C:/Users/YM10195/AppData/Local/Yarn/Data/global/node_modules/.bin/umi: No such file or directory
```

**Comment by sorrycc** [comment]
晚上回去我试试 windows 。

**Comment by sorrycc** [comment]
@xiaohuoni 有 windows 机器可以试一下。

**Comment by wulinjie122** [comment]
环境，安装了最新版本nodist，安装路径D:\nodist，设置环境变量NODIST_PREFIX=D:\nodist\，添加Path %NODIST_PREFIX%\bin;%NODIST_PREFIX%\bin\bin，执行yarn global add umi，然后执行umi -v报错。

**Comment by wulinjie122** [comment]
之前是好好的，卸载了nodist之后，重新安装了nodist和yarn，就再也跑不起来了。

**Comment by wulinjie122** [comment]
```shell
C:\Windows\system32>umi -v
文件名、目录名或卷标语法不正确
```

**Comment by okoala** [comment]
windows 下用这个 https://github.com/coreybutler/nvm-windows ，应该会好点~

**Comment by wulinjie122** [comment]
> windows 下用这个 https://github.com/coreybutler/nvm-windows ，应该会好点~

感谢，这次好了，我已经卸载了nodist了，改用nvm一切正常了。
