### ISSUE TITLE
样式丢失

### ISSUE THREAD

**Issue by ypli0629** [umijs/umi#1859]
在 node_modules 下面有一个自己基于antd二次封装的组件，但是在页面上这个组件中的日期组件(antd中的组件)样式没了,已经通过 extraBabelIncludes 指定该包的路径，样式还是没有

**Comment by sorrycc** [comment]
node_modules 下的 css/less 文件不走 css modules 的，是不是这个原因？不是的话，给可复现仓库吧。

**Comment by dkvirus** [comment]
这问题我有遇到过，最终手动引入 antd.css 文件解决的，也就多了几十kb.
