### ISSUE TITLE
为什么刷新页面后变成 404？

### ISSUE THREAD

**Issue by 6691** [umijs/umi#186]
比如：我访问到 http://localhost:5000/admin 刷新一下或者直接输入，变404了

请问这个有解决方案吗？

**Comment by sorrycc** [comment]
dev 模式还是 build 之后？

**Comment by 6691** [comment]
dev 和 build 后都是这种情况?

**Comment by sorrycc** [comment]
dev 下我不能重现，build 之后是需要自己处理让服务端支持的。

**Comment by 6691** [comment]
是不是这个版本有问题？ 这是npm i umi -g下来的版本
{
  "scripts": {
    "start": "umi dev",
    "build": "umi build"
  },
  "dependencies": {
    "umi": "^1.0.0-0",
    "umi-plugin-dva": "^0.1.0"
  },
  "devDependencies": {
    "query-string": "^5.1.0"
  }
}

**Comment by leo-joy** [comment]
dev 下我不能重现，build 之后是需要自己处理让服务端支持的。

大神你好！build之后刷新404问题，自己在服务端如何处理？ 我部署在docker的nginx容器中的

**Comment by leo-joy** [comment]
* 改用 hashHistory，在 `.umirc.js` 里配 `hashHistory: true` 
此方案解决我的问题！

**Comment by xiaohuoni** [comment]
```js
这里有几个方案供选择：

* 改用 hashHistory，在 `.umirc.js` 里配 `hashHistory: true`
* 静态化，在 `.umirc.js` 里配 `exportStatic: true`
* 服务端配置路由 fallback 到 index.html
```
更多开发常见错误，可以查看 #246

**Comment by imaxing** [comment]
@leo-joy 请问你是如何配置的?我配置了编译不允许
![image](https://user-images.githubusercontent.com/26427785/63826983-fb991580-c993-11e9-9b49-c97877c91974.png)
