### ISSUE TITLE
jest 单元测试中涉及到 Link及router时报错

### ISSUE THREAD

**Issue by realeve** [umijs/umi#1862]
## 问题描述
用jest单元测试时，如果被测试的文件中涉及到  link 及router时将报错，具体内容如下：

## 版本
 umi@2.4.3

## 现象
![image](https://user-images.githubusercontent.com/448208/51289913-0e7e5b80-1a3d-11e9-82fc-9261fb78e2de.png)

### 1. /umi/router
将对应目录router.js中的内容拷贝一份重新引用，测试通过：
```js  
// router.js
/* global window */

export function push(...args) {
  window.g_history.push(...args);
}

export function replace(...args) {
  window.g_history.replace(...args);
}

export function go(...args) {
  window.g_history.go(...args);
}

export function goBack(...args) {
  window.g_history.goBack(...args);
}

export function goForward(...args) {
  window.g_history.goForward(...args);
}

export default {
  push,
  replace,
  go,
  goBack,
  goForward,
};

```

```js
// import router from 'umi/router'; -- 这样会报错
import router from '@/utils/router'; // 复制的文件有效
```

## 2. Link组件也是如此

```js
// 使用umi提供的link测试报错，报错原因与router类似
import { Link } from 'umi/link';

// 使用源码中导入的 react-router-dom时测试通过
import { Link } from 'react-router-dom';
```

**Comment by yuquanwang** [comment]
遇到类似问题，运行jest测试报错：Cannot find module 'umi/router' from ...

**Comment by realeve** [comment]
@yuquanwang 用 umi test就不用添加这些

**Comment by sorrycc** [comment]
用 `umi test`，已处理这些 alias 。

**Comment by realeve** [comment]
@sorrycc 成哥，还是这样的，umi@2.5.5  用的是    umi test ./src/xxxx.test.js  

![1](https://user-images.githubusercontent.com/448208/53346230-923b3a00-3951-11e9-9442-18169f2c0c85.png)

**Comment by sorrycc** [comment]
看起来好想是 windows 下才会有，我找台 windows 验证下。

**Comment by duuliy** [comment]
2.1.2也是这样的

**Comment by sorrycc** [comment]
@duuliy 你也是 windows？

**Comment by eruca** [comment]
@sorrycc macOs也是这样 #2076

![image](https://user-images.githubusercontent.com/5526344/54085067-51d9b400-4374-11e9-91ae-995ebc332281.png)
