### ISSUE TITLE
## umi dev 之后页面一直在不停地刷新怎么办？

### ISSUE THREAD

**Issue by sciice** [umijs/umi#1863]
## umi dev 之后页面一直在不停地刷新怎么办？

这是因为 html 和 umi.js 的端口不一致。

比如：

* html 在 7001 端口
* umi.js 在 8000 端口

然后你访问 html，并且在 html 里引用了 8000 端口的 umi.js，这样会导致 socket server 连接出错，触发了循环刷新问题。

### 解决

配置 SOCKET_SERVER 到 `umi dev` 所在端口，比如 `SOCKET_SERVER=8000 umi dev`。（windows 下是 set SOCKET_SERVER=8000&&umi dev`）

_Originally posted by @sorrycc in https://github.com/umijs/umi/issues/1421#issuecomment-437808422_

**Comment by xiekw2010** [comment]
新版本直接设置 port 不行了。应该这么设置 SOCKET_SERVER=http://localhost:8000 umi dev
