### ISSUE TITLE
dll 无法识别 @types/d3-scale

### ISSUE THREAD

**Issue by tolerance-go** [umijs/umi#1872]
```
This dependency was not found:

* @types/d3-scale in dll umi

To install it, you can run: npm install --save @types/d3-scale
```

我用的 yarn@1.12.1 安装的依赖，

如果在 dll.exclude 加入 ‘@types/d3-scale’ 通过 import 插件导入的 antd 样式全部丢失

help me。。。

**Comment by sorrycc** [comment]
@types/d3-scale 放在 devDependencies 里。

**Comment by tolerance-go** [comment]
@sorrycc 

我将 `@types/d3-scale` 加入到了 umi-plugin-react dll.exclude 里面，和 @babel/runtime 一样，但是上述错误。

之后将依赖放到了 devDependencies 里面，删除 lock 重新执行 yarn install 也报错了，此时我的 dll.exclude 为 `['@babel/runtime'],`

**Comment by hnsylitao** [comment]
@tolerance-go 我遇到了同样是的问题，请问下你解决了么。
开启dll 然后 antd babel-import-plugin 样式就有部分缺失了
