### ISSUE TITLE
.umirc.local.js没覆盖config.js的值

### ISSUE THREAD

**Issue by hanwenbo** [umijs/umi#1875]
umi文档提示：为简化说明，后续文档里只会出现 .umirc.js。.umirc.local.js 是本地的配置文件，不要提交到 git，所以通常需要配置到 .gitignore。如果存在，会和 .umirc.js 合并后再返回。
![image](https://user-images.githubusercontent.com/5869741/51438518-4fe66380-1ce8-11e9-98b8-6257324cab91.png)
我认为local会替换config.js的值

**Comment by sorrycc** [comment]
看源码是会做 merge，但 local 限定了 dev 时有效，https://github.com/umijs/umi/blob/c45b3a2e29f4362cd6318c119c14e755374604c7/packages/umi-build-dev/src/UserConfig.js#L195

**Comment by hanwenbo** [comment]
@sorrycc 好的 大佬，我改用了.umirc.js 和 .umirc.local.js 了，这样没任何问题  我就不用config了

**Comment by hankaibo** [comment]
@sorrycc 我现在的umi-builld-dev是1.8版本的，还是未生效。
工程是基于antd-pro的。
![Annotation 2019-04-25 114051](https://user-images.githubusercontent.com/5361465/56708364-02e2b500-674f-11e9-9e53-7207a5e42c32.jpg)
