### ISSUE TITLE
项目build后，js文件太大，1M左右

### ISSUE THREAD

**Issue by stoneWeb** [umijs/umi#1876]
项目build后，js文件太大，1M左右，是否有减小的方法？

**Comment by sorrycc** [comment]
执行 `ANALYZE=1 umi build` 分析下。

**Comment by cardsix** [comment]
@sorrycc 执行 ANALYZE=1 umi build 时提示ANALYZE不是内部或外部命令是怎么回事？umi版本2.3.4
