### ISSUE TITLE
在地址栏输入地址打开，每次路由都会被渲染执行2次

### ISSUE THREAD

**Issue by smithyj** [umijs/umi#188]
在地址栏输入地址打开，每次路由都会被渲染执行2次
项目地址：http://github.com/smithyj/umi.yangyj.com
![qq20180308-154758](https://user-images.githubusercontent.com/9820142/37139243-227b78b8-22e8-11e8-8564-c5f4a82501ab.png)

**Comment by sorrycc** [comment]
这会导致什么问题吗？

**Comment by smithyj** [comment]
在某些场景下可能会导致多次Modal弹窗

**Comment by sorrycc** [comment]
还没排查为啥会有两次 LOCATION_CHANGE，但第二次的 state 是没有变化的。render 重复执行在 react 是应该是正常的吧，modal 需要自行控制不多次弹出。
