### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot assign to read only property 'exports' of object '

### ISSUE THREAD

**Issue by terminalqo** [umijs/umi#1886]
errrr....Why submit a bug no need to follow special patterns now?

Anyway, when I delete node-modules folder, and re install them, run my project:

(It's normal before I delete node-modules )

![image](https://user-images.githubusercontent.com/20705423/51510365-c5147e80-1e37-11e9-8960-7e892349d748.png)

I search this error in google, not find right explanation :)

But I do get some idea, because of **babel 6 --> bable 7 ?**

Then I change `module.exports` to `export default`.

I hope can help someone~

**Comment by sorrycc** [comment]
Please provide a reproducible repository.

**Comment by weishijun14** [comment]
1. old umi version = 2.2.8;
2. yarn remove umi.
3. yarn add umi.
4. yarn start --> report error;
5. yarn remove umi --> yarn add --dev umi@2.2.8;
6. everything goes normal.

**Comment by sorrycc** [comment]
Please try the latest umi version first.
