### ISSUE TITLE
model 添加手动注册功能

### ISSUE THREAD

**Issue by dkvirus** [umijs/umi#1891]
@sorrycc 现在 model 是自动注册的，能否添加手动注册 model 的功能配置，实际业务有需求。

**Comment by sorrycc** [comment]
Try `window.g_app.model()`.

**Comment by dkvirus** [comment]
@sorrycc  大佬，测试了一波，有两个问题不太明白，请教一波：

### 1. `window.g_app.model()` 写在什么位置？

看官方文档第一次写在 `src/app.js` 文件中，打印发现 window 为 undefined。

第二次写在组件中 `src/pages/index.js`，由 index 跳转到 users 页面是没问题的，但刷新 users 页面，就会报错。

好奇到底写在 `window.g_app.model()` 写在什么位置比较合适？

```
// index.js
import Link from 'umi/link';
import styles from './index.css';

export default function() {
  console.log(window);
  console.log(window.g_app);

  window.g_app.model({
      namespace: 'user',

      state: {
          name: 'dk'
      },

      reducers: {

      },
  });

  return (
    <div className={styles.normal}>
      <Link to="/users">User</Link>
      <h1>Page index</h1>
    </div>
  );
}
```

### 2. 这样注册的 model 如何做动态加载？

这种方法时单独注册 model，怎么做到 model 随页面动态加载啊？

原生 dva 里按需加载是如下处理的，不清楚手动注册 model 如何能做到按需加载。

```
const routes = [
  {
    path: '/',
    component: () => xxx,
    models: () => xxx,
  },
  {
    path: '/users',
    component: () => xxx,
    models: () => xxx,
  }
]

// .......

{
  routes.map(({ path, ...dynamics }, key) => (
    <Route
      exact
      key={key}
      path={path}
      component={dynamic({ app, ...dynamics })}
    />
  ))
}
```

**Comment by dkvirus** [comment]
`window.g_app` 写的位置在 #1803 里找到了。

**Comment by dkvirus** [comment]
@sorrycc     

使用 `window.g_app.model()` 手动注册 model 怎么做到按需加载啊。我测试发现是一开始就注册了 model。

![image](https://user-images.githubusercontent.com/29170168/51588349-d08ea500-1f1e-11e9-80dd-3f6087f0c6c6.png)

我能想到的一种解决办法是避开手动注册 model，在 `.umrc.js` 中添加一个配置属性：`includePkg`，含义为自动处理 node_modules 里的依赖包里的页面和 model，就像处理 src/pages 一样，当然前提是依赖包也是用 umi 这一套，有 pages 目录。

最后，这个 issue 还没问完，怎么 reopen？

**Comment by shanzheng1991** [comment]
你好，楼主，请问你的问题解决了吗？
