### ISSUE TITLE
umi支持启动独立的mock服务吗？

### ISSUE THREAD

**Issue by zhongds** [umijs/umi#1894]
场景：测试环境可能是mock数据和部分真实的api请求并存

目前：打包后的代码运行，mock api就不能用了

需求：能否在现有的mock文件里启动一个mock服务？这样mock api就可以通过nginx代理到mock服务

**Comment by zhongds** [comment]
@sorrycc

**Comment by i5ting** [comment]
umi支持proxy的

**Comment by zhongds** [comment]
> umi支持proxy的

这只是webpack-dev-server的功能，，在测试环境一般是用nginx启动服务的吧

**Comment by sorrycc** [comment]
有想过做，但还没有实现。需要把 mock 中间件提出来，然后实现一个 umi-serve 。

**Comment by i5ting** [comment]
> 有想过做，但还没有实现。需要把 mock 中间件提出来，然后实现一个 umi-serve 。

1. 做成一个插件，直接在配置了配置
2. 插件里注册serve命令，umi serve。
3. 纯粹的cli

三合一也不错

**Comment by xiaohuoni** [comment]
可以自己简单的实现一个服务 https://github.com/xiaohuoni/antd-pro-server
