### ISSUE TITLE
关于umi block，有两个问题：1、引入block以后，如何删除？2、block和项目有什么严格的区分，如果是一个小的项目，可以怎么改造成block呢？

### ISSUE THREAD

**Issue by Symboler** [umijs/umi#1895]

**Comment by sorrycc** [comment]
> 1、引入block以后，如何删除？

目前还不支持 revert，之后会支持。我觉得目前可以用 git 进行 revert。

> 2、block和项目有什么严格的区分，如果是一个小的项目，可以怎么改造成block呢？

区别是 block 只有一个路由。
