### ISSUE TITLE
没有 index.js 时 hashHistory 有问题

### ISSUE THREAD

**Issue by 6691** [umijs/umi#190]
现在不支持吗？

**Comment by sorrycc** [comment]
.umirc.js 里配 `"hashHistory": true`

**Comment by 6691** [comment]
之前：http://localhost:8000/soft/base  这样可以访问

配置 hashHistory : true 

配置之后：http://localhost:8000/#/soft/base   这样访问不了

这样反而成功了
http://localhost:8000/soft/base#/soft/base

**Comment by sorrycc** [comment]
umi 什么版本？我在 examples/func-test 里试了下是可以的。

**Comment by 6691** [comment]
这是配置文件：
{
  "scripts": {
    "start": "umi dev",
    "build": "umi build"
  },
  "dependencies": {
    "ant-design-pro": "^1.1.0",
    "lodash": "^4.17.5",
    "lodash-decorators": "^4.5.0",
    "react-document-title": "^2.0.3",
    "umi": "^1.0.6",
    "umi-plugin-dva": "^0.3.0"
  },
  "devDependencies": {
    "enquire-js": "^0.1.2",
    "particles.js": "^2.0.0",
    "react-container-query": "^0.11.0"
  }
}

还需要配置 history 查件吗？？？？

**Comment by sorrycc** [comment]
配在 .umirc.js 里，不是 package.json。https://umijs.org/docs/zh-Hans/config-umi.html#hashhistory

**Comment by 6691** [comment]
这是 .umirc.js :
export default {
  plugins: ['umi-plugin-dva'],
  hashHistory:true
};
配置了后要这样才可以访问：http://localhost:8000/login#/login

**Comment by sorrycc** [comment]
打个包传上来，我看下。

**Comment by 6691** [comment]
源码 还是 buIld 后的？

**Comment by sorrycc** [comment]
源码。

**Comment by 6691** [comment]
https://github.com/6691/Test-umijs

**Comment by sorrycc** [comment]
试了下，是 bug，没有 index.js 时 hashHistory 有问题，你可以先新建一个 index.js 解决。

**Comment by sorrycc** [comment]
Fix via #433, and it will be included in next release.
