### ISSUE TITLE
新增prependHTMLScript，添加到umi之前, html尾部。

### ISSUE THREAD

**Issue by likun7981** [umijs/umi#1908]
![image](https://user-images.githubusercontent.com/13427467/51661410-c2f32100-1feb-11e9-90c9-3f990377004e.png)

目前用这种方式感觉很不靠谱。

**Comment by sorrycc** [comment]
用 https://umijs.org/zh/plugin/develop.html#addhtmlheadscript 把需要放在 umi.js 前的脚本加在 head 里？

**Comment by likun7981** [comment]
这个api看到了的， 但是感觉还是把script放到底部更好。

**Comment by Mooooom713** [comment]
@likun7981  May I know what font you are using? Thx~

**Comment by likun7981** [comment]
> @likun7981 May I know what font you are using? Thx~

`Operator Mono`

**Comment by xiaohuoni** [comment]
另外：新的 api 提供了这个方法 https://umijs.org/plugins/api#addhtmlscripts
