### ISSUE TITLE
如何配置cssmodule支持多个样式

### ISSUE THREAD

**Issue by areyouse7en** [umijs/umi#1911]
目前通过module一次调用多个样式只能通过 `className={[style.aaa, style.bbb].join(' ')}` 的方式，
能否支持配置cssModules，开启allowMultiple
https://github.com/gajus/react-css-modules#allowmultiple

**Comment by zaleGZL** [comment]
可以试试 classcat 包，个人感觉 classnames 体积大了些，classcat 只有300b
https://github.com/jorgebucaran/classcat
