### ISSUE TITLE
国际化问题

### ISSUE THREAD

**Issue by WangJM001** [umijs/umi#1914]
umi的国际化可以重后台获取后再初始化进去么，我们自己有个国际化的配置库，公司要统一管理国际化文件，有没有什么解法？

**Comment by yutingzhao1991** [comment]
不是很明白，需求描述可以再具体一点吗？是什么内容要从后台获取？

**Comment by WangJM001** [comment]
我们有个国际化的配置平台，是一个单独的项目。现在使用antd pro2想国际化信息来源于这个平台，antdpro通过接口访问配置平台获取国际化信息。
现在准备重写umi-plugin-locale插件，在插件中发送请求去后端获取国际化数据初始化，不知道这种方案是否可行，有没有什么更好的方案？谢谢

**Comment by Verten** [comment]
应该是多语言文件都是后台返回的，而不是直接build-in在项目里面的。我们之前的做法是，在Mount App之前，通过fetch去获取到多语言的配置，在来render 页面。所以应该思路也是差不多。

**Comment by onpaik** [comment]
一次性从后台获取所有的国际化数据吗

**Comment by onpaik** [comment]
看见需求，实现了一下，这个插件[umi-plugin-locale-paik](https://www.npmjs.com/package/umi-plugin-locale-paik)增加了远程获取数据的功能，看是否是你需要的，一次向全量获取数据也是可以的，只需要在根组件请求一下，子代都会有国际化信息
最新`3.1.4`版本哦，欢迎 star
