### ISSUE TITLE
在引用less文件后，怎么支持直接写className='top' 这种格式不用去写 className={styles.top}

### ISSUE THREAD

**Issue by estn** [umijs/umi#1918]
问题：在一个组件里面引用了less文件后，如何直接在组件里面的className属性直接写样式的类名 不用在按照jsx的语法来写.  

如定义个top样式   

期望:直接写 className='top'， 而不用写className={styles.top}这种jsx语法

环境: umi  2.4.4  

![dcbdc179-a5c2-4efa-8536-033cd54b9902](https://user-images.githubusercontent.com/1539613/51747607-f8c80080-20e4-11e9-9c7c-c3a3602313df.png)

**Comment by i5ting** [comment]
用css modules的写法:global，直接写class就好了

**Comment by i5ting** [comment]
index.less

```
.welcome {
  height: 328px;
  background: url(../assets/yay.jpg) no-repeat center 0;
  background-size: 388px 328px;
}

:global {
  .red {
    background: red;
  }
}
```

在index.js里

```
import styles from './index.less';

export default function() {
  return (
    <div>
      <div class='red'>
        2233232
      </div>
      <div className={styles.welcome}>
    
      </div>
    </div>
  );
}
```

是可以混用的

**Comment by estn** [comment]
@i5ting  非常感谢~ 可以了

**Comment by Wangyage1** [comment]
:global {
  .red {
    background: red;
  }
}
这样子写的话，打包后的class还是'red', 而不是‘Header__red___1UdUE’， 请问如何解决呢

**Comment by DavidJiah** [comment]
less引入不生效  请问该怎么办  需要配置什么  less  less-load都下载了
