### ISSUE TITLE
请教一下，umi如何开启gzip压缩？有示例吗

### ISSUE THREAD

**Issue by cardsix** [umijs/umi#1922]

**Comment by afc163** [comment]
umi 是前端框架，不涉及服务端的功能。gzip 开启方式可以直接 Google。https://www.google.com/search?client=firefox-b-d&q=gzip+%E5%BC%80%E5%90%AF

**Comment by cardsix** [comment]
@afc163 再打扰一下，为什么我在运行ANALYZE=1 umi dev时提示ANALYZE不是内部命令，我是少安装什么东西了吗？

**Comment by Fuphoenixes** [comment]
修改.umirc.js文件即可
`
const CompressionPlugin = require("compression-webpack-plugin");

module.exports =  {
...
 chainWebpack: function (config) {
    if(process.env.NODE_ENV === 'production'){
      //gzip压缩
      config
        .plugin('compression-webpack-plugin')
        .use(CompressionPlugin, [{
          test:/\.js$|\.html$|\.css$/, //匹配文件名
          threshold: 10240,//对超过10k的数据压缩
          deleteOriginalAssets: false //不删除源文件
        }])
    }
  },
...

}
`

**Comment by Fuphoenixes** [comment]
> _No description provided._
修改.umirc.js文件即可
`
const CompressionPlugin = require("compression-webpack-plugin");

module.exports =  {
...
 chainWebpack: function (config) {
    if(process.env.NODE_ENV === 'production'){
      //gzip压缩
      config
        .plugin('compression-webpack-plugin')
        .use(CompressionPlugin, [{
          test:/\.js$|\.html$|\.css$/, //匹配文件名
          threshold: 10240,//对超过10k的数据压缩
          deleteOriginalAssets: false //不删除源文件
        }])
    }
  },
...

}
`
