### ISSUE TITLE
_mock.js 文件下不识别 @ 

### ISSUE THREAD

**Issue by dkvirus** [umijs/umi#1925]
### 问题

按如下目录结构写页面：

```
- src/
  - configs/
    - config.js
  - pages/
    - user/
      - index.js
      - model.js
      - _mock.js
```

在 `_mock.js` 文件中使用 `@/configs/config.js`，报错：

```
✖  error     Mock file parse failed
Cannot find module '@/configs/config.js'
```

issue 里翻到 `@` 默认指向 `src` 目录，我又在 `model.js` 里测试了 `@/configs/config.js`，发现是可以的，这说明 `@` 应该是可用的，只是没有对 `_mock.js` 做处理。

### 期望

`_mock.js` 中也可以使用 `@`。 

version umi  2.4.4

**Comment by sorrycc** [comment]
思路是调用 `@babel/register` 时通过 babel-plugin-module-resolver 处理别名，欢迎 PR 。

**Comment by dkvirus** [comment]
@i5ting  设置别名，减少使用相对路径，要不项目重构时文件挪个位置还得回头改路径？

**Comment by i5ting** [comment]
@dkvirus 要不要来个pr？

**Comment by dkvirus** [comment]
@i5ting 大佬，你要是方便提pr最nice啊🌹，我基础差，看源码估计搞的慢。（尴尬）
