### ISSUE TITLE
node.js版本10.15.0，create-umi没法新建项目

### ISSUE THREAD

**Issue by pufei007** [umijs/umi#1926]
The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.15.0"
![image](https://user-images.githubusercontent.com/25975239/51954511-6e342800-247b-11e9-9ec8-453262d55794.png)

**Comment by i5ting** [comment]
我在mac下测试是正常的。

```
➜  umi-node-10 node -v
v8.15.0
➜  umi-node-10 nvm use 10
Now using node v10.12.0 (npm v6.4.1)
➜  umi-node-10 yarn create umi
yarn create v1.12.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
```

经确认是upath版本问题

https://github.com/anodynos/upath/commit/8c5f4e10376ed1cd4553d9432297d39a34410c69#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

<img width="1427" alt="2019-01-30 10 52 50" src="https://user-images.githubusercontent.com/3118295/51955005-37f7a800-247d-11e9-914e-042710b9f71c.png">

查了一下源码

- chokidar依赖upath
- umi-tools\umi-build-dev\af-webpack依赖chokidar

解决办法，保证upath是v1.0.5+的版本就没有问题了 @sorrycc

**Comment by pufei007** [comment]
yarn版本1.13.0 @sorrycc

**Comment by sorrycc** [comment]
是你本地 yarn 环境的问题，安装任何全局包都会报错吧，我查了 create-umi 的依赖链里没有 upath 这个库的。
