### ISSUE TITLE
eslintignore失效

### ISSUE THREAD

**Issue by Kol96** [umijs/umi#1928]
想要屏蔽src/utils下的xxx.js文件，在项目根目录的.eslintignore设置如下
```
/src/utils/xxx.js
```
结果并没有起作用。

在antd-pro项目中也是如此。

**Comment by sorrycc** [comment]
这不是 umi 的问题，需要检查编辑器的配置吧。

**Comment by Kol96** [comment]
> 这不是 umi 的问题，需要检查编辑器的配置吧。

编辑器vscode没有报错
是执行umi dev时报错

**Comment by Kol96** [comment]
> 这不是 umi 的问题，需要检查编辑器的配置吧。

umi默认使用的af-webpack中eslint-loader是如下配置,eslintignore就不起作用了。需要外部用webpack-chain修改option
```
const eslintOptions = {
    formatter: eslintFormatter,
    baseConfig: {
      extends: [require.resolve('eslint-config-umi')],
    },
    ignore: false,
    eslintPath: require.resolve('eslint'),
    useEslintrc: false,
};
```

**Comment by zlyyyy** [comment]
同遇到这个问题。。。

**Comment by yerled** [comment]
@Kol96 我项目里面af-webpack/eslint-loader 是2.1.2版本的。文件里都没有你讲的这个配置啊，请问这该怎么改呢？

**Comment by yerled** [comment]
感谢！ @Kol96 
![image](https://user-images.githubusercontent.com/13483247/65034763-3df1b900-d97a-11e9-8d14-f2a6a266479a.png)
参考着在自己项目的config.chainWebpack里修改就真好使了

**Comment by wjw760306378** [comment]
> 感谢！ @Kol96
> ![image](https://user-images.githubusercontent.com/13483247/65034763-3df1b900-d97a-11e9-8d14-f2a6a266479a.png)
> 参考着在自己项目的config.chainWebpack里修改就真好使了

您好 请问我想忽略src下models文件夹下面的某个文件  我具体该怎么配置  我配置没有生效  可以参考一下您的配置嘛
