### ISSUE TITLE
router.config.js need a new option for always remounting Dynamic Route Component

### ISSUE THREAD

**Issue by ChieveiT** [umijs/umi#1930]
There is a very popular scenario if someone design a dynamic route with a `id` param and expect the route component remounted when `id` changed.

I think using `key` prop is a proper approach to force route component remounted, something like:

```
// router.config.js
{
  path: '/article/:id',
  pathAsKey: true,
  component: './Article/Detail',
}

// router
<ArticleDetail key={pathname} />
```

**Comment by sorrycc** [comment]
Does react-router support this feature?

**Comment by ChieveiT** [comment]
I'm not sure. There are some relevant issues such as [#5430](https://github.com/ReactTraining/react-router/pull/5430).

Personally, I think it is a feature about React Reconcilation. If <Route> from react-router respects `key` prop as expected, maybe we can simply add a `pathAsKey` option and generate `key={location.pathname}` for those `pathAsKey: true` routes. Call a `@connect((_, { location }) => ({ location }))` for Router listening to changes of  location is also needed.
