### ISSUE TITLE
node_modules下cssModule加载问题

### ISSUE THREAD

**Issue by leiysky** [umijs/umi#1931]
## 复现

```shell
$ git clone --depth=1 https://github.com/ant-design/ant-design-pro.git my-project
$ cd my-project
$ yarn add react-monaco-editor
$ yarn start
```
![image](https://user-images.githubusercontent.com/22445410/51975978-8bd6b100-24be-11e9-86cd-c8c575be45db.png)

结果如上图，可以看到一些样式有明显变化（比如说页面周围出现边框，a标签出现下划线等）

## 引申出的问题
根据 #1842 关闭`hardSource`，并无变化。

尝试通过`webpack-chain`来hack webpack配置，在`config/plugin.config.js`中加入如下代码：
```js
const MONACO_DIR = path.resolve(__dirname, '../node_modules/monaco-editor');

config.module
  .rule('css')
    .exclude.add(MONACO_DIR)
    .end();

config.module
  .rule('css-in-node_modules')
    .exclude.add(MONACO_DIR)
    .end();

config.module
    .rule('monaco-css-loader')
    .test(/\.css$/)
      .include.add(MONACO_DIR)
      .end()
    .use('css-hot-loader')
      .loader(path.resolve(__dirname, '../node_modules/css-hot-loader/index.js'))
      .options({
        reloadAll: true,
      })
      .end()
    .use('mini-css-extract-loader')
      .loader(path.resolve(__dirname, '../node_modules/mini-css-extract-plugin/dist/loader.js'))
      .options({
        publicPath: '/',
      })
      .end()
    .use('css-loader')
      .loader(path.resolve(__dirname, '../node_modules/af-webpack/node_modules/css-loader/dist/cjs.js'))
      .options({
        importLoaders: 1,
        sourceMap: true,
        modules: true,
        localIdentName: '[name]__[local]___[hash:base64:5]',
      })
      .end()
    .use('postcss-loader')
    // 该配置参考af-webpack中的postcss-options
      .loader(path.resolve(__dirname, '../node_modules/postcss-loader/src/index.js'))
      .options({
        ident: 'postcss',
        plugins: () => [
          require('postcss-flexbugs-fixes'), // eslint-disable-line
          autoprefixer({
            browsers: DEFAULT_BROWSERS,
            flexbox: 'no-2009',
          }),
          ...(process.env.NODE_ENV === 'development' ||
          process.env.CSS_COMPRESS === 'none' ||
          process.env.COMPRESS === 'none' ||
          process.env.NO_COMPRESS
            ? []
            : [
                require('cssnano')({
                  preset: [
                    'default',
                    {
                      mergeRules: false,
                      // ref: https://github.com/umijs/umi/issues/955
                      normalizeUrl: false,
                    },
                  ],
                }),
              ]),
        ],
      })
      .end();
```

结果错误如下（此处参考了`postcss-modules-scope`的[commit](https://github.com/css-modules/postcss-modules-scope/commit/cb11e64f2a11e8227ffcd2c593ae4745bceae844)对`af-webpack`中的`css-loader`进行了更新，但依然报错，原本的报错与 #1842 相同）：
[gist](https://gist.github.com/leiysky/fc0fe01db975c3a3e8a5d4b4c1001a03)

另外，我尝试在`create umi`的`ant design pro`脚手架上引入`react-monaco-editor`没有出现类似问题，但是在`ant-design-pro`官方提供的脚手架上出现了该问题。由于两个脚手架的差别还是有点大，无法精确定位到冲突点。

**Comment by sorrycc** [comment]
注释掉这一行呢？https://github.com/ant-design/ant-design-pro/blob/178c48d/config/config.js#L117

**Comment by leiysky** [comment]
@sorrycc 可以了，请问是什么原因呢。。

**Comment by sorrycc** [comment]
ant-design-pro 里的主题配置插件的问题吧。

**Comment by CyanPZ** [comment]
@leiysky 请问你是怎么配置集成 的
我这边一直报错
![image](https://user-images.githubusercontent.com/9296308/52766241-8aca8580-3061-11e9-8300-444750a9ac80.png)

**Comment by leiysky** [comment]
@CyanPZ 我这边如果用`monaco-editor-webpack-plugin`的话也会这样报错，去掉就能用了，不过这样没有语法高亮。我还在看有没有更合适的解决方案。

**Comment by CyanPZ** [comment]
@leiysky  我这边没有加 `monaco-editor-webpack-plugin`也是报错
![image](https://user-images.githubusercontent.com/9296308/52767708-47264a80-3066-11e9-9d72-cb3df623a261.png)

**Comment by leiysky** [comment]
@CyanPZ 试试把`config.js`里面这部分注释掉？
```js
// ...(!process.env.TEST && os.platform() === 'darwin'
//   ? {
//       dll: {
//         include: ['dva', 'dva/router', 'dva/saga', 'dva/fetch'],
//         exclude: ['@babel/runtime'],
//       },
//       hardSource: false,
//     }
//   : {}),
```

**Comment by CyanPZ** [comment]
@leiysky 很奇怪，我按照你的方法也是不行，后面我找到这个就没报错了
![image](https://user-images.githubusercontent.com/9296308/52772601-dbe37500-3073-11e9-953e-70494f370fe9.png)

**Comment by CyanPZ** [comment]
@leiysky 方便看一下你的配置和导入方式吗

**Comment by leiysky** [comment]
@CyanPZ 我直接使用`react-monaco-editor`的`module`，配置没改过了

**Comment by gitbotsman** [comment]
@CyanPZ 我也遇到同样的问题，在使用react-monaco-editor 的时候，请问你解决了这个问题了吗？

**Comment by CyanPZ** [comment]
@gitbotsman 我注释掉了config.js中的一段配置就可以了，但是我不太清楚为什么
![image](https://user-images.githubusercontent.com/9296308/53552054-7dd78700-3b75-11e9-91cf-e605a32884c5.png)

**Comment by m430** [comment]
@leiysky 我目前也是通过一样的方式解决css module样式的问题，出现的原因大概是因为引入了第三方的库也使用了css module样式影响了antd自己的样式加载。

**Comment by Seasonley** [comment]
我遇到相同问题，引入了`monaco-editor-webpack-plugin`后编译报错，目前也是通过注释`cssLoaderOptions`解决。

**Comment by LeoWang1991** [comment]
@Seasonley  https://github.com/umijs/umi/issues/2236 你可以看下这个解决方案，需要umi>=2.8
