### ISSUE TITLE
pwa的config

### ISSUE THREAD

**Issue by lifegit** [umijs/umi#1932]
webSite的目录关系：
+ webSite
    + services // 接口
    + dist // umi build出来的目录
        - service-worker.js

问题：
如果 config.js：pwa.workboxOptions.swDest 设置为 service-worker.js 那么umi build后该js则在dist里，因为我的站root不是dist(设置了publicPath:'/dist/'),此时是无法加载到该js的，如果swDest设置为'/dist/service-worker.js',就会变为 webSite.dist.dist.service-worker.js,就更无法访问到了。我想问下，是否可以添加一个service-worker的publicPath的配置项来搞定当service-worker.js不在跟目录下时这个需求呢？

**Comment by xiaoiver** [comment]
部署到非根目录的情况下应该用 `base` 而非 `publicPath`：
https://umijs.org/zh/config/#base

在拼接 ServiceWorker 的请求路径时，会使用 `base`：
```
register(`${process.env.BASE_URL}${swDest}`, {
```
https://github.com/umijs/umi/blob/master/packages/umi-plugin-react/src/plugins/pwa/registerServiceWorker.js#L30

**Comment by lifegit** [comment]
但是如果配置base, url就由https://domain/? 变成成了: https://domain/dist/?

**Comment by lifegit** [comment]
因为 base 也会影响路由

**Comment by lifegit** [comment]
register(`${process.env.BASE_URL}${swDest}`, {
是否可以单独做一个配置项呢？默认值可以为${process.env.BASE_URL},另外也可以自己设置

**Comment by sorrycc** [comment]
@lifegit 有没有兴趣提个 PR?
