### ISSUE TITLE
全局layout如何调用子组件的方法

### ISSUE THREAD

**Issue by zmm2tysu** [umijs/umi#1934]
当前有个项目antd-mobile+umi+dva
导航栏navbar写在全局layout里面的，navbar里面有个按钮，点击按钮需要调用子组件也就是this.props.children里面的方法，该如何调用呢

**Comment by Verten** [comment]
能通过context来实现么？

**Comment by zmm2tysu** [comment]
> 能通过context来实现么？

怎么用context实现啊，我现在用的events插件 绑定的事件，感觉好low

**Comment by sorrycc** [comment]
参考 https://github.com/umijs/umi/pull/1282#issue-224134432
