### ISSUE TITLE
umi dev , webpack 打包打包进度到 95%卡住

### ISSUE THREAD

**Issue by flowke** [umijs/umi#1935]
<img width="738" alt="2019-01-31 12 49 00" src="https://user-images.githubusercontent.com/15080893/52031280-a8bec300-2556-11e9-870b-ee73c325bad4.png">

就这样, 一直卡住, 同事的也一样

**Comment by dkvirus** [comment]
`unnamed compat plugin` 字面意思，插件问题。可以把 .umirc.js 下的配置贴一下看看。

**Comment by flowke** [comment]
> `unnamed compat plugin` 字面意思，插件问题。可以把 .umirc.js 下的配置贴一下看看。

和插件没关系, 前一天可以, 早上到公司就不行了, 在 Mock="none" 的时候可以启动

**Comment by i5ting** [comment]
能丢给demo出来重现么？

**Comment by afc163** [comment]
提问前先看看 FAQ。https://github.com/umijs/umi/issues/1421#issuecomment-438169125
