### ISSUE TITLE
Jest component

### ISSUE THREAD

**Issue by Verten** [umijs/umi#1938]
component里面使用了formatMessage方法，但是跑jest的时候会报warning，同时也拿不到多语言。这个情况要怎么处理？

**Comment by imhele** [comment]
mock 掉

**Comment by Verten** [comment]
formatMessage是从 umi/locale里面Import进来的，如何mock？能给点思路不😂

**Comment by imhele** [comment]
稍等，我在 create-umi 加个示例。你可以提前看看这篇文章 https://segmentfault.com/a/1190000011565450

**Comment by imhele** [comment]
在测试文件同级添加 `__mocks__` 文件夹，并在此文件夹中新建 `umi-plugin-locale.(ts|js)` 文件，然后在测试文件 `import` 后添加 `jest.mock('umi-plugin-locale');` ，测试时 `import {} from 'umi-plugin-locale';` 就会被定向到 `__mocks__` 里的文件。

**Comment by Verten** [comment]
不错，我试试
