### ISSUE TITLE
TitleWrapper.jsx in ./app/web/pages/.umi/router.js

### ISSUE THREAD

**Issue by wyzwhp** [umijs/umi#1939]
每次生成的路径都是这个"Routes": [require('TitleWrapper.jsx').default],
把他改成"Routes": [require('./TitleWrapper.jsx').default], 就能好，请修复一下这个问题，谢谢

**Comment by sorrycc** [comment]
@wyzwhp windows 用户？

**Comment by yutingzhao1991** [comment]
这个看上去像是之前遇到的 https://github.com/umijs/umi/pull/1850/files#diff-4f516677be49f656dfe4656eb0089cc1R57 这个修改对应的问题，看看是不是 umi 的版本不够新（可能是 umi-plugin-react 升上去了但是 umi 没有升）。

**Comment by sorrycc** [comment]
@wyzwhp 升级下依赖，还有问题再 reopen。
