### ISSUE TITLE
build 是否支持 all in one ？

### ISSUE THREAD

**Issue by malacca** [umijs/umi#1942]
想结合 Electron 做一个桌面版项目，使用 Ant Design pro， 请问构建是否支持打包后只有一个js, 一个css 文件。看了文档的所有参数，没找到相关介绍

**Comment by yutingzhao1991** [comment]
dynamicImport 配置为 false 就好了 https://umijs.org/zh/plugin/umi-plugin-react.html#dynamicimport

**Comment by malacca** [comment]
@yutingzhao1991  it works! 感谢，顺祝春节好
