### ISSUE TITLE
是否支持配置默认 chunk 名称（umi）？

### ISSUE THREAD

**Issue by dreamerblue** [umijs/umi#1944]
build 的默认 chunk 名称是否可以提供配置？例如配置 umi.css、umi.js 的文件名为 app.css、app.js。

**Comment by i5ting** [comment]
目前是写死的。

```
const entryScript = join(cwd, `./${paths.tmpDirPath}/umi.js`);
```

你可以在部署的时候自己命名，比如`mv umi.js app.js`这种

**Comment by yutingzhao1991** [comment]
什么场景下的需求？

**Comment by dreamerblue** [comment]
@yutingzhao1991  项目里有一些推荐或者说约定俗成的规范...

**Comment by sorrycc** [comment]
@dreamerblue 你好，目前不支持。

**Comment by shunok** [comment]
希望能支持

**Comment by rendongsc** [comment]
目前支持了吗？
我们项目有多个版本的登录页（是多个umi项目），希望生成的文件名以auth_v1,auth_v2等开头，方便运维根据客户的需求部署不同的文件。
