### ISSUE TITLE
.wrapper h1  希望去掉这些全局的css

### ISSUE THREAD

**Issue by hanwenbo** [umijs/umi#1946]
希望去掉这些全局的css，经常冲突

**Comment by afc163** [comment]
umi 应该不存在全局 css。

**Comment by hanwenbo** [comment]
@afc163 页面没有404哈，这个css是默认加载在全局下的，.wrapper呢又是常用的命名，我的项目不大，但是已经和两个库冲突。其他库没加css部分只是在div标签上加了class="wrapper"
![image](https://user-images.githubusercontent.com/5869741/52343012-eb4e3700-2a51-11e9-878c-4014c070d8a9.png)

**Comment by sorrycc** [comment]
@hansnow 你是不是禁用了 css modules ?

**Comment by hansnow** [comment]
@sorrycc 哥，你可能艾特错人了:sweat_smile:
