### ISSUE TITLE
react hook今天发布了

### ISSUE THREAD

**Issue by sessionboy** [umijs/umi#1947]
如题，希望umijs尽快跟上

**Comment by afc163** [comment]
两者好像并不冲突，你可以在 umi 中自由地使用 hooks。

**Comment by sessionboy** [comment]
@afc163  并不仅仅是指umijs本身，还有dva、antd，毕竟这些基本是绑定一起的，尤其是你们要接入区块和物料，就是一个小生态了。但现阶段尤其是antd，并不支持react hook。

另外我觉得umijs、dva这些，你们可能也会开发一些自己的react hook方便我们做开发。

**Comment by afc163** [comment]
antd 不支持 react hooks 具体是指什么？UI 库貌似和 hooks 没什么直接联系。

**Comment by sessionboy** [comment]
我讲的有点笼统了，这么说吧，有了hook之后，class会被用的越来越少，乃至于最后会被react API中剔除(虽然没有官宣，而是采取逐渐的策略)，总之臃肿的class已经没有必要了。
antd很多组件是用class写的，所以我觉得有必要做一些重构，或者新开一个repo做一个hook版本，性能会比现在的好很多。
另外一个就是dva，dva是基于redux基础上开发的，本身非常不错。但现在有了hook，尤其是useReducer这些钩子，其实没有必要再用第三方状态管理器了，你们完全可以基于context、hook API开发一个原生版的dva(没有redux)。

**Comment by asktalk** [comment]
@sessionboy  支持  useReducer非常简单，虽然大家一致在用redux，但是实际上这些第三方的框架还是很绕，不够直接。
