### ISSUE TITLE
约定目录和文件是否可配置

### ISSUE THREAD

**Issue by malacca** [umijs/umi#1949]
相应文档

https://umijs.org/zh/guide/app-structure.html
https://umijs.org/zh/guide/config.html

.umirc.js 可根据 UMI_ENV 配置不同选项。

希望 默认仍使用约定（可向下兼容），但也可在 配置文件 手动指定 相关的约定目录或文件

比如

src/layouts/index.js
src/pages
src/pages/404.js
src/global.(j|t)sx
src/global.(css|less|sass|scss)

使用场景举例：

比如使用了 pwa 插件生成一份 dist， global js 会针对性添加一些代码，另外生成不使用 pwa 的， global.js  就不需要了，或可以使用另外一个 global.js

比如针对 PC 和 phone 使用不同的 404 页面

etc....

目前根据文档，只有 src/pages/document.ejs  可以针对 env 设置不同生成结果 （
https://umijs.org/zh/guide/html-template.html
），其他的都未找到相关说明。

**Comment by xiaohuoni** [comment]
暂时这些文件都是固定的，还没有可以配置的地方。

**Comment by malacca** [comment]
希望可以考虑一下，当使用一套代码适配不同浏览器，甚至多端（如 electron），可以手工配置就显得有必要了。

虽然可以在  global.js 中进行环境判断进而输出不同效果，但既然都有 build 这个步骤了，就没必要打包用不到的代码了吧

**Comment by sorrycc** [comment]
先在 global.js 里通过环境变量进行判断吧，看似有这个配置的需求，但目前优先级比较低，比较少有场景会需要这点。
