### ISSUE TITLE
IE9-11打开白屏

### ISSUE THREAD

**Issue by jianghaolun** [umijs/umi#1955]
![image](https://user-images.githubusercontent.com/23391765/52615949-e5cd7280-2ed1-11e9-81fc-abad856503ba.png)
IE下报无效字符，chrome没问题
var Authorized = (_ref) => {
  var children = _ref.children,
      authority = _ref.authority,
      _ref$noMatch = _ref.noMatch,
      noMatch = _ref$noMatch === void 0 ? null : _ref$noMatch;
  var childrenRender = typeof children === 'undefined' ? null : children;
  return (0, _CheckPermissions.default)(authority, childrenRender, noMatch);
};

**Comment by xiaohuoni** [comment]
umi@2现在不是这么写的，使用[targets](https://umijs.org/zh/config/#targets)
```js
export default {
  plugins: [
    'umi-plugin-react',
  ],
  targets: {
    ie: 9,
  },
};
```

如果是umi@1，可以在global.js里面添加补丁

**Comment by Wen006** [comment]
mac开发的时候用ie11报错umi未定义，修改 config.js 配置去掉就行了
 ...(!process.env.TEST && os.platform() === 'darwin'
        ? {
            // dll: {
            //   include: ['dva', 'dva/router', 'dva/saga', 'dva/fetch'],
            //   exclude: ['@babel/runtime'],
            // },
            // hardSource: false,
          }
        : {}),
