### ISSUE TITLE
Unexpected template using `public/index.html` in develop mode

### ISSUE THREAD

**Issue by chiaweilee** [umijs/umi#1959]
## Version
`2.4.2`

## What is expected?
Expected umi use default template.

## What is actually happening?
`public/index.html` will used if it exist in develop mode,
and default template used in product mode.

### 2, `mkdir public`, create `index.html` as below
```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Your App</title>
</head>
<body>
  <div id="root"></div>
</body>
</html>
```
### 3, `npm run start`, open `localhost:8000`

*the page title is `Your App`*, `public/index.html` used

### 4, `npm run build`, check `dist/index.html`

*the page title is `umi`*, default template used.

**Comment by xiaohuoni** [comment]
use the html template  on `src/pages/document.ejs`
https://umijs.org/guide/html-template.html#html-template
