### ISSUE TITLE
docs require translate

### ISSUE THREAD

**Issue by chiaweilee** [umijs/umi#1960]
Docs below require translate into english

https://umijs.org/guide/html-template.html#configure-the-template

https://umijs.org/guide/html-template.html#%E9%92%88%E5%AF%B9%E7%89%B9%E5%AE%9A%E9%A1%B5%E9%9D%A2%E6%8C%87%E5%AE%9A%E6%A8%A1%E6%9D%BF

**Comment by xiaohuoni** [comment]
@imhele
