### ISSUE TITLE
约定式路由可以直接在router.js增加重定向吗？yaml注解的方式可以增加吗？

### ISSUE THREAD

**Issue by clean222** [umijs/umi#1961]

**Comment by coppyC** [comment]
其实自己动手试一下就知道了，
我用yaml注解的方式可以，router没用过。
/** 
 * redirect: /xxx
 */

**Comment by clean222** [comment]
@coppyC 谢谢

**Comment by clean222** [comment]
@coppyC 我目前发现这个yaml只支持 Routes，redirect，title。请问还支持什么？有这个文档吗?比如我不想生成某些路由；我想修改某些路由的path，增加某个path然后redirect生成的路由.....然后这些yaml注释可以解决吗？

**Comment by xiaohuoni** [comment]
@clean222 试试update吧！
https://github.com/xiaohuoni/umi-antd-pro/blob/5ebf3118ccd6352d6bc83e075df0abaab03fd2f1/config/config.js#L23-L26
