### ISSUE TITLE
[问题] 如何使用 stylus

### ISSUE THREAD

**Issue by atzcl** [umijs/umi#1962]
在 `.umirc.js` 里面的 `chainWebpack` 里面配置了，但是无效：
```js
config.module
      .rule('stylus')
      .oneOf('normal')
      .use('stylus-loader')
      .loader('stylus-loader')
      .options({
        import: [
          resolve('src/assets/css/variables.styl')
        ],
      });
```

**Comment by sorrycc** [comment]
参考 https://github.com/umijs/umi/issues/1421#issuecomment-445132872

**Comment by fengxinming** [comment]
@atzcl 兄弟配成功了吗？我这边还是报错，解析不了.styl，不知道是webpack-chain的问题，还是af-webpack的问题

**Comment by fengxinming** [comment]
@atzcl 我已经配成功拉，点击看 [这里](https://github.com/fengxinming/chain-css-loader)
