### ISSUE TITLE
[umi-plugin-locale] formatMessage not initialized yet, you should use it after react app mounted

### ISSUE THREAD

**Issue by suezse** [umijs/umi#1963]
import { formatMessage } from 'umi/locale'之后，在componentDidMount方法中调用formatMessage报warning，warning信息：[umi-plugin-locale] formatMessage not initialized yet, you should use it after react app mounted. 请问该怎么改呀？

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/blob/master/packages/umi-plugin-locale/README.md
查阅文档，确认一下用法。

**Comment by suezse** [comment]
好的，谢谢。原来是我仿照antd pro的写法在locales文件夹下把不同页面中用到的字段分开写了，但是忘了再加一个zh-CN.js文件统一的import再export。报错信息有些偏差，导致我一直以为是我不该在componentDidMount中使用formatMessage方法。

**Comment by xiaohuoni** [comment]
👍

**Comment by goldentiger1127** [comment]
> 好的，谢谢。原来是我仿照antd pro的写法在locales文件夹下把不同页面中用到的字段分开写了，但是忘了再加一个zh-CN.js文件统一的import再export。报错信息有些偏差，导致我一直以为是我不该在componentDidMount中使用formatMessage方法。

你好，我也遇到了你一样的问题，但是无法解决，可以详细的说一下你是如何解决的吗？
