### ISSUE TITLE
pages 目录嵌套四层后model丢失

### ISSUE THREAD

**Issue by youpeipei** [umijs/umi#1966]
![image](https://user-images.githubusercontent.com/37535101/52761384-2fdb6300-304e-11e9-8f2a-b4f6873eda10.png)

![image](https://user-images.githubusercontent.com/37535101/52761398-379b0780-304e-11e9-82fd-f23e1f20bec4.png)

![image](https://user-images.githubusercontent.com/37535101/52761410-441f6000-304e-11e9-9f04-603a75efb5a4.png)

**Comment by sorrycc** [comment]
请提供可复现仓库。

**Comment by weishijun14** [comment]
周末弄个codesandbox上来 :)

**Comment by weishijun14** [comment]
@exvu no
