### ISSUE TITLE
webpack html 的配置貌似不会覆盖 dist/index.html

### ISSUE THREAD

**Issue by pengfeiWang** [umijs/umi#197]
看到文档有html配置项, 以为是覆盖umi默认生成的 html呢, 实际没有覆盖
```
html: {
    template: './src/index.ejs',
    filename: '../index.html',
  }
```

**Comment by sorrycc** [comment]
参考 https://umijs.org/docs/zh-Hans/html-tpl.html

**Comment by pengfeiWang** [comment]
官方的文档看了，这个html指的是全局的首页文件，比如我想在全局的index.html中增加一些额外的脚本饮用，是会被覆盖的，默认的全局首页文件内容应该是 umi-build-dev里的模版文件，不知道是不是我文档还没看仔细，遗漏了什么

**Comment by sorrycc** [comment]
可以在 index.html 里判断 context.path 增加额外的内容。
