### ISSUE TITLE
调用后台接口，umi却把它当场页面路由进行跳转

### ISSUE THREAD

**Issue by HypnosNova** [umijs/umi#1970]
前端页面和后台系统是部署在同一个域名下的。前端调用后台接口拿数据，umi认为是路由跳转从而得到返回结果是404页面。如果页面和后台是不同的端口，就回报跨域错误。这个要怎么解决

例如前后端项目都部署在aaa.com

现在有个登录页面：aaa.com/login
后台有个获取用户的接口：aaa.com/api/getuser

那么我调用后台接口，umi会认为是跳到/api/getuser路由页面，从而得到404页面。

**Comment by sorrycc** [comment]
开发环境还是生产环境？开发环境应该不会在同一个端口吧，生产环境的路由应该是后台控制的。

**Comment by HypnosNova** [comment]
@sorrycc 开发环境。之前是后台不允许跨域，所以前端会用whistle把localhost地址代理到后台部署到测试服务器相同的ip和端口下。就出现来这个问题。现在我们是让后台允许ip相同，端口不同可以跨域请求。

**Comment by sorrycc** [comment]
需求有点怪，请求不同域下的 css 和 js 不算跨域吧。

**Comment by HypnosNova** [comment]
@sorrycc 现在问题是这样，我在某个页面调用接口，service里面是这样：
request('api/getuser');

那么model里面拿到的返回结果是404页面的html代码

或者直接fetch也试过：
fetch('api/getuser').then(data => data.json()).then(data=>console.log(data)
在第一个then里面也会报错，返回的结果也是404页面的html代码，而不是json数据

**Comment by clock157** [comment]
你看下 network 里的请求，地址是否正确，返回内容

**Comment by HypnosNova** [comment]
@clock157 正确的。
network里面接口的地址是xxx.xxx.xxx.xxx:8000/api/getuser，但是由于前端页面也是代理到xxx.xxx.xxx.xxx:8000，所以在请求接口的时候路由以为是跳转xxx.xxx.xxx.xxx:8000/api/getuser页面而不是去后端调接口，所以request或者fetch出来的结果就是404页面的html代码

**Comment by clock157** [comment]
这不是 umi 的问题，而是你配置的网关没有正确将  api/xxx 这个地址代理到后端 server, 在本地你可以通过 https://umijs.org/config/#proxy ，如果是部署开发或生产环境，你需要配置网关。

**Comment by FionaWong** [comment]
> 这不是 umi 的问题，而是你配置的网关没有正确将 api/xxx 这个地址代理到后端 server, 在本地你可以通过 https://umijs.org/config/#proxy ，如果是部署开发或生产环境，你需要配置网关。

本地的怎么代理呢？

**Comment by FionaWong** [comment]
我也遇到这个问题，请问下是什么原因呢？有解决方案了吗？

**Comment by kalavt** [comment]
遇到了同样问题, UMI 把 API 地址 当成了页面路由跳转.
