### ISSUE TITLE
在windows系统pages/**/_mock.js修改无法热加载mock数据

### ISSUE THREAD

**Issue by zysuper** [umijs/umi#1974]
由于chokidar在windows下使用反斜杠组成的glob无法正确watch文件变动的bug，[chokidar/issues/777](https://github.com/paulmillr/chokidar/issues/777)
临时的修复手段是将反斜杠转换成斜杠。
`.replace(/\\/g, '/')`

**Comment by xiaohuoni** [comment]
umi应该有winPath

**Comment by xiaohuoni** [comment]
@yutingzhao1991

**Comment by yutingzhao1991** [comment]
和 `winPath` 没有关系，看上去应该算是 chokidar 这个的问题。那应该其它地方的 watch 也会有这个问题。不光是 `_mock.js`。

**Comment by zysuper** [comment]
有用glob表达式的才会有问题。

**Comment by sorrycc** [comment]
@zysuper  有兴趣提个 PR 修复下吗？

**Comment by zysuper** [comment]
好的，我提个PR。

**Comment by zysuper** [comment]
我看到umi-build-dev 1.4.4在createMockMiddleware.js的如下代码：
```
const watcher = chokidar.watch(
      [absConfigPath, absMockPath, join(absPagesPath, '**/_mock.js')],
      {
        ignoreInitial: true,
      },
    );
```
已经被独立成umi-mock模块，并且上述代码被替换成：
```
const paths = [
    absMockPath,
    absConfigPath,
    basename(absSrcPath) === 'src' ? absSrcPath : absPagesPath,
  ];
........
const watcher = chokidar.watch(paths, {
      ignoreInitial: true,
    });
```
如果是监控整个absPagesPath，应该不会再触发这个bug了。
但这样是否会导致无关的文件被修改时，触发了mock回调处理函数呢？

**Comment by zysuper** [comment]
umi 2.5 已经修复。

**Comment by sorrycc** [comment]
> 但这样是否会导致无关的文件被修改时，触发了mock回调处理函数呢？

这个应该没多大消耗，先简单处理吧。
