### ISSUE TITLE
umi 打包完，感觉文件有点大，具体大小如下，求分析下：

### ISSUE THREAD

**Issue by xiaomei991** [umijs/umi#1975]
<img width="1432" alt="wechatimg1" src="https://user-images.githubusercontent.com/20355401/52828172-b18cc880-3102-11e9-898c-8fd2776dccc7.png">
<img width="311" alt="wechatimg2" src="https://user-images.githubusercontent.com/20355401/52828173-b2255f00-3102-11e9-8f49-138d8451e78e.png">

**Comment by sorrycc** [comment]
这个还是自己分析吧。
