### ISSUE TITLE
umi是否支持多个路由使用同一页面

### ISSUE THREAD

**Issue by susanred** [umijs/umi#1977]
umi根据pages中的文件自动生成路由配置十分方便，
但在一些业务场景下，例如“个人空间”，本人和其他人看到的是同一个页面，但是路由和面包屑不一样，这个该如何配置呢？

**Comment by imhele** [comment]
使用 [动态路由](https://umijs.org/guide/router.html#dynamic-routing) ，umi 会给组件 props 传入一个参数 `match` ，你可以从 `params` 里取到对应的值：
```ts
interface YourComponentProps<T extends object = null> {
  match?: {
    isExact: boolean;
    params: { [key in keyof T]: T[key] };
    path: string;
    url: string;
  };
}
```

**Comment by sorrycc** [comment]
我理解，路由应该是一样，然后在同一个路由组件里做区分处理，面包屑生成逻辑也需要特殊调整下。
