### ISSUE TITLE
通过yarn create umi创建项目失败

### ISSUE THREAD

**Issue by yutao98712** [umijs/umi#1978]
![image](https://user-images.githubusercontent.com/20662809/52838913-3c83b800-312f-11e9-9bb7-5e4901658d3f.png)
已经根据文档的提示，将yarn global bin的路径添加至环境变量中了，但依然无法解决该问题。
![image](https://user-images.githubusercontent.com/20662809/52838978-7a80dc00-312f-11e9-8425-b05a66d9cc2d.png)

**Comment by sorrycc** [comment]
这样呢？

```bash
$ yarn global add create-umi
$ create-umi
```

**Comment by sorrycc** [comment]
有问题再 reopen。
