### ISSUE TITLE
更新到umi@2.5.0后编译错误

### ISSUE THREAD

**Issue by leiysky** [umijs/umi#1983]
![image](https://user-images.githubusercontent.com/22445410/52858019-f09f3600-3163-11e9-8f6f-bc9544a71177.png)

看起来像是dynamic module的loader问题。

`umi@2.4.4`编译的结果：
```js
import dynamic from 'umi/dynamic';
{
    "path": "/",
    "component": dynamic({ loader: () => import('../../layouts/BasicLayout'), loading: require('/Users/leiysky/work/ttarch/archcloud/src/components/PageLoading/index').default }),
    "Routes": [require('../Authorized').default],
    "routes":[],
}
```

`umi@2.5.0`编译的结果：
```js
import _dvaDynamic from 'dva/dynamic';
{
    "path": "/",
    "component": _dvaDynamic({
      component: () => import('../../layouts/BasicLayout'),
      LoadingComponent: require('/data00/home/leiyu.leiysky/ttarch-cloud-fe/src/components/PageLoading/index').default,
}),
    "Routes": [require('../Authorized').default],
    "routes": [],
}
```

**Comment by mlqgg** [comment]
遇到了同样的错误。。。

**Comment by leiysky** [comment]
@mlqgg 锁的大版本，下午上线的时候崩了，回滚也崩了。。。😆

**Comment by sorrycc** [comment]
给个可重现的仓库？我试了下 ant-design-pro 没有发现问题。

@leiysky 回滚为啥会崩？

**Comment by sorrycc** [comment]
会不会是 umi 升了但插件还是老的？

**Comment by jwmann** [comment]
I have the same problem in ant-design-pro
Here's my ticket ant-design/ant-design-pro#3548

**Comment by mlqgg** [comment]
在webpack的git下发现了类似的issue(https://github.com/webpack/webpack/issues/8779),然而问题的根本好像是npm的bug？？？

**Comment by sorrycc** [comment]
你们是用 npm 安装依赖？试试 yarn 和 cnpm 会不会有问题？

**Comment by zhilianbi520** [comment]
遇到同样问题～！求解～

**Comment by sorrycc** [comment]
@zhilianbi520 先用 cnpm 或 yarn。

**Comment by zhilianbi520** [comment]
@sorrycc  cnpm 也有同样的问题。

**Comment by sorrycc** [comment]
@zhilianbi520 这个错和前面的不一样吧。

**Comment by zhilianbi520** [comment]
更新"umi-plugin-react": "^1.5.0" 这个？回退webpack版本是更新这个依赖库嘛？
