### ISSUE TITLE
设置treeShaking报错问题

### ISSUE THREAD

**Issue by ruizhengyun** [umijs/umi#1986]
升级到V2.4.0，报错=> 
watch handler failed, since ".umirc.js" 中配置的 "treeShaking" 并非约定的配置项
export default {
   ...,
   treeShaking: true
}
还要配置其他项？

**Comment by sorrycc** [comment]
给可复现的步骤，或者直接升最新的 2.5。

**Comment by sorrycc** [comment]
有问题再 reopen 。
