### ISSUE TITLE
约定式路由怎么触发404？

### ISSUE THREAD

**Issue by 6691** [umijs/umi#199]
dev 下我输入错误地址没有触发自定义的404页面，而是显示： umi development 404 page....

直接访问 http://localhost:8000/404  正常显示了自定义的404页面

**Comment by sorrycc** [comment]
> 开发模式下，umi 会添加一个默认的 404 页面，但你仍然可通过精确地访问 /404 来验证 404 页面。

生成模式下会触发的。

**Comment by 6691** [comment]
好吧

**Comment by Rpeanut** [comment]
@sorrycc嗨云谦大大，我部署到测试环境任然不会触发自定义的404页面

**Comment by MinWest** [comment]
dev 下我输入错误地址没有触发自定义的404页面，而是显示空白页

直接访问 http://localhost:8000/404 正常显示了自定义的404页面

umi build 后的文件，放到本地nginx 公共目录，后同样是访问未定义的路由显示空白页，配置history: {type: 'hash'}后也是同样的表现

$ node -v
v12.12.0
$ umi -v
umi@3.2.1

这个解决方案在issues下并没有找到啊～

**Comment by viccsen** [comment]
@sorrycc +1，umi@3.2.6，node 10.15.3， 约定式路由下输入错误地址显示空白页面，不会自动跳转404页面

**Comment by sendking** [comment]
https://github.com/umijs/umi/issues/5652 尝试使用这里的老外解决方式
`
...
NoFoundPage.path = undefined;
NoFoundPage.exact = undefined;
...
`
对应umi生成的路由
![image](https://user-images.githubusercontent.com/12857833/109456523-fd193180-7a93-11eb-9526-c0baee1dcfa2.png)
