### ISSUE TITLE
在容器中构建报错~!Module parse failed: Unexpected token 

### ISSUE THREAD

**Issue by zhilianbi520** [umijs/umi#1991]
在容器中构建报错 @umi2.4.2 @umi-plugin-react npm6.6版本 node10.8版本～
![jietu20190218-154123](https://user-images.githubusercontent.com/16549630/52935192-b2885900-3393-11e9-8b86-960ed7d41770.jpg)

**Comment by ystyle** [comment]
同遇到了这问题
![image](https://user-images.githubusercontent.com/4478635/52935766-44dd2c80-3395-11e9-9f8e-839396f0c5c9.png)

**Comment by sorrycc** [comment]
这不应该是 umi@2.5 下才会有的问题？和 #1983 是同一个问题吧。

**Comment by zhilianbi520** [comment]
@sorrycc 切换回之前的版本，。，问题同样复现。。。

**Comment by sorrycc** [comment]
更我更新个版本，然后全部换新的试试。或者你用 yarn 试试。

**Comment by ystyle** [comment]
@zhilianbi520 @sorrycc 切回2.4.4就没问题了

**Comment by sorrycc** [comment]
已在 umi@2.5.1 中修复。
