### ISSUE TITLE
umi-mock watch触发频繁

### ISSUE THREAD

**Issue by LeoHuiyi** [umijs/umi#1992]
版本: umi: 2.5.0

![image](https://user-images.githubusercontent.com/8001457/52937205-73f59d00-3399-11e9-814f-d6e69c25b365.png)

能改回
![image](https://user-images.githubusercontent.com/8001457/52937452-16ae1b80-339a-11e9-9b3c-ce5ed67f91b8.png)

**Comment by sorrycc** [comment]
可以，有兴趣提个 PR 么？
