### ISSUE TITLE
路由配置如果引用了同一个对象，会导致最终的路由配置错误

### ISSUE THREAD

**Issue by yutingzhao1991** [umijs/umi#1998]
比如下面的配置：

```js
const commonRoutes = [{
  path: 'test',
  component: 'test',
}];

export default [{
  path: '/a',
  routes: commonRoutes,
}, {
  path: '/b',
  routes: commonRoutes,
}];
```

这个会导致最终 https://github.com/umijs/umi/blob/master/packages/umi-build-dev/src/routes/getRouteConfigFromConfig.js#L23 这里会被重复调用，`component: 'test'` 最终会被转换为 `component: '../page/page/test'`（多一个 page）。

**Comment by exvu** [comment]
你可以使用lodash.cloneDeep 创建新对象
