### ISSUE TITLE
如何升级umi版本，以及antd，dva这些版本如何控制

### ISSUE THREAD

**Issue by SakuraYea** [umijs/umi#2000]
开发过程中，版本在不停迭代修复一些bug，umi文档没有提及如何升级版本，package.json对于用户来说是一个黑盒，关联的包敢随意修改，请问该如何升级。

**Comment by SakuraYea** [comment]
![image](https://user-images.githubusercontent.com/7360502/52996945-00679480-345a-11e9-919c-075b0d057278.png)
文档只提供react以及umi的一些基本版本信息那么为什么不提供升级方案

**Comment by SakuraYea** [comment]
![image](https://user-images.githubusercontent.com/7360502/52997014-3dcc2200-345a-11e9-9434-e1f44ae5ec2d.png)
package.json相对于用户是一个黑盒

**Comment by SakuraYea** [comment]
![image](https://user-images.githubusercontent.com/7360502/52997451-8506e280-345b-11e9-92bf-cc6e85d28f50.png)
使用yarn upgrade-interactive --latest只能检测这些依赖，没有dva也没有antd

**Comment by SakuraYea** [comment]
请问umi改如何控制这些依赖进行升级操作

**Comment by wangxingkang** [comment]
自己安装就好 优先使用自己安装的版本
