### ISSUE TITLE
ant design pro build 问题

### ISSUE THREAD

**Issue by LiboliboLibolibo** [umijs/umi#2002]
ant design Pro build时报错，错误日志如下
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.5.0-next.0
3 info using node@v11.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ant-design-pro@2.1.1~prebuild: ant-design-pro@2.1.1
6 info lifecycle ant-design-pro@2.1.1~build: ant-design-pro@2.1.1
7 verbose lifecycle ant-design-pro@2.1.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle ant-design-pro@2.1.1~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/tiantian/admin-test/qyl-admin/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tiantian/.rvm/bin
9 verbose lifecycle ant-design-pro@2.1.1~build: CWD: /Users/tiantian/admin-test/qyl-admin
10 silly lifecycle ant-design-pro@2.1.1~build: Args: [ '-c', 'umi build' ]
11 silly lifecycle ant-design-pro@2.1.1~build: Returned: code: 1  signal: null
12 info lifecycle ant-design-pro@2.1.1~build: Failed to exec build script
13 verbose stack Error: ant-design-pro@2.1.1 build: `umi build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:188:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:188:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid ant-design-pro@2.1.1
15 verbose cwd /Users/tiantian/admin-test/qyl-admin
16 verbose Darwin 18.2.0
17 verbose argv "/usr/local/Cellar/node/8.4.0/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v11.6.0
19 verbose npm  v6.5.0-next.0
20 error code ELIFECYCLE
21 error errno 1
22 error ant-design-pro@2.1.1 build: `umi build`
22 error Exit status 1
23 error Failed at the ant-design-pro@2.1.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

仔细检查了也没有大小写不一致的问题，困扰好久了

**Comment by LiboliboLibolibo** [comment]
补充一句本地npm start，和npm run build没问题，目前是本地打包解压放在线上的，由于是线上项目不敢删node-models尝试

**Comment by LiboliboLibolibo** [comment]
怀疑是某个依赖的版本不对，具体又不知道从何下手

**Comment by sorrycc** [comment]
从日志看，没有到 umi 就报错了。

**Comment by okoala** [comment]
提供能复现的仓库吧，不然没法查~
