### ISSUE TITLE
How do I add a loader configuration with chainWebpack. 

### ISSUE THREAD

**Issue by fxylee** [umijs/umi#2005]
[Webpack preprocessing with graphql-tag/loader](https://github.com/apollographql/graphql-tag#webpack-preprocessing-with-graphql-tagloader)

[The same question](https://github.com/gajus/babel-plugin-graphql-tag/issues/27)

我通过`webpack.config.js`可以正确处理`.graphql`文件，但是我在umi里面通过`chainWebpack`配置的loader不起作用

I can get compiled results when i use `webpack.config.js` to config webpack.
But I can't get compiled results when i use chainWebpack to config webpack,
I'm not sure my configuration code is correct

```javascript
config.module
  .rule('graphql')
     .test(/\.graphql$/)
  .exclude
    add(/node_modules/)
    .end()
  .use('graphql-tag/loader')
    .loader('graphql-tag/loader')
    .end();
```

```
# demo.graphql
query Demo {
  uv
}
```

```
import DemoGQL from './demo.graphql'
```

**Comment by sorrycc** [comment]
参考 https://github.com/umijs/umi/issues/1421#issuecomment-445132872
