### ISSUE TITLE
yarn create umi提示安装包404

### ISSUE THREAD

**Issue by Willworkgogogo** [umijs/umi#2010]
使用yarn create umi创建项目时报错：
error An unexpected error occurred: "http://registry.npm.taobao.org/flatmap-stream/download/flatmap-stream-0.1.1.tgz: Request failed \"404 Not Found\"".

尝试更换了几个其他的npm源，依旧是同样的问题

环境：
yarn ： v1.13.0
umi: v2.5.4

**Comment by imhele** [comment]
这个包三个月前被 npm 封了，但 create-umi 似乎并没有直接或间接依赖它

**Comment by imhele** [comment]
你可以尝试 `yarn list flatmap-stream` 和 `yarn global list` 找一下是否在其他地方有这个依赖，确定是 umi 的依赖再 reopen 。
