### ISSUE TITLE
开启了dll后antd样式丢失

### ISSUE THREAD

**Issue by aited** [umijs/umi#2017]
import { resolve } from 'path'
import RouterConfig from './config/router.config';
import ThemePlugin from './config/theme.plugin';
// ref: https://umijs.org/config/
export default {
  routes:RouterConfig,
  history: 'hash',
  plugins: [
    // ref: https://umijs.org/plugin/umi-plugin-react.html
    ['umi-plugin-react', {
      antd: true,
      dva: {
        immer: true,
        hmr:false,
      },
      dynamicImport: {
        webpackChunkName: true,
        loadingComponent: './components/TLoader/index',
      },
      title: 'TCode.Web',
      dll: {
        include: [],
      },
      pwa: false,
      hardSource: false,
    
    }],
----------------------以上是配置文件------------------------

**Comment by sorrycc** [comment]
提供复现步骤后再 reopen 。
