### ISSUE TITLE
能不能把当前约定的所有目录都提供给用户配置

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#2018]
提供路径文件夹配置，没有或为空字符时，使用原有默认值。
```js
{
src:'src',
pages:'pages',
mock:'mock'
}
```
为了在国际化的时候，自己配置加载不同的mock文件夹。
还有之前有用户希望修改约定是pages。

**Comment by sorrycc** [comment]
选择性挂载不同的 mock 可以有其他的实现方式，目录约定是基础，不能放开，放开后不利于之后的功能扩展。

**Comment by xiaohuoni** [comment]
选择性挂载不同的 mock 可以有其他的实现方式，这个有什么方案推荐吗？

**Comment by sorrycc** [comment]
用 .umirc.mock.js，然后通过环境变量选择性挂载 mock/ 下不同语言的文件夹？
