### ISSUE TITLE
希望可以有mock only模式

### ISSUE THREAD

**Issue by zhongjiewu** [umijs/umi#2019]
使用ant design pro的时候，发布静态前端后希望能在后端开发完毕前使用mock的后端作为demo站点展示。现在只能在服务器上开启完整的开发环境获得mock API端。希望可以有mock only模式而不开启webpack等复杂的部分。

`umi MOCK=only dev`

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/pull/1971

**Comment by zhongjiewu** [comment]
@xiaohuoni 我看了那个PR，好像并没有添加`umi serve`这个选项呀？

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/pull/1971/files#diff-4c2bd1c1d86a411ad10adca3fa0ce370

**Comment by zhongjiewu** [comment]
多谢。希望能添加到 umi的包里面成为一个命令。

**Comment by xiaohuoni** [comment]
应该是文档还没补充而已

**Comment by zhongjiewu** [comment]
我先把做法在这里写下来，如果有人搜到正好可以帮到他。

在package.json中添加 umi-serve 包
```
npm install umi-serve --save-dev
```

然后在package.json中添加script命令
```
"scripts": {
  ...
  "api": "umi-serve",
}
```

然后就可以通过 `npm run api` 唤起mock服务器了

**Comment by afc163** [comment]
我有点担心有人会拿 umi-serve 当 egg/koa/express 用了。

**Comment by zhongjiewu** [comment]
那就把file watcher做上然后运行的时候写明白一点呗？然后命令叫mock-api之类的就更明白了。
我确实需要单独serve （用来做prototype和demo，介于dev和真正的production之间，所以需要部署到开放稳定的环境）

偏右 <notifications@github.com>于2019年3月6日 周三下午5:45写道：

**Comment by RanQiwu** [comment]
> 我先把做法在这里写下来，如果有人搜到正好可以帮到他。
> 
> 在package.json中添加 umi-serve 包
> 
> ```
> npm install umi-serve --save-dev
> ```
> 然后在package.json中添加script命令
> 
> ```
> "scripts": {
>   ...
>   "api": "umi-serve",
> }
> ```
> 然后就可以通过 `npm run api` 唤起mock服务器了

你好，请问如何配置端口呢？

**Comment by zhongjiewu** [comment]
@RanQiwu 可以请作者 @sorrycc 来回答这个问题。
在这之前，你可以进入node_modules/umi-serve/bin/umi-serve.js里面直接修改文件改变端口

**Comment by RanQiwu** [comment]
> @RanQiwu 可以请作者 @sorrycc 来回答这个问题。
> 在这之前，你可以进入node_modules/umi-serve/bin/umi-serve.js里面直接修改文件改变端口

谢谢！

**Comment by jing-wu** [comment]
我理解的是，使用umi-server是将整个前端项目部署在服务器上，然后使用`npm run api`使项目使用mock数据跑起来。

而如果是想将项目build之后，将生成的静态文件发布在服务器上（使用Spring Boot），这时候怎么使用mock数据？

**Comment by zhongjiewu** [comment]
@jing-wu
前端项目应该用静态服务器部署，例如nginx。index.html静态文件传回浏览器后，所以资源都会随之加载。umi-serve是用来启动mock数据api服务器的。需要用nginx把/api的路径对准mock服务器端口（proxy pass）。

**Comment by jing-wu** [comment]
多谢！

**Comment by askurat** [comment]
@zhongjiewu I know this is quite an old post but was just curious how you handled this. Do you have any sort of example?

**Comment by zhongjiewu** [comment]
@askurat

**Comment by zhongjiewu** [comment]
@askurat here's an example nginx conf to proxy over to API server

```
server {
    listen 80 http2;
    server_name mysite.com;

    root /var/www;
    gzip on;
    gzip_types application/json application/javascript text/css;

    autoindex off;
    index index.html;

    resolver 8.8.8.8;
    set $api_server api.mysite.com;
    set $api_port 8080;

    location /api {
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Real-IP         $remote_addr;

        proxy_pass         http://$api_host:$api_port;
        break;
    }

    try_files $uri $uri/ /index.html;
}
```

**Comment by iShawnWang** [comment]
> 我有点担心有人会拿 umi-serve 当 egg/koa/express 用了。

正有此意 ! demo 演示的场景, 会想直接直接发布上去一个前端+mock server 做演示
