### ISSUE TITLE
.umirc.js 中loading无效果，依然 Compiling

### ISSUE THREAD

**Issue by Liuqing650** [umijs/umi#202]
```
  "umi": "^1.0.6",
  "umi-plugin-dva": "^0.1.5"
```
.umirc.js文件中
```
export default {
  plugins: ['umi-plugin-dva'],
  loading: './PageLoadingComponent',
  hashHistory: true
}
```

项目目录下有新建此文件，但是每一次 `npm start` 进入时都依然出现 `Compiling...`
![](https://liuqing650.github.io/view/umi/issue/compiling.png)

**Comment by sorrycc** [comment]
有 PageLoadingComponent 时 Compiling? 没有是好的？

**Comment by Liuqing650** [comment]
是的

**Comment by sorrycc** [comment]
loading 只针对 build 有效，dev 模式下始终是 Compiling 的。

**Comment by Liuqing650** [comment]
确实是这个样子，没有注意到。谢谢

**Comment by superlbr** [comment]
@Liuqing650 
按需编译可通过 COMPILE_ON_DEMAND 环境变量关闭。关掉之后就没有Compiling

$ COMPILE_ON_DEMAND=none npm start
