### ISSUE TITLE
umi-mock:  ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by chiaweilee** [umijs/umi#2020]
### async/await
ReferenceError: regeneratorRuntime is not defined

### Step

1, create mock code with async function

```javascript
// mock/api.js
export default {
  '/api/async': async function() {
    // code
  },
}
```

2, run dev

code https://github.com/umijs/umi/blob/master/packages/umi-mock/src/getMockData.js#L125

FYI, I used Promise instead.

**Comment by xiaohuoni** [comment]
It's supposed to be asynchronous ？ no use async
