### ISSUE TITLE
支持 eslint 来做 typescript 的 lint

### ISSUE THREAD

**Issue by clock157** [umijs/umi#2021]
typescript 和 eslint 官宣在一起，今后就使用 eslint 就可以了，结合 [umi-lint](https://github.com/umijs/umi-lint) 更方便使用。先记个 issue，我来搞。

https://github.com/Microsoft/TypeScript/issues/29288
https://eslint.org/blog/2019/01/future-typescript-eslint#the-future-of-typescript-on-eslint

**Comment by sorrycc** [comment]
https://medium.com/palantir/tslint-in-2019-1a144c2317a9

**Comment by clock157** [comment]
在 #2024 跟进

**Comment by langlong149** [comment]
已经使用eslint来代替tslint了吗？
