### ISSUE TITLE
更全面的 eslint-config-umi

### ISSUE THREAD

**Issue by clock157** [umijs/umi#2024]
## 为什么
在内部我们基于 bigfish ，在外部基于 antd, antd-pro 各自进行了代码规范最佳实践的探索和沉淀，现在是时候来一波整理，形成一个统一维护的规范，供我们的开发者使用。

## 目标
- [ ] 支持 typescript
- [ ] 不需要单独安其他依赖
- [ ] umi 应用开发最佳实践
- [ ] 组件开发最佳实践
- [ ] 库开发最佳实践

## 提议方案
在不同的场景，通过 path 使用不同的规则集
默认：
`"extends": "umi",`
支持 ts
`"extends": "umi/ts",`
...

## 问题
- [ ] 现在的 eslint-config-umi 比较简单，我们是否要做成一个最佳实践的各种规则集？
- [ ] 是否要集成 stylelint 这种非 js 的，但也是 lint 的规则，减小用户去获取信息的成本，还是说通过文档解决。

**Comment by sorrycc** [comment]
Extend eslint-config-umi 用户是否还要安装额外的 eslint-plugin-xxx ?

**Comment by clock157** [comment]
我的理解是不需要，我在使用这个版本的 `eslint-config-umi` 时，还提示我还要安装 `eslint-plugin-flowtype`，安装完又提示另一个，感觉这对用户不太友好。

**Comment by sorrycc** [comment]
我理解 eslint 的 config 和 plugin 是分开的，怎么能做到只依赖一个 eslint config 而不安装 plugin?

**Comment by clock157** [comment]
将用到的 plugin 作为 `dependencies` ，之前是因为考虑到什么原因没有这么做呢？

**Comment by sorrycc** [comment]
现在应该是不能把 config 和 plugin 打包到一起的，参考 [https://github.com/eslint/eslint/issues/3458](https://github.com/eslint/eslint/issues/3458)，等 https://github.com/eslint/rfcs/pull/9/files 这个吧。
