### ISSUE TITLE
如何给每一个页面添加自己meta信息

### ISSUE THREAD

**Issue by yubanxian2014** [umijs/umi#2026]
如何给每一个页面添加属于这个页面的meta信息，尝试过在plugin里添加metas但是这会导致所有的页面的meta是相同的，addHTMLMeta是否可以实现呢？官网的使用文档对这个方法的说明不是特别详细，如果可以实现的话请教一下如何使用呢？

**Comment by sorrycc** [comment]
在 page component 中用 react-helmet 处理。

**Comment by Evin-An** [comment]
加入了meta信息也只是动态的吧，还是不能被百度监测到
