### ISSUE TITLE
umi g page test  .hexString is not a function

### ISSUE THREAD

**Issue by chen2aaron** [umijs/umi#2028]
$ umi g page test    
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: (0 , _randomColor.default)(...).hexString is not a function
```
修改下面文件 hexString -> hex 就可以工作了
umi-build-dev/lib/plugins/commands/generate/generators/page/index.js:45:44

**Comment by sorrycc** [comment]
我试过（用 yarn）没有问题，应该是你安装依赖的问题，导致 random-color 使用了错误的 color 版本。random-color 用的是 [0.x 的 color](https://github.com/mock-end/random-color/blob/master/package.json#L47)，而这个 color 版本是有 [hexString 方法](https://github.com/Qix-/color/blob/0.12.0/index.js#L152)的。

**Comment by sorrycc** [comment]
有问题再 reopen。
