### ISSUE TITLE
umi dev开发环境下启动首页空白也不报错

### ISSUE THREAD

**Issue by Cslove** [umijs/umi#2035]
用umi替换之前项目内部的构建工具，按文档替换下来之后使用umi dev启动首页一直空白，也不报错，其他路由正常
umi版本：2.5.5 
困扰挺久后经过层层排查后是因为在项目根目录下的public文件夹下有个index.html文件，导致首页空白，删掉即正常
不知算不算是个问题～

**Comment by sorrycc** [comment]
不算，这是符合预期的，public 下的文件会自动 copy 到 dist 下。
