### ISSUE TITLE
umi安装之后命令无法使用

### ISSUE THREAD

**Issue by TonyLiuYan** [umijs/umi#2039]
步骤如下：
1.`yarn global add umi`
2.`yarn global bin` 获得路径`D:\Program Files\nodejs\node_global\bin` 加入环境变量PATH中
3.`umi -v`:提示 ：文件名、目录名或卷标语法不正确。

**Comment by TonyLiuYan** [comment]
使用cnpm安装后就可以使用了

**Comment by OOAngelOO** [comment]
我也出现了这个问题，最后的原因是环境变量配的不对。yarn global bin获得的并不一定是对的路径。要找到正确的路径可以搜索umi.cmd文件。由于之前不断的装umi可能会有很多。可以在每一个umi.cmd所在的文件夹打开cmd(在此文件夹打开控制台)，如果可以运行umi -v。那么这个文件夹路径就应该是umi路径。系统环境变量中写这个路径就可以运行成功。

**Comment by jiang1576** [comment]
看看D:\Program Files (x86)\nodejs\node_global\node_modules文件夹下面有没有名为umi文件夹吧，主要的资源都在这个文件夹中。我就是yarn global add umi后，umi -v:提示 ：文件名、目录名或卷标语法不正确。然后发现其实并没有这个文件，说明umi并没有被下载。
