### ISSUE TITLE
动态路由点击浏览器返回按钮不能返回上一个页面

### ISSUE THREAD

**Issue by dkvirus** [umijs/umi#2040]
# 问题

配置动态路由如下：

```
{ path: '/user/:id?', component: './User/index' },
```

实际浏览器地址切换了好几个用户的信息：

```
http://localhost:8000/user/dGl0bGU956ys5LiJ5Liq5pS55oiQ56ys5Zub5LiqMTImaWQ9NTM=
http://localhost:8000/user/dGl0bGU95rWL6K+V55uu5b2VMyZpZD05Mg==
http://localhost:8000/user/dGl0bGU956m655qE5o+P6L+wMSZpZD04Nw==
```

可以看到每个 url 地址都是不一样的，问题是点击浏览器地址栏返回按钮，页面并没有返回到上一个页面。

猜测：动态路由的跳转没有添加到路由栈中，导致没有监听到路由跳转。

这种场景应该用的还不少，简书的每个用户主页也是这种动态路由方式。

```
https://www.jianshu.com/u/52f65070ab9d
```

**Comment by imhele** [comment]
不会吧，我这里用的没问题，你切换路由使用的什么方式？

**Comment by dkvirus** [comment]
@imhele 浏览器返回按钮，左上角那个箭头

**Comment by xiaohuoni** [comment]
提供一个重现demo，我这边没问题

**Comment by sorrycc** [comment]
重现后再 reopen。

**Comment by imhele** [comment]
请选择以下任意一种方式检查代码，~~如有问题再 reopen ~~：
1. 在顶层 layout 中使用 `console.log(props)` 检查路由是否改变
2. 在 dva 中订阅 history 监听并 `console.log()` 检查路由
3. 在对应未发生变化组件的 `componentDidUpdate` 中 `console.log` 任意值，检查路由改变时组件是否更新
大部分情况下是以下两种情况：
- 上层组件使用了 `PureComponent` 或者 `shouldComponentUpdate` 阻止了子组件的更新
- fetch 逻辑写在了 `constructor` 或 `componentWillMount` ，路由切换后没有销毁组件，而只是 udpate 组件，导致没有更新数据

**Comment by dkvirus** [comment]
楼上 imhele 正解。

按浏览器返回按钮，地址栏地址是有变化的，但页面没有重新渲染。子组件调用了 componentWillMount 方法。最终解决方法是在订阅中监听路由变化重新发请求。
