### ISSUE TITLE
如何在前端部分获得配置的 routes 属性

### ISSUE THREAD

**Issue by gh-0** [umijs/umi#2044]
我需要根据配置的路由（config.js 中的 routes 属性）制作一个左侧菜单。我不知道如何在前端代码（浏览器环境）中获取routes

**Comment by sorrycc** [comment]
`window.g_routes`。

**Comment by qq645381995** [comment]
> `window.g_routes`。

不能放到 props 中吗？

**Comment by axolo** [comment]
为什么不把一些框架公用的必要的参数和变量已用户可以方便获取的方式存放或提供接口呢，比如store、app、routes、route、config、middleware、plugin，而要去污染window呢？感觉很松散，缺乏严谨性和系统性。
