### ISSUE TITLE
exit code 137.（small memory）

### ISSUE THREAD

**Issue by anlia260** [umijs/umi#2046]
## Env:
> nodejs@8.11.1
> yarn@1.12.3

## When
umi build

## Then
19915 Killed，and exit code 137.

![image](https://user-images.githubusercontent.com/11311553/53649941-55877f80-3c7e-11e9-9978-3dc83eab0d7c.png)

## But
umi dev successed.
![image](https://user-images.githubusercontent.com/11311553/53650241-07bf4700-3c7f-11e9-9d7c-6ebce2eb45e1.png)

## Centos
![image](https://user-images.githubusercontent.com/11311553/53650169-e65e5b00-3c7e-11e9-8ec7-22b4888b0804.png)

**Comment by sorrycc** [comment]
This is due to uglifyjs, and `umi dev` does not do the uglifyjs.

Try the the following method:

1. Increase memory
2. Don't compressed 
3. Try external some dependencies
