### ISSUE TITLE
create-umi使用ant-design-pro报错

### ISSUE THREAD

**Issue by miuchan** [umijs/umi#2049]
操作系统：macOS
Node版本：v11.1.0
Yarn版本：1.12.3
报错：
```yarn create v1.12.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "umi > react-loadable@5.5.0" has unmet peer dependency "react@*".
warning "umi > umi-build-dev > af-webpack > eslint-config-umi > eslint-config-react-app@3.0.6" has unmet peer dependency "babel-eslint@9.x".
[4/4] 📃  Building fresh packages...
success Installed "create-umi@0.10.0" with binaries:
      - create-umi
? Select the boilerplate type ant-design-pro
> git clone https://github.com/umijs/ant-design-pro --depth=1 ./
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Command failed: git clone https://github.com/umijs/ant-design-pro --depth=1 ./
fatal: destination path '.' already exists and is not an empty directory.


    at makeError (/Users/hackplan/.config/yarn/global/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/hackplan/.config/yarn/global/node_modules/execa/index.js:278:16)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/hackplan/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:433:22)
    at processImmediate (timers.js:632:19)
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-umi
Arguments:
Directory: /Users/hackplan/Developer/website
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.```

**Comment by miuchan** [comment]
不能在一个已有的git仓库中创建项目

**Comment by watsonhaw** [comment]
@miuchan 需要怎么处理呢？我也是碰到了这个问题呢

**Comment by missmimia** [comment]
> @miuchan 需要怎么处理呢？我也是碰到了这个问题呢

我是新建了个空白文件夹，在里面新建项目就阔以了，你可以试试看。

**Comment by Lpbzzz** [comment]
webstrom生成的.idea文件夹都会影响，删除掉.idea就能创建了

**Comment by mhdrad** [comment]
could you guys give us (non-china users) a conclusion for how to resolve bugs like this in English? I'm really tired of translating docs 😫

**Comment by mhdrad** [comment]
For resolve this error, you have to run `yarn create umi` in a **blank folder**.

**Comment by PaulPCIO** [comment]
i agree would be great to see errors in english.

**Comment by ClausClaus** [comment]
I ran into the same problem and the solution was to give the empty folder together to UMI to create
![image](https://user-images.githubusercontent.com/21154310/79033336-0aa99c80-7be0-11ea-8a81-2505a53f1ac1.png)

**Comment by marfotony** [comment]
Thanks @ClausClaus . Your option actually did the fix..

**Comment by cuicuicuinice** [comment]
> I ran into the same problem and the solution was to give the empty folder together to UMI to create
> ![image](https://user-images.githubusercontent.com/21154310/79033386-755ad800-7be0-11ea-813a-ca5632251201.png)

正解，通过npm create umi ant-design-app 自动创建一个ant-design-app的目录，clone下来的代码也会进ant-design-app，就不会有这种报错了

**Comment by Superb-x** [comment]
Windows，如果是报xxx is already exist。确保文件夹是空的，如果报 git: Functonal ...，那就先别用系统自带的cmd终端，用git bash跑，就可以了。

**Comment by zengqi** [comment]
空文件夹还是会报错，可以加 sudo 
加了 sudo 装依赖又会报错这个时候再用 chown 改成自己的用户名和用户组就好了
