### ISSUE TITLE
umi_env 目前好像是覆盖方式，可以支持合并方式吗

### ISSUE THREAD

**Issue by yuicer** [umijs/umi#2050]
如果有 .umirc.prod.js 和 .umirc.js的话，.prod plugins 选项很容易需要写很多重复的配置。

能否支持 merge 方式，这样在 .umirc 中写基本的 plugins ，然后在 .prod 中添加额外需要的配置。
这种类似于 webpack merge 的形式应该更好一点把？

**Comment by sorrycc** [comment]
你可以在 .umirc.prod.js 里 import .umirc.js 的内容，然后做合并。

**Comment by yuicer** [comment]
@sorrycc ，好的，谢谢
