### ISSUE TITLE
app.js 新增插件打包之后没有新增的插件

### ISSUE THREAD

**Issue by jinyindu** [umijs/umi#2051]
![image](https://user-images.githubusercontent.com/18224886/53726583-3587d400-3ea9-11e9-908a-f911c68ce090.png)
![image](https://user-images.githubusercontent.com/18224886/53726652-65cf7280-3ea9-11e9-9bcc-de19fc273a54.png)

**Comment by jinyindu** [comment]
![image](https://user-images.githubusercontent.com/18224886/53726697-7849ac00-3ea9-11e9-8a8b-c485363848e7.png)
yuxiang预想效果这样 不知道在那个地方配置

**Comment by sorrycc** [comment]
理论上可运行，跑步起来给个可复现例子。

**Comment by jinyindu** [comment]
大佬 有使用过single-spa-react dva 微前端结合使用吗

**Comment by sorrycc** [comment]
参考 umi-example-monorepo

**Comment by Fantasy9527** [comment]
@jinyindu  可以的,我这里给出接入方法,请参照使用
https://alili.tech/archive/9xuojm75d2a/
