### ISSUE TITLE
请问请求失败后，怎么关闭loading的层

### ISSUE THREAD

**Issue by tanzhihang** [umijs/umi#2054]
loading 是用antd-mobile的ActivityIndicator做的
在全局layout中通过state的loading.global控制，但是如果请求失败，一直显示loading，怎么手动关闭loaing

**Comment by sorrycc** [comment]
dva? 加上 `onError` 应该就好了吧。

**Comment by tanzhihang** [comment]
> dva? 加上 `onError` 应该就好了吧。

我在fetch请求中已经有做catch的处理，但是loading的state怎么改变
dva.js 中的onError并没有执行到

**Comment by sorrycc** [comment]
给复现步骤吧。
