### ISSUE TITLE
如何配置多个可选的路由参数

### ISSUE THREAD

**Issue by gh-0** [umijs/umi#2058]
“/info/:type?/:id?”

**Comment by sorrycc** [comment]
有什么问题？

**Comment by gh-0** [comment]
我用的是 antd pro，配置参数路由生成menu链接有点奇怪。原来这是antd pro的原因
https://pro.ant.design/docs/router-and-nav-cn#%E5%B8%A6%E5%8F%82%E6%95%B0%E7%9A%84%E8%B7%AF%E7%94%B1
