### ISSUE TITLE
别名设置不生效

### ISSUE THREAD

**Issue by HengzheLi** [umijs/umi#2060]
使用 chainWebpack 的形式，在单独的js文件中导出的配置，试了以下两种方式，都没有生效

`config.resolve.alias.set('*', path.resolve(__dirname,'../src'));
    
    config.alias({
        '*': path.resolve(__dirname,'../src')
    });`

使用命令umi build的时候提示These dependencies were not found:

**Comment by sorrycc** [comment]
[sorrycc-H79a7B.zip](https://github.com/umijs/umi/files/2939426/sorrycc-H79a7B.zip)
试了下没发现问题。

**Comment by sorrycc** [comment]
有问题再 reopen。
