### ISSUE TITLE
Optimize umi split chunk - 提供代码分割的最佳实践

### ISSUE THREAD

**Issue by yutingzhao1991** [umijs/umi#2063]
## 概述

之前做了一个 splitChunk 的调研，见 https://github.com/frontend9/fe9-library/issues/242 。当前 umi 的 splitChunk 的策略个人感觉并不是最优的（所有的 node_modules 下的内容都会打到一个 vendors.async.js 中，并没有按照路由去做 splitChunk）。

个人的想法是通过插件提供一个 splitChunk 的最佳实践，这个最佳实践可以通过配置提供一定程度的自定义选择。比如是否要 external 就可以通过一个配置自动选择，这样对于在意构建速度或者在意网络依赖两种情况下的项目就可以快速设置。

## 方案草案

可以通过一个 umi-plugin-splitchunk 来实现该优化（后面也可以考虑内置到 umi 或者在 af-webpack 中实现）。基本的思路是：

- 类似 react, react-dom 这样基本没有路由都会用到的第三方包单独抽取到一个 initial chunk(common.js) 中，这样可以提高这个 chunk 的缓存命中率（业务代码和 umi 升级都不会导致这个 chunk 的 hash 改变）。
- 只有部分路由会用到的比较大的，更新频率比较低的包可以单独打成 async 的 chunk，比如 g2，和上一条规则类似，也是为了提高缓存命中率。
- 其它的 async 的 chunk 按照默认的逻辑抽取即可（需要把当前 umi 默认的 name 为 vendors 去掉，改为自动的），但是支持按照项目实际情况配置 minSize 等（只有在开启动态加载的情况下有效）。

### 使用示例

```js
export default {
  plugins: [['umi-plugin-splitchunk', {
    initialCommonIncludes: ['react', 'react-dom'], // 哪些包要默认打到 common.js 中
    asyncChunkOption: {
      minSize: 30000, // 被抽出来的 chunk 至少 30k， 和 webpack 默认值保持一致
      maxAsyncRequests: 5, // 没有路由对应的 chunk 数不超过 5 个
      minChunks: 1,
      independentChunks: {
        chart: ['g2', 'biz-charts'], // 这样的话 g2 和 biz-charts 会被指定的打到一个 chart.async.js 中
      },
    },
  }]],
};
```

最终的文件示例（对应 css 也应该有一份）：

- common.js // 包含 react react-dom 这些，需要在 html 中直接引入
- umi.js
- p__a.js // a 页面
  - xxxx.async.js
  - xxxx2.async.js
- p__b.js // b 页面
  - chart.async.js
  - xxxx.async.js
  - xxxx3.async.js 

## 相关 ISSUE

- https://github.com/frontend9/fe9-library/issues/242
- https://github.com/ant-design/ant-design-pro/pull/3650

**Comment by qzmer1104** [comment]
同意，方向上有意义，一个线上项目，没有使用其他包，打出来有近5m+，gzip还有800k，这个问题当时还困扰了一会，改成异步引入时，有问题，没那么多时间折腾框架，最终强忍的大小上线。

**Comment by ch-liuzhide** [comment]
很有意义，学习。感觉webpack这边很有技术细节啊

**Comment by zhilianbi520** [comment]
需要这样的插件。。。vendors.async.js文件已经快2M了。

**Comment by peakandyuri** [comment]
安装umi-plugin-splitchunk报没找到

**Comment by jcedo** [comment]
> 同意，方向上有意义，一个线上项目，没有使用其他包，打出来有近5m+，gzip还有800k，这个问题当时还困扰了一会，改成异步引入时，有问题，没那么多时间折腾框架，最终强忍的大小上线。

冒昧请教一下 异步引入是指？首屏加载并发加载资源吗？还是有其他的方法？
目前打包出来的umi.js 在首屏加载大小为700kb左右

**Comment by zhangyuang** [comment]
应该先用analyzer去分析包里到底包含什么东西，表示没有正确的开启tree shaking再怎么分割也是白搭还是那么大。路由组件分割只加载首屏组件代码在绝大多数的情况下已经够用。

**Comment by peakandyuri** [comment]
我之前首次加载gzip之后也是1.6兆，在chainWebpack里面修改splitChunks配置，将一些不必要的组件剔出vendors，现在gzip之后也就700KB左右，不太好切割了，因为umi和antd两个就差不多要占这么多大小了

**Comment by wangyazhen** [comment]
`umi-plugin-splitchunk` 在研发中了吗

**Comment by hsxfjames** [comment]
在 `umi-build-dev` 里没有找到拆包相关配置，感觉应该是用了 webpack 默认的 vendors 分包。目前在我的场景中，页面或组件的 chunk 基本上不是 initial 的，所以可以直接把 vendors 禁掉，并在 async 里面拆 common 出来。

```
config.optimization.splitChunks({
    cacheGroups: {
        common: {
            name: 'common-async',
            minChunks: 2,
            chunks: 'async',
            reuseExistingChunk: true,
        },
        vendors: false,
    },
});
```

当然上面的配置也并不是最优。假如有 A B C 三个异步页面， `minChunks: 2` 会导致 A 页面不仅加载 A B 共有的依赖，也会加载 B C 共有的（但对 A 来说不是必要的）。我们实际配置比这要复杂得多。

个人感觉没必要实现一个 `umi-plugin-splitchunk` 插件，因为它做的事情跟 `optimization.splitChunks` 是一样的，高度封装带来的效益似乎只是减少而非简化配置。还不如期待一下 `webpack@5` 的分包策略是否有足够的提升。

**Comment by Ryuurock** [comment]
> 很有意义，学习。
> ps:请教楼主个问题，我引入了一个富文本编辑器breaft-editor，按照楼主的方法，我提取了它到viz.async.js。但是富文本编辑器所依赖的其它包没有一起打过来，还在vendors那边，这种情况是因为什么，我要怎么做。 @yutingzhao1991

解决了吗

**Comment by chj-damon** [comment]
@yutingzhao1991 请问这个提案怎么样了？

**Comment by yuanguandong** [comment]
我是这样做的，大的第三方库完全不走编译，用最原始的按需加载第三方production版本的方式，
![20210322103235](https://user-images.githubusercontent.com/13197560/111933359-42140f00-8afa-11eb-9d3d-29ab1674c2e3.jpg)
![20210322103421](https://user-images.githubusercontent.com/13197560/111933366-45a79600-8afa-11eb-90e4-d0001c894caf.jpg)

**Comment by 77629296** [comment]
没找到相关的插件，因为多个项目用到，每个手动配一遍太累。so，自己搞了一个，根据chunks配置自动分包，可以交流一下
[@rainbowfish/umi-plugin-chunks](https://www.npmjs.com/package/@rainbowfish/umi-plugin-chunks)

![效果预览](https://tva1.sinaimg.cn/large/008i3skNly1gpvnu2k46uj31n50u01kx.jpg)

**Comment by xuchao996** [comment]
Mark

**Comment by iceberg211** [comment]
学习了
