### ISSUE TITLE
umi-lib build 不支持 import 目录

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#2065]
![image](https://user-images.githubusercontent.com/7939085/53946532-fa7ede00-40fe-11e9-8455-89da817a06e9.png)
重现步骤：拉取代码https://github.com/umijs/umi-plugin-library/tree/master/packages/docz-theme-antd
定位到docz-theme-antd文件夹
1. yarn add  umi umi-library -D
2.scripts中添加 "build": "umi-lib build --esm --cjs --umd"
运行 出现上图所示错误

**Comment by clock157** [comment]
看起来是 rollup 的 resolve 插件没有配置 `extensions` 的原因。

**Comment by xiexingen** [comment]
> rollup

有没处理办法

**Comment by soolx** [comment]
我也遇到了，后面加/index可以暂时解决

**Comment by clock157** [comment]
我提个 pr 会修复这个问题。
