### ISSUE TITLE
不支持https

### ISSUE THREAD

**Issue by landfei** [umijs/umi#207]
现在配置不支持https,希望能支持

**Comment by paranoidjk** [comment]
你是指哪里不支持 https? 云凤蝶部署吗？

**Comment by sorrycc** [comment]
没明白，先 close 了，有问题再 reopen 。

**Comment by landfei** [comment]
说的不是很清楚,本地调试的时候希望有参数可以开启https服务模式.

**Comment by sorrycc** [comment]
本地为啥要用 https ?

**Comment by landfei** [comment]
现在需要调试H5移动端定位,需要https支持
