### ISSUE TITLE
TypeError: exports[name].indexOf is not a function 更新css-loader版本

### ISSUE THREAD

**Issue by mllw** [umijs/umi#2070]
在umi里css-loader的版本是锁定在1.0.1
在这个版本里，css-loader的dependencies 模块postcss-modules-scope存在不能处理css的名字为.constructor的style 。postcss-modules-scope的BUG在2.0.1版本解决，对应的css-loader版本为2.1.1

**Comment by sorrycc** [comment]
所以复现步骤是写一个 `.constructor {}` 的就会报错？

**Comment by mllw** [comment]
对，只要一个简单的style，就报错
.constructor {
    background: 'black'
}

**Comment by mllw** [comment]
var exports = {};

    function exportScopedName(name) {
      var scopedName = generateScopedName(name, css.source.input.from, css.source.input.css);
      exports[name] = exports[name] || [];
      if (exports[name].indexOf(scopedName) < 0) {
        exports[name].push(scopedName);
      }
      return scopedName;
    }

这是错误代码，
原因是 exports的定义是  var exports = {};
导致当name为‘constructor’时，exports[name]是exports的构造函数

**Comment by sorrycc** [comment]
先不用 .constructor 这个 class，css-loader 之前有尝试升级过，但遇到没法绕开的 break-change，等 umi@3 再考虑了。

**Comment by mllw** [comment]
使用的monaco-editor第三方库，.constructor的class在第三库中，暂时无法不用这个class，有没有办法让css-loader不加载monaco-editor里的样式
config.module.rule('css').test(/\.css/).exclude.add(path.resolve(__dirname, 'node_modules/monaco-editor')).end()
通过这样配置，不起作用。

**Comment by Klaus1995** [comment]
@mllw 现在也遇到了同样的问题，使用monaco-editor时会影响现有的样式加载，请问您是怎么解决的呢？

**Comment by mllw** [comment]
> @mllw 现在也遇到了同样的问题，使用monaco-editor时会影响现有的样式加载，请问您是怎么解决的呢？

两方案：
1、每次 npm install 后手动修改 postcss-modules-scope 模块的代码 把 var exports = {}; 修改为var exports = Object.create(null);
2、弃用umi，自己使用webpack配置
我自己现在是使用在第2条，自己配置webpack

**Comment by Klaus1995** [comment]
> > @mllw 现在也遇到了同样的问题，使用monaco-editor时会影响现有的样式加载，请问您是怎么解决的呢？
> 
> 两方案：
> 1、每次 npm install 后手动修改 postcss-modules-scope 模块的代码 把 var exports = {}; 修改为var exports = Object.create(null);
> 2、弃用umi，自己使用webpack配置，升级css-loader版本到2.1.1
> 我自己现在是使用在第2条，自己配置webpack

谢谢，后来发现需求只需要diff代码，所以换成diff2html了。。。

**Comment by sorrycc** [comment]
在 https://github.com/umijs/umi/issues/2236 跟进。
