### ISSUE TITLE
[Typescript]如何在提交时的 hook 中强制检查 TS 编译是否存在错误呢

### ISSUE THREAD

**Issue by RunningCoderLee** [umijs/umi#2073]
用 UMI 创建项目后，开发模式下可以通过设置 `FORK_TS_CHECKER` 变量值来开启 TS 校验，我想在提交 commit 时像 `ESlint` 那样对所有文件做 TS 校验，通过后才允许提交，这个要怎么实现呢？

**Comment by RunningCoderLee** [comment]
找到一个方案，在 `pre-commit` 里再添加一个运行 TS 编译检查的命令，但感觉不够优雅 🤨

~~~json
~~~

**Comment by afc163** [comment]
👍

**Comment by MinJieLiu** [comment]
tsconfig.json 中加入
```
"noEmit": true,
```
就够优雅了吧

**Comment by ChenYCL** [comment]
> ```json
> npm run ts-compile-check &&
> ```

这个不行吧，整个项目都会直接生成d.ts文件在源码目录下

**Comment by space-77** [comment]
> ```json
> "ts-compile-check": "tsc -p tsconfig.json"
> ```



> tsconfig.json 中加入
> 
> ```
> "noEmit": true,
> ```
> 
> 就够优雅了吧

把命令改一下更好
```
"ts-compile-check": "tsc --noEmit -p tsconfig.json"
```

**Comment by fzhange** [comment]
> 

这不是全量做的compile么
