### ISSUE TITLE
post 返回数据错误

### ISSUE THREAD

**Issue by AntoninSorrento** [umijs/umi#2078]
# 请求
 
![image](https://user-images.githubusercontent.com/26902024/54063197-fa3d2a80-4245-11e9-9d33-969716139e77.png)

# mock
![image](https://user-images.githubusercontent.com/26902024/54063215-0fb25480-4246-11e9-94ff-249b1721f7f0.png)

# 路由访问
![image](https://user-images.githubusercontent.com/26902024/54063225-1d67da00-4246-11e9-9001-a76acf711c20.png)

# ⚠️ API 访问：（错误❌）
![image](https://user-images.githubusercontent.com/26902024/54063249-47210100-4246-11e9-8b07-2094b60419aa.png)
期望：
![image](https://user-images.githubusercontent.com/26902024/54063255-556f1d00-4246-11e9-870b-a89eb6a94c0d.png)

# 说明：
不知道问题出在哪里，使用的axios，get请求没有问题，使用post的时候，返回的是html类数据

**Comment by xiaohuoni** [comment]
需要设置headers
```
Accept: 'application/json',
```
欢迎使用[umi-request](https://github.com/umijs/umi-request)
