### ISSUE TITLE
umi的配置有一个env选项，可以用来区分环境，希望能在文档里加上。

### ISSUE THREAD

**Issue by leijingdao** [umijs/umi#2079]

**Comment by leijingdao** [comment]
要去配置production环境下的babel plugin，使用 extraBabelPlugins  不能区分环境。翻了文档，又没有发现方法。 还是通过翻源码找到了，还有一个env选项，折腾死了。。。

**Comment by leijingdao** [comment]
> 要去配置production环境下的babel plugin，使用 extraBabelPlugins 不能区分环境。翻了文档，又没有发现方法。 还是通过翻源码找到了，还有一个env选项，折腾死了。。。

不知道 是不是文档是有，我没有发现。。。

**Comment by phyoyo** [comment]
https://umijs.org/zh/guide/config.html#umi-env

**Comment by leijingdao** [comment]
`
export default {
  plugins,
  env: {
    production:{
      extraBabelPlugins: ['transform-remove-console'],
    }
  },
  define: {
    APP_TYPE: APP_TYPE || '',
  },
  treeShaking: true,
  targets: {
    ie: 11,
  },
 ...
`
发现还可以这样配

**Comment by sorrycc** [comment]
实现 production 环境下添加 babel 插件有多种方式，

1. env 配置，之前 roadhog 的方式，由于没有做 merge 处理，我觉得比较冗余，所以没在文档里露出
2. 跟进 process.env.NODE_ENV === 'production' 判断
3. 写多个 config，比如 config/config.prod.js，然后通过 UMI_ENV=prod 运行 umi dev 或 umi build

推荐用 2 或者 3 吧。

**Comment by leijingdao** [comment]
> 实现 production 环境下添加 babel 插件有多种方式，
> 
> 1. env 配置，之前 roadhog 的方式，由于没有做 merge 处理，我觉得比较冗余，所以没在文档里露出
> 2. 配置文件里通过编程的方式判断 process.env.NODE_ENV === 'production' 区分处理
> 3. 写多个 config，比如 config/config.prod.js（用 .umirc.js 的话是 .umirc.prod.js），然后通过 UMI_ENV=prod 运行 umi dev 或 umi build
> 
> 推荐用 2 或者 3 。

👌
