### ISSUE TITLE
firefox 45.0版本运行出错

### ISSUE THREAD

**Issue by fake-car** [umijs/umi#2082]
错误日志
![177456bb4ccc6335b2543f9c54489b47](https://user-images.githubusercontent.com/13540489/54099465-707f8f80-43f4-11e9-84d0-c59cac130630.jpg)
查了一下iterator的支持版本
![图片](https://user-images.githubusercontent.com/13540489/54099531-bc323900-43f4-11e9-9e34-82f3d2df511b.png)

**Comment by fake-car** [comment]
targets使用的是默认的值

**Comment by sorrycc** [comment]
给下复现步骤。

**Comment by fake-car** [comment]
> 给下复现步骤。

我使用firefox45.0打开运行后的网页时候报的错，

**Comment by sorrycc** [comment]
`yarn create umi` 创建的项目不做修改能复现？

**Comment by fake-car** [comment]
> `yarn create umi` 创建的项目不做修改能复现？

是的 我刚复现了一次

**Comment by sorrycc** [comment]
firefox 45 太老了，默认配置应该没覆盖，targets 配上 `{ firefox: 45 }` 试试。

**Comment by fake-car** [comment]
> firefox 45 太老了，默认配置应该没覆盖，targets 配上 `{ firefox: 45 }` 试试。

targets的设置除了firefox45之外，我试了比`{ firefox: 45 }`低的几个版本都运行成功了，`{ firefox: 45 }`会报这个错误

**Comment by sorrycc** [comment]
有问题再 reopen。
