### ISSUE TITLE
请问Redirect的时候报这个警告怎么解决的？

### ISSUE THREAD

**Issue by youngsailor** [umijs/umi#2087]
Warning: You tried to redirect to the same route you're currently on

**Comment by sorrycc** [comment]
提示很明确了。

**Comment by li2215890610** [comment]
![image](https://user-images.githubusercontent.com/19567679/54668303-89412100-4b29-11e9-908f-6e1e1081c862.png)

你是不是也是这样配置路由才导致这个警告

**Comment by oldashes** [comment]
同样的问题，这个提示并不能定位问题。@sorrycc

**Comment by steveleeh** [comment]
我也遇到这个问题，难道这种写法不支持吗

**Comment by steveleeh** [comment]
@oldashes 解决了
![image](https://user-images.githubusercontent.com/19660631/60314701-34b60900-9996-11e9-9b13-d7717af495f2.png)
放在根级下面重定向就行了

**Comment by atzcl** [comment]
@sorrycc  如果放在根级去重定向的话，会发生 layout rerender 的，界面闪烁很明显

**Comment by Lmangoxx** [comment]
同样的问题，参照ant-design-pro写的，路由权限拦截老是会走2次，路由权限这块官方文档介绍的太少了
