### ISSUE TITLE
对于window用户严重不友好

### ISSUE THREAD

**Issue by Helovebai** [umijs/umi#2089]
## What happens?
在window上安装 yarn，完了add umi， 接着umi -v 就报错了，command not found。

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by imhele** [comment]
**0**. 阅读文章 https://zhuanlan.zhihu.com/p/25795393

**1**. 打开 Explorer ，在地址栏输入 `控制面板\系统和安全\系统` 回车

![image](https://user-images.githubusercontent.com/32428655/54123453-cc6d0700-443a-11e9-9bf0-3b5b71234041.png)

**2**. 点击 `高级系统设置` => `环境变量`

![image](https://user-images.githubusercontent.com/32428655/54123901-e5c28300-443b-11e9-8b6b-867bb9950c82.png)

**3**. 在终端 [CMD / PowerShell] 中运行 `yarn global bin` ，并将输出的路径添加到 `环境变量` 的 `Path` 中

![image](https://user-images.githubusercontent.com/32428655/54123835-b9a70200-443b-11e9-88a7-fb30a53ef71b.png)

> 遇到其他问题请先尝试自行寻找解决方法或者使用搜索引擎，无法解决时再开 issue

*Tips*: Windows 不太适合开发，但进行一些额外的配置之后也是可以接受的。如果你使用的是 Windows 10 ，可以尝试安装 Ubuntu 子系统来开发，具体步骤详见各大搜索引擎。

**Comment by xiaohuoni** [comment]
我觉得还好吧，我用window也用了三四年了，没觉得有什么问题。
