### ISSUE TITLE
Umi-library doc with TypeScript build error

### ISSUE THREAD

**Issue by xiaoxiangmoe** [umijs/umi#2094]
@clock157 

## What happens?

When run umi-library doc dev with TypeScript, it throw runtime error:

> Uncaught ReferenceError: string is not defined

Because `  const [dataSource, setDataSource] = useState<Array<string>>([]);` is compiled into

```js
  var _ref = react__WEBPACK_IMPORTED_MODULE_2__["useState"] < Array < string >> [],
      _ref2 = _slicedToArray(_ref, 2),
      dataSource = _ref2[0],
      setDataSource = _ref2[1];
```

## Mini Showcase Repository(REQUIRED)

https://github.com/xiaoxiangmoe/ant-design-demos

## How To Reproduce

yarn install
yarn run doc:dev

**Comment by imhele** [comment]
试试在 library 配置文件中手动添加一项：
```ts
export default {
   doc: { typescript: true },
}
```
相关 pr #2075
