### ISSUE TITLE
proxy 代理，post请求无效

### ISSUE THREAD

**Issue by AntoninSorrento** [umijs/umi#2095]
## 起因
配置好代理后，使用axios发起post请求，地址没有替换，文档已度过，相关问题已搜索过

### 代理配置
![image](https://user-images.githubusercontent.com/26902024/54204767-e3c9f400-450f-11e9-9c3b-54517c1cfeaf.png)

### 请求
![image](https://user-images.githubusercontent.com/26902024/54204792-f6dcc400-450f-11e9-8077-0a0e9da9bfe1.png)

### 发起请求后
![image](https://user-images.githubusercontent.com/26902024/54204938-44f1c780-4510-11e9-98cb-545df056226e.png)

**Comment by xiaohuoni** [comment]
这个问题回答了好几次呢，代理的是服务，不是请求地址。
关于proxy，可以看看这个文档https://www.yuque.com/umijs/umi/proxy
