### ISSUE TITLE
线上资源代理到本地，umi dev 之后页面一直在不停地刷新

### ISSUE THREAD

**Issue by caoerguo** [umijs/umi#2097]
## What happens?

因为要查线上bug，我将静态资源代理到本地localhost上，运行的是 npm run start 执行的是umi dev，
然后页面会一直不停的重新加载，线上的端口80我不能改，请问该怎么解决

## 相关环境信息

- **Umi 版本 2.6.1**：
- **Node 版本 11.10.0**：
- **操作系统 mac os 10.14**：

**Comment by sorrycc** [comment]
配下 SOCKET_SERVER，参考 https://umijs.org/guide/env-variables.html#socket-server 。

**Comment by caoerguo** [comment]
> 配下 SOCKET_SERVER，参考 https://umijs.org/guide/env-variables.html#socket-server 。

中英文文档居然不同步 …😂

**Comment by ruohuan** [comment]
> > 配下 SOCKET_SERVER，参考 https://umijs.org/guide/env-variables.html#socket-server 。
> 
> 中英文文档居然不同步 …😂

配置了socket server后报umi is not defined，楼主有遇到吗？

**Comment by Magua-Q** [comment]
https://umijs.org/guide/env-variables.html#socket-server 
 
 链接打不开。。。

**Comment by xiaohuoni** [comment]
都几百年的帖子了，还在这挖坟。

https://umijs.org/docs/introduce/faq#%E4%BB%A3%E7%90%86%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90%E5%88%B0%E6%9C%AC%E5%9C%B0%E5%90%8E%E4%B8%80%E7%9B%B4-restart-%E5%88%B7%E6%96%B0%E9%A1%B5%E9%9D%A2

**Comment by shanhexi** [comment]
"start": "SOCKET_SERVER=http://localhost:8000 umi dev"
    配置了还是在不断的刷新，

**Comment by guoxm0903** [comment]
> ```
> "start": "SOCKET_SERVER=http://localhost:8000 umi dev"
> 配置了还是在不断的刷新，
> ```

+1
