### ISSUE TITLE
yarn create umi 运行报错，无法创建项目

### ISSUE THREAD

**Issue by lifengsbotlp** [umijs/umi#2098]
![微信截图_20190314122416](https://user-images.githubusercontent.com/29885219/54331296-65c33580-4654-11e9-87ed-445a053b1b2d.png)
系统:win7

**Comment by globalhomepage** [comment]
npm create umi

**Comment by sorrycc** [comment]
参考 https://github.com/umijs/create-umi#yarn-create-umi-command-failed
