### ISSUE TITLE
umi run  dev  卡很久 很久 然后打开localhost：8000 以后 也回等待很久 认真帮忙一下 不然本地调试真的很辛苦啊

### ISSUE THREAD

**Issue by yehoan** [umijs/umi#2099]
## What happens?

项目使用的是umi 框架  umi run dev  即启动本地服务  但是每次都很卡很久 很久
![image](https://user-images.githubusercontent.com/22631753/54331857-bfc4fa80-4656-11e9-8126-477ac4cb67c0.png)
[package.zip](https://github.com/umijs/umi/files/2964752/package.zip)

这个是项目的pacakge.Json 我真的是希望umi 更好 更流畅 

类似zhey这样 一直卡着  本地调试真的很慢
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
![image](https://user-images.githubusercontent.com/22631753/54331929-0155a580-4657-11e9-8494-5f2e43d91e7a.png)

## 相关环境信息

- **Umi 版本**：1.00
- **Node 版本**：10.13
- **操作系统**：win10

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/54333117-37e1ef00-465c-11e9-83ce-2109a6748ebf.png)
这个是项目结构 我也没看见哪里有config

**Comment by ikobe** [comment]
https://umijs.org/config/#externals

https://webpack.js.org/configuration/externals

这两个可以了解一下，然后配置起来。应该会快不少

**Comment by sorrycc** [comment]
先参考[文档](https://umijs.org/zh/guide/migration.html)升级到 umi@2 吧，从 webpack@3 到 webpack@4 差很多的。
