### ISSUE TITLE
mock的路由中识别？

### ISSUE THREAD

**Issue by TRUEJASONFANS** [umijs/umi#2101]
例如 http://localhost:8000/api/dashboard?page=1&limit=20
我的写法是：
`  
'GET /api/dashboard?page=1&limit=20':[
    { ticketNum: "001", title: "www", desc: "pxxxxxxx", storyPoint: 3 },
    { ticketNum: "002", title: "create xxx", desc: "caaaaaaa", storyPoint: 5 },
  ]
`
但是这个mock 的api并不会成功，而是返回404错误

## 最小可复现仓库

https://github.com/TRUEJASONFANS/sprint-pocker-front

## 相关环境信息

- **Umi 版本**：2.1.2
- **Node 版本**：v10.15.1
- **操作系统**：win10

**Comment by sorrycc** [comment]
GET 的 key 里不要加 querystring，改成 `GET /api/dashboard`。

**Comment by TRUEJASONFANS** [comment]
oh. 我明白了. 当作options 传递？
`export async function request(url, options) {

  console.log('url', url);
  console.log('options', options);

  try {
    const response = await fetch(url, options);

    console.log('response', response);

    checkStatus(response);

    //await 异步回调方法。 以写同步的方式写异步回调
    const data = await response.json();
    
    console.log("in the request", data);

    const ret = {
      data,
      headers: {},
    };

    if (response.headers.get('x-total-count')) {
      ret.headers['x-total-count'] = response.headers.get('x-total-count');
    }

    return ret;
  } catch (error) {
    console.error(error);
    return {}
  }
}`
