### ISSUE TITLE
组件发起的 dispatch 没有生效。

### ISSUE THREAD

**Issue by xiashuyuan** [umijs/umi#2103]
## What happens?
通过 yarn create umi 生成的 pro 项目，页面上发起 dispatch 后，model 没有生效，没有进入 effects，reducer 进入但没有合并。
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1. 组件在 pages/DataDev/LinkTrace/index.js 
2. model 在pages/DataDev/LinkTrace/models/linkTrace.js
3. 点击链路追踪中的搜索按钮，分别发起一个 effects/fetch 和 reducers/save 

**Expected behavior**
1. 发起 fetch 对应的 http 请求
2. 执行 save 对应的合并

## Context

- **Umi Version**: 2.5.0
- **Node Version**: v8.12.0
- **Platform**: mac os 10.14.3 (18D109)

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/54339786-c52f3e80-4670-11e9-8972-fb923ab6b984.png)

试了下，正常。

**Comment by xiashuyuan** [comment]
> ![image](https://user-images.githubusercontent.com/35128/54339786-c52f3e80-4670-11e9-8972-fb923ab6b984.png)
> 
> 试了下，正常。

感谢云谦，已解决，非框架问题。

**Comment by Mh2336393** [comment]
> > ![image](https://user-images.githubusercontent.com/35128/54339786-c52f3e80-4670-11e9-8972-fb923ab6b984.png)
> > 试了下，正常。
> 
> 感谢云谦，已解决，非框架问题。

我也遇到类似得问题 升级umi3 后出现得之前重来没遇到过
