### ISSUE TITLE
How to configure extraBabelIncludes

### ISSUE THREAD

**Issue by ljxyweb** [umijs/umi#2117]
## What happens?

When I build the project ，I came across an error.
umi.29aa9bc5.js from UglifyJs
Unexpected token: keyword (const) [umi.29aa9bc5.js:717,0]

I found that there is a problem with @sccbafe/sccba-js-api，so I use extraBabelIncludes
![image](https://user-images.githubusercontent.com/20186491/54505063-4d635b80-4971-11e9-98cb-a3699143ffb5.png)
![image](https://user-images.githubusercontent.com/20186491/54505078-5bb17780-4971-11e9-914a-1bea3d9a7e30.png)

But the problem still exists

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.hope build project success
2.

## Context

- **Umi Version**:2.6.1
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
It's better to make a PR to [es5-imcompatible-versions](https://github.com/umijs/es5-imcompatible-versions).

**Comment by ljxyweb** [comment]
Is extraBabelIncludes invalid?

**Comment by ljxyweb** [comment]
How can I view the detailed packaging error log?

**Comment by sorrycc** [comment]
You can use extraBabelIncludes, but the path may not be `node_modules/@sccbafe/sccba-js-api`, it's related to the package manager tool you use.

**Comment by ljxyweb** [comment]
I use yarn ,so how do I determine the path?

**Comment by sorrycc** [comment]
You can use extraBabelIncludes as function, 

e.g.

```js
export default {
  extraBabelIncludes: [
    (filePath) => true | false,
  ]
}
```

**Comment by ljxyweb** [comment]
I use 
`extraBabelIncludes: [filePath => filePath]`


I have solved my problem.Thank you

**Comment by dkvirus** [comment]
@ljxyweb  hi, bro. How did you solve the problem, can you intro detail.

How can I modify the following code. hope your reply.

```
extraBabelIncludes: [
    "node_modules/org"
  ],
```

**Comment by inTheSun** [comment]
> @ljxyweb hi, bro. How did you solve the problem, can you intro detail.
> 
> How can I modify the following code. hope your reply.
> 
> ```
> extraBabelIncludes: [
>     "node_modules/org"
>   ],
> ```
const path = require('path');
extraBabelIncludes:[
    path.resolve(__dirname, '需要babel解析的文件相对与当前代码所在文件的相对地址')
  ],
