### ISSUE TITLE
[RFC] Warn user if have react-router or react-router-dom in package.json

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#2120]
## 背景

参考 [sorrycc/blog#82](https://github.com/sorrycc/blog/issues/82)，由于 umi 现在允许用户自定义 react-router-dom 等库的版本，所以可能会出现不一致。比如 react-router 和 react-router-dom 版本不一致时会出现问题。

## 思路

几个方案：

1. 启动之前做一些检测，包括这个路由版本不一致的问题，提醒用户
2. 不支持 react-router 和 react-router-dom 的版本自定义

有点倾向方案 2 。

## 跟进

- [ ] PR

**Comment by imhele** [comment]
使用 umi-plugin-react 额外引入不同版本的 umi-plugin-locale 也会出现同类问题

**Comment by xiaohuoni** [comment]
路由这一块还是放在umi统一管理，没什么好选择的。一些组件和工具类包，可以允许用户自定义版本

**Comment by yutingzhao1991** [comment]
+1 react-router 和 react-router-dom 感觉没有什么理由要支持用户自定义，我理解路由这块 react-router 都应该是对用户不可见的。

@imhele 说的问题应该就可以用 `启动之前做一些检测，包括这个路由版本不一致的问题，提醒用户` 这个来解决。

**Comment by sorrycc** [comment]
已锁定。
