### ISSUE TITLE
使用umi创建项目 antd 在只引入DatePicker 组件的时候样式丢失

### ISSUE THREAD

**Issue by DragonT** [umijs/umi#2121]
## What happens?
使用umi创建项目antd 在只引入DatePicker 组件的时候样式丢失，如果使用了Form组件或者Input组件的话样式是正常的。 使用create-react-app创建项目中使用antd的DatePicker 组件的时候都没有这个问题。

![11](https://user-images.githubusercontent.com/7319029/54537195-14f16b00-49cd-11e9-8726-cce17f87972a.PNG)

## 相关环境信息

- **Umi 版本**：2.4.4
- **Node 版本**：11.4.0
- **操作系统**：windows

**Comment by yutingzhao1991** [comment]
配置了 `umi-plugin-react` 里面的 antd 了吗？或者加上 bable-plugin-import。

**Comment by DragonT** [comment]
> 配置了 `umi-plugin-react` 里面的 antd 了吗？或者加上 bable-plugin-import。

`umi-plugin-react` 里面配置了的 使用yarn create umi创建的里面选择了antd

**Comment by sorrycc** [comment]
给复现步骤。

**Comment by DragonT** [comment]
yarn create umi 
Select the boilerplate type 选择 app
What functionality do you want to enable? 选择 antd、dva、dll、internationalization 
page目录中的index.js 只引入DatePicker 使用<DatePicker/>组件
复现仓库 [https://github.com/DragonT/umitest](url)

**Comment by yutingzhao1991** [comment]
trace in https://github.com/ant-design/ant-design/issues/15483
