### ISSUE TITLE
是否可以支持对model的扩展

### ISSUE THREAD

**Issue by 545682879** [umijs/umi#2122]
![image](https://user-images.githubusercontent.com/15208098/54573035-69283980-4a25-11e9-80db-bdbc05be4751.png)
使用的是如下处理的model：
return { namespace: 'client',...m.default}

是否可以添加一个配置选项，传入函数extendModel，对model做额外处理，类似
return extendModel({ namespace: 'client',...m.default})

**Comment by sorrycc** [comment]
在 model 内部扩展好导出吧。
