### ISSUE TITLE
[RFC] 规范的 eslint 规则

### ISSUE THREAD

**Issue by DiamondYuan** [umijs/umi#2123]
## 背景

> 描述你希望解决的问题的现状，附上相关的 issue 地址

eslint 规范化。规范全部的阿里前端项目

## 思路

区分四个包
+ js
+ ts
+ react
+ ts

js为基础的规则，每一条 eslint 的规范都配置上，并且说明原因。
react 使用 eslint-plugin-react ，继承 js 的规则的基础上配置专属规则
ts 使用 @typescript-eslint ，继承js的规则，覆盖一些冲突的。
react-ts继承 react 和 ts。

**Comment by DiamondYuan** [comment]
https://github.com/DiamondYuan/eslint-config

**Comment by DiamondYuan** [comment]
https://github.com/umijs/umi/issues/2024

**Comment by yutingzhao1991** [comment]
在做 https://github.com/umijs/umi-lint 这个，会升级 eslint-config-umi 作为规范。内部统一的话可以内部 Bigfish 群里面沟通。

**Comment by DiamondYuan** [comment]
> 在做 https://github.com/umijs/umi-lint 这个，会升级 eslint-config-umi 作为规范。内部统一的话可以内部 Bigfish 群里面沟通。

看了一下，这个是 lint 工具，似乎不包含 lint 规则。

**Comment by xiaohuoni** [comment]
这个规范会在eslint-config-umi里面维护的吧

**Comment by DiamondYuan** [comment]
> 这个规范会在[eslint-config-umi](https://github.com/umijs/umi/tree/master/packages/eslint-config-umi)里面维护的吧

区分 ts js react react-ts ？因为很多规则会冲突。



![image](https://user-images.githubusercontent.com/9692408/54663464-4af13500-4b1c-11e9-8bf1-95135dd1b1c6.png)

**Comment by xiaohuoni** [comment]
@clock157

**Comment by clock157** [comment]
你好 @DiamondYuan ，之所以没有分离，是因为存在像 `antd-pro` 这种可能混用 ts 和 js 的项目，同时希望对用户透明，不需要额外配置也能支持 ts。一方面有个 [pr](https://github.com/umijs/umi/pull/2038) 在验证。再一方面，也在观望和等待 [eslint](https://github.com/eslint/rfcs/pull/9) 新的配置方式。

你如果有兴趣，可以对 eslint-config-umi 基于 master 重新提 pr，一起评估和验证更好的方式。
