### ISSUE TITLE
为什么我的路由器在跳转子路由的时候会报403?

### ISSUE THREAD

**Issue by shine135235** [umijs/umi#2125]
![image](https://user-images.githubusercontent.com/18108307/54579951-ca113b00-4a40-11e9-9be6-3da139a5122c.png)

**Comment by sorrycc** [comment]
没理解问题，不过 403 肯定不是前端返回的。

**Comment by superchow** [comment]
是 3.x版本吗？ 如果是，那就是 Authorized.js 判断你没登陆
