### ISSUE TITLE
umi-lib,部分依赖放在dependencies中导致打包umd时报错

### ISSUE THREAD

**Issue by NexxLuo** [umijs/umi#2126]
使用umi-lib打包组件时，某些情况下依赖如果放在dependencies中，会导致打包umd时报错，
比如下图，如果把react放在peerDependencies中就能正常打包。
 
但是peerDependencies中的依赖不会被打包到输出文件中，那么下述情况就会依赖外部的react，必须在html中另行引入react的umd文件。
 
1.
![image](https://user-images.githubusercontent.com/18549980/54584302-ebc6ee00-4a51-11e9-8eab-d2481c09e2c6.png)

2.
![image](https://user-images.githubusercontent.com/18549980/54584254-d4880080-4a51-11e9-9ab0-388f58641149.png)

 
 
## Context

- **Umi Version**:1.2.0
- **Node Version**: v10.15.3
- **Platform**: Windows 10

**Comment by clock157** [comment]
这是约定的规则： https://github.com/umijs/umi/tree/master/packages/umi-library#%E5%85%B3%E4%BA%8E-dependenciespeerdependencies-%E5%92%8C-external

**Comment by NexxLuo** [comment]
> 这是约定的规则： https://github.com/umijs/umi/tree/master/packages/umi-library#%E5%85%B3%E4%BA%8E-dependenciespeerdependencies-%E5%92%8C-external

peerDependencies是这样约定的没错，但是很多组件需要放到dependencies中进行打包，我的项目中就存在好几个第三方组件放到dependencies中打包不成功的问题

**Comment by NexxLuo** [comment]
rollup中有解决方案https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
但是使用这种方式难免会出现配置很多namedExports，如下图：
![image](https://user-images.githubusercontent.com/18549980/54593152-d5785c80-4a68-11e9-8864-a23ead05a144.png)

这种该如何解决？
因为想将组件打包成umd包供浏览器script引入，出现这种问题导致无法实现。

**Comment by sorrycc** [comment]
可能和 https://github.com/umijs/umi/pull/2130 有关。

**Comment by NexxLuo** [comment]
> 可能和 #2130 有关。

更新了1.2.2，依然是同样的问题。

**Comment by sorrycc** [comment]
给可复现步骤。
