### ISSUE TITLE
1.x升级到2.x如何解决Page.js的问题

### ISSUE THREAD

**Issue by 662** [umijs/umi#2129]
## 问题

1.x升级到2.x，原有的page.js约定被废弃，如何在routes.exclude中排除大量的非/pages/xx/page.js内容；量非常大，而且层级深浅不一，收集很困难；有没有什么高效的方式可以排除“有page.js的目录中的所有其他文件和文件夹”

## 为什么要升级
1.x中无法自定义babel-plugin-import插件；而我现在的需求需要用如下方式引入style
```
@import "~antd/dist/antd.less";   // 引入官方提供的 less 样式入口文件
@import "your-theme-file.less";   // 用于覆盖上面定义的变量
```

**Comment by sorrycc** [comment]
参考 https://umijs.org/zh/guide/migration.html#%E9%85%8D%E7%BD%AE

**Comment by 662** [comment]
@sorrycc 
文档翻来覆去读了也没有解决我现在的问题
现在的问题是我升级到2.x之后，好几百个page.js无法正常工作

而umi-plugin-react中用到的umi-plugin-routes如下选项
> option.exclude
type: Array(RegExp|Function)

不管是RegExp还是Function，都没办法实现：
> 排除 **包含有page.js的目录** 中的所有其他文件和文件夹

**Comment by 662** [comment]
@sorrycc 
还有个问题：page.js如何在不更名为index.js的情况下被正确的识别为目录路由

**Comment by 662** [comment]
我看了你发布到youtube的视频，你是手动去排除的每一个文件

我综合了各方面得出了一个结论，应该没办法简单的处理几百个page.js这种局面

我打算手动处理每个目录，把page.js改成index.js然后把其他文件放置于 components中

只有走体力路线了

这个issue可以关闭了
