### ISSUE TITLE
建议: dva引入注解方式编写 

### ISSUE THREAD

**Issue by KellerLong** [umijs/umi#213]
- 希望dva的编写方式增加注解的方式 提高代码的维护性 阅读体验
如
export default {
  namespace: "User",

  state: {
    list: [],
    status: "test",
  },

  effects: {
    *login() {
      /* TODO */
    }
  },

  reducers: {
    setStatus( state, {payload}) {
      return {...state, ...payload};
    }
  },

  Subscription: {
    setup({ history }) {
      // Subscribe history(url) change, trigger `load` action if pathname is `/`
      return history.listen(({ pathname, search }) => {
        if (typeof window.ga !== "undefined") {
          window.ga("send", "pageview", pathname + search);
        }
      });
    }
  }
};

改为
import {Model, State, Effect, Reducer, Subscription} from "../note/model";
//
@Model
export default class User {
  @State({default: []})
  public list: any[];

  @State({default: "test", set: true})
  public status: string;

  @Effect
  public *login() {
    /* TODO */
  }

  @Reducer
  public todo() {
    /* TODO */
  }

  @Subscription
  public setup({ history }) {
    // Subscribe history(url) change, trigger `load` action if pathname is `/`
    return history.listen(({ pathname, search }) => {
      if (typeof (window as any).ga !== "undefined") {
        (window as any).ga("send", "pageview", pathname + search);
      }
    });
  }
}
这种方式

已经在公司项目使用 经过验证!!!

**Comment by sorrycc** [comment]
注意格式。

**Comment by sorrycc** [comment]
先自己尝试，整理个可实现的版本试试吧。
