### ISSUE TITLE
前端页面打包后放到静态目录后，前端路由刷新后会404错误，这时候该如何做呢？

### ISSUE THREAD

**Issue by TRUEJASONFANS** [umijs/umi#2131]
## What happens?
前端页面打包后放到静态目录后，前端路由刷新后会404错误，这时候该如何做呢？

## 最小可复现仓库
https://github.com/TRUEJASONFANS/sprint-pocker-front

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by imhele** [comment]
https://umijs.org/zh/guide/faq.html#build-%E5%90%8E%E8%AE%BF%E9%97%AE%E8%B7%AF%E7%94%B1%E5%88%B7%E6%96%B0%E5%90%8E-404%EF%BC%9F

**Comment by TRUEJASONFANS** [comment]
@imhele  @sorrycc  
thanks.
