### ISSUE TITLE
有段 import 模块的代码在 umi2 和 umi1 表现不一致，可能是 bug

### ISSUE THREAD

**Issue by lessfish** [umijs/umi#2134]
代码如下：

```js
import * as classnames from 'classnames'
console.log(typeof classnames)
```

在 umi2 中输出是 object，但是在 umi1 以及 vue-cli，create-react-app 和自配置的 webpack4 里都是输出 function，这导致了之前 umi1 这样使用的方式全部报错

这个表现不一致是 umi2 禁止了之前的使用方式么？升级文档也没有说明

谢谢

**Comment by hanzichi** [comment]
@sorrycc 求助。。

**Comment by sorrycc** [comment]
```
import * as classnames from 'classnames'
```

输出包含 default 的 object，`{ default: fn }`。

```
import classnames from 'classnames'
```

输出 fn。

我觉得没有问题，符合规范的。

**Comment by hanzichi** [comment]
@sorrycc 但是为啥 `import * as classnames from 'classnames'` 在 umi1 输出是 fn 。。

**Comment by sorrycc** [comment]
umi@1 处理的不正确吧，一起有个 https://github.com/59naga/babel-plugin-add-module-exports 的插件，但这不是正确的使用方式。

**Comment by hanzichi** [comment]
@sorrycc  我试了 vue-cli，create-react-app，以及最小的 webpack4 配置，都是输出 fn，所以比较困惑到底哪个结果才是正确的

**Comment by sorrycc** [comment]
确实，你说的对，create-react-app 应该做了啥特殊处理，有时间的话可以帮忙找下。

**Comment by hanzichi** [comment]
@sorrycc  umi2 server 底层是 webpack4 么？

**Comment by sorrycc** [comment]
对。

**Comment by sorrycc** [comment]
我想了想，原因大概是 cra 是连 node_modules 也走 babel 编译的。不过我觉得要用 classnames 的 default 导出，`import classnames` 就好了，为啥要 `import * as classnames`？

**Comment by hanzichi** [comment]
@sorrycc 

我觉得不是吧，就算 cra 是，无配置的 webpack4 也是输出 fn，无配置的 webpack4  babel 默认 exclude node_modules 的吧

升级前人 umi1 的代码碰到的问题

**Comment by sorrycc** [comment]
@hanzichi 给个 0 配置的 webpack 的例子？

**Comment by hanzichi** [comment]
@sorrycc https://github.com/deprecated-space/classnames-import-as 这样？我不知道算不算 0 配置

**Comment by sorrycc** [comment]
@hanzichi 没时间细查这个，你有空的话可以先研究下。

其实是引用一个 cjs 时返回的对象不同。

bar.js
```js
module.exports = function() {}
```

main.js
```js
// umi 里 bar 为 object，cra 里 bar 为 function
import * as bar from 'bar';

// bar 为 function
import bar from 'bar';
```

**Comment by hanzichi** [comment]
@sorrycc 这个我知道，不知道咋研究。。webpack4 最小配置输出都是 fn，umi2 用了 webpack4。。那就得研究 umi2 了是吧
