### ISSUE TITLE
 umi-library cssModules 不支持 camelCase  配置

### ISSUE THREAD

**Issue by jiechud** [umijs/umi#2135]
我的 less 文件为

```
.test{
    &-layout: { }
}
```

使用的时候驼峰去用， 如

```
<div className={styles.testLayout}></div>
```

此问题需要配置 cssModules 的 `camelCase`

**Comment by clock157** [comment]
cssModules 不建议再使用 `namespace`

**Comment by jiechud** [comment]
cssModules 用`-`分割 不仅是 `namespace` 的问题 。
还有就是css的书写习惯和团队css风格问题。
大多数情况下我们书写比较长的class或者是这个模块css比较多，会采用多个单词来表达。一般使用`-`分隔。
如： antd 和 bootstrap
```
.spinner-border {
}
.spinner-border-sm {
}
```

**Comment by chaselss02** [comment]
cssLoaderOptions:{
    camelCase: true
  }

**Comment by mizi-lin** [comment]
![image](https://user-images.githubusercontent.com/2802841/77134512-5e720b80-6aa2-11ea-86ce-522a94b1e32d.png)
```
module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/i,
        loader: 'css-loader',
        options: {
          localsConvention: 'camelCase',
        },
      },
    ],
  },
};
```

**Comment by huybn5776** [comment]
https://umijs.org/config#cssloader
```javascript
// config.js
{
  cssLoader: {
    localsConvention: 'camelCase';
  }
}
```
