### ISSUE TITLE
[RFC] 解析 ts js 的 jsdoc，自动化生成接口文档。

### ISSUE THREAD

**Issue by DiamondYuan** [umijs/umi#2140]
## 背景

rc 相关组件，antd 都可以使用。

相关讨论。

https://github.com/ant-design/ant-design/pull/14999

https://github.com/react-component/switch/issues/38

## 思路

用 babel 解析 ts js 文件。然后分析 ast 中的注释。通过正则解析出需要的字段。
https://github.com/DiamondYuan/interface-comments-parser （目前只能解析 ts）

语法和 jsdoc 相同，唯一不同的是支持 i18n

**Comment by xiaoxiangmoe** [comment]
@DiamondYuan 要不看看 [tsdoc](https://github.com/Microsoft/tsdoc)，提个 Proposal？

**Comment by DiamondYuan** [comment]
> @DiamondYuan 要不看看 [tsdoc](https://github.com/Microsoft/tsdoc/issues/153)

我的想法其实是类似 jsdoc 的自定义语法。

**Comment by sorrycc** [comment]
@DiamondYuan 有兴趣提 PR ?

**Comment by sorrycc** [comment]
和 tsdoc 的差异点是？

**Comment by DiamondYuan** [comment]
> 和 tsdoc 的差异点是？

一开始只是想给 antd 的接口都加上注释，为了不维护两套文档就在想通过注释生成文档的方法。
在不不知道 tsdoc 的情况下造了一套轮子。语法和 tsdoc类似，支持 i18n。
我先去研究游戏 tsdoc，然后再考虑如何和 umi 结合起来。

**Comment by DiamondYuan** [comment]
> 和 tsdoc 的差异点是？

tsdoc 主要在于解析注释，生成注释的 ast/html
我想的是解析 ts 代码，根据原有类型 + 注释生成 json 信息。然后进一步处理生成文档。

**Comment by xiaoxiangmoe** [comment]
@DiamondYuan  umi-library 生成组件的文档是靠 docz 的 [PropsTable](https://www.docz.site/documentation/components-api#propstable)
除了 tsdoc 里需要加这个功能之外，可能还得看看 docz

**Comment by DiamondYuan** [comment]
在代码之前要先把注释规范定一下，注释一旦写了，以后改的成本太大了。

**Comment by DiamondYuan** [comment]
https://github.com/umijs/umi/issues/2147

**Comment by clock157** [comment]
docz 的 PropsTable 是基于 https://github.com/styleguidist/react-docgen-typescript

**Comment by DiamondYuan** [comment]
> docz 的 PropsTable 是基于 https://github.com/styleguidist/react-docgen-typescript

我觉得他那个很多情况没有考虑到。比如文档显示的类型和实际代码类型的文字不同，接口参数版本。
https://github.com/umijs/umi/issues/2147

**Comment by xiaoxiangmoe** [comment]
-

**Comment by xiaoxiangmoe** [comment]
1

**Comment by youngjuning** [comment]
@DiamondYuan 什么原因遗弃这个库了呢？

**Comment by youngjuning** [comment]
> 我想在 tsdoc 的基础上加一些自定义注解和 i18n 支持。

这个有新的仓库吗？
