### ISSUE TITLE
Reporting compilation failure using @keyframes: global (xxxx)

### ISSUE THREAD

**Issue by junliuxian** [umijs/umi#2142]
## What happens?
Using `@keyframes: global (xxxx)` grammar in `.less` file results in compilation failure

## Context
- **Umi Version**: 2.4.4

**Comment by sorrycc** [comment]
给复现步骤。

**Comment by junliuxian** [comment]
在 pages 目录中，新增一个样式文件，里面写 ：

**Comment by junliuxian** [comment]
It's been too long. It should be closed.
