### ISSUE TITLE
Not reload dev server if change theme

### ISSUE THREAD

**Issue by levkovich2806** [umijs/umi#2145]
## What happens?
I have file .umirc.js:

export default {
  ...
  theme: `${__dirname}/src/themes/default.js`,
  ...
}

if i make changes to the file src/themes/default.js my not reload. To see the changes I have to manually restart the server (npm start)

package.json 

"scripts": {
    "start": "umi dev",
    ...
  },

Should it restart automatically or maybe I forgot to specify some setting somewhere?

"umi": "^2.5.6",
node: v10.14.1
Windows 10

**Comment by shengbeiniao** [comment]
mark

**Comment by levkovich2806** [comment]
up
