### ISSUE TITLE
[RFC] 一起讨论注释的规范

### ISSUE THREAD

**Issue by DiamondYuan** [umijs/umi#2147]
## 背景

想要根据 tsdoc 注释生成文档。
这样可以在编写代码时直接在编辑器里就可以查看文档。
<img src="https://user-images.githubusercontent.com/9692408/54727067-cef4fc80-4bb0-11e9-9452-04d322f022f8.png" width="50%">

## 思路

```ts
/**
 * 接口的注释
 *
 * @remarks
 *
 * 这个是接口注释的 demo
 */
interface ITestInterface {
  /**
   * 摘要部分
   *
   * @remarks
   * 详细说明
   *
   * @since 1.0.0
   *
   * @type 'a'|'b'
   *
   * @privateRemarks
   * 不会出现在文档上的注释
   *
   * @deprecated
   *  
   * @default 'a'
   */
  /**
   *
   * Summary
   *
   * @remarks
   *
   * remarks
   *
   * @locale en-US
   *
   */
  disabled?: NameType;

  /**
   * 判断是否任一输入控件经历过 `getFieldDecorator` 的值收集时机 `options.trigger`
   *
   * @type (names?: string[]) => boolean
   *
   * @param names 字段数组
   *
   * @returns 返回结果
   *
   */
  isFieldsTouched?: (names?: string[]) => boolean;
}

```

## 说明

1. type 根据 ast 自动分析，遇到复杂类型可以自定义
2. deprecated 表示参数已经废弃
3. 第一段文字为摘要
3. remarks 标记后面跟着详细的说明
4. since 表示参数第一次出现的版本，随后参数修改版本号也不会改变。

## 参考链接

https://github.com/Microsoft/tsdoc

https://microsoft.github.io/tsdoc/

**Comment by DiamondYuan** [comment]
@sorrycc  @afc163

**Comment by DiamondYuan** [comment]
`@default` 标注默认值

**Comment by DiamondYuan** [comment]
```
export interface FieldInfo {
  /**
   * 字段名称
   */
  name: string;
  /**
   * 是否必填
   */
  optional: boolean;
  /**
   * 第一次出现的版本号
   */
  since?: string;
  /**
   * 类型
   */
  type: string;
  /**
   * 是否过期
   */
  deprecated: boolean;
  /**
   * 默认类型
   */
  default: string;
}

export interface MethodInfo {
  /**
   * 参数列表
   */
  param: {
    name: string;
    description: string;
  }[];
  /**
   * 返回结果
   */
  return?: string;
  /**
   * 第一次出现的版本号
   */
  since?: string;
  /**
   * 类型
   */
  type: string;
  /**
   * 是否过期
   */
  deprecated: boolean;
}

```

**Comment by sorrycc** [comment]
建议的方案是自己手写还是用 tsdoc？

**Comment by xiaoxiangmoe** [comment]
能用 tsdoc 还是最好用 tsdoc 吧，因为 tsdoc 支持之后，vscode 也会增加支持。
最近 tsdoc 组的人在忙 [API Extractor v7](https://www.npmjs.com/package/@microsoft/api-extractor)，可能不会很快实现它。

**Comment by DiamondYuan** [comment]
tsdoc 只是解析注释，但是解析接口有多少个参数这类信息需要自己写。
注释解析通过 tsdoc 来完成。

**Comment by DiamondYuan** [comment]
> 能用 tsdoc 还是最好用 tsdoc 吧，因为 tsdoc 支持之后，vscode 也会增加支持。
> 
> 最近 tsdoc 组的人在忙 [API Extractor v7](https://www.npmjs.com/package/@microsoft/api-extractor)，可能不会很快实现它。
> 
> 提几个问题：
> 
> * 多语言的话，我们应该怎么做呢？也就是我们要手动写多遍 `@remark` 等信息吗？ 如果我在英文中写了 `@remark`,在中文中没写，那会自动带过来英文中写的信息吗？
> * `@since 1.0.0` 是自动生成还是手动维护呢？
> * `@type 'a'|'b' ` 没有什么必要吧。类型还是让 IDE 通过 language service 自动计算吧

```js
/**
 * @remarks
 * en
 */
/**
 * @remarks
 * 中文
 * @locale zh
 */
```

注释分基础注释和额外注释，额外注释里的字段会覆盖基础注释里的字段，否则就取基础注释里的信息。

@since 需要手动维护 只有第一次新增 API 后才需要写


@type 'a'|'b' 一般是不需要手动写。但是如果希望在文档中显示的文字和时机代码中的类型不同，就可以自己指定，覆盖机器分析的结果。
