### ISSUE TITLE
[Feature Request] Set "async" or "defer" prop in <script src="/umi.js" ></script> when umi build

### ISSUE THREAD

**Issue by xiaozhaoqi** [umijs/umi#2149]
## Background
When browser loads umi.js, umi.css, or umi.dll.js, it will block DOM render.
I try to use "setAttribute" function, and change "<script src="/umi.js" ></script>" to "<script src="/umi.js"  async></script>" , but it's not work. It's still blocked DOM render.

## Proposal
Is there any way to set async or defer script  in "document.ejs" or ".umirc.js" ?
I have not find that on https://umijs.org.

THANKS.

**Comment by sorrycc** [comment]
Umi.js is already at the bottom, why need to add `defer`?
