### ISSUE TITLE
umi-plugin-polyfills依赖于2.6.0的core-js，而2.6.0的core-js还不支持Array.prototype.flat，请升级依赖。

### ISSUE THREAD

**Issue by qwIvan** [umijs/umi#2151]
## What happens?
Array.prototype.flat 从 Chrome 69 开始支持，使用旧版Chrome或者使用使用旧版Chromium内核的中国厂商开发的浏览器的用户遇到 Array.prototype.flat 函数时出错。

## Mini Showcase Repository(REQUIRED)
https://github.com/ant-design/ant-design-pro/

## How To Reproduce
**Steps to reproduce the behavior:**
1. 在 ant-design-pro 中使用 Array.prototype.flat 函数。
2. 使用搜狗浏览器访问。

**Expected behavior**
1. umi-plugin-polyfills 提供 flat 的polyfill
2. 旧版浏览器调用 flat 的 polyfill 来代替未获支持的 Array.prototype.flat

## Context

- **Umi Version**: 2.4.4
- **Node Version**: 11.11
- **Platform**: Chrome on ArchLinux、搜狗浏览器 on Windows

**Comment by sorrycc** [comment]
需要同时升级 babel@7.4 和 core-js@3 。

**Comment by qwIvan** [comment]
@sorrycc 

目前基于 ant design pro 的项目，运行过程中提示 Warning: umi-plugin-polyfills has been deprecated.
use config.targets instead.
关于 config.targets 的用法，在 https://github.com/umijs/umi/issues/1108 当中有所提及。那么在ant design pro 中该如何处理呢？

**Comment by sorrycc** [comment]
参考 https://umijs.org/config/#targets ，无需加 umi-plugin-polyfills 这个插件。

**Comment by qwIvan** [comment]
ant design pro现在不是使用umi-plugin-polyfills来做的吗？

**Comment by sorrycc** [comment]
@qwIvan 不，用 targets 配置。

**Comment by FalconIA** [comment]
@sorrycc  问题仍然存在

clone 最新版本 ant-design-pro @`59e06434`
npm install
npm install --save-dev@core-js dev

配置targets
```
  targets: {
    chrome: 49,
    ie: 11,
  },
```

build结果中 Array.prototype.flat 在IE11下仍然报错

版本信息如下：
```
node: 10.15.3
npm: 6.4.1
ant-design-pro: 59e06434
umi: 2.8.16
babel-preset-umi: 1.6.0
core-js: 3.4.1
```
