### ISSUE TITLE
pwa manifest 和 publicPath 冲突

### ISSUE THREAD

**Issue by hnsylitao** [umijs/umi#2152]
使用pwa的时候
如果设置了publicPath 设置为cdn 的域名
生成的manifest 也是cdn 下的 
运行的时候就会报
``` json
Manifest: property 'start_url' ignored, should be same origin as document.
```

**Comment by LukerSpringtree** [comment]
@xiaoiver 你好,能不能提供一个 demo仓库地址, 让我们学习一下 umi究竟该怎么使用 pwa
我也是一头雾水啊
