### ISSUE TITLE
[Feature Request] 添加cssModulesIncludes处理node_modules下的css module

### ISSUE THREAD

**Issue by NexxLuo** [umijs/umi#2153]
## Background

umi-library发布的npm包，其中存在使用了css module的组件，umi-lib开启cssModules只能对umd包生效。因此安装后，导致组件样式丢失。
 
umi本身支持cssModulesExcludes的配置进行排除，能否添加cssModulesIncludes配置以包含node_modules下的目录？

如果有其它解决方式，望解答，十分感谢。

**Comment by NexxLuo** [comment]
可通过chainWebpack设置less-in-node_modules实现，如下：
![image](https://user-images.githubusercontent.com/18549980/54803153-473ee900-4ca9-11e9-81ef-81faa9f24451.png)

**Comment by sorrycc** [comment]
esm 和 cjs 使用 rollup 方式，也是会处理 css modules 的；babel 方式肯定不行，因为不转 css 文件的。

**Comment by Mr-jiangzhiguo** [comment]
@sorrycc 

最近也遇到同样的问题：

使用 dumi 开发组件，组件中用了 cssModules，采用 babel 打包方式（为了拆分文件），
由于是文件到文件的编译，不会处理 css，导致编译产物仍然是形如：`import Styles from 'style/index.css'`，在 umi 项目中使用组件的时候，cssModules 没有处理 node_modules 下的样式，导致组件样式问题，

解决方案：

添加对 node_modules 下的 module.rule

```ts
// .umirc.ts

chainWebpack: (config) => {
    config.module
      .rule('cssModules-in-node_modules')
        .test(/\.css$/)
        .include
          .add(path.resolve(__dirname,'./node_modules/lean'))
          .end()
        .use('css-loader')
          .loader('css-loader')
          .options({
            modules: true,
            importLoaders: 2,
          })
  }
```
然而不起作用，求解，是我配置的不对么？

**Comment by hzyhbk** [comment]
遇到同样的问题，有解法吗？
