### ISSUE TITLE
运行一直提示 npm install --save uws

### ISSUE THREAD

**Issue by leelic7** [umijs/umi#2155]
yarn run v1.12.3
$ umi dev
[hardsource:2373e647] Writing new cache 2373e647...
[hardsource:2373e647] Tracking node dependencies with: package-lock.json, yarn.lock, .umirc.js, .umirc.local.js, config/*.
Build completed in 13.49s

 ERROR  Failed to compile with 2 errors                                                                                                                    15:18:25
This dependency was not found:

* uws in dll umi, ./node_modules/engine.io/lib/server.js

To install it, you can run: npm install --save uws
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
![image](https://user-images.githubusercontent.com/25266108/54806808-26c95b80-4cb6-11e9-8d52-f46ff63052d1.png)

运行 yarn start 一直报这个提示 运行 npm install --save uws 还是报这个错误

**Comment by sorrycc** [comment]
请给复现步骤。

**Comment by soolx** [comment]
在dll的exclude里加入uws试试

**Comment by mathcw** [comment]
@sorrycc 不明白原因 引入socket.io后会报这个错 移除后正常 #2308

**Comment by soolx** [comment]
@mathcw 浏览器端应该用socket.io-client
