### ISSUE TITLE
如何修改静态资源存放的文件夹名称

### ISSUE THREAD

**Issue by caoerguo** [umijs/umi#2157]
现在图片打包后会默认保存到dist/static/文件夹下，我们公司的jenkens服务器不识别static文件夹，只识别images文件夹，所以要把图片保存到images文件夹下，请问该如何配置

**Comment by sorrycc** [comment]
这个是不是解决了？我前面有看到 issue 了，有问题再 reopen 。

**Comment by caoerguo** [comment]
是一个问题，期待官方解决方案呀

chencheng (云谦) <notifications@github.com>于2019年3月26日 周二上午9:33写道：

**Comment by jangdelong** [comment]
解决了吗？
