### ISSUE TITLE
[Feature Request] eslint-loader options `no-undef` to "warn" or "off"

### ISSUE THREAD

**Issue by zhongwm** [umijs/umi#2160]
## Background

Some global names may be induced in .umirc.js, eg. by adding webpack.ProvidePlugin, causing compiling failed with error message like: '$api' is not defined  no-undef

## Proposal

Should we eslint-loader options `no-undef` to "warn" or "off" by default, or add user-friendly or 1st class configuration in umirc.js for `eslint-loader` options . this is a plus for projects using umi to integrate some 3rd party or legacy libs.

**Comment by sorrycc** [comment]
能给个具体的例子吗？

**Comment by clock157** [comment]
`no-undef` 规则很重要，不能改为 `warn` 或 `off`。你的问题请参考如下配置
https://eslint.org/docs/user-guide/configuring#specifying-globals

**Comment by langlong149** [comment]
在umi的config文件配置
`const define = {globalEnvConfig: envConfig};`

在eslintrc.js中配置了
`  globals: {
    globalEnvConfig: true
  },`

在编译时依然会包未定义的错误。
只有在使用的地方加上// eslint-disable-next-line no-undef 才可以打包通过。

是不是eslint-loader没有读取根目录下的.eslintrc.js文件

**Comment by hezhii** [comment]
同样的问题 @langlong149

**Comment by dimasusername** [comment]
@langlong149 @hezhii @zhongwm @sorrycc @clock157 
yes, `eslint-loader` does ignore `.eslintrc`
You are supposed to add https://github.com/webpack-contrib/eslint-loader#options to webpack.config but it was ignored, and `.umirc` said it was an invalid option.
The only workaround I found was https://eslint.org/docs/user-guide/configuring#specifying-globals
using comments inside the file you're using the global in:
`/* global var1:writable, var2:writable */`

**.umirc.js**
```
export default {
  ...
  define: {
    BASE_URL: 'http://...'
  }
}
```
**MyComponent.js**
```
/* global BASE_URL:readonly */
```

And for your editor:

**.eslintrc**
```
{
  ...
  "globals": {
    "BASE_URL": true
  }
}
```
