### ISSUE TITLE
This page contains the following errors

### ISSUE THREAD

**Issue by caoerguo** [umijs/umi#2164]
## What happens?
我要把图片打包到dist/images下，默认是打包到dist/static下，
我参考的是UMI默认配置，
![image](https://user-images.githubusercontent.com/10955343/54879935-24176380-4e7a-11e9-9f7a-30979ed2f5fc.png)

我做了以下配置
config.module.rule('xx')
            .test(/\.(png|jpg|gif|ttf|eot|svg|woff(2)?)(\?[^('|")]*)?$/)
            .use('url-loader')
            .loader(require.resolve('umi-url-pnp-loader'))
            .options({
                limit: 10000,
                name: 'images/[name].[hash:8].[ext]',
            });
我在options中讲name改为了 images/xxxxx。

在生成的css中使用了data url
![image](https://user-images.githubusercontent.com/10955343/54879891-989dd280-4e79-11e9-8c42-55420e04e42e.png)

但是在浏览器访问中访问该data会显示如下信息

![image](https://user-images.githubusercontent.com/10955343/54879905-bf5c0900-4e79-11e9-8636-d83da1ac682d.png)

我的需求很简单就是将图片打包后生成到dist/images目录下(默认是dist/static目录下)，请指出我那里配置的有问题，或者正确的配置方式应该是怎么样的。感谢！

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Umi Version： 2.6.1:
- **Node Version v11.10.0:
- **Platform**:

**Comment by caoerguo** [comment]
通过阅读umi的源码，然后我是这么解决的
`
config.module.rule('exclude')
            .use('url-loader')
            .tap(options => Object.assign(options, { name: 'images/[name].[hash:8].[ext]' }))
`

**Comment by sorrycc** [comment]
你可以自己找方案解决，但不是推荐的方式。
