### ISSUE TITLE
static output to any directory

### ISSUE THREAD

**Issue by m9rco** [umijs/umi#2167]
## hello 

If there is a way，Define the output directory

## example

```
<script src="./umi.js">
<link rel="stylesheet" href="./umi.css">
```

```
<script src="/static/umi/v2/umi.js">
<link rel="stylesheet" href="/static/umi/v2/umi.css">
```

**Comment by sorrycc** [comment]
My thoughts,

1. `publicPath` must be **absolute**, `./` is not supported
2. If you want to deploy to any location, you need to bring html together, checkout https://umijs.org/guide/deploy.html#statically-output-to-any-path for detial
3. You can also try `runtimePublicPath`, maybe it will meet your need

**Comment by m9rco** [comment]
Thanks to the teacher's reply,

1. `publicPath` Just changed the address static file output ，It will be shown in `*.css` 
2. My ultimate goal is actually true will output files into different directories

## The current path

```
static
└── module
    └── umi
        ├── 404.html
        ├── index.html
        ├── layouts__index.async.js
        ├── static
        │   ├── notfound.72a5d588.png
        │   ├── sprite.wap.ce008da2.png
        │   └── sprite.wap@2x.d94c238c.png
        ├── story
        │   ├── category.html
        │   ├── detail.html
        │   ├── home.html
        │   └── special.html
        ├── story.html
        ├── umi.css
        ├── umi.js
        ├── vendors.async.js
        └── vendors.chunk.css
```

## Expected path

```
static
└── js
│       ├── layouts__index.async.js
│      ├── umi.js
│     └── vendors.async.js
 ├── css
│        ├── umi.css
│       └── vendors.chunk.css
└── module
    └── umi
        ├── 404.html
        ├── index.html
        ├── static
        │   ├── notfound.72a5d588.png
        │   ├── sprite.wap.ce008da2.png
        │   └── sprite.wap@2x.d94c238c.png
        ├── story
        │   ├── category.html
        │   ├── detail.html
        │   ├── home.html
        │   └── special.html
        └── story.html
```

Because our CDN service is in the release of the code to index the specified directory，So the corresponding static files are an absolute path

maybe I can extend `umi-plugin-react` plug-in, but I don't know what's the idea，

**Comment by sorrycc** [comment]
Try to write a umi plugin to handle this.

**Comment by DazChong** [comment]
For anyone looking still looking for this solution.
as of UmiJS v4 we could host it in any dir with the below configs:

`.umirc.ts`
```import { defineConfig } from "umi";

export default defineConfig({
  base: "/myPath/",
  publicPath: "/myPath/",
  ...
  ```

**Comment by longqingzhao** [comment]
my nginx root: /usr/share/nginx/dist

my umijs config:export default defineConfig({
  base: "/main/",
  publicPath: "/main/",

my umi project url:/usr/share/nginx/dist/main

url:  http://uri/main/index.html
It just loads all the resources, and umi.js is executed, but the picture is not rendered. How to solve this problem?
