### ISSUE TITLE
配置式路由怎么制定多个html模板

### ISSUE THREAD

**Issue by wssgchungang** [umijs/umi#2168]
如题

**Comment by sorrycc** [comment]
参考 https://umijs.org/guide/html-template.html#modify-the-default-template

**Comment by wssgchungang** [comment]
> 参考 https://umijs.org/guide/html-template.html#modify-the-default-template

这个是约定式路由的  有配置式路由的写法吗

**Comment by sorrycc** [comment]
路由上配 `document`，参考 https://umijs.org/guide/html-template.html#specify-templates-for-specific-pages

**Comment by wssgchungang** [comment]
> 路由上配 `document`，参考 https://umijs.org/guide/html-template.html#specify-templates-for-specific-pages

![image](https://user-images.githubusercontent.com/29122164/54968796-e79d5200-4fb6-11e9-8980-260da518d16c.png)
为什么我两个路由配了不同的模板，但是两个路由显示的都是第一个test.ejs的模板啊

**Comment by sorrycc** [comment]
有问题 reopen。

**Comment by joseahhj** [comment]
请问修复了吗？为什么更新到最新版本还是没有生效

**Comment by xiabingwu** [comment]
> 有问题 reopen。

@sorrycc 这个问题修复了吗
