### ISSUE TITLE
从windows迁移到mac后，npm i 以后.umi文件夹的router.js文件创建React对象路径错误

### ISSUE THREAD

**Issue by qhy90223** [umijs/umi#2169]
## What happens?

从windows迁移到mac后，npm i 以后，npm start ，.umi文件夹的router.js文件创建React对象路径错误，导致缺少模块，请问如何改变.umi文件夹中的设置，使项目能够进行迁移
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by qhy90223** [comment]
Umi 版本：2.0.0-0
Node 版本：8.14
操作系统：mac 13.6

**Comment by imhele** [comment]
删掉 .umi 文件夹，重新运行 npm run start

**Comment by qhy90223** [comment]
试过了，生成后还是原来的目录

**Comment by imhele** [comment]
可以发一下出问题的代码吗？

**Comment by qhy90223** [comment]
![image](https://user-images.githubusercontent.com/27689377/54908519-0eaa4400-4f23-11e9-8657-0ad7b257c140.png)

**Comment by qhy90223** [comment]
![image](https://user-images.githubusercontent.com/27689377/54909079-4fef2380-4f24-11e9-8366-7af7e8fe54df.png)

**Comment by xiaohuoni** [comment]
给个最小重现用例吧

**Comment by qhy90223** [comment]
[WorkFlow-umi-mobile.zip](https://github.com/umijs/umi/files/3002975/WorkFlow-umi-mobile.zip)

**Comment by xiaohuoni** [comment]
配置里面应该使用相对路径
```
  { path: '/', component: './login/index' },
```

**Comment by qhy90223** [comment]
搞定，万分感谢
