### ISSUE TITLE
How to manage js versioning 

### ISSUE THREAD

**Issue by saurabh-czone** [umijs/umi#2170]
Hello Support,

i am using ant design pro theme build with react: https://pro.ant.design/

and unable to find a way to manage versioning for javascript file so that is not get cached with browsers and force browser to load latest copy of code using versions.

please help me

**Comment by imhele** [comment]
you can try to disable service worker cache:
https://github.com/ant-design/ant-design-pro/blob/master/src/defaultSettings.js#L13

**Comment by sorrycc** [comment]
Try to set `hash` to true, https://umijs.org/config/#hash
