### ISSUE TITLE
Autogenerated routes bug

### ISSUE THREAD

**Issue by mediatec** [umijs/umi#2174]
## What happens?
Umi generates wrong routes when total high level routes count more then > 10-15. Please check  "src/pages" folder structure in repository.

Try to open "/#/accounts/add" route - there is loads wrong component: "/src/pages/accounts/$id/index.js" instead of correct "/src/pages/accounts/add.js"

And next route from folder structure  "/#/utilities/add" working as well: loads correct component "/src/pages/utilities/add.js"

## Mini Showcase Repository
https://github.com/mediatec/umi-bug

## How To Reproduce
See repository "/src/pages/" folder

## Context

- **Umi Version**: 2.6.8
- **Node Version**: 10.15.1
- **Platform**: Windows 10

**Comment by mediatec** [comment]
I tried structure, but still no luck. Route "/#/accounts/add" still loads wrong component "accounts/$account.js" instead of "accounts/add/index.js". And this happen only in one accounts folder. In other all works as well.
```
accounts/add/index.js
accounts/$account.js
accounts/index.js
```

Any help with this?

**Comment by intothelab** [comment]
I had this issue. Figured out that it may be a bug on the order that umiJS reads and generates the `router.js`. **Try to insert dummy file that sits in the accounts folder, below the `$account`.** 

Apparently umi uses an inverse alphabetic order to fetch everything from the folder.

**Comment by intothelab** [comment]
@sorrycc , could you help us out? Think that's possibly a bug on `generateRouterJS` function. Any clues on what should we look for?

**Comment by sorrycc** [comment]
@intothelab What's your node version?

**Comment by intothelab** [comment]
@sorrycc `10.11.0`

**Comment by mediatec** [comment]
@sorrycc and my v10.15.1

**Comment by madisvain** [comment]
We are experiencing the same issue with our sites that any file on the same level with $id.js does not get correctly routed.

The interesting thing is that on the development server for us the routing is correct. It's only routes incorrectly after building the site.

**Comment by madisvain** [comment]
I can also confirm that once I deleted some top level routes to be below 10 the issue disappeared and in production everything is working as expected so there definitely is some kind of very weird bug here.
