### ISSUE TITLE
[Feature Request] Import majestic as GUI test tool

### ISSUE THREAD

**Issue by afc163** [umijs/umi#2175]
## Background

https://github.com/Raathigesh/majestic

## Proposal

```
 umi test --ui
```

**Comment by huandoy** [comment]
👍目前有什么方法可以暴露umi-test里关于jest的配置给idea或vscode的jest插件？

**Comment by sorrycc** [comment]
@huandoy vscode 或 idea 的插件的说明给个，他们拿到配置之后可以做什么？

**Comment by huandoy** [comment]
@sorrycc 其实是想让[vscode-jest](https://github.com/jest-community/vscode-jest#how-to-get-it)或[IDEA Jest](https://www.jetbrains.com/help/idea/running-unit-tests-on-jest.html#ws_jest_installation)读取到jest配置正常运行而已。或者说umi-test怎样能够像jest一样跟idea或vscode集成起来，个人目前用idea写测试时debug体验很好，代码里uncoverd line显示也清晰，感觉majestic暂时还不够完善。

**Comment by sorrycc** [comment]
majestic 调研了下，`umi test` 不能直接接，fork 下把 jestScriptPath 改成 jestScriptCommand 然后支持数组就可以了，`umi-test` 倒是可以直接接。

https://github.com/Raathigesh/majestic/blob/07dbbfc972d18bad7251aa9c52307b4acf8c89ad/server/services/project.ts#L18

**Comment by sorrycc** [comment]
majestic 调研了下，`umi test` 不能直接接，fork 下把 jestScriptPath 改成 jestScriptCommand 然后支持数组就可以了，`umi-test` 倒是可以直接接。

https://github.com/Raathigesh/majestic/blob/07dbbfc972d18bad7251aa9c52307b4acf8c89ad/server/services/project.ts#L18

**Comment by sorrycc** [comment]
@huandoy 我觉得 umi 可以通过一个 API 露出 jest 的配置项，然后用户可以在 jest.config.js 里引用他并扩展。

**Comment by huandoy** [comment]
@sorrycc 小改了一下，有计划加入这个API吗，可以提PR?
https://github.com/huandoy/umi/blob/2c24b6809c9c07446e48a3482f84e29eee0ef6df/packages/umi-test/src/index.js#L1

**Comment by sorrycc** [comment]
@huandoy 怎么改的？直接提 PR 看下。

**Comment by sorrycc** [comment]
在 umi ui 里考虑。
