### ISSUE TITLE
针对特定页面指定模板的配置不生效

### ISSUE THREAD

**Issue by Symboler** [umijs/umi#2178]
## What happens?

项目中使用了配置式路由，由于需要对不同路由使用不同的index.ejs模版，所以根据文档配置了exportStatic=true，且给路由配置了document属性，但是打包出来发现两个现象，1、确实每个路由生成了一个index.html;2、问题就是index.html都是一样的用的默认的模版，并没有使用我自己配置的document属性指定路径下的ejs模版。请教一下是哪里出了问题？

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by sorrycc** [comment]
给复现仓库。

**Comment by delonzhou** [comment]
发现使用history: 'hash'时不支持按路由指定模板
