### ISSUE TITLE
约定式路由，页面跳转后点浏览器返回，地址变了视图没有变化

### ISSUE THREAD

**Issue by 6691** [umijs/umi#218]
目前在 dev下  约定式路由，
model里面 yield put(routerRedux.push('/**/**')); 页面跳转后点浏览器返回，地址变了但视图没有变化？

**Comment by xiaohuoni** [comment]
遇到同样的问题！还没定位出来 @6691 你处理了吗

**Comment by sorrycc** [comment]
传个能重现的 demo 上来。

**Comment by xiaohuoni** [comment]
https://github.com/xiaohuoni/umi-route-bug
重现步骤在readme
@sorrycc

**Comment by sorrycc** [comment]
layouts/index.js 里用 withRouter 包以下。参考 https://github.com/umijs/umi-dva-user-dashboard/blob/master/src/layouts/index.js

**Comment by xiaohuoni** [comment]
可以解决问题。你说这一块后续要放到框架中完成，希望，现阶段的文档里面，能够添加说明

**Comment by sorrycc** [comment]
先不在框架里处理了，感觉太耦合。
