### ISSUE TITLE
在Android6.0以下版本出现兼容性问题，白屏

### ISSUE THREAD

**Issue by liweiSm** [umijs/umi#2185]
## What happens?

我通过umi搭建了项目，后面测试的时候在Android 6.0以下版本会出现白屏加载不出页面的问题，原因目前还没定位到，我下载了官网推荐的两个demo进行兼容性测试，发现有一些正常，有一些也会出现白屏的问题

## 最小可复现仓库

https://github.com/Jadeite2/umi-antd-mobile.git

## 相关环境信息

代码运行在 <= Android 5.1 环境下，6.0+正常

**Comment by afc163** [comment]
https://umijs.org/zh/config/#targets

**Comment by liweiSm** [comment]
> https://umijs.org/zh/config/#targets

非常感谢，已经解决

**Comment by lfh1991** [comment]
> > https://umijs.org/zh/config/#targets
> 
> 非常感谢，已经解决

你好，请问具体怎么解决的？在targets中添加了android:5.1，没有作用。

**Comment by brownbo** [comment]
> > > https://umijs.org/zh/config/#targets
> > 
> > 
> > 非常感谢，已经解决
> 
> 你好，请问具体怎么解决的？在targets中添加了android:5.1，没有作用。

config.ts 部分配置也会影响
