### ISSUE TITLE
本地开发环境下，怎么将 umi.css 和 umi.js 的路径改为相对路径，publicPath 设置无效

### ISSUE THREAD

**Issue by laixstx** [umijs/umi#2186]
本地开发环境下，我的站点是一个子站点 /site1/*
通过 nginx 配置 子站点 /site1 到我的 端口 localhost:8000
但是 index.html 里面的 /umi.css /umi.js 是绝对路径，
我想他们的路径是相对路径  ./umi.css ./umi.js

现在我 .umirc.js中配置了

> publicPath: './',

但是没有起作用，这个 publicPath 的配置需要在 build 之后才起作用
![image](https://user-images.githubusercontent.com/10735940/55061992-ffa4cc80-50af-11e9-8d29-7d60ef5fb58e.png)

## 相关环境信息

- **Umi 版本**：2.4.2
- **Node 版本**：v10.15.3
- **操作系统**：win10

**Comment by imhele** [comment]
https://umijs.org/zh/guide/deploy.html#%E9%83%A8%E7%BD%B2-html-%E5%88%B0%E9%9D%9E%E6%A0%B9%E7%9B%AE%E5%BD%95

**Comment by laixstx** [comment]
> https://umijs.org/zh/guide/deploy.html#%E9%83%A8%E7%BD%B2-html-%E5%88%B0%E9%9D%9E%E6%A0%B9%E7%9B%AE%E5%BD%95
> 
> https://umijs.org/zh/config/#base

我已经配置了 base 和 publicPath 都是 './'了，还是没有用啊，
![image](https://user-images.githubusercontent.com/10735940/55063140-4a274880-50b2-11e9-9f72-e33c300a0b67.png)

在本地开发环境下，umi dev，路径仍然是绝对路径的
![image](https://user-images.githubusercontent.com/10735940/55063240-85c21280-50b2-11e9-9049-e6b148a57fec.png)

**Comment by laixstx** [comment]
怎么这么着急 closed 的 （--||）

**Comment by imhele** [comment]
配置了 runtimePublicPath 需要在 html 里指定 `window.publicPath`
```html
<script>
window.publicPath = <%= YOUR PUBLIC_PATH %>
</script>
```

**Comment by laixstx** [comment]
> 配置了 runtimePublicPath 需要在 html 里指定 `window.publicPath`
> 
> ```
> <script>
> window.publicPath = <%= YOUR PUBLIC_PATH %>
> </script>
> ```

一开始我以为 runtimePublicPath 可以将 umi dev 之后的 html 的 js 和 css 设置成相对路径，之后发现这个设置没用，所以已经去掉 runtimePublicPath 的配置了。

**现在主要的问题是，**
**在本地开发，umi dev 之后，html 中哪些自动插入的 umi.js 、umi.css 等，可以是相对路径，但是不管怎么设置，都是绝对路径**
![image](https://user-images.githubusercontent.com/10735940/55064637-4a751300-50b5-11e9-95a2-c220e8f99c50.png)

**似乎  publicPath: './' 的配置，只有 umi build 才有用，umi dev 是没有用的**

**Comment by imhele** [comment]
你是希望在 umi dev 开发环境的同时配合 nginx 使用吗？

**Comment by laixstx** [comment]
> 你是希望在 umi dev 开发环境的同时配合 nginx 使用吗？

我是在希望 umi dev 开发环境中，可以将 umi.js 等文件的加载路径 设置成 相对路径。

![image](https://user-images.githubusercontent.com/10735940/55066209-40a0df00-50b8-11e9-9161-e2b3fa5942af.png)

**Comment by imhele** [comment]
似乎没有能满足你需求的配置，runtimePublicPath 也是 build 后生效的。你是在什么场景下遇到的这种需求呢？

**Comment by laixstx** [comment]
> 似乎没有能满足你需求的配置，runtimePublicPath 也是 build 后生效的。你是在什么场景下遇到的这种需求呢？

目前我的本地开发环境是 http://localhost:8000，
然后使用 nignx 做了个代理，
配置当访问 http://localhost/site1/ 时,重定向到 http://localhost:8000，
但是由于 umi dev 之后的 umi.js、umi.css 等文件，都是绝对路径，所以就加载不了这些 js 和 css 文件了

**Comment by imhele** [comment]
一般没有直接把 umi dev 放到 nginx 后面做测试的情况。如果必须使用，你可以在 nginx 配置 rewrite 规则，将静态资源 `^/site1/(.*)` rewrite 到 `localhost:8000/$1`

**Comment by laixstx** [comment]
> 一般没有直接把 umi dev 放到 nginx 后面做测试的情况。如果必须使用，你可以在 nginx 配置 rewrite 规则，将静态资源 `^/(.*)` rewrite 到 `localhost:8000/$1`

好的，我明白了，非常感谢 大大 的耐心解答  :）

**Comment by GithubGoldMiner** [comment]
@laixstx 你好啊，我之前也遇到了这个问题，我把publicPath修改成'/site1/'后边带斜线，js和css就可以直接读到了

**Comment by oufeng** [comment]
- 假设test.local.com是主站点,test.local.com/v2-web是子站点。
- 假设开发环境是192.168.2.19:8000，如果用docker的方式使用ngxin的话建议不要写localhost或者127.0.0.1

```nginx
# https://github.com/umijs/umi/issues/2186
# http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files
server {
    listen  80;
    server_name test.local.com;

    # 删除所有URL上的尾斜杠
    # rewrite ^/(.*)/$ /$1 permanent;
    
    # 删除尾斜杆
    rewrite ^/v2-web/$ /v2-web permanent;

    # 将/v2-web开头的请求代理到umi服务
    location /v2-web {
      proxy_pass http://192.168.2.19:8000;
    }
    
    location @umi-static {
      proxy_pass http://192.168.2.19:8000;
    }
    
    location / {
      # 加载根资源时，先到主站点尝试加载，加载失败就到子站点进行加载
      try_files $uri $uri/ @umi-static;
    }
}
```

**Comment by amio** [comment]
对照 `publicPath = '/'` 是绝度路径，
把 `publicPath = ''` 处理为相对路径的话也是很符合直觉的，希望支持一下

**Comment by amio** [comment]
> @laixstx 你好啊，我之前也遇到了这个问题，我把publicPath修改成'/site1/'后边带斜线，js和css就可以直接读到了

如果希望支持灵活的子路径，同时跑在 `/site1/` 和 `/site2/` 路径下，这样配置就不行了，只能给每个需要支持的路径都编译一份。还是需要支持相对路径的。

**Comment by LhrAlander** [comment]
不知道还有没有人有这个问题，可以用chainwebpack来更改output.publicPath，具体配置如下：
```js
chainWebpack: (config, { webpack }) => {
    config.output.publicPath('/site1/')
  }
```

**Comment by benjieming421** [comment]
配置改成这样
  base: './',
  publicPath: './',
  history: {
    type: 'hash'
  }

**Comment by iWATCHDOG** [comment]
这个帖子还有人吗！！
我的子目录是"license"
设置是
base: "./"
publicPath: "./"
<img width="724" alt="image" src="https://github.com/umijs/umi/assets/147891684/d5dd542a-335b-4652-9512-e6faabe8d360">
如图所示,umi.js能正常加载，但是
<img width="724" alt="image" src="https://github.com/umijs/umi/assets/147891684/70bca6dd-684f-4703-b9b6-54f141627fba">
这几个js还是正常的路径，并没受到./的影响。
