### ISSUE TITLE
配置路由大小写

### ISSUE THREAD

**Issue by wx1322** [umijs/umi#2188]
## What happens?

使用配置路由并且添加了sensitive属性，访问路由时，不区分路由的大小写。

## 最小可复现仓库

> https://github.com/wx1322/umi-routes

## 复现步骤，错误日志以及相关配置

访问/login和/logIn都会显示login页面

期望：/login显示login页面，/logIn显示404页面。

## 相关环境信息

- **Umi 版本**：2.6.10
- **Node 版本**：v10.15.3
- **操作系统**：macOS 10.14.3

**Comment by wangxingkang** [comment]
地址栏路径 不区分大小写

**Comment by wx1322** [comment]
不区分大小写是umi不支持，还是其他什么原因

**Comment by afc163** [comment]
这是 http 协议的规范。

**Comment by wx1322** [comment]
好的，谢谢你们的答复

**Comment by wx1322** [comment]
umi的路由是基于[`react-router`](https://reacttraining.com/react-router/web/guides/quick-start)，react-router是支持匹配是区分大小写的，通过sensitive属性，但是我用umi配置路由的时候设置了sensitive属性，匹配路由的时候并不能区分大小写
