### ISSUE TITLE
This dependency was not found:  * husky in dll umi错误无法解决

### ISSUE THREAD

**Issue by HypnosNova** [umijs/umi#2189]
## What happens?
不知道为什么2.4.3版本的umi出现This dependency was not found:  * husky in dll umi的问题。然后我把umi升级的2.6.10最新版，安装完执行umi dev依旧出现这个问题。

于是我索性把node_modules文件夹删除，所有依赖重新安装一遍，依旧出现这个问题。我是用yarn安装。安装过程无任何报错信息。

不只是我本机有问题，同事也出现这个问题。但是使用umi build是正常的，能够打包部署到测试环境并且正常运行。

## Mini Showcase Repository(REQUIRED)

属于umi的工具的bug，非前端API的bug，无法提供链接。

## How To Reproduce
**Steps to reproduce the behavior:**
1. 执行umi dev命令

**Expected behavior**
1.构建dev环境的项目并且本地浏览器打开运行的网页，实际结果报This dependency was not found:  * husky in dll umi

![image](https://user-images.githubusercontent.com/7953802/55128689-7513aa00-514f-11e9-9d74-dee7a1217eef.png)

## Context

- **Umi Version**: 2.6.10，2.4.3
- **Node Version**: 10.15.1
- **Platform**: win10，mac

**Comment by sorrycc** [comment]
husky 不要装在 dependencies 里，装 devDependencies。

**Comment by HypnosNova** [comment]
已解决，谢谢
