### ISSUE TITLE
区块物料block add 不支持私有仓库地址

### ISSUE THREAD

**Issue by YYJay** [umijs/umi#2191]
## 复现步骤，错误日志以及相关配置
复现步骤: ``` umi block add http://192.169.3.19/YYJay/test-umi-block/tree/master/ ```

错误日志: ```  Parse url and args✖  error     Error: http://192.169.3.19/YYJay/test-umi-block/tree/master/ can't match any pattern  ```

## 相关环境信息

- **Umi 版本**：2.6.10
- **Node 版本**：11.3.0
- **操作系统**：MacOS

**Comment by yutingzhao1991** [comment]
当前识别 git 仓库的规则没有考虑到这种情况，应该加上就好了。

**Comment by paradox010** [comment]
现在支持了吗？为什么我的url还是无法解析？umi版本2.10.6

**Comment by nouh** [comment]
希望可以尽快支持一下

**Comment by sunsmeil** [comment]
求支持

**Comment by sunsmeil** [comment]
git@git.xx.com 这种格式可以支持吗
