### ISSUE TITLE
可以在一个文件(夹)名上定义多个路由参数吗

### ISSUE THREAD

**Issue by sujxia** [umijs/umi#2195]
现在是多个路由参数通过$param文件夹生成 path: 'task/taskdetail/:tab/:id/:assignee'

+ task/
  + taskdetail/
    + $tab/
      + $id/
        + $assignee/
	  - index.js
  - index.js
  - model.js
  - services.js

## 相关环境信息

- **Umi 版本**：2.6.3
- **Node 版本**：10.14.2
- **操作系统**：windows

**Comment by sorrycc** [comment]
现在不可以。

**Comment by sujxia** [comment]
好的, 谢谢
