### ISSUE TITLE
使用最新umi脚手架创建app类型项目后使用@connect 报错

### ISSUE THREAD

**Issue by pkaq** [umijs/umi#2198]
## What happens?

使用最新umi脚手架创建app类型项目后使用@connect 报错
```
Using the export keyword between a decorator and a class is not allowed
```
## 最小可复现仓库
无

## 复现步骤，错误日志以及相关配置

使用@connect即可重现

需要降级   "babel-eslint": "^8.2.6", 后可解决

## 相关环境信息

- **Umi 版本**： 最新
- **Node 版本**：最新
- **操作系统**：Win X

**Comment by sorrycc** [comment]
报什么错？给复现步骤。

**Comment by OPY-bbt** [comment]
re #1044

**Comment by OPY-bbt** [comment]
> 报什么错？给复现步骤。

re #1044

**Comment by t880216t** [comment]
同样的错误

**Comment by sorrycc** [comment]
在浏览器里抛出来的？
