### ISSUE TITLE
umi 是 Ant Financial 的基本前端框架吗？

### ISSUE THREAD

**Issue by Lizhooh** [umijs/umi#2199]
文档写着：umi 是 [Ant Financial](https://www.antfin.com) 的基本前端框架。

![image](https://user-images.githubusercontent.com/19299088/55324308-3ca7ff00-54b4-11e9-92b7-36cb43bd17bf.png)

但是我看了 Ant Financial 官网的源码，发现是基于 JQuery + Sea 的，与文档说的不符。

![image](https://user-images.githubusercontent.com/19299088/55324261-184c2280-54b4-11e9-946b-c7eebb9aac29.png)

**Comment by sorrycc** [comment]
Ant Financial 泛指蚂蚁金服，不是特指 Ant Financial 官网。
