### ISSUE TITLE
[Feature Request] Gzip support

### ISSUE THREAD

**Issue by RanQiwu** [umijs/umi#2204]
## Background

现在运行 umi-serve 部署之后的文件传输很慢。

## Proposal

希望增加Gzip的支持。

## Additional context

参考：
https://github.com/expressjs/serve-static/issues/62
https://github.com/expressjs/compression

**Comment by sorrycc** [comment]
@RanQiwu 有兴趣提个 PR?

**Comment by RanQiwu** [comment]
> @RanQiwu 有兴趣提个 PR?

可以，稍后提过来。

**Comment by RanQiwu** [comment]
已经可以压缩了。
![image](https://user-images.githubusercontent.com/22112008/55394083-0e3c2980-5571-11e9-9ff6-b34e9015699b.png)
