### ISSUE TITLE
[Feature Request] support don't check mountElement

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#2208]
## Background

![image](https://user-images.githubusercontent.com/35128/55403149-c70d6300-5587-11e9-81f2-e5b359d0ee6c.png)

## Proposal

via config

```js
export default {
  disableMountElementCheck: true,
};
```

**Comment by xiaohuoni** [comment]
啥是'abird2_header'

**Comment by sorrycc** [comment]
用户自己配了 mountElement 吧。
