### ISSUE TITLE
项目中用splitChunks 分包，遇到问题

### ISSUE THREAD

**Issue by liweiSm** [umijs/umi#2209]
## What happens?
打包过程中添加splitChunks分包会导致打包报错，报错信息如下：
 ERROR  Failed to compile with 1 errors                                           21:53:43
 error  

file vendors.js don't exists in chunksMap {"layouts__index.css":"layouts__index.chunk.css","layouts__index.js":"layouts__index.async.js","p__index.css":"p__index.chunk.css","p__index.js":"p__index.async.js","umi.css":"umi.css","umi.js":"umi.js"}

error Command failed with exit code 1.

项目地址： https://github.com/liweiSm/umiDemo.git

node 版本： v10.14.2
npm 版本：  v6.4.1

不清楚是否和本地运行环境有关系，我尝试过用不同的node版本打包，但是都没有成功，报的异常信息也是大同小异

**Comment by liweiSm** [comment]
我把仓库发给朋友帮我测试，发现能正常打包，但是我这边还是不可以，这是不是和编译环境会有关系

**Comment by KaivOU** [comment]
请问是怎么解决的，同遇到

**Comment by KaivOU** [comment]
@liweiSm

**Comment by Zhou-Bill** [comment]
同错误

**Comment by Zhou-Bill** [comment]
@KaivOU 解决了吗 
@liweiSm  请问如何解决

**Comment by Zhou-Bill** [comment]
貌似不能够用config.merge, 可以直接 换成config.optimization.splitChunks 写配置才成功

**Comment by liweiSm** [comment]
> @KaivOU 解决了吗
> @liweiSm 请问如何解决

解决了，可能是某个依赖包的问题，之前安装都是用cnpm install or yarn install，后面换成npm install 后就解决这个问题了，你可以试试

**Comment by Zhou-Bill** [comment]
> > @KaivOU 解决了吗
> > @liweiSm 请问如何解决
> 
> 解决了，可能是某个依赖包的问题，之前安装都是用cnpm install or yarn install，后面换成npm install 后就解决这个问题了，你可以试试

我解决了

**Comment by anya16** [comment]
遇到同样的问题，重新安装依赖包没有用，请问如何解决的？ @Zhou-Bill
