### ISSUE TITLE
如何去除umi自带的mock功能，我想自己实现一套serve，有引入json-serve等功能，就是不用命令mock = none，直接去除

### ISSUE THREAD

**Issue by longfeixueyi** [umijs/umi#2212]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by imhele** [comment]
你可以尝试使用 umi 提供的插件机制来实现你的需求，可以参照文档 https://umijs.org/zh/plugin/develop.html#addmiddlewarebeforemock

**Comment by xiaohuoni** [comment]
可以基于umi构建自己的框架，参考 [sekiro](https://github.com/sorrycc/sekiro) 或者 [alita](https://github.com/alitajs/alita)
