### ISSUE TITLE
[Feature Request] 提示window用户关闭[hardSource]

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#2213]
## Background
在window上使用[hardSource],有不少的问题，一直需要花时间对hardSource做答疑，我想既然没有几个window用户能够良好的使用这个功能，是否可以直接禁用掉，或者像下面这样直接给出提示？
## Proposal
```js
import isWindows from 'is-windows';

export default function(api) {
  // 允许用户通过环境变量覆盖配置
  if (!('HARD_SOURCE' in process.env)) {
    process.env.HARD_SOURCE = true;
  }
  if(isWindows()){
    api.log.success('If your page has caching problems, please close [hardSource]');
  }
}
```

**Comment by sorrycc** [comment]
提个 PR 彻底删掉 hardSource 功能吧，不管用户有没配。

**Comment by xiaohuoni** [comment]
mac上也删除吗？

**Comment by Topthinking** [comment]
为什么要删掉呀，你们有找到什么更好的webpack编译缓存方案么？

**Comment by sorrycc** [comment]
@Topthinking 有兴趣可以写个插件实现，比如 umi-plugin-hardsource 。

**Comment by Topthinking** [comment]
@sorrycc 主要我实现，对于样式资源处理都通过babel读取资源处理了，也就没有用css-loader之类的，所以在处理像antd内置的less，明显缓存hardSourceWebpackPlugin这个工具失效了

**Comment by 104gogo** [comment]
可以更新下官网的文档了。。@sorrycc
