### ISSUE TITLE
windows下umi 最新版本跑不起来

### ISSUE THREAD

**Issue by hanwenbo** [umijs/umi#2216]
index.js:1 TypeError: (0 , _umiPluginLocale.addLocaleData) is not a function
    at Object../src/pages/.umi/LocaleWrapper.jsx (LocaleWrapper.jsx:52)
    at __webpack_require__ (bootstrap:771)
    at fn (bootstrap:129)
    at Object../src/pages/.umi/router.js (router.js:5)
    at __webpack_require__ (bootstrap:771)
    at fn (bootstrap:129)
    at oldRender (umi.js:20)
    at runtimePlugin.js:60
    at umi.js:32
function.console.(anonymous function) @ index.js:1
(anonymous) @ umi.js:34
Promise.catch (async)
./src/pages/.umi/umi.js @ umi.js:33
__webpack_require__ @ bootstrap:771
fn @ bootstrap:129
0 @ request.js:137
__webpack_require__ @ bootstrap:771
(anonymous) @ bootstrap:946
(anonymous) @ bootstrap:946
webpackHotDevClient.js:153 ./node_modules/_umi-utils@1.2.1@umi-utils/lib/compatDirname.js 29:21-37
Critical dependency: the request of a dependency is an expression
printWarnings @ webpackHotDevClient.js:153
handleWarnings @ webpackHotDevClient.js:170
onmessage @ webpackHotDevClient.js:88
./node_modules/_sockjs-client@1.3.0@sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:278
./node_modules/_sockjs-client@1.3.0@sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:276
./node_modules/_sockjs-client@1.3.0@sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35

**Comment by xiaohuoni** [comment]
@imhele cc

**Comment by sorrycc** [comment]
@hanwenbo 怎么复现？

**Comment by hanwenbo** [comment]
@sorrycc 您好  任意找台windows电脑 npm install -g umi 就行了

**Comment by hanwenbo** [comment]
@sorrycc 跑的这个项目 https://github.com/mojisrc/fashop-admin

**Comment by hanwenbo** [comment]
@sorrycc 在windows下编译完事 启动之后就提示这个库报错  但它是umi内部的 我修改不了

**Comment by imhele** [comment]
> @sorrycc 跑的这个项目 https://github.com/mojisrc/fashop-admin

我来跑一下

**Comment by imhele** [comment]
create-umi 新建的项目试了一下 `yarn` 和 `npm` 都没有问题，这个仓库的依赖一直卡在 `2208/2210` ，我再整整

**Comment by imhele** [comment]
运行没问题，你使用的 npm 还是 yarn ？

![image](https://user-images.githubusercontent.com/32428655/55553967-37e18600-5714-11e9-903c-c5e9a4fc66e3.png)

![image](https://user-images.githubusercontent.com/32428655/55553910-14b6d680-5714-11e9-8ea7-3c848b7b68fc.png)

**Comment by hanwenbo** [comment]
@imhele 稍后我再试一下  我是npm
