### ISSUE TITLE
umi-library是否可以支持打包出x.d.ts

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#2217]
## Background
用umi-library打包typescript的包，有时候需要打包出x.d.ts的定义文件

**Comment by sorrycc** [comment]
rollup 模式时是会输出 d.ts 文件的，参考这个例子 https://github.com/umijs/umi/tree/3b120197ac7e4b56f8ee64543fea5e4c563ec34d/packages/umi-library/src/fixtures/build/rollup-typescript 。

**Comment by xiexingen** [comment]
> rollup 模式时是会输出 d.ts 文件的，参考这个例子 https://github.com/umijs/umi/tree/3b120197ac7e4b56f8ee64543fea5e4c563ec34d/packages/umi-library/src/fixtures/build/rollup-typescript 。
试了下 是可以的  谢谢

**Comment by xiexingen** [comment]
![image](https://user-images.githubusercontent.com/7939085/55681259-dceba100-5956-11e9-90f9-ca54d07f8361.png)
umi-lib怎么调试 报错了都没办法看到里面的错误信息

**Comment by sorrycc** [comment]
cjs 格式不打依赖包的，react-loadable 应该放 dependencies 里。

**Comment by NexxLuo** [comment]
cjs模式下目前不能打包出d.ts ？ 目前发现的是把d.ts编译成d.js了，有点尴尬。  那组件的d.ts文件就无效了。
能否让cjs打包支持原样输出d.ts文件？

**Comment by sorrycc** [comment]
@NexxLuo 这是个 bug，有兴趣提 PR 修复吗？

**Comment by NexxLuo** [comment]
> @NexxLuo 这是个 bug，有兴趣提 PR 修复吗？

我得先研究下源码 >_<   能力欠佳，估计无法快速修复。

**Comment by sorrycc** [comment]
http://github.com/umijs/umi/blob/8195a8f250c0e1cba9b3f91bbb51aef1da58da0d/packages/umi-library/src/babel.ts#L96
在这里处理，记得加用例。

**Comment by NexxLuo** [comment]
> [http://github.com/umijs/umi/blob/8195a8f250c0e1cba9b3f91bbb51aef1da58da0d/packages/umi-library/src/babel.ts#L96](https://github.com/umijs/umi/blob/8195a8f250c0e1cba9b3f91bbb51aef1da58da0d/packages/umi-library/src/babel.ts#L96)
> 在这里处理，记得加用例。

欧克  ，周末弄下
