### ISSUE TITLE
多个路由对应同一个Layout时路由切换会导致Layout重新挂载

### ISSUE THREAD

**Issue by chj-damon** [umijs/umi#2218]
## What happens?
route.config.js里面定义路由的时候指定了Layout，
因为有不同的前缀，所以我分成了多个。即：
```js
[
  {
    path: '/base',
    component: '../layouts/BasicLayout',
    routes: [
      { path: '/base/warehouse', component: './warehouse' },
      { path: '/base/goods', component: './goods' },
    ],
  },
  {
    path: '/test',
    component: '../layouts/BasicLayout',
    routes: [{ path: '/test/goods', component: './goods' }],
  },
  {
    path: '/',
    component: '../layouts/BasicLayout',
    routes: [
		{ path: '/', redirect: '/homepage' }, 
		{ path: '/homepage', component: './homepage' }
	],
  },
  {
    component: '404',
  },
]
```
当进行路由切换的时候，比如从`/homepage`切换到`/test/goods`的时候，发现BasicLayout会重新挂载一次，导致之前Menu选中的selectedKeys和openKeys都会被置空。
## Mini Showcase Repository(REQUIRED)
https://github.com/chj-damon/umi-layout-issue-recurrence
> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.clone这个地址对应的项目
2.npm install
3.npm start
4.点击左侧的菜单，从首页切换到另一个菜单项

**Expected behavior**
1.期望在路由切换的时候同一个Layout不会出现重新挂载

## Context

- **Umi Version**:2.6.11
- **Node Version**:v10.11.0
- **Platform**:MacOS MoJave

**Comment by zebrallel** [comment]
我也碰到了同样的问题。和你类似的配置，每次baseLayout都会重新挂载。
我需要一个稳定的外层组件来注入自己生成的store，不知道该怎么弄。

**Comment by chj-damon** [comment]
@zebrallel 我现在的做法是如果layout是同一个，我就放在一起了。

**Comment by sorrycc** [comment]
这样配置是会 rerender 的，BasicLayout 放到外面配。

**Comment by zebrallel** [comment]
> 这样配置是会 rerender 的，BasicLayout 放到外面配。

放到外面配是怎么配置，可以详细说下嘛，或者有没有demo，谢谢~

**Comment by sorrycc** [comment]
{
  path: '/',
  component: '../layouts/BasicLayout',
  routes: [
	  { path: '/', redirect: '/homepage' }, 
	  { path: '/homepage', component: './homepage' },
      { path: '/base/warehouse', component: './warehouse' },
      { path: '/base/goods', component: './goods' },
  ]
}
