### ISSUE TITLE
How do you deploy?

### ISSUE THREAD

**Issue by brunp** [umijs/umi#2219]
I have been looking through the documents on umijs.org, and the only deployment information provided is the "Now" integration? I would I distribute my UMI website to a new server? Do I simply ZIP up the results of umi build and copy it into a directory on the target system and run it using the UMI serve command?

**Comment by imhele** [comment]
I hope you have read this document https://umijs.org/guide/deploy.html .
The products generated after executing the `umi build` command (usually in the `./dist` directory) can be deployed anywhere you want: virtual machines, servers, CDN, and so on. The products are static files such as `.html` and `.js`. If you want to deploy them to the server, you can configure services such as nginx to make them accessible to the outside. Certainly, you can choose other services such as Spring Boot or Express, you can try to deploy your product by referring to documentation of ant-design-pro:  [Release](https://pro.ant.design/docs/deploy#Release).

**Comment by brunp** [comment]
Thank you. I have read this URL, but it wasn't completely clear how you deploy, but rather more information on configuration. It appears that the dist files are the equivalent of production files, so they just get copied (i.e., deployed) to destination server. I could in theory run the code within Apache Web Server?

**Comment by imhele** [comment]
> so they just get copied (i.e., deployed) to destination server

👍 You're right.

> I could in theory run the code within Apache Web Server?

You can choose any service you want to deploy, there are no additional limitations on the deployment of UMI products.

**Comment by OhIAmFine** [comment]
@brunp  I think you just want to know how to deploy the static file(after umi build in ./dist directory), you can copy this directory to anywhere you want ,just create a server and load the built files(./dist directory),like your remote server, github.io,and so on.
