### ISSUE TITLE
IE11无法打开页面，提示Syntax error和Loading chunk vendors failed。chrome和edge中显示正常

### ISSUE THREAD

**Issue by suezse** [umijs/umi#2220]
配置了 targets: {  ie: 11,  } ，打包后chrome可以打开页面，但是IE打不开，console中报错信息如下：
SCRIPT1002: Syntax error
vendors.async.js (549,21)
Unhandled promise rejection Error: Loading chunk vendors failed.
(missing: http://localhost:8000/vendors.async.js)

打开vendors.async.js 的549行的代码如下：
const ansi = style => {
  style.open = `\u001b[${style.codes[0]}m`;
  style.close = `\u001b[${style.codes[1]}m`;
  style.regex = new RegExp(`\\u001b\\[${style.codes[1]}m`, 'g');
  return style;
};
请教一下这个是什么原因导致的呢？

**Comment by imhele** [comment]
放一下配置文件，检查一下 targets 是不是不小心配置到 umi-plugin-react 里面去了

**Comment by suezse** [comment]
> 放一下配置文件，检查一下 targets 是不是不小心配置到 umi-plugin-react 里面去了

umi-plugin-react 放在plugins变量里的，targets在外面的
export default {
  plugins,
  history: 'hash',
  define: {
    APP_TYPE: process.env.APP_TYPE || '',
  },
  targets: {
    ie: 11,
  },
  ...

**Comment by imhele** [comment]
从配置来看没有发现问题，给一下简单的重现仓库我来看看是什么问题

**Comment by suezse** [comment]
> 从配置来看没有发现问题，给一下简单的重现仓库我来看看是什么问题

早上排查了一下所有的代码记录，是一个同事在一个文件中加了一行import { bgBlack } from 'ansi-colors';但是没有用到，结果build之后IE就报了这样的错~
