### ISSUE TITLE
[Feature Request] 能不能传递额外的 props 给 route

### ISSUE THREAD

**Issue by OPY-bbt** [umijs/umi#2221]
## Background

在嵌套路由的情况下，有时候想在1级路由中传递一些数据给2级路由，已经看到文档中有modifyRouteProps方法，但是这个只能传递一些静态数据。

## Proposal
之前使用的是dva，自己封装了renderRoutes方法，现在项目正在迁移到umi，发现此方法已经集成在umi里没法修改。类似代码如下：
```js
function renderRoutes(routes, extraProps) {
  return routes.map(route => (
     <Route
         render={
           props => (
               <route.component {...props} {...extraProps} />
           )
        }
     />
 ))
}
```

## Additional context

目前可以通过react context实现

**Comment by sorrycc** [comment]
react context 应该是个合理的方案吧，另外也可以尝试通过 route 的 Routes 属性给组件添加 hoc 组件，在这里通过 react context 拿到之后往下传。

**Comment by OPY-bbt** [comment]
thx，目前先用context了。就是感觉不够直接，如果能直接传就更好了。Routes还是保持他权限路由的功能吧
