### ISSUE TITLE
Error: 'default' is not exported by node_modules\classNames\index.js

### ISSUE THREAD

**Issue by Nokecy** [umijs/umi#2222]
## What happens?

npm run build  出现 Error: 'default' is not exported by node_modules\classNames\index.js
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

https://github.com/Nokecy/umitest

## 相关环境信息

- **Umi 版本**：    "umi-library": "^1.3.0"
- **Node 版本**：
- **操作系统**：windows 10

**Comment by imhele** [comment]
你的 package.json 中并没有添加 `classnames` 依赖，只有一个 `@types/classnames` 类型定义，而且这个包名是 `classnames` 不是 `classNames`
