### ISSUE TITLE
npm run dev 访问http://127.0.0.1:8001/ 浏览器卡死

### ISSUE THREAD

**Issue by Nokecy** [umijs/umi#2223]
## What happens?

npm run dev 后 访问http://127.0.0.1:8001/ 浏览器卡死。
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

https://github.com/Nokecy/umitest

## 复现步骤，错误日志以及相关配置

npm run dev

## 相关环境信息

- **Umi 版本**："umi-library": "1.3.0",
- **Node 版本**：
- **操作系统**：windows 10  chrome 73.0.3683.86

**Comment by Nokecy** [comment]
使用npm create umi  选中typescript类型的项目 ，就可以重现。哪位大佬看一下

**Comment by Nokecy** [comment]
1.2.1 没有问题 ，从1.2.2开始typescript项目就有问题了。@sorrycc

**Comment by yy923683900** [comment]
我也遇到同样问题

**Comment by Nokecy** [comment]
@sorrycc  大佬能抽空看下这个问题吗？

**Comment by HelloWorldCAT** [comment]
请问这个解决了吗？

**Comment by Nokecy** [comment]
v1.5.1 解决了
