### ISSUE TITLE
可以拿到根组件吗？

### ISSUE THREAD

**Issue by tolerance-go** [umijs/umi#2224]
## Background

接入，比如某些需要根组件使用的库，如 redux-react-hook 

## Proposal

如果目前不行，建议动态配置的方式 app.js 暴露出来怎么样～

@sorrycc

**Comment by sorrycc** [comment]
通过 app.js 可以修改根组件的，看下文档。

**Comment by tolerance-go** [comment]
@sorrycc 谢谢 找到了 https://umijs.org/zh/guide/runtime-config.html#rootcontainer
