### ISSUE TITLE
umi如何配置支持ios9系统

### ISSUE THREAD

**Issue by hpf888** [umijs/umi#2226]
umi如何配置支持能ios9系统？

目前用的版本：
 "umi": "^2.6.11",
 "umi-plugin-react": "^1.7.2"
nodejs: 11.13

**Comment by imhele** [comment]
[targets](https://umijs.org/zh/config/#targets) 配置 `safari: 9, ios: 9`

**Comment by hpf888** [comment]
在config.js里配置了，不起作用，还需要做其他的相关设置吗

import pageRoutes from './router.config';
const path = require('path');
export default {
  hash: true,
  targets: {
    safari:9, 
    ios:9,
  },
  plugins: [
    ['umi-plugin-react', {
      antd: true,
      dva: true,
      dynamicImport: {
        loadingComponent: './components/PageLoading/index',
        webpackChunkName: false,
      },
      polyfills: ['ie9'],
      dll: true,
      //hd:true,
      title: { defaultTitle: '新摩比服务号' },

**Comment by imhele** [comment]
给一个最小复现仓库我来看看是什么问题，另外， polyfills 配置已经废弃

**Comment by hpf888** [comment]
imhele老师您好，后面是代码地址，麻烦您帮忙看看，谢谢了 https://github.com/hpf888/wechat-service.git

**Comment by hpf888** [comment]
@imhele 最新版本targets设置对safari:9、ios:9不生效的这个是bug吗，该如何拒绝呢？

**Comment by imhele** [comment]
> @imhele 最新版本targets设置对safari:9、ios:9不生效的这个是bug吗，该如何修改呢？

用 umi inspect 来看配置是没问题的
我这边路由器有点奇怪，刚整了一部 ios9 的设备还没连上局域网，你稍等一下

**Comment by imhele** [comment]
复现了，但即使 targets 配置到 ie9 ，ios9 同样无法浏览。
我用 create-umi 新建一个项目，没配置 targets 时 ios9 无法浏览，配置之后可以浏览，说明 targets 是生效的。有可能是你的项目或者项目的依赖使用了无法通过补丁支持的功能，我没有 mac 设备没办法调试，我先找找是不是项目依赖出的问题

**Comment by hpf888** [comment]
@imhele 好的，还有没有其他方法，我绕开依赖项直接把ios9补丁直接放进去呢

**Comment by imhele** [comment]
可以在 src/pages/document.ejs 的 head 中添加 script 引入补丁

**Comment by hpf888** [comment]
之前引入过，但是也不起作用啊，这个和版本有关系吗

**Comment by imhele** [comment]
> 之前引入过，但是也不起作用啊，这个和版本有关系吗

有相关报错信息吗

**Comment by sorrycc** [comment]
create-umi 创建的项目没问题，说明是项目代码引入的依赖的问题，需要定位到具体代码，然后再看怎么解决。

**Comment by hpf888** [comment]
我也设置了兼容IE系统列，ie9-ie11报错的问题：
SCRIPT1002: 语法错误
文件: umi.37416a68.js，行: 1，列: 60941
class o extends c.default.Component{componentDidMount(){document.title=this.props.route._title}getTitle()

**Comment by sorrycc** [comment]
可以加环境变量 `COMPRESS=none` 不压缩构建，定位到具体是哪个依赖文件导致的。

**Comment by hpf888** [comment]
@imhele @sorrycc 非常感谢帮忙指导，问题已经解决了。

**Comment by sqfbeijing** [comment]
> @imhele @sorrycc 非常感谢帮忙指导，问题已经解决了。

@hpf888 请问最终怎么解决的呢？？ 我也遇到这个问题

**Comment by peterzhai** [comment]
reducers: {
    saveInfos(state, action) {
    }
  },
在ios8 会报SyntaxError: Unexpected token '('. Expected a ':' following the property name 'saveInfos'.

**Comment by liudq** [comment]
> @imhele @sorrycc 非常感谢帮忙指导，问题已经解决了。

请问怎么解决的呀
