### ISSUE TITLE
跳转页面后页面的状态保存问题

### ISSUE THREAD

**Issue by csj8520** [umijs/umi#2228]
umi 怎么配置页面返回后上一页的状态还保存着并且滚动位置还是之前的

**Comment by sorrycc** [comment]
我记得滚动位置默认应该不会清吧，需要清的时候自己手动 `window.scrollTo(0, 0)` 处理，参考 https://umijs.org/zh/guide/router.html#scroll-to-top

**Comment by csj8520** [comment]
> 我记得滚动位置默认应该不会清吧，需要清的时候自己手动 `window.scrollTo(0, 0)` 处理，参考 https://umijs.org/zh/guide/router.html#scroll-to-top

我也不清楚我这到底是怎么回事切换页面的时候上一页的组件都销毁了，再返回时什么都没有了

**Comment by sorrycc** [comment]
组件是会被销毁的，react-router 没有 vue-router 的 keep-alive 功能。

**Comment by ZouHuaYi** [comment]
umi能否参考这给路由包一层呢？ https://github.com/CJY0208/react-router-cache-route
