### ISSUE TITLE
model 重名的问题

### ISSUE THREAD

**Issue by maifine** [umijs/umi#2229]
## What happens?

在动态路由下，不同页面下下model命名能重名吗，比如：

pageA下的models中有datajs，namespace为data；
pageB下的models中有datajs，namespace为data；

如果用户先访问pageA，然后再访问pageB，期望能够实现pageB下的model data将pageA下的model data覆盖，貌似目前框架在发现重名的时候，并未选择覆盖重名的model。

在大型的项目里，如果要求每个页面的model命名不一样，其实对管理和维护都有些不利，请问目前有没有好的解决方案，能够支持这种覆盖模式？

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **2.3.1**：
- **Node 版本**：
- **操作系统**：

**Comment by sorrycc** [comment]
现在 dva 的机制是不允许重名的，目前没法改进。

**Comment by maifine** [comment]
> 现在 dva 的机制是不允许重名的，目前没法改进。

好的，谢谢
