### ISSUE TITLE
hash 模式下不会触发后退前进的刷新吗？ http://localhost:8000/a/#/shop/page?page=2&rows=10

### ISSUE THREAD

**Issue by hanwenbo** [umijs/umi#2230]
当我是http://localhost:8000/a/#/shop/page?page=2&rows=10的时候
我按浏览器的后退键 应该是返回page=1的页面，确实返回了但是没有重新加载，我测试了非hash模式下是可以的，比如路由是不带#的：
http://localhost:8000/a/shop/page?page=2&rows=10

**Comment by sorrycc** [comment]
给最简复现步骤。

**Comment by hanwenbo** [comment]
ok 我去倒腾下
