### ISSUE TITLE
[Feature Request] 通过配置项使用 css-loader@2，解决 monaco editor 的问题

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#2236]
## Background

* https://github.com/umijs/umi/issues/2070
* https://github.com/ant-design/ant-design-pro/issues/3901
* https://github.com/umijs/umi/pull/1822

## Proposal

通过配置指定 css-loader 版本，

### cssLoaderVersion

> 在 umi@3 里默认用 css-loader@2 。

* Type: `number`
* Default: `1`

比如：

```js
export default {
  cssLoaderVersion: 2,
};
```

## 如何同时使用两个版本的 css-loader？

* fork css-loader@1 并改名为 css-loader-1
* css-loader@2 正常用

**Comment by Lind-pro** [comment]
这儿也没说怎么解决这个问题啊？配置css-loader是在哪儿配置呢？

**Comment by Lind-pro** [comment]
@sorrycc 怎么解决npm add react-monaco-editor --save后，样式错误的问题呢？看遍了所有ISSUE，好像并没有最终的解决方案？

**Comment by sorrycc** [comment]
还没正式发布，你可以升级到 umi@2.7.0-beta.3，然配置上 `cssLoaderVersion: 2`。
