### ISSUE TITLE
[Feature Request] 准备支持pnp吗？

### ISSUE THREAD

**Issue by OPY-bbt** [umijs/umi#2238]
## Background

目前支持pnp吗？运行之后报如下错误：
`Error: Package "umi-mock@1.1.1" (via "/Users/zhangyan/Library/Caches/Yarn/v4/npm-umi-mock-1.1.1-27957c128fc4772e561e0421224eca7324b8bfc9/node_modules/umi-mock/lib/getMockData.js") is trying to require the package "debug" (via "debug") without it being listed in its dependencies (body-parser, chokidar, glob, multer, path-to-regexp, signale, umi-utils, umi-mock) `

**Comment by sorrycc** [comment]
之前跑通过，要做不少 hack 处理，没持续关注，目前不支持。
