### ISSUE TITLE
Mock 如果动态载入后，再更改动态载入的文件代码，Mock 数据并未发生变更 

### ISSUE THREAD

**Issue by smithyj** [umijs/umi#224]
项目地址：https://github.com/smithyj/oa.yangyj.com

**Comment by smithyj** [comment]
@sorrycc Mock功能有问题啊，大神快来看看啊，其他POST接口都是正常的，/api/admin/editPassword这个接口就提示404

**Comment by sorrycc** [comment]
搞定了？

**Comment by smithyj** [comment]
@sorrycc 在.umirc.mock.js采用解构require其他mock文件时，动态改变那个require的文件代码mock并不会更新，得重新start

**Comment by smithyj** [comment]
我新开个issue吧

**Comment by sorrycc** [comment]
require 的 mock 文件不是 ./mock/ 下的？

**Comment by smithyj** [comment]
是./mock下的
