### ISSUE TITLE
umi 多模板template项目中，document属性如何支持动态路由配置文件？

### ISSUE THREAD

**Issue by KongAjax** [umijs/umi#2244]

**Comment by sorrycc** [comment]
没理解问题，详细描述下吧。

**Comment by KongAjax** [comment]
> 没理解问题，详细描述下吧。

![image](https://user-images.githubusercontent.com/32997120/55850779-72ba4280-5b88-11e9-838a-0467b4a186ff.png)

在动态路由配置文件router.config.js中，针对特定的页面制定模板，会抛出异常：you should not use exportStatic with dynamic route: /document/token/:key 。那么动态路由如何支持特定页面特定模板配置

**Comment by sorrycc** [comment]
抱歉，导出静态时不支持动态路由。

**Comment by delonzhou** [comment]
发现使用history: 'hash'时不支持按路由指定模板
