### ISSUE TITLE
发布到github pages报404错误

### ISSUE THREAD

**Issue by duxiaojiao** [umijs/umi#2247]
发布到github pages上之后umi.css，umi.js返回404，请问是需要什么配置吗？

**Comment by wangxingkang** [comment]
可以贴个项目看看呗 这样描述 谁知道

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi-plugin-gh-pages

**Comment by duxiaojiao** [comment]
> https://github.com/umijs/umi-plugin-gh-pages

原来有一个插件啊，我看了umi.js的官网，发现是routerBase等几个地方需要配置，也解决了这个问题，多谢。

**Comment by duxiaojiao** [comment]
还有就是如果项目里面使用了mock里面的数据，是不是就没办法获取到这些数据了？

**Comment by xiaohuoni** [comment]
要部署服务
