### ISSUE TITLE
umi配置proxy可以在测试环境中正常使用，正式环境前后端分离应该如何设置？？？

### ISSUE THREAD

**Issue by appleUserName** [umijs/umi#2248]
umi配置proxy可以在测试环境中正常使用，正式环境前后端分离设置的proxy失效，只有将‘/api/login’修改为‘’http://www.baodu.com/login'，并设置后台跨域之后，才能访问到数据。文档中设置proxy为webpack-dev-server的proxy即开发环境，那么生产环境应该如何配置呢？？？

**Comment by dengfuping** [comment]
- 参考umi 的 [部署文档](https://umijs.org/zh/guide/deploy.html)

**Comment by bobbychan** [comment]
请问解决了吗？我也遇到了同样问题，部署文档并没有讲怎么设置fetch的root url啊

**Comment by appleUserName** [comment]
部署的时候是在服务器设置端口转发，不建议在项目中设置（把所有的接口前边加baseURL，测试跟发布的时候切换一下），IIS用URL重写，nginx则设置proxy。我用的是nginx






------------------ 原始邮件 ------------------
发件人: "Evil Rhino"<notifications@github.com>; 
发送时间: 2019年5月14日(星期二) 下午2:59
收件人: "umijs/umi"<umi@noreply.github.com>; 
抄送: "喜欢爱"<764189132@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [umijs/umi] umi配置proxy可以在测试环境中正常使用，正式环境前后端分离应该如何设置？？？ (#2248)




请问解决了吗？我也遇到了同样问题，部署文档并没有讲怎么设置fetch的root url啊
