### ISSUE TITLE
提交一个 umi Demo 

### ISSUE THREAD

**Issue by smithyj** [umijs/umi#225]
Github：https://github.com/smithyj/oa.yangyj.com
演示地址：http://oa.yangyj.com:8000/
账号：admin  密码：123456

**Comment by xiaohuoni** [comment]
umi-antd-pro，现在的都是在antd-design-pro的基础上修改的，觉得有点乱，保留antd-design-pro的组件和页面逻辑，一点点整理的。地址：https://github.com/xiaohuoni/umi-antd-pro
