### ISSUE TITLE
[Feature Request] config sourcePath like webpack module.rules

### ISSUE THREAD

**Issue by kotepillar** [umijs/umi#2251]
## Background
As we know ES6 classes can not be mixed between transpiled and non transpiled code, so I need to config webpack like this:
module: {
    rules: [
        {
            test: /\.jsx?$/,
            loader: 'babel-loader',
            include: [
                path.resolve(__dirname, 'src'),
                /node_modules[\\/]prefix-[^\\/]+[\\/]src/,   // here is what I want
            ],
            options: {....}
   ]
}

But I saw the UmiJS source code umijs/babel.ts ,  you set srcPath like this:
const srcPath = join(cwd, 'src');

## Additional context
No Hurry~  but thank you in advance

**Comment by sorrycc** [comment]
> ES6 classes can not be mixed between transpiled and non transpiled code

I don't get what this means. Can you explain in detail?

**Comment by kotepillar** [comment]
@sorrycc 
Thanks for your reply : ), I am not a professional, If there is some mistakes, please point out~
node_modules/test/index.js:
```
import React from 'react';
class newReactModal extends React.Component {
  constructor() {
    super();
  }
}
export default newReactModal
```
project/src/app.js
```
import reactModal from '../../node_modules/test';
class newReactModal extends reactModal {
  constructor() {
    super();
  }
}
modal = new newReactModal();
```
It will raise an runtime Error: Class constructor newReactModal cannot be invoked without 'new', of course If I can add node_modules/test to bundle srcPath, everything will be ok (or just copy it to src !- - )

**Comment by sorrycc** [comment]
If you transform files in node_modules with babel, send a PR to [es5-imcompatible-versions](https://github.com/umijs/es5-imcompatible-versions).
