### ISSUE TITLE
extraPostCSSPlugins配置属性能在官网中添加一个配置案例吗？

### ISSUE THREAD

**Issue by wanghong2013** [umijs/umi#2252]
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by sorrycc** [comment]
有兴趣可以提个 PR，文档我们会找时间全面维护一次。
