### ISSUE TITLE
V2 发现inputItem 得虚拟键盘 再ios 11 上点击没有效果

### ISSUE THREAD

**Issue by yehoan** [umijs/umi#2253]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.  点击inputItem 再ios11 得iphone7上没有效果 点击无效
2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/55933461-ef6c2000-5c5f-11e9-86f4-faa48e7253e6.png)

**Comment by yehoan** [comment]
umi 1得时候是直接是100px

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/55933503-1591c000-5c60-11e9-92d8-99a79e95da14.png)

**Comment by yehoan** [comment]
同时发现2.0 导致 antd-mobile 得inputIntem 得虚拟键盘 再ios11.0系统下 点击按钮没效果..

**Comment by yehoan** [comment]
目前就看见iphone7 有着问题

**Comment by yehoan** [comment]
之前1.0 没有盖问题  然后直接再antd-mobile inputItem 组件下 尝试 是没有问题得 ....

**Comment by yehoan** [comment]
希望能看下这个问题

**Comment by sorrycc** [comment]
antd-mobile 的问题？如果是兼容问题，记得配 `targets`。
