### ISSUE TITLE
react-helmet 修改 meta 无效

### ISSUE THREAD

**Issue by h0730303779** [umijs/umi#2254]
请问在umi使用react-helmet 为什么只能在子组件 不能修改meta

![image](https://user-images.githubusercontent.com/16299810/55946282-01a98680-5c7f-11e9-8ccb-dedf2699127a.png)
![image](https://user-images.githubusercontent.com/16299810/55946299-08d09480-5c7f-11e9-8f70-79176d36b21e.png)
而且 title 未变化 浏览器 却可以改变
![image](https://user-images.githubusercontent.com/16299810/55946351-269df980-5c7f-11e9-94c1-9cdc393bfb78.png)

是我那里缺少配置或者代码有问题吗  查了很求麻烦 告知

**Comment by h0730303779** [comment]
我是 npm build 静态化出来的.

**Comment by h0730303779** [comment]
@xiaohuoni  请问 umijs可以做到吗 build出来的每个静态页 都有自己的meta

**Comment by sorrycc** [comment]
静态化的 title 好像不用这么处理，直接在路由上配 title 就好了。

**Comment by h0730303779** [comment]
> 静态化的 title 好像不用这么处理，直接在路由上配 title 就好了。（有点不确定）

谢谢  后面我试试 路由上配titile  可是 我的meta build后没办法在  静态化的 html上显示 各位有什么好办法吗
