### ISSUE TITLE
如何将umi引用的字体本地化？

### ISSUE THREAD

**Issue by jy4618272** [umijs/umi#226]
umi默认引用的是：https://at.alicdn.com/t/font_148784_v4ggb6wrjmkotj4i.woff，本地化如何配置？

**Comment by jy4618272** [comment]
"theme": {
        "icon-url": "'/src/themes/iconfont-3.x/font_148784_y7rvx0pkve2buik9/iconfont'",
        "text-color": "fade(#000, 90%)"
    }
已经解决

**Comment by drmaplesoul** [comment]
@jy4618272 这是修改的哪个文件?字体文体放哪?

**Comment by renzku** [comment]
😅，有点懵。还好找到了。
ant css 中的@font-face 的font-family为‘anticon’的引用了alicdn上的字体，
[ant文档有写可以通过‘icon-url’覆盖，theme属性最后一句](https://ant.design/docs/react/customize-theme-cn)
然后看了最后一句跟着的[修正示例](https://github.com/vision8tech/dvajs-user-dashboard/pull/2)才懂

**Comment by chiangfai** [comment]
@jy4618272  配置icon-url，本地图标还是无法显示。
```theme.js
module.exports = {
    'primary-color': 'pink',
    'icon-url': '"/src/assets/iconfont/iconfont"'
};
```
