### ISSUE TITLE
从自定义分支上获取区块报错

### ISSUE THREAD

**Issue by huaibaomengxiang** [umijs/umi#2260]
## What happens?

从feat/xxxx-xxxx分支获取区块报错。错误内容：Error: Error: Command failed: git checkout feature

## 最小可复现仓库

不必提供，运行 umi block add [gitUrl] gitUrl用feat/xxxxx这种分支 

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by huaibaomengxiang** [comment]
好像非master 分支都会报错

**Comment by huaibaomengxiang** [comment]
umi 版本： 2.6.11
node版本：10.15.0
操作系统：os

**Comment by yutingzhao1991** [comment]
应该是识别分支的时候有问题，feat/xxxxx 里面没有把 `/` 也识别为分支的内容。导致 checkout 了 feat。

但是这个感觉不太好搞，因为无法直接通过地址去判断 `/` 应该是属于分支名还是路径。你们有没有什么好的想法。

**Comment by huaibaomengxiang** [comment]
之前在脚手架里面用过一个拉模板的工具 download-git-repo, 可以拉到任何分支的模板。
或者 分支由用户输入
