### ISSUE TITLE
如何不使用layout

### ISSUE THREAD

**Issue by dragooncjw** [umijs/umi#2266]
你好，我想请问我如果想写一个页面，不使用layout中的任何布局，应该如何写？文档中貌似也没有写清楚如何切换不同的layout（如果我不使用location.pathname判断路径进行返回，是否还有其他的方法切换布局？）

**Comment by sorrycc** [comment]
> 不使用layout中的任何布局，应该如何写？

通过 location.pathname 判断。

> 如果我不使用location.pathname判断路径进行返回，是否还有其他的方法切换布局？

没有。
