### ISSUE TITLE
[Feature Request] block v2: support add block to a exist page 支持区块重复添加到一个页面中

### ISSUE THREAD

**Issue by yutingzhao1991** [umijs/umi#2269]
action:

- [ ] 支持按照新的结构添加区块到项目 @focus7eleven
- [ ] 支持重复添加 @focus7eleven
- [ ] 实现重名时自动 rename，可以提示用户手动输入
- [ ] 局部区块添加时用户必须指定 path，没有则提示用户手动输入
- [ ] 优化重复添加时修改页面主入口的逻辑，使用 babel 解析语法树，兼容更多场景
- [ ] 支持 model

## 背景

当前 umi 的区块（block）就是一个页面的代码片段，不支持我们把更细粒度 UI 片段提取为区块，使得可以基于 umi 研发更细粒度的区块，这样就能够通过添加多个区块来更灵活的来初始化页面了。

## 目的

可以把一个 umi 区块添加到已有的页面中。

### 区块

区块的代码结构不变，和现有的区块保持一致（@ 目录不再推荐使用了，局部区块的方案也不再支持它）：

```
- src // 通常我们推荐一个区块只包含 index.js 和 style.less 不再有 model 相关内容
  - index.js
  - style.less
- package.json
```

添加区块的命令行也保持不变，比如 `tnpx bigfish block add [blockpath]`（未来会支持通过 umi ui 来快速添加）。

但是具体将代码添加到项目的时候策略会修改，具体步骤如下：

#### 检测目标路径是否已经有组件存在

比如说 --path=/NewPage 时检测 `page/NewPage/index.(jsx?|tsx)` 是否存在。

#### 如果不存在则添加一个新的容器组件

如果不存在则添加 `page/NewPage/index.(js|tsx)`，通过判断是否有 tsconfig.json 来决定创建 tsx 还是 js。

该组件作为新的页面组件，并在路由中添加新的路由，逻辑和当前的区块添加逻辑保持一致。组件的内容如下：

```jsx
import React, { Component } from '@alipay/bigfish/react';

class NewPage extends Component {
  render() {
    return (
	  <Reeat.Fragment>
	  </Reeat.Fragment>
	)
  }
}
```

#### 下载区块到目标目录的子目录下

```
- page
  - NewPage
    - index.js
    - BlockName // 把区块代码下载到该目录，如果有已经有重名的则提示用户输入新的名称
      - index.js
      - style.less
```

#### 往容器组件中添加区块

```diff
import React, { Component } from '@alipay/bigfish/react';
+ import BlockName from './BlockName';

class NewPage extends Component {
  render() {
    return (
	  <Reeat.Fragment>
+		<BlockName />
	  </Reeat.Fragment>
	)
  }
}
```

**Comment by sorrycc** [comment]
实现层还是要支持 model。

**Comment by sorrycc** [comment]
有重名时自动 rename 吧。

**Comment by yutingzhao1991** [comment]
> 实现层还是要支持 model。

要支持 model 的话方案需要改进下，需要把区块的 model 放置到对应页面的 model(s) 文件夹下，而不能和其它内容一样直接放到区块自己的文件夹下。

**Comment by yutingzhao1991** [comment]
另外还有一点，考虑到现有的区块都是页面级的，如果直接改为新的方式是对现有区块不友好的（会多一级没必要的）。所以感觉还是要加一个参数来表明这个区块不是页面级的区块，是可以被重复添加到一个页面中的。

```json
{
  "blockConfig": {
     "inline": true
  }
}
```

@sorrycc 你觉得怎么样

**Comment by chenshuai2144** [comment]
现在的区块存量也不多，应该把页面级别的区块当成特殊的吧

**Comment by yutingzhao1991** [comment]
也行，可以在这个还没发布之前先把存量的代码更新下，加上页面级的一个标识：

```json
{
  "blockConfig": {
     "level": "page"
  }
}
```

不过感觉要一个个去加有点蛋疼，而且还要通知是不是我们维护的区块去修改。感觉还是用上面的方法兼容比较好。

**Comment by chenshuai2144** [comment]
加到 package.json 中吧。

**Comment by xiaohuoni** [comment]
> 判断是否有 tsconfig.json 来决定创建 tsx 还是 js。

有些项目中使用了.d.ts也存在tsconfig，但他需要的区块应该是js的。https://github.com/umijs/umi/issues/2302
