### ISSUE TITLE
request to update less version to support css grid's syntax 

### ISSUE THREAD

**Issue by arvinxx** [umijs/umi#227]
Less version 2.7.2 didn't support some syntax for css grid like this
```css
grid-template-columns: [full-start] 1fr [content] minmax(100%, 1000px) 1fr [full-end];
```
and version 3.x support this. So I request to update less version to support css grid new syntax

here is the issues: https://github.com/less/less.js/issues/3092

**Comment by sorrycc** [comment]
It's done in umi@2-beta .
