### ISSUE TITLE
如何指定动态路由的匹配模式

### ISSUE THREAD

**Issue by superchow** [umijs/umi#2272]
## 如何指定动态路由的匹配模式

`
       {
            path: '/lexicon/talks/:respId',
            name: 'talkList',
            component: './Lexicon/TalkList',
            hideInMenu: true,
          }
`

如何指定 respId 是数字？

## 相关环境信息

- **Umi 版本**：^2.3.1

**Comment by sorrycc** [comment]
如果用 react-router@4，是怎么处理的？

**Comment by superchow** [comment]
> 如果用 react-router@4，是怎么处理的？

`'/lexicon/talks/:respId(\\d+)’`
这样写？

**Comment by superchow** [comment]
好的，已经解决了
