### ISSUE TITLE
 修改 .umirc.js 不重新渲染,必须ctrl+c,重新开始

### ISSUE THREAD

**Issue by nonespace** [umijs/umi#2276]
修改 .umirc.js 不重新渲染,必须ctrl+c,重新开始

**Comment by sorrycc** [comment]
正常不会有这问题，是不是你的环境有啥特殊的？

**Comment by nonespace** [comment]
![image](https://user-images.githubusercontent.com/25641088/56178824-34b09900-6036-11e9-9871-3c02bc4d5044.png)
![image](https://user-images.githubusercontent.com/25641088/56178839-3d08d400-6036-11e9-86fa-64722e2eb515.png)

**Comment by nonespace** [comment]
只是router单独拿出来了

**Comment by nonespace** [comment]
知道原因了  这个routes不能单独拿出来
