### ISSUE TITLE
umi-lib build --watch 出现语法错误时，watch中断，必须重新启动

### ISSUE THREAD

**Issue by NexxLuo** [umijs/umi#2277]
## What happens?

1.umi-lib build --watch

![image](https://user-images.githubusercontent.com/18549980/56179214-70982e00-6037-11e9-8138-e9584865da64.png)

2.出现语法错误，watch直接中断

![image](https://user-images.githubusercontent.com/18549980/56179449-5ad73880-6038-11e9-96e8-d6be29ce8108.png)

由于整个项目保护多个packages，使用lerna管理，a项目依赖b、c的lib，当启动a项目的时候想要调试b、c的改动。如果出现上述错误情况，b、c watch中断的同时，a项目也会出现编译错误（因为找不到lib对应的文件了），要想重新调试，必须先重新watch b、c， 然后再重新启动a项目。

期望结果

1.如果出现语法错误，能否不让watch中断，而是改正错误后，能直接正常替换lib中的文件

 

## 复现步骤，错误日志以及相关配置
 
1.umi-lib build --watch
2.让某一个文件出现语法错误
3.build失败，watch中断

## 相关环境信息

- **Umi-library 版本**：1.4.1
- **Node 版本**：10.15.3
- **操作系统**：windows 、cmd

**Comment by zhangyuang** [comment]
实质是调用了babel --watch
新版本会提供npm run watch的选项用来watch 所有的package的改动
另外本地调试用npm link
