### ISSUE TITLE
 umi-test: roadhog test  when app use variable in define, show  variable undefined

### ISSUE THREAD

**Issue by FunctionRun** [umijs/umi#2283]
##

-**Roadhog Version**: 2.4.9
- **Umi Version**: 0.5.6
- **Node Version**:8.12.0  
- **Npm Version**:6.4.1  
- **Platform**:macOS Mojave

.webpackrc.js

```
define: {
        'process.env.PRODUCT_MODEL': 'CLOUD'
    }
```

Component/index.tsx

```
 render() {
    const logoSrc:string = process.env.PRODUCT_MODEL === 'CLOUD' ? cloudSrc : defaultSrc;
    return (
         <Logo src={logoSrc}/>
   );
}
```
work, when I use``` roadhog dev```.

But,  ```roadhog test``` get  process.env.PRODUCT_MODEL is undefined;
-------------------
then , I add globals in jest.config.js

jest.config.js

```
globals: {
    process.env.PRODUCT_MODEL: 'CLOUD'
}
```
also process.env.PRODUCT_MODEL is undefined.

jest doc:
globals must start __ end __

how can modify my webpackrc?

**Comment by sorrycc** [comment]
umi-test does not support define, define is a config of webpack. but umi-test does not use webpack, it use jest.
