### ISSUE TITLE
uglifyOptions 缺少drop_console的配置

### ISSUE THREAD

**Issue by wzch333** [umijs/umi#2284]
## What happens?
多人协作 打包需要这个配置
希望能加上....
## 相关环境信息

- **Umi 版本**：2.5.0
- **Node 版本**：11.12.0
- **操作系统**：win64

**Comment by sorrycc** [comment]
uglifyOptions 可以自己配的。

**Comment by wzch333** [comment]
> uglifyOptions
https://github.com/umijs/umi/blob/master/packages/af-webpack/src/getConfig/uglifyOptions.js#L6
 没暴露出这个配置项api("drop_console")

**Comment by sorrycc** [comment]
https://github.com/umijs/umi/blob/master/packages/af-webpack/src/getConfig/prod.js#L61-L66
允许覆盖的。
