### ISSUE TITLE
windows系统 mdx文件的热替换编译非常慢！

### ISSUE THREAD

**Issue by airfisher** [umijs/umi#2285]
不知道是否跟本地配置有关？感谢解答。。
![image](https://user-images.githubusercontent.com/22497287/56279376-8d695a00-613a-11e9-8881-ab22b93cf024.png)

**Comment by sorrycc** [comment]
如何复现？umi-library?

**Comment by airfisher** [comment]
> 如何复现？umi-library?

嗯 是umi-library 提错地方了 尴尬。。
是比较基础的配置，编译js，less都没有问题，但是编译mdx的性能很差
![image](https://user-images.githubusercontent.com/22497287/56331234-0fe72d80-61be-11e9-9b0f-a4df0e0abec3.png)

**Comment by sorrycc** [comment]
补充下问题吧，描述清楚如何复现的 1、2、3、4 步骤。
