### ISSUE TITLE
Feature Request: 支持为路由配置额外的 model

### ISSUE THREAD

**Issue by WangJM001** [umijs/umi#2286]
router.config.js
` {
        path: '/sys/user',
        component: './User/index',
        models:["./i18n/models/i18n.js"]
      },`
我在路由配置中自定义增加了个models属性值，想问下在 api.modifyRouteComponent方法中怎么样才能取到这个属性值。
目的是为了实现不同页面下model互调功能
谢谢

**Comment by sorrycc** [comment]
现在每一这个 key，你可以整理下方案，我觉得 umi-plugin-dva 应该默认支持这个。

**Comment by WangJM001** [comment]
## 需求背景

目前在dynamicImport开启状态下，umi-plugin-dva插件会根据路径向上扫描并生成RouteComponent来实现models的自动注册，现在在我们实际项目中存在各种业务场景相互依赖，所以考虑能不能根据配置额外的models路径，把这些路径下的models和扫描到的models合并后自动注册，这样就可以实现在不同的页面下model互相调用了

## 建议
可以在router.config.js中为每个路由配置models属性，属性可传入多个其他页面下的model地址
在插件调用api.modifyRouteComponent时，获取路由下配置models以及扫描得到的models，合并后返回

**Comment by wangxingkang** [comment]
这种场景挺常见的 现在的做法是提取到全局，按照上面的方案应该更优雅

**Comment by WangJM001** [comment]
@sorrycc 大佬这个功能有计划哪个版本解决么

**Comment by WangJM001** [comment]
能不能在modifyRouteComponent中返回路由的path，这样就可以在插件里添加额外的model了

**Comment by WangJM001** [comment]
通过插件已经搞定了。

**Comment by wangxingkang** [comment]
分享一下

**Comment by dongongfeiyu** [comment]
@WangJM001 您好，这个是怎么实现的？能分享下吗

**Comment by WangJM001** [comment]
路由上增加配置项
![image](https://user-images.githubusercontent.com/20501316/70209020-0cfb7600-176a-11ea-9e19-7bc47d3f2e8d.png)

修改umi-plugin-dva插件
一、通过onPatchRouter把配置项参数拼装到component属性上
![image](https://user-images.githubusercontent.com/20501316/70209083-416f3200-176a-11ea-8527-feef7e0230b6.png)
二、修改modifyRouteComponent方法获取extraModels再和原来的pages model拼在一起

**Comment by dongongfeiyu** [comment]
您好，umi-plugin-dva这块是在哪里修改？ @WangJM001

**Comment by WangJM001** [comment]
https://github.com/umijs/umi/tree/master/packages/umi-plugin-dva
重写替换了官方插件

**Comment by dongongfeiyu** [comment]
ok，了解了，是不是可以考虑加入到官方插件中去 @sorrycc

**Comment by geek4go** [comment]
@WangJM001 你好，route.component后面加的  ^@^ 是什么意思？ resolveExtraModels 那个函数是怎么写的呀？
