### ISSUE TITLE
热更新太慢

### ISSUE THREAD

**Issue by youuycom** [umijs/umi#2288]
## What happens?

直接使用yarn create umi新建一个项目，选择基础的app版本，插件功能全选择，启动后，修改代码后，都需要10-1分钟不等。之前使用ant-design-pro roadhog的版本，复杂项目编译也就几秒钟就好。

## 相关环境信息

- **Umi 版本**：2.6.13
- **Node 版本**：v10.15.3
- **操作系统**：Windows10 最新版本

**Comment by zhangyuang** [comment]
hmr本质上是用webpack-dev-server实现的，你可以直接用webpack-dev-server试试看看速度如何

**Comment by without-yy** [comment]
使用 12.1.0 版本的 node 试一下

**Comment by sorrycc** [comment]
试了下，不能重现，初始化的项目在 windows 下 HMR 也只要 200+ ms。

![image](https://user-images.githubusercontent.com/35128/57698137-74938c00-7687-11e9-80b1-0fc995c5f34e.png)

**Comment by nuaajiangteng** [comment]
chainWebpack(config, { webpack }) {  
    // webpack热更新
    config.resolve.alias.set("react-dom", '@hot-loader/react-dom')
    config.devServer.hot(true)
    config.devtool('eval')
    new webpack.HotModuleReplacementPlugin()
  }
umi配置里面加这个试下，我本地热更新很快

**Comment by nuaajiangteng** [comment]
chainWebpack(config, { webpack }) {
    // webpack热更新
    config.resolve.alias.set("react-dom", '@hot-loader/react-dom')
    config.devServer.hot(true)
    config.devtool('eval')
    new webpack.HotModuleReplacementPlugin()
  }
umi配置里面加这个试下，我本地热更新很快

**Comment by sorrycc** [comment]
@nuaajiangteng 主要是把 devtool 配成了 eval 吧。

**Comment by nuaajiangteng** [comment]
> @nuaajiangteng 主要是把 devtool 配成了 eval 吧。

是的

**Comment by nuaajiangteng** [comment]
@sorrycc 是的
