### ISSUE TITLE
请问如何配置postCss

### ISSUE THREAD

**Issue by furylee** [umijs/umi#2289]
## What happens?
在 chrome < 70的版本中flex布局样式有问题,添加-webkit-box后成功解决样式问提,所以想知道怎么添加前缀或者开启postCss

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：2.6.13
- **Node 版本**：10.15.3
- **操作系统**：win10

**Comment by sorrycc** [comment]
配 `autoprefixer: { flexbox: true | false }` 试试。

**Comment by furylee** [comment]
> 配 `autoprefixer: { flexbox: true | false }` 试试。

配制如下
`import '@babel/polyfill';
export default {
  treeShaking: true,
  history: 'hash',
  theme: {
    'primary-color': '#FB551B',
  },
  targets: {
    ie: 9,
  },
  hash: true,
  publicPath: './',
  
  autoprefixer: { flexbox: true },
  plugins: [
    // ref: https://umijs.org/plugin/umi-plugin-react.html
    ['umi-plugin-react', {
      antd: true,
      dva: true,
      dynamicImport: { webpackChunkName: true },
      dll: true,
      locale: {
        enable: true,
        default: 'en-US',
      },
      routes: {
        exclude: [
          /models\//,
          /services\//,
          /model\.(t|j)sx?$/,
          /service\.(t|j)sx?$/,
          /components\//,
        ],
      }
    }]
  ],
};
`

生成的css
`    display: -ms-flexbox;
    display: flex;`

-ms的前缀还是加上才有的
`  targets: {
    ie: 9,
  }`

并没有autofix

**Comment by furylee** [comment]
```
autoprefixer: {
    'browsers': [
      '> 1%',
      'last 2 versions',
      'not ie <= 10',
    ],
  },
```
这样就成功了
