### ISSUE TITLE
[Feature Request] mock requests to external servers

### ISSUE THREAD

**Issue by inconduit** [umijs/umi#2290]
## Background

mocking `GET api/users` works but `GET https://myserver.com/api/users` does not intercept the network request. sometimes i want to mock a few (but not all) requests to an external API because certain endpoints are not defined yet.

## Proposal

support prefix matching for api requests in mock files, i.e. `GET https://myserver.com/api/`

## Additional context

if this is already supported but not described in the documentation please let me know!

**Comment by sorrycc** [comment]
Try the proxy config.

**Comment by inconduit** [comment]
@sorrycc thanks! that worked.
