### ISSUE TITLE
Material-ui 水滴涟漪效果和 Fastclick冲突、

### ISSUE THREAD

**Issue by shangdev** [umijs/umi#2291]
## What happens?
项目用到了Material-ui，经测试发现点击按钮之后水滴涟漪效果不会恢复，如果多次点击，会叠加颜色。

效果和下面这个图差不多：

![image](https://camo.githubusercontent.com/8cfb74a4ad2be7ec4d3692b5b667b3c1655c0b86/68747470733a2f2f6779617a6f2e636f6d2f32323365356232346162343035636163653161636333613535643837646664662e676966)

![image](https://user-images.githubusercontent.com/15621520/56400748-14781880-6288-11e9-94fb-2694a356bc02.png)

同时控制台出现了fastclick的错误信息：

![image](https://user-images.githubusercontent.com/15621520/56400760-1fcb4400-6288-11e9-8c0e-1c2f70a8415b.png)

这是Material-ui issue 下的讨论：https://github.com/mui-org/material-ui/issues/7537

所以我想确认是不是fastclick引起的该BUG，如果直接在umi-build-dev依赖包中移除fastclick，那么umi dev后会报错，可能其中有一些代码用到了这个包，如何测试这个BUG，或者如何移除fastclick 呢？

## Context

- **Umi Version**: ^1.3.18
- **Node Version**: 10.15.3
- **Platform**: IOS 和 安卓（移动设备）都存在该问题

**Comment by boxcc** [comment]
https://umijs.org/zh/plugin/umi-plugin-react.html#fastclick

在 umi-plugin-react 的配置里设置 
```
fastclick: false
```

**Comment by shangdev** [comment]
@boxcc 

我没有安装umi-plugin-react，这个配置得先安装umi-plugin-react包吧、

**Comment by boxcc** [comment]
@shangdev v1的这样设置  https://v1.umijs.org/config/#disablefastclick
