### ISSUE TITLE
可以使用 prerender-spa-plugin 

### ISSUE THREAD

**Issue by furylee** [umijs/umi#2295]
## What happens?
除了ssr之外，想使用这个插件做SEO，但是使用过程中始终编译不成功，所以想知道能不能使用这个插件

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：2.6.13
- **Node 版本**：10.15.3
- **操作系统**：Windows10

**Comment by sorrycc** [comment]
目前不支持，会和 SSR 一同考虑。
