### ISSUE TITLE
组件间事件无法穿透

### ISSUE THREAD

**Issue by yuyuabc1** [umijs/umi#2296]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
父组件包含子组件，
组件间的事件冒泡被阻止。

例子： 
<div onClick={this.event}>
    <Example />
</div>

Example中点击无法触发父组件上的方法
- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
没理解问题，这个和 umi 有关吗？
