### ISSUE TITLE
关于官方插件umi-plugin-react

### ISSUE THREAD

**Issue by superchow** [umijs/umi#2298]
官方的插件umi-plugin-react 中dynamicImport实现了路由级别的动态加载，在antd pro的示例中
```
     dynamicImport: {
        loadingComponent: './components/PageLoading/index',
      },
```
这个应用到了，可这是每个路由都是同个加载中组件，如何根据不同的路由配置不同的 `loadingComponent` ?

**Comment by sorrycc** [comment]
目前不支持这么做。
