### ISSUE TITLE
判断是否是typescript，实现不是很好

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#2302]
https://github.com/umijs/umi/blob/89b28126d673e90c00e4cdedbbd0e8a15a37667f/packages/umi-build-dev/src/BasicGenerator.js#L8

继承umi的generator的时候，取this.isTypeScript，这里判断里，项目中是否存在tsconfig.json文件，现在挺多js项目中，也有这个文件。
不知道能不能换一种更好的判断方式。

## 相关环境信息

- **Umi 版本**：
2.6.13
- **Node 版本**：
v10.15.3
- **操作系统**：
mac

**Comment by sorrycc** [comment]
js 项目为啥要有这个？

**Comment by xiaohuoni** [comment]
这就要问 pro为什么要有https://github.com/ant-design/ant-design-pro/blob/master/tsconfig.json
很多项目都是直接用的pro模版改的，基本上都有带。🤔️

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/56656571-6fff3780-66c8-11e9-9f5c-2a21764bd32f.png)

**Comment by xiaohuoni** [comment]
干脆config里面加一个配置如何？@sorrycc
