### ISSUE TITLE
通过yarn create umi 选择ant-design-pro 创建的项目IE11不兼容

### ISSUE THREAD

**Issue by amos520** [umijs/umi#2303]
window7下使用VS code 创建umi项目

使用命令
yarn create umi 
yarn 
yarn start
打开IE11，只有空白页
![image](https://user-images.githubusercontent.com/16744138/56493269-232d2c80-6521-11e9-9457-5a898928fbcd.png)

**Comment by xiaohuoni** [comment]
设置[targets](https://umijs.org/zh/config/#targets)

**Comment by amos520** [comment]
默认就是 targets: {
    ie: 11,
  },
请问还要怎么设置？

**Comment by afc163** [comment]
调试环境里 webpack 等工具是不支持 IE11 的。

**Comment by amos520** [comment]
谢谢，原来如此，我刚接触前端，不太懂请谅解。
