### ISSUE TITLE
请问如何在页面中获取配置

### ISSUE THREAD

**Issue by jaylecn** [umijs/umi#2305]
如何在页面中获取到配置值呢？

https://umijs.org/zh/config/

比如我现在需要知道 当前是否启用了 hash 文件后缀，这个条件会影响到后续的一些逻辑，该如何做的？

**Comment by zhang0ZGC** [comment]
应该可以用define实现吧

[https://umijs.org/zh/config/#define](https://umijs.org/zh/config/#define)

**Comment by jaylecn** [comment]
O__O "…   这个我是知道的， 我指的是直接获取  config 中任意配置的值

比如 mountElementId,  我现在有个功能就需要在 pages 里面拿到  mountElementId 的值, 默认是 root.

可能用户未手动指定,也可能重置了, 我需要知道实际值

**Comment by sorrycc** [comment]
写插件，通过 define 传入 api.config 里你需要在项目代码中使用到的配置项。
