### ISSUE TITLE
集成Socket.io报错

### ISSUE THREAD

**Issue by zhaiqiang1987** [umijs/umi#2308]
"dependencies": {
    "antd": "^3.15.0",
    "dva": "^2.5.0-beta.2",
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "socket.io": "^2.2.0",
    "uws": "^100.0.1"
  },
添加socket.io后编译报错了
This dependency was not found:

* uws in dll umi, ./node_modules/_engine.io@3.3.2@engine.io/lib/server.js

To install it, you can run: npm install --save uws
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `umi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
安装uws后仍然没法启动

**Comment by zhaiqiang1987** [comment]
"umi": "^1.0.0-0",
这个版本貌似可以集成 启动正常 
请问如何解决umi 2.X版本集成socket.io?

**Comment by soolx** [comment]
浏览器端应该用socket.io-client
