### ISSUE TITLE
请问umi plugin api有提供 dev server 所运行的端口和HOST的接口吗？

### ISSUE THREAD

**Issue by biliGates** [umijs/umi#2312]

**Comment by zhang0ZGC** [comment]
可以在环境变量里面设置的，scripts里面可以配置
```js
{
  "scripts":{
    "start": "cross-env PORT=8080 umi dev"
  }
}
```

要安装cross-env， `yarn add -D cross-env`

**Comment by biliGates** [comment]
> 可以在环境变量里面设置的，scripts里面可以配置
> 
> ```js
> {
>   "scripts":{
>     "start": "cross-env PORT=8080 umi dev"
>   }
> }
> ```
> 
> 要安装cross-env， `yarn add -D cross-env`

**Comment by zhang0ZGC** [comment]
[https://umijs.org/zh/guide/env-variables.html](https://umijs.org/zh/guide/env-variables.html)

**Comment by biliGates** [comment]
好的，谢谢了。其实我想实现的是这样的效果。

在 umi dev server 启动后，我想拿到当前dev server 的 url。

在 vue-cli-plugin 中可以这样做：
```js
export default async function vueCliPlugin(api, config) {
  // 启动 vue-cli serve
  const { url } = await api.service.run('serve')
 // 拿到了 dev server url
// do something
}

```
请问下umi-plugin中有类似的api吗？

**Comment by zhang0ZGC** [comment]
> 好的，谢谢了。其实我想实现的是这样的效果。
> 
> 在 umi dev server 启动后，我想拿到当前dev server 的 url。
> 
> 在 vue-cli-plugin 中可以这样做：
> 
> ```js
> export default async function vueCliPlugin(api, config) {
>   // 启动 vue-cli serve
>   const { url } = await api.service.run('serve')
>  // 拿到了 dev server url
> // do something
> }
> ```
> 
> 请问下umi-plugin中有类似的api吗？

我觉得可以通过webpack的definePlugin解决[https://www.webpackjs.com/plugins/define-plugin/](https://www.webpackjs.com/plugins/define-plugin/)，在umi里面是[https://umijs.org/zh/config/#define](https://umijs.org/zh/config/#define)
比如
![image](https://user-images.githubusercontent.com/10346399/56637942-74632a80-669f-11e9-836f-992dcb2471d3.png)

在代码里面引入
```js
console.log(HOST);   /* eslint no-undef:0 */
```

其实我也是个渣渣 :sweat_smile: 今天看umi文档恰好看到了

**Comment by biliGates** [comment]
谢谢你啦。但我我想用一个更加优雅的方式实现，因为有时候端口占用了，改端口比较麻烦。
