### ISSUE TITLE
通过yarn create umi 创建了工程，配置了targets:{ie:11},  在ie11浏览器下依然报语法错误

### ISSUE THREAD

**Issue by jiangshitou** [umijs/umi#2319]
## What happens?
刚刚通过yarn create umi 创建了工程，.umirc.js 配置了targets:{ie:11}, 但是在ie11下依然报错；一个月之前创建的工程这样配置之后ie11运行正常。为什么之前创建的工程 package.json  中 "umi": "^2.6.8"  ， 现在新创建的 是 "umi": "^2.6.3" ？

## How To Reproduce

1. 通过脚手架创建工程 ：yarn create umi
2. 安装依赖  : yarn 
3. 修改 .umirc.js  配置 targets:{ ie:11 }
4. 启动 npm run start
5. ie11 浏览器中输入 http://localhost:8000

**Expected behavior**
1.希望能够正常在ie11 中运行

## Context

- **Umi Version**:  package.json 中 "devDependencies": {"umi": "^2.6.3"}
- **Node Version**: 10.15.1
- **Platform**:  win10

**Comment by zhangji012** [comment]
我也是，创建的是"umi": "^2.6.1",配置targets:{ie:9}，在ie10和ie9上运行报错

**Comment by imhele** [comment]
请提供一下复现

**Comment by zhangji012** [comment]
// yarn create umi  之后，下面是配置文件
import { IConfig } from 'umi-types';

// ref: https://umijs.org/config/
const config: IConfig =  {
  treeShaking: true,
  plugins: [
    // ref: https://umijs.org/plugin/umi-plugin-react.html
    ['umi-plugin-react', {
      antd: false,
      dva: false,
      dynamicImport: false,
      title: 'myapp1',
      dll: false,

      routes: {
        exclude: [
          /components\//,
        ],
      },
    }],
  ],
  targets: {
    ie: 9,
  },
}

export default config;

**Comment by imhele** [comment]
复现了
![image](https://user-images.githubusercontent.com/32428655/56708338-df1f6f00-674e-11e9-858e-630c7a7ae107.png)

**Comment by sorrycc** [comment]
应该是开发模式下的问题，build 后不会有问题。

**Comment by jiangshitou** [comment]
> 应该是开发模式下的问题，build 后不会有问题。

是在开发模式下有问题，3月份我通过yarn create umi 创建的工程，配置了targets:{ie：11} 之后，在开发模式下ie11 是没问题的， 现在即使配置了，在ie11下会报语法错误，错误指向箭头函数。官网上说 umijs 的一个特性是一键兼容ie9,  通过配置 targets 来实现，是指开发模式下兼容到ie9 吧？

**Comment by leftstick** [comment]
会不会就是我这个问题https://github.com/umijs/umi/issues/2332

**Comment by sorrycc** [comment]
@leftstick 你的问题好了吗？

**Comment by leftstick** [comment]
@sorrycc 好了，提交merge后我就测了，没问题

**Comment by sorrycc** [comment]
那这个也先 close 了，有问题再 reopen。 @jiangshitou

**Comment by jiangshitou** [comment]
> 那这个也先 close 了，有问题再 reopen。 @jiangshitou

已经验证，没有问题了！
