### ISSUE TITLE
add umi lint 

### ISSUE THREAD

**Issue by demohi** [umijs/umi#232]
I think umi can add a lint command

`
$ umi lint 
`

**Comment by sorrycc** [comment]
Not a good idea, the editor is usually run directly with eslint, so it is best to have eslint dependencies in the project.

**Comment by demohi** [comment]
When I use typescript , It's weird to add tslint because umi already have this feature built in.

**Comment by sorrycc** [comment]
If eslint/tsling is configured in the project, umi will use this.

**Comment by demohi** [comment]
ok.
