### ISSUE TITLE
在tsx中引入less会提示模块找不到，但是可以运行

### ISSUE THREAD

**Issue by zhangji012** [umijs/umi#2322]
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by sorrycc** [comment]
请提供复现步骤。

**Comment by mankeheaven** [comment]
![image](https://user-images.githubusercontent.com/17426397/56788077-0484a980-6831-11e9-9767-df9c0d2eb1b4.png)

**Comment by zhangji012** [comment]
解决了，谢谢

**Comment by samwangdd** [comment]
怎么解决的？

**Comment by grasilife** [comment]
怎么解决的

**Comment by grasilife** [comment]
> 解决了，谢谢

怎么解决的,我也遇到了

**Comment by brizer** [comment]
> 解决了，谢谢

中国人就是喜欢这样，解决了又不放解决方案。不愿意帮助更多的人。

**Comment by KillianTang** [comment]
@brizer @grasilife   
人家解决的图片已经给出了，  
创建一个typings.d.ts文件，在里面声明那些内容，  
实测在`组件目录`或者`项目根目录`都可以去掉这个提示  

![组件目录](https://user-images.githubusercontent.com/25997259/63575422-a1c3d480-c5bc-11e9-9ac8-8446408aaad8.png)

**Comment by KillianTang** [comment]
> 怎么解决的？

如上

**Comment by brizer** [comment]
> @brizer @grasilife
> 人家解决的图片已经给出了，
> 创建一个typings.d.ts文件，在里面声明那些内容，
> 实测在`组件目录`或者`项目根目录`都可以去掉这个提示
> 
> ![image](https://user-images.githubusercontent.com/25997259/63575492-cddf5580-c5bc-11e9-8915-46f216745086.png)

不好意思，没看到哈。。

**Comment by samwangdd** [comment]
我把`typings.d.ts`加在组件目录下有效，但是在根目录下不生效。排查了很久，才发现`tsconfig.json`里`include`配置项里只有`["./src"]`，将它去掉就生效了！

**Comment by chenleyiduo** [comment]
看不到图片

**Comment by onsummer** [comment]
在根目录的 typing.d.ts 和组件目录下的 index.d.ts 写了 declare module '*.less' 还是无效...

![image](https://user-images.githubusercontent.com/26168955/146338368-7accff0a-fa17-4767-936e-0ca51e4868d0.png)

![image](https://user-images.githubusercontent.com/26168955/146338557-db831a20-f4e7-4d01-9a8a-845a6802a457.png)

![image](https://user-images.githubusercontent.com/26168955/146338582-09f8f52c-209d-468a-b2f4-3adc11f2e882.png)

**Comment by xu-Aurora** [comment]
> 在根目录的 typing.d.ts 和组件目录下的 index.d.ts 或者 typing.d.ts(截图中没有，但是试过了） 写了 declare module '*.less' 还是无效...
> 
> ![image](https://user-images.githubusercontent.com/26168955/146338368-7accff0a-fa17-4767-936e-0ca51e4868d0.png)
> 
> ![image](https://user-images.githubusercontent.com/26168955/146338557-db831a20-f4e7-4d01-9a8a-845a6802a457.png)
> 
> ![image](https://user-images.githubusercontent.com/26168955/146338582-09f8f52c-209d-468a-b2f4-3adc11f2e882.png)



> 在根目录的 typing.d.ts 和组件目录下的 index.d.ts 或者 typing.d.ts(截图中没有，但是试过了） 写了 declare module '*.less' 还是无效...
> 
> ![image](https://user-images.githubusercontent.com/26168955/146338368-7accff0a-fa17-4767-936e-0ca51e4868d0.png)
> 
> ![image](https://user-images.githubusercontent.com/26168955/146338557-db831a20-f4e7-4d01-9a8a-845a6802a457.png)
> 
> ![image](https://user-images.githubusercontent.com/26168955/146338582-09f8f52c-209d-468a-b2f4-3adc11f2e882.png)

解决了嘛？我也有这样的问题

**Comment by LolipopJ** [comment]
> 在根目录的 typing.d.ts 和组件目录下的 index.d.ts 或者 typing.d.ts(截图中没有，但是试过了） 写了 declare module '*.less' 还是无效...

参考[此文档](https://www.jianshu.com/p/7ddcc53df6d8)解决了：

```ts
// typings.d.ts
declare module '*.module.less' {
  const classes: Readonly<Record<string, string>>;
  export default classes;
  declare module '*.less';
}
```

```json
// tsconfig.json
{
  "include": ["typings.d.ts", "otherPath..."],
}
```
