### ISSUE TITLE
registerCommand的第二个参数options是干嘛的

### ISSUE THREAD

**Issue by tonypig93** [umijs/umi#2323]
## What happens?
如题，找了半天文档没找到

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by sorrycc** [comment]
command 的配置项，提供描述信息、help 说明、是否获取 webpack 配置等等，umi 源码里搜下 `api.registerCommand` 会有很多示例，比如 http://github.com/umijs/umi/blob/e1b2ea7f9f8990c01e625ff124615b70574214f7/packages/umi-build-dev/src/plugins/commands/block/index.js#L395
