### ISSUE TITLE
umi library打包，静态资源没有打包进去

### ISSUE THREAD

**Issue by HelloWorldCAT** [umijs/umi#2324]
## What happens?
umi library打包，静态资源没有打包进去

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

create umi， 选择library, typescript，然后加一个图片
```ts
import React, { Component } from 'react';
import './index.css';
const avatar = require('./avatar.jpg')

class App extends Component {
  render() {
    return (
      <div className="App">
      <img style={{width: 100, height: 100}} src={avatar} alt=""/>
      </div>
    );
  }
}

export default App;
```

## How To Reproduce
**Steps to reproduce the behavior:**
1. npm run build
2. check the dist/index.js, the image is not packed.

**Expected behavior**
1. the image is packed

## Context

- **Umi Version**: 1.2.1
- **Node Version**: v10.15.3
- **Platform**: win

**Comment by mankeheaven** [comment]
我的css文件都没打进去，真奇怪
