### ISSUE TITLE
[Feature Request] window.g_app、window.g_history等全局变量名可定制

### ISSUE THREAD

**Issue by 3610cn** [umijs/umi#2326]
## Background

目前我们在尝试将多个react、vue项目整合到同一个页面上（micro-frontends），但是在整合umi应用时发现umi暴露了一些全局变量如window.g_app, window.g_history等，这就导致多个umi应用整合在一个页面中时存在冲突

## Proposal

挂载到window上的全局变量可以通过option进行定制，类似webpack配置中的webpack.jsonpFunction,可以定制webpackJsonp名称，以便多个使用webpack打包的应用可以同时运行在一个页面里。

**Comment by sorrycc** [comment]
已知问题，会安排时间解决。

**Comment by wangxingkang** [comment]
@3610cn 请问如何解决相同库 的重复加载问题

**Comment by 3610cn** [comment]
> @3610cn 请问如何解决相同库 的重复加载问题

你是指类似react，antd这一类的重复加载吗?
我个人理解这里需要根据团队实际情况来看，对性能要求高或者对子应用有强控制权的，可以通过external方式全局使用一个版本，否则各自打包，类似antd之类的第三方组件库，要设置prefix，做好样式隔离。

**Comment by sorrycc** [comment]
@wangxingkang @3610cn 这是个麻烦的问题，通常会用 external 来做，但需要解 external 库升级的问题，比如 antd 升级到 4 了怎么办。

**Comment by wangxingkang** [comment]
嗯嗯，确实是！
