### ISSUE TITLE
umi build 参数 --watch无效

### ISSUE THREAD

**Issue by 515074431** [umijs/umi#2327]
## 相关环境信息

- **Umi 版本**：2.3.0-0
- **Node 版本**：v10.0.0
- **操作系统**： windows10 和 ubuntu 18

##问题表现
umi build 参数 --watch无效，build完成后仍然会退出，无法监视文件变化自动打包

**Comment by sorrycc** [comment]
有兴趣排查下，然后提个 PR 解决吗？

**Comment by zhangyuang** [comment]
umi build目前未提供watch的配置选项

**Comment by sorrycc** [comment]
是的，目前不支持。
