### ISSUE TITLE
html生成不支持改变index.html的名称

### ISSUE THREAD

**Issue by zhongjie-chen** [umijs/umi#2328]
不生成静态的build， 需要根据环境生成不同的index html文件，名字可以配置

**Comment by sorrycc** [comment]
build 之后自己用脚本 rename 下。

**Comment by zhongjie-chen** [comment]
用plugin解决了

**Comment by zhilianbi520** [comment]
> 用plugin解决了

使用的是哪个插件？可以只更新index.html的版本号嘛？
