### ISSUE TITLE
Error: api.register() should not be called after plugin is initialized.

### ISSUE THREAD

**Issue by tonypig93** [umijs/umi#2329]
## What happens?
我在写插件，然后在Promise的回调中执行`api.addHTMLScript()`就会报这个错，这是为什么？

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by sorrycc** [comment]
api.addXXX 是一个注册的过程，只能同步执行，不能异步执行。

**Comment by tonypig93** [comment]
> api.addXXX 是一个注册的过程，只能同步执行，不能异步执行。

那如何在异步当中向html中写入script？
