### ISSUE TITLE
pages router bug

### ISSUE THREAD

**Issue by demohi** [umijs/umi#233]
![image](https://user-images.githubusercontent.com/1209159/37576166-f5409906-2b65-11e8-8a51-79e81d8c1fff.png)

when I vist the /components/detail , I got 404

![image](https://user-images.githubusercontent.com/1209159/37576205-3f9bb80a-2b66-11e8-890e-fa271187e4af.png)

**Comment by sorrycc** [comment]
Check `.umi/router.js`, what's the content?

**Comment by demohi** [comment]
![image](https://user-images.githubusercontent.com/1209159/37576344-f030c5d4-2b66-11e8-82ae-d01e5ccb2e20.png)

I can't find the detail route.

**Comment by sorrycc** [comment]
The current rule is that the directory router will no longer match down. You can add additional routes via [umi-plugin-routes](https://github.com/umijs/umi/issues/219).

**Comment by demohi** [comment]
It's hard to understand the rule by the document.
