### ISSUE TITLE
[Feature Request] provide an option to disable error overlay

### ISSUE THREAD

**Issue by chadCool** [umijs/umi#2334]
I'm trying to capture the error in the error boundary, and don't want error overlay to show, is there any way to disable the error boundary?

**Comment by sorrycc** [comment]
Which error overlay?

**Comment by chadCool** [comment]
![something like this.](https://user-images.githubusercontent.com/46188956/57498092-06f50200-730d-11e9-9c4e-2ab8c3cedc99.png)

**Comment by sorrycc** [comment]
It's a runtime error, why do you want to disable it?

**Comment by betterRunner** [comment]
@sorrycc what if we don't disable it but catch the error? It seems the exception is captured by umi without throwing it out, so we can not capture it in our own error boundary
