### ISSUE TITLE
umi/link

### ISSUE THREAD

**Issue by zywkuo** [umijs/umi#2335]
link传参可以不把参数拼接在url上吗？？？？？？

**Comment by sorrycc** [comment]
你想拼在哪？如果不拼，不传是不是就可以了？

**Comment by zywkuo** [comment]
穷之前用dva 的link 参数没有在url上显示，但是刷新就获取不到值了。升级了之后换到umi 然后link就把参数都拼在url上了。我不想在url上显示参数，是不是只能把link换成a标签，然后点击执行事件，在事件里把参数存储到全局，然后在跳转的页面在调用。

**Comment by sorrycc** [comment]
通过事件就不会有参数了，但我觉得通常来说，放 url 参数里比较好，刷新后也可走到。
