### ISSUE TITLE
hd方案 iphone4和iphone5 适配错误

### ISSUE THREAD

**Issue by Chryseis** [umijs/umi#2338]
发现umi的移动端适配无论iphone4 iphone5 iphone6 
html中的rootSize全是100px meta中scale全是0.5
导致iphone4和iphone5 适配不行
![iphone4](https://user-images.githubusercontent.com/13757352/56875755-59186680-6a75-11e9-8536-1b0ef7317cee.png)

![iphone5](https://user-images.githubusercontent.com/13757352/56875749-5453b280-6a75-11e9-845f-cf4ac08b235e.png)

![iphone6](https://user-images.githubusercontent.com/13757352/56875759-5d448400-6a75-11e9-9166-a0f31334830d.png)

所以如何配置可以不使用umi的适配，而改用flexible.js的适配

## 相关环境信息

- **Umi 版本**：2.6.1
- **Node 版本**：v10.5.0
- **操作系统**：win 10

**Comment by sorrycc** [comment]
别开 hd 配置，umi 就不会做适配了。

**Comment by xiaohuoni** [comment]
不应该有适配问题吧！之前应该是可用的？

**Comment by xiaohuoni** [comment]
@Chryseis
加一下我微信，讨论一下。

**Comment by wang777777** [comment]
确实有这个问题，@xiaohuoni , 请问现在解决了吗

**Comment by xiaohuoni** [comment]
@wang777777 刚刚Chryseis联系我了，umi的hd我们也一直在用，没要求到iphone4和iphone5，所以我没注意。应该需要作者来处理吧。@pigcan @写轮

**Comment by sorrycc** [comment]
iphone@5 可以考虑不支持了吧，如果要支持，建议自行实现高清方案的脚本部分。

**Comment by Chryseis** [comment]
自定义配置flexible.js
```javascript
//.umirc.js
const px2rem = require('postcss-plugin-px2rem')
export defalut {
   ...,
  extraPostCSSPlugins: [px2rem({ rootValue: 75 })],
  plugins: [
        ['umi-plugin-react', {
            hd: false,
            fastClick: true,
        }],
    ]
}
```

然后在document.ejs 文件中加入flexible.js

**Comment by xiaohuoni** [comment]
@xiaohuoni

**Comment by qianL93** [comment]
这里说的iphone4 /5 是什么ios版本呢？
