### ISSUE TITLE
umi设置target 兼容IE9，报错！

### ISSUE THREAD

**Issue by smz8023** [umijs/umi#2339]
Warning: The <DynamicComponent /> component appears to have a render method, but doesn't extend React.Component. This is likely to cause errors. Change DynamicComponent to extend React.Component instead. 
SCRIPT5022: 引发了异常但未捕获 
umi.js, 行25001 字符5
The above error occurred in the <DynamicComponent> component:
    in DynamicComponent (created by Component)
    in Component (created by Component)
    in Authorized (created by AuthComponent)
    in AuthComponent (created by Connect(AuthComponent))
    in Connect(AuthComponent) (created by Component)
    in Component (created by Route)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by ret)
    in ret (created by RouterWrapper)
    in Switch (created by RouterWrapper)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by RouterWrapper)
    in sfc (created by LocaleWrapper)
    in IntlProvider (created by LocaleWrapper)
    in LocaleProvider (created by LocaleWrapper)
    in LocaleWrapper (created by RouterWrapper)
    in RouterWrapper
    in Provider (created by DvaContainer)
    in DvaContainer

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. 
Unhandled promise rejectionTypeError: Cannot call a class as a function

**Comment by smz8023** [comment]
谢谢！！！！！！

**Comment by leftstick** [comment]
一般就是语法不支持问题，看下你的`umi.js`, 行25001，是什么内容，贴出来代码再做下一步判断

**Comment by smz8023** [comment]
Unhandled promise rejection TypeError :cannot call a class as a function

**Comment by sorrycc** [comment]
给复现步骤。

**Comment by smz8023** [comment]
更改了config文件中的targets: {
    ie: 9,
  },
之前是11，更改了9 之后就报这个错误，没有别的步骤了

**Comment by sorrycc** [comment]
那给个可复现的仓库。

**Comment by leftstick** [comment]
@smz8023 你得从这个角度想，你提供的信息是否足够别人帮你解决问题。你两次提供的错误信息，其实先不要怕，不认怂，仔细读一下，你就会发现，这些内容都是些抽象的不能再抽象的废话，类似“报错了”，任谁都不会从按个信息里推导出具体原因的。

这也是issue模板里会要求你提供可复现错误的最小仓库，便于其他人检查问题

**Comment by sorrycc** [comment]
Duplicated https://github.com/umijs/umi/issues/2391，不要重复提相同的问题。

**Comment by zjafei** [comment]
我也是这样的 
[zhgcloud.com.zip](https://github.com/umijs/umi/files/3181306/zhgcloud.com.zip)
上面是我的项目包
