### ISSUE TITLE
antd 样式只能在 global.css 中覆盖吗

### ISSUE THREAD

**Issue by Hongye567** [umijs/umi#234]
使用 `antd-mobile` 中的组件，难以做到针对指定文件的样式覆盖，如下需求：

A 页面需要覆盖 `Button` 的背景色为 red；
B 页面需要覆盖 `Button` 的背景色为 blue。

现在只能在 `global.css` 或者 `:global()` 进行全局的覆盖，无法达到不同页面不同需求。

**Comment by sorrycc** [comment]
可以在 page component 的 root 阶段加 class，比如 `antdm-btn-red`，然后针对这个 class 下的 button 进行覆盖。

**Comment by Hongye567** [comment]
`antd` 的组件里大多都有很多嵌套，如：
```html
<div class="am-button">
    <span class="am-button-text">Button</span>
</div>
```
这个时候我的 class 只能赋值到外层容器，像这样 (my-button-red)：
```html
<div class="am-button my-button-red">
    <span class="am-button-text">Button</span>
</div>
```
这样并不能覆盖 `am-button-text` 的样式

**Comment by sorrycc** [comment]
你期望的方案是怎样？

**Comment by Hongye567** [comment]
在以往使用 react 的时候我只需要 import 我的样式，在我的样式中复写 antd 样式就能覆盖了，如：

```css
/* myButton.css */
.am-button .am-button-text {
  color: red;
}
```

```js
import './myButton.css';
//...
<Button title="Button" />
```

**Comment by ishenli** [comment]
是不是你的样式优先级不够才导致没有覆盖？@Hongye567

**Comment by xiaohuoni** [comment]
```js
.wrapper {
    height: 500px;
     :global {
        .am-button-text {
            padding: 6px;
        }
    }
}
```

**Comment by Hongye567** [comment]
@ishenli 不是不能覆盖，而是想不同的页面不同的覆盖效果

**Comment by xiaohuoni** [comment]
@Hongye567 看我写的那样，可以实现不同页面不同的覆盖效果

**Comment by Hongye567** [comment]
@xiaohuoni 我试了下，你这样写似乎是谁在后面加载，覆盖的样式就是谁的样式；如 B 在 A 后面加载，B 加载结束后 A 就会使用 B 的样式。因为你设置的样式还是全局的 `:global`，并不是针对某个页面的，样式的作用域为整个应用

**Comment by xiaohuoni** [comment]
@Hongye567 你好，我没有认真的测试过你说的这个先后加载的流程，但是我们现在项目中是这么使用的，可以实现，在某个页面下面的样式与其它页面的样式不同，你可以再看看，我忙完手上的事情，再写个demo试试。抱歉
