### ISSUE TITLE
权限路由 Routes 报错

### ISSUE THREAD

**Issue by karchinkong** [umijs/umi#2347]
## What happens?
使用权限路由判断用户是否已经登录,会报下图错误.
![image](https://user-images.githubusercontent.com/16110331/56951183-bdb4ed80-6b69-11e9-9300-e5210729fda0.png)

## How To Reproduce
**Steps to reproduce the behavior:**

.umirc.js 文件路由配置
routes: [
        {
            path: '/',
            redirect: '/app',
        },
        {
            path: '/app',
            component: '../layouts/index',
            Routes: ['src/routes/authority'],
            routes: [
                { path: '/app', component: './index' },
                { path: '/app/a', component: './test' },
            ],
        },
        {
            path: '/login',
            component: './login/login',
        },
    ],

authority.js 文件

import React, { Component } from 'react';
import { connect } from 'dva';
import { Route, Redirect, withRouter } from 'dva/router';
import { message } from 'antd';

class AuthRouter extends Component {
    constructor(props) {
        super(props);

        this.state = {
            isLogged: true,
        };
    }

    render() {
        const { component: Component, ...rest } = this.props;
        const userInfo = localStorage.getItem('userInfo');
        const { isLogged } = this.state;
        if (!userInfo) {
            message.warning('您需要先登陆');
            this.setState({ isLogged: false });
        }
        return (
            <Route {...rest} render={props => {
                return isLogged
                    ? <Component {...props} />
                    : <Redirect to="/login"/>;
            }}/>
        );
    }
}

function mapStateToProps(state) {
    return {
        state,
    };
}

export default connect(mapStateToProps)(withRouter(AuthRouter));

**Expected behavior**
1.页面能展示出来并没有报错

## Context

- **Umi Version**:"^2.6.3",
- **Node Version**: v11.4.0
- **Platform**: mac oc 10.14.1

**Comment by sorrycc** [comment]
请调整下格式，并给下可复现的仓库吧。

**Comment by didilinkin** [comment]
@karchinkong 这代码格式令人窒息， 编辑完后， 用 `Preview` 看一下 效果再发
