### ISSUE TITLE
Create react app + Ant design pro  Jest test  SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by jieliu218** [umijs/umi#2350]
Create react app + Ant design pro

Jest test

Details:

/Users/j.e.liu/Desktop/project/liquid_studio/sok/alepa-korttelitoive-2-frontend/node_modules/umi/index.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { default as Link } from './lib/link';
                                                                                         ^^^^^^

SyntaxError: Unexpected token export

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
给下可复现的仓库。
