### ISSUE TITLE
无意义的报错。

### ISSUE THREAD

**Issue by chenshuai2144** [umijs/umi#2352]
![image](https://user-images.githubusercontent.com/8186664/57010962-f15b4a80-6c31-11e9-90ac-d6e7812cf553.png)

虽然产生了错误，但是没有任何详细的报错信息，需要查看源码排除错误。
并且在源码中找到这一行然后删除。
项目仍然可以正式启动。并且正常运行

具体原因 
validKeys 这个数组中不存在 locale 这个插件的 key。
` validKeys.concat('default').indexOf(key) > -1` 必定报错。删除后可以解决这个问题

复现步骤：
https://github.com/umijs/umi/tree/new-local/packages/umi-plugin-locale/examples/base 
运行 yarn start

**Comment by xiaohuoni** [comment]
<img width="967" alt="runtimeerror" src="https://user-images.githubusercontent.com/11746742/57425697-cdf65800-724e-11e9-92b9-3a5e3d6bf9f3.png">

**Comment by xiaohuoni** [comment]
其实这个问题，比较常遇到的是，使用create-umi创建项目，选择了dva，
然后在config里面，将dva删掉，app.js里面还保留着，dva的配置。就会出错。
我觉得改成错误给提示，错误的配置是失效的，不知道你们觉得如何？

**Comment by sorrycc** [comment]
我觉得应该抛错，但文案得调整下。

**Comment by xiaohuoni** [comment]
@sorrycc 文案要改成啥？
