### ISSUE TITLE
[Feature Request] umi-library 支持非根目录作为组件目录

### ISSUE THREAD

**Issue by iShawnWang** [umijs/umi#2353]
## Background

https://docs.bit.dev/docs/add-and-isolate-components.html

比如 bit 支持跟踪, 打包项目中的某个目录
许多项目的起步是没有 组件库的... 后来业务稳定, 想要整理抽离组件, 但又不想剥离一个 repo, 不太灵活

## Proposal

支持一个配置 `baseDir: './src/components` 来制定组件库根目录
现在的打包代码, 和扩展, 好像都没有考虑这个问题...

**Comment by sorrycc** [comment]
我理解项目里的组件应该不需要 build，只要做 doc dev 就好了。如果是这样，目前就支持的，新建相应的 mdx 文件就好了。
