### ISSUE TITLE
yarn create umi 选择 ant-design-pro模版中的antd样式重复引入打包

### ISSUE THREAD

**Issue by Slebee** [umijs/umi#2358]
## What happens?
使用yarn create umi创建的ant-design-pro项目，antd重复引入了 es/style/index.less与 lib/style/index.less，并且在打包之后也都会被打包进去。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1. yarn create umi
2. 创建 ant-design-pro 项目

**Expected behavior**
1.
2.

## Context

- **Umi Version**: umi@2.6.16
- **Node Version**: 10.11.0
- **Platform**: win32 x64

**Comment by xiaohuoni** [comment]
不要使用yarn create umi创建的ant-design-pro项目
