### ISSUE TITLE
iphone5部分手机不兼容

### ISSUE THREAD

**Issue by yuyuabc1** [umijs/umi#2360]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.  iphone 5 无法正常运行项目
2.  Unknown “Uncaught SyntaxError: Unexpected token <”

**Expected behavior**
1.
2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
target 配了吗？

**Comment by xiaohuoni** [comment]
好像不需要配置target，我们的项目有在iphone5上面跑。
除了hd方案不适配，好像没有其他的问题。
