### ISSUE TITLE
umi block 无法解析 config.ts 

### ISSUE THREAD

**Issue by chenshuai2144** [umijs/umi#2365]
由于 umi 使用了esprima 来解析模块。而 esprima 并不支持解析 Typescript .
我们可能需要一个ts的解析器来实现功能。

复现步骤：
在 pro v4 中进行任意的区块安装。

## 方案
[typescript-formatter](https://github.com/vvakame/typescript-formatter) 
[ts-Compiler](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API)

**Comment by sorrycc** [comment]
block@2 的解析器换成 babel + @babel/preset-typescript， @yutingzhao1991 。

**Comment by chenshuai2144** [comment]
block 2 的具体发布时间是？

**Comment by yutingzhao1991** [comment]
> block 2 的具体发布时间是？

deadline 是 618。不过最晚 530 发一个版本吧，我这两周搞一下看看 520 发个 beta。

**Comment by sorrycc** [comment]
在 https://github.com/umijs/umi/pull/2311 统一跟进。
