### ISSUE TITLE
路由切换后model中state未重置

### ISSUE THREAD

**Issue by WangJM001** [umijs/umi#2366]
## 框架
Antd Pro 2 

## 场景（生产环境）
菜单A:
     /a           model: a.js
     /a/:id

菜单B:
     /b         model:b.js

1、路由从`/a`跳转到`/a/:id`，再返回`/a`
2、`/a`跳转到`/b`

因为菜单A的主列表（`/a`）下有一些过滤及翻页等数据，希望进入详情页（`/a/:id`）后再返回能保留这些数据，切换菜单后model数据重置。现在把数据都存了/a对应的model下，详情返回后state数据依然存在，没有问题。但是当我切换到菜单B后modelA中state数据没有重置，再回去菜单A后modelA中数据依然存在。

**Comment by sorrycc** [comment]
重置功能需要自己处理，框架里没有这部分实现。

**Comment by WangJM001** [comment]
不同路由下model之间不能互相调用，再次进入model不是重新注册？

**Comment by WangJM001** [comment]
我们有很多这种场景，有没有什么思路能通用解决下，插件啥的
