### ISSUE TITLE
umi-library: `appropriate loader` issue while using `umi-lib doc dev`

### ISSUE THREAD

**Issue by leftstick** [umijs/umi#2368]
## What happens?

Following error occurs while `umi-lib doc dev`:

```
./src/index.js 7:21
Module parse failed: Unexpected token (7:21)
You may need an appropriate loader to handle this file type.
|
| class RfReceiver extends React.Component {
>   _fireOriginalClick = e => {
|     const { children } = this.props
|     const childCallback = children.props.onClick
```

## Mini Showcase Repository(REQUIRED)

https://github.com/leftstick/rf-filereceiver

## How To Reproduce
**Steps to reproduce the behavior:**
1. yarn
2. yarn start

You will see errors at terminal

**Expected behavior**
1. doc displayed without any error

## Context

- **Umi Version**: umi-library 1.5.1
- **Node Version**: 11.12.0
- **Platform**: macOS Mojave 10.14.4

And if you try with https://github.com/leftstick/docz-test, (repo with `docz` only), there is no any error

**Comment by sorrycc** [comment]
估计不支持这个语法，换一个语法是不是就好了？

**Comment by sorrycc** [comment]
`.umirc.library.js` 里的 `src: './doc'` 删掉就好了。

**Comment by leftstick** [comment]
真的是，文档和源码只要在同级目录下就可以了。。。。

貌似是这里[docz-core-loaders](https://github.com/pedronauck/docz/blob/master/core/docz-core/src/bundler/loaders.ts#L70)，蓝瘦
