### ISSUE TITLE
page.js文件路由问题

### ISSUE THREAD

**Issue by williamnie** [umijs/umi#237]
当目录结构如下时，启动后，自动生成的路由文件(.umi/router.js)中，不会将page.js以外的目录进行路由打包，
`├── pages/   
                      
        ├── page1

             └── page.js        // 此时路由为： <Route exact path="/page1"   

             └── test

                  └── page.js`
也就是说，当umi遇到page.js文件时，就会自动停止查找同级其他目录文件，如果将page.js给成index.js则不会出现上述问题，不知道是设计成这样还是个bug，请您查看！

**Comment by demohi** [comment]
是这样设计的

**Comment by demohi** [comment]
https://github.com/umijs/umi/issues/105

**Comment by sorrycc** [comment]
关注 #105，马上就解决这个问题了。
