### ISSUE TITLE
umi 能用 immutablejs 吗？

### ISSUE THREAD

**Issue by jiechud** [umijs/umi#2370]
umi 可以用 immutablejs 吗？ 
由于 Redux 中内置的 combineReducers 和 reducer 中的 initialState 都为原生的 Object 对象，需要重写 combineReducers 或使用 redux-immutablejs 来提供支持。
这部分有解决方案吗？

**Comment by sorrycc** [comment]
如果用 dva，配 immer: true 就可以用了。
