### ISSUE TITLE
[Feature Request] 在umi.js中，怎么使用useContext()

### ISSUE THREAD

**Issue by guccihuiyuan** [umijs/umi#2372]
useContext需要传入一个Context类型的参数，我需要全局使用就必须包裹在最外层，但是umi.js封装的太死了，看不到最外层组件，只能从layout组件入手，如果有多个layout，就需要写多次，有什么解决方法吗？

**Comment by sorrycc** [comment]
如果有多个 layout，可以在最上层再加个处理 context 的 route component（layout） 。
