### ISSUE TITLE
升级dva最新版提示Warning: Please use `require("dva").dynamic` instead of `require("dva/dynamic")`. Support for the latter will be removed in the next major release.

### ISSUE THREAD

**Issue by 3478349671** [umijs/umi#2373]
## What happens?

升级dva最新版本，浏览器控制台提示错误

`Warning: Please use `require("dva").dynamic` instead of `require("dva/dynamic")`. Support for the latter will be removed in the next major release.`

## 复现步骤，错误日志以及相关配置

升级dva（2.6.0-beta.3）最新版本，控制台提示错误
`Warning: Please use `require("dva").dynamic` instead of `require("dva/dynamic")`. Support for the latter will be removed in the next major release.`

## 相关环境信息

- **Umi 版本**：2.6.17
- **Dva 版本**：2.6.0-beta.3
- **Node 版本**：11.12.0
- **操作系统**：mac os 10.14.4

**Comment by sorrycc** [comment]
警告信息可忽略，也可以改下代码，换成 `import { dynamic } from 'dva';`。

**Comment by 3478349671** [comment]
好的，谢谢

**Comment by nonespace** [comment]
@sorrycc 在哪里修改这个代码呀
![image](https://user-images.githubusercontent.com/25641088/60063505-c07a2c00-972f-11e9-8376-d334617895dd.png)

**Comment by nonespace** [comment]
搜不到呀
