### ISSUE TITLE
umi-library 配置支持 UMI_ENV

### ISSUE THREAD

**Issue by ycjcl868** [umijs/umi#2375]
## Background

现在只有一个配置文件 `.umirc.library.(ts|js|tsx|jsx)`，并且 配置中不支持配置动态化（根据 NODE_ENV 来指定不同的配置）。

**Comment by ycjcl868** [comment]
增加环境变量支持，或者 配置动态化，都可以

**Comment by sorrycc** [comment]
.umirc.library.js 里不能拿到 process.env.NODE_ENV 等环境变量吗？

**Comment by sorrycc** [comment]
@ycjcl868 找时间排查下？

**Comment by ycjcl868** [comment]
支持的
