### ISSUE TITLE
umi 有没有模块打包模式 类似 angular-cli 的 ngc 

### ISSUE THREAD

**Issue by amily4555** [umijs/umi#238]
如题 并非打包成 web 
而是打包成 React 模块

**Comment by sorrycc** [comment]
需求是啥？把 page component 打包出来复用？

**Comment by amily4555** [comment]
对的，把component打包出来复用，毕竟ant-design并不是万能的
我们需要自己打包一些基于自己系统的常用工具
但是 现在tsc 对非 ts 文件编译没有任何支持， 如 css/sass/less 等
而且 React 对于 tsc 打包出来 es5 的代码似乎有点水土不服 （我在排查，也可能是我的错误）


2018-03-22 10:33 GMT+08:00 chencheng (云谦) <notifications@github.com>:
