### ISSUE TITLE
umi配置文件es6和cmd使用混乱问题

### ISSUE THREAD

**Issue by dkvirus** [umijs/umi#2384]
## What happens?

umi 提供配置文件，在配置文件中使用的是 es6 `import` 和 `export`

```
  /config/config.js
  import os from 'os';
  import pageRoutes from './router.config';
  import webpackPlugin from './plugin.config';
  import defaultSettings from '../src/defaultSettings';
  import slash from 'slash2';

  const { pwa, primaryColor } = defaultSettings;
```

在配置文件中导入其它 js 文件，比如上面的 `import defaultSettings from '../src/defaultSettings';`，导入的 js 文件必须要是 cmd 的 `module.eports` 和 `require` 才能正常启动，如果导入的其它 js 文件里仍然用 es6 的 `import` 和 `export`，启动就会报错。

```
(function (exports, require, module, __filename, __dirname) { import path from 'path';
                                                                     ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    
// .....

Error: 配置文件 ".umirc.js" 解析出错，请检查语法。

SyntaxError: Unexpected identifier
    at onError (/Users/dkvirus/work/krproduct/git/org/org-admin-web/src/main/static/node_modules/umi-build-dev/lib/UserConfig.js:97:13)
```

现在的问题就是：在配置文件里导入的其它 js 文件也需要是 es6 的模块化方法才行，但是不支持。

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

https://github.com/ant-design/ant-design-pro

## 复现步骤，错误日志以及相关配置

- 拉代码，跑起来；
- 用 es6 的 export 导出 `src/defaultSetting.js`；
- 启动项目，报错。

## 相关环境信息

- **Umi 版本**： 2.1.2
- **Node 版本**：10.15.0
- **操作系统**：macOS

**Comment by sorrycc** [comment]
umi 升级到最新，这个问题修复了的。

**Comment by dkvirus** [comment]
@sorrycc  请同步修改 cli 工具自动生成的 umi 脚手架工程里面的 umi 版本，避免其它人重复提问。

**Comment by dkvirus** [comment]
@sorrycc  本地更新 umi 为最新版本 2.6.17，启动项目仍然报错。请确保看清楚我的问题，等我复测通过再关闭 issue，ok？

```
import orgSkeleton from '../src/export';

yntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    // .......

Error: 配置文件 ".umirc.js" 解析出错，请检查语法。

SyntaxError: Unexpected identifier
```

**Comment by peakandyuri** [comment]
我使用的typescript，也试过升级到最新版，但使用import仍然报错

**Comment by zGgoing** [comment]
"umi": "^2.8.7",该问题依然存在

**Comment by jsuper1980** [comment]
昨天正常的代码，今天在公司检出并 yarn 后，报这个错。。。
