### ISSUE TITLE
umi如何禁用某个eslint配置呢

### ISSUE THREAD

**Issue by Luxiaoshi** [umijs/umi#2388]
浏览器和iterm端都报warning如下：
![image](https://user-images.githubusercontent.com/8713879/57425358-6390e800-724d-11e9-8175-a6c3b102c1bb.png)
我希望可以去除这个warning，查了以后在.eslintrc文件中用这个配置，但是无效
"rules":{
    "jsx-a11y/anchor-is-valid":"off"
}
想问，应该如何去除这个warning

**Comment by jiechud** [comment]
@Luxiaoshi  在开发环境上配置 `rules` 好像不起作用，可以在开发环境先关闭检测
![image](https://user-images.githubusercontent.com/9709396/57689754-b6660780-7672-11e9-9629-f00efff74fc8.png)

**Comment by xiaohuoni** [comment]
@sorrycc 要不要加一个eslint配置，用于开启关闭，eslint-config-umi。还有修改和补充eslint-config-umi的rules

**Comment by xfields** [comment]
项目中也遇到了这个问题，通过自己写插件解决了，可以参考下：

**Comment by yutingzhao1991** [comment]
应该会优先用项目自己的 `.eslintrc` 吧，然后可以写成：

```js
{
  extends: "eslint-config-umi",
  rules: {}
}
```

**Comment by tz310200** [comment]
> 应该会优先用项目自己的 `.eslintrc` 吧，然后可以写成：
> 
> ```js
> {
>   extends: "eslint-config-umi",
>   rules: {}
> }
> ```

但是貌似只有vscode 读取了这个配置,umi dev 编译还是会再console打印

**Comment by fengyun2** [comment]
感觉是umi读取eslint的优先级问题，覆盖了也没有效果

**Comment by fengyun2** [comment]
@sorrycc 为何关闭这个问题了呢，如何解决这个问题呢？现在项目启动都是报这个警告. 
![image](https://user-images.githubusercontent.com/8147202/62526241-74142700-b86b-11e9-9205-c2dccccce538.png)

**Comment by lihao-id** [comment]
个人解决是在 `node_modules/@umijs/lint/dist/config/eslint/rules/fabric.js `里面找到了 `@typescript-eslint/no-unused-vars `配置。
于是修改了 .eslintrc.js 的 rules 
`  rules: {
    "@typescript-eslint/no-unused-vars": 0
  }`
