### ISSUE TITLE
不支持get请求本地json

### ISSUE THREAD

**Issue by LuzMariaa** [umijs/umi#2389]
## What happens?
不支持get请求本地json

1. 一般情况下，我们都用 import 引进静态资源或数据文件
2. 但当需要异步请求的场景下，不支持。返回一个函数，路径页面404
3.  期望：如 create-react-app那样，把json文件放在指定文件如public中，就可异步获取

**Comment by sorrycc** [comment]
放 public 目录下的文件可以请求到的。

**Comment by caowenhai888** [comment]
做开源真是不容易

**Comment by jcedo** [comment]
> 放 public 目录下的文件可以请求到的。

有类似的code沙盒吗请问 谢谢
