### ISSUE TITLE
当global.css存在时，IE11将无法渲染页面，并报Promise未定义

### ISSUE THREAD

**Issue by lancelot-song** [umijs/umi#239]
删除后即可正常渲染，本地环境与打包放线上均出现

**Comment by sorrycc** [comment]
？css 和 Promise 有啥关系？

**Comment by lancelot-song** [comment]
css和Promise没关系
但当这个文件存在时，IE11就会报Promise错，即便这个文件是一个空文件
删除后则正常运行，并且不会报错

**Comment by sorrycc** [comment]
Promise 不存在？在 global.js 里加个 `@babel/polyfill` 呢？

**Comment by lancelot-song** [comment]
global.js？我不太清楚指的是哪儿个文件
简单的复现 可以用umi中的示例项目 eleme-demo
umi dev的时候IE11可以正常使用，console也能打印出Promise方法
umi build后则报Promise未定义，页面渲染失败

**Comment by hopperhuang** [comment]
同。打包多页面后，也报了这个错误。还有service-worker不起作用，进入除了首页外的页面后，并没有正常拉取数据和渲染，只渲染出框架，并没有渲染出动态数据。

**Comment by sorrycc** [comment]
> global.js？我不太清楚指的是哪儿个文件

先安装依赖。

```bash
$ tnpm i @babel/polyfill
```

然后新建 src/global.js，内容：

```js
import '@babel/polyfill';
```

**Comment by sorrycc** [comment]
> 进入除了首页外的页面后，并没有正常拉取数据和渲染，只渲染出框架，并没有渲染出动态数据。

没明白，什么症状？

**Comment by lancelot-song** [comment]
完美解决！谢谢~
