### ISSUE TITLE
dva/fetch 跨域 ，服务已经设置可以跨域 ，但还是不行

### ISSUE THREAD

**Issue by caogaofeng0** [umijs/umi#2390]
跨域 dva/fetch
前端设置了 mode:'cors', 后端设置了 可以跨域 res.header("Access-Control-Allow-Origin", "*");
还是报错 提示跨域 报错 如下
Access to fetch at 'http://127.0.0.1:3003/json/index.json' from origin 'http://localhost:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

**Comment by lhr000lhr** [comment]
本地开发使用 proxy的方式来做

**Comment by caogaofeng0** [comment]
> 本地开发使用 proxy的方式来做
现在 设置  proxy: {
    '/json/index': {
      target: 'http://127.0.0.1:3003/',
      changeOrigin: true,
    },
  },
还是报404， 找不到
怎么设置呀？ 上线以后呢

**Comment by caogaofeng0** [comment]
> 本地开发使用 proxy的方式来做
现在 设置  proxy: {
    '/json/index': {
      target: 'http://127.0.0.1:3003/',
      changeOrigin: true,
    },
  },
还是报404， 找不到
怎么设置呀？ 上线以后呢

**Comment by caogaofeng0** [comment]
> > 本地开发使用 proxy的方式来做
> > 现在 设置  proxy: {
> > '/json/index': {
> > target: 'http://127.0.0.1:3003/',
> > changeOrigin: true,
> > },
> > },
> > 还是报404， 找不到
> > 怎么设置呀？ 上线以后呢

这个404 是后端的原因 ，已经解决掉了。
请问 上线怎么配置 ， 是url 直接写后端的地址和端口吗？

**Comment by lhr000lhr** [comment]
可以直接将build 文件部署到 server 下面

**Comment by sorrycc** [comment]
非 umi 问题。

**Comment by monttailee** [comment]
1、注释掉proxy配置；2、服务端添加cors访问项‘http://localhost:8000’
