### ISSUE TITLE
config 配置中组件使用dynamicImport 时，IE10报错！

### ISSUE THREAD

**Issue by smz8023** [umijs/umi#2391]
dynamicImport: {
        loadingComponent: './components/PageLoading/index',
        webpackChunkName: true,
        level: 2,
      },
在config配置dynamicImport报错，
'./components/PageLoading/index：
import React from 'react';
import { Spin } from 'antd';

// loading components from code split
// https://umijs.org/plugin/umi-plugin-react.html#dynamicimport

// const index = () => (
//   <div style={{ paddingTop: 100, textAlign: 'center' }}>
//     <Spin size="large" />
//   </div>
// );
class PageLoading extends React.Component {
  constructor(props){
    super(props);
  }
  render(){
    return <div style={{ paddingTop: 100, textAlign: 'center' }}>
        <Spin size="large" />
    </div>
  }
}
export default PageLoading;

**Comment by sorrycc** [comment]
在 windows 下试过并不会，我的步骤是：

1. create-umi 选 app
2. targets 配 ie9
3. umi build 后在 ie9 下打开，正常

有问题再 reopen。

**Comment by fengyun2** [comment]
@sorrycc 我在windows下设置为 `targets: {ie: 10}`, 运行 `umi dev` 在ie10下运行还是报这个错误。

![image](https://user-images.githubusercontent.com/8147202/62526037-07992800-b86b-11e9-993b-2f33ecd2f295.png)

**Comment by smz8023** [comment]
@fengyun2 最后更改了懒加载的配置解决了，不报错了。你可以试试

**Comment by fengyun2** [comment]
@smz8023 我的配置是

```json
dynamicImport: {
        loadingComponent: './components/PageLoading/index',
        webpackChunkName: true,
        level: 3
      },
```

我看了官方给出的demo也是这样哦，哪里还有问题呢？

**Comment by smz8023** [comment]
当你不用这个的时候，是不是就不报错了？我记得要把一个配置更改成undefined ，就可以咯。具体哪一个忘记了

**Comment by fengyun2** [comment]
@smz8023 删除 `dynamicImport` 配置，在ie11/ie10又会报另外一个bug，而且我的项目比较大，希望可以懒加载路由文件。

版本：
"react": "^16.8.6",
"react-dom": "^16.8.6",
"umi": "^2.8.16",
"umi-plugin-react": "^1.9.14"


![image](https://user-images.githubusercontent.com/8147202/62527651-251bc100-b86e-11e9-9bd4-6451ad48e962.png)

**Comment by smz8023** [comment]
![image](https://user-images.githubusercontent.com/31838004/62528048-cdca2080-b86e-11e9-9c08-2e67a139e788.png)
你可以试试我之前的解决方案~

**Comment by fengyun2** [comment]
@smz8023 谢谢，异步加载的BUG解决了，但是在ie下还是存在这个问题

![image](https://user-images.githubusercontent.com/8147202/62529546-6feb0800-b871-11e9-95df-2bc8ca199f21.png)

**Comment by stupid2013** [comment]
> @smz8023 谢谢，异步加载的BUG解决了，但是在ie下还是存在这个问题
> 
> ![image](https://user-images.githubusercontent.com/8147202/62529546-6feb0800-b871-11e9-95df-2bc8ca199f21.png)

请问你这个问题解决了吗，我的项目也会报这个错。。。
