### ISSUE TITLE
umi配置文件es6和cmd使用混乱问题

### ISSUE THREAD

**Issue by dkvirus** [umijs/umi#2393]
> 官方回复说最新版的 umi 已修复，我更新了 Umi 版本为 2.6.17，仍然存在这个问题，请确认下该功能是否修复。: ) 等我复测通过之后我会关闭此 issue，请不要立即关闭，按照格式提 issue 也是需要花时间的。🙏🙏🙏

## What happens?

umi 提供配置文件，在配置文件中使用的是 es6 `import` 和 `export`

```
  /config/config.js
  import os from 'os';
  import pageRoutes from './router.config';
  import webpackPlugin from './plugin.config';
  import defaultSettings from '../src/defaultSettings';
  import slash from 'slash2';

  const { pwa, primaryColor } = defaultSettings;
```

在配置文件中导入其它 js 文件，比如上面的 `import defaultSettings from '../src/defaultSettings';`，导入的 js 文件必须要是 cmd 的 `module.eports` 和 `require` 才能正常启动，如果导入的其它 js 文件里仍然用 es6 的 `import` 和 `export`，启动就会报错。

```
(function (exports, require, module, __filename, __dirname) { import path from 'path';
                                                                     ^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    
// .....

Error: 配置文件 ".umirc.js" 解析出错，请检查语法。

SyntaxError: Unexpected identifier
    at onError (/Users/dkvirus/work/krproduct/git/org/org-admin-web/src/main/static/node_modules/umi-build-dev/lib/UserConfig.js:97:13)
```

现在的问题就是：在配置文件里导入的其它 js 文件也需要是 es6 的模块化方法才行，但是不支持。

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

https://github.com/ant-design/ant-design-pro

## 复现步骤，错误日志以及相关配置

- 拉代码，跑起来；
- 用 es6 的 export 导出 `src/defaultSetting.js`；
- 启动项目，报错。

## 相关环境信息

- **Umi 版本**： 2.6.17
- **Node 版本**：10.15.0
- **操作系统**：macOS

**Comment by sorrycc** [comment]
https://github.com/ant-design/ant-design-pro master 分支跑不起来？

**Comment by dkvirus** [comment]
@sorrycc

### 问题复现

master 分支最新代码 `src/defaultSetting.js`  默认是 `module.exports` (node 模块化) 导出的配置对象，我想要以 `export default`(es6模块化) 导出。一改成 export default 启动就会报错。

```
export default {
  navTheme: 'dark', // theme for nav menu
  primaryColor: '#1890FF', // primary color of ant design
  // ........
};
```

### 为什么我要用 export default??

配置文件 config/config.js 里有一个属性是 routes，我需要导入页面组件，做个性化修改。

在写页面组件都是用 `export default` 导出的组件，现在在配置文件里就无法导入这个组件。。

```
export default class User extends React.Component {
    render () {
        return  (.....)
    }
}
```

**Comment by dreamlin517** [comment]
我也遇到这个问题了，请问什么时候能解决。

**Comment by dkvirus** [comment]
@sorrycc  同问，啥时候修复这个问题。 : )

**Comment by dkvirus** [comment]
使用的typescript，也试过升级到最新版，但使用import仍然报错

@sorrycc  这个问题考虑修复不。

**Comment by dkvirus** [comment]
@sorrycc 大佬

**Comment by sorrycc** [comment]
这个问题比较麻烦，而且优先级相对不高，有办法先绕过去么？

**Comment by dkvirus** [comment]
找到替代方法了。

.umirc.js 只能处理 cjs 模块化，但是 pages 目录里可以处理 cjs 和 esm 两种格式的模块化。

npm 包对外暴露的入口文件既可以使用 import/export ，也可以使用 require/exports，但在发布包之前使用 `fathter` 或其它编译工具进行一次编译。`$ father build --cjs babel`，这样入口文件就是 cjs 模块化了，.umirc.js 引入也就不会再报错了，普通 pages 文件也能引用底层 npm 包暴露出来的方法了。

**Comment by hysyer** [comment]
import { primaryColor } from '../src/defaultSettings';
require = require("esm")(module);
const routes = require('../src/configs/routes').default;
可以使用esm模块处理

**Comment by lyqeyes** [comment]
2019.10.16, umi版本2.10.4
发现问题还存在.
与上面描述一致: 在config/config.js文件中import /src目录下的某个es module文件会报错: 

> SyntaxError: Unexpected token export

将模块换成CommonJS的写法则能成功编译. 
<hr/>

使用场景: 

> config.js中配置路由, 路由的path配置使用到了/src目录下统一定义的常量, 且常量被/src下其他模块共用.

**Comment by TronSun** [comment]
我也遇到了同样的问题

**Comment by caoxu331** [comment]
通过
require = require("esm")(module);
const routes = require('../src/configs/routes').default;
可以达到目的，但是无法加载ts，想要保留ts的类型提示，不知道咋办了
