### ISSUE TITLE
config 配置 dynamicImport 引用路劲 IE10  报错！！！！

### ISSUE THREAD

**Issue by smz8023** [umijs/umi#2395]
dynamicImport：{ 
loadingComponent：'。/ component / PageLoading / index'，
webpackChunkName：true，
level：2，
}，
在config配置dynamicImport报错，
'./components/PageLoading/index：
import来自'react'的React; 
从'antd'导入{Spin};

//从代码拆分中加载组件
// https://umijs.org/plugin/umi-plugin-react.html#dynamicimport

// const index =（）=>（
// <div style = {{paddingTop：100，textAlign：'center'}}> 
// 
// 
//）; 
class PageLoading扩展了React.Component { 
constructor（props）{ 
super（props）; 
} 
render（）{ 
return <div style = {{paddingTop：100，textAlign：'center'}}> 

} 
} 
export default PageLoading;

**Comment by sorrycc** [comment]
Duplicated https://github.com/umijs/umi/issues/2391 ，不要重复提相同的问题。
