### ISSUE TITLE
样式的引入对开发体验很不友好

### ISSUE THREAD

**Issue by lemondreamtobe** [umijs/umi#2397]
![image](https://user-images.githubusercontent.com/22766436/57509248-57cd2080-7336-11e9-85c7-fc63e8108051.png)
![image](https://user-images.githubusercontent.com/22766436/57509257-5c91d480-7336-11e9-8ae7-c4f63a589fd3.png)
这样引入样式相当麻烦。可不可以像下图一样直接引入css/less文件。className直接写字符就好了。
![image](https://user-images.githubusercontent.com/22766436/57509311-7f23ed80-7336-11e9-9d51-502aab8367f3.png)
目前刚用umi。发现这个点非常不友好

**Comment by afc163** [comment]
http://www.ruanyifeng.com/blog/2016/06/css_modules.html 了解一下
