### ISSUE TITLE
umi.js es6  conversion is not completely，android 5.0

### ISSUE THREAD

**Issue by m9rco** [umijs/umi#2399]
## What happens?

version 

```
"umi": "~2.4.4",
```

Under the path `umi.js `  There `es6 ` transformation， Conversion is not completely

```
/umi.js
```

It will lead to the exception occurs

![image](https://user-images.githubusercontent.com/18391791/57529803-603e4f00-7368-11e9-87f1-781f68c2a8cd.png)

find `umi.js`

```
 const sagaMiddleware = createSagaMiddleware()\n          const store = createStore(reducer, applyMiddleware(sagaMiddleware))\n          sagaMiddleware.run(saga, ...args)\n      ');
```

![image](https://user-images.githubusercontent.com/18391791/57530124-26ba1380-7369-11e9-88d2-1bd2f10629a1.png)

Syntax error cause the program crash 

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

**Expected behavior**

## Context

- **Umi Version**: 2.4.4
- **Node Version**: v8.11.3
- **Platform**:

**Comment by sorrycc** [comment]
给下可复现仓库，看起来像是 dva 的问题。
