### ISSUE TITLE
umi-request - Request payload [object Object]

### ISSUE THREAD

**Issue by tranducit95** [umijs/umi#2401]
## What happens?

Data sent to the server are in the form [object Object], each request I have to use JSON.stringify (data)
I tried many ways, requestType: 'json' but failed, please help me. thank you.

## 相关环境信息

- **Umi 版本**："umi": "^2.4.4", "umi-request": "^1.0.7"
- **Node 版本**：v8.10.0
- **操作系统**：ubuntu 18.04

**Comment by sorrycc** [comment]
给下可复现例子。

**Comment by clock157** [comment]
try to use `requestType: 'form' `
