### ISSUE TITLE
约定式路由如何指定动态路由的匹配模式

### ISSUE THREAD

**Issue by superchow** [umijs/umi#2403]
在配置路由中可以在 path 里使用正则实现，那约定式路由如何实现呢？
配置路由的动态路由匹配模式：[issues2272](https://github.com/umijs/umi/issues/2272#issuecomment-483476727)

**Comment by sorrycc** [comment]
没理解匹配模式指啥？

**Comment by superchow** [comment]
比如这个链接 `http://localhost:8000/bot/librarySystem/index/155607494335657` 我如何指定 `155607494335657` 的格式

**Comment by sorrycc** [comment]
目前不支持，有啥建议吗？

**Comment by superchow** [comment]
可否跟 [通过注释扩展路由](https://umijs.org/zh/guide/router.html#%E9%80%9A%E8%BF%87%E6%B3%A8%E9%87%8A%E6%89%A9%E5%B1%95%E8%B7%AF%E7%94%B1) 这种形式类似， 加个 `rule`

**Comment by xiaohuoni** [comment]
https://umijs.org/zh/plugin/umi-plugin-react.html#routes
通过它可以处理嘛？

**Comment by sorrycc** [comment]
> 可否跟 通过注释扩展路由 这种形式类似， 加个 rule

这只能处理文件，对动态路由的目录无效。

**Comment by superchow** [comment]
```
+ pages/
  + users/
    - $id$.js
  - index.js
```
然后在 `$id$.js` 文件头部加个 **注释**  `rule: /\d+/`

生成的路由配置自动加上规则

```
[
  { path: '/': component: './pages/index.js' },
  { path: '/users/:id(\\d+)': component: './pages/users/$id$.js' },
]
```

**Comment by superchow** [comment]
> https://umijs.org/zh/plugin/umi-plugin-react.html#routes
> 通过它可以处理嘛？

可以尝试下，目前项目用的是配置式的

**Comment by wgh970312** [comment]
看了.core里的routes 为什么:id(\\d+)会被打包成:id(/d+)  ？？？导致path-to-regexp无法匹配，我试了直接改.core里的routes，是可以用的
