### ISSUE TITLE
Umi Request. Support Path in the url

### ISSUE THREAD

**Issue by nguyenhuutinh** [umijs/umi#2404]
Hello team, thanks for incredible lib.
But I cannot find the way to replace id in url
example: 
I want "/api/v1/import/orders/14/products"
so
return request(`/api/v1/import/orders/:id/products`, {
    method: 'PUT',
    params :{id: params.body.id},
    data: {
      ...params.body,
    },
    
  });

but it does not  . please suggest. thanks

**Comment by sorrycc** [comment]
@clock157  Do we support this?

**Comment by yutingzhao1991** [comment]
You can write like this:

```js
request(`/api/v1/import/orders/${params.body.id}/products`, {
  method: 'PUT',
  data: {
  ...params.body,
  },
});
```
