### ISSUE TITLE
yaml语法配置权限路由不生效

### ISSUE THREAD

**Issue by YuetTusi** [umijs/umi#2405]
使用yaml语法来定义权限路由如下：

```javascript
/**
 * title: Login
 * Routes: 
 *  -  ./src/LoginValidate.js
 */
```
运行umi没有执行LoginValidate.js，在.umi/router.js中查看代码发现umi并没有识别yaml语法，请问是不是还需要配置一些东西？

**Comment by sorrycc** [comment]
如何复现？

**Comment by soolx** [comment]
应该是umi-build-dev里的依赖esprima-extract-comments被删掉的原因

**Comment by sorrycc** [comment]
有问题再 reopen。
