### ISSUE TITLE
dev环境缓存

### ISSUE THREAD

**Issue by shawn-play** [umijs/umi#2408]
## What happens?
在dev MOCK=none的本地服务器，出现缓存。页面刷新但是不能反馈更改内容，并且不能清除。需要删除.umi文件夹以及重启本地服务才能奏效。并且在下次启动本地服务器，还会有类似情况出现，缓存的内容是在首次出现缓存时的内容，没有中间版本的缓存出现。已经是在第二个项目中有类似的情况。项目是dva + umi + antd构建的。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Umi Version**: 2.2.2
- **Node Version**: 8.11.1
- **Platform**:

**Comment by sorrycc** [comment]
如何复现？

**Comment by sorrycc** [comment]
你是用外部 ip 访问还是本地访问？

**Comment by shawn-play** [comment]
> 你是用外部 ip 访问还是本地访问？

本地localhost访问的

**Comment by shawn-play** [comment]
> 如何复现？

**Comment by shawn-play** [comment]
> 如何复现？

不能复现，但是出现缓存之前，做了和路由相关的改动，也及时重启了项目
