### ISSUE TITLE
区块添加的宏替换能否支持文件名的替换

### ISSUE THREAD

**Issue by astonishqft** [umijs/umi#2409]
区块添加的宏替换功能很强大，可以避免区块添加到应用中出现冲突，
想请教下宏替换能否支持文件名的替换？感谢

**Comment by xiaohuoni** [comment]
请问什么情况下会用到宏替换文件名？
新增区块，文件名应该是新增的
往现有页面增加区块，应该不需要改文件名吧？

**Comment by astonishqft** [comment]
比如我现在有个需求：
项目使用的是umi + mobx，基于这个去实现的（https://github.com/umijs/umi-examples/tree/master/mobx-state-tree）
现在需要通过umi block add --path 新增一个空的mobx模板区块，空模板下面的store目录下的文件名需要能指定，因为store是由文件名划分的，添加多个区块的时候要求不能重复。
![示例](https://user-images.githubusercontent.com/15138753/57906511-d7b23800-78ac-11e9-9b26-c6ad3baa3bfa.png)
