### ISSUE TITLE
[Feature Request] Improve conventional router for complex project: only read index.js

### ISSUE THREAD

**Issue by yutingzhao1991** [umijs/umi#2412]
## Background

约定式路由可以让文件结构和路由直接对应上，减少了隐含存在的一份路由配置的冗余，同时也让查看项目结构变得更方便，开发起来也少了一些工作。但是对于大型项目来说存在一个问题：

- 路由组件太大之后需要拆分为多个组件，拆分出来的内容需要 ignore 掉，不然会被识别为约定式路由。

## Proposal

约定式路由是否可以只识别 index.js。

**Comment by xiaohuoni** [comment]
我现在在[alita](https://github.com/alitajs/alita)里面就是这么处理的，只有index.js生效。但是在需要约定式嵌套路由的时候，很不好处理。(因为我们公司项目，没有用到约定式嵌套路由的情况，只在 layout/index.js 里面做了 layout 区分)
在umi项目中，你可以尝试配置routes
```js
routes: {
      // 规定只有index文件会被识别成路由
      exclude: [
        /(?<![\s\S]*index\$?\.(js|jsx|ts|tsx)?)$/,
        /model\.(j|t)sx?$/,
        /\.test\.(j|t)sx?$/,
        /service\.(j|t)sx?$/,
        /models\//,
        /components\//,
        /services\//
      ]
    },
```
