### ISSUE TITLE
开发过程中，热更新文件无限增加

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#2414]
![image](https://user-images.githubusercontent.com/11746742/57675045-688dd700-7653-11e9-80f3-4beaa7360f20.png)

## What happens?
在开发过程中，开发一段时间后，每一次保存会新增一个hot-update文件，
会无限增加，导致热更新很慢很卡。
还会导致电脑变得卡顿

## Mini Showcase Repository(REQUIRED)
任意的umi项目都行，触发条件未知，非毕现bug

## How To Reproduce
**Steps to reproduce the behavior:**
1.启动umi dev，正常业务开发

**Expected behavior**
1.正常热更新
2.不管开发持续多长实现，都和刚刚启动dev服务一样流畅

## Context

- **Umi Version**: 2.6.17
- **Node Version**:10.15.0
- **Platform**: Mac

**Comment by afc163** [comment]
看下 create-react-app 怎么解决的

**Comment by zhangyuang** [comment]
这是正常情况，本来hmr就是通过这样实现的

**Comment by sorrycc** [comment]
hmr 的机制就是这样吧，hot-update.js 文件理论上很小的。

**Comment by xiaohuoni** [comment]
@sorrycc 
这个文件有时候会出现在这里，有时候不会。
当它开始出现之后。
16G内存的Mac，在继续日常开发工作，半小时左右，内存接近100%。
@zhangyuang 
我理解的hmr机制，应该是最后一个文件有效的吧。

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/57746664-c3cbd200-7704-11e9-8da5-4ff1e8cfa781.png)
@sorrycc 这是正常的嘛？

**Comment by zhangyuang** [comment]
> @sorrycc
> 这个文件有时候会出现在这里，有时候不会。
> 当它开始出现之后。
> 16G内存的Mac，在继续日常开发工作，半小时左右，内存接近100%。
> @zhangyuang
> 我理解的hmr机制，应该是最后一个文件有效的吧。

本质上umi 的hmr是通过webpack-dev-server来做的，每次修改都会生成一个新的hot-update来实现局部替换，本地开发webpack-dev-server将静态资源文件是编译在内存中的。内存100%你可以排查下用量，不太可能是因为这个造成的，chrome日常飙高内存

**Comment by xiaohuoni** [comment]
@zhangyuang 谢谢，学习了。
我再去看看，什么原因导致的开发卡顿问题。Mac和window都会。

**Comment by zhangyuang** [comment]
> @zhangyuang 谢谢，学习了。
> 我再去看看，什么原因导致的开发卡顿问题。Mac和window都会。

亲身经验。。。一般都是chrome和vscode导致的。。chrome可以装个冻结长时间不用的tab的扩展，vscode的配置把node_modules给忽略掉

**Comment by xiaohuoni** [comment]
@zhangyuang 请问这个如何配置？ 
> vscode的配置把node_modules给忽略掉

**Comment by zhangyuang** [comment]
> @zhangyuang 请问这个如何配置？
> 
> > vscode的配置把node_modules给忽略掉

 "search.followSymlinks": false,
  "files.useExperimentalFileWatcher": true,
  "files.exclude": {
    "/.git": true,
    "/.DS_Store": true,
    "/node_modules": true,
    "/node_modules/": true
  },
  "search.exclude": {
  "/node_modules": true
  },

**Comment by sorrycc** [comment]
看起来不是 umi 的问题。

**Comment by xiaohuoni** [comment]
@zhangyuang 默认设置就是排除了node_modules的，感觉不是这个问题。

**Comment by xiaohuoni** [comment]
@sorrycc 我会持续跟进，暂时不确定是umi的问题，有问题再reopen

**Comment by atzcl** [comment]
@xiaohuoni 同有这个问题，而且越来越严重了，使用其他脚手架类似 create-react-app、easywebpack 则不会，起初怀疑是 chrome 的版本问题，结果现在升级了 3 个版本了，还是一样

**Comment by exvu** [comment]
@xiaohuoni 是否找到原因？

**Comment by MagicHacker** [comment]
我不引入moment就没啥事了

**Comment by xiaohuoni** [comment]
后面更新了版本就没遇到过这个问题了。
