### ISSUE TITLE
难道没有这样的需求在输出的js后面添加参数的？

### ISSUE THREAD

**Issue by JayenLee** [umijs/umi#2415]
默认输出的是umi.js 能不能自定义这个名字？一定是这个默认名字吗？文档里面很不全啊

**Comment by sorrycc** [comment]
为啥要自定义名字？

**Comment by xiaohuoni** [comment]
我觉得还是使用umi.js最好，别人发布线上的代码，看一眼就知道是umi技术栈的，在还接手二手代码项目的时候，很有自信。

**Comment by JayenLee** [comment]
但是经常会有这种需求，就是js后面会加一些?t=test这种，尤其是用api网关做代理后，同一个域名是希望希望不同的参数做环境切换，本来webpack是支持的，但是昨天测试发现umi应该是把这个功能给屏蔽掉了，写到入口html里面的根本不支持，要么就报chunkmap没有。

**Comment by sorrycc** [comment]
加 `?t=test` 之类的参数和 umi 的文件名应该无关吧。

**Comment by JayenLee** [comment]
额，这个是跟标题来的，描述是因为我用webpack测试可以通过修改文件名实现标题所说的功能，但是我的目的还是需要在生成的js后面添加自定义参数?t=test
