### ISSUE TITLE
执行umi -v，会运行项目中已使用的所有的插件

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#2419]
## What happens?
```sh
$ umi -v
cordova platform use ios
please run "umi cordova --init --ios" to init cordova and add cordova platform
umi@2.6.17
```
这里只是一个例子，其他插件也有同样的问题。
## 复现步骤
```sh
$ create-umi
选择 plugin
```
修改`src/index.ts`
```js
export default function (api, options) {
    console.log('plugin used!');
}
```
```sh
$ cd example
$ umi -v
plugin used!
umi@2.6.17
```

## 相关环境信息

- **Umi 版本**：2.6.17
- **Node 版本**：10.13.0
- **操作系统**：Mac

## 预期效果
希望执行`umi -v`的时候不要加载其他的插件，因为有些插件带有副作用。
但是这会导致 `addVersionInfo ` 不可用。
所以期望能够提供一个新的 API，来区分当前执行的 Command 。

**Comment by sorrycc** [comment]
副作用放 `api.onStart` 里。

**Comment by xiaohuoni** [comment]
`api.onStart` 这个可以处理， `umi -v`的问题，确实是不会执行其他插件。
但是注册的其他命令，比如我 `registerCommand` 一个命令 `abc` 。
执行`umi abc` 也会触发 `api.onStart`
要不要直接`if(presentCommand !== 'dev') return;`这样子的方式简洁一点。
