### ISSUE TITLE
在umi 中使用 react-intl, 路由变化没有刷新视图

### ISSUE THREAD

**Issue by maxiaochuan** [umijs/umi#242]
- 问题描述:
     在layouts/index.tsx中使用 IntlProvider, 使用routerRedux.push()方法,  地址发生变化但是视图没有更新.
- 问题原因:
     IntlProvider组件有 shouldComponentUpdate的检测, 在state props 都没有发生变化的时候并不更新组件.
- 解决方法:?
     我思考到的解决办法是在 IntlProvider中传入一个 location

期待更好的解决方案

**Comment by zjxpcyc** [comment]
是不是需要使用 withRouter ?
https://reacttraining.com/react-router/web/api/withRouter

**Comment by sorrycc** [comment]
https://github.com/umijs/umi/tree/master/examples/func-test
在这里试了下 func-test，没发现切换后视图不更新。

解决不了的话，给个可重现的例子吧。

**Comment by maxiaochuan** [comment]
这个是我描述的不清晰了,
使用的 umi + umi-plugin-dva + react-intl,
刚才写了一个示例
https://github.com/maxiaochuan/umi-with-intl
我感觉就是 IntlProvider的问题, 如过在它的props加上 location 就没问题了 @sorrycc

**Comment by sorrycc** [comment]
在 [with-dva](https://github.com/umijs/umi/tree/master/examples/with-dva) 里试了下，没有发现问题。
