### ISSUE TITLE
prompt cannot block router change

### ISSUE THREAD

**Issue by Lynn0108** [umijs/umi#2421]
## What happens?
when i change the router, prompt give a confirm window, but the router is already changed.

![image](https://user-images.githubusercontent.com/25974463/57779112-12568c00-7758-11e9-9339-04ae60122575.png)
![image](https://user-images.githubusercontent.com/25974463/57779102-0f5b9b80-7758-11e9-8405-51e566715381.png)

## Mini Showcase Repository(REQUIRED)
i use the example you provide

```js
import Prompt from 'umi/prompt';

export default () => {
  return (
    <>
      <h1>Prompt</h1>
      <Prompt
        when={true}
        message={(location) => {
          return window.confirm(`confirm to leave to ${location.pathname}?`);
        }}
      />
    </>
  );
}
```

## How To Reproduce
**Steps to reproduce the behavior:**
1.open detail page
2.change router

**Expected behavior**
1.router change only when i confirm it 

## Context

- **Umi Version**:v2.4.4
- **Node Version**:v10.10.0
- **Platform**: chrome

**Comment by xiaohuoni** [comment]
please refer  https://github.com/umijs/umi-examples/tree/master/routes

**Comment by Lynn0108** [comment]
> please refer https://github.com/umijs/umi-examples/tree/master/routes

I tried it and found the problem happen because i use router.goBack() instead of umi/link. It will change the route immediately.

 what can i do to block route change when using router function to change route?

**Comment by sorrycc** [comment]
Do `router.push()` work? I guess it's the problem with back.

**Comment by Lynn0108** [comment]
> Do `router.push()` work? I guess it's the problem with back.

It works. 
`umi/link` and `router.push()` need a specific path，what about I don't know the path and just want to go back ?

**Comment by sorrycc** [comment]
I think react-router don't support this.

**Comment by Lynn0108** [comment]
thx~
