### ISSUE TITLE
更新umi的个人建议！！

### ISSUE THREAD

**Issue by li2215890610** [umijs/umi#2422]
## What happens?

umi是我用dva-cil之后的又一个框架，当umi发布版本的时候就开始用了，最近遇到了一个我觉得在我开发中碰到的问题，当umi更新之后，我想跟随umi的版本来更新对应的依赖

类似于Taro这样的操作：
https://nervjs.github.io/taro/docs/GETTING-STARTED.html

![image](https://user-images.githubusercontent.com/19567679/57821966-15d42c80-77c5-11e9-8768-9ff0192eab12.png)

当然我也可以用别的野路子来更新各种umi的依赖。

我只是站在我的角度，来觉得那样更方便而已。

这个是否能得到反馈，并纳入umi的开发计划我还是很期待的。

**Comment by zhangyuang** [comment]
....你只要版本号用^就可以用大版本最新的了

**Comment by li2215890610** [comment]
> ....你只要版本号用^就可以用大版本最新的了

谢谢你。
这个我知道的，我是建议umi 也搞一个类似于 Taro这样的版本更新命令，这样快捷一点

**Comment by sorrycc** [comment]
umi 升大版本时可能会提供 codemod，mirror 和 bugfix 版本的升级用户不需要有感知的，用 `^` 前缀就好了。

**Comment by li2215890610** [comment]
> umi 升大版本时可能会提供 codemod，mirror 和 bugfix 版本的升级用户不需要有感知的，用 `^` 前缀就好了。

好吧 谢谢
