### ISSUE TITLE
mock 数据在rest里包含queryString不工作

### ISSUE THREAD

**Issue by zxs2162** [umijs/umi#2424]
## What happens?

在mock目录下面创建自己的mock data：
module.exports = {
    [`GET ${ApiPrefix}/dashboard`](req, res) {
        res.status(200).json(database)
    },
    [`GET ${ApiPrefix}/people?maxSizes=3`](req, res) {
        res.status(200).json(persons)
    },
...
}

以上两个REST， 第一个后面没有queryString,zhchang工作，第二个后面有maxSize导致错误：

[HPM] Error occurred while trying to proxy request /api/mock/people?maxSize=3 from localhost:7000 to http://localhost:9999/ (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by sorrycc** [comment]
没理解你的问题，另外需要可复现仓库。

**Comment by zxs2162** [comment]
已经解决，这个是mock的问题。
对于需要的REST， 如果RESTURL包含参数， 在mock拦截的中间不能增加该参数。

譬如， 在真实代码里访问REST:
/people?maxSizes=3

MOCK里必须监听如下URL， 不能附加参数（maxSize)： 
[GET ${ApiPrefix}/people](req, res) {

const {
            query
        } = req
        let {
            maxSizes
        } = query

res.status(200).json(persons)
}
