### ISSUE TITLE
yarn create umi失败 文件名、目录名或卷标语法不正确

### ISSUE THREAD

**Issue by FredaMJ95** [umijs/umi#2425]
![image](https://user-images.githubusercontent.com/26449438/57834963-13d39300-77f0-11e9-9cdc-6b1b9b8d9873.png)

**Comment by sorrycc** [comment]
手动执行 `create-umi` 会不会报错？

**Comment by manyhelp** [comment]
怎么解决的？ yarn create umi 还是报错 @sorrycc

**Comment by chenjiacun35** [comment]
> 怎么解决的？ yarn create umi 还是报错 @sorrycc

在Windows 10中我的解决方法是：

**Comment by snowwindsand** [comment]
应该是修改了npm或者yarn的全局目录导致的问题，默认不修改是可以的，解决方法就是上面chenjiacun35所说的。

**Comment by lichangchao15442** [comment]
现在create-umi.cmd文件是一下内容：
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir//bin/sh" ]; then
  "$basedir//bin/sh"  "$basedir/C:/Users/lichangchao/AppData/Local/Yarn/Data/global/node_modules/.bin/create-umi" "$@"
  ret=$?
else 
  /bin/sh  "$basedir/C:/Users/lichangchao/AppData/Local/Yarn/Data/global/node_modules/.bin/create-umi" "$@"
  ret=$?
fi
exit $ret
这种又该怎么修改呢？
