### ISSUE TITLE
request.js 第一次获取不到Storage作用率的值

### ISSUE THREAD

**Issue by mxthd** [umijs/umi#2436]
用户登录成功后,我将token存在localStorage中,request.js使用localStorage.getItem("token")时没有获取到数据,但是我在其他组件内是可以获取到的.

但是h5刷新浏览器后就可以获取到了,

https://yq.aliyun.com/ask/496797

**Comment by wang5909912** [comment]
@mxthd  这个是怎么解决的呢？
