### ISSUE TITLE
_mock.js 文件不支持别名路径

### ISSUE THREAD

**Issue by dkvirus** [umijs/umi#2438]
## What happens?

在 `.umirc.js` 文件中配置了路径别名

```
// .umirc.js
alias: {
      configs: path.resolve(process.cwd(), 'src/configs'),
  },
```

在 `_mock.js` 中使用别名声明的全局路径，会报错。

```
import { apiPrefixMock } from 'configs/config.js';
```

报错信息：

```
✖  error     Mock file parse failed
Error: Cannot find module 'configs/config.js'
```

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**

期待在 `_mock.js` 中使用别名路径。

```
import { apiPrefixMock } from 'configs/config.js';
```

## Context

- **Umi Version**: 2.6.17
- **Node Version**: v10.15.0
- **Platform**: MacOS 10.13.6

**Comment by dkvirus** [comment]
@i5ting 前辈，这个 bug 能帮忙修复下吗？

**Comment by sorrycc** [comment]
mock 不走编译，webpack 的别名配置对他不生效的。
