### ISSUE TITLE
umi和antd pro 怎么结合使用?

### ISSUE THREAD

**Issue by tianlinzx** [umijs/umi#244]
这个和antd pro 怎么结合使用?

**Comment by sorrycc** [comment]
antd-pro 的 [component](https://pro.ant.design/components/AvatarList-cn) 可以直接用，antd-pro 项目预计等 umi@1.1 支持嵌套路由之后才可以。

**Comment by boxcc** [comment]
大概做了一个demo  https://github.com/boxcc/umi-pro   还有些没做完
