### ISSUE TITLE
[Feature Request] Support typescript error check in umi dev

### ISSUE THREAD

**Issue by robert-zaremba** [umijs/umi#2442]
## Background

When using `umi dev` with typescript, it will watch and compile all typescript files on the fly. It will also use the local `tsconfig.json`. However it doesn't display any typescript type errors and warnings. Hence we need to run `npx tsc --noEmit` to see typescript errors.

On the other hand when using `create-react-app my-app --typescript` and then `react-scripts start` will monitor and display all typescript errors.

## Proposal

When using `umi` with typescript, show all typescript compilation errors and warnings.

## Additional context

I've created a Stackoverflow question to see if there is an easy solution for that: https://stackoverflow.com/questions/56119734/how-i-can-instrument-umijs-to-output-typescript-type-errors

### Example project with typescript setup:

https://github.com/robert-zaremba/react-umi-antdpro-ts-bootstrap/

**Comment by sorrycc** [comment]
Try the [FORK_TS_CHECKER](https://umijs.org/guide/env-variables.html#fork-ts-checker) env variable.

**Comment by robert-zaremba** [comment]
This works. Thanks. The build time (in umi watch mode) is a bit longer. Is this the right way to do? Shall we close this issue?
