### ISSUE TITLE
多个umi.js项目怎么相互之间调用model?

### ISSUE THREAD

**Issue by congceng999** [umijs/umi#2450]
比如我的项目结构如下所示：

```
    app-a/
        .umirc.js
          src/
             model
   app-b/
       .umirc.js
        src/
            model
```

app-a想改变app-b/src/model层reducer的数据应该怎么做？项目打包时会单独打包

**Comment by sorrycc** [comment]
两个应用一起跑？要么有父应用做信息串联，要么就通过全局变量或其他事件库串起来。

**Comment by congceng999** [comment]
> 两个应用一起跑？要么有父应用做信息串联，要么就通过全局变量或其他事件库串起来。

两个应用一起跑的，运行在不同的电脑上，但是打包后这两个文件会在同一台服务器下面,需求就是app-a想控制app-b的弹框,。全局变量怎么设置？window应该行不通，浏览器环境不一样

**Comment by sorrycc** [comment]
目前默认情况下不支持两个应用一起跑，需要借助微前端方案才行，比如 https://github.com/umijs/umi-plugin-single-spa

**Comment by congceng999** [comment]
> 目前默认情况下不支持两个应用一起跑，需要借助微前端方案才行，比如 https://github.com/umijs/umi-plugin-single-spa

谢谢，会解决我的需求，希望这个方案尽快成熟

**Comment by congceng999** [comment]
> 目前默认情况下不支持两个应用一起跑，需要借助微前端方案才行，比如 https://github.com/umijs/umi-plugin-single-spa

谢谢，会解决我的需求，希望这个方案尽快成熟
