### ISSUE TITLE
umi-request的multipart/form-data的bug

### ISSUE THREAD

**Issue by mankeheaven** [umijs/umi#2451]
## What happens?
使用axios可以，使用umi-request不行，multipart/form-data的情况
```
axios({
      method: 'post',
      url: serverUrl,
      data: formdata,
      headers: {
        'Content-Type': 'multipart/form-data',
        Authorization: "Bearer mybearxxxxx"
      }
    })
    .then(function (res: any) {
      console.log(res)
    })
```
```
request(serverUrl, {
    method: "post",
    data: formdata,
    headers: {
      "Content-Type": "multipart/form-data; boundary=----abc"
    }
  });
```
上面的方式可以，下面的不行，其中我对request进行了简单封装

```
import { extend, RequestOptionsInit, RequestMethod, RequestResponse } from 'umi-request';
import notification from 'antd/lib/notification';
import 'antd/lib/notification/style';

const serverUrl = 'xxxxxxxx';

export interface CodeMessage {
  [key: number]: string;
}

export interface IRequestInterceptors extends RequestOptionsInit {
  interceptors: boolean;
}

export interface IRequestMethod<R = false> extends RequestMethod {
  <T = any>(url: string, options?: IRequestInterceptors): R extends true
    ? Promise<RequestResponse<T>>
    : Promise<T>;
}

const codeMessage: CodeMessage = {
  200: '服务器成功返回请求的数据。',
  201: '新建或修改数据成功。',
  202: '一个请求已经进入后台排队（异步任务）。',
  204: '删除数据成功。',
  400: '发出的请求有错误，服务器没有进行新建或修改数据的操作。',
  401: '用户没有权限（令牌、用户名、密码错误）。',
  403: '用户得到授权，但是访问是被禁止的。',
  404: '发出的请求针对的是不存在的记录，服务器没有进行操作。',
  406: '请求的格式不可得。',
  410: '请求的资源被永久删除，且不会再得到的。',
  422: '当创建一个对象时，发生一个验证错误。',
  500: '服务器发生错误，请检查服务器。',
  502: '网关错误。',
  503: '服务不可用，服务器暂时过载或维护。',
  504: '网关超时。',
};

/**
 * 异常处理程序
 */
const errorHandler = (error: any) => {
  const { response = {} } = error;
  const errortext = codeMessage[response.status] || response.statusText;
  const { status, url } = response;

  notification.error({
    message: `请求错误 ${status}: ${url}`,
    description: errortext,
  });
};

/**
 * 配置request请求时的默认参数
 */
const request = extend({
  prefix: serverUrl,
  errorHandler, // 默认错误处理
  credentials: 'include', // 默认请求是否带上cookie
  useCache: true,
  interceptors: true,
} as IRequestInterceptors) as IRequestMethod;

request.interceptors.request.use((url: string, options: any) => {
  if (options.interceptors) {
    options.headers.Authorization = `Bearer ${localStorage.getItem('token')}`;
  }

  return {
    url,
    options,
  };
});

export default request;

```
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by clock157** [comment]
怎么不行？报什么错，或者问题是什么。看起来是 fetch 的使用问题，你看这个能帮助你解决问题吗？
https://stackoverflow.com/questions/35192841/fetch-post-with-multipart-form-data

**Comment by zhangWeiZhuang** [comment]
> ## What happens?
> 使用axios可以，使用umi-request不行，multipart/form-data的情况
> 
> ```
> axios({
>       method: 'post',
>       url: serverUrl,
>       data: formdata,
>       headers: {
>         'Content-Type': 'multipart/form-data',
>         Authorization: "Bearer mybearxxxxx"
>       }
>     })
>     .then(function (res: any) {
>       console.log(res)
>     })
> ```
> 
> ```
> request(serverUrl, {
>     method: "post",
>     data: formdata,
>     headers: {
>       "Content-Type": "multipart/form-data; boundary=----abc"
>     }
>   });
> ```
> 
> 上面的方式可以，下面的不行，其中我对request进行了简单封装
> 
> ```
> import { extend, RequestOptionsInit, RequestMethod, RequestResponse } from 'umi-request';
> import notification from 'antd/lib/notification';
> import 'antd/lib/notification/style';
> 
> const serverUrl = 'xxxxxxxx';
> 
> export interface CodeMessage {
>   [key: number]: string;
> }
> 
> export interface IRequestInterceptors extends RequestOptionsInit {
>   interceptors: boolean;
> }
> 
> export interface IRequestMethod<R = false> extends RequestMethod {
>   <T = any>(url: string, options?: IRequestInterceptors): R extends true
>     ? Promise<RequestResponse<T>>
>     : Promise<T>;
> }
> 
> const codeMessage: CodeMessage = {
>   200: '服务器成功返回请求的数据。',
>   201: '新建或修改数据成功。',
>   202: '一个请求已经进入后台排队（异步任务）。',
>   204: '删除数据成功。',
>   400: '发出的请求有错误，服务器没有进行新建或修改数据的操作。',
>   401: '用户没有权限（令牌、用户名、密码错误）。',
>   403: '用户得到授权，但是访问是被禁止的。',
>   404: '发出的请求针对的是不存在的记录，服务器没有进行操作。',
>   406: '请求的格式不可得。',
>   410: '请求的资源被永久删除，且不会再得到的。',
>   422: '当创建一个对象时，发生一个验证错误。',
>   500: '服务器发生错误，请检查服务器。',
>   502: '网关错误。',
>   503: '服务不可用，服务器暂时过载或维护。',
>   504: '网关超时。',
> };
> 
> /**
>  * 异常处理程序
>  */
> const errorHandler = (error: any) => {
>   const { response = {} } = error;
>   const errortext = codeMessage[response.status] || response.statusText;
>   const { status, url } = response;
> 
>   notification.error({
>     message: `请求错误 ${status}: ${url}`,
>     description: errortext,
>   });
> };
> 
> /**
>  * 配置request请求时的默认参数
>  */
> const request = extend({
>   prefix: serverUrl,
>   errorHandler, // 默认错误处理
>   credentials: 'include', // 默认请求是否带上cookie
>   useCache: true,
>   interceptors: true,
> } as IRequestInterceptors) as IRequestMethod;
> 
> request.interceptors.request.use((url: string, options: any) => {
>   if (options.interceptors) {
>     options.headers.Authorization = `Bearer ${localStorage.getItem('token')}`;
>   }
> 
>   return {
>     url,
>     options,
>   };
> });
> 
> export default request;
> ```
> 
> ## Mini Showcase Repository(REQUIRED)
> > Provide a mini GitHub repository which can reproduce the issue.
> > Use `yarn create umi` then upload to your GitHub
> 
> ## How To Reproduce
> **Steps to reproduce the behavior:**
> 1.
> 2.
> 
> **Expected behavior**
> 1.
> 2.
> 
> ## Context
> * **Umi Version**:
> * **Node Version**:
> * **Platform**:

你好，打扰下。请问你这边获取token是怎么做的呢？有没有代码示例，是否可以发下看看呢。

**Comment by kimmerchen** [comment]
> ## What happens?
> 使用axios可以，使用umi-request不行，multipart/form-data的情况
> 
> ```
> axios({
>       method: 'post',
>       url: serverUrl,
>       data: formdata,
>       headers: {
>         'Content-Type': 'multipart/form-data',
>         Authorization: "Bearer mybearxxxxx"
>       }
>     })
>     .then(function (res: any) {
>       console.log(res)
>     })
> ```
> 
> ```
> request(serverUrl, {
>     method: "post",
>     data: formdata,
>     headers: {
>       "Content-Type": "multipart/form-data; boundary=----abc"
>     }
>   });
> ```
> 
> 上面的方式可以，下面的不行，其中我对request进行了简单封装
> 
> ```
> import { extend, RequestOptionsInit, RequestMethod, RequestResponse } from 'umi-request';
> import notification from 'antd/lib/notification';
> import 'antd/lib/notification/style';
> 
> const serverUrl = 'xxxxxxxx';
> 
> export interface CodeMessage {
>   [key: number]: string;
> }
> 
> export interface IRequestInterceptors extends RequestOptionsInit {
>   interceptors: boolean;
> }
> 
> export interface IRequestMethod<R = false> extends RequestMethod {
>   <T = any>(url: string, options?: IRequestInterceptors): R extends true
>     ? Promise<RequestResponse<T>>
>     : Promise<T>;
> }
> 
> const codeMessage: CodeMessage = {
>   200: '服务器成功返回请求的数据。',
>   201: '新建或修改数据成功。',
>   202: '一个请求已经进入后台排队（异步任务）。',
>   204: '删除数据成功。',
>   400: '发出的请求有错误，服务器没有进行新建或修改数据的操作。',
>   401: '用户没有权限（令牌、用户名、密码错误）。',
>   403: '用户得到授权，但是访问是被禁止的。',
>   404: '发出的请求针对的是不存在的记录，服务器没有进行操作。',
>   406: '请求的格式不可得。',
>   410: '请求的资源被永久删除，且不会再得到的。',
>   422: '当创建一个对象时，发生一个验证错误。',
>   500: '服务器发生错误，请检查服务器。',
>   502: '网关错误。',
>   503: '服务不可用，服务器暂时过载或维护。',
>   504: '网关超时。',
> };
> 
> /**
>  * 异常处理程序
>  */
> const errorHandler = (error: any) => {
>   const { response = {} } = error;
>   const errortext = codeMessage[response.status] || response.statusText;
>   const { status, url } = response;
> 
>   notification.error({
>     message: `请求错误 ${status}: ${url}`,
>     description: errortext,
>   });
> };
> 
> /**
>  * 配置request请求时的默认参数
>  */
> const request = extend({
>   prefix: serverUrl,
>   errorHandler, // 默认错误处理
>   credentials: 'include', // 默认请求是否带上cookie
>   useCache: true,
>   interceptors: true,
> } as IRequestInterceptors) as IRequestMethod;
> 
> request.interceptors.request.use((url: string, options: any) => {
>   if (options.interceptors) {
>     options.headers.Authorization = `Bearer ${localStorage.getItem('token')}`;
>   }
> 
>   return {
>     url,
>     options,
>   };
> });
> 
> export default request;
> ```
> 
> ## Mini Showcase Repository(REQUIRED)
> > Provide a mini GitHub repository which can reproduce the issue.
> > Use `yarn create umi` then upload to your GitHub
> 
> ## How To Reproduce
> **Steps to reproduce the behavior:**
> 1.
> 2.
> 
> **Expected behavior**
> 1.
> 2.
> 
> ## Context
> * **Umi Version**:
> * **Node Version**:
> * **Platform**:

有找到解决办法吗，我遇到了同样的问题

**Comment by wjune211** [comment]
umi使用 new FormData()上传文件时，设置'Content-Type': false不起作用

**Comment by phucuongit** [comment]
You should remove `'Content-Type': 'multipart/form-data'`, umi-request will add it automatically
