### ISSUE TITLE
npm run build 到 91%就被killed了，不知道为什么

### ISSUE THREAD

**Issue by SanPy** [umijs/umi#2455]
![image](https://user-images.githubusercontent.com/4796185/58159821-dbc8c600-7caf-11e9-93aa-5ea1d4b272fb.png)

## 相关环境信息

- **Umi 版本**：2.6.17

- **Node 版本**：v10.15.1

- **操作系统**：centos7

**Comment by SanPy** [comment]
经过一番搜索，发现是内存问题，内存不够的情况下，可以通过配置虚拟内存来满足要求，虚拟内存的配置方法参考这里：https://m.imooc.com/article/19208?block_id=tuijian_wz

**Comment by jiaohuix** [comment]
@SanPy 为什么12G内存还是不够啊 npm run build
