### ISSUE TITLE
define 定义的变量 js中无法访问

### ISSUE THREAD

**Issue by sandercage** [umijs/umi#2474]
## What happens?
我在.umirc.js 里的define中定义了变量：classPre，  但在我的视图js中无法访问， 提示undefine

![image](https://user-images.githubusercontent.com/36032199/58299520-f7e47880-7e11-11e9-9a20-5aadd00f404f.png)

![image](https://user-images.githubusercontent.com/36032199/58299959-6413ac00-7e13-11e9-8ad5-e8ae06bf741e.png)

## Mini Showcase Repository(REQUIRED)

https://github.com/sandercage/fisher-h5

## How To Reproduce
1. yarn start
2.  访问 http://localhost:8000/autoLibrary

**Expected behavior**
1 .  autoLibrary    $index$.js 中不能访问classPre( 但可以访问process.env.currentEnv)

## Context

- **Umi Version**:      2.6.3
- **Node Version**: 12.3
- **Platform**:  macosX  10.14.5

**Comment by sandercage** [comment]
我发现问题了， define这里定义的变量的值换成常量就好了.............

**Comment by llh1187** [comment]
> 我发现问题了， define这里定义的变量的值换成常量就好了.............

老哥，我这里换成常量还是访问不到~

**Comment by lxzy-yun** [comment]
我也访问不到
