### ISSUE TITLE
[Feature Request] block support transform TypeScript to JavaScript

### ISSUE THREAD

**Issue by yutingzhao1991** [umijs/umi#2476]
## Background

Ant Design Pro V4 基于 TypeScript.

## Proposal

想要用 JS 的项目也可以用 TypeScript 的区块

## Additional context

比如可以支持 `umi block add demo --js` 加一个 `--js` 的参数来支持。主要是要看看这个是不是要通过 umi 官方内置支持，还是通过插件来支持。

**Comment by yutingzhao1991** [comment]
cc @chenshuai2144 @sorrycc

**Comment by hfuuss** [comment]
期待v4，有具体时间节点吗？

**Comment by yutingzhao1991** [comment]
> 期待v4，有具体时间节点吗？

近期就会发布。

**Comment by yutingzhao1991** [comment]
这个 issue 可以参考 @zombieJ 的 https://github.com/umijs/create-umi/pull/65 这个 PR。一个想法是把那个 PR 里面转换区块的代码抽取为一个库：比如 `js-to-ts`，然后在 umi 中内置。内部的代码逻辑为：

- 判断区块是不是 ts 的，通过是否有 `src/index.ts` 来判断，如果不是 ts 那么就直接添加，不需要处理。
- 判断项目是不是 ts 的，通过项目中是否有 tsconfig.json 来判断，如果是那么直接添加区块。
- 如果项目是 ts 的，区块是 js 的那么调用 `js-to-ts` 将区块转换为 js 的区块然后添加到项目中。
- 用户可以通过 `--js` 或者 `--no-js` 来强制指定是否转换。
