### ISSUE TITLE
[Feature Request] How to add debugger to node_modules

### ISSUE THREAD

**Issue by iShawnWang** [umijs/umi#2481]
## Background

I wan to add debugger in library inside of `node_modules`, but it seems all the `debugger` and `console` will be removed during `umi dev`, what should i do to prevent my `debugger` from cleared, any config here ?

# Env

- umi latest
- umi typescript template

**Comment by sorrycc** [comment]
There is no logic to delete `debugger` and `console` inside umi. It may be the problem of files changed in node_modules does not trigger the hot recompile, so try to restart `umi dev` after files in node_modules is changed.
