### ISSUE TITLE
umi g 命令现在能生成啥？

### ISSUE THREAD

**Issue by miaozilong** [umijs/umi#2482]
D:\test1\umidemo
λ umi g model users
×  error     Generate failed, Generator model not found

D:\test1\umidemo
λ umi g component users
×  error     Generate failed, Generator component not found

D:\test1\umidemo
λ umi g c users
×  error     Generate failed, Generator c not found

D:\test1\umidemo
λ umi g service users
×  error     Generate failed, Generator service not found

**Comment by xiaohuoni** [comment]
应该是page

**Comment by sorrycc** [comment]
内置有两个，

```bash
$ umi g page xxx
$ umi g layout xxx
```

加了 dva 插件之后，还有

```bash
```

**Comment by maxl960** [comment]
![image](https://user-images.githubusercontent.com/8602874/162098252-1b168acf-3dff-4f61-9dad-6df4fac3d2fd.png)
是安装- @umijs/plugin-dva吗，好像是默认安装的但是生成model的命令不好使。
