### ISSUE TITLE
路由如何缓存，像vue中keep-alive一样

### ISSUE THREAD

**Issue by AsaYao** [umijs/umi#2487]
## What happens?
请问一下路由如何进行缓存，切换到下一个路由的时候缓存当前路由的状态。

**Comment by afc163** [comment]
https://github.com/facebook/react/issues/12039#issuecomment-359801971

**Comment by iShawnWang** [comment]
感觉 SPA 很像移动端开发了, react-router 如果能引入 移动端的页面栈概念就可以解决这个问题... 但 在其 issues 里, 看到他们不准备支持这个 feature....

**Comment by AielloChan** [comment]
Try https://github.com/AielloChan/KeepAliveRoute
