### ISSUE TITLE
DynamicComponent触发之前调用过的reducers

### ISSUE THREAD

**Issue by changero** [umijs/umi#2489]
## What happens?

先触发一个reducers，记为1。接着切换页面，动态载入一个新的model，会重新触发1这个reducers。如果在动态载入一个新的model之前，有多个reducers被执行，在载入之后，也会被依次执行。

当正常执行reducers时，调用栈如下：
![image](https://user-images.githubusercontent.com/17746517/58453817-06eb6380-814f-11e9-8f1b-77360eda259b.png)

而动态载入一个model之后的触发，调用栈如下：
![image](https://user-images.githubusercontent.com/17746517/58453854-284c4f80-814f-11e9-8d87-c623bd8d9610.png)

会发现有一个replaceReducer

## 最小可复现仓库

通过[ant design pro](https://github.com/ant-design/ant-design-pro)项目，就能复现

## 相关环境信息

```json
{
    "umi": "^2.6.17",
    "node":"10.15.0",
    "platform": "windows10 64"
}
```

**Comment by changero** [comment]
不知道是否设计如此。如果是的话，这样操作的作用是什么，因为这样感觉像是纪录reducer的执行路线

**Comment by sorrycc** [comment]
就是这么设计的，有啥问题吗？动态加载是通过 replaceReducer 复写传给 redux 的 reducer。

**Comment by changero** [comment]
功能上不影响，问题不大。

只是在replaceReducer之后，重复执行之前的reducer来计算state，感觉有点浪费。

容我升级一下dva，看看是不是replaceReducer之后dispatch的那个action的问题

**Comment by changero** [comment]
@sorrycc 

功能上不影响，问题不大。

只是在replaceReducer之后，重复执行之前的reducer来计算state，感觉有点浪费。

容我升级一下dva，看看是不是replaceReducer之后dispatch的那个action的问题
