### ISSUE TITLE
umi-plugin-dva 支持引入 redux-persist

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#249]
```js
import { persistStore, autoRehydrate } from 'redux-persist';
const app = dva({
extraEnhancers: [autoRehydrate()],
});
persistStore(app._store);
```

ref:

* dvajs/dva#1573

**Comment by 18601673727** [comment]
表示关注 👀

**Comment by fattypanda** [comment]
写在哪一个文件中？dva.js ?

**Comment by kelekexiao123** [comment]
无法写入dvaContainer.js啊，会被刷新

**Comment by dilidili** [comment]
通过 #1007 的 PR 后，可以按照下面的 demo 配置 redux-persist 进行使用。
https://github.com/dilidili/umi-examples/tree/redux-persist-demo/with-dva

**Comment by zhilianbi520** [comment]
> 有一种解决方法 利用 store enhancer 在`src`目录下的`dva.js`
> 
> ```js
> import { persistStore, persistReducer } from 'redux-persist';
> import storage from "redux-persist/es/storage/session";
> 
> const persistConfig = {
>   key: 'xxx',
>   storage,
> };
> const persistEnhancer = ()=>createStore=>(reducer, initialState, enhancer)=>{
>   const store = createStore(persistReducer(persistConfig, reducer), initialState, enhancer);
>   const persist = persistStore(store);
>   return {...store, persist };
> };
> export function config() {
>     return {
>       onError(err) {
>         err.preventDefault();
>         console.error(err.message);
>       },
>       extraEnhancers:[
>         persistEnhancer()
>       ]
>     };
> }
> ```
> 
> 我这用的`redux-persist 5.10.0`

在开发环境下能够获取到全部models的存的值，但是打包后只能一部分的models的值被取到。

**Comment by zhilianbi520** [comment]
![wechatimg6282](https://user-images.githubusercontent.com/16549630/49070612-156fc580-f267-11e8-9e3a-1a1f034e7b44.jpg)
![wechatimg6283](https://user-images.githubusercontent.com/16549630/49070635-1f91c400-f267-11e8-9da5-ed0ec53f218c.jpg)
利用的是ant design pro v2.0脚手架

**Comment by lulei90** [comment]
@zhilianbi520  我这边用起来都是正常的  没在ant design pro上试过  你看看是不是你那边生产环境配置了黑名单

**Comment by EvanWaL** [comment]
> > @zhilianbi520 我这边用起来都是正常的 没在ant design pro上试过 你看看是不是你那边生产环境配置了黑名单
> 
> pages下的models都存不到。models目录下的都能缓存上。。感觉好像跟环境配置没啥关系。

刚学习antd pro，没太明白怎么处理这个问题

**Comment by zhilianbi520** [comment]
> > > @zhilianbi520 我这边用起来都是正常的 没在ant design pro上试过 你看看是不是你那边生产环境配置了黑名单
> > 
> > 
> > pages下的models都存不到。models目录下的都能缓存上。。感觉好像跟环境配置没啥关系。
> 
> 刚学习antd pro，没太明白怎么处理这个问题

目前还是无解状态。。求解。

**Comment by EvanWaL** [comment]
> > > > @zhilianbi520 我这边用起来都是正常的 没在ant design pro上试过 你看看是不是你那边生产环境配置了黑名单
> > > 
> > > 
> > > pages下的models都存不到。models目录下的都能缓存上。。感觉好像跟环境配置没啥关系。
> > 
> > 
> > 刚学习antd pro，没太明白怎么处理这个问题
> 
> 目前还是无解状态。。求解。

```javascript
import { persistStore, persistReducer } from 'redux-persist';
import storage from 'redux-persist/es/storage/session';

const persistConfig = {
  key: 'redux-storage',
  storage,
};
const persistEnhancer = () => createStore => (reducer, initialState, enhancer) => {
  const store = createStore(persistReducer(persistConfig, reducer), initialState, enhancer);
  const persist = persistStore(store);
  return { ...store, persist };
};

/* eslint-disable */
export const dva = {
  config: {
    onError(e) {
      e.preventDefault();
    },
    extraEnhancers: [persistEnhancer()],
  },
  plugins: [require('dva-logger')()],
};
/* eslint-enable */
```

在src新建app.js,目前看来没什么问题

**Comment by zhilianbi520** [comment]
> > > > > @zhilianbi520 我这边用起来都是正常的 没在ant design pro上试过 你看看是不是你那边生产环境配置了黑名单
> > > > 
> > > > 
> > > > pages下的models都存不到。models目录下的都能缓存上。。感觉好像跟环境配置没啥关系。
> > > 
> > > 
> > > 刚学习antd pro，没太明白怎么处理这个问题
> > 
> > 
> > 目前还是无解状态。。求解。
> 
> ```js
> import { persistStore, persistReducer } from 'redux-persist';
> import storage from 'redux-persist/es/storage/session';
> 
> const persistConfig = {
>   key: 'redux-storage',
>   storage,
> };
> const persistEnhancer = () => createStore => (reducer, initialState, enhancer) => {
>   const store = createStore(persistReducer(persistConfig, reducer), initialState, enhancer);
>   const persist = persistStore(store);
>   return { ...store, persist };
> };
> 
> /* eslint-disable */
> export const dva = {
>   config: {
>     onError(e) {
>       e.preventDefault();
>     },
>     extraEnhancers: [persistEnhancer()],
>   },
>   plugins: [require('dva-logger')()],
> };
> /* eslint-enable */
> ```
> 
> 在src新建app.js,目前看来没什么问题


打包后的文件嘛？sessionStorage存的是所有models里的state嘛？包括pages里的。

**Comment by regreceive** [comment]
什么时候加入redux-persist支持呢

**Comment by sorrycc** [comment]
Closed via https://github.com/umijs/umi/issues/1898

**Comment by morelearn1990** [comment]
需要在 dva config 里面将 reducer 用 redux-persist 的 reducer 包裹一遍。代码如下：
app.js
```
import { persistStore, persistReducer } from 'redux-persist';
import storage from 'redux-persist/lib/storage';

const persistConfig = {
  key: 'root',
  storage,
};

const persistEnhancer = () => createStore => (reducer, initialState, enhancer) => {
  const store = createStore(persistReducer(persistConfig, reducer), initialState, enhancer);
  const persist = persistStore(store, null);
  return { ...store, persist };
};

export const dva = {
  config: {
    onError(err) {
      err.preventDefault();
      console.error(err.message);
    },
    extraEnhancers: [persistEnhancer()],
    onReducer: reducer => persistReducer(persistConfig, reducer),
  },
  plugins: [process.env.APP_TYPE === 'build' ? null : require('dva-logger')()],
};
```

**Comment by morelearn1990** [comment]
还是存在问题，更新了 store 里面 state 的内容，但是 persist 并没有刷新 localStorage 里面的内容。不知道为啥，有哪位大佬了解么？

**Comment by morelearn1990** [comment]
之前的代码存在问题：一下是更新版，减少persistReducer第二次处理，不然会经常报错：state 在 render里面修改的错误。
```
const persistEnhancer = () => createStore => (reducer, initialState, enhancer) => {
  // const store = createStore(persistReducer(persistConfig, reducer), initialState, enhancer);
  // reducer 已经在 dva.config. onReducer 里面处理过了，所以这儿不用再次处理
  const store = createStore(reducer, initialState, enhancer);
  const persist = persistStore(store, null);
  return { ...store, persist };
};
```

**Comment by morelearn1990** [comment]
上面的写法对于 hot replacement 存在问题。
优化后如下 
```
let $persistor = null;
const persistConfig = {
  key: "root",
  storage,
  whitelist: ["auth", "config", "nav", "user"],
  stateReconciler: autoMergeLevel2
};
export const onPersistReducer = reducer => {
  let rootReducer = persistReducer(persistConfig, reducer);
  // umi 在进行模块化的异步加载时，会第二次触发 onReducer。
  // 这个时候 Redux-Persist 会重新初始化，导致里面有个默认为 true 参数 _paused 重置了。
  // 这个参数又决定了 redux-persist 是否更新 localstorage 。
  // 而如何将这个参数置为对于我们有利的，就需要重新调用 $persistor.persist()
  // 这儿需要使用 setTimeout 来进行 nextTick 的调用才能赶在 redux init 之后 dispath {type:'PERSIST'} 才能生效
  setTimeout(() => $persistor && $persistor.persist(), 0);
  return rootReducer;
};
export const persistEnhancer = () => createStore => (reducer, initialState, enhancer) => {
  //  persistReducer 已经在 app.js 里面的 onReducer 已经处理过了,所以这儿不用再次进行处理，避免重复
  // const persistReducer = onPersistReducer(reducer);
  const persistReducer = reducer;
  const store = createStore(persistReducer, initialState, enhancer);
  $persistor = persistStore(store, null);
  $persistor.persist();
  return { ...store, $persistor };
};
```

具体可以参考 [commit: lyingd/antd-pro-standalone@24bfb77](https://github.com/lyingd/antd-pro-standalone/commit/24bfb77b501d2bec3f956607da9c80d66be55402)

**Comment by caidongwei** [comment]
按文档配置，报错：_reduxPersist.autoRehydrate) is not a function，该怎么处理

**Comment by gengkeke** [comment]
umi3  antd pro v5
app.tsx:
`const persistConfig = {
  key: 'root',
  storage,
  whitelist: ['global', 'screen'],
};

const persistEnhancer = () => createStore => (reducer, initialState, enhancer) => {
  const store = createStore(persistReducer(persistConfig, reducer), initialState, enhancer);
  const persist = persistStore(store, null);
  return { ...store, persist };
};

export const dva = {
  config: {
    onError(e) {
      e.preventDefault();
    },
    extraEnhancers: [persistEnhancer()],
    onReducer(reducer) {
      return persistReducer(persistConfig, reducer);
    },
  },
};`
