### ISSUE TITLE
如何去掉打包typescript?

### ISSUE THREAD

**Issue by petitspois** [umijs/umi#2490]
![B7940C76-B803-4919-BDC4-AB4E6F981D19](https://user-images.githubusercontent.com/9461149/58457432-3ef7a400-8159-11e9-9f9e-21a83ddb40e6.png)

```js
import pageRoutes from './router.config';
import theme from './theme'

const plugins = [
    ['umi-plugin-react', {
        antd: true,
        dva: true,
        dynamicImport: false,
        title: 'anpin-ops-pc',
		dll: false,
        locale: {
            enable: true, // default false
            default: 'zh-CN', // default zh-CN
            baseNavigator: true, // default true, when it is true, will use `navigator.language` overwrite default
        },
        routes: {
          exclude: [
            /models\//,
            /services\//,
            /model\.(t|j)sx?$/,
            /service\.(t|j)sx?$/,
            /components\//,
          ],
        },
    }],
]

// ref: https://umijs.org/config/
export default {
    plugins,
    treeShaking: true,
    routes: pageRoutes,
    ignoreMomentLocale: true,
    theme,
    hash: true,
    targets: {
        ie: 11,
    },
}
  
```

**Comment by petitspois** [comment]
项目没有使用typescript

**Comment by sorrycc** [comment]
如何复现？即使是 typescript 项目，也不应该引入这个吧。

**Comment by huiXinYiJi** [comment]
我今天也碰到这个问题了。后来一个个文件对下来  才发现问题。

在我的项目中，有一个js文件引入了 typescript中的方法

import { createImportSpecifier } from "typescript"

这行代码不是我引入的，应该是编辑器自动给我引的，可能是在敲代码的时候不小心给自动带进去了。
你可以查查你的src中的文件，是否有类似代码

同时，引入这行代码后，在我的控制台会有如下警告

`
 warning  in ./node_modules/typescript/lib/typescript.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/typescript/lib/typescript.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/typescript/lib/typescript.js

Module not found: Error: Can't resolve 'perf_hooks' in 'E:\react\umi3\node_modules\typescript\lib'

`

当我删除了import那行代码后，控制台警告也没有了，打包之后typescript文件也没有了。
