### ISSUE TITLE
升级新版本umi后，打包报错

### ISSUE THREAD

**Issue by choby** [umijs/umi#2493]
## What happens?

升级新版本umi 2.6.17后，打包报错，之前旧版的2.0.0没问题

## 最小可复现仓库

> https://github.com/choby/shift

## 复现步骤，错误日志以及相关配置

UnhandledPromiseRejectionWarning: WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[5].include should be one of these:
   RegExp | string | function | [(recursive)] | object { and?, exclude?, include?, not?, or?, test? } | [RegExp | string | function | [(recursive)] | object { and?, exclude?, include?, not?, or?, test? }]
   -> One or multiple rule conditions
   Details:
    * configuration.module.rules[5].include should be an instance of RegExp
    * configuration.module.rules[5].include should be a string.
    * configuration.module.rules[5].include should be an instance of function
    * configuration.module.rules[5].include[0] should be an instance of RegExp
    * configuration.module.rules[5].include[0]: The provided value "node_modules" is not an absolute path!
    at service._applyPluginsAsync.then (E:\HMC-FRONEND\HMC-FRONTEND-UPMS\node_modules\umi-build-dev\lib\plugins\commands\build\index.js:56:44)
    at internalTickCallback (internal/process/next_tick.js:77:7)
    at process._tickCallback (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:763:11)
    at startup (internal/bootstrap/node.js:303:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
(node:21152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the 
Node.js process with a non-zero exit code.

- **Umi 版本**：2.6.17
- **Node 版本**：11.0.0
- **操作系统**：windows 10 x64 专业版

**Comment by sorrycc** [comment]
hmcore 是什么？依赖安装失败了。

**Comment by choby** [comment]
> hmcore 是什么？依赖安装失败了。

内部组件项目，仓库地址：http://119.130.112.228:4873/

**Comment by sorrycc** [comment]
你需要给一个我能复现的仓库。
