### ISSUE TITLE
怎么把model文件和component文件打包在一起

### ISSUE THREAD

**Issue by kingsily** [umijs/umi#2499]

**Comment by kingsily** [comment]
比如说我的user
![image](https://user-images.githubusercontent.com/12093660/58546969-134beb00-8239-11e9-8890-995b9fcdecbd.png)
这里面user/info底下的userInifo.js 和这里面的models里的test.js、userInfo.js打包成一个文件？
遇到的问题：
目前我试了umijs的配置要么都是各打各的。要么就只是把component文件单独打包，然后所有的model文件都打包到umi.hash.js。
想实现的模板：
把路由对应的文件打包到一起，或者可以配置webpackChunkName

**Comment by kingsily** [comment]
> _No description provided._

**Comment by sorrycc** [comment]
目前不支持。

**Comment by kingsily** [comment]
以后会支持这样的打包方式吗？

**Comment by sorrycc** [comment]
这是一个优化点，应该会支持（可能通过配置项开启）。目前把 model 提到 umi.js 里的考虑是在多级目录下都有 model 时，父级的 model 就不能确定和哪个 page 一起打包了。
