### ISSUE TITLE
有多个ejs,build时根据变量选择不同的模板

### ISSUE THREAD

**Issue by furylee** [umijs/umi#2500]
## What happens?
 有多个ejs,build时根据变量选择不同的模板

## 最小可复现仓库
在routes中添加 ``` document:'./src/pages/noCN.ejs', ```build时失败
> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by sorrycc** [comment]
没理解你的问题是啥。

**Comment by furylee** [comment]
> 没理解你的问题是啥。

a.ejs 
b.ejs 
我想通过不同环境的build命令选择不同的html模板

**Comment by cwjTerrace** [comment]
这个问题的结论呢 @furylee
