### ISSUE TITLE
通过create-umi创建项目起不来？？？

### ISSUE THREAD

**Issue by ningzhenyi** [umijs/umi#2501]
![image](https://user-images.githubusercontent.com/26025135/58553834-86a92900-8248-11e9-91b7-98cbe8bcd4f0.png)
这是什么问题呢？？？

**Comment by sorrycc** [comment]
依赖没装好，找不到 `umi-plugin-react`。

**Comment by ningzhenyi** [comment]
@sorrycc 那我该怎么做呢？我安装官网一步步操作的呀
