### ISSUE TITLE
如何自行处理loading chunk failed 错误

### ISSUE THREAD

**Issue by kingsily** [umijs/umi#2502]
build运行时候发现有的包或者模板没有加载进来报loading chunk failed的错误。我先做想实现的是怎样的配置能实现处理或者捕获这样错误，自己再去处理，比如界面上有提示重新加载按钮，而不是就控制台报个错。

**Comment by sorrycc** [comment]
静态资源为啥会载入失败？是服务端的问题？

**Comment by jeremaihloo** [comment]
我也存在这个问题
![image](https://user-images.githubusercontent.com/10516530/59732118-98944f80-927b-11e9-84e6-50d062bd3a10.png)
很多人都有这个问题，Webpack也有这个问题

**Comment by sorrycc** [comment]
得排查下是路径不对，还是文件不存在？

**Comment by feibi** [comment]
这可能是缓存问题导致的

**Comment by Anonymity94** [comment]
> 我也存在这个问题
> ![image](https://user-images.githubusercontent.com/10516530/59732118-98944f80-927b-11e9-84e6-50d062bd3a10.png)
> 很多人都有这个问题，Webpack也有这个问题

这个问题有什么进展吗？

**Comment by acpplife** [comment]
```
function handleLoadChunkError (err) {
  const pattern = /^Loading chunk (\d)+ failed\./;
  const isChunkLoadingFailed = pattern.test(err.message);

  if (isChunkLoadingFailed) {
    notification.info({
      message: '系统提醒',
      description: '服务器版本已更新，正在刷新本地缓存，请稍后...',
    })

    window.location.replace(window.location.href);
  }
}
```

```
dva: {
   config: {
       onError(err) {
            handleLoadChunkError(err)
       }
   }
},
```

不知道这样处理可不可以，我添加这块之后项目重新发布没有出错，但是也没有触发这个更新提示。
如果大家有可行的方案欢迎讨论~

**Comment by codercatmomi** [comment]
@acpplife 我先借用你这个试试

**Comment by zhilisu** [comment]
> @acpplife 我先借用你这个试试

请问这个可行吗？我这边不管用，也还在找其他解决方案中

**Comment by 1215708470** [comment]
这个问题有什么解决方法吗，一直得不到解决办法

**Comment by XiaoMing6** [comment]
有方法可以捕获到这个错误吗？“loading chunk failed”

**Comment by xyy7260** [comment]
@ArleneShine  @1215708470  请问你们解决了吗

**Comment by ArleneShine** [comment]
@xyy7260 用window.onerror可以捕获到

**Comment by CLXGGG** [comment]
> 这可能是缓存问题导致的

确实 Ctrl + F5 强制刷新一下就好了

**Comment by wenlei0617** [comment]
> 这可能是缓存问题导致的

为什么是缓存呢？通过hash打包的，并且过去的资源没有删除，也会出现这个问题呢？

**Comment by Losstie** [comment]
同问，我们SPA应用，html开启的不缓存，通过hash打包，过去资源也没有删除，但也会出现loading chunk的错误。看了下加载的资源路径没问题，资源也存在。是网络原因吗？
