### ISSUE TITLE
如何实现唯一的html名字

### ISSUE THREAD

**Issue by yuyuabc1** [umijs/umi#2504]
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

如何生成唯一的项目名

例如webpack的打包，每次构建过程中，唯一的 hash 生成
filename: "[name].[hash].bundle.html"

在umijs中打包如何实现唯一的html

**Comment by sorrycc** [comment]
为啥要生成这种？

**Comment by zero1898** [comment]
为啥要生成这种？
