### ISSUE TITLE
添加runtimeLocale时能否把当前的语言列表作为props返回来

### ISSUE THREAD

**Issue by zhongds** [umijs/umi#2505]
`src/app.js`支持设置运行时的locale变量，但是目前没有把当前的语言列表返回来
```
// src/app.js
export const locale = {
   default: (props) => {
      // 目前props是undefined。
      // do something
     return locale
   }
}
```
把`localInfo`或者`localeList`作为参数返回来，语言处理应该可以灵活很多
https://github.com/umijs/umi/blob/fa3e629695c4d78c5bceb661d810aa0d1ac47bc6/packages/umi-plugin-locale/template/wrapper.jsx.tpl#L72

**Comment by yutingzhao1991** [comment]
是不是提供 `import { getAvailableLocales } from 'umi-plugin-locale';` 这样会更好一点，不仅仅是这里也许其它地方也会用到。

**Comment by zhongds** [comment]
> 是不是提供 `import { getAvailableLocales } from 'umi-plugin-locale';` 这样会更好一点，不仅仅是这里也许其它地方也会用到。

嗯 这样也可以，确实可能其他地方也会用到
