### ISSUE TITLE
ie11报fetch未定义错误

### ISSUE THREAD

**Issue by XQ-0** [umijs/umi#2506]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
fetch 不能直接用吧，得用 whatwg-fetch 。
