### ISSUE TITLE
.umirc.js如何添加第三方的plugin

### ISSUE THREAD

**Issue by htank-wang** [umijs/umi#2508]
如想加一个monaco-editor-webpack-plugin这样的第三方插件

**Comment by sorrycc** [comment]
通过 [chainWebpack](https://umijs.org/config/#chainwebpack) 配置。

**Comment by huntbao** [comment]
- 安装3个包 `monaco-editor`、`monaco-editor-webpack-plugin`和`react-monaco-editor`
- `config.js` 配置文件中的写法如下：
```js
...
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');
...
export default {
   ...
   chainWebpack(config, { webpack }) {
        config.plugin('monaco-editor').use(MonacoWebpackPlugin);
    },
   ...
}
```

**Comment by ArleneShine** [comment]
这两天在用react-monaco-editor，已照方法引入，但代码还是没有高亮，求大神指点~

// .umirc.js
const chainWebpack = (config, { webpack }) => {
    config.plugin('monaco-editor').use(MonacoWebpackPlugin, [
        {
            languages: ['javascript']
        }
    ])
};

export default {
    ...,
    chainWebpack 
}

// 使用react-monaco-editor
import React, { Component } from 'react';
import ReactMonacoEditor from 'react-monaco-editor';

class MonacoEditor extends Component {
    editorDidMount = (editor) => {
        this.editor = editor;
    };

    handleChange = (value) => {
        this.props.onChange && this.props.onChange(value)
    };

    render() {
        const options = {
            selectOnLineNumbers: true
        }
        return (
            <ReactMonacoEditor
                language="javascript"
                theme="vs-light"
                defaultValue={this.props.defaultValue}
                value={this.props.value}
                options={options}
                onChange={this.handleChange}
                editorDidMount={this.editorDidMount}
            />
        )
    }
};

**Comment by tomorrowcheng** [comment]
请问下上面的问题是如何解决的？我和上面一样的配置，代码也没有高亮，求帮忙～

**Comment by youngjuning** [comment]
> 请问下上面的问题是如何解决的？我和上面一样的配置，代码也没有高亮，求帮忙～

+1
