### ISSUE TITLE
动态添加的路由如何注册页面级的model?

### ISSUE THREAD

**Issue by Sayid1** [umijs/umi#2509]
pages的页面结构如下图：
![image](https://user-images.githubusercontent.com/29008437/58677883-4359d200-8390-11e9-8947-2775ee089527.png)

动态添加的路由如下
![image](https://user-images.githubusercontent.com/29008437/58677904-540a4800-8390-11e9-824e-aebf4071b948.png)

现在pages/Visualization下面的文件使用dva的connect后，无法获得model里面的state

**Comment by xiaohuoni** [comment]
你在这里是运行时环境，你这个样子require应该还是找不到这些文件才对吧？

**Comment by chanceLe** [comment]
解决了吗？  遇到同样的问题
