### ISSUE TITLE
windows下嵌套路由没有正确生成

### ISSUE THREAD

**Issue by boxcc** [umijs/umi#251]
目录结构
```
+ form
    + step-form
        - _layout.js
        - index.js
        - a.js
```

打开 `/form/step-form/a` 提示404, 再刷新页面看到路由列表是  `/form\step-form`

应该是嵌套路由没有正确生成

**Comment by sorrycc** [comment]
好吧，又是 winPath 问题，明天我找 win 电脑测下。
