### ISSUE TITLE
每次yarn start的时候都有烦人的：Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by kaoding** [umijs/umi#2510]
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by sorrycc** [comment]
如何复现？

**Comment by kaoding** [comment]
![image](https://user-images.githubusercontent.com/18542211/58756001-2228eb00-8522-11e9-9a64-13dff41d461f.png)

**Comment by k983551019** [comment]
我也有

**Comment by sorrycc** [comment]
应该是 ant-design-pro 里配了额外 webpack 插件给的警告，我用 create-umi 选 app -> (dva、antd、等）没能复现这个问题。

**Comment by drizzlesconsin** [comment]
> 应该是 ant-design-pro 里配了额外 webpack 插件给的警告，我用 create-umi 选 app -> (dva、antd、等）没能复现这个问题。

@sorrycc 是因为自定义打包规则，请问有解吗？
```ts
// config/config.ts
chainWebpack(memo) {
  memo.plugin('extract-css').tap(() => []);
}
```
## 相关 Issues
+ #2788
+ #2127
+ #3833
