### ISSUE TITLE
将index.css修改为index.less报错

### ISSUE THREAD

**Issue by whateveryoudo** [umijs/umi#2517]
pages  下的index.css修改为index.less报错  ，报错信息如下:
`Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: ENOENT: no such file or directory, open 'E:\REACT\dhb-website-reconsitution\src\pages\index.css'`

**Comment by sorrycc** [comment]
在 JS 文件里需要修改对于 css 文件的引用。
