### ISSUE TITLE
can't find module eslint-config-umi

### ISSUE THREAD

**Issue by DiamondYuan** [umijs/umi#2519]
![image](https://user-images.githubusercontent.com/9692408/58800485-92c32b00-863a-11e9-9b63-665caa778cae.png)

![image](https://user-images.githubusercontent.com/9692408/58800489-9787df00-863a-11e9-82ad-48db3079cd35.png)

**Comment by DiamondYuan** [comment]
project path https://github.com/DiamondYuan/switch

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/58800534-b4bcad80-863a-11e9-80f6-795814b08e70.png)


that works for me. but i think config of eslint-config-umi is not correct.

**Comment by leftstick** [comment]
我试了下你的repo，如下配置没有错

```javascript
module.exports = {
  extends: ['umi']
};
```

所以我在想，是不是你那依赖安装时出什么问题了。。。

**Comment by xiaohuoni** [comment]
@DiamondYuan 我这边也可以使用，再确认一下

**Comment by sorrycc** [comment]
有问题再 reopen。

**Comment by baochengshi** [comment]
大神问一下哈，这个文件再增加自定义配置可以吗？为什么我加了之后没反应？没报错页不提示
