### ISSUE TITLE
× TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by ShaneKing** [umijs/umi#252]
https://github.com/ShaneKing/sk-user

npm install
umi dev

报typeerror，写法的问题么？

![image](https://user-images.githubusercontent.com/3394899/37837171-7ec4d822-2eef-11e8-9701-81e160692ac6.png)

**Comment by sorrycc** [comment]
super undefined, 是不是继承了一个 undefined 的类？

**Comment by ShaneKing** [comment]
@sorrycc 
嗯，import的时候放到{}里了：import {Comp} from 'xxx';
export default的Class要放在大括号外面。。。
