### ISSUE TITLE
_@babel_types@7.4.4@@babel这个包含有es6语法

### ISSUE THREAD

**Issue by oraclexudehua** [umijs/umi#2523]
## 背景

> 使用antpro不能成功构建，dev热部署正常

## 思路

> umi交流群，给出方案，翻阅发现_@babel_types@7.4.4@@babel好像这个有问题

**Comment by sorrycc** [comment]
没理解问题是啥，复现步骤？

**Comment by oraclexudehua** [comment]
不好意思，是这样的
1.昨天umi2.7版本更新（我的项目没有锁定版本），然后install之后，项目就不能正常编译了
vendors.async.js from UglifyJs
Unexpected token: keyword «const» [vendors.async.js:18,0]

异常如上，然后根据https://github.com/sorrycc/blog/issues/68
使用cross-env  COMPRESS=none umi build，查看vendors.async.js的第18行代码，并没有发现含有const，但是在这个vendors.async.js的164行是存在const定义，查看模块后发现_@babel_type  版本是7.4.4（不知道我这样理解是否正确）
------------------ 原始邮件 ------------------
发件人: "chencheng (云谦)"<notifications@github.com>;
发送时间: 2019年6月3日(星期一) 晚上11:00
收件人: "umijs/umi"<umi@noreply.github.com>;
抄送: "小许"<2320838977@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [umijs/umi] _@babel_types@7.4.4@@babel这个包含有es6语法 (#2523)




没理解问题是啥，复现步骤？

**Comment by sorrycc** [comment]
看下 https://github.com/umijs/umi/issues/2520 ，应该是相同问题。
