### ISSUE TITLE
Graphql 配置到umi?

### ISSUE THREAD

**Issue by sanshuiwang** [umijs/umi#2532]
## Graphql
#
![image](https://user-images.githubusercontent.com/20984566/58874575-bef2b080-86fb-11e9-8e19-25922d3dc936.png)
umi 如何配置.graphql文件

## 相关环境信息

- **Umi 版本**：2.6.16
- **Node 版本**：12.1.0
- **操作系统**：macOS

**Comment by leftstick** [comment]
来吧少年，用这个配置：

```javascript
chainWebpack(config, { webpack }) {
    config.module
      .rule('graphql')
      .test(/\.gql$/)
      .exclude.add(/node_modules/)
      .end()
      .use('graphql')
      .loader('graphql-tag/loader')

    config.module
      .rule('exclude')
      .exclude.add(/\.gql$/)
      .end()
  },
```

无论`.graphql`还是`.gql`都是`umi`未知的module，所以进了默认的`exclude`规则，然后也被`url-loader`处理了一下，这就是为什么你的导入永远是一个base64的字符串的缘故。。。

所以我们只要修改默认的`exclude`规则，把`.graphql`和`.gql`加入到排除列表里，一切就都正常了...

**Comment by sanshuiwang** [comment]
> 来吧少年，用这个配置：
> 
> ```js
> chainWebpack(config, { webpack }) {
>     config.module
>       .rule('graphql')
>       .test(/\.gql$/)
>       .exclude.add(/node_modules/)
>       .end()
>       .use('graphql')
>       .loader('graphql-tag/loader')
> 
>     config.module
>       .rule('exclude')
>       .exclude.add(/\.gql$/)
>       .end()
>   },
> ```
> 
> 无论`.graphql`还是`.gql`都是`umi`未知的module，所以进了默认的`exclude`规则，然后也被`url-loader`处理了一下，这就是为什么你的导入永远是一个base64的字符串的缘故。。。
> 
> 所以我们只要修改默认的`exclude`规则，把`.graphql`和`.gql`加入到排除列表里，一切就都正常了...

@leftstick 溜溜溜里那个溜皮😄

**Comment by sanshuiwang** [comment]
https://github.com/neutrinojs/webpack-chain
