### ISSUE TITLE
使用antd的时候Menu.Item标签内无法正常使用id属性

### ISSUE THREAD

**Issue by dragooncjw** [umijs/umi#2533]
下面是我的报错信息：
![image](https://user-images.githubusercontent.com/13393433/58889619-ccb82e00-871b-11e9-8da3-ccf6267bdd90.png)
我在yarn start调试模式下是可以正常运行跳转的，但是umi build后，我在dist文件夹下serve启动，却无法正常运行跳转。我尝试在外部套一个div或者Fragment，加上id也是报错的，内部span加id可以但是不符合我点击事件代理获取点击区域id的应用情形，想问一下如何在antd组件内使用id属性？我这样的情况下是否有解决方案？

**Comment by sorrycc** [comment]
这应该去 antd 的 issue 提。
