### ISSUE TITLE
我把global.css 改成global.less 以后出现问题

### ISSUE THREAD

**Issue by ManuRodgers** [umijs/umi#2534]
![image](https://user-images.githubusercontent.com/33333844/58926138-679d2080-878d-11e9-85ac-e21ae37bd035.png)

请问这里需要什么额外的配置吗？ 查了一下issue历史 没有发现解决方案

**Comment by xiaohuoni** [comment]
重启服务了嘛？

**Comment by sorrycc** [comment]
给复现后再 reopen。

**Comment by afc163** [comment]
http://github.com/ant-design/ant-design-pro

pro 现在应该就不行。https://github.com/ant-design/ant-design-pro/issues/4346
