### ISSUE TITLE
history 为 hash 时路由错误

### ISSUE THREAD

**Issue by ffalconjs** [umijs/umi#2538]
配置项：
history: 'hash',
base: '/umi',

运行结果路由地址并非是hash形式：
http://localhost:8001/umi/list/tablelist
期望的结果
http://localhost:8001/umi/#/list/tablelist

- **Umi 版本**：2.7.1
- **Node 版本**：v11.12.0
- **操作系统**：mac

**Comment by xiaohuoni** [comment]
按照你的配置
结果是
http://localhost:8001/#/umi/list/tablelist

**Comment by ffalconjs** [comment]
<Link to='/list/tablelist'> 跳转的结果是 http://localhost:8001/umi/list/tablelist 而不是http://localhost:8001/#/umi/list/tablelist
另外期望的结果 http://localhost:8001/umi/#/list/tablelist 需要怎么配置

**Comment by xiaohuoni** [comment]
[umihash.zip](https://github.com/umijs/umi/files/3256328/umihash.zip)
根目录运行umi dev

**Comment by sorrycc** [comment]
不能复现，有问题再 reopen 。

**Comment by jing-wu** [comment]
遇到同样的问题
history: 'hash',
base: '/learn',

期望：http://localhost:8000/learn/#/index
实际：http://localhost:8000/#/learn/index

并且后续的路由跳转（例如回到首页），浏览器中的#没了，又变成了browserHistory的形式：
http://localhost:8000/learn/index
