### ISSUE TITLE
ReferenceError:Can't find variable:IntersectionObserver

### ISSUE THREAD

**Issue by SherilyShieh** [umijs/umi#2539]
When I open my web page in safari and got this error, but it worked fine on chrome。
![umi错误](https://user-images.githubusercontent.com/16333792/58942167-d4291700-87af-11e9-9b65-08c73f4f80d5.png)

safari：
![safari](https://user-images.githubusercontent.com/16333792/58942210-eb680480-87af-11e9-8654-c53fa2765c03.png)

macOS:
![macos](https://user-images.githubusercontent.com/16333792/58942243-fae74d80-87af-11e9-92c1-7fb9590073a2.png)

**Comment by xiaohuoni** [comment]
You can try it， https://umijs.org/zh/config/#targets
