### ISSUE TITLE
在vscode中debugger umi 应用

### ISSUE THREAD

**Issue by linyongping** [umijs/umi#2542]
### 在vscode中debugger 引用

这个问题之前有人问过，可能描述不清，
在vscode中debugger 单页应用真的很不错，目前Create React App 可以实现这个功能，理论上umi应该也不是难事，我尝试了几遍，但是都跑不起来，所以特来发一个issue
贴一些资料以供参考

[create-react-app debugger vscode config](https://github.com/facebook/create-react-app/blob/eee8491d57d67dd76f0806a7512eaba2ce9c36f0/docusaurus/docs/setting-up-your-editor.md)

[youtube link for debugger in vscode for CRA](https://www.youtube.com/watch?v=UI7dpnVoad8&list=WL&index=23&t=0s )
-

**Comment by linyongping** [comment]
问题解决
dabugger使用配置如下：
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "debugger umi",
            "url": "http://localhost:8001",
            "webRoot": "${workspaceFolder}",
            "sourceMapPathOverrides": {
                "webpack:///./*": "${webRoot}/*",
                "webpack:///src/*": "${webRoot}/*",
                "webpack:///*": "*",
                "src:///src/*":"${webRoot}/*"
            }
        },
    ]
}`

**Comment by kwzm** [comment]
@linyongping 想问一下，您这个配置只能测试页面吧，mock 文件能测试吗？

**Comment by WLyKan** [comment]
> 问题解决
> dabugger使用配置如下：
> `{ // Use IntelliSense to learn about possible attributes. // Hover to view descriptions of existing attributes. // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387 "version": "0.2.0", "configurations": [ { "type": "chrome", "request": "launch", "name": "debugger umi", "url": "http://localhost:8001", "webRoot": "${workspaceFolder}", "sourceMapPathOverrides": { "webpack:///./*": "${webRoot}/*", "webpack:///src/*": "${webRoot}/*", "webpack:///*": "*", "src:///src/*":"${webRoot}/*" } }, ] }`

```json
...
      "webRoot": "${workspaceFolder}",
      "sourceMapPathOverrides": {
          "webpack:///./*": "${webRoot}/*",
          "webpack:///src/*": "${webRoot}/*",
          "webpack:///*": "*",
          "src:///src/*": "${webRoot}/*"
      }
...
```

这样配置，至少能通过vs code打断点了。。。不用在devtools中先找代码，再打断点了

**Comment by zjp123** [comment]
> 问题解决 dabugger使用配置如下： `{ // Use IntelliSense to learn about possible attributes. // Hover to view descriptions of existing attributes. // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387 "version": "0.2.0", "configurations": [ { "type": "chrome", "request": "launch", "name": "debugger umi", "url": "http://localhost:8001", "webRoot": "${workspaceFolder}", "sourceMapPathOverrides": { "webpack:///./*": "${webRoot}/*", "webpack:///src/*": "${webRoot}/*", "webpack:///*": "*", "src:///src/*":"${webRoot}/*" } }, ] }`

不行啊大佬，我用的是umi 3.x的版本，不知道是什么影响，我通过上面的配置，调试信息报找不到xxx.jx的映射文件
