### ISSUE TITLE
umi target配置不管用

### ISSUE THREAD

**Issue by gaogaolater** [umijs/umi#2546]
## What happens?

umi 2.7 target不管设置什么，编译出来的js 都包含箭头函数，应该是一个bug

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：2.7.0
- **Node 版本**：10+
- **操作系统**：mac

**Comment by xiaohuoni** [comment]
随意项目测试,没有箭头函数
```js
export default {
  targets:{
    ie:9
  }
};
```

**Comment by sorrycc** [comment]
[sorrycc-usr5lK.zip](https://github.com/umijs/umi/files/3268650/sorrycc-usr5lK.zip)
用了一个最简例子，不能复现你的问题。

1. 不配 `targets` 时产物有箭头符号
2. 配 `targets: : {ie:9}` 后产物无箭头符号
