### ISSUE TITLE
Request to feature umi on Docusaurus users page

### ISSUE THREAD

**Issue by ericbuss** [umijs/umi#2558]
Hello, we would like to feature your project to the Docusaurus [users](https://docusaurus.io/en/users) page.

If you are okay with it, are you able to provide a logo we can use? Additional information can be found [here](https://github.com/facebook/Docusaurus/issues/1437)

**Comment by sorrycc** [comment]
But we're using vuepress.

**Comment by ericbuss** [comment]
@sorrycc My apologies. I found your project through the Docusaurus depencies. My bad.
