### ISSUE TITLE
能否统一升级Core-js@3.x版本?

### ISSUE THREAD

**Issue by lauer3912** [umijs/umi#2566]
## What happens?

能否统一使用Core-js@3.x 版本

## 相关环境信息

- **Umi 版本**：2.7.3
- **Node 版本**：10.15.3
- **操作系统**：Win10

**Comment by sorrycc** [comment]
原因呢？使用 umi 时应该不需要感知 core-js 版本的。

**Comment by 2zH** [comment]
> 原因呢？使用 umi 时应该不需要感知 core-js 版本的。

core-js@3.x 包含了 flat/web-url/web-url-search-params
core-js@2.x 没有 web-url ，flat 对应的 polyfill 仍然还是 flatten

emmmmm 虽然都有第三方库作为替代

**Comment by lauer3912** [comment]
@sorrycc 
see https://babeljs.io/docs/en/babel-polyfill

> As of Babel 7.4.0, this package has been deprecated

**Comment by aixfox** [comment]
@lauer3912 你们有直接升到 core-js@3 吗？有没有什么迁移成本。

**Comment by sorrycc** [comment]
升过一次升失败了，到 umi@3 时再统一升级。
