### ISSUE TITLE
[Feature Request] Support split node_modules package to vendors.js

### ISSUE THREAD

**Issue by hstarorg** [umijs/umi#2568]
## Background

It only give me umi.<hash>.js when I build a umi project. Any times this `umi.js` is a very big file, so I want to split node_modules package to `vendors.js`

## Proposal

Add splitChunks in webpack optimization config to support split vendors bundle.

**Comment by sorrycc** [comment]
Use [chainWebpack](https://umijs.org/config/#chainwebpack) to add splitChunks configuration.

**Comment by hstarorg** [comment]
@sorrycc very thanks, I find the doc: https://umijs.org/zh/plugin/umi-plugin-react.html#chunks
