### ISSUE TITLE
服务器停掉之后请求不会走到errorhandler哎

### ISSUE THREAD

**Issue by pkaq** [umijs/umi#2569]
服务器停掉之后请求不会走到errorhandler哎

![TIM截图20190610190827](https://user-images.githubusercontent.com/4537450/59191863-44baa400-8bb3-11e9-8f81-fa373180e94d.png)

**Comment by sorrycc** [comment]
这是 fetch 使用的问题，和 umi 没啥关系。

**Comment by pkaq** [comment]
![123](https://user-images.githubusercontent.com/4537450/59611021-26bde800-914d-11e9-8a4d-a35f3f86ee93.png)
可是报错显示 umi-request 中这句错误 导致没走errorHandler也没进拦截器把？
@sorrycc
