### ISSUE TITLE
umi dev下目录约定路由跳转正常 build之后路由跳转空白

### ISSUE THREAD

**Issue by yclnycl** [umijs/umi#257]
问题如题 可复现demo https://github.com/yclnycl/umi-demo

打包后尝试使用nginx和php启动server都不行,跳转均空白

点击首页右下方图标跳转

**Comment by sorrycc** [comment]
demo 库没有 package.json，我安装不了依赖。

**Comment by sorrycc** [comment]
Info/info 没内容是因为出错了，我写了个简单内容做替换是可以出来的。

**Comment by sorrycc** [comment]
有问题再 reopen 。
