### ISSUE TITLE
umi block add 安装依赖报错

### ISSUE THREAD

**Issue by ffalconjs** [umijs/umi#2575]
原工程已经安装过 ant-design-pro ，执行umi block add就会报错
$ umi block add ant-design-pro/TableList --path /Demo/TableList
Warning: Please use `require("react-router").matchPath` instead of `require("react-router/matchPath")`. Support for the latter will be removed in the next major release.
Warning: Please use `require("react-router").Router` instead of `require("react-router/Router")`. Support for the latter will be removed in the next major release.
Warning: Please use `require("react-router").Switch` instead of `require("react-router/Switch")`. Support for the latter will be removed in the next major release.
Warning: Please use `require("react-router").Route` instead of `require("react-router/Route")`. Support for the latter will be removed in the next major release.
✔ Parse url and args
✔ Git fetch
✔ Git checkout master
✔ Git pull
✖ Install additional dependencies ant-design-pro@^2.1.1 with npm
✖  error     Error: Error: Command failed: npm install ant-design-pro@^2.1.1 --save 
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "ant-design-pro" under a package
npm ERR! also called "ant-design-pro". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

## 相关环境信息

- **Umi 版本**：2.7.3
- **Node 版本**：v12.4.0
- **操作系统**：mac

**Comment by guxiaobai** [comment]
`umi block add ant-design-pro/TableList`

其中 `ant-design-pro/TableList` 是 `list` 调用 `http://blocks.umijs.org/api/blocks`接口返回数据 与 [pro-block](https://github.com/ant-design/pro-blocks)不一致


正确: `umi block add ant-design-pro/ListTableList`
