### ISSUE TITLE
求助，项目启动报错，win7下没问题，切换到macOs就报错

### ISSUE THREAD

**Issue by congceng999** [umijs/umi#2576]
win7正常启动，macOs10.14.1启动报错：
**fs.js:114   throw err; 
Error: ENOENT: no such file or directory,**
大神们，帮我看一下为什么，node_moudles删了好多次了，没用

- **Umi 2.7**:
- **Node v10.16.0**:
![1560256049538](https://user-images.githubusercontent.com/44044504/59272550-dea05080-8c88-11e9-9d12-fe2a80003ebd.jpg)

**Comment by sorrycc** [comment]
把 `未命名文件夹 3` 改成英文，并且不要空格试试。

**Comment by congceng999** [comment]
> 把 `未命名文件夹 3` 改成英文，并且不要空格试试。

一样的报错，刚试过了。。。。。

**Comment by congceng999** [comment]
> > 把 `未命名文件夹 3` 改成英文，并且不要空格试试。
> 
> 一样的报错，刚试过了。。。。。

![1560266692281](https://user-images.githubusercontent.com/44044504/59285192-28486580-8ca0-11e9-8408-daf0b1d8c2c3.jpg)

**Comment by sorrycc** [comment]
给可复现的仓库。

**Comment by sorrycc** [comment]
set xxx 是 windows 下的使用方式，换成 mac/linux 的。

**Comment by congceng999** [comment]
> set xxx 是 windows 下的使用方式，换成 mac/linux 的。

换成export 成功启动项目  谢谢cc大神
