### ISSUE TITLE
Upgrade umi-request package in the NPM to support async types

### ISSUE THREAD

**Issue by laozhu** [umijs/umi#2578]
![code](https://user-images.githubusercontent.com/1212457/59320441-fc110100-8d00-11e9-8ace-96d92e4274b3.png)

Publish [latest code](https://github.com/umijs/umi-request/blob/master/types/index.d.ts#L59) in GitHub to NPM please.

**Comment by sorrycc** [comment]
+ umi-request@1.0.8
