### ISSUE TITLE
使用 umi-plugin-qiankun 子工程umi.js 引用其他js  发起的请求是主工程的地址

### ISSUE THREAD

**Issue by yuanguandong** [umijs/umi#2579]
使用 umi-plugin-qiankun 子工程umi.js 引用其他js  发起的请求是主工程的地址， 这个用什么方式解决呢？也就是主工程加载子工程的资源地址问题如何解决？
直观的比如说：子工程app1是一个初始化的umi app, 应该有一个小丑的图片，但是加载的图片地址是主工程的，主工程是没有这个图片的

![11111](https://user-images.githubusercontent.com/13197560/59323093-c4f41d00-8d0b-11e9-9e99-d776a07ca05d.png)

**Comment by sorrycc** [comment]
已知问题，先把图片传 cdn 解决。

**Comment by kuitos** [comment]
umi-plugin-qiankun  会默认支持这个能力

**Comment by sorrycc** [comment]
@kuitos 现在是 fetch CSS，然后通过 style 插进去的，CSS 里如果引相对路径就会找不到。

**Comment by kuitos** [comment]
想了下这种场景好像子应用不自己处理（比如传 cdn），qiankun 也没办法解决？比如子应用在 html 里应用了一个图片 `<img src="./a.png">` 这种

**Comment by kuitos** [comment]
相关 issue https://github.com/umijs/qiankun/issues/11#issuecomment-506168153 @yuanguandong
