### ISSUE TITLE
yarn create umi 报错

### ISSUE THREAD

**Issue by MBearo** [umijs/umi#2580]
## What happens?
运行yarn create umi 报错

## Mini Showcase Repository(REQUIRED)

无法提供

## How To Reproduce
**Steps to reproduce the behavior:**
1. yarn create umi

**Expected behavior**
1. 进行到可以选择模板的步骤

## Context

```
$ yarn create umi
yarn create v1.16.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/MBear/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```
连着梯子呢
- **yarn Version**: 1.16.0
- **Umi Version**: 2.7.3
- **Node Version**: 10.14.1
- **Platform**: Mac 10.12.5

**Comment by sorrycc** [comment]
create-umi 没有 event-stream 的依赖，我猜是你 yarn 全局环境的问题，你试着 `yarn global add` 其他的包试试，应该也会报这个错。

**Comment by longhaiyan** [comment]
https://github.com/yarnpkg/yarn/issues/6725#issuecomment-444702390 我在这找到了答案
