### ISSUE TITLE
对于tsx的test,该如何在umi 中配置

### ISSUE THREAD

**Issue by TRUEJASONFANS** [umijs/umi#2585]
按照https://www.yuque.com/ant-design/course/unittest 配置了jest.config.js
以及测试tsx文件
`export default () => {
    return <div>test</div>;
};`
测试代码：
```
import { mount } from 'enzyme';
import TestDemo from '../component/TestDemo'

test('TestDemo', () => {
  const wrapper = mount(<TestDemo />);
  expect(wrapper.find('div').text()).toBe('test');
});
```
测试失败:
![image](https://user-images.githubusercontent.com/5670289/59332165-33df6f00-8d28-11e9-8be0-3946c7a004cf.png)
![image](https://user-images.githubusercontent.com/5670289/59332271-69845800-8d28-11e9-90f6-ba77f19cff6e.png)

当我将该文件改为jsx,或者js时候 测试能通过

**Comment by TRUEJASONFANS** [comment]
是不是ts-jest与Umi的版本不兼容? 按照这个comand line alert.

**Comment by sorrycc** [comment]
啥都不用干应该就能跑 ts 的测试的。

**Comment by TRUEJASONFANS** [comment]
@sorrycc 
不加ts-jest依赖， 啥都不干也run 不过。 报错显示是jest没能正确parse tsx文件。
![image](https://user-images.githubusercontent.com/5670289/59358123-96536200-8d5e-11e9-82ad-9600653a14a1.png)
source project 在https://github.com/TRUEJASONFANS/sprint-pocker-front

**Comment by TRUEJASONFANS** [comment]
@sorrycc  我把umi 升级到2.7.0fix了这个问题， 之前2.1.0 确实过不了
