### ISSUE TITLE
ssr demo 报错

### ISSUE THREAD

**Issue by williamnie** [umijs/umi#2586]
我在尝试ssr，clone了umi-example,，然后clone了umi的feat/ssr分支到本地，执行build 以后，在example项目中，引用本地的umi，以及umi-build-dev ，但是还是报错，ssr不是配置项，请问这是什么问题，哪里出错了么？

example的package代码如下
`{
  "scripts": {
    "start": "umi dev"
  },
  "dependencies": {
    "koa": "^2.7.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "regenerator-runtime": "^0.13.2",
    "umi": "file:/Users/xiaobei/Documents/aminer/ssrTest/umi/packages/umi",
    "umi-plugin-dva": "file:/Users/xiaobei/Documents/aminer/ssrTest/umi/packages/umi-plugin-dva",
    "umi-build-dev": "file:/Users/xiaobei/Documents/aminer/ssrTest/umi/packages/umi-build-dev",
    "webpack-node-externals": "^1.7.2"
  }
}
`

**Comment by sorrycc** [comment]
ssr 不是配置项说明没有用本地 link 过来的 umi 跑。

**Comment by williamnie** [comment]
现在已经跑起来了，原因是umi里面的umi-build-dev依赖没改，跑起来后，csr的可以运行，但是ssr的一直报错，
 Invariant Violation: Objects are not valid as a React child (found: object with keys {htmlElement, rootContainer}). If you meant to render a collection of children, use an array instead.

在server.js 里面打印serverRes 为{ htmlElement:
   { '$$typeof': Symbol(react.element),
     type: 'html',
     key: null,
     ref: null,
     props: { children: [Array] },
     _owner: null,
     _store: {} },
  rootContainer:
   { '$$typeof': Symbol(react.element),
     type: [Function: _DvaContainer],
     key: null,
     ref: null,
     props: { children: [Object] },
     _owner: null,
     _store: {} } }

看issue，fix Invariant Violation bug的pr，我的umi-build-dev文件已经没问题了，这里不知道是哪里的问题了，能指点下么？

**Comment by sorrycc** [comment]
没有 `npm run build`?

**Comment by williamnie** [comment]
build 了，但还是不行，build的时候，打印了下面的信息，正在排查问题
`(node:62898) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: webpackConfig should be plain object.
    at Object.build [as default] (/Users/xiaobei/Documents/aminer/ssrTest/umi-example-ssr/node_modules/umi/node_modules/umi-build-dev/node_modules/af-webpack/lib/build.js:33:23)
    at /Users/xiaobei/Documents/aminer/ssrTest/umi-example-ssr/node_modules/umi/node_modules/umi-build-dev/lib/plugins/commands/build/index.js:56:46
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:62898) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:62898) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 5.07s.`

**Comment by sorrycc** [comment]
等功能正式发布吧，还在开发中。

**Comment by ycjcl868** [comment]
开发中，如果想体验的话：
1. clone umi，切换到 `feat/ssr` 分支
1. 按 `CONTRIBUTING.md` 步骤进行安装和 build
1. umi 根目录下执行 

```bash
$ cd packages
$ cd af-webpack && yarn link && cd ..
$ cd umi-build-dev && yarn link && cd ..
$ cd umi-plugin-dva && yarn link && cd ..
$ cd umi && yarn link && cd ..
$ yarn link af-webpack && yarn link umi-build-dev && yarn link umi-plugin-dva && yarn link umi && yarn link umi-plugin-react && yarn link umi-plugin-hd && yarn link umi-plugin-prerender
```

1. 然后在 demo 里，执行 `npm run build && node server.js`，访问 `localhost:7001` 即可

![image](https://user-images.githubusercontent.com/13595509/59416063-3ceb4180-8df7-11e9-962a-293112da9102.png)

**Comment by sorrycc** [comment]
不用 link 那么多，只要 umi 和 umi-plugin-react 就好了。
