### ISSUE TITLE
when i use yarn create umi and add targets in the config doesn't working

### ISSUE THREAD

**Issue by liudq** [umijs/umi#2587]
## What happens?

 yarn create umi 之后 在配置文件里增加targets 没有生效。

## 复现步骤

1.yarn create umi
2.umirc.js 里添加如下代码：

 targets: {
    android: 5,
    ios: 7,
    safari: 7,
    chrome: 58,
    ie: 11,
  }
3. ios8.0的手机打开空白页面

## 相关环境信息

 "umi": "^2.7.0",
 "umi-plugin-react": "^1.8.3",
"dva": "^2.6.0-beta.4",
   "react": "^16.8.6",
node版本是：v10.16.0

**Comment by xiaohuoni** [comment]
提供几个步骤供你排查一下问题
1、targets需要执行build才会有效，dev是无效的
2、打开build生成的umi.js，如果使用默认配置，那就是dist/umi.js
3、全局搜索一下 `const` 和 `=>` ，如果都没有，那说明targets是生效的
你配置这么多，建议你直接设置 `ie:9`

**Comment by liudq** [comment]
>您好 排查了一下 
> 1、targets是执行了build的
> 2、在page下生成了.umi文件夹 里面有umi.js
> 3、umi.js 里有 const 和 =>

**Comment by sorrycc** [comment]
dist/umi.js 里搜，有没有 const 和 `=>`，不是在 `pages/.umi/umi.js` 里搜。

**Comment by sorrycc** [comment]
targets 配置肯定是有效的，检查自己的使用问题吧。
