### ISSUE TITLE
umi dev Page/models || Page/Models 两种命名文件格式热更新不一致

### ISSUE THREAD

**Issue by li2215890610** [umijs/umi#2588]
## Background

最近在使用umi开发的时候出现了一个问题，我查询源码没有找到这个解决办法

我的一个个人癖好每个文件名称都想以大写开头，

![image](https://user-images.githubusercontent.com/19567679/59343520-a6f3e000-8d3e-11e9-88b2-8ff052cb69f3.png)

和Umi 官方推荐的不一样，

我的目录结构是这样的

![image](https://user-images.githubusercontent.com/19567679/59343560-bd9a3700-8d3e-11e9-9456-b4077458301c.png)

## Proposal

我发现 pages/Models 如果以这样的文件方式命名，command+s 保存之后 在Models文件里面 修改一些代码热更新不会马上更新的

但是我把 pages/models 如果以这样的文件方式命名，command+s 保存之后 在models文件里面 修改一些代码热更新就会马上的更新

我觉得是 umi 包里面做了正则，然后就去看了下源代码，但是没有找到这个块关联的代码

希望官方也能支持这种命名的方式吧！

如果这个你们觉得没有那么的必要，能不能告诉我在哪里可以修改，我修改一下本地的代码，不用纳入你们版本迭代的计划中。

**Comment by sorrycc** [comment]
不支持大写字母开头的，习惯下用小写字母吧。。

**Comment by li2215890610** [comment]
> 不支持大写字母开头的，习惯下用小写字母吧..

你方便给我指出在哪里匹配大写字母的吗？ 我在umi -g 目录下的代码里面没有找到我在本地改。

**Comment by sorrycc** [comment]
pages 是 umi-build-dev 里写死的，models 是的 umi-plugin-dva 里写死的。

**Comment by sorrycc** [comment]
有兴趣可以自己研究下。

**Comment by li2215890610** [comment]
> 有兴趣可以自己研究下。

好的谢谢了
