### ISSUE TITLE
使用umi、antd、dva构建的项目，在比较旧的安卓手机上运行报错

### ISSUE THREAD

**Issue by lbx-wilson** [umijs/umi#2589]
![image](https://user-images.githubusercontent.com/25903015/59346586-356b6000-8d45-11e9-8ead-84b32c23036e.png)
打包运行的时候 _ansi-regex@4.1.0@ansi-regex包里的es6语法没被编译导致不支持es6的浏览器报错

**Comment by sorrycc** [comment]
基于 https://github.com/umijs/es5-imcompatible-versions/blob/master/package.json#L130 的配置，ansi-regex@4 是会走 babel 编译的，打包后依旧有 `=>` 应该是 targets 没有配到位，比如配 `ie: 10` 试试。
