### ISSUE TITLE
window.navigator is readonly under Chrome

### ISSUE THREAD

**Issue by kocomic** [umijs/umi#2590]
## What happens?
cause error when change locale
## Mini Showcase Repository(REQUIRED)
just this repo
> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1. yarn create umi
2. choose ant-design-pro
3. choose TypeScript
4. yarn
5. yarn start
6. change locale in navbar

**Expected behavior**
1.
2.

## Context

- **Umi Version**: 2.7.5
- **Node Version**: 10.15.3
- **Platform**: macOS Mojave 10.14.5

**Comment by linfengluo** [comment]
TypeError: Cannot assign to read only property 'navigator' of object '#<Window>'

node_modules/umi-plugin-locale/lib/locale.js:52

**Comment by kocomic** [comment]
> TypeError: Cannot assign to read only property 'navigator' of object '#'
> 
> node_modules/umi-plugin-locale/lib/locale.js:52

最新版本已修复。
