### ISSUE TITLE
run dev throw err "We should not have multiple dynamic routes under a directory"

### ISSUE THREAD

**Issue by guozhengzhongGit** [umijs/umi#2595]
## What happens?
- When i run shell "yarn start",i get an error "We should not have multiple dynamic routes under a directory".
- I use Conventional Routing and marked Dynamic Routing by '$'
- The error from 'node_modules/umi-build-dev/lid/routes/getRouteConfigFromDir.js:45:23'.
-**But,with the same code,my partner have no error,this is too strange**

## Context
- **Umi Version**: 2.1.2
-**umi-plugin-react**: 1.1.1
- **Node Version**:v10.16.0
- **Platform**:macOS Mojave(10.14.5)

**Comment by sorrycc** [comment]
There can't be more than one dynamic routing file starting with $ in a directory.

**Comment by guozhengzhongGit** [comment]
@sorrycc ok, i will check my directory,thanks~

**Comment by wbget** [comment]
![image](https://user-images.githubusercontent.com/12776391/59834440-95cc5400-937a-11e9-8e7a-8addff775d4b.png)
I can't wirte in this way?

**Comment by wbget** [comment]
![image](https://user-images.githubusercontent.com/12776391/59834440-95cc5400-937a-11e9-8e7a-8addff775d4b.png)
I can't wirte in this way?
