### ISSUE TITLE
配置hash history后，路径不正确

### ISSUE THREAD

**Issue by jing-wu** [umijs/umi#2597]
config.ts中配置：
history: 'hash',
base: '/learn',

期望：http://localhost:8000/learn/#/index
实际：http://localhost:8000/#/learn/index

并且后续的路由跳转（例如回到首页），浏览器中的#没了，又变成了browserHistory的形式：
http://localhost:8000/learn/index

**Comment by JustForLucky** [comment]
遇到同样的问题，umi version是2.7.5

**Comment by JustForLucky** [comment]
可以换到2.6.16版本，是正常的

**Comment by Monsterbx** [comment]
也遇到同样的问题，history：'hash' 设置不成功。切换2.6的umi版本可以。
![image](https://user-images.githubusercontent.com/27794222/59413457-268eb700-8df2-11e9-88e0-301b8acb380c.png)

**Comment by amily4555** [comment]
the some 

而且 NavLink 中 会把 base 带到路径中去

**Comment by amily4555** [comment]
如果  umi 版本回退到  v2.6.16
出现如下问题
![image](https://user-images.githubusercontent.com/2802841/59423702-3bc11100-8e05-11e9-8071-f8cf71561a28.png)

还需将 umi-plugin-dva 版本回退

`"umi-plugin-dva": "1.5.3"`

**Comment by amily4555** [comment]
@sorrycc 

可复现地址 

git@github.com:amily4555/umi-issues.git

望急修

**Comment by xf564246963** [comment]
ant-design-pro2.3.1的umi2.4.4也有这个问题

**Comment by sorrycc** [comment]
@amily4555 不能复现？

**Comment by sorrycc** [comment]
有问题再 reopen。

**Comment by DiamondYuan** [comment]
同样遇到问题。

https://github.com/DiamondYuan/vanaheim

修改 packages/vanaheim-website/.umirc.ts 的 history 为 'hash'

yarn && yarn bootstrap && yarn dev-website

**Comment by mizi-lin** [comment]
[git@github.com:mizi-lin/umi-issues.git](https://github.com/mizi-lin/umi-issues)
