### ISSUE TITLE
[Feature Request] 支持stylus-loader

### ISSUE THREAD

**Issue by fengxinming** [umijs/umi#2598]
## Background

基于create-react-app的项目使用了stylus做样式预处理，选择stylus是由于写法简易、灵活，可支持自定高级特性，把业务代码迁至umi之后发现不支持stylus-loader，我也提过issue但未解决 [#2577](https://github.com/umijs/umi/issues/2577)。

## Proposal

希望像vue-cli3一样，内置支持stylus，或者提供方法支持

**Comment by sorrycc** [comment]
直接提 PR 吧。

**Comment by fengxinming** [comment]
@sorrycc 弱弱的问一下 PR 是什么，去哪里提？加一个loader支持变得这么麻烦，我这边已经有解决方案了，亲测跟less处理保持一致，你可以 [点击这里](https://github.com/fengxinming/chain-css-loader) review一下实现方法，没问题就把这个关掉把！
