### ISSUE TITLE
配置devServer before后umi报错

### ISSUE THREAD

**Issue by Loogeek** [umijs/umi#2599]
## What happens?
同 #2161 提到的问题

配置devServer before后会报错
<img width="460" alt="屏幕快照 2019-06-13 下午7 50 55" src="https://user-images.githubusercontent.com/9320755/59430409-c4937900-8e14-11e9-9305-9a366ccd626a.png">

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：2.7.2
- **Node 版本**：8.12.0
- **操作系统**：os x

**Comment by sorrycc** [comment]
给复现步骤。

**Comment by Loogeek** [comment]
> 给复现步骤。
<img width="718" alt="屏幕快照 2019-06-14 下午2 45 36" src="https://user-images.githubusercontent.com/9320755/59488904-65d10c80-8eb3-11e9-83f0-de62dcad33e5.png">

配置devServer before后就可以复现，关闭dll配置后页面正常
