### ISSUE TITLE
umi@2.7 Unexpected token {

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#2600]
## What happens?
![image](https://user-images.githubusercontent.com/11746742/59439966-c830fb00-8e28-11e9-9d4a-ecf117725b39.png)
在谷歌浏览器47版本 发生这个错误，不知道ie会不会，找不到电脑验证。
搜索了编译后的代码，没有 `const` 和 `=>` 

- **Umi Version**: 2.7.1
- **Node Version**: 10.13.0
- **Platform**: windows

**Comment by sorrycc** [comment]
复现步骤？

**Comment by xiaohuoni** [comment]
正常设置targets，在谷歌版本47浏览器，打开。

**Comment by xiaohuoni** [comment]
非umi问题
