### ISSUE TITLE
umi线上 移动端报API Error

### ISSUE THREAD

**Issue by yanmeiYang** [umijs/umi#2604]
## What happens?
移动端线上报“Network Error”

![WechatIMG91](https://user-images.githubusercontent.com/13979990/59491785-20fca400-8eba-11e9-83ce-d0e636b01bd0.jpeg)

错误信息
![](https://user-images.githubusercontent.com/13979990/59478461-ea0f9980-8e8b-11e9-95f3-0c02b78d2a24.png)

链接：www.aminer.cn

- **Umi Version**: 2.7.3
- **Node Version**: 11.6
- **Platform**: iphone 8p

**Comment by ycjcl868** [comment]
这是服务端报错吧，和前端没关系

**Comment by yanmeiYang** [comment]
不是服务端报错，在桌面端没有问题，显示就是umi.js内部报错。
