### ISSUE TITLE
关于自定义文件夹热更新问题

### ISSUE THREAD

**Issue by SiroSong** [umijs/umi#2606]
## What happens?

对于自定义添加文件夹中的文件不能进行热更新，不能再自定义文件夹内容改变是自动重新编译。这种情况下需要怎么样设置？

**Comment by sorrycc** [comment]
没理解问题，什么是自定义文件夹。

**Comment by xiaohuoni** [comment]
写个小插件，添加监听应该可以。
https://umijs.org/zh/plugin/develop.html#addpagewatcher
