### ISSUE TITLE
targets 设置ie9 vendors.async.js还有const

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#2608]
## What happens?
```js
dynamicImport: {
  webpackChunkName: true,
  level: 3,
},
targets:{
  ie:9
}
```
`umi.js` 和相应的 `p__showDoc__index.async.js` 都没有 `const` 和箭头函数 `=>`
但是 vendors.async.js 还有`const` 和箭头函数 `=>`
![image](https://user-images.githubusercontent.com/11746742/59498452-092c1c80-8ec8-11e9-9c17-2e8c91737853.png)

## Context

- **Umi Version**:2.7.1
- **Node Version**:10.13.0
- **Platform**:mac

**Comment by xiaohuoni** [comment]
先关闭了。

**Comment by afc163** [comment]
什么原因？

**Comment by xiaohuoni** [comment]
@afc163 可能是来自未走 babel 编译的 node_modules

**Comment by chenshuai2144** [comment]
有些库就是死活不用 babel编译一下。比如 query-string。

**Comment by Inori-Lover** [comment]
```
    "umi": "^2.6.16",
    "umi-plugin-react": "^1.6.0",
```
umirc中targets的节选是这样的：
```
  targets: {
    ie: 10,
    ios: 8,
    chrome: 40,
  },
```
umi的chunk还是出现了const(只有一处)

**Comment by fishenal** [comment]
有什么解决办法吗

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/1421#issuecomment-516762499

**Comment by fishenal** [comment]
@xiaohuoni 

我遇到的问题可能是引用的fabric里引用的jsdom引用的一个库会出现高版本的代码，使用fabric-browserfy就解决了这个问题

**Comment by SongZhuhai** [comment]
vendors. async.js 的作用是什麼，我打包後運行服務器報錯
