### ISSUE TITLE
请问process.platform 的规则是什么？如何修改

### ISSUE THREAD

**Issue by htank-wang** [umijs/umi#2610]
process.platform在本地开发和构建都是"browser"。

我在进行第三方插件集成的时候，发现它也用了这个属性，要求是真实的platform。
如'darwin','win32', 'linux'。

请问这样的情况如何调整

**Comment by cyjake** [comment]
process 是 webpack 内建的 node-libs-browser 模块处理的，你用的第三方插件具体是啥哇，构建出来的代码不是在浏览器跑吗？

**Comment by htank-wang** [comment]
插件：monaco-editor@0.14.3 (根据不同系统显示不同的组合键)
源码位置：
![image](https://user-images.githubusercontent.com/17918845/59552575-50470a00-8fbb-11e9-8c28-4a97f73f7b31.png)
效果图：
![image](https://user-images.githubusercontent.com/17918845/59552601-b764be80-8fbb-11e9-81d1-8fdbc4d98443.png)

**Comment by cyjake** [comment]
看上去是 `process.platform === 'browser'` 反而导致它误判走了客户端逻辑，可以关闭 process shim 设置 `webconfig.node.process` 为 false 或者把 `process.platform` 置空解决

**Comment by htank-wang** [comment]
已解决。感谢！
![image](https://user-images.githubusercontent.com/17918845/59573600-5c7bb600-90e6-11e9-96da-36577d9d807a.png)

**Comment by htank-wang** [comment]
webconfig.node.process 设置为false不是一个解决方案，只要插件使用了process都会受影响。

process.platform 是怎么一个设置法呢？

虽然不太清楚使用node-libs-browser做什么用。个人觉得它的process.platform结果与其它比较出名有些出入，并且貌似插件的作者有不在维护的打算。是不是考虑采用其它方案？我相信umi是可以跨平台的。
