### ISSUE TITLE
webpackConfig.node should be turned off (almost) completely

### ISSUE THREAD

**Issue by cyjake** [umijs/umi#2612]
## What happens?

According to [webpack's documentation](https://webpack.js.org/configuration/node/), webpack shims node builtin modules as much as they can, unless `webpackConfig.node` is set to false.

Currently af-webpack sets `webpackConfig.node` to following object:

```js
// node
webpackConfig.node.merge({
  setImmediate: false,
  process: 'mock',
  dgram: 'empty',
  fs: 'empty',
  net: 'empty',
  tls: 'empty',
  child_process: 'empty',
});
```

This config indicates the builtin modules listed already gets set to false or mocked an empty object. But the rest of the modules (that chould be shimmed) are turned on now, which means modules like http, https, crypto, or path are all included. Full list of supported modules can be found at [node-libs-browser](https://github.com/webpack/node-libs-browser/blob/master/index.js).

This could lead to a bloated build with useless libraries. 

On the other hand, according to webpack/webpack#9262, node-libs-browser should be considered DEPRECATED at webpack 4, besides it is removed completely in webpack 5. 

## Mini Showcase Repository(REQUIRED)

TODO

## How To Reproduce
**Steps to reproduce the behavior:**
1. start dev server.
2. see if umi.js (or umi-dll.js) contains packages like querystring-es3 or stream-http by searching `./node_modules/querystring-es3` etc.

**Expected behavior**
1. start dev server.
2. umi.js (or umi-dll.js) should not contain shims of node builtin modules by default.

## Context

- **Umi Version**: latest
- **Node Version**: v10.15
- **Platform**: darwin

## Suggested Changes

According to my test on a medium sized web app, here's the suggested `webpackConfig.node` (for webpack 4):

```js
webpackConfig.node.merge({
  // besides the ones listed above
  buffer: false,
  console: false,
  constants: false,
  crypto: false,
  domain: false,
  global: true,
  http: false,
  https: false,
  os: false,
  path: false,
  process: false,
  punycode: false,
  querystring: false,
  stream: false,
  sys: false,
  timers: false,
  tty: false,
  url: false,
  util: false,
  vm: false,
  zlib: false,
});
```

This basically turns off every module except the [`global` shim](https://github.com/webpack/webpack/blob/master/buildin/global.js), which does get used by third-party packges.

This change breaks dev server a bit however, because currently dev serve requires socksjs, sockers requires eventsource-shim, and eventsource-shim requires http/https. To make things easier, we can actually externalize eventsource-shim because EventSource is widely supported accross browsers. For those that does not, an auto polyfill service, or a graceful downgrade shall suffice. Not every browser needs live reload, right?

**Comment by cyjake** [comment]
不过很可能有一些应用已经用了 node module，这个改动会是 breaking change，需要放到 3.x 里面

**Comment by sorrycc** [comment]
umi@3 计划会升 webpack@5，而 webpack@5 已默认关 node 补丁了。

**Comment by cyjake** [comment]
噢，那没必要在 2.x 改了，我关 issue 咯？

**Comment by sorrycc** [comment]
好的
