### ISSUE TITLE
umi block add 提示 git fetch 命令不存在

### ISSUE THREAD

**Issue by ZeroJsus** [umijs/umi#2613]
## What happens?
通过命令下载区块的时候 提示不存在git fetch 命令

## How To Reproduce
**Steps to reproduce the behavior:**
1.sudo umi block list
2.umi block add DashboardAnalysis

**Expected behavior**
1.正常下载区块

## Context

- **Umi Version**:
v2.7.7
- **Node Version**:
v10.13.0
- **Platform**:
mac

**Comment by ZeroJsus** [comment]
用的是 antdPro 的模版

**Comment by xiaohuoni** [comment]
没有安装git嘛？

**Comment by ZeroJsus** [comment]
安装了的 我用umi 初始化一个 app 项目就可以正常下载 antpro的区块 但是 用antpro的模版 就不行 即使在 目录下 git init 初始化当前目录 也不行

**Comment by xiaohuoni** [comment]
antpro的模版是指create-umi创建的时候选择ant-design-pro，还是说使用https://github.com/ant-design/ant-design-pro

**Comment by ZeroJsus** [comment]
create-umi 创建的时候选择的

**Comment by tomsure** [comment]
我也遇到同样问题
