### ISSUE TITLE
在config.js中设置base: '',最终打包打出的路径还是默认值’/‘

### ISSUE THREAD

**Issue by qingmeizhujiufan** [umijs/umi#2619]
export default {
    base: './',
    publicPath: './',
    history: 'hash',
    ... ...
最终<script src="/umi.js"></script>

**Comment by sorrycc** [comment]
base 不能配 `./`，如果要打出可以在任意路径运行的版本，可以看下 https://umijs.org/zh/guide/deploy.html#%E9%9D%99%E6%80%81%E5%8C%96%E5%90%8E%E8%BE%93%E5%87%BA%E5%88%B0%E4%BB%BB%E6%84%8F%E8%B7%AF%E5%BE%84

**Comment by qingmeizhujiufan** [comment]
谢谢~
