### ISSUE TITLE
如何配置 `html` 标签的 `lang` 属性？

### ISSUE THREAD

**Issue by liuzhaowei55** [umijs/umi#2624]
## What happens?
在官方配置文档中未找到可以配置 `html` 标签 `lang` 属性的选项，
是否只能自定义 `document.ejs` 去实现这个设置？

- **Umi Version**:  v2.7.7
- **Node Version**: v12.4.0

**Comment by sorrycc** [comment]
是的。

**Comment by liuzhaowei55** [comment]
@sorrycc 感谢回复。

**Comment by afc163** [comment]
可以搞一个 umi-plugin-html-props
