### ISSUE TITLE
使用 umi/router 进行页面跳转时，地址栏地址和实际地址不符，导致 subscriptions 中监听失效！

### ISSUE THREAD

**Issue by shangdev** [umijs/umi#2626]
## What happens?

用户前往目标页面，系统判断用户是否登录，未登录时使用 router.replace() 跳转至登录页，完成登录后再使用 router.replace() 返回到目标页面。

如果此时使用 subscriptions 监听页面是否进入目标页面，从而请求对应的数据，发现少数情况下，无法正确监听到，也就导致无法正确的渲染页面。

不知是否有过类似的发生？因为这个不太好复现，所以暂时提供不了复现步骤。

## Context

- **Umi Version**:  ^2.6.17
- **Node Version**: v10.15.3

## 页面显示如下

![image](https://user-images.githubusercontent.com/15621520/59663592-ee1c1e00-91e1-11e9-85c9-244d0e68bbb8.png)

## subscriptions 监听

```
subscriptions: {
    setup({ dispatch, history }) {
      return history.listen(({ pathname, query }) => {
        console.log(pathname);
        if (pathname === '/saleOrder') {
          dispatch({
            type: 'fetch',
            payload: query,
          });
        } else if (pathname === "/saleOrder/detail") {
          dispatch({
            type: 'fetchDetail',
            payload: query,
          });
        }
      });
    },
  },
```

**Comment by sorrycc** [comment]
没遇到过，不用 replace，用 push 呢？

**Comment by shangdev** [comment]
@sorrycc 经测试，用push也有同样的问题。

**Comment by sorrycc** [comment]
> 当登录完成跳转回目标页的时候，是可以执行 alert(1)的
> 如果刷新当前页面，又是可以执行dispatch的

所以，是什么时候不会执行？

**Comment by sorrycc** [comment]
请给明确的复现步骤。

**Comment by Glutton-d** [comment]
目前我也遇到类似的问题。
从A页面跳转到B页面，subscriptions方法已经做出响应，但是真实的url并未更新，依然是A。就会导致subscriptions中监听A页面下的请求再次请求一遍。如下，queryA会先发出请求，然后url更新为B，queryB发出请求：
      history.listen((location) => {
        if (location.pathname.indexOf('/login') === A) {
          dispatch({ type: 'queryA' });
        }
        if (location.pathname.indexOf('/login') === B) {
          dispatch({ type: 'queryB' });
        }
      });
该情况只在项目上线之后出现。在本地或者打包之后都无法复现。
不知是何原因，希望能给出解答，谢谢。
