### ISSUE TITLE
umi dev下目录约定路由跳转正常 build之后路由跳转空白

### ISSUE THREAD

**Issue by yclnycl** [umijs/umi#263]
问题如题 可复现demo https://github.com/yclnycl/umi-demo

打包后尝试使用nginx和php启动server都不行,跳转均空白

点击首页右下方图标跳转

2018-3-27更新
取消了依赖,并且更新到最新版本还是无法显示 页面已经没有报错了,编译好的文件可以复现问题

**Comment by sorrycc** [comment]
自己排查下问题吧，应该是业务组件的写法问题。
