### ISSUE TITLE
配置式路由不会自动刷新

### ISSUE THREAD

**Issue by 1067011734** [umijs/umi#2633]
## What happens?
 从约定式路由改成配置式路由后，修改jsx无在浏览器页面生效，应该是缓存缘故。
改回约定式路由，浏览器页面又会自动刷新了

**Comment by sorrycc** [comment]
配置式和约定式是一样的，约定式也是转成配置形式的路由，不会影响 HMR。给复现后再 reopen。

**Comment by 1067011734** [comment]
我今天排除了一下，发现配置形式的路由component要区分大小写，否则只有启动的时候才生效一次：
path: '/login',   component: './Login' , //ok
path: '/login',   component: './login' , // error
