### ISSUE TITLE
yarn create umi 默认创建的脚手架报错

### ISSUE THREAD

**Issue by jszjgqq** [umijs/umi#2634]
## What happens?
chrome下控制台报错
![TIM截图20190618201412](https://user-images.githubusercontent.com/2629994/59681109-b1621e00-9205-11e9-9a8a-096a580e5847.jpg)

IE不管哪个版本打开页面直接不显示

## How To Reproduce
**Steps to reproduce the behavior:**
复现步骤如下:
$ yarn global add umi
$ umi -v
$ 2.6.17
$ yarn create umi
![TIM截图20190618202030](https://user-images.githubusercontent.com/2629994/59681454-8deba300-9206-11e9-8d60-df3d778be307.jpg)

$ yarn
$ yarn start

然后打开Chrome浏览器, 可以看到控制台报错了.

IE11报下面的错误

![TIM截图20190618202526](https://user-images.githubusercontent.com/2629994/59681763-3ac62000-9207-11e9-9f82-34c70c146c1a.jpg)

## Context

- **Umi Version**: 2.6.17
- **Node Version**:v10.15.1
- **Platform**: windows

## 期望的结果
不要出现报错，其次让IE下能够正常显示页面（目前是空白页）

**Comment by jszjgqq** [comment]
下面是默认生成的package.json 文件内容

`{
  "private": true,
  "scripts": {
    "start": "umi dev",
    "build": "umi build",
    "test": "umi test",
    
    "lint": "eslint --ext .js src mock tests",
    
    
    "precommit": "lint-staged"
  },
  "dependencies": {
    
    "dva": "^2.6.0-beta.4",
    
    
    "antd": "^3.19.2",
    
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "devDependencies": {
    
    "babel-eslint": "^9.0.0",
    "eslint": "^5.4.0",
    "eslint-config-umi": "^1.4.0",
    "eslint-plugin-flowtype": "^2.50.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.11.1",
    "husky": "^0.14.3",
    "lint-staged": "^7.2.2",
    "react-test-renderer": "^16.7.0",
    
    "umi": "^2.7.0",
    "umi-plugin-react": "^1.8.0"
    
    },
  "lint-staged": {
    
    "*.{js,jsx}": ["eslint --fix", "git add"]
  },
  "engines": {
    "node": ">=8.0.0"
  }
}
`

**Comment by jszjgqq** [comment]
下面是默认生成的package.json文件的内容

{
  "private": true,
  "scripts": {
    "start": "umi dev",
    "build": "umi build",
    "test": "umi test",
    
    "lint": "eslint --ext .js src mock tests",
    
    
    "precommit": "lint-staged"
  },
  "dependencies": {
    
    "dva": "^2.6.0-beta.4",
    
    
    "antd": "^3.19.2",
    
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "devDependencies": {
    
    "babel-eslint": "^9.0.0",
    "eslint": "^5.4.0",
    "eslint-config-umi": "^1.4.0",
    "eslint-plugin-flowtype": "^2.50.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.11.1",
    "husky": "^0.14.3",
    "lint-staged": "^7.2.2",
    "react-test-renderer": "^16.7.0",
    
    "umi": "^2.7.0",
    "umi-plugin-react": "^1.8.0"
    
    },
  "lint-staged": {
    
    "*.{js,jsx}": ["eslint --fix", "git add"]
  },
  "engines": {
    "node": ">=8.0.0"
  }
}

**Comment by sorrycc** [comment]
配 [targets](https://umijs.org/config/#targets) 。

**Comment by jszjgqq** [comment]
> 配 [targets](https://umijs.org/config/#targets) 。

感谢大佬回复，试了之后也是一样，依然报错，页面显示空白。

**Comment by jszjgqq** [comment]
以下这一份package.json文件是前一段时间用 yarn create umi 创建的，试了下这个的就没问题，估计是哪个npm包升级之后导致的。

{
    "private": true,
    "scripts": {
        "start": "cross-env PORT=8001 umi dev",
        "build": "umi build",
        "test": "umi test",
        "lint": "eslint --ext .js src",
        "precommit": "lint-staged"
    },
    "dependencies": {
        "dva": "^2.5.0-beta.2",
        "antd": "^3.15.0",
        "react": "^16.7.0",
        "react-dom": "^16.7.0"
    },
    "devDependencies": {
        "babel-eslint": "^9.0.0",
        "cross-env": "^5.2.0",
        "eslint": "^5.4.0",
        "eslint-config-umi": "^1.4.0",
        "eslint-plugin-flowtype": "^2.50.0",
        "eslint-plugin-import": "^2.14.0",
        "eslint-plugin-jsx-a11y": "^5.1.1",
        "eslint-plugin-react": "^7.11.1",
        "husky": "^0.14.3",
        "lint-staged": "^7.2.2",
        "react-test-renderer": "^16.7.0",
        "umi": "^2.6.3",
        "umi-plugin-react": "^1.6.0"
    },
    "lint-staged": {
        "*.{js,jsx}": [
            "eslint --fix",
            "git add"
        ]
    },
    "engines": {
        "node": ">=8.0.0"
    }
}

**Comment by sorrycc** [comment]
不能复现你的问题，下面是我的截图和项目压缩包。

![image](https://user-images.githubusercontent.com/35128/59735177-1447c980-9287-11e9-88de-bb323c39b61d.png)

[sorrycc-NR4IXT.zip](https://github.com/umijs/umi/files/3304314/sorrycc-NR4IXT.zip)

**Comment by jszjgqq** [comment]
> 不能复现你的问题，下面是我的截图和项目压缩包。
> 
> ![image](https://user-images.githubusercontent.com/35128/59735177-1447c980-9287-11e9-88de-bb323c39b61d.png)
> 
> [sorrycc-NR4IXT.zip](https://github.com/umijs/umi/files/3304314/sorrycc-NR4IXT.zip)

看了下您的package.json文件，应该是初始化的时候没有选择dva，请把dva选上，然后重新试下。

**Comment by jszjgqq** [comment]
我把我初始化的项目发上来

[jszjgqq.zip](https://github.com/umijs/umi/files/3308364/jszjgqq.zip)

**Comment by xiaohuoni** [comment]
dva先别升级到最新吧？
```
"dva": "2.5.0-beta.2",
```

**Comment by sorrycc** [comment]
为啥不升？遇到问题解决就好了。

**Comment by jszjgqq** [comment]
> dva先别升级到最新吧？
> 
> ```
> "dva": "2.5.0-beta.2",
> ```

试了下，create的时候，只要选择了dva，IE全系列就挂了。

[dva init error.zip](https://github.com/umijs/umi/files/3308401/dva.init.error.zip)

**Comment by xiaohuoni** [comment]
感觉papakage里面的这些，都不需要好像
```
"dependencies": {
    
    "dva": "^2.6.0-beta.6",
    
    
    "antd": "^3.19.5",
    
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
```

**Comment by jszjgqq** [comment]
> 感觉papakage里面的这些，都不需要好像
> 
> ```
> "dependencies": {
>     
>     "dva": "^2.6.0-beta.6",
>     
>     
>     "antd": "^3.19.5",
>     
>     "react": "^16.8.6",
>     "react-dom": "^16.8.6"
>   },
> ```

umi create的时候可以选择的，只要脚手架提供了选项，不管我怎么选，出了问题不得解决么，我做项目就要用到这些，选上也没啥问题，经过我各种测试，目前发现的问题是只要选dva就会复现。

**Comment by jszjgqq** [comment]
> 为啥不升？遇到问题解决就好了。

找到问题了，强制把dva的版本改成2.4.1就好了。

"dependencies": {
    
    "dva": "^2.4.1",
    
    
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },

**Comment by xiaohuoni** [comment]
感觉这个算是umi-plugin-dva的问题吧？

**Comment by jszjgqq** [comment]
> 感觉这个算是umi-plugin-dva的问题吧？

具体不明，dva改了版本号就解决了。

**Comment by Superman-wc** [comment]
@sorrycc 
看了楼主的第一张图， 这个警告还是
/pages/.umi/router.js 里
```
import _dvaDynamic from 'dva/dynamic'

const Router = require('dva/router').routerRedux.ConnectedRouter;
```
还是这写法问题

改成
```
import {dynamic as dvaDynamic, router} from dva;
```

就可以解决这个问题了

**Comment by lfire** [comment]
这个问题目前进度如何了？

**Comment by lfire** [comment]
@sorrycc 该错误还会影响到 mock 的正常响应，当将 dva 降级到 2.4.1 时，mock才正常返回

**Comment by lucky126** [comment]
我用2.4.1还是不可以

**Comment by xiaohuoni** [comment]
@jszjgqq 最新umi@2.9.1应该没有这个问题了吧？

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/2693 相同问题
