### ISSUE TITLE
Gzip dll's request

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#264]
<img src='https://shipusercontent.com/8d6b2d80a4d14b3b6e0f5a4cfbc48768/Pasted%20Image%201.png' title='Pasted Image 1.png' width=665>

```js
res.set('Content-Encoding', 'gzip');
res.set('Content-Type', 'text/javascript');
```

* express.static
* https://github.com/expressjs/compression
* https://www.npmjs.com/package/shrink-ray-current

**Comment by Nokecy** [comment]
![image](https://user-images.githubusercontent.com/12318131/37978280-464b2024-3218-11e8-9992-f797e4632f45.png)
貌似默认就是gzip压缩过的呀
