### ISSUE TITLE
create-umi创建的app工程报错

### ISSUE THREAD

**Issue by fengyuchenglun** [umijs/umi#2642]
## What happens?

使用create-umi创建app工程能够正常启动 ，页面加载出错;
create-umi：0.13.5
创建app的时候出了没有勾选typescript，勾选了其他所有选项

打开浏览器出错如下：
![image](https://user-images.githubusercontent.com/11927244/59748688-39036780-92ae-11e9-85e7-3197f06dd44a.png)
![image](https://user-images.githubusercontent.com/11927244/59748780-6a7c3300-92ae-11e9-8f78-62e57f6ed245.png)

## 最小可复现仓库

我不知道是不是只有我这样出错，如果需要，我上传到仓库中

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：v10.15.3
- **操作系统**：win10

**Comment by fengyuchenglun** [comment]
dva版本替换成"dva": "^2.4.1",页面正常打开

**Comment by sorrycc** [comment]
给下复现仓库。

**Comment by sorrycc** [comment]
给下复现仓库。

**Comment by fengyuchenglun** [comment]
https://github.com/fengyuchenglun/umi-demo.git 这个

> 给下复现仓库。

**Comment by xiaohuoni** [comment]
> https://github.com/fengyuchenglun/umi-demo.git 这个
> 
> > 给下复现仓库。

demo可正常运行，依旧存在dva新用法的两个警告，可以暂不理会。
