### ISSUE TITLE
devServer一些配置无效

### ISSUE THREAD

**Issue by zhanglingsi1** [umijs/umi#2647]
想把警告和错误直接显示在浏览器页面中而不是控制台，试了以下两种配置无效：
> 
> ```js
> devServer: {
>     overlay: {
>       warnings: true,
>       errors: true
>     }
> }
> ```

> 
> ```js
> chainWebpack(config) {
>     config.devServer
>         .overlay({
>              warnings: true,
>              errors: true,
>         })
>     }
> }
> ```

该如何配置呢？

**Comment by sorrycc** [comment]
overlay 默认就有了，无需配置。

**Comment by 269957022** [comment]
host配置也无效，我们需要使用域名来开发，怎么办
