### ISSUE TITLE
生产环境数据请求baseUrl地址设置问题？

### ISSUE THREAD

**Issue by l2en** [umijs/umi#2648]
开发环境使用proxy进行数据请求正常，生产环境部署（前后端分离）后如何确定数据请求的baseUrl地址？或者说该如何设置fetch的baseurl？    考虑是否是在build的时候将proxy中target地址替换为fetch的请求baseUrl地址？ 查看build源码之后没发现相关操作。。。。   望解答

**Comment by xiaohuoni** [comment]
一般是build之前，自己增加baseurl
