### ISSUE TITLE
不用路由怎么按需加载model?

### ISSUE THREAD

**Issue by cobantou** [umijs/umi#265]
单页面应用，没有用到路由，每个菜单项对应一个page.js，build打包之后发现是打包在一起的，现在想按页面分开，点击对应菜单项的时候才加载对应的page和model，应该怎么做了？

**Comment by zjxpcyc** [comment]
怎么感觉你描述的像多页面应用。

如果你真是单页面，应该有一个初始js, 或者共用 js ，你就在这个 js 里面进行页面的判断，并设置 page 和 model  加载机制。 如果没有这种 js 。你可以写在 layout 这种文件里面去试试。

**Comment by sorrycc** [comment]
用的 umi? 没有路由怎么组织页面的？

**Comment by sorrycc** [comment]
有问题再 reopen 。
