### ISSUE TITLE
addPageWatcher 添加文件，文件改动后页面不生效

### ISSUE THREAD

**Issue by bluexiaowei** [umijs/umi#2650]
## What happens?
在项目文件夹下新建自定义目录 `src/data`，加入文件监听，发现 `webpack` 有反应但是页面中没有效果。

在老版本中是自动监听 `src/*` 下的所有文件。

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

1. 新建自定义文件 `src/data/test.json`

    ```json
    [{"key": "1", "value": "test"}]
    ```

2. 创建插件 `/src/plugin/watcher.ts`

    ```typescript
    import { join } from 'path';
    export default (api: any, opts: any) => {
        const { paths } = api.service;
        console.log('success') // 使用 npm start 的时候成功输出
        api.addPageWatcher(join(paths.absSrcPath, 'data'));
    };
    ```

3. 配置 `.umirc.ts`

    ```typescript
    const config: IConfig = {
        alias: {
            Data: path.resolve(__dirname, 'src/data/'),
        },
         plugins: [['./src/plugin/watcher.ts', {}]],
    };
    ```

4. 创建页面 `src/pages/index.tsx`

    ```tsx
    import React from 'react';
    import testJSON from '@/Data/test.json';

    class Index extends React.Component {
        render(){
            console.log(testJSON);
            return <div>test</div>
        }
    }

    export default Index;
```

首次运行控制台输出 `[{"key": "1", "value": "test"}]`;

修改文件 `src/data/test.json`, `[{"key": "2", "value": "test"}]`

命令行显示 webpack 编译成功, 页面没有反应。刷新页面 `console.log(testJSON)` 数据没有更新

## 相关环境信息

- **Umi 版本**：umi@2.7.7
- **Node 版本**：v10.8.0
- **操作系统**：macOS

**Comment by sorrycc** [comment]
几个注意点，

1. 不用配 alias
2. 用 `@/data/test.json` 去引
3. 不用通过插件 addPageWatcher, webpack 自动会做增量编译的

我搞个例子，试过没问题。

[sorrycc-WNezsu.zip](https://github.com/umijs/umi/files/3328897/sorrycc-WNezsu.zip)
