### ISSUE TITLE
更新 umi v2.8.0  项目无法启动

### ISSUE THREAD

**Issue by lovemegowin** [umijs/umi#2651]
## What happens?

![image](https://user-images.githubusercontent.com/25566683/59817137-47ef2600-9351-11e9-888d-45b383e09dac.png)
初步怀疑是 web/www/src/pages/.umi/umi.js 

> import findRoute from 'C:\Users\yexm\catior\web\www\node_modules\_umi-build-dev@1.10.0@umi-build-dev\lib\findRoute.js';
![image](https://user-images.githubusercontent.com/25566683/59817203-9b617400-9351-11e9-835d-4862daa1eeff.png)

没有对 windows 寻址做适配

## 最小可复现仓库
https://github.com/lovemegowin/catior
## 复现步骤，错误日志以及相关配置

cd web/www 
cnpm install 
npm start 

## 相关环境信息

- **Umi 版本**：v2.8.0
- **Node 版本**：v10.15.0
- **操作系统**：win10

**Comment by ycjcl868** [comment]
统一在这 #2654
