### ISSUE TITLE
formatMessage 提示 id 错误

### ISSUE THREAD

**Issue by chenshuai2144** [umijs/umi#2652]
formatMessage 的 d.ts 并不会扫描区块下的, 
宜鑫看一下别的方案。这个写起来太难受了。

https://github.com/ant-design/ant-design-pro/issues/4515
https://github.com/ant-design/ant-design-pro/issues/4488
https://github.com/ant-design/ant-design-pro/issues/4496

**Comment by ycjcl868** [comment]
临时解决方案：

```js
// 项目里加一个 types.d.ts
declare module 'umi-plugin-react/locale' {
  export default interface MessageDescriptor {
    id: string;
  }
}

```

**Comment by theprimone** [comment]
@ycjcl868  我在根目录配置了还是报错啊

**Comment by ycjcl868** [comment]
这样配置不会报错的吧。

```
// src/typings.d.ts
declare module 'umi-plugin-react/locale' {
  export default interface MessageDescriptor {
    id: string;
  }
}

```

![image](https://user-images.githubusercontent.com/13595509/59971442-cdbbdd00-95ae-11e9-9142-89539b81b6f8.png)

**Comment by theprimone** [comment]
我是这么用的

[![ZCT1YV.md.png](https://s2.ax1x.com/2019/06/23/ZCT1YV.md.png)](https://imgchr.com/i/ZCT1YV)

初始化项目的时候跟 src 同级有一个 **typings.d.ts** ，后来添加 less 模块的时候也是在里边加的，所以这个我也加在了里边，无效。看了你的回复我又在 src 下新建了一个 **typings.d.ts** 还是报错 \_(:3J∠)\_

**Comment by ycjcl868** [comment]
建一个 typings.d.ts，写到一起

**Comment by theprimone** [comment]
```
// src/typings.d.ts
declare module '*.css';
declare module "*.png";
declare module '*.less';


declare module 'umi-plugin-react/locale' {
  export default interface MessageDescriptor {
    id: string;
  }
}
```
这样了，还是不行。

**Comment by ycjcl868** [comment]
使用是怎么导入的

**Comment by theprimone** [comment]
```
import { formatMessage } from 'umi-plugin-locale';
```

试了下把路径改成 `umi-plugin-react/locale` 直接到 typings.d.ts 那个文件了

**Comment by ycjcl868** [comment]
按上面的方式导入吧

**Comment by theprimone** [comment]
现在我就是这样的啊

```jsx
import { formatMessage } from 'umi-plugin-locale';

//...
{orderItems.map(item => (
  <Select.Option key={item} value={item}>{formatMessage({ id: `home.${item.toLowerCase()}` })}</Select.Option>
))}
```

还是报错诶

[![ZCqn3V.md.png](https://s2.ax1x.com/2019/06/23/ZCqn3V.md.png)](https://imgchr.com/i/ZCqn3V)

**Comment by ycjcl868** [comment]
@theprimone  https://github.com/umijs/umi/issues/2652#issuecomment-503836899，我更新了下。

**Comment by theprimone** [comment]
@ycjcl868 😆这样搞了又找不到 formatMessage 了啊

**Comment by ycjcl868** [comment]
重装下模块吧，你这个模块不是最新的吧

**Comment by theprimone** [comment]
```
"umi-plugin-react": "^1.8.0",
```

代码没问题，提示真难搞。我看最新的1.9.1，那我更新试一下。

**Comment by theprimone** [comment]
@ycjcl868 
更新了，很不幸，还是这样，虽然代码正常运行。

···
Module '"umi-plugin-react/locale"' has no exported member 'formatMessage'.
···

总不至于把模块中的其它的定义都复制过来吧。

**Comment by theprimone** [comment]
折腾到现在，终于灵机一动得到一个解决办法了_(:3J∠)_

```ts
import {
  formatMessage,
  MessageDescriptor,  // 引入 interface
} from 'umi-plugin-locale';

// as 语法
<Select.Option key={item} value={item}>{formatMessage({ id: `home.${item.toLowerCase()}` as MessageDescriptor['id'] })}</Select.Option>
```

**Comment by amoibean** [comment]
types.d.ts 加入以下内容解决了我的问题：

```
declare module 'umi-plugin-locale' {
  export type MessageValue = string | number | boolean | Date | null | undefined;
  export interface MessageDescriptor {
    id: string;
    description?: string;
    defaultMessage?: string;
  }
  export function formatMessage(
    messageDescriptor: MessageDescriptor,
    values?: { [key: string]: MessageValue },
  ): string;
}

```

**Comment by chenshuai2144** [comment]
@amoibean 有兴趣给 pro 提个 pr 吗？

**Comment by amoibean** [comment]
@chenshuai2144 这种临时解决方案（workaround）不适合作为pr添加到项目里面，需要设计合理的终极解决方案

**Comment by chenshuai2144** [comment]
@amoibean  很长时间内都解决不了，这个应该是个帮助用户的提示，现在堵塞了用户了。应该先关掉来着

**Comment by amoibean** [comment]
@chenshuai2144 临时解决方案先用着吧，如果有更好的解决办法，我再提pr。
可以先添加到known issues里面去让大家知道

**Comment by xiejun** [comment]
> types.d.ts 加入以下内容解决了我的问题：
> 
> ```
> declare module 'umi-plugin-locale' {
>   export type MessageValue = string | number | boolean | Date | null | undefined;
>   export interface MessageDescriptor {
>     id: string;
>     description?: string;
>     defaultMessage?: string;
>   }
>   export function formatMessage(
>     messageDescriptor: MessageDescriptor,
>     values?: { [key: string]: MessageValue },
>   ): string;
> }
> ```

你这种改法，为何不直接修改umi-plugin-local的index.d.ts，把“id: zh_CN extends string ? zh_CN : string;”修改成“id:string”，不就可以了吗，没必要新建一个types.d.ts吧，你新建的types.d.ts还缺少其他东西的并不完整呀

**Comment by amoibean** [comment]
@chenshuai2144 , @xiejun ,
有个更优雅没有侵入性的做法，主要思想是把项目目录下所有locale文件夹里面文件import进来。具体做法如下（以zh-CN为例）：
1. 在src/locales.zh-CN/目录下创建app.tz文件，这个文件用来导入项目目录下所有的locale文件，以下的代码导入了两个目录下的locale文件，如果有创建新的locale目录，也应该修改这个文件把它import进来
```
import analysis from '@/pages/dashboard/analysis/locales/zh-CN';
import exception from '@/pages/exception/403/locales/zh-CN';

export default {
  ...analysis,
  ...exception,
};

```
2. 修改src/locales/zh-CN.ts文件，把app.tz导入进来：
import component from './zh-CN/component';
import globalHeader from './zh-CN/globalHeader';
import menu from './zh-CN/menu';
import pwa from './zh-CN/pwa';
import settingDrawer from './zh-CN/settingDrawer';
import settings from './zh-CN/settings';
**import app from './zh-CN/app';**
export default {
  'navBar.lang': '语言',
  'layout.user.link.help': '帮助',
  'layout.user.link.privacy': '隐私',
  'layout.user.link.terms': '条款',
  'app.preview.down.block': '下载此页面到本地项目',
  ...globalHeader,
  ...menu,
  ...settingDrawer,
  ...settings,
  ...pwa,
  ...component,
  **...app,**
};

至此，一切正常，我相信这才是正确的做法。
