### ISSUE TITLE
TypeError: Cannot read property 'ssr' of undefined

### ISSUE THREAD

**Issue by superlbr** [umijs/umi#2654]
## What happens?

umi-build-dev版本更新了，但是不兼容旧的umi版本

```
Plugin apply failed: Cannot read property 'ssr' of undefined
×  error     TypeError: Cannot read property 'ssr' of undefined
    at Array.<anonymous> (D:\Develop\antd-admin\node_modules\umi-build-dev\lib\plugins\afwebpack-config\index.js:76:22)
```

**Comment by johnsken-jerry** [comment]
我也遇到这样的问题

**Comment by Francis-FY** [comment]
把umi-plugin-react版本降到1.8.4就可以了
```
"umi": "2.7.7",
"umi-plugin-react": "1.8.4"
```

**Comment by johnsken-jerry** [comment]
> 把umi-plugin-react版本降到1.8.4就可以了
> 
> ```
> "umi": "2.7.7",
> "umi-plugin-react": "1.8.4"
> ```

完美解决问题，谢谢！

**Comment by ycjcl868** [comment]
@superlbr 项目地址发我下，我看下其它问题，如果统一升 umi，是没问题的。

**Comment by superlbr** [comment]
@ycjcl868 https://github.com/zuiidea/antd-admin/tree/develop

**Comment by hanguihe** [comment]
@ycjcl868 我刚刚新建项目也遇到这个问题 

版本号是：
"umi": "^2.7.2",
"umi-plugin-ga": "^1.1.3",
"umi-plugin-pro-block": "^1.3.2",
"umi-plugin-react": "^1.8.2",
"umi-request": "^1.0.7"

**Comment by ycjcl868** [comment]
等合并后发 patch 版

**Comment by lovemegowin** [comment]
@ycjcl868  #2651 大哥 这个issues 好像跟 umi-plugin-react 无关 我按照上面试了 还是会报错

**Comment by zjafei** [comment]
老项目升级2.8.0要做什么适配么 
我是从2.6.17升级的
![微信图片_20190620145241](https://user-images.githubusercontent.com/8189405/59827379-1a16db00-936b-11e9-9217-25b6113a3fc7.png)
```JavaScript
const pathname = location.pathname;
const activeRoute = findRoute(require('@tmp/router').routes, pathname);
if (activeRoute) {
      props = activeRoute.component.getInitialProps ? await activeRoute.component.getInitialProps() : {};
 }
```
activeRoute.component 为undefined

**Comment by skjun** [comment]
解决方法 , 本人有效 
"devDependencies": {
    "umi": "2.7.7",
    "umi-plugin-ga": "^1.1.3",
    "umi-plugin-react": "~1.8.4"
  },
  "resolutions": {
    "umi-plugin-react": "1.8.4"
  },

**Comment by lovemegowin** [comment]
> 解决方法 , 本人有效
> "devDependencies": {
> "umi": "2.7.7",
> "umi-plugin-ga": "^1.1.3",
> "umi-plugin-react": "~1.8.4"
> },
> "resolutions": {
> "umi-plugin-react": "1.8.4"
> },

你这个直接把umi版本锁了 当然没啥问题

**Comment by lovemegowin** [comment]
> 解决方法 , 本人有效
> "devDependencies": {
> "umi": "2.7.7",
> "umi-plugin-ga": "^1.1.3",
> "umi-plugin-react": "~1.8.4"
> },
> "resolutions": {
> "umi-plugin-react": "1.8.4"
> },

你这个直接把umi版本号锁死 当然没啥问题了

**Comment by topwood** [comment]
mark

**Comment by ycjcl868** [comment]
@zjafei 项目仓库在哪，我排查下

**Comment by zjafei** [comment]
@ycjcl868 
[demo.zip](https://github.com/umijs/umi/files/3309209/demo.zip)
上面的是整个项目 谢谢 :)

**Comment by ycjcl868** [comment]
@zjafei  我运行是这个，build 是没问题的。

![image](https://user-images.githubusercontent.com/13595509/59829900-0cfcea80-9371-11e9-9bcf-ceb1ff3a1b8b.png)

**Comment by Well634890** [comment]
刚入职，升级项目，挂了；临时方案先试试

**Comment by tianxiangbing** [comment]
应该是windows上才会有问题，版本要先退回2.7.7了

**Comment by zjafei** [comment]
> @zjafei 我运行是这个，业务代码上的报错，build 是没问题的。
> 
> ![image](https://user-images.githubusercontent.com/13595509/59829900-0cfcea80-9371-11e9-9bcf-ceb1ff3a1b8b.png)

我再呢看看

**Comment by sunplum123** [comment]
我试了 @lovemegowin 的方法。把版本改成了1.8.4，加了resolution，删除了node_modules重新安装，还是不行。

**Comment by peterlxb** [comment]
为什么我的是 mac 上有问题，在windows 跑正常？

**Comment by Gzbox** [comment]
![image](https://user-images.githubusercontent.com/21010051/59830375-15a1f080-9372-11e9-8b61-4a7713cc820f.png)
我也是 刚升级完  挂了
Mac OS : 10.14.5
不知道和系统有没有关系呢

**Comment by tianxiangbing** [comment]
windows也报错。。。。

**Comment by tianxiangbing** [comment]
别升级了，
`    "umi": "2.7.7",
    "umi-plugin-react": "1.8.4"`
指定版本吧

**Comment by sunplum123** [comment]
findRoute 可以临时把.umi/umi.js中findRoute中路径中的 \ 改成 / 可以启动。

**Comment by peterlxb** [comment]
没有升级为什么也报错，搞不明白，我的是 2.2.1 1.4.3

**Comment by wu568431592** [comment]
同样mac 也有问题。npm create umi 现在卡在 Do you want to use typescript? （y/n）后无响应。git clone ant design pro 报错 ssr undefined

**Comment by zjafei** [comment]
我升级到 
umijs 2.8.1 
用 node v10.15.3 就好了
