### ISSUE TITLE
无法通过脚手架 create umi 创建项目

### ISSUE THREAD

**Issue by ggleo08** [umijs/umi#2658]
使用脚手架 create umi 创建项目，当进行到 Do you want to use typescript? （y/n）选择后，不能正常输入，卡在此处无法继续，如下图所示：
![image](https://user-images.githubusercontent.com/32858631/59828730-35371a00-936e-11e9-9ab8-8a83ef8c281f.png)

## 相关环境信息

- **Umi 版本**：2.8（新升级该版本）
- **Node 版本**：v10.7.0
- **操作系统**：win10

**Comment by wu568431592** [comment]
我的也是同样的问题。

- umi版本：2.8.0
- Node 版本：12.4.0
- 操作系统：macOS Mojave 10.14.5

**Comment by killvf** [comment]
同样问题

**Comment by tigerli** [comment]
同样的问题

- umi：2.8.0

- Node：v12.3.1

**Comment by saopao** [comment]
我也是这个问题，我还以为是我的mac坏了呢，重启几次了。。

**Comment by gow1080p** [comment]
同样问题，mac和win都失败，卡在ts和js上，我以为我机器出问题了呢

**Comment by wu568431592** [comment]
我把 node 环境。yarn 都重新安装了一次 无解、

**Comment by TimLiu1** [comment]
我也约到了，严重issue啊

**Comment by TimLiu1** [comment]
官方为啥还不出来解决

**Comment by TimLiu1** [comment]
。。。。

**Comment by ggleo08** [comment]
升级2.8.1 、回退2.7.7 同样问题。 前端小白，束手无策ing... @sorrycc

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/4563

**Comment by huangguozhen** [comment]
ERROR CODE  ERR_WEBPACK_MODULE_NOT_FOUND

**Comment by fundon** [comment]
https://github.com/umijs/create-umi 更新下 https://github.com/SBoudrias/Inquirer.js 试试

**Comment by zhanyunzhi** [comment]
现在是什么情况？

**Comment by zhangWeiZhuang** [comment]
那有其他路径下载源码吗

**Comment by killvf** [comment]
还是卡住，并没有解决。

**Comment by zhanyunzhi** [comment]
好像还是不行啊

**Comment by killvf** [comment]
@ycjcl868

**Comment by ycjcl868** [comment]
再试下，新版可以了。

**Comment by zhanyunzhi** [comment]
我还是卡住的 @killvf 你那边可以么？

**Comment by saopao** [comment]
我又试了两遍还是不行啊

**Comment by linchengzzz** [comment]
@ycjcl868 

https://www.npmjs.com/package/create-umi

版本还是 v0.13.4

**Comment by zhanyunzhi** [comment]
重新试了好几次，还是不行

**Comment by liuchuzhang** [comment]
好像现在 npm 安装最新版本还是 v0.13.4 
但可以这样用修复了的最新的版本
```shell
yarn global add create-umi@0.13.7
create-umi project-name
```

**Comment by killvf** [comment]
> 好像现在 npm 安装最新版本还是 v0.13.4
> 但可以这样用修复了的最新的版本
> 
> ```shell
> yarn global add create-umi@0.13.7
> create-umi project-name
> ```

我在 https://cnpmjs.org/package/create-umi SYNC 了一下  cnpm重新下载可以了

**Comment by saopao** [comment]
ok，已经解决了

**Comment by zhangWeiZhuang** [comment]
![image](https://user-images.githubusercontent.com/44084004/59840689-6ec74f80-9385-11e9-9fd1-f0521ec80cf4.png)
各位，这个又是什么意思哦
