### ISSUE TITLE
拉取最新脚手架create-umi  cnpm下载依赖包后 项目报错

### ISSUE THREAD

**Issue by killvf** [umijs/umi#2661]
## 拉取最新脚手架create-umi  cnpm下载依赖包后 项目报错

没有做任何改动 拉取项目之后直接下载依赖包

![image](https://user-images.githubusercontent.com/23251559/59837761-5d2f7900-9380-11e9-8bd0-b7210528cc3d.png)

![image](https://user-images.githubusercontent.com/23251559/59838034-d7f89400-9380-11e9-88bc-3d2986d3198c.png)

**Comment by ycjcl868** [comment]
重装就可以了。#2657

**Comment by huaibaomengxiang** [comment]
我重新下载了node_modules 还是同样的错误

**Comment by Binkle** [comment]
同楼上

**Comment by ycjcl868** [comment]
试了下 windows，只有 core-js 的问题，路径问题已经修复了。
