### ISSUE TITLE
config.routes配置404

### ISSUE THREAD

**Issue by liminshen** [umijs/umi#2664]
## What happens?
create-umi初始化项目
路由复制一份，将（/）直接复制添加一个子路由（/a）
![image](https://user-images.githubusercontent.com/14226199/59842428-2316a500-9389-11e9-8871-b32f7bf59ba8.png)

![image](https://user-images.githubusercontent.com/14226199/59842468-2f9afd80-9389-11e9-956d-8a3527deb329.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.子路径按要求就可以添加
2.

## Context

- **Umi Version**: 2.7.2
- **Node Version**:10.16.0
- **Platform**:mac

**Comment by ycjcl868** [comment]
配置方式有问题，看下 [umi 路由配置文档](https://umijs.org/zh/guide/router.html#%E9%85%8D%E7%BD%AE%E5%BC%8F%E8%B7%AF%E7%94%B1)。

**Comment by liminshen** [comment]
> 配置方式有问题，看下 [umi 路由配置文档](https://umijs.org/zh/guide/router.html#%E9%85%8D%E7%BD%AE%E5%BC%8F%E8%B7%AF%E7%94%B1)。
我只是复制一份都存在配置错误？
