### ISSUE TITLE
mac开发，ubuntu部署出错，提示大小写问题

### ISSUE THREAD

**Issue by vanishcode** [umijs/umi#2665]
![VvH8C4.png](https://s2.ax1x.com/2019/06/20/VvH8C4.png)

node v10.5
mac10.11
ubuntu16.04
umi2.4.4

**Comment by ycjcl868** [comment]
上面的错误截一下屏，能提供可复现的仓库例子更好，便于排查

**Comment by huaibaomengxiang** [comment]
![图片](https://user-images.githubusercontent.com/29159923/59847832-3714d380-9396-11e9-81db-82bbf945355d.png)

**Comment by ycjcl868** [comment]
#2657, core-js 问题
