### ISSUE TITLE
umi不能监听文件修改，也不能提示代码错误

### ISSUE THREAD

**Issue by exvu** [umijs/umi#2667]
从昨天umi2.8.0的问题开始，我的项目出现修改文件，页面不更新的问题。我尝试将js文件随意输入错误字符，命令行触发编译后并没有提示错误，也没有更新页面。我必须重新umi dev才能查看命令行的错误。我曾怀疑是自己代码动到了，但是我尝试切换最近几日的git历史版本，都是一样的问题。

**Comment by sorrycc** [comment]
更新到最新的 umi 的 umi 插件试试，现在还有问题吗？
