### ISSUE TITLE
antd v4 request.ts 中的errorHandler不能觸發

### ISSUE THREAD

**Issue by hubertmok** [umijs/umi#2668]
參考list中的search table 模組改成自己的應用, 在後端status為200, 能正常發送資料時, table都能正常顯示, 但後端發出status為401或500時, 錯誤並沒有觸發errorHandler, request不能觸發error notification,有嘗試在errorhandler裏面加入console.log, 當觸發errorhandler就會有訊息在console顯示, 但是卻沒有
正常應該會進入error handler執行以下代碼:
notification.error({
message: 请求错误 ${status}: ${url},
description: errortext,
});

**Comment by sorrycc** [comment]
给下复现步骤。

**Comment by hubertmok** [comment]
复现步骤:
我這邊是直接連接到後端測試, 不是用mock, 利用search table模組, 後端直接向前端發出status 401即可(在antd v2是沒有問題), 該前端頁面一直呈現loading狀態, error沒有處理

**Comment by sorrycc** [comment]
@chenshuai2144 有空看下。

**Comment by clock157** [comment]
能贴下 request.ts 的代码吗？我下载了最新 antd-pro 测试没有问题

**Comment by hubertmok** [comment]
/**
 * request 网络请求工具
 * 更详细的 api 文档: https://github.com/umijs/umi-request
 */
import { extend } from 'umi-request';
import { notification } from 'antd';
import router from 'umi/router';

interface ResponseError<D = any> extends Error {
  name: string;
  data: D;
  response: Response;
}

const codeMessage = {
  200: 'The server successfully returned the requested data.',
  201: 'Create or modify data successfully.',
  202: 'One request has entered the backend queue (asynchronous task).',
  204: 'Delete data successfully.',
  400: 'The request has an error, server did not create or modify data',
  401: 'User does not have permission (token, username, password is incorrect).',
  403: 'The user is authorized but access denied.',
  404: 'The request is made for a record that does not exist and the server does not operate.',
  406: 'The format of the request is not available.',
  410: 'The requested resource is permanently deleted and will not be retrieved.',
  422: 'A validation error occurred when creating an object.',
  500: 'An error occurred on the server. Please check the server.',
  502: 'Gateway error.',
  503: 'The service is unavailable and the server is temporarily overloaded or maintained.',
  504: 'Gateway timed out.',
};

/**
 * 异常处理程序
 */
const errorHandler = (error: ResponseError) => {
  const { response = {} as Response } = error;
  const errortext = codeMessage[response.status] || response.statusText;
  const { status, url } = response;

  if (status !== 401) {
    notification.error({
      message: `Request error ${status}: ${url}`,
      description: errortext,
    });
  }
  if (status === 401) {
    // @HACK
    /* eslint-disable no-underscore-dangle */
    window.g_app._store.dispatch({
      type: 'login/logout',
    });
    return;
  }
  // environment should not be used
  if (status === 403) {
    router.push('/exception/403');
    return;
  }
  if (status <= 504 && status >= 500) {
    router.push('/exception/500');
    return;
  }
  if (status >= 404 && status < 422) {
    router.push('/exception/404');
  }
};

/**
 * 配置request请求时的默认参数
 */
const request = extend({
  errorHandler, // 默认错误处理
  credentials: 'include', // 默认请求是否带上cookie
});

export default request;

**Comment by hubertmok** [comment]
@clock157 我這邊只有在用search table 模組有錯誤

**Comment by clock157** [comment]
request.ts 看起来没有问题。另外什么是 search table 模组，有可重现的访问地址或者 repo 吗？

**Comment by hubertmok** [comment]
我是以下路徑的模組才出現錯誤
![image](https://user-images.githubusercontent.com/5517502/60778482-b3b2fa80-a169-11e9-8e35-b0df3203b900.png)

**Comment by hubertmok** [comment]
剛剛做了一個可以用MOCK復現的情況, 將以下代碼替換至antd4 
src->pages->list->table-list->_mock.ts即可

import { parse } from 'url';
import { TableListItem, TableListParams } from './data';
// mock tableListDataSource
let tableListDataSource: TableListItem[] = [];

for (let i = 0; i < 8; i += 1) {
  tableListDataSource.push({
    key: i,
    disabled: i % 6 === 0,
    href: 'https://ant.design',
    avatar: [
      'https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png',
      'https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png',
    ][i % 2],
    name: `TradeCode ${i}`,
    title: `一个任务名称 ${i}`,
    owner: '曲丽丽',
    desc: '这是一段描述',
    callNo: Math.floor(Math.random() * 1000),
    status: Math.floor(Math.random() * 10) % 4,
    updatedAt: new Date(`2017-07-${Math.floor(i / 2) + 1}`),
    createdAt: new Date(`2017-07-${Math.floor(i / 2) + 1}`),
    progress: Math.ceil(Math.random() * 100),
  });
}

function getRule(
  req: { url: any },
  res: {
    json: (
      arg0: {
        list: TableListItem[];
        pagination: { total: number; pageSize: number; current: number };
      },
    ) => void;
  },
  u: any,
) {
  let url = u;
  if (!url || Object.prototype.toString.call(url) !== '[object String]') {
    url = req.url; // eslint-disable-line
  }

  const params = (parse(url, true).query as unknown) as TableListParams;

  let dataSource = tableListDataSource;

  if (params.sorter) {
    const s = params.sorter.split('_');
    dataSource = dataSource.sort((prev, next) => {
      if (s[1] === 'descend') {
        return next[s[0]] - prev[s[0]];
      }
      return prev[s[0]] - next[s[0]];
    });
  }

  if (params.status) {
    const status = params.status.split(',');
    let filterDataSource: TableListItem[] = [];
    status.forEach((s: string) => {
      filterDataSource = filterDataSource.concat(
        dataSource.filter(item => {
          if (parseInt(item.status + '', 10) === parseInt(s.split('')[0], 10)) {
            return true;
          }
          return false;
        }),
      );
    });
    dataSource = filterDataSource;
  }

  if (params.name) {
    dataSource = dataSource.filter(data => data.name.indexOf(params.name) > -1);
  }

  let pageSize: number = 10;
  if (params.pageSize) {
    pageSize = parseInt(params.pageSize + '', 0);
  }

  const result = {
    list: dataSource,
    pagination: {
      total: dataSource.length,
      pageSize,
      current: parseInt(`${params.currentPage}`, 10) || 1,
    },
  };

  return res.json(result);
}

function postRule(
  req: { url: any; body: any },
  res: { json: (arg0: { list: TableListItem[]; pagination: { total: number } }) => void },
  u: any,
  b: { body: any },
) {
  let url = u;
  if (!url || Object.prototype.toString.call(url) !== '[object String]') {
    url = req.url; // eslint-disable-line
  }

  const body = (b && b.body) || req.body;
  const { method, name, desc, key } = body;

  switch (method) {
    /* eslint no-case-declarations:0 */
    case 'delete':
      tableListDataSource = tableListDataSource.filter(item => key.indexOf(item.key) === -1);
      break;
    case 'post':
      const i = Math.ceil(Math.random() * 10000);
      tableListDataSource.unshift({
        key: i,
        href: 'https://ant.design',
        avatar: [
          'https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png',
          'https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png',
        ][i % 2],
        name: `TradeCode ${i}`,
        title: `一个任务名称 ${i}`,
        owner: '曲丽丽',
        desc,
        callNo: Math.floor(Math.random() * 1000),
        status: Math.floor(Math.random() * 10) % 2,
        updatedAt: new Date(),
        createdAt: new Date(),
        progress: Math.ceil(Math.random() * 100),
      });
      break;
    case 'update':
      tableListDataSource = tableListDataSource.map(item => {
        if (item.key === key) {
          Object.assign(item, { desc, name });
          return item;
        }
        return item;
      });
      break;
    default:
      break;
  }

  const result = {
    list: tableListDataSource,
    pagination: {
      total: tableListDataSource.length,
    },
  };

  return res.json(result);
}

export default {
  'GET /api/rule': (req, res) => {
    res.status(401).send({
      list: tableListDataSource,
      pagination: {
        total: tableListDataSource.length,
        pageSize: 50,
        current: 1,
      },
    });
  },
  'POST /api/rule': postRule,
};

**Comment by sorrycc** [comment]
提供明确的复现步骤再 reopen 吧。
