### ISSUE TITLE
We should not have multiple dynamic routes under a directory

### ISSUE THREAD

**Issue by wbget** [umijs/umi#2669]
## What happens?

ERR: We should not have multiple dynamic routes under a directory

## Mini Showcase Repository(REQUIRED)
I wrote like this.
![image](https://user-images.githubusercontent.com/12776391/59834440-95cc5400-937a-11e9-8e7a-8addff775d4b.png)

**Comment by sorrycc** [comment]
有多个动态的时候匹配哪个呢？

**Comment by wbget** [comment]
这种路由类似于这样
/user/:uid/trade
/user/:uid/info
如果这样不符合规则的话，那就不这样做了。

**Comment by wbget** [comment]
@sorrycc
