### ISSUE TITLE
通过脚手架创建项目，关于require("dva/router")报错

### ISSUE THREAD

**Issue by saopao** [umijs/umi#2672]
![image](https://user-images.githubusercontent.com/26051001/59911333-39cf0180-9446-11e9-9450-566193b746d3.png)
控制台提示让我将【router.js】文件下的【require("dva/router")】换成【require("dva").router】,因为在下一个版本会把【require("dva/router")】的方式删除。我尝试按照提示换掉，但是提示了新的错误。如图
![image](https://user-images.githubusercontent.com/26051001/59911605-dd201680-9446-11e9-8a59-e56c8ba94223.png)
于是我尝试在控制台打印看看两个的区别，我分别打印了【require('dva/router')】和【require("dva").router】,两个都打印出【Module】这个对象，里面的值也是一样的。不过打印【require("dva").router.routerRedux.ConnectedRouter】的值是undefined。
由于本人的新手，希望各位老师指点一下，谢谢

**Comment by LeoHuiyi** [comment]
![image](https://user-images.githubusercontent.com/8001457/59912855-89fb9300-9449-11e9-8e22-1901e6885642.png)
![image](https://user-images.githubusercontent.com/8001457/59913155-36d61000-944a-11e9-820b-5de64ccaf605.png)


应该是dva库的警告。能关闭这个警告吗？或者有个配置关闭。
![image](https://user-images.githubusercontent.com/8001457/59913173-40f80e80-944a-11e9-8e07-8cec7c7ac1bc.png)
低版本chrome （43） 还报错

**Comment by ycjcl868** [comment]
提供可复现的例子

**Comment by saopao** [comment]
> 提供可复现的例子

我是按照Umi官网的教程【通过脚手架创建项目】搭建的项目，使用【yarn create umi】命令创建Umi，然后选择【app】（官网写的是：选择 project），然后选择ts、antd以及dva，最后启动项目，没有添加或修改其他的代码，【yarn start】运行出来就提示的上面截图的错误。
随后我使用【umi build】构建项目，然后用【serve ./dist】做本地验证，最后访问本地验证这个地址没有报任何错误。
综上所诉，由于我并没有做其他任何操作，所以我并不能提供可复现的例子。不知道老师怎么看待这个问题。

**Comment by sorrycc** [comment]
routerRedux 用这样获取，

```diff
- require("dva").router.routerRedux.ConnectedRouter
+ require("dva").routerRedux.ConnectedRouter
```

dva@2.6 beta 全部走 esm，推荐用 `require('dva')`，而不是 `require('dva/router')`，所以给了警告。

**Comment by saopao** [comment]
谢谢老师指点




------------------ 原始邮件 ------------------
发件人: "chencheng (云谦)"<notifications@github.com>;
发送时间: 2019年6月26日(星期三) 下午3:40
收件人: "umijs/umi"<umi@noreply.github.com>;
抄送: "郑晶"<1056021017@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [umijs/umi] 通过脚手架创建项目，关于require("dva/router")报错 (#2672)




Closed #2672.

**Comment by Superman-wc** [comment]
@sorrycc 
自己代码使用 import {router} from dva 就可以
但是 /pages/.umi/router.js 是umi自动生成的，

import _dvaDynamic from 'dva/dynamic'    // 第6行

const Router = require('dva/router').routerRedux.ConnectedRouter;    // 第8行

只要改写成 
import {dynamic, router} form dva 就好啊

**Comment by saopao** [comment]
> @sorrycc
> 自己代码使用 import {router} from dva 就可以
> 但是 /pages/.umi/router.js 是umi自动生成的，
> 
> import _dvaDynamic from 'dva/dynamic' // 第6行
> 
> const Router = require('dva/router').routerRedux.ConnectedRouter; // 第8行
> 
> 只要改写成
> import {dynamic, router} form dva 就好啊

谢谢指点
