### ISSUE TITLE
npm run bulid 出错

### ISSUE THREAD

**Issue by yangjie21** [umijs/umi#2673]
![image](https://user-images.githubusercontent.com/19204745/59913440-b8c63900-944a-11e9-8073-cdd75b0fac92.png)

uim 2.83

**Comment by ycjcl868** [comment]
重装下模块

**Comment by yangjie21** [comment]
我都重装  好几次了 都不行

**Comment by ycjcl868** [comment]
提供可复现的最简例子，我来排查下

**Comment by yangjie21** [comment]
npm run dulid 
![image](https://user-images.githubusercontent.com/19204745/59916561-190ca900-9452-11e9-89c2-04b43f421bb2.png)

npm start

![image](https://user-images.githubusercontent.com/19204745/59916575-26c22e80-9452-11e9-8d85-471b40cc1af4.png)

**Comment by yangjie21** [comment]
我也是服了

**Comment by ycjcl868** [comment]
我试了下，是 ok 的。看下是不是有依赖未安装：`keyboardjs`、`rebound`

```jsx
import useKeyboardJs from 'react-use/lib/useKeyboardJs';
import React from 'react';

export default (): React.ReactNode => {
  const [isPressed] = useKeyboardJs('a + b');
  return (
    <p style={{ textAlign: 'center' }}>
        {isPressed ? 'yyyyyyyy' : 'nnnnnnnn'}
      Want to add more pages? Please refer to{' '}
      <a href="https://pro.ant.design/docs/block-cn" target="_blank" rel="noopener noreferrer">
        use block
      </a>
      。
    </p>
  )
};

```

![image](https://user-images.githubusercontent.com/13595509/59917108-a270ab00-9453-11e9-9706-6fbcc2dc8549.png)

**Comment by yangjie21** [comment]
好的  我试试
