### ISSUE TITLE
create umi 无法初始化 ant-design-pro 脚手架

### ISSUE THREAD

**Issue by garygchai** [umijs/umi#2674]
## What happens?

create umi 无法初始化 ant-design-pro 脚手架：

![image](https://user-images.githubusercontent.com/8703655/59914278-a1884b00-944c-11e9-8b56-2c292c7f57f4.png)

如图，箭头无法选择，已经卡死。

## 复现步骤，错误日志以及相关配置

第一步：执行 npm create umi
第二步：选择 ant-design-pro
第三步：选择 Typescript，到这里就挂了，无法选择。

## 相关环境信息

- **Umi 版本**：2.8.0
- **Node 版本**：v12.1.0
- **操作系统**：mac os 10.14.5

**Comment by afc163** [comment]
`npx create umi`

**Comment by afc163** [comment]
试试先卸载掉全局的 umi：

```
npm uninstall create-umi -g
```

然后再 `npm create umi`。

**Comment by garygchai** [comment]
> 试试先卸载掉全局的 umi：
> 
> ```
> npm uninstall create-umi -g
> ```
> 
> 然后再 `npm create umi`。

卸载之后正常了，谢谢！
