### ISSUE TITLE
Invalid key initialProps from plugin

### ISSUE THREAD

**Issue by EliazTray** [umijs/umi#2676]
## Invalid key initialProps from plugin.

![image](https://user-images.githubusercontent.com/16015431/59921299-d520a080-945f-11e9-8ed9-1e857083b1f9.png)

## How To Reproduce
**Steps to reproduce the behavior:**
1. npm start

**Expected behavior**
no errors report.

## Context

- **Umi Version**: 2.7.5, 2.7.7, 2.8.3 both.
- **Node Version**: 10.14.1
- **Platform**: macOs

**Comment by GGwujun** [comment]
initialProps?

**Comment by dengfuping** [comment]
@EliazTray 插件配置项的 `key` 不合法，应该没有哪个插件有 `initialProps` 配置。

**Comment by feibi** [comment]
这里有用到 `initialProps`
https://github.com/umijs/umi/blob/ecf4af74f6bfbb1c388296424d69143d75779fbf/packages/umi-plugin-dva/src/runtime.js#L8

**Comment by EliazTray** [comment]
我发现，umi的版本和umi中packages的版本采用的是lerna的independent的模式，所以应该不是umi这个库版本的问题。

今天重新`umi dev`，`.umi` 文件夹下 `umi.js` 部分截图如下。
![image](https://user-images.githubusercontent.com/16015431/59986764-b5a99380-966a-11e9-808d-3eccb6951ad6.png)
上周五编译的时候，这里是**没有 `initialProps`** 这个key的。

结合 [validKeys](https://github.com/umijs/umi/blob/2fdce3e147aeec8432011e88addf4af6fc71a845/packages/umi-build-dev/src/FilesGenerator.js#L177) 的描述，和 [入口模版](https://github.com/umijs/umi/blob/fda1ad295dfdfaaadff2178cca42ceeed940fff6/packages/umi-build-dev/template/entry.js.tpl#L17) 的定义。

理应是 `validKeys` 会包括 `initialProps`。

目前(此时此刻)，这个问题不会复现，所以先 close。

**Comment by ZhangHaiyangYang** [comment]
怎么解决啊？

**Comment by fishenal** [comment]
我这边 通过 npm update 到 umi-plugin-react ^1.9.14确实会有这个问题，
还原成umi-plugin-react ^1.8.4即可解决，
应该是最新版本引入的问题
