### ISSUE TITLE
Module parse failed: Unexpected token in ./src/pages/.umi/router.js

### ISSUE THREAD

**Issue by sridummy** [umijs/umi#2678]
<img width="964" alt="Screenshot 2019-06-22 at 12 55 14 AM" src="https://user-images.githubusercontent.com/30023455/59946549-73c0f780-9488-11e9-8454-8444456730d3.png">

tried upgrading umi, umi-plugin-react packages. no luck!😞

**Comment by sridummy** [comment]
roll back to umi 2.7.2 and umi-plugin-react 1.8.2 issue fixed.

**Comment by Hyg900928** [comment]
![image](https://user-images.githubusercontent.com/19190553/60077624-f681d500-975c-11e9-8597-26892716c49f.png)
我也遇到这个问题了, 请问怎么解决的啊 我的版本如下
![image](https://user-images.githubusercontent.com/19190553/60077684-1d400b80-975d-11e9-979e-0add301d2a61.png)

**Comment by Hyg900928** [comment]
@sorrycc 这是什么问题呢, 劳烦提供下思路了

**Comment by IsaacHo** [comment]
我也遇到，版本升级之后，建议先退回并锁版
 "umi": "2.7.7",
 "umi-plugin-react": "1.8.4"

**Comment by limzb** [comment]
![picturemessage_5v2j0tle bzx](https://user-images.githubusercontent.com/33625320/60159644-4bd5e900-9826-11e9-8b7f-c00d617718da.png)

使用了最新版本之后，我这边也遇到相同的问题

**Context**
umi: v2.8.5
node: v10.15.3
platform; Windows OS
