### ISSUE TITLE
example with-dva 的几个问题

### ISSUE THREAD

**Issue by ppxu** [umijs/umi#268]
with-dva 这个 example，其中 search 这个 model 没有注册，所以切换到 /list/search 会报错。
另外，如果在 index/index.js 中 connect list 里面的 a，b 两个 model 并显示出来，dev 环境中可以正常显示出来，但是 prd 环境里就拿不到这两个值，访问过一次 /list 路由后才能显示，好像是跟 model 的动态加载有关，可是我在 webpackrc 里加了 disableDynamicImport 也不行，这种跨路由获取 model 的方式有什么解决办法吗

**Comment by sorrycc** [comment]
> with-dva 这个 example，其中 search 这个 model 没有注册，所以切换到 /list/search 会报错。

试了下，不能重现。umi-plugin-dva 是最新的吗？

> 另外，如果在 index/index.js 中 connect list 里面的 a，b 两个 model 并显示出来，dev 环境中可以正常显示出来，但是 prd 环境里就拿不到这两个值，访问过一次 /list 路由后才能显示，好像是跟 model 的动态加载有关，可是我在 webpackrc 里加了 

index/index.js 不应该 connect list 里的 model 吧，model 只会从自身开始往上找，如果需要公用，就放在 pages 外的 models 里。

> disableDynamicImport 也不行，这种跨路由获取 model 的方式有什么解决办法吗

还不支持这个配置，可以在 #262 跟进。

**Comment by ppxu** [comment]
第一个问题，umi-plugin-dva 升级到 0.4.0 之后就正常了，example 里的依赖是 0.3.0 的
第二个问题，不一定是 index，就是 page A 要访问 page B 的 model，但是好像必须要访问过 page B 的路由后才能拿到 B 的 model，不过这个问题只在 prd 环境下出现，dev 是正常的

**Comment by sorrycc** [comment]
pageA 和 pageB 的 model 不是公用的，要公用就放全局。
