### ISSUE TITLE
莫名其妙在router中出现了__IS_BROWSER的校验 请问这个是什么 

### ISSUE THREAD

**Issue by zsz91** [umijs/umi#2684]
umi.js:1 ReferenceError: __IS_BROWSER is not defined
    at Object.i4x8 (umi.js:1)
    at n (umi.js:1)
    at i (umi.js:1)
    at umi.js:1
    at umi.js:1

**Comment by ycjcl868** [comment]
提供下可复现的最小仓库，我用 windows / mac 试了下，没这个问题

**Comment by allenZhengchangjin** [comment]
> 提供下可复现的最小仓库，我用 windows / mac 试了下，没这个问题

本地是没问题的，部署到服务器上会有问题

**Comment by zsz91** [comment]
> > 提供下可复现的最小仓库，我用 windows / mac 试了下，没这个问题
> 
> 本地是没问题的，部署到服务器上会有问题

对的 就是这样. 不知道哪里配置出了问题

**Comment by zsz91** [comment]
> 提供下可复现的最小仓库，我用 windows / mac 试了下，没这个问题



> 提供下可复现的最小仓库，我用 windows / mac 试了下，没这个问题

https://github.com/zsz91/zyd-jy.git
最后生成的/src/pages/.umi/router.js 中会出现 __IS_BROWSER

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/60146990-3cdb4080-97fe-11e9-96f8-6028ae597eab.png)

![image](https://user-images.githubusercontent.com/13595509/60147001-482e6c00-97fe-11e9-9f62-cb351ae67c2e.png)


没问题的，重装下依赖

**Comment by ycjcl868** [comment]
先 Close 了，有问题再 reopen

**Comment by lubanbaba** [comment]
我也碰到了这个问题，哪位大神告知下如何解决的？
在Docker里运行起来的，常规配置，重装依赖也没用......@ycjcl868 @zsz91
