### ISSUE TITLE
umi router 跳转时，触发多次pathname

### ISSUE THREAD

**Issue by srrrr** [umijs/umi#2688]
代码：
![image](https://user-images.githubusercontent.com/5070841/60015312-c03d4a80-96b5-11e9-8171-42165d3d43a6.png)

开始刷新页面，这个Warning以前一直是没有出现的
**Warning: Please use `require("dva").router` instead of `require("dva/router")`.**
按图操作：
![image](https://user-images.githubusercontent.com/5070841/60015209-79e7eb80-96b5-11e9-9e8a-168e542e002a.png)

点击后，pathname打印多次，即触发匹配多次history.listen的pathname，同时初始化接口也多次调用：
![image](https://user-images.githubusercontent.com/5070841/60015373-e8c54480-96b5-11e9-866c-5c5ab0a45908.png)
Network:
![image](https://user-images.githubusercontent.com/5070841/60015513-46599100-96b6-11e9-838e-2d07e39dff92.png)

并且，页面也没法通过后退依次返回到之前的页面，一直在这两个页面切换。。。

以前用一直都没这个问题的，好像是前天重新装了新的依赖包后，变成这样了。

## 相关环境信息

- **Umi 版本**："^2.0.0"/"^2.8.3"
- **Node 版本**：10.13.0
- **操作系统**：win10

**Comment by feibi** [comment]
是有这个问题，暂时可回退版本 
```
   "umi": "2.7.7",
   "umi-plugin-react": "1.8.4",
```

**Comment by srrrr** [comment]
嗯，好了

**Comment by xoptimal** [comment]
@feibi  我更新了仍然存在这个问题

**Comment by srrrr** [comment]
@xoptimal 你package里umi设的是什么版本？

**Comment by xoptimal** [comment]
版本: 
```
 "umi": "^2.2.9",
 "umi-plugin-react": "^1.2.4"
```
我已经把所有的dva/router 引用改成 umi/router 了, 但是有个很奇怪的问题,  我的history, 是browser, 
它跳转的时候, 返回会无限循环返回上一个页面, 跟当前页面 相互切换, 一直返回不到顶层,

举个例子,  A -> B ,  B -> A ,  按道理这个时候再 return 就关闭了 webview了,  但是 A retrurn 居然到了B , B return 又到了 A,  一直按返回, 都是如此, (android 下的物理返回键) ... 

@srrrr

**Comment by srrrr** [comment]
@xoptimal 用这个
` "umi": "2.7.7",
"umi-plugin-react": "1.8.4",`
