### ISSUE TITLE
window 运行uni项目，界面提示报错

### ISSUE THREAD

**Issue by zichen-cici** [umijs/umi#2689]
## What happens?
window 运行uni项目，界面提示报错。（mac系统可以正常运行和显示界面，windows运行出错）

![image](https://user-images.githubusercontent.com/13568082/60063507-c112c280-972f-11e9-97a9-5f736ea15044.png)

## 最小可复现仓库
使用的umi生成的模板项目
> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
![image](https://user-images.githubusercontent.com/13568082/60063566-f7504200-972f-11e9-8c76-c02cae8805dd.png)

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by ycjcl868** [comment]
重装下依赖，再试下。

**Comment by zichen-cici** [comment]
试过了，不可以

**Comment by sorrycc** [comment]
@chenshuai2144 能复现吗？

**Comment by chenshuai2144** [comment]
不行的。pro 和新建的项目都不行
