### ISSUE TITLE
ssr模式下配置dll，打包以后会报umi is not defined

### ISSUE THREAD

**Issue by williamnie** [umijs/umi#2691]
## 问题
在开启ssr模式时，配置dll，会出现问题，打包以后会找不到umi。
##报错信息
2019-06-25 11:16:22,199 ERROR 19786 [-/127.0.0.1/-/169ms GET /] nodejs.ReferenceError: umi is not defined
##复现步骤
在ssr-egg的demo上即可复现，
在config.ts中加入
` dll: {
         include: ['dva', 'dva/router', 'dva/saga', 'dva/fetch'],
         exclude: ['@babel/runtime', 'netlify-lambda'],
       },`
启动项目即可。

**Comment by ycjcl868** [comment]
`umi.server.js` 不需要加 dll。
