### ISSUE TITLE
[Feature Request] umi-request support abort

### ISSUE THREAD

**Issue by afc163** [umijs/umi#2692]
https://github.com/github/fetch#aborting-requests

**Comment by clock157** [comment]
稍后支持一下

**Comment by iceshu** [comment]
请问什么时候支持下

**Comment by afc163** [comment]
@chenjsh36 有进展不

**Comment by chenjsh36** [comment]
目前 canceltoken 只是 promise 的中断，后续可以通过这个支持请求层的中断，目前看来除了对 responseType 为 blob 的情况 abort 会有问题外，其他兼容性上应该可以。

**Comment by chenjsh36** [comment]
umi-request 1.3.0 版本已提供 [AbortController](https://github.com/umijs/umi-request/blob/master/README_zh-CN.md#%E9%80%9A%E8%BF%87-abortcontroller-%E6%9D%A5%E4%B8%AD%E6%AD%A2%E8%AF%B7%E6%B1%82) 支持中止请求
