### ISSUE TITLE
antd css 样式丢失

### ISSUE THREAD

**Issue by Tomny2016** [umijs/umi#2696]
## What happens?
使用umi新建一个项目；选择antd，dva，在.umirc已经确保antd开启；
但是开启服务之后，引入button;发现button的css样式丢失

```
import React from 'react';
import styles from './index.css';
import { Button } from 'antd';
const BasicLayout: React.FC = props => {
  return (
    <div className={styles.normal}>
       <Button>Delete</Button>
      <h1 className={styles.title}>Yay! Welcome to umi!</h1>
      {props.children}
    </div>
  );
};

export default BasicLayout;
```

## Context

- **Umi 2.7.0**:
- **Node 10.16.0**:
- **windows**:

**Comment by imhele** [comment]
检查一下 tsconfig 的 module 是否为 `"esnext"` 或者 `"esxxxx"`

**Comment by Tomny2016** [comment]
是的，是为“esnext”,

**Comment by ycjcl868** [comment]
`umi-plugin-react` 配置 `antd: true` 了吗？

**Comment by Tomny2016** [comment]
```
    // ref: https://umijs.org/plugin/umi-plugin-react.html
    ['umi-plugin-react', {
      antd: true,
      dva: true,
      dynamicImport: false,
      title: 'myapp',
      dll: false,
      
      routes: {
        exclude: [
          /models\//,
          /services\//,
          /model\.(t|j)sx?$/,
          /service\.(t|j)sx?$/,
          /components\//,
        ],
      },
    }],
  ],
```
已经是`true`了

**Comment by Tomny2016** [comment]
`Warning: Please use `require("dva").router` instead of `require("dva/router")`. Support for the latter will be removed in the next major release.`
按照提示修改之后，报错
`router.js:8 Uncaught (in promise) TypeError: Cannot read property 'ConnectedRouter' of undefined`

**Comment by sorrycc** [comment]
是因为开了 dll 吧，

1. 关 dll，是不是可以？
2. 升级到最新的 umi，昨天发布的版本已经修复 dll 里 css 的冲突问题

**Comment by rule78** [comment]
解决了吗？我之前 出现过这问题，打包时能找到es模块，但是没有引到项目去

**Comment by muuma** [comment]
> 是因为开了 dll 吧，
> 
> 1. 关 dll，是不是可以？
> 2. 升级到最新的 umi，昨天发布的版本已经修复 dll 里 css 的冲突问题

请问具体是哪个版本呢？

**Comment by zhangxinmiao-study** [comment]
['umi-plugin-react', {
      antd: true,
      dva: true,
      dynamicImport: false,
      title: 'myapp',
      dll: false,
      
      routes: {
        exclude: [
          /models\//,
          /services\//,
          /model\.(t|j)sx?$/,
          /service\.(t|j)sx?$/,
          /components\//,
        ],
      },
    }],
  ],

请问这个配置是在 .umirc文件中更改吗

**Comment by noxue** [comment]
import 'antd/dist/antd.css';

这样就可以了
