### ISSUE TITLE
`.env.local` 的环境变量无法覆盖 `.env`

### ISSUE THREAD

**Issue by fengxinming** [umijs/umi#2699]
## What happens?
本地环境变量无法覆盖配置的环境变量

## Mini Showcase Repository(REQUIRED)

直接使用umi脚手架创建即可

## How To Reproduce
**Steps to reproduce the behavior:**
1. 配置.env文件 PORT=8080
2. 配置.env.local文件 PORT=3000

**Expected behavior**
1. 服务的监听端口为3000
2.

## Context
调试源码发现问题所在 `umi/src/buildDevOpts.js`

```
function loadDotEnv() {
  const baseEnvPath = join(process.cwd(), '.env');
  const localEnvPath = `${baseEnvPath}.local`;

  const loadEnv = envPath => {
    if (existsSync(envPath)) {
      const parsed = parse(readFileSync(envPath, 'utf-8'));
      Object.keys(parsed).forEach(key => {
        // eslint-disable-next-line no-prototype-builtins
        if (!process.env.hasOwnProperty(key)) {
          process.env[key] = parsed[key];
        }
      });
    }
  };

  loadEnv(baseEnvPath);
  loadEnv(localEnvPath);
```
原因：
```
// 这样判断达不到文档介绍的覆盖效果
if (!process.env.hasOwnProperty(key)) {
    process.env[key] = parsed[key];
}
```

**Comment by fengxinming** [comment]
@sorrycc 请问基于哪个分支上改？

**Comment by sorrycc** [comment]
@fengxinming master 分支。

**Comment by farzer** [comment]
@fengxinming 可否这样？https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables

**Comment by saplf** [comment]
我看 master 分支的代码没变，请问现在关闭是不改了吗？ @sorrycc

**Comment by zybn2004** [comment]
@sorrycc @saplf 我看master源码也觉得这个问题.env.local无法覆盖.env的问题依然存在，大概找了下，应该有2处地方涉及到了：
1.umijs/umi/packages/umi/src/buildDevOpts.js
2.umijs/umi/packages/umi-build-dev/src/Service.js

把
load(basePath);
load(localPath);
换个顺序改成：
load(localPath);
load(basePath);
应该就好了

**Comment by qq645381995** [comment]
问题解决了吗

**Comment by shuai4983958** [comment]
问题还存在没有解决

**Comment by kwzm** [comment]
Same question！
