### ISSUE TITLE
webpack编译过程异常，人工修改后正常启动（包括dev和build）

### ISSUE THREAD

**Issue by alexgogoing** [umijs/umi#2701]
## What happens?
![image](https://user-images.githubusercontent.com/30588385/60146607-c722a500-97fc-11e9-8f87-d43a44c312d4.png)
执行编译操作时，router.js 文件中出现异常换行符，手动删除该换行符后正常编译运行。
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Umi Version**:2.7.7 & 2.8.4
- **Node Version**: 10.12.0
- **Platform**: mac os

**Comment by sorrycc** [comment]
复现步骤给下，是约定式路由并且页头有注释吗？

**Comment by alexgogoing** [comment]
@sorrycc https://github.com/alexgogoing/error-feedback.git
复现仓库已经建立

**Comment by sorrycc** [comment]
看了下，是用的约定式路由，把 `error-feedback/src/pages/map/plugin` 改成 `error-feedback/src/pages/map/_plugin` 试试。

**Comment by alexgogoing** [comment]
@sorrycc 问题解决，感谢！
