### ISSUE TITLE
设置高清模式hd: true，高德地图缩小了

### ISSUE THREAD

**Issue by Nose407** [umijs/umi#2710]
设置高清模式hd: true，高德地图整体缩小了。请问题怎么解决呢？
![image](https://user-images.githubusercontent.com/19990129/60167829-73cd4880-9836-11e9-8fb7-e446b0cf67b5.png)

**Comment by Nose407** [comment]
生成的content="width=device-width,user-scalable=no,initial-scale=0.5,maximum-scale=0.5,minimum-scale=0.5"有问题不合理会吧第三方的整体缩小，这个可以配置不？最好设置成等于1。

**Comment by Mcyfeng** [comment]
是所有的地图都会有这情况，我建议就是能不能改成可配置式，某些页面可设置不用

**Comment by Nose407** [comment]
是呀，有没有解决的办法呢？

**Comment by xiaohuoni** [comment]
iframe的问题，通过设置样式不可以处理吗？

**Comment by xiaohuoni** [comment]
不要自己在html中设置 `<meta name="viewport" content="width=device-width, initial-scale=1.0" />`就可以
