### ISSUE TITLE
You may need an additional loader to handle the result of these loaders

### ISSUE THREAD

**Issue by dario-fiore** [umijs/umi#2712]
## What happens?
Command _`umi dev`_ fail with 1 compile error. Can you help me?

I already tried:
- npm cache clean
- npm install -g npm@latest
- npm i

```
ERROR  Failed to compile with 1 errors                                                                                                
error  in ./src/pages/.umi/router.js
Module parse failed: Unexpected token (36:15)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
```

## Context

- **Umi Version**:  2.6.13
- **Node Version**: 8.12.0
- **Platform**: Windows

**Comment by sorrycc** [comment]
How to reproduce? Please provide a reproducible repo.

**Comment by yue-qtl** [comment]
I also get this problem.
Here is npm package info of my project.
`npm list --depth=0
ant-design-pro@2.2.1 C:\workspace\qcc\customerportalfrontend
+-- @antv/data-set@0.10.2
+-- @babel/runtime@7.4.5
+-- @types/react@16.8.22
+-- @types/react-dom@16.8.4
+-- antd@3.19.8
+-- antd-pro-merge-less@1.0.0
+-- antd-theme-webpack-plugin@1.3.0
+-- axios@0.18.1
+-- babel-eslint@10.0.2
+-- babel-plugin-transform-remove-console@6.9.4
+-- chalk@2.4.2
+-- check-prettier@1.0.3
+-- classnames@2.2.6
+-- cross-env@5.2.0
+-- cross-port-killer@1.1.1
+-- crypto@1.0.1
+-- dva@2.4.1
+-- echarts@4.2.1
+-- enquire-js@0.2.1
+-- enzyme@3.8.0
+-- eslint@5.16.0
+-- eslint-config-airbnb@17.1.0
+-- eslint-config-prettier@3.6.0
+-- eslint-plugin-babel@5.3.0
+-- eslint-plugin-compat@2.7.0
+-- eslint-plugin-import@2.18.0
+-- eslint-plugin-jsx-a11y@6.2.1
+-- eslint-plugin-markdown@1.0.0
+-- eslint-plugin-react@7.14.2
+-- file-saver@2.0.2
+-- gh-pages@2.0.1
+-- git-rev-sync@1.12.0
+-- hash.js@1.1.7
+-- html2canvas@1.0.0-rc.3
+-- husky@1.3.1
+-- identicon.js@2.3.3
+-- jest-puppeteer@3.9.1
+-- js-yaml@3.13.1
+-- jspdf@1.5.3
+-- less@3.9.0
+-- lint-staged@8.2.1
+-- lodash@4.17.11
+-- lodash-decorators@6.0.1
+-- memoize-one@5.0.4
+-- merge-umi-mock-data@1.0.5
+-- mockjs@1.0.1-beta3
+-- moment@2.24.0
+-- numeral@2.0.6
+-- nzh@1.0.4
+-- omit.js@1.0.2
+-- path-to-regexp@3.0.0
+-- prettier@1.16.1
+-- prismjs@1.16.0
+-- prop-types@15.7.2
+-- puppeteer@1.18.1
+-- qs@6.7.0
+-- rc-animate@2.8.3
+-- UNMET PEER DEPENDENCY react@16.8.6
+-- react-container-query@0.11.0
+-- react-copy-to-clipboard@5.0.1
+-- react-document-title@2.0.3
+-- UNMET PEER DEPENDENCY react-dom@16.8.6
+-- react-fittext@1.0.0
+-- react-json-view@1.19.1
+-- react-media@1.9.2
+-- react-router-dom@4.3.1
+-- slash2@2.0.0
+-- stylelint@9.10.1
+-- stylelint-config-prettier@4.0.0
+-- stylelint-config-standard@18.3.0
+-- tslint@5.18.0
+-- tslint-config-prettier@1.18.0
+-- tslint-react@3.6.0
+-- umi@2.8.3
+-- umi-plugin-ga@1.1.3
+-- umi-plugin-react@1.9.4
+-- underscore@1.9.1
`-- xlsx@0.14.3`

Here is some error info.
![2](https://user-images.githubusercontent.com/40888352/60231842-3c5dab00-98cd-11e9-95ee-09d91c9baf43.png)

**Comment by yue-qtl** [comment]
I find a temporary solution that use `umi@2.7.7` and `umi-plugin-react@1.8.4`.
Reference link: https://github.com/umijs/umi/issues/2701

**Comment by dario-fiore** [comment]
There is an open issue here: https://github.com/webpack/webpack/issues/8656

**Comment by sorrycc** [comment]
So, how to reproduce? I've try in mac, and can not reproduce it.

**Comment by yue-qtl** [comment]
> So, how to reproduce? I've try in mac, and can not reproduce it.

My platform is windows 10. I'm not sure there's also a problem on Mac.
For now, I also can't reproduce this problem again in a new antd pro project.

Here's my step try to reproduce:
> git clone --depth=1 https://github.com/ant-design/ant-design-pro.git my-project -b v2
> cd my-project
> npm install --ignore-scripts
In this case, code works normally without error. I think the problem may be in other library I use .

**Comment by Ikxyz** [comment]
had same issue

**Comment by ken-chen-91** [comment]
me too

**Comment by antonpodkur** [comment]
same issue here when i try to add @react-three/cannon
