### ISSUE TITLE
cannot load font using font-face

### ISSUE THREAD

**Issue by nguyenhuutinh** [umijs/umi#2715]
Hi 

I tried to add font to publish and assets and use @font-face to load but still failed.

The text is not change. 
Do we need to config any thing else?

**Comment by sorrycc** [comment]
Need reproduce step.

**Comment by nguyenhuutinh** [comment]
sorry, I just realize that the global.css is not loaded even I build from umi ant pro. I'm checking it now

**Comment by nguyenhuutinh** [comment]
@font-face {
  font-family: 'SVN-LarchShaded';
  src: url('/fonts/fonts/SVN-LarchShaded.eot');
  src: url('/fonts/SVN-LarchShaded.eot?#iefix') format('embedded-opentype'),
       url('/fonts/SVN-LarchShaded.svg#SVN-LarchShaded') format('svg'),
       url('/fonts/SVN-LarchShaded.ttf') format('truetype'),
       url('/fonts/SVN-LarchShaded.woff') format('woff'),
       url('/fonts/SVN-LarchShaded.woff2') format('woff2');
  font-weight: normal;
  font-style: normal;
}

and I put my fonts to /public/fonts folder 
also tried with the assets folder but font is not applied

**Comment by nguyenhuutinh** [comment]
sorry my bad

**Comment by kovalevroman** [comment]
How to solve this problem?

> sorry my bad
