### ISSUE TITLE
SSR模式下 dev模式启动，不会build文件

### ISSUE THREAD

**Issue by williamnie** [umijs/umi#2721]
## What happens?
在ssr模式下，dev启动，不会build文件到public目录下，但是umi依然启动了，导致根本找不到umi.server.js ，无法进行server render。build模式下没问题
尝试使用昨天的备份，跑起来没问题，但清除node_modules以后重新yarn，就不行了，
也尝试了重新clone ssr-egg的demo，发现也不行，umi升级到最新版本也不行，初步判断，应该是某个依赖包问题。

## How To Reproduce
**Steps to reproduce the behavior:**
clone umi的ssr egg demo，dev启动即可复现

## Context

- **Umi Version**:尝试了2.8.0，2.8.6
- **Node Version**:12.4.0

**Comment by ycjcl868** [comment]
- 问题在 dev 时，只传入了 client 的 webpack 配置。[#L93-L97](https://github.com/umijs/umi/blob/master/packages/umi-build-dev/src/plugins/commands/dev/index.js#L93-L97)
- 之前的解决方案是用 webpack-dev-middleware 去执行服务端构建，触发 ` write-file-webpack-plugin` 插件生成 `umi.server.js`

**Comment by sorrycc** [comment]
@ycjcl868 提 PR 再加回去吧，webpack-dev-middleware 通过 af-webpack 露出，这样不会有 peerDependencies 的问题。

**Comment by williamnie** [comment]
我现在是ssr的测试人员，😆，光提问题了

**Comment by ycjcl868** [comment]
Thanks ~

**Comment by williamnie** [comment]
刚刚测试，umi升级到2.8.7版本，dev模式下会报错

```
✖  error     Error: Cannot find module 'af-webpack/webpack-dev-middleware'
Require stack:
- /Users/xiaobei/Documents/aminer/ssrTest/umi-example-ssr-with-egg/node_modules/umi-build-dev/lib/plugins/commands/dev/index.js
- /Users/xiaobei/Documents/aminer/ssrTest/umi-example-ssr-with-egg/node_modules/umi-build-dev/lib/getPlugins.js
- /Users/xiaobei/Documents/aminer/ssrTest/umi-example-ssr-with-egg/node_modules/umi-build-dev/lib/Service.js
- /Users/xiaobei/Documents/aminer/ssrTest/umi-example-ssr-with-egg/node_modules/umi/lib/scripts/realDev.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /Users/xiaobei/Documents/aminer/ssrTest/umi-example-ssr-with-egg/node_modules/umi-build-dev/lib/plugins/commands/dev/index.js:131:60
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
^C2019-06-30 19:34:10,046 INFO 16002 [master] receive signal SIGINT, closing
```

代码加回去，貌似在umi-build-dev里面的package没改？

**Comment by ycjcl868** [comment]
还没发布
