### ISSUE TITLE
打包后在umi.js里动态生成了一段代码：网络慢（超过2S）会自动重定向到根目录

### ISSUE THREAD

**Issue by amplee** [umijs/umi#2723]
## 环境
node:11.1.0;npm:6.4.1;umi:2.4.4;
react+dva+umi+antd搭建的
## 问题
两个项目之间跳转，从A项目跳去B项目（umi项目）时，请求时间若超过两秒，就会被重定向到根目录
## 如何复现
如问题所述，从一个非umi项目跳去umi项目，将network的网络设置慢点，在请求umi项目的时候，html文件里会先出现这样一段代码（个人猜测是打包后的umi.js动态生成的）：

`setTimeout("location.replace(location.href.split(\"#\")[0])",2000);`

而后，项目的URL就被改成到根目录，我在打包后的umi.js也有发现这样一段代码：

`g = function(e) {
            var t = window.location.href.indexOf("#");
            window.location.replace(window.location.href.slice(0, t >= 0 ? t : 0) + "#" + e)`

在umi的源码项目里，也进行了搜索，发现这段代码出现位置在源代码以下目录的文件：
packages/umi-build-dev/src/html/HTMLGenerator.js的248行到252行的代码：

`if  (exportStatic && exportStatic.dynamicRoot)  {

      routerBaseStr = `location.pathname.split('/').slice(0, -${route.path.split('/').length - 1}).concat('').join('/')`;

      publicPathStr = `location.protocol + '//' + location.hostname + (location.port ? ':' +  location.port : '') + window.routerBase`;
}`
## 期望
现在在做前后端分离，需要从旧项目跳去umi项目，希望把重定向到根路由的这个去掉，假如是项目有其他用处，那希望能提供一个方法给我自己去掉，谢谢

**Comment by sorrycc** [comment]
看了没啥头绪，需要给简单可复现的仓库，让我本地能复现出来。

**Comment by sorrycc** [comment]
和 HTMLGenerator 应该没啥关系，我觉得不是 umi 框架的问题，我跑了例子，没搜到 setTimeout + 2000 的代码，相关代码应该在业务代码上。

**Comment by amplee** [comment]
又查阅了一番，猜测是网页被劫持了。先关闭了，谢谢。

**Comment by hxswen** [comment]
> 

请问一下后面是怎么处理了呢
