### ISSUE TITLE
[Feature Request] support disable umi 404 when dev

### ISSUE THREAD

**Issue by DiamondYuan** [umijs/umi#2726]
## Background

When i use umi-plugin-qiankun with hash mode. #xxx is route to another app.

![image](https://user-images.githubusercontent.com/9692408/60355986-6795e680-9a02-11e9-843c-6c9bf5ad2b73.png)

## Proposal

add a config

**Comment by DiamondYuan** [comment]
maybe umi-plugin-qiankun can use api.modifyRoutes to change router rather change umi.



@kuitos

**Comment by kuitos** [comment]
主应用的配置发出来看一下？

**Comment by DiamondYuan** [comment]
> 主应用的配置发出来看一下？

https://github.com/umijs/umi-plugin-qiankun/blob/test/404/src/master/index.ts

主项目原本路由模式为 hash 时，就会这样。

**Comment by kuitos** [comment]
地址不对？ @DiamondYuan

**Comment by DiamondYuan** [comment]
> 地址不对？ @DiamondYuan

没错。我切了另外一个 branch.

**Comment by kuitos** [comment]
我以为你贴的链接是你的配置~
主工程里启用了 history 但是并没有对应的 routes 配置然后 404 了，这应该是预期之内的吧？如果只是禁用了 dev 的 404 感觉并没有真正解决问题？

目前有两个想法：
1. 大部分场景下主工程不需要自己的路由，插件直接禁用其 router
2. 插件根据注册信息里的 routerBase 配置注册路由，并提供相应的 404 fallback 处理

**Comment by DiamondYuan** [comment]
> 我以为你贴的链接是你的配置~
> 主工程里启用了 history 但是并没有对应的 routes 配置然后 404 了，这应该是预期之内的吧？如果只是禁用了 dev 的 404 感觉并没有真正解决问题？
> 
> 目前有两个想法：
> 
> 1. 大部分场景下主工程不需要自己的路由，插件直接禁用其 router
> 2. 插件根据注册信息里的 routerBase 配置注册路由，并提供相应的 404 fallback 处理

我现在遇到的场景是想从主工程拆分出一些页面出来，这个时候主工程的路由还必须存在。
解决方案是自己手动为拆分出来的页面配置一个完全空白的页面。

**Comment by kuitos** [comment]
嗯晚上我提个pr支持一下
