### ISSUE TITLE
[Feature Request] async render

### ISSUE THREAD

**Issue by DiamondYuan** [umijs/umi#2729]
## Background

https://github.com/umijs/umi-plugin-qiankun/blob/881eade3833149920699165ac900e8db5216f83c/src/master/runtimePlugin.ts#L7

我们老的项目，render 是异步的，需要先获取权限。

```
export function render(oldRender: typeof noop) {
  oldRender();
}
```

**Comment by DiamondYuan** [comment]
@kuitos  qiankun 现在是不是和 umi 原本的按需加载冲突。

**Comment by sorrycc** [comment]
没理解问题是啥，为什么会冲突？

**Comment by kuitos** [comment]
我试了下应用自己的异步 render 应该是不影响的，为啥会跟按需加载冲突？

**Comment by DiamondYuan** [comment]
> 我试了下应用自己的异步 render 应该是不影响的，为啥会跟按需加载冲突？

async render 是没问题的。

https://github.com/umijs/umi-plugin-qiankun/blob/test/dynamicImport/src/master/index.ts

我可能用法用错了 app-root 放在了 页面里，而不是 layout 里面。第一次 app2 可以加载，切换到其他页面会报错。

**Comment by kuitos** [comment]
app-root 是需要放到主应用里的

**Comment by DiamondYuan** [comment]
> app-root 是需要放到主应用里的

一定要放在主应用的 layout ? 不能每个页面不一样么。

**Comment by kuitos** [comment]
也是可以的，我们内部在用 qiankun 的时候就是这样的，因为接入应用的技术栈会更多变一些。
但是在主子应用都是 umi 的场景下，是否需要支持呢？ cc @sorrycc

**Comment by DiamondYuan** [comment]
> 也是可以的，我们内部在用 qiankun 的时候就是这样的，因为接入应用的技术栈会更多变一些。
> 但是在主子应用都是 umi 的场景下，是否需要支持呢？ cc @sorrycc

![image](https://user-images.githubusercontent.com/9692408/60489002-e4141800-9cd5-11e9-87c0-1dffe09df6eb.png)



https://github.com/umijs/umi-plugin-qiankun/tree/test/dynamicImport

从子应用切换到 master 的应用，会有一个警告。上面的项目可以复现。

**Comment by DiamondYuan** [comment]
> 也是可以的，我们内部在用 qiankun 的时候就是这样的，因为接入应用的技术栈会更多变一些。
> 但是在主子应用都是 umi 的场景下，是否需要支持呢？ cc @sorrycc

![image](https://user-images.githubusercontent.com/9692408/60489058-0148e680-9cd6-11e9-8f09-6c1038fbbc1c.png)


![image](https://user-images.githubusercontent.com/9692408/60489066-073ec780-9cd6-11e9-85fa-2bdf63436ac1.png)



访问 master 然后跳转到 app2 和 直接访问 app2 。显示的样式不一样。
app-root 的替换遇到了问题.
