### ISSUE TITLE
我用这个写完程序打包给朋友

### ISSUE THREAD

**Issue by fattypanda** [umijs/umi#2732]
我做了一个小东西，给朋友看，没有服务器，朋友不是搞编程的。
是不是我还得买一个服务器，或则搞个内网穿透才能给朋友正常用？
就不能引入路径相对嘛，太难受，就算不默认，也要可以支持吧？

**Comment by williamnie** [comment]
啥叫引入相对路径？你是build了以后发给你朋友看的？你问题没有描述清楚吧，这样提问没法帮你，

**Comment by xiaohuoni** [comment]
now

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/60406216-6376ee00-9be7-11e9-84e9-bbefe4c63583.png)
https://www.yuque.com/umijs/umi/serve
