### ISSUE TITLE
umi@2.8.8 SSR: Cannot find module '@tmp/history'

### ISSUE THREAD

**Issue by elivoa** [umijs/umi#2737]
umijs/umi-example-ssr-with-egg
升级到 umi@2.8.8，yarn build && yarn start 之后
Build过程没有报错，打开页面，服务端报错：

2019-07-02 00:51:57,657 ERROR 38310 [-/::1/-/803ms GET /] nodejs.MODULE_NOT_FOUNDError: Cannot find module '@tmp/history'
Require stack:
- /xxx/umi-example-ssr-with-egg/node_modules/umi/lib/router.js
- /xxx/umi-example-ssr-with-egg/node_modules/umi/router.js
- /xxx/umi-example-ssr-with-egg/app/public/umi.server.js
- /xxx/umi-example-ssr-with-egg/app/controller/home.js
- /xxx/umi-example-ssr-with-egg/node_modules/egg-core/lib/utils/index.js
- /xxx/umi-example-ssr-with-egg/node_modules/egg-core/lib/egg.js
- /xxx/umi-example-ssr-with-egg/node_modules/egg-core/index.js
- /xxx/umi-example-ssr-with-egg/node_modules/egg/lib/application.js
- /xxx/umi-example-ssr-with-egg/node_modules/egg/index.js
- /xxx/umi-example-ssr-with-egg/node_modules/egg-cluster/lib/app_worker.js
Require stack:
- /xxx/umi-example-ssr-with-egg/node_modules/umi/lib/router.js
- /xxx/umi-example-ssr-with-egg/node_modules/umi/router.js
- /xxx/umi-example-ssr-with-egg/app/public/umi.server.js
- /xxx/umi-example-ssr-with-egg/app/controller/home.js
- /xxx/umi-example-ssr-with-egg/node_modules/egg-core/lib/utils/index.js
- /xxx/umi-example-ssr-with-egg/node_modules/egg-core/lib/egg.js
- /xxx/umi-example-ssr-with-egg/node_modules/egg-core/index.js
- /xxx/umi-example-ssr-with-egg/node_modules/egg/lib/application.js
- /xxx/umi-example-ssr-with-egg/node_modules/egg/index.js
- /xxx/umi-example-ssr-with-egg/node_modules/egg-cluster/lib/app_worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/xxx/umi-example-ssr-with-egg/node_modules/umi/lib/router.js:13:39)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
code: "MODULE_NOT_FOUND"
requireStack: ["/xxx/umi-example-ssr-with-egg/node_modules/umi/lib/router.js","/xxx/umi-example-ssr-with-egg/node_modules/umi/router.js","/xxx/umi-example-ssr-with-egg/app/public/umi.server.js","/xxx/umi-example-ssr-with-egg/app/controller/home.js","/xxx/umi-example-ssr-with-egg/node_modules/egg-core/lib/utils/index.js","/xxx/umi-example-ssr-with-egg/node_modules/egg-core/lib/egg.js","/xxx/umi-example-ssr-with-egg/node_modules/egg-core/index.js","/xxx/umi-example-ssr-with-egg/node_modules/egg/lib/application.js","/xxx/umi-example-ssr-with-egg/node_modules/egg/index.js","/xxx/umi-example-ssr-with-egg/node_modules/egg-cluster/lib/app_worker.js"]
name: "MODULE_NOT_FOUNDError"

**Comment by yoster0520** [comment]
@sorrycc umi test阶段也报这个错了，
  ● Test suite failed to run

    Cannot find module '@tmp/history' from 'router.js'

    However, Jest was able to find:
        'lib/router.js'
```
import router from 'umi/router';
router.push({...})
````

**Comment by yoster0520** [comment]
请问，怎样可以解决这个问题，版本2.7.7 刚用2.8.8试也不行。

**Comment by aquibbaig** [comment]
Anybody got the solution for this?

> @sorrycc umi test阶段也报这个错了，
> ● Test suite failed to run
> 
> ```
> Cannot find module '@tmp/history' from 'router.js'
> 
> However, Jest was able to find:
>     'lib/router.js'
> ```
> 
> ```
> import router from 'umi/router';
> router.push({...})
> ```
