### ISSUE TITLE
pages 下配置了两个ejs名，

### ISSUE THREAD

**Issue by lsdiao** [umijs/umi#274]
我在pages下放了两个ejs， 一个document.ejs, 一个print.ejs ，然后在.umi.js配置如下
```
  pages: {
    "/print/*": { document: './src/pages/print.ejs' },
  },
```
这样我调用print/list的时候并没有引用print.ejs,请问我改怎么配置
` "/print/list": { document: './src/pages/print.ejs' },`
也不行

**Comment by sorrycc** [comment]
试试 https://github.com/umijs/umi/tree/master/examples/func-test ？ 我测了下没有问题。
