### ISSUE TITLE
where is the place to put my custom enviroment variables?

### ISSUE THREAD

**Issue by videni** [umijs/umi#2740]
the issue [Cannot customize HOST from env](https://github.com/umijs/umi/issues/1397) is not correct answer. the situation is simple,  I want the the domain of API be changed along with the environment.  apparently  the config/config.js or .umirc.js  is not for our custom use, otherwise, there must be a method for us to get it in our code , for example 
```
endpoint = config('API_ENDPOINT');

axios({url:`${endpoint}/api/v1/admin/product`});

```
also this configuration will output to frontend.

of course I can make my owner environment config this way, however,   we would end up with two env files, one is for umijs, one is ours. this is not a good idea.

**Comment by khalibloo** [comment]
If you define the endpoint using the `define` property in `.umirc` (as described in https://github.com/umijs/umi/issues/1397#issuecomment-465260258), you should be able to use it in your code like so.
```ts
endpoint = API_ENDPOINT;
axios({url:`${endpoint}/api/v1/admin/product`});
```
No need for a method.

**Comment by videni** [comment]
@khalibloo, thanks , your solution works,  I didn't understand it at the first glimpse.
