### ISSUE TITLE
Custom Layout css is not applied

### ISSUE THREAD

**Issue by nguyenhuutinh** [umijs/umi#2741]
## What happens?
my layout css is overrided by the ant css 

## How To Reproduce
**Steps to reproduce the behavior:**
1. i have home page (/) use mainlayout and login page (/login) use userlayout in route config
2. in the userLayout, I use < DefaultFooter /> from ant pro block
3. open home page , go to /login , click logo to back to home.
4. my mainLayout css and global.less css is below the index.less of ant

if I remove Default Footer and DocumentTitle , my main layout css is works
**Expected behavior**
1. keep the current layout css (mainLayout)

## Context

- **Umi Version**:2.7.2
- **Node Version**: 11.11
- **Platform**:

**Comment by DuffyWang926** [comment]
Hi，Did you resolve it? I get a similar problem.
I use the antd modal,give the wrapClassName={headerStyle.cartsModal}.
When I write the .cartsModal in global.css. It works.
But write the .cartsModal in ./header.scss.It dosen't work.I can look the class in googleChrome,but it doesn't work!
<img width="854" alt="image" src="https://user-images.githubusercontent.com/31502024/61100229-f17c8f80-a497-11e9-8670-eb5184ef174d.png">

**Comment by nguyenhuutinh** [comment]
did you add it to the config file?

**Comment by nguyenhuutinh** [comment]
<img width="661" alt="Screenshot 2019-07-12 at 12 34 59 PM" src="https://user-images.githubusercontent.com/4114159/61102692-7fa94380-a4a1-11e9-80e8-e0ea0a021ae9.png">

**Comment by nguyenhuutinh** [comment]
and the custom css file should be putted in the pages folder, not sub component folder
