### ISSUE TITLE
umi/dynamic

### ISSUE THREAD

**Issue by BinaryHao** [umijs/umi#2742]
umi/dynamic
怎么用，比如有个按钮，我点击会动态的加载某个组件
dynamic({
    loader: () => import('../pages/Demo.tsx')
});
这样写不行，这个应该怎么用

**Comment by elivoa** [comment]
我做的延时加载组件。并且webpack打包到独立的trunk。

const LazyXXX = dynamic({
  modules: () => ({ SomeComp: import('./SomeComp' /* webpackChunkName:"blabla” */) }),
  render(props, loaded) {
    return (<loaded.SomeComp {...props} />);
  },
  loading: () => (null),
});

**Comment by sorrycc** [comment]
[sorrycc-hgB73I.zip](https://github.com/umijs/umi/files/3366573/sorrycc-hgB73I.zip)

试过发现没问题，

1. 通过 dynamic 引入组件

```js
const Foo = dynamic({
  loader: () => import('../Foo'),
});
```

2. 通过 umi-plugin-react 开 dynamic

```js
export default {
  plugins: [
    ['umi-plugin-react', {
      dynamicImport: true,
    }],
  ]
}
```

**Comment by sorrycc** [comment]
[sorrycc-hgB73I.zip](https://github.com/umijs/umi/files/3366573/sorrycc-hgB73I.zip)

试过发现没问题，

1. 通过 dynamic 引入组件

```js
const Foo = dynamic({
  loader: () => import('../Foo'),
});
```

2. 通过 umi-plugin-react 开 dynamic

```js
export default {
  plugins: [
    ['umi-plugin-react', {
      dynamicImport: true,
    }],
  ]
}
```

**Comment by llfylwg** [comment]
这样打包出来的文件名是以id命名的，怎么自定义呢 ？
