### ISSUE TITLE
Hash 为true，并同时配置 base 后 hash路径问题

### ISSUE THREAD

**Issue by mizi-lin** [umijs/umi#2743]
这其实是 #2597 的后续问题

umi_v2.8.8

场景
.umirc.ts 
```ts
hash: true,
history: 'hash',
base: '/sub',
```
启动项目 访问route (NavLink, Link) 后地址为
`http://localhost:8001/sub#/sub/base-error `

但我所期望的是 （或 2.6 之前版本为）
`http://localhost:8001/sub#/base-error`

dev 模式下 使用 `http://localhost:8001/sub/#/base-error` 访问
控制台警告信息

![image](https://user-images.githubusercontent.com/2802841/60506026-8690c300-9cf7-11e9-8699-c392802d039b.png)

------

可复现资源地址：

[git@github.com:mizi-lin/umi-issues.git](https://github.com/mizi-lin/umi-issues)

**Comment by Renderz** [comment]
原来是版本问题么... 我以为用了base就不能用hash history. 现在用回browserHistory 同时改了nginx的匹配逻辑...

**Comment by ycjcl868** [comment]
base 去掉就行了

**Comment by ycjcl868** [comment]
any question?

**Comment by Renderz** [comment]
> base 去掉就行了

功能就是需要base啊... 去掉是什么情况...

**Comment by sorrycc** [comment]
base 带 `/` 后缀，我试过这样配没问题，

```js
export default {
  history: 'hash',
  base: '/foo/'
};
```

**Comment by mizi-lin** [comment]
@sorrycc 

使用新配置
问题依旧存在

umi version: 2.8.16

![image](https://user-images.githubusercontent.com/2802841/62051108-3f89e500-b245-11e9-9fbb-5edd835ebd42.png)

**Comment by sorrycc** [comment]
base 你理解错了，base 是路由的 base，你设了 `/sub/` 如果是 hash，那 `/#sub/` 是期望的结果。

**Comment by mizi-lin** [comment]
@sorrycc 
 
那混乱了，
在 umi version: 2.8.16  的结果是 `/sub/#sub/`
而不是你所说的期望值 `/#sub/`
---
而 umi_v2.8.8 与你所说更不一致
其表现为  /sub#/

> 所以这边略显混乱

- 按你所说 base 是路由的base 那么 就不应该把二级目录也设置为 base 的值 `sub/#sub` 而应该只是 '/#sub/'

- 若跟旧版本一样那 base指向的是 二级目录 'sub/#/' 
![image](https://user-images.githubusercontent.com/2802841/64075035-9a4faa00-cce5-11e9-8505-9f88e8e6fa2a.png)

**Comment by mizi-lin** [comment]
@Renderz 

你能改配置算好的·
我都不敢动
功能还好
URL 地址不敢改变~ 
一些客户因为其自身原因，配置后，就不能改变URL地址
--
现在我因为这么一点点小功能，不能升级UMI也蛮搞笑的··

**Comment by everything8** [comment]
怎么解决的？遇到了同样的问题
