### ISSUE TITLE
动态生成嵌套路由，三个路由显示组件都是_layout.js

### ISSUE THREAD

**Issue by majiang666** [umijs/umi#2746]
#1562  What happens?
按照官方示例动态生成嵌套路由，然后三个路径全都读取同一个组件，并且动态生成的src\pages\.umi\router.js  的"exact": false
`{
        "path": "/users",
        "exact": false,
        "component": require('../users/_layout.js').default,
        "routes": [
          {
            "path": "/users",
            "exact": true,
            "component": require('../users/index.js').default,
            "_title": "umijs",
            "_title_default": "umijs"
          },
          {
            "path": "/users/list",
            "exact": true,
            "component": require('../users/list.js').default,
            "_title": "umijs",
            "_title_default": "umijs"
          },
          {
            "component": () => React.createElement(require('E:/work/github/umijs/node_modules/umi-build-dev/lib/plugins/404/NotFound.js').default, { pagesPath: 'src/pages', hasRoutesInConfig: false }),
            "_title": "umijs",
            "_title_default": "umijs"
          }
        ],
        "_title": "umijs",
        "_title_default": "umijs"
      }`

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库
https://github.com/majiang666/umijs 

## 相关环境信息
- **Umi 版本**："^2.7.7"
- **Node 版本**：v10.16.0
- **操作系统**：windows10

**Comment by sorrycc** [comment]
问题是啥？

**Comment by majiang666** [comment]
> 问题是啥？

问题就是：我现在自动生成嵌套路由，pages/users/_layout.js和pages/users/index.js，两个访问的component应该是不一样的，但是现在我访问http://localhost:8000/users和http://localhost:8000/users/，以及users下的所有路由，最后展示的都是pages/users/_layout.js这个组件的内容。
代码仓库是：https://github.com/majiang666/umijs，感谢！

**Comment by sorrycc** [comment]
理解下你的问题，

```
+ pages
  + users
    - _layout.js
    - index.js
```

然后访问 `/users` 下所有路径，都会带上 `_layout.js`？

这是符合预期的吧，你希望如何组织呢？

**Comment by majiang666** [comment]
> 理解下你的问题，
> 
> ```
> + pages
>   + users
>     - _layout.js
>     - index.js
> ```
> 
> 然后访问 `/users` 下所有路径，都会带上 `_layout.js`？
> 
> 这是符合预期的吧，你希望如何组织呢？

您说的这个是对的，但是现在访问 /users 下所有路径，**都只显示_layout.js**，其他的组件都不显示。
比如：
`
+ pages
  + users
    - _layout.js
    - index.js
    - other.js
`
我现在访问 `/users/other`,只显示`_layout.js`，而不显示`other.js`的内容，不知道是我的配置有问题吗？谢谢
示例代码已经上传：https://github.com/majiang666/umijs

**Comment by sorrycc** [comment]
_layout.js 里得通过 props.children 渲染子路由，比如 [src/pages/users/_layout.js](https://github.com/majiang666/umijs/blob/master/src/pages/users/_layout.js) ，

```js
export default function(props) {
  return (
    <div>
      <h1>user-home</h1>
      { props.children }
    </div>
  );
}
```

**Comment by majiang666** [comment]
非常感谢，这个还是我理解的不太深，继续学习。
