### ISSUE TITLE
[umi-types] webpack-chain模块的类型定义有问题

### ISSUE THREAD

**Issue by duan602728596** [umijs/umi#2752]
## What happens?

在开发umi插件时，`webpack-chain`模块是使用`export =`导出类型的，`umi-types`在引入`webpack-chain`模块时，是
```javascript
import IWebpackChainConfig from 'webpack-chain';
```
这样引入的，这样会报错误` error TS1259: Module '"node_modules/webpack-chain/types/index"' can only be default-imported using the 'esModuleInterop' flag`，可以使用`tsc --esModuleInterop`来解决。但是`--esModuleInterop`会导致其他的js模块和同样使用`export =`导出类型的模块出现问题。

建议修改成：
```javascript
import * as IWebpackChainConfig from 'webpack-chain';
```

## 最小可复现仓库

[https://github.com/duan602728596/umi-types-bug-example](https://github.com/duan602728596/umi-types-bug-example)

## 复现步骤，错误日志以及相关配置

1. `tsc`编译代码，
  会报错` This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag`
2. `tsc --esModuleInterop`，编译成功，
  但是代码内使用`import * as module from 'module-name';`方式导入的模块会报错` Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.`。
3. `umi-types`改成`import * as IWebpackChainConfig from 'webpack-chain';`后，
  正常编译代码成功。

## 相关环境信息

- **Umi 版本**：umi-types v0.3.11
- **Node 版本**：v12.4.0
- **操作系统**：win10

**Comment by ycjcl868** [comment]
PR Welcome

**Comment by duan602728596** [comment]
我的typescript编译没有开启`esModuleInterop`选项，开启`esModuleInterop`就好了，但是这样可能会对严格一些的工程有影响吧。
