### ISSUE TITLE
Please use `require("dva").dynamic` instead of `require("dva/dynamic")

### ISSUE THREAD

**Issue by ray0324** [umijs/umi#2753]
## 复现步骤:

1. npm create umi app 
2. 选择 app
3. 选择 typescript
4. 选择 codespliting  dva
5. cd app && npm start
 打开窗口即可看到

## 相关环境信息

- **Umi 版本**：2.8.8
- **Node 版本**：12.5.0
- **操作系统**： win 10

![1](https://user-images.githubusercontent.com/5204198/60680921-c2768480-9ebf-11e9-817d-a13dc8bacb76.jpg)

**Comment by guyunxiang** [comment]
看这里 https://github.com/umijs/umi/issues/2672，

dva 版本降到 2.5.0-beta.2 即可
