### ISSUE TITLE
[Feature Request] umi build support watch

### ISSUE THREAD

**Issue by DiamondYuan** [umijs/umi#2759]
有些场景需要，例如开发 chrome 插件的时候。

**Comment by xiaohuoni** [comment]
开发插件的时候dev不够嘛？

**Comment by DiamondYuan** [comment]
> 开发插件的时候dev不够嘛？

chrome 插件必须生成所有的文件。dev 下有些文件在内存里。

**Comment by ycjcl868** [comment]
`father build --watch` 会比较合适吧

**Comment by xiaohuoni** [comment]
@ycjcl868 这是要写页面的，如果是 `father build --watch` ，那 `father` 又要包含 `umi` 的内容，感觉更乱了吧？

**Comment by DiamondYuan** [comment]
https://github.com/webclipper/web-clipper

用 webpack 配置的 chrome 插件。

使用了 dva ts umi。


umi 暂时不支持的地方


1. dev 时生成所有文件到本地
2. webpack-chrome-extension-reloader 实现 插件的热加载
3. webpack-create-extension-manifest-plugin 根据配置生成插件的 manifest

**Comment by arvinxx** [comment]
针对 electron 的开发，希望build有 watch功能 。希望能够评估一下加入。感谢~
