### ISSUE TITLE
[umi-plugim-qiankun] 子项目的 base 配置问题

### ISSUE THREAD

**Issue by DiamondYuan** [umijs/umi#2763]
原本主项目有三个页面
wechat/a
wechat/b

拆分出一个子项目 wechat，设置 base为 wechat
配置
```
 [
    '@umijs/plugin-qiankun/master',
    {
      apps: [
        {
          name: 'wechat',
          routerBase: '#/wechat',
          entry: 'http://localhost:8001/wechat/',
        },
      ],
    },
  ],
```

当 wechat 进行路由切换时 
router.push('wechat/b') 会跳转到 'wechat/wechat/b'

此时需要把原来的代码改成 router.push('/b')。

**Comment by kuitos** [comment]
之前没有设置 base 么？
如果不想改子项目代码可以设置 base 为 '/' 跟之前保持一致

**Comment by DiamondYuan** [comment]
> 之前没有设置 base 么？
> 如果不想改子项目代码可以设置 base 为 '/' 跟之前保持一致

如果之前的项目没有 base，那么子项目的 base 只能为 /
