### ISSUE TITLE
【SSR】动态路由无法正常显示，pathname bug

### ISSUE THREAD

**Issue by dzj15973** [umijs/umi#2770]
动态路由中  此行代码有点小问题,应该不能直接使用 pathname，动态路由好像不一样

https://github.com/umijs/umi/blob/6292344ff4ae6aa430ead13466bf91f37537fa91/packages/umi-build-dev/template/entry.js.tpl#L81

应该使用 Router 的path：

https://github.com/umijs/umi/blob/6292344ff4ae6aa430ead13466bf91f37537fa91/packages/umi-build-dev/template/entry.js.tpl#L57

可能需要改成如下样子：
```jsx
 return {
      htmlElement: htmlTemplateMap[activeRoute.path],
      rootContainer,
    };
```

**Comment by ycjcl868** [comment]
PR Welcome
