### ISSUE TITLE
[Feature Request] 提供配置或 hook 可以忽略 src/app.js

### ISSUE THREAD

**Issue by yesmeck** [umijs/umi#2773]
## Background

在尝试把 remax 的小程序应用用 umi 构建到 web 应用，但是小程序的 [`src/app.js`](https://github.com/remaxjs/todo-demo/blob/master/src/app.js) 跟 umi 的约定规则有冲突。

## Proposal

提供配置或 hook 可以忽略 src/app.js

**Comment by sorrycc** [comment]
## 方案

新增一个 `api.modifyRuntimePlugins` hook，

```js
api.modifyRuntimePlugins(memo => {
  // 过滤默认的运行时插件配置
  return memo.filter(p => p !== '@/app');
});
```

**Comment by yesmeck** [comment]
现在好像不需要了
