### ISSUE TITLE
使用react hook 报错

### ISSUE THREAD

**Issue by chrisovu** [umijs/umi#2775]
在现有项目中使用 react hook 报错。

经测试：
使用 yarn create umi 创建一个 JavaScript app dva 模板
使用 useState 的时候均报错：
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app

使用 yarn create umi 创建一个 TypeScript app dva 模板
useState 可以正常使用。

npm ls react
├── react@16.8.6 
└─┬ umi@2.8.9
  └─┬ umi-build-dev@1.10.9
    ├── react@16.8.6  deduped
    └─┬ umi-test@1.6.1
      └── react@16.8.6  deduped

**Comment by chrisovu** [comment]
> 在现有项目中使用 react hook 报错。
> 
> 经测试：
> 使用 yarn create umi 创建一个 JavaScript app dva 模板
> 使用 useState 的时候均报错：
> 
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> 
> 使用 yarn create umi 创建一个 TypeScript app dva 模板
> useState 可以正常使用。
> 
> npm ls react
> ├── react@16.8.6
> └─┬ umi@2.8.9
> └─┬ umi-build-dev@1.10.9
> ├── react@16.8.6 deduped
> └─┬ umi-test@1.6.1
> └── react@16.8.6 deduped

**Comment by komagic** [comment]
我也遇到了诶
