### ISSUE TITLE
css 的热更新问题

### ISSUE THREAD

**Issue by XuZhaoTong** [umijs/umi#2778]
按照rhl官网教程配置了一下，没效果，配完和hmr的效果一样，比如说input框中输入了文字，更新一下css，input中的文字就没了。代码如下：

.umirc.js
```//.umirc.js
export default {
  extraBabelPlugins: ['react-hot-loader/babel'],
  chainWebpack(config, { webpack }) {
    config.resolve.alias.set('react-dom', '@hot-loader/react-dom');
    config.devServer.hot(true);
    config.devtool('eval');
    new webpack.HotModuleReplacementPlugin();
  },
};
```

layouts/index.js
```//.layouts.js
import { hot } from 'react-hot-loader/root';
import React, { Suspense } from 'react';

class App extends React.Component {
  render() {
    return (
      <>
        <Suspense fallback={<div>Loading...</div>}>
          {this.props.children}
        </Suspense>
      </>
    );
  }
}

export default hot(App);
```

**Comment by sorrycc** [comment]
有内置 hmr 的，为啥还要额外配？

**Comment by XuZhaoTong** [comment]
> 有内置 hmr 的，为啥还要额外配？

比如我现在有个场景 我从状态0推到状态2了 然后更新下css又回到状态0了  就感觉很浪费时间

**Comment by sorrycc** [comment]
那是 css 的 hmr 问题吧，用了 css-modules？

**Comment by XuZhaoTong** [comment]
> 那是 css 的 hmr 问题吧，用了 css-modules？

嗯是的，每次一修改CSS控制台就会提示 [HMR] Detected local css modules. Reload all css，也没找到什么办法，所以就想试试rhl

**Comment by MinJieLiu** [comment]
这个问题在目前版本上仍然存在，难受。

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/3763

**Comment by xiaodun** [comment]
找了半天找到了这里，有大佬找到解决方案了吗，我看了下不是所有的命名都改变了，是在不行就不用css Module

**Comment by MinJieLiu** [comment]
@xiaodun 现在 react 团队出了 `Fast Refresh` 方案，目前将就用，等方案成熟。

**Comment by xiaodun** [comment]
> @xiaodun 现在 react 团队出了 `Fast Refresh` 方案，目前将就用，等方案成熟。https://www.npmjs.com/package/react-refresh

请教下，这个要怎么集成到umi 中，介绍一片空白...

**Comment by MinJieLiu** [comment]
等方案成熟，比较刚出不久 webpack 插件还有很多BUG
