### ISSUE TITLE
How to configure webpack?

### ISSUE THREAD

**Issue by RusseII** [umijs/umi#2780]
I am trying to configure webpack, like in this example https://github.com/collab-project/videojs-record/wiki/React

![image](https://user-images.githubusercontent.com/15036618/60810067-80ce2e00-a18c-11e9-84ef-8b9666db6851.png)
They are using create-react app

How do I make this same configuration with umijs? 

In my umirc.ts file, I tried adding 
```
  chainWebpack(config, { webpack }) {
    const videojsPlugin = new webpack.ProvidePlugin({
      videojs: 'video.js/dist/video.cjs.js',
      RecordRTC: 'recordrtc',
      MediaStreamRecorder: ['recordrtc', 'MediaStreamRecorder'],
    });

    config.plugin('record').use(videojsPlugin);
    config.resolve.alias
      .set('videojs', 'video.js')
      .set('WaveSurfer', 'wavesurfer.js')
      .set('RecordRTC', 'recordrtc');
  },
```
but it did not work. 

Here is a code sandbox reproducing my issue: https://codesandbox.io/s/configure-webpack-plugins-y0shn

**Comment by ycjcl868** [comment]
Good question another https://github.com/collab-project/videojs-record/issues/382, maybe you can config like this:

```js
// .umirc.ts
export default {
  chainWebpack(config, { webpack }) {
    config.plugin('record').use(require.resolve('webpack/lib/ProvidePlugin'), [{
      videojs: 'video.js/dist/video.cjs.js',
      RecordRTC: 'recordrtc',
      MediaStreamRecorder: ['recordrtc', 'MediaStreamRecorder']
    }]);
  },
  // https://umijs.org/config/#alias
  alias: {
    videojs: 'video.js',
    WaveSurfer: 'wavesurfer.js',
    RecordRTC: 'recordrtc'
  },
}
```

I tried, but gave me an error `Error: plugin "record" does not exist`, it seems like `videojs-record` issue collab-project/videojs-record#328 for React.

**Comment by thijstriemstra** [comment]
See https://github.com/collab-project/videojs-record/wiki/UmiJS.

This ticket can be closed imo.
