### ISSUE TITLE
约定式路由只能指定统一的全局布局，无法实现为特定页面定制布局

### ISSUE THREAD

**Issue by rtxu** [umijs/umi#2781]
## What happens?
在 umi 官方文档有关[嵌套路由](https://umijs.org/zh/guide/router.html#%E5%B5%8C%E5%A5%97%E8%B7%AF%E7%94%B1)的描述中，除了全局布局外，还可以给页面配置单独布局

但是我配置完后，**子页面的布局还是嵌入到全局布局之中**

![image](https://user-images.githubusercontent.com/539937/60821875-f9f27300-a1d6-11e9-9a16-4c5b6e1f1222.png)
![image](https://user-images.githubusercontent.com/539937/60821902-070f6200-a1d7-11e9-8503-c09c48c4432f.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

https://github.com/rtxu/umi-bug-report

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1. 子页面拥有单独的布局
2.

## Context

- **Umi Version**: 2.8.9
- **Node Version**: 10.15
- **Platform**: windows

**Comment by smithyj** [comment]
_layout.js

**Comment by sorrycc** [comment]
在全局布局里通过 path 区分处理不同的 render 逻辑。
