### ISSUE TITLE
路由动效有问题

### ISSUE THREAD

**Issue by XuZhaoTong** [umijs/umi#2789]
![微信图片编辑_20190710112627](https://user-images.githubusercontent.com/32711995/60938235-d548e900-a305-11e9-9952-8230c57e1b03.jpg)
切换路由时，只有下面的dom会有exit的class，上面的dom没有enter的class

layouts.js
```
import withRouter from 'umi/withRouter';
import { TransitionGroup, CSSTransition } from 'react-transition-group';

export default withRouter(({ location, match, children }) => (
  <>
    <div>
      <TransitionGroup>
        <CSSTransition key={location.pathname} classNames="fade" timeout={300}>
          {children}
        </CSSTransition>
      </TransitionGroup>
    </div>
  </>
));
```

路由跳转用的是router.push()

package.json中的包都是最新的

**Comment by xiaohuoni** [comment]
> 只有下面的dom会有退出的class 上面的dom没效果

加个标点吧，看不懂。再提供个demo

**Comment by XuZhaoTong** [comment]
> > 只有下面的dom会有退出的class 上面的dom没效果
> 
> 加个标点吧，看不懂。再提供个demo

这个是我从项目上拷贝出来的删减版，能复现。https://github.com/XuZhaoTong/CssTrans-demo

**Comment by Fuphoenixes** [comment]
我也遇见了

**Comment by Fuphoenixes** [comment]
这样exit的样式触发了，enter的样式没有

**Comment by Fuphoenixes** [comment]
找到解决办法了，加层div
`
export default withRouter(
  ({ location, children }) =>{
    return(
      <TransitionGroup>
        <CSSTransition key={location.pathname} classNames="fade" timeout={10000}>
          <div>
            { children }
          </div>
        </CSSTransition>
      </TransitionGroup>
    )
})
`

**Comment by Fuphoenixes** [comment]
找到解决办法了，在CSSTransition 下加层div
```

export default withRouter(
  ({ location, children }) =>{
    return(
      <TransitionGroup>
        <CSSTransition key={location.pathname} classNames="fade" timeout={10000}>
          <div>
            { children }
          </div>
        </CSSTransition>
      </TransitionGroup>
    )
})

```
