### ISSUE TITLE
umi dev 执行仍然报错

### ISSUE THREAD

**Issue by lfire** [umijs/umi#2791]
## What happens?
按官网手册提供的方式开始使用 umi 时，执行 umi dev 即报错
手册地址：
https://umijs.org/zh/guide/getting-started.html#%E8%84%9A%E6%89%8B%E6%9E%B6
报错内容

![image](https://user-images.githubusercontent.com/2528719/60952586-1f45c500-a32e-11e9-89a4-3e29985e3684.png)

本问题与 2768 重复，但发现仍存在问题，
https://github.com/umijs/umi/issues/2768

## 最小可复现仓库
直接执行官网介绍最简单步骤，如下

## 复现步骤，错误日志以及相关配置
```bash
npm i -g umi
mkdir myUmi
cd myUmi
umi g page index
umi dev
```

## 相关环境信息

- **Umi 版本**：2.8.10
- **Node 版本**：10.16.0
- **操作系统**：windows 10

**Comment by lfire** [comment]
经过测试，该报错只会出现在全局安装 umi 的情况下，如若使用 本地安装，
```
npx umi dev
```
一切正常

**Comment by sir-ran** [comment]
老哥，一毛一样的问题啊，我也是全局安装的。
运行`umi dev` 时就报umi下有些模块找不到
![image](https://user-images.githubusercontent.com/26730748/61423529-b3251b80-a942-11e9-9ebc-88cffa4dbcbc.png)

**Comment by sppsun** [comment]
@lfire @sir-ran 两位这个问题解决了吗？现在Mac下面依然报错。谢谢。
