### ISSUE TITLE
本地开发热更新时该如何配置忽略某一文件？

### ISSUE THREAD

**Issue by htank-wang** [umijs/umi#2792]
我写了一个umi插件，在Compiled的时候会调用方法实时生成一份业务代码。
但这个时候umi会监控到业务代码变化再次进行Compile。
这样形成了死循环。

**Comment by xiaohuoni** [comment]
临时的代码可以放到临时文件夹去，build的时候，再放到项目中？

**Comment by htank-wang** [comment]
有考虑过，这种方法有点绕。

比如我的文件为public/manifest.json。用临时文件是否这样操作：
1.gitignore配置忽略public/manifest.json。
2.build完拷贝public/manifest.json到dist目录。

**Comment by htank-wang** [comment]
郁闷，之前放在src目录内容变化时不会触发热更新，今天启动项目突然又触发了。

临时文件夹是怎么创建，类似这种:".umi"？

**Comment by sorrycc** [comment]
为什么要在 Compiled 时去做？

**Comment by htank-wang** [comment]
umi有些地方做的不错，比如一个命令生成页面框架等等。

基于umi框架，我做了一些改造。设计思路是这样的：
1.用户开发一个页面前，先写配置文件(api，字段等等)
2.开发阶段自动编译时会调用我写一个小node脚本对配置文件进行处理。配置文件某些字段由脚本生成。内部会集成一些实时校验等等。
3.页面的开发依赖这个配置文件，所有展现由配置文件决定。
4.和具体业务绑定（如权限等等）

最终目的是希望根据配置文件一个命令生成具备完整功能的页面（CRUD）。

 其中第2点开发阶段比较依赖Compiled，所以Compiled的回调对我比较重要。

**Comment by htank-wang** [comment]
如下图所示
![image](https://user-images.githubusercontent.com/17918845/61442440-301fb780-a97a-11e9-8374-e24a8ba2035d.png)

**Comment by sorrycc** [comment]
F1.json 是被依赖谁依赖的？如果是依赖链路上的，那是不是 umi，都会死循环吧。

**Comment by sorrycc** [comment]
我不清楚，这是 webpack 内部逻辑，你可以去 webpack 文档里找找，然后通过 chainWebpack 修改 webpack 配置。
