### ISSUE TITLE
umi-request 不能获取跨域请求的自定义response headers信息

### ISSUE THREAD

**Issue by tangniyuqi** [umijs/umi#2793]
能获取到数据，但不能获取到自定义header信息

![image](https://user-images.githubusercontent.com/5830538/60942438-31673980-a315-11e9-96b9-45c5d4bf5473.png)

![image](https://user-images.githubusercontent.com/5830538/60942507-74c1a800-a315-11e9-93fe-3e77d745d1e7.png)

**Comment by ycjcl868** [comment]
headers 参数里没有？

**Comment by tangniyuqi** [comment]
> headers 参数里没有？

是有的，我用axios 都能正常获取

**Comment by ycjcl868** [comment]
能给个 umi-request 使用例子吗？

**Comment by tangniyuqi** [comment]
const { data, response } = yield call(queryGoods);
yield put({ type: 'query', payload: data });

console.log('count:', response.headers.get('x-pagination-total-count'))

**Comment by tangniyuqi** [comment]
原来要这样才能获取。。文档没说明。

**Comment by clock157** [comment]
如果你要在结果中用到response，需要增加参数 getResponse: true
```js
request('/api/v1/some/api', { getResponse: true }).then({data, response} => {
  response.headers.get('');
});
```

**Comment by shaodushu** [comment]
@clock157 非常感谢，不过之前就已经试过了，是我操作不对嘛

![image](https://user-images.githubusercontent.com/26360246/61588582-b1708780-abd0-11e9-8d0b-efd6a4260ade.png)

![image](https://user-images.githubusercontent.com/26360246/61588592-f7c5e680-abd0-11e9-9bb1-bf70ded7d25d.png)

![image](https://user-images.githubusercontent.com/26360246/61588595-03b1a880-abd1-11e9-80ef-68a7ce97523b.png)

**umi-request版本：**

![image](https://user-images.githubusercontent.com/26360246/61588646-ee894980-abd1-11e9-82e3-887d5b33a108.png)

**Comment by shaodushu** [comment]
需要在服务器设置 Access-Control-Expose-Headers，浏览器才能获取自定义headers

**Comment by JuniorGR** [comment]
我也遇到了类似的问题，在设置了getResponse: true后，返回的response对象的headers中只能get到我发起请求时设置的一个header，一些最基本的返回如Content-Length，Date这些均无法获取到，一个我希望获取的header的get结果也为null，但是chrome查看请求时这些返回均可获取到，有人解决了这个问题吗？
umi-request版本为1.0.7

**Comment by JuniorGR** [comment]
> @clock157 非常感谢，不过之前就已经试过了，是我操作不对嘛
> 
> ![image](https://user-images.githubusercontent.com/26360246/61588582-b1708780-abd0-11e9-8d0b-efd6a4260ade.png)
> 
> ![image](https://user-images.githubusercontent.com/26360246/61588592-f7c5e680-abd0-11e9-9bb1-bf70ded7d25d.png)
> 
> ![image](https://user-images.githubusercontent.com/26360246/61588595-03b1a880-abd1-11e9-80ef-68a7ce97523b.png)
> 
> **umi-request版本：**
> 
> ![image](https://user-images.githubusercontent.com/26360246/61588646-ee894980-abd1-11e9-82e3-887d5b33a108.png)
我也遇到了类似的问题，在设置了getResponse: true后，返回的response对象的headers中只能get到我发起请求时设置的一个header，一些最基本的返回如Content-Length，Date这些均无法获取到，一个我希望获取的header的get结果也为null，但是chrome查看请求时这些返回均可获取到，有人解决了这个问题吗？
umi-request版本为1.0.7

**Comment by JuniorGR** [comment]
我也遇到了类似的问题，在设置了getResponse: true后，返回的response对象的headers中只能get到我发起请求时设置的一个header，一些最基本的返回如Content-Length，Date这些均无法获取到，一个我希望获取的header的get结果也为null，但是chrome查看请求时这些返回均可获取到，有人解决了这个问题吗？
umi-request版本为1.0.7

**Comment by Nasaakaa** [comment]
is there any solutions on this problem? @tangniyuqi

**Comment by ctq123** [comment]
感觉都没有解决问题就被关掉了

**Comment by ctq123** [comment]
问题解决了，必须通过headers.get()方法的形式获取字段。
```js
// 获取headers中自定义的abc属性
request('/api/v1/some/api', { getResponse: true }).then({data, response} => {
  response.headers['abc']; // fail
});
```

```js
// 获取headers中自定义的abc属性
request('/api/v1/some/api', { getResponse: true }).then({data, response} => {
  response.headers.get('abc'); // success
});
```
