### ISSUE TITLE
umi-build-dev 依赖 react-router 固定版本

### ISSUE THREAD

**Issue by iShawnWang** [umijs/umi#2795]
## What happens?
项目已经升级到 react-router 5.x

但是 [umi-build-dev](https://github.com/umijs/umi/blob/46b9cbaea2e236e24407a89587824455352dbac6/packages/umi-build-dev/package.json#L45)

锁了 4.3.1 版本, 然后会有这个报错 `"export '__RouterContext' (imported as 'RouterContext') was not found in 'react-router'`

希望可以移除这个依赖, 或者改成 peerdependencies

**Comment by sorrycc** [comment]
基于 umi 的项目为啥要自己依赖 react-router? 锁定 4.3.1 是符合预期的，等 umi@3 才会升级到 5。

**Comment by iShawnWang** [comment]
emmmmm 是为了用 Hooks, 所以自己升级了 `react-router` 和 `react-router-dom`

**Comment by videni** [comment]
@iShawnWang , I also want to use the __RouterContext, how do  you solve it currently?

**Comment by iShawnWang** [comment]
@videni https://gist.github.com/iShawnWang/fddaa66f0090133fd8d42cc363a7e6d4
