### ISSUE TITLE
使用Mock功能不能自动更新吗？需要重启目录！

### ISSUE THREAD

**Issue by Lemonreds** [umijs/umi#2796]
## What happens?

使用Mock功能不能自动更新吗？需要重启目录，还是说我的用法有问题？

## 最小可复现仓库

无，如上问题。

## 复现步骤，错误日志以及相关配置

无，如上问题。

## 相关环境信息

无，如上问题。

**Comment by xiaohuoni** [comment]
重启目录是指什么？
mock文件有监听服务的

**Comment by Lemonreds** [comment]
@xiaohuoni  我也看到控制台有这个输出:
√  success   Mock files parse success，但是结果一样哦，需要重新跑 npm run dev 命令重启后才生效。。

**Comment by XuZhaoTong** [comment]
> @xiaohuoni 我也看到控制台有这个输出:
> √ success Mock files parse success，但是结果一样哦，需要重新跑 npm run dev 命令重启后才生效。。
+1 最近我也碰到了这个问题，√ success Mock files parse success后，Mock的接口没有效果，需要重新启一下才能生效。

**Comment by xiaohuoni** [comment]
尝试了一下umi@2.8.10，我这里可以修改后立即有效。能提供一下重现步骤吗？
包括环境什么的

**Comment by Lemonreds** [comment]
@xiaohuoni 我这边是 umi@2.4.3 ，看来有可能是版本的bug！
步骤大概是：
1。 mock 文件夹下新建或者编辑已经有的mock文件。
2。 控制台显示 √ success Mock files parse success。
3。 请求刚刚编辑的mock无效，没有返回数据。

**Comment by xiaohuoni** [comment]
@Lemonreds mac吗？

**Comment by XuZhaoTong** [comment]
> @Lemonreds mac吗？

我这里是win10，这是根据我的项目删减出来的demo，能复现。https://github.com/XuZhaoTong/Mock-Demo

**Comment by Lemonreds** [comment]
@xiaohuoni @XuZhaoTong 是win10

**Comment by sorrycc** [comment]
我猜是 windows 下的 BUG，可能和路径有关。

**Comment by OxPatient** [comment]
我这里也遇到同样的问题，就是最近一周才出现的，之前还好好的。 @XuZhaoTong
