### ISSUE TITLE
在vscode中创建umi项目报错

### ISSUE THREAD

**Issue by mushroomlb** [umijs/umi#2799]
## What happens?
在vscode中创建umi 项目，多次尝试均报错，如下图1，但是用命令行创建就不报错，如图2

## Mini Showcase Repository(REQUIRED)
图1
![image](https://user-images.githubusercontent.com/1701771/61094972-2848aa80-a484-11e9-8c4b-b7288cb6563e.png)

图2
v10.16.0
![image](https://user-images.githubusercontent.com/1701771/61095087-a311c580-a484-11e9-845b-b55271b74cd3.png)

## Context
- **Umi Version**:0.13.7
- **Node Version**:v10.16.0
- **Platform**:windows 7

**Comment by xiaohuoni** [comment]
试试sudo？

**Comment by mushroomlb** [comment]
在windows平台下，本身就是管理员，有权限
