### ISSUE TITLE
umi-plugin-qiankun not support gloal style

### ISSUE THREAD

**Issue by DiamondYuan** [umijs/umi#2801]
![image](https://user-images.githubusercontent.com/9692408/61101578-e37d3d80-a49c-11e9-871e-4bfdd8b5e618.png)

![image](https://user-images.githubusercontent.com/9692408/61101583-e841f180-a49c-11e9-9c99-2c6e48460f65.png)

样式不生效

**Comment by nguyenhuutinh** [comment]
should be className={styles.normal}

**Comment by kuitos** [comment]
插件的实现里没有把子应用的样式带过来，需要处理下
