### ISSUE TITLE
ssr动态路由依旧有问题

### ISSUE THREAD

**Issue by hoverCow1990** [umijs/umi#2805]
> 感觉问题在**umi-build-dev/lib/findRoute.js**下**findRoute**函数下22行

我的路由配置会在递归中的第一个有routes那级就断了，不会往下继续匹配

````javascript
if (route.routes) {
     return findRoute(route.routes, path)
 }
````

> 在**umi-build-dev/lib/template/entry.js.tpl**中**findRoute**基本都是false

````javascript
const activeRoute = findRoute(require('./router').routes, pathname) || false;

````

我的路由配置如下，放开注释部分二级目录博之, 就会导致之后count无法被匹配到

````javascript
const routerConfig = [
  {
    path: '/',
    component: '../layout/BasicLayout',
    routes: [
      {
        name: 'home',
        znName: '主页',
        path: '/',
        component: './index',
      },
      {
        name: 'users',
        znName: '用户',
        path: '/users',
        component: './users',
        icon: 'file-add',
        // Routes: ['src/pages/RouterAuthorized'],
        // routes: [
        //   {
        //     name: 'bozhi',
        //     znName: '博之',
        //     path: '/users/bozhi',
        //     component: './users',
        //   },
        // ],
      },
      {
        name: 'count',
        znName: '次数',
        path: '/count',
        component: './count',
      }
    ]
  }
]
````

**Comment by ycjcl868** [comment]
我看下

**Comment by hoverCow1990** [comment]
> 我看下

Next里的getInitialProps是可以获取参数req的, 目前umi中的getInitialProps中参数只接受route, isServer, initialProps 我无法在其中操作ctx 是否可以考虑把ctx作为参数

**Comment by ycjcl868** [comment]
req 传进去的话，走客户端渲染 req 是不存在的。

**Comment by hoverCow1990** [comment]
> req 传进去的话，走客户端渲染 req 是不存在的。

这个问题，开发者可以对当前环境或者isServer进行判断处理，我目前有个需求就是在我服务端发送请求时，若token失效需要对当前路由重定向去接口返回的sso地址，但是由于在getInitialProps中我无法操作window, 也无法用ctx重定向, 有点无助. 

目前我能想到的是return 一个特定值出去，然后在服务端用rootContainer.props.children.props获取返回值来进行判断, 但我觉得是不是可以有更好的方式来解决这个问题

**Comment by hoverCow1990** [comment]
> req 传进去的话，走客户端渲染 req 是不存在的。

**Comment by ycjcl868** [comment]
发请求用同构 request libraray，这样保持前端数据 store 与服务端 store 获取方式一致。

**Comment by ycjcl868** [comment]
getInitialProps 为什么要操作 window?

**Comment by hoverCow1990** [comment]
参考了Next.js文档 我想要的就是如下服务端钩子重定向的效果, 但目前umi提供的route, isServer, initialProps三个入参无法满足需求

```jsx
const Page = () => <div>博之有个基友叫 朱泽亮 </div>

Page.getInitialProps = async ({ pathname, query, req, res }) => {
  const next = await fetch('https://xxxxxxxxxx')
  const data = await next.json()
  const { code, redirect_url } = data.body
  
  // 3002为登陆失效需要重定向去sso地址
  if (code === 3002) {
    // 只有服务端才有res这个入参
    res ? res.redirect(redirect_url) : window.location.href = redirect_url
  }
}

export default Page
```

**Comment by hoverCow1990** [comment]
> getInitialProps 为什么要操作 window?

还有感谢fix: findRoute recursive bug #2812的修复, 目前升级后动态路由已可正常使用 ^_^

**Comment by ycjcl868** [comment]
getInitialProps 需要的参数再提个 issue 吧，我跟进下。

**Comment by hoverCow1990** [comment]
> getInitialProps 需要的参数再提个 issue 吧，我跟进下。

好, 感谢🙏
