### ISSUE TITLE
umi block不支持code.aliyun.com

### ISSUE THREAD

**Issue by chj-damon** [umijs/umi#2808]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
在 https://github.com/umijs/umi/issues/2816 跟进。
