### ISSUE TITLE
有些第三方插件没有编译成es5

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#281]
有些第三方插件没有编译成es5
或者使用了一些es6的方法，如Map，Set
在global.js中使用 import 'core-js/es6/map' 不能修复这个问题，
请问怎么处理

**Comment by sorrycc** [comment]
试试 [extraBabelIncludes](https://umijs.org/docs/zh-Hans/config-webpack.html#extrababelincludes) ?

**Comment by xiaohuoni** [comment]
在global.js中有效，项目中umi版本过低。
