### ISSUE TITLE
[Feature Request] How can I send props of layout to children elements?

### ISSUE THREAD

**Issue by nguyenhuutinh** [umijs/umi#2810]
Hello team

I want to share the props: isMobile defined in layout to all children pages. 

but the props of children always is from router.

is it posible to send the custom props to their children pages?
tried with cloneelement but it not work
const children = React.Children.map(props.children, child => {
    return React.cloneElement(child, {
      isMobile : true 
    });
  });

**Comment by ycjcl868** [comment]
Switch not pass `props` into children Component

![image](https://user-images.githubusercontent.com/13595509/61197645-b3d26d80-a708-11e9-81d0-0bcf86cc64f7.png)

I sugguest that you can do using `Context`, you can get props in any children Component:

```js
export const ReactContext = createContext({
  isMobile: true,
})

// layout
class Bar extends Component {
  render() {
    return (
      <ReactContext.Provider value={{ isMobile: true }}>
       {this.props.children}
      </ReactContext.Provider>
    )
  }
}

// children
import { ReactContext } from '../layout/index';

const ChildrenComp = (props) => {

  const { isMobile } = useContext(ReactContext);

  console.log('children isMobile', isMobile);

  return (
    ...
  )
}
```

**Comment by nguyenhuutinh** [comment]
thanks
