### ISSUE TITLE
[Feature Request] publicPath  如何在 page 里面代码使用。

### ISSUE THREAD

**Issue by xgj1988** [umijs/umi#2813]
## Background

我程序运行的过程中，就比如antd pro 的color.less这个文件，如果我要在程序运行中动态添加link 或者script，我如果拿到publicPath去拼接呢？谢谢。

## Proposal

程序是否能拿到umi的变量。

**Comment by sorrycc** [comment]
配 publicPath，然后额外通过 define 传入一份 publicPath 进去给代码用。
