### ISSUE TITLE
如果routes的配置信息存储在数据库，前端该如何绑定？

### ISSUE THREAD

**Issue by htank-wang** [umijs/umi#2814]
**需求是路由和组件解绑，由用户在界面任意配置关系。流程如下：**
1.页面加载，请求用户配置的路由信息,如：
   {
            path: '/system/userManage',
            name: 'userManage',
            component: './System/UserManage/Index',
          },
2.将此信息进行组装，component由路径转换为动态路由。
3.转换完成的信息，追加到routes的指定位置。

**这里有两个问题：**
1.现在的routes在构建前指定，在哪里可以获取并追加（最好有model的动态注入）？
2.这样做动态组件加载，会不会存在组件没有构建到源码里？毕竟我这个组件开发阶段是没有任何地方被依赖。

**Comment by ycjcl868** [comment]
我理解是动态生成前端路由，这个在服务端去加，前端提供通用模板路由即可。

**Comment by htank-wang** [comment]
"通用模板路由" 这个能具体说一下吗？
我举个栗子：
1.路由数据
![image](https://user-images.githubusercontent.com/17918845/61350099-f62ab480-a898-11e9-8cdd-198679b22ad9.png)
2.应该可以从服务端获取红框内的数据放到这个位置：
![image](https://user-images.githubusercontent.com/17918845/61350261-89fc8080-a899-11e9-9eaf-fcc5258fec70.png)
当然组件部分会解析成动态组件加载。另外还涉及models的绑定。

**Comment by ycjcl868** [comment]
这个可以配置一个模板路由：`{ path: '/dashboard/:id', component: 'Bar' }` ，

服务端存储 `[{ path: '/dashboard/bar' }, { path: '/dashbaord/foo' }]`，菜单出是动态读服务端的数据展示出来。

**Comment by htank-wang** [comment]
component: 'Bar'  那这里的Bar组件就是一个容器了，根据id加载不同的业务组件。

这个方法貌似只能解决少部分问题：
1."/dashbaord/foo"可能有子路由。可能是N级.
2."/dashbaord/foo"可能要重定向。"/dashbaord/foo"=》"/dashbaord/page1"
3."/dashbaord/foo"本身又是带参的。
等等...
另外按照以上方法在开发阶段来说，一个页面开发完成，开发必须在模板路由Bar里面做好id和页面的映射。

是不是框架内有这样一个功能：
1.有个菜单配置界面
2.新增菜单时指定菜单的具体名称，icon，path，component路径(框架内部自动生成)。
3.加载layout容器时，根据菜单信息生成对应的路由（routes里追加这部分信息，component由路径改成动态组件加载）。

以上可能涉及到部分业务，但是如果能处理routes和component动态组件。
比模板路由更灵活，相当于路由完全由界面操作定制，框架内部也不需要写映射关系。

**Comment by htank-wang** [comment]
分开打包：微前端我这边业务场景可能暂时不行，后面会采用渐进式开发。
一起打包：是不是问题有点复杂化了。

设想的目的是除了框架本身的路由以外。其它部分的路由（特别是业务模块）与框架解耦。
框架生产组件，用户配置路由与组件关系。灵活定制项目的菜单。

我还在尝试，目前可以达到类似的目的。但是还是有BUG。

**Comment by sorrycc** [comment]
我的建议是思路 2。有问题再 reopen 吧，搞出来后也可以整理下最佳实践。

**Comment by htank-wang** [comment]
类似的项目已经有了，不过不是我写的。可以参考一下：
https://github.com/zhangdaiscott/jeecg-boot
