### ISSUE TITLE
如何禁止开发服务器启动后，自动把地址复制到剪切板

### ISSUE THREAD

**Issue by hayderGo** [umijs/umi#2815]
## Background

每次启动开发服务器，都会自动复制开发服务器的地址导致我自己的剪切板记录被覆盖，造成了许多不便。
![image](https://user-images.githubusercontent.com/23020389/61263994-7da2f580-a7bd-11e9-9297-8a58bd1011ff.png)

## Proposal

1.希望能够默认不做剪切板的操作，或者能够提供个配置选项。
2.为什么不直接使用 webpack devServer的open功能直接打开一个浏览器窗口呢？https://webpack.js.org/configuration/dev-server/#devserveropen；
而且我使用umi的devServer配置了open也没有生效。https://umijs.org/zh/config/#devserver

## Additional context

umi版本: 2.8.11

**Comment by sorrycc** [comment]
检查 `.env` 文件，把 `BROWSER=none` 去掉就会自动打开，去掉复制到粘贴板这个先不考虑吧，有类似反馈的很少。

**Comment by ShinChven** [comment]
> 
这个功能经常导致我粘贴板里的数据丢失
