### ISSUE TITLE
Umi block list failed 

### ISSUE THREAD

**Issue by kwzm** [umijs/umi#2818]
## What happens?
When I execute `umi block list` show the errors as follows:
![捕获](https://user-images.githubusercontent.com/16114101/61354315-7d315a00-a8a4-11e9-8de8-500704f23c76.PNG)
I think it's because of the Internet, my company use proxy, how can I set the proxy, I tried `set http_proxy` but didn't work.
## Context

- **Umi Version**: 2.8.7
- **Node Version**: 10.13.0
- **Platform**:win7 64bit

**Comment by lpp18** [comment]
没人解决吗？我也遇到这个问题了
