### ISSUE TITLE
同时启用umi-plugin-dll 和externals时报错

### ISSUE THREAD

**Issue by elivoa** [umijs/umi#282]
启用 umi-plugin-dll 
并且配置了
```
externals: {
  "react": "window.React",
  "react-dom": "window.ReactDOM",
},
```

会报错，原因是有两个react被引入。

**Comment by sorrycc** [comment]
dll 打入一个，然后自己又引了一个？

**Comment by elivoa** [comment]
我在.webpackrc.js中externals配置了 react和react-dom，然后在首页用script标签引入了这两个js文件。
同时使用了umi-plugin-dll, 这样导致了两套react同时引入了。

配置了externals时dll也应该忽略externals吧。

**Comment by sorrycc** [comment]
优先级低。
