### ISSUE TITLE
引入不同的css文件

### ISSUE THREAD

**Issue by xlei1123** [umijs/umi#2823]
根据业务需要 配置不同主题色， 怎么引入不同的本地css文件？

**Comment by sorrycc** [comment]
生产环境的多主题切换没试过，不在 umi 的能力范围之内，自己尝试吧。应该是要构建多次生产不同的 css 文件吧。

**Comment by xlei1123** [comment]
`js
if (this.getPlatebyUrl() == 'a') {
      require (`../assets/less/a.less`);
    } else if(this.getPlatebyUrl() == 'b') {
      require (`../assets/less/b.less`);
    }
`
--------------------------------------------------------------
这个两个文件都引入了， 为啥？
