### ISSUE TITLE
请问 mock 数据的参数文档哪有？

### ISSUE THREAD

**Issue by javahuang** [umijs/umi#2825]
官方的 [Mock 数据](https://umijs.org/zh/guide/mock-data.html#mock-%E6%95%B0%E6%8D%AE) 文档里面好像并没有哦 req 和 res 的 api 啊，请教下大家在哪里可以找到。

**Comment by sorrycc** [comment]
参考 [express 的 API](https://expressjs.com/en/4x/api.html#req)。
