### ISSUE TITLE
npm install Error: Cannot find module 'webpack'

### ISSUE THREAD

**Issue by zlyyyy** [umijs/umi#2827]
## Context
npm install 报错如下图
![image](https://user-images.githubusercontent.com/22760932/61463226-8efb2600-a9a6-11e9-87ac-30bb5cb146ef.png)

- **Umi Version**:2.8.7
- **Node Version**:8.11.4
- **Platform**:

**Comment by zlyyyy** [comment]
就正常npm install。。。不得行，这个也要再现嘛

**Comment by zlyyyy** [comment]
在umi build时开始报错

**Comment by zlyyyy** [comment]
试了下装一下npm install webpck再执行npm install就ok了。但是我还是想知道为什么会出现这个问题

**Comment by sorrycc** [comment]
依赖没装好吧，如果确认不是依赖安装的问题，给复现步骤。
