### ISSUE TITLE
关于 umi dev & umi build 运行版本问题

### ISSUE THREAD

**Issue by li2215890610** [umijs/umi#2830]
## What happens?

最近开发用umi开发了两个项目，用的2.6.17 看到umi 更新到了2.8，想升级umi版本开发新的项目，但是害怕一个问题，umi版本不向下兼容，2.8 umi build  2.6.17的项目会出现bug。

我用Taro开发小程序的时候遇到过高版本不兼容低版本，我用了下面的这种办法

npm install  @tarojs/cli@1.3.4 
在本地安装一个指定版本，在package.json 脚本里面指定运行项目 node_modules 里面的 cli

![image](https://user-images.githubusercontent.com/19567679/61471496-6b8ba780-a9b5-11e9-97bb-82b101be5554.png)

然后编译小程序的时候就会按照我指定脚本中的node_modules里面的脚手架去编译项目。

![image](https://user-images.githubusercontent.com/19567679/61472080-53685800-a9b6-11e9-9188-4a87cfec82aa.png)

我想问一下，

umi 有没有类似的方式加载指定版本？

我在看package.json中看到了

![image](https://user-images.githubusercontent.com/19567679/61472267-ae01b400-a9b6-11e9-966d-7d4552e27618.png)

这里有指定版本，我运行项目的时候，执行的是 package.json --》 devDependencies --》umi 安装包，还是 我-g安装的cli ？

**Comment by ycjcl868** [comment]
1. 不要全局安装，安装在项目的 devDeps 里，使用直接 `umi dev`
1. `umi` `umi-plugin-react` 最好同时升级。
1. 若有包之间上下不兼容改动，会发 `minor`，整体升级即可。

**Comment by li2215890610** [comment]
你好 
比如这个图，在packgae.json 里面 安装的有 umi umi-plugin-react，那我启动 sudo umi dev 走的是全局的安装包，还是devDeps里面的安装包呢？

![](https://user-images.githubusercontent.com/19567679/61472267-ae01b400-a9b6-11e9-966d-7d4552e27618.png)

**Comment by li2215890610** [comment]
> 1. 不要全局安装，安装在项目的 devDeps 里，使用直接 `umi dev`
> 2. `umi` `umi-plugin-react` 最好同时升级。
> 3. 若有包之间上下不兼容改动，会发 `minor`，整体升级即可。

你好
比如这个图，在packgae.json 里面 安装的有 umi umi-plugin-react，那我启动 sudo umi dev 执行的是全局的安装包，还是devDeps里面的安装包呢？

![](https://user-images.githubusercontent.com/19567679/61472267-ae01b400-a9b6-11e9-966d-7d4552e27618.png)

我看了node_modules 里面的代码，好像是走的node_modules里面的umi，但是还是不确定。

**Comment by li2215890610** [comment]
谢谢了

**Comment by li2215890610** [comment]
> 1. 不要全局安装，安装在项目的 devDeps 里，使用直接 `umi dev`
> 2. `umi` `umi-plugin-react` 最好同时升级。
> 3. 若有包之间上下不兼容改动，会发 `minor`，整体升级即可。

有一个建议希望你们采纳，能不能搞一个类似于 taro运行的版本号输出在cmd里面，类似于下面

![image](https://user-images.githubusercontent.com/19567679/61507383-18970c00-aa18-11e9-91c8-239e0cf8a123.png)

每次运行 umi dev 或者 umi build  输出一下项目依赖的umi版本号。

**Comment by xiaohuoni** [comment]
```
sudo umi dev
```
执行的是全局的包，你要在package里面写类似
```
start:umi dev
```
然后用 `yarn start`，用的才是项目里的包。
然后umi，用高版本编译低版本，没出现什么问题。
所以应该没必要运行版本。

**Comment by li2215890610** [comment]
> ```
> sudo umi dev
> ```
> 
> 执行的是全局的包，你要在package里面写类似
> 
> ```
> start:umi dev
> ```
> 
> 然后用 `yarn start`，用的才是项目里的包。
> 然后umi，用高版本编译低版本，没出现什么问题。
> 所以应该没必要运行版本。

感谢感谢 
我指定了固定版本，现在是运行本地的包。
不升级的原因，因为以前踩过坑， 哈哈。
总之谢谢。

**Comment by xiaohuoni** [comment]
不客气
