### ISSUE TITLE
在全局model下监听路由执行dispatch，跳转路由，路由会跳转多次。第一次会跳转到目标路由，第二次回到当前路由，第三次到目标路由

### ISSUE THREAD

**Issue by yuhang1995** [umijs/umi#2833]
## What happens?

在全局model下监听路由执行dispatch，跳转路由，路由会跳转多次。第一次会跳转到目标路由，第二次回到当前路由，第三次到目标路由 

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：2.7.0
- **Node 版本**：8.10.0
- **操作系统**：win10

**Comment by sorrycc** [comment]
请提供复现步骤。

**Comment by yuhang1995** [comment]
> ## What happens?
> 在全局model下监听路由执行dispatch，跳转路由，路由会跳转多次。第一次会跳转到目标路由，第二次回到当前路由，第三次到目标路由
> 
> ## 最小可复现仓库
> > 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库
> 
> ## 复现步骤，错误日志以及相关配置
![image](https://user-images.githubusercontent.com/31569789/61506603-32831f80-aa15-11e9-9f3b-2c8abd0e34db.png)
图1
![image](https://user-images.githubusercontent.com/31569789/61506615-3d3db480-aa15-11e9-994b-6551c186a052.png)
图2
![image](https://user-images.githubusercontent.com/31569789/61506665-6cecbc80-aa15-11e9-9851-e1ba4356a994.png)
图3

如上图所示：在page2跳转到page1，在全局的model中监听路由（图3所示）

> ## 相关环境信息
> * **Umi 版本**：2.7.0
> * **Node 版本**：8.10.0
> * **操作系统**：win10

**Comment by sorrycc** [comment]
我如何复现？

**Comment by yuhang1995** [comment]
不好意思，仓库：https://github.com/yuhang1995/umi-demo.git

**Comment by zouliang073** [comment]
我也是这个问题，关注下

**Comment by zouliang073** [comment]
在subscriptions中执行dispatch会导致这样的情况，找到原因了，但为何会出现这种状况还未知

**Comment by sorrycc** [comment]
在 #2693 跟进，相同问题。
