### ISSUE TITLE
watch changes in node_module

### ISSUE THREAD

**Issue by videni** [umijs/umi#2835]
how to watch changes in node_nodule?  configure here not working

plugin.config.ts
```
  config.devServer
    .watchOptions({
      ignore: [/node_modules([\\]+|\/)+(?!react-router)/]
    });
```

I also remove all places  the node_module directory is excluded  in the af-webpack, still not working, why?

 here are what I did

1. remove all places the watchOptions is present
2. restart by yarn start.
3. changes  made in a file doesn't show in the browser side.

**Comment by xiaohuoni** [comment]
you can try it! but why should we watch node_modules？

config/config.js
``` 
plugins: [
        [`${__dirname}/plugin`,],
    ],
```
config/plugin.js
```
export default function (api, option = {}) {
  console.log('plugin success');
  api.addPageWatcher(['xxx.js', '*.mock.js']);
}
```

**Comment by videni** [comment]
@xiaohuoni , thanks, but it doesn't work.  I also asked [here](https://stackoverflow.com/questions/57106052/why-file-changes-in-node-module-not-show-at-browser). 

The ready why I want to do this because something doesn't work as expected,  I have to debug it at runtime, no matter what I do , changes in node_module just doesn't show at browser side.
