### ISSUE TITLE
umi build后，怎么将 umi.css 和 umi.js 的路径改为绝对路径，publicPath 设置无效

### ISSUE THREAD

**Issue by Lmisaka** [umijs/umi#2837]
本地是umi build到springboot项目的public目录下，目前给别人调用的时候获取不到
umi.css和umi.js 这两个文件，目前publicPath 设置为'http://localhost:8888/site/'无效
![image](https://user-images.githubusercontent.com/16377488/61519899-9a4e6000-aa3f-11e9-861d-e664b3ce8ea8.png)

相关环境信息
Umi 版本：2.8.7
Node 版本：v10.12.0
操作系统：win10

**Comment by Lmisaka** [comment]
期望值是http://localhost:8888/site/umi.css 和http://localhost:8888/site/umi.js

**Comment by Ivocin** [comment]
可以提供你配置 publicPath 的截图看一下

**Comment by Lmisaka** [comment]
![image](https://user-images.githubusercontent.com/16377488/61531001-32f0da00-aa58-11e9-906f-87ba2fa30f8a.png)

**Comment by Lmisaka** [comment]
> 可以提供你配置 publicPath 的截图看一下
我是采用config.js文件配置的
![image](https://user-images.githubusercontent.com/16377488/61532162-8b75a680-aa5b-11e9-8496-1dbfcfdc4031.png)

**Comment by ycjcl868** [comment]
publicPath 不要加 http，直接 `/site/`

**Comment by Lmisaka** [comment]
> publicPath 不要加 http，直接 `/site/`

你好，按照你的修改了，还是不行还是生成这样的格式
![image](https://user-images.githubusercontent.com/16377488/61533391-553a2600-aa5f-11e9-9391-ecf4a3642f67.png)

**Comment by Lmisaka** [comment]
想问下我这个网页嵌入到别人的网页中，会影响这个访问的上下文吗，就是umi.js 和umi.css请求的是别人的服务器还是我的服务器？

**Comment by Lmisaka** [comment]
目前是可以了除了pwa的文件
