### ISSUE TITLE
静态导出后与开发时运行效果不一致

### ISSUE THREAD

**Issue by ShaneKing** [umijs/umi#284]
@sorrycc 大神，静态导出后与开发时运行效果不一致，这个有木有sourcemap一样的东东可以调试啊？？？

导出后丢nginx里效果（输入框icon图标木有了，还有错误信息也不展现）
![image](https://user-images.githubusercontent.com/3394899/38163804-a54d86f4-352c-11e8-8857-9f06f0a85787.png)
开发时效果
![image](https://user-images.githubusercontent.com/3394899/38163816-d69ea0a8-352c-11e8-8d25-fb412313f527.png)

**Comment by sorrycc** [comment]
> 这个有木有sourcemap一样的东东可以调试啊？？？

在 .webpackrc 里配 devtool: 'source-map'

> 效果不一致

给个可重现的库。

**Comment by ShaneKing** [comment]
@sorrycc 

sk-user库的umi#284分支
https://github.com/ShaneKing/sk-user/tree/umi%23284

安装依赖
npm install

开发模式启动
npm run dev
访问：http://localhost:8000/auth

静态导出
npm run build
dist丢到nginx里，访问：http://localhost/auth

**Comment by sorrycc** [comment]
有问题再 reopen 。

**Comment by ShaneKing** [comment]
@sorrycc 昨天试了一下，还是一样。就不重新给库了，还请帮忙看下～～～

**Comment by xiaohuoni** [comment]
![171708](https://user-images.githubusercontent.com/11746742/39806561-c8f485e6-53ac-11e8-8dc3-8814e130b5e6.png)

**Comment by ShaneKing** [comment]
@xiaohuoni 

sk-user库的umi#284分支
https://github.com/ShaneKing/sk-user/tree/umi%23284

**Comment by ShaneKing** [comment]
@sorrycc @xiaohuoni 
大神们，麻烦帮忙see1see啊～
新分支：https://github.com/ShaneKing/sk-user/tree/umi%23284new

**Comment by ShaneKing** [comment]
原因找到了。
因为代码中用到了Component.name，开发阶段name是Icon，编译后变成了t这种的。。。
