### ISSUE TITLE
升级至 2.8.12 报错 Error: Cannot find module 'eslint-config-prettier/@typescript-eslint' 

### ISSUE THREAD

**Issue by Jack-Sparrow** [umijs/umi#2840]
2.8.11 升级至 2.8.12，dev 和 build 均报该错  Error: Cannot find module 'eslint-config-prettier/@typescript-eslint' ，回复版本至 2.8.11 问题消失

**Comment by ycjcl868** [comment]
重装依赖，如果用了 cpm， 同步下模块

**Comment by fengbozhi** [comment]
遇到同样的问题，版本降只2.8.11，可以避免该问题。

**Comment by 3478349671** [comment]
我也遇到这个问题，重装依赖也同样报这个错误，只能降级到2.8.11

**Comment by ycjcl868** [comment]
@chenshuai2144  cc

**Comment by sorrycc** [comment]
复现步骤呢？

**Comment by archerU** [comment]
降级以后，仍然报错，何解

**Comment by DuduStyle** [comment]
@sorrycc umi脚手架创建工程，删除本地npm的缓存文件，保证eslint-config-prettier的版本是`"eslint-config-prettier": "^3.0.1"`,即可复现

**Comment by huaibaomengxiang** [comment]
同样的问题

**Comment by chenshuai2144** [comment]
eslint-config-prettier 这个库删掉就好了。

**Comment by huaibaomengxiang** [comment]
同样的问题
![图片](https://user-images.githubusercontent.com/29159923/61617515-6a03fd00-ac9d-11e9-8818-93837c389bee.png)

**Comment by huaibaomengxiang** [comment]
相同的问题
"eslint-config-prettier": "^3.0.1",
![图片](https://user-images.githubusercontent.com/29159923/61617563-83a54480-ac9d-11e9-8d51-9a1d38210e17.png)

**Comment by chenshuai2144** [comment]
https://github.com/umijs/fabric/blob/fa1639963873b99c764bc670e6255dec96329258/package.json#L40

fabric 依赖了 4.0.1，旧版本的 pro 都是 3

**Comment by 904492381** [comment]
我是新手 遇到这个问题了 具体该怎么操作呀 详细一点谢谢

**Comment by 904492381** [comment]
@chenshuai2144   大神 具体该怎么操作呀 刚开始学习react

**Comment by WangJM001** [comment]
相同的问题
eslint-config-prettier删除后，我本机是好的，同事拉代码安装后就报同样的错误了，不知道为啥

**Comment by WangJM001** [comment]
stylelint-config-prettier这个依赖也是同样的问题，目前只能在项目中引用这两个包来解决了

**Comment by 3478349671** [comment]
升级umi 2.8.12以上， package.json里面并没有安装eslint-config-prettier，也是报这个错误，查看包依赖里面eslint-config-prettier这个包是在umi里面依赖的也无法删除啊
