### ISSUE TITLE
约定路由 & dva.js 页面级model，会生成不想要的路由

### ISSUE THREAD

**Issue by thomaszdxsn** [umijs/umi#2845]
## What happens?

约定路由 & dva.js 页面级model，会生成不想要的路由。

models文件夹下面的.js文件，也会生成路由。然后打开后是空白的。

## 复现步骤，错误日志以及相关配置

下面是`/pages/.umi/router.js`的内容

![image](https://user-images.githubusercontent.com/23616426/61577577-f25a9480-ab1b-11e9-8e64-583951c62805.png)

## 相关环境信息

我不确定这是bug还是缺陷。如果需要复现的话我会提供相关环境和仓库。

**Comment by sorrycc** [comment]
参考 https://github.com/umijs/create-umi/blob/master/lib/generators/app/templates/.umirc.js#L17-L25 配下 routes.exclude 。

**Comment by JoeYnnn** [comment]
umi3.0中没有这个配置，应该怎么去做
