### ISSUE TITLE
ssr渲染中是否不支持umi的routes配置

### ISSUE THREAD

**Issue by hoverCow1990** [umijs/umi#2846]
"umi": "^2.8.12",
"umi-plugin-react": "^1.9.0"

在umi配置中,若设置routes, 而不是根据文件路径自动配置,会导致无法正常服务端渲染(依旧是客户端渲染)? 是否目前还不支持？
```javascript
export default {
  ssr: true,
  manifest: {},
  // routes: [...], 注释之后可以正常服务端渲染
  ....
}
```
在不注释的情况下, 根据路由去配置, 页面显示没有任何问题，只是查看network时发现页面请求回来的为空html壳子, 渲染依旧依靠引入umi.js后触发

**Comment by ycjcl868** [comment]
给下复现步骤，ssr 里不做约定式路由和配置式的区分

**Comment by hoverCow1990** [comment]
排查了, 是我某处代码有问题～ 感谢

**Comment by 569202812** [comment]
@hoverCow1990 可否交流下umi ssr
