### ISSUE TITLE
React Native WebView 加载使用umi框架的单页应用，路由变化时，没有触发React Native WebView 的onNavigationStateChange事件

### ISSUE THREAD

**Issue by KingAmo** [umijs/umi#2847]
## What happens?
我是`React Native` 开发者，同事使用`umi`框架写的h5单页应用，放在`React-Native-WebView`中加载，问题是，当h5页面的路由变化时，没有触发`React-Native-WebView`的 `onNavigationStateChange`事件.

## How To Reproduce
**Steps to reproduce the behavior:**
1. 创建RN项目，安装`react-native-webview`
2. 使用`react-native-webview`加载 使用`umi`框架的h5页面
3. 使h5页面路由变化

**Expected behavior**
1. h5路由变化时触发`react-native-webview`的`onNavigationStateChange` 事件

## Context

- **Umi Version**:  ^2.6.3
- **Node Version**:
- **Platform**: Android、iOS

**Comment by sorrycc** [comment]
没写过 RN，这是会自动触发的？不会的话，在 app.js 里通过 onRouteChange 手动触发下，参考 https://umijs.org/guide/runtime-config.html#onroutechange

**Comment by xiaohuoni** [comment]
@KingAmo 这个会自动触发的，我测试了一下，使用hash和静态化html部署的形式，都会触发。

**Comment by xiaohuoni** [comment]
要不你试试这个地址？https://docs.alitajs.com/zh

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/61855215-3ff74880-aef2-11e9-8a1d-eb5dacdce9a1.png)

**Comment by KingAmo** [comment]
> @KingAmo 这个会自动触发的，我测试了一下，使用hash和静态化html部署的形式，都会触发。

是的，静态html肯定会触发； 我们改成`hash`后也会触发，问题是，必须使用`hash`...

**Comment by xiaohuoni** [comment]
@KingAmo 我说的不是静态html，我说的是html静态化 https://umijs.org/zh/guide/deploy.html#%E9%9D%99%E6%80%81%E5%8C%96

**Comment by KingAmo** [comment]
> @KingAmo 我说的不是静态html，我说的是html静态化 https://umijs.org/zh/guide/deploy.html#%E9%9D%99%E6%80%81%E5%8C%96

嗯，现在的问题是，单页应用，不使用html静态化，不使用`hash`，而是用默认的`history`来路由，无法触发。

**Comment by xiaohuoni** [comment]
为什么要不使用静态化，不是用hash？感觉是这个库的bug，和umi无关的。
https://github.com/react-native-community/react-native-webview/pull/551

**Comment by xiaohuoni** [comment]
就算是使用hash的情况，也是会有不会触发的情况，比如，umi的官网。用的是vue的技术。
`https://umijs.org/zh/config/#history` 你可以试试 `https://umijs.org` 也不会触发的

**Comment by Bensonyy** [comment]
> 没写过 RN，这是会自动触发的？不会的话，在 app.js 里通过 onRouteChange 手动触发下，参考 https://umijs.org/guide/runtime-config.html#onroutechange


遇到同样的问题 rn-webview 嵌入 基于 umi 写的 h5 不会触发 onNavigationStateChange，改成嵌入百度官网的 H5 会触发，

‘在 app.js 里通过 onRouteChange 手动触发下’，如何手动？
