### ISSUE TITLE
umi 2.8.12 约定式路由 Routes 配置出错

### ISSUE THREAD

**Issue by g770728y** [umijs/umi#2848]
## What happens?
在page/index.tsx里配置路由如下:
```
/**
*   Routes:
*      - ./routes/PrivateRoute.tsx
*/
export function () {
.....
```

在pages/.umi/routers.js里生成代码:
```
...
        Routes: [
          require('../../../routers/Private.tsx').default,   <== 路径多了一个".."!!!!
          require('./TitleWrapper.jsx').default,
        ],
...
```
如上, 生成的routers.js文件, 路径引用始终是错的
怀疑这跟现在umi增加了一层 `src` 目录有关 ( 老版是对的 ) 

## Context

- **Umi Version**: 2.8.12
- **Node Version**: 12.6.0
- **Platform**: mac

**Comment by sorrycc** [comment]
提供复现仓库。

**Comment by g770728y** [comment]
感谢回复! 
不好意思, 白天一直在忙.

---

重现步骤:
1.`yarn create umi`
2. 添加 `src/routes/PrivateRouter.tsx`
3. 在`pages/index.tsx`顶部配置`Routes: - ./routes/PrivateRouter.tsx`
4. yarn start, 查看 `.umi/router.js`
 
---

以下是重现repo: 
```https://github.com/g770728y/umi_bug_report_router```

**Comment by sorrycc** [comment]
Route 是从根目录开始找起的，可以用 `./src/routes/PrivateRoutes.tsx`。

**Comment by g770728y** [comment]
明白了, 感谢!
