### ISSUE TITLE
在运行时配置路由，路由信息从服务器拉取

### ISSUE THREAD

**Issue by buzhanhua** [umijs/umi#2849]
我的项目，权限交由后端处理， 需要我在运行时，在后台拉取数据，进行路由配置。目前遇到一些问题：

1. app.js 中 render函数 和 patchRoutes函数在这种有异步请求的情况下，如何配合使用？
2. 目前暂时实现了一下， 但是发现，之前在 umi-plugin-react中配置的，按需加载，现在不能生效，如果这种情况下，按需加载应该如何实现呢？
3. patchRoutes 函数除了可以更改路由，是否可以指定路由的layout呢？

**Comment by yutingzhao1991** [comment]
> app.js 中 render函数 和 patchRoutes函数在这种有异步请求的情况下，如何配合使用？

应该可以在 render 函数中去请求后端数据然后暂存起来，执行 patchRoutes 的时候可以拿到暂存的数据修改，但是这个感觉是个 hack 的方案...

> 目前暂时实现了一下， 但是发现，之前在 umi-plugin-react中配置的，按需加载，现在不能生效，如果这种情况下，按需加载应该如何实现呢？

按需加载只针对 config.js 中配置的路由有效，运行时的现在还做不到

> patchRoutes 函数除了可以更改路由，是否可以指定路由的layout呢？

可以，layout 就是通过路由配置嵌套实现的

**Comment by yutingzhao1991** [comment]
不过如果只是权限控制不一定通过修改路由来实现。

**Comment by buzhanhua** [comment]
> 不过如果只是权限控制不一定通过修改路由来实现。

是的，目前这么做，是因为有一套完善的权限系统可以使用， 使用这种方式可以和现在系统友好的结合起来。

对于patchRoutes中，配置路由时指定布局， 可以提供一个demo吗？想学习怎么实现的 @yutingzhao1991

**Comment by chenxiangdashen** [comment]
app.js 中  patchRoutes 引入对应的 component 后 ， model 只有 src/model的生效了， page/model 没有了，这种情况 该如何 将对应的model 注入啊？？？

**Comment by scm-Q** [comment]
我项目也遇到类似情况，权限是后端控制的；我现在做法是router.config.js只定义path与component的关系，在app.js 中patchRoutes 中将path对应component存储自己的格式；菜单导航自行实现基于权限数据，加载菜单功能时，实现自定义容器组件去加载component(菜单通过path作为关联字段，获取component动态组件). @buzhanhua

**Comment by scm-Q** [comment]
> app.js 中 patchRoutes 引入对应的 component 后 ， model 只有 src/model的生效了， page/model 没有了，这种情况 该如何 将对应的model 注入啊？？？

umi会在启动过程时会在src/pages/.umi/router.js，这里的每个组件动态加载包括了对应加载models，所以可以换种思路，在pathRoutes做过滤，而不是去加component，整个还是走框架默认的原则。

**Comment by gaorubin1990** [comment]
我们项目环境基本一样，一开始我也想在运行时修改路由配置，感觉后台返回菜单数据，可以在切换路由时通过这个返回数据校验权限问题。菜单显示通过这个返回数据展示。

**Comment by simonyouth** [comment]
不同的layout可以在index里根据pathname指定的，文档有，感觉能满足需求吧？

**Comment by ywy94ywy** [comment]
> > app.js 中 patchRoutes 引入对应的 component 后 ， model 只有 src/model的生效了， page/model 没有了，这种情况 该如何 将对应的model 注入啊？？？
> 
> umi会在启动过程时会在src/pages/.umi/router.js，这里的每个组件动态加载包括了对应加载models，所以可以换种思路，在pathRoutes做过滤，而不是去加component，整个还是走框架默认的原则。

我这里的场景无法做过滤，后端可能调整菜单结构，所以我不能定死后通过权限过滤菜单，这样的场景应该怎么处理呢

**Comment by ywy94ywy** [comment]
> app.js 中 patchRoutes 引入对应的 component 后 ， model 只有 src/model的生效了， page/model 没有了，这种情况 该如何 将对应的model 注入啊？？？

兄弟，这个情况解决了吗？我也碰到了

**Comment by ruanhailiang** [comment]
大家有解决方案了吗？分享一下

**Comment by Fengjing95** [comment]
所以现在是只能动态删不能加对吧😳

**Comment by liangxp** [comment]
> 所以现在是只能动态删不能加对吧😳

好像是这样，太难了，后端加载路由，前端还要把所有路由写一遍

**Comment by 1391020381** [comment]
这个问题最后的结论是什么？
