### ISSUE TITLE
URL携带参数丢失

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#285]
exportStatic: true
url:http://localhost:8000/?source_id=1
跳转到别的路由，比如
import router from 'umi/router';
router.push('/main')
url变成:http://localhost:8000/main
请问如何处理这个问题？

**Comment by sorrycc** [comment]
跳转时需要手动把参数传过去。

```
router.push('/main', { query })
```

**Comment by xiaohuoni** [comment]
这个我清楚。还有别的处理方式吗？设置#的时候可以放到#之前处理

**Comment by xiaohuoni** [comment]
这个需求还是挺常见的，有没有什么办法做同一拦截。比如微信分链接分享

**Comment by sorrycc** [comment]
没理解问题，和 # 有啥关系，详细说下？

**Comment by xiaohuoni** [comment]
设置hashHistory:true
url:http://localhost:8000/?source_id=1/#/
跳转后地址
http://localhost:8000/?source_id=1/#/main

**Comment by sorrycc** [comment]
http://localhost:8000/?source_id=1/#/

这个地址就不对吧，source_id 应该放 #/ 后面。
