### ISSUE TITLE
umi动态引入文件

### ISSUE THREAD

**Issue by xlei1123** [umijs/umi#2853]
## 动态引入css文件 发现 条件判断不起作用

if (111 == '222') {
    require (`../assets/less/a.less`);
}

这个a.less会被引入呢 为啥？

**Comment by sorrycc** [comment]
webpack 构建就是这样的，不能按需编译的。

**Comment by xiaodel** [comment]
```
require.context('./apis/', true, /\.js$/);
```
这段代码编译会报错
