### ISSUE TITLE
yarn create umi 报错

### ISSUE THREAD

**Issue by VFiee** [umijs/umi#2854]
## What happens?

![image](https://user-images.githubusercontent.com/42051272/61624236-cfaab600-acaa-11e9-903e-dc9ddc16bd77.png)

## 相关环境信息

- **Umi 版本**：2.6.17
- **Node 版本**：v10.16.0
- **操作系统**：macOS

**Comment by sorrycc** [comment]
提示很明确，当前目录不是空目录。
