### ISSUE TITLE
cnpm安装umi后， 使用umi dev启动报错

### ISSUE THREAD

**Issue by jackywq** [umijs/umi#2855]
**整个目录结构：**
![image](https://user-images.githubusercontent.com/21954704/61624898-14831c80-acac-11e9-9331-1dba99001075.png)
**报错信息如下：**
![image](https://user-images.githubusercontent.com/21954704/61624919-1ea51b00-acac-11e9-82c4-b064e8db1968.png)
**相关环境信息如下：**
Umi 版本：v2.8.13
Node 版本：v10.16.0
操作系统：window10

**Comment by ycjcl868** [comment]
这个 [ci](https://circleci.com/gh/umijs/umi/34?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) 跑的 cnpm，模块安装没有问题。

**Comment by jackywq** [comment]
> 这个 [ci](https://circleci.com/gh/umijs/umi/34?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) 跑的 cnpm，模块安装没有问题。

我觉得这个跟node有关系。

**Comment by sorrycc** [comment]
目录不要有中文。
