### ISSUE TITLE
在index.js中设置默认启动页，build之后，模块数据丢失

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#286]
使用
```js
import Home from './main/page';
export default Home;
```
这样的方式，设置默认启动页
build之后，访问，提示
```base
Cannot read property 'text' of undefined
```
demo
```js
https://github.com/xiaohuoni/umibug
```
重现步骤
```base
$ npm i
$ npm run build
$ cd dist
$ serve
```
访问：报错http://localhost:5000/#/
访问：可以正常访问http://localhost:5000/#/main
再访问：也可以正常访问http://localhost:5000/#/

demo里面包含了dist产物，可直接先查看。

**Comment by sorrycc** [comment]
两个解决方案：

1. pages/index.js 用 `<Redirect to="/main" />`
2. 移动 pages/index.js 到 pages/index/page.js，并新建 pages/index/model.js，内容为 export default from '../main/models/main`

**Comment by xiaohuoni** [comment]
方案2： 报错namespace should be defined

**Comment by superlbr** [comment]
@xiaohuoni 可以ctril+c终止之后，再run一下，model改动之后，umi反应不过来

**Comment by xiaohuoni** [comment]
@superlbr  build后的问题，和停不停有什么关系？

**Comment by sorrycc** [comment]
还有问题的话可以 reopen 。
