### ISSUE TITLE
devServer的publicPath对umi.css不起作用

### ISSUE THREAD

**Issue by GrayChoi** [umijs/umi#2860]
## What happens?

配置了devServer的publicPath，css路径仍然是根目录

![image](https://user-images.githubusercontent.com/10493353/61636544-cc2a2580-acd0-11e9-98c0-17405d986774.png)

## 期待的动作

想要在dev模式下配置publicPath

**Comment by sorrycc** [comment]
dev 模式下不支持 publicPath 配置的。
