### ISSUE TITLE
umi dev 启动报错

### ISSUE THREAD

**Issue by xlsdg** [umijs/umi#2862]
## What happens?

$ umi dev

✖  error     Error: Cannot find module 'eslint-plugin-jest'
✖  error     Error: Cannot find module 'eslint-plugin-eslint-comments'
✖  error     Error: Cannot find module '@typescript-eslint/eslint-plugin'

## Mini Showcase Repository(REQUIRED)

https://github.com/xlsdg/umi-dva-antd-starter

## How To Reproduce
**Steps to reproduce the behavior:**
1. `git clone https://github.com/xlsdg/umi-dva-antd-starter.git`
2. `cd umi-dva-antd-starter && yarn && yarn start`

**Expected behavior**
1. 必须手动安装 `yarn add -D eslint-plugin-jest eslint-plugin-eslint-comments @typescript-eslint/eslint-plugin` 后才能启动工程。
2. 通过 `npm i` 安装依赖包则不会出现该问题。

## Context

- **Umi Version**: v2.8.13
- **Node Version**: v10.16.0
- **Npm Version**: v6.10.1
- **Yarn Version**: v1.17.3
- **Platform**: macOS Mojave 10.14.6

**Comment by xlsdg** [comment]
报错显示是 [sylvanas](https://github.com/umijs/sylvanas) 库，搜索发现只有 https://github.com/umijs/umi/blob/master/packages/umi-build-dev/yarn.lock 里有引用，不知是不是这个文件造成的。

**Comment by sorrycc** [comment]
复现了，是 bug，晚上发个版本修复。
