### ISSUE TITLE
添加ssr后，umi.css 文件错误

### ISSUE THREAD

**Issue by P13rre** [umijs/umi#2867]
设置ssr: true，umi.css 文件Content-Type: text/html; charset=utf-8，拿到的是html

![image](https://user-images.githubusercontent.com/51985715/61700899-d4856d80-ad6f-11e9-87b6-1e5533125b99.png)

**Comment by sorrycc** [comment]
你好 @P13rre，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为无复现步骤或可复现仓库而被自动关闭，提供之后会被 REOPEN。
