### ISSUE TITLE
调试界面中文乱码

### ISSUE THREAD

**Issue by superlbr** [umijs/umi#287]
![image](https://user-images.githubusercontent.com/8142164/38181631-847e879e-3666-11e8-84c4-8472cbbcd1a7.png)

**Comment by sorrycc** [comment]
你的文件不是 utf-8 编码？

**Comment by superlbr** [comment]
文件是utf8，View compiled 正常，怀疑这个截取代码显示的时候乱了
![image](https://user-images.githubusercontent.com/8142164/38183384-9388697e-3672-11e8-80eb-bb6f1338caff.png)

**Comment by sorrycc** [comment]
<img src='https://shipusercontent.com/1ec2b5190d5d85657f8c8d22b54cdca2/Pasted%20Image%201.png' title='Pasted Image 1.png' width=386>
<img src='https://shipusercontent.com/c0cc5505d2b7b4f13a210885c77d19a0/Pasted%20Image%202.png' title='Pasted Image 2.png' width=386>

试了下，应该是本地文件编码的问题，本地文件 GBK 时乱码，UTF-8 时是好的。
