### ISSUE TITLE
umi block --path 应该有保留字段

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#2871]
## What happens?
比如使用 `umi block --path=/from`,脚本会将这个 `path` 首字母提升为 `From` ，然后和代码`antd` 的组件冲突了。就没办法启动，在使用 `--js` 的时候，也无法继续执行转化js代码。

**Comment by sorrycc** [comment]
应该是 bug，语法树里添加代码时得检查 scope 里的命名冲突。
