### ISSUE TITLE
umi中使用antd-mobile打包后ios10一下系统报错

### ISSUE THREAD

**Issue by Mcyfeng** [umijs/umi#2873]
<img width="243" alt="222" src="https://user-images.githubusercontent.com/35359402/61770611-44533100-ae20-11e9-8013-94187f761e2d.png">
版本是：
 "umi": "2.7.7",
    "umi-plugin-react": "1.8.4",

 targets: {
    android: 5,
    ios: 7,
    chrome: 58,
    ie: 9,
  },

在项目是使用了picker组件，然后安装并引入了antd-mobile-demo-data，打包上线后，ios10一下版本访问都出现了上图的报错

**Comment by sorrycc** [comment]
是组件的问题，组件应该发布为 es5 代码。
