### ISSUE TITLE
package里面的 peerDependencies和devDependencies不会自动安装

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#2877]
```
"peerDependencies": {
    "@ant-design/pro-layout": "^4.5.5"
  },
 "devDependencies": {
    "@types/express": "^4.17.0"
}
```
`umi block add https://github.com/ant-design/pro-blocks/tree/master/AccountCenter`
自动安装模块的时候没有安装`peerDependencies`和`devDependencies`

**Comment by sorrycc** [comment]
这是符合预期的，需要被安装的放 dependencies 里。

**Comment by xiaohuoni** [comment]
@chenshuai2144 那block里面的写法就要改了
