### ISSUE TITLE
目前发现umijs在支付宝小程序的webview跳转中有异常

### ISSUE THREAD

**Issue by ooxx87** [umijs/umi#2878]
## What happens?

目前发现umijs在支付宝小程序的webview跳转中有异常
通过小程序菜单跳转到一个含有web-view的页面后，通过webview跳转到umi的react页面会发现在IOS下正常没问题，但是安卓端的会白屏。
我们已经联系过支付宝小程序的团队他们给予的答复是umijs在那边报错了，错误如下
![image](https://user-images.githubusercontent.com/39373576/61844065-b97e3f00-aed0-11e9-809e-6a5172b7f57c.png)

如果需要调试，需要通过支付宝小程序测试

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：2.8.11
- **Node 版本**：10
- **操作系统**：win10

**Comment by xiaohuoni** [comment]
设置一下targets应该可以解决，https://umijs.org/zh/config/#targets

**Comment by ooxx87** [comment]
> 设置一下targets应该可以解决，https://umijs.org/zh/config/#targets

能否告知应该设置成什么样子？不太清楚如何设置兼容支付宝

**Comment by xiaohuoni** [comment]
可以先试试直接设置成ie:9

**Comment by ooxx87** [comment]
我们项目引用了antd pro所以没办法适配到IE9

**Comment by xiaohuoni** [comment]
只是让你设置打ie9的补丁，不是适配到i9呢

**Comment by xiaohuoni** [comment]
你先试试是不是补丁的问题，如果打补丁可以解决问题，那你再换成设置其他的什么android:4之类的

**Comment by ooxx87** [comment]
早上试过了，依然不行目前targets：[ie:9]

**Comment by xiaohuoni** [comment]
那我就不清楚了，没开发过支付宝小程序

**Comment by ooxx87** [comment]
啊哦。。那是不是说目前umi+antd pro的组合目前无法在支付宝小程序的web-view中适配呢？

**Comment by xiaohuoni** [comment]
不能这么说吧，只是我不懂。@sorrycc

**Comment by ooxx87** [comment]
。。不好意思我表达的不对。
只是现在小程序的webview没办法访问我们这个页面，很蛋疼

**Comment by sorrycc** [comment]
看提示是缺 Intl，加载 Intl 的补丁试试？

**Comment by ooxx87** [comment]
已经先把国际化的那个插件去除了。
