### ISSUE TITLE
request错误捕捉的问题

### ISSUE THREAD

**Issue by zhongds** [umijs/umi#2879]
### 场景
我现在有这样的一个场景：

> 各业务发请求后可以自行捕捉处理错误，如果没有捕捉错误，则由全局错误拦截统一处理

目前umi-request的错误处理是：先经过统一的拦截处理，再到各业务的catch处理。

### 期望
想请教下，要实现上面的场景，除了传回调外，有没有其他更优雅更简洁的方式来处理这个问题？

**Comment by chenjsh36** [comment]
umi-request 目前在beta 测试中的中间件机制，开发者可以通过添加自定义中间件，对请求前后做相关处理，例如对 response 做校验判断，且中间件在统一的拦截处理之前，不知能否满足你们的业务场景？

**Comment by chenjsh36** [comment]
umi-request 已经发布 1.2.x 版本，支持自行对 response 自行捕捉处理错误，再由全局错误拦截统一处理

**Comment by whwnow** [comment]
提个小建议，能不能再灵活一点，自行捕捉处理错误之后，还可以判断是否需要统一错误拦截进行处理

**Comment by zhongds** [comment]
中间件这个处理方式挺好的，很灵活。
不过最初提这个issue的初衷是希望每个请求能个性化处理错误。开始我是通过传回调callback，在response拦截器中实现：
```
dispatch({type: "xxx", callback: fn}) => model => service => request
```
只是这样太麻烦了，需要通过model，service一层层传下去。

后来发现可以在dva onError中可以获取action（这个太赞了！）。最后是类似下面这样实现的：
```
// app.js
export const dva = {
  config: {
    onError(e, ...args) {
      // 各业务自行拦截处理
      const [
        dispatch,
        {
          effectArgs: [{ onError: _onError }],
        },
      ] = args;
      if (_onError && typeof _onError === 'function' && !_onError(e)) {
        return;
      }
      // 统一的错误处理
      if (e.error) {
        notification.error({
          message: `Error: ${e.status}: ${e.error}`,
          description: e.error_description,
        });
      } else {
        notification.error({
          message: `Network Error`,
          description: 'Network Unreachable, Please try later',
        });
      }
    },
  },
};
```
业务组件调用的时候，把onError定义好
```
dispatch({
  type: "xxx",
  onError(err) {
     // do something....
  }
})
```
