### ISSUE TITLE
关于路由的问题

### ISSUE THREAD

**Issue by feivorid** [umijs/umi#288]
想问一下  
![image](https://user-images.githubusercontent.com/5013223/38182211-851e37ea-366a-11e8-8a5e-2c81adaa7e85.png)

这种路由 pages 中应该是什么结果  ？ 

我尝试  /user/$userId/classes   不好用  

求指导 ？

**Comment by xiaohuoni** [comment]
不好用是什么意思？

**Comment by feivorid** [comment]
@xiaohuoni   写错了   可以用  😅

**Comment by feivorid** [comment]
@xiaohuoni   写错了   可以用  😅
