### ISSUE TITLE
Error: Cannot find module './features/css-clip-path'

### ISSUE THREAD

**Issue by huandie2012** [umijs/umi#2880]
## What happens?

使用yarn install安装依赖包，并且使用yarn start启动项目服务，会报下图的错误，提示找不到某个依赖包
![image](https://user-images.githubusercontent.com/8893631/61933519-a1acc680-af75-11e9-87ae-6f8c82457193.png)
最后删除了node_modules和yarn.lock，使用npm install和npm start才可以正常访问页面
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：2.8.15
- **Node 版本**：10.15.3
- **操作系统**：windows 7旗舰版

**Comment by sorrycc** [comment]
这是安装或 yarn 的问题，和 umi 无关。

**Comment by huandie2012** [comment]
我卸载重新安装还是会有这个问题，在windows7上面
