### ISSUE TITLE
umi@2.** 中如何使用自定义eslint配置？

### ISSUE THREAD

**Issue by baochengshi** [umijs/umi#2881]
1. 目前配置了.eslintrc文件，但是好像并没有起到作用，所以现在不知道怎么配置了
2.请大神指点一下，文档地址或者配置方式都行

**Comment by sorrycc** [comment]
你要覆盖什么配置？umi dev 内置的 eslint ？

**Comment by baochengshi** [comment]
对的，我想基于他的配置在加上自己自定义的。
但是现在好像没法使用.eslintrc文件，不能自定义。
或者有啥方法，麻烦提示一下，谢谢。
我的wx  DoveSummer220  大佬方便的话可以加下我哈

**Comment by sorrycc** [comment]
https://github.com/umijs/umi/blob/5f1608074caaa5c35e3cead71fbc86c7f714ed62/packages/af-webpack/src/getConfig/eslint.js#L4
目前不支持自定义。

**Comment by baochengshi** [comment]
好的，谢了

**Comment by baochengshi** [comment]
后面的版本这个功能能开放下吗？

**Comment by sorrycc** [comment]
之前 umi@1 开放过，有不少坑的，有兴趣可以提个 PR 试试。
