### ISSUE TITLE
关于package-lock.json

### ISSUE THREAD

**Issue by ybzjsxh** [umijs/umi#2884]
出于好奇想问下为什么保留了yarn.lock而gitignore了package-lock.json文件吗，还是说因为只用yarn，因为`npm help package-lock.json`里面有这样的描述：
![image](https://user-images.githubusercontent.com/18141198/61996274-2f4afc00-b0c5-11e9-86ef-5acb18cab7c6.png)

**Comment by sorrycc** [comment]
umi 本身的开发用 yarn 不用 npm，另外保留 yarn.lock 可以让 ci 跑地更快。
