### ISSUE TITLE
umi prerender build bug

### ISSUE THREAD

**Issue by iisbigfish** [umijs/umi#2886]
## What happens?
umi 添加预渲染后出现

```
(node:4921) UnhandledPromiseRejectionWarning: /Users/pandacat/Desktop/xiangmu/node_modules/antd/es/message/style/index.js:1
(function (exports, require, module, __filename, __dirname) { import '../../style/index.less';
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^
```

查询后是因为antd组件的动态引入问题。而后修改babel配置项但是不起作用

```
  extraBabelPlugins: [
    [require.resolve('babel-plugin-import'), { libraryName: "antd", libraryDirectory: 'es', style: "true" }],
  ],
```

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Umi Version**: 2.8.11
- **Node Version**: v10.15.3
- **Platform**: MacOS

**Comment by ycjcl868** [comment]
antd 引入用 lib，有复现例子吗？

**Comment by iisbigfish** [comment]
> antd 引入用 lib，有复现例子吗？

https://github.com/iisbigfish/umissr.git

弄了一个由umi-create初始化的最小复现例子和配置。

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/62021770-84892980-b1fb-11e9-97b9-f69eb1d1268b.png)

`antd: true` 时，无须单独配置 `babel-plugin-import` 。

如果有特殊需求要配置的，记得关闭 `antd: false`，将 `libraryDirectory` 改成 `lib`，ssr 才能识别。

![image](https://user-images.githubusercontent.com/13595509/62021815-c5813e00-b1fb-11e9-9169-5fa4248a589f.png)
