### ISSUE TITLE
umi-request Failed to minify the code from this file

### ISSUE THREAD

**Issue by ningzhenyi** [umijs/umi#2887]
使用umi-request build 的时候会出现这个错误：

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/umi-request/node_modules/query-string/index.js:9

Read more here: http://bit.ly/2tRViJ9

要怎么解决呢？

**Comment by sorrycc** [comment]
构建不是用的 umi？ umi 已经处理了 query-string 的压缩问题。
