### ISSUE TITLE
config/config.js 配置插件umi-plugin-react 配置links无效

### ISSUE THREAD

**Issue by scm-Q** [umijs/umi#2889]
## What happens?
umi-plugin-react插件中配置links，html页面head生成了link，但是css文件并未加载.

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1. config.js 插件umi-plugin-react配置links，比如：
links: [
        {
          ref: 'stylesheet',
          href:`<%= PUBLIC_PATH %>app.min.css`
        },
      ],
确认app.min.css浏览器访问路径无误；
2. 查看页面head 有link 生成，但是network未看到加载css；

**Expected behavior**
1. 页面生成link；
2. network能看到资源请求，并css生效；

## Context

- **Umi Version**: 2.8.15
- **Node Version**: 8.9.3
- **Platform**: Mac

**Comment by sorrycc** [comment]
生成的 html 看下，或者给可复现仓库。

**Comment by scm-Q** [comment]
我在自己的工程下遇到该问题，用了ant-design-pro实例项目下验证，问题依旧，主要代码如下：
<link rel="manifest" href="/manifest.json">
<link ref="stylesheet" href="/app.min.css">
<link rel="stylesheet" href="/umi.css">

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <title>Analysis - Ant Design Pro</title>
    <link rel="icon" href="/favicon.png" type="image/x-icon">
备注：app.min.css 为测试的css文件，目前我放在public目录下，通过浏览器直接访问http://localhost:8000/app.min.css 确认能返回内容，比如：
.test {
    float:right;
}
但是开发者工具network并未看到请求的css资源。

**Comment by aixfox** [comment]
生成了link标签但是浏览器没有发起请求？我觉得还是提供一下复现仓库才能排查问题。

**Comment by sorrycc** [comment]
看不出问题，提供可复现仓库再 reopen。
