### ISSUE TITLE
SSR报警告 Warning: Did not expect server HTML to contain a <div> in <div>

### ISSUE THREAD

**Issue by elivoa** [umijs/umi#2894]
Console报警告： 
`Warning: Did not expect server HTML to contain a <div> in <div>`

SSR umi@2.8.16
umi-example-ssr-with-egg 工程中，app/view/index.html中，如果有下面这段则报上述警告：
```
  <script>
    (function () {
      window.g_useSSR = true;
      window.g_initialData = JSON.parse(decodeURIComponent('{{ g_initialData }}'));
    })()
  </script>

```
这是什么原因？

**Comment by ycjcl868** [comment]
看报错是 server render 出来的 html 与 client 预期有差别，会报这个 warning

**Comment by elivoa** [comment]
是这个问题。
window.g_initialData 这段脚本，会将服务端获取api得到的state内容都放到页面，同步到客户端。就会报警告，这个警告貌似会影响渲染性能。

**Comment by elivoa** [comment]
是这个问题。
window.g_initialData 这段脚本，会将服务端获取api得到的state内容都放到页面，同步到客户端。就会报警告，这个警告貌似会影响渲染性能。

**Comment by ycjcl868** [comment]
会有一次 rerender 的渲染性能消耗

**Comment by elivoa** [comment]
这个问题预计什么时候可以解决？
