### ISSUE TITLE
Override deva.js.tpl

### ISSUE THREAD

**Issue by mihai-cloudbrick** [umijs/umi#2895]
Im using Antd-pro and i need to implement OIDC on top of it. The authentication need to happen at the begining of the application and the only way to doit its to override the dvs.js file. Iths there any way to override the template dinamically from config.js?

**Comment by sorrycc** [comment]
Try to use the **render** method of [runtime config](https://umijs.org/guide/runtime-config.html#render).

```js
export function render(oldRender) {
  doAuth().then(() => oldRender).catch(e => {});
}
```
