### ISSUE TITLE
[Feature Request] configure file hash suffix

### ISSUE THREAD

**Issue by netroby** [umijs/umi#2897]
The current file hash like  `index.0459c.js`, was not good for cdn. and directory may contains many unused files.
Every publishing to server will generate new files.
That was terrible consume the disk usage.

we should configure the file hash suffix.

like `index.js?_v=0459c`

the origin file will be override by the new content. and no more new file been created.
feel free to use it .

**Comment by sorrycc** [comment]
If you want to use `index.js?_v=0459c`, disable `hash` config and add the affix in the HTML file.
