### ISSUE TITLE
打包后浏览器除了谷歌 别的浏览器报错 因该是编译出错了 怎么解决？

### ISSUE THREAD

**Issue by yourdear** [umijs/umi#2899]

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/1421#issuecomment-516762499

**Comment by sorrycc** [comment]
你好 @yourdear ，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为无复现步骤或可复现仓库而被自动关闭，提供之后会被 REOPEN。
