### ISSUE TITLE
fetch 服务端没有respond的时候，程序卡死

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#290]
import fetch from 'dva/fetch';

**Comment by sorrycc** [comment]
不是 umi 问题，看下 fetch 有没有超时设置，或者利用 redux-saga 做超时控制。

**Comment by xiaohuoni** [comment]
程序错误。
服务端没有respond，取得的值是null，在对其取值就报错了，
与任何框架都无关，关闭了
