### ISSUE TITLE
umi-request 在使用中间件时，post请求被强制改为了get请求

### ISSUE THREAD

**Issue by huangbao21** [umijs/umi#2900]
## What happens?

umi-request 在使用中间件时，post请求被强制改为了get请求

## 相关环境信息

- **Umi 版本**："umi": "^2.8.7", 
"umi-request": "^1.1.1"

**Comment by chenjsh36** [comment]
本地测试没有这个问题，能给个线上 DEMO 或样例吗？如要使用中间件可以尝试使用 1.2.0-beta.4 版本

**Comment by huangbao21** [comment]
我暂时没用中间件了，换了其他思路解决了目前的需求

**Comment by huangbao21** [comment]
@chenjsh36 等测试后没问题，再给你反馈
