### ISSUE TITLE
ie

### ISSUE THREAD

**Issue by yourdear** [umijs/umi#2902]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/1421#issuecomment-516762499
