### ISSUE TITLE
umi 项目在ie中报错，兼容问题

### ISSUE THREAD

**Issue by songshuyu-messi** [umijs/umi#2903]
项目在谷歌和火狐中均可正常运行，但是在ie中报错，错误如下如，
     SCRIPT1002: 语法错误
     umi.js, 行61668 字符3
在朋友帮助下，在node_modules/es5-imcompatible-versions/package.json，文件中加入
    "react-redux":{
      "^7.1.0":{"version":"^7.1.0","reason":"dist/react-redux.js/L2229"}
   }
之后错误变成
   SCRIPT5009: “Proxy”未定义 
   umi.js, 行147296 字符3
   TypeError: 对象不支持“repeat”属性或方法

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/1421#issuecomment-516762499

**Comment by sorrycc** [comment]
你好 @yourdear ，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为无复现步骤或可复现仓库而被自动关闭，提供之后会被 REOPEN。
