### ISSUE TITLE
针对context的说明

### ISSUE THREAD

**Issue by rubyisapm** [umijs/umi#2905]
## What happens?

文档中关于针对每个路由通过context配置信息如何进行？

引用原文档：

出处1：
```
context
类型：Object
默认值：{}
配置全局 context，会覆盖到每个 pages 里的 context。
```
出处2：
```
配置模板
模板里可通过 context 来获取到 umi 提供的变量，context 包含：

route，路由对象，包含 path、component 等
config，用户配置信息
publicPath2.1.2+，webpack 的 output.publicPath 配置
env，环境变量，值为 development 或 production
其他在路由上通过 context 扩展的配置信息
```
其中的”每个 pages 里的 context“ ”其他在路由上通过 context 扩展的配置信息“应该如何配置？

我是想实现一个在某个路由下才加载的一段统计脚本，想通过这种方式配置，然后在ejs中通过变量判断加载脚本。

**Comment by sorrycc** [comment]
单页应用只有一份 ejs 的，应该存和路由关联的数据，然后拿 url 和这份数据匹配决定是否加载统计脚本。
