### ISSUE TITLE
最新版本 onRouteChange执行顺序在model subscriptions 之后 v2.8.15正常

### ISSUE THREAD

**Issue by Veveue** [umijs/umi#2908]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xjdata** [comment]
+1

**Comment by 282159468** [comment]
+1
