### ISSUE TITLE
Router.push问题

### ISSUE THREAD

**Issue by ShaneKing** [umijs/umi#291]
@sorrycc 

目录如下图
![image](https://user-images.githubusercontent.com/3394899/38200856-8f4ba0f0-36c8-11e8-8e80-47ef1b61a047.png)

一、pages下中的butler和settings有_layout.js时，
在浏览器拍http://localhost:8000/butler/settings/short
然后程序中Router.push('/workspace')，木有问题，会跳转到http://localhost:8000/butler/workspace
如果在浏览器拍http://localhost:8000/butler/workspace
然后程序中Router.push('/tracing')，有问题，会跳转到http://localhost:8000/tracing

二、pages中无_layout.js
在浏览器拍http://localhost:8000/butler/workspace，或http://localhost:8000/butler/settings/short
然后程序中Router.push('/butler/tracing')，没有问题，会跳转到http://localhost:8000/butler/tracing
如果程序中Router.push('/butler/settings/short')，有问题，会跳转到http://localhost:8000/butler/.0:$/butler/settings/short

![image](https://user-images.githubusercontent.com/3394899/38200803-53ebaeb0-36c8-11e8-87c3-df1e771c6764.png)

**Comment by sorrycc** [comment]
方便给个可重现的库吗？

**Comment by ShaneKing** [comment]
@sorrycc 

sk-user库的umi#291-1分支，重现pages下有_layout.js的请看
https://github.com/ShaneKing/sk-user/tree/umi%23291-1

安装依赖npm install
开发模式启动npm run dev

url拍链接：http://localhost:8000/admin/user/lst?skToken=Ec7EAFcC-AC8e-0FfD-6c42-FccEAA1CEE7F
页面**没**有内容，也没有报错
点击左边菜单Dashboard，此时程序逻辑Router.push('/dashboard')
可route到http://localhost:8000/admin/dashboard
页面还是**没**内容

url拍链接：http://localhost:8000/admin/dashboard?skToken=Ec7EAFcC-AC8e-0FfD-6c42-FccEAA1CEE7F
页面有内容
点击左边菜单Application，此时程序逻辑Router.push('/application')
**却**路由到了http://localhost:8000/application

**Comment by ShaneKing** [comment]
@sorrycc

sk-user库的umi#291-2分支，重现pages无_layout.js的情况
https://github.com/ShaneKing/sk-user/tree/umi%23291-2

安装依赖npm install
开发模式启动npm run dev

浏览器地址栏里输入并回车：http://localhost:8000/admin/dashboard?skToken=Ec7EAFcC-AC8e-0FfD-6c42-FccEAA1CEE7F
展开左边Test菜单，并点击Long，此时程序逻辑Router.push('/admin/test/long')
却路由到了：http://localhost:8000/admin/.1:$/admin/test/long
