### ISSUE TITLE
umi 中如何使用sass

### ISSUE THREAD

**Issue by ywy94ywy** [umijs/umi#2911]
请问在create umi 项目里，如何完美使用sass预处理器

**Comment by xiaohuoni** [comment]
啥叫完美使用？

**Comment by ywy94ywy** [comment]
首先能够使用sass，同时umi g page a生成的文件不再是css而是sass



------------------ 原始邮件 ------------------
发件人: "陈小聪"<notifications@github.com>; 
发送时间: 2019年7月31日(星期三) 下午5:13
收件人: "umijs/umi"<umi@noreply.github.com>; 
抄送: "杨文渊"<529042309@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [umijs/umi] umi 中如何使用sass (#2911)




啥叫完美使用？

**Comment by ycjcl868** [comment]
https://umijs.org/zh/config/#sass
