### ISSUE TITLE
使用SSR的同时，使用 dynamicImport:true。在客户端无法执行 getInitialProps

### ISSUE THREAD

**Issue by qzhongyou** [umijs/umi#2912]
问题：
配置文件中同时配置` ssr: true`和` dynamicImport: {
        webpackChunkName: true,
      }`时，在客户端无法执行 getInitialProps

原因：
因为按需加载，导致umi renderRouter.js文件中 ``` if (__IS_BROWSER && Component.getInitialProps) {
                  const initialProps = plugins.apply('modifyInitialProps', {
                    initialValue: {},
                  });
                  Component = wrapWithInitialProps(Component, initialProps);
                }```中`Component.getInitialProps`无法获取

**Comment by ycjcl868** [comment]
`dva` 那层的 dynamic 问题

**Comment by qzhongyou** [comment]
> `dva` 那层的 dynamic 问题

dynamic 实际使用的 react-loadable，但是react-loadable并没法暴露getInitialProps 。
