### ISSUE TITLE
umi ssr 没有热更新

### ISSUE THREAD

**Issue by lilili001** [umijs/umi#2913]
umi ssr 启动 `npm run build && node server.js`  没有热更新 , 
例子: umi-example-ssr , 改动一次还需要重启很麻烦, 有解决方法吗

**Comment by ycjcl868** [comment]
有的，可参考 [umi-example-ssr-with-egg](https://github.com/umijs/umi-example-ssr-with-egg) 例子
- node 换成 [supervisor](https://www.npmjs.com/package/supervisor) 或者 [pm2](https://www.npmjs.com/package/pm2)
- `npm run build` 换成 `umi dev`

**Comment by lstrive-yn** [comment]
> 有的，可参考 [umi-example-ssr-with-egg](https://github.com/umijs/umi-example-ssr-with-egg) 例子
> 
> * node 换成 [supervisor](https://www.npmjs.com/package/supervisor) 或者 [pm2](https://www.npmjs.com/package/pm2)
> * `npm run build` 换成 `umi dev`

使用supervisor或者pm2并不能在dev启动的情况下重启服务，所以还是没办法实现热更新；

**Comment by a982564562** [comment]
遇到了同样的问题 
换成cross-env  concurrently "umi dev" "nodemon server.js" 启动, 无法加载.js, .css文件
dist目录中只有umi.server.js文件
项目地址: https://github.com/a982564562/umi-ssr
