### ISSUE TITLE
umi-plugin-locale getLocale方法始终返回default/baseNavigator值

### ISSUE THREAD

**Issue by shawn-play** [umijs/umi#2917]
## What happens?
umi-plugin-locale getLocale方法始终返回default/baseNavigator值

## 复现步骤，错误日志以及相关配置
plugins: [
    [
      "umi-plugin-react",
      {
        antd: true,
        dva: true,
        dynamicImport: {
          webpackChunkName: true,
          loadingComponent: "./components/loading/loading"
        },
        locale: {
          default: 'zh-CN',
          baseNavigator: true,
          antd: true
        }
      }
    ]
  ],

## 相关环境信息

- **Umi 版本**：2.8.16
- **Node 版本**：v8.11.3
- **操作系统**：macOs

**Comment by ycjcl868** [comment]
baseNavigator: false

**Comment by shawn-play** [comment]
> `baseNavigator: false`

这个设置没有作用
