### ISSUE TITLE
umi的ssr打包依赖问题

### ISSUE THREAD

**Issue by hoverCow1990** [umijs/umi#2919]
umi的ssr打包后服务端渲染时，是否必须要存在nodemodule文件夹

**Comment by ycjcl868** [comment]
这个 https://github.com/umijs/umi/pull/2906 ，增加了 `disableExternal` 配置，默认是 `false`。

如果开启，就全量打包进 `umi.server.js`，不做 external，这时候就不依赖 `node_modules`

**Comment by hoverCow1990** [comment]
谢谢，请问是否还没发npm包～

**Comment by ycjcl868** [comment]
周一，有几个一起上车

**Comment by hoverCow1990** [comment]
> 周一，有几个一起上车

嘻嘻, 辛苦了～～

**Comment by ycjcl868** [comment]
Release umi@2.8.17.

**Comment by hoverCow1990** [comment]
> Release umi@2.8.17.

3q~ 收到

**Comment by awang0608** [comment]
你好，请问 关于disableExternal的配置是被关掉了咩？怎么现在这个配置没有出现在官方文档里了，types里面也没有这个配置
![image](https://user-images.githubusercontent.com/35441582/93067595-fea19980-f6ad-11ea-8885-76a0faf6e19b.png)

![image](https://user-images.githubusercontent.com/35441582/93067541-f0ec1400-f6ad-11ea-8227-cbaafa666d7f.png)

umi版本： "umi": "^3.2.10",
