### ISSUE TITLE
图片引用路径有问题

### ISSUE THREAD

**Issue by walkinMrwang** [umijs/umi#292]
.webpackrc配置：
![egpi sxq ep8a rhny8ew h](https://user-images.githubusercontent.com/26135370/38224369-45c8f7de-3722-11e8-9d90-5f4beeec1ff3.png)
dist文件打包路径：
![vu8ync135hava tmgcs0heu](https://user-images.githubusercontent.com/26135370/38224402-72a56986-3722-11e8-98a1-ee0202706adf.png)
最终结果引用路径：
![tim 20180403092759](https://user-images.githubusercontent.com/26135370/38224426-89009b06-3722-11e8-9f27-95e0e29dd587.png)
./static/static/static  多了一个static层级

**Comment by xiaohuoni** [comment]
图片并没有丢失，能找到就好，这个是之前有一个bug，找不到图片。所以增加了这个，估计后续会处理这个问题，现在不影响项目使用就好

**Comment by sorrycc** [comment]
publicPath 为啥要写 ./static ?

**Comment by walkinMrwang** [comment]
如果不这样写，打包到服务器之后路径有问题，=。=，试过'./static/'才没问题，不过需要给图片资源再加一个static层级

**Comment by xiaohuoni** [comment]
现在默认就是你设置的这个。你现在去掉。服务器就不用再加一个

**Comment by sorrycc** [comment]
部署到服务器端 publicPath 用绝对路径。
