### ISSUE TITLE
[Feature Request] share config between bundlers

### ISSUE THREAD

**Issue by rtxu** [umijs/umi#2920]
## Background

storybook 有自己独立的 webpack 配置，我猜测 umi 也有一套 webpack 配置，目前不知道如何获取到 umi 的 webpack 配置，导致同一份代码库的不同 bundler 无法共享配置

## Proposal

希望 umi 可以暴露出自己的 webpack 配置，或者提供可以读取/引用的方法，这样一份代码库中的不同 webpack 配置可以实现复用

## Additional context

N/A

**Comment by aixfox** [comment]
在这里：
https://umijs.org/zh/config/#chainwebpack

**Comment by rtxu** [comment]
抱歉，我的锅，居然漏掉了文档，我跟了一段 npm run dev 的代码，发现层次较深，后来放弃了

**Comment by rtxu** [comment]
但是我的 storybook 怎么引用 umi 中的 webpack 配置呢

**Comment by aixfox** [comment]
你的场景是不是这样：开发库使用 storybook，在 umi 工程中使用。

storybook 目前的方向是与 cra 集成吧。umi  的 webpack 配置都在 af-webpack 中。
其实打包库的话不需要过多关心 webpack，把 jsx?/tsx? 编译好，注意一下 af-webpack 如何处理 node_modules 的 rule 就差不多了。

**Comment by rtxu** [comment]
> 你的场景是不是这样：开发库使用 storybook，在 umi 工程中使用。
> 
> storybook 目前的方向是与 cra 集成吧。umi 的 webpack 配置都在 af-webpack 中。
> 其实打包库的话不需要过多关心 webpack，把 jsx?/tsx? 编译好，注意一下 af-webpack 如何处理 node_modules 的 rule 就差不多了。

主要是 storybook 要 run 起来，ts/babel/less/global.css 所有这些都要和 umi 中的配置一致，否则会遇到各种各样的问题

看起来，可以用 af-webpack 的 umi 官方配置 merge chainWebpack 的用户自定义配置的方式来配置 storybook 中的 webpack。但是太丑了，一点也不 single source of truth
