### ISSUE TITLE
how to upgrade the workbox version

### ISSUE THREAD

**Issue by nguyenhuutinh** [umijs/umi#2923]
Hi team

I found there is new version of workbox

But I cannot find they way to upgrade it.
in my project, it always 3.6.3
Can you give me some suggestion?

thank you

**Comment by xiaohuoni** [comment]
The current maximum version is 2.9.1

**Comment by nguyenhuutinh** [comment]
hi @xiaohuoni : I meant workbox version, not umijs version.
workbox is above 5 now (https://github.com/GoogleChrome/workbox/releases)
but in umi. it's always 3.6.3

**Comment by cookie314** [comment]
+1, could this project upgrade workbox to the latest version?
