### ISSUE TITLE
打包重新发布react-umi项目，用户的浏览不刷新，引用还是旧的js和css

### ISSUE THREAD

**Issue by 892744577** [umijs/umi#2925]
打包重新发布react-umi项目，用户的浏览不刷新，引用还是旧的js和css

**Comment by sorrycc** [comment]
可能原因：

1. 开了 PWA
2. 浏览器缓存，加时间戳或 hash 之类的

非 umi 框架问题。

**Comment by 892744577** [comment]
hash: true解决了
