### ISSUE TITLE
SSR中服务端渲染阶段无法获取 props.location。

### ISSUE THREAD

**Issue by elivoa** [umijs/umi#2930]
我的URL是 /search?t=b&q=query
在服务端输出 props.location 得到的是下面结果，加上withRouter也不行。
```
location: {
  pathname: '/search',
  search: '',
  hash: '',
  state: undefined,
  key: '...'
}
```

props.match 是可以的。

如何在服务端获取到正确的值？

**Comment by ycjcl868** [comment]
这个例子昨天更新了，用 jsdom mock 下，就可以这样获取：

https://github.com/umijs/umi-example-ssr-with-egg/blob/master/app/web/utils/request.ts#L13
https://github.com/umijs/umi-example-ssr-with-egg/blob/master/app/controller/home.js#L36

**Comment by elivoa** [comment]
比如我的url是 /search?t=b&q=query

我的意思是在服务端的render阶段，获取 props.location 的到的内容是：
```
props.location {
  pathname: '/search',
  search: '',
  hash: '',
  state: undefined,
  key: 'dykjpl'
}
```
其中  search 和 query没有值。

而客户端render阶段拿到的是

![image](https://user-images.githubusercontent.com/958954/62427700-6a82a600-b729-11e9-9674-2804a1f1606f.png)

能够正常获得 query 和 search;

我觉得这个地方 服务端和客户端应该行为一致。不知框架中是否应该支持这样？
