### ISSUE TITLE
解决model 重名的问题的设计思路

### ISSUE THREAD

**Issue by tkvern** [umijs/umi#2936]
## What happens?

很多人遇到了这样的问题
>在动态路由下，不同页面下下model命名能重名吗，比如：
>
>pageA下的models中有datajs，namespace为data；
>pageB下的models中有datajs，namespace为data；
>
>如果用户先访问pageA，然后再访问pageB，期望能够实现pageB下的model data将pageA下的model data覆盖，貌似目前框架在发现重名的时候，并未选择覆盖重名的model。
>
>在大型的项目里，如果要求每个页面的model命名不一样，其实对管理和维护都有些不利

根据umi的文档描述，我们的目的是要让文件目录名限定作用域
让不同作用域下，可以使用相同的namesapace名称，且能正常工作。

## 解决步骤
下面给出解决思路
### Step 1 注册
我们都知道，在umi + dva中，mode分为全局和局部。局部model不能被不同目录下的其他页面引用。具体描述见图：
![image](https://user-images.githubusercontent.com/10667077/62449403-ad319600-b79c-11e9-87fb-21f4603c76c6.png)

而在实际使用中，表现并未与此一致。
那么怎么办呢？
在model进行注册的时候，带上model文件在pages这层目录的前缀
例如，model文件`category.js` 位于 `pages/Articles/models/category.js`
那么在注册model的时候自动带上所在目录的前缀

在声明的时候正常书写
`pages/Articles/models/category.js`
```js
export default {
  namespace: 'category',

  state: {
    data: {
      list: [],
    },
  },
.
.
.
```
在dva register model时带上文件所在目录前缀，全部转为单词全部转为小写，按照下划线分割
则在app._models中得到的model为`articles_category`

考虑到dispatch effect是使用斜杠切分的，所以这里演示暂时用下划线分割。我们的文件以及目录，按照约定是不允许出现下划线的。

未优化前,见下图:
![image](https://user-images.githubusercontent.com/10667077/62450338-b3287680-b79e-11e9-874a-dcd1202fd8fb.png)

优化自动添加目录前缀后，见下图:
![image](https://user-images.githubusercontent.com/10667077/62450411-d8b58000-b79e-11e9-8d3b-1b4f067ce192.png)

### Step2 使用
这里涉及到的就比较复杂一点了，要想兼容以前的书写方式不变，必须要考虑调用方所在文件路径。

我们在页面`pages/Articles/Category.js`使用正常方式书写
`pages/Articles/Category.js`
```js
  componentDidMount() {
    const { dispatch } = this.props;

    this.getTableData();
    dispatch({
      type: 'category/fetchAll',
      payload: {
        project: 1,
      },
    });
  }
```

在运行时，自动识别所调用的是全局的model还是局部的model。优先匹配局部的model。
带上目录前缀。
所以这里会自动匹配`articles_category/fetchAll`。
如果存在这样的model:  `pages/Articles/models/category.js`
则会带来这样的效果
```js
  componentDidMount() {
    const { dispatch } = this.props;

    this.getTableData();
    dispatch({
      type: 'articles_category/fetchAll',
      payload: {
        project: 1,
      },
    });
  }
```
当然如果不存在，再向上找全局model中是否有`category/fetchAll`。

这样即可满足model声明的物理隔离，多级目录也是同样的实现原理。

**Comment by tkvern** [comment]
@sorrycc sorrycc 这样修改dva的机制是不是就可以达到效果
![image](https://user-images.githubusercontent.com/10667077/62451560-14514980-b7a1-11e9-8707-25afc181df69.png)

**Comment by ycjcl868** [comment]
这样太黑盒了，Chrome 开发者工具里看 redux action 时，会比较蒙圈

**Comment by sorrycc** [comment]
是个思路，但还有很多细节需处理。

* devtool 里的展现
* dispatch 父级和全局的 model 时如何写和处理
* 组件层 dispatch 的处理
* dispatch 如何自动加前缀？

**Comment by luoboding** [comment]
不建议增加重名支持，只会带来混淆.
