### ISSUE TITLE
缺少服务端渲染（SSR）详细配置说明文档

### ISSUE THREAD

**Issue by softshield** [umijs/umi#2937]
项目是基于ant-pro 4.0版本，我是刚刚接触react ，umi 这些框架，想让项目支持服务端渲染，好做SEO优化。

要改的主要有哪些配置？

**Comment by ycjcl868** [comment]
will coming soon

**Comment by peakandyuri** [comment]
我也想尝试一下SSR，网上下的一些demo都过于复杂了，甚至一些都跑不起来
