### ISSUE TITLE
在dva global model的subscriptions中dispatch会导致路由失控

### ISSUE THREAD

**Issue by ZH4L** [umijs/umi#2950]
## What happens?
配合dva使用时，在global model的`subscriptions`中`dispatch`会导致路由失控

## Mini Showcase Repository(REQUIRED)
https://github.com/ZH4L/umi-issue-demo

## How To Reproduce
1. 启动项目并打开控制台
2. 点击首页的测试链接
3. 跳转后查看控制台输出信息

**Expected behavior**
1. 控制台只输出一次`/detail`和`PUSH`

## Context
真实结果是控制台输出了三次PUSH
*在`app.js`的`onRouteChange`中输出了action和pathname*

**Comment by feibi** [comment]
好像和 #2693 是同一个问题
