### ISSUE TITLE
umi/link 重复跳转同一路径会报警告

### ISSUE THREAD

**Issue by ffalconjs** [umijs/umi#2951]
<Link to="/list">Go to list page</Link> 
重复点击会报警告，是否可以在Link实现层加上重复判断
index.js:1 Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack

## 相关环境信息

- **Umi 版本**：^2.8.7
- **Node 版本**：v12.4.0
- **操作系统**：mac

**Comment by sorrycc** [comment]
给警告是符合预期的，这是依赖库 history 给。

**Comment by qq1170623178** [comment]
![image](https://user-images.githubusercontent.com/43264733/63160114-95d19300-c04f-11e9-9ea1-5d9f7a0e6190.png)
会变成这样浏览器然后卡死
