### ISSUE TITLE
打包后文件有多大呢？

### ISSUE THREAD

**Issue by offeeyang** [umijs/umi#2953]
大家打包后dist文件夹有多大呢？不包含ui上静态图片，不包含引入外展js，css文件。我这里纯粹由umi产生的也由4M了，担心有点大呢

**Comment by li2215890610** [comment]
你package.json 都用什么东西了?  build 出来 umi.js 就4M?

**Comment by peakandyuri** [comment]
我整个项目打包出来5M多，比较大的组件就antd和ag-grid，不过web服务器要开启gzip，初始加载也就1M多点点，后面都是动态加载，我觉得还OK

**Comment by li2215890610** [comment]
> 我整个项目打包出来5M多，比较大的组件就antd和ag-grid，不过web服务器要开启gzip，初始加载也就1M多点点，后面都是动态加载，我觉得还OK

那你的首次加载速度很慢吧？

**Comment by peakandyuri** [comment]
> > 我整个项目打包出来5M多，比较大的组件就antd和ag-grid，不过web服务器要开启gzip，初始加载也就1M多点点，后面都是动态加载，我觉得还OK
> 
> 那你的首次加载速度很慢吧？

还好吧，做的是PC端项目，现在的网速不存在好大问题，并且也不算是互联网应用，一般1-2秒加载出来吧

**Comment by sorrycc** [comment]
加环境变量 `ANALYZE` 分析下。
