### ISSUE TITLE
没配置eslint也会报这样的eslint错误

### ISSUE THREAD

**Issue by fengyun2** [umijs/umi#2956]
没配置eslint也会报这样的eslint错误

![image](https://user-images.githubusercontent.com/8147202/62688683-e582df80-b9fb-11e9-9cf4-b186f2abde4c.png)

## 相关环境信息

- **Umi 版本**：2.8.16
- **Node 版本**：11.12.0
- **操作系统**：windows 10

**Comment by xiaohuoni** [comment]
这个日志是在哪显示的？

**Comment by fengyun2** [comment]
@xiaohuoni 在项目启动的时候

**Comment by xiaohuoni** [comment]
eslint有默认，你可以使用ESLINT来关闭它。https://umijs.org/zh/guide/env-variables.html#eslint
