### ISSUE TITLE
每次打包都会在pages/.umi 下生成initDva.js, 而且.gitignore 也忽略不掉。求助呀！！！！！

### ISSUE THREAD

**Issue by 781194033** [umijs/umi#2957]
## What happens?
每次提交到git远程仓库，都会发现生成了initDva.js，我在.gitignore里面加了.umi/ ，但是没办法忽略。有什么办法嘛？

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：2.8.16
- **Node 版本**：12.7.0
- **操作系统**：macos

**Comment by ycjcl868** [comment]
删除 .umi ，然后提交 git。

**Comment by sorrycc** [comment]
Git 操作问题。
