### ISSUE TITLE
Mac下，mock无法热更新

### ISSUE THREAD

**Issue by polofish** [umijs/umi#2959]
umi： 2.8.16

原因：
mock目录
    + m
       -- m2.js
     - index.js
mock目录下，index.js 修改可以热更新
在index.js 中 import了 m/m2.js

修改index.js的数据可以热更新
而修改m2.js 无法热更新。
（但是在umi:2.8.10以前，一直都可以的）
更改mock数据后，提示 “ success   Mock files parse success”
然后刷新看界面的数据，依旧没有改变，重新 npm start才生效。

**Comment by sorrycc** [comment]
应该和 #2885 有关。

**Comment by leijingdao** [comment]
@sorrycc  重新又检测了一遍代码，发现确实是 windows 系统的 路径问题。。。
