### ISSUE TITLE
不能完全支持 SASS|SCSS

### ISSUE THREAD

**Issue by leogitpro** [umijs/umi#2974]
项目中引入 Bootstrap4, 引入 SCSS 报错.
在 umirc.js 中按教程添加了 : sass: {}, 也是报错.

**Comment by sorrycc** [comment]
不止加 sass: {} 配置，还要安装 `node-sass` 和 `sass-loader`。

**Comment by JamosLi** [comment]
sass版本太高也会出问题

**Comment by llh1187** [comment]
> 项目中引入 Bootstrap4, 引入 SCSS 报错.
> 在 umirc.js 中按教程添加了 : sass: {}, 也是报错.

你好，请问你解决这个问题了吗？
