### ISSUE TITLE
不能支持多布局的路由配置

### ISSUE THREAD

**Issue by leogitpro** [umijs/umi#2975]
最常见的页面布局不同的模块需要搭配不同的 Layout. 这个框架怎么配置也不支持.
不知道是什么情况. 配套的文档千篇一律. 这个框架的使用成本真是不低.

`
  routes: [
    //首页路由
    {
      path: '/',
      component: '../layouts/blank',
      routes: [
        {
          path: '/',
          component: './index',
          exact: true,
        },
      ],
    },

    //认证路由
    {
      path: '/auth',
      component: '../layouts/basic',
      routes: [
        {
          path: 'login',
          component: './auth/login',
          exact: true,
        },
      ],
    },

    //管理后台路由
    {
      path: '/admin',
      component: '../layouts/admin',
      routes: [
        {
          path: 'dashboard',
          component: './admin/dashboard',
          exact: true,
        },
      ],
    },
  ],
`
这样的配置, 无论如何都是404.
有神奇的办法么? 
除了在全局默认的路由里添加愚蠢的地址栏判断render不同的路由么?

**Comment by peakandyuri** [comment]
pages下面的目录里加上_layout文件啊，全局Layout就让它渲染children，umi的路由一般不需要手动配置吧

**Comment by xiaohuoni** [comment]
@leogitpro 麻烦编辑一下问题，你这个配置是两个还是一个？

**Comment by xiaohuoni** [comment]
如果需要配置不同的layout，可以参考 https://github.com/ant-design/ant-design-pro/blob/v2/config/router.config.js 然后，我觉得 umi 应该已经非常友好了，如果你不想关注这么多配置，可以使用约定式，或者使用[alita](https://github.com/alitajs/alita)

**Comment by qinghua5453** [comment]
> https://github.com/ant-design/ant-design-pro/blob/v2/config/router.config.js

不错不错，解决了一大难题，根路由path 一定要写，不然前面会覆盖后面的。
