### ISSUE TITLE
[Feature Request] 支持应用的文档开发及部署

### ISSUE THREAD

**Issue by tolerance-go** [umijs/umi#2976]
## Background

随着项目的扩大，人员的增多，应用内的组件信息共享，希望可以通过外部文档的方式查看

## Proposal

新增 umi 命令：umi doc dev 和 umi doc build；文档文件格式基于 mdx，共享 umi 的 react 相关配置，支持 code live 和 typescirpt 类型自动识别；约定可以根据文件目录结构生成文档导航菜单

## Additional context

实际上大部分是 docz 的功能，不过我觉得大型 react 应用的文档展示应该是比较通用的需求，相比 [father](https://github.com/umijs/father)，在提取作为外部依赖前，文档部分可以和仓库代码一起开发看上去更加合理

**Comment by sorrycc** [comment]
优先级低，短期应该不会做。

**Comment by tolerance-go** [comment]
@sorrycc 因为项目比较急，本地做了一个demo能用
![image](https://user-images.githubusercontent.com/37258382/63000368-8f061d00-bea3-11e9-9f22-590e9d5698cb.png)
![image](https://user-images.githubusercontent.com/37258382/63000374-92010d80-bea3-11e9-89d1-aeff96c4007b.png)
还是需要手写路由配置，准备后期封装成 umi 插件，大佬这个交给我吧
