### ISSUE TITLE
去掉lodash/uniq依赖

### ISSUE THREAD

**Issue by superlbr** [umijs/umi#299]
使用[..new set()]
参考 https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_uniq

**Comment by sorrycc** [comment]
dll 插件里的 uniq? 这是 node 端的依赖，和浏览器兼容无关吧。

**Comment by sorrycc** [comment]
> 还有umi插件全家桶的依赖版本不一致，比如@babel/runtime，@babel/core, @babel-eslint, chokidar。。。

@babel 系的我都用的 `^` 前缀，应该是一致的，chokidar 看了下也是一致的，是有遇到啥问题？

**Comment by superlbr** [comment]
刚刚看到[avet](https://github.com/avetjs/avet)，好大一个轮子，在想插件是否太多了。顺路打个酱油。。。
