### ISSUE TITLE
IE浏览器白屏问题

### ISSUE THREAD

**Issue by kangaroo-525** [umijs/umi#2994]
IE 11会出现白屏问题

![image](https://user-images.githubusercontent.com/34292792/63010296-b74c4680-beb8-11e9-990e-673c4d5cf369.png)
报错分别对应地方
![image](https://user-images.githubusercontent.com/34292792/63010380-df3baa00-beb8-11e9-944a-0a2a7bfe3c9a.png)
![image](https://user-images.githubusercontent.com/34292792/63010456-02665980-beb9-11e9-990d-355ae58999e9.png)

**Comment by wangxingkang** [comment]
配置为兼容 IE 9  试一下
```
targets: {
    ie: 9
  },
```

**Comment by FanFanJUN** [comment]
![image](https://user-images.githubusercontent.com/37857876/63996825-5fa41100-cb2f-11e9-9fc1-830359b0ab97.png)

IE 11页面一片空白  其他浏览器却可以正常访问

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/1421#issuecomment-516762499
