### ISSUE TITLE
ssr 问题 

### ISSUE THREAD

**Issue by kolterr** [umijs/umi#2995]
Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release UnhandledPromiseRejectionWarning: Error: Cannot find module '@tmp/history' build过后 用node启动的时候错误

**Comment by ycjcl868** [comment]
you can reinstall `node_modules` after remove lock files like `yarn.lock`, `package-lock.json`.

if not working, maybe you could provide a bug repo , I try

**Comment by kolterr** [comment]
> you can reinstall `node_modules` after remove lock files like `yarn.lock`, `package-lock.json`.
> 
> if not working, maybe you could provide a bug repo , I try

thx ,do not work for us. we will  keep trying.
