### ISSUE TITLE
umi test --coverage  不显示测试覆盖率，coverage文件夹中也只剩下coverage-final.json

### ISSUE THREAD

**Issue by lzsgitlzs** [umijs/umi#2996]
## What happens?
umi test --coverage  不显示测试覆盖率，coverage文件夹中也只剩下coverage-final.json

## 最小可复现仓库
使用yarn create umi选择antd即可。

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by yxqme** [comment]
修改 jest 配置 jest.config.js

里面有个参数

```
// 改成默认
coverageReporters: ['json', 'lcov', 'text', 'clover'],
```

包含 `text` 或者 `text-summary` 就能在控制台看到输出

**Comment by lzsgitlzs** [comment]
> 修改 jest 配置 jest.config.js
> 
> 里面有个参数
> 
> ```
> // 改成默认
> coverageReporters: ['json', 'lcov', 'text', 'clover'],
> ```
> 
> 包含 `text` 或者 `text-summary` 就能在控制台看到输出



> 修改 jest 配置 jest.config.js
> 
> 里面有个参数
> 
> ```
> // 改成默认
> coverageReporters: ['json', 'lcov', 'text', 'clover'],
> ```
> 
> 包含 `text` 或者 `text-summary` 就能在控制台看到输出

**Comment by lzsgitlzs** [comment]
> 修改 jest 配置 jest.config.js
> 
> 里面有个参数
> 
> ```
> // 改成默认
> coverageReporters: ['json', 'lcov', 'text', 'clover'],
> ```
> 
> 包含 `text` 或者 `text-summary` 就能在控制台看到输出

，非常感谢，内容都出来了
