### ISSUE TITLE
umi路由配置提示404

### ISSUE THREAD

**Issue by lddlww** [umijs/umi#2997]
其中一段路由配置如下：（antd pro中）
{
path: '/platform/mysql',
name: 'mysql',
icon: 'icon-MySQL',
component: './platform/mysql',
exact: true,
routes: [
{
path: '/platform/mysql/meters',
name: 'meters',
component: './platform/mysql/meters',
// hideInMenu: true,
exact:true,
},
{
path: '/platform/mysql/test',
name: 'test',
component: './platform/mysql/test',
},
]
},

当跳转到/platform/mysql/meters 或者 /platform/mysql/test，都会报umi development 404 page错误

我的目录结构：
src/pages/platform/mysql/
index.tsx
meters.tsx
test.tsx

当我把下面两个配置去掉，就能正常访问，加上就不行
component: './platform/mysql',
exact: true,

我不知道哪里配置有问题？

**Comment by xiaohuoni** [comment]
如果你这么配置的话，那真实的访问路径应该是 `/platform/mysql/platform/mysql/test` 
（另外提问请整理一下问题的格式，谢谢）
