### ISSUE TITLE
More webpack configs

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#3]
## Todos

* [x] sass
* [x] enableCSSModules -> disableCSSModules
* [x] devtool (e.g. enable sourcemap in production)

## Configs don't support

* extraBabelPresets and extraBabelPlugins (use babel instead)
* multipage
* autoprefixer ( use browsers instead)
* dllPlugin
* svgSpriteLoaderDirs
* library
* libraryTarget
* cssModulesExclude

## Config changes

* entry

## New Configs

* babel
* copy
* commons
* browsers
* extraResolveModules

**Comment by yamakasiluke** [comment]
哥哥，你的entry怎么配置

**Comment by sorrycc** [comment]
umi 里不能配 entry，为啥要配？

**Comment by yamakasiluke** [comment]
那么请问多入口如何配置？

**Comment by sorrycc** [comment]
多个页面的入口？在 pages 下新增文件就好了。

**Comment by yamakasiluke** [comment]
这个也是特殊需求可能，多js入口，可以通过webpack的entry配置

**Comment by sorrycc** [comment]
暂不考虑吧，有需求自行通过 webpack.config.js 扩展就好。

**Comment by kwzm** [comment]
您好，那 libraryTarget 就是用 webpack 默认的配置是吗？
