### ISSUE TITLE
Error: Plugin umi-plugin-dva don't exists.

### ISSUE THREAD

**Issue by ctcx** [umijs/umi#300]
看到说是内置了 dva，我直接按照教程在根目录下新建 .umirc.js 文件：
export default {
  plugins: [
    'umi-plugin-dva',
    // 有参数时为数组，数组的第二项是参数，类似 babel 插件
    ['umi-plugin-routes', {
      update() {},
    }],
  ],
};

umi dev 后提示 Error: Plugin umi-plugin-dva don't exists.

然后我又安装了 dva：cnpm i dva --save

再次 umi dev 后依然如此，我哪里做错了？

**Comment by sorrycc** [comment]
插件需要先安装的。

```bash
$ cnpm i umi-plugin-dva --save
```
