### ISSUE TITLE
代码依赖包缺失，启动umi编译不会通过，但不会提示错误原因

### ISSUE THREAD

**Issue by shengbeiniao** [umijs/umi#3004]
## What happens?

![image](https://user-images.githubusercontent.com/3301995/63084911-db725b00-bf7e-11e9-9705-13dddd8e4f93.png)

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：2.8.18
- **Node 版本**：
- **操作系统**：

**Comment by xiaohuoni** [comment]
umi@2.8.18
![image](https://user-images.githubusercontent.com/11746742/64140941-e0695280-ce38-11e9-98ca-02700f60e57c.png)

**Comment by xiaohuoni** [comment]
@shengbeiniao 请给一个可以重现的项目
