### ISSUE TITLE
更新antd到新版(3.21.4)后，所有国际化文本变成null，有报错信息

### ISSUE THREAD

**Issue by effapp** [umijs/umi#3008]
## What happens?
更新antd到新版(3.21.4)后，所有国际化文本变成null，有报错信息

![image](https://user-images.githubusercontent.com/51013754/63155170-a6304080-c044-11e9-9317-83114335fc31.png)

![image](https://user-images.githubusercontent.com/51013754/63155115-931d7080-c044-11e9-860e-8b2c30ae43ef.png)

## Context

- **Umi Version**:2.8.18
- **Node Version**:
- **Platform**:ant design pro 4

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/63209737-83bb2780-c117-11e9-9327-646f98519e68.png)
