### ISSUE TITLE
eslintrc文件修改无效

### ISSUE THREAD

**Issue by fjmhzyh** [umijs/umi#3010]
## What happens?

修改eslintrc文件如下, 重启项目多次依然无效
```
{
  "extends": "eslint-config-umi",
  "rules": {
    "no-unused-vars": 0,
    "eqeqeq": "off",
  }
}
```

## 相关环境信息

- **Umi 版本**：2.8.17
- **Node 版本**：v10.16.0
- **操作系统**：win10

**Comment by sorrycc** [comment]
问题是啥？在哪里无效？

**Comment by fjmhzyh** [comment]
> 问题是啥？在哪里无效？

关闭某些规则以后,控制台依然会提示报错

**Comment by zlab** [comment]
同问

**Comment by liuhaoliang** [comment]
修改eslintrc配置文件无效

**Comment by ligaopeng123** [comment]
tsconfig.json中"noUnusedLocals": true, // 改成false 或者删除
