### ISSUE TITLE
SSR中无法根据cookie确定服务端渲染时用的默认locale设置。

### ISSUE THREAD

**Issue by elivoa** [umijs/umi#3013]
目的是在SSR工程中，在服务端渲染阶段，服务端读取cookie中的语言设置，作为默认的语言来渲染页面html。
以umi-example-ssr-with-egg工程为例，服务端生成的html语言内容为config.ts中的这段
```
  plugins: [
    [
      'umi-plugin-react',
      {
        locale: {
          baseNavigator: false,
          default: 'zh-CN', // <-----
        },
```
我再app/controller/home.js中可以使用ctx.cookies.get来获取到cookie中语言设置，这时候应该如何将cookie中获取的语言设置应用到umi中？

目前服务端还是只能刷新出config.ts中配置的配置。

**Comment by ycjcl868** [comment]
使用 query 吧，`?locale=en-US` https://github.com/umijs/umi-example-ssr-with-egg/blob/master/app/web/app.js#L11-L22

**Comment by elivoa** [comment]
我也调研过，从SEO的角度看，多语言最佳的方案是给不同的语言一个不同的URL，或者用query。
只是现在工程中使用的方法是用cookie记录语言，一下子改过来代价太大了，所以想先继续使用读取cookie的方法兼容一下，下一步改用URL中加入语言的方案。

所以不知道有没有解决方案

**Comment by elivoa** [comment]
这个问题我已经解决了。下面是具体办法如下：

1. 我以 umi-example-ssr-with-egg 工程为基础。
2. 如 @ycjcl868 所说，app.js 中的 export locale.default 方法返回的语言值，会作为此次刷新的语言。例子中是通过query参数来设置语言。
3. 由于我希望从cookie中读取语言设置，因此我在 app/controller/home.js 中使用 ctx.cookies.get 来获取到cookie中语言设置，再将其设置到window.SSR_COOKIE_LANG中。
4. 这样在 app.js 的export locale.default 方法中可以读取到window.SSR_COOKIE_LANG的值并直接返回，作为这次渲染的默认语言。这样可以做到在SSR的服务端渲染阶段可以使用cookie中存储的语言设置来渲染页面（也就是查看页面源码的时候，html中使用多语言的地方才会正确显示成想要的语言）。
5. 但是有一个奇怪的地方，config.ts中的locale配置必须有 baseNavigator: false, 我测试只有存在baseNavigator并且值为false的时候才生效。否则app.js中的语言设置不生效。

```
      locale: {
        enable: true, // default false
        default: 'zh-CN',
        baseNavigator: false, 
      } 
```

**Comment by ycjcl868** [comment]
https://github.com/umijs/umi/pull/3043  这个 pr 可以将 `location` 传到 服务端渲染和客户端 ，通过 `location.search` 来决定 `props.locale`，然后对应相应的国际化。也是可行的。
