### ISSUE TITLE
umi block add 之后区块的路由配置无法直接使用

### ISSUE THREAD

**Issue by theprimone** [umijs/umi#3014]
## What happens?

比如

```shell
umi block add LessonList --path=lessons
```

会生成路由配置

```js
{
  path: '/lessons',
  component: './Lessons',
},
```

但是该配置无法正常使用 dva 的状态

![mMkwIs.png](https://s2.ax1x.com/2019/08/18/mMkwIs.png)

把 `component` 改为 `'./Lessons/LessonList'` 之后，dva 的状态才能正常使用。

## 相关环境信息

- **Umi 版本**：2.8.16
- **Node 版本**：v10.15.1
- **操作系统**：win 10

**Comment by chenshuai2144** [comment]
这个区块是你自己写的吗？

**Comment by theprimone** [comment]
@chenshuai2144 对的，自己写的。是我用法不对吗？

**Comment by chenshuai2144** [comment]
可以看看这里https://umijs.org/zh/guide/block.html#%E5%8C%BA%E5%9D%97%E5%BC%80%E5%8F%91
用宏可以解决这个问题

**Comment by theprimone** [comment]
我确认了一下，应该不是 namespace 冲突的问题。所以是用宏做什么呢？

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/63236087-fc80c780-c26e-11e9-82d2-91747ed38b05.png)
zhe'ge这个地方应该用宏代替的。不应该[name] 这种的

**Comment by theprimone** [comment]
看了下 ant design pro 的[个人中心区块](https://github.com/ant-design/pro-blocks/blob/master/AccountCenter/src/model.ts)，才发现都是用的宏啊。不过还是没懂为什么不能这么直接用呢，宏替换和这种写法不是只是换了个名字吗？:flushed:

**Comment by theprimone** [comment]
试了一下，宏的用法，结果一样的啊，还真就只是换了个变量名而已啊

![mymX8K.png](https://s2.ax1x.com/2019/08/24/mymX8K.png)

**Comment by theprimone** [comment]
123

**Comment by theprimone** [comment]
123

**Comment by xiaohuoni** [comment]
你model里面有没有定义list？感觉与umi无关，是写法问题。

**Comment by theprimone** [comment]
```ts
const Model: ModelType = {
  namespace: 'BLOCK_NAME_CAMEL_CASE',

  state: {
    list: [],
  },

  effects: {
    *fetch({ payload }, { call, put }) {
      const response = yield call(getMyLessons, payload);
      if (isResponseError(response)) {
        console.error(formatMessage({ id: 'hint.getClassesFail' }));
        return;
      }
      yield put({
        type: 'save',
        payload: response,
      });
    },
  },

  reducers: {
    save(state, { payload }) {
      return {
        ...(state as ModalState),
        list: payload.lessons,
      };
    },
  },
};

export default Model;
```

以上是我的 demo ，有初始值的。而且我不是说了把路由再写深入一层，不使用区块自动添加的包裹区块的组件，就可以使用了吗？ \_(:3J∠)\_

**Comment by xiaohuoni** [comment]
给一个可以运行的项目，帮你改一下吧。

**Comment by theprimone** [comment]
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/umi-block-demo-kl1pw)

不知道怎么在 CodeSandbox 使用 umi，但是这个代码我本地测试了一下，一样的问题。
