### ISSUE TITLE
umi-plugin-qiankun 的子应用如果配置了dynamicImport，本地调试要怎么处理呢

### ISSUE THREAD

**Issue by Symboler** [umijs/umi#3015]
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by kuitos** [comment]
supported by 1.0.3 https://github.com/umijs/umi-plugin-qiankun/releases/tag/v1.0.3
