### ISSUE TITLE
部署最新版本到生产环境后，访问到的还是旧内容

### ISSUE THREAD

**Issue by shangdev** [umijs/umi#3017]
感觉是浏览器缓存了内容。
项目并没有启用PWA，应该不是pwa的问题。
这种情况下应该怎么解决这个不同步更新的问题呢？

**Comment by sorrycc** [comment]
可能原因：

0. PWA
1. 代码没更新
2. 浏览器缓存，所以得加时间戳或者 Hash 后缀。
