### ISSUE TITLE
上一页的请求在下一页切换时还会被执行一次

### ISSUE THREAD

**Issue by Hexa-gram** [umijs/umi#3018]
## What happens?
页面切换路由时,上个页面的mapStateToProps函数被强行触发

## Mini Showcase Repository(REQUIRED)

复现地址https://github.com/Hexa-gram/umi-bug  
详细复现步骤在readme中,该问题类似于https://github.com/umijs/umi/issues/2832

**Expected behavior**
1.切换页面不会触发历史栈中任何一个页面的mapStateToProps函数

## Context

- **Umi Version**: 2.7.7
- **Node Version**:10.16.0
- **Platform**:macOs

**Comment by sorrycc** [comment]
是 subscriptions 相关的问题？

**Comment by Hexa-gram** [comment]
> 是和 subscriptions 相关的问题？

subscriptions的listen确实会引发这种问题,但是我不用subscriptions方法,用componentDidMount生命周期,也会有该问题

**Comment by feidudu1** [comment]
是router有问题，去.umirc.js中把dynamicImport设置为 true，但即便这样，虽然不会跳两次，速度也还是慢。应该路由还有别的问题。配置了自己的404.js文件，如果url中没有/404，还是会跳到umi内置的404页面，不能跳到自己自定义的404页面
我也是2.7.7版本的umi

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/2832 同一个问题
