### ISSUE TITLE
IE9下css文件过大加载不全，使用css-split-webpack-plugin分割，分割之后的css没办法自动全部引入

### ISSUE THREAD

**Issue by YunSmile** [umijs/umi#3021]
![image](https://user-images.githubusercontent.com/18326947/63254152-cc085000-c2a5-11e9-8e8c-bd291c25a298.png)

配置如上所示，配置之后浏览器打开显示只加载了最后一个切割文件
![image](https://user-images.githubusercontent.com/18326947/63254229-f2c68680-c2a5-11e9-8589-a5fc17488ced.png)
还请大神们赐教，如何将另外两个切割文件引入。

**Comment by wangxingkang** [comment]
支持 IE9  是个 大BUG

**Comment by wangxingkang** [comment]
这个 好像需要 搞个 umi插件 才可以吧

**Comment by kwzm** [comment]
其实 css-split-webpack-plugin 是可以做到的，你需要设置一下 imports
![QQ截图20191213113529](https://user-images.githubusercontent.com/16114101/70767577-d1c9fa00-1d9c-11ea-83b9-3e62dcf4c2ef.png)
这样最后大的css文件的内容会变成 
```
@import 'xxxx.chunk-1.css'
@import 'xxxx.chunk-2.css'
```

**Comment by YunSmile** [comment]
> 其实 css-split-webpack-plugin 是可以做到的，你需要设置一下 imports
> ![QQ截图20191213113529](https://user-images.githubusercontent.com/16114101/70767577-d1c9fa00-1d9c-11ea-83b9-3e62dcf4c2ef.png)
> 这样最后大的css文件的内容会变成
> 
> ```
> @import 'xxxx.chunk-1.css'
> @import 'xxxx.chunk-2.css'
> ```
谢谢，我试试
