### ISSUE TITLE
如何配置才能去除掉链接中的“#”呢？

### ISSUE THREAD

**Issue by vae13** [umijs/umi#3023]
如何配置才能去除掉链接中的“#”呢？每次build之后，去访问页面的时候总是有一个#，由于要跟后台进行对接，不能含有#号，很是苦恼，我用的umi默认的配置文件
`history: 'browser',
history: 'memory',
history: 'hash',
`
都试过了，都是带有#号

**Comment by zhihongzhong** [comment]
1. 在config.[t|j]s 里面 修改 history 字段的type值为 'browser'
2. 如果服务器的uri前缀和本地不一致，则需要判断是否为生产环境， 根据环境设置 base， 例如：
生产环境的uri前缀为 /public/mobile 则config.[j|t]s 需要做以下处理（假设没有production.config.[j|t]s的情况下）：
export default = {
 base: process.env.NODE_ENV == 'development' ? '/' : '/public/mobile'
};
