### ISSUE TITLE
eslint警告信息没有文件目录信息，错误信息正常。

### ISSUE THREAD

**Issue by sevilen** [umijs/umi#3024]
## What happens?
接手一个项目，有很多警告信息，发现eslint并没有显示警告的文件信息，导致排查修改困难。希望能得到解决。

## 最小可复现仓库
复现仓库地址：https://github.com/sevilen/umi-eslint-warning-no-file-directory
> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
执行`yarn start`
控制台查看警告信息，没有警告具体的文件目录信息。

## 相关环境信息

- **Umi 版本**：@2.7.7
- **Node 版本**：v8.12.0
- **操作系统**：macOS Mojave 10.14.5

**Comment by skczjun** [comment]
我也遇到这个问题 [https://github.com/umijs/umi/pull/3881](url) 你看一下这个是不是可以解决

**Comment by Earlzs** [comment]
> 我也遇到这个问题 [https://github.com/umijs/umi/pull/3881](url) 你看一下这个是不是可以解决

请问怎么解决啊，打开链接没看到解决方法啊
