### ISSUE TITLE
yarn create umi 自带警告！！！

### ISSUE THREAD

**Issue by GeNa-jj** [umijs/umi#3026]
Warning: componentWillMount has been renamed, and is not recommended for use.

Warning: componentWillReceiveProps has been renamed, and is not recommended for use.

yarn create umi 并安装依赖后，直接启动会报2条警告，取了两条警告的第一句。怎么解决，急！！！

**Comment by lanceMe** [comment]
这个是React警告 ，这篇文章有解决办法：https://zh-hans.reactjs.org/blog/2019/08/08/react-v16.9.0.html

**Comment by sorrycc** [comment]
`yarn create umi` 选哪个？

**Comment by GeNa-jj** [comment]
> `yarn create umi` 选哪个？

yarn create umi

**Comment by GeNa-jj** [comment]
> `yarn create umi` 选哪个？

> `yarn create umi`
> `Select the boilerplate type`  app
> `Do you want to use typescript? ` No
> ` What functionality do you want to enable? ` antd, dva

> `cd project`
> `yarn`
> `yarn start`
