### ISSUE TITLE
在css modules情况下切换路由动效无效果

### ISSUE THREAD

**Issue by karchinkong** [umijs/umi#3028]
## What happens?
在css modules情况下切换路由动效无效果

![image](https://user-images.githubusercontent.com/16110331/63338045-a72ede00-c374-11e9-9947-c8415cfd9b69.png)

![image](https://user-images.githubusercontent.com/16110331/63338082-bada4480-c374-11e9-8b31-084ada2058ca.png)

Result: class只有exit,并没有enter的class
![image](https://user-images.githubusercontent.com/16110331/63339252-0d1c6500-c377-11e9-8441-2069dc0a0545.png)

- **Umi Version**: {
    "antd": "^3.19.5",
    "dva": "^2.6.0-beta.6",
    "moment": "^2.24.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-markdown": "^4.1.0",
    "react-syntax-highlighter": "^11.0.2",
    "react-transition-group": "^4.2.2",
    "babel-eslint": "^9.0.0",
    "eslint": "^5.4.0",
    "eslint-config-umi": "^1.4.0",
    "eslint-plugin-flowtype": "^2.50.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.11.1",
    "husky": "^0.14.3",
    "lint-staged": "^7.2.2",
    "react-test-renderer": "^16.7.0",
    "umi": "^2.7.7",
    "umi-plugin-react": "^1.8.4"
  }
- **Node Version**: ">=8.0.0"

**Comment by ycjcl868** [comment]
global.css 不走 css modules，没有 enter className 应该是组件没 render
