### ISSUE TITLE
问题咨询：微服务前端架构问题咨询？

### ISSUE THREAD

**Issue by upcwangying** [umijs/umi#3030]
看了这个项目[umi-plugin-qiankun](https://github.com/umijs/umi-plugin-qiankun),有几个问题咨询.
1. 微服务前端架构中，如何注册新服务？代码中偏手动？个人偏向于自动.
2. 新注册的应用，在主应用重启后，是否会丢失注册信息？
3. 已注册的服务宕机后，如何做到为了保证用户体验，把该应用剔除，而不是显示错误信息？
4. umijs有没有类似的实践？

**Comment by kuitos** [comment]
1. 支持运行时异步配置子应用列表 https://github.com/umijs/umi-plugin-qiankun#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE
2. 主应用重启什么场景，没理解
3. 子应用可以异步注册，注册策略可以自己决定
4. umijs 只是提供能力，怎么实践是看用户怎么用吧，你说的实践是？

**Comment by kuitos** [comment]
close as inactivity
