### ISSUE TITLE
按照文档上写法添加国际化

### ISSUE THREAD

**Issue by k983551019** [umijs/umi#3031]
出现，Invalid key locale from plugin

**Comment by ycjcl868** [comment]
config 里添加 `umi-plugin-react` 插件，并开启 `locale` 配置。

**Comment by k983551019** [comment]
开了，   我重新安装了umi  就好了






------------------ 原始邮件 ------------------
发件人: "信鑫-King"<notifications@github.com>; 
发送时间: 2019年8月21日(星期三) 下午5:05
收件人: "umijs/umi"<umi@noreply.github.com>; 
抄送: "择一城而终老丶"<983551019@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [umijs/umi] 按照文档上写法添加国际化 (#3031)




config 里添加 umi-plugin-react 插件，并开启 locale 配置。
