### ISSUE TITLE
版本问题线上打包失败，看有同样经历的小伙伴吗

### ISSUE THREAD

**Issue by KillianTang** [umijs/umi#3036]
这两天出现打包和运行失败的问题  
----
一开始版本是2.4.2  

重新拉项目后，`npm i`安装依赖，紧接着直接打包，发现全部less文件都处理失败  

然后把依赖删了，版本升到2.8.18，`npm i`再打包，成功  

----
但是今天，又打包失败了  
![image](https://user-images.githubusercontent.com/25997259/63497059-a5405880-c4f5-11e9-8cb4-27392fb4ee0b.png)
  

抱着试一试的心态，把版本降回2.4.2，重新装依赖，打包，成功
  
模拟线上发布，每次我都是删除了依赖，重新安装依赖再打包

不知道有其他小伙伴也有这个问题吗？

## 相关环境信息

- **Umi 版本**：2.4.2
- **Node 版本**：v10.12.0
- **操作系统**：macOS 10.14

**Comment by ycjcl868** [comment]
重新 demo
