### ISSUE TITLE
使用.umi文件夹里的问题

### ISSUE THREAD

**Issue by lzw46209659** [umijs/umi#3037]
问一下，我想在app.js里使用dva或者history，或者说在除了通过组件connect方式，应该怎么使用呢？ 尝试了直接引用.umi文件夹里的文件是可以的，可以取到history和dva的app，但这个是临时文件夹，这是使用方式是正常途径吗? run build之后在生产环境也可以正常使用吗?

**Comment by wxingheng** [comment]
遇到同样的问题，我希望在react的完成可以控制 store, 手动dispatch 二不是通过 connect 的方式

**Comment by feibi** [comment]
window.g_app._store.dispatch ?

**Comment by wxingheng** [comment]
@feibi  是的，谢谢。

**Comment by lzw46209659** [comment]
> window.g_app._store.dispatch ?
不行啊，在app.js里没法用

**Comment by wxingheng** [comment]
@lzw46209659  你要干嘛？ 你应该贴上代码
你的app.js 的时候可能还没有初始化  
打印 winsow.g_app 看看
