### ISSUE TITLE
使用 umi 在华为手机上不渲染页面,加载出空白页

### ISSUE THREAD

**Issue by luoandy** [umijs/umi#304]
如上

**Comment by sorrycc** [comment]
啥出错？在 src/global.js 里引入 @babel/polyfill 试试。

**Comment by luoandy** [comment]
没有报错,在其他手机的页面都能显示,在华为的手机就只能加载空白页

**Comment by sorrycc** [comment]
解决了？

**Comment by luoandy** [comment]
没有,应该是 react 的原因,我使用了原生的写法也不会渲染页面    谢谢

**Comment by clown-helang** [comment]
我也遇到了相同问题，请问怎么解决？

**Comment by mrcaobin** [comment]
遇到相同问题，在华为手机和华为平板上均出现该问题
在src/global.js中加入@babel/polyfill 还是不行

**Comment by xiaohuoni** [comment]
随便写一个简单的demo，就会出现这个问题吗？

**Comment by clown-helang** [comment]
targets: {
    chrome: 58,
    ie: 9,
  },
  exportStatic:{},
我好像这样设置后就可以解决，我是umi2.1

**Comment by jingkeke** [comment]
@clown-helang 的可以......我擦.............试了一天了.........感谢!!!!

**Comment by imhele** [comment]
其实是要加 `android: 4` ...，Android 手机自带的浏览器基本都要加这句

**Comment by shenyiling** [comment]
加载空白后，点击刷新又会渲染内容，请问也是targets设置的问题吗

**Comment by citrusjunoss** [comment]
如何测试target 版本呢

**Comment by citrusjunoss** [comment]
> 如何测试target 版本呢

安卓版本和chrome版本已经降到最低了，其他要怎么降![E5A09F2A-AA8F-4c16-A901-E848295C39F5.png](https://user-images.githubusercontent.com/18432488/90148937-7f6f2c00-ddb6-11ea-8982-9f19261e59ff.png)
