### ISSUE TITLE
Umi 如何调整 dva 依赖为最新版，或者支持 react-redux v7 版本？

### ISSUE THREAD

**Issue by shangdev** [umijs/umi#3041]
###项目概况：

项目中用到了 material-ui v4，但是 material-ui v4 无法运行在 react-redux v5.0.7版本下，而 umi 最新版依赖的 react-redux 仅仅是 v5.0.7。

相关问题：https://stackoverflow.com/questions/56448807/im-getting-error-after-upgrading-to-material-ui-4-withstyles 大致意思是 react-redux v5.0.7 对传入 connect 的 component 进行了验证，验证代码片段如：

```
    invariant(
      typeof WrappedComponent == 'function',
      `You must pass a component to the function returned by ` +
      `${methodName}. Instead received ${JSON.stringify(WrappedComponent)}`
    )
```

所以是否可以升级 react-redux 的版本呢？或者升级 Umi 依赖的 dva 版本为 dva@2.6.0-beta.12，我注意到 dva v2.4.1 以上的 beta 版是把 react-redux v7 作为依赖的。

## 相关环境信息

- **Umi 版本**：v2.8.11
- **Dva版本**: dva@2.5.0-beta.2

![image](https://user-images.githubusercontent.com/15621520/63560386-6b6c6200-c588-11e9-9734-d07592ec038f.png)

**Comment by wangxingkang** [comment]
`yarn add dva@next`

**Comment by wangxingkang** [comment]
最新版本 2.6.0-beta.12

**Comment by shangdev** [comment]
@wangxingkang 

直接这样安装是不行的，报错信息：

```
browser.js:38 Uncaught Invariant Violation: Could not find "store" in either the context or props of "Connect(ConnectedRouterWithContext)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(ConnectedRouterWithContext)".
```

![image](https://user-images.githubusercontent.com/15621520/63667128-30c32d80-c805-11e9-979b-d82a8ab87369.png)

**Comment by wangxingkang** [comment]
https://github.com/ts-react/react-admin-template/blob/master/package.json  我的项目就可以啊

**Comment by shangdev** [comment]
最新版umi已支持dva@2.6.0-beta.6，支持react-redux最新版了

**Comment by nelhu** [comment]
> 最新版umi已支持dva@2.6.0-beta.6，支持react-redux最新版了

3q, you saved me a couple of hours
