### ISSUE TITLE
如何在不使用html-webpack-plugin条件下，使用preload-webpack-plugin？

### ISSUE THREAD

**Issue by ZhouHansen** [umijs/umi#3051]
## What happens?
使用 html-webpack-plugin 会有出现bug ：
https://github.com/umijs/umi/issues/1640

同时umi不建议使用html-webpack-plugin：
https://github.com/umijs/umi/issues/1640#issuecomment-448127249
>  html 是 umi 非常重要的一环，不推荐额外使用 html-webpack-plugin 。

但是preload-webpack-plugin 是基于html-webpack-plugin的插件。
那么如何在不使用html-webpack-plugin条件下，使用preload-webpack-plugin？
或者有什么别的方法可以如何 add `rel="preload"` to `<link>`?

## 相关环境信息

- **Umi 版本**：
2.8.20
- **Node 版本**：
11.0.0
- **操作系统**：
mac

**Comment by amio** [comment]
@stale keep it

**Comment by lighte-chen** [comment]
同样遇到这个问题

**Comment by elevensky** [comment]
+1

**Comment by GSBL** [comment]
为啥没人出来回复呀

**Comment by shlomitsur** [comment]
Any news about this? preload is important

**Comment by tanyplzu** [comment]
+1
