### ISSUE TITLE
权限路由路径解析不正确

### ISSUE THREAD

**Issue by shockw4ver** [umijs/umi#3055]
## What happens?

配置路由后，生成的 router 对权限路由 Routes 中的组件路径解析不正确

## 复现步骤，错误日志以及相关配置

1. 在 config/config.js 中配置路由：
```javascript
{
  //...
  routes: [
    //...
    {
       path: '/classes',
       component: './classes',
       Routes: ['../routes/Pro']
    }
  ]
}
```
2. 得到报错：
```bash
 ERROR  Failed to compile with 1 errors          11:33:21 AM

This relative module was not found:

* ../../../../routes/Pro in ./src/pages/.umi/router.js
```
4. 发现 routes 中解析出来的 Pro 组件路径为 ``../../../../routes/Prop``
3. 其中 routes 文件夹与 pages 文件同级，Pro 的位置应当是 ``../../routes/Pro``

## 相关环境信息

- **Umi 版本**：2.8.7
- **Node 版本**：12.6.0
- **操作系统**：macOS 10.14.2

**Comment by varfate** [comment]
我也遇到了，不得不把 `routes` 放到了与 `src` 同级的目录才能正确解析。

**Comment by shockw4ver** [comment]
经过试验，写成：
```javascript
{
  //...
  routes: [
    //...
    {
       path: '/classes',
       component: './classes',
       Routes: ['./src/routes/Pro']
    }
  ]
}
```
这样是可以用的，但是文档描述的规则，`./`应该是指向 pages 文件夹，并且同一个配置里出现两种路径似乎也不太对...

目前手动将 pages/.umi.js 里的相关路径改成正确的了，但希望官方能说明或修复一下吧。

**Comment by sorrycc** [comment]
是个问题，现在改会有 break-change，等 umi@3 一起改。
