### ISSUE TITLE
[RFC] 如何在VS Code中debug umi，观察编译过程

### ISSUE THREAD

**Issue by shengbeiniao** [umijs/umi#3059]
## 背景

>  经常在群里看到有人问这个问题，现在给出解决方案，以umi inspect命令为例

[vscode debug文档](https://code.visualstudio.com/docs/nodejs/nodejs-debugging)
```
 {
        "name": "inspect umi",
        "type": "node",
        "request": "launch",
        "cwd": "${workspaceFolder:zstack}",
        "program": "${workspaceFolder:cmp}/node_modules/umi/lib/cli.js",
        // "outFiles": ["${workspaceFolder:cmp}/node_modules/umi/lib/**/*/js"],
        "args": ["inspect"],
   }
```

实测outFiles无效，如果debug src/cli.js，所以此处还是选用编译过的文件

${workspaceFolder:}冒号为multi workspaces配置，如果是单一workspace，直接采用${workspaceFolder}即可

现在你可以在cli.js或者.umirc.js愉快的加断点了，轻松改写chainWebpack

**Comment by shengbeiniao** [comment]
如果在本地项目yarn link umi，并变更了umi代码，debug，可以参考这个issue，[debug vscode with npm link](https://github.com/Microsoft/vscode-node-debug/issues/73)

**Comment by baxtergu** [comment]
我有个类似的问题就是：
是否可以基于每个 `packages/xxx/src` 下的代码进行 debug，而不是 rollup 转换后的 `packages/xxx/lib` 去 debug。曾经尝试过开启 nodejs 的 import 支持但是效果不是很理想，请问有没有推荐的方式能够实现类似在 chrome 中调试 webpack 打包后的代码这样？How to contribute 里的内容写得太简易了。

**Comment by shengbeiniao** [comment]
> 我有个类似的问题就是：
> 是否可以基于每个 `packages/xxx/src` 下的代码进行 debug，而不是 rollup 转换后的 `packages/xxx/lib` 去 debug。曾经尝试过开启 nodejs 的 import 支持但是效果不是很理想，请问有没有推荐的方式能够实现类似在 chrome 中调试 webpack 打包后的代码这样？How to contribute 里的内容写得太简易了。

手动编译umi，带上sourcemap
