### ISSUE TITLE
umi/router push ({pathname, query})方法报错

### ISSUE THREAD

**Issue by zhangqianliang** [umijs/umi#3082]
## What happens?
```
router.push({
        pathname: '/search',
        query: {
          s: value,
        },
      });
```
方式报错
`VM631:1 Uncaught RangeError: Maximum call stack size exceeded`

```
router.push(`/search?${stringify({ s: value })}`) 
```
则没有报错

## Context

- **Umi Version**: 2.8.15
- **Node Version**: v12.9.1
- **Platform**: macos 10.14.6 (18G87)

**Comment by INTMIN** [comment]
这两种好像不是一个概念，query这种带值，只是一个key好像
