### ISSUE TITLE
ant-design-pro配置ssr后运行umi.server.js出错

### ISSUE THREAD

**Issue by regreceive** [umijs/umi#3083]
## What happens?
错误信息：Super expression must either be null or a function

## How To Reproduce
**Steps to reproduce the behavior:**
1. 选择创建ant-design-pro项目后，在config.ts里面添加了ssr: true。
2. 启动dev后，在项目根目录下新建server.js

```js
// server.js
global.window = {};
const serverRender = require('./dist/umi.server');
```

```shell
$ node server.js
You are using a whole package of antd, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.
D:\work\my-order\node_modules\umi-utils\node_modules\prettier\index.js:1957
    throw new TypeError("Super expression must either be null or a function");
    ^
...
```

## Context

- **Umi Version**: 2.8.20
- **Node Version**: v10.15.3
- **Platform**: win10

**Comment by weijinnx** [comment]
the same issue!

**Comment by Kwei9** [comment]
你好朋友，请问现在有成功在Ant Design Pro中使用ssr吗？想请教一下

**Comment by weijinnx** [comment]
@Kwei9 I didn't find the solution :(
