### ISSUE TITLE
开启按需加载后，npm start 报错！

### ISSUE THREAD

**Issue by shangdev** [umijs/umi#3087]
开启按需加载后：

![image](https://user-images.githubusercontent.com/15621520/63989656-a5eb7700-cb13-11e9-8aae-f63b527e0fe5.png)

控制台报错，项目无法启动：

![image](https://user-images.githubusercontent.com/15621520/63987616-7b95bb80-cb0b-11e9-88f8-f009151c6090.png)

项目一开始是可以的，但是不清楚现在是什么原因导致的？有可能的原因供参考吗？

**Comment by Inori-Lover** [comment]
我觉得把完整的umi配置脱敏后丢出来比较好

**Comment by shangdev** [comment]
> 我觉得把完整的umi配置脱敏后丢出来比较好

已更新为完整的配置图了

**Comment by xiaohuoni** [comment]
试试配置
```
dynamicImport: {
      webpackChunkName: true,
      level: 3,
    },
```
还是不行，提供一下umi版本，最好能有一个复现demo

**Comment by shangdev** [comment]
@xiaohuoni 

试了，还是不行，把 404.js 删了也不行。我试着复现，但新创建的 umi app 就好好的，没问题。应该还是我代码哪里不规范导致的吧，，

**Comment by xiaohuoni** [comment]
@shangdev 不开按需加载，可以吗？

**Comment by shangdev** [comment]
@xiaohuoni 不开可以，正常启动。

看这个保存信息是models出错了，umi版本是 "^2.7.7"，"umi-plugin-react": "^1.6.0"，"react": "^16.8.0"；

这个是组件的写法（类组件）：

```
import React from 'react';
import { withStyles } from '@material-ui/core';
import styles from '@/utils/pageLayout';

class Index extends React.Component {
  ...
}

function mapStateToProps(state) {
  const { companies, accounts, currentCompany } = state.account;

  return {
    loading: state.loading.models.account,
  };
}

export default connect(mapStateToProps)(withStyles(styles)(Index));
```

不知道和 class 组件有没有关系，因为目前大多数项目都切换到了函数组件、

**Comment by xiaohuoni** [comment]
class 组件没关系的，我们项目有全是class组件的，你要不要试试更新到最新umi@2.8.20，umi-plugin-react@1.9.19？

**Comment by shangdev** [comment]
其实已经是最新版了

![image](https://user-images.githubusercontent.com/15621520/64002642-15299100-cb3d-11e9-9b5e-743de87ec202.png)

**Comment by xiaohuoni** [comment]
这个机器人有点问题，刚添加的 label ，判断的是创建时间。

**Comment by shangdev** [comment]
@xiaohuoni 

更新到最新版，问题解决了，，

```
"umi": "^2.9.2",
"umi-plugin-react": "^1.9.19"
```

之前是：
```
"umi": "^2.8.11",
"umi-plugin-react": "^1.6.0"
```

我以为带 ^ 的版本会自动安装最新版的，其实还是有区别的，必须得指定才行///
