### ISSUE TITLE
umi-plugin-routes locale 失效

### ISSUE THREAD

**Issue by zywkuo** [umijs/umi#3088]
升级到
    "umi": "^2.8.20",
    "umi-plugin-react": "^1.9.19"
后 antd默认中文失效，
降级到
    "umi": "^2.6.13",
    "umi-plugin-react": "^1.7.4"
后可以使用

## 相关环境信息

- **Umi 版本v2.6.13**：
- **Node 版本v12.8.1**：
- **antd 版本v3.22.1**：
- **操作系统mac os**：

**Comment by afc163** [comment]
给一个重现看看？

**Comment by zywkuo** [comment]
降级了之后antd提示，语言设置需要使用ConfigProvider
![WX20190830-111210](https://user-images.githubusercontent.com/21994183/63990658-67f05200-cb17-11e9-8bb8-5f7a6254f631.png)
重新升级后antd的默认语言就变为英文了。
![WX20190830-112426](https://user-images.githubusercontent.com/21994183/63991018-be11c500-cb18-11e9-90c3-f531a614cbaf.png)
我看了一下做了兼容处理，但是要修改这个default为中文怎么修改呢？
<img width="670" alt="WX20190830-113140@2x" src="https://user-images.githubusercontent.com/21994183/63991296-c1598080-cb19-11e9-84eb-fa30caa01aaa.png">

**Comment by zywkuo** [comment]
可能需要引用 antd ConfigProvider来替换LocaleProvider。
<img width="507" alt="WX20190830-113750@2x" src="https://user-images.githubusercontent.com/21994183/63991512-bf43f180-cb1a-11e9-9022-341219bf4bef.png">
<img width="830" alt="WX20190830-113759@2x" src="https://user-images.githubusercontent.com/21994183/63991518-c408a580-cb1a-11e9-8a3b-7353f476316c.png">
修改后使用的为中文。

**Comment by ycjcl868** [comment]
antd 版本多少

**Comment by ycjcl868** [comment]
写了一个复现：https://codesandbox.io/s/epic-chatelet-s7fqx

**Comment by zywkuo** [comment]
不知道怎么搞了，我直接把umi-plugin-react 插件locale: false了，然后在layouts布局中用引入ConfigProvider将组件包裹起来，引入zhCN使用，暂时解决了。
