### ISSUE TITLE
用例挂了

### ISSUE THREAD

**Issue by afc163** [umijs/umi#3089]
## What happens?

https://github.com/umijs/umi/runs/201352919

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
就一个 MacOS 下是有问题，其他都过的，应该是环境问题，还没细查。
