### ISSUE TITLE
引入ant-design-pro组件后build dll无法通过

### ISSUE THREAD

**Issue by webup** [umijs/umi#309]
./node_modules/ant-design-pro/es/Login/index.js
Module parse failed: Unexpected character '@' (10:0)
You may need an appropriate loader to handle this file type.
| import styles from './index.less';
|
| @Form.create()
| class Login extends Component {
|   static defaultProps = {

会出现上述错误，目前在dll插件那边直接exclude掉ant-design-pro可以规避。

**Comment by sorrycc** [comment]
decorator 的问题应该已经没了，babel 自己升级后加上了，有问题再 reopen 。
