### ISSUE TITLE
[RFC] umi@3 支持Keep Alive 试用方案

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#3091]
可以使用 @alitajs/keep-alive。需要使用组件包裹 layout 的最内层。原理就是劫持了 `children `

## 安装
```
yarn add @alitajs/keep-alive
```
## 配置

```ts
export default {
  plugins:['@alitajs/keep-alive'],
  keepalive:['/list']
}
```

## 使用

```tsx
// src/layouts/index.tsx
import { KeepAliveLayout } from 'umi';
const BasicLayout: React.FC = props => {
  return (
    <OtherLayout >
        <KeepAliveLayout {...props}>{children}</KeepAliveLayout>
    </OtherLayout>
  );
};
```

## 解除缓存

```tsx
// src/pages/list/index.tsx
import { dropByCacheKey } from 'umi';
const Page: React.FC = props => {
  return (
      <div onClick={()=>{
          dropByCacheKey('/list');
      }}>Click dropByCacheKey
    </div>
  );
};
```

### 动态修改 keepalive 配置

```ts
// 假如 config 中配置 keepalive: []
import { patchKeepAlive } from 'umi';
const Page: React.FC = (props) => {
  return (
    <div
      onClick={() => {
        //
        patchKeepAlive((config) => {
          // 这里可以获取到最新的 keepalive 配置
          config.push('/list');
          // 操作配置之后返回
          return config;
        });
      }}
    >
      Click patchKeepAlive
    </div>
  );
};
```

**Comment by hzcdt** [comment]
也许还有方案三，其它方案都是基于路由的做缓存，而且都是通过display:none|block来控制组件的展示和隐藏，而我前两天在github意外发现的react-keep-alive是通过 React.createPortal把需要缓存的组件渲染到应用程序的外面，这样就是直接基于组件而不是基于路由，对react-router就没那么大的依赖了

**Comment by hzcdt** [comment]
[https://github.com/StructureBuilder/react-keep-alive/blob/master/README.zh-CN.md](url)

**Comment by xiaohuoni** [comment]
欢迎讨论

**Comment by burro630** [comment]
> 欢迎讨论

到底怎么用哦，没看明白，能详细说说基于目前的umi框架怎么使用keepalive吗，或者有没有其他实现方式，我是移动端在用 返回到前一个页面怎么保持页面不刷新

**Comment by wangxingkang** [comment]
还没实现

**Comment by CJY0208** [comment]
> 也许还有方案三，其它方案都是基于路由的做缓存，而且都是通过display:none|block来控制组件的展示和隐藏，而我前两天在github意外发现的react-keep-alive是通过 React.createPortal把需要缓存的组件渲染到应用程序的外面，这样就是直接基于组件而不是基于路由，对react-router就没那么大的依赖了

`react-keep-alive` 如果能完全实现的话，应该是更好的方案，不过目前有发现对 React 的 Context 功能造成影响，今天给作者提供了 issue 

https://github.com/StructureBuilder/react-keep-alive/issues/36

**Comment by xiaohuoni** [comment]
如果不依赖route方案的话，应该可以通过插件实现，我试试。

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/64328049-5fa88300-cfff-11e9-9213-7daaef54648c.png)

**Comment by xiaohuoni** [comment]
`data-reactroot=""` 没了，不知道有没有影响ssr功能，需要进一步验证

**Comment by CJY0208** [comment]
补充最近开发的工具，[react-activation](https://github.com/CJY0208/react-activation) ，纯粹的、不依赖 Router 的 `<KeepAlive>` 方案

但由于实现方式原因，将对 React 本身造成一定[影响]https://github.com/CJY0208/react-activation#breaking-change，仅做方案补充

[示例](https://codesandbox.io/s/affectionate-beaver-solkt)

![test](https://user-images.githubusercontent.com/18415774/65132988-78b82780-da34-11e9-8256-6544ba4ed036.gif)

**Comment by CodeMonkeyLin** [comment]
keep-alive需求什么时候能发布到umi版本？

**Comment by AielloChan** [comment]
Try https://github.com/AielloChan/KeepAliveRoute

**Comment by xiaohuoni** [comment]
https://www.npmjs.com/package/umi-plugin-cache-route
先用插件实现，详细看README

**Comment by aidenwei** [comment]
> https://www.npmjs.com/package/umi-plugin-cache-route
> 先用插件实现，详细看README

好用！这个版本组合试过：
"umi-plugin-cache-route": "1.1.0",
"umi": "2.10.6",
"umi-plugin-react": "1.12.7"

**Comment by xiaohuoni** [comment]
@CJY0208 瞧一瞧看一看，十块钱买不了吃亏，买不了上当。
`keepalive的组件外层会比普通组件多一个无样式的div`

**Comment by CJY0208** [comment]
> @CJY0208 瞧一瞧看一看，十块钱买不了吃亏，买不了上当。
> `keepalive的组件外层会比普通组件多一个无样式的div`

@xiaohuoni @aidenwei 是会多出一个包裹容器，关于展示的控制样式会加在这个容器上，避免影响内部容器本身的样式

确实存在影响层级容器布局的可能性，所以 cache-route 暴露了 className 和 behavior 属性来对包裹层 div 进行控制

https://github.com/CJY0208/react-router-cache-route/blob/master/README_CN.md#cacheroute-%E5%B1%9E%E6%80%A7%E8%AF%B4%E6%98%8E

可以参考此处，考虑如何结合到 umi-plugin-cache-route 中

**Comment by wangyinwei1** [comment]
@xiaohuoni 计划什么时候合并keep-alive

**Comment by xiaohuoni** [comment]
@wangyinwei1 你好，暂时还没有定期，你可以先通过插件https://www.npmjs.com/package/umi-plugin-cache-route 使用，详细看README

**Comment by wangyinwei1** [comment]
![image](https://user-images.githubusercontent.com/15857725/67645909-63ed7e80-f966-11e9-9d71-44a1c3275d1c.png)

**Comment by wangyinwei1** [comment]
![image](https://user-images.githubusercontent.com/15857725/67645971-ae6efb00-f966-11e9-9c49-54fa9fcdced8.png)

**Comment by wangyinwei1** [comment]
![image](https://user-images.githubusercontent.com/15857725/67646020-ff7eef00-f966-11e9-9e7d-73b0b515a81c.png)
![image](https://user-images.githubusercontent.com/15857725/67646029-09085700-f967-11e9-9d0e-35b6fa52c0e7.png)
请问我这个是哪配置错了吗？安装你上面的步骤配置的，但是启动报错了

**Comment by wangyinwei1** [comment]
> @wangyinwei1 你好，暂时还没有定期，你可以先通过插件https://www.npmjs.com/package/umi-plugin-cache-route 使用，详细看README
可用于生产，请问开发环境下可用吗？

**Comment by wangyinwei1** [comment]
![que](https://user-images.githubusercontent.com/15857725/67826654-36403b00-fb08-11e9-8b36-a23bdaed7ef1.gif)
嵌套路由切换。keep-alive就不缓存了这个问题解决下@xiaohuoni

**Comment by fengyun2** [comment]
**version:**

```json
"umi": "^2.11.1",
"umi-plugin-cache-route": "^1.1.0",
```

**报错信息：**

```shell
$ umi dev
×  error     Plugin user:node_modules/umi-plugin-cache-route/lib/index.js initialize failed

Cannot read property 'keepalive' of undefined
```

**Comment by see365** [comment]
安装了插件 也执行了 umi keepalive   但是从umi导出dropByCacheKey 提示没有

**Comment by see365** [comment]
执行dropByCacheKey 也没有清除 重新打开路由还是缓存着数据呀

**Comment by xiaohuoni** [comment]
应该会有清除。需要提供一个复现demo。

**Comment by zyqq** [comment]
照着用了为啥没生效，    
"umi": "^2.10.7",
    "umi-plugin-cache-route": "^2.0.0",
    "umi-plugin-react": "^1.12.8"

**Comment by zyqq** [comment]
![image](https://user-images.githubusercontent.com/15664576/70139066-a8d6a480-16cc-11ea-8c86-9e074045eaf3.png)
![image](https://user-images.githubusercontent.com/15664576/70139074-ae33ef00-16cc-11ea-802a-bf7d9d442e86.png)

**Comment by LiuL0703** [comment]
使用umi-plugin-cache-route插件初始化报错
```
// .umirc.js
export default {
  plugins: [
    ['umi-plugin-cache-route', {
      keepalive:['path']
    }],
  ],
```
`yarn  run  init`
```js
Overwrite:node_modules/umi/lib/renderRoutes.js
Overwrite Success!
✖  error     Plugin user:node_modules/umi-plugin-cache-route/lib/index.js initialize failed

/node_modules/umi-plugin-cache-route/lib/index.js: api.addUmiExports is not a function (75, 7)

  73 |   }); // import { dropByCacheKey } from 'react-router-cache-route';
  74 | 
> 75 |   api.addUmiExports([{
     |       ^
  76 |     specifiers: ['dropByCacheKey'],
  77 |     source: 'react-router-cache-route'
  78 |   }]);
  79 | }
error Command failed with exit code 1.
```
```js
"umi": "2.4.4",
"umi-plugin-cache-route": "^2.0.0",
```

**Comment by xiaohuoni** [comment]
@LiuL0703 umi版本太低了。

**Comment by xiaohuoni** [comment]
@CJY0208 哥哥，推进一下这个事情吧

**Comment by yinhangfeng** [comment]
> https://www.npmjs.com/package/umi-plugin-cache-route
> 先用插件实现，详细看README

可以把 react-router-cache-route 的 when 属性配置暴露出来么，或者默认值改为 forward

**Comment by LiuL0703** [comment]
页签切换正常通过导航切换页签状态带不过去 @xiaohuoni

**Comment by LiuL0703** [comment]
手动解除keep无效 是什么原因呢?和版本有关吗
```
"umi": "2.10.6",
"umi-plugin-cache-route": "2.0.0",
```

**Comment by Fea-Sin** [comment]
手动清除 keep 无效

```js
import { dropByCacheKey } from 'umi';

dropByCacheKey undefined
```


```
"umi": "2.12.6",
"umi-plugin-cache-route": "2.0.0",
```

**Comment by xiaohuoni** [comment]
看一下这个文件 `src/pages/.umi/umiExports.js`

**Comment by Fea-Sin** [comment]
```
src/pages/.umi/umiExports 文件有三个
src/pages/.umi/umiExports.d.ts 为空
src/pages/.umi/umiExports.js 为空

src/pages/.umi/umiExports.ts 内容为
export { dropByCacheKey } from 'react-router-cache-route';
```

项目中如此使用，可以清除 keep
```js
  import { dropByCacheKey } from 'react-router-cache-route';

  const clearCache = () => {
    dropByCacheKey('/list');
  };
```

**Comment by xiaohuoni** [comment]
应该是 https://github.com/umijs/umi/issues/3805 这个问题

**Comment by xiaohuoni** [comment]
删除 `src/pages/.umi` 文件夹重启 `umi dev` 应该就可以了

**Comment by yruson** [comment]
着实有必要官方支持

**Comment by xiaohuoni** [comment]
umi@3 可以使用 @alitajs/keep-alive。配置和用法和umi-plugin-cache-route 基本保持一致。不再需要执行init命令。需要使用组件包裹layout的最内层。
```ts
import { KeepAliveLayout } from 'umi';
const BasicLayout: React.FC = props => {
  return (
    <OtherLayout >
        <KeepAliveLayout {...props}>{children}</KeepAliveLayout>
    </OtherLayout>
  );
};
```

**Comment by johanazhu** [comment]
下个项目用上

**Comment by zhfish** [comment]
顶一下~~

**Comment by huzhichong** [comment]
给力，解决了我疼痛的问题。

**Comment by snice** [comment]
umi3 集成失败

**Comment by xiaohuoni** [comment]
@snice 是要结合layout使用吧。用 @alitajs/plugin-layout ，https://github.com/alitajs/alita/issues/128

**Comment by snice** [comment]
> @snice 是要结合layout使用吧。用 @alitajs/plugin-layout ，[alitajs/alita#128](https://github.com/alitajs/alita/issues/128)

我用的是@ant-design/pro-layout

**Comment by stillyu** [comment]
Cannot read property 'pathname' of undefined  at BasicLayout.render (KeepAliveLayout.tsx:72)
umi3，集成失败

**Comment by xiaohuoni** [comment]
@stillyu props需要透传，你应该是漏了

**Comment by xiaoshuoyiyi** [comment]
大佬，上面那个配置，是在哪个配置文件里的？

**Comment by xiaohuoni** [comment]
@xiaoshuoyiyi 说的配置指的是 umirc 或者 config/config 文件。运行时配置指的是 src/app 。所有的 umi 文档都是这样

**Comment by pwh19920920** [comment]
layout嵌套的情况下支持么？

**Comment by xiaohuoni** [comment]
@pwh19920920 https://github.com/alitajs/alita/tree/master/packages/layout 看看这里，是没有问题的。如果你的场景有问题，可以给一个复现demo。

**Comment by Jsen0926** [comment]
@alitajs/keep-alive方案目前初次尝试问题不大，但是生成的 class="rumtime-keep-alive-layout"里面的第一级元素为什么要使用 position: "absolute" 定位？是有特殊考虑吗

**Comment by xiaohuoni** [comment]
@Jsen0926 
之前在rn中的用法，有没撑开页面的问题，所以这么写了。一直没改。有影响到你们的布局吗？

**Comment by pwh19920920** [comment]
> @pwh19920920 https://github.com/alitajs/alita/tree/master/packages/layout 看看这里，是没有问题的。如果你的场景有问题，可以给一个复现demo。

能否给个demo，这个文档愣是没看懂。。。

**Comment by finalreturn** [comment]
mark   等一个Keep Alive，满足多tab

**Comment by xiaohuoni** [comment]
@finalreturn  https://www.npmjs.com/package/@alitajs/@alitajs/tabs-layout 同样技术实现的，多tabs 。可以尝试能否解决，预览页面 https://pro.alitajs.com/

**Comment by xiaohuoni** [comment]
这个 issues 锁了，有疑问和其他问题可以，单独找我，或者另开 issues

**Comment by xiaohuoni** [comment]
umi-plugin-keep-alive 支持 umi3.x了
https://github.com/alitajs/umi-plugin-keep-alive
