### ISSUE TITLE
@umijs/plugin-qiankun 子应用无法运行

### ISSUE THREAD

**Issue by chj-damon** [umijs/umi#3095]
## What happens?
@umijs/plugin-qiankun 子应用无法运行

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

https://github.com/chj-damon/umijs-plugin-qiankun-subapp-reproduce

## How To Reproduce
**Steps to reproduce the behavior:**
1. yarn
2. yarn start

**Expected behavior**
应用可以正常运行

## Context

- **Umi Version**: ^2.7.0
- **Node Version**: v10.16.0
- **Platform**: macos Mojave 10.14.6

**Comment by kuitos** [comment]
子应用是需要放到主应用中才能跑起来的

**Comment by chj-damon** [comment]
@kuitos umi-plugin-qiankun 里面提供的examples是可以单独跑起来的。

**Comment by chj-damon** [comment]
另外，如果我把@umijs/plugin-qiankun这个插件去掉，我的应用就可以跑起来了。所以，我还是觉得应该是这个插件有问题。

**Comment by kuitos** [comment]
see https://github.com/umijs/umi-plugin-qiankun/blob/master/examples/app1/app.js#L3

**Comment by chj-damon** [comment]
谢谢！我先验证一下。

**Comment by huanglei1991** [comment]
不在这个demo下运行  按这个demo 的方式配置都跑不起来。。

**Comment by huanglei1991** [comment]
求一个直接使用 npm 依赖运行的demo

**Comment by huanglei1991** [comment]
原因找到了。。。app.js 或者app.ts 如果有src 目录一定要放src下  不怎么用这个文件所以不清楚
