### ISSUE TITLE
umi ui 2.9.0-beta.5 反馈和建议

### ISSUE THREAD

**Issue by afc163** [umijs/umi#3103]
- [x] 右下角语言切换，弹层应该包括中英文两个选项，当前的打勾。
- [x] 右下角语言切换，建议去掉最右侧的切换图标，给人感觉是点击切换（实际是点击弹层选择切换）。
  <img width="72" alt="图片" src="https://user-images.githubusercontent.com/507615/64060090-a6ab0880-cbfa-11e9-860c-723e9371ac2c.png">
- [x] 启动命令行建议展示 umi/bigfish 版本号，方便定位排查。
- [x] UI 界面中建议展示 umi/bigfish 版本号，方便定位排查。
- [x] `UmiUI` 和 `umi ui` 是不是统一写成 `Umi UI`？我看到几处地方不太统一。
- [x] 创建应用时，文件名要写清楚正确的规则（目前只是提示无效），错误提示和 placeholder 里都要写清。
    <img width="158" alt="图片" src="https://user-images.githubusercontent.com/507615/64060083-95fa9280-cbfa-11e9-92fe-91aee884f92a.png">
- [x] 帮助链接是否应该链接到 Umi UI 的说明文档中，而不是 umi 首页。（Bigfish 同理）
- ~~[ ] 反馈链接目前是微信？1）微信二维码几天就失效了，不妥。2）是否应该是外网 issue 地址，内网语雀讨论区地址？~~，改成微信 + 钉钉二维码的组合
- [x] 新建页面下一步应该始终在首页（无论浏览器多高，建议目录选择的高度用 `calc(100vh - xxxpx)` 实现），现在基本上在第一屏边缘或者外面。
   <img width="923" alt="图片" src="https://user-images.githubusercontent.com/507615/64060118-0e615380-cbfb-11e9-9b71-cc9e532fbb6a.png">

**Comment by afc163** [comment]
- [ ] `友情提示：单击选择，双击进入`，这一句话的 `友情提示：` 可删，没什么作用。

**Comment by afc163** [comment]
- [ ] 本地通过 `cnpm i umi@2.9.0-beta.5 -g` 装的 umi，创建项目时提示版本过低。
  <img width="352" alt="图片" src="https://user-images.githubusercontent.com/507615/64060185-dc9cbc80-cbfb-11e9-9139-46796cc3b1b0.png">

**Comment by afc163** [comment]
- [ ] 从列表页面点击卡片进入详情，丢失了 history 导致无法直接点击浏览器返回按钮。
<img width="179" alt="图片" src="https://user-images.githubusercontent.com/507615/64060224-31403780-cbfc-11e9-90fd-1904f75dd837.png">

**Comment by afc163** [comment]
- [ ] Empty 处可以加一句：项目列表为空，试试[创建](xx)或[导入](xx)一个项目
<img width="235" alt="图片" src="https://user-images.githubusercontent.com/507615/64060330-a06a5b80-cbfd-11e9-90ed-13458eabeb93.png">

**Comment by zombieJ** [comment]
> Select 组件选中效果目前的颜色下容易搞错，是不是统一选中加钩？

Select 单选不支持自定义图标，更新 4.x 的新 Select 会支持。伪类可以做但是先别急 @ycjcl868

**Comment by afc163** [comment]
- [ ] 项目详情，标题上应该有当前项目的名字。
  <img width="261" alt="图片" src="https://user-images.githubusercontent.com/507615/64072174-de7a8480-ccbc-11e9-946d-307f8359ef0c.png">

- [ ] 最近打开不知道是什么意思，也不能点。 
  <img width="190" alt="图片" src="https://user-images.githubusercontent.com/507615/64072163-965b6200-ccbc-11e9-93b9-202ad50dbc9d.png">

- [ ] 执行任务时，日志这里应该是红色的字？
<img width="959" alt="图片" src="https://user-images.githubusercontent.com/507615/64072168-b0954000-ccbc-11e9-8dda-6cc27e3d9164.png">

**Comment by afc163** [comment]
- [ ] 配置管理和任务管理后面的『管理』都是多余的文字，建议删除。

**Comment by afc163** [comment]
- [ ] 这里的间距看着很不舒服。

<img width="310" alt="图片" src="https://user-images.githubusercontent.com/507615/64072189-3618f000-ccbd-11e9-98cb-9d7babc69f10.png">

**Comment by afc163** [comment]
- [ ] 这里的『项目』不能点，也没有高亮，我点了好几次。

<img width="103" alt="图片" src="https://user-images.githubusercontent.com/507615/64072200-59dc3600-ccbd-11e9-94d3-4c3c3b758314.png">

**Comment by afc163** [comment]
- [ ] 点击配置子菜单的时候重复刷新。已经在这个页面了，应该不需要再 reload。

<img width="284" alt="图片" src="https://user-images.githubusercontent.com/507615/64074114-e137a280-ccd9-11e9-8476-ede0e74c5604.png">

- [ ] 点击右上角『打开配置文件』没有任何反应。

**Comment by afc163** [comment]
- [ ] 点击左下角目录时弹出一个奇怪的对话框。（Firefox 下）

<img width="815" alt="图片" src="https://user-images.githubusercontent.com/507615/64074145-3b386800-ccda-11e9-916e-3e13360a60d9.png">

- [ ] 从项目详情返回项目列表时，左下角的当前目录依然是之前的项目目录。

- [ ] 点击左下角目录时，目前的行为是复制路径，貌似没什么用，是否改成『命令行打开此目录』或者『编辑器打开此目录』

**Comment by afc163** [comment]
- [ ] 这个对话框打开时左上角有个奇怪的白点。（Firefox）

<img width="633" alt="图片" src="https://user-images.githubusercontent.com/507615/64074295-edbcfa80-ccdb-11e9-9adf-9eff0c39bb1c.png">

**Comment by afc163** [comment]
- [ ] 命令行里有光标，导致滚动条下面还有一段。

<img width="994" alt="图片" src="https://user-images.githubusercontent.com/507615/64074382-10034800-ccdd-11e9-9ff6-ab303d124023.png">

**Comment by afc163** [comment]
- [ ] Notification 里要统一打上项目名前缀或后缀，不然可能分不清是哪个项目报的问题。（尤其是原生弹出来的）

**Comment by sorrycc** [comment]
该修的已经修完。
