### ISSUE TITLE
[Feature Request] umi如何在进入系统时做初始化的全局性异步工作，之后再进行页面渲染

### ISSUE THREAD

**Issue by BearGS** [umijs/umi#3104]
umi如何在进入系统时做初始化的全局性异步工作，之后再进行页面渲染

**Comment by atzcl** [comment]
[app.(js|ts)](https://umijs.org/zh/guide/app-structure.html#src-app-js-ts) 的 [render](https://umijs.org/zh/guide/runtime-config.html#render) 不能满足你的需求嘛？

**Comment by zhouccccc** [comment]
@atzcl @xiaohuoni 
目前在做的项目是 umi3 + Dva. 现在有个需求也是如标题所示，我尝试在render方法中调用dva做一些异步初始化工作，但是遇到一个问题:
`export function render(oldRender) {
  setTimeout(() => {
    console.log(getDvaApp);
  });
  oldRender();
}`
这种情况下可以拿到 Dva实例，但是 render()在外面，就是同步渲染了。但是如果这样写
`export function render(oldRender) {
  setTimeout(() => {
    console.log(getDvaApp);
    oldRender();
  });
}`
就无法获取到Dva实例了, 所以大神有Nice建议吗？
