### ISSUE TITLE
about npm dependencies

### ISSUE THREAD

**Issue by JarVan007** [umijs/umi#313]
提示 warning : "umi > babel-preset-umi > @babel/plugin-proposal-async-generator-functions@7.0.0-beta.44" has unmet peer dependency "@babel/core@7.0.0-beta.44" 
但是我看了一下 npm balel-core 的版本只有7.0.0-beta.3 这是什么情况哦~

**Comment by sorrycc** [comment]
@babel/core，不是 babel-core
