### ISSUE TITLE
@ant-design/icons 始终在umi.js中

### ISSUE THREAD

**Issue by beeant0512** [umijs/umi#3130]
## What happens?
自定义 splitChunks 实现 ant-design 单独分包 ，但是分包后ant-design/icons 还是在umi.js中 没有实现分包的目的

## How To Reproduce
**Steps to reproduce the behavior:**
1.
配置如下
```
  cacheGroups: {
     ......
    antd: {
          test: module => {
            const packageName = getModulePackageName(module) || '';
            return packageName === '@ant-design' || packageName === 'antd'
          },
          name: 'antd',
        }
}
```
2.

## Context

- **Umi Version**: ^2.8.7
- **Node Version**: v10.16.0
- **Platform**: windows10

**Comment by ycjcl868** [comment]
antd 3.x 里会引入，这样分包不能解决。具体方案可参考 https://github.com/ant-design/ant-design/issues/12011#issuecomment-417993223
