### ISSUE TITLE
子项目使用@umijs/plugin-qiankun，.umirc.js开启dll，会因为跨域问题导致无法加载

### ISSUE THREAD

**Issue by feibi** [umijs/umi#3131]
## What happens?
子项目使用umi技术栈，在`umi dev`下
- .umirc.js开启dll，主项目加载子项目时会报umi.dll.js跨域问题。

`Access to fetch at 'http://localhost:9000/umi.dll.js' from origin 'http://localhost:7099' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled`

- .umirc.js关闭dll，主项目加载正常。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1. 配置 .umirc.js
```js
...
plugins: [
    '@umijs/plugin-qiankun/slave',
    [
      'umi-plugin-react',
      {
        dva: {
          immer: true
        },
        hd: false,
        fastClick: false,
        routes: {
          exclude: [
            /model\.(j|t)sx?$/,
            /service\.(j|t)sx?$/,
            /models\//,
            /utils\//,
            /extends\//,
            /components\//,
            /services\//
          ]
        },
        dll: {
          exclude: ['@umijs/plugin-qiankun'],
          include: ['antd/es']
        },
        antd: true
      }
    ]
  ]
```
2. app.js挂载
```js
import * as app from '@tmp/umi';
if (!window.isMain) {
  setTimeout(() => {
    app.bootstrap().then(() => {
      app.mount();
    });
  }, 0);
}
```

**Expected behavior**
1. 开启dll时，子项目被正常加载

## Context

- **Umi Version**: umi@2.8.17
- **Node Version**: v10.15.0
- **Platform**: window10

**Comment by sssession** [comment]
+1

**Comment by atzcl** [comment]
配置了
```
devServer: {
        ...,
        headers: {
          'Access-Control-Allow-Origin': '*',
        },
      },
```

依然不行，，
