### ISSUE TITLE
umi ui 版本为 2.9.0 在umi ui创建项目提示创建失败

### ISSUE THREAD

**Issue by sunhaixin06** [umijs/umi#3133]
![终端报错的原因](https://user-images.githubusercontent.com/29425276/64101723-080cdc00-cda1-11e9-8f25-571791f5d4db.jpg)
## What happens?
umi ui 版本为 2.9.0 在umi ui创建项目提示创建失败 原因如下 
npm update --registry=https://registry.npm.taobao.org -d
执行完后还是创建项目失败

## How To Reproduce
**Steps to reproduce the behavior:**
1.在创建项目时出现 create-umi报错
2.报错原因为 npm update --registry=https://registry.npm.taobao.org -d
3.执行完后还是创建项目失败

## Context

umi ui@2.9.0
cnpm@6.1.0
npm@6.11.2
node@12.9.1
:

**Comment by ycjcl868** [comment]
npm 执行权限问题

**Comment by sorrycc** [comment]
怎么看出是权限问题？

**Comment by taoveweb** [comment]
同问

**Comment by tomatobybike** [comment]
umi@3.2.28 也是同样的问题。 鸡肋，umi ui 完全用不了啊
