### ISSUE TITLE
【问题咨询】项目中用脚手架规范目录

### ISSUE THREAD

**Issue by junjiebyr** [umijs/umi#3145]
目前项目中使用的是umi，但是随着页面的增多，参与开发人员也越来越多，就很难保证项目目录能够统一规范，比如接口放哪  配置文件放哪等问题。所以有了想定制一个小工具，创建页面时将页面目录能够定制化。目前看文档有这么一句话：

![image](https://user-images.githubusercontent.com/26082207/64142375-42788680-ce3e-11e9-9f93-534366925032.png)

所以想问一下有例子去扩展generate吗，还是用node做一个命令行小工具来的快呢？谢谢~

**Comment by xiaohuoni** [comment]
我觉得如果你们有定制化的需求，最简单的是fork [create-umi](https://github.com/umijs/create-umi)

**Comment by sorrycc** [comment]
`umi g` 可以扩展的，写一个插件，参考 umi-plugin-dva 的插件实现，他实现了一个 `umi g dva:model`。
