### ISSUE TITLE
npm start时，构建过程为什么经常会卡住？

### ISSUE THREAD

**Issue by xuanxuan321** [umijs/umi#3147]
## What happens?
npm start时，构建过程经常会卡住，进度条一直没有反应。我是使用npm create umi，选择ant-design-pro 这套模板创建的应用，没有做任何的修改

## How To Reproduce
npm start

## Context

- **Umi Version**:
2.9.0
- **Node Version**:
v12.5.0
- **Platform**:
chrome版本 76.0.3809.132（正式版本） （64 位）
![image](https://user-images.githubusercontent.com/26357577/64147742-efa9c980-ce53-11e9-8339-6531ddba0a4f.png)

**Comment by sorrycc** [comment]
没有遇到过，也没有收到过类似反馈。

**Comment by hevily** [comment]
试试 cnpm create umi

**Comment by sunhaixin06** [comment]
● Webpack █████████████████████████ compiling (0%)  
 
Starting the development server...

是不是这个情况 ？

**Comment by sunhaixin06** [comment]
试试 yarn start启动项目看看

**Comment by leftstick** [comment]
same issue, 偶现，目前的确不知道为什么。反正我都是ctrl + c杀了进程，再来一发就好了

**Comment by Jeepeng** [comment]
+1，几乎每次都卡住，要`ctrl + c`,`npm run start`几次才成功
* umi@2.9.3
* macOS 10.14.6
* nodejs 12.10.0

**Comment by iceDays** [comment]
我也经常出现这种情况. `ctrl + c` 后很大几率下次 start 卡住, 有时候必须重启电脑才好. yarn 与 npm 一样.

**Comment by smithyj** [comment]
是的要 ctrl +c 好几次才可以

**Comment by jianglin-wu** [comment]
同样，遇到过几次，可能是构建任务子进程没杀掉

**Comment by Rickiiii** [comment]
。。每次拖动一下 改变一下窗口大小就会继续跑了。。。

**Comment by LinYouYuan** [comment]
经常遇到，和macos版本有关系吗？

**Comment by sorrycc** [comment]
我本地复现不了，有遇到的修改 `packages/umi/src/scripts/dev.js` 调调看，然后给个 PR。

**Comment by xuanxuan321** [comment]
我出现的概率很高，现在摸索出的方法是，在卡住的时候改变一下终端的窗口大小就可以了，很神奇

**Comment by xuanxuan321** [comment]
2.10版本的umi目前还没卡住过，有问题的朋友可以升级umi试试，这个issue我就先关掉了

**Comment by shx996** [comment]
> 2.10版本的umi目前还没卡住过，有问题的朋友可以升级umi试试，这个issue我就先关掉了

最新的脚手架的yarn create umi装了之后还是2.9.3版本的
