### ISSUE TITLE
如何在其他model 里面访问另一个model数据 , 如何我想在所有model 都能访问全局model数据 , 我该怎么做?

### ISSUE THREAD

**Issue by ouweiya** [umijs/umi#3152]
如何在其他model 里面访问另一个model , 如何我想在所有model 都能访问全局model数据 , 我该怎么做?

**Comment by sorrycc** [comment]
全局 model 就是可以被所有 model 访问到的，你的问题是啥？

**Comment by ouweiya** [comment]
就是如何访问全局model 的数据不？

**Comment by Fuphoenixes** [comment]
这不是umi的内容，建议去看dva和react-saga相关文档。
访问其他model的数据可以使用 select。
eg:
```
 yield select(state=>state.global.xxx);
```

**Comment by ouweiya** [comment]
> 这不是umi的内容，建议去看dva和react-saga相关文档。
> 访问其他model的数据可以使用 select。
> eg:
> 
> ```
>  yield select(state=>state.global.xxx);
> ```

你要是早上8点之前, 给出这个答案, 我肯定给个赞,  但是现在不行.
