### ISSUE TITLE
UMI UI 重装项目依赖，控制台报错

### ISSUE THREAD

**Issue by leijingdao** [umijs/umi#3153]
## What happens?
用UMI UI 创建一个项目，在任务->重装依赖 ，确认后控制台报错
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

![ezgif-5-2b4f50fea582](https://user-images.githubusercontent.com/12496382/64181400-f870be80-ce98-11e9-985b-4966d0c29754.gif)
![image](https://user-images.githubusercontent.com/12496382/64181536-35d54c00-ce99-11e9-9d07-d1d7fa6eb71b.png)

## Context

- **Umi Version**: v2.9.2
- **Node Version**: v10.16.0
- **Platform**: mac v10.14.6

**Comment by ikobe** [comment]
这是个 bug

执行任务管理中的重装依赖，使用的是项目目录下的 node_modules，而这个时候项目目录下的 node_modules 正在清空

这儿应该需要使用全局的 node_modules 执行，今天 fix 一下

**Comment by xiaohuoni** [comment]
使用全局的node_modules执行的话，是不是意味着 `umi ui` 也是使用全局
那当使用项目中的 `"start" : "umi dev --ui"` 或者 `"start" : "umi ui"` 都不行了吧？

**Comment by sorrycc** [comment]
@xiaohuoni 

* umi ui 得执行全局的，如果执行本地的 umi ui，就不应该提供删除 node_modules 的操作了
* umi dev 启动的 ui 不会出现任务管理的 Panel

**Comment by ycjcl868** [comment]
Duplicate #3156

**Comment by sorrycc** [comment]
@ycjcl868 不是一个问题？

**Comment by leijingdao** [comment]
已经升级 2.9.3，问题并没有解决

**Comment by leijingdao** [comment]
umi/packages/umi-ui-tasks/src/server/core/Tasks/Base.ts中的iconv-lite，在清除node_modules后找不到
