### ISSUE TITLE
ios微信打开空白

### ISSUE THREAD

**Issue by wowoshidaqiangge** [umijs/umi#3155]
用umi写的H5 在安卓微信和浏览器都可以打开    在safari浏览器也可以打开 但是在ios微信打开只显示title不显示内容  https://testmini.napin.com/joinInGetJoin

**Comment by xiaohuoni** [comment]
确实不能访问。我们也有微信的项目，但是我们的设置默认是
```
targets: {
    ie: 9,
 },
```
你要不试试？

**Comment by wowoshidaqiangge** [comment]
试了一下也不行  不知道是不是别的什么影响了

**Comment by HaishengLiang** [comment]
componentDidMount() {
    alert('join pages ...');
    console.log("join pages ...");
    debugger; // const {dispatch} = this.props // 这一行 debugger 错误卡住了 
    // dispatch({type: 'getJoin/getJoinIn'})
  }

**Comment by wowoshidaqiangge** [comment]
> componentDidMount（）{ 
> alert（'join pages ...'）; 
> console.log（“join pages ...”）; 
> 调试器; // const {dispatch} = this.props //这一行调试器错误卡住了
> // dispatch（{type：'getJoin / getJoinIn'}）
> }
这个之前就是因为不出来  我才打上的debugger  删除了也不显示
