### ISSUE TITLE
umi-ui 创建项目时遇到问题

### ISSUE THREAD

**Issue by longfeixueyi** [umijs/umi#3156]
umi-ui创建项目时遇到此问题然后构建失败
command failed: npm update --registry=https://registry.npm.taobao.org -d

自己开的控制台执行这段命令没有问题

## 相关环境信息

- **Umi 版本**：2.9.2
- **Node 版本**：10.15.3
- **操作系统**：mac

**Comment by sorrycc** [comment]
遇到啥问题？截图看下。

**Comment by longfeixueyi** [comment]
> 遇到啥问题？截图看下。
创建项目失败，原因：
![image](https://user-images.githubusercontent.com/12692542/64221871-e0cd2080-cf00-11e9-9fad-592a303473b5.png)
自己命令行执行没问题：
![image](https://user-images.githubusercontent.com/12692542/64221905-065a2a00-cf01-11e9-99df-da4a2d1489b9.png)

**Comment by sorrycc** [comment]
有日志吗？

**Comment by sorrycc** [comment]
在 `~/.umi/creator/create-umi` 执行那段命令试试会不会报错。

**Comment by longfeixueyi** [comment]
> 在 `~/.umi/creator/create-umi` 执行那段命令试试会不会报错。

![image](https://user-images.githubusercontent.com/12692542/64223450-ab2b3600-cf06-11e9-810d-0f5ae1a44f4e.png)
看情况是权限问题，如何解决？

**Comment by sorrycc** [comment]
权限问题比较麻烦，Umi UI 层会改进下给出提示，你试试手动删除 `~/.umi/creator/create-umi` 再试试。

不要用 sudo 解决权限问题，试着换成 nvm 之类的 node 管理工具管理 node 和安装依赖。

**Comment by longfeixueyi** [comment]
> 权限问题比较麻烦，Umi UI 层会改进下给出提示，你试试手动删除 `~/.umi/creator/create-umi` 再试试。
> 
> 不要用 sudo 解决权限问题，试着换成 nvm 之类的 node 管理工具管理 node 和安装依赖。
晚点试试

**Comment by afc163** [comment]
https://github.com/vuejs/vue-cli/blob/3173d20b5097a185cc7c5db6c56839d2cd5e2abe/docs/guide/troubleshooting.md#running-installation-with-sudo-or-as-root
