### ISSUE TITLE
[umi-build-dev] umi block list时，不支持公司网络代理

### ISSUE THREAD

**Issue by woniu1983** [umijs/umi#3160]
## What happens?
 使用umi block list命令时，出现time out.
 自行调试了下，发现问题是没有过公司的网络代理。

### 1
 文件：  \umi-build-dev\lib\plugins\commands\block\util.js
 方法： function _getDefaultBlockList(){}
 调用处：  有两处使用got库
       const _ref4 = yield got(`https://api.github.com/repos/${owner}/${name}/git/trees/master`, ),
       const _ref5 = yield got(`http://blocks.umijs.org/api/blocks`),
   这两处没有可选的代理参数（agent），所以公司网络就过不了。

### 2
 文件：  \getnpmregistry\index.js
 调用处： const fetch = require("node-fetch");
                 const text = await fetch("http://myip.ipip.net")
                 await fetch(registryMap[key])
   上面使用fetch的地方也没有使用到网络代理参数
   
## 相关环境信息
- 公司网络访问外网时需要通过一个本地HTTP代理
- **Umi 版本**：
     "name": "umi",   "version": "2.8.20",
- **Node 版本**：
    10.15.0
- **操作系统**：
    Windows 10  Pro x64.

## 复现步骤，错误日志以及相关配置
 umi block list

**Comment by aixfox** [comment]
试一下 proxychains ？

**Comment by woniu1983** [comment]
> 试一下 proxychains ？
能详细讲讲么？  我的是Windows 10 系统

**Comment by aixfox** [comment]
> 
> 
> > 试一下 proxychains ？
> > 能详细讲讲么？  我的是Windows 10 系统

Windows 的话找系统级的代理工具，给 node.exe 配置规则，比如 Proxifier。

要使用 proxychains 的话，得用 WSL 或者虚拟机。

使用方式自己搜索一下。

**Comment by woniu1983** [comment]
> Proxifier

谢谢。 好奇下， 金服这边开发的机器都是直连外网无公司代理的？

**Comment by SteiensGate** [comment]
同样的问题
