### ISSUE TITLE
关于 umijs 中使用 umi-plugin-react插件 links 配置 css 引用问题

### ISSUE THREAD

**Issue by chenkan456** [umijs/umi#3166]
```
你好，在  umi-plugin-react中 使用links 配置css 文件的时候，生成出来的顺序永远是在，umi.css之前，这样会导致我的文件永远都是被umi.css覆盖，
有没有办法改变这个引用的顺序呢，谢谢！

```
.umirc.js 配置如下：
export default {
  treeShaking: true,
  plugins: [
    // ref: https://umijs.org/plugin/umi-plugin-react.html
    ['umi-plugin-react', {
      antd: true,
      dva: {immer: true},
      dynamicImport: true,
      title: 'create',
     scripts: [
        { src: 'iconfont/iconfont.js' },
        { src: 'https://cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js' }
       /* { content: `window.less = {
          async: false,
          env: 'production'
        };` }, */
      ],
      links: [
        { rel: 'stylesheet', href: 'iconfont/iconfont.css' },
        { rel: 'stylesheet/less', href: '/color.less' } 
      ]
      
  
    }],
  ]

}

生成后，查看生成html，如下
<html class=" ">
<head>

<link rel="stylesheet" href="iconfont/iconfont.css">
<link rel="stylesheet/less" href="/color.less">
<style type="text/css" id="less:color">
<style type="stylesheet"  href="/umi.css">
........
发现 ，umi.css 引用始终是之后引用，我想吧<link rel="stylesheet/less" href="/color.less">放置在<style type="stylesheet"  href="/umi.css"> 之后，怎么处理呢？

**Comment by sorrycc** [comment]
给可复现仓库，issue 格式调整下。

**Comment by chenkan456** [comment]
不好意思我不清楚如何提交仓库，我再描述下：
![image](https://user-images.githubusercontent.com/17775768/64401750-e499a800-d0a4-11e9-9b75-1c7c8dc87992.png)
图中是我通过links 来配置生成时候引用的css文件，但是发现生成出来后，永远都是在umi.css
之前，如下：
![image](https://user-images.githubusercontent.com/17775768/64401789-114dbf80-d0a5-11e9-8fb1-886b76e31ffa.png)

我就是想问有没有办法设置后，实现效果如下：

**Comment by chenkan456** [comment]
不好意思 ，接上条

**Comment by chenkan456** [comment]
主要这也不属于bug，主要是我项目引用顺序，需要这么处理，我不想在layout/index 里面的Helmet 设置，感觉刷新的时候用户感受不好！既然umi-plugin-react 有封装这个功能，就想有没有办法实现！

**Comment by sorrycc** [comment]
links 生成的是在上面的，要放下面可以配 html 模板，参考 https://umijs.org/zh/guide/html-template.html

**Comment by chenkan456** [comment]
> links 生成的是在上面的，要放下面可以配 html 模板，参考 https://umijs.org/zh/guide/html-template.html

谢谢 正在尝试用ejs 来处理
