### ISSUE TITLE
在仿真IE9 IE10运行antd项目报 无法获取未定义或 null 引用的属性“split” 

### ISSUE THREAD

**Issue by x1nGoo** [umijs/umi#3174]
## What happens?
无法获取未定义或 null 引用的属性“split”
umi.js (78620,3)
该行对应内容
 var browserLang = typeof navigator !== 'undefined' ? navigator.language.split('-').join(g_langSeparator) : '';

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Umi Version**:
2.8.16
- **Node Version**:
10.16.1
- **Platform**:
win10

**Comment by xiaohuoni** [comment]
开发环境没有打补丁，要build之后才能在ie上查看，你可以看看是不是这个原因。如果不是的话，可以参照[ie报错和压缩问题解决思路](https://github.com/umijs/umi/issues/1421#issuecomment-516762499)处理。基本上都是这些问题。

**Comment by x1nGoo** [comment]
build 后在测试环境运行也还是报这个错误.

**Comment by x1nGoo** [comment]
build 后在测试地址打开页面也还是报这个错误.

**Comment by x1nGoo** [comment]
使用 COMPRESS=none umi build  build后放在测试服务器运行 打开页面还是 同样的错
![image](https://user-images.githubusercontent.com/20261541/64514394-1e74e380-d31d-11e9-9adc-f660c74e38c9.png)
![image](https://user-images.githubusercontent.com/20261541/64514420-27fe4b80-d31d-11e9-9e3d-784aef43af38.png)

**Comment by xiaohuoni** [comment]
参照[ie报错和压缩问题解决思路](https://github.com/umijs/umi/issues/1421#issuecomment-516762499)看看

**Comment by x1nGoo** [comment]
看了,  第四步、不压缩构建，查找出错源, 
弄完第4步后, 就是上面的错, 不知道该修改本地node_modules哪个包

**Comment by xiaohuoni** [comment]
看一下是哪个包，一般往上或往下会有注释

**Comment by x1nGoo** [comment]
![image](https://user-images.githubusercontent.com/20261541/64520827-7d405a00-d329-11e9-928a-436fa3824388.png)

然后在json里我是这样写吗?
      "locale": {
        "^2.9.13": {
          "version": "^2.9.13",
          "reason": ""
        }
      }

**Comment by xiaohuoni** [comment]
这个包应该不会出错吧，给一个重现demo！

**Comment by x1nGoo** [comment]
https://github.com/x1nGoo/myDemo @xiaohuoni ,麻烦了.

**Comment by xiaohuoni** [comment]
是bug，不过已经修复了，你升级一下umi-plugin-locale@2.10.0-beta.2 就好了

**Comment by x1nGoo** [comment]
package.json 里没 umi-plugin-locale,  是升级 "umi-plugin-react" 的版本吗?

**Comment by xiaohuoni** [comment]
都可以的，直接升级umi-plugin-react本地覆盖了也可以，但还是建议直接升级umi吧，这样同步给别人的时候，也不会出错。

**Comment by x1nGoo** [comment]
"umi": "^2.9.3",
    "umi-plugin-react": "^1.9.19"
这是我升级后的版本, 删除所有npm依赖重新安装后还是一样报错

**Comment by xiaohuoni** [comment]
确实，先手动升级吧,等umi更新

**Comment by x1nGoo** [comment]
好的, 请问怎么手动升级

**Comment by xiaohuoni** [comment]
yarn add umi-plugin-locale@2.10.0-beta.2

**Comment by Asence** [comment]
InvalidTokenError: Invalid token specified: 无法获取未定义或 null 引用的属性“replace” 

我报这个怎么办
