### ISSUE TITLE
umi-qiankun与umi-ui兼容问题

### ISSUE THREAD

**Issue by cookHu** [umijs/umi#3180]
## 相关环境信息

- **Umi 版本**：2.9.3
- **Node 版本**：10.16.3
- **操作系统**：macos Mojave 10.14.1

## 业务场景
**数据中台项目 含有非常多的系统子应用 系统的日益增长导致管理不同的应用很繁琐，考虑将项目转换为微前端**
目前调研umi-qiankun作为微前端的主框架，结合umi-ui进行管理父子系统，降低管理成本，提升效率，但目前遇见的几个问题，反馈一下，希望在后续迭代中考虑进去

## 问题
**umi-ui**
- 无法识别微前端的子系统结构 

## 新增功能建议
**umi-ui**
- 【加入】系统路由结构可视化功能
- 【加入】公共组件/路由预览功能
- 【加入】GUI界面组装功能

**Comment by kuitos** [comment]
子系统一般都是独立的仓库，需要在主应用中通过 umi ui 识别到结构？ @ycjcl868 @cookHu

**Comment by cookHu** [comment]
微前端很多开发情况是 其中一个或多个子系统 是交由一个团队成员负责 还是需要可以查看到多个子系统的结构 并且无法识别子系统的话 似乎无法在umi-ui启动单个子系统服务来开发啦 需要将主应用全部启动 @kuitos
