### ISSUE TITLE
umi block do not support private gitlab repo domain url

### ISSUE THREAD

**Issue by lidianhao123** [umijs/umi#3184]
## What happens?
umi block add cli do not support private gitlab repo domain

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1. umi block add https://code.xxx.com/laboratory/umi-blocks/tree/feature-init/SearchList --path=TradeCenter/TradeManagement/TradeOrder --page 
2. ⠹ 😁  Parse url and args✖  error     Error: https://code.xxx.com/laboratory/umi-blocks/tree/feature-init/SearchList can't match any pattern

**Expected behavior**
1. umi block add cli Support private gitlab domain
2. success add block

## Context

- **Umi Version**: 2.9.3
- **Node Version**: v10.16.3
- **Platform**: osx

## Remark
umi source code

[download.js](https://github.com/umijs/umi/blob/master/packages/umi-build-dev/src/plugins/commands/block/download.js#L67)
```js
const gitSiteParser = /^(https\:\/\/|http\:\/\/|git\@)((github|gitlab)[\.\w\-]+|(?:(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))(\/|\:)([\w\-]+)\/([\w\-]+)(\/tree\/([\w\.\-]+)([\w\-\/]+))?(.git)?$/;
export function isGitUrl(url) {
  return gitSiteParser.test(url);
}
```

**Comment by fodurrr** [comment]
Same problem here. My git repo name contained a dot therefore download.js couldn't parse it. I changed my gitrepo name but I am still not able to get my block from my private gitrepo. It works however if I use `umi block add` with relative local path. Any comment or solution for this?

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/2191
