### ISSUE TITLE
[Feature Request] indexPath的支持 

### ISSUE THREAD

**Issue by KaierChou** [umijs/umi#3186]
## Background
项目目录 是同后端文件放在一起的.
由于后端框架的要求. 打包输出的 index.html和 js,css等要放在不同的目录下. 
比如 index.html要放在 ./a/index.html
其他文件则要放在 ./b/dist/other.js

现在每次都得手动把index.html 改成 index.php后, 再拖到对应的目录中~~

## Proposal

希望能支持输出index.html到指定目录下.

thanks~

**Comment by ycjcl868** [comment]
这个和 `indexPath` 关系不大，构建完后用 [copy](https://umijs.org/zh/config/#copy) 处理下文件移动。
