### ISSUE TITLE
Loading chunk {n} failed

### ISSUE THREAD

**Issue by zhilianbi520** [umijs/umi#3190]
## What happens?
偶发性问题，加载分割资源报错，报资源内容解析失败的错误

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

1. 点击路由菜单，跳转至相应页面
![11_39_41__09_11_2019](https://user-images.githubusercontent.com/16549630/64666438-e7234580-d488-11e9-9a5b-c8f050a2623b.jpg)

## 相关环境信息

- **Umi 版本**：
2.3.2

- **Node 版本**：
10.15.3

- **操作系统**：
windows10

**Comment by zhilianbi520** [comment]
是否可以通过捕获异常，重新加载资源解决？

**Comment by zhilianbi520** [comment]
ctrl+f5刷新就好了。。。如何处理这种问题呢？？？

**Comment by ycjcl868** [comment]
能稳定复现吗？

**Comment by feibi** [comment]
大多是缓存导致的吧。

**Comment by HSdiana** [comment]
请问你这个后来怎么修复的呢？
