### ISSUE TITLE
添加autoprefixer之后，我竟然看不到后缀，原因究竟是...

### ISSUE THREAD

**Issue by johanazhu** [umijs/umi#3195]
## What happens?

我在.umirc.js中配置了autoprefixer: { flex: true }（配置 flex："no-2019"也一样，但是我想是不是文档写错了，应该是“no-2009”，但是“no-2009”也不行），但是浏览器上没有加前缀，浏览器用的是chrome和火狐，都没有前缀

## 最小可复现仓库

`export default {
  autoprefixer: { flexbox: true },
}`

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：^2.7.7
- **Node 版本**：v10.15.3
- **操作系统**：window

**Comment by wangxingkang** [comment]
文档写错了  是 no-2009

**Comment by johanazhu** [comment]
在targets中加{chrome：40}，就有前缀了，问题解决了
