### ISSUE TITLE
The framework can't suppport some installations like 'qiniu' ?

### ISSUE THREAD

**Issue by fireairforce** [umijs/umi#3211]
In my project,I just write some codes in the `pages/index.js` as follows:
```js
import React from 'react';
import qiniu from 'qiniu';

function Main(){
  return(
    <div>
      test pages
    </div>
  )
}


export default Main;
```
But When I start the project,i found the pages as follows:
![TIM图片20190916151907](https://user-images.githubusercontent.com/32598811/64939987-5b008c00-d895-11e9-9c0c-457e92c1ed30.png)

but when i delete the code `import qiniu from 'qiniu'`,the pages will get normal,but in my project i need this installation to support some functions.

![TIM图片20190916152109](https://user-images.githubusercontent.com/32598811/64940081-a450db80-d895-11e9-8bfe-8e694e40a46e.png)

my installation version as follows:
```json
"dependencies": {
    "antd": "^3.19.5",
    "dva": "^2.6.0-beta.6",
    "qiniu": "^7.2.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  }
```

**Comment by aixfox** [comment]
qiniu is a package for node.js environment.
![图片](https://user-images.githubusercontent.com/28643426/64941651-d2d0b580-d899-11e9-9ff6-fa3141123517.png)

**Comment by fireairforce** [comment]
but i can use this in `create-react-app`....

> qiniu is a package for node.js environment.
> ![图片](https://user-images.githubusercontent.com/28643426/64941651-d2d0b580-d899-11e9-9ff6-fa3141123517.png)

**Comment by aixfox** [comment]
> 
> 
> but i can use this in `create-react-app`....
> 
> > qiniu is a package for node.js environment.
> > ![图片](https://user-images.githubusercontent.com/28643426/64941651-d2d0b580-d899-11e9-9ff6-fa3141123517.png)

Is this package https://github.com/qiniu/js-sdk you are looking for?
Some objects of node.js are not exist in browser.
Something should be wrong in your project created by create-react-app. Maybe create-react-app mock these objects for isomorphism, you can get the answer by yourself.

**Comment by fireairforce** [comment]
thx,i will try.
