### ISSUE TITLE
切换路由后，点击后退按钮，路由无限循环

### ISSUE THREAD

**Issue by Hewaller** [umijs/umi#3213]
## What happens?

使用 `Browser History` 和配置式路由 ，进入页面切换路由后，点击浏览器的后退按钮，会在最初进入的两个路由之间来回循环切换。
在返回首页时偶尔前进按钮也会失效。
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库
> https://github.com/Hewaller/umiDemo.git

## 复现步骤，错误日志以及相关配置
> 路由切换顺序： /  =>  nodes 
> 点击后退，返回顺序： nodes => / => nodes => /   ... 无限循环
```js
//  后退时history参数中key也会一直变化
History {
  length: 2
  scrollRestoration: "auto"
  state:
  key: "lkj2qf"  // 返回上一级key也是会改变
  state: undefined
}
```

## 相关环境信息

- **Umi 版本**：2.7.7
- **Node 版本**：10.16.0
- **操作系统**：macOS 10.14.6

**Comment by Hewaller** [comment]
@sorrycc 麻烦请看下，是什么原因导致的

**Comment by aixfox** [comment]
你要把你的lock文件上传。
我这边试了一下并没有问题。

依赖版本是这些：
antd@3.23.4
react@16.9.0
react-dom@16.9.0
umi@2.9.6
umi-plugin-react@1.10.1

**Comment by Hewaller** [comment]
@aixfox 已经解决了，不使用全局的dva处理数据就可以了
