### ISSUE TITLE
纯属吐槽一下，umi-request，这是个太难用。

### ISSUE THREAD

**Issue by dmwin72015** [umijs/umi#3215]
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

吐槽一下，umi-request， 太难用，还是as好用一点

**Comment by sorrycc** [comment]
具体点，难用的点是啥？

**Comment by chenjsh36** [comment]
可以的话请详细说下是哪里难用了，以帮助我们去改进，例如是文档不完善、使用不友好、功能缺失等等，也欢迎提 PR 参与到共建里来。

**Comment by zjxpcyc** [comment]
> 具体点，难用的点是啥？

他说了是  Axios 好用。估计是不太熟悉，入参的风格
