### ISSUE TITLE
RouterTypes类型定义有缺陷

### ISSUE THREAD

**Issue by Sayid1** [umijs/umi#3218]
为什么不在继承BasicRouteProps的时候声明泛型类型？
现在我想使用match.params里面的属性的时候总是提示我找不到
使用computedMatch总是要先判断不为空才能使用
```javascript
interface RouterTypes<T extends Object = {}, P = {}> extends BasicRouteProps<P>
```
这样不是更好吗？

![image](https://user-images.githubusercontent.com/29008437/65021315-69b47500-d961-11e9-9180-939310a877a0.png)

![image](https://user-images.githubusercontent.com/29008437/65021072-00346680-d961-11e9-8b0d-8291054b06f7.png)

## 相关环境信息
- **Umi 版本**：2.8.7
- **Node 版本**：
- **操作系统**：

**Comment by Sayid1** [comment]
![image](https://user-images.githubusercontent.com/29008437/65021658-23abe100-d962-11e9-9c2a-0008a097b911.png)

**Comment by ycjcl868** [comment]
用 `umi-types`

**Comment by Sayid1** [comment]
@ycjcl868 大兄弟 这个里面没有router相关的啊

**Comment by ycjcl868** [comment]
看了下，可以使用 `RouterTypes`

```js
import { RouterTypes } from 'umi';

type IRoute = RouterTypes<{}, { code: string }>;

this.props.computedMatch.params.code
```

![image](https://user-images.githubusercontent.com/13595509/65135953-642a5e00-da39-11e9-93b3-5bd5855757a9.png)

**Comment by Sayid1** [comment]
![image](https://user-images.githubusercontent.com/29008437/65396650-069c6580-dddb-11e9-9f10-e8b715596a01.png)
大哥你在忽悠我
@ycjcl868

**Comment by handycode** [comment]
![屏幕快照 2019-10-11 10 05 24](https://user-images.githubusercontent.com/5368890/66620134-ff19f080-ec11-11e9-87d8-590777ee3738.png)
我现在是加 ! 号解决。。。
@Sayid1

**Comment by Sayid1** [comment]
我直接用react-router-dom的类型了


来自阿里邮箱 iPhone版
 ------------------原始邮件 ------------------
发件人：handy <notifications@github.com>
日期：2019-10-11 10:30:05
收件人：umijs/umi <umi@noreply.github.com>
抄送：m <sayid.zheng@aliyun.com>, Mention <mention@noreply.github.com>
主题：Re: [umijs/umi] RouterTypes类型定义有缺陷 (#3218)

 我现在是加 ! 号解决。。。
@Sayid1

**Comment by hhking** [comment]
目前的想到的一个解决方法是类似这样
```ts
interface IRoute extends RouterTypes {
    match: RouterTypes['match'] & { params: ParamsType };
}
```

**Comment by dickeylth** [comment]
> 目前的想到的一个解决方法是类似这样
> 
> ```ts
> interface IRoute extends RouterTypes {
>     match: RouterTypes['match'] & { params: ParamsType };
> }
> ```

建议把这个加到 umi 文档里，挺常见的一个需求。
