### ISSUE TITLE
Error: Cannot find module '@tmp/history'

### ISSUE THREAD

**Issue by karlgit** [umijs/umi#3221]
Error: Cannot find module '@tmp/history'

https://github.com/karlgit/wit-office-web.git

## Context
- **Umi Version**:2.8.7
- **Node Version**: v12.9.1
- **Platform**: macos

**Comment by sorrycc** [comment]
https://github.com/karlgit/wit-office-web/blob/9efe2cc/config/config.js#L5
这行删了。
