### ISSUE TITLE
[Feature Request] 路由跳转优化

### ISSUE THREAD

**Issue by zjxpcyc** [umijs/umi#3224]
## Background

现在跳转是这样的 

```js
import router from 'umi/router';

router.push('/list');
```

## Proposal

能不能把 router 内置到 props 里面.  我不用每次都 import

## Additional context

还有一个感觉不太对劲的
```jsx
router.push({
  pathname: '/list',
  query: {
    a: 'b',
  },
});
```

这种跳转方式 `pathname` 哪里来的 ？ 是 `route` 里面的 `path` 吗?  为啥不是 `route.id` 或者 `route.pathname` ?  虽然我知道 `route` 里面没有这两个属性。给人的感觉 `pathname` 就应该是一个 name 或者 id 之类的东西。  这个不知道符不符合大家的思维。

我觉得用 `router.push('/list')` 不如用 `router.push({  pathname: '/list' })` . 因为后者语义更强一点。但是我更倾向这种 `router.push({  pathname: 'post.list' })`. 吐槽一下

**Comment by sorrycc** [comment]
感谢建议。

* `router` 不应该放 props 里，为了遍历放 props 里的话，可以放的东西就太多了，而且不仅是组件里需要做路由操作，组件外也需要
* API 是透传 [history](https://github.com/ReactTraining/history) 的接口

另外，`router` 推荐是从 `umi` 中 import。

```js
import { router } from 'umi';
```
