### ISSUE TITLE
如何保证多页应用中，顶级的变量g_app不会冲突的问题？ 

### ISSUE THREAD

**Issue by huyansheng3** [umijs/umi#3225]
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by sorrycc** [comment]
配 `disableGlobalVariables: true` 不会生成全局变量。
