### ISSUE TITLE
help me borthers

### ISSUE THREAD

**Issue by kunzi588** [umijs/umi#3233]
如何在上线的时候清除所有的console.log()呢？是不是咋哪一个配置文件里面定义，急！！！！！！！！！！！！！！！！

**Comment by xiaohuoni** [comment]
https://umijs.org/config/#uglifyjsoptions
```js
uglifyjsoptions: {
      uglifyOptions: {
        // remove console.* except console.error
        compress: {
          drop_console: true,
          pure_funcs: ['console.error'],
        },
      },
    }
```

**Comment by kunzi588** [comment]
谢谢您的建议，但是这么写好像不行的

**Comment by xiaohuoni** [comment]
应该是可以的，我们项目中就是这么配置的。

**Comment by kunzi588** [comment]
请问你这个在什么地方写的，umi.js吗？

**Comment by xiaohuoni** [comment]
`umirc.js` 或者 `config.js` 都可以

**Comment by kunzi588** [comment]
那请问一下你这个在什么位置写的呢？plugins数组下吗

**Comment by kunzi588** [comment]
还是 直接在export defualt里面呢

**Comment by xiaohuoni** [comment]
外面和 `plugins` 同级

**Comment by kunzi588** [comment]
是够能加你下大哥你的微信呢

**Comment by kunzi588** [comment]
否

**Comment by kunzi588** [comment]
这个问题一直存在真想给你拍照看一下

**Comment by xiaohuoni** [comment]
我的微信yu_xiaohu，个人信息里面有的

**Comment by sunlanlisa** [comment]
> 我的微信yu_xiaohu，个人信息里面有的

我的还没解决，写在和plugins 同级的下面，但是打包出来，依旧还有console 
![image](https://user-images.githubusercontent.com/4921284/68642642-d0ad6f00-0549-11ea-8b89-4b1ad299aba9.png)

**Comment by sunlanlisa** [comment]
大神可以帮我看看吗

**Comment by sunlanlisa** [comment]
> 如何在上线的时候清除所有的console.log()呢？是不是咋哪一个配置文件里面定义，急！！！！！！！！！！！！！！！！

您解决了吗，是否可以帮我看看

**Comment by cornwang** [comment]
> > 如何在上线的时候清除所有的console.log()呢？是不是咋哪一个配置文件里面定义，急！！！！！！！！！！！！！！！！
> 
> 您解决了吗，是否可以帮我看看

您好 请问您解决了嘛
