### ISSUE TITLE
Use official cli command init project will occur error when install deps.

### ISSUE THREAD

**Issue by icarusysuper** [umijs/umi#3239]
## What happens?
Use official cli command init project will occur error when install deps.

## Mini Showcase Repository(REQUIRED)
See reproduce steps below.

## How To Reproduce
**Steps to reproduce the behavior:**
1. npm create umi
2. select app
3. enable ts
4. select all react features
5. npm i

Error will occur:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @typescript-eslint/parser@canary
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@umijs/fabric'
npm ERR! notarget
```

**Expected behavior**
install deps successfully

## Context

- **Umi Version**: latest
- **Node Version**: latset
- **Platform**: win10

**Comment by xiaohuoni** [comment]
I think it should be the network problem.

**Comment by icarusysuper** [comment]
Yeah, I hava try in another machine an it's OK. I should found this problem with my machine.
