### ISSUE TITLE
immer 是否可以按model部分开启？这样就慢慢迁移了。

### ISSUE THREAD

**Issue by elivoa** [umijs/umi#324]
项目太大，直接打开immer会导致很多model直接报错，全改代价太大了。是否可以按model自由选择是否开启immer？

**Comment by elivoa** [comment]
这个issue什么时候可以得到支持？

**Comment by sorrycc** [comment]
It's supported.

**Comment by elivoa** [comment]
How to use?

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva/pull/1729
参考这个，没有返回值时走 immer，内部已有项目这么用了。
