### ISSUE TITLE
tsconfig.json中的paths配置不生效

### ISSUE THREAD

**Issue by VeronicaF** [umijs/umi#3240]
## What happens?

想要使用tsconfig.json中的paths功能，尝试过将config.ts中的alias设置成与tsconfig.json中相同，
在chainWebpack中确实看到了alias，但编译还是报错

## 最小可复现仓库

官方的umi-examples/typescript即可复现

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by ouweiya** [comment]
为什么不生效?
