### ISSUE TITLE
使用ssr，动态路由页面查看源代码title标签没有改变  

### ISSUE THREAD

**Issue by hg542006810** [umijs/umi#3242]
网页title如下图：
![image](https://user-images.githubusercontent.com/16329156/65319877-3a0ca380-dbd3-11e9-837a-71feac562c63.png)
右键查看源代码如下：
![image](https://user-images.githubusercontent.com/16329156/65319962-6cb69c00-dbd3-11e9-8969-86466d251f00.png)
想要的效果是右键查看源代码跟网页title一致。
改变title插件是使用的DocumentTitle。
另外，如何配置不同路由meta标签的keywords和description值呢？因为每个页面的关键字都不一样。

**Comment by ycjcl868** [comment]
可参考这个例子 https://github.com/umijs/plugins/blob/master/packages/%40umijs/plugin-prerender/test/fixtures/react-document-title/.umirc.js#L17-L23，实现思路应该是一样的。

**Comment by ycjcl868** [comment]
@label-actions 我看了

**Comment by hg542006810** [comment]
@ycjcl868 好的，了解，请问一下打包之后，如何部署呢？目前直接放到nginx是未经处理的静态文件。有示例吗？

**Comment by hg542006810** [comment]
非常感谢！问题已解决。

**Comment by rfw** [comment]
@hg542006810   我也遇到这问题了，你是怎么解决的？下面配置无效

```
plugins: [
    // ref: https://umijs.org/plugin/umi-plugin-react.html
    
    ['@umijs/plugin-prerender', {
      postProcessHtml: ($, path) => {
        const helmet = Helmet.renderStatic();
        const title = helmet.title.toString();
        const meta = helmet.meta.toString();
        // const link = helmet.link.toString();
        console.log('---title', title)
        $('html head').prepend(title);
        $('html head').append(meta)
        // $('html head').append(link)
        return $;
      }
    }]
  ],
```

**Comment by JJH0901** [comment]
兄弟，这个问题最后怎么解决的，我也是postProcessHtml的配置无效

**Comment by c-cdn** [comment]
@JJH0901  3.0以后 官方有教程呀

**Comment by c-cdn** [comment]
@JJH0901  2.x 的 server.js 处理
