### ISSUE TITLE
ssr部署到服务器上之后，第一次加载会出现没有样式的页面

### ISSUE THREAD

**Issue by hg542006810** [umijs/umi#3244]
![image](https://user-images.githubusercontent.com/16329156/65382125-f6c84700-dd30-11e9-8926-2da8927acc31.png)
第一次加载是这样，过了几秒后第二次加载就是正常的页面了。如何才能在css和js都加载完成只有才显示页面？项目链接：http://106.12.7.125/   部署方式采用的是pm2 + nginx。另外，右键源代码g_initialData 会有一大堆数据，这个可以去掉吗？

**Comment by ycjcl868** [comment]
css 预加载，参考 [home.js#L44-L51](https://github.com/umijs/umi-example-ssr-with-egg/blob/55db11eb5397a6cece19983f4d2d98038419d572/app/controller/home.js#L44-L51)

**Comment by hg542006810** [comment]
我使用的是koa.js，现在已经把css和js获取出来了，如何实现预加载呢？koa官方文档没看懂
![image](https://user-images.githubusercontent.com/16329156/65390164-45a4c980-dd8f-11e9-9d35-917ea72dceef.png)

**Comment by hg542006810** [comment]
@ycjcl868 请问可以让js和css都加载完成之后，才显示页面吗？这样就不用做预加载了

**Comment by zhangyuang** [comment]
拿到js和css后把地址写到你的模版文件对应的插槽就行了，css放头部

**Comment by hg542006810** [comment]
非常感谢！问题已解决，加入了一个ejs模板，在其头部引用css就好了

**Comment by 569202812** [comment]
@hg542006810 可以联系你交流下你怎么ssr的吗

**Comment by LBC100** [comment]
> 非常感谢！问题已解决，加入了一个ejs模板，在其头部引用css就好了

同问. 怎么加的ejs模板? 加在哪呢?

**Comment by ycjcl868** [comment]
demo 已更新，使用最新的

**Comment by 569202812** [comment]
> demo已更新，使用最新的

demo ```start```命令可以 ```dev```命令报错
