### ISSUE TITLE
错误 throw ReactError(Error('Element type is invalid: expected a string (for built-in components)

### ISSUE THREAD

**Issue by JamosLi** [umijs/umi#3246]
## What happens?
此问题一直出现多次，解决方式实在玄学，也不知道哪里报错。

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by nuoer2048** [comment]
想知道这个问题解决没得？

**Comment by mansion-sun** [comment]
关闭mfsu就好了，而且只有个别页面有这个问题，我用到了hoc包裹的组件，组件层级比较深，正常构建没有问题，mfsu就一直报错，没法解决！
