### ISSUE TITLE
antd 和 antd-mobile 只处理业务代码，不处理 node_modules 下的

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#325]
## 问题

项目依赖 a，a 依赖了 antd-mobile@1，但是 umi 通过 alias 内置了 antd-mobile@2，会导致 a 里使用的 antd-mobile 也是 2 。

## 临时解决

项目里新增 antd-mobile@1 的依赖，umi 会优先使用项目中依赖的 antd-mobile 版本。

## 最优解

antd 和 antd-mobile 只处理业务代码，不处理 node_modules 下的，但由于 https://tinyletter.com/sorrycc/letters/babel 描述的问题，解决起来比较麻烦，需要调整 babel-plugin-import 的逻辑。

**Comment by superlbr** [comment]
明明用不到antd-mobile，依赖里还是默认装了。。。
