### ISSUE TITLE
Could not open xxxx in the editor.

### ISSUE THREAD

**Issue by afc163** [umijs/umi#3251]
<img width="333" alt="image" src="https://user-images.githubusercontent.com/507615/65411337-2c4b5e00-de1f-11e9-9e62-c2ff17233fca.png">

<img width="812" alt="image" src="https://user-images.githubusercontent.com/507615/65411310-1e95d880-de1f-11e9-8a4e-52499e4857fa.png">

- Atom 1.40.1

第一次打开成功后 cmd + q 关掉 Atom，再次点击无法打开，且 ui 界面没有报错信息。

**Comment by aixfox** [comment]
应该是这里报的：
https://github.com/yyx990803/launch-editor/blob/cf575715fd/packages/launch-editor/index.js#L82

**Comment by sorrycc** [comment]
@ycjcl868 新的打开方案在 v2 的分支里了吗？

**Comment by ycjcl868** [comment]
还没合，我加一下

**Comment by sorrycc** [comment]
已修复。

**Comment by ycjcl868** [comment]
未指定编辑器打开时，顺序还需要优化
