### ISSUE TITLE
How to mock websocket?（如何mock websocket?）

### ISSUE THREAD

**Issue by maosong** [umijs/umi#3255]
No method for "mock-websocket" was found in the umijs document.
The current idea is to start my own "websocket server" when "umi dev" starts.
May I ask if my thinking is correct and how to achieve it?

没有找到umijs文档中关于"mock-websocket"的方法。
目前的思路是"umi dev"启动时，同时启动我自己的"websocket server"。
请问我的思路是否正确，以及如何实现？

**Comment by maosong** [comment]
Because "proxy" of umijs can't use "ws", can UMI dev fork sub-process?

因为umijs的"proxy"无法使用"ws"，想出的折中方案，"umi dev"能否fork子进程？

**Comment by sorrycc** [comment]
umi 不支持 mock ws，你可以写个插件实现。

**Comment by maosong** [comment]
> umi 不支持 mock ws，你可以写个插件实现。没明白为啥要 fork 子进程，插件里可以做的，没有这类限制。

🙏
