### ISSUE TITLE
publicPath 不起作用

### ISSUE THREAD

**Issue by Jimyzzp** [umijs/umi#3264]
"umi": "^2.7.7"
在.umirc.js设置publicPath，构建后html的资源引用路径是publicPath，但是dist文件夹下面的资源文件并没有生成到publicPath对应的文件夹

**Comment by leftstick** [comment]
`publicPath`就是这个功能，没毛病。
如果你有其他诉求，例如：希望生成的资源在`dist`目录下也能有和`publicPath`对应的位置，那你得找其他插件，或者自己写脚本处理了

**Comment by wangxingkang** [comment]
二楼正解

**Comment by youngjuning** [comment]
好的吧
