### ISSUE TITLE
umi.js get browser language failed in IE 10 

### ISSUE THREAD

**Issue by firemoon2000** [umijs/umi#3266]
## What happens?

umi.js line 116915
in function getLocale()
  var browserLang = typeof navigator !== 'undefined' ? navigator.language.split('-').join(g_langSeparator) : '';

throw exception in IE10
there is no navigator.language
there is only navigator.browserLanguage = "zh-CN"
so  null.split('-') throw a exception.
then hole website is done, empty page,  nothing shown

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.set targets: { ie: 9 },
2.open ie10 view the website

**Expected behavior**
1. the website show success or show message not support.
2.

## Context

- **Umi Version**:  2.3.0
- **Node Version**: 6.4.1
- **Platform**: windows

if not support IE10 and lower
how can I show message. 
not throw exception and  show a blank website ?

**Comment by firemoon2000** [comment]
update to umi 2.9.6
also had this problem.

**Comment by firemoon2000** [comment]
We set baseNavigator: false in config.js ,  still can't avoid problem.
The whole website is down.

**Comment by sorrycc** [comment]
@chenshuai2144 看下。

**Comment by leftstick** [comment]
@firemoon2000 seems same issue as [3154](https://github.com/umijs/umi/pull/3154), it was fixed at `2.9.4`.

You should provide a reproducible repo if you still have this issue

**Comment by xiaohuoni** [comment]
@firemoon2000 有问题再reopen
