### ISSUE TITLE
[Feature Request] umi-request 好像不支持  onUploadProgress

### ISSUE THREAD

**Issue by zjxpcyc** [umijs/umi#3267]
## Background

不知道是 bug 还是 feature  。没有找到支持 onUploadProgress 事件的说明

**Comment by chenjsh36** [comment]
**onUploadProgress** 事件我理解因为是 [XMLHttpRequest.upload](https://developer.mozilla.org/zh-CN/docs/Web/API/XMLHttpRequest/upload) 里事件监听器中的 **onprogress** 事件。很遗憾，umi-request 是基于 fetch 而非 XMLHttpRequest 封装的请求库，本身并不支持 onUploadProgress、onDownloadProgress 这类原生能力。

为什么 umi-request 不选择 XMLHttpRequest ，具体的原因和讨论可以看[传统 Ajax 已死，Fetch 永生](https://github.com/camsong/blog/issues/2)，简单来说，相比设计粗糙、不关注分离、调用方式混乱的 XMLHttpRequest，我们选择了语法简洁、基于标准 Promise 实现的 Fetch ，在享用 fetch 带来的好处的同时，也接受了 fetch 带来的不足之处。

**Comment by zjxpcyc** [comment]
好像网上有 fetch 模拟 process 的实现  [https://jakearchibald.com/2016/streams-ftw/](https://jakearchibald.com/2016/streams-ftw/)

**Comment by Hitotsubashi** [comment]
早知道我就用回原生的axios，失望
