### ISSUE TITLE
约定式路由，pages下有个index目录，能不能url上不显示index，只显示index的上一级，但是内容是index目录下的

### ISSUE THREAD

**Issue by SilentFlute** [umijs/umi#3276]
首先感谢@sorrycc 大佬开发的那么好用的脚手架！！
最近在用umi开发项目，有这么一个需求：
约定式路由，有如下路径`/pages/a/a1/index.js`, 对应的url为`http://xxx/a/a1`这没毛病，但是如果有个目录是`/pages/b/index/index.js`，我希望此时的url是`http://xxx/b`，然后显示的是`/pages/b/index/index.js`的内容，就是没有上一级的这个`index`，而目录`/pages/b/b1/index.js`对应url则又是`http://xxx/b/b1`，不知道这样是否可行

**Comment by baxtergu** [comment]
试着在 /pages/b 目录下新建一个 index.js 对 /pages/b/index/index.js 做一下导入导出呢？

**Comment by sorrycc** [comment]
`/pages/b/index/index.js` -> `/pages/b/index`, `/pages/b/b1/index.js` -> `/pages/b/b1`，规则是这样的，只会去最后的 index.js 。

**Comment by SilentFlute** [comment]
能不能`/pages/b/index/index.js` -> `http://xxx/pages/b`，直接到最里面的index.js，然后url上没有index.js的上一级呢？
大佬求实现@sorrycc 🤣🤣

**Comment by sorrycc** [comment]
不能，这是定好的规则，有需要可以自己写插件实现。
