### ISSUE TITLE
页面内如何获取路由参数？

### ISSUE THREAD

**Issue by lusess123** [umijs/umi#328]
如题

**Comment by sorrycc** [comment]
用 [withRouter](https://umijs.org/docs/zh-Hans/api.html#umi-withrouter) 包一下，就能取到 props.location.query 了。

**Comment by lusess123** [comment]
另外相关的问题，多参数的路由应该怎么配置？

**Comment by xiaohuoni** [comment]
自己手动加上去的参数，使用location.query获取不到，比如aaa.com/?id=1这样子的。获取不到id。使用原生的方法在globe model里面获取。一次有一次空。不知道这个值不值得提交iss

**Comment by sophieChenyx** [comment]
我在index.js 下创建了 一个 $details$.jsrouter.push({
      pathname: 'index/details',
      query: {
        userId,
        room
      },
    });
跳转过去的子页面 this.props 根本就没有显示参数 
是我使用的有问题吗
umi 传url 上的参数有这么麻烦吗

**Comment by qishilong** [comment]
const localtion = useLocaltion();
// localtion
<img width="831" alt="image" src="https://github.com/umijs/umi/assets/105185710/8cc04238-2496-4eef-93cd-b54fc2d43035">

**Comment by qishilong** [comment]
umijs 官方文章链接：
https://umijs.org/docs/guides/routes#%E8%B7%AF%E7%94%B1%E7%BB%84%E4%BB%B6%E5%8F%82%E6%95%B0

**Comment by qishilong** [comment]
里面介绍的都很详细
