### ISSUE TITLE
umi build 之后如果将html和JS 分开在不同目录

### ISSUE THREAD

**Issue by yadongxie150** [umijs/umi#3286]
具体想要的效果如下
-build
  -index.html
  -static/umi.js
  -static/umi.css

**Comment by wangxingkang** [comment]
写插件吧

**Comment by tianleiyiji123** [comment]
config
    .output
    .path(resolveApp('build'))
    .filename('static/js/[name].[hash:8].js')
    .chunkFilename('static/js/[name].[chunkhash:8].chunk.js')
    config.plugin('mini-css-extract-plugin').use(MiniCssExtractPlugin, [{
      filename: 'static/css/[name].[hash:8].css',
      chunkFilename: 'static/css/[name].[chunkhash:8].chunk.css'
    }])
但是css还会打包出来，不知道如何禁掉

**Comment by sorrycc** [comment]
不支持这种方式，umi 内部实现和这个约定强绑的。
