### ISSUE TITLE
开启ssr后，每次访问数组中都会增加新的history.min.js

### ISSUE THREAD

**Issue by qzhongyou** [umijs/umi#3287]
![image](https://user-images.githubusercontent.com/7010519/65675530-e5f53980-e080-11e9-9206-e9f4a40bd57f.png)
开启ssr后，每次访问数组中都会增加新的history.min.js，导致数组越来越大。页面卡顿。具体原因暂未找到

**Comment by ycjcl868** [comment]
怎样可以复现下

**Comment by qzhongyou** [comment]
知道原因了， .umi/router.js 里面 每次请求都会 this.unListen = history.listen(routeChangeHandler);但是，  componentWillUnmount() { this.unListen(); }，并不会再服务端执行，所以并没有被释放。

**Comment by qzhongyou** [comment]
> 怎样可以复现下
知道原因了， .umi/router.js 里面 每次请求都会 this.unListen = history.listen(routeChangeHandler);但是， componentWillUnmount() { this.unListen(); }，并不会再服务端执行，所以并没有被释放。

**Comment by qzhongyou** [comment]
知道原因了， .umi/router.js 里面 每次请求都会 this.unListen = history.listen(routeChangeHandler);但是， componentWillUnmount() { this.unListen(); }，并不会再服务端执行，所以并没有被释放。

**Comment by ycjcl868** [comment]
@qzhongyou  debug 了下 `history.length` ，每次 ssr 时，数量都是重装 render 的。数组增加是指哪个数组？
