### ISSUE TITLE
umi build --watch 模式下，每次变更总会触发多次编译，甚至是首次启动时也如此

### ISSUE THREAD

**Issue by leftstick** [umijs/umi#3288]
## What happens?

执行`umi build --watch`时，每次代码变更总会触发多次编译，即便是首次启动时，也会编译多次

## 最小可复现仓库

https://github.com/leftstick/umi-issue

## 复现步骤，错误日志以及相关配置

```bash
yarn
yarn build
```

你会看到如下现象：

![watch](https://user-images.githubusercontent.com/1059956/65683865-f6adab80-e090-11e9-9545-8a3900344508.gif)

多次编译的代码其实是webpack[af-webpack-build.js](https://github.com/umijs/umi/blob/master/packages/af-webpack/src/build.js#L34)，所以这就难受了，涉及因素有点多

## 相关环境信息

- **Umi 版本**：2.9.6
- **Node 版本**：10.16.0
- **操作系统**：macOS 10.14.6

**Comment by sorrycc** [comment]
build 的 watch 模式现在支持的不好，还有不少细节没处理。

**Comment by james70s** [comment]
也遇到同样的问题
