### ISSUE TITLE
as it exceeds the max of 500KB

### ISSUE THREAD

**Issue by succulen-plants** [umijs/umi#3294]
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
The code generator has deoptimised the styling of /Users/data-vi-pro/src/**/TreeTadialData.js as it exceeds the max of 500KB.
引入了一个比较大的数据文件， 使用如下解决办法， 无效
.babelrc
{
  "compact": false
}

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by starsoul666** [comment]
引入这个插件以后需要增加配置吗？
