### ISSUE TITLE
[Feature Request] 增加区块组的概念，可以通过添加区块组的操作一次添加多个区块

### ISSUE THREAD

**Issue by ft20082** [umijs/umi#3295]
## Background

我们有很多功能都是重复开发，想通过微服务提供服务，一个微服务对应一组功能，如果按照规范，需要做到多个区块，既然已经支持了区块，增加对区块组的支持应该改动不大。

## Proposal

通过区块组快速操作多个区块，也可以管理一个区块组中的部分区块，包含添加、删除功能，这样可以更方便的做公司内部的共享，重复的前后端服务功能都不需要开发。

同时建议官方维护一个区块的市场，前端的功能和后端的功能最好绑定，后端服务以 docker 方式提交，这样方便大家共享代码

**Comment by sorrycc** [comment]
为啥关了？区块组设计之初是有的，实现的时候有些变样，目前正在梳理区块功能，之后会支持的。

**Comment by ft20082** [comment]
> 为啥关了？区块组设计之初是有的，实现的时候有些变样，目前正在梳理区块功能，之后会支持的。

我以为要在 https://github.com/ant-design/ant-design-pro/issues/5349 要在这个页面提，那我是在哪提呢？
还有，你是产品吗？想和你聊下 ant design 的设计问题，这能和谁沟通？
