### ISSUE TITLE
[Feature Request] Umi UI suggestions

### ISSUE THREAD

**Issue by afc163** [umijs/umi#3296]
- [x] `编辑器打开` 移到右上角。
- [ ] 关闭页面时进行提示，避免关了找不到。
   <img width="207" alt="image" src="https://user-images.githubusercontent.com/507615/66549726-83b73100-eb76-11e9-8fee-b46eaeac56f0.png">
- [ ] 导入项目时做一些校验，比如没有 package.json 肯定不合法。还有其他条件，判断是不是合法的 umi/bigfish 项目。
- [ ] 版本检查更新机制
  - [ ] 命令行内：https://ice.work/docs/iceworks/upgrade
  - [ ] UI 界面内
- [ ] 目录选择里要加个搜索框。https://github.com/umijs/umi/issues/3690#issuecomment-599397053
- [ ] 新增『命令行打开项目』，出现在所有『编辑器打开』的地方，如果能做成内嵌的命令行，这个可以不需要。类似：<img width="341" alt="image" src="https://user-images.githubusercontent.com/507615/66888155-083eff00-f010-11e9-9306-8e3280644c90.png">
- [ ] Git 分支切换和提交功能。

**Comment by afc163** [comment]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/507615/66888012-8cdd4d80-f00f-11e9-94a0-0faaf12c8fc9.png">

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/507615/66888031-a2eb0e00-f00f-11e9-9d0e-07646694dc1a.png">

**Comment by afc163** [comment]
- [ ] 新增『命令行打开项目』。类似：<img width="341" alt="image" src="https://user-images.githubusercontent.com/507615/66888155-083eff00-f010-11e9-9306-8e3280644c90.png">

**Comment by afc163** [comment]
>  编辑器打开 移到右上角。

最好在配置、任务的右上角都加一下，『命令行打开』类似。

**Comment by afc163** [comment]
- [ ] Git 分支切换和提交功能。

<img width="624" alt="image" src="https://user-images.githubusercontent.com/507615/66888634-f3636b00-f011-11e9-853e-0dcd1ab880ac.png">

<img width="412" alt="image" src="https://user-images.githubusercontent.com/507615/66888644-fe1e0000-f011-11e9-9f20-bd7ec76d1b74.png">

**Comment by afc163** [comment]
- [ ] 内嵌命令行。

**Comment by afc163** [comment]
- [ ] 全局 umi ui 的命令行提示可以加一下。

<img width="648" alt="image" src="https://user-images.githubusercontent.com/507615/67362696-28d20080-f59e-11e9-9ebe-c0775a5eed50.png">

**Comment by sorrycc** [comment]
@afc163 umi 不是最新的？这里加过的。

![image](https://user-images.githubusercontent.com/35128/67370726-c97bec80-f5ad-11e9-8064-a04320e4904a.png)

**Comment by afc163** [comment]
更新之后有了👍
