### ISSUE TITLE
umi如何进行react-css-module配置以及全局sass的配置

### ISSUE THREAD

**Issue by ywy94ywy** [umijs/umi#3307]
{
  test: /\.scss$/,
  use: [
    'style-loader',
    // 简洁方式
    // 'css-loader?modules&localIdentName=[local]-[hash:base64:10]',
    {
      loader: 'css-loader',
      options: {
        module: true,
        localIdentName: '[local]-[hash:base64:10]'
      }
    },
    'sass-loader',
    {
      loader: 'sass-resources-loader',
      options: {
        resources: path.resolve(__dirname, '../src/assets/styles-variable.scss')
      }
    }
  ]
},

plugins: [
  [
    'react-css-modules',
    {
      generateScopedName: '[local]-[hash:base64:10]',
      filetypes: {
        '.scss': {
          syntax: 'postcss-scss'
        }
      }
    }
  ]
]

umi中可以配置sass的变量吗，还有react-css-module的配置，用styleName='a' 代替className={style.a}

**Comment by sorrycc** [comment]
* sass 默认支持，通过配置项开启，配置项会透传给 sass-loader，sass 变量没理解是啥，这不是代码里面组织的吗？
* react-css-module 没记得有加过这个的支持

**Comment by ywy94ywy** [comment]
> * sass 默认支持，通过配置项开启，配置项会透传给 sass-loader，sass 变量没理解是啥，这不是代码里面组织的吗？
> * react-css-module 没记得有加过这个的支持

我没有表述清楚，我的意思是sass全局变量或者全局mixin要如何配置，在普通项目中是通过添加sass-resources-loader，在umi中不知应该如何手动修改sass-loader的配置。另外react-css--module可以省略一堆style.这样的写法，写起来更舒服一些。

**Comment by sorrycc** [comment]
在 sass-loader 的基础上额外加 sass-resources-loader? 如果是通用需求，可以提 PR 内置，如果不是，可以通过 chainWebpack 修改。

**Comment by sorrycc** [comment]
在 sass-loader 的基础上额外加 sass-resources-loader? 如果是通用需求，可以提 PR 内置，如果不是，可以通过 chainWebpack 修改。

**Comment by HazySoda** [comment]
```js
  chainWebpack: config => {
    const oneOfsMap = config.module.rule('sass').oneOfs.values();
    oneOfsMap.forEach(item => {
      item
        .use('sass-resources-loader')
        .loader('sass-resources-loader')
        .options({
          resources: './src/assets/scss/_var.scss',
        })
        .end();
    });
  },
```

@ywy94ywy 使用 chainWebpack 配置可以解决。

**Comment by baiguo818** [comment]
> ```js
>   chainWebpack: config => {
>     const oneOfsMap = config.module.rule('sass').oneOfs.values();
>     oneOfsMap.forEach(item => {
>       item
>         .use('sass-resources-loader')
>         .loader('sass-resources-loader')
>         .options({
>           resources: './src/assets/scss/_var.scss',
>         })
>         .end();
>     });
>   },
> ```
> 
> @ywy94ywy 使用 chainWebpack 配置可以解决。是在哪个文件里写的 chainWebpack 啊

**Comment by baiguo818** [comment]
> ```js
>   chainWebpack: config => {
>     const oneOfsMap = config.module.rule('sass').oneOfs.values();
>     oneOfsMap.forEach(item => {
>       item
>         .use('sass-resources-loader')
>         .loader('sass-resources-loader')
>         .options({
>           resources: './src/assets/scss/_var.scss',
>         })
>         .end();
>     });
>   },
> ```
> 
> @ywy94ywy 使用 chainWebpack 配置可以解决。

可以用来设置全局less吗，我改了下  没有生效
 chainWebpack: config => {
    console.log('config:',config)
    const oneOfsMap = config.module.rule('less').oneOfs.values();
    oneOfsMap.forEach(item => {
      item
        .use('sass-resources-loader')
        .loader('sass-resources-loader')
        .options({
          resources: './src/layoutCss/default.less',
          // resources: './src/global.less',
        })
        .end();
    });
  },

**Comment by steveleeh** [comment]
https://github.com/Yatoo2018/webpack-chain/tree/zh-cmn-Hans

`chainWebpack: config => {
    config.module
      .rule('less')
      .test(/\.less$/)
      .oneOf('normal')
      .use('sass-resources-loader')
      .loader('sass-resources-loader')
      .options({
        resources: path.resolve(__dirname, '../src/assets/styles/util.less'),
      })
      .end();
  },`

**Comment by Raymond-Mao** [comment]
> https://github.com/Yatoo2018/webpack-chain/tree/zh-cmn-Hans
> 
> `chainWebpack: config => { config.module .rule('less') .test(/\.less$/) .oneOf('normal') .use('sass-resources-loader') .loader('sass-resources-loader') .options({ resources: path.resolve(__dirname, '../src/assets/styles/util.less'), }) .end(); },`

This setting solves the global scss variables issue.

**Comment by allxblue** [comment]
UMI (用的是2.0) 實在很少人用，使用`@umijs/plugin-sass 1.1.1` ，添加 SCSS global variable 可在 config.js 添加
`
    sass: {
        additionalData: ` 
            @import '@/assets/scss/includes/_variable.scss';
            @import '@/assets/scss/includes/_style-effects.scss';
        `
    }
`
給查詢的人參考。
關鍵字： sass, additionalData, 全域變量

**Comment by OctopusRoe** [comment]
> UMI (用的是2.0) 實在很少人用，使用@umijs/plugin-sass 1.1.1 ，添加 SCSS global variable 可在 config.js (.umirc.js) 添加
> 
> ```
> sass: {
>     additionalData: ` 
>         @import '@/assets/scss/includes/_variable.scss';
>         @import '@/assets/scss/includes/_style-effects.scss';
>     `
> }
> ```
> 
> 給查詢的人參考，希望有節省到您的時間 😁 關鍵字： sass, additionalData, 全域變量

umi3 编译的时候会提示additionalData不是可用字段最优解还是安装 sass-resources-loader 包，然后通过chainWebpack加入配置中

`
config.module
    .rule('sass')
    .oneOfs.values()
    .forEach(item => {
      item
        .use('sass-resources-loader')
        .loader('sass-resources-loader')
        .options({
          resources: path.join(__dirname, '../src/default.module.scss'),
        })
        .end();
    });
`
