### ISSUE TITLE
如何配置mock

### ISSUE THREAD

**Issue by 472756921** [umijs/umi#332]
.umirc.mock.js应该怎么配置？

**Comment by sorrycc** [comment]
参考 https://github.com/sorrycc/roadhog#mock

**Comment by huangshunping** [comment]
@sorrycc 我遇到一样的问题

我现在版本是1.3.16，按照[官方文档](https://umijs.org/guide/mock-data.html)  配置，无法访问到mock数据

最后解决是在.umirc.mock.js里面配置：

const mock = {}
require('fs').readdirSync(require('path').join(__dirname + '/mock')).forEach(function(file) {
    Object.assign(mock, require('./mock/' + file))
})

export default mock;

参考：[.umirc.mock.js](https://github.com/umijs/umi/issues/246)

请问是我哪里配置的不对，还是就应该这样做？
