### ISSUE TITLE
Umi UI 二期问题反馈

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#3320]
> 陆续添加中

## 资产添加 Modal

@chenshuai2144 @yutingzhao1991 

* [ ] 添加的时候路由路径已存在时，默认不报错，切换之后才报错 `待讨论可优化的交互点`
![image](https://user-images.githubusercontent.com/35128/65818373-99a62700-e243-11e9-8bc0-19771b771ec0.png)
* [x] 添加的时候 DetectLanguage 无效，接口返回的是 JavaScript，这里的编译为 JS 仍然未选中
![image](https://user-images.githubusercontent.com/35128/65814043-7497c100-e20f-11e9-81bd-3bc2bbf7faf9.png)
* [x] 编译为 JS 不显示出来，隐藏就好，猜的应该足够准确，不需要用户选
* [ ] mini 下的 Modal 框里显示日志感觉太小
![image](https://user-images.githubusercontent.com/35128/65814069-e40db080-e20f-11e9-9736-d92f6d24c802.png)
* [x] 日志最后一行看不到 @ycjcl868 
![image](https://user-images.githubusercontent.com/35128/65814075-f8ea4400-e20f-11e9-8562-99917fe3c143.png)
* [x] 移除国际化没有记住上次选的
![image](https://user-images.githubusercontent.com/35128/65814131-875ec580-e210-11e9-84bb-d54f09365dce.png)
* [x] 一个模板添加中的时候点另一个模板的添加，没有给出不允许添加警告，而是弹出了 Modal 窗，但是数据也不对
* [x] 模板添加中的时候，点 Modal 的关闭，界面上 Adding... 消息（因为没有完成添加，应该保留，这样用户之后哪个模板正在被添加）
* [x] 表单里的路由路径不是最终添加到用户路由配置里的路由路径，比如 AccountCenter 会被写成 accountcenter
![image](https://user-images.githubusercontent.com/35128/65814243-b295e480-e211-11e9-8e8a-9411bdfe3784.png)
* [x] 区块添加应该没有 `编译为 JS` 和 `移除国际化` 的功能？
* [x] 添加区块时，先添加一个区块（输入自定义名字），添加成功，然后再添加另一个区块时，名字没有给推荐的名字，还是上次自定义输入的名字，然后习惯性地点确定后就报错了
![image](https://user-images.githubusercontent.com/35128/65814656-5f269500-e217-11e9-8ee2-46771979559f.png)
* [x] 添加模板后可能走 HMR 没有刷新（比如 antdpro 的 EditorMind 模板）的时候，添加另一个模板，表单的值还是老的
![image](https://user-images.githubusercontent.com/35128/65816418-eb43b700-e22d-11e9-8eae-d217c2459936.png)
* [x] 任务添加取消功能无效，点停止后后台实际上还在跑，过一会页面就刷新了 @ikobe 
* [x] 编译为 JS 功能无效，勾上了生成出来的文件依旧是 tsx @ikobe 
![image](https://user-images.githubusercontent.com/35128/65817833-69a85500-e23e-11e9-9eb9-7af144541a3e.png)
* [x] 选择路由时意外多出路由，见 GIF 图
![aaa](https://user-images.githubusercontent.com/35128/65817924-43cf8000-e23f-11e9-829a-00b12a5151bd.gif)
* [x] 筛选路由输入任意值报错
![xxx](https://user-images.githubusercontent.com/35128/65818343-58ae1280-e243-11e9-8dd5-e716eec058d6.gif)
* [x] getNpmClients 和 detectNpmClients 的匹配问题，比如用户有 `['a','b']`，探测到项目可能用了 `['c', 'b']`，默认项应该是 `b`，现在是不存在的 `c`，而 `c` 用户可能本地是没有安装过的
* [x] 刷新按钮无效
![image](https://user-images.githubusercontent.com/35128/65826067-5a162400-e2b1-11e9-9492-e8aa525b4a7d.png)
* [x] 清理缓存按钮报错
![image](https://user-images.githubusercontent.com/35128/65826080-8cc01c80-e2b1-11e9-9cf5-8bc002621172.png)
* [x] 区块和模板的分页数据串了，区块里是第四页，点击模板，也切换到第四页

**Comment by chenshuai2144** [comment]
- [ ] mini 模式下一行五个太多，字和图都看不清楚
- [ ] 卡片 padding 太大，浪费空间，应该留给图
- [ ] 弹窗的确定按钮在首屏外，体验不好
- [ ] 编译为 js 和移除国际化有点浪费垂直，应该缩小弱化，横向放
- [ ] 成功后直接提示，不需要点击完成

**Comment by afc163** [comment]
- [ ] 这两个按钮的样式像是坏掉了，高度，对齐都有问题。
![image](https://user-images.githubusercontent.com/507615/65827943-2a264b00-e2c8-11e9-8ecb-a529b66a98fc.png)

**Comment by afc163** [comment]
![image](https://user-images.githubusercontent.com/507615/65827953-43c79280-e2c8-11e9-9083-d7ce0ff27911.png)

**Comment by sorrycc** [comment]
* [ ] 添加出错的时候就上面一个提示，日志里没有给原因。
<img width="680" alt="Image Copied on 2019-09-30 at 16 01 35 PM" src="https://user-images.githubusercontent.com/35128/65860993-046b7580-e39e-11e9-9e3a-4a8a5e10b2a9.png">
* [ ] 添加路由选根目录时，却被添加到 `/user` 下，路由配 `/user-dashboard` 可复现

**Comment by xiaohuoni** [comment]
约定式路由考虑一下（🤦‍♂️）
