### ISSUE TITLE
umi-request设置了超时时间，接口调用出错

### ISSUE THREAD

**Issue by Sayid1** [umijs/umi#3321]
## What happens?
使用 `request.get`发送一个超时请求，接口请求了21s，并且异常处理程序接收到的`response`为`undefined`
但是我设置的超时时间为3000ms

## 复现步骤，错误日志以及相关配置
```javascript
const errorHandler = (error: { response: Response }): void => {
  const { response } = error
  console.log(response) // 此处打印出来为undefined
  if (response && response.status) {
    const errorText = codeMessage[response.status] || response.statusText
    message.error(errorText)
  }
}

const request: RequestMethod = extend({
  errorHandler, // 默认错误处理
  credentials: 'include', // 默认请求是否带上cookie
  timeout: 3000
})
```

![image](https://user-images.githubusercontent.com/29008437/65814982-ccd4c000-e21b-11e9-887a-da6580e6793b.png)
![image](https://user-images.githubusercontent.com/29008437/65815033-6a2ff400-e21c-11e9-863d-8df35338f680.png)

## 相关环境信息

- **Umi 版本**：^2.8.7
- **Node 版本**：v8.11.4
- **操作系统**：window 10

**Comment by Sayid1** [comment]
@sorrycc 大佬看下咯

**Comment by Sayid1** [comment]
@chenshuai2144 帅哥看下咯  等着用呢

**Comment by chenjsh36** [comment]
response 为 undefined 是正常的，因为你设置了超时时间为 3s，所以在 3s 后请求会被忽略然后 reject 并抛出请求超时的异常，这个时候由于接口还没有响应返回，所以 **error.response** 是 undefined，如果要捕获超时异常，可以参考文档关于[错误处理](https://github.com/umijs/umi-request/blob/master/README_zh-CN.md#错误处理) 文档：

``` javascript
const errorHandler = function (error) {
  const codeMap = {
    '021': '发生错误啦',
    '022': '发生大大大大错误啦',
    // ....
  };
  if (error.response) {
    // 请求已发送但服务端返回状态码非 2xx 的响应
    console.log(error.response.status);
    console.log(error.response.headers);
    console.log(error.data);
    console.log(error.request);
    console.log(codeMap[error.data.status])
    
  } else {
    // 请求初始化时出错或者没有响应返回（如请求超时）的异常
    // 在这里处理请求超时的情况
    console.log(error.message);
  }

  throw error;   // 如果throw. 错误将继续抛出.
  
  // 如果return, 则将值作为返回. 'return;' 相当于return undefined, 在处理结果时判断response是否有值即可.
  // return {some: 'data'}; 
}
```

**Comment by sanshuiwang** [comment]
我们某个api响应时间是30s左右，由于客户端request这边未设置timeout，会直接走throw的erroeHandle。
造成了请求中断,response为null, respose.json则无法正常解析。
