### ISSUE TITLE
npm run lint-staged:js package.json not work,or more error info

### ISSUE THREAD

**Issue by donghanji** [umijs/umi#3324]
## What happens?

first,scripts config in package.json:
`
"lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
`
don't work,no eslint directory，to change it:
`
"lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ./src",
`
when run :
`
npm run lint-staged:js
`
output more error info:
```
umi-test/src/components/GlobalHeader/RightContent.jsx
  37:11  warning  Unexpected console statement  no-console
  40:11  warning  Unexpected console statement  no-console

umi-test/src/components/NoticeIcon/NoticeList.jsx
  40:28  error  Do not nest ternary expressions  no-nested-ternary

umi-test/src/components/SettingDrawer/themeColorClient.js
  3:19  error  Requires 'eslint-enable' directive for 'import/no-extraneous-dependencies'  eslint-comments/disable-enable-pair

umi-test/src/e2e/baseLayout.e2e.js
   2:18  warning  `lodash` import should occur before import of `../../config/config`  import/order
  35:3   warning  Unexpected console statement                                         no-console

umi-test/src/global.jsx
  47:1  error  Line 47 exceeds the maximum line length of 100  max-len

umi-test/src/layouts/SecurityLayout.jsx
  27:1  error  Line 27 exceeds the maximum line length of 100  max-len

umi-test/src/pages/user/login/components/Login/LoginItem.jsx
  87:1  error  Line 87 exceeds the maximum line length of 100  max-len
```

when 
`npm run lint`
`npm run lint:fix`

also out put more errors.

## How To Reproduce
**Steps to reproduce the behavior:**
1.yarn create umi
2.select `ant design pro`,`javascript`
3.yarn
4. change package.json scripts config :`"lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ./src",`
5.npm run lint-staged:js

**Expected behavior**
1.npm run lint,or num run lint-staged:js,no error info
2.Pass the code checking before commit the code

## Context

- **Create Umi Version**:0.17.0
- **Umi Version**:^2.8.7
- **Node Version**:v11.15.0
- **Platform**:mac OS High Sierra 10.13.5

**Comment by xiaohuoni** [comment]
pro 的问题请提交到 https://github.com/ant-design/ant-design-pro/issues
