### ISSUE TITLE
windows 10 下使用`umi dev `，ctrl + c 退出后nodejs进程没有退出

### ISSUE THREAD

**Issue by klouskingsley** [umijs/umi#333]
如下图：
![gif](https://user-images.githubusercontent.com/12490787/38788374-ec4b52bc-4165-11e8-9990-5e776b77a5b3.gif)

**Comment by xiaohuoni** [comment]
这个修复了吧？我这边重现不了了？

**Comment by sorrycc** [comment]
先 close 了，有问题再 reopen 。
