### ISSUE TITLE
官方demo(umi-example-ssr)跑起来报错

### ISSUE THREAD

**Issue by 419280377** [umijs/umi#3334]
一、demo地址：https://github.com/umijs/umi-example-ssr
二、本地环境
1、node：v10.13.0
2、umi：2.9.6
三、yarn dev后的问题
1、页面样式布局和github中不一致
2、umi is not defined
![image](https://user-images.githubusercontent.com/20454290/65828865-331c1a00-e2d2-11e9-93c2-74056c66e081.png)

请问如何fix呀？

**Comment by ycjcl868** [comment]
访问 `http://localhost:7001` server 服务
