### ISSUE TITLE
umi-request 使用get方式请求时，嵌套的params会被转成 [object, Object]

### ISSUE THREAD

**Issue by truejiang** [umijs/umi#3335]
let params = {
      pager: {
        page: 1,
        page_size: 15
      }
   }

request.get('/api/v1/some/api', {
    params
})
这种情况请求
Query String Parameters 是 pager=%5Bobject%20Object%5D

如果用了 JSON.stringify 

request.get('/api/v1/some/api', {
    params: JSON.stringify(params)
})

这种情况请求
Query String Parameters 是0=%7B&1=%22&10=%22&11=p&12=a&13=g&14=e&15=%22&16=%3A&17=1&18=%7D&19=%7D&2=p&3=a&4=g&5=e&6=r&7=%22&8=%3A&9=%7B

同样的请求用axios就是正常的

**Comment by chenjsh36** [comment]
新版本 1.2.7 已修复嵌套 params 问题，请升级至新版本，详见[1.2.7](https://github.com/umijs/umi-request/releases/tag/v1.2.7)
