### ISSUE TITLE
Plugin user:node_modules/umi-plugin-react/lib/index.js initialize failed

### ISSUE THREAD

**Issue by asevenm** [umijs/umi#3339]
## What happens?
I got errors  when executed umi dev or umi build.
Plugin user:node_modules/umi-plugin-react/lib/index.js initialize failed
 Cannot find module '../ui/dist/index.umd'
error Command failed with exit code 1.

## 相关环境信息

- **Umi 版本**: 2.6.8
- **Node 版本**：10.15.3 or 8.14.0
- **操作系统**：Mac os

**Comment by LiuL0703** [comment]
> Plugin user:node_modules/umi-plugin-react/lib/index.js initialize failed
Cannot find module '../ui/dist/index.umd'

some!!! help

**Comment by sorrycc** [comment]
node_modules 和 yarn.lock 删了重装，有问题的 umi-plugin-react 版本已回退。

**Comment by xileliu** [comment]
@sorrycc 用最新的umijs 生成基础工程，但是移除node_modules yarn.lock 重新安装还是报这个错误

**Comment by gaomeng965** [comment]
我也报这个错，/node_modules/@umijs/plugin-qiankun/lib/index.js: api.describe is not a function (36, 7)

**Comment by Aledenn** [comment]
> 我也报这个错，/node_modules/@umijs/plugin-qiankun/lib/index.js: api.describe is not a function (36, 7)
你是umi2吗 因为umi2的插件开发文档真的没有这个函数.... 我也遇到这个问题了

**Comment by TQ-Martin** [comment]
> 我也报这个错，/node_modules/@umijs/plugin-qiankun/lib/index.js: api.describe is not a function (36, 7)
你把@umijs/plugin-qiankun版本回退到1.5.5(官方实例用的这个版本，所以我就回退到这个版本)，这个问题就解决了

**Comment by wsdqr001** [comment]
> > 我也报这个错，/node_modules/@umijs/plugin-qiankun/lib/index.js: api.describe is not a function (36, 7)
> > 你把@umijs/plugin-qiankun版本回退到1.5.5(官方实例用的这个版本，所以我就回退到这个版本)，这个问题就解决了
回退到1.5.5又爆了这个错：
error     Plugin qiankun-slave initialize failed，api.modifyPublicPathStr is not a function

**Comment by liuxiuqian** [comment]
> error Plugin qiankun-slave initialize failed，api.modifyPublicPathStr is n

你的这个错误解决了吗
