### ISSUE TITLE
yarn lint:ts 报错

### ISSUE THREAD

**Issue by skyunBoss** [umijs/umi#3343]
## What happens?
yarn lint:ts 报错

## Mini Showcase Repository(REQUIRED)

直接使用 yarn create umi 命令选择 app 模板创建 umi 项目。

Failed to load /project/ziguang-single-page/tslint.yml: Cannot convert undefined or null to object
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## Context

- **Umi Version**:2.9.0
- **Node Version**:10.16.0
- **Platform**:MacOS 10.14.6

**Comment by sorrycc** [comment]
Duplicated #3342 .

**Comment by skyunBoss** [comment]
> Duplicated #3342 .

没有说明问题在哪啊？
