### ISSUE TITLE
2019.9.30 umi新建项目控制台error

### ISSUE THREAD

**Issue by ywy94ywy** [umijs/umi#3345]
## What happens?
2019.9.30 14.14 
步骤
①yarn create umi（选择ant design pro，javascript）
②yarn
③yarn start
启动成功，控制台error

index.js:1 
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
Check the render method of `ResizeObserver`
in Typography (created by ResizeObserver)
    in ResizeObserver (created by LocaleReceiver)
    in LocaleReceiver (created by Base)
    in Base (created by Context.Consumer)
...........

所有版本为2019.9.30 最新下载

**Comment by ywy94ywy** [comment]
通过删除欢迎页的所有包含Typography的控件，问题得以解决

**Comment by sorrycc** [comment]
@chenshuai2144 看下。

**Comment by xiaohuoni** [comment]
@chenshuai2144
