### ISSUE TITLE
[Feature Request]希望升级 umi-locale的 react-intl 依赖

### ISSUE THREAD

**Issue by arvinxx** [umijs/umi#3347]
## Background

如题所示，react-intl v3 引入了一些更棒的特性，例如 FormattedMessage和formatMessage 的富文本能力。希望进行能够更新其依赖

ref: [Upgrade Guide for react-intl@3.x](
 https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md#enhanced-formattedmessage--formatmessage-rich-text-formatting)

**Comment by ycjcl868** [comment]
locale 插件考虑重构下，在保证兼容 v2 的同时做升级
