### ISSUE TITLE
build时无法设置process.env.NODE_ENV='development'

### ISSUE THREAD

**Issue by langlong149** [umijs/umi#3349]
## What happens?

测试环境有1，2，3共3个环境，1环境希望不使用代码压缩等，须将process.env.NODE_ENV设置为development。但当我设置后，执行yarn build时会报以下错误：
![image](https://user-images.githubusercontent.com/19711638/66177230-409b2080-e693-11e9-9223-9ccff1093909.png)

查看代码发现umi中有如下代码：
`    (0, _assert().default)(this.env === 'production', `HtmlGenerator.generate() should only be used in umi build`);`

请问这个限制可以去掉吗？
ps：在define中设置process.env.COMPRESS不生效，需要直接赋值。可以解决这个问题。

## 相关环境信息

- **Umi 版本2.9.6**：
- **Node 版本10.16.3**：
- **操作系统 mac**：

**Comment by ycjcl868** [comment]
```diff
// package.json

{
  "script": {
-     "build": "umi build"
+     "build": "COMPRESS=none umi build"
   }
}
```
