### ISSUE TITLE
context赋值失效

### ISSUE THREAD

**Issue by webup** [umijs/umi#335]
基于example/simple的代码，按 https://umijs.org/docs/en/config-umi.html#pages 提到的几种方式设置context: { title: 'xxx' }，在document.ejs里面打印context值，都是 { path: undefined }，无法获取title。

**Comment by webup** [comment]
build之后在生产模式也是没有输出context.title @sorrycc

**Comment by sorrycc** [comment]
context 的替换只有在配了 exportStatic 后才有效，因为如果是单页，在 index.html 输出就好了。参考：https://github.com/umijs/umi-examples/tree/master/context
