### ISSUE TITLE
问题：Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by 419280377** [umijs/umi#3352]
一、问题：官方umi-example-ssr例子build部署后报错Unexpected token '<'，扫了一遍其他类似issue，但没答案，例如：https://github.com/umijs/umi-example-ssr/issues/12
![image](https://user-images.githubusercontent.com/20454290/66269705-43a63480-e87e-11e9-8039-c467c99cc1ee.png)

二、环境
1、node：10.13.0

三、可重现仓库：https://gitee.com/ToDanger/web.huajun.seo

感谢大佬们在百忙中抽空帮忙，🙏！

**Comment by 419280377** [comment]
> @ycjcl868 请看下。

可重现demo：https://gitee.com/ToDanger/web.huajun.seo
yarn dev没问题，build就Unexpected token '<'

**Comment by ycjcl868** [comment]
`yarn start` 有问题吗？

**Comment by 419280377** [comment]
问题已解决，感谢宜鑫！

**Comment by DearGaz** [comment]
> ![image](https://user-images.githubusercontent.com/13595509/66547491-f376ed00-eb71-11e9-981e-b5afd78484d7.png)
> 
> publicPath 静态资源路径配置不正确。
> 
> 将 `.umirc.js` 中的 `publicPath` 配置成 `/` 就ok了

@ycjcl868  请问umi@3.0下publicPath配置是不支持./ 么？
