### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by shenyiling** [umijs/umi#3366]
## what happen

qq浏览器下加载页面空白，错误如下：
![image](https://user-images.githubusercontent.com/25818722/66457063-028e6a00-eaa2-11e9-953f-6a0fc1df6827.png)

有配置`targets`:
```js
targets: {
    android: 4,
    ie:9
}
```

## 浏览器版本

![image](https://user-images.githubusercontent.com/25818722/66457227-73358680-eaa2-11e9-8edb-379661cd4c17.png)

请教下如何处理呢？

**Comment by xiaohuoni** [comment]
先自己排查一下 https://github.com/umijs/umi/issues/1421#issuecomment-516762499
