### ISSUE TITLE
插件修改路由怎么赋值成 require('xxx').default

### ISSUE THREAD

**Issue by yoyooyooo** [umijs/umi#3367]
## 目的
想通过约定式路由写个menu菜单，通过插件的形式给route加一个icon，期望生成的.umi/router.js 里的routes能像component或者Routes那样，加个 `icon: require('xxx').default`。

## 实际代码
插件写法
```js
api.onPatchRoute(async ({ route }) => {
    // ...省略判断
    route.icon = `require('./page同级下的icon.js路径').default`;
})
```

实际的到的.umi/router.js ——routes ：
```
...
icon:  "require('xx').default"  //  还是字符串
...
```

## 期望
有没有办法能去掉这个引号？或者约定 route.icon = \`"require('xxx').default"\` 的时候去掉引号怎么样？
或者像component/Routes那样把相对路径写入.umi/router.js的时候自动套上require。
不想换配置式路由，那样就失去了umi最方便的约定式路由。

**Comment by aixfox** [comment]
照你的理解不是应该这样吗：

```javascript
// plugin
api.onPatchRoute(async ({ route }) => {
    // ...省略判断
    route.icon = `./page同级下的icon.js路径`;
})

// Menu.js
icon = require(route.icon).default
```

umi 及其 plugin 并没有保证 .umi 下生成什么样子，依赖这个不合适吧。
可以考虑把 route path 和 icon 的关系维护在一个表里。
```javascript
const mapRoutePathToIcon = {
  [route_path_0]: require('icon0').default,
}
```
