### ISSUE TITLE
upgrade umi1.14->1.16报错

### ISSUE THREAD

**Issue by jincan39** [umijs/umi#337]
- 环境 
umi                   1.1.4  →   1.1.6
umi-plugin-dva       ^0.5.0  →  ^0.6.1

-报错信息
Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead.
    in div (created by Count)
    in div (created by Count)
    in Count (created by Connect(Count))
    in Connect(Count) (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by Route)
    in Route (created by Route)
    in Switch (created by Route)
    in div (created by Basic)
    in Basic (created by Adapter)
    in Adapter
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter
    in div (created by BasicLayout)
    in BasicLayout (created by Adapter)
    in Adapter
    in div
    in IntlProvider
    in Unknown (created by Connect(Component))
    in Connect(Component) (created by Route)
    in Route (created by withRouter(Connect(Component)))
    in withRouter(Connect(Component)) (created by Route)
    in Route
    in Switch
    in Router (created by ConnectedRouter)
    in ConnectedRouter
    in Unknown
    in Provider (created by DvaContainer)
    in DvaContainer

**Comment by sorrycc** [comment]
传下可重现代码？

**Comment by sorrycc** [comment]
没有上传 . 开头的配置文件?

**Comment by sorrycc** [comment]
没有上传 . 开头的配置文件?

**Comment by xiaohuoni** [comment]
这里count返回的是一个空对象，使用{}解析出错。
```js
export default {
  namespace: 'count',
  state:0,
  reducers: {
    increase(state) {
      return ++state;
    },
    decrease(state) {
      return --state ;
    },
  },
  subscriptions: {
    setup({ dispatch, history }) {
      return history.listen(({ pathname, query }) => {
        console.log(history,'history');
      });
    },
  },
};
```
这个demo这里的state是一个数值，传递到index.js是count={}
之前版本可以运行
实际项目中应该是使用如下
```js
export default {
  namespace: 'count',
  state:{
    count:0
  },
  reducers: {
    increase(state) {
      return {...state,count:++state.count};
    },
    decrease(state) {
      return {...state,count:--state.count};
    },
  },
  subscriptions: {
    setup({ dispatch, history }) {
      return history.listen(({ pathname, query }) => {
        console.log(history,'history');
      });
    },
  },
};
```
这样一个对象
count:{count: 0}
应该是一个bug

**Comment by xiaohuoni** [comment]
和版本什么的没有关系。
```js
export default {
  hashHistory: true,
  plugins: [
    ['umi-plugin-dva', { immer: true }],
    [
      'umi-plugin-routes',
      {
        exclude: [
          /model\.(j|t)sx?$/,
          /service\.(j|t)sx?$/,
          /models\//,
          /components\//,
          /services\//,
        ],
      },
    ],
  ],
};
```
设置了immer: true 。
这里就会返回空

**Comment by sorrycc** [comment]
@xiaohuoni 定位到原因了？

**Comment by xiaohuoni** [comment]
是我上面说的那个原因 @sorrycc

**Comment by sorrycc** [comment]
非 umi 问题就先关了，有问题再 reopen 。
