### ISSUE TITLE
在eleme-example中启动时报错Module build failed: Error: Cannot find module 'babel-eslint'

### ISSUE THREAD

**Issue by suiyi8760** [umijs/umi#338]
按理说umi应该是包含了babel-eslint了，不用另外配置吧，是否node环境使用的是nvm的原因，系统macOS10.13.4

**Comment by sorrycc** [comment]
把 eleme-example copy 到外面试试呢？

**Comment by suiyi8760** [comment]
😂可能我说不清楚，意思是umi全局装的话被装到nvm里，我google类似错误好像会跟nvm有关，目前解决办法是在目录里安装babel-eslint，感觉应该有其他解决办法

**Comment by sorrycc** [comment]
eleme-example 是在 umi 的库下？copy 到外面试试看。

**Comment by suiyi8760** [comment]
eleme-demo 不在umi库下的，对了ide用的webstorm，但是eslint已经disable掉了

**Comment by sorrycc** [comment]
用的 npm/cnpm/yarn ?

**Comment by suiyi8760** [comment]
npm 5.8.0
node 8.9.0

**Comment by sorrycc** [comment]
测过确实是，那就装个依赖吧。
