### ISSUE TITLE
umi+dva+redux-undo 如何配置

### ISSUE THREAD

**Issue by yetingmao** [umijs/umi#3384]
我在使用umi+dva搭建框架是，项目业务里需要加入redux-undo
## What happens?
我在app.ts文件里面加入配置然后就报错了

![image](https://user-images.githubusercontent.com/20633411/66536365-3ffd0100-eb4f-11e9-9b8b-79d6efc468a4.png)
![image](https://user-images.githubusercontent.com/20633411/66536509-c6b1de00-eb4f-11e9-85b2-7ed46ecb5690.png)

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：  "umi": "^2.9.0"
- **Node 版本**：v10.15.3
- **操作系统**：window10

**Comment by 154305** [comment]
import undoable from 'redux-undo';
const app = dva({
  onReducer: reducer => {
    return (state, action) => {
      const undoOpts = {};
      const newState = undoable(reducer, undoOpts)(state, action);
      // 由于 dva 同步了 routing 数据，所以需要把这部分还原
      return { ...newState, **### routing: newState.present.routing** };
    },
  },
});
看看dva官网这一段

**Comment by 154305** [comment]
`import undoable from 'redux-undo';
const app = dva({
  onReducer: reducer => {
    return (state, action) => {
      const undoOpts = {};
      const newState = undoable(reducer, undoOpts)(state, action);
      // 由于 dva 同步了 routing 数据，所以需要把这部分还原
      return { ...newState, routing: newState.present.routing };
    },
  },
});`看看官网的返回的是啥
