### ISSUE TITLE
umi 2.9.5 ssr Cannot find module 'history'

### ISSUE THREAD

**Issue by Nabufaces** [umijs/umi#3396]
## What happens?
umi 2.9.5 setting ssr = true and require umi.server.js throw Cannot find module 'history'

**Comment by jin-benben** [comment]
想问下你的这也问题解决了，我也遇到同样的问题，创建一个新的egg项目，把前端打包后文件放到public，修改HomeController后运行就会报这个错误

**Comment by ctq123** [comment]
+1
