### ISSUE TITLE
嵌套路由如何同级展示？

### ISSUE THREAD

**Issue by poyiding** [umijs/umi#3398]
## What happens?
比如一个 table 页面，进入某个数据的详情页，这种嵌套路由的同级展示如何处理？
![image](https://user-images.githubusercontent.com/15643321/66563607-b40bc900-eb90-11e9-9acd-f8bf8c26baad.png)
路由配置
![image](https://user-images.githubusercontent.com/15643321/66564180-f8e42f80-eb91-11e9-8f41-3898de8abd71.png)

目前我是在config中给详情页设置 hideInMenue; 有其他更好的方法么？

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by yoyooyooo** [comment]
你planId都是不定的，详情放在menu有什么意义。。单独点的时候跳到哪？

**Comment by poyiding** [comment]
> 你planId都是不定的，详情放在menu有什么意义。。单独点的时候跳到哪？

你没明白嵌套路由同级展示的意思，项目详情归属项目list，不能再同一级，问题就出在这，所以我通过hideInMenue把项目详情的菜单隐藏，我的问题是有没有更好的方法。

**Comment by xiaohuoni** [comment]
菜单和路由数据应该分开来比较好，你如果用一份数据，那你这个处理方法没有错。

**Comment by poyiding** [comment]
> 菜单和路由数据应该分开来比较好，你如果用一份数据，那你这个处理方法没有错。

不太明白你指的的菜单和路由数据应该分开来比较好？能否举个例子说明一下？菜单本身就是根据路由生成的哇。

**Comment by xiaohuoni** [comment]
菜单是为了菜单栏的导航的数据，路由是你整个项目中可以访问的所有的页面。比如你可以通过服务端做到动态菜单，但是你不能做到动态路由，因为路由是提前编译好的

**Comment by ShawLyon** [comment]
> > 菜单和路由数据应该分开来比较好，你如果用一份数据，那你这个处理方法没有错。
> 
> 不太明白你指的的菜单和路由数据应该分开来比较好？能否举个例子说明一下？菜单本身就是根据路由生成的哇。

遇到同样问题，不然面包屑“项目和项目详情”达不到嵌套的关系
