### ISSUE TITLE
Umi 兼容ie8的问题

### ISSUE THREAD

**Issue by wind17** [umijs/umi#3399]
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：
Umi v2.9.6
请问除了在 .umirc.js 里配置 targets能兼容到ie9 以外，有方式能兼容到ie8吗

**Comment by iceberg211** [comment]
react v16 都不兼容ie8

**Comment by sorrycc** [comment]
ie8 兼容不了，主要依赖库都不兼容他。
