### ISSUE TITLE
targets: ie11 not working [v2.10.1]

### ISSUE THREAD

**Issue by jwmann** [umijs/umi#3409]
## What happens?
When I build the app with `targets: { ie: 11 },` the output of `umi.js` contains arrow functions `() => {}`  and `const` variables.

This will obviously throw errors in IE 11.

## Mini Showcase Repository(REQUIRED)

https://github.com/jwmann/umijs-targets-ie11-bug

Look at `dist/umi.js`

## How To Reproduce
**Steps to reproduce the behavior:**
1. `npm run build`
2. Open it in IE 11

**Expected behavior**
1. Works in IE 11

## Context

- **Umi Version**: `2.10.1`
- **Node Version**: `v12.10.0`

**Comment by sorrycc** [comment]
Can you find out where the `() => {}` come from?

**Comment by leftstick** [comment]
@jwmann caused by the `react-spring`, fixed. You can give a try while later new version of `es5-imcompatible-versions` published.
