### ISSUE TITLE
定制主题

### ISSUE THREAD

**Issue by Dorisfeng** [umijs/umi#341]
根目录新建.webpackrc.js，设置如下
export default {
  "theme": {
    "primary-color": "#7546c9"
  }
}
自定义主题未生效

**Comment by lusess123** [comment]
同样的问题

**Comment by xiaohuoni** [comment]
有效

**Comment by sorrycc** [comment]
测过没问题，https://github.com/umijs/umi-examples/tree/master/theme

**Comment by lusess123** [comment]
原因找到了，我用的pro组件是独立发布版本的， 因为独立版自带antd  的默认样式，导致换肤的less样式被覆盖导致。[讨论](https://github.com/ant-design/ant-design-pro/issues/1317#issuecomment-382311970)
