### ISSUE TITLE
umi-request get请求params序列化的问题

### ISSUE THREAD

**Issue by linchengzzz** [umijs/umi#3413]
当 `params` 对象里面的参数的值 为 `null` 的时候，序列化失效

> 更新到 v1.2.7 遇到的问题, 之前用的版本是 v1.0.7, 这是一个 feature 还是一个 bug 呢？

**v1.0.7:** `params: { a: null, b: null, c: '', d: 1}` 序列化之后 http://xxxx?a&b&c=&d=1
**v1.2.7:** `params: { a: null, b: null, c: '', d: 1}` 序列化之后 http://xxxx?c=&d=1

**Comment by chenjsh36** [comment]
之前为支持嵌套对象类型的 params 而更新了序列化 params 的逻辑，导致当 a === null 时没有了该参数，1.2.8 已经兼容老版，但当 params 为嵌套对象时，由于使用了 JSON.stringify 进行格式化，内嵌对象里的 null 参数会带上。

**Comment by linchengzzz** [comment]
> 之前为支持嵌套对象类型的 params 而更新了序列化 params 的逻辑，导致当 a === null 时没有了该参数，1.2.8 已经兼容老版，但当 params 为嵌套对象时，由于使用了 JSON.stringify 进行格式化，内嵌对象里的 null 参数会带上。

好的，辛苦了，明天上班了去更新后试下
