### ISSUE TITLE
Find return statement failed  

### ISSUE THREAD

**Issue by southnan0** [umijs/umi#3414]
## What happens?
使用umi 2.10.1 ，函数组件return如果包在if...else代码块里，在开发过程中，会提示没有return 的错误。在build的时候却不会报错。

## 复现步骤，错误日志以及相关配置

代码片段
![image](https://user-images.githubusercontent.com/3942033/66696330-bb041a00-ecfd-11e9-89e2-ec1bb62ba1f9.png)
开发过程报错提示
![image](https://user-images.githubusercontent.com/3942033/66696338-c7887280-ecfd-11e9-9fec-bd11694cc61a.png)
把最后面的else注释之后，报错解决
![微信图片_20191012144035](https://user-images.githubusercontent.com/3942033/66696403-4e3d4f80-ecfe-11e9-9829-777599765716.png)

## 相关环境信息

- **Umi 版本**：2.10.1
- **Node 版本**：10+
- **操作系统**：window7

**Comment by sorrycc** [comment]
是 bug，马上修复。

**Comment by sorrycc** [comment]
试试 umi@2.10.2 。
