### ISSUE TITLE
extent如何处理返回数据？

### ISSUE THREAD

**Issue by gaorubin1990** [umijs/umi#3415]
## What happens?
使用  umi-request 封装的 extent 方法，如何统一的处理返回数据？例如后台api返回的数据都封装了一层，包裹了一层data，如 { data: { ...需要的数据 } }。如何能在request.js文件中统一的处理，将data层去掉，返回 { ...需要的数据 }？

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.import { extend } from 'umi-request';
2.使用extend方法

**Expected behavior**
不知如何在request文件中统一处理数据

## Context

- **Umi Version**: 2.10.1
- **Node Version**:
- **Platform**:mac

**Comment by gaorubin1990** [comment]
石沉大海。。。

**Comment by chenjsh36** [comment]
可以通过 umi-request 的中间件来实现，详细请参考[中间件章节](https://github.com/umijs/umi-request/blob/master/README_zh-CN.md#%E4%B8%AD%E9%97%B4%E4%BB%B6)

``` javascript
import { extend } from 'umi-request';

const request = extend({});

 // 通过中间件在请求响应后对数据统一处理
request.use(async (ctx, next) => {
  await next();
  const { res } = ctx;
  const { data } = res; // 将 res 里的 data 取出来
  ctx.res = data;
})

// 请求
request('/api/some')
  .then( data => console.log(data) )
```

**Comment by xiaohuoni** [comment]
楼上正解，项目中亲测有效。

**Comment by gaorubin1990** [comment]
非常感谢
