### ISSUE TITLE
umi-request 在IE11下参数化失败

### ISSUE THREAD

**Issue by ourfeel** [umijs/umi#3417]
## What happens?

umi-request 在IE11下GET请求， 提示调用的对象无效错误

## 复现步骤，错误日志以及相关配置
Error: TypeError: 调用的对象无效
at isArray (http://test.static.huayu.nd/up/umi/umi.656f304d.js:55033:3)

## 原因

Window的toString是特定于实现的,规范中没有任何内容说DOM主机对象上的方法必须使用call / on other objects 

## 相关环境信息

- **Umi 版本**：2.8.7
- **Node 版本**：
- **操作系统**：win10

**Comment by chenjsh36** [comment]
umi-request 1.2.8 版本已经更新修复，请更新 umi-request 版本或重新安装依赖库再试试看。
