### ISSUE TITLE
为什么按照CONTRIBUTING 的说明跑不起来呢?

### ISSUE THREAD

**Issue by KingJeason** [umijs/umi#3421]
卡在了learn bootstrap这一步
![image](https://user-images.githubusercontent.com/15926513/66710342-edb71c80-eda8-11e9-90d2-4c5f7886f370.png)

**Comment by sorrycc** [comment]
这是在安装依赖，时间多少取决于你的网络，如果命令行走翻墙可能会快一些，或者可以指定客户端执行，比如 `y bootstrap --npm-client cnpm`。
