### ISSUE TITLE
'api.changePluginOption' not work

### ISSUE THREAD

**Issue by chiaweilee** [umijs/umi#3422]
## What happens?

`api.changePluginOption` not work

## Mini Showcase Repository(REQUIRED)

https://github.com/chiaweilee/umi-plugin-pwa

## How To Reproduce
**Steps to reproduce the behavior:**

### 1. `api.changePluginOption('plugin-id', {})`

```js
api.changePluginOption('umi-plugin-react', {});
```

`_umi-build-dev@1.13.8@umi-build-dev/lib/Service.js: plugin umi-plugin-react not found (307, 27)`

### 2. check `changePluginOption()`

```js
  changePluginOption(id, newOpts) {
    (0, _assert().default)(id, `id must supplied`);
    console.log(this.plugins.map(p => p.id)); //  <-- 👈debug
    const plugin = this.plugins.filter(p => p.id === id)[0];
    (0, _assert().default)(plugin, `plugin ${id} not found`);
    plugin.opts = newOpts;

    if (plugin.onOptionChange) {
      plugin.onOptionChange(newOpts);
    } else {
      this.restart(`plugin ${id}'s option changed`);
    }
  }
```

got:

```
  'built-in:plugins/importFromUmi',
  'user:node_modules/umi-plugin-md/lib/index.js',
  'user:node_modules/umi-plugin-react/lib/index.js',
  'umi-plugin-react:dynamicImport',
  'umi-plugin-react:dva',
  'umi-plugin-react:routes',
  'umi-plugin-react:antd',
  'umi-plugin-react:title'
```

### 3. try `umi-plugin-react:title`

```js
api.changePluginOption('umi-plugin-react:title', 'title');
```

`_umi-plugin-react@1.12.3@umi-plugin-react/lib/plugins/title/index.js: api.rebuildTmpFiles is not a function (76, 9)`

### 4. and also try 'umi-plugin-react:pwa'

```js
api.changePluginOption('umi-plugin-react:pwa', {});
```

`_umi-build-dev@1.13.8@umi-build-dev/lib/Service.js: plugin umi-plugin-react:pwa not found (308, 27)`

**Expected behavior**

`changePluginOption` should work

```js
api.changePluginOption('dva-plugin-id', {
  immer: true,
});
```
## Context

- **Umi Version**: 2.10.2
- **Node Version**: 12.10.0
- **Platform**: mac os

**Comment by ycjcl868** [comment]
删除 `yarn.lock`、`package-lock.json` 并升级到最新

**Comment by chiaweilee** [comment]
> 删除 `yarn.lock`、`package-lock.json` 并升级到最新

not work for me,
`/_umi-build-dev@1.13.10@umi-build-dev/lib/Service.js: plugin umi-plugin-react not found (307, 27)
`

**Comment by chiaweilee** [comment]
Turns out,
![Untitled Diagram](https://user-images.githubusercontent.com/29817353/67620053-38b74200-f835-11e9-9b84-5106afeeeaaa.jpg)
