### ISSUE TITLE
umi升级到2.10.2，SSR 工程会多访问一个不存在的资源sockjs-node。

### ISSUE THREAD

**Issue by elivoa** [umijs/umi#3428]
受影响的版本 umi: 2.10.2，以前的版本没问题。

SSR方式启动时 7001端口，(umi-example-ssr-with-egg)，会多访问一个资源，但是404，链接如下：
http://localhost:7001/sockjs-node/873/2ez33eog/xhr_streaming?t=1571024426662

8000端口启动时没有问题。

**Comment by sorrycc** [comment]
已修复，更新到 2.10.3。
