### ISSUE TITLE
Relative path in cssModulesExcludes does not work

### ISSUE THREAD

**Issue by klouskingsley** [umijs/umi#343]
- It does not work
```js
// .webpackrc
const path = require('path')

export default {
  cssModulesExcludes: [
    './src/layouts/Header.less'
  ]
}

```

- It works
```js
// .webpackrc
const path = require('path')

export default {
  cssModulesExcludes: [
    path.resolve(__dirname, './src/layouts/Header.less')
  ]
}

```

**Comment by klouskingsley** [comment]
看代码是只对global.css进行了path.join https://github.com/umijs/umi/blob/e0199c51d33fdd628f0a7363bfd4d3cad6b1477e/packages/umi-build-dev/src/plugins/global-css.js#L43

**Comment by sorrycc** [comment]
> 试过了，是不行的

确定试过？我刚测了下是这个规则，不加 `./` 就可以。

**Comment by sorrycc** [comment]
和 global.css 是两个逻辑。

**Comment by klouskingsley** [comment]
确定试过了，windows 10下

**Comment by sorrycc** [comment]
windows 下是不是反斜杠的，试试 `src\layouts\Header.less`。

**Comment by klouskingsley** [comment]
> windows 下是不是反斜杠的，试试 `src\layouts\Header.less`。

`src\\layouts\\Header.less`这样是可以的
