### ISSUE TITLE
路由发生变化，如何取消页面跳转？

### ISSUE THREAD

**Issue by lusess123** [umijs/umi#344]
有时候路由发生变化，我并不想进行页面跳转，而是在当前页面上进行页面内的操作 。能否增加路由控制的钩子，让我可以根据业务条件取消页面跳转，并且执行组件内操作？

**Comment by sorrycc** [comment]
umi 的路由是基于 react-router@4，他不支持这个功能。

**Comment by lusess123** [comment]
这个有点坑啊 ，  umi 能否帮忙填上
