### ISSUE TITLE
无法出现二级菜单

### ISSUE THREAD

**Issue by gaorubin1990** [umijs/umi#3441]
## What happens?
在layout配置了菜单后无法出现二级菜单

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.const menuDataRender = () => {
    return (
      [
        {
          path: "/base",
          name: '基础配置',
          icon: "setting",
          routes: [
            {
              path: "/base/user",
              name: "用户",
              exact: true
            },
          ]
        }
      ]
    )
  }
2.menuDataRender={menuDataRender}

**Expected behavior**
1.能够出现二级菜单，目前只有基础配置一级菜单
2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by gaorubin1990** [comment]
发现问题了，要把routes换成children
https://pro.ant.design/docs/router-and-nav-cn
这一章节的说明有问题啊。命名按照文档的说明去做是有问题的，是要把routes改成children的

**Comment by xiaohuoni** [comment]
pro的问题，请提交到 https://github.com/ant-design/ant-design-pro/issues
