### ISSUE TITLE
IE11运行异常

### ISSUE THREAD

**Issue by xoptimal** [umijs/umi#3445]
## What happens?
正常运行一个umi项目, 在IE11上跑, 报错了以下错误: 
已经配置支持, 仍然无效
```
targets: {
    ie: 11,
  },
```

SCRIPT1005: Expected '('
umi.js (157724,37)
```
function _init() {
  _init = _asyncToGenerator(function* (url, opts = {}) {
    const onMessage = opts.onMessage,
          onError = opts.onError;
    return new Promise((resolve, reject) => {
      function handler(e) {
        const _JSON$parse = JSON.parse(e.data),
              type = _JSON$parse.type,
              payload = _JSON$parse.payload;
```

## How To Reproduce
**Steps to reproduce the behavior:**
1.  yarn create umi  ...> ant pro  ...> npm start

**Expected behavior**
在IE11上正常显示

## Context

- **Umi Version**: last version
- **Node Version**: 10
- **Platform**:  IE 11.418

**Comment by xoptimal** [comment]
@sorrycc  help

**Comment by dep-darkLonely** [comment]
遇见了同样的问题
刚开始使用的umijs版本为2.10.2，参考 #3451 、 #3471  发现在2.10.5版本中进行了fix，版本升级之后，该问题消失。
