### ISSUE TITLE
[bug] umi-ui bug using react-document-title

### ISSUE THREAD

**Issue by tsuijie** [umijs/umi#3446]
## Background

Umi-ui is automatically enabled that requires opening port 3000 or so, which may not be posibble under certain conditions. When xhr response error, page crashes.

## Proposal

Provide option to disable umi-ui, or fix posibble crashes caused by network error.

## Additional context

```
Uncaught Invariant Violation: React.Children.only expected to receive a single React element child.
The above error occurred in the <DocumentTitle> component
ui socket init CloseEvent {type: "close", bubbles: false, cancelable: false, timeStamp: 1571127775342, wasClean: false, …}
```

**Comment by ycjcl868** [comment]
`UMI_UI=none umi dev`

**Comment by ycjcl868** [comment]
和 `DocumentTitle` 使用的时候有问题，这个 @sorrycc cc

**Comment by sorrycc** [comment]
这个问题我修复下，可以先临时在 <DocumentTitle /> 外套一个 `<></>`，变成 `<><DocumentTitle /></>`。

**Comment by zhuoshaohere** [comment]
同样的问题，目前好像没有修复的
