### ISSUE TITLE
如何动态加载国际化信息

### ISSUE THREAD

**Issue by gaorubin1990** [umijs/umi#3448]
## What happens?
希望国际化的翻译信息即local中的js文件信息是通过后端api获取然后动态加载的。在之前的版本中可以动态的修改IntlProvider组件中的message，但是在最新的pro工程中，IntlProvider组件存在于临时文件夹.umi中，请问改如何实现需求？

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
无

**Expected behavior**
通过api获取国际化数据动态修改local信息

## Context

- **Umi Version**:2.10.1
- **Node Version**:
- **Platform**:

**Comment by gaorubin1990** [comment]
@sorrycc 大神能提供下解决思路吗？非常感谢

**Comment by xiaohuoni** [comment]
感觉可以通过 `runtime` 配置那边去实现。

**Comment by gaorubin1990** [comment]
> 感觉可以通过 `runtime` 配置那边去实现。

我想要通过runtime中的rootContainer包裹国际化组件。但是担心和系统自带的冲突，最新版本的remove国际化脚本是报错的

**Comment by gaorubin1990** [comment]
@sorrycc @xiaohuoni 
我在rootContainer中用一个组件AAA去包裹root根组件，但是在这个AAA中组件中无法使用connect，会报错，下图。感觉这个dva是在root根组件中封装的。这种如何处理呢？或者有其他动态获取国际化的解决方案吗？不要石沉大海啊，求助！！

Could not find "store" in either the context or props of "Connect(LocalContainer)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(LocalContainer)".

**Comment by WangJM001** [comment]
我重写了umi-local的插件实现的，但是只是编译时一次性获取了

**Comment by gaorubin1990** [comment]
> 我重写了umi-local的插件实现的，但是只是编译时一次性获取了

那样感觉也不是很符合，期望的效果是刷新页面就可以重新通过接口获取国际化信息。不需要重新编译的。之前的版本在global里添加了这个接口方法。

**Comment by WangJM001** [comment]
global能不能发出来看看，我们项目还是老版本的，也想动态获取

**Comment by gaorubin1990** [comment]
> global能不能发出来看看，我们项目还是老版本的，也想动态获取

global里就是一个effects方法啊，我们有个语言维护管理页面，每种语言具体维护国际化信息（即locales文件夹的zh-CN.js的信息）然后通过api去获取国际化zh-CN信息，在路由的地方<Route>包裹<LocaleProvider>和<IntlProvider>，locale属性值通过global的state动态传递进去。

**Comment by gaorubin1990** [comment]
> global能不能发出来看看，我们项目还是老版本的，也想动态获取

路由的地方Route包裹LocaleProvider和IntlProvider

**Comment by WangJM001** [comment]
谢谢，坐等大佬解决方案

**Comment by gebilaoman** [comment]
同求官方解决方案

**Comment by WangJM001** [comment]
目前项目中通过修改插件在LocaleWrapper中请求一次后端接口解决了，重写了umi-plugin-locale插件

**Comment by gebilaoman** [comment]
官方还么提供统一的解决方案就给close掉了吗

**Comment by gaorubin1990** [comment]
为什么不解决就关闭？

**Comment by laosandegudai** [comment]
> > 我重写了umi-local的插件实现的，但是只是编译时一次性获取了
> 
> 那样感觉也不是很符合，期望的效果是刷新页面就可以重新通过接口获取国际化信息。不需要重新编译的。之前的版本在global里添加了这个接口方法。

之前我也是在global里面加载接口返回的语言，新版本不知道怎么搞了。

**Comment by taomengyue** [comment]
亲，最后这个怎么解决的？

**Comment by twinkle77** [comment]
晕，感觉这个需求很常规呀...

**Comment by xiexingen** [comment]
这个能 reopen 吗

**Comment by lhl-cpu** [comment]
咋解决呢最后是？

**Comment by lujun5068** [comment]
umi4中提供了 addLocale 的方法可以追加国际化的 message，接口获取到国际化信息后调用即可。
具体源码如下：
![image](https://github.com/umijs/umi/assets/38418599/d0b27233-3521-40e5-ad47-2b87cdf6fd87)

**Comment by lhl-cpu** [comment]
> umi4中提供了 addLocale 的方法可以追加国际化的 message，接口获取到国际化信息后调用即可。 具体源码如下： ![image](https://user-images.githubusercontent.com/38418599/280191496-d0b27233-3521-40e5-ad47-2b87cdf6fd87.png)

最后用的这个方法实现的，已解决
