### ISSUE TITLE
路由不自动生成,使用配置路由还是是识别路由

### ISSUE THREAD

**Issue by luoandy** [umijs/umi#346]
`
import React, { Component } from "react";
import { Toast } from 'antd-mobile';
import NoData from './../../components/NoData/NoData'
import styles from './page.less'
export default class Empty extends Component {
    constructor(props) {
        super(props);
        this.state = {

        };
    }
    componentDidMount() {

    }
    render() {
        return (
            <div className={styles.emptyWrapper}>
                <NoData text="ssss"/>
            </div>
        )
    }
}
`
![image](https://user-images.githubusercontent.com/20121275/38909039-76b13fbc-42f5-11e8-8df2-7f2a74975fa4.png)

**Comment by sorrycc** [comment]
详细点? 没明白问题在哪。
