### ISSUE TITLE
支持.postcss文件格式的处理

### ISSUE THREAD

**Issue by nelhu** [umijs/umi#3462]
# 支持.postcss文件格式，并使用 css-loader,postcss-loader,less-loader处理
## Background
当前umi支持以下几种css文件格式的解析，但不包括.postcss格式，希望提供支持
![image](https://user-images.githubusercontent.com/24311105/67003857-8d5e0d00-f111-11e9-8e97-d272590c0dd1.png)

## Proposal

希望是
```js
const CSS_EXTNAMES = ['.css', '.less', '.scss', '.sass', '.postcss']
```
希望我表达的清楚

**Comment by sorrycc** [comment]
第一次看到 `.postcss`，这是来自哪里？为啥用这个？

**Comment by nelhu** [comment]
> 第一次看到 `.postcss`，这是来自哪里？为啥用这个？

可以为.less，但更倾向于.postcss，在社区已有插件支持该后缀，表示使用postcss-loader处理的样式文件名。
![image](https://user-images.githubusercontent.com/24311105/67060979-6810e380-f191-11e9-8062-c9ae9379f3f1.png)

你的建议呢？

**Comment by sorrycc** [comment]
我觉得用 less 比较好，用 .postcss 可能不能正常渲染 less 的语法，而且编辑器支持也不全。

**Comment by nelhu** [comment]
> 我觉得用 less 比较好，用 .postcss 可能不能正常渲染 less 的语法，而且编辑器支持也不全。

有道理，目前用less了
