### ISSUE TITLE
在ie浏览器上 一直报错SCRIPT1002

### ISSUE THREAD

**Issue by feilongOnMoudu** [umijs/umi#3474]
## What happens?
在ie浏览器上 一直报错
SCRIPT1002  如图
![318a8a0ceb938bbb469c6e33b8a396c7](https://user-images.githubusercontent.com/16435428/67179722-cf38cd00-f409-11e9-8ef7-2f281843f457.jpg)
![0d55c0aed31485f5047efca2d790917c](https://user-images.githubusercontent.com/16435428/67179726-d19b2700-f409-11e9-9736-8e963b26fed7.jpg)

换了多种写法 没有成功

已配置：targets: { ie: 9}, 其他浏览器都没问题

- **Umi Version**: 2.8.16
- **Node Version**:10.12.0
- **Platform**:mac

**Comment by sorrycc** [comment]
出错代码来自哪里？你的项目吗？

**Comment by sorrycc** [comment]
给复现步骤。

**Comment by feilongOnMoudu** [comment]
@sorrycc  是我自己的项目代码  入口页面都不能打开的 ，也开启了不压缩打包 但是不压缩发到外网报错的行数 跟我本地build的 对应的行数不一致

**Comment by feilongOnMoudu** [comment]
var _propTypes = _interopRequireDefault(__webpack_require__(/*! prop-types */ "./node_modules/prop-types/index.js"));

var _react = _interopRequireDefault(__webpack_require__(/*! react */ "./node_modules/react/index.js"));

var _classnames = _interopRequireDefault(__webpack_require__(/*! classnames */ "./node_modules/classnames/index.js"));

var _utils = __webpack_require__(/*! ../../utils */ "./node_modules/video-react/lib/utils/index.js");

var propTypes = {
  player: _propTypes["default"].object,
  className: _propTypes["default"].string
};

在我本地看到的行数是var propTypes = {  到这一行
