### ISSUE TITLE
使用装饰器，报错ts1238错误

### ISSUE THREAD

**Issue by supercat55** [umijs/umi#3478]
## What happens?

使用最新版umi2.9构建项目后，不能在class顶部使用@connect装饰器方法，会报作为表达式调用时，无法解析类修饰器的签名错误

## 相关环境信息

- **Umi 2.9**：
- **Node 12.12**：
- **操作系统 mac**：

**Comment by LiuJinYang9527** [comment]
+1,请问下解决了吗 @supercat55
