### ISSUE TITLE
使用了 umi+ dva+ ts之后，不能使用百度地图了

### ISSUE THREAD

**Issue by xishanxu** [umijs/umi#3479]
使用了 umi+ dva+ ts之后，不能使用百度地图了，有什么办法能让我使用吗？

**Comment by xiaohuoni** [comment]
为什么不能？

**Comment by xishanxu** [comment]
这是我尝试的第一种方案，会报错  this.initMap() 不是一个function


-----------------------------\
这是我尝试的第二种方式  

----- 写了一个plugin.ts  插件，写入umirc中会报错

------------------ 原始邮件 ------------------
发件人: "陈小聪"<notifications@github.com>;
发送时间: 2019年10月22日(星期二) 下午2:41
收件人: "umijs/umi"<umi@noreply.github.com>;
抄送: "self"<825983767@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [umijs/umi] 使用了 umi+ dva+ ts之后，不能使用百度地图了 (#3479)




为什么不能？

**Comment by wangxingkang** [comment]
应该给最小可复现 demo 哈哈

**Comment by xishanxu** [comment]
我其实想得到一个可以使用的demo，看看你们是如何使用的




------------------ 原始邮件 ------------------
发件人: "wangxingkang"<notifications@github.com>;
发送时间: 2019年10月22日(星期二) 下午3:59
收件人: "umijs/umi"<umi@noreply.github.com>;
抄送: "self"<825983767@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [umijs/umi] 使用了 umi+ dva+ ts之后，不能使用百度地图了 (#3479)




应该给最小可复现 demo 哈哈

**Comment by wangxingkang** [comment]
没 现在 项目用的高德

**Comment by xiaohuoni** [comment]
你可以给一个跑不同的demo。还可以帮你改改。很久没看百度地图了，不想去看文档。😊

**Comment by xishanxu** [comment]
https://gitee.com/xingyongxu/medical-admin.git    Dev分支，进入系统之后，选择一个会议点击action的➕，进入管理页面，然后点击会议交通管理，对应代码中的Traffic页面




------------------ 原始邮件 ------------------
发件人: "陈小聪"<notifications@github.com>;
发送时间: 2019年10月22日(星期二) 下午5:00
收件人: "umijs/umi"<umi@noreply.github.com>;
抄送: "self"<825983767@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [umijs/umi] 使用了 umi+ dva+ ts之后，不能使用百度地图了 (#3479)




你可以给一个跑不同的demo。还可以帮你改改。很久没看百度地图了，不想去看文档。😊

**Comment by xishanxu** [comment]
你告诉我高德怎么在项目中用也可以
------------------ 原始邮件 ------------------
发件人: "陈小聪"<notifications@github.com>;
发送时间: 2019年10月22日(星期二) 下午5:00
收件人: "umijs/umi"<umi@noreply.github.com>;
抄送: "self"<825983767@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [umijs/umi] 使用了 umi+ dva+ ts之后，不能使用百度地图了 (#3479)




你可以给一个跑不同的demo。还可以帮你改改。很久没看百度地图了，不想去看文档。😊
