### ISSUE TITLE
Definition for rule '@typescript-eslint/no-angle-bracket-type-assertion' was not found

### ISSUE THREAD

**Issue by theprimone** [umijs/umi#3480]
## What happens?

tsx 提示 `Definition for rule '@typescript-eslint/no-angle-bracket-type-assertion' was not found`，尝试添加 rule 无效:

```json
{
  "extends": "eslint-config-umi",
  "rules": {
    "@typescript-eslint/no-angle-bracket-type-assertion": "off"
  }
}
```

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：^2.7.0
- **Node 版本**：v10.16.3
- **操作系统**：windows 10 1903

**Comment by sorrycc** [comment]
eslint-config-umi 没有 `@typescript-eslint/no-angle-bracket-type-assertion` 这条规则，所以你不能关闭他。

**Comment by vdfor** [comment]
> eslint-config-umi 没有 `@typescript-eslint/no-angle-bracket-type-assertion` 这条规则，所以你不能关闭他。

那如何与airbnb搭配呢？以下配置仍然存在 not found 提示

`{
  "env": {
    "browser": true,
    "commonjs": true,
    "es6": true,
    "node": true,
    "jest": true
  },
  "extends": [
    "eslint:recommended",
    "react",
    "eslint-config-umi",
    "plugin:@typescript-eslint/recommended",
    "plugin:react/recommended",
    "airbnb"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "useJSXTextNode": true,
    "extraFileExtensions": [
      "tsx"
    ]
  },
  "plugins": [
    "@typescript-eslint",
    "react",
    "react-hooks"
  ]
}`

**Comment by vdfor** [comment]
> > eslint-config-umi 没有 `@typescript-eslint/no-angle-bracket-type-assertion` 这条规则，所以你不能关闭他。
> 
> 那如何与airbnb搭配呢？以下配置仍然存在 not found 提示
> 
> ```json
> {
>   "extends": [
>     "eslint:recommended",
>     "react",
>     "eslint-config-umi",
>     "plugin:@typescript-eslint/recommended",
>     "plugin:react/recommended",
>     "airbnb"
>   ],
>   "parser": "@typescript-eslint/parser",
>   "parserOptions": {
>     "ecmaFeatures": {
>       "jsx": true
>     },
>     "useJSXTextNode": true,
>     "extraFileExtensions": [
>       "tsx"
>     ]
>   },
>   "plugins": [
>     "@typescript-eslint",
>     "react",
>     "react-hooks"
>   ]
> }
> ```

升级eslint对应版本即可
