### ISSUE TITLE
ssr有没有详细文档.

### ISSUE THREAD

**Issue by 569202812** [umijs/umi#3481]

**Comment by 569202812** [comment]
已有umi项目怎么扩展ssr,怎么嵌入的egg里面

**Comment by 569202812** [comment]
@ycjcl868 我用这个有几个困惑,1.getInitialProps的获取数据我怎么在umi dev的时候查看,2.umi项目怎么扩展ssr我只想把数据预渲染出来

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/pull/2963

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/2937

**Comment by liukunr** [comment]
umi dev能查看gitinitialprops的数据了吗，怎么弄得 @xiaohuoni
