### ISSUE TITLE
在umi+ dva中，如何给一个元素两个不同的类名呢？

### ISSUE THREAD

**Issue by xishanxu** [umijs/umi#3482]
在常规react项目中 我在一个div中添加两个类名，直接className='a b'就加上了，
但是在umi 项目中， 它引入less的方式变成了 import style from 'xxx.less'
 然后我给一个元素添加两个类名，会报错， 我是这样写的   
 className={style.a,style.b} , 也尝试过 className={[style.a,style.b]}  但是会报错，className接受的值是一个string
## 相关环境信息

- **Umi 版本**： 最新版
- **Node 版本**：10.几稳定版
- **操作系统**： Mac OS

**Comment by alexsunxl** [comment]
```
className={[style.a,style.b].join(' ')}
```

**Comment by xishanxu** [comment]
牛逼&nbsp; 谢谢



---原始邮件---
发件人: "alex 孙欣乐"<notifications@github.com&gt;
发送时间: 2019年10月22日(星期二) 下午3:10
收件人: "umijs/umi"<umi@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"xishanxu"<825983767@qq.com&gt;;
主题: Re: [umijs/umi] 在umi+ dva中，如何给一个元素两个不同的类名呢？ (#3482)


className={[style.a,style.b].join(' ')}

**Comment by wangxingkang** [comment]
classnames 这个库了解一下
