### ISSUE TITLE
js文件更新之后页面不更新，强制刷新，页面的内容也不会发生任何变化

### ISSUE THREAD

**Issue by xuanxuan321** [umijs/umi#3485]
## What happens?
umi 升级到2.10后，发现更改文件内容，umi不会重新编译文件，后面发现在config.js的umi-plugin-react配置里面加一个locale:{}上,述问题就解决了，每次保存文件的时候，umi都会重新打包。但是又有了一个新的问题，那就是虽然umi能重新打包，但是页面的内容不会发生任何变化，即使强制刷新也不行。请问，umi的打包机制和umi-plugin-react中的locale配置是有什么关联吗

ps：如果是约定式路由的话是没有任何问题的，问题主要就是出在配置式路由的情况下

## Mini Showcase Repository(REQUIRED)
不好意思，暂时无法剥离业务逻辑抽象出一个demo来

## Context

- **Umi Version**:2.10.6
- **Node Version**:v12.12.0
- **Platform**:chrome 版本 77.0.3865.120  macos 10.15

**Comment by sorrycc** [comment]
没有复现步骤，我不能帮你解决问题。DEMO 不一定要有业务代码，只需要能复现你的问题。

**Comment by liumin1128** [comment]
这个问题我也遇到，莫名其妙的就不可以热更新了
