### ISSUE TITLE
随着项目不断增大，引入ts后，打包很慢

### ISSUE THREAD

**Issue by YitaoO** [umijs/umi#3486]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by sorrycc** [comment]
据说基于 babel 做 ts 编译会快，但我还没有验证过数据，有时间我会加上这种 ts 编译模式。 cc @chenshuai2144

**Comment by iShawnWang** [comment]
emmmmm, 请问按需编译 在计划中吗 ~ @sorrycc

**Comment by iShawnWang** [comment]
有一个非常粗糙简单的想法 : umirc.ts 下面的 `routes`, 加一些配置, 不要所有页面都编译就好了....
