### ISSUE TITLE
link 组件相同 pathname 不刷新问题

### ISSUE THREAD

**Issue by smithyj** [umijs/umi#349]
发现link组件如果地址栏中的pathname 与 to={path} 的path 相同，则 umi.js 好像会预先请求一次 但是这样就会造成304请求

**Comment by sorrycc** [comment]
为啥要请求自己？这应该是 react-router@4 的逻辑。

**Comment by smithyj** [comment]
比如我在左侧菜单第一次点击的时候页面是可以被reden的，但是第二次点击就不会有render了，目前想了个hack就是加个t参数

**Comment by xiaohuoni** [comment]
我也有个类似的问题，比如说在login页面，再次push到login，会报错误。能不能不要提示这个错误。

**Comment by sorrycc** [comment]
> 比如我在左侧菜单第一次点击的时候页面是可以被render的，但是第二次点击就不会有render了，目前想了个hack就是加个t参数

@smithyj 已经 render 了，为啥还要有 render ？没理解。

> 我也有个类似的问题，比如说在login页面，再次push到login，会报错误。能不能不要提示这个错误。

@xiaohuoni 会报什么错误？

**Comment by smithyj** [comment]
比如我在 /blog/article 这个列表页面下（进入页面会去 fetch 一次列表数据），我再次点击 Link 到 /blog/article 下，我希望再次 fetch 列表数据，但是结果并没有 fetch

**Comment by sorrycc** [comment]
url 没有变化就不会触发 history.listen，不会 fetch 是正常的。

**Comment by sorrycc** [comment]
304 请求测了下只在 dev 模式下有，build 后不会有，先忽略吧。

**Comment by xiaohuoni** [comment]
@sorrycc  Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack

**Comment by qq1170623178** [comment]
![image](https://user-images.githubusercontent.com/43264733/63160383-345df400-c050-11e9-87b4-b6aa602eae31.png)
救救孩子吧
