### ISSUE TITLE
把Mock数据打包

### ISSUE THREAD

**Issue by xclw2000** [umijs/umi#3490]
由于服务端还没有开发完，想临时发布一个演示系统，使用代码中的Mock的数据来展示，有什么办法？

**Comment by xiaohuoni** [comment]
现在暂时没有提供将 `mock` 数据打包的能力，你可以自己搭建一个 `mock` 服务器。
如果不太懂 node 服务的话，那你可以 fork 这个项目 [antd-pro-server](https://github.com/xiaohuoni/antd-pro-server) ，把 [mock](https://github.com/xiaohuoni/antd-pro-server/tree/master/mock) 替换成你自己的，直接运行就可以了
