### ISSUE TITLE
ts项目umi打包问题

### ISSUE THREAD

**Issue by wakeup153** [umijs/umi#3494]
运行build命令，无法打包成静态，进度一直卡在95%(卡了一夜也无法打包成功)，重新安装依赖也无法解决问题
![QQ图片20191023082147](https://user-images.githubusercontent.com/32958565/67345715-98c89280-f56e-11e9-925d-6c7eac7534eb.png)

## 相关环境信息
- **Umi 版本**：2.10.7
- **Node 版本**：10.13.0
- **操作系统**：win10

**Comment by xiaohuoni** [comment]
是不是这个问题
## antd-pro 项目热更新慢并且是在 95% (emitting) 时卡住怎么办？

编辑 `config/config.js`，搜索 chainWebpack 并注释掉。

**Comment by wakeup153** [comment]
不是，项目是用create-umi创建的,不过已经解决了，我把react版本降了就好了
