### ISSUE TITLE
安装或者更新依赖必须重启项目才能用！

### ISSUE THREAD

**Issue by qq645381995** [umijs/umi#3496]
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库
刚创建项目，`yarn start` 启动后安装一个包，刷新页面没有用。

## 相关环境信息

- **Umi 版本**：刚更新最新
- **Node 版本**：v10.16.0
- **操作系统**：mac

**Comment by xiaohuoni** [comment]
这有什么问题？

**Comment by qq645381995** [comment]
> 这有什么问题？

不能不重启 直接刷新就能用刚装的包吗？

**Comment by qq645381995** [comment]
cra 装完包，也是立刻能用的，不需要重启项目

**Comment by qq645381995** [comment]
@ycjcl868

**Comment by xiaohuoni** [comment]
我不觉得是个问题

**Comment by qq645381995** [comment]
真的大问题，你 `yarn upgradge xxx` 包了，但是刷新浏览器看不到更新的状态，还必须重启才能看到。

**Comment by xiaohuoni** [comment]
是啊，那就重新启动不就好了吗？依赖都变更了，你不关掉服务重新开一下，不会觉得，用的是缓存之类的嘛？

**Comment by qq645381995** [comment]
其他都没有这样的，都是可以动态更新的，例如：https://github.com/facebook/create-react-app

**Comment by sorrycc** [comment]
得看是啥依赖。node 端的依赖更新了必须重启有效，否则逻辑上也说不通；浏览器端的依赖更新了理论上可以做到热更新，但我们目前没有监听 node_modules 的变更（监听了性能会变差），所以也需要重启。

**Comment by qq645381995** [comment]
> 得看是啥依赖。node 端的依赖更新了必须重启有效，否则逻辑上也说不通；浏览器端的依赖更新了理论上可以做到热更新，但我们目前没有监听 node_modules 的变更（监听了性能会变差），所以也需要重启。

嗯，我说的是`dependencies`依赖，如果是为了性能考虑，期望还是做个开关，因为合并分支的这种场景没关注到有依赖变更，本地还是用的旧版本包，看着没问题，但有隐患。
