### ISSUE TITLE
umi dev: 提示umi/link, umi/navlink...不存在

### ISSUE THREAD

**Issue by stack-wuh** [umijs/umi#3497]
These dependencies were not found:

* umi/dynamic in dll umi
* umi/link in dll umi
* umi/navlink in dll umi
* umi/redirect in dll umi
* umi/router in dll umi
* umi/withRouter in dll umi

To install them, you can run: npm install --save umi/dynamic umi/link umi/navlink umi/redirect umi/router umi/withRouter

 ERROR CODE  ERR_WEBPACK_DLL_MODULE_NOT_FOUND

 DETAILS

## 错误原因

构建 dll 文件时出错了，由于 dependencies 下的依赖会全部被打到 dll 里，所以报错可能有以下原因：

    1. dependencies 里的某些依赖没有 main 文件
    2. 应该放在 devDependencies 里的 node 相关的依赖却写在了 dependencies

## 解决方案

让不该打到 dll 的不被打到 dll 里，有几个解决方案：

    1. 把 node 相关依赖放到 devDependencies 里
    2. 把出错的依赖配置到 dll 的 exclude 里

比如：

    dll: {
      exclude: ['foo']
    }

![image](https://user-images.githubusercontent.com/34117238/67363837-c6c6ca80-f5a0-11e9-8053-fa055b033606.png)

## Context

- **Umi Version**:2.2.6
- **Node Version**:10.16.3
- **Platform**: window10 (家庭版)

**Comment by sorrycc** [comment]
需要给可复现仓库。
