### ISSUE TITLE
umi build error when  `generateCssModulesTypings` set to true.

### ISSUE THREAD

**Issue by EliazTray** [umijs/umi#3503]
## What happens?
Compile error.
编译错误
![image](https://user-images.githubusercontent.com/16015431/67463130-79675d80-f673-11e9-9768-8bc93b848721.png)

## Mini Showcase Repository(REQUIRED)
[https://github.com/EliazTray/umi-bug-generateCssModulesTypings](https://github.com/EliazTray/umi-bug-generateCssModulesTypings)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1. clone the project and then install dependencies
2. run `npm start`
3. [https://github.com/EliazTray/umi-bug-generateCssModulesTypings/blob/master/.umirc.ts#L35](https://github.com/EliazTray/umi-bug-generateCssModulesTypings/blob/master/.umirc.ts#L35), 放开这一行的注释，自动生成 `.d.ts` 文件

**Expected behavior**
编译通过

**Detail Description**

**放开 `.umirc` 中 routes 的注释，此时编译通过**
目前看起来 **generateCssModulesTypings** 似乎只支持了**配置式路由**的场景.

## Context

- **Umi Version**: 2.10.7
- **Node Version**: v10.14.1
- **Platform**: mac os

**Comment by EliazTray** [comment]
查看了下 `.umi` 文件夹下的 `router.js`，发现会将 `.d.ts` 文件当作 routeComponent 来处理。

**Comment by HazySoda** [comment]
@EliazTray 确实是这样，在 `umi-plugin-react` 的 `routes.exclude` 配置项中加入 `/.d.ts/` 正则后问题解决了。
