### ISSUE TITLE
如何将单页实现为tabs切换的形式

### ISSUE THREAD

**Issue by furylee** [umijs/umi#3507]
## What happens?
如何将单页实现为tabs切换的形式,使用umi是否可行,可否有例子可以参考或者实现方式
参考地址 [http://demo26.crmeb.net/admin/index/index.html](http://demo26.crmeb.net/admin/index/index.html)
账号:demo
密码:crmeb.com

![企业微信截图_15719971244513.png](https://i.loli.net/2019/10/25/v6XuWYsK4b1z9Sq.png)

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：1
- **Node 版本**：1
- **操作系统**：1

**Comment by sorrycc** [comment]
这个和 umi 无关，你可以在 umi 里使用任意的 ui 库。

**Comment by furylee** [comment]
> 这个和 umi 无关，你可以在 umi 里使用任意的 ui 库。

不是UI库的问题,是说,layout下的一个children变成多个children,然后children可以像页面那样切换,可以看下我给的那个地址,想知道使用umi能否那样实现

**Comment by furylee** [comment]
> 这个和 umi 无关，你可以在 umi 里使用任意的 ui 库。

http://demo26.crmeb.net/admin/index/index.html

**Comment by furylee** [comment]
有没有人给个实现思路啊

**Comment by gaorubin1990** [comment]
我是在{children}的外层添加了tab组件。但是没有用状态保持的插件。因为dva本身model中的state不会随组件ummount而清空。也能实现类似的效果。

**Comment by Aaron52077** [comment]
https://wuli-admin.gitee.io/react-antd-template/#/dashboard 最近实现的页签带缓存iframe功能

**Comment by eternallycyf** [comment]
- 用过别人的umi插件 但是一更新又崩了 还是自己有个能改的比较好
- 最小复现 无其他依赖
- https://github.com/eternallycyf/umi4-tab 
- 
<img width="688" alt="tag" src="https://user-images.githubusercontent.com/63464198/212682655-4d422cc4-ef8b-4d7c-89d2-c77d3980058d.png">

```json
"dependencies":{
    "classnames": "^2.2.6",
    "js-cookie": "^3.0.1",
    "lodash": "^4.17.19",
    "redux-persist": "^6.0.0",
}
  "devDependencies": {
    "@types/js-cookie": "^3.0.2",
    "cross-env": "^7.0.3",
    "mockjs": "^1.1.0",
    "@types/lodash": "^4.14.191",
  }
```

**Comment by eternallycyf** [comment]
- https://github.com/eternallycyf/umi4-tab
- 用过别的插件 umi一更新就会有问题 建议维护一个自己的版本 
- 基于umi4封了一个  抽离了其他多余代码 
<img width="929" alt="截屏2023-01-17 10 43 03" src="https://user-images.githubusercontent.com/63464198/212798327-5eb567f2-eb95-4727-a59f-0e239907b760.png">
