### ISSUE TITLE
请问如何做到真正按需加载？

### ISSUE THREAD

**Issue by ljshj** [umijs/umi#3513]
通过配置config.optimization.splitChunks已经将node-modules中的包分片打包，第一次渲染速度得到了很大提升。
但是看chrome的资源下载，第一次访问chrome将所有分片后的js都预加载了。

如何做到第一次访问，只加载当前页面需要的js

**Comment by llfylwg** [comment]
同问，分片的通过umi.js触发加载了

**Comment by srrrr** [comment]
我现在有个项目图片比较多，需要先加载完图片等资源再作显示，否则会在页面切换时白屏，请问怎么实现？如何进行预加载图片或预渲染？
