### ISSUE TITLE
[Feature Request] 希望能给create-umi提供一份文档

### ISSUE THREAD

**Issue by AboyL** [umijs/umi#3516]
## Background

当前创建路由这些必须通过g来创建才会自动更新，但是create-umi文档就很不足
希望能给他一份文档进行说明

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by ycjcl868** [comment]
直接使用 `umi ui`，路由创建是通过 `umi`，不通过 `create-umi`
