### ISSUE TITLE
Unable to install umi under Node.js@10.14.1

### ISSUE THREAD

**Issue by liucong1** [umijs/umi#3519]
## What happens?
When I use ` yarn global add umi` to install umi , an error about Node.js version was reported.

How can I deal with it ?

```
$ yarn global add umi
yarn global v1.12.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.14.1"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

## Context

- **Umi Version @ Latest edition**:
- **Node.js@10.14.1**:
- **MacBook Pro**:

**Comment by xiaohuoni** [comment]
试了这个版本可以安装。

**Comment by sorrycc** [comment]
试试 `yarn config set ignore-engines true` 再安装。
