### ISSUE TITLE
如何动态自定义菜单配置？

### ISSUE THREAD

**Issue by wangyinwei1** [umijs/umi#3523]
需求：做到菜单自定义增删改，这样是不是就不能按照umi的约定式路由了？

**Comment by wangyinwei1** [comment]
> 需求：做到菜单自定义增删改，这样是不是就不能按照umi的约定式路由了？

补充：系统管理员可以操纵角色下的菜单我就自定义增删改的需求。

**Comment by gaorubin1990** [comment]
约定式路由只是定义路由信息，菜单的显示可以动态获取的，官方文档上有方法。

**Comment by sorrycc** [comment]
这个和 umi 无关，可参考 ant-design-pro 的实现。
