### ISSUE TITLE
在自定义的models文件下增加文件，.umi文件夹下面的initDva.js 文件自动导入将文件导入两次

### ISSUE THREAD

**Issue by py1597** [umijs/umi#3524]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.使用andt pro框架，自己新建的models文件下新增js文件
2.保存内容后，或者修改其他内容保存

**Expected behavior**
1.    Used by 1 module(s), i. e.
    D:\vs_pycode\ray\webapp\node_modules\babel-loader\lib\index.js??ref--7-0!D:\vs_pycode\ray\webapp\src\pages\.umi\initDva.js
2.  项目运行保存，新增的js文件增加了两次

## Context

- **Umi Version**: 2.10.7
- **Node Version**: v10.16.0
- **Platform**:win10 64

**Comment by xiaohuoni** [comment]
请提供重现demo
