### ISSUE TITLE
umi g page users 后删除user.js文件，但是.umi/route.js 中还是有/user的配置

### ISSUE THREAD

**Issue by inmWang** [umijs/umi#3525]
![image](https://user-images.githubusercontent.com/20293919/67753002-fda05300-fa6e-11e9-8926-5420648d63e4.png)
我用yarn create umi创建了一个app项目，插件选择了dva和antd。
使用umi g page user 建立了user.js的文件，后面我发现路由建错了，所以删除了user.js文件。
之后重启，发现.umi/route.js 中还存在/user的路由配置。
删除.umi文件夹也没有用。
请问umi g page user 后，应该如何删除才能够让.umi中的配置也删除？

**Comment by JasonSJ** [comment]
.umirc.js 里面的 routes跟新下呢

**Comment by inmWang** [comment]
@JasonSJ 我使用自动路由的方式，按理说删除了page，umirc的配置也应该没有了吧

**Comment by JasonSJ** [comment]
> @JasonSJ 我使用自动路由的方式，按理说删除了page，umirc的配置也应该没有了吧

你打开看看就知道了

**Comment by xiaohuoni** [comment]
给重现demo吧，按你的描述，不存在这个问题，你可以关掉服务重新启动试试。
