### ISSUE TITLE
[新人问题求助] 多项目打包

### ISSUE THREAD

**Issue by LbhFront-end** [umijs/umi#3529]
## 背景
第一次发 大项目的issue,可能的不是很规范。
我的项目是分开为一个门户网站以及两个后台管理系统的。后期为了迎合需求，将代码放在一块。
![image](https://user-images.githubusercontent.com/30042334/67844292-76b7ad00-fb38-11e9-9b00-ac56781bbfd8.png)
只是在 `src/pages`里面分出来，然后在路由那里根据不同的文件前缀区分开来。如下图：
![image](https://user-images.githubusercontent.com/30042334/67844373-94851200-fb38-11e9-920b-1ed332373f3a.png)
![image](https://user-images.githubusercontent.com/30042334/67844382-9b138980-fb38-11e9-92d0-e432bde8ff75.png)
这样是完成了三个项目代码在一起的愿望。然后我发现打包出来的也是全部都在一起了。这样会导致项目的运行很慢。

## 想要解决的问题
1. 如果不改变这种形式的打包，如何让项目在服务器部署的时候运行比较快
2. 可否配置多个入口，来分开打包三个项目。开发时仍然是三个项目一起运行，但是打包的时候用不同的入口或者webpack配置来分别打包出来 admin/enterprise/client 三个文件夹出来，可以在服务器分别部署。这个该怎么去弄

**Comment by wangxingkang** [comment]
用lerna管理 是不是更合适

**Comment by LbhFront-end** [comment]
> 用lerna管理 是不是更合适

第一次听说这个工具，可以去了解一下，谢谢。如果是针对那两个问题，是否在原来工具上面进行配置的好的解决方案

**Comment by xiaohuoni** [comment]
好像只要维护两份配置就可以了吧？
```
let defaultRoutes = [
  { path: '/', redirect: '/user' },
  { path: '/user', component: './user' },
  { path: '/admin', component: './admin' },
];

if (process.env.COMPILEONDEMAND === 'user') {
  defaultRoutes = [{ path: '/', redirect: '/user' }, { path: '/user', component: './user' }];
} else if (process.env.COMPILEONDEMAND === 'admin') {
  defaultRoutes = [{ path: '/', redirect: '/admin' }, { path: '/admin', component: './admin' }];
}

export default defaultRoutes;

```
用不同的命令启动
```
"scripts": {
    "build": "umi build",
    "dev": "umi dev",
    "userDev": "COMPILEONDEMAND=user umi dev",
    "adminDev": "COMPILEONDEMAND=admin umi dev",
    "buildUser": "COMPILEONDEMAND=user umi build",
    "buildAdmin": "COMPILEONDEMAND=admin umi build"
  },
```
[umitest.zip](https://github.com/umijs/umi/files/3791849/umitest.zip)

**Comment by xiaohuoni** [comment]
lerna是多包管理吧，这里不发包，不太适用

**Comment by LbhFront-end** [comment]
> 好像只要维护两份配置就可以了吧？
> 
> ```
> let defaultRoutes = [
>   { path: '/', redirect: '/user' },
>   { path: '/user', component: './user' },
>   { path: '/admin', component: './admin' },
> ];
> 
> if (process.env.COMPILEONDEMAND === 'user') {
>   defaultRoutes = [{ path: '/', redirect: '/user' }, { path: '/user', component: './user' }];
> } else if (process.env.COMPILEONDEMAND === 'admin') {
>   defaultRoutes = [{ path: '/', redirect: '/admin' }, { path: '/admin', component: './admin' }];
> }
> 
> export default defaultRoutes;
> ```
> 
> 用不同的命令启动
> 
> ```
> "scripts": {
>     "build": "umi build",
>     "dev": "umi dev",
>     "userDev": "COMPILEONDEMAND=user umi dev",
>     "adminDev": "COMPILEONDEMAND=admin umi dev",
>     "buildUser": "COMPILEONDEMAND=user umi build",
>     "buildAdmin": "COMPILEONDEMAND=admin umi build"
>   },
> ```
> 
> [umitest.zip](https://github.com/umijs/umi/files/3791849/umitest.zip)

一语点醒，谢谢大佬！
