### ISSUE TITLE
How to change webpack UglifyJS options?

### ISSUE THREAD

**Issue by aletus** [umijs/umi#353]
I want to drop console logs for production build.  But there is no way to set the webpack UglifyJS options below.

```
plugins: [
    new Webpack.optimize.UglifyJsPlugin({
      compress: {
        drop_console: true,
      }
    }
]

```
UglifiedJS options seemed to be hardcode here without any mechansim to add or override:

`https://github.com/umijs/umi/blob/master/packages/af-webpack/src/defaultConfigs/uglifyJS.js`

**Comment by sorrycc** [comment]
You can try to remove console with [babel-plugin-transform-remove-console](https://www.npmjs.com/package/babel-plugin-transform-remove-console).

**Comment by aletus** [comment]
Thanks. Do I put it in .webpack.rc.js as follow?

```
"env": {
  "production": {
    "extraBabelPlugins": ["transform-remove-console"]
  }
}
```
