### ISSUE TITLE
umi build时报找不到依赖错误

### ISSUE THREAD

**Issue by lilifan** [umijs/umi#3530]
## What happens?
新项目引用monaco-languageclient依赖并使用后，umi build时报错如下：
```
This dependency was not found:
* vscode in ./node_modules/vscode-languageclient/lib/client.js, ./node_modules/vscode-languageclient/lib/typeDefinition.js and 12 others

```
## Mini Showcase Repository(REQUIRED)

https://github.com/lilifan/demo_umi

## How To Reproduce
**Steps to reproduce the behavior:**
1. 新建umi项目，tyarn create umi
2. 不启用typescript，启用antd、dva、dll、code splitting
3. 在 package.json  dependencies里 添加 "monaco-languageclient": "^0.10.2"依赖
4. 在src目录下 添加util.js文件，内容为
```
import {
  MonacoLanguageClient, CloseAction, ErrorAction,
  createConnection
} from 'monaco-languageclient';

export function createLanguageClient(connection) {
  return new MonacoLanguageClient({
    name: "Python Language Client",
    clientOptions: {
      // use a language id as a document selector
      documentSelector: ['python'],
      // disable the default error handler
      errorHandler: {
        error: () => ErrorAction.Continue,
        closed: () => CloseAction.DoNotRestart
      }
    },
    // create a language client connection from the JSON RPC connection on demand
    connectionProvider: {
      get: (errorHandler, closeHandler) => {
        return Promise.resolve(
          createConnection(connection, errorHandler, closeHandler))
      }
    }
  });
}
```
5. 在src/pages/index.js 添加以下2行代码
```
import {createLanguageClient} from '@/util'
createLanguageClient()
```
6. tyarn install 安装依赖
7. umi build 构建，报上述错误

**Expected behavior**
1. 构建不报错

## Context

- **Umi Version**: 2.10.7
- **Node Version**:  10.15.3
- **Platform**:mac  10.13.6 (17G8030)
- ** tyarn version：1.17.3

**Comment by lilifan** [comment]
webpack构建不报错的例子在这里：https://github.com/TypeFox/monaco-languageclient/tree/master/example
其实我就是想把这个例子整合进我的umi项目

**Comment by lilifan** [comment]
抱歉，我自己又仔细对比了2个构建配置，发现是自己少了个alias配置，加上就对了。
```
 alias: {
    'vscode': require.resolve('monaco-languageclient/lib/vscode-compatibility')
  }
```
自己一个人排查没有头绪，感觉把问题按条理描述出来，一下子就思路清晰了，惭愧....

**Comment by poyiding** [comment]
> 抱歉，我自己又仔细对比了2个构建配置，发现是自己少了个alias配置，加上就对了。
> 
> ```
>  alias: {
>     'vscode': require.resolve('monaco-languageclient/lib/vscode-compatibility')
>   }
> ```
> 
> 自己一个人排查没有头绪，感觉把问题按条理描述出来，一下子就思路清晰了，惭愧....

昨晚看了一下也没发现，刚查到[解决](https://stackoverflow.com/a/56644955/10483173)，和你的一样。

**Comment by lilifan** [comment]
> > 抱歉，我自己又仔细对比了2个构建配置，发现是自己少了个alias配置，加上就对了。
> > ```
> >  alias: {
> >     'vscode': require.resolve('monaco-languageclient/lib/vscode-compatibility')
> >   }
> > ```
> > 
> > 
> > 自己一个人排查没有头绪，感觉把问题按条理描述出来，一下子就思路清晰了，惭愧....
> 
> 昨晚看了一下也没发现，刚查到[解决](https://stackoverflow.com/a/56644955/10483173)，和你的一样。

厉害，我搜了2天没搜到这条.....
