### ISSUE TITLE
[Feature Request] Option to change Umi UI port

### ISSUE THREAD

**Issue by khalibloo** [umijs/umi#3534]
## Background

Default port for Umi UI is 3000, which happens to be what most of my local projects use. And when `PORT=3000` in an umi project, this conflicts with umi ui. Running `umi dev` starts umi ui instead of my project.

## Proposal

There should be an option to change the default umi ui port. And if it conflicts with a project's port, a new port should automatically be assigned to umi ui.

Edit:
It looks like there's an env variable for `UMI_UI_PORT` but changing it has no effect. Umi ui still runs on 3000 even when `UMI_UI_PORT=5000`.

**Comment by GongT** [comment]
然而正确的环境变量是 UMI_PORT
