### ISSUE TITLE
请问如何单独打包组件

### ISSUE THREAD

**Issue by asyura** [umijs/umi#3535]
项目里用到bizcharts，但只有一个页面用到，现在配置了dynamicImport，打包后所有组件包括bizcharts都打到vendors里，vendors就比较大。所以有没有方法把bizcharts单独打一个包，然后只在那一个用到的页面使用呢，请教有什么解决方法。

**Comment by sorrycc** [comment]
让 bizcharts 按需打包，用 `import()` 语法，比如 `import('bizchart').then(BizChart => {})`。

**Comment by aixfox** [comment]
import() 也是不行的，这样也会匹配默认的 cacheGroup，把 bizcharts 打包到 async vendors 里去。
umi 给的配置是通用的，想自定义 chunk 拆分规则的话，得自己去改 webpack SplitChunksPlugin 的参数。

**Comment by asyura** [comment]
谢谢回复，怎么按需打包呢，已经配置了dynamicImport，import('bizchart').then(BizChart => {})也没试成功。。。

**Comment by aixfox** [comment]
简单的话可以这样：
```javascript
// 使用 import('bizcharts')

// .umirc.js 或 config/config.js
  chainWebpack(config, { webpack }) {
    config.optimization.splitChunks({
      cacheGroups: {
        bizcharts: {
          name: 'bizcharts',
          test: /[\\/]node_modules[\\/](@antv|bizcharts)/,
          enforce: true,
          priority: 1,
        },
      },
    });
  },
```

结合项目实际情况合理拆分，需要自己理解 SplitChunksPlugin 哦。

**Comment by asyura** [comment]
主要 import('bizcharts') 这里怎么写，是写在component里吗

**Comment by asyura** [comment]
多谢各位回答，如下配置后，打包成3个文件：vendor.async.js，recharts.async.js，umi.js，可是放到nginx里运行后，界面是空白的，console也没有出错信息，主各位大神再看看。
.umirc中相关配置内容：
`chainWebpack(config, { webpack }) {
  config.optimization.splitChunks({
    cacheGroups: {
      recharts: {
        chunks: "all",
        name: "recharts",
        test: /(recharts|recharts-scale)/,
        enforce: true,
        priority: 10,
        minSize: 0,
        minChunks: 1
      },
      vendor: {
        chunks: "all",
        name: "vendor",
        priority: 1,
        minSize: 0,
        minChunks: 1
      }
    }
  });
}`

**Comment by wzjjack** [comment]
可以尝试把priority的值调整一下

**Comment by xiaohuoni** [comment]
@asyura  是因为没有设置chunks https://v2.umijs.org/plugin/umi-plugin-react.html#chunks

**Comment by youngjuning** [comment]
@xiaohuoni 你比作者都活跃，可以加个微信，交个朋友吗？

**Comment by xiayuxiaoyan** [comment]
> @asyura 是因为没有设置chunks https://v2.umijs.org/plugin/umi-plugin-react.html#chunks

umi3没有chunks了。自己配置了cacheGroups，独立的包就没有被引入

**Comment by xiaohuoni** [comment]
@youngjuning 我头像上有微信，然后我是负责打杂的，看起来活跃是因为杂事很多。（微笑）

**Comment by travonf** [comment]
赞
