### ISSUE TITLE
含base64的样式文件编译会报错

### ISSUE THREAD

**Issue by jyjin** [umijs/umi#3536]
#### 现象：
umi版本2.8.15
重新安装umi@2.8.15后，含有base64的样式就编译报错了，

#### 业务：
这个样式却是第三方的npm包，虽然可以定制图标替换解决此问题，避免使用base64样式

#### 猜测：
umi会把background含有url的转成base64，但是却没有把已经是base64的样式排除出来

#### 错误信息
<img width="763" alt="aa" src="https://user-images.githubusercontent.com/8912548/67937323-59521400-fc08-11e9-9a80-2fc6de2d7639.png">

去除类似以下的样式，编译就能通过
```
.ril__closeButton {
  background: url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZlcnNpb249IjEuMSIgd2lkdGg9IjIwIiBoZWlnaHQ9IjIwIj48cGF0aCBkPSJtIDEsMyAxLjI1LC0xLjI1IDcuNSw3LjUgNy41LC03LjUgMS4yNSwxLjI1IC03LjUsNy41IDcuNSw3LjUgLTEuMjUsMS4yNSAtNy41LC03LjUgLTcuNSw3LjUgLTEuMjUsLTEuMjUgNy41LC03LjUgLTcuNSwtNy41IHoiIGZpbGw9IiNGRkYiLz48L3N2Zz4=')
    no-repeat center;
}
```

#### 诉求：
还是想寻求base64样式的编译方案，某个配置项可以排除这样样式转换，或者类似什么，希望有朋友们帮忙解答一下

**Comment by leftstick** [comment]
给个最小化的复现repo？
