### ISSUE TITLE
怎么自定义eslint配置

### ISSUE THREAD

**Issue by smithyj** [umijs/umi#354]
同题

**Comment by xjdata** [comment]
请问如何自定义呢?

**Comment by xiaohuoni** [comment]
有配置文件

**Comment by xiaohuoni** [comment]
这些问题可以看看官网umijs.org

**Comment by xjdata** [comment]
恩. 不好意思, 我没说清楚.
官网文档看了.... 想增加一下自定义的规则. 但是文档只有如何开启, 也搜了下 issues 发想刚好有人问, 但是这位兄弟自己关闭了, 估计是找到了办法. 所以才继续问的.

**Comment by xiaohuoni** [comment]
哦，这个要看eslint官方的了。你可以看看umi-eslint怎么实现的
