### ISSUE TITLE
如何不显示umi-ui-bubble，强迫症不想看到

### ISSUE THREAD

**Issue by qinyuhua** [umijs/umi#3540]

**Comment by sorrycc** [comment]
UMI_UI=none

**Comment by qinyuhua** [comment]
> UMI_UI=none

在哪里配置？

**Comment by sorrycc** [comment]
这是环境变量，执行 `echo 'UMI_UI=none' >> .env` 或者在启动脚本里加上。

**Comment by qinyuhua** [comment]
> 这是环境变量，执行 `echo 'UMI_UI=none' >> .env` 或者在启动脚本里加上。

已经改好了，谢谢☺
