### ISSUE TITLE
FORK_TS_CHECKER=1 umi dev 启动TS检查 有报错

### ISSUE THREAD

**Issue by wangyinwei1** [umijs/umi#3542]
![image](https://user-images.githubusercontent.com/15857725/67998716-81875480-fc94-11e9-87cd-04a5e2893781.png)
这个请问怎么解决？尝试进去安装了，但是又报另一个错误？有谁碰到吗

**Comment by fallen158** [comment]
我也遇到了这个问题，请问你是如何解决的
