### ISSUE TITLE
centos6.8 npm run build打包后页面白屏（window系统打包正常）

### ISSUE THREAD

**Issue by frankliusd** [umijs/umi#3544]
linux打包后访问错误信息如下（centos6.8版本：npm:6.4.1 nodejs:v10.15.0
react-dom.production.min.js:198 TypeError: Cannot read property 'default' of undefined
    at Icon.render (Icon.js:64)
    at Qg (react-dom.production.min.js:173)
    at Og (react-dom.production.min.js:172)
    at Tg (react-dom.production.min.js:180)
    at bi (react-dom.production.min.js:232)
    at ci (react-dom.production.min.js:233)
    at Di (react-dom.production.min.js:249)
    at Yh (react-dom.production.min.js:248)
    at Xh (react-dom.production.min.js:245)
    at qf (react-dom.production.min.js:243)
qh @ react-dom.production.min.js:198
Ch.c.callback @ react-dom.production.min.js:210
ih @ react-dom.production.min.js:193
hh @ react-dom.production.min.js:193
Vh @ react-dom.production.min.js:217
Zh @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
exports.unstable_runWithPriority @ scheduler.production.min.js:18
Fi @ react-dom.production.min.js:250
Di @ react-dom.production.min.js:249
Yh @ react-dom.production.min.js:248
Xh @ react-dom.production.min.js:245
qf @ react-dom.production.min.js:243
Ji @ react-dom.production.min.js:253
Ki @ react-dom.production.min.js:253
Pi.render @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:264
Hi @ react-dom.production.min.js:251
Si @ react-dom.production.min.js:264
render @ react-dom.production.min.js:266
oldRender @ umi.js:23
(anonymous) @ runtimePlugin.js:60
(anonymous) @ umi.js:33

**Comment by frankliusd** [comment]
![1](https://user-images.githubusercontent.com/6456680/68006375-5bbd7800-fcb3-11e9-8b16-efeb74509189.jpg)
![2](https://user-images.githubusercontent.com/6456680/68006390-67a93a00-fcb3-11e9-81bb-7216374387cc.jpg)

**Comment by frankliusd** [comment]
![11](https://user-images.githubusercontent.com/6456680/68006475-9e7f5000-fcb3-11e9-8eac-15ef43ade6f8.jpg)
![1](https://user-images.githubusercontent.com/6456680/68006509-ba82f180-fcb3-11e9-9af4-03f8b3eb7d26.jpg)

**Comment by sorrycc** [comment]
Icon.js 哪来的？这是业务代码的问题吧。

**Comment by frankliusd** [comment]
> Icon.js 哪来的？这是业务代码的问题吧。

大神好：来自 ant-design/icons-react/es/components/Icon.js 但死活定位不到业务代码

**Comment by sorrycc** [comment]
给下复现吧，我找时间排查。

**Comment by JackDan9** [comment]
![image](https://user-images.githubusercontent.com/12805846/144430637-21558a6d-7a2e-42b0-b59a-5e4db4df50e3.png)


其实也遇到了类似的问题，但是并不能稳定复现。正在看umi源码，也在看业务代码，先贴一张图记录补充一下，出现的环境是sass部署出现的问题，docker pod中运行和本地运行都没有问题。

也记录一下React版本和umi版本。

"react": "16.14.0",
"react-dom": "16.14.0",
"umi": "^3.2.27"
