### ISSUE TITLE
extraBabelIncludes能否增加通配符匹配和extraRuleIncludes

### ISSUE THREAD

**Issue by lusess123** [umijs/umi#355]
三点建议：

1.extraBabelIncludes能否增加通配符匹配，  这样更灵活一些，效率应该影响不大吧

2.extraBabelIncludes 换成extraRuleIncludes， 因为我有些转义的文件不只是走babel-loader , 有可能是tsx,less,vue文件

3.能否给这些文件增加Live Reload , 宁可首次编译多花时间 也不想放弃  HRM

**Comment by sorrycc** [comment]
#357
