### ISSUE TITLE
Using umi/router push function in dva model seems doesn't work in production build, but works in dev server

### ISSUE THREAD

**Issue by hosos** [umijs/umi#3554]
## What happens?
```js
import router from 'umi/router';
const bullShitDvaModel = {
  effects() {
    *fuck({}, { call }) {
      yield something ();
      router.push('/hongkongnoit'); // doesn't work in production build 唔撚 work 呀屌
      yield call(router.push, '/香港創科局係垃圾'); // it behaves same
    }
  }
};
```
## 相关环境信息

- **Umi 版本**：latest version
- **Node 版本**：12
- **操作系统**：Ubuntu

**Comment by hosos** [comment]
Should I use `routerRedux`  in `dva/router` package instead of `umi/router`?

**Comment by hosos** [comment]
I use `serve` to run the production server

**Comment by hosos** [comment]
@sorrycc 加個濕鳩 tag 睇吓會唔會快啲覆🤣

**Comment by sorrycc** [comment]
Hot to reproduce? Have you used `subscription`?

**Comment by sorrycc** [comment]
Just published `dva@2.6.0-beta.17`, remove the node_modules directory and reinstall to try.

**Comment by hosos** [comment]
> Just published `dva@2.6.0-beta.17`, remove the node_modules directory and reinstall to try.

Thanks, I will have a try next Monday 🙂

**Comment by hosos** [comment]
> Hot to reproduce? Have you used `subscription`?

I have used subscription `setup` for initializing the auth credentials check.

If the auth token is valid, I use router.push to redirect the user to main page in `effects` section.

**Comment by sorrycc** [comment]
It's fixed. I will reopen it if it doesn't work for you.

**Comment by zhangyoof** [comment]
> ## 怎么了？
> ```js
>  从' umi / router '导入路由器 ；
> const bullShitDvaModel = {
>    效果（）{
>      * 他妈的（{}，{通话}）{
>        产生某些东西（）;
>       路由器。推送（' / hongkongnoit '）; //确实在生产版本唔捻工作呀屌不工作产量调用（路由器，推，' /香港创科局系垃圾'）; //行为相同    
>        
>     }
>   }
> };
> ```
> 
> ## 相关环境信息
> * **Umi版本**：最新版本
> * **节点版本**：12
> * **操作系统**：Ubuntu



> ## What happens?
> ```js
> import router from 'umi/router';
> const bullShitDvaModel = {
>   effects() {
>     *fuck({}, { call }) {
>       yield something ();
>       router.push('/hongkongnoit'); // doesn't work in production build 唔撚 work 呀屌
>       yield call(router.push, '/香港創科局係垃圾'); // it behaves same
>     }
>   }
> };
> ```
> 
> ## 相关环境信息
> * **Umi 版本**：latest version
> * **Node 版本**：12
> * **操作系统**：Ubuntu

这个问题现在解决了嘛，请教一下解决方法
