### ISSUE TITLE
请问如何让某一个组件无论怎么样都要执行？

### ISSUE THREAD

**Issue by ManuRodgers** [umijs/umi#3555]
我有一个Auth 组件 它不渲染任何东西 只是根据有没有accessToken 来判断路由跳转和访问权限？

**Comment by ManuRodgers** [comment]
比如说我把那个组件<Auth />在page/index.tsx 里面渲染 怎么样可以设置那个路由不是exact？

**Comment by sorrycc** [comment]
可以配 `exact={false}`。

**Comment by ManuRodgers** [comment]
> 可以配 `exact={false}`。

请问怎么样配置？ 通过注释？
/**
 * title: Index Page
 * exact: false
 */

**Comment by ManuRodgers** [comment]
请问是不是只有用配置式的路由了？ 还是说约定式路由一样可以配置exact={false}?

**Comment by sorrycc** [comment]
@ManuRodgers 是的，约定式路由不支持。

**Comment by leftstick** [comment]
@ManuRodgers 试试我这个思路？[generator-umi](https://github.com/DFocusGroup/generator-umi)，一个包含了登录验证的脚手架，有你要的功能

**Comment by ManuRodgers** [comment]
@leftstick 谢谢 等等尝试一下
