### ISSUE TITLE
升级2.11.0后，locale部分不支持ssr

### ISSUE THREAD

**Issue by Kwei9** [umijs/umi#3556]
## What happens?
在umi-example-ssr项目上增加国际化配置，更新umi版本至2.11.0后，yarn start启动项目，访问页面后控制台出错

## How To Reproduce
**Steps to reproduce the behavior:**
1.git clone umi-example-ssr
2.修改.umirc.js文件，添加locale配置
locale: {
      enable: true,
      default: 'zh-CN',
      baseNavigator: false,
    },
3.yarn add umi-plugin-locale
4.yarn start
5.访问页面，控制台报错
 TypeError: (0 , l.addLocaleData) is not a function

## Context

- **Umi Version**:2.11.0
- **Node Version**:12.11.1
- **Platform**:Windows

**Comment by sorrycc** [comment]
试试 2.11.1，已修复。

**Comment by ycjcl868** [comment]
可参考这个 https://github.com/umijs/umi-server/pull/20/files
