### ISSUE TITLE
修改了request的参数，返回error时，dva-loading一直为true

### ISSUE THREAD

**Issue by chenyu1990** [umijs/umi#3557]
```
const request = extend({
  useCache: false,
  errorHandler,
  getResponse: true,  //   添加了这个。
});
```

**Comment by chenjsh36** [comment]
设置了 getResponse 为 true，返回结果结构从 response 变成 { response, data }， 有在 errorHandler 和处理正常响应逻辑里做对应更新么？

**Comment by chenyu1990** [comment]
> 设置了 getResponse 为 true，返回结果结构从 response 变成 { response, data }， 有在 errorHandler 和处理正常响应逻辑里做对应更新么？

errorHandler 里处理出错处理。正常响应处理了没意义。因为dva-loading一直为true，那个圈圈一直在转。
就是因为不加这个参数，不能捕获到底是否成功，不能准确判断对应的回调，所以我要加这个参数。

**Comment by chenyu1990** [comment]
> 设置了 getResponse 为 true，返回结果结构从 response 变成 { response, data }， 有在 errorHandler 和处理正常响应逻辑里做对应更新么？

thx

**Comment by chenyu1990** [comment]
> 设置了 getResponse 为 true，返回结果结构从 response 变成 { response, data }， 有在 errorHandler 和处理正常响应逻辑里做对应更新么？

上次发现问题好几天了，以至于这个issue我描述错了，接口正常的时候没有问题，接口错误的时候会一直loading
