### ISSUE TITLE
umi-plugin-react polyfills有效 targets无效

### ISSUE THREAD

**Issue by ishanyang** [umijs/umi#3558]
文档里推荐，实际ie 9运行报错
```JS
targets: {
  ie: 9
}
```

如下配置，ie 9可正常运行
```JS
[
    'umi-plugin-react',
    {
      polyfills: ['ie9'],
```

**Comment by xiaohuoni** [comment]
`umi` 和 `umi-plugin-react` 的版本是多少，我们一直使用第一种

**Comment by songyizhe** [comment]
我的好像也不可以， "umi": "^2.11.1",
    "umi-plugin-react": "^1.13.1",

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/68261464-2fbb4180-007b-11ea-96e6-c5c0d9dbf724.png)
试了下最简的场景，不能复现。

我的复现包，[sorrycc-tWiTNK.zip](https://github.com/umijs/umi/files/3812138/sorrycc-tWiTNK.zip)
