### ISSUE TITLE
app.js中访问window.g_app._history，为 null，求解啊

### ISSUE THREAD

**Issue by bibiehy** [umijs/umi#3559]
win10
"umi": "2.8.18",

在 src/app.js 中添加如下代码
![image](https://user-images.githubusercontent.com/35096473/68099457-b4805100-fefd-11e9-8528-20a779a111f5.png)
结果 _history 为
![image](https://user-images.githubusercontent.com/35096473/68099475-c661f400-fefd-11e9-8f92-d24cd34afaa5.png)

为啥在 app.js 中访问不到，pages、layouts下面的组件都可以访问到

**Comment by feibi** [comment]
打印的时候还没挂载上

**Comment by sorrycc** [comment]
时机不对，太早了，dva 在渲染时才会初始化。

**Comment by sorrycc** [comment]
要拿 history 可以试试 `g_history` 或者 `import history from '@tmp/history'`。
