### ISSUE TITLE
[plugin] this.restart is not a function

### ISSUE THREAD

**Issue by phobal** [umijs/umi#3561]
## What happens?

`this.restart is not a function`

## Mini Showcase Repository(REQUIRED)

https://github.com/phobal/plugin-qiankun-slave

## How To Reproduce

1. 在自定义插件中去改变 `umi-plugin-react:dll` 的 options

``` js
 api.changePluginOption('umi-plugin-react:dll', {
    dll: false,
  })
```

2. `changePluginOption` 方法内部就会报错

![image](https://user-images.githubusercontent.com/9244211/68102577-57d96200-ff0e-11e9-9ffa-aca0cdc90d38.png)

``` js
 changePluginOption(id, newOpts) {
    ;(0, _assert().default)(id, `id must supplied`)
    const plugin = this.plugins.filter((p) => p.id === id)[0]
    console.log('-----plugin----')
    console.log(this.plugins.map((p) => p.id))
    console.log(id)
    ;(0, _assert().default)(plugin, `plugin ${id} not found`)
    plugin.opts = newOpts

    if (plugin.onOptionChange) {
      plugin.onOptionChange(newOpts)
    } else {
      console.log(this)  // 👈 debug, 打印结果却是没有 restart 方法,初步怀疑是 this 指向变了，但没证据
      this.restart(`plugin ${id}'s option changed`)  // 报错的一行
    }
  }
```

**Expected behavior**

不报错

## Context

- **Umi Version**:  v2.11.1
- **Node Version**:  v10.16.0
- **Platform**:  macOS v10.14.4

**Comment by sorrycc** [comment]
用 `api.restart()` ?

**Comment by sorrycc** [comment]
用 `api.restart()` ?

**Comment by phobal** [comment]
@sorrycc 我是用 `api. changePluginOption ` 方法，然后这个方法内部抛 `this.restart` 未定义

**Comment by sorrycc** [comment]
1. `api.changePluginOption` 很少这么用，通常是在 `api.onOptionChange` 中使用，用于实现一个类似 preset 的概念，参考 umi-plugin-react 的实现
1. `api.changePluginOption('umi-plugin-react:dll', { dll: false })` 并不能关闭 dll，因为 dll 插件默认开启，不会跟进参数 `{ dll }` 进行判断
1. 建议不要这么做，可以判断用户配置，如果有 dll 插件，给予报错

**Comment by phobal** [comment]
谢谢大佬，我换个思路来做吧
