### ISSUE TITLE
[Feature Request] umi-request缓存请求可以不限制方法吗？

### ISSUE THREAD

**Issue by langlong149** [umijs/umi#3562]
## Background
目前umi-request方法中限制缓存必须使用'get’方法。

## Proposal

目前公司所有的请求都是使用‘post'，期望这个缓存不限制方法。

**Comment by chenjsh36** [comment]
HTTP 常见的四种方法为 GET、POST、PUT、DELETE，分别对应对资源的查、改、增、删，GET 一般用于获取或查询资源信息，POST 一般用于修改或更新资源信息，前者不对数据库做改动所以在更新频率低的情况下可以做缓存处理，后者为更新数据库资源操作，需要保障每次更新都实时获取是否成功的响应。基于以上关于 HTTP 协议规范考虑，umi-request 只对 get 请求做了响应的缓存，也建议开发者将需要缓存的接口改造成 GET 方法。

后续可拓展一个钩子供开发者自行决定什么情况下需要做缓存，来满足特殊场景下的需求。

**Comment by langlong149** [comment]
> HTTP 常见的四种方法为 GET、POST、PUT、DELETE，分别对应对资源的查、改、增、删，GET 一般用于获取或查询资源信息，POST 一般用于修改或更新资源信息，前者不对数据库做改动所以在更新频率低的情况下可以做缓存处理，后者为更新数据库资源操作，需要保障每次更新都实时获取是否成功的响应。基于以上关于 HTTP 协议规范考虑，umi-request 只对 get 请求做了响应的缓存，也建议开发者将需要缓存的接口改造成 GET 方法。
> 
> 后续可拓展一个钩子供开发者自行决定什么情况下需要做缓存，来满足特殊场景下的需求。

完全理解设计意图。 
但因为设置缓存是针对接口层面的，哪一个接口需要缓存，开发者应该是清楚的，需要缓存的才传递相应的参数，所以希望可以将这个主动权交给开发者来控制。
通过增加钩子的话，也没问题，只是用起来可能就会多一层逻辑。
