### ISSUE TITLE
 IE10 dva/dynamic The above error occurred in the <DynamicComponent> component

### ISSUE THREAD

**Issue by ggleo08** [umijs/umi#3563]
## What happens?

IE10 动态引入组件报错，信息如下：
![image](https://user-images.githubusercontent.com/32858631/68114104-338e7d00-ff30-11e9-9d16-1921dd53bbec.png)
![image](https://user-images.githubusercontent.com/32858631/68114122-3db07b80-ff30-11e9-89bd-e5094179de44.png)

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库
首页 Welcome 组件内的  Info 组件，即需要引入使用的组件，
复现repo：https://github.com/ggleo08/DVA_DYNAMIC_IE10_ISSUE
![image](https://user-images.githubusercontent.com/32858631/68114272-9253f680-ff30-11e9-9b42-02b967c9a675.png)

## 相关环境信息

- **Umi 版本**：v2.9.6
- **Node 版本**：v10.7.0
- **操作系统**：win10

**Comment by xiaohuoni** [comment]
好像ie不支持按需加载的api

**Comment by ggleo08** [comment]
> 好像ie不支持按需加载的api

按需加载是没有开启的，
`      antd: true,
      dva: {
        hmr: true,
        dynamicImport: false
      },
      locale: {
        // default false
        enable: true,
        // default zh-CN
        default: 'zh-CN',
        // default true, when it is true, will use `navigator.language` overwrite default
        baseNavigator: true,
      },
      dynamicImport: {
        // loadingComponent: './components/PageLoading/index',
        // webpackChunkName: true,
        // level: 3,
      },`

**Comment by xiaohuoni** [comment]
上次帅帅好像有说过，@chenshuai2144

**Comment by ggleo08** [comment]
@sorrycc @chenshuai2144  呼叫大佬，help  help help ...

**Comment by sorrycc** [comment]
排查了一段，

1. 通过 @ggleo08 提供的 repo 复现了
2. 注释掉一些插件（国际化等）之后不再报 DynamicImport 的错，而是报 saga 里 `user/fetchCurrect` 的错，再注释掉 `user/fetchCurrent` 的 dispatch 后能跑起来
3. 我自己写一个简单的例子，又不能复现，[sorrycc-aZtvNb.zip](https://github.com/umijs/umi/files/3812238/sorrycc-aZtvNb.zip)
4. 内网的 IE 平台测到一半挂了，再找时间继续排查吧

**Comment by ggleo08** [comment]
> 上次帅帅好像有说过，@chenshuai2144


> 排查了一段时间，笔记如下，
> 
> 1. 通过 @ggleo08 提供的 [repo](https://github.com/ggleo08/DVA_DYNAMIC_IE10_ISSUE) 复现了
> 2. 注释掉一些插件（国际化等）之后不再报 DynamicImport 的错，而是报 saga 里 `user/fetchCurrect` 的错，再注释掉 `user/fetchCurrent` 的 dispatch 后能跑起来
> 3. 我自己写一个简单的例子，又不能复现，[sorrycc-aZtvNb.zip](https://github.com/umijs/umi/files/3812238/sorrycc-aZtvNb.zip)
> 4. 内网的 IE 平台测到一半挂了，再找时间继续排查吧

感谢关注处理问题，前端弱鸡无力解决，继续 mark

**Comment by fantasy-wc** [comment]
现在也碰到了这个问题，mark一下

**Comment by Lokya** [comment]
现在这个问题感觉还是没有解决啊，我参考https://github.com/umijs/umi/issues/413#issuecomment-389016598这个里面的方案来解决，依旧不行，有没有好的解决方案呢。

**Comment by hankaibo** [comment]
我也遇到这个问题了。同求。

**Comment by quicklearning123** [comment]
同问
