### ISSUE TITLE
在externals中配置jquery，打包后umi.js报错jquery is not defined？

### ISSUE THREAD

**Issue by zhilianbi520** [umijs/umi#3564]
## What happens?
使用externals配置，提取了jquery，但是打包后 umi.js文件报jquery is not defined的错，如何解决？
![20191105161303](https://user-images.githubusercontent.com/16549630/68190099-c3dbc900-ffe7-11e9-9938-8f26382319ac.jpg)
![20191105161334](https://user-images.githubusercontent.com/16549630/68193591-41a2d300-ffee-11e9-811e-a69f825ee5fd.jpg)
![20191105161453](https://user-images.githubusercontent.com/16549630/68190121-ca6a4080-ffe7-11e9-975f-93cc3304a064.jpg)

## Context

- **Umi Version**:2.6.17
- **Node Version**:11.2.0
- **Platform**:mac 
使用的是 antd pro 版本为：2.1.1

**Comment by ycjcl868** [comment]
external 后，得配一个 js 外联到 html 中，并且在 umi.js 之前加载。
