### ISSUE TITLE
tsx文件中使用"可选链"语法报错解析不了(是否有用:@babel/plugin-proposal-optional-chaining插件解析呢？)

### ISSUE THREAD

**Issue by YitaoO** [umijs/umi#3572]
![image](https://user-images.githubusercontent.com/10783373/68278332-0b2b8d80-00ac-11ea-8ebd-b6ca8b0f1b42.png)

**Comment by zuozijian3720** [comment]
我也碰到了这个问题

**Comment by sorrycc** [comment]
`Optional Chaining` 是 ts 3.7 的功能吧，还没升上去。

**Comment by YitaoO** [comment]
> `Optional Chaining` 是 ts 3.7 的功能吧，还没升上去，需要改 af-webpack/package.json 里的 typescript 版本。

嗯，ts3.7版本有说，所以开发者是改不了的，等后期umi更新支持？

**Comment by GongT** [comment]
可以用yarn，
这样在package.json里写上
```jsonc
{
	// ...
	"resolutions": {
		"typescript": "3.7.2"
	},
	// ...
}
```
就可以了
