### ISSUE TITLE
Service.js printUmiError 方法覆盖问题

### ISSUE THREAD

**Issue by billfeller** [umijs/umi#3574]
## What happens?

Service.js 定义了 printUmiError 方法：
https://github.com/umijs/umi/blob/fc509d3588528e9dffdb7b424df8bd8a39a49f0c/packages/umi-build-dev/src/Service.js#L58

同时在构造函数中调用赋值操作：
https://github.com/umijs/umi/blob/fc509d3588528e9dffdb7b424df8bd8a39a49f0c/packages/umi-build-dev/src/Service.js#L40

导致调用对象的方法 printUmiError 其实都是调用全局工具方法，无法调用到 L58 定义的方法，确认下 printUmiError 是否有误

**Comment by sorrycc** [comment]
是的。
