### ISSUE TITLE
2.11.1版本下出现 You shoule not use <Switch> ouside a <Router>

### ISSUE THREAD

**Issue by Anonymity94** [umijs/umi#3576]
## What happens?
在umi@2.11.1版本下，出现了`You shoule not use <Switch> ouside a <Router>`。

截图如下：
![image](https://user-images.githubusercontent.com/13148447/68358563-d7a43e00-0153-11ea-9dce-9a03801639bd.png)

回退到 `umi@2.10.7` 后，没有该问题。
目前只测试了这2个版本， `2.10.7` ~ `2.11.1` 之间的版本是否有这个问题**尚未测试**。

## Mini Showcase Repository(REQUIRED)

暂无最小复现仓库<等忙完再补充>

## How To Reproduce

<待补充>

## Context

- **Umi Version**: umi@2.11.1
- **Node Version**: v10.15.2
- **Platform**: macOS Mojave 10.14.5

**Comment by sorrycc** [comment]
等补充完最小复现仓库再看。

**Comment by ycjcl868** [comment]
关闭 dll 试试。 @Anonymity94

**Comment by Anonymity94** [comment]
@ycjcl868 感觉和这个没什么关系。
因为生产环境下没有开启`dll`，使用`jenkins`在生产环境下自动打包的时候也会出现这个问题。

**Comment by Anonymity94** [comment]
@sorrycc 没有使用到`umi-plugin-preload`这个。

我今天下午看看能不能复现出来，复现出来的话我给提供个最小仓库地址~

**Comment by ycjcl868** [comment]
watch

**Comment by Anonymity94** [comment]
1. 尝试一，失败😥
获取 `Ant Design Pro` 最新分支代码，然后调整依赖的版本：
```
"umi": "^2.8.7",
"umi-plugin-react": "^1.9.5"
```

2. 尝试二，失败😩
获取公司产品代码，调整依赖的版本（同上），复现失败。

要不先这样吧，如果我再次发现这个问题，我`debug`下，再更新进展吧~
