### ISSUE TITLE
How to remove umi ui bubble

### ISSUE THREAD

**Issue by axelginepro** [umijs/umi#3577]
## What happens?
https://drive.google.com/open?id=1JU52HPDikMn_8oRWvhlJwsasyoN51Asu

how to remove this umi.js ui bubble please , thanks

**Expected behavior**
remove 
## Context

- **Umi Version**: ^2.11.1",
- **Node Version**: 13.1
- **Platform**: windows 10

**Comment by sorrycc** [comment]
with the env variable `UMI_UI=none`.

**Comment by sxcooler** [comment]
我的项目里用到了mobx，mobx的provider会用React.Children.only，然后就报了Error: React.Children.only expected to receive a single React element child
我百思不得其解（我代码里明明只有一个div），直到我看到那三个children里有两个type=GUmiUIFlag，我真的……
发在这里方便遇到同样问题的同学吧，真心希望国内有些pm不要设计一些破坏性的莫名其妙的东西。
