### ISSUE TITLE
[RFC] 将 .umi/.umi-production 迁移至 node_modules 中

### ISSUE THREAD

**Issue by CJY0208** [umijs/umi#3578]
## 背景

`.umi/.umi-production` 是临时文件夹，放在页面层级的文件夹下，具体为 `src/pages` 中

https://umijs.org/zh/guide/app-structure.html#src-pages-umi
https://umijs.org/zh/guide/app-structure.html#src-pages-umi-production

开发者总是能看到它们，文档里也需要特意说明不要改动里边的东西，如果项目中额外加入了功能，也许还需要对其做 .ignore 声明

为什么不直接将它们迁移至一般不会被关注的地方呢？例如 `node_modules` 中

## 思路

1. 将 `.umi/.umi-production` 的输出路径由 `src/pages` 调整为 `node_modules`
2. 调整对应的 `webpackConfigOpts.resolve.alias`
3. 其他调整

## 跟进

- [ ] 将 .umi/.umi-production 迁移至 node_modules 中
- [ ] PR URL

**Comment by sorrycc** [comment]
虽然 `.umi` 不允许被修改，但开发者通常还是需要了解这里的内容的，以及出错调试的时候也会用到他，放 node_modules 下找起来就很麻烦了。类似的比如 next.js 也是如此。

**Comment by CJY0208** [comment]
了解了，由于 .umi 也属于运行时文件，严格意义上也属于源代码的一种

只是由 umi 辅助生成，所以放在 src 中也合理，感谢解答！

不过有没有办法可以在不希望关注它时隐藏它呢？会有一丝洁癖或者...强迫症之类的

它并不是我的代码产物，我却总是能在工作区看到它

**Comment by sorrycc** [comment]
能否隐藏得看编辑器的功能了，或者用着用着你可以就习惯他的存在了。
