### ISSUE TITLE
Umi UI 创建项目挂起

### ISSUE THREAD

**Issue by GongT** [umijs/umi#3579]
> 安装或更新 没反应 卡住 umi ui hang create-umi create step 2

## What happens?

![image](https://user-images.githubusercontent.com/2265048/68444160-fc122000-0210-11ea-85a2-2eed5f455d25.png)
```
Nov 07 22:20:39 work.gongt.me umi[11226]: 2019-11-07T14:20:39.710Z umiui:UmiUI:socket >>>> {"type":"@@project/create/progress","payload":{"install":"npm WARN create-umi No description\n"}}
Nov 07 22:20:39 work.gongt.me umi[11226]: npm WARN create-umi No repository field.
Nov 07 22:20:39 work.gongt.me umi[11226]: npm WARN create-umi No license field.
Nov 07 22:20:39 work.gongt.me umi[11226]: 2019-11-07T14:20:39.710Z umiui:UmiUI:socket >>>> {"type":"@@project/create/progress","payload":{"install":"npm WARN create-umi No repository field.\nnpm WARN create-umi No license field.\n"}}
Nov 07 22:20:39 work.gongt.me umi[11226]: 2019-11-07T14:20:39.710Z umiui:UmiUI:socket >>>> {"type":"@@project/create/progress","payload":{"install":"\n"}}
Nov 07 22:20:49 work.gongt.me umi[11226]: + create-umi@0.19.0
Nov 07 22:20:49 work.gongt.me umi[11226]: added 510 packages from 363 contributors in 2074.816s
Nov 07 22:20:49 work.gongt.me umi[11226]: 2019-11-07T14:20:49.720Z umiui:UmiUI:socket >>>> {"type":"@@project/create/progress","payload":{"install":"+ create-umi@0.19.0\nadded 510 packages from 363 contributors in 2074.816s\n"}}
Nov 07 22:20:49 work.gongt.me umi[11226]: npm 2019-11-07T14:20:49.723Z umiui:UmiUI:socket >>>> {"type":"@@project/create/progress","payload":{"install":"npm "}}
Nov 07 22:20:49 work.gongt.me umi[11226]: timing npm Completed in 2075604ms
Nov 07 22:20:49 work.gongt.me umi[11226]: npm info ok
Nov 07 22:20:49 work.gongt.me umi[11226]: 2019-11-07T14:20:49.723Z umiui:UmiUI:socket >>>> {"type":"@@project/create/progress","payload":{"install":"timing npm Completed in 2075604ms\nnpm info ok \n"}}
Nov 07 22:20:49 work.gongt.me umi[11226]: (node:11226) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'creatingProgress' of undefined
Nov 07 22:20:49 work.gongt.me umi[11226]:     at Config.setCreatingProgress (/usr/local/share/yarn/global/node_modules/umi-ui/lib/Config.js:174:100)
Nov 07 22:20:49 work.gongt.me umi[11226]:     at /usr/local/share/yarn/global/node_modules/umi-ui/lib/UmiUI.js:680:25
Nov 07 22:20:49 work.gongt.me umi[11226]:     at Generator.next (<anonymous>)
Nov 07 22:20:49 work.gongt.me umi[11226]:     at asyncGeneratorStep (/usr/local/share/yarn/global/node_modules/umi-ui/lib/UmiUI.js:210:103)
Nov 07 22:20:49 work.gongt.me umi[11226]:     at _next (/usr/local/share/yarn/global/node_modules/umi-ui/lib/UmiUI.js:212:194)
Nov 07 22:20:49 work.gongt.me umi[11226]:     at runMicrotasks (<anonymous>)
Nov 07 22:20:49 work.gongt.me umi[11226]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Nov 07 22:20:49 work.gongt.me umi[11226]: (node:11226) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

```

## 相关环境信息

- **Umi 版本**：2.11.1
- **Node 版本**：v12.13.0
- **操作系统**：Linux

**Comment by sorrycc** [comment]
1. `~/.umi/ui/data.json` 的内容贴出来看下
2. 编辑 `/usr/local/share/yarn/global/node_modules/umi-ui/lib/UmiUI.js` 第 680 行，打印下 key 和 e，看看是啥

**Comment by GongT** [comment]
很奇怪，试了几次自己好了。。。
这个先关了吧。。


不过有个建议：

上一步我刚选完要用yarn，结果这个还是在调用npm，而且似乎registry固定是淘宝源。    
这个对环境限制太大了，我在windows上一般是不装npm的。而且我本地配置有npm镜像，实际没用到，导致这一步非常慢。

**Comment by sorrycc** [comment]
1. npm 有 node 就有，不需要装
2. `而且我本地配置有npm镜像，实际没用到`，这个我优化下，优先用自定义的 registry

**Comment by williamhatch** [comment]
![image](https://user-images.githubusercontent.com/40409716/70406490-c4afc100-1aa5-11ea-9930-cd46048555cd.png)

hang here...

**Comment by williamhatch** [comment]
Uncaught (in promise) TypeError: api.addDashboard is not a function
    at ui (eval at <anonymous> (umi.6fa2ee83.js:28), <anonymous>:17383:9)
    at umi.6fa2ee83.js:28
    at Array.forEach (<anonymous>)
    at umi.6fa2ee83.js:28
    at l (umi.6fa2ee83.js:28)
    at Generator._invoke (umi.6fa2ee83.js:28)
    at Generator.e.<computed> [as next] (umi.6fa2ee83.js:28)
    at n (umi.6fa2ee83.js:28)
    at i (umi.6fa2ee83.js:28)

**Comment by PmcFizz** [comment]
> Uncaught (in promise) TypeError: api.addDashboard is not a function
> at ui (eval at (umi.6fa2ee83.js:28), :17383:9)
> at umi.6fa2ee83.js:28
> at Array.forEach ()
> at umi.6fa2ee83.js:28
> at l (umi.6fa2ee83.js:28)
> at Generator._invoke (umi.6fa2ee83.js:28)
> at Generator.e. [as next] (umi.6fa2ee83.js:28)
> at n (umi.6fa2ee83.js:28)
> at i (umi.6fa2ee83.js:28)

请问这个你解决了吗  我也遇到同样的问题

**Comment by t880216t** [comment]
> > Uncaught (in promise) TypeError: api.addDashboard is not a function
> > at ui (eval at (umi.6fa2ee83.js:28), :17383:9)
> > at umi.6fa2ee83.js:28
> > at Array.forEach ()
> > at umi.6fa2ee83.js:28
> > at l (umi.6fa2ee83.js:28)
> > at Generator._invoke (umi.6fa2ee83.js:28)
> > at Generator.e. [as next] (umi.6fa2ee83.js:28)
> > at n (umi.6fa2ee83.js:28)
> > at i (umi.6fa2ee83.js:28)
> 
> 请问这个你解决了吗 我也遇到同样的问题

同问
