### ISSUE TITLE
af-webpack 是否有引入类似 happypack 的机制来提高构建速度？

### ISSUE THREAD

**Issue by lusess123** [umijs/umi#358]
如题

**Comment by sorrycc** [comment]
目前没有，有兴趣提个 PR？

**Comment by superlbr** [comment]
翻到一篇[旧文](http://taobaofed.org/blog/2016/12/08/happypack-source-code-analysis/), 充分利用了多核？

**Comment by xiajinchun** [comment]
请问现在用类似 happypack 实现多核构建，这个 umi 有了吗？
