### ISSUE TITLE
Problem with runtimePublicPath 

### ISSUE THREAD

**Issue by rockSandy** [umijs/umi#3588]
## What happens?

set runtimePublicPath to true
The `dist/index.html` code 

```html
<!DOCTYPE html><html lang="en"><head><link rel="stylesheet" href="/umi.css"><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Document</title>
<script>window.publicPath = "http://cdn.xxx"</script>
<script>window.routerBase = "/";
  window.publicPath = "/";</script>
</head><body><div id="root"></div><script src="/umi.js"></script></body></html>
```
window.publicPaht overwritten by the generated code

## Mini Showcase Repository(REQUIRED)

https://github.com/rockSandy/umi-report/tree/runtimePunlicPath

## How To Reproduce

1. define window.publicPath in `pages/document.ejs` header tag
2. npm run build

## Context

- **Umi Version**: 2.7.7
- **Node Version**: v12.4.0
- **Platform**:

**Comment by sorrycc** [comment]
使用 runtimePublicPath 时，通常 html 不是前端提供的，因为 runtimePublicPath 需要针对环境做区分。

**Comment by sqlwwx** [comment]
<script src="/umi.js">这个地址应该是http://cdn.xxx/umi.js
