### ISSUE TITLE
webpack DefinePlugin does not work with EJS template

### ISSUE THREAD

**Issue by aletus** [umijs/umi#359]
I need to define analytics ID and other strings out side of the code to separate out dev and production environments and other usages.  Currently I put this in the <head> of a document.ejs template.

If I use define in .webpackrc.js like this:
```
define": {
  "ANALYTIC_ID: 123,
}
```

UMI does not replace strings ANALYTIC_ID in EJS templates such as document.ejs.

Looking through the code it seems the reason being HTML are being render directly by UMI code instead of being handle through html_webpack_plugin.

I have workaround such as using process.env variables or moving some of this from the EJS template into the JS code.

However would be simpler if EJS can use webpack defineplugin.  Enhancement? Any thought?

**Comment by qhy90223** [comment]
同上，我在webpackrc.js中设置了define，但是在document.ejs的script标签中无法获取
```
"define": {
       "publicPath":JSON.stringify(publicPath)
        
      },
```
![image](https://user-images.githubusercontent.com/27689377/39849315-538e3d0a-543e-11e8-92e5-b5565d97e237.png)

**Comment by lsqaisen** [comment]
https://stackoverflow.com/questions/39053562/eslint-no-undef-and-webpack-plugin?rq=1

**Comment by NexxLuo** [comment]
我现在也遇到了同样的问题，但是按照楼上的做法，依然不行。

**Comment by sorrycc** [comment]
可以通过 `<%= context.config.define %>` 获取到。
