### ISSUE TITLE
umi-plugin-locale 插件中  使用 typescript 没有定义 defineMessages。

### ISSUE THREAD

**Issue by jefferyssy** [umijs/umi#3590]
import { FormattedMessage, defineMessages } from 'umi-plugin-react/locale';

typescript 下： 提示没有定义 defineMessages 
查看代码：  是  
umi-plugin-locale\index.d.ts
中 没有 申明 react-intl 的 defineMessage

**Comment by jefferyssy** [comment]
> import { FormattedMessage, defineMessages } from 'umi-plugin-react/locale';
> 
> typescript 下： 提示没有定义 defineMessages
> 查看代码： 是
> umi-plugin-locale\index.d.ts
> 中 没有 申明 react-intl 的 defineMessage

**Comment by leftstick** [comment]
目前使用的是`react-intl@2.7.2`，里面没有`defineMessages`

**Comment by jefferyssy** [comment]
![image](https://user-images.githubusercontent.com/18325063/68556943-38db5280-046f-11ea-830d-989a0991da75.png)

**Comment by jefferyssy** [comment]
![image](https://user-images.githubusercontent.com/18325063/68557044-95d70880-046f-11ea-89f0-c80f5cdbc3bf.png)
![image](https://user-images.githubusercontent.com/18325063/68557066-a7b8ab80-046f-11ea-8830-971511d3a1b5.png)
