### ISSUE TITLE
umi-request 拦截器对Promise的响应好像不符合预期

### ISSUE THREAD

**Issue by weiqinke** [umijs/umi#3592]
## 最小可复现仓库
https://gitee.com/weiqinke/umi-request-iss.git
`
const request = extend({
  maxCache: 50, // 最大缓存个数, 超出后会自动清掉按时间最开始的一个.
  //prefix: '/api/v1', // 默认前缀
  errorHandler, // 默认错误处理
  credentials: 'omit', // 默认请求是否带上cookie 'include'
});

// 是否正在刷新的标记
let isRefreshing = false;
// 是否过期
let guoqi = true;
// 缓冲池
let _cacheRequest = [];
request.interceptors.request.use(async (url, options, next ) => {
  //获取token
  const token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiMTExMTExMTExMTExMTExMTExMTExMSIsImlhdCI6MTU3MzIwMTk0NCwiZXhwIjoxNTczMjQ1MTQ0fQ.oIhp68tfof5RqEKyHyiTvtfNEiz3w0rgeuwNrIF5tl8'
  //如果有token
  if (token) {
    //如果过期了
    if(guoqi){
      if( url === '/top/api/account/login/getnewtoken'){
        return {
          url,
          options: { ...options, headers },
        };
      }
      if (!isRefreshing) {
        isRefreshing = true
        request('/top/api/account/login/getnewtoken', {
          method: 'POST',
          data: {},
        }).then(function( data ){
          guoqi = false;
          isRefreshing = false;
          _cacheRequest.forEach(cb=>cb())
          _cacheRequest = [];
        })

        return new Promise((resolve) => {
          // 将resolve放进队列，用一个函数形式来保存，等token刷新后直接执行
          _cacheRequest.push(() => {
            resolve( request( url, options ) )
          })
        })
      } else {
        // 正在刷新token，将返回一个未执行resolve的promise
        return new Promise((resolve) => {
          // 将resolve放进队列，用一个函数形式来保存，等token刷新后直接执行
          _cacheRequest.push(() => {
            resolve( request( url, options ) )
          })
        })
      }
    }
    
    const headers = {
      Authorization: `Bearer ${token}`,
    };

    return {
      url,
      options: { ...options, headers },
    };
  }
  return {
    url,
    options: { ...options },
  };
});

`

## 复现步骤，错误日志以及相关配置
在发起请求前，拦截器返回了Promise，在Promise触发了resolve的时候，好像会重新请求？还是说暂不支持的

## 相关环境信息

- **Umi 版本**：^2.9.6
- **Node 版本**：10.0.0
- **操作系统**：win10

**Comment by chenjsh36** [comment]
拦截器支持 Promise 的，会重新请求是因为你在 resolve 里调用了 request 函数导致发起新的请求，去掉 request( url, options ) 就可以了
