### ISSUE TITLE
context如何注入到页面

### ISSUE THREAD

**Issue by lee84233** [umijs/umi#3594]
## 最小可复现仓库

[https://github.com/lee84233/React-demo](https://github.com/lee84233/React-demo)

## 复现步骤，错误日志以及相关配置
1. `.umirc.js` 配置 `context` 属性对象。`export default { context: {domain: 'xxx'} }`
2. 每个 *.js 页面中`this.context`都是空对象`{}`，如何获取 context ？

## 相关环境信息

- **Umi 版本**：2.11.1
- **Node 版本**：10.16.2
- **操作系统**：win7

**Comment by leftstick** [comment]
在`src/pages/document.ejs`里，可以通过`<%= context. domain %>`来访问
