### ISSUE TITLE
umi可以在app.js中进行dispatch吗

### ISSUE THREAD

**Issue by ywy94ywy** [umijs/umi#3598]
需求是这样的，路由是动态获取的，所以在app.js中的render方法里请求接口获取菜单，然后再渲染。
现在这个菜单需要在全局使用，除了存入本地存储，可以通过dispatch修改全局数据吗

**Comment by leftstick** [comment]
你这个操作，放到layout里，以HOC的形式会不会更好达成一点？

**Comment by ywy94ywy** [comment]
不行啊，动态获取菜单只能放在app.js里

**Comment by sorrycc** [comment]
比较好的办法是 app.js 里异步取，然后通过 dva 的 initialState 传入，但是 dva 的配置不支持异步取，所以先存全局变量吧。

**Comment by ywy94ywy** [comment]
@sorrycc 我动态获取的菜单，model.js就不会注册了么，我connect之后发现找不到动态模块的model了

**Comment by sorrycc** [comment]
没理解，问题需要更清楚一些。

**Comment by ywy94ywy** [comment]
@sorrycc 
在app.js中通过接口获取菜单后，其中一个菜单path为/test，对应组件为pages/test/index.js，
此时我在test文件夹下建立一个model.js，
然后在test/index.js中connect之后，访问不到这个model，即这个model没有被注册
umi好像只有两种方式会自动注册，
①pages/models文件夹下所有models，
②在config.js中配置好路由，对应组件的model.js被注册。

**Comment by sorrycc** [comment]
dva 不开按需，model 应该是全量加载的，试试 `dva: { dynamicImport: false }`。

**Comment by ywy94ywy** [comment]
好像还是不行，
这是配置：
![image](https://user-images.githubusercontent.com/22499767/69108630-3355bc00-0ab0-11ea-9f83-f018a06d6e21.png)

这是测试代码：
![image](https://user-images.githubusercontent.com/22499767/69108557-fd183c80-0aaf-11ea-9c16-fab1bf192a71.png)
![image](https://user-images.githubusercontent.com/22499767/69108568-03a6b400-0ab0-11ea-9067-daaf218df1ab.png)
![image](https://user-images.githubusercontent.com/22499767/69108593-14572a00-0ab0-11ea-8919-dcc9710a084c.png)
![image](https://user-images.githubusercontent.com/22499767/69108596-17eab100-0ab0-11ea-9641-9e85f52a4874.png)

这是输出：
![image](https://user-images.githubusercontent.com/22499767/69108651-4b2d4000-0ab0-11ea-9f92-f13a16747905.png)

**Comment by axolo** [comment]
Get `window.g_app._store` as `store` after `await render()` in `/src/app.js`:

```js
export async function render(renderNext) {
  await renderNext();
  const { g_app: app } = window;
  const { _store: store } = app;
  const { dispatch, getState } = store;
  const { settings } = getState();
  socket({ config: settings.socket, dispatch });
}
```

**Comment by minteliuwm** [comment]
> Get `window.g_app._store` as `store` after `await render()` in `/src/app.js`:
> 
> ```js
> import socket from './utils/socket';
> 
> export async function render(renderNext) {
>   await renderNext();
>   const { g_app: app } = window;
>   const { _store: store } = app;
>   const { dispatch, getState } = store;
>   const { settings } = getState();
>   socket({ config: settings.socket, dispatch });
> }
> ```

试了一下，也取不到。。尴尬
