### ISSUE TITLE
Migrating create-react-app to umi

### ISSUE THREAD

**Issue by urrri** [umijs/umi#3601]
Hi UMI team,

Is there any way or documentation (English preferably) to migrate project built with create-react-app to umi? Also it would be nice to have possibility to allow any project to be used with umi. Especially interesting the way to use existing routing with umi, but without converting it to umi conventions.

Thanks.

**Comment by sorrycc** [comment]
Try [umi-plugin-mpa](https://github.com/umijs/umi-plugin-mpa), which only use umi as a webpack wrapper.

**Comment by urrri** [comment]
Thank you. Does it work with other cool options of UMI, like mock server, antd support, SPA support, etc.?

**Comment by ycjcl868** [comment]
Maybe we should provide the migration document or the codemod tool.

**Comment by urrri** [comment]
It would be nice.
UMI is a very cool and strong system, but on the other hand it has become very complex. It was easy to connect any projects to the good old Roadhog, but this one requires compliance with many conditions.

**Comment by JunlinZhu-Tommy** [comment]
It would be very nice we have a migration docs about how to migrate from create-react-app to umi.

**Comment by urrri** [comment]
We still don't have promised migration document. At least nobody placed link here.
