### ISSUE TITLE
when after `npm install umi-request` module, it has node_modules

### ISSUE THREAD

**Issue by cathy-zhao** [umijs/umi#3602]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by leftstick** [comment]
这个是npm的策略，当你的项目和umi-request有相同的依赖，但版本要求不同且不能自动`solve confict`时，你的项目依赖`node_modules`和`umi-request`的依赖`node_modules/umi-request/node_modules`都会出现这个依赖，且保持各自需要的版本
