### ISSUE TITLE
umi-plugin-react必须配置dva为true吗？设置false会报错。

### ISSUE THREAD

**Issue by langlong149** [umijs/umi#3605]
## What happens?
配置项如下图：
![image](https://user-images.githubusercontent.com/19711638/68636783-a81c7980-0537-11ea-92e2-e7f03e288f5f.png)
配置dva为true时，没有问题，设置为false时，报错如下：
![image](https://user-images.githubusercontent.com/19711638/68636809-c6827500-0537-11ea-834b-5d10a7203f51.png)
。
umi-plugin-react版本为： 1.13.1
umi版本： 2.11.1。

**Comment by xiaohuoni** [comment]
`src/app.js` 里面有 dva 的相关设置，要去掉

**Comment by langlong149** [comment]
> `src/app.js` 里面有 dva 的相关设置，要去掉

刚意识到，想过来关闭下，发现已经关了~~ 多谢。
