### ISSUE TITLE
使用 decorator，启动的时候报错

### ISSUE THREAD

**Issue by amily4555** [umijs/umi#361]
配置文件 ".umirc.js" 解析出错，请检查语法。

Error: [BABEL] /Users/Mizi/git/express/.umirc.js: The new decorators proposal is not supported yet. You must pass the `"legacy": true` option to @babel/plugin-proposal-decorators (While processing: "/Users/Mizi/git/express/node_modules/@babel/plugin-proposal-decorators/lib/index.js")

-
看网上解决方案是 配置 transform-decorators-legacy
但我在 webpackrc 中配置

extraBabelPlugins: [
        'transform-decorators-legacy',
]

还是不启动失败，还是原来的错误

**Comment by sorrycc** [comment]
已通过 babel-preset-umi@0.2.8 修复，重装依赖试试。

**Comment by amily4555** [comment]
OK 测试通过，也无需配置 extraBabelPlugins

then, 准备在umi的哪个版本使用0.2.8 的依赖？

**Comment by sorrycc** [comment]
0.2.8 是 bugfix，已使用。
