### ISSUE TITLE
devServer配置无效？

### ISSUE THREAD

**Issue by yuyic** [umijs/umi#3613]
`
devServer:{ port:9000 }
`
或
`
devServer:{ https:true }
`
都无效

**Comment by liulinana** [comment]
直接在.env文件中配置环境即可，例如：配置启动端口：PORT=8000，热更新：HMR=reload等，
![image](https://user-images.githubusercontent.com/34056781/69040420-bcc1ab80-0a28-11ea-8792-4d3d7bae6ca6.png)

**Comment by sorrycc** [comment]
通过环境变量实现，PORT, HTTPS 等。

**Comment by qiaosu** [comment]
@sorrycc 如果想通过配置文件的方式指定 port，现在有办法吗？
