### ISSUE TITLE
最近升级后，umi dev只能localhost访问，局域网内不能访问

### ISSUE THREAD

**Issue by tom110** [umijs/umi#3617]
最近升级后，umi dev只能localhost访问，局域网内不能访问了

**Comment by tom110** [comment]
设置了.env的环境变量也没有起作用，请问需要设置什么地方，另外umi dev的script文件位置能不能说一下，非常感谢

**Comment by xiaohuoni** [comment]
看一下 dev 给的链接，还有 ipconfig 看一下，你是不是链接了 vpn 之类的，最近更新版本号是多少？
毕现的话给一个重现 demo 。

**Comment by xiaohuoni** [comment]
另外 `umi dev` 的文件位置 `packages/umi/src/scripts/dev.js`

**Comment by tom110** [comment]
- Local:   http://127.0.0.1:8000/ (copy to clipboard failed)，打印是这样的，我在.env上设置了HOST=0.0.0.0,没有起作用，vue里的package.json是直接webpack脚本，灾后面加host=0.0.0.0就可以了，但是咱们的是umi dev，然后追到packages/umi/src/scripts/dev.js后，发现也没有webpack的设置，还要往下追，所以就在这里问了，umi 是2.11.3

**Comment by xiaohuoni** [comment]
dev 会给一个局域网的地址。

**Comment by tom110** [comment]
```
[root@localhost ant]# umi dev

✔ Webpack
  Compiled successfully in 5.05s

Starting the development server...

 DONE  Compiled successfully in 5056ms                                                                                       11:02:27 AM


  App running at:
  - Local:   http://127.0.0.1:8000/ (copy to clipboard failed)


 WAIT  Compiling...                                                                                                          11:02:27 AM


✔ Webpack
  Compiled successfully in 278.93ms

 DONE  Compiled successfully in 280ms           
```
以前学士还有一个局域网地址，但是现在就是这个

**Comment by sorrycc** [comment]
查下自己的 ip，然后用 http://{ip}:8000/ 能访问吗？

**Comment by tom110** [comment]
我的开发实在我的一台局域网centos机器上做的，访问在另外一台电脑上，使用http://{centos-ip}:8000访问

**Comment by tom110** [comment]
使用umi挺长时间了，操作一直没变，就是最近才出现的这个问题，我查资料有人说webpack变了，所以不能局域网其他机器访问了，webpack的解决办法是加--host 0.0.0.0，这个在vue-cli创建的脚手架中成功了，咱们的umi我不知道去那个文件设置一下webpack的配置，问题就是这样的，umi dev后只有http://127.0.0.1:8000,以前的时候是有http://{centos-ip}:8000的

**Comment by sorrycc** [comment]
umi 默认加了 host 0.0.0.0 的，我不能复现这个问题。

**Comment by ystarlongzi** [comment]
1. 检查下 html 里是否设置了 window.publicPath 【也可以尝试在控制台输出下这个变量】

2. 检查下 .umirc.ts 里是否配置了 [`runtimePublicPath`](https://v2.umijs.org/zh/config/#runtimepublicpath)

**Comment by BearD01001** [comment]
遇到了同样的问题，umi.css 与 umi.js 这两个文件即使使用局域网的 IP 访问，也会请求到 localhost 上导致无法加载，最终无法渲染。
没有配置 `window.publicPath` 与 `runtimePublicPath`。
有解决了该问题的朋友吗？

**Comment by drafish** [comment]
我这边也复现了这个问题，是因为我用了`@umijs/plugin-qiankun`插件的缘故，我把插件去掉就好了，我的umi版本是2.13.13

**Comment by nopapername** [comment]
> ```
> [root@localhost ant]# umi dev
> 
> ✔ Webpack
>   Compiled successfully in 5.05s
> 
> Starting the development server...
> 
>  DONE  Compiled successfully in 5056ms                                                                                       11:02:27 AM
> 
> 
>   App running at:
>   - Local:   http://127.0.0.1:8000/ (copy to clipboard failed)
> 
> 
>  WAIT  Compiling...                                                                                                          11:02:27 AM
> 
> 
> ✔ Webpack
>   Compiled successfully in 278.93ms
> 
>  DONE  Compiled successfully in 280ms           
> ```
> 
> 以前学士还有一个局域网地址，但是现在就是这个

这个有解决吗

**Comment by guwan** [comment]
用的最新版，还没有解决啊，烦啊。有没有解决方案呢？

**Comment by fz6m** [comment]
需要配置 `HOST=0.0.0.0` 才能公开到局域网，否则都是本地才可以使用。

**Comment by guwan** [comment]
> 需要配置 `HOST=0.0.0.0` 才能公开到局域网，否则都是本地才可以使用。

我使用 `"start:dev": "cross-env HOST=0.0.0.0 REACT_APP_ENV=dev MOCK=none UMI_ENV=dev max dev"`
或者在idea的node选项那里加入参数均不行。
![image](https://github.com/umijs/umi/assets/5222986/ca51ed97-af0f-43fc-8bf6-9a0349827798)

请问你是怎么做的呢？
我的依赖配置如下：
"dependencies": {
    "@ant-design/icons": "^5.1.4",
    "@ant-design/pro-components": "^2.6.8",
    "@ant-design/use-emotion-css": "1.0.4",
    "@umijs/route-utils": "^4.0.1",
    "@zxing/library": "^0.20.0",
    "antd": "^5.7.3",
    "antd-mobile": "^5.32.4",
    "antd-mobile-icons": "^0.3.0",
    "classnames": "^2.3.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.11.0",
    "rc-util": "^5.35.0",
    "react": "^18.2.0",
    "react-dev-inspector": "^1.8.6",
    "react-dom": "^18.2.0",
    "react-helmet-async": "^1.3.0",
    "vditor": "^3.9.4"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^3.1.0",
    "@testing-library/react": "^13.4.0",
    "@types/classnames": "^2.3.1",
    "@types/express": "^4.17.17",
    "@types/history": "^4.7.11",
    "@types/jest": "^29.4.0",
    "@types/lodash": "^4.14.191",
    "@types/react": "^18.2.17",
    "@types/react-dom": "^18.2.7",
    "@types/react-helmet": "^6.1.6",
    "@umijs/fabric": "^4.0.1",
    "@umijs/lint": "^4.0.73",
    "@umijs/max": "^4.0.73",
    "cross-env": "^7.0.3",
    "eslint": "^8.34.0",
    "express": "^4.18.2",
    "gh-pages": "^3.2.3",
    "husky": "^7.0.4",
    "jest": "^29.4.3",
    "jest-environment-jsdom": "^29.4.3",
    "lint-staged": "^10.5.4",
    "mockjs": "^1.1.0",
    "prettier": "^2.8.4",
    "swagger-ui-dist": "^4.15.5",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.5",
    "umi-presets-pro": "^2.0.2"
  }

**Comment by fz6m** [comment]
如有局域网问题，请自行排查电脑情况和代理情况。

**Comment by wowsummer** [comment]
umi max 4.3.35 同样的问题
