### ISSUE TITLE
如何动态开启hd？ 

### ISSUE THREAD

**Issue by innocces** [umijs/umi#3618]
## What happens?
想要动态配置hd配置

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by ycjcl868** [comment]
为何要动态开

**Comment by xiaohuoni** [comment]
伪需求吧

**Comment by innocces** [comment]
=。-  因为想要共用antd和mobile，pc和h5部署在一起，因为rem是用hd写的，所以开启hd的时候。antd的css也被编译成了rem，但是在切换成pc的时候还想用px

**Comment by sorrycc** [comment]
现在不支持这种方式，可以通过两次打包，两份配置的方式绕过。

**Comment by DarcyXf** [comment]
其实在写H5活动的时候，这种需求蛮常见的。
用户打开的场景主要是移动端，但是用户也会有机会在PC打开这个链接，这个时候只要能在视口中以主流移动设备的尺寸居中显示就能比较好的满足需求了。但是当前hd方案下的rem会让设计变得很不协调。
