### ISSUE TITLE
umi-plugin-qiankun 由路由跳回上一个模块时，渲染的还是上一次的渲染页面而不是本身路由的页面

### ISSUE THREAD

**Issue by yshkk** [umijs/umi#3624]
## What happens?

umi-plugin-qiankun 由路由跳回上一个模块时，渲染的还是该模块上一次的渲染页面而不是本身路由的页面

## How To Reproduce

如examples，先点到http://localhost:8000/app1/user页 然后点上方导航菜单的app2，再点app1，这时候的url是 http://localhost:8000/app1 但是渲染的是http://localhost:8000/app1/user的内容而不是http://localhost:8000/app1/ 的内容

**Expected behavior**
切回app1时渲染当前url对应的页面

## Context

- **Umi Version**:^2.9.0, "@umijs/plugin-qiankun": "^1.3.2"
- **Node Version**:v10.16.0
- **Platform**: Mac

**Comment by gaorubin1990** [comment]
请问这个问题有解决方案吗？遇到了相同的问题 @sorrycc

**Comment by Plortinus** [comment]
这个问题有解决吗？
