### ISSUE TITLE
咨询一下为什么 2.8.12 和 2.10.5 中 router.push 行为不一致

### ISSUE THREAD

**Issue by theprimone** [umijs/umi#3639]
## What happens?

我实现了一个基于 `ant-design-pro` 的多标签页功能，通过将 `router.push` 的组件放到 `Tabs` 的子组件中实现，切换标签页也是使用 `router.push`，如果这个组件没有子路由的话，就不让该组件刷新以优化性能，[具体实现](https://github.com/theprimone/ant-design-pro-v2-plus/blob/master/src/components/PageTabs/index.tsx#L69) 。

之前一切正常，一次偶然的机会升级最新的 umi 升到了 2.8.12 ，后来发现即使我在 `shouldComponentUpdate` 中 `return false` 一样会触发所有标签页的刷新。在 React 的开发者工具中发现 2.8.12 中的 `router.push` 会持续更新 `props` 中的 `history` 的，怀疑就是这个属性导致了页面的刷新。

好在一个同事也升级了 umi ，他的没有这个问题，所以我升级到 2.10.5 之后，这个问题就解决了， `router.push` 不会持续更新注入的 `history` 了。

问题虽然解决了，但是不太清楚具体是怎么回事，希望能解答一下，抑或告知一下源码中有何变化，谢谢。

## 相关环境信息

- **Umi 版本**：2.8.12 和 2.10.5
- **Node 版本**：v10.16.3
- **操作系统**：windows 10 1903

**Comment by sorrycc** [comment]
没太理解，可以抽象下功能，补个用例，确保 umi 升级不会导致这个问题出错。umi 2.8 和 2.10 的区别，应该是 2.10 升级了最新的 react-router@5，但是 2.x 到 2.8 路由并没有啥相关的变动。

**Comment by theprimone** [comment]
又思考了一下，核心问题如下：

```tsx
// Page.tsx 假设该页面路由为：path/:name

@connect()  // 注入 Dva 中的状态
class Page extends React.component {
  // ...
}
```

umi 2.8.12 之前（或许是 2.4.4 ） ，路由注入 `history` 到页面组件 `Page`（**标签页不关闭就一直渲染的是最初的组件，后续注入同一路由的组件不会调用**）后不会随着后续路由变化而改变。但是在 2.8.12 中，已经被注入的 `history` 的组件 `Page`（还是渲染最初的组件）中的 `history` 还是会随着后续路由变化而改变（能直观的看到 `length` 在增加），导致页面还是会不断的重复渲染，也就是不受如下的 `StaticChildren` 组件的控制。

```tsx
class StaticChildren extends React.Component {
  shouldComponentUpdate() {
    return false;
  }

  render() {
    const { children } = this.props;
    return children;
  }
}
```

另，为没有子路由的页面组件都加上 `shouldComponentUpdate() { return false; }`，就不会受到任何外部因素的影响了，但这样很不优雅啊。
再另，刚才手滑又升级到 2.11.3 又出现这个问题了，所以这到底有没有个稳定的行为了？我太难了 \_(:3J∠)\_

如果要看实例可以克隆一下我的仓库 [ant-design-pro-v2-plus](https://github.com/theprimone/ant-design-pro-v2-plus) 打开头两个菜单后再在这两个标签页间切换即可，有问题的情况是切换时不停的打印，如果是 2.10.5 的话，切换的时候无任何打印的。

真正的总结（大概）：**已注入的页面组件中的 `history` 到底跟不跟着最新的 `history` 变化？**

**Comment by theprimone** [comment]
研究了一下，虽然行为上有一些不同，但是我在判断是否刷新 tab 的逻辑上的问题更大。
