### ISSUE TITLE
umi 如何将静态资源单独打包到 static 文件夹呢

### ISSUE THREAD

**Issue by liulinana** [umijs/umi#3644]
创建了最新版本的umi脚手架，但是umi build之后发现js,css,等静态资源都和html在同一级别下，想要把css放到一个文件夹，js放到一个文件夹，图片资源放到一个文件夹，然后整合到static文件夹下，找了官网api没有这中配置

**Comment by sorrycc** [comment]
不支持这种方式，构建产物为啥还要美观？

**Comment by ohhoney1** [comment]
> 不支持这种方式，构建产物为啥还要美观？

有时候是直接适配后端的一些框架

**Comment by fantasy525** [comment]
建议支持，要不然这种
<img width="114" alt="image" src="https://user-images.githubusercontent.com/22516157/206640009-427b613e-2705-4213-acf2-933caf344e0d.png">
很丑，同时也不太配合后端，更多是想有个 static和index.html同级，然后static里面区分js img css等文件夹
