### ISSUE TITLE
pages里面添加文件了，但是路由不起作用，没有自动生成

### ISSUE THREAD

**Issue by xishanxu** [umijs/umi#3645]
1.
![image](https://user-images.githubusercontent.com/43942406/69040233-6e141180-0a28-11ea-9a7a-df58521ae7e5.png) 
pages里面配置了路由没有起作用

2. layouts 的index中配置了 props.children
![image](https://user-images.githubusercontent.com/43942406/69040323-969c0b80-0a28-11ea-9eae-78830fcf1f43.png)
3. 但是在页面中 找不到我pages中添加的路由， 打开.umi 文件夹中的路由文件，也没有自动生成，重启了很多次项了 没有用
![image](https://user-images.githubusercontent.com/43942406/69040444-c64b1380-0a28-11ea-9c97-9f8fe783cb2d.png)

 
## Context
希望此问题能够被解决，不然项目写不下去了

- **Umi Version**:
    "umi": "^2.9.0",
    "umi-plugin-react": "^1.8.0",
    "umi-types": "^0.3.0"
- **Node Version**: 最新
- **Platform**:

**Comment by liulinana** [comment]
如果项目里.umirc.ts或者.umirc.js文件中配置了routes 属性，自动路由将会不起作用，创建页面也就不会自动添加路由了

**Comment by liulinana** [comment]
.umirc.ts或者.umirc.js文件中配置了routes属性是自己手动配置路由的标志，
![image](https://user-images.githubusercontent.com/34056781/69041746-fabfcf00-0a2a-11ea-95ab-9fdae0ff09ef.png)
routes里是自己手动配置的路由

**Comment by sorrycc** [comment]
配置式路由和约定式路由是二选一的。

**Comment by xishanxu** [comment]
已经删除了.umirc.ts中的routes，并且重新启动了项目，但是还是没有自动生成路由，不仅页面上不能跳转.umi 文件夹中routes还是没有生成路由


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liulinana"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 下午5:44
收件人:&nbsp;"umijs/umi"<umi@noreply.github.com&gt;;
抄送:&nbsp;"self"<825983767@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [umijs/umi] pages里面添加文件了，但是路由不起作用，没有自动生成 (#3645)




.umirc.ts或者.umirc.js文件中配置了routes属性是自己手动配置路由的标志，
 
 routes里是自己手动配置的路由

**Comment by xishanxu** [comment]
不好意思，没有删除干净 还有routes


------------------ 原始邮件 ------------------
发件人:&nbsp;"liulinana"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 下午5:44
收件人:&nbsp;"umijs/umi"<umi@noreply.github.com&gt;;
抄送:&nbsp;"self"<825983767@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [umijs/umi] pages里面添加文件了，但是路由不起作用，没有自动生成 (#3645)




.umirc.ts或者.umirc.js文件中配置了routes属性是自己手动配置路由的标志，
 
 routes里是自己手动配置的路由

**Comment by pxim** [comment]
![image](https://user-images.githubusercontent.com/5111701/151494128-e856b6dc-458d-4f43-b2be-12ff74f401a7.png)
![image](https://user-images.githubusercontent.com/5111701/151494216-d2ab0497-2d44-4f28-b7bf-9d8f56af660b.png)
![image](https://user-images.githubusercontent.com/5111701/151494155-25d28ce8-3747-4cc7-b47a-e26e4832408b.png)

![image](https://user-images.githubusercontent.com/5111701/151494278-b455fd7f-976f-4fd4-a08f-379bbe3110a9.png)


完全对不上
