### ISSUE TITLE
在umi + ts + antd 项目当中使用高阶组件后传参vscode报错的问题

### ISSUE THREAD

**Issue by xishanxu** [umijs/umi#3647]

**Expected behavior**
 我一个组件，使用了antd的Form.create来包裹，然后暴露出去了，然后我在另外一个组件中引入这个组件，可以正常使用，但是我传参过去，因为Form.create这个函数中我没有办法写接口，所有在使用包装之后的高阶组件之后，vscode会报错
图一是使用的时候报的错：
![image](https://user-images.githubusercontent.com/43942406/69044853-a61f5280-0a30-11ea-97cc-024292bc37d3.png)

图二是暴露出去的组件
![image](https://user-images.githubusercontent.com/43942406/69044916-c3542100-0a30-11ea-8ff2-f8910ca119b3.png)
项目可以使用可以正常跑起来

## Context

- **Umi Version**:
    "umi": "^2.9.0",
    "umi-plugin-react": "^1.8.0",
    "umi-types": "^0.3.0"
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
和 umi 无关，编辑器配置和 ts 问题。
