### ISSUE TITLE
在umi + ts 项目中使用less，引入less，然后vscode中报错，说找不到模块的问题，但是可以正常使用

### ISSUE THREAD

**Issue by xishanxu** [umijs/umi#3648]
1.在umi + ts 项目中使用less，引入less，然后vscode中报错，说找不到模块的问题，但是可以正常使用

![image](https://user-images.githubusercontent.com/43942406/69045475-dfa48d80-0a31-11ea-8ecc-5d3ea89f46fc.png)

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by laixstx** [comment]
在 typings.d.ts 加入这一句就行了：

![image](https://user-images.githubusercontent.com/10735940/69046551-314e1780-0a34-11ea-9509-05eddab49a1d.png)

**Comment by laixstx** [comment]
https://github.com/umijs/umi/issues/2322#issuecomment-486944137
