### ISSUE TITLE
使用umi-plugin-locale的setLocale Api，antd组件的文字没有根据locale修改

### ISSUE THREAD

**Issue by Adherentman** [umijs/umi#3656]
## What happens?
当使用setLocale的Api时，antd组件没有跟着修改文字内容。

## Mini Showcase Repository(REQUIRED)
![umi-localeBug](https://user-images.githubusercontent.com/26477346/69121406-3fa13f80-0ad7-11ea-9799-a198bb333ff0.png)
![umi-bug](https://user-images.githubusercontent.com/26477346/69121419-4def5b80-0ad7-11ea-93e2-330443e88be7.png)

![屏幕截图](https://user-images.githubusercontent.com/26477346/69121459-63fd1c00-0ad7-11ea-921b-613d4955a72f.png)

## How To Reproduce
**Steps to reproduce the behavior:**
1.setLocale("en-US")

**Expected behavior**
1.antd的组件应该渲染跟ant里configprovider里的example一样

## Context

- **Umi Version**: 2.11.3
- **Node Version**: 10.13.0
- **Platform**: mac

**Comment by ycjcl868** [comment]
给个复现 demo

**Comment by Adherentman** [comment]
> 给个复现 demo

https://github.com/Adherentman/umiBugReport

可以clone 然后yarn -> yarn start

**Comment by Adherentman** [comment]
@ycjcl868 你好，这个demo可以满足调bug吗？如果不够我可以再写点东西

**Comment by Adherentman** [comment]
@ycjcl868 我将代码改为umi-plugin-locale里的`example`还是不行。
![屏幕截图_2](https://user-images.githubusercontent.com/26477346/69520114-b1293400-0f96-11ea-9b07-3c1055c9347e.png)

随后我下载了antd-pro。我将umi 和umi-plugin-react的版本和antd-pro生成的版本统一，也依然不行。。求解。。

**Comment by JiangMengLei** [comment]
> @ycjcl868 我将代码改为umi-plugin-locale里的`example`还是不行。
> ![屏幕截图_2](https://user-images.githubusercontent.com/26477346/69520114-b1293400-0f96-11ea-9b07-3c1055c9347e.png)
> 
> 随后我下载了antd-pro。我将umi 和umi-plugin-react的版本和antd-pro生成的版本统一，也依然不行。。求解。。

你看下切换语言之后，localstage中是zh-CN还是en-US?

**Comment by JiangMengLei** [comment]
> > @ycjcl868 我将代码改为umi-plugin-locale里的`example`还是不行。
> > ![屏幕截图_2](https://user-images.githubusercontent.com/26477346/69520114-b1293400-0f96-11ea-9b07-3c1055c9347e.png)
> > 随后我下载了antd-pro。我将umi 和umi-plugin-react的版本和antd-pro生成的版本统一，也依然不行。。求解。。
> 
> 你看下切换语言之后，localstage中是zh-CN还是en-US?

我试了下你的demo，添加locales文件夹及下的en、zh文件之后，切换有效了。可能得需要这两个文件的支持？

**Comment by ycjcl868** [comment]
locale: {
   antd: true,
  ...
}

**Comment by Adherentman** [comment]
@JiangMengLei 感谢添加了locales文件夹后确实有效。
@ycjcl868 并且我将`antd:true`去掉了也是有效的。
再次感谢二位🙏
