### ISSUE TITLE
使用动态路由时 lint-staged 如何匹配校验

### ISSUE THREAD

**Issue by CooCleC** [umijs/umi#3658]
![WeChat3ca0ca39d0285cc921082b53de734983](https://user-images.githubusercontent.com/29189543/69125449-cc9cc680-0ae0-11ea-9081-7cbc5734bfa7.png)

动态路由不被识别，路径变为// ，lint-stage检查报错，请问这个怎么解决？？

**Comment by sorrycc** [comment]
感觉是个问题，我们需要调整下动态路由的规则。

**Comment by caosm** [comment]
Any update please.

Is't enough to modify this file - [getRouteConfigFromDir.js](https://github.com/umijs/umi/blob/master/packages/umi-build-dev/src/routes/getRouteConfigFromDir.js#L90) ?
