### ISSUE TITLE
umi框架搭建的react项目启动报错 error  in ./app/web/src/pages/.umi/router.js

### ISSUE THREAD

**Issue by DaneeLee** [umijs/umi#3660]
### npm install 成功，npm run dev失败
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                        16:52:41
 error  in ./app/web/src/pages/.umi/router.js

Module parse failed: Unexpected token (33:13)
File was processed with these loaders:
 ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   "component": (0, _dynamic2.default)({
|     component: function component() {
       return import('../../layouts/Layout');
|     },
|     LoadingComponent: require('/mnt/e/git_mec/aviv-dashboard/app/web/src/components/PageLoading/index').default

 @ ./app/web/src/pages/.umi/umi.js 90:57-76 200:2-202:4
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./node_modules/umi-build-dev/template/setPublicPath.js ./app/web/src/pages/.umi/umi.js

**Comment by ycjcl868** [comment]
重装 node_modules
