### ISSUE TITLE
Static image not display

### ISSUE THREAD

**Issue by wmtjaychhatrola** [umijs/umi#3661]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1.[
  {
        "image_url": "../static/agentlisting/6_9.jpg"
  },
]
2.

<img src{data.image_url} />
can't display image
**Expected behavior**
1. want to display image in img tag using direct path

## Context

- **Umi Version**:2.7.7
- **Node Version**: 10
- **Platform**:react

**Comment by aixfox** [comment]
```javascript
import image from '[image path]';

<img src={image} />
```
