### ISSUE TITLE
This is a issue of umi-request

### ISSUE THREAD

**Issue by xialvjun** [umijs/umi#3668]
## What happens?

https://github.com/umijs/umi-request/blob/master/src/middleware/parseResponse.js#L35-L43

明明有 copy 不消耗, 去消耗原 res, 导致用户自己  request.use 增加的 middleware 不能再次读取 res.body... 或许可以在 `request.interceptors.response.use` 里面写自己的 middleware, 里面的顺序可能比 parseResponseMiddleware 快一步, (我不知道, 没仔细看源代码), 但总归 parseResponseMiddleware 消耗了 res 导致 res 之后不能再被读取应该就是一个代码缺陷. 望修改.

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by chenjsh36** [comment]
umi-request 默认对 200 的响应 response 做处理、解析，所以通过 request.use 拿到的是解析、处理后的 response.body 内容；
如果开发者需要自行解析，umi-request 提供了两种方式：

1、配置 **getResponse** 为 true，umi-request 会同时返回原始 response 的拷贝对象和解析处理后的 response.body：
```javascript
    server.get('/test/a', (req, res) => {
      writeData(req.query, res);
    });

    const req = extend({
      getResponse: true
    })

    const res = await req(prefix('/test/a'), { params: { user: 'a' }})
    const { data, response } = res;
    const text = await response.text()

    expect(data).toStrictEqual({ user: 'a' });
    expect(text).toBe('{\"user\":\"a\"}');
```

2、配置 **parseResponse** 为 false，跳过默认处理，开发者自行解析处理 response

```javascript
request('/api/a', {
  parseResponse: false,
})
  .then(function (response) {
    console.log(response.text());
  })
  .catch(function (error) {
    console.log(error);
  })
```

**Comment by xialvjun** [comment]
明白了, 可以通过 catch 的 error 拿 copy response 和 解析出来的 data, 也可以配置 `getResponse: true` ... 其实我之前的场景是服务器会返回 401 的 json 响应, 我客户端需要看 json 里的内容来决定统一做什么....所以:
```js
request.use(async (ctx, next) => {
  try {
    await next();
  } catch (e) {
    // 根据 ctx.res 或 e 做点什么, 例如跳转登录页, 所以期望如果 之前的中间件 throw 了, 就本不应该消耗 res_body... 如果没 throw, 那就  const res = await next(); 再根据 res 决定是否跳转...
    // 就这样, 这里我只提供个自己的使用场景, 你们自己思考自己的代码逻辑顺序是否合理
  }
});
```
