### ISSUE TITLE
不知道是不是 babel-plugin-import的问题

### ISSUE THREAD

**Issue by pengfeiWang** [umijs/umi#367]
问题

包a, 依赖 antd,  包 a 发布发布到 npm, 供项目使用

项目b,  依赖 包a, 使用 包a时样式丢失

我的想法是包a, 与项目b 都依赖 antd, 包a中的antd不做过多处理, 通过项目b的配置来处理相关依赖

目的是减少项目b最终体积, 如果包a, 把依赖打进包里的话, b中也会有相同的antd依赖时, 会出现重复的样式代码

**Comment by sorrycc** [comment]
* a 不打包 antd
* 样式不生效原因是 babel-plugin-import 针对 a 不生效，为 a 配 extraBabelIncludes 即可
