### ISSUE TITLE
怎么样在umi配置式路由实现假如一个都没有匹配到 然后进入默认页面？

### ISSUE THREAD

**Issue by ManuRodgers** [umijs/umi#3676]
![image](https://user-images.githubusercontent.com/33333844/69280963-8314be80-0c3b-11ea-9a9f-8068cab859a9.png)
就是实现类似上图如果前面一个都没有匹配 就redirect到指定页面

**Comment by sorrycc** [comment]
配下 `disableRedirectHoist: true`，参考 https://umijs.org/config/#disableredirecthoist 。

**Comment by wwjd2016** [comment]
在最后写一个path="*"或者没path属性的Route
