### ISSUE TITLE
[umi-plugin-dll] 更新 dependencies 依赖的版本后，umi.dll.js 不会更新

### ISSUE THREAD

**Issue by deswan** [umijs/umi#3679]
项目里启用了 dll 特性，npm install 更新 dependencies 依赖的版本后，umi.dll.js 文件不会更新，所以运行看到的还是旧版本依赖。

这个判断dll文件是否需要更新的逻辑是否有问题？或者有没有方便的办法在依赖版本更新时重新生成 dll 文件？

**Comment by sorrycc** [comment]
是需要改进的点。
