### ISSUE TITLE
umi-test在引入jest testEnvironment时报错

### ISSUE THREAD

**Issue by webup** [umijs/umi#368]
通过jest.config.js引入自定义的testEnvironment后，会在https://github.com/umijs/umi/blob/master/packages/umi-test/src/setupTests.js#L12 这里报错，发现这里 global.window变成undefined了，而不引入时是正常有值的。 @sorrycc

**Comment by sorrycc** [comment]
怎么重现？或者有兴趣直接提个 PR 修复？

**Comment by webup** [comment]
重现很简单，我下午试试能不能修复吧

**Comment by webup** [comment]
按这个可以解决 https://stackoverflow.com/questions/43960608/setting-up-jsdom-with-mocha
```javascript
const dom = new JSDOM('<!DOCTYPE html><html><head></head><body></body></html>');

global.window = dom.window;
global.document = dom.window.document;
```
