### ISSUE TITLE
关于 whatwg-fetch 的引入

### ISSUE THREAD

**Issue by Grewer** [umijs/umi#3680]
## What happens?

新建 umi 项目后,初始化项目,打包测试 ANALYZE ,发现有 whatwg-fetch 被引用,但其实我并不需要这个库

## 最小可复现仓库

新建项目打包即可

**Comment by sorrycc** [comment]
umi 内部没有依赖这个，分析下是哪里引入的。

**Comment by sorrycc** [comment]
分析 build 环境的，dev 环境时会引入一些额外的辅助依赖。

**Comment by Grewer** [comment]
具体情况:  
配置
```
? Select the boilerplate type app
? Do you want to use typescript? Yes
? What functionality do you want to enable? antd, dva, code splitting, dll
```
之后 ` yarn`

再 `ANALYZE=1 umi build`
bundle analyze 里就有这个库了

搜索了一下,发现 umi-build-dev/src/plugin/404/NotFound.js 里面引入了

@sorrycc

**Comment by sorrycc** [comment]
试了下，发现是 dva 引入的，好像 tree-shaking 没有生效，我排查下。
