### ISSUE TITLE
umi-request requestType: form 参数格式bug

### ISSUE THREAD

**Issue by asevenm** [umijs/umi#3681]
## What happens?
post 方法以requestType: form格式提交数据时formData如下（intergrations为数组）：
`
id: 1676,
intergrations[0]: 688,
intergrations[1]: 687,
`
导致后端解析参数intergrations失败

**Expected behavior**
id: 1676,
intergrations: 688,
intergrations: 687,

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by chenjsh36** [comment]
新版本已经修复该问题，请更新下依赖库

**Comment by asevenm** [comment]
> 新版本已经修复该问题，请更新下依赖库

好的
