### ISSUE TITLE
[请教大神]如何去除登录模块？

### ISSUE THREAD

**Issue by Icefr09** [umijs/umi#3686]
写一个学校project想用umi做前端，然而create project后可以umi dev但是本地serve或部署服务器后，api都会出问题。user/ant.design这套用户和密码也无法登录，点注册也返回404，好像是因为dev模式下有mock用户而serve的时候没有。以下为本地错误信息

请求错误 404: http://localhost:5000/api/currentUser
发出的请求针对的是不存在的记录，服务器没有进行操作。

请问这种情况是要怎么解决呢？（我猜测是要建立api连接数据库什么的储存用户信息，然后在调用的时候返回数据给前端？） 或者如何整体去除用户登录模块，就简单地制作一个用来展示信息给所有用户（不用登陆）的前端呢？（project主要是在aws上处理数据什么的，前端可以简单一点）

万分感谢！

**Comment by xiaohuoni** [comment]
虽然我哦不知道你在说什么，但是我猜你用的是[ant design pro](https://github.com/ant-design/ant-design-pro) 这个项目，最简单的不需要登录，可以设置 `ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION ` ，当然比较好的方式是，搜索一下 `ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION `,看看它做了什么，做相应的处理。

**Comment by Icefr09** [comment]
> 虽然我哦不知道你在说什么，但是我猜你用的是[ant design pro](https://github.com/ant-design/ant-design-pro) 这个项目，最简单的不需要登录，可以设置 `ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION ` ，当然比较好的方式是，搜索一下 `ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION `,看看它做了什么，做相应的处理。

抱歉第一次用很多地方没弄清楚，描述也十分混乱，确实是用的ant design pro，感谢您的帮助，我试试
