### ISSUE TITLE
[编译问题]

### ISSUE THREAD

**Issue by lovelywoman** [umijs/umi#3691]
项目有两块大的逻辑代码，是否能够将这两块代码分别build到dist文件中的两个文件夹中，公共代码单独编译。umi2.0是否支持这种方式，如果可以要怎么做呢？

**Comment by sorrycc** [comment]
需要你自己搜 webpack code splitting，调整代码组合策略。

**Comment by lovelywoman** [comment]
我配置了config.js 中chainWebpack，设置了optimization.splitChunks({cacheGroups}), 做了 vendors 依赖提取之后,并配置了plugins: [ ['umi-plugin-react', {chunks: ['vendors', 'umi'] }]，但页面打开时空白，没有引用到编译的包。请问这是哪里没有配置正确还是配置项更改了。
