### ISSUE TITLE
build时，能否打包一个js（css，js都在里面）

### ISSUE THREAD

**Issue by liming8077** [umijs/umi#3694]
目前没有找到解决办法，希望帮忙解决一下。

**Comment by sorrycc** [comment]
这么做的原因是啥？

**Comment by liming8077** [comment]
想在传统的html页面引入一个打包好的js（可以看做一个组件）&nbsp;








李明
东方网升


 联系我









&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "chencheng (云谦)"; 
Date: 2019年11月26日(星期二) 中午11:43
To: "umijs/umi"; 
Cc: "liming8077"; "Author"; 
Subject: Re: [umijs/umi] build时，能否打包一个js（css，js都在里面） (#3694)

&nbsp;

这么做的原因是啥？

**Comment by sorrycc** [comment]
用组件打包方案，可以考虑 father-build。

**Comment by liming8077** [comment]
.umirc.js配置已经解决，谢谢。
有时间我再试下您给的方案。谢谢
&nbsp;








李明
东方网升


 联系我









&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "chencheng (云谦)"; 
Date: 2019年11月29日(星期五) 下午2:21
To: "umijs/umi"; 
Cc: "liming8077"; "Author"; 
Subject: Re: [umijs/umi] build时，能否打包一个js（css，js都在里面） (#3694)

&nbsp;

用组件打包方案，可以考虑 father-build。
