### ISSUE TITLE
配置型路由，修改路由时不会自动重新编译，路由404

### ISSUE THREAD

**Issue by wwjd2016** [umijs/umi#3695]
## What happens?
1、使用了配置型路由，路由的定义在另外的文件中定义
2、在.umirc.js中引入
3、然后在路由文件中新增一个路由/test，访问，报404
4、重新start，正常

## Context

- **Umi Version**: ^2.7.7
- **Node Version**: v10.15.3
- **Platform**: MacOs

**Comment by sorrycc** [comment]
路由文件在哪？`.umirc.js` 和 `config` 目录会做监听，其他的没有监听。

**Comment by leftstick** [comment]
@wwjd2016 问题应该在这了 `使用了配置型路由，路由的定义在另外的文件中定义`，你的这个`另外的文件`应该不在监听范围，我觉得如果放到`src`下面，应该可以。试试呗

**Comment by xiaohuoni** [comment]
不方便移动文件的话，也可以写一个自定义插件，通过填加文件监听来实现
`api.addPageWatcher(['xxx.js', '*.mock.js']);`

**Comment by wwjd2016** [comment]
> 路由文件在哪？`.umirc.js` 和 `config` 目录会做监听，其他的没有监听。

路由文件是在src下单独的文件夹里，在.umirc中引入的

**Comment by wwjd2016** [comment]
> @wwjd2016 问题应该在这了 `使用了配置型路由，路由的定义在另外的文件中定义`，你的这个`另外的文件`应该不在监听范围，我觉得如果放到`src`下面，应该可以。试试呗

是在src下的

**Comment by sorrycc** [comment]
umi@3 解决。
