### ISSUE TITLE
当项目是typescript的时候, 在babel-preset里面的有一些proposal使用不了

### ISSUE THREAD

**Issue by phpmaple** [umijs/umi#3700]
例如 @babel/plugin-proposal-pipeline-operator
使用js的时候webpack打包没问题， ts的时候会报语法错误，应该是tsc不能解析，但是babel是可以支持的，这时候如何配置呢

**Comment by sorrycc** [comment]
typescript 会先走 tsc，再走 babel，所以只能用 tsc 支持的语法特性。
