### ISSUE TITLE
动态创建script标签设置src为本地文件的问题

### ISSUE THREAD

**Issue by wzh0823** [umijs/umi#3704]
请问一下，我这里动态创建script标签设置src为本地文件，但网络请求确是路由？
`
      const lessScriptNode = document.createElement('script');
    lessScriptNode.setAttribute('src', '../../assets/less.min.js')`

**Comment by leftstick** [comment]
`src为本地文件的意思`，我猜就是你写的`../../assets/less.min.js`吧？

还是那句话，你确定你知道HTML的script标签上，src属性的值是怎么工作的么？这个不是umi的问题，是你的HTML基本功的问题哦

**Comment by wzh0823** [comment]
> `src为本地文件的意思`，我猜就是你写的`../../assets/less.min.js`吧？
> 
> 还是那句话，你确定你知道HTML的script标签上，src属性的值是怎么工作的么？这个不是umi的问题，是你的HTML基本功的问题哦

这样写有什么问题吗，HTML的script标签本地文件不是也可以吗
