### ISSUE TITLE
[UMI UI] read package.json failed

### ISSUE THREAD

**Issue by afc163** [umijs/umi#3709]
<img width="842" alt="image" src="https://user-images.githubusercontent.com/507615/69704963-89210880-112f-11ea-9ace-e15cbf7421ca.png">

**Comment by xiaohuoni** [comment]
看起来是没在项目目录下执行？

**Comment by afc163** [comment]
这东西不需要在项目目录下执行的。

**Comment by afc163** [comment]
合并到 #4479
