### ISSUE TITLE
SSR warning: Did not expect server HTML to contain a <div> in <div>

### ISSUE THREAD

**Issue by hkhere** [umijs/umi#3711]
## What happens?
浏览器访问ssr服务时，会看到 Warning: Did not expect server HTML to contain a &lt;div&gt; in &lt;div&gt;的提示,

浏览器刷新或第一次进入页面会闪两次

## 最小可复现仓库
[umi-server/examples/koajs](https://github.com/umijs/umi-server/tree/master/examples/koajs)
> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
default

## 相关环境信息

- **Umi 版本**：2.12.3
- **Node 版本**：12.13.1

**Comment by hkhere** [comment]
@ycjcl868 请看一下，这个和dynamicImport有关，开起来就会出现这些情况

**Comment by elivoa** [comment]
开dynamicImport就会有这个问题。

**Comment by hkhere** [comment]
@ycjcl868 关闭dynamicImport会有另外严重问题，这样ssr没法用， 是否考虑优先处理一下。

关闭dynamicImport，页面如果有useEffect或者componentDidMount改变props会导致页面无限render。重现 官方 umi-server examples里面的express，关掉dynamicImport，打开devtools可以看到一直在重复发送请求

**Comment by zhangyuang** [comment]
并不会重复发请求,你useEffect忘记传第二个参数了吧

**Comment by hkhere** [comment]
@zhangyuang 官方那个，并没有修改代码，只修改配置关闭dynamicImport

**Comment by ycjcl868** [comment]
dynamicImport 现在有两层，一层是路由、还有一层是 dva，待解决。

https://github.com/umijs/umi/pull/3348
