### ISSUE TITLE
为何全局layout的render会执行两次？

### ISSUE THREAD

**Issue by sunyum** [umijs/umi#3712]
#3484  What happens?
src/layouts/index.js 全局路由的render方法会执行两次，可以看到 123 被打印了两次
![image](https://user-images.githubusercontent.com/20025971/69734433-edf95480-1169-11ea-913f-73ac9d59ac2f.png)

![image](https://user-images.githubusercontent.com/20025971/69734244-9c50ca00-1169-11ea-8bf7-25a5b06dfa0a.png)

![image](https://user-images.githubusercontent.com/20025971/69734462-f6518f80-1169-11ea-8a71-b4100827399f.png)

**Comment by sunyum** [comment]
知道为什么，因为用了dva，添加了全局model，所以组件update了

**Comment by Stephen526** [comment]
@sunyum 如果要用全局model，怎么解决这个问题呢
