### ISSUE TITLE
无法正确添加 fetch 的 polyfill

### ISSUE THREAD

**Issue by Youjingyu** [umijs/umi#3714]
## What happens?
配置 targets 如下：
```js
// .umirc.js
{
  targets: {
    "android":"4.4"
  },
  plugins：[
    ['umi-plugin-react', {

    }]
  ]
}
```
打包结果中没有添加 fetch 的 polyfill。
修改配置，添加 dva：
```js
// .umirc.js
{
  targets: {
    "android":"4.4"
  },
  plugins：[
    ['umi-plugin-react', {
      dva: true
    }]
  ]
}
```
 打包结果中正确添加了 fetch 的 polyfill。
## Mini Showcase Repository(REQUIRED)

直接用 umi 脚手架创建的项目即可复现

## Context

- **Umi Version**: ^2.11.1
- **umi-plugin-react Version**: ^1.13.1
- **Node Version**: v10.8.0
- **Platform**: mac

**Comment by sorrycc** [comment]
https://github.com/zloirock/core-js/issues/25
fetch 不包含在 core-js 的补丁方案里，需自行引入。

**Comment by Youjingyu** [comment]
那为什么配置了 ` dva: true ` 后就能添加 fetch 的 polyfill 的了呢？
是因为 dva 相关的包，自己引用了 fetch 的 polyfill 吗

**Comment by Youjingyu** [comment]
我感觉文档里应该说明配置 targets 后，哪些东西是不会被自动 polyfill 的

**Comment by sorrycc** [comment]
> 是因为 dva 相关的包，自己引用了 fetch 的 polyfill 吗

是的。

**Comment by sorrycc** [comment]
> 我感觉文档里应该说明配置 targets 后，哪些东西是不会被自动 polyfill 的

这个比较多，umi@3 时统一处理下。
