### ISSUE TITLE
引入less，想要直接写className="xxx"，但是打包后class并没有加hash后缀？

### ISSUE THREAD

**Issue by Wangyage1** [umijs/umi#3718]
1、引入less文件之后，想要直接写className="xxx" 而不是className={styles.xxx},  看了这个issue：https://github.com/umijs/umi/issues/1918   ，   发现写了global的话，打包后的class为'red', 而不是‘Header__red___1UdUE’  请问如何解决呢？

2、是否支持styleName呢？该如何配置？

**Comment by finalreturn** [comment]
都写了global，全局都是引这个，难道还去加前缀，每个地方引的地方都去生成一个。我觉得也是没必要的

**Comment by Wangyage1** [comment]
已解决， https://github.com/umijs/umi/issues/1417#issuecomment-530712214
