### ISSUE TITLE
building dll 报错

### ISSUE THREAD

**Issue by shenshanyoumu** [umijs/umi#3720]
dll: {
        exclude: [],
        include: ["dva", "dva/router", "dva/saga", "dva/fetch", "antd/es"],
      }

在package.json文件的dependencies字段引入了
 "koa": "^2.5.1",
    "koa-bodyparser": "^4.2.1",
    "koa-cors": "^0.0.16",
    "koa-ejs": "^4.2.0",
    "koa-multer": "^1.0.2",
    "koa-onerror": "^4.1.0",
    "koa-respond": "^1.0.1",
    "koa-router": "^7.4.0",
    "koa-static": "^5.0.0",
    "koa-unless": "^1.0.7",
    "koa-views": "^6.2.0",
    "koa2-validation": "^0.1.0",

Failed to compile with 34 errors                                                                                             11:13:59
These dependencies were not found:

* atpl in ./node_modules/consolidate/lib/consolidate.js
* bracket-template in ./node_modules/consolidate/lib/consolidate.js
* coffee-script in ./node_modules/consolidate/lib/consolidate.js
* dns in ./node_modules/isemail/lib/index.js, ./node_modules/mz/dns.js
* dot in ./node_modules/consolidate/lib/consolidate.js
* dustjs-linkedin in ./node_modules/consolidate/lib/consolidate.js
* eco in ./node_modules/consolidate/lib/consolidate.js
* ect in ./node_modules/consolidate/lib/consolidate.js
* haml-coffee in ./node_modules/consolidate/lib/consolidate.js
* hamlet in ./node_modules/consolidate/lib/consolidate.js
* hamljs in ./node_modules/consolidate/lib/consolidate.js
* hogan.js in ./node_modules/consolidate/lib/consolidate.js
* htmling in ./node_modules/consolidate/lib/consolidate.js
* jazz in ./node_modules/consolidate/lib/consolidate.js
* jqtpl in ./node_modules/consolidate/lib/consolidate.js
* just in ./node_modules/consolidate/lib/consolidate.js
* liquor in ./node_modules/consolidate/lib/consolidate.js
* marko in ./node_modules/consolidate/lib/consolidate.js
* module in ./node_modules/babel-core/lib/helpers/resolve.js, ./node_modules/npm-check/lib/in/find-module-path.js
* mote in ./node_modules/consolidate/lib/consolidate.js
* plates in ./node_modules/consolidate/lib/consolidate.js
* ractive in ./node_modules/consolidate/lib/consolidate.js
* readline in ./node_modules/mz/readline.js
* slm in ./node_modules/consolidate/lib/consolidate.js
* teacup/lib/express in ./node_modules/consolidate/lib/consolidate.js
* templayed in ./node_modules/consolidate/lib/consolidate.js
* toffee in ./node_modules/consolidate/lib/consolidate.js
* twig in ./node_modules/consolidate/lib/consolidate.js
* vash in ./node_modules/consolidate/lib/consolidate.js
* velocityjs in ./node_modules/consolidate/lib/consolidate.js
* walrus in ./node_modules/consolidate/lib/consolidate.js
* whiskers in ./node_modules/consolidate/lib/consolidate.js

To install them, you can run: npm install --save atpl bracket-template coffee-script dns dot dustjs-linkedin eco ect haml-coffee hamlet hamljs hogan.js htmling jazz jqtpl just liquor marko module mote plates ractive readline slm teacup/lib/express templayed toffee twig vash velocityjs walrus whiskers

 ERROR CODE  ERR_WEBPACK_DLL_MODULE_NOT_FOUND

**Comment by sorrycc** [comment]
后端应用需要在 dll 的 exclude 配置中排除掉。

**Comment by shenshanyoumu** [comment]
> 后端应用需要在 dll 插件的 exclude 配置中排除掉。

已修复，tks

**Comment by liuzyong** [comment]
怎么解决的？

**Comment by liuzyong** [comment]
> 后端应用需要在 dll 插件的 exclude 配置中排除掉。

能说的具体点吗
