### ISSUE TITLE
开启 lessLoader 开启 `javascriptEnabled` 不支持写函数，编译报错

### ISSUE THREAD

**Issue by jiechud** [umijs/umi#3721]
## What happens?
开启 lessLoader 开启 `javascriptEnabled` 不支持写函数, 配置文件如下：

```
  treeShaking: true,
  lessLoaderOptions: {
    javascriptEnabled: true,
  },
```
在less文件编写 function 函数， 如下

```
.remMixin() {
    @functions: ~`(function() {
      var clientWidth = '375px';
      function convert(size) {
        return typeof size === 'string' ?
          +size.replace('px', '') : size;
      }
      this.rem = function(size) {
        return convert(size) / convert(clientWidth) * 10 + 'rem';
      }
    })()`;
    }

.remMixin();
```

编译报错如下：
![image](https://user-images.githubusercontent.com/9709396/69844823-cfe63e00-12a8-11ea-93e6-cb277eadd5ff.png)

**Comment by ycjcl868** [comment]
umi 是默认开 `javascriptEnabled` 的，编译报错能给个复现吗？

https://github.com/umijs/umi/blob/master/packages/af-webpack/src/getWebpackConfig/css.js#L60

**Comment by jiechud** [comment]
是我的疏忽， umi 创建的项目，是css 文件，我在css 文件引入了 less function，所以报错， 现已解决， 谢谢
