### ISSUE TITLE
umi-plugin-cache-route 不生效

### ISSUE THREAD

**Issue by zyqq** [umijs/umi#3737]
照着工具说明用了没生效，
"umi": "^2.10.7",
"umi-plugin-cache-route": "^2.0.0",
"umi-plugin-react": "^1.12.8"
![image](https://user-images.githubusercontent.com/15664576/70140016-c60c7280-16ce-11ea-9609-ebd824a0797a.png)
![image](https://user-images.githubusercontent.com/15664576/70140027-ca389000-16ce-11ea-9711-16720dd2fc54.png)
![image](https://user-images.githubusercontent.com/15664576/70140037-ce64ad80-16ce-11ea-89eb-94beef311987.png)
看了下字段是有加上去的，但是点击订单详情再返回来时还是重新加载了列表
也执行了npm run init
![image](https://user-images.githubusercontent.com/15664576/70140073-dfadba00-16ce-11ea-918d-9776d1b8d678.png)

**Comment by zyqq** [comment]
@xiaohuoni

**Comment by xiaohuoni** [comment]
最新的不需要执行init 只需要安装玩插件，配置使用即可。
https://github.com/xiaohuoni/umi-antd-pro/pull/17/files

**Comment by xiaohuoni** [comment]
当前，只能简单的事情，对于嵌套路由的时候还存在bug。但是生效应该是没有问题的。
如果你还是无法生效，那可以给一个简单的重现demo

**Comment by pxim** [comment]
![image](https://user-images.githubusercontent.com/5111701/129825409-c519c6c1-3916-44c1-a276-176c66f164d3.png)

**Comment by CJY0208** [comment]
@pxim umi-plugin-cache-route 很长时间不维护了，现在可以换成 umi-plugin-keep-alive 试试
