### ISSUE TITLE
@umi qiankun 插件： 子应用的antd pro 样式丢失（可能是多个styled component 实例引发）

### ISSUE THREAD

**Issue by godismygirl** [umijs/umi#3744]
## What happens?
主应用和子应用都是umi antd pro, 使用umi qiankun插件搭建微前端。动态加载的子应用antd pro的样式丢失，但pro用到的antd组件样式又是ok的。控制台报多个styled component可能引发问题

## Mini Showcase Repository(REQUIRED)
复现仓库地址：

https://github.com/godismygirl/qiankunIssue.git

## How To Reproduce

1. communication 和portal文件夹下分别npm install 然后 npm start
2. 8000端口的portal主应用会在root slave节点加载子应用

**Expected behavior**
1.
2.

**Comment by kuitos** [comment]
duplicated with https://github.com/umijs/qiankun/issues/180
