### ISSUE TITLE
2019-12-6，yarn create umi 后，在IE与Edge中都报这个错误

### ISSUE THREAD

**Issue by ywy94ywy** [umijs/umi#3753]
![QQ截图20191206155000](https://user-images.githubusercontent.com/22499767/70305819-4c949180-1840-11ea-8839-78afb112996c.png)

**Comment by sym233** [comment]
ie和edge不支持Object.fromEntries方法，请用polyfill或换chrome/firefox

**Comment by chenshuai2144** [comment]
更新一下依赖，已经删掉了。
https://github.com/ant-design/ant-design-pro-layout/commit/4f2a368cbdf309ec1b2b2a0413380de6105bb053
