### ISSUE TITLE
SSR开dynamicImport报警告导致页面在客户端重新渲染，报错Warning: Did not expect server HTML to contain a...

### ISSUE THREAD

**Issue by elivoa** [umijs/umi#3757]
SSR之后dynamicImport选项打开，会造成服务端和客户端渲染不一致，导致客户端页面重新render。 新版umi这个问题也没有解决。开了就报错Warning: Did not expect server HTML to contain a <section> in <div>.

umi@2.12.6-beta.1 

umi-server egg的例子即可复现。

**Comment by hkhere** [comment]
这个问题不是反应过了吗？客户端hydrate的是LoadingComponent

**Comment by eevin** [comment]
ssr开启dynamicImport 后，页面骨架已经显示出来，待js load完毕后页面骨架消失，出现loadingComponent 组件，然后重新渲染页面。期待解决问题！
