### ISSUE TITLE
SSR 开发模式修改后build太慢

### ISSUE THREAD

**Issue by elivoa** [umijs/umi#3758]
在SSR工程中，每次修改内容会重新build umi.server.js，这个文件很大，导致等待时间特别长。
我的项目是20秒，而正常只需要6秒左右。

建议开发模式下避免这么大规模的build。

![image](https://user-images.githubusercontent.com/958954/70340016-ed0fa380-188a-11ea-81fe-976efeb1430d.png)

**Comment by zhangyuang** [comment]
你给的仓库都没有image文件夹。另外本地开发用npm run dev && NODE_ENV=development node ./server.js。静态资源访问路径是http://localhost:3000/dist/404.html这样的路径
