### ISSUE TITLE
service-worker.js 报错

### ISSUE THREAD

**Issue by smithyj** [umijs/umi#376]
本地开发环境没问题，好像 build 后就有问题
打开网址：https://test.crm.yangyj.com/login

然后报错：
```
A bad HTTP response code (404) was received when fetching the script.
service-worker.js Failed to load resource: net::ERR_INVALID_RESPONSE
```

**Comment by zhanchengkun** [comment]
同样的问题 怎么处理的？

**Comment by nba148** [comment]
build出来，和spingboot一起部署，报错service-worker.js Failed to load resource: the server responded with a status of 404 ()

**Comment by ycjcl868** [comment]
缓存问题，清缓存解决

**Comment by chenfengyanyu** [comment]
@ycjcl868 遇到了同样的问题，请问是如何解决的？
"umi": "2.5.1"
"umi-build-dev": "^1.2.6",
"umi-plugin-react": "^1.2.3"
