### ISSUE TITLE
umi 如何使用 useDispatch

### ISSUE THREAD

**Issue by birdycn** [umijs/umi#3760]
umi 如何使用 useDispatch，似乎没有导出这个钩子

**Comment by atzcl** [comment]
使用 2.6.0 beta 版本的 dva 就可以了

**Comment by birdycn** [comment]
> 使用2.6.0 beta版本的dva就可以了

2.6.0beta会提示 required 'dva' replace required dva/router
而且使用了2.6.0，然后在普通函数内使用UseDispatcha似乎没效果。

**Comment by sorrycc** [comment]
> 2.6.0beta会提示 required 'dva' replace required dva/router
> 而且使用了2.6.0，然后在普通函数内使用UseDispatcha似乎没效果。

这两个都不是问题。
