### ISSUE TITLE
在umi中使用：new Promise((resolve,reject)=>{reject()})，在network会重新加载“umi.js” "umi.js.map"

### ISSUE THREAD

**Issue by birdycn** [umijs/umi#3764]
在umi中使用：   
```
new Promise((resolve,reject)=>{
     reject()
    })
```
，会导致加载 “umi.js” "umi.js.map"

请问这是正常的吗？

**Comment by birdycn** [comment]
每次reject都会重新加载，这两个文件是干嘛的

**Comment by xiaohuoni** [comment]
在什么地方使用的？这是你的项目js代码的打包。

**Comment by leftstick** [comment]
需要完整示例，以及明确的复现步骤。详情可以参考贵司的QA提issue的流程和内容

**Comment by lishaoh** [comment]
> 在什么地方使用的？这是你的项目js代码的打包。

用的antd pro脚手架，比如中止http请求时，通过reject()达到中止请求目的，但此时network中会多次请求umi.js、umi.js.map文件

**Comment by xiaohuoni** [comment]
@lishaoh 提供个复现demo再reopen
