### ISSUE TITLE
viewport的属性无法修改

### ISSUE THREAD

**Issue by williamnie** [umijs/umi#3768]
## What happens?
![image](https://user-images.githubusercontent.com/26871884/70503707-fc2e7400-1b5e-11ea-81f0-6761a2b3ad2b.png)
通过在config里面配置umi-plugin-react的meta标签的配置项，无法改变viewport的属性，原因是在
umi-build-dev内部的document.ejs里面写死了两个meta标签

```
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no" />
<% if (context.title != null) { %>
  <title><%= context.title %></title>
<% } %>
</head>
<body>

<div id="<%= context.config.mountElementId %>"></div>

</body>
</html>

```
在这里不应该写死吧或者写死以后发现配置里面有viewpoint，就替换这个

**Comment by ycjcl868** [comment]
可以改的
