### ISSUE TITLE
umi supports prerender, isomorphic, server side render (SSR) ?

### ISSUE THREAD

**Issue by aletus** [umijs/umi#377]
Since umi is described as next.js like, does umi support prerendering of HTML pages when build?  

I tried the exportStatic option but it doesn't seem to prerender the page.

**Comment by sorrycc** [comment]
* prerender is planned to support
* ssr does not support, we do not need it

**Comment by aletus** [comment]
@sorrycc  I agree with umi build and static site hosting, SSR is not needed.  

However prerendering the initial HTMLs are really good to speed up the load time and also for search engine optimization SEO. Looking forward to get it added to umi.

I am also looking for a way to generate google [Accelerated Mobile Page AMP](https://www.ampproject.org/) when doing umi build.  

Right now I have to hand coded the AMP HTML separately and it is duplicated work.

**Comment by antenando** [comment]
I don't want to reopen this issue but I think this is the best place to ask this.

Is there a proper way I can make certain(s) page(s) SSR (maybe like config.openPages ?) server side renderable ?

In this case I'm looking for a way a page can be indexed by the web crawlers, i.e. Google.

**Comment by ycjcl868** [comment]
support ssr:  

https://github.com/umijs/umi-example-ssr  
https://github.com/umijs/umi-example-ssr-with-egg
