### ISSUE TITLE
umi从2.11.0版本开始开启dva后页面会刷新两次

### ISSUE THREAD

**Issue by williamnie** [umijs/umi#3774]
umi从2.11.0版本开始，如果开启dva选项以后，页面会render两次，api也会调用两次.一开始怀疑是dva问题，降级dva版本后不管用，开始尝试降级umi版本，找到问题。
复现代码在ya'suo'b压缩包内，希望尽快修复
[dva.zip](https://github.com/umijs/umi/files/3948255/dva.zip)

**Comment by sunyum** [comment]
确实，如果使用全局model，就会导致这个问题

**Comment by williamnie** [comment]
> 确实，如果使用全局model，就会导致这个问题

在2.11.0版本以前是没问题的，2.10.7升级到11以后会发生这个问题，

**Comment by ycjcl868** [comment]
dva 也有相应的升级

**Comment by sorrycc** [comment]
已在 https://github.com/dvajs/dva/releases/tag/dva%402.6.0-beta.17 修复。
