### ISSUE TITLE
dev模式publicPath不支持

### ISSUE THREAD

**Issue by wrfighting** [umijs/umi#3775]
umi dev模式下 publicPath设置了但是没起作用，
希望能支持dev模式下的publicPath设置

**Comment by sorrycc** [comment]
通过 chainWebpack 改。

**Comment by 1206646568** [comment]
就算是用 chainWebpack 改了umi.dll.js 也是没有变化的
另外变更后 umi.css umi.js 的路径确实被改变了，但内容还是有问题的

**Comment by sorrycc** [comment]
dll 和 publicPath 有啥关系？

**Comment by 1206646568** [comment]
因为部署在非根目录下
所以对开发环境的服务进行了代理。
因开发环境pubilcPath不生效，想通过chainwebpack改变资源的路径，发现只有dll. js的路径没有改变。
好吧，可能这个需要单独改。
另外修改后生成的umi. css文件内容不是css

我的配置是
chainWebpack:(cogfig) =>{config.output.publicPath('./')}

**Comment by wrfighting** [comment]
验证确实通过 chainWebpack 可以改  thks
