### ISSUE TITLE
Tree组件设置loadedKeys=[]，展开空目录时无限onload

### ISSUE THREAD

**Issue by Twighost** [umijs/umi#3779]
## What happens?

Tree组件设置loadedKeys=[]，想达到每次展开向后端请求的效果，结果展开空目录时无限onload；不应该用expanded判断是否load吗

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by ycjcl868** [comment]
问错地方了，https://github.com/ant-design/ant-design/issues 这里问
