### ISSUE TITLE
遵守了你们的路由约定，可是pages/pagename/*/*.js 这些还是被生成了路由

### ISSUE THREAD

**Issue by LamTech** [umijs/umi#3788]
如何解决这个问题呢？

pages下的所有service，models之类的都被自动生成了路由。

**Comment by sunyum** [comment]
同问，声明式路由，src/pages/login/下的model.js也被生成了路由
![image](https://user-images.githubusercontent.com/20025971/71322886-bf239380-2507-11ea-8915-629856081d22.png)

**Comment by dxd1102** [comment]
放在pages外面。。。

**Comment by sunyum** [comment]
> 放在pages外面。。。

重点不是放没放在外边
![image](https://user-images.githubusercontent.com/20025971/71387693-f2614200-262f-11ea-931a-24a7abd634cb.png)
