### ISSUE TITLE
Umi local可否提供一个接口或则方法，从后台获取相关多语言配置的内容？

### ISSUE THREAD

**Issue by crashsol** [umijs/umi#3789]
目前有一部分多语言内容是后端在管理，可否提供一个api，允许从后台请问相关多语言的配置，这样也方便对页面中多语言显示的内容进行管理和修改？

**Comment by xiexingen** [comment]
支持

**Comment by imhele** [comment]
https://github.com/onpaik/umi-lib-paik/tree/master/packages/umi-plugin-locale-paik
