### ISSUE TITLE
umi升级1.2.1之后的路由问题

### ISSUE THREAD

**Issue by ppxu** [umijs/umi#379]
比如这样的路由结构，pages/message/index.js，
升级之前访问页面 /message 是可以正常访问，
升级之后 /message 是空白页了，必须 /message/ 这样才能打开，
我看了 .umi/router.js 的内容都是一样的，为什么会有这个问题

**Comment by sorrycc** [comment]
我在 https://github.com/umijs/umi-examples/tree/master/routes 试了下，/list 这个路由可以访问到。给个可重现的例子吧，理论上没配 strict 这两个路由是等价的。

**Comment by amily4555** [comment]
这个问题我也出现过
/message 只显示 layout/layout.js 的内容，但不显示children 内容
我怀疑是不是 嵌套路由 造成的问题~ 
望查之

**Comment by sorrycc** [comment]
给可重现的库才能排查啊。

**Comment by ppxu** [comment]
可重现的例子：https://github.com/ppxu/data-insight
安装启动后，http://localhost:8080/#/imports/task，http://localhost:8080/#/imports/source，http://localhost:8080/#/message，均不能访问正确的页面，要加个 / 才能打开

**Comment by xiaohuoni** [comment]
@sorrycc 将文件夹下的index.js 重命名为page.js就可以正常访问

**Comment by ppxu** [comment]
@xiaohuoni 换成 page.js 确实可以了，看了下是生成的 router.js 变了
```
{
  "path": "/message",
  "exact": true,
  "component": require('../message/page.js').default
}

{
  "path": "/message/",
  "exact": true,
  "component": require('../message/index.js').default
}
```

**Comment by xiaohuoni** [comment]
应该算bug吧，等大佬修复。之前index和page都是可以的

**Comment by sorrycc** [comment]
发现是加了 umi-plugin-dva 之后就严格匹配了。

**Comment by jdreamer** [comment]
这个版本更新的，，，，很，，，让人，纠结啊。
我也有router的问题，凡是有 $id 这种路径的，都不能访问
比如我有一个文件
/src/pages/user/$id/detail.js
之前访问
http://hostname/user/1/detail 是可以的，更新1.2.1之后不能用了，报404

**Comment by jdreamer** [comment]
看router.js文件，之前会把$id映射成:id，新版本映射成了$id。

**Comment by xiaohuoni** [comment]
**发现是加了 umi-plugin-dva 之后就严格匹配了，原因待查。**
这个原因，可能是因为增加了path-to-regexp
我把'path-to-regexp': require.resolve('path-to-regexp'),注释掉就可以了
```js
api.register('modifyAFWebpackOpts', ({ memo }) => {
    memo.alias = {
      ...memo.alias,
      dva: dirname(require.resolve('dva/package')),
      'dva-loading': require.resolve('dva-loading'),
      'path-to-regexp': require.resolve('path-to-regexp'),
      'object-assign': require.resolve('object-assign'),
      ...(opts.immer
        ? {
            immer: require.resolve('immer'),
          }
        : {}),
    };
    return memo;
  });
```
@sorrycc

**Comment by sorrycc** [comment]
@xiaohuoni 👍，那和 #378 是同一个问题了。

**Comment by sorrycc** [comment]
在 #378 继续跟进。
