### ISSUE TITLE
[Feature Request] umi-plugin-qiankun里面如何将两个子应用合并在主应用显示

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#3790]
## Background

![image](https://user-images.githubusercontent.com/7939085/70856971-ff3fb080-1f20-11ea-8620-c96e1db37e5b.png)

这种在这里面有没办法实现

**Comment by kuitos** [comment]
菜单由主应用来画就可以了

**Comment by dkvirus** [comment]
@kuitos  登录操作如何做？也交给主系统来做嘛？要是子系统1通过 token 认证，子系统2 通过 sessionId，那么主系统就不好处理。

如果强行规定只能用一种认证方式，那么子系统就没那么独立了。

**Comment by kuitos** [comment]
权限认证应该是一种公司通用的基础设施，比如都是 oauth 2.0 这种。认知方式都不一样。。基本可以断定是整个业务架构都有问题了
