### ISSUE TITLE
[Umi UI] 项目名样式问题

### ISSUE THREAD

**Issue by afc163** [umijs/umi#3792]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/507615/70859652-1fd42e80-1f52-11ea-8676-f17167fa54b9.png">

`umi@2.12.5`

**Comment by afc163** [comment]
<img width="224" alt="image" src="https://user-images.githubusercontent.com/507615/70860098-2ebddf80-1f58-11ea-91b1-e6c2983192b0.png">

弹层也有问题。

**Comment by ycjcl868** [comment]
记得修过了 https://github.com/umijs/umi/pull/3767/files#，要重装下 node_modules

![image](https://user-images.githubusercontent.com/13595509/70877828-16060600-1ffa-11ea-82e0-86e6fe12ed4e.png)
