### ISSUE TITLE
[Feature Request] 国际化如何为 ant design 添加一个不存在的语言？比如 zh-HK

### ISSUE THREAD

**Issue by liuzhaowei55** [umijs/umi#3794]
比如我在项目中添加了 zh-HK 语言，umi 自动关联 ant 多语言时并不存在 zh_HK，我该如何为 ant 也添加一套多语言？

**Comment by ycjcl868** [comment]
https://github.com/ant-design/ant-design/blob/master/components/locale/zh_TW.tsx
