### ISSUE TITLE
Uncaught (in promise) TypeError: api.addDashboard is not a function

### ISSUE THREAD

**Issue by PmcFizz** [umijs/umi#3795]
![image](https://user-images.githubusercontent.com/13403284/70882166-ca5b5880-2009-11ea-8161-7542d7b24634.png)

**Comment by ycjcl868** [comment]
You should use call `api.addUIPlugin` in `plugin` function, to init UI plugin:

https://github.com/umijs/umi/blob/c24a2bfd63bfaf04ce69ffc042f18b927b9765dd/packages/umi-plugin-ui/src/plugins/configuration/index.ts#L159

then call `api.addDashboard` in the UI plugin:

https://github.com/umijs/umi/blob/c24a2bfd63bfaf04ce69ffc042f18b927b9765dd/packages/umi-plugin-ui/src/plugins/configuration/ui.tsx#L35-L47
