### ISSUE TITLE
umi configuration file don't use dotfile

### ISSUE THREAD

**Issue by paranoidjk** [umijs/umi#380]
Suggest we use `umi.config.js`, instead of `.umirc.js`, and this is why:

- dotfiles are generally used by linux software configuration, mac/windows  FileManager will hidden it by default, moreover some IDE/editor will exclude it during search.
- Most of the popular framwork or tool use `foo.config.js`, eg:
  - Jest:  [jest.config.js](https://facebook.github.io/jest/docs/en/configuration.html)
  - Webpack:  [webpack.config.js](https://webpack.js.org/concepts/configuration/)
  - TypeScript: [tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)

**Comment by sorrycc** [comment]
I think it has no correct answer if the config files should be prefixed with dot.

**Comment by paranoidjk** [comment]
Moreover.  IMO use `$` as folder or filename prefix is a badly design too, since `$` is a variable prefix in bash, which means when you type `cd /myproject/pages/$shop`, bash will evaluate `$shop` as a variable.

**Comment by paranoidjk** [comment]
http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-5.html

**Comment by sorrycc** [comment]
If don't perfer `.umirc.js`, try `config/config`.
