### ISSUE TITLE
umi-plugin-react 依赖 antd: 3.x，如何使用 antd: 4.x

### ISSUE THREAD

**Issue by MinJieLiu** [umijs/umi#3800]
## What happens?

umi-plugin-react 依赖 antd: 3.x，若想用 antd: 4.x。则会在项目中安装两份 antd。

我建议在该库 `peerDependencies` 中加上 `antd: 3.x || 4.x`，不建议使用强依赖。

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：next
- **Node 版本**：next
- **操作系统**：mac

**Comment by ycjcl868** [comment]
`npm i antd --save`

在项目里:

```jsx
import { version } from 'antd'

console.log('version: ', version);
// ==> version: 4.0.0-**
```
