### ISSUE TITLE
自定义区块，运行命令添加报错

### ISSUE THREAD

**Issue by guccihuiyuan** [umijs/umi#3801]
What happens?

我写了一个区块项目，在之前 ant design pro 项目 运行 umi block add https://github.com/guccihuiyuan/pyramid-blocks/tree/master/blocks/Demo 可以添加成功，但是从最新的 ant design pro 项目中运行，会报如下信息，应该说是从  https://gitee.com 克隆代码，但我的地址是在 github 上的
![image](https://user-images.githubusercontent.com/7911691/70983240-5bf2c500-20f3-11ea-96da-c534874ce022.png)

## 相关环境信息

- **Umi 版本**：老项目：2.8.16 新项目：2.12.6
- **Node 版本**：10.15.3
- **操作系统**：windows

**Comment by Wuuuu** [comment]
我也是遇见了这样的问题

**Comment by fucaobao** [comment]
一样的问题，解决了麻烦说一声
