### ISSUE TITLE
withRouter  里面的location中的key不见了 

### ISSUE THREAD

**Issue by xuchao321** [umijs/umi#3803]
默认是createBrowserHistory路由应该有key的 还有自动生成的keyLength 在哪里配置

**Comment by xuchao321** [comment]
<img width="648" alt="WechatIMG194" src="https://user-images.githubusercontent.com/28084523/71074310-008d0980-21bd-11ea-9b65-97d6086bfb3c.png">

**Comment by ycjcl868** [comment]
![Uploading image.png…]()


有啊
