### ISSUE TITLE
.umirc.js 中 dva 设置为 false 页面加载时会闪烁 "loading..." 字样

### ISSUE THREAD

**Issue by panghongye** [umijs/umi#3804]
**Steps to reproduce the behavior:**
1. 用 yarn create umi  新建项目 
2. .umirc.js  文件中 dva 设置为 false
3. Chrome中 Network 设置为 Slow 3G 
4. 刷新页面时 会先闪一下 "loading..." 然后才显示正常内容。

**Expected behavior**
1. 刷新页面时 不闪 "loading..."  字样。

## Context

- **Umi Version**: ^2.9.0
- **Node Version**: v12.13.0

**Comment by ycjcl868** [comment]
```js
export default {
  plugins: [
    [
      'umi-plugin-react',
      {
        dynamicImport: {
          webpackChunkName: true,
          loadingComponent: './components/Loading.js',
        },
      },
    ],
  ],
};
```

```jsx
// src/components/Loading.js

import React from 'react';

export default () => <div />
```

**Comment by gintamamadao** [comment]
升级到 umi 3 后会出现一样的问题，loadingComponent 好像不允许配置了，这个该怎么解决？ @ycjcl868
