### ISSUE TITLE
动态路由配置 path为 $id

### ISSUE THREAD

**Issue by linsphone** [umijs/umi#381]
跟着https://umijs.org 网站的docs 一步步做下来 发现生成的路由和案例上的不一致。
请指教
![_20180425131841](https://user-images.githubusercontent.com/28978824/39227525-c22bd06a-488b-11e8-9b36-74406d5cd149.png)
umi -v   1.21 
node -v 8.2.1

**Comment by xiaohuoni** [comment]
试试$id$.j s

**Comment by linsphone** [comment]
@xiaohuoni 生成的path路径是 "path": "/users/$id?",

![_20180425133535](https://user-images.githubusercontent.com/28978824/39227871-97d670e8-488d-11e8-97f1-fa3501dfc10e.png)

**Comment by sorrycc** [comment]
windows 系统？怎么重现？试试 https://github.com/umijs/umi-examples/tree/master/routes 里的例子是否正常？

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi-examples/tree/master/routes 也是一样的 @sorrycc

**Comment by xiaohuoni** [comment]
![34938](https://user-images.githubusercontent.com/11746742/39228211-7f9d9658-488f-11e8-8162-585ccf765ad7.png)

**Comment by linsphone** [comment]
@sorrycc  window 系统

**Comment by alfred1994** [comment]
不要升级到1.2.1

**Comment by sorrycc** [comment]
试了 mac 没有问题，帮忙测试下 windows 下为啥有问题？相关代码在 ./node_modules/umi/node_modules/umi-build-dev/lib/getRouteConfig.js 里走 variablePath 。

**Comment by xiaohuoni** [comment]
在Windows下，文件路由是users\$id$
现有代码
```js
 path.split('/').map(path => path.replace(/^\$/, ':').replace(/\$$/, '?')).join('/')
```
修改为
```js
 path.split('\\').map(path => path.replace(/^\$/, ':').replace(/\$$/, '?')).join('/')
```
```js
 {
        "path": "/users/:id?",
        "exact": true,
        "component": () => React.createElement(require('xx').default, { route: '/users/:id?' })
      },
```

**Comment by sorrycc** [comment]
试试改成这样？

```
winPath(path).split('/').map(path => path.replace(/^\$/, ':').replace(/\$$/, '?')).join('/')
```

**Comment by sorrycc** [comment]
然后提个 PR ?
