### ISSUE TITLE
umi-plugin-react 中 preact 版本过低

### ISSUE THREAD

**Issue by HazySoda** [umijs/umi#3810]
目前 umi-plugin-react 中 preact 依赖版本为 8.x，不支持 Fragment 及 Hooks 等目前常用的特性，希望可以更新一下依赖版本。

**Comment by zhangyuang** [comment]
可以用resolutions自己覆盖一下版本

**Comment by HazySoda** [comment]
@zhangyuang 
使用 resolutions 覆盖后 umi-plugin-react 报了如下错误：

`Cannot find module 'preact/devtools'`
