### ISSUE TITLE
使用 dynamicImport，打包后，使用 _layout.js 的页面报错，其他页面正常

### ISSUE THREAD

**Issue by merlin-li** [umijs/umi#3814]
使用 dynamicImport配置 level 1
dynamicImport: {
        webpackChunkName: true,
        level: 1,
      },

打包后，访问使用  _layout.js 的页面，报js错误，其他页面正常。

但是使用  yarn start，开发模式访问是正常的。

## Context

- **Umi Version**: 2.8.7
- **Node Version**: v10.15.3
- **Platform**: macOS

**Comment by ycjcl868** [comment]
给个复现 demo

**Comment by xiaohuoni** [comment]
有重现再reopen吧
