### ISSUE TITLE
ssr和pwa同时开启时报错

### ISSUE THREAD

**Issue by vdfor** [umijs/umi#3815]
## What happens?
同时开启ssr和pwa时报错

## Mini Showcase Repository(REQUIRED)
https://github.com/vdfor/umi-issues-demo/tree/master/ssr-with-pwa

## How To Reproduce
```ts
// .umirc.ts
const config: IConfig = {
  plugins: [
    // ref: https://umijs.org/plugin/umi-plugin-react.html
    ['umi-plugin-react', {
      ...
      pwa: {
        workboxPluginMode: 'GenerateSW',
        workboxOptions: {
          importWorkboxFrom: 'local',
        },
      },
    }],
  ],
  ssr: true,
};
```

此时报错 unexpected token export，于是将ssr配置项修改为

```ts
// .umirc.ts
const config: IConfig = {
  ...
  ssr: {
    externalWhitelist: [/register-service-worker/],
    disableExternal: false,
  }
}
```
此时依然报错 TypeError: Cannot read property 'prototype' of undefined

**Expected behavior**
ssr与pwa能够并存

## Context

- **Umi Version**: 2.12.7
- **Node Version**: 12.14.0
- **Platform**: ubuntu 18.04

**Comment by ycjcl868** [comment]
有问题，不建议同时开，这个没处理好
