### ISSUE TITLE
umi SSR 模式下静态资源不能访问

### ISSUE THREAD

**Issue by 810106148** [umijs/umi#3816]
问题：
（SSR模式）运行umi build && node server.js无法访问到静态文件和无法取得远程数据。

源码地址：
https://github.com/810106148/umi-ssr-test

## 相关环境信息

- **Umi 版本**：2.12.6
- **Node 版本**：v10.15.1
- **操作系统**：win10 64

**Comment by zhangyuang** [comment]
你给的仓库都没有image文件夹。另外本地开发用npm run dev && NODE_ENV=development node ./server.js。静态资源访问路径是http://localhost:3000/dist/404.html这样的路径

**Comment by zhangyuang** [comment]
你的仓库都没image文件夹，node静态资源的访问路径是localhost:3000/dist/xxx

**Comment by 810106148** [comment]
> 你的仓库都没image文件夹，node静态资源的访问路径是localhost:3000/dist/xxx

我是放在public目录，没上传。改为localhost:3000/dist/xxx是可以访问了。谢谢！

**Comment by 810106148** [comment]
开SSR远程数据访问不了的问题，我另开个主题来提问好了。
