### ISSUE TITLE
umi 开启SSR， request请求无法取得数据

### ISSUE THREAD

**Issue by 810106148** [umijs/umi#3817]
代码仓库：git@github.com:810106148/umi-ssr-test.git
问题代码位置： src\Home\Content5.jsx
class Content5 extends React.PureComponent {
。。。。。
    getWorkList=()=>
    {
      
      console.log("show works list");
      request (`/api/work_index?status=2`).then((result) => {
        console.log(result);
    
        this.setState({
              rows:result.data.data.rows,
         });
       
      });
    
    };
    componentDidMount() {
      this.getWorkList();
    }
。。。。。

$ umi dev 可正常运行取得数据。
$ umi start 不能正常运行。
出现错误：
p__index.4c927ad3.async.js:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at p__index.4c927ad3.async.js:1
    at l (umi.d3b81334.js:1)
    at Generator._invoke (umi.d3b81334.js:1)
    at Generator.e.<computed> [as next] (umi.d3b81334.js:1)
    at n (umi.d3b81334.js:1)
    at u (umi.d3b81334.js:1)

测试环境：
Umi 版本：2.12.6
Node 版本：v10.15.1
操作系统：win10 64

**Comment by ycjcl868** [comment]
server-side 时，request 不能填相对路径，得用绝对路径。https://github.com/umijs/umi-server/blob/053bf8dd0dbd377461126d6f20bc2263225c3aff/examples/eggjs/app/web/utils/request.ts#L16-L19

**Comment by 810106148** [comment]
> server-side 时，request 不能填相对路径，得用绝对路径。https://github.com/umijs/umi-server/blob/053bf8dd0dbd377461126d6f20bc2263225c3aff/examples/eggjs/app/web/utils/request.ts#L16-L19

可是我用了代理，不能写成绝对路径。
#.umirc.js

  proxy: {
    "/api": {    
       "target": "https://api.scratchina.com/",// "target": "http://127.0.0.1:7001/",
      "changeOrigin": true,
      //"pathRewrite": { "^/api" : "" }
    }
  },
