### ISSUE TITLE
umi使用yarn build后报错，提示Error: Cannot find module './_baseClone'，但好像就没有这个module

### ISSUE THREAD

**Issue by xuesjie** [umijs/umi#3818]
以下是项目用的package.json
{
  "private": true,
  "scripts": {
    "start": "umi dev",
    "build": "umi build",
    "test": "umi test",
    "lint": "eslint --ext .js src mock tests",
    "precommit": "lint-staged"
  },
  "dependencies": {
    "antd": "^3.19.5",
    "babel-plugin-import": "^1.3.1",
    "babel-runtime": "^6.9.2",
    "dva": "^2.6.0-beta.6",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "devDependencies": {
    "babel-eslint": "^9.0.0",
    "eslint": "^5.4.0",
    "eslint-config-umi": "^1.4.0",
    "eslint-plugin-flowtype": "^2.50.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.11.1",
    "husky": "^0.14.3",
    "lint-staged": "^7.2.2",
    "react-test-renderer": "^16.7.0",
    "umi": "^2.12.7",
    "umi-plugin-react": "^1.8.4"
  },
  "lint-staged": {
    "*.{js,jsx}": [
      "eslint --fix",
      "git add"
    ]
  },
  "engines": {
    "node": ">=8.0.0"
  }
}

**Comment by ycjcl868** [comment]
给个复现仓库
