### ISSUE TITLE
如何关闭build时的publicPath校验

### ISSUE THREAD

**Issue by viviprprpr** [umijs/umi#3825]
请问，如何关闭publicPath校验，因为这个地方想配置变量。

![image](https://user-images.githubusercontent.com/40267580/71408522-87d4f400-2679-11ea-9e2b-dcada2667de9.png)

**Comment by ycjcl868** [comment]
publicPath 必须以 `/` 结尾，不然 `bababa/umi.js` 就变成了 `bababaumi.js`
