### ISSUE TITLE
新建的 block 使用 @ 引用不到文件，配置了 alias 也引用不到

### ISSUE THREAD

**Issue by Benpaodejiezai** [umijs/umi#3829]
![image](https://user-images.githubusercontent.com/51696361/71454079-e7421980-27c9-11ea-9f02-5467a3e630f3.png)
![image](https://user-images.githubusercontent.com/51696361/71454095-fb861680-27c9-11ea-9019-376de3aea1d8.png)
![image](https://user-images.githubusercontent.com/51696361/71454112-05a81500-27ca-11ea-8d1c-62c54dd62bd4.png)
在 ant-design-pro 项目里面是好用的，还需要配置什么吗？

**Comment by Benpaodejiezai** [comment]
![image](https://user-images.githubusercontent.com/51696361/71456133-f6799500-27d2-11ea-9d4b-2981ed4d88fc.png)
![image](https://user-images.githubusercontent.com/51696361/71456138-fc6f7600-27d2-11ea-8001-73a666af53e5.png)
这样的是可以的。。。

**Comment by ycjcl868** [comment]
配置下 `tsconfig.json`

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design-pro/blob/bf3abbb89918f6f34d3f4967e2497c4301eca53f/tsconfig.json#L21
