### ISSUE TITLE
formatMessage({ id="TEST_TITLE" })这里这样使用报错了，改成如下方式没有问题了：formatMessage({ id: "TEST_TITLE"

### ISSUE THREAD

**Issue by wangyuan0108** [umijs/umi#3833]
## What happens?

![image](https://user-images.githubusercontent.com/22407253/71476904-53e90280-2822-11ea-87bc-7f29d212b67f.png)

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
![image](https://user-images.githubusercontent.com/22407253/71476984-9ca0bb80-2822-11ea-89fb-8df7cae4a8d5.png)

这里的是不是文档写错了还是我用的不对

## 相关环境信息

- **Umi 版本**：v2.9.0
- **Node 版本**：v10.16.0
- **操作系统**：macOs

**Comment by ycjcl868** [comment]
`{ id =  }` js 编译器都过不去，正确用法是 `{ id: '' }`

**Comment by wangyuan0108** [comment]
> `{ id = }` js 编译器都过不去，正确用法是 `{ id: '' }`
是的，我知道，所以你们的api文档写错了，你们看下。
![image](https://user-images.githubusercontent.com/22407253/71495647-ed97ca80-2889-11ea-8a79-23f1c2c3090e.png)

**Comment by wangyuan0108** [comment]
@ycjcl868

**Comment by ycjcl868** [comment]
文档哪个地方

**Comment by wangyuan0108** [comment]
@ycjcl868 上面截图的地方，你能看的到吗

**Comment by ycjcl868** [comment]
提个 PR 改一把
