### ISSUE TITLE
使用公网ip访问服务器的开发环境，umi ui说非本地ip不能直接连接，需添加环境变量0.0.0.0。

### ISSUE THREAD

**Issue by llh1187** [umijs/umi#3842]
## What happens?
使用公网ip访问服务器的开发环境，umi ui说非本地ip不能直接连接，需添加环境变量0.0.0.0。

我启动时 npm start HOST=0.0.0.0或者 npm start 'HOST=0.0.0.0' 都不能解决这个问题。

**Comment by ycjcl868** [comment]
`HOST=0.0.0.0 npm start` 或者 `HOST=0.0.0.0 umi dev`

**Comment by llh1187** [comment]
> `HOST=0.0.0.0 npm start` 或者 `HOST=0.0.0.0 umi dev`
还是提示说非本地ip不能访问。

**Comment by zch233** [comment]
也遇到了这个问题加了`HOST=0.0.0.0`没用

**Comment by gaozhidf** [comment]
也遇到了这个问题加了HOST=0.0.0.0没用

**Comment by 378840826** [comment]
通过127.0.0.1进行访问试试

**Comment by llh1187** [comment]
> 通过127.0.0.1进行访问试试

公网ip..我是通过服务器直接进行开发的，用来玩下:smile:

**Comment by Harrypotterrrr** [comment]
同 命令行以及start中加入环境变量 都没有用

**Comment by fanyinghao** [comment]
umi需要默认3000端口，看是否有打开了

**Comment by OneFz** [comment]
> umi需要默认3000端口，看是否有打开了

正解
