### ISSUE TITLE
创建umi ui项目后安装依赖出错。

### ISSUE THREAD

**Issue by llh1187** [umijs/umi#3846]
## What happens?
创建umi ui项目后安装依赖出错。
使用淘宝源，npm install以及使用npmjs的源，翻了墙安装，也还是不行。

## 版本：
win10,node v12.13.1.

## 出错
![image](https://user-images.githubusercontent.com/40154001/71569325-3e692680-2b09-11ea-8aad-5901326213ba.png)

## 详细出错：
[2019-12-30T05_16_07_996Z-debug.log](https://github.com/umijs/umi/files/4009031/2019-12-30T05_16_07_996Z-debug.log)

**Comment by ycjcl868** [comment]
https://umijs.org/zh/guide/faq.html#styled-components-%E7%BC%96%E8%AF%91%E5%A4%B1%E8%B4%A5

看起来目录没有权限，给个写权限试试
