### ISSUE TITLE
LoadableComponent 在控制台一直输出警告信息！

### ISSUE THREAD

**Issue by shangdev** [umijs/umi#3847]
umi版本：2.12.0
umi-plugin-react版本：1.14.3

![image](https://user-images.githubusercontent.com/15621520/71572374-b6d7e380-2b19-11ea-98c9-a74ef55f8deb.png)

**Comment by ycjcl868** [comment]
复现 demo

**Comment by chj-damon** [comment]
@shangdev 为什么关掉啊？
