### ISSUE TITLE
modifyRouteComponent 第二个参数可以多返回 route 里的值吗

### ISSUE THREAD

**Issue by MinJieLiu** [umijs/umi#3852]
## What happens?

插件开发 `modifyRouteComponent ` API 回调中第二个参数

```ts
interface IModifyRouteComponentArgs {
  importPath: string;
  webpackChunkName: string;
  component: string;
}
```

第一个参数是 memo 字符串

始终无法获得 `path` 和 `exact`。
有其他办法获得吗？

## 相关环境信息

- **Umi 版本**：latest
- **Node 版本**：12
- **操作系统**：mac

**Comment by ycjcl868** [comment]
从 `api.routes` 上获取
