### ISSUE TITLE
打包文件过大的问题

### ISSUE THREAD

**Issue by 544751779** [umijs/umi#3853]
打包的js太大,怎么吧?

图表  富文本  以及一些组件 超过5M了  怎么像vue一样分若干个js进行加载?

**Comment by ycjcl868** [comment]
https://umijs.org/plugin/umi-plugin-react.html#dynamicimport

**Comment by harekuer** [comment]
同样的问题，umi.js打包出来超级大，对首屏渲染，非常不友好
