### ISSUE TITLE
umi更新到2.12.8之后react-media报错

### ISSUE THREAD

**Issue by huanghonghao** [umijs/umi#3858]
* 相关代码
```js
export default connect(({ global, setting, menu: menuModel }) => ({
  collapsed: global.collapsed,
  layout: setting.layout,
  menuData: menuModel.menuData,
  breadcrumbNameMap: menuModel.breadcrumbNameMap,
  ...setting,
}))(props => (
  <Media query="(max-width: 599px)">
    {isMobile => <BasicLayout {...props} isMobile={isMobile} />}
  </Media>
));
```

* umi@2.12.8之前是正常的
![image](https://user-images.githubusercontent.com/43006765/71660993-b8a6de80-2d87-11ea-9e08-79e83dab1c97.png)

* 更新umi@2.12.8后报错
![image](https://user-images.githubusercontent.com/43006765/71661076-0ae7ff80-2d88-11ea-945f-a30fb6eb1e55.png)

![image](https://user-images.githubusercontent.com/43006765/71661193-6f0ac380-2d88-11ea-80d4-9b5a41cfbfe3.png)

> 原因：umi@2.12.8版本在children中加了GUmiUIFlag组件导致变成了数组，而react-media对children做了类型检查

![image](https://user-images.githubusercontent.com/43006765/71661265-a6797000-2d88-11ea-852a-083a90581ccc.png)

**Comment by Ka-Houl** [comment]
"umi": "^2.4.4"  也有这个问题
