### ISSUE TITLE
Import动态导入的文件路径错误时缺少日志提示

### ISSUE THREAD

**Issue by linxiangjun** [umijs/umi#3863]
## What happens?

通过import动态导入的模块如果路径错误，在构建时没有错误日志，仅显示**Failed to compile with 1 errors**，是否能够捕获到错误并在日志中打印出来。

通过在代码顶层import的形式如果路径错误则会有详细的错误原因和解决方案。

## 最小可复现仓库

无

### 一、代码
```js
import(`config/routes/pages/${pageRoute}`).then(m => {
  // do something       
})
```

### 二、运行

`npm run dev`

### 三、结果

ERROR Failed to compile with 1 errors

## 相关环境信息

- **Umi 版本**：2.10.7
- **Node 版本**：10.16.3
- **操作系统**：macOS

**Comment by xiaohuoni** [comment]
```
import(`config/routes/pages/abc`).then(m => {
  // do something       
})

export default () => <div> Index Page11 </div>;
```
![image](https://user-images.githubusercontent.com/11746742/93547571-eb394b80-f997-11ea-978b-58088bedac23.png)
试了一下无法复现。
