### ISSUE TITLE
渲染多次是什么原因呢？

### ISSUE THREAD

**Issue by ywy94ywy** [umijs/umi#3865]
1、yarn create umi => ant design pro;
2、yarn;
3、在BasicLayout.jsx增加一条console.log，输出了一次;
4、在Welcome.jsx页面增加一条console.log，输出了四次;

想知道为什么在业务页面会输出这么多次，antd pro layout做了什么，记得V2版本是没有这么多次的。

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/5844
看这里
