### ISSUE TITLE
import scope package 没有自动提示

### ISSUE THREAD

**Issue by simonyouth** [umijs/umi#3867]
## What happens?
```js
import { ... } from '@ant-design/icons-react';
```
package没有提示， 模块也没有提示， 使用cra创建的项目都是有的。不知道从哪配置或者其他问题？
## 最小可复现仓库

无

## 复现步骤，错误日志以及相关配置

- yarn add @ant-design/icons-react
- import {} from '@an...'

## 相关环境信息

- **Umi 版本**：^2.7.0-beta.6
- **Node 版本**：v10.16.3
- **IDE**: webstrom, vscode
- **操作系统**：win10

**Comment by sorrycc** [comment]
得直接依赖 `@ant-design/icons-react`。

**Comment by simonyouth** [comment]
> 得直接依赖 `@ant-design/icons-react`。

这是install之后的，提示没有的。

**Comment by xiaohuoni** [comment]
这个好像是开发工具插件的活。
