### ISSUE TITLE
hd方案，在OPPO r9plus 手机QQ扫码打开时失效

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#387]
开启hd方案，在OPPO r9plus上，页面图标都变得很大。
https://github.com/umijs/umi-examples/tree/master/eleme-demo
重现步骤
```base
$ gitclone https://github.com/umijs/umi-examples
$ cd eleme-demo
$ npm i
$ npm run build
$ cd dist
// (npm i serve -g)
$ serve  
```
我本地测试是安装了ngrok
然后使用ngrok http 5000
生成http://7be3372c.ngrok.io
用草料二维码生成二维码
使用OPPO r9plus，手机QQ扫描二维码

**Comment by xiaohuoni** [comment]
![120203](https://user-images.githubusercontent.com/11746742/39285184-9f9b73ac-4949-11e8-8b58-099023bd979b.png)

**Comment by xiaohuoni** [comment]
```base
...\umi\node_modules\umi-build-dev\lib\plugins\hd\template\flex.js
```
代码片段
```js
var win = window;
  var doc = win.document;
  var ua = navigator.userAgent;
  var matches = ua.match(/Android[\S\s]+AppleWebkit\/(\d{3})/i);
  var UCversion = ua.match(/U3\/((\d+|\.){5,})/i);
  var isUCHd = UCversion && parseInt(UCversion[1].split('.').join(''), 10) >= 80;
  var isIos = navigator.appVersion.match(/(iphone|ipad|ipod)/gi);
  var dpr = win.devicePixelRatio || 1;
  alert(`isIos:${isIos},matches[1]:${matches &&matches[1]},isUCHd:${isUCHd}`)
  if (!isIos && !(matches && matches[1] > 534) && !isUCHd) {
    // 如果非iOS, 非Android4.3以上, 非UC内核, 就不执行高清, dpr设为1;
    dpr = 1;
  }
```

**Comment by xiaohuoni** [comment]
![a8](https://user-images.githubusercontent.com/11746742/39289335-5345b30e-495e-11e8-8e48-b4075101a3b7.png)

**Comment by sorrycc** [comment]
提个 PR?

**Comment by xiaohuoni** [comment]
哈哈哈，我还没找到问题（捂脸）

**Comment by xiaohuoni** [comment]
在oppor9s，自带的浏览器，和微信浏览器上。
![aaa](https://user-images.githubusercontent.com/11746742/39296579-e4c09654-4973-11e8-9e51-94e12579ede2.png)

**Comment by xiaohuoni** [comment]
在oppor9s，手机QQ的浏览器上（通过扫码进去）
![bbb](https://user-images.githubusercontent.com/11746742/39296639-003057e4-4974-11e8-8f17-26b5464dd60a.png)

**Comment by xiaohuoni** [comment]
尝试做了修改，等一下提PR

**Comment by xiaohuoni** [comment]
因为借销售的手机测试，他一直有业务，所以进展比较慢。修复之后，尝试发包，发到技术交流群里，找其他人扫码验证了，问题已修复。保证OPPOR9S上问题修复。其他机型没有测试

**Comment by sorrycc** [comment]
👍
