### ISSUE TITLE
umiui dev 模式下可以关闭么

### ISSUE THREAD

**Issue by limerickgds** [umijs/umi#3871]
## What happens?
应用域名和 cdn 域名是不一致的，umiui 会请求 应用域名的 ws://xxx:3000  的 ws ，一致请求失败。本地开发暂时没有使用 umiui 诉求，想关掉

## 相关环境信息

- **Umi 版本**：2.1.x
- **Node 版本**：10
- **操作系统**：macos

**Comment by sorrycc** [comment]
可以通过环境变量 `UMI_UI=none` 关闭。
