### ISSUE TITLE
引入stylus后测试代码报错

### ISSUE THREAD

**Issue by yalishizhude** [umijs/umi#3872]
## What happens?

umi 配置文件加入stylus配置，代码构建成功，但是执行测试代码失败。
.umirc.ts 文件添加如下配置

```
chainWebpack(config) {
    config.module
      .rule('stylus')
      .test(/\.styl$/)
      .use('stylus')
      .loader('stylus-loader');
  }
```

## Mini Showcase Repository(REQUIRED)

https://github.com/yalishizhude/umi-stylus-error.git

## How To Reproduce
**Steps to reproduce the behavior:**
1. yarn install
2. yarn test

**Expected behavior**
通过测试

## Context

- **Umi Version**:2.12.8
- **Node Version**: 12.4
- **Platform**: linux

![编译成功](https://user-images.githubusercontent.com/3870098/71799823-4852d280-3091-11ea-9838-88c2805f8499.png)

![执行测试代码失败](https://user-images.githubusercontent.com/3870098/71799791-3113e500-3091-11ea-9b28-28f347301566.png)

**Comment by xiaohuoni** [comment]
没用过 stylus 不太清楚，但是你这个应该是 stylus 如何使用 jest 编写单元测试之类的问题。
