### ISSUE TITLE
怎样使用 antd v4 呢？

### ISSUE THREAD

**Issue by fjc0k** [umijs/umi#3873]
## What happens?
antd v4 发布了 rc 版，想使用看看，但是直接将项目依赖改成 4 的貌似不行，有解决方案吗？

**Comment by MinJieLiu** [comment]
行啊，咋不行

**Comment by fjc0k** [comment]
@MinJieLiu  不行的，我用了 v4 特有的属性完全没效果。最简单的判断方法就是 `import {Icon} from 'antd'`，因为 v4 里图标独立出去了，所以是引用不到的，但是我引用到了。

**Comment by MinJieLiu** [comment]
#3800

**Comment by fjc0k** [comment]
@MinJieLiu 老哥，你亲自试过吗？我这边该做的都做了，只不过用的 lerna + yarn，死活就还是 3.x 版本。

**Comment by fjc0k** [comment]
发现原因了，我用了 lerna + yarn workspace，去除 workspace 后好使了，应该是 workspace 内部一些机制导致依赖没对。

**Comment by Sayid1** [comment]
老哥，能把你的lerna + umi的搭建步骤发一下吗，我lerna+umi搭建项目的时候没有思路了

**Comment by fjc0k** [comment]
跟普通一样啊 去除 workspace 在需要的包安装 umi 就行

**Comment by Sayid1** [comment]
去掉lerna的useWorkspaces配置，然后再每个packages里面执行npx @umijs/create-umi-app创建umi项目吗，最后在根目录执行lerna bootstarp吗？
