### ISSUE TITLE
umi-plugin-auto-externals 在 antd-pro 中，加载失败 TypeError: Cannot read property '' of undefined

### ISSUE THREAD

**Issue by zhanghouji** [umijs/umi#3875]
## What happens?
umi-plugin-auto-externals 在 antd-pro 中，加载失败 
```
TypeError: Cannot read property '' of undefined
```
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

[https://github.com/zhanghouji/umi-plugin-auto-externals-issues](https://github.com/zhanghouji/umi-plugin-auto-externals-issues)
## How To Reproduce
**Steps to reproduce the behavior:**
1. yarn
2. yarn start

**Expected behavior**
1.
2.

## Context

- **Umi Version**: 2.9.3 or 2.8.7
- **Node Version**: 10.14.2
- **Platform**: Mac OS

**Comment by peng2018** [comment]
umi/auto-external-packages 里面目前的正则把 use-media-antd-query 依赖也当作antd处理成了external形式。

可以先本地试试修改一下
```diff
  dependencies: ['react', 'react-dom', 'moment'],
  global: (_, request, callback) => {
    if (
-      !/antd/.test(request) ||
+      !/(^|\/)antd($|\/)/.test(request) ||
      /style/.test(request) ||
      /locale-provider\/.*/.test(request)
    ) {
```
 [umijs/auto-external-packages/pull/2](https://github.com/umijs/auto-external-packages/pull/2/files)

**Comment by zhanghouji** [comment]
@peng2018 谢谢你，我会关注它[umijs/auto-external-packages/pull/2](https://github.com/umijs/auto-external-packages/pull/2/files)

**Comment by w771854332** [comment]
+1， 啥时候修复呀，急用

**Comment by zhanghouji** [comment]
@w771854332 可以先自己配置 [https://umijs.org/zh/config/#externals](https://umijs.org/zh/config/#externals)
在 document.ejs 中手动加上 cdn 就行了

**Comment by w771854332** [comment]
@zhanghouji 因为有babel-plugin-import，
```js
import { Modal } from 'antd' => import Modal from 'antd/lib/Modal'
```
这样直接配external是没用的，必须得写一些比较复杂的逻辑...等着插件修复

**Comment by KingThq** [comment]
这个问题修复了吗？我已经升级到最新版本了，为什么还有这个问题？

**Comment by xiaohuoni** [comment]
auto-external-packages 这个包已经不维护了。项目优化问题可以参考文档[如何做编译提速](https://umijs.org/guide/boost-compile-speed) 或者 [umi 项目如何做产物优化](https://zhuanlan.zhihu.com/p/157540425) 自己实现
