### ISSUE TITLE
Page里嵌套其他的Page，内层Page没法获取到自己的model

### ISSUE THREAD

**Issue by CoolBerry** [umijs/umi#3877]
如题。
一个page（PageA）中打算直接使用另一个page（PageB），那么PageB自己connect的model会返回undefined。

请问要怎么解决。
谢谢：）

**Comment by CoolBerry** [comment]
model是在Page里面单独使用的，不是放在外面共享的model。

**Comment by CoolBerry** [comment]
model没有注册的原因，注册就好了

**Comment by yuki070** [comment]
model注册是指什么？能不能截图个示例看看？

**Comment by CoolBerry** [comment]
有个subscribe来注册，可以在dvajs里面查找具体文档
