### ISSUE TITLE
npm 或 cnpm 都装不上了

### ISSUE THREAD

**Issue by lirunwin** [umijs/umi#3878]
## What happens?

npm 或cnpm 都装不上了.

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by zhanghouji** [comment]
@lirunwin 你可以试试yarn [https://umijs.org/zh/guide/getting-started.html#%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87](https://umijs.org/zh/guide/getting-started.html#%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87)

**Comment by lirunwin** [comment]
> @lirunwin 你可以试试yarn https://umijs.org/zh/guide/getting-started.html#%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87

以前可以用npm   现在感觉只能用yarn了
