### ISSUE TITLE
ssr和dynamicImport同时开启时客户端getInitialProps方法不执行

### ISSUE THREAD

**Issue by lcya86** [umijs/umi#3879]
## What happens?

1.ssr和dynamicImport同时开启时客户端getInitialProps方法不执行
2.ssr开启dynamicImport关闭时，点击浏览器回退按钮，动态路由页面的getInitialProps方法中的route.params参数值不正确

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

https://github.com/lcya86/umi-koa-ssr-dynamic

## 复现步骤，错误日志以及相关配置

安装依赖后运行 npm start
然后进入 http://localhost:3000/aaa
打开开发者工具console

针对问题1：点击页面中的bbb链接，期待console打印bbb，目前是不会打印，说明客户端的getInitialProps方法没有运行。

针对问题2：修改.umirc.js，将dynamicImport设为false，重启项目，然后进入http://localhost:3000/aaa 页面。点击页面中的bbb链接，然后点击浏览器回退按钮，期待console打印aaa，但是目前打印的是bbb，与url不符。

## 相关环境信息

- **Umi 版本**：2.12.9
- **Node 版本**：10.15.1
- **操作系统**：mac OS 10.14.3

**Comment by 5kong** [comment]
試了ssr 的 example（https://github.com/umijs/umi-server/tree/master/examples）： eggjs & expressjs，  發現都是同樣問題。 麻煩大神盡快解決一下。
