### ISSUE TITLE
新建 src/dva.js，通过导出的 config 方法来返回额外配置项, 不生效

### ISSUE THREAD

**Issue by qingfengmy** [umijs/umi#388]
FAQ
如何配置 onError、initialState 等 hook？
新建 src/dva.js，通过导出的 config 方法来返回额外配置项，比如：
```
import { message } from 'antd';

export function config() {
  return {
    onError(err) {
      err.preventDefault();
      message.error(err.message);
    },
    initialState: {
      global: {
        text: 'hi umi + dva',
      },
    },
  };
}
```
=================================================
``
src/dva.js
import { message } from 'antd';

export function config() {
  const config = {
    onError(err) {
      err.preventDefault();
      message.error(err.message);
    },
    initialState: {
      global: {
        text: 'hi umi + dva',
      },
    },
  };
  console.log('config', config); // log未执行
  return config;
}
```
log未执行， 是否还需要其他地方配置？

**Comment by xiaohuoni** [comment]
功能可以使用吗？
你在项目中试试
```js
const error = new Error('测试');
 throw error;
```

**Comment by qingfengmy** [comment]
@xiaohuoni 

不会捕捉异常，onError无代码执行

**Comment by xiaohuoni** [comment]
是不是没有使用'umi-plugin-dva'哦？ @qingfengmy

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi-examples/tree/master/with-dva
参考一下这个 @qingfengmy

**Comment by xiaoElevener** [comment]
@qingfengmy  首先看你在 .umirc.js里有没有引入umi-plugin-dva。然后看umi和umi-plugin-dva的版本。我更新下了这两个模块的版本就能用了。
