### ISSUE TITLE
How to pass server cookie to client side in ssr koa js ?

### ISSUE THREAD

**Issue by wmtjaychhatrola** [umijs/umi#3880]
## What happens?
I want to pass the server cookie to the client-side when server-side rendering.

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

`` cookies.get('any') ``

## How To Reproduce
**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context

- **Umi Version**: 2.12.7 **Umi Server**: 1.1.9
- **Node Version**: 10.15.2
- **Platform**: React

**Comment by lcya86** [comment]
![image](https://user-images.githubusercontent.com/3196009/71977735-85b38d80-3254-11ea-9974-0d2edcc0a0d8.png)
