### ISSUE TITLE
umi-locale 语法提示问题

### ISSUE THREAD

**Issue by crashsol** [umijs/umi#3884]
## Background

在使用umi-locale是，经常因为 记不住ID或则id输入错误，是否考虑新增对 Id的提示功能

## Proposal
当本地locales修改的时候，自动生成一个 interface localNames {
    "menu.user":string;
    "menu.role":string;
     ...
}
对formatMessage的 ID参数进行验证和提示  比如 
export interface MessageDescriptor {
  id: keyof localNames ;
  description?: string;
  defaultMessage?: string;
}

这样在使用本地化时，Id值会自动有提示，可以大大提高开发效率

**Comment by ycjcl868** [comment]
https://github.com/umijs/umi/pull/2469
https://github.com/umijs/umi/pull/2713
