### ISSUE TITLE
i can't config inlineLimit now

### ISSUE THREAD

**Issue by qhxin** [umijs/umi#3886]
## What happens?
I use umi@2.12.7 and i can't config `inlineLimit` for `url-loader`.

Because .webpackrc and webpack.config.js is not supported in umi@2.

**Expected behavior**
1. i want to update `inlineLimit` for `url-loader`

**Comment by qhxin** [comment]
@sorrycc So how to solve this question? plz.

**Comment by qhxin** [comment]
@sorrycc 

Oka, i solved this question.
But webpack-chain's docs is really unreadable.

```

  chainWebpack(config) {
    config.module
      .rule('exclude')
      .use('url-loader')
      .tap(options => {
        return {
          ...options,
          xxxxxx: 123,
        };
      });
  },
```

**Comment by stoneyallen** [comment]
I also encountered this problem.
Please open the options of inlineLimit.
