### ISSUE TITLE
在ui中启动本地开发会报8888端口错误

### ISSUE THREAD

**Issue by winter-ice** [umijs/umi#3888]
## What happens?
在ui中每次启动本地开发会报8888端口错误，启动失败，然后重新启动就好了。
![image](https://user-images.githubusercontent.com/24680921/71968811-8f32fa80-3240-11ea-904a-098d54aaaba8.png)

找了一下在这里硬编码了8888端口，不知道是不是这个的原因：
https://github.com/umijs/umi/blob/5e0bca942ce3f98cb522d13dd7728afed4781fa0/packages/umi-ui-tasks/src/server/util/stats.ts#L14

## How To Reproduce
**Steps to reproduce the behavior:**
1.初始化antd项目
2.本地启动

## Context

- **Umi Version**:2.12.9
- **Node Version**:12.5.0
- **Platform**:win

**Comment by ycjcl868** [comment]
Umi 2？

**Comment by winter-ice** [comment]
嗯，好久以前的issue了，umi3没发现，没啥用就关了吧
