### ISSUE TITLE
umi-plugin-qiankun该插件是否只能用于子应用是基于umi实现的应用？

### ISSUE THREAD

**Issue by crixusshen** [umijs/umi#3894]
疑问：umi-plugin-qiankun该插件是否只能用于子应用是基于umi实现的应用？如果不是基于Umi实现的应用可以使用吗？

**Comment by dkvirus** [comment]
可以直接用 qiankun 这个项目：https://github.com/umijs/qiankun

官方有个 Example 目录，子系统分别用了 React15、React16 和 Vue 写的三个子系统。

看的过程有个疑问：登录行为在哪里做？如果在主系统做，那就意味着各个子系统都需要与主系统交互数据了。

**Comment by kuitos** [comment]
umi plugin 是给 umi 应用用的

**Comment by shizhipeng** [comment]
请问主应用是umi 子应用非 umi 可以有接入方案吗
