### ISSUE TITLE
[Feature Request] 提供在登录之后通过运行时配置获取路由数据的功能

### ISSUE THREAD

**Issue by chj-damon** [umijs/umi#3898]
## Background
umi提供了运行时配置，可以让我们在程序一启动的时候做一些事情，比如动态获取后端路由数据。但是实际项目里面一般是需要登录操作的，在登录成功之后才能去拿路由数据。所以现在的umi运行时配置做不到这种效果。

## Proposal
实际上我们在项目里面通常会把应用的主程序部分和登录注册这些页面用不同的Layout分开，比如BasicLayout/LoginLayout...那么是否可以做到在运行某个layout的时候触发运行时配置，或者说运行时配置可以指定在加载某个layout的时候才执行，这样上述的场景就可以在登录之后，加载BasicLayout的时候通过运行时配置去后台拿路由数据了。

**Comment by wangyinwei1** [comment]
同问

**Comment by wangyinwei1** [comment]
我也有此类问题，请问是否已经有解决方案？

**Comment by xiaohuoni** [comment]
@umijs/plugin-initial-state@2.2.0 setInitialState

**Comment by sorrycc** [comment]
我想到的办法是，

1. 逻辑仍旧放在 app.ts 里处理
2. 登录时存 cookie，刷新页面
3. 如果通过 cookie 等识别出已登录，通过 render 和 patchRoutes 增加额外的路由
