### ISSUE TITLE
版本2.12.7 中 ，location.pathname获取重定向之后的地址出现错误

### ISSUE THREAD

**Issue by qinyuhua** [umijs/umi#3899]
使用react开发，重定向之前是/home 使用router.repalce('/home/1/0/0')，结果获取的还是/home

**Comment by zhangyoof** [comment]
我也遇到了这个问题  版本是2.13.6  你这个问题解决了吗

**Comment by zhangyoof** [comment]
> 使用react开发，重定向之前是/ home使用router.repalce（'/ home / 1/0/0'），结果获取的还是/ home

我也遇到了你这个问题，版本是2.13.6，你这个问题解决了吗

**Comment by sorrycc** [comment]
Fixed via umi@2.13.7.
