### ISSUE TITLE
初始化plugin后，安装完依赖，yarn start 报错，如图

### ISSUE THREAD

**Issue by monkeylp** [umijs/umi#3903]
## What happens?
按照步骤 yarn create umi --plugin  
初始化plugin后，安装完依赖，yarn start 报错，如图

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
1， yarn create umi --type=plugin
2，yarn
3,   yarn build --watch
![image](https://user-images.githubusercontent.com/28817520/72202699-9a369680-349d-11ea-8cf6-18c4260b6bed.png)
4，yarn start:mini
![image](https://user-images.githubusercontent.com/28817520/72202535-9c97f100-349b-11ea-90dc-fa3bb55ebd8c.png)

## 相关环境信息

- **Umi 版本**：2.12.9
- **Node 版本**：v8.14.1
- **操作系统**：macOS

**Comment by ycjcl868** [comment]
![Uploading image.png…]()

给个复现吧

**Comment by monkeylp** [comment]
莫的问题，应该是我node版本的问题，v8.14.1有些依赖安不上，换了个版本重新创建plugin，运行就没啥问题，打扰打扰
