### ISSUE TITLE
在Layout组件里面我想这样子向子路由组件传递属性，传递不过去，有办法嘛

### ISSUE THREAD

**Issue by bibiehy** [umijs/umi#3905]
"umi": "2.12.7",

如下代码：
![image](https://user-images.githubusercontent.com/35096473/72230085-3ff91b00-35ee-11ea-8edf-81ca005f5698.png)
传递自定义属性和事件，子路由组件接收不到，
使用 React.createContext() 肯定可以，但我就是想通过传递属性方式获取，有办法嘛

**Comment by sorrycc** [comment]
umi@2 不行，等 umi@3 吧，https://github.com/umijs/umi-next/blob/6dd2a57210132e6a3a1ea64624106d71a835f92a/packages/renderer-react/src/renderRoutes/renderRoutes.test.tsx#L115 。

**Comment by xiaohuoni** [comment]
看起来是已解决的问题，有问题再reopen
