### ISSUE TITLE
[Feature Request] 针对型项目的targets

### ISSUE THREAD

**Issue by hzgotb** [umijs/umi#3911]
不需要做太多的兼容和垫片，只针对新版本浏览器的话，目前的targets不大好用。因为配置后只会合并默认值，而非整体覆盖。

切确的使用场景是，终端都是最新版本的浏览器。
这意味着，我打包时，不需要各种垫片。

而 browserlist 提示已废弃。

其中之一的建议是，增加一个 overrideTargets: boolean 的属性，默认是 false。如果为 true 则覆盖。

**Comment by sorrycc** [comment]
umi@3 中考虑了这一点，umi@2 中可以通过配 targets.browsers 试试，我记得有 targets.browsers 会忽略其他的。

**Comment by hzgotb** [comment]
> umi@3 中考虑了这一点，umi@2 中可以通过配 targets.browsers 试试，我记得有 targets.browsers 会忽略其他的。

是的，就这一个(config/#browserslist)[https://umijs.org/zh/config/#browserslist]。但是因为显示 deprecated ，心有点慌🤣🤣
