### ISSUE TITLE
Configuration routing doesn't work if routes are more than two level deep

### ISSUE THREAD

**Issue by aquibbaig** [umijs/umi#3913]
## What happens?
We have a `config.js` to generate routes. Our pages folder is as follows:
```
|_ Controllers
   |_ index.js
|_ Results
   |_ index.js
|_ Summary
   |_ index.js
```

and the routing configuration is:
```
module.exports = [
  {
    path: '/',
    component: '../layouts/BasicLayout',
    routes: [
      {
        path: '/',
        name: 'dashboard',
        icon: 'dashboard',
        component: './Controllers',
      },
      {
        path: '/results',
        name: 'results',
        component: './Results',
      },
      {
        path: '/summary',
        name: 'summary',
        component: './Summary',
      },
],
}]
```

Now we would like to have a configuration in which we have a path like `/results/summary`.
We have tried the following configuration, which doesn't work and doesn't throw a 404 also. It doesn't redirect to anything. 
```
module.exports = [
  { path: '/', component: '../layouts/BasicLayout',
    routes: [
      { path: '/', component: './Controllers',
        routes: [
          { path: '/results', component: './Results',
            routes: [
              { path: '/summary', component: './Summary' }
            ]
          }
        ]
      }
    ],
  },
];
```

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

https://github.com/distributed-system-analysis/pbench/tree/master/web-server/v0.4

## How To Reproduce
**Steps to reproduce the behavior:**
1. Override the router.config.js inside `config` directory as above.

**Expected behavior**
1. Should open up  **Results** component in `/results` URL after redirect from `/`, but it doesn't redirect to anything.

## Context

- **Umi Version**: 2.11.1
- **Node Version**: >=8.0.0
- **Platform**: fedora 29

**Comment by xiaohuoni** [comment]
https://github.com/distributed-system-analysis/pbench/tree/master/web-server/v0.4 is 404
