### ISSUE TITLE
-webkit-box-orient: vertical; 编译后丢失！！！

### ISSUE THREAD

**Issue by GeNa-jj** [umijs/umi#3915]
-webkit-box-orient: vertical; 编译后丢失

代码上写有
overflow: hidden;
display:-webkit-box; 
text-overflow: ellipsis;
-webkit-line-clamp: 3;
-webkit-box-orient: vertical;

编译后，浏览器上只有
overflow: hidden;
display:-webkit-box; 
text-overflow: ellipsis;
-webkit-line-clamp: 3;

**Comment by sorrycc** [comment]
试试不压缩构建（COMPRESS=none），如果正常，说明是压缩的问题，需要调 cssnano 的参数；如果不正常，说明是 autoprefixer 的问题，需要调 targets 参数。

**Comment by GeNa-jj** [comment]
@sorrycc 设置不压缩构建（COMPRESS=none）一样不正常。请问一下 autoprefixer 的 targets 参数怎么设置？

**Comment by GeNa-jj** [comment]
@sorrycc 我在代码里面设置

**Comment by GeNa-jj** [comment]
@sorrycc 我在代码里面设置
/* autoprefixer: ignore next */
-webkit-box-orient: vertical;

可以编译出来

**Comment by xiaohuoni** [comment]
应该是配置 targets 支持的浏览器可以解决
