### ISSUE TITLE
权限路由修改不能实时编译

### ISSUE THREAD

**Issue by llfylwg** [umijs/umi#3916]
## 路由文件是个单独的js，配置了权限路由，修改路由文件不能实时编译，需要重启才能生效

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本2.12.3**：
- **Node 版本10.16.0**：
- **操作系统 mac**：

**Comment by llfylwg** [comment]
没人理么 ？

**Comment by leftstick** [comment]
你的权限路由放在哪里的？

**Comment by llfylwg** [comment]
> 你的权限路由放在哪里的？

src/components/xxx

**Comment by liyuewen** [comment]
我现在也遇到这种情况了，请问你解决这个问题了么

**Comment by leftstick** [comment]
给个可复现的repo

**Comment by xiaohuoni** [comment]
为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN
