### ISSUE TITLE
怎么关闭umi项目的eslint？

### ISSUE THREAD

**Issue by 980961628** [umijs/umi#3922]
我已经把.eslintrc.js里面的eslint-config-umi去掉了，但是会有提示
// .eslintrc.js

```
module.exports={
  // "extends": "eslint-config-umi"
}
```

` Line 1:8:  'styles' is defined but never used  no-unused-vars`

**Comment by imhele** [comment]
[ENV/ESLINT](https://umijs.org/zh/guide/env-variables.html#eslint)

![image](https://user-images.githubusercontent.com/32428655/72486188-184fc000-3845-11ea-9878-17152a4b7891.png)
