### ISSUE TITLE
axios请求报500,400后，不深度刷新页面的情况下进入组件中再次触发请求，this.props.dispatch,不在被执行，其他非mode里面的异步方法可正常请求。这是为什么

### ISSUE THREAD

**Issue by jerry625257379** [umijs/umi#3929]
dva，组件中通过this.props.dispatch,调用mode里面的异步方法，请求方式是用的axios，如果请求服务器没有500,400，的错误返回，这this.props.dispatch，再次触发都正常，一旦服务器返回了这个500,400，那么再次触发这个this.props.dispatch，将不被执行，所以无法调用到dva里面的mode异步方法！------求大神解答下，这是为什么？急！

**Comment by jerry625257379** [comment]
组件中的部分代码：
componentDidMount=(props)=>{
		this.init();
	}
	init=()=>{
	    console.log(this.props)
		this.gethttp({
			//param_trade_type:this.state.selectValue,
			//param_curpage:this.state.pagination.page,
			//param_pagesize:this.state.pagination.size,
			//batch_id:this.state.selectedId
		},this.state.modetype)

	}
	gethttp=(parm,type)=>{
		const {dispatch}=this.props
		let consb=dispatch({
			 type:type,
			 parm:parm
		}).finally(res=>{
			//console.log(res)

		})
		
     }
mode中的代码：
export default {
	namespace:'mode',
	state: {
		mergeData:null
	},
	reducers:{
		BackQueryInvoice(state,{mergeData}){
			
			return { ...state,mergeData};
		}

	},
    effects:{

		*QueryInvoice({parm},{ call, put, select }){
			store.send();
			const response = yield call(API.getQueryInvoice,parm)
			try{  
				yield put({
					type: 'BackQueryInvoice', 
					mergeData:response, 
				});
				
			}catch(e){  
				console.log(e)
			}
			
		}
    },
    subscriptions: {
		setup({
		  dispatch, history, query, store,
		}) 
		{
		  return history.listen(({ pathname, search }) => {
			  
			if (pathname === '/TicketMerge') {
				//console.log('TicketMerge')
				//dispatch({ type: 'load' });
			}
		  });
		},
    }
  
};

**Comment by jerry625257379** [comment]
组件大致代码：
class TikeMerge extends React.Component {

	constructor(props) {  
		super(props);
		this.state = {
			selectValue:'0',
			selectedId:'0',,
			modetype:'mode/QueryInvoice',
			pagination:{
				page:'1',
				size:'6'
			}
		}
	}
    componentDidMount=(props)=>{
		this.init();
	}
	init=()=>{
	    console.log(this.props)
		this.gethttp({
			//param_trade_type:this.state.selectValue,
			//param_curpage:this.state.pagination.page,
			//param_pagesize:this.state.pagination.size,
			//batch_id:this.state.selectedId
		},this.state.modetype)

	}
	gethttp=(parm,type)=>{
		const {dispatch}=this.props
		let consb=dispatch({
			 type:type,
			 parm:parm
		}).finally(res=>{
			//console.log(res)

		})
		
     }
}

**Comment by xiaohuoni** [comment]
代码乱的没办法阅读，请提供一个重现库。提供了再reopen

**Comment by minzojian** [comment]
我也碰上同样的情况了. 只要effect中做网络接口调用返回错误,后边想再次做请求,消息虽然dispatch过去了,但是effect那边不被执行.不知道卡在什么地方了

**Comment by wwz223** [comment]
同上，有解决方法吗

**Comment by wwz223** [comment]
> 我也碰上同样的情况了. 只要effect中做网络接口调用返回错误,后边想再次做请求,消息虽然dispatch过去了,但是effect那边不被执行.不知道卡在什么地方了



> 我也碰上同样的情况了. 只要effect中做网络接口调用返回错误,后边想再次做请求,消息虽然dispatch过去了,但是effect那边不被执行.不知道卡在什么地方了

将异步方法用try catch 包起来就可以了，原因应该是错误没有被抛出，卡住了
