### ISSUE TITLE
 刷新浏览器，不展开路由相匹配的menu

### ISSUE THREAD

**Issue by duchaojie** [umijs/umi#3930]
## What happens?
使用create umi 创建ant-design-pro 项目并启动，刷新浏览器，不展开路由相匹配的菜单，菜单全部关闭了。

## How To Reproduce
**Steps to reproduce the behavior:**
1. 新创建ant-design-pro 项目，启动后刷新浏览器就可以复现问题

**Expected behavior**
1. 打开菜单，去到详情页，在详情页刷新浏览器，还能展开路由相应匹配菜单（高亮显示）.

- **Umi Version**:2.12.9
- **Node Version**:v10.14.1
- **Platform**:Mac

**Comment by xiaohuoni** [comment]
非umi问题，菜单问题请到pro的[issues区](https://github.com/ant-design/ant-design-pro/issues)提问吧。
