### ISSUE TITLE
如何通过config/config.js中的theme配置，使用antd v4 的dark theme?

### ISSUE THREAD

**Issue by jonahfang** [umijs/umi#3933]
如题。

**Comment by Szetta** [comment]
安装：`$ npm install @ant-design/dark-theme`
配置：`config/config.js`文件中：
```js
import darkTheme from '@ant-design/dark-theme';
theme: darkTheme,
```
或者
```js
import darkTheme from '@ant-design/dark-theme';
lessLoaderOptions: {
  ...
  modifyVars: darkTheme,
  ...
},
```
参考：
[ant-design-dark-theme](https://github.com/ant-design/ant-design-dark-theme)
[umi-theme](https://umijs.org/zh/config/#theme)

**Comment by jonahfang** [comment]
@Szetta ,谢谢，测试有效，完美!

**Comment by ycjcl868** [comment]
https://next.ant.design/docs/react/customize-theme-cn#%E4%BD%BF%E7%94%A8%E6%9A%97%E8%89%B2%E4%B8%BB%E9%A2%98

**Comment by jonahfang** [comment]
希望这个文档中添加商上述 config.js 配置的方法。

**Comment by ywy94ywy** [comment]
@jonahfang 你在umi里能用antdv4的icon么

**Comment by jonahfang** [comment]
@ywy94ywy 我已经放弃umi, 过去 1 个月都在使用cra.

**Comment by wuang1992** [comment]
> @jonahfang 你在umi里能用antdv4的icon么
不能，除非使用@antd-design/compatible , umi 依赖的是antd 3.x ,升级4.0.0之后一堆的问题

**Comment by damonZDM** [comment]
如何动态切换dark和light模式呢？
