### ISSUE TITLE
请问umi插件如何调试？

### ISSUE THREAD

**Issue by crixusshen** [umijs/umi#3943]
开发文档只有相关的开发指南和API，但是却没有如何调试一个自己写的umi，请问如何来调试自己编写的umi插件？

**Comment by xiaohuoni** [comment]
https://umijs.org/guide/plugin-develop#%E4%B8%BA%E6%8F%92%E4%BB%B6%E7%BC%96%E5%86%99%E6%B5%8B%E8%AF%95

**Comment by yutucc** [comment]
@xiaohuoni 大佬，文档打不开

**Comment by fz6m** [comment]
旧文档使用 `v3.umijs.org` 域名。
