### ISSUE TITLE
[Question] How can I wait for the store to finish in SSR?

### ISSUE THREAD

**Issue by shlomitsur** [umijs/umi#3945]
Hello Everybody,
When I do this in the server :
> const { ssrHtml } = await render(ctx);

I want that all of the effects that were invoked in getInitialProps() will be finished.
I think that in Saga it's something like this:

> await store.runSaga(rootSaga)

How can I do something like this in Umijs/Dva?
Thank you.

**Comment by vuquangthinh** [comment]
I saw in sourcecode of umi build.
getInitialProps will be used for window.g_initialData = {}. it's also used as initial data of dva (redux store).

=> you need create getInitialProps as promise function and return g_initialData.
in body of this function, await store.dispatch(initAction)

init action is a effect (in a model) and return all of current store data.
