### ISSUE TITLE
Module Warning from eslint-loader

### ISSUE THREAD

**Issue by cemremengu** [umijs/umi#3948]
## What happens?
When the app starts bunch of warnings from:

` ./node_modules/af-webpack/node_modules/eslint-loader/index.js`

## How To Reproduce
**Steps to reproduce the behavior:**
1. start any app

**Expected behavior**
1. no warnings

## Context

- **Umi Version*2.13.3*:
- **Node Version*12.x*:
- **Platform*windows*:

**Comment by cemremengu** [comment]
Never mind this is just regular unused warnings

**Comment by ifsc01** [comment]
@cemremengu 怎么过滤掉呢, 看起来别扭
