### ISSUE TITLE
[QUESTION] 请问一下如何引入wasm文件

### ISSUE THREAD

**Issue by anonymous-qsh** [umijs/umi#3951]
我有参考https://github.com/umijs/umi/pull/918之前这个issues, 但是我还是没有看明白我应该如何正确的引入wasm文件, 我直接import的话, 会报错
```ts
 import('./m.wasm').then(m => {
      console.log(m);
 })
```

报错信息:

This dependency was not found:

* env in ./.../m.wasm

**Comment by xiaohuoni** [comment]
可以在[chainwebpack](https://umijs.org/config#chainwebpack) 中试试 https://www.npmjs.com/package/wasm-module-webpack-plugin

**Comment by rise0chen** [comment]
折腾了2天终于折腾出来了，在配置文件里把`dynamicImport`或者`dynamicImportSyntax`打开即可
