### ISSUE TITLE
Replace react-loadable

### ISSUE THREAD

**Issue by tomtxcx** [umijs/umi#3959]
Hi,
because umiJS uses the dead project react-loadable ([issue](https://github.com/bbc/simorgh/issues/3087), [pull-request](https://github.com/jamiebuilds/react-loadable/pull/195)) this error always appears in the console:
```
react-dom.development.js:12357 Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: LoadableComponent
```
```
$ npm ls react-loadable
`-- umi@2.13.3
  `-- react-loadable@5.5.0 
```

It would be super nice if you replace it with an equivalent library. Maybe [loadable-components](https://github.com/gregberge/loadable-components) does a good job.

Thanks,
Tom

**Comment by sorrycc** [comment]
loadable-components is too heavy, I used [a modified version of react-loadable](https://github.com/umijs/umi-next/commit/13de4663c84d09e413eb1309d109f11d8ff7c487) in umi@3.

**Comment by yoyo837** [comment]
How about [@loadable/component](https://github.com/gregberge/loadable-components) ?

**Comment by tranvansang** [comment]
`react-loadable` is great. [@react-loadable/revised](https://www.npmjs.com/package/@react-loadable/revised) is an in-maintenance version of it, and a good option for modern applications.
