### ISSUE TITLE
umi-plugin-react配置scripts, 无法引入

### ISSUE THREAD

**Issue by Renderz** [umijs/umi#3960]
## What happens?
umi-plugin-react配置中配置了scripts, dev的时候会无法找到文件路径返回首页html.

## Mini Showcase Repository(REQUIRED)

复现仓库
https://github.com/Renderz/testumi

## How To Reproduce
**Steps to reproduce the behavior:**
1. 项目根目录创建一个test.js 内容只有console.log('test')
2. 配置项如下
```
const umiPluginReactOption = {
    scripts: [
        { src: '/test.js' }
    ]
}

const config = {
    publicPath: '/',
    plugins: [
        ['umi-plugin-react', umiPluginReactOption],
    ]
}

export default config;
```

**Expected behavior**
1.  没有正确找到test.js位置, 返回html.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
把 test.js 放到 `public` 目录下。
