### ISSUE TITLE
有没有Umi的调试工具？

### ISSUE THREAD

**Issue by chengtie** [umijs/umi#3961]
大家好，

我在没用umi之前会用[Redux-devtools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en)来帮助调试Redux，很好用。

我想知道用了umi之后这个工具还仍然很好用吗（我看好像多了很多不是我代码设置的信息）？或者有什么其他工具可以帮助调试umi+redux呢？

谢谢

**Comment by sorrycc** [comment]
可以继续用 redux-devtool，不冲突。

**Comment by chengtie** [comment]
@sorrycc 谢谢，那用于umi调试还有其他的、更好的吗？
