### ISSUE TITLE
umi增加babel-runtime-jsx-plus插件报错

### ISSUE THREAD

**Issue by wittech** [umijs/umi#3965]
extraBabelPlugins: [
    "module:babel-runtime-jsx-plus"
]
在umijs中增加babel扩展插件，运行时报错：

 error  in ./src/pages/.umi/history.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Must export a default export when using ES6 modules.

 error  in ./node_modules/@uform/antd/esm/index.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Must export a default export when using ES6 modules.

**Comment by sorrycc** [comment]
如果是加了 babel-runtime-jsx-plus 的原因，说明是 babel-runtime-jsx-plus 修改了代码导致。

**Comment by wittech** [comment]
应该是webpack babel 禁止编译部分 node_modules，请问如何在umijs中配置类似这样的规则：
{
                test: /\.jsx$/,
                exclude: /node_modules/,
                loader: "babel",
                query: {
                presets: ['es2015', 'react', 'stage-0']
            }
            },
            {

                test: /\.js$/,
                exclude: /node_modules/, 
                loader: "babel",
                query: {
                presets: ['es2015', 'stage-0']
            }

**Comment by wittech** [comment]
已经解决，ts貌似不支持，换成js了。
