### ISSUE TITLE
开启singular后无法加载model内的模块

### ISSUE THREAD

**Issue by Instanced** [umijs/umi#397]
开启singular后，更改models文件夹名称为model后无法加载model内的文件。。

`.umirc.js` 配置

```
export default {
  plugins: ['umi-plugin-dva'],
  hashHistory: true,
  singular: true,
}
```

**Comment by xiaohuoni** [comment]
你是修改src/models还是src/page/xxx/models?

**Comment by xiaohuoni** [comment]
我在这里面试了，是正常的
https://github.com/xiaohuoni/umi-examples/tree/master/with-dva-singular

**Comment by Instanced** [comment]
@xiaohuoni 你好，我这边用了你上面的示例仍然无法加载， [https://github.com/Instanced/with-dva-singular.git](https://github.com/Instanced/with-dva-singular.git)

> 本地环境
>  node -v
v9.11.1
npm -v
5.6.0

**Comment by xiaohuoni** [comment]
提示什么错误，或者程序走到哪一步了

**Comment by Instanced** [comment]
@xiaohuoni 奇怪了，我用的`dva  new`创建的项目，我发现我现在的插件版本跟你的不一样啊 ，，我本地是还是 `"umi-plugin-dva": "^0.1.5"`。。你那边的都0.6x了，。

**Comment by xiaohuoni** [comment]
没什么关系可能版本号写在脚手架里面了。你装一个npm-check检测更新一下就好了

**Comment by Instanced** [comment]
好，我升级下版本试试看，谢了

**Comment by xiaohuoni** [comment]
你慢慢你是不是全局装过umi。没有更新。你下我给的例子里面应该都是最新的

**Comment by Instanced** [comment]
果然是版本的问题。现在解决了...
