### ISSUE TITLE
[Feature Request] support set global form validateMessages for antd v4

### ISSUE THREAD

**Issue by zmayor** [umijs/umi#3970]
## Background

The antd v4 support [set global form validateMessages template](https://next.ant.design/components/form-cn/#validateMessages). However, I cannot set any configuration on ConfigProvider in an umi project.

## Proposal

I want to be accessible to add some settings on ConfigProvider.

**Comment by xiaohuoni** [comment]
https://umijs.org/plugins/plugin-antd#config
