### ISSUE TITLE
'umi-plugin-locale' use 'ConfigProvider' from "antd/lib",but antd Modal.confirm use 'antd/es/modal'

### ISSUE THREAD

**Issue by kanweiwei** [umijs/umi#3971]
## What happens?
antd modal.confirm locale didn't work expectedly. Because we often use `import { Modal } from "antd"`, the path is "antd/es/modal".  The locale.jsx of `modal` component  will work expectedly;
https://github.com/ant-design/ant-design/blob/30a3ac63ef79b96029578f8e6eb6f50c2240527a/components/modal/locale.tsx#L9-L28

现象：
locale设置zh-CN了，但是antd的modal.confirm 还是英文显示。

原因：
umi-plugin-locale 用的是antd/lib目录里的 ConfigProvider 组件，导致它在调Modal组件的locale.jsx文件里的changeConfirmLocale方法时改变的不是我预期的runtimeLocale变量。我们平常用的modal.confirm 都是引用的 antd/es 目录。这两个runtimeLocale不是同一个。

.umi 目录下的 LocalWrapper.jsx里是这样的
···
 // antd 3.21.0 use ConfigProvider not LocaleProvider
     const isConfigProvider = Number(major) > 3 || (Number(major) >= 3 && Number(minor) >= 21);
     if (isConfigProvider) {
       try {
         AntdProvider = require('antd/lib/config-provider').default;
       } catch (e) {}
     }
···

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1. 

**Expected behavior**
1. 修改umi-plugin-locale，或者有什么配置可以使umi编译时用 antd/lib里的代码
2.

## Context

- **Umi Version**: 2.13.3
- **Node Version**: v10.16.3
- **Platform**: mac os

**Comment by fanyonglong** [comment]
解决了?遇到一样的问题了

**Comment by kanweiwei** [comment]
> 解决了?遇到一样的问题了
pakage.json/scripts 启动的时候，加个ANTD_IMPORT_DIRECTORY的环境变量
"start": "cross-env  ANTD_IMPORT_DIRECTORY=lib umi dev",
