### ISSUE TITLE
Safari Browser SyntaxError: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by big-MuMu** [umijs/umi#3978]
## What happens?
antd-pro 项目运行报错，谷歌正常，safari,firefox 报错
"umi": "^2.8.7",
![image](https://user-images.githubusercontent.com/26105552/74823194-498a4700-5341-11ea-9caa-1ecea801df3a.png)

**Comment by hl1002426580** [comment]
我也遇到了同样的问题

**Comment by shinymm** [comment]
“SyntaxError: Invalid regular expression: invalid group specifier name” 我也遇到同样问题，本地启动项目后，safari 上打开就报错，其他浏览器没问题。但是在非本地环境，safari 就不报这个错，请问改怎么解决？

**Comment by hudson-dong** [comment]
请问这个解决了吗? 今天本地启动项目在safari上出现了

**Comment by axl-axl** [comment]
进到代码内部看到是url路由添加的地方使用的正则表达式safari不支持导致的，不能做个内部监听吗？感觉应该很好处理才对，为什么会一年多了还没解决。😣
