### ISSUE TITLE
windows下umi ui Error: spawn sh ENOENT退出

### ISSUE THREAD

**Issue by duwei54** [umijs/umi#3981]
## What happens?
`yarn create umi` 创建的初始项目
通过uimi ui 执行任何任务均报错退出
![image](https://user-images.githubusercontent.com/8448880/74926896-a1907e80-5411-11ea-8d37-ca0ae7b49d59.png)

## 相关环境信息

- **Umi 版本**：2.13.0
- **Node 版本**：v12.16.0
- **操作系统**：win10

和这个 https://github.com/umijs/umi/issues/3747 问题有点像,但是报错原因不同
不知道是不是我电脑环境原因

**Comment by yuwade** [comment]
我的也是出现这个错误,而且还是乱码

**Comment by pccai** [comment]
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: spawn sh ENOENT

**Comment by wisenchen** [comment]
> 我的也是出现这个错误,而且还是乱码

我现在也是这样，请求问老哥这个问题解决了吗？

**Comment by xiaodun** [comment]
删掉node_modules 并重新安装
