### ISSUE TITLE
如何声明路由参数类型？

### ISSUE THREAD

**Issue by dickeylth** [umijs/umi#3983]
## What happens?

路由参数捕获声明类型遇到问题，参照 [react-router 的文档](https://www.pluralsight.com/guides/react-router-typescript) 也没有解决：

![image](https://user-images.githubusercontent.com/2196373/75017555-381f7700-54c8-11ea-907e-188c028272a4.png)
![image](https://user-images.githubusercontent.com/2196373/75017590-47062980-54c8-11ea-9bfc-139c547b2f46.png)
![image](https://user-images.githubusercontent.com/2196373/75017618-59806300-54c8-11ea-82c2-179cc840b0b7.png)

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：2.13.3
- **Node 版本**：10.17.0
- **操作系统**：macOS 10.15.3

**Comment by fjc0k** [comment]
umi3 的话可以考虑下这个插件：https://github.com/fjc0k/umi-plugin-router-plus
