### ISSUE TITLE
生产环境配置路由，可以把css和js打包到static目录

### ISSUE THREAD

**Issue by fangaofeng** [umijs/umi#3984]
创建了最新版本的umi脚手架，但是umi build之后发现js,css,等静态资源都和html在同一级别下，想要把css放到一个文件夹，js放到一个文件夹，图片资源放到一个文件夹，然后整合到static文件夹下，找了官网api没有这中配置

**Comment by MinJieLiu** [comment]
chainWebpack 配置
```js
const hash = !isDev ? '.[contenthash:8]' : '';
config.output.chunkFilename(`js/[name]${hash}.async.js`);

config.plugin('extract-css').tap(args => [
  {
    ...args[0],
    chunkFilename: `css/[name]${hash}.chunk.css`,
  },
]);
```
可以试试

**Comment by poet-CN** [comment]
> chainWebpack 配置
> 
> ```js
> const isDev = process.env.NODE_ENV === 'development';
> 
> const hash = !isDev ? '.[contenthash:8]' : '';
> config.output.chunkFilename(`js/[name]${hash}.async.js`);
> 
> config.plugin('extract-css').tap(args => [
>   {
>     ...args[0],
>     chunkFilename: `css/[name]${hash}.chunk.css`,
>   },
> ]);
> ```
> 
> 可以试试

依照您的方法试了一下，但发现umi.js和umi.css还是在dist的根目录下。

**Comment by MinJieLiu** [comment]
是这样配的吗
```ts
...
chainWebpack(config: IWebpackChainConfig) {
  const isDev = process.env.NODE_ENV === 'development';
  const hash = !isDev ? '.[contenthash:8]' : '';
  config.output.chunkFilename(`js/[name]${hash}.async.js`);

  config.plugin('extract-css').tap(args => [
    {
      ...args[0],
      chunkFilename: `css/[name]${hash}.chunk.css`,
    },
  ]);
},
...
```

**Comment by poet-CN** [comment]
> ```ts
> chainWebpack(config: IWebpackChainConfig) {
>   const isDev = process.env.NODE_ENV === 'development';
>   const hash = !isDev ? '.[contenthash:8]' : '';
>   config.output.chunkFilename(`js/[name]${hash}.async.js`);
> 
>   config.plugin('extract-css').tap(args => [
>     {
>       ...args[0],
>       chunkFilename: `css/[name]${hash}.chunk.css`,
>     },
>   ]);
> },
> ```

是的，我使用的umi版本是3.0.12，最终生成的目录结构如下
> dist
> - css
> - js
> - static
> - index.html
> - umi.(hash).css
> - umi.(hash).js

**Comment by poet-CN** [comment]
> 是这样配的吗
> 
> ```ts
> ...
> chainWebpack(config: IWebpackChainConfig) {
>   const isDev = process.env.NODE_ENV === 'development';
>   const hash = !isDev ? '.[contenthash:8]' : '';
>   config.output.chunkFilename(`js/[name]${hash}.async.js`);
> 
>   config.plugin('extract-css').tap(args => [
>     {
>       ...args[0],
>       chunkFilename: `css/[name]${hash}.chunk.css`,
>     },
>   ]);
> },
> ...
> ```

我的.umirc.ts的配置是
> ```
> history: { type: 'hash' },
> routes: routerConfig,
> dynamicImport: {
>     loading: '@/pages/Loading',
> },
> publicPath: 'xxxxx',
> hash: true,
> chainWebpack: (config) => {
>     const isDev = process.env.NODE_ENV === 'development';
>      const hash = !isDev ? '.[contenthash:8]' : '';
>     config.output.chunkFilename(`js/[name]${hash}.async.js`);
>     config.plugin('extract-css').tap(args => [
>         {
>             ...args[0],
>             chunkFilename: `css/[name]${hash}.chunk.css`,
>         },
>     ]);
> }
> ```

**Comment by poet-CN** [comment]
> 是这样配的吗
> 
> ```ts
> ...
> chainWebpack(config: IWebpackChainConfig) {
>   const isDev = process.env.NODE_ENV === 'development';
>   const hash = !isDev ? '.[contenthash:8]' : '';
>   config.output.chunkFilename(`js/[name]${hash}.async.js`);
> 
>   config.plugin('extract-css').tap(args => [
>     {
>       ...args[0],
>       chunkFilename: `css/[name]${hash}.chunk.css`,
>     },
>   ]);
> },
> ...
> ```

我最终选择了使用node来进行编译后的移动，不过这个问题相关的解答我也会持续关注

**Comment by MinJieLiu** [comment]
umi.(hash).css
umi.(hash).js
上面那个配置没做处理，其实保持这两个在根目录影响不大吧，主要是数量不多。
如果你必须要移动的话，得改一下代码，加一行
```js
config.output.filename(`js/[name]${hash}.js`);
```
css，你看着办^-^

**Comment by poet-CN** [comment]
> umi.(hash).css
> umi.(hash).js
> 上面那个配置没做处理，其实保持这两个在根目录影响不大吧，主要是数量不多。
> 如果你必须要移动的话，得改一下代码，加一行
> 
> ```js
> config.output.filename(`js/[name]${hash}.js`);
> ```
> 
> css，你看着办^-^

多谢

**Comment by Fntys** [comment]
> umi.(hash).css
> umi.(hash).js
> 上面那个配置没做处理，其实保持这两个在根目录影响不大吧，主要是数量不多。
> 如果你必须要移动的话，得改一下代码，加一行
> 
> ```js
> config.output.filename(`js/[name]${hash}.js`);
> ```
> 
> css，你看着办^-^

请问下打包出来的图片，不要hash，怎么操作？

**Comment by sstshenshutao** [comment]
export default defineConfig({  
  chainWebpack: function(config, { webpack }) {
    const isDev = process.env.NODE_ENV === 'development';
    const hash = !isDev ? '.[contenthash:8]' : '';
    config.output.chunkFilename(`js/[name]${hash}.async.js`);
    config.output.filename(`static/[name]${hash}.js`);
    config.plugin('extract-css').tap(args => [
      {
        ...args[0],
        chunkFilename: `css/[name]${hash}.chunk.css`,
        filename: `static/[name]${hash}.css`,
      },
    ]);
  },
});

**Comment by 426-330** [comment]
umi4这样配置不行了。。。。
