### ISSUE TITLE
IE中的'Proxy' is undefined错误

### ISSUE THREAD

**Issue by chengtie** [umijs/umi#3985]
你好，

我们有一款Excel add-in是用React+Node+Umi做的. 它的登录系统在Chrome和Safari里都好使，但是我们发现在 IE 里会出错; F12 会报错 `'Proxy' is undefined`.

虽然这个工具应该在Excel里面使用，但是有些测试也可以在浏览器里面做。比如，在IE中打 https://jsaddin.10studio.tech/welcome/?next=formulaEditor, 用ID `3094557608@qq.com`和密码`123456`登录。我们就可以在F12中看到错误信息。

![Screenshot 2020-02-22 at 04 10 58](https://user-images.githubusercontent.com/774409/75085675-d1cc4000-552b-11ea-9b7b-3775eb5befee.png)

下面是我们使用的Umi版本：
```
 "umi": "^2.7.0",
 "umi-plugin-react": "^1.8.0",
 "umi-types": "^0.2.0"
```

在代码中，我们也加了：
```
 targets: {
   ie: 9,
   safari: 9,
 },
```

请问这个错误信息是否和Umi有关呢？如果和Umi有关，应该如何解决呢？

谢谢

Tie

**Comment by xiaohuoni** [comment]
相同的问题 https://github.com/umijs/umi/issues/5428
