### ISSUE TITLE
UmiJS之我见

### ISSUE THREAD

**Issue by axolo** [umijs/umi#3989]
结合ant design pro的几点个人浅见，若有冒犯或说得不对，请一笑而过。

- 框架是一个有机体，需要整体规划逻辑和实现，不仅仅是简单整合了Redux、Router、Saga
- 配置需考虑各种场景，不仅仅是defaultSettings，.env他真香
- 污染全局环境真没必要，框架自身全局提供app和ctx岂不更好，app.routes，app.store不比window.g_*更香
- 作为一个框架来说，显式加入插件和中间件机制很必要，不能全扔src/utils下吧
- 文件、常量、变量命名需规范，大小写一致且互相对应（model/setting -> state.settings）
- Webpack自有配置足够赏心悦目而且已经深入人心，没必要拆得七零八落
- 萝卜青菜各有所爱，ESLint配置务必开放，提交时不必自动格式化代码
- 没有必要每个routes挂个404尾巴，猿猴是时候进化成人类了
- Layout和Page虽然都是组件，在路由里作为同等公民会导致路由层级过深判断不易，不如Page按需指定自己的Layout或在路由配置里增加layout参数

总之，框架的归框架，依赖的归依赖，开发的归开发，运行的归运行，上帝的归上帝，撒旦的归撒旦，众神归位。

**Comment by xiaohuoni** [comment]
@chenshuai2144 cc

**Comment by ahuigo** [comment]
显式加入插件和中间件机制 +1
Webpack自有配置+1

ps:
ESLint配置是开放的，根目录下放一个.eslintrc.js

```
// .eslintrc.js
module.exports = {
    extends: [require.resolve('@umijs/fabric/dist/eslint')],
    globals: {
        ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION: true,
        page: true,
    },
    rules: {
        'no-else-return': 'off',
        'prefer-template': 'off',

```
