### ISSUE TITLE
Mock dynamic matching route

### ISSUE THREAD

**Issue by fatefate0727** [umijs/umi#3993]
### I want mock to dynamically match interface routes similar to the following rules

`POST /api/test/{data1}/{data2}`

The above {data1} and {data2} are uncertain data, but I didn't find a way to dynamically match them

I need help, please let me know if there is a solution

**Comment by scplay** [comment]
I think you can use `POST /api/test/:data1/:data2`

Seems mock server use express under the hood, you may use same route match as [express](https://expressjs.com/en/guide/routing.html)

see packages/preset-umi/src/commands/preview.ts:63

```javascript
const app = express();

...
      app.use(
        createMockMiddleware({
          context: {
            mockData: getMockData({
              cwd: api.cwd,
              mockConfig: api.config.mock || {},
            }),
          },
        }),
      );
```
