### ISSUE TITLE
exportStatic 是否支持某些路由导出静态页面

### ISSUE THREAD

**Issue by lichenbuliren** [umijs/umi#3994]
## 问题

在阅读了官方的 API 配置文档与翻阅源码之后，发现导出静态页面的是全量导出的，
但是 exportStatic 又不支持动态路由；所以这里就像问下是否有支持指定路由导出的配置方式

**Comment by sorrycc** [comment]
指定的是静态路由还是动态路由？

**Comment by xiaohuoni** [comment]
@lichenbuliren cc

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
