### ISSUE TITLE
创建antdpro时，不选择antd@4会报错

### ISSUE THREAD

**Issue by detonateyin** [umijs/umi#3997]
## What happens?
使用`npm create umi`时选择不用antd@4会报错

## How To Reproduce
**Steps to reproduce the behavior:**
1. `npm create umi`
2. `? Select the boilerplate type`-- Pick `ant-design-pro`
3. ` ? 🤓 Which language do you want to use? `-- Pick `JavaScript`
4. `? 🦄 Time to use better, faster and latest antd@4! `-- Pick `No`

## Context

- **Umi Version**:v2.13.3
- **Node Version**:v12.16.1
- **Create-umi Version**:v0.20.1
- **Platform**:macOs v10.14.6

## Log

    ? Select the boilerplate type ant-design-pro
    ? 🤓 Which language do you want to use? JavaScript
    ? 🦄 Time to use better, faster and latest antd@4! No
    events.js:288
          throw er; // Unhandled 'error' event
          ^
    
    TypeError: self.env.emit is not a function
        at /Users/xxxx/.npm/_npx/15815/lib/node_modules/create-umi/node_modules/yeoman-generator/lib/index.js:653:22
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
    Emitted 'error' event on AntDesignProGenerator instance at:
        at Immediate.<anonymous> (/Users/xxxx/.npm/_npx/15815/lib/node_modules/create-umi/node_modules/yeoman-generator/lib/index.js:668:20)
        at processImmediate (internal/timers.js:456:21)

**Comment by newmann** [comment]
不管选不选，都报错

**Comment by detonateyin** [comment]
> 不管选不选，都报错

对，提完issue就发现了🤣

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
