### ISSUE TITLE
TypeError: self.env.emit is not a function

### ISSUE THREAD

**Issue by fengme** [umijs/umi#3998]
## What happens?
When executing the command "yarn create umi", then select antd in the step "What functionality do you want to enable? antd" and then press ENTER, the whole process will always exit and get the following exception:
? What functionality do you want to enable? antd
events.js:298
      throw er; // Unhandled 'error' event
      ^

TypeError: self.env.emit is not a function
    at /usr/local/share/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:653:22
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Emitted 'error' event on Generator instance at:
    at Immediate.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:668:20)
    at processImmediate (internal/timers.js:456:21)
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-umi
Arguments: 
Directory: /data/projects/umi1
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

I cannot believe I still can meet such a bug like the above one in the project. Are there any solutions?

## Context
[root@localhost umi1]# umi -v
2.13.3
[root@localhost umi1]# node -v
v13.9.0

[root@localhost umi1]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

**Comment by fmfmfmfm** [comment]
Me too

**Comment by fengme** [comment]
How to address it?

**Comment by freeznet** [comment]
here is a temporary solution:

add a dep resolution to your yarn global `package.json` file.
your global `package.json` can be find from the error log. Such as 

```
TypeError: self.env.emit is not a function
at /usr/local/share/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:653:22
```

so your global `package.json` is at `/usr/local/share/.config/yarn/global/package.json`

then your global `package.json` should look like
```
{
  "dependencies": {
    "create-umi": "^0.20.1"
  },
  "resolutions": {
    "create-umi/yeoman-generator": "4.5.0"
  }
}
```

after the change, run again with `yarn create umi`

**Comment by fengnex** [comment]
@freeznet It worked, thank you!

But what make me suprise is that umi 2.0.0, umi 2.13.0 and umi 2.13.1 all have the bug. I have thought that both umi and antd are excellent, but now I'm afraid they are not mature enough. Do you agree?

**Comment by iplash** [comment]
me too
