### ISSUE TITLE
SourceMapDevToolPlugin 配置后不生效，不能成功注入 sourceMappingURL

### ISSUE THREAD

**Issue by elevensky** [umijs/umi#3999]
## What happens?
配置 SourceMapDevToolPlugin 插件自定义sourcemap 生成规则不生效。

## Mini Showcase Repository(REQUIRED)
demo: https://codesandbox.io/s/umi-example-lz9bf

## How To Reproduce
1. bash 下 yarn build
2. 查看 ls dist/ 没有.map文件生成
**Expected behavior**
切望能够正确生成.map文件，并正确写入 `# sourceMappingURL=http://example.com/sourcemap/[url]`

## Context

- **Umi Version**: latest
- **Node Version**: v10.17.0
- **Platform**: sandbox

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
