### ISSUE TITLE
'@umijs/plugin-qiankun' 主应用不支持设置base、publicPath

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#4010]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
比如 app1 的base /app1   app2的base 为app2/
 master节点不设置base可以正常用，但是master设置了base 就不能正常用
**Expected behavior**
master设置了base也可以正常用

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by cuijiudai** [comment]
还是有这个问题啊

**Comment by buquan** [comment]
请问这个有解决办法了吗，我主应用配置了base和publicPath一样的值，但是子应用bootstrap的打印变成了 ` /base//微前端入口路径`, 多了一个/

**Comment by cl1107** [comment]
> 请问这个有解决办法了吗，我主应用配置了base和publicPath一样的值，但是子应用bootstrap的打印变成了 ` /base//`微前端入口路径, 多了一个/

你的主应用base是不是配置成/结尾了，如： /main/ 需要改成 /main

**Comment by buquan** [comment]
> > 请问这个有解决办法了吗，我主应用配置了base和publicPath一样的值，但是子应用bootstrap的打印变成了 ` /base//`微前端入口路径, 多了一个/
> 
> 你的主应用base是不是配置成/结尾了，如： /main/ 需要改成 /main

是的 就是按照你说的可以了，只能这么hack处理了
