### ISSUE TITLE
打包以及start失败  ./src/.umi/core/umiExports.ts   

### ISSUE THREAD

**Issue by INTMIN** [umijs/umi#4020]
## What happens?

yarn run start的时候编译生成的控制台报错umiExports.ts 里面的
>This relative module was not found: 
>../plugin-initial-stateexports in ./src/.umi/core/umiExports.ts 
把文件内的  
>export * from '../plugin-initial-state\exports';改成
>export * from '../plugin-initial-state/exports';
就可以正常启动了，但是打包的时候无法介入  

我的是windows系统
## 版本号

- **Umi Version**: 3.0
- **Node Version**:12.
- **Platform**: windows10

**Comment by ywy94ywy** [comment]
+1

**Comment by 200ljx** [comment]
+1

**Comment by userhjp** [comment]
刚开始我也有这问题，但是我将node_modules 和 yarn.lock 干掉后重新 yarn install 就好了

**Comment by INTMIN** [comment]
@userhjp 感谢，问题解决了

**Comment by liutian** [comment]
现在安装最新版本还是有这个问题
