### ISSUE TITLE
快速上手 + layout:{}, 报错

### ISSUE THREAD

**Issue by kaoding** [umijs/umi#4021]
## What happens?
import { defineConfig } from 'umi';

```
export default defineConfig({'{'}
+ layout: {},
  routes: [
    {'{'} path: '/', component: '@/pages/index' {'}'},
  ],
});
```

![image](https://user-images.githubusercontent.com/18542211/75644514-8299b400-5c7d-11ea-8e4c-dd2455a25efc.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create umi` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by ywy94ywy** [comment]
+1
