### ISSUE TITLE
导出路径错误

### ISSUE THREAD

**Issue by uncle-link** [umijs/umi#4022]
umi3.0 启动失败
![image](https://user-images.githubusercontent.com/15264018/75644490-77468880-5c7d-11ea-84a0-d42c2efa18cf.png)

- **Umi Version**: 3
- **Node Version**: 12.3.1
- **Platform**: windows

**Comment by kaoding** [comment]
https://github.com/umijs/umi/issues/4021

**Comment by kaoding** [comment]
https://github.com/umijs/umi/issues/4020

**Comment by ywy94ywy** [comment]
+1

**Comment by sorrycc** [comment]
昨天的 3.0.1 修复了。
