### ISSUE TITLE
routes 配置文档描述不一致

### ISSUE THREAD

**Issue by xusai2014** [umijs/umi#4025]
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：
https://github.com/umijs/umi/blob/d32880d4eb9236f13d7c05a21e99930cdac2c08a/docs/docs/upgrade-to-umi-3.zh-CN.md
![image](https://user-images.githubusercontent.com/8156165/75647290-816d8480-5c87-11ea-8cfc-7e9c5c8670a1.png)
![image](https://user-images.githubusercontent.com/8156165/75647317-96e2ae80-5c87-11ea-89aa-8f1391f0153a.png)

routes描述不一致

**Comment by DevilRoshan** [comment]
这里删除的是插件的配置项吧

**Comment by ycjcl868** [comment]
删除了 `umi-plugin-react` 的 `routes 配置项`
