### ISSUE TITLE
getInitialState默认启用

### ISSUE THREAD

**Issue by Kol96** [umijs/umi#4027]
## What happens?

项目中有app.js 但没导出getInitialState方法，启动时提示如下信息

```
warning  in ./src/.umi/plugin-initial-state/models/initialState.ts

"export 'getInitialState' (imported as 'app') was not found in '@/app'
```

## How To Reproduce

**Steps to reproduce the behavior:** 

1.  存在app.js但无getInitialState 
2. 启动项目yarn start

**Expected behavior** 

1. 项目正常启动

## Context

- **Umi Version**: 3.0.0
- **Node Version**: 10.16.13
- **Platform**: mac

**Comment by Kol96** [comment]
> ## What happens?
> 项目中有app.js 但没导出getInitialState方法，启动时提示如下信息
> 
> ```
> warning  in ./src/.umi/plugin-initial-state/models/initialState.ts
> 
> "export 'getInitialState' (imported as 'app') was not found in '@/app'
> ```
> 
> ## How To Reproduce
> **Steps to reproduce the behavior:**
> 
> 1. 存在app.js但无getInitialState
> 2. 启动项目yarn start
> 
> **Expected behavior**
> 
> 1. 项目正常启动
> 
> ## Context
> * **Umi Version**: 3.0.0
> * **Node Version**: 10.16.13
> * **Platform**: mac

配置文件设置initialState: false可以暂时避免这个问题

**Comment by Kol96** [comment]
配置文件设置initialState: false可以暂时避免这个问题

**Comment by duan602728596** [comment]
或者在`app.js`文件内加上
```javascript
export function getInitialState() {
  return {};
}
```
