### ISSUE TITLE
formatMessage API只能在pages目录下？

### ISSUE THREAD

**Issue by six-666** [umijs/umi#4031]
以下代码在 pages 目录下正常， 但是在其他目录下会返回空。
```
import { formatMessage } from 'umi/locale';
const TITLE_FILTER_SORT = formatMessage({
  id: 'demo',
});

console.log(TITLE_FILTER_SORT)  // null
```

补充： 后来发现是提前加载的原因，定时2秒后会正常， 这应该是个Bug?

**Comment by xiaohuoni** [comment]
说明一下版本号，按模版填写issues吧

**Comment by lemovel** [comment]
> 以下代码在 pages 目录下正常， 但是在其他目录下会返回空。
> 
> ```
> import { formatMessage } from 'umi/locale';
> const TITLE_FILTER_SORT = formatMessage({
>   id: 'demo',
> });
> 
> console.log(TITLE_FILTER_SORT)  // null
> ```
> 
> 补充： 后来发现是提前加载的原因，定时2秒后会正常， 这应该是个Bug?

我也碰到了这个问题，请问你怎么解决的？
