### ISSUE TITLE
antdpro迁移失败

### ISSUE THREAD

**Issue by jaysg** [umijs/umi#4032]
#3484  What happens?
拉取antdpro@v4
修改package.json文件下的umi2.x => 3.x
再根据 UMI官网#升级到 Umi 3做出一系列的修改
结果无法正常启动项目

- **Umi 版本**：3.x
- **Node 版本**：10.15
- **操作系统**：WIN10

**Comment by snice** [comment]
我的是成功的，https://github.com/gadmins/admin-react/tree/develop/antd-pro
