### ISSUE TITLE
移除urlLoaderExcludes 后 怎么排除处理 svg文件

### ISSUE THREAD

**Issue by userhjp** [umijs/umi#4035]
> 以前这样使用引入svg 需要 排除处理.svg文件，现在移除urlLoaderExcludes 后怎么排除处理.svg 交由svg-sprite-loader处理？？ 求解
```bash
  urlLoaderExcludes: [/.svg$/],
  chainWebpack(config) {
    config.module
      .rule('svg')
      .test(/.svg$/)
      .use('svg-sprite-loader')
      .loader('svg-sprite-loader');
  },
```

**Comment by userhjp** [comment]
前面加上一句：config.module.rules.delete('svg');  删除处理svg文件

**Comment by yckbilly1929** [comment]
更新到v3後沒了urlLoaderExcludes，要怎麼配置svg icon?

The above error occurred in the </static/test-logo.79dd321c.svg> component

試了一下上面的也不行，跟antd v4文檔里的方法也不一樣
```
chainWebpack(config) {
    config.module.rules.delete('svg');
    config.module
      .rule('svg')
      .test(/.svg$/)
      .use('svg-sprite-loader')
      .loader('svg-sprite-loader');
  },
```
```
import Icon from '@ant-design/icons';
import TestHeaderLogo from '../assets/images/test-logo.svg';

...
<Icon className='logo' component={TestHeaderLogo} />
```

**Comment by userhjp** [comment]
> 更新到v3後沒了urlLoaderExcludes，要怎麼配置svg icon?
> 
> The above error occurred in the </static/test-logo.79dd321c.svg> component
> 
> 試了一下上面的也不行，跟antd v4文檔里的方法也不一樣
> 
> ```
> chainWebpack(config) {
>     config.module.rules.delete('svg');
>     config.module
>       .rule('svg')
>       .test(/.svg$/)
>       .use('svg-sprite-loader')
>       .loader('svg-sprite-loader');
>   },
> ```
> 
> ```
> import Icon from '@ant-design/icons';
> import TestHeaderLogo from '@/assets/images/test-logo.svg';
> 
> ...
> <Icon className='logo' component={TestHeaderLogo} />
> ```

我这边是用的移动端的antd-mobile,这样配置后是正常的，urlLoaderExcludes 只是用于排除其他loader处理svg文件，svg交给svg-sprite-loader处理
```
import React from 'react';
// 使用
// <Icon size="xxs" type={require('../../assets/icons/add.svg')} />
type IconProps = {
    type?: any,
    className?: string,
    size: 'xxs' | 'xs'| 'sm'| 'md'| 'lg',
    [key: string]: any
}

const KIcon = ({ type, className = '', size = 'md', ...restProps }: IconProps) => (
     <svg
       className={`am-icon am-icon-${type.default.id} am-icon-${size} ${className}`}
       {...restProps}
     >
       <use xlinkHref={`#${type.default.id}`} />
     </svg>
 );
export default KIcon;

///配置文件修改
  chainWebpack(config) {
    config.module.rules.delete('svg'); // 删除其他loader处理svg
    config.module
      .rule('svg')
      .test(/\.svg$/)
      .use('svg-sprite-loader')
      .loader('svg-sprite-loader')
  },
```

**Comment by chenos** [comment]
```js
chainWebpack: (memo, args) => {

    memo.module
      .rule('svg')
      .exclude.add(/pages/).end();  // 给内置的添加 exclude，这里根据自己的情况处理

    memo.module
      .rule('svgr')
      .test(/.svg$/)
      .include.add(/pages/).end() // include 指定需要直接 svgr 的情况
      .use('@svgr/webpack')
        .loader(require.resolve('@svgr/webpack'));
  },
```

**Comment by yckbilly1929** [comment]
> ```js
> chainWebpack: (memo, args) => {
> 
>     memo.module
>       .rule('svg')
>       .exclude.add(/pages/).end();  // 给内置的添加 exclude，这里根据自己的情况处理
> 
>     memo.module
>       .rule('svgr')
>       .test(/.svg$/)
>       .include.add(/pages/).end() // include 指定需要直接 svgr 的情况
>       .use('@svgr/webpack')
>         .loader(require.resolve('@svgr/webpack'));
>   },
> ```
> 
> 大致可以这样：
> 
> ```js
> // assets 的走内置的 svg
> import iconFile, { ReactComponent as Icon } from '@/assets/icon.svg';
> 
> // pages 的可以直接 svgr
> import Icon from '@/pages/icon.svg';
> ```

這個行，然後我發現要用CustomIconComponentProps就要這樣寫
```
import iconFile, { ReactComponent as TestLogo } from '@/assets/svg/test-logo.svg';
<Icon component={() => <TestLogo className='logo' />} />
```

**Comment by chenos** [comment]
@yckbilly1929 

```js
// svgr 的
import Icon from '@ant-design/icons';
import Logo from '@/pages/logo.svg';

// 这样可以
<Logo className={'logo'} width={20} height={20}/>

 // 这样也行
<Icon component={Logo} className={"logo"}/>
```

**Comment by peiwen-pts** [comment]
> ```js
> chainWebpack: (memo, args) => {
> 
>     memo.module
>       .rule('svg')
>       .exclude.add(/pages/).end();  // 给内置的添加 exclude，这里根据自己的情况处理
> 
>     memo.module
>       .rule('svgr')
>       .test(/.svg$/)
>       .include.add(/pages/).end() // include 指定需要直接 svgr 的情况
>       .use('@svgr/webpack')
>         .loader(require.resolve('@svgr/webpack'));
>   },
> ```
> 
> 大致可以这样：
> 
> ```js
> // assets 的走内置的 svg
> import iconFile, { ReactComponent as Icon } from '@/assets/icon.svg';
> 
> // pages 的可以直接 svgr
> import Icon from '@/pages/icon.svg';
> ```

谢谢@yckbilly 这样解决了我的 umi svg loader 配置问题

**Comment by shinvdu** [comment]
[6.2.1](https://www.npmjs.com/package/@svgr/webpack/v/6.2.1)

这个版本报错

换成[5.5.0](https://www.npmjs.com/package/@svgr/webpack/v/5.5.0)
就正常了
