### ISSUE TITLE
修改umijs配置文件后无法自动生效，需要重启 yarn start

### ISSUE THREAD

**Issue by winter-ice** [umijs/umi#4036]
## What happens?

如题，与文档描述不符

## 相关环境信息

- **Umi 版本**：3.0.1
- **Node 版本**：12.5.0
- **操作系统**：win10

**Comment by OneCodeMonkey** [comment]
+1，改了代码并没有发现有自动增量编译，还得 yarn start一次

**Comment by laixstx** [comment]
+1

**Comment by kaoding** [comment]
+1

**Comment by sorrycc** [comment]
比如说改啥配置？

**Comment by kaoding** [comment]
+ layout: {}
![image](https://user-images.githubusercontent.com/18542211/75738190-98ba7980-5d3c-11ea-9d28-20eaf2ad6be6.png)

**Comment by DAOLIDEWONIU** [comment]
+1

**Comment by onism68** [comment]
+1

**Comment by OneCodeMonkey** [comment]
这问题没法解决么？还是说改了代码只能整个的重启

**Comment by xiexingen** [comment]
感觉umi2的时候挺好的，比如增加了路由 那么服务重新启动

**Comment by sorrycc** [comment]
大家都是 windows 吗？

**Comment by kaoding** [comment]
> 大家都是 windows 吗？

1. windows 使用占有量应该是最高的
2. 在windows上开发，很多提示对windows的确不友好

**Comment by xiaohuoni** [comment]
> 大家都是 windows 吗？

看反馈问题的，都是win10

**Comment by kaoding** [comment]
> > 大家都是 windows 吗？
> 
> 看反馈问题的，都是win10

我是 win10

**Comment by laixstx** [comment]
我也是 win10

**Comment by laixstx** [comment]
我也是 win10

**Comment by xiexingen** [comment]
我也是 win10

**Comment by sorrycc** [comment]
感觉和 #4177 有关。

**Comment by winter-ice** [comment]
@sorrycc 好像是的，merge后更新了新版本问题没了
