### ISSUE TITLE
升级后打包问题，包大小增加了110K左右，有什么办法可以优化吗？

### ISSUE THREAD

**Issue by userhjp** [umijs/umi#4038]
umi.css 升级前52k 升级后 82k
umi.js 升级前503k 升级后 587k
包体积增加了20% 这是一个比较高的增长值，或者有什么办法去除掉不需要的一些插件吗
![image](https://user-images.githubusercontent.com/31978565/75677047-86e9bf80-5cc5-11ea-8215-03db9d7d01a1.png)

**Comment by sorrycc** [comment]
为啥 css 都增加了，能对比下看看两边差异是啥吗？尤其是 css 的部分，umi 没有内置 css 的。

**Comment by userhjp** [comment]
> 为啥 css 都增加了，能对比下看看两边差异是啥吗？尤其是 css 的部分，umi 没有内置 css 的。

js代码和css代码没有任何差异，我只是将umi 2.迁移到了3.x并没有新增css或者js代码，目前我已经分包处理了，按需加载

**Comment by sorrycc** [comment]
我是说打包后 css，umi 没有内置任何 css，理论上不管怎样都不会增加 css 。
