### ISSUE TITLE
覆盖antd-mobile样式失败 src/global.less 下全局样式无法覆盖antd-mobile样式

### ISSUE THREAD

**Issue by userhjp** [umijs/umi#4039]
检查元素看到全局样式文件被划掉了，应该是引入样式顺序问题，没能成功覆盖antd-mobile样式

**Comment by MinJieLiu** [comment]
顺序问题，可以通过增加权重解决

**Comment by userhjp** [comment]
> 顺序问题，可以通过增加权重解决

目前是增加的权重 !important 但是感觉有点诡异，全局样式文件还需要!important  然后一堆 !important 看着很不爽 0.0 看后面版本怎么样 现只能这样了

**Comment by MinJieLiu** [comment]
@userhjp 非要加 !important 吗，没有其他办法吗？

比如

```css
:root {
  .ant-layout {}
}
```

再比如

```css
.ant-layout.ant-layout {}
```

**Comment by tmpbin** [comment]
antd@4 主题 `'~antd/dist/antd.dark.less' `同样无法在 global.less 下覆盖原版主题.

**Comment by Pasoul** [comment]
持续关注

**Comment by wjkang** [comment]
antd@4 modal样式同样无法覆盖
```
.ant-modal-title,
.ant-modal-confirm-title {
  font-weight: bold;
}
```

**Comment by bald-newcomer** [comment]
pro-layout插件的header样式，也无法在global中被覆盖..

**Comment by sorrycc** [comment]
加载有先后，通过调整权重的方式覆盖吧。

**Comment by KellenHe** [comment]
框架应该保证先后和权重啊，这个是要umi去处理的。antd的less变量都需要在config里改，这设计有问题。

**Comment by wenrouxiansheng** [comment]
![image](https://user-images.githubusercontent.com/57562534/120415182-b2a69a00-c38d-11eb-9bdc-44b56b03a343.png)
我醉了   真的
