### ISSUE TITLE
路由重定向怎么处理？

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#404]
请问我要怎么写，会在.umi/router.js中生成如下标签
```html
<Redirect exact from="/" to="/list" />
<Redirect exact from="/user" to="/account" />
```

**Comment by xiaohuoni** [comment]
@sorrycc （捂脸）

**Comment by sorrycc** [comment]
配置式的会支持 redirect，约定式我还没想到好办法，估计得通过 umi-plugin-routes 增加了。

**Comment by boxcc** [comment]
暂时是直接写在页面上了 
```
import Redirect from 'umi/redirect';

export default () => {
  return <Redirect to="/form/base-form" />;
}
```

**Comment by smz666** [comment]
import Redirect from 'umi/redirect';

export default () => {
  return <Redirect to="/form/base-form" />;
}
这样使用Redirect会报错
