### ISSUE TITLE
babel 无法识别导出的类型定义

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#4042]
## What happens?

![image](https://user-images.githubusercontent.com/11746742/75738036-2fd30180-5d3c-11ea-8945-500ade611642.png)
```js
api.addUmiExports(() => [
    {
      specifiers: ['Reducer'],
      source: 'redux',
    },
  ]);
```
通过 `api.addUmiExports` 添加导出，比如上面的 `Reducer` 是一个 type ，在编译的时候就会提示无法找到 `"export 'Reducer' was not found in 'redux'`，看是不是能先关掉 warning 日志。

## 尝试修复
通过升级 typescript 版本，使用最新的语法。
```
export type { Reducer  } from 'redux';
```
发现 babel 还没有支持。
![image](https://user-images.githubusercontent.com/11746742/75738271-cef7f900-5d3c-11ea-928a-9af6f62d1680.png)

## 相关环境信息

- **Umi 版本**：3.0.1
- **Node 版本**：10.13.0
- **操作系统**：mac

**Comment by sorrycc** [comment]
https://github.com/babel/babel/pull/11171

**Comment by sorrycc** [comment]
Wait for babel@7.9 .

**Comment by xiaohuoni** [comment]
我的临时的解决方案是将
```tsx
import { IndexModelState } from './index';
import { SettingsModelState } from './settings';
import { ListModelState } from './list';
export { ListModelState, SettingsModelState, IndexModelState };
```
修改为
```tsx
export * from './index';
export * from './settings';
export * from './list';
```

**Comment by pikename** [comment]
![image](https://user-images.githubusercontent.com/33223524/78095518-c234f680-7409-11ea-9e77-d48c02ee1320.png)

**Comment by xiaohuoni** [comment]
https://github.com/babel/babel/releases/tag/v7.11.6
