### ISSUE TITLE
umi block问题

### ISSUE THREAD

**Issue by anye931123** [umijs/umi#4043]
我自己写了个block项目，项目地址为[https://github.com/anye931123/react-visual-editor](https://github.com/anye931123/react-visual-editor)，当我在项目中引入我的block时，执行umi block add  https://github.com/anye931123/react-visual-editor，我的地址就会变为 https://gitee.com/anye931123/react-visual-editor

**Comment by fucaobao** [comment]
我也遇到了这问题，请问有解决么？

**Comment by sheldonwr** [comment]
Same problem.
