### ISSUE TITLE
升级到 umi3 之后，配置 @umijs/plugin-qiankun 插件后，启动报错 Path must be a string

### ISSUE THREAD

**Issue by laixstx** [umijs/umi#4046]
## What happens?

升级到 umi3 ，配置 @umijs/plugin-qiankun 插件后，启动报错 Path must be a string

![image](https://user-images.githubusercontent.com/10735940/75750700-b8af6480-5d5f-11ea-9575-8a4893a39302.png)

主应用的 umirc：
![image](https://user-images.githubusercontent.com/10735940/75834078-f8289000-5df5-11ea-9348-d540d6a5ca5e.png)

子应用的 umirc：
![image](https://user-images.githubusercontent.com/10735940/75834177-3a51d180-5df6-11ea-90ca-6ee82f3ed5e2.png)

## Context

- **Umi Version**: 3.0.1
- **Node Version**: 12.14.1
- **Platform**: windows10

**Comment by qq382724935** [comment]
1.主应用配置我也遇到了此问题
2.子应用项目配置plugins: ['@umijs/plugin-qiankun']启动项目报错：api.register() failed, hook.fn must supplied and should be function, but got qiankun.
![image](https://user-images.githubusercontent.com/24310904/75773911-c974d000-5d89-11ea-94e8-ae4ed25a5b03.png)

**Comment by sorrycc** [comment]
插件的配置方式变更了，官网搜 Plugins。

**Comment by laixstx** [comment]
按umi官网最新文档配置之后，解决问题；谢谢~
https://umijs.org/zh-CN/plugins/plugin-qiankun#%E4%B8%BB%E5%BA%94%E7%94%A8

**Comment by bestRenekton** [comment]
# 主应用配置：
![image](https://user-images.githubusercontent.com/15810263/76047159-f2b97a00-5f9c-11ea-886a-fc077340af8c.png)

# app1配置：
![image](https://user-images.githubusercontent.com/15810263/76047174-fc42e200-5f9c-11ea-8bb4-76ea67971e5e.png)


## 报错：
主应用启动时候报错  ` Invalid config key: qiankun`

**Comment by cassiewang01** [comment]
> 1.主应用配置我也遇到了此问题
> 2.子应用项目配置plugins: ['@umijs/plugin-qiankun']启动项目报错：api.register() failed, hook.fn must supplied and should be function, but got qiankun.
> ![image](https://user-images.githubusercontent.com/24310904/75773911-c974d000-5d89-11ea-94e8-ae4ed25a5b03.png)

你好，你的问题解决了么？我自己写的插件也是遇到api.register() failed, hook.fn must supplied and should be function,类似问题，现在升级3.0后必须要api.register么？有demo么？谢谢

**Comment by ywy94ywy** [comment]
@cassiewang01，@qq382724935 ，你们的问题解决了吗，我也遇到了
