### ISSUE TITLE
[umi@v3] less 使用@import引入第三方库的less文件存在相对路径的资源时，编译报错

### ISSUE THREAD

**Issue by mizi-lin** [umijs/umi#4047]
## What happens?
less 使用@import引入第三方库的less文件
当第三方库的less文件有相对路径的资源时，编译不通过

![image](https://user-images.githubusercontent.com/2802841/75759887-40519f00-5d71-11ea-8f1d-ecbbb1c98a15.png)

git clpne git@github.com:mizi-lin/umi-issues.git
git checkout relative-path
yarn start

--
详见：src/pages/index.less

```less
@import "./relative.less";
@import "~antd/lib/spin/style/index.less";
@import "~simple-line-icons/less/simple-line-icons.less";
```
引入
@import "./relative.less";
@import "~antd/lib/spin/style/index.less";
均不报错，但一旦引入 @import "~simple-line-icons/less/simple-line-icons.less";
就报错，

simple-line-icons.less 存在相对路径资源

![image](https://user-images.githubusercontent.com/2802841/75760494-557afd80-5d72-11ea-9e8b-0cffe17e170f.png)

并验证，只要删除 调用 node_module 中的相对资源地址的配置，项目正常启动

**Comment by chenos** [comment]
问题在这里

https://github.com/umijs/umi/blob/9746d03addde97e5cfe0653c098b7777e9c2b750/packages/bundler-webpack/src/getConfig/getConfig.ts#L199

暂时可以这么解决：

```js
chainWebpack: (memo, args) => {
    memo.module
      .rule('images')
      .test(/\.(png|jpe?g|gif|webp|eot|woff|woff2|ttf)(\?.*)?$/);
},
```

**Comment by mizi-lin** [comment]
漂亮 3q

**Comment by sorrycc** [comment]
👍，我加进去。

**Comment by mizi-lin** [comment]
实测通过~ 3q

**Comment by SanPy** [comment]
v2的版本怎么配置能够解决这个问题
