### ISSUE TITLE
[umi3] 不支持识别单文件model（ model.js ）了吗？

### ISSUE THREAD

**Issue by sunyum** [umijs/umi#4049]
## What happens?

v3 不支持直接识别 model.js 了吗，只能放在models目录中？

![image](https://user-images.githubusercontent.com/20025971/75769277-de993100-5d80-11ea-9b80-e70dd1040e05.png)

v2
![image](https://user-images.githubusercontent.com/20025971/75775681-71d86380-5d8d-11ea-8036-d0539aaf916b.png)

## 相关环境信息

- **Umi 版本**：v3.0.2
- **Node 版本**：v12.16.1
- **操作系统**：win10

**Comment by ycjcl868** [comment]
统一到 `models` 吧，不支持子目录 `models`

**Comment by sorrycc** [comment]
要加的，明天。

**Comment by superlbr** [comment]
@sorrycc today？

**Comment by sorrycc** [comment]
已经加了，试试。

**Comment by sorrycc** [comment]
改进点，文档明早更新。

	* import 更多借口 from umi
	* dva model 识别准确率问题
	* 支持通过配置 skipModelValidate 禁用 dva model 识别，因为 JS 的动态性，有些边界条件**无法**检测
	* 支持通过配置 extraModels 引入额外的 model
	* 新增命令 `umi dva list model`，用于自查
	* 支持通过 import \{ getDvaApp } from umi，来拿到之前的 `g_app`
	* 修复 connect 的 ts 定义问题
	* 支持找 model.ts 文件作为 dva model

**Comment by sunyum** [comment]
> 改进点，文档明早更新。
> 
> ```
> * import 更多借口 from umi
> * dva model 识别准确率问题
> * 支持通过配置 skipModelValidate 禁用 dva model 识别，因为 JS 的动态性，有些边界条件**无法**检测
> * 支持通过配置 extraModels 引入额外的 model
> * 新增命令 `umi dva list model`，用于自查
> * 支持通过 import \{ getDvaApp } from umi，来拿到之前的 `g_app`
> * 修复 connect 的 ts 定义问题
> * 支持找 model.ts 文件作为 dva model
> ```

还是无法识别model.js额
路径如下
+ src
  + pages
    + login
       - index.js
       - model.js   ---此model无法识别

**Comment by sorrycc** [comment]
model.js 不可以吗？我昨天验过是可以的。

**Comment by sunyum** [comment]
> model.js 不可以吗？我昨天验过是可以的。

可以了，是umi插件依赖版本的问题，之前参考升级文档 preset-react的依赖引入的是 "@umijs/preset-react": "^1"
用 npm-check-updates 更新依赖，检测不出来 ^1 的新版本，最新版本是 ^1.3.6
修改成 "@umijs/preset-react": "^1.3.6" 就行了

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/76041533-50de6100-5f8d-11ea-914c-850d7c055cd4.png)
能匹配到，可能是本地 lock 文件到原因。
