### ISSUE TITLE
404页面逻辑失效

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#405]
今天发现，我好想重来没触发过404页面，好奇编译了一下
[umi-examples/routes/](https://github.com/umijs/umi-examples/tree/master/routes)
发现build之后，并没有正确触发404页面。

**Comment by xiaohuoni** [comment]
![27224753](https://user-images.githubusercontent.com/11746742/39368753-07705460-4a6d-11e8-8768-655c424ec300.png)

**Comment by xiaohuoni** [comment]
我很好奇，正确的404页面，生成的router.js是什么样子的

**Comment by xiaoxiangmoe** [comment]
@xiaohuoni 我也遇到了，但是开启 hashHistory 的支持就好了，应该是需要服务器端的支持。

**Comment by sorrycc** [comment]
这个 404 是加在路由里，所以 build 之后还是需要自行配置 html 响应的。

**Comment by xiaohuoni** [comment]
例子里面哪个有实现？

**Comment by xiaohuoni** [comment]
最新的umi 1.3.0 支持

**Comment by chj-damon** [comment]
@sorrycc 自行配置html响应，是什么意思？

**Comment by kitebear** [comment]
就是nginx去做配置
