### ISSUE TITLE
请问umi是否支持将html和其他静态资源分别自定义目录？

### ISSUE THREAD

**Issue by YellowPure** [umijs/umi#4059]
## What happens?

我无法将html和静态资源组合成我想要的目录结构：
```
dist/
       index.html
       static/
                  xxx.css
                  xxx.js
```

## 最小可复现仓库

[https://github.com/YellowPure/ant-pro-bug-report](url)

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：2.13.3
- **Node 版本**：v10.15.3
- **操作系统**：macOS

**Comment by ohhoney1** [comment]
+1

**Comment by ohhoney1** [comment]
目前通过在package.json 里的scripts 里 手动写几个shell语句完成

**Comment by felix9ia** [comment]
> 目前通过在package.json 里的scripts 里 手动写几个shell语句完成

这样 html 里面的链接位置也是需要变的吧。不能通过 shell 解决吧？

**Comment by ohhoney1** [comment]
> > 目前通过在package.json 里的scripts 里 手动写几个shell语句完成
> 
> 这样 html 里面的链接位置也是需要变的吧。不能通过 shell 解决吧？
umi3 配置下：`publicPath: '/static/',`  umi2的话应该也有类似的配置
