### ISSUE TITLE
run command failed, command ui does not exists.

### ISSUE THREAD

**Issue by abcnny** [umijs/umi#4060]
## What happens?

when i run "umi ui"，The error is as follows：

run command failed, command ui does not exists.
AssertionError [ERR_ASSERTION]: run command failed, command ui does not exists.
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\umi\node_modules\@umijs\core\lib\Service\Service.js:625:29
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\Administrator\AppData\Roaming\npm\node_modules\umi\node_modules\@umijs\core\lib\Service\Service.js:100:103)
    at _next (C:\Users\Administrator\AppData\Roaming\npm\node_modules\umi\node_modules\@umijs\core\lib\Service\Service.js:102:194)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

- **Umi Version**:
umi@3.0.2
- **Node Version**:
v12.16.1
- **Platform**:
windows10

**Comment by hellorayza** [comment]
not update yet now[introduce](https://umijs.org/zh/guide/umi-ui.html#%E2%9C%A8-%E7%89%B9%E6%80%A7)

refer to[umi-ui#-快速开始](https://github.com/umijs/umi-ui#-%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B)，

```sh
PS E:\Test\umi-test> umi dev
�🚀 Starting Umi UI using umi@3.0.3.
�🌈 Umi UI mini Ready on port 30

Starting the development server...

× Webpack
  Compiled with some errors in 2.21s

 ERROR  Failed to compile with 1 errors                                                                 10:51:45
 error  in ./src/.umi/umi.ts

Syntax Error: SyntaxError: E:\Test\umi-test\src\.umi\umi.ts: Bad character escape sequence (13:40)

  11 | (() => {
  12 |   // Runtime block add component

> 13 |   window.GUmiUIFlag = require('E:\Test\umi-test\node_modules\@umijs\plugin-ui-blocks\lib\sdk\flagBabelPlugin\GUmiUIFlag.js').default;
>      |                                         ^
>   14 | 
>   15 |   // Enable/Disable block add edit mode
>   16 |   window.addEventListener('message', (event) => {


 @ multi ./node_modules/@umijs/bundler-webpack/lib/webpackHotDevClient/webpackHotDevClient.js ./src/.umi/umi.ts 
```



And refer to [this](https://github.com/umijs/umi/blob/docs-umi-ui/docs/docs/umi-ui.zh-CN.md)

```
'UMI_UI' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
```

**Comment by hezhongfeng** [comment]
umi@3.2.2 same problem

**Comment by handycode** [comment]
umi@3.2.19 same problem

**Comment by sorrycc** [comment]
umi ui is not recommended. If you want to use this, try https://umijs.org/docs/use-umi-ui#-%E4%BD%BF%E7%94%A8 .
