### ISSUE TITLE
关于ant design pro 升级 umi3，约定式路由菜单配置的优化建议

### ISSUE THREAD

**Issue by sorryljt** [umijs/umi#4065]
如题，我umi3发布后，我尝试更新，并打算试一试约定式路由，改成配置时路由后，页面变为无导航模式，可是配置菜单却让我很头疼，我按照文档提示(@umijs/plugin-layout)打算找出点方法，于是找到了这样一段代码
```
export const routes=  [
  {
    path: '/welcome',
    component: 'IndexPage',
    menu: {
      name: '欢迎', // 兼容此写法
      icon: 'testicon',
    },
    layout:{
      hideNav: true,
    },
    access: 'canRead',
  }
]
```
我尝试按照这样去在`config/router.js`中配置菜单，却什么也不生效。是文档不够清晰，还是这里有问题呢？
按照文档提示，config中已经配置过layout相关option。
请指条明路。

**Comment by sorrycc** [comment]
提供下复现步骤，期望结果，实际结果？

**Comment by sorryljt** [comment]
因为没有在ant design pro中用过约定式路由，那天尝试换了一下，具体操作步骤如下
1. 删掉config/config.js中删掉router配置
2. 在`defineConfig`中加入`layout`配置项
此时页面为pro默认主题，但无菜单显示
3. 接着看文档至plugin-layout-->扩展的路由配置，新建`config/router.js`文件夹，加入`router`
相关配置，页面还是没有出现菜单。然后找文档就找不见相关东西了。
###### 期望结果
看到umi3更新日志中有提到约定式路由，想尝尝新鲜，可不能很顺利的将菜单、路由、不同布局结合起来。期望有一详细文档能协助在配置式路由和约定式路由之间无缝转换

**Comment by doudou003** [comment]
21天也是醉了。

我理解的意思是使用`@umijs/plugin-layout`后，在`.umirc.ts`或`config/config.js`中添加
```
export default defineConfig({
    layout: {},
    ...
});
```
**然后左侧菜单怎么出现？**
1. 看文档是自动根据`src/pages/`目录生成左侧菜单，请问可以吗？
2. 手动添加菜单的方式如何配置？


**期望结果**
+ 使用`@umijs/plugin-layout`后，可以根据`src/pages/`目录生成左侧菜单


**实际结果**
+ 左侧菜单无内容


---

**以下碎碎念**（吃了猪肉又觉得肉少）
+ 文档是使用者了解产品的方式，一直在迭代那可以把细节描述清楚可以么？
+ 嫁接了一层又一层，把链条上下描述清楚可以体现一个团队的专业性和责任心


**文档**
清晰的文档会增加开源团队的**时间成本**！ 但：
> （使用者 x 阅读文档时间） > （开源团队 x 完善文档时间）

+ 产品功能可以帮助节省时间
+ 产品文档同样可以节省时间

文档描述不到的功能，是不是等于没有，至少大大打折！
（至少确保大版本是可以好好撸的）

|
|
|
 
最后肉是香的，希望在发布4.0时候，3.0文档是完整的，开源不易，加油~

**Comment by singagain** [comment]
俺也一样 😶

**Comment by doudou003** [comment]
第一次觉得，文档差的开源不用也罢，也让我意识到文档的重要性（代码内和代码外）。

### 负面情绪：
长时间回复都没有，可能是喝醉了

通过这次使用体验，学习到：
1. 测试驱动开发是困难模式，有大量明显bug一定是测试偷懒了；
2. 文档是公开之前二校的一道门，守不住这里都是流氓。

以后评一个开源是否优秀要多几个指标了
+ 开源的初心
+ 社区的认可
+ 完善的文档
+ 跟进的责任


### 正面情绪：
可以自己fix啊
没有反馈，没有正面情绪，创建的 Demo 先放一放有时间再说

**Comment by GS-LiuYang** [comment]
感觉 umi3 就是个半成品  造成这个认知 可能 就是 文档跑不通的原因吧。

**Comment by LarryZhao0616** [comment]
这个umi3文档，我已经醉了。
就拿config router这一件事来说，我能找到的官方文档分两部分。
https://umijs.org/docs/routing
https://umijs.org/config#routes
但是写的极其宽泛，杂乱无比，毫无条理。没一个地方解释name title之间的关系（文档里根本就没有name）。后者还有一个跳往“路由配置章节”的链接也挂了。。。。。。

**Comment by aofeng1227** [comment]
一直以为是自己白痴不会，没想到你们也一样啊。

**Comment by aofeng1227** [comment]
> 如题，我umi3发布后，我尝试更新，并打算试一试约定式路由，改成配置时路由后，页面变为无导航模式，可是配置菜单却让我很头疼，我按照文档提示(@umijs/plugin-layout)打算找出点方法，于是找到了这样一段代码
> 
> ```
> export const routes=  [
>   {
>     path: '/welcome',
>     component: 'IndexPage',
>     menu: {
>       name: '欢迎', // 兼容此写法
>       icon: 'testicon',
>     },
>     layout:{
>       hideNav: true,
>     },
>     access: 'canRead',
>   }
> ]
> ```
> 
> 我尝试按照这样去在`config/router.js`中配置菜单，却什么也不生效。是文档不够清晰，还是这里有问题呢？
> 按照文档提示，config中已经配置过layout相关option。
> 请指条明路。

敢问你们 的菜单出来了吗

**Comment by zhanglingyugit** [comment]
有解决了的吗

**Comment by zss1004504439** [comment]
怎么解决

**Comment by monttailee** [comment]
> 21天也是醉了。
> 
> 我理解的意思是使用`@umijs/plugin-layout`后，在`.umirc.ts`或`config/config.js`中添加
> 
> ```
> export default defineConfig({
>     layout: {},
>     ...
> });
> ```
> 
> **然后左侧菜单怎么出现？**
> 
> 1. 看文档是自动根据`src/pages/`目录生成左侧菜单，请问可以吗？
> 2. 手动添加菜单的方式如何配置？
> 
> **期望结果**
> 
> * 使用`@umijs/plugin-layout`后，可以根据`src/pages/`目录生成左侧菜单
> 
> **实际结果**
> 
> * 左侧菜单无内容
> 
> **以下碎碎念**（吃了猪肉又觉得肉少）
> 
> * 文档是使用者了解产品的方式，一直在迭代那可以把细节描述清楚可以么？
> * 嫁接了一层又一层，把链条上下描述清楚可以体现一个团队的专业性和责任心
> 
> **文档**
> 清晰的文档会增加开源团队的**时间成本**！ 但：
> 
> > （使用者 x 阅读文档时间） > （开源团队 x 完善文档时间）
> 
> * 产品功能可以帮助节省时间
> * 产品文档同样可以节省时间
> 
> 文档描述不到的功能，是不是等于没有，至少大大打折！
> （至少确保大版本是可以好好撸的）
> 
> |
> |
> |
> 
> 最后肉是香的，希望在发布4.0时候，3.0文档是完整的，开源不易，加油~ @sorrycc

export default defineConfig({ 
   layout: {
    name: ' ',
    theme: 'pro',
    locale: true,
  },
  routes: [
    {
      path: '/login',
      layout: false,
      component: '@/pages/login',
    },
   //......
  ],
})

**Comment by monttailee** [comment]
umirc.ts

export default defineConfig({
layout: {
name: ' ',
theme: 'pro',
locale: true,
},
routes: [
{
path: '/login',
layout: false,
component: '@/pages/login',
},
//......
],
})

**Comment by Cufoon** [comment]
别提了，坑死了，umi 和 pro-layout 的文档一团糟 真的无语 配置都不知道咋配置 阿里的写文档的水平这么次？？？

**Comment by sofichael** [comment]
路由类似这样配置就可以显示了， config.ts配置layout,app.ts配置layout
------------------------------------
  routes: [
    {
      path: '/user',
      layout: false,
      routes: [
        {
          name: 'login',
          path: '/user/login',
          component: './User/login',
        },
      ],
    },
    {
      path: '/welcome',
      name: 'welcome',
      icon: 'smile',
      component: './Welcome',
    },
    {
      path: '/admin',
      name: 'admin',
      icon: 'TeamOutlined',
      access: 'canAdmin',
      // component: './Admin',
      routes: [
        {
          path: '/admin/user',
          name: 'user',
          component: './UserList',
        },
        {
          path: '/admin/user/detail/:id',
          name: 'userDetail',
          hideInMenu: true,
          component: './UserDetail',
        },
        {
          path: '/admin/profile',
          name: 'profile',
          component: './ProfileList',
        },
        {
          path: '/admin/profile/add',
          name: 'addProfile',
          hideInMenu: true,
          component: './AddProfile',
        },
        {
          path: '/admin/profile/detail/:id',
          name: 'profileDetail',
          hideInMenu: true,
          component: './ProfileDetail',
        },
      ],
    },
]

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.

**Comment by Itroads** [comment]
问题仍然存在。左侧菜单无内容。

**Comment by Itroads** [comment]
umi3

**Comment by Itroads** [comment]
文档确实是有些简陋。如果把撰写文档也能纳入KPI，应该会得到一个有效的改善。

**Comment by lsaint** [comment]
2021年4月底， 搜到这个才发现我并不孤独。  

**到底怎样在使用BasicLayout的时候自动在侧边栏展示约定式路由？**

**Comment by Echo365** [comment]
> 2021年4月底， 搜到这个才发现我并不孤独。
> 
> **到底怎样在使用BasicLayout的时候自动在侧边栏展示约定式路由菜单？**
> 
> 我是umi和antd的新用户，只使用了几周。

使用ant design pro 试试，已经做好了框架。

**Comment by lydsgit** [comment]
楼上解决了吗？官方文档说如果没有 routes 配置，Umi 会进入约定式路由模式，删掉配置也完全没用啊

**Comment by lxl1024** [comment]
约定式路由不会展示在左侧菜单（plugin-layout），看样子是因为生成的路由信息中没有name属性导致
![image](https://user-images.githubusercontent.com/26319380/121189403-a8f4c900-c89c-11eb-9341-1b0e61db07fc.png)

但是按照文档上扩展属性，name属性加不上去，会报错
![image](https://user-images.githubusercontent.com/26319380/121181568-befe8b80-c894-11eb-9ca0-417377c37634.png)
![image](https://user-images.githubusercontent.com/26319380/121182386-9fb42e00-c895-11eb-921b-57ecd60fdcf9.png)

**Comment by nolure** [comment]
@lxl1024 确实是name的问题，这个奇葩问题真是无语了，

只有改成配置式路由，并手动指定全局layout

**Comment by zitudu** [comment]
> @lxl1024 确实是name的问题，这个奇葩问题真是无语了，
> 
> 只有改成配置式路由，并手动指定全局layout

运行时配置 `patchRoutes` 为需要的 route 加上 name 属性可显示菜单。

**Comment by mode365Dong** [comment]
文档不清晰，很多地方只有一句话描述。再查找就没有下文了。
冗余产品太多了，umijs，umi ui，antd pro 的umi。
request有好多个版本，我也是使用了很久才明白。
期待1月8日的umi4   加油！！！

**Comment by gggso** [comment]
> 

鸽了啊

**Comment by xiaohuoni** [comment]
https://github.com/alitajs/umi-antd-pro

**Comment by ycq3** [comment]
```tsx
function MusicPage() {
    return (
        <div>
            <h1>Page MusicPage</h1>
        </div>
    );
}

MusicPage.menu = {
    name: '音乐', // 兼容此写法
    icon: 'icon-testicon',
}


export default MusicPage
```

<img width="427" alt="image" src="https://user-images.githubusercontent.com/23733814/186089553-0704272d-f3e1-45a6-8b59-bbd0d7cdbcb2.png">
