### ISSUE TITLE
解构赋值ts报错 类型“DefaultRootState”上不存在属性“app”  当在使用connect方法时，不解构则正常

### ISSUE THREAD

**Issue by MatrixAge** [umijs/umi#4066]
## What happens?

![image](https://user-images.githubusercontent.com/25472851/75877429-ad893100-5e52-11ea-95cd-2e309a25c453.png)

当在使用connect方法时，解构赋值ts报错 类型“DefaultRootState”上不存在属性“app”  。

![image](https://user-images.githubusercontent.com/25472851/75877473-cdb8f000-5e52-11ea-9497-9a2d8d38b35e.png)

按照umi3官网直接从umi引入connect，ts也报错。（是不是types未更新导致）

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create umi` then upload to your GitHub

## How To Reproduce

yarn create @umijs/umi-app

然后在src/moels下新建一个app.ts并写入model，然后再页面中引入（上图所示）。

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi 3.0.0-beta.38**:
- **Node 12.13**:
- **Platform osx catalina10.15.3**:

**Comment by MatrixAge** [comment]
connect通过重新安装，已可以引入

**Comment by MatrixAge** [comment]
![image](https://user-images.githubusercontent.com/25472851/75879507-7ae13780-5e56-11ea-8fa5-ee110878d519.png)
这么写也OK，但并不想这么写（不然为什么上ts）

**Comment by sherry007** [comment]
我也遇到了同类型问题，就是报“DefaultRootState”上不存在属性xx的问题，想问最后是怎么解决的呀

**Comment by xiaohuoni** [comment]
```tsx
// src/models/index.ts
export interface IndexModelState {
  name: string;
}
...
```
```tsx
import { IndexModelState, ConnectProps, connect } from 'umi';

interface PageProps extends ConnectProps {
  index: IndexModelState;
}

const IndexPage: FC<PageProps> = ({ index, dispatch }) => {
  const { name = '' } = index;
  return (
    <div className={styles.center}>
      {name}
    </div>
  );
};
export default connect(({ index }: { index: IndexModelState }) => ({ index }))(IndexPage);
```
