### ISSUE TITLE
umi2.10升级umi3后，部分es6没有转成es5，导致Android7系统无法打开app内嵌入的后

### ISSUE THREAD

**Issue by crownclownwl** [umijs/umi#4069]
## 最小可复现仓库
https://github.com/crownclownwl/umi2-level-up-to-umi3-demo

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
$ yarn build
Android 7 无法打开内嵌的h5 页面

报错如下：Object.entries is not a function
#

## 相关环境信息

- **Umi 版本**：
3.0.3
- **Node 版本**：
12.16.0
- **操作系统**：
win10 1909 64位 家庭版

**Comment by sorrycc** [comment]
https://unpkg.com/browse/core-js-compat@3.6.4/data.json 这里搜 object.entries，targets 配到这里有到 key 的数值以下。

**Comment by crownclownwl** [comment]
这里没有Android 也就是说我需要找到我的 app 内嵌的浏览器内核版本 是这意思把？

**Comment by crownclownwl** [comment]
还是不行，我改成如下配置了
```js
    targets: {
        chrome: 50,
        edge: 13,
        firefox: 45,
        ie: 9,
        ios: 11,
        safari: 10,
  },
```

还是报那个错误
![image](https://user-images.githubusercontent.com/11539526/75957664-71f37300-5ef5-11ea-89ae-06623715498d.png)
![image](https://user-images.githubusercontent.com/11539526/75957679-7cae0800-5ef5-11ea-87f3-5322a1aea8ef.png)

**Comment by crownclownwl** [comment]
今天还发现一个bug，就是 我这个项目里升级umi3 后无法自动跳转到指定首页路由了 /src/pages/main/index.tsx了

**Comment by crownclownwl** [comment]
我今天用 yarn create umi ，选择 app 这个类型的，创建的项目 也是不行，就是Android7.1 无法访问，targets 貌似 没起到作用啊，我都把chrome 版本降到 40 了，也不行

**Comment by wuxiaoshi888** [comment]
我今天也遇到这个问题

**Comment by crownclownwl** [comment]
升级到 3.0.11 就好了，Android 7 可以用了，

**Comment by crownclownwl** [comment]
但是 控制台报错如下
![image](https://user-images.githubusercontent.com/11539526/77051937-0d610980-6a07-11ea-8d55-c22146d94819.png)

**Comment by crownclownwl** [comment]
umi.js:45214Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.function.console.(anonymous function) @ umi.js:45214
umi.js:60839dev

**Comment by missingRead** [comment]
> umi.js:45214Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.function.console.(anonymous function) @ umi.js:45214
> umi.js:60839dev

这个问题解决了嘛？如何解决的

**Comment by crownclownwl** [comment]
> > umi.js:45214Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.function.console.(anonymous function) @ umi.js:45214
> > umi.js:60839dev
> 
> 这个问题解决了嘛？如何解决的

应该解决了把，我升级到最新的umijs 版本后 就没有这个错误了
