### ISSUE TITLE
UMI 在amd模式下不能在IE11中正常运行

### ISSUE THREAD

**Issue by Aiooioo** [umijs/umi#4070]
## What happens?

UMI APP在设置为AMD模式下时，config中开启了targets ie 11，仍然不能在IE11下正常显示。
不报错，显示为白屏。
Chrome中可以正常显示。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create umi` then upload to your GitHub

https://github.com/Aiooioo/umi3-amd-ie11-issue

## How To Reproduce

**Steps to reproduce the behavior:** 
1. git clone 
2. npm install
3. npm start

**Expected behavior** 
1. 希望在IE11 中可以正常运行UMI

**PS：** 希望UMI可以暴露出HTML Inject的接口，因为在AMD模式下，bundle文件需要用require函数加载。

## Context

- **Umi Version**: 3.0.2
- **Node Version**: 12
- **Platform**: Windows 10 x64

**Comment by rilaohn** [comment]
同问

**Comment by xiaohuoni** [comment]
相同的问题 https://github.com/umijs/umi/issues/5428
