### ISSUE TITLE
如何覆盖UMI的babel plugin的config

### ISSUE THREAD

**Issue by ruruiye** [umijs/umi#4072]
## What happens?
我们需要使用typescript的namespace，基于`@babel/plugin-transform-typescript`， 需要加一个`allowNamespaces`  的配置项，通过
```
  extraBabelPlugins: [["@babel/plugin-transform-typescript", {
    "allowNamespaces": true
  }]]
```

编译时会报错，
```
error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]
```
应该是plugin已经在umi里面有了。只需要加一个配置即可。请问需要怎么做。

## 相关环境信息

- **Umi 版本**：
3.0.2
- **Node 版本**：
10.x
- **操作系统**：
ubuntu

**Comment by sorrycc** [comment]
allowNamespaces 内置会不会有啥副作用？

**Comment by ruruiye** [comment]
应该没有啥副作用吧，这是下一个版本的功能，现在默认是false，将来会是true.

https://babeljs.io/docs/en/babel-plugin-transform-typescript#impartial-namespace-support

**Comment by sorrycc** [comment]
那内置吧，下个版本我加上。
