### ISSUE TITLE
export 'useIntl' was not found in 'umi'

### ISSUE THREAD

**Issue by hellorayza** [umijs/umi#4075]
## What happens?

 `import { useIntl } from 'umi';` 

**terminal** : **"export 'useIntl' was not found in 'umi'**

umi dev`执行后src/.umi/core/umiExports.ts不出现intl.

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

已参照[import from umi 没有定义怎么办](https://umijs.org/zh-CN/docs/faq#import%20from%20umi%20%E6%B2%A1%E6%9C%89%E5%AE%9A%E4%B9%89%E6%80%8E%E4%B9%88%E5%8A%9E)

配置`tsconfig.json`的`paths`并执行umi dev等命令。

## 复现步骤，错误日志以及相关配置

已删除yarnlock,重装无效

## 相关环境信息

- **Umi 版本**：3.0.3
- **Node 版本**：12.14.1
- **操作系统**：windows10

**Comment by dkvirus** [comment]
我也遇到了类似的问题， `import { history } from 'umi'` 编辑器报错 history 不存在。

**Comment by sorrycc** [comment]
@dkvirus 官网 FAQ 里有。
@ycjcl868 useIntl 的问题确认下。

**Comment by ycjcl868** [comment]
```bash
$ npm i @umijs/plugin-locale -D
```

然后配置 `locale` 开启，具体配置见[这里](https://umijs.org/zh-CN/plugins/plugin-locale)。

**Comment by NexxLuo** [comment]
plugin @umijs/plugin-locale is already registered by E:/xxx/node_modules/@umijs/plugin-locale/lib/index.js, plugin from E:/xxx/node_modules/@umijs/plugin-locale/lib/index.js register failed.

这是什么情况

**Comment by NexxLuo** [comment]
> plugin @umijs/plugin-locale is already registered by E:/xxx/node_modules/@umijs/plugin-locale/lib/index.js, plugin from E:/xxx/node_modules/@umijs/plugin-locale/lib/index.js register failed.
> 
> 这是什么情况
看起来是umi已内置，无需单独安装，删除package.json中的@umijs/plugin-locale依赖声明即可

**Comment by zhangyuheng** [comment]
https://github.com/ant-design/ant-design-pro/issues/7321

**Comment by simplast** [comment]
遇到同样的问题，按照官网新建项目，dev启动就有一堆warning

**Comment by wangfupeng1988** [comment]
- `config/config.ts` 中增加 `locale: {}`
- 新建文件 `src/locales/zh-CN.ts` ，文件中写 `export default {}`
- 重启服务

当前版本 `"umi": "^3.2.22"`

**Comment by Verena99** [comment]
我也遇到了类似的问题，"export 'connect' was not found in 'umi'编译器报错connect不存在

**Comment by 772920023** [comment]
我遇到的类似的问题，"export 'SelectLang' was not found in 'umi'，无法导出SelectLang

**Comment by aaronxdd** [comment]
> ```shell
> npm i @umijs/plugin-locale -D
> ```

不用国际化不可以嘛

**Comment by ahuigo** [comment]
> * `config/config.ts` 中增加 `locale: {}`
> * 新建文件 `src/locales/zh-CN.ts` ，文件中写 `export default {}`
> * 重启服务
> 
> 当前版本 `"umi": "^3.2.22"`

还要再加上：
```
export default defineConfig({
  layout: {},
  locale: {
      default: 'zh-CN',
      antd: false,
      title: false,
      baseNavigator: true,
      baseSeparator: '-',
  },
...

```

**Comment by peiwen-pts** [comment]
> > * `config/config.ts` 中增加 `locale: {}`
> > * 新建文件 `src/locales/zh-CN.ts` ，文件中写 `export default {}`
> > * 重启服务
> > 
> > 当前版本 `"umi": "^3.2.22"`
> 
> 还要再加上：
> 
> ```
> export default defineConfig({
>   layout: {},
>   locale: {
>       default: 'zh-CN',
>       antd: false,
>       title: false,
>       baseNavigator: true,
>       baseSeparator: '-',
>   },
> ...
> ```

我没有新建 `zh-CN.ts` 文件，只像上面一样修改了配置就解决了导入错误问题
