### ISSUE TITLE
umi3 Mock 功能请求是成功的，返回的是一段空白 Html 代码

### ISSUE THREAD

**Issue by dkvirus** [umijs/umi#4077]
## What happens?

- 使用 Umi 脚手架创建的空白项目；
- 在 src/mock/user.ts 里写 mock 数据（复制官网 mock 示例代码）；
- 启动工程，访问 Mock 地址，页面一片空白；
- 控制台中看到网络请求是成功的，但响应不是 json 数据，而是一段 html 代码。

```
Request URL: http://localhost:8000/api/users
Request Method: GET
Status Code: 200 OK
Remote Address: 127.0.0.1:8000
Referrer Policy: no-referrer-when-downgrade
```

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
    />
    <link rel="stylesheet" href="/umi.css" />
    <script>
      window.routerBase = "/";
    </script>
    <script>
      //! umi version: 3.0.3
    </script>
  </head>
  <body>
    <div id="root"></div>

    <script src="/umi.js"></script>
  </body>
</html>
```

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create umi` then upload to your GitHub

[可复现工程](https://github.com/dkvirus/umi4-mock)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

- 拉工程；
- `yarn` 装依赖；
- `yarn start` 启动项目；
- 打开浏览器访问 `localhost:8000/api/users`。

## Context

- **Umi Version**: 3.0.3
- **Node Version**: 12.9.1
- **Platform**: MacOS

**Comment by happyIris01** [comment]
umi dev的时候，不触发404。build之后会正常，抛出404错误。
查看umi2.0文档：
注意：开发模式下，umi 会添加一个默认的 404 页面来辅助开发，但你仍然可通过精确地访问 /404 来验证 404 页面。

**Comment by dkvirus** [comment]
@happyIris01  这跟错误页面无关啊。

经过大量测试，我发现一个规律:

- 只有在根目录下的 mock 目录下写 mock 数据才有效 `my_project/mock/user.ts`；
- umi3 官方文档将 mock 数据写在 `my_project/src/mock/user.ts` 实测无效；
- umi2 支持的将 mock 数据写在页面同目录下 `my_project/src/pages/user/_mock.ts` 也实测无效。

```
|-- my_project
    |-- mock
        |-- user.ts          <= 只有根目录下 mock 目录下的数据也有效
    |-- src
        |-- mock
            |-- user.ts     <= umi3官方文档的 mock 数据写在 src 目录下，实测无效
        |-- pages
            |-- user
                |-- index.tsx
                |-- _mock.ts  <= umi2 支持将mock数据写在页面下的 _mock.ts，实测也无效。
```

@sorrycc  以前 mock 解析规则能不能保留，要不要改很多代码。

**Comment by dkvirus** [comment]
@sorrycc  为啥啥也没说就把我 issue 关了？无语。。。

**Comment by helong123445** [comment]
问下大佬怎么解决的，我更换了目录还是不行

**Comment by legendsf** [comment]
@dkvirus  太感谢了，就是换下目录解决了！！
