### ISSUE TITLE
umi-examples context BUG

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#408]
https://github.com/umijs/umi-examples/tree/master/context

**Comment by xiaohuoni** [comment]
![2](https://user-images.githubusercontent.com/11746742/39393957-f97b58aa-4afd-11e8-8997-59a56188a2da.png)
```js
<Link to="/list">
      <Button type="primary">go to /list</Button>
</Link>
```
a标签里面不能有a标签，解析之后的dom
```html
<a href="/list">
    <a role="button" class="am-button am-button-primary" aria-disabled="false">
        <span>go to /list</span>
    </a>
</a>
```

**Comment by xiaohuoni** [comment]
![3](https://user-images.githubusercontent.com/11746742/39393981-615083b0-4afe-11e8-9c5c-816cd2d044fd.png)
从index跳转到list，title不修改
要在list刷新一下，才会修改
![4](https://user-images.githubusercontent.com/11746742/39393988-824b6fee-4afe-11e8-99ac-5c1e34c762a6.png)

**Comment by sorrycc** [comment]
> a 套 a 标签会给 warning

这是 react 的场景。

> 从index跳转到list，title不修改，要在list刷新一下，才会修改

那个 title 配置是给 html 文件的，所以切单页肯定不会刷新，需要单页刷新的，可以用 react-helmet 。

**Comment by xiaohuoni** [comment]
> 那个 title 配置是给 html 文件的，所以切单页肯定不会刷新，需要单页刷新的，可以用 react-helmet 。

这个你的例子里面，每一个路由都配置了，会让我觉得，这是一个内置的react-helmet 或者react-document-title的功能。

**Comment by sorrycc** [comment]
恩，这是一个可以改进的地方。
