### ISSUE TITLE
如何去除打包后的注释？

### ISSUE THREAD

**Issue by travonf** [umijs/umi#4081]
## What happens?

代码注释检查不通过，需要去除打包后的注释。

## Mini Showcase Repository(REQUIRED)

无

## How To Reproduce

![image](https://user-images.githubusercontent.com/18564432/75984624-bc8ce380-5f25-11ea-9ed3-656db6b955d5.png)
如图所示，添加uglifyJSOptions配置后执行yarn build,打包后的文件里还是有一堆注释。

## Context

- **Umi Version**: 2.13.0
- **Node Version**: v12.14.1
- **Platform**: win10x64 1909

**Comment by travonf** [comment]
已解决。

**Comment by cornwang** [comment]
> 已解决。

请问是如何解决的，我现在遇到 和你一样的问题
