### ISSUE TITLE
umi ui 界面中 antd-pro模板添加一直失败

### ISSUE THREAD

**Issue by September9** [umijs/umi#4082]
## What happens?
按照antd-pro官方例子 初始化项目，启动umi ui后，资产添加中，添加模板，一直失败。
![image](https://user-images.githubusercontent.com/30931753/75993926-2d87c780-5f35-11ea-9ea6-b0389ed6a823.png)

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
3
- **Node 版本**：
12.16.1
- **操作系统**：
mac

**Comment by cheneyjuu** [comment]
我也遇到同样的问题了

**Comment by ycjcl868** [comment]
更新下最新的呢，我这边可以

**Comment by cheneyjuu** [comment]
@September9 
我删除了用户目录下的`.umi`文件夹，重新`npm install`，就可以正常添加了。你可以试试。
