### ISSUE TITLE
【bug】umi3 的 src/.umi 下自动生成的 exports.ts ，import 路径错误（用了 '\'），包括但不限于：plugin-dva/exports.ts、plugin-initial-state/exports.ts

### ISSUE THREAD

**Issue by laixstx** [umijs/umi#4084]
## What happens?

umi3 的 src/.umi 下自动生成的 exports.ts ，import 路径错误（用了 '\'），包括但不限于：

**plugin-dva/exports.ts**
![image](https://user-images.githubusercontent.com/10735940/76042112-d0b8fb00-5f8e-11ea-8f20-3f9ab4ee5140.png)

**plugin-initial-state/exports.ts**
![image](https://user-images.githubusercontent.com/10735940/76042132-ddd5ea00-5f8e-11ea-8bfc-192742296c7d.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create umi` then upload to your GitHub

直接 yarn create umi 一个新的项目，配上 dva: { immer: true, hmr: true }

## How To Reproduce

运行 yarn start ，看 src/.umi 下生成的文件即可。

## Context

- **Umi Version**: 3.0.3
- **Node Version**: 12.14.1
- **Platform**: win10

**Comment by ycjcl868** [comment]
记得这个问题修了，重装试试

**Comment by sorrycc** [comment]
有问题再 reopen。
