### ISSUE TITLE
require 图片时，生成Base64路径和url路径数据格式不一样

### ISSUE THREAD

**Issue by linyongkangm** [umijs/umi#4085]
## What happens?

require 图片时，生成Base64路径的时候是esModule，而url路径数据格式是string。
期望能生成一致的数据格式。

![1583468105081_12C089DF-7BAC-4F05-915D-CF95FDCBFA5D](https://user-images.githubusercontent.com/17702643/76051014-6448f680-5fa4-11ea-8dc3-6c634c2a2a55.png)

## Context

- **Umi Version**: 3.0.2
- **Node Version**: 10.16.0
- **Platform**: mac

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
