### ISSUE TITLE
umi3.0 qiankun 配置问题

### ISSUE THREAD

**Issue by bestRenekton** [umijs/umi#4087]
## What happens?

# 主应用配置：
![image](https://user-images.githubusercontent.com/15810263/76047159-f2b97a00-5f9c-11ea-886a-fc077340af8c.png)

# app1配置：
![image](https://user-images.githubusercontent.com/15810263/76047174-fc42e200-5f9c-11ea-8bb4-76ea67971e5e.png)

## 最小可复现仓库

https://github.com/bestRenekton/demos2/tree/master/micro-front-test

## 复现步骤，错误日志以及相关配置

主应用启动时候报错  ` Invalid config key: qiankun`

## 相关环境信息

- **Umi 版本**：3.0.4
- **Node 版本**：v12.11.1
- **操作系统**：mac

**Comment by Slebee** [comment]
``yarn add @umijs/plugin-qiankun``
然后就可以了

**Comment by bestRenekton** [comment]
还有个问题，子应用start时报错plugin @umijs/plugin-qiankun is already registered

**Comment by gaorubin1990** [comment]
> 还有个问题，子应用start时报错plugin @umijs/plugin-qiankun is already registered,最新代码我已经提交了 谢谢
我也遇到这个问题

**Comment by EchoPark** [comment]
> > 还有个问题，子应用start时报错plugin @umijs/plugin-qiankun is already registered,最新代码我已经提交了 谢谢
> > 我也遇到这个问题

请问解决了么？

**Comment by Aledenn** [comment]
> > > 还有个问题，子应用start时报错plugin @umijs/plugin-qiankun is already registered,最新代码我已经提交了 谢谢
> > > 我也遇到这个问题
> 
> 请问解决了么？

请问解决了吗

**Comment by wsdqr001** [comment]
遇到了同样的问题 @Slebee @bestRenekton @EchoPark

**Comment by wsdqr001** [comment]
问题已解决，plugins里不要再引入@umijs/plugin-qiankun，只需要定义qiankun的配置，可以参考：
// plugins: ['@umijs/plugin-qiankun'],
  qiankun: {
    master: {
      defer: false, // 是否异步渲染
      jsSandbox: true, // 是否启用 js 沙箱
      prefetch: true, // 是否启用 prefetch 特性
    },
  },

@EchoPark @gaorubin1990 @bestRenekton
