### ISSUE TITLE
Build dist files pwacompat.min.js has 'const'

### ISSUE THREAD

**Issue by Superman-wc** [umijs/umi#4089]
devDependencies
"umi": "^2.1.2",
"umi-plugin-react": "^1.1.1"

.umirc.js

pwa: {
        manifestOptions: {
          srcPath: 'src/manifest.json',
        },
        workboxPluginMode: 'GenerateSW',
        workboxOptions: {
          swDest: 'service-worker.js',
          importWorkboxFrom: 'local',
        },
      },

build dist 

/pwacompat.min.js line 4
const data = _interopRequireDefault(require("react"));   

	
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

**Comment by ycjcl868** [comment]
尝试下 `targets: { ie: 11 }`
