### ISSUE TITLE
Umi3.0 如何在 global.ts 中 getStore

### ISSUE THREAD

**Issue by MinJieLiu** [umijs/umi#4090]
## What happens?

升级到 umi@3.x 。没有了 `g_app` 变量，如何在非组件中获取 `store` 呢？

场景：比如在全局 `request ` 中需要配置 `store` 中的数据 

建议在 `umi` 中导出 `getStore` API 吧。

## 最小可复现仓库

> 无

## 相关环境信息

- **Umi 版本**：3
- **Node 版本**：12
- **操作系统**：mac

**Comment by MinJieLiu** [comment]
找到了，是 `getDvaApp` 。

**Comment by JerryBerton** [comment]
> 找到了，是 `getDvaApp` 。

在哪里 我都把对象打印出来了还是获取不到啊

**Comment by MinJieLiu** [comment]
@JerryBerton 
```js
import { getDvaApp } from 'umi'
```

**Comment by JerryBerton** [comment]
> @JerryBerton
> 
> ```js
> import { getDvaApp } from 'umi'
> ```

没有啊 直接报错了

**Comment by JerryBerton** [comment]
> ```js
> import { getDvaApp } from 'umi'
> ```

 'umi' does not contain an export named 'getDvaApp'.

**Comment by MinJieLiu** [comment]
你配置里面开启了 dva 的插件没

https://umijs.org/zh-CN/plugins/plugin-dva#getdvaapp

**Comment by JerryBerton** [comment]
> 你配置里面开启了 dva 的插件没
> 
> https://umijs.org/zh-CN/plugins/plugin-dva#getdvaapp

 dva: {
    hmr: true
  }
这不就是开启了 connect 有 其他的没有

**Comment by MinJieLiu** [comment]
你要把项目启动，才会生成
![image](https://user-images.githubusercontent.com/6167727/76308602-19154780-6306-11ea-9b0d-813d0b3e994a.png)

**Comment by JerryBerton** [comment]
> 你要把项目启动，才会生成
> ![image](https://user-images.githubusercontent.com/6167727/76308602-19154780-6306-11ea-9b0d-813d0b3e994a.png)

你发的图片看不到啊

**Comment by MinJieLiu** [comment]
你启动项目试试，看看 .umi 目录里有个 plugin-dva/exports.ts

**Comment by JerryBerton** [comment]
> 你启动项目试试，看看 .umi 目录里有个 plugin-dva/exports.ts

![image](https://user-images.githubusercontent.com/11454938/76308925-ba9c9900-6306-11ea-8dd2-bb67a3940960.png)

**Comment by MinJieLiu** [comment]
怪了，比我的少一个文件，你 preset-react 升级到最新版了吗

**Comment by JerryBerton** [comment]
没有 我用的估计还是react

**Comment by JerryBerton** [comment]
> 怪了，比我的少一个文件，你 preset-react 升级到最新版了吗

能截屏一下你的config配置吗

**Comment by MinJieLiu** [comment]
![image](https://user-images.githubusercontent.com/6167727/76309734-51b62080-6308-11ea-9c6c-090b37862c8e.png)

**Comment by wwavelet** [comment]
> > ```js
> > import { getDvaApp } from 'umi'
> > ```
> 
> 'umi' does not contain an export named 'getDvaApp'.

确认配置了有效的dva model吗?
https://umijs.org/zh-CN/plugins/plugin-dva#import--connect-%E7%AD%89-api--from-umi-%E6%97%A0%E6%95%88%EF%BC%9F
我也遇到了，最后发现是因为没配置model

**Comment by JustGogoing** [comment]
朋友解决了吗  我打印 getDvaApp 是undefined

**Comment by wulinjie122** [comment]
> 朋友解决了吗 我打印 getDvaApp 是undefined

朋友，你解决了吗？

**Comment by GitHubGanKai** [comment]
如果你是在请求接口的api中可以这么使用 
// require.js 中：
`
import axios from 'axios';
import { getDvaApp } from 'umi';
// 以下的结果是undefined ，可能原因是，这个文件初始化的时候，getDvaApp并没有生成，
console.log('getDvaApp=>', getDvaApp);   

export const getUserInfo = (uid) =>{
   return new Promise((resolve,reject)=>{
      // 需要这样才能获取到
       console.log('store------>', getDvaApp()._store.getState())
   })
}`

**Comment by swdenglian** [comment]
我这里发现了一个，由vscode自动引入了 `.umi` 里面的getDvaApp, 而不是从 `umi` 中引入。导致打包后getDvaApp 获取到的是undefined
