### ISSUE TITLE
eslint配置无法生效

### ISSUE THREAD

**Issue by MangGoDio** [umijs/umi#4091]
## What happens?

`{
  "extends": "eslint-config-umi",
  "rules": {
    "jsx-a11y/anchor-is-valid": false
  }
}
`

## How To Reproduce

rules里的规则未生效，start以后依然生成了提醒

## Context

- **Umi Version**: v2.7.7
- **Node Version**: v10.5.3
- **Platform**: windows

**Comment by FoxGui** [comment]
.umirc.js文件我是这样配置的
```jsx
import { resolve } from 'path';

export default {
  chainWebpack(config) {
    config.module
      .rule('lint')
      .test(/\.js(x)?$/)
      .pre()
      .include.add(resolve(__dirname, './src'))
      .end()
      .use('eslint')
      .loader('eslint-loader');
  },
}
```
.eslintrc.js配置
```jsx
module.exports = {
  "extends": "eslint-config-umi", 
  "rules": { 
    "jsx-a11y/anchor-is-valid": 0
  }
}
```

**Comment by zevingao** [comment]
> ```js-jsx
> .include.add(resolve(__dirname, './src'))
> ```

你好，我像你这样配置后代码不能热更新了，请问有解决办法吗？

**Comment by zevingao** [comment]
找到原因了，是配置了outputPath后热更新失效的
