### ISSUE TITLE
[plugin-layout]配置项支持app.js不支持app.ts

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#4092]
## Mini Showcase Repository(REQUIRED)
![image](https://user-images.githubusercontent.com/7939085/76074179-f5849100-5fd5-11ea-9307-c7df76049475.png)
试了下 app.ts是真的不行
> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create umi` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by Ariel-Cheng** [comment]
请问有可以复现的仓库吗？因为我这边本地尝试是可以的。这个是测试项目 https://github.com/umijs/plugins/blob/master/example/app.ts#L11

**Comment by xiexingen** [comment]
> 尝试

是我自己我这边的问题
