### ISSUE TITLE
[插件] 插件编写的时候 ， api.modifyRoutes 执行两次

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#4093]
## What happens?

刚开始是觉得 `umi2` 升 `umi3` 之后，项目编译时间更久了。本来以为是因为 `nodemodules` 里面也走 `babel` 的原因，就没有太在意。后来再实现一个需求的时候，发现了 ` api.modifyRoutes` 比 `umi@2` 的时候多执行了一次。而且通过debug，打印日志，展示出来的结果也是第一次的结果。但是最终结果，确是执行两次之后的结果

![image](https://user-images.githubusercontent.com/11746742/76090976-99326900-5ff7-11ea-86fa-fce08258857c.png)

## 最小可复现仓库
可以新建一个插件，`src/index` 写以下内容。
```ts
import { IApi } from '@umijs/types';
import { resetMainPath } from '@alitajs/utils';

export default (api: IApi) => {
  api.describe({
    key: 'mainPath',
    config: {
      schema(joi) {
        return joi.string();
      },
    },
  });

  if (api.userConfig.mainPath) {
    api.modifyRoutes((routes: any[]) => {
      return resetMainPath(routes, api.config.mainPath);
    });
  }
};

function resetMainPath(routes: any[], mainPath: string) {
  let newPath = mainPath;
  // 把用户输入/abc/ 转成 /abc
  if (newPath !== '/' && newPath.slice(-1) === '/') {
    newPath = newPath.slice(0, -1);
  }
  // 把用户输入abc 转成 /abc
  if (newPath !== '/' && newPath.slice(0, 1) !== '/') {
    newPath = `/${newPath}`;
  }
  return routes.map(element => {
    if (element.path === '/' && !element.routes) {
      element.path = '/index';
    }
    if (element.path === newPath) {
      element.path = '/';
    }
    if (Array.isArray(element.routes)) {
      element.routes = resetMainPath(element.routes, mainPath);
    }
    return element;
  });
}

```
> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：3
- **Node 版本**：10.13.0
- **操作系统**：mac

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/76684836-25710b80-664a-11ea-8016-5ecc97e23288.png)

**Comment by fangaofeng** [comment]
我配置参考ant pro 升级umi3，现在发现编译至少两次。如果vs code中进行attach的debug，也会编译一到两次，此时代码没有修改。css-loader » postcss-loader » less-loader » node_modules\antd\es\modal\style\index.less 0  ，停留时间较长

**Comment by fangaofeng** [comment]
修改config和文件名后缀，无法触发重新编译。提示文件不存在，比如login.js 更改为login.tsx，提示编译login.js不存在。在sourcemap提示很慢

**Comment by sorrycc** [comment]
> 比如login.js 更改为login.tsx，提示编译login.js不存在

这是 webpack 的问题。

**Comment by ithack** [comment]
这个两次的问题解决了吗？

**Comment by sorrycc** [comment]
[sorrycc-Iipi2a.zip](https://github.com/umijs/umi/files/4358596/sorrycc-Iipi2a.zip)
不能复现。

1. 执行 umi g tmp
2. 检查 .umi/core/routes.ts，只生成了一个 /foo 的路由

```js
const routes = [
  {
    "path": "/",
    "exact": true,
    "component": require('@/pages/index.tsx').default
  },
  {
    "path": "/foo",
    "component": require('/private/tmp/sorrycc-Iipi2a/pages/index.tsx').default
  }
];
```
