### ISSUE TITLE
umi@3 运行时插件如何保证多个插件的顺序

### ISSUE THREAD

**Issue by MinJieLiu** [umijs/umi#4094]
## What happens?

umi@3 运行时插件如何保证多个插件的顺序

比如 `addRuntimePlugin` 中 `rootContainer` 在多个插件中如同洋葱一样，但怎么保证多个插件按照一定的顺序执行呢？因为插件都是自动从 `package.json` 中读取的。

好像项目中 `app.ts` 中的写法优先级大于插件中的，包在了里层。

## 起因

目前在结合 `react-activation` 做 `KeepAlive`，`Provider` 需要包在所有最顶层。

## 最小可复现仓库

> 无

## 相关环境信息

- **Umi 版本**：3
- **Node 版本**：12
- **操作系统**：mac

**Comment by sorrycc** [comment]
两个思路，

1. 要求使用者最后挂载此插件
2. addRuntimePlugins 时通过 stage 让自己靠后，比如 `api.addRuntimePlugins({ fn: ()=> ['runtime plugins'], stage: Infinity })`

**Comment by xiaohuoni** [comment]
`react-activation` 的作者有一个实现 https://github.com/alitajs/umi-plugin-keep-alive

**Comment by MinJieLiu** [comment]
@xiaohuoni 这个插件已经不能在 umi@3.x 上运行了

**Comment by MinJieLiu** [comment]
@xiaohuoni 有计划兼容 umi@3.x 吗

**Comment by CJY0208** [comment]
@MinJieLiu umi-plugin-keep-alive@0.0.1-beta.9 已支持 umi@3.x
