### ISSUE TITLE
路由配置menu时，icon不起作用。

### ISSUE THREAD

**Issue by hzgotb** [umijs/umi#4095]
## What happens?

如果使用的是已经迁移到antd@4的pro-layout，此时使用的是图标组件而非Icon组件，这时候如果icon传入字符的话，是无法显示图标的。除非使用@ant-design/compatible包。

当我直接使用组件的时候
config/routes.tsx
```ts
{
    path: '/workbench/dashboard',
    component: '@/pages/dashboard',
    menu: {
      name: '概覽',
      icon: <DashboardOutlined />,
    },
},
```

然后看了一下.umi下的routes
```ts
{
    "path": "/workbench/dashboard",
    "component": require('@/pages/dashboard').default,
    "menu": {
        "name": "概覽",
        "icon": {
            "type": {},
            "key": null,
            "ref": null,
            "props": {},
            "_owner": null,
            "_store": {}
        }
    },
    "exact": true
},
```
应该是umi在编译config时没编译到组件。

## 相关环境信息

- **Umi 版本**：3.0.4
- **Node 版本**：12.9.1
- **操作系统**：macOS 10.15.2

**Comment by weicong** [comment]
https://github.com/umijs/umi-plugin-antd-icon-config

**Comment by hzgotb** [comment]
> https://github.com/umijs/umi-plugin-antd-icon-config

报错了
```bash
api.register() failed, hook.fn must supplied and should be function, but got /Users/xxx/Projects/company/yms/antd-pro/node_modules/umi-plugin-antd-icon-config/lib/app.js.
```

**Comment by hzgotb** [comment]
> https://github.com/umijs/umi-plugin-antd-icon-config

这个是获取设置在routeItem.icon中的。umi@3的话，是设置在routeItem.menu.icon中的。

**Comment by hzgotb** [comment]
看了一下源码，umi的route只把component和wrapper进行require。
umi@3中，pro-layout如果使用 @ant-design/icon@4 的话，在没有插件下，必须在menu中的icon直接写成ReactNode。
如果要以插件形式的话，可能需要修改routesToJSON相关的部分。

暂时就研究了这些。

**Comment by felhz** [comment]
你可以运行配置添加 export const layout = { menuItemRender: ( menuItemRender)=> { 
return (ReactNode)
}} 自定义渲染菜单项

**Comment by hzgotb** [comment]
> 你可以运行配置添加 export const layout = { menuItemRender: ( menuItemRender)=> {
> return (ReactNode)
> }} 自定义渲染菜单项

看了一下props。還得重新去匹配route再生成ReactNode。太麻煩了。

**Comment by gouflv** [comment]
现在的办法只能是路由和菜单分两套配置来写。.umi 的 routes 就是个黑盒

**Comment by leftstick** [comment]
如果是 `umi@3` 的话，routes这么配置：

```typescript
import { defineConfig } from "umi";

export default defineConfig({
  antd: {
    dark: true,
  },
  layout:{
    name: 'Ant Design', 
  },
  routes: [{
    path: '/welcome',
    component: 'welcome.tsx',
    menu: {
      name: '欢迎',
      icon: 'github',
    },
    layout:{
      hideNav: true,
    },
    access: 'canRead',
  }]
});
```

注意里面的 `icon` 配置，使用的是 `antd@4` 的图标组件，把图标组件 `<GithubOutlined />` 名字小写，然后去掉 `outlined`，剩下的 `github` 就可以用在 `menu` 的配置里了

**Comment by LarryZhao0616** [comment]
> 如果是 `umi@3` 的话，routes这么配置：
> 
> ```ts
> import { defineConfig } from "umi";
> 
> export default defineConfig({
>   antd: {
>     dark: true,
>   },
>   layout:{
>     name: 'Ant Design', 
>   },
>   routes: [{
>     path: '/welcome',
>     component: 'welcome.tsx',
>     menu: {
>       name: '欢迎',
>       icon: 'github',
>     },
>     layout:{
>       hideNav: true,
>     },
>     access: 'canRead',
>   }]
> });
> ```
> 
> 注意里面的 `icon` 配置，使用的是 `antd@4` 的图标组件，把图标组件 `<GithubOutlined />` 名字小写，然后去掉 `outlined`，剩下的 `github` 就可以用在 `menu` 的配置里了
> 
> 效果如下：
> 
> <img alt="Screen Shot 2020-04-08 at 11 23 49" width="456" src="https://user-images.githubusercontent.com/1059956/78741243-747d3880-798b-11ea-9a88-a2a4e3f30b0a.png">

请问你这个写法在官网文档哪里写出来了？你们指望所有人去猜新写法吗？

**Comment by leftstick** [comment]
@LarryZhao0616  强行解释的话，文档里有 `当前菜单的左侧 icon，可选 antd 的 icon name 和 url`。不过如你所言，`icon name` 也不是那么友好。稍后文档做些调整吧

**Comment by mouseTrip** [comment]
![image](https://user-images.githubusercontent.com/26135245/79970875-2b1e0480-84c6-11ea-8a75-ae59b48cc5fd.png)

使用最新的`yarn create @umijs/umi-app`，安装了依赖，只做了如上图的配置，菜单栏的图标不生效

![image](https://user-images.githubusercontent.com/26135245/79971040-64567480-84c6-11ea-9052-07cf2a9de804.png)

**Comment by leftstick** [comment]
@mouseTrip 给个可复现的repo吧。我弄不出来这个效果

**Comment by mouseTrip** [comment]
基于最新umi脚手架踩坑，icon不能配置在menu里面，要和menu平级单独写出，才能读取到，也不能安装`umi-plugin-antd-icon-config`这个插件，否则启动会报`toUpperCase`错误。
![image](https://user-images.githubusercontent.com/26135245/80088214-c7abd980-858e-11ea-95ef-53adb9e0d7a5.png)

**Comment by zhangminggeek** [comment]
> 基于最新umi脚手架踩坑，icon不能配置在menu里面，要和menu平级单独写出，才能读取到，也不能安装`umi-plugin-antd-icon-config`这个插件，否则启动会报`toUpperCase`错误。
> ![image](https://user-images.githubusercontent.com/26135245/80088214-c7abd980-858e-11ea-95ef-53adb9e0d7a5.png)

这个方法有用，感谢大佬

**Comment by io-o** [comment]
这也太操蛋了吧， 全靠猜？

**Comment by EmiyaYang** [comment]
菜单没法约定式生成？

**Comment by EmiyaYang** [comment]
约定式路由配置的 icon 不能被解析出来

**Comment by erichDuanET** [comment]
> 这也太操蛋了吧， 全靠猜？

新版本总是要有个踩坑的过程，淡定

**Comment by edvardchen** [comment]
约定式路由 icon 没有被解析

**Comment by git-lt** [comment]
umijs: 3.2.23
proLayout: 6.5.0
配置在 menu 外层依然不生效
![image](https://user-images.githubusercontent.com/8443758/95702479-03427900-0c7f-11eb-9e18-56a35275ef59.png)
![image](https://user-images.githubusercontent.com/8443758/95702497-0fc6d180-0c7f-11eb-8d1e-efc212648888.png)
![image](https://user-images.githubusercontent.com/8443758/95702516-18b7a300-0c7f-11eb-9c70-83bce4d75f96.png)

**Comment by windf17** [comment]
以上说的几种方法我都试了，不行啊！！
```
                menu: { name: '账户' },
                icon: 'setting',
```
```
                menu: {
                         name: '账户' ，
                         icon: 'setting',
               },
```

**Comment by mengxxSELF** [comment]
> 以上说的几种方法我都试了，不行啊！！
> 
> ```
>                 menu: { name: '账户' },
>                 icon: 'setting',
> ```
> 
> ```
>                 menu: {
>                          name: '账户' ，
>                          icon: 'setting',
>                },
> ```

    "umi": "^3.5.21"    也无法展示。还是自行处理吧

**Comment by yinzixie** [comment]
我也不行。都没用，只能用 `table` 和 `crown` 。

**Comment by Milesyan** [comment]
蛋了个疼 招个写文档的好不

**Comment by 521xueweihan** [comment]
支持的图标在这里：https://ant.design/components/icon-cn/

使用方法：不要样式类型，例如：<DollarOutlined />，icon 就写 dollar

官方文档说明：https://umijs.org/docs/max/layout-menu#icon

**Comment by gaollard** [comment]
全靠猜，决定自己开发一套了～，要一起搞的加我

**Comment by astfn** [comment]
> 全靠猜，决定自己开发一套了～，要一起搞的加我

我也有这个想法，一个小小的问题都不好解决
