### ISSUE TITLE
建议在 Umi@3 中 生成的 .umi 文件加入 @ts-nocheck

### ISSUE THREAD

**Issue by MinJieLiu** [umijs/umi#4097]
## What happens?

在 umi@3 中，`.umi` 目录下的文件建议禁止 ts 检查 `@ts-nocheck`，现在一堆错。`tsconfig.json` 排除这个目录无效。

## 最小可复现仓库

> 无

## 相关环境信息

- **Umi 版本**：3
- **Node 版本**：12
- **操作系统**：mac

**Comment by ycjcl868** [comment]
给个复现步骤

**Comment by MinJieLiu** [comment]
主要是我想在提交代码之前验证 ts 有没有错误信息，有错误阻断提交。
![image](https://user-images.githubusercontent.com/6167727/76157443-d60b7680-6143-11ea-940a-d7413eaae229.png)

**Comment by sorrycc** [comment]
重复问题，https://github.com/umijs/umi/issues/4194 跟进。

**Comment by sorrycc** [comment]
重复问题，https://github.com/umijs/umi/issues/4194 跟进。
