### ISSUE TITLE
umi v3 如何全局获取dispatch？

### ISSUE THREAD

**Issue by shangdev** [umijs/umi#4099]
在umi v2中，使用window.g_app.store.dispatch可以获取到；
在umi v3中：  
如果是函数式组件，使用hooks方式能够轻松获取；  
如果是class方式则使用：  `import { getDvaApp } from 'umi';  `  
其中getDvaApp 相当于window.g_app，但是当使用getDvaApp._store.dispatch()时提示报错信息：`Uncaught TypeError: Cannot read property 'dispatch' of undefined`

那么什么是正确的获取diapatch的方法呢？

**Comment by shangdev** [comment]
getDvaApp返回个函数，需要`getDvaApp()._store.dispatch()`

**Comment by JerryBerton** [comment]
> getDvaApp返回个函数，需要`getDvaApp()._store.dispatch()`
请问你是怎么获取到的

**Comment by GitHubGanKai** [comment]
import { getDvaApp } from 'umi';

> > getDvaApp返回个函数，需要`getDvaApp()._store.dispatch()`
> > 请问你是怎么获取到的

// require.js 中：
`
import axios from 'axios';
import { getDvaApp } from 'umi';
// 以下的结果是undefined ，可能原因是，这个文件初始化的时候，getDvaApp并没有生成，
console.log('getDvaApp=>', getDvaApp);

export const getUserInfo = (uid) =>{
return new Promise((resolve,reject)=>{
// 需要这样才能获取到
console.log('store------>', getDvaApp()._store.getState())
})
}`
