### ISSUE TITLE
TS 下 withRouter 缺少类型声明文件

### ISSUE THREAD

**Issue by arvinxx** [umijs/umi#410]
![default](https://user-images.githubusercontent.com/28616219/39396274-da3f896e-4b1d-11e8-856c-ef609c04250b.png)

**Comment by zhang740** [comment]
https://github.com/umijs/umi/blob/ae9fea44ce227157799bf6a5a8b1e4237640ae64/packages/umi/package.json#L34

少 redirect.d.ts navlink.d.ts withRouter.d.ts @sorrycc

**Comment by xiaohuoni** [comment]
@zhang740 直接提个PR会快一点，他说这两天先处理业务上的事情。
