### ISSUE TITLE
[hd] umi@3.x如何开启hd或者vw适配

### ISSUE THREAD

**Issue by JustGogoing** [umijs/umi#4102]
看在2.x的版本可以通过开启hd使用rem适配，但是在3没有找到相关选项

**Comment by ycjcl868** [comment]
https://github.com/umijs/plugins/pull/24，在这，还没合

**Comment by xiaohuoni** [comment]
我是复制下来自己发了包先用 `yarn add @alitajs/hd` `hd:true`

**Comment by JustGogoing** [comment]
我是自己通过 extraPostCSSPlugins 配置了vw
