### ISSUE TITLE
设置路由的wrappers属性会导致，layout布局重复挂载

### ISSUE THREAD

**Issue by exvu** [umijs/umi#4104]
根据文档说明，我在路由中设置wrapper，一切都能正常显示，但是使用link或history.push会导致layout组件先卸载后挂载，我尝试在wrappers组件中useEffect 打印日志，发现wrappers组件也是先卸载后挂载。由此我猜测这是一个bug。

- Umi Version: 3.0.5

- Node Version: 13.10.1

- Platform: macos

**Comment by beginnerJq** [comment]
我第一次执行`history.push`时，组件会重新挂载一次

**Comment by beginnerJq** [comment]
是再初始化一次

**Comment by atzcl** [comment]
同有这个问题，第一次路由跳转的时候，会将根节点的 layout 销毁重建，antd pro 可重现 [https://github.com/ant-design/ant-design-pro/](https://github.com/ant-design/ant-design-pro/)

**Comment by linxianxi** [comment]
有这个问题，不打算修复了吗

**Comment by exvu** [comment]
@chenshuai2144 @sorrycc

**Comment by xuwenqing2014** [comment]
怎么解决呀

**Comment by xuwenqing2014** [comment]
对umi有点失望
