### ISSUE TITLE
is umi dependencies version locked/shrinkwrapped and documented?

### ISSUE THREAD

**Issue by aletus** [umijs/umi#411]
I upgraded umi to the latest 1.2.4 version and ant-designed got upgraded also.  the new antd has a bug and required code change to work around.

i have antd version 3.3.0 in my project and umi installed globally and it seemed to pick up antd version 3.4.4 from the umi global installation

this is unexpected because reading the umi release note did not mention antd upgrade.

**Comment by sorrycc** [comment]
umi is using the ^3.0.0 version of antd by default, and if you specify antd dependency in package.json, umi will use this one.
