### ISSUE TITLE
scss 配置不生效，umi3.0

### ISSUE THREAD

**Issue by hlerenow** [umijs/umi#4111]
```
  chainWebpack(config) {
    config.module.rule('scss')
    .test(/\.scss$/)
    .use('css')
    .loader('css-loader')
    return config
  }
```
在umirc.js 中配置如下代码，编译scss报错不生效

**Comment by sorrycc** [comment]
安装 `@umijs/plugin-sass` 即可。

**Comment by cpocar** [comment]
我从2.X升级到3.0.6 之后同样的配置sass全局变量在scss文件中报undefined。我直接新建个项目同样的配置就没问题。能不能指个思路

**Comment by hlerenow** [comment]
> 我从2.X升级到3.0.6 之后同样的配置sass全局变量在scss文件中报undefined。我直接新建个项目同样的配置就没问题。能不能指个思路

我也是2.x升级上来的，装了@umijs/plugin-sass 这个插件，虽然编译能过了，但是antd的样式好像都不见了，升级的坑有点多，我暂时还是放弃升级😂
