### ISSUE TITLE
umi3.0的@umijs/plugin-sass 无法注入全局变量

### ISSUE THREAD

**Issue by sandercage** [umijs/umi#4115]
## What happens?

umi3.0的@umijs/plugin-sass 无法注入全局变量

## Mini Showcase Repository(REQUIRED)
https://github.com/sandercage/test

## How To Reproduce

```
yarn
yarn start
```

![image](https://user-images.githubusercontent.com/36032199/76282529-e3a33680-62d2-11ea-9b08-965177ce8ae1.png)

## Context

- **Umi Version**: 3.0.6
- **Node Version**: 13.X
- **Platform**: macOS

**Comment by sorrycc** [comment]
node-sass 或 sass-loader 更新了吧，注入方式变了。参考：https://github.com/webpack-contrib/sass-loader/issues/760#issuecomment-534043880

**Comment by minsonl** [comment]
再配置文件加上这个试试
sass:{
    prependData: `$color:red;`,
  }
然后全局使用这个$color

**Comment by ppatch** [comment]
修改为 prependData 引入也一样不成功
