### ISSUE TITLE
yarn create umi, husky 不生效

### ISSUE THREAD

**Issue by L-Jovi** [umijs/umi#4116]
## What happens?

通过 `yarn create umi` 生成 ant-design-pro 模板项目，git commit 不会运行 husky 对应的 lint-staged 脚本命令

## How To Reproduce

1. mkdir my-app

2. cd my-app && yarn create umi
  1. 选择 ant-design-pro 模板
  2. 选择 typescript 作为开发语言
  3. 选择 ant-design 4.x 作为 ui 规范

3. yarn

4. git flow init

5. git commit -m "xxx"
  发现 husky 对应 hooks lint-staged 并没有被运行

## Context

- **Umi Version**:  2.13.0
- **Node Version**: v10.18.0
- **Platform**: Mac OS X

**Comment by MinJieLiu** [comment]
我的 windows 10 不行， mac 可以

**Comment by L-Jovi** [comment]
我这边试了好几次通过 yarn create umi 生成 ant design pro 模板项目，都是不可以在 git commit 的时候调用到 hooks 的 lint-staged 脚本的

然后这边本地尝试了 yarn 重新安装 husky 后就可以了，是因为在 .git 中 hooks 安装了对应的脚本么？这个功能怎么才能保证生成模板后就是可用的

**Comment by MinJieLiu** [comment]
我的 Windows 10 重新 clone 下来 再 yarn 也不行

**Comment by ziven27** [comment]
@L-Jovi  umi 3 已经去掉了 `husky` 用 `yorkie` 替代了

**Comment by nsuedu** [comment]
> 我的 Windows 10 重新 clone 下来 再 yarn 也不行

试试这个解决方案[lint-staged not running on precommit](https://stackoverflow.com/questions/50048717/lint-staged-not-running-on-precommit)
