### ISSUE TITLE
【小白求助】umi2.x如何支持sass(scss)

### ISSUE THREAD

**Issue by llh1187** [umijs/umi#4125]
就找到文档的这句话：
配置 node-sass 的选项。注意：使用 sass 时需在项目目录安装 node-sass 和 sass-loader 依赖。
https://v2.umijs.org/zh/config/#sass

不知道在config/config.js中如何去写，有大佬可以分享下示例代码吗？

**Comment by ybzjsxh** [comment]
把这两个依赖添加上就能直接用了🥴。

**Comment by llh1187** [comment]
> 把这两个依赖添加上就能直接用了🥴。

配置 node-sass 的选项，这个不需要在config/config.js或者umirc.js中去写吗？

**Comment by ybzjsxh** [comment]
> > 把这两个依赖添加上就能直接用了🥴。
> 
> 配置 node-sass 的选项，这个不需要在config/config.js或者umirc.js中去写吗？

不需要哦。
