### ISSUE TITLE
新的3版本必须把404路由手动配置到各个自路由的routes列表里才能用，原来的版本只要配置到最外层routes即可

### ISSUE THREAD

**Issue by sujingclg** [umijs/umi#4126]
## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by sorrycc** [comment]
开了 layout ?

**Comment by sujingclg** [comment]
是的，基于原有的ant design pro项目，尝试迁移到umi3的过程中发现需要在嵌套路由每级都必须指定404才能最终返回404页面。

**Comment by sorrycc** [comment]
路由没有这方面的变更。

**Comment by sorrycc** [comment]
感觉还是配置方式的问题。

比如，

```
path: /
  path: /foo
    path: /foo/a
    path: /foo/b
    component: foo-404
  path: /bar
  component: 404
```

那么访问 `/hoo` 会通过 404 渲染，而访问 `/foo/hoo` 则会通过 foo-404 渲染。这在 umi 2 和 3 下是一致的。

**Comment by sujingclg** [comment]
明白了，原来是本来就应该是这样，是我理解错了，感谢答复。
