### ISSUE TITLE
Warning: Cannot update a component from inside the function body of a different component.

### ISSUE THREAD

**Issue by linyongkangm** [umijs/umi#4127]
## What happens?

Model的值在component里触发update就报Warning

## How To Reproduce
`
// models/Num.tsx
function useNum(): [number, () => void] {
  const [num, setNum] = useState(0);
  function add() {
    setNum(n => {
      return n + 1;
    });
  }
  return [num, add];
}

// pages/index.tsx
export default () => {
  const [num, add] = useModel('Num');
  return (
    <div>
      <p onClick={() => add()}>{num}</p>
    </div>
  );
};
`

## Context

- **Umi Version**: 3.0.2
- **Node Version**: 10.16.0
- **Platform**: mac

**Comment by leftstick** [comment]
It was already fixed in latest verison of `@umijs/plugin-model`, please upgrade your dependencies
