### ISSUE TITLE
umi.ts入口文件问题

### ISSUE THREAD

**Issue by qingxiao** [umijs/umi#4129]
umi.ts作为构建入口文件，其中有如下代码：
```
const clientRender = plugin.applyPlugins({
  key: 'render',
  type: ApplyPluginsType.compose,
  initialValue: () => {
    return renderClient({
      // @ts-ignore
      routes: require('./core/routes').routes,
      plugin,
      history: createHistory(),
      rootElement: '{{{ rootElement }}}',
      defaultTitle: '{{{ defaultTitle }}}',
    });
  },
  args: {},
});

export default clientRender();
```
- 这个地方导出模块clientRender()执行结果为`undefined`，
- .umirc.ts 配置 `memo.library('umiSubApp').libraryTarget('umd')`启动服务器
- 浏览器输出`window.umiSubApp`为 `Module {default: undefined, __esModule: true, Symbol(Symbol.toStringTag): "Module"}`
- 由于导出为空，导致当项目作为子应用，在`src/app.ts`中配置了qiankun相关的内容，获取不到导出的生命周期

![image](https://user-images.githubusercontent.com/3422905/76491449-a8d30700-6468-11ea-9329-357ea99cc162.png)

## 相关环境信息

- **Umi 版本**：v3.0.7
- **Node 版本**：v12.16.1
- **@umijs/plugin-qiankun 版本： "^2.0.5"
- **操作系统**：mac

**Comment by sorrycc** [comment]
最根本的问题是 `clientRender()` 返回 undefined?

**Comment by qingxiao** [comment]
> 最根本的问题是 `clientRender()` 返回 undefined?

clientRender()返回的undefined，相当于模块导出为undefined啊, 没有把app.ts里面的东西导出呢

**Comment by qingxiao** [comment]
> > 最根本的问题是 `clientRender()` 返回 undefined?
> 
> clientRender()返回的undefined，相当于模块导出为undefined啊, 没有把app.ts里面的东西导出呢
再贴一个**子应用**的配置，主应用模块中qiankun使用还需要配置 **libraryExport** 来将`default`内容提升
`
import { defineConfig } from 'umi';
const packageName = 'umiSubApp';

export default defineConfig({
  base: `/subapp`, // 子应用的 base，默认为 package.json 中的 name 字段
  routes: [{ path: '/', component: '@/pages/index' }],

  chainWebpack(memo, { env, webpack, createCSSRule }) {
    //qiankun.umijs.org/zh/faq/#application-died-in-status-loading-source-code-you-need-to-export-the-functional-lifecycles-in-xxx-entry
    memo.output
      .library(`${packageName}`)
      .libraryTarget('umd')
      .libraryExport('default')
      .jsonpFunction(`webpackJsonp_${packageName}`);
  },
});
`

**Comment by sorrycc** [comment]
设置 mountElementId 为 `''` 试试，https://umijs.org/config#mountelementid

**Comment by qingxiao** [comment]
> 设置 mountElementId 为 `''` 试试，https://umijs.org/config#mountelementid

刚看了下， 配置mountElementId 为 `''`后，估计没有调用renderDOM，直接返回的组件模块；
其实现在的问题是，正常构建后，没有导出app里面配置的export相关的内容，主要是qiankun在主应用里面需要去获取子应用并调用其生命周期

子应用 app.ts 配置
```
export const qiankun = {
  // 应用加载之前
  async bootstrap(props) {
    console.log('app1 bootstrap', props);
  },
  // 应用 render 之前触发
  async mount(props) {
    console.log('app1 mount', props);
  },
  // 应用卸载之后触发
  async unmount(props) {
    console.log('app1 unmount', props);
  },
};
```
qiankun源码部分
```
globalVariableExports = window[appName] || {};
bootstrapApp = globalVariableExports.bootstrap; // eslint-disable-next-line prefer-destructuring
 mount = globalVariableExports.mount; // eslint-disable-next-line prefer-destructuring
unmount = globalVariableExports.unmount;
```

**Comment by sorrycc** [comment]
@kuitos @yutingzhao1991 看下。

**Comment by kuitos** [comment]
没看明白。。
为啥子应用要配 webpack，不能直接用插件？ @qingxiao

**Comment by kuitos** [comment]
子应用没用 @umijs/plugin-qiankun 插件导致没有在 entry 里导出相应的钩子。umi 应用的 app.ts 并不是 entry

**Comment by qingxiao** [comment]
> 没看明白。。
> 为啥子应用要配 webpack，不能直接用插件？ @qingxiao
> 子应用没用 @umijs/plugin-qiankun 插件导致没有在 entry 里导出相应的钩子。umi 应用的 app.ts 并不是 entry

直接用了插件 并且子应用和主应用使用的相同的 ` "@umijs/plugin-qiankun": "^2.0.5"`，webpack是为了导出`umd`模式的模块，见FAQ：
https://qiankun.umijs.org/zh/faq/#application-died-in-status-loading-source-code-you-need-to-export-the-functional-lifecycles-in-xxx-entry
![image](https://user-images.githubusercontent.com/3422905/76716531-7debfa00-676b-11ea-9fcb-bd95bbc4c380.png)




如果没配置插件，app.ts中导出`qiankun`变量，umi会进行检测报错

**Comment by Plortinus** [comment]
> 子应用没用 @umijs/plugin-qiankun 插件导致没有在 entry 里导出相应的钩子。umi 应用的 app.ts 并不是 entry

请问umi的entry是啥，为啥umi的[官方配置文档](https://umijs.org/zh-CN/plugins/plugin-qiankun#%E5%AD%90%E5%BA%94%E7%94%A8%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE)是这个app.js

**Comment by kuitos** [comment]
使用了 @umijs/plugin-qiankun 不需要再去管 webpack umd 这些配置，插件会帮你自动做掉
