### ISSUE TITLE
升级新版本之后ie报错

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#413]
umi-plugin-dva 升级到0.6.3
```js
Warning: The <DvaContainer /> component appears to have a render method, but doesn't extend React.Component. This is likely to cause errors. Change DvaContainer to extend React.Component instead. 
SCRIPT5022: 引发了异常但未捕获 
umi.js, 行17111 字符5
The above error occurred in the <DvaContainer> component:
    in DvaContainer

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. 
SCRIPT5022: 引发了异常但未捕获 
```
https://github.com/umijs/umi-examples/tree/master/with-dva
可重现

**Comment by xiaohuoni** [comment]
umi 1.1.4 和 umi-plugin-dva 0.5.0 下可以正确运行

**Comment by xiaohuoni** [comment]
补充一句Windows 10

**Comment by xiaohuoni** [comment]
在 https://github.com/umijs/umi-examples/tree/master/with-dva 下安装
umi1.1.4 umi-plugin-dva 0.5.0  也还是有这个问题
但是在我的项目中umi1.1.4 umi-plugin-dva 0.5.0 这个环境是可以的。
@sorrycc

**Comment by xiaohuoni** [comment]
在群里看到其他朋友，说在mac上模拟的ie浏览器，也有这个问题

**Comment by sorrycc** [comment]
mac 上怎么模拟 IE 浏览器？

**Comment by xiaohuoni** [comment]
![_20180508174047](https://user-images.githubusercontent.com/11746742/39750120-ff766330-52e6-11e8-8cc3-ace8c436fd1a.jpg)

**Comment by sorrycc** [comment]
经测试发现，是 `@babel/runtime@7.0.0-beta.46` 的问题，`@babel/runtime@7.0.0-beta.44` 是好的。

**Comment by sorrycc** [comment]
测过 @vue/cli@3 也有这个问题。

```js
function A() {}
A.prototype.a = 'aaa';

class B extends A {}
console.log(B.prototype.a);
```

IE10 下输出是 undefined，IE11 是 aaa。

**Comment by sorrycc** [comment]
create-react-app@next 没有这个问题，因为他们 release 的版本用的是 7.0.0-beta.44。

**Comment by sorrycc** [comment]
https://github.com/babel/babel/issues/7892

**Comment by dgeibi** [comment]
core-js 的 `Object.setPrototypeOf` polyfill 需要支持 `__proto__` ，但 ie 10 不支持

加个更好的 polyfill 可以解决：

```js
import '@babel/polyfill'
Object.setPrototypeOf = require('setprototypeof')
```

**Comment by xiaohuoni** [comment]
@dgeibi @sorrycc 引入之后存在其他的问题。
在[umi/umi-examples/with-dva](https://github.com/umijs/umi-examples/tree/master/with-dva)里面引入，存在以下问题。
```js
SCRIPT5022: [React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.
See: http://formatjs.io/guides/runtime-environments/ 
umi.js, 行1264 字符5
The above error occurred in the <IntlProvider> component:
    in IntlProvider
    in Unknown (created by Connect(Component))
    in Connect(Component) (created by Route)
    in Route (created by withRouter(Connect(Component)))
    in withRouter(Connect(Component)) (created by Route)
    in Route (created by Route)
    in Switch (created by Route)
    in Route
    in Router (created by ConnectedRouter)
    in ConnectedRouter
    in Unknown
    in Provider (created by DvaContainer)
    in DvaContainer

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. 
SCRIPT5022: [React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.
See: http://formatjs.io/guides/runtime-environments/ 
umi.js, 行48647 字符7
```
在我们公司的项目中使用，没有报错，可以访问到静态页面（首页，广告之类的）但是dva/fetch无法跨域请求服务器。
```js
SEC7118: http://xxx.com/apiIndex.php的 XMLHttpRequest 需要跨域资源共享(CORS)。 
localhost:5000
TypeError: 对象不支持“rerender”属性或方法 
TypeError: 对象不支持“dispose”属性或方法 
Unhandled promise rejectionTypeError: 对象不支持“rerender”属性或方法 
SEC7120: 在 Access-Control-Allow-Origin 标头中未找到源 http://localhost:5000。 
localhost:5000
SCRIPT7002: XMLHttpRequest: 网络错误 0x80070005, 拒绝访问。
```
还有导致其它的组件模块失效。
```js
The above error occurred in the <EchartsReact> component:
    in EchartsReact (created by MapChartComponent)
    ...
Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. 
```

**Comment by sorrycc** [comment]
这两个问题和 class 继承应该都没问题。

**Comment by xiaohuoni** [comment]
恩，主要是我之前能发布上线的版本（兼容ie10），即不存在fetch跨域兼容问题，也不存在组件兼容问题，对我真的是迷之干扰啊。（捂脸）我再测试一下。

**Comment by 951565664** [comment]
@dgeibi 有用！！！

**Comment by 951565664** [comment]
@dgeibi 方案有用！
想请教下，你是如何发现这个问题的。因为我的ie报错，但一直报：‘这是一个异常’，根本定位不到哪行代码出问题的，也根本发现不了是哪个方法不兼容。

**Comment by dgeibi** [comment]
@951565664 ie 的 debug 我也不会。弄个最小 demo，结合 js 继承的知识分析 babel 生成的代码。

```bash
npm i @babel/cli @babel/core @babel/preset-env @babel/preset-react
```

babelrc:

```json
{
  "presets": [
    [
      "@babel/env",
      {
        "targets": {
          "browsers": "last 2 versions"
        }
      }
    ],
    "@babel/react"
  ]
}
```

package.json:

```json
{
  "scripts": {
    "build": "babel index.js -d dist"
  }
}
```

**Comment by sorrycc** [comment]
这个问题有结论了，先 Close 了。

**Comment by xiaohuoni** [comment]
umi更新1.3.之后
with-dva刚刚使用上面的方法，在加上init补丁，可以在ie上运行，
umi更新1.3
```js
SCRIPT1002: 语法错误 
umi.js, 行57566 字符3
```
我好想reopen！

**Comment by xiaohuoni** [comment]
@951565664 更新umi还有问题吗？

**Comment by wyj580231** [comment]
@dgeibi 试了你这个方法,ie还是打不开啊

**Comment by xiaohuoni** [comment]
@wyj580231  umi 1.3.*这样改后还有其它问题

**Comment by xiaohuoni** [comment]
@sorrycc 
现在的umi-antd-admin 
dev环境  ie10
```js
SCRIPT1002: 语法错误 
umi.dll.js, 行370808 字符1
SCRIPT1002: 语法错误 
umi.js, 行47389 字符3
```
重现项目 https://github.com/umijs/umi-antd-admin

在我们公司的项目中，
umi.dll.js, 缺少‘：’

**Comment by sorrycc** [comment]
调试时不要用 IE 吧。

**Comment by xiaohuoni** [comment]
build之后也不行。（捂脸）

**Comment by xiaohuoni** [comment]
我们项目，升级umi1.3.3 之后，build之后可以了。有问题再reopen

**Comment by wgwxf** [comment]
IE11打不开

SCRIPT1014: 无效字符
umi.js (100629,11)

-->
if (pathname.slice(-1) === '/') {
    ret = `${pathname.slice(0, -1)}/index.js`; // 这行报错？
  } else {
    ret = `${pathname}.js`;
  } // strip the start slash

**Comment by xiaohuoni** [comment]
@wgwxf 
```base
npm i @babel/polyfill setprototypeof --save
```
global.js
```js
import "@babel/polyfill";
import "core-js/fn/array/for-each";
Object.setPrototypeOf = require('setprototypeof')
if (window.NodeList && !NodeList.prototype.forEach) {
  NodeList.prototype.forEach = function(callback, thisArg) {
    thisArg = thisArg || window;
    for (var i = 0; i < this.length; i++) {
      callback.call(thisArg, this[i], i, this);
    }
  };
}
```
这么加，build之后，应该是可用的。你试试

**Comment by 951565664** [comment]
@xiaohuoni 
![image](https://user-images.githubusercontent.com/22285404/40305800-aac9feda-5d2e-11e8-8291-92d51722adbc.png)
按照这个走，再加一个babel-polifill ie ok

**Comment by sorrycc** [comment]
@xiaohuoni 可以搞个 umi-plugin-ie10，自动注入 `@babel/polyfill` 和 `setprototypeof`。

**Comment by xiaohuoni** [comment]
我有打算写一个umi-plugin-polyfill。不止IE的兼容。其实用上动画的话，或者其他东西可能有别的兼容。比如antd-pro里面就用到了url-polyfill。动画可能要添加web animation。react我不太清楚还需不需要别的什么兼容。这几天在看材料。

**Comment by xiaohuoni** [comment]
再出现兼容问题，可以尝试使用umi-plugin-polyfill
```js
export default {
  plugins: [
    "umi-plugin-polyfill"
  ]
};
```
如果还存在其他不兼容的情况，再提ISSUES

**Comment by cokeknight** [comment]
这个问题解决了，因为babel 7针对继承做了改动，原先state = {
      rendering: true,
      isMobile: false,
      menuData: this.getMenuData(),
    }; 这样的属性是直接编译成superClass.call(this,props),而现在是编译成Object.getprototypeof(subClass).call(this);
子类本身是不会指向父函数的，所以原来的继承方式会通过Object.setPrototypeOf的方式显式的把子类的__proto__指向父函数，ie9,10不支持这个属性，却有Object.getprototypeof，需要改造下
if ('__proto__' in {}){
	
} else{
var old =  Object.getPrototypeOf
	Object.getPrototypeOf =  function(param){
			if(param.__proto__){
			return param.__proto__
			} else {
			return old(param)
		}
	}
}
至于Object.setPrototypeOf的模拟参考上面的例子@sorrycc

**Comment by ganxunzou** [comment]
@dgeibi  good !!! 

通过你的方法， 我解决了IE 10中如下报错：
```js
function _classCallCheck(instance, Constructor) {
  if (!(instance instanceof Constructor)) {
    throw new TypeError("Cannot call a class as a function");
  }
}
```
