### ISSUE TITLE
[lessLoader] 如何配置全局less变量文件？

### ISSUE THREAD

**Issue by JustGogoing** [umijs/umi#4131]
umi@3.x
在 .umirc.ts配置后在其他less文件使用变量报错但， 是不是不支持啊？
`  
lessLoader: {
    test: /\.less$/,
    use: ['style-loader', 'css-loader', 'less-loader', 
      {
        loader: 'style-resources-loader',
        options: {
           patterns: path.resolve(__dirname, 'src/assets/mixins.less'),
          injector: 'append'
        }
      }
    ]
  }
`

**Comment by sorrycc** [comment]
通过 lessLoader 配置项配置。

**Comment by JustGogoing** [comment]
> 通过 lessLoader 配置项配置。

就是通过lessLoader配置的，是不是我配置有误啊

`
lessLoader: {
 options: {
      patterns: path.resolve(__dirname, './src/assets/mixins.less'),
      injector: 'append'
    }
 }
或者
lessLoader: {
    test: /\.less$/,
    use: ['style-loader', 'css-loader', 'less-loader',
              { loader: 'style-resources-loader', 
                options: { patterns: path.resolve(__dirname, 'src/assets/mixins.less'), injector: 'append' } } 
        ] 
}
`

**Comment by JustGogoing** [comment]
完成配置 
正确配置如下

`
  lessLoader: {
    module: {
      rules: [
        {
          test: /\.less$/,
          use: ['style-loader', 'css-loader', {
            loader: 'less-loader',
            options: {
              paths: [path.resolve(__dirname, 'src/assets/mixins.less')],
            }
          }]
        }
      ]
    }
  }

`

**Comment by sorrycc** [comment]
options 不要试试。`lessLoader: { patterns: {} }`

**Comment by JustGogoing** [comment]
`
lessLoader: {
    modifyVars: {
      // 或者可以通过 less 文件覆盖（文件路径为绝对路径）
      'hack': `true; @import "~@/assets/mixins.less";`
    }
  }
`

**Comment by IFmiss** [comment]
@JustGogoing 我使用这个方法还是提示 变量为定义 `Variable @main-c is undefined`  还需要做什么其他操作吗

**Comment by IFmiss** [comment]
问题已解决，我变量名称写错了

**Comment by ahwgs** [comment]
> ```
> lessLoader: {
>     modifyVars: {
>       // 或者可以通过 less 文件覆盖（文件路径为绝对路径）
>       'hack': `true; @import "~@/assets/mixins.less";`
>     }
>   }
> ```
我现在这样设置
```
theme:{
 '@brand-primary': '#5B98FF',
},
lessLoader: {
    modifyVars: {
      hack: 'true; @import "~@/styles/index.less";',
    },
  },
```
index.less文件：
```
@import './mixins.less';
@import './themes/default.less';
```
我的`mixins.less`是工具类样式`themes/default.less`是包含`antd-mobile`的主题样式，我用这样的方法全局注入后，会出现`@brand-primary`变量没有符合我预期的效果，还是组件库默认的样式，请问我该如何配置？

**Comment by 17628368021** [comment]
> ```
> lessLoader: {
>     modifyVars: {
>       // 或者可以通过 less 文件覆盖（文件路径为绝对路径）
>       'hack': `true; @import "~@/assets/mixins.less";`
>     }
>   }
> ```

请问hack是什么意思，搜了很多文章也没注明这个hack的意义

**Comment by AkiSong** [comment]
> > ```
> > lessLoader: {
> >     modifyVars: {
> >       // 或者可以通过 less 文件覆盖（文件路径为绝对路径）
> >       'hack': `true; @import "~@/assets/mixins.less";`
> >     }
> >   }
> > ```
> 
> 请问hack是什么意思，搜了很多文章也没注明这个hack的意义

可能没什么意义，只是一个变量名
参考less命令参数
![image](https://github.com/umijs/umi/assets/40135149/81c6ad97-5c07-404c-b885-55bebf13951f)
