### ISSUE TITLE
3.0没有pwa了请问怎么去配置webpack的插件workbox

### ISSUE THREAD

**Issue by jiaozhouzhou** [umijs/umi#4132]
3.0没有pwa了请问怎么去配置webpack的插件workbox，有没有大佬指点一下迷津的

**Comment by jiaozhouzhou** [comment]
就是我在.umirc.ts里怎么配置workbox-webpack-plugin

**Comment by Mr-jiangzhiguo** [comment]
chainWebpack   workbox-webpack-plugin

**Comment by nguyenhuutinh** [comment]
hi @Mr-jiangzhiguo , can you give me more detail how to use this. thanks
