### ISSUE TITLE
umijs/plugin-layout运行时配置rightRender报错

### ISSUE THREAD

**Issue by yxl2628** [umijs/umi#4133]
```javascript
export const layout = {
  logout: () => {
    sessionStorage.clear();
    history.push('/login/');
  },
  iconfontUrl: '//at.alicdn.com/t/font_1684266_ecuk4gq4zml.js',
  rightRender: () =>  (<div>hello</div>)
}
```
看[https://umijs.org/zh-CN/plugins/plugin-layout#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE](https://umijs.org/zh-CN/plugins/plugin-layout#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE)说明，是支持ReactNode返回值的，但是我这么使用的时候，却报错了
```log
/portal/src/app.ts: Unterminated regular expression (19:37)

  17 |   },
  18 |   iconfontUrl: '//at.alicdn.com/t/font_1684266_ecuk4gq4zml.js',
> 19 |   rightRender: () => <div>111111111</div>
     |                                      ^
  20 | }
  21 | 
```

**Comment by yxl2628** [comment]
我知道了，把app.ts改成app.tsx才可以支持ReactNode；

**Comment by qq382724935** [comment]
layout中logout方法通过什么方式触发的呢？

**Comment by tiakia** [comment]
> layout中logout方法通过什么方式触发的呢？

同问  怎么触发layout中的logout方法 @yxl2628

**Comment by tiakia** [comment]
> > layout中logout方法通过什么方式触发的呢？
> 
> 同问 怎么触发layout中的logout方法 @yxl2628

同时配置了`logout`和`rightRender`， logout 会失效

**Comment by Simoon-F** [comment]
有解决方案吗？
