### ISSUE TITLE
[Feature Request] umi 3.0 后期会计划支持react-routerV6m么？v5-v6的迁移指南里来看改动不少

### ISSUE THREAD

**Issue by X-neuron** [umijs/umi#4134]
## Background

 react-router 已经发布v6的bata版了。 改动不少，不少api不兼容。 [...]

## Proposal

 建议自动生成的router 考虑升级到v6版。

**Comment by sorrycc** [comment]
尽量跟，希望能无缝升级。

**Comment by X-neuron** [comment]
> 尽量跟，希望能无缝升级。
@reach/router 好像也可以，实现上，更优美些。 是react router 作者出的 下代router ，没有 向下兼容的包袱。这个对于umi 本身 自带路由无缝 切换可能更自在。但是可能存在react 版本兼容的问题。

**Comment by flyinghail** [comment]
刚看介绍，react-router 6 就是 @reach/router 2，两个项目合并了，目前来说 @reach/router 更接近于新的API。新的 API 也会对 react-router v5 做向后兼容。
