### ISSUE TITLE
昨天更新完umi-build-dev,今天打包失败。提示No matching version found for umi-build-dev@1.17.2.

### ISSUE THREAD

**Issue by cater111** [umijs/umi#4140]

**Comment by sorrycc** [comment]
正常，你用的 npm 源有缓存没同步吧。

```
$ npm info umi-build-dev@1.17.2

dist-tags:
latest: 1.17.2        next: 1.16.12-beta.2
```

**Comment by cater111** [comment]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for umi-build-dev@1.17.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'umi'
npm ERR! notarget 
昨天晚上和上午打包出现这个问题。
但是我用的umi是2.7.2，我看本地umi包里package.json 里umi-build-dev 版本是1.15.1。不知道是什么原因，现在又正常了。可能是因为服务器npm源有缓存没同步吧。
非常感谢了！
