### ISSUE TITLE
router.push 相同的 地址 界面不能重新加载数据

### ISSUE THREAD

**Issue by xgj1988** [umijs/umi#4144]
我当前的地址为：
http://localhost:8000/system/member/update/1

我用router.push('/system/member/update/2')
也就是加载ID为2的数据。。
但是界面没变，。也没请求后端数据。。但是地址栏变成了 /system/member/update/2。。
但是内容还是1 的。。

**Comment by xgj1988** [comment]
路由是这样设置的。   
{
            path: "/system/member/update/:id",
            name: "修改用户",
            component: "./System/Member/MemberInfo"
          },

**Comment by RusseII** [comment]
I'm. having the same issue

**Comment by symbiot-india** [comment]
I am facing the same issue since yesterday's build. Only the URL changes, but the new component is not rendered. How do I fix it?

**Comment by zhangyoof** [comment]
我也遇到了同样的问题

**Comment by xgj1988** [comment]
i had solved it .  use  componentWillReceiveProps method ,when the id of query.param ,call the  remote load data function

**Comment by xiaohuoni** [comment]
应该是你的请求发起时机不对，动态路由共用一个组件。

**Comment by symbiot-india** [comment]
Yesterday, I ran the heroku build again. It suddenly started working again. I have made no changes to the codebase. Weird.

**Comment by sorrycc** [comment]
https://github.com/umijs/umi/issues/4159

**Comment by zhanchengkun** [comment]
同题

**Comment by xiaohuoni** [comment]
Fixed via umi@2.13.7.
