### ISSUE TITLE
约定式model，当使用pages/bar/model.ts方式配置时，报错

### ISSUE THREAD

**Issue by Jude-summery** [umijs/umi#4152]
## What happens?

当使用约定式路由时，以`pages/bar/model.ts`方式配置，dva.ts内生成的`app.model({ namespace: ...})`中`namespace `属性固定为`model`而并不是在model.ts中指定的`namespace`

## How To Reproduce
```
// pages/Login/model.ts
const Login = {
  namespace: 'Login',
  state: {
    name: ''
  }
}

export default Login

// .uim/plugin-dva/dva.ts
// 自动生成的代码为
app.model({ namespace: 'model', ...(require('***/src/pages/Login/model.ts').default) });
```

## Context

- **Umi Version**: 3.0.7
- **Node Version**: 12.14.1

**Comment by sorrycc** [comment]
```
app.model({ namespace: 'model', ...(require('***/src/pages/Login/model.ts').default) });
```

从这段来看，`src/pages/Login/model.ts` 的 namespace 会覆盖前面的。

**Comment by Jude-summery** [comment]
> ```
> app.model({ namespace: 'model', ...(require('***/src/pages/Login/model.ts').default) });
> ```
> 
> 从这段来看，`src/pages/Login/model.ts` 的 namespace 会覆盖前面的。
嗯嗯 后面看到报错的原因是因为 model里没写state，并不是因为没注册model

**Comment by guangming21** [comment]
这个怎么解决的

**Comment by guangming21** [comment]
> > ```
> > app.model({ namespace: 'model', ...(require('***/src/pages/Login/model.ts').default) });
> > ```
> > 
> > 
> > 从这段来看，`src/pages/Login/model.ts` 的 namespace 会覆盖前面的。
> 
> 嗯嗯 后面看到报错的原因是因为 model里没写state，并不是因为没注册model

怎么解决的

**Comment by Jude-summery** [comment]
> > > ```
> > > app.model({ namespace: 'model', ...(require('***/src/pages/Login/model.ts').default) });
> > > ```
> > > 
> > > 
> > > 从这段来看，`src/pages/Login/model.ts` 的 namespace 会覆盖前面的。
> > 
> > 
> > 嗯嗯 后面看到报错的原因是因为 model里没写state，并不是因为没注册model
> 
> 怎么解决的

model里有state属性，就不会报这个错了
