### ISSUE TITLE
初始化项目失败 yarn create @umijs/umi-app

### ISSUE THREAD

**Issue by Mrzouning** [umijs/umi#4153]
当初始化项目时， 报$ yarn create @umijs/umi-app
yarn create v1.22.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "http://registry.npm.taobao.org/flatmap-stream/download/flatmap-stream-0.1.0.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug,

**Comment by xiaohuoni** [comment]
重试一下，我试了是可以用的。

**Comment by sorrycc** [comment]
本地网络问题。

**Comment by delapecci** [comment]
```
cd ~/.config/yarn/global
rm -rf ./node_modules/flatmap-stream ./node_modules/event-stream
rm yarn.lock
```
重新执行
