### ISSUE TITLE
动态路由开启dynamicImport 打包问题

### ISSUE THREAD

**Issue by LeoHuiyi** [umijs/umi#4155]
开启dynamicImport，
动态路由路径中有[id]打包出来会有问题  
![image](https://user-images.githubusercontent.com/8001457/76681640-34e35b00-6630-11ea-91d6-4fe98133b078.png)
。webpack好像把他作为魔法字符串了去替换了
![image](https://user-images.githubusercontent.com/8001457/76681537-f5683f00-662e-11ea-89b2-30408adc2343.png)

**Comment by sorrycc** [comment]
复现不了，给可复现的仓库。

**Comment by LeoHuiyi** [comment]
[umi-test.rar.zip](https://github.com/umijs/umi/files/4359268/umi-test.rar.zip)
yarn install 
npm run build
