### ISSUE TITLE
umi不能使用react-devtools来调试吗

### ISSUE THREAD

**Issue by wingever** [umijs/umi#4156]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by wingever** [comment]
用什么工具可以在chrom里面像react-devtools一样查看组件结构的吗

**Comment by sorrycc** [comment]
试过，可以。
