### ISSUE TITLE
router.push后，地址栏变了，但是页面并没有变

### ISSUE THREAD

**Issue by zhangyoof** [umijs/umi#4159]
import router from ‘umi/router’
*****
router.push("/home")
******
操作后this.props.children.props.location.pathname  还是上一个路由的名称，没有变

- **Umi Version**:2.13.6
- **Node Version**:12.14.1
- **Platform**:Windows 10

**Comment by xiaohuoni** [comment]
怎么重现？给一个重现demo

**Comment by sorrycc** [comment]
https://github.com/umijs/umi/issues/4159

**Comment by sorrycc** [comment]
在 umi@2.13.7 里修复了。
