### ISSUE TITLE
使用了document.ejs的情况下浏览器端会报错

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#4165]
![image](https://user-images.githubusercontent.com/7939085/76726355-d59a5d80-678b-11ea-92c4-6a5ab6ba7c7b.png)
如图，使用了document.ejs模板的情况下，会报这个错，虽然不影响使用 但是看着特别不爽
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**： ^3.0.8
- **Node 版本**：v10.16.0
- **操作系统**：windows 10

**Comment by sorrycc** [comment]
browser.js 是哪里引的？给复现吧。

**Comment by xiexingen** [comment]
> browser.js 是哪里引的？给复现吧。

知道问题出在哪了，之前的document.ejs里面使用这种形式引用了public里面的js文件
<script src="<%= context.publicPath %>upgrade/browser.js" type="text/javascript"></script>
升到umi3后 ，通过<%= context.publicPath %>取到的是''空字符串  所以导致的

**Comment by xiexingen** [comment]
> browser.js 是哪里引的？给复现吧。

知道问题出在哪了，之前的document.ejs里面使用这种形式引用了public里面的js文件
<script src="<%= context.publicPath %>upgrade/browser.js" type="text/javascript"></script>
升到umi3后 ，通过<%= context.publicPath %>取到的是''空字符串  所以导致的

**Comment by xiexingen** [comment]
context.publicPath是算有点小bug还是我用法有问题，context.publicPath默认不应该是'/'嘛 怎么会是‘’

**Comment by sorrycc** [comment]
upgrade/browser.js 怎么放的？没有放 public 目录下吗？

**Comment by xiexingen** [comment]
> upgrade/browser.js 怎么放的？没有放 public 目录下吗？

upgrade/browser.js 这个路径在的
![image](https://user-images.githubusercontent.com/7939085/76812266-4a72a380-682f-11ea-8599-72cc5e4e4903.png)
我现在发现的问题是
![image](https://user-images.githubusercontent.com/7939085/76812418-bce38380-682f-11ea-9c7c-0289103744ca.png)
![image](https://user-images.githubusercontent.com/7939085/76812440-cec52680-682f-11ea-8a3d-68db10e154fb.png)
