### ISSUE TITLE
umi 3.08 userequest 

### ISSUE THREAD

**Issue by fangaofeng** [umijs/umi#4167]
## What happens?

import { Link, request ,useRequest} from 'umi';

...
const { data, error, loading } = useRequest({
  url: '/api/changeUsername',
  method: 'post',
});
throw error:
react-dom.development.js:22157 Error: url MUST be a string

if write:
**import { useRequest } from '@umijs/hooks';**
const { data, error, loading } = useRequest({
  url: '/api/changeUsername',
  method: 'post',});
it work.

- **Umi Version**: 3.0.8
- **Node Version**:10.15.0
- **Platform**: win10

**Comment by sorrycc** [comment]
在 https://github.com/umijs/plugins/pull/97 修复，今天更新。
