### ISSUE TITLE
建议access插件当子菜单都没有权限的时候是不是应该默认隐藏父菜单项

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#4171]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by Ariel-Cheng** [comment]
现在的交互应该是，如果没有权限的话，layout 提供默认的没有权限的 UI。

是期望可以
1.  没有权限就同时隐藏侧边栏的入口，如果所有子菜单都隐藏，父菜单也隐藏
2. 同时别人分享一个没有权限的链接时，打开依旧是默认的没有权限的默认 UI

吗？

**Comment by xiexingen** [comment]
> 现在的交互应该是，如果没有权限的话，layout 提供默认的没有权限的 UI。
> 
> 是期望可以
> 
> 1. 没有权限就同时隐藏侧边栏的入口，如果所有子菜单都隐藏，父菜单也隐藏
> 2. 同时别人分享一个没有权限的链接时，打开依旧是默认的没有权限的默认 UI
> 
> 吗？

是这个意思，目前发现的是 当菜单下的所有子菜单都没权限了 菜单项还是显示的

**Comment by salody** [comment]
我觉得也是应该是这个交互逻辑。在没有权限的情况下，子路由的sidebar的menuItem应该是不显示出来的，而不是现在的点击这个路由，显示出一个没有权限的页面

**Comment by wtzeng1** [comment]
已提交 PR 进行处理，当子路由存在并且所有子路由不可访问时，父路由也将不可访问

[105](https://github.com/umijs/plugins/pull/105)
