### ISSUE TITLE
修改了 css 文件,自动刷新了浏览器

### ISSUE THREAD

**Issue by MyCupOfTeaOo** [umijs/umi#4174]
## What happens?

启动了css module后,修改了 scss 文件,自动刷新了浏览器,目前有办法解决这个缺陷吗

## 最小可复现仓库

git@github.com:MyCupOfTeaOo/umi-css-reload.git

修改 index.less 会刷新浏览器,因为启用了 css module,修改 index2.less 不会刷新浏览器,因为没有使用 css module

## 相关环境信息

- **Umi 版本**：umi@3.0.8
- **Node 版本**：v12.9.1
- **操作系统**：windows 10

**Comment by sorrycc** [comment]
仓库空的。

**Comment by MyCupOfTeaOo** [comment]
> 仓库空的。

不好意思,刚提交上去了,大佬佬

**Comment by sorrycc** [comment]
![4](https://user-images.githubusercontent.com/35128/76810995-ff569180-682a-11ea-8291-5cff88eb1d22.gif)
mac 下没能复现。

**Comment by MyCupOfTeaOo** [comment]
> ![4](https://user-images.githubusercontent.com/35128/76810995-ff569180-682a-11ea-8291-5cff88eb1d22.gif)
> mac 下没能复现。

看来只是在win环境会有这个问题QAQ
