### ISSUE TITLE
插件useRequest方法报错

### ISSUE THREAD

**Issue by afocus** [umijs/umi#4176]
## What happens?

使用useRequest时报错  `Uncaught Error: url MUST be a string`

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

```javascript

import { useRequest, request } from 'umi';

export default function(){
    // const { ecsData, err, loading } = useRequest(request.get('/api/ecs'));
    const { ecsData, err, loading } = useRequest(
        request('/api/ecs', { method: 'get' }),
     );
     ....
}

```

## 相关环境信息

- **Umi 版本**：3.0.7
- **Node 版本**：v12.13.0
- **操作系统**：windows10

**Comment by sorrycc** [comment]
在 https://github.com/umijs/plugins/pull/97 修复，今天更新。
