### ISSUE TITLE
@umijs/plugin-layout menu项文档描述跟实际情况不符

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#4179]
menu
Type: false | IRouteMenuConfig
Default: false
SideMenu 相关配置。默认为 false，表示在菜单中隐藏此项包括子项。
根据描述项，如果menu配置为false，那么菜单中应该隐藏该项
![image](https://user-images.githubusercontent.com/7939085/76758295-5e34f000-67c4-11ea-8e89-560ad7ec592a.png)
.umi/core/routes中生成的内容是这样的，但是实际页面上 这个菜单项还是出来了(除非没有name)

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**： ^3.0.8
- **Node 版本**：v10.16.0
- **操作系统**：windows 10

**Comment by Ariel-Cheng** [comment]
这里的表述可能有点问题，默认是 false ，但是兼容 name 平铺配置在 routeItem 中的写法，所以这种情况下，等同于设置了 menu。
所以如果有需要同时配置 name & 隐藏 menu 的需求，仍需显示配置 menu：false

**Comment by xiexingen** [comment]
知道了，谢谢；这个是不是可以更新到文档里面去，避免另外的人采坑
