### ISSUE TITLE
一个简单的modal page gallery的umi插件

### ISSUE THREAD

**Issue by JiangWeixian** [umijs/umi#4180]
https://github.com/JiangWeixian/umi-advanced-routes-generator

![pro-routes](https://raw.githubusercontent.com/JiangWeixian/umi-advanced-routes-generator/master/screenshots/pro-routes.gif?token=ABUF2GFF2H2WFWQGEA3ZWAC6N5ZSW)

**Comment by sorrycc** [comment]
👍，可以找时间适配到 umi 3。
