### ISSUE TITLE
[plugin-request] showType: 0 无法关闭请求失败/错误的提示

### ISSUE THREAD

**Issue by daolou** [umijs/umi#4181]
## What happens?
目的：关闭请求失败/错误的（message）提示
实现：
```ts
// /app.tsx
export const request: RequestConfig = {
  timeout: 1000,
  errorConfig: {
    adaptor: resData => {
      return {
        ...resData,
        showType: ErrorShowType.SILENT,
      };
    },
  },
  middlewares: [],
};
```
![屏幕录制2020-03-1620 50 36](https://user-images.githubusercontent.com/22312092/76760325-668f2a00-67c8-11ea-911e-c401c70610dc.gif)

## Mini Showcase Repository(REQUIRED)

 repo: <https://github.com/Mr-jiangzhiguo/repo-bugs>

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.0.8
- **Node Version**: 10.15.3
- **Platform**: mac

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.

**Comment by blake-coconut** [comment]
这个问题有解决吗？我也有遇到同样的问题

**Comment by zjxpcyc** [comment]
同问，怎么解决

**Comment by zjxpcyc** [comment]
找到原因了，我这边是在写 `response` 拦截器的时候, 有个地方的 返回值错误
