### ISSUE TITLE
bug(history): umi+dva router.push 不能正常导航

### ISSUE THREAD

**Issue by junhwong** [umijs/umi#4183]
## What happens?

项目是基于antd pro 的，重新 npm install 后 路由全挂了(菜单除外)，现在也有很多人出现同样的问题。
config/config.js
改成 history: 'hash' 可以导航，使用 browser 无效。
初步看是 router.push 的问题，是老项目也不好做umi升级

相关问题如：
https://github.com/umijs/umi/issues/4144
https://github.com/umijs/umi/issues/4159
https://github.com/umijs/umi/pull/4162

## 相关环境信息

- **Umi 版本**：2.13.6
- **Node 版本**：v13.11.0
- **操作系统**：linux

**Comment by junhwong** [comment]
目前，改成 "umi": "2.13.4" 版本可用

**Comment by sorrycc** [comment]
Fixed via umi@2.13.7.
