### ISSUE TITLE
.umirc.js 会执行两次

### ISSUE THREAD

**Issue by ithack** [umijs/umi#4185]
.umirc.js文件带吗如下：

```
import { defineConfig } from 'umi';
console.log("=============")
console.log(process.env.ENV)
console.log("=============")
export default defineConfig({
  outputPath: process.env.ENV === "test" ? "pre_dist":"dist",
  publicPath: "./",
  history: {
    type: 'hash'
  }
});
```

![image](https://user-images.githubusercontent.com/4329193/76826118-95ec7800-6856-11ea-9744-7144d492e194.png)

## 相关环境信息

- **Umi 版本**：3.0
- **Node 版本**：12.13.0
- **操作系统**：Mac

**Comment by sorrycc** [comment]
会有啥问题？配置会读好几次的。

**Comment by xiaohuoni** [comment]
感觉是同一个问题 https://github.com/umijs/umi/issues/4093
