### ISSUE TITLE
升级到 umi 3，提示 invalid key dva from plugin 

### ISSUE THREAD

**Issue by solobat** [umijs/umi#4188]
## What happens?

按照迁移文档从 umi2 升到 umi3 以后，执行 umi dev 正常启动，没有报错，但页面无法正常访问，提示如图：
![image](https://user-images.githubusercontent.com/1894203/76829731-cd5f2280-685e-11ea-97c8-07cf26418311.png)

## 最小可复现仓库
以下是我的 .umirc.js 配置
![image](https://user-images.githubusercontent.com/1894203/76829788-eff13b80-685e-11ea-8a29-f72bbe94e9a6.png)

## 相关环境信息

- **Umi 版本**：3.0.9
   - **@umijs/preset-react**: 1.4.3
- **Node 版本**：v11.10.1
- **操作系统**：MacOS 10.14
- **package.json**:
![image](https://user-images.githubusercontent.com/1894203/76830571-75c1b680-6860-11ea-8bd0-01168184a5c5.png)

**Comment by sorrycc** [comment]
给复现仓库，示例看不出来。

**Comment by solobat** [comment]
解决了，model 不识别导致的，修改下 .umirc.js 配置就好了
```
dva: { skipModelValidate: true }
```

**Comment by maquannene** [comment]
我尝试 dva: { skipModelValidate: true } 也是不好使的。我是在 config/config.ts 里面设置的配置；
最后解决方式是增加 modal/xxmodal.ts，随便能加一个 dva modal 就可以运行了；
`
const initState = {};

export default {
  namespace: 'user',
  state: initState
};
`

吐槽一下，不知道为什么有这么隐含的规则，着实有点蛋疼。

**Comment by kokiy** [comment]
@maquannene 
![image](https://user-images.githubusercontent.com/15773714/107190157-6eca0680-6a25-11eb-8382-8570bbb77f56.png)

**Comment by maquannene** [comment]
@kokiy 
这个并不代表，dva 必须要写 model 文件。只是描述了 model 的使用规则。
