### ISSUE TITLE
Umi Model 目录下测试文件会被引入 dva 模型

### ISSUE THREAD

**Issue by arvinxx** [umijs/umi#419]
测试文件路径 pages/**/models/xxx.test.js
该文件会被自动引入 Model 中造成报错。
![default](https://user-images.githubusercontent.com/28616219/39580595-120c32f0-4f1c-11e8-9f9b-615996369016.png)

**Comment by xiaohuoni** [comment]
['umi-plugin-dva', {
      exclude: [
        /^\$/,
      /.test\.(j|t)sx?$/
      ],
    }],
