### ISSUE TITLE
使用 yarn lint:tsc 检测时，会检测 src/.umi 文件中的内容并报错

### ISSUE THREAD

**Issue by BBBigCat** [umijs/umi#4194]
## What happens?

将配置写在 **config** 文件后，使用 `yarn lint:tsc` 检测时，会检测到 `src/.umi` 文件中的内容并报错，在 `tsconfig.json` 中设置 `exlude` 无效，

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

最小复现仓库
[myapp](https://github.com/BBBigCat/myapp)

## 复现步骤，错误日志以及相关配置
1.  `package.json` 中 `script` 配置 `lint:tsc": "tsc -p tsconfig.json --noEmit`
2. 将配置写在 `config` 文件夹里
3. 执行 `yarn lint:tsc`，会检测到 src/.umi 文件中的内容并报错

![image](https://user-images.githubusercontent.com/31910599/76844405-30a97e80-6878-11ea-859c-a5c1cf69271e.png)

## 相关环境信息

- **Umi 版本**：3.0.9
- **Node 版本**：10.16.0
- **操作系统**：macOS 10.15.3

**Comment by sorrycc** [comment]
ts 问题会统一找时间修复。

**Comment by BBBigCat** [comment]
是哪里的原因呢

**Comment by BBBigCat** [comment]
> ts 问题会统一找时间修复。

是哪里的问题呢

**Comment by sorrycc** [comment]
相关 PR：

* https://github.com/umijs/umi/pull/4206
* https://github.com/umijs/plugins/pull/112

**Comment by MinJieLiu** [comment]
https://github.com/umijs/umi/issues/4097

**Comment by sorrycc** [comment]
Fixed in https://github.com/umijs/umi/commit/ce005fc759531f7795b8dba34b0827dd8148abfa
