### ISSUE TITLE
[Feature Request] 强烈建议Umi将主体和Umi UI部分分离

### ISSUE THREAD

**Issue by joesdu** [umijs/umi#4198]
## Background

强烈建议Umi将主体和Umi UI部分分离,并不是每个人都需要Umi UI,建议将UI做成插件的形式.由于UI的兼容性导致项目升级缓慢.并且由于UI导致项目启动时间较长.

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by sorrycc** [comment]
Umi 3 分离了。

**Comment by joesdu** [comment]
> Umi 3 分离了。

刚看了3的文档,才发现.不好意思😁

**Comment by ycjcl868** [comment]
https://github.com/umijs/umi-ui
