### ISSUE TITLE
umi3 配置式路由后缀打包报错

### ISSUE THREAD

**Issue by INTMIN** [umijs/umi#4201]
## What happens?

在umi3版本上，配置式路由添加 path 为  类似/detail/:id时，编译报错，start是可以启动的
![image](https://user-images.githubusercontent.com/30612388/76933328-d49e3300-6927-11ea-85d1-21c2bc56fb40.png)

## 暂时的解决方式

path改为/detail/时build打包成功

## Context

- **Umi Version**:3.0.10
- **Node Version**:12.14.1
- **Platform**:windows10

**Comment by LeoHuiyi** [comment]
和我那个bug一样 #4155  配置路由中不能有[id] 字段不然开启 dynamicImport和hash 打包会有问题，看了下源码 好像是webpack把[id]这个作为魔法字符串去替换路径了

**Comment by LeoHuiyi** [comment]
我这边测试发现 引入webpack/lib/NamedChunksPlugin 这个插件会出问题  
```
{
    dynamicImport: {},
    hash: true,
    chainWebpack(webpackConfig) {
        webpackConfig.plugin('named-chunks').use(require('webpack/lib/NamedChunksPlugin')).end()
    },
}

加入/page/[id].index.js
```
umi build 报错

**Comment by sorrycc** [comment]
@INTMIN 给可复现的仓库，我复现不了。

**Comment by INTMIN** [comment]
@sorrycc 我整理下

**Comment by INTMIN** [comment]
@sorrycc https://github.com/INTMIN/umiRouterBug.git

**Comment by sorrycc** [comment]
不能复现。

![image](https://user-images.githubusercontent.com/35128/77074653-1d3f1480-6a2c-11ea-9a6a-4e96838dde51.png)

**Comment by INTMIN** [comment]
@sorrycc 你的lock文件能给我下吗

**Comment by sorrycc** [comment]
[yarn.lock.zip](https://github.com/umijs/umi/files/4354994/yarn.lock.zip)

**Comment by INTMIN** [comment]
@sorrycc 大佬你的lock里所有的依赖都是  https://registry.yarnpkg.com 源的
![image](https://user-images.githubusercontent.com/30612388/77077559-57aab080-6a30-11ea-970d-2c9a55ad0d28.png)
我需要把源换掉吗

**Comment by INTMIN** [comment]
导致很多版本不一致

**Comment by INTMIN** [comment]
我本地是淘宝镜像

**Comment by INTMIN** [comment]
@sorrycc 升级3.0.16后打包出现polyfill的一片报错，后测试了很多次，最后加上这个   
`polyfill: {
    imports: [
      'core-js/stable',
    ]
  }
`
打包就成功了，之前加   /:id  的就可以打包成功了

**Comment by sorrycc** [comment]
有复现再 reopen。

**Comment by INTMIN** [comment]
好的
