### ISSUE TITLE
umi3.0升级后自己写的插件使用后报错

### ISSUE THREAD

**Issue by cassiewang01** [umijs/umi#4202]
自己写的插件使用报错，提示：api.register() failed, hook.fn must supplied and should be function, but got undefined.

插件全部代码：
`export default function(api, options) {
  api.addEntryImports({
    source: 'a',
    specifier: '{b}',
  });

  const setSpmPageCode = `c`;
  api.addEntryCodeAhead(setSpmPageCode);

  const listener = `d`;
  api.addEntryCode(listener);
}
`
## 相关环境信息

- **Umi 版本**：^3.0.7
- **Node 版本**：v10.16.2
- **操作系统**：mac

**Comment by sorrycc** [comment]
参考以下文档升级插件，

* https://umijs.org/plugins/api
* https://github.com/umijs/umi-next/wiki/Migrate-Plugins-to-Umi-3
