### ISSUE TITLE
UMI3顶层用了rudex封装

### ISSUE THREAD

**Issue by ithack** [umijs/umi#4205]
![image](https://user-images.githubusercontent.com/4329193/76948267-dc6ad100-6941-11ea-8b4d-a2ca100e2e4a.png)
![image](https://user-images.githubusercontent.com/4329193/76948357-f1476480-6941-11ea-8909-97563bfc9ea4.png)

## Context

- **Umi Version**: 3.0.7
- **Node Version**: 12.11.0
- **Platform**: Mac

**Comment by sorrycc** [comment]
Umi 没有内置 redux，应该是开了啥插件吧。问题是啥？

**Comment by ithack** [comment]
> x，应该是开了啥插件吧。问题是啥？这个 Provider 哪来的吗

我并没有用dva和plugin-initial-state这个插件，为了代码的客观性，不知有没有办法关掉外层的Provider

**Comment by sorrycc** [comment]
配置 initialState: false

**Comment by ithack** [comment]
> 你应该是配了 preset-react，可能由于某些原因 plugin-initial-state 被无开启了，可配置 initialState: false 关闭试试。

谢谢，已经找到查找关闭插件相关方法非常实用分享一下：
首先用` umi plugin list --key` 查找安装（包裹默认安装）的插件和相应的key，然后在.umirc.ts里通过key配置相关插件；如下：
```
……
initialState: false,
dva: false,
model: false,
……
如上关闭不想用的插件
```
