### ISSUE TITLE
umi-plugin-qiankun的生产环境配置在哪里

### ISSUE THREAD

**Issue by rodchen-king** [umijs/umi#4207]
## What happens?

umi-plugin-qiankun的生产环境配置在哪里，找不到

**Comment by sorrycc** [comment]
@kuitos

**Comment by kuitos** [comment]
插件配置不区分环境

**Comment by rodchen-king** [comment]
> 插件配置不区分环境

我的表述有问题，想问一下，ant design pro微前端的生产环境配置在哪里找得到文档？

**Comment by rodchen-king** [comment]
> > 插件配置不区分环境
> 
> 我的表述有问题，想问一下，ant design pro微前端的生产环境配置在哪里找得到文档？

@kuitos
