### ISSUE TITLE
无法开启devtool

### ISSUE THREAD

**Issue by LeoHuiyi** [umijs/umi#4210]
## What happens?

production环境，无法开启devtool

## How To Reproduce

devtool: 'source-map'
![image](https://user-images.githubusercontent.com/8001457/77026499-c0614100-69ce-11ea-833a-53517936636d.png)

- **Umi Version**:3.0.10
- **Node Version**:12.13.1
- **Platform**:windows10

**Comment by fangaofeng** [comment]
我配置了也是无法开启，版本3.0.10.提示内存不够，我有32g内存。
