### ISSUE TITLE
配置把history:'browser' 路由模式在本地开发环境还是hash路由

### ISSUE THREAD

**Issue by LeoWang1991** [umijs/umi#4211]
antd pro脚手架，配置把history:'browser' 路由模式在本地开发环境还是hash路由

umi版本：^2.8.7。

但是打包后部署到线上是正常的browser模式，这是为什么？是哪里没有配置好么

**Comment by LeoWang1991** [comment]
emmm 这个问题出现在antd pro2.1.0，如果把配置文件config.js中的dll部分注释掉
```javascript
...(!process.env.TEST && os.platform() === 'darwin'
          ? {
              dll: {
                include: ['dva', 'dva/router', 'dva/saga', 'dva/fetch'],
                exclude: ['@babel/runtime'],
              },
              // hardSource: true,
            }
          : {}),
```
就没这个问题对比了下antd pro2.3.1就没这个问题，发现两者唯一的区别就是dva的版本，有问题的dva版本是2.4.0，antd pro2.3.1中的dva版本是2.4.1。翻了下dva的[release](https://github.com/dvajs/dva/releases/tag/dva%402.4.1) 大概应该就是这个问题引起的吧，升级dva到2.4.1解决了问题。

**Comment by LeoWang1991** [comment]
我从history:'browser'改成 `hash`但是本地还是没有变化 不清楚是否是因为`[umi-plugin-dll] File list is equal, don't generate the dll file` 的原因，把这个dll优化去掉的话，改history重新编译跑起来就没有问题。

**Comment by sorrycc** [comment]
那就是 dll 的问题了。
