### ISSUE TITLE
解决跨域问题时需修改的.umirc.js文件没有

### ISSUE THREAD

**Issue by kinsenxu** [umijs/umi#4212]
## What happens?
遇到跨域问题查看资料时说要在.umirc.js中添加proxy，但在项目文件中找不到.umirc.js，请问是版本升级了该文件没有了吗？
<img width="490" alt="屏幕快照 2020-03-19 上午11 39 28" src="https://user-images.githubusercontent.com/31841297/77029800-ad9f3a00-69d7-11ea-83ea-e3d212e15e0d.png">

- **Umi Version**:2.11.1

**Comment by snice** [comment]
请参考文档 https://v2.umijs.org/zh/config/#proxy
