### ISSUE TITLE
[Feature Request] dynamicImport 打包时文件名太长

### ISSUE THREAD

**Issue by ue360** [umijs/umi#4213]
生成的文件名好长

![image](https://user-images.githubusercontent.com/367891/77049802-b4dc3d00-6a03-11ea-9573-1d2af3427360.png)

**Comment by leftstick** [comment]
你列出的这几个文件都有 hash 啊，所以问题其实是文件名太长？

**Comment by kelvin1984** [comment]
我记得2.x，dynamicImport为true时，默认就是[id]，随机文件名，现在3.x，webpackChunkName配置项好像没有了

**Comment by somychfudewe** [comment]
```ts
chainWebpack(config) {
  config.output.chunkFilename(`[name].[contenthash:8].async.js`);
  config.output.filename(`[name].[contenthash:8].js`);
}
```
即使这样，也是无法修改过长的文件名。

**Comment by kilingzhang** [comment]
官方大大这个Feature未来会有计划吗

**Comment by zhaoxuhui1122** [comment]
试试下面这种方式
```ts
config.output.set('chunkFilename','[id].[contenthash:8].js');
```

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.

**Comment by umlink** [comment]
还没修复吗
