### ISSUE TITLE
umi 3.0.11 执行 npm create umi 报错

### ISSUE THREAD

**Issue by hnxyhcz** [umijs/umi#4214]
## What happens?

执行 npm create umi 报错，是不是 clipboardy 2.3.0版本的问题？
![image](https://user-images.githubusercontent.com/10190358/77065369-20320900-6a1c-11ea-95cb-4ca1664feced.png)

## How To Reproduce

1. mkdir my-app

2. cd my-app

3. npm create umi

## Context

- **Umi Version**: 3.0.11
- **Node Version**: 13.1.0
- **Platform**: win10

**Comment by sorrycc** [comment]
```bash
$ npm create @umijs/umi-app
```

**Comment by hnxyhcz** [comment]
不好意思，才看到umi3的文档才看到umi3的文档  ￣□￣｜｜
