### ISSUE TITLE
yarn create umi创建的新应用的依赖版本低，怎么升级？

### ISSUE THREAD

**Issue by fengnex** [umijs/umi#4216]
例如antd已经发布了4.0.3正式版，但是创建的工程却还在使用rc版本，如下：
## What happens?

`"dependencies": {
    "@ant-design/icons": "^4.0.0-alpha.19",
    "@ant-design/pro-layout": "^5.0.0",
    "@ant-design/pro-table": "^2.0.0",
    "@antv/data-set": "^0.11.1",
    "antd": "^4.0.0-rc.1",
    "classnames": "^2.2.6",
    "dva": "^2.6.0-beta.16",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "omit.js": "^1.0.2",
    "path-to-regexp": "2.4.0",
    "qs": "^6.9.0",
    "react": "^16.8.6",
    "react-copy-to-clipboard": "^5.0.1",
    "react-dom": "^16.8.6",
    "react-helmet": "^5.2.1",
    "redux": "^4.0.1",
    "umi": "^2.13.0",
    "umi-plugin-antd-icon-config": "^1.0.2",
    "umi-plugin-antd-theme": "1.2.0-0",
    "umi-plugin-pro-block": "^1.3.2",
    "umi-plugin-react": "^1.14.10",
    "umi-request": "^1.0.8",
    "use-merge-value": "^1.0.1"
  },`

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

1、执行yarn create umi app_name
2、中途选创建antd pro、javascript
3、检查package.json中上一部生成的新应用的依赖

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：
[root@localhost projects]# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
[root@localhost projects]# node -v
v12.16.1
[root@localhost projects]# npm -v
6.14.2
[root@localhost ant319]# umi -v
umi@3.0.11

**Comment by sorrycc** [comment]
yarn create @umijs/umi-app
