### ISSUE TITLE
[Feature Request] 期望可以支持 应用程序模块化 开发

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#4218]
## Background
先上图
![image](https://user-images.githubusercontent.com/7939085/77128424-0976cb00-6a8b-11ea-987b-8e5746f3d994.png)
![image](https://user-images.githubusercontent.com/7939085/77129130-c10cdc80-6a8d-11ea-99cc-1d99b9dad1e4.png)

## 说明
子应用模块 ：包含页面、路由、菜单定义的子模块()  
宿主应用:相当于提供一个启动的壳，在宿主应用中引入和使用各种子应用模块
##
目的是可以达到这样，开发了多个子应用模块 
比如:博客模块、技术文档模块、权限管理模块
这些模块会打包成单独的npm包，然后在宿主应用中想要一个博客模块就安装过来，然后再路由中导入博客模块的路由；

## Proposal
望各位大佬给点意见或者思路

**Comment by dkvirus** [comment]
你要的模块化 [demo](https://github.com/dkvirus/umi-module-demo)
