### ISSUE TITLE
问题：升级到 umi@3 之后使用导出的 connect 代码不报错，运行报错

### ISSUE THREAD

**Issue by yanglwr** [umijs/umi#4222]
1.问题
在 antd pro 中升级了 umi@3 使用 connect 时代码不报错，运行时错误 TypeError: Object(...) is not a function
2.截图 
![image](https://user-images.githubusercontent.com/32095100/77146059-16181500-6ac5-11ea-996f-15f27eb895c8.png)
![image](https://user-images.githubusercontent.com/32095100/77146094-334ce380-6ac5-11ea-8d19-ac7a6f88f531.png)
![image](https://user-images.githubusercontent.com/32095100/77146123-49f33a80-6ac5-11ea-9ba4-632a2784adde.png)

请问这是哪里的问题，希望能得到帮助

**Comment by sorrycc** [comment]
官网搜 plugin-dva，下面有方案，先试试。

**Comment by yanglwr** [comment]
> 官网搜 plugin-dva，下面有方案，先试试。

![image](https://user-images.githubusercontent.com/32095100/77149148-e7ea0380-6acb-11ea-999f-de133eb316de.png)

之前已经尝试过官网上提出来的方案了，umi 文件是存在的

**Comment by sorrycc** [comment]
给复现。

**Comment by feibi** [comment]
有最小复现例子嘛，我本地也遇到了

**Comment by feibi** [comment]
![image](https://user-images.githubusercontent.com/16058286/77169280-33180c80-6af4-11ea-9b0a-2816fba97db0.png)

**Comment by feibi** [comment]
检查下项目是不是和#4235问题一样

**Comment by yanglwr** [comment]
> 检查下项目是不是和 #4235 问题一样

是的，问题类似

**Comment by bijinfeng** [comment]
请问如何解决这个问题的

**Comment by yanglwr** [comment]
> 请问如何解决这个问题的

发现可能是文件目录的问题，目录过深就会复现，最快速的解决方法项目引入 react-redux ，connect 从这个包引入

**Comment by EdifierCN** [comment]
我的原因是在connect()(A)，但是model中导入了一个A中方法，2.x 没问题，3.x会出错

**Comment by lyuns** [comment]
遇到了同样的问题，import { connect } from "react-redux" + 升级 dva@2.6.0-beta.19 得到了解决

**Comment by jackchoumine** [comment]
> 遇到了同样的问题，import {connect} from "react-redux" + 升级 dva@2.6.0-beta.19 得到了解决

但是出现了新的问题。
```bash
×
Error: Could not find "store" in the context of "Connect(Users)". 
Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> 
and the corresponding React context consumer to Connect(Users) in connect options.
```

**Comment by maijieduo** [comment]
请问你这个问题解决没

**Comment by hzhijun** [comment]
> > 遇到了同样的问题，import {connect} from "react-redux" + 升级 dva@2.6.0-beta.19 得到了解决
> 
> 但是出现了新的问题。
> 
> ```shell
> ×
> Error: Could not find "store" in the context of "Connect(Users)". 
> Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> 
> and the corresponding React context consumer to Connect(Users) in connect options.
> ```

请问你这个问题解决了吗？我也遇到了同样的问题，试了好多种方案，都没解决。

**Comment by lyuns** [comment]
时间有点久了，当时这个项目后来锁版本了  "umi": "3.5.17",
    "@umijs/plugin-esbuild": "1.4.1",
    "@umijs/preset-react": "1.8.24" 可以参考下，另外变更包后要把 node_modules、.umi 文件全部删了，重新 npm install 和 build

**Comment by yunyouu** [comment]
当时是引入了 react-redux 依赖，然后 connect 直接从 react-redux 导入可以正常使用，后续项目使用的 umi 跟着版本升级了之后没有这类问题了。
