### ISSUE TITLE
umi升级到3后，实时编译速度明显减慢，node_modules必须参与编译吗，是否可以将需要编译的node_moules配置进去，否则排除掉

### ISSUE THREAD

**Issue by shuai-shuai-shuai** [umijs/umi#4229]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by zuiidea** [comment]
umi3 可以通过更改webpack 配置来改变`node_moules`哪些库参与编译，下面是禁用`node_moules`所有库参与编译的例子。不过很不幸的是，经实测即使完全排除编译速度也不及umi2。

.umirc.js

```js
  chainWebpack(memo) {
    memo.module
      .rule('js-in-node_modules')
      .exclude.add(/node_modules/)
      .end()

    memo.module
      .rule('ts-in-node_modules')
      .exclude.add(/node_modules/)
      .end()
}
```

API参考：[https://umijs.org/config#chainwebpack](https://umijs.org/config#chainwebpack)

**Comment by sorrycc** [comment]
在 #4231 跟进。

**Comment by NexxLuo** [comment]
排除了node_modules并没有明显的速度提升

**Comment by bobchen554** [comment]
`memo.module.rules.delete('js-in-node_modules')`   使用后 nodeModulesTransform 功能不可用
