### ISSUE TITLE
配置式路由报错，相对路径莫名其妙多了两个层级？？

### ISSUE THREAD

**Issue by dkvirus** [umijs/umi#423]
# 版本信息

- umi 1.2.4
- node 8.0.0

# 目录结构

![image](https://user-images.githubusercontent.com/29170168/39611101-87b81346-4f87-11e8-9b11-9a45c5128258.png)

# 路由配置

按照文档要求创建  `_routes.json` 放在 src 目录下面。

页面很简单，pages 目录下只有一个 index.js 页面和 user.js 页面，文档里说 component 是相对路径引用，这里 `_routes.json` 和 `pages` 处于同一层级，用 `./pages` 貌似没问题吧~
 
```
[
    { "path": "/", "exact": true, "component": "./pages/index" },
    { "path": "/user", "exact": true, "component": "./pages/user" }
]
```

# 报错信息

![image](https://user-images.githubusercontent.com/29170168/39611135-db4083c2-4f87-11e8-922a-645bdbf2b0d7.png)

**Comment by sorrycc** [comment]
component 的路径是从当前路径开始算的，不是从 pages 目录开始，所以改成 `./src/pages/index` 试试。

**Comment by dkvirus** [comment]
改成 `./src/pages/index` 可以了。很纳闷 `_routes.json` 放在 src 目录下面，相对路径却还要从 src 开始，感觉很容易让人产生误解的。官方文档最好好实时更新一下吧~
