### ISSUE TITLE
@umijs/plugin-access和@umijs/plugin-initial-state里面的数据如何更改啊，只能用初始化的数据吗？文档看完都找不到解决办法

### ISSUE THREAD

**Issue by Picsong** [umijs/umi#4230]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by yutingzhao1991** [comment]
目前不支持更改。可以说下具体的需求场景吗？

**Comment by Picsong** [comment]
这样一个场景，一个后台管理系统，用户未登录默认进入首页根据初始数据，没有任何权限只能看到一个欢迎页，当用户登录之后，有了自己的权限访问一些页面，这时候把登录获取到的数据更新到初始数据中去，然后access.ts这个文件的方法再更新权限。目前就是没有办法修改，但是你们access.ts中的数据又是从plugin-initial-state的方法返回的，但是这个方法又是应用第一次加载的时候执行的，能不能提供一个方法去修改初始数据



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yu"<notifications@github.com&gt;; 
发送时间: 2020年3月23日(星期一) 下午2:30
收件人: "umijs/umi"<umi@noreply.github.com&gt;; 
抄送: "@Picsong"<312465087@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [umijs/umi] @umijs/plugin-access和@umijs/plugin-initial-state里面的数据如何更改啊，只能用初始化的数据吗？文档看完都找不到解决办法 (#4230)





 
目前不支持更改。可以说下具体的需求场景吗？

**Comment by leftstick** [comment]
@Picsong 我做的脚手架里包含了你这个场景，[generator-umi](https://dfocusgroup.github.io/generator-umi/)，有专门的介绍。你看下，有问题再交流

**Comment by Picsong** [comment]
> @Picsong 我做的脚手架里包含了你这个场景，[generator-umi](https://dfocusgroup.github.io/generator-umi/)，有专门的介绍。你看下，有问题再交流
谢谢了，正在学习，大佬加个qq吧交流方便点，我留一个我的312465087

**Comment by leftstick** [comment]
> > @Picsong 我做的脚手架里包含了你这个场景，[generator-umi](https://dfocusgroup.github.io/generator-umi/)，有专门的介绍。你看下，有问题再交流
> 
> 谢谢了，正在学习，大佬加个qq吧交流方便点，我留一个我的312465087

我没qq，抱歉


加我微信：leftstick

**Comment by xuchao321** [comment]
请问这个问题如何解决的  同问

**Comment by z-lionel** [comment]
https://umijs.org/zh-CN/plugins/plugin-initial-state#loading
文档上有说通过setInitialState可以去修改
