### ISSUE TITLE
umi3 性能上真的有提升吗 

### ISSUE THREAD

**Issue by zuiidea** [umijs/umi#4231]
umi3 相比 umi2在架构上有升级，但是在性能上真的有提升吗，这是一个最简单的例子在gitpod.io上运行情况，
- 首次启动：umi3 13.38s，umi2 7.81s.
- 首次改变代码编译时间：umi3 1.53s, umi2 1.20s.
- 二次改变代码编译时间：umi3 0.64s, umi2 0.57s.

在真实项目中，可能包含了许多库，umi 3编译时间更为堪忧，node_modules走babel带来的性能问题尤其明显。即使node_modules不走babel性能也不及 umi2。

目前是否有hack的方案，或者直接建议不使用umi3?

### umi3和umi2在gitpod.io上运行情况：

- [https://gitpod.io/#https://github.com/zuiidea/app-umi2](https://gitpod.io/#https://github.com/zuiidea/app-umi2)
- [https://gitpod.io/#https://github.com/zuiidea/app-umi3](https://gitpod.io/#https://github.com/zuiidea/app-umi3)

![屏幕快照 2020-03-21 下午8 55 39](https://user-images.githubusercontent.com/16070518/77246073-accc0980-6c5e-11ea-8260-3d9591ebb4c6.png)

![屏幕快照 2020-03-21 下午8 53 40](https://user-images.githubusercontent.com/16070518/77246080-b7869e80-6c5e-11ea-99a3-01742655af1e.png)

### node_modules不走babel的配置方式：

![code](https://user-images.githubusercontent.com/16070518/77246075-ae95cd00-6c5e-11ea-96dc-20841358c73d.png)

**Comment by zhfish** [comment]
关注一下

**Comment by sorrycc** [comment]
准备允许通过配置切换到旧的 node_modules 打包方式，

1. 可以选择是否使用 es5-imcompatible-versions
2. 允许 include 部分依赖

配置格式为 `dontTransformNodeModules: { expect?: string[], useEs5ImcompatibleVersions?: boolean; }`。

* expect, 指定依赖里需要走 babel 编译的部分
* useEs5ImcompatibleVersions，是否编译 https://github.com/umijs/es5-imcompatible-versions 里的依赖

**Comment by fjc0k** [comment]
我的建议是 dev 阶段关闭 babel 编译 node_modules，build 时开启 babel 编译。

就是现在这样：

```ts
{
  chainWebpack: config => {
    if (process.env.NODE_ENV === 'development') {
      config.module
        .rule('js-in-node_modules')
        .exclude.add(/node_modules/)
        .end()
      config.module
        .rule('ts-in-node_modules')
        .exclude.add(/node_modules/)
        .end()
    }
  }
}
```

**Comment by rilaohn** [comment]
个人感觉是明显变慢，但是本地文件大小确实少了

**Comment by sorrycc** [comment]
Fixed via umi 3.1

**Comment by conkyliu** [comment]
升级了3.1.0
