### ISSUE TITLE
umi3 model中router对象在切换路由时信息不更新

### ISSUE THREAD

**Issue by 3478349671** [umijs/umi#4232]
## What happens?

umi3 中切换路由时，model state的router对象不更新，umi2没这个问题

## 复现步骤，错误日志以及相关配置

从路由/a切换到路由/b，model中的router对象值还是路由/a的信息，并没有自动更新到路由/b的信息

umirc.ts配置
```
dva: {
    immer: true,
    hmr: true,
  }
```
## 相关环境信息

- **Umi 版本**：3.0.12
- **Node 版本**：12.13.1
- **操作系统**：mac os

**Comment by sorrycc** [comment]
给下复现。

**Comment by 3478349671** [comment]
> 给下复现。


<img width="648" alt="屏幕快照 2020-03-23 下午9 36 14" src="https://user-images.githubusercontent.com/19977382/77322341-8eddd200-6d4e-11ea-85b9-7a3327c5e48e.png">
比如从/login切换到/main路由，这个router对象里面的值不跟随跳转路由更新成/main路由信息

**Comment by feibi** [comment]
确实存在这个问题

**Comment by leftstick** [comment]
给出可复现问题的的最小repo。不是问题截图，截图并不能帮助我们定位问题

**Comment by LeoHuiyi** [comment]
![image](https://user-images.githubusercontent.com/8001457/77732078-1b361080-703f-11ea-92b9-8e5ce207be61.png)
要使用ConnectedRouter

**Comment by haozhecao** [comment]
ConnectedRouter要加在哪里呢？app.ts文件还是.umi.ts文件？或者是其他地方？

> ![image](https://user-images.githubusercontent.com/8001457/77732078-1b361080-703f-11ea-92b9-8e5ce207be61.png)
> 要使用ConnectedRouter

**Comment by wisdomG** [comment]
ConnectedRouter 要加在什么地方？是app.ts还是.umi.ts呢？或者是其他地方

**Comment by LeoHuiyi** [comment]
目前只能写个addRuntimePlugin 插件
![image](https://user-images.githubusercontent.com/8001457/77745895-0bc2c180-7057-11ea-94e1-db58985ae045.png)
覆盖RouterComponent这个组件

**Comment by 3478349671** [comment]
https://github.com/umijs/umi/issues/4385

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.

**Comment by kaven276** [comment]
我也是在项目 umi2 升级 umi3 后，发现 dva/redux 的 router model 不更新，
1. 从 redux devtools 看不到更新
2. 代码 useSelect(g => g.router.location.query) 看不到地址栏 query 的更新

**Comment by panghuhu123** [comment]
这个问题解决了么？

**Comment by panghuhu123** [comment]
这个问题现在有修复么？
