### ISSUE TITLE
Nested dva model namespaces

### ISSUE THREAD

**Issue by bogutski** [umijs/umi#4234]
Umi 3.

Current model placement in the store are flat like:
- UserList
- UserProfile
- UserFriends
- ReportList
- ReportDetails
- ...

How to organize it like:
- user
-- Profile (or UserProfile)
-- Friends (or UserFriends)
- report
-- List
-- Details

If not what is the advantages of flat structure?

**Comment by xiaohuoni** [comment]
- user
-- Profile (or UserProfile)
-- Friends (or UserFriends)
- report
-- List
-- Details

it is available that

**Comment by bogutski** [comment]
@xiaohuoni thanks. Solved
