### ISSUE TITLE
.umirc.ts开启dva后，model中引入components下的组件，会导致umi导出的插件接口(如connect,injectIntl等)失效

### ISSUE THREAD

**Issue by feibi** [umijs/umi#4235]
## What happens?

同标题

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

https://github.com/feibi/umi-model-bug.git

## How To Reproduce

1. .umirc.ts开启dva
```ts
  dva: {
    skipModelValidate: true, 
    immer: true,
  }
```
2. src/model.js导入组件
```js
import Test from '@/components/Test';

export default {
  namespace: 'app',
  state: {
    test: 'state.test',
  },
};
```
3. pages/index.tsx引入injectIntl
```tsx
import React from 'react';
import { Link, injectIntl } from 'umi';

import styles from './index.less';

export default injectIntl(({ intl }) => {
  return (
    <div>
      <h1 className={styles.title}>Page index</h1>
      <Link to="/detail">to detail</Link>
      {intl.formatMessage({ id: 'test.page' })}
    </div>
  );
});

```
4. 报错TypeError: Object(...) is not a function，umi中找不到injectIntl方法

另外，可以在组件中访问到injectIntl等方法
```tsx
import Test from '@/components/Test';
import {connect} from 'umi';

export default () => {
  console.log(connect);//这里打印没问题
  return <div>test</div>
});
```

**Expected behavior** 
希望接口能正常访问到

## Context

- **Umi Version**: 3.0.10和3.0.12
- **Node Version**: 10.15.2
- **Platform**: window10

**Comment by hankaibo** [comment]
我也遇类似错误。
reducers中user已经保存了最新数据；通过Redux插件也看到user里面有值了。
但是，通过connect中包装的组件中，user依然是空。

**Comment by feibi** [comment]
> 我也遇类似错误。
> reducers中user已经保存了最新数据；通过Redux插件也看到user里面有值了。
> 但是，通过connect中包装的组件中，user依然是空。

是umi中找不到connect方法，运行直接报错了，不是取不到数据的问题。

**Comment by hankaibo** [comment]
我是取不到最新值。
[myantdpro (2).zip](https://github.com/umijs/umi/files/4374492/myantdpro.2.zip)
npm start之后，登录，刷新或者切换语言，connect中获取不到最新值。

**Comment by hejinhua** [comment]
那请问这个问题怎么解决呢？

**Comment by feibi** [comment]
> 那请问这个问题怎么解决呢？

可以不从umi导出
```diff
- import {connect, injectIntl} from 'umi'
+ import {connect} from 'dva'
+ import {injectIntl} from 'react-intl'
```

**Comment by hankaibo** [comment]
我的是自己{}位置写错了。

**Comment by JLoveI** [comment]
有解决办法吗 急

**Comment by 104gogo** [comment]
+1，某个文件`import { formatMessage } from 'umi';`死活拿不到 formatMessage

**Comment by Malarkey-Jhu** [comment]
同问题，connect在某些页面时拿不到

**Comment by 104gogo** [comment]
将formatMessage调用的地方改个位置，在模块中的函数里面使用formatMessage可以了。。感觉需要延迟一下

**Comment by jungor** [comment]
@104gogo 大佬你找到原因了吗 我也有一样的问题

**Comment by 104gogo** [comment]
没有找到原因，不过有几个应对的方法
1. 在函数里面使用，不在模块里面直接调用
2. 放在 async.js 的文件里面
3. 从umi把用到的函数源码复制出来，直接使用

**Comment by jungor** [comment]
我在global.ts里先手动addLocal添加语言信息，其他地方的formatMessage就基本正常了

**Comment by leegsen7** [comment]
亲测的这个问题。https://v3.umijs.org/zh-CN/plugins/plugin-dva#typeerror-object-is-not-a-function
默认会将 model 导出的类型挂载到 umi 上，这个设计真烂
