### ISSUE TITLE
[Feature Request] useModel有什么思路可以统一loading?

### ISSUE THREAD

**Issue by zhfish** [umijs/umi#4238]
## Background

1. dva统一了loading，像切换到更简洁的useModel上，却发现loading不好处理了  
2. useModel能否加载当前目录下的model？

## Proposal

能否给出useModel的食用最佳方案或者思路？

**Comment by sorrycc** [comment]
useModel 适用于简易场景，如果数据流方面需要有比较复杂的处理，建议继续用 dva 或其他数据流方案。
