### ISSUE TITLE
eslint 命名跑不起来,Cannot find module 'eslint-config-umi'

### ISSUE THREAD

**Issue by 6691** [umijs/umi#424]
因为多人开发，想查看当前负责的目录下的文件是否符合 eslint 规范

.eslintrc 文件如下：
{
  "extends": "eslint-config-umi"
}

cmd  eslint 命名跑不起来 Cannot find module 'eslint-config-umi'

C:\web>eslint ./src/user
Cannot find module 'eslint-config-umi'
Referenced from: C:\web\.eslintrc
Error: Cannot find module 'eslint-config-umi'

请问怎么配置????

**Comment by xiaohuoni** [comment]
```js
 "devDependencies": {
    "eslint": "^4.19.1",
    "eslint-config-umi": "^0.1.4",
    "eslint-plugin-flowtype": "^2.46.3",
    "eslint-plugin-import": "^2.11.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.1.0",
    "husky": "^0.14.3"
  }
```

**Comment by xiaohuoni** [comment]
Cannot find module 'xxx'   npm i xxx

**Comment by 6691** [comment]
@xiaohuoni 
"devDependencies": {
    "enquire-js": "^0.1.2",
    "eslint": "^4.19.1",
    "eslint-config-umi": "^0.1.4",
    "eslint-plugin-flowtype": "^2.46.3",
    "eslint-plugin-import": "^2.11.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.7.0",
    "react-container-query": "^0.11.0"
  }
这些东西都有的，我是单独 eslint 命令行跑

**Comment by xiaohuoni** [comment]
那是不是要装到全局变量里面？

**Comment by 6691** [comment]
@xiaohuoni  不用吧 这个就在本地用，

**Comment by xiaohuoni** [comment]
@6691 那你在package.json里面，添加一个scripts试试
```js
"scripts": {
    "start": "umi dev",
    "abcd": "eslint ./src/user",
  },
```
npm run abcd

**Comment by 6691** [comment]
@xiaohuoni  这样可以 谢谢

**Comment by xiaohuoni** [comment]
@6691 那就是全局变量问题了，这样子，用的才是项目中的模块
