### ISSUE TITLE
控制台提示 export ‘defineConfig’ was not found in ‘umi’

### ISSUE THREAD

**Issue by liuxinqiong** [umijs/umi#4241]
## What happens?

更新 umi 3.下后, config.ts 中使用如下代码
```ts
import { defineConfig, utils } from 'umi';
```

控制台提示 `export ‘defineConfig’ was not found in ‘umi’` 与 `export 'utils' was not found in 'umi'`，vscode 不报错，但浏览器访问服务报错，提示 `Cannot read property 'winPath' of undefined`

备注
1. tsconfig.json 已配置 `@@`
2. `src/.umi/core/umiExport` 有相关内容

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.
希望控制台不报 warning，服务正常访问

## Context

- **Umi Version**: 3.0.12
- **Node Version**:10.15.3
- **Platform**:windows

**Comment by sorrycc** [comment]
代码里有引配置文件？

**Comment by liuxinqiong** [comment]
> 项目代码里有引配置文件？

感谢回复，还真是，用到了 `config.base` 的配置，是项目中完全不能引配置文件吗？

**Comment by sorrycc** [comment]
配置文件是 node 侧的，很有可能会引入 node 相关依赖，甚至包括 webpack。

**Comment by MrSuperLi** [comment]
> 项目代码里有引配置文件？

请问这个怎么解决呢。如何引入

**Comment by minlingling1234** [comment]
> ## What happens?
> 更新 umi 3.下后, config.ts 中使用如下代码
> 
> ```ts
> import { defineConfig, utils } from 'umi';
> ```
> 
> 控制台提示 `export ‘defineConfig’ was not found in ‘umi’` 与 `export 'utils' was not found in 'umi'`，vscode 不报错，但浏览器访问服务报错，提示 `Cannot read property 'winPath' of undefined`
> 
> 备注
> 
> 1. tsconfig.json 已配置 `@@`
> 2. `src/.umi/core/umiExport` 有相关内容
> 
> ## Mini Showcase Repository(REQUIRED)
> > Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub
> 
> ## How To Reproduce
> **Steps to reproduce the behavior:** 1. 2.
> 
> **Expected behavior** 1. 2.
> 希望控制台不报 warning，服务正常访问
> 
> ## Context
> * **Umi Version**: 3.0.12
> * **Node Version**:10.15.3
> * **Platform**:windows

同问，想知道怎么解决问题的，具体出错在哪？

**Comment by minlingling1234** [comment]
> ## What happens?
> 更新 umi 3.下后, config.ts 中使用如下代码
> 
> ```ts
> import { defineConfig, utils } from 'umi';
> ```
> 
> 控制台提示 `export ‘defineConfig’ was not found in ‘umi’` 与 `export 'utils' was not found in 'umi'`，vscode 不报错，但浏览器访问服务报错，提示 Refused to apply style from 'http://******/undefinedvendors.chunk.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
> 
> 备注
> 
> 1. tsconfig.json 已配置 `@@`
> 2. `src/.umi/core/umiExport` 有相关内容
> 
> ## Mini Showcase Repository(REQUIRED)
> > Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub
> 
> ## How To Reproduce
> **Steps to reproduce the behavior:** 1. 2.
> 
> **Expected behavior** 1. 2.
> 希望控制台不报 warning，服务正常访问
> 
> ## Context
> * **Umi Version**: 3.1.4
> * **Node Version**:12.16.3
> * **Platform**:windows

**Comment by cajan** [comment]
> > ## What happens?
> > 更新 umi 3.下后, config.ts 中使用如下代码
> > ```ts
> > import { defineConfig, utils } from 'umi';
> > ```
> > 
> > 
> > 控制台提示 `export ‘defineConfig’ was not found in ‘umi’` 与 `export 'utils' was not found in 'umi'`，vscode 不报错，但浏览器访问服务报错，提示 Refused to apply style from 'http://******/undefinedvendors.chunk.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
> > 备注
> > 
> > 1. tsconfig.json 已配置 `@@`
> > 2. `src/.umi/core/umiExport` 有相关内容
> > 
> > ## Mini Showcase Repository(REQUIRED)
> > > Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub
> > 
> > 
> > ## How To Reproduce
> > **Steps to reproduce the behavior:** 1. 2.
> > **Expected behavior** 1. 2.
> > 希望控制台不报 warning，服务正常访问
> > ## Context
> > 
> > * **Umi Version**: 3.1.4
> > * **Node Version**:12.16.3
> > * **Platform**:windows

后来解决了么，我同出现
