### ISSUE TITLE
umi3创建应用ie11无法访问，配置targets也不行

### ISSUE THREAD

**Issue by gaorubin1990** [umijs/umi#4242]
## What happens?

umi3创建应用ie11无法访问，配置targets也不行

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.0.12
- **Node Version**:  12.10.0
- **Platform**: mac

**Comment by sorrycc** [comment]
dev 时不行（dev 先用 Chrome 吧），build 后可以。

**Comment by gaorubin1990** [comment]
> dev 时不行（dev 先用 Chrome 吧），build 后可以。

好的，谢谢

**Comment by xiexingen** [comment]
build以后 会有`` 模板字符串 在ie下提示不支持的语法
