### ISSUE TITLE
umi3 在android 4.4无法运行

### ISSUE THREAD

**Issue by huangang** [umijs/umi#4246]
## What happens?

umi3 在android 4.4无法运行，targets已经加了 `android: 4.4`
报`Uncaught SyntaxError: Use of const in strict mode. `的错误
dev, build都无法运行
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:3.0.13
- **Node Version**:12.16.1
- **Platform**:mac

**Comment by sorrycc** [comment]
排查下 const 在哪个文件里出现？

**Comment by huangang** [comment]
> 排查下 const 在哪个文件里出现？

`umi.js`这个文件出现的

**Comment by xusai2014** [comment]
这要吓死个人啊，我得赶紧切回去

**Comment by xiaohuoni** [comment]
给一个重现demo？我这里没什么问题

**Comment by huangang** [comment]
> 给一个重现demo？我这里没什么问题

在android4.4上面用原生的浏览器测试是有问题的，装个最新的谷歌浏览器是没问题的

**Comment by huangang** [comment]
感觉问题就是编译生成的`umi.js`, `const` 这样es6或者更新语法能不能编译到低版本兼容的写法？

**Comment by xusai2014** [comment]
最简单的方式拿到这个文件全局搜索一下，就成了。没那么麻烦。

**Comment by xusai2014** [comment]
要学会看混淆后的文件

**Comment by xusai2014** [comment]
![image](https://user-images.githubusercontent.com/8156165/77455944-7eeced80-6e35-11ea-9775-8ebf7d65f44d.png)
![image](https://user-images.githubusercontent.com/8156165/77455973-8d3b0980-6e35-11ea-964e-85942eda3b56.png)
react-intl 包转译过程未处理const

**Comment by sorrycc** [comment]
找到原因了，今天修。

**Comment by xusai2014** [comment]
react-intl的语法降级问题，在plugin-locale中选择降级方案。想向社区做贡献奈何一堆穿越式包引入方案，没太搞懂，请教一下umi整体的bundle方案。

**Comment by huangang** [comment]
项目要上线了，umi这个问题还没修复
搞了个临时解决方案：
+ 安装一些依赖: `npm i core-js @babel/cli @babel/core @babel/preset-env webpack-cli -D`
+ 添加`.babelrc`: 
``` json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "esmodules": true,
          "android": "4.4"
        },
        "modules": "umd",
        "corejs": "^3.6.4",
        "useBuiltIns": "usage"
      }
    ]
  ]
}
```
+ 添加`webpack.config.js`: 
``` js
const config = {
  mode: 'production',
  entry: __dirname + '/www/umi.js',
  devtool: 'cheap-module-source-map',
  output: {
    path: __dirname + '/www',
    filename: 'umi.js',
    library: 'umi.js',
    libraryTarget: 'umd',
    umdNamedDefine: true,
    globalObject: "typeof self !== 'undefined' ? self : this"
  },
  module: {
    rules: [
      {
        test: /(\.jsx|\.js)$/,
        loader: 'babel-loader',
        exclude: /(node_modules|bower_components)/
      }
    ]
  }
};

module.exports = config;
```
+ 修改或者添加新的编译命令:`umi build && webpack`
