### ISSUE TITLE
umi3 plugin-locale 中设定default:en-US不生效（locales文件夹有对应的语言文件）

### ISSUE THREAD

**Issue by MatrixAge** [umijs/umi#4248]
## What happens?

umi3 plugin-locale 中设定default:en-US不生效（locales文件夹有对应的语言文件）

## Mini Showcase Repository(REQUIRED)

[https://github.com/MatrixAge/testool](https://github.com/MatrixAge/testool)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by leftstick** [comment]
你把 `baseNavigator` 设置成 `false` 试试

**Comment by MatrixAge** [comment]
@leftstick 生效了，3ks
