### ISSUE TITLE
title能否配置关闭

### ISSUE THREAD

**Issue by LeoHuiyi** [umijs/umi#4249]
## What happens?
![image](https://user-images.githubusercontent.com/8001457/77381849-d9486880-6db9-11ea-93f1-1658c08d6dd6.png)

项目中有设置document.title 会导致title重置

**Comment by leftstick** [comment]
"项目中有设置document.title 会导致title重置"

这句话什么意思？能详细解释下场景么

**Comment by LeoHuiyi** [comment]
切换路由时候，一些遗留代码在页面中设置document.title

**Comment by xiaohuoni** [comment]
然后呢？需要关闭啥？

**Comment by LeoHuiyi** [comment]
给个配置 可以关闭set title

**Comment by xiaohuoni** [comment]
你这看起来调用的是js的方法吧。不需要的地方删除才是。和umi无关。

**Comment by LeoHuiyi** [comment]
项目中是用服务端给的数据自动配置页面title的
