### ISSUE TITLE
umi 的 权限路由对结尾的斜线敏感的bug

### ISSUE THREAD

**Issue by xiaoxiangmoe** [umijs/umi#425]
umi 的权限路由对结尾的斜线敏感，导致 umi-example 的router例子失效

**Comment by xiaohuoni** [comment]
这个能不能和模糊配置一起修改哦 https://github.com/umijs/umi/pull/403  @sorrycc

**Comment by soolx** [comment]
@sorrycc 这个问题解决了吗，或者有没有方案可以绕过去

**Comment by soolx** [comment]
版本没更新到最新，已经没问题了好像

**Comment by sorrycc** [comment]
umi@2 的方式变了，这个关了。
