### ISSUE TITLE
jest 测试方面有什么注意事项吗？升级 umi@3 之后各种错误

### ISSUE THREAD

**Issue by liuxinqiong** [umijs/umi#4251]
## What happens?

一个 warning，umi@3 中 `jest.config` 是不是不支持 `extraSetupFiles` 配置了。

运行 `npm test` 就会出现如下的错误
![image](https://user-images.githubusercontent.com/20576218/77383296-7eb10b80-6dbd-11ea-9a98-33dfd39aaf9d.png)

![image](https://user-images.githubusercontent.com/20576218/77383299-81abfc00-6dbd-11ea-9dd3-3332b7a015ea.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.
这一块的文档非常少，希望可以多一点

希望根据上述错误，给指名点方向，实在是没辙了

## Context

- **Umi Version**: 3.0.12
- **Node Version**: 10.15.3
- **Platform**: windows

**Comment by liuxinqiong** [comment]
难道只有我有这个问题吗，[这里是一个委屈巴巴的表情]

**Comment by sorrycc** [comment]
直接用 jest 会有问题吗？

**Comment by liuxinqiong** [comment]
@sorrycc 
抱歉，就在这一刻，我找到原因了。首先声明一下，和 umi@3 的升级没有关系。

原因在于测试运行真的失败了，但控制台没能把运行结果打印出来。控制台没打印出来的原因在于，为配合 CI，修改了 `reporters` 配置，但没保留 `default` 选项。

至于为何单测失败的原因在于，test 文件中通过 `@` alias import 文件，报错找不到指定模块，在这里也可以顺便提一下，如果有人也碰到这个问题的话可能会有帮助，正在如下 jest 配置即可
```json
moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
}
```

最后感谢回复，叨扰了。
