### ISSUE TITLE
export 'useIntl' was not found in 'umi'

### ISSUE THREAD

**Issue by Turbe** [umijs/umi#4254]
import { Link, useIntl } from 'umi';
const { formatMessage }  = useIntl();

按照文档来搭建，为何出现这样报错，在社区提出问题也并没有回答
如果配置有问题，请在文档里说清楚呀，umi3到目前为止，直接让人奔溃
export 'useIntl' was not found in 'umi'

**Comment by leftstick** [comment]
给出可复现的repo吧。就目前为止，你说的现象我还没遇到

**Comment by leftstick** [comment]
或者直接使用脚手架[generator-umi](https://dfocusgroup.github.io/generator-umi/)，创建一个项目，对照一下差异在哪里

**Comment by Turbe** [comment]
基本摸索出来了……需要查看配置和对应模块的文件夹是否存在

**Comment by Turbe** [comment]
基本摸索出来了……需要查看配置和对应模块的文件夹是否存在

**Comment by Turbe** [comment]
基本摸索出来了……需要查看配置和对应模块的文件夹是否存在

**Comment by Turbe** [comment]
基本摸索出来了……需要查看配置和对应模块的文件夹是否存在

**Comment by Turbe** [comment]
基本摸索出来了……需要查看配置和对应模块的文件夹是否存在

**Comment by wangjingithub** [comment]
求看下解决方案

**Comment by tsinglemon** [comment]
同求~，我是从umi2升级到啊umi3时出现这个问题的

**Comment by zhangyuezhong** [comment]
import { SelectLang } from '@umijs/plugin-locale';

**Comment by HaiYoungs** [comment]
配置加上locale: {} 开启 @umijs/plugin-locale 插件就可以了
