### ISSUE TITLE
umi@3 css modules的识别方式无法处理node_modules下的文件？ 

### ISSUE THREAD

**Issue by NexxLuo** [umijs/umi#4255]
![image](https://user-images.githubusercontent.com/18549980/77396557-f04d8180-6dde-11ea-8d5c-debea0b0a361.png)

umi@3会自动识别哪些文件走css modules，
但是目前发现无法处理到node_modules下的文件。 

node_modules中有一个组件包，组件包中使用了 import styles from "./styles.less";
此组件样式会丢失

**Comment by NexxLuo** [comment]
可能是中间的转换问题。
手动在import地方加上resourceQuery `modules`就可以。
乳：` import styles from "../styles.less?modules`

**Comment by 662** [comment]
@NexxLuo 我这边遇到个问题有点类似
> node_modules中有一个组件包，组件包中使用了 import "./styles.less";
dev 时可用
build 时发现 umi.css 中未包含 "./styles.less" 中的样式

**Comment by rockhentai** [comment]
同样遇到这个问题

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.

**Comment by sorrycc** [comment]
node_modules 下的文件不走 babel 编译，所以失效，如需这个功能，可通过 extraBabelIncludes 指定 node_modules 下需要额外编译的依赖。

**Comment by AricZhu** [comment]
> node_modules 下的文件不走 babel 编译，所以失效，如需这个功能，可通过 extraBabelIncludes 指定 node_modules 下需要额外编译的依赖。

配置 extraBabelIncludes 后是可以解析本地的 node_modules 中的样式文件，但对于 tnpm link 的包还是无法解析

**Comment by wsz7777** [comment]
同样遇到这个问题 配置了
```
  extraBabelIncludes: ['antd'],
```
还是不生效
