### ISSUE TITLE
history监听

### ISSUE THREAD

**Issue by Joan1106web** [umijs/umi#4257]
"umi": "^3.0.13",版本中的 history没listen方法，监听无效

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/77414504-1afa0300-6dfc-11ea-8001-891c09dc0cc9.png)

试了下，有效，[sorrycc-1QdpJF.zip](https://github.com/umijs/umi/files/4374621/sorrycc-1QdpJF.zip)。

**Comment by laeni** [comment]
在 app.ts 中监听无效
