### ISSUE TITLE
静态化部署到nginx中的动态路由

### ISSUE THREAD

**Issue by DarcyXf** [umijs/umi#4261]
.umirc.ts中配置了
`exportStatic: {}, 
dynamicImport：{},`
选择静态化与按需加载后，
部署到nginx, 通过rewrite的方式隐式跳转（/c/xxx =>  a.html）
通过访问/c/xxx 可以加载到对应的html, umi.js, umi.css 但是该页面对应的按需加载的js和css却未加载
- **umi 3.0.7**:
- **node 12.10.0**:
- **sys macOs  10.14.5**:

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
