### ISSUE TITLE
本地项目的 Umi 版本（3.0.14）过低，请升级到 umi@2.10 或以上

### ISSUE THREAD

**Issue by JeffreyBool** [umijs/umi#4263]
![image](https://user-images.githubusercontent.com/24415888/77457670-f4f25400-6e37-11ea-88a2-821e86495d71.png)

**Comment by sorrycc** [comment]
@ycjcl868

**Comment by ycjcl868** [comment]
升级全局 umi

**Comment by ycjcl868** [comment]
umi 3目前没提供完整版 ，先在项目里使用 mini 版

**Comment by JeffreyBool** [comment]
明显本地的umi高于需要版本------------------ 原始邮件 ------------------
发件人: "信鑫-King"<notifications@github.com>
发送时间: 2020年3月25日(星期三) 上午8:48
收件人: "umijs/umi"<umi@noreply.github.com>;
抄送: "JeffreyBool"<1402992668@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [umijs/umi] 本地项目的 Umi 版本（3.0.14）过低，请升级到 umi@2.10 或以上 (#4263)




 
升级全局 umi
 
&mdash;

**Comment by JeffreyBool** [comment]
> umi 3目前没提供完整版 ，先在项目里使用 mini 版

mini 版 在哪？

**Comment by xiaohuoni** [comment]
> > umi 3目前没提供完整版 ，先在项目里使用 mini 版
> 
> mini 版 在哪？

装完preset-ui，直接 dev 启动就是 mini

**Comment by ycjcl868** [comment]
https://github.com/umijs/umi-ui#-%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B
