### ISSUE TITLE
dynamicImport打包文件偏大

### ISSUE THREAD

**Issue by freecnpro** [umijs/umi#4266]
升级umi 3后，dynamicImport不再有level配置，导致打包后的文件量由umi 2的十几个增加到一百多个，同时vendors.async.js和umi.js大小也偏大。请问要怎么优化？
<img width="730" alt="693EABBA-0FB0-4173-B0C3-72840FF5A0E0" src="https://user-images.githubusercontent.com/3022374/77495834-8daec100-6e84-11ea-96b0-20f996e35b8e.png">

## 相关环境信息

- **Umi 版本**：3.0.12
- **Node 版本**：13.10.1
- **操作系统**：macOS 10.15

**Comment by Agagy** [comment]
附议，+1，看了源代码确实打包进去了不少重复代码，本来一个10K的文件，加上依赖就可能超过100K。。。

**Comment by Tenodec** [comment]
感觉有点像赶kpi出来的产物，相对于2，文档，教程不齐全，优化没到位就出来了（单纯吐槽一番）。antd4.0文档感觉也差不多的样子

**Comment by sorrycc** [comment]
ANALYZE=1 分析下。

**Comment by sorrycc** [comment]
code splitting 策略可以自己配的，umi 没做啥特殊处理。
