### ISSUE TITLE
history.location获取query报错tslint

### ISSUE THREAD

**Issue by perany** [umijs/umi#4268]
umi3.0通过history获取URL参数时报错，代码：
const {query} = history.location;
tslint会报错：Property 'query' does not exist on type 'Location<PoorMansUnknown>'.
但实际上可以获取到query对应的值

**Comment by leftstick** [comment]
漏了定义，处理中

**Comment by sorrycc** [comment]
fixed.

**Comment by leftstick** [comment]
@sorrycc commit [7b681c5](https://github.com/umijs/umi/commit/7b681c56a659ac67d91976b6b381786917cd0aca) 只提供了 `history.push({ query })` 里query的定义，

直接使用 `history.location`，或者 `useLocation()` 导出的 `location` 里依旧是没有 `query` 定义的。但实际 `query` 是有值的

**Comment by fjc0k** [comment]
推荐插件：https://github.com/fjc0k/umi-plugin-router-plus:

```ts
// src/pages/test.tsx
import React from 'react'
import { usePageParams } from 'umi'

export interface Params {
  id: number,
  enabled?: boolean,
  gender: 'male' | 'female',
  name: string,
  tags?: string[],
}

export default function () {
  const {
    id,
    enabled = false, // 指定默认值
    gender,
    name,
    tags = [],
  } = usePageParams('Test')

  return (
    <div>id is: {id}</div>
  )
}
```

**Comment by sorrycc** [comment]
@leftstick 感觉是个大工程。

**Comment by leftstick** [comment]
@sorrycc ，只加定义的话，你是考虑可能有场景是没有 `query` 的？还是担心 `query` 的实现问题?

**Comment by xiaohuoni** [comment]
相同的问题 https://github.com/umijs/umi/issues/5278
