### ISSUE TITLE
官网API左侧边栏导航链接不对

### ISSUE THREAD

**Issue by s5s5** [umijs/umi#4269]
访问： https://umijs.org/zh-CN/api#navlink
左侧边栏路由下面的导航点击时链接的地址不对
PS: 好像别的侧导航有的也有问题，没细看，你们排查下
PSPS：好像还有页面右侧导航在文字太多时导致有滚动条，WIN下特有，你们有空也看看

## 相关环境信息

Windows 10 专业版 64位 版本号 1903
Google Chrome 80.0.3987.149（正式版本）（64 位）

**Comment by xiaohuoni** [comment]
我这里都是正确的。你再试试，有问题再说下
