### ISSUE TITLE
期待 umi 对于【业务功能模块化开发】的一些改进

### ISSUE THREAD

**Issue by dkvirus** [umijs/umi#427]
@sorrycc 模块化开发的思想之前在 antd-pro 的社区里有人提出，后来使用 dva 我也确实实现了，但现在看着 umi 的茁壮成长，想要迁移过来，遇到点问题。

# dva 时代

以电商后管系统为例，包含 `商品模块`、`订单模块`。建立三个 dva 项目

- dva 商品项目：做商品模块功能；
- dva 订单项目：做订单模块功能；
- dva 布局项目：后管整体布局。

正式上线的时候会将 `商品项目` 和 `订单项目` 打包成 npm 包，在 `布局项目` 中引入 npm 包实现功能。

`dva 商品项目` 和 `dva 订单项目` 往外部透漏一个接口，为页面对应的 models 和 routes 文件的相对路径。在 `dva 布局项目` 中只需要拼接下数组即可。格式如下：

**dva 商品项目透漏给外部的接口示例：** 只要路由变成 `/shop/goods` ，就会显示 `./routes/shop/goods/` 对应的页面，于此同时加载 `./models/shop/goods` 下面的状态管理器。

这里 models 由外部 `dva 布局项目` 注册，但实际执行的文件仍然是 npm 包内部的文件。

```
const routes = [{
    path: '/shop/goods',
    models: () => [import('./models/shop/goods')],
    component: () => import('./routes/shop/goods/'),
}];
export default routes;
```

# umi 时代

umi 目前的特性阻碍了模块化开发代码的迁移，原因有两点。

- 路由。好的一点是目前提供了配置式路由，但貌似只支持 json 格式，这样就不能自主拼接路由了。希望能升级成 **js 格式的路由配置文件**，最终 export 一个数组就完美了。:100:

- model 注册。暂时特性为自动注册 src 下面的 model.js，这样就没法注册 npm 包里子模块的 model 了。希望能添加 **手动注册 model 的方法**。

个人理解，umi 仅仅是工具上的完善，应该尽量少的干预工具原本的特性，可以优化，但前提是保证原有特性仍可使用，这在老代码升级上简直太重要了。

**Comment by wunayou** [comment]
像我们这种喜欢 react-router 4的人  第二级路由确定以后，第三级 就交给专门业务负责的人 所以是需要 他们自动配的

**Comment by dkvirus** [comment]
@szwork2013 route 内部用的状态为何不直接用 state，model 里就放可能多个 route 会用到的数据。

**Comment by szwork2013** [comment]
@dkvirus 业务模块多的系统一般还是要动态加载的，而不是一次全部加载.

**Comment by CN-YUANYU** [comment]
@dkvirus 实际上，当你选择用了  数据流的管理框架之后， 我们就不推荐你在任何业务组件中 去使用 state了，  理想状态下全部放置在model 中， 这样带来的好处是统一管理，  不然你一个页面 十几个组件， 这个组件里面写两个state  ， 那个里面也写两个， 你让后面维护的人心理怎么想？

当然并不是说我们就彻底的不要用state 了，  我觉得在开发业务代码的时候 突然的发现自己的某一个组件可以完全的独立出业务，拿到任何一个项目中用都很棒， 那么适当的结合state+props 或许会更好

事实上 通过实践我倒是觉得，  在单个页面级 应该去写两个model ，  一个控制ui的呈现， 一个控制domain数据， 这样逻辑上更加的清晰，  当然全局model 也有存在的必要


在实际的开发过程中， 我还思考过 是否要对model 进行3级缓存处理？ 方便我能够通过一个方法之前清除掉 指定缓存级别中的所有model

**Comment by zjxpcyc** [comment]
公司好几个项目的 model 都是按资源分的，跟 route 就不是一一对应关系。所以，umi 从 1.x 一直观望到现在了。

**Comment by sorrycc** [comment]
@zjxpcyc 路由和 model 支持扩展是否就可以了？

* [x] 路由已经是配置式的了
* [ ] 支持路由组件定义额外的 models

**Comment by zjxpcyc** [comment]
@sorrycc 是的

**Comment by CN-YUANYU** [comment]
@sorrycc  还有一种场景化的 model ，  就是可能我是多个路由组建起来了一个业务场景， 在这个业务场景下  大家用的model  是一样的， 而出了这个场景之后会被卸载

**Comment by sorrycc** [comment]
在 https://github.com/umijs/umi-example-monorepo 跟进。
