### ISSUE TITLE
[Bug] getInitialProps not work in ssr

### ISSUE THREAD

**Issue by JaeWangL** [umijs/umi#4270]
## What happens?
getInitialProps looks not working in ssr
Did I handle something wrong?

```
    ssr: true,
    theme: 'src/theme.ts',
    treeShaking: true,
    hash: true,
    targets: {
        ie: 11,
    },
    sass: {},
    runtimePublicPath: true,
    cssModulesWithAffix: true,
    outputPath: '../public',
    publicPath: '/public/',
    manifest: {
        fileName: '../../config/manifest.json',
    },
    exportStatic: false,
    lessLoaderOptions: {
      javascriptEnabled: true,
      modules: false,
    },
    disableCSSModules: true,
    disableCSSSourceMap: true,
```
```
interface TestProps extends RouteComponentProps<MatchParams> {
    channel: any;
}

const Test: React.FC<TestProps> = (props) => {
    const { channel, match } = props;

    return (...);
};
Test.getInitialProps = async ({ route, store, isServer }) => {
    const test = {
        id: 1,
    };

    return Promise.resolve({ channel: test });
};

export default React.memo(Test);
```

## Context
- **Umi Version**: 2.13.3
- **Node Version**: Node LTS 12

**Comment by xlei1123** [comment]
> ## What happens?
> getInitialProps looks not working in ssr
> Did I handle something wrong?
> 
> ```
>     ssr: true,
>     theme: 'src/theme.ts',
>     treeShaking: true,
>     hash: true,
>     targets: {
>         ie: 11,
>     },
>     sass: {},
>     runtimePublicPath: true,
>     cssModulesWithAffix: true,
>     outputPath: '../public',
>     publicPath: '/public/',
>     manifest: {
>         fileName: '../../config/manifest.json',
>     },
>     exportStatic: false,
>     lessLoaderOptions: {
>       javascriptEnabled: true,
>       modules: false,
>     },
>     disableCSSModules: true,
>     disableCSSSourceMap: true,
> ```
> 
> ```
> interface TestProps extends RouteComponentProps<MatchParams> {
>     channel: any;
> }
> 
> const Test: React.FC<TestProps> = (props) => {
>     const { channel, match } = props;
> 
>     return (...);
> };
> Test.getInitialProps = async ({ route, store, isServer }) => {
>     const test = {
>         id: 1,
>     };
> 
>     return Promise.resolve({ channel: test });
> };
> 
> export default React.memo(Test);
> ```
> 
> ## Context
> * **Umi Version**: 2.13.3
> * **Node Version**: Node LTS 12

??? 我遇到相同的问题了， React.memo 取掉 直接 export default Test; 但是这是为什么呢？
