### ISSUE TITLE
最新版运行build报错

### ISSUE THREAD

**Issue by conkyliu** [umijs/umi#4274]
## What happens?
![image](https://user-images.githubusercontent.com/26617741/77513651-5e15ae00-6eb0-11ea-9e8e-d3330113d2f8.png)

运行dev可以正常运行, build不可以
- **Umi Version**:3.0.16
- **Node Version**:13.9.0
- **Platform**:mac

**Comment by conkyliu** [comment]
关闭了dynamicImport才可以打包成功
![image](https://user-images.githubusercontent.com/26617741/77514188-51458a00-6eb1-11ea-82d9-b601d38260a2.png)

**Comment by Agagy** [comment]
附议，+1，两个我都遇到过，暂时我是加大node运行内存到4G解决这个问题

**Comment by linyongkangm** [comment]
附议，+1

**Comment by sorrycc** [comment]
在 https://github.com/umijs/umi/issues/4231 跟进。
