### ISSUE TITLE
新版 umi 在 .umi 下生成的临时文件，import 路径错误(反斜杠和正斜杠同在)

### ISSUE THREAD

**Issue by laixstx** [umijs/umi#4278]
## What happens?

如题。比如这个（反斜杠和正斜杠同在...)：
```
import { InitialState as InitialStateType } from '../plugin-initial-state\models\initialState';
```
![image](https://user-images.githubusercontent.com/10735940/77530629-9e832500-6ecc-11ea-99e6-c7ff1a2ad50e.png)

这个问题应该是从 3.0.0 开始，就一直存在的问题，一直没修复....

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

直接官网快速上手，启动即可。

## How To Reproduce

直接官网快速上手，启动即可。

## Context

- **Umi Version**: 3.0.13
- **Node Version**: 12.14.1
- **Platform**: win10

**Comment by xiaohuoni** [comment]
这个应该是修复了的，你看看你的 `@umijs/preset-react` 是不是版本没更新？

**Comment by ycjcl868** [comment]
https://github.com/umijs/plugins/pull/66/files#diff-00b70c07038bcd6bd0e403cbb8ba5baaR26

很早之前已修复，重装试试

**Comment by answer-yida** [comment]
您好，能否问一下最后是怎么解决的么，我现在也遇到同样的情况了。
