### ISSUE TITLE
ant design pro下面umi block list无法执行

### ISSUE THREAD

**Issue by fengnex** [umijs/umi#4279]
## What happens?
yarn create umi创建ant design pro应用，选择ts、antd4
创建成功后执行yarn,然后执行下面的命令，等候很长时间，一直是下面这样：

[root@localhost ant325]# umi block list
umi block list
⠦   fetch block list✖  error     HTTPError: Response code 404 (Not Found) 
    at EventEmitter.<anonymous> (/data/projects/ant325/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
⠏   fetch block list

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
[root@localhost projects]# umi -v
umi@3.0.11
[root@localhost projects]# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
[root@localhost projects]# node -v
v12.16.1
[root@localhost projects]#

**Comment by TianEnPang** [comment]
同样的问题 +1 /(ㄒoㄒ)/~~

**Comment by sorrycc** [comment]
umi ui 已不推荐使用，请使用其他方式添加模版代码。
