### ISSUE TITLE
['@umijs/plugin-qiankun']请问一下，能够做到切换模块，上个模块的内容不重置掉吗？现在一切换模块，上个模块的内容就被卸载掉了。

### ISSUE THREAD

**Issue by dbfu** [umijs/umi#4280]

**Comment by zhihongzhong** [comment]
React 都是这个特性， 使用 useModel 或者传统的model保存状态。 
在useModel中使用useEffect 执行异步方法，可以在应用程序开始的时候就执行，而不是进入页面的时候执行。 

但是在useModel中执行异步方法是危险的，例如有部分请求需要认证用户后才可访问，而useModel中调用了这个请求的话， 则会出现方法失败。
