### ISSUE TITLE
官网 配合dva使用教程 显示为空

### ISSUE THREAD

**Issue by liangyuqi** [umijs/umi#4283]
地址：[https://umijs.org/guide/with-dva.html](url)

目前效果：
<img width="1792" alt="截屏2020-03-26下午5 29 12" src="https://user-images.githubusercontent.com/28591437/77631321-5ecd4380-6f87-11ea-9811-eb829781a3ee.png">

期望效果：有教程，或者有个quickStart demo，或者有个pure的 cli

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi-examples/tree/master/with-dva
