### ISSUE TITLE
集成umi 3 后特定浏览器内核环境下，出现异常 Uncaught SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by XSmarter** [umijs/umi#4284]
## What happens?
集成umi 3 后特定浏览器内核环境下，出现异常 Uncaught SyntaxError: Unexpected token =

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
3
- **Node Version**:
- **Platform**:
千牛 6.02.09N

**Comment by xiaohuoni** [comment]
应该一样的可以通过targets配置。https://umijs.org/config#targets
