### ISSUE TITLE
umi-request does not support Big Integer type while parse JSON data

### ISSUE THREAD

**Issue by fanyinghao** [umijs/umi#4285]
## What happens?

json 数据里的整型number 如果长度超过16，后边的数字全为0。如1242730652734849000，实际为1242730652734849123(丢失最后的123)

在旧版本我可以修改response的body，用第三方包https://github.com/sidorares/json-bigint 解决

> While most JSON parsers assume numeric values have same precision restrictions as IEEE 754 double, JSON specification does not say anything about number precision. Any floating point number in decimal (optionally scientific) notation is valid JSON value. It's a good idea to serialize values which might fall out of IEEE 754 integer precision as strings in your JSON api, but { "value" : 9223372036854775807}, for example, is still a valid RFC4627 JSON string, and in most JS runtimes the result of JSON.parse is this object: { value: 9223372036854776000 }

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：1.2.19
- **Node 版本**：
- **操作系统**：

**Comment by xiaohuoni** [comment]
应该也可以一样的方式修复吧？
使用 `middlewares: [middleware],` 试试？
