### ISSUE TITLE
umi3 使用完 Umi-UI 就必然出现的运行错误。

### ISSUE THREAD

**Issue by LamTech** [umijs/umi#4286]
## What happens?

最新的 Ant Design Pro 4 ，里面是umi 3.0.14，使用umi-UI之后就会出错（需要先ctrl+c再重新tyarn start ），原因是自动安装了redux 和 dva。

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

`MacBook-Pro student % git diff package.json 
diff --git a/package.json b/package.json
index d5b23fd..bc7a419 100644
--- a/package.json
+++ b/package.json
@@ -53,6 +53,7 @@
     "@ant-design/pro-table": "^2.1.11",
     "antd": "^4.0.0",
     "classnames": "^2.2.6",
+    "dva": "^2.4.0",
     "lodash": "^4.17.11",
     "moment": "^2.24.0",
     "numeral": "^2.0.6",
@@ -62,6 +63,7 @@
     "react": "^16.8.6",
     "react-dom": "^16.8.6",
     "react-helmet-async": "^1.0.4",
+    "redux": "^4.0.1",
     "umi": "^3.0.14",
     "umi-request": "^1.0.8",
     "use-merge-value": "^1.0.1"
`

解决方法，使用完umi-UI 之后，tyarn remove dva redux，这样就可以解决问题。但是这非常麻烦！

## 相关环境信息

- **Umi 版本**：3.0.14
- **Node 版本**：13.11.0
- **操作系统**：mac

**Comment by xiaohuoni** [comment]
@ycjcl868 感觉自动装包可以去掉？这个有点难受，本来很干净的几个库，执行几次区块添加，就慢慢的库了。而且，不同的人员一起开发，也会相互影响冲突。

**Comment by ycjcl868** [comment]
不自动装依赖添加会报错

**Comment by chenshuai2144** [comment]
EffectsCommandMap  这个类型能够正常导出吗？
