### ISSUE TITLE
cannot import {Access, useAccess} from 'umi';

### ISSUE THREAD

**Issue by ahayaSKBINCN** [umijs/umi#4290]
## What happens?
.umi 文件夹里面的 plugin-access 没有被导出。

// src/access.ts

export default (initstate: any) => {
    return {
        viewable: false
    }
}
//umiExports.ts
export { history } from './history';
export { plugin } from './plugin';
export * from '../plugin-dva/exports';
export * from '../plugin-initial-state/exports';
export * from '../plugin-model/useModel';
export * from '../plugin-request/request';

唯独没有access 的导出；
虽然可以通过路径访问到  但是打包之后是否还在？
有什么办法可以处理这个问题么？

**Comment by leftstick** [comment]
给个可复现的repo

**Comment by ahayaSKBINCN** [comment]
这个问题在 node v11.10.1 中发现的；
在v10.19 中又消失了

**Comment by gitHber** [comment]
我也碰到了这个问题，但是好像要删掉.umi, 重新start应该就好了
