### ISSUE TITLE
umi2.x使用this.props.children获取子元素不正确

### ISSUE THREAD

**Issue by qianyiyang** [umijs/umi#4292]
## What happens?

在父组件中获取this.props.children获取的子元素不对.在使用的时候LeftBar外层套一层div或者在其中添加点注释,这时this.props.children获取就是正确的.把umi版本降到2.8.10的时候获取的也是正确的

![微信图片_20200327141934](https://user-images.githubusercontent.com/22905113/77727805-102ab280-7036-11ea-9ca0-3302f115071b.png)
![微信图片_20200327141938](https://user-images.githubusercontent.com/22905113/77727812-11f47600-7036-11ea-9208-4fa096a4a675.png)
![微信图片_20200327141941](https://user-images.githubusercontent.com/22905113/77727814-128d0c80-7036-11ea-8a4d-f56878214303.png)

## Context

- **Umi Version**:2.11.1
- **Node Version**:12.16.1
- **Platform**:windows 10

**Comment by xiaohuoni** [comment]
请提供重现demo
