### ISSUE TITLE
umijs3 启动后如何自动打开浏览器

### ISSUE THREAD

**Issue by eevin** [umijs/umi#4294]
没有配置.env
webpack 配置config.devServer.open(true) 也不行

**Comment by sorrycc** [comment]
暂不支持。

**Comment by luxueyan** [comment]
这么好用的功能竟然 不支持的这么理所当然，感觉umi的有些思想太项目化，完全没有开源脚手架该有的考虑

**Comment by zuixinghua** [comment]
oh my god!

**Comment by pkaq** [comment]
所以 支持了么？

**Comment by xuanxuan321** [comment]
> 暂不支持。

能说下原因吗？这么好的功能下掉了着实可惜

**Comment by RainManGO** [comment]
devServer: {
      open: true,
}
配置无效，有没有支持的计划？

**Comment by cnInkHao** [comment]
这个... 可惜了

**Comment by yaohwu** [comment]
I've tried several plugins，but no typescript version for me
so I write a simple one using typescript.

```import open from "opener";

// custom define webpack plugin
class openBrowser {
    constructor() {
        console.log("create open browser");
    }

    // noinspection JSUnusedGlobalSymbols
    apply(compiler: Compiler) {
        compiler.hooks.afterDone.tap("open browser", () => {
            console.log("open in browser");
            // can not load in same tab, bad
            open("http://localhost:3000/webapp");
        })
    }
}
```
But is there any way to make it open in the same browser tab instead of creating one new?

**Comment by huangchen1031** [comment]
I use the PLUGIN `open-browser-webpack-plugin`

```js
import openBrowser from 'open-browser-webpack-plugin';

export default defineConfig({
  // ... other config
  devServer: {
    port: process.env.PORT,
  },
  chainWebpack(config) {
    config
      .plugin('open-browser-webpack-plugin')
      .use(openBrowser, [{ url: `http://localhost:${process.env.PORT}` }]);
  },
});
```

you should add PORT in `.env` before

**Comment by xiaohuoni** [comment]
api.onDevCompileDone(async ({ isFirstCompile, ws }) => {
    const timeer = setTimeout(async () => {
      if (isFirstCompile) {
        await open(`http://localhost:${process.env.PORT}`);
      }
    }, 2000);
    ws?.wss.on('connection', async (ws, req: any) => {
      clearTimeout(timeer);
    });
  });
