### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by ynnyh** [umijs/umi#4295]
按照快速上手打开项目后，修改.umirc.ts文件里的favicon属性无效，原有umi logo消失了但是现在的没有替换上去

**Comment by leftstick** [comment]
你的地址怎么写的？
项目结构是怎么样的？
图片放在哪里？

**Comment by ynnyh** [comment]
我在src目录下新建了个assets目录里面放了个favicon.ico，在配置里写的favicon: '/assets/favicon.ico'，结果没生效，路径里加@也没用

**Comment by leftstick** [comment]
对，这就是为啥要问题的缘故。图片放的位置不对。

放到根目录的`public`下面，配置里改成`/favicon.ico`

**Comment by ynnyh** [comment]
嗯，刚试了是可以的，请把你们文档更新一下吧，我照着文档改的，谢谢了

**Comment by leftstick** [comment]
> 嗯，刚试了是可以的，请把你们文档更新一下吧，我照着文档改的，谢谢了

文档里应该补充一下，favicon 的配置 指的是 `public` 目录。所以文档里的意思是，你可以在`public` 目录下建 `assets/favicon.ico`，然后配置里是写 `/assets/favicon.ico`

**Comment by luminous6** [comment]
在ts umi 中， 在.umirc.ts 中配置favicon 提示当前interface 没有该参数

**Comment by wildwood151** [comment]
> 在ts umi 中， 在.umirc.ts 中配置favicon 提示当前interface 没有该参数

老哥，解决了吗？

**Comment by yanugto** [comment]
> > 嗯，刚试了是可以的，请把你们文档更新一下吧，我照着文档改的，谢谢了
> 
> 文档里应该补充一下，favicon 的配置 指的是 `public` 目录。所以文档里的意思是，你可以在`public` 目录下建 `assets/favicon.ico`，然后配置里是写 `/assets/favicon.ico`

不行，试了下 还是访问 /favicon.ico 才有用呢，文件位置根目录下 public/favicon.ico

**Comment by hesetiema** [comment]
还需要nginx配置下：
`location = /favicon.ico {
  return 204;
  access_log     off;
  log_not_found  off;
}`
