### ISSUE TITLE
defineConfig中配置routes，path字段不能接受string[]类型

### ISSUE THREAD

**Issue by wisdomG** [umijs/umi#4296]
## What happens?

在.umirc.ts中修改routes配置，编辑器提示path只能是string类型，而不能是string[]类型。

但文档时说类型可以 string|string[]，是文档更新不及时吗？

![image](https://user-images.githubusercontent.com/11959301/77746526-ff8b3400-7057-11ea-8930-77fa598f6e46.png)

## 复现步骤，错误日志以及相关配置

直接安装umi，只改这一行

![image](https://user-images.githubusercontent.com/11959301/77746345-c18e1000-7057-11ea-842b-a210ae8fb40f.png)

## 相关环境信息

- **Umi 版本**：^3.0.14
- **Node 版本**：10.15.0
- **操作系统**：ubuntu16.04

**Comment by sorrycc** [comment]
Fixed.
