### ISSUE TITLE
umi3.x ts类型重新export出去，警告类型找不到

### ISSUE THREAD

**Issue by adam1985** [umijs/umi#4297]
umi3.x ts类型重新export出去，警告类型找不到

<img width="649" alt="WX20200328-222505@2x" src="https://user-images.githubusercontent.com/2756802/77825363-bb755d80-7143-11ea-9b92-9b94752ffa72.png">

复现代码仓库 https://github.com/adam1985/umi-ts-warning

## 相关环境信息

- **Umi 版本**：umi@3.0.14
- **Node 版本**：v10.16.3
- **操作系统**：mac

**Comment by vdfor** [comment]
同上，多次出现此问题，有时换台电脑也好了

**Comment by bibidu** [comment]
https://github.com/umijs/umi/issues/4042

**Comment by bibidu** [comment]
同https://github.com/umijs/umi/issues/4042

**Comment by adam1985** [comment]
问题解决了，@babel/core@7.9.0
