### ISSUE TITLE
[Feature Request] Class constructor xxx cannot be invoked without 'new'

### ISSUE THREAD

**Issue by wscart** [umijs/umi#4298]
这种一般是父类和new 这个子类的地方不在一起，比如我这次的父类在node_module里，当然也不可能挪到一起啊，然后就在

webpack里面把node_module的路径加上了

webpack.base.conf.js，见最后一行

```
{
        test: /\.ts$/,
        include: /node_modules\/@projectstorm/,
        loader: 'babel-loader',
        options: {
          presets: ['@babel/preset-env']
        }
}
```

但是在umi文档上找不到类似这个解决方案，还是来这里求助。谢谢

## 复现步骤，错误日志以及相关配置
Uncaught TypeError: Class constructor cannot be invoked without 'new'

## 相关环境信息

- **Umi 版本**：3.0.14
- **Node 版本**：v12.15.0
- **操作系统**：macos

**Comment by wscart** [comment]
添加webpack.config.js填写这个配置即可

**Comment by sorrycc** [comment]
添加啥配置？

**Comment by wscart** [comment]
{
        test: /\.ts$/,
        include: /node_modules\/@projectstorm/,
        loader: 'babel-loader',
        options: {
          presets: ['@babel/preset-env']
        }
}
是这个配置，因为node_modules引入的包需要babel转换。
