### ISSUE TITLE
TypeScript不能支持antd的按需加载

### ISSUE THREAD

**Issue by awaw00** [umijs/umi#430]
umi没有开放对loader的配置，不论是ts-loader之后再来babel-loader，还是 [ui-component-loader](https://github.com/gwuhaolin/ui-component-loader) 都没办法用，框架是否可以考虑集成typescript的按需加载功能？

**Comment by sorrycc** [comment]
typescript 按需加载需要怎么配？

**Comment by xiaohuoni** [comment]
@sorrycc 我有一个疑问，如果typescript不是按需加载的话，那umi内置了antd和antd-mobile，那不是不管有没有用，都会被引入发布包？假设我现在ui框架选的是其他的话，没有尝试过，就是突然想到这个问题

**Comment by sorrycc** [comment]
确实有这个问题。

**Comment by sorrycc** [comment]
在 umi@2 里已解决，ts 后会走 babel 。
