### ISSUE TITLE
umijs v3.x 插件无法使用，与文档描述不符！

### ISSUE THREAD

**Issue by HQ6968** [umijs/umi#4302]
希望官方完善下插件的文档，文档上说的于测试不符合。
![image](https://user-images.githubusercontent.com/4061162/77816898-abd52500-7101-11ea-9a81-21d6e93e779f.png)  无法使用
![image](https://user-images.githubusercontent.com/4061162/77816914-c7d8c680-7101-11ea-89fc-b3a455e755e2.png)
dva的这些方法， umi并没有导出，

![image](https://user-images.githubusercontent.com/4061162/77816957-19815100-7102-11ea-856a-5d99f77b218c.png)
上图为项目依赖

yarn create @umijs/umi-app 使用该命令构建的测试项目

**Comment by sorrycc** [comment]
没理解问题，图里分别贴了 plugin-model 和 plugin-dva 的使用文档，不清楚哪个没有用？

**Comment by niezw** [comment]
`
import { Effect, Reducer } from 'umi'; //报错说没有导出

已经按照文档里的插件描述，在.umirc.ts中配置开启dva
dva: {
    immer: true,
    hmr: false,
  },

我的package.json:
  "dependencies": {
    "@umijs/preset-react": "1.x",
    "@umijs/test": "^3.0.18",
    "antd": "^4.1.1",
    "lint-staged": "^10.0.7",
    "prettier": "^1.19.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "umi": "^3.0.18",
    "yorkie": "^2.0.0"
  }

`
