### ISSUE TITLE
umi3开启国际化后,国际化代码未做ES5转换

### ISSUE THREAD

**Issue by yxl2628** [umijs/umi#4303]
## What happens?

开启国际化后,国际化部分未做ES5转换

## 最小可复现仓库

只需要在.umirc.ts开启国际化,即可复现
```javascript
import { defineConfig } from 'umi';

export default defineConfig({
  routes: [
    { path: '/', component: '@/pages/index' },
  ],
  // 兼容ie
  targets: {
    ie: 11,
  },
  // 国际化
  locale: {
    default: 'zh-CN',
    antd: true,
    title: true,
  },
});
```

## 复现步骤，错误日志以及相关配置

`npm run build`之后,可以查dist目录下的umi.js,其中国际化部分,均未做转换

![](https://s1.ax1x.com/2020/03/28/GkgHgJ.png)

## 相关环境信息

- **Umi 版本**：3.0.14
- **Node 版本**：12.13.1
- **操作系统**：Ubuntu 18.04

**Comment by huangang** [comment]
https://github.com/umijs/umi/issues/4246#issuecomment-605447779
看看这个链接的解决方法，对你有没有用

**Comment by yxl2628** [comment]
> [#4246 (comment)](https://github.com/umijs/umi/issues/4246#issuecomment-605447779)
> 看看这个链接的解决方法，对你有没有用

恩,谢了,可以用,不过我们项目还没上线,我倒是没那么着急,等着官方出更新也行,就是提前提一下

**Comment by sorrycc** [comment]
在 #4246 跟进。
