### ISSUE TITLE
umi3如何进行全局初始化？

### ISSUE THREAD

**Issue by wittech** [umijs/umi#4309]
需要在umi3开始的时候进行一次全局初始化，之前在dva中有app.js，现在在umi中应该如何处理呢？

**Comment by sorrycc** [comment]
全局初始化什么？

**Comment by joesdu** [comment]
> 需要在umi3开始的时候进行一次全局初始化，之前在dva中有app.js，现在在umi中应该如何处理呢？

应该是可以在global.tsx同级目录下添加App.tsx文件来支持,我没试过,你可以试试.
