### ISSUE TITLE
How to make the specified file under src/models folder not registered

### ISSUE THREAD

**Issue by wanghairong-i** [umijs/umi#431]
Sometimes it is necessary to create a commonModel.js similar to the updateState common method.
But if I create the file in the src/models folder, the file will be automatically registered.
Because there is no necessary attribute such as namespace in the file, it will be wrong.

Hope: 
The function of files that are not registered under src/models, such as the $prefix, will not be registered: src/models/$noRegisterModel.js

题目：
如何使src/models文件夹下指定的文件不被注册

问题：
有时候是需要创建类似commonModel.js（该文件内会声明一些类似updateState公共方法），
但是如果我将该文件创建在 src/models文件夹下，该文件会被自动注册，
而因为该文件内没有namespace等必须属性，所以会报错。

期望：
提供src/models下的文件不被注册的功能，比如加上$前缀就不会被注册了：src/models/$noRegisterModel.js

**Comment by xiaohuoni** [comment]
其实，不要把这些文件放在src/models下就好了吧。约定了src/models下的model会被全局自动加载。

**Comment by sorrycc** [comment]
可以提 PR 给 umi-plugin-dva 加个 exclude 的配置项，使用时可以这样：

```js
export default {
  plugins: [
    ['umi-plugin-dva', {
      exclude: [/^$/],
    }],
  ],
};
```
