### ISSUE TITLE
title is not translated by plugin-locale

### ISSUE THREAD

**Issue by khalibloo** [umijs/umi#4310]
## What happens?

`title` in `.umirc.ts` is not translated by `plugin-locale`.

## Mini Showcase Repository(REQUIRED)

https://github.com/khalibloo/umi-title-bug

## How To Reproduce

**Steps to reproduce the behavior:**
1. Configure `locale` in `.umirc.ts` and set `locale.title` to `true`
2. Set `title` to a string ID

**Expected behavior**
1. Title should be set to the value of the string ID from your locale files

## Context

- **Umi Version**: ^3.0.14
- **Node Version**: 12.13.0
- **Platform**: Windows 10 x64

**Comment by LarryZhao0616** [comment]
same here。

anyone trying to solve this problem？ 
the docs is totally useless. https://umijs.org/config#routes

**Comment by khalibloo** [comment]
Hi @LarryZhao0616 hang in there. @ycjcl868 has been assigned to it. It's only a matter of time now ;)

n the meantime, you can work around this issue by specifying a title for each page as demonstrated here in the reproduce repo https://github.com/khalibloo/umi-title-bug/blob/c0f136ae50e79a7212ea8dcf6181c8828d89dd71/.umirc.ts#L18

The transition to version 3 was not a smooth one for the docs, I agree. But the docs are being improved and translated slowly through feedback from us, the users. Let's try to help them out by suggesting ways to improve it.

**Comment by xiaohuoni** [comment]
相同问题 https://github.com/umijs/plugins/issues/127
