### ISSUE TITLE
API能否详细一点

### ISSUE THREAD

**Issue by leninxh** [umijs/umi#4311]
路由
Link
NavLink
Prompt
withRouter
useRouter
useHistory
useLocation
useParams
useRouteMatch

你们官网的api能否稍微详细一点点咯

**Comment by joesdu** [comment]
> 路由
> Link
> NavLink
> Prompt
> withRouter
> useRouter
> useHistory
> useLocation
> useParams
> useRouteMatch
> 
> 你们官网的api能否稍微详细一点点咯

我也觉得Umi官方这个文档写的很难受,根本看不懂怎么用.🤣😂

**Comment by leftstick** [comment]
这个部分的确做了一些假设，假设了用户都已经熟悉 `react-router` 。这个部分的确可以再加强一点

**Comment by shengbeiniao** [comment]
现在不敢直接用 umi API了，原来是import Link from 'umi/link'，现在是import { Link } from 'umi'，这在升级的时候多痛苦，如果有几十万行代码，我怎么测试
