### ISSUE TITLE
[3.x] umi build 

### ISSUE THREAD

**Issue by jdreamer** [umijs/umi#4319]
刚升级到3.x
build的时候2.x的时候是每个page都会单独生成js文件
现在只生成了umi.xxxx.js和umi.xxxx.css
需要在哪里配置么？

**Comment by jdreamer** [comment]
相关的设置项，目前是这个配置
dynamicImport: { loading: '@/pages/loading' },

**Comment by sorrycc** [comment]
文档里搜 dynamicImport。

**Comment by jdreamer** [comment]
> 文档里搜 dynamicImport。

目前是这样配置的，我有一个加载页面。
dynamicImport: { loading: '@/pages/loading' },

还试过手动配置routes，没有效果。
完整的.umirc.ts配置：

import { defineConfig } from 'umi';

let base = 'localhost:8801';

export default defineConfig({
    publicPath: '/static/',
    dynamicImport: {
        loading: '@/pages/loading' ,
    },
    hash: true,
    antd: {
        dark: false,
    },
    externals: {
        "jquery": 'jQuery',
        "flickity": 'Flickity',
        "react": 'React',
        "react-dom": 'ReactDOM',
    },
    extraBabelPlugins : [
        "babel-plugin-dynamic-import-node" ,
        "babel-plugin-react-require"
    ],
    // webpack config
    proxy: {
        '/socket': {
            target: 'ws://' + base + '/socket',
            pathRewrite: { '^/socket': '' },
            ws: true,
        },
        '/favicon.ico': {
            target: 'http://' + base + '/favicon.ico',
            pathRewrite: { '^/favicon.ico': '' },
        },
        '/logout': {
            target: 'http://' + base + '/logout',
            pathRewrite: { '^/logout': '' },
        },
        '/rest': {
            target: 'http://' + base + '/rest',
            pathRewrite: { '^/rest': '' },
        },
        '/api': {
            target: 'http://' + base + '/api',
            pathRewrite: { '^/api': '' },
        },
        '/assets': {
            target: 'http://' + base + '/assets',
            pathRewrite: { '^/assets': '' },
        },
    },
    theme: {
        '@primary-color': '#EB7522',
    },
});

**Comment by jdreamer** [comment]
试出来了，build的时候，不能启用babel-plugin-dynamic-import-node这个插件。
dev模式可以加速编译。
