### ISSUE TITLE
package dva be replaced

### ISSUE THREAD

**Issue by wanghairong-i** [umijs/umi#432]
Look at [the document](https://github.com/sorrycc/blog/issues/66)：how to configure hook such as onError and initialState through the new src/dva.js.
However, when I did this operation, the error occurred in the screenshot:

看[该处文档](https://github.com/sorrycc/blog/issues/66)说：通过新建src/dva.js来如何配置 onError、initialState 等 hook，
但是，当我执行这个操作时，发生截图中错：
![image](https://user-images.githubusercontent.com/13896347/39672479-5cf9e8d2-515d-11e8-9715-2cc8869904ad.png)

**Comment by wanghairong-i** [comment]
已找到问题原因：
因为配置了tsconfig.json的baseUrl为"./src", 所以在import安装包时，会优先基于baseUrl查找。

解决方案：
```javascript
// tsconfig.json
{
  "compilerOptions": {
    // ...
    "baseUrl": "./src",
    "paths": {
      // ...
      "dva": [
        "../Users/apple/Desktop/whr/web/umi/umi-dva-user-dashboard/node_modules/_dva@2.2.3@dva/index"
      ]
    }
  }
}
```

**Comment by wanghairong-i** [comment]
虽然找到了解决方案，但很不优雅。
希望针对配置dva的onError、initialState 等 hook，umi能给出更好方案。

**Comment by sorrycc** [comment]
用 typescript 的需要额外再装个 dva 的依赖吧。

**Comment by wanghairong-i** [comment]
@sorrycc 
是指 umi-plugin-dva 吧，这个已事先装好。

目前的问题是：
新建src/dva.js来如何配置 onError、initialState 等 hook，
因为配置了tsconfig.json的baseUrl为"./src", 所以在import安装包时，

```
import { connect } from 'dva'  //此处报错
```

会优先基于baseUrl查找，然后就会报错。

**Comment by sorrycc** [comment]
不是，是 dva 依赖。
