### ISSUE TITLE
umi2.2.7开启pwa后JS加载速度非常慢

### ISSUE THREAD

**Issue by xiayu1986** [umijs/umi#4320]
版本：2.2.7
问题：开启pwa功能后打包出来的umi.js文件有988k大小，加载速度非常慢，能加载20多秒
配置：pwa: {
        workboxPluginMode: 'GenerateSW',
        workboxOptions: {
          importWorkboxFrom: 'local',
        },
        manifestOptions: {
          srcPath: 'src/manifest.json'
        }
      }

**Comment by QianDingwei** [comment]
大佬，想请教你一下，开启pwa是只需要config中配置嘛，我的问题是配置完了，但是好像servicework并没有注册，在serviceworker中console.log都没有输入，这是为啥，麻烦指教

**Comment by 539917729** [comment]
> 大佬，想请教你一下，开启pwa是只需要config中配置嘛，我的问题是配置完了，但是好像servicework并没有注册，在serviceworker中console.log都没有输入，这是为啥，麻烦指教

你是怎么解决的？遇到同样的问题
