### ISSUE TITLE
本地运行报错 Module build failed

### ISSUE THREAD

**Issue by cpu220** [umijs/umi#4321]
项目重新安装依赖后，报错
``` 
in ./src/pages/.umi/DvaContainer.js

Module build failed (from ./node_modules/_babel-loader@8.0.5@babel-loader/lib/index.js):
TypeError: Cannot read property 'file' of undefined

 @ ./node_modules/_umi-plugin-dva@1.4.0@umi-plugin-dva/lib/runtime.js 3:21-49
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/_af-webpack@1.5.3@af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js
```

* 正常的项目删除 node_modules 再重新安装后，出现该问题。所以怀疑是babel与umi的配置有冲突，但不知道package.json 应该升级哪个，将umi和babel 都升到最新依然报错。

``` json
// package.json
{
  "name": "ant-design-pro",
  "version": "2.1.1",
  "description": "An out-of-box UI solution for enterprise applications",
  "private": true,
  "scripts": {
    "start": "cross-env APP_TYPE=site umi dev",
    "build": "umi build"
  },
  "dependencies": {
    "ant-design-pro": "^2.1.1",
    "antd": "3.20.7",
    "cheerio": "1.0.0-rc.2",
    "classnames": "^2.2.6",
    "dva": "^2.4.0",
    "lodash": "^4.17.10",
    "lodash-decorators": "^6.0.0",
    "memoize-one": "^4.0.0",
    "moment": "^2.22.2",
    "path-to-regexp": "^2.4.0",
    "prop-types": "^15.5.10",
    "rc-animate": "^2.4.4",
    "react": "^16.6.3",
    "react-container-query": "^0.11.0",
    "react-document-title": "^2.0.3",
    "react-media": "^1.8.0",
    "umi-request": "^1.0.0",
    "react-monaco-editor": "0.25.1"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "cross-env": "^5.1.1",
    "cross-port-killer": "^1.0.1",
    "eslint": "^5.4.0",
    "eslint-config-airbnb": "^17.0.0",
    "eslint-config-prettier": "^3.0.1",
    "eslint-plugin-babel": "^5.3.0",
    "eslint-plugin-compat": "^2.6.2",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-markdown": "^1.0.0-beta.6",
    "eslint-plugin-react": "^7.11.1",
    "husky": "^1.2.0",
    "lint-staged": "^8.1.0",
    "prettier": "1.15.2",
    "stylelint": "^9.8.0",
    "stylelint-config-prettier": "^4.0.0",
    "stylelint-config-standard": "^18.0.0",
    "umi": "2.5.5",
    "umi-plugin-pro-block": "^1.2.0",
    "umi-plugin-react": "1.5.2",
    "react-monaco-editor": "0.25.1"
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "husky": {
    "hooks": {}
  }
}

```

## 相关环境信息

- **Umi 版本**：3.0.15
- **Node 版本**： 12.16.1
- **操作系统**：macOs 10.15.3

**Comment by sorrycc** [comment]
需要复现步骤。

**Comment by cpu220** [comment]
定位了下
node_modules/_babel-plugin-dva-hmr@0.4.1@babel-plugin-dva-hmr/lib/index.js

``` javascript
CallExpression 这个接口里 直接取了  filename = path.hub.file.opts.filename;

但是不知道为什么path.hub  是undefined
手动加了个trycatch后跑起来了
```

**Comment by xiaohuoni** [comment]
umi版本和umi-plugin-react版本不对应导致的。可以使用。
```
  "umi": "2.13.0",
   "umi-plugin-react": "1.15.6"
```
另外你i组件里面的用到了umi@3的导出。如果需要使用这些，那需要更新到umi@3

**Comment by cpu220** [comment]
我本地把版本排查了一遍，发现问题是出在哪了。
这个项目是用的19年的官方模板，用的antd3.x， 最近升了4.x ，用了官方的  @ant-design/codemod-v4 。在node_modules没有删除重新install的情况下，本地是不会发现问题的，且打包也不会出现问题。

只有当重新安装依赖的时候，才会因为package里包版本会发生本地无法启动。

**Comment by heng1025** [comment]
> [demo](https://github.com/cpu220/umiDEMO)
> 
> 复现流程：
> 
> 1. cnpm i
> 2. npm start
> 
> 定位了下 node_modules/_babel-plugin-dva-hmr@[0.4.1@babel-plugin-dva-hmr](mailto:0.4.1@babel-plugin-dva-hmr)/lib/index.js
> 
> ```js
> CallExpression 这个接口里 直接取了  filename = path.hub.file.opts.filename;
> 
> 但是不知道为什么path.hub  是undefined
> 手动加了个trycatch后跑起来了
> ```
> 
> 然后打印path
> 
> ```js
> NodePath {
>   parent: {
>     type: 'ReturnStatement',
>     argument: {
>       type: 'CallExpression',
>       callee: [Object],
>       arguments: [Array],
>       loc: undefined
>     },
>     loc: undefined
>   },
>   hub: undefined,  // 这里undefined
>   contexts: [
>     TraversalContext {
>       queue: [Array],
>       parentPath: [NodePath],
>       scope: [Scope],
>       state: undefined,
>       opts: [Object],
>       priorityQueue: []
>     }
>   ],
> ```
> 
> 基本就是官网的demo，不过是年前的，删除了 `node_modules `之后，重新安装依赖到底是哪个自动升级，导致版本挂了

用yarn 安装能正常运行，用npm 安装依赖运行就会有同样的问题 umi@2.7.7 umi-plugin-react@1.8.4
