### ISSUE TITLE
[Feature Request] 需要开发文档

### ISSUE THREAD

**Issue by SIvaCoHan** [umijs/umi#4322]
## Background

需要开发文档，介绍umijs3的整体架构，目录结构，依赖关系。

## Proposal

现在因为缺乏开发文档，阅读源码速度很慢。希望能提供一个基础的开发文档，起到地图的作用。方便其他开发者加入。

**Comment by hankaibo** [comment]
比如说，想配置dynamicImport ，去官网一看，上面说了一堆没用的，配置项就说了一个loading，其它配置项有哪些呢？

**Comment by stfenjobs** [comment]
文档确实不完善，我今天掉了好几次坑

**Comment by stfenjobs** [comment]
我是个react 新手
