### ISSUE TITLE
使用@umijs/plugin-qiankun无法加载子应用页面

### ISSUE THREAD

**Issue by Fntys** [umijs/umi#4323]
主应用配置：dev模式
![image](https://user-images.githubusercontent.com/13896710/77900685-fc3eb500-72b0-11ea-8bae-94c5a565f30b.png)
子应用配置：dev模式
![image](https://user-images.githubusercontent.com/13896710/77900931-5ccdf200-72b1-11ea-91fe-105a01425cff.png)

报错：
![image](https://user-images.githubusercontent.com/13896710/77901069-90108100-72b1-11ea-8480-44e9777b93da.png)

**Comment by Fntys** [comment]
主应用配置：dev模式
  [
    '@umijs/plugin-qiankun',
    {
      master: {
        // 注册子应用信息
        apps: [
          {
            name: 'met_sms', // 唯一 id
            entry: '//192.168.3.171:10070', // html entry
            base: '/met_sms', // app1 的路由前缀，通过这个前缀判断是否要启动该应用，通常跟子应用的 base 保持一致
          },
        ],
        jsSandbox: true, // 是否启用 js 沙箱，默认为 false
        prefetch: true, // 是否启用 prefetch 特性，默认为 true
      },
    },
  ],

**Comment by Fntys** [comment]
子应用配置：dev模式

export default {
  [['@umijs/plugin-qiankun', { slave: {} }]],
  base: '/met_sms',
  mountElementId: 'root-slave',
}

**Comment by Fntys** [comment]
报错：Uncaught (in promise) Error: Target container is not a DOM element.

**Comment by bibidu** [comment]
可以传个代码示例

**Comment by BearD01001** [comment]
一模一样的问题，子应用可以单独打开，但是在主应用中就显示空白，报错相同

**Comment by BearD01001** [comment]
找到问题原因了，主应用 HTML 入口文件中需手动添加一个与 mountElementId 相同 ID 的元素作为挂载点。如果挂载点是由主应用异步渲染的，需启用 defer 配置
