### ISSUE TITLE
配置dynamicImport后，会分成很多小模块，只要模块代码有改动就变动文件名，项目发布后，因为是单页面应用，客户不刷新页面访问这个模块时就会加载不到这个模块代码了

### ISSUE THREAD

**Issue by XSmarter** [umijs/umi#4324]
## What happens?
配置dynamicImport后，会分成很多小模块，只要模块代码有改动就变动文件名，项目发布后，因为是单页面应用，客户不刷新页面访问这个模块时就会加载不到这个模块代码了，应该怎么处理发布项目呢？头疼......

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by XSmarter** [comment]
现在项目不知道该怎么发布了，一发布改动的模块页面就一直加载中，因为用户没有刷新页面，还是访问原来的js脚本，可是那个模块脚本文件名已经变了

**Comment by leftstick** [comment]
最简单最傻瓜的方法，让后端写个接口，告诉你当前的版本号是多少。

前端写个定时器，每隔一段时间发一次这个接口，一旦发现获取到的版本号和之前保存的不一致，就给用户弹出一个提示框，说有新版本发布，请用户刷新。

当然 这种发心跳的方式不高级，你也可以试试web socket之类的服务器端推送的方案，总之一句话。

就是前端要能侦测到服务器有了新的发布，并提示用户刷新

**Comment by XSmarter** [comment]
我看了下nginx没有配置缓存，不行配置一下缓存，至少不会出现一直加载中，加载不到模块代码

**Comment by sorrycc** [comment]
发布策略问题，和 Umi 没啥关系。启用 hash: true 然后服务端不删文件就能解决了吧，或者是上 cdn。

**Comment by Evanna51** [comment]
不知道这位仁兄如何解决的，最好的方案当时是服务端不删除文件；
不过我们当时是用sw，每次加载资源前去请求后端资源是否存在，是否需要更新。。。
