### ISSUE TITLE
[Feature Request]希望能自动添加initial chunks

### ISSUE THREAD

**Issue by LeoHuiyi** [umijs/umi#4330]
## Background

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L273
我想实现这样的splitChunks

## Proposal

希望能自动添加initial chunks

看了下html-webpack-plugin代码
https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L606
是把compilation.entrypoints 中每个entryPointFiles 的css，js，mjs自动加入assets

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
