### ISSUE TITLE
router is undefined

### ISSUE THREAD

**Issue by andyliu-417** [umijs/umi#4332]
I add search list block as below,
![image](https://user-images.githubusercontent.com/39243920/77984170-d5977300-72de-11ea-94aa-520f2f488de1.png)

when i change tabs, it reports:
Uncaught TypeError: Cannot read property 'push' of undefined
then I log router, it is undefined indeed.

import {connect, router} from 'umi';
this line is unchanged from block.
![image](https://user-images.githubusercontent.com/39243920/77983968-52761d00-72de-11ea-86f3-749a92de1413.png)

Also, I have warnings:
![image](https://user-images.githubusercontent.com/39243920/77984300-3161fc00-72df-11ea-8b6a-08c6f79ec195.png)

## Context
"umi": "^3.0.14",
mac pro

**Comment by joesdu** [comment]
router换成了history了.

**Comment by joesdu** [comment]
> I add search list block as below,
> ![image](https://user-images.githubusercontent.com/39243920/77984170-d5977300-72de-11ea-94aa-520f2f488de1.png)
> 
> when i change tabs, it reports:
> Uncaught TypeError: Cannot read property 'push' of undefined
> then I log router, it is undefined indeed.
> 
> import {connect, router} from 'umi';
> this line is unchanged from block.
> ![image](https://user-images.githubusercontent.com/39243920/77983968-52761d00-72de-11ea-86f3-749a92de1413.png)
> 
> ## Context
> "umi": "^3.0.14",
> mac pro

router换成了history了.

**Comment by andyliu-417** [comment]
ok thanks!
but where can i find the change like this?

**Comment by joesdu** [comment]
> ok thanks!
> but where can i find the change like this?

https://umijs.org/zh-CN/docs/upgrade-to-umi-3#%E9%85%8D%E7%BD%AE%E5%B1%82
