### ISSUE TITLE
config如何引入其他工作区目录？

### ISSUE THREAD

**Issue by six-666** [umijs/umi#4333]
配置别名，下面test并不在当前工作区。 把test目录移到当前工作区就没问题。 但是我需要这个需求，因为有一些子模块是共用的。
```
alias: {
    '@test': path.resolve(__dirname, '../../../../test'),
  }
```

**Comment by sorrycc** [comment]
有 PR 了，在 https://github.com/umijs/umi/pull/4327 跟进。

**Comment by six-666** [comment]
@sorrycc  请问什么时候可以修复，我用的是2.x umi。

**Comment by sorrycc** [comment]
2.x 的不支持。

**Comment by miaozilong** [comment]
无语了  试了一下 3终于能成了  2.x不支持,不知道升级复杂不

**Comment by miaozilong** [comment]
> @sorrycc 请问什么时候可以修复，我用的是2.x umi。

你解决了吗
