### ISSUE TITLE
history.redirectTo is not a function[3.0.16]

### ISSUE THREAD

**Issue by mov1er** [umijs/umi#4334]
## What happens?

history.redirectTo is not a function

## 最小可复现仓库

import { history } from 'umi';

export function render(oldRender) {
  fetch('/api/auth').then(auth => {
    if (auth.isLogin) { oldRender() }
    else { history.redirectTo('/login'); }
  });
}

## 复现步骤，错误日志以及相关配置

参照umi官方文档配置  [https://umijs.org/zh-CN/docs/runtime-config#renderoldrender-function](https://umijs.org/zh-CN/docs/runtime-config#renderoldrender-function)

## 相关环境信息

- **Umi 版本**：3.0.16
- **Node 版本**：v10.16.0
- **操作系统**：macOS 10.15.3

**Comment by bogutski** [comment]
Try to use history.push('/login');

**Comment by sorrycc** [comment]
文档写错了，换成 history.push 或 history.replace。
