### ISSUE TITLE
[Feature Request] 配置 chainWebpack 项支持异步函数

### ISSUE THREAD

**Issue by shengliangli** [umijs/umi#4336]
## Background

需要根据某些异步操作的结果来对webpack 进行修改

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

希望 chainWebpack 配置项支持异步函数或者 promise 对象

**Comment by sorrycc** [comment]
举个具体的异步场景呢？

**Comment by shengliangli** [comment]
场景：我的 umi 工程项目在启动的时候，先通过异步的方式检查在端口 9000-9010的范围内是否已经启动了开发助手服务（类似于 umi ui 的一个助手服务），如果检测到有启动，那么就通过配置 webpack 的插件把检测到的端口号设置为全局变量。这样，我的工程启动后，就可以知道助手服务是否启动，以及启动的端口号。

多谢
