### ISSUE TITLE
hd

### ISSUE THREAD

**Issue by ynnyh** [umijs/umi#4338]
现在的版本怎么开启hd呢，或者有没有什么替代方案啊

**Comment by xiaohuoni** [comment]
可以试试[@alitajs/hd](https://www.npmjs.com/package/@alitajs/hd) 是先把@umijs/plugin-hd 发的一个包。不知道umi@3的移动端方案，走到哪了。

**Comment by liyuewen** [comment]
请问你解决了么，能说下么，我也遇到了这个问题

**Comment by xiaohuoni** [comment]
@liyuewen 
yarn add @alitajs/hd
```
export default {
  plugins: ['@alitajs/hd'],
  hd: true,
};
```

**Comment by bruintong** [comment]
@xiaohuoni 请问有没有遇到 Umijs 3.x 开启hd，dev环境是有效的，生产环境不生效的问题？主要是html标签的缺失font-size样式

**Comment by bruintong** [comment]
> @xiaohuoni 请问有没有遇到 Umijs 3.x 开启hd，dev环境是有效的，生产环境不生效的问题？主要是html标签的缺失font-size样式

不是@alitajs/hd的问题，是参考文档Express服务器框架写的，请问你采用的是这种方式吗？

**Comment by bruintong** [comment]
不是@alitajs/hd的问题，我开启了ssr，采用Express服务器框架的代码写的
`
const express = require('express');
const Stream = require('stream');
const app = express();
const port = process.env.PORT || 3000;
app.use(async (req, res) => {
  const render = require('../dist/umi.server');
  res.setHeader('Content-Type', 'text/html');
  const context = {};
  const { html, error, rootContainer } = await render({
    path: req.url,
    context,
  });
  if (html instanceof Stream) {
    html.pipe(res);
    html.on('end', function() {
      res.end();
    });
  } else {
    res.send(html);
  }
});
app.listen(port, function() {
  console.log(`app is running at port ${port}.`);
});
`
我是哪里写的有问题吗？

**Comment by bruintong** [comment]
不是@alitajs/hd的问题，我开启了ssr，采用Express服务器框架的代码写的
`const express = require('express');
const Stream = require('stream');
const app = express();
const port = process.env.PORT || 3000;

app.use(async (req, res) => {
  const render = require('../dist/umi.server');
  res.setHeader('Content-Type', 'text/html');
  const context = {};
  const { html, error, rootContainer } = await render({
    path: req.url,
    context,
  });
  if (html instanceof Stream) {
    html.pipe(res);
    html.on('end', function() {
      res.end();
    });
  } else {
    res.send(html);
  }
});

app.listen(port, function() {
  console.log(`app is running at port ${port}.`);
});
`
我是哪里写的有问题吗？

**Comment by xiaohuoni** [comment]
@bruintong ssr的问题可以另开一个issues。感觉与这个问题无关。ssr的要问问宜鑫
