### ISSUE TITLE
[Feature Request] support preload attribute for <link>

### ISSUE THREAD

**Issue by khalibloo** [umijs/umi#4340]
## Background

There doesn't appear to be any way to add `rel="preload"` to `<link>`s. `preload-webpack-plugin` only works with `html-webpack-plugin`, and so does not work with `umi`.

## Proposal

This seems to me like a feature that should be supported out-of-the-box. Or instructions for this should be provided in the documentation.

**Comment by realeve** [comment]
@sorrycc  什么时候能有这功能啊

**Comment by Leonewu** [comment]
蹲

**Comment by tanyplzu** [comment]
+1

**Comment by GODOFZHZ** [comment]
咋弄啊

**Comment by charanjit-singh** [comment]
+1
