### ISSUE TITLE
import {Effect,Reducer} from 'umi' has no exported member 'Reducer' 'Effect'

### ISSUE THREAD

**Issue by frmachao** [umijs/umi#4341]
## What happens?
import {Effect,Reducer} from 'umi' has no exported member 'Reducer' 'Effect'
问题描述：import umi 上没有 `Reducer`和`Effect`
tsconfig中已经配置了"@@/*": ["src/.umi/*"]
## package.json中的依赖版本：
 "@umijs/preset-react": "1.x",
 "umi": "^3.0.16",
## umi配置：  
dva: {
    hmr: true,
  },
![](https://tva1.sinaimg.cn/large/005u1oUhgy1gddg9vederj310104zq3z.jpg)

**Comment by xiaohuoni** [comment]
https://github.com/zhangminggeek/react-template/blob/e141f7e087ad353e4538c50ee4d351c42c0bb09b/src/model/user.ts#L1
可以的，是不是没有运行？

**Comment by frmachao** [comment]
> 

抱歉,我的项目是运行的，执行了`umi dev`，但是它不能正常工作 终端输出`"export 'connect' was not found in 'umi'`等信息，并且项目依赖也已经正常安装
[https://github.com/frmachao/webSite/blob/master/front/src/layouts/client-layout/index.tsx](https://github.com/frmachao/webSite/blob/master/front/src/layouts/client-layout/index.tsx)
![005u1oUhgy1gdf95dyxr2j30i307nmxt](https://tva1.sinaimg.cn/large/005u1oUhgy1gdf95dyxr2j30i307nmxt.jpg)
![005u1oUhgy1gdf98a1hhkj309x0gy0tx](https://tva1.sinaimg.cn/large/005u1oUhgy1gdf98a1hhkj309x0gy0tx.jpg)

**请reopen这个issues**

**Comment by sorrycc** [comment]
给可复现仓库。

**Comment by frmachao** [comment]
> 

[https://github.com/frmachao/umi-issues/blob/master/src/models/index.ts](https://github.com/frmachao/umi-issues/blob/master/src/models/index.ts)

感谢您的回复，当我重建了一个干净的`umi`工程后，发现它是可以正常工作的，这个`issues`应当被关闭！！

**Comment by Vincent-X** [comment]
只有在models/下有model export了，才会在.umi/下出现插件，只写配置项dva:{}不会触发编译。

**Comment by abcox** [comment]
I am unclear on the resolution here.  I have the same thing in my global.ts.  Can't resolve..

import { Subscription, Reducer, Effect } from 'umi';

I went looking for those types, and could not find them, so maybe there is a setup issue.  Should I be refreshing the node_modules?  How?

THanks

**Comment by abcox** [comment]
> https://github.com/zhangminggeek/react-template/blob/e141f7e087ad353e4538c50ee4d351c42c0bb09b/src/model/user.ts#L1
> Yes, is it not running?

Did you get this working?

It seems I need to import these from different libs, like:
import { Reducer } from 'redux';
import { Subscription, Effect } from 'dva';

Instead of the way the example has it, like:
import { Subscription, Reducer, Effect } from 'umi';

Where in the umi or antd docs is this discussed?

Thanks

**Comment by HDU-blank** [comment]
> > https://github.com/zhangminggeek/react-template/blob/e141f7e087ad353e4538c50ee4d351c42c0bb09b/src/model/user.ts#L1
> > Yes, is it not running?
> 
> Did you get this working?
> 
> It seems I need to import these from different libs, like:
> import { Reducer } from 'redux';
> import { Subscription, Effect } from 'dva';
> 
> Instead of the way the example has it, like:
> import { Subscription, Reducer, Effect } from 'umi';
> 
> Where in the umi or antd docs is this discussed?
> 
> Thanks

I encountered the same situation as you, have you solved it?

**Comment by lsaint** [comment]
我也遇到类似情况，运行是没问题的，但编辑器提示(ts language server)has no exported member 'Reducer' xxxx等等， 除了新建工程有没其他办法？

**Comment by zhangxiaoshang** [comment]
我也遇到了这个问题
删除node_modules .umi文件夹 重新yarn反复几次就好了

**Comment by Dabada** [comment]
When looking into src/.umi I found that plugin-dva is missing. So, to force umi to load plugin, I set 

`dva{
  ...
  skipModelValidate:true
}`

within ./config/config.ts
Now it works !

**Comment by wfk007** [comment]
I solved it by `command+Q` the vscode and reopen it again

**Comment by HeroMeiKong** [comment]
现在通过umi 3.2.4 新建一个项目，就会这样啊，头疼

**Comment by fancygit** [comment]
> 只有在models/下有model export了，才会在.umi/下出现插件。
> 
> 只写配置项`dva:{}`不会触发编译。

export SomeModel makes it right, thx a lot

**Comment by superbogy** [comment]
Why close this?.  I spent a long time to resolve this issue. it  reproduces when the `.umirc` and `config` folder exists at the same time.
