### ISSUE TITLE
启动项目的时候显示错误的 umi ui 端口号

### ISSUE THREAD

**Issue by shengliangli** [umijs/umi#4346]
## What happens?

执行 umi dev 的时候，显示 umi ui 的启动端口号错误

$ umi dev
�🚀 Starting Umi UI using umi@3.0.16.
�🌈 Umi UI mini Ready on port 30

Starting the development server...

实际上的端口号是 3000，但是显示成30 了

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/78095127-cdd3ed80-7408-11ea-9809-e3edd193c0f8.png)

神奇

**Comment by xiaohuoni** [comment]
> ![image](https://user-images.githubusercontent.com/13595509/78095127-cdd3ed80-7408-11ea-9809-e3edd193c0f8.png)
> 
> 神奇

多加一个点吧`Umi UI mini Ready on port 3000.`

**Comment by shengliangli** [comment]
@ycjcl868 升级了最新版本的 @umijs/preset-ui （2.1.9）和 umi （3.1.0），现在现实的端口号好了一点点：）
$ umi dev
�🚀 Starting Umi UI using umi@3.1.0.
�🌈 Umi UI mini Ready on port 300
Starting the development server...

30 变成了300 ，什么鬼？
