### ISSUE TITLE
[Feature Request] 项目启动后是否能够不把项目的访问url 放到系统的剪切板中

### ISSUE THREAD

**Issue by shengliangli** [umijs/umi#4348]
## Background

umi dev 命令执行后，umi 会把项目的访问地址url 放到系统的剪切板中，这是一个贴心的小特征，但是也会在某些时候造成困扰。比如，我正在调整 .umirc.js，umi 会检测到配置文件变更，然后帮助我自动重启服务，这很好，但是由于每次重新启动项目，umi 都会把我的项目访问url放到剪切板中，打乱了工作节奏，造成困扰。

比如：我刚从网上拷贝了一段代码，准备粘贴到项目中，但是粘贴的时候发现变成了：

http://localhost:8000

:)

## Proposal

希望可以不再自动把项目的访问地址url 放到系统的剪切板中，这不会给用户造成任何的不便，同时可以消除困扰。或者，如果还是想保留这一特征的话，能否只是在第一次启动的时候才修改剪贴板内容，在检测到配置文件变更后导致的重新启动服务的情况下，不再把访问地址放到剪贴板里面。

thx

**Comment by stfenjobs** [comment]
真的这样吗， 希望可以不要这样做

**Comment by stfenjobs** [comment]
我刚才测试了，最新的版本，还是会胡乱修改剪贴板， 希望可以 删除这个特性 

我是按照官方的方法弄的

![image](https://user-images.githubusercontent.com/6580897/82754685-333ccd00-9e01-11ea-8b27-4d659d903b76.png)


然后我的剪贴板就变成了  http://localhost:8000/

**Comment by tsinglemon** [comment]
就在刚刚我把工作区没提交的代码粘贴在剪切板上，然后用git重置该文件并启动项目，
结果继续粘贴时已经变成 http://localhost:8000/ 了，
而且由于这个文件被 `git reset --hard`，所以之前的代码也随着永远消失了

**Comment by xxxxxMiss** [comment]
为啥不再启动完直接打开浏览器

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
