### ISSUE TITLE
执行 yarn prettier  报错

### ISSUE THREAD

**Issue by tristanhou** [umijs/umi#4349]
## What happens?

根目录执行 `yarn prettier` 报错：
No files matching the pattern were found: "'**/*.{js,jsx,tsx,ts,less,md,json}'".

### before in package.json scripts 
"prettier": "prettier --write '**/*.{js,jsx,tsx,ts,less,md,json}'"

### after in package.json scripts 
"prettier": "prettier --write **/*.{js,jsx,tsx,ts,less,md,json}"

## Context

- **Umi Version**: umi@3.0.16
- **Node Version**: v12.16.1
- **Platform**: win7

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/78095484-b0535380-7409-11ea-932e-28b1fe6d742c.png)

mac 下加 `'` 没发现问题，可能是 windows 下的问题，另外加不加 `'` 我发现文件覆盖范围不同。

**Comment by leason-wan** [comment]
建议prettier通过eslint插件整合在一起
