### ISSUE TITLE
.umirc.ts里面不支持引入别名路径

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#4351]
## What happens?
在.umirc.ts中 导入@/modules 这种路径会报 can not found @/modules

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by xiaohuoni** [comment]
是不支持的。
