### ISSUE TITLE
qiankun在生产环境下加载资源的路径有点问题

### ISSUE THREAD

**Issue by MrXujiang** [umijs/umi#4352]
在开发环境下测试乾坤没有任何问题,打包后由于静态资源上传到cdn上的,所以publicPath:路径配置的是cdn路径. 打包运行测试的时候发现一部分资源是走cdn了, 但是子系统的vender.js还是localhost
![image](https://user-images.githubusercontent.com/28833634/78096020-21473b00-740b-11ea-9e6e-d34227cf4de5.png)

## Context

- **使用Umi 2**:
- **Node 10.16**:
- **mac**:

**Comment by iplaces** [comment]
@MrXujiang  遇到了相同的问题，你这个问题解决了吗

**Comment by YaleWan** [comment]
也同样遇到这个问题，vendors似乎不走cdn

**Comment by hu-ke** [comment]
+1，请问有知道如何解决这个问题的同学吗？

**Comment by hu-ke** [comment]
publicPath指定的是静态资源的路径，但是vendor的加载是动态加载。需要开启webpack的runtimePublicPath，webpack指定了一个全局变量`__webpack_public_path__`来指定动态加载路径：https://webpack.js.org/guides/public-path/

**Comment by coderew** [comment]
请问解决了吗？

**Comment by wohaiwo** [comment]
umi 3.x 解决方案 
1.入口app.js 头部第一行 引入
```
import './public-path'  // 名字自己取
```
2. 新增一个public-path.js 文件
```
__webpack_public_path__ = PUBLICPATH  //  PUBLICPATH 是config.js define 里面写入的全局变量，需要跟着不同的环境配置下，跟着自己的业务走 
```
3. config.js 文件 
```
let publicPathUrl = isDev ? '/' : 'https://cdn.xxxx.com'
{
publicPath: , publicPathUrl// 对应的
dynamicImport: {},
define: {
  PUBLICPATH: publicPathUrl
 }
}
```
