### ISSUE TITLE
[Feature Request] SSR预期是什么时候支持上

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#4357]
## Background
SSR预期是什么时候支持上

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by stillyu** [comment]
同样需要SSR

**Comment by heynext** [comment]
+1 请问 umi3 有没有预期支持的时间呢？

**Comment by ClearSeve** [comment]
+1 请问 umi3 有没有预期支持的时间呢？

**Comment by xiexingen** [comment]
这个真的比较重要

**Comment by ClearSeve** [comment]
> 这个真的比较重要

你有没有试过用版本2, 版本2的可以实现ssr, 但是标题会出现问题

**Comment by qingxiao** [comment]
> 
> 
> > 这个真的比较重要
> 
> 你有没有试过用版本2, 版本2的可以实现ssr, 但是标题会出现问题

现在在用@2.x的ssr
- `Layout.getInitialProps`  函数只在服务端渲染才执行，并且和`page.getInitialProps` 使用`Promise.all`并行获取数据，实现不了在`layout.getInitialProps(ctx)`  获取全局数据，修改ctx.context，然后在`page.getInitialProps(ctx)`  中使用ctx.context
- 前端渲染/切换路由只执行当然路由的page.getInitialProps(ctx) ，更没有ctx.context
- app中的modifyInitialProps，功能又太单一，获取不到node-server的req，也不支持异步。
-------
我看@3.2.0-beta.1支持app中写全局InitialProps了，赞，不知道能不能直接迁移使用
