### ISSUE TITLE
plugin-locale imports not working in tests

### ISSUE THREAD

**Issue by khalibloo** [umijs/umi#4358]
## What happens?

Imports from `plugin-locale` are not available when running unit tests. In my case, I'm importing `getIntl` from `umi` in a `utils.ts` file (not a react component).
The import works when I run or build the app, but fails when running tests. It shows the following error.
```
TypeError: (0 , _umi.getIntl) is not a function
```

## Mini Showcase Repository (REQUIRED)

https://github.com/khalibloo/umi-intl-bug

## How To Reproduce

**Steps to reproduce the behavior:**
1. Import `getIntl` and use it in a simple function
2. Write a test for the function and run the test

**Expected behavior**
1. The import should work in the test environment

## Example
```ts
// utils.ts
import { getIntl } from "umi";

export const formatPrice = (currency: string, amount: number) => {
  const intl = getIntl();
  return intl.formatNumber(amount, {
    style: "currency",
    currency,
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
};
```
```ts
// utils.test.ts
import { formatPrice } from "./utils";

describe("formatPrice tests", () => {
  test("(USD, 30) should return $30.00", () => {
    expect(formatPrice("USD", 30)).toEqual("$30.00");
  });
});
```

## Context

- **Umi Version**: 3.0.16
- **Node Version**: 12.13.0
- **Platform**: Windows 10 x64

**Comment by wind13** [comment]
Same problem. Any ideas?

**Comment by AmagiDDmxh** [comment]
同问，已经4个月过去了，还是得不到回复

**Comment by wadezhan** [comment]
可以通过手动初始化国际化预研包，在测试的Reac组件外包裹_LocaleContainer组件，从而在 umi 实现组件级单元测试：

以下实例基于 umi@3.3.5 版本测试验证：

jest.config.js
```js
module.exports = {
  // ...
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@@/(.*)$': '<rootDir>/src/.umi/$1',
  },
};
```

src/pages/404.tsx
```ts
import React from 'react';
import { history, useIntl } from 'umi';
import { Button, Result } from 'antd';

const NoFoundPage = props => {
  const { formatMessage } = useIntl();
  return (
    <Result
      status="404"
      title="404"
      subTitle={formatMessage({ id: 'component.404.text' })}
      extra={
        <Button type="primary" onClick={() => history.push('/')}>
          {formatMessage({ id: 'component.404.button' })}
        </Button>
      }
    />
  );
};

export default NoFoundPage;
```

src/pages/404.test.tsx
```ts
import React from 'react';
import TestRenderer from 'react-test-renderer';
import { setIntl } from '@@/plugin-locale/localeExports';
import { _LocaleContainer as LocaleContainer } from '@@/plugin-locale/locale';
import NoFoundPage from './404';

describe('NoFoundPage Component Test', () => {
  beforeAll(() => {
    setIntl('zh-CN');
  });

  it('NoFoundPage render ok', () => {
    const testRenderer = TestRenderer.create(
      <LocaleContainer>
        <NoFoundPage />
      </LocaleContainer>,
    );
    expect(testRenderer.toJSON()).toMatchSnapshot();
  });
});
```

**Comment by michaelmaosynttro** [comment]
> 后面找到解决方法，`umi` 依赖于浏览器运行时和其他状态，所以单元测试里不能生效。
> 
> Since `umi` `getIntl` library rely on browser runtime and other state, using it with unit testing would possibly cause problem and crash.

請問解決方法是什麼呢?

**Comment by michaelmaosynttro** [comment]
> 可以通过手动初始化国际化语言包，在测试的Reac组件外包裹 _LocaleContainer 组件，从而在 umi 实现组件级单元测试：
> 
> 以下实例基于 umi@3.3.5 版本测试验证：
> 
> jest.config.js
> 
> ```js
> module.exports = {
>   // ...
>   moduleNameMapper: {
>     '^@/(.*)$': '<rootDir>/src/$1',
>     '^@@/(.*)$': '<rootDir>/src/.umi/$1',
>   },
> };
> ```
> 
> src/pages/404.tsx
> 
> ```ts
> import React from 'react';
> import { history, useIntl } from 'umi';
> import { Button, Result } from 'antd';
> 
> const NoFoundPage = props => {
>   const { formatMessage } = useIntl();
>   return (
>     <Result
>       status="404"
>       title="404"
>       subTitle={formatMessage({ id: 'component.404.text' })}
>       extra={
>         <Button type="primary" onClick={() => history.push('/')}>
>           {formatMessage({ id: 'component.404.button' })}
>         </Button>
>       }
>     />
>   );
> };
> 
> export default NoFoundPage;
> ```
> 
> src/pages/404.test.tsx
> 
> ```ts
> import React from 'react';
> import TestRenderer from 'react-test-renderer';
> import { setIntl } from '@@/plugin-locale/localeExports';
> import { _LocaleContainer as LocaleContainer } from '@@/plugin-locale/locale';
> import NoFoundPage from './404';
> 
> describe('NoFoundPage Component Test', () => {
>   beforeAll(() => {
>     setIntl('zh-CN');
>   });
> 
>   it('NoFoundPage render ok', () => {
>     const testRenderer = TestRenderer.create(
>       <LocaleContainer>
>         <NoFoundPage />
>       </LocaleContainer>,
>     );
>     expect(testRenderer.toJSON()).toMatchSnapshot();
>   });
> });
> ```
> 
> 测试结果如下：
> 
> ```shell
> $ npm run test -- src/pages/404.test.tsx
> 
> > ant-design-pro@1.0.0 test pcmgr-client
> > umi test "src/pages/404.test.tsx"
> 
>  PASS  src/pages/404.test.tsx (8.675s)
>   NoFoundPage Component Test
>     √ NoFoundPage render ok (29ms)
> 
> Test Suites: 1 passed, 1 total
> Tests:       1 passed, 1 total
> Snapshots:   1 passed, 1 total
> Time:        10.127s, estimated 65s
> Ran all test suites matching /src\\pages\\404.test.tsx/i.
> ```

我在這一段就直接報錯了

``` import NoFoundPage from './404'; ```

這個解法對我不起作用

**Comment by chenEdgar** [comment]
> 可以通过手动初始化国际化语言包，在测试的Reac组件外包裹 _LocaleContainer 组件，从而在 umi 实现组件级单元测试：
> 
> 以下实例基于 umi@3.3.5 版本测试验证：
> 
> jest.config.js
> 
> ```js
> module.exports = {
>   // ...
>   moduleNameMapper: {
>     '^@/(.*)$': '<rootDir>/src/$1',
>     '^@@/(.*)$': '<rootDir>/src/.umi/$1',
>   },
> };
> ```
> 
> src/pages/404.tsx
> 
> ```ts
> import React from 'react';
> import { history, useIntl } from 'umi';
> import { Button, Result } from 'antd';
> 
> const NoFoundPage = props => {
>   const { formatMessage } = useIntl();
>   return (
>     <Result
>       status="404"
>       title="404"
>       subTitle={formatMessage({ id: 'component.404.text' })}
>       extra={
>         <Button type="primary" onClick={() => history.push('/')}>
>           {formatMessage({ id: 'component.404.button' })}
>         </Button>
>       }
>     />
>   );
> };
> 
> export default NoFoundPage;
> ```
> 
> src/pages/404.test.tsx
> 
> ```ts
> import React from 'react';
> import TestRenderer from 'react-test-renderer';
> import { setIntl } from '@@/plugin-locale/localeExports';
> import { _LocaleContainer as LocaleContainer } from '@@/plugin-locale/locale';
> import NoFoundPage from './404';
> 
> describe('NoFoundPage Component Test', () => {
>   beforeAll(() => {
>     setIntl('zh-CN');
>   });
> 
>   it('NoFoundPage render ok', () => {
>     const testRenderer = TestRenderer.create(
>       <LocaleContainer>
>         <NoFoundPage />
>       </LocaleContainer>,
>     );
>     expect(testRenderer.toJSON()).toMatchSnapshot();
>   });
> });
> ```
> 
> 测试结果如下：
> 
> ```shell
> $ npm run test -- src/pages/404.test.tsx
> 
> > ant-design-pro@1.0.0 test pcmgr-client
> > umi test "src/pages/404.test.tsx"
> 
>  PASS  src/pages/404.test.tsx (8.675s)
>   NoFoundPage Component Test
>     √ NoFoundPage render ok (29ms)
> 
> Test Suites: 1 passed, 1 total
> Tests:       1 passed, 1 total
> Snapshots:   1 passed, 1 total
> Time:        10.127s, estimated 65s
> Ran all test suites matching /src\\pages\\404.test.tsx/i.
> ```

用3.3.5版本验证后不生效
https://github.com/umijs/umi/issues/4358#issuecomment-761808717

**Comment by chenEdgar** [comment]
> 可以通过手动初始化国际化语言包，在测试的Reac组件外包裹 _LocaleContainer 组件，从而在 umi 实现组件级单元测试：
> 
> 以下实例基于 umi@3.3.5 版本测试验证：
> 
> jest.config.js
> 
> ```js
> module.exports = {
>   // ...
>   moduleNameMapper: {
>     '^@/(.*)$': '<rootDir>/src/$1',
>     '^@@/(.*)$': '<rootDir>/src/.umi/$1',
>   },
> };
> ```
> 
> src/pages/404.tsx
> 
> ```ts
> import React from 'react';
> import { history, useIntl } from 'umi';
> import { Button, Result } from 'antd';
> 
> const NoFoundPage = props => {
>   const { formatMessage } = useIntl();
>   return (
>     <Result
>       status="404"
>       title="404"
>       subTitle={formatMessage({ id: 'component.404.text' })}
>       extra={
>         <Button type="primary" onClick={() => history.push('/')}>
>           {formatMessage({ id: 'component.404.button' })}
>         </Button>
>       }
>     />
>   );
> };
> 
> export default NoFoundPage;
> ```
> 
> src/pages/404.test.tsx
> 
> ```ts
> import React from 'react';
> import TestRenderer from 'react-test-renderer';
> import { setIntl } from '@@/plugin-locale/localeExports';
> import { _LocaleContainer as LocaleContainer } from '@@/plugin-locale/locale';
> import NoFoundPage from './404';
> 
> describe('NoFoundPage Component Test', () => {
>   beforeAll(() => {
>     setIntl('zh-CN');
>   });
> 
>   it('NoFoundPage render ok', () => {
>     const testRenderer = TestRenderer.create(
>       <LocaleContainer>
>         <NoFoundPage />
>       </LocaleContainer>,
>     );
>     expect(testRenderer.toJSON()).toMatchSnapshot();
>   });
> });
> ```
> 
> 测试结果如下：
> 
> ```shell
> $ npm run test -- src/pages/404.test.tsx
> 
> > ant-design-pro@1.0.0 test pcmgr-client
> > umi test "src/pages/404.test.tsx"
> 
>  PASS  src/pages/404.test.tsx (8.675s)
>   NoFoundPage Component Test
>     √ NoFoundPage render ok (29ms)
> 
> Test Suites: 1 passed, 1 total
> Tests:       1 passed, 1 total
> Snapshots:   1 passed, 1 total
> Time:        10.127s, estimated 65s
> Ran all test suites matching /src\\pages\\404.test.tsx/i.
> ```

参考配置后，执行仍然是报错
![image](https://user-images.githubusercontent.com/12596622/117534910-f96ed180-b025-11eb-9056-b6559ba0588a.png)

**Comment by rzp1** [comment]
> > 可以通过手动初始化国际化语言包，在测试的Reac组件外包裹 _LocaleContainer 组件，从而在 umi 实现组件级单元测试：
> > 以下实例基于 umi@3.3.5 版本测试验证：
> > jest.config.js
> > ```js
> > module.exports = {
> >   // ...
> >   moduleNameMapper: {
> >     '^@/(.*)$': '<rootDir>/src/$1',
> >     '^@@/(.*)$': '<rootDir>/src/.umi/$1',
> >   },
> > };
> > ```
> > 
> > 
> > src/pages/404.tsx
> > ```ts
> > import React from 'react';
> > import { history, useIntl } from 'umi';
> > import { Button, Result } from 'antd';
> > 
> > const NoFoundPage = props => {
> >   const { formatMessage } = useIntl();
> >   return (
> >     <Result
> >       status="404"
> >       title="404"
> >       subTitle={formatMessage({ id: 'component.404.text' })}
> >       extra={
> >         <Button type="primary" onClick={() => history.push('/')}>
> >           {formatMessage({ id: 'component.404.button' })}
> >         </Button>
> >       }
> >     />
> >   );
> > };
> > 
> > export default NoFoundPage;
> > ```
> > 
> > 
> > src/pages/404.test.tsx
> > ```ts
> > import React from 'react';
> > import TestRenderer from 'react-test-renderer';
> > import { setIntl } from '@@/plugin-locale/localeExports';
> > import { _LocaleContainer as LocaleContainer } from '@@/plugin-locale/locale';
> > import NoFoundPage from './404';
> > 
> > describe('NoFoundPage Component Test', () => {
> >   beforeAll(() => {
> >     setIntl('zh-CN');
> >   });
> > 
> >   it('NoFoundPage render ok', () => {
> >     const testRenderer = TestRenderer.create(
> >       <LocaleContainer>
> >         <NoFoundPage />
> >       </LocaleContainer>,
> >     );
> >     expect(testRenderer.toJSON()).toMatchSnapshot();
> >   });
> > });
> > ```
> > 
> > 
> > 测试结果如下：
> > ```shell
> > $ npm run test -- src/pages/404.test.tsx
> > 
> > > ant-design-pro@1.0.0 test pcmgr-client
> > > umi test "src/pages/404.test.tsx"
> > 
> >  PASS  src/pages/404.test.tsx (8.675s)
> >   NoFoundPage Component Test
> >     √ NoFoundPage render ok (29ms)
> > 
> > Test Suites: 1 passed, 1 total
> > Tests:       1 passed, 1 total
> > Snapshots:   1 passed, 1 total
> > Time:        10.127s, estimated 65s
> > Ran all test suites matching /src\\pages\\404.test.tsx/i.
> > ```
> 
> 参考配置后，�执行仍然是报错
> ![image](https://user-images.githubusercontent.com/12596622/117534910-f96ed180-b025-11eb-9056-b6559ba0588a.png)

+1 @sorrycc 大佬，这个如何解决

**Comment by tc9011** [comment]
如果 mock useIntl，可以参考：
```typescript
jest.mock('umi', () => ({
  useIntl: () => ({
    formatMessage: (msg: { id: string }) => msg.id,
  }),
}))
```
