### ISSUE TITLE
Resource path problem when useing "yarn build"

### ISSUE THREAD

**Issue by keunoklim** [umijs/umi#4359]
## What happens?

When I executed "yarn build" to deploy web server, Umi created umi.xxxxx.js file and umi.xxx.css and inserted these two file in 'Index.html" . When I checked index.html ,I found uim.xxx.js file and umi.xxx.css path have '/' prefix as like the below. But I think '/' should be removed because this path is relative path not absolute path. These caused problem when I deployed on Zendesk app.
Is there any way to remove '/' when I build using UMI?

<link rel="stylesheet" href="/umi.baa4811d.css">
<script src="/umi.e000ede9.js">

## Context

- **Umi Version**: 2.13.0

**Comment by sorrycc** [comment]
Try to set publicPath to `./`.
