### ISSUE TITLE
开启hd后 编译报错

### ISSUE THREAD

**Issue by xxxlihui** [umijs/umi#436]
github地址https://github.com/xxxlihui/umitest

Failed to compile.

./node_modules/_antd-mobile@2.1.8@antd-mobile/es/badge/style/index.less
Module build failed: 

@0: .;@1: /;@2: s;@3: r;@4: c;@5: /;@6: t;@7: h;@8: e;@9: m;@10: e;@11: .;@12: j;@13: s;@hd: 2px;
        ^
Unrecognised input
      in E:\project\chargingpile\apph5\node_modules\_antd-mobile@2.1.8@antd-mobile\es\badge\style\index.less (line 89, column 10)
^C��ֹ�����������(Y/N)? 
Process finished with exit code 1

**Comment by xiaohuoni** [comment]
咦？怎么是我写的。。。。。可是我没有这个版本的项目啊（捂脸）
然后你的pages里面的index都是空的，就算不加hd，也运行不了的吧。
你可以更新一下，https://github.com/xiaohuoni/umi-antd-pro
或者用群里他们说实现更好的版本https://github.com/boxcc/umi-pro

**Comment by xxxlihui** [comment]
@xiaohuoni 就是从你这个分支出来的,修改了layout那里

**Comment by xiaohuoni** [comment]
@xxxlihui 
修改.webpackrc.js
```js
theme: './src/theme.js',
extraBabelPlugins: [
     ['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }],
],
```
为
```js
theme: {
        "brand-primary": "red",
        "color-text-base":  "#333"
      },
      extraBabelPlugins: [
        ["import", { libraryName: "antd-mobile", libraryDirectory: "es", style: true }]
      ]
```
参考官方：
Antd-Mobile：[定制主题](https://mobile.ant.design/docs/react/customize-theme-cn)
Ant-Design：[定制主题](https://ant.design/docs/react/customize-theme-cn)

**Comment by xiaohuoni** [comment]
@xxxlihui 确认没有问题的话可以关闭，然后，antd-pro主要还是用于web端，你要勇于手机端，还是使用dva-cli@next 或者oni-cli创建一个新项目，比较好。
