### ISSUE TITLE
从 umi 中导入 connect，Dispatch 等模块时提示 umi 未导出

### ISSUE THREAD

**Issue by zhangminggeek** [umijs/umi#4360]
## What happens?

从 umi 中导入 connect，Dispatch 等模块时提示 'umi' does not contain an export named 'connect'.

## 最小可复现仓库

https://github.com/zhangminggeek/react-template/blob/master/src/pages/index.tsx

## 复现步骤，错误日志以及相关配置

从 umi 中引用 connect, Dispatch, Reducer, Effect 均存在同样的问题

![image](https://user-images.githubusercontent.com/30174437/78201017-1cde5900-74c3-11ea-9c56-97b1bb4c507e.png)

## 相关环境信息

- **Umi 版本**：3.0.16
- **Node 版本**：12.14.1
- **操作系统**：macOS

**Comment by xiaohuoni** [comment]
https://github.com/zhangminggeek/react-template/pull/1

**Comment by sanfire86626** [comment]
希望能解决下呢
 umi@4
import { connect} from '@umijs/max'
import { connect} from 'umi'
都会报错
求解决

**Comment by SnakeHacker** [comment]
在src文件夹下新建models文件夹，然后创建一个文件，删除node_modules，重新yarn install
<img width="410" alt="image" src="https://github.com/umijs/umi/assets/11294011/346c8551-6e6e-4cea-b36b-dd3beebf7e22">

**Comment by sanfire86626** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月24日(星期一) 晚上6:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [umijs/umi] 从 umi 中导入 connect，Dispatch 等模块时提示 umi 未导出 (#4360)





 
在src文件夹下新建models文件夹，然后创建一个文件，删除node_modules，重新yarn install
