### ISSUE TITLE
最新版开启dynamicImport后build失败

### ISSUE THREAD

**Issue by conkyliu** [umijs/umi#4361]
## What happens?
![image](https://user-images.githubusercontent.com/26617741/78206843-831ea800-74d2-11ea-996d-91718b59ab5b.png)
![image](https://user-images.githubusercontent.com/26617741/78206958-d5f85f80-74d2-11ea-8370-d0a534011e46.png)
不开启就可以build成功

- **Umi Version**3.0.16
- **Node Version**:13.9.0
- **Platform**:mac

**Comment by sorrycc** [comment]
这是 oom  了，先参考 https://github.com/umijs/umi/issues/4231 解决。
