### ISSUE TITLE
umi3.x版本create umi 创建的ant-design-pro项目没有自动打开浏览器，文档上说BROWSER是默认开启的。结果与期望不符

### ISSUE THREAD

**Issue by zcSkr** [umijs/umi#4365]
## What happens?

预期yarn start 自动打开浏览器

## How To Reproduce
yarn create umi 
选择ant-design-pro
选择JavaScript
选择antd4.0
yarn start

## Context

- **Umi Version**: 3.0.16
- **Node Version**: 12.16.1
- **Platform**: mac os 10.15.4

**Comment by sorrycc** [comment]
Umi 3 没加这个功能。

**Comment by l-x-f** [comment]
有可用的自动打开浏览器方案吗
