### ISSUE TITLE
🐛 Bug 使用 3.0.17 版本 yarn start antd-pro 报如下错误（win 10）

### ISSUE THREAD

**Issue by kaoding** [umijs/umi#4368]
## What happens?

![image](https://user-images.githubusercontent.com/18542211/78251072-6363a000-7523-11ea-9aaa-6114d2878977.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
试了脚手架，不能复现。

**Comment by kaoding** [comment]
我在windows 10上，重新拉了一个 ant-design-pro 最新的 master 试了，把版本定在 3.0.16就没有问题，定在 3.0.17 就报错。

![image](https://user-images.githubusercontent.com/18542211/78254345-5a290200-7528-11ea-8f00-9a8607372729.png)

![image](https://user-images.githubusercontent.com/18542211/78254305-4da4a980-7528-11ea-8fef-db66f2b2aed5.png)

@sorrycc

**Comment by caicheng** [comment]
macos下同样遇到此问题

**Comment by ilanus** [comment]
Same Issue

```
node v12.3.1
yarn v1.22.4
umi@3.0.17
```

<img width="1024" alt="Screenshot 2020-04-02 at 16 09 33" src="https://user-images.githubusercontent.com/9677898/78259000-5e3f2a80-74fc-11ea-889c-c6286dcc5755.png">

**Comment by sorrycc** [comment]
给个复现步骤呢？

**Comment by ilanus** [comment]
```
$ yarn global add umi
$ umi -v
umi@3.0.17
$ yarn create umi myApp
$ > ant-design-pro
$ > TypeScript
$ > simple
$ > antd@4! (Y)
$ cd myApp
$ yarn && yarn start
```

**Comment by ycjcl868** [comment]
我试了下 node 10，MacOS 无法复现

**Comment by kaoding** [comment]
windows 10 上 

1. git clone https://github.com/ant-design/ant-design-pro.git
2. yarn (package.json 安装的是 3.0.17)
3. yarn start (就报错)

**Comment by kaoding** [comment]
> 我试了下 node 10，MacOS 无法复现

我 node 是 v12.13.0

**Comment by ycjcl868** [comment]
> > 我试了下 node 10，MacOS 无法复现
> 
> 我 node 是 v12.13.0

node 12 也试了，也不行

**Comment by ilanus** [comment]
@ycjcl868 you starting with wrong version `Starting Umi UI using umi@2.13.1...` need to be 3+

**Comment by sorrycc** [comment]
https://github.com/umijs/umi/pull/4327
和这个有关，我先 revert 了。

**Comment by sorrycc** [comment]
修复了，https://github.com/umijs/umi/releases/tag/v3.0.18

**Comment by ycjcl868** [comment]
> @ycjcl868 you starting with wrong version `Starting Umi UI using umi@2.13.1...` need to be 3+

![image](https://user-images.githubusercontent.com/13595509/78262765-9e6dcf80-7533-11ea-95de-07fc6a6ced4b.png)

似乎也不能复现

**Comment by sorrycc** [comment]
我用 `y create @umijs/umi-app` 不能复现，但直接 clone ant-design-pro 能复现，原因待查。
