### ISSUE TITLE
配置了umi-request 的errorHandler属性后，错误请求不会走catch流程

### ISSUE THREAD

**Issue by zengjingke** [umijs/umi#4374]
问题：配置了umi-request 的errorHandler属性后，错误请求不会走catch流程

**Comment by xiaohuoni** [comment]
errorHandler 的用处就是统一处理错误，应该是在这里拦截了错误，不会再抛出异常。
我觉得统一处理，会比较好。再抛出错误，有没接收的情况就会导致项目挂掉

**Comment by zengjingke** [comment]
@xiaohuoni 配置了errorHandler后，判断undefine即可？
