### ISSUE TITLE
[Feature Request] support language-only locales like "en"

### ISSUE THREAD

**Issue by khalibloo** [umijs/umi#4375]
## Background

Sometimes, `navigator.language` returns the only the language without the country. Currently I have not found a way to handle this in umi. Making a `locales/en.ts` file does not work. It produces the following error
```
This dependency was not found:
* antd/es/locale/en_EN in ./src/.umi/plugin-locale/localeExports.ts
```

## Proposal

Locales that specify only the language should fall back to one with a similar language. For example, "fr" should fall back to "fr-XX" and "en" should fall back to "en-XX". Additionally, `locales/en.ts` should be supported.

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
