### ISSUE TITLE
svg 图片无法正常转 base64

### ISSUE THREAD

**Issue by aprilyzl0405** [umijs/umi#4377]
版本 3.0.16
```
// 1
import logo from '../assets/logo.svg';

// 2
<img alt="logo" className={styles.logo} src={require("../assets/logo.svg")} />
```
均无法将 svg 图片转为 base64

无奈换成 png 后是可以的，但我记得在 2.0 时 svg 也是转了的，翻了文档貌似没有 svg 这点的改动，算是个 bug？

**Comment by sorrycc** [comment]
svg 太大，超过 10K 了？

**Comment by aprilyzl0405** [comment]
[最小可复现仓库](https://github.com/aprilyzl0405/umi-svg-2-base64)
inlineLimit 也放开 10K 的限制了，build 后依然是直接引用 static 下的 svg 资源，但 png 则是转为了 base64

**Comment by aixfox** [comment]
svg 使用的是 file-loader 不是 url-loader，inlineLimit 是给 url-loader 使用的。
瞧了一下 cra 和 vue 的配置也是如此。
至于为什么嘛，可能和 @svgr/webpack 有关？蹲个解答 →_→

**Comment by delonzhou** [comment]
> svg 太大，超过 10K 了？

同样遇到这个问题，应该不是文件太大的问题，我的文件是700bytes，也没有转。

**Comment by delonzhou** [comment]
targets配置由ie:9 ==> ie: 10，问题解决

**Comment by aizigao** [comment]
相同的问题啊，我用targets为10也不行

**Comment by code-brewer** [comment]
> svg 使用的是 file-loader 不是 url-loader，inlineLimit 是给 url-loader 使用的。

是这个原因吗？ 如果是的话， 怎么能让 svg 交给 url-loader  处理呢？ 

烦躁啊， 很多问题都没人解答。 如果umi自己暂时没办法解决，为什么不写些文章、章节介绍怎么开放扣子給用户。自己直接用 webpack配置的工程，简单google下，就都解决了。 这个UMI的，真的搜索不到，资源少。

**Comment by mvslan** [comment]
因为umi对svg打包专门做了处理：
@umijs/bundler-webpack/lib/getConfig/getConfig.js
webpackConfig.module.rule('svg').test(/\.(svg)(\?.*)?$/).use('file-loader').loader(require.resolve('@umijs/deps/compiled/file-loader')).options({
  name: 'static/[name].[hash:8].[ext]',
  esModule: false
}); 
把这俩file-loader改成url-loader就ok了
当然这么做不是很好，所以在config中这么写：
 chainWebpack: (memo) => {
    memo.module
      .rule('svg')
      .test(/\.(svg)(\?.*)?$/)
      .use('file-loader')
      .loader('url-loader')
      .options({
        limit: 1024 * 1024 * 100,
      })
      .end()
  },

**Comment by ahv5aw5n** [comment]
```
chainWebpack: (config) => {
    // 覆盖 svg rule
    const svgRule = config.module.rule('svg');
    svgRule.uses.clear();
    svgRule
      .use('url-loader')
      .loader(require.resolve('../node_modules/@umijs/deps/compiled/url-loader'))
      .options({
        limit: 1024 * 10,
        name: 'static/[name].[hash:8].[ext]',
        esModule: false,
        fallback: {
          loader: require.resolve('../node_modules/@umijs/deps/compiled/file-loader'),
          options: {
            name: 'static/[name].[hash:8].[ext]',
            esModule: false,
          },
        },
      })
      .end();
  },
```

`"umi": "^3.4.8",` 可以正常转Base64
