### ISSUE TITLE
umi 编译后文件 umi.js  umi.css 修改后浏览器不能及时更新的解决办法

### ISSUE THREAD

**Issue by zsl1549** [umijs/umi#4382]
## What happens?

umi 编译后文件 umi.js  umi.css 修改后浏览器不能及时更新的解决办法
下面方法也解决不了，请问还有别的方法解决问题吗？ 请求指教一下！
![image](https://user-images.githubusercontent.com/32888522/78620584-02d1bb80-78b3-11ea-8d7c-21b83ec3e632.png)

## 相关环境信息

- **Umi 版本:^2.7.2：
![image](https://user-images.githubusercontent.com/32888522/78620756-7247ab00-78b3-11ea-8508-c821b9af5da8.png)

- **Node 版本:：v11.1.0
- **操作系统**：mac

**Comment by zsl1549** [comment]
![image](https://user-images.githubusercontent.com/32888522/78621641-a8862a00-78b5-11ea-9700-558ead44227b.png)
![image](https://user-images.githubusercontent.com/32888522/78621652-af14a180-78b5-11ea-88f9-a7340773f24f.png)

**Comment by xiaohuoni** [comment]
看请求，这个文件没变？还是编译的时候这个文件没变？？

**Comment by zsl1549** [comment]
@xiaohuoni 编译后文件变了  请求也变了

**Comment by zsl1549** [comment]
![image](https://user-images.githubusercontent.com/32888522/78883218-c6a58300-7a8b-11ea-9c8b-931619943704.png)
![image](https://user-images.githubusercontent.com/32888522/78883259-d8872600-7a8b-11ea-8f55-25419c0bb82f.png)
