### ISSUE TITLE
使用webstorm，.umi文件夹中导出的接口无法使用代码补全

### ISSUE THREAD

**Issue by VeronicaF** [umijs/umi#4384]
win10平台，使用webstorm

配置开启了dva并且项目能正常启动，但是import时没有代码补全
![a1](https://user-images.githubusercontent.com/20827900/78627442-06ba0980-78c4-11ea-9eb1-3f658798fd00.png)

原因是src/.umi/plugin-dva/exports.ts中导出时使用的是绝对路径，webstorm无法识别
![a2](https://user-images.githubusercontent.com/20827900/78627672-ad9ea580-78c4-11ea-8277-518e71d57056.png)

与webstorm官方交流过，他们表示

![a3](https://user-images.githubusercontent.com/20827900/78627724-c909b080-78c4-11ea-9f05-e8e0b75c2d19.png)

vscode下倒是一切正常

所以除了换编辑器还有啥解决办法吗

## 相关环境信息

- **Umi 版本**：3.0.18
- **Node 版本**：12.10.0
- **操作系统**：win10

**Comment by sorrycc** [comment]
有个 webstorm 提 vscode 支持吗？

**Comment by VeronicaF** [comment]
不太明白啥意思

**Comment by lzbabd** [comment]
有跟 webstorm 提 vscode 支持吗？

**Comment by yc-2018** [comment]
这个现在还是不行
