### ISSUE TITLE
umi3中用chrome的redux插件查看更改state值未更新router/location/pathname

### ISSUE THREAD

**Issue by liuhongbo-11** [umijs/umi#4385]
## What happens?

升级umi3.0.1版本后通过chrome中的redux插件查看更改state值未更新router.location.pathname
初始
![1586240726463_3506DB80-3736-448A-95FA-5EBC1C41BA76](https://user-images.githubusercontent.com/22939957/78637696-7983ae80-78dd-11ea-9be9-752eda6dc1ba.png)

切换路由
![1586240897198_E7DA7AAB-DD34-49AC-B882-5104BC5A0EC7](https://user-images.githubusercontent.com/22939957/78637715-830d1680-78dd-11ea-9109-e8b438f0dffc.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
umi 3.0.1

- **Node Version**:
v10.16.2

- **Platform**:
mac Os

**Comment by xiaohuoni** [comment]
相同问题 https://github.com/umijs/umi/issues/4232
