### ISSUE TITLE
ts中引入RequestConfig报错

### ISSUE THREAD

**Issue by twtyjvkg** [umijs/umi#4387]
![image](https://user-images.githubusercontent.com/26063786/78685987-13227e80-7925-11ea-8824-c1123c3338ec.png)

在ts中引入`RequestConfig`报错`Error:(1, 10) TS2305: Module '"node_modules/umi/types"' has no exported member 'RequestConfig'.`
```typescrpit
import { RequestConfig } from 'umi';

export const request: RequestConfig = {

};

```

- **Umi ^3.0.18**:
- **Node v12.16.1**:
- **win10专业版**:

**Comment by xiaohuoni** [comment]
从umi-request导入

**Comment by Echo-minn** [comment]
https://umijs.org/zh-CN/plugins/plugin-request#requestconfig官方文档还是写的
`import { RequestConfig } from 'umi';`
改为了`import { RequestConfig } from 'umi-request';`还是报错
另外，那之后应该怎么使用呢，这本来是一个类型
