### ISSUE TITLE
Open block dev window raise some errors 

### ISSUE THREAD

**Issue by 0RaymondJiang0** [umijs/umi#4388]
## What happens?
When I create a umi project and run it, to open the block dev window, then raise some errors.
- Project open failed  
- TypeError: UmiService is not a constructor

## Some screenshots 
![Snip20200407_2](https://user-images.githubusercontent.com/501182/78656492-0fc5cd80-78fa-11ea-84d8-d254a2a3b9eb.png)
![DF2FA7D8-7B70-4EA9-A91D-8685DF66DDB4](https://user-images.githubusercontent.com/501182/78656932-adb99800-78fa-11ea-9da9-4d9ecb532772.png)

**Comment by Henry-baobao** [comment]
same problem as you described! Did you solve this problem?
