### ISSUE TITLE
umi dev 运行后一直Compiling...怎么回事，要手动刷新才渲染界面，umi版本@1.2.6

### ISSUE THREAD

**Issue by 314172670** [umijs/umi#439]
@xiaohuoni

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/158

**Comment by 314172670** [comment]
![image](https://user-images.githubusercontent.com/23290703/39747284-6d96c3ee-52df-11e8-98e7-cd82fdc45db7.png)

**Comment by xiaohuoni** [comment]
我在[with-dva](https://github.com/umijs/umi-examples/tree/master/with-dva) 里面试了 ,第一次是卡死了，执行了umi build之后，再运行umi dev就好了@314172670

**Comment by 314172670** [comment]
我没用到dva

**Comment by xiaohuoni** [comment]
那你能给一个可以重现的demo吗？

**Comment by 314172670** [comment]
https://github.com/314172670/my_umi

**Comment by 314172670** [comment]
![image](https://user-images.githubusercontent.com/23290703/39748135-e6a012b6-52e1-11e8-9553-590dcf272a67.png)
title配置没有反应，为什么？

**Comment by xiaohuoni** [comment]
title配置没有反应，为什么？
-------------------------------
增加
```js
exportStatic: true
```
但是存在https://github.com/umijs/umi/issues/408

**Comment by 314172670** [comment]
@sorrycc 重现步骤是什么意思？我的demo在这https://github.com/314172670/my_umi

**Comment by sorrycc** [comment]
出现几率如何？我试了 10 次出现 1-2 次。

**Comment by sorrycc** [comment]
另外，我用 umi master 分支的代码测试已经不能重现了。先关了，等 umi@1.3 发布后有问题再开吧。介意这个问题的可以加环境变量禁用按需编译：

```bash
$ COMPILE_ON_DEMAND=none umi dev
```

另外，.umirc.js 里配置 PrivateRoute 的路径错了，应该是 `./src/routes/PrivateRoute.js`。

**Comment by xiaohuoni** [comment]
@314172670 @sorrycc  修改layouts/index.js.能处理这个问题，
比如
```js
export default ({ children }) => {
  return (
    <div>
      <div>Header (layouts/index.js)</div>
      <hr/>
      <hr/>
      {
        children
      }
      <hr/>
      <div>Footer (layouts/index.js)</div>
    </div>
  );
}
```
但是我看了现有的layout，没觉得有什么问题。
