### ISSUE TITLE
umi3 提示模块找不到， 急！

### ISSUE THREAD

**Issue by six-666** [umijs/umi#4390]
代码在 umi2是正常的，今天打算升级下，结果发现问题

代码路径 src/common/er/src/local.js

下面这段代码无法导入 umi， formatMessage 为 undefined， 但是在其他文件是正常的，我猜想是不是跟目录有关。
```
import { formatMessage } from 'umi';

const OK = formatMessage({ id: 'ok' });
```

**Comment by leftstick** [comment]
你插件 `@umijs/plugin-locale` 或者 `@umijs/preset-react` 装了么？

**Comment by six-666** [comment]
已经找到原因了，原来是 "path-to-regexp": "2.4.0", => "path-to-regexp": "^6.1.0",  升级了这个导致的
