### ISSUE TITLE
umi3 引入 xlsx 报错

### ISSUE THREAD

**Issue by six-666** [umijs/umi#4392]
import demo from '../../../../public/demo.xlsx';

Module parse failed: Unexpected character '' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

从umi2 升级到umi3 各种奇怪问题都出来了。

**Comment by leftstick** [comment]
好像目前的确不支持，你的意思是 `umi@2` 是支持 `.xlsx` 引入的？

**Comment by six-666** [comment]
@leftstick 是的， 那怎么办呢，我要在项目中加个按钮下载这个文件

**Comment by leftstick** [comment]
如果只是下载的话，直接放到 `public` 目录里，提供下载链接 `<a href="/demo.xlsx">下载</a>` 不就好了么？

**Comment by six-666** [comment]
@leftstick 对哦，我怎么没想到呢，， 还有个问题想问下


```
import { history, formatMessage } from 'umi';
// formatMessage 和history  是 undefine。  不知道怎么回事，用的是 umi@3.0.14

```

**Comment by leftstick** [comment]
`formatMessage` 要安装 `@umijs/plugin-locale` 或者 `@umijs/preset-react` 才能用。

`history` 不应该啊，要是还有错，另开issue吧

**Comment by AKclown** [comment]
> 如果只是下载的话，直接放到 `public` 目录里，提供下载链接 `<a href="/demo.xlsx">下载</a>` 不就好了么？
你好，我是用a标签直接下载下来的excel是损坏的，如何下载本地excel呢？
版本为:  "umi": "^3.5.20"
![image](https://user-images.githubusercontent.com/33648653/149074629-dc4d5570-60e5-40d9-887d-68cbadc5c9d5.png)

**Comment by AKclown** [comment]
使用FileSaver.js插件解决该问题
