### ISSUE TITLE
umi3 找不到 umi 模块， 急 【bug】

### ISSUE THREAD

**Issue by six-666** [umijs/umi#4393]
```
// undefined  "umi": "^3.0.14",
import umi from 'umi';
```

报错
```
"export 'default' (imported as 'umi') was not found in 'umi'
```

不知道啥情况，还有这种操作。

2.x是正常的，现在升级3.x 有点困难。

@sorrycc

**Comment by leftstick** [comment]
因为真的没有 默认导出，先说你要干嘛？

**Comment by six-666** [comment]
@leftstick  我要使用里面的方法， history   等

**Comment by leftstick** [comment]
`import { history } from 'umi'`

**Comment by six-666** [comment]
我是从2.x 升级到 3.x 就遇到这个问题了,  umi 什么都没有
```
import { formatMessage } from 'umi';
const OK = formatMessage({ id: 'ok' });
```

**Comment by six-666** [comment]
其他模块都是正常的，只有 umi 无法导入进来

**Comment by leftstick** [comment]
给可复现 repo吧

**Comment by six-666** [comment]
@leftstick 找到原因了，纳闷,  在model 里面用就会有这个问题， 什么问题呢。

src/models/global.js
```
import { formatMessage } from 'umi';

console.log(formatMessage)
```

**Comment by leftstick** [comment]
`umi@3` 的文档里是这么写的：

```typescript
//page/index.tsx

import React, { useState } from 'react';
import { useIntl } from 'umi';

export default function() {
  const intl = useIntl();
  return (
    <button type="primary">
      {intl.formatMessage(
        {
          id: 'name',
          defaultMessage: '你好，旅行者',
        },
        {
          name: '旅行者',
        },
      )}
    </button>
  );
}
```

由此观之，你的用法不对

**Comment by six-666** [comment]
@leftstick 不是国际化问题，是 umi 整个模块都导入不进来

```
import umi from 'umi';
// undefined
console.log(umi)


setTimeout(async () => {
  const u = await import('umi')
// ok
  console.log(u.history)
}, 2000)
```

**Comment by feibi** [comment]
看是不是这个情况 #4235

**Comment by six-666** [comment]
@feibi  默认开启dva的，那这个有解决方案吗

**Comment by gogohere** [comment]
猜测是umi的初始化代码执行顺序问题，可以使用import('umi').then(data => {}）这种方法引用umi

**Comment by gogohere** [comment]
> 猜测是umi的初始化代码执行顺序问题，可以使用import('umi').then(data => {}）这种方法引用umi

我这边也碰到了这样的问题，用这种方法解决的

**Comment by liyang001** [comment]
试一下配置
dva: {
  disableModelsReExport: true,
  lazyLoad: true,
}
https://umijs.org/zh-CN/plugins/plugin-dva

**Comment by EdenLiang** [comment]
> 试一下配置
> dva: {
> disableModelsReExport: true,
> lazyLoad: true,
> }
> https://umijs.org/zh-CN/plugins/plugin-dva

提示"lazyLoad" is not allowed, 
在版本"umi": "^3.2.14"上

**Comment by EdenLiang** [comment]
可以暂时在models里面使用formatMessage, 先过渡
