### ISSUE TITLE
antd pro升级到umi3.0后打包失败/体积过大

### ISSUE THREAD

**Issue by MangGoDio** [umijs/umi#4394]
不开启按需加载的话，直接打包会提示内存不足
Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
开启`dynamicImport: {}`后，升级前打包出的文件7MB，3.0后打包出的文件29MB，翻了下文档`dynamicImport`的配置似乎也取消了，请问这个打包体积有办法控制回去吗

- **Umi 版本**：3.0.18
- **Node 版本**：10.15.3
- **操作系统**：windows

**Comment by hanguihe** [comment]
我也是...CICD直接挂了...
![截屏2020-04-08 下午4 50 25](https://user-images.githubusercontent.com/29910482/78764434-1cf5c180-79b9-11ea-9762-f4a0fd0934e6.png)

**Comment by phoema** [comment]
我也挂掉了

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

我发现之前配置的
      dynamicImport: {
        loadingComponent: './components/PageLoading/index',
        webpackChunkName: true,
        level: 3,
      },

        属性webpackChunkName: true,
        level: 3,
在新版中没有属性定义了。

**Comment by linfengluo** [comment]
同样，直接挂了


**FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory**

**Comment by Dddota** [comment]
具体是terserPlugin这个插件这里报内存溢出
我现在的做法是，卸载了terser 和 terser-webpack-plugin
npm uninstall terser  和npm uninstall terser-webpack-plugin
然后修改webpack 和umi   去除了对terser-webpack-plugin 的依赖
具体修改的地方：
/feit/tools/jenkins/workspace/hcip-web-develop/node_modules/webpack/lib/WebpackOptionsDefaulter.js
vi /feit/tools/jenkins/workspace/hcip-web-develop/node_modules/@umijs/bundler-webpack/lib/getConfig/getConfig.js
vi /feit/tools/jenkins/workspace/hcip-web-develop/node_modules/webpack/package.json
搜索关键字 terser   ，相关的代码行，全部注释掉了

**Comment by zhangyu1818** [comment]
我也遇到这个问题了，本地没事，在服务器打包就出问题了，服务器4g内存不够吗，设置了--max_old_space_size=4096好像也没有用orz

**Comment by yzStrive** [comment]
@xiaohuoni  这个issue关闭了有解决方案吗 我们这边也出现这个问题了 服务器上内存溢出了

**Comment by xiaohuoni** [comment]
@yzStrive 我觉得服务器本身内存就小的情况，因为我们的是正常的，如果还有其他疑问，可以去 pro 那边提交问题。

**Comment by zhangyu1818** [comment]
我之前4g内存不够用，现在换了个48g的打包2个项目都没问题😂

**Comment by phoema** [comment]
我竟无言以对
> @yzStrive 我觉得服务器本身内存就小的情况，因为我们的是正常的，如果还有其他疑问，可以去 pro 那边提交问题。

**Comment by xiaohuoni** [comment]
我只是猜的，如果你可以定位问题的话，倒是可以进一步的跟进。从现在的信息，看不出来为啥。（捂脸）

**Comment by Mh2336393** [comment]
我也是同样得问题 有解决方案没~呢啊得

**Comment by phoema** [comment]
> 我也是同样得问题 有解决方案没~呢啊得

建议开新Issue啊，这个被关闭了，虽然我也没解决问题。

**Comment by Mh2336393** [comment]
umi build 前面可以加  --max-old-space-size=4096  不过我们服务器内存只有1G可用 不知道好不好使 明儿让测试试一下

**Comment by zhoushaobo1015** [comment]
这个问题的本质其实是项目过大导致的，但也是没有办法的，解决方式
1. 将dynamicImport注释
2. 开启dynamicImport的同时也要启用chainWebpack做路由切片
推荐第2种路由碎片话对项目是一个很大的优化
参考地址: https://mp.csdn.net/mp_blog/creation/editor/107906243

**Comment by phoema** [comment]
> 您这个网址无法跳转到详情页面

**Comment by sinianzhiren** [comment]
https://blog.csdn.net/weixin_40228604/article/details/107906243   文章地址
