### ISSUE TITLE
antpro 升级到3.0 ie11下报错了  设置targets没有效果

### ISSUE THREAD

**Issue by FFJUN** [umijs/umi#4396]
## What happens?
config设置了 targets 但是ie11下面还是报  没有Promise的错 
export default defineConfig({
    targets: {
        ie: 11,
    },
    hash: true
})

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:3.0.18
- **Node Version**: 12.16.1
- **Platform**: window10

**Comment by rilaohn** [comment]
同问，尝试了最新的umi2也是一样的！

**Comment by xiaohuoni** [comment]
相同的问题 https://github.com/umijs/umi/issues/5428
