### ISSUE TITLE
How to share model's data between pages in umi + dva-no-router.

### ISSUE THREAD

**Issue by elivoa** [umijs/umi#44]
I am refactoring my project using umi.
As shown In this example https://github.com/umijs/umi/tree/master/examples/with-dva

Each page has a new instance of dva, Is this the right way to use dva in umi?
If so, models can't share it's data between pages. but I want to share data just like before in dva with react-router@4.

What's the best way to use dva-no-router in umi?

**Comment by sorrycc** [comment]
Create a dva instance with a separate file and make sure dva is a singleton.

**Comment by elivoa** [comment]
I already make dva a singleton, create it at the first page who use it.
At each page, I do the following things.
1. Get dva instance by: 
`const app = createDVA()`

2. register model,
`app.model(require('models/somemodel').default);`

3. Create a react component as a page. 
`class Login extends React.Component {...}`

4. Register react Component to dva instance.
`dva.router(()=><Login/>);`

5 export default
```javascript
const p = app.start(); // I cached this p
export default p
```

By doing so I can see the first page 'PageA', but when I redirect to the second page 'PageB', I got 'PageA', 

I think is wrong to call dva.router() twice. I can't update app.router.

What's the best way to fix this in umi?

**Comment by sorrycc** [comment]
It's dva's bug, I'll fix it later.

**Comment by elivoa** [comment]
Great, Thanks.

**Comment by sorrycc** [comment]
Bumped `dva-no-router@1.1.0-beta.1`, and I've tried it in the [with-dva](https://github.com/umijs/umi/tree/master/examples/with-dva) example.

**Comment by elivoa** [comment]
It works in my project perfectly . thanks.
