### ISSUE TITLE
UmiJS文档中关于路由配置项exact字段默认值描述错误

### ISSUE THREAD

**Issue by justaworker** [umijs/umi#4402]
文档地址 https://umijs.org/zh-CN/docs/routing 
按文档中举例exact默认值为false，实际上exact默认值为true,当包含子路由配置routes字段时值为false

**Comment by xiaohuoni** [comment]
看最新的文档，是正确的。
![image](https://user-images.githubusercontent.com/11746742/93838359-f18f3680-fcbb-11ea-8550-f2ac0f037d03.png)
