### ISSUE TITLE
umi3 layout config conflict with @ant-design/pro-layout

### ISSUE THREAD

**Issue by LarryZhao0616** [umijs/umi#4403]
## What happens?
我看到[umi3使用plugin-layout插件内置pro-layout](https://umijs.org/zh-CN/plugins/plugin-layout)
但是这个layout config似乎和直接使用@ant-design/pro-layout的场景存在冲突。
有以下几点反馈：

1.plugin-layout似乎只支持sidemenu，不支持topmenu。
```
export default defineConfig({
  layout: {
    ...defaultSetting, 
     layout: 'topmenu', //不生效
   },
})
```

2.如果同时在BasicLayout使用ProLayout组件以及在config配制layout，会出现layout嵌套。这一点建议在文档说明。

3.如果继续保持在BasicLayout使用ProLayout组件，config中的一些其他配置似乎和ProLayout有冲突，比如router的name和title国际化失效，document.title的生效规则也没有地方明确说明等等。

1 2只是在使用体验上比较奇怪，不算问题，完善文档就好了。
3的国际化是真正问题。

**Comment by xiaohuoni** [comment]
？？？
所以问题是啥？
