### ISSUE TITLE
[getDvaApp] Umi3.0 getDvaApp时返回undefined

### ISSUE THREAD

**Issue by JustGogoing** [umijs/umi#4405]
## Background

在封装的请求文件中,需要从model获取token写在请求头, 但是通过getDvaApp获取到的是undefined,
如果使用异步打印是正常的, 这个怎么处理啊

![image](https://user-images.githubusercontent.com/17309976/78865187-bb445e80-7a6f-11ea-9bac-7bd71a55286e.png)

**Comment by ChamHuang** [comment]
我也是出现这个问题

**Comment by JustGogoing** [comment]
> 我也是出现这个问题

解决了吗?

**Comment by ChamHuang** [comment]
> > 我也是出现这个问题
> 
> 解决了吗?

没有，你解决了吗？

**Comment by JustGogoing** [comment]
> > > 我也是出现这个问题
> > 
> > 
> > 解决了吗?
> 
> 没有，你解决了吗？

我刚才无意中发现打包之后 能正常获取,  还没有测试, 你可以先试试

**Comment by JustGogoing** [comment]
@ChamHuang  还是不行  找到解决办法告知下哈

**Comment by JustGogoing** [comment]
修改了model中state的数据, 在dev-tool中查看已经改完了,  但是 在打印的时候 还是之前的.

**Comment by ChamHuang** [comment]
现在弄好了吗？今天没有试

**Comment by JustGogoing** [comment]
> 现在弄好了吗？今天没有试

今天测试  在请求拦截器中设置的, 打印出来一切正常, 但是请求仍旧没有

最后直接在封装的post 和get 里加的  这个应该是umi-request的问题
参考下
`
export const get = (url: string, params?: any): Promise<any> => {
  return new Promise((reslove, reject) => {
    const headers = {
      system: '4',
      'Content-Type': 'application/x-www-form-urlencoded',
      token:localStorage.getItem("token")
    };
    request
      .get(url, {
        params,
        headers: headers,
      })
      .then((res: any) => {
        reslove(res);
      })
      .catch((e: any) => {
        reject(e);
      });
  });
};
`

**Comment by ChamHuang** [comment]
> > 现在弄好了吗？今天没有试
> 
> 今天测试 在请求拦截器中设置的, 打印出来一切正常, 但是请求仍旧没有
> 
> 最后直接在封装的post 和get 里加的 这个应该是umi-request的问题
> 参考下
> `export const get = (url: string, params?: any): Promise<any> => { return new Promise((reslove, reject) => { const headers = { system: '4', 'Content-Type': 'application/x-www-form-urlencoded', token:localStorage.getItem("token") }; request .get(url, { params, headers: headers, }) .then((res: any) => { reslove(res); }) .catch((e: any) => { reject(e); }); }); };`好的我看一下，这个问题怎么也没人关注了

**Comment by hanwenbo** [comment]
@JustGogoing 解决了吗？  这好像是个bug一直存在

**Comment by hyzx86** [comment]
我来格式化下。。

``` javascript
export const get = (url: string, params?: any): Promise<any> => {
    return new Promise((reslove, reject) => {
        const headers = {
            system: '4',
            'Content-Type': 'application/x-www-form-urlencoded',
            token: localStorage.getItem("token")
        };
        request.get(url, { params, headers: headers, })
            .then((res: any) => { reslove(res); })
            .catch((e: any) => { reject(e); });
    });
};
```
