### ISSUE TITLE
babel not support class declare syntax

### ISSUE THREAD

**Issue by ycjcl868** [umijs/umi#4407]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

[useDefineForClassFields.zip](https://github.com/umijs/umi/files/4454827/useDefineForClassFields.zip)

## How To Reproduce

1. `yarn`
1. `yarn start`

![image](https://user-images.githubusercontent.com/13595509/78872933-97d3e080-7a7c-11ea-89b5-9d7a3ceb2671.png)

## Context

- **Umi Version**: 3.1.0
- **Node Version**: 12.x
- **Platform**: OS X

enable the `useDefineForClassFields: true` in `tsconfig.json`, but still not work. 

Reference
- [the-declare-property-modifier](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier)

**Comment by sorrycc** [comment]
估计 babel 不支持吧。

**Comment by ycjcl868** [comment]
umi 2.x 支持

**Comment by sorrycc** [comment]
2.x 的 ts 不走 babel 编译的。

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
