### ISSUE TITLE
Umi3配置开启中文后时间选择器月份不显示中文

### ISSUE THREAD

**Issue by adongroom** [umijs/umi#4409]
## What happens?

RangePicker组件无法格式化为中文月份

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

https://github.com/adongroom/umidate.git

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**npm run serve

![image](https://user-images.githubusercontent.com/6489754/78877281-2f3c3200-7a83-11ea-9abb-48a4ade65fbb.png)

## Context

- **Umi Version**:^3.0.18
- **Node Version**: 12.x
- **Platform**:mac os

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/78901252-a0dba680-7aaa-11ea-81e7-4c3aa1e6e734.png)


external 的 moment，并且没给 `moment/locale/zh-cn` 也 external，导致 moment 国际化失效，去掉 external 后，正常。

![image](https://user-images.githubusercontent.com/13595509/78901309-ba7cee00-7aaa-11ea-8d40-e244b2b9cf6a.png)
