### ISSUE TITLE
当.umirc.ts存在但并未配置路由时，在config/config.ts中配置路由不生效

### ISSUE THREAD

**Issue by justaworker** [umijs/umi#4410]
### What happens?

当.umirc.ts存在但并未配置路由时，在config/config.ts中配置路由不生效，与文档中关于配置文件的描述不符
![image](https://user-images.githubusercontent.com/24671249/78877990-429bcd00-7a84-11ea-8750-552f991888f6.png)
图片文档地址 https://umijs.org/zh-CN/docs/config

![861586422500_ pic](https://user-images.githubusercontent.com/24671249/78877646-c43f2b00-7a83-11ea-901d-f4adac61ca36.jpg)
图片代码地址 https://github.com/umijs/umi/blob/master/packages/core/src/Config/Config.ts

**Comment by ycjcl868** [comment]
不是很懂问题？

**Comment by xiaohuoni** [comment]
两者二选一，`.umirc` 优先。

**Comment by justaworker** [comment]
。。。。文档描述有点让人误解
推荐在 .umirc.ts 中写配置。如果配置比较复杂需要拆分，可以放到 config/config.ts 中，并把配置的一部分拆出去，比如路由。

**Comment by xiaohuoni** [comment]
感觉确实有问题
