### ISSUE TITLE
location缺少类型提示

### ISSUE THREAD

**Issue by conkyliu** [umijs/umi#4411]
## What happens?
![image](https://user-images.githubusercontent.com/26617741/78879461-7ed02d00-7a86-11ea-8aad-e0fbaef359c0.png)

![image](https://user-images.githubusercontent.com/26617741/78879390-69f39980-7a86-11ea-9595-54d49697065f.png)
![image](https://user-images.githubusercontent.com/26617741/78879568-a45d3680-7a86-11ea-9ac1-ecfcd13d86cb.png)
Location接口没看到query属性,导致类型提示错误

- **Umi Version**:3.1.0
- **Node Version**:
- **Platform**:

**Comment by Picsong** [comment]
3.10也没修复吗，我3.0.18也有这问题

**Comment by leftstick** [comment]
没，还pending在 https://github.com/sorrycc/history-with-query/pull/1
