### ISSUE TITLE
window 启动慢的问题统计

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#4415]
## What happens?
在window系统上，启动缓慢的问题。
![image](https://user-images.githubusercontent.com/11746742/78953697-5723a800-7b0c-11ea-9fb6-21ae59911082.png)

## Mini Showcase Repository(REQUIRED)

如果你也遇到了同样的问题，请在评论区给出反馈，以帮助我们定位和解决问题。
我正在尝试着定位这个问题。

## Context

- **Umi Version**:3.1.0
- **Node Version**: ？？？
- **Platform**:window7 16Gb内存，I7的cpu、window10 16G，I7CPU，三星全固态硬盘

@fengyun2  @fengnex 来这里讨论下，你们的node版本是？

**Comment by phoema** [comment]
3.1.1使用如下配置
编译直接内存溢出
、     dynamicImport: {
        loadingComponent: './components/PageLoading/index',
      },

我发现之前配置的
dynamicImport: {
loadingComponent: './components/PageLoading/index',
webpackChunkName: true,
level: 3,
},

    属性webpackChunkName: true,
    level: 3,
在新版中没有属性定义了。是否是去掉了那俩属性导致重复引用的包被重复编译导致的？

**Comment by sorrycc** [comment]
@phoema nodeModulesTransform 设为 `type: none` 呢？https://umijs.org/config#nodemodulestransform-31

**Comment by phoema** [comment]
@sorrycc 
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
不行，内存轻松上4G
我相对antPro就是多引入了mobx、moment、bizcharts、crypto-js等几个库

**Comment by kkerwin** [comment]
启用 dynamicImport ，nodeModulesTransform 设置为 none ,build还是失败，每次都是卡在92%。umi dev 则没有问题。
![企业微信截图_20200413151116](https://user-images.githubusercontent.com/7856025/79100840-edb8c900-7d99-11ea-8878-9ecb7d06a906.png)

![企业微信截图_20200413151052](https://user-images.githubusercontent.com/7856025/79100868-fc9f7b80-7d99-11ea-8c96-eba49c5b6958.png)
===============================================================
关闭 dynamicImport build的时间：

![企业微信截图_20200413151324](https://user-images.githubusercontent.com/7856025/79100932-22c51b80-7d9a-11ea-96c5-56278e68158c.png)

同样的代码在umi 2 下开启 dynamicImport 是正常的

**Comment by phoema** [comment]
原来这么多难兄难弟

**Comment by phoema** [comment]
#4423 #4453

**Comment by xiaohuoni** [comment]
感觉没一个有效信息，讨论请提供
umi版本、电脑系统、电脑内存、node版本、umi config配置等便于定位的信息。
最好能有最间的重现demo。比如一个空的umi项目是否也会如此。

**Comment by phoema** [comment]
umi:3.1.1
电脑系统:windows 10
电脑内存:16G
node版本:v12.16.2
umi config:
// https://umijs.org/config/
import { defineConfig } from 'umi';
import defaultSettings from './defaultSettings';
import proxy from './proxy';
import router from './router.config';
const { REACT_APP_ENV } = process.env;

export default defineConfig({
  hash: true,
  antd: {},
  dva: {
    hmr: true,
  },
  locale: {
    // default zh-CN
    default: 'zh-CN',
    // default true, when it is true, will use `navigator.language` overwrite default
    antd: true,
    baseNavigator: true,
  },
  dynamicImport: {
    loading: '@/components/PageLoading/index',
  },
  nodeModulesTransform: {type:'none'},
  targets: {
    ie: 11,
  },
  // umi routes: https://umijs.org/docs/routing
  routes: router,

  // Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme: {
    'font-size-base': '12px',
    'font-family': '微软雅黑',
    // 'form-item-margin-bottom': '8px',
    'collapse-content-padding': '5px',
    // 'drawer-header-padding': '16px 24px',
    'drawer-body-padding': '10px 15px 0px 15px',
    'modal-body-padding': '10px 24px 10px 24px',
    'table-padding-vertical': '12px',
    'table-padding-horizontal': '12px',
    'form-item-margin-bottom': '8px',
    'layout-body-background':'#fff',
     // ...darkTheme,
    'primary-color': defaultSettings.primaryColor,
  },
  ignoreMomentLocale: true,
  proxy: proxy[REACT_APP_ENV || 'dev'],
  manifest: {
    basePath: '/',
  },
  exportStatic:{    
    htmlSuffix: false,
    dynamicRoot: true
  },
});
最好能有最间的重现demo：很抱歉，这个无法提供，我拉取的正式项目。
一个空的umi项目是否也会如此：不会，默认的antdPro可以编译

**Comment by xiaohuoni** [comment]
@phoema 看起来只是增加了配置
```
exportStatic:{
    htmlSuffix: false,
    dynamicRoot: true
  },
```
能否 默认的antd pro 增加这个配置试试？

**Comment by phoema** [comment]
antd pro仅增加如下配置，可以打包
exportStatic:{
    htmlSuffix: false,
    dynamicRoot: true
  },

**Comment by rilaohn** [comment]
不仅是windows，mac一样，启动要十多分钟，不是启动后的热编译速度还算可以就没管了，最近同事的mac也是这样，而且非css Modules有时候也会加hash，导致样式问题，不知什么原因，最近打开浏览器，选择元素就卡爆了，不知道其他人有没有遇到，还有控制台显示热加载完成，但是页面没有刷新

**Comment by wuxiaoshi888** [comment]
自从升级了3以后 真的开发时超级慢 无论是否将chainWebpack 还是 dynamicImport 注释掉 都一样慢

**Comment by rilaohn** [comment]
umi3页面一多，打开chrome浏览器的DevTools，选择Elements，随便选一个元素查看样式就，非常的卡，样式要很久很久才能出来，根本无法修改样式，不知道其他人有没有这个问题！

**Comment by fengnex** [comment]
我这边win7下的环境是这样的：
C:\Users\Administrator>node -v
v12.16.1

C:\Users\Administrator>npm -v
6.13.4

C:\Users\Administrator>yarn -v
1.22.4

C:\Users\Administrator>umi -v
umi@3.0.14

**Comment by sorrycc** [comment]
试试 https://umijs.org/zh-CN/guide/boost-compile-speed 里的方法，有问题新开 ISSUE 吧。

**Comment by LemonTree-shine** [comment]
> 试试 https://umijs.org/zh-CN/guide/boost-compile-speed 里的方法，有问题新开 ISSUE 吧。

没有用，加了这个配置照样卡的飞起

**Comment by hhlcom** [comment]
![image](https://user-images.githubusercontent.com/71809799/120133823-6cbbcb80-c1ff-11eb-99d9-01d7fb489ef9.png) 要命

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/189529082-e7faf568-6d39-4841-8124-82fa192ccae1.png)
一个setup花了8分钟。。。

是个老项目想尝试迁移来着，确实里面页面特别多，但是这个耗时太吓人了，等安装看了一集视频，等编译又看了一集……
