### ISSUE TITLE
一直提示警告 Definition for rule '@typescript-eslint/consistent-type-assertions' was not found

### ISSUE THREAD

**Issue by niezw** [umijs/umi#4417]
## What happens?
出现 Definition for rule '@typescript-eslint/consistent-type-assertions' was not found ，在每一个ts文件上

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
Definition for rule '@typescript-eslint/consistent-type-assertions' was not found

安装完就出现了，在每一个ts文件的第一行,
eslint配置:
`{
  "extends": "eslint-config-umi"
}
`
ts配置:
`
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "jsx": "react",
    "esModuleInterop": true,
    "sourceMap": true,
    "baseUrl": ".",
    "strict": true,
    "paths": {
      "@/*": ["src/*"]
    },
    "allowSyntheticDefaultImports": true
  }
}
`

## 相关环境信息

- **Umi 版本**：
umi@2.13.12
- **Node 版本**：
v10.0.0
- **操作系统**：
mac os

**Comment by Clago** [comment]
解决了吗，我这边也是

**Comment by qhanw** [comment]
我也遇到这个问题，但最终检查出来，发现是网络问题引起。
#### 环境信息
Umi：umi@3.x
Node：v12.18.2
操作系统：mac os

**Comment by RepSklvska** [comment]
我这边也是，不论Linux还是Windows。

**Comment by RepSklvska** [comment]
> 
> 
> 我也遇到这个问题，但最终检查出来，发现是网络问题引起。
> #### 环境信息
> 
> Umi：[umi@3.x](mailto:umi@3.x)
> Node：v12.18.2
> 操作系统：mac os

你解决的方法是不是不用国内的npm镜像源？

**Comment by xiaohuoni** [comment]
没复现这个问题，提供可复现的demo，再reopen
