### ISSUE TITLE
和eggjs一起使用的时候，window下无法运行

### ISSUE THREAD

**Issue by daihaoxin** [umijs/umi#442]
eggjs给的一个demo项目https://github.com/eggjs/examples/tree/master/assets-with-umi，  在linux里运行正常，在windows下，生成.umi包里面的router.js文件会报错，
![image](https://user-images.githubusercontent.com/5250679/39809714-2eb07e82-53b5-11e8-845f-a368e70c9651.png)

 实际项目中，eggjs和umi/dva一起使用的，生成的DvaContainer.js也会报错，如下图
![image](https://user-images.githubusercontent.com/5250679/39809959-e87b9ac2-53b5-11e8-9457-8950df25312c.png)

@sorrycc  补充一下问题，windows中，在上面的assets-with-umi程序中，如果使用npm run build也会出现问题，截图如下：
![image](https://user-images.githubusercontent.com/5250679/39815142-b4a39fb0-53c9-11e8-9c9c-0db3256d5a56.png)

**Comment by sorrycc** [comment]
重现了，待修复，在处理 cwd 非当前路径是有些问题。

**Comment by daihaoxin** [comment]
@sorrycc 下个小版本可以解决吗？

**Comment by sorrycc** [comment]
这周会修复。

**Comment by hanzichi** [comment]
修复了吗？试了下 win 下还是有问题 @sorrycc @daihaoxin

**Comment by daihaoxin** [comment]
> 修复了吗？试了下 win 下还是有问题 @sorrycc @daihaoxin

已经修复了，团队已经用过一个项目了

**Comment by hanzichi** [comment]
@daihaoxin  是做了什么配置或者版本升级吗？你 issue 说的这个 demo 我还是没在 win 上跑起来，这个 demo 你现在能跑起来？

**Comment by daihaoxin** [comment]
> @daihaoxin 是做了什么配置或者版本升级吗？你 issue 说的这个 demo 我还是没在 win 上跑起来，这个 demo 你现在能跑起来？

没有做什么配置，就是更来升级了一下，不过升级后我就没有跑过这个demo了，当时是直接在项目上升级的，当时项目比较紧张
