### ISSUE TITLE
开发模式下，代码出现异常后，会出现Redux错误,导致卡死

### ISSUE THREAD

**Issue by hejiao76** [umijs/umi#4420]
## What happens?

开发模式下，model超过15个数量后，
didUpdate中修改Redux 某个变量为undefined
render中取该变量的属性
此时代码会报错，控制台会输出一堆Redux抛出的错误
![image](https://user-images.githubusercontent.com/4813097/78963544-6580bc80-7b2a-11ea-9bfe-a88a66c32fcb.png)

## Mini Showcase Repository(REQUIRED)

> https://github.com/hejiao76/errorDemo

## How To Reproduce

**直接访问路由/dir1
**http://localhost:8000/dir1

## Context

- **Umi Version**: 3.1.0
- **Node Version**: 12.16.1
- **Platform**: windows

**Comment by hejiao76** [comment]
@sorrycc 求助

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
