### ISSUE TITLE
升级到umi 3.1.0 打包项目卡死，不知道为什么，哪位大佬给看下

### ISSUE THREAD

**Issue by XSmarter** [umijs/umi#4423]
![image](https://user-images.githubusercontent.com/33716687/78966588-ddeb7b80-7b32-11ea-84d5-a8b6da9143af.png)

升级到 umi3.1.0 把配置文件简化后就变成这样了
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by XSmarter** [comment]
![image](https://user-images.githubusercontent.com/33716687/78966854-7255de00-7b33-11ea-8458-fe60a88280a5.png)

最后打包出来了，这个时间也太长了吧。。。

**Comment by ycjcl868** [comment]
试下加上 `nodeModulesTransform` 配置：

```js
// .umirc.ts
nodeModulesTransform: {
    type: 'none',
  },
```

**Comment by xiaohuoni** [comment]
也可以试试禁用 babel 缓存 `BABEL_CACHE `

**Comment by phoema** [comment]
根目录创建.env文件，增加BABEL_CACHE=none，仍然无效，到92就卡住了，如下：
* Webpack █████████████████████████ chunk asset optimization (92%) TerserPlugin
然后一段时间后，内存溢出
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

下面是报告，不知道有没有排查效果。

 
[report.20200414.215522.20932.0.001.log](https://github.com/umijs/umi/files/4475703/report.20200414.215522.20932.0.001.log)

**Comment by fengnex** [comment]
建议回退到umi3.0.14
为此我把node、npm、yarn几乎都重装了，umi感觉质量上问题多多，3.1.0特别无语，为此搭上了几个工作日，建议各位难兄难弟，升级umi一定要慎重！血泪教训！

**Comment by phoema** [comment]
umi3.0.14仍然不行，一样溢出，是不是我页面太多，把umi调webpack的时候整崩溃了？
我把路由设置删到只剩login，就打包通过了。
export default [
  {
    name: 'login',
    path: '/user/login',
    component: './login/login.js',
    // component: './user/login',
  }, 
  {
    path: '/',
    component: '../layouts/SecurityLayout',
    routes: [
      {
        path: '/',
        component: '../layouts/BasicLayout',
        Routes: ['src/pages/Authorized'],
        routes: [



        ],
      },
    ],
  },
  {
    component: './404',
  },
];

**Comment by phoema** [comment]
将页面从路由里删除完，再尝试增加了一批页面，能够打包通过，但是打包效果不是我想要的。
![image](https://user-images.githubusercontent.com/8730272/79236440-871dd300-7e9f-11ea-8168-43b29617772d.png)
我希望能够像umi2一样，将我的页面按layout拆分即可，不然每个页面都单独打包，最终网站会非常大。
![image](https://user-images.githubusercontent.com/8730272/79236601-bd5b5280-7e9f-11ea-88c3-3f699d8da248.png)

**Comment by ycjcl868** [comment]
可以提供几个打包策略，供项目选择。

**Comment by Dddota** [comment]
具体是terserPlugin这个插件这里报内存溢出
我现在的做法是，卸载了terser 和 terser-webpack-plugin
npm uninstall terser  和npm uninstall terser-webpack-plugin
然后修改webpack 和umi   去除了对terser-webpack-plugin 的依赖
具体修改的地方：
/feit/tools/jenkins/workspace/hcip-web-develop/node_modules/webpack/lib/WebpackOptionsDefaulter.js
vi /feit/tools/jenkins/workspace/hcip-web-develop/node_modules/@umijs/bundler-webpack/lib/getConfig/getConfig.js
vi /feit/tools/jenkins/workspace/hcip-web-develop/node_modules/webpack/package.json
搜索关键字 terser   ，相关的代码行，全部注释掉了

**Comment by zwh1666258377** [comment]
> ![image](https://user-images.githubusercontent.com/33716687/78966854-7255de00-7b33-11ea-8458-fe60a88280a5.png)
> 
> 最后打包出来了，这个时间也太长了吧。。。

差不多 我也四分多钟。  本想从umi2升级到umi3提提速，结果势均力敌。

mbp  16款 8g内存
node 12

**Comment by xiaohuoni** [comment]
试试 esbuild 插件

**Comment by phoema** [comment]
umi3的打包问题、浏览器断点调试问题还有人跟进吗？

**Comment by ycjcl868** [comment]
> 根目录创建.env文件，增加BABEL_CACHE=none，仍然无效，到92就卡住了，如下：
> 
> * Webpack █████████████████████████ chunk asset optimization (92%) TerserPlugin
>   然后一段时间后，内存溢出
>   FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
> 
> 下面是报告，不知道有没有排查效果。
> 
> [report.20200414.215522.20932.0.001.log](https://github.com/umijs/umi/files/4475703/report.20200414.215522.20932.0.001.log)

用最新版 [umi@3.2.28](https://github.com/umijs/umi/releases/tag/v3.2.28)，已经解决了 OOM

**Comment by phoema** [comment]
恭喜，大半年了，不容易啊
另外不卡死时，打包出重复css的问题解决了吗？

**Comment by phoema** [comment]
#5471 #4260

**Comment by xccjk** [comment]
> 具体是terserPlugin这个插件这里报内存溢出
> 我现在的做法是，卸载了terser 和 terser-webpack-plugin
> npm uninstall terser 和npm uninstall terser-webpack-plugin
> 然后修改webpack 和umi 去除了对terser-webpack-plugin 的依赖
> 具体修改的地方：
> /feit/tools/jenkins/workspace/hcip-web-develop/node_modules/webpack/lib/WebpackOptionsDefaulter.js
> vi /feit/tools/jenkins/workspace/hcip-web-develop/node_modules/@umijs/bundler-webpack/lib/getConfig/getConfig.js
> vi /feit/tools/jenkins/workspace/hcip-web-develop/node_modules/webpack/package.json
> 搜索关键字 terser ，相关的代码行，全部注释掉了

确实是这个插件的原因导致的...在Jenkins中执行构建命令也总是内存溢出.

**Comment by luojinghui** [comment]
同样的问题，使用dumi，基于最新的umi进行构建，在centos服务器自动化构建时，每次运行到92%就构建结束，没有任何错误，但是没有任何构建包产出。导致服务器访问dist目录失效。

构建信息：
Webpack █████████████████████████ chunk asset optimization (92%) TerserPlugin

表现：
到92%任务自动结束，没有构建包输出，没有任何错误，执行 DEBUG 调试模式输出也没有任何错误；

观察：
1. 内存飙升
2. 在运行到92%时，服务器cpu达到110%+（本地测试mac高配笔记本也有同样的问题，cpu达到110%+）

请问，有解决方案吗？

**Comment by sanmmm** [comment]
同样出现这个问题。在centos下会出现。ubuntu/和本地开发机（windows）都正常。

**Comment by xiaoyierle** [comment]
同样的问题出现了，在路由中添加了wrappers:[] 参数，对应嵌套了同一个组件， 就开始报错了，本地测试mac高配笔记本也有同样的问题，jenkins也有同样的问题，直接oom

**Comment by xiaoyierle** [comment]
最开始node版本是12.13.1 升级到了 16.13.1，可以打包成功了

**Comment by xiaoyierle** [comment]
> 

<img width="593" alt="截屏2021-12-29 下午5 21 50" src="https://user-images.githubusercontent.com/24968758/147646762-1f94b0a9-c43d-46c6-8580-1bb56daac9de.png">
