### ISSUE TITLE
修改entry build 报错

### ISSUE THREAD

**Issue by xileliu** [umijs/umi#4428]
## What happens?
umi 2
![image](https://user-images.githubusercontent.com/13429648/78978704-e0f36580-7b4c-11ea-9844-59d7465368b6.png)

yarn build 
![image](https://user-images.githubusercontent.com/13429648/78978807-23b53d80-7b4d-11ea-803d-1783e32e903e.png)

yarn start 可正常启动项目

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xileliu** [comment]
@sorrycc

**Comment by xiaohuoni** [comment]
不支持修改主入口
