### ISSUE TITLE
umi 升级到版本3.1.x之后，项目中的className变成动态的了，这时候自己需要通过dom添加class时该怎么弄呢？

### ISSUE THREAD

**Issue by XSmarter** [umijs/umi#4429]
umi 升级到版本3.1.x之后，项目中的className变成动态的了，这时候自己需要通过dom添加class时该怎么弄呢？

比如之前我们处理行选中添加样式这样
trElement.classList.add('antd-pro-components-senior-table-index-tr-selected');
但是现在className变成动态的这个样式就不生效了
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by SmartWrh** [comment]
同问

**Comment by rilaohn** [comment]
3.1.1同问，一些非css Modules也加了hash 导致页面样式问题

**Comment by XSmarter** [comment]
https://umijs.org/zh-CN/guide/upgrade-antd-pro-to-umi-3#%E9%85%8D%E7%BD%AE%E5%B1%82%E8%BF%81%E7%A7%BB
安装页面上的配置添加 cssLoader 就可以了
