### ISSUE TITLE
umi 3 umi dev 启动项目后控制台提示找不到CopyPlugin，当修改代码后重新编译时错误停止

### ISSUE THREAD

**Issue by q531219702** [umijs/umi#4430]
✔ Webpack
  Compiled successfully in 52.03s

 WARNING  Compiled with 0 warnings                                                                                                                                                                                        5:57:13 PM

 SMP  ⏱  Outputted timing info to /Users/.../speed-measure.json

  App running at:
  - Local:   http://localhost:8008 (copied to clipboard)
  - Network: http://192.168.6.190:8008
Could not find a matching event to end plugins CopyPlugin/Compiler/afterEmit { id: 17177 }
 WAIT  Compiling...                                                                                                                                                                                                       5:58:44 PM

● Webpack █████████████████████████ building (70%) 62/62 modules 0 active
 

/Users/***/node_modules/neo-async/async.js:16
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (/Users/.../node_modules/neo-async/async.js:16:11)
    at /Users/.../node_modules/neo-async/async.js:2818:7
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
✨  Done in 150.52s.
...Mac:...$ 
![image](https://user-images.githubusercontent.com/24428085/78983353-a68ec600-7b56-11ea-8a56-26f955cd137a.png)

**Comment by AttackXiaoJinJin** [comment]
我也遇到这个 bug 了

**Comment by johanazhu** [comment]
俺也是

**Comment by 425139060** [comment]
俺也一样

**Comment by INTMIN** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
