### ISSUE TITLE
[dva]state数据变更, 获取仍有缓存, getDvaApp 返回undefined

### ISSUE THREAD

**Issue by JustGogoing** [umijs/umi#4431]
## What happens?

1.对数据请求进行了封装config.js, 在该文件获取 getDvaApp返回的是undefined,  
2. 通过import对应model 获取到model中state的token, 打印正常
3. 修改model中state的token, 通过浏览器插件工具查看redux中数据已经变更,但是再次发送请求打印的时候依然为之前的数据.

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

![image](https://user-images.githubusercontent.com/17309976/78985481-80b7f000-7b5b-11ea-823f-0b14b6cb218d.png)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version  3.0.11**:
- **Node Version  10.17.0**:
- **Platform  windows**:

**Comment by xg4** [comment]
1. `umi-request` `extend` 是静态设置

2. 想要动态设置使用 `request.extendOptions`

3. 文档： [https://github.com/umijs/umi-request/blob/master/README_zh-CN.md#%E6%9B%B4%E6%96%B0%E6%8B%93%E5%B1%95%E5%AE%9E%E4%BE%8B%E9%BB%98%E8%AE%A4%E5%8F%82%E6%95%B0](https://github.com/umijs/umi-request/blob/master/README_zh-CN.md#%E6%9B%B4%E6%96%B0%E6%8B%93%E5%B1%95%E5%AE%9E%E4%BE%8B%E9%BB%98%E8%AE%A4%E5%8F%82%E6%95%B0)

4. 比如你想接口获取 token 之后写入 `request headers`

```tsx
// config.ts
import { extend } from 'umi-request'

const request = extend({
  prefix: '/api',
  timeout: 10000,
  headers: {
    system: '4',
  },
  mode: 'cors',
})

// somewhere
import request from './config'
import React from 'react'
import { useMount } from 'react-use'

const App: React.FC = () => {
  // 请求获取 token 之后，动态设置
  useEffect(() => {
    request('/token').then((res) => {
      request.extendOptions({
        headers: {
          token: res.data,
        },
      })
    })
  }, [])
  return <div>App</div>
}

export default App
```

**Comment by JustGogoing** [comment]
> 1. `umi-request` `extend` 是静态设置
> 2. 想要动态设置使用 `request.extendOptions`
> 3. 文档： https://github.com/umijs/umi-request/blob/master/README_zh-CN.md#%E6%9B%B4%E6%96%B0%E6%8B%93%E5%B1%95%E5%AE%9E%E4%BE%8B%E9%BB%98%E8%AE%A4%E5%8F%82%E6%95%B0
> 4. 比如你想接口获取 token 之后写入 `request headers`
> 
> ```tsx
> // config.ts
> import { extend } from 'umi-request'
> 
> const request = extend({
>   prefix: '/api',
>   timeout: 10000,
>   headers: {
>     system: '4',
>   },
>   mode: 'cors',
> })
> 
> // somewhere
> import request from './config'
> import React from 'react'
> import { useMount } from 'react-use'
> 
> const App: React.FC = () => {
>   // 请求获取 token 之后，动态设置
>   useEffect(() => {
>     request('/token').then((res) => {
>       request.extendOptions({
>         headers: {
>           token: res.data,
>         },
>       })
>     })
>   }, [])
>   return <div>App</div>
> }
> 
> export default App
> ```

感谢

**Comment by xoptimal** [comment]
这里并没有提及到 getDvaApp 呀,  请问 getDvaApp()._models 获取到的 state 数据, 为啥是更新前的
