### ISSUE TITLE
Dynamic routing not compatible with lint staged

### ISSUE THREAD

**Issue by khalibloo** [umijs/umi#4434]
This is a compatibility issue rather than a bug. When you have a file such as `src/pages/products/[id].tsx` and you try to commit changes to it, the lint staged script will produce the following error
```
[error] No matching files. Patterns tried: path/to/project/src/pages/products/[id].tsx !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
```
Notice that `[` and `]` are not escaped in the pattern.

**Comment by sorrycc** [comment]
It's the problem of eslint, next.js use the same pattern for dynamic routing.
