### ISSUE TITLE
[Bug] localIdentName 问题

### ISSUE THREAD

**Issue by xlsdg** [umijs/umi#4436]
## What happens?

手动配置 localIdentName，造成 antd 的样式文件也被 CSS Modules 处理了。

## Mini Showcase Repository(REQUIRED)

https://github.com/xlsdg/umi-dva-antd-starter

## How To Reproduce

**Steps to reproduce the behavior:**

```js
export default {
  cssLoader: {
    modules: {
      localIdentName: '[hash:base64:8]',
    },
  },
};
```

**Expected behavior**

排除 antd 样式文件

## Context

- **Umi Version**: v3.1.1
- **Node Version**: v12.16.2
- **Platform**: MacOS

**Comment by ycjcl868** [comment]
应该排除所有的 node_modules 下样式文件
