### ISSUE TITLE
umi layout生成的菜单如何生成

### ISSUE THREAD

**Issue by yaeSakuras** [umijs/umi#4439]
首先按照文档快速上手
```bash
yarn create @umijs/umi-app
```
创建好工程，然后依据文档
```js
import { defineConfig } from 'umi';

export default defineConfig({
+ layout: {},
  routes: [
    { path: '/', component: '@/pages/index' },
  ],
});
```
添加布局接着问题就好了。
然后通过约定路由创建页面，发现菜单无法生成没有说明如何配置。文档也没有相关描述。

然后通过配置路由的方式
```js
routes: [
    { path: '/', component: '@/pages/index' },
    { path: '/users', component: '@/pages/users'
  },
],
```
手动pages创建users.tsx，在添加路由。
菜单还是没出来。
配置了半天也没弄明白这个菜单到底如何出现。
开源不易，但是文档写的让人看不懂，也不敢在实际项目中使用和推广。

**Comment by zim-lee** [comment]
在插件plugin-layout那里，对应menu的配置

**Comment by leftstick** [comment]
参考这个 https://github.com/umijs/umi/issues/4095#issuecomment-610730633

**Comment by gouflv** [comment]
在不启用 plugin-layout  的情况下，是不是 menuDataRender 就没办法拿到路由配置的数据了?

**Comment by leftstick** [comment]
> 在不启用 plugin-layout 的情况下，是不是 menuDataRender 就没办法拿到路由配置的数据了?

理应如此，不然就是bug了

**Comment by travonf** [comment]
翻遍ProLayout和umijs官网文档，只提了菜单会自动生成，没提怎么配置，好坑。

**Comment by ILiuDongHui** [comment]
在启用了 layout 配置的情况下，菜单是根据扁平化的 routes 来产生的，这就导致另一个致命的问题，无法给所有的顶级路由再增加一个父组件，因为 ProLayout 的 Content 部分还需要增加一些固定的布局，比如点击菜单后在Content顶部展示选项卡

**Comment by deepred5** [comment]
```js
routes: [
    { path: '/', component: '@/pages/index' },
    { path: '/users', component: '@/pages/users'
  },
]
```
没用菜单生成的原因是少配置了`name`

```js
routes: [
    { path: '/', component: '@/pages/index', name: 'home' },
    { path: '/users', component: '@/pages/users', name: 'user' },
],
```
