### ISSUE TITLE
求 yaml 注释扩展路由功能替代方案

### ISSUE THREAD

**Issue by ouyangfan** [umijs/umi#4440]
**Umi 版本**：3.1.1
- 约定式路由，不知道在哪儿加判断条件。umi 升级前可以用 yaml 注释扩展路由。

**Comment by sorrycc** [comment]
看文档，约定式路由的文档里有。

**Comment by leftstick** [comment]
1. 什么样的 判断条件？
2. 文档[扩展路由属性](https://umijs.org/docs/convention-routing#%E6%89%A9%E5%B1%95%E8%B7%AF%E7%94%B1%E5%B1%9E%E6%80%A7)
