### ISSUE TITLE
umi3.x 不支持 SOCKET_SERVER 的环境变量后会导致微前端场景下 HMR host 有误

### ISSUE THREAD

**Issue by howel52** [umijs/umi#4441]
https://github.com/umijs/umi/blob/7717760445356c293827501e629a3a0cefa34fba/packages/bundler-webpack/bundled/webpackHotDevClient.js#L13155-L13157

https://github.com/umijs/umi/blob/8d089bbff0b8292005df2680473e773eca416abd/packages/preset-built-in/src/plugins/features/devScripts.ts#L17-L43

比如父应用在 `localhost:6000` ，子应用的 HMR 在 `localhost:5959`，`{}.SOCKET_SERVER` 导致 `env` 自定义 `host` 失效。

解法应该还挺多的，比如像 `@@/devScripts.js` 整成绝对路径，然后 host 从绝对路径里读；

但是没想明白的是 `SOCKET_SERVER` 这个 api 为何去掉，有什么考虑么 （另外貌似和文档不一致了，目前的文档里还有 `SOCKET_SERVER` 相关的章节）

**Comment by jockey100332** [comment]
> https://github.com/umijs/umi/blob/7717760445356c293827501e629a3a0cefa34fba/packages/bundler-webpack/bundled/webpackHotDevClient.js#L13155-L13157
> 
> https://github.com/umijs/umi/blob/8d089bbff0b8292005df2680473e773eca416abd/packages/preset-built-in/src/plugins/features/devScripts.ts#L17-L43
> 
> 比如父应用在 `localhost:6000` ，子应用的 HMR 在 `localhost:5959`，`{}.SOCKET_SERVER` 导致 `env` 自定义 `host` 失效。
> 
> 解法应该还挺多的，比如像 `@@/devScripts.js` 整成绝对路径，然后 host 从绝对路径里读；
> 
> 但是没想明白的是 `SOCKET_SERVER` 这个 api 为何去掉，有什么考虑么 （另外貌似和文档不一致了，目前的文档里还有 `SOCKET_SERVER` 相关的章节）

我需要配置子项目的webpack的output，在chinwebpack 配置后为生效，能否给一下你的代码，如何进行的修改

**Comment by howel52** [comment]
> 我需要配置子项目的webpack的output，在chinwebpack 配置后为生效，能否给一下你的代码，如何进行的修改

你可以暂时关了 hmr，或是通过 [xswitch](https://github.com/yize/xswitch) 从 client 层面 proxy 一下比较快

**Comment by jockey100332** [comment]
并不是响应时间慢的问题。我在子项目设置.umirc
```
  base: `/app1`,
  chainWebpack: (memo, { env, webpack, createCSSRule }) => {
    if (env === 'production') {
      memo.output.library = 'app1';
      memo.output.libraryTarget = 'umd'
      memo.output.jsonpFunction = 'webpackJsonp_app1';
    }
  }
```

在主项目中 仍然显示没有暴露出生命周期来,
```
Application 'app1' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in app1 entry
```

但是我已经在子项目的app.js 中导出，我感觉更像webpack 没有生效
```
export const qiankun = {
  // 应用加载之前
  async bootstrap(props) {
    console.log('app1 bootstrap', props);
  },
  // 应用 render 之前触发
  async mount(props) {
    console.log('app1 mount', props);
  },
  // 应用卸载之后触发
  async unmount(props) {
    ReactDOM.unmountComponentAtNode(document.getElementById('root-subapp'));
  },
};

```

**Comment by bluescurry** [comment]
现在有解决方案了吗？

**Comment by tw93** [comment]
最后有解决方案了吗
