### ISSUE TITLE
can't create antd-pro project with the last step "yes"

### ISSUE THREAD

**Issue by xiaoxintang** [umijs/umi#4443]
## What happens?
when i create antd-pro project with the last step press `y`,it will show me : `already exists and is not an empty directory.` but the dir was created just now

## How To Reproduce
1. create an empty dir 
2. entry the dir
3. yarn create umi
>the last step `Time to use better, faster and latest antd@4!`
>> if i press `y` it will show me : `already exists and is not an empty directory.`
>> if i press `n` it will git clone and create a directory,but i don't want i create 
>>> when press `n` & in windows ,it will have a error  `already exists and is not an empty directory.`

## Context

- **Umi Version**:
maybe 3.x
- **Node Version**:
v12.16.1
- **Platform**:
windows && macos

**Comment by Chazie9** [comment]
same
