### ISSUE TITLE
Top-Level await 支持

### ISSUE THREAD

**Issue by duwei54** [umijs/umi#4445]
babel插件 `@babel/plugin-syntax-top-level-await`
我看插件官方文档说[webpack@5's experiments.topLevelAwait](https://babeljs.io/docs/en/babel-plugin-syntax-top-level-await)支持
umi可以考虑内置么?

**Comment by sorrycc** [comment]
内置的是 webpack 4，babel 语法开了也没用。

**Comment by duwei54** [comment]
@sorrycc 云谦大佬  会不会考虑在 `@umijs/plugin-webpack-5` 插件添加支持呢 😄
