### ISSUE TITLE
关于tree-shaking 用法中一些不明之处

### ISSUE THREAD

**Issue by hopperhuang** [umijs/umi#4446]
配置tree-shaking 为 true 后，应该怎么做呢？
1. 需要在package.json中声明 sideEffects 字段吗？
比如，当项目所有文件都遵循es规范时，只需要声明 sideEffects 为false。
当项目中有某个文件not pure 的时候，声明该文件 sideEffects: [ './path/to/somefile']
2. 可以提供具体的用例么？很简单的即可。

谢谢

**Comment by xiaohuoni** [comment]
https://webpack.js.org/guides/tree-shaking/#clarifying-tree-shaking-and-sideeffects
