### ISSUE TITLE
@umijs/plugin-qiankun 没有办法接收到子组件的生命周期

### ISSUE THREAD

**Issue by jockey100332** [umijs/umi#4447]
我确信按照文档做了全部修改。代码如下：
```
// app.js
export const qiankun = {
  // 应用加载之前
  async bootstrap(props) {
    console.log('app1 bootstrap', props);
  },
  // 应用 render 之前触发
  async mount(props) {
    console.log('app1 mount', props);
  },
  // 应用卸载之后触发
  async unmount(props) {
    ReactDOM.unmountComponentAtNode(document.getElementById('root-subapp'));
  },
};
```
```
// umirc.js
 base: `/app2`,
  chainWebpack: (memo) => {
    memo.output
      .library('app2')
      .libraryTarget('umd')
      .jsonpFunction('webpackJsonp_app2')
  }
```
父组件正常渲染是没有问题的，只不过是props 的透传没有办法接收到，页面报错

```
Application 'app2' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in app2 entry
```

**Comment by JayWongwz** [comment]
哦

**Comment by jockey100332** [comment]
> 哦
嗯？ 是我的提问方式不对吗

**Comment by kuitos** [comment]
> // umirc.js
 base: `/app2`,
  chainWebpack: (memo) => {
    memo.output
      .library('app2')
      .libraryTarget('umd')
      .jsonpFunction('webpackJsonp_app2')
  }

不用配

> // 应用卸载之后触发
  async unmount(props) {
    ReactDOM.unmountComponentAtNode(document.getElementById('root-subapp'));
  },

不用配

**Comment by jockey100332** [comment]
> > // umirc.js
> > base: `/app2`,
> > chainWebpack: (memo) => {
> > memo.output
> > .library('app2')
> > .libraryTarget('umd')
> > .jsonpFunction('webpackJsonp_app2')
> > }
> 
> 不用配
> 
> > // 应用卸载之后触发
> > async unmount(props) {
> > ReactDOM.unmountComponentAtNode(document.getElementById('root-subapp'));
> > },
> 
> 不用配
```
一直报这个错误，在子项目中没有办法接收到父项目中传来的props
```
Uncaught app1: Application 'app1' died in status LOADING_SOURCE_CODE: You need to export the functional lifecycles in app1 entry
    at http://localhost:8001/umi.js:56245:25
    at step (http://localhost:8001/umi.js:94118:23)
    at Object.next (http://localhost:8001/umi.js:94099:53)
    at fulfilled (http://localhost:8001/umi.js:94089:58)
```

**Comment by xiaohuoni** [comment]
没问题的呀
![image](https://user-images.githubusercontent.com/11746742/79183615-80ae3d80-7e44-11ea-9f48-5a9e362c1d3d.png)
https://github.com/umijs/next-app/tree/009qiankun

**Comment by jockey100332** [comment]
> 没问题的呀
> ![image](https://user-images.githubusercontent.com/11746742/79183615-80ae3d80-7e44-11ea-9f48-5a9e362c1d3d.png)
> https://github.com/umijs/next-app/tree/009qiankun
我之前并不是使用的这个模版，而且根据官网的文档进行配置的，这个模版可以直接用作生产使用吗？

**Comment by jockey100332** [comment]
> 没问题的呀
> ![image](https://user-images.githubusercontent.com/11746742/79183615-80ae3d80-7e44-11ea-9f48-5a9e362c1d3d.png)
> https://github.com/umijs/next-app/tree/009qiankun
我对比了一下代码，是我在子项目中没有添加 slave， 我以为不配置可以不用写的

**Comment by xiaohuoni** [comment]
next-app看issues，几个关键问题，不建议用于生产哦。后续会提交到 pro 。用 pro 那边的提交提交内容用于生产，比较可靠。

**Comment by zhangfu-git** [comment]
遇到相同问题，发现是有子应用的package.json name有相同造成

**Comment by Plortinus** [comment]
> next-app看issues，几个关键问题，不建议用于生产哦。后续会提交到 pro 。用 pro 那边的提交提交内容用于生产，比较可靠。

你们的qiankun配置文档就是next-app的代码，为什么不建议用于生产...
