### ISSUE TITLE
请问支持异步修改路由配置么

### ISSUE THREAD

**Issue by liyuewen** [umijs/umi#4449]
我现在遇到了需要从接口中获取路由权限表，来添加到配置中。
第一，个想法是在高阶组件中来判断但是发现connect中不支持异步导致类型不匹配，
第二，我看文档中wrappers但是发现也不支持异步
第三，我现在发现只有在mapStateToProps可以进行异步操作，
但是我还是希望可以通过动态设置路由来解决。请问有办法么

**Comment by leftstick** [comment]
这个严格意义上也不是异步加载路由的问题。而是权限问题。

实际上，路由已经都存在了，只是你需要一个手段，获取某个api的返回值后来决定用户是否有访问当前页面的权限，对么？

如果是，转右[看这里](https://dfocusgroup.github.io/generator-umi/)

**Comment by liyuewen** [comment]
> 这个严格意义上也不是异步加载路由的问题。或者权限问题。
> 
> 实际上，路由已经都存在了，只是你需要一个手段，获取某个api的返回值后来决定用户是否有访问当前页面的权限，对么？
> 
> 如果是，转右[看这里](https://dfocusgroup.github.io/generator-umi/)

非常感觉，这个解决了我的问题
