### ISSUE TITLE
hooks model能否支持从pages中创建

### ISSUE THREAD

**Issue by cpocar** [umijs/umi#4450]
## Background

@umijs/plugin-model的hooks model能否效仿dva的model一样可以从pages下创建，这样页面的逻辑可以相对独立

## Proposal

hooks model支持从pages下创建

**Comment by cpocar** [comment]
感觉 完全以文件名作为useModel使用hooksModel时的唯一 方式太过死板，不如像namespace灵活。不利于model按模块划分

**Comment by xiaohuoni** [comment]
感觉不太适合在项目中重度使用usemodel。
