### ISSUE TITLE
umi配置proxy之后怎么加载服务端图片资源

### ISSUE THREAD

**Issue by wangruiStart** [umijs/umi#4451]
## 背景

图片上传中后，服务端返回的是相对路径，需要加上服务地址。request请求可以通过proxy代理。image中的src怎么代理呢

## 思路

> 描述大概的解决思路，可以包含 API 设计和伪代码等

## 跟进

- [ ] some task
- [ ] PR URL

**Comment by ycjcl868** [comment]
配置下：{ proxy: { path: '/images/',  ignorePath: true }

**Comment by wangruiStart** [comment]
用的ant design pro
![image](https://user-images.githubusercontent.com/21194195/79189277-e5bd5f80-7e53-11ea-91c3-e494efd6a4fe.png)

这样配之后还是没有生效。

element里面发现src还是相对路径
![image](https://user-images.githubusercontent.com/21194195/79189388-3339cc80-7e54-11ea-9cf2-e6507b61c285.png)

**Comment by xiaohuoni** [comment]
image 地址不需要代理吧？ image 的 src 又不存在跨域问题，直接拼接访问路径，不是可以嘛？

**Comment by wangruiStart** [comment]
> image 地址不需要代理吧？ image 的 src 又不存在跨域问题，直接拼接访问路径，不是可以嘛？

部署到服务器上肯定是不存在。但是如果服务器分开发，测试，生产环境。不同环境下上传的图片不可以互相访问。这就要求，image的src必须在前端拼好

**Comment by xiaohuoni** [comment]
> > image 地址不需要代理吧？ image 的 src 又不存在跨域问题，直接拼接访问路径，不是可以嘛？
> 
> 部署到服务器上肯定是不存在。但是如果服务器分开发，测试，生产环境。不同环境下上传的图片不可以互相访问。这就要求，image的src必须在前端拼好

直接在代码中拼接才对，你设置proxy，生产环境不可用的。
