### ISSUE TITLE
[缺陷]umi在过滤非react组件时无法识别纯字符串返回以及模板中tsconfig的include缺失

### ISSUE THREAD

**Issue by Inori-Lover** [umijs/umi#4452]
## What happens?
1. 当页面使用形如`return '<>something</>'`作为render值返回时，umi会认为这不是一个有效的组件从而过滤这个组件（页面）
2. create得到的默认模板，tsconfig中不包含`.umirc.ts`导致该文件无法正常享受ts校验、提示等

## 最小可复现仓库

https://github.com/Inori-Lover/umi_issue_report

## 复现步骤，错误日志以及相关配置
clone & start, 确认上述bug即可

## 相关环境信息

- **Umi 版本**：3.1.1
- **Node 版本**：v13
- **操作系统**：window

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/79183866-43967b00-7e45-11ea-8eeb-6590329fab92.png)

**Comment by ycjcl868** [comment]
约定式路由的 babel 解析问题

**Comment by ycjcl868** [comment]
@Inori-Lover  `yarn create umi`？

**Comment by Inori-Lover** [comment]
> @Inori-Lover `yarn create umi`？

`@umijs/umi-app`
