### ISSUE TITLE
【BUG】关于build内存飙升，打包失败的问题

### ISSUE THREAD

**Issue by phoema** [umijs/umi#4453]
#4423

## What happens?
你好，我们项目之前使用pro4，umi2，一直正常，看到pro升级到umi3，尝试更新了pro+umi3.1.1，修改了兼容性问题，在dev模式下能够正常调试，但是打包失败，内存溢出。
是umi3的问题吧？
我们尝试升级umi3的原因，主要是pro升级了，然后我们的antd版本从4.1.0还正常，再往上升就会出现国际化的问题，很多组件默认显示英文。
antd4.1.0没有问题，4.1.+都有国际化问题。UMI2是否存在antd的ConfigProvider的兼容问题？
升级到UMI3以后国际化就正常了。

所以想升级，但是发现pro、umi3遇到很多坑，填完以后就差最后一步编译打包了。。结果，内存占用飙升，尝试几次调整，均失败。
我们的升级分支的进度就一直停滞了。

请各位大神支援。
我翻了issue，发现一批类似问题，开新issue主要是为了随时查修改进度，见谅。

**Comment by ycjcl868** [comment]
Duplicate https://github.com/umijs/umi/issues/4423#issuecomment-613189198
