### ISSUE TITLE
umi ui 问题汇总

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#4456]
## What happens?

最佳实践中使用umi ui 的问题汇总。

## Mini Showcase Repository(REQUIRED)

https://github.com/umijs/next-app/tree/011ui

## How To Reproduce
见下方问题，重现步骤

## Context

- **Umi Version**: 3.1.1
- **Node Version**:10.13.0
- **Platform**:MacBook Pro (Retina, 15-inch, Mid 2015)
- **@umijs/preset-ui**: 2.1.10

> 无特殊说明，所有表现，均是 mini ui

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/79193457-40a78480-7e5d-11ea-99d2-56f3e6b31b32.png)

问题：添加区块失败
原因：将配置中的 `routes` 拆出来，放在 `config/routes.ts` 中。
个人意见：因为在文档中有引导用户将 `routes` 拆分到这个文件，因此我觉得这应该是一个需要支持的场景。另外，这个提示框截图之后就关闭了。原因是文件写了触发了 umi 重启。如果不支持，可以把后续未进行的步骤，输出到error.log。
比如这里如果能够告知用户，后续还需要在 `routes` 中配置，即可访问。
```ts
{
      name: '登录页',
      path: '/userlogin',
      component: './UserLogin',
    },
```
当前的流程，会让我很疑惑。提示添加失败了，但是文件存在，文件是都写完了还是没写完。我后续改如何使用，如何定位错误？

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/79194389-09d26e00-7e5f-11ea-97e6-5481e19495ed.png)

## 问题
启动默认语言与当前项目语言不一致。
## 个人意见
改不改好像都行，感觉统一会更好。

**Comment by xiaohuoni** [comment]
项目中使用了 `plugin-layout` 的情况，登录页面正确的配置，如下
```
  {
    // name: '登录页',
    path: '/userlogin',
    component: './UserLogin',
    layout: false,
  },
```
当前写入值为
```
{
      name: '登录页',
      path: '/userlogin',
      component: './UserLogin',
},
```

**Comment by xiaohuoni** [comment]
# 区块问题
login 区块，为什么要去除背景和头部厂牌？
实际效果：
![image](https://user-images.githubusercontent.com/11746742/79195892-a39b1a80-7e61-11ea-932a-b97d74a1475c.png)
真实效果：
![image](https://user-images.githubusercontent.com/11746742/79195937-b6155400-7e61-11ea-8496-6c5e45a2b658.png)
@chenshuai2144

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/79196134-0db3bf80-7e62-11ea-88d8-23ea51b403e9.png)

## 问题
只有 pages 或 page 目录下的页面才能插入资产
## 可能的原因
不明

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/79196737-32f4fd80-7e63-11ea-85b4-9cb6615d913d.png)

## 问题
操作按钮的文字，不居中。

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/79197060-b9114400-7e63-11ea-8019-0d7e410828c2.png)
## 问题
npm-debug.log 的行号，从0计数。和编译器里面的行数不一致，很难受。

## 重现步骤
UI 页面 选择任务-代码风格检测-执行（有错误时生成）

**Comment by ycjcl868** [comment]
> ![image](https://user-images.githubusercontent.com/11746742/79196134-0db3bf80-7e62-11ea-88d8-23ea51b403e9.png)
> 
> ## 问题
> 只有 pages 或 page 目录下的页面才能插入资产
> 
> ## 可能的原因
> 不明

这个 babel cache 导致，重新 start 才能出现可插入区域，这个问题从 umi 层修复

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/79198176-a5ff7380-7e65-11ea-8601-0e040aeadf63.png)

## 问题
添加之后，需要刷新页面，样式才有效。需要重启服务，mock服务才有效。

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/79198553-3fc72080-7e66-11ea-8e2b-3b6fc05d417b.png)

## 问题007
修改 ui 语言，刷新页面，会被重置成初始值。
## 个人建议
感觉可以和问题 002 一起处理

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/79198902-c24fe000-7e66-11ea-9c83-e4fa0388d0ae.png)

## 问题008
任务页面的这个配色，感觉有点突兀，链接是红色的，是正确的嘛？

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/79199151-21155980-7e67-11ea-8ef8-54af3817f2d1.png)
## 问题009
构建完成，查看分析
TypeError: Cannot read property 'dispose' of null
## 重现步骤
UI 页面，任务-构建-（等待构建完成）-（右上角）分析
![image](https://user-images.githubusercontent.com/11746742/79199308-63d73180-7e67-11ea-8079-3452496421fc.png)

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/79200244-b9f8a480-7e68-11ea-9176-0895a4972d14.png)

## 问题 010
在 ui 任务模块，点击构建。
###  问题1
构建时间超长：日志上显示29秒，实际100秒左右的构建时间（在项目中构建时间为31秒）
## 问题2
这个分析（ANALYZE=1）不可选，build 之后如何关闭这个进程，没有操作的地方。

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/79200985-e82ab400-7e69-11ea-8a42-fef1556b6eda.png)

## 问题011
看板中，早报，标题和时间显示重叠。

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/79201460-b1a16900-7e6a-11ea-9653-788cc3bccb0d.png)
## 问题 012
添加-区块-form-注册新用户
## 可能的原因
好像是我之前把自动引入去掉了 `import React from 'react';`，无需再引入。估计 ui 里面也要去掉。
修复这个问题，需要验证一下问题，添加完成，需要重启服务。
![image](https://user-images.githubusercontent.com/11746742/79201573-deee1700-7e6a-11ea-9be2-6855b9b7277f.png)

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/79201936-6471c700-7e6b-11ea-9b42-29e31ad4c8c0.png)

## 问题 013
小气泡的提示文字，都是中文。与项目的国际化配置无关，与ui的国际化配置也无关。

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/79202118-b4508e00-7e6b-11ea-93e1-7f0d185ca05a.png)
## 问题 014
日志记录的数据太少，操作了很多东西，打开看还是只有开启项目的日志，不知道这个日志在这里是记录哪些东西
## 可能的原因
添加区块，模版等操作，会重启 umi 服务。估计，日志只记录本次启动期间的操作（瞎猜的）。

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/79202347-101b1700-7e6c-11ea-91b1-24305bccb619.png)
## 问题015 
底部日志，打开，这个很像下载的 `至底部` 点击无反应。
是说现在这种状态已经是至底部的话，那应该可以有`至顶部`之类的操作。
![image](https://user-images.githubusercontent.com/11746742/79202579-66885580-7e6c-11ea-9e37-44865a277554.png)

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/79202733-9cc5d500-7e6c-11ea-8bac-b223acd32d76.png)
## 问题 016
底部这个版本号，`3.1.0` 不知道指的是什么，当前 umi 版本 `3.1.3` , preset-ui 版本 `2.1.10`。
鼠标移上去也没反应，点击也没反应。

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/79203068-1362d280-7e6d-11ea-81a4-1397eba918f2.png)
## 问题 017
底部终端的意义是什么呢？
## 可能的原因
mini 版本不够 mini ，
## 个人建议
多项目管理的，在 mini 版本不需要，比如底部的终端、日志、甚至整个任务板。因为 mini 版的启动是 `umi dev` ，要执行其他任务的时候，最好是关掉 `umi dev`。不然同一个项目文件路径，执行不同的命令，可能有未知的错误。

**Comment by xiaohuoni** [comment]
## 问题 018
项目语言猜测错误，js项目，安装的区块是 ts 的
相关issues：https://github.com/ant-design/ant-design-pro/issues/6274

**Comment by xiaohuoni** [comment]
这里还有一些 https://github.com/umijs/umi/issues/3296

**Comment by tigerxiongj** [comment]
> ## 问题 018
> 项目语言猜测错误，js项目，安装的区块是 ts 的
> 相关issues：[ant-design/ant-design-pro#6274](https://github.com/ant-design/ant-design-pro/issues/6274)
> 
> ## 重现步骤
> 1、npm create umi
> 2、选择ant design pro 版本4
> 3、选择使用javascript
> 5、选择创建 simple 的 pro 项目
> 6、安装好后启动项目
> 7、添加模版

js创建项目，插入页面和block是ts，这个问题找到原因了吗？有计划什么时候解吗？

**Comment by SappersCode** [comment]
问题19:

**Comment by SappersCode** [comment]
问题19:

1.yarn create umi
2.选择 ant design pro 版本4
3. yarn add @umijs/preset-ui -D
4.UMI_UI=1 umi dev启动项目
5.进入antd pro页面点击umi气泡报错:Assertion failed: new_time >= loop->time, file c:\ws\deps\uv\src\win\core.c, line 309
6网上搜索答案:是node和inter处理器兼容问题,能否帮忙测试一下
node.js版本：12.16.0
硬件:笔记本联想yoga940,英特尔（R）酷睿TM i7-1065G7
Windows 10专业版1903
OS版本内部版本18362.356
