### ISSUE TITLE
umi v3.x 配置全局moment 和antd 语言在哪设置？

### ISSUE THREAD

**Issue by GeNa-jj** [umijs/umi#4459]
umi v2.x 的版本在 .umirc.js 配置如下设置：
locale: {
    default: 'zh-CN',
    baseNavigator: true,
    antd: true
}

umi v3.x 文档没有了这个配置项

强行设置有效，但浏览器会出现如下警告：
devScripts.js:5035 Warning: The current popular language does not exist, please check the locales folder!

**Comment by xiaohuoni** [comment]
https://umijs.org/zh-CN/plugins/plugin-locale#%E6%9E%84%E5%BB%BA%E6%97%B6%E9%85%8D%E7%BD%AE

```ts
export default {
  locale: {
    default: 'zh-CN',
    antd: false,
    title: false,
    baseNavigator: true,
    baseSeparator: '-',
  }
}
```

**Comment by GeNa-jj** [comment]
@xiaohuoni 
设置了还是报错
Warning: The current popular language does not exist, please check the locales folder!
