### ISSUE TITLE
umi-test 单元测试使用记录

### ISSUE THREAD

**Issue by arvinxx** [umijs/umi#446]
在这里记录下 umi-test 单测的一些使用情况。完备之后会提个 PR 给官方文档。

**Comment by arvinxx** [comment]
umi test Cli

目前 `umi-test` 支持两个参数选项 `--watch` 和 `--coverage`，均为`jest` 自带的方法。

个人希望之后能够提供匹配测试文件路径的选项，便于进行单个测试文件的测试。

**Comment by arvinxx** [comment]
# Css Modules Mock
大多数情况下我们都会使用 Css Modules 进行样式命名，但这就会导致进行测试时不清楚随机生成的 className 到底是什么。为了解决这个问题，umi-test 引入了 `identity-obj-proxy` 库来 mock Css Modules 的 className。在实际使用时只需要使用样式文件中的 css 类名即可。
```jsx
// App Component
import React, { Component } from 'react';
import styles from './App.css';
export default class App extends Component {
  render() {
    return (
        <h1 className={styles.hello}>Hello, world!</h1>
    );
  }
}
```

```js
// test
import React from 'react';
import { shallow } from 'enzyme';
import App from './App';

it('App Component should be render', () => {
  expect(wrapper.find('.hello').length).toEqual(1);
}

// test will pass
```

如果需要进行 config 覆盖，可以在 `jest.config.js` 中配置 `moduleNameMapper` 参数。
``` js
module.exports={
  //...
  moduleNameMapper: {
        '\\.(css|less|sass|scss)$': require.resolve('your-package'),
      },
  //...
}
```

**Comment by arvinxx** [comment]
# umi-test 默认配置
```
 const config = {
    rootDir: process.cwd(),
    setupFiles: [
      require.resolve('./shim.js'),
      require.resolve('./setupTests.js'),
    ],
    transform: {
      '\\.jsx?$': require.resolve('./transformers/jsTransformer'),
      '\\.tsx?$': require.resolve('./transformers/tsTransformer'),
    },
    testMatch: ['**/?(*.)(spec|test|e2e).(j|t)s?(x)'],
    moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx'],
    setupTestFrameworkScriptFile: require.resolve('./jasmine'),
    moduleNameMapper: {
      '\\.(css|less|sass|scss)$': require.resolve('identity-obj-proxy'),
    },
    globals: {
      'ts-jest': {
        useBabelrc: true,
      },
    },
    ...(coverage
      ? {
          collectCoverageFrom: [
            'pages/**/*.{ts,tsx,js,jsx}',
            'src/**/*.{ts,tsx,js,jsx}',
            '!**/*.d.ts',
          ],
          collectCoverage: true,
          coveragePathIgnorePatterns: [
            `/${pagesPath}/.${libraryName}/`,
            `/${pagesPath}/.${libraryName}-production/`,
          ],
        }
      : {}),
    ...(userJestConfig || {}),
  };
```

**Comment by arvinxx** [comment]
# jest 自定义配置

如果需要进行自定义 jest 配置，需要在根目录下添加 `jest.config.js` 文件。config 中的配置将会覆盖默认配置。

**Comment by arvinxx** [comment]
# Dva 组件测试方式

被 dva connect 的 React 组件 使用 `WrappedComponent`  属性获取包裹后的组件。


Ref : [测试 dva 包装组件](https://pro.ant.design/docs/ui-test-cn#%E6%B5%8B%E8%AF%95-dva-%E5%8C%85%E8%A3%85%E7%BB%84%E4%BB%B6)
```js
import React from 'react';
import { shallow } from 'enzyme';
import Dashboard from './Dashboard';

it('renders Dashboard', () => {
  // 使用包装后的组件
  const wrapper = shallow(
    <Dashboard.WrappedComponent user={{ list: [] }} />
  );
  expect(wrapper.find('Table').props().dataSource).toEqual([]);
});
```

**Comment by arvinxx** [comment]
# 测试文件中引入图片文件报错
如果在 js 或 ts 文件中引入了图片文件，在测试时会进行报错
```
\path\to\img\1.jpg:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,glo
bal,jest){����

          ^

    SyntaxError: Invalid or unexpected token

    > 1 | import photo1 from '../assets/photos/1.jpg';
       2 | 
```
umi-test 的配置中没有mock掉图片资源，因此 jest 加载会出错。

解决方案是在项目目录下新建 `jest.config.js` ，添加一条 `moduleNameMapper` 的配置项。 `moduleNameMapper` 配置项用于 Mock 相应的文件资源。

```json
{
  "moduleNameMapper": {
    "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js",
  },
}
```

` "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$"` 该项为匹配各种格式的资源文件，`"<rootDir>/__mocks__/fileMock.js"` 指用 `./__mocks__/fileMock.js` 文件进行替换。

因此，我们需要在根目录下新建 `__mocks__`文件夹，增加一个 `fileMock.js` 文件，内容随意填写，只要有输出即可。最简单的就是
```js
// fileMock.js
export default {};
```
当然，路径与文件名都可以自行替换。

**Comment by arvinxx** [comment]
# Path Alias 在 Jest 中的使用

在 Webpack 中设置过的 path alias 在 jest 中是无法识别的。因此我们需要为 jest 添加 path alias 设置。
例如在 webpackrc 中，alias 设置如下：
```js
   alias: {
    '@/components': resolve(__dirname, './src/components'),
    '@/utils': resolve(__dirname, './src/utils'),
    },
```
> PS： 以 @ 开头主要是为了与 node_modules 区分开来，大家可以根据自己的喜好进行命名

在 jest 的配置文件 `jest.config.js` 中，在  `moduleNameMapper` 这一栏中添加对应的设置：
```js
   moduleNameMapper: {
    '@/components': '<rootDir>/src/components',
    '@/utils': '<rootDir>/src/utils',
    },
```
> PS：<rootdir>即项目根目录

如此 jest 就可以识别 Path Alias 了。

参考：https://doc.ebichu.cc/jest/docs/zh-Hans/webpack.html

**Comment by jsw0528** [comment]
```
"moduleNameMapper": {
  "@(.*)$": "<rootDir>/src/$1"
}
```

这么写就行，不用挨个配置

**Comment by hejun01** [comment]
> # Dva 组件测试方式
> 被 dva connect 的 React 组件 使用 `WrappedComponent` 属性获取包裹后的组件。
> 
> Ref : [测试 dva 包装组件](https://pro.ant.design/docs/ui-test-cn#%E6%B5%8B%E8%AF%95-dva-%E5%8C%85%E8%A3%85%E7%BB%84%E4%BB%B6)
> 
> ```js
> import React from 'react';
> import { shallow } from 'enzyme';
> import Dashboard from './Dashboard';
> 
> it('renders Dashboard', () => {
>   // 使用包装后的组件
>   const wrapper = shallow(
>     <Dashboard.WrappedComponent user={{ list: [] }} />
>   );
>   expect(wrapper.find('Table').props().dataSource).toEqual([]);
> });
> ```

组件中如果在componentDidMount使用dispatch发起请求的话，test的时候会报错``` TypeError: dispatch is not a function```,该如何解决呢

**Comment by GreatAuk** [comment]
umi 内置的测试脚本有文档吗? 想知道怎么更新快照 ..., 还有怎么查看单个文件的 coverage

**Comment by GreatAuk** [comment]
问下使用了 [@umijs/plugin-model](https://umijs.org/zh-CN/plugins/test) 的组件怎么测试了？

**Comment by hiyangguo** [comment]
> # umi-test 默认配置
> umi-test 默认配置覆盖了日常 90% 以上的需求，包括 Typescript 支持、转义 jsx/tsx、Css Modules Mock、测试覆盖率等。
> 
> ```js
>  const config = {
>     rootDir: process.cwd(),
>     setupFiles: [
>       require.resolve('./shim.js'),
>       require.resolve('./setupTests.js'),
>     ],
>     transform: { 
>       '\\.jsx?$': require.resolve('./transformers/jsTransformer'),
>       '\\.tsx?$': require.resolve('./transformers/tsTransformer'),
>     },
>     testMatch: ['**/?(*.)(spec|test|e2e).(j|t)s?(x)'],
>     moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx'],
>     setupTestFrameworkScriptFile: require.resolve('./jasmine'),
>     moduleNameMapper: {
>       '\\.(css|less|sass|scss)$': require.resolve('identity-obj-proxy'),
>     },
>     globals: {
>       'ts-jest': {
>         useBabelrc: true,
>       },
>     },
>     ...(coverage                                   // 判断是否有测试覆盖
>       ? {
>           collectCoverageFrom: [
>             'pages/**/*.{ts,tsx,js,jsx}',
>             'src/**/*.{ts,tsx,js,jsx}',
>             '!**/*.d.ts',
>           ],
>           collectCoverage: true,
>           coveragePathIgnorePatterns: [
>             `/${pagesPath}/.${libraryName}/`,
>             `/${pagesPath}/.${libraryName}-production/`,
>           ],
>         }
>       : {}),
>     ...(userJestConfig || {}),                   // 判断是否有自定义配置
>   };
> ```
配置文件地址 [./test/src/createDefaultConfig/createDefaultConfig.ts](https://github.com/umijs/umi/blob/v3.5.26/packages/test/src/createDefaultConfig/createDefaultConfig.ts)

**Comment by DongDeming** [comment]
> 



> 问下使用了 [@umijs/plugin-model](https://umijs.org/zh-CN/plugins/test) 的组件怎么测试了？

使用Provider 包裹 `import Provider from '@@/plugin-model/Provider';`
