### ISSUE TITLE
打包时能否使用chunkhash打包，即修改过的文件更改hash, 未修改的不变hash

### ISSUE THREAD

**Issue by xiaoyierle** [umijs/umi#4460]
现在每次打包都会改变所有的hash ,webpack 中有个 hash  和 chunkhash 的配置， umi 中是否也可以按照这个逻辑整一个？

**Comment by hopperhuang** [comment]
同样遇到此问题，增加新页面后，旧页面的hash变化了。

**Comment by hopperhuang** [comment]
@xiaoyierle 
https://github.com/umijs/umi/issues/4570 
你看这个方法对你是否有用。

**Comment by xiaohuoni** [comment]
见 https://github.com/umijs/umi/issues/4570
