### ISSUE TITLE
npm start 正常运行，但是 npm run build 后的文件 run 起来页面空白， layout 里面的 props.children 好像没有插入，页面也没有报错

### ISSUE THREAD

**Issue by huiop368** [umijs/umi#4462]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：2.7.7
- **Node 版本**：11.10.1
- **操作系统**：mac

**Comment by xuwenqing2014** [comment]
这个问题解决了么，我也出现了，不知道咋回事
