### ISSUE TITLE
在config.local.ts中配置dynamicImport，但没有在config.ts中配置，build时不起作用

### ISSUE THREAD

**Issue by sujingclg** [umijs/umi#4463]
## What happens?
在config.local.ts中配置dynamicImport，但没有在config.ts中配置此项，则仅在dev开发中生效，build时不起作用，仍会打包到一起

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：3.1.1
- **Node 版本**：12.13.0
- **操作系统**：Mac

**Comment by leftstick** [comment]
`.local.ts` 的确只会在 `umi dev` 时有效。所以如果你希望 `dynamicImport` 配置在 `build` 时工作：

1. 要么放到 `config/config.ts` 里，然后直接 `umi build`。
2. 要么放到其他变量对应的配置文件，如`config/config.prod.ts`，然后`UMI_ENV=prod umi build`
