### ISSUE TITLE
@umijs/plugin-layout配置Route生成侧边栏菜单，但是没有生成面包屑

### ISSUE THREAD

**Issue by GGBO0M** [umijs/umi#4464]
## What happens?

尝试使用@umijs/plugin-layout 在项目中配置layout，在查阅 @ant-design/pro-layout文档，应该在配置Route后，会自动生成菜单栏以及面包屑，但是实际上却只有菜单栏，breadcrumbRender的回调中可以拿到面包屑数据。是否umi的layout不支持自动生成面包屑

## How To Reproduce

1. 使用 yarn create @umijs/umi-app 创建项目
2. 在umirc.ts中配置routes
```js
  routes: [
    {
      name: 'demo1',
      path: '/demo1',
      routes: [
        {
          name: 'demo2',
          path: 'demo2',
          component: 'demo2',
        },
        {
          name: 'demo3',
          path: 'demo3',
          component: 'demo3',
        },
      ],
    }, {
      name: 'demo',
      path: '/demo',
      component: 'demo',
    },
  ],
```

## Context

- **Umi Version**: v3.1.1
- **Node Version**: 12.10.0
- **Platform**: mac

**Comment by lichangchao15442** [comment]
同问，蹲一个回答。

**Comment by xiaohuoni** [comment]
试试最新版本的插件

**Comment by sjzpengyuyan** [comment]
请问有解决了吗？
