### ISSUE TITLE
@umijs/plugin-layout配置routes生成侧边栏菜单未显示对应菜单名

### ISSUE THREAD

**Issue by lichangchao15442** [umijs/umi#4470]
## What happens?

@umijs/plugin-layout配置routes,配置了name，没有显示出来。
相关路由代码：
```
routes: [
    {
      path: '/',
      component: '../layouts/BlankLayout',
      routes: [
        {
          path: '/user',
          component: '../layouts/UserLayout',
          routes: [
            {
              path: '/user',
              redirect: '/user/login',
            },
            {
              name:'login',
              path: '/user/login',
              component: './user/login',
            },
          ],
        },
        {
          path: '/',
          component: '../layouts/BasicLayout',
          routes: [
            {
              path: '/',
              redirect: '/home',
            },
            {
              name: '首页',
              path: '/home',
              component: './home',
            },
          ],
        },
      ],
    },
  ],
```

应该显示home菜单栏，但是没有显示。
## 相关环境信息

- **Umi 3.1.1**：
- **Node 版本 v13.12.0**：
- **操作系统 mac**：

**Comment by xiaohuoni** [comment]
使用 `@umijs/plugin-layout` 应该是默认接了一层 layout。不需要这个的，应该通过 `layout:false` 去掉，而不是像以前那样子整个配置，如果需要像以前那样子使用，可以不用 `@umijs/plugin-layout`

**Comment by lichangchao15442** [comment]
> 使用 `@umijs/plugin-layout` 应该是默认接了一层 layout。不需要这个的，应该通过 `layout:false` 去掉，而不是像以前那样子整个配置，如果需要像以前那样子使用，可以不用 `@umijs/plugin-layout`

所以，现在配置路由的数据结构是更加扁平化了，因为不需要再额外配置layout（除登陆需求外）吗？

**Comment by xiaohuoni** [comment]
> > 使用 `@umijs/plugin-layout` 应该是默认接了一层 layout。不需要这个的，应该通过 `layout:false` 去掉，而不是像以前那样子整个配置，如果需要像以前那样子使用，可以不用 `@umijs/plugin-layout`
> 
> 所以，现在配置路由的数据结构是更加扁平化了，因为不需要再额外配置layout（除登陆需求外）吗？

是这个意思，最简单demo可以查看https://github.com/umijs/next-app/tree/002layout
