### ISSUE TITLE
@umijs/plugin-layout rightRender没有渲染出结果

### ISSUE THREAD

**Issue by lichangchao15442** [umijs/umi#4472]
What happens?
在config下的layout中配置rightRender，右上角没有渲染

```
layout {
 rightRender:() => 'xxxxx'
}
```
期望：右上角能够显示xxxxx，
结果：未显示
疑问：难道rightRender不是这么使用的吗（希望umi的文档能够多提供一些在线的demo）

# 相关环境信息

- **Umi 3.1.1**：
- **Node 版本 v13.12.0**：
- **操作系统 mac**：

**Comment by xg4** [comment]
[https://umijs.org/zh-CN/plugins/plugin-layout#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE](https://umijs.org/zh-CN/plugins/plugin-layout#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE)

在 `src/app.js` 中配置，不是在 `config` 中

**Comment by lichangchao15442** [comment]
> https://umijs.org/zh-CN/plugins/plugin-layout#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE
> 
> 在 `src/app.js` 中配置，不是在 `config` 中

在app.tsx中配置 会export  export后不需要在config中导入传给layout吗？
umi3.0文档中说：‘除了下面的插件支持的特有配置外，运行时配置支持所有的构建时配置并透传给 @ant-design/pro-layout’，具体是什么意思呢？

**Comment by xg4** [comment]
`config` 中配置一些静态的设置

`app.tsx` 中只需 `export`，`umi` 会自动 `import`

**Comment by lichangchao15442** [comment]
我找到我自己没有显示的原因的（在app.tsx中配置），哈哈 ，自己太粗心，把app.tsx放到src/pages下面了，应该是src/app.tsx。
