### ISSUE TITLE
@umijs/plugin-crossorigin 不生效问题

### ISSUE THREAD

**Issue by macsen110** [umijs/umi#4473]
1. publicPath 为 cdn 域名， 生成的script 标签不带crossorigin 属性

**Comment by ycjcl868** [comment]
给个复现

**Comment by blankul** [comment]
我也遇到了同样的问题：
publicPath 设置为 oss 的地址，生成 script 标签就不带 crossorigin 属性，不设置的话 就是正常的 @ycjcl868

**Comment by blankul** [comment]
我看源码那部分判断了，可不可以加一个配置来控制，不要一刀切，不然 cdn 这种场景没法满足

![image](https://user-images.githubusercontent.com/27713538/86987948-c2dbe680-c1c9-11ea-9c21-28e79e509f38.png)

**Comment by sorrycc** [comment]
可以提个 PR，加个配置项，如果 extraScripts: true，则不加这条限制。

**Comment by HopperDai** [comment]
@sorrycc 这个问题解决方案实现了吗

**Comment by ColinChen2** [comment]
crossorigin: {
    include: [/^https:\/\/example.com/],
},
