### ISSUE TITLE
umi 3.1.1 className 动态后缀？

### ISSUE THREAD

**Issue by SmartWrh** [umijs/umi#4474]
如何关闭这个特性？
className=‘activeBlock’ 变为 className='activeBlock___2kiz8'

**Comment by XSmarter** [comment]
+1 
特殊业务，不想要这个特性，麻烦提供个可关闭的方案，谢谢

**Comment by sorrycc** [comment]
那不会冲突吗？

**Comment by XSmarter** [comment]
https://umijs.org/zh-CN/guide/upgrade-antd-pro-to-umi-3#%E9%85%8D%E7%BD%AE%E5%B1%82%E8%BF%81%E7%A7%BB
安装页面上的配置添加 cssLoader 就可以了

**Comment by sorrycc** [comment]
import styles from './x.css'; // 动态
import './x.css'; // 非动态

3.x 开始就是这样的。
