### ISSUE TITLE
umi v3.1.1 webstorm @別名路径提示找不到。

### ISSUE THREAD

**Issue by GeNa-jj** [umijs/umi#4477]
umi 从v2 升级到 v3.1.1 webstorm @別名路径提示找不到。但是能用。我用的是js、eslint。

![image](https://user-images.githubusercontent.com/36023435/79409352-4ffb0f00-7fd0-11ea-9a6f-9bd96f75d0ae.png)

需要配置什么吗

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/4645 相同的问题
