### ISSUE TITLE
umi3在使用了plugin-layout和开启antd的dark主题后会冲突报错

### ISSUE THREAD

**Issue by avalonWx** [umijs/umi#4478]
umi3按照文档设置了dark为true，同时开启了plugin-layout的antd pro布局，会导致如下图的错误
![image](https://user-images.githubusercontent.com/37049644/79413598-f2b88b00-7fda-11ea-9a87-f20593660c79.png)
我在antd pro那边看到可能需要umi-plugin-antd-theme插件来支持，于是加载依赖后不但主题没有按照设置的变更，还导致组件中less文件和scss文件的样式全部失效，于是现在只能放弃使用plugin-layout

**Comment by ycjcl868** [comment]
@AshoneA @chenshuai2144  cc

**Comment by AshoneA** [comment]
@avalonWx 请问你 `antd` 和 `umi-plugin-antd` 版本分别是多少？

**Comment by avalonWx** [comment]
antd: 4.1.3,
umi-plugin-antd-theme: 2.1.2

**Comment by AshoneA** [comment]
能给个最小复现仓库吗？因为其实我没怎么用 `antd-pro` 加 `umi-plugin-antd-theme` 这个东西。

**Comment by avalonWx** [comment]
https://github.com/avalonWx/umiJS-webApp
现在是两个问题
1：我在放入仓库后重新加载了一次依赖，错是不会报了，但是按照umi文档里在.umirc.ts文件里设置antd:{ dark:true }直接就毫无作用了，哪怕是不启用layout的pro主题布局；
2：使用umi-plugin-antd-theme会导致less和scss文件不能加载到组件中，仓库里面的demo我暂时删除了umi-plugin-antd-theme（问题1的优先级应该高一点，问题2可能暂时先不用理会）

**Comment by AshoneA** [comment]
@avalonWx 麻烦你提供的仓库了哈，问题一的话已经[解决](https://github.com/ant-design/ant-design/pull/23243)了，这周 antd 那边会发一版 4.1.4 ，你到时候更新下就会 OK 了。



如果需要急用的话，可以参考下这个解决方案： https://github.com/ant-design/ant-design/issues/23237#issuecomment-613290095

**Comment by AshoneA** [comment]
@ycjcl868 应该可以关了
