### ISSUE TITLE
umi3.x打包完devScripts.js modules[moduleId].call 最后一个参数后面多了逗号',' ，导致在IE11下面报错

### ISSUE THREAD

**Issue by finneenchueng** [umijs/umi#4482]
http://localhost:8001/@@/devScripts.js
报错位置：25行第5列

## 最小可复现仓库
https://github.com/finneenchueng/umi3xtest.git

## 相关环境信息

- **Umi 版本**：3.1.1
- **Node 版本**：10.15.3
- **操作系统**：Mac

**Comment by LeoHuiyi** [comment]
我这边也有复现 这文件低版本都不兼容

**Comment by sorrycc** [comment]
开发时用旧版本浏览器？

**Comment by LeoHuiyi** [comment]
嵌入第三方的设备开发

**Comment by LeoHuiyi** [comment]
@sorrycc

**Comment by finneenchueng** [comment]
> 开发时用旧版本浏览器？
IE11是最低要求；生产打包完之后umi.js IE11就报语法错误。定位错误还得回到开发环境用IE11

**Comment by LeoHuiyi** [comment]
![image](https://user-images.githubusercontent.com/8001457/80596344-cf6cf180-8a58-11ea-9e9f-59692a7aa64f.png)



![image](https://user-images.githubusercontent.com/8001457/80595864-01318880-8a58-11ea-9a94-e84431e643cc.png)
能否加个开关 webpackHotDevClient可以加入entry？

**Comment by chemdemo** [comment]
+1，ios低版本也报错了，有解决方案吗 @sorrycc

**Comment by singhello** [comment]
解决了吗？

**Comment by icarusysuper** [comment]
@sorrycc 有时候需要在低版本的内核上开发调试

**Comment by oliviaxtli** [comment]
请问解决了吗？

**Comment by blueju** [comment]
@sorrycc 请问解决了吗？

**Comment by blueju** [comment]
> ![image](https://user-images.githubusercontent.com/8001457/80596344-cf6cf180-8a58-11ea-9e9f-59692a7aa64f.png)
> 
> ![image](https://user-images.githubusercontent.com/8001457/80595864-01318880-8a58-11ea-9a94-e84431e643cc.png)
> 能否加个开关 webpackHotDevClient可以加入entry？

请问你这个是解决方案吗？

**Comment by quicklearning123** [comment]
请问下大家怎么解决的? 怎么问题close了

**Comment by wzc0x0** [comment]
在低版本浏览器内核中开发，有这样的需求，毕竟antd-pro使用的人也不少。
