### ISSUE TITLE
使用@umijs/umi-app创建的项目Icon不显示，控制台出现warning

### ISSUE THREAD

**Issue by zim-lee** [umijs/umi#4483]
## What happens?
`devScripts.js:5035 Warning: In order to ensure compatibility with antd@4, we will delete the configuration icon in the next version, details can be viewed.
为了兼容 antd@4，我们会在下个版本删除配置 icon: string 生成icon的用法。请查看
https://pro.ant.design/blog/antd-4.0-cn 寻找解决方式！`
按照链接的说明安装插件后无效，添加插件配置提示插件已注册
到底如何才能使用antd4的icon，其他类似的issue都是关闭状态，也没有给出解决办法，难道其他人都正常？？？？个例？？？？？？？？？

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

[umi-demo1](https://github.com/zim-lee/umi-demo1)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

`yarn create @umijs/umi-app`

**Expected behavior** 1. 2.

## Context

`
"dependencies": {
    "@umijs/preset-react": "1.x",
    "@umijs/test": "^3.1.1",
    "lint-staged": "^10.0.7",
    "prettier": "^1.19.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "umi": "^3.1.1",
    "umi-plugin-antd-icon-config": "^2.0.3",
    "yorkie": "^2.0.0"
  }
`

- **Umi Version**: 3.1.1
- **Node Version**: 12.6
- **Platform**: win10

**Comment by CorleoneYang** [comment]
同样遇到了这样的 Warning，按照那个链接操作，提示「plugin umi-plugin-antd-icon-config is already registered」

#### 完整复现操作
```shell
mkdir demo && cd demo
yarn create @umijs/umi-app
yarn add umi-plugin-antd-icon-config -D
```
然后编辑 .umirc.ts ，修改成如下
```ts
import { defineConfig } from 'umi';

export default defineConfig({
  plugins:['umi-plugin-antd-icon-config'],
  layout:{},
  nodeModulesTransform: {
    type: 'none',
  },
  routes: [
    { path: '/', component: '@/pages/index',menu:{name:"测试",icon:"github"} },
  ],
});

```
然后再
```shell
yarn start
```
就会提示 Error「plugin umi-plugin-antd-icon-config is already registered」，如下：

```
yarn run v1.15.2
$ umi dev
plugin umi-plugin-antd-icon-config is already registered by /Users/corleoneyang/Projects/reproduction/node_modules/umi-plugin-antd-icon-config/lib/index.js, plugin from /Users/corleoneyang/Projects/reproduction/node_modules/umi-plugin-antd-icon-config/lib/index.js register failed.
Error: plugin umi-plugin-antd-icon-config is already registered by /Users/corleoneyang/Projects/reproduction/node_modules/umi-plugin-antd-icon-config/lib/index.js, plugin from /Users/corleoneyang/Projects/reproduction/node_modules/umi-plugin-antd-icon-config/lib/index.js register failed.
    at Service.registerPlugin (/Users/corleoneyang/Projects/reproduction/node_modules/@umijs/core/lib/Service/Service.js:420:13)
    at Service.initPlugin (/Users/corleoneyang/Projects/reproduction/node_modules/@umijs/core/lib/Service/Service.js:404:10)
    at Service.initPresetsAndPlugins (/Users/corleoneyang/Projects/reproduction/node_modules/@umijs/core/lib/Service/Service.js:313:12)
    at /Users/corleoneyang/Projects/reproduction/node_modules/@umijs/core/lib/Service/Service.js:227:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/corleoneyang/Projects/reproduction/node_modules/@umijs/core/lib/Service/Service.js:106:103)
    at _next (/Users/corleoneyang/Projects/reproduction/node_modules/@umijs/core/lib/Service/Service.js:108:194)
    at /Users/corleoneyang/Projects/reproduction/node_modules/@umijs/core/lib/Service/Service.js:108:364
    at new Promise (<anonymous>)
    at /Users/corleoneyang/Projects/reproduction/node_modules/@umijs/core/lib/Service/Service.js:108:97
```

**Comment by chenshuai2144** [comment]
插件已经安装了 不需要重复安装 可能是你的icon在新的antd中不存在了

**Comment by zim-lee** [comment]
> 插件已经安装了 不需要重复安装 可能是你的icon在新的antd中不存在了

@chenshuai2144 已经核实过了，不是这个问题，图标都是从`antd4`的官网复制的，按照`layout`的说明去掉`Outlined`之类的后缀，小写，每个图标都只展示成字符。而且即使图标不存在了，也解释不了控制台的warning

**Comment by xiaohuoni** [comment]
@CorleoneYang 在umi@3中，以 `umi-plugin`、`@umijs\`、`umi-presets`开头的包，只要安装了，就会自动被注册，不需要再 `config` 中使用，`plugins`配置使用。

**Comment by xiaohuoni** [comment]
@zim-lee 配置打平了就行，兼容旧的写法，我提交PR了。
```
{
        path: '/',
        component: '@/pages/index',
        name: '欢迎',
        icon: 'smile',
    }
```

**Comment by zim-lee** [comment]
@chenshuai2144 打平也不行，到转换的时候icon变成了react element对象，调用`toUpperCase`报错，这是啥情况
`TypeError: Cannot read property 'toUpperCase' of undefined`

```js
{$$typeof: Symbol(react.element), type: {…}, key: null, ref: null, props: {…}, …}
$$typeof: Symbol(react.element)
key: null
props: {}
ref: null
type: {$$typeof: Symbol(react.forward_ref), render: ƒ}
_owner: null
_store: {validated: false}
_self: null
_source: null
__proto__: Object
```

**Comment by xiaohuoni** [comment]
@zim-lee 我在这里重试配置打平是可以的。https://github.com/umijs/next-app/tree/002layout 你试试，不行请提供重现demo

**Comment by zim-lee** [comment]
嗯，新拉一个项目确实可用，我再仔细检查下配置:confused:

**Comment by ChenYCL** [comment]
经常这样 包括 @umijs/plugin-model 这些 总是提醒已经注册,然后跑不起来
