### ISSUE TITLE
ESLINT 局部忽略是如何执行的

### ISSUE THREAD

**Issue by xy163** [umijs/umi#4485]
作者您好：
我遇到了一个eslint问题。
比如我有一个工具文件 xxx.js
我不想要去eslint这个文件的所有内容。

如果以前我会这么写： /* eslint-disable */ 
我看到umi中有一个 .prettierignore 文件。
然后我进入当中 写入了 **/xxx.js
然后重新编译。两者方法都无效。
我应该如何配置这些文件，来实现我想要的效果。
有知道的可以告知下吗。

**Comment by xiaohuoni** [comment]
首先在文件头部写`/* eslint-disable */` 是有效果，然后你有没有看到一个文件叫做 `.eslintignore`

**Comment by xy163** [comment]
![image](https://user-images.githubusercontent.com/54010795/79738187-017ea500-832f-11ea-9e26-c6f650e152f0.png)
@xiaohuoni   感谢您的回答 ，我使用的是2.xx版本,我是想尝试解决部分警告，目前按照您的方法，并没有生效。我再寻找其他答案吧。
