### ISSUE TITLE
upgrade to umi3 no loader for '.mp3' file

### ISSUE THREAD

**Issue by sherry007** [umijs/umi#4486]
最近为项目升级 `umi` 库到最新版本（3.1.1），以下是我的配置文件（只放部分）
```javascript
// .umirc.js
export default {
  ...
  hash: true,
  dva: {
    immer: true,
    hmr: true,
  },
  dynamicImport: {
    loading: '@/components/PageLoading/index',
  },
  locale: {
    baseNavigator: true,
    default: 'zh-CN',
  },
  ignoreMomentLocale: true,
  ...
}
```
但是报错如图所示：
![image](https://user-images.githubusercontent.com/5960194/79534679-d0437200-80ad-11ea-8f73-f103906ad29d.png)

后来，我添加了 `chainWebpack` 配置如下：
```javascript
// .umirc.js
chainWebpack(memo) {
  memo.module
    .rule('media')
    .test(/\.(mp3|4)$/)
    .use('file-loader')
    .loader(require.resolve('file-loader'))
}
```
报错消失。
但是我个人觉得音视频文件也属于基础的 assets 文件，可否在 `umi` 中配置好 loader 呢

**Comment by sorrycc** [comment]
这类文件太多了，chainWebpack 解决吧。

**Comment by jclegendary** [comment]
楼主的 test的正确写法应该是  .test(/.mp(3|4)$/)，不然只能匹配到MP3文件

**Comment by sherry007** [comment]
> 楼主的 test的正确写法应该是 .test(/.mp(3|4)$/)，不然只能匹配到MP3文件

啊，是的，非常感谢，我修改一下👍

**Comment by whereiscode** [comment]
.rule('media') 这一句是什么意思
