### ISSUE TITLE
upgrade to umi3 报错 'Unexpected export specifier type'

### ISSUE THREAD

**Issue by sherry007** [umijs/umi#4487]
## What happens?

为项目升级 `umi` 库到最新版（v3.1.1), 配置如下：

1. `package.json`

```json
// package.json
...
"dependencies": {
  "umi": "^3.1.1",
  "@umijs/preset-react": "^1.4.16",
}
...
```
2.  `.umirc.js`
```javascript
// .umirc.js
export default {
  ...
  hash: true,
  dva: {
    immer: true,
    hmr: true,
  },
  dynamicImport: {
    loading: '@/components/PageLoading/index',
  },
  locale: {
    baseNavigator: true,
    default: 'zh-CN',
  },
  ignoreMomentLocale: true,
  ...
}
```
结果项目启动报错如下：

![image](https://user-images.githubusercontent.com/5960194/79536163-ee12d600-80b1-11ea-9e3e-fcf6fdb009ac.png)

报错文件摘取如下：
```javascript
// index.js
...
export * as enums from './enums';
export * as utils from './utils';
...
```
自我分析是无法识别 `export * as xxx from ''` 这种语法，但是我看到 `umi` 是配了插件`@babel/plugin-proposal-export-default-from`，另外在升级之前是可以这么引入的。后面我修改了代码如下：
```javascript
...
// index.js
// 先 import 进来，再统一 export
import * as enums from './enums';
import * as utils from './utils';
...
export {
  ...
  enums,
  utils
}
```
麻烦查看一下，也不确定是不是我哪里配置的不对
## 相关环境信息

- **Umi 版本**：v3.1.1
- **Node 版本**：v12.16.1
- **操作系统**：Mac os

**Comment by xiaohuoni** [comment]
参考迁移文档，请注意最好不要只改几个库，而应该删掉 lock 文件，重新安装模块 。
https://umijs.org/docs/upgrade-to-umi-3
