### ISSUE TITLE
[Feature Request] 支持设置 antd ConfigProvider 的属性

### ISSUE THREAD

**Issue by wtzeng1** [umijs/umi#4488]
## 背景

由于项目采用乾坤微服务方案，存在多版本 antd 共存的问题，希望通过 `prefixCls` 来设置 antd 前缀以避免全局样式冲突。Umi 目前在 `LocaleWrapper` 中自己有一层 ConfigProvider 的配置，通过 `rootContainer` 配置的 ConfigProvider 无法再生效。

## 建议

支持设置 ConfigProvider 的 `prefixCls` 等更多属性

**Comment by ycjcl868** [comment]
可以在 @umijs/plugin-antd 插件中加

**Comment by xiaohuoni** [comment]
已经加了。

**Comment by yzStrive** [comment]
@xiaohuoni  你好这个在哪个版本开始支持的呢？目前umi v3.2.22提示不行
```
Validate config "antd" failed, "prefixCls" is not allowed
ValidationError: "prefixCls" is not allowed
```

**Comment by xiaohuoni** [comment]
@yzStrive https://umijs.org/plugins/plugin-antd#config
```
antd:{
   config:{
        prefixCls:'xx'
    }
}
```

**Comment by yujingxiacai** [comment]
你好，我用了上面配置后，antd组件打包出来的文件中className前缀还是ant，而不是xx，这个有什么办法吗，大佬

**Comment by 985563349** [comment]
> @yzStrive https://umijs.org/plugins/plugin-antd#config
> 
> ```
> antd:{
>    config:{
>         prefixCls:'xx'
>     }
> }
> ```

我写入了如下配置：
antd: {
    config: {
      componentSize: 'small',
      getPopupContainer: (trigger: any) => trigger.parentElement,
    },
}
但实际并没有生效，请问这是什么原因？

**Comment by laommmm** [comment]
解决了吗？我加上没生效？给个完整配置？

**Comment by xiaohuoni** [comment]
这个功能和 preset 的版本有关，可以先确认版本是否升级

**Comment by JoMartinezZhu** [comment]
> > @yzStrive https://umijs.org/plugins/plugin-antd#config
> > ```
> > antd:{
> >    config:{
> >         prefixCls:'xx'
> >     }
> > }
> > ```
> 
> 我写入了如下配置： antd: { config: { componentSize: 'small', getPopupContainer: (trigger: any) => trigger.parentElement, }, } 但实际并没有生效，请问这是什么原因？

再加上

lessLoader: {
    modifyVars: {
      '@ant-prefix': 'dmp-v2',
    },
  },
