### ISSUE TITLE
怎么开启多页面啊

### ISSUE THREAD

**Issue by YAN7** [umijs/umi#449]
![image](https://user-images.githubusercontent.com/15334343/39912795-7290cbf6-5532-11e8-9f1c-e359bcb80e5c.png)

是用exportStatic来配置吗

**Comment by xiaohuoni** [comment]
多页面?

**Comment by YAN7** [comment]
@xiaohuoni 是啊，开启多页面应用

**Comment by sorrycc** [comment]
umi 本身就是单页和多页都能跑的，需要为每个页面输出 html 文件时配置下 exportStatic。

**Comment by ilaipi** [comment]
@sorrycc 这个说的太不明确了。。文档里说“一键切换单页多页”，但是都没有找到切换的地方。不应该加一下吗？

**Comment by icarusysuper** [comment]
@sorrycc 这个issue里边的“多页面”其实还是单页应用是吗？配置了exportStatic : { htmlSuffix : true }，打包出来的a.html, b.html里边内容是一样的。

umi会支持传统的多页面应用吗，就是传统的路由跳转页面

**Comment by SagittariusZhu** [comment]
我写了一个umijs的插件支持传统的多页面应用，只需要在config.js中增加一个配置项激活即可，对现有代码完全无侵入。
[umi-plugin-multitabs](https://www.npmjs.com/package/umi-plugin-multitabs)
