### ISSUE TITLE
使用 cordova 9.0.1 创建项目，无法运行 umijs 2.x 及 3.x 的初始样例页面，无法看到内容

### ISSUE THREAD

**Issue by watch-the-fun** [umijs/umi#4492]
## What happens?

当前使用 cordova(9.0.1) 进行 hybird 应用开发，使用 umijs （2.x,3.x） 创建脚手架项目，创建成功后，执行 umi dev 可以正常看到初始的样例页面，可以显示 Index 那行文字，执行 umi build ，将项目打包后，将生成的文件放置在 cordova-cli 生成的项目中 www 目录上，执行 cordova run android ，看到的页面为白屏，该 cordova 项目可以运行默认创建时生成的显示 APACHE CORDOVA device ready 的页面
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

此项目仅为使用 yarn create @umijs/umi-app 生成，未改动任何内容，查阅文档及查找 issue 后，未找到明确说明关于 cordova 环境下如何配置才可以运行

https://github.com/watch-the-fun/umi3-app

## How To Reproduce

**Steps to reproduce the behavior:** 

1. 创建 Apache Cordova 项目
npm install -g cordova
cordova create MyApp
cd MyApp
cordova platform add android
cordova run android (已提前下载好  android studio 及相关 SDK ）
可以运行 cordova 默认项目，显示 APACHE CORDOVA device ready 的页面
2. 创建 umi 3.x 项目
mkdir umi3-app && cd umi3-app
yarn create @umijs/umi-app
yarn 
yarn start ( 可以看到显示的 Index 内容的默认页面）
3. 打包并将生成文件替换到 corodova 环境中运行
yarn build
复制 dist 中生成的文件到 cordova 项目的 www 目录
cordova run android (页面白屏，无法看到显示的 Index 文字）

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.1.1
- **Node Version**: v10.15.3
- **Platform**: macOS 10.15.3

**Comment by xiaohuoni** [comment]
要等待cordova环境成功之后，再启动页面，看你这描述，可能的原因是少了配置`publicPath: './',` 和` history: { type: 'hash' },`,直接用插件吧 [@alitajs/cordova](https://github.com/alitajs/alita/tree/master/packages/cordova)
