### ISSUE TITLE
umi3.1.1 和 antd-pro3.0 下 命令新增页面不生效

### ISSUE THREAD

**Issue by Mrzzchao** [umijs/umi#4495]
## What happens?
1. umi g page 一个新页面
![image](https://user-images.githubusercontent.com/13391134/79685416-4b9e5280-826b-11ea-9b14-7125b752206d.png)

2. pages下面有了新文件
![image](https://user-images.githubusercontent.com/13391134/79685424-53f68d80-826b-11ea-9318-455e1afd3bad.png)

问题：
1. routes没有新增新路由配置
![image](https://user-images.githubusercontent.com/13391134/79685434-6670c700-826b-11ea-9728-b0173526d055.png)

## 最小可复现仓库
https://github.com/Mrzzchao/umi-template

## 复现步骤，错误日志以及相关配置
1. umi g page learn/test/index
2. 看./config/routes.ts 有没有新增路由配置

## 相关环境信息

- **Umi 版本**：3.1.1
- **Node 版本**：10.16.3
- **操作系统**：mac

**Comment by xiaohuoni** [comment]
在 https://github.com/Mrzzchao/umi-template/blob/cc0b8e681acfda94b6b2c89c39ce8b807d798ea1/config/routes.ts#L26 加上配置就好了。
`umi g page` 只是一个简单的demo命令。
现在还不支持ts，不支持自动写配置。
```ts
{
            path: '/learn',
            name: 'learn',
            icon: 'smile',
            component: './learn',
          },
```
