### ISSUE TITLE
【运行时配置】官网示例是否存在错误？

### ISSUE THREAD

**Issue by shangdev** [umijs/umi#4496]
render(oldRender: Function)
```
import { history } from 'umi';

export function render(oldRender) {
  fetch('/api/auth').then(auth => {
    if (auth.isLogin) { oldRender() }
    else { history.push('/login'); }
  });
}
```

上面的示例中，`history.push('/login')`部分，后面如果不写 `oldRender()`，页面就不显示内容了、

**Comment by GeraltX** [comment]
我也有遇到这个问题，但是我选择了不用它。。。

**Comment by sorrycc** [comment]
应该是 window.location = '/login';

**Comment by GeraltX** [comment]
> 应该是 window.location = '/login';

这样跳转的话，页面各种初始化又要再跑一次了，就跟刷新页面一样。

**Comment by sorrycc** [comment]
那就在 history.push('/login'); 后面加 oldRender();

**Comment by shangdev** [comment]
@GeraltX 请问你是如何确保页面切换过程中用户登录失效的？我是在 onRouteChange 切换路由时每次都检查一次是否登录、
