### ISSUE TITLE
umi 2.13.3版本 patchRoutes获取不到routes路由信息

### ISSUE THREAD

**Issue by lunar9621** [umijs/umi#4497]
umi 2.13.3版本src目录下可以读取app.js文件 但是 patchRoutes方法获取不到routes路由信息，控制台打印undefiend

**Comment by xiaohuoni** [comment]
可以的，确认一下你的用法有没有问题。
![image](https://user-images.githubusercontent.com/11746742/79815775-1f421d80-83b4-11ea-9aa1-fd3c767ff349.png)
[umi2test.zip](https://github.com/umijs/umi/files/4507188/umi2test.zip)
