### ISSUE TITLE
3.1.1开启dynamicImport 时build依旧报错

### ISSUE THREAD

**Issue by conkyliu** [umijs/umi#4505]
## What happens?
配置如下
![image](https://user-images.githubusercontent.com/26617741/79836291-8c6ca780-83e2-11ea-9d58-fefb8e59da34.png)
运行umi build 依旧报错
![image](https://user-images.githubusercontent.com/26617741/79836454-b6be6500-83e2-11ea-8a8e-eb88a232f5c7.png)

- **Umi Version**:3.1.1
- **Node Version**:
- **Platform**:

**Comment by conkyliu** [comment]
加大了node内存至4m,build成功,但是打包出来100+m,
![image](https://user-images.githubusercontent.com/26617741/80273944-55133900-8709-11ea-8e8f-b2067bca2f7a.png)
后面自己加了splitChunks
![image](https://user-images.githubusercontent.com/26617741/80273973-973c7a80-8709-11ea-9e2f-92fb045a4e0e.png)
![Uploading image.png…]()
可以正常build,不用加大node内存,

**Comment by sorrycc** [comment]
@conkyliu 配了啥 splitChunks ？

**Comment by conkyliu** [comment]
> @conkyliu 配了啥 splitChunks ？

加了文档里写的chunks,不加splitChunks,打包出100多MB是因为每个chunks都被打包进一份
antd包,依赖用的是3.0版本的antd.

`export default {
  chunks: ['vendors', 'umi'],
  chainWebpack: function (config, { webpack }) {
    config.merge({
      optimization: {
        minimize: true,
        splitChunks: {
          chunks: 'all',
          minSize: 30000,
          minChunks: 3,
          automaticNameDelimiter: '.',
          cacheGroups: {
            vendor: {
              name: 'vendors',
              test({ resource }) {
                return /[\\/]node_modules[\\/]/.test(resource);
              },
              priority: 10,
            },
          },
        },
      }
    });
  },
}`

**Comment by sorrycc** [comment]
https://umijs.org/zh-CN/guide/boost-compile-speed
整理了文档。
