### ISSUE TITLE
Using jest --reporters option gives TypeError

### ISSUE THREAD

**Issue by khalibloo** [umijs/umi#4506]
## What happens?

Using jest `--reporters` option fails with an error.
```
TypeError: reporters.find is not a function
```

## Mini Showcase Repository(REQUIRED)

https://github.com/khalibloo/umi-jest-bug
This happens on a fresh install of umi. Just add a test and run the command.

## How To Reproduce

1. Add a test
2. Run `yarn test --ci --runInBand --reporters="default"`

**Expected behavior**
1. All jest CLI options should work.

## Context

- **Umi Version**: 3.1.1
- **Node Version**: 12.13.0
- **Platform**: Windows 10

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
