### ISSUE TITLE
umi2 插件开发，插件api提供在umi.js之前插入script的能力

### ISSUE THREAD

**Issue by KMBaby-zyl** [umijs/umi#4507]
## Background

埋点资源需要我们在umi.js之前加入资源。根据现有的插件api，我的埋点插件无法做到

**Comment by xiaohuoni** [comment]
不是很清楚你的代码需要加在什么位置，如果需要添加前置代码，可以尝试 https://v2.umijs.org/zh/plugin/develop.html#addentrycodeahead

**Comment by KMBaby-zyl** [comment]
加到umijs之前
```
<script src="mycontent">
</script>
<script src="./umi.js"></script>
```

**Comment by xiaohuoni** [comment]
https://v2.umijs.org/zh/guide/app-structure.html#src-pages-document-ejs
通过document直接写上不行吗？
还可以通过https://v2.umijs.org/zh/plugin/develop.html#addhtmlheadscript 添加

**Comment by KMBaby-zyl** [comment]
我在开发插件，希望能通过插件做到这件事情。 很多场景都需要在umi.js 之前插入 script。 比如配置externals，提取react。如果在document上做，我这边几十个项目就都要写一遍了。

**Comment by xiaohuoni** [comment]
可以通过https://v2.umijs.org/zh/plugin/develop.html#addhtmlheadscript 添加（这个就是插件的方式啊）
