### ISSUE TITLE
monorepo项目，umi运行报错

### ISSUE THREAD

**Issue by shenck215** [umijs/umi#4508]
What happens?

lerna bootstrap后，所有相同版本的依赖装在monorepo项目最外层的node_modules里，导致umi运行时找不到@umijs\babel-preset-umi下的node_modules

* E:\static\xbz\xbz-monorepo\node_modules\@umijs\babel-preset-umi\node_modules\@babel\runtime/helpers/esm/objectSpread2 in ./src/models/global.ts, ./src/pages/recruit/resumeImport/index.tsx and 5 others* E:\static\xbz\xbz-monorepo\node_modules\@umijs\babel-preset-umi\node_modules\@babel\runtime/helpers/esm/slicedToArray in ./src/.umi/plugin-model/Provider.tsx, ./src/.umi/plugin-model/useModel.tsx and 
8 others
* E:\static\xbz\xbz-monorepo\node_modules\@umijs\babel-preset-umi\node_modules\@babel\runtime/regenerator in E:/static/xbz/xbz-monorepo/node_modules/@umijs/runtime/dist/index.esm.js, ./src/models/global.ts and 10 others

## 相关环境信息

- **Umi 版本**：v3.1.1
- **Node 版本**：v12.14.1
- **操作系统**：windows 10

## 期望

@umijs\babel-preset-umi下找不到相应依赖包时，逐级向上查找

**Comment by mizi-lin** [comment]
有相同的问题，暂时需要手动指定路径

**Comment by shenck215** [comment]
> 有相同的问题，暂时需要手动指定路径

@mizi-lin 怎么配置?

**Comment by shenck215** [comment]
> 有相同的问题，暂时需要手动指定路径

我现在通过别名解决的，等官方修复
![image](https://user-images.githubusercontent.com/20554664/79873327-8e059200-8419-11ea-92fa-f7ba02dfc6c6.png)

**Comment by sorrycc** [comment]
谁来解释下为啥会找不到呢？这么写应该是会往上找吧。https://github.com/umijs/umi/blob/1be095aaf07e39a6bfc226b02e9e937846c5f465/packages/babel-preset-umi/src/index.ts#L96

**Comment by sorrycc** [comment]
@shenck215 不要用 alias，会有潜在问题，依赖库如果用了不同版本的 @babel/runtime，也会走你设置了的那个。

**Comment by Sayid1** [comment]
你好，能把你的lerna和umi的搭建步骤说一下吗？我现在配合lerna没有思路，不知道该如何搭建项目了 @shenck215

**Comment by shenck215** [comment]
@Sayid1 用lerna初始化项目，在lerna.json的packages里划分成三块，docs、packages、projects。
ui组件库，业务组件库，等等其他项目中可提取的公共模块都提取到packages里，每个包都有自己的独立的开发及构建；项目放在projects里，之前umi该怎么用就怎么用，只是放在里面；docs是用于文档的。
整个menorepo仓库的依赖统一通过lerna bootstrap去安装；运行及构建各个包或项目，通过lerna exec或者run去执行相应命名空间下各自package.json里的scripts;发布时的changelog也通过lerna。
为了方面依赖packages，用了yarn workspace;项目多了后用git submodule减少了体积.

**Comment by Sayid1** [comment]
使用lerna init初始化项目后, 加上workspace
> package.json 文件加入
```
  "workspaces": [
    "packages/*"
  ]
```
> lerna.json 文件加入
```
"useWorkspaces": true
```
然后在packages里面使用npx @umijs/create-umi-app创建package
或者使用lerna create components在packages里面创建业务组件、UI组件等

是这样吗？

**Comment by shenck215** [comment]
@Sayid1 
是的
lerna.json里
![D75CDA0D-FCFE-4C7A-9783-F480D8C1F9E6](https://user-images.githubusercontent.com/20554664/81288500-58a6a880-9097-11ea-8b9a-9b31db2fe9bd.jpeg)

**Comment by Sayid1** [comment]
lerna 根目录的package.json里面的dependencies/devDependencies只有一个lerna吗，项目的依赖还是安装在各自的package.json里面吗？这样会不会有很多重复的项目依赖文件？

**Comment by shenck215** [comment]
@Sayid1 lerna bootstrap安装依赖的时候，会把所有项目中相同版本的依赖装在最外层的node_modules里，不同的版本的装在自己项目下的node_modules里

**Comment by shenck215** [comment]
@Sayid1 可以尽量保证各项目的依赖版本统一，将相同版本的依赖写在根目录的package.json里，便于维护

**Comment by Sayid1** [comment]
方便把你的项目结构和配置文件借个图吗:)

**Comment by shenck215** [comment]
@Sayid1 
公司的项目，不方便截图。

使用 --hoist 来把每个 package 下的依赖包都提升到工程根目录，来降低安装以及管理的成本https://github.com/lerna/lerna/tree/master/commands/bootstrap#--hoist-glob

基础结构就是这种
![image](https://user-images.githubusercontent.com/20554664/81387214-eabab980-9148-11ea-8645-21bcf190967c.png)

**Comment by 282159468** [comment]
+1

**Comment by mizi-lin** [comment]
> 谁来解释下为啥会找不到呢？这么写应该是会往上找吧。
> 
> https://github.com/umijs/umi/blob/1be095aaf07e39a6bfc226b02e9e937846c5f465/packages/babel-preset-umi/src/index.ts#L96

@sorrycc 

使用 require.resolve(xxxxx) 逐层查找模块地址的时候，xxxxx 不是绝对地址或不带标识的相对地址，且 后缀名 不带 `.js` 或 `.json` 那么它就认为这是一个模块，就会逐层向上查找，且如果当前项目查找不到，它还会不甘心的去全局查找

**Comment by mizi-lin** [comment]
> > 有相同的问题，暂时需要手动指定路径
> 
> @mizi-lin 我现在通过alias临时解决的，等官方修复
> ![image](https://user-images.githubusercontent.com/20554664/79873327-8e059200-8419-11ea-92fa-f7ba02dfc6c6.png)

alias 有危险，我是手动指定设定 preset

**Comment by astonishqft** [comment]
> > > 有相同的问题，暂时需要手动指定路径
> > 
> > 
> > @mizi-lin 我现在通过alias临时解决的，等官方修复
> > ![image](https://user-images.githubusercontent.com/20554664/79873327-8e059200-8419-11ea-92fa-f7ba02dfc6c6.png)
> 
> alias 有危险，我是手动指定设定 preset

请问下你是如何设定的呢？

**Comment by guoxmin** [comment]
> @Sayid1 用lerna初始化项目，在lerna.json的packages里划分成三块，docs、packages、projects。
> ui组件库，业务组件库，等等其他项目中可提取的公共模块都提取到packages里，每个包都有自己的独立的开发及构建；项目放在projects里，之前umi该怎么用就怎么用，只是放在里面；docs是用于文档的。
> 整个menorepo仓库的依赖统一通过lerna bootstrap去安装；运行及构建各个包或项目，通过lerna exec或者run去执行相应命名空间下各自package.json里的scripts;发布时的changelog也通过lerna。
> 为了方面依赖packages，用了yarn workspace;项目多了后用git submodule减少了体积.

lerna bootstrap安装packages包，不支持HRM，有解决方案么

**Comment by Sayid1** [comment]
> > @Sayid1 用lerna初始化项目，在lerna.json的packages里划分成三块，docs、packages、projects。
> > ui组件库，业务组件库，等等其他项目中可提取的公共模块都提取到packages里，每个包都有自己的独立的开发及构建；项目放在projects里，之前umi该怎么用就怎么用，只是放在里面；docs是用于文档的。
> > 整个menorepo仓库的依赖统一通过lerna bootstrap去安装；运行及构建各个包或项目，通过lerna exec或者run去执行相应命名空间下各自package.json里的scripts;发布时的changelog也通过lerna。
> > 为了方面依赖packages，用了yarn workspace;项目多了后用git submodule减少了体积.
> 
> lerna bootstrap安装packages包，不支持HRM，有解决方案么

需要修改rule的include配置
我在umirc里面这样配置的
```
chainWebpack(config: any) {
    config.module
      .rule('ts-in-node_modules')
      // .exclude.add(/node_modules/)
      // .end()
      .include.add(path.join(__dirname, '..'))
      .end()
}
```

**Comment by guoxmin** [comment]
> > > @Sayid1 用lerna初始化项目，在lerna.json的packages里划分成三块，docs、packages、projects。
> > > ui组件库，业务组件库，等等其他项目中可提取的公共模块都提取到packages里，每个包都有自己的独立的开发及构建；项目放在projects里，之前umi该怎么用就怎么用，只是放在里面；docs是用于文档的。
> > > 整个menorepo仓库的依赖统一通过lerna bootstrap去安装；运行及构建各个包或项目，通过lerna exec或者run去执行相应命名空间下各自package.json里的scripts;发布时的changelog也通过lerna。
> > > 为了方面依赖packages，用了yarn workspace;项目多了后用git submodule减少了体积.
> > 
> > 
> > lerna bootstrap安装packages包，不支持HRM，有解决方案么
> > @guoxmin
> > 需要修改rule的include配置
> > 我在umirc里面这样配置的
> 
> ```
> chainWebpack(config: any) {
>     config.module
>       .rule('ts-in-node_modules')
>       // .exclude.add(/node_modules/)
>       // .end()
>       .include.add(path.join(__dirname, '..'))
>       .end()
> }
> ```

感谢回答， 可以了

**Comment by HEternally** [comment]
我也遇到了这个问题，如何解决

**Comment by ihavecoke** [comment]
> 

关掉 MFSU

**Comment by yuanguandong** [comment]
> > > @Sayid1 用lerna初始化项目，在lerna.json的packages里划分成三块，docs、packages、projects。
> > > ui组件库，业务组件库，等等其他项目中可提取的公共模块都提取到packages里，每个包都有自己的独立的开发及构建；项目放在projects里，之前umi该怎么用就怎么用，只是放在里面；docs是用于文档的。
> > > 整个menorepo仓库的依赖统一通过lerna bootstrap去安装；运行及构建各个包或项目，通过lerna exec或者run去执行相应命名空间下各自package.json里的scripts;发布时的changelog也通过lerna。
> > > 为了方面依赖packages，用了yarn workspace;项目多了后用git submodule减少了体积.
> > 
> > 
> > lerna bootstrap安装packages包，不支持HRM，有解决方案么
> > @guoxmin
> > 需要修改rule的include配置
> > 我在umirc里面这样配置的
> 
> ```
> chainWebpack(config: any) {
>     config.module
>       .rule('ts-in-node_modules')
>       // .exclude.add(/node_modules/)
>       // .end()
>       .include.add(path.join(__dirname, '..'))
>       .end()
> }
> ```

你好，咨询一下，include外层之后项目明显启动明显慢了很多，你是如何提速的？把其他一些不相干的文件夹exclude掉？

**Comment by jws132** [comment]
MFSU 开启  报错 AssertionError [ERR_ASSERTION]: [MFSU] package.json not found for dep  大家有没有需要的
