### ISSUE TITLE
UMI3 稳定性太差，页面多了就卡暴

### ISSUE THREAD

**Issue by rilaohn** [umijs/umi#4509]
## What happens?

只要页面和路由一多，run dev 就特别慢，在chrome浏览器中很多样式都没有出来，打开chrome浏览器的element就卡爆，我们现在开发都是注释掉大部门路由才能正常使用！

## 最小可复现仓库

> 建议官方多考虑umi3的稳定性，

## 相关环境信息

- **Umi 版本3.1.1：
- **Node 版本12.x：
- **操作系统 windows 10：

**Comment by rilaohn** [comment]
yarn run v1.22.4
$ umi dev
� Starting Umi UI using umi@3.1.1...
� Umi UI mini Ready on port 3000.
Starting the development server...

√ Webpack
  Compiled successfully in 6.80m

[BABEL] Note: The code generator has deoptimised the styling of E:\IdeaSpace\front-end\model-control-u2\src\assets\fish-topo\fish-topo-flow.js as it exceeds the max of 500KB.
 DONE  Compiled successfully in 407770ms

**Comment by rilaohn** [comment]
这是路由配置
const dataStandardRoutes = [
  {
    icon: 'dashboard',
    path: '/dataStandard',
    name: 'data.standard',
    routes: [
      {
        name: 'element',
        path: '/dataStandard/element',
        routes: [
          {
            name: 'system',
            path: '/dataStandard/element/system',
            component: '@/pages/dataStandard/belongSystem',
          },
          {
            name: 'sourceSystem',
            path: '/dataStandard/element/sourceSystem',
            component: '@/pages/dataStandard/sourceSystem',
          },
          {
            name: 'layer',
            path: '/dataStandard/element/layer',
            component: '@/pages/dataStandard/layer',
          },
          {
            name: 'domain',
            path: '/dataStandard/element/domain',
            component: '@/pages/dataStandard/domain',
          },
          {
            name: 'subareaType',
            path: '/dataStandard/element/subareaType',
            component: '@/pages/dataStandard/subareaType',
          },
          {
            name: 'accountPeriod',
            path: '/dataStandard/element/accountPeriod',
            component: '@/pages/dataStandard/accountPeriod',
          },
          {
            name: 'memoryCycle',
            path: '/dataStandard/element/memoryCycle',
            component: '@/pages/dataStandard/memoryCycle',
          },
          {
            name: 'customize',
            path: '/dataStandard/element/customize',
            component: '@/pages/dataStandard/customize',
          },
        ],
      },
      {
        name: 'data',
        path: '/dataStandard/data',
        routes: [
          {
            name: 'fieldsLibrary',
            path: '/dataStandard/data/fieldsLibrary',
            component: '@/pages/dataStandard/fieldsLibrary',
          },
          {
            name: 'acronym',
            path: '/dataStandard/data/acronym',
            component: '@/pages/dataStandard/acronym',
          },
          {
            name: 'keywords',
            path: '/dataStandard/data/keywords',
            component: '@/pages/dataStandard/keywords',
          },
        ],
      },
      {
        name: 'modelDesign',
        path: '/dataStandard/modelDesign',
        routes: [
          {
            name: 'designRule',
            path: '/dataStandard/modelDesign/designRule',
            component: '@/pages/dataStandard/designRule',
          },
          {
            name: 'testRule',
            path: '/dataStandard/modelDesign/testRule',
            component: '@/pages/dataStandard/testRule',
          },
        ],
      },
    ],
  },
];

export default [
  {
    path: '/user',
    component: '../layouts/UserLayout',
    routes: [
      {
        name: 'login',
        path: '/user/login',
        component: './user/login',
      },
    ],
  },
  {
    path: '/',
    component: '../layouts/SecurityLayout',
    routes: [
      {
        path: '/',
        component: '../layouts/BasicLayout',
        authority: ['admin', 'user'],
        routes: [
          { path: '/', component: '@/pages/index', icon: 'dashboard', name: 'home' },
          ...dataStandardRoutes,
          {
            icon: 'dashboard',
            path: '/modelDesign',
            name: 'model.design',
            routes: [
              {
                name: 'workbench',
                path: '/modelDesign/workbench',
                component: '@/pages/modelDesign/modelWorkbench',
                // hideChildrenInMenu: true,
                // routes: [
                //   {
                //     name: 'workOrder',
                //     path: '/modelDesign/workbench/workOrder',
                //     hideInMenu: true,
                //     component: '@/pages/modelDesign/modelWorkbench/component/orderInfo',
                //   },
                // ],
              },
              {
                name: 'workOrder',
                path: '/modelDesign/workOrder',
                hideInMenu: true,
                flatMenu: true,
                component: '@/pages/modelDesign/modelWorkbench/component/designInfo',
              },
              {
                name: 'search',
                path: '/modelDesign/search',
                component: '@/pages/modelDesign/modelSearch',
              },
              {
                name: 'compare',
                path: '/modelDesign/compare',
                component: '@/pages/modelDesign/compare',
              },
            ],
          },
          {
            path: '/demo',
            component: '@/pages/demo',
            icon: 'dashboard',
            name: 'demo',
          },
          {
            path: '/',
            redirect: '/welcome',
          },
          {
            path: '/welcome',
            name: 'welcome',
            icon: 'smile',
            component: './Welcome',
          },
          {
            path: '/admin',
            name: 'admin',
            icon: 'crown',
            component: './Admin',
            authority: ['admin'],
            routes: [
              {
                path: '/admin/sub-page',
                name: 'sub-page',
                icon: 'smile',
                component: './Welcome',
                authority: ['admin'],
              },
            ],
          },
          {
            name: 'list.table-list',
            icon: 'table',
            hideInMenu: true,
            path: '/list',
            component: './ListTableList',
          },
          {
            component: './404',
          },
        ],
      },
      {
        component: './404',
      },
    ],
  },
  {
    component: './404',
  },
];

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/4415

**Comment by rilaohn** [comment]
不仅是windows，同事mbp也一样

**Comment by xiaohuoni** [comment]
看起来页面也不是特别多。有尝试过运行pro的完整项目嘛？
3.1.1 有开启配置 [nodeModulesTransform](https://umijs.org/config#nodemodulestransform-31) 吗？

**Comment by rilaohn** [comment]
> 看起来页面也不是特别多。有尝试过运行pro的完整项目嘛？
> 3.1.1 有开启配置 [nodeModulesTransform](https://umijs.org/config#nodemodulestransform-31) 吗？

没有运行pro的完整项目，nodeModulesTransform 有配置过type：none

**Comment by sorrycc** [comment]
https://umijs.org/zh-CN/guide/boost-compile-speed
整理了文档。
