### ISSUE TITLE
文档中“按需加载”部分有误导性

### ISSUE THREAD

**Issue by SentretC** [umijs/umi#4510]
文档中“通过 Umi 的 `dynamic` 接口实现按需加载组件”与“通过 `import()` 实现按需加载非组件”为平级并列关系，且“按需加载组件”部分的示例代码是延时1秒显示一个div，并没有体现按需加载，让本小白困惑了很长时间。

没理解错的话，只要是按需加载就要用到 `import()`，只是当加载的对象是一个组件时，可以使用 `dynamic` 对其返回的 Promise 进行包装，省去自己管理加载状态的麻烦，对吗？

另外建议明确文档的读者应具有哪些前置知识。

**Comment by leftstick** [comment]
`没理解错的话，只要是按需加载就要用到 import()，只是当加载的对象是一个组件时，可以使用 dynamic 对其返回的 Promise 进行包装，省去自己管理加载状态的麻烦`

你的理解是对的。

关于文档部分，的确会有不足，『大家共同努力让她变得更好』，这不就是开源的初衷嘛。

我倒是建议你能把你心目中关于这个部分，整理一份能让『几天之前』的你一下就看懂文案。这也便于我们今后更好的优化文档。谢谢

**Comment by SentretC** [comment]
> 我倒是建议你能把你心目中关于这个部分，整理一份能让『几天之前』的你一下就看懂文案。这也便于我们今后更好的优化文档。谢谢

感谢，抱歉没有及时回复
您看这样如何：
---
# 按需加载
<对按需加载的简要介绍>
## 启用按需加载
<现有文档中该部分内容>
<启用后效果简介> - 详见：配置|dynamicImport
## 手动加载模块（表示对许多人来说默认效果就够用了）
使用`import()`动态加载指定模块：
（为了扩大受众没有使用hook）
```
import React from 'react';
− import { Chart } from '@antv/g2';

export default class MyComponent extends React.Component {
  componentDidMount() {
−     const chart = new Chart({ ...
+     import('@antv/g2').then(({ Chart }) => {
+       const chart = new Chart({ ...
```
参见：MDN|import
### 使用`dynamic`接口简化组件加载
```
// 静态加载
import React from 'react';
import LargeComponent from '@/components/LargeComponent';

export default class MyComponent extends React.Component {
  render() {
    return (
      <div>
        <LargeComponent />
...
```
```
// 动态加载 - 不使用dynamic
import React from 'react';

export default class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      LargeComponent: null,
    };
  }
  componentDidMount() {
    import('@/components/LargeComponent').then(({ default: LargeComponent }) => {
      this.setState({ LargeComponent });
    });
  }
  render() {
    const { LargeComponent } = this.state;
    return (
      <div>
        {LargeComponent ? <LargeComponent /> : 'Loading...'}
...
```
```
// 动态加载 - 使用dynamic
import React from 'react';
import { dynamic } from 'umi';

export default class MyComponent extends React.Component {
  render() {
    const Dynamic = dynamic({
      loader: async function() {
        const { default: LargeComponent } = await import('@/components/LargeComponent');
        return () => <LargeComponent />;
      }
    });
    // or: const Dynamic = dynamic(() => import('@/components/LargeComponent'));
    return (
      <div>
        <Dynamic />
...
```

**Comment by leftstick** [comment]
最下面，『而无需自行管理加载状态：』这段，描述的是不用`dynimac` 的麻烦场景，对么？

**Comment by SentretC** [comment]
> 
> 
> 最下面，『而无需自行管理加载状态：』这段，描述的是不用`dynimac` 的麻烦场景，对么？

是的，我觉得采用对比的方法会更容易理解，另两个例子写成diff形式也是这个原因
不过现在再看，给出不用`dynamic`动态加载组件的例子好像是没有必要的。作为介绍的话和静态加载对比就够了，而且理解了`import()`之后也不难想到

**Comment by leftstick** [comment]
close with #4546

**Comment by SentretC** [comment]
感谢

不过我所说存在将`dynamic`与`import()`并列的页面其实是这个：
https://umijs.org/zh-CN/docs/load-on-demand
我想这个页面应该是比API文档更加面向新手的，希望也能得到改进
