### ISSUE TITLE
umi 3.1.1 antd 暗色主题设置无效

### ISSUE THREAD

**Issue by m01i0ng** [umijs/umi#4513]
antd 版本: 4.1.4
配置如下，开启暗色和紧凑主题但无效

![image](https://user-images.githubusercontent.com/19723234/79945690-efbd0f00-84a0-11ea-89b7-b1b4ea1a35d5.png)

**Comment by chj-damon** [comment]
+1，删除compact之后暗色主题生效。

**Comment by sorrycc** [comment]
修复了。
