### ISSUE TITLE
开启 PWA 以及调试 service-worker.js

### ISSUE THREAD

**Issue by TianenPang** [umijs/umi#4516]
请问如何在本地调试service-worker.js

dev环境下和编译后都不行，也没有报错

但在Chrome中提示service-worker未找到
以及
'serviceWorker' in navigator为false

**Comment by xiaohuoni** [comment]
umi@3 应该还不支持 PWA

**Comment by TianenPang** [comment]
> umi@3 应该还不支持 PWA

Ant Design Pro 有用到PWA，但是看不明白是怎么在配置文件配置的，还有就是 service worker 的问题
