### ISSUE TITLE
权限功能，umi打包后，不生效，虽然页面不会在侧边显示，但是通过改变地址依然能看见页面

### ISSUE THREAD

**Issue by Picsong** [umijs/umi#4517]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by xiaohuoni** [comment]
更新插件包版本，已修复
