### ISSUE TITLE
umi/locale的setLocale()传参数的问题

### ISSUE THREAD

**Issue by minsion** [umijs/umi#4520]
问题：umi/locale的setLocale(lang)，只支持zh-CN这中形式，能不能支持zh-cn。只能本地手动做映射？有没有好的方案兼容性lang这个参数不一定是/^([a-z]{2})-([A-Z]{2})$/.test(lang)，有可能是/^([a-z]{2})-([a-z]{2})$/.test(lang)。

原因：setLocale的方法里面有这个校验
if (lang !== undefined && !/^([a-z]{2})-([A-Z]{2})$/.test(lang)) {
    // for reset when lang === undefined
    throw new Error('setLocale lang format error');
  }

复现：钉钉浏览器的汉语是：zh-Hans-CN，当用户在钉钉浏览器切换中文时需setLocale("zh-Hans-CN")，那么就会抛错误 throw new Error('setLocale lang format error');

**Comment by leftstick** [comment]
好问题啊。根据`intl`的介绍[Intl/locale](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Locale_identification_and_negotiation)，钉钉浏览器里给出的值是合法的。

那就应该是 `umi` 里的处理方式还不够完整了

**Comment by xiaohuoni** [comment]
后续更近 https://github.com/umijs/plugins/issues/173
