### ISSUE TITLE
Umi3 如何配置底层库为preact

### ISSUE THREAD

**Issue by zhengsusu2014** [umijs/umi#4522]
现象：
在Umi2中通过library设置底层库为react还是preact，具体配制见链接： https://v2.umijs.org/zh/plugin/umi-plugin-react.html#library

但在Umi3中看到已去掉了library这一功能，具体见链接： https://umijs.org/zh-CN/docs/upgrade-to-umi-3#%E5%8D%87%E7%BA%A7-umi-plugin-react-%E4%B8%BA-umijspreset-react

问题：Umi3 中如何配置底层库为preact，还是说不支持？

**Comment by xiaohuoni** [comment]
有看到一个库，还没看到文档。https://github.com/umijs/plugins/tree/master/packages/plugin-preact

**Comment by sorrycc** [comment]
`npm i @umijs/umi-preact` 即可，我补个文档。
