### ISSUE TITLE
layout 里面配置有哪些 文档不清晰  谢谢

### ISSUE THREAD

**Issue by xuchao321** [umijs/umi#4523]
![image](https://user-images.githubusercontent.com/28084523/80054810-d70d3180-8552-11ea-8a79-d5454e96c40b.png)

**Comment by xiaohuoni** [comment]
https://umijs.org/plugins/plugin-layout#%E6%9E%84%E5%BB%BA%E6%97%B6%E9%85%8D%E7%BD%AE
 这里有配置说明
