### ISSUE TITLE
模板文件用ejs而不是html，能说下这么做的理由吗？

### ISSUE THREAD

**Issue by z0nka1** [umijs/umi#4524]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by leftstick** [comment]
我觉得大致是 `umi@2` 就是 用的 `ejs`，为了保持向后兼容，`umi@3` 依旧沿用了这个部分。

然后，当初 `umi@2` 为啥要用 `ejs`，我想应该是 [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md) 默认使用了 `ejs`，由于这个插件受众很多，所以考虑到用户的学习、迁移成本，所以沿用了 `ejs` 吧

**Comment by musicode** [comment]
这就意味着，选择 umi 等价于接受 ejs？

这种捆绑销售最好在文档里写清楚，如果我早知道是这么回事，文档看了第一页我就关了，不会花时间去试用
