### ISSUE TITLE
yarn create umi -> ant-design-pro文件缺失

### ISSUE THREAD

**Issue by yulrosy** [umijs/umi#4525]
打包失败

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
1. yarn create umi
2. Select the boilerplate type => ant-design-pro 
3. Be the first to experience the new umi@3 => y
4. yarn install 
5. yarn fetch:blocks
6. yarn start

Cannot find module 'xxx/src/layouts/BlankLayout

src缺少layouts

## 相关环境信息

- **Umi 版本**：3.1.1
- **create-umi 版本**：0.22.0
- **Node 版本**：12.16.2
- **操作系统**：macOS 10.15.4

**Comment by Rhuaer** [comment]
和这个问题相同，但我在windows上不会报错，能跑起来https://github.com/umijs/umi/issues/4526
