### ISSUE TITLE
yarn  create umi   创建项目的目录与之前不同

### ISSUE THREAD

**Issue by Tenodec** [umijs/umi#4526]
前几天同样创建项目 umi版本是3.1.1 ，今天再创建就是3.1.0了。生成ant-design-pro项目的文件目录也变了。
跟umi3.0的文档也不一样了
咋整
## 相关环境信息

- **Umi 版本**：3.1.0

**Comment by Rhuaer** [comment]
我怀疑是不是create umi出了问题吧，是不是官方提交了什么奇怪的代码
![image](https://user-images.githubusercontent.com/13702561/80081663-d477ff80-8585-11ea-8d20-d0547eb8f093.png)
![image](https://user-images.githubusercontent.com/13702561/80081741-ed80b080-8585-11ea-9c4e-665b01c83cb7.png)

**Comment by GezzellPang** [comment]
我也懵逼了。。原来是这样。。

**Comment by xiaohuoni** [comment]
只是提前放出了pro v5版本，但是很多东西还没准备好，所以觉得不合适，经过讨论，又重置了。后续的项目会以 pro v5 为标准，但是需要等 v5 发布。

**Comment by fzxiang** [comment]
这个问题如何解决呢？
