### ISSUE TITLE
proxy中proxyRes事件监听函数未执行

### ISSUE THREAD

**Issue by lhsxyzj** [umijs/umi#4527]
## What happens?

proxy中同时监听了proxyReq, proxyRes事件，proxyRes事件未执行
配置：
proxy: {
    ['/api']: {
      target: '',
      ws: false,
      changeOrigin: true,
      secure: false,
      onProxyReq(proxyReq, req, res) {
        console.log('request') //成功打印
      },
      onProxyRes(proxyRes) {
        console.log('response') //未打印
      }
    }
  }
## Context

- **Umi Version**: 3.1.1
- **Node Version**: 10.16.0

**Comment by zhouzhiyang-git** [comment]
您好，onProxyRes方法未监听是在哪个版本修复的，我现在最新版还是不行

**Comment by xiaohuoni** [comment]
已修复 https://github.com/umijs/umi/pull/5202
