### ISSUE TITLE
开启 hash，build 后文件名称不会变化

### ISSUE THREAD

**Issue by rfw** [umijs/umi#4529]
## What happens?

配置完 targets  再开启 hash，每次打包后的文件名称 是固定的。

```

export default defineConfig({
  title: false,
  hash: true,
  targets: {
    ie: 11,
  },
});

```

## Context

- **Umi Version**:  3.1.1
- **Node Version**: v12.13.1  
- **Platform**:  window  and  os x

**Comment by sorrycc** [comment]
内容没有变化，所以 hash 不变。

**Comment by wangxingxing123654** [comment]
> 内容没有变化，所以 hash 不变。

新增加一个js文件，再打包，hash值都不变
