### ISSUE TITLE
umi的文档系统无法在ie11中打开

### ISSUE THREAD

**Issue by sdhr27** [umijs/umi#4533]
## What happens?

umi的文档系统https://umijs.org/zh-CN/docs/getting-started无法在ie11中打开，是否是由于umi的文档系统没有配置ie11兼容？

## 复现步骤，错误日志以及相关配置

1、打开ie浏览器
2、输入https://umijs.org/zh-CN/docs/getting-started
3、报错如下：
![TIM图片20200424111353](https://user-images.githubusercontent.com/37827411/80171343-bad5c700-861c-11ea-8dc3-15e70fc2e1f7.png)

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：win10

**Comment by sorrycc** [comment]
用 Chrome 打开吧，不准备加 IE11 的补丁。
