### ISSUE TITLE
useHistory希望能获取到浏览器的后退、前进、刷新是否可用的状态

### ISSUE THREAD

**Issue by DeyiXu** [umijs/umi#4538]
## What happens?

useHistory希望能获取到浏览器的后退、前进、刷新是否可用的状态

## 复现步骤，错误日志以及相关配置

![image](https://user-images.githubusercontent.com/22539808/80296607-441d0300-87af-11ea-9e23-938a531e0365.png)

## 相关环境信息

- **Umi 版本**：v3.1.1
- **Node 版本**：v12.16.1
- **操作系统**：MacOS

**Comment by sorrycc** [comment]
不能。
