### ISSUE TITLE
umi externals  还是打包了设置项 比如antd

### ISSUE THREAD

**Issue by coy9** [umijs/umi#4542]
## What happens?

![image](https://user-images.githubusercontent.com/23191825/80332562-c116ae00-887d-11ea-9bad-230d07f96b64.png)
设置无效

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
![image](https://user-images.githubusercontent.com/23191825/80332622-e1466d00-887d-11ea-9f63-66f97264570a.png)
antd 还存在

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by coy9** [comment]
externals 如何设置才能不打包 类似 react react-router antd 库

**Comment by sorrycc** [comment]
因为用了 babel-plugin-import 插件，所以引的时候不是 antd，而是 antd/es/xxx，搜 webpack 的文档解决。

**Comment by wleven** [comment]
> 因为用了 babel-plugin-import 插件，所以引的时候不是 antd，而是 antd/es/xxx，搜 webpack 的文档解决。

所以这里应该怎么写，不是很懂webpack配置

**Comment by Baoyx007** [comment]
可以直接配置 antd: false,

**Comment by tinytinysunny** [comment]
同好奇怎么解决

**Comment by travonf** [comment]
> config/config.ts
``` js
import { defineConfig } from 'umi';

export default defineConfig({
  externals: {
   'antd/lib/table': 'antd.Table'
  }
}
```

**Comment by zwh1666258377** [comment]
@😱

**Comment by hanwenbo** [comment]
> 可以直接配置 antd: false,

测试了 不行

**Comment by wangmeijian** [comment]
umi3 禁用了动态加载也不行

**Comment by aeroxy** [comment]
> 按组件扩展
> 
> ```
> export default defineConfig({
>   externals: {
>    'antd/es/alert': 'antd.Alert',
>   }
> }
> ```
> 
> 批量扩展 external-antd.js
> 
> ```
> import * as antd from 'antd'
> import { kebabCase } from 'lodash'
> let externalsAntd = {}
> for (const key in antd) {
>   if (Object.hasOwnProperty.call(antd, key)) {
>     externalsAntd[`antd/es/${kebabCase(key)}`] = `window.antd.${key}`;
>   }
> }
> export default externalsAntd;
> ```
> 
> config.ts
> 
> ```
> import ExternalAntd from 'external-antd'
> export default defineConfig({
>   externals: {
>     ...ExternalAntd,
>   }
> }
> ```

这个配置我在实际项目中发现`window.antd.${key}`被编译为`window["window.antd." + key]`
