### ISSUE TITLE
cdn部署，css背景图怎么写？

### ISSUE THREAD

**Issue by rfw** [umijs/umi#4543]
## What happens?
使用CND存放静态资源
在css或者less中背景图片怎么写才能正常访问到？

## 相关环境信息

- **Umi 版本**： 3.1.2

**Comment by xiaohuoni** [comment]
```
publicPath
类型：String
默认值：/
指定 webpack 的 publicPath，指向静态资源文件所在的路径
```

**Comment by rfw** [comment]
@xiaohuoni  配置里指定了 publicPath 为 https://xxx.xxx.com ,  css或less文件里图片路径也没加上域名

**Comment by xiaohuoni** [comment]
路径是没添加域名，你js的访问地址就有加了 cdn 域名了。https://webpack.js.org/configuration/output/#output-publicpath

**Comment by rfw** [comment]
@xiaohuoni  测试了下，的确可以了，但现在又遇到一个问题，我使用的CDN不支持创建文件夹，所以我想打包的图片资源放到根目录，而不是 static文件夹里面，有办法吗？

**Comment by xiaohuoni** [comment]
我不确定，但是你可以试试，使用的文件放到public目录下，而不是assets。（感觉这样也不行。）
