### ISSUE TITLE
umi router能否设置别名呢

### ISSUE THREAD

**Issue by liuliu66666** [umijs/umi#4545]
## What happens?

router能否设置别名呢

## 相关环境信息

- **Umi 版本**：2.7.7
- **Node 版本**：12.16.2
- **操作系统**：win7

**Comment by xiaohuoni** [comment]
不知道你说的别名是啥意思？

**Comment by liuliu66666** [comment]
> 不知道你说的别名是啥意思？

就像react-router里的from一样，from 是 path 的别名
```
<Switch>
  <Redirect from="/accounts" to="/users" />
</Switch>
```
但是在.umirc.js里
```
routes: [
    { exact: true, path: '/list', from: '/detaillist', component: 'list' },
  ],
```
并没有生效

**Comment by sorrycc** [comment]
这样用 `routes: [{ path: '/accounts', redirect: '/users' }]`。

**Comment by sorrycc** [comment]
文档里有，https://umijs.org/docs/routing#redirect
