### ISSUE TITLE
[Feature Request] access插件是否可以提供一个刷新的功能

### ISSUE THREAD

**Issue by krypton100** [umijs/umi#4547]
## Background

整合pro-layout，登录超时，重新登录后，重新执行 getInitialState 方法，但access权限并没有修改，权限没有更新，是否可以提供一个刷新access的方法？以刷新当前的权限路由。

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by leftstick** [comment]
不应该啊，如果你用了 `useModel('@@initialState')` 里的 `refresh` 方法，`access` 一定会被刷新的。

请给出你的可复现repo

**Comment by xiaohuoni** [comment]
要确认一下你使用的版本，这个问题在 https://github.com/umijs/plugins/pull/162 已经修复了

**Comment by krypton100** [comment]
> 要确认一下你使用的版本，这个问题在 [umijs/plugins#162](https://github.com/umijs/plugins/pull/162) 已经修复了

已经将umi升至3.1.2版本

我的场景是这样的：
1. 进入页面，`initialState`通过后台获取用户权限信息，用户未登录，所有权限设置为false
2. 请求后台时，用户未登录，通知前端引导到登录页
3. 用户登录成功后，通过`refresh`方法刷新`initailstate`,权限已从后台正常返回，`refresh`方法后调用`history.goBack`方法，返回原来的页面，但此时页面仍显示403无权限访问的页面

[图](https://tva1.sinaimg.cn/large/007S8ZIlgy1ge9ixcmstbj313j0u045f.jpg)

**Comment by leftstick** [comment]
@krypton100 `refresh` 是个异步操作。如果你写

```typescript
refresh()
history.goBack()
```

那大概率是，你重置回原先页面的时候，`access` 状态还没有更新，依旧拿到是旧的值

**Comment by krypton100** [comment]
> @krypton100 `refresh` 是个异步操作。如果你写
> 
> ```ts
> refresh()
> history.goBack()
> ```
> 
> 那大概率是，你重置回原先页面的时候，`access` 状态还没有更新，依旧拿到是旧的值

1秒后执行也是一样

**Comment by leftstick** [comment]
那只能提供可复现repo了。就目前给出的信息，我猜不出来问题出在哪了

**Comment by xiaohuoni** [comment]
给你一个简单的重现demo吧，https://github.com/umijs/next-app/tree/006access
你要的登录刷新权限的功能，我在这里测试了是OK的。你可以先比对一下有什么差异。

**Comment by krypton100** [comment]
> 给你一个简单的重现demo吧，https://github.com/umijs/next-app/tree/006access
> 你要的登录刷新权限的功能，我在这里测试了是OK的。你可以先比对一下有什么差异。

已经将next-app拉下来，本地启动项目，点击模拟登录后，master分支以及006access分支，两个分支访问欢迎页，均显示403页面。

操作系统：mac OS Catalina 10.15.4
浏览器：谷歌、Safari

**Comment by xiaohuoni** [comment]
确实，但是菜单是有得到控制的，我看看，哪里出了问题。

**Comment by xiaohuoni** [comment]
https://github.com/umijs/plugins/pull/183

**Comment by krypton100** [comment]
> 已修复，等待发包 [umijs/plugins#183](https://github.com/umijs/plugins/pull/183)

谢谢！请问升级哪个依赖可以解决此问题？

**Comment by xiaohuoni** [comment]
项目中应该是升级 preset-react

**Comment by mzvast** [comment]
最新版umi+@umijs/preset-react 依然复现，要能拿到左边ref我forceupdate也行呀～
暂时采用sessionStorage持久化+window.history.go(0) 恶心处理

**Comment by laozhu** [comment]
还是有这个问题啊，登录完成后有了用户资料，如何刷新路由权限呢？

**Comment by laozhu** [comment]
找到问题了，setInitialState 后需要后，需要延迟一段时间再跳转路由以及执行 refresh 操作。

```typescript
/** 登录 */
const login = usePersistFn((data: LoginResponse['data']) => {
  if (!data) {
    return;
  }

  const { token, profile } = data;

  // 保存 Token
  saveToken(token);

  // 保存当前用户资料
  if (initialState) {
    setInitialState({ ...initialState, currentUser: profile });
  }

  // 登录成功提示
  message.success('登录成功');

  // 跳转到首页
  setTimeout(() => {
      history.replace(indexUrl);
      refresh();
  }, 100);
});
```

不过还是有个不足的地方，调用 `refresh` 会触发重新请求用户资料，如果我手动 `setInitialState` 后只是想更新下权限并不想有额外的请求该如何呢？ @xiaohuoni @krypton100
