### ISSUE TITLE
脚手架生成的例子less文件导入错误

### ISSUE THREAD

**Issue by dongzhiwei1990** [umijs/umi#4551]
## What happens?
vsvode编译错误警告
按照官方文档，脚手架方式创建项目
yarn create @umijs/umi-app
vsvode中打开编译错误警告：找不到模块“index.less”。
## Mini Showcase Repository(REQUIRED)
------pages/index.tsx-------
import styles from 'index.less';

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:3.1.2
- **Node Version**:v12.13.0
- **Platform**:win10*64
![微信截图_20200428094923](https://user-images.githubusercontent.com/47775301/80437963-9d16a380-8935-11ea-901a-1251faa9ea38.png)

**Comment by dongzhiwei1990** [comment]
脚手架生成的例子less文件导入错误

**Comment by leftstick** [comment]
@dongzhiwei1990  `tsconfig.json` 里的内容是如下这样么？

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "jsx": "react",
    "esModuleInterop": true,
    "sourceMap": true,
    "baseUrl": "./",
    "strict": true,
    "paths": {
      "@/*": ["src/*"],
      "@@/*": ["src/.umi/*"]
    },
    "allowSyntheticDefaultImports": true
  },
  "include": ["mock/**/*", "src/**/*", "config/**/*", ".umirc.ts"]
}
```

不是，用这个覆盖。重启 vscode试试

**Comment by dongzhiwei1990** [comment]
tsconfig.json内容一致，就是脚手架生成的"include"数组里元素有格式化换行了而已，用提供的内容覆盖，重启vscode，问题依旧存在。

**Comment by leftstick** [comment]
@dongzhiwei1990  给个可复现的repo吧。我这里用`yarn create @umijs/umi-app` 生成的项目没有问题

**Comment by dongzhiwei1990** [comment]
> @dongzhiwei1990 给个可复现的repo吧。我这里用`yarn create @umijs/umi-app` 生成的项目没有问题

100%复现，我试建几次都是出现同样的报错，钉钉群里也有其他人遇到同样问题。

管理员打开的CMD,执行命令log如下：
C:\Windows\system32>D:

D:\>cd D:\dev\git-pro\umi-demo-4

D:\dev\git-pro\umi-demo-4>yarn create @umijs/umi-app
yarn create v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@umijs/create-umi-app > @umijs/utils > @babel/register@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
[4/4] Building fresh packages...

success Installed "@umijs/create-umi-app@3.1.2" with binaries:
      - create-umi-app
[#############################################################################################################] 236/236Copy:  .editorconfig
Write: .gitignore
Copy:  .prettierignore
Copy:  .prettierrc
Write: .umirc.ts
Copy:  mock/.gitkeep
Write: package.json
Copy:  README.md
Copy:  src/pages/index.less
Copy:  src/pages/index.tsx
Copy:  tsconfig.json
Copy:  typings.d.ts
Done in 1.24s.

D:\dev\git-pro\umi-demo-4>yarn
yarn install v1.22.4
info No lockfile found.
[1/4] Resolving packages...
warning @umijs/preset-react > @umijs/plugin-antd > antd-mobile > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @umijs/preset-react > @umijs/plugin-antd > antd-mobile > rmc-list-view > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @umijs/preset-react > @umijs/plugin-test > @umijs/test > jest-environment-jsdom-fourteen > @jest/environment > @jest/transform > jest-haste-map > fsevents@1.2.12: fsevents 1 will break on node v14+. Upgrade to fsevents 2 with massive improvements.
warning umi > @umijs/preset-built-in > @umijs/bundler-webpack > webpack > watchpack > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning umi > @umijs/preset-built-in > @umijs/bundler-webpack > webpack > watchpack > chokidar > fsevents@1.2.12: fsevents 1 will break on node v14+. Upgrade to fsevents 2 with massive improvements.
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.12: The platform "win32" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@umijs/preset-react > @umijs/plugin-dva > babel-plugin-dva-hmr@0.4.2" has unmet peer dependency "redbox-react@1.x".
warning "@umijs/preset-react > @umijs/plugin-dva > dva-loading@3.0.20" has unmet peer dependency "dva-core@^1.1.0 | ^1.5.0-0 | ^1.6.0-0".
warning "@umijs/preset-react > @umijs/plugin-antd > antd > rc-picker@1.4.9" has unmet peer dependency "dayjs@^1.8.18".
warning "@umijs/preset-react > @umijs/plugin-dva > dva > connected-react-router@6.5.2" has unmet peer dependency "react-router@^4.3.1 || ^5.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
$ umi generate tmp
Done in 33.82s.

D:\dev\git-pro\umi-demo-4>node -v
v12.13.0

D:\dev\git-pro\umi-demo-4>

**Comment by leftstick** [comment]
完蛋，我没有 windows 机器。。。。

**Comment by xiaohuoni** [comment]
脚手架生成的代码应该是
```
import styles from './index.less';
```
看起来你的代码少了 `./`是被你删除了，还是？你手动补上试试。

**Comment by leftstick** [comment]
@dongzhiwei1990 

突然想起来，`tsconfig.json` 里，`include` 部分应该再加一条就好了：

`"include": ["mock/**/*", "src/**/*", "config/**/*", ".umirc.ts", "typings.d.ts"]`

**Comment by xiaohuoni** [comment]
我的项目中都没写 include。

**Comment by dongzhiwei1990** [comment]
> @dongzhiwei1990
> 
> 突然想起来，`tsconfig.json` 里，`include` 部分应该再加一条就好了：
> 
> `"include": ["mock/**/*", "src/**/*", "config/**/*", ".umirc.ts", "typings.d.ts"]`
> 
> 把 `typings.d.ts` 加上

用这个方案确实解决了，脚手架生成的tsconfig.json 里，include没有typings.d.ts导致的错误

**Comment by leftstick** [comment]
> 我的项目中都没写 include。

@xiaohuoni  我也很奇怪。几天前我也不写 `include`，然后昨天重新创建了一个应用，不写 `include` 就不工作了。所以我才加的。目前还没找到什么原因。

**Comment by zhaoyao91** [comment]
同样的问题，同样的 workaround。希望脚手架模板给加上

**Comment by hulkyuan** [comment]
> > @dongzhiwei1990
> > 突然想起来，`tsconfig.json` 里，`include` 部分应该再加一条就好了：
> > `"include": ["mock/**/*", "src/**/*", "config/**/*", ".umirc.ts", "typings.d.ts"]`
> > 把 `typings.d.ts` 加上
> 
> 用这个方案确实解决了，脚手架生成的tsconfig.json 里，include没有typings.d.ts导致的错误

这个方法有效
