### ISSUE TITLE
umi3 修改 umirc.ts proxy 的配置导致开发服务全部重启

### ISSUE THREAD

**Issue by Superman-wc** [umijs/umi#4553]
"umi": "^3.1.1",

修改 .umirc.ts 文件中的proxy配置，导致开发服务重启， 会候再说咯重新编译了， 以前2.x的时候并不会重启服务。

开发调试的时候， 只是改变一下代理的target ，可以灵活的切换数据，

现在3.1.1版本 在这个处理方式上没有以前2.x的方便

**Comment by ycjcl868** [comment]
proxy 的修改实际上修改了 `.umirc.ts` 文件，会触发重编译

**Comment by sorrycc** [comment]
proxy 可以改进下，2.x 是修改完热更新的。
