### ISSUE TITLE
antd配置了externals，但是如果开启了plugin-layout，还是会打包antd

### ISSUE THREAD

**Issue by wxxcarl** [umijs/umi#4554]
## What happens?

antd配置了externals，但是如果开启了plugin-layout，还是会打包antd

## 最小可复现仓库

暂无

## 复现步骤，错误日志以及相关配置

```js
layout: {
    name: '数据平台', 
    locale: false,
  },
````
```js
externals: {
    'react': 'window.React',
    'react-dom': 'window.ReactDOM',
    'moment': 'moment',
    'antd': 'antd',
    'lodash': '_'
  },
````

## 相关环境信息

- **Umi 版本**：3.x
- **Node 版本**：v12.4.0
- **操作系统**：MACOS

**Comment by wxxcarl** [comment]
另外，如果antd配置了externals，是不是就不能替换成dayjs了？

**Comment by sorrycc** [comment]
external 的方式不对，参考 https://github.com/umijs/umi/issues/4542#issuecomment-620656314 。

**Comment by Niofh** [comment]
题主最后怎么解决呢，还没有找到方法
