### ISSUE TITLE
umi3打包太大，preset-react会导致很多无用的插件被打包

### ISSUE THREAD

**Issue by dhzou** [umijs/umi#4556]

**Comment by dhzou** [comment]
umi3.x chunks 在哪设置，目前build出来只有 3个文件 index.html 、umi.js 、umi.css

**Comment by sessionboy** [comment]
@umi/preset-react插件集确实包含了一堆插件，你可以卸载掉preset-react插件集，然后仅安装你需要的那些插件就可以解决这个问题了。
