### ISSUE TITLE
umi@3 启用SPEED_MEASURE后 umi dev 报错

### ISSUE THREAD

**Issue by NexxLuo** [umijs/umi#4560]
## What happens?

`set SPEED_MEASURE=JSON&& umi dev` ：启用 SPEED_MEASURE后 dev报错，试了两个项目，
第一个项目如果不使用copy，就没有问题，而且就算使用了copy，虽然有报错但是却不会导致中断；
第二个项目会直接中断

![image](https://user-images.githubusercontent.com/18549980/80569101-cd8c3980-8a2a-11ea-81f6-dc359bef3885.png)

![image](https://user-images.githubusercontent.com/18549980/80569239-12b06b80-8a2b-11ea-88d6-6dd92679fb44.png)

情况应该与https://github.com/umijs/umi/issues/4430 相同

 
- **Umi Version**: 3.1.0
- **Node Version**: 10.15.3
- **Platform**: windows

**Comment by johanazhu** [comment]
我也遇到这个问题了

**Comment by johanazhu** [comment]
> 我也遇到这个问题了

我原本的 Umi 版本是 3.2.3，后来升级到 3.2.17 就可以了
