### ISSUE TITLE
object.entries is not a function, js报错, 这个语法没有做转换

### ISSUE THREAD

**Issue by hopperhuang** [umijs/umi#4562]
## What happens?
object.entries is not a function, js报错, 这个语法没有做转换,
在ios10的浏览器中，因为此错误打开页面失败
奇怪的是，在开发环境中，可以正常打开页面，build后，却出现问题。

![image](https://user-images.githubusercontent.com/20254356/80572711-54dcab80-8a31-11ea-9de0-bd131e96d385.png)

## Mini Showcase Repository(REQUIRED)

[demo 地址](https://github.com/hopperhuang/umi_analyze_bug)
> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

```
npm install 
npm run build
cd dist 
serve 
```
然后访问页面

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.
希望object.entries 语法得到转换不会报错

## Context

- **Umi Version**: umi@2.13.13 
- **Node Version**:  8.11.3
- **Platform**:

![image](https://user-images.githubusercontent.com/20254356/80572727-5a39f600-8a31-11ea-9a63-8410b50616f6.png)

**Comment by hopperhuang** [comment]
可以通过 增加 额外的babel插件： transform-es2017-object-entries 解决此问题。
但是，我觉得问题的关键在于， 为什么在框架层没有做这层的转换呢？ 希望得到回答和解决。

**Comment by snice** [comment]
> 可以通过 增加 额外的babel插件： transform-es2017-object-entries 解决此问题。
> 但是，我觉得问题的关键在于， 为什么在框架层没有做这层的转换呢？ 希望得到回答和解决。

https://umijs.org/zh-CN/config#targets 可以通过配置即可

**Comment by hopperhuang** [comment]
> > 可以通过 增加 额外的babel插件： transform-es2017-object-entries 解决此问题。
> > 但是，我觉得问题的关键在于， 为什么在框架层没有做这层的转换呢？ 希望得到回答和解决。
> 
> https://umijs.org/zh-CN/config#targets 可以通过配置即可

配置默认targets 就是ios10, 同事也尝试把配置降到ios: 7 ,依旧无法解决。

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
