### ISSUE TITLE
Problem with 404 page

### ISSUE THREAD

**Issue by gracjan-op** [umijs/umi#4564]
## What happens?

I have fresh instaled umi project with very easy config file and all is working ok in dev mode but when i build this project and try to test builded version by "serve" ir even deploy on Netlify then application not working correctly. I can not reach 404 page which i have in ma pages folder.

CONFIG:
![obraz](https://user-images.githubusercontent.com/25821211/80574045-65752d80-8a01-11ea-97ad-4bd8167300aa.png)

PRODUCTION MODE:
![obraz](https://user-images.githubusercontent.com/25821211/80574070-71f98600-8a01-11ea-9a66-0012eda0575a.png)

DEV MODE:
![obraz](https://user-images.githubusercontent.com/25821211/80574117-863d8300-8a01-11ea-97a5-53fbf61329bf.png)

## Mini Showcase Repository(REQUIRED)

[LINK](https://github.com/gracjan-op/umi-test)

## How To Reproduce

yarn build and try to use 'serve' or some kind of deploy of "dist" folder

## Context

- **Umi Version**: 3.1.2
- **Node Version**: 12.16.1
- **Platform**: WIndows 10

**Comment by xiaohuoni** [comment]
问题是你的部署有错误，如果没使用 hash 模式，需要服务端配置路由 fallback 到 index.html。
你可以尝试添加 
```ts
history: {
    type: 'hash'
},
```
![image](https://user-images.githubusercontent.com/11746742/81132820-4850d980-8f82-11ea-8010-60a4f0b35e43.png)
