### ISSUE TITLE
Umi项目环境不明

### ISSUE THREAD

**Issue by ILiuDongHui** [umijs/umi#4568]
Umi 项目 yarn 恢复依赖时，报错 gyp ERR   

但是在文档里丝毫没有提过需要 node-gyp，希望将Umi需要用到的环境解释清楚

**Comment by leftstick** [comment]
`node-gyp`， 这个不是umi的直接依赖，是更低层的依赖。的确不用专门在umi文档里提出。因为不需要你对他做什么操作。
所以如果你安装依赖时因为这个报错，那就得贴出你的具体可复现repo了。
