### ISSUE TITLE
umi3.x打包组件被当成依赖引入，model追踪错误

### ISSUE THREAD

**Issue by haoyinag** [umijs/umi#4569]
### 问题一：路由页面引入被当成依赖，提示
![image](https://user-images.githubusercontent.com/24349947/80677103-db08f880-8aea-11ea-9731-255101aea61d.png)
  ERROR  Failed to compile with 1 errors                                                                          2:07:00 PM

This dependency was not found:

* @/pages/User/Login in ./src/.umi-production/core/routes.ts

To install it, you can run: npm install --save @/pages/User/Login
Child
    
    ERROR in ./src/.umi-production/core/routes.ts
    Module not found: Error: Can't resolve '@/pages/User/Login' in '/root/h5/Chy-Umi-Pro/src/.umi-production/core'
     @ ./src/.umi-production/core/routes.ts 49:15-51:29
     @ ./src/.umi-production/umi.ts
     @ multi ./node_modules/_antd-dayjs-webpack-plugin@1.0.0@antd-dayjs-webpack-plugin/src/init-dayjs.js ./src/.umi-production/umi.ts
build failed
Error: build failed

### 问题二、model不明
```bash
 error  in /root/h5/Chy-Umi-Pro/src/.umi/plugin-dva/connect.ts

ERROR in /root/h5/Chy-Umi-Pro/src/.umi/plugin-dva/connect.ts(10,15):
10:15 Cannot find module '/root/h5/Chy-Umi-Pro/src/pages/user/model'.
     8 | export * from '/root/h5/Chy-Umi-Pro/src/pages/demo/useModel/model';
     9 | export * from '/root/h5/Chy-Umi-Pro/src/pages/Task/Today/model';
  > 10 | export * from '/root/h5/Chy-Umi-Pro/src/pages/user/model';
       |               ^
    11 | 
    12 | export interface Action<T = any> {
    13 |   type: T

Child
    
    ERROR in /root/h5/Chy-Umi-Pro/src/.umi/plugin-dva/connect.ts
    ERROR in /root/h5/Chy-Umi-Pro/src/.umi/plugin-dva/connect.ts(10,15):
    10:15 Cannot find module '/root/h5/Chy-Umi-Pro/src/pages/user/model'.
         8 | export * from '/root/h5/Chy-Umi-Pro/src/pages/demo/useModel/model';
         9 | export * from '/root/h5/Chy-Umi-Pro/src/pages/Task/Today/model';
      > 10 | export * from '/root/h5/Chy-Umi-Pro/src/pages/user/model';
           |               ^
        11 | 
        12 | export interface Action<T = any> {
        13 |   type: T
build failed
Error: build failed

```

- **Umi Version**:
"@umijs/preset-react": "1.x",
    "@umijs/test": "^3.1.1",
    "antd-dayjs-webpack-plugin": "^1.0.0",
    "cross-env": "^7.0.2",
    "lint-staged": "^10.0.7", 
    "prettier": "^1.19.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0", 
    "umi": "^3.1.1",
- **Node Version**:
v12.16.3
- **Platform**:
chrome浏览器

**Comment by xiaohuoni** [comment]
@haoyinag 问题2，是因为两个 model 里面有同名的导出变量嘛？还是什么原因？

**Comment by haoyinag** [comment]
@xiaohuoni 并不是刚找到原因，effects中的方法不能直接用query，否则需要手动刷新页面
```bash
  effects: {
-   query: Effect;
+  queryTest: Effect;
  };


  effects: {
 -    *query({ payload }, { call, put }: { call: any; put: any }): any {
+    *queryTest({ payload }, { call, put }: { call: any; put: any })
```

**umi3.x**还是有很多莫名的坑，还是希望多点测试吧。
有时候带来简便的同时也有可能隐藏了很多小问题。
现在当真是后悔新项目直接上umi3了，抹泪ing...

**Comment by haoyinag** [comment]
@xiaohuoni 新增一个坑，开启immer之后无效
![image](https://user-images.githubusercontent.com/24349947/82984910-a161d980-a025-11ea-8c18-0a49cfb24de7.png)

**Comment by immrj** [comment]
【umi3.x打包组件被当成依赖引入】这问题咋解决啊，我本地是可以的，服务器上就不行，头疼

**Comment by lxnxbnq** [comment]
@immrj 看一下你pages里面的目录大小写和你配置的路由大小写是否匹配。服务器是linux，对大小写敏感

**Comment by flyingFlowers** [comment]
@xiaohuoni 请问这个问题解决了吗，遇到相同的问题

**Comment by xiaohuoni** [comment]
> @xiaohuoni 请问这个问题解决了吗，遇到相同的问题

什么问题，再提一个，提供可复现的 demo。这些长久不处理的问题，我会关闭

**Comment by GloriaCHL** [comment]
@xiaohuoni 这里的问题一那个在服务器部署的问题。我也遇到了。我是用最新的 ant design pro v4 来搭建的项目，在本地可以正常build，但是服务器上就出现了跟上面提问的那个问题一一样的错误...虽然想提供可复现demo，但是本地OK，只有服务器出现这点实在是...

**Comment by xiaohuoni** [comment]
@GloriaCHL 这种异常的话，很大概率是大小写敏感问题，你可以从这个角度排查下

**Comment by GloriaCHL** [comment]
的确是大小写问题，3Q

**Comment by huahouye** [comment]
ubuntu 20.04 编译遇到同样的问题，我遇到的问题是大小写问题，需要修改 config/routes.ts 的 compoment 路经，https://github.com/huahouye/go-ant-design-pro/commit/d2bc37e9ea6ce1031359a6e393cce96fa941d709 这里，奇怪的是 User 有时候是 user，不清楚哪里出问题。macos 编译则没有大小写问题。

**Comment by 1c7** [comment]
## 解决了问题，也是大小写敏感造成的，简单分享一下

目前在用 Github Action 跑 `npm run build` 然后把 `dist/` 目录放到到 AWS S3 的某个 bucket 的跟路径下。   
然后 S3 + CloudFront 的形式部署前端网站。

本地 macOS  跑 `npm run build` 毫无问题，但 Github Action 里会报错

![image](https://user-images.githubusercontent.com/1804755/122630662-0a683380-d0f8-11eb-9bc3-314702bd96b6.png)

![image](https://user-images.githubusercontent.com/1804755/122630686-35528780-d0f8-11eb-9b84-7c5b4470b89a.png)

## 总结
* `config/routes.js` 里写的是 `component: './User/Login'` 和 `component: './User/Register'` 
* 但是文件夹名字是 `src/pages/User/login` 和 `src/pages/User/register`
* 修复为正确的 `src/pages/User/Login` 和 `src/pages/User/Register`
* 并且让 git 不要忽略大小写 `git config core.ignorecase false`
* git commit & push 后
* 再次触发 Github Action 此时可正常完成

![image](https://user-images.githubusercontent.com/1804755/122630722-8e222000-d0f8-11eb-87de-a6cc805eebf3.png)

**Comment by chenjunjia97** [comment]
> ## 解决了问题，也是大小写敏感造成的，简单分享一下
> 目前在用 Github Action 跑 `npm run build` 然后把 `dist/` 目录放到到 AWS S3 的某个 bucket 的跟路径下。 然后 S3 + CloudFront 的形式部署前端网站。
> 
> 本地 macOS 跑 `npm run build` 毫无问题，但 Github Action 里会报错
> 
> ![image](https://user-images.githubusercontent.com/1804755/122630662-0a683380-d0f8-11eb-9bc3-314702bd96b6.png)
> 
> ![image](https://user-images.githubusercontent.com/1804755/122630686-35528780-d0f8-11eb-9b84-7c5b4470b89a.png)
> 
> ## 总结
> * `config/routes.js` 里写的是 `component: './User/Login'` 和 `component: './User/Register'`
> * 但是文件夹名字是 `src/pages/User/login` 和 `src/pages/User/register`
> * 修复为正确的 `src/pages/User/Login` 和 `src/pages/User/Register`
> * 并且让 git 不要忽略大小写 `git config core.ignorecase false`
> * git commit & push 后
> * 再次触发 Github Action 此时可正常完成
> 
> ![image](https://user-images.githubusercontent.com/1804755/122630722-8e222000-d0f8-11eb-87de-a6cc805eebf3.png)

确实是大小写的问题,git没提交大小写的变化

**Comment by fliu2476** [comment]
> * git config core.ignorecase false

感谢总结！确实是大小写问题。
我这边是本地修改了大小写，git忽略了这一处更改，修改git配置，重新提交构建成功了。
