### ISSUE TITLE
加入chunkids: named 优化打包产物缓存配置

### ISSUE THREAD

**Issue by hopperhuang** [umijs/umi#4570]
## Background

背景：优化产物缓存。在自身项目打包时，我发现，增加新的页面，会引起旧页面hash值的变化，导致缓存失效。

我用自己的项目做测试的例子。在原有项目的基础上，我加入了一个叫做some的页面，导致了如下的变化。

有写异步chunk是不需要变化的，因为新增了模块，导致了模块id变化了,影响了打包产物的hash值。

![image](https://user-images.githubusercontent.com/20254356/80678502-96cb2780-8aed-11ea-82fe-e87eed2c8689.png)
## Proposal

我建议在打包时，默认加入如下配置。
```
  optimization: {
    chunkIds: 'named'
  }
```
加入此配置后，打包产物的diff

![image](https://user-images.githubusercontent.com/20254356/80678706-0c36f800-8aee-11ea-8b68-31a906521326.png)
Describe the solution you'd like, better to provide some pseudo code.

## Additional context

umi ：umi@2.13.13 
更多相关的资料：
https://gitmemory.com/issue/tpai/tpai.github.io/93/520283012
https://webpack.js.org/configuration/optimization/#optimizationchunkids

**Comment by xiaohuoni** [comment]
@sorrycc 看看这个，搞不搞？

**Comment by hopperhuang** [comment]
@xiaohuoni 
这个问题出现在umi@2里面，对应的应该是webpack@4。
但是经过我的事件发现即使加入了这个设定，hashcode还是会变化，原因是这是webpack里面hashcode计算机制的一个bug，在webpack@4和webpack@5中都有这个问题，目前wepack已经在处理好这个问题了，在webpack@5中已经得到了修复。

我的建议是，对于umi@2的用户，建议他们自行配置  chunkIds: 'named', 并告知，即使配置好后，依然有机会发生hashcode变化的问题。（毕竟在webpack@4你帮他们配了也是白搭）

对于umi@3的用户，umi框架应该跟进升级内置的webpack,并开放chunkIds: 'named'及类似的配置，方便用户选择是否进行优化。

[向wepack反应的bug](https://github.com/webpack/webpack/issues/10864)
[原来webpack中已经有人反映过的问题，在此统一跟踪处理的issue](https://github.com/webpack/webpack/issues/9520)
[问题已经在20多天前这个issue中得到解决，应该升级webpack@5就可以了](https://github.com/webpack/webpack/pull/11339)

建议umi继续关注相关的issue和变动。

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.

**Comment by HiWayne** [comment]
所以还没有上chunkhash？
