### ISSUE TITLE
[Feature Request] chainWebpack add examples for sass

### ISSUE THREAD

**Issue by mu1004** [umijs/umi#4572]
## Background
我使用sass，但不知道如何配置，webpack-chain中并没有createCSSRule的参数，不知道如何编写，希望大神能给个例子

**Comment by sherry007** [comment]
可以查看我之前提的 #4486，我当时是添加音视频类型的 loader
```javascript
// .umirc.js
chainWebpack(memo) {
  memo.module
    .rule('media')
    .test(/\.(mp3|4)$/)
    .use('file-loader')
    .loader(require.resolve('file-loader'))
}
```
sass 配置应该差不多，修改 test 里面的文件类型以及所用的 loader

**Comment by aixfox** [comment]
用这个
https://umijs.org/zh-CN/plugins/plugin-sass

**Comment by mu1004** [comment]
> 用这个
> https://umijs.org/zh-CN/plugins/plugin-sass
umi的版本是 umi@3.1.2 报下错误啊
Invalid config key: sass

**Comment by mu1004** [comment]
> 可以查看我之前提的 #4486，我当时是添加音视频类型的 loader
> 
> ```js
> // .umirc.js
> chainWebpack(memo) {
>   memo.module
>     .rule('media')
>     .test(/\.(mp3|4)$/)
>     .use('file-loader')
>     .loader(require.resolve('file-loader'))
> }
> ```
> 
> sass 配置应该差不多，修改 test 里面的文件类型以及所用的 loader，希望有所帮助

这个可以， 但是感觉应该更简单一点一点，这个配置太复杂了

**Comment by sherry007** [comment]
> > 可以查看我之前提的 #4486，我当时是添加音视频类型的 loader
> > ```js
> > // .umirc.js
> > chainWebpack(memo) {
> >   memo.module
> >     .rule('media')
> >     .test(/\.(mp3|4)$/)
> >     .use('file-loader')
> >     .loader(require.resolve('file-loader'))
> > }
> > ```
> > 
> > 
> > sass 配置应该差不多，修改 test 里面的文件类型以及所用的 loader，希望有所帮助
> 
> 这个可以， 但是感觉应该更简单一点一点，这个配置太复杂了

不算复杂吧。。

**Comment by ppatch** [comment]
@mu1004 @sherry007 解决了吗

**Comment by allxblue** [comment]
UMI (用的是2.0) 實在很少人用，使用@umijs/plugin-sass 1.1.1 ，添加 SCSS global variable 可在 config.js (.umirc.js) 添加

    sass: {
        additionalData: ` 
            @import '@/assets/scss/includes/_variable.scss';
            @import '@/assets/scss/includes/_style-effects.scss';
        `
    }
給查詢的人參考。
關鍵字： sass, additionalData, 全域變量
