### ISSUE TITLE
[Feature Request] 权限和动态菜单如何组合使用

### ISSUE THREAD

**Issue by fangzhengjin** [umijs/umi#4573]
## Background

由于项目需要按需分配用户的菜单, 而在app.tsx的layout无法通过initialState拿到已经初始化的菜单数据

## Proposal

建议将layout从变量改为函数, 默认传入initialState, 在initialState变动时重新调用layout配置更新布局

**Comment by xiaohuoni** [comment]
搭配 https://umijs.org/zh-CN/plugins/plugin-access 使用的话，应该是可以的。

**Comment by fangzhengjin** [comment]
> 搭配 https://umijs.org/zh-CN/plugins/plugin-access 使用的话，应该是可以的。

权限和动态菜单这个咋搭配? 我需要从后台返回具体的菜单和路径 不仅仅是路由中的 也可能是站外url跳转

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.

**Comment by Longder** [comment]
请问下各位大佬，如果想实现按钮级别的动态，就是使用useAccess hook来做动态 展示，怎么弄。
