### ISSUE TITLE
[Feature Request] 如何在umi@3中使用umi-plugin-react中的routes配置？How to use routes config like umi-plugin-react in umi@3?

### ISSUE THREAD

**Issue by NicoKam** [umijs/umi#4574]
## Background

公司的项目大多使用umi@2，约定式路由的规则比较随意，任意的jsx文件都能被识别。为了让约定式路由更加清晰，我们强制加入了规则（通过umi-plugin-react的routes配置）：
1.必须是index.js才能够被识别为页面入口
2.路径不得包含大写字母（业界习惯很少存在大写字母的路由）
3.特别的资源路径不会被识别为路由（如components目录，services目录，models目录，layouts目录等）

## Proposal

看到umi@3的文档，preset-react中移除了routes配置，所以不知道该如何延续上述功能。
当然完全使用配置式路由也可以，但我还是比较青睐约定式路由的便捷性。
求大神给个好的方案。
要是实在不行，我可能考虑放弃约定式路由，自己实现一个插件，运行时监控pages目录，自动生成配置式路由。

英文水平一般，所以直接中文描述了。

**Comment by 104gogo** [comment]
![image](https://user-images.githubusercontent.com/8522646/80780624-419d1d80-8ba2-11ea-9186-1981ff63de4e.png)
同问一下，升级到UMI3，按照官方的routes配置，报这错误是为什么呢？

**Comment by xiaohuoni** [comment]
https://alitajs.com/plugins/routes 用这个吧。和umi@2 保持一样的用法，只是配置打平了。

**Comment by NicoKam** [comment]
> https://alitajs.com/plugins/routes 用这个吧。和umi@2 保持一样的用法，只是配置打平了。

感谢，其实我也是这个意思，打算自己实现一个简单的插件。只是想着如果官方有开放的话直接用最好了，毕竟有官方文档，大家看一份就好，不用到处翻其它地方看使用方法。

**Comment by xiaohuoni** [comment]
@NicoKam 这就是官方的插件，代码在 https://github.com/umijs/plugins/pull/25 一直 hold 是觉得没人用。

**Comment by NicoKam** [comment]
> @NicoKam 这就是官方的插件，代码在 [umijs/plugins#25](https://github.com/umijs/plugins/pull/25) 一直 hold 是觉得没人用。

忠实用户来了，赶紧上官方文档吧~~~

**Comment by NicoKam** [comment]
前些日子又准备升级一下框架，思考了一下还是决定自己写插件了。https://www.npmjs.com/package/umi-plugin-convention-routes
