### ISSUE TITLE
umi.js包含了多语言文件导致体积很大

### ISSUE THREAD

**Issue by 104gogo** [umijs/umi#4576]
## What happens?
如下图，umi.js包含了多语言的文件，导致umi.js体积很大，请问有配置可以拆出来吗？
![image](https://user-images.githubusercontent.com/8522646/80858889-2a882980-8c8f-11ea-8e95-4ecd1dc0d848.png)

## 相关环境信息

- **Umi 版本**：3.1.2 
- **Node 版本**：
- **操作系统**：

**Comment by 104gogo** [comment]
搞定

**Comment by Sun-Liu** [comment]
@104gogo  请问你是如何解决的吗？

**Comment by 104gogo** [comment]
> @104gogo 请问你是如何解决的吗？

打包的时候，只引入对应语言的包，我们部署了多个语言站点
