### ISSUE TITLE
运行时配置：patchRoutes动态添加多级路由，子路由没效果。

### ISSUE THREAD

**Issue by blackboy1987** [umijs/umi#4579]
运行时配置：patchRoutes动态添加多级路由，子路由没效果。

仓库地址：
https://github.com/blackboy1987/umijs2.git

![image](https://user-images.githubusercontent.com/6405701/80908610-cc714a00-8d53-11ea-9dd9-be660084f71d.png)
参考文档https://umijs.org/zh-CN/docs/runtime-config#%E9%85%8D%E7%BD%AE%E9%A1%B9
里面的配置。访问第一层路由：http://localhost:8000/index1 是可以正常访问的。但是下的子路由就不行了。也就是说：http://localhost:8000/index1/2 这个访问地址是404了。
后来查看antd pro 里面的issue和umijs的issue。有人反馈说是组件没有加载进去。因此我在.umirc.ts文件里面把这几个组件也加载进去了。
![image](https://user-images.githubusercontent.com/6405701/80908661-3e499380-8d54-11ea-9861-d475b5d3d2ba.png)

发现还是不行。
使用的插件版本信息：
"@umijs/preset-react": "1.x",
    "@umijs/test": "^3.1.2",
    "lint-staged": "^10.0.7",
    "prettier": "^1.19.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "umi": "^3.1.2",
    "yorkie": "^2.0.0"

node版本是：12.14.0
mac电脑

**Comment by xiaohuoni** [comment]
@blackboy1987 
![image](https://user-images.githubusercontent.com/11746742/81132382-d3c96b00-8f80-11ea-949a-c42c839cfb41.png)

**Comment by xiaohuoni** [comment]
你这问题是 layout 层级的 `exact: true`

**Comment by qianweichen** [comment]
父级的component不要配置，否则会默认模糊匹配到父级。
使用keepalive的tabs组件时不会新建标签卡
