### ISSUE TITLE
umi3 使用plugin-qiankun，异常 Unexpected keys "@@dva"

### ISSUE THREAD

**Issue by eevin** [umijs/umi#4582]
主子应用都使用umi 3 框架
每次子应用切换回主应用都会报异常信息：
devScripts.js:5035 Unexpected keys "@@dva", "global" found in preloadedState argument passed to createStore. Expected to find one of the known reducer keys instead: "routing", "login", "activities", "project", "businessRelease", "hello", "sysMenu", "sysRole", "sysStatic", "sysUrl", "sysUser", "loading". Unexpected keys will be ignored.
in Context.Provider

qiankun插件："@umijs/plugin-qiankun": "^2.1.1",

**Comment by xiaohuoni** [comment]
需要重现demo，微前端
