### ISSUE TITLE
[Feature Request] devServer lazy options

### ISSUE THREAD

**Issue by ycjcl868** [umijs/umi#4584]
## Background

https://webpack.js.org/configuration/dev-server/#devserverlazy-

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/80958567-d7050f80-8e37-11ea-8224-8c880906633e.png)

@sorrycc  cc

**Comment by ycjcl868** [comment]
lazy was removed for next release，https://github.com/webpack/webpack-dev-middleware/issues/409#issuecomment-557513396

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
