### ISSUE TITLE
yarn create umi 组件模板对 dumi 的支持

### ISSUE THREAD

**Issue by L-Jovi** [umijs/umi#4587]
目前 yarn create umi 后选择了 lib 的模式开发组件，看项目依赖是 father 集成了 docz，通过 mdx 文件输出组件文档

想了解下，为何不是默认集成 dumi，在我理解应该是一样的东西，用一种解决方案比较好理解

**Comment by xiaohuoni** [comment]
应该是还没来得及修改。请使用dumi。
```
$ npx @umijs/create-dumi-lib        # 初始化一个文档模式的组件库开发脚手架
# or
$ yarn create @umijs/dumi-lib

$ npx @umijs/create-dumi-lib --site # 初始化一个站点模式的组件库开发脚手架
# or
$ yarn create @umijs/dumi-lib --site
```

**Comment by xiaohuoni** [comment]
@PeachScript 看看，是要合并，还是两边维护，还是移除 create-umi 里面的 lib ？

**Comment by PeachScript** [comment]
@xiaohuoni create-umi 是 Umi 2 的脚手架吧

**Comment by xiaohuoni** [comment]
@PeachScript 不是的，create-umi 都有支持的，只是有些还没迁移到umi@3

**Comment by L-Jovi** [comment]
懂了，这边先用 dumi 吧，如果合并了之后支持到 create-umi library 里面了，麻烦通知下哈，感谢~
