### ISSUE TITLE
在npm中找不到umi/locale依赖包，导致项目启动报错！

### ISSUE THREAD

**Issue by gaoyafengyagao** [umijs/umi#4588]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
什么版本，怎么重现，请按要求提交issues
