### ISSUE TITLE
history push里的query 传过去的参数如果是数组存在bug

### ISSUE THREAD

**Issue by whereiscode** [umijs/umi#4589]
history push里的query 传过去的参数如果是数组存在bug

 `history.push({
            pathname: url,
            query: {
                goods_ids:[1,23,4,56,6]
            },
        });
`
push过去之后:
BUG1: 导航栏的链接是 localhost:8000/#/url? goods_ids=1
BUG2: history.location.query 获得的goods_ids是[1,23,4,56,6]

ok ,那换种思路吧，我们传：
 `history.push({
            pathname: url,
            query: {
               `goods_ids[]`:[1,23,4,56,6]
            },
        });
`
这样的话 导航栏的链接正确了
那通过 history.location.query获得来测试下，我理解是 history.location.query.goods_ids 就可以获得，但是必须得写成history.location.query['goods_ids[]']

我觉得这不符合http的标准，我没见过这样的GET方式

**Comment by whereiscode** [comment]
又发现一个bug   history的push过后的location.search 和 刷新后的location.search  不一致

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/81767637-7c407780-950b-11ea-9db3-171afef41aa5.png)

```
<h1 onClick={()=>props.history.push({ pathname: 'home', query: { goods_ids:[1,23,4,56,6] }, })}>Go Home Page</h1>

```

**Comment by quarkcms** [comment]
@xiaohuoni 大侠，这种方法依然有一个bug，就是从浏览器刷新的时候，无法获取到参数

**Comment by xiaohuoni** [comment]
@quarkcms 我这边都是正常的，有复现的demo嘛？

**Comment by quarkcms** [comment]
我是手动点击浏览器的刷新按钮，获取到的参数是object这么个字符串

**Comment by dydanyu** [comment]
请问是怎么解决的？

**Comment by dydanyu** [comment]
> ![image](https://user-images.githubusercontent.com/11746742/81767637-7c407780-950b-11ea-9db3-171afef41aa5.png)
> 
> ```
> <h1 onClick={()=>props.history.push({ pathname: 'home', query: { goods_ids:[1,23,4,56,6] }, })}>Go Home Page</h1>
> ```

数组传多个值的时候是正常的，但是传一个值，刚进到页面打印出来是数组类型，再刷新下页面就变成字符串了
