### ISSUE TITLE
关于 addRendererWrapperWithComponent API

### ISSUE THREAD

**Issue by phobal** [umijs/umi#4593]
## Background

之前自定义写的插件的 umi 版本 从 2.x 升级到 3.x 以后，发现 `addRendererWrapperWithComponent`  不存在了，在 umi3 的源码中也未找到相关代码，请问是移除了么？如果是移除了是出于什么原因移除呢？有没有替代的接口可以达到同样的目的呢？

## Proposal

无

## Additional context

无

**Comment by xiaohuoni** [comment]
现在使用runtime替代了，你可以看这里 https://umijs.org/zh-CN/docs/runtime-config#rootcontainerlastrootcontainer-args

**Comment by phobal** [comment]
感谢 @xiaohuoni 

PS：其他人要是也遇到该问题可以参考我的方式：https://github.com/phobal/plugin-qiankun-slave/blob/master/src/index.ts
