### ISSUE TITLE
函数组件model要刷新页面才生效，首页提示Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by haoyinag** [umijs/umi#4594]
## What happens?
1、yarn start或者yarn build之后打开页面；
2、使用model的地方不生效，手动刷新页面之后才可以。 
3、有且只有首页一直提示Cannot read property 'name' of undefined，但是首页相关的文件没有任何name相关的字段，找不到报错的地方
```bash
devScripts.js:5035 uncaught at _callee3 at _callee3 
 at _callee7 
 at takeEvery 
 at _callee 
 at _callee 
 Error: TypeError: Cannot read property 'name' of undefined
    at query$ (http://10.100.13.179:3000/umi.js:176631:34)
```
 
- **Umi 版本**：
"umi": "^3.1.1"
- **Node 版本**：
$ node -v
v12.16.2
- **操作系统**：
windows 10

**Comment by xiaohuoni** [comment]
请提供复现demo

**Comment by haoyinag** [comment]
@xiaohuoni 这个抱歉我写法的问题已经解决了，帮忙看下另外的问题
https://github.com/umijs/umi/issues/4685

**Comment by Mh2336393** [comment]
> @xiaohuoni 这个抱歉我写法的问题已经解决了，帮忙看下另外的问题
> #4685
> 这个有代码，不知道是不是也是我的写法有问题

什么问题 我也遇到了

**Comment by liufenghua808** [comment]
@haoyinag   请教下大神如何解决的这个问题  https://github.com/umijs/umi/issues/4594，
我遇到的这个问题和您遇到的有些类似：https://github.com/umijs/umi/issues/6416

**Comment by haoyinag** [comment]
@Mh2336393 @liufenghua808 抱歉我很久没用ALi系的了，按照我上面的描述大概率是写法/用法不符合；所以可以严格看下自己的流程有没有问题。

引起的问题猜测是库不够健壮，其次是内部做了性能相关的处理导致监听不到！？只是猜测，不一定。

另外，使用第三方库，特别是强封装过的，尽量不要让自己的代码再次嵌套过深，否则容易引起类似的不可预知的问题；
