### ISSUE TITLE
希望给对应ts环境更多的类型提示，如route、call等

### ISSUE THREAD

**Issue by haoyinag** [umijs/umi#4597]
typescript能带来很好的开发体验，但是很多用到的umi或者别的库封装好的API的时候类型定义有点茫然，只能用any大法跳过去，但这样就失去ts的意义了。

项目中经常会有如route、或者请求时候的call、put等等，这些起码我不知道对应的类型是啥

```bash
    *queryTest({ payload }, { call, put }: { call: any; put: any }): any {
      yield put({
        type: "save",
        payload: payload.name,
      });
    },
```

**Comment by ycjcl868** [comment]
dva？

**Comment by haoyinag** [comment]
@ycjcl868 这只是举个例子    我觉得大厂有那么多好的实践，可能在内部司空见惯的东西，在小厂小作坊可能就是一些很好的借鉴了
