### ISSUE TITLE
'umi' does not contain an export named 'qiankunStart'

### ISSUE THREAD

**Issue by zhangfu-git** [umijs/umi#4600]
## What happens?
umi3.0 does not contain an export named 'qiankunStart'

## Context
- **Umi Version**: ^3.0.0

**Comment by xiaohuoni** [comment]
你说的是什么问题。

**Comment by zhangfu-git** [comment]
这是使用umi3.0 import { qiankunStart } from 'umi' 报的错误
目前已经解决，直接使用 import { start } from 'qiankun'
