### ISSUE TITLE
报错：Unhandled Rejection (ReferenceError): tryApplyUpdates is not defined

### ISSUE THREAD

**Issue by tangeleven** [umijs/umi#4601]
## What happens?

启动项目正常，在更改代码保存的时候，浏览器有时候会报这个错误（Unhandled Rejection (ReferenceError): tryApplyUpdates is not defined ），刷新浏览器页面又显示正常了，不知道这个是什么问题引起的？

![error](https://user-images.githubusercontent.com/34758822/81141688-06cf2700-8fa0-11ea-96d7-802360a34bdb.png)

## Mini Showcase Repository(REQUIRED)

> git@github.com:tangeleven/umi3.0-demo.git

## How To Reproduce

**Steps to reproduce the behavior:** 
1. yarn 
2. yarn start
3. 随便改动src目录下的某个代码，然后保存，就会出现这个报错，复现率不高，偶尔会出现。（修改css的时候，这个bug的复现率特别高）

**Expected behavior:** 
希望找到这个错误到底是什么问题导致的。

## Context

- **Umi Version**: ^3.1.2
- **Node Version**: v10.18.1
- **Platform**: windows

**Comment by yy923683900** [comment]
一样，遇到了这个问题

**Comment by ycjcl868** [comment]
+1

**Comment by tangsengrouyidai** [comment]
+2

**Comment by OutBigpeng** [comment]
+3

**Comment by niechenhua** [comment]
+4

**Comment by sorrycc** [comment]
![14](https://user-images.githubusercontent.com/35128/82793564-ac8cfc00-9ea3-11ea-8b90-2e5664f04c1c.gif)
![13](https://user-images.githubusercontent.com/35128/82793570-aeef5600-9ea3-11ea-869a-edd311ecb982.gif)
试着改 JS 和 CSS，都没能复现。

**Comment by ycjcl868** [comment]
最新 3.2.x 好像修了，试下最新版

**Comment by ycjcl868** [comment]
可以是这个修复的 https://github.com/umijs/umi/pull/4681

**Comment by JhonXY** [comment]
似乎并没有修复：
![image](https://user-images.githubusercontent.com/21687167/82998004-bb0d1c00-a039-11ea-984d-2b2f3b60218d.png)
![image](https://user-images.githubusercontent.com/21687167/82998017-bfd1d000-a039-11ea-810a-c2897cda7c85.png)

**Comment by ycjcl868** [comment]
https://github.com/umijs/umi/issues/4601 这个 PR 能修复
