### ISSUE TITLE
umi 配置uglifyJSOptions报错warning is not a supported option

### ISSUE THREAD

**Issue by JoeYnnn** [umijs/umi#4602]
## What happens?
配置内uglifyJSOptions
export default {
  uglifyJSOptions(opts) {
    opts.uglifyOptions.compress.warning = true;
    return opts;
  },
};
实测warning报错，改为warnings则编译正常

报错信息为：
11.async.js from UglifyJs
`warning` is not a supported option
error  

## Context

- **Umi Version**:2.27
- **Node Version**:10.16.0
- **Platform**:

**Comment by xiaohuoni** [comment]
设置 warnings 有效吗？

**Comment by JoeYnnn** [comment]
> 设置警告有效吗？

将warning改为warnings之后，亲测有效

**Comment by xiaohuoni** [comment]
👍
