### ISSUE TITLE
npm 打包时提示内存不足 max_old_space_size 属性在哪能设置

### ISSUE THREAD

**Issue by 544751779** [umijs/umi#4604]
react 建议设置max_old_space_size 不知道写在哪里

**Comment by xiaohuoni** [comment]
https://blog.csdn.net/qq_20881087/article/details/62428774
百度

**Comment by chenshuai2144** [comment]
"large-start": "node --max-old-space-size=8192 ./node_modules/.bin/umi start",
"large-build": "node --max-old-space-size=8192 ./node_modules/.bin/umi build",
