### ISSUE TITLE
umi3可以根据url中的参数来动态的设置config.ts文件中的theme值吗

### ISSUE THREAD

**Issue by avalonWx** [umijs/umi#4606]
现在有个需求是不同入口进来的链接有参数，根据参数显示不同的主色调，意思就是浏览器进入页面的时候修改theme的@primary-color值，以前只做过手动切换的，现在是要在页面渲染前就根据url参数决定使用哪一种主题，有这样的需求实现吗？

**Comment by xiaohuoni** [comment]
https://preview.pro.ant.design/dashboard/analysis?language=en-US&layout=topmenu&contentWidth=Fixed&primaryColor=volcano
pro里面的实现，就是你这个效果
