### ISSUE TITLE
[Feature Request] Umi 3 support multiple routes templates

### ISSUE THREAD

**Issue by ycjcl868** [umijs/umi#4607]
## Background

Umi 2 specify templates for specific pages using `route.document`

https://v2.umijs.org/zh/guide/html-template.html#%E9%92%88%E5%AF%B9%E7%89%B9%E5%AE%9A%E9%A1%B5%E9%9D%A2%E6%8C%87%E5%AE%9A%E6%A8%A1%E6%9D%BF

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
