### ISSUE TITLE
umi如何配合lerna搭建monorepo项目?

### ISSUE THREAD

**Issue by Sayid1** [umijs/umi#4608]
## What happens?
使用npx @umijs/create-umi-app 创建项目后，项目结构如下
![image](https://user-images.githubusercontent.com/29008437/81160911-4ce6b380-8fbd-11ea-9f3e-6774353a7755.png)
lerna的项目结构如下
![image](https://user-images.githubusercontent.com/29008437/81161167-b8308580-8fbd-11ea-9bb1-af08e9d11742.png)

umi配合lerna的话，是下面的步骤吗？
1. 把umi创建的项目移到packages中
2. 把umi创建package.json的dependencies移到lerna的package.json中
3. 执行lerna bootstrap

如果不是，请大神指教一下正确的步骤 :)

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi-example-monorepo 这里有一个 demo
