### ISSUE TITLE
无法 引入本地js/css文件

### ISSUE THREAD

**Issue by Clickus** [umijs/umi#4609]
## What happens?

[http://106.13.26.17:8989/ERROR.png](url)

如图 :  我想引入本地js文件, 会出现上图中的报错。
           请问下，这个有什么解决方案不。

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：3.1.2
- **Node 版本**：10.16.3
- **操作系统**：win10

**Comment by Clickus** [comment]
![avatar](http://106.13.26.17:8989/ERROR.png)

**Comment by leftstick** [comment]
network 里， 请求 `xx/jquery.js` 的内容什么样子？

**Comment by Clickus** [comment]
![avatar](http://106.13.26.17:8989/NET.png)

## NETWORK 是没这个的  我是在开发模式下

**Comment by leftstick** [comment]
`publicPath` 为什么是 `./`？ 是你自己设置的么？ 

改成 '/'

**Comment by Clickus** [comment]
#####   我都尝试过  报的一样的错误  
![avatar](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAaAAAAB9CAIAAABrgyBLAAAS2ElEQVR4Ae1dW8hcVxWemf+WlGD+5qJtKhJIq0TQ0FqjYLUIii+FtmpBfCiipfiiQqiIRWn7oIKi1BeFUqrUF/FaxfbBeksvai+2BB+K2hRBTatpk7R/TJP/6oorfFnsvc8+e/Y5Z+bMmW/4may99re+tfa39yzO/JP5T39paalX8Dh8+PCePXsKJummAlSACrRdgUHbC2R9VIAKUIFcBWZzA7sWt2/fPlnSoUOHdGE6tJ6iBQsSUcCkhyOEBhWgArUr0OorOLSJ2pddSig9y29bpVEAVAwHDw0qQAWqKMAruHPqVWlnVTaAsVSACjSnwKgbnL0osz3F8WMIw4J9OXyYeBDi2BpuZx2Pzw+Pn0imgk6EWANIcaIAC6BNBahAjQqMusFp6fraRt/Rlz2c1p/YBQBDbJFGPhJ5i0Ks3w8PrsiGwHZqc4aA0aACVKAuBcbQ4NAj7BrgFENe+XYqxQ6GaAdxppxhCrnFBMNRvEUG7WB4EEknFaAC1RUYQ4OrXrTDIF0DLQYdxDZKO2tth6d0GExUGmUByG6dtKkAFWhIgbZ8iorGBCNjwemx6chgGdnh2YHBMuikAlQgrkB/xN9kkFc4rmIcG4VagO+Exxq2cSBcADaF4n2k9QhGw4NOJVSeIBKpU8LBAEIaVIAK1KvAqBtcvdWTjQpQASoQUaAtb1EjJXKKClABKpCnABtcnm6MogJUYAIUYIObgE1iiVSACuQpwAaXpxujqAAVmAAF2OAmYJNYIhWgAnkKsMHl6cYoKkAFJkABNrgJ2CSWSAWoQJ4CbHB5ujGKClCBCVCADW4CNoklUgEqkKdAyZft5b4zebyMogJUgAqMXYGSBud8p3Ls5bIAKkAFqEC6AnyLmq4VkVSACkyYAmxwE7ZhLJcKUIF0Bdjg0rUikgpQgQlTgA1uwjaM5VIBKpCuQMmHDOlERFKBPAX27NljP6x3hpbTTlnbYtSWWd9ps/iz9HRSATa4Tm7rxCwq3qeCy0DzgiEwv3k5HgsO0tLZSQXY4JrdVryu8HpTD4ZNpJcUPr9fCVKPtyS/MN8jpYpTF6XPGGIVjgESx9/EsLSYJpKSM0WByWtwFQ9TxfAUTYEZZS4kLTLQF4oAcb+sBQC/e2JKjfSFg0r5baDNaPnhhwESC3OcAFtMLbYwO7lqoSVJLQpMXoOrZdljJGnhiyGxJMAaeklHaJ32hEpkH50p7GyRHwAa06DAGBqcPXk4qb4z4sFUabgCgNcdxRDhwZ0GTGaB9J2+R/BwquGUATanHh06s+q0nGIDI/xFdpxNZ1EnSBy/zaVTzrPDgCEMy6xO67Fs6heMDxAPCCXE2pYBts+AKceIl+SAOZw4BUbd4ILnyTrFlgcOqBrqsbYV2uLFD7AYOpRnEDpgy2NtjUWUTlmn2PIAwKnNGWo4nE4ikFhCi7E2SBBlZ62dggTGBkoZMizl1xDAtHgQwg9mrA6GTGkuYMSQQAuwU7AtucPgDBECw8bCmW2UlprNzMBaFBh1g5OigycMTjFwRuEsXSpCLBJU6TxOuB2qDSqQix9OH1+vJz1ROjJYYTAcIttZOIM81mmj4IcznUdiI2AQagpBOh6kViM+64A5nDgFxtDgmtAoeEz1cEdeDE1UksGJCoOryCBsKMQvz7YPrKJ6dj+Rw2kBwbxFhdlAhzNjaLNkhDNkBAqMocEFjwWcYmQsG+GIBY+caX8WMDUU7Jz+YBScGuLw5A2dvJGSIvw11iNZsMxIRjtVb3bLHLSHSheUF7RKFccATGPiFBh1g5OTJEdKT5WIpQcr6IxIGQ9HoD21EoKhEw68NYIlBZ02Km4jrxp+PRIOZ5AKDIBpST7YR8Jjswedyokp5PKzFGUXZEq4hfnkEY8tCYmAF48WZmGYpTFVCvSXlpaKFizng38Prkicuvz6agSbM4RfjMiUhU2QbVfk2LIKpz0pQJ6DCwTY53HwQDr+YYc20bCxxI9MgVFfwY1sYUzUfgVsrymysQoFWBimrGEB1raYWuxGyWupkCSiABvcmI+BvE7sVQlfNmPeD6bvlgJscOPfz8Smlggb/3pYARVojQL8e3Ct2QoWQgWoQN0KlF3BPfNM3RnJRwWoABUYkQJlDW7XrhEVwjRUgApQgboV4FvUuhUlHxWgAq1RgA2uNVvBQqgAFahbATa4uhUlHxWgAq1RgA2uNVvBQqgAFahbgbIPGYrznfzbX1667yenH3t87djxwbYLN+/fv/36D2657E3FEZyhAlSACoxUgcwruJce/t0LBz57wcEnt53q7VxY3H6qd8FDTzx/4JZjjxwcafnDJltcHDaC+KlQoK6DURfPVIg+ikXmNLiTh589/vVvbl2b6c/O9gcz/V7/7PPs3OLa7LGv3XnyucOxwp0T4AxjkU3OpZchSP3JKyc9kc+P1FUK8GmreJzlOMMqzFVimyijCc4qa2RsmgI5De7E/Q9sXR305+df8+U75t/1zv6WLfIstni2rg1evv+BtNQTiJJTfuLEuZ+xlI/sYvAxhQqwzw656Tm/g1t++tDC+kZvde30fb+44BM3rr778Oxll5767vfE01vfOPPUoSFr6J29JsLDvnSDfjiBFE+RDVoxLAZDsMEAzMZG7GB2sKUkAhip1aNDa/tlyKzAHIagU2IBs1X54ZpFwSjJT13k8bNYQrX9pSFderhQOWAMYaB+eCQq6NTC/GcEwgiGw6kMCoYTscjue/zU1uMQ2inaxQrkNLiNV/7b29jora2tPH1o9a/PLnzgfWd+9ZuVPz0tHkl0djbvoadBNhKG8OCIgBMeIDFlDTsbtNWJXKC1JI4tGImSRwoYsNJEYEOdSOSk06FW5UfZWVDBqYZGiW0BcCpzLc/gdAwl1+wypVXpsyLt6vwibXhpFBYCHiccGZUKeGsE6xeAzS62TWGnFIlEzrCI3Bbg5HKmOIwqkNPgZnbs7P3jX73BYO7yfbNvvPTML38tV3Bzb7t8+eHf99bXZ3bujGYsmLQnAJCgU08PMMMaQc50kuCJ1MNtj7gQpicKrkjC1W95rI2a4YRhsxc5kRQAGMrsDJEuxQjGIqNlEGTiMovCLVvEDoZH8ClTWCZWIVGSCH6QBLP7MOCtobGJYBtIO+/vwW1+x/7ekZ/3ZmY2XXfNqXvuXXnq0NwV+zZde83yHx6Xi7jN+9/eoLD29AQPjc0NQO2HQwhRido271A2eCQKBatdkXmoMkYADu6CLt8uvKiSYHgR2PdXDPcJizy6a046Z1gUG/QroT0nQRidIQVyPmTYKu9Jt2/fWFl55dbblx/948bJk/K8dOvtvdXVM9t3yGwoUZYvcu6DU45TTob+ZCUfdZAtHrYe7rpKAS2MCLNgUmARBmfKZ4MnZZkAW9qg0wJgR5CRKYQHDQTCUJi/HAcQZIs4hVAeFUki/N2dynmLuumSixcPfPrEnd/e9OK/z/4yrt+X54319TOv27X4mU/KbEwuZ+9154IBisSmKtIJ18CgU6YQK7aGBxOpE+AIEhiHUAuIBNq8IFG8xvoAyyYhOkSsU4ANL7I1ERgsf1FIqV85AYtwOtmDIf4yQeiHi8dxAizkzjIdpAAQrjbwKMw3gNFEDqc6EaWzQaRmBDLRUCpIlBg19bCym87s3l0k0Znn/7P020flE9X14ycGFy4uXLFvy3uvWrgo6xdwRTmq+J2j4AyrMAdjm+YPJu2kk0p2clvHtKicKzgtdeHi1y589Pqe/PDB1yTPABVopQL5Da6VyzFF6XsEOPQKH8O6DGltfFABKtBWBbrb4ETxhpqa3csRpLDppsGmpNOwy6NaY86nqKOqjXmoABWgApUUYIOrJB+DqQAVaLMCZW9Rjxxpc/WsjQpQASoQUaCswfGuWhHxOEUFqEC7FeBb1HbvD6ujAlSgggJscBXEYygVoALtVoANrt37w+qoABWooEDZ7+CKqXnTmWJtOEMFqEArFMj8LqrcdOb4V7+xdWNO/gDcue/bD/on+ivbP3fLtquubsXKWAQVoAJTr0DOW9RKN50Zr+Kj/2aVZNSf8S68zdnTN6W1SiYuQeu34FpWZAnbvNHjqC2nwVW66YyzGc5wHBKczZlYhsDwk1KqgOWLR/qTgm8Ug8rVaDRXOrkUIw99To9qFNlQMULbnsPQqIBtIs/5HVz9N51pkyIlteCbknpeS9Atm0bxLalLNUxXsm31V5exeyuqrkmtDDkNrv6bzsgRx8NuedAPJ5D2FeLYoBXD4jEEGwzAbGzcRmwRLTiDSJmFP45EGYCJB7HIXuREOAyJ9bMHnUHOIiTAtk4kzTCwRocQfuF0pmyWIpjjxxBGhFP4AYvnAkwN5YTTpoDTWU7Qb522ANpGgZwG18hNZ7Cjsm32BNjt17rhAdKs57xpZ4O2OpELtOcp0ixLLhER2iASIWpoziKkzDoFCxJOjZXnonAFKwzrBdjO+k6dRXYLgBMFJBoSaJNGooIpUEMk0E6BBIbMwgYbDBvr2xYmtj6sUzw6RAo1FAnnuUjzD6YcQyHKaROJzUeBAjkNrpGbzti9R61BZ8XtDHIiY6mB7JYHzvRwiwQVDJkNcloAGILOjHDLAxuGpIMtBvitEyVZsHX6tlIJG3h8TMSjZaTEBjFwioEVRdKlTFXkQUk2V0VOSzVldk6Dk9vKvPjQowtHj8pNZ+RGM3InLbnpzMpjT5696cyOnTtqvOmMvxmy0zgBpbsOAEJ8wmE9SiXMtpJ0/iaQwSWkJwqGj9gp1Vo9E7NjjbrRGCaGNwRroowmOBtafstocz5F1ZvOyC1mzv8nONx05sCnSm46M9T69eAGQ4JTjlOOhf4EGao4nQPn5I0wjwyZnihSrTMFThgOwA4FkwhzxLQkiXY2AyqEkZjRwpxYZ2iR2XaEMzKVna5DgTlXcLL8LW9989yXvujcdGZHyk1n5CzaLYkcTUUCrEgnXHci6JQpxIqt4YoPPgNcikS4hAhYsyM8kmsESC2+KFFKkVidYzicmsjBDDvUevQ5TojKLRhOyRsPDxYWWRGYI7QarqktXmwMI4UBo0ZpIuCVM5g9uMzpdmZ+k2ECRJMDYQ+NM5yABUxHidyX6djnca0y5y3quGplXipABajAUApkvkUdKsd4wLiG1/T2am48BTFrSAHuS0gV+upSoLsNThTii6euY0IeKjCZCvAt6mTuG6umAlQgQQE2uASRCKECVGAyFWCDO79vN9x00/nB/y3x+E4HY4dDgRGYF4VwGlSAChQp0OnfwQ3zXxCky/zw7ruLZGrUL3kTs6MVolR4UCGm4KFBBaZWgU43uMq72qpmYZsgbKdCv99V1oAEVGCCFehKg5OLNX3oJ6cYwoh+oop+gZ1Ep7AdBE6BFfl9BoA1XAOtrQDxWE5x+hiQBw2fIQijkwpMjwJdaXDoX/q2FG0O/iG31LYhJxRTjiEwbUlq2G6lrUc8CtBnC3BSZAyROiOWIVSgqwp0pcHhSq3hjUrvSsGOgx6XwlOEEebgVNDZsB6kpwKtVqATDU6v2lTnUXW60l0NthvtTcHeV0qogGB3q0KYmJcwKjCJCnTrv4mMtbs5XcYZyuGAR3of7MihEYwDk2GwbwpJkT/Czykq0HkFOnEFJ79oK2pt8A/5yzh0FjUi7QPdCoYcGrVBgmNkeSLdCnhrKBs4QQWPBdOmAlRAFOjun0sacnuHbTdD0pfAx5u9pDhOU4GJVaATV3C56q+tr3/k5pslGldDyjSya6La884MBt+/665cPRhHBbqmAK/gzu/ouC6jxpX3/MppUYGOKsAG19GN5bKoABXo9br1KSp3lApQASpgFCj7HdyRIwZMkwpQASowSQqUNbi9eydpNayVClABKmAU4FtUIwZNKkAFuqUAG1y39pOroQJUwCjABmfEoEkFqEC3FGCD69Z+cjVUgAoYBdjgjBg0qQAV6JYClRrc34+uP/Hc2vLqRrc04WqoABXoiAL5DW5lbeMrPzv9hR+c+ukTK6dX2OM6ciC4DCrQJQXyG9zsTP+2D21+/baZew6e+c7B5VeX2eO6dDC4FirQBQXyG1y/17toa/+OD2/ae8nMfU8uf+vB0ydPs8d14UxwDVSgMwrkNziRYDDoXbw4uPGq+bX13oN/Xn3myHpndOFCqAAV6IAClRrc+nrv+RPr9z6yPDPovf8ts3t3VWLrgJpcAhWgAq1SoOy7qMXFytvRF17euO1Hp/95bO26K+c/9p75zfPytpUPKkAFqEBbFMhvcKtrG3f8+FXpbh+/euHaK+c2zbG7tWVTWQcVoAKqQH6Dm5vpf/7aTUeXNva9YTA/y+7GE0UFqEDrFMhvcLKU3TsHu3e2bkksiApQASqgCvBjAZ4EKkAFOqsAG1xnt5YLowJUgA2OZ4AKUIHOKsAG19mt5cKoABVgg+MZoAJUoLMKsMF1dmu5MCpABdjgeAaoABXorAL/A34nnuxcLxEVAAAAAElFTkSuQmCC)

**Comment by leftstick** [comment]
那截图你network里发出的请求的url具体是什么

**Comment by Clickus** [comment]
2个 
http://172.16.10.15:8888  (是我本机工程启动的 ip:端口)

http://172.16.10.15:8888/dev-server/info?t=1588760252639     返回===》
{"websocket":true,"origins":["*:*"],"cookie_needed":false,"entropy":1995270665}

**Comment by leftstick** [comment]
no，不是这些。
是那个有关jquery的请求，浏览器一定会发出请求的，只是路径不存在，所以devserver返回了html的内容，导致作为js解析失败。

所以核心问题就是，发出的请求的url到底是什么？

**Comment by Clickus** [comment]
发出的请求就只有这2个

**Comment by aixfox** [comment]
public 目录会被 copy，使用 /jquery.js 就好了，和 config.publicPath 配置无关。
你可以看请求回来的 html 是什么，还有你的截图里面那个筛选的漏斗是红色的说明有筛选条件（我猜是 Doc），所以没看到 jquery.js 的那条请求。
还有…这个时候看请求就别把 preserve log 给勾上了。

**Comment by Clickus** [comment]
浏览器network 请求 
![avatar](http://106.13.26.17:8989/ERR0509.png)

**Comment by leftstick** [comment]
目前来看，你的代码没问题。请求路径是正确的，但返回的内容却不是`jquery.nestable.js`，从`response header`得知，返回的是html的内容。

这个只能提供可复现demo了。

**Comment by Clickus** [comment]
### 我使用官方工具创建|初始化了一个项目
你看这个地址行不
https://github.com/Clickus/test_umi_import_local.git

**Comment by leftstick** [comment]
试了你给的repo，不能复现问题。文件`jquery.nestable.js` 加载正常

![Screen Shot 2020-05-11 at 12 32 26](https://user-images.githubusercontent.com/1059956/81524377-80da2400-9383-11ea-9604-b0def4de3479.png)

![Screen Shot 2020-05-11 at 12 32 32](https://user-images.githubusercontent.com/1059956/81524380-86376e80-9383-11ea-8a54-0fe87aed3adb.png)

**Comment by Clickus** [comment]
我的也是用的同一份代码  这个会不会跟 操作系统有关 我的是win10
![avatar](http://106.13.26.17:8989/eee.png)

**Comment by leftstick** [comment]
有可能，不过没有windows机器，没法确认

**Comment by Clickus** [comment]
等会儿  我再另外找台windows和mac 测试下。

如果说跟操作系统有关 那这个可以修复吗 @leftstick

**Comment by Clickus** [comment]
## 测试了不同系统
mac 系统正常
windows 系统不正常

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/81767074-1a334280-950a-11ea-9d7e-4e278ad1a35d.png)

ThinkPad T470P-window10 正常

**Comment by Clickus** [comment]
请问  控制台有报错不  @xiaohuoni

**Comment by xiaohuoni** [comment]
@Clickus 没有的
