### ISSUE TITLE
umi2中config.ts的block配置项，在umi3下怎么配置

### ISSUE THREAD

**Issue by guccihuiyuan** [umijs/umi#4610]
在Umi3下的config.ts中进行如下配置，会提示报错 Invalid config key: block，我看umi的block类型变成了number类型，那如果要配置closeFastGithub，应该怎么写呢？
block: {
    closeFastGithub: true
},

**Comment by xiaohuoni** [comment]
@chenshuai2144  cc

**Comment by sunsmeil** [comment]
同求

**Comment by sorrycc** [comment]
umi ui 已不推荐使用，请使用其他方式添加模版代码。
