### ISSUE TITLE
Typescript 的编译有问题 TypeError: xx is not a function

### ISSUE THREAD

**Issue by chenos** [umijs/umi#4620]
代码见：https://github.com/chenos/demo/blob/master/src/pages/index.tsx#L19

```ts
class Parent extends React.Component {
  fun1() {

  }
}

class Demo extends Parent {
  fun1: Function;

  constructor(props:any) {
    super(props);
    this.state = {};
  }

  componentDidMount() {
    this.fun1() // 这里会报错，TypeError: xx is not a function
  }

  render() {
    return <div>aaa</div>
  }
}
```

编译之后：

```js
class Parent extends react__WEBPACK_IMPORTED_MODULE_0___default.a.Component {
  fun1() {}
}

class Demo extends Parent {
  constructor() {
    super(...arguments);
    this.fun1 = void 0; // 原因是这里初始化了，strictPropertyInitialization: false 试过了，不行
  }
}
```

跟这篇文章提到的是一个问题：

https://dev.to/vire/caveats-of-processing-typescript-code-with-babel-423p

babel-preset-umi 调了半天，没解决，求助 @sorrycc

**Comment by chenos** [comment]
```ts
class A {
  fun1() {

  }
}

class B extends A {
  fun1: () => void;
}

let b = new B;
b.fun1();
```

提炼了下，这里的 fun1 也会出问题，因为编译之后会初始化

```js
class A {
  fun1() {}

}

class B extends A {
  constructor() {
    super(...arguments);
    this.fun1 = void 0;
  }

}
```

https://babeljs.io/repl 编译结果是符合预期的

```js
class A {
  fun1() {}

}

class B extends A {}  // 移除了  fun1: () => void;
```

**Comment by chenos** [comment]
找到原因，是这个插件引起的
https://babeljs.io/docs/en/babel-plugin-proposal-class-properties

使用了这个插件之后，类型声明的属性会被初始化为 `void 0`，如果属性是父类继承的，这个声明会导致父类的属性或方法被重置，导致报错。

如果可以改代码，有个 allowdeclarefields 参数可以设置，属性前加 declare 的编译之后，纯类型声明的属性会被删除。

https://babeljs.io/docs/en/babel-preset-typescript#allowdeclarefields
https://babeljs.io/docs/en/babel-plugin-transform-typescript#allowdeclarefields

```ts
class A {
  declare foo: string; // Removed
  bar: string; // Initialized to undefined
}
```

但是旧代码有很多写法不规范的，都 declare 处理非常麻烦。找了一圈之后，终于发现有个插件可以解决这个问题

https://www.npmjs.com/package/babel-plugin-fix-class-properties-uninitialized

**Comment by xiaohuoni** [comment]
@chenos 👍
