### ISSUE TITLE
ssr可以配置引入的某个组件不进行渲染吗

### ISSUE THREAD

**Issue by 515445681** [umijs/umi#4621]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by ycjcl868** [comment]
- 可以使用 React 的 Suspense，延迟加载
- 控制 state，在 useEffect 时渲染
