### ISSUE TITLE
[Feature Request] Enable DynamicImport by default

### ISSUE THREAD

**Issue by Kol96** [umijs/umi#4623]
## Background

umi2.x，想使用webpack的DynamicImport功能，但不开启umi的路由切割，默认disableDynamicImport为true，外部配置无法覆盖这个属性，现在只能写一个umi插件修改属性值

## Proposal

默认开启dynamicImport，disableDynamicImport: false
[代码位置](https://github.com/umijs/umi/blob/2.x/packages/umi-build-dev/src/plugins/afwebpack-config/index.js#L145)

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
