### ISSUE TITLE
[Feature Request] access权限无法通过refresh刷新

### ISSUE THREAD

**Issue by saltovo** [umijs/umi#4627]
access通过initialState拿到当前权限，getInitialState方法是登录过后通过上传至localStorage获得的，但是项目初始化时未登录localStorage为空，登录过后使用refresh方法无法刷新access,请问有什么解决方法吗

**Comment by leftstick** [comment]
试试用这个[脚手架](https://dfocusgroup.github.io/generator-umi/)，创建一个项目。和你写的对比一下。哪里不同

**Comment by xiaohuoni** [comment]
插件版本需要更新到最新，应该已经修复了这个问题。
