### ISSUE TITLE
切换路由会白屏一闪而过

### ISSUE THREAD

**Issue by pengxingwang** [umijs/umi#4628]
## What happens?

第一次切换到某个路由下（没有缓存的情况下），切换路由会白屏一闪而过(浏览器上毫秒级，内嵌到安卓应用中就很明显)。单页应用切路由应该不会出现这种问题吧，不知道umi是否有针对这个的配置项？

## 相关环境信息

- **Umi 版本**：2.9.0
- **Node 版本**：12.16.0
- **操作系统**：mac

**Comment by xiaohuoni** [comment]
页面按需加载的吧，都会这样，关掉按需加载。就首屏启动较慢

**Comment by pengxingwang** [comment]
@xiaohuoni 
没有按需加载

**Comment by taoWcode** [comment]
我预计在浏览器端，双端节点对比失败，导致组件重新渲染，也就是只有当服务端和浏览器端渲染的组件具有相同的props 和 DOM 结构的时候，组件才能只渲染一次。

**Comment by xiaohuoni** [comment]
提供复现demo
