### ISSUE TITLE
自定义字体不能正常使用

### ISSUE THREAD

**Issue by lisf** [umijs/umi#4631]
首先，字体路径，字体文件都没问题，因为在umi2是可以正常使用的
字体定义：
![image](https://user-images.githubusercontent.com/17263888/81469947-a4ce2600-921a-11ea-9322-34191ac1ba2c.png)
global.less和index.less都引用了自定义字体，报错信息：
![image](https://user-images.githubusercontent.com/17263888/81469969-c29b8b00-921a-11ea-8dfc-c10dd062e7fc.png)

**Comment by lisf** [comment]
Module build failed (from ./node_modules/**mini-css-extract-plugin**/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character ' ' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

官方文档中找到一个问题点：
dev 模式下 css 会被打到 js 里，而不是以单独的 css 文件出现，因为 mini-css-extract-plugin 和 webpack@5 的物理缓存有冲突

判断下是不是这个问题导致的？？？？

**Comment by zhangyuxiang1226** [comment]
我也遇到同样的问题，有办法解决吗，是否要配置file-loader?

**Comment by lisf** [comment]
已经有人给出解决方法[https://github.com/umijs/umi/issues/1802#issuecomment-667031371](url)
