### ISSUE TITLE
安装并使用umi-plugin-antd-theme这个插件每次打包编译都很慢，有什么好的解决办法吗

### ISSUE THREAD

**Issue by xiaoshuoyiyi** [umijs/umi#4632]
## umi-plugin-antd-theme插件问题

我使用了动态主题功能，安装并使用umi-plugin-antd-theme这个插件，但是这样每次打包编译时都很慢，很影响测试，有什么好的解决办法吗？

## 相关环境信息

- **Umi 版本**：^3.0.14
- **Node 版本**：12.14.0
- **操作系统**：MacOS

**Comment by chj-damon** [comment]
确实是这样，因为开发时每次修改都会重新去buildcss。它好像没法判断less文件是否有改动。

**Comment by xiaohuoni** [comment]
这还是一个不太成熟的尝试方案。建议你开发的时候先关掉它。编译再打开。

**Comment by xiaoshuoyiyi** [comment]
> 这还是一个不太成熟的尝试方案。建议你开发的时候先关掉它。编译再打开。
好的，目前也是用的这种方案

**Comment by chj-damon** [comment]
> 这还是一个不太成熟的尝试方案。建议你开发的时候先关掉它。编译再打开。

现在可以配置吗？它以umi-plugin开头，会自动被umi识别为插件，所以我们不会在plugins里面去配置
