### ISSUE TITLE
开启 FORK_TS_CHECKER 时 umi build 报缺少 .umi 目录的错误

### ISSUE THREAD

**Issue by mancoxu** [umijs/umi#4633]
执行 `yarn build ` 报错
## 本地复现 
  1. 把 .umi 文件删除
  2. 执行 `yarn build`
![image](https://user-images.githubusercontent.com/15724205/81470879-d695bb80-921f-11ea-9228-e07f2f6cae32.png)

## 线上复现
  1. 因 .umi 文件写进了 `.gitignore`，线上 `build ` 缺少 `.umi`，导致报错, 报错与上图一样

- **Umi Version**: 3.1.3
- **Node Version**: v12.14.0
- **Platform**:  macOS 10.15.4 (19E266)

**Comment by xiaohuoni** [comment]
应该不是这个问题，我本地多个项目重试，都没有这个问题。
你可以提供一个重现，或者试试其他的项目，有没有同样的问题。
这里提供我重试的项目中的一个 https://github.com/ant-design/start

**Comment by mancoxu** [comment]
> 应该不是这个问题，我本地多个项目重试，都没有这个问题。
> 你可以提供一个重现，或者试试其他的项目，有没有同样的问题。
> 这里提供我重试的项目中的一个 https://github.com/ant-design/start

复现项目地址： https://github.com/mancoxu/reproduce-umi
步骤：
     1. 删除 `src/.umi`
     2. `yarn build`

正常来说在执行 `yarn build ` 的时候也生成了 `.umi`文件夹，不应该报错，根本问题是啥我还没去研究 

**目前我的的解决办法是，在 build 之前执行下 `umi generate tmp`**

**Comment by ycjcl868** [comment]
umi build 会帮助生成 `.umi-production`，`.umi` 这里只用在  dev 开发环境

**Comment by xiaohuoni** [comment]
build 的时候 应该是
```
 "@@/*": ["src/.umi-production/*"]
```

**Comment by xiaohuoni** [comment]
感觉 tsconfig 中的 path 配置，应该由 umi 接管才对
```
"paths": {
            "@/*": ["src/*"],
            "@@/*": ["src/.umi-production/*"]
        }
```

**Comment by xiaohuoni** [comment]
@sorrycc 这个要看一下，不然 build 的时候，用的都是 dev 时的产物，很容易出错。

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
