### ISSUE TITLE
when a package require the same version of core-js with @umijs/babel-plugin-lock-core-js-3,there will be a problems.

### ISSUE THREAD

**Issue by Trendymen** [umijs/umi#4635]
## What happens?
when a package depends the same version of core-js with @umijs/babel-plugin-lock-core-js-3,there will be a problems.

Like  "prettier-eslint": "9.0.1",it need  core-js 3.6.5 ,then core-js 3.6.5 will be installed in ${projectDir}/node_modules,then there will be a error, beacause @umijs/babel-plugin-lock-core-js-3 change the required path that inclues core-js to the @umijs/babel-plugin-lock-core-js-3/node_modules/core-js but there are nothing.

当有另一个包与@umijs/babel-plugin-lock-core-js-3依赖于同一个版本的core-js
，开启本地服务会报错。

比如prettier-eslint 9.0.1版本也依赖core-js 3.6.5,安装项目依赖时,core-js将被安装在项目的node_modules下，这时候@umijs/babel-plugin-lock-core-js-3将所有导入core-js的路径全部
替换成自己的node_modules下面的core-js，但这时候是在这个路径没有这个包的。

复现链接是用ant-design-pro脚手架搭的初始项目。
![image](https://user-images.githubusercontent.com/35187547/81479073-acf68780-9253-11ea-840d-311d10918073.png)

## Mini Showcase Repository(REQUIRED)

[https://github.com/Trendymen/antd-pro-issue](https://github.com/Trendymen/antd-pro-issue)

## How To Reproduce

**Steps to reproduce the behavior:** 
```bash
yarn 
yarn run start
```

**Expected behavior**  
webpack devServer start successfully 

## Context

- **Umi Version**: 3.1.4
- **Node Version**: v13.13.0
- **Platform**: windows10  64 bit

**Comment by aixfox** [comment]
你要把 lock 文件传上来。

用 Windows/WSL 和 npm/yarn 4种情况试了一下，没有复现。

@umijs/babel-plugin-lock-core-js-3 使用的是 `require.resolve('core-js/package.json')`，应该没有问题吧。

**Comment by Trendymen** [comment]
抱歉，因为删掉项目了，我本地也没lock文件了,我直接clone了一下也没复习。然后我把lock node_modules都删掉,把package.json中对prettier-eslint和prettier-eslint-cli的依赖也删掉，然后安装依赖，yarn start，这时没问题。然后把那两个依赖加回来,再重新安装依赖，再yarn start就会出现模块找不到的报错了。
但是我再把包含lock的项目push到github上来，再重新clone，又无法复现了。

**Comment by shadowdreamer** [comment]
我好像复现了，删掉node_modules和lock再装还是出现
[yarn.zip](https://github.com/umijs/umi/files/4614434/yarn.zip)

**Comment by scyang-sss** [comment]
复现的办法是使用yarn，如果有一个包的依赖有core-js 3.6.5  然后在umi之前安装，@umijs/babel-plugin-lock-core-js-3里面的core-js就不会安装，因此umi强制指向@umijs/babel-plugin-lock-core-js-3的node_modules下的core-js就会找不到文件。解决办法就是把另外的库的core-js版本号改成非3.6.5版本（必须跟@umijs/babel-plugin-lock-core-js-3的不一样版本）。或者编译前进@umijs/babel-plugin-lock-core-js-3用yarn安装依赖，使node_modules内有core-js。

**Comment by yuyic** [comment]
一样的问题

**Comment by charanjit-singh** [comment]
- Same issue

**Comment by charanjit-singh** [comment]
comes with firebase
