### ISSUE TITLE
[Feature Request] umi3 扩展路由属性支持类的静态属性

### ISSUE THREAD

**Issue by taixw2** [umijs/umi#4638]
## Background

umi3 扩展路由属性支持类的静态属性

## Proposal

eg: 
```javascript

export default class Home extends Component {
    static title = "Home Page"
}
```

**Comment by taixw2** [comment]
https://github.com/umijs/umi/pull/4640

**Comment by Miss-violet** [comment]
这个功能的使用场景是什么？
是不是还需要做另外的一些设置才能让代码层通过导出静态属性的方式扩展路由的 title 属性在浏览器页面标题中展示出来？
以下截图是我在 src/Detail/index.jsx 的代码里设置了 Detail.title='Detail2'：
`import React from 'react';

const Detail = props => {
  return (
    <div>
      <h1>Page detail</h1>
    </div>
  );
};

Detail.title = 'Detail2';

export default Detail;`
在路由设置了 { path: '/detail', component: './Detail', title: 'Detail' }：
`export default [
  { path: '/', redirect: '/index', title: 'App' },
  { path: '/index', component: './Index', title: 'Index' },
  { path: '/detail', component: './Detail', title: 'Detail' },
];`
最后发现打印在浏览器页面标题上的是路由上的设置
![Uploading image.png…]()
