### ISSUE TITLE
ts中 使用useHistory，希望 history 能支持 query参数 的声明

### ISSUE THREAD

**Issue by huey-LS** [umijs/umi#4639]
## What happens?

![image](https://user-images.githubusercontent.com/5868138/81520199-33a38580-9376-11ea-832f-1acc281dcc71.png)
![image](https://user-images.githubusercontent.com/5868138/81520203-37370c80-9376-11ea-829a-31933aed3de7.png)
文档中说支持 history.push时使用 query (实际效果也正确)，但是 ts的类型检测不支持会报错，希望能支持一下

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

1. 使用 ts
2. 组件中使用 useHistory 并history.push({ pathname: 'xx', query: { xxx} })
3. 出现ts 报错

## 相关环境信息

- **Umi 版本**：
![image](https://user-images.githubusercontent.com/5868138/81520566-47032080-9377-11ea-852a-ae88c6b7f38a.png)

- **Node 版本**：
![image](https://user-images.githubusercontent.com/5868138/81520585-56826980-9377-11ea-8728-f0be6b0d48eb.png)

- **操作系统**：
mac 10.15.4

**Comment by huey-LS** [comment]
https://github.com/umijs/umi/commit/7b681c56a659ac67d91976b6b381786917cd0aca 
看到这里修复了... 晚了一波，感觉可以关了

**Comment by ghyaccount** [comment]
> [7b681c5](https://github.com/umijs/umi/commit/7b681c56a659ac67d91976b6b381786917cd0aca)
> 看到这里修复了... 晚了一波，感觉可以关了

没有修复啊，我用的也是最新版本
