### ISSUE TITLE
Webstorm 在import时无法智能提示history、withRouter变量

### ISSUE THREAD

**Issue by se1phine** [umijs/umi#4645]
## What happens?
Webstorm 在import时无法智能提示history、withRouter变量
![image](https://user-images.githubusercontent.com/11831722/81529337-3fe90c00-9391-11ea-87bb-853d605406d2.png)

怀疑是 Webstorm 无法自动索引到 @umijs/runtime
修改node_modules/umi/lib/cjs.d.ts:
``` diff
import * as utils from '@umijs/utils';
import { Service } from './ServiceWithBuiltIn';
import { defineConfig } from './defineConfig';
export * from '@umijs/types';
export * from '@umijs/runtime'; // 这里已经引用了 withRouter
+ export { withRouter } from 'react-router-dom';
export { utils };
export { Service };
export { defineConfig };
```
可以提示 withRouter 了，但其实 withRouter 已经在 @umijs/runtime 中引用过了
![image](https://user-images.githubusercontent.com/11831722/81530367-4ed0be00-9393-11ea-90fc-4f82010b1499.png)
没有想到原因，是我 Webstorm 的版本问题么

## 相关环境信息

- **Umi 版本**：3.1.4
- **Node 版本**：12.14.0
- **操作系统**：win10
- **Webstorm**:  WebStorm 2020.1.1 Build #WS-201.7223.93, built on April 30, 2020

**Comment by se1phine** [comment]
node_modules/umi/types.d.ts 中 @@/core/umiExports 没有索引到，使用手动 webpack 配置 alias，但似乎 webstorm 并不会在 node_modules/umi/types.d.ts 中使用 @@ 别名

webpack.config.js
```
module.exports = {
  resolve: {
    alias: {
      '@': require('path').resolve(__dirname, 'src'),
      "@@": require('path').resolve(__dirname, 'src/.umi'),
    },
  },
};
```
history 提示成功
![image](https://user-images.githubusercontent.com/11831722/81532066-652c4900-9396-11ea-8761-1a8b5af361f4.png)

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/4384 相同的问题

**Comment by lzbabd** [comment]
https://youtrack.jetbrains.com/issue/WEB-46063 给WS提BUG了, 说是 2020.2 版本修复
![image](https://user-images.githubusercontent.com/15899833/85939886-8d263a80-b94b-11ea-8d4c-28b746ce96df.png)

**Comment by luyinhua** [comment]
> https://youtrack.jetbrains.com/issue/WEB-46063 给WS提BUG了, 说是 2020.2 版本修复
> ![image](https://user-images.githubusercontent.com/15899833/85939886-8d263a80-b94b-11ea-8d4c-28b746ce96df.png)

webstorm 2020.2 has not fixed the bug, have you some any solution to fix the bug.

**Comment by Hnnphone** [comment]
> > https://youtrack.jetbrains.com/issue/WEB-46063 给WS提BUG了, 说是 2020.2 版本修复
> > ![image](https://user-images.githubusercontent.com/15899833/85939886-8d263a80-b94b-11ea-8d4c-28b746ce96df.png)
> 
> webstorm 2020.2 has not fixed the bug, have you some any solution to fix the bug.

这不是 webstorm 的问题，你把 jsconfig.json 改成 tsconfig.json 就好使了。

**Comment by xytech123** [comment]
最近在用umi，也遇到了这个问题，可以在项目的根目录声明文件中扩展一下umi，手动修正无法识别`@@`别名的问题，在`typings.d.ts`中增加以下代码：
``` javascript
import 'umi';
declare module 'umi' {
  export * from 'src/.umi/core/umiExports';
}
```
