### ISSUE TITLE
yarn global add umi失败 error http://registry.npm.taobao.org/capture-stack-trace/download/capture-stack-trace-1.0.1.tgz

### ISSUE THREAD

**Issue by deineryao** [umijs/umi#4647]
## What happens?
执行 yarn global add umi 报错

error http://registry.npm.taobao.org/capture-stack-trace/download/capture-stack-trace-1.0.1.tgz: Integrity check failed for "capture-stack-trace" (computed integrity doesn't match our records, got "sha512-xxxxxxxxxxx")
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

## 相关环境信息

- **Umi 版本**：未安装成功
- **Node 版本**：12.16.3
- **操作系统**：Mac
-**Yarn版本**： 1.22.4

**Comment by xiaohuoni** [comment]
网络问题，请重试。

**Comment by JoshOY** [comment]
Same issue here.
Resolved by cleaning up my yarn (version 1.22.0) global directory `$HOME/.config/yarn/global`.
