### ISSUE TITLE
update umi to 1.3.0 umi dev  not work 

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#465]
```js
"start": "umi dev",
```
```base 
$ npm start
//or
$npm build
```
![_20180515142512](https://user-images.githubusercontent.com/11746742/40040216-e6007bb0-584b-11e8-90df-2af7b491c7b9.png)
一直卡在这里。

```base
rm -rf node_modules 然后重新安装依赖
```
一样的问题。
根据
> 新增 TS_CONFIG_PATHS_PLUGIN 环境变量，遇到启动卡很久的用户可以把这个值配为 none 试试，#369

重新设置
```js
"start": "cross-env TS_CONFIG_PATHS_PLUGIN=none umi dev",
```
```base 
$ npm start
```
![_20180515142448](https://user-images.githubusercontent.com/11746742/40040485-02f0b48c-584d-11e8-9dd0-11d618a215d9.png)

问题没有修复

**Comment by dengnan123** [comment]
您好 最后怎么解决的呢

**Comment by xiaohuoni** [comment]
Bug修复
