### ISSUE TITLE
如何设置相对打包路径？

### ISSUE THREAD

**Issue by Smi1e96** [umijs/umi#4651]
## What happens?

jenkins 打包项目 路径使用绝对路径 
![image](https://user-images.githubusercontent.com/31199247/81630149-6a8da000-9437-11ea-8ca7-9e09a0468885.png)

## Mini Showcase Repository(REQUIRED)

> umi3.0版本都会这样

## How To Reproduce
这行代码影响的路径
https://github.com/umijs/umi/blob/b3d0ef543a8cf56960f79a12d5f2f1ef9a15e178/packages/core/src/Route/routesToJSON.ts#L31

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
尝试修复下，提个 PR？

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
