### ISSUE TITLE
umi3使用patchRoutes添加路由后document.ejs编译报警

### ISSUE THREAD

**Issue by Leon-JiangLe** [umijs/umi#4653]
## What happens?
RT,具体错误信息如下
` WARNING  Compiled with 1 warnings`
` warning  in ./src/pages/document.ejs`
`Module parse failed: Unexpected token (1:0)`
`You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders`
`> <!DOCTYPE html>`
`| <html lang="en">`
`|   <head>`
` @ ./src sync ^\.\/pages.*$`
` @ ./src/app.tsx`
` @ ./src/.umi/core/plugin.ts`
` @ ./src/.umi/umi.ts`
` @ multi ./src/.umi/umi.ts`

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

https://github.com/Leon-JiangLe/umi3-runtime-example

## How To Reproduce

直接运行上述示例

## Context

- **Umi Version**: ^3.1.0
- **Node Version**: v12.14.0
- **Platform**: win10

**Comment by xiaohuoni** [comment]
这只是 WARNING 应该不影响你的代码，你的错误是因为 routes 取值错误 https://github.com/Leon-JiangLe/umi3-runtime-example/pull/2
```
WARNING  Compiled with 1 warnings                                                     09:48:20

 warning  in ./src/pages/document.ejs

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!DOCTYPE html>
| <html lang="en">
|   <head>

 @ ./src sync ^\.\/pages.*$
 @ ./src/app.tsx
 @ ./src/.umi/core/plugin.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts
```

**Comment by Leon-JiangLe** [comment]
@xiaohuoni  `感谢回复`

1. 相关PR没有解决问题，目前警告依旧存在。
2. 该警告影响antd pro测试，导致CI Pipeline卡死无法通过。
具体情况如下
`$ yarn test:all`
` yarn run v1.22.0`
` $ node ./tests/run-tests.js`
` Starting development server for e2e tests...`
` npm`
`  WARN lifecycle The node binary used for scripts is /tmp/yarn--1588738715435-0.5083848675012324/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
`
` > ant-design-pro@1.0.0 start /builds/csp/ccs/api-gallery/api-market-statics`
` > umi dev`
` Starting the development server...`
` [BABEL] Note: The code generator has deoptimised the styling of /builds/csp/ccs/api-gallery/api-market-statics/node_modules/@antv/data-set/build/data-set.js as it exceeds the max of 500KB.
`
`  WARNING  Compiled with 1 warnings4:20:02 AM`
`  warning  in ./src/pages/document.ejs`
` Module parse failed: Unexpected token (1:0)`
` You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders`
` > <!DOCTYPE html>`
` | <html lang="en">`
` |   <head>`
`  @ ./src lazy ^\.\/pages.*$ namespace object`
`  @ ./src/app.tsx`
`  @ ./src/.umi/core/plugin.ts`
`  @ ./src/.umi/umi.ts`
`  @ multi ./src/.umi/umi.ts`
`   App running at:`
`   - Local:   http://localhost:8000 (copy to clipboard failed)`
`   - Network: http://172.17.0.2:8000`
(在此处卡住,不再进行下一步的测试操作)

`Pulling docker image gitlab/gitlab-runner-helper:x86_64-003fe500 ...`
` ERROR: Job failed: execution took longer than 1h0m0s seconds`
而后因超时导致流水线失败
完整测试日志
[CI错误日志.txt](https://github.com/umijs/umi/files/4619650/CI.txt)

**Comment by xiaohuoni** [comment]
@Leon-JiangLe 
CI相关的东西，我不太懂，等其他大佬回答你的问题吧

**Comment by yisiqi** [comment]
@xiaohuoni 这个问题看起来跟CI没什么关系。

使用官方的动态路由demo也一样，只要是umi3 + ejs必然会报错。

**Comment by xiaohuoni** [comment]
@ycjcl868 cc，我不知道是什么问题导致的

**Comment by ycjcl868** [comment]
我理解 patchRoutes 与 ejs 关系不大，应该是其它问题，我细看下

**Comment by okilled** [comment]
+1

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.

**Comment by liu-miao-miao** [comment]
+1

**Comment by heartrainy** [comment]
我也有这个问题，我发现是在require(`XXXX`).default 赋值组件的时候才会报的这个警告提示

**Comment by heartrainy** [comment]
> 我也有这个问题，我发现是在require(`@/pages/${XXXX}`).default 赋值组件的时候才会报的这个警告提示, 如果require里的是纯字符串地址就不回报警告了，不知道是什么原因导致的

解决了 需要在require中加.jsx或者.tsx，require(`@/pages/${XXXX}.jsx`).default , 全路径加后缀才不会报错。

**Comment by hanxiaozhang5741** [comment]
如果使用import(`@/pages${XXX}`)这种方式给组件赋值，按照您 @heartrainy 的方法可能不对。您有没有什么解决办法

**Comment by hanxiaozhang5741** [comment]
解决了：写成这种形式暂时可以 import(`@/pages${XXX}/index.tsx`)}

**Comment by meiheng01** [comment]
> 解决了：写成这种形式暂时可以 import(`@/pages${XXX}/index.tsx`)}

是整个项目里的import都要写成这种加后缀的吗

**Comment by Sailde** [comment]
> > 我也有问题，我发现是在要求（`@/pages/${XXXX}`）。默认这个集合的时候会报告这个组件的警告提示，如果是纯字符串地址，则返回警告了，不知道是什么原因导致的
> 
> 解决了需要在require中加.jsx或者.tsx，require( `@/pages/${XXXX}.jsx`).default , 全路径加后缀才不会报错。

感谢您的正确答案，谢谢，。

**Comment by limubai1223** [comment]
请问该问题如何解决，我用了上面的方法写全路径还是报这个错误
![image](https://user-images.githubusercontent.com/48703884/147041887-27e3ff98-ffe2-416c-b950-f5bb828541d2.png)

**Comment by liukai3586** [comment]
> 请问该问题如何解决，我用了上面的方法写全路径还是报这个错误 ![image](https://user-images.githubusercontent.com/48703884/147041887-27e3ff98-ffe2-416c-b950-f5bb828541d2.png)
`require(`./pages${v.component}.tsx`).default `
我是这样写的

**Comment by liukai3586** [comment]
> 请问该问题如何解决，我用了上面的方法写全路径还是报这个错误 ![image](https://user-images.githubusercontent.com/48703884/147041887-27e3ff98-ffe2-416c-b950-f5bb828541d2.png)

require(`./pages${v.component}.tsx`).default 
我是这样写的
