### ISSUE TITLE
.env 文件定义环境变量后 dev 环境下获取不到

### ISSUE THREAD

**Issue by m01i0ng** [umijs/umi#4654]
已在 `.umirc.ts` 文件中定义：
![image](https://user-images.githubusercontent.com/19723234/81634429-957cf180-9441-11ea-8b2f-905ea264bea5.png)

**Comment by m01i0ng** [comment]
umi 版本 3.1.4

**Comment by lengthmin** [comment]
就可以直接使用 API_URL 这个字段了。

**Comment by TangTangJia** [comment]
> 已在 `.umirc.ts` 文件中定义：
> ![image](https://user-images.githubusercontent.com/19723234/81634429-957cf180-9441-11ea-8b2f-905ea264bea5.png)

请问你解决这个问题了吗

**Comment by m01i0ng** [comment]
> > 已在 `.umirc.ts` 文件中定义：
> > ![image](https://user-images.githubusercontent.com/19723234/81634429-957cf180-9441-11ea-8b2f-905ea264bea5.png)
> 
> 请问你解决这个问题了吗

像楼上说的那样在代码中直接引用这个字段可以获取到、

**Comment by lengthmin** [comment]
解决了就可以关闭了

**Comment by m01i0ng** [comment]
> 解决了就可以关闭了

这种方式 lint 会报错、所以我不知道这算不算是官方的解决方案、

**Comment by leftstick** [comment]
@m01i0ng  代码里引用提示错误的，加`//@ts-ignore`，如下：

```typescript
//@ts-ignore
  console.log('process', REACT_APP_API_URL)
```

**Comment by sorrycc** [comment]
lint 会报错是其他问题，自己定义 lint 规则。
