### ISSUE TITLE
用了最新的umi@3，每次热更新都像是在全量编译，不知道怎么解决

### ISSUE THREAD

**Issue by bibiehy** [umijs/umi#4656]
umi -> 3.1.4
node -> 10.16.3
win7

这是一个新项目，用了umi@3.x，.umirc.ts 文件配置如下

![image](https://user-images.githubusercontent.com/35096473/81637436-e8a67280-9448-11ea-8b43-16721172ee27.png)

改一个样式，或删除一个属性，都会触发热更新，感觉是全量编译了，用时间20几秒，不知道怎么解决，看gif图片，

![GIF](https://user-images.githubusercontent.com/35096473/81635156-15578b80-9443-11ea-951a-cb73472ad62e.gif)

**Comment by dugagjin** [comment]
第一：
```ts
const isProduction = process.env.NODE_ENV === 'production';
```


然后是非关键的地方。

```ts
chainWebpack: isProduction ? (config, { webpack }) => {
        config.merge({ ... })
    } : undefined;
```

**Comment by bibiehy** [comment]
@dugagjin 果然，NB，竟然是这个 chainWebpack，赞！
