### ISSUE TITLE
使用sass编写样式时，嵌套结构在页面解析错误

### ISSUE THREAD

**Issue by lirl-cn** [umijs/umi#4657]
## What happens?
直接创建umi项目后，使用sass编写样式，嵌套结构时页面解析样式错误

![image](https://user-images.githubusercontent.com/23329045/81648408-3cbd5100-9461-11ea-95ec-bd8c15fa0bd2.png)
![image](https://user-images.githubusercontent.com/23329045/81648437-4941a980-9461-11ea-8709-381ef9d69af2.png)

## 相关环境信息

- **Umi 版本**："umi": "^2.9.0",
- **Node 版本**：v13.11.0
- **操作系统**：mac

**Comment by xiaohuoni** [comment]
如何使用的，请给重现 demo ，我们项目中是正常的。
