### ISSUE TITLE
[dva] model 中异步回调函数中无法使用put

### ISSUE THREAD

**Issue by cjl-df** [umijs/umi#4658]
##call and put can not invoke（effects call 和 put方法不能执行相应的reducer）

i use umi with dva ; but in the model effects ,i invoke put and the put is function with params action;then i pass an action ,but doesnot run into the reducer.

## dependencies
```
  "dependencies": {
    "@ant-design/icons": "^4.1.0",
    "antd": "^4.1.5",
    "dva": "^2.6.0-beta.20",
    "react": "^16.8.6",
    "react-contextmenu": "^2.13.0",
    "react-dom": "^16.8.6",
    "react-sticky": "^6.0.3",
    "umi-request": "^1.2.19"
  },
  "devDependencies": {
    "babel-eslint": "^9.0.0",
    "cross-env": "^7.0.2",
    "eslint": "^5.4.0",
    "eslint-config-umi": "^1.4.0",
    "eslint-plugin-flowtype": "^2.50.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.11.1",
    "http-proxy-middleware": "^1.0.3",
    "husky": "^0.14.3",
    "lint-staged": "^7.2.2",
    "react-test-renderer": "^16.7.0",
    "umi": "^2.7.7",
    "umi-plugin-dva": "^1.11.3",
    "umi-plugin-react": "^1.8.4"
  }
```

model file:

```
export default {
  namespace: 'project',
  state: {
    projectList: [
      {
        ProjectName: 'xxxxxxxx',
        PhId: '226200223000002',
      },
    ],
    prejectObj: {},
  },
  reducers: {
    saveList(state) {
      debugger;
      return { ...state, projectList: [] };
    },

    checkedProject(state, { payload }) {
      return { ...state, prejectObj: payload };
    },
  },
  effects: {
    async *fetchProjectList({ payload: pageNum }, { call, put }) {
      // const dataList = await call(queryProList);
      // const dataList = yield call(
      //   () =>
      //     new Promise((resolve, reject) => {
      //       setTimeout(() => {
      //         resolve(projectList);
      //       }, 500);
      //     }),
      // );
      yield call(delay, 1000);
      yield put({ type: 'saveList' });
    },
  },
  // subscriptions: {
  //   setup({ history, dispatch }) {
  //     // 监听 history 变化，当进入 `/` 时触发 `load` action
  //     return history.listen(({ pathname }) => {
  //       if (pathname === '/') {
  //         dispatch({ type: 'load' });
  //       }
  //     });
  //   },
  // },
};

function delay(timeout) {
  return new Promise(resolve => {
    setTimeout(resolve, timeout);
  });
}
```

it's runnint into fetchProjectList,but cannot into saveList reducer
(就是可以进入fetchProjectList这个函数，显示put也是异步的reduce，但是这样调用，不知心saveList ，这是为什么)

what's the matter,can anyone help me ?

**Comment by xiaohuoni** [comment]
我这里是正常的，有重现 demo 吗

**Comment by cjl-df** [comment]
@xiaohuoni 有的，就是直接新建一个npm create umi 项目；然后选择ant-design-pro；在新建models这样写过来

**Comment by xiaohuoni** [comment]
[abc 2.zip](https://github.com/umijs/umi/files/4620179/abc.2.zip)
不能重现，给你一个最简 demo 吧，这个每天都在用，不应该会有问题的。

**Comment by cjl-df** [comment]
@xiaohuoni 找到原因了，effects里面 generatoer函数不能加async；加这个就会导致里面的call和put不能执行；
这个地方怎么处理generator的，源码在哪儿，能不能讲一下

**Comment by xiaohuoni** [comment]
感觉是个bug，先开着吧。

**Comment by cjl-df** [comment]
@xiaohuoni 好的

**Comment by xiaohuoni** [comment]
重新看了，还是没有重现问题，感觉是没有正确 return。有问题再reopen

**Comment by showtan001** [comment]
@xiaohuoni 

![image](https://user-images.githubusercontent.com/32892347/141957168-12991b3f-ddb1-4fd8-a252-f4e6cceba5d1.png)
![image](https://user-images.githubusercontent.com/32892347/141957324-f9e509e2-4ccd-4e37-97e9-d46660ce551b.png)

typescript怎么办，error："yield" 表达式隐式导致 "any" 类型，因为它的包含生成器缺少返回类型批注。

**Comment by hideInEye** [comment]
> @xiaohuoni
> 
> ![图像](https://user-images.githubusercontent.com/32892347/141957168-12991b3f-ddb1-4fd8-a252-f4e6cceba5d1.png) ![图像](https://user-images.githubusercontent.com/32892347/141957324-f9e509e2-4ccd-4e37-97e9-d46660ce551b.png)
> 
> typescript怎么办，错误："yield"表达式隐式导致"any"类型，因为它的包含生成器缺少返回类型批注。
> 
> 网上找到答案了，`只需要对effects中的每一个*进行类型定义即可`

可是在tsconfig中compilerOptions中设置noImplicitAny为true就可以.
