### ISSUE TITLE
outputPath 不支持绝对路径

### ISSUE THREAD

**Issue by mizi-lin** [umijs/umi#4662]
![image](https://user-images.githubusercontent.com/2802841/81667007-58caed80-9475-11ea-885f-60115d0eb49d.png)

路径地址是 `/Users/Mizi/git/demo/umi-issues/dist`
编译时却变成了 `Users/Mizi/git/demo/umi-issues/dist`

umi@v3+
mac

**Comment by ycjcl868** [comment]
不建议相对路径，watch 路径会不准备
