### ISSUE TITLE
自定义环境变量无效了

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#4666]
## What happens?

2.x版本中可以使用自定义环境变量，在package.json中设置环境变量；如:
cross-env REACT_APP_ENV=dev
3.x中，设置后，在app.ts中输出，发现没有
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by xiexingen** [comment]
自己搞错了，需要在.umirc.ts中define再处理一下
比如：'process.env.WETRIAL_ENV': WETRIAL_ENV,

**Comment by daydayuphuan** [comment]
![image](https://user-images.githubusercontent.com/7309887/83322810-3f0b1200-a28d-11ea-85f0-4d0fd35c4509.png)
升级之前还是有用的，升级后无效了，需要在 umirc 里面配置 define  才能生效。
![image](https://user-images.githubusercontent.com/7309887/83322850-711c7400-a28d-11ea-8290-88d8564732b7.png)
为什么？？？

**Comment by citrusjunoss** [comment]
> ![image](https://user-images.githubusercontent.com/7309887/83322810-3f0b1200-a28d-11ea-85f0-4d0fd35c4509.png)
> 升级之前还是有用的，升级后无效了，需要在 umirc 里面配置 define 才能生效。
> ![image](https://user-images.githubusercontent.com/7309887/83322850-711c7400-a28d-11ea-8290-88d8564732b7.png)
> 为什么？？？

环境变量可以通过package.json script 设置，为了跨平台建议使用cross-env 环境

**Comment by BodhiHu** [comment]
同样问题
