### ISSUE TITLE
最新版本的umi，antd的日期组件又都变成英文了

### ISSUE THREAD

**Issue by zhangzhi93** [umijs/umi#4667]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by zhangzhi93** [comment]
moment版本的原因

**Comment by JLoveI** [comment]
又没有解决方案
