### ISSUE TITLE
使用@umijs/plugin-qiankun，主应用可以正常访问子应用，刷新页面后，报错找不到DOM节点，VM5146:76 Uncaught (in promise) Error: Minified React error #200;

### ISSUE THREAD

**Issue by wuth10** [umijs/umi#4669]
主应用和子应用均为antd pro工程，V2版本
@umijs/plugin-qiankun: "^1.3.3"
主应用配置：
    [
    '@umijs/plugin-qiankun',
    {
      master: {
        apps: [
          {
            name: 'bata_serv',
            entry: 'http://IP:PORT/', 
            base: '/cb',
          },
        ],
          jsSandbox: true, // 是否启用 js 沙箱，默认为 false
          prefetch: true, // 是否启用 prefetch 特性，默认为 true
        },
    },
    ]
子应用配置：
['@umijs/plugin-qiankun']
主应用的basicLayout里增加root-subapp的div
<div id="root-subapp"></div>

当通过主应用点击菜单，可以正常访问子应用

![image](https://user-images.githubusercontent.com/43315953/81819494-f865aa00-9561-11ea-95b4-eb79ec726398.png)

但当刷新页面时，便会报错，找不到DOM节点，VM5146:76 Uncaught (in promise) Error: Minified React error #200;Target container is not a DOM element.

![image](https://user-images.githubusercontent.com/43315953/81819447-e8e66100-9561-11ea-9c1b-173e8ca8ed00.png)

清除缓存后再次刷新，便可正常访问
怀疑与缓存、主子应用加载速度有关，烦请协助解决，谢谢。

**Comment by wuth10** [comment]
使用defer:true异步加载配置，解决

**Comment by wsdqr001** [comment]
> 使用defer:true异步加载配置，解决
请问你的umi版本是哪个呀？我用了1.3.3的qiankun还是会报错。
