### ISSUE TITLE
umi@2 中的umi ui 文档链接错误

### ISSUE THREAD

**Issue by NexxLuo** [umijs/umi#4671]
由于umi 3的升级，导致umi ui有所变化，且无具体文档，故依然沿用umi@2中的umi ui，但是之前的文档链接指向了umi3对应的文档地址，且无内容。

是否可在umi2 的文档中修复下umi ui的相关链接。
https://v2.umijs.org/zh/guide/umi-ui.html#%E2%9C%A8-%E7%89%B9%E6%80%A7

**Comment by xiaohuoni** [comment]
umi@3 中应该无法使用 umi@2 的ui。
你要的umi@2 的文档应该是 https://v2.umijs.org/guide/develop-umi-ui-plugin.html#initialization-the-plugin

**Comment by lizeyuan** [comment]
umi3的ui如何使用？

**Comment by jingguangyan** [comment]
> umi@3 中应该无法使用 umi@2 的ui。 你要的umi@2 的文档应该是 https://v2.umijs.org/guide/develop-umi-ui-plugin.html#initialization-the-plugin

这个链接 404 了
