### ISSUE TITLE
模板document.ejs文件中title在页面渲染过程中闪现后消失

### ISSUE THREAD

**Issue by guyuezhai** [umijs/umi#4674]
## What happens?

模板document.ejs文件中title在页面渲染过程中闪现后消失
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：3.x
- **Node 版本**：12.16.1
- **操作系统**：win10
![image](https://user-images.githubusercontent.com/24433701/81917794-3a492b80-9608-11ea-9d6d-10ca00c4368a.png)
![image](https://user-images.githubusercontent.com/24433701/81918483-15a18380-9609-11ea-88e4-6ebb0d3932e1.png)

**Comment by YJY12138** [comment]
我也碰到了这个问题，请问你有解决么？

**Comment by guyuezhai** [comment]
> 我也碰到了这个问题，请问你有解决么？

我们在配置理由时，可以针对路由配置标题即  `title` 属性，示例如下所示：
```js
export default {
  title: 'hi',
  routes: [
    { path: '/', title: 'Home' },
    { path: '/users', title: 'Users' },
    { path: '/foo' },
  ],
};
```
[详情参考文档](https://umijs.org/zh-CN/config#title)

**Comment by YJY12138** [comment]
明白了，谢谢回复。五一快乐。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月30日(星期五) 上午10:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umijs/umi] 模板document.ejs文件中title在页面渲染过程中闪现后消失 (#4674)

**Comment by guyuezhai** [comment]
> 明白了，谢谢回复。五一快乐。------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年4月30日(星期五) 上午10:53 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [umijs/umi] 模板document.ejs文件中title在页面渲染过程中闪现后消失 (#4674)

同乐，假期愉快哈 ！

**Comment by leeumm** [comment]
配置里设置 `title: false`
> 如果需要自行通过 react-helmet 等方式渲染 title，配 title: false 可禁用内置的 title 渲染机制
[官方文档](https://umijs.org/zh-CN/config#title)
