### ISSUE TITLE
嵌套路由生成的router.js没有自动添加Routes

### ISSUE THREAD

**Issue by xlszzck** [umijs/umi#4676]
在使用嵌套路由时，我有以下路径的文件
src\pages\Manage\Gif\Material\_layout.tsx
![bug](https://user-images.githubusercontent.com/21256790/81940881-a9377c00-962a-11ea-9e1e-2a0582978aeb.png)

当我运行项目时，查看src\pages\.umi\router.js，发现该路径并没有像其他目录一样，配置`Routes: [require('../Authorized').default],`
导致我无法“src\pages\Authorized.tsx”中的传递的参数
![bug2](https://user-images.githubusercontent.com/21256790/81941446-6c1fb980-962b-11ea-9e2b-79360bc5ca49.png)

如果手动添加该项，就能正常获取参数

请问是需要另外的设置吗？求解决方案

## 相关环境信息

- **Umi 版本**：2.13.13
- **Node 版本**：v12.16.2
- **操作系统**：win10

**Comment by xlszzck** [comment]
这个问题一直没人帮忙解决啊……

**Comment by xiaohuoni** [comment]
Routes 是授权判断的，layouts 本来就不会生成 Routes。
你是遇到什么问题？

**Comment by xlszzck** [comment]
> Routes 是授权判断的，layouts 本来就不会生成 Routes。
> 你是遇到什么问题？

我就是希望_layout能生成 Routes，这样Authorized.tsx中的权限才会通过props传递过来
