### ISSUE TITLE
umi3抽离config后，配置路由失效

### ISSUE THREAD

**Issue by singhello** [umijs/umi#4677]
将 路由配置 放在 config/config.ts下，仍然使用的是约定式路由，并没有使用配置式路由。
放在 .umirc.ts 下，配置式路由是有效的。

**Comment by chj-damon** [comment]
你是怎么用的？
`
import routeConfig from './routeConfig';
{
	// 其他配置
	...,
	// 路由配置
	routes: routeConfig
}`

**Comment by singhello** [comment]
在 config/config.ts 中直接配置的 routes。这个config/config.ts和.umirc.ts不都是默认的配置文件吗，为啥还要在引入？

**Comment by chj-damon** [comment]
约定式路由是不需要配置routes的

**Comment by chj-damon** [comment]
最好能给一个复现地址。我本地也是在config.ts里面配置的routes，是没问题的

**Comment by xiaohuoni** [comment]
config/config.ts和.umirc.ts二选一，我猜是两个文件都存在了。

**Comment by singhello** [comment]
> 最好能给一个复现地址。我本地也是在config.ts里面配置的routes，是没问题的

我以为.umirc和config.ts是可以共存合并的。删掉.umirc.ts后， config.ts就生效了

**Comment by singhello** [comment]
> config/config.ts和.umirc.ts二选一，我猜是两个文件都存在了。

嗯嗯，原先我两个都有，以为可以合并配置

**Comment by ych800** [comment]
> 将 路由配置 放在 config/config.ts下，仍然使用的是约定式路由，并没有使用配置式路由。
> 放在 .umirc.ts 下，配置式路由是有效的。


> > 最好能给一个复现地址。我本地也是在config.ts里面配置的routes，是没问题的
> 
> 我以为.umirc和config.ts是可以共存合并的。删掉.umirc.ts后， config.ts就生效了
还是不起作用呀~
