### ISSUE TITLE
umijs3.1.4  config merge 后类型错误的问题

### ISSUE THREAD

**Issue by xiaoliang2535** [umijs/umi#4680]
proxy配置agent，请求时会抛出如下问题

TypeError [ERR_INVALID_ARG_TYPE]: The "options.agent" property must be one of type Agent-like Object, undefined, or false. Received type object

proxy没有添加agent时正常代理，配置后出现问题
相同配置2.0版本正常，3.0版本出现问题

## 相关环境信息
- **Umi 版本**："umi": "^3.1.4",
- **Node 版本**：12.4.0
- **操作系统**：OS

**Comment by xiaoliang2535** [comment]
console了一下日志，追到了这里出了问题，ProxyAgent类，被合并成了一个普通的object，以至于后续代理出了问题

![image](https://user-images.githubusercontent.com/5997382/82276851-016ad700-99b9-11ea-99ed-1ff0092818a7.png)

![image](https://user-images.githubusercontent.com/5997382/82277071-8f46c200-99b9-11ea-8d45-59e47f45d0a9.png)

**Comment by swd3823** [comment]
@sorrycc 大佬，请教下这个bug短期内有修复计划吗？

**Comment by sorrycc** [comment]
给个复现，我修下。

**Comment by swd3823** [comment]
## What happens?

umi 3.x版本 config 结合http-proxy-agent 5.x 设置proxy 报错
![image](https://user-images.githubusercontent.com/5397440/86736376-0fa6ac80-c066-11ea-893c-44e6ab744167.png)

## Mini Showcase Repository(REQUIRED)

https://github.com/swd3823/umitest

## How To Reproduce

1. in console: yarn start
2. open http://localhost:8002 in browser
3. click the "trigger request" button to trigger the request
4. the errow will appear in console

## Context

- **Umi Version**: ^3.2.8
- **Node Version**: 12.18.2
- **Platform**: macOS 10.15.5


**@sorrycc 麻烦大佬**

**Comment by feaswcy** [comment]
折腾了两小时，求修复

**Comment by swd3823** [comment]
> 折腾了两小时，求修复

global-agent可替代

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.

**Comment by zhangcong25** [comment]
global-agent怎么处理？

**Comment by zhangcong25** [comment]
这个问题还存在，没人修？

**Comment by dragoncz** [comment]
这个问题在最新的 `3.5.23` 版本中依然存在, 问题应该就出在楼上指出的 `deepMerge()` 方法上, 拷贝后丢失了原有类型: 
https://github.com/umijs/umi/blob/5c86b136b551fdc5327536da5ec223c4e936a998/packages/core/src/Config/Config.ts#L211-L218

想要绕过这个问题, 可以使用 [`global-agent`](https://github.com/gajus/global-agent#readme)

TLDR:
安装`global-agent`:
```bash
yarn add -D global-agent
```
然后在你的`.umirc.js`, 删除相应配置, 再添加:
```javascript
import 'global-agent/bootstrap';
```
Done!
