### ISSUE TITLE
[Feature Request] 在配置式routes里面使用children

### ISSUE THREAD

**Issue by ttshangxiang** [umijs/umi#4682]
想用react-router-dom中Route的children参数，实现类似keep-alive的功能，但是好像不支持？

**Comment by ttshangxiang** [comment]
`
<Route
      path={to}
      children={({ match }) => (
        <li className={match ? "active" : ""}>
          <Link to={to} {...rest} />
        </li>
      )}
    />
`
这种感觉，不管是否匹配，都会显示组件内容

**Comment by see365** [comment]
umi 路由这块封装太死了

**Comment by xiaohuoni** [comment]
可以参考这个插件来试试 https://github.com/alitajs/umi-plugin-keep-alive
