### ISSUE TITLE
无法配置二级路由菜单

### ISSUE THREAD

**Issue by saltovo** [umijs/umi#4684]
umi版本3.1.1，路由配置中使用了二级路由，写在config/route.js中，二级菜单不生效，怀疑在配置中开启了mpa，

**Comment by saltovo** [comment]
一周前的项目相同的路由写法，可以生效，但是2天前就不生效了，无法解决

**Comment by 272269639** [comment]
我也遇到这个问题了

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/4732 相同的问题

**Comment by 17779286189** [comment]
我也是遇到这个问题

**Comment by miss61008596** [comment]
真的是服了，release版本就这个样子，有点工匠精神好么？拿社区当玩具么？

**Comment by ycjcl868** [comment]
Duplicate https://github.com/umijs/umi/issues/5708.
