### ISSUE TITLE
函数式页面中使用model的数据无法获取实时数据

### ISSUE THREAD

**Issue by haoyinag** [umijs/umi#4685]
## 最小可复现仓库
![image](https://user-images.githubusercontent.com/24349947/82107041-50b1cd00-9757-11ea-826e-6779c4ce5178.png)

 
## 复现步骤，错误日志以及相关配置
1、正确使用model
2、在函数式页面中connect/model，调用dispatch；
3、绑定的model数据不更新；
4、通过then也不行，类型报错

![image](https://user-images.githubusercontent.com/24349947/82107077-91a9e180-9757-11ea-96d9-9aecb4120b53.png)

## 相关环境信息
"@amap/amap-jsapi-types": "^0.0.4",
    "@ant-design/pro-layout": "^5.0.9",
    "@ant-design/pro-table": "^2.2.7",
    "@types/jest": "^25.2.1",
    "@types/react": "^16.9.34",
    "@umijs/preset-react": "1.x",
    "@umijs/test": "^3.1.1",
    "antd-dayjs-webpack-plugin": "^1.0.0",
    "cross-env": "^7.0.2",
    "lint-staged": "^10.0.7",
    "postcss-px-to-viewport": "^1.1.1",
    "prettier": "^2.0.5",
    "react": "^16.12.0",
    "react-amap": "^1.2.8",
    "react-dom": "^16.12.0",
    "stylus": "^0.54.7",
    "stylus-loader": "^3.0.2",
    "ts-md5": "^1.2.7",
    "typescript": "^3.8.3",
    "umi": "^3.1.1",
    "yorkie": "^2.0.0"
- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by xiaohuoni** [comment]
为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN
