### ISSUE TITLE
想在devtool中搜索工程中的相关源码，结果一直发现indexing很慢

### ISSUE THREAD

**Issue by minzojian** [umijs/umi#4689]
## 相关环境信息

- **Umi 版本**：umi@3.1.4
- **Node 版本**：node v12
- **操作系统**：win10
![image](https://user-images.githubusercontent.com/361781/82138094-5dfeb280-9850-11ea-9de3-f599b9919087.png)

是不是没有排除node_modules还是真的有这么多代码要检索？

**Comment by xiaohuoni** [comment]
为什么需要在这里搜索？这里和 umi 没关系吧？
