### ISSUE TITLE
keepAlive 方案怎么样了

### ISSUE THREAD

**Issue by lovesL** [umijs/umi#4691]
请问umi 的keepAlive 现在问的了吗？ 我现在急需这个插件

**Comment by xiaohuoni** [comment]
先看看这个，其他没别的进度。https://github.com/umijs/umi/issues/3091

**Comment by xiaohuoni** [comment]
还有这个插件可以试试 https://github.com/alitajs/umi-plugin-keep-alive

**Comment by Nick742037091** [comment]
"@umijs/max": "^4.0.52"
直接在config.js配置keepalive就可以实现页面缓存了

**Comment by nbbjack** [comment]
> "@umijs/max": "^4.0.52" 直接在config.js配置keepalive就可以实现页面缓存了

如果没有其它插件，加上这个配置直接报错的：
node:assert:399
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Invalid config keys: keepalive
