### ISSUE TITLE
^3.2.0-beta.6: Error: Could not find "store" in the context of "Connect(Page)". Either wrap the root component in a

### ISSUE THREAD

**Issue by zuolung** [umijs/umi#4692]
import React from 'react';
import { connect } from 'umi'; //  from umi not found connect; ||  from dva Error like report title; 
import './index.less';
const mapStateToProps = (state) => ({
  data: state,
  loading: state.loading.global
});
@connect(mapStateToProps)
class Page extends React.PureComponent {
  constructor(props) {
    super(props);
    this.state = {}
  }

  render() {
    return (
      <div className="public-homePage">
        "content"
      </div>
    );
  }
}
export default Page;

**Comment by ycjcl868** [comment]
Enable ssr?

**Comment by xiaohuoni** [comment]
为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

**Comment by fanxinjie** [comment]
@zuolung The reason for this problem is that the corresponding Models definition was not found. There may be no corresponding **models** directory in your project, or it may be defined as **model**.
