### ISSUE TITLE
umi3.0 设置 targets: { ie: 9 }  在ie9 仍然会出现兼容问题，有解决办法吗

### ISSUE THREAD

**Issue by congshuang** [umijs/umi#4693]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/4694 相同问题
