### ISSUE TITLE
umi3.0 targets配置IE9 无效

### ISSUE THREAD

**Issue by lambGirl** [umijs/umi#4694]
## What happens?
umi3.0 targets配置IE9 无效， 打开页面空白； umi.js错误。
config/config.js中配置
targets: {
    ie: 9,
 }
在IE9版本下打开，页面空白；console报umi.js错误
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:  umi@3.1.4
- **Node Version**: Node@10.15.3
- **Platform**:  Windows

**Comment by xiaohuoni** [comment]
可以先尝试配置 ie:10 ，应该有效。

**Comment by KMBaby-zyl** [comment]
> 可以先尝试配置 ie:10 ，应该有效。

ie:10 会导致ios9用户不兼容。 umi2的ie9不会

**Comment by z-lionel** [comment]
yarn create @umijs/umi-app 创建项目
配置targets:{ie: 9} 或者10 , 11,
默认界面会显示,但是打印栏报错
SCRIPT1002: 语法错误
devScripts.js (25,5)
plugin-model: Invoking '@@initialState' model failed: TypeError: 对象不支持此操作

**Comment by baggiomygod** [comment]
解决了吗？我也遇到这个问题，各种方法都是了，无效
umi.js (75274,15)
devScripts.js (25,5)

`
targets: {
    ie: 10
  },
`

**Comment by franzpan** [comment]
同样的问题，有解决办法吗?
SCRIPT1002: 语法错误
devScripts.js (25,5)
plugin-model: Invoking '@@initialstate' model failed: TypeError: 对象不支持此操作

**Comment by zhangxiaofeng87** [comment]
我也想问这个问题解决了没有

**Comment by quicklearning123** [comment]
同问

**Comment by zhangxiaofeng87** [comment]
> 同问

3不支持ie9，最低ie11+

**Comment by quicklearning123** [comment]
> > 同问
> 
> umi3内置的antd是4.0不支持ie9，最低ie11+，如果想支持9，需要按照antd v3

@zhangxiaofeng87 IE11也报这个错误

**Comment by chenyuhu** [comment]
> > > 同问
> > 
> > 
> > umi3内置的antd是4.0不支持ie9，最低ie11+，如果想支持9，需要按照antd v3
> 
> @zhangxiaofeng87 IE11也报这个错误

同问
