### ISSUE TITLE
React antd项目中不能打包vue的组件

### ISSUE THREAD

**Issue by CindyBoy** [umijs/umi#4699]
环境：umi 2.13.3
打包配置config/config.js  参数chainWebpack: ( config, { webpack } ) 添加以下配置
const rule = config.module
      .rule('vue')
      .test(/\.vue$/)
    
    rule
    .exclude.add([path.resolve('node_modules')]).end()
      .use('vue-loader')
      .loader('vue-loader')
      .options({
        compilerOptions: {
          preserveWhitespace: true
        },
        plugins:[
          new VueLoaderPlugin()
        ],
        loaders: {
          'scss': [
              'vue-style-loader',
              'css-loader',
              'sass-loader'
          ],
          'sass': [
              'vue-style-loader',
              'css-loader',
              'sass-loader?indentedSyntax'
          ]
        }
      })

不能对vue的组件进行打包

**Comment by xiaohuoni** [comment]
能打包才奇怪吧？？
