### ISSUE TITLE
history在自定义工具类中封装再导出后，history.push浏览器路由变化但是页面不刷新

### ISSUE THREAD

**Issue by Liaozzzzzz** [umijs/umi#4701]
## What happens?

特殊场景， 需要对history进行一层封装，但是发现调用push时路由变化， 页面不刷新。但是history为hash模式的时候是没问题的，browser不行

## Mini Showcase Repository(REQUIRED)

复现demo仓库：https://github.com/Liaozzzzzz/umi-issue.git

## How To Reproduce
![image](https://user-images.githubusercontent.com/33082279/82198172-865cde80-992e-11ea-87f2-a22460ba8a80.png)
未作任何修改， 仅仅转了一次导出；

![image](https://user-images.githubusercontent.com/33082279/82198193-8ceb5600-992e-11ea-9aae-ae64d1d36dc1.png)
页面内使用就无法刷新页面了

**Expected behavior** 1. 2.

## Context

"umi": "^3",
"@ant-design/pro-layout": "^5.0.6",
浏览器环境 chrome 81.0.4044.138
开发环境 win10

**Comment by 282159468** [comment]
same issue

**Comment by zhanchengkun** [comment]
import { history} from 'umi'; 

export const router=history;

**Comment by Liaozzzzzz** [comment]
> import { history} from 'umi';
> 
> export const router=history;

和引入方式没关系。

**Comment by KMBaby-zyl** [comment]
@sorrycc 我们umi2升级也遇到一样的问题了。 这个是bug吗？

**Comment by shockw4ver** [comment]
这个 issue 目前有进展吗？

**Comment by xiaohuoni** [comment]
没复现这个问题，复现demo链接不可用。先关闭，有问题的提供复现demo再reopen

**Comment by MIN202299** [comment]
这个仓库凉了吗，umi 4 出现相同的问题了

**Comment by zhilianbi520** [comment]
遇到同样问题～！

**Comment by fz6m** [comment]
如果在 umi 4 中需要自行对 history 的方法进行 patch ，可以在运行时进行修改，以下供参考：

```ts
// src/app.ts

export const modifyClientRenderOpts = (context) => {
  const h = context.history
  const originPush = h.push
  const originReplace = h.replace
  h.push = (...args) => {
    originPush.apply(h, args)
  }
  h.replace = (...args) => {
    originReplace.apply(h, args)
  }
  return context
}
```
