### ISSUE TITLE
使用process.on报错 not function

### ISSUE THREAD

**Issue by liuqingsong** [umijs/umi#4703]
调用process.on全局方法，报错 not function，umi是否重写了该方法，如果是，怎么修改回来

**Comment by ycjcl868** [comment]
process.on？

**Comment by liuqingsong** [comment]
> process.on？
是的，正常情况下调用 process相关的属性、方法下有process.on()这个方法；
但是使用umi编译生成后调用process.on()失效，提示not function

**Comment by sorrycc** [comment]
浏览器端没有 process.on 的。

**Comment by liuqingsong** [comment]
问题解决了 umi webpack 默认node配置为 process:'mock'
在config.ts配置文件中 修改 为process:true就可以了 
但是不知道修改之后对框架有啥影响
