### ISSUE TITLE
配置layout无效

### ISSUE THREAD

**Issue by Smi1e96** [umijs/umi#4704]
## How To Reproduce

使用 `yarn create @umijs/umi-app`  
![image](https://user-images.githubusercontent.com/31199247/82284218-105a8500-99cb-11ea-8f4d-fdc14dd94641.png)
之后配置layout 
![image](https://user-images.githubusercontent.com/31199247/82284096-c376ae80-99ca-11ea-9d31-12f08bb30ce0.png)
出现下列问题
![image](https://user-images.githubusercontent.com/31199247/82284113-d1c4ca80-99ca-11ea-9ef3-3158835702c1.png)

ps: 最新的umi3.2 有此问题 3.1也有

**Comment by lzfei** [comment]
感觉不好用啊 按照文档来的 不行 也不知道发布的人员试过没

**Comment by l2en** [comment]
+1
