### ISSUE TITLE
plugin-dva 支持 ssr modifyGetInitialPropsCtx 还没有发布吗？

### ISSUE THREAD

**Issue by itellyou-com** [umijs/umi#4706]
## What happens?

发布了 umijs3.2 ssr ，但是没有发布最新的 plugin-dva ，没办法使用 modifyGetInitialPropsCtx 获取dva 数据流

我本地 plugin-dva 版本 0.6.5 ,runtime.tpl

```
import React from 'react';
import { _DvaContainer } from './dva';

export function rootContainer(container) {
  return React.createElement(_DvaContainer, null, container);
}
```

但是 https://github.com/umijs/plugins/blob/master/packages/plugin-dva/src/runtime.tpl 里面有扩展
modifyGetInitialPropsCtx 方法，你们还没有发布吗？

**Comment by ycjcl868** [comment]
发布中
