### ISSUE TITLE
SSR v3.2.0

### ISSUE THREAD

**Issue by kaoding** [umijs/umi#4707]
没有开启SSR的情况下，console下报，

Warning: Did not expect server HTML to contain the text node " " in <div>.

**Comment by ycjcl868** [comment]
？怎么复现

**Comment by ycjcl868** [comment]
有种情况就是 `<div id="root">里面有内容</div>`

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro/issues/6620

**Comment by kaoding** [comment]
1. git clone https://github.com/ant-design/ant-design-pro/tree/v5
2. yarn install
3. yarn start

就会出现。

网上的：https://www.pianshen.com/article/935962166/

**Comment by kaoding** [comment]
> 网上的：https://www.pianshen.com/article/935962166/

根据上面网上的操作，删除 document.ejs 里的 <div id="root"></div> 里的全部内容（里面有文本和dom都报错误）就不会报错误，没有开启SSR的情况下也得这样。

**Comment by ycjcl868** [comment]
> > 网上的：https://www.pianshen.com/article/935962166/
> 
> 根据上面网上的操作，删除 document.ejs 里的
> 
> 里的全部内容（里面有文本和dom都报错误）就不会报错误，没有开启SSR的情况下也得这样。

不用操作，合了发个版本更新下，就修复了
