### ISSUE TITLE
hideNav 配置不起作用

### ISSUE THREAD

**Issue by KevinWG** [umijs/umi#4709]
@umijs/plugin-layout 下，扩展配置：

   layout:{
          hideNav: true,
        },
此配置不起作用，仅   hideNav     这一配置，其他都OK

**Comment by leftstick** [comment]
我试了没问题，请提供详细信息，最好有可复现的repo

**Comment by KevinWG** [comment]
见：https://github.com/KevinWG/AntDesignProMenuSample

用最新版的创建的示例，在示例路由配置的基础上，修改了：

  {
      path: '/welcome',
      name: 'welcome',
      icon: 'smile',
      **layout:{
        hideNav:true,
      },**
      component: './Welcome',
    },

   在左侧菜单栏依然顽强的存在。

   操作系统是 : win10 pro

**Comment by leftstick** [comment]
这个。。。。你似乎是对 `hideNav` 和 `hideMenu` 有误解。

`hideNav` 指的是正上方的导航栏
`hideMenu` 才是你说的左侧菜单栏
