### ISSUE TITLE
umi3.2-ssr 编译报错

### ISSUE THREAD

**Issue by itellyou-com** [umijs/umi#4710]
## What happens?
开启配置：
```
ssr:{},
dva:{
   hmr: true,
},
dynamicImport:{},
```
新建一个 src/models/test.js
```
export default {
    namespace: 'test',

    state: {
    },
    effects: {
    }
}
```
yarn start 编译报错
.umi/plugin-dva/connect 并没有这个文件
```
Failed to compile with 1 errors                              下午5:02:05

This relative module was not found:

* ../plugin-dva/connect in ./src/.umi/core/umiExports.ts
```

## Mini Showcase Repository(REQUIRED)

> 复现仓库

https://github.com/itellyou-com/umi3.2-ssr-test

## 环境版本

- **Umi Version**:3.2
- **Node Version**:13.2
- **Platform**:mac

**Comment by ycjcl868** [comment]
已修复 https://github.com/umijs/plugins/pull/219
