### ISSUE TITLE
umi 3.2 + ssr 新项目创建即出错

### ISSUE THREAD

**Issue by silentim** [umijs/umi#4711]
1、 npx @umijs/create-umi-app  创建项目，
2、 cnpm install 安装依赖
3、未执行其它任何操作，立即 umi dev 运行

启动完后提示：

 ERROR  Failed to compile with 1 errors                                                                                                                                 下午6:32:19
 error  in ./src/.umi/plugin-request/request.ts

Module parse failed: Unexpected token (18:35)
File was processed with these loaders:
 * ./node_modules/_babel-loader@8.1.0@babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| function useRequest(service, options = {}) {
|   return useUmiRequest(service, {
>     formatResult: result => result?.data,
|     requestMethod: requestOptions => {
|       if (typeof requestOptions === 'string') {

 @ ./src/.umi/core/umiExports.ts 6:0-42 6:0-42
 @ ./node_modules/_umi@3.2.0@umi/dist/index.esm.js
 @ ./src/pages/index.jsx
 @ ./src/.umi/core/server.ts
 @ multi ./src/.umi/core/server.ts

引用 import { Helmet} from 'umi' ，提示没有该模块

**Comment by ycjcl868** [comment]
按需要 模块没安装完，npm update 试试

**Comment by silentim** [comment]
update 也不行，只要引用了  import { Helmet} from 'umi' ，就会有上面那个错误提示

**Comment by silentim** [comment]
我的环境是 windows + Node 14.2，没有 .lock 文件

**Comment by ycjcl868** [comment]
看起来像这个问题  https://github.com/umijs/plugins/pull/220

**Comment by silentim** [comment]
貌似与 helmet 无关，可能只要使用了类似  data?.title 中的 ? ，就会这样。

`import { Helmet } from 'umi';`

当使用 helmet 时，错误提示停在  formatResult: result => result?.data  ：

`You may need an additional loader to handle the result of these loaders.
    function useRequest(service, options = {}) {
    return useUmiRequest(service, {
>     formatResult: result => result?.data,`


然后不用 helmet ，如下代码：

`const Home = props => {
    const { data } = props;
    return data?.title;
};
Home.getInitialProps = (async (ctx) => {
    return Promise.resolve({
    data: {
        title: 'Hello World',
    }
    })
});
export default Home;`

提示：

`File was processed with these loaders:
     * ./node_modules/_babel-loader@8.1.0@babel-loader/lib/index.js
    You may need an additional loader to handle the result of these loaders.
    | const Home = props => {
    |   const data = props.data;
>   return data?.title;
};`


不使用helmet，只是使用了 data?.title ，错误提示也停在  ?  那一句。是否因为这个原因？
不使用ssr时，使用类似 data?.title 没有这样的问题

**Comment by silentim** [comment]
补充图片：

不引入 helmet 的时候：

![20200519212621](https://user-images.githubusercontent.com/65599013/82340243-96a1b600-9a21-11ea-85d7-5de6d2338ede.png)


引入 helmet 的时候：

![20200519212811](https://user-images.githubusercontent.com/65599013/82340254-999ca680-9a21-11ea-910b-9675f3b96efb.png)

**Comment by ycjcl868** [comment]
神奇的 bug，有复现的 demo 吗？

**Comment by ycjcl868** [comment]
重装试下，已经修了
