### ISSUE TITLE
routes参数缺失

### ISSUE THREAD

**Issue by zhanba** [umijs/umi#4712]
路由组件注入到页面的props中的route里面的routes没有。

![image](https://user-images.githubusercontent.com/4224253/82321420-62210080-9a07-11ea-94c9-0ed7901a9e59.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by zhanba** [comment]
麻烦修一下，这个生成面包屑要用到

**Comment by xiaohuoni** [comment]
是有的，要在layout层才有routes
