### ISSUE TITLE
connect.ts的类型冲突问题

### ISSUE THREAD

**Issue by zhanba** [umijs/umi#4714]
![image](https://user-images.githubusercontent.com/4224253/82322379-fd66a580-9a08-11ea-89b9-5290e926e1e3.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by ycjcl868** [comment]
先回滚了，connect.d.ts 没写对
