### ISSUE TITLE
umijs3.2.1 ssr 添加 getInitialState 后无法获得ssr渲染

### ISSUE THREAD

**Issue by itellyou-com** [umijs/umi#4715]
## What happens?

app.js 中 添加 getInitialState 
```
export async function getInitialState() {
    return {
        me:null,//window.g_initialProps.user.me,
    };
}
```
开启ssr 渲染后，无法获得渲染后的html代码，项目无报错,root 节点为空

```
<div id="root"></div>
```

## Mini Showcase Repository(REQUIRED)
https://github.com/itellyou-com/umi3.2-ssr-test

## Context

- **Umi Version**:3.2.1
- **Node Version**:13
- **Platform**:mac

**Comment by itellyou-com** [comment]
@ycjcl868 @sorrycc 
```
export const ssr = {
    modifyGetInitialPropsCtx: async (ctx) => {
        console.log(ctx,12313)
        ctx.test = "test"
    }
}
```
这个也失效了，无法执行到，控制台看不到相关打印消息

**Comment by ycjcl868** [comment]
没有 getInitialState，去掉了。

**Comment by wsz7777** [comment]
这个有什么比较好的解决方案么

**Comment by rfw** [comment]
什么比较好的解决方案么
