### ISSUE TITLE
怎么配置antd下dayjs 代替 Moment

### ISSUE THREAD

**Issue by eruca** [umijs/umi#4716]
antd下面有个插件可以使 dayjs替代moment, 怎么在umijs里配置

**Comment by chj-damon** [comment]
照着antd官网提供的做法做就行了

**Comment by williamnie** [comment]
安装这个插件AntdDayjsWebpackPlugin，在config里面修改
```
 chainWebpack(memo, { env, webpack, createCSSRule }) {
    //  使用day.js替换moment.js
    //TODO: 可能存在问题，后续需要确定下day.js的local-zh文件是否加载进来了
    memo.plugin('AntdDayjsWebpackPlugin').use(AntdDayjsWebpackPlugin);
  },
```

**Comment by H-Sven** [comment]
> 安装这个插件AntdDayjsWebpackPlugin，在config里面修改
> 
> ```
>  chainWebpack(memo, { env, webpack, createCSSRule }) {
>     //  使用day.js替换moment.js
>     //TODO: 可能存在问题，后续需要确定下day.js的local-zh文件是否加载进来了
>     memo.plugin('AntdDayjsWebpackPlugin').use(AntdDayjsWebpackPlugin);
>   },
> ```

我这样使用，好像并没有生效

**Comment by williamnie** [comment]
> > 安装这个插件AntdDayjsWebpackPlugin，在config里面修改
> > ```
> >  chainWebpack(memo, { env, webpack, createCSSRule }) {
> >     //  使用day.js替换moment.js
> >     //TODO: 可能存在问题，后续需要确定下day.js的local-zh文件是否加载进来了
> >     memo.plugin('AntdDayjsWebpackPlugin').use(AntdDayjsWebpackPlugin);
> >   },
> > ```
> 
> 我这样使用，好像并没有生效

看打包的分析页面里还有moment？
