### ISSUE TITLE
如何对内置权限错误页面的返回首页按钮进行控制

### ISSUE THREAD

**Issue by lichangchao15442** [umijs/umi#4717]
## Background

背景：在做页面权限时，用户进入了一个没有权限的页面，会显示umi/plugin-access内置的权限错误页面，该页面有一个返回首页的按钮。
目前的问题：返回的首页，该用户也没有首页的权限。就是一直停留着内置权限错误的页面。
## Proposal

自己思考：1. 有没有什么方法能够在配置路由时（config.route.ts)，根据用户的权限来决定‘/’路由的重定向路由（即不同权限对‘/’是重定向到不同页面的）；
2. 或者有没有什么办法是可以直接让开发者控制内置的权限错误页面（控制返回首页的按钮）。

**Comment by itellyou-com** [comment]
你指的内置权限是哪部分？，一般我在路由上使用 
```
{
        path: '/test',
        component: '../layouts/BlankLayout',
        access: 'isLogin',
        wrappers: ['@/wrappers/auth'],
        ...
}
```
自定义处理权限
```
import React from 'react';
import { useAccess, Redirect } from 'umi';
import { getRoute } from '@/utils/page';

export default ({ children, route, location: { pathname } }) => {
    const { routes = [] } = route || {};

    if (route && !route.routes) {
        routes.push(route);
    }
    const routeData = getRoute(pathname, routes);
    if (routeData && routeData.unaccessible) {
        const access = useAccess();
        if (!access.isLogin) return <Redirect to="/login" />;
        return <Redirect to="/403" />;
    }
    return children;
};

```

**Comment by lichangchao15442** [comment]
> 你指的内置权限是哪部分？，一般我在路由上使用
> 
> ```
> {
>         path: '/test',
>         component: '../layouts/BlankLayout',
>         access: 'isLogin',
>         wrappers: ['@/wrappers/auth'],
>         ...
> }
> ```
> 
> 自定义处理权限
> 
> ```
> import React from 'react';
> import { useAccess, Redirect } from 'umi';
> import { getRoute } from '@/utils/page';
> 
> export default ({ children, route, location: { pathname } }) => {
>     const { routes = [] } = route || {};
> 
>     if (route && !route.routes) {
>         routes.push(route);
>     }
>     const routeData = getRoute(pathname, routes);
>     if (routeData && routeData.unaccessible) {
>         const access = useAccess();
>         if (!access.isLogin) return <Redirect to="/login" />;
>         return <Redirect to="/403" />;
>     }
>     return children;
> };
> ```

我是指umi/plugin-access内置的权限错误页面，也就是‘/403’对应的页面，这个页面会有一个 ‘返回首页’的按钮，有没有什么方法可以控制这个按钮？

**Comment by itellyou-com** [comment]
> 我是指umi/plugin-access内置的权限错误页面，也就是‘/403’对应的页面，这个页面会有一个 ‘返回首页’的按钮，有没有什么方法可以控制这个按钮？
你看下api吧，权限错误页面是可以自己指定的，我在文档里面没有看的有内置错误页面，可能是你项目里的错误页面吧，或者 antd-pro 里面的内置错误页面？
https://umijs.org/zh-CN/plugins/plugin-access#children

**Comment by lichangchao15442** [comment]
> > 我是指umi/plugin-access内置的权限错误页面，也就是‘/403’对应的页面，这个页面会有一个 ‘返回首页’的按钮，有没有什么方法可以控制这个按钮？
> 
> 你看下api吧，权限错误页面是可以自己指定的，我在文档里面没有看的有内置错误页面，可能是你项目里的错误页面吧，或者 antd-pro 里面的内置错误页面？
> https://umijs.org/zh-CN/plugins/plugin-access#children

![image](https://user-images.githubusercontent.com/48148646/82418640-d2835c80-9aaf-11ea-8a24-76ad27f7bf4b.png)
是umi/plugin-layout里面的内置权限错误页面。我想请问一下，你的自定义权限处理是写在basicLayout文件中的吗？或者说是其它地方。我是使用的umi/plugin-layout和umi/plugin-access。

**Comment by itellyou-com** [comment]
> > > 我是指umi/plugin-access内置的权限错误页面，也就是‘/403’对应的页面，这个页面会有一个 ‘返回首页’的按钮，有没有什么方法可以控制这个按钮？
> > 
> > 
> > 你看下api吧，权限错误页面是可以自己指定的，我在文档里面没有看的有内置错误页面，可能是你项目里的错误页面吧，或者 antd-pro 里面的内置错误页面？
> > https://umijs.org/zh-CN/plugins/plugin-access#children
> 
> ![image](https://user-images.githubusercontent.com/48148646/82418640-d2835c80-9aaf-11ea-8a24-76ad27f7bf4b.png)
> 是umi/plugin-layout里面的内置权限错误页面。我想请问一下，你的自定义权限处理是写在basicLayout文件中的吗？或者说是其它地方。我是使用的umi/plugin-layout和umi/plugin-access。

https://umijs.org/zh-CN/plugins/plugin-layout#name-1
我看了文档，是可以自定义路由配置和 access 的，自定义处理添加到 src 目录下即可，然后路由中 wrappers 属性配置好路径就行了，可以配置多个

**Comment by lichangchao15442** [comment]
> > > > 我是指umi/plugin-access内置的权限错误页面，也就是‘/403’对应的页面，这个页面会有一个 ‘返回首页’的按钮，有没有什么方法可以控制这个按钮？
> > > 
> > > 
> > > 你看下api吧，权限错误页面是可以自己指定的，我在文档里面没有看的有内置错误页面，可能是你项目里的错误页面吧，或者 antd-pro 里面的内置错误页面？
> > > https://umijs.org/zh-CN/plugins/plugin-access#children
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/48148646/82418640-d2835c80-9aaf-11ea-8a24-76ad27f7bf4b.png)
> > 是umi/plugin-layout里面的内置权限错误页面。我想请问一下，你的自定义权限处理是写在basicLayout文件中的吗？或者说是其它地方。我是使用的umi/plugin-layout和umi/plugin-access。
> 
> https://umijs.org/zh-CN/plugins/plugin-layout#name-1
> 我看了文档，是可以自定义路由配置和 access 的，自定义处理添加到 src 目录下即可，然后路由中 wrappers 属性配置好路径就行了，可以配置多个

我刚刚试了一下，wrappers只能在有component的路由中生效，对于像是父菜单这种没有component就不能使用（采用plugin-layout是不能给父菜单再配置component的）

**Comment by itellyou-com** [comment]
> > > > > 我是指umi/plugin-access内置的权限错误页面，也就是‘/403’对应的页面，这个页面会有一个 ‘返回首页’的按钮，有没有什么方法可以控制这个按钮？
> > > > 
> > > > 
> > > > 你看下api吧，权限错误页面是可以自己指定的，我在文档里面没有看的有内置错误页面，可能是你项目里的错误页面吧，或者 antd-pro 里面的内置错误页面？
> > > > https://umijs.org/zh-CN/plugins/plugin-access#children
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/48148646/82418640-d2835c80-9aaf-11ea-8a24-76ad27f7bf4b.png)
> > > 是umi/plugin-layout里面的内置权限错误页面。我想请问一下，你的自定义权限处理是写在basicLayout文件中的吗？或者说是其它地方。我是使用的umi/plugin-layout和umi/plugin-access。
> > 
> > 
> > https://umijs.org/zh-CN/plugins/plugin-layout#name-1
> > 我看了文档，是可以自定义路由配置和 access 的，自定义处理添加到 src 目录下即可，然后路由中 wrappers 属性配置好路径就行了，可以配置多个
> 
> 我刚刚试了一下，wrappers只能在有component的路由中生效，对于像是父菜单这种没有component就不能使用（采用plugin-layout是不能给父菜单再配置component的）

https://umijs.org/zh-CN/plugins/plugin-layout#errorcomponent

ErrorComponent 自定义错误处理试过吗？只要能自定义错误处理，按钮很好控制了

**Comment by lichangchao15442** [comment]
> > > > > > 我是指umi/plugin-access内置的权限错误页面，也就是‘/403’对应的页面，这个页面会有一个 ‘返回首页’的按钮，有没有什么方法可以控制这个按钮？
> > > > > 
> > > > > 
> > > > > 你看下api吧，权限错误页面是可以自己指定的，我在文档里面没有看的有内置错误页面，可能是你项目里的错误页面吧，或者 antd-pro 里面的内置错误页面？
> > > > > https://umijs.org/zh-CN/plugins/plugin-access#children
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/48148646/82418640-d2835c80-9aaf-11ea-8a24-76ad27f7bf4b.png)
> > > > 是umi/plugin-layout里面的内置权限错误页面。我想请问一下，你的自定义权限处理是写在basicLayout文件中的吗？或者说是其它地方。我是使用的umi/plugin-layout和umi/plugin-access。
> > > 
> > > 
> > > https://umijs.org/zh-CN/plugins/plugin-layout#name-1
> > > 我看了文档，是可以自定义路由配置和 access 的，自定义处理添加到 src 目录下即可，然后路由中 wrappers 属性配置好路径就行了，可以配置多个
> > 
> > 
> > 我刚刚试了一下，wrappers只能在有component的路由中生效，对于像是父菜单这种没有component就不能使用（采用plugin-layout是不能给父菜单再配置component的）
> 
> https://umijs.org/zh-CN/plugins/plugin-layout#errorcomponent
> 
> ErrorComponent 自定义错误处理试过吗？只要能自定义错误处理，按钮很好控制了
这个倒是没有试过，但是权限问题可能不算ErrorComponent（刚刚试过，没有权限，不会调用这个API），而且，如果没有权限会调用ErrorComponent，但是这样的话对于不是权限的错误也会显示权限错误页面。感觉不太灵活。
十分感谢您的回复，目前，我打算给每个有component的路由配置都加上wrappers（虽然实现很冗余，但是这个是目前我知道能解决我问题的唯一方案了。）

**Comment by singhello** [comment]
> 你指的内置权限是哪部分？，一般我在路由上使用
> 
> ```
> {
>         path: '/test',
>         component: '../layouts/BlankLayout',
>         access: 'isLogin',
>         wrappers: ['@/wrappers/auth'],
>         ...
> }
> ```
> 
> 自定义处理权限
> 
> ```
> import React from 'react';
> import { useAccess, Redirect } from 'umi';
> import { getRoute } from '@/utils/page';
> 
> export default ({ children, route, location: { pathname } }) => {
>     const { routes = [] } = route || {};
> 
>     if (route && !route.routes) {
>         routes.push(route);
>     }
>     const routeData = getRoute(pathname, routes);
>     if (routeData && routeData.unaccessible) {
>         const access = useAccess();
>         if (!access.isLogin) return <Redirect to="/login" />;
>         return <Redirect to="/403" />;
>     }
>     return children;
> };
> ```

你的权限路由是怎么配置的，我配置了不行啊，求解

**Comment by itellyou-com** [comment]
> 这个倒是没有试过，但是权限问题可能不算ErrorComponent（刚刚试过，没有权限，不会调用这个API），而且，如果没有权限会调用ErrorComponent，但是这样的话对于不是权限的错误也会显示权限错误页面。感觉不太灵活。
> 十分感谢您的回复，目前，我打算给每个有component的路由配置都加上wrappers（虽然实现很冗余，但是这个是目前我知道能解决我问题的唯一方案了。）

看了下 plugin-layout 的代码，确实没有切入口
https://github.com/umijs/plugins/blob/master/packages/plugin-layout/src/component/Exception/index.tsx
直接获取到当前匹配的路由配置 currentMatchPaths ，然后传入了WithExceptionOpChildren ，没权限直接 403
https://github.com/umijs/plugins/blob/master/packages/plugin-layout/src/layout/index.tsx

**Comment by itellyou-com** [comment]
> 你的权限路由是怎么配置的，我配置了不行啊，求解

我没使用plugin-layout，也没有动态渲染路由，只判断了权限的
先获得初始化数据，这个插件 @umijs/plugin-initial-state
```
export async function getInitialState() {
    const result = await fetchMe();
    const me = result && result.result ? result.data : null;
   return {
        me,
    };
}
```
这里获得权限，
src/access.js
```
export default function(props) {
    const { me } = props || {}
    if (!me) return {};

    const isLogin = !!me;

    return {
        isLogin,
    };
}
```
获取到当前匹配的路由
```
import pathToRegexp from 'path-to-regexp';
import isEqual from 'lodash/isEqual';
import memoizeOne from 'memoize-one';

export const matchParamsPath = (path, routes) => {
    const routeMap = {};

    const renderMap = routes => {
        routes.forEach(item => {
            if (item && item.name && item.path) {
                routeMap[item.path] = item;
            }
            if (item.routes) {
                renderMap(item.routes);
            }
        });
    };

    renderMap(routes);

    const pathKey = Object.keys(routeMap).find(key => pathToRegexp(key).test(path));
    return routeMap[pathKey];
};

export const getRoute = memoizeOne((pathname, routes) => {
    return matchParamsPath(pathname, routes);
}, isEqual);
...
const routeData = getRoute(pathname, routes);
```
里面包含了 unaccessible 属性

**Comment by lichangchao15442** [comment]
@xiaohuoni 问题还没有解决怎么就关闭了呢（无奈），之前我说的那种方法也不能解决这个问题。

**Comment by phobal** [comment]
@lichangchao15442  可以参考这个做法 https://dfocusgroup.github.io/generator-umi/guide/route.html#%E6%9D%83%E9%99%90%E8%B7%AF%E7%94%B1%E7%9A%84%E5%BA%94%E7%94%A8

**Comment by lichangchao15442** [comment]
> @lichangchao15442 可以参考这个做法 https://dfocusgroup.github.io/generator-umi/guide/route.html#%E6%9D%83%E9%99%90%E8%B7%AF%E7%94%B1%E7%9A%84%E5%BA%94%E7%94%A8

我看了一下文档，里面似乎并没有涉及到我提出的问题😂

**Comment by lichangchao15442** [comment]
自己目前的解决方案：不在路由配置文件中对'/'重定向，并且在全局model中的subscriptions里对‘/’路由进行监听，根据用户权限决定‘/’要重定向到的页面路由。

**Comment by xiaohuoni** [comment]
@lichangchao15442 我看回复应该是可以解决的吧？

**Comment by lichangchao15442** [comment]
> @lichangchao15442 我看回复应该是可以解决的吧？
在关闭的时候还没有找到有效的解决方案😂（现在可以了）

**Comment by pgsteven** [comment]
having the same issue here as there is no way to customise the 403 page currently....

**Comment by txp1035** [comment]
来炒冷饭，2022了我也在看这个问题

**Comment by WuJiY** [comment]
> 来炒冷饭，2022了我也在看这个问题

快2023了我也在看这个问题

**Comment by txp1035** [comment]
> > 来炒冷饭，2022了我也在看这个问题
> 
> 快2023了我也在看这个问题

解决了~可以看这个https://github.com/umijs/umi/pull/8757

**Comment by txp1035** [comment]
> > 来炒冷饭，2022了我也在看这个问题
> 
> 快2023了我也在看这个问题

解决了~https://github.com/umijs/umi/pull/8757看这个pr，配置自定义权限页面

**Comment by WuJiY** [comment]
> > > 来炒冷饭，2022了我也在看这个问题
> > 
> > 
> > 快2023了我也在看这个问题
> 
> 解决了~#8757 看这个pr，配置自定义权限页面，使用方法在https://umijs.org/docs/max/access#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%9D%83%E9%99%90%E9%A1%B5%E9%9D%A2%E9%85%8D%E7%BD%AE

我是遇到了这么个问题，mix布局的时候，点击顶部menu的时候 需要个跳转redirect，这个redirect怎么判断跳哪一个有权限的路由？

**Comment by txp1035** [comment]
> > > > 来炒冷饭，2022了我也在看这个问题
> > > 
> > > 
> > > 快2023了我也在看这个问题
> > 
> > 
> > 解决了~#8757 看这个pr，配置自定义权限页面，使用方法在https://umijs.org/docs/max/access#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%9D%83%E9%99%90%E9%A1%B5%E9%9D%A2%E9%85%8D%E7%BD%AE
> 
> 我是遇到了这么个问题，mix布局的时候，点击顶部menu的时候 需要个跳转redirect，这个redirect怎么判断跳哪一个有权限的路由？

没有get到你的需求点，你可以在我主页找到我的微信，详细聊

**Comment by txp1035** [comment]
> > > > 来炒冷饭，2022了我也在看这个问题
> > > 
> > > 
> > > 快2023了我也在看这个问题
> > 
> > 
> > 解决了~#8757 看这个pr，配置自定义权限页面，使用方法在https://umijs.org/docs/max/access#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%9D%83%E9%99%90%E9%A1%B5%E9%9D%A2%E9%85%8D%E7%BD%AE
> 
> 我是遇到了这么个问题，mix布局的时候，点击顶部menu的时候 需要个跳转redirect，这个redirect怎么判断跳哪一个有权限的路由？

如果你想实现一个按钮点击需要基于权限重定向不同的路由需要你在点击菜单的时候去做处理
