### ISSUE TITLE
普通page页面如何获取config配置，umi 貌似没有对应的api

### ISSUE THREAD

**Issue by ZengTianShengZ** [umijs/umi#4721]
## What happens?
需要在普通page页面如何获取config下的 routes 信息，umi 貌似没有对应的api

 
 
## 相关环境信息
- Ant Design Pro
-    "@ant-design/pro-layout": "^5.0.8",
-    "umi": "^3.1.2",
- node v12.16.2
-  Mac OS

**Comment by itellyou-com** [comment]
用 Context ，Layout 包裹下

**Comment by ZengTianShengZ** [comment]
@itellyou-com  能再具体些吗，这样是能获取的到  config 下的 settings 配置，但 routes 信息拿不到

```js
import {Settings} from '@ant-design/pro-layout';
import { connect } from 'umi';

const PageTest = (props) => {
  const {settings} = props
  return (
    <div>page test</div>
  )
}

export default connect(({ global, settings }) => ({
  collapsed: global.collapsed,
  settings,
}))(PageTest);
```

**Comment by itellyou-com** [comment]
> @itellyou-com 能再具体些吗，这样是能获取的到 config 下的 settings 配置，但 routes 信息拿不到
> 
> ```js
> import {Settings} from '@ant-design/pro-layout';
> import { connect } from 'umi';
> 
> const PageTest = (props) => {
>   const {settings} = props
>   return (
>     <div>page test</div>
>   )
> }
> 
> export default connect(({ global, settings }) => ({
>   collapsed: global.collapsed,
>   settings,
> }))(PageTest);
> ```

使用 @ant-design/pro-layout 的话看一下 https://prolayout.ant.design/ 文档
```
import { RouteContext } from '@ant-design/pro-layout'
import { useContext } from 'react'

...

const { menuData } = useContext(RouteContext)
```
这里能获取到menuData 
或者你在项目 layouts 模版文件中自定义一个 类似 RouteContext 的Context 传递原本的路由
```
const BasicLayout = ({ route }) => {
   return (
      ...
      <RouteContext.Provider
                value={{
                    route
                }}
            >
                {children}
            </RouteContext.Provider>
      ...
   )
}
```

**Comment by ZengTianShengZ** [comment]
@itellyou-com 学习了，RouteContext 能获取到 routes 信息，不过需要 BasicLayout 下的子路由页面才能获取的到，如果在最上层的路由貌似还是拿不到 config下的所有 routes 信息。

如下: 子页面 `@/page1/index` 是能获取到对应的 routes 信息，但脱离 BasicLayout 的页面 `@/pagehome/index` 也是没法获取到 routes 信息 。

```js
// config.ts
...
routes: [
    {
      path: '/page-home',
      name: '首页',
      component: '@/pagehome/index',
    },
    {
      path: '/page1',
      name: 'page1',
      component: '../layouts/BasicLayout',
      routes: [
        {
          path: '/page1/index',
          component: '@/page1/index',
        }
      ]
   }
]
```

**Comment by itellyou-com** [comment]
> @itellyou-com 学习了，RouteContext 能获取到 routes 信息，不过需要 BasicLayout 下的子路由页面才能获取的到，如果在最上层的路由貌似还是拿不到 config下的所有 routes 信息。
> 
> 如下: 子页面 `@/page1/index` 是能获取到对应的 routes 信息，但脱离 BasicLayout 的页面 `@/pagehome/index` 也是没法获取到 routes 信息 。
> 
> ```js
> // config.ts
> ...
> routes: [
>     {
>       path: '/page-home',
>       name: '首页',
>       component: '@/pagehome/index',
>     },
>     {
>       path: '/page1',
>       name: 'page1',
>       component: '../layouts/BasicLayout',
>       routes: [
>         {
>           path: '/page1/index',
>           component: '@/page1/index',
>         }
>       ]
>    }
> ]
> ```

是的 Context 代表上下文，只要在母板页下面就能获取的上下文信息，如果脱离了baselayout页面比较多可以单独设置一个空的母板页专门设置共用的context以及其它参数。可以看下prolayout的源码

**Comment by ZengTianShengZ** [comment]
好的，谢谢

看 prolayout 源码，`MenuData` 是从 props 那到的 

```js
// @ant-design/pro-layout -> ProLayout.tsx
const ProLayout: React.FC<BasicLayoutProps> = (props) => {
  const {
    children,
    onCollapse: propsOnCollapse,
    location = { pathname: '/' },
    fixSiderbar,
    navTheme,
    contentStyle,
    layout: PropsLayout,
    route,
    style,
    disableContentMargin,
    siderWidth = 256,
    menu,
    isChildrenLayout: propsIsChildrenLayout,
    menuDataRender,
    loading,
    ...rest
  } = props;

  console.log('----route---', route)

}

```


ProLayout 的 route 由 BasicLayout 提供

```js
//  ./layouts/BasicLayout
const BasicLayout: React.FC<BasicLayoutProps> = (props) => {
  const {
    dispatch,
    children,
    settings,
    route
   } = props;

   retrun (
    <ProLayout
    {...props}>
    </<ProLayout
    )
}
```

BasicLayout 在 config.ts 下使用

```js
// config.ts
{
      path: '/page1',
      name: 'page1',
      component: '../layouts/BasicLayout',
      routes: [
        {
          path: '/page1/index',
          component: '@/page1/index',
        }
      ]
}
```

这些估计要分析 umi 框架是怎么加载 config.ts 配置生成路由才能知道怎么在普通页面获取 route 信息了
