### ISSUE TITLE
umi如何配置less-loader css-loader ？

### ISSUE THREAD

**Issue by zwtcici** [umijs/umi#4722]
# Question1
如何配置css-loader/less-loader ?
能给一个配置的demo吗？
官网的配置介绍根本不起作用，以前在webpack配置css-loader 、less-loader....但是现在用了umi之后;
# Question2
css的类名只能写成对象object，无法写字符串:
类似：`<div className={style.wrapper}/> `
当需要写多个类名的时候就必须要`${}` 这种写法才可以；而无法像
 `<div className="wrapper sizeBox"/> `
这种需要怎么解决？

**Comment by itellyou-com** [comment]
https://umijs.org/zh-CN/docs/assets-css#css-modules

Umi 会自动识别 CSS Modules 的使用，你把他当做 CSS Modules 用时才是 CSS Modules。

比如：

// CSS Modules
import styles from './foo.css';
使用 <div className={style.wrapper}></div>

// 非 CSS Modules
import './foo.css';
使用 <div className="wrapper"></div>

**Comment by GeraltX** [comment]
内置了classnames库，可以学一下怎么用
