### ISSUE TITLE
[Feature Request] 可不可以提供electron的架子

### ISSUE THREAD

**Issue by 986244073** [umijs/umi#4725]
## Background

想用electron-react 写一个app

**Comment by williamnie** [comment]
有基于2.0的，可以先用着，或者自己改改https://github.com/williamnie/umi-electron

**Comment by yy923683900** [comment]
https://github.com/Deuscx/umi3-electron-base 基于umi3的

**Comment by williamnie** [comment]
https://github.com/williamnie/umi3.0-electron 这个是3.0的

**Comment by codering** [comment]
🙋‍♂️+1

**Comment by DiamondYuan** [comment]
https://github.com/boilerplate-fe/umi-electron-boilerplate

typescript + umi3 + webpack

**Comment by BySlin** [comment]
https://github.com/BySlin/umi-plugin-electron-builder
umi3 electron plugin

**Comment by spirobel** [comment]
那么多。。。不知道怎么决定 :smile:

**Comment by WangJM001** [comment]
基于Umi的Electron框架，一行命令(pnpm create poros)生成Electron应用，快速开发、打包， 集成了各种功能，方便好用，感兴趣的可以看下，欢迎Star，项目还在不断迭代中。
https://github.com/porosjs/poros
