### ISSUE TITLE
3.2 ssr modifyGetInitialPropsCtx 无效果

### ISSUE THREAD

**Issue by itellyou-com** [umijs/umi#4726]
## What happens?

配置文件
```
export default defineConfig({
    ssr:{},
    dva:{
        //hmr: true,
    },
    dynamicImport:{},
    nodeModulesTransform: {
      type: 'none',
    },
    routes: [
       { path: '/', component: '@/pages/index' },
    ],
});
```
app.js
```
export const ssr = {
    modifyGetInitialPropsCtx: async (ctx) => {
        console.log(ctx,12313)
        ctx.test = "test"
    }
}
```
src/pages/index.tsx
```
Page.getInitialProps = async (cxt:any) => {
    console.log("test value:",cxt.test)
    return new Promise((resolve,reject) => {
        setTimeout(() => {
            resolve({text:"Timeout Hello"})
        }, 2000);
    })
}
```
https://umijs.org/zh-CN/docs/ssr#%E6%89%A9%E5%B1%95-ctx-%E5%8F%82%E6%95%B0
文档中说 同时也可以在自身应用中进行扩展，但是无法获取到 test 的值，同时控制台也无相关消息g
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/itellyou-com/umi3.2-ssr-test

## 复现步骤，错误日志以及相关配置

yarn start

## 相关环境信息

- **Umi 版本**：3.2.1
- **Node 版本**：13
- **操作系统**：mac

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/82516276-edf07500-9b4c-11ea-95b2-abdbad5d0ab3.png)

试了下有的

**Comment by ycjcl868** [comment]
看了下因为 dva 插件的原因，是 bug

**Comment by ycjcl868** [comment]
修复了
