### ISSUE TITLE
【问题】如何强制重新执行一次patchRoutes

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#4728]
## What happens?

情况如下，在render里面请求了后端api，然后再patchRoutes中增加了部分动态路由；
用户进入系统后，在页面上切换了角色，这个时候需要重新请求后端api，然后重新调用patchRoutes方法切换掉动态部分的路由；这种情况应该怎么处理？
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by EmilioDeng98** [comment]
我也正好遇到了这个问题，我的解决方法是登陆后刷新页面。

**Comment by zlyyyy** [comment]
我也遇到了。大佬你解决了嘛，除了刷新有没有别的办法啊

**Comment by zhuxiwen** [comment]
> 我也正好遇到了这个问题，我的解决方法是登陆后刷新页面。

踩的坑：建议下面这样写，不然h5可能不刷新
window.location.reload(true);

**Comment by EmilioDeng98** [comment]
> > 我也正好遇到了这个问题，我的解决方法是登陆后刷新页面。
> 
> 踩的坑：建议下面这样写，不然h5可能不刷新
> window.location.reload(true);

我现在解决的方案是  window.location.href ，会比 window.location.reload(true) 少刷新一次页面

**Comment by EmilioDeng98** [comment]
> 我也遇到了。大佬你解决了嘛，除了刷新有没有别的办法啊

暂时只找到这个解决方法 window.location.href , 本质还是刷新页面
