### ISSUE TITLE
二级目录不生效

### ISSUE THREAD

**Issue by 272269639** [umijs/umi#4732]
## config文件里无法设置二级目录

配置config文件时，二级路由中使用menu时无效，无法配置第二层级的目录

## 相关代码
```
{
  title:"项目管理",
  menu: {
    name:'项目管理',
    icon:'github'
  },
  routes:[
    {path:'/customer',
    component:'@/pages/projectManage/customer',  
    icon:'user',
    menu: {
      name:'客户管理',
    }
  }
  ]
}
```
## 相关环境信息

- **Umi 版本**：
3.2.1
- **Node 版本**：
10.15.3
- **操作系统**：
macOS

**Comment by ycjcl868** [comment]
是 `runtimePublicPath` 导致的

**Comment by miss61008596** [comment]
不使用menu项是正常的，应该是有bug。
`import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  layout: {
    name: '预算执行考评系统',
    locale: false,
    logo: false,
  },
  routes: [
    {
      path: '/',
      exact: true,
      component: '@/pages/index',
      icon: 'home',
      menu: {
        name: '首页',
      },
      access: 'home_menu',
    },
    {
      path: '/management',
      exact: true,
      icon: 'project',
      name: '项目管理',
      access: 'management_menu',
      routes: [
        {
          path: '/management/list',
          exact: true,
          component: '@/pages/index',
          name: '项目列表',
          access: 'management_list_menu',
        },
        {
          path: '/management/add',
          exact: true,
          component: '@/pages/index',
          name: '创建项目',
          access: 'management_add_menu',
        },
      ],
    },
  ],
  plugins: [],
});
`
![image](https://user-images.githubusercontent.com/6361237/86514834-59657c00-be47-11ea-9362-95d6e3998f38.png)

**Comment by miss61008596** [comment]
拿社区当玩具呢？发个release版本能认真点么？就这样的东西能用到生产？

**Comment by miss61008596** [comment]
暂时先用app.ts 配置动态的解决问题吧。。。。 
`
export const layout = {
  logout: () => {
    console.log("luocj");
  }, // do something

  menuDataRender:() =>[       //此功能可以实现动态路由，用来渲染访问路由
    {
      path: '/',
      name: '路由模块1',
    },
    {
      path: '/',
      name: '路由模块2',
      children: [
        { path: '/index1', name: '路由模块2-1' },
        { path: '/user', name: '路由模块2-2' },
      ],
    },
  ],
};
`

**Comment by wangyuan0108** [comment]
我也遇到这个问题，现在还没有解决是吗？

**Comment by ycjcl868** [comment]
Duplicate https://github.com/umijs/umi/issues/5708
