### ISSUE TITLE
@umijs/plugin-layout access应该遵循最小权限原则

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#4733]
## What happens?

![image](https://user-images.githubusercontent.com/7939085/82531793-98c75a00-9b72-11ea-8952-be4bdc69e89e.png)
这里觉着应该当为true的时候才允许访问该路由，这样更稳妥一些；因为有些情况其实没有这个权限，获取到的值是undefined或者null这种，这种情况下相当于权限通过了，而实际这种应该算未通过的

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by xiaohuoni** [comment]
不配置默认放行，这应该是设计如此。

**Comment by xiexingen** [comment]
对  个人感觉这里应该是最小权限的原则  默认不放行   看各位大佬的意见呢

**Comment by ypli0629** [comment]
+1

**Comment by holiday12138** [comment]
+1 主要是如果后端api报错，这时候拿到undefined 会放行所有菜单权限

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.

**Comment by xiexingen** [comment]
怎么关闭了
