### ISSUE TITLE
umi 3.2.0 本地ssr时报了警告，请问怎么去掉？

### ISSUE THREAD

**Issue by baochengshi** [umijs/umi#4734]
export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  ssr: {},
  routes: [
    { path: '/', component: '@/pages/index' },
  ],
});

![image](https://user-images.githubusercontent.com/27420773/82532142-476b9a80-9b73-11ea-8240-aeb2a795e74d.png)
在使用antd的组件时也会报警告，而且越来越多。
请问这么把这个去掉？
- **Umi 3.2.1**：
- **Node 10.14.1**：
- **mac**：

**Comment by baochengshi** [comment]
WARNING  Compiled with 1 warnings                                                                                                                                                                                               14:53:30

 warning  in ./src/pages/index.less?modules

Module Warning (from ./node_modules/_postcss-loader@3.0.0@postcss-loader/src/index.js):
Warning

Greetings, time traveller. We are in the golden age of prefix-less CSS, where Autoprefixer is no longer needed for your stylesheet.

 @ ./src/pages/index.tsx 3:0-42 14:15-21
 @ ./src/.umi/core/server.ts
 @ multi ./src/.umi/core/server.ts

[SSR]  render / start: 140.790ms


这个是报错内容

**Comment by ycjcl868** [comment]
感觉还好，postcss-loader 的 warn，不影响

**Comment by silentim** [comment]
同问

**Comment by baochengshi** [comment]
是不影响运行，但是每个页面如果都引用一次的话，警告特别多，很不好

**Comment by mzonghao** [comment]
你在 .umirc.local.ts 或 config.local.ts 中
设置
`
{
  targets: false,
  autoprefixer: false
}
`
将收获惊喜😄😄

**Comment by kungege** [comment]
[https://stackoverflow.com/questions/62883240/how-do-i-solve-greetings-time-traveller-we-are-in-the-golden-age-of-prefix-le](url)
可以试试这上面的解决办法

**Comment by wxf-start** [comment]
请问一下为什么有这个报错呐，我的也报错这个
