### ISSUE TITLE
使用约定路由，在打开新tab页后刷新页面、或者在打开新tab页时，hash值会掉，路由会回到根路由

### ISSUE THREAD

**Issue by yinweiyujian** [umijs/umi#4735]
**Steps to reproduce the behavior:** 
1、在http://www.xxxxx.com/#/DraftList页面，新打开http://www.xxxxx.com/#/Add页面（新tab页），
出错后会变成http://www.xxxxx.com/#/      回到首页

目前来看该问题主要出现在线上环境，本地环境暂未出现。还有就是mac上未出现此问题，问题发生在window电脑上，不是必现，是偶现，但出现几率较大。

- **Umi 2.7.7**:
- **Node v12.15.0**:
- **window**:

**Comment by xiaohuoni** [comment]
为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

**Comment by xiaohuoni** [comment]
为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN
