### ISSUE TITLE
Provide umi 3 project using Ssr + Redux below the examples directory

### ISSUE THREAD

**Issue by ozkanonur** [umijs/umi#4736]
What is the right way, best practices of running umi project with redux, redux persist and running ssr enabled ? There is documentation or no examples about it. It would be super nice if this is doable from maintainers. Please show us the best practices of it.

**Comment by ycjcl868** [comment]
Why not use [@umijs/plugin-dva](https://umijs.org/plugins/plugin-dva)？

**Comment by ozkanonur** [comment]
Because dva has its own standarts, I want to keep pure Redux and my project is pretty large so I dont want to refactor my whole state management.

**Comment by ozkanonur** [comment]
Also, just like umi and antd, Dva has too much documentation issues. Everything is Chinese, its hard to understand things via Google translate.

**Comment by sajjadshahi** [comment]
+1 for SSR example

**Comment by ozkanonur** [comment]
> +1 for SSR example with antd

If you use antd, the SSR does not work with the routes logic of Antd.

In Antd you use layouts below the absolute path like in [this](https://github.com/ant-design/ant-design-pro/blob/master/config/config.ts#L42) link. But umi takes them as a page, anything below that layouts does never render from server.

**Comment by ozkanonur** [comment]
Note: The usage in screenshot below is from Umi docs. This routing does not work with SSR.
<img width="550" alt="Screen Shot 2020-05-23 at 15 17 51" src="https://user-images.githubusercontent.com/39852038/82730475-ad3d5b00-9d08-11ea-99bb-4f9b72bbad79.png">

Branching with layout components in routes brokes the SSR somehow.

**Comment by sajjadshahi** [comment]
> Note: The usage in screenshot below is from Umi docs. This routing does not work with SSR.
> <img alt="Screen Shot 2020-05-23 at 15 17 51" width="550" src="https://user-images.githubusercontent.com/39852038/82730475-ad3d5b00-9d08-11ea-99bb-4f9b72bbad79.png">
> 
> Branching with layout components in routes brokes the SSR somehow @ycjcl868

What about wrapping the pages with the layout component. 

`
<MyLayout>
     <div>
          Here is my page at /user/login
     </div>
</MyLayout>
`

**Comment by ozkanonur** [comment]
> 
> 
> > Note: The usage in screenshot below is from Umi docs. This routing does not work with SSR.
> > <img alt="Screen Shot 2020-05-23 at 15 17 51" width="550" src="https://user-images.githubusercontent.com/39852038/82730475-ad3d5b00-9d08-11ea-99bb-4f9b72bbad79.png">
> > Branching with layout components in routes brokes the SSR somehow @ycjcl868
> 
> What about wrapping the pages with the layout component.
> 
> `<MyLayout> <div> Here is my page at /user/login </div> </MyLayout>`

That's also my workaround plan, I just wanted to share that ssr does not work naturally with umi routes which includes layoutings.

**Comment by dugagjin** [comment]
@sorrycc I saw that this is fixed with https://github.com/umijs/umi/pull/4842 but no release yet.
