### ISSUE TITLE
如何根据后台接口数据生成路由

### ISSUE THREAD

**Issue by lipengfei00** [umijs/umi#4737]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by j172993563** [comment]
这两也有关系？

**Comment by xiaohuoni** [comment]
后端接口返回的是菜单数据，不是路由数据，要分清楚。
