### ISSUE TITLE
文件的修改不会触发重新编译

### ISSUE THREAD

**Issue by j172993563** [umijs/umi#4738]
当创建了一个新的UMI项目后，当将已有的（其他项目）代码复制到新项目的文件夹时，例如：别的项目下的index.tsx（首页文件）直接拉到新项目的src/page/index.tsx后，假如修改刚粘贴过来的index.tsx文件，不能触发生编译。

编辑器是vscode，看到过说webstorm的safe write设置，所以我试过用idea，甚至直接用window自带文本编辑器，但都没有用。
也试过删除了src/.umi和node_modules文件夹，重新yarn && yarn start也没有用，唯一能重新编译的方法是重新启动项目。

**Comment by LeoHuiyi** [comment]
我这边部分会， 我加了个process.env.WATCH_IGNORED=node_modules就可以了 - -

**Comment by LeoHuiyi** [comment]
![image](https://user-images.githubusercontent.com/8001457/82635953-08514e00-9c34-11ea-8576-edd069f16668.png)
初步估计是这个正则问题 目录中有带dist 都会被忽略编译

**Comment by j172993563** [comment]
> ![image](https://user-images.githubusercontent.com/8001457/82635953-08514e00-9c34-11ea-8576-edd069f16668.png)
> 初步估计是这个正则问题 目录中有带dist 都会被忽略编译

但文件还是那些文件，没有动过，我意思也是按原来旧的（有效自动编译）文件直接拉下来用也不行

**Comment by j172993563** [comment]
> 我这边部分会， 我加了个process.env.WATCH_IGNORED=node_modules就可以了 - -

我在layouts/index.tsx里加了`useEffect(() => {
    process.env.WATCH_IGNORED = "node_modules"
  }, []);`
也没有效果

**Comment by j172993563** [comment]
自己解决了，步骤如下：
1. yarn create @umijs/umi-app
2.yarn
3.yarn start
4.直接用资源管理器（explorer）下拉到别的文件夹，不要直接到到编辑器上
