### ISSUE TITLE
3.2.2 ssr BasicLayout getInitialProps 和 Page getInitialProps

### ISSUE THREAD

**Issue by itellyou-com** [umijs/umi#4740]
## What happens?

我测试时这两者是异步执行的，谁先取得数据谁先返回。这里我在 BasicLayout 中使用 getInitialProps 获取全局状态，如果获取数据速度比 Page getInitialProps 慢，会导致 BasicLayout getState() 返回后无效

因为开启 ssr 后，@umijs/plugin-initial-state 就无法使用了，所以如果在 BasicLayout 通过 getInitialProps 获取全局数据，不能优先加载，将导致 Page 一些业务逻辑错误。

ssr 是否有什么好的获取全局数据推荐方法 ？

## Mini Showcase Repository(REQUIRED)

https://github.com/itellyou-com/umi3.2-ssr-test

## Context

- **Umi Version**:3.2.2
- **Node Version**:13
- **Platform**:mac

**Comment by ycjcl868** [comment]
应该是匹配 routes 串行执行的

**Comment by itellyou-com** [comment]
> 应该是匹配 routes 串行执行的

但是 page 并没有等待 BasicLayout getInitialProps 的执行结果就开始执行 page 的 getInitialProps ，这样导致我在 BasicLayout 获取的数据在return getState()之前， page 就先执行 return getState()。这样我的数据就不在 window.g_initialProps 里面了，dva 也加载不到这个全局数据了

**Comment by itellyou-com** [comment]
解决了：
在ssr服务端中使用 umi-request 请求获取全局数据，然后使用 getInitialPropsCtx 注入
```
getInitialPropsCtx: {
            user:userData
        }
```
BasicLayout 中 getInitialProps 里注入到 dva ，这样几乎不存在在BasicLayout中请求api网络延迟问题导致Page页先获取到数据return getState()不包含全局数据了
```
BasicLayout.getInitialProps = async ({ isServer , user , store , params }) => {
    const { dispatch , getState } = store
   
    const state = getState()
    if(isServer){
        dispatch({
            type:'user/setMe',
            payload:{
                ...user
            }
        })
        return Promise.resolve({ ...state , user:{ ...state.user , me:user } })
    }
    
}
```
