### ISSUE TITLE
怎样把生成的js与css放到子目录中去

### ISSUE THREAD

**Issue by IIIThSoul** [umijs/umi#4741]
使用umi编译成的脚本的话，css与js都是在根目录中的，类似dist/p__index.js这样的，请问怎样配置能把这些生成的文件放到单独的子目录中呢，如：js文件放到assets/js/下，这样

**Comment by xiaohuoni** [comment]
暂不支持

**Comment by antiantian** [comment]
config.js 文件中的 chainWebpack 可支持修改

chainWebpack: (config)=> {
     config.merge({
         output: {
            filename:'js/[name].[hash:8].js',
            chunkFilename : 'js/chunk/[name].[hash:8].chunk.js'
         }
     })    
}

**Comment by antiantian** [comment]
chainWebpack: (config)=> {
     // 修改js打包路径
     config.merge({
         output: {
            filename:'js/[name].[hash:8].js',
            chunkFilename : 'js/chunk/[name].[chunkhash:8].chunk.js'
         }
     })
     // 修改css文件打包路径
     config
     .plugin('extract-css')
     .use(
      MiniCssExtractPlugin,
       [
         {
           filename: `css/[name].[hash:8].css`,
           chunkFilename: `css/[name].[chunkhash:8].chunk.css`,
           ignoreOrder: true,
         },
       ],
     ); 
    
  }

**Comment by IIIThSoul** [comment]
好的，谢谢
