### ISSUE TITLE
提示安装ProLayout 安装完路由就不管用了

### ISSUE THREAD

**Issue by xuchao321** [umijs/umi#4745]
![image](https://user-images.githubusercontent.com/28084523/82662772-0b166800-9c61-11ea-9d9c-9b3ba3058a0f.png)

**Comment by xiaohuoni** [comment]
按模版发issues吧

**Comment by xuchao321** [comment]
@xiaohuoni 
您好 按模版发issues吧 是什么意思？
我这个目前刚创建的项目  yarn 一下  就提示少包  单独安装完成以后  项目跑起来  左侧菜单栏就不可点击了

**Comment by xiaohuoni** [comment]
照新建issues里面填写。
需要提供重现步骤。
## What happens?

A clear and concise description of what the bug is.

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub



## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by zxh0907** [comment]
遇到同样的问题，按提示安装后左侧菜单显示不出来了

**Comment by xiaohuoni** [comment]
@zxh0907 是什么项目，怎么操作，遇到什么问题？要表述一下。
