### ISSUE TITLE
yarn 下载依赖的时候提示缺少ProLayout  可以单独安装 左侧路由又不可点击了

### ISSUE THREAD

**Issue by xuchao321** [umijs/umi#4746]
- **Umi Version**:
- **Node v12.14.0:
- **Platform**:
![image](https://user-images.githubusercontent.com/28084523/82665168-d2c55880-9c65-11ea-9492-3e5c46f7394d.png)

**Comment by xuchao321** [comment]
![image](https://user-images.githubusercontent.com/28084523/82665628-c8578e80-9c66-11ea-88a1-de189837e1d5.png)

**Comment by xuchao321** [comment]
按提示安装完插件 就变成这样了  路由不管事了
![image](https://user-images.githubusercontent.com/28084523/82666156-da85fc80-9c67-11ea-9d18-f814891ec90f.png)

**Comment by Y-wson** [comment]
解决了么

**Comment by xuchao321** [comment]
没有 &nbsp;还是别用内部插件了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 悦者生存 <notifications@github.com&gt;
发送时间: 2020年5月23日 21:42
收件人: umijs/umi <umi@noreply.github.com&gt;
抄送: 徐超 <864141924@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[umijs/umi] yarn 下载依赖的时候提示缺少ProLayout  可以单独安装 左侧路由又不可点击了 (#4746)





 
解决了么

**Comment by xuchao321** [comment]
紧急求助  这是怎么回事   为什么umi插件yarn的时候下载不下来了  单独下载还不行

**Comment by Picsong** [comment]
又更新了3.23还是没解决

**Comment by xuchao321** [comment]
@Picsong 无语

**Comment by l2en** [comment]
遇到同样问题+1，希望官方紧急处理啊； 还没开始就结束了

**Comment by sorrycc** [comment]
需要手动安装下 @ant-design/pro-layout，然后我试过成功的。

![image](https://user-images.githubusercontent.com/35128/83826290-1b711d00-a70e-11ea-9692-e51b664064aa.png)

**Comment by Goomay** [comment]
> 需要手动安装下 @ant-design/pro-layout，然后我试过成功的。
> 
> ![image](https://user-images.githubusercontent.com/35128/83826290-1b711d00-a70e-11ea-9692-e51b664064aa.png)

下载是可以用的  不过hash路由下，点击侧边栏项路由能切换，但是侧边项不会选中

**Comment by Y-wson** [comment]
下载是可以用的 不过hash路由下，点击侧边栏项路由能切换，但是侧边项不会选中这个问题还是存在呀，有解决了的么
