### ISSUE TITLE
umi的官网文档过时

### ISSUE THREAD

**Issue by stfenjobs** [umijs/umi#4750]
进入页面 https://umijs.org/

点击 菜单栏 【Guide】  发现文档是旧版的

我在 钉钉群里，发现了新版文档地址是   https://umijs.org/zh-CN/docs

麻烦修改下

**Comment by stfenjobs** [comment]
old：
![image](https://user-images.githubusercontent.com/6580897/82755201-bb70a180-9e04-11ea-9007-772f9e475b31.png)


new：

![image](https://user-images.githubusercontent.com/6580897/82755205-c75c6380-9e04-11ea-9606-2179cc856308.png)

**Comment by itellyou-com** [comment]
我这里显示都是新版的，可能是你本地缓存问题

**Comment by ycjcl868** [comment]
> old：
> ![image](https://user-images.githubusercontent.com/6580897/82755201-bb70a180-9e04-11ea-9007-772f9e475b31.png)
> 
> new：
> 
> ![image](https://user-images.githubusercontent.com/6580897/82755205-c75c6380-9e04-11ea-9606-2179cc856308.png)

清一下 PWA 缓存

**Comment by stfenjobs** [comment]
f12 删除了 各种东西， 正常了， 谢谢

你们用啥技术实现的缓存的，  有办法自动刷新吗

**Comment by ycjcl868** [comment]
PWA，因为新站点没有触发旧站点的 Service Worker 的 Clean Cache，就会永久缓存
