### ISSUE TITLE
umi  编译之后在.umi文件中 找不到对应的模块

### ISSUE THREAD

**Issue by xuchao321** [umijs/umi#4755]
![image](https://user-images.githubusercontent.com/28084523/82778099-ebf72080-9e82-11ea-8bb0-5048adcd3780.png)

## 相关环境信息

- **Umi 版本**：@3.2.2
- **Node 版本**：@12
- **操作系统**：mac

**Comment by xuchao321** [comment]
![image](https://user-images.githubusercontent.com/28084523/82778224-59a34c80-9e83-11ea-8a96-b9c3fb03cd1b.png)

**Comment by xiaohuoni** [comment]
可能也需要 tsconfig 
> tsconfig.json 中有配置 @@ 的路径，比如 "@@/*": ["src/.umi/*"]，
https://umijs.org/docs/faq#import-from-umi-%E6%B2%A1%E6%9C%89%E5%AE%9A%E4%B9%89%E6%80%8E%E4%B9%88%E5%8A%9E%EF%BC%9F

**Comment by xuchao321** [comment]
您好，照着配置上也不管用


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"陈小聪"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月25日(星期一) 下午4:31
收件人:&nbsp;"umijs/umi"<umi@noreply.github.com&gt;;
抄送:&nbsp;"ip141陈蜀川"<864141924@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [umijs/umi] umi  编译之后在.umi文件中 找不到对应的模块 (#4755)





 
可能也需要 tsconfig
  
tsconfig.json 中有配置 @@ 的路径，比如 "@@/": ["src/.umi/"]，
 https://umijs.org/docs/faq#import-from-umi-%E6%B2%A1%E6%9C%89%E5%AE%9A%E4%B9%89%E6%80%8E%E4%B9%88%E5%8A%9E%EF%BC%9F

**Comment by xuchao321** [comment]
![image](https://user-images.githubusercontent.com/28084523/82869632-29ca7680-9f61-11ea-9b52-50184ad479a0.png)
默认就这样

**Comment by xuchao321** [comment]
![image](https://user-images.githubusercontent.com/28084523/82871068-8af34980-9f63-11ea-8113-74f00097f7dd.png)

**Comment by xiaohuoni** [comment]
提供个 demo 吧。我现在很少用 jsx 的
