### ISSUE TITLE
umi 在 jenkins 打包内存溢出

### ISSUE THREAD

**Issue by lvzegeng** [umijs/umi#4758]
今天刚升级为3版本才有这个问题，2版本没问题

![image](https://user-images.githubusercontent.com/26923315/82805912-60e44d80-9eb7-11ea-8f89-151a4f290d3e.png)

umi 3.2.2
centos 7
jenkins

**Comment by ycjcl868** [comment]
https://umijs.org/guide/boost-compile-speed#%E9%85%8D%E7%BD%AE-nodemodulestransform-%E4%B8%BA---type-none-
