### ISSUE TITLE
登录进入页面，配置的权限菜单未渲染，需要手动刷新路由才会渲染

### ISSUE THREAD

**Issue by lichangchao15442** [umijs/umi#4759]
## What happens?
结合使用umi/plugin-layout和umi/plugin-access，登录进入页面，配置的权限菜单未渲染，需要手动刷新路由才会渲染

## 最小可复现仓库
https://github.com/lichangchao15442/re-demo-umi_access-layout.git

## 复现步骤，错误日志以及相关配置

输入用户名lcc和任意密码，进入页面，应该显示dashboard页面和菜单。
（实际进入后会提示没有权限，并且菜单未渲染，手动刷新路由后，才会出现对应页面和路由）

## 相关环境信息

- **Umi 版本**：3.2.2
- **Node 版本**：v13.12.0
- **操作系统**：macOS Catalina 10.15.4

**Comment by lichangchao15442** [comment]
这个问题已经解决了。
解决方法：登录成功路由跳转时，调用@umijs/plugin-initial-state的refresh方法。
困惑的我是：我和同事是一份代码，但是有些在我电脑上有问题，但是在同事的电脑上就不存在这些问题。比如：菜单无法高亮选中和权限菜单不渲染（就是这里提出的，已调用过refresh方法但是在我电脑上运行时权限菜单还是不渲染），在我的电脑上存在这些问题，同一份代码，在同事电脑上又没有，这种问题也不好定位，我想要了解一下有没有人遇到和我一样的问题（😂）

**Comment by annpeter** [comment]
@lichangchao15442   我刷新了好像也还是有这个问题

**Comment by lichangchao15442** [comment]
> @lichangchao15442 我刷新了好像也还是有这个问题

我当时也存在使用@umijs/plugin-initial-state的refresh方法后还是没有显示侧边导航栏的情况（但是同样的代码在同事的电脑上不存在这个问题），如果没有其它方法可以解决的话，你可以尝试使用window.location.reload()强制刷新当前页面。

**Comment by annpeter** [comment]
![image](https://user-images.githubusercontent.com/7344217/87250262-39ad0400-c496-11ea-9224-0fb2555b9a5b.png)
我试过了用window.location.reload()强制刷新是可以，但是页面会加载两次；后来我知道原因了，是pro登录成功跳转这边有点问题，我把跳转方式全都改成**window.location.href**就可以了

**Comment by lichangchao15442** [comment]
> ![image](https://user-images.githubusercontent.com/7344217/87250262-39ad0400-c496-11ea-9224-0fb2555b9a5b.png)
> 我试过了用window.location.reload()强制刷新是可以，但是页面会加载两次；后来我知道原因了，是pro登录成功跳转这边有点问题，我把跳转方式全都改成**window.location.href**就可以了

我从来没想到会是路由跳转方式的问题。确实使用window.location.href可以解决，感谢！

**Comment by JackDan9** [comment]
@lichangchao15442 具体原因后面有排查出来吗？
