### ISSUE TITLE
v1.3.1 使用代理 post 请求 contentType = application/json  超时报错

### ISSUE THREAD

**Issue by amily4555** [umijs/umi#476]
如题

**Comment by sorrycc** [comment]
怎么重现？

**Comment by superlbr** [comment]
Here to show it：
1. use antd-admin@develop
2. update dep
```
    "umi": "^1.3.1",
    "umi-plugin-dll": "^0.2.0",
    "umi-plugin-dva": "0.7.1",
    "umi-plugin-routes": "^0.1.3"
```
3. comment .umirc.mock.js
4. modify .webpackrc.js proxy. then take whatever a server.
```
        "/api/v1": {
      "target": "http://localhost:3000",
      "changeOrigin": true,
      "pathRewrite": { "^/api/v1": "/" }
    },
```
5. it'll see login post pending, and finally such
![image](https://user-images.githubusercontent.com/8142164/40060527-6d9c2b18-5889-11e8-8ba8-1fef2c0b3f90.png)
6. also the server side
```
    2018-05-15 21:43:30,544 ERROR 39981 A client (::ffff:127.0.0.1:53418) error [HPE_INVALID_EOF_STATE] occurred: Parse Error
2018-05-15 21:43:30,553 WARN 39981 [-/127.0.0.1/-/120008ms POST /user/login] nodejs.BadRequestError: request aborted
    at IncomingMessage.onAborted (/Users/dva/Developer/tuhuo/api/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:180:13)
    at abortIncoming (_http_server.js:441:9)
    at socketOnClose (_http_server.js:435:3)
    at Socket.emit (events.js:185:15)
    at TCP._handle.close [as _onclose] (net.js:541:12)
message: 'request aborted'
code: 'ECONNABORTED'
expected: 48
length: 48
received: 0
type: 'request.aborted'
headerSent: true
pid: 39981
hostname: Dva.lan
```
though HPE_INVALID_EOF_STATE is an error of server, but it never seen before umi@1.3.0

**Comment by superlbr** [comment]
guess maybe something with mock, mock is ok however

**Comment by sorrycc** [comment]
So, there is a problem with proxy + post?

**Comment by sorrycc** [comment]
Does **GET** + proxy work?

**Comment by superlbr** [comment]
yes

**Comment by sorrycc** [comment]
I don't know how to reproduce it.

Have tested jsonplaceholder.typicode.com, and it works.

```
proxy: {
  "/api": {
    "target": "http://jsonplaceholder.typicode.com/",
    "changeOrigin": true,
    "pathRewrite": { "^/api" : "" }
  }
}
```

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/479

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi-dva-user-dashboard  在这里重现不了
![_20180516101547](https://user-images.githubusercontent.com/11746742/40092875-3785347a-58f2-11e8-881c-24f4e67840df.png)

**Comment by amily4555** [comment]
将 content-type 改成 application/json 试下

**Comment by xiaohuoni** [comment]
@amily4555 
![_20180516110939](https://user-images.githubusercontent.com/11746742/40094446-99d33594-58f9-11e8-9f57-9816f44070b8.png)
应该不是 content-type的问题吧

**Comment by xiaohuoni** [comment]
@superlbr 我们项目组刚刚也出现这个错误，我看了一下，是别人不小心把服务器的请求地址写错了，你可以先确定一下你这个服务能不能正确响应

**Comment by xiaohuoni** [comment]
@superlbr This is a mistake in our project group. I looked at it. Someone accidentally wrote the wrong address of the server's request. You can first make sure that your service can respond correctly.（Baidu Translate）

**Comment by superlbr** [comment]
不用翻译，我只是练练英语, 等下准备抓个包看看，get是可以正确相应的，感觉mock缺个开关...

**Comment by xiaohuoni** [comment]
mock开关加一个环境变量就能处理了。如antd-pro里面的实现
https://github.com/xiaohuoni/umi-antd-pro/blob/master/.umirc.mock.js

**Comment by yb7** [comment]
同样出现这个问题好奇怪～

**Comment by hansnow** [comment]
一个可复现demo [hansnow/umi-proxy-issue](https://github.com/hansnow/umi-proxy-issue)

观察到的一些现象:
1. body里有内容且headers设置了{"Content-type": "application/json"}时，开发者工具中会显示该请求一直处于pending状态，此时服务端能接收到该请求，但是没有收到body
2. body里有内容且headers没有做content-type相关设置时（此时默认为"text/html; charset=utf-8"?），请求可以被正常发出去且开发者工具可以正常看到返回

**Comment by yb7** [comment]
同一个代码测试了 1.3.X 都是pending，切换回1.2.6 ok

**Comment by superlbr** [comment]
并非所有的post都会fail...
一个header 为application/json; charset=utf-8，但是form-data形式的提交是ok

**Comment by superlbr** [comment]
1.3.0 就有这个问题，可以缩小范围

**Comment by xiaohuoni** [comment]
@hansnow 你的例子，增加一个async就能请求到了
```js
export const createPost = async () =>
  fetch("/api/posts", {
    method: "POST",
    credentials: 'include',
    mode: 'cors',
    cache: "force-cache",  
    body: JSON.stringify({
      title: "foo",
      body: "bar",
      userId: 1
    }),
    headers: {
      "Content-type": "application/json; charset=UTF-8;"
    }
  }).then(resp => resp.json());
```

**Comment by hansnow** [comment]
我发现了，headers里面改成这样就可以了

```diff
    headers: {
-      "Content-type": "application/json; charset=UTF-8"
+      "Content-type": "application/json; charset=UTF-8;"
    }
```

**Comment by xiaohuoni** [comment]
@sorrycc head不设置的时候，默认带的是Content-Type: application/x-www-form-urlencoded;charset=UTF-8 就是没带分号的。

**Comment by xiaohuoni** [comment]
和使用代理没有关系，跨域访问也存在这个问题。

**Comment by xiaohuoni** [comment]
1.2.6也能重现这个问题

**Comment by chinacoolboyzz** [comment]
windows 10
1.3.2版

` "Content-type": "application/json; charset=UTF-8;"`
工作正常

`"Content-type": "application/json"`
代理配置不工作

**Comment by sorrycc** [comment]
@chinacoolboyzz Content-type 是客户端请求库里配的？

**Comment by chinacoolboyzz** [comment]
```
import fetch from 'dva/fetch'

export default function request (url, options) {
  return Promise.race([
    fetch(url, { ...options, credentials: 'include' }),
    new Promise(
      _.debounce(
        (resolve, reject) => reject(new Error('服务器请求超时'))
        , 20000))
  ])
    .then((response) => {
      return checkStatus(response)
    })
    .then(parseErrorMessage)
    .catch(err => ({ err }))
}

export async function query (params) {
  return request('/api/init', {
    method: 'post',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json; charset=UTF-8;'
    },
    body: JSON.stringify(params)
  })
}
```

**Comment by xiaohuoni** [comment]
不使用umi也有这个问题嘛？我刚刚单独使用，好想也会。（捂脸）

**Comment by xiaohuoni** [comment]
@hansnow 你有没有弄明白，加不加；有什么差别？我实在没弄懂。

**Comment by xiaohuoni** [comment]
应该看不到  '/user/1' 吧，代理是不是启了一个中转服务器？在浏览器里的应该看不到这个请求吧，

**Comment by superlbr** [comment]
wireshark

**Comment by hansnow** [comment]
@xiaohuoni 还没时间看，我打算有时间的话对比一下umi@1.2.6和umi@1.3.1依赖的包有哪些更新版本了，然后再从这些更新了版本的包里找到和proxy相关的

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/492 在这里跟进，这个太长了，每次进来好卡

**Comment by LemonTree-shine** [comment]
umi的proxy代理有时候转发请求特别特别慢，用postman不转发调原有接口或者ng转发都是正常的，只有用umi的proxy转发超级慢，求解决
