### ISSUE TITLE
config file not catch parse the content error

### ISSUE THREAD

**Issue by ycjcl868** [umijs/umi#4760]
## What happens?

![image](https://user-images.githubusercontent.com/13595509/82854646-a8acb880-9f3b-11ea-95d2-b80a2e887aff.png)

## Mini Showcase Repository(REQUIRED)

create new config file `config/config.local.ts`, empty content like

```js
// config/config.local.ts
```

## How To Reproduce

`umi dev`

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
Can't reproduce.
