### ISSUE TITLE
require("history/createHashHistory")报错

### ISSUE THREAD

**Issue by azx1985** [umijs/umi#4763]
## What happens?
现在用的是umi3.2.2版本，报错   “devScripts.js:5035 Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release.”

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by wulinjie122** [comment]
后来解决了吗？我也遇到同样的问题了，我也是用的`"umi": "^3.3.7"`，不知道为什么会报警告。
```jsx
import { history } from 'umi';

history.goBack();
```
