### ISSUE TITLE
保存文件后，热加载编译前，会有1s多的延时

### ISSUE THREAD

**Issue by qld-cf** [umijs/umi#4770]
## What happens?

保存文件后，热加载编译前，会有1s多的延时，这期间发生了什么？

## 相关环境信息

- **Umi 版本**：3.1.1
- **Node 版本**：12
- **操作系统**：mac

**Comment by xiaohuoni** [comment]
不太应该，你修改了什么文件。如果是 pro 的项目，修改了 less 文件，有可能。可以通过判断 dev 环境，先不启用动态皮肤方案。

**Comment by qld-cf** [comment]
已解决

**Comment by qld-cf** [comment]
``

**Comment by qld-cf** [comment]
`if (closeFlexRoute) {
  // 本地热加载走写死路由，提高速度，命令行添加参数才有效
  config.routes = _route
}`

**Comment by qld-cf** [comment]
> 不太应该，你修改了什么文件。如果是 pro 的项目，修改了 less 文件，有可能。可以通过判断 dev 环境，先不启用动态皮肤方案。

你指的动态皮肤是动态路由？

**Comment by xiaohuoni** [comment]
@qld-cf 我只是猜的，如果你不知道我说的是什么，那就忽略就好。看你的解决方法，并没有解决问题，可否提供一个复现 demo，便于我们进一步定位问题。

**Comment by qld-cf** [comment]
> @qld-cf 我只是猜的，如果你不知道我说的是什么，那就忽略就好。看你的解决方法，并没有解决问题，可否提供一个复现 demo，便于我们进一步定位问题。

不是啊，明显解决了，当我在src的page里面添加50个业务，有没有在umirc.ts添加routes，热加载速度差距很大

**Comment by xiaohuoni** [comment]
嗯，你是用 routes 只编译你配置的这几个页面，和数量比较起来当然差异很大。但是热加载应该只编译有修改的那个文件即可的。所以我说你开发的时候，配置 routes 没有解决问题。
