### ISSUE TITLE
umi3.22官方文档快速上手项目 yarn create @umijs/umi-app报错

### ISSUE THREAD

**Issue by Picsong** [umijs/umi#4776]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库
就是yarn create @umijs/umi-app报错提示python找不到

## 相关环境信息

- **Umi 版本**：3.22
- **Node 版本**：14.3
- **操作系统**：w10

**Comment by qld-cf** [comment]
什么卵 我们都用的好好的  错误呢

**Comment by Picsong** [comment]
> 什么卵 我们都用的好好的 错误呢
你是重新yarn create @umijs/umi-app的吗。创建能成功只是有个python报错提示，还有就是开启layout后yarn安装依赖提示要自己安装Pro-layout了，umi现在不自动安装了吗

**Comment by xuchao321** [comment]
@Picsong 自己安装完  就运行不了了

**Comment by Picsong** [comment]
> @Picsong 自己安装完 就运行不了了
等更新吧
