### ISSUE TITLE
umi3.2在dva的model中直接或间接使用isBrowser()报错TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by hqm19** [umijs/umi#4779]
## What happens?

umi3.2在dva的model中直接或间接使用isBrowser()时报错TypeError: Object(...) is not a function

## 最小可复现仓库
> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/hqm19/umi-issue-recurrence

## 复现步骤，错误日志以及相关配置

```
git clone https://github.com/hqm19/umi-issue-recurrence  && cd umi-issue-recurrence
cnpm i
umi dev
```

访问首页http://localhost:8000/
命令行报错：

```
ERROR [SSR] TypeError: Object(...) is not a function
    at getBackendApiPrefix (/umi-issue-recurrence/dist/umi.server.js:109872:129)
    at Module../src/models/user/loginUser.js (/umi-issue-recurrence/dist/umi.server.js:109881:16)

```

页面报错：

```
TypeError: Object(...) is not a function
getBackendApiPrefix
./src/models/user/loginUser.js:9
   6 | import { isBrowser } from "umi"
   7 | 
   8 | function getBackendApiPrefix() {
>  9 |   console.log("isBrowser:", isBrowser, isBrowser())
  10 |   if (!isBrowser()) {
  11 |     return "http://localhost:8080" //本机测试
  12 |   } else {

```

## 相关环境信息

- **Umi 版本**：
3.2.2
- **Node 版本**：
v10.16.3
- **操作系统**：
Darwin hqmac.local 19.3.0 Darwin Kernel Version 19.3.0

**Comment by OliverBancroft** [comment]
同出现

**Comment by xiaohuoni** [comment]
@ycjcl868 看导出关系应该是正确的，但是运行时就是报错。

**Comment by leftstick** [comment]
循环依赖导致的，就目前来说，快速解决的办法就是把

`import { isBrowser } from "umi"`

改成

`import { isBrowser } from "@umijs/utils/lib/ssr.js"`

**Comment by wsz7777** [comment]
没有更好的解决办法了吗

**Comment by feibi** [comment]
这个问题什么时候能修复呢
