### ISSUE TITLE
enabled SSR but still get empty in root div

### ISSUE THREAD

**Issue by nguyenhuutinh** [umijs/umi#4782]
hi,
I tried to convert my project (umijs and antd )to SSR.
All error has been fixed. I can see the log of server and I can view my website

But when I view source, it is still in SPA , not server rendering.

Do you know why?

<img width="752" alt="Screenshot 2020-05-28 at 4 34 31 PM" src="https://user-images.githubusercontent.com/4114159/83125020-20781000-a101-11ea-8832-e6d1d096ebc2.png">

![Screenshot 2020-05-28 at 4 27 57 PM](https://user-images.githubusercontent.com/4114159/83124929-0a6a4f80-a101-11ea-8cc9-62df851ced9a.png)

Thanks

**Comment by ozkanonur** [comment]
This problem might related to https://github.com/umijs/umi/issues/4736#issuecomment-633042294

**Comment by ycjcl868** [comment]
Maybe `<div id="root">` should be empty, or wouldn't be replaced by rendered HTML. 

https://github.com/umijs/umi/blob/master/packages/preset-built-in/src/plugins/features/ssr/templates/utils.ts#L119-L120

**Comment by nguyenhuutinh** [comment]
so how can I fix it @ycjcl868 ? thanks

**Comment by dugagjin** [comment]
I have the same issue, empty root div. 

And this are my routes:

```javascript
    routes: [
        { exact: true, path: '/', redirect: '/dashboard' },
        {
            component: '@/pages/dashboard',
            icon: 'home',
            name: 'Dashboard',
            path: '/dashboard',
            title: 'Dashboard',
        },
        {
            component: '@/pages/tips',
            icon: 'bulb',
            name: 'Tips',
            path: '/tips',
            title: 'Tips',
        },
        { component: '@/pages/404' },
    ],
```
`exportStatic` and `ssr are enabled with `{}` on both.

**Comment by dugagjin** [comment]
> I have the same issue, empty root div.
> 
> And this are my routes:
> 
> ```js
>     routes: [
>         { exact: true, path: '/', redirect: '/dashboard' },
>         {
>             component: '@/pages/dashboard',
>             icon: 'home',
>             name: 'Dashboard',
>             path: '/dashboard',
>             title: 'Dashboard',
>         },
>         {
>             component: '@/pages/tips',
>             icon: 'bulb',
>             name: 'Tips',
>             path: '/tips',
>             title: 'Tips',
>         },
>         { component: '@/pages/404' },
>     ],
> ```
> 
> `exportStatic` and `ssr` are enabled with `{}` on both.

After some testing I discovered that umi pro-layout plugin is the cause of this issue (at least of me).
When I remove it SSR works without any issue.

I then tested a fresh umi app with pro-layout by following: https://umijs.org/docs/getting-started#change-setting.

I activated `exportStatic: {}` and `ssr: {}` and I could not run it because of an error telling me that @ant-design/pro-layout is required and missing as dependency. I added it and then empty root div!

I removed `layout: {}` in `.umirc.ts` and SSR worked without any issues.
