### ISSUE TITLE
约定式路由的场景下，404无法正确匹配

### ISSUE THREAD

**Issue by harrischen** [umijs/umi#4783]
我现在的项目目录是这样的：
![image](https://user-images.githubusercontent.com/8149304/83144990-b2464400-a126-11ea-8913-8eeaf0823fea.png)

我通过在`layouts/index.tsx`当中配置了全局路由，打印了相关信息：
```
import './index.less';
import React, { FunctionComponent } from 'react';
import { IRouteComponentProps } from 'umi';
import Header from '@/components/header';
import Footer from '@/components/footer';
import Policy from '@/components/footer/policy';

const Layout = ({ children, route, match }: IRouteComponentProps) => {
  console.log(route);
  console.log(match);
  return (
    <div className="page-layout">
      <Header />
      {children}
      <Footer />
      <Policy />
    </div>
  );
};

export default Layout;
```
![image](https://user-images.githubusercontent.com/8149304/83145112-e6ba0000-a126-11ea-9b4b-8b5f3e36bbe6.png)

这个时候，我随意访问一个不存在的路径，比如`127.0.0.1/xxxx.html`。这个时候，页面却是能正常渲染，并渲染出以下组件(因为项目原因，不能截图，只能贴出渲染出的代码信息)：
```
<div className="page-layout">
    <Header />
    <Footer />
    <Policy />
</div>
```

即它会渲染出一个不包含`children`的节点~我以为是会正常渲染出404页面的！但实际上并没有！所以想请问一下大家，是我哪里配置有问题吗？

**Comment by xiaohuoni** [comment]
为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

**Comment by RobbsLuo** [comment]
当使用约定式路由时，  
会生成如下路由
![image](https://user-images.githubusercontent.com/11434009/97521580-d3aea300-19d8-11eb-9ae2-a99ccd9a7f53.png)
导致404页面失效
