### ISSUE TITLE
publicPath 和umi2不一致。在dev也生效了

### ISSUE THREAD

**Issue by KMBaby-zyl** [umijs/umi#4790]
umi2中 publicPath 只在build的时候生效， dev不生效。

umi3中 publicPath在dev也生效了。

**Comment by ycjcl868** [comment]
具体是指？

**Comment by KMBaby-zyl** [comment]
> 具体是指？
publicPath是期望正式环境走这个静态资源cdn地址。本地走 相对路径
配置： publicPath: 'https://baidu.com/'。 
yarn start 
页面中资源就变成了， https://baidu.com/umi.js 。 本地无法启动了

**Comment by codingbycat** [comment]
同样的问题，我希望打包后的文件使用publicPath，但是开发环境也使用了publicPath，配置了runtimePublicPath貌似也无效

**Comment by sorrycc** [comment]
可以这么配，

export default {
  ...(process.env.NODE_ENV==='production' && { publicPath: '/abc/' }),
}
