### ISSUE TITLE
How to use PWA on umi 3.0

### ISSUE THREAD

**Issue by nguyenhuutinh** [umijs/umi#4793]
Hello, 
wanna to know how to use pwa in 3.0

I tried but it seems that this option was removed.

Thank you

**Comment by sherry007** [comment]
因为项目中需要用 PWA 和 service worker，研究了一天，最终打通，以下是我的配置：

1. `umirc.js` 配置：需要安装插件 `workbox-webpack-plugin`
```javascript
// umirc.js
const { InjectManifest } = require('workbox-webpack-plugin');
export default {
  ...
  copy: [`/pwa/${manifestName}`],  // 这个需要提供 pwa 需要的 .webmanifest 文件，然后手动将其拷贝到构建之后的目录（dist）下
  links: [{ rel: 'manifest', href: `/console/${manifestName}` }], // 手动插入 .webmanifest 文件的 link
  chainWebpack(memo) {
    // workbox 配置
    memo.plugin('workbox').use(InjectManifest, [
      {
        swSrc: './pwa/service-worker.js',
        swDest: 'sw.js',
        exclude: [/\.map$/, /favicon\.ico$/, /^manifest.*\.js?$/],
      },
    ]);
  },
  ...
}
```
2. 创建文件 `register-service-worker.js`, 文件内容是注册 service worker，需要先安装插件 `register-service-worker` 哈：
```javascript
// register-service-worker.js
import { register } from 'register-service-worker';

function dispathServiceWorkerEvent(eventName) {
  const event = document.createEvent('Event');
  event.initEvent(eventName, true, true);
  window.dispatchEvent(event);
}

if (process.env.NODE_ENV === 'production') {
  register(`/console/sw.js`, { // 这个路径是根据你最终生成的 service worker 的文件路径来确定
    updated() {
      dispathServiceWorkerEvent('sw.updated');
    },

    offline() {
      dispathServiceWorkerEvent('sw.offline');
    },
  });
}
```
3. 将 `register-service-worker.js` 文件引入到你的 app 运行入口，我的话是在 global.js 中 引入了这个文件，反正就是在运行应用前先运行这个脚本对 service worker 进行注册
```javascript
// global.js
...
import './register-service-worker';
...
```
4. 这个验证的话，其实本地不太好验证，我们项目的话，是把项目放到 docker 里运行，然后暴露端口进去，是可以看到 sw.js 和 .webmanifest 文件；然后在平板运行的时候可以生成桌面应用
![image](https://user-images.githubusercontent.com/5960194/89148723-34bb0c00-d58d-11ea-9ea6-82d382721694.png)
![image](https://user-images.githubusercontent.com/5960194/89148794-5e743300-d58d-11ea-9060-1c6676ddbe0b.png)

最后，希望能够对你有所帮助，如果有问题，可以联系我

**Comment by yuanxuyan** [comment]
求大神赐教！！！！！！
![image](https://user-images.githubusercontent.com/34082804/91928409-8a124680-ed0e-11ea-9836-78cdb2a6bfd5.png)
用这种方法配置之后，service worker 激活成功了，但是把网断开或者更新sw文件之后都不触发注册的事件是为什么呢？刷新才会触发sw更新事件，而且报错了，不清楚是为什么？
![image](https://user-images.githubusercontent.com/34082804/91928436-99918f80-ed0e-11ea-9b05-68031cb5613c.png)
![image](https://user-images.githubusercontent.com/34082804/91928726-5b48a000-ed0f-11ea-8d51-71944e1771c8.png)

**Comment by sherry007** [comment]
> 求大神赐教！！！！！！
> ![image](https://user-images.githubusercontent.com/34082804/91928409-8a124680-ed0e-11ea-9836-78cdb2a6bfd5.png)
> 用这种方法配置之后，service worker 激活成功了，但是把网断开或者更新sw文件之后都不触发注册的事件是为什么呢？刷新才会触发sw更新事件，而且报错了，不清楚是为什么？
> ![image](https://user-images.githubusercontent.com/34082804/91928436-99918f80-ed0e-11ea-9b05-68031cb5613c.png)
> ![image](https://user-images.githubusercontent.com/34082804/91928726-5b48a000-ed0f-11ea-8d51-71944e1771c8.png)

叫大神言重了🤣，这个我查了一下，首先网络断开是不是本来就不会触发注册事件呢，更新sw文件的话应该是会触发更新事件的，但是你这个sw文件是不是构建之后的呀，你在哪里改了这个文件呢？我推荐你看一下[这篇文章](https://developers.google.com/web/fundamentals/primers/service-workers#update-a-service-worker)哦
我当时配置也只是稍微理解些类型为 `InjectManifest` 的，这种我可能不太了解怕给你说错了，不好意思呀~

**Comment by yuanxuyan** [comment]
谢谢！！！
本来是想实现build代码生成新版本的sw.js文件之后，浏览器不刷新在当前页就能感知到sw.js文件的更新，立马注册，但是后来查资料发现，并没有这样的功能，之恶能刷新之后才会重新注册。

**Comment by sherry007** [comment]
> 谢谢！！！
> 本来是想实现build代码生成新版本的sw.js文件之后，浏览器不刷新在当前页就能感知到sw.js文件的更新，立马注册，但是后来查资料发现，并没有这样的功能，之恶能刷新之后才会重新注册。

嗯嗯！不客气哦~

**Comment by jimStyle88** [comment]
@sherry007   大神你好，我在umi2.x  开启了Pwa  配置，在实际场景中发先，每次发布新版本之后，总有几个用法返回无法拉取到最新的js文件导致白屏，控制台报错（js 路径 404），目前还搞不懂为何没有触发update。 请大神支招，怎么平滑用户无感知的关闭PWA ，达到每次发布，不会有获取不到最新文件的问题出现。
目前的代码如下：
![image](https://user-images.githubusercontent.com/20588608/97127303-394e2580-1774-11eb-981b-2c54b551fe73.png)
望回复

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.

**Comment by Aloento** [comment]
@sherry007 大佬，我在用Ant Pro构建的时候遇到了这个错误
`Can't find self.__WB_MANIFEST in your SW source.`
请问如何解决？

**Comment by rianonehub** [comment]
> @sherry007 大佬，我在用Ant Pro构建的时候遇到了这个错误 `Can't find self.__WB_MANIFEST in your SW source.` 请问如何解决？

add this line on `service-worker.js` fix for me
`workbox.precaching.precacheAndRoute(self.__WB_MANIFEST || []);`

**Comment by W-yang-hhhhh** [comment]
@sherry007 你的那个.webmanifest文件 怎么生成的，还有文件的目录方便看一下么

**Comment by conioX** [comment]
any example or plugin to use umi pwa?

**Comment by sherry007** [comment]
> @sherry007 你的那个.webmanifest文件 怎么生成的，还有文件的目录方便看一下么

这个有模板文件，可以看 mdn 这篇 https://developer.mozilla.org/zh-CN/docs/Web/Manifest ；这个文件被我放到了 root 目录下的 pwa 文件夹下的
![image](https://user-images.githubusercontent.com/5960194/154025702-d2855601-adb4-42a1-a28a-97595c8df048.png)

**Comment by sambhav2612** [comment]
any updates on this? can't seem to get the manifest registered with the service worker

**Comment by sherry007** [comment]
> 

Hi, I want to know if you have created the manifest file and config the "links" in `umirc` as I said

**Comment by shenyinabcd** [comment]
我是这样解决的（Ant design Pro V5）：
`npm install workbox-webpack-plugin`

在 config.ts 中


```
import { InjectManifest, GenerateSW } from 'workbox-webpack-plugin';

export default defineConfig({
  define: {
    // 注入到浏览器环境的变量（必须显式定义）
    'process.env.REACT_APP_ENV': process.env.REACT_APP_ENV || 'dev',
  },

  copy: ['./src/manifest.json'],
  links: [
    { rel: 'manifest', href: 'manifest.json' },
    { rel: 'icon', href: './favicon.ico' },
  ],
  chainWebpack: (memo, args) => {
    memo.plugin('workbox').use(GenerateSW, [
      {
        cacheId: 'webpack-pwa', // 设置前缀
        skipWaiting: true, // 强制等待中的 Service Worker 被激活
        clientsClaim: true, // Service Worker 被激活后使其立即获得页面控制权
        cleanupOutdatedCaches: true, //删除过时、老版本的缓存
        swDest: 'service-wroker.js', // 输出 Service worker 文件
        include: ['**/*.{html,js,css,png.jpg}'], // 匹配的文件
        exclude: ['service-wroker.js'], // 忽略的文件
        runtimeCaching: [
          {
            urlPattern: /.*\.js.*/i,
            handler: 'NetworkFirst',
            options: {
              cacheName: 'seed-js',
              expiration: {
                maxEntries: 20, //最多缓存20个，超过的按照LRU原则删除
                // maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
                maxAgeSeconds: 1 * 24 * 60 * 60, // 1 day
              },
            },
          },
          {
            urlPattern: /.*css.*/,
            handler: 'NetworkFirst',
            options: {
              cacheName: 'seed-css',
              expiration: {
                maxEntries: 30, //最多缓存30个，超过的按照LRU原则删除
                // maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
                maxAgeSeconds: 30 * 24 * 60 * 60, // 1 day
              },
            },
          },
          {
            urlPattern: /.*(png|svga).*/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'seed-image',
              expiration: {
                maxEntries: 30, //最多缓存30个，超过的按照LRU原则删除
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
              },
            },
          },
        ],
      },
    ]);
  },

...
})
```

see these links:

[https://github.com/umijs/umi/issues/4793](url)

[https://github.com/umijs/umi/issues/7721](url)
