### ISSUE TITLE
路由配置文件中 component 和 routes 是互斥的

### ISSUE THREAD

**Issue by miaojinxing** [umijs/umi#4797]
![image](https://user-images.githubusercontent.com/65324519/83289197-4394e380-a217-11ea-833c-6976c547fe86.png)

如图，当存在component存在 那么它的子路由 routes 就失效了 ,这种路由方案不是应该合理存在且普遍的吗 。

**Comment by ahayaSKBINCN** [comment]
这个不是umi的问题，应当是你配置文件写的有问题  可以试试添加exact 保证子路由的优先级跟高

**Comment by miaojinxing** [comment]
> 这个不是umi的问题，应当是你配置文件写的有问题 可以试试添加exact 保证子路由的优先级跟高
感谢回应 ,
![image](https://user-images.githubusercontent.com/65324519/83324717-c2cafb80-a299-11ea-9558-3cbc6b7b05aa.png)
是否是这样，这样也是匹配不上的，当1级或上级存有component那么即使存在子路由那么也是匹配不上的, 
能否提供一下你的demo.

**Comment by xiaohuoni** [comment]
不要发一摸一样的问题https://github.com/umijs/umi/issues/4800

**Comment by ahayaSKBINCN** [comment]
@xiaohuoni 这个错误应当被修复  patg =>path   umijs v3 里面有太多这种错误
{
            "name": "children",
            "icon": "user",
            "patg": "/user/login/children",
            "component": dynamic({ loader: () => import(/* webpackChunkName: 'p__children__index' */'/Users/ahaya/work_space/test/src/pages/children/index'), loading: require('@/components/PageLoading/index').default}),
            "exact": true
          },

**Comment by ahayaSKBINCN** [comment]
由于某些约定的原因  你这样写会匹配不到  至少在umijs 中是这样。 把routes 里的东西提出来 添加exact 如果出现匹配问题  仔细检查下缓存文件.umi 里面有没有出现上面的问题
