### ISSUE TITLE
预渲染后覆盖 index.html，造成没有默认 HTML 模板

### ISSUE THREAD

**Issue by ycjcl868** [umijs/umi#4798]
## What happens?

预渲染后，生成出来的 HTML 都是经过渲染后的，没有一个默认能 CSR 的 HTML 兜底模板。

就会造成像 umi 官网样，访问不存在的路由，前端路由跳转，样式不正常的现象

![image](https://user-images.githubusercontent.com/13595509/83318683-9b5c3a80-a269-11ea-8264-70b7ead8c8fd.png)

本质原因是，预渲染后，如果开发者不通过跳转逻辑干预，没办法回退到默认 HTML 模板， 走 CSR 客户端渲染

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by sorrycc** [comment]
bug or feature?

**Comment by ycjcl868** [comment]
feature，应该有解法，从两个角度：
- 不覆盖 `index.html`，怎样解决首页路由与 预渲染 HTML 模板 的映射？
- 提供一个 `default.html` 作为默认模板，但需要用户手动去映射不匹配路由到这个模板

**Comment by hz251** [comment]
@ycjcl868 如何生成default.html？
