### ISSUE TITLE
Config parameters in route '/search/person/:query/:n'

### ISSUE THREAD

**Issue by elivoa** [umijs/umi#48]
I can create page file pages/search/person.js to match /search/person.html
Can I put parameters in url?
/search/person/:query/:n

I did this before with react-rotuer:

```javascript
  User: {
    path: '/user/:id',
    models: () => [import('models/user/detail')],
    component: () => import('./detail/'),
  },   
```

**Comment by elivoa** [comment]
When will you fix this issue? I will make my dev play based on that. thanks.

**Comment by sorrycc** [comment]
Maybe next week, we have not decided which solution to use.

**Comment by sorrycc** [comment]
It's supported via umi@1.0.0-rc.1, please checkout out [Router Config](https://umijs.org/docs/zh-Hans/router.html) for more detail.
