### ISSUE TITLE
umi router配置存在明显缺陷 

### ISSUE THREAD

**Issue by miaojinxing** [umijs/umi#4800]
![image](https://user-images.githubusercontent.com/65324519/83327010-43462800-a2ab-11ea-9b37-d044fd6c49ce.png)
如图，当1级存在component 那么他的子路由匹配全部失效，当启用精确匹配 也仅能匹配1级路由，子路由全部为404，另外建议官网文档写详细点，文献太少，以实际业务出发。

**Comment by MyCupOfTeaOo** [comment]
? 你这个exact 应该是false,你应该去看 react-router文档

**Comment by miaojinxing** [comment]
> ? 你这个exact 应该是false,你应该去看 react-router文档

无论是false还是true 这种嵌套都是无法得到正常渲染的 ，如果我写法有错误，请大佬指出。

**Comment by xiaohuoni** [comment]
为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN
