### ISSUE TITLE
开启layout后，浏览器回退操作时，回退到的页面的useEffect先于onRouteChange执行

### ISSUE THREAD

**Issue by vdfor** [umijs/umi#4801]
## What happens?

开启layout后，浏览器回退操作时，回退到的页面的useEffect先于onRouteChange执行

## Mini Showcase Repository(REQUIRED)

https://github.com/vdfor/umi-issues-demo/tree/master/route-change-with-layout

## How To Reproduce

1） umi开启layout配置
2）进入A页面，A页面某个点击进入到B页面
3）点击浏览器回退，回退到A页面，会发现A页面的 `useEffect` 先于 运行时配置的 `onRouteChange` 运行 

## Context

- **Umi Version**: v3.2.3
- **Node Version**: v12.16.2
- **Platform**: windows 10 / Microsoft Edge 83 (chromium内核)

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.

**Comment by wumx** [comment]
没人解决吗
