### ISSUE TITLE
umi的dva配置文档错误

### ISSUE THREAD

**Issue by mytheart** [umijs/umi#4802]
![image](https://user-images.githubusercontent.com/42933010/83341850-ae7b1300-a31a-11ea-938b-d186abe41ce2.png)
![image](https://user-images.githubusercontent.com/42933010/83341848-aa4ef580-a31a-11ea-8746-930315009b8e.png)

**Comment by xiaohuoni** [comment]
没错的，这里只是演示怎么配置 dva
