### ISSUE TITLE
项目一开始启用了pwa，现在不想用缓存，想要卸载service work该怎么操作？

### ISSUE THREAD

**Issue by lumia2046** [umijs/umi#4803]
启用pwa后，每次项目部署更新，都要过一会才会刷新页面，这个用户体验非常不好。
我现在项目打包代码启用了hash，然后也禁用了pwa，更新部署后发现项目必须手动清理一次缓存才能去掉service work。如果用户不清缓存，因为有之前的service work在，就永远拿不到最新代码了，这真是超级坑，有没有什么办法可以解决呢？

**Comment by wmzhong** [comment]
可以先上一版取消注册的 service-worker.js 去 
`unregister`

**Comment by iceberg211** [comment]
umi2的官网就有这个问题

**Comment by jimStyle88** [comment]
> 可以先上一版取消注册的 service-worker.js 去
> `unregister`

 if ('serviceWorker' in navigator) {
  // unregister service worker
  const { serviceWorker } = navigator;
  if (serviceWorker.getRegistrations) {
    serviceWorker.getRegistrations().then(sws => {
      sws.forEach(sw => {
        sw.unregister();
      });
    });
  }
  serviceWorker.getRegistration().then(sw => {
    if (sw) sw.unregister();
  });

  // remove all caches
  if (window.caches && window.caches.keys) {
    caches.keys().then(keys => {
      keys.forEach(key => {
        caches.delete(key);
      });
    });
  }

这样操作，还是能看到某些静态文件来自 service worker
