### ISSUE TITLE
@umijs/preset-react v1.5.5中的plugin-layout异常报错

### ISSUE THREAD

**Issue by cryst4lMao** [umijs/umi#4804]
## 想要 ant-design-pro 的布局，在添加了layout: {}后，出现“@umijs/plugin-layout 需要安装 ProLayout 才可运行”的异常报错。
尝试了将“@umijs/preset-react”降到”1.4.19“，关联的"@umijs/plugin-layout"为"0.10.0"，系统恢复正常现实。
怀疑是在之前@umijs/plugin-layout@0.10.0之后某一个版本中有问题

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：3.2.3
- **Node 版本**：12.16.2
- **操作系统**：osx 10.15.1

**Comment by io-o** [comment]
我也遇到这种情况。。。。

**Comment by io-o** [comment]
现在还没修复

**Comment by leftstick** [comment]
目前可以手动安装`yarn add @ant-design/pro-layout`

**Comment by chenshuai2144** [comment]
有报错信息吗？
