### ISSUE TITLE
获取自定义变量

### ISSUE THREAD

**Issue by TangTangJia** [umijs/umi#4806]
配置了
`  define: {
    "process.env.REACT_APP_API_URL": process.env.REACT_APP_API_URL
  },`
但是console.log(process.env.REACT_APP_API_URL)为undefined

**Comment by leftstick** [comment]
不是这么玩的啊，文档看漏了吧？

![Screen Shot 2020-06-01 at 17 45 43](https://user-images.githubusercontent.com/1059956/83397169-bbd5f180-a42f-11ea-9fc9-0721feeb4770.png)


所以你应该配置：

```typescript
{
  define: {
    REACT_APP_API_URL: process.env.REACT_APP_API_URL
  }
}
```

然后使用

```typescript
console.log(REACT_APP_API_URL)
```

**Comment by TangTangJia** [comment]
> 不是这么玩的啊，文档看漏了吧？
> 
> ![Screen Shot 2020-06-01 at 17 45 43](https://user-images.githubusercontent.com/1059956/83397169-bbd5f180-a42f-11ea-9fc9-0721feeb4770.png)
> 
> 所以你应该配置：
> 
> ```ts
> {
>   define: {
>     REACT_APP_API_URL: process.env.REACT_APP_API_URL
>   }
> }
> ```
> 
> 然后使用
> 
> ```ts
> console.log(REACT_APP_API_URL)
> ```

我也试过的，打印出来都是undefined，只有给它赋值一个具体的值才能打印

**Comment by leftstick** [comment]
这个我确认没有问题，启动用`REACT_APP_API_URL=fuckfuck yarn start`，代码里 console就有值了。

如果你那边不工作，提供可复现repo

**Comment by TangTangJia** [comment]
> 这个我确认没有问题，启动用`REACT_APP_API_URL=fuckfuck yarn start`，代码里 console就有值了。
> 
> 如果你那边不工作，提供可复现repo
![image](https://user-images.githubusercontent.com/34622385/83587010-8987d980-a580-11ea-9cc7-427dee5c34ed.png)
![image](https://user-images.githubusercontent.com/34622385/83587026-94db0500-a580-11ea-818a-dbfb482fec2f.png)
![image](https://user-images.githubusercontent.com/34622385/83587063-b3410080-a580-11ea-984e-dac7865975c5.png)
就很难受，不知道到底是哪里的打开方式有问题

**Comment by qduld** [comment]
我有同样的问题 想在fetch的过滤器里加环境变量判断一直取不到
![捕获](https://user-images.githubusercontent.com/23184084/84565054-2cb6cb00-ad99-11ea-8be5-487e842fa0c5.PNG)

**Comment by qduld** [comment]
// https://umijs.org/config/
import { defineConfig } from 'umi';
import defaultSettings from './defaultSettings';
import proxy from './proxy';
const { REACT_APP_ENV } = process.env;
export default defineConfig({
  history: { type: 'hash' },
  hash: true,
  antd: {},
  dva: {
    hmr: true,
  },
  locale: {
    // default zh-CN
    default: 'zh-CN',
    // default true, when it is true, will use `navigator.language` overwrite default
    antd: true,
    baseNavigator: true,
  },
  dynamicImport: {
    loading: '@/components/PageLoading/index',
  },
  targets: {
    ie: 11,
  },
  define: {
    REACT_APP_ENV: REACT_APP_ENV || false
  },
  proxy: proxy[REACT_APP_ENV || 'dev'],
  manifest: {
    basePath: '/',
  },
});

**Comment by kyssion** [comment]
+1 我也遇到了同样的问题

**Comment by azhen98** [comment]
看你的截图好像vue的使用方式 ,vue会自动读取.env文件 不知道design 会不会读取
这个define就是加一个全局变量,你可以这样实现
```JavaScript
let isProduct = process.env.NODE == 'production'
define: {
    REACT_BASE_URL: isProduct ? '生产环境' : '开发环境'
  },
```
