### ISSUE TITLE
[Feature]base前缀路由不支持动态参数

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#4811]
## What happens?

如图所示，base只能是固定的字符串
![image](https://user-images.githubusercontent.com/7939085/83472951-0e102480-a4bb-11ea-8615-d5ecb139ef2e.png)
实际应用场景中，应该经常存在动态参数的情况，是不是考虑支持一下动态参数的情况？
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by xiexingen** [comment]
或者支持在运行时指定base

**Comment by xiaohuoni** [comment]
是希望像 https://umijs.org/config#runtimepublicpath 类似的 runtimeBase 嘛？

**Comment by xiexingen** [comment]
还不是，使用场景比如
正常情况下部署是通过子域名来区分不同企业端
比如:
http://test.umi.com
某些情况下需要变成这样
www.umi.com/test
www.umi.com/develop
此处 test、develop用来区分不同的企业端
进去app.js文件的时候在render里面先即系出这个基础路由再请求数据，目前umi里面基础路只能是固定死的，不能是动态变化的

**Comment by xiaohuoni** [comment]
没太明白，你这个不同的企业端，是有重复部署嘛？

**Comment by xiexingen** [comment]
相当于sass模式
正常情况咯，是通过子域名来区别不同的企业端
但是一些特殊情况，想通过这个前缀路由来算作不同的企业端，然后目前umi的前缀路由只能是固定的值，不能是动态的
期望的结果:
目前的umi 前缀路由支持动态形式
然后再app.ts里面去解析url上的这个动态路由，再向后端请求 
不知道我表达清楚没

**Comment by xiaohuoni** [comment]
我还是没明白 @sorrycc cc

**Comment by xiexingen** [comment]
以umijs.org为例
假如，为umijs.org设置了一个前缀路由，比如ui
那么部署后，访问的首页地址就是umijs.org/ui  而且只能是umijs.org/ui
其实就是想这个ui这个前缀可以是动态的，比如输入umijs.org/ui   umijs.org/component   umijs.org/style 都可以正常用

**Comment by sorrycc** [comment]
需要由服务端控制 html 输出，在 html 里输出不同的 base，然后切换时刷页面。

**Comment by smilehht** [comment]
有类似的需求，希望动态支持base路径的修改

**Comment by git-lt** [comment]
> 是希望像 https://umijs.org/config#runtimepublicpath 类似的 runtimeBase 嘛？

这种要怎么实现？接入 qiankun的情况下，做为子应用访问和单独访问，base是不一样的，需要在运行时动态设置

**Comment by twinkle77** [comment]
接入 qiankun的情况下，做为子应用访问和单独访问，base是不一样的，需要在运行时动态设置
@git-lt  同样的需求，请问最后是怎么解决的？

**Comment by wangcheng007** [comment]
> 接入 qiankun的情况下，做为子应用访问和单独访问，base是不一样的，需要在运行时动态设置 @git-lt 同样的需求，请问最后是怎么解决的？
同问，这个问题怎么解决？

**Comment by wangcheng007** [comment]
> 接入 qiankun的情况下，做为子应用访问和单独访问，base是不一样的，需要在运行时动态设置 @git-lt 同样的需求，请问最后是怎么解决的？

同问想问下怎么解决的 @twinkle77

**Comment by 16slowly** [comment]
有类似的需求，希望动态支持base路径的修改

> 有类似的需求，希望动态支持base路径的修改

**Comment by 16slowly** [comment]
> 接入 qiankun的情况下，做为子应用访问和单独访问，base是不一样的，需要在运行时动态设置 @git-lt 同样的需求，请问最后是怎么解决的？

➕1，最后是怎么解决的啊

**Comment by gnatecheng** [comment]
工作中也遇到这个问题，有解决方案了么？
