### ISSUE TITLE
umi3在启用dva写了model之后会自动引入antd样式

### ISSUE THREAD

**Issue by a3538333** [umijs/umi#4812]
umi3在启用dva写了model之后会自动引入antd样式,删除model之后就正常了,会引入
mode_modules/antd/es/style/index.less
请问这个原因是因为我配置不对吗,还是什么情况?
即使不引入model, 只是写了model放到了src/models下,框架就会自动引入这个样式
umi: umi@3.1.4
node: v12.13.1

**Comment by fuwh233** [comment]
同样的问题

**Comment by xiaohuoni** [comment]
类似的问题，一起讨论吧。https://github.com/umijs/umi/issues/4813
