### ISSUE TITLE
umi3开启antd配置后，仅使用antd-mobile库会默认加载antd的基本样式

### ISSUE THREAD

**Issue by bobbychan** [umijs/umi#4813]
## What happens?

我在项目中用的是antd-mobile，在umi3的配置文件里加上antd: {}，在没有导入任何antd组件的情况下会默认加载antd库的node_modules/antd/es/style/index.less样式

## 相关环境信息

- **Umi 版本**：3.2.3
- **Node 版本**：12.16.3
- **操作系统**：windows 10

**Comment by sorrycc** [comment]
检查了下插件源码，理论上不会，给复现我看下。

**Comment by zwj7181** [comment]
可能是插件@umijs/plugin-request有用antd

**Comment by bobbychan** [comment]
用umi脚手架新建了个项目，又没有加载antd了

**Comment by bobbychan** [comment]
> 可能是插件@umijs/plugin-request有用antd

**Comment by bobbychan** [comment]
> 可能是插件@umijs/plugin-request有用antd

的确是这样，我在配置里加上request: false就不会加载antd的样式了

**Comment by bobbychan** [comment]
> 检查了下插件源码，理论上不会，给复现我看下。

好像是插件@umijs/plugin-request有引入antd引起的问题

**Comment by margitoxis** [comment]
```ts
import { message, notification } from 'antd';

switch (errorInfo?.showType) {
  case ErrorShowType.SILENT:
    // do nothing
    break;
  case ErrorShowType.WARN_MESSAGE:
    message.warn(errorMessage);
    break;
  case ErrorShowType.ERROR_MESSAGE:
    message.error(errorMessage);
    break;
  case ErrorShowType.NOTIFICATION:
    notification.open({
      message: errorMessage,
    });
    break;
  case ErrorShowType.REDIRECT:
    // @ts-ignore
    history.push({
      pathname: errorPage,
      query: { errorCode, errorMessage },
    });
    // redirect to error page
    break;
  default:
    message.error(errorMessage);
    break;
}
```
能否支持自定义全局通知的方法
只使用 antd-mobile，在手机上弹出 `notification` 就不太友好

*如果再使用 qiankun 还会有坑（样式冲突）*

**Comment by xiaohuoni** [comment]
@margitoxis 需要自定义只要重写覆盖一下 errorHandler 就可以。

**Comment by xiaohuoni** [comment]
这里跟进 https://github.com/umijs/plugins/issues/371
