### ISSUE TITLE
基于约定路由配置为什么会出现类似“xx/inherit” 类似的资源请求

### ISSUE THREAD

**Issue by TRUEJASONFANS** [umijs/umi#4821]
## What happens?

访问某一个约定路由页面的时候

## Mini Showcase Repository(REQUIRED)

由于是私人仓库无法直接贴上来。。

## How To Reproduce

![image](https://user-images.githubusercontent.com/5670289/83591042-a07ef980-a589-11ea-8ccc-529189660c83.png)

## Context

- **Umi Version**: "^2.9.0",
- **Node Version**:  ">=8.0.0"
- **Platform**: chrome, spring boot + UMI

**Comment by xiaohuoni** [comment]
没看到过类似的，你看看是不是你自己的代码发起的请求？

**Comment by TRUEJASONFANS** [comment]
![image](https://user-images.githubusercontent.com/5670289/112280709-438f3400-8cc0-11eb-82a1-5b0ec6297ecc.png)
@xiaohuoni  感觉是antd 发起的， 之前一直以为是umi
