### ISSUE TITLE
使用了APP_ROOT后， absNodeModulesPath路径不对

### ISSUE THREAD

**Issue by KMBaby-zyl** [umijs/umi#4830]
## What happens?
项目目录结构
- node_modules
- packages
  - a
    - .umirc
  - b
     - .umirc
- package.json

执行
APP_ROOT=packages/a  umi build
此时 插件api中的 absNodeModulesPath 是packages/a/node_modules

**Comment by sorrycc** [comment]
为啥不对？导致了啥问题？

**Comment by KMBaby-zyl** [comment]
> 为啥不对？导致了啥问题？

我是多umi 多spa的项目。2个umi项目在一个代码库。
absNodeModulesPath 期望是项目根目录下面的不是在 子项目a 下面

**Comment by xiaohuoni** [comment]
我觉得现在的逻辑是正确的。
