### ISSUE TITLE
请问如何配置 rules

### ISSUE THREAD

**Issue by bin-sun** [umijs/umi#4832]
## What happens?
当前想在项目中使用 thread-loade 和 speed-measure-webpack-plugin，但是看了官方文档后无从下手，自己摸索写一直报错。。。speed-measure-webpack-plugin需要在webpack对象的最外层包一下，请问最外层对象在哪里？thread-loade看官方文档在module里配置，也没有找到配置入口
module: {
    rules: [
      {
        test: /\.js$/,
        include: path.resolve("src"),
        use: [
          "thread-loader",
          // your expensive loader (e.g babel-loader)
        ]
      }
    ]
  }

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：2.7.7
- **Node 版本**：12.16.1
- **操作系统**：win

**Comment by leftstick** [comment]
你用这些插件貌似是想优化编译的速度?

按理说，这个事情应该交给 umi 来处理的，你不需要这么搞。

换句话说，如果你都要用这些工具来 『额外帮助umi』 提升性能了，说明你可能更需要一个自组的框架

**Comment by caoxiemeihao** [comment]
> 你用这些插件貌似是想优化编译的速度?
> 
> 按理说，这个事情应该交给 umi 来处理的，你不需要这么搞。
> 
> 换句话说，如果你都要用这些工具来 『额外帮助umi』 提升性能了，说明你可能更需要一个自组的框架

编译速度提上给个思路，大佬

**Comment by caoxiemeihao** [comment]
> > 你用这些插件貌似是想优化编译的速度?
> > 按理说，这个事情应该交给 umi 来处理的，你不需要这么搞。
> > 换句话说，如果你都要用这些工具来 『额外帮助umi』 提升性能了，说明你可能更需要一个自组的框架
> 
> 大佬，如何提示编译速度，给个思路呗

我用的 umi@3.x 已经按照官方的 guide 配置，打包速度大幅度提升；
1.esbuild
2.webpack splitChunks

**Comment by iamwjj** [comment]
speed-measure-webpack-plugin可以在chainWebpack里这样配置：
```
{
  chainWebpack(config, { env, webpack }) {
    // ...其他config
    const wrappedConfig = smp.wrap(config.toConfig())
    config.toConfig = () => wrappedConfig
  }
}
```

**Comment by AmorDiamond** [comment]
`
chainWebpack(config, { webpack }) {
  config.module
    .rule('ts-in-node_modules')
    .use('thread-loader')
    .loader('thread-loader')
    .options({
      workers: 2,
    })
    .before('babel-loader');
  config.module
    .rule('js-in-node_modules')
    .use('thread-loader')
    .loader('thread-loader')
    .options({
      workers: 2,
    })
    .before('babel-loader');
}
`
这样添加了thread-loader，通过config.toConfig()获取到的的配置也是成功了的，不过打包看不出来任何效果
