### ISSUE TITLE
使用umi时能编译成功但是开发服务器无法启动是啥原因呀

### ISSUE THREAD

**Issue by SiberianHuskyL** [umijs/umi#4833]
## 使用umi时能编译成功但是开发服务器无法启动?
![image](https://user-images.githubusercontent.com/29498245/83721143-1019e500-a66d-11ea-8375-94c3c3478633.png)

**Comment by leftstick** [comment]
无法启动是什么意思，页面不能访问？

**Comment by xiaohuoni** [comment]
可以尝试删掉 src/.umi 重新启动。

**Comment by xiaohuoni** [comment]
为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN
