### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by six-666** [umijs/umi#4834]
报错信息
```
Module parse failed: Unexpected token (21:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| const PageLoading = () => (
>   <div style={style}>
|     <Spin size="large" />
|   </div>

 @ ./src/layouts/UserLayout.jsx 9:0-46
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./node_modules/@umijs/bundler-webpack/lib/getConfig/runtimePublicPathEntry.js ./src/.umi/umi.ts
```

原因是引入当前项目外的组件报错
```
import Loading from '../../../../../../../PageLoading'
```

当把 PageLoading 组件移动到当前项目的 src 下就正常 ， 这要怎么处理？

**Comment by sorrycc** [comment]
如果是 ts 文件，可以用以下配置，

```js
chainWebpack(memo) {
  memo.module.rule('ts-in-node_modules').include.clear();
  return memo;
},
```

**Comment by six-666** [comment]
@sorrycc   不是ts， 请问怎么解决呢，比较急！

**Comment by sorrycc** [comment]
ts-in-node_modules 换成 js-in-node_modules。

**Comment by six-666** [comment]
@sorrycc  不行诶 ，同样的错误，解析不了 jsx

**Comment by sorrycc** [comment]
jsx 用前面的配置，自己多试试。

**Comment by six-666** [comment]
@sorrycc 试过了，

```js
chainWebpack(memo) {
    memo.module.rule('jsx-in-node_modules').include.clear();
    memo.module.rule('js-in-node_modules').include.clear();
    return memo;
  },
```

**Comment by smddzcy** [comment]
From what I understand, you're trying to transpile modules in `node_modules`. I have the same issue and I'm trying to find a solution.

```
chainWebpack(memo) {
  memo.module.rule('ts-in-node_modules').include.clear();
  return memo;
},
```

This or `js-in-node_modules` didn't work. What can I do? @sorrycc

**Comment by wellenzhong** [comment]
> From what I understand, you're trying to transpile modules in `node_modules`. I have the same issue and I'm trying to find a solution.
> 
> ```js
> chainWebpack(memo) {
>   memo.module.rule('ts-in-node_modules').include.clear();
>   return memo;
> },
> ```
> 
> This or `js-in-node_modules` didn't work. What can I do? @sorrycc

same issue

**Comment by miaozilong** [comment]
同样的问题,有大佬解决吗?

**Comment by likepearl** [comment]
chainWebpack(memo) {
    memo.module.rule('js').include.clear();
    return memo;
  }

我这样配的，可以
