### ISSUE TITLE
安装 umi-plugin-cache-route

### ISSUE THREAD

**Issue by lovesL** [umijs/umi#4835]
![image](https://user-images.githubusercontent.com/27960630/83741696-1e76f980-a68b-11ea-8013-b256d74ba163.png)

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：3.1.2
- **Node 版本**：v12.16.1
- **操作系统**： mac

**Comment by xjh22222228** [comment]
React实现路由缓存目前还没有比较完善的方案，可以考虑 [use-keep-state](https://github.com/xjh22222228/use-keep-state) ,  hooks 方案比较完善

**Comment by sorrycc** [comment]
这个插件非官方维护，请到插件的 issue 里提问。
