### ISSUE TITLE
umi打包后ant design 样式丢了

### ISSUE THREAD

**Issue by SmartWrh** [umijs/umi#4836]
umi 相关配置

`lessLoader: { javascriptEnabled: true },
  cssLoader: {
    localsConvention: 'camelCase',
  },`

某一个页面用到了图表组件，引入了
`
import 'antd/dist/antd.css';
import 'ant-design-pro/dist/ant-design-pro.css';
`

本地运行时没有异常，打包后样式丢失

**Comment by sorrycc** [comment]
需要复现步骤。

**Comment by SmartWrh** [comment]
您好，这是我本地运行时的效果
![image](https://user-images.githubusercontent.com/12826628/83827876-e797f680-a711-11ea-8e1e-971f947c102b.png)
这是打包后的效果运行 npm build
![image](https://user-images.githubusercontent.com/12826628/83828015-3e053500-a712-11ea-9894-1af25232f670.png)
@sorrycc

**Comment by sorrycc** [comment]
没有复现步骤解决不了你的问题。

**Comment by SmartWrh** [comment]
sorry,已经解决是我本地代码的问题，可以关闭此问题 @sorrycc

**Comment by thomaszdxsn** [comment]
> sorry,已经解决是我本地代码的问题，可以关闭此问题 @sorrycc

请问最后查明是什么问题？我也碰到了

**Comment by SmartWrh** [comment]
@thomaszdxsn css写的有问题，opacity 最开始写的 100% ~ 0% 打包发现不生效，要用 1.0 ~ 0.1

**Comment by thomaszdxsn** [comment]
> @thomaszdxsn css写的有问题，opacity 最开始写的 100% ~ 0% 打包发现不生效，要用 1.0 ~ 0.1

那和我不是同一个问题哦。我打包后没有看到我要的css

**Comment by coder-chin** [comment]
> > @thomaszdxsn css写的有问题，opacity 最开始写的 100% ~ 0% 打包发现不生效，要用 1.0 ~ 0.1
> 
> 那和我不是同一个问题哦。我打包后没有看到我要的css

我的css也失效了，请问还记得怎么解决的嘛
