### ISSUE TITLE
如何使用懒加载

### ISSUE THREAD

**Issue by adminparry** [umijs/umi#4837]
import { dynamic } from 'umi';
export default dynamic({
  loader: async function() {
    // 这里的注释 webpackChunkName 可以指导 webpack 将该组件 HugeA 以这个名字单独拆出去
    const { default: HugeA } = await import(/* webpackChunkName: "external_A" */ './HugeA');
    return HugeA;
  },
});

给的例子是这样的

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  routes: [
    {
      path: '/', component: import('@/pages/index'),
    },
    {
      path: '/test', component: dynamic({
  loader: async function () {
    // 这里的注释 webpackChunkName 可以指导 webpack 将该组件 HugeA 以这个名字单独拆出去
    const { default: HugeA } = await import(/* webpackChunkName: "external_A" */ "@/pages/test/test");
    return HugeA;
  },
})
    },
    
  ],
});

webpack 给的方案挺好的 路由懒加载非常好 到umi里怎么玩

**Comment by sorrycc** [comment]
配 `dynamicImport: {}`。

**Comment by adminparry** [comment]
dynamicImport是配置loading路由的 

老哥 antd-pro的组件文档该做了 比如@ant-design/pro-table 现在只能在npm上看个大概
