### ISSUE TITLE
umi3如何配置drop_console？

### ISSUE THREAD

**Issue by zoffyzhang** [umijs/umi#4840]
## What happens?

我配置了去除 console ，但打包后还是存在 console

```
  terserOptions: {
    compress: {
      drop_console: true,
      drop_debugger: true,
    },
  },
```

而且我希望开发模式保留 console，生产模式才去除 console，应该怎么做？

 
## 相关环境信息

- **Umi 版本**：3.2.3
- **Node 版本**：12.15.0
- **操作系统**：win10

**Comment by zoffyzhang** [comment]
去掉配置 `esbuild: {},`就可以生效了

而且开发模式自动保留console和debugger，生成模式才去除，感觉有点贴心，又有点混乱

**Comment by xiaohuoni** [comment]
和 esbuild 配置有关吗？

**Comment by conkyliu** [comment]
esbuild开不开我这生产环境都有log

**Comment by zoffyzhang** [comment]
> 和 esbuild 配置有关吗？

刚刚加上esbuild试了下，umi build 会把 `console.log('')` 编译成 `console.log("")`，不会去除

**Comment by iamwjj** [comment]
啊这个issue为什么关掉了，问题还存在。
升级到了3.3.7，也没有配置esbuild，生产环境还是有log

**Comment by zhuibo66** [comment]
实际测试：
umi version: 3.5.20
1、先去除根目录下的`config`文件下的`config.ts`/`config.js`文件里面的`esbuild: {}`配置
2、然后添加如下代码：

```
terserOptions: {
  compress: {
    drop_console: true,
  },
},
```
如上操作后，就可以去除console一类的注释了，但是我自己比较好奇的是，为什么要去除`esbuild: {}`配置，难道这是个隐藏性bug吗？

**Comment by tomatobybike** [comment]
> terserOptions

terserOptions 是使用terser压缩打包的配置，不去处esbuild:{},默认认为是使用esbuild来作为压缩引擎压缩代码， terser的配置是无效的

**Comment by maqinghao** [comment]
如果使用esbuild,有什么方法去除console呢?
