### ISSUE TITLE
TS提示connect组件缺少属性location, history, route

### ISSUE THREAD

**Issue by Cliff-Rhine** [umijs/umi#4849]
按照官方dva插件给的page用例，使用`extends ConnectProps`或是`ConnectRC`，导出的组件TS报错：

在`src/pages/index.tsx`中引用的ShowCount组件就报错，划红线的地方，页面能正常运行，工作正常，就是编辑器里报错，编辑器是vscode
![image](https://user-images.githubusercontent.com/48267247/83945530-d2b88180-a83d-11ea-8162-a88b7ad81112.png)

报错内容
```
Type '{}' is missing the following properties from type 'Pick<PageProps, "match" | "location" | "history" | "route">': location, history, routets(2739)
```
想知道是怎么回事，有什么解决办法

代码贴下面
src/models/count.ts
```javascript
import { ImmerReducer } from 'umi';
export interface CountState {
  count: number;
}
export interface CountModalType {
  namespace: string;
  state: CountState;
  reducers: {
    add: ImmerReducer<CountState>;
  }
}
const CountModal: CountModalType = {
  namespace: 'count',
  state: {
    count: 0
  },
  reducers: {
    add(state) {
      state.count = state.count + 1
    }
  }
}
export default CountModal
```
src/pages/components/count.tsx
```javascript
import React, { FC } from 'react'
import { ConnectProps, connect, CountState } from 'umi';
interface PageProps extends ConnectProps {
  count: number;
}
const mapStateToProps = ({ count }: { count: CountState }) => {
  return { count: count.count }
}
const ShowCount: FC<PageProps> = ({ count }) => {
  return <div>{count}</div>
}
export default connect(mapStateToProps)(ShowCount)
```
src/pages/index.tsx
```javascript
import React from 'react'
import ShowCount from './components/count'
import { Button } from 'antd'
import { useDispatch } from 'umi'
const App = () => {
  const dispatch = useDispatch()
  return (
    <div>
      <ShowCount></ShowCount>
      <Button onClick={() => { dispatch({ type: 'count/add' }) }}>ADD</Button>
    </div>
  )
}
export default App
```

**Comment by j172993563** [comment]
import React, { FC } from 'react'
import { ConnectProps, connect, CountState } from 'umi';
interface PageProps extends ConnectProps {
  count: number;
}
const mapStateToProps = ({ count }: { count: CountState }) => {
  return { count: count.count }
}
const ShowCount: FC<PageProps> = ({ count }) => {
  return <div>{count}</div>
}
export default connect<PageProps>(mapStateToProps)(ShowCount)

**Comment by Cliff-Rhine** [comment]
> import React, { FC } from 'react'
> import { ConnectProps, connect, CountState } from 'umi';
> interface PageProps extends ConnectProps {
> count: number;
> }
> const mapStateToProps = ({ count }: { count: CountState }) => {
> return { count: count.count }
> }
> const ShowCount: FC = ({ count }) => {
> return
> 
> {count}
> 
> }
> export default connect(mapStateToProps)(ShowCount) // 要这里加泛型

请教一下这里怎么加泛型，能给个示列么

**Comment by j172993563** [comment]
export default connect<PageProps>(mapStateToProps)(ShowCount) // 要这里加泛型

**Comment by j172993563** [comment]
connect《PageProps》(mapStateToProps)(ShowCount) // 要这里加泛型，要用英文的尖括号

**Comment by j172993563** [comment]
`export default connect<PageProps>(mapStateToProps)(ShowCount) // 要这里加泛型`

**Comment by Cliff-Rhine** [comment]
> `export default connect<PageProps>(mapStateToProps)(ShowCount) // 要这里加泛型`

![image](https://user-images.githubusercontent.com/48267247/84014911-a459b400-a9ad-11ea-97bc-a07423c11fa8.png)

现在报这个错误

**Comment by zuoyi615** [comment]
我也遇到相同的问题了 怎么解决呢

**Comment by zuoyi615** [comment]
我也遇到同样的问题, 我是两种方法解决的
- 非路由组件, 层级不深的情况将 props 透传即可
- 层级嵌套太深, 定义组件类型时 Pick 路由组件里面需要的类型, 比如:
```ts
Pick<PageProps, 'index'|'dispatch'> // 只需要 index 和 dispatch 类型
```

**Comment by cctor** [comment]
遇到同样的问题，参照文档的例子[plugin-dva](https://umijs.org/plugins/plugin-dva)，编辑器vs code里面会出现提示
```
Type '{}' is missing the following properties from type 'Pick<XXXXXX, "match" | "location" | "history" | "route">': location, history, routets(2739)
```
请求说明

**Comment by Cliff-Rhine** [comment]
> 遇到同样的问题，参照文档的例子[plugin-dva](https://umijs.org/plugins/plugin-dva)，编辑器vs code里面会出现提示
> 
> ```
> Type '{}' is missing the following properties from type 'Pick<XXXXXX, "match" | "location" | "history" | "route">': location, history, routets(2739)
> ```
> 
> 请求说明

官方那个我也没有研究透，现在已经没有使用connect的方式了，改成了useStore的HOOK方式

**Comment by zuoyi615** [comment]
> > 遇到同样的问题，参照文档的例子[plugin-dva](https://umijs.org/plugins/plugin-dva)，编辑器vs code里面会出现提示
> > ```
> > Type '{}' is missing the following properties from type 'Pick<XXXXXX, "match" | "location" | "history" | "route">': location, history, routets(2739)
> > ```
> > 
> > 
> > 请求说明
> 
> 官方那个我也没有研究透，现在已经没有使用connect的方式了，改成了useStore的HOOK方式

useStore 是 react-redux 的 API 吗

**Comment by Cliff-Rhine** [comment]
> > > 遇到同样的问题，参照文档的例子[plugin-dva](https://umijs.org/plugins/plugin-dva)，编辑器vs code里面会出现提示
> > > ```
> > > Type '{}' is missing the following properties from type 'Pick<XXXXXX, "match" | "location" | "history" | "route">': location, history, routets(2739)
> > > ```
> > > 
> > > 
> > > 请求说明
> > 
> > 
> > 官方那个我也没有研究透，现在已经没有使用connect的方式了，改成了useStore的HOOK方式
> 
> useStore 是 react-redux 的 API 吗

umi的api，版本`"umi": "^3.2.3",`
`import { useStore } from 'umi`

**Comment by Cliff-Rhine** [comment]
> > > > 遇到同样的问题，参照文档的例子[plugin-dva](https://umijs.org/plugins/plugin-dva)，编辑器vs code里面会出现提示
> > > > ```
> > > > Type '{}' is missing the following properties from type 'Pick<XXXXXX, "match" | "location" | "history" | "route">': location, history, routets(2739)
> > > > ```
> > > > 
> > > > 
> > > > 请求说明
> > > 
> > > 
> > > 官方那个我也没有研究透，现在已经没有使用connect的方式了，改成了useStore的HOOK方式
> > 
> > 
> > useStore 是 react-redux 的 API 吗
> 
> umi的api，版本`"umi": "^3.2.3",`
> `import { useStore } from 'umi`

这个API还是我以前在官网上看到的，不过现在没有看到了，另外connect的方式现在貌似正常没有再报错了

**Comment by Cliff-Rhine** [comment]
> > > > > 遇到同样的问题，参照文档的例子[plugin-dva](https://umijs.org/plugins/plugin-dva)，编辑器vs code里面会出现提示
> > > > > ```
> > > > > Type '{}' is missing the following properties from type 'Pick<XXXXXX, "match" | "location" | "history" | "route">': location, history, routets(2739)
> > > > > ```
> > > > > 
> > > > > 
> > > > > 请求说明
> > > > 
> > > > 
> > > > 官方那个我也没有研究透，现在已经没有使用connect的方式了，改成了useStore的HOOK方式
> > > 
> > > 
> > > useStore 是 react-redux 的 API 吗
> > 
> > 
> > umi的api，版本`"umi": "^3.2.3",`
> > `import { useStore } from 'umi`
> 
> 这个API还是我以前在官网上看到的，不过现在没有看到了，另外connect的方式现在貌似正常没有再报错了

hook API，umi的dva插件，需要dva为 2.6.x 以上有效，[https://umijs.org/zh-CN/plugins/plugin-dva#connect](https://umijs.org/zh-CN/plugins/plugin-dva#connect)

**Comment by geograous** [comment]
umi 能好好支持一下typescript吗？好多问题

**Comment by xiaohuoni** [comment]
@geograous 有什么问题可以提出来。缺的会补上的。你可以吧问题整理一下法issues

**Comment by fall-wind** [comment]
为什么被close了 问题还没有被解决吧

**Comment by dhy1994** [comment]
const Foo = (props: Pick<IProps, 'dispatch' | 'foo' | 'loading'>) => {}
用到哪些属性，在Pick中加入哪些属性即可

**Comment by Hquestion** [comment]
我是这么解决的：

`
import { ConnectProps } from 'umi';
interface IProps {
    title: string;
    visible: boolean
}
type IConnectProps = IProps & {   mappedProp: Object; } & ConnectProps;

const Component = (props:IProps ) => {
    const { title, visible, mappedProp } = props as unknown as IConnectProps;
   .... 
}
`

主要通过unknow 转换类型，感觉也不太好。

**Comment by jianhao** [comment]
问题原因就是因为使用 **extends ConnectProps或是ConnectRC** 继承了人家的类型，ConnectProps里面有些必传属性没传，所以不继承就好了，我是这样处理的：
```tsx
import React from 'react'
import { Dispatch, history, connect } from 'umi'

interface Props{
  dispatch: Dispatch
  className?: string
}

const Index: React.FC<Props> = props => {}

export default connect(() => )(Index)

```

这样就不会报类型错误的警告了
