### ISSUE TITLE
antd pro(umi:2.8.3)安装配置@umijs/plugin-qiankun后启动报错

### ISSUE THREAD

**Issue by wsdqr001** [umijs/umi#4850]
antd pro(umi:2.8.3)安装配置@umijs/plugin-qiankun后启动报错，报错信息：

error Plugin \node_modules\@umijs\plugin-qiankun\lib\index.js initialize failed

api.describe is not a function
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Galaxy@2.3.1 start: `cross-env ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION=site umi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Galaxy@2.3.1 start script.

配置修改方法参考的：https://github.com/umijs/umi-plugin-qiankun

谢谢~

**Comment by wsdqr001** [comment]
@sorrycc @cyjake

**Comment by kuitos** [comment]
`npm i @umijs/plugin-qiankun@umi2 -D`
