### ISSUE TITLE
类似 redux-persist

### ISSUE THREAD

**Issue by Fengwz0228** [umijs/umi#4853]
umi有类似redux-persist的插件可以实现state数据持久化吗，或者集成redux-persist

**Comment by elaoshi** [comment]
试试这个，可以参考：
https://hooks.umijs.org/zh-CN/hooks/state/use-local-storage-state#%E4%BB%A3%E7%A0%81%E6%BC%94%E7%A4%BA

**Comment by xiaohuoni** [comment]
看到一个web的数据存储， https://localforage.docschina.org/
