### ISSUE TITLE
layouts 组件下 使用 useParams 获取不到路由参数

### ISSUE THREAD

**Issue by JohnApache** [umijs/umi#4855]
## What happens?

项目配置了如下路由
```js
const Routes = [
    {
        exact    : false,
        path     : '/',
        component: '@/layouts/index',
        routes   : [
            {
                exact    : true,
                path     : '/:id',
                component: '@/pages/index',
            },
        ],
    },
];
```
访问 `http://localhost:8000/123`,  使用 `useParams()` 方法 获取路由参数， 在 `pages` 下的组件 可以正常获取到  id 为 123，但是在 `layouts` 组件下返回的是空对象，这是为什么？   
我尝试 使用 `withRouter` 包裹组件，`props.match.params` 依旧是空对象,  在 `layouts` 下的组件 只能 自己解析`pathname` 获取路由参数吗

- **Umi Version**:  v3.2.3
- **Node Version**: v11.15.0
- **Platform**: MacOS

**Comment by leftstick** [comment]
`在 layouts 下的组件 只能 自己解析pathname 获取路由参数吗`

你说的对

**Comment by JohnApache** [comment]
> `在 layouts 下的组件 只能 自己解析pathname 获取路由参数吗`
> 
> 你说的对

那不是很麻烦吗， `layouts` 的组件都要单独处理，这是由于什么 内部 原因才不实现的吗？

**Comment by leftstick** [comment]
没什么特的理由啊，哪个组件上声明的 `params` ，哪个组件里使用，这不是很合理的操作么。

你现在是要在 layout 里获取到子路由里 设置的 `params`? 如果有多个子路由，并且子路由都有自己规则的 `params` ，那 layout里 的 `useParams` 该怎么办呢？

所以说回来， 你的这个issue就是一个典型的x-y problem。 你应该先谈你的需求是什么，而不是问为什么 `layout 里用 useParams 得不到预期的结果`

**Comment by ArleneShine** [comment]
想在layout里统一显示面包屑，但useParams里拿不到想要的参数

**Comment by steveleeh** [comment]
> 特的理由啊，哪个组件上声明的 `params` ，哪个组件里使用，这不是很合理的操作么。
> 
> 你现在是要在 layout 里获取到子路由里 设置的 `params`? 如果有多个子路由，并且子路由都有自己规则的 `params` ，那 layout里 的 `useParams` 该怎么办呢？
> 
> 所以说回来， 你的这个issue就是一个典型的x-y problem。 你应该先谈你的需求是什么，而不是问为什么 `layout 里用 useParams 得不到预期的结果`

这个理解也很正常啊，在layout里面认为拿到的路由就是当前页面的路由，现在在这里拿不到当前页面的路由而是根路由，这个问题能扯到需求什么的也是真服。很多场景下这里都需要拿到当前页面的路由去做判断，并不觉得的这个问题提出本身有什么问题。

**Comment by lxxxv5** [comment]
> 想在layout里统一显示面包屑，但useParams里拿不到想要的参数

同样的问题，所以大家后面是怎么解决的呢？

**Comment by yucheng1207** [comment]
使用useRouteMatch

**Comment by yangliuyu** [comment]
我使用ant design pro创建代码脚手架后，在routes.ts中定义了路由：
```
 {
    name: 'project-main',
    icon: 'project',
    path: '/projects/:id',
    exact: true,
    component: '@/pages/Welcome',
    hideInMenu: true
  },
  {
    name: 'view',
    icon: 'project',
    path: '/projects/:id/views',
    exact: true,
    component: '@/pages/View'
  },
```
当访问 `http://localhost:8000/projects/1`时，左侧的菜单栏中的'view'菜单的链接显示为 `http://localhost:8000/projects/:id/views` 而不是 `http://localhost:8000/projects/1/views`，希望路由的:id参数能在菜单的location.path中自动被替换掉。
<img width="582" alt="WeChatWorkScreenshot_bbcc5e75-9b72-4216-a3ac-da737998e49c" src="https://user-images.githubusercontent.com/1361821/133428219-674bd3fb-781d-4bbc-9275-1438f0c17ac9.png">

目前是通过正则匹配手工替换menuItemRender中item.path变量。
@JohnApache 如果能从useParams中取得路由参数，那么就可以不用正则匹配了。
