### ISSUE TITLE
useRequest接收的请求函数，有些疑问

### ISSUE THREAD

**Issue by aisriver** [umijs/umi#4857]
#### 主要是关于submit这种传入的请求写法有些疑问

`useRequest(submit, {
    manual: true,
    onSuccess: () => {
      message.success('保存成功');
    },
    onError: error => {
      console.error(error.message);
      message.error('保存失败');
    },
  });`

##### 1、反馈正常

`
 const submit = () => {
    return request(***);
  };
`

##### 2、反馈正常（不加return也有正常反馈）

`
 const submit = async() => {
    await request(***);
  };
`

##### 3、如果request1返回错误结果，捕捉到的是request1，request2不会继续执行

`
 const submit = async() => {
    await request1(***);
    await request2(***);
  };
`

##### 4、如果request1返回正确结果，最终捕捉到的是request2

`
 const submit = async() => {
    await request1(***);
    await request2(***);
  };
`

##### 5、报错then undefined

`
 const submit = () => {
    request(***);
  };
`

**针对以上几种现象，不知道是不是bug，还是就是这样设计的？**

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：3.2.1
- **Node 版本**：10.15.3
- **操作系统**：macOS 10.14.6

**Comment by leftstick** [comment]
`const submit = async() => { async request(***); };`

应该是 `const submit = async() => { await request(***); };`  吧？

**Comment by aisriver** [comment]
> `const submit = async() => { async request(***); };`
> 
> 应该是 `const submit = async() => { await request(***); };` 吧？

对！我写错了，不好意思

**Comment by aisriver** [comment]
> `const submit = async() => { async request(***); };`
> 
> 应该是 `const submit = async() => { await request(***); };` 吧？

改过来了

**Comment by 104gogo** [comment]
大括号里面加上 return

**Comment by aisriver** [comment]
> 大括号里面加上 return

加return是没问题的，其他那些现象是正常的吗，就是这样设计的？
