### ISSUE TITLE
umi3.1怎么在tsx文件中使用styleName?

### ISSUE THREAD

**Issue by SilentSword69** [umijs/umi#4859]
参考了这个回答[#1417](https://github.com/umijs/umi/issues/1417#issuecomment-530712214)里的方法，元素的 `className` 虽然加上了 `hash`,但是样式实际上没有引入

**Comment by xiaohuoni** [comment]
如何使用的？

**Comment by EmiyaYang** [comment]
@xiaohuoni 

遇到同样的问题，样式实际上没有引入。

```less
.container {
  padding: 10px !important;
}
```

```tsx
import * as React from 'react';
import { IRouteComponentProps } from 'umi';
import './index.less';

export default function Layout({ children }: IRouteComponentProps) {
  return <section styleName="container">{children}</section>;
}
```

```ts
// config
{
  // ...
  extraBabelPlugins: [
    [
      'react-css-modules',
      {
        exclude: 'node_modules',
        generateScopedName: '[name]__[local]___[hash:base64:5]',
        filetypes: {
          '.less': {
            syntax: 'postcss-less',
          },
        },
      },
    ],
  ],
}
```

**Comment by SilentSword69** [comment]
我们已经放弃使用umi了

**Comment by williamyorkl** [comment]
> @xiaohuoni
> 
> 遇到同样的问题，hash生成了，但样式没有被引入。
> 
> **相关依赖**
> 
> * "postcss-less": "^3.1.4"
> * "umi": "^3.2.3"
> * "babel-plugin-react-css-modules": "^5.2.6"
> 
> **配置**
> 
> ```ts
> // .umirc.ts
> {
>   // ...
>   extraBabelPlugins: [
>     [
>       'react-css-modules',
>       {
>         exclude: 'node_modules',
>         generateScopedName: '[name]__[local]___[hash:base64:5]',
>         filetypes: {
>           '.less': {
>             syntax: 'postcss-less',
>           },
>         },
>       },
>     ],
>   ],
> }
> ```
> 
> **使用**
> 
> ```css-less
> // src/layout/index.less
> .container {
>   padding: 10px !important;
> }
> ```
> 
> ```tsx
> // src/layout/index.less
> import * as React from 'react';
> import { IRouteComponentProps } from 'umi';
> import './index.less';
> 
> export default function Layout({ children }: IRouteComponentProps) {
>   return <section styleName="container">{children}</section>;
> }
> ```
> 
> **检查**
> 
> ![image](https://user-images.githubusercontent.com/22047765/85221644-02dc5480-b3e8-11ea-9733-0d3fba1a2e83.png)

大佬, 你后面解决问题了么, 我的情况一毛一样....

**Comment by chenxiaoyao6228** [comment]
可行的方案

umi版本
```json
"umi": "^3.5.20",
```

## step1
安装包
```
yarn add babel-plugin-react-css-modules @types/react-css-modules -D
```

## step2

`config.ts`中
```ts
const GENERATE_PATH = '[path]___[name]__[local]___[hash:base64:5]';

const cssLoaderOptions = {
  modules: {
    localIdentName: GENERATE_PATH,
  },
};

export default defineConfig({
  extraBabelPlugins: [
    [
      'babel-plugin-react-css-modules',
      {
        exclude: 'node_modules',
        generateScopedName: GENERATE_PATH,
        filetypes: {
          '.less': {
            syntax: 'postcss-less',
          },
        },
      },
    ],
  ],
  cssLoader: cssLoaderOptions
}
```
