### ISSUE TITLE
umi3开启ssr之后的部署问题

### ISSUE THREAD

**Issue by CassielLee** [umijs/umi#4860]
## umi3开启ssr之后的部署问题
这两天在研究umi3的ssr功能，目前主要遇到以下几个问题：
2、开启了ssr之后，使用geiInitialProps方法返回的数据是undifined；
3、ssr模式下打包会生成一个umi.server.js的文件，但是把官方示例的服务端代码拷下来运行之后发现无法加载到样式、图片等资源，另外还有这个`Uncaught SyntaxError: Unexpected token '<'`错误，希望有人帮忙解答一下疑惑，不胜感激~
## 相关环境信息

- **Umi 版本**：3.2.3
- **Node 版本**：11.14.0
- **操作系统**：win10

**Comment by ycjcl868** [comment]
服务端路径配置不对

**Comment by CassielLee** [comment]
> 服务端路径配置不对
是publicPath吗？这个我没有配置，就是用的默认的，请问您能否详细说一下呢？感谢！

**Comment by williamnie** [comment]
> > 服务端路径配置不对
> > 是publicPath吗？这个我没有配置，就是用的默认的，请问您能否详细说一下呢？感谢！

做个复现的最小版本吧，我看下，上个issue里的哥们遇到的问题可能跟你一样

**Comment by CassielLee** [comment]
> > > 服务端路径配置不对
> > > 是publicPath吗？这个我没有配置，就是用的默认的，请问您能否详细说一下呢？感谢！
> 
> 做个复现的最小版本吧，我看下，上个issue里的哥们遇到的问题可能跟你一样

我看了他的提交的复现最小版本，和我是一样的，都是copy的官方代码，问题也是一样的，https://github.com/SilentFlute/umi3.x-ssr.git

**Comment by williamnie** [comment]
> > > > 服务端路径配置不对
> > > > 是publicPath吗？这个我没有配置，就是用的默认的，请问您能否详细说一下呢？感谢！
> > 
> > 
> > 做个复现的最小版本吧，我看下，上个issue里的哥们遇到的问题可能跟你一样
> 
> 我看了他的提交的复现最小版本，和我是一样的，都是copy的官方代码，问题也是一样的，https://github.com/SilentFlute/umi3.x-ssr.git

https://github.com/umijs/umi/issues/4808#issuecomment-642389596看这个回复

**Comment by williamnie** [comment]
#close

**Comment by williamnie** [comment]
closed

**Comment by williamnie** [comment]
#4860closed

**Comment by 104gogo** [comment]
准备上线了，什么时候发下个版本啊 @ycjcl868
