### ISSUE TITLE
[Feature Request] umi 可以 eject 出 webpack 配置吗 

### ISSUE THREAD

**Issue by tolerance-go** [umijs/umi#4862]
## Background

准备使用 storybook 进行组件开发，umi 作为项目构建工具，希望可以共用配置

## Proposal

类似 CRA 可以弹射出 umi 的配置文件

**Comment by xiaohuoni** [comment]
可以看下这个是不是你需要的 https://umijs.org/docs/cli#umi-webpack

**Comment by tolerance-go** [comment]
太赞了，我现在使用的是 @umijs/bundler-webpack 感谢回答 @xiaohuoni
