### ISSUE TITLE
@umijs/plugin-model 类型推导错误

### ISSUE THREAD

**Issue by jockey100332** [umijs/umi#4869]
## What happens?
在项目中使用了@umijs/plugin-model， 在程序可以正常执行的情况下， ts 类型中报错

错误显示： 类型“"useParaphraseInfoModel"”的参数不能赋给类型“"@@initialState"”的参数。

项目 为 ant pro v5

**Comment by leftstick** [comment]
是不是类似这个[model-错误](https://github.com/umijs/plugins/issues/107)?

**Comment by xiaohuoni** [comment]
为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN

**Comment by H-Sven** [comment]
请问你解决了吗

**Comment by xiaohuoni** [comment]
@H-Sven 如果是同样的问题，你可以提供复现demo

**Comment by birdycn** [comment]
请问解决了吗

**Comment by xiaohuoni** [comment]
@birdycn 如果是同样的问题，你可以提供复现demo

**Comment by lirongling** [comment]
遇到同样的问题了

**Comment by ccysmd** [comment]
遇到同样的问题了

**Comment by semmywong** [comment]
遇到同样的问题了
