### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by alwaysRemember** [umijs/umi#4872]
## What happens?

**运行时配置函数：render 鸡肋**
```
export function render(oldRender) {
  fetch('/api/auth').then(auth => {
    if (auth.isLogin) { oldRender() }
    else { history.push('/login'); }
  });
}
```
> 就只有一个oldRender函数传递到render方法，那我怎么知道哪个页面是要进行校验，哪个页面不校验。比如给的这个样例，我如果访问的本身是/login，那让我/login本身还去校验登录态么。。

**路由配置中的 wrappers**
> 只能进行同步的操作，一旦异步那么就会有个问题，我页面先渲染了，数据还在请求中，那如果是同步的例如路由级别的权限校验，只能说是本身对路由对象进行操作，一旦进行一些页面切换的时候校验登录态这种，那基本就不能基于这个来实现了。 

## 相关环境信息

- **Umi 版本**：3.2.3
- **Node 版本**：v10.15.3
- **操作系统**：10.14.6

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
