### ISSUE TITLE
umi dva-logger文档错误

### ISSUE THREAD

**Issue by mytheart** [umijs/umi#4874]
![image](https://user-images.githubusercontent.com/42933010/84598426-375a8880-ae9d-11ea-8c2d-59e377923894.png)

**Comment by mytheart** [comment]
refactor:发现错误

**Comment by juzhiyuan** [comment]
https://umijs.org/zh-CN/plugins/plugin-dva#dva-%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE

文档已更新
