### ISSUE TITLE
config的路由通过patchRoutes重新合并后，出现了空白页面和404的页面的情况

### ISSUE THREAD

**Issue by XunyChen** [umijs/umi#4877]
#4356  复现步骤，错误日志以及相关配置

1、yarn create umi storeAdmin 选项全部使用默认（语言js和ts都试过，都存在一样的问题，仓库代码为js代码）。
2、添加testPage，app.jsx。
3、当合并代码为`home.routes = [
      ...home.routes,
      ...menusConfig,
    ]`时，menusConfig添加的菜单，点击后为404
4、当合并代码为`home.routes = [
      ...menusConfig,
      ...home.routes,
    ]`时，home.routes的菜单，页面为空白
5、去除config下的404页面配置项后，所有页面就可以正常显示！但是真正的404页面就无法显示了。

tip: localStorage数据为`[{"authorityType":"menu","name":"测试页面","componentUrl":"/TestPage/index","icon":"crown","path":"/testPage","exact":true},{"authorityType":"menu","name":"测试页面2","icon":"table","routes":[{"authorityType":"menu","name":"测试页面3","componentUrl":"/ListTableList/index","icon":"table","path":"/testPage3","exact":true}]}]`

## 最小可复现仓库

[仓库地址](https://github.com/XunyChen/storeAdmin)

## 相关环境信息

- **Umi 版本**：^3.1.2
- **Node 版本**：v12.18.0
- **操作系统**：MacOs Catalina 10.15.4 (19E287)

**Comment by XunyChen** [comment]
@leftstick 大佬，这个问题怎么处理

**Comment by leftstick** [comment]
@XunyChen  把你的

```js
home.routes = [
      ...home.routes,
      ...menusConfig,
    ]
```

改成

```js
home.routes = [
      ...home.routes.slice(0, -1),
      ...menusConfig,
      home.routes[home.routes.length -1]
    ]
```


核心问题是，你运行时新增的路由，加到了404的后面，所以无论你点什么，人家都先match了404.。。。

**Comment by XunyChen** [comment]
@leftstick 按你的配置修改了，但是当输入的url不存在的时候（http://localhost:8000/check-check），还是无法渲染出404

**Comment by leftstick** [comment]
@XunyChen  核心问题在于，你自己在localstorage里设置的数据不规范，改成这样：

```json
[
  {
    "authorityType": "menu",
    "name": "测试页面",
    "componentUrl": "/TestPage/index",
    "icon": "crown",
    "path": "/testPage",
    "exact": true
  },
  {
    "authorityType": "menu",
    "name": "测试页面2",
    "icon": "table",
    "path": "/testPage2",
    "routes": [
      {
        "authorityType": "menu",
        "name": "测试页面3",
        "componentUrl": "/ListTableList/index",
        "icon": "table",
        "path": "/testPage3",
        "exact": true
      }
    ]
  }
]

```

你少了 `    "path": "/testPage2",` ，别看这是个父菜单，按理说不应该有path，但是没有，你后面的404就是没法命中，你就说high不high吧

**Comment by XunyChen** [comment]
@leftstick 改完了，每个子菜单的path还得再把父菜单path带上，才能访问到页面，不然又是404；这个骚套路。。。所以其实每个path都必须要写绝对路径对吧

**Comment by leftstick** [comment]
@XunyChen  也不是，两个方法：

1. 给所有的『父级路由』都加 `path` ，这是上面我教你改的方式
2. 给所有的『子集路由』最后，都加一个404处理 `{ component: './404' }`

其实这也不算骚，彻底搞明白 `react-router` 的 match 策略，就很容易想通了
