### ISSUE TITLE
部署到正式版本后，自动引入无关的文件，导致页面加载错误。

### ISSUE THREAD

**Issue by shangdev** [umijs/umi#4878]
如图所示：

![image](https://user-images.githubusercontent.com/15621520/84720206-074fda00-afb0-11ea-97da-7e202facd9b7.png)

![image](https://user-images.githubusercontent.com/15621520/84720221-12a30580-afb0-11ea-9257-483bc82476da.png)

![image](https://user-images.githubusercontent.com/15621520/84720268-31a19780-afb0-11ea-94d7-d9f75548692a.png)

![image](https://user-images.githubusercontent.com/15621520/84720287-3ebe8680-afb0-11ea-9862-e95bc0024d56.png)

上图中的 ipjs.js 在开发环境中是没用的，所以请问这个是umi框架的一部分吗（貌似是个埋点统计）？如何关闭。

**Comment by xiaohuoni** [comment]
umi 的项目应该不会添加这个，看看是不是你们，被攻击了？？
https://preview.pro.ant.design/dashboard/analysis
