### ISSUE TITLE
@umijs/plugin-locale WARNING: antd is not installed, <SelectLang /> unavailable

### ISSUE THREAD

**Issue by yayxs** [umijs/umi#4880]
## What happens?

@umijs/plugin-locale WARNING: antd is not installed, <SelectLang /> unavailable.

Cannot find module 'antd/package.json'
Error: Cannot find module 'antd/package.json'

## Mini Showcase Repository(REQUIRED)

[可以在这个仓库重现问题](https://github.com/yayxs/umi-nest/tree/master/umi-antd-admin)
是一个新项目

## How To Reproduce
 - mkdir myapp && cd myapp
 - yarn create @umijs/umi-app
 - yarn

**Expected behavior** 1. 2.

## Context

- **Umi Version**:

- **Node Version**:
v12.13.0
- **Platform**:
windows

**Comment by leftstick** [comment]
你给的repo不可复现，要不你再重装一下试试吧

**Comment by yayxs** [comment]
> 你给的repo不可复现，要不你再重装一下试试吧

使用`yarn ` 去装依赖的时候，会遇到提及的问题，npm i 使用npm 是可以的

**Comment by leftstick** [comment]
@yayxs  我用的也是yarn。这就尴尬了，可能和操作系统有关？

**Comment by yayxs** [comment]
> @yayxs 我用的也是yarn。这就尴尬了，可能和操作系统有关？
以下是错误的详细信息，我换用的 tyarn 也还是不行，不知是否我的电脑设备有问题
--------------------------

PS D:\github-code\umi-nest\umi-antd-admin> npm run start

> @ start D:\github-code\umi-nest\umi-antd-admin
> umi dev

@umijs/plugin-locale WARNING: antd is not installed, <SelectLang /> unavailable.
Starting the development server...
Cannot find module 'antd/package.json'
Require stack:
- D:\github-code\umi-nest\umi-antd-admin\node_modules\@umijs\plugin-antd\lib\index.js
- D:\github-code\umi-nest\umi-antd-admin\node_modules\@umijs\core\lib\Service\utils\pluginUtils.js
- D:\github-code\umi-nest\umi-antd-admin\node_modules\@umijs\core\lib\Service\Service.js
- D:\github-code\umi-nest\umi-antd-admin\node_modules\@umijs\core\lib\index.js
- D:\github-code\umi-nest\umi-antd-admin\node_modules\umi\lib\ServiceWithBuiltIn.js
- D:\github-code\umi-nest\umi-antd-admin\node_modules\umi\lib\forkedDev.js
Error: Cannot find module 'antd/package.json'
Require stack:
- D:\github-code\umi-nest\umi-antd-admin\node_modules\@umijs\plugin-antd\lib\index.js
- D:\github-code\umi-nest\umi-antd-admin\node_modules\@umijs\core\lib\Service\utils\pluginUtils.js
- D:\github-code\umi-nest\umi-antd-admin\node_modules\@umijs\core\lib\Service\Service.js
- D:\github-code\umi-nest\umi-antd-admin\node_modules\@umijs\core\lib\index.js
- D:\github-code\umi-nest\umi-antd-admin\node_modules\umi\lib\ServiceWithBuiltIn.js
- D:\github-code\umi-nest\umi-antd-admin\node_modules\umi\lib\forkedDev.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.resolve (internal/modules/cjs/helpers.js:80:19)
    at Object.fn (D:\github-code\umi-nest\umi-antd-admin\node_modules\@umijs\plugin-antd\lib\index.js:103:40)
    at D:\github-code\umi-nest\umi-antd-admin\node_modules\@umijs\core\lib\Service\Service.js:496:44
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\github-code\umi-nest\umi-antd-admin\node_modules\@umijs\core\lib\Service\Service.js:106:103)
    at _next (D:\github-code\umi-nest\umi-antd-admin\node_modules\@umijs\core\lib\Service\Service.js:108:194)
    at D:\github-code\umi-nest\umi-antd-admin\node_modules\@umijs\core\lib\Service\Service.js:108:364
    at new Promise (<anonymous>)
    at D:\github-code\umi-nest\umi-antd-admin\node_modules\@umijs\core\lib\Service\Service.js:108:97

**Comment by leftstick** [comment]
按理说`antd` 会被自动安装的，如果没有，你就手动来一发吧 `yarn add antd`

**Comment by jungor** [comment]
+1 我是用 npm，但是antd没自动安装

**Comment by xiaohuoni** [comment]
使用 antd 可以安装 plugin-antd。
