### ISSUE TITLE
环境变量WATCH和WATCH_IGNORED不起作用

### ISSUE THREAD

**Issue by Sayid1** [umijs/umi#4881]
## What happens?

我使用环境变量
WATCH=none，修改文件会触发热重载
WATCH_IGNORED=none，修改node_modules内文件不会触发热重载

## Mini Showcase Repository(REQUIRED)

仓库使用的是 [repo](https://github.com/umijs/umi/tree/master/examples/normal)（umi官方demo）

## How To Reproduce

**Steps to reproduce the behavior:**
1. 使用WATCH=none umi dev启动项目，修改pages/index.tsx，会触发热重载
2. 使用WATCH_IGNORED=none umi dev启动项目，修改node_modules内文件 **不会** 触发热重载

**Expected behavior** 
期望使用WATCH_IGNORED=none umi dev启动项目，修改node_modules内文件 **会** 触发热重载

## Context

- **Umi Version**: latest
- **Node Version**: v10.16.0
- **Platform**: macOS10.14.5

**Comment by Sayid1** [comment]
@sorrycc @xiaohuoni 两位大佬帮看看咯，急用 :)

**Comment by xiaohuoni** [comment]
WATCH=none 看代码的逻辑是监听 package.json 中的插件库变化。
WATCH_IGNORED=none 看代码实现是没有问题的，但是确实真实无效。

**Comment by Sayid1** [comment]
我加了corss-env也不起作用，能抓紧修复吗，大佬

**Comment by yxlolxy** [comment]
cross-env 完全不起作用
`cross-env NODE_ENV=dev umi dev`
结果 process.env.NODE_ENV取到的永远是development不是dev，请问少了哪些配置

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.

**Comment by earvinLi** [comment]
is this fixed already? seems like it's still a bug even with `^3.5.20`

**Comment by lys623** [comment]
> is this fixed already? seems like it's still a bug even with `^3.5.20`

+1
