### ISSUE TITLE
如何动态指定请求后端的地址

### ISSUE THREAD

**Issue by imSHIN** [umijs/umi#4883]
公司有许多环境，正式环境，预发布环境，沙盒环境，个人沙盒环境，每个环境都有各自对应的域名，如何能够动态的指定proxy的target？

当前是不同环境打包时写死的不同target值，比较麻烦

我希望项目部署在a域名下，请求的就是a域名的后端地址，部署在b域名下，请求的就是b域名的后端地址。

如何解决这个问题？

**Comment by xiaohuoni** [comment]
build之后 proxy 无效，你可以通过判断当前的 url，修改 prefix [request运行时配置](https://umijs.org/plugins/plugin-request#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE)

**Comment by bobchen554** [comment]
直接请求'/url/a/b' ==> a域名 （https://a.com/url/a/b,  b域名 （https://b.com/url/a/b)   服务器上反向代理一下
