### ISSUE TITLE
扩展路由属性功能设置title无法在routes里收到

### ISSUE THREAD

**Issue by NeptDaniel** [umijs/umi#4884]
https://umijs.org/zh-CN/docs/convention-routing#扩展路由属性

请问设置组件 title 后，是否可以在 this.route.toutes 里看到改变的？

**Comment by Miss-violet** [comment]
可以在 this.props.route.routes 看到改变，但是是在 component 里，所以不会被渲染在页面的标题上
以下截图是我在 src/Detail/index.jsx 的代码里设置了 Detail.title='Detail2'
在路由设置了 { path: '/detail', component: './Detail', title: 'Detail' }
最后发现打印在浏览器页面标题上的是路由上的设置
![image](https://user-images.githubusercontent.com/26664762/93962029-63cf4c00-fd8c-11ea-8c4b-2f4d98cb6992.png)

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
