### ISSUE TITLE
升级到新版本后PrivateRoute内Redirect会出错

### ISSUE THREAD

**Issue by Instanced** [umijs/umi#489]
看了下新版自动生成的路由，全局`layout`跟 `index/index.js`的 `path`都是 `/`。 那如果在PrivateRoute.js文件内需要对`/`路由做鉴权的话，就会死循环Redirect

[Test](https://github.com/Instanced/test)

**Comment by xiaohuoni** [comment]
你给的例子不能重现你说的这个问题，就是进了两次PrivateRoute

**Comment by sorrycc** [comment]
是有这个问题，在 PrivateRoute 判断 props.location.path，忽略相关的路由。
