### ISSUE TITLE
i18n-remove  出现问题 

### ISSUE THREAD

**Issue by shwzh** [umijs/umi#4893]
## 项目利用yarn create umi，分别选择ant-design-pro、Pro V4、 Ts 、simple、antd4

项目初始化成功，依赖安装成功，启动项目 yarn start

想删除项目中国际化的选项，利用yarn i18n-remove,未果，报错，
   使用npm run i18n-remove 效果一样

因图片上传不成功，粘贴错误

错误提示： 

remove locale for src/global.tsx./Users/xxx/Documents/work/umi-dir/umi-3-antd-4-test/node_modules/@ant-design/pro-cli/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:335
            throw error;
            ^

Error: Cannot read config file: /Users/xxx/Documents/work/umi-dir/.eslintrc.js
Error: Cannot find module '@umijs/fabric/dist/eslint'
Require stack:
- /Users/xxx/Documents/work/umi-dir/.eslintrc.js
- /Users/xxx/Documents/work/umi-dir/umi-3-antd-4-test/node_modules/@ant-design/pro-cli/node_modules/eslint/lib/cli-engine/config-array-factory.js
- /Users/xxx/Documents/work/umi-dir/umi-3-antd-4-test/node_modules/@ant-design/pro-cli/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js
- /Users/xxx/Documents/work/umi-dir/umi-3-antd-4-test/node_modules/@ant-design/pro-cli/node_modules/eslint/lib/cli-engine/cli-engine.js
- /Users/xxx/Documents/work/umi-dir/umi-3-antd-4-test/node_modules/@ant-design/pro-cli/node_modules/eslint/lib/cli-engine/index.js
- /Users/xxx/Documents/work/umi-dir/umi-3-antd-4-test/node_modules/@ant-design/pro-cli/node_modules/eslint/lib/api.js
- /Users/xxx/Documents/work/umi-dir/umi-3-antd-4-test/node_modules/@ant-design/pro-cli/src/i18n/eslintJs.js
- /Users/xxx/Documents/work/umi-dir/umi-3-antd-4-test/node_modules/@ant-design/pro-cli/src/i18n/index.js
- /Users/xxx/Documents/work/umi-dir/umi-3-antd-4-test/node_modules/@ant-design/pro-cli/cli.js

## Mini Showcase Repository(REQUIRED)

> GitHub : https://github.com/shwzh/umi-3-antd-4-test.git 

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version: 3.0**:
- **Node Version: 12.14.0**:
- **Platform: macBook pro**:

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
