### ISSUE TITLE
在不使用 umi-plugin-react Preset 时，无法自定义排除路由

### ISSUE THREAD

**Issue by JonasGao** [umijs/umi#4895]
## What happens?

现在手上有个小需求要做。不需要太复杂的东西。所以预想的是 umi + react hooks 即可，不需要 redux 或者 dva 出场。这种情况下，写 hooks 时，想放在 pages 目录下，就会生成路由。

想通过配置排除。但是在官网搜索了一圈，发现并没有对应配置。只能有 example 库里有个例子，不过例子类似如下

```javascript
config = {
  plugins: [
    ['umi-plugin-react', {
        'routes': {
          'exclude': [ /hooks/ ]
        }
    }]
  ]
}
```

但是因为并没有安装 `umi-plugin-react`，所以上述配置不能使用，使用就会报错。

是否可以考虑在最小依赖下，支持自定义排除路由？

## 最小可复现仓库

复现仓库就不提交了。因为复现很简单。

## 复现步骤，错误日志以及相关配置

1. 创建空的 umi app
2. 按上面的配置，配置 umi
3. `umi dev`
4. 报错

## 相关环境信息

- **Umi 版本**：^3.1.1
- **Node 版本**：v12
- **操作系统**：MacOS

**Comment by leftstick** [comment]
如果你要排除`/hooks/` 目录下的所有文件，这么写：`/hooks\//`。

你那个写法，应该只能排除文件名叫`hooks` 的文件

**Comment by xiaohuoni** [comment]
3.1.1 版本，不需要排除，应该会自动排除才是，如果你需要手动个配置，需要再安装一个插件。
[@alitajs/routes](https://alitajs.com/plugins/routes)

**Comment by JonasGao** [comment]
了解。感谢回复

**Comment by jiechud** [comment]
@xiaohuoni 
![image](https://user-images.githubusercontent.com/9709396/105838014-798aa180-600a-11eb-9608-bf9caaf3b2e3.png)
这个地址打不开了
