### ISSUE TITLE
umi3国际化只提供了hooks组件形式,class组件如何使用多语言

### ISSUE THREAD

**Issue by Hexa-gram** [umijs/umi#4900]
## What happens?

老项目使用class组件形式,迁移umi3后,formatMessage无法使用,文档中提供的useIntl hook只支持函数组件,全部用函数组件重写工作量也太大了

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
![image](https://user-images.githubusercontent.com/28613856/85258355-f1ec1b80-b499-11ea-9d4e-b6be21eacdc4.png)
![image](https://user-images.githubusercontent.com/28613856/85258368-f7496600-b499-11ea-9b82-a385866e818a.png)

## 相关环境信息

- **Umi 版本**： "umi": "^3.1.2",
- **Node 版本**：v12.13.1
- **操作系统**：macOs

**Comment by GloriaCHL** [comment]
遇到同样问题。所以，这里的答案是？ORZ

**Comment by Hexa-gram** [comment]
> 遇到同样问题。所以，这里的答案是？ORZ

我们用的antdPro  所以在新的页面使用的这种解决方案

https://pro.ant.design/docs/i18n-cn#gatsby-focus-wrapper

同时引入 import { FormattedMessage, formatMessage } from 'umi/locale';

可以开一个新的issue找大佬们看看能不能解决一下

**Comment by GloriaCHL** [comment]
https://formatjs.io/docs/react-intl/api/#injectintl-hoc
