### ISSUE TITLE
Umi does not support language "zh_HK"

### ISSUE THREAD

**Issue by AlbertZheng66** [umijs/umi#4901]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by leftstick** [comment]
What you mean by `does not support language "zh_HK"`?  Would you tried with `zh-HK` ?

Detailed description is required for solving issue
