### ISSUE TITLE
怎么启用hashHistory 下的 _k 查询参数

### ISSUE THREAD

**Issue by gebilaoman** [umijs/umi#4902]
## What happens?
hashHistory 下的 _k 查询参数

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

![image](https://user-images.githubusercontent.com/26354664/85275158-806c9700-b4b2-11ea-9cb0-6b68e57fb201.png)

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
