### ISSUE TITLE
更新umi后，ssr服务npm start报500错误

### ISSUE THREAD

**Issue by 104gogo** [umijs/umi#4904]
## What happens?
使用最新的umi@3.2.5，运行npm start，srr服务报500的错误，使用3.2.3版本是正常的

**Comment by ycjcl868** [comment]
报错信息是什么？

**Comment by 104gogo** [comment]
![image](https://user-images.githubusercontent.com/8522646/85411079-7cb43f80-b59a-11ea-9078-2d0c461606d4.png)
如果哪里可以看到更多具体信息，你可以告诉我，我去找来发你

**Comment by ycjcl868** [comment]
复现 demo 发我下

**Comment by 104gogo** [comment]
那天着急提了这个问题，今天看了下，发现是我们注入的js里面多了stript标签，然后umi.server.js运行报错了。
![image](https://user-images.githubusercontent.com/8522646/85915678-1837ff80-b87c-11ea-9128-21fde2cd0aa7.png)
