### ISSUE TITLE
[Feature Request] umi3 devServer 没有实现webpack dev server的before能力？

### ISSUE THREAD

**Issue by sonacy** [umijs/umi#4905]
## Background

> 我们原有项目在webpack devserver的before hooks做一些基于express的路由增强。
升级umi3之后，因为umi3自己实现了devserver，导致before hooks没了。
换成了beforeMiddlewares, onListening, onConnection等等hooks.
但无论哪种hooks都是在server启动后，这个时候没有办法在app.use去动态加入middleware。
只能在beforeMiddlewares的数组中根据req.path一个个判断处理。很麻烦。

## Proposal

希望可以增加一个hook，比如onBeforeListening,回传参数包含app或者Server，可以在server启动前调用。实现类似于webpack dev server的before hook。

或者现有api有啥方法可以实现？

**Comment by qingxiao** [comment]
同求  umi@2有该功能，迁移到umi@3 不能使用了。

**Comment by qingxiao** [comment]
> 同求 umi@2有该功能，迁移到umi@3 不能使用了。

改成 beforeMiddlewares 可以用，但是文档里面没搜索到该配置， 在插件扩展中有提到。

**Comment by hbrls** [comment]
umi@3 并没有使用 `webpack-dev-server`，而是用 `express` [自己写的]()，所以那个配置项 `devServer` 只是为了保持和 `webpack` 一样的命名惯例。

然后由于没有实现 `express` 的 by route middleware 的传参形式，所以要自己写 if。

写法对比：

```javascript
// webpack@4, webpack-dev-server@3
before: function(app) {
    app.get('/some/path', async function(req, res) {
        res.json({ custom: 'response' });
    });
},
   
// webpack@5, webpack-dev-server@4
 onBeforeSetupMiddleware: function ({ app }) {
    app.get('/some/path', function (req, res) {
        res.json({ custom: 'response' });
    });
},

// umi@3, express
beforeMiddlewares: [
    (req, res, next) => {
        if (req.method === 'GET' && req.url === '/some/path') {
            res.json({ custom: 'response' });
        } else {
            next();
        }
    },
],
```
