### ISSUE TITLE
umi + ant-design/pro-layout 使用 icon name 无法显示图标

### ISSUE THREAD

**Issue by bluexiaowei** [umijs/umi#4908]
## What happens?

umi 在搭配 layout 使用时，无法显示 antd 内置的 icon 图标，只显示了字符串。

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/bluexiaowei/umi-example

## 复现步骤，错误日志以及相关配置

```ts
// .umirc.ts
import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  layout: { name: 'test', locale: false },
  routes: [
    {
      path: '/',
      component: '@/pages/index',
      menu: { name: '用户管理', icon: 'user' },
    },
  ],
});
```

umi 文档说明 https://umijs.org/zh-CN/plugins/plugin-layout#menu

## 相关环境信息

- **Umi 版本**："umi": "^3.2.3",
- **Node 版本**：v14.4.0
- **操作系统**：macos

![image](https://user-images.githubusercontent.com/20636951/85527341-5e535000-b63d-11ea-953d-dc878e42bdfd.png)

**Comment by leftstick** [comment]
`@umijs/plugin-layout` 目前的实现和文档不一致。快速调整，你只要把把`menu` 去掉，配置直接落在route上就好了，如下：

```ts
import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  layout: { name: 'test', locale: false },
  routes: [
    {
      path: '/',
      component: '@/pages/index',
      name: '用户管理', icon: 'user'
    },
  ],
});

```

**Comment by chaosJS** [comment]
Duplicate of #4095 
提交issue之前先搜一下

**Comment by bluexiaowei** [comment]
谢谢，受教了。下次一定多搜索一下。
