### ISSUE TITLE
配置dynamic后，跳转连接时，当前页面会重新更新一次，不配置dynamic，就不会更新第二次

### ISSUE THREAD

**Issue by dsmelon** [umijs/umi#4911]
## What happens?

整个页面会重新装载一次，useEffect和useState都会重新运行，这不符合逻辑，是bug,当跳转过后，第二次就不会了

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by kelvin1984** [comment]
这个问题我也遇到了，目前撤回到umi@3.0.9没这个问题
就是初次访问或者刷新页面时，路由在第一次跳转会导致整个页面完全更新，之后就好了

**Comment by MinJieLiu** [comment]
https://preview.pro.ant.design/dashboard/analysis

可以试试，打开后，再一次点击当前路由标签，页面会全部重新加载一次。第二次就不会了

**Comment by MinJieLiu** [comment]
@sorrycc 可以跟一下这个问题吗

**Comment by MinJieLiu** [comment]
可以关了 https://github.com/umijs/umi/pull/5124
