### ISSUE TITLE
ssr getinitialprops bug

### ISSUE THREAD

**Issue by jasonc08** [umijs/umi#4912]
## What happens?

在client side轉跳頁面時,它會執行render先,然後才會執行 getinitialprops, 導致 TypeError: Cannot read property 'title' of undefined

## 最小可复现仓库
https://github.com/jasonc08/umijs-ssr-bug.git 

## 复现步骤，错误日志以及相关配置

當由 http://localhost:8000/page2 去 http://localhost:8000/page1 時,便會throw exception
TypeError: Cannot read property 'title' of undefined, 
原因應該是因為當它在client side轉跳頁面時,它會執行render先,然後才會執行 getinitialprops 

//配置, 開啟ssr
 ```

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  ssr:{},
  // routes: [
  //   { path: '/', component: '@/pages/index' },
  // ],
  autoprefixer: false,
  targets:false
}); 
```
//page1.tsx
 ```

import { IGetInitialProps, Link } from 'umi';
import React from 'react';
const Page1 = (props: any) => {
    const { data } = props;
    return (
        <div>
            <div>{data.title}</div>
            <Link to="/page1">Page1</Link><br />
            <Link to="/page2">Page2</Link>
        </div>

    )
}
Page1.getInitialProps = (async (ctx) => {
    return Promise.resolve({
        data: {
            title: 'Hello World, Page 1',
        }
    })
}) as IGetInitialProps;

export default Page1;
``` 

## 相关环境信息

- **Umi 版本**： 3.2.5
- **Node 版本**：v12.18.1
- **操作系统**：win 7

**Comment by qingxiao** [comment]
3.2.12 ssr同样问题，client端渲染的时候，会先执行组件渲染，后执行`getInitialProps`，导致组件获取不到getInitialProps返回的数据而报错

**Comment by ycjcl868** [comment]
> 3.2.12 ssr同样问题，client端渲染的时候，会先执行组件渲染，后执行`getInitialProps`，导致组件获取不到getInitialProps返回的数据而报错
> 目测[这里](https://github.com/umijs/umi/blob/656dd0115fea87673778a173d467859b79630bad/packages/renderer-react/src/renderRoutes/renderRoutes.tsx#L69)需要 加个判断 ，
> 
> ```
> return <Component {...props} {...initialProps} />;
> ```
> 
> 如 `Component.getInitialProp && ! initialProps ` 不渲染组件, 防止报错

来个 PR ~

**Comment by handycode** [comment]
> > 3.2.12 ssr同样问题，client端渲染的时候，会先执行组件渲染，后执行`getInitialProps`，导致组件获取不到getInitialProps返回的数据而报错
> > 目测[这里](https://github.com/umijs/umi/blob/656dd0115fea87673778a173d467859b79630bad/packages/renderer-react/src/renderRoutes/renderRoutes.tsx#L69)需要 加个判断 ，
> > ```
> > return <Component {...props} {...initialProps} />;
> > ```
> > 
> > 
> > 如 `Component.getInitialProp && ! initialProps ` 不渲染组件, 防止报错
> 
> 来个 PR ~

@ycjcl868 遇到相同的问题~    

在切换路由且数据未返回时，应该渲染loading 组件。我在本地增加了如下述代码，测试是可行的

```
 if (Component?.getInitialProps && !initialProps) {
    return Component.loadingComponent ? Component.loadingComponent() : <></>
 }
```
问题： 如何能拿到配置 config.dynamicImport 内的 loading 组件 而不是手动在页面组件上去添加 loadingComponent

**Comment by jxiangji** [comment]
同样的问题会先执行render然后再执行getInitialProps然后再执行render，请问这都一年了，这个bug还没解决吗？或者有其他使用方式规避？

**Comment by jxiangji** [comment]
> 同样的问题会先执行render然后再执行getInitialProps然后再执行render，请问这都一年了，这个bug还没解决吗？或者有其他使用方式规避？

@ycjcl868 麻烦大佬帮忙看下怎么解决呢？因为我必须要先通过getInitialProps获取服务端数据前置条件后才能执行render
