### ISSUE TITLE
Convention Routing "index.tsx" problem

### ISSUE THREAD

**Issue by jasonc08** [umijs/umi#4913]
## What happens?
當進入 http://localhost:8000/book/index , 它會進入 pages/book/[otherpages].tsx, 而不是 pages/book/index.tsx

## 最小可复现仓库
https://github.com/jasonc08/umijs-ssr-bug.git

## 复现步骤，错误日志以及相关配置

```
//配置, 開啟ssr
export default defineConfig({
 nodeModulesTransform: {
   type: 'none',
 },
 ssr:{},
 // routes: [
 //   { path: '/', component: '@/pages/index' },
 // ],
 autoprefixer: false,
 targets:false
}); 
```

// Directory structure
```
└── pages 
    ├── book
        ├── index.tsx
        └── [otherpages].tsx

```

## 相关环境信息

- **Umi 版本**：3.2.5
- **Node 版本**：v12.18.1
- **操作系统**：win7

**Comment by ethanhjwang** [comment]
http://localhost:8000/book 会进入 pages/book/index.tsx 
参考：[动态路由](https://umijs.org/zh-CN/docs/convention-routing#%E5%8A%A8%E6%80%81%E8%B7%AF%E7%94%B1)

**Comment by jasonc08** [comment]
我只是覺得 http://localhost:8000/book 和 http://localhost:8000/book/index 都應該進入 index.tsx 才是對, 就像http://localhost:8000/book/detail， 正常會預期它會尋找detail.tsx, 如找不到才會用[otherpages].tsx

**Comment by jasonc08** [comment]
umi v2 有以下這一個，不過到v3就沒有了，好像倒退了
{ path: '/users/:id?': component: './pages/users/$id$.js' },

**Comment by ycjcl868** [comment]
用的是约定式路由？
