### ISSUE TITLE
钉钉3群人数已满，无法加入

### ISSUE THREAD

**Issue by tarvos21** [umijs/umi#4918]
## What happens?

钉钉扫码加入umi 群，提示钉钉3群人数已满，超过1000人，无法加入

## 最小可复现仓库

无

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/86074512-b912fe80-bab8-11ea-8c3a-f28b071f0dfc.png)
二群还有50个位置

**Comment by tarvos21** [comment]
感谢，已加入钉钉群

@sorrycc @xiaohuoni 团队招前端吗？很想加入你们

**Comment by xiaohuoni** [comment]
@tarvos21 招人，简历私聊到 sorrycc@gmail.com 😊
