### ISSUE TITLE
如何在js里面获取publicPath的值

### ISSUE THREAD

**Issue by xgj1988** [umijs/umi#4919]
## What happens?

如何在js里面获取publicPath的值，比如这样
```
import { Icon } from '@ant-design/compatible';
import React from "react";

const Index = (props) => {
  const IconFont = Icon.createFromIconfontCN({ scriptUrl: `${context.config.publicPath}/iconfont/iconfont.js` })
  return (
    <IconFont {...props} />
  );
};

export default Index;

```

## 最小可复现仓库
 
无

## 复现步骤，错误日志以及相关配置
 这里我想引用本地的iconfont.js。但是这个文件又在public路径下面。如何做呢

## 相关环境信息

- **Umi 版本**： 3.0.14
- **Node 版本**： v10.13.0
- **操作系统**： win10

**Comment by xiaohuoni** [comment]
可以使用 https://umijs.org/config#runtimepublicpath

**Comment by xoptimal** [comment]
@xiaohuoni   怎么使用呀, 怎么在代码里拿到配置的 publicPath

**Comment by xiaohuoni** [comment]
@xoptimal window.publicPath 取不到吗？

**Comment by xgj1988** [comment]
额，，我自己写了一个 写了一个react的amap组件

**Comment by xoptimal** [comment]
@xiaohuoni  window.publicPath  你尝试打印下, 并不存在

**Comment by hyzx86** [comment]
同问。。。
要么 给出怎么获取 base 也行。。 这个关键字实在不好找
![image](https://user-images.githubusercontent.com/15613121/198878948-f8d1b572-56c8-4ca7-af5d-eff67025d6ed.png)
现在只能直接这样写么？
`const host = `${window.location.protocol}//${window.location.host}${APP_BASE_PATH}`;`

**Comment by hyzx86** [comment]
在 window 上找到  个 routerBase ， 可以用
![image](https://user-images.githubusercontent.com/15613121/198879512-b9ba6cdc-22e3-4195-b66a-27a4a1b0ae07.png)

**Comment by xiaohuoni** [comment]
__webpack_public_path

**Comment by hyzx86** [comment]
你们说的这些 。。前提都是 
runtimePublicPath:true,
文档地址在这里，umi文档 里面反而没有了
https://pro.ant.design/zh-CN/config/config#runtimepublicpath

然后我在本地尝试了下报错嘞。。
我的源码是 从 antdpro 仓库拉的 5.20 分支

**Comment by hyzx86** [comment]
runtimePublicPath:true
好了，是因为别的东西影响

**Comment by xiaohuoni** [comment]
https://umijs.org/docs/api/config#runtimepublicpath
这不就是文档吗？

**Comment by xiaohuoni** [comment]
> > https://umijs.org/docs/api/config#runtimepublicpath 这不就是文档吗？
> 
> 我用的 umi 3 , 你给的是 umi4 文档 无论怎样，感谢答复

emmmm，我才发现。
