### ISSUE TITLE
整理了一下#476 关于请求错误的问题（proxy）

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#492]
#476 
重现例子 https://github.com/xiaohuoni/umi-proxy-issue
问题表现：
### POST 没带分号 一直在pending 直到超时 
<p>Provisional headers are shown </p>
<p>"Content-type": "application/json; charset=UTF-8" </p>

### POST 带分号
<p>"Content-type": "application/json; charset=UTF-8;" </p>
返回数据是

```json
{
"id": 101
}
```

### POST 带分号 
<p>"Content-type": "application/json; charset=UTF-8;" </p>
返回数据是

```json
{
"id": 101
}
```
### POST 没带分号
<p>"Content-type": "application/json; charset=UTF-8" </p>
返回数据是

```json
{
  "title": "foo",
  "body": "bar",
   "userId": 1,
   "id": 101
}
```
## 不使用umi
没使用umi，和没使用proxy时表现是一致的，可以查看index.html文件

**Comment by xiaohuoni** [comment]
@superlbr
Here is the report of http packages
1.  suppose config like below
```
proxy: {
  "/api": {
    "target": "http://api.xxx.com/",
    "changeOrigin": true,
    "pathRewrite": { "^/api" : "" }
  }
}
```
2. suppose a post request `'/api/user/1' ` with `Content-Type: application/json;charset=UTF-8`, usually there'll be two request
    one is `'/api/user/1'`, another is `'/user/1'` because of proxy
3. what I found is there is no `'/user/1'` request
4. however a request with `content-type: multipart/form-data` is ok

**Comment by sorrycc** [comment]
赞！整理地很细致，我找时间看下这个问题。

**Comment by Instanced** [comment]
这个问题对ANT的upload组件有影响。服务端直接获取不到值了。

**Comment by xiaohuoni** [comment]
upload走的应该是formdata，应该不会有关系吧？

**Comment by Instanced** [comment]
@xiaohuoni 在没升级之前是没有问题的。现在我在服务端直接取不到值了，

**Comment by sorrycc** [comment]
相关问题，https://github.com/sorrycc/roadhog/issues/689

**Comment by sorrycc** [comment]
相关问题：

* https://segmentfault.com/q/1010000014957356
* https://github.com/sorrycc/roadhog/issues/689

**Comment by sorrycc** [comment]
测试后发现是把 mock 提到 proxy 之前引起的，`MOCK=none umi dev` 后是正常的，考虑把 proxy 放到 mock 之前。

**Comment by RisingSunYZ** [comment]
没使用umi ，post请求 后台接受不到参数，为null 。没有一直处于pending状态 就是后台接受不到参数

**Comment by RisingSunYZ** [comment]
@xiaohuoni 问一下 没有使用umi， antd 的post请求后台也获取不到参数(也没有pending) 请问什么情况？怎么解决？ 是哪个地方代理配置有问题嘛
