### ISSUE TITLE
如何开启bundle分析

### ISSUE THREAD

**Issue by a982564562** [umijs/umi#4920]
## What happens?

设置ANALYZE=1 之后运行时报'ANALYZE' 不是内部或外部命令，也不是可运行的程序或批处理文件。

PS D:\umi> yarn build
yarn run v1.22.4
$ ANALYZE=1 umi build
'ANALYZE' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## Context

- **Umi Version**:^3.2.6
- **Node Version**:12.13.1
- **Platform**: window10

**Comment by xiaohuoni** [comment]
window 使用环境变量 要加 set ，如 `set  ANALYZE=1 umi build`，一般是推荐使用 cross-env 
```
yarn add cross-env  
cross-env  ANALYZE=1 umi build
```
