### ISSUE TITLE
[Feature Request] 执行yarn create @umijs/umi-app时，download下来的模板是ts版本的，希望加个参数，能够直接下载js版本的

### ISSUE THREAD

**Issue by xuanxuan321** [umijs/umi#4921]
## Background

执行yarn create @umijs/umi-app时，download下来的模板是ts版本的

## Proposal

希望加个参数，（比如 --js）能够直接下载js版本的

**Comment by harry0071** [comment]
+1，求js版本的模板

**Comment by a982564562** [comment]
执行yarn create umi指令创建的项目可以选择配置
