### ISSUE TITLE
windows下开启预渲染打包无法创建文件夹

### ISSUE THREAD

**Issue by CassielLee** [umijs/umi#4923]
## What happens?
开启预渲染之后，配置动态路由会导致打包之后文件夹的名字存在:，导致在window下无法创建带:的文件夹而出错，请问这种情况要怎么解决？

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：umi3
- **Node 版本**：10.16.0
- **操作系统**：win10

**Comment by xiaohuoni** [comment]
相同的问题 https://github.com/umijs/umi/issues/5446

**Comment by xrkffgg** [comment]
试试这个 https://github.com/xrkffgg/umi-win-exportStatic
