### ISSUE TITLE
在umi中使用：new Promise((resolve,reject)=>{reject()})，在network会重新加载“umi.js” "umi.js.map"

### ISSUE THREAD

**Issue by lishaoh** [umijs/umi#4924]
### 问题描述 
项目中通过promise的reject()方法实现中止request时，network中会不断的加载umi.js、umi.js.map文件，这两个文件有什么用吗？能否取消？

### 开发环境
**umi:** 2.8.7
**umi-request:** 1.3.3

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
