### ISSUE TITLE
[求助] babel-loader fails to parse node module

### ISSUE THREAD

**Issue by pycxu** [umijs/umi#4925]
## What happens?
在使用 [Whois](https://www.npmjs.com/package/whois) module 的时候报错:
```
` error  in ./node_modules/whois/index.js

Module parse failed: Unexpected character '#' (1:0)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
> #!/usr/bin/env node
| // Generated by CoffeeScript 1.12.7
| (function () {

 @ ./src/pages/Dashboard/Popdomain.js 10:12-28
 @ ./src/pages/Dashboard/Analysis.js
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts`
```
## Mini Showcase Repository(REQUIRED)
https://github.com/pycxu/nozzle

## How To Reproduce
**Steps to reproduce the behavior:** 1. 2.
To reproduce the issue:
git clone https://github.com/pycxu/nozzle.git
npm i
npm run dev

## Context
问题好像是umi的babel-loader不能compile `#!/usr/bin/env node`.
stackoverflow上也有相关问题，其中一个解决方法是在webpack的配置中添加shebang-loader来自动去除`#!/usr/bin/env node`. 但是我也试过手动去除`#!/usr/bin/env node`，还是会报错：`net.isIP is not a function`
请问如何在config/config.js添加额外的loader或者如何配置umi来Compile nodejs based module？

{
I was trying to use a Nodejs based NPM module called Whois but Umi's babel-loader complains about `#!/usr/bin/env node`. Is there any way to resolve this by adding additional loader which I am not too sure how to do it. 

There is a shebang-loader that replaces `#!/usr/bin/env node` with empty space but I dont know how to include it to Umi's config.js file. Also I have tried to manually remove `#!/usr/bin/env node` but then I got error message saying `net.isIP is not a function` .

Any helps or suggestions would be appreciated :). 
}

**Comment by smddzcy** [comment]
I have the same issue. I want to transpile some of the modules in `node_modules`. Is there any way to do this?

**Comment by sorrycc** [comment]
https://unpkg.com/browse/whois@2.12.1/index.js
这是 bin 文件，咋能依赖使用呢？
