### ISSUE TITLE
umi 3 没有了 src/global.js 和 src/global.css 了吗？

### ISSUE THREAD

**Issue by kaoding** [umijs/umi#4928]
umi 2 截图
![image](https://user-images.githubusercontent.com/18542211/85994419-596e1200-ba2a-11ea-83a6-41f0dd5b70d9.png)

**Comment by ycjcl868** [comment]
有，`global.less`、`global.ts` js 也行

**Comment by kaoding** [comment]
umi 3的文档是没有说明，需要补充一下说明。

**Comment by MingShined** [comment]
从umi2升级到3，global.less没生效
