### ISSUE TITLE
Bug 若干

### ISSUE THREAD

**Issue by block-sexy** [umijs/umi#4930]
## 几个 bug
1、当本地开发时候，遇到致命错误，实时编译报错，到这里都 ok；但是修改完错误，不会再实时编译了，永远都不会了，除非重启；
2、.MD 内容的 tsx 代码，调用 其他 ts 文件，当遇到 函数中 使用 美元符开头的变量，会报错：
Syntax Error: SyntaxError: xx.tsx: Unexpected token, expected "}" ；
 

- **Umi 版本**："dumi": "^1.0.31",
- **Node 版本**：12
- **操作系统**：mac

**Comment by xiaohuoni** [comment]
第二个问题是指 dumi 的问题嘛？
