### ISSUE TITLE
url query的改变会触发组件的重新创建(只会多一次)

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#4931]
## What happens?
用的umi@^3.2.6, 然后看内部使用的react-router-dom版本是5.1.2
所以特地在react-router-dom官方的案例中用了5.1.2这个版本测试了下，发现官方的案例中 url query的改变不会有这个问题
但是在umi中(url query的改变会导致组件的重新加载) 由于是umi的应用不好给复现仓库，这里贴了一段最简单的代码可以直接用
1. 启动后进入页面会输出"组件初始化" （正常）
2. 点击test1或者test2 页面会输出"组件初始化" （不支持，query的改变不应该导致组件重新创建）
3.在切换test或者test2控制台不会再有输出了(说明组件没有再被销毁了)
```
import React, { useEffect } from 'react';
import { Link, useLocation } from 'umi';

export default () => {
  useEffect(() => {
    console.log('组件初始化');
  }, []);

  const location = useLocation();

  console.log(location['query']);

  return (
    <>
      <Link to={{ search: 'id=1' }}>test1</Link> &nbsp;
      <Link to={{ search: 'id=2' }}>test2</Link>
    </>
  );
};

 
```
## 操作步骤

这是直接使用react-router-dom的例子
https://reacttraining.com/react-router/web/example/query-parameters
![image](https://user-images.githubusercontent.com/7939085/86078164-16f71480-bac0-11ea-9824-11b71b82d3d4.png)

下图是本地使用umi的例子
![image](https://user-images.githubusercontent.com/7939085/86079035-0f386f80-bac2-11ea-8240-0b548f322cb1.png)

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by qhwc2009** [comment]
我也有同样的问题. 当想把filter数据存储在url的query里面的时候, 就会导致组件的 unmount

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
