### ISSUE TITLE
使用access插件,如何自定义权限错误界面?

### ISSUE THREAD

**Issue by z-lionel** [umijs/umi#4932]
看文档access插件, 默认渲染 Layout 插件内置的权限错误页面。

看到个解决方法用wrappers高阶组件自定义权限,但是菜单会默认显示,
而使用access时候,没有权限的菜单默认是隐藏的.

所以还是想要用access插件,那么如何将错误页面修改为自定义的组件?

**Comment by leftstick** [comment]
参考[中台助手](https://dfocusgroup.github.io/generator-umi/)的实现

**Comment by z-lionel** [comment]
1.通过高阶组件自定义错误界面, 
2.通过pro-layout的 menuDataRender,  自定义过滤菜单数据
这样就可以达到想要的效果
