### ISSUE TITLE
能否扩展增加一个loading的功能？

### ISSUE THREAD

**Issue by liujiayu10** [umijs/umi#4935]
import useRequest from '@umijs/use-request';
import request from '@/utils/Request';  //umi-request  extend

const SubmitData = useRequest((params) => { return request('/api/xxxx', { method: 'post', data: params }) }, { manual: true });

 SubmitData.run(params).then((response) => {
message.success('ok');
})

感觉这样有点不完美，甚至有点土的感觉。如果umi-request 能有loading  那就完全不需要useRequest , 我用useRequest 就是用一个loading 原来是用dva 也只是用一个dva的loading 功能。

**Comment by xiaohuoni** [comment]
这个还是需要项目中实现

**Comment by liujiayu10** [comment]
真诚感谢您的回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "小虎oni"<notifications@github.com&gt;; 
发送时间: 2020年9月18日(星期五) 下午3:47
收件人: "umijs/umi"<umi@noreply.github.com&gt;; 
抄送: "智佳"<15392155@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [umijs/umi] 能否扩展增加一个loading的功能？ (#4935)





 
这个还是需要项目中实现

**Comment by wangjingithub** [comment]
+1
