### ISSUE TITLE
`dynamic` function returns incorrect type `ComponentClass<{}, any>`

### ISSUE THREAD

**Issue by JoshOY** [umijs/umi#4936]
## What happens?

When creating a on-demand dynamic component using dynamic wrapper function, we found that the returned type of the on-demand component is always `ComponentClass<{}, any>`, where type of original component properties cannot be preserved or inferred from the component it loads.

## Mini Showcase Repository(REQUIRED)

https://github.com/JoshOY/umi-dynamic-function-bug-reproduce

## How To Reproduce

For instance:

In `Demo.tsx`:
```tsx
export interface DemoProps {
  propsA: string;
  propsB: boolean;
}

export const Demo: React.FC<DemoProps> = props => {
  // ...
}
```

In `AsyncDemo.tsx`:

```tsx
import { dynamic } from 'umi';

export const AsyncDemo = dynamic({
  async loader() {
    const { Demo } = await import('./Demo');
    // type of `Demo` can be inferred properly as `React.FC<DemoProps>`
    return Demo;
  },
});

export type AsyncDemoType = typeof AsyncDemo;  // <-- but here infers type `ComponentClass<{}, any>`
```

## Context

- **Umi Version**: 3.2.0-beta.11
- **Node Version**: v12.16.1
- **Platform**: OS X 10.14.6

## Possible Solution

Change the typing signature of function `dynamic ` (https://github.com/umijs/umi/blob/1be095aaf07e39a6bfc226b02e9e937846c5f465/packages/runtime/src/dynamic/dynamic.tsx#L9) to a template function, which allows developer to declare the return type.

The original function definition:

```tsx
export default function (opts: any) { ... }
```
 
Could be changed to:

```tsx
export default function <Props = {}>(opts: any): React.ComponentClass<Props> { ... }
```

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
