### ISSUE TITLE
使用layout布局插件，想开启右侧的登录按钮和用户名等，但是看了文档并不知道如何开启，有详细的例子吗？

### ISSUE THREAD

**Issue by wangyuan0108** [umijs/umi#4937]
![image](https://user-images.githubusercontent.com/22407253/86107866-02813f00-baf5-11ea-96c0-bf8b739a15a5.png)

文档看了几遍，这个运行时配置又依赖了几个插件，然后还是开启失败，能给个简单的开启demo吗？文档可能有点笼统。

**Comment by wangyuan0108** [comment]
是不是要依赖dva的数据流中的数据也没有表明

**Comment by wangyuan0108** [comment]
什么条件下可以触发logout方法，一直没有触发到这个方法

**Comment by wangyuan0108** [comment]
只要配置了运行时的配置函数,就只显示文字，不出图片和退出登录的按钮
```jsx
rightRender: initInfo => {
    return <div>{initInfo.name}</div>;
}, // return string || ReactNode;
```

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.

**Comment by Simoon-F** [comment]
请问有解决方案吗？
