### ISSUE TITLE
umi 1.3.3 运行umi-antd-admin 出错

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#494]
更新umi版本
```js
  "umi": "^1.3.3",
  "umi-plugin-dll": "^0.2.1",
  "umi-plugin-dva": "^0.7.2",
  "umi-plugin-routes": "^0.1.4"
```
执行npm start
无法启动项目，查看debug
程序停在了
```js
  af-webpack:send send {"type":"DONE"} +5s
```
重现项目 https://github.com/umijs/umi-antd-admin

**Comment by xiaohuoni** [comment]
```base
 "start": "cross-env  HARD_SOURCE=none DEBUG=umi*,af-webpack* BABELRC=1 BROWSER=none HOST=0.0.0.0 umi dev",
```
一样的问题，我试试另一个项目

**Comment by sorrycc** [comment]
一样的什么问题？卡住？

我找了台 windows 试了下 umi-antd-admin，没配 `HARD_SOURCE=none`，没有问题，二次启动 10s 不到。

**Comment by xiaohuoni** [comment]
![_20180518104107](https://user-images.githubusercontent.com/11746742/40213416-f0d12452-5a87-11e8-9285-04387c75a45f.png)
原来是编译通过了，但是没有自动打开页面。
手动访问http://localhost:8000，页面已经生成

**Comment by sorrycc** [comment]
所以，没有问题了？

umi-antd-admin 可以更新下代码，我把按需编译关了，umi@1.3.3 已经快到不需要按需编译了。

**Comment by xiaohuoni** [comment]
我更新一下，有问题再reopen
