### ISSUE TITLE
umijs框架创建模式选择complete   sass文件不编译

### ISSUE THREAD

**Issue by 52myu** [umijs/umi#4941]
## What happens?

umijs框架创建模式选择complete和 simple  sass文件不编译
simple模式下，yarn add @umijs/plugin-sass  sass文件可编译
complete模式下，yarn add @umijs/plugin-sass  sass文件不可编译
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
创建项目后，welcome 文件 scss code样式编译如下
simple
**< pre class="pre_**"><\/pre>**
complete
**< pre class="antd-pro-pages-welcome.scss-pre"><\/pre>**

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by xiaohuoni** [comment]
sass 要单独安装 https://umijs.org/plugins/plugin-sass
