### ISSUE TITLE
ssr-with-egg 构建完成后，start运行失败

### ISSUE THREAD

**Issue by JerryBerton** [umijs/umi#4945]
AssertionError [ERR_ASSERTION]: /Users/mac/Desktop/ssr-with-eggjs/config/manifest.json is required

**Comment by JerryBerton** [comment]
> AssertionError [ERR_ASSERTION]: /Users/mac/Desktop/ssr-with-eggjs/config/manifest.json is required

![image](https://user-images.githubusercontent.com/11454938/86202542-10869c80-bb95-11ea-98d8-b2b4693b41cd.png)

**Comment by JerryBerton** [comment]
2020-07-01 12:17:28,084 ERROR 81130 nodejs.AppWorkerDiedError: [master] app_worker#2:81134 died (code: 1, signal: null, suicide: false, state: dead), current workers: ["1","3","4"]
[egg-scripts]     at Master.onAppExit (/Users/idvert-wjb/Desktop/ssr-with-eggjs/node_modules/egg-cluster/lib/master.js:510:21)
[egg-scripts]     at Master.emit (events.js:311:20)
[egg-scripts]     at Messenger.sendToMaster (/Users/idvert-wjb/Desktop/ssr-with-eggjs/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
[egg-scripts]     at Messenger.send (/Users/idvert-wjb/Desktop/ssr-with-eggjs/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
[egg-scripts]     at EventEmitter.<anonymous> (/Users/idvert-wjb/Desktop/ssr-with-eggjs/node_modules/egg-cluster/lib/master.js:353:22)
[egg-scripts]     at EventEmitter.emit (events.js:323:22)
[egg-scripts]     at ChildProcess.<anonymous> (internal/cluster/master.js:193:13)
[egg-scripts]     at Object.onceWrapper (events.js:418:26)
[egg-scripts]     at ChildProcess.emit (events.js:311:20)
[egg-scripts]     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

**Comment by 104gogo** [comment]
https://github.com/104gogo/umiKeepalive2
可以试试我这个

**Comment by williamnie** [comment]
这个是egg的assets插件问题，可以配置在start模式下不启动这个插件，配下plugin的env就可以，或者需要在umi打包时生成mainfest文件，并且复制到egg的config目录，第一种方案是比较简单的
```
exports.assets = {
  enable: true,
  package: 'egg-view-assets',
  env:['local']
};
env支持数组，可以把你需要启动这个插件的环境都写上
```
这个插件只在dev的时候起作用
