### ISSUE TITLE
umi3 ssr 运行报serverRender.default is not a function

### ISSUE THREAD

**Issue by a982564562** [umijs/umi#4950]
## What happens?
clone umi-ssr-example-koajs 到本地 按照文档升级umi3 
执行 yarn start命令后 报错 TypeError: serverRender.default is not a function

项目地址:https://github.com/a982564562/umi-ssr

## Context

- **Umi Version**:3.2.6
- **Node Version**:12.13.1
- **Platform**:window10

**Comment by ycjcl868** [comment]
Umi 3 已内置 umi-server，使用请参考文档 https://umijs.org/docs/ssr#%E9%83%A8%E7%BD%B2
