### ISSUE TITLE
[Feature Request] archive compiled umi.js but not need to be injected into result index.html

### ISSUE THREAD

**Issue by code-brewer** [umijs/umi#4954]
## Background

 In my case, there is some injected js object for umi UI to use. 
So, I want to delay the loading umi.js till some injected js object 

```
        var injectJsTagToBody = function () {
          var s = document.createElement("script");
          s.type = "text/javascript";
          s.src = "./umi.js";
          document.body.appendChild(s);
        };

    while (!window.myInjectedObject) {
      //sleep 100ms 
    }

   injectJsTagToBody()

```

 However, I don't know how to prevent `yarn build` to inject `    <script src="./umi.js"></script> ` to  document.ejs.

 I simple try delete `<div id="root"></div>` from document.ejs, no luck, alway have index.html with auto injected umi.js

## Proposal

 Maybe some configuration needs to add. Or I miss something.

## Additional context

 None.

**Comment by 104gogo** [comment]
When build complite, I rewrite the html by self.
Or try modifyHtml api, gl!

**Comment by no13bus** [comment]
这个问题有解决办法吗

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
