### ISSUE TITLE
Uniform configuration antd prefixCls ​​not working

### ISSUE THREAD

**Issue by somychfudewe** [umijs/umi#4956]
## What happens?

`@umijs/plugin-antd` uniform configuration `prefixCls` ​​not working.

## Mini Showcase Repository(REQUIRED)

[Demo](https://github.com/somychfudewe/umi-antd-prefixc-class-demo)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
```ts
// .umirc.ts
{
  "antd": {
    "config": {
      "prefixCls": "test-ant"
    }
  }
}
```
**Expected behavior** 1. 2.

Normal display antd style.

## Context

- **Umi Version**: 3.2.7
- **Node Version**: 13.9.0
- **Platform**: macOS
- **antd**: 4.4.0

**Comment by xiaohuoni** [comment]
cooperated with @ant-prefix
