### ISSUE TITLE
通过官方工具创建项目，跑起来有一个警告

### ISSUE THREAD

**Issue by GeNa-jj** [umijs/umi#4958]
通过官方工具创建项目
yarn create @umijs/umi-app
跑起来
警告：
react-error-overlay is not meant for use in production. You should ensure it is not included in your build to reduce bundle size.

请问怎么去掉。还是说你们要去优化一下？

**Comment by fandepeng1993** [comment]
> 通过官方工具创建项目
> yarn create @umijs/umi-app
> 跑起来
> 警告：
> react-error-overlay is not meant for use in production. You should ensure it is not included in your build to reduce bundle size.
> 
> 请问怎么去掉。还是说你们要去优化一下？

我大神 我想问 您解决了吗？我现在也出现这个问题呢

**Comment by fandepeng1993** [comment]
> 通过官方工具创建项目
> yarn create @umijs/umi-app
> 跑起来
> 警告：
> react-error-overlay is not meant for use in production. You should ensure it is not included in your build to reduce bundle size.
> 
> 请问怎么去掉。还是说你们要去优化一下？

大神，我也出现这个问题了，请问您是如何解决的呢？

**Comment by GeNa-jj** [comment]
> > 通过官方工具创建项目
> > yarn create @umijs/umi-app
> > 跑起来
> > 警告：
> > react-error-overlay is not meant for use in production. You should ensure it is not included in your build to reduce bundle size.
> > 请问怎么去掉。还是说你们要去优化一下？
> 
> 大神，我也出现这个问题了，请问您是如何解决的呢？

**Comment by GeNa-jj** [comment]
@fandepeng1993  大神，我也没解决呢

**Comment by huangchj** [comment]
这要怎么解决？

**Comment by yejiajiehz** [comment]
同遇到该问题  
umi 版本：3.2.14

警告来自 umi `@@devScripts.js` 看了一下代码，应该是 process.env.NODE_ENV 判断出问题了  
![image](https://user-images.githubusercontent.com/1755967/89984293-bad10400-dcab-11ea-8da3-96173edfcf96.png)

本地确认过 process.env.NODE_ENV 为 development    

附： react-error-overlay  代码

https://github.com/facebook/create-react-app/blob/react-error-overlay%406.0.7/packages/react-error-overlay/src/index.js#L188
![image](https://user-images.githubusercontent.com/1755967/89984188-8f4e1980-dcab-11ea-8285-701811e9001d.png)

**Comment by laozhu** [comment]
我也有这个warning，感觉是不是判断判断反掉了，在 development 下显示了这个警告。

**Comment by yingzhiji** [comment]
react-error-overlay 源码里是这样判断的，但为什么在开发环境下还是有警告
```javascript
if (process.env.NODE_ENV === 'production') {
  console.warn(
    'react-error-overlay is not meant for use in production. You should ' +
      'ensure it is not included in your build to reduce bundle size.'
  );
}
```

**Comment by fengerzh** [comment]
> react-error-overlay 源码里是这样判断的，但为什么在开发环境下还是有警告
> 
> ```js
> if (process.env.NODE_ENV === 'production') {
>   console.warn(
>     'react-error-overlay is not meant for use in production. You should ' +
>       'ensure it is not included in your build to reduce bundle size.'
>   );
> }
> ```

`react-error-overlay`源码没写错，是`umi`自己写错了。

**Comment by kaoding** [comment]
devScripts.js:6731 react-error-overlay is not meant for use in production. You should ensure it is not included in your build to reduce bundle size.

**Comment by yolio2003** [comment]
一直没人解决一下 哎 换吧 ~

**Comment by ETRick** [comment]
目前用的是 umi 3..4.5, 其集成了 `react-dev-inspector` 这个 npm 包，导致依赖了 react-dev-inspector。这个 npm 包在使用了 sourcemap 的情况下显得比较鸡肋，且在 chrome dev 模式下查看源码时会注入大量 debug 用的信息，干扰视线，降低 debug 效率，希望能去掉这个依赖。

**Comment by jiyingzhi** [comment]
umi 3.4.8 这个问题又出现了
