### ISSUE TITLE
yarn build打包后作为静态资源，egg使用模版引擎render后，加载到js，但页面dom元素没有加载。

### ISSUE THREAD

**Issue by ppatch** [umijs/umi#4960]
yarn build打包后作为静态资源，egg使用模版引擎render后，浏览器访问加载到js，但页面dom元素没有挂载。

serve ./public 能正常起服务

**Comment by williamnie** [comment]
什么意思？是ssr模式？有复现么？

**Comment by xiaohuoni** [comment]
@ppatch 提供复现demo再reopen
