### ISSUE TITLE
打包后不能在chrome插件中运行

### ISSUE THREAD

**Issue by yubin-code** [umijs/umi#4965]
umi目前是不是只能服务器运行，因为chrome插件是静态文件运行的时候不显示任何内容空白的

**Comment by xiaohuoni** [comment]
猜测配置 `publicPath: './',` 应该可以，具体还是要看一下报错

**Comment by Java-http** [comment]
> umi目前是不是只能服务器运行，因为chrome插件是静态文件运行的时候不显示任何内容空白的
1. 设置 publicPath: './'
2. history:{ type: 'hash' },设置哈希路由

```
  publicPath:'./',
  history:{ type: 'hash' },
```
