### ISSUE TITLE
3.2.7 版本，开启ssr提示 plugin-model: Invoking '@@initialState' model failed: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by kwooshung** [umijs/umi#4967]
什么都没安装，就是按照官方文档来的，只是开启了`ssr:{}`配置后，出了问题

**Comment by ycjcl868** [comment]
https://umijs.org/zh-CN/docs/ssr#window-is-not-defined-document-is-not-defined-navigator-is-not-defined

FAQ 有

**Comment by yucccc** [comment]
可事实上没有没有使用到window的方法

**Comment by ycjcl868** [comment]
plugin-model 插件问题
