### ISSUE TITLE
Javascript: [app.model] namespace should be unique

### ISSUE THREAD

**Issue by SagittariusZhu** [umijs/umi#4969]
官方约定式的 model 组织方式中说明符合以下规则的文件会被认为是 model 文件，
```
src/models 下的文件
src/pages 下，子目录中 models 目录下的文件
src/pages 下，所有 model.ts 文件
```
注意哦，这里说的是`model.ts`文件，如果是用javascript开发的`model.js`文件虽然会被认为是model文件，但并不会去取文件中的`namespace`定义，而是直接用文件名，也就是`model`作为namespace，显然这是一个逻辑错误。

建议的解决方法当然是对于js文件，也应该取其中定义的`namespace`，而不应该直接用文件名。

**Comment by SagittariusZhu** [comment]
我的错误，不是系统问题。

**Comment by zheillen** [comment]
我这边也出现了这个问题，请问你的错误是啥，我借鉴一下
