### ISSUE TITLE
我们老板发火了，说我们开发人员选的什么狗屁框架，烂透了，可是我们技术人员知道umi是个好东西，只是有点儿问题，联系不上官方人员解决而已。

### ISSUE THREAD

**Issue by kwooshung** [umijs/umi#4970]
## 我们老板发火了，说我们开发人员选的什么狗屁框架，烂透了
可是我们技术人员知道umi是个好东西，只是有点儿问题，联系不上官方人员解决而已。

**Comment by kwooshung** [comment]
在一个朋友的帮助下解决了~

**Comment by williamnie** [comment]
解决了么？没解决，给个复现，我帮忙看看

**Comment by hector12free** [comment]
确实微信钉钉交流群现在都进不了呢 按着微信公众号的提示来并没有回复，钉钉群也满了进不了

**Comment by LeoHuiyi** [comment]
来不及就自己fork个改，给官方提个pr。

**Comment by williamnie** [comment]
ssr的群二维码
![image](https://user-images.githubusercontent.com/26871884/86525570-54421480-bebb-11ea-88cc-6fed7dd8fdf2.png)

**Comment by CassielLee** [comment]
你好，请问怎么解决的呀？我也有同样的问题，我之前换了版本没问题了，但是发现打包的时候还是不行

**Comment by sorrycc** [comment]
@CassielLee 哪个问题？

**Comment by 104gogo** [comment]
稳住老哥，这波操作666，官方别划了呀~

**Comment by youngjuning** [comment]
这就过分了，React 还各种BUG呢

**Comment by CassielLee** [comment]
> @CassielLee 哪个问题？

1、动态路由开始预渲染打包之后访问动态路由时会先加载首页的内容，目前还没有找到解决办法；
2、配置动态路由开启预渲染之后打包生成的文件夹是以冒号开头的，如:id这种，由于windows操作系统不允许以冒号开头命名文件夹，所以导致在windows系统上没办法打包，或者是别人打包之后代码也没办法拉下来；
3、按照官方配置的IE兼容配置不生效，还是没办法兼容IE；
以上是比较典型的几个问题，在不同的渠道都有提过问题，但是一直没有人帮忙解决，请麻烦看一下～感谢！

**Comment by iceberg211** [comment]
做ssr为啥不用next.js ?

**Comment by regischen** [comment]
> ssr的群二维码
> ![image](https://user-images.githubusercontent.com/26871884/86525570-54421480-bebb-11ea-88cc-6fed7dd8fdf2.png)

当前群聊仅群主可添加群成员

**Comment by vipliucheng** [comment]
> ssr的群二维码 ![image](https://user-images.githubusercontent.com/26871884/86525570-54421480-bebb-11ea-88cc-6fed7dd8fdf2.png)

能带我进群吗，哈哈哈哈。钉钉号 goodjobandlife

**Comment by CassielLee** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件已收到，我会尽快给您回复，谢谢！

**Comment by linliwei999** [comment]
> ssr的群二维码 ![image](https://user-images.githubusercontent.com/26871884/86525570-54421480-bebb-11ea-88cc-6fed7dd8fdf2.png)

二维码过期了，能在重新发一个么

**Comment by little077** [comment]
+11111111111，难受死了，报错提示加群，文档所有的二维码都失效了

**Comment by CassielLee** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件已收到，我会尽快给您回复，谢谢！

**Comment by iemi** [comment]
千万别用这垃圾框架搞ssr，谁用谁知道

**Comment by CassielLee** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件已收到，我会尽快给您回复，谢谢！
