### ISSUE TITLE
运行时配置请求后台菜单数据延时的问题，有办法解决吗?

### ISSUE THREAD

**Issue by tonyjync** [umijs/umi#4972]
## umi3 运行时配置请求后台菜单数据延时的问题

1、用umi3快速指南生成了项目
2、config.ts配置了layout和routes
3、app.tsx配置了layout,想通过请求后台数据生成菜单，发现在启动开始不是显示后台请求的菜单，过儿点击菜单的时候可以显示请求的菜单，我了解请求数据是异步的有延时，请问有办法解决启动后就显示请求的后台菜单吗？是不是我在这里处理思路不对，有没有其他办法？
下面是代码：
import request from 'umi-request';

function getUsername() {
      request('/api/getMenuData', {
        method: 'get',
        params: { id: 1 },
        })
        .then(function(response) {
          menuData=response.data
          console.log(menuData)
          return menuData
        })
        .catch(function(error) {
          console.log(error);
        });
}
let menuData;

    menuData=[
      {
        path: '/',
        name: 'welcome',
        icon:'icon-smile',
        children: [
          {
            path: '/welcome',
            name: 'one',
            icon:'icon-menu',
            children: [
              {
                path: '/welcome/welcome',
                name: 'two',
                exact: true,
                icon:'icon-user'
              },
            ],
          },
        ],
      },
      {
        path: '/user',
        name: '用户',
        icon:'icon-user'
      },
];

export const layout = { 
    logout: () => {}, // do something 
    rightRender:(initInfo)=> { console.log(initInfo);return 'hahah'; },// return string || ReactNode;
    menuDataRender:() => menuData,
    iconfontUrl:'/iconfont/iconfont.js'
  };

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

改动的就要是这个文件，其他的基本就是脚手架代码。

## 相关环境信息

- **Umi 版本---3.2.7**：
- **Node 版本---v12.13.0**：
- **操作系统---OSX EI Capitan 10.11.6**：

**Comment by xiaohuoni** [comment]
请求数据肯定是耗时的，这个希望怎么解决？
