### ISSUE TITLE
不在models目录下的model不会被引入

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#498]
如
src/models2
src/models3

**Comment by sorrycc** [comment]
model 为啥不放 models 目录下？

**Comment by xiaohuoni** [comment]
这个问题我也很好奇

**Comment by sorrycc** [comment]
这是约定，就按约定的来吧。

**Comment by NexxLuo** [comment]
实际情况是这样的，项目里将一些公共页面给提取出来了，以备之后的项目能继续使用。目录结构如下：
src/commonPages

src/commonPages里必然会存在model，如：
src/commonPages/page1/models
src/commonPages/page1/services
src/commonPages/page1/components


实际上model的目录依然是models，只是不在跟目录下。
之前使用umi-plugin-dva 0.1.5 ，这种情况是支持的。

更新了umi-plugin-dva 0.7.2后，src/commonPages下的models无法被找到。

目前更新了umi 1.3.3 ，但是umi-plugin-dva 0.1.5。不知道是否会对打包速度有影响
