### ISSUE TITLE
约定路由[id].js 或者routers中 配置 path: ‘/:id'  开启  exportStatic:{}, 不使用 hash   编译会报错no such file or directory

### ISSUE THREAD

**Issue by zhanchengkun** [umijs/umi#4981]
## What happens?

约定路由[id].js 或者routers中 配置 path: ‘/:id' 开启 exportStatic:{}, 不使用 hash 编译会报错

no such file or directory

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：^3.2.6
- **Node 版本**：v12.13.1
- **操作系统**：win10 企业版

**Comment by CassielLee** [comment]
我们也遇到了这个问题，这个是因为win系统不支持冒号开头命名文件夹~

**Comment by xiaohuoni** [comment]
@sorrycc cc

**Comment by xrkffgg** [comment]
试试这个 https://github.com/xrkffgg/umi-win-exportStatic

**Comment by sorrycc** [comment]
exportStatic 不支持动态路由的。
