### ISSUE TITLE
菜单栏点击路由跳转的时候，有时候会报错

### ISSUE THREAD

**Issue by zhangyoof** [umijs/umi#4984]
## What happens?

菜单点击导致路由切换的时候，有时候会报错 Uncaught( in promise ) ChunkLoadErroe : Loading chunk 110 failed .

## Context

- **Umi Version**:2.13.7
- **Node Version**:8.17.0
- **Platform**:windows 10

**Comment by leftstick** [comment]
这个事是不是发生在你重新部署了服务，但浏览器之前就打开了页面，并且在重新部署服务后也没刷新？

**Comment by zhangyoof** [comment]
> 这个事是不是发生在你重新部署了服务，但浏览器之前就打开了页面，并且在重新部署服务后也没刷新？
不是，就是在一次部署后，用户处长时间处在一个菜单内，然后切换菜单有时候就会报这个错误，中间也没有进行重新部署

**Comment by leftstick** [comment]
这太6了，这种问题一般就是资源不存在了。但照你的说法它是不应该不存在的。但我觉得你还是得朝这个思路找下去。

1. 报错的请求，直接贴到地址栏里，看看能否下载下来。
2. 到服务器上检查，该资源是否还健在

**Comment by zhangyoof** [comment]
> 这太6了，这种问题一般就是资源不存在了。但照你的说法它是不应该不存在的。但我觉得你还是得朝这个思路找下去。
> 
> 1. 报错的请求，直接贴到地址栏里，看看能否下载下来。
> 2. 到服务器上检查，该资源是否还健在

好的 我试一下

**Comment by wangchaoHeart** [comment]
> 这个事是不是发生在你重新部署了服务，但浏览器之前就打开了页面，并且在重新部署服务后也没刷新？
我遇到了这个问题就很你描述的一模一样，应该怎么解决这种情况？
我想着是能捕捉到这个错误，然后我手动刷新，但是我没找到捕捉的入口。
@leftstick
