### ISSUE TITLE
wrappers的路由权限配置

### ISSUE THREAD

**Issue by meiqinLiu** [umijs/umi#4990]
## What happens?

官网提供的 src/wrappers/auth 代码不是特别明白，我想要跳转到登录页，需要怎么写呢。

````
export default (props) => {
  const { isLogin } = useAuth();
  if (isLogin) {
    return <div>{ props.children }</div>;
  } else {
    redirectTo('/login');   
  }
}
```
 上面代码中的这个redirectTo是umi的吗，如果是的话当前版本无法引入
如果不是，可不可以提供一下redirectTo函数的方案


## 相关环境信息

- **Umi 版本**：3.2.3
- **Node 版本**：v12.16.2
- **操作系统**：wimdow

**Comment by leftstick** [comment]
`redirectTo` 的实现可以是`window.location.href = xxx`，也可以参考[history.push](https://umijs.org/api#history)

**Comment by meiqinLiu** [comment]
> `redirectTo` 的实现可以是`window.location.href = xxx`，也可以参考[history.push](https://umijs.org/api#history)

你好，我使用push配置的时候页面是跳转了，但是由于这个是高阶组件，出错了,
我的配置是这样的
```
const redirectTo = (url:string) => {
  history.push('/account/login')
}
```
报错如下：
![image](https://user-images.githubusercontent.com/38028974/86891299-31209a80-c131-11ea-89f1-20693ccd5506.png)

**Comment by leftstick** [comment]
@meiqinLiu 
那就改成

```ts
import { Redirect } from 'umi'

export default (props) => {
  const { isLogin } = useAuth();
  if (isLogin) {
    return <div>{ props.children }</div>;
  } else {
    return <Redirect to="/login" />
  }
}
```

**Comment by meiqinLiu** [comment]
> @meiqinLiu
> 那就改成
> 
> ```ts
> import { Redirect } from 'umi'
> 
> export default (props) => {
>   const { isLogin } = useAuth();
>   if (isLogin) {
>     return <div>{ props.children }</div>;
>   } else {
>     return <Redirect to="/login" />
>   }
> }
> ```

**Comment by meiqinLiu** [comment]
> > @meiqinLiu
> > 那就改成
> > ```ts
> > import { Redirect } from 'umi'
> > 
> > export default (props) => {
> >   const { isLogin } = useAuth();
> >   if (isLogin) {
> >     return <div>{ props.children }</div>;
> >   } else {
> >     return <Redirect to="/login" />
> >   }
> > }
> > ```


这么写提示错误 https://github.com/umijs/umi/issues/4990#issuecomment-655362834
运行起来也是报错的 
![image](https://user-images.githubusercontent.com/38028974/86894532-c4f46580-c135-11ea-81d9-3ac530e89a18.png)
我的umi版本号是3.2.3 ，

**Comment by meiqinLiu** [comment]
> @meiqinLiu
> 那就改成
> 
> ```ts
> import { Redirect } from 'umi'
> 
> export default (props) => {
>   const { isLogin } = useAuth();
>   if (isLogin) {
>     return <div>{ props.children }</div>;
>   } else {
>     return <Redirect to="/login" />
>   }
> }
> ```

使用这个写法运行时报错
![image](https://user-images.githubusercontent.com/38028974/86895229-c4100380-c136-11ea-9ef3-aab169bd1eea.png)
我目前的版本号是3.2.3

**Comment by leftstick** [comment]
怎么会报语法错误。。。。把文件名改成`auth.tsx` 试试吧

**Comment by meiqinLiu** [comment]
> 怎么会报语法错误。。。。把文件名改成`auth.tsx` 试试吧

可以了，非常感谢您哈。

**Comment by meiqinLiu** [comment]
感觉写发送了很奇怪的事情

**Comment by leftstick** [comment]
要写函数，你也至少得return嘛，没有return 那算的哪门子组件嘛，如下：

```ts
const redirectTo = (url:string) => {
  return <Redirect to={url} />;
}

export default (props: Props) => {
  const isLogin = useAuth();
  if (isLogin) {
    return props.children;
  }
  return redirectTo('/account/login'); 
}
```

**Comment by betazk** [comment]
想请教下，Wrapper路由权限和umi的useAccess有什么区别呢？
