### ISSUE TITLE
[Feature Request] 微前端框架下动态增加微前端路由

### ISSUE THREAD

**Issue by topwood** [umijs/umi#4995]
## Background

umi 中有 patchRoutes 可以实现路由的动态加载

```
export function patchRoutes(routes) {
  routes[0].unshift({
    path: '/foo',
    component: require('./routes/foo').default,
  });
}
```

甚至这样

```
export function async patchRoutes(routes) {
  fetch('/getApps').then(apps => {
    xxxx
 })
  
}
```

但是在微前端框架下，这种微前端的component没有动态添加的方法，例如

```
export async function patchRoutes({ routes }) {
  const apps = await request('/apps')
  const old = routes[0].routes;
  const newRoutes = apps.map(app => ({
    path: `/${app.name}`,
    exact: false,
    microApp: `/${app.name}`,
  })).concat(old);
  routes[0].children = newRoutes;
  routes[0].routes = newRoutes;
}
```

这种方式是不会直接生效的，不知道怎么去指定component

## Proposal

微前端框架下动态增加微前端路由

```
export async function patchRoutes({ routes }) {
  const apps = await request('/apps')
  const old = routes[0].routes;
  const newRoutes = apps.map(app => ({
    path: `/${app.name}`,
    exact: false,
    microApp: `/${app.name}`,
    component: <MicroApp name={app.name}/> // 指定微前端的子应用
  })).concat(old);
  routes[0].children = newRoutes;
  routes[0].routes = newRoutes;
}
```
类似这种方式，可以做到动态添加微前端的路由。

**Comment by kuitos** [comment]
自己 patchRoutes 的话这样就可以了吧

```diff
export async function patchRoutes({ routes }) {
  const apps = await request('/apps')
  const old = routes[0].routes;
  const newRoutes = apps.map(app => ({
    path: `/${app.name}`,
    exact: false,
-   microApp: `/${app.name}`,
+   component: () => <MicroApp name={app.name}/>
  })).concat(old);
  routes[0].children = newRoutes;
  routes[0].routes = newRoutes;
}
```

**Comment by blueju** [comment]
> 自己 patchRoutes 的话这样就可以了吧
> 
> ```diff
> export async function patchRoutes({ routes }) {
>   const apps = await request('/apps')
>   const old = routes[0].routes;
>   const newRoutes = apps.map(app => ({
>     path: `/${app.name}`,
>     exact: false,
> -   microApp: `/${app.name}`,
> +   component: () => <MicroApp name={app.name}/>
>   })).concat(old);
>   routes[0].children = newRoutes;
>   routes[0].routes = newRoutes;
> }
> ```

实测无效。

![image](https://user-images.githubusercontent.com/49681036/92393290-42e2e600-f152-11ea-9f65-8cfd29c319eb.png)

![image](https://user-images.githubusercontent.com/49681036/92393322-4e361180-f152-11ea-911d-a051caf39d93.png)

![image](https://user-images.githubusercontent.com/49681036/92393347-57bf7980-f152-11ea-9f9f-4a56f83e9590.png)

是我哪里写错了吗？
