### ISSUE TITLE
打包部署时去掉console.log及debugger不生效

### ISSUE THREAD

**Issue by zhangyoof** [umijs/umi#4998]
## What happens?

`如题：打包部署时去掉console.log及debugger不生效`，.umirc.js文件如下配置
`const routes = require('./src/routes')
const webpack = require('webpack')
const resolve = require('path').resolve
const caseSensitivePathsWebpackPlugin = require('case-sensitive-paths-webpack-plugin')

export default {
  ignoreMomentLocale: true,
  publicPath: '/',
  hash: true,
  routes,
  plugins: [
    ['umi-plugin-react', {
      antd: true,
      dva: {
      },
      dynamicImport: {
        webpackChunkName: true,
        loadingComponent: './components/Loader/Loader',
      },
      chunks: ['vendors', 'config', 'umi'],
      locale: {
        enable: true,
        default: 'zh-CN', // default zh-CN
        baseNavigator: true, // default true, when it is true, will use navigator.language overwrite default
        antd: true, // use antd, default is true
      }
    }],
    
  ],
  extraBabelPlugins: [
    ['import', {libraryName: "ewec", libraryDirectory: "lib/components"}],
    ['transform-remove-console', { "exclude": [ "error", "warn"] }]  //打包去除debugger及console.log
  ],
  proxy: {
    '/api': {
      target: 'http://127.0.0.1:9049/',
      changeOrigin: true,
      "pathRewrite": {"^/api": ""}
    },
  },
  // 设置文件夹别名
  alias: {
    src: resolve(__dirname, './src/'),
    config: resolve(__dirname, './src/config/'),
    pages: resolve(__dirname, './src/pages/'),
    utils: resolve(__dirname, './src/utils/'),
    services: resolve(__dirname, './src/services/'),
    assets: resolve(__dirname, './src/assets/'),
  },
  chainWebpack(config, {webpack}) {
    config.plugin('case-sensitive-paths-webpack-plugin').use(caseSensitivePathsWebpackPlugin);
    config.optimization.splitChunks({
      cacheGroups: {
        config: {
          name: 'config',
          chunks: 'all',
          filename: 'config.js',
          enforce: true,
          test: /[\\/]config[\\/]commonConfig/,
        },
        vendors: {
          name: 'vendors',
          chunks: 'all',
          //filename: 'vendors.js',
          test: /[\\/]node_modules[\\/](react|react-dom|react-router|react-router-dom)[\\/]/,
        },
        commons: {
          name: 'commons',
          chunks: 'async',
          minChunks: 2,
          minSize: 0,
        },
      },
    })
  },
//打包去除debugger及console.log
  uglifyJSOptions(opts) {
    opts.uglifyOptions.compress.drop_debugger = true;
    opts.uglifyOptions.compress.drop_console = true;
    return opts;
  },
}
`

## Context

- **Umi Version**:2.13.7
- **Node Version**:8.17.0
- **Platform**:Windows 10

**Comment by williamnie** [comment]
配置这个试试
```
uglifyJSOptions = {
    uglifyOptions: {
      compress: {
        drop_console: true,
        pure_funcs: ['console.error', 'console.warn'],
      },
    },
  };
```

**Comment by zhangyoof** [comment]
> 配置这个试试
> 
> ```
> uglifyJSOptions = {
>     uglifyOptions: {
>       compress: {
>         drop_console: true,
>         pure_funcs: ['console.error', 'console.warn'],
>       },
>     },
>   };
>好的，我试下，谢谢了

**Comment by Aric-sky** [comment]
亲测！umijs下配置，以下方式有效。
```
uglifyJSOptions(opts) {
    opts.uglifyOptions.compress.warnings = true;
    opts.uglifyOptions.compress.drop_debugger = true;
    opts.uglifyOptions.compress.drop_console = true;
    return opts;
  }
```

**Comment by qingfengmy** [comment]
文档中都看不到相关说明

**Comment by jjj201200** [comment]
指路 [https://umijs.org/zh-CN/config#terseroptions](https://umijs.org/zh-CN/config#terseroptions)
