### ISSUE TITLE
1.3.3静态文件无法访问

### ISSUE THREAD

**Issue by scfido** [umijs/umi#500]
项目请见：https://github.com/scfido/umiStaticFile
### umi 1.2.2  
访问http://localhost:3000/logo.png，正常显示图片

### 执行升级到1.3.3
```
npm update -g umi
```

再访问
显示
> umi development 404 page
 There's not a page yet at /logo.png
 Create a React.js component in your pages directory at src/pages/logo.png.js and this page will 
 automatically refresh to show the new page component you created.
 Page List
/
/
/tabel

**Comment by neil-mao** [comment]
public 目录下的所有资源 build 之后 都被放到 static 目录了，所以无法访问了

跟踪了一下生成的webpack配置，有如下

webpackConfig: { bail: true,
  devtool: undefined,
  entry:
   { umi:
      [ 'xxxx/node_modules/umi-build-dev/template/setPublicPath.js',
        'xxxx/src/pages/.umi-production/umi.js' ] },
  output:
   { path: 'xxxxx/dist/static',
     pathinfo: false,
     filename: '[name].[chunkhash:8].js',
     publicPath: '/static/',
     chunkFilename: '[name].[chunkhash:8].async.js' },
  resolve:


即使设置了环境变量

PUBLIC_PATH=/  umi build

生成的webpack配置是

webpackConfig: { bail: true,
  devtool: undefined,
  entry:
   { umi:
      [ 'xxxxx/node_modules/umi-build-dev/template/setPublicPath.js',
        'xxxxx/src/pages/.umi-production/umi.js' ] },
  output:
   { path: 'xxxxx/dist/static',  <--------------
     pathinfo: false,
     filename: '[name].[chunkhash:8].js',
     publicPath: '/',
     chunkFilename: '[name].[chunkhash:8].async.js' },
  resolve:

是不是生成webpack配置的地方有问题？

**Comment by xiaohuoni** [comment]
@neil-mao  `PUBLIC_PATH=/ umi build` 这个设置的是publicPath不是path 你的指针往下三行

**Comment by neil-mao** [comment]
我的环境是这样的，解释一下：

指定一个 doucment.ejs,里面调用了第三方的JS
<script type="text/javascript" src="test.js"></script>
test.js 是放在 public 目录下的

目前测试下来，开发正常，build 出来之后，test.js 被放到了 /dist/static 目录下，显然就不对了

无论是否设置 PUBLIC_PATH=/  ，所有 public 的资源都会放到 /dist/static 下
这个变量仅会影响 index.html 里的这段 js： “window.publicPath=...."

跟踪了一下源码，应该底层调用webpack的时候，把public里的内容拷贝到里 dist/static 目录
require('af-webpack/dev').default({...})

目前我这样解决绕过去的

1. 把public 目录改名，比如 修改成 public_asset 防止build 的时候拷贝位置错误
2. 修改 node_modules/umi-build-dev/lib/Service.js 里启动 webpack 开发服务器的contentBase设置
 
contentBase: './path-do-not-exists',
 改成
 contentBase: './public_asset',

3. 在package.json 里 建一个 postBuild 脚本
"postbuild": "node ./copyPublicAsset.js"
把资源拷贝到 /dist目录

**Comment by xiaohuoni** [comment]
第三方文件可以在global.js里面写。就不会有路径问题啦

**Comment by neil-mao** [comment]
就是因为要引用很多外部的js，微信JSSDK，webim sdk之类的
所以写在global.js里，是不可行的。

另外，看里一下 umi 的 html 生成机制，
node_modules/umi-build-dev/lib/html/getHTMLContent.js 
第47行附近
context.path = context.path || path; 
let html = _ejs.default.render(tpl, context, {
    _with: false,
    localsName: 'context'
  });

对于全局模版 document.ejs context  是空对象，path 是 undefined 
所以没有办法通过配置 context变量来控制 index.html 的生成

也期待官方也增强这个，这样模版里可以用变量来引用第三方的JS了

**Comment by sorrycc** [comment]
有问题再 reopen 。

**Comment by neil-mao** [comment]
@sorrycc  就根本没解决，就close？

随便放个 文件在public下，发布出来之后都会到 /static目录下

我现在解决方法就是弄个 postbuild脚本，再搬出来

**Comment by sorrycc** [comment]
和 #637 是同一个问题。

**Comment by scfido** [comment]
经过测试1.3.13版本，此问题依然存在。 @sorrycc
