### ISSUE TITLE
umi 3.0, 默认支持eslint嘛？ 或者说怎么开启和关闭。配置了eslint-config-umi不生效

### ISSUE THREAD

**Issue by chaiguanpeng** [umijs/umi#5000]
.eslintrc文件配置如下，但是没有作用
{
  "extends": "eslint-config-umi",
  "rules": {}
}

**Comment by zevingao** [comment]
请问你解决了吗，我也遇到了相同的问题

**Comment by chaiguanpeng** [comment]
看umi的.eslintrc文件，用了一个@umijs/fabric/dist/eslint。具体配置如下
module.exports = {
  extends: [require.resolve('@umijs/fabric/dist/eslint')],
  rules: {
    'import/no-unresolved': 0,
    'no-underscore-dangle': 0,
    'import/no-extraneous-dependencies': 0,
    'global-require': 0,
    'import/no-dynamic-require': 0,
    'react/sort-comp': 0,
    'jsx-a11y/aria-role': 0,
    'jsx-a11y/alt-text': 0,
    'jsx-a11y/anchor-has-content': 0,
    'jsx-a11y/control-has-associated-label': 0,
    'no-param-reassign': 0,
    'prefer-object-spread': 0,
    'consistent-return': 0,
    '@typescript-eslint/no-unused-vars': 0,
    'no-useless-escape': 0,
    'react/button-has-type': 0,
    'react/react-in-jsx-scope': 0,
    'prefer-destructuring': 0,
    'array-callback-return': 0,
  },
};

**Comment by zevingao** [comment]
好的，我试试，谢谢

**Comment by smilelmz** [comment]
我试了一下，感觉没有效果

**Comment by Simoon-F** [comment]
没效果

**Comment by fairyOfMale** [comment]
https://github.com/ant-design/ant-design-pro
按照这个项目的配置试一下
