### ISSUE TITLE
umi3版本，配置了publicPath, routes里面的redirect会失效

### ISSUE THREAD

**Issue by spicyboiledfish** [umijs/umi#5004]
umi使用的是3.2.2版本，我的.umirc.ts的配置如下：
```
import { defineConfig } from 'umi';

export default defineConfig({
  publicPath: 'https://xxxxx.xxx/',
  routes: [
    {
      path: '/',
      component: '@/layout/index',
      routes: [
        {
          exact: true,
          path: '/apm',
          redirect: '/apm/dashboard',
        },
        {
          exact: true,
          path: '/',
          redirect: '/apm/dashboard',
        },
        {
          key: '/apm/dashboard',
          path: '/apm/dashboard',
          routes: [
            {
              key: '/apm/dashboard',
              path: '/apm/dashboard',
              component: '@/pages/dashboard',
            },
            {
              key: '/apm/dashboard/detail/service',
              path: '/apm/dashboard/detail/service',
              component: '@/pages/dashboard/detail',
            },
            {
              key: '/apm/dashboard/detail/endpoints',
              path: '/apm/dashboard/detail/endpoints',
              component: '@/pages/dashboard/detail',
            },
          ],
        },
        {
          key: '/apm/performance',
          path: '/apm/performance',
          routes: [
            {
              exact: false,
              key: '/apm/performance',
              path: '/apm/performance',
              component: '@/pages/performance',
            },
          ],
        },
        {
          key: '/apm/analysis',
          path: '/apm/analysis',
          routes: [
            {
              key: '/apm/analysis',
              path: '/apm/analysis',
              component: '@/pages/analysis/index',
            },
            {
              key: '/apm/analysis/detail',
              path: '/apm/analysis/detail',
              component: '@/pages/analysis/index',
            },
          ],
        },
        {
          key: '/apm/detection',
          path: '/apm/detection',
          routes: [
            {
              key: '/apm/detection',
              path: '/apm/detection',
              component: '@/pages/detection/index',
            },
            {
              key: '/apm/detection/detail',
              path: '/apm/detection/detail',
              component: '@/pages/detection/index',
            },
          ],
        },
      ],
    },
  ],
  lessLoader: {
    modifyVars: {
      hack: `true; @import "~@/style/variable.less";`,
    },
  },
  theme: {
    'font-size-base': '13px',
    'font-family': 'PingFangSC-Regular, PingFang SC',
  },
  proxy: {
  },
});

```
我的需求是当路由/apm， 会跳转/apm/dashboard。当路由是/，会跳转到/apm/dashboard。但是我一旦加了publicPath，那么这些配置就会失效。反而我去掉，就可以生效了

**Comment by leftstick** [comment]
我试了下，没有你说的问题。请提供可复现repo吧

**Comment by xiaohuoni** [comment]
@spicyboiledfish cc

**Comment by dmdoit** [comment]
我也遇到这个问题

**Comment by quicklearning123** [comment]
我也遇到这个问题

**Comment by quicklearning123** [comment]
> 我试了下，没有你说的问题。请提供可复现repo吧

@leftstick 请问下有示例吗？

我设置了base和publicPath
效果：面包屑的地址是错的
![image](https://user-images.githubusercontent.com/70048681/116552168-50d8b780-a92b-11eb-9379-08423b9bf019.png)

**Comment by SunshineH2** [comment]
> 我也遇到这个问题

我也遇到了，请问解决了吗

**Comment by SunshineH2** [comment]
请问你解决了吗，我也遇到了这个问题

**Comment by SunshineH2** [comment]
> umi使用的是3.2.2版本，我的.umirc.ts的配置如下：
> 
> ```
> import { defineConfig } from 'umi';
> 
> export default defineConfig({
>   publicPath: 'https://xxxxx.xxx/',
>   routes: [
>     {
>       path: '/',
>       component: '@/layout/index',
>       routes: [
>         {
>           exact: true,
>           path: '/apm',
>           redirect: '/apm/dashboard',
>         },
>         {
>           exact: true,
>           path: '/',
>           redirect: '/apm/dashboard',
>         },
>         {
>           key: '/apm/dashboard',
>           path: '/apm/dashboard',
>           routes: [
>             {
>               key: '/apm/dashboard',
>               path: '/apm/dashboard',
>               component: '@/pages/dashboard',
>             },
>             {
>               key: '/apm/dashboard/detail/service',
>               path: '/apm/dashboard/detail/service',
>               component: '@/pages/dashboard/detail',
>             },
>             {
>               key: '/apm/dashboard/detail/endpoints',
>               path: '/apm/dashboard/detail/endpoints',
>               component: '@/pages/dashboard/detail',
>             },
>           ],
>         },
>         {
>           key: '/apm/performance',
>           path: '/apm/performance',
>           routes: [
>             {
>               exact: false,
>               key: '/apm/performance',
>               path: '/apm/performance',
>               component: '@/pages/performance',
>             },
>           ],
>         },
>         {
>           key: '/apm/analysis',
>           path: '/apm/analysis',
>           routes: [
>             {
>               key: '/apm/analysis',
>               path: '/apm/analysis',
>               component: '@/pages/analysis/index',
>             },
>             {
>               key: '/apm/analysis/detail',
>               path: '/apm/analysis/detail',
>               component: '@/pages/analysis/index',
>             },
>           ],
>         },
>         {
>           key: '/apm/detection',
>           path: '/apm/detection',
>           routes: [
>             {
>               key: '/apm/detection',
>               path: '/apm/detection',
>               component: '@/pages/detection/index',
>             },
>             {
>               key: '/apm/detection/detail',
>               path: '/apm/detection/detail',
>               component: '@/pages/detection/index',
>             },
>           ],
>         },
>       ],
>     },
>   ],
>   lessLoader: {
>     modifyVars: {
>       hack: `true; @import "~@/style/variable.less";`,
>     },
>   },
>   theme: {
>     'font-size-base': '13px',
>     'font-family': 'PingFangSC-Regular, PingFang SC',
>   },
>   proxy: {
>   },
> });
> ```
> 
> 我的需求是当路由/apm， 会跳转/apm/dashboard。当路由是/，会跳转到/apm/dashboard。但是我一旦加了publicPath，那么这些配置就会失效。反而我去掉，就可以生效了

请问是怎么解决的呢

**Comment by davidloveengles** [comment]
base和publicPath设置成一样的路径就好了
