### ISSUE TITLE
ssr开启后，如果使用 umi request 会报 document is not defined

### ISSUE THREAD

**Issue by robinv8** [umijs/umi#5005]
## What happens?

ssr开启后，如果使用 umi request 会报 document is not defined,目前报错的原因是 request 依赖了 antd ，antd 又依赖了 rc-notification
## Context

- **Umi Version**: ^3.2.9
- **Node Version**:  v12.18.0
- **Platform**: mac

**Comment by ycjcl868** [comment]
antd 是支持 SSR 的，可以排查下

https://umijs.org/zh-CN/docs/ssr#window-is-not-defined-document-is-not-defined-navigator-is-not-defined

**Comment by robinv8** [comment]
你们发现这个问题了？

**Comment by ycjcl868** [comment]
还有问题？

**Comment by robinv8** [comment]
@ycjcl868 被激活了，我以为你们发现问题。

**Comment by a982564562** [comment]
这个问题有解决的方案吗

**Comment by xiaohuoni** [comment]
@ycjcl868 https://github.com/umijs/plugins/issues/371

**Comment by ycjcl868** [comment]
`antd: false` 关闭
