### ISSUE TITLE
umirc.config.js设置outputPath会使热更新失效

### ISSUE THREAD

**Issue by Ka-Houl** [umijs/umi#5006]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by Ka-Houl** [comment]
设置outputPath后，只有umirc.config.js文件能热更新，src目录下所有文件不生效

**Comment by williamnie** [comment]
有最小复现么，我的项目里是没问题的，提个复现吧

**Comment by zevingao** [comment]
请问解决了吗，我这里也出现了。最新umi版本，mac，node-12.18.2

**Comment by Ka-Houl** [comment]
> 有最小复现么，我的项目里是没问题的，提个复现吧
抱歉我现在也找不到复现的途径，这个是我以前的umi3.X版本才有的问题， 我前几天重新下载新的umi3.X+1的版本 就复现不出来了，我趁项目还没深入已经换成现在最新版的umi3.X+1版本暂时解决了。。

**Comment by Ka-Houl** [comment]
> 请问解决了吗，我这里也出现了。最新umi版本，mac，node-12.18.2

抱歉我现在也找不到复现的途径，这个是我以前的umi3.X版本才有的问题， 我前几天重新下载新的umi3.X+1的版本 就复现不出来了，我趁项目还没深入已经换成现在最新版的umi3.X+1版本暂时解决了。。

**Comment by Ka-Houl** [comment]
> 请问解决了吗，我这里也出现了。最新umi版本，mac，node-12.18.2

也不知道算不算解决了，我现在也找不到复现的途径，这个是我以前的umi3.X版本才有的问题， 我前几天重新下载新的umi3.X+1的版本 就复现不出来了，我趁项目还没深入已经换成现在最新版的umi3.X+1版本暂时解决了。。

**Comment by zevingao** [comment]
我的版本是"umi": "^3.2.10"，可以复现的

**Comment by kicktech** [comment]
我也遇到了类似的问题, umi 3.2.24   node 15.0.1  mac 。时好时不好，之前删了node_modules重装好了，最近又开始了
