### ISSUE TITLE
配置dva有问题

### ISSUE THREAD

**Issue by smalltian** [umijs/umi#5008]
配置 运行时 app.tsx 提示 Uncaught Error: register failed, invalid key dva from plugin

**Comment by kingctan** [comment]
same problem.

**Comment by williamnie** [comment]
我本地测试了一下，没发现你说的问题，有最小复现么？

**Comment by aizigao** [comment]
目录有models文件就不会崩，可以新建一个 models/global.ts, 然后就可以起来了
```ts
import { Subscription, Effect, Reducer } from 'umi';
// import { ConnectState } from './connect.d';

export interface GlobalModelType<U> {
  namespace: 'global';
  state: Record<string, any>;
  effects: {
    fetchNotices: Effect;
    clearNotices: Effect;
    changeNoticeReadState: Effect;
    fetchJumpList: Effect;
  };
  reducers: Record<string, Reducer<U>>;
  subscriptions: { setup: Subscription };
}

const GlobalModel: GlobalModelType = {
  namespace: 'global',

  state: {},

  effects: {},

  reducers: {},

  subscriptions: {
    setup({ history }): void {
      // Subscribe history(url) change, trigger `load` action if pathname is `/`
      history.listen(({ pathname, search }): void => {
        console.log({ pathname });
        // if (typeof window.ga !== 'undefined') {
        //   // window.ga('send', 'pageview', pathname + search);
        // }
      });
    },
  },
};

export default GlobalModel;

```

**Comment by smalltian** [comment]
是的，我也发现了，有model才会加载dva插件------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;aizigao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月16日(星期四) 下午3:43
收件人:&nbsp;&quot;umijs/umi&quot;<umi@noreply.github.com&gt;;
抄送:&nbsp;&quot;zhujuntian&quot;<2424647830@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [umijs/umi] 配置dva有问题 (#5008)

**Comment by xiaohuoni** [comment]
设计如此，没有model，不会启用 dva 插件。

**Comment by EngsShi** [comment]
@xiaohuoni 用 `yarn create @umijs/umi-app` 创建的初始项目建议增加默认model。目前创建的空工程无法直接启动，提示前面的问题

**Comment by yqwoe** [comment]
我本地有src/models也包这个错。。

**Comment by xiaohuoni** [comment]
不是存在 `src/models` 是需要存在 dva model。

**Comment by xiaohuoni** [comment]
@EngsShi 最新的创建项目没问题，可以运行。
