### ISSUE TITLE
dvaBUG

### ISSUE THREAD

**Issue by smalltian** [umijs/umi#5009]
越更新问题越多，服气
import { createLogger } from 'redux-logger';
import { message } from 'antd';
export const dva = {
  config: {
    onAction: createLogger(),
    onError(e: Error) {
      message.error(e.message, 3);
    },
  },
};

和文档一摸一样，为什就是报错
  dva:{
    hmr: true,
    immer: true
  },

我是没配置？

**Comment by monsoonwang** [comment]
1.使用umi dva list model命令来检查是否有model
2.如果没有任何的model,则需要创建model在models文件夹下否则不会开启dva
3当dva没有的时候 类似 import { connect } from 'umi'的时候会报错 connect is undefined
