### ISSUE TITLE
非根目录models文件夹下的model无法加载

### ISSUE THREAD

**Issue by NexxLuo** [umijs/umi#501]
实际情况是这样的，项目里将一些公共页面给提取出来了，以备之后的项目能继续使用。目录结构如下：
src/commonPages

src/commonPages里必然会存在model，如：
src/commonPages/page1/models
src/commonPages/page1/services
src/commonPages/page1/components

实际上model的目录依然是models，只是不在跟目录下。
之前使用umi-plugin-dva 0.1.5 ，这种情况是支持的。

更新了umi-plugin-dva 0.7.2后，src/commonPages下的models无法被找到。

目前更新了umi 1.3.3 ，但是umi-plugin-dva 0.1.5。不知道是否会对打包速度有影响

**Comment by xiaohuoni** [comment]
就算close了，你评论了，就看得到，不用再发一个

**Comment by xiaohuoni** [comment]
model约定了放在models下面，所以应该不会修改你这个需求。
