### ISSUE TITLE
umi ssr数据脱水和注水

### ISSUE THREAD

**Issue by a982564562** [umijs/umi#5014]
## What happens?
umi ssr有实现数据脱水和注水吗,还是必须通过getInitialProps方法在服务端和客户端都获取一次数据
我有一个城市定位的需求, 请求服务端时,会生成cityName
我希望在服务端能存入服务端的store中,再通过注水的方式存入到客户端中
在getInitialProps方法中直接通过连接store获取这个cityName
我应该怎么做,请大佬指点下

**Comment by williamnie** [comment]
用的dva数据流么？正常写就行了，数据是从model里面获取，getInitialProps里面发dispath，可以先看下这个mr，参照一下
https://github.com/umijs/umi/pull/5017/commits/2a874a0d4a724aaa8009860fb79a5b417ecf6163

**Comment by a982564562** [comment]
> [2a874a0](https://github.com/umijs/umi/commit/2a874a0d4a724aaa8009860fb79a5b417ecf6163)

我目前的做法是在服务端渲染时,通过ctx传递到getInitialProps, 在客户端store初始化时直接通过cookie获取内容
在nextjs中,服务端渲染时会生成next_data存在页面全局中, 到客户端通过next_data初始化store

**Comment by williamnie** [comment]
umi是一样的，会把数据存在g_initialData，带到页面上，在序列化到store里面，原理都是一样的，用cookie传不了很大的数据吧，按照例子里面写就可以了

**Comment by a982564562** [comment]
> umi是一样的，会把数据存在g_initialData，带到页面上，在序列化到store里面，原理都是一样的，用cookie传不了很大的数据吧，按照例子里面写就可以了

你说的g_initialData这个变量我在页面源码中没有看到,dva数据流我也是按照例子做的

**Comment by williamnie** [comment]
目前ssr渲染失败会自动降级到csr渲染，如果没看到可能是ssr渲染失败了，你可以把例子clone下来，跑一下，就看到了

**Comment by a982564562** [comment]
> 目前ssr渲染失败会自动降级到csr渲染，如果没看到可能是ssr渲染失败了，你可以把例子clone下来，跑一下，就看到了

应该没失败吧, 我把浏览器的script脚本禁止了页面还是能出来的

**Comment by williamnie** [comment]
先看demo吧，如果还不行，提个复现的仓库，

**Comment by a982564562** [comment]
> 先看demo吧，如果还不行，提个复现的仓库，

感谢大佬, 问题解决了, 是配置问题
ssr: {
-	forceInitial: true,
	devServerRender: false,
	mode: "stream"
}
+ nodeModulesTransform: {
	type: "none"
}

还有个问题, 只有getInitialProps方法return出来的数据才会挂载到g_initialProps中去吗
下面是原来的写法
![微信截图_20200713192742](https://user-images.githubusercontent.com/44221996/87299758-33bf2d80-c53f-11ea-873e-9c7c90249376.png)
![微信截图_20200713192923](https://user-images.githubusercontent.com/44221996/87299766-36ba1e00-c53f-11ea-88eb-bfd2aaadd0f0.png)

**Comment by williamnie** [comment]
要么不写return，要么把需要的modelreturn回去，你这样写数据都带不回去，改成和例子里一样的
