### ISSUE TITLE
函数组件国际化可以使用useIntl，在class组件中国际化应该怎么做呢？

### ISSUE THREAD

**Issue by effapp** [umijs/umi#5016]
## What happens?

函数组件国际化可以使用useIntl，在class组件中国际化应该怎么做呢？

## 相关环境信息

- **Umi 版本3.2.9：
- **Node 版本12：
- **操作系统win2019：

**Comment by williamnie** [comment]
getIntl(getLocale()).formatMessage()

**Comment by mortalYoung** [comment]
` injectIntl ` 这个来包裹 组件以后 ，在 props 里可以获取到 `intl`

**Comment by sorrycc** [comment]
改成 Function 的方式。

**Comment by hyxiangwsl** [comment]
`
import { injectIntl } from 'umi';
class Group extends Component {
  constructor(props) {
    super(props);
  }

 render(){
    const {
      intl: { formatMessage },
    } = this.props;
 return <div>

 {formatMessage({ id: 'common.search', defaultMessage: '查询' })}
 </div>
 }
  
}
export default injectIntl(Group);
`
