### ISSUE TITLE
配置中添加babel插件不生效, 无法解析这种语法export * as embed from "./embed"

### ISSUE THREAD

**Issue by Enzozzzz** [umijs/umi#5019]
导入的第三方包, 启动项目会报一下错误,  通过babel的插件在ant-design-pro中的配置中配置了extraBabelPlugins: ["@babel/plugin-proposal-export-namespace-from"], 但是并没有生效, 还麻烦遇到同样问题的大神帮看下呢,非常感谢

error  in ./node_modules/@bokeh/bokehjs/build/js/lib/index.js

Module parse failed: Unexpected token (3:9)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| export { version } from "./version";
| export { index } from "./embed";
> export * as embed from "./embed";
| export * as protocol from "./protocol";
| export * as _testing from "./testing";

**Comment by xiaohuoni** [comment]
给个可以复现的repo再reopen
