### ISSUE TITLE
调整proxy和mock处理相同url优先级

### ISSUE THREAD

**Issue by scfido** [umijs/umi#502]
umi 1.2.2中已经验证相同的url请求，webpack中的proxy的优先级要高于mock，要用mock必须要注释掉proxy才行。能否调整顺序顺序为有mock匹配地址时，优先使用mock。

**Comment by xiaohuoni** [comment]
可以先试试1.3.3的表现

**Comment by scfido** [comment]
等1.3.3的静态文件bug解决了我再试试。

**Comment by sorrycc** [comment]
1.3 之后 mock 优先于 proxy。
