### ISSUE TITLE
when umi2 migrate to umi3, it will give error that use config of ssr and exportStatic

### ISSUE THREAD

**Issue by stoneyallen** [umijs/umi#5022]
## What happens?

In this start of year, it's helpful that I use umi's config of ssr and prerend.
But when I set runtimePublicPath as true in umi2, I found that the path of images contained 'undefined', and umi official suggest to update to umi3.
So I try to migrage umi2 to umi3, but umi2 set mockWindow originally, and it doesn't support mockWindow now. So I got many errors, e.g "/ render failed ReferenceError: window is not defined"
I try to use 'window-mock' npm package in app.ts, But I got another error "[SSR] Error: You may only call rewind() on the server. Call peek() to read the current state."

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:3.1.4
- **Node Version**:12
- **Platform**:mac

**Comment by ycjcl868** [comment]
https://umijs.org/zh-CN/docs/ssr#polyfill

可以用 `beforeRenderServer` 来 polyfill window

**Comment by stoneyallen** [comment]
> https://umijs.org/zh-CN/docs/ssr#polyfill
> 
> 可以用 `beforeRenderServer` 来 polyfill window

是的根据umi3官网文档，如果只使用了例如location这种api，可以使用beforeRenderServer可以模拟global.window.location，我写的例子是可以成功的。
但是如果我的项目引用了一些第三方包，他们使用到了例如document这类api，我再给global.window = windowMock;就会报错“[SSR] Error: You may only call rewind() on the server. Call peek() to read the current state.”

在umi2的prerender中是默认提供了window mock，如果由我们自己做的话，一般如何去mock才能避免报错

**Comment by ycjcl868** [comment]
ping @stoneyallen 还有问题吗
