### ISSUE TITLE
register failed, invalid key ssr from plugin /Users/bytedance/Desktop/demos/umi3-ssr/src/app.ts.

### ISSUE THREAD

**Issue by stoneyallen** [umijs/umi#5027]
## What happens?
在app.ts中设置了export const ssr后，在ssr编译时没问题，但是在dev环境非ssr的时候会报错，但是export是没法conditional的，一旦暴露了ssr即使设置为false、undefined、null，都会报错

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:3.2.9
- **Node Version**:12
- **Platform**:mac

**Comment by ycjcl868** [comment]
`app.ts` 中的 ssr key 只在 `ssr: {}` 配置开启时生效，没开 `ssr: {}` 运行时 ssr key 完全是无效的

**Comment by stoneyallen** [comment]
> `app.ts` 中的 ssr key 只在 `ssr: {}` 配置开启时生效，没开 `ssr: {}` 运行时 ssr key 完全是无效的
> 
> > 当然，报错也可以去掉，但从用途上讲不通

我觉得应该是这样，但从我的例子来看，我的dev环境是没有ssr配置的，只在prod环境设置了。
即使没有打开ssr配置，但是在app.js中设置了export const ssr = .....，从结果来看，编译过程没有报错，但是页面会提示报错
![image](https://user-images.githubusercontent.com/5013633/87513673-ab11d000-c6ab-11ea-98a4-bbb706e534ab.png)
注释掉export const ssr = .....，页面立马恢复正常，你们最好自己验证下

**Comment by ycjcl868** [comment]
我试下吧

**Comment by stoneyallen** [comment]
> 我试下吧

怎么样哥们

**Comment by Yezzle** [comment]
把文件名改一下不要叫app

**Comment by appzk** [comment]
禁用layout时，也会出现register fail,将app改名或删除就ok了。

**Comment by ycjcl868** [comment]
看了下是 https://github.com/sbstnmsch/window-mock，会把 `history` 类型改了，去掉重新编译就好了
