### ISSUE TITLE
[SSR] Error: Invariant failed

### ISSUE THREAD

**Issue by stoneyallen** [umijs/umi#5028]
## What happens?
当在modles中添加完dva文件后，执行ssr、exportstatic会报错。但是在dev非ssr环境中是可以正常访问的，只要把models文件夹给删掉，ssr 又恢复正常

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:3.2.9
- **Node Version**:12
- **Platform**:mac

**Comment by ycjcl868** [comment]
给下复现

**Comment by stoneyallen** [comment]
> 给下复现

这里有个demo的例子，https://github.com/stoneyallen/umi3--ssr

**Comment by xiaohuoni** [comment]
相同的问题 https://github.com/umijs/umi/issues/5027

**Comment by zhoushaobo1015** [comment]
我去这都多久还是没有解决... ..., 我也遇到相同问题了
