### ISSUE TITLE
使用 cross-env 设置环境变量失效？

### ISSUE THREAD

**Issue by chenfengyanyu** [umijs/umi#503]
场景是这样的，我有几套环境，需要不同的API地址：
```
"release": "cross-env NODE_ENV=production umi build",
"dev": "cross-env NODE_ENV=development umi build",
```
像上面这样，只要我一运行 npm run dev，NODE_ENV 就会变成 production ，所以区分不了环境。有朋友可以提供解决思路吗，谢谢！

**Comment by chenfengyanyu** [comment]
已解决，不能使用 NODE_ENV 区别环境变量，改用 HOST

**Comment by JohnNiang** [comment]
> 已解决，不能使用 NODE_ENV 区别环境变量，改用 HOST

请问用HOST是如何解决的呢？我的需求是通过不同的环境变量调用不同的api。
