### ISSUE TITLE
 Android 安卓手机 QQ浏览器 打不开umi 搭建的项目 其他浏览器都行， 应该是国际化的问题

### ISSUE THREAD

**Issue by wenJonSnow** [umijs/umi#5036]
"umi": "^2.9.0",
    "umi-plugin-locale": "^2.11.6",
    "umi-plugin-react": "^1.15.8"

 targets: {
    ie: 11,
  },
提示这个错误：
[React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.

ie9时
 targets: {
    ie: 9,
  },
这个错
![21594777864_ pic](https://user-images.githubusercontent.com/24515796/87494068-b8659500-c680-11ea-8d8a-06cf4b9a1966.jpg)

**Comment by williamnie** [comment]
需要单独引入intl这个包，并且在入口处引用
```javascript
import 'intl';
import 'intl/locale-data/jsonp/en';
```

**Comment by wenJonSnow** [comment]
> 需要单独引入intl这个包，并且在入口处引用
> 
> ```js
> import 'intl';
> import 'intl/locale-data/jsonp/en';
> ```

感谢 大神
