### ISSUE TITLE
antd pro npm run build  不识别 ?. 和 ??  typescript语法

### ISSUE THREAD

**Issue by ES1993** [umijs/umi#5037]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by xiaohuoni** [comment]
是识别的，具体看看你的报错，是不是eslint之类的错误。
