### ISSUE TITLE
对 Typescript 支持不太好，有些定义是 any

### ISSUE THREAD

**Issue by Lizhooh** [umijs/umi#5038]
## What happens?

```js
import { history } from 'umi';
```

难怪使用 history api 时没有智能提示，看了一下定义直接来了一个 `history: any`，如下图。

看能不能修复一下，对 ts 的支持度。

## 复现步骤，错误日志以及相关配置

![QQ拼音截图20200716095440](https://user-images.githubusercontent.com/19299088/87617739-b49e4500-c74a-11ea-82be-069f6900e997.png)

## 相关环境信息

- **Umi 版本**：^3.2.9
- **Node 版本**：v12
- **操作系统**：win10

**Comment by leftstick** [comment]
用 `useHistory` 吧
![Screen Shot 2020-07-16 at 10 16 06](https://user-images.githubusercontent.com/1059956/87618837-60e12b00-c74d-11ea-9efd-a3ba8569fb4d.png)

**Comment by ycjcl868** [comment]
PR Welcome

**Comment by xiaodun** [comment]
> 用 `useHistory` 吧
> ![Screen Shot 2020-07-16 at 10 16 06](https://user-images.githubusercontent.com/1059956/87618837-60e12b00-c74d-11ea-9efd-a3ba8569fb4d.png)


在非函数式组件这样行不通...

还有一个问题 ，我始终觉得叫history容易引发潜在性的问题，因为window对象上也有这个属性，会出现在本地没问题，可到了生产环境无法正常使用，因为没有导入history

所以我想把它重命名在导出，可只有路径发生了变化，页面没变...
