### ISSUE TITLE
umi3运行时配置app.js的render方法无法获取dva的store

### ISSUE THREAD

**Issue by levonlin** [umijs/umi#5041]
## What happens?
umi3开启SSR时，app.js的render方法无法通过getDvaApp来获取dva的store，返回null
um2的window.g_app是可以在render方法里访问到dva的

## 最小可复现仓库
使用官方例子里的[ssr-koa](https://github.com/umijs/umi/tree/master/examples/ssr-koa)可复现

## 复现步骤，错误日志以及相关配置
app.js里加上：
![image](https://user-images.githubusercontent.com/6989347/87632237-84b36980-c76b-11ea-8c64-ab45c345d46f.png)

npm run build, npm start运行时输出：
![image](https://user-images.githubusercontent.com/6989347/87632563-3c487b80-c76c-11ea-8f40-99d54d13b0f4.png)

可以看到render时返回null，直到onRouteChange时才能看到dva对象

## 相关环境信息

- **Umi 版本**：3.2.9
- **Node 版本**：10.15.3
- **操作系统**：macOSX

**Comment by xiaohuoni** [comment]
相同问题 https://github.com/umijs/umi/issues/5074
