### ISSUE TITLE
动态路由页面内容加载问题

### ISSUE THREAD

**Issue by CassielLee** [umijs/umi#5046]
## What happens?
umi3开启预渲染之后，配置了动态路由的页面在加载的时候总是会先加载首页的内容然后才加载对应的动态路由的页面，在弱网环境下尤其明显，用户体验极其不友好

## 相关环境信息

- **Umi 版本**：3.2.3
- **Node 版本**：10.16.0
- **操作系统**：mac

**Comment by xiaohuoni** [comment]
你可以试试导出多个入口。[exportstatic](https://umijs.org/config#exportstatic)

**Comment by wushaobo** [comment]
@xiaohuoni  你的同伴说，exportStatic 是不支持动态路由的
https://github.com/umijs/umi/issues/4981#issuecomment-761803752
