### ISSUE TITLE
umi3 性能上真的有提升吗

### ISSUE THREAD

**Issue by phoema** [umijs/umi#5047]
#4231 #4229

我跟踪UMI3几个月了，到现在为止在本地调试模式下启动性能没有明显改善
性能优化要按照文档示例做了调整，
但是：

同一份代码两个分支的情况下，UMI2的性能明显比UMI3快很多，
请问UMI3的性能优化还在持续做吗？
我的包文件、配置文件、路由文件请参照附件。

[config.zip](https://github.com/umijs/umi/files/4931181/config.zip)

[package.zip](https://github.com/umijs/umi/files/4931183/package.zip)

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by k983551019** [comment]
难说

**Comment by phoema** [comment]
各位，能否尽快解决UMI3编译性能问题啊，到底是什么机制导致这样的差异？
没有调试影响开发效率，有调试太慢也影响开发效率。
（刚才看到说3.2.28的OOM问题解决了，点赞！）

下图对比代码完全相同，是从指定分支开的新分支，按照UMI2到UMI3升级文档仅修正了不兼容项，功能一点没改。
我机器16G内存，CPU啥的都不错。

UMI2 
在源码中敲一个空格，点击保存，编译速度如下图，都在1秒以内
UMI自带浏览器F12源码调试效果
![image](https://user-images.githubusercontent.com/8730272/99788757-8b5c4e00-2b5c-11eb-92af-6d7849c2beb1.png)


UMI3.2.28
开启devtool，能够在浏览器F12调试，在源码中敲一个空格，点击保存，编译速度在30秒到70秒之间
devtool:'source-map',
![image](https://user-images.githubusercontent.com/8730272/99788882-b646a200-2b5c-11eb-83e9-d6e8d311202a.png)

不开启devtool，不能够在浏览器F12调试，在源码中敲一个空格，点击保存，编译速度在2秒到4秒之间
![image](https://user-images.githubusercontent.com/8730272/99789988-6963cb00-2b5e-11eb-8f69-fa692ce97eea.png)

问题，我如何在UMI3既能支持浏览器F12源码调试，又快速便捷啊？

**Comment by sorrycc** [comment]
构建性能没有提升，umi 升级的不是性能。
