### ISSUE TITLE
[Feature Request] transpiling modules in node_modules

### ISSUE THREAD

**Issue by smddzcy** [umijs/umi#5048]
First of all, thanks for this great library.

We're using umi in a monorepo project and we're having issues with it. It would be nice to be able to transpile modules in `node_modules` by providing some paths like `transpile: ['node_modules/module-a', 'node_modules/module-b', ...]`.

I think umi v2 had an option called `extraBabelIncludes`, which is somehow removed in v3. Am I missing something or is this feature completely removed? If removed, is there any workaround for this?

**Comment by ycjcl868** [comment]
try [nodeModulesTransform](https://umijs.org/config#nodemodulestransform-31)

```js
export default {
   nodeModulesTransform: {
     type: 'none',
     exclude: ['module-a', 'module-b']
   }
}
```
