### ISSUE TITLE
适配移动端, 使用postcss-px-to-viewport插件, 对于写在.less的单位能转换，但是在tsx文件里面的style写的单位无法转化

### ISSUE THREAD

**Issue by z-lionel** [umijs/umi#5049]
如题：
适配移动端, 使用postcss-px-to-viewport插件, 对于写在.less的单位能转换，
但是在tsx文件里面的style写的单位无法转化

**Comment by xiaohuoni** [comment]
是的，这里面不走这个插件，在style里面要自己转换单位。
