### ISSUE TITLE
[Feature Request] mpa功能配置

### ISSUE THREAD

**Issue by weihomechen** [umijs/umi#5051]
## Background

想使用mpa功能，发现文档
[https://umijs.org/zh-CN/config#mpa-31](https://umijs.org/zh-CN/config#mpa-31)
没写怎么配置这个功能，只有一个是配置形式是`object`的信息。。。可以补一下文档或给个例子么

![image](https://user-images.githubusercontent.com/16172317/87745015-6e66e580-c81f-11ea-8c45-e0e594ca33af.png)

**Comment by pxim** [comment]
同问
