### ISSUE TITLE
兼容ie的问题

### ISSUE THREAD

**Issue by xu-Aurora** [umijs/umi#5053]
在哪里配置兼容ie样式的问题

**Comment by CassielLee** [comment]
请问找到解决办法了吗？我们试了好久好像都不能兼容IE11

**Comment by ycjcl868** [comment]
targets: {
  ie: 9
}

**Comment by CassielLee** [comment]
> targets: {
> ie: 9
> }

这个配置没用

**Comment by ycjcl868** [comment]
为啥，遇到什么问题了，我有个项目兼容  ie 11 没问题啊

**Comment by ycjcl868** [comment]
可能需要补个 ie 兼容文档

**Comment by CassielLee** [comment]
> 为啥，遇到什么问题了，我有个项目兼容 ie 11 没问题啊

umi3.2.3，打包之后报语法错误
![image](https://user-images.githubusercontent.com/26957138/87897196-22b17780-ca7d-11ea-96a8-3bceca425026.png)

**Comment by ycjcl868** [comment]
> > 为啥，遇到什么问题了，我有个项目兼容 ie 11 没问题啊
> 
> umi3.2.3，打包之后报语法错误
> ![image](https://user-images.githubusercontent.com/26957138/87897196-22b17780-ca7d-11ea-96a8-3bceca425026.png)

点进去看看，试试全走 node_modules 编译，这样所有代码都能编译成 targets 的

nodeModulesTransform: {
   type: 'all'
}

代价就是慢一点，可能会有 OOM

**Comment by CassielLee** [comment]
> > > 为啥，遇到什么问题了，我有个项目兼容 ie 11 没问题啊
> > 
> > 
> > umi3.2.3，打包之后报语法错误
> > ![image](https://user-images.githubusercontent.com/26957138/87897196-22b17780-ca7d-11ea-96a8-3bceca425026.png)
> 
> 点进去看看，试试全走 node_modules 编译，这样所有代码都能编译成 targets 的
> 
> nodeModulesTransform: {
> type: 'all'
> }
> 
> 代价就是慢一点，可能会有 OOM

我用RM_TMPDIR=none COMPRESS=none yarn run build命令打包之后看了一下，报错定位的地方是下面一张图里面的isBrowser函数
![image](https://user-images.githubusercontent.com/26957138/87897791-fe569a80-ca7e-11ea-9650-997c980fc202.png)

![image](https://user-images.githubusercontent.com/26957138/87897702-bdf71c80-ca7e-11ea-8fb8-ef8d8c73fb07.png)
