### ISSUE TITLE
最新版本,当开启dynamicImport后，第一次切换路由会闪一下，具体步骤看过来

### ISSUE THREAD

**Issue by bibiehy** [umijs/umi#5054]
umi@3.2.10
win 10

当开启dynamicImport后，第一次切换路由会闪一下，步骤如下：

1.创建项目 yarn create @umijs/umi-app

2.在.umirc.ts中添加 dynamicImport: { loading: '@/Loading' }，开启按需加载

3.随便添加一个路由如 /product

4.首页和产品页加Link，然后 ctrl + f5 刷新，点击另外一个路由，会闪一下，后面在切换不会出现这种情况

或者

添加 layouts 文件夹，里面加一个请求，这样更明显，页面加载完后，第一次点击路由切换，layouts 会重新渲染，请求会再次触发，之后再切换路由就没有这种现象了，

页面样子
![image](https://user-images.githubusercontent.com/35096473/87775730-249af100-c859-11ea-9a08-c29d547e52e4.png)

layouts/index.tsx
![image](https://user-images.githubusercontent.com/35096473/87775626-ffa67e00-c858-11ea-93e1-de983e946ef3.png)

**Comment by williamnie** [comment]
css chunk没打全，后续会修复

**Comment by bibiehy** [comment]
@williamnie 还一个问题需要注意一下，接上面问题，当注释掉按需加载dynamicImport后，在生产环境，比如我需要把bizcharts包单独打包出来，配置了 chainWebpack，打包后的文件运行不了，也没报错，除非开启按需加载或一起打包到vendor下。
![image](https://user-images.githubusercontent.com/35096473/88019609-bf971200-cb5c-11ea-9635-4ebf05a5a036.png)

**Comment by xiaohuoni** [comment]
@williamnie 后续在哪里跟进？

**Comment by williamnie** [comment]
@ycjcl868 这个修复了么

**Comment by bibiehy** [comment]
@williamnie 已经修复了umi@3.2.14
