### ISSUE TITLE
umi2升级到umi3,global.less没生效

### ISSUE THREAD

**Issue by MingShined** [umijs/umi#5056]
项目是umi2的老项目，按升级文档，一步步升级。确认过global.less的拼写，存放路径（src/global.less）均正确，结果没有生效

**Comment by ycjcl868** [comment]
去掉 `:global` 就 ok 了

**Comment by MingShined** [comment]
> 去掉 `:global` 就 ok 了

哦哦，OK了，谢谢，umi做了最高优先级吗
