### ISSUE TITLE
怎么查看umi的webpack配置

### ISSUE THREAD

**Issue by xu-Aurora** [umijs/umi#5058]
umi的webpack中有配置"postcss-loader"吗？假如没有的话我要怎么才能配置上去？

**Comment by ycjcl868** [comment]
umi 里有 postcss-loader

![image](https://user-images.githubusercontent.com/13595509/87896974-7374a080-ca7c-11ea-8cde-b4e44117828b.png)


如果需要查看 webpack 的配置，可以使用

```js
// .umirc.ts
export default {
   chainWebpack: (config) => {
      console.log('webpack Config', config.toConfig())
       return config;
   }
}
```

**Comment by xu-Aurora** [comment]
> umi 里有 postcss-loader
> 
> ![image](https://user-images.githubusercontent.com/13595509/87896974-7374a080-ca7c-11ea-8cde-b4e44117828b.png)
> 
> 如果需要查看 webpack 的配置，可以使用
> 
> ```js
> // .umirc.ts
> export default {
>    chainWebpack: (config) => {
>       console.log('webpack Config', config.toConfig())
>        return config;
>    }
> }
> ```

那怎么添加一个webpack插件配置呢？

**Comment by thinkingc** [comment]
`umi webpack`

**Comment by MissNanLan** [comment]
> 
比如
import CompressionPlugin from 'compression-webpack-plugin';
$.plugin('compression-webpack-plugin').use(CompressionPlugin,{xxx})

**Comment by MissNanLan** [comment]
> > umi 里有 postcss-loader
> > ![image](https://user-images.githubusercontent.com/13595509/87896974-7374a080-ca7c-11ea-8cde-b4e44117828b.png)
> > 如果需要查看 webpack 的配置，可以使用
> > ```js
> > // .umirc.ts
> > export default {
> >    chainWebpack: (config) => {
> >       console.log('webpack Config', config.toConfig())
> >        return config;
> >    }
> > }
> > ```
> 
> 那怎么添加一个webpack插件配置呢？

比如
import CompressionPlugin from 'compression-webpack-plugin';
$.plugin('compression-webpack-plugin').use(CompressionPlugin,{xxx})
