### ISSUE TITLE
请问umi 3.0如何打包node_modules下的es6文件

### ISSUE THREAD

**Issue by Pasoul** [umijs/umi#5062]
## What happens?

我引入了一个第三方js库，该库是用es6编写的，导致最终打包后的文件包含es6代码，umi3.0移除了extraBabelIncludes配置项。我应该怎么做才能打包node_mobules下的es6代码？

## Context

- **Umi Version**: 3.2.10
- **Node Version**: 12.9.1
- **Platform**: mac

**Comment by leftstick** [comment]
试试 [nodeModulesTransform](https://umijs.org/config#nodemodulestransform-31) ?
