### ISSUE TITLE
umi打包项目index.html页面引入代码高亮插件shCore.js后报错打不开

### ISSUE THREAD

**Issue by hanfengmi** [umijs/umi#5064]
![image](https://user-images.githubusercontent.com/23490512/88002920-3a990200-cb36-11ea-8df0-c6c6a8525bef.png)

页面就会提示

![image](https://user-images.githubusercontent.com/23490512/88002961-513f5900-cb36-11ea-89d4-1392279ca045.png)

项目就是demo事例，没有引入其他插件，这是什么原因啊

**Comment by xiaohuoni** [comment]
提供可复现的repo 再 reopen
