### ISSUE TITLE
Could not match correct Router 

### ISSUE THREAD

**Issue by IamFive** [umijs/umi#5065]
## What happens?

When a parent-route[1] matches a location, umijs will not continue searching other routes even all sub routes of this parent-route[1] does not match the location.

When matching Route, umijs does not using DFS. 
When First level route matches the location, it will not check whether any sub route of this route matches location.

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

https://github.com/IamFive/ant-design/commit/3aadf84afa0eb403f214053f9d926c6b11dc1f16

```bash
git clone https://github.com/IamFive/ant-design antd-v5.1-route-match-issue
cd antd-v5.1-route-match-issue
git checkout v5.1
yarn
yarn start
```

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

After start app, login and visit *http://localhost:8000/admin/showcases*, it renders correctly.
Then visit *http://localhost:8000/admin2/showcases* or *http://localhost:8000/list*, it shows a blank page.

**Expected behavior** 1. 2.
*http://localhost:8000/admin2/showcases* and *http://localhost:8000/list* should be rendered correctly.

## Context

- **Umi Version**:
umi@3.2.10

- **Node Version**:
v12.13.1

- **Platform**:
Window 10

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
