### ISSUE TITLE
dva 的 typescript 类型提示不友好

### ISSUE THREAD

**Issue by iajun** [umijs/umi#5069]
现在 Action 为 AnyAction, useSelector 每次都要写类型, 没有 redux 官网那样的 useTypedSelector 的支持；其次， useDispatch 的 Action 为 AnyAction ，没有任何类型提示， Effect 类型不支持泛型....

**Comment by xiaohuoni** [comment]
@iajun 这一块的类型是我加的，因为我们现在项目中 dva 用的也不多。我只处理了我们默认使用的一种情况。很多场景和类型没有考虑到。希望你能帮忙完善一下。

**Comment by SuperHuangXu** [comment]
> @iajun 这一块的类型是我加的，因为我们现在项目中 dva 用的也不多。我只处理了我们默认使用的一种情况。很多场景和类型没有考虑到。希望你能帮忙完善一下。



> @iajun 这一块的类型是我加的，因为我们现在项目中 dva 用的也不多。我只处理了我们默认使用的一种情况。很多场景和类型没有考虑到。希望你能帮忙完善一下。

请问现在你们项目一般使用什么数据流方案呢？

**Comment by SuperHuangXu** [comment]
> @iajun 这一块的类型是我加的，因为我们现在项目中 dva 用的也不多。我只处理了我们默认使用的一种情况。很多场景和类型没有考虑到。希望你能帮忙完善一下。

请问现在你们项目一般使用什么数据流方案呢？

**Comment by xiaohuoni** [comment]
我们是dva结合react-hooks使用。
