### ISSUE TITLE
关于umi require('../package.json') 相对路径的问题

### ISSUE THREAD

**Issue by EvanJin** [umijs/umi#5072]
## What happens?
![image](https://user-images.githubusercontent.com/1031636/88149232-5da8dc00-cc32-11ea-8778-39c7f68cddc5.png)
1) umi 3.2.0 bin umi.js 中引入了package.json文件，在npm install完成后，cd node_modules/.bin/npx umi，不会出现任何问题
，因为 umi -> ../umi/bin/umi.js 

2) 将工程目录(包括node_modules)通过cp命令，挪到其他目录下，做构建相关工作，不重新npm install的情况下, 在执行(cd node_modules/.bin/npx umi) ，此时会报require('../package.json')错误

3）cp命令会破坏掉node cli 的link问题（不重新install的情况）

4）umi 2 不会出现此问题

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：3.2.0
- **Node 版本**：v14.5.0
- **操作系统**：macos

**Comment by xiaohuoni** [comment]
我试了一下，好像并不会有这个情况。
