### ISSUE TITLE
3.2.10 版本中patchRoutes：routes

### ISSUE THREAD

**Issue by zjs9609** [umijs/umi#5076]
routes的类型是啥？

**Comment by zjs9609** [comment]
> routes的类型是啥？

这个不能像写普通路由是那样写吗？

**Comment by cieldon32** [comment]
routes: [
    {
      path: '/',
      component: '@/layouts/basic.layout',
      routes: [
        { path: '/', component: 'index' }  // 成功匹配到
      ]
    },
    {
      path: '/auth',
      component: '@/layouts/full.layout',
      routes: [
        { path: '/auth/login', component: 'login' } //没有匹配到
      ]
    }
  ],
