### ISSUE TITLE
umi3.X版本中配置sass,启动报错

### ISSUE THREAD

**Issue by overcastsky** [umijs/umi#5078]
## What happens?

在安装node-sass、sass-loader后，在.umirc.js中配置'sass': {},运行报错**Invalid config key: sass
Error: Invalid config key: sass**

## 复现步骤，错误日志以及相关配置

1、npm i node-sass sass-loader --save
2、在.umirc.js中配置
export default defineConfig({
  'sass': {},
});

- **Umi 版本**：3.0.16
- **Node 版本**：12.18.3
- **操作系统**：
MacOs

**Comment by xiaohuoni** [comment]
要先装这个库，https://github.com/umijs/plugins/tree/master/packages/plugin-sass

**Comment by SimonXinw** [comment]
“sass”:{},  你这个是怎么写入进去的呢，我的在编辑器里面会自动 sass:{} 去除双引号，不知道你的是怎么搞得，我的一直都不生效

**Comment by Deja-vuuu** [comment]
> 

这里的文档能更新一下吗  https://umijs.org/zh-CN/docs/faq#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8-sass-%EF%BC%9F

这里根本没说这个

**Comment by overcastsky** [comment]
gsdg45sd4g5s4dg5sdイシリーズからドムをプレゼンりやかなベルガモットオジビタから
