### ISSUE TITLE
配置环境变量启动报错

### ISSUE THREAD

**Issue by overcastsky** [umijs/umi#5079]
## What happens?
想要配置不同环境的打包命令，
"start:dev": "cross-env UMI_ENV=dev umi dev"，
cross-env已安装
启动时报错信息如下：
get user config failed, undefined does not exist, but process.env.UMI_ENV is set to dev.

## 相关环境信息

- **Umi 版本**：3.0.16
- **Node 版本**：12.18.3
- **操作系统**：macos

**Comment by zlh** [comment]
请问你是怎么解决的？

**Comment by zm8** [comment]
> 请问你是怎么解决的？
需要新增 .umirc.dev.ts 文件。

建议官方不要报错，而是忽略，
因为实战当中，有时就只需要一个文件就行了。

**Comment by xiaomingyu-git** [comment]
> 请问你是怎么解决的？
在 tsconfig中 ，在include里把自己环境变量的文件加上。
我配置的环境叫qa 定义的文件名是 .umirc.qa.ts
如下。
  "include": [
    "mock/**/*",
    "src/**/*",
    "config/**/*",
    ".umirc.ts",
    ".umirc.qa.ts",
    "typings.d.ts"
  ],

……………………………………………………………………
我今天也遇见了这个问题，手动添加上了。
有一定概率出现。

**Comment by yanglebupt** [comment]
似乎 config/config.<env>.ts  和 .umirc.<env>.ts 不可以混用，要么全部用 config 的形式，要么全用 .umirc

**Comment by overcastsky** [comment]
gsdg45sd4g5s4dg5sdイシリーズからドムをプレゼンりやかなベルガモットオジビタから
