### ISSUE TITLE
windows 下 umi dev 编译错误时没有报错，同时内存飙升

### ISSUE THREAD

**Issue by arvinxx** [umijs/umi#508]
版本 1.3.3
错误编译状态如下
![11](https://user-images.githubusercontent.com/28616219/40247407-d71598e6-5afe-11e8-8236-dba215490233.gif)

而编译成功时的内存只有几百 M
![default](https://user-images.githubusercontent.com/28616219/40247434-ed73ff4c-5afe-11e8-8696-bf049d2597fd.png)

**Comment by arvinxx** [comment]
禁用 hard-source-webpack-plugin 插件后解决

请问会是什么原因导致的？

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/495
应该与这个问题重复了
