### ISSUE TITLE
umi最新版本使用约定式路由404页面出不来，随便输入路由都是空白页面并未渲染404页面。

### ISSUE THREAD

**Issue by zevingao** [umijs/umi#5081]
如题。
![image](https://user-images.githubusercontent.com/17871738/88258039-c1460e80-ccf1-11ea-818c-93ceef3f6f04.png)
![image](https://user-images.githubusercontent.com/17871738/88258060-cdca6700-ccf1-11ea-9d19-fb4e14d01c34.png)
![image](https://user-images.githubusercontent.com/17871738/88258112-ee92bc80-ccf1-11ea-9c17-3f8d74f153dd.png)

**Comment by xiaohuoni** [comment]
bug，有相关的issues 和 PR的

**Comment by zhengmenghuang** [comment]
遇到相同的问题 demo 网站 https://llxhzm.xyz:6001

**Comment by lxzxl** [comment]
鉴于迟迟没有合并PR， 提供本人的解决方法：

1. 把`404.jsx` 改成 `[any].jsx`, 保证在生成的路由在最后一项

2. 覆盖页面属性的 `path` 为 `undefined`, 达到生成的routes里没有path的目的

```javascript
// [any].jsx

const NoFoundPage = () => <div>not found</div>

// !!!这里覆盖掉 path 的值!!!
NoFoundPage.path = undefined;

export default NoFoundPage;

```

**Comment by xiaohuoni** [comment]
相同问题https://github.com/umijs/umi/issues/5092
