### ISSUE TITLE
umi3.x中headScripts配置，启动报错

### ISSUE THREAD

**Issue by overcastsky** [umijs/umi#5082]
<img width="878" alt="截屏2020-07-23下午3 34 18" src="https://user-images.githubusercontent.com/28147733/88262456-d07d8a00-ccfa-11ea-9358-e266e0605c78.png">

## What happens?
尝试使用headScripts，添加一个额外的脚本文件，但是启动的时候报错

## 相关环境信息

- **Umi 版本**：3.0.16
- **Node 版本**：12.18.3
- **操作系统**：macos

**Comment by Jf0820** [comment]
未配置headScripts，但删除一些无用依赖并升级node版本至12.18.3后出现类似问题

**Comment by xiaohuoni** [comment]
这个问题和你的配置无关，目前是建议删除一下.umi文件夹重新开启就好。
