### ISSUE TITLE
约定路由和 404.tsx 好像不兼容。

### ISSUE THREAD

**Issue by xiaorong61** [umijs/umi#5085]
当不配置路由信息时，404.tsx 无法正常使用，即访问不存在的路径时，显示空白，而不是 404.tsx 内容。
![image](https://user-images.githubusercontent.com/5251387/88272627-949ef080-cd0b-11ea-9c94-513a240d69b4.png)
![image](https://user-images.githubusercontent.com/5251387/88272669-a41e3980-cd0b-11ea-97da-0a6aa78c564d.png)
![image](https://user-images.githubusercontent.com/5251387/88272715-b8623680-cd0b-11ea-89ec-b2095ad4e133.png)

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/5081
都是一个问题的。

**Comment by skyunBoss** [comment]
解决了吗？

**Comment by xiaohuoni** [comment]
@skyunBoss 没有合并。

**Comment by skyunBoss** [comment]
> 合并

大概什么时候合并

**Comment by wenbingyan** [comment]
撒时候修复

**Comment by lxzxl** [comment]
鉴于迟迟没有合并PR， 提供本人的解决方法：

1. 把`404.jsx` 改成 `[any].jsx`, 保证在生成的路由在最后一项

2. 覆盖页面属性的 `path` 为 `undefined`, 达到生成的routes里没有path的目的

```javascript
// [any].jsx

const NoFoundPage = () => <div>not found</div>

// !!!这里覆盖掉 path 的值!!!
NoFoundPage.path = undefined;

export default NoFoundPage;

```
