### ISSUE TITLE
umi3中无去除console相关配置？

### ISSUE THREAD

**Issue by zhilianbi520** [umijs/umi#5089]
## What happens?
umi中去除console无效？？
`terserOptions:{
    compress: {
      drop_console:process.env.NODE_ENV==='production'?true:false,
    }
  }`
暴露的配置项无相关配置？？https://github.com/umijs/umi/blob/master/packages/bundler-webpack/src/getConfig/terserOptions.ts
ps:没有配置esbuild相关内容。

## Context

- **Umi Version**:  3.2.10
- **Node Version**: 12.6
- **Platform**: mac

**Comment by sorrycc** [comment]
`terserOptions:{ compress: { drop_console:process.env.NODE_ENV==='production'?true:false, } }` 这个有啥问题？

**Comment by zhilianbi520** [comment]
> `terserOptions:{ compress: { drop_console:process.env.NODE_ENV==='production'?true:false, } }` 这个有啥问题？

打包后控制台的console还会打印，没有去除。

**Comment by zhilianbi520** [comment]
> `terserOptions:{ compress: { drop_console:process.env.NODE_ENV==='production'?true:false, } }` 这个有啥问题？

已解，部署至服务器，未更新资源导致.
