### ISSUE TITLE
自定义404.js无效

### ISSUE THREAD

**Issue by chiangfai** [umijs/umi#509]
显示Not Found

**Comment by xiaohuoni** [comment]
什么是自定义404

**Comment by chiangfai** [comment]
@xiaohuoni  我build后，使用serve启动.访问页面还是只显示Not Found。

**Comment by sorrycc** [comment]
参考 https://github.com/umijs/umi-examples/tree/master/routes

**Comment by superlbr** [comment]
404.js这个文件必须要存在？改成404.ts就不行

**Comment by chj-damon** [comment]
@sorrycc 我是ts项目，在pages下新建的404.tsx并不会生效
