### ISSUE TITLE
兼容问题：umi 3.2.10 打包后在IE11浏览器中无法访问

### ISSUE THREAD

**Issue by ShaunZh** [umijs/umi#5097]
## What happens?
打包后在IE11浏览器中无法访问，报错提示如下：
![image](https://user-images.githubusercontent.com/12807720/88377193-5cfa7c00-cdd1-11ea-9f8d-0da6385db6fb.png)
如果将打包后的js文件去除"use strict"，则在IE11浏览器中访问正常
## umi配置信息
![image](https://user-images.githubusercontent.com/12807720/88377545-fb86dd00-cdd1-11ea-9a98-717df3ee4a57.png)
![image](https://user-images.githubusercontent.com/12807720/88377569-03df1800-cdd2-11ea-9e1c-364cb68f719c.png)

## 相关环境信息

- **Umi 版本**：3.2.10
- **Node 版本**：13.7
- **操作系统**：mac 10.13.6

**Comment by lhzbxx** [comment]
Umi 3.2.22 依旧存在这个问题。

**Comment by sorrycc** [comment]
已修复。
