### ISSUE TITLE
我想通过读取 @@/core/routes 的数据自动生成 antd pro Layout 的导航栏，但失败了。

### ISSUE THREAD

**Issue by xiaorong61** [umijs/umi#5098]
![image](https://user-images.githubusercontent.com/5251387/88378798-46095900-cdd4-11ea-90f5-82d548c68589.png)
会返回 undefined
要是能被读取就好了

**Comment by leftstick** [comment]
循环依赖问题。

其实你可以用页面组件的`props.routes`，就是这个东西，你试试看

**Comment by xiaorong61** [comment]
谢了，貌似 props.route.routes 更好，
props.routes需要props.routes[0].routes
