### ISSUE TITLE
更新到umi@1.3.3之后，POST请求会被pending，但GET不受影响。

### ISSUE THREAD

**Issue by LiXuanqi** [umijs/umi#510]
## 开发环境
node v10.1.0
umi 1.3.3
dva-cli 1.0.0-beta.4
dva 2.2.3

## 问题
今天在尝试更新到新版本的umi后，之前能够运行的代码出现了错误。配置代理后，GET方法正常，但POST一直处于Pending状态。
请求的方式如下。
```
  const { data: res } = yield call(request, '/oversea/api/tokens', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    username: formData.username,
                    password: formData.password
                })
            })
```

`.webpackrc.js`文件如下
```js
export default {
    "proxy": {
        "/oversea/api":{
            "target": "http://127.0.0.1:5000",
            "changeOrigin": true,
        },
    },
    "publicPath": "/oversea/static/"
}
```
![](http://7u2fph.com1.z0.glb.clouddn.com/9A4E89E8-DA27-4451-8905-A398193940B4.png?imageMogr2/thumbnail/!70p)

尝试过将request 替换为 axios，问题依旧。
也尝试过使用`dva new` 重新新建项目，但发现新建的工程里依旧没有`.webpackrc.js` 这个文件了，我不确定是不是新版的dva更改了webpack的配置方式。

**Comment by LiXuanqi** [comment]
在 #492 里找到了同样的情况，
```
  headers: {
                    "Content-type": "application/json; charset=UTF-8;"
                },
```
可解决。

**Comment by songlairui** [comment]
find a similar problem here

https://github.com/chimurai/http-proxy-middleware/issues/40#issuecomment-163398924
