### ISSUE TITLE
不自定义服务器的话怎么将服务端参数扩展到ctx？

### ISSUE THREAD

**Issue by supwjm** [umijs/umi#5104]
## Background

我试了你们项目中example/ssr-koa, 发现自定义服务器后，热更新无效了，会变成强制更新，而且还会有短暂的服务器崩溃现象，所以我开发环境没有采用自定义服务，而是采用自带的，但我想扩展服务器req到ctx , 文档中只给出了一个自定义服务器的示例，不自定义服务器的话，我改怎么搞？

**Comment by williamnie** [comment]
自带的暂时没法扩展，理论上不会出现你说的热更新失效，自带的和koa的处理方式应该是一样的，开发模式下，每次重新加载build好的文件，是没问题的，可以提个复现，我看下

**Comment by supwjm** [comment]
自定义服务器热更新失效我提成另外的issue 了，https://github.com/umijs/umi/issues/5103 ，用你们项目中的example/ssr-koa就能复现，修改完文件后，保存，会先出现无法访问，然后再自动刷新。能告知自带的在哪定义的吗？找了老半天，没找着代码在哪。
