### ISSUE TITLE
umi2升级3 字体图标显示小方框

### ISSUE THREAD

**Issue by jayguojianhai** [umijs/umi#5106]
umi2 是正常的
升级到3就不对了如下图，最小复现demo
![image](https://user-images.githubusercontent.com/15603321/88528967-ead4a200-d031-11ea-9f7b-50b72484bc0d.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

https://github.com/jayguojianhai/umi3

## Context

- **Umi Version**:3.2.11
- **Node Version**:12.16.1
- **Platform**:mac

**Comment by jayguojianhai** [comment]
没有大佬看看嘛？

**Comment by jayguojianhai** [comment]
没有大佬看看嘛？

**Comment by FiftyShadows** [comment]
There is a problem with your iconfont and it cannot be loaded.

**Comment by jayguojianhai** [comment]
thanks
