### ISSUE TITLE
有什么办法可以判断dynamicImport切出的chunk文件加载成功

### ISSUE THREAD

**Issue by chj-damon** [umijs/umi#5107]
## What happens?
使用dynamicImport之后会按照路由进行拆分，生成一堆chunk文件，然后根据路由加载对应的chunk文件。
现在的问题是：如果进行了重新部署，这个时候拆分出来的文件的hash值已经改变。但是用户无法感知到，在不刷新页面的情况下，已经下载的chunk文件再次访问的时候就会报404错误，表现出来的就是页面一直在loading，直到用户强刷页面，才会去下载新的chunk

所以我的问题是，有什么办法能够判断chunk文件是否加载成功？如果能拿到http code是404，这个时候就可以做对应的逻辑处理（比如提示用户刷新页面）

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by steveleeh** [comment]
是用非覆盖式的cdn部署静态资源，当前用户虽然用的还是旧的资源表，cdn上该旧资源还是存在的。

**Comment by steveleeh** [comment]
用非覆盖式的cdn部署静态资源，当前用户虽然用的还是旧的资源表，cdn上该旧资源还是存在的。

**Comment by leftstick** [comment]
后端做一个推送服务，或者提供一个版本号的api吧。

前端接收推送，或者定时去call这个api获得最新的版本号，如果发现有新版本，提示用户刷新。


这种问题，其实从技术上解决很难做到完美，从业务角度反而更容易一点
