### ISSUE TITLE
umi3以上使用xlsx报错

### ISSUE THREAD

**Issue by azx1985** [umijs/umi#5109]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
估计是需要自己配loader https://umijs.org/zh-CN/docs/faq#%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E9%A2%9D%E5%A4%96%E7%9A%84-loader-
