### ISSUE TITLE
V1版本项目启动报错 Module build failed: Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean

### ISSUE THREAD

**Issue by yolo2013** [umijs/umi#5110]
## What happens?
项目启动报错，之前应该是好的（具体日期不明，2礼拜之前应该好的，业务代码原封未动）

错误信息：Module build failed: Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you are migrating from Babylon/Babel 6 or want to use the old decorators proposal, you should use the 'decorators-legacy' plugin instead of 'decorators'.

自问自答：
Q：问什么不升级到V2或者V3？
A：历史项目，只是升级下小功能，没有精力做升级。

Q：尝试过什么解法？
A：使用 extraBabelPlugins 配置了 @babel/plugin-proposal-decorators，但是提示无法和自带集成plugin共存，想看umi文档，发现官网V1的文档已经无法访问。Google上有类似错误，都是库依赖问题。

- **Umi Version**: V1.3.18
- **Node Version**: V10 & V8都测试过
- **Platform**: Mac&TNPM

**Comment by xiaohuoni** [comment]
可以尝试将项目中的依赖包都做锁包处理。然后再尝试一下。有可能是某些依赖升级来。没有你的代码，具体的我不是太清楚。

**Comment by yolo2013** [comment]
> 可以尝试将项目中的依赖包都做锁包处理。然后再尝试一下。有可能是某些依赖升级来。没有你的代码，具体的我不是太清楚。

全部都锁不太行。。关键现在不好精准定位哪个包。
