### ISSUE TITLE
router.push丢了，我该用哪个？

### ISSUE THREAD

**Issue by pxim** [umijs/umi#5111]
## What happens?

```
import router from 'umi/router';

router.push('/dashboard/anyParams');
```
现在没有这了router.push 了，我该用哪种方法

- **Umi Version**: ^3.1.2
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
umi@3 改用 https://umijs.org/zh-CN/api#history
所有升级 umi@3 的注意事项，可以在这里看到 https://umijs.org/zh-CN/docs/upgrade-to-umi-3

**Comment by pxim** [comment]
> umi@3 改用 https://umijs.org/zh-CN/api#history
> 所有升级 umi@3 的注意事项，可以在这里看到 https://umijs.org/zh-CN/docs/upgrade-to-umi-3

好的，谢谢了
