### ISSUE TITLE
Where to add Amplitude analytics code [Umi3]

### ISSUE THREAD

**Issue by shlomitsur** [umijs/umi#5112]
Hello.

When adding the Amplitude initialization code:
```
import { initAmplitude } from './utilities/amplitude';

initAmplitude();
```
Should I add it in app.tsx or in global.tsx, or maybe it's better to add it in some other place?
Thank you

**Comment by xiaohuoni** [comment]
You can do it on global.tsx and [src/pages/document.ejs](https://umijs.org/docs/html-template)
