### ISSUE TITLE
Plugin API reference doc is very unclear

### ISSUE THREAD

**Issue by djyde** [umijs/umi#5113]
https://umijs.org/zh-CN/plugins/api

For example, it wasn't clear that how to use `modifyConfig`, what params it would received in the callback function or what should I return.

**Comment by xiaohuoni** [comment]
因为很多api都是一样的用法，所以没有每一个都写明。
```
 api. modifyConfig((config) => {
    return config;
  });
```

**Comment by djyde** [comment]
@xiaohuoni And what about `applyPlugins`? What about `addPolyfillImports`? What about `modifyBundler`? etc..

It's hard to persuade teammates to use Umi if the document was unclear. 😅

**Comment by xiaohuoni** [comment]
明白了，我这几天补一下。
