### ISSUE TITLE
意见

### ISSUE THREAD

**Issue by tenkiss258** [umijs/umi#5116]
东西做的再好，没有好的api都扯淡。api少了不知道多少个版本的，重来不补，多少人想用，却被拒之门外。
留给别人的唯一社区，就是技术讨论群。里边一团糟，有发广告卖小视频的，有发广告推鞋子的。有俩人互相骂傻逼，菜鸟的。简直就是个杂货市场。乌烟瘴气。

**Comment by xiaohuoni** [comment]
什么时候，有这些东西？你是不是加错群了。“里边一团糟，有发广告卖小视频的，有发广告推鞋子的。有俩人互相骂傻逼，菜鸟的”

**Comment by xiaohuoni** [comment]
> api少了不知道多少个版本的，重来不补，多少人想用，却被拒之门外
不知道你这里指的api是指什么？

**Comment by zwh1666258377** [comment]
> 什么时候，有这些东西？你是不是加错群了。“里边一团糟，有发广告卖小视频的，有发广告推鞋子的。有俩人互相骂傻逼，菜鸟的”

你们的群真是白建，不知道建了有什么意义。  
排除一些小白问题，一些本身因文档不清晰产生的问题也没人回答。
目前怎么评价umi呢，就是按照文档讲的就能跑，按照你们的例子也能跑，但只要偏离几乎就走投无路了… 看文档文档没有 问问题群里没人理

**Comment by zwh1666258377** [comment]
> 什么时候，有这些东西？你是不是加错群了。“里边一团糟，有发广告卖小视频的，有发广告推鞋子的。有俩人互相骂傻逼，菜鸟的”

你们的群真是白建，不知道建了有什么意义。  
排除一些小白问题，一些本身因文档不清晰产生的问题也没人回答。
目前怎么评价umi呢，就是按照文档讲的就能跑，按照你们的例子也能跑，但只要偏离几乎就走投无路了… 看文档文档没有 问问题群里没人理

**Comment by xiaohuoni** [comment]
群里没人理？发个 issues 不就好了吗？

**Comment by zwh1666258377** [comment]
> 群里没人理？发个 issues 不就好了吗？

https://github.com/umijs/umi/issues/5119 感谢大佬
