### ISSUE TITLE
SSR页面标题渲染失败

### ISSUE THREAD

**Issue by zfhslfgit** [umijs/umi#5118]
## 最小可复现仓库

> https://github.com/zfhslfgit/ssr-with-eggjs-test

## 标题SSR渲染失败
内容能正常服务端渲染，但标题不行（用户能正常显示标题，就是SEO的标题异常）。
<img width="1705" alt="图片" src="https://user-images.githubusercontent.com/12530974/88666765-19767980-d113-11ea-91f6-951cd6f1c973.png">

<img width="1290" alt="图片" src="https://user-images.githubusercontent.com/12530974/88666705-0368b900-d113-11ea-901d-709b4ccb34ea.png">

![image](https://user-images.githubusercontent.com/12530974/88665867-de277b00-d111-11ea-8280-0962883f6edf.png)

## 相关环境信息

umi：3.2.9
node: 10.16.3

**Comment by supwjm** [comment]
虽然没有找到具体原因，不过example/ssr-koa 那个例子，我把渲染模式mode 从stream 改成string就好了https://blog.csdn.net/supming1/article/details/107523129

**Comment by shlomitsur** [comment]
I have the same issue, the Helmet plugin is not called for mode='stream'?

**Comment by shlomitsur** [comment]
I have the same issue too.

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/94362880-1b0ce100-0073-11eb-9a7e-9f50847fc8b2.png)


test case reproduce, fixing ...

**Comment by ycjcl868** [comment]
https://github.com/nfl/react-helmet/issues/322

**Comment by sandmanman** [comment]
请问有人解决了吗，现在还是这个情况。umi -> 3.2.25
