### ISSUE TITLE
umi2如何不编译node_modules？

### ISSUE THREAD

**Issue by zwh1666258377** [umijs/umi#5119]
## What happens?

文档里说的实在太抽象了，请问有没有例子？感谢

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
本来就没编译的吧？

**Comment by zwh1666258377** [comment]
> 本来就没编译的吧？

看样子是编译了的 我怎么给你复现..

**Comment by xiaohuoni** [comment]
好的

**Comment by zwh1666258377** [comment]
> 好的

我的意思是我怎么给你复现这个问题，他确实是编译了的，构建速度很慢很慢，或者换个问题umi2可以怎么加快构建速度？ sry 我上面的问题可能问得并不准确

**Comment by sorrycc** [comment]
umi 2 默认不编译 node_modules。

**Comment by appzk** [comment]
● Webpack █████████████████████████ building (69%) 1776/1777 modules 1 active
  node_modules/_is-plain-obj@1.1.0@is-plain-obj/index.js

Starting the development server..

![image](https://user-images.githubusercontent.com/4745752/105272679-d33b3800-5bd4-11eb-8f3f-724ad54e65b2.png)
