### ISSUE TITLE
运行 umi build 是否必须下先保证  src/.umi/core/umiExports.ts 文件存在？

### ISSUE THREAD

**Issue by GiserTangqin** [umijs/umi#5129]
关于 官网上  [import from umi 没有定义怎么办](https://umijs.org/docs/faq) 

![image](https://user-images.githubusercontent.com/20224381/88873161-9fe3a600-d24e-11ea-89a6-196de865a7ef.png)

确保事件2，亲测运行  umi build 并不能生成 src/.umi/core/umiExports.ts 有关类容，导致打包继续报定义没，请问是否又解析方案遗漏?或是还有其他注意事项？

目前只有先运行了  umi dev 生成  .umi 相应文件后，一并提交到线上环境打包才可正常进行，希望能有更好的解决方案？
比如 umi build 能正确生成相应文件？

**Comment by leftstick** [comment]
`umi build` 生成的是`.umi-production`，而且编译完就自动删除了。

再一个，`umi build` 和你在ide里的提示也没关系。你需要的是`umi dev` 吧

**Comment by xiaohuoni** [comment]
这个问题是存在的。https://github.com/umijs/umi/issues/4633

**Comment by GiserTangqin** [comment]
@leftstick 
我需要的是 umi build ，但直接运行打包会失败报错
![image](https://user-images.githubusercontent.com/20224381/88889060-0f1ec180-d272-11ea-9fdc-ed8c91f33869.png)

初步确定是  没有  src/.umi/core/umiExports.ts  相关内容的原因导致 （但这个文件是 umi dev  生成）
所以才来咨询，
和  [#4633](https://github.com/umijs/umi/issues/4633)  问题一致

**Comment by xiaohuoni** [comment]
你可以在 build 之前执行下 umi generate tmp。来展示绕过这个问题。后续看修复情况。目前的问题，我觉得是 umi 不保管 typescript 导致的。

**Comment by GiserTangqin** [comment]
@xiaohuoni 嗯呢，目前确实是先采用类似的方式绕过

**Comment by leftstick** [comment]
高级，我还专门删了`.umi` 试了下编译，没报错。所以我猜这里面应该还有故事，你的项目里应该有能触发报错的东西。可以研究下，很6

**Comment by leftstick** [comment]
我觉得，tsconfig.json，稍微改一下：

```json
"paths": {
            "@/*": ["src/*"],
            "@@/*": ["src/.umi/*", "src/.umi-production/*"]
}
```

应该就没问题了，@GiserTangqin 你试试？

**Comment by xiaohuoni** [comment]
@GiserTangqin 我重试了一下，新版本好像没有这个问题了。你试试更新 umi 版本？
@leftstick 本来想试试你说的配置的。没重现环境了。不过就当可以了吧（假装学到了）

**Comment by GiserTangqin** [comment]
@leftstick  
"paths": {
            "@/*": ["src/*"],
            "@@/*": ["src/.umi/*", "src/.umi-production/*"]
}
这个配置确实没问题了~~（总归还是自己不会用~哈哈哈~）
@xiaohuoni 我当前环境使用的是最新 umi 版本

非常感谢两位百忙之中抽空帮忙解惑~~谢谢了~~
@leftstick @xiaohuoni

**Comment by crazyair** [comment]
> 你可以在 build 之前执行下 umi generate tmp。来展示绕过这个问题。后续看修复情况。目前的问题，我觉得是 umi 不保管 typescript 导致的。

![image](https://user-images.githubusercontent.com/7971419/100843329-29350e80-34b5-11eb-806d-2e7c291408a1.png)
之前 build 成功的 runner，今天重试都报错了，后来我在 build 前加上了 umi generate tmp 就好了
