### ISSUE TITLE
npm run build后，切换并没有显示  .umi.js配置的 loading页面

### ISSUE THREAD

**Issue by changyijie** [umijs/umi#513]
umi    `"version": "1.3.3"`        
   umi-build-dev     `"version": "0.18.3",`

> 同时 配置`.umi.js`中的 `loading `和不配置，打包生成的文件大小一样

>  `.umi.js` 文件配置

```
export default {
  plugins: [
    'umi-plugin-dva',
    ['umi-plugin-routes', {
      exclude: [
        /model/,
        /service/,
        /(\w){0,}Modal/,
      ],
    }],
  ],
  loading: './PageLoadingComponent',
}
```

>  文件目录

![image](https://user-images.githubusercontent.com/31202798/40302090-9ea15e72-5d20-11e8-82c3-1a38bbe8e491.png)

**Comment by xiaohuoni** [comment]
是不是现在页面加载比较快

**Comment by changyijie** [comment]
不，第一次加载时，出现1~2s空白页面。 而且我配置loading和不配置loading页面组件，打包文件大小并不变

**Comment by xiaohuoni** [comment]
经测试loading有效。
可以设置loading页面为
```js
export default () => {
console.log('loading')
return (<div>Loading Page...</div>)
};
```
这样有调用的时候，就能在日志中打印。

**Comment by webup** [comment]
@sorrycc @xiaohuoni 1.3.11也是这样，我在node_modules/umi/lib/dynamic.js里面打log，dynamic被引入的，但没被执行过，dist里面的umi.js和common.js里面也没有console.log loading的内容。

**Comment by webup** [comment]
跟了一下发现在umi-build-dev的routes/routesToJSON里面，开始是生成了dynamic(xxx, loadingopts）的，但在applyplugins之后ret被改写了，ret作为initialvalue传入给modifyRouteComponent，但这个函数根本没用这个。。。

@sorrycc @xiaohuoni

**Comment by sorrycc** [comment]
@webup @huangketong 有使用 umi-plugin-dva 吗？
