### ISSUE TITLE
umi3 ssr在build之后，点击跳转正常，但是在有二级路由的情况下刷新或者直接手动输入二级路由，都会报错404

### ISSUE THREAD

**Issue by chinafelix** [umijs/umi#5137]
#4679  What happens?

umi3 ssr在build之后，点击跳转正常，但是在有二级路由的情况下刷新或者直接手动输入二级路由，都会报错404

## 最小可复现仓库

https://github.com/chinafelix/umi-ssr-test

## 复现步骤，错误日志以及相关配置

1.build之后，执行node server.js运行，打开 http://localhost:7001或者 http://localhost:7001/base, 显示正常；
2.随便点击左侧菜单，再强制刷新页面，报错：umi.css 和 umi.js not found; 原因是文件路径多了一层 ‘base’；我不知道它是在哪里增加的。

## 相关环境信息

- **Umi 版本**：3.2.10
- **Node 版本**：v14.3.0
- **操作系统**：win10

**Comment by dechuangchang** [comment]
我也遇到了 找到什么解决办法了吗

**Comment by chinafelix** [comment]
还没有解决

**Comment by anita8004** [comment]
http://localhost:7001/scoreboard/soccer  & http://localhost:7001/scoreboard/soccer/league
更多層路由還是會有一樣的問題

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/105813185-53aac180-5f64-11eb-91b7-91e3dec6322a.png)
