### ISSUE TITLE
关于@umijs/plugin-qiankun2.5.1的使用

### ISSUE THREAD

**Issue by lipenghu001** [umijs/umi#5141]
**@umijs/plugin-qiankun2.5.1的使用**
主应用umi3，没问题
子应用umi2,   如何配置 @umijs/plugin-qiankun?

**Comment by lipenghu001** [comment]
umi2与3版本差距有点大。在使用 @umijs/plugin-qiankun 1或者2时，分别需要怎样配置。文档并没有做好区分和解释。

**Comment by kuitos** [comment]
umi2 对应的插件 https://github.com/umijs/umi-plugin-qiankun

**Comment by tomee-oy** [comment]
> umi2与3版本差距有点大。在使用 @umijs/plugin-qiankun 1或者2时，分别需要怎样配置。文档并没有做好区分和解释。

可以分享一下你的解决方案吗？
