### ISSUE TITLE
umi3.x约定式路由怎么新增exclude

### ISSUE THREAD

**Issue by tianjixiaoqiang** [umijs/umi#5144]
需要注意的是，满足以下任意规则的文件不会被注册为路由，
以 . 或 _ 开头的文件或目录
以 d.ts 结尾的类型定义文件
以 test.ts、spec.ts、e2e.ts 结尾的测试文件（适用于 .js、.jsx 和 .tsx 文件）
components 和 component 目录
utils 和 util 目录
不是 .js、.jsx、.ts 或 .tsx 文件
文件内容不包含 JSX 元素
——————————————————————
我怎么拓展这个规则

**Comment by xiaohuoni** [comment]
可以装 @alitajs/routes 用法和 umi@2 一致
