### ISSUE TITLE
打包后从服务器端（flask)渲染时，报错

### ISSUE THREAD

**Issue by gaohongwei** [umijs/umi#5146]
该问题与应用内容无关，最简单的例子，
也有这个问题。

本地启动没有问题 
umi dev
umi build;cd dist;serve -d .
以上两种方法都没问题。

把dist 拷贝到服务器相应目录，从服务器端（flask)渲染时,
（服务器端支持 'unsafe-inline' 'self' 安全策略)
如下错误
Refused to execute inline script because it violates the following Content Security Policy directive: "default-src *". Either the 'unsafe-inline' keyword, a hash ('sha256-YM8uI2F+VfHULiDF1T+UCYmPwssvvWleyz5k2gtmTQo='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

localhost/:13 Refused to execute inline script because it violates the following Content Security Policy directive: "default-src *". Either the 'unsafe-inline' keyword, a hash ('sha256-+SgnNI1LpzxFqZ3RqS4f1ACa8GIyDivfy6TfgwLiXJ8='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

localhost/:1 Refused to apply style from 'http://localhost:5000/umi.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:5000/umi.server.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by xy2009** [comment]
@sorrycc @gaohongwei 两位大神，你好， 请问此问题如何解决了，未找到相应的方案，烦请指点迷津，谢谢🙏
