### ISSUE TITLE
Eslint doesn't work when I run umi dev

### ISSUE THREAD

**Issue by leadream** [umijs/umi#5150]
## What happens?

I justed installed `umi-lint` and created `.eslintrc` but Eslint doesn't work when I run `umi dev`

## Mini Showcase Repository(REQUIRED)

https://github.com/leadream/umi-app

## How To Reproduce

**Steps to reproduce the behavior:**
1. install dependencies
2. run `yarn start` to start app
3. There's no errors in the dev console (left) but I can see errors when running `yarn lint` (right)
![image](https://user-images.githubusercontent.com/12868055/89148972-e5c1a680-d58d-11ea-8578-bbb0af1fe3ab.png)

**Expected behavior** 1. 2.
I can see the errors when dev server compiling files.

## Context

- **Umi Version**: 3.2.14
- **Node Version**: v13.9.0
- **Platform**: MacOS 10.15.5

**Comment by sorrycc** [comment]
lint 没有在 dev 时执行，不报错符合预期。

**Comment by leadream** [comment]
> lint 没有在 dev 时执行，不报错符合预期。

需要自己配置是吗？

**Comment by empty916** [comment]
那该怎么配置，让eslint在dev环境有提示？

**Comment by leadream** [comment]
@empty916 在 config 中添加下面的配置：

```javascript
  chainWebpack(config) {
    config.module
      .rule('lint')
      .test(/\.js(x)?$/)
      .pre()
      .include.add(resolve(__dirname, '../src'))
      .end()
      .use('eslint')
      .loader('eslint-loader')
      .options({
        configFile: isDev ? './.eslintrc.dev' : './.eslintrc.prod',
      });
  }
```

**Comment by empty916** [comment]
@leadream 感谢，目前已经不用了，现在的机制是在提交的时候有lint，这样也可以接受
