### ISSUE TITLE
umi+qiankun 子应用配置了qiankun: {slave:{}}启动项目报错“You should have name in package.json”

### ISSUE THREAD

**Issue by juntaozhou05** [umijs/umi#5151]
## umi.ts配置slave为空会报错的。：

```
import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  routes: [{ path: '/', component: '@/pages/index' }],
  qiankun: {
    slave: {},
  },
});
```

启动项目npm run start 报错：

You should have name in package.json
AssertionError [ERR_ASSERTION]: You should have name in package.json

## 相关环境信息

- **Umi 版本**：3.2.13
- **@umijs/plugin-qiankun版本**：2.6.1
- **Node 版本**：12.16.2
- **操作系统**：mac

**Comment by kuitos** [comment]
`You should have name in package.json`

**Comment by lanweifeng** [comment]
配置了name后路由会无限跳转

**Comment by luokaiii** [comment]
要在package.json中配置name
