### ISSUE TITLE
[Feature Request] 如何在 umi build 生成一个随机码并写入文件

### ISSUE THREAD

**Issue by hihuangwei** [umijs/umi#5152]
## Background

如何在 umi build 生成一个随机码并写入文件

**Comment by leftstick** [comment]
自定义环境变量应该可以做到。

BTW，这是要干嘛？

**Comment by hihuangwei** [comment]
> 自定义环境变量应该可以做到。
> 
> BTW，这是要干嘛？

每次build 自动生成一个版本号

**Comment by leftstick** [comment]
环境变量就可以做到。加油

**Comment by hihuangwei** [comment]
> 环境变量就可以做到。加油

可以来个demo吗 非常感谢

**Comment by hihuangwei** [comment]
npm version patch 就可以实现 目的
