### ISSUE TITLE
export 'Access' was not found in 'umi'

### ISSUE THREAD

**Issue by effapp** [umijs/umi#5154]
## What happens?

import { Access } from 'umi';
这一句报错了：export 'Access' was not found in 'umi'

## Context

- **Umi Version 3.2.14:

**Comment by effapp** [comment]
![image](https://user-images.githubusercontent.com/51013754/89195133-e3d20480-d5da-11ea-9205-baaca7adc579.png)

**Comment by ycjcl868** [comment]
`umi g tmp`
