### ISSUE TITLE
yarn start 后没有正常启动

### ISSUE THREAD

**Issue by Chenqt5** [umijs/umi#5157]
执行yarn start 后服务没有启动

yarn run v1.16.0
$ cross-env umi dev
Starting the development server...

● Webpack █████████████████████████ additional chunk assets processing (90%)

Done in 51.68s.

**Comment by sorrycc** [comment]
应该是报错了，加环境变量 FRIENDLY_ERROR=none 试试。

**Comment by xiaohuoni** [comment]
@Chenqt5 cc

**Comment by jin-benben** [comment]
安装插件plugin-esbuild之后也是同样的问题，启动不了了
