### ISSUE TITLE
umijs request 问题

### ISSUE THREAD

**Issue by gaohongwei** [umijs/umi#5158]
几个问题请教

1. umijs request 对API 的 response 有什么要求，list/index 总数，页面等？ 没找到说明。
2. 与axios相比，umijs request有什么好处？
3. umijs request通过增加{method: 'aaa'},把多种API包装成POST请求， 是否是一种好的约定？

**Comment by xiaohuoni** [comment]
详情请见官网 https://github.com/umijs/umi-request/blob/master/README_zh-CN.md
还有其他问题可以在那边问作者。
