### ISSUE TITLE
请问空标签<></>是通过哪个包实现的

### ISSUE THREAD

**Issue by MangGoDio** [umijs/umi#5159]
react16里提供了Fragment但是显得很臃肿，最近用umi发现这个空标签非常好用，没有查到相关资料，来咨询下大佬是通过插件还是包之类实现的？

**Comment by blueway** [comment]
<></> 应该就是Fragment， 你通过eslint --fix 应该会把所有<Fragment></Fragment> 替换成<></>

**Comment by leadream** [comment]
是 Fragment 的简写形式：
https://reactjs.org/docs/fragments.html#short-syntax

**Comment by MangGoDio** [comment]
> 是 Fragment 的简写形式：
> https://reactjs.org/docs/fragments.html#short-syntax

.......，原来是这样的吗，感谢分享
