### ISSUE TITLE
window.g_app._store.dispatch问题

### ISSUE THREAD

**Issue by wgwxf** [umijs/umi#516]
进入首页，执行多个查询：
index/fetchNews
index/fetchQuestion
index/fetchCourse

其中，前两个不登录可查询，第三个必须登录才能查询

request.js中，判断如果是未登录（未登录response.status=401），dispatch弹窗显示登录二维码
按理说，前两个应该查询出来并渲染结果，在ant-pro没问题，改成umi出了问题：
前两个查询执行到下面不走了：
      // 调用接口
      const data = yield call(indexService.getNewsList, { pageSize: 3 });
      console.log(data);
console没打印。

如果屏蔽掉第三个查询，前两个查询正常执行。

**Comment by xiaohuoni** [comment]
我不太理解，最好是有重现demo

**Comment by wgwxf** [comment]
明白了，dva异常未捕获，导致其他请求也中端了，加了个dva.js，catch exception：
export function config() {
  return {
    onError(err) {
      err.preventDefault();
    },
    initialState: {
    },
  };
}
