### ISSUE TITLE
umi官方文档路由重定向有问题

### ISSUE THREAD

**Issue by Pasoul** [umijs/umi#5162]
## What happens?

[https://umijs.org/zh/config/#treeshaking](https://umijs.org/zh/config/#treeshaking) 不能正确打开这个页面，会重定向到首页
试试其他的链接[https://umijs.org/zh/guide/load-on-demand.html#%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD%E7%BB%84%E4%BB%B6](https://umijs.org/zh/guide/load-on-demand.html#%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD%E7%BB%84%E4%BB%B6)

**Comment by xiaohuoni** [comment]
没有 treeShaking 配置， 默认开了。
