### ISSUE TITLE
umi3.x 版本treeShaking配置

### ISSUE THREAD

**Issue by 24Kshign** [umijs/umi#5163]
想请问一下3.x没有treeShaking这个配置了吗

**Comment by xiaohuoni** [comment]
默认开了。

**Comment by jing-wu** [comment]
> 默认开了。

可以配置关闭吗？

**Comment by sorrycc** [comment]
原因是啥，为啥要关？

**Comment by jing-wu** [comment]
我这边利用umi，扩展成了模块化开发的框架，容器框架提供三方库的全量依赖，外部模块化代码不含三方依赖，而是调用框架提供的依赖。现在tree shaking了，使框架的三方依赖不完整，导致外部模块运行报错。

所以想着关闭 tree shaking，以实现我的功能。建议还是提供开关 tree shaking 的配置项给开发者，由大家自己选择。

**Comment by sorrycc** [comment]
> 容器框架提供三方库的全量依赖

把相关内容全部导出一遍呢？

**Comment by jing-wu** [comment]
这工作量有点大了，比如要把 antd 的所有组件导出一遍😂，而且 antd 以后加一个组件还得改导出文件，有点麻烦了

**Comment by sorrycc** [comment]
antd 的话，用 external 的方式全量载吧。

**Comment by jing-wu** [comment]
这样还是有不少限制和不便的地方，我看还有不少人问这个配置项，还是建议大佬加个  treeShaking 的配置吧🙏

**Comment by sorrycc** [comment]
你是第一个问怎么关的。。

**Comment by m9rco** [comment]
我是第二个问怎么关的 😂  ( 我在引用一个UI组件时 发现部分方法没有打包进来 导致 undefined )

我在 `package.json` 里加入 

```json
 "sideEffects": [

  ],
```
会提示
```bash
umi.9adbe72e.js:177 Uncaught TypeError: Cannot read property '@@initialState' of undefined
```
