### ISSUE TITLE
useRequest的泛型约束问题

### ISSUE THREAD

**Issue by SmartWrh** [umijs/umi#5164]
```
  const loginRequest = useRequest<UserData>(accountLogin, {
    formatResult: res => res,
    manual: true,
    onSuccess: data => loginSuccess(data)
  });
```
为何在`onSuccess`的`data`没有被自动推断为`UserData`？

Umi版本**umi@3.2.12**

**Comment by brickspert** [comment]
这个不好写，onSuccess 的入参等于 formatResult 的出参~

**Comment by SmartWrh** [comment]
> 这个不好写，onSuccess 的入参等于 formatResult 的出参~

栗子中的```formatResult```出参就是```UserData```类型的哇

**Comment by xiaohuoni** [comment]
@brickspert cc

**Comment by brickspert** [comment]
这个 ts 是推断不出来的。

onSuccess 的入参等于 formatResult 的出参。
