### ISSUE TITLE
如何去掉 Antd 的样式？

### ISSUE THREAD

**Issue by leadream** [umijs/umi#5165]
我发现默认的 demo 没有引入 Antd 样式，但是一旦加了 Umi 中的组件，比如说 Link，就会引入 Antd 样式。比如下图，添加了 `import { Link } from 'umi';` 并且在代码中使用 Link 之后，就自动引入了 Antd 的样式（链接颜色、选中文字背景色、body 的 reset）。

文档中提到了默认开启 Antd 插件，但是没有说如何关闭，请问下如何不引入 Antd 的样式呢？谢谢。

![image](https://user-images.githubusercontent.com/12868055/89265232-c3e82280-d666-11ea-82ff-e44e0bcb71a5.png)

**Comment by xiaohuoni** [comment]
理论上来说，不装 plugin-antd 这个插件就可以的，你可以不安装preset-react。只安装你需要的插件就好。清单列表在 https://umijs.org/plugins/preset-react

**Comment by leadream** [comment]
@xiaohuoni  移除 `@umijs/preset-react` 之后就无法编译 React 了。`@umijs/plugin-antd` 没有显式安装在 `package.json` 里面没法移除。Umi 配置是不是要增加支持移除选项？

![image](https://user-images.githubusercontent.com/12868055/89365580-796ab280-d707-11ea-985c-32d549a7241e.png)

**Comment by xiaohuoni** [comment]
@leadream 要把你需要的插件装回来。你这报错是少装了 dva 插件。

**Comment by leadream** [comment]
@xiaohuoni 真的可以了，谢谢！移除 `preset-react` 然后再安装 `plugin-dva` 就可以了，不过还是希望 `preset-react` 里面的预置插件可以支持配置开关。
