### ISSUE TITLE
ssr渲染，cookie 的透传问题

### ISSUE THREAD

**Issue by robinv8** [umijs/umi#5166]
## What happens?

![image](https://user-images.githubusercontent.com/12277531/89281758-21876980-d67d-11ea-804a-e30c99a5ea14.png)
可以通过 ctx 拿到 cookie 中的 Token, 不知道怎么传到 umi.server 的 request 层

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by williamnie** [comment]
参见ssr-koa的demo，可以通过global对象传过去

**Comment by robinv8** [comment]
如果A、B两用户依次访问，由于异步的问题，B用户的cookis会覆盖A用户的cookis

**Comment by williamnie** [comment]
不会啊，看下ssr-koa的例子就知道了，不会覆盖

**Comment by robinv8** [comment]
我现在的做法是通过 getInitialPropsCtx 对象传递Token，如果使用 global，多人访问会造成全局变量污染的情况

**Comment by williamnie** [comment]
> 我现在的做法是通过 getInitialPropsCtx 对象传递Token，如果使用 global，多人访问会造成全局变量污染的情况

感觉有可能，我后续跟进一下，测试看看

**Comment by wangjiangs** [comment]
请问在开发时怎么拿到cookie？看ssr-koa都是只能在运行时修改运行脚本才拿到cookie的，那么我在本地开发时怎么拿到呢？

**Comment by robinv8** [comment]
> 请问在开发时怎么拿到cookie？看ssr-koa都是只能在运行时修改运行脚本才拿到cookie的，那么我在本地开发时怎么拿到呢？

我目前的做法：
![image](https://user-images.githubusercontent.com/12277531/123031375-ca19f580-d416-11eb-8c2e-959260087d94.png)

**Comment by williamnie** [comment]
> 请问在开发时怎么拿到cookie？看ssr-koa都是只能在运行时修改运行脚本才拿到cookie的，那么我在本地开发时怎么拿到呢？

不是啊，一直可以拿到cookie的啊，在客户端正常获取，在服务端通过koa的api就能获取

**Comment by wangjiangs** [comment]
> > 请问在开发时怎么拿到cookie？看ssr-koa都是只能在运行时修改运行脚本才拿到cookie的，那么我在本地开发时怎么拿到呢？
> 
> 不是啊，一直可以拿到cookie的啊，在客户端正常获取，在服务端通过koa的api就能获取

我的意思是在本地用yarn start启动开发的时候，没地方可以操作koa的api啊，只有打包后，运行的时候，才能操作koa的api。

**Comment by williamnie** [comment]
开发的时候为啥拿不到koa的api？dev环境下在server端调用parseCookie方法， 在客户端调用getCookie方法，就好了啊，koa的例子里都封装好了啊，肿么会拿不到呢

**Comment by wangjiangs** [comment]
> 开发的时候为啥拿不到koa的api？dev环境下在server端调用parseCookie方法， 在客户端调用getCookie方法，就好了啊，koa的例子里都封装好了啊，肿么会拿不到呢

哦哦，我知道了，看了下ssr-koa的dev命令，要按照它的这种写法来才可以在开发时使用koa，多谢啦。
