### ISSUE TITLE
菜单路由不支持多个多级嵌套菜单，当出现第二个后，报404

### ISSUE THREAD

**Issue by CarreyZhang** [umijs/umi#5167]
## What happens?

菜单路由不支持多个多级嵌套菜单，当出现第二个后，
报错：
umi development 404 page 
There's not a page yet at /xxxx/xxx
Create a React.js component in your pages directory at src/xxxx/xxx/index.js and config the route in config file then this page will automatically refresh to show the new page component you created.

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
在config/config.ts文件中新增路由，无法添加多个嵌套路由
**Expected behavior** 1. 2.
支持添加多个嵌套路由，不报上面404的错误
## Context

- **Umi Version**:
2.8.7/2.8.20 
- **Node Version**:
12.18.2
- **Platform**:
windows

**Comment by xiaohuoni** [comment]
请提供复现步骤
