### ISSUE TITLE
配置路由文件时导出的打印出来是array没错，但是一直报错提示Validate config "routes" failed, "value" must be an array

### ISSUE THREAD

**Issue by gaomeng965** [umijs/umi#5171]
## What happens?

配置路由文件时导出的打印出来是array没错，但是一直报错提示Validate config "routes" failed, "value" must be an array
routes [
  {
    path: '/travel',
    component: '../layouts/index',
    routes: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  {
    path: '/',
    component: '../layouts/index',
    routes: [ [Object], [Object], [Object], [Object], [Object] ]
  }
]

Validate config "routes" failed, "value" must be an array
ValidationError: "value" must be an array

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.0
- **Node Version**: 13.7 
- **Platform**: mac

**Comment by gaomeng965** [comment]
![image](https://user-images.githubusercontent.com/22706391/89365137-9652b600-d706-11ea-8618-05a33b5a53a7.png)

**Comment by gaomeng965** [comment]
原先是umi2.0的没问题，升级成3.0的，就出现这个了

**Comment by weiqq45** [comment]
怎么解决这个问题的呢？

**Comment by zhoustudent** [comment]
@gaomeng965 想问下这个是怎么解决的呢？我这也出现这个情况了。。。。

**Comment by cxw2014** [comment]
@zhoustudent 请问你这解决了吗
