### ISSUE TITLE
配置 extraBabelPlugins import 报错

### ISSUE THREAD

**Issue by tdida** [umijs/umi#5173]
## What happens?

`extraBabelPlugins: [
    ['import', { libraryName: 'qnzs-ui', libraryDirectory: 'es', style: true }, 'import-qnzs'],
  ]`

配置 extraBabelPlugins import，报错如下

![image](https://user-images.githubusercontent.com/18672870/89380658-792fde80-d72a-11ea-8e0c-65fd4c2bc1a2.png)

## Context

- **Umi Version**: 3.2.14
- **Node Version**: 12.13.1
- **Platform**:

**Comment by xiaohuoni** [comment]
有 demo 嘛？
