### ISSUE TITLE
配置路由下，开启layout，自动生成的菜单直接不见了

### ISSUE THREAD

**Issue by mov1er** [umijs/umi#5174]
## What happens?

配置路由下，开启layout，自动生成的菜单直接不见了
一个月前上线时是有的，今天重新clone项目跑起来就没了，什么鬼！

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/umijs/umi/issues

## 相关环境信息

- **Umi 版本**：umi@3.2.14
- **Node 版本**：v12.16.3
- **操作系统**：macOS 10.15.5

**Comment by xiaohuoni** [comment]
是什么东西不见了？
你的配置怎么写的？
最好给一个重现demo
