### ISSUE TITLE
mock是否能支持配置跨域OPTIONS前置请求

### ISSUE THREAD

**Issue by yukilzw** [umijs/umi#5176]
## 问题描述：

在本地运行https开发服务，利用代理软件将线上域名代理到本地localhost资源html模板进行开发。
因为当前域名为线上域名，需要请求mock域名为本地，会有跨域问题，一般在mock文件下配置setHeader可解决，但是复杂跨域请求会触发OPTIONS请求校验，目前umi是否有办法mock OPTIONS请求？

## 相关环境信息

- **Umi 版本**：3.1.2
- **Node 版本**：12
- **操作系统**：mac

**Comment by xiaohuoni** [comment]
通过 [proxy](https://umijs.org/zh-CN/config#proxy) 设置，绕过开发时候的跨域访问问题就好。

**Comment by yukilzw** [comment]
proxy只能代理远程接口，现在是访问localhost本地mock跨域

**Comment by xiaohuoni** [comment]
> proxy只能代理远程接口，现在是访问localhost本地mock跨域

写本地ip和端口也能代理的
