### ISSUE TITLE
对象不支持“flat”属性或方法

### ISSUE THREAD

**Issue by azx1985** [umijs/umi#5177]
## What happens?
在IE浏览器的情况下报对象不支持“flat”属性或方法的错误，谷歌的版本低版本也会报对象不支持“flat”属性或方法的错误；
已经在入口document.ejs里面添加了Array.prototype.flat，还是把报错；
网址是： devmc.sangon.com；

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:2.13.3
- **Node Version**:10.15.3
- **Platform**:

**Comment by azx1985** [comment]
https://blog.csdn.net/m0_37624880/article/details/84944265?utm_medium=distribute.pc_aggpage_search_result.none-task-blog-2~all~first_rank_v2~rank_v25-1-84944265.nonecase
可以参考这个兼容问题

**Comment by xiaohuoni** [comment]
开了 https://umijs.org/config#targets 配置了嘛？

**Comment by azx1985** [comment]
在umi的config文件夹里的config.js里面添加了targets: { chrome: 49, firefox: 64, safari: 5, edge: 13, ios: 10, ie: 11 }

**Comment by xiaohuoni** [comment]
直接写 ie:9 试试

**Comment by xiaohuoni** [comment]
相同的问题 https://github.com/umijs/umi/issues/3620
