### ISSUE TITLE
umi 3.x 开启服务端渲染SSR后，配置styleLoader，样式加载不出来

### ISSUE THREAD

**Issue by tangweixiong** [umijs/umi#5179]
## What happens?

umi 3.x 开启ssr，同时配置styleLoader，样式加载不出来，原因估计是同构时，服务端的css module的hash值与客户端生成的hash值不一样

// config.js
export default {
  ssr: {
    mode: 'stream',
    forceInitial: false,
  },
  styleLoader: {}
}

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## Context

- **Umi Version 3**:
- **Node Version 10.15.3**:
- **Platform mac**:

**Comment by ycjcl868** [comment]
不需要配置 styleLoader，umi 内部会处理好的，我这里的 项目 都正常使用的
