### ISSUE TITLE
运行时配置 中的onRouteChange 函数 首次加载会执行两次

### ISSUE THREAD

**Issue by chenbingweb** [umijs/umi#5181]
运行时配置 中的onRouteChange 函数 首次加载会执行两次

## Context

- **Umi Version**:3.0
- **Node Version**:
- **Platform**:mac

**Comment by ccksfh** [comment]
+1

**Comment by li2215890610** [comment]
+1

**Comment by LiuJinYang9527** [comment]
+1

**Comment by ineedacatmiao** [comment]
+1

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/104839831-c2ea3b00-58fe-11eb-9d1e-56201564694e.png)
不能复现。

**Comment by youtiao66** [comment]
+1 复现仓库【https://github.com/youtiao66/umi-route-change-twice】

**Comment by citrusjunoss** [comment]
+1

**Comment by rushairer** [comment]
+1
