### ISSUE TITLE
开启 dynamicImport 导致Echarts的渐变失效

### ISSUE THREAD

**Issue by boomsi** [umijs/umi#5182]
配置项开启 dynamicImport 
`{
        loadingComponent: './components/PageLoading/index',
        webpackChunkName: true,
}`
能看到懒加载效果是 ok 的，但是我定义在global的部分样式失效了
比如 Button，此外，echarts 的 visualMap 属性设置颜色渐变也失效了，为什么会这样呢？

umi v2.9.6
node v12.14.0
win10 1909

**Comment by boomsi** [comment]
chrome  v84.0.4147.105

**Comment by boomsi** [comment]
global定义的样式找到原因，是权重不够了，需要加important才会生效，为什么？
另外Echarts的渐变失效的原因还是没找到

**Comment by xiaohuoni** [comment]
相同的问题 https://github.com/umijs/umi/issues/4039

**Comment by boomsi** [comment]
> 相同的问题 #4039

Echarts 渐变也失效了（写在option的配置项），这个不是外部的样式，请问这个怎么处理？

**Comment by xiaohuoni** [comment]
@boomsi 是什么失效？这里说的失效是权重不够的问题。

**Comment by boomsi** [comment]
> @boomsi 是什么失效？这里说的失效是权重不够的问题。

譬如：
![image](https://user-images.githubusercontent.com/39713960/95566085-add65400-0a53-11eb-832a-dcecc4ee790c.png)
echarts的这个渐变是option里的参数控制
![image](https://user-images.githubusercontent.com/39713960/95566163-c9d9f580-0a53-11eb-9b49-4c528385f898.png)
这个渐变在开启懒加载后就不生效了

**Comment by boomsi** [comment]
> 相同的问题 #4039

可以看下我上一个回复
谢谢+^+

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
