### ISSUE TITLE
编译时提示注释无法解析

### ISSUE THREAD

**Issue by skyunBoss** [umijs/umi#5185]
/*
 * @PageName: 
 * @Author: 
 * @Description:
 */
注释出现@符号会在编译时出现如下错误：
![image](https://user-images.githubusercontent.com/29365288/89501861-a5189600-d7f6-11ea-8474-a5e488e4a107.png)

umi v2.7.7
node v12.18.2

**Comment by xiaohuoni** [comment]
顶部注释会有 yaml 的功能

**Comment by j78742** [comment]
> 顶部注释会有 yaml 的功能

可是我需要在顶部添加一个页面信息说明，这边要怎么搞？可以按页面开启yaml吗

**Comment by dz333333** [comment]
就没有解决方案就关掉了?
