### ISSUE TITLE
umi 3.x 与 umi-plugin-auto-externals 插件不兼容吗？每次安装都会出错

### ISSUE THREAD

**Issue by KingThq** [umijs/umi#5186]
## What happens?

创建pro项目4.x版本，安装 umi-plugin-auto-externals 插件报错

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

yarn add umi-plugin-auto-externals 就报错了
错误信息：Cannot read property 'packages' of undefined

## 相关环境信息

- **Umi 版本**：3.2.0
- **antd 版本**：4.4.0
- **Node 版本**：12.18.0
- **操作系统**：macOS

**Comment by xiaohuoni** [comment]
umi-plugin-auto-externals 这个库不维护了。
