### ISSUE TITLE
国际化 useIntl 不是用hooks写的咋整，一用就抱错。

### ISSUE THREAD

**Issue by sl798970799** [umijs/umi#5188]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by shaohuatsou** [comment]
好好描述你的问题，别发这种没用的。

**Comment by bingo618** [comment]
我是使用<FormattedMessage />组件。

**Comment by ycjcl868** [comment]
https://umijs.org/plugins/plugin-locale#useintl
