### ISSUE TITLE
ignore “.umi“

### ISSUE THREAD

**Issue by zinkey** [umijs/umi#519]
ignore the “.umi“, because users don't care

should we put it in node_modules ?

**Comment by aweffr** [comment]
Sometimes I check the .umi file to track the routes and model registeration while debuging.

So far I personally think putting .umi/ under `pages` dir make sense, because it's highly related together, and I'd like to see **explicitly** the change in git diff when I change the file orginzation.

**Comment by zinkey** [comment]
Provide a 
api for user selection?
