### ISSUE TITLE
umi2升级到3，项目无法热更新

### ISSUE THREAD

**Issue by piluohen-huaigu** [umijs/umi#5190]
按照文档umi2升级到3，热更新使用
{
dva:{
  hmr: true
}
}

结果是
1、修改src下的任何文件都无法热更新
2、修改.umirc.js 竟然可以热更新

什么鬼？

- **Umi 版本**：
3.2.14
- **Node 版本**：
12.16.3
- **操作系统**：
macOS Catalina 10.15.5

**Comment by williamnie** [comment]
是ssr模式，还是csr模式？

**Comment by piluohen-huaigu** [comment]
> 是ssr模式，还是csr模式？

csr模式

**Comment by piluohen-huaigu** [comment]
已知道原因。
umi3里outputPath的配置名称不能与工程名称相同。
推测umi3里应该排除了outputPath目录下的热更新，又没有对工程名称与outputPath的目录层级进行区分，所以直接也排除了工程下的热更新。

**Comment by piluohen-huaigu** [comment]
> 已知道原因。
> umi3里outputPath的配置名称不能与工程名称相同。
> 推测umi3里应该排除了outputPath目录下的热更新，又没有对工程名称与outputPath的目录层级进行区分，所以直接也排除了工程下的热更新。

@williamnie

**Comment by fygethub** [comment]
我也遇到了热更新到70% 就不动而且服务还关不掉
