### ISSUE TITLE
onDevCompileDone怎样知道哪些文件更新

### ISSUE THREAD

**Issue by wjjhhh** [umijs/umi#5191]
请问onDevCompileDone有参数提供哪些文件更新吗？

## 相关环境信息

- **Umi 版本**：3.2.3
- **Node 版本**：12.16.1

- **操作系统**：win10

**Comment by xiaohuoni** [comment]
支持三个参数，你可以看看其中有没有你要的数据。

| key | value type |
|  :-  | :-:  |
| isFirstCompile | boolean |
| type | "csr" | "ssr" |
| stats | webpack.Stats |

**Comment by wjjhhh** [comment]
> 支持三个参数，你可以看看其中有没有你要的数据。
> 
> key	value type
> isFirstCompile	boolean
> type	"csr"
> stats	webpack.Stats

就是没找到

**Comment by xiaohuoni** [comment]
那就是不支持（捂脸）

**Comment by leftstick** [comment]
@wjjhhh  我是这么做的，挫是挫了点，但能用：

https://github.com/chenshuai2144/umi-plugin-antd-theme/pull/24/files

**Comment by wjjhhh** [comment]
> @wjjhhh 我是这么做的，挫是挫了点，但能用：
> 
> https://github.com/chenshuai2144/umi-plugin-antd-theme/pull/24/files

我擦无情
