### ISSUE TITLE
index.html文件在哪？

### ISSUE THREAD

**Issue by xu-Aurora** [umijs/umi#5194]
想在index.html文件中修改meta标签，整个项目上都没有找到index.html文件

**Comment by hc-codersatlas** [comment]
https://umijs.org/zh-CN/docs/html-template

**Comment by FrankFan** [comment]
同问， umi v4 的 index.html文件在哪？

**Comment by fz6m** [comment]
Umi 4 ：[document.ejs 去哪了，如何自定义 HTML 模板](https://umijs.org/docs/introduce/faq#documentejs-%E5%8E%BB%E5%93%AA%E4%BA%86%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89-html-%E6%A8%A1%E6%9D%BF)
