### ISSUE TITLE
在Mac OS端使用useModel存在一些问题.

### ISSUE THREAD

**Issue by joesdu** [umijs/umi#5195]
## What happens?

在Mac OS中使用useModel会出现需要将名称写两次的情况,在Windows中写法也不一样.如下图所示:
![image](https://user-images.githubusercontent.com/13188169/89756001-d86b6580-db13-11ea-995b-e5172aa75907.png)
```typescript
  const { refresh } = useModel('@@initialState');
  // Todo Mac OS下要写login.login ?
  const { loading, signIn } = useModel('login.login');
  // Todo Windows下要写login
  const { loading, signIn } = useModel('login');
```
希望官方能修复一下这个问题,各个平台代码不一样不太好.

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by tli4** [comment]
之前在 windows 环境下是有问题的，在 POSIX 下是预期行为。目前 windows 下的行为在 plugin-model@2.5.2 已经修正。
只有全局的 model 是没有前缀的，为了避免重名，建在页面里的 models 都是有前缀的，举几个例子

| path | namespace |
|-|-|
| src/models/global.ts | global |
| src/pages/models/user.js | user |
| src/pages/DashBoard/models/drawer.ts | DashBoard.drawer |
| src/pages/DashBoard/stat.model.ts | DashBoard.stat |
| src/pages/DashBoard/Chart/models/data.ts | DashBoard.Chart.data |
