### ISSUE TITLE
是否支持为页面指定 html 模板？

### ISSUE THREAD

**Issue by jing-wu** [umijs/umi#5196]
`history: {type: 'hash'}`，且未开启 `exportStatic`，这种情况下，是否支持为某个页面指定独立的 html 模板？

**Comment by xiaohuoni** [comment]
现在还不支持为某个页面制定独立的模版，现在都是统一通过 [src/pages/document.ejs](https://umijs.org/zh-CN/docs/html-template#%E4%BF%AE%E6%94%B9%E9%BB%98%E8%AE%A4%E6%A8%A1%E6%9D%BF) 指定。
