### ISSUE TITLE
不支持mp3文件引入吗？请问怎么配置？

### ISSUE THREAD

**Issue by yangdachu** [umijs/umi#5197]
![image](https://user-images.githubusercontent.com/23580181/89760666-6731af80-db1f-11ea-8c6d-3fb3e4035e0a.png)

安装了file-loader
然后在config.js里配置了

```
  chainWebpack(memo) {
    memo.module
      .rule('media')
      .test(/\.(mp3|4)$/)
      .use('file-loader')
      .loader(require.resolve('file-loader'))
  },
```

没作用，还是一样的报错

**Comment by xiaohuoni** [comment]
在我们的项目中，它是有效的。如果你需要协助定位问题，请提供 demo。

**Comment by jclegendary** [comment]
> ![image](https://user-images.githubusercontent.com/23580181/89760666-6731af80-db1f-11ea-8c6d-3fb3e4035e0a.png)
> 
> 安装了file-loader
> 然后在config.js里配置了
> 
> ```
>   chainWebpack(memo) {
>     memo.module
>       .rule('media')
>       .test(/\.(mp3|4)$/)
>       .use('file-loader')
>       .loader(require.resolve('file-loader'))
>   },
> ```
> 
> 没作用，还是一样的报错你

你的test写错了，正确是  .test(/\.mp(3|4)$/)
