### ISSUE TITLE
当项目比较大的时候 , 热更新很慢,有无办法提升一下

### ISSUE THREAD

**Issue by 544751779** [umijs/umi#5198]
当项目比较大的时候 , 热更新很慢,有无办法提升一下

**Comment by piluohen-huaigu** [comment]
devtool: 'eval'
试一下

**Comment by ycjcl868** [comment]
dev 下默认 `devtool: false`，不会生成 sourceMap，这个得看具体 demo

**Comment by itellyou-com** [comment]
确实，之前我umi3.2，这两天升级到了umi最新版。本身项目比较大，修改了文件保存后，这边还没热更新完，我又继续修改文件后继续保存。结果感觉好像进了死循环了。
···
  App running at:
  - Local:   http://localhost:8000 (copied to clipboard)
  - Network: http://192.168.1.6:8000
Compiled...
···
一直循环这个，由于开启了ssr，很多样式警告，具体日志不好看到。
有时候循环有个几分钟就好了。。。可能项目大，文件多的原因。不太好复现 @ycjcl868

**Comment by sorrycc** [comment]
热更新慢是因为依赖多，参考 https://umijs.org/zh-CN/guide/boost-compile-speed 这里的方式优化下。

**Comment by LoveEocding** [comment]
太慢了umi 以后用vite
