### ISSUE TITLE
umi/Link, umi/router can't trigger state change with dva.

### ISSUE THREAD

**Issue by elivoa** [umijs/umi#52]
```javasciprt
<Link to="xx">link</Link>
```
or 
```javascript
router.push('/path')
```

can change url and route to new page, but can't trigger state change in umi+dva project.

Subscription and life-circle method like componentWillReceiveProps will not run.

**Comment by elivoa** [comment]
I saw the the generated .umi/router.js use ```<Router history='...' >```

How to use ```<ConnectedRouter>```?

Is this the reason why state doesn't change after router.push?

**Comment by sorrycc** [comment]
I will build a plugin called umi-plugin-dva to deal with this issue, and other things like automatically load model.

**Comment by sorrycc** [comment]
After umi@1.0 is released.
