### ISSUE TITLE
build map.json

### ISSUE THREAD

**Issue by zinkey** [umijs/umi#520]
whether there is "--hash" or not, there must be a "map.json" for mapping JS files

**Comment by xiaohuoni** [comment]
It is not necessary to configure this option in the development environment because the development environment does not turn on compression, directly debug source. As for the line, there is no need.

**Comment by xiaohuoni** [comment]
这个还是有必要的，特别是需要定位build之后的框架错误。

**Comment by xiaohuoni** [comment]
cross-env COMPRESS=none umi build

**Comment by sorrycc** [comment]
有 manifest 的配置了的。
