### ISSUE TITLE
关于umi的约定式路由

### ISSUE THREAD

**Issue by zxs2162** [umijs/umi#5203]
## What happens?
在开发阶段，约定式路由比较好理解，但是打包后，我的理解是这些约定式路由最终会生成对应的js code被混淆，那在prod模式下是如何找到路由对应的组件或者page呢？

找遍文档，没看到这方面的描述啊。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
我不是很理解你的问题，但是打包之后，也只是将这些代码混淆在一起而已。他们的引用应该依旧是正确的。

**Comment by xiaohuoni** [comment]
约定式路由，只是因为约定式写法自动生成了路由配置文件，和配置式的表现其实是一致的。差别仅在于是否需要显示的写明路由配置。

**Comment by donghero** [comment]
@xiaohuoni 那我可以理解为 “约定式写法”是隐藏路由配置？

**Comment by donghero** [comment]
> 约定式路由，只是因为约定式写法自动生成了路由配置文件，和配置式的表现其实是一致的。差别仅在于是否需要显示的写明路由配置。

@

> 约定式路由，只是因为约定式写法自动生成了路由配置文件，和配置式的表现其实是一致的。差别仅在于是否需要显示的写明路由配置。

@xiaohuoni  那我可以理解为 “约定式写法”是隐藏路由配置？

**Comment by donghero** [comment]
> 约定式路由，只是因为约定式写法自动生成了路由配置文件，和配置式的表现其实是一致的。差别仅在于是否需要显示的写明路由配置。

@xiaohuoni  那我可以理解为 “约定式写法”是隐藏路由配置？
