### ISSUE TITLE
路由上的search字符串，刷新页面后丢失了

### ISSUE THREAD

**Issue by bibiehy** [umijs/umi#5204]
win 10
umi@3.2.14

假如路由是 path: '/server/firewall'，代码如下

" const rotueSearch = qs.stringify({ os: 'linux', servers: [ { id: 1, ip: '' }, { id: 2, ip: '' } ] }); "
" <Link to={{ pathname: '/server/firewall'，search: rotueSearch  }}>防火墙配置<\/Link> "

在 /server/firewall 页面，当刷新页面时候，search 丢失了。

在 app.tsx 下的 onRouteChange 方法内可以看到，search 是存在的，到组件上就丢了

**Comment by xiaohuoni** [comment]
无法重现这个问题，请提供可重现的repo
