### ISSUE TITLE
How to change the Workbox version when build?

### ISSUE THREAD

**Issue by tuphampro** [umijs/umi#5205]
How to change the Workbox version when build?

**Comment by xiaohuoni** [comment]
What is Workbox ？

**Comment by tuphampro** [comment]
![ảnh](https://user-images.githubusercontent.com/19162524/89966878-52b5fa00-dc7a-11ea-9a2b-8d7b1ca0df4c.png)

When the build version of the workbox is always v3.6.3. How to upgrade to v5?

**Comment by xiaohuoni** [comment]
It seems to be your own plug-in logic. umi does not generate this directory by default.

**Comment by tuphampro** [comment]
Because **umi-plugin-react** configures the workbox-webpack-plugin version of v3.6.3.

**Comment by xiaohuoni** [comment]
Where are the relevant documents?

**Comment by tuphampro** [comment]
![ảnh](https://user-images.githubusercontent.com/19162524/90084291-29ab6d00-dd3f-11ea-9e24-e24651a37b0f.png)

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
