### ISSUE TITLE
FAQ: dev/build 卡死、慢、CPU 100% 等问题

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#521]
## 先自行尝试以下方法

> 如果对你有效，请在下面反馈，以帮助更多的人。

### 问题 1

如遇以下问题：

1. 卡好久才启动成功？

通过 `TS_CONFIG_PATHS_PLUGIN=none` 禁用 ts config path plugin 试试，在某些机器上有出现。

### 问题 2

如遇以下问题：

* 启动卡在 91% 或者安装
* import 一个不存在的依赖后 Compiling 卡住一会或好久（和 node_modules 下的模块数有关）

可尝试几个方法：

1. 重装依赖，在 #526 里有尝试修复
2. 换 yarn 试试

### 问题 3

如遇以下问题：

<img src='https://shipusercontent.com/2edb98495330751be1d2c769eca90c6b/Pasted%20Image%202.png' title='Pasted Image 2.png' width=1283>

通过 `HARD_SOURCE=none` 禁用 hard-source-webpack-plugin 。

## 如无效，请回复并提供以下信息

1. 操作系统，win/mac/linux
1. umi 版本
1. 具体问题描述
1. 可重现的库（最好有）

**Comment by wuomzfx** [comment]
1. mac
2. umi@1.3.3
3. 当加载依赖包的路径不对时，就会卡死，爆CPU
4. basement的h5应用模板

**Comment by sorrycc** [comment]
@wuomzfx 试过 `HARD_SOURCE=none` 没？

**Comment by xiaohuoni** [comment]
Windows 启动项目，在getConfig处卡很久，几分钟甚至无响应。
```base
cross-env  HARD_SOURCE=none COMPILE_ON_DEMAND=none MOCK=none umi dev
```
```
af-webpack:getConfig use user's .eslintrc: F:\risk\.eslintrc +0ms
```
开启DEBUG
![_20180530174145](https://user-images.githubusercontent.com/11746742/40712701-e79b5418-6430-11e8-9ba0-53e7cddf2886.png)

无响应的时候，执行umi build，之后再执行umi dev，就会变成等待几分钟启动。

**Comment by sorrycc** [comment]
@xiaohuoni 看问题 1 。
