### ISSUE TITLE
自定义组件无法按照文档描述方式传入参数

### ISSUE THREAD

**Issue by zwh1666258377** [umijs/umi#5210]
<img width="534" alt="WX20200812-153959@2x" src="https://user-images.githubusercontent.com/32405058/89988407-1900e580-dcb2-11ea-84ab-b5cc4d7017e9.png">

**Comment by zwh1666258377** [comment]
请问是我配置方式不正确么

**Comment by zwh1666258377** [comment]
@xiaohuoni @williamnie  求大佬解决

**Comment by zwh1666258377** [comment]
看了插件部分的源码，问题解决了。

但这和你们文档叙述的方式也差太多了。

不过还是感谢大佬开源这么好用的框架，如果文档能清晰一点就更好了

**Comment by xiaohuoni** [comment]
@zwh1666258377 哪个文档有这种写法？

**Comment by zwh1666258377** [comment]
![image](https://user-images.githubusercontent.com/32405058/90084459-f7ead400-dd47-11ea-8104-3a01a0ed977d.png)

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/90122578-11b00980-dd90-11ea-9f40-d37f7bd78550.png)
