### ISSUE TITLE
Patchroutes makes layout and sidebar not visible

### ISSUE THREAD

**Issue by gbaranski** [umijs/umi#5213]
## What happens?

Problem is when I want to dynamicly add route in way like that, it works, but problem is It doesn't show any layout, looks like it changes default settings or something like that
```
export function patchRoutes({ routes }) {
  routes.unshift({
    path: '/foo',
    exact: false,
    name: 'foo',
    component: Device,
  });
}
```

## Mini Showcase Repository(REQUIRED)

https://github.com/gbaranski/Control-Home/tree/move_antd_web/app-web-antd

## How To Reproduce

**Steps to reproduce the behavior:** 
1. Create app from using `yarn create umi myApp` and select v5
2. Add `patchRoutes` function in app.tsx
3. Navigate to `/foo` and layout and sidebar is not visible

**Expected behavior**
1. Create app from using `yarn create umi myApp` and select v5
2. Add `patchRoutes` function in app.tsx
3. Navigate to `/foo` and layout and sidebar are visible

## Context

- **Umi Version**: 3.2.14
- **Node Version**: 12.18.0
- **Platform**: MacOS 10.15.6

**Comment by xiaohuoni** [comment]
你要将它添加到对应布局的数组中，你可以在这里打印一下 routes ，看看你项目中的实际数据结构。
