### ISSUE TITLE
umi 3.x @@/core/umiExports  包报错

### ISSUE THREAD

**Issue by ShichengBegonia** [umijs/umi#5219]
This dependency was not found:

* @@/core/umiExports in ./node_modules/umi/dist/index.esm.js

To install it, you can run: npm install --save @@/core/umiExports

![image](https://user-images.githubusercontent.com/6166544/90104517-ff75a180-dd76-11ea-8625-60a446c96233.png)

**Comment by xiaohuoni** [comment]
尝试以下方法：

1、重启 ide
2、重启 umi dev
3、配置 tsconfig
