### ISSUE TITLE
umi 3添加locale插件,报插件重复注册

### ISSUE THREAD

**Issue by xuesongde** [umijs/umi#5220]
## What happens?

\node_modules\@umijs\core\lib\Service\PluginAPI.js
  81,63:         throw new Error(`api.describe() failed, ${name} ${id} is already registered by ${plugins[id].path}.`);
  registerPlugin(plugin) {
    // 考虑要不要去掉这里的校验逻辑
    // 理论上不会走到这里，因为在 describe 的时候已经做了冲突校验
    if (this.plugins[plugin.id]) {
      const name = plugin.isPreset ? 'preset' : 'plugin';
      throw new Error(`\
${name} ${plugin.id} is already registered by ${this.plugins[plugin.id].path}, \
${name} from ${plugin.path} register failed.`);
    }

    this.plugins[plugin.id] = plugin;
  }

## 相关环境信息

- **Umi 版本**：3.0
- **Node 版本**：>13
- **操作系统**：windows

**Comment by xiaohuoni** [comment]
可能是preset里面已经注册过了，直接使用配置就可以。没必要再引入一次。
