### ISSUE TITLE
Targets 低版本浏览器兼容，如何设置浏览器版本号

### ISSUE THREAD

**Issue by citrusjunoss** [umijs/umi#5224]
## 目前的配置
`
targets: {
    chrome: 37,
    safari: 5,
    firefox: 5,
    ios: 8,
    ie: 8,
    android: 4,
  }
`
### 在上述浏览器上打开空白应该是有些特性不支持，现在看不到报错，如何做兼容。

TBS 调试工具 ，提示不支持。
![image](https://user-images.githubusercontent.com/18432488/90201325-19fa5a00-de0d-11ea-8c5d-eda8cfe2a24e.png)
 
 Vconsole 没有报错信息，

### 1. 此种场景可以兼容，但是会引入重复的polyfill包
``` html
  <script src="https://cdn.bootcss.com/babel-polyfill/6.23.0/polyfill.min.js"></script>
  <script src="https://qzd-web-group-oss.qizhidao.com/wx/cdn/vconsole/vconsole.min.js"></script>
```

## 浏览器UA 信息
![image](https://user-images.githubusercontent.com/18432488/90201127-81fc7080-de0c-11ea-87b4-baffecfe5bdb.png)

## 求助

针对该浏览器如何做兼容？

**Comment by citrusjunoss** [comment]
> 相同的问题 #5428
问题好像不一样吧

**Comment by citrusjunoss** [comment]
> 相同的问题 #5428

好像问题不太一样吧。。。

**Comment by xiaohuoni** [comment]
@citrusjunoss 你觉得有什么不一样呢？我是觉得都是 polyfill 的问题
