### ISSUE TITLE
开发环境约定式路由页面不存在无法跳转404页面

### ISSUE THREAD

**Issue by skyunBoss** [umijs/umi#5227]
## What happens?
开发环境约定式路由页面不存在无法跳转404页面

![image](https://user-images.githubusercontent.com/29365288/90220414-bc7d0200-de3a-11ea-93c3-23ebe5f38327.png)

**Comment by xiaohuoni** [comment]
相同问题 https://github.com/umijs/umi/issues/5092

**Comment by skyunBoss** [comment]
> 相同问题 #5092

不行啊，现在上生产环境也不行
