### ISSUE TITLE
Umi 3.2.0版本无法使用hd:true,怎么做rem适配

### ISSUE THREAD

**Issue by gwl026596** [umijs/umi#5230]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by xiaohuoni** [comment]
装这个插件 [@alitajs/hd](https://www.npmjs.com/package/@alitajs/hd)

**Comment by gwl026596** [comment]
谢谢，可以使用

**Comment by QUCT** [comment]
使用这个插件后 ant mobile组件的字体变小并且很模糊 该怎么处理
