### ISSUE TITLE
I can't upload image with "content-type: multipart/form-data"

### ISSUE THREAD

**Issue by Mai-Tuyen** [umijs/umi#5232]
## What happens?

I have followed document to send a post request with "content-type: multipart/form-data", but it's not working !
const formData = new FormData();
formData.append('file', file);
request('/api/v1/some/api', { method:'post', data: formData });

What wrong ? Thanks for the help !

**Comment by xiaohuoni** [comment]
这个要根据你的服务端设计实现。连调一下就好。umi无关问题。
