### ISSUE TITLE
umijs 3.x + antd 4.x 踩坑记录

### ISSUE THREAD

**Issue by travonf** [umijs/umi#5233]
# 未完待续

**Comment by xiaohuoni** [comment]
> 我这里遇到一个问题就是antd怎么弄都会打包进去，翻看issues说是收到babel-plugin-import影响，
但是我根本没开启antd，不知道为什么还是不行。

默认装了插件就是开了。

**Comment by wangyuan0108** [comment]
rightRender渲染出自己的图片和昵称貌似出不来退出登录按钮，有遇到问题吗？

**Comment by wangyuan0108** [comment]
>antdv4 图标名去除后缀（outlined）并小写，但是我这里需要大写才能生效。
按照这个来配置图标也是不显示的，不知道又出了什么幺蛾子

**Comment by travonf** [comment]
> rightRender渲染出自己的图片和昵称貌似出不来退出登录按钮，有遇到问题吗？

理论上来说GlobalHeader应该交由用户通过rightRender控制的，谁知道某个版本是不是自动注入了登录注销功能

**Comment by travonf** [comment]
> > antdv4 图标名去除后缀（outlined）并小写，但是我这里需要大写才能生效。
> 
> 按照这个来配置图标也是不显示的，不知道又出了什么幺蛾子

这块感觉不稳定，试试icon: <CloudOutlined />这样的方式配置，不然就等稳定了再玩。

**Comment by travonf** [comment]
> > 我这里遇到一个问题就是antd怎么弄都会打包进去，翻看issues说是收到babel-plugin-import影响，
> > 但是我根本没开启antd，不知道为什么还是不行。
> 
> 默认装了插件就是开了。

这个文档上不是说config里配置了才开启么？ 或者提供antd: boolean支持手动关闭也可以啊，现在来看还不行。

**Comment by victorWuxz** [comment]
ErrorComponent不起作用呢

**Comment by victorWuxz** [comment]
layout的 onError和ErrorComponent不起作用

**Comment by zhangyu1818** [comment]
之前ant design pro4的时候layout是一个组件，我在menuDataRender里可以通过后台数据过滤，现在返回的是一个对象，不知道怎么操作了

**Comment by wy5211** [comment]
手动在 layouts 里面引入 pro-layout， config 里面的 layout 为 false，然后将路由通过 menuDataRender 配置在 pro-layout 上，路由重定向不生效，有人遇到过吗

**Comment by ykmind** [comment]
我碰到了个问题, umi3中配置redux-persist, 想数据持久化, 但是仅仅初始化的时候再调试工具中能看到, 自己的action刷新页面后 数据仍然丢失, 请问有人碰到过嘛?

**Comment by wxf-start** [comment]
> 我碰到了个问题, umi3中配置redux-persist, 想数据持久化, 但是仅仅初始化的时候再调试工具中能看到, 自己的action刷新页面后 数据仍然丢失, 请问有人碰到过嘛?

请问你解决了吗~~~
