### ISSUE TITLE
umi2.x的config.js修改target没有效果

### ISSUE THREAD

**Issue by bjwulin** [umijs/umi#5235]
## What happens?

用electron+umijs2.x做项目，因为renderer端要引用第三方的nodejs api，因此需要将webpack的target设置为：electron-renderer，代码如下：

export default {
  chainWebpack(config, { webpack }) {
    config.target('electron-renderer');
  },
  history: 'hash',
  outputPath: `../../dist/renderer`,
  publicPath: './',
  ...
}

但是没有效果，如果用create-react-app，设置target:electron-renderer,则没有问题。

- **Umi Version**:2.8.16
- **Node Version**:v11.13.0
- **Platform**:mac

**Comment by gjfei** [comment]
你好，解决了嘛？
