### ISSUE TITLE
源代码中文被编码

### ISSUE THREAD

**Issue by skyunBoss** [umijs/umi#5236]
## What happens?
![image](https://user-images.githubusercontent.com/29365288/90303606-e50c0700-dee1-11ea-8425-e4f07001827c.png)

## 最小可复现仓库
yarn create umi demo

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
右击【显示网页源代码】

## 相关环境信息

- **Umi 版本**：v3.2.14
- **Node 版本**：v12.18.3
- **操作系统**：mac

**Comment by sukechris** [comment]
I have the same problem!

**Comment by skyunBoss** [comment]
@sorrycc 这是3.0的优化吗？
