### ISSUE TITLE
使用proxy时报错

### ISSUE THREAD

**Issue by FAOfao931013** [umijs/umi#5240]
我是在 ant-design-pro 项目中使用的 umi 的 proxy
我修改了我的代理地址，但是一请求就报错，报错如下

`/node_modules/@umijs/preset-built-in/node_modules/@umijs/server/lib/Server/Server.js:314`
`const realUrl = ((_URL = new URL(req.url || '', target)) === null || _URL === void 0 ? void 0 : _URL.href) || '';`
`ReferenceError: URL is not defined`

实在不知道哪里出问题了

**Comment by AliasT** [comment]
Node版本太低。

**Comment by FAOfao931013** [comment]
> Node版本太低。

原来如此，切到node 10就好了，感谢大佬~
