### ISSUE TITLE
通过chainWebpack注册antd-dayjs-webpack-plugin， 替换Moment.js不起作用

### ISSUE THREAD

**Issue by H-Sven** [umijs/umi#5246]
## What happens?
```
import AntdDayjsWebpackPlugin from 'antd-dayjs-webpack-plugin'


chainWebpack(memo, { env, webpack, createCSSRule }) {
    //  使用day.js替换moment.js
    memo.plugin('AntdDayjsWebpackPlugin').use(AntdDayjsWebpackPlugin)
  }
```

这样使用插件用dayjs替换moment.js 没有用

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xu-Aurora** [comment]
我也没有起效果，请问解决了嘛？

**Comment by xu-Aurora** [comment]
![image](https://user-images.githubusercontent.com/35291465/126441763-93660b47-c691-457b-b233-c48f5a7b0e3f.png)
设置默认值的时候我是直接编译不过，直接报错

**Comment by xiaohuoni** [comment]
这个plugin是在构建的时候替换的，你在项目中应该直接使用moment而不是 dayjs

**Comment by xu-Aurora** [comment]
> 这个plugin是在构建的时候替换的，你在项目中应该直接使用moment而不是 dayjs

直接使用moment？那不是还要重新下载moment了，项目都下载moment了，那不是有起到项目体积变小的效果了嘛，毕竟moment都下载到项目上了

**Comment by williamnie** [comment]
> > 这个plugin是在构建的时候替换的，你在项目中应该直接使用moment而不是 dayjs
> 
> 直接使用moment？那不是还要重新下载moment了，项目都下载moment了，那不是有起到项目体积变小的效果了嘛，毕竟moment都下载到项目上了

不是啊，下载了很多包，并不会都打进去啊，webpack有tree-shaking会排除一些无用的包，在构建的时候动态的把moment替换成dayjs，moment就不会在被打进去了，如果不信可以启动ANALYZE=1 umi build，进入analyze模式下分析一下包的组成你就知道了

**Comment by xu-Aurora** [comment]
> > > 这个plugin是在构建的时候替换的，你在项目中应该直接使用moment而不是 dayjs
> > 
> > 
> > 直接使用moment？那不是还要重新下载moment了，项目都下载moment了，那不是有起到项目体积变小的效果了嘛，毕竟moment都下载到项目上了
> 
> 不是啊，下载了很多包，并不会都打进去啊，webpack有tree-shaking会排除一些无用的包，在构建的时候动态的把moment替换成dayjs，moment就不会在被打进去了，如果不信可以启动ANALYZE=1 umi build，进入analyze模式下分析一下包的组成你就知道了

好的，谢谢

**Comment by xrjj** [comment]
@williamnie ANALYZE之后还有moment包，目前是装了moment,dayjs，然后设置了config.plugin('antd-dayjs-webpack-plugin').use(AntdDayjsWebpackPlugin);
