### ISSUE TITLE
Link能够通过js来调用吗? 或者提供onBefore方法.

### ISSUE THREAD

**Issue by l745230** [umijs/umi#5247]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

## Additional context

需求:
<Link onBefore={()=>{ // do somethine   }} to={`${url}?${stringify(data)}`}>
       <Button> 
            {title}
          </Button>
      </Link>

在link 跳转url之前调用方法. 或者在Button onClick中手动调用link

类似
import router from 'umi/router'; 
router.push('/list');

**Comment by leftstick** [comment]
你要的是 `history.push` 么？ 看文档[history](https://umijs.org/api#history)

**Comment by l745230** [comment]
@leftstick 
history满足不了.

配置了
base: '/admin/',
publicPath: '/admin/',

列表页访问地址
http://localhost:8000/admin/#/admin/list
新窗口打开详情页
http://localhost:8000/admin/#/admin/detail

Link 可以配置target="_blank" 从而新窗口打开.
<Link target="_blank" to="/detail">

而window.open 还得手动拼接上/admin
window.open('/admin/detail')

找了好久文档,才找到Link. 但是现在有个需求,要在跳转前处理一些东西.Link又不够用了.

**Comment by leftstick** [comment]
好像真没有这功能，自己把`window.open` 封装以下也蛮好的

```ts
function openNewTab(path: string) {
  // @ts-ignore
  window.open(`${window.routerBase}${path.replace(/^\//g, '')}`)
}
```

**Comment by l745230** [comment]
@leftstick 
emmmm,自己封装个openNewTab也能实现,但是还是想偷懒下.... 如果Link官方能支持下onBefore是最好的了
