### ISSUE TITLE
devtool设置成false，打包后部署到线上环境报错

### ISSUE THREAD

**Issue by H-Sven** [umijs/umi#5249]
## What happens?

```
devtool: false,
```
在.umirc.ts中设置devtool: false，打包部署到线上后，在较低版本浏览器下报错 包括最新版360浏览器，内核是78
![9beb289ed18851941229166e815bffe](https://user-images.githubusercontent.com/26042365/90509631-36d7ba00-e18c-11ea-985c-6225fefca144.png)

![b982e5d36424d924befd4767ddd262a](https://user-images.githubusercontent.com/26042365/90511772-92f00d80-e18f-11ea-9efc-1fb8fbdc516b.png)

设置成devtool: 'eval', 就没这个问题， 但是这样会导致打包的代码非常大

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by H-Sven** [comment]
已经定位到原因， 是开启了esbuild导致的

```
esbuild: {},
devtool: false,
```
当开启了esbuild，并且devtool设置为false的时候，yarn build后，发布到线上环境，在最新版360浏览器下打开网页，就会出现上面说到的问题

这应该是一个bug，望修复


新建一个空项目，并配置上面2个属性，就能复现

**Comment by sorrycc** [comment]
已修复。
