### ISSUE TITLE
菜单的图标实际使用配置和文档描述差别太大，按文档使用icon显示不出来

### ISSUE THREAD

**Issue by wangyuan0108** [umijs/umi#5253]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

```jsx
routes: [
    {
      name: 'home',
      path: '/',
      component: '@/pages/index',
      icon: 'github',
      name: '首页'
    },
    {
      name: 'test',
      path: '/test',
      component: '@/pages/test',
      name: '仪表板',
      icon: 'github',
    },
  ],
```
这样配置才会显示出icon，如果放到menu下面配置，显示的只是字符串。

## 相关环境信息

- **Umi 版本**：3.2.3
- **Node 版本**：10.16.0
- **操作系统**：macOS

**Comment by leftstick** [comment]
最新版的`@umijs/plugin-layout` 应该这两种写法都支持的把

**Comment by wangyuan0108** [comment]
> 最新版的`@umijs/plugin-layout` 应该这两种写法都支持的把

我写在menu下面，菜单不显示图标。我不放到menu下面就显示出来了

**Comment by wangyuan0108** [comment]
![image](https://user-images.githubusercontent.com/22407253/90607574-faf82f80-e233-11ea-8296-253832dae9e0.png)
第一个是放到menu下面的配置未显示，第二个是直接配置的显示出来了

**Comment by wangyuan0108** [comment]
> 最新版的`@umijs/plugin-layout`应该这两种写法都支持的把

如上图

**Comment by leftstick** [comment]
所以你确定你的`@umijs/plugin-layout` 已经升级到最新的`0.11.15`了，然后这个问题依旧存在？如果是，提供可复现demo

**Comment by wangyuan0108** [comment]
@leftstick 好的，我看下，更新试试

**Comment by wangyuan0108** [comment]
新的0.11.15是没问题的，只看到了安装的包，没在意内置的包
