### ISSUE TITLE
Dynamic expressions for import() are broken

### ISSUE THREAD

**Issue by justable** [umijs/umi#5256]
## What happens?

import()无法加载动态表达式的模块

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

https://github.com/tingyur/dynamic-import-broken/blob/master/src/pages/index.tsx

## How To Reproduce

**Steps to reproduce the behavior:** 

我希望动态加载非组件资源，

```tsx
let id = 1
import(`./${id}.html`) // 提示Cannot find module './1.html'
import('./1.html') // work fine
```
terminal警告：Critical dependency: the request of a dependency is an expression

**Expected behavior** 

我查看了[webpack文档](https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import)是可以使用表达式的啊，不知道是否umi对import()做了额外处理？

## Context

- **Umi Version**:^3.2.14
- **Node Version**:v14.7.0
- **Platform**:Win10

**Comment by leftstick** [comment]
这个功能webpack 直上是没问题的。我猜 umi 应该是用了某些babel插件导致了问题。 不过这个得稍后仔细检查下了。

**Comment by wzxm** [comment]
请问这个问题解决了吗？我也碰到了同样的问题，webpack直上是OK的，用 umi 就不行。

**Comment by aixfox** [comment]
这个似乎是 webpack 的问题不是 umi 的，umi 仓库里没有发现有 callExpression 且 callee 为 Import 的 visitor。

复现的仓库我试了一下异步加载就好了（不知道为什么）
```
dynamicImport: {},
```

**Comment by kanyuan** [comment]
貌似是 @babel/preset-env 的modules设置有问题

**Comment by qqjay2017** [comment]
- 1. `.umirc.ts`开启`dynamicImport`

```
 dynamicImport: {
    loading: '@/components/LoadingCp',
  },
```

- 2.  import 函数里面的变量需要用字符串和变量模板拼接的形式,不能全部是变量

```
import(`xx/${path}`)
```

**Comment by sorrycc** [comment]
Config dynamicImport or [dynamicImportSyntax](https://umijs.org/config#dynamicimportsyntax) if you don't want route code splitting.

**Comment by shaoyi52** [comment]
@sorrycc 你这个问题就没解决怎么就闭关了
