### ISSUE TITLE
关于在umi中配置额外的loader启动报错问题

### ISSUE THREAD

**Issue by overcastsky** [umijs/umi#5257]
## What happens?
项目中需要需要配置额外的loader，来解析文件，按照官方文档中的FAQ中的指引，在.umirc.js中配置
  urlLoaderExcludes: [/.mp4$/],
  chainWebpack(config) {
    config.module.rule('mp4')
      .test(/.mp4$/)
      .use('url-loader')
      .loader('url-loader')
  }
启动会报错,报错信息如下
Invalid config key urlLoaderExcludes，
在umi官方配置文档中也并没有发现有urlLoaderExcludes配置项

## 相关环境信息

- **Umi 版本**：3.0.16
- **Node 版本**：10.15.0
- **操作系统**：MacOS

**Comment by yxrgds** [comment]
> ## What happens?
> 项目中需要需要配置额外的loader，来解析文件，按照官方文档中的FAQ中的指引，在.umirc.js中配置
> urlLoaderExcludes: [/.mp4$/],
> chainWebpack(config) {
> config.module.rule('mp4')
> .test(/.mp4$/)
> .use('url-loader')
> .loader('url-loader')
> }
> 启动会报错,报错信息如下
> Invalid config key urlLoaderExcludes，
> 在umi官方配置文档中也并没有发现有urlLoaderExcludes配置项
> 
> ## 相关环境信息
> * **Umi 版本**：3.0.16
> * **Node 版本**：10.15.0
> * **操作系统**：MacOS

请问怎么解决的

**Comment by overcastsky** [comment]
> > ## What happens?
> > 项目中需要需要配置额外的loader，来解析文件，按照官方文档中的FAQ中的指引，在.umirc.js中配置
> > urlLoaderExcludes: [/.mp4$/],
> > chainWebpack(config) {
> > config.module.rule('mp4')
> > .test(/.mp4$/)
> > .use('url-loader')
> > .loader('url-loader')
> > }
> > 启动会报错,报错信息如下
> > Invalid config key urlLoaderExcludes，
> > 在umi官方配置文档中也并没有发现有urlLoaderExcludes配置项
> > ## 相关环境信息
> > 
> > * **Umi 版本**：3.0.16
> > * **Node 版本**：10.15.0
> > * **操作系统**：MacOS
> 
> 请问怎么解决的
chainWebpack: (config) => {
config.module
.rule('url-loader')
.test(/\.(mp4 | mp3)$/)
.use('url-loader')
.loader('url-loader')
}
