### ISSUE TITLE
[Feature Request] ssr模式下，styles、scripts、headScripts等外部资源的配置在manifest中添加映射

### ISSUE THREAD

**Issue by feehc** [umijs/umi#5258]
## Background

egg搭建ssr，需要使用模板时，外部资源未在manifest中进行映射，无法在模板中通过helper.assets.getStyle获取

## Proposal

styles、scripts、headScripts等配置支持key-value的配置形式，例如：

```
{
  styles: process.env.NODE_ENV === 'development'
    ? [
        { 'antd.css': 'https://cdn.jsdelivr.net/npm/antd@4.5.3/dist/antd.css'' },
      ]
    : [
        { 'antd.css': 'https://cdn.jsdelivr.net/npm/antd@4.5.3/dist/antd.min.css'' },
      ],
}
```

然后在生成manifest时直接生成相应的映射配置

**Comment by ycjcl868** [comment]
`helper.assets.getStyle` 只用来获取本地的 style 资源（如 css），直接写在 egg 的 view html 里
