### ISSUE TITLE
BUG: the link is invalid, got 404 error. 

### ISSUE THREAD

**Issue by OhIAmFine** [umijs/umi#5265]
## What happens?

 when I clicked the link in the plugin-locale page, the redirected page was invalid. pls fix this link.

![image](https://user-images.githubusercontent.com/10390004/90847844-0b2c1e00-e39e-11ea-936f-73795a878ff5.png)
![image](https://user-images.githubusercontent.com/10390004/90847867-14b58600-e39e-11ea-8ceb-ad34fa533cfc.png)

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.

**Comment by OhIAmFine** [comment]
@sorrycc  so do you mean this feature will no longer being supported or other meaning ?(by the way, i am a fan of you, used to join your offline sharing).

**Comment by sorrycc** [comment]
which feature?
