### ISSUE TITLE
Cannot invoke an object which is possibly 'undefined'.

### ISSUE THREAD

**Issue by CreazyJack** [umijs/umi#5268]
## What happens?
At pages/ListTableList/index.tsx,there are a error at 183 line <FooterToolBar>......<Button onClick={async () => {...... **_actionRef.current?.reloadAndRest()_**}}></Button></FooterToolBar>

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

https://github.com/CreazyJack?tab=repositories
## How To Reproduce
use the latest umi ,antdpro5 and vscode,then open the file
**Steps to reproduce the behavior:** 1. 2.
use the latest umi ,antdpro5 and vscode,then open the file
**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.2.0
- **Node Version**:  12.6.1
- **Platform**: win10 1909

**Comment by xiaohuoni** [comment]
@CreazyJack 复现仓库链接不可用
