### ISSUE TITLE
How to update snapshot?

### ISSUE THREAD

**Issue by AmethystCat** [umijs/umi#527]
Does the umi has the update snapshot option?

**Comment by sorrycc** [comment]
snapshot for what? umi test?

**Comment by AmethystCat** [comment]
I use umi-test script to do unit test for react components in my project, but I didn't find a command similar to ‘jest --updateSnapshot’ when I wanna update the snapshot sometimes 😀。

**Comment by mutouzdl** [comment]
I have the same question, how to use a [CLI Option](https://facebook.github.io/jest/docs/en/cli.html#options) like [jest --updateSnapshot] in umi test?
