### ISSUE TITLE
How to fix one React Helmet issue with SSR (Umi3)

### ISSUE THREAD

**Issue by shlomitsur** [umijs/umi#5271]
Hello everybody!

Just wanted to share a problem I had with Helmet & SSR, maybe it can be of help to someone:
Everything was looking ok with the plugin and the server rendering and still not meta/title was rendered.
After a while I found that this was the culprit:

In my layout there was are a 'loader' spinner showing until the model was loaded.
That prevented the page from being loaded in the server and the Helmet to load its values.
After I changed to this the problem was solved:

```
`     {isBrowser() && !isReady ? (
        <div>
          <Spin />
        </div>
      ) : (
        <Layout>
          ...
         </Layout>
      )}
```

**Comment by xiaohuoni** [comment]
thk！
