### ISSUE TITLE
umi.server 找不到问题

### ISSUE THREAD

**Issue by supwjm** [umijs/umi#5273]
https://github.com/umijs/umi/blob/master/examples/ssr-koa/server.js
这文件里，这句const render = require('./dist/umi.server') 的写法在开发模式下有问题。由于package.json是先运行node server.js 的，初始化项目或者删除dist之后，这文件./dist/umi.server不存在，会导致报错，必须先运行一次build

**Comment by williamnie** [comment]
require的时候加个try吧，如果提前build，dev的时候可能会无法覆盖umi.server文件，但是如果放到方法里面去require，又会在dev模式下oom，这块暂时还没想好怎么弄
