### ISSUE TITLE
在使用配置路由时能否使用默认布局，以及单条路由的 layout 属性

### ISSUE THREAD

**Issue by leadream** [umijs/umi#5274]
## What happens?

我想实现以下路由效果：
```bash
# 以下路由使用默认布局（`layouts/index`）
/
/login
# 以下路由使用 Dashboard 布局（`layouts/dashboard`）
/dashboard
/meeting
```

我按照下面的路由配置写的，没有达到效果

```js
export default defineConfig({
  routes: [
    { path: '/', component: '@/pages/home' },
    { path: '/login', component: '@/pages/login' },
    {
      path: '/',
      component: '@/layouts/dashboard',
      wrappers: [
        '@/wrappers/Auth',
      ],
      routes: [
        { path: '/dashboard', component: '@/pages/dashboard' },
        { path: '/meeting', component: '@/pages/meeting' },
      ],
    },
  ],
});
```

不知道是我写的方式不对还是目前还不支持默认布局。如果不支持的话，希望可以支持一下，像 `/` 和 `login` 这种可以默认使用 `layouts/index`。或者增加一个 layout 属性，能够给单条路由指定布局方式，比如 `{ path: '/login', layout: '@/layouts/index', component: '@/pages/login' }`。

谢谢！

**Comment by MinatoHikari** [comment]
官方文档写法：
export default {
  routes: [
    { path: '/login', component: 'login' },
    {
      path: '/',
      component: '@/layouts/index',
      routes: [
        { path: '/list', component: 'list' },
        { path: '/admin', component: 'admin' },
      ],
    }, 
  ],
}
这样就可以在下面的路由里用layout











你以为这样写能行吗？
答案是不行，按官方文档写不行
export default {
  routes: [
    { path: '/login', component: 'login' },
    {
      path: '/*',
      component: '@/layouts/index',
      routes: [
        { path: '/list', component: 'list' },
        { path: '/admin', component: 'admin' },
      ],
    }, 
  ],
}
要这么写，嘻嘻，没想到吧

**Comment by leadream** [comment]
@MinatoHikari 感谢，好多坑啊。

**Comment by sorrycc** [comment]
1. `/` 和 `/*` 是一样的，有 child routes 时 exact 为 false，做模糊匹配
2. @MinatoHikari 的方法应该解不了前面的问题， @leadream 是解了吗？
3. 推荐的做法是做 `layouts/index.js` 判断 props.location.url，分别引不同的 layout 渲染

**Comment by MinatoHikari** [comment]
> 1. `/` 和 `/*` 是一样的，有 child routes 时 exact 为 false，做模糊匹配
> 2. @MinatoHikari 的方法应该解不了前面的问题， @leadream 是解了吗？
> 3. 推荐的做法是做 `layouts/index.js` 里判断 `props.location.url`，分别引不同的 layout 渲染

我自己试了
```
routes: [
    { path: '/', exact: true, redirect: '/home' },
    {
      path: '/',
      component: '@/layouts/index',
      routes: [
        { path: '/home', component: '@/pages/index' },
        { path: '/category', component: '@/pages/category' },
      ],
    },
  ],
```
当routes下只有这一个配置时，必须将母层级的path设置为"/*"加不加exact倒是无所谓
如果path不加这个星号子层级全部无法渲染
```
routes: [
    { path: '/', exact: true, redirect: '/home' },
    {
      path: '/',
      component: '@/layouts/index',
      routes: [
        { path: '/home', component: '@/pages/index' },
        { path: '/category', component: '@/pages/category' },
      ],
    },
  ],
```
只有当存在另一个平行的母层级时数组第二个元素的path写"/"而不是"/*"才能正确渲染
不知道这个到底时有意为之还是文档的疏漏还是bug

**Comment by leadream** [comment]
@sorrycc 尝试了，确实不行。

我是这样写的：

```js

  routes: [
    {
      path: '/*',
      component: '@/layouts',
      routes: [
        { path: '/', component: '@/pages/index' },
        { path: '/login', component: '@/pages/login' }
      ]
    },
    {
      path: '/*',
      component: '@/layouts/dashboard',
      wrappers: ['@/wrappers/auth'],
      routes: [
        {
          path: '/welcome',
          component: '@/pages/welcome',
        },
        {
          path: '/settings',
          component: '@/pages/settings',
        }
      ],
    },
  ],
```

看起来在 routes 数组中第一个元素内匹配不到就不会往后找了。新的 [React Router V6](https://reacttraining.com/blog/react-router-v6-pre/#nested-routes-and-layouts) 是支持的，不知道到时候 UMI 是不是可以考虑支持一下。

![image](https://user-images.githubusercontent.com/12868055/91554104-0e587880-e961-11ea-8fa4-f78d86a8aa2d.png)

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
