### ISSUE TITLE
关于 配置.copy 的问题

### ISSUE THREAD

**Issue by block-sexy** [umijs/umi#5277]
## What happens?
文件 .umirc.ts 的 copy 命令，以前 都支持 form/to 用的挺好的，后来改为了 只允许 string；
那么问题来了：
加入需求是：把文件夹 /src/resource 复制到 /dist , 根据帮助文档，应该写：
copy: [
    './src/resource',  // 尝试了 './src/resource/' 效果一样
  ],
但是，无论是 npm run start，还是 npm run build，复制过得的文件夹，丢了 resource ,会把里面的子文件全部复制到根目录；
难道我 需要文件：/dist/resource/* 我需要搞一个  /src/resource/resource 才可以？？？

 
## 相关环境信息

- **Umi 版本**： "umi": "^3.2.16",
- **Node 版本**：node 12
- **操作系统**： mac

**Comment by xlszzck** [comment]
遇到同样的问题`
  copy: [{ 
    from: '../../admin_new/static/index.html', 
    to: '../../admin_new/index.html' 
  }],`
在config.ts这样配置无效

**Comment by block-sexy** [comment]
> 遇到同样的问题` copy: [{ from: '../../admin_new/static/index.html', to: '../../admin_new/index.html' }],`
> 在config.ts这样配置无效

散了吧，umi3 就不允许制定了，原因未知；

感觉略坑
