### ISSUE TITLE
Location 和 useLocation的query 缺少 ts 声明类型

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#5278]
如图
![image](https://user-images.githubusercontent.com/7939085/91000837-ade1d800-e5fc-11ea-8bcd-fba5269231d5.png)

![image](https://user-images.githubusercontent.com/7939085/91000844-b0dcc880-e5fc-11ea-97b4-df0cf454bdf9.png)

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by xiaohuoni** [comment]
看了一下代码，应该是已经修复了。https://github.com/umijs/umi/commit/94f47a9039889244a95119056751d5bd1422d37c
你可以更新一下你的umi版本

**Comment by xiexingen** [comment]
![image](https://user-images.githubusercontent.com/7939085/93552802-12961580-f9a4-11ea-866e-d74d9c742919.png)
奇怪了
"@umijs/preset-react": "^1.6.6",
"umi": "^3.2.20"

**Comment by xiaohuoni** [comment]
@xiexingen 给个例子看下

**Comment by leftstick** [comment]
@xiaohuoni  @xiexingen  之前那个修复只对 page component 的 props 里的location 有效。

直接用  `useLocation` ，或者 `history.location` 得到的对象，仍然没有 `query` 定义。

之前我印象 @sorrycc  似乎提过这个地方有潜在问题，所以一直没修复。不确定那个疑问现在是否依旧存在。但`query` 定义应该确实还没有加

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/4268#issuecomment-616908652

**Comment by alvin0216** [comment]
```ts
const location = useLocation()
location.query // 类型“Location”上不存在属性“query”。
```
实际上是有的 ，但是类型声明就没有，请问各位如何解决的 ^3.3.2
@xiexingen

**Comment by xiexingen** [comment]
> ```ts
> const location = useLocation()
> location.query // 类型“Location”上不存在属性“query”。
> ```
> 
> 实际上是有的 ，但是类型声明就没有，请问各位如何解决的 ^3.3.2
> @xiexingen

官方暂时还没处理，改动比较大；我目前是用location['query']这种形式来暂时解决的

**Comment by alvin0216** [comment]
> > ```ts
> > const location = useLocation()
> > location.query // 类型“Location”上不存在属性“query”。
> > ```
> > 
> > 
> > 实际上是有的 ，但是类型声明就没有，请问各位如何解决的 ^3.3.2
> > @xiexingen
> 
> 官方暂时还没处理，改动比较大；我目前是用location['query']这种形式来暂时解决的

谢回，我是通过 [react-router query-paramters](https://reactrouter.com/web/example/query-parameters) 去解决的

代码：

```ts
export default function useSearchParams(): URLSearchParams {
  return new URLSearchParams(useLocation().search);
}
```

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.

**Comment by mastercbhw** [comment]
This problem still exists

**Comment by LiuJinYang9527** [comment]
该问题仍然存在

**Comment by lhzbxx** [comment]
这个问题没有计划解决吗？

**Comment by varfate** [comment]
我是重新定义了一次
- use-real-location.ts
```ts
import * as H from 'history';
import { parse, ParsedQuery } from 'query-string';
import { useLocation } from 'umi';

const useRealLocation = <Q extends ParsedQuery<string>>() => {
  const location = useLocation<undefined>() as H.Location<undefined> & { query: Q };
  const query = location.query || parse(location.search);

  return { ...location, query };
};

export default useRealLocation;
```

**Comment by lhzbxx** [comment]
> 我是重新定义了一次
> 
> * use-real-location.ts
> 
> ```ts
> import * as H from 'history';
> import { parse, ParsedQuery } from 'query-string';
> import { useLocation } from 'umi';
> 
> const useRealLocation = <Q extends ParsedQuery<string>>() => {
>   const location = useLocation<undefined>() as H.Location<undefined> & { query: Q };
>   const query = location.query || parse(location.search);
> 
>   return { ...location, query };
> };
> 
> export default useRealLocation;
> ```

我目前是直接用了 [@ahooksjs/use-url-state](https://www.npmjs.com/package/@ahooksjs/use-url-state)。

**Comment by hengkx** [comment]
@sorrycc @xiaohuoni 问题依然 没有解决

**Comment by LeleCao** [comment]
@sorrycc @xiaohuoni  该问题依然存在，你们家应用没有路由吗。 // @ts_nocheck

**Comment by littlee** [comment]
👀  问题依然 没有解决

**Comment by xiaohuoni** [comment]
现在这里提交了修改，不知道会不会合并。https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53693

**Comment by bruceeewong** [comment]
试试自定义hook + any 大法🤪

```ts
import { useLocation } from "umi";
export default  function useQuery(): Record<string,string> {
  const location: any = useLocation();
  return location.query;
}
```

**Comment by fengjiahao** [comment]
same problem for my project

**Comment by cl1107** [comment]
> 试试自定义hook + any 大法🤪
> 
> ```ts
> import { useLocation } from "umi";
> export default  function useQuery(): Record<string,string> {
>   const location: any = useLocation();
>   return location.query;
> }
> ```
```typescript
import { useLocation } from 'umi';
import type { Location } from 'umi';

export const useLocationQuery = <T extends Record<string, string>>() => {
  const location = useLocation() as Location & { query: T };
  return location.query;
};
```

**Comment by linxianxi** [comment]
+1。好像是 @types/history 的问题？

**Comment by cloudy-boyuan** [comment]
> +1。好像是 @types/history 的问题？

手动添加声明
```typescript
import { Location } from 'history';

declare module 'History' {
  interface Location{
    query: Record<string,string>;
  }
}
```

**Comment by linxianxi** [comment]
> > +1。好像是 @types/history 的问题？
> 
> 手动添加声明
> 
> ```ts
> import { Location } from 'history';
> 
> declare module 'History' {
>   interface Location{
>     query: Record<string,string>;
>   }
> }
> ```

没用

**Comment by Liu-Ya** [comment]
```ts
import type { Location } from 'history';
const location = useLocation() as Location & { query: { from?: string } };
```

**Comment by zchhaenngg** [comment]
import type { Location } from 'history';

export default withRouter(({ history, location, match }) => {
    const newlocation = location as Location & { query: { tag?: string } };
    const { tag } = newlocation.query;

**Comment by bobbychan** [comment]
```js
  import type { Location } from 'umi';
  const location: Location = useLocation();
```

**Comment by Pszz** [comment]
> ```js
>   import type { Location } from 'umi';
>   const location: Location = useLocation();
> ```

and
import type { Location } from 'umi';
const { query } = history.location as Location;

**Comment by HuangZurong** [comment]
const location = useLocation();
    const query = (location as any).query;
