### ISSUE TITLE
启用layout的情况下，antd的table sticky属性不生效

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#5280]
安装最新的antd 
使用table的sticky属性，让表头吸顶  发现如果使用了@umijs/preset-react并且启用了layout的情况下 antd的table吸顶效果没了
禁用layout的情况 可以正常使用

特地建了一个issue仓库
https://github.com/xiexingen/antd-table-issue

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：
"umi": "^3.2.16",
 "@umijs/preset-react": "^1.5.22",
"@ant-design/pro-layout": "^6.4.9",
"antd": "^4.6.1",

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
