### ISSUE TITLE
提交的 PR 卡在了 test 阶段

### ISSUE THREAD

**Issue by zhanyuzhang** [umijs/umi#5282]
提交的 PR ，卡在了 test 阶段，已经 8 分钟还没有跑完，是不是测试用例有问题？
![image](https://user-images.githubusercontent.com/12018876/91044562-10ac9100-e648-11ea-8bab-b69baaceeef1.png)

**Comment by sorrycc** [comment]
node 8 的先不管了，node 最低需要 10。
