### ISSUE TITLE
dynamic 配置  相关

### ISSUE THREAD

**Issue by kokiy** [umijs/umi#5285]
hello, 我现在不想让这个项目基于路由懒加载,只想一些依赖大的第三方库懒加载分割一下,现在在umi3+ 里,我配置了dynamic 后 就全部基于路由分割了 . 如果不启用 dynamic  单独使用 react.lazy 和 react-loadable 也不行 ,

**Comment by sorrycc** [comment]
不想基于路由懒加载的考虑是啥？

**Comment by kokiy** [comment]
@sorrycc  基于路由分割之后  有的文件只有几k, 通过网络请求 得不偿失吧 , 只是希望大的包含第三方库组件分割一下

**Comment by sorrycc** [comment]
cdn 是 http/2 的话，文件数量就没有影响了。

**Comment by urielvan** [comment]
@kokiy 

用 chainWebpack 修改一下配置

```ts
   memo.module.rule('js')
      .use('babel-loader')
      .get('options')
      .presets[0][1].dynamicImportNode = false;
```

因为我没加别的 babel 的 preset，所以我这边看到 `.presets` 的结果就一项，如果你有加别的 preset 的话，用 `console.log` 确认下 `babel-preset-umi` 的索引位置然后改下下标就好了。

改完之后就可以用 `memo.optimization.splitChunks` 配置具体分拆的需求了
