### ISSUE TITLE
dynamic加载函数组件，无法得到组件对外提供的方法

### ISSUE THREAD

**Issue by robinv8** [umijs/umi#5287]
## What happens?

使用 dynamic 动态加载函数组件，函数组件使用了forwardRef 后无法得到组件内部方法

## Context

- **Umi Version**: v3.2.10
- **Node Version**: v12.18.3
- **Platform**: macos

**Comment by xiaohuoni** [comment]
@leftstick cc,xixi

**Comment by leftstick** [comment]
@robinv8  给个可复现repo?

**Comment by robinv8** [comment]
@leftstick 稍等，我写一个。

**Comment by leftstick** [comment]
@robinv8 难受了，真的是 `dynamic` 的问题，她把导出的组件做了额外的封装，而且并没有把 `ref` 透传到动态导入的组件上。

这个我还得想想该怎么解，为今之计，你只能workaround一下了：


index.tsx

```tsx
import React, { useRef } from 'react';
import styles from './index.less';
import Com1 from './dynamic';

export default () => {
  const ref1 = useRef();

  const onClick = () => {
    console.log(ref1);
  };
  return (
    <div>
      <h1 className={styles.title}>Page index</h1>
      <Com1 onRefReady={r => {
        ref1.current = r
      }}></Com1>
      <button onClick={onClick}>确定</button>
    </div>
  );
};
```

component1.tsx

```tsx
import React, { useImperativeHandle, useRef, useEffect } from 'react';

const Index = ({onRefReady}) => {

  const ref = useRef({})

  useImperativeHandle(ref, () => ({
    getValue: () => {
      return 'umi';
    },
  }));


  useEffect(() => {
    onRefReady && onRefReady(ref.current)
  }, [])

  return <div>组件</div>;
};

export default Index;
```

**Comment by robinv8** [comment]
@leftstick 还能这样玩，学到了。

**Comment by Johnbug** [comment]
> @robinv8 难受了，真的是 `dynamic` 的问题，她把导出的组件做了额外的封装，而且并没有把 `ref` 透传到动态导入的组件上。
> 
> 这个我还得想想该怎么解，为今之计，你只能workaround一下了：
> 
> index.tsx
> 
> ```tsx
> import React, { useRef } from 'react';
> import styles from './index.less';
> import Com1 from './dynamic';
> 
> export default () => {
>   const ref1 = useRef();
> 
>   const onClick = () => {
>     console.log(ref1);
>   };
>   return (
>     <div>
>       <h1 className={styles.title}>Page index</h1>
>       <Com1 onRefReady={r => {
>         ref1.current = r
>       }}></Com1>
>       <button onClick={onClick}>确定</button>
>     </div>
>   );
> };
> ```
> 
> component1.tsx
> 
> ```tsx
> import React, { useImperativeHandle, useRef, useEffect } from 'react';
> 
> const Index = ({onRefReady}) => {
> 
>   const ref = useRef({})
> 
>   useImperativeHandle(ref, () => ({
>     getValue: () => {
>       return 'umi';
>     },
>   }));
> 
> 
>   useEffect(() => {
>     onRefReady && onRefReady(ref.current)
>   }, [])
> 
>   return <div>组件</div>;
> };
> 
> export default Index;
> ```

这种方式也workaround不来啊。你这还是返回静态的数据，返回动态的数据就不行了吧
