### ISSUE TITLE
......\dva.ts: Identifier  'Modelmodel' has already been declared

### ISSUE THREAD

**Issue by RememberHearts** [umijs/umi#5291]
umi-dva 识别出来的Model路径和文件名可能存在问题。

我的 model 直接以 model.js 命名，每个 model 里都有 namespace，且每个 namespace 都不同。
但是 dva.ts 里 import 的 model 都是以 Modelmodel 命名，而不是 Model[namespace] 命名

- **Umi Version：3.2.16**:
- **Node Version：14.8.0**:
- **Platform：Windows 10**:

**Comment by RememberHearts** [comment]
原因：dva 和 umi-dva 冲突，删除原来的 dva 依赖即可

**Comment by RememberHearts** [comment]
删除了原来的 dva 依赖后，虽然 node 不报错，但是实际 app.model({ namespace: 'model', ...ModelModel61 }); 里的 namespace 还是有问题。。。

**Comment by sorrycc** [comment]
有啥问题？`ModelModel61` 是 import 自你的 model，里面的 namespace 会覆盖外面的  model 的 namespace。

**Comment by RememberHearts** [comment]
> 有啥问题？`ModelModel61` 是 import 自你的 model，里面的 namespace 会覆盖外面的 model 的 namespace。

直接以model命名model文件时，即使model文件里有namespace，但得到的结果里，namespace 还是没有与 model 里的 namespace 一致，就像下面这样：
app.model({ namespace: 'model', ...ModelModel45 });
app.model({ namespace: 'model', ...ModelModel46 });
app.model({ namespace: 'model', ...ModelModel47 });
app.model({ namespace: 'model', ...ModelModel48 });
app.model({ namespace: 'model', ...ModelModel49 });
app.model({ namespace: 'model', ...ModelModel50 });
app.model({ namespace: 'model', ...ModelModel51 });
app.model({ namespace: 'model', ...ModelModel52 });
app.model({ namespace: 'model', ...ModelModel53 });
app.model({ namespace: 'model', ...ModelModel54 });
app.model({ namespace: 'model', ...ModelModel55 });
app.model({ namespace: 'model', ...ModelModel56 });
app.model({ namespace: 'model', ...ModelModel57 });
app.model({ namespace: 'model', ...ModelModel58 });
app.model({ namespace: 'model', ...ModelModel59 });
app.model({ namespace: 'model', ...ModelModel60 });
app.model({ namespace: 'model', ...ModelModel61 });
app.model({ namespace: 'model', ...ModelModel62 });
app.model({ namespace: 'model', ...ModelModel63 });
app.model({ namespace: 'model', ...ModelModel64 });
app.model({ namespace: 'model', ...ModelModel65 });

**Comment by sorrycc** [comment]
给个简单复现吧，没理解。

**Comment by RememberHearts** [comment]
简单复现的一个 demo：`https://github.com/RememberHearts/antd-pro-test.git`
主要描述：我在 `./src/pages/User` 和 `./src/pages/Account` 下分别新建了一个 model，这两个 model 有不同的 namespace。但是 ./src/.umi/plugin-dva/plugin-dva.ts 中关于这两个 model 的处理结果如下：

> import ModelModel4 from 'XXX/antd-pro-test/src/pages/Account/model.js';
import ModelModel5 from 'XXX/antd-pro-test/src/pages/Users/model.js';
......
app.model({ namespace: 'model', ...ModelModel4 });
app.model({ namespace: 'model', ...ModelModel5 });

**Comment by xiaohuoni** [comment]
@RememberHearts 给个小 demo 吧
