### ISSUE TITLE
devScripts 报错 Antd Form

### ISSUE THREAD

**Issue by RememberHearts** [umijs/umi#5292]
#5131  What happens?
我先升级了 antd@4，使用 umi2 可以正确运行且无报错。
今天升级了 umi3，devScripts 报了以下 Warning 且终止了程序运行：
Warning: [antd: Form] antd v4 removed `Form.create`. Please remove or use `@ant-design/compatible` instead.
项目中所有 Form 均已替换成 `@ant-design/compatible` Form

- **Umi 版本**：3.2.16
- **Node 版本**：14.8.0
- **操作系统**：Windows 10

**Comment by sorrycc** [comment]
给复现步骤。

**Comment by RememberHearts** [comment]
> 给复现步骤。

1. 在 umi2 下使用 `@ant-design/compatible Form` 实现一个表单
2. 启动无报错
3. 将 umi2 升级到 umi3，再次启动，报错`Warning: [antd: Form] antd v4 removed Form.create. Please remove or use @ant-design/compatible instead.`，且程序终止运行

**Comment by hyzx86** [comment]
请问下，这莫名其妙直接关Issue 是什么操作
是问题太小儿科还是 压根实现不了，给句话也行啊
