### ISSUE TITLE
升级umi3.2.16后，antdesign ProV5 所有页面都会报404错误

### ISSUE THREAD

**Issue by vVvlife** [umijs/umi#5293]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
1.从3.2.13版本开始使用npm升级
2.出现404页面无法找到错误
**Expected behavior** 1. 2.
升级成功，正常使用
## Context
![image](https://user-images.githubusercontent.com/20148964/91162125-414f0200-e6fe-11ea-915b-6964a1c015ce.png)
升级umi3.2.16后，antdesign ProV5 怎么都会报404错误

- **Umi Version**:  3.2.16
- **Node Version**: 12.18.3
- **Platform**:Linux

**Comment by sorrycc** [comment]
复现步骤？

**Comment by vVvlife** [comment]
> 复现步骤？

就是直接npm install umi更新后就出现这个问题了，后面直接回滚为3.2.13版本又没有问题了

**Comment by vVvlife** [comment]
@sorrycc 一开始的版本为3.2.13，直接升级为3.2.15及以上的版本都会出现路由一直找不到，跳到404的情况，升到3.2.14还是可以正常运行的。

**Comment by sorrycc** [comment]
给可复现的仓库，不然没法排查。这个问题也没有其他人反馈。

**Comment by vVvlife** [comment]
> 给可复现的仓库，不然没法排查。这个问题也没有其他人反馈。

这个是公司内部项目，属于本地化的仓库，一些config配置文件可以贴上，我也是最近升上了才发现这个问题

**Comment by sorrycc** [comment]
自己抽象下问题，整个最小复现的仓库。

**Comment by vVvlife** [comment]
> 自己抽象下问题，整个最小复现的仓库。

估计是依赖包出现了一些问题，我重新用umi搭建过一次环境并没有出现这个问题

**Comment by lichangchao15442** [comment]
我也遇到了这个问题，升级前umi版本为3.2.3，直接yarn add umi 升级到了3.2.22后项目所有页面都报404页面找不到。

**Comment by vVvlife** [comment]
> 我也遇到了这个问题，升级前umi版本为3.2.3，直接yarn add umi 升级到了3.2.22后项目所有页面都报404页面找不到。

大概率是依赖的问题，后面用了新版的umi再搭建新环境，迁移src部分过去，就解决了
