### ISSUE TITLE
Typed hints are missing in Redux-like effects, just type any

### ISSUE THREAD

**Issue by ace-han** [umijs/umi#5298]
## What happens?

In ant-design-pro@V4 `@/models/user.ts`, there is no typed hints in effects invocation even if I have defined `queryUsers(): Promise<CurrentUser> => (...)`

If we could make it definitely typed is much better.

```typescript
// @/service/user.ts
import requestService from '@/utils/request';
import { CurrentUser } from '@/models/user';

export async function query(): Promise<CurrentUser[]> {
  return requestService.get<CurrentUser[]>('/api/users');
}

```
```typescript
// @/models/user.ts
// ... 
  effects: {
    *fetch(_, { call, put }) {
      const response = yield call(queryUsers); // <!-- no typed hints for response as it is any
      yield put({
        type: 'save',
        payload: response,
      });
    },
// ...
}
```

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

![image](https://user-images.githubusercontent.com/1177332/91284029-f5fc2880-e7bd-11ea-80ab-deb898e71c41.png)

![image](https://user-images.githubusercontent.com/1177332/91284064-03191780-e7be-11ea-9421-4fcb9d918137.png)

## How To Reproduce

**Steps to reproduce the behavior:** 
1. yarn create umi demo
2. modify these above two files as instructed

**Expected behavior** 
Typed hints popup as below. 
![image](https://user-images.githubusercontent.com/1177332/91284494-8b97b800-e7be-11ea-8626-c0030e222a72.png)
That's the work around I could come up with for the time being. Or please make it as template for future reference
```
const response: T = yield call(someFunc);
```

## Context

- **Umi Version**: "^3.2.14"
- **Node Version**: 12.16.1
- **Platform**: macOs 10.15.6

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if still have problems.
