### ISSUE TITLE
开发环境下chrome@50控制台报错，无法热更新

### ISSUE THREAD

**Issue by okilled** [umijs/umi#5299]
## What happens?
使用脚手架创建项目后，在开发环境下chrome@50控制台报错，无法热更新

<img width="1005" alt="图片" src="https://user-images.githubusercontent.com/23131376/91285343-b1718c80-e7bf-11ea-9ffe-7b64b13ce58d.png">
<img width="1031" alt="图片" src="https://user-images.githubusercontent.com/23131376/91285366-b8989a80-e7bf-11ea-94be-3fe1ff2890a1.png">

## 最小可复现仓库

> https://github.com/okilled/umi

## 复现步骤，错误日志以及相关配置
1. yarn create @umijs/umi-app
2. yarn
3. yarn start
4. 打开chrome@50

## 相关环境信息

- **Umi 版本**：3.2.17
- **Node 版本**：10.19.0
- **操作系统**：win7
- **chrome 版本**：50.0.2661.94 (64-bit)

**Comment by xiaohuoni** [comment]
建议你升级开发浏览器。umi 只有在 build 的时候才会添加对应浏览器补丁。
