### ISSUE TITLE
history.push 页面空白，再刷新就能正常显示页面

### ISSUE THREAD

**Issue by skyunBoss** [umijs/umi#5301]
## What happens?

开发环境无问题，生产环境history.push（Link是路由变了，页面没有变） 页面空白，再刷新就能正常显示页面
config配置了base

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

在登录回调方法使用history.push('/')，页面会空白，再刷新就正常显示

## 相关环境信息

- **Umi 版本**：v3.2.16
- **Node 版本**：v12.18.3
- **操作系统**：mac

**Comment by skyunBoss** [comment]
> ## What happens?
> 开发环境无问题，生产环境history.push 页面空白，再刷新就能正常显示页面
> config配置了base
> 
> ## 最小可复现仓库
> > 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库
> 
> ## 复现步骤，错误日志以及相关配置
> 在登录回调方法使用history.push('/')，页面会空白，再刷新就正常显示
> 
> ## 相关环境信息
> * **Umi 版本**：v3.2.16
> * **Node 版本**：v12.18.3
> * **操作系统**：mac

@sorrycc 这是是问题吗？

**Comment by xiaohuoni** [comment]
给个小 demo 吧

**Comment by skyunBoss** [comment]
config配置文件有点问题

**Comment by Limsanity** [comment]
[这里](https://github.com/Limsanity/umi-router-repro)给出了一个路由跳转失败的 demo。
出现的问题大概如下：
- 从`@/.umi/core/history` 中导入 `history`，在开发环境中路由跳转正常，build 构建后则跳转失败；
- 从 `umi` 中导入 `history` 则可以修复这个问题。

[可分别打开第一第二行注释](https://github.com/Limsanity/umi-router-repro/blob/master/src/pages/index.tsx#L2)，分别进行构建进行测试。

**Comment by xiaohuoni** [comment]
why import from  '@/.umi/core/history';?

**Comment by Limsanity** [comment]
> why import from '@/.umi/core/history';?

ide 自动补全会出现多个选项，没留意就会从 `@/.umi/core/history` 中导入，开发环境表现正常导致困惑。

**Comment by xiaohuoni** [comment]
build 的时候不是走 /.umi/ 目录的
