### ISSUE TITLE
process.env return undefined

### ISSUE THREAD

**Issue by mahmutduva** [umijs/umi#5303]
## process.env return undefined

I use Ant Design Pro v4.  After update umi version,  env variables are returned undefined.

## Context
- **Ant Design Pro:** 4
- **Umi Version:** 3.2.17
- **Node Version:** 2.16.1

**Comment by mahmutduva** [comment]
@xiaohuoni When will you solve this problem?

**Comment by DanielFromTAFE** [comment]
I have the same issue. Any help with this would be appreciated @xiaohuoni

**Comment by xiaohuoni** [comment]
How to reproduce it?

**Comment by mahmutduva** [comment]
@sorrycc how to reproduce it?

**Comment by mahmutduva** [comment]
@sorrycc  I defined variables in .env file. But i cant reach these variables in js after update umijs.
`REACT_APP_API=https://blabla.com`

**Comment by mohaphez** [comment]
@sorrycc , 

I Have Same Problem . 
How can get .env file variables with process.env ?

**Comment by mahmutduva** [comment]
@mohaphez @DanielFromTAFE @xiaohuoni use UMI_APP prefix instead of REACT_APP for env vars. I used that and worked!

For Example: REACT_APP_API   ---- > UMI_APP_API

**Comment by sorrycc** [comment]
If you want to use REACT_APP_API, set the `define` in config file.

```
export default {
  define: {
    'process.env.REACT_APP_API': process.env.REACT_APP_API,
  }
}
```
