### ISSUE TITLE
umi-plugin-react/locale 切换菲律宾语有bug

### ISSUE THREAD

**Issue by zyqq** [umijs/umi#5305]
umi-plugin-react/locale 切换菲律宾语切换不过来，经查看源码是检测语言的正则过滤掉了fil-PH，如下：
![29c3e002c89f973e0b17bd0548b6317](https://user-images.githubusercontent.com/15664576/91421423-830bb400-e888-11ea-8b74-a345a6a4c311.png)
![image](https://user-images.githubusercontent.com/15664576/91421515-9a4aa180-e888-11ea-8540-fbb22b499f3e.png)
正确的应该是
![image](https://user-images.githubusercontent.com/15664576/91421601-b2babc00-e888-11ea-93de-8d8dc364a476.png)

![image](https://user-images.githubusercontent.com/15664576/91421574-ab93ae00-e888-11ea-887f-95c5cf531ddc.png)

## 相关环境信息

- **Umi 版本**：^2.10.7
- **Node 版本**：v10.12.0
- **操作系统**：windows10 x64

**Comment by hello-lun** [comment]
我切换阿拉伯语的时候，会导致antd的css样式错乱，看了element节点是加上了一些class导致的
