### ISSUE TITLE
使用 dynamic 时，进行动态 import 会报错：Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by wzxm** [umijs/umi#5306]
#### 动态组件使用：
![image](https://user-images.githubusercontent.com/13127730/91441333-9deb2200-e8a2-11ea-9c4d-526abb740a2f.png)

#### 配置源码，直接 import 一个常量，则正常显示组件：

![image](https://user-images.githubusercontent.com/13127730/91440998-08e82900-e8a2-11ea-9fd3-7d9d8c1044df.png)

![image](https://user-images.githubusercontent.com/13127730/91441087-3339e680-e8a2-11ea-8a8d-4570fbc30b0a.png)

#### 配置源码，当 import 地址为一个变量时，则无法正常加载：

![image](https://user-images.githubusercontent.com/13127730/91441410-bb1ff080-e8a2-11ea-9858-3c1c2c2b69ea.png)

![image](https://user-images.githubusercontent.com/13127730/91441261-75fbbe80-e8a2-11ea-9e36-34eb1921542a.png)

**Comment by xiaohuoni** [comment]
@leftstick 帮忙看下什么意思，thk！

**Comment by leftstick** [comment]
貌似和 https://github.com/umijs/umi/issues/5256，是同一个原因引起的，似乎某个插件对 `import(...)` 语法做了处理，但处理的不正确。

为今之计，动态 import 时，不要用变量就没事。

root cause 待查

**Comment by wzxm** [comment]
也只能先不用变量了

**Comment by wzxm** [comment]
> 貌似和 [#5256](https://github.com/umijs/umi/issues/5256)，是同一个原因引起的，似乎某个插件对 `import(...)` 语法做了处理，但处理的不正确。
> 
> 为今之计，动态 import 时，不要用变量就没事。
> 
> root cause 待查

我这么修改配置之后，可以实现 import(...)可以使用变量了，但是有一点，路径不能使用 "@/xx/xx"，需要 "../../components/xx/xx"
![image](https://user-images.githubusercontent.com/13127730/92193062-fe2d2580-ee99-11ea-8508-1cc9d34544f8.png)

**Comment by xiaohuoni** [comment]
相同问题 https://github.com/umijs/umi/issues/5256
