### ISSUE TITLE
语法错误被修复之后没有热加载

### ISSUE THREAD

**Issue by eevin** [umijs/umi#5307]
在劫持children渲染，由于某个组件代码错误后，修改代码后页面不能显示正常显示。

在umi@3.2.3中会抛错误信息Unhandled Rejection (Error): Module build failed (from ./node_modules/babel-loader/lib/index.js):

在umi@3.2.16中返回空白页面。

```
const Basic: FC<BasicProps> = (props) => {
  const { location, children } = props;
  const { pathname, query } = location;

  const [childrens, setChildrens] = useState(null);

  // history model change
  useEffect(() => {
    setChildrens(children);
  }, [pathname, query]);

  return <>{childrens}</>;
};

export default Basic;
```

**Comment by xiaohuoni** [comment]
是指语法错误被修复之后没有热加载的问题吗？

**Comment by eevin** [comment]
是的。
版本从版本2开始这么用，一直没有问题。
3+以上就不行了。

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if you still have problems.
