### ISSUE TITLE
如何在dva model中使用hook model?

### ISSUE THREAD

**Issue by mjkohoh** [umijs/umi#5308]
我之前的一些代码使用的是`dva model`，现在又使用了`@umijs/plugin-initial-state`，需要在原先的`dva model`中修改`initialState`。我在`dva model`中调用`useModel('@@initialState')`，运行报错`Invalid hook call`。请问有解决方案吗？

**Comment by xiaohuoni** [comment]
useHooks 的方法不能在组件之外调用。你可以在初始化数据的时候，调用 dva 的 dispatch 来设置 model 的 state

**Comment by mjkohoh** [comment]
是啊，我也发现了。可是`ant-design/pro-components`中，大量的代码是`dva model`。而`plugin-initial-state`，`plugin-access`都使用的是`hook model`。已有项目中也大量使用了`dva model`。如果不能在`dva model`中修改`hook model`中的数据，非常的让人头疼，感觉不美好。诶。

**Comment by mjkohoh** [comment]
没有人和我一样，遇到相似的问题吗？

**Comment by lei-cao** [comment]
遇到同样的问题。

**Comment by wangyuan0108** [comment]
要在函数组件中调用hook吧

**Comment by wulinjie122** [comment]
我想知道怎么能在Component里，拿到initialState，我用的是redux的connect方法，想在组件初始化时，拿到全局的initialState,作为组件的props

**Comment by wulinjie122** [comment]
```javascript
export default connect(({product, image, tag, initialState, loading}) => ({
  product,
  image,
  tag,
  initialState,
  loading
}))(ProductEdit);
`

**Comment by wulinjie122** [comment]
因为我不是函数组件，而是class组件，没办法使用hook useModel，所有有没有别的办法可以拿到initialState

**Comment by mjkohoh** [comment]
@wulinjie122 ，在你的Component外面再套一层函数组件，获取initialState后，将其作为props传给你的Component。

**Comment by mjkohoh** [comment]
哈哈哈，笑死我了。

**Comment by sunyum** [comment]
单个插件都是好插件，放在一块就成了一滩水

**Comment by thk-liu** [comment]
用的Component 系统配置都在initialState 取不到一取就报错 头疼

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if you still have problems.

**Comment by wongzzh** [comment]
有解决方案吗
