### ISSUE TITLE
Bug Failed to load parser '@typescript-eslint/parser' declared in '--config 

### ISSUE THREAD

**Issue by hihuangwei** [umijs/umi#5311]
## What happens?

Error: Failed to load parser '@typescript-eslint/parser' declared in '--config » D:\Web\console\node_modules\@umijs\fabric\dist\eslint.js » eslint-config-airbnb-typescript » D:\Web\console\node_modules\@umijs\fabric\node_modules\eslint-config-airbnb-typescript\lib\shared.js': Cannot find module 'typescript'

## Context

- **Umi Version**: 3.2.18
- **Node Version**: 14.8.0
- **Platform**: eslint 7.7.0

**Comment by xiaohuoni** [comment]
How to reproduce？

**Comment by hihuangwei** [comment]
@xiaohuoni https://github.com/ant-design/ant-design-pro/issues/7267

**Comment by DAHU123** [comment]
How to solve this question？please help me！
