### ISSUE TITLE
获取路由的path作为model的namespace，如何依据模板model动态生成页面的model

### ISSUE THREAD

**Issue by AntHuiZi** [umijs/umi#5312]
我们的需求是所有的页面通过后台管理配置的，根据登陆时返回的菜单的参数请求对应页面的json数据进行渲染，因为所有的页面都相似，只是数据不同，登陆时获取菜单，然后根据页面的path作为动态生成页面的model，但是不知道该如何做？

**Comment by xiaohuoni** [comment]
不是太理解你的描述，不过感觉使用 app.model 动态注册应该可行？或者你们的数据都在服务端的 json 里面，有必要使用 dva 吗？
