### ISSUE TITLE
现在umi3 没有hd啦，怎么处理？？？

### ISSUE THREAD

**Issue by sanshuiwang** [umijs/umi#5317]
@xwjune 开启hd，有这个功能

_Originally posted by @xiaohuoni in https://github.com/umijs/umi/issues/1691#issuecomment-449329499_

现在umi3 没有hd啦，怎么处理？？？

**Comment by xiaohuoni** [comment]
用它 https://www.npmjs.com/package/@alitajs/hd

**Comment by sanshuiwang** [comment]
> 用它 https://www.npmjs.com/package/@alitajs/hd

多谢！
