### ISSUE TITLE
请问如何进行回调拦截?

### ISSUE THREAD

**Issue by laolaolulu** [umijs/umi#5321]
oidc登录验证成功后会调用回调页面导致整个antdpro页面刷新了,请问怎么拦截这个回调来实现局部刷新呢

**Comment by xiaohuoni** [comment]
不回调怎么验证？然后这问题与 umi 无关。你可以查查 oidc 的资料。

**Comment by laolaolulu** [comment]
> 不可以怎么验证？然后这问题与umi无关。你可以查查oidc的资料。

第三方身份验证系统都是回调验证的,但umi的应用属于单页应用利用回调验证页面跳转验证就导致整个页面重新加载了一次,我实在找不到好的解决方案了才到这里来提问的不好意思

**Comment by xiaohuoni** [comment]
我的印象中，应该是都有重新加载一次。你可以找个没有加载的例子（如果能找到的话），看看他们怎么做的。
