### ISSUE TITLE
umi.js 中 .eslintrc.js 的 'react-hooks/exhaustive-deps': 'error' 该配置项不起作用

### ISSUE THREAD

**Issue by WebEngineerLi** [umijs/umi#5324]
## What happens?

umi.js 项目中配置了 在 `.eslintrc.js `文件中配置了  `react-hooks/exhaustive-deps': 'error'` 但是该规则没有起作用。
`.eslintrc.js` 中
![image](https://user-images.githubusercontent.com/30517805/91663424-4e635b00-eb1b-11ea-997e-e8c3191ad1f4.png)
实际结果
![image](https://user-images.githubusercontent.com/30517805/91663522-f24d0680-eb1b-11ea-961e-d63d98b33da9.png)

## Context

- **Umi Version**:
3.2.0
- **Node Version**:
11.12.0
- **Platform**:
Mac OS 10.15.5

**Comment by dongxiaoyong009** [comment]
+1 同问

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if you still have problems.

**Comment by Simoon-F** [comment]
+1

**Comment by AprildreamMI** [comment]
请问有解决方法吗？看他的lint源码，就[已经引用了react-hooks](https://github.com/umijs/umi/blob/master/packages/lint/src/config/eslint/index.ts#L8)，并且[添加了相应规则](https://github.com/umijs/umi/blob/master/packages/lint/src/config/eslint/rules/recommended.ts#L67),不知道为什么还是无法产生报错
