### ISSUE TITLE
打包出来的图片文件不需要hash文件名，如何设置？

### ISSUE THREAD

**Issue by Fntys** [umijs/umi#5325]
![image](https://user-images.githubusercontent.com/13896710/91676724-59e27080-eb73-11ea-9bf3-acc8345110d1.png)

![image](https://user-images.githubusercontent.com/13896710/91676750-6d8dd700-eb73-11ea-90aa-1bf5a44a155f.png)

**Comment by zoeygo** [comment]
![umi配置](https://user-images.githubusercontent.com/47884189/100565171-f0066e00-32fd-11eb-951e-97c5ae5764e8.jpg)
在umi配置文件添加这个配置项，打包出来的图片就不会带hash后缀了。如果是.js之类的文件不想带hash后缀，添加hash配置项（参考下图）
![umi文件配置](https://user-images.githubusercontent.com/47884189/100565312-3cea4480-32fe-11eb-93ac-bb296b8c44e2.jpg)

**Comment by ycjcl868** [comment]
> ![umi配置](https://user-images.githubusercontent.com/47884189/100565171-f0066e00-32fd-11eb-951e-97c5ae5764e8.jpg)
> 在umi配置文件添加这个配置项，打包出来的图片就不会带hash后缀了。如果是.js之类的文件不想带hash后缀，添加hash配置项（参考下图）
> ![umi文件配置](https://user-images.githubusercontent.com/47884189/100565312-3cea4480-32fe-11eb-93ac-bb296b8c44e2.jpg)

文档来个 PR？

**Comment by zoeygo** [comment]
提交了一个请求，然而我不确定我这波操作对不对。如果带来麻烦提前道歉了 @ycjcl868

**Comment by sorrycc** [comment]
只能统一配 hash: false，不能为图片单独配置。
