### ISSUE TITLE
多个路由指向同一个实体页面，页面根据json配置显示不同组件，该如何做？

### ISSUE THREAD

**Issue by AntHuiZi** [umijs/umi#5328]
我目前的业务是几十个页面都结构，只有部分区别。
所以需求是通过后台管理页面配置生成不同的页面的json。
目前我得实验是所有的路由都指向了一个实体的页面组件，然后根据接口返回的json来动态配置出不同的页面子组件，当页面切换时，保存路由的pathname作为不同页面区分，同时一个model内部有多个子对象对应不同的页面，如下图：
![截屏2020-08-31 下午6 00 31](https://user-images.githubusercontent.com/18253873/91708438-e6ad1e80-ebb3-11ea-81a2-1b315802e24c.png)
在页面UNSAFE_componentWillMount里初始化对应页面的model
*initPageState(_, { put, select }) {
      let { quoteMaintenance } = yield select(({ quoteMaintenance }) => ({
        quoteMaintenance: quoteMaintenance,
      }));
      if (!quoteMaintenance.hasOwnProperty(getPathname())) {
        yield put({
          type: 'updateState',
          payload: initalState
        });
      }
但是在切换页面时，页面上的数据没有切换成对应的model里的数据，
请问我该如何实现。

**Comment by chinacoolboyzz** [comment]
建议了解下 [https://github.com/umijs/sula](url)

**Comment by lspeer** [comment]
解决了么？菜单有什么好的配置方法么？

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if you still have problems.
