### ISSUE TITLE
warning "export 'useIntl' was not found in 'umi'

### ISSUE THREAD

**Issue by mengfei0053** [umijs/umi#5330]
# warning "export 'useIntl' was not found in 'umi'
![image](https://user-images.githubusercontent.com/20025631/91824376-3d2a6380-ec6d-11ea-9815-94213030c902.png)

## Mini Showcase Repository(REQUIRED)

https://github.com/mengfei0053/umi-type-bug

## How To Reproduce

```
# step1 
 yarn create @umijs/umi-app

# step2 
# .umirc.ts
import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  layout: {}, # 开启layout
  routes: [{ path: '/', component: '@/pages/index' }],
});

```

## Context

- **Umi Version**:umi@3.2.19
- **Node Version**:v12.18.1
- **Platform**: wsl-ubuntu

**Comment by leftstick** [comment]
你就没开启 `locale` 配置啊。如下：

```ts
import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  locale: {}, // 这条，你没加啊
  layout: {},
  routes: [{ path: '/', component: '@/pages/index' }],
});

```

**Comment by mengfei0053** [comment]
我不想开locale啊，我只要layout啊

**Comment by mengfei0053** [comment]
官网给出的配置中，layout，并没有强制绑定locale。
![image](https://user-images.githubusercontent.com/20025631/91829535-2cc9b700-ec74-11ea-86a6-bfd0d4d7a914.png)

**Comment by mengfei0053** [comment]
![image](https://user-images.githubusercontent.com/20025631/91829765-76b29d00-ec74-11ea-9693-927141a1d562.png)
![image](https://user-images.githubusercontent.com/20025631/91829813-8336f580-ec74-11ea-8895-a72e760810f5.png)

**Comment by thisAries** [comment]
我也遇到这个问题了。新手小白刚搭建项目，发现这个waring，然后用umi ui加载的模板列表，访问列表时报错。`./src/.umi/plugin-layout/layout/utils/intl.ts:25` 原因好像是`import { useIntl, getLocale } from 'umi';` umi没有导出这两个模块。完完整整按照文档来的，好心塞啊，堵一天了。

**Comment by thisAries** [comment]
建议写入文档内。新手小白按照文档做，出现了这个问题

**Comment by Gyang18** [comment]
哇，第一次用这个按照文档做真是。。。。

**Comment by twoKilo** [comment]
> 哇，第一次用这个按照文档做真是。。。。

真的是
