### ISSUE TITLE
开启动态加载时，会加载非本页面的模块

### ISSUE THREAD

**Issue by htank-wang** [umijs/umi#5331]
## What happens?
https://preview.pro.ant.design/profile/advanced
打开高级详情页，查看network会有account__settings的资源加载进来，是什么原因？
如果是正常的依赖加载，是不是有歧义，并且请求数变多了？

## 相关环境信息

![image](https://user-images.githubusercontent.com/17918845/91828013-34885c00-ec72-11ea-8720-12104b7fa0f6.png)

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by leftstick** [comment]
说明 account settting 和 profile 两个页面里有共用的内容，被提取到这个文件里了。

**Comment by htank-wang** [comment]
提取的策略是，方便发个文档地址么？
