### ISSUE TITLE
官网给出的配置中，layout，并没有强制绑定locale。

### ISSUE THREAD

**Issue by mengfei0053** [umijs/umi#5332]
官网给出的配置中，layout，并没有强制绑定locale。
![image](https://user-images.githubusercontent.com/20025631/91829535-2cc9b700-ec74-11ea-86a6-bfd0d4d7a914.png)

_Originally posted by @mengfei0053 in https://github.com/umijs/umi/issues/5330#issuecomment-684609516_

**Comment by wangyuan0108** [comment]
是的啊

**Comment by simplast** [comment]
不用不行吗，不用会出现一堆warning

**Comment by okilled** [comment]
一样的问题

**Comment by sorrycc** [comment]
已修复。
