### ISSUE TITLE
page connect model 时出现 undefined 的问题

### ISSUE THREAD

**Issue by nbbjack** [umijs/umi#5334]
## 首先、app创建是使用命令  `yarn create @umijs/umi-app`

Config 主要配置
```
history: {
    type: 'hash',
  },
  hash: true,
  layout: {
    name: 'backend',
    locale: true,
  },
  antd: {
    dark: false,
    compact: false,
  },
  theme: {
    'primary-color': '#30a679',
  },
  dynamicImport: {
    loading: '@/component/PageLoading/index',
  },
  dva: {
    immer: true,
    hmr: true, 
  },
```

看到这里你会说没有注册啊、没有开始dva之类的，那么，请继续看...

## 相关代码截图
model 写法
![QQ截图20200901204934](https://user-images.githubusercontent.com/7787811/91854144-dff6d800-ec95-11ea-99b0-9634c5c49084.png)
page 的代码
![QQ截图20200901204822](https://user-images.githubusercontent.com/7787811/91854141-df5e4180-ec95-11ea-9346-b98e5335c3a2.png)
console.log
![QQ截图20200901204746](https://user-images.githubusercontent.com/7787811/91854137-dd947e00-ec95-11ea-9721-dbda9a174a50.png)
![QQ截图20200901210915](https://user-images.githubusercontent.com/7787811/91855204-6fe95180-ec97-11ea-9e68-8250a0362e43.png)

到底是bug还是我写错了，还是有bug呢？

model的写法和user一样的，如上图，userInfo就能正常取出数据。

![QQ截图20200901210338](https://user-images.githubusercontent.com/7787811/91854669-a7a3c980-ec96-11ea-9c91-a1ac317fef95.png)

最后，src/.umi 目录下自动生成的文件
![QQ截图20200901205233](https://user-images.githubusercontent.com/7787811/91854148-e1280500-ec95-11ea-8154-656a5085bf11.png)
![QQ截图20200901205249](https://user-images.githubusercontent.com/7787811/91854152-e1c09b80-ec95-11ea-8695-e34c554177ae.png)

**Comment by aixfox** [comment]
connect() 的参数里不是应该是 online 吗，并没有 onlineData 这个 model 吧。

`connect(({ online }) => ({ onlineData: online.data  }))`
