### ISSUE TITLE
只想用layout，不用locale。warning "export 'useIntl' was not found in 'umi' 

### ISSUE THREAD

**Issue by mengfei0053** [umijs/umi#5343]
# warning "export 'useIntl' was not found in 'umi' 。（只想使用layout，不想开locale，locale:false）
![image](https://user-images.githubusercontent.com/20025631/91824376-3d2a6380-ec6d-11ea-9815-94213030c902.png)

## Mini Showcase Repository(REQUIRED)

https://github.com/mengfei0053/umi-type-bug

## How To Reproduce

```
# step1 
 yarn create @umijs/umi-app

# step2 
# .umirc.ts
import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  layout: {}, # 开启layout
  routes: [{ path: '/', component: '@/pages/index' }],
});

```

## Context

- **Umi Version**:umi@3.2.19
- **Node Version**:v12.18.1
- **Platform**: wsl-ubuntu

https://github.com/umijs/umi/issues/5330#issuecomment-684584509

**Comment by victorWuxz** [comment]
一样的问题

**Comment by okilled** [comment]
一样的问题

**Comment by RepSklvska** [comment]
一样的问题

**Comment by wangyuan0108** [comment]
不开也没事吧

**Comment by mengfei0053** [comment]
有修复的准备么

**Comment by xiaohuoni** [comment]
相同issues
