### ISSUE TITLE
AssertionError: Invalid key dva from plugin  有没有人遇到过

### ISSUE THREAD

**Issue by bushuizaijian** [umijs/umi#5344]
- [ ] 
![image](https://user-images.githubusercontent.com/40242973/91966820-f445de00-ed44-11ea-9082-9fe1230e85c1.png)

**Comment by leftstick** [comment]
你的配置文件，和package.json里的依赖列表贴一下。你给的这个玩意没啥用

**Comment by bushuizaijian** [comment]
> 你的配置文件，和package.json里的依赖列表贴一下。你给的这个玩意没啥用

![企业微信截图_15991052107616](https://user-images.githubusercontent.com/40242973/92069540-340bd480-eddc-11ea-947e-4844e0f16f28.png)
![image](https://user-images.githubusercontent.com/40242973/92069587-41c15a00-eddc-11ea-9ddb-da966100ed9a.png)

**Comment by blueju** [comment]
> > 你的配置文件，和package.json里的依赖列表贴一下。你给的这个玩意没啥用
> 
> ![企业微信截图_15991052107616](https://user-images.githubusercontent.com/40242973/92069540-340bd480-eddc-11ea-947e-4844e0f16f28.png)
> ![image](https://user-images.githubusercontent.com/40242973/92069587-41c15a00-eddc-11ea-9ddb-da966100ed9a.png)

你只贴了 package.json 的依赖和开发依赖，配置文件没贴呢？

**Comment by blueju** [comment]
我遇到过一个可能类似的问题，已经解决，应该是 dva 插件没装的问题。

https://www.yuque.com/blueju/umijs/xzraw2

**Comment by bushuizaijian** [comment]
> > > 你的配置文件，和package.json里的依赖列表贴一下。你给的这个玩意没啥用
> > 
> > 
> > ![企业微信截图_15991052107616](https://user-images.githubusercontent.com/40242973/92069540-340bd480-eddc-11ea-947e-4844e0f16f28.png)
> > ![image](https://user-images.githubusercontent.com/40242973/92069587-41c15a00-eddc-11ea-9ddb-da966100ed9a.png)
> 
> 你只贴了 package.json 的依赖和开发依赖，配置文件没贴呢？

![image](https://user-images.githubusercontent.com/40242973/92075622-6ffa6600-edeb-11ea-84b7-0feef108aee5.png)

**Comment by bushuizaijian** [comment]
> 我遇到过一个可能类似的问题，已经解决，应该是 dva 插件没装的问题。
> 
> https://www.yuque.com/blueju/umijs/xzraw2
下载了，并没有解决这个问题，都不知道啥情况，谢谢

**Comment by xiaohuoni** [comment]
src/models 下面有 dva 文件吧？不需要用 dva 的话，app.js 里面的 dva 相关配置可以删掉。
