### ISSUE TITLE
启动报错，找不到原因

### ISSUE THREAD

**Issue by sussertod891015** [umijs/umi#5346]
## What happens?

本来项目开发没问题，结果今天到家启动项目突然就报错了，而且莫名其妙没有给出错误位置，貌似不是业务代码导致的。

## Mini Showcase Repository(REQUIRED)

报错其中有一行是这个，不知道是什么原因。undefined postinstall: `umi generate tmp`

## How To Reproduce

![image](https://user-images.githubusercontent.com/10465307/91996034-1b170b00-ed6b-11ea-9149-be49f0865db7.png)

## Context

- **Umi Version**: 3.2.10
- **Node Version**: 14.5.0
- **Platform**: macos 10.15.5

**Comment by xiaohuoni** [comment]
重新执行了 npm install 了嘛？感觉没装好，你重装一下模块试试。

**Comment by sussertod891015** [comment]
> 重新执行了 npm install 了嘛？感觉没装好，你重装一下模块试试。

嗯，删了重新装也不行。。。新建个项目，把代码拷贝进去也不行，而且重装也报错

**Comment by xiaohuoni** [comment]
给个复现demo吧

**Comment by sorrycc** [comment]
给复现例子看看，应该是 dva 或者 plugin-model 语法解析部分的问题。

**Comment by tiakia** [comment]
我今天也出现了这个问题
```
Unexpected token, expected "," (32:27)
```
删了依赖重新安装也不行，请问你怎么解决的？

**Comment by tiakia** [comment]
> 我今天也出现了这个问题
> 
> ```
> Unexpected token, expected "," (32:27)
> ```
> 
> 删了依赖重新安装也不行，请问你怎么解决的？

自问自答：
找到问题了，是因为在`modal`中使用了组件，所以报错了，奇怪的是编辑的时候可以，再次启动就不行了。

**Comment by zry754331875** [comment]
> > 我今天也出现了这个问题
> > ```
> > Unexpected token, expected "," (32:27)
> > ```
> > 
> > 
> > 删了依赖重新安装也不行，请问你怎么解决的？
> 
> 自问自答：
> 找到问题了，是因为在`modal`中使用了组件，所以报错了，奇怪的是编辑的时候可以，再次启动就不行了。

@tiakia 请问下怎么排查的哪一个文件呢，我同时使用了plugin-dva跟plugin-model，不知道是哪一个插件导致的，哪一个models导致的

**Comment by tiakia** [comment]
> > > 我今天也出现了这个问题
> > > ```
> > > Unexpected token, expected "," (32:27)
> > > ```
> > > 
> > > 
> > > 删了依赖重新安装也不行，请问你怎么解决的？
> > 
> > 
> > 自问自答：
> > 找到问题了，是因为在`modal`中使用了组件，所以报错了，奇怪的是编辑的时候可以，再次启动就不行了。
> 
> @tiakia 请问下怎么排查的哪一个文件呢，我同时使用了plugin-dva跟plugin-model，不知道是哪一个插件导致的，哪一个models导致的

这个要看你在哪个model中使用了react组件，我的情况是：在菜单数据回来后，遍历，给每条数据加了一个自定义的Icon组件，所以报错了

**Comment by Arthur0k** [comment]
解决了吗 兄弟  我今天也遇到这个错了  公司运行好好的 在家启动就报这个问题  还不知道哪出的错

**Comment by liutian** [comment]
我也是，文件很难定位

**Comment by senro** [comment]
只要有Model命名的文件就会出这个问题，改个名字就行了
