### ISSUE TITLE
使用headScripts方法插入额外脚本编译报错

### ISSUE THREAD

**Issue by overcastsky** [umijs/umi#5347]
## What happens?
我想在<head>中插入额外的脚本

headScripts: [{ src: './utils/demo.js' }]
编译时报错

## 相关环境信息

- **Umi 版本**：3.0.16
- **Node 版本**：10.15.0
- **操作系统**：MacOs
<img width="1674" alt="截屏2020-09-03下午4 12 13" src="https://user-images.githubusercontent.com/28147733/92089208-6af3e180-ee00-11ea-8e30-6ee667790c87.png">
<img width="320" alt="截屏2020-09-03下午4 10 54" src="https://user-images.githubusercontent.com/28147733/92089215-6c250e80-ee00-11ea-8d34-f5960bc8c5a9.png">

**Comment by xiaohuoni** [comment]
看起来是引入的文件，语法没有编译

**Comment by overcastsky** [comment]
如何解决呢

**Comment by overcastsky** [comment]
> 看起来是引入的文件，语法没有编译

这个问题怎么解决呢

**Comment by xiaohuoni** [comment]
感觉你的额外脚本可以写到 global.js ，如果是外部文件，文件需要编译。

**Comment by overcastsky** [comment]
> 感觉你的额外脚本可以写到 global.js ，如果是外部文件，文件需要编译。

这是我自己写的一个脚本文件，只能放在global.js中吗？

**Comment by xiaohuoni** [comment]
不是只能放在 global 中，是你的代码需要编译，你可以通过任意方式实现，我只是给你一个最小实现成本。直接用babel转一下也可以。

**Comment by cc7gs** [comment]
我也遇到同样情况，
想法: 只是想把工具类库通过script进入不走打包。
结果: 但是引入后会被打包成html文件。
暂时方案: 只能自己手动copy 到 ./dist目录，最后还是配置到了CDN加载。
<img width="701" alt="截屏2020-09-21 下午10 50 25" src="https://user-images.githubusercontent.com/36002392/93782221-e0630d00-fc5c-11ea-9179-e5872bfeed63.png">
![截屏2020-09-21 下午10 46 34](https://user-images.githubusercontent.com/36002392/93782246-e78a1b00-fc5c-11ea-90eb-28a4f055afc7.png)

**Comment by sorrycc** [comment]
需要同时配 `headScripts` 和 `copy`，

比如：（路径还要具体尝试下）

```
headScripts: [{ src: '/utils/demo.js' }],
copy: [
  './utils/demo.js',
]
```
