### ISSUE TITLE
[Feature Request] 希望 umi v3 开放 devScripts.js 修改能力 

### ISSUE THREAD

**Issue by yejiajiehz** [umijs/umi#5348]
## Background

在项目中注册了 `unhandledrejection` 事件做统一错误处理，但是发现不起作用  
原因是 `react-error-overlay` 注册了 `unhandledrejection` 事件，出现 `promise` 异常时会弹出 iframe  
看了一下 `react-error-overlay` 代码，内部提供了解绑事件和停止监听事件  

我尝试以下方式，均不起作用
1. 通过在 `global.tsx` 调用 解绑事件
2. 通过在 webpack 中使用 `NormalModuleReplacementPlugin` 替换 `react-error-overlay`

研究了一下 `umi` 的代码
由于 `umi` v3 版本默认将底层依赖构建到了 `@@/devScripts.js` 文件，`bundler-webpack/bundled/webpackHotDevClient.js` 实际是已经打包完成，无法通过配置 `webpack` 或者 `global.tsx` 中修改底层逻辑

## Proposal

希望开放高级编译模式，devScripts 中的依赖行为能够符合预期。

或者和 V2 [ERROR_OVERLAY](https://v2.umijs.org/guide/env-variables.html#error-overlay) 变量一样，能够禁用 `react-error-overlay`

## Additional context

同步 #4958 ，原因是一样的

**Comment by shengbeiniao** [comment]
同样的问题，如果用了 qiankun，会导致热更新失效

**Comment by RIPm** [comment]
我这边把主应用当成layout壳，子应用代理拉壳，也出现react-error-overlay报错导致热更失败

**Comment by jk4235** [comment]
https://github.com/umijs/qiankun/issues/1804#issuecomment-1017174913

过渡方法

**Comment by zerooverture** [comment]
在自定义协议下 devScripts 会提示  `The URL's scheme must be either 'http:' or 'https:'. 'xxx:' is not allowed.`
希望能增加配置自定义协议的功能或者提供修改devScripts的方法

**Comment by hyzx86** [comment]
请问下，这莫名其妙直接关Issue 是什么操作
是问题太小儿科还是 压根实现不了，给句话也行啊
