### ISSUE TITLE
api.addDepInfo is not a function

### ISSUE THREAD

**Issue by robinv8** [umijs/umi#5355]
## What happens?

![image](https://user-images.githubusercontent.com/12277531/92207853-90462580-eebc-11ea-8de8-051a8514de20.png)

## 相关环境信息

@umijs/plugin-helmet 1.1.1

**Comment by xiaohuoni** [comment]
升级 umi 版本

**Comment by robinv8** [comment]
@xiaohuoni 就是升级到最新版报的错

**Comment by xiaohuoni** [comment]
@robinv8 是需要升级umi版本。
