### ISSUE TITLE
使用 APP_ROOT 时 babel-loader 的缓存路径不对

### ISSUE THREAD

**Issue by gjfei** [umijs/umi#5356]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/gjfei/umi-test.git
## 复现步骤，错误日志以及相关配置
yarn start
![image](https://user-images.githubusercontent.com/33827314/92208104-12364e80-eebd-11ea-9e50-92b7d782fa72.png)

## 相关环境信息

- **Umi 版本**：
^3.2.19

- **Node 版本**：
v12.18.0
- **操作系统**：
win10

**Comment by xiaohuoni** [comment]
外面的是 babel-loader 的缓存目录，里面的是 umi 的运行时代码。
![image](https://user-images.githubusercontent.com/11746742/92339989-45f6bb80-f0eb-11ea-9cad-8c5a469ded4d.png)

**Comment by gjfei** [comment]
如果不修改启动目录的时候这个缓存文件也是在src下面修改了之后才会到根目录下面

**Comment by gjfei** [comment]
> 外面的是babel-loader的缓存目录，里面的是umi的运行时代码。
> ![图片](https://user-images.githubusercontent.com/11746742/92339989-45f6bb80-f0eb-11ea-9cad-8c5a469ded4d.png)

如果不修改启动目录的时候这个缓存文件也是在src下面修改了之后才会到根目录下面

**Comment by xiaohuoni** [comment]
没问题的，你就算设置 `APP_ROOT=src` 也是会在外面生成的。执行的根目录问题。 `.umi` 文件夹只是临时文件。

**Comment by gjfei** [comment]
> 没问题的，你就算设置也是`APP_ROOT=src`会在外面生成的。执行的根目录问题。`.umi`文件夹只是临时文件。

不影响运行就是了
我如果设置了app_root在根目录的环境文件就不起作用了，在umi2.x的时候就可以，这个问题怎么解决呢？

**Comment by xiaohuoni** [comment]
新的问题重新提Issues吧。我不太明白你说的 “app_root在根目录的环境文件”。你可以详细描述一下问题。

**Comment by sorrycc** [comment]
应该是 bug，我改了个标题。

**Comment by gjfei** [comment]
> 我不太明白你说的“ app_root在根目录的环境文件”。你可以详细描述一下问题。

https://github.com/umijs/umi/issues/5413
新开了一个issues可以看下
