### ISSUE TITLE
umi github 仓库 docs 与官网文档不同步的问题

### ISSUE THREAD

**Issue by blueju** [umijs/umi#5357]
报告一个问题：
umi github仓库docs与官网文档不同步。

12天前（约8月24日）提交了 pull request 并得到合并，如下图：

![image](https://user-images.githubusercontent.com/49681036/92295526-3dbe4500-ef60-11ea-83bd-c3e10a37a025.png)

![image](https://user-images.githubusercontent.com/49681036/92295827-d0f77a80-ef60-11ea-8af5-334fad390756.png)

3天前，作者修改了官网文档首页背景色相关代码，官网也相应更新了背景色。

![image](https://user-images.githubusercontent.com/49681036/92295803-9a216480-ef60-11ea-884e-20569f32e2e6.png)

![image](https://user-images.githubusercontent.com/49681036/92295809-a60d2680-ef60-11ea-9556-dbaad9a32f93.png)

但此时官网效果中提交的 pull request 修改处并未发生改变，仍是合并前的效果。

![image](https://user-images.githubusercontent.com/49681036/92295920-e1f4bb80-ef61-11ea-9a10-27db5744a797.png)

**Comment by blueju** [comment]
@sorrycc

**Comment by smart817** [comment]
建议更新一下官方文档吧，还有为什么yarn create umi创建的umi版本是2.9呢，而其它方式创建的都3.2.19了，

**Comment by blueju** [comment]
> 建议更新一下官方文档吧，还有为什么yarn create umi创建的umi版本是2.9呢，而其它方式创建的都3.2.19了，

+1，感觉官方文档有点过时了，大家提交的合并了的 pull request 都看不到。😂

create umi 是 umi 2 的脚手架，create @umijs/umi-app 是 umi 3 的脚手架，但是 create umi 中除了 app  模板，其他模板都是 umi 3，好混乱。😂

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/pull/5310/files#diff-184eb82ff267b9a62932ba673342c507R185
没问题的。只是被 qiankun 作者覆盖了。
