### ISSUE TITLE
用了3.X版本,出了很多问题,除了index页面,其他pages下的js都显示不出来等很急的问题

### ISSUE THREAD

**Issue by create-my-world** [umijs/umi#5358]
## What happens?

1. umi dev 成功后,浏览器除了能显示 http://localhost:8000/出来,其他pages包下的js 都显示不出来
![image](https://user-images.githubusercontent.com/50352516/92305537-cc5fb000-efba-11ea-8e45-2cf85030836c.png)
***
![image](https://user-images.githubusercontent.com/50352516/92305546-dd102600-efba-11ea-91eb-bee8b489910c.png)
***
![image](https://user-images.githubusercontent.com/50352516/92305558-fadd8b00-efba-11ea-94a0-911217a57d24.png)
***
![image](https://user-images.githubusercontent.com/50352516/92305560-02049900-efbb-11ea-8688-7bb47888035b.png)
***
![image](https://user-images.githubusercontent.com/50352516/92305564-06c94d00-efbb-11ea-85d8-6c2a97656a68.png)

2.console台 那一直黄牌警告 二个问题, babel.js 的转码器输出到console台 也没起作用.

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**： "umi": "^3.2.19",
- **Node 版本**：v12.18.3
- **操作系统**：win10

**Comment by xiaohuoni** [comment]
给重现demo

**Comment by create-my-world** [comment]
谢谢 你好,。我看网上说是, 约定式路由不能再配置路由了,然后我删除了.umirc.ts下的默认配置的路由,就好了。那个404 下面有不同路由信息展示页面 没出来,其他都挺好目前 





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "小虎oni"<notifications@github.com&gt;; 
发送时间: 2020年9月7日(星期一) 上午9:15
收件人: "umijs/umi"<umi@noreply.github.com&gt;; 
抄送: "尉官正年轻"<941301612@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [umijs/umi] 用了3.X版本,出了很多问题,除了index页面,其他pages下的js都显示不出来等很急的问题 (#5358)





 
给重现demo

**Comment by xiaohuoni** [comment]
你现在的配置文件应该是无效的，放的地方不正确吧？

**Comment by create-my-world** [comment]
,把这注释了





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "小虎oni"<notifications@github.com&gt;; 
发送时间: 2020年9月7日(星期一) 上午9:34
收件人: "umijs/umi"<umi@noreply.github.com&gt;; 
抄送: "尉官正年轻"<941301612@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [umijs/umi] 用了3.X版本,出了很多问题,除了index页面,其他pages下的js都显示不出来等很急的问题 (#5358)





 
你现在的配置文件应该是无效的，放的地方不正确吧？

**Comment by sorrycc** [comment]
很急但问题应该给复现。

**Comment by create-my-world** [comment]
感谢 ,现已解决 .是我对React组件化开发和约定式路由理解短浅了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chencheng (云谦)"<notifications@github.com&gt;; 
发送时间: 2020年9月7日(星期一) 中午11:12
收件人: "umijs/umi"<umi@noreply.github.com&gt;; 
抄送: "尉官正年轻"<941301612@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [umijs/umi] 用了3.X版本,出了很多问题,除了index页面,其他pages下的js都显示不出来等很急的问题 (#5358)





 
很急的问题应该给复现。
