### ISSUE TITLE
[Feature Request] dynamicImport 支持配置加载失败显示的组件

### ISSUE THREAD

**Issue by yingzhiji** [umijs/umi#5360]
目前 dynamicImport 只能配置 loading 组件，当网络出错时会一直显示 loading，可不可以加一个 error 配置，当网络出错时显示这个 error 组件，还有 timeout 配置，指定当超出这个时间还没有加载成功，也显示 error 组件。

**Comment by PeachScript** [comment]
虽然不在文档里，但实际上是支持的，可以通过 loading 组件的 props 拿到 `error` 和 `timeout`，详见：https://github.com/umijs/umi/blob/master/packages/runtime/src/dynamic/loadable.js#L181

如果有时间，可以在使用成功后帮 Umi 完善下 dynamicImport 部分的中英文文档

**Comment by yingzhiji** [comment]
试了一下，loading 组件拿不到 error 和 timeout，打印 props 是这样的：
![image](https://user-images.githubusercontent.com/21698836/102746999-57ae5700-439a-11eb-9c3d-eee02be166eb.png)
如果可以这样配置就好了，
```js
dynamicImport: {
  loading: '@/components/PageLoading',
  error: '@/components/ErrorComponent',
  delay: 200,
  timeout: 3000
}

**Comment by sorrycc** [comment]
有需要可以直接提 PR。
