### ISSUE TITLE
AssertionError: Invalid key dva from plugin  有没有人遇到过

### ISSUE THREAD

**Issue by bushuizaijian** [umijs/umi#5362]
![image](https://user-images.githubusercontent.com/40242973/92344798-02f01480-f0fa-11ea-84cb-13acf43533d0.png)
![image](https://user-images.githubusercontent.com/40242973/92344810-0a172280-f0fa-11ea-97bd-236120ccf80e.png)
![image](https://user-images.githubusercontent.com/40242973/92344831-18fdd500-f0fa-11ea-8ea6-49421dd55c9a.png)
![image](https://user-images.githubusercontent.com/40242973/92344850-21eea680-f0fa-11ea-8186-b480ce2025f3.png)
![image](https://user-images.githubusercontent.com/40242973/92344870-2b780e80-f0fa-11ea-8434-b6d0dda7519d.png)

**Comment by sorrycc** [comment]
看依赖和配置是对的，但为啥 dva 插件没有生效。。

**Comment by bushuizaijian** [comment]
> 看依赖和配置是对的，但为啥 dva 插件没有生效。。
就是不明白为啥dva没有生效，这可咋办。。。

**Comment by sorrycc** [comment]
给复现步骤，找时间给你排查下。

**Comment by bushuizaijian** [comment]
> 给复现步骤，找时间给你排查下。
复现步骤就是， 我运行yarn安装依赖，然后用 umi dev 运行项目，编译完成，最后打开页面就是报dva插件无效
![image](https://user-images.githubusercontent.com/40242973/92346055-3765cf80-f0fe-11ea-90e1-64980864c9e8.png)
这个是我编译成功的截图，还需要什么吗？ 谢谢你

**Comment by xiaohuoni** [comment]
给一个可以运行复现的最小项目。

**Comment by bushuizaijian** [comment]
> 给一个可以运行复现的最小项目。


[tst.zip](https://github.com/umijs/umi/files/5185918/tst.zip)

**Comment by bushuizaijian** [comment]
> 给一个可以运行复现的最小项目。

您好，请问复现问题了吗？

**Comment by xiaohuoni** [comment]
要存在 dva 的 model。
