### ISSUE TITLE
紧急：useRequest当连续run同一个请求，onSuccess只触发了一次。

### ISSUE THREAD

**Issue by shx996** [umijs/umi#5364]
## What happens?

如题，（并未使用防抖）。

## 最小可复现仓库

[https://codesandbox.io/s/holy-https-cejdy?file=/src/App.js](https://codesandbox.io/s/holy-https-cejdy?file=/src/App.js)

## 复现步骤，错误日志以及相关配置
任何同一个请求多次run即可复现

## 相关环境信息

@umijs/use-request 1.4.3

**Comment by xiaohuoni** [comment]
可以用[并行](https://ahooks.js.org/zh-CN/hooks/async#%E5%B9%B6%E8%A1%8C%E8%AF%B7%E6%B1%82)或者[防抖](https://ahooks.js.org/zh-CN/hooks/async#%E9%98%B2%E6%8A%96)的方式处理
