### ISSUE TITLE
为什么国际化切换到“阿拉伯语言”的时候，会导致antd的样式错乱

### ISSUE THREAD

**Issue by hello-lun** [umijs/umi#5374]
一、问题：为啥国际化切换到“阿拉伯语言”的时候，会导致antd的样式错乱
1、正常的样式
![image](https://user-images.githubusercontent.com/34638158/92428747-92f99100-f1c2-11ea-9df8-647bd1ce7aac.png)

2、错误的样式：
![image](https://user-images.githubusercontent.com/34638158/92428904-fdaacc80-f1c2-11ea-8dae-99bba4fcdde8.png)

代码：
![image](https://user-images.githubusercontent.com/34638158/92428878-eb309300-f1c2-11ea-8fda-a0f7491d5fd7.png)

umijs版本：3.2.15

**Comment by xiaohuoni** [comment]
关闭原因是：浏览器特性，谷歌浏览器会有这个表现，介意的朋友，可以通过 [antd config](https://umijs.org/plugins/plugin-antd#config) 指定模式。
