### ISSUE TITLE
目前是否支持将整个应用打包成一个umd包，入口执行逻辑支持自定义

### ISSUE THREAD

**Issue by wjkang** [umijs/umi#5375]
目前有这样的业务场景，需要将整个应用打包成一个umd包，暴露出一个对象，调用对象的方法做一写配置，并且调用某一个特定方法时（比如`mount`），才将应用挂载到相应的 dom 节点上

**Comment by uWydnA** [comment]
找到解决方案了吗？

**Comment by JeromeYangtao** [comment]
@wjkang @uWydnA 有解决方案  也遇到了这个问题
