### ISSUE TITLE
ssr + dynamicImport 配置，指定loading组件 ssr 失败

### ISSUE THREAD

**Issue by yangsendyx** [umijs/umi#5376]
## What happens?

开启ssr + dynamicImport，在浏览器端页面切换加载资源时，会有`Loading...`的组件显示，期望是关闭，但未找到相关配置
如果指定了 dynamicImport.loading 组件，则 ssr 渲染失败，会降级为 csr 模式。

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库
https://github.com/yangsendyx/umi-issue

## 复现步骤，错误日志以及相关配置

注释或开启`.umirc.ts`的 `loading` 配置，会影响 ssr 模式的渲染结果

## 相关环境信息

- **Umi 版本**：3.2.19
- **Node 版本**：v10.15.0
- **操作系统**：macOS 10.15.6

**Comment by yangsendyx** [comment]
目前是用 css 隐藏了`#root`元素下的第一个直系`p`元素，但感觉就很不靠谱 - -

**Comment by PeachScript** [comment]
无法复现，如何判定 SSR 失败，控制台有错误输出吗

**Comment by PeachScript** [comment]
渲染失败是指控制台报错 `ReferenceError: LoadingComponent is not defined` 吗

**Comment by yangsendyx** [comment]
> 渲染失败是指控制台报错 `ReferenceError: LoadingComponent is not defined` 吗

是的，控制台有报这个错误。
