### ISSUE TITLE
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by promotion-xu** [umijs/umi#5377]
## What happens?
当我将项目部署到服务器上的时候

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 2.4.4
- **Node Version**: v8.10.0
- **Platform**: Linux

**Comment by promotion-xu** [comment]
可能与机器有关？ 我们这复现不了，只有客户那里才能复现
客户Chrome版本: 85

**Comment by jvcjunior** [comment]
Any news about this one?

**Comment by 2fps** [comment]
有解决么？我这边台chrome的版本是 85.0.4183.121 也出现了同样的问题，其他的chrome都是正常的

**Comment by jvcjunior** [comment]
I know what happened, at least with me. If the user is using google translate plugin for chrome, then it'll try to translate automatically and try to change the html causing this problem. Deactivate the google translate plugin and test please!

**Comment by quicklearning123** [comment]
> I know what happened, at least with me. If the user is using google translate plugin for chrome, then it'll try to translate automatically and try to change the html causing this problem. Deactivate the google translate plugin and test please!

same problem

**Comment by puff-sunny** [comment]
有解决么。我这边使用的edge浏览器 会自动翻译。 出现了同样的问题

**Comment by mamumu123** [comment]
https://github.com/facebook/react/issues/11538
