### ISSUE TITLE
建议添加使用 browserslist 的功能

### ISSUE THREAD

**Issue by yingzhiji** [umijs/umi#5380]
建议添加功能：当 targets 为 false 时，就读取 browserslist 里的配置，因为有些工具如：eslint-plugin-compat、stylelint-no-unsupported-browser-features、postcss-preset-env、postcss-normalize 都是读取的 browserslist 里的配置，当使用这些工具时，现在需要同时维护 targets 和 browerslist 的配置，而且 targets 也不支持 broserslist 里的一些高级配置：last 2 versions、>= 5% 等。

**Comment by jiyingzhi** [comment]
browserslist 可以看成是社区的约定，不仅上面这些工具，webpack5 也会读取里面的浏览器范围生成对应浏览器兼容的运行时代码
https://webpack.docschina.org/migrate/5/#need-to-support-an-older-browser-like-ie-11
