### ISSUE TITLE
ssr模式下routes中redirect配置问题

### ISSUE THREAD

**Issue by feehc** [umijs/umi#5382]
## What happens?

当routes中配置redirect时，服务端未执行目标组件的getInitialProps静态函数，客户端却执行了getInitialProps静态函数

## How To Reproduce

**Steps to reproduce the behavior:** 

1、ssr配置如下：
```
  ssr: {
    // forceInitial: false,
    devServerRender: false,
  },
```

2、routes配置如下：
```
  {
    path: '/course',
    redirect: '/course/0/0/1',
  },
  {
    path: '/course/:categoryId/:majorId/:current',
    component: './course/list',
    exact: false,
  },
```

3、目标组件中添加日志输出：
```
CourseList.getInitialProps = async (ctx) => {
  console.log('CourseList.getInitialProps');
  ...
};
```

4、服务端日志输出：无

5、客户端日志输出，其中错误日志因此时无法从上下文中解构出routes引起：
```
CourseList.getInitialProps
Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined
  at flattenRoutes (breadcrumb.js:6)
  ...
```

**Expected behavior**

1、服务端完成redirect跳转，并执行完目标组件的getInitialProps静态函数后再返回response

2、forceInitial为false时，客户端完成redirect跳转后不再执行getInitialProps静态函数

3、客户端执行getInitialProps静态函数时，确保上下文的routes、history等已正确实例化

## Context

- **Umi Version**: 3.2.15
- **Node Version**: v12.18.3
- **Platform**: win10

**Comment by ycjcl868** [comment]
有复现的例子吗？
