### ISSUE TITLE
跪求回答：自定义区块什么时候才能在 umi 3 中使用

### ISSUE THREAD

**Issue by bluescurry** [umijs/umi#5383]
这个功能非常关键，可以极大的提升开发效率，umi 3什么时候才能使用。。。

**Comment by ycjcl868** [comment]
有个 VSCode 插件，umi 应该也可以用

**Comment by bluescurry** [comment]
能麻烦说的具体些吗，vscode 哪个插件呢


| |
韩硕
邮箱：18832643723@163.com
|

签名由 网易邮箱大师 定制

在2020年09月13日 20:50，信鑫-King 写道：

有个 VSCode 插件，umi 应该也可以用

**Comment by bluescurry** [comment]
能麻烦说的具体些吗，


| |
韩硕
邮箱：18832643723@163.com
|

签名由 网易邮箱大师 定制

在2020年09月13日 20:50，信鑫-King 写道：

有个 VSCode 插件，umi 应该也可以用

**Comment by xuanxuan321** [comment]
umi3是不是废弃掉区块了，文档里面都没相关的介绍了

**Comment by sorrycc** [comment]
umi ui 已不推荐使用，请使用其他方式添加模版代码。

**Comment by bluescurry** [comment]
> umi ui 已不推荐使用，请使用其他方式添加模版代码。

dumi 1.1.0 已经支持了在 Umi-ui 中添加自定义区块了啊，为啥现在不推荐使用了呢，比较关心这块后期的迭代规划，是否解答下，多谢多谢

**Comment by PeachScript** [comment]
@bluescurry 后续会发布一款 VSCode 插件来实现区块添加，目前还在内测
