### ISSUE TITLE
开启配 layout 我希望配置路由嵌套可以自己定义，目前生成配置默认嵌套全部路由

### ISSUE THREAD

**Issue by namecui** [umijs/umi#5386]
生成配置如下：
<img width="1124" alt="截屏2020-09-09 下午12 00 04" src="https://user-images.githubusercontent.com/34806181/92553136-d15f8080-f294-11ea-9403-0418447e7b6d.png">

我希望可以自己配置生成效果例如：
<img width="1155" alt="截屏2020-09-09 下午12 00 52" src="https://user-images.githubusercontent.com/34806181/92553180-e6d4aa80-f294-11ea-83a6-38ff0d67789a.png">

目前没有找到解决办法

**Comment by aixfox** [comment]
你实际上是想 login 有单独的 layout？

在 src/layout/index.js 中判断一下 props.location.pathname，不同情况返回不同的组件。
