### ISSUE TITLE
国际化语言配置中路由中配置了菜单名，在配置title字段，页面的标题会被菜单名覆盖掉。

### ISSUE THREAD

**Issue by wangyuan0108** [umijs/umi#5388]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by hopperhuang** [comment]
也遇到这个问题
umi: "^3.2.27",
node: 14.15.0,
操作系统: osx 10.12.6

**Comment by chenshuai2144** [comment]
配置 title=false
