### ISSUE TITLE
layout的name字段配置暂时貌似不支持国际化配置

### ISSUE THREAD

**Issue by wangyuan0108** [umijs/umi#5389]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by xiaohuoni** [comment]
可以通过 runtime 配置传入。

**Comment by wangyuan0108** [comment]
> 可以通过 runtime 配置传入。

好的，我试试
