### ISSUE TITLE
custom .env vars 

### ISSUE THREAD

**Issue by octaviou** [umijs/umi#5392]
## What happens?

Not so sure if this is a bug or it's me... 
I am not able to set a new env variable. (I need to pass API_URL at build time so I can inject urls)
Tried creating and .env file but no success. However, If I add PORT=3000 I successfully start the app in that port number.

## How To Reproduce
printing: process.env  
```
eg: console.log( process.env );
```

**Steps to reproduce the behavior:** 1. 2.
```
1. create .env file with
2. write new var like: API_URL=https://...
3. read process.env ,  eg: console.log( process.env )
```

**Expected result:** 1.2
```
NODE_ENV:development
API_URL=https://...

```
Unfortunately, I not able to read the later one (API_URL) 
Any help is appreciated , many thanks for your time!

- **Umi Version**:
3.2.20
- **Node Version**:
v10.16.3
- **Platform**:
osx / linux

**Comment by aixfox** [comment]
`process.env` in runtime is provided by webpack.DefinePlugin.

There are filters in umi, see:
https://github.com/umijs/umi/blob/master/packages/bundler-webpack/src/getConfig/resolveDefine.ts

You can use umi config `option.define` for what you like.

**Comment by octaviou** [comment]
> `process.env` in runtime is provided by webpack.DefinePlugin.
> 
> There are filters in umi, see:
> https://github.com/umijs/umi/blob/master/packages/bundler-webpack/src/getConfig/resolveDefine.ts
> 
> You can use umi config `option.define` for what you like.

Many thanks! 
By looking at that file I realised that new env vars should be prefixed with UMI_APP_ I added that and worked!!
About ```option.define``` The thing is that I need to provide a way for devops to change the url from outside. That's why did not fit to my development.
