### ISSUE TITLE
chunk文件如何被umi.js匹配加载的呢

### ISSUE THREAD

**Issue by w611363303798** [umijs/umi#5397]
打包后有很多chunk和async文件

本地启动可以被umi.js匹配被加载进来

服务端返回html后（路由一样），成功加载umi.js umi.css react.js 但chunk文件没被引入导致页面白屏。root节点为空，未报错

## 相关环境信息

- **Umi 版本**：2.85
- **Node 版本**：14.9.0
- **操作系统**：macos

**Comment by xiaohuoni** [comment]
不知道你的服务端返回html怎么做的。建议直接用 [ssr](https://umijs.org/config#ssr-32)
