### ISSUE TITLE
[Feature Request] yarn create @umijs/umi-app和 yarn create umi有没有可能合并？

### ISSUE THREAD

**Issue by oxygen-xx** [umijs/umi#5399]
## Background

yarn create @umijs/umi-app和 yarn create umi有没有可能合并？
yarn create @umijs/umi-app的提示中，有没有可能选择不用TS用JS？
yarn create umi，好像一直不支持最新的UMI3版本，默认出来的就是V2

## Proposal

建立把所有功能，合并在yarn create umi中。

**Comment by xiaohuoni** [comment]
看情况，短时间内不会做这个事情。因为 2 和 3 差异比较大。
