### ISSUE TITLE
使用了 ??= 语法 umi编译失败

### ISSUE THREAD

**Issue by originshi** [umijs/umi#5400]
var a = {a: 12, b: null};
		a.b ??= 'aaaaaa';
		a.a ??= 123;
源码

SyntaxError: index.tsx: Unexpected token (2:7)

  1 | var a = { a: 12, b: null };
> 2 | a.b ?? ;
    |        ^
  3 | 'aaaaaa';
  4 | a.a ?? ;
  5 | 123;

使用了 ??= 语法 umi编译失败

**Comment by blinkMyEyesConsciously** [comment]
??=  是什么语法  有这个语法吗  不应该是a.b ?? 'aaaaaa';     a.a ??123; 吗

**Comment by aixfox** [comment]
umi 是什么版本？ 3.1.4 才添加 @babel/plugin-proposal-logical-assignment-operators

**Comment by sorrycc** [comment]
请使用最新版 Umi 。
