### ISSUE TITLE
行尾这个逗号得去掉，IE11会报语法错误

### ISSUE THREAD

**Issue by feehc** [umijs/umi#5402]
https://github.com/umijs/umi/blob/8f5add11137003bc1ec8e007dd69de18e8b5353e/packages/bundler-webpack/mini-css-extract-plugin/dist/hmr/hotModuleReplacement.js#L73

**Comment by KellenHe** [comment]
这个什么时候release？

**Comment by ycjcl868** [comment]
还有问题吗？
