### ISSUE TITLE
useModel，refresh无法刷新access.

### ISSUE THREAD

**Issue by tangsengrouyidai** [umijs/umi#5406]
//.umirc.ts
layout: {}, 
routes: [
    { path: '/', component: '@/pages/index', access: "isLogin" },
    { path: '/login', component: '@/pages/login.tsx', access:"noLogin" },
  ]
//pages/index.tsx
import React from 'react';
export default () => {
  return (
    <div>
      <h1>Page index</h1>
    </div>
  );
}
//pages/login.tsx
export default () => {
  const { refresh,setInitialState } = useModel('@@initialState');
  return (
    <div>
      登录页面
      <button onClick={() => {
        globalData.login = true
        refresh()
      }}>
        登录
      </button>
    </div>
  );
}
//app.ts
import globalData from './globalData';
export function getInitialState() {
  return globalData.login
}
//pages/globalData
let globalData = {
  login: false
}
export default globalData
//access.ts
export default function (initialState: any) {
  return {
    isLogin: initialState,
    noLogin: !initialState,
  }
}

**Comment by tangsengrouyidai** [comment]
refresh 调用后 layout页面,access为true的页面依然是403

**Comment by sorrycc** [comment]
It's inactive above 3 months, feel free to reopen if you still have problems.

**Comment by xiexingen** [comment]
这些bug 怎么都自动关闭了
