### ISSUE TITLE
example SSR koa 运行服务端渲染，接口默认是80端口，直接调不到代理的地址

### ISSUE THREAD

**Issue by jessechenyi** [umijs/umi#5408]
static getInitialProps = async ({ store, isServer, history, match, route }) => {
    if (!isServer) {
      return;
    }

    await store.dispatch({ type: 'ask/fetchAskList' });
    const { ask } = store.getState();
    return { ask: ask.data };
  };
调用后
这是地址
export function getAskList(data) {
  return request({
    url: '/api/web/ask/list',
    method: 'post',
    data,
  });
}
但是我的接口去了80端口
打印报错
Error: Error: connect ECONNREFUSED 127.0.0.1:80
怎么去了80端口
代理是好的，按理说是服务的7001端口
代理配置如下
app.use(
  koaServerHttpProxy('/api/**', {
    target: 'http://localhost:8080',
    pathRewrite: { '^/api': '' },
    changeOrigin: true,
  }),
);

**Comment by williamnie** [comment]
有复现方式么，提供一个

**Comment by jessechenyi** [comment]
没有复现地址，但是我把node服务改成80端口，node在做个代理服务，暂时解决问题



---原始邮件---
发件人: "小北"<notifications@github.com&gt;
发送时间: 2020年9月14日(周一) 上午9:34
收件人: "umijs/umi"<umi@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"最前端"<879786154@qq.com&gt;;
主题: Re: [umijs/umi] example SSR koa 运行服务端渲染，接口默认是80端口，直接调不到代理的地址 (#5408)




 
有复现方式么，提供一个

**Comment by JavaScriptam** [comment]
我也出现了这个问题
![image](https://user-images.githubusercontent.com/25917806/99220857-6a24f600-281a-11eb-8d10-113d8192a08b.png)
![image](https://user-images.githubusercontent.com/25917806/99220923-950f4a00-281a-11eb-972e-8b881aa3e3fd.png)
![image](https://user-images.githubusercontent.com/25917806/99221015-c2f48e80-281a-11eb-8c6f-104848ef2c33.png)

设置代理到3001  开启node服务确实是3001端口 这个不会错。
