### ISSUE TITLE
af-webpack和umi-build-dev的config assert 有点冗余

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#541]
umi\packages\umi-build-dev\lib\getConfig\configPlugins
umi\packages\af-webpack\src\getUserConfig\configs
这两个文件下面的文件感觉有点冗余

**Comment by sorrycc** [comment]
umi\packages\af-webpack\src\getUserConfig\configs 这个是 umi 和 roadhog 共用的。
