### ISSUE TITLE
layout配置是否可以增加mix模式

### ISSUE THREAD

**Issue by saltovo** [umijs/umi#5411]
ant-design/pro-layout 现已支持layout:mix模式，可否在umi中增加配置更改pro-layout的mix模式

**Comment by sorrycc** [comment]
@chenshuai2144 现在支持吗？

**Comment by yutingzhao1991** [comment]
支持的，项目里面依赖 pro-layout 6.x 版本就行，然后配置 `layout: 'mix'`
