### ISSUE TITLE
设置APP_ROOT之后.env环境变量如果放在根目录就无效了

### ISSUE THREAD

**Issue by gjfei** [umijs/umi#5413]
## What happens?

我把APP_ROOT设置成src/render环境变量.env需要放在.env才会生效，但是使用yarn create umi 创建的umi2.x项目放在根目录下面就可以
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/gjfei/umi-test.git
## 复现步骤，错误日志以及相关配置
yarn start
yarn create @umijs/umi-app
![image](https://user-images.githubusercontent.com/33827314/93153018-d019d200-f732-11ea-910b-a58b14e40b51.png)
![image](https://user-images.githubusercontent.com/33827314/93153043-d9a33a00-f732-11ea-8b30-ed85b745f206.png)

yarn create umi
![image](https://user-images.githubusercontent.com/33827314/93153449-d9f00500-f733-11ea-8f7a-f16283763a84.png)
![image](https://user-images.githubusercontent.com/33827314/93153491-f0965c00-f733-11ea-9e01-eae284f6c506.png)

## 相关环境信息

- **Umi 版本**：
^3.2.19

- **Node 版本**：
v12.18.0
- **操作系统**：
win10

**Comment by sorrycc** [comment]
不用新开了，就在 #5356 跟进吧，已标记为 bug，找时间修复。

**Comment by gjfei** [comment]
> 不用新开了，就在[＃5356](https://github.com/umijs/umi/issues/5356)跟进吧，已标记为bug，找时间修复。

好的，这是两个不同的bug

**Comment by laozhu** [comment]
请问这个问题解决了吗 @gjfei @sorrycc @xiaohuoni 
最新版本的 umijs 在自定义 APP_ROOT 环境变量后依然无法读取根目录下面的 .env 文件。

**Comment by xiaohuoni** [comment]
> 请问这个问题解决了吗 @gjfei @sorrycc @xiaohuoni
> 最新版本的 umijs (3.2.28)，系统是 macOS，在自定义 APP_ROOT 环境变量后依然无法读取根目录下面的 .env 文件。
> 
> ```json
> {
>   "dev": " cross-env REACT_APP_ENV=dev APP_ROOT=renderer UMI_UI=none umi dev",
> }
> ```

和这个问题好像不是一回事

**Comment by gjfei** [comment]
> 请问这个问题解决了吗 @gjfei @sorrycc @xiaohuoni
> 最新版本的 umijs (3.2.28)，系统是 macOS，在自定义 APP_ROOT 环境变量后依然无法读取根目录下面的 .env 文件。
> 
> ```json
> {
>   "dev": " cross-env REACT_APP_ENV=dev APP_ROOT=renderer UMI_UI=none umi dev",
> }
> ```

解决的是缓存的问题，这个问题并没有解决。
我是利用了dotenv去读取文件
![image](https://user-images.githubusercontent.com/33827314/100205653-5c6d2000-2f40-11eb-9545-a2b3b8464162.png)

**Comment by xiaohuoni** [comment]
也可能是 .dev 文件的读取有问题，不改APP_ROOT 的时候，也有朋友提过无效

**Comment by laozhu** [comment]
@xiaohuoni 我是在做 `electron` 应用开发时候遇到此问题的。

1. 使用 `src` 作为默认的 `APP_ROOT` 没有出现问题，正常读取
2. 将 `src` 重命名为 `renderer`，给 `scripts` 加上了 `APP_ROOT=renderer` 后就没法读取根目录下的 `.env` 文件了
3. 同 2 操作，但将 `.env` 从根目录移到 `renderer` 目录中，又可以正常读取了

**Comment by gjfei** [comment]
> @xiaohuoni 我是在做 `electron` 应用开发时候遇到此问题的。
> 
> 1. 使用 `src` 作为默认的 `APP_ROOT` 没有出现问题，正常读取
> 2. 将 `src` 重命名为 `renderer`，给 `scripts` 加上了 `APP_ROOT=renderer` 后就没法读取根目录下的 `.env` 文件了
> 3. 同 2 操作，但将 `.env` 从根目录移到 `renderer` 目录中，又可以正常读取了

可以看下我的解决方案，这样electron和umi可以公用一个env

**Comment by xiaohuoni** [comment]
> @xiaohuoni 我是在做 `electron` 应用开发时候遇到此问题的。
> 
> 1. 使用 `src` 作为默认的 `APP_ROOT` 没有出现问题，正常读取
> 2. 将 `src` 重命名为 `renderer`，给 `scripts` 加上了 `APP_ROOT=renderer` 后就没法读取根目录下的 `.env` 文件了
> 3. 同 2 操作，但将 `.env` 从根目录移到 `renderer` 目录中，又可以正常读取了

感觉这是正确的逻辑

**Comment by laozhu** [comment]
@xiaohuoni 只是运行 renderer 的话放里面也没什么问题，但我还有一个同级的 main 也希望能读取 .env，放到根目录的话能正常读取是不是好些啊。

**Comment by xiaohuoni** [comment]
放根目录能正常读取的话，就是bug了吧。APP_ROOT 就是修改根目录指向。被指定的文件目录才是真正的根目录。

**Comment by laozhu** [comment]
@xiaohuoni  谢谢解释，虽然你这样解释让我明白这个不是 umi 有 bug，而是设计如此。
但我还是觉得这是个合理需求，如果能从 APP_ROOT 向上搜索 .env 的话（可以限制搜索的层级），就能在项目的前后端或者前端多个包之间公用一个 .env 文件了。
