### ISSUE TITLE
开启按需加载dynamicImport以后，页面组件化引用时，加载报错

### ISSUE THREAD

**Issue by maureen2018** [umijs/umi#5414]
## What happens?

打开dynamicImport按需加载以后，页面组件化引用时，加载报错
![image](https://user-images.githubusercontent.com/41036644/93154019-2e47b480-f735-11ea-9c27-f5bea273ab00.png)
![image](https://user-images.githubusercontent.com/41036644/93154081-50d9cd80-f735-11ea-831c-282c08e6c37e.png)
这些页面被当成组件引入另一个页面，页面加载的时候，props那边会报错。
不打开dynamicImport不会报错。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
你这么写没有按需的必要。然后通过layout去控制路由变化就好。还有如果你直接在页面只能中引入，那你可能还需要把父级的props传到页面组件内。
