### ISSUE TITLE
ant插件 怎么设置全局组件大小

### ISSUE THREAD

**Issue by jack1157693211** [umijs/umi#5415]
这是申明:
  antd?: {
    dark?: boolean;
    compact?: boolean;
    config?: {};
  };
这是我:
export default defineConfig({
  antd: {
    config: {
      componentSize: "small"
    }
  }
我想知道config 里面可以写的哪里或者在源码哪里能找到config相关信息

**Comment by xiaohuoni** [comment]
config 配置的是 https://ant.design/components/config-provider-cn/
