### ISSUE TITLE
路径中不能包含“distributor”英文单词？

### ISSUE THREAD

**Issue by silentim** [umijs/umi#5416]
## What happens?

如果路径中包含 distributor 英文，如：/pages/distributor/index.jsx ，则index.jsx页面更改后，umi不会自动重新生成页面，必须重新启动，即umi dev后才会更新。好象之前的umi版本是可以的，不知道是从哪个版本开始就这样。

## 复现步骤，错误日志以及相关配置

在项目中创建以 distributor 命名的目录，然后更新或直接重新保存该目录中的页面内容

## 相关环境信息

- **Umi 版本**：3.2.20
- **Node 版本**：14.3.0
- **操作系统**：windows

**Comment by LeoHuiyi** [comment]
![image](https://user-images.githubusercontent.com/8001457/93186479-45a49300-f771-11ea-8676-e09e5aeda58a.png)
估计是这段代码问题 有dist都会忽略
启动时候加个WATCH_IGNORED=node_modules变量可以暂时解决

**Comment by sorrycc** [comment]
这么隐藏的 bug 都能被找到。。

**Comment by 7ynstar** [comment]
+1，今天也遇到了这个bug。
发现是 `component` 路径中不能含有 `dist` 这四个字母，有则不刷新。
不知道之后的 `umi` 中会修复不？

**Comment by xiaohuoni** [comment]
@7ynstar 已经修复了
