### ISSUE TITLE
umi的getInitialState里面发请求如果请求比较费时 页面会有很长一段时间的空白

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi#5417]
## What happens?

步骤
1.在app.ts中getInitialState中发起以后后端请求查询基础的站点数据，这个请求比较费时
2.由于已经启动了umi id="root"的目录已经挂载(本来是在document.ejs中root目录下增加了loading效果的元素的)，这样 页面会有很长一段时间的空白，也没办法给一个loading效果
有没什么好点的解决方案
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by williamnie** [comment]
这个不应该是让后端去优化接口么？即便有loading也不好啊，无论是c端还是b端的场景，哪有一打开页面就开始loading的，你得考虑下为什么要在这里去加载数据，是否可以换到其他的地方，接口为什么慢，是后端逻辑复复杂还是什么情况，有没有办法做缓存

**Comment by xiexingen** [comment]
> 这个不应该是让后端去优化接口么？即便有loading也不好啊，无论是c端还是b端的场景，哪有一打开页面就开始loading的，你得考虑下为什么要在这里去加载数据，是否可以换到其他的地方，接口为什么慢，是后端逻辑复复杂还是什么情况，有没有办法做缓存

是没错，但是如果有个loading效果不是更好？ 就算后端返回快那也存在客户端网络等外在原因会存在需要loading的情况吧

**Comment by williamnie** [comment]
你不一定在启动的时候做这个请求，可以加个缓冲页，或者是采用，先加载出来基本的页面，在加载特殊配置重新render

**Comment by xiexingen** [comment]
有个前置请求，比如 根据子域名加载不同的logo图片、站点配置等

**Comment by williamnie** [comment]
可以有这些，一般情况下来说，这样的api会很快，而且这些数据会做前端缓存，第二次加载直接从本地读取，第一次即便是客户网络慢，可能资源加载都没加载完，打不开也很正常

**Comment by xiexingen** [comment]
所以 有个loading从体验上来说不是更好么
