### ISSUE TITLE
pro-layout升级成6.4.18，侧边栏样式错乱

### ISSUE THREAD

**Issue by qwe9527** [umijs/umi#5420]
umi 3.2.19
@ant-design/pro-layout版本升级成6.4.18后，侧边栏空出一块。下图中的div好像是多余的。

![image](https://user-images.githubusercontent.com/23071889/93180977-759c6800-f76a-11ea-988a-23c39ce9dc1a.png)

**Comment by chenshuai2144** [comment]
来个重写的 repo

**Comment by xiaohuoni** [comment]
@qwe9527 cc

**Comment by qwe9527** [comment]
> 来个重现的 repo

新建一个干净的项目，又可以了...
