### ISSUE TITLE
publicPath设置了路径后，publicPath：‘/tmr/’后，http://域名/dev-server/info?t=1600157059518无法连接，publicPath对dev-server没生效

### ISSUE THREAD

**Issue by 892744577** [umijs/umi#5421]
操作：umirc.js中publicPath设置了路径，如‘/tmr/’ 
问题：能正常访问所有路径，但是只有这条路径http://域名/dev-server/info?t=1600157059518是404，会出现disconnected from devServer trying to reconnect
我认为该404路径的正确路径应该是http://域名/tmr/dev-server/info?t=1600157059518，但实际并没有
即publicPath对dev-server心跳路径没起作用

**Comment by xiaohuoni** [comment]
请详细描述问题。

**Comment by 892744577** [comment]
publicPath设置了路径，如‘/tmr/’ 后能正常访问所有路径，但是只有这条路径http://域名/dev-server/info?t=1600157059518是404，会出现disconnected from devServer trying to reconnect

**Comment by conghuhu** [comment]
我也遇到了同样的问题，求解

**Comment by KingPengZero** [comment]
线上地址只支持publicPath或者base，不支持直接访问/，所以会遇到dev-server/info无法访问的情况，报404，

![image](https://user-images.githubusercontent.com/19372274/145136072-f4cea1eb-a740-4272-881b-5ff6a156f8e5.png)

**Comment by WuBin88996** [comment]
请问这个问题解决了吗 我也遇到了同样的问题
