### ISSUE TITLE
切换多语言，导致useSelector获取的store为undefined

### ISSUE THREAD

**Issue by hello-lun** [umijs/umi#5427]
问题：使用setLocale切换多语言后，导致useSelector获取的store的值为undefined

代码如下： 
![image](https://user-images.githubusercontent.com/34638158/93287524-56eead80-f80c-11ea-8098-d5349d5b63a2.png)

当我使用setLocale切换多语言的时候，console打印的store为undefined：
![image](https://user-images.githubusercontent.com/34638158/93287778-f57b0e80-f80c-11ea-89ae-7263d0d40438.png)

umijs版本： 3.2.16

**Comment by RedingSir** [comment]
相同问题：无刷新切换语言[setLocale(language, false)]会卸载store。

**Comment by justiceti** [comment]
我也遇到了相同的问题，请问是怎么解决的呢？ @sorrycc @hello-lun
