### ISSUE TITLE
IE11、IE10下 指定 targets polyfill无效

### ISSUE THREAD

**Issue by cc7gs** [umijs/umi#5428]
问题:配置 targets属性后，在IE下仍然没有完全 polyfill

配置如下:
 
![image](https://user-images.githubusercontent.com/36002392/93290667-cf0ca180-f813-11ea-9fb0-0f771efec1cc.png)

## 日志

![image](https://user-images.githubusercontent.com/36002392/93290698-df248100-f813-11ea-969b-f099b9cc604b.png)

## 相关环境信息

- **Umi 版本**：3.2.3
- **Node 版本**：12.13
- **操作系统**：window10

**Comment by xiaohuoni** [comment]
疑似相关的问题 https://github.com/umijs/umi/issues/3563

**Comment by xiaohuoni** [comment]
相关问题 https://github.com/umijs/umi/issues/4562

**Comment by Slebee** [comment]
同问，现在好像设了都没什么作用

**Comment by beside4ever** [comment]
@xiaohuoni 请问在排期处理了吗

**Comment by ycjcl868** [comment]
怎么来个最简复现

**Comment by KellenHe** [comment]
@ycjcl868 
yarn create @umijs/umi-app 生成的项目，添加了
`targets: {
    ie: 11,
  },`
别的一个代码没改，IE11跑不起来

**Comment by chenyuhu** [comment]
> @xiaohuoni 请问在排期处理了吗

同问，解决了吗？ umi3.x edge都无法打开

**Comment by cc7gs** [comment]
> > @xiaohuoni 请问在排期处理了吗
> 
> 同问，解决了吗？ umi3.x edge都无法打开

edge 可以打开的，我目前用的`umi@3.2.2`你配置下`nodeModulesTransform` -> type: all 试试

**Comment by chenyuhu** [comment]
> > > @xiaohuoni 请问在排期处理了吗
> > 
> > 
> > 同问，解决了吗？ umi3.x edge都无法打开
> 
> edge 可以打开的，我目前用的`umi@3.2.2`你配置下`nodeModulesTransform` -> type: all 试试

edge  没有问题，IE还是有点问题的

**Comment by quicklearning123** [comment]
同问

**Comment by a758801405** [comment]
> > > > @xiaohuoni 请问在排期处理了吗
> > > 
> > > 
> > > 同问，解决了吗？ umi3.x edge都无法打开
> > 
> > 
> > edge 可以打开的，我目前用的`umi@3.2.2`你配置下`nodeModulesTransform` -> type: all 试试
> 
> edge 没有问题，IE还是有点问题的

ie11能显示，但是还有有报错，跳转什么的也有问题，plugin-model: Invoking '@@initialState' model failed: TypeError: 对象不支持此操作

**Comment by quicklearning123** [comment]
> > > > > @xiaohuoni 请问在排期处理了吗
> > > > 
> > > > 
> > > > 同问，解决了吗？ umi3.x edge都无法打开
> > > 
> > > 
> > > edge 可以打开的，我目前用的`umi@3.2.2`你配置下`nodeModulesTransform` -> type: all 试试
> > 
> > 
> > edge 没有问题，IE还是有点问题的
> 
> ie11能显示，但是还有有报错，跳转什么的也有问题，plugin-model: Invoking '@@initialstate' model failed: TypeError: 对象不支持此操作


我也是这样的 IE11
SCRIPT1002: 语法错误
devScripts.js (25,5)
plugin-model: Invoking '@@initialstate' model failed: TypeError: 对象不支持此操作

**Comment by afc163** [comment]
Duplicate of #5660
