### ISSUE TITLE
非根目录下，build后，即使配置了base项，也是错的

### ISSUE THREAD

**Issue by gaomeng965** [umijs/umi#5429]
## What happens?

umi3项目build后 在根目录下一切正常，
但是在非根目录下，比如  我按照文档 配置了base项为  '/saasManage/', 但是打包后的html 文件中对 umi.js和umi.css文件的引入是  ：
```
<link rel="stylesheet" href="/umi.css" />
-------
window.routerBase = "/saasManage/";
-------
<script src="/umi.js"></script>
-------
```
这是第一个问题， 应该为  ./umi.js  或 ./umi.css  不然一定404
即使我自己直接修改html后变为 ./  但是按需加载的其它js 也是同样的问题指向 根目录 。

umi的官方文档里是这样说的：
```
怎么解决？

可通过配置 base 解决。

export default {
  base: '/path/to/your/app/root',
};
```
但这个也是加上 /  即base: '/path/to/your/app/root/',才对吧， 

请问这种到底该如何解决？  

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：^3.0.0
- **Node 版本**：v13.7.0
- **操作系统**：mac os

**Comment by gaomeng965** [comment]
base: '/saasManage/',
  outputPath: './dist/saasManage',
  publicPath: '/saasManage/',

得同时配置publicPath  才可以
项目最终的部署是重中之重，，希望可以完善修复下这方面的文档。谢谢

**Comment by xiaohuoni** [comment]
base 是设置路由前缀，通常用于部署到非根目录。
publicPath 是打包的时候静态文件路径前缀。这两个并不一定一样的。
@gaomeng965 欢迎帮忙补充一下文档。

**Comment by sorrycc** [comment]
base 和 publicPath 是两个概念，部署文档在 https://umijs.org/zh-CN/docs/deployment 有详细写。

**Comment by tankpanv** [comment]
> base: '/saasManage/', outputPath: './dist/saasManage', publicPath: '/saasManage/',
> 
> 得同时配置publicPath 才可以 项目最终的部署是重中之重，，希望可以完善修复下这方面的文档。谢谢



> 
你好，请问一下
base: '/saasManage/',
outputPath: './dist/saasManage',
publicPath: '/saasManage/',
这里/saasManage/ 的路径是绝对路径吗。比如我

**Comment by tankpanv** [comment]
> base: '/saasManage/', outputPath: './dist/saasManage', publicPath: '/saasManage/',
> 
> 得同时配置publicPath 才可以 项目最终的部署是重中之重，，希望可以完善修复下这方面的文档。谢谢
你好请问这里 
base: '/saasManage/',
outputPath: './dist/saasManage',
publicPath: '/saasManage/',

publicPath 路径 是绝对路径吗 '/saasManage/',
比如我部署的路径是 在 /Users/tp/HBuilderProjects/cube 下。这个应该怎么填呢，是

base: '/saasManage/',
outputPath: './dist/saasManage',
publicPath: ' /Users/tp/HBuilderProjects/cube/',
吗

**Comment by pxim** [comment]
umi3 配置  base: './' 没问题，效果正常

umi4 base配置  base: './', 直接 白屏 和 什么重定向太多

**Comment by beikeliu** [comment]
应该设置publicPath: './'
