### ISSUE TITLE
Extremely low performance because of browserify process: react-pdf is way too slow!

### ISSUE THREAD

**Issue by mleister97** [umijs/umi#5433]
As I already asked on stackoverflow.com, please the likely problem here: https://stackoverflow.com/a/63976087/12900361

**Comment by mleister97** [comment]
@chenshuai2144

Have you got any idea whats causing the issue? I really consider removing umi-js from my project, even tough it got many really nice features... Would be sad :(

**Comment by mleister97** [comment]
Please see the explanation of the issue here: https://stackoverflow.com/a/63976087/12900361

**Comment by mleister97** [comment]
As no one is interrested in this really fatal issue I decided to remove umi completely of my project.

**Comment by 8cells** [comment]
@mleister97 
I was able to fix it:
https://stackoverflow.com/a/67255527/15726758

**Comment by mleister97** [comment]
Thanks a lot. But as this is already some months ago I will keep the way not using umi.
Accepted and upvoted your answer, have a good day!
