### ISSUE TITLE
/@umijs/bundler-webpack包下的webpackHotDevClient.js的initSocket()方法路径写死了

### ISSUE THREAD

**Issue by 892744577** [umijs/umi#5435]
function initSocket() {
          var host = getSocketHost();
          sock = new entry_default.a(''.concat(host, '/dev-server'));   *

          sock.onopen = function () {
            var _pending, _pending$parentElemen;

            retries = 0;
            (_pending = pending) === null || _pending === void 0
              ? void 0
              : (_pending$parentElemen = _pending.parentElement) === null ||
                _pending$parentElemen === void 0
              ? void 0
              : _pending$parentElemen.removeChild(pending);
          };

中sock = new entry_default.a(''.concat(host, '/dev-server'));   **//这里路径只能是 http://host/dev-server，如果我使用nginx代理非根目录会导致报错，出现连接异常，出现 Disconnected from the devServer...

**Comment by sorrycc** [comment]
已修复。
