### ISSUE TITLE
antd表格组件，加了scroll之后,表头与第一行数据中间有空隙；合并表格行之后，行内内容不再垂直居中.

### ISSUE THREAD

**Issue by QJerryxjh** [umijs/umi#5436]
## What happens?
antd的table组件，加了scroll之后，表头与第一行数据之间有空隙；
表格合并行，合并之后的单元格内容不再垂直居中。
原来表现符合预期的代码，将依赖包及pack-lock文件删除重装之后，也出现了该问题，在其表现正常的时候与表现不正常的时候antd的版本都为4.6.4,rc-table版本都为7.9.9。

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
使用antd的table组件，为其加scroll={{ x: 800 }},UI将出现空隙；合并某列的两行单元格，合并后的单元格内容不垂直居中。（或需要删除依赖包及lock文件重新安装依赖）

**Expected behavior** 1. 2.
表头与数据之间不出现空隙，合并后的单元格垂直居中

## Context

- **Umi Version**: 3.2.20
- **Node Version**: 12.18.3
- **Platform**:

**Comment by QJerryxjh** [comment]
![image](https://user-images.githubusercontent.com/39372547/93431037-28e59800-f8f6-11ea-9c85-0ee5d588def0.png)

**Comment by xiaohuoni** [comment]
请到 antd 区提交 https://github.com/ant-design/ant-design/issues

**Comment by QJerryxjh** [comment]
是我弄错了
