### ISSUE TITLE
开启ssr之后如何让第三方依赖不在服务端 import

### ISSUE THREAD

**Issue by awang0608** [umijs/umi#5438]
部分第三方插件依赖于window或document，服务端要报错
![image](https://user-images.githubusercontent.com/35441582/93447785-66055680-f905-11ea-9700-09b5ca602b46.png)

**Comment by ycjcl868** [comment]
`beforeRenderServer `可以来做一些渲染前 polyfill，https://umijs.org/docs/ssr#polyfill

**Comment by ycjcl868** [comment]
这部分也可以后面增加一个配置 `globals` 或者 `polyfill` 来解决这类问题

**Comment by awang0608** [comment]
好的，谢谢，顺便问一下，关于disableExternal的配置是被关掉了咩？怎么现在这个配置没有出现在官方文档里了，types里面也没有这个配置
![image](https://user-images.githubusercontent.com/35441582/93450301-62270380-f908-11ea-963d-6dadf5701220.png)
![image](https://user-images.githubusercontent.com/35441582/93450322-6b17d500-f908-11ea-9577-2808780dbd19.png)

umi版本： "umi": "^3.2.10",

**Comment by awang0608** [comment]
beforeRenderServer的参数里也只有location和history呀，没有完整的window和document

**Comment by itellyou-com** [comment]
> beforeRenderServer的参数里也只有location和history呀，没有完整的window和document

自己定义的window和document的话，很多库，包括antd和umijs的代码都有判断 window !== 'undefined' ，如果你给了的话，他们会执行这部分代码，导致错误更多，我试过的。。。那还用了 jsdom 模拟取得window对象，只会出现更多的错误。我目前的解决办法是https://umijs.org/zh-CN/docs/load-on-demand#%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD%E7%BB%84%E4%BB%B6-dynamic 使用异步组件读取那些无法在ssr下渲染的库

**Comment by ycjcl868** [comment]
> 好的，谢谢，顺便问一下，关于disableExternal的配置是被关掉了咩？怎么现在这个配置没有出现在官方文档里了，types里面也没有这个配置
> ![image](https://user-images.githubusercontent.com/35441582/93450301-62270380-f908-11ea-963d-6dadf5701220.png)
> ![image](https://user-images.githubusercontent.com/35441582/93450322-6b17d500-f908-11ea-9577-2808780dbd19.png)
> 
> umi版本： "umi": "^3.2.10",

umi 3 默认就是 disableExternal 的
