### ISSUE TITLE
plugin-model: Invoking '@@initialState' model failed: TypeError

### ISSUE THREAD

**Issue by zhangxiaofeng87** [umijs/umi#5439]
ie11下报这个错误是什么问题

**Comment by memerylihong** [comment]
> ie11下报这个错误是什么问题

同问啊

**Comment by quicklearning123** [comment]
同问

**Comment by yulongcs** [comment]
同问

**Comment by sorrycc** [comment]
已修复。

**Comment by qingxiao** [comment]
> 已修复。

umi@3.3.7 +   @umijs/plugin-qiankun@2.21.2
在ie下还是报这个错误
![image](https://user-images.githubusercontent.com/3422905/105688188-42e25780-5f34-11eb-968a-e4337340c598.png)

**Comment by chenghangcong** [comment]
> 已修复。

请问是哪个版本修复了，我现在3.3.7还是报错

**Comment by LiuJinYang9527** [comment]
目前还有问题  umi版本3.3.7

**Comment by YUD1112** [comment]
umi 3.3.7 
ie11 报错：plugin-model: Invoking '@@initialState' model failed: TypeError：对象不支持此操作

**Comment by tangeleven** [comment]
"umi": "^3.1.2"
ie11 报错：plugin-model: Invoking '@@initialState' model failed: TypeError: 对象不支持此操作

**Comment by ZhaoXueJing** [comment]
> "umi": "^3.1.2"
> ie11 报错：plugin-model: Invoking '@@initialstate' model failed: TypeError: 对象不支持此操作

能问下你，你这个问题解决了吗

**Comment by ZhaoXueJing** [comment]
> umi 3.3.7
> ie11 报错：plugin-model: Invoking '@@initialstate' model failed: TypeError：对象不支持此操作

能问下你，你这个问题解决了吗

**Comment by memerylihong** [comment]
这个问题不影响使用，不过我也没解决哈哈------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月17日(星期三) 中午11:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umijs/umi] plugin-model: Invoking &#39;@@initialState&#39; model failed: TypeError (#5439)
