### ISSUE TITLE
模块“"umi"”没有导出的成员“getLocale”

### ISSUE THREAD

**Issue by BigGoblin** [umijs/umi#5444]
## What happens?

 模块“"umi"”没有导出的成员“getLocale”

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

![image](https://user-images.githubusercontent.com/27881216/93566821-38311800-f9c0-11ea-902f-6055116c37dd.png)

## 相关环境信息

- **Umi 版本**：3.2.20
- **Node 版本**：14.8.0
- **操作系统**：windows

**Comment by xiaohuoni** [comment]
看起来需要安装 locale 插件才行，你装了嘛？

**Comment by ycjcl868** [comment]
https://umijs.org/plugins/plugin-locale
