### ISSUE TITLE
umi3 layout/index.tsx 中注入ApolloProvider 无法启动，放在pages/index.tsx就正常

### ISSUE THREAD

**Issue by yzStrive** [umijs/umi#5445]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

https://github.com/yzStrive/umi-apollo-client

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:3.2.20
- **Node Version**:v12.18.3
- **Platform**:macOS

**Comment by yzStrive** [comment]
解决了https://umijs.org/zh-CN/docs/runtime-config#rootcontainerlastrootcontainer-args
不要被 https://umijs.org/zh-CN/guide/migrating-create-react-app-to-umi#%E4%BF%AE%E6%94%B9%E6%A0%B9%E7%BB%84%E4%BB%B6 误导了

**Comment by xiaohuoni** [comment]
@yzStrive 怎么误导？

**Comment by qinyuhua** [comment]
> 解决了https://umijs.org/zh-CN/docs/runtime-config#rootcontainerlastrootcontainer-args 不要被 https://umijs.org/zh-CN/guide/migrating-create-react-app-to-umi#%E4%BF%AE%E6%94%B9%E6%A0%B9%E7%BB%84%E4%BB%B6 误导了

这个是如何使用的？
