### ISSUE TITLE
exportStatic开启后，windows 下无法打包动态路由

### ISSUE THREAD

**Issue by 1089109** [umijs/umi#5446]
`import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  hash: true,
  outputPath: './dist',
  publicPath: '/',
  ignoreMomentLocale: true, // 忽略 moment 的 locale 文件，用于减少尺寸
  inlineLimit: 10, // 配置图片文件是否走 base64 编译的阈值。默认是10000 (10k)字节，少于他会被编译为 base64 编码，否则会生成单独的文件
  // dynamicImport: {}, // 是否启用按需加载，即是否把构建产物进行拆分，在需要的时候下载额外的 JS 再执行
  exportStatic: { // 路由以.html访问
    htmlSuffix: true, // 不要二级目录名，生成类似index.html
    // dynamicRoot: true,
  },
  routes: [
    { 
      path: '/demo2', 
      component: '@/layout/Demo2', 
      routes: [
        { path: '/demo2/ds', component: '@/pages/demo2/ds.tsx', title: 'demo2 动态路由 ID ds'},
        { path: '/demo2/:id', component: '@/pages/demo2/[id].tsx', title: 'demo2 动态路由 ID'},
        { path: '/demo2/', redirect: '/demo2/ds' },
      ]
    },
    { path: '/demo1', component: '@/pages/demo1', title: 'demo1' },
    { path: '/', component: '@/pages/demo.tsx', title: 'demo' },
    // { path: '/', component: '@/pages/index' },
  ],

  // ssr: {
  //   forceInitial: true,
  //   devServerRender: true,
  //   mode: 'stream', // 提供开箱即用的流式渲染功能
  //   staticMarkup: true,  // html 片段静态标记（适用于静态站点生成）
  // },
});
`

这是我的配置文件

然后报了这个错，请问应该怎么解决

>
![image](https://user-images.githubusercontent.com/52598593/93657056-c14c5b80-fa61-11ea-8767-73686b8cabb3.png)

**Comment by 1089109** [comment]
![image](https://user-images.githubusercontent.com/52598593/93657052-b42f6c80-fa61-11ea-848c-cb958ad70761.png)

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/93727765-41ec9280-fbef-11ea-8f33-4cd76e7f81ba.png)

**Comment by ycjcl868** [comment]
已知问题

**Comment by xrkffgg** [comment]
试试这个 https://github.com/xrkffgg/umi-win-exportStatic

**Comment by sorrycc** [comment]
参考 https://github.com/umijs/umi/issues/5921#issuecomment-754601670
