### ISSUE TITLE
打包后 umi.js 加载不完整 

### ISSUE THREAD

**Issue by luoxuefengs** [umijs/umi#5449]
![image](https://user-images.githubusercontent.com/68887680/93729750-6a2cbf00-fbf8-11ea-8c60-591e1e492e72.png)
打包后 umi.js文件在服务器渲染的时候，莫名其妙的被浏览器 截取掉了一部分，是什么情况？

**Comment by xiaohuoni** [comment]
确认一下服务器上的文件是否完整
