### ISSUE TITLE
windows 启动 dev 服务器，路径错误

### ISSUE THREAD

**Issue by tindytian** [umijs/umi#545]
umi 版本 v1.3.4

![image](https://user-images.githubusercontent.com/4383871/40519995-7dd45db6-5ff5-11e8-9d1f-3e457f89c573.png)

**Comment by xiaohuoni** [comment]
是不是版本没装好？插件重装一下。（微笑）

**Comment by xiaohuoni** [comment]
提供一下你的版本吧！其他插件

**Comment by sorrycc** [comment]
好像是不同盘符时的问题，把 umi 安装在项目里可以绕过。

**Comment by xiaohuoni** [comment]
不是啊，我这表现是不在项目中，根本不能运行

**Comment by sorrycc** [comment]
试试把 af-webpack/src/getConfig.js 里把 debugLoader 注释掉，是否可以？

**Comment by tindytian** [comment]
把debugLoader 注释掉之后 dynamic.js 找不到
![image](https://user-images.githubusercontent.com/4383871/40522633-7358cfa2-6004-11e8-909e-3433eacd5833.png)
我的目录结构用dva-cli@next生成的
我把umi装到项目里面试试

**Comment by xiaohuoni** [comment]
存在 https://github.com/umijs/umi/issues/546 
没办法重现这个问题

**Comment by realeve** [comment]
umi 1.3.4，刚全局升级后遇到一样的问题，用得很心累。

**Comment by sorrycc** [comment]
在 win@10 下测了下，没法重现这个问题啊。

**Comment by sorrycc** [comment]
@tindytian 你是啥系统？

**Comment by xiaohuoni** [comment]
@tindytian 麻烦全局用cross-env HARD_SOURCE=none umi dev看看还有没有这个问题。

**Comment by sorrycc** [comment]
有问题再 reopen 。
