### ISSUE TITLE
umijs3 global.css失效

### ISSUE THREAD

**Issue by songyizhe** [umijs/umi#5450]
## What happens?
通过脚手架创建的umijs3项目，创建后没有global.css文件，然后手动创建，但是发现在里面添加样式是失效的

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
刚新建完，需要重启服务

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/4039#issuecomment-694741255
如果是权重问题，参考其他的回复。

**Comment by songyizhe** [comment]
> 刚新建完，需要重启服务

你好，重启服务也是不行，我想在global.css中修改body的样式，但是是无效的，好像是没有引用到
