### ISSUE TITLE
alias配置后无效，编辑器运行报错

### ISSUE THREAD

**Issue by hello-lun** [umijs/umi#5451]
问题：alias配置后无效，编辑器运行报错
1、umijs配置如下：
![image](https://user-images.githubusercontent.com/34638158/93731273-e924f600-fbfe-11ea-81c6-59dab01fe877.png)

2、业务代码中使用：
![image](https://user-images.githubusercontent.com/34638158/93731291-f7731200-fbfe-11ea-9054-e8cc1a93eda9.png)

3、编辑器报错：
![image](https://user-images.githubusercontent.com/34638158/93731300-ffcb4d00-fbfe-11ea-8f60-25e811d4c62e.png)

什么情况呢

**Comment by github-ace** [comment]
怎么解决的，朋友

**Comment by kampiu** [comment]
我也想知道

**Comment by pxim** [comment]
同样的问题
