### ISSUE TITLE
Windows 使用全局umi执行umi dev

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#546]
```js
Failed to compile.

Cannot read property '0' of undefined
```

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi-examples/issues/16#issuecomment-391603456

**Comment by xiaohuoni** [comment]
经定位，错误执行到
https://github.com/umijs/umi/blob/c09913ba2ee35b25e0bb9cf88a092582a8e76fe0/packages/af-webpack/src/WebpackDevServerUtils.js#L108

**Comment by xiaohuoni** [comment]
任意项目可重现

**Comment by xiaohuoni** [comment]
umi版本1.3.4

**Comment by sorrycc** [comment]
和 #545 重复，在一个地方跟进就好。

**Comment by xiaohuoni** [comment]
我不确定是一个问题！包括#493 #443

**Comment by BayesZou** [comment]
macOS 系统下，dva-cli@next 生成的项目，使用全局的 `umi` 运行 `umi dev` 出现一样的问题, 报错 `Cannot read property '0' of undefined`；
运行 `npx umi dev` 使用项目内部的 umi 则可以正常启动。
umi 版本都为 1.3.4

**Comment by sorrycc** [comment]
@BayesZou dva-cli 版本是 1.0.0-beta.4 ? 我在 mac 下试了下如下步骤，不能重现。

```bash
$ npm i dva-cli@next -g
$ dva -v
dva-cli version 1.0.0-beta.4
$ dva new myapp
$ cd myapp
$ npm start
```

**Comment by BayesZou** [comment]
@sorrycc 版本是 1.0.0-beta.4，`npm start` 使可以运行的，但是直接运行 `umi dev` 会报错

**Comment by xiaohuoni** [comment]
@sorrycc 这个问题就是umi没有安装在项目中才有的。

**Comment by sorrycc** [comment]
你全局还有一个 umi? 是什么版本的？

**Comment by xiaohuoni** [comment]
都是最新的

**Comment by BayesZou** [comment]
@sorrycc 项目中和全局都是 1.3.4

**Comment by sorrycc** [comment]
node 版本呢？

**Comment by BayesZou** [comment]
@sorrycc v10.1.0

**Comment by sorrycc** [comment]
试过 mac 和 windows 系统，用 dva-cli@next 新建项目，然后用全局 umi(1.3.4) 和项目本地 umi (1.3.4) 启动，都正常，无法重现。

mac 下试过 10.1.0 也没问题。。

**Comment by xiaohuoni** [comment]
@sorrycc 应该是引入HardSourceWebpackPlugin导致的
https://github.com/umijs/umi/blob/3b055e0db496e118f61bf637a08735d90208ab95/packages/af-webpack/src/getConfig.js#L513

```js
: [new HardSourceWebpackPlugin()]),
```
```js
: []),
```
上述修改，可以修复这个问题。
使用cross-env HARD_SOURCE=none  umi dev
可启动项目

**Comment by xiaohuoni** [comment]
相关BUG https://github.com/mzgoddard/hard-source-webpack-plugin/issues/329

**Comment by guyunxiang** [comment]
楼上正解，这两天用umi@1.3.4全局运行，umi 报同样问题，cross-env HARD_SOURCE=none umi dev可正常启动

**Comment by sorrycc** [comment]
umi@1.3.5 应该已修复此问题。
