### ISSUE TITLE
开启dynamicImport loading能否禁用

### ISSUE THREAD

**Issue by eevin** [umijs/umi#5460]
umi3 开启dynamicImport loading能否禁用
官方FAQ说明 给 dynamicImport 配置加上 loading: '() => <></>'
即使这样使用还是有闪烁，这样体验太差了，特别是在移动端。

**Comment by sorrycc** [comment]
既然开了按需加载，肯定是一个异步的过程，有 loading 正常吧。

**Comment by ouzhou** [comment]
@sorrycc 

https://umijs.org/zh-CN/plugins/plugin-initial-state#usemodel
正常流程是在app.tsx里面发起异步请求获取当前用户权限，然后在wrappers里面对路由进行拦截，文档里面说有个loading可以使用
```
const { initialState, loading } = useModel('@@initialState');
```
这个loading 和 dynamicImport的loading区别是什么
我反复测试过低网速，这个loading永远为false，什么情况下会导致loading为true呢

**Comment by hoivee** [comment]
> 既然开了按需加载，肯定是一个异步的过程，有 loading 正常吧。

我也有这个需求，场景是这样的，项目开启ssr，同时开启dynamicImport，在首次打开页面的时候，因为显示loading导致页面会白屏闪动一下，很影响体验，能否给一个开启dynamicImport后不展示loading的配置

**Comment by leftstick** [comment]
我觉得 `loading: '() => <></>'` 的思路没问题。

闪烁是不是因为，组件还没加载完毕时，缺失部分又是一个空的`<></>` ，导致这部分布局坍塌，等加载完毕后又撑起来了，产生了闪烁的感觉？

**Comment by gujintao1900** [comment]
1. 你需要的loading骨架屏方案，替换首页 loading <></>方案
2. 白屏闪动，主要问题在于你的loading是个<></>那肯定有白屏，而且由于内容没有预先占位（骨架可以帮你提前撑开），所以还会有抖动的过程

**Comment by eevin** [comment]
骨架屏只是解决内容部分渲染不一造成抖动。这里是页面js代码加载异步的loading。
由于我是移动H5开发，抖动比较明显。
最终处理方式是：组件初始加载设置页面透明opacity: 0;组件加载完成后开始页面入场动画。已经看不到闪一下了。

**Comment by fyxwanan** [comment]
umi.js如果没有下载完的话，就会出现一段白屏。如果在弱网的情况下，比如移动端，就会白屏很长一段时间，然后用户体验会很差，有什么可以优化的方案吗？

**Comment by ouzhou** [comment]
那你不如自己在html上写一个css loading, umi.js加载完成后移除掉， 然后看 umi调用自己的dynamicImport loading

**Comment by Does666** [comment]
开启dynamicImport loading能禁用吗？不禁用的话，提示信息“loading”及样式能修改吗？

**Comment by tankpanv** [comment]
> 开启dynamicImport loading能禁用吗？不禁用的话，提示信息“loading”及样式能修改吗？

我也遇到了这个问题，你这边找到解决方案了吗。我想开启dynamicImport loading 修改提示信息“loading”及样式，但是不知道怎么修改

**Comment by javanoclaw** [comment]
应该开启路由页面 prefetch,如
import(/* webpackPrefetch: true */ '@/features/SearchResult'))
