### ISSUE TITLE
umi3热更新速度问题

### ISSUE THREAD

**Issue by whereiscode** [umijs/umi#5463]
我的所有路由估计有100个界面吧 ，每次任意改个代码热更新就要5-6s，我觉得挺慢的
但是当我把路由删除，只留我要修改的那个界面，编译速度只需要300ms，这是相当快的

我想啊能不能只编译改的那个文件呢，其他router不要重新编译了，或者现在就有，我不知道呢？

**Comment by whereiscode** [comment]
我用的是umi最新版本

**Comment by jin-benben** [comment]
> 我用的是umi最新版本

所你是怎么解决的？

**Comment by jiechud** [comment]
@whereiscode 你是用什么方法解决的呢

**Comment by 104gogo** [comment]
先把不用的路由手动注释了。。就贼快了
