### ISSUE TITLE
"export 'getCreateHistoryOptions' was not found in './history'。

### ISSUE THREAD

**Issue by LeoWang1991** [umijs/umi#5464]
## What happens?
![image](https://user-images.githubusercontent.com/22044609/93872285-84eb5a80-fd02-11ea-850d-4894980335ec.png)

当引用 Link这个api时候 会出现这个warning，虽然不影响运行。

## How To Reproduce

`import { Link } from 'umi'` 引用Link api时候会出现这个warning

## Context

- **Umi Version**: 3.2.8
- **Node Version**: 10.13.0
- **Platform**: macOS 10.14.6

**Comment by chhpt-blog** [comment]
出现了同样的问题

**Comment by Justin-lu** [comment]
https://github.com/umijs/umi/commit/f692219a05b0524462f64cf4fb6f242c7193c8ac

看代码已经更新，重装一下即可
