### ISSUE TITLE
约定式路由，未设置routes，pages下的页面除了index其他都不渲染

### ISSUE THREAD

**Issue by qwe9527** [umijs/umi#5466]
按照文档配置，.umirc.ts中未设置routes，在pages目录下新建页面，如下
![image](https://user-images.githubusercontent.com/23071889/93956909-c244fc00-fd85-11ea-95c5-134170177210.png)

访问`/manage/emeter/realtime`未渲染realtime页面内容，访问`/`可以正常渲染index页面
可复现demo [https://github.com/qwe9527/umi-example.git](https://github.com/qwe9527/umi-example.git)

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/93958755-c70baf00-fd89-11ea-900d-9d56ca5016bb.png)
不是可以的吗？
