### ISSUE TITLE
使用了layout配置后控制台弹出很多警告⚠️

### ISSUE THREAD

**Issue by ouzhou** [umijs/umi#5468]
## What happens?

新建项目 umirc.ts 中开启 layout:{}
控制台启动后会抛出很多警告，但是能正常使用

```
 WARNING  Compiled with 8 warnings                                                                                                     19:49:43

 warning  in ./src/.umi/plugin-layout/layout/layout/renderRightContent.tsx

"export 'SelectLang' was not found in 'umi'

 warning  in ./src/.umi/plugin-layout/layout/layout/renderRightContent.tsx

"export 'SelectLang' was not found in 'umi'

 warning  in ./src/.umi/plugin-layout/layout/utils/intl.ts

"export 'getLocale' was not found in 'umi'

 warning  in ./src/.umi/plugin-layout/layout/layout/index.tsx

"export 'useIntl' was not found in 'umi'

 warning  in ./src/.umi/plugin-layout/layout/layout/index.tsx

"export 'useIntl' was not found in 'umi'

 warning  in ./src/.umi/plugin-layout/layout/utils/intl.ts

"export 'useIntl' was not found in 'umi'
```

## 期待结果

去除掉这些不影响结果的警告消息
 
- **Umi 版本**：3
- **Node 版本**：
- **操作系统**：

**Comment by wangyuan0108** [comment]
貌似是默认开启了多语言的功能，然后又没有相应的配置，感觉像是布局插件的问题

**Comment by gujintao1900** [comment]
1. 麻烦阅读 https://umijs.org/zh-CN/plugins/preset-react
2. 检查 package.json 是否包含相应插件
![image](https://user-images.githubusercontent.com/48408513/94353227-15c68b00-00a1-11eb-9ccf-8499d1212760.png)

**Comment by wb1018** [comment]
这个就是 @ant-design/pro-layout组件默认无法关闭国际化
![国际化](https://user-images.githubusercontent.com/63702670/95718055-7d372a00-0ca0-11eb-878d-1fdc37aab29d.png)；

解决方案
`
// 开启国际化插件
locale: {
    default: 'zh-CN'
  },
// 设置@ant-design/pro-layout语言为简体中文
layout: {
  locale: 'zh-CN'
}
`

**Comment by wb1018** [comment]
就是 @umijs/plugin-layout 和 @ant-design/pro-layout组件的原因，这两中local的类型和取值不同，根据测试得出还是一@ant-design/pro-layout的配置为主

在 @umijs/plugin-layout 中配置
![国际化002](https://user-images.githubusercontent.com/63702670/95720470-dce30480-0ca3-11eb-804b-6153ebd60fcf.png)

在 @ant-design/pro-layout 中配置方式
![国际化](https://user-images.githubusercontent.com/63702670/95719967-31d24b00-0ca3-11eb-8303-a6947d488162.png)

**Comment by Ray-56** [comment]
@gujintao1900 
![](https://raw.githubusercontent.com/Ray-56/image-service/master/picgo20201120/162854.png)
是有的，但是还是有提示
![](https://raw.githubusercontent.com/Ray-56/image-service/master/picgo20201120/162955.png)

**Comment by zhixinpeng** [comment]
我是第一次使用umi，我按照官网的快速上手来走一遍，也发现了这个问题，另外 @ant-design/pro-layout 好像是一开始就有的，并不需要自己再去安装。这初体验确实太影响第一印象了。

**Comment by Witee** [comment]
我的解决办法是增加: `locale: {}`

```
// .umirc.ts
export default defineConfig({
  ...
  layout: {
    locale: false,
  },
  locale: {},
})
```
