### ISSUE TITLE
能否在service中支持传入headers信息

### ISSUE THREAD

**Issue by LOVEwitch** [umijs/umi#5472]
## Background

根据接口的不同，传入不同的header信息

## Proposal

希望能够在service.ts中支持传入header信息，而不用在request.ts中做统一处理

**Comment by xiaohuoni** [comment]
可以的。直接传就会生效的。

**Comment by LOVEwitch** [comment]
> 可以的。直接传就会生效的。

嗯啊，之前版本太低了，直接传有问题，升级版本后可以了
