### ISSUE TITLE
动态设置 Open Graph protocol og:url 属性

### ISSUE THREAD

**Issue by shangdev** [umijs/umi#5474]
想让网站加上OPG属性，这样分享时更直观。
目前了解到只能在 .umijs.rc 的metas中写死配置，如：
```
  metas: [
    {
      property: 'og:url',
      content: 'http://xxx.com/',
    },
  ],
```

现有功能支持动态设置该OPG属性吗？

**Comment by anakornk** [comment]
Umi 支持SSR 可以参考 https://umijs.org/zh-CN/docs/ssr
也可以自己实现 Dynamic Rendering 
https://developers.google.com/search/docs/guides/dynamic-rendering

**Comment by gujintao1900** [comment]
你需要的是动态修改meta标签，请使用 https://umijs.org/zh-CN/plugins/plugin-helmet ， 支持SSR的

![image](https://user-images.githubusercontent.com/48408513/94353306-35aa7e80-00a2-11eb-82ca-29d9fa3fdca5.png)

**Comment by shangdev** [comment]
@gujintao1900 

使用Helmet后生成的htmk多了data-react-helmet属性：
![image](https://user-images.githubusercontent.com/15621520/94407282-dcc40e80-01a5-11eb-959d-c702337f83b7.png)

有什么办法可以不显示这多余的属性吗？

**Comment by gujintao1900** [comment]
`data-*` 属于HTML规范的[自定义数据属性](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Global_attributes/data-*)，不影响SEO结果的
