### ISSUE TITLE
一个子应用使用<MicroApp /> 嵌套多个子应用，在子应用直接切换，第一次渲染都是好的，第二次渲染全部报错，没有导出lifecycle

### ISSUE THREAD

**Issue by fatehuanchen** [umijs/umi#5475]
## What happens?
一个子应用使用<MicroApp /> 嵌套多个子应用，通过路由在子应用之间切换，第一次渲染都是好的，第二次渲染全部报错，没有导出lifecycle

## 最小可复现仓库
https://github.com/brickspert/umi-micro-apps.git  

## 复现步骤，错误日志以及相关配置
按readme启动项目后，在http://localhost:8000/shop/2  页面点击管理员设置，第一次成功渲染，第二次报错
loader.js:204 Uncaught (in promise) Error: [qiankun] You need to export lifecycle functions in user entry

## 相关环境信息

- **Umi 版本**：最新
- **Node 版本**：12.9.1
- **操作系统**：mac os

**Comment by lomocc** [comment]
https://github.com/kuitos/import-html-entry/blob/master/src/index.js#L167
这个地方第二次执行结果变成空对象了。

**Comment by lomocc** [comment]
https://github.com/kuitos/import-html-entry/blob/master/src/utils.js#L32
看到这些黑科技我有点想哭。

**Comment by fatehuanchen** [comment]
https://github.com/kuitos/import-html-entry/blob/master/src/utils.js#L56  是的，每次loadMicroApp，往父global上挂载最新的子window对象，子内切换，总是会覆盖，最终只有最后加入的子应用可以重复渲染，其余全部抛出undefined，导致lifecycle报错

**Comment by fatehuanchen** [comment]
是不是不允许，子应用嵌套子应用？？？

**Comment by lomocc** [comment]
我简单修改了一下，可以暂时使用：
```
yarn add import-html-entry@npm:@tcfuture/import-html-entry
```
来修复这个问题（可能需要删除 node_modules 重新安装）。

**Comment by fatehuanchen** [comment]
![image](https://user-images.githubusercontent.com/20472185/94353713-c2efd200-00a6-11eb-8214-6f06d4f7b1c1.png)
![image](https://user-images.githubusercontent.com/20472185/94353721-dc911980-00a6-11eb-832e-2694ff50a740.png)
好像并未起效果，当再次进入的时候，还是会报错，看代码也并未修改逻辑，且如果一个子应用嵌套多个孙子应用，是否umi的逻辑就存在问题？

**Comment by lomocc** [comment]
你确保一下 **node_modules/qiankun/node_modules/import-html-entry** 这个目录不存在哈（用**node_modules/import-html-entry** 代替它），我这边是可以的。
有可能没替换成功，umi 依赖比较杂，可能放到子目录去了就没办法替换。
确保在 yarn.lock 里可以找到类似以下配置：
```
import-html-entry@^1.9.0, "import-html-entry@npm:@tcfuture/import-html-entry":
  version "1.9.2"
  resolved "http://r.tnpm.oa.com/@tcfuture/import-html-entry/download/@tcfuture/import-html-entry-1.9.2.tgz#cd083f71e90597a3f9baeb772c63e11537651922"
  integrity sha1-zQg/cekFl6P5uut3LGPhFTdlGSI=
  dependencies:
    "@babel/runtime" "^7.7.2"
```

**Comment by fatehuanchen** [comment]
删除了 node_modules/qiankun/node_modules/import-html-entry 这个后，是成功了，子应用互相嵌套可以实现，后面会考虑把这个修复到qiankun里吗，因为我们是使用的umi，依赖qiankun，后续想通过升级版本来处理此问题
