### ISSUE TITLE
热更新不起作用了，我并没有关闭热更新

### ISSUE THREAD

**Issue by 521guyu** [umijs/umi#5477]
我的项目初期可以热更新，到了后期项目庞大起来热更新就不起作用了，每次都要npm start一下才可以，很苦恼。

**Comment by sorrycc** [comment]
给复现步骤。

**Comment by 521guyu** [comment]
> 给复现步骤。


我保存文件能检测到变化文件但是就是不重新编译
umi版本2.8.7  node版本12.18.3

**Comment by kicktech** [comment]
能问下你是怎么解决的吗

**Comment by renwangT** [comment]
我的是重新编译了， 页面不刷新， 每次都要 F5 自己手动刷新
