### ISSUE TITLE
热更新可以监听到文件变化，不自动编译

### ISSUE THREAD

**Issue by 521guyu** [umijs/umi#5478]
我保存文件能检测到变化文件但是就是不重新编译,
debug [change] config/config.js（我改变那个文件change后就是那个文件），我猜想可以检测到文件变化，但是有东西阻止了重新编译
[https://ask.csdn.net/questions/1097874](url)
umi版本2.8.7节点版本12.18.3

**Comment by kicktech** [comment]
我也是修改文件不能热更新。

Umi 版本：3.2.24
Node 版本：15.0.1
操作系统：macos 10.14.6
