### ISSUE TITLE
Default export of the module has or is using private name 'ICreateCSSRule', 'IManifest', 'ISSR'

### ISSUE THREAD

**Issue by fjc0k** [umijs/umi#5482]
![image](https://user-images.githubusercontent.com/13151189/94277190-c9cdf600-ff7b-11ea-88a9-c50bd3c50af1.png)

**Comment by ycjcl868** [comment]
配置发我下，我试下

**Comment by fjc0k** [comment]
@ycjcl868 
```ts
import { defineConfig } from 'umi'
import { range, sample } from 'vtils'

const ids = range(1, 10000)

const cssNames = new Map<string, string>()

export default defineConfig({
  dynamicImport: {
    loading: '@/Loading',
  },
  devtool: false,
  nodeModulesTransform:
    process.env.NODE_ENV === 'development'
      ? {
          type: 'none',
          exclude: [],
        }
      : {
          type: 'all',
          exclude: [],
        },
  cssLoader:
    process.env.NODE_ENV === 'development'
      ? {}
      : {
          modules: {
            getLocalIdent: (
              context: any,
              localIdentName: any,
              localName: any,
            ) => {
              if (
                context.resource &&
                String(context.resource).includes('node_modules')
              ) {
                return localName
              }
              const cssKey = `${context.resource}____${localName}`
              if (!cssNames.has(cssKey)) {
                const id = ids.splice(sample(range(0, ids.length)), 1)
                cssNames.set(cssKey, `_${id}`)
              }
              return cssNames.get(cssKey)
            },
          },
        },
  metas: [
    {
      'http-equiv': 'Cache-Control',
      'content': 'no-cache, no-store, must-revalidate',
    },
    {
      'http-equiv': 'Pragma',
      'content': 'no-cache',
    },
    {
      'http-equiv': 'Expires',
      'content': '0',
    },
  ] as any,
  scripts: [
    'https://i.alicdn.com/s/polyfill.min.js?features=default,es2015,es2016,es2017,es2018,fetch,RegeneratorRuntime,IntersectionObserver,IntersectionObserverEntry,URL,URLSearchParams,Set,Map',
  ],
  hash: true,
  targets: {
    ios: 8,
    safari: 8,
    android: 4,
  },
  exportStatic: {
    htmlSuffix: true,
    dynamicRoot: true,
  },
  antd: {},
  plugins: ['@alitajs/hd'],
  hd: {},
})

```

**Comment by 0xDing** [comment]
> @ycjcl868
> 
> ```ts
> import { defineConfig } from 'umi'
> import { range, sample } from 'vtils'
> 
> const ids = range(1, 10000)
> 
> const cssNames = new Map<string, string>()
> 
> export default defineConfig({
>   dynamicImport: {
>     loading: '@/Loading',
>   },
>   devtool: false,
>   nodeModulesTransform:
>     process.env.NODE_ENV === 'development'
>       ? {
>           type: 'none',
>           exclude: [],
>         }
>       : {
>           type: 'all',
>           exclude: [],
>         },
>   cssLoader:
>     process.env.NODE_ENV === 'development'
>       ? {}
>       : {
>           modules: {
>             getLocalIdent: (
>               context: any,
>               localIdentName: any,
>               localName: any,
>             ) => {
>               if (
>                 context.resource &&
>                 String(context.resource).includes('node_modules')
>               ) {
>                 return localName
>               }
>               const cssKey = `${context.resource}____${localName}`
>               if (!cssNames.has(cssKey)) {
>                 const id = ids.splice(sample(range(0, ids.length)), 1)
>                 cssNames.set(cssKey, `_${id}`)
>               }
>               return cssNames.get(cssKey)
>             },
>           },
>         },
>   metas: [
>     {
>       'http-equiv': 'Cache-Control',
>       'content': 'no-cache, no-store, must-revalidate',
>     },
>     {
>       'http-equiv': 'Pragma',
>       'content': 'no-cache',
>     },
>     {
>       'http-equiv': 'Expires',
>       'content': '0',
>     },
>   ] as any,
>   scripts: [
>     'https://i.alicdn.com/s/polyfill.min.js?features=default,es2015,es2016,es2017,es2018,fetch,RegeneratorRuntime,IntersectionObserver,IntersectionObserverEntry,URL,URLSearchParams,Set,Map',
>   ],
>   hash: true,
>   targets: {
>     ios: 8,
>     safari: 8,
>     android: 4,
>   },
>   exportStatic: {
>     htmlSuffix: true,
>     dynamicRoot: true,
>   },
>   antd: {},
>   plugins: ['@alitajs/hd'],
>   hd: {},
> })
> ```

You may need to `tsconfig.json` to:
```json
{
  "compilerOptions": {
      "declaration": true
   }
}
```

It's work for me.
