### ISSUE TITLE
umi在ios11的兼容性问题

### ISSUE THREAD

**Issue by xue-chao** [umijs/umi#5483]
![image](https://user-images.githubusercontent.com/11371132/94330932-5ec40400-fffb-11ea-8487-83db7f67c46e.png)

项目中使用umi2.x，在ios11.1中打开报错

**Comment by xiaohuoni** [comment]
提供复现demo

**Comment by hkonlaor** [comment]
> ![image](https://user-images.githubusercontent.com/11371132/94330932-5ec40400-fffb-11ea-8487-83db7f67c46e.png)
> 
> 
> 
> 项目中使用umi2.x，在ios11.1中打开
