### ISSUE TITLE
能否只对指定 host 进行端口检测

### ISSUE THREAD

**Issue by jansenchan** [umijs/umi#5484]
## Background

umi 在调试时，1024 以下的端口号都需要 root 权限才能启动。

umi@2.x 可以在用户权限下启动 1024 以下的接口。

绝大多数时候，本地调试都只使用 127.0.0.1:port 和 0.0.0.0:port ,这两个 host listen 1024 以下的端口是不需要 root 权限的。

umi@3.x 使用了 portfinder 库来检测端口可用性，会对所有 host 都进行检测，其实必要不大

## Proposal

在调试时，如果配置明确指定了 host 和 port 的时候，能否只对这个 host:port 做可用性检测。

如果可用，就启动 devserver，而不是强制所有端口都需要可用，才启动这个服务

## Additional context

针对端口有特殊需求的本地调试，每次都需要以 root 权限启动，开发体验不是十分友好，特别是，只是要用到 127.0.0.1 和 0.0.0.0 host 时

**Comment by shirleyYing** [comment]
sudo cross-env PORT=80 umi dev

**Comment by jansenchan** [comment]
> sudo cross-env PORT=80 umi dev

想避免使用 root 权限来启动
