### ISSUE TITLE
[Feature Request] Linaria support

### ISSUE THREAD

**Issue by ncioj10** [umijs/umi#5488]
## Background

I would like to integrate linaria (similar to styled components) see [Linaria](https://github.com/callstack/linaria)
 
Is it possible to do that? It currently uses some modifications to webpack to generate the css.

The general setup for webpack of linaria can be found here:
https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md#webpack

I'm using ant design pro with umi js 3.2.20.

**Comment by laozhu** [comment]
You can custom webpack with `chainWebpack` key in umi.js config file for using linaria. But If you are using umi.js with ant design components, I think it's not easy to custom theme variables in [LESS file](https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less) and refer them from your `SFC`.

**Comment by ncioj10** [comment]
Ok I've tried it with a chained webpack configuration, but it didn't seem to work. I have now resorted to applying LESS as global theme.
