### ISSUE TITLE
ssr 重刷新頁面後，umi.css&umi.js會404

### ISSUE THREAD

**Issue by anita8004** [umijs/umi#5490]
## What happens?

[https://github.com/umijs/umi/issues/5137](https://github.com/umijs/umi/issues/5137)
與此issue是一樣的問題
在路由更多層時重新刷新時，umi.css和umi.js會不見
![截圖 2020-09-28 下午12 41 33](https://user-images.githubusercontent.com/24818934/94391469-0ff7a500-0188-11eb-882a-641227335ec9.png)

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：3.2.22
- **Node 版本**：12.18.3
- **操作系统**：mac 10.15.5

**Comment by ycjcl868** [comment]
production 情况下配置 `publicPath` 为 `/scoreboard/soccer/dist/`

![image](https://user-images.githubusercontent.com/13595509/105812417-f2ceb980-5f62-11eb-8a09-93b7206b89bb.png)
