### ISSUE TITLE
重新打包后，含有import css的页面需要重刷新才能打开。

### ISSUE THREAD

**Issue by gugu-lee** [umijs/umi#5493]
## What happens?

工程重新打包后，如果某个页面中有引入css/less，打开此页面会出现一直等待的情况，查看调试窗口，发现 css与页面的chunkhash不相符。
估计是，js发生的变化，打包后文件名改变，但css没有变化。所以浏览器用得还是缓存的csss，因此页面打开不。刷新一下页面，css也使用最新的，就可以正常显示页面了。
请问如何解决？

## 相关环境信息

- **Umi 版本**：3.2.19
- **Node 版本**：v10.14.0
- **操作系统**：Windows 10

**Comment by itellyou-com** [comment]
清除本地缓存，或者设置刷新服务器/cdn的缓存时间

**Comment by gugu-lee** [comment]
> 清除本地缓存，或者设置刷新服务器/cdn的缓存时间

清除本地缓存需要用户操作手工操作，不友好。还是选择后者吧
