### ISSUE TITLE
文档描述错误

### ISSUE THREAD

**Issue by fanhualei** [umijs/umi#5494]
https://umijs.org/zh/guide/getting-started.html#%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87

让新手，第一入门的例子就出现编译错误，太不友好了。

```js
import Link from 'umi/link';
```

应该这么来写
```js
import { Link } from "umi";
```

**Comment by xiaohuoni** [comment]
你看的是umi@2的文档？

**Comment by fanhualei** [comment]
> 你看的是umi@2的文档？

https://umijs.org/zh/guide/getting-started.html#%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87    在这个链接的文档里面

**Comment by xiaohuoni** [comment]
我这边是没内容的。你强制刷新一下缓存。

**Comment by fanhualei** [comment]
我赛，还真是缓存的事情。我换了一个浏览器，发现官网帮助的界面都不一样了。 能不能发布官网时用webpack打成可以更新的hash包，不然谁知道还要删除缓存这种操作。
