### ISSUE TITLE
lessLoader的plugins不生效

### ISSUE THREAD

**Issue by zhangyu1818** [umijs/umi#5497]
## What happens?

lessLoader的plugins不生效
## Mini Showcase Repository(REQUIRED)

```
  lessLoader: {
    javascriptEnabled: true,
    plugins: [new LessPluginFunction()],
  },
```

最后浏览器里并没有解析less函数

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
这是要做啥？less本来就生效的

**Comment by zhangyu1818** [comment]
之前在storybook是可以的，页面上的css是通过了plugin的less插件转换，我昨天换成了dumi，发现样式就没生效

**Comment by zhangyu1818** [comment]
@xiaohuoni  这是复现仓库 https://github.com/zhangyu1818/umi-less-plugin.git
大佬有空看看

我刚才又试了下，在storybook里有效的，同时father打包出来的结果也是生效了，但是在umi里开发和打包都没有生效

**Comment by xiaohuoni** [comment]
可重现，还未定位问题。

**Comment by aixfox** [comment]
+1 mark

**Comment by q716015** [comment]
去找了一下问题, 发现只要是外部传进来的不行,或者在getConfig/css 文件手动 new 这个插件, 又或者是在这个文件引入插件并传入 是可以生效的, 就很奇怪🤔

**Comment by lxy94** [comment]
@zoy-l 引入是啥意思，我也遇到了，想写一个less插件，修改第三方组件得classname，但是好像并没有进入
