### ISSUE TITLE
修改端口小于1024只会显示1024端口

### ISSUE THREAD

**Issue by taoWcode** [umijs/umi#5498]
## What happens?

想改80端口，但是经过许多尝试均显示1024端口，后来再测试发现端口改为1024以后的端口才可以生效。

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

umi dev --port 83
.env   PORT=83  都尝试过了，还包括devServer

## 相关环境信息

- **Umi 版本**：3.2.20
- **Node 版本**：
- **操作系统**：Mac

**Comment by taoWcode** [comment]
使用较新版本会有问题。
经尝试3.1.1版本没问题

**Comment by aixfox** [comment]
#5484

**Comment by sorrycc** [comment]
Duplicated with #5484
