### ISSUE TITLE
autoprefixer： flexbox能不能自定义？

### ISSUE THREAD

**Issue by DeyuanTan** [umijs/umi#55]
https://github.com/umijs/umi/blob/9799a86f3e89b304d5502daa71bc5ca71c53a9aa/packages/af-webpack/src/getConfig.js#L42

**Comment by DeyuanTan** [comment]
项目用的是 roadhog V2.1

**Comment by sorrycc** [comment]
flexbox 的配置我 copy create-react-app 的，不能自定义是什么意思？

**Comment by DeyuanTan** [comment]
期望是在 .webpackrc 配置flexbox这个选项，因为flexbox: 'no-2009'会导致-webkit-box-orient: vertical;这些属性被过滤掉，我看了1.x的roadhog，是没有配flexbox的。求指导

https://github.com/sorrycc/roadhog/blob/bfd04555c267830453fabf4ea51f70678923bd5f/src/config/common.js#L328

**Comment by sorrycc** [comment]
找到为啥配这个 no-2009 了，

* https://developers.google.com/web/tools/lighthouse/audits/old-flexbox
* https://github.com/facebookincubator/create-react-app/issues/1658
