### ISSUE TITLE
开启ssr之后，不能热更新

### ISSUE THREAD

**Issue by PresByter2015** [umijs/umi#5501]
## What happens?

在 配置 ssr 之后，修改页面，会有一个 警告 如下
```
√ Client
  Compiled successfully in 176.87ms

√ Server
  Compiled successfully in 47.04ms

 WARNING  Compiled with 1 warnings                                                                              23:34:15

 warning  in ./src/pages/index.css?modules

Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

Greetings, time traveller. We are in the golden age of prefix-less CSS, where Autoprefixer is no longer needed for your stylesheet.

 @ ./src/pages/index.js 2:0-41 5:15-21
 @ ./src/.umi/core/server.ts
 @ multi ./src/.umi/core/server.ts

[SSR]  render /76275867cd84dc242aa8.hot-update.json start: 119.42ms
[SSR]  render / start: 140.41ms
```
之后 再也不会热更新了。同时 所有的tsx文件全部转换为 js和.map.js文件。
即使此时去掉 ssr 依然不会热更新。
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

1. yarn create @umijs/umi-app my-app  并且 yarn
2. 添加 ssr
3. yarn start (此时.umirc.ts会编译出 .umirc.js和.umirc.map.js文件)
4. 出现如上警告，修改页面 没有热更新
5. 关闭服务，重新yarn start。此时页面才会更新（但依然没有热更新）。

## 相关环境信息

- **Umi 版本**：3.2.22
- **Node 版本**：v12.14.1
- **操作系统**：win10

**Comment by ycjcl868** [comment]
复现了

**Comment by ycjcl868** [comment]
https://github.com/umijs/umi/pull/5462

与这个有关
