### ISSUE TITLE
css 装换rem问题

### ISSUE THREAD

**Issue by huang-guanhua** [umijs/umi#5502]
#5131  相关环境信息

- **Umi 版本**：3.2.14
- **Node 版本**：v12.14.1
- **操作系统**：window 10

我想在项目的css中的单位转成rem，有尝试使用安装@alitajs/hd，直接报错 Validate config "hd" failed, "value" must be of type object

```config.js
plugins: ['@alitajs/hd'],
hd: true
```

**Comment by xiaohuoni** [comment]
配置改了
```
hd:{
}
```

**Comment by huang-guanhua** [comment]
> 配置改了
> 
> ```
> hd:{
> }
> ```

我想了解下里面的配置参数

**Comment by huang-guanhua** [comment]
> 配置改了
> 
> ```
> hd:{
> }
> ```

我尝试在配置config.js,导出的对象上写hd:{},可是会报错的
```
Invalid config key: hd
Error: Invalid config key: hd
```
