### ISSUE TITLE
umi3 how to modify .umi folder path

### ISSUE THREAD

**Issue by haydonduan** [umijs/umi#5503]
my project code is generated by JHipster, so the project code structure is different from the standard structure.
like:
```
 -src
 --main
 ---java
 ---webapp
```
my frontend code should be in webapp folder. 
so, when the project is started, the .umi folder is generated blow src directly. like this
```
 -src
 --.umi <---- is generated here
 --main
 ---java
 ---webapp
```

but I want to like this:
```
 -src
 --main
 ---java
 ---webapp
 ----- .umi   <-----  I want it is generated here
```

Thanks

**Comment by xiaohuoni** [comment]
[APP_ROOT](https://umijs.org/zh-CN/docs/env-variables#app_root)=src/webapp

**Comment by haydonduan** [comment]
YES~ Thanks
