### ISSUE TITLE
请问如何升级到typescript4.0?

### ISSUE THREAD

**Issue by g770728y** [umijs/umi#5507]
1. yarn add typescript ( 安装4.0) 

2. 写 4.0 语法 

3.  yarn start 报错

请教应当如何做呢?

**Comment by ycjcl868** [comment]
默认就是 ts 4.0

如果是 ts 4.1 的话，还在 beta 中

https://github.com/umijs/umi/pull/5573

**Comment by g770728y** [comment]
sorry, 原来是用的umi2.x....
升级到umi3.x就无问题了, 感谢!

**Comment by wangzhengbo** [comment]
> 默认就是 ts 4.0
> 
> 如果是 ts 4.1 的话，还在 beta 中
> 
> #5573

请问哪里可以看到默认是4.0呢？我看node_modules下安装的是3.9.7的版本？
