### ISSUE TITLE
modifyDefaultConfig 修改第三方插件的配置依赖于插件的解析顺序

### ISSUE THREAD

**Issue by jiyingzhi** [umijs/umi#5511]
比如：通 modifyDefaultConfig 配置 antd: {} 时要求 @umijs/plugin-antd 已经被解析，而 package.json 中的依赖顺序是不可控的，又不希望手动在 config 中配置 plugins，有没有什么办法解决？试了下 onPluginReady 和 onStart 都不行

**Comment by zry754331875** [comment]
+1
