### ISSUE TITLE
npm-run-all 结合 dumi 和 umi 一起使用的时候报错

### ISSUE THREAD

**Issue by tolerance-go** [umijs/umi#5515]
## What happens?

npm-run-all 结合 dumi 和 umi 一起使用的时候报错

![image](https://user-images.githubusercontent.com/37258382/95561919-04409400-0a4e-11eb-8730-fa4e33dc7bc5.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

pkg 配置如下，执行 yarn dev 的时候，浏览器报错

 "dev": "npm-run-all --parallel dev:**",
    "dev:app": "umi dev",
    "dev:doc": "cross-env PORT=9000 UMI_ENV=doc dumi dev",

## Context

- **Umi Version**: latest
- **Node Version**: 12
- **Platform**: macOS

**Comment by tolerance-go** [comment]
生成的 .umi 不一样导致的

**Comment by AlisonZXQ** [comment]
> 生成的 .umi 不一样导致的

怎么解决的
