### ISSUE TITLE
升级umi3后，安装依赖为antd3，antd无效

### ISSUE THREAD

**Issue by jusheng** [umijs/umi#5516]
## What happens?

升级umi3后，安装依赖为antd3，antd无效

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本3.x：
- **Node 版本**：
- **操作系统**：

**Comment by ycjcl868** [comment]
什么问题，
