### ISSUE TITLE
自定义css打包输出路径后 url相对地址访问错误

### ISSUE THREAD

**Issue by johnnylc** [umijs/umi#5525]
在项目中，通过chainWebpack修改了css文件的打包输出路径
```
    config.plugin('extract-css').tap(args => [
      {
        ...args[0],
        chunkFilename: `css/[name]${hash}.chunk.css`,
        filename: `static/[name]${hash}.css`,
        ignoreOrder: true
      },
    ]);
```
```
.backgroundImage {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background: url(../assets/images/login_bg.png) no-repeat;
  background-repeat: no-repeat;
  background-size: 100% 100%;
}
```
导致css中的引用的url图片地址无法正常访问到，url地址都从css文件夹开始的相对路径进行访问，例如图片打包：
打包后实际图片地址：static/login_bg.ecb99795.png
打包后代码访问的图片地址：css/static/login_bg.ecb99795.png

我尝试过通过chainWebpack修改 css 插件的 publicPath，可能因为具体配置写法有问题，没有能够配置成功。

请问这种情况是否有合适的解决方式？

**Comment by sorrycc** [comment]
不支持这么修改路径的。

**Comment by LiuJinYang9527** [comment]
我也遇到这个问题了，自定义打包的css文件路径后，背景图片的路径一直是相对路径，看了下源码是将`publicPath`固定写为相对路径 `'./'`的， 这个能不能支持配置呢，尝试通过chainWebpack去修改但是一直没成功。 @sorrycc 
源码地址: https://github.com/umijs/umi/blob/master/packages/bundler-webpack/src/getConfig/css.ts#L64

**Comment by drizzlesconsin** [comment]
@LiuJinYang9527 

看 @sorrycc 的回复，应该是可以修改 `publicPath ` 的？
https://github.com/umijs/umi/pull/5031#issuecomment-658007667

> 遇到同样的问题 #6171

**Comment by drizzlesconsin** [comment]
@LiuJinYang9527 

看 @sorrycc 的回复，应该是可以修改 `publicPath ` 的？
https://github.com/umijs/umi/pull/5031#issuecomment-658007667

> 遇到同样的问题 #6171

**Comment by LiuJinYang9527** [comment]
> @LiuJinYang9527 
> 
> 
> 
> 看 @sorrycc 的回复，应该是可以修改 `publicPath ` 的？
> 
> https://github.com/umijs/umi/pull/5031#issuecomment-658007667
> 
> 
> 
> > 遇到同样的问题 #6171 

感觉是可以的  不过试了半天没成功  我再仔细看看webpackchain的文档试试吧

**Comment by LiuJinYang9527** [comment]
解决了 配置代码如下，希望可以帮到其它人
```js
    const isDev = process.env.NODE_ENV === 'development';
    config.module.rule('css').oneOf('css').use('extract-css-loader').tap(options => ({
      publicPath: '/',
      hmr: isDev
    }))
    config.module.rule('less').oneOf('css').use('extract-css-loader').tap(options => ({
      publicPath: '/',
      hmr: isDev
    }))
```

**Comment by drizzlesconsin** [comment]
@LiuJinYang9527 请问除了上面两个配置，还有别的配置吗？

直接把 [/src/getConfig/css.ts#L64](https://github.com/umijs/umi/blob/master/packages/bundler-webpack/src/getConfig/css.ts#L64) `publicPath: './'` 改成 `publicPath: '../'`
打包出来的路径是正确的
```css
background-image: url("../img/xx.xx.png"); /* http://xx.com/img/xx.xx.png ✅ */
```

通过上面两个配置打包出来的路径还是不对
```css
background-image: url("img/xx.xx.png"); /* http://xx.com/css/img/xx.xx.png ❌ */
```

#### ChainWebpack config
```js
// css
config.module.rule('css').oneOf('css').use('extract-css-loader').tap(options => ({
  publicPath: '/',
  hmr: false
}))
config.module.rule('less').oneOf('css').use('extract-css-loader').tap(options => ({
  publicPath: '/',
  hmr: false
}))

config.plugin('extract-css').tap(() => [
  {
    filename: 'css/[name].[contenthash:8].css',
    chunkFilename: 'css/[name].[contenthash:8].chunk.css',
    ignoreOrder: true,
  },
]);

// img
config.module
  .rule('images')
  .test(/\.(png|jpe?g|gif|webp|ico)(\?.*)?$/)
  .use('url-loader')
  .loader(require.resolve('url-loader'))
  .tap((options) => ({
    ...options,
    name: 'img/[name].[hash:8].[ext]',
    fallback: {
      ...options.fallback,
      options: {
        name: 'img/[name].[hash:8].[ext]',
        esModule: false,
      },
    },
  }));
```

```json
"umi": "^3.2.14",
"@umijs/bundler-webpack": "3.3.7"
```

**Comment by drizzlesconsin** [comment]
umi v2 是支持配置 cssPublicPath https://github.com/umijs/umi/issues/1398#issuecomment-435793576, v3 好像不支持了。
@sorrycc 请问是什么原因 在新的版本中去除了呢。这个配置相对来说还是有用的(_抽离样式文件、图片资源到指定目录_)。
看到有相关的 PR https://github.com/umijs/umi/pull/5031/commits/a2ebb5f208cb080603b816a52c38d8e0f26e178e `config.publicPath` 不过改为 `config.cssPublicPath` 是不是会好点。

_或许真的没必要对输出资源进行分类？_

**Comment by LiuJinYang9527** [comment]
这是我的完整配置
### chainWebpack Config

```js
chainWebpack: function(config, { webpack }) {
    const isDev = process.env.NODE_ENV === 'development';
    const hash = !isDev ? '.[contenthash:8]' : '';
    config.output.chunkFilename(`js/[name]${hash}.async.js`);
    config.output.filename(`static/[name]${hash}.js`);
    config.plugin('extract-css').tap((args) => [
      {
        ...args[0],
        filename: `static/[name]${hash}.css`,
        chunkFilename: `css/[name]${hash}.chunk.css`
      }
    ]);
    config.module
      .rule('css')
      .oneOf('css')
      .use('extract-css-loader')
      .tap((options) => ({
        publicPath: '/',
        hmr: isDev
      }));
    config.module
      .rule('less')
      .oneOf('css')
      .use('extract-css-loader')
      .tap((options) => ({
        publicPath: '/',
        hmr: isDev
      }));
    config.merge({
      optimization: {
        minimize: true,
        splitChunks: {
          chunks: 'all',
          name: true,
          minSize: 30000,
          minChunks: 1,
          automaticNameDelimiter: '.',
          cacheGroups: {
            vendors: {
              name: 'vendors',
              chunks: 'all',
              test: /[\\/]node_modules[\\/]/,
              priority: -12
            }
          }
        }
      }
    });
    if (isDev) {
      config.module
        .rule('js-in-node_modules')
        .exclude.add(/node_modules/)
        .end();
      config.module
        .rule('ts-in-node_modules')
        .exclude.add(/node_modules/)
        .end();
    }
  },
```
```
"umi": "^3.2.117",
"@umijs/bundler-webpack": "3.3.7"
```

你是不是用到了`sass`，如果是要加一下sass配置试试
```js
    config.module
      .rule('sass')
      .oneOf('css')
      .use('extract-css-loader')
      .tap((options) => ({
        publicPath: '/',
        hmr: isDev
      }));
```

**Comment by drizzlesconsin** [comment]
@LiuJinYang9527 感谢回复。
试了还是不行，我再找找别的方法 🤣

**Comment by LiuJinYang9527** [comment]
> @LiuJinYang9527 感谢回复。
> 试了还是不行，我再找找别的方法 🤣

可以通过打印`config.toString()` 来查看生成的webpack配置，应该可以帮到你

**Comment by drizzlesconsin** [comment]
> 可以通过打印`config.toString()` 来查看生成的webpack配置，应该可以帮到你

@LiuJinYang9527 感谢提醒。找到解决方法了 🎉
增加 css-modules 的规则配置：
```diff
config.module.rule('css').oneOf('css').use('extract-css-loader').tap(options => ({
  publicPath: '../',
  hmr: false
}))
config.module.rule('less').oneOf('css').use('extract-css-loader').tap(options => ({
  publicPath: '../',
  hmr: false
}))
+ config.module.rule('less').oneOf('css-modules').use('extract-css-loader').tap(() => ({
+   publicPath: '../',
+   hmr: false
+ }));

config.plugin('extract-css').tap(() => [
  {
    filename: 'css/[name].[contenthash:8].css',
    chunkFilename: 'css/[name].[contenthash:8].chunk.css',
    ignoreOrder: true,
  },
]);
```

**Comment by drizzlesconsin** [comment]
> 可以通过打印`config.toString()` 来查看生成的webpack配置，应该可以帮到你

@LiuJinYang9527 感谢提醒。找到解决方法了 🎉
增加 css-modules 的规则配置：
```diff
config.module.rule('css').oneOf('css').use('extract-css-loader').tap(() => ({
  publicPath: '../',
  hmr: false
}))
config.module.rule('less').oneOf('css').use('extract-css-loader').tap(() => ({
  publicPath: '../',
  hmr: false
}))
+ config.module.rule('less').oneOf('css-modules').use('extract-css-loader').tap(() => ({
+   publicPath: '../',
+   hmr: false
+ }));

config.plugin('extract-css').tap(() => [
  {
    filename: 'css/[name].[contenthash:8].css',
    chunkFilename: 'css/[name].[contenthash:8].chunk.css',
    ignoreOrder: true,
  },
]);
```

**Comment by slcyyy** [comment]
> 
你好，我对webpack和webpack-chain不是很理解，请问这里的extract-css-loader我搜索并没搜索到这个loader，这个写法是什么的简写还是怎么样呢

**Comment by slcyyy** [comment]
> > 可以通过打印`config.toString()` 来查看生成的webpack配置，应该可以帮到你
> 
> @LiuJinYang9527 感谢提醒。找到解决方法了 🎉 增加 css-modules 的规则配置：
> 
> ```diff
> config.module.rule('css').oneOf('css').use('extract-css-loader').tap(() => ({
>   publicPath: '../',
>   hmr: false
> }))
> config.module.rule('less').oneOf('css').use('extract-css-loader').tap(() => ({
>   publicPath: '../',
>   hmr: false
> }))
> + config.module.rule('less').oneOf('css-modules').use('extract-css-loader').tap(() => ({
> +   publicPath: '../',
> +   hmr: false
> + }));
> 
> config.plugin('extract-css').tap(() => [
>   {
>     filename: 'css/[name].[contenthash:8].css',
>     chunkFilename: 'css/[name].[contenthash:8].chunk.css',
>     ignoreOrder: true,
>   },
> ]);
> ```

你好，我对webpack和webpack-chain不是很理解，请问这里的extract-css-loader我搜索并没搜索到这个loader，这个写法是什么的简写还是怎么样呢

**Comment by 7kms** [comment]
@drizzlesconsin  thanks.

**Comment by SilentFlute** [comment]
以前用过`umi2.x`, 然后通过配置`publicPath`来处理静态资源的路径问题, 测试和生产使用`cdn`的域名, 开发使用默认的`/`, 打包完毕之后使用上传脚本将打包之后的内容上传到`cdn`, 上传完毕之后`js`, `css`中相应的图片地址就换成了设置的`publicPath`, 只是项目中使用的图片是通过`import`引入直接写到`jsx`中的. 时间久远, 或许只是`html`中`js` `css`文件的地址换成了`cdn`的地址吧, 毕竟图片`import`进来就直接`base64`了, 记不太清了, 只是`publicPath`能够生效, 以及项目中有设置`publicPath`为`cdn`域名的代码:
`.env`:
```
publicPath=http://xxx/
```
`.umirc.js`:
```
publicPath: process.env.publicPath,
```
现在做新的项目, 使用的是`umi 3.5.20`, 是在`less`文件中通过`background-image: url(/img/xxx.png);`以及`js`中`<img src="/img/xxx.png"/>`这样的路径形式使用图片, 可此时我配置`publicPath`却不起作用了, 我倒没有把`css`文件全部提取到某个目录的需求, 但需要将前面提到的静态资源地址修改为`publicPath`, 比如默认打包:
`html`:
```
<link rel="stylesheet" href="/umi.css" />
 <script src="/umi..js"></script>
```
`umi.css`:
```
background-image:url(/img/xxx.png);
```
修改为:
`html`:
```
<link rel="stylesheet" href="{publicPath}/umi.css" />
 <script src="{publicPath}/umi.js"></script>
```
`umi.css`:
```
background-image:url({publicPath}/img/xxx.png);
```
或者哪怕图片路径就用`/img/xxx.png`, 那`html`里的静态资源目录修改为:
```
<link rel="stylesheet" href="{publicPath}/umi.css" />
 <script src="{publicPath}/umi.js"></script>
```
这样将打包出来的`/dist`目录中的`/img`目录和`js` `css`文件都放到`{publicPath}`下即可, 而如果`publicPath`不生效, 那就需要我手动去修改`html`文件中的引用路径了, 这就有点蛋疼了...
试了上面的方法, 但并没有成功, 求指点

**Comment by SilentFlute** [comment]
@drizzlesconsin 求指点~~

**Comment by liguonan888** [comment]
> 

🙏，感谢，确实能用了

**Comment by Asher-Tan** [comment]
https://github.com/umijs/umi/blob/master/packages/bundler-webpack/src/getConfig/getConfig.ts
把链接里的规则copy到自己项目的 chainWebpack做定制就行
``` js
 webpackConfig.module
    .rule('images')
    .test(/\.(png|jpe?g|gif|webp|ico)(\?.*)?$/)
    .use('url-loader')
      .loader(require.resolve('@umijs/deps/compiled/url-loader'))
      .options({
        limit: config.inlineLimit || 10000,
        name: `${staticDir}/[name].[hash:8].[ext]`,
        // require 图片的时候不用加 .default
        esModule: false,
        fallback: {
          loader: require.resolve('@umijs/deps/compiled/file-loader'),
          options: {
            publicPath: '', // 加上这句就可以了
            name: `${staticDir}/[name].[hash:8].[ext]`,
            esModule: false,
          },
        }
      });

```
