### ISSUE TITLE
[RFC] say something

### ISSUE THREAD

**Issue by Afoora890** [umijs/umi#5526]
## 背景

> 描述你希望解决的问题的现状，附上相关的 issue 地址

## 思路

> 描述大概的解决思路，可以包含 API 设计和伪代码等

## 跟进

- [ ] some task
- [x] PR URL

**Comment by bkt161616** [comment]
Àllô

**Comment by bkt161616** [comment]
> Àllô

![image](https://user-images.githubusercontent.com/72665080/95670708-b36b9100-0b5c-11eb-8012-b0bddec3b392.png)
