### ISSUE TITLE
打包后想本地打开dist里面的index.html，要配置些什么呢

### ISSUE THREAD

**Issue by CiciIvory** [umijs/umi#5532]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
看文档 https://umijs.org/zh-CN/docs/getting-started#%E6%9C%AC%E5%9C%B0%E9%AA%8C%E8%AF%81 别随便加 bug label

**Comment by SilentFlute** [comment]
@xiaohuoni 你好, 我也想问这个问题, 简单来说就是: 为何打包出来的`index.html`不能直接在浏览器中访问而需要`serve`一下呢? 哪怕我修改了`index.html`中`css` `js`的引用地址, `css`文件和`js`文件都能正常访问到也不行呢? 直接在浏览器中访问`index.html`浏览器不报错, 但是页面显示一片空白, 求指点, 感谢 :)

**Comment by CiciIvory** [comment]
> @xiaohuoni 你好, 我也想问这个问题, 简单来说就是: 为何打包出来的`index.html`不能直接在浏览器中访问而需要`serve`一下呢? 哪怕我修改了`index.html`中`css` `js`的引用地址, `css`文件和`js`文件都能正常访问到也不行呢? 直接在浏览器中访问`index.html`浏览器不报错, 但是页面显示一片空白, 求指点, 感谢 :)
后来看文档后总结：
https://blog.csdn.net/qq_40593656/article/details/109157279

**Comment by SilentFlute** [comment]
@CiciIvory 感谢感谢, 可以了~但这是为什么呢? 我试了试, 主要是`history`和`publicPath` `api`起作用, `hash`模式的话url切换不会发送真实的请求, 但这和这个问题有什么关系呢? 静态资源的路径我知道, 改成相对的, 那为何改成了`hash`模式就可以了呢?
