### ISSUE TITLE
[Bug] npm start 或 build 的时，config/config.js 文件会执行两边

### ISSUE THREAD

**Issue by tanyplzu** [umijs/umi#5533]
## What happens?

npm start 或 build 的时，config/config.js 文件会执行两遍。

## 复现步骤，错误日志以及相关配置

yarn create @umijs/umi-app 生成的项目。

## 相关环境信息

- **Umi 版本**：3.2.22
- **Node 版本**：12.16.2
- **操作系统**：ios

**Comment by sorrycc** [comment]
执行两边有啥问题？

**Comment by tanyplzu** [comment]
写错了，是执行两遍，下面问题说明里写了。

**Comment by tanyplzu** [comment]
> 执行两边有啥问题？

写错了，是执行两遍，下面问题说明里写了。
