### ISSUE TITLE
按 pages 下目录打包并按需加载

### ISSUE THREAD

**Issue by hdwong** [umijs/umi#5535]
请问如何把 pages 目录下的不同目录打包到不同的 js 并实现按需加载，是约定路由。搜索下找不到相关帮助，谢谢。

**Comment by sorrycc** [comment]
按需加载配 dynamicImport 就好了，和是否约定式路由无关。

**Comment by sorrycc** [comment]
配置 dynamicImport 后，就会分开构建，比如，

![image](https://user-images.githubusercontent.com/35128/104831100-6c5e0c00-58c0-11eb-877e-2a1d0cf53416.png)
