### ISSUE TITLE
umi2 与 umi3 版本管理

### ISSUE THREAD

**Issue by xingdongyang** [umijs/umi#5538]
## 背景

> 通过npm全局安装umi ,在公司安装的版本为v3+  在家安装的最新版本为  v2+ 。
为什么最新的版本来回变换,导致分不清哪个是最高的版本。我查看了发布记录,发现 4天前的版本为 3.2.23  最新的版本为: 2.13.15
这样发布发布是基于什么考虑的呢？谢谢！

![image](https://user-images.githubusercontent.com/8855891/95857400-227bfc00-0d8e-11eb-9c2f-fcef2e927bec.png)

**Comment by sorrycc** [comment]
这是个问题，已修复。
