### ISSUE TITLE
更新umi之后初始化启动无法加载index

### ISSUE THREAD

**Issue by dawnChen666** [umijs/umi#554]
umi1.3.4 初始化项目之后直接npm start，无法正常展示index.js的内容

**Comment by sorrycc** [comment]
怎么重现？

**Comment by dawnChen666** [comment]
我是全局安装了umi和dva-cli 然后用dva new新的项目完成后不做任何操作，直接npm start
我注意到一件事，就是1.3.4的router.js跟之前的版本似乎有些不同，在配置路由上面。如果是正常的匹配，也就是/xxx这种是能正常的，唯独/这个不行。显示的不是index.js的内容而是空白页，并且浏览器控制台报错。

**Comment by dawnChen666** [comment]
我会尝试下之前的umi版本是否有相同的问题。@sorrycc

**Comment by dawnChen666** [comment]
win10是不是有关系？或许Linux是正常的？因为刚开始使用umi的时候是1.0.x的是正常的，之前的项目升级到1.3.4也是正常的，唯独今天要开新项目了，建起来的时候出问题了，所以来问问

**Comment by xiaohuoni** [comment]
我也试了，不能重现

**Comment by dawnChen666** [comment]
dva-cli beta4 
umi 1.3.4
umi全局安装会出现我这个问题，项目里如果有umi就不会出现index界面不会展示的问题

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/546 因为存在这个问题，并无法使用全局的umi启动项目
