### ISSUE TITLE
[Bug] history组件query中，如果上一个页面携带的number类型 刷新页面之后类型发生了变动变动成了string，建议修复保持类型不变

### ISSUE THREAD

**Issue by BM-laoli** [umijs/umi#5541]
## 最小可复现仓库
https://github.com/BM-laoli/umi-history.git
> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

1. 进入项目切换到master分支启动项目
2.点击 “goto"链接打开新组件
3.在新组件得devToop上可以观察到location.query中的参数id是 number类型 
4. 刷新页面，发现参数变成了 string类型

## 相关环境信息

- **Umi 版本**：3.2.23
- **Node 版本**：12.16.2
- **操作系统**： Windows10

**Comment by BM-laoli** [comment]
最近项目最后测试阶段，发现和微前端 qiankun结合之后，也会有这个bug，如果是独立运行 ，没有问题，和乾坤结合之后，就又重现了这个bug

**Comment by sorrycc** [comment]
类型错误会造成什么影响？devtool 里怎么看类型？给个截图？

**Comment by BM-laoli** [comment]
类型不匹配，会影响，基于query进行页面传参的方案，带来一定量开发中非逻辑性的额外判断，比如query传参在 参数里传了一个true，然后，正式部署上去之后 会变成 “true”,所以我需要额外的判断
