### ISSUE TITLE
项目中为什么每个页面，外层都会包裹一个div，这是为什么，如何去掉呢？

### ISSUE THREAD

**Issue by leiyangs** [umijs/umi#5543]
![image](https://user-images.githubusercontent.com/16798581/95951436-ffeaf100-0e28-11eb-8550-d4c9d6a1b089.png)

**Comment by itellyou-com** [comment]
检查 layouts 和  document.ejs 看看

**Comment by ycjcl868** [comment]
不会吧，检查下 layouts 目录或 `layout` 配置

![image](https://user-images.githubusercontent.com/13595509/102085072-ffd88480-3dca-11eb-8b52-b95e28faa02d.png)

**Comment by gugegev5** [comment]
> 不会吧，检查下 layouts 目录或 `layout` 配置
> 
> ![image](https://user-images.githubusercontent.com/13595509/102085072-ffd88480-3dca-11eb-8b52-b95e28faa02d.png)

你直接访问首页当然没事啦，用route跳转一下就会包一层。我是配置式路由

**Comment by gugegev5** [comment]
看看是不是用了官方wrappers的demo
```js
import { Redirect } from 'umi'

export default (props) => {
  const { isLogin } = useAuth();
  if (isLogin) {
    return <div>{ props.children }</div>;
  } else {
    return <Redirect to="/login" />;
  }
}
```
