### ISSUE TITLE
[Bug] 文档里hash路由的配置有误

### ISSUE THREAD

**Issue by htank-wang** [umijs/umi#5547]
## What happens?

![image](https://user-images.githubusercontent.com/17918845/96086833-79501580-0ef5-11eb-9e3c-088726d1f4c9.png)

## 正确使用
history: {
    type:'hash'
  },

## 相关环境信息

- **Umi 版本**：umi@3.2.17
- **Node 版本**：v12.8.1
- **操作系统**：macos

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/96108241-ebcdef00-0f0f-11eb-9211-d9c562f693be.png)
