### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wangyong00** [umijs/umi#5550]
## What happens?

问题：删除yarn.lock快照文件后，重新使用 lerna bootstrap安装依赖。执行 npm run build异常。使用yarn.lock文件能正常构建。

## 相关环境信息

- **Umi 版本**：3.2.23
- **Node 版本**：v12.19.0
- **操作系统**：macos

**Comment by xiaohuoni** [comment]
别提这种没有任何信息的问题，什么项目，报什么错，给个复现Demo
