### ISSUE TITLE
[Bug] 404 conventional routing not working

### ISSUE THREAD

**Issue by khalibloo** [umijs/umi#5557]
## What happens?

Conventional 404 routing isn't working. `404.tsx` is treated like a normal page. Here is the generated `.umi/core/routes.ts`
```ts
export function getRoutes() {
  const routes = [
  {
    "path": "/404",
    "exact": true,
    "component": require('@/pages/404.tsx').default
  },
  {
    "path": "/",
    "exact": true,
    "component": require('@/pages/index.tsx').default
  }
];
```

## Mini Showcase Repository

https://github.com/khalibloo/umi-404-bug

## How To Reproduce

1. Create new umi project
2. Remove `routes` from `.umirc.ts`
3. Add `404.tsx` in "src/pages"

**Expected behavior** 
1. When visiting invalid link, 404 page should be displayed.

## Context

- **Umi Version**: 3.2.23
- **Node Version**: 12.13.0
- **Platform**: Windows 10 x64

**Comment by zhouzyc** [comment]
I'm the same
umi@3.2.23

**Comment by xiaohuoni** [comment]
这个问题出于什么考虑，不修复？@sorrycc
