### ISSUE TITLE
[Bug] umi2.9.0 无法使用可选链操作符?.

### ISSUE THREAD

**Issue by 23cicada** [umijs/umi#5558]
## What happens?

使用 `?.` 操作符报语法错误

但是 `node-module/babel-preset-umi/src/index.js` 下引用了 `@babel/plugin-proposal-optional-chaining`

请问是需要特别设置什么吗？

## 相关环境信息

- **Umi 版本**：
2.9.0
- **Node 版本**：
12.18.2
- **操作系统**：
win10

**Comment by chjiyun** [comment]
我的没报错，但是ts提示红的
