### ISSUE TITLE
[Bug] Extremely low performance because of browserify process: react-pdf is way too slow!

### ISSUE THREAD

**Issue by mleister97** [umijs/umi#5559]
As I already asked on stackoverflow.com, please the likely problem here: https://stackoverflow.com/a/63976087/12900361

**Comment by mleister97** [comment]
@sorrycc why did you close this issue?
react-pdf is still extremely slow in any umijs project.

**Comment by 8cells** [comment]
@sorrycc How to fix it?

**Comment by mleister97** [comment]
@8cells I did not find any solution. Sorry. I removed umi completely because of this and also other issues I faced in the time using it.
@sorrycc ??
