### ISSUE TITLE
dev访问不存在的页面，报错，没有到Page List

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#556]
![_20180528180449](https://user-images.githubusercontent.com/11746742/40610255-40cb238a-62a4-11e8-8b79-d54e75aff555.png)

**Comment by sorrycc** [comment]
怎么重现？或者打印下 routes 是啥？

**Comment by xiaohuoni** [comment]
不是必先嘛？就dev之后，随便访问一个页面。你试试。如果不是必现。明天我再定位。

**Comment by sorrycc** [comment]
重现不了。

**Comment by xiaohuoni** [comment]
好的。我会跟进这个问题

**Comment by xiaohuoni** [comment]
这个问题是因为文件名以n开头，如newlogin 在被添加到路由时
```js
\\\\newlogin
会被解析成
\\\
ewlogin
```
我觉得可能和文件的files.eol --行尾序列 有关。
mac下一般为LF(\r\n),windows下一般为CRLF
但是生成的router文件，为LF

**Comment by xiaohuoni** [comment]
@sorrycc 还有一个疑问，文件地址是‘./src/pages/abc’。会被转换成'./src\\\\pages\\\\abc'
我每次看到这个都觉的不是很正常，按我的理解应该是被转换成'.\\src\\pages\\abc'

**Comment by xiaohuoni** [comment]
其他转移字符(除了引号，文件名中带引号也不行)不会有问题
