### ISSUE TITLE
umi3.0用什么替代v2.0的hd配置？

### ISSUE THREAD

**Issue by explorefit** [umijs/umi#5562]
## What happens?

之前一直使用umi2.0里的hd方案，使用rem来转换，换为3.0版本后，使用什么来替代呢，怎么支持rem呢
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by xiaohuoni** [comment]
可以用@alitajs/hd 和 umi2 一模一样。
