### ISSUE TITLE
[Bug] qiankun插件和externals的问题

### ISSUE THREAD

**Issue by EddieUp** [umijs/umi#5563]
## What happens?

在qiankun子项目中配置了externals后，运行会报错，已经引入了对应的CDN了。注释掉qiankun的配置就不会报错。
```
externals: {
  react: 'window.React',
  'react-dom': 'window.ReactDOM',
},
qiankun: {
  slave: {},
},
```
![image](https://user-images.githubusercontent.com/19686692/96711227-cfc6c380-13cf-11eb-9267-5f6cc12ad517.png)

## Context

- **Umi Version**: 3.2.23
- **Node Version**:
- **Platform**:

**Comment by jqxismygit** [comment]
我也碰到了这个问题，解决了么

**Comment by EddieUp** [comment]
> 我也碰到了这个问题，解决了么

没呢，也不是很紧急

**Comment by jqxismygit** [comment]
@EddieUp 我找到问题了

**Comment by jqxismygit** [comment]
https://github.com/umijs/umi/issues/5575

**Comment by EddieUp** [comment]
> #5575
感谢感谢大佬

**Comment by deaver1248** [comment]
module. <anonymous>
.ali-data-query-[masterT]/node_modules/mini-create-react-context/dist/esm/index.js:176

**Comment by kuitos** [comment]
closed via #5575
