### ISSUE TITLE
[Bug] global.less里修改antd less 变量无效

### ISSUE THREAD

**Issue by KellenHe** [umijs/umi#5567]
虽然是权重和引入顺序导致的，但是起码要保证修改antd less变量可以生效吧，不然设计global.less的意义何在呢。

现在是antd 的less变量修改要在config里配置，这设计很不合理。
很多情况less是一套代码，很多变量需要修改，一个个挪到config很麻烦。

**Comment by xiaohuoni** [comment]
现在的设计，less 变量的修改就是在 theme 配置。
