### ISSUE TITLE
使用 MicroApp 形式引用子应用，并设置 autoSetLoading=true   ,子应用加载成功后一直处于loading 状态

### ISSUE THREAD

**Issue by Dolov** [umijs/umi#5568]
## What happens?

使用 MicroApp 形式引用子应用，并设置 autoSetLoading=true   ,子应用加载成功后一直处于loading 状态
子应用没有使用 @umijs/plugin-qiankun 插件

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaoyierle** [comment]
这个问题解决了吗？
