### ISSUE TITLE
[Bug] 开发模式下全局异常处理，仍然弹出错误遮罩层

### ISSUE THREAD

**Issue by sunyum** [umijs/umi#5571]
## What happens?

开发环境下，局部抛出异常时，即使全局处理异常并拦截，仍然会弹出错误遮罩层，希望能够针对此问题提供一个解决方案。
![image](https://user-images.githubusercontent.com/20025971/96990257-712d5100-1559-11eb-881a-fedd546246de.png)

**至于为什么不局部处理，下面描述一个典型的场景：**
使用plugin-request时，业务错误时会统一弹窗提示，同时会抛出一个BizError异常。
大部分时候不需要catch，因为已经统一弹窗提示了，但是此时会弹出错误遮罩层。
同样此异常也不能不抛出，因为可能会在请求处catch进行额外的业务处理

## 相关环境信息

- **Umi 版本**：3.2.24

**Comment by TokisakiYuu** [comment]
最后怎么解决的呢

**Comment by hanyaxxx** [comment]
这么做真的很垃圾

**Comment by Darcrandex** [comment]
同样遇到这个问题.
哈哈哈, 服了😂
