### ISSUE TITLE
打包项目上线后 初次打开项目 会报错 Internal Server Error

### ISSUE THREAD

**Issue by luoxuefengs** [umijs/umi#5572]
初次用域名加路由的方式打开项目的浏览器会报错  500 Internal Server Error，但是正常访问项目域名打开 项目是正常的，手动刷新后一部分浏览也是可以访问正常的
![image](https://user-images.githubusercontent.com/68887680/97101530-4bc75100-16d9-11eb-968b-038e3aa14d52.png)

**Comment by xiaohuoni** [comment]
这个应该和你的部署容器的配置有关，应该和umi无关。
