### ISSUE TITLE
[Bug] @umi-plugin-qiankun externals

### ISSUE THREAD

**Issue by jqxismygit** [umijs/umi#5575]
## What happens?

子应用是umi项目，只要配置了externals就会出错

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by jqxismygit** [comment]
找了好久终于解决了！

**Comment by jqxismygit** [comment]
debug了好久，终于找到问题了

**Comment by jqxismygit** [comment]
debug了好久，找到问题了
![image](https://user-images.githubusercontent.com/6635900/97287495-9e427200-187f-11eb-823c-aea01441df01.png)


该配置是子项目的配置，配置完之后会报这个错

![image](https://user-images.githubusercontent.com/6635900/97287622-c5993f00-187f-11eb-8b76-dabcf92d67eb.png)

config.output.libraryTarget('umd').library(`${api.pkg.name}-[name]`);

qiankun的子项目会用把libraryTarget改成umd
![image](https://user-images.githubusercontent.com/6635900/97288039-435d4a80-1880-11eb-803e-f30a0012afd7.png)

这个root["window.React"]是undefined，正确的应该是root["React"]

所以只需要把配置改成
  externals: {
    react: 'React',
    'react-dom': 'ReactDOM',
  }
就可以了

**Comment by EddieUp** [comment]
感谢大佬

**Comment by cnInkHao** [comment]
externals配置后 antd静态资源地址从哪里找到？
类似“https://gw.alipayobjects.com/os/lib/react/16.13.1/umd/react.development.js”的地址

**Comment by feaswcy** [comment]
好坑
