### ISSUE TITLE
[Bug] 单独使用 @umijs/plugin-initial-state 插件报错

### ISSUE THREAD

**Issue by Lzw2016** [umijs/umi#5577]
## What happens?

单独使用 @umijs/plugin-initial-state 插件报错

```
"umi": "^3.2.24",
"umi-request": "^1.3.5",
"@umijs/plugin-model": "^2.5.5",
"@umijs/plugin-initial-state": "^2.2.1",
"@umijs/fabric": "^2.3.1",
"antd-dayjs-webpack-plugin": "^1.0.1",
```

![` O TS43AW`%$_N8ZF2OAKF](https://user-images.githubusercontent.com/19291563/97247885-83e6a500-183b-11eb-97bb-41d3d012f547.png)

![image](https://user-images.githubusercontent.com/19291563/97248266-5c440c80-183c-11eb-8760-4e51b30e5b60.png)

使用 @umijs/preset-react 这个插件才能正常

```
"umi": "^3.2.24",
"umi-request": "^1.3.5",
"@umijs/preset-react": "^1.6.14",
"@umijs/fabric": "^2.3.1",
"antd-dayjs-webpack-plugin": "^1.0.1",
```

## Context

- **Umi Version**:

"umi": "^3.2.24"

- **Node Version**:

node v12.19.0

- **Platform**:

win10

**Comment by ttys026** [comment]
see: https://umijs.org/plugins/plugin-initial-state

文档里有提到：本插件不可直接使用，必须搭配 @umijs/plugin-model 一起使用。

**Comment by Lzw2016** [comment]
> see: https://umijs.org/plugins/plugin-initial-state
> 
> 文档里有提到：本插件不可直接使用，必须搭配 @umijs/plugin-model 一起使用。

我使用了 @umijs/plugin-model 还是有问题，我的部分依赖如下：

```
"umi": "^3.2.24",
"umi-request": "^1.3.5",
"@umijs/plugin-model": "^2.5.5",
"@umijs/plugin-initial-state": "^2.2.1",
"@umijs/fabric": "^2.3.1",
"antd-dayjs-webpack-plugin": "^1.0.1",
```

**Comment by KellenHe** [comment]
@umijs/preset-react 是umi所有插件的前提吧

**Comment by leftstick** [comment]
给个可复现repo

**Comment by lidroid** [comment]
这个bug目前一直存在，去掉preset-react依赖添加umijs/plugin-model和umijs/plugin-initial-state就可以复现这个问题，开发人员关注一下吧
