### ISSUE TITLE
在项目代码中如何获取.umirc.ts下的配置信息

### ISSUE THREAD

**Issue by wansuiasdn** [umijs/umi#5580]
想在某个页面或组件中获取整个项目的所有路由信息，不是仅当前页面的路由信息，求破

**Comment by dongfg** [comment]
`props.routes`

**Comment by ycjcl868** [comment]
`props.route.routes`

**Comment by deaver1248** [comment]
#include   <iostream>

using namespace std;

{
cout  <<next please>>endl;
 
return 0;
}
