### ISSUE TITLE
请问umi的路由配置，component可以配置成npm导出的组件吗

### ISSUE THREAD

**Issue by KellenHe** [umijs/umi#5581]
比如把一个组件打包成npm包并在package.json里添加依赖。
在路由配置里能否这样配置

`
import { mycomponent } from 'mypackage';

export default {
  routes: [
    {  path: '/', component: mycomponent  },
  ],
}
`

或者有别的方法可以实现类似的功能。

**Comment by deaver1248** [comment]
#include   <iostream>

using namespace std;

int main()
{

cout << not to sure what I need to do << endl,

**Comment by deaver1248** [comment]
Module.<anonymous>
.ali-data-query-[MasterT]/node_modules/mini-create-react-context/dist/esm/index.js:176
