### ISSUE TITLE
开启dynamicImport 跳转带query路由参数layout会重新渲染，跳转普通路由不带参数的就不会重新渲染！！！

### ISSUE THREAD

**Issue by wiscgazf** [umijs/umi#5584]
version umi  3.2.23

开启dynamicImport 跳转带query路由参数layout会重新渲染，跳转普通路由不带参数的就不会重新渲染！！！

**Comment by wiscgazf** [comment]
补充说明：如果是通过鼠标点击query参数跳转 ， 又不会出现问题了， 但是通过地址栏输入参数在跳转 就会出现layout重新渲染，重新渲染其实也没有问题，就是感觉体验不好 会有一瞬间的闪白屏，我看VUE通过地址栏输入跳转 虽然渲染了layout  但是页面 很自然 不会出现白屏闪屏

**Comment by poet-CN** [comment]
遇到了相同的问题。

**Comment by poet-CN** [comment]
遇到了相同的问题。
开启dynamicImport的情况下，例如，路由处在【'/'】，代码中有个逻辑使【history.push('/?query=123')】，这个页面就会重载，即触发【componentDidMount】与【componentDidUpdate】。然而不开启dynamicImport的情况下，页面只会触发【componentDidUpdate】，并不会重载。
