### ISSUE TITLE
[RFC] upgrade webpack 5

### ISSUE THREAD

**Issue by ycjcl868** [umijs/umi#5589]
## 背景

> 描述你希望解决的问题的现状，附上相关的 issue 地址

## 思路

> 描述大概的解决思路，可以包含 API 设计和伪代码等

## 跟进

- [ ] some task
- [ ] PR URL

**Comment by chunterg** [comment]
引入plugin-webpack5后内存会爆

**Comment by ycjcl868** [comment]
> 引入plugin-webpack5后内存会爆

使用 yarn 方式安装，cnpm 会引发模块引入死循环

**Comment by Artoria-0x04** [comment]
计划什么时候更新？

**Comment by urielvan** [comment]
今天装了 plugin-webpack5 之后直接就报错了
https://github.com/webpack/webpack/pull/7824 这个 PR 2年多之前就已经合并了，webpack 也都已经 5.11 了，难道开发组的还在用 beta 版？

**Comment by shengbeiniao** [comment]
mark，坐等更新
