### ISSUE TITLE
[Bug] say something There are multiple modules with names that only differ in casing. This can lead to unexpected behavior when compiling on a filesystem with other case-semantic...

### ISSUE THREAD

**Issue by 521707** [umijs/umi#5591]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:
在React中的一个页面上把另一个页面当做组件使、出现：There are multiple modules with names that only differ xxxxx....
虽然不影响使用，但是如何把这个告警给解决了呢
![image](https://user-images.githubusercontent.com/37111718/97415286-f9d43480-193f-11eb-95a8-ca0d858ed2cd.png)
![IBM70@8NY@ $P7B)6P}5XT9](https://user-images.githubusercontent.com/37111718/97415653-7830d680-1940-11eb-9f75-f158e5bb1806.png)

**Comment by ycjcl868** [comment]
这个看提示是模块大小写问题，检查下模块大小写

https://stackoverflow.com/questions/47534267/webpack-there-are-multiple-modules-with-names-that-only-differ-in-casing-but

**Comment by xiaofuliang** [comment]
@521707 请问解决没，遇到同样问题，组件被其他地方引用 会报
