### ISSUE TITLE
[Bug] Umi 引用 APP_ROOT 外 ts 文件失效问题

### ISSUE THREAD

**Issue by ycjcl868** [umijs/umi#5594]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

[umi-ts.zip](https://github.com/umijs/umi/files/5475348/umi-ts.zip)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

![image](https://user-images.githubusercontent.com/13595509/97873704-dfe27b00-1ccc-11eb-8cd5-09c3476e2dde.png)

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by caoxiemeihao** [comment]
> 控制台输出

`yarn umi:build
yarn run v1.22.4
$ cross-env DIST=dist YPSHOP_ENV=sit APP_ROOT=src/render umi build

✖ Webpack
  Compiled with some errors in 26.67s

 ERROR  Failed to compile with 1 errors                                                                 1:16:15 PM

 error  in ./common/aclas.ts

Module parse failed: Unexpected token (17:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| /** 下发状态码 */
> export interface ErrorCode {
|   256: '已初始化',
|   257: '未初始化',

 @ ./src/render/utils/aclas-addons/index.ts 14:0-123 56:34-49 56:54-76 60:20-34 60:42-56 62:6-20 62:34-48 139:20-37 139:40-49 198:21-30 244:15-24 256:15-24
 @ ./src/render/pages/OperateManage/models/plu-200918.ts
 @ ./src/render/.umi-production/plugin-dva/dva.ts
 @ ./src/render/.umi-production/plugin-dva/runtime.tsx
 @ ./src/render/.umi-production/core/pluginRegister.ts
 @ ./src/render/.umi-production/umi.ts
 @ multi ./src/render/.umi-production/umi.ts`

--------------------------------------------

> common/aclas.ts

`export const ACLAS_ADDONS = '@Aclas/addons'
export const ADDONS_TYPE = { cpp: 'C++', csharp: 'C#' }
export const ADDONS_TYPE_DEFAULT = ADDONS_TYPE.cpp
/** 电子秤标签-保质期(按日期/见包装) */
export const ACLAS_ValidDate = '@Aclas/ValidDate'
export const ValidDate_TYPE = {
  date: '按日期',
  /** 普通模板 */
  date_value: 0,
  pack: '见包装',
  /** 见包装模板(约定) */
  pack_value: 2,
}
export const ValidDate_TYPE_DEFAULT = ValidDate_TYPE.date

/** 下发状态码 */
export interface ErrorCode {
  256: '已初始化',
  257: '未初始化',
  258: '设备不存在',
  259: '不支持的协议类型',
  260: '该数据类型不支持此操作',
  261: '该数据类型不支持',
  264: '无法打开输入文件',
  265: '字段数与内容数不匹配',
  266: '通讯数据异常',
  267: '解析数据异常',
  268: 'CodePage错误',
  269: '无法创建输出文件',

  0: 'sucessed',
  1: 'processing',

  // 自定义错误
  401: '报错 [写入 plu.txt 失败]',
  403: '报错 [链接超时]',
  404: '报错 [加载 AclasSDK.dll 失败]',
  405: '报错 [polyfill addons.]',
  406: '报错 [子进程拉起多次失败]',
  407: '报错 [C# addons 子进程]',
  408: '报错 [C# addons 正在运行]',
  409: '报错 [trycatch 未知异常]',
  501: 'ping [超时]',
  502: 'ping [不通]',
}
export const code_dict: ErrorCode = {
  256: '已初始化',
  257: '未初始化',
  258: '设备不存在',
  259: '不支持的协议类型',
  260: '该数据类型不支持此操作',
  261: '该数据类型不支持',
  264: '无法打开输入文件',
  265: '字段数与内容数不匹配',
  266: '通讯数据异常',
  267: '解析数据异常',
  268: 'CodePage错误',
  269: '无法创建输出文件',

  0: 'sucessed',
  1: 'processing',

  // 自定义错误
  401: '报错 [写入 plu.txt 失败]',
  403: '报错 [链接超时]',
  404: '报错 [加载 AclasSDK.dll 失败]',
  405: '报错 [polyfill addons.]',
  406: '报错 [子进程拉起多次失败]',
  407: '报错 [C# addons 子进程]',
  408: '报错 [C# addons 正在运行]',
  409: '报错 [trycatch 未知异常]',
  501: 'ping [超时]',
  502: 'ping [不通]',
}

/** code 大于 2 均为报错；(2: 主动停止下发) */
export const ErrorBoundaryCode = 2
`

**Comment by ycjcl868** [comment]
> > 控制台输出
> 
> ```shell
> yarn umi:build
> yarn run v1.22.4
> $ cross-env DIST=dist YPSHOP_ENV=sit APP_ROOT=src/render umi build
> 
> ✖ Webpack
>   Compiled with some errors in 26.67s
> 
>  ERROR  Failed to compile with 1 errors                                                                 1:16:15 PM
> 
>  error  in ./common/aclas.ts
> 
> Module parse failed: Unexpected token (17:7)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> |
> | /** 下发状态码 */
> > export interface ErrorCode {
> |   256: '已初始化',
> |   257: '未初始化',
> 
>  @ ./src/render/utils/aclas-addons/index.ts 14:0-123 56:34-49 56:54-76 60:20-34 60:42-56 62:6-20 62:34-48 139:20-37 139:40-49 198:21-30 244:15-24 256:15-24
>  @ ./src/render/pages/OperateManage/models/plu-200918.ts
>  @ ./src/render/.umi-production/plugin-dva/dva.ts
>  @ ./src/render/.umi-production/plugin-dva/runtime.tsx
>  @ ./src/render/.umi-production/core/pluginRegister.ts
>  @ ./src/render/.umi-production/umi.ts
>  @ multi ./src/render/.umi-production/umi.ts
> ```
> 
> > common/aclas.ts
> 
> ```ts
> export const ACLAS_ADDONS = '@Aclas/addons'
> export const ADDONS_TYPE = { cpp: 'C++', csharp: 'C#' }
> export const ADDONS_TYPE_DEFAULT = ADDONS_TYPE.cpp
> /** 电子秤标签-保质期(按日期/见包装) */
> export const ACLAS_ValidDate = '@Aclas/ValidDate'
> export const ValidDate_TYPE = {
>   date: '按日期',
>   /** 普通模板 */
>   date_value: 0,
>   pack: '见包装',
>   /** 见包装模板(约定) */
>   pack_value: 2,
> }
> export const ValidDate_TYPE_DEFAULT = ValidDate_TYPE.date
> 
> /** 下发状态码 */
> export interface ErrorCode {
>   256: '已初始化',
>   257: '未初始化',
>   258: '设备不存在',
>   259: '不支持的协议类型',
>   260: '该数据类型不支持此操作',
>   261: '该数据类型不支持',
>   264: '无法打开输入文件',
>   265: '字段数与内容数不匹配',
>   266: '通讯数据异常',
>   267: '解析数据异常',
>   268: 'CodePage错误',
>   269: '无法创建输出文件',
> 
>   0: 'sucessed',
>   1: 'processing',
> 
>   // 自定义错误
>   401: '报错 [写入 plu.txt 失败]',
>   403: '报错 [链接超时]',
>   404: '报错 [加载 AclasSDK.dll 失败]',
>   405: '报错 [polyfill addons.]',
>   406: '报错 [子进程拉起多次失败]',
>   407: '报错 [C# addons 子进程]',
>   408: '报错 [C# addons 正在运行]',
>   409: '报错 [trycatch 未知异常]',
>   501: 'ping [超时]',
>   502: 'ping [不通]',
> }
> export const code_dict: ErrorCode = {
>   256: '已初始化',
>   257: '未初始化',
>   258: '设备不存在',
>   259: '不支持的协议类型',
>   260: '该数据类型不支持此操作',
>   261: '该数据类型不支持',
>   264: '无法打开输入文件',
>   265: '字段数与内容数不匹配',
>   266: '通讯数据异常',
>   267: '解析数据异常',
>   268: 'CodePage错误',
>   269: '无法创建输出文件',
> 
>   0: 'sucessed',
>   1: 'processing',
> 
>   // 自定义错误
>   401: '报错 [写入 plu.txt 失败]',
>   403: '报错 [链接超时]',
>   404: '报错 [加载 AclasSDK.dll 失败]',
>   405: '报错 [polyfill addons.]',
>   406: '报错 [子进程拉起多次失败]',
>   407: '报错 [C# addons 子进程]',
>   408: '报错 [C# addons 正在运行]',
>   409: '报错 [trycatch 未知异常]',
>   501: 'ping [超时]',
>   502: 'ping [不通]',
> }
> 
> /** code 大于 2 均为报错；(2: 主动停止下发) */
> export const ErrorBoundaryCode = 2
> ```
> 
> > 业务代码
> 
> ```ts
> import { ACLAS_ValidDate, ValidDate_TYPE, ValidDate_TYPE_DEFAULT, code_dict, ErrorBoundaryCode } from '@root/common/aclas'
> 
> // ***
> /**
>  * 监听主进程过来的下发状态
>  */
> if (!window._already_on_dispatchDZC) {
>   ipcRenderer.on('dispatch-dzc', function (event, json: CallbackArgs) {
>     const { code, index, total, extra: host } = json
>     const param: CallbackArgsExtend = {
>       ...json, done: code !== 1, host,
>       error: code > ErrorBoundaryCode ? code_dict[code] // code > 2
>         : code === 1 ? `${~~(index / total * 100)}% | ${total}` : '成功', // 0 = 成功
>     }
>     if (process.env.NODE_ENV === 'development') { console.log(json) }
>     ypEvent.emit(DISPATCH_DZC_FEEDBACK, param)
>   })
>   window._already_on_dispatchDZC = true
> }
> ```

来个复现链接，我试下
