### ISSUE TITLE
[Bug] umi@3 开启immer IE11报错

### ISSUE THREAD

**Issue by simonyouth** [umijs/umi#5595]
## What happens?

使用umi@3，配置immer开启，IE11报错，`Immer] minified error nr 19: ES5. Find the full error at: https://bit.ly/38PiBHb`

## 复现步骤，错误日志以及相关配置

使用 `yarn create @umijs/umi-app` 创建项目，安装依赖（当dva-immer依赖immer@7版本）,运行项目，使用ie浏览器看，就会报错。

immer6+之后需要手动require，但是umi没有提供可以使用的入口文件，即便在global.ts里尝试`enableES5()`也不生效。

## 相关环境信息

- **Umi 版本**：3.2.19
- **Node 版本**：12.16.3
- **操作系统**：win10

**Comment by simonyouth** [comment]
阔不阔以帮帮卑微的打工人？

**Comment by afc163** [comment]
https://stackoverflow.com/a/62321664/3040605

**Comment by simonyouth** [comment]
> https://stackoverflow.com/a/62321664/3040605

我上面说了，我找不到一个合适的入口文件去引入这些enable。global.ts, layout/index.ts都不行

**Comment by afc163** [comment]
@simonyouth 看看怎么解决比较好，直接 PR 吧~

**Comment by ycjcl868** [comment]
> > https://stackoverflow.com/a/62321664/3040605
> 
> 我上面说了，我找不到一个合适的入口文件去引入这些enable。global.ts, layout/index.ts都不行

app.ts 呢？

**Comment by simonyouth** [comment]
> > > https://stackoverflow.com/a/62321664/3040605
> > 
> > 
> > 我上面说了，我找不到一个合适的入口文件去引入这些enable。global.ts, layout/index.ts都不行
> 
> app.ts 呢？

不行呐 app.ts是运行时配置文件，更不行了

**Comment by LiuJinYang9527** [comment]
这个问题请问你解决了吗

**Comment by a982564562** [comment]
请问这个问题解决了嘛

**Comment by Baoyx007** [comment]
在 app.ts 中是可以的.

但是, 要确保 import 的 immer 和 dva 的 immer 是一个版本

**Comment by sorrycc** [comment]
已支持，参考 https://umijs.org/plugins/plugin-dva#immer 。
