### ISSUE TITLE
[Bug] alias配置别名后没有生效，报错：This dependency was not found

### ISSUE THREAD

**Issue by fc1904** [umijs/umi#5596]
## 问题
在.umirc.ts文件的alias中增加了配置项：
`@components': resolve(__dirname, '../src/components'), `
在pages/index.jsx中尝试使用@components：
`import components from '@components';`
umi 报错
![image](https://user-images.githubusercontent.com/19899590/97681127-bfe76780-1ad2-11eb-8cfd-e3733028b652.png)

之后尝试使用chainWebpack进行添加，错误依旧，代码如下：
` config.resolve.alias.set(
      '@components',
      resolve(__dirname, '../src/components'),
    );`

## 问题复现仓库地址

[https://github.com/fc1904/question-box/tree/dev](https://github.com/fc1904/question-box/tree/dev)

## 如何复现
clone仓库 安装依赖后 umi dev 即可

## Context

- **Umi Version**: umi@3.2.24
- **Node Version**: v12.14.0
- **Platform**: windows 10

**Comment by ycjcl868** [comment]
用 https://umijs.org/config#alias

**Comment by KumaCool** [comment]
我在 config/config.ts
```
alias: {
        '#': '/src',
        '@': '/src/components',
        '~': '/src/common'
    },
```
以及 tsconfig.json
```
"paths": {
            "#/*": ["./src/*"],
            "@@/*": ["./src/.umi/*"],
            "@/*": ["./src/components/*"],
            "~/*": ["./src/common/*"]
        }
```
两个文件中设置了,都无效,vscode可以识别,但运行报错.
奇怪的是前两天未配置config中的alias还有效果的.

**Comment by fc1904** [comment]
> 用 https://umijs.org/config#alias


> 下图为我的配置项截图，
![image](https://user-images.githubusercontent.com/19899590/97834428-cf54f380-1d12-11eb-9eae-4a3a858ab728.png)



> 用 https://umijs.org/config#alias

下图是我的配置项截图，官方文档上alias的配置和2.x版本好像没啥区别吧，配置项在2.x是生效的，使用3.x版本就不行了
![image](https://user-images.githubusercontent.com/19899590/97834728-7f2a6100-1d13-11eb-996f-64f3aa362659.png)

**Comment by fc1904** [comment]
> 用 https://umijs.org/config#alias
感谢回复，以下是我的配置项截图，希望能有助于分析问题；
此配置项在2.x是可以生效的，但是在使用3.x构建的项目中导致了报错，alias的配置项相较于2.x版本其实并没有改动，还是不太清楚是否是我的写法问题还是确实存在bug
![image](https://user-images.githubusercontent.com/19899590/97834860-cca6ce00-1d13-11eb-8683-e3555053a8df.png)

**Comment by fc1904** [comment]
@ycjcl868

**Comment by Lemonreds** [comment]
同样的问题，3.2.27

**Comment by dongxiaoyong009** [comment]
有人解决这个问题吗？两个月前遇到了，现在还没解决呢
