### ISSUE TITLE
[Bug] 开启了dark主题后，如何自定义dark模式下的样式？

### ISSUE THREAD

**Issue by travonf** [umijs/umi#5602]
## What happens?

开启了dark主题后，如何自定义dark模式下的样式？
观察antd官网切换主题的行为，会在切换为dark或者compact后给body加上data-theme属性，
这样其他的组件比如说Tabs可以针对dark/compact模式覆写样式，现在这边还不行

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by ycjcl868** [comment]
用 [theme](https://umijs.org/config#theme)

**Comment by travonf** [comment]
> 用 [theme](https://umijs.org/config#theme)

如何覆写antd组件的样式，比如说[Antd Tabs](https://ant.design/components/tabs-cn/#components-tabs-demo-card-top)这里的选择器写法
