### ISSUE TITLE
onRouteChange或onPageChange方法中能调用Hooks修改Model的数据吗？[Bug] 

### ISSUE THREAD

**Issue by shaohuatsou** [umijs/umi#5603]
想修改model的数据，这个里面又不能用hook，直接改变的话页面又不渲染，请问需要怎么做？

**Comment by GreatAuk** [comment]
@shaohuatsou 请问这个问题怎么解决的？

**Comment by shaohuatsou** [comment]
我忘记当时为啥有这样的场景了，现在升级V5好像没有这样的问题。

**Comment by GreatAuk** [comment]
我想知道的是在 `onRouteChange` 里面怎么使用 `hooks` 修改` model`。
![image](https://user-images.githubusercontent.com/20253809/104142455-a6c63580-53f6-11eb-9131-1e690c4915e0.png)

还是有在非组件，或非 `hooks function` 里使用 `hooks` 修改 `model` 的场景的

**Comment by shaohuatsou** [comment]
那就不太清楚了，之前V4我也没解决，后来升级V5之后换了其他方式，大概就是使用hook提供的设置方法来设置值

**Comment by heyuuuu** [comment]
> 那就不太清楚了，之前V4我也没解决，后来升级V5之后换了其他方式，大概就是使用hook提供的设置方法来设置值

怎么解决的？
