### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by eaststrong** [umijs/umi#5604]
TypeError: Object(...) is not a function
getAuthorityFromRouter/authority<
./src/utils/utils.ts:38

  35 |   pathname: string,
  36 | ): T | undefined => {
  37 |   const authority = router.find(
> 38 |     ({ routes, path = '/', target = '_self' }) =>
  39 |       (path && target !== '_blank' && pathRegexp(path).exec(pathname)) ||
  40 |       (routes && getAuthorityFromRouter(routes, pathname)),
  41 |   );

getAuthorityFromRouter
./src/utils/utils.ts:37

  34 |   router: T[] = [],
  35 |   pathname: string,
  36 | ): T | undefined => {
> 37 |   const authority = router.find(
  38 |     ({ routes, path = '/', target = '_self' }) =>
  39 |       (path && target !== '_blank' && pathRegexp(path).exec(pathname)) ||
  40 |       (routes && getAuthorityFromRouter(routes, pathname)),

BasicLayout
http://localhost:8000/layouts__BasicLayout.js:1566:96

  1563 | }; // get children authority
  1564 | 
  1565 | 
> 1566 | var authorized = Object(_utils_utils__WEBPACK_IMPORTED_MODULE_13__["getAuthorityFromRouter"])(props.route.routes, location.pathname || '/') || {
       |                                                                                              ^  1567 |   authority: undefined
  1568 | };
  1569 |

**Comment by afc163** [comment]
给重现。

**Comment by bing127** [comment]
我也是遇到同样的问题

`×
TypeError: Object(...) is not a function
Module../config/config.ts
./config/config.ts:8
   5 | 
   6 | const { REACT_APP_ENV } = process.env;
   7 | 
>  8 | export default defineConfig({
   9 |   hash: true,
  10 |   antd: {},
  11 |   dva: {
View compiled
__webpack_require__
./webpack/bootstrap:837
  834 | };
  835 | 
  836 | // Execute the module function
> 837 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  838 | 
  839 | // Flag the module as loaded
  840 | module.l = true;
View compiled
fn
./webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
      | ^  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
Module../src/app.tsx
http://10.3.1.119:8000/umi.js:185668:73
__webpack_require__
./webpack/bootstrap:837
  834 | };
  835 | 
  836 | // Execute the module function
> 837 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  838 | 
  839 | // Flag the module as loaded
  840 | module.l = true;
View compiled
fn
./webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
      | ^  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
Module../src/.umi/core/pluginRegister.ts
./src/.umi/core/pluginRegister.ts:1
> 1 | // @ts-nocheck
  2 | import { plugin } from './plugin';
  3 | import * as Plugin_0 from '/Users/wxb/Documents/backEnd_project/go_project/go-admin/go-admin-antd/src/app.tsx';
  4 | import * as Plugin_1 from '/Users/wxb/Documents/backEnd_project/go_project/go-admin/go-admin-antd/node_modules/_umi-plugin-antd-icon-config@2.0.3@umi-plugin-antd-icon-config/lib/app.js';
View compiled
__webpack_require__
./webpack/bootstrap:837
  834 | };
  835 | 
  836 | // Execute the module function
> 837 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  838 | 
  839 | // Flag the module as loaded
  840 | module.l = true;
View compiled
fn
./webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
      | ^  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
Module../src/.umi/umi.ts
./src/.umi/umi.ts:1
> 1 | // @ts-nocheck
  2 | import './core/polyfill';
  3 | import '@@/core/devScripts';
  4 | import '../global.tsx';
View compiled
__webpack_require__
./webpack/bootstrap:837
  834 | };
  835 | 
  836 | // Execute the module function
> 837 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  838 | 
  839 | // Flag the module as loaded
  840 | module.l = true;
View compiled
fn
./webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
      | ^  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
0
http://10.3.1.119:8000/umi.js:188163:18
__webpack_require__
./webpack/bootstrap:837
  834 | };
  835 | 
  836 | // Execute the module function
> 837 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  838 | 
  839 | // Flag the module as loaded
  840 | module.l = true;
View compiled
(anonymous function)
./webpack/bootstrap:1016
  1013 | 
  1014 | 
  1015 | // Load entry module and return exports
> 1016 | return hotCreateRequire(0)(__webpack_require__.s = 0);
       | ^  1017 | 
View compiled
(anonymous function)
http://10.3.1.119:8000/umi.js:1020:10
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.`

**Comment by williamnie** [comment]
可能是加载顺序的问题，给个复现才好查

**Comment by ycjcl868** [comment]
import * from 'umi' 里的包加载晚了
