### ISSUE TITLE
升级到umi3 项目工程起不来了  [Bug] 

### ISSUE THREAD

**Issue by Mh2336393** [umijs/umi#5609]
## What happens?

![image](https://user-images.githubusercontent.com/48132028/97949168-ba896600-1dcd-11eb-8567-23cb4e1e38e5.png)
![image](https://user-images.githubusercontent.com/48132028/97949190-c9701880-1dcd-11eb-8dd2-e9a2338b96f4.png)
![image](https://user-images.githubusercontent.com/48132028/97949209-d68d0780-1dcd-11eb-8892-e10f75ce471a.png)
![image](https://user-images.githubusercontent.com/48132028/97949268-0b00c380-1dce-11eb-8c8d-782ea13bc2f1.png)

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by Mh2336393** [comment]
算了还原了umi2吧

**Comment by afc163** [comment]
重装 node_modules 了么

**Comment by Mh2336393** [comment]
重装了 https://umijs.org/zh-CN/docs/upgrade-to-umi-3  按照这个步骤来的

**Comment by afc163** [comment]
给个重现的 repo 吧。

**Comment by Mh2336393** [comment]
正在压缩 稍等

**Comment by Mh2336393** [comment]
[client.zip](https://github.com/umijs/umi/files/5479355/client.zip)
[Uploading client.zip…]()

**Comment by afc163** [comment]
Pro 的项目你可以参考一下：https://umijs.org/guide/upgrade-antd-pro-to-umi-3

注意 `'umi/locale'` 和 `'umi-plugin-react/locale'` 一样需要修改。

**Comment by Mh2336393** [comment]
HAO

**Comment by Mh2336393** [comment]
antd 组件库也要升级到4.+ 吧 文档上没有说

**Comment by afc163** [comment]
> antd 组件库也要升级到4.+ 吧 文档上没有说

不需要的，umi 3 可以和 antd 3 一起工作。

**Comment by Mh2336393** [comment]
![image](https://user-images.githubusercontent.com/48132028/98113332-78037e80-1ede-11eb-8861-1b17fa178c43.png)
![image](https://user-images.githubusercontent.com/48132028/98113444-a2edd280-1ede-11eb-9efa-73c8e68018e1.png)

**Comment by afc163** [comment]
@ycjcl868 看看是这样的么？

**Comment by afc163** [comment]
@ant-design/icons 现在是独立包，可以和 antd@3 一起工作。

**Comment by Mh2336393** [comment]
感谢 大佬。太谢谢了。。其实以后也会去升级 antd组件库。 但是别人等着往分支里提交东西，我短时间又搞不完 所以想先兼容处理一下。
