### ISSUE TITLE
启动项目非常的慢

### ISSUE THREAD

**Issue by Mh2336393** [umijs/umi#5610]
## 背景

> 描述你希望解决的问题的现状，附上相关的 issue 地址
![image](https://user-images.githubusercontent.com/48132028/97967457-31d3ef80-1df8-11eb-9e12-2de3474a49a5.png)

## 思路

> 描述大概的解决思路，可以包含 API 设计和伪代码等

## 跟进

- [ ] some task
- [ ] PR URL

**Comment by Mh2336393** [comment]
就是因为这个原因才想要升级 到umi3，然后升级过程中也遇到非常多的问题。。花了很多时间 现在还没有解决完

**Comment by ycjcl868** [comment]
https://umijs.org/guide/boost-compile-speed#%E9%85%8D%E7%BD%AE-nodemodulestransform-%E4%B8%BA---type-none-

**Comment by Mh2336393** [comment]
谢谢大佬。。我说么 咋回事 升级了umi3 还是感觉好慢

**Comment by Mh2336393** [comment]
![image](https://user-images.githubusercontent.com/48132028/97989035-e54cdc00-1e18-11eb-9314-f7473afe0cb8.png)
加了这个还是很慢 启动一下得好几分钟
