### ISSUE TITLE
[Bug] history配置中的getUserConfirmation 参数问题，目前不可配置

### ISSUE THREAD

**Issue by johanazhu** [umijs/umi#5625]
## What happens?

如题，希望 Prompt 效果，看[issue](https://github.com/umijs/umi/pull/3935)，这个问题已经被修复了，但是文档中又写道不可配置，我按照 3935 中的demo做了下，但是 prompt 没有出现
望解答~~

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by zhiyuc123** [comment]
https://github.com/umijs/umi/pull/3935 已关闭，应以文档为准

离开确认可以通过 https://github.com/umijs/umi/issues/1688 中给出的方案实现
https://github.com/umijs/umi/issues/1688#issuecomment-450270173
https://github.com/umijs/umi/issues/1688#issuecomment-451353419

**Comment by johanazhu** [comment]
> #3935 已关闭，应以文档为准
> 
> 离开确认可以通过 #1688 中给出的方案实现
> [#1688 (comment)](https://github.com/umijs/umi/issues/1688#issuecomment-450270173)
> [#1688 (comment)](https://github.com/umijs/umi/issues/1688#issuecomment-451353419)

试了下，是可以的，3Q

**Comment by liuxiansheng2018** [comment]
@johanazhu 请问你是如何实现的

**Comment by johanazhu** [comment]
> @johanazhu 请问你是如何实现的

如上，1688给出方案了。https://github.com/umijs/umi/issues/1688#issuecomment-450270173

**Comment by liuxiansheng2018** [comment]
@johanazhu 我看了一下我并没有明白
![image](https://user-images.githubusercontent.com/35281468/106416512-8258f880-648c-11eb-8a1e-877b8f22159a.png)这些东西不明白在哪里配置

**Comment by johanazhu** [comment]
看boxcc的回答，引入react-router-navigation-prompt

**Comment by liuxiansheng2018** [comment]
@johanazhu 发现了，但是发现页面刷新时，和离开的页面的的样式都不一样了，

**Comment by johanazhu** [comment]
离开页面时的样子是浏览器默认的样子吗？你可以好好看看react-router-navigation-prompt这个库，有可以自定义样式的方法

**Comment by liuxiansheng2018** [comment]
![image](https://user-images.githubusercontent.com/35281468/106417786-ca2d4f00-648f-11eb-8cd7-f04b90254e65.png)
![image](https://user-images.githubusercontent.com/35281468/106417811-daddc500-648f-11eb-9fd4-c48793640a54.png) 使用了这个库之后发现 刷新页面时会弹出图二， 离开页面时弹出图一， 现在想让它们样式逻辑都跟自定义样式一样，发现无法做到

**Comment by liuxiansheng2018** [comment]
@johanazhu

**Comment by johanazhu** [comment]
Look this。https://www.npmjs.com/package/react-router-navigation-prompt
