### ISSUE TITLE
umi2中 publicPath 只在build的时候生效， dev不生效

### ISSUE THREAD

**Issue by xuanxuan321** [umijs/umi#5627]
## What happens?

umi2中 publicPath 只在build的时候生效， dev不生效。

**Expected behavior** 1. 2.
在dev时也生效
## Context

- **Umi Version**:2.13.13
- **Node Version**:12.12
- **Platform**:mac

**Comment by xiaohuoni** [comment]
dev的时候为何要生效？

**Comment by wswDotaIT** [comment]
基座qiankun，子应用umi项目，子应用在dev时，怎么设置publicPath~
