### ISSUE TITLE
[Bug] umi3 koa+ssr 正式环境部署降级为 csr 渲染

### ISSUE THREAD

**Issue by muzqi** [umijs/umi#5629]
## What happens?
使用 umi/examples/ssr-koa/ 搭建的项目，本地环境跑 npm start 后能够正常 ssr 渲染。使用 docker 部署到正式环境服务器后，执行了 csr 渲染，请问在什么情况下 umi 会执行降级处理？

- **3.2.25**：
- **10.17.0**：
- **Macos 10.15.7**：

**Comment by ycjcl868** [comment]
报错才会降级，看下报错日志

**Comment by ibandeng** [comment]
@muzqi 请问你解决了吗？报错日志从哪里看
