### ISSUE TITLE
umi dev启动，修改文件不会自动刷新页面（代码目录是通过挂载的方式）

### ISSUE THREAD

**Issue by icarusysuper** [umijs/umi#563]
开发方式如下：
在windows上写代码，在linux上跑代码。
通过将windows上的一个代码目录挂载到linux上，在linux上通过umi dev启动。

结果表现如下：
然后在windows上修改代码，页面不会刷新。
但在linux上直接编辑代码文件，页面是可以自动刷新的。

请问之后会支持上述开发方式也能自动刷新页面这个功能吗

**Comment by sorrycc** [comment]
有问题再 reopen 。
