### ISSUE TITLE
https://umijs.org 官网如果不手动清空浏览器缓存，一直进入的是2.0版本的网站

### ISSUE THREAD

**Issue by ctcx** [umijs/umi#5632]
因为从1.0就开始使用umi，一直到2.0，创建项目一直使用的是 create-umi，但最近发现antd已经升级到4.x，而用create-umi 还是3.x，umi 也是2.x，然后手动升级后各种报错；issues里提到umi3.x的插件配置不一样里，让去官网看插件说明。然后打开官网没有任何变化，最后换了个浏览器才进入到新的3.0的官网。麻烦在create-umi页面上给个提示啊～

**Comment by sorrycc** [comment]
是因为 2.0 开了 pwa 引起的，除了手动清缓存，目前没有好的办法。
