### ISSUE TITLE
[Bug] 当路由为动态时（如：/xx/:id）并且开启 exportStatic 时，build 报错

### ISSUE THREAD

**Issue by kaoding** [umijs/umi#5633]
![image](https://user-images.githubusercontent.com/18542211/98440540-4ab00e00-2134-11eb-9254-51835e420150.png)

**Comment by xiaohuoni** [comment]
是Windows平台吗？

**Comment by kaoding** [comment]
> 是Windows平台吗？

是的

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro/issues/7565

**Comment by xrkffgg** [comment]
试试这个 https://github.com/xrkffgg/umi-win-exportStatic
