### ISSUE TITLE
每次保存热更新后，内存一直向上涨，直到最后内存溢出

### ISSUE THREAD

**Issue by ibandeng** [umijs/umi#5634]
## What happens?

每次保存热更新后，内存一直向上涨，直到最后内存溢出
![微信截图_20201107222902](https://user-images.githubusercontent.com/47233643/98443785-aab0af80-2148-11eb-977d-065bd7586497.png)

## 相关环境信息

- **Umi 版本**：
3.2.24
- **Node 版本**：
14.15
- **操作系统**：
win10

**Comment by ycjcl868** [comment]
SSR？

**Comment by ibandeng** [comment]
> SSR？

对，是我配置有问题吗？

**Comment by shangdev** [comment]
我的情况是：1c2g服务器上开调试模式，每次保存文件CPU和内存均大幅增加（达到90%以上），如果保存太多频繁，直接导致服务器卡死。

**Comment by ycjcl868** [comment]
这个我来排查下

**Comment by iamwjj** [comment]
@ycjcl868 还没排查出来吗？这开发体验也太难受了，时不时要重新启动。

**Comment by robinv8** [comment]
> @ycjcl868 还没排查出来吗？这开发体验也太难受了，时不时要重新启动。

暂时可以在启动命令配置 NODE_OPTIONS=--max_old_space_size=8192 来增加 node 配额

**Comment by williamnie** [comment]
这块应该是require的问题导致内存上涨，在开发阶段虽然每次都会清理require进来的umi.server.js，但是貌似内存并没有真正的释放，所以会导致内存泄露，貌似暂时没啥好办法 @ycjcl868

**Comment by williamnie** [comment]
@ibandeng 提供一个复现吧，你是参照example里的例子，还是自己搭建的呢？我这边复现不了，给我个最小复现吧，

**Comment by ycjcl868** [comment]
可能是  require('./umi.server')，这个会占用不少内存

**Comment by williamnie** [comment]
> 可能是 require('./umi.server')，这个会占用不少内存

是的，我怀疑是这里，我实际测试感觉还行，会定期的释放，可能是页面太少了，如果项目太大的话，有可能会造成这个问题，还发现一个问题，现在egg的例子貌似不会热更新了，是不是没指定port造成的？

**Comment by ace0109** [comment]
出现一样的问题，不是SSR。node版本14.16是直接dev启动直接就内存溢出了。换到12.22.1，能够撑一段时间。

**Comment by LemonTree-shine** [comment]
反正是保存多次整个电脑都卡，让我说场景我说不出来，该看的文档都看了，说的配置都加上了，就是卡，项目大了，打包也卡，热更新更是卡的离谱，完全没有开发体验！

**Comment by httol** [comment]
有结果吗，开发时内存暴涨。node占用2G

**Comment by dctxf** [comment]
为毛关了？

**Comment by flwzz** [comment]
内存占用9个g啊

**Comment by williamnie** [comment]
> 内存占用9个g啊

哪个版本啊，现在还会占用这么高么？是只有开发环境这样，还是生产环境也这样？

**Comment by hyzx86** [comment]
同样的项目 antd pro 5.20 不同的电脑就出现这种内存溢出的问题
都是32G内存，另一台电脑跑到1G 就挂了。。说内存溢出

**Comment by hyzx86** [comment]
重新捣鼓了下 nvm ..好了

**Comment by airzhanglin** [comment]
大佬，最后怎么解决这个问题？能够用--max_old_space_size=4096方式解决？

**Comment by hyzx86** [comment]
> 大佬，最后怎么解决这个问题？能够用--max_old_space_size=4096方式解决？

换node版本

**Comment by airzhanglin** [comment]
> > 大佬，最后怎么解决这个问题？能够用--max_old_space_size=4096方式解决？
> 
> 换node版本

换到多少版本可以解决？

**Comment by hyzx86** [comment]
不记得了，16 ？
我用的 umi4

**Comment by OctopusRoe** [comment]
项目大了修改样式就爆内存，umi版本从2升级到3还是会出这问题，使用 NODE_OPTIONS=--max_old_space_size=8192 会解决一部分，从每次保存爆内存，到可以改多次才爆，但是修改内存大小会严重影响热更新的速度

**Comment by fz6m** [comment]
如果 umi 2、3 的项目很大，建议升级到 umi 4 ，可以新起一个 umi 4 项目一点点迁移。

否则，可以在开发时把 `routes` 路由表只配成你要开发的那个路由和 layout ，这样可以大幅减少需要预编译的内容加快速度，对于上百个页面的 umi 3 应用都是这么开发的，但构建一次可能要快一个小时，长期来看还是要升级或者分割（拆出去到微前端或者迁移一部分）。
