### ISSUE TITLE
配置网页title，无效

### ISSUE THREAD

**Issue by Oscar19921030** [umijs/umi#565]
修改.umirc.js文件
export default {
  ...
 context:{
   title:'xxx',
  }
...
};

生成的html title还是内容为空

**Comment by xiaohuoni** [comment]
配置的结构应该是
```js
export default {
  pages: {
    '/': { context: { title: 'IndexPage' } },
    '/list':  { context: { title: 'ListPage' } },
    '/路由':  { context: { title: 'ListPage' } },
  },
};
```

**Comment by xiaohuoni** [comment]
并且这并不是一个动态修改标题的方案。需要动态修改标题，可以使用react-helmet 或者react-document-title

**Comment by Oscar19921030** [comment]
https://umijs.org/docs/zh-Hans/config-umi.html，我是看这个文档里这样写 ，我就用了。那我试试react-helmet吧

**Comment by xiaohuoni** [comment]
恩，这个功能现在的是，多入口的静态标题。如文章提到的，配置，指的是，从list.html进入。标题显示ListPage。

**Comment by Oscar19921030** [comment]
谢谢回复。但是确实想提一下，这个配置文档会引起困惑，
![image](https://user-images.githubusercontent.com/20589681/40699411-b33717d6-6406-11e8-92a8-e168d10645b7.png)，按照源码，以及umi的默认模版document.ejs,这个context.title注入，让我以为整个网站的title直接可以根据这个配置方法使用。

**Comment by xiaohuoni** [comment]
我和你提过同样的疑问。估计这是一个内部需求，就没有优化

**Comment by Oscar19921030** [comment]
事实上，我没有动态修改网页标题的需求。我只是想在单页应用里，定义网页的title，然后发现，基于umi默认的document.ejs模板，加上给出的配置方案是根本不起效的。现在我自己在pages文件夹里定义了一个ejs模版，网页title写死就行了。

**Comment by Oscar19921030** [comment]
感觉这不是没有优化，而是一个bug

**Comment by xiaohuoni** [comment]
那你可以配置根目录应该是有效的。https://github.com/umijs/umi-examples/tree/master/context 可以看这个，我也是在这个上面测试，这个版本这个功能没有问题之后，再回复你的

**Comment by Oscar19921030** [comment]
ok，谢谢

**Comment by hyl1374961656** [comment]
https://github.com/umijs/umi-examples/tree/master/context  地址404
