### ISSUE TITLE
[Bug] 约定式路由自动生成的404页面与预期不符

### ISSUE THREAD

**Issue by MaxPeak** [umijs/umi#5652]
## What happens?

约定式路由自动生成的404页面与预期不符

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
- mkdir umi-demo
- cd umi-demo
- yarn create @umijs/umi-app 
- yarn
- 删除.umirc.ts里面的routes配置
- 按照官网文档在pages下面创建users、index、404

**Expected behavior** 1. 2.
预期约定式路由自动生成为：{ component: '@/pages/404' }
<img width="882" alt="WeChat57e319a3dc6d068b7373c823fc4042cf" src="https://user-images.githubusercontent.com/49097525/98634178-c5a83d00-235d-11eb-9731-18b4369b6244.png">

实际生成为：{
    "path": "/404",
    "exact": true,
    "component": require('@/pages/404.tsx').default
  }
<img width="961" alt="WeChatddedf505b88be456321ee24c48aa1d39" src="https://user-images.githubusercontent.com/49097525/98634208-d8227680-235d-11eb-9ed6-104e4e2a483e.png">

项目整体目录以及配置文件截图
<img width="901" alt="WeChat639034fcdb780aa6957a8175c4c191c5" src="https://user-images.githubusercontent.com/49097525/98634277-fee0ad00-235d-11eb-9d92-0be37fcc215f.png">

## Context

- **Umi Version**:3.2.26
- **Node Version**:14.4.0
- **Platform**:macOS 10.15.7

**Comment by bravoeguizabal** [comment]
This is not working as specified in the documentation under convention routing. After digging for a bit a found a way to make it work. Basically you have to set some route properties manually as in the code bellow:

`
import React from 'react';
import { history } from 'umi';
import { Button, Result } from 'antd';
import { MenuDataItem } from '@ant-design/pro-layout';

const NoFoundPage: React.FC<{}> & MenuDataItem = () => (
  <Result
    status="404"
    title="404"
    subTitle="Sorry, the page you visited does not exist."
    extra={
      <Button type="primary" onClick={() => history.push('/')}>
        Back Home
      </Button>
    }
  />
);

NoFoundPage.path = undefined;
NoFoundPage.exact = undefined;

export default NoFoundPage;
`

**Comment by MaxPeak** [comment]
> This is not working as specified in the documentation under convention routing. After digging for a bit a found a way to make it work. Basically you have to set some route properties manually as in the code bellow:
> 
> `
> import React from 'react';
> import { history } from 'umi';
> import { Button, Result } from 'antd';
> import { MenuDataItem } from '@ant-design/pro-layout';
> 
> const NoFoundPage: React.FC<{}> & MenuDataItem = () => (
> <Result
> status="404"
> title="404"
> subTitle="Sorry, the page you visited does not exist."
> extra={
> <Button type="primary" onClick={() => history.push('/')}>
> Back Home
> 
> }
> />
> );
> 
> NoFoundPage.path = undefined;
> NoFoundPage.exact = undefined;
> 
> export default NoFoundPage;
> `

是的，有其他解决办法，但我想这个问题还是需要解决，毕竟大部分用户都会通过文档来编码却得不到期待的结果，会和我一样产生疑惑

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/pull/6258
