### ISSUE TITLE
服务端压力过大，实测可支持并发量过小

### ISSUE THREAD

**Issue by chenhaoren** [umijs/umi#5657]
## What happens?
使用 umi 构建项目上线压测的时候，实际用户并发数并不高，但服务器cpu基本满负荷，导致无法进行进一步的压测。
压测数据： 20 并发。

## 最小可复现仓库

公司内部仓库，不允许上传。

## 复现步骤，错误日志以及相关配置
步骤： 对服务端渲染进行压测，指定并发数为20.
![image](https://user-images.githubusercontent.com/16437631/98760133-9bae5380-240d-11eb-8c3f-aa2db9b54a59.png)

## 相关环境信息

- **Umi 版本**： 3.2.0
- **Node 版本**：10.22
- **操作系统**： centos 7

**Comment by afc163** [comment]
umi 是前端项目，为啥会影响压测？

**Comment by chenhaoren** [comment]
> ~umi 是前端项目，为啥会影响压测？~
> 
> 看到了，是服务端渲染出现的问题。

定位了一下，在render 部分会有比较大的耗时。不知道 umi 的服务端渲染内部有没有做缓存，做一些 LRU 之类的优化手段。或者说有没有其他的方案可以来解决这个问题。

**Comment by ycjcl868** [comment]
> > ~umi 是前端项目，为啥会影响压测？~
> > 看到了，是服务端渲染出现的问题。
> 
> 定位了一下，在render 部分会有比较大的耗时。不知道 umi 的服务端渲染内部有没有做缓存，做一些 LRU 之类的优化手段。或者说有没有其他的方案可以来解决这个问题。

render 是纯渲染函数，不做缓存策略，缓存我理解由业务逻辑处理

**Comment by Treblex** [comment]
只有在build时候才会占这么多资源，可以缓存一下获取数据的请求试试

**Comment by chenhaoren** [comment]
> > > ~umi 是前端项目，为啥会影响压测？~
> > > 看到了，是服务端渲染出现的问题。
> > 
> > 
> > 定位了一下，在render 部分会有比较大的耗时。不知道 umi 的服务端渲染内部有没有做缓存，做一些 LRU 之类的优化手段。或者说有没有其他的方案可以来解决这个问题。
> 
> render 是纯渲染函数，不做缓存策略，缓存我理解由业务逻辑处理

业务层无法做缓存，每次请求的数据存在不一致的情况，编译结果的缓存基本无效，不能复用。

**Comment by chenhaoren** [comment]
> 只有在build时候才会占这么多资源，可以缓存一下获取数据的请求试试

每次请求数据大概率都是不一致的，组装编译出来的html也会不一致。数据请求上的缓存走不通

**Comment by ycjcl868** [comment]
https://github.com/vercel/next.js/blob/canary/examples/ssr-caching/server.js#L11-L29

可以根据这段代码改下 https://github.com/umijs/umi/tree/master/examples/ssr-with-eggjs ， 增加渲染缓存
