### ISSUE TITLE
dynamic加载动态组件，获取不到真实的组件ref

### ISSUE THREAD

**Issue by yuanguandong** [umijs/umi#5658]
## What happens?

我在使用dynamic加载一个动态组件时，发现ref没有透传给目标组件
![image](https://user-images.githubusercontent.com/13197560/98762430-96073c80-2412-11eb-8e2f-2f576bd0a48f.png)
得到的ref如下，拿不到真实目标组件的ref
![image](https://user-images.githubusercontent.com/13197560/98762611-03b36880-2413-11eb-82aa-c51532b5c32a.png)

## Context

- **Umi Version**:  umi@3.1.4
- **Node Version**:  v12.16.3
- **Platform**:  macos 10.15.6

**Comment by yuanguandong** [comment]
![image](https://user-images.githubusercontent.com/13197560/98762715-3d846f00-2413-11eb-899f-11f257b6b00c.png)
会不会是这里ref没传递下去，希望能支持一下，感谢

**Comment by sorrycc** [comment]
ref 没有传会导致啥问题？有需要直接提个 PR 吧。

**Comment by guanyuan** [comment]
相同的问题，需要给动态组件传ref，请问楼主这个问题是如何解决的？

**Comment by yuanguandong** [comment]
> 相同的问题，需要给动态组件传ref，请问楼主这个问题是如何解决的？
没有用dynamicComponents了，用不走编译的方式，运行时动态按需加载的原始方式load大型第三方库
