### ISSUE TITLE
umi支持ie11吗，脚手架生成的项目一个代码没改ie11都跑不起来

### ISSUE THREAD

**Issue by KellenHe** [umijs/umi#5660]
添加了
`  targets: {
    ie: 11,
  },`
其他一个代码没改，IE11跑不起来。

**Comment by KellenHe** [comment]
项目做了一半了，这有点坑啊。

**Comment by Slebee** [comment]
dva 的 immer先弄false是可以跑的

**Comment by KellenHe** [comment]
@Slebee 
是加这个配置吗
`  dva: {
    immer: false
  },`
还是不行。

**Comment by Slebee** [comment]
> @Slebee
> 是加这个配置吗
> ` dva: { immer: false },`
> 还是不行。

具体看报错了，我们项目前些天也是突然发现ie11不行，我用官方脚手架测试过是dva immer的问题，你的应该是其他报错？

**Comment by KellenHe** [comment]
报了语法错误，定位是在这一行
![企业微信截图_16050771343453](https://user-images.githubusercontent.com/9713892/98777941-90b6eb80-242c-11eb-9077-bdca0c7982dd.png)

**Comment by afc163** [comment]
https://github.com/umijs/umi/issues/5402

**Comment by KellenHe** [comment]
就是这里

**Comment by 552233** [comment]
同样的问题...edge和低版本的chrome也报错了

**Comment by Chenjiayuan195** [comment]
同样遇到这个问题，IE11上和低版本的Chrome都报语法错误，无法运行

**Comment by simonyouth** [comment]
看看是不是styled-components这个库，5.2.0有个正则不兼容，最新的版本改过来了，或者用5.1

**Comment by KellenHe** [comment]
我本地跑报两个错误，
1、umi.js语法错误，同
[#5402](https://github.com/umijs/umi/issues/5402)
2、devscript.js的语法错误。部署后没有devscript.js了，所以这个问题还好。
umi.js那个报错什么时候可以release？

**Comment by KellenHe** [comment]
@ycjcl868 
请问这个问题是没时候可以解决？
或者有临时解决方法吗

**Comment by xyhui** [comment]
@KellenHe 请问你这个问题解决了嘛，IE11报同样的错

**Comment by KellenHe** [comment]
@xyhui 我也在等，umi好像还没release新的版本，等最新版本发布看会不会把这个bug fix

**Comment by asdwsxzc123** [comment]
config.ts文件中修改配置可以跑起来

  nodeModulesTransform: {
    type: 'all',
  },
 dva: {
    immer: false
  },

**Comment by KellenHe** [comment]
@asdwsxzc123 实测有效

**Comment by ycjcl868** [comment]
> config.ts文件中修改配置可以跑起来
> 
> nodeModulesTransform: {
> type: 'all',
> },
> dva: {
> immer: false
> },

all 会很慢的，看是哪个包不兼容，加到  https://github.com/umijs/es5-imcompatible-versions 里

**Comment by ikun** [comment]
好像是 umijs/utils 中有代码没转义
如下配置就可以支持ie11了

nodeModulesTransform: {
    type: 'none',
    exclude: ['@umijs/utils'],
},

**Comment by quicklearning123** [comment]
@ikun @ycjcl868 IE11下仍然报错
```
function traverseModifyRoutes(routes, access) {
这行报错  const resultRoutes = [].concat(routes).map(resultRoute => {
    const routes = resultRoute.routes;

    if (routes && (routes === null || routes === void 0 ? void 0 : routes.map)) {
      return _objectSpread(_objectSpread({}, resultRoute), {}, {
        // return new route to routes.
        routes: routes === null || routes === void 0 ? void 0 : routes.map(route => _objectSpread({}, route))
```

**Comment by yulongcs** [comment]
问题有解决吗？

**Comment by zhouxianwei** [comment]
![image](https://user-images.githubusercontent.com/1953871/103325543-2e22b900-4a87-11eb-9898-cbcab92540af.png)
ie11下框架报错

**Comment by quicklearning123** [comment]
请问各路神仙们都是如何解决的

**Comment by quicklearning123** [comment]
> nodeModulesTransform
这是默认参数吧？为啥配个默认参数会有用
![image](https://user-images.githubusercontent.com/70048681/103913185-4065bc80-5143-11eb-84a2-1a66306ba644.png)

**Comment by quicklearning123** [comment]
> @ikun @ycjcl868 IE11下仍然报错
> 
> ```
> function traverseModifyRoutes(routes, access) {
> 这行报错  const resultRoutes = [].concat(routes).map(resultRoute => {
>     const routes = resultRoute.routes;
> 
>     if (routes && (routes === null || routes === void 0 ? void 0 : routes.map)) {
>       return _objectSpread(_objectSpread({}, resultRoute), {}, {
>         // return new route to routes.
>         routes: routes === null || routes === void 0 ? void 0 : routes.map(route => _objectSpread({}, route))
> ```

按文档说法，nodeModulesTransform默认是all，应该全部都会转换。为什么要配成none，这样转换的范围更小了。

**Comment by afc163** [comment]
看上去是 plugin-access 的问题。https://github.com/umijs/plugins/blob/5ea07023c34aa4f4e5af21ec698ffc274ea50364/packages/plugin-access/src/utils/runtimeUtil.ts#L6

@sorrycc 看看。

---

@quicklearning123 可以帮忙确认一下是否问题只存在开发环境。https://github.com/umijs/umi/issues/2319#issuecomment-486905133

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/104147016-8f009a00-5381-11eb-8267-bce64f4bcac4.png)

确实 access 问题

**Comment by ycjcl868** [comment]
+ @umijs/preset-react@1.7.10

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/104148773-8dc97e80-540e-11eb-9a72-7b24dac54122.png)
已验证正常。

**Comment by quicklearning123** [comment]
给力~！

**Comment by asevenm** [comment]
默认的文档模式还是报错的，需要切换到edge文档模式

**Comment by fcode1** [comment]
umi 2.0版本没有nodeModulesTransform这个配置项，如何解决不支持ie11问题

**Comment by lovestarboy** [comment]
> umi 2.0版本没有nodeModulesTransform这个配置项，如何解决不支持ie11问题

请问解决了嘛，我也遇到这个问题了。

**Comment by daisybaicai** [comment]
{  
    ...
    targets: { ie: 11 },  
    esbuild: { target: 'es5' },
}

**Comment by lingjieding** [comment]
https://github.com/umijs/umi/issues/5042#issuecomment-1019325800
