### ISSUE TITLE
内置的 umi-test 脚本有文档吗? 想知道怎么更新快照 ..., 还有怎么查看单个文件的 coverage

### ISSUE THREAD

**Issue by GreatAuk** [umijs/umi#5663]
## Background

想知道怎么更新快照 ..., 还有怎么查看单个文件的 coverage
## Proposal

Describe the solution you'd like, better to provide some pseudo code.
umi-test 脚本能够传递参数
## Additional context

![image](https://user-images.githubusercontent.com/20253809/98888710-7126ce00-24d3-11eb-84be-0726832069bb.png)

**Comment by sorrycc** [comment]
参数透传给 jest 的。
