### ISSUE TITLE
[Bug] plugin-initial-state 首次获取数据阻塞整个应用加载，可能产生长时间白屏现象

### ISSUE THREAD

**Issue by dpyzo0o** [umijs/umi#5664]
## What happens?

使用 plugin-initial-state 插件后去初始数据的时候，如果函数里面获取数据耗时较长，应用在初始化的时候显示的是白屏，用户体验不是太好。是否可以在首次数据获取之前全屏显示一个loading呢？或者自定义显示的内容？

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by xiaosu12138** [comment]
这个是什么结论么，怎么处理
