### ISSUE TITLE
[Feature Request] 需要增加一个symlinks的 配置

### ISSUE THREAD

**Issue by lusess123** [umijs/umi#5666]
```
  webpackConfig.resolve
    // 不能设为 false，因为 tnpm 是通过 link 处理依赖，设为 false tnpm 下会有大量的冗余模块
    .set('symlinks', true)
```

我认为 阿里内部才会使用tnpm，而阿里外部用的是常规的npm,不会有tnpm 下会有大量的冗余模块，但是会经常需要用到软链，
每次需要自己去修改chainWebpack， 不如增加一个symlinks的配置,  当然默认可以为true

**Comment by sorrycc** [comment]
通过 chainWebpack 修改吧，这个点太细了。

**Comment by sorrycc** [comment]
或者可以提一个插件。

**Comment by maidangzhu** [comment]
能看一下你的 chainWebpack 配置吗，我也遇到了这个问题，umi3以使用 npm link，直接各种编译不通过
