### ISSUE TITLE
[Feature Request] require.context 加载多张图片

### ISSUE THREAD

**Issue by crazhou** [umijs/umi#5667]
## 加载多张图片

我项目中我想一次加载9 张小图标，现在是需要写 9 个 import xxx from '@/assets/images/icon_xxx.png'

webpack 中，用 `require.context` api  可以实现，但在 umi 3.x (我的是3.2.14) 没有这个 Feature

```javascript
const reqImg = require.context('@/assets/images/icons', false, /icon_\w+\.png$/)
const images = reqImg.keys.map(reqImg)
```

**Comment by hiyangguo** [comment]
✋  @sorrycc 我也是遇到了一样的问题。为什么这个 enhancement 被关了？
