### ISSUE TITLE
umi 的useRequest中data第一次请求为 undefined, 第二次请求的data为第一次的结果

### ISSUE THREAD

**Issue by xppcnn** [umijs/umi#5669]
const { data, loading, run } = useRequest(
values => ({
url: '/api/account/login',
method: 'post',
data: values,
}),
{
manual: true,
},
);

const onFinish = async (values: LoginParamsType) => {
await run(values);
console.log(data);
if (data && data.token) {
setToken(data.token);
message.success('登录成功');
window.location.href = '/index';
}
};

**Comment by brickspert** [comment]
https://github.com/umijs/umi/issues/5669

**Comment by brickspert** [comment]
const result = await run(values);

这样拿结果
