### ISSUE TITLE
[Bug] 在拆分的config/route.ts中配置重定向无效

### ISSUE THREAD

**Issue by ycd12345** [umijs/umi#5670]
// .umirc.ts 中配置有效。将routes拆分到config/route.ts中，redirect失效
import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },

  routes: [
    { 
      exact: true,
      path: '/', 
      component: '@/pages/index' 
    },
    { 
      exact: true,
      path: '/user',       
      title:'用户中心',
      redirect: '/user/center'
    },
    { 
      exact: true,
      path: '/user/center', 
      component: '@/pages/user/center',
      title:'用户中心2' 
    },
  ],
});

**Comment by ycd12345** [comment]
"umi": "^3.2.27"

**Comment by Jfreey** [comment]
@ycd12345 首先，可能你是被他们文档这段误导了 

> 如果项目的配置不复杂，推荐在 .umirc.ts 中写配置； 如果项目的配置比较复杂，可以将配置写在 config/config.ts 中，并把配置的一部分拆出去，比如路由配置可以拆成单独的 config/routes.ts。

这里的routes.ts经测试，不会自动注入或者合并到config当中。之所以你的设置无效，是因为route.ts根本就没有被引用和加载。这里，你需要主动import写有route的文件到config的routes设置选项字段当中。

所以，这是文档的歧义吧🙃

**Comment by ycd12345** [comment]
多谢回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/umi"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月1日(星期二) 晚上9:26
收件人:&nbsp;"umijs/umi"<umi@noreply.github.com&gt;;
抄送:&nbsp;"Sherlock Holmes"<1662927602@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [umijs/umi] [Bug] 在拆分的config/route.ts中配置重定向无效 (#5670)





 
@ycd12345 首先，可能你是被他们文档这段误导了
  
如果项目的配置不复杂，推荐在 .umirc.ts 中写配置； 如果项目的配置比较复杂，可以将配置写在 config/config.ts 中，并把配置的一部分拆出去，比如路由配置可以拆成单独的 config/routes.ts。
  
这里的routes.ts经测试，不会自动注入或者合并到config当中。之所以你的设置无效，是因为route.ts根本就没有被引用和加载。这里，你需要主动import写有route的文件到config的routes设置选项字段当中。
 
所以，这是文档的歧义吧🙃
