### ISSUE TITLE
[Feature Request] 增加单独启动一个页面功能，而不是每次都启动整个引用

### ISSUE THREAD

**Issue by maquannene** [umijs/umi#5671]
## Background

一般情况，工程架构不错的情况下，启动整个应用速度都很快，但是遗留的一些老应用代码量非常大，每次开发其实只需要开发某个路径下的代码，不需要启动编译整个工程，整个工程启动太慢了；

## Proposal

通过增加路径参数，只编译启动指定的路径

**Comment by sorrycc** [comment]
近期计划做，会做基于路由的按需编译。

**Comment by zdc1111** [comment]
@sorrycc 按需编译路由实现了吗 我很感兴趣 有具体代码可以让我参考一下吗
