### ISSUE TITLE
[Bug] umi2.9升级到3.0项目启动报错

### ISSUE THREAD

**Issue by promotion-xu** [umijs/umi#5673]
## What happens?

按照升级umi3.0文档，出现此错误。望解答

![image](https://user-images.githubusercontent.com/36992764/99150739-a4cf4700-26d1-11eb-8540-c89c5e3562fa.png)
![image](https://user-images.githubusercontent.com/36992764/99150754-b7e21700-26d1-11eb-89f9-4363017f7aff.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by ycjcl868** [comment]
去掉 umi-plugin-locale 这个依赖，用 `@umijs/preset-react` 代替
