### ISSUE TITLE
exportStatic: { htmlSuffix: true },缓存问题

### ISSUE THREAD

**Issue by rong12345** [umijs/umi#5675]
config中配置了exportStatic: { htmlSuffix: true }之后  每次变更到正式环境，需要用户清除缓存才能加载最新的文件，有什么方法能自动清除缓存吗
- **Umi 版本**：3.2.0
- **Node 版本**：13.10.0
- **操作系统**：windows

**Comment by ycjcl868** [comment]
这为啥有缓存啊

**Comment by rong12345** [comment]
> 这为啥有缓存啊

不太清楚  之前做其他项目 配置上都差不多  就这个exportStatic: { htmlSuffix: true }是这个项目才用到的 然后每次更新都有缓存 需要手动清除  刷新还不行
