### ISSUE TITLE
UmiJS与yarn workspace集成问题

### ISSUE THREAD

**Issue by IIIThSoul** [umijs/umi#5681]
我想在项目中通过yarn workspace来管理子项目，yarn版本是1.13.0，umi版本是3.2.27

目录结构如下：

    common       公共模块
    main             模块2
    node_modules
    package.json 
    system         模块1
    yarn.lock

根目录下的package.json文件内容如下：

    {
      "name": "project-aio",
      "version": "1.0.0",
      "license": "MIT",
      "private": true,
      "workspaces": [
        "common",
        "main",
        "system"
      ]
    }
目录main下package.json文件内容如下：

    {
      "name": "main",
      "version": "1.0.0",
      ....
    }

目录system下package.json文件内容如下：

    {
      "name": "system",
      "version": "1.0.0",
      ....
    }

我分别在两个目录下使用`yarn create @umijs/umi-app`创建应用，然后在根目录下使用`tyarn`安装依赖，但是运行一段时间后，就会报以下错误
![image](https://user-images.githubusercontent.com/10285557/99228004-ff2dec00-2826-11eb-9806-c0b3d4dc65c3.png)

并在项目根路径下的 node_modules下生成对应的目录链接，如下图

![image](https://user-images.githubusercontent.com/10285557/99228166-37352f00-2827-11eb-9979-aaa182f489ff.png)

![image](https://user-images.githubusercontent.com/10285557/99228205-41efc400-2827-11eb-97a4-8cc13d61ee9c.png)

这两个链接我确认了下是指向子项目目录，但是umi好像是通过node_modules下的链接来确认umi路径的，然后会生成路径失败，因为我在子项目目录main下的.bin目录查看生成的cmd脚本时这样的

![image](https://user-images.githubusercontent.com/10285557/99228438-94c97b80-2827-11eb-90aa-808d7040e2b3.png)

对应的路径是根目录下的`node_modules\node_modules\umi\bin\umi.js`，多了个`node_modules`

请问这个问题应该怎么处理，umi有相关配置项吗？

**Comment by veici** [comment]
同遇到这个问题，请问有解决方案吗

**Comment by veici** [comment]
@sorrycc 你好，这里是可重现bug的仓库，https://github.com/veici/report.git，我这边发现重现的关键点是packages下子项目名称存在@符号，跟题主情况不同。

**Comment by sorrycc** [comment]
@veici 把你的问题描述下，重新提个 issue ？

**Comment by tweet** [comment]
问题解决了吗

**Comment by wangchaoHeart** [comment]
> @sorrycc 你好，这里是可重现bug的仓库， https://github.com/veici/report 我这边发现重现的关键点是packages下子项目名称存在@符号，跟题主情况不同。

你解决了吗 我项目上也遇到了和你一样的问题， 子项目名称带@就报那个错误
