### ISSUE TITLE
[Bug] 如果我需要部分接口走mock，部分走线上如何做？

### ISSUE THREAD

**Issue by chua1989** [umijs/umi#5686]
如果我需要部分接口走mock，部分走线上如何做？
两类接口的域名和前缀都是一样的， 我需要如何配置？

比如有以下两个接口
http://www.xx.com/api/a   // 这个接口正常发送到www.xx.com服务器
http://www.xx.com/api/b  // 这个接口转发请求mock数据

**Comment by xiaohuoni** [comment]
上生产之后 mock 服务无效，如果是开发，可以通过配置 proxy ，识别 /api/a 到服务器

**Comment by gezichenshan** [comment]
确实不太智能, 配了proxy还得让后台配cors.

**Comment by xiaohuoni** [comment]
@gezichenshan 开发的时候配置 proxy ，上生产了同源部署。这和智能有什么关系？

**Comment by KellenHe** [comment]
@xiaohuoni 请问上了生产有什么方法继续使用mock吗

现在是用dumi开发了组件，组件的dome需要访问mock。
生产的数据需要登录或者其他的业务依赖，单独一个组件访问mock比较方便。

**Comment by xiaohuoni** [comment]
现在的方案需要自己再启一个 mock 服务

**Comment by sorrycc** [comment]
问题咨询请到 https://github.com/umijs/umi/discussions 。
