### ISSUE TITLE
umi3首次加载，会出现loading的字样，根据FAQ配置去掉无效

### ISSUE THREAD

**Issue by cnyhazz** [umijs/umi#5688]
根据FAQ里面的描述去修改
export default {
  dynamicImport: {
    loading: '() => <></>'
  },
}

仍然无效，页面报错
![image](https://user-images.githubusercontent.com/15262865/99366222-45508180-28f3-11eb-8ecc-05ec10463365.png)

**Comment by ycjcl868** [comment]
文档有误，这个需要写一个文件

loading: '@/components/loading.tsx'

然后你创建 `src/components/loading.tsx`

内容是 

```jsx

import * as React from 'react';
const Loading = () => <></>;
export default Loading;
```
