### ISSUE TITLE
umijs引进静态文件(非js, img)，引进之后webpack提示错误

### ISSUE THREAD

**Issue by greenking19** [umijs/umi#5693]
## What happens?
因为要结合threejs搭建3d场景。 需要引进mtl跟obj文件，文件放在src/assets目录下
![import](https://user-images.githubusercontent.com/43332372/99396728-0fc08e00-291d-11eb-84e5-67947fde8e59.png)
使用的时候报错了
这是使用的function
![loader](https://user-images.githubusercontent.com/43332372/99396887-40a0c300-291d-11eb-8c0d-dce2935072ea.png)
报错如下
![webpackError](https://user-images.githubusercontent.com/43332372/99396944-50200c00-291d-11eb-8740-b2f4cd0e3495.png)

请问要如何配置webpack呢？ 还是我的路径不对？
是不是要在webpack添加file-loader呢？ 请问在哪里修改webpack呢？ 
官网的配置chainWebpack告诉了怎么修改，
但是没又说在哪里修改 这让我无从下手😢
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
3.2.14
- **Node Version**:
v12.16.1
- **Platform**:
macos && windows

**Comment by whereiscode** [comment]
@greenking19 实现不了  umi没这个功能

**Comment by whereiscode** [comment]
你说的这个是webpack默认的
