### ISSUE TITLE
[Bug] umi3.0官网文档中html模版变量使用有错误, 望即是同步官网文档

### ISSUE THREAD

**Issue by MrXujiang** [umijs/umi#5694]
## What happens?

umi3.0官网文档中html模版变量使用有错误

## 复现步骤，错误日志以及相关配置
![image](https://user-images.githubusercontent.com/28833634/99480143-7633c380-2992-11eb-967b-4f954dd1c5af.png)
应该改成:
``` html
<link rel="icon" type="image/x-icon" href="<%= context.config.publicPath %>favicon.png" />
```

 文档路径: [修改默认模版](https://umijs.org/zh-CN/docs/html-template#%E4%BF%AE%E6%94%B9%E9%BB%98%E8%AE%A4%E6%A8%A1%E6%9D%BF)

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by sorrycc** [comment]
已修改。
