### ISSUE TITLE
如何指定页面SSR

### ISSUE THREAD

**Issue by a982564562** [umijs/umi#5697]
## What happens?
请问不需要登录的页面使用SSR渲染, 需要登录的页面使用CSR渲染, 应该如何配置?
` const { error, html } = await serverRender({
      path: request.url,
      mode: 'string',
      getInitialPropsCtx: {
        user: params.user || null,
      },
      forceInitial: true,
    });`

测试了forceInitial属性, 开启 forceInitial后，首屏得到的结果是
window.g_initialProps = null;
希望能保留服务端返回的数据
另外除了设置forceInitial属性,还有没有其它方法能实现?

## Context

- **Umi Version**: 3.2.24
- **Node Version**: 12.19.0
- **Platform**: win10

**Comment by HowTerrible** [comment]
这个问题在另一个issue里提到了 #7023
