### ISSUE TITLE
[Bug] umi2.0升级umi3+, register failed, invalid key dva from plugin

### ISSUE THREAD

**Issue by lwbweb** [umijs/umi#5702]
在2.0config中{dva:true},在3+中设置为：{dva:{skipModelValidate:true}},已有规则，怎么配置都报错、npm start正常、
控制台报错如下：

index.esm.js:219 Uncaught Error: register failed, invalid key dva from plugin ./****/****/src/app.ts.

src下app.ts内容为：
export const dva = {
  config: {
    onError(err: ErrorEvent) {
      err.preventDefault();
      console.error(err.message);
    },
  },
};

- **Umi Version**:3.2.27
- **Node Version**:12.18.2
- **Platform**:mac

**Comment by beginnerJq** [comment]
I have same problem

**Comment by xrkffgg** [comment]
组件名称不要使用 app 关键字

**Comment by lwbweb** [comment]
> 组件名称不要使用 app 关键字

检查了下、没有app关键字之类的组件命名

**Comment by xrkffgg** [comment]
文件的名字呢？

**Comment by sorrycc** [comment]
有问题再 reopen。

**Comment by lwbweb** [comment]
assay

> 有问题再 reopen。

非自己close，无reopen选项

**Comment by sorrycc** [comment]
dva 插件没有注册上吧，你提供可复现仓库。
