### ISSUE TITLE
plugin-dva 不支持校验有 tsx 语法的 model 文件的合法性[Bug] 

### ISSUE THREAD

**Issue by gintamamadao** [umijs/umi#5703]
## What happens?

plugin-dva 不支持校验有 tsx 语法的 model 文件的合法性

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：3.2.2
- **Node 版本**：12.x
- **操作系统**：mac

**Comment by sorrycc** [comment]
可以通过参数关闭校验。
