### ISSUE TITLE
plugin-locale bug on Firefox: unreachable code after return statement

### ISSUE THREAD

**Issue by setheredge1105** [umijs/umi#5704]
## What happens?

When using plugin locale on Firefox, I get a warning in the console: "unreachable code after return statement". 
This does not happen on Chrome.

The problem comes from src/.umi/plugin-locale/locale.tsx line 45

There are 2 returns with one unreachable. When removing the unreachable return (line 45) the warning disappears. 

## Mini Showcase Repository(REQUIRED)

https://github.com/setheredge1105/umijs-pluginlocale-bug-demo

## How To Reproduce

- launch react app, open in Firefox, look in the console: unreachable code after return statement 

## Context

- **Umi Version**: ^3.2.22
- **Node Version**: v12.18.4
- **Platform**: React

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/104831897-a76d2a80-5841-11eb-9aee-1486ecdb215c.png)

There's no `unreachable code after return statement` warning in the console.
