### ISSUE TITLE
[Bug] 即使不使用 ts，项目根目录下也没有 tsconfig.json，但还是会提示：[WARN] update `jsx: "react"` into `jsx: "react-jsx"` to suport the new JSX transform in React 17 in tsconfig.json

### ISSUE THREAD

**Issue by yingzhiji** [umijs/umi#5707]

**Comment by xiaohuoni** [comment]
项目不使用ts，.umi 文件夹下生成的还是 ts 文件。感觉是强制使用 ts @sorrycc @ycjcl868

**Comment by ycjcl868** [comment]
这是用了 React 17，`npm ls react` 下，看下是哪个包导致整个项目升到了 React 17

或者你 package.json 声明下 `"react": "^16.0.0"`

**Comment by yingzhiji** [comment]
我的意思是虽然使用了 react17，但是没有使用 ts，项目根目录下也没有 tsconfig.json，应该不会有下面这行提示：
![image](https://user-images.githubusercontent.com/21698836/102743863-562d6080-4393-11eb-8b39-887e66e43b48.png)
