### ISSUE TITLE
配置入口entry

### ISSUE THREAD

**Issue by zhengki** [umijs/umi#571]
配置入口entry，提示这项配置被禁用了，目前不支持修改入口吗？

**Comment by sorrycc** [comment]
为啥要修改入口？umi 的入口文件是自动生成的。

**Comment by amily4555** [comment]
我认为还是有比较好
比如引入第三方库（antd, echarts, lodash 等) 造成打包后 umi.js 文件过大，还是可以设置分开为好，
而这些第三方库 单独打包文件 甚至可以不需要hash值，直接浏览器缓存~~

**Comment by amily4555** [comment]
不过目前自己 webpack.config.js 自己配置吧

**Comment by sorrycc** [comment]
> 比如引入第三方库（antd, echarts, lodash 等) 造成打包后 umi.js 文件过大，还是可以设置分开为好，

配 externals ，然后在 document.ejs（自定义 html）里引入就好了吧。

**Comment by gouding** [comment]
> 为啥要修改入口？umi 的入口文件是自动生成的。

你好  正因为umi入口文件在.umi临时生成。但现在遇到的问题是项目比较大，每次上线不可能因为一个模块整个都不上线，所以想一个项目拆分成多个模块，比如能否生成多个模块对应的各自的js文件，然后在index.html里再依次引入js文件。如页面上有三个菜单（模块），各自生成a.js、b.js、c.js（公共模块都引用）。哪怕a.js出问题上不了，那也不影响b和c的正常上线。a可还用上个版本的a.js。所以想请问下umi能否这样配置，或者您有没有更好的解决方案。谢谢

**Comment by sorrycc** [comment]
@gouding 参考 https://github.com/umijs/umi-example-monorepo

**Comment by gouding** [comment]
> @gouding 参考 https://github.com/umijs/umi-example-monorepo

谢了  能拆分我这边就好办多了   试了下能满足现在的项目开发  多谢多谢

**Comment by gouding** [comment]
> @gouding 参考 https://github.com/umijs/umi-example-monorepo

@sorrycc 还得麻烦
![image](https://user-images.githubusercontent.com/13016673/48938776-2bbb1000-ef4d-11e8-84de-7bda0953a4f4.png)
这句话我的理解是在单独做子模块开发时，跟主框架其实是没有任何关系的是吗？
按照您给的这个示例，我这样写可以吗,开发不同的子模块，配置不同的命名？求解（如下）
![image](https://user-images.githubusercontent.com/13016673/48939071-10043980-ef4e-11e8-8711-3ff1d701e6e7.png)
若此时要做子模块的开发，需 yarn startHome 启动项目。还是说在home模块里去维护自己的package,安装他所对应的安装包，若要启动项目，然后再在home模块里，yarn start （如下）
![image](https://user-images.githubusercontent.com/13016673/48939207-70937680-ef4e-11e8-80f1-c273ece605b5.png)
现在是单独启动，或在外边配置 yarn startHome，子模块里引用不了antd，样式加载不了。若umd引入，启动主模块是可以的。求解
在子模块里，这样写，然后怎么能像主模块里的.umirc.js里写的antd加载（如下是子--主模块对比）求解
![image](https://user-images.githubusercontent.com/13016673/48939463-47bfb100-ef4f-11e8-93e3-a1c19bf36482.png)
![image](https://user-images.githubusercontent.com/13016673/48939446-3b3b5880-ef4f-11e8-8743-bacc56ce2d7f.png)

多谢指教！多谢

**Comment by gouding** [comment]
> > 比如引入第三方库（antd, echarts, lodash 等) 造成打包后 umi.js 文件过大，还是可以设置分开为好，
> 
> 配 externals ，然后在 document.ejs（自定义 html）里引入就好了吧。

@sorrycc 子模块里怎么引用antd这些第三方库，现在样式不生效，子模块需要单独装node_modules吗

**Comment by amily4555** [comment]
@gouding 

每个 package.json 对应一个 node_modules 

把 每个子模块看成一个项目吧··

**Comment by mokinzhao** [comment]
请问，比如我只想 打包umi 工程文件下某个js 文件对外输出为一个umd 模块的js，然后被别的项目引用，这样怎么配置？

**Comment by xlePE** [comment]
这个现在有办法做到吗？

**Comment by xlePE** [comment]
> 请问，比如我只想 打包umi 工程文件下某个js 文件对外输出为一个umd 模块的js，然后被别的项目引用，这样怎么配置？

这个现在有办法做到吗？

**Comment by BoyYangzai** [comment]
> > 请问，比如我只想 打包umi 工程文件下某个js 文件对外输出为一个umd 模块的js，然后被别的项目引用，这样怎么配置？
> 
> 这个现在有办法做到吗？

我的理解是 这是打包器的能力而不是umi提供的吧 qwq
