### ISSUE TITLE
[Bug] 项目启动失败

### ISSUE THREAD

**Issue by ssas01** [umijs/umi#5710]
## What happens?

使用 tyarn 创建 umi 项目，使用 tyarn 安装项目依赖。yarn start 启动项目失败，报错信息

`yarn run v1.16.0
$ umi dev
Starting the development server...

✔ Webpack
  Compiled successfully in 4.54s

Fatal error in , line 0
Check failed: U_SUCCESS(status).

✨  Done in 9.45s.`

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: ^3.2.28
- **Node Version**: v12.0.0
- **Platform**: mac

**Comment by xiaohuoni** [comment]
@ycjcl868 看起来是你们内部的包

**Comment by screetBloom** [comment]
Node 12.x 的一个问题，参考：https://github.com/nodejs/node/issues/27379

<br>

**推荐解决方式：** 
- nvm 切换 node 版本到 10.15.x 
- 如果一定要 12.x, 根据 [Node Release](https://github.com/nodejs/node/pull/27440) + 实践，建议还是选择 12.16 


@ssas01
