### ISSUE TITLE
"export 'connect' was not found in 'umi'

### ISSUE THREAD

**Issue by wenlittleoil** [umijs/umi#5712]
import { connect } from 'umi'

**Comment by wenlittleoil** [comment]
dva配置如下：
`
  dva: {
    skipModelValidate: true,
    immer: true,
    hmr: true,
  },
`

**Comment by zoffyzhang** [comment]
请问怎么解决的？我也遇到这个问题

**Comment by Verena99** [comment]
请问怎么解决的呢？

**Comment by MangoSeven** [comment]
dva配置如下：该配置无效
dva: { skipModelValidate: true, immer: true, hmr: true, },

**Comment by corgii-123** [comment]
将'umi'改成'dva‘没问题了
import { connect } from 'dva'

**Comment by swanf** [comment]
> 将'umi'改成'dva‘没问题了
> import { connect } from 'dva'

按照你说的解决了问题了，但是想知道为什么会这样，因为在另外一个 antd pro 项目中是从 'umi' 中引入的 connect

**Comment by peng** [comment]
这umi 文档也太坑爹了

**Comment by zoffyzhang** [comment]
可能是因为 plugin-dva 没有生效，因为该插件有这样的[启动条件](https://github.com/umijs/plugins/blob/ad1b3e46e3073ff9033e15a47dfdf43ffaf88bb5/packages/plugin-dva/src/index.ts#L101)  

试试这样解决：
先删除 `src/.umi`，然后创建文件 `src/models/index.ts`

```ts
// 仅用于启动 @umijs/plugin-dva
export default { namespace: '@umijs/plugin-dva', state: null };
```

**Comment by yaximi111** [comment]
我真是服了

**Comment by yummyo** [comment]
原因就是项目中没有找到models文件夹，plugin-dva没有启动成功，参考上方@zoffyzhang的引用。
