### ISSUE TITLE
[Bug] 通过cnpm下载v2版本，为啥依赖的corejs下载的是v3.7.0的版本了？最近很多老项目编译都有问题了

### ISSUE THREAD

**Issue by tanyo520** [umijs/umi#5715]
最近通过cnpm 下载umi v2的版本 ，但是里面的core-js会依赖下载3.7.0的版本，这个是在哪里配置了么，v2的版本应该用core-js v2的版本才行，不然编译会爆错，这个是cnpm源导致？

**Comment by tanyo520** [comment]
umi-build-dev 好像是这个包会下载core-js 3.7版本

**Comment by ycjcl868** [comment]
复现项目发一个

**Comment by tanyo520** [comment]
我看这个项目里面
![image](https://user-images.githubusercontent.com/5094034/99939275-ade0a800-2da4-11eb-9a3d-85689bdd78d7.png)


> 复现项目发一个

我看项目里面是引用的v2版本
![image](https://user-images.githubusercontent.com/5094034/99939309-be911e00-2da4-11eb-93b4-7a112374fcad.png)

我直接初始化项目，安装 发现node_modules/core-js的版本是3.7.0.0 ,昨天发生的事情，很多ci机器都跑不过了。因为v2的版本，用的是corejsv2版本，默认拉下来的3.7.0就导致
![image](https://user-images.githubusercontent.com/5094034/99939489-20ea1e80-2da5-11eb-8fb4-5ddb72bd9604.png)

demo如下
{
  "name": "nodejs-console-app1",
  "version": "0.0.0",
  "description": "NodejsConsoleApp1",
  "main": "app.js",
  "dependencies": {
	  "umi-build-dev": "1.18.6"
     
  },
  "author": {
    "name": ""
  }
}

**Comment by tanyo520** [comment]
> 复现项目发一个

刚又深入 找了下 发现是这个包导致 "af-webpack": "1.14.9"

**Comment by ycjcl868** [comment]
af-webpack 版本全是锁🔒的，可能是某个依赖的依赖升级导致，再看下

**Comment by ifibercc** [comment]
同样的问题, 主干都跑不过了
![image](https://user-images.githubusercontent.com/13199426/99944392-c5705e80-2dad-11eb-9b9e-dd737afb27aa.png)

**Comment by tanyo520** [comment]
> af-webpack 版本全是锁🔒的，可能是某个依赖的依赖升级导致，再看下
解决了 ，在主干项目的package.json加上
`"core-js": "2.6.9"
感谢

**Comment by tanyo520** [comment]
> af-webpack 版本全是锁🔒的，可能是某个依赖的依赖升级导致，再看下

实在不想在挖下去了，哈哈 里面又是一大堆

**Comment by tanyo520** [comment]
> 同样的问题, 主干都跑不过了
> ![image](https://user-images.githubusercontent.com/13199426/99944392-c5705e80-2dad-11eb-9b9e-dd737afb27aa.png)

先在主干加个 `"core-js": "2.6.9" 试试，估计很难找到到底是哪个包依赖出问题了

**Comment by ifibercc** [comment]
> > 同样的问题, 主干都跑不过了
> > ![image](https://user-images.githubusercontent.com/13199426/99944392-c5705e80-2dad-11eb-9b9e-dd737afb27aa.png)
> 
> 先在主干加个 `"core-js": "2.6.9" 试试，估计很难找到到底是哪个包依赖出问题了

对, 我也先这样解决了
```
  "devDependencies": {
    "core-js": "^2"
  },
```

**Comment by PeachScript** [comment]
umi@2.13.16 已修复

**Comment by tanyo520** [comment]
> umi@2.13.16 已修复

感谢 我撤销增加的， 试试ci
