### ISSUE TITLE
umi 版本和antd-pro文档对应的问题, 请尽快解决，很影响使用

### ISSUE THREAD

**Issue by hopperhuang** [umijs/umi#5716]
## What happens?
这两天都在配置umi+atnd-pro的框架，用的是@umijs/plugin-layout
文档上写着的是支持antd-pro上的所有配置项，但是，我尝试了一下，好像支持度有限。

第一，现在umijs/plugin-layout 注入的antd-pro是5.x的。我顺着链接去查看相关的可配置项，官方给出的文档地址是这个：
https://procomponents.ant.design/components/layout/#prolayout

然后我看到PageContainer 这个组件是可以倒出的，但是我引入后打算使用，根本就没有export这个组件。

报错信息
```
react_devtools_backend.js:2450 ./src/app.js 76:46-59
" '@ant-design/pro-layout' does not contain an export named 'PageContainer'.
```

这里的原因是什么呢，是pro的文档写错了，还是代码有问题呢？

第二，我又尝试了一下菜单的高级用法

我在routes里面又配置了相关的一些选项，包括的是, 我就是复制粘贴测试一下而已。
```
    // https://beta-pro.ant.design/docs/advanced-menu
    // 不展示顶栏
    headerRender: false,
    // 不展示页脚
    footerRender: false,
    // 不展示菜单
    menuRender: false,
    // 不展示菜单顶栏
    menuHeaderRender: false,
    // 权限配置，需要与 plugin-access 插件配合使用
    access: 'canRead',
    // 隐藏子节点
    hideChildrenInMenu: true,
    // 隐藏自己和子节点
    hideInMenu: true,
    // 子项往上提，仍旧展示,
    flatMenu: true,
```

然后我发发现这几个配置项也是不起作用的。
```
    headerRender: false,
    // 不展示页脚
    footerRender: false,
    // 不展示菜单
    menuRender: false,
    // 不展示菜单顶栏
    menuHeaderRender: false,
```

想要起作用的话，要根据https://beta-pro.ant.design/docs/advanced-menu-cn 这里的说明来写，这样子才行
```
      // layout: {
      //   hideMenu: true,
      //   hideNav: true,
      //   hideFooter:true,
      // },
```

第三，现在breadcrumbs能自动生成的吗？antd-pro说能自动生成，但是我配置了路由，也是不可以的。

到底是pro的问题还是umi的问题呢？还是umi 对应的pro插件版和现在文档的api说明对不上呢？赶紧解决这些问题？

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

https://github.com/hopperhuang/umi3_bug

## How To Reproduce

```
npm start
```
可以看到并没有breadcrumb

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: "^3.2.27",
- **Node Version**: v14.15.0
- **Platform**: osx

**Comment by hopperhuang** [comment]
@ant-design/pro-layout@5.0.19 现在插件用的pro还是5.0的。但是例子的，都是6.0的。那到底是多少呀？

**Comment by hopperhuang** [comment]
breadcrumbs显示不出来是这里的原因吗？
![屏幕快照 2020-11-23 下午6 15 02](https://user-images.githubusercontent.com/20254356/99950928-459bc180-2db8-11eb-9afd-8850f51e99fe.png)

**Comment by hopperhuang** [comment]
安装信息如下
```
/Users/jiawei/Desktop/develop/try_create_umi
└─┬ @umijs/preset-react@1.7.0
  └── @umijs/plugin-layout@0.12.5 

bogon:try_create_umi jiawei$ npm ls @ant-design/pro-layout
/Users/jiawei/Desktop/develop/try_create_umi
└── @ant-design/pro-layout@5.0.19 

```

**Comment by hopperhuang** [comment]
但是，我提供的仓库的例子，是我手动指定了antd-pro到最新版本的，依然是无法显示breadcrumbs，是什么原因呢，麻烦尽快排查，解决。麻烦了，谢谢。

**Comment by hopperhuang** [comment]
升级依赖到preset-react1.7.4后，问题可以解决。

**Comment by Witee** [comment]
我也是同样的问题, 用的是脚手架生成的项目 
`npx @umijs/create-umi-app`
遇到了你的第二个问题, 也就是 routes 中的配置  menuRender 不生效的那个问题.
原因是 `package.json` 中 `dependencies` 安装的 `@ant-design/pro-layout` 包是 `5.x` 版本的, 改成 `6.x` 就可以了.

感谢楼主提供思路.
