### ISSUE TITLE
[Bug] Antd Modal.confirm 默认按钮文字与配置不一致

### ISSUE THREAD

**Issue by onlyling** [umijs/umi#5720]
## What happens?

umi、@ant-design/pro-layout 使用最新版本，`layout:false` 配置的路由跳转到 非 `layout:false` 路由后，`Modal.confirm` 出现的对话框确定、取消按钮为英文文案。页面刷新后文案正常。

如果是 `layout: {hideMenu: true,hideFooter: true,hideNav: true,}` 路由跳转非 `layout:false` 皆正常。

其他 Modal 按钮文案正常。

## 最小可复现仓库
```
|--src

|--|-- layouts
|--|--|-- base-layout.tsx

|--|-- pages
|--|--|-- demo1.tsx
|--|--|-- demo2.tsx
```

```js
{
routes: [
    {
      path: '/',
      name: '父路由',
      component: '@/layouts/base-layout',
      menu: {
        flatMenu: true,
      },
      routes: [
        { path: '/', component: '@/pages/demo1', layout: false },
        {
          path: '/demo',
          component: '@/pages/demo2',
          name: 'demo'
        },
      ],
    },
  ],
}
```

```js
// base-layout
import React from 'react';
import { ConfigProvider } from 'antd';
import zhCN from 'antd/es/locale/zh_CN';

const Layout: React.FC = props => {
  return <ConfigProvider locale={zhCN}>{props.children}</ConfigProvider>;
};

export default Layout;
```

```js
// demo1
import React from 'react';
import { Modal } from 'antd';
import { history } from 'umi';

export default () => {
  React.useEffect(() => {
    Modal.confirm({
      content: 'MMMM---1',
    });
  }, []);

  return (
    <div>
      <p>
        <span
          onClick={() => {
            history.push('/demo');
          }}
        >
          go demo
        </span>
      </p>
    </div>
  );
};
```

```js
// demo2
import React from 'react';
import { Modal } from 'antd';

const Demo: React.FC = () => {
  React.useEffect(() => {
    Modal.confirm({
      content: 'MMMM---2',
    });
  }, []);

  return <div>demo</div>;
};

export default Demo;
```

## 复现步骤，错误日志以及相关配置

默认第一页：`http://localhost:8000` ，页面初始化后弹出一个对话框，按钮文案是中文。

点击 go demo

新页面：`http://localhost:8000/demo` ，页面初始化后弹出一个对话，按钮文案是英文。

## 相关环境信息

- **Umi 版本**：^3.2.28
- **@ant-design/pro-layout 版本**：^6.5.15
- **Node 版本**：v12.14.1
- **操作系统**：Mac OS 10.15.7 (19H15)

<img width="575" alt="WX20201123-183936@2x" src="https://user-images.githubusercontent.com/9999765/99952922-64e81e00-2dbb-11eb-847c-a7bf83ad5344.png">
<img width="573" alt="WX20201123-183949@2x" src="https://user-images.githubusercontent.com/9999765/99952930-69143b80-2dbb-11eb-8f9e-b6f3ffa0fd7d.png">

**Comment by fangqibin** [comment]
确认一下Modal引入的方式是不是不一致

**Comment by onlyling** [comment]
> 确认一下Modal引入的方式是不是不一致

应该不是，像是 layout 插件或 `pro-layout` 配置导致的。

当时有问题的版本一旦使用 `layout:false`，最外层的 `base-layout.tsx` 组件也不会渲染，Antd 的配置都卸载 `base-layout.tsx` 组件上面的。

**Comment by fangqibin** [comment]
> > 确认一下Modal引入的方式是不是不一致
> 
> 应该不是，像是 layout 插件或 `pro-layout` 配置导致的。
> 
> 当时有问题的版本一旦使用 `layout:false`，最外层的 `base-layout.tsx` 组件也不会渲染，Antd 的配置都卸载 `base-layout.tsx` 组件上面的。

可以确认pro-layout下语言问题。
