### ISSUE TITLE
chainWebpack 有没有更详细的配置文档或者案例

### ISSUE THREAD

**Issue by zlfgege** [umijs/umi#5723]
config.module.rule('mp4').test(/(.mp4$|.pdf$)/).use('url-loader').loader('url-loader');
 
    // {
    //   test: /\.(mp4|pdf)$/,
    //   use: [
    //     {
    //       loader: 'url-loader',
    //       options: {
    //         limit: 8192,
    //         name: 'static/images/[hash].[ext]',
    //       },
    //     },
    //   ],
    // },

如何在配置 引入.pdf 文件 路径 而不是转成64 找不到在哪设置options limit 的大小

**Comment by xiaohuoni** [comment]
详细文档看这里 https://github.com/neutrinojs/webpack-chain

**Comment by Cyberhan123** [comment]
你如果想要知道当前webpack配置了什么可以参考
https://github.com/Yatoo2018/webpack-chain/tree/zh-cmn-Hans#%E6%A3%80%E6%9F%A5%E7%94%9F%E6%88%90%E7%9A%84%E9%85%8D%E7%BD%AE,
其实更好的办法是参考vue的配置，它跟vue很相似
