### ISSUE TITLE
项目运行失败，出现chencheng的工作目录

### ISSUE THREAD

**Issue by laixstx** [umijs/umi#5726]
✖ Webpack
  Compiled with some errors in 721.88ms

 ERROR  Failed to compile with 1 errors下午3:44:27

 error  in ./src/pages/.umi-production/umi.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '/Users/chencheng/Code/github.com/ant-design/babel-plugin-import/node_modules/babel-preset-umi/node_modules/@babel/runtime/helpers/interopRequireDefault'

**Comment by baochengshi** [comment]
+1

**Comment by ycjcl868** [comment]
重新安装依赖
