### ISSUE TITLE
[Bug] 构建失败并报错

### ISSUE THREAD

**Issue by baochengshi** [umijs/umi#5729]
> UMI_ENV=prod umi build
ℹ Compiling Webpack
✔ Webpack: Compiled with some errors in 972.93ms
 ERROR  Failed to compile with 1 errors8:21:30 AM
 error  in ./src/.umi-production/umi.ts
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /root/app/src/.umi-production/umi.ts: Cannot find module '/Users/chencheng/Code/github.com/ant-design/babel-plugin-import/node_modules/babel-preset-umi/node_modules/@babel/runtime/helpers/interopRequireDefault'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/app/node_modules/babel-plugin-import/lib/index.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._compile (/root/app/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (/root/app/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at requireModule (/root/app/node_modules/@babel/core/lib/config/files/plugins.js:165:12)
    at loadPlugin (/root/app/node_modules/@babel/core/lib/config/files/plugins.js:68:17)

 @ multi ./src/.umi-production/umi.ts

**Comment by laixstx** [comment]
今天一升级，全部用到 umi 的项目都爆炸，/Users/chencheng 真是碉堡

**Comment by ycjcl868** [comment]
重新安装下依赖

**Comment by laixstx** [comment]
> 重新安装下依赖

重新装了好多遍了，还是报这个错。node_modules 整个文件夹移除了，重新装都不行。

babel-plugin-import 都在 package.json 锁死是 1.13.1 了，还是避免不了装了那该死的 babel-plugin-import 1.13.2

因为 node_modules/umi-plugin-react 的 package.json 里是 "babel-plugin-import": "1.x"，导致 node_modules/umi-plugin-react/node_modules/babel-plugin-import 安装的就是那个该死的  babel-plugin-import 1.13.2

这个该死的  babel-plugin-import 1.13.2

**Comment by laixstx** [comment]
@ycjcl868 
能不能不要老是回一句类似“重新安装下依赖”就 close 了，你自己试试是不是问题真的解决了，之后再 close 行吗？

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/100073708-b233b200-2df2-11eb-9326-d9accf0fa14d.png)


将检查是否有 `yarn.lock` 、`package-lock.json`，

**Comment by laixstx** [comment]
> ![image](https://user-images.githubusercontent.com/13595509/100073708-b233b200-2df2-11eb-9326-d9accf0fa14d.png)
> 
> 将检查是否有 `yarn.lock` 、`package-lock.json`，

我是将 node_modules yarn.lock 都删得干干净净了之后，才重装的，重装完之后，
node_modules/umi-plugin-react/node_modules/babel-plugin-import 还是 1.13.2 版本的...

**Comment by laixstx** [comment]
node_modules/umi-plugin-react 的 package.json 里是 "babel-plugin-import": "1.x" ，不是 “^1.0.0”

**Comment by ycjcl868** [comment]
> node_modules/umi-plugin-react 的 package.json 里是 "babel-plugin-import": "1.x" ，不是 “^1.0.0”

同样不会安装到 1.13.2

![image](https://user-images.githubusercontent.com/13595509/100074917-2a4ea780-2df4-11eb-95ec-5c3349423855.png)

**Comment by laixstx** [comment]
@ycjcl868  我本地是用了 淘宝源 的，是不是淘宝源的就不行呢？

**Comment by ycjcl868** [comment]
> @ycjcl868 我本地是用了 淘宝源 的，是不是淘宝源的就不行呢？

再试下呢

**Comment by dddreee** [comment]
很奇怪，我们2套测试环境，一套可以，另一套是docker的就不行，按理说不应该啊。。都是用的cnpm

**Comment by thomasyxy** [comment]
我公司的源也不行 @ycjcl868

**Comment by ycjcl868** [comment]
> 我公司的源也不行 @ycjcl868

执行下你们公司的源同步（淘宝是 `cnpm sync babel-plugin-import`）

**Comment by laixstx** [comment]
本地淘宝源可以了，谢谢大大

**Comment by sorrycc** [comment]
Fixed via 1.13.3 .

**Comment by baochengshi** [comment]
大佬出马一个顶俩，已完美解决

**Comment by Inori-Lover** [comment]
package里跟umi有关的依赖就这几个

```
    "umi": "^3.2.28",
    "umi-request": "^1.2.19",
    "@umijs/fabric": "2.3.1",
    "@umijs/preset-react": "^1.6.7",
```

然后start就会报错，整个项目重新clone并移除了相关lock文件后`npm i`的

```
./src/.umi/umi.ts
Module build failed (from ./node_modules/@umijs/deps/compiled/babel-loader/index.js):
Error: Cannot find module 'babel-plugin-import'
Require stack:
- C:\****\node_modules\@umijs\deps\compiled\babel\bundle.js
- C:\****\node_modules\@umijs\deps\compiled\babel\register.js
- C:\****\node_modules\@umijs\utils\lib\BabelRegister\BabelRegister.js
- C:\****\node_modules\@umijs\utils\lib\index.js
- C:\****\node_modules\@umijs\core\lib\Config\Config.js
- C:\****\node_modules\@umijs\core\lib\index.js
- C:\****\node_modules\umi\lib\ServiceWithBuiltIn.js
- C:\****\node_modules\umi\lib\forkedDev.js
```

有一样遭遇的？

**Comment by gaoman2015** [comment]
babel-plugin-import 1.13.0   锁死这个就可以了
