### ISSUE TITLE
[Bug] ssr + dompurify 报错

### ISSUE THREAD

**Issue by crazyair** [umijs/umi#5732]
## What happens?
.umirc.js
```
  ssr: {},
  exportStatic: {},
```
index.tsx

```
import React from 'react';
// import { sanitize } from 'dompurify'; 
import { sanitize } from 'isomorphic-dompurify';
import styles from './index.less';

export default () => {
  return (
    <div>
      <h1 className={styles.title}>{sanitize('demo')}</h1>
    </div>
  );
};

```
使用 dompurify 会报错，
```
ERROR [SSR] /index.html TypeError: (void 0) is not a function
```
而是用支持服务端渲染的  isomorphic-dompurify 会报错
```
 ERROR  Failed to compile with 1 errors                                                                                                                                               1:59:57 PM

This dependency was not found:

* canvas in ./node_modules/jsdom/lib/jsdom/utils.js

To install it, you can run: npm install --save canvas
```

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:latest
- **Node Version**:12
- **Platform**:mac

**Comment by kkomelin** [comment]
Other people experience this issue as well https://github.com/jsdom/jsdom/issues/3042

**Comment by crazyair** [comment]
install canval
```

 ERROR  Failed to compile with 1 errors                                                                                                                                              10:08:39 AM

 error  in ./node_modules/canvas/build/Release/canvas.node

Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```
demo:https://github.com/crazyair/umi-dompurify-demo

**Comment by crazyair** [comment]
无人问津

**Comment by kkomelin** [comment]
Hi @crazyair,

> 无人问津

Не согласен с вами. Мы работаем над этой проблемой https://github.com/kkomelin/isomorphic-dompurify/pull/36

**Comment by moshangqi** [comment]
> install canval
> 
> ```
> 
>  ERROR  Failed to compile with 1 errors                                                                                                                                              10:08:39 AM
> 
>  error  in ./node_modules/canvas/build/Release/canvas.node
> 
> Module parse failed: Unexpected character '�' (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> (Source code omitted for this binary file)
> ```
> 
> demo:https://github.com/crazyair/umi-dompurify-demo

请问下你这问题解决了吗
