### ISSUE TITLE
[求助] 使用yarn workspaces 管理多个项目,安装新依赖报错

### ISSUE THREAD

**Issue by JiangJingxuan** [umijs/umi#5735]
## What happens?

使用workspaces,项目可以正常运行,但是安装新的依赖的时候会报错如下图:
执行 yarn add ahooks 
![image](https://user-images.githubusercontent.com/25758620/100218258-7bbf7980-2f4f-11eb-8aee-b84a9003460c.png)

在根目录下使用 yarn workspace systemcore add ahooks 也是不行

初次使用workspaces,不知道是我创建的有问题漏掉了什么东西还是umi-app不支持使用workspaces

## Mini Showcase Repository(REQUIRED)

> https://github.com/JiangJingxuan/workspacedemo

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:3.2.28
- **Node Version**:14.15.1
- **Platform**:windows 10 1836.1198

**Comment by sorrycc** [comment]
需要用 extraBabelIncludes 包含。
