### ISSUE TITLE
[Bug] umi dev 之后warning "export 'getDvaApp' was not found in 'umi'

### ISSUE THREAD

**Issue by WMautumn** [umijs/umi#5737]
## What happens?

![image](https://user-images.githubusercontent.com/42930177/100233992-6a816780-2f65-11eb-9964-b409f8ead792.png)
umi dev 启服务后一直警告
多次重新yarn global add umi 
yarn 后
问题一直在

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:  3.2.28
- **Node Version**:12.13.1
- **Platform**:win10

**Comment by beginnerJq** [comment]
我也出现同样的问题
**Umi Version**: 3.2.28
**Node Version**: 14.15.1
**Platform**: macOS Big Sur

**Comment by yingpengsha** [comment]
同样的问题

- Umi Version: 3.3.3

**Comment by yingpengsha** [comment]
只需要在 models 里写几个 model，umi 便会在 .umi 里生成对应声明
