### ISSUE TITLE
lerna该如何支持HRM？

### ISSUE THREAD

**Issue by guoxmin** [umijs/umi#5739]
通过lerna管理多个子应用，公共组件放在packages目录，bootstrap到node_modules后，不支持HRM，怎么解决？

**Comment by ycjcl868** [comment]
有复现吗？

**Comment by guoxmin** [comment]
> 有复现吗？

这边是必现。[demo](https://github.com/guoxmin/lerna-prov5)

**Comment by sorrycc** [comment]
用这个环境变量配上，https://umijs.org/docs/env-variables#watch_ignored

**Comment by littleQing** [comment]
我也遇到了同样的问题，lerna + tsdx 用and.design 做为提供库的demo时，修改lerna管理的包并不会热更新and.design的项目
