### ISSUE TITLE
Unexpected token . (不好重现的bug)

### ISSUE THREAD

**Issue by amily4555** [umijs/umi#574]
![image](https://user-images.githubusercontent.com/2802841/40757642-128bd112-64bc-11e8-9185-5f465775d2fe.png)

另 “”.concat 看了umi 里面出现N次，但就一处出现问题

偶尔出现，经常出现在长时间待机后，重新刷新会加载
- umi 1.3.4  
- mac
- umi dev
出现问题后，重新启动项目，无效

目前的解决方案

1. 删除 node_module 重新安装 启动项目，恢复正常

2. 删除 pages/.umi 文件夹, 启动项目，恢复正常

**Comment by sorrycc** [comment]
出错信息贴全点，207 哪个模块是啥？不生效，估计是有缓存，出现之后试试 `BABEL_CACHE=none`、`HARD_SOURCE=none` 两个试试，看下哪个有效。

**Comment by amily4555** [comment]
两个都无效，可能我的项目比较特殊
我将umi 扩展成多项目集成环境（即 一个项目下 可以运行 n 个项目）
所以每一次启动，可能都是不同的项目，造成pages下的文件经常性变化
进而影响 .umi 里面的部分文档生成错误
--
解决方案也简单，在我的脚本文件里启动的时候加上 启动前移除 pages/.umi 
每次都自动生成就可

@sorrycc 可以close 此 issue 了

**Comment by amily4555** [comment]
基本可以确认该 bug 是有 使用 require 动态加载文件, 文件路径中 以 './' 开头的部分资源，有时候会不被识别 造成 Unexpected token .  错误

**Comment by sorrycc** [comment]
有时候? 给个可重现的例子？
