### ISSUE TITLE
[Bug] 本地开发和线上打包的 css 优先级不一致

### ISSUE THREAD

**Issue by dengfuping** [umijs/umi#5741]
## What happens?
- 本地开发: umi.css 优先级低于嵌入式样式 (其中内容是业务组件库的样式)
![image](https://user-images.githubusercontent.com/14918822/100323848-4e330880-3001-11eb-863e-681da6d410c7.png)

- 线上打包: umi.css 优先级高于嵌入式样式
![image](https://user-images.githubusercontent.com/14918822/100324121-b8e44400-3001-11eb-8cc4-44ac6b5278cd.png)

## Context

- **Umi Version**: v3.2.28
- **Node Version**: v14.8.0
- **Platform**: MacOS 10.15.5

**Comment by xiaohuoni** [comment]
配置了什么？
