### ISSUE TITLE
[Bug] tsconfig 配置 jsx: react-jsx 后，IDE中提醒 Cannot use JSX unless the '--jsx' flag is provided.

### ISSUE THREAD

**Issue by mizi-lin** [umijs/umi#5742]
如图:

![image](https://user-images.githubusercontent.com/2802841/100342468-fc967800-3018-11eb-9b4b-84a4d6c8609c.png)

**Comment by mizi-lin** [comment]
另，我们的项目是 monorepo， 子项目的tsconfig 继承主目录的 
在主项目的tsconfig 中配置 jsx: "react-jsx"
但在 umi 启动的时候，还会继续警告~

**Comment by mizi-lin** [comment]
另，为什么 使用 React 转换要采用 修改tsconfig 的配置？
https://zh-hans.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html
这里完成没有提到这点？

**Comment by ycjcl868** [comment]
https://umijs.org/docs/faq#%E4%BD%BF%E7%94%A8-react-17

**Comment by mizi-lin** [comment]
就是按文档后配置了，才出现上述问题·~

**Comment by ycjcl868** [comment]
> 另，为什么 使用 React 转换要采用 修改tsconfig 的配置？
> https://zh-hans.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html
> 这里完成没有提到这点？
> 为什么不是检测到项目包里使用react17 自动使用新的转换呢？

tsconfig.json 只是给编辑器展示用的，真正的编译走的 babel，babel 会自动转换的

**Comment by trlanfeng** [comment]
这个对Typescript版本有要求，使用4.1.2就可以了

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/100585566-a63c6a00-32a2-11eb-9842-76d4126582bf.png)
文档我改下

**Comment by axtlive** [comment]
解决没？

**Comment by garyxiang-ag** [comment]
如果你是用vs code 话， 需要将 vs code 的ts 版本换成 4.2 +
具体：
1. ctr + sft + p
2. 输入 type...
3. 选  .... select typescript version ...
4. 选 4.2 + 的。
参考： https://www.supercodebros.dev/typescript-react-jsx-flag/
