### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by boizz** [umijs/umi#5743]
https://umijs.org/zh-CN/docs/getting-started#%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE
这个废弃了吧？

**Comment by xiaohuoni** [comment]
看这里 https://umijs.org/zh-CN/plugins/plugin-layout

**Comment by boizz** [comment]
umi: 3.2.28
```
Invalid config key: layout
Error: Invalid config key: layout
```
