### ISSUE TITLE
chainWebpack chunks 提取

### ISSUE THREAD

**Issue by leozhang007** [umijs/umi#5744]
.umirc -> chainWebpack 添加 chunks 提取，事例代码如下
  chunks: ['vendors', 'umi'],
  chainWebpack: function(config, { webpack }) {
    if (prod) {
      config.plugin('compression-webpack-plugin').use(CompressionPlugin, [
        {
          test: /\.js$|\.html$|\.css$/, //匹配文件名
          threshold: 10240, //对超过10k的数据压缩
          deleteOriginalAssets: false, //不删除源文件
        },
      ]);
    }

    // 启动项目会卡住，进度在 90 % 左右，
    config.merge({
      optimization: {
        minimize: !prod,
        splitChunks: {
          chunks: 'all',
          minSize: 20000,
          minChunks: 1,
          automaticNameDelimiter: '.',
          cacheGroups: {
            vendor: {
              name: 'vendors',
              test({ resource }) {
                return /[\\/]node_modules[\\/]/.test(resource);
              },
              priority: -10,
            },
          },
        },
      }
    });
  },

demo 地址：https://github.com/leozhang007/umi-app

· yarn  
· npx umi dev

package.json 如下

{
  "private": true,
  "scripts": {
    "start": "umi dev",
    "build": "umi build",
    "postinstall": "umi generate tmp",
    "prettier": "prettier --write '**/*.{js,jsx,tsx,ts,less,md,json}'",
    "test": "umi-test",
    "test:coverage": "umi-test --coverage"
  },
  "gitHooks": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*.{js,jsx,less,md,json}": [
      "prettier --write"
    ],
    "*.ts?(x)": [
      "prettier --parser=typescript --write"
    ]
  },
  "dependencies": {
    "@ant-design/icons": "^4.0.2",
    "@ant-design/pro-layout": "^5.0.12",
    "@umijs/preset-react": "1.x",
    "@umijs/test": "^3.2.28",
    "antd": "^4.0.0",
    "compression-webpack-plugin": "^6.1.1",
    "lint-staged": "^10.0.7",
    "prettier": "^1.19.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "umi": "^3.2.28",
    "yorkie": "^2.0.0"
  },
  "devDependencies": {
    "@umijs/plugin-esbuild": "^1.0.1",
    "@umijs/preset-ui": "^2.2.9",
    "redux-logger": "^3.0.6"
  }
}

mac book pro
node 版本 v15.0.1

**Comment by xiaohuoni** [comment]
你提供的 demo 可以正常编译，我的 node 版本是v12.18.0，你切换 node 版本再试下
```
 File                                         Size           Gzipped

 dist/vendors.32fdccbd.async.js               3.3 MB         719.8 KB
 dist/umi.8412ebbc.js                         106.7 KB       20.2 KB
 dist/t__plugin-layout__Layout.cccdce26.      28.4 KB        6.1 KB
 async.js
 dist/p__user.b3982d4b.async.js               4.7 KB         1.4 KB
 dist/p__index.9119b0c4.async.js              2.3 KB         809.0 B
 dist/external_A.726d3a8f.async.js            2.1 KB         805.0 B
 dist/wrappers.c8424d1d.async.js              1.0 KB         514.0 B
 dist/vendors.t__plugin-layout__Layout.9      71.0 B         70.0 B
 02d5f39.async.js
 dist/vendors.umi.fc094120.async.js           71.0 B         70.0 B
 dist/vendors.t__plugin-layout__Layout.e      348.2 KB       35.3 KB
 7c096b8.chunk.css
 dist/vendors.umi.b06c526c.chunk.css          34.2 KB        4.9 KB
 dist/t__plugin-layout__Layout.68bfa84a.      1.4 KB         504.0 B
 chunk.css
 dist/p__index.309f6878.chunk.css             43.0 B         63.0 B
 dist/p__user.f48b6135.chunk.css              43.0 B         63.0 B

  Images and other types of assets omitted.


The bundle size is significantly larger than recommended.
Consider reducing it with code splitting: https://umijs.org/docs/load-on-demand
You can also analyze the project dependencies using ANALYZE=1

✨  Done in 23.68s.
```

![image](https://user-images.githubusercontent.com/11746742/100403245-5179d300-3099-11eb-8fd6-a44ec1a5316b.png)

**Comment by leozhang007** [comment]
@xiaohuoni 先跟你确认下，我 chainWebpack 中的配置是正确的么？下面是我本地测试的问题，如有问题请指正，感谢🙏

我切换到 12.18.0 也是卡住的，是不是有什么配置可以打开编译信息？这样好定位问题；而且还有个问题，umi build 之后，serve ./dist 启动服务，页面是空的，相关截图如下：
![umi dev 卡住](https://user-images.githubusercontent.com/17313851/100405305-4e351600-309e-11eb-810a-9bc4d4351707.png)

![umi build](https://user-images.githubusercontent.com/17313851/100405539-c4397d00-309e-11eb-8a56-fe1bcb76313d.png)

![浏览器](https://user-images.githubusercontent.com/17313851/100405566-d0bdd580-309e-11eb-9f98-88181e7fb99b.png)

**Comment by xiaohuoni** [comment]
这里的规则不对，你可以这么修改。不然没匹配到的模块，还会生成vendor.umi.js 但是 chunks 里面没有写命引入，所以页面就无法使用。
```
 cacheGroups: {
            vendor: {
              name: 'vendors',
              test: /[\\/]node_modules[\\/]/, // 这里
              priority: -10,
            },
          },
```

**Comment by xiaohuoni** [comment]
用 DEBUG=* umi build 来看看，是到什么环节卡住了

**Comment by xiaohuoni** [comment]
有另外一个事情，咨询你一下，同目录下的gz文件有用吗？我们都是通过容器来配置 gzip。

**Comment by leozhang007** [comment]
gzip 是在 issues 里有这么配置的，所以我试一下

**Comment by leozhang007** [comment]
DEBUG=* 威力太大了，给我 iterm 跑的内存溢出了。。。

**Comment by leozhang007** [comment]
minimize: false, // 这个设置造成的卡住，现在有个新的问题，配置如下：
chunks: ['vendors', 'umi'],
chainWebpack: function(config, { webpack }) {
  config.merge({
      optimization: {
        splitChunks: {
          chunks: 'all',
          minSize: 20000,
          minChunks: 1,
          automaticNameDelimiter: '.',
          cacheGroups: {
            vendors: {
              test: /[\\/]node_modules[\\/]/,
              priority: 10,
            },
          },
        },
      },
    });
  },

error: chunk of vendors not found.

截图如下：
![iterm](https://user-images.githubusercontent.com/17313851/100411990-48473100-30ae-11eb-89e9-4a07a6424fe1.png)

@xiaohuoni 感谢🙏

**Comment by xiaohuoni** [comment]
先注释掉 `chunks: ['vendors', 'umi'],` 看看 js 生成情况。这个问题多半是文件没生成。

**Comment by yaodong5063** [comment]
我也遇到这个问题了，但是都打包进去了，也是白屏
![image](https://user-images.githubusercontent.com/37628562/133231341-0ef33efd-2740-464e-b3a9-4eca2ce5a442.png)

**Comment by yaodong5063** [comment]
![企业微信截图_16316111152193](https://user-images.githubusercontent.com/37628562/133231425-2855047d-6cf4-4819-9280-73cdea8a3f09.png)
