### ISSUE TITLE
https://www.npmjs.com/package/@alitajs/@alitajs/tabs-layout 同样技术实现的，多tabs 。可以尝试能否解决，预览页面 https://pro.alitajs.com/

### ISSUE THREAD

**Issue by thelaurelyy** [umijs/umi#5748]
@finalreturn  https://www.npmjs.com/package/@alitajs/@alitajs/tabs-layout 同样技术实现的，多tabs 。可以尝试能否解决，预览页面 https://pro.alitajs.com/

_Originally posted by @xiaohuoni in https://github.com/umijs/umi/issues/3091#issuecomment-627688475_

______________________________________
请教：在带参数传递的路由中，如何完善这个组件？

**Comment by xiaohuoni** [comment]
这个插件只是一个尝试，存在很多问题，我一直没抽出时间来处理，不建议在项目中使用。需要多 tabs 方案，可以使用 [umi-plugin-keep-alive](https://github.com/alitajs/umi-plugin-keep-alive) 插件实现，这里有一个[demo](https://codesandbox.io/s/umi-keep-alive-tabs-demo-knfxy)
