### ISSUE TITLE
[Bug] umi3 部署时，反向代理后无数据

### ISSUE THREAD

**Issue by lininn** [umijs/umi#5754]
代码如下：
`var express = require('express'); 
const {createProxyMiddleware } = require('http-proxy-middleware');
var app = express(); 

let PROXY_HOST = 'http://localhost:8000'
//本地启动端口
let Local_PORT=9000;

// 设置端口
app.set('port', Local_PORT);

let options={
  target:PROXY_HOST,
  changeOrigin: true, // needed for virtual hosted sites
  ws: true,
}
 app.use('/api',createProxyMiddleware(options))

 app.use(async (req, res) => {
  
    const render = require('./dist/umi.server');
    res.setHeader('Content-Type', 'text/html');
    const context = {};
    const { html, error, rootContainer } = await render({
    
      path: req.url,
      context,
     
    });
   
    if (content instanceof Stream) {
      html.pipe(res);
      html.on('end', function() {
        res.end();
      });
    } else {
      res.send(res);
    }
  })

// 监听端口
app.listen(Local_PORT, () => {
  console.log(`server running @${Local_PORT}`);
});

`

错误：
UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Socket'
    |     property 'parser' -> object with constructor 'HTTPParser'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (/mnt/g/demo/react-blog-egg/umi/ssr-with-eggjs/node_modules/express/lib/response.js:1123:12)
    at ServerResponse.json (/mnt/g/demo/react-blog-egg/umi/ssr-with-eggjs/node_modules/express/lib/response.js:260:14)
    at ServerResponse.send (/mnt/g/demo/react-blog-egg/umi/ssr-with-eggjs/node_modules/express/lib/response.js:158:21)
    at /mnt/g/demo/react-blog-egg/umi/ssr-with-eggjs/vvv/index.js:45:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

配置

import { defineConfig } from 'umi';

export default defineConfig({
  dva: {},
  ssr: {
    forceInitial: true
  },
  nodeModulesTransform: {
    type: 'none',
  },
  proxy: {
    '/api': {
      'target': 'http://localhost:8000',
      'changeOrigin': true,
      'pathRewrite': { '^/api' : '/api/v1' },
    },
  },
  routes: [
    { path: '/', component: '@/pages/index' },
    { path: '/artinfo/:id', component: '@/pages/article/articleinfo' },
    { path: '/page/:id', component: '@/pages/index' }
  ],
});

**Comment by xiaohuoni** [comment]
https://umijs.org/config#proxy
![image](https://user-images.githubusercontent.com/11746742/100685601-a67a5980-33b7-11eb-99b9-fae342b406a9.png)

看文档

**Comment by lininn** [comment]
解决
`const express = require('express');
const app = express();
const {createProxyMiddleware } = require('http-proxy-middleware');
const fs=require('fs')
const port = 3000;

const domain = 'http://localhost';
app.use('/', express.static('./'));
let PROXY_HOST = 'http://localhost:8000'
let options={
  target:PROXY_HOST,
  changeOrigin: true, // needed for virtual hosted sites
  ws: true,
  pathRewrite:{
    '^/api':'/api/v1'
  }
}
app.use('/api',createProxyMiddleware(options))






// Express
const umijs = fs.readFileSync('./dist/umi.js');
const umicss = fs.readFileSync('./dist/umi.css');
app.use(async (req, res) => {
  // 或者从 CDN 上下载到 server 端
  // const serverPath = await downloadServerBundle('http://cdn.com/bar/umi.server.js');
  if (req && req.url === '/umi.css') {
    res.setHeader('Content-Type', 'text/css');
    res.send(umicss);
  } else if (req && req.url === '/umi.js') {
    res.setHeader('Content-Type', 'text/js');
    res.send(umijs);
}else{
  const render = require('./dist/umi.server');
  res.setHeader('Content-Type', 'text/html');

  const context = {};
  const { html, error, rootContainer } = await render({
    // 有需要可带上 query
    path: req.url,
    context

    // 可自定义 html 模板
    // htmlTemplate: defaultHtml,

    // 启用流式渲染
    // mode: 'stream',

    // html 片段静态标记（适用于静态站点生成）
    // staticMarkup: false,

    // 扩展 getInitialProps 在服务端渲染中的参数
    // getInitialPropsCtx: {},

    // manifest，正常情况下不需要
  });

  // support stream content
  // if (content instanceof Stream) {
  //   html.pipe(res);
  //   html.on('end', function() {
  //     res.end();
  //   });
  // } else {
  //   res.send(res);
  // }
  res.send(html);}
});

app.listen(port, err => {
  if (err) {
    throw err;
  }
  console.log(`> Ready on port ${port}, ${domain}:${port}`);
});
`
