### ISSUE TITLE
Mac 下 vscode 的 tsserver 会非常卡顿，cpu 很高

### ISSUE THREAD

**Issue by zhou0818** [umijs/umi#5762]
## What happens?

在 Mac 下使用 vscode 编写 antd pro v5，一段时间后就会非常卡顿，tsserver 占用 cpu 很高
![image](https://user-images.githubusercontent.com/25949890/100706333-cb84c180-33e3-11eb-942a-b36ed1f894ba.png)

跳转定义跳不了，鼠标指向也是一直加载中,10分钟也加载不出来，代码补全也没有了。。
![image](https://user-images.githubusercontent.com/25949890/100706387-e7886300-33e3-11eb-82e8-51f6749ceadb.png)

## 最小可复现仓库

> 使用 umi 新建antd pro v5

## 相关环境信息

- **Umi 版本**："umi": "^3.2.28",
- **Node 版本**：v13.10.1
- **操作系统**：mac 10.15.7

**Comment by zhou0818** [comment]
换了ts版本解决了。。

**Comment by sinpor** [comment]
> 换了ts版本解决了。。

你好，我也有相同的问题

相关版本如下：
- macOS 10.15.5
- node: v14.8.0
- "stylelint": "^13.0.0",
- "typescript": "^4.0.3"
- "umi": "^3.2.14"

我只注意到eslint服务占用高，禁用本地eslint扩展后正常。切换ts版本有用的话请问具体的版本是哪个？
谢谢：）

**Comment by sinpor** [comment]
@sorrycc 烦请抽空关注一下。是不是umi的eslint某些配置项比较耗性能，只要一编辑cpu占用立刻飙升。
感谢：）

![image](https://user-images.githubusercontent.com/35513921/103990628-8450d400-51cc-11eb-9bba-fa7e8cdaac05.png)

**Comment by zhou0818** [comment]
> @sorrycc 烦请抽空关注一下。是不是umi的eslint某些配置项比较耗性能，只要一编辑cpu占用立刻飙升。
> 感谢：）
> 
> 相关版本如下：
> 
> * macOS 10.15.5
> * node: v14.8.0
> * "eslint": "^7.1.0",
> * "typescript": "^4.0.3"
> * "umi": "^3.2.14"
> 
> ![image](https://user-images.githubusercontent.com/35513921/103990628-8450d400-51cc-11eb-9bba-fa7e8cdaac05.png)

![image](https://user-images.githubusercontent.com/25949890/104142878-59e35e80-53f8-11eb-826c-6fcb47a0badb.png)

![image](https://user-images.githubusercontent.com/25949890/104142892-6e275b80-53f8-11eb-8fa7-216a23277063.png)

我现在用的这个版本

**Comment by sinpor** [comment]
感谢回复：）

切换ts到如你所示版本依然没有解决，我再找找看。

**Comment by sorrycc** [comment]
要不要试试 webstorm，无此问题。

**Comment by zhou0818** [comment]
> 感谢回复：）
> 
> 切换ts到如你所示版本依然没有解决，我再找找看。

你是不是装了哪个包有影响，新建一个空项目试试，我当时是空项目都卡

**Comment by hb-bobo** [comment]
这个问题还是存在，卡到6s后才出提示，昨天刚生成的目录
