### ISSUE TITLE
umi dev 时 无法找到 layoutExports

### ISSUE THREAD

**Issue by clpz299** [umijs/umi#5765]
## What happens?
![image](https://user-images.githubusercontent.com/30864698/100821291-07269680-348b-11eb-9f2f-875bcfa7b645.png)
![image](https://user-images.githubusercontent.com/30864698/100821315-160d4900-348b-11eb-9fe8-742ae56669c3.png)
![image](https://user-images.githubusercontent.com/30864698/100821327-1dcced80-348b-11eb-9ba2-1f46fa687401.png)
![image](https://user-images.githubusercontent.com/30864698/100821359-245b6500-348b-11eb-968f-0f0f33241a92.png)

从 umi g tmp 看来生成了 .umi 文件夹，但是 umi dev 时 无法找到 layoutExports
## 相关环境信息

- **Umi 版本**：
3.2.14
- **Node 版本**：
v12.16.2
- **操作系统**：
windows / mac os

**Comment by Wmstone** [comment]
同问，今天重新安装了一下就遇到了这个问题，版本已经升级到了3.2.28也没用

**Comment by chenliangngng** [comment]
本地开发环境解决方案：把src/.umi/core/umiExports.ts的
`export * from '../plugin-layout/LayoutExports';`改成`export * from '../plugin-layout/Layout';`
本地打包可以一样的改node_modules里面的方法。
远端流水线暂时无解，等待官方修复

**Comment by Wmstone** [comment]
修改.umi里面中的编译后会立马失效，完全没办法开发，难受

**Comment by clpz299** [comment]
先启动再修改，就可以了，我这边可以了。 不过每次都要重新修改一次

**Comment by clpz299** [comment]
> 修改.umi里面中的编译后会立马失效，完全没办法开发，难受

先启动再修改

**Comment by Zoexyf** [comment]
webpack启动后 修改可以成功运行，但重新编译又会自动生成export * from '../plugin-layout/LayoutExports，导致运行失败

**Comment by Wmstone** [comment]
@sorrycc

**Comment by huohongchang1026** [comment]
我今天也遇到这个问题了 突然之间的  那我想上线咋办

**Comment by Zoexyf** [comment]
新启antd项目 运行仍旧出现该情况

**Comment by huohongchang1026** [comment]
@chenliangngng  大兄弟 fix之后的版本是多少啊 我看最新的3.2.28 还是不行 是不是没有发布呢

**Comment by my9988** [comment]
@chenshuai2144 请问下修复后的版本？我应该更新什么？技术太多，不清楚更新哪部分？按说ant-design-pro更新我才能更新吧？

**Comment by chenshuai2144** [comment]
执行

```
git clean -dfx
npm i
```

**Comment by lanvige** [comment]
> 执行
> 
> ```
> git clean -dfx
> npm i
> ```


报找不到 layout@0.13.1 错误

```
npm ERR! notarget No matching version found for @umijs/plugin-layout@0.13.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by huohongchang1026** [comment]
@chenshuai2144  请问我的window电脑执行git clean -dfx   npm i的操作 还是有问题 同事的mac本 dev 可以 这是为啥

**Comment by clpz299** [comment]
> @chenshuai2144 请问我的window电脑执行git clean -dfx npm i的操作 还是有问题 同事的mac本 dev 可以 这是为啥 我也手动删除试了

windows PowerShell 配置 环境变量添加git

**Comment by huohongchang1026** [comment]
@clpz299 我的配置了 我的意思是我git clean后  在安装 还是有那个问题 而且我从官网从新creat 一个v5的项目也有这个问题

**Comment by my9988** [comment]
我的可以，我同事的也不行，我的环境下就没有layoutExports.d...文件，奇怪

**Comment by my9988** [comment]
@chenshuai2144 preset-react 你改成了1.7.4，好像没有这个版本

**Comment by chenshuai2144** [comment]
https://www.npmjs.com/package/@umijs/preset-react

是有的，是不是有 lock

**Comment by huohongchang1026** [comment]
@my9988  你 git clean -dfx  npm i一遍  注意 npm 不要用自己公司的源  我的就是公司的有缓存造成的 坑死我了

**Comment by mtiger95** [comment]
估计什么时候能出稳定版，准备立个新的中台项目，遇到这个问题了，不敢用了。

**Comment by kex327hht** [comment]
同问这个问题，上面方法都试过了

**Comment by chenshuai2144** [comment]
@kex327hht` npm ls  @umijs/preset-react` 看看版本是不是新的，一般都是 lock 之类的
