### ISSUE TITLE
AssertionError [ERR_ASSERTION]: chunk of XXX not found.

### ISSUE THREAD

**Issue by lixx3000** [umijs/umi#5766]
## What happens?

我想做代码分割可是他却给我报错

## Mini Showcase Repository(REQUIRED)
![image](https://user-images.githubusercontent.com/45725941/100824924-f4639000-3491-11eb-8e11-00926ded998e.png)

chunks: ['antdesigns', 'umi'],
  chainWebpack (config: any, { env, webpack }: any) {
    config.merge({
      optimization: {
        splitChunks: {
          chunks: 'all',
          minSize: 50000,
          maxSize: 400000,
          minChunks: 2,
          automaticNameDelimiter: '.',
          maxAsyncRequests: 6, // 在做一次按需加载的时候最多有多少个异步请求，为 1 的时候就不会抽取公共 chunk 了
          maxInitialRequests: 5, // 针对一个 entry 做初始化模块分隔的时候的最大文件数，优先级高于 cacheGroup，所以为 1 的时候就不会抽取 initial common 了。    
          cacheGroups: {
            antdesigns: { // antdsign
              name: 'antdesigns',
              chunks: 'all',
              test: /(@antd|antd|@ant-design)/,
              priority: 10,
            },
            default: {
              minChunks: 2,
              priority: -20,
              reuseExistingChunk: true
            }
          }
        },
      }
    });
  },

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2. 我很期待代码分割可以用

## Context

- **Umi Version**: 3.2.27
- **Node Version**: 12.13.1
- **Platform**: window

**Comment by codedart2018** [comment]
同样遇到相同的问题

```
 DONE  Compiled successfully in 6667ms                                                                                                                                                                                      10:25:21 PM


  App running at:
  - Local:   http://localhost:8000 (copied to clipboard)
  - Network: http://192.168.3.23:8000
 WAIT  Compiling...                                                                                                                                                                                                         10:25:21 PM


✔ Webpack
  Compiled successfully in 408.91ms

 DONE  Compiled successfully in 409ms                                                                                                                                                                                       10:25:22 PM

(node:52866) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of vendors not found.
    at htmlChunks.forEach (/Users/rabbit/develop/react/jibei_front/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27)
    at Array.forEach (<anonymous>)
    at chunksToFiles (/Users/rabbit/develop/react/jibei_front/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
    at /Users/rabbit/develop/react/jibei_front/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:189:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/rabbit/develop/react/jibei_front/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
    at _next (/Users/rabbit/develop/react/jibei_front/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:52866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:52866) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:52866) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of vendors not found.
    at htmlChunks.forEach (/Users/rabbit/develop/react/jibei_front/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27)
    at Array.forEach (<anonymous>)
    at chunksToFiles (/Users/rabbit/develop/react/jibei_front/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
    at /Users/rabbit/develop/react/jibei_front/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:189:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/rabbit/develop/react/jibei_front/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
    at _next (/Users/rabbit/develop/react/jibei_front/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:52866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

```

**Comment by fyh-mengxiang** [comment]
我的使用 umi3.5.34 配置splitChunks多个分包报错如下：
Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
AssertionError [ERR_ASSERTION]: chunk of react not found.

配置代码：
 config.optimization.splitChunks({
        chunks: 'all',
        minSize: 30000,
        minChunks: 1,
        cacheGroups: {
          react: {
            name: 'react',
            chunks: 'all',
            test: /[\\/]node_modules[\\/](react|react-dom|react-redux|react-router|react-router-dom|react-helmet-async|react-helmet|react-color|react-intl|reactcss|dva)[\\/]/,
            priority: 12
          },
          antd: {
            name: 'antd',
            test: /[\\/]node_modules[\\/](antd|@ant-design)[\\/]/,
            priority: 12
          },
          charts: {
            name: 'charts',
            test: /[\\/]node_modules[\\/](echarts|bizcharts|@antv)[\\/]/,
            priority: 11
          },
          vendors: {
            chunks: 'all',
            name: 'vendors',
            test: /[\\/]node_modules[\\/]/,
            priority: 10
          }
        }
      });

   // umirc.ts文件引用
    chunks: ['react', 'antd',  'charts','vendors','umi'],
    chainWebpack: require('./config/webpackConfig')


版本信息
Umi Version: 3.5.34
Node Version: v12.22.0
Platform: mac

**Comment by lixx3000** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
