### ISSUE TITLE
如何导出生成的路由json数据？

### ISSUE THREAD

**Issue by scfido** [umijs/umi#577]
我想在服务端读取umi生成的路由数据，根据客户端路由来做服务端路由，实现服务端页面和客户端页面的灵活组合。

现在了解到开发模式会生成`pages/.umi/router.js`文件存放路由信息，但是`umi build`生成时会把路由信息混合到`dist/static/mui.xxxxxxx.js`文件中，此文件包含的内容较多而且压缩过不便于读取。有没有插件可以在build期间，把开发模式下生成的`pages/.umi/router.js`单独导出来呢？

**Comment by xiaohuoni** [comment]
dev和buld产生的路由文件应该是相同的吧？你是需要动态绑定还是手动绑定。如果需要手动绑定的话，我觉得保存下来dev时候的router应该就满足你的要求了

**Comment by scfido** [comment]
dev生成的文件在`pages/.umi/`目录下，build在`dist/static/umi`中，dev有单独的`route.js`文件，build时会混合到umi.[hash].js文件中。  
使用dev生成的route也不是不可以，想要插件导出的目的是确保route和build输出是绝对一致的。比如修改的代码直接`umi build`的情况，以及服务器自动构建的情况，都需要从build过程中导出route。

**Comment by xiaohuoni** [comment]
增加outputJson配置
当值存在时，会把当前的路由，生成public/UmiRoute.json
执行build之后会被原样拷贝到dist/xx目录下面

**Comment by xiaohuoni** [comment]
@sorrycc 看看这个行不行！

**Comment by scfido** [comment]
这个方案非常好👍
