### ISSUE TITLE
[Feature Request] dispatch时输入type字符串没有代码提示（There is no code prompt when entering the type string when dispatching）

### ISSUE THREAD

**Issue by MarxZhou** [umijs/umi#5771]
在调用dispatch时，输入type的字符串没有代码提示。
最近在用vuex，发现这个东西在调用dispatch时，输入action的字符串时，在webstorm中能够有代码提示。
之前在写antd pro的项目中，一直就靠复制粘贴。

请问社区的同志们，有谁知道如何能够让编辑器在调用dispatch函数，输入type字符串时出现代码提示啊？

When dispatch is called, there is no code prompt for the input type string.
I was using vuex recently and found that when this thing called dispatch, when the action string was entered, there could be code hints in webstorm.
I used to copy and paste in the antd pro project before.

Does anyone know how to make the editor display a code prompt when calling the dispatch function and entering the type string?

**Comment by sorrycc** [comment]
目前不支持。

**Comment by MarxZhou** [comment]
> 目前不支持。

请问目前有支持这个功能的计划吗？另外请给一点建议，该怎样实现这个功能呢，我想自己尝试开发一下

**Comment by JayShen1943** [comment]
> > 目前不支持。
> 
> 目前有支持这个功能的计划吗？请另外提出一些建议，该怎样实现这个功能呢，我想自己尝试开发一下
我自己写了个，可用
`ts
import { GlobalModelState, GlobalModelType } from './global'
import { MenuModelState, MenuModelType } from './menu'
declare namespace DVA {
    /** DVA模块名称声明 */
    type ModelName = {
        global: GlobalModelState;
        menu: MenuModelState;
    }

    /** DVA Action声明 */
    export type Action<T = any> = (action:
        {
            type: `${keyof ModelName}/${(keyof GlobalModelType['reducers'] & GlobalModelType['effects'])}`;
            payload?: T;
            [key: string]: any;
        } |
        {
            type: `${keyof ModelName}/${keyof (MenuModelType['reducers'] & MenuModelType['effects'])}`;
            payload?: T;
            [key: string]: any;
        }
    ) => any;
}
`
![image](https://user-images.githubusercontent.com/54438598/179446526-7fe6bc29-3891-4ab8-951e-50a521c292ac.png)
