### ISSUE TITLE
[Bug] Model中State有JSX类型属性值时编译不通过

### ISSUE THREAD

**Issue by realDonaldJTrump** [umijs/umi#5772]
在使用antd表格时，在Model中给state的某个属性赋值为JSX对象时编译不通过，提示出错的代码如下：
`state:{
columns[
{
render: (text, row)=><a exact href={row.url} target='_blank'><img src={text} width='50px' height='50px' /></a>,
}
]
}`
错误提示为：Unexpected token, expected ","
不知道是语法有问题还是BUG？求教～～

**Comment by Leskur** [comment]
</a> 后面多了个逗号。
