### ISSUE TITLE
[Bug] umi-test缺少class static property支持： Missing class properties transform.

### ISSUE THREAD

**Issue by AntiMoron** [umijs/umi#5774]
![image](https://user-images.githubusercontent.com/6587734/100874277-4a125980-34df-11eb-8e10-949e91db8e7c.png)

**Comment by AntiMoron** [comment]
我怀疑是这个文件里少了配置：
https://github.com/umijs/umi/blob/master/packages/test/helpers/transformers/javascript.js

**Comment by AntiMoron** [comment]
复现代码也就是这样：

```typescript
class MyComponent extends React.Component {
  public static SubComponent = SubComponent;
  public static show() {
     // global show
  }
}
```

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/102075181-ba13c000-3dba-11eb-8b7b-9514c825262b.png)

未复现
