### ISSUE TITLE
约定式路由的二级路由怎么设置路由出口，我无法在文档中阅读到[Bug] 

### ISSUE THREAD

**Issue by LvCoding112** [umijs/umi#5778]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by xiaohuoni** [comment]
能更详细的描述你的问题嘛？我无法从你的标题中阅读到问题。
