### ISSUE TITLE
[Bug] library in node_modules parse failed

### ISSUE THREAD

**Issue by Leemin0311** [umijs/umi#5779]
## What happens?
library in node_modules parse failed
![image](https://user-images.githubusercontent.com/34387426/100983047-be9ed400-3583-11eb-8adc-399a12cc8e91.png)

## Mini Showcase Repository(REQUIRED)

https://github.com/Leemin0311/nodeModuleTransform

## How To Reproduce

**Steps to reproduce the behavior:** 
1. cd library
2. npm link
3. cd ../projectA
4. yarn && yarn start

**Expected behavior** 
1. start successful

## Context

- **Umi Version**:  3.2.28
- **Node Version**: 14.7.0
- **Platform**: Macos 11.0.1

**Comment by ycjcl868** [comment]
改成 lerna 形式，直接 link 找不到路径的

**Comment by ycjcl868** [comment]
yarn && yarn start

=> `yarn && yarn link library && yarn start`
