### ISSUE TITLE
求助 umi build之后在浏览器中还是能被redux-dev-tool 读到modal里面的数据。

### ISSUE THREAD

**Issue by yuluoqingtian** [umijs/umi#5780]
## What happens?

如题，在生产上不想被redux开发者工具读到数据，互联网搜索和umi官网文档好像都没有找到解决办法。请问有什么比较好的建议？

## 相关环境信息

- **Umi 版本**：
2.10.7
- **Node 版本**：
- **操作系统**：

**Comment by sorrycc** [comment]
devtool 默认 umi build 之后是不会有的，https://github.com/dvajs/dva/blob/617e678289cf68c300785206929f666fa68cbb21/packages/dva-core/src/createStore.js#L30
