### ISSUE TITLE
Charles 如何映射 umi 生成的 JS和CSS 文件

### ISSUE THREAD

**Issue by pwstrick** [umijs/umi#5784]
线上有个网站出了点问题，我现在想用 Charles 将的 umi.js 和 umi.css 映射到本地的文件。
在本地使用 umi dev 命令调试，那么我如何操作才能成功映射到生成的 umi.js 和 umi.css。

在本地调试时，我发现有下面两个文件，但是目录里是找不到的，是不是在内存中的，我映射到其中的某一个，发现就会报错，是不是 build 的文件并不是下面的这两个文件。

http://localhost:8000/umi.js
http://localhost:8000/umi.dll.js

- **Umi 版本**：1.X

**Comment by ycjcl868** [comment]
访问下页面，看 Network 里的 umi.js 地址是什么，映射过去
