### ISSUE TITLE
create-umi脚手架创建的项目，umi为什么不是3.x的[Bug] 

### ISSUE THREAD

**Issue by imchaoyu** [umijs/umi#5785]
## What happens?

`create-umi`或`yarn create umi`创建的项目，umi版本默认是2.x，需要自己手动升级吗

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by ycjcl868** [comment]
用 `yarn create @umijs/umi-app`
