### ISSUE TITLE
[Bug] umi3.3.0使用：快速刷新（Fast Refresh）启动报错

### ISSUE THREAD

**Issue by zhouzyc** [umijs/umi#5786]
## What happens?

刚才更新3.3.0  启动项目出现以下错误。
```
TypeError: Cannot read property 'forEach' of undefined
injectIntoGlobalHook
./node_modules/react-refresh/cjs/react-refresh-runtime.development.js:461
  458 | // https://github.com/facebook/react/issues/17626
  459 | 
  460 | 
> 461 | hook.renderers.forEach(function (injected, id) {
      | ^  462 |   if (typeof injected.scheduleRefresh === 'function' && typeof injected.setRefreshHandler === 'function') {
  463 |     // This version supports React Refresh.
  464 |     helpersByRendererID.set(id, injected);

```
## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by ycjcl868** [comment]
可否提供一个复现 demo

**Comment by zhouzyc** [comment]
> 可否提供一个复现 demo

https://github.com/zhouzyc/umi-test.git

**Comment by ycjcl868** [comment]
正常启动

![image](https://user-images.githubusercontent.com/13595509/101327184-33dc0480-3823-11eb-8c7a-ea43f08e696d.png)


另，组件名要小写

```diff
- function home() {
+ function Home() {
```

**Comment by zhouzyc** [comment]
-umi3.3.0使用：快速刷新（Fast Refresh）启动报错 (#5786)
+umi3.3.0使用：快速刷新（Fast Refresh）启动后进入页面报错 (#5786)
是我问题描述错误。



你好、我使用win系统编译运行 打开页面没有问题。


我在mac环境下、进入页面后报错



你说的另：是说组件名称要大写？



趾蝣一粷`~怼卜戚~我~愛`YOU


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/umi"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月7日(星期一) 下午4:29
收件人:&nbsp;"umijs/umi"<umi@noreply.github.com&gt;;
抄送:&nbsp;"尐爺ぶ超々"<609435061@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [umijs/umi] [Bug] umi3.3.0使用：快速刷新（Fast Refresh）启动报错 (#5786)





 
正常启动
 

 
另，组件名要小写
 - function home() { + function Home() {

**Comment by YJKZHUZHU** [comment]
解决了吗

**Comment by zhouzyc** [comment]
已解决、React Developer Tools的问题 关闭后可以运行。
