### ISSUE TITLE
不同项目都是基于umi框架，开发依赖配置完全一致，开发完毕之后，业务代码如何实现打包后的动态整合？

### ISSUE THREAD

**Issue by wo-de-ping-er** [umijs/umi#5788]
两个基于相同版本umi并且依赖配置完全一致的不同项目a和b，a项目和b项目打包完成之后，如何实现将b项目打包之后的代码整合到a项目打包文件中直接可以使用？

**Comment by ycjcl868** [comment]
这是什么场景？ 可以用 shell 脚本处理
？
