### ISSUE TITLE
[Feature Request] 什么时候支持 webpack 5？

### ISSUE THREAD

**Issue by Artoria-0x04** [umijs/umi#5792]
## Background

Webpack 5 正式版已经出到 5.9.x 了，插件一直是 beta 还有一堆坑，比如手动升级版本以后编译代码会出 bug，也是没想到。

## Proposal

官方至少给一个升级 webpack 5 的 roadmap 和时间点吧。

**Comment by ycjcl868** [comment]
https://umijs.org/zh-CN/plugins/plugin-webpack-5

**Comment by Artoria-0x04** [comment]
@ycjcl868  next 是指 4.x 版吗？那 plugin 什么时候更新？

**Comment by atzcl** [comment]
期待 webpack 5 的更新
