### ISSUE TITLE
.umi 文件夹不应该使用绝对路径

### ISSUE THREAD

**Issue by uinio** [umijs/umi#5796]
## What happens?
.umi 文件夹不应该使用绝对路径

![image](https://user-images.githubusercontent.com/49021590/101447083-7c98d800-395f-11eb-86f7-f8f250259af0.png)

## 相关环境信息

- **Umi 版本**：3.3.1
- **Node 版本**：14.15.1
- **操作系统**：window 10

**Comment by ycjcl868** [comment]
？有问题？
