### ISSUE TITLE
配置文件中使用 theme问题

### ISSUE THREAD

**Issue by J-DuYa** [umijs/umi#5797]
```bash
theme: {
  'ant-prefix': 'web'
}
```
有部分命名没有被修改，官方有什么办法吗？

**Comment by ycjcl868** [comment]
试下 `@ant-prefix` 叱

**Comment by J-DuYa** [comment]
> @ant-prefix

不可以

**Comment by LullabyLY** [comment]
hi，After I set the style, it works locally, but it doesn’t work on the server. What caused it?
`theme: {
    '@primary-color': '#3954FF',
    'font-size-base': '12px',
  },`

**Comment by wzxm** [comment]
这个问题解决了吗？我出现 table/tree 组件的样式没有
