### ISSUE TITLE
[Bug] css module使用空对象会报错undefined导致白屏

### ISSUE THREAD

**Issue by Slartbartfast1** [umijs/umi#5801]
## What happens?

日常环境能正常使用，但是打包到线上会报错
![image](https://user-images.githubusercontent.com/38152942/101596414-fa2c1900-3a2f-11eb-94cf-db81c57526bb.png)

![image](https://user-images.githubusercontent.com/38152942/101595419-49714a00-3a2e-11eb-9381-757c360b327d.png)

## Mini Showcase Repository(REQUIRED)

https://github.com/Slartbartfast1/umi-test

## How To Reproduce
1..umirc.ts配置
```
import { defineConfig } from 'umi';
import { publicPath } from './deploy2def';
export default defineConfig({
  publicPath,
  hash: true,
  disableDynamicImport: false,
  history: {
    type: 'hash',
  },
  nodeModulesTransform: {
    type: 'none',
  },
  terserOptions: {
    compress: {
      drop_console: true,
      drop_debugger: true,
    },
  },
  extraBabelPlugins: [
    '@babel/plugin-proposal-optional-chaining',
    '@babel/plugin-proposal-nullish-coalescing-operator',
  ],
});
```
2.在style.less中写如一个空对象
```
.container {
}

```
3.在react组件中用cssmodule的方式引入
```
import styles from './style.less';
...
 render() {
    return (
      <Container
        className={styles['container']}
      >
...
```
怀疑是打包的配置把空对象给删除了？但是本地开发和打包的表现不一样就很迷，把umi版本锁死到3.2.28就不会出现这个问题
## Context

- **Umi Version**: 3.3.1
- **Node Version**:12
- **Platform**: chrome 86

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/101731036-e1dbee80-3a6f-11eb-8e33-72e7f83d6d0b.png)

未复现

**Comment by Slartbartfast1** [comment]
> ![image](https://user-images.githubusercontent.com/13595509/101731036-e1dbee80-3a6f-11eb-8e33-72e7f83d6d0b.png)
> 
> 未复现

我重新试了下
本地没有报错应该是有3.2.28版本的缓存，删除node_modules更新到3.3.1版本后本地运行也会报错了，是因为这个插件版本更新导致的css打包规则变化吗
https://github.com/umijs/umi/commit/8ea4f65edae9d45addcc1220a026835a606afcab

**Comment by Slartbartfast1** [comment]
> ![image](https://user-images.githubusercontent.com/13595509/101731036-e1dbee80-3a6f-11eb-8e33-72e7f83d6d0b.png)
> 
> 未复现
仓库：https://github.com/Slartbartfast1/umi-test
之前我本地不报错打包到线上会报错是因为我本地有3.2.28版本的umi包，删除node_modules之后重新安装3.3.1的umi本地就能正常报错了，https://github.com/umijs/umi/commit/8ea4f65edae9d45addcc1220a026835a606afcab 是因为这个插件的更新导致的吗？

**Comment by asevenm** [comment]
> ![image](https://user-images.githubusercontent.com/13595509/101731036-e1dbee80-3a6f-11eb-8e33-72e7f83d6d0b.png)
> 
> 未复现

把title这个类删了应该就复现了

**Comment by ycjcl868** [comment]
复现了
