### ISSUE TITLE
[Bug] 同时开启 layout 与 locale 配置后，layout报错

### ISSUE THREAD

**Issue by krypton100** [umijs/umi#5802]
## What happens?
新建UMI项目，.umirc.ts中同时开启layout与locale，Layout.tsx文件报错无法启动项目，注释 useIntl 后，项目可以正常启动。

![image](https://user-images.githubusercontent.com/55964976/101605647-682b0d00-3a3d-11eb-8344-51ba51c924e5.png)

![image](https://user-images.githubusercontent.com/55964976/101605581-4fbaf280-3a3d-11eb-824d-fb9410f139e3.png)

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：3.3.1
- **Node 版本**：12.18.3
- **操作系统**：mac

**Comment by ycjcl868** [comment]
https://github.com/umijs/plugins/pull/464/files#diff-4ee610f4da3c0e57c2bab942697e98418b1fd1ac155f24511cecf4602a233b7aL210-L215
