### ISSUE TITLE
[Bug] a new umi project，pro-layout default sideWidth is 208，but umi project is 256？why？

### ISSUE THREAD

**Issue by Willworkgogogo** [umijs/umi#5803]
## What happens?

i generated a new umi project, and i intall the latest @ant-design/pro-layout6.5.19, the pro-layout sideWidth default value is 208, but my umi project is 256. i need to update config/config.ts layout object , set sideWidth to 208. i just want to know why?

## Mini Showcase Repository(REQUIRED)

just a new umi project and use pro-layout

## How To Reproduce

just a new umi project and use pro-layout
![image](https://user-images.githubusercontent.com/20815934/101610427-30bf5f00-3a43-11eb-84a0-078cabe439b2.png)

## Context

- **Umi Version**: 3.3.1
- **Node Version**: 14.8.0
- **Platform**: mac pro

**Comment by chenshuai2144** [comment]
umi uses a lower version of the layout

https://pro.ant.design/blog/layout-new-style-cn

**Comment by Willworkgogogo** [comment]
@chenshuai2144 显示现在pro-layout，没法覆盖吗？如果说umi强制使用了lower version, 那为什么header部分的高度又是48呢？
![image](https://user-images.githubusercontent.com/20815934/101733044-25c70600-3af9-11eb-9833-5361645836b4.png)
