### ISSUE TITLE
useModel 是否支持 promise，虽然简单，但是需要 getTaskList.then((result)=>{window.console.log(result)}) 类似的promise操作

### ISSUE THREAD

**Issue by Zach-Lu** [umijs/umi#5804]
![image](https://user-images.githubusercontent.com/62736001/101710600-c521d400-3acc-11eb-8d5f-95fb4e6b168e.png)
我们用了useModel ，觉得很好用，目前只差一个promise的补充措施。

**Comment by Artoria-0x04** [comment]
自己在 model 里用 useEffect 处理 promise，model 只返回结果就可以了

**Comment by ttys026** [comment]
Promise 的处理是需要 hook 内部自己实现的，可以返回一个 async function，也可以用 useEffect 监听变化。
这个不适合 useModel 提供通用的处理。

**Comment by ttys026** [comment]
```javascript
const getTaskList = async () => {
  const res = await fetch(xxx);
  // setState
  setTaskList(res.data);
  return res.data;
}
```

要实现标题里的效果，可以这样写

**Comment by Zach-Lu** [comment]
> ```js
> const getTaskList = async () => {
>   const res = await fetch(xxx);
>   // setState
>   setTaskList(res.data);
>   return res.data;
> }
> ```
> 
> 要实现标题里的效果，可以这样写

谢谢！是的，目前就是这么解决的。唯一的不好就是，有时候model有时候直接service，有种管理不规范的感觉。

**Comment by ttys026** [comment]
> 谢谢！是的，目前就是这么解决的。唯一的不好就是，有时候model有时候直接service，有种管理不规范的感觉。

model 不需要直接写 service 的，这里只是举个例子，service 可以在专门的文件里维护，await 一个import 进来的方法，返回的是一个 promise 就可以。

或者直接用 [useRequest](https://ahooks.js.org/zh-CN/hooks/async) 去管理,

```javascript
const { run: getTaskList } = useRequest(service, { manual: true })
```
