### ISSUE TITLE
ssr 渲染失败 没有渲染成功 

### ISSUE THREAD

**Issue by hqylss111** [umijs/umi#5806]
https://github.com/umijs/umi/tree/master/examples/ssr-with-eggjs  使用的是官网的demo 启动以后 body 也是只有 root一个标签 没有其他的dom 不知道是为什么

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/102058955-2388d400-3da5-11eb-9e28-f95c4cef9fd0.png)

访问 localhost:7001，这个是服务端地址
