### ISSUE TITLE
项目启动报错。。。。

### ISSUE THREAD

**Issue by xu-Aurora** [umijs/umi#5807]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

![image](https://user-images.githubusercontent.com/35291465/101849144-0a5c0980-3b92-11eb-9a8b-eed1bad782a2.png)
umi3.1.3版本，跟着antd官网里面的在webpack里面配置dayjs替换moment，然后启动项目就报这个错了。。。。。

**Comment by xu-Aurora** [comment]
umi项目中，怎么才能把moment替换成dayjs

**Comment by xu-Aurora** [comment]
![image](https://user-images.githubusercontent.com/35291465/101850929-a6d3db00-3b95-11eb-8079-723311769acd.png)
按照antd官网方式做的，哪里有问题吗？

**Comment by ycjcl868** [comment]
我试下

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/101856248-c2999b80-3b19-11eb-8a1d-c9e10aa880ad.png)


```js
chainWebpack: memo => {
    memo.plugin('dayjs').use(require('antd-dayjs-webpack-plugin'));

    return memo;
  },
```

可以考虑给 `@umijs/plugin-antd` 加一个 `antd: { dayjs: {} }`

**Comment by xu-Aurora** [comment]
![Uploading image.png…]()

**Comment by xu-Aurora** [comment]
![image](https://user-images.githubusercontent.com/35291465/101877662-51b1bc80-3bc9-11eb-885f-b7844c69185b.png)

**Comment by xu-Aurora** [comment]
1.去掉 dayjs: {} 就能正常启动项目了
2.给DatePicker设置默认值后，再onchang的时候就会报错了
![image](https://user-images.githubusercontent.com/35291465/101877927-b836da80-3bc9-11eb-8d8b-928f3ac905f3.png)

**Comment by xu-Aurora** [comment]
1.去掉 dayjs: {} 就能正常启动项目了
2.给DatePicker设置默认值后，再onchang的时候就会报错了
![image](https://user-images.githubusercontent.com/35291465/101877975-c4bb3300-3bc9-11eb-83a3-8b00b932fe7f.png)

**Comment by xu-Aurora** [comment]
![image](https://user-images.githubusercontent.com/35291465/101878078-f03e1d80-3bc9-11eb-97f0-753eefff793e.png)

**Comment by xu-Aurora** [comment]
![image](https://user-images.githubusercontent.com/35291465/101878359-604ca380-3bca-11eb-9a64-1afc718ba3a8.png)
即使按你的方法替换成dayjs了，但这里看到的组件的数据类型还是moment呢，所以估计是这个原因报错

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/101903529-4464e580-3b69-11eb-81d2-c990066e5fa7.png)

😂

**Comment by xu-Aurora** [comment]
> ![image](https://user-images.githubusercontent.com/13595509/101903529-4464e580-3b69-11eb-81d2-c990066e5fa7.png)
> 
> 😂

我知道啊，加了报错，项目启动不了。不加项目能启动，但DatePicker你在onchange的时候就报错，我上面有截图啊

**Comment by ycjcl868** [comment]
不使用 umi 也会报错吗？

**Comment by xu-Aurora** [comment]
> 不使用 umi 也会报错吗？

我的就是umi项目啊，怎么叫不使用umi呢😂

**Comment by sorrycc** [comment]
rm -rf src/.umi 后试试，不行的话给个最简复现。

**Comment by xu-Aurora** [comment]
> rm -rf src/.umi 后试试，不行的话给个最简复现。

删除下.umi文件也是不行的，我给不了复现的情况，你可以新建一个umi的项目试下就知道了，确实不行

**Comment by sorrycc** [comment]
你换个目录试试可能就可以了，这是 babel 缓存导致的问题。新建个 umi 项目肯定是好的，不然 issue 早就炸了。

**Comment by xu-Aurora** [comment]
> 你换个目录试试可能就可以了，这是 babel 缓存导致的问题。新建个 umi 项目肯定是好的，不然 issue 早就炸了。

是指把项目的根目录换个名字试试嘛？
