### ISSUE TITLE
建议：chunk of kits not found，当chunk不存在的时候，报个警告 不要抛错

### ISSUE THREAD

**Issue by mizi-lin** [umijs/umi#5811]
场景：项目是monorepo 

每个package 大同小异

但如果每个package都配一遍chunk 相当麻烦，而且有可能根据不同条件，某个package 配置的chunk就是没有

能不能当检测chunk的时候，不存在，页面上就不加载了，在开发模式下 抛个警告就好··~~

**Comment by ycjcl868** [comment]
配 chunk？直接配 `APP_ROOT` 比较好吧

**Comment by atzcl** [comment]
@ycjcl868  新项目应用了旧项目的配置时，因为有做 splitChunks 而配置的 chunks，会因为新项目暂时没满足某一个 split chunk 的条件，而没有生成已配置到 chunks 的项时，就会报错；

感觉在遇到 chunks 没有的文件时，做跳过的容错处理会更合适些

**Comment by mizi-lin** [comment]
> 配 chunk？直接配 `APP_ROOT` 比较好吧
> 
> https://umijs.org/zh-CN/docs/env-variables#app_root

@ycjcl868 完全理解错误了，不是配置root地址，而是 在webpack chain 中配置 splitChunks ，在config中必须配置相应的 chunks 

@atzcl  理解完全正确

**Comment by mizi-lin** [comment]
@ycjcl868  麻烦reopen
