### ISSUE TITLE
[Bug] setLocale 使用第二个参数为false时不起作用

### ISSUE THREAD

**Issue by toutouli** [umijs/umi#5813]
## What happens?

通过设置第二个参数为 false ，来实现无刷新动态切换。
setLocale(locale,false)
然而实际情况是方法执行后没有切换过来，需要手动刷新页面才能实现切换。
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:3.3.1
- **Node Version**:14.4.0
- **Platform**:Mac OS

**Comment by ycjcl868** [comment]
有报错吗？

**Comment by ycjcl868** [comment]
未复现

```js
import React from 'react';
import { setLocale, getLocale, useIntl } from 'umi';
import { DatePicker, Button } from 'antd';
import styles from './index.less';

export default () => {
  const handleSwitch = () => {
    setLocale(getLocale() === 'zh-CN' ? 'en-US' : 'zh-CN');
  };
  const { formatMessage } = useIntl();

  return (
    <div className={styles.container}>
      locale: {getLocale()}
      {formatMessage({
        id: 'hello',
      })}
      <DatePicker />
      <Button onClick={handleSwitch}>Switch</Button>
      <h1 className={styles.title}>Page index</h1>
    </div>
  );
};

```

![bug](https://user-images.githubusercontent.com/13595509/102073128-b5014180-3db7-11eb-9644-93646c0f18db.gif)
