### ISSUE TITLE
[Bug] Cannot build ant design pro

### ISSUE THREAD

**Issue by smddzcy** [umijs/umi#5814]
All of our apps stopped building in production today with this error:

```
> node ./patchPackages && umi g tmp

Register plugin /app/node_modules/umi-plugin-antd-icon-config/lib/index.js failed, since Cannot use import statement outside a module
Error: Register plugin /app/node_modules/umi-plugin-antd-icon-config/lib/index.js failed, since Cannot use import statement outside a module
    at Object.apply (/app/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:159:15)
    at /app/node_modules/@umijs/core/lib/Service/Service.js:348:22
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/app/node_modules/@umijs/core/lib/Service/Service.js:108:103)
    at _next (/app/node_modules/@umijs/core/lib/Service/Service.js:110:194)
    at /app/node_modules/@umijs/core/lib/Service/Service.js:110:364
    at new Promise (<anonymous>)
    at /app/node_modules/@umijs/core/lib/Service/Service.js:110:97
    at Service.applyAPI (/app/node_modules/@umijs/core/lib/Service/Service.js:355:7)
    at /app/node_modules/@umijs/core/lib/Service/Service.js:438:20
```

Any idea why this happens?

**Comment by smddzcy** [comment]
OK we tracked down the issue and it's actually related to a package that `@ant-design/colors` is using, `@ctrl/tinycolor`. See: https://github.com/scttcper/tinycolor/issues/208

We just forced antd to use tinycolor 3.2.1 and it fixed the issue:

```
"resolutions": {
    "@ctrl/tinycolor": "3.2.1"
  },
```

**Comment by Matthew10r** [comment]
> OK we tracked down the issue and it's actually related to a package that `@ant-design/colors` is using, `@ctrl/tinycolor`. See: [scttcper/tinycolor#208](https://github.com/scttcper/tinycolor/issues/208)
> 
> We just forced antd to use tinycolor 3.2.1 and it fixed the issue:
> 
> ```
> "resolutions": {
>     "@ctrl/tinycolor": "3.2.1"
>   },
> ```

We're experiencing the same issue as well. Thank you for you suggestion!
