### ISSUE TITLE
[Bug] yarn create umi ant design pro 报错 Register umi-plugin-antd-icon-config Failed

### ISSUE THREAD

**Issue by yoole5699** [umijs/umi#5815]
## What happens?

使用 yarn create umi 创建项目，按照提示依次选择
ant-design-pro
Pro V4  
TypeScript
simple       
antd@4

接着进入目录，执行yarn，然后就报错了，报错提示是
Register plugin D:\temp\t-umi-upload\node_modules\umi-plugin-antd-icon-config\lib\index.js failed, since Cannot use import statement outside a module
项目无法正常启动就挂在这了，相关操作过程及截图在复现步骤或仓库中可看到图片...

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/yoole5699/umi-error-demo

## 复现步骤，错误日志以及相关配置

![step](https://user-images.githubusercontent.com/13230016/102020398-f09a0c80-3db3-11eb-8cc6-03be18fca9a4.PNG)
![error](https://user-images.githubusercontent.com/13230016/102020406-f7288400-3db3-11eb-94c5-50d82d93d221.PNG)
如果无法看到图的话，可以看下我上传的复现仓库中的图片

## 相关环境信息

- **Umi 版本**：3.3.1
- **Node 版本**：14.15.0
- **操作系统**：win10

**Comment by lucas-seismic** [comment]
请问为什么关闭了呢？ 我也有同样的问题

**Comment by chenshuai2144** [comment]
重复注册了插件 删除重复的就行了

**Comment by lhzbxx** [comment]
> 重复注册了插件 删除重复的就行了

奇怪，我今天也是项目的 CI 突然报错：

```
Register plugin /node_modules/umi-plugin-antd-icon-config/lib/index.js failed, since Cannot use import statement outside a module
```

之前同样的配置跑了蛮久的了。

**Comment by vericle** [comment]
Hi ther problem seem sto be in this line of code in node_modules\@umijs\preset-ant-design-pro\lib
![image](https://user-images.githubusercontent.com/9371418/107415023-1ffa9a80-6b13-11eb-91b7-98af70ddafb9.png)
i have commented the plugins.push(require.resolve('umi-plugin-antd-icon-config')); and it works for me. @yoole5699 yoole5699

**Comment by lenville** [comment]
sorry @sorrycc , same error occurs to me

**Comment by ncioj10** [comment]
@sorrycc Same here, that seems to be coming from some update today on the libraries.

**Comment by xXAvoraXx** [comment]
same problem

**Comment by j511002** [comment]
same problem +1

**Comment by sonmibz** [comment]
try adding this code in package.json

```
"resolutions": {
    "@ant-design/colors": "5.0.0"
  }
```

**Comment by zooyer** [comment]
> 重复注册了插件 删除重复的就行了

具体怎么操作呢？yarn create umi之后运行yarn就报这个错。
