### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by baobao12356** [umijs/umi#5819]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：
![image](https://user-images.githubusercontent.com/22005273/102047981-35a45a00-3e19-11eb-8afc-a9ebe4ef3e5f.png)

**Comment by ycjcl868** [comment]
`src/pages` 目录有吗？
