### ISSUE TITLE
[Bug] 新建项目安装依赖包报错

### ISSUE THREAD

**Issue by MissLiu34** [umijs/umi#5823]
按照官方文档，通过yarn create @umijs/umi-app新建一个项目之后，安装依赖。
输入yarn后报错，如下：
`error An unexpected error occurred: "/Users/didi/Documents/workspace/myapp/package.json: Unexpected token } in JSON at position 788".
info If you think this is a bug, please open a bug report with the information provided in "/Users/didi/Documents/workspace/myapp/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

查看package.json，删除devDependencies中最后一个逗号，此时安装成功。
` "devDependencies": {
    "lint-staged": "^10.0.7",
    "prettier": "^1.19.1",
  }`

**Comment by mtmzorro** [comment]
给其他同学新建项目也碰到了，早点发布个 release 把，错误不大，就是不太应该 😂 。
