### ISSUE TITLE
[Bug]  热更新时间长

### ISSUE THREAD

**Issue by jiechud** [umijs/umi#5827]
现在项目比较大，文件比较多，我改完之后，等五六秒才会出现编译进度条

![image](https://user-images.githubusercontent.com/9709396/102182355-1411a400-3ee7-11eb-83b5-a2372fb858b4.png)

**Comment by phoema** [comment]
大哥们，处理处理吧，我10多秒。

**Comment by ycjcl868** [comment]
> 现在项目比较大，文件比较多，我改完之后，等五六秒才会出现编译进度条
> 
> ![image](https://user-images.githubusercontent.com/9709396/102182355-1411a400-3ee7-11eb-83b5-a2372fb858b4.png)

最近才出现的？还是之前也是这样

**Comment by jiechud** [comment]
升级到umi3之后吧。监测文件改变，生成需要热更新变更的这块内容。umi是自己实现的还是用的webpack-dev-server？。我们项目目前是约定式路由，嵌套的文件比较多

**Comment by ycjcl868** [comment]
自己实现的 dev-server

**Comment by jiechud** [comment]
设计到公司项目，没法提供复现环境，能否指点一下这块代码在哪个lerna包下，我们自己debug下看看

**Comment by jiechud** [comment]
![image](https://user-images.githubusercontent.com/9709396/102317167-0d039800-3fb2-11eb-93bb-b31b064ef43c.png)
@ycjcl868 @sorrycc 
改完代码后，等待热更新，通知 umi-dev-server 时间需要好几秒

**Comment by gwsbhqt** [comment]
@sorrycc 关于启动慢，热更新慢，热更新丢失状态的问题，有把webpack换成vite的想法吗？

**Comment by sorrycc** [comment]
> @sorrycc 关于启动慢，热更新慢，热更新丢失状态的问题，有把webpack换成vite的想法吗？

有想过，但优先级低。

> 现在项目比较大，文件比较多，我改完之后，等五六秒才会出现编译进度条

目前能做的都在这里了，https://umijs.org/zh-CN/guide/boost-compile-speed

**Comment by LemonTree-shine** [comment]
> > @sorrycc 关于启动慢，热更新慢，热更新丢失状态的问题，有把webpack换成vite的想法吗？
> 
> 有想过，但优先级低。
> 
> > 现在项目比较大，文件比较多，我改完之后，等五六秒才会出现编译进度条
> 
> 目前能做的都在这里了，https://umijs.org/zh-CN/guide/boost-compile-speed

热更新太卡了，有没有什么方案可以解决，或者开发的时候我想跳过热更新，我需要怎么做

**Comment by 104gogo** [comment]
> > > @sorrycc 关于启动慢，热更新慢，热更新丢失状态的问题，有把webpack换成vite的想法吗？
> > 
> > 
> > 有想过，但优先级低。
> > > 现在项目比较大，文件比较多，我改完之后，等五六秒才会出现编译进度条
> > 
> > 
> > 目前能做的都在这里了，https://umijs.org/zh-CN/guide/boost-compile-speed
> 
> 热更新太卡了，有没有什么方案可以解决，或者开发的时候我想跳过热更新，我需要怎么做

开发的时候，可以把用不到的路由给注释了，临时体验下飞一般的速度

**Comment by renwangT** [comment]
> @sorrycc 关于启动慢，热更新慢，热更新丢失状态的问题，有把webpack换成vite的想法吗？
我已经受够 umi 这乌龟般的速度了，无可救药
