### ISSUE TITLE
Prompt 功能不全

### ISSUE THREAD

**Issue by winddamage** [umijs/umi#5829]
umi3 官方文档--API 中对Prompt的定义为“提供一个用户离开页面时的提示选择”，但是在使用的过程中发现，当关闭浏览器和关闭浏览器的Tab页签的时候，并没有生效。是否应该把这个功能加进去？！

**Comment by sorrycc** [comment]
通过路由跳转时才有效，关闭窗口和浏览器不在此功能覆盖范围。
