### ISSUE TITLE
umi-plugin-keep-alive 支持 umi3.x了

### ISSUE THREAD

**Issue by RobelChina** [umijs/umi#5832]
umi-plugin-keep-alive 支持 umi3.x了
https://github.com/alitajs/umi-plugin-keep-alive

用了这个方案以后，以前的国际化就失效了，默认是英文，这个怎么处理一下呢？

**Comment by RobelChina** [comment]
DatePicker.jsx
`
import { Dayjs } from 'dayjs';
import dayjsGenerateConfig from 'rc-picker/lib/generate/dayjs';
import generatePicker from 'antd/es/date-picker/generatePicker';
import 'antd/es/date-picker/style/index';

const DatePicker = generatePicker<Dayjs>(dayjsGenerateConfig);

export default DatePicker;
`

这是全局国际化配置
`
import React from 'react';
import { ConfigProvider, Empty } from 'antd';
import zhCN from 'antd/es/locale/zh_CN';
import dayjs from 'dayjs';
import zh_cn from 'dayjs/locale/zh-cn';

dayjs.locale(zh_cn);

<ConfigProvider locale={zhCN} renderEmpty={() => <Empty description={'抱歉，暂无数据！'}/>}>
······
</ConfigProvider>
`

引用以后，国际化配置就失效了，渲染成英文的样式了
<img width="306" alt="WX20201216-171452@2x" src="https://user-images.githubusercontent.com/13807125/102328849-90c58080-3fc2-11eb-8970-e41596746f48.png">

**Comment by sorrycc** [comment]
应该给 umi-plugin-keep-alive 提 issue?

**Comment by RobelChina** [comment]
我研究了下 @umijs/plugin-locale 插件，加上了配置就好使了，具体配置如下：
locale: {
    default: 'zh-CN',
    antd: true,
    title: false,
    baseNavigator: true,
    baseSeparator: '-',
  }
