### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Lyrics1** [umijs/umi#5833]
## 复现步骤，错误日志以及相关配置
# 高危安全风险

请在保持兼容性的前提下，将组件 acorn (版本：6.0.5) 升级到最新版本，一次性修复存在的 1 个高危安全风险
Regular Expression Denial of Service (ReDoS)
acorn is a tiny, fast JavaScript parser written in JavaScript. Affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS) via a regex in the form of /[x-\ud800]/u, which causes the parser to enter an infinite loop. This string is not a valid UTF16 and is therefore not sanitized before reaching the parser. An application which processes untrusted input and passes it directly to acorn, will allow attackers to leverage the vulnerability leading to a Denial of Service.

依赖源升级之后还是6.0.5版本，依赖关系 ： umi-library@1.6.0 -》 docz-core@1.1.0-》acorn@6.0.5

## 相关环境信息

- **Umi 版本**：
-   "umi-library": "^1.6.0",
    "umi-request": "^1.3.5",
    "universal-cookie": "^4.0.4"
- **Node 版本**：v12.16.3
- **操作系统**：mac os 10.14.5

**Comment by sorrycc** [comment]
docz 方案已不推荐使用，可以用 package.json 中的 resolution 指定版本来规避此安全提示。
