### ISSUE TITLE
如何彻底卸载service worker 

### ISSUE THREAD

**Issue by jimStyle88** [umijs/umi#5835]
## What happens?
使用UMI 2.3.0  创建项目时，框架默认开启了pwa, 由于缓存问题严重，现在先关闭PWA ，不使用 service worker  能力
于global.js 中执行 以下代码无效，控制台仍然可以看到部分静态文件来源于service worker 
if ('serviceWorker' in navigator) {
  // unregister service worker
  const { serviceWorker } = navigator;
  if (serviceWorker.getRegistrations) {
    serviceWorker.getRegistrations().then(sws => {
      sws.forEach(sw => {
        sw.unregister();
      });
    });
  }
  serviceWorker.getRegistration().then(sw => {
    if (sw) sw.unregister();
  });

  // remove all caches
  if (window.caches && window.caches.keys) {
    caches.keys().then(keys => {
      keys.forEach(key => {
        caches.delete(key);
      });
    });
  }
}
使用service worker  ，会导致本地静态文件与服务器文件不一致，导致 404  的情况，导致白屏。

希望可以提供方案，彻底卸载service worker  
- **Umi 版本**：2.3.0
- **Node 版本**：8.11.4
- **操作系统**：win 10

**Comment by sorrycc** [comment]
Google 下，https://www.google.com/search?q=disable+service+worker+completely&oq=disable+service+worker+completely&aqs=chrome..69i57.10679j0j7&sourceid=chrome&ie=UTF-8
