### ISSUE TITLE
[Feature Request] 项目整体是基于umi框架，使用father-build打包组件，一直在报这个错误，请问是什么地方配置的有问题吗？

### ISSUE THREAD

**Issue by wo-de-ping-er** [umijs/umi#5836]
![image](https://user-images.githubusercontent.com/23158766/102337674-befc8d80-3fcd-11eb-9ef0-668e10c5231e.png)

**Comment by wo-de-ping-er** [comment]
并且存在打包组件中如果存在高阶组件，就会出现打包高阶组件内部组件未export的问题

**Comment by PeachScript** [comment]
请提供复现，另外 Umi 项目为什么会用 father-build 打包

**Comment by wo-de-ping-er** [comment]
> 请提供复现，另外 Umi 项目为什么会用 father-build 打包

umi项目里面一个模块想直接打包成umd包  直接在其他umi项目html直接引入使用  这个是初衷的想法

**Comment by sorrycc** [comment]
issue 提到 https://github.com/umijs/father/issues，然后给复现步骤。
