### ISSUE TITLE
[Bug] it will show Property 'getInitialProps' does not exist on type 'FC<IProps>', in tsx page

### ISSUE THREAD

**Issue by amyhuangxbd** [umijs/umi#5837]
this code is: 
`import React, { FC } from "react";

interface IProps {};

const Index:FC<IProps> = (props) => {
    return <div></div>
};

Index.getInitialProps = async ({ store, isServer, history, match, route }) => {
    if (!isServer) {
      return;
    }
    const fetchData = () => {
      return new Promise((resolve,reject) => {
        setTimeout(async () => {
          const list = await fetch();
          resolve(list);
        },2000)
      })
    }
    const result = await fetchData();
    await store.dispatch({ type: 'test/setList', payload:{list: result} });
    const { test } = store.getState();
    return { list: test?.list || [] };
  };

export default Index;`

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by sorrycc** [comment]
看不懂，给复现步骤再 reopen 。

**Comment by Zach-Lu** [comment]
`const IndexPage: React.FC<IndexPageProps> & {
  getInitialProps: IGetInitialProps;
} = (props) => {}`

我应该帮你解决了，今后应该很多人来感谢这个回答。

**Comment by GentleSen** [comment]
在 umi 中有没有类似 next 中的 NextPage 类型？
