### ISSUE TITLE
[Bug] 使用refresh刷新initialState后,access数据已更新但路由状态没有随之更新

### ISSUE THREAD

**Issue by tingrabbit** [umijs/umi#5839]
## What happens?

我正在写一个具有权限控制的管理后台,在登陆成功后,需要获取权限信息配置权限路由. 我研究了脚手架,它也展示了相似的权限控制功能. 而我仿照其功能进行改写时,出现了access文件返回数据已经更新但是路由权限依然没有变化的情况.

我发现其原因是脚手架在登陆页成功登陆后使用以下代码进行跳转
/src/pages/usr/login
`
    replaceGoto();
        setTimeout(() => {
          refresh();
     }, 0);
`
replaceGoto方法使用了window.location.href进行页面跳转,页面进行了刷新从而获得了最新的权限状态. refresh方法即使注释掉也不会有任何的影响.但是在使用hash路由的菜单中,更换hash后面的路由并不会刷新页面,我的项目使用了window.location.href = ‘'/'跳转到首页的方式可以强制刷新获取最新的权限菜单, 它是目前的替代方案.但我仍然希望能够使用refesh更新access的数据能够生效.

## 期望效果
使用这种代码更新的access数据可以被更新到菜单上
`
    await refresh();
    replaceGoto();
    // setTimeout(() => {replaceGoto()}, 100} 这种也不生效
`
在调试中发现access文件返回的数据已经更新,但是菜单并没有变化 (使用哈希路由,登陆跳转没有刷新页面)

## 最小可复现仓库

[https://github.com/tingrabbit/umi-refesh-demo](url)

## 复现步骤，错误日志以及相关配置

1. 登陆admin用户,进入菜单管理页->二级管理页,可见权限路由,该用户在权限内
2. 登出
3. 登陆user用户,查看菜单,菜单管理页->二级管理页可见,该用户应不在权限内
4. 按F5进行刷新,路由恢复正常,菜单管理页->二级管理不可见

## 相关环境信息

- **Umi 版本**：^3.2.14
- **Node 版本**：14.7.0
- **操作系统**： mac OS

**Comment by ycjcl868** [comment]
Fast Refresh？

**Comment by tingrabbit** [comment]
> Fast Refresh？

是@umijs/plugin-initial-state的refresh API,我期望用refresh来重新执行 getInitialState 方法，并获取新数据并达到更新权限文件access.ts返回的数据,进而更新菜单权限的功能

**Comment by laozhu** [comment]
遇到同样的问题，现在登录后不得不使用 `window.location.href = '/'` 来刷新权限。

**Comment by XSmarter** [comment]
我也遇到了，升级了umi 到 3.3.2 refresh就正常使用了，可以升级一下试试

**Comment by sorrycc** [comment]
@tingrabbit @laozhu 还有问题吗？

**Comment by ouzhou** [comment]
用的pro-layout, 在refresh后，onPageChange触发时间更快，这个时候拿不到InitialState更新的用户数据，导致虽然登录成功了还是会跳转到登录页面

**Comment by ouzhou** [comment]
官方案例里面写的权限refresh没啥可行性 onPageChange里面其实做不了这个

**Comment by okilled** [comment]
+1

**Comment by mumu-baba** [comment]
+1，因为权限数据是登录完去请求，如果登录完再调用权限接口，等接口值回来，去setInitialState会导致登录页面卡顿，导致权限数据没有返回，onPageChange触发时间太快（因为权限是页面级别等。只能等数据回来才能渲染页面），期待登录成功增加中间过度页，处理项目基础数据等拉取。目前也是用window.location.href 去刷新的。

**Comment by mumu-baba** [comment]
@sorrycc 期待大佬有个好的优化。

**Comment by fz6m** [comment]
`access` 是静态一次性的，如果需要动态权限变化，要用 [`<Access></Access>`](https://umijs.org/docs/max/access#access-1) 包起来。

**Comment by AmorDiamond** [comment]
> 
`
export const routes: Route[] = [
    {
        key: 'dashboard',
        path: '/dashboard',
        component: '@/pages/dashboard/index',
        name: '工作看板',
        icon: 'DashboardOutlined',
        access: 'DASHBOARD',
    },
]
`
这种是直接设置在路由上的。
然后登录成功的时候，通过以下方式处理初始状态数据和跳转系统页面
`
const { refresh } = useModel('@@initialState')
await refresh()
history.replace('/dashboard')
`
![image](https://github.com/umijs/umi/assets/22789550/3abaa76e-a476-48c7-b605-ad363c84ab25)

就会出现进入页面后显示403界面，可能是渲染页面的时候Access的状态数据没有更新。
重新刷新页面就是正常的啦。

**Comment by WestCraneLi** [comment]
这个问题，我也遇到了，用户有管理员、普通用户权限，管理员登录后，进入到首页，没有显示对应的管理员权限的菜单

* umi/max版本："@umijs/max": "^4.0.72",
* 系统：macos
* node版本：v16.20.0

解决方案：
* 给进入到的页面加上 `// @refresh reset` 注释，启动快速刷新，即可解决

ex: 
```tsx
// @refresh reset
export default function demo() {
  // TODO
}
```

参考链接：[fast-refresh](https://v3.umijs.org/zh-CN/docs/fast-refresh)
