### ISSUE TITLE
[Bug]  严重bug!!! 当 window.g_initialProps 包含 模板字符`$`，会导致页面标签错乱

### ISSUE THREAD

**Issue by robinv8** [umijs/umi#5840]
## What happens?
当 window.g_initialProps 包含 模板字符`$`，会导致页面标签错乱
![image](https://user-images.githubusercontent.com/12277531/102473642-a6a27680-4092-11eb-9ebb-8b978eb42fa8.png)

![image](https://user-images.githubusercontent.com/12277531/102473916-f97c2e00-4092-11eb-81ca-0167787f9886.png)

## 相关环境信息

- **Umi 版本**：3.3.1
- **Node 版本**：v12.18.3
- **操作系统**：mac

**Comment by robinv8** [comment]
复现代码
```javascript
import React from 'react';
import { IGetInitialProps } from 'umi';
const Index = ({ title }) => {
  return <div>{title}</div>;
};
Index.getInitialProps = (async ctx => {
  return {
    title: '`$`',
  };
}) as IGetInitialProps;
export default Index;

```

**Comment by ycjcl868** [comment]
这么神奇，我看看

**Comment by robinv8** [comment]
@ycjcl868 我处理了一下，我历史上第一个 pr 求合并
