### ISSUE TITLE
"export 'connect' was not found in 'umi' 

### ISSUE THREAD

**Issue by shaojava** [umijs/umi#5844]
umi: 3.3.2
umijs/preset-react: 1.7.8

使用import { connect } from 'umi';提示"export 'connect' was not found in 'umi' 

新项目准备使用新版本umi
之前有个项目umi 3.2.14 使用import { connect } from 'umi';没有问题
 
新项目切换umi版本问题依旧 从3.2.14 到 3.3.2 都会报 "export 'connect' was not found in 'umi' 
只能使用import { connect } from 'dva'进行解决
很奇怪的问题

**Comment by xiaohuoni** [comment]
models 下需要有 dva 的 models 文件，并且执行过 umi dev 或者 umi g tml 之类的命令。

**Comment by jiachaosun** [comment]
只是执行umi dev并不生效，.umi里没有plugin-dva插件，需要手动执行umi generate tmp才行

**Comment by caver-yan** [comment]
umi当前版本是3.4.0，也执行了umi dev && umi generate tmp命令，还是会报同样的错误"export 'connect' was not found in 'umi'

**Comment by caver-yan** [comment]
.umi中没有找到plugin-dva文件

**Comment by yanyang1116** [comment]
实测下来：
`
"umi": "^3.5.41",
"@umijs/preset-react": "1.x",
// 有问题 ❌
`

改为 ↓↓↓

`
“@umijs/preset-react": "1.8.32",
"umi": "3.5.41"
// 可以 ✅
`
**当然，可能和 preset-react 没关系，只和 umi 有关，就不具体测了**
