### ISSUE TITLE
如何解决ssr的页面打开时会出现闪白

### ISSUE THREAD

**Issue by stoneyallen** [umijs/umi#5845]
## What happens?

使用umi prerender后的页面，打开时会先看到一部分内容，然后运行时的react重新运行一遍页面内容，导致页面出现了空白而后又出现相同内容

## How To Reproduce

下面是官方文档的截图
![image](https://user-images.githubusercontent.com/5013633/102567995-984d6c80-411d-11eb-8c20-0950ec45b132.png)

**Comment by ycjcl868** [comment]
这个例子在哪？ umi 2 的？

**Comment by stoneyallen** [comment]
> 这个例子在哪？ umi 2 的？

目前项目时Umi2，半年前提的跟ssr相关的三个bug，你们还没解决完，所以还没迁移到Umi3，但是看了你们的Umi3官网截图，发现还是有空白的时间，你可以上面的红色框

**Comment by ycjcl868** [comment]
图裂了

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/110906668-1eaec000-82c1-11eb-8434-03169ad7fdd2.png)

看了下 https://segmentfault.com/questions 实现，没什么问题

**Comment by wentoos** [comment]
我也发现这个问题了 毫无头绪
