### ISSUE TITLE
[Bug] ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by effapp** [umijs/umi#5849]
onSubmit = async (model) => {
        await this.setState({ data: model });
    }

上述的代码报错了：

ReferenceError: regeneratorRuntime is not defined

- **Umi 版本**：3.3.2
- **Node 版本**：14.11.0
- **操作系统**：windows 2019

**Comment by JeanZhao** [comment]
我也碰到了  当使用 async/await开发组件后，在项目中应用，会提示这个错误。不知道是不是需要额外配置? 兄台，你后来解决了么？
> onSubmit = async (model) => {
> await this.setState({ data: model });
> }
> 
> 上述的代码报错了：
> 
> ReferenceError: regeneratorRuntime is not defined
> 
> * **Umi 版本**：3.3.2
> * **Node 版本**：14.11.0
> * **操作系统**：windows 2019

**Comment by JeanZhao** [comment]
已解决。umi依赖的是father-build来完成的打包，所以最终还是通过father-build来使我们打包的目标文件为es5规范，并用babel/runtime来识别regeneratorRuntime 。
具体修复步骤为：
1. npm install @babel/runtime
一定要在dependencies里添加，这样组件在被引用时才会打包使用这个dependency

2. .fatherrc.ts文件里, 设置 { target: 'browser', runtimeHelpers: true }
