### ISSUE TITLE
[Bug] 请问如何在useModel('model')是去加载model中的useEffect而不是程序一启动就执行了useEffect

### ISSUE THREAD

**Issue by laolaolulu** [umijs/umi#5851]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

import { useState,useEffect, useCallback } from 'react';
import { query } from '../services/basedata'

export default function useAuthModel() {
  const [bdlist, setbdlist] = useState<API.BaseData[]>([]);
  useEffect(()=>{
     //查询列表
     query().then(res => {
      setbdlist(res);
    });
  }, []);

  return {
    bdlist
  };
}

我需要在第一次执行useModel('model')去初始化这个model的所有数据,而不是程序一启动就把所有model都加载出来了

**Comment by zhang0ZGC** [comment]
确实是有这个问题。。。getInitialState跟models文件夹里面的代码时同时执行的。。我 `getInitialState` 方法里面可能有校验权限的步骤，设置token等功能，结果 `models` 文件夹里面的方法却比它先执行了，只能拆出来使用hooks的方式引入 🤣

**Comment by Kaier33** [comment]
所有的model在启动(刷新)时全部要跑一遍. 总感觉不太好~
我不在Model中使用effect, 只写方法, 然后在组件的effect去调用

**Comment by hooliy** [comment]
怎么解决呢？打开登录页就把models全执行了一遍，导致页面报了一堆的403提示框，体验太差了

**Comment by promotion-xu** [comment]
dynamic能解决这个问题吗
