### ISSUE TITLE
[Bug] SSR mode:'string' 服务端没有报错日志

### ISSUE THREAD

**Issue by zfhslfgit** [umijs/umi#5853]
## What happens?

mode:'string' 服务端没有报错日志，`pages/index.js`写了一个`window.location.href`导致SSR失效，但是没有任何报错日志。
导致在复杂的项目难以定义问题。
```
    const { err, html } = await render({
      path: ctx.request.url,
      mode: 'string',
    });
```
![image](https://user-images.githubusercontent.com/12530974/102682706-927f8600-4206-11eb-9dfc-fa940636a34f.png)

## 最小可复现仓库

> https://github.com/zfhslfgit/ssr-with-eggjs-test

## 相关环境信息

- **Umi 版本:3.2.9：
- **Node 版本:10.16.3：
- **操作系统:MacOS：

**Comment by ycjcl868** [comment]
const { html, error, rootContainer } 错误在 `error` 对象里

console.error('error', error)
