### ISSUE TITLE
[Bug] SSR styled-components服务端没有渲染出style

### ISSUE THREAD

**Issue by zfhslfgit** [umijs/umi#5855]
## What happens?

使用了`styled-components`，服务端没有正常渲染出`style`导致没有样式，闪烁严重

![image](https://user-images.githubusercontent.com/12530974/102685664-468c0b80-421d-11eb-89c9-6115d94381b0.png)

## 最小可复现仓库

> https://github.com/zfhslfgit/ssr-with-eggjs-test-2

## 相关环境信息

- **Umi 版本:3.2.9：
- **Node 版本:10.16.3：
- **操作系统:MacOS：

**Comment by wangjiangs** [comment]
这个问题解决了吗？我也碰到了，styled-components没办法导出到静态的css文件里面。生成的是css-in-js。所以在ssr中会闪烁。

**Comment by MakerTED** [comment]
我也遇到了类似的问题，希望可以得到解决。

启用 SSR （egg）和动态加载时，服务器端生成的 html 中包含有 umi.js 和 html 内容。其它的 js 和 css 是需要通过 umi.js 在浏览器端动态加载的。所以会看到页面中的 html 元素没有任何样式，当 css 动态加载完成后，就可以正常显示了。
