### ISSUE TITLE
umi 使用 access 配置路由不生效

### ISSUE THREAD

**Issue by sunbingye** [umijs/umi#5863]
//access.js 文件
export default function (initialState) {
console.log('initialState', initialState);
return {
canReadGoods: initialState.roleId === 1 || initialState.roleId === 2
};
}
// .umirc.ts 文件
routes: [
{
path: '/',
component: '@/layouts/index',
routes: [
{ path: '/', component: '@/pages/index', exact: true },
{ path: '/login', component: '@/pages/login', exact: true },
{
path: '/goods',
component: '@/pages/goods',
// exact: true,
access: 'canReadGoods',
},
]
}
]
已经验证 access 文件返回的 canReadGoods 值是正确的，但是 goods 路径访问没有受到影响。
还有一个问题，如果使用约定式路由，需要对 Goods 路由扩展，即在 goods.js 文件中使用 Goods.access=useAccess().canReadGoods 来进行扩展，但是 hooks 不能在函数组件外部使用，那么该如何配置？

**Comment by beatlesD** [comment]
你好，你解决了这个问题了么

**Comment by sunbingye** [comment]
> 你好，你解决了这个问题了么

没有。。。

**Comment by leftstick** [comment]
提供可复现repo，不然就凭你那段模糊的描述，没人能帮忙的。

**Comment by sunbingye** [comment]
无所谓了，不用这个了，问题太多，网上的解决方案太少

**Comment by beatlesD** [comment]
那你现在用啥做权限路由呀

**Comment by sunbingye** [comment]
用配置式吧，我没用别的，只是学习，没在项目中用到
