### ISSUE TITLE
约定式路由扩展与dva的connect函数冲突

### ISSUE THREAD

**Issue by sunbingye** [umijs/umi#5868]
如果一个组件导出时使用 connect 函数包装，则对该组件的路由扩展失效，看了网上有人说在 connect 外面再包装一层 withRouter 可以解决，实际试验后还是不行。

**Comment by sorrycc** [comment]
路由扩展是什么意思？

**Comment by sunbingye** [comment]
> 路由扩展是什么意思？

比如说定义了一个 Home 组件，如果是约定式路由，可以通过 Home.title="home page" 的形式给路由做扩展，官方文档在这：https://umijs.org/zh-CN/docs/convention-routing#%E6%89%A9%E5%B1%95%E8%B7%AF%E7%94%B1%E5%B1%9E%E6%80%A7

**Comment by mynameismaosheng** [comment]
请问这个问题怎么解决呢?
function HomePage() {
  return <h1>Home Page</h1>;
}

HomePage.title = 'Home Page';

export default connect()(HomePage);

**Comment by feibi** [comment]
> 请问这个问题怎么解决呢?
> 
> ```
> function HomePage() {
>   return <h1>Home Page</h1>;
> }
> 
> HomePage.title = 'Home Page';
> 
> export default connect()(HomePage);
> ```

那就再包一层
```
const ConnectPage = connect()(HomePage);
ConnectPage.title = 'Home Page';
export default ConnectPage;
```
