### ISSUE TITLE
[Bug] 按照文档umi2升级到umi3以后，因为moment导致打包体积变大

### ISSUE THREAD

**Issue by WebPuY** [umijs/umi#5869]
## What happens?

按照文档umi2升级到umi3以后，重新安装依赖，没有通过yarn add等方式引入moment，但是发现moment仍然打包进入了umi.js，导致umi.js体积变大。

这是umi2的分析结果
![image](https://user-images.githubusercontent.com/12791829/102863726-f5268b00-446d-11eb-9936-fb47da38110c.png)

这个是umi3的结果
![image](https://user-images.githubusercontent.com/12791829/102863402-821d1480-446d-11eb-99cd-a9273890119e.png)

## 最小可复现仓库

> 无

## 相关环境信息

- **Umi 版本**：^3.3.2
- **Node 版本**：v10.16.0
- **操作系统**：windows10

**Comment by williamnie** [comment]
可以通过antd-dayjs-webpack-plugin 插件替换为dayjs，或者将moment 打出去也行
```
import AntdDayjsWebpackPlugin from 'antd-dayjs-webpack-plugin';
  chainWebpack(memo, { env, webpack, createCSSRule }) {
    memo.plugin('AntdDayjsWebpackPlugin').use(AntdDayjsWebpackPlugin);
  },
```

**Comment by xiaohuoni** [comment]
https://github.com/umijs/plugins/blob/master/packages/plugin-antd-dayjs/README.md
