### ISSUE TITLE
[Bug] useRequest typescript 类型推导

### ISSUE THREAD

**Issue by bluexiaowei** [umijs/umi#5872]
## 最小可复现仓库
使用 `import {  useRequest } from 'umi'` 返回数据无法正常推导。
![image](https://user-images.githubusercontent.com/20636951/102951527-08863480-4508-11eb-9208-86e5ef82403b.png)
使用 `import { useRequest } from 'ahooks'` 正常。
![image](https://user-images.githubusercontent.com/20636951/102951700-6f0b5280-4508-11eb-8560-23a5d196ef18.png)

## 相关环境信息

- **Umi 版本**：3.3.3
- **@umijs/preset-react 版本**: 1.7.8
- **typescript 版本**: 4.1.3
- **Node 版本**：13.X
- **操作系统**：macos

**Comment by xu-Aurora** [comment]
这个我也碰到过，umi和ahooks里面的useRequest有点不一样的，umi的useRequest要在请求接口函数的返回值用data接受下，不能不能直接获取到接口返回的返回值

**Comment by ruofeng086** [comment]
我也遇到了，怎么解决de？，怎么解决都不提一下就关了？

**Comment by bluexiaowei** [comment]
```tsx
import { request } from 'umi';

export function userLogin(){
     return request<{success: boolean; data: {token: 'xxx'}}>("/user/login")
}

```

**Comment by destinytaoer** [comment]
出现同样的问题，有解决？

**Comment by Gorden-Wang** [comment]
@destinytaoer 
源码中是通过接口返回的 data来推导的：
```tyepscript
function useRequest<R extends ResultWithData = any, P extends any[] = any>(
  service: CombineService<R, P>,
  options?: BaseOptions<R['data'], P>,
): BaseResult<R['data'], P>;
```

只要保证接口返回中包含这个字段即可：

```typescript
interface Response<T> {
  success: boolean;
  status: number;
  message: any;
  result: T;
  data: T;
}

type IUserShape = Response<{test: string}>

export async function foo() {
  return request<API.IUserShape>(
    '/getUser',
    {
      method: 'GET',
    },
  );
}
```

**Comment by loveCHN** [comment]
> @destinytaoer 源码中是通过接口返回的 data来推导的：
> 
> ```
> function useRequest<R extends ResultWithData = any, P extends any[] = any>(
>   service: CombineService<R, P>,
>   options?: BaseOptions<R['data'], P>,
> ): BaseResult<R['data'], P>;
> ```
> 
> 只要保证接口返回中包含这个字段即可：
> 
> ```ts
> interface Response<T> {
>   success: boolean;
>   status: number;
>   message: any;
>   result: T;
>   data: T;
> }
> 
> type IUserShape = Response<{test: string}>
> 
> export async function foo() {
>   return request<API.IUserShape>(
>     '/getUser',
>     {
>       method: 'GET',
>     },
>   );
> }
> ```

完美解决
