### ISSUE TITLE
[Bug] 使用@umijs/plugin-initial-state插件导致SSR服务端渲染失败

### ISSUE THREAD

**Issue by Jeepeng** [umijs/umi#5873]
## What happens?

使用@umijs/plugin-initial-state（@umijs/plugin-model）导致SSR服务器渲染失败
```js
// app.tsx
export function getInitialState() {
  return {};
}
```

## Context

- **Umi Version**: v3.3.3
- **Node Version**: v14.15.3
- **Platform**: macOS Big Sur 11.1

**Comment by ilanguis** [comment]
有此问题+1

>

**Comment by tangsengrouyidai** [comment]
有此问题+2

**Comment by lyscms** [comment]
有此问题+3

**Comment by williamnie** [comment]
提供一个复现仓库吧，ssr模式貌似只支持dva做数据管理吧

**Comment by lyscms** [comment]
> 提供一个复现仓库吧，ssr模式貌似只支持dva做数据管理吧

复现地址： https://github.com/lyscms/lyscms-ssr-pis.git

**Comment by williamnie** [comment]
这个插件确实是有问题，不过即使没问题，现在也不支持ssr模式，ssr模式目前应该只有dva可以，整个流程是在服务端拿到数据，放到window. g_initialProps里，等到页面渲染时需要拿到这些数据，在序列化回model里，react会进行hydra，不一致会重新render，目前hooks的数据流好像没有序列化回model里这个操作

**Comment by williamnie** [comment]
@ycjcl868 开启getInitialState这个插件后会造成ssr失败，我昨天没找到问题，得需要你看下😳
