### ISSUE TITLE
[Feature Request] 希望提供 cli 生成约定路由配置

### ISSUE THREAD

**Issue by tongyu-public** [umijs/umi#5874]
## Background

很多插件不支持约定路由了，不想造轮子，是不是可以暴露一个命令自动生成路由配置

## Proposal

umi gen-routes

**Comment by shijistar** [comment]
可以看一下 `~/src/.umi/core/routes.ts`，约定式路由都生成在这里，可以 `import` 或拷出来作为声明式路由
