### ISSUE TITLE
是否支持 从外部项目导入组件，dev下能够热更新，prod能够打包编译

### ISSUE THREAD

**Issue by MoonSeeing** [umijs/umi#5876]
## Background
目前我的项目 都是使用了 umi框架 构建的，但是项目管理上使用了monorepo 项目结构如下
![image](https://user-images.githubusercontent.com/19420622/103061731-39896680-45e7-11eb-89db-9493e8b4d62c.png)
apps下的三个都是基于umi的项目，shared 下有两个包，一个是 compnents用于共享组件，utils共享函数方法的。
使用lerna 和yarn workpace 协同管理。
这边尝试了 在 项目中引用 utils 是可以实现热更新的，因为utils是 可执行的纯js.但是components下的组件确无法共享。

![image](https://user-images.githubusercontent.com/19420622/103062001-e663e380-45e7-11eb-9527-7c0231533ba5.png)
```
// shared/components
import React from 'react'
const SharedButton =()=><div>124</div>
export default SharedButton;
```
```
// shared/utils
export const testSharedFun = () => {
 console.log('funciton utils test success!')
};
```
报错如下
>>>Module parse failed: Unexpected token (4:24)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { Button } from 'antd';
| 
> const SharedButton =()=><div>124</div>
| export default SharedButton;
## Proposal

应该是因为 外部项目的组件通过workspace的方式 引入 是没有经过 babel  处理 react jsx 语法造成的。那是否有方案可以支持 这种外部组件能够在项目中可以被正常打包和编译呢。
或者说 这种多个 umi 项目采用monorepo 方式 有什么好的组件共享方式吗？（不上传npm,bit，也不用做版本维护）只在本地一个仓库 下 维护就好。

## Additional context
 "umi": "^3.2.19"

**Comment by MoonSeeing** [comment]
@sorrycc

**Comment by sorrycc** [comment]
用 extraBabelIncludes 包含其他需要做 babel 编译的目录或 npm 包。
