### ISSUE TITLE
es5-imcompatible-versions版本问题

### ISSUE THREAD

**Issue by tanyo520** [umijs/umi#5879]
今天所有ci服务器又爆了，没找出哪个依赖包导致，在主package.json加上
"es5-imcompatible-versions": "0.1.64" 可以临时解决，但是打出来的包，ie11不支持
![image](https://user-images.githubusercontent.com/5094034/103078620-3e611100-460d-11eb-95b1-d4e539ea4bbc.png)

## 相关环境信息

- **Umi 版本**：
 v2最新版本
- **Node 版本**：
- **操作系统**：

**Comment by sorrycc** [comment]
> 今天所有ci服务器又爆了，没找出哪个依赖包导致，在主package.json加上

报什么错？可复现吗？

**Comment by tanyo520** [comment]
> > 今天所有ci服务器又爆了，没找出哪个依赖包导致，在主package.json加上
> 
> 报什么错？可复现吗？

可以复现 就是我截图的那个错误

**Comment by sorrycc** [comment]
截图是 patch 失败的报错，不是构建的。
