### ISSUE TITLE
.umirc.js 中配置 routes 属性报错

### ISSUE THREAD

**Issue by dkvirus** [umijs/umi#588]
@sorrycc 

# 版本信息

- node 8.0.0
- umi 1.3.5

# 问题

在 [umi-examples 中路由配置](https://github.com/umijs/umi-examples/blob/master/routes-via-config-bigfish/.umirc.js) 看到路由支持 js 文件格式配置，试了一下，结果报错。

```
"D:\work\csii\git\seagod-umi\.umirc.js" 中配置的 "routes" 并非约定的配置项，请选择 "context, 

disableDynamicImport, disableServiceWorker, exportStatic, loading, pages, plugins, preact, singular, 

outputPath, disableFastClick, hd, hashHistory" 中的一项，详见 https://fengdie.alipay-

eco.com/doc/h5app/configuration
```

**Comment by sorrycc** [comment]
你应该不是用 umi@1.3.5 这个版本跑的，注意全局和项目本地 umi 版本的差异。

**Comment by dkvirus** [comment]
@sorrycc 是的，上午只更新了本地 umi，全局 umi 还是老版本，结果报那个错误。

这会刚把全局 umi 也更新了一下，直接在命令行敲 `umi dev` 什么反应也没有，等了好久了都。按理说启动不应该这么慢，看起来像卡住了一下，试了几次都这样。

**Comment by sorrycc** [comment]
simple 那个例子也会卡住吗？

**Comment by dkvirus** [comment]
@sorrycc  

> 1. simple 例子

`simple` 下面就一个 index.js，没有配置路由，使用全局 `umi dev` 启动成功；

> 2. routes-via-config-bigfish 例子，有路由配置，看配置还是嵌套路由。

`routes-via-config-bigfish` 启动报错编译失败。

```
// .umirc.js 配置文件
// 测试案例里嵌套路由配置
routes: [
    {
      path: '/',
      component: 'a',
      indexRoute: { redirect: '/b' },
      childRoutes: [
        { path: '/b', component: 'b' },
        { path: '/users/:name', component: 'c' },
        { path: '/posts/:name', redirect: '/users/:name' },
      ]
    },
  ],
```

```
Failed to compile.

./pages/.umi/router.js
Module not found: Can't resolve '../../b' in 'D:\study\umi\umi-examples\routes-via-config-bigfish\pages\.umi'
```

看报错信息是组件 b 引用路径问题，我将其换成 `./pages/b` 之后启动成功，但是显示异常。`indexRoute: { redirect: '/b' },` 代码猜测是当路由是 `/` 时重定向到 `/b`，实际并没有重定向过去。

> 3. `routes-via-config` 下也有路由配置，启动成功，运行成功。

该文件里没有父子嵌套路由，运行成功，跳转页很正常。

```
// .umirc.js 配置文件
routes: [
    {
      path: '/',
      exact: true,
      component: 'a',
    },
    {
      path: '/list',
      component: 'b',
    },
    {
      path: '/redirect',
      redirect: '/users/guanguan',
    },
    {
      path: '/users/:name',
      exact: true,
      component: 'c',
    },
  ],
```

**Comment by sorrycc** [comment]
routes-via-config-bigfish 这是内部例子，可以忽略他。所以，在 simple 和 routes-via-config 下都不卡，然后在你的项目里卡？

**Comment by dkvirus** [comment]
大佬，之前是的，一直卡着不动，我重新起了一个 umi 项目，现在可以了，应该不是 umi 的问题，可能是我之前哪里写的不对吧~~
