### ISSUE TITLE
[Bug]  extraBabelIncludes  Error: Invalid config key

### ISSUE THREAD

**Issue by MoonSeeing** [umijs/umi#5880]
## What happens?
![image](https://user-images.githubusercontent.com/19420622/103115676-8a0fcb00-469e-11eb-8446-1bf64df3eaa9.png)
在  umi 启动的项目中添加 extraBabelIncludes 就会报错如下
![image](https://user-images.githubusercontent.com/19420622/103115700-a1e74f00-469e-11eb-880b-d8759cd684e4.png)

如果不添加 这个参数 就可以正常运行。
## Mini Showcase Repository(REQUIRED)

![image](https://user-images.githubusercontent.com/19420622/103116842-d3621980-46a2-11eb-8eed-b2f4727f0656.png)

代码地址：
https://github.com/MoonSeeing/umi-shared

## How To Reproduce
1. clone code
2. yarn
3. yarn start

**Expected behavior** 1. 2.

## Context

- **Umi Version**: umi": "^3.2.14",

**Comment by MoonSeeing** [comment]
这边看到 umi3 似乎把该配置删掉了
![image](https://user-images.githubusercontent.com/19420622/103132456-91a39400-46df-11eb-91f1-6d6e02ab8398.png)
那请问 是否有方法可以 babel-loader src之外 别的文件夹的 组件呢？

**Comment by sorrycc** [comment]
是的，现在不支持，不过可以通过 chainWebpack 修改 `.rule('js')` 的配置。

**Comment by MoonSeeing** [comment]
最新版本的umi  又支持这个配置了，
