### ISSUE TITLE
[Bug] ssr 模式，使用 dynamicImport 配置，会导致 useEffect 执行两次

### ISSUE THREAD

**Issue by robinv8** [umijs/umi#5881]
## What happens?
使用 dynamicImport 配置, 即便 useEffect 依赖项为 [], 还是会执行两次

## 相关环境信息

- **Umi 版本**：v3.3.3
- **Node 版本**：v12.18.3.
- **操作系统**：macos

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/105453516-21802380-5c35-11eb-80e6-b49603070c1b.png)


开启后，没有渲染两次
