### ISSUE TITLE
[Bug] chainWebpack配置HtmlWebpackPlugin组件后,无法热更新页面.

### ISSUE THREAD

**Issue by ruanhailiang** [umijs/umi#5882]
## What happens?
1. 我创建了一个新的工程[ yarn create @umijs/umi-app]. 
2. 通过.umirc.ts的配置文件中chainWebpack,修改webpack配置后,能够正常运行并且能够热编译,但页面上的元素无法动态更新了.
我的配置文件:

import { defineConfig } from 'umi';
const CopyWebpackPlugin = require("copy-webpack-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const HtmlWebpackTagsPlugin = require('html-webpack-tags-plugin');
const webpack = require("webpack");

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },

  async chainWebpack(config){
    const prod = process.env.NODE_ENV === 'production'; // 生产模式开启
    config.plugin("CopyWebpackPlugin").use(new CopyWebpackPlugin({
      patterns: [{
          from: "node_modules/cesium/Build/CesiumUnminified",
          to: "cesium",
        },],}
    ));
    config.plugin("HtmlWebpackPlugin").use(new HtmlWebpackPlugin({title: "Application name", template: './src/index.html'}));
  },
  routes: [
    { path: '/', component: '@/pages/index' },
  ],
});

## How To Reproduce
我的package.json文件
`{
  "private": true,
  "scripts": {
    "start": "umi dev",
    "build": "umi build",
    "postinstall": "umi generate tmp",
    "prettier": "prettier --write '**/*.{js,jsx,tsx,ts,less,md,json}'",
    "test": "umi-test",
    "test:coverage": "umi-test --coverage"
  },
  "gitHooks": {
    "pre-commit": "lint-staged"
  },
  "lint-staged": {
    "*.{js,jsx,less,md,json}": [
      "prettier --write"
    ],
    "*.ts?(x)": [
      "prettier --parser=typescript --write"
    ]
  },
  "dependencies": {
    "@ant-design/pro-layout": "^6.5.0",
    "@types/copy-webpack-plugin": "^6.3.0",
    "@umijs/preset-react": "1.x",
    "cesium": "^1.76.0",
    "html-webpack-plugin": "^4.5.0",
    "html-webpack-tags-plugin": "^2.0.17",
    "resium": "^1.13.1",
    "umi": "^3.3.3"
  },
  "devDependencies": {
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "@umijs/test": "^3.3.3",
    "lint-staged": "^10.0.7",
    "prettier": "^2.2.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "typescript": "^4.1.2",
    "yorkie": "^2.0.0"
  }
}
`

**Comment by sorrycc** [comment]
html-webpack-plugin 不要用，会和内部插件冲突；copy-webpack-plugin 内置了。

**Comment by muuma** [comment]
> html-webpack-plugin 不要用，会和内部插件冲突；copy-webpack-plugin 内置了。

拆包之后有很多 Render block request，怎么能在 script 标签上添加 defer 呢？

**Comment by 461201574asd** [comment]
> html-webpack-plugin 不要用，会和内部插件冲突；copy-webpack-plugin 内置了。
大佬，umi3热更新的时候，路由多的时候，copy-webpack-plugin会卡5-6s，怎么优化呢
