### ISSUE TITLE
[Bug] isGitUrl function returns false for url "https://github.com/ant-design/pro-blocks/tree/umi%403/AccountSettings"

### ISSUE THREAD

**Issue by zhangyongjiang** [umijs/umi#5886]
## What happens?

Command `umi block add "https://github.com/ant-design/pro-blocks/tree/umi%403/AccountSettings"` failed

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
block 功能不再推荐使用，请使用其他方式组织页面。
