### ISSUE TITLE
[Bug] umi3不兼容IE

### ISSUE THREAD

**Issue by quicklearning123** [umijs/umi#5887]
## What happens?

  targets: {
    ie: 10,
  },

![image](https://user-images.githubusercontent.com/70048681/103164461-67b8b180-4846-11eb-9ada-a7cc640cf0e4.png)

## 最小可复现仓库

按官方文档默认方式创建仓库

## 复现步骤，错误日志以及相关配置

必现

## 相关环境信息

- **Umi 版本**： ^3.2.21
- **Node 版本**：10+
- **操作系统**：win10 IE11

**Comment by afc163** [comment]
Duplicate of #5660
