### ISSUE TITLE
[Bug] umi3.3.3 开启ssr请求数据后报错

### ISSUE THREAD

**Issue by RuoFeng2015** [umijs/umi#5888]
![image](https://user-images.githubusercontent.com/41161634/103171796-ff8bbf00-4889-11eb-9a9e-557ef44975fa.png)
![image](https://user-images.githubusercontent.com/41161634/103171807-0ca8ae00-488a-11eb-87a4-c3f1b7e65a91.png)

**Comment by Baoyx007** [comment]
如果用了 dva, 那么返回的数据 key, 必须是 dva store 中的 key
