### ISSUE TITLE
[Feature Request] umi是否能支持到更改webpack config 让 webpack 打包项目之外的组件，也就是在 babel -loader的include 增加一个项目之前的路径 

### ISSUE THREAD

**Issue by MoonSeeing** [umijs/umi#5895]
## Background
组件共享 想将项目之外 ，也就是 src之外的组件 打包到项目中
![image](https://user-images.githubusercontent.com/19420622/103268288-2fec6e00-49ee-11eb-88ab-c62c222dd595.png)
app 是使用umi 的框架的项目，shared 是一些公用的 组件或者函数，这边采用lerna 以及yarn workspace 可以将 普通函数做到共享。但是UI组件 无法共享 ，因为 wepack没有给外部的组件做babel转换，这边如何用chainwepack  更改umi 的webpack babel-loader的 include 配置呢？
A

**Comment by sorrycc** [comment]
试试通过 chainWebpack 修改 `.rule('js')` 的配置。
