### ISSUE TITLE
[Bug] 开启ssr项目跑起来后的警告

### ISSUE THREAD

**Issue by WebPuY** [umijs/umi#5896]
## What happens?

如果没有开启ssr，在浏览器中报警告：

Warning: Please use `require("history").createHashHistory` instead of `require("history/createHashHistory")`. Support for the latter will be removed in the next major release. 如下图
![image](https://user-images.githubusercontent.com/12791829/103269283-75aa3600-49f0-11eb-859b-7c0c0a72e11b.png)

开启ssr后，控制台中报如下警告
![image](https://user-images.githubusercontent.com/12791829/103269232-5dd2b200-49f0-11eb-9fbc-60af102e2f7c.png)

## 最小可复现仓库

> https://github.com/WebPuY/umi-demo

## 复现步骤，错误日志以及相关配置

项目运行后，浏览器访问 http://localhost:9099/privacy-policy?lang=en-US

## 相关环境信息

- **Umi 版本**：3.3.2
- **Node 版本**：v10.16.0
- **操作系统**：win10

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/105811817-0c233600-5f62-11eb-839a-500be2619e1e.png)


`dva/lib/index.js` 里的 `require('history/createHashHistory')` 需要改成 `require('history').createHashHistory`  @sorrycc

**Comment by ycjcl868** [comment]
useLayoutEffect warning 可以忽略，不影响 SSR

**Comment by WebPuY** [comment]
这个问题新版本已经解决了吗？close掉了 @ycjcl868
