### ISSUE TITLE
国际化formatMessage ,返回Null

### ISSUE THREAD

**Issue by lemovel** [umijs/umi#5897]
## What happens?

import { formatMessage } from 'umi/locale';
export default {
  sourceTypes: {
    /* 数据源类型 */
    jdbc: formatMessage({ id: 'report.shuJuKu' }),
    msg: formatMessage({ id: 'report.baoWen' }),
  },}
在其他页面引用此变量的返回为Null，加个延迟就能返回正确的值。
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:2.4.4
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
import { formatMessage } from 'umi';

不是 
import { formatMessage } from 'umi/locale';
