### ISSUE TITLE
[Bug] 在HTTPS=1的情况下, 页面多次重定向会出现以下报错并且服务崩溃

### ISSUE THREAD

**Issue by Renderz** [umijs/umi#5901]
## What happens?

在启动HTTPS的情况下, 如果页面出现多次重定向, 会出现以下报错. 
(node:11076) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
_stream_writable.js:476
    throw new ERR_MULTIPLE_CALLBACK();
    ^

Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
    at onwrite (_stream_writable.js:476:11)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:12)
    at Immediate._onImmediate (D:\jyfei\newMyApp\repo-main\node_modules\handle-thing\lib\handle.js:127:11)
    at processImmediate (internal/timers.js:456:21) {
  code: 'ERR_MULTIPLE_CALLBACK'

## Mini Showcase Repository(REQUIRED)

复现仓库: https://github.com/Renderz/repo

## How To Reproduce

1. yarn start
2. 进入 https://localhost:8000/test
3. 点击test按钮. 此时会出现多次重定向最后重定向回https://localhost:8000
4. 多次点击(1-2次), umi会崩溃并且报错

做了以下尝试
1. 关闭HTTPS, 不会出现问题.
2. 火狐不会出现问题, chrome会出现.
3. mac上不会出现, win上会出现.

## Context

- **Umi Version**: 3.3.3
- **Node Version**: v12.18.0
- **Platform**: win chorm 66.0.3359.139

**Comment by Renderz** [comment]
node升级到14.0+以上ok了... (可以,但是为什么

**Comment by ycjcl868** [comment]
可能是 nodejs 的 https 原生模块问题

**Comment by sorrycc** [comment]
那 umi 层也处理不了，遇到了就建议升级到 14 吧。你之前是多少？稳定版应该不会有问题才对。

**Comment by 939243423** [comment]
困扰了好久 以为是umi的配置问题 但不知道怎么改
