### ISSUE TITLE
[Bug]   开启umi中local的属性baseNavigator，初始化为什么getLocale是 “zh” ？

### ISSUE THREAD

**Issue by ISBN9527** [umijs/umi#5904]
## What happens?

`locale: {`
   ` // default zh-CN`
    `default: 'zh-CN',`
   ` antd: true,`
    `// default true, when it is true, will use `navigator.language` overwrite default`
    `baseNavigator: true, // 自动检测浏览器语言`
   ` baseSeparator: '-',`
  },`

为什么在初始化时，umi的方法getLocale获取到的值是"zh"?（ps：在初登录系统时，本地localstorage还没有umi_locale的时候。）

## 相关环境信息

- **Umi 版本**：3.3.3
- **Node 版本**：15.4.0
- **操作系统**：mac

**Comment by ISBN9527** [comment]
求大佬指点

**Comment by amin168** [comment]
我也是这个情况

**Comment by cuijiudai** [comment]
setLocale 本地缓存就有值了，不想这样

**Comment by kaipengHan** [comment]
> ## What happens?
> `locale: {` ` // default zh-CN` `default: 'zh-CN',` ` antd: true,` `// default true, when it is true, will use `navigator.language` overwrite default` `baseNavigator: true, // 自动检测浏览器语言` ` baseSeparator: '-',` },`
> 
> 为什么在初始化时，umi的方法getLocale获取到的值是"zh"?（ps：在初登录系统时，本地localstorage还没有umi_locale的时候。）
> 
> ## 相关环境信息
> * **Umi 版本**：3.3.3
> * **Node 版本**：15.4.0
> * **操作系统**：mac

刷新页面的时候需要清空localStorage中umi_locale的，才能获取navigator.language的值
