### ISSUE TITLE
[Bug] react-router-config in ./node_modules/umi/node_modules/@umijs/renderer-react/dist/index.js

### ISSUE THREAD

**Issue by EdisonVan** [umijs/umi#5905]
## What happens?
This dependency was not found:
* react-router-config in ./node_modules/umi/node_modules/@umijs/renderer-react/dist/index.js

## How To Reproduce
![image](https://user-images.githubusercontent.com/38999461/103333280-5bcc2a00-4aa8-11eb-8a4d-d7512b14e466.png)

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:^3.3.3
- **Node Version**:v10.16.0
- **Platform**:windwos 10
- **@umijs/preset-react**:^1.7.9

**Comment by sorrycc** [comment]
https://unpkg.com/browse/@umijs/renderer-react@3.3.3/package.json 这里有显式声明依赖的，所以肯定是依赖安装的问题，重装依赖再试吧。

**Comment by teamco** [comment]
The issue not in the @umijs/render-react - pay attention... 

AssertionError [ERR_ASSERTION]: filePath not found of **./node_modules/umi/node_modules/**@umijs/renderer-react
at ./node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:115:27
at Generator.next (<anonymous>)
  at asyncGeneratorStep (./node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:64:103)
  at _next (./node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:66:194)
  at ./node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:66:364
  at new Promise (<anonymous>)
    at ./node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:66:97
    at figureOutExport (./node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:125:17)
    at ./node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:184:201
    at Generator.next (<anonymous>)
