### ISSUE TITLE
[Bug] umi@3.3.3开发环境启动后没有生成sourcemap

### ISSUE THREAD

**Issue by WangJM001** [umijs/umi#5907]
## What happens?

开发环境启动后没有生成sourcemap
devtool没有配置使用的默认配置

## Mini Showcase Repository(REQUIRED)

不能复现再提供复现仓库

## Context

- **Umi Version**:3.3.3
- **Node Version**:
- **Platform**:

**Comment by WangJM001** [comment]
本地新建个项目又重现不出来了，先关了，重现了再开吧

**Comment by WangJM001** [comment]
应该和`splitChunks`配置有关，配置了`splitChunks` sourcemap就没有生成了

**Comment by ycjcl868** [comment]
是的，splitChunks 会导致sourceMap 失效

**Comment by WangJM001** [comment]
有解决方法么？还是说devtool配置其他的，配eval是可以的

**Comment by sorrycc** [comment]
@WangJM001 试试 devtool 配 sourcemap。

**Comment by WangJM001** [comment]
sourcemap也不行

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/104795835-3a7b7580-57ec-11eb-964b-493fb9df68b9.png)
没发现问题。。

**Comment by WangJM001** [comment]
sourcemap可以的，是我配置错了😅
