### ISSUE TITLE
[Bug] 开发模式保留 console，生产模式才去除 console，应该怎么做？

### ISSUE THREAD

**Issue by baobao12356** [umijs/umi#5909]
## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：
- **Node 版本**：
- **操作系统**：

**Comment by yingzhiji** [comment]
有一种方法是配置 terser 在压缩时去除 console：
```js
terserOptions: {
  compress: {
    drop_console: true
  }
}

**Comment by iamwjj** [comment]
> 有一种方法是配置 terser 在压缩时去除 console：
> 
> ```js
> terserOptions: {
>   compress: {
>     drop_console: true
>   }
> }
> ```

不知道为啥，我配置了没生效。。

**Comment by yingzhiji** [comment]
在哪里配置的

**Comment by iamwjj** [comment]
.umirc.ts的config里面配置的
