### ISSUE TITLE
How to handle `useRequest` errors correctly?

### ISSUE THREAD

**Issue by KrishnaPG** [umijs/umi#5910]
Tried various methods, still getting **"Unhandled Promise"** error or other unsatisfactory results. Would like to know what is the right way to handle errors with `useRequest`.

Here is the code:
````js
import { useRequest } from 'umi';

export default (props) => {
  const { data, error, loading } = useRequest(getData, {   throwOnError: true  });

  if (error)
    return <div>Failed to Load Data</div>;
  if (loading) {
    return <div>loading...</div>;
  }
  return <div>Username: {data}</div>;
}
````

I am using the default UMI application template, and there is a **network error** that need to be handled.

------------
**Problem:**

1.  If I set `throwOnError: false` then I would get below error in the console:
````
Uncaught (in promise) useRequest has caught the exception, if you need to handle the exception yourself, you can set options.throwOnError to true.
````
2. If I set `throwOnError: true` then I would get below error:
````
Uncaught (in promise) TypeError: Failed to fetch
````
3. If I turn off the `throw error` in the `app.tsx` errorHandler, then I would not see any errors, but the below error would NOT render in the UI
````
  if (error)
    return <div>Failed to Load Data</div>;
````

**Question:**
How to handle errors with `useRequest` so that:

1. I would get the error notification alert on the screen
2. I do NOT get `Uncaught (in promise) ` in the console logs
3. I get **error code** rendered in react fragment. That is: `<div>Failed to Load Data</div>`

--------------
In the `app.tsx` the default error handler as shown below:
````tsx
const errorHandler = (error: ResponseError) => {
  const { response } = error;
  if (response && response.status) {
    const errorText = codeMessage[response.status] || response.statusText;
    const { status, url } = response;

    notification.error({
      message: `请求错误 ${status}: ${url}`,
      description: errorText,
    });
  }

  if (!response) {
    notification.error({
      description: '您的网络发生异常，无法连接服务器',
      message: '网络异常',
    });
  }
  throw error;
};
````

**Comment by brickspert** [comment]
https://github.com/alibaba/hooks/issues/812
