### ISSUE TITLE
[Bug] 在mock文件夹里import src目录里的文件，开发时编译通不过

### ISSUE THREAD

**Issue by serenaxx** [umijs/umi#5911]
## 我在mock里加了一个文件，文件里import src 里的一个配置文件，但发现编译通不过，解析不了内置的@/目录
![image](https://user-images.githubusercontent.com/7919149/103432882-395e1c00-4c22-11eb-8667-450154831094.png)

**Comment by sorrycc** [comment]
不要 import src 下的文件。
