### ISSUE TITLE
autoprefixer doesn't work in umijs 3 when ssr is enabled

### ISSUE THREAD

**Issue by amerllica** [umijs/umi#5913]
## What happens?

I wanna use `autoprefixer` and support old browsers, it means when I used `display: flex` the built CSS should have:

```
{
  display:-webkit-box;
  display:-ms-flexbox;
  display:-webkit-flex;
  display:flex
}
```

But it seems, it doesn't work, inside `umi.css` I just see `display: flex`

## Mini Showcase Repository(REQUIRED)

I just create a simple app with `umijs` and just add `display: flex` in the `title` class and expect the built CSS have the earlier CSS of old browsers.

## How To Reproduce

Just create a simple project with `yarn create @umijs/umi-app` and then inside `.umirc.ts` I add below configs:

```
import { defineConfig } from 'umi';

const isDevelopment = process.env.NODE_ENV === 'development';

export default defineConfig({
  ssr: {
    mode: 'stream',
  },
  nodeModulesTransform: {
    type: 'none',
  },
  cssLoader: {
    modules: {
      localIdentName: isDevelopment
        ? '[path][name]__[local]'
        : '[contenthash:base64:5]',
    },
    sourceMap: isDevelopment,
  },
  routes: [{ path: '/', component: '@/pages/index' }],
});
```

**Expected behavior** 1. 2.

When I use `display: flex` I wanna have all possible equivalent CSS in the built. like: 

```
{
  display:-webkit-box;
  display:-ms-flexbox;
  display:-webkit-flex;
  display:flex
}
```

## Context

- **Umi Version**: "^3.3.3"
- **Node Version**: v14.15.1
- **Platform**: OSX Big Sur

**Comment by ycjcl868** [comment]
ref: https://github.com/umijs/umi/issues/5513

**Comment by ycjcl868** [comment]
The `ssr` doesn't concern `autoprefixer`, you can config `targets: { ie: 9 }` [detail](https://umijs.org/config#targets), the `autoprefixer` will work

![image](https://user-images.githubusercontent.com/13595509/105810490-e432d300-5f5f-11eb-8d73-b6088de5bf5f.png)

**Comment by amerllica** [comment]
@ycjcl868 , It's so weird because it works on any kind of SSR, it doesn't work just on UMIJS SSR. when I set the browser support for last 25, it should works but it doesn't.
