### ISSUE TITLE
[Bug] modifyBabelOpts 和 modifyBabelPresetOpts 对 node_modules 下的模块不生效

### ISSUE THREAD

**Issue by yingzhiji** [umijs/umi#5914]
通过阅读源码，以上两个 API 只会对 src 和 node_modules 里的模块生效，对 node_modules 里的 js 和 mjs 文件不生效，用户无法修改它们的 Babel 配置，而且会造成 src 和 node_modules 的 Babel 配置不一致

**Comment by LeoHuiyi** [comment]
我是用api.chainWebpack，去改js-in-node_modules rule的

**Comment by yingzhiji** [comment]
Umi 对于 node_modules 里的 .js 文件使用了单独的 Babel 配置：@umijs/babel-preset-umi/dependency，除了 api.modifyBabelOpts 和 api.modifyBabelPresetOpts，用户配置的 extraBabelPresets 和 extraBabelPlugins 也不生效，这会导致项目的同一种文件有不同的 Babel 配置，比如：我想加一个去除 console 语句的 Babel 插件，但是它只会作用于 src 内的文件，对 node_modules 里的文件不生效，而用户肯定期望它都是生效的。再细想一下，node_modules 里 .js 文件用单独的配置好像意义不大，src 里也是无论 .js、.jsx、.ts、.tsx 一律走 @umijs/babel-preset-umi/app 的。

**Comment by LeoHuiyi** [comment]
![image](https://user-images.githubusercontent.com/8001457/103518719-40e62500-4eaf-11eb-880c-e51bc14f6521.png)
![image](https://user-images.githubusercontent.com/8001457/103518848-70952d00-4eaf-11eb-988c-bd85cdab6a70.png)

比较诡异的是ts-in-node_modules rule可以生效，不知道是不是设计如此，还是bug。。。

**Comment by yingzhiji** [comment]
源码里就是 node_modules 里的 .jsx、.ts、.tsx 走 @umijs/babel-preset-umi/app，node_modules 里的 .js 走 @umijs/babel-preset-umi/dependency。

**Comment by sorrycc** [comment]
这是 by design 的，感觉是需要接口修改依赖下的 babel 配置，比如 api.modifyBabelOptsForDeps 。 @yingzhiji 要不要考虑加一个？

**Comment by yingzhiji** [comment]
@sorrycc 如果要加的话该怎么设计呢？是不是也需要一个 api.modifyAllBabelOpts，不然可能相同的配置要写两遍

**Comment by sorrycc** [comment]
我觉得加一个 api.modifyBabelOptsForDeps 就好了，依赖通常不走 babel 编译，这是第一个需求。

**Comment by youngjuning** [comment]
我现在编辑 babel.config.js 可以编译 node_modules 

![image](https://user-images.githubusercontent.com/13204332/104012087-2b903400-51ea-11eb-9976-29a5ca892952.png)

配置 extraBabelPresets 不可以

![image](https://user-images.githubusercontent.com/13204332/104012129-419df480-51ea-11eb-9dd8-f1605baac822.png)


我是想把 react-native 相关的 babel 配置写到插件里，有什么办法吗现在 @sorrycc

**Comment by sorrycc** [comment]
配 @babel/preset-flow 就够了，另外两个内置了。

**Comment by sorrycc** [comment]
有需要再 reopen。

**Comment by jiyingzhi** [comment]
@sorrycc 我现在就遇到了这个问题，我的项目是monorepo，有一个common目录，这个common目录被视为node_modules里的模块，由于common里有TS和JSX的代码，但是Umi默认不编译node_modules里的TS和JSX，配置extraBabelPresets也不会对node_modules里的模块生效

**Comment by jiyingzhi** [comment]
试了 extraBabelIncludes 也不行

**Comment by youngjuning** [comment]
> @sorrycc 我现在就遇到了这个问题，我的项目是monorepo，有一个common目录，这个common目录被视为node_modules里的模块，由于common里有TS和JSX的代码，但是Umi默认不编译node_modules里的TS和JSX，配置extraBabelPresets也不会对node_modules里的模块生效

https://github.com/umijs/umi/issues/5914#issuecomment-756714305
