### ISSUE TITLE
[Feature Request] 动态修改base路径

### ISSUE THREAD

**Issue by smilehht** [umijs/umi#5915]
## Background

一个项目中包含不同业务的数据，url中通过加上business来区分业务，页面跳转时需要加上business，能否在运行时改变base，跳转时只需要关心非business路径即可。

## Proposal

支持动态修改base路径

**Comment by sorrycc** [comment]
不支持动态修改 base 路径，也没有计划，这个需求比较奇怪。

**Comment by wefiy** [comment]
不奇怪啊，应用的上下文有时候部署的时候不是固定的

**Comment by smilehht** [comment]
可以通过设置window.routerBase = 'xxx'来动态改变base路由

**Comment by justable** [comment]
@sorrycc qiankun的子应用就需要运行时判断 base 路径：`<BrowserRouter basename={window.__POWERED_BY_QIANKUN__ ? '/app-react' : '/'}>`，基于 umi 这部分配置都被框架收敛了，没法操作。。

**Comment by LOWINC** [comment]
> @sorrycc qiankun的子应用就需要运行时判断 base 路径：`<BrowserRouter basename={window.__POWERED_BY_QIANKUN__ ? '/app-react' : '/'}>`，umi 把这部分配置收敛了，没法操作。。

我也遇到这个问题了。。。。 umi项目 作为子应用应该怎么配置base？

**Comment by windyzoe** [comment]
reopen?qiankun没法用直接凉凉了

**Comment by transtone** [comment]
> 可以通过设置window.routerBase = 'xxx'来动态改变base路由

这个方法需要启用 `runtimehistory` https://umijs.org/zh-CN/config#runtimehistory
 
可以把 `public-path.js` 文件改写一下：
```js
if (window.__POWERED_BY_QIANKUN__) {
  // eslint-disable-next-line no-undef
  __webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__;
} else {
  window.routerBase = '/非乾坤路由-base-xxx/'
}
```

**Comment by wsz7777** [comment]
强烈reopen

**Comment by wsz7777** [comment]
@sorrycc 动态改base是迁移成本最低的方式了

**Comment by zhanghsoft** [comment]
最后咋解决的 在用微前端也遇到了

**Comment by smilehht** [comment]
> 最后咋解决的 在用微前端也遇到了

window.routerBase = 'xxx'来动态改变base路由

**Comment by poapoc** [comment]
我是在qiankun的子应用里面用到了，用的框架是umi
1 配置开启runtimeHistory，在配置里面加上runtimeHistory: {},
`export default defineConfig({
  runtimeHistory: {},
})`
2 在app.tsx里面设置basename

`
import { setLocale, setCreateHistoryOptions } from 'umi';
setCreateHistoryOptions({
    basename: pathPrefix,//你要设置的前缀
});
`

**Comment by Clown-W** [comment]
父子应用都是umi  父应用配置了base之后  子应用的路由就访问不到了

**Comment by HeeBooo** [comment]
> runtimeHistory

解决了，谢谢

**Comment by gaofei019** [comment]
> 我是在qiankun的子应用里面用到了，用的框架是umi 1 配置开启runtimeHistory
> 
> ```
> export default defineConfig({
>   runtimeHistory: {},
> })
> ```
> 
> 2 在app.tsx里面设置basename
> 
> ```
> import { setLocale, setCreateHistoryOptions } from 'umi';
> setCreateHistoryOptions({
>     basename: pathPrefix,//你要设置的前缀
> });
> ```

用的第几版本的umi

**Comment by cuijiudai** [comment]
> 父子应用都是umi 父应用配置了base之后 子应用的路由就访问不到了

我也遇到了

**Comment by ziqiya** [comment]
umi4 不支持修改 basename，子应用只能修改config里的base和publicPath，再改nginx配置

**Comment by balabll** [comment]
> umi4 不支持修改 basename，子应用只能修改config里的base和publicPath，再改nginx配置

@ziqiya 请问Nginx部分是如何配置的

**Comment by Jiyr0119** [comment]
> 

解决了么 真的秀 升级个版本 升的微前端不好用了 动态修改base 这么平常的一个需求

**Comment by twinkle77** [comment]
同，动态修改  base 路径真的是个必要需求

**Comment by warjiang** [comment]
> feat: support dynamically modify the base path #9811

umi也太拉了，准备弃疗了

**Comment by twinkle77** [comment]
@warjiang 

```typescript
export const qiankun = {
  async mount(props) {
    // 微前端依赖
    if (window.__POWERED_BY_QIANKUN__ && props) {
      props.base = '/cl'
    }
  }
}
```

通过这种方式改子应用的 base 可以

**Comment by HJM515** [comment]
> @warjiang
> 
> ```ts
> export const qiankun = {
>   async mount(props) {
>     // 微前端依赖
>     if (window.__POWERED_BY_QIANKUN__ && props) {
>       props.base = '/cl'
>     }
>   }
> }
> ```
> 
> 通过这种方式改子应用的 base 可以

试了一下，真的可以，厉害！

**Comment by Malarkey-Jhu** [comment]
umi4裡不支持动态修改 base 路径呀ＱＱ
