### ISSUE TITLE
IE下会报SCRIPT1014: 无效字符

### ISSUE THREAD

**Issue by skaier** [umijs/umi#5918]
![image](https://user-images.githubusercontent.com/19259682/103524358-63c90700-4eb8-11eb-9aad-57710f58c1a7.png)

ie打开会报错，无法进入网站，官方文档预览网站也是无法打开。

**Comment by skaier** [comment]
抱歉 提错地方了 应该是去antdesignpro

**Comment by CR7-yi** [comment]
@skaier 问题解决了吗，是怎么弄得

**Comment by FlavourSh4T** [comment]
@skaier 我也遇到这个问题了，请问你是怎么解决的

**Comment by jayguojianhai** [comment]
@skaier 我也遇到了，请问问题解决了吗？
