### ISSUE TITLE
开启了immer以后如何直接返回新的state

### ISSUE THREAD

**Issue by suiyi8760** [umijs/umi#592]
参照immer文档这样写似乎不行，组件中接收到的state是空的:
```
reducers: {
    setInfo(state, { payload }) {
      return payload;
    }
  }
```
或这样也不行
```
reducers: {
    setInfo(state, { payload }) {
      state = payload;
    }
  }
```
难道只能`state.xxx=payload.xxx`这样用吗

**Comment by sorrycc** [comment]
dva-immer 用 0.2.0，兼容老的 reducer 返回方式的。

**Comment by sorrycc** [comment]
你是用 umi-plugin-dva + immer 的方式？

**Comment by suiyi8760** [comment]
是的，刚更新了umi-plugin-dva和umi到最新版本，但问题还存在

**Comment by sorrycc** [comment]
更新到 [umi-plugin-dva@0.9.0](https://github.com/umijs/umi/releases/tag/umi-plugin-dva%400.9.0) 试试。

**Comment by suiyi8760** [comment]
@sorrycc thx.可以了

**Comment by superlbr** [comment]
目测dva-immer不兼容老的 reducer 返回方式，要改得一起改。。。

**Comment by sorrycc** [comment]
@superlbr 兼容的，我们有项目在用。

**Comment by superlbr** [comment]
还有假设原state[index]['children'] = []
```
changeStockItem(state, { payload }) {
    const { index, key, value } = payload
    state[index]['children'] = [1,2,3]
}
```
这样也会报错，提示children属性只读
