### ISSUE TITLE
windows 环境下开启 exportStatic 打包方案

### ISSUE THREAD

**Issue by xrkffgg** [umijs/umi#5921]
地址：https://github.com/xrkffgg/umi-win-exportStatic

### 现象描述

当 config 设置 exportStatic 时，windows 环境下 docs:build 会出现如下问题

`~demos\:uuid`

![](https://github.com/xrkffgg/umi-win-exportStatic/blob/main/public/error.png?raw=true)

- 原因为：现不支持 windows 动态路由。Mac、Linux 下正常。

### 解决方案

1. `.gitignore`
去掉或注释 doc 打包生成路径 /docs-dist

2. 复制 `.github/workflows/build.yml`
在自己的项目中新建 Actions，内容可复制该项目内容。

3. 提交代码触发 Actions
4. 系统自动打包并提交代码
5. 下载最新代码，获取打包后结果

**Comment by xrkffgg** [comment]
ref:
https://github.com/umijs/umi/issues/5633
https://github.com/umijs/umi/issues/5446

**Comment by sorrycc** [comment]
exportStatic 不支持动态路由，可以想一下，就算能生成，访问之后刷一下也是访问不到的，这个流程串不通。

**Comment by 97Yates05** [comment]
这严格意义不算解决办法吧。。上传到github打包，再下载，还如直接上传到服务器，交给服务器打包
