### ISSUE TITLE
[Bug] getSaga.js:194 Uncaught (in promise) {preventDefault: ƒ}

### ISSUE THREAD

**Issue by promotion-xu** [umijs/umi#5922]
## What happens?
当我切换Tab时，控制台报错getSaga.js:194 Uncaught (in promise) {preventDefault: ƒ}, 页面显示空白

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 2.4.4
- **Node Version**: 12.16.3
- **Platform**: macOs

**Comment by sorrycc** [comment]
没有复现步骤，帮不了你。
