### ISSUE TITLE
preact打包体积

### ISSUE THREAD

**Issue by jpdan** [umijs/umi#5923]
umi@3.3.3
@umijs/plugin-preact@1.0.1
手动引入一部分polyfill，
![image](https://user-images.githubusercontent.com/3361732/103619274-65ec9d80-4f6c-11eb-9249-e988fa2136ff.png)
打包出来umi.js有200K，也没有使用useHistory等涉及到react-router-dom包的，请问怎样缩小打包体积？

**Comment by sorrycc** [comment]
加 ANALYZE=1 环境变量分析下。

**Comment by sorrycc** [comment]
加 ANALYZE=1 环境变量分析下。

**Comment by jpdan** [comment]
![image](https://user-images.githubusercontent.com/3361732/103720184-bf54db00-5005-11eb-83bd-357f437b18f7.png)
@sorrycc 没有使用路由系统，只是一个个单独的单页面，为啥还打包进去了？
