### ISSUE TITLE
public下的html文件如何访问

### ISSUE THREAD

**Issue by SmartWrh** [umijs/umi#5927]
在public下有文件夹`A`，`A`下面有一个`B`，`B`中有一个静态html，打包后如何匹配访问

打包后通过 `path\A\B\C.html` 可以访问到该静态资源，但是变成 `path\A\B\C.html?params=xxx` 就匹配不到了，请问该如何修改呢

**Comment by sorrycc** [comment]
打包后如何访问不是 umi 范围了。
