### ISSUE TITLE
[Feature Request] 是否有配置可以去掉copied to clipboard吗？

### ISSUE THREAD

**Issue by 104gogo** [umijs/umi#5928]
经常会遇到粘贴板里面的内容，变成了http://localhost:8000
感觉很无语，结果发现是项目启动了之后，umi自动帮我们做了这件事件，有配置可以去掉这个吗？挺烦的。
![image](https://user-images.githubusercontent.com/8522646/103755267-8853e900-5048-11eb-8a60-2b646e90927f.png)

**Comment by sorrycc** [comment]
不能配置去掉，你可能需要一个粘贴板管理工具，推荐 Paste。

**Comment by 104gogo** [comment]
好的，我试试
