### ISSUE TITLE
[Feature Request] How to use babel-plugin-import-glob for glob pattern

### ISSUE THREAD

**Issue by felix-cao** [umijs/umi#5930]
## Background

[babel-plugin-import-glob](https://www.npmjs.com/package/babel-plugin-import-glob)

- Install babel-plugin-import-glob
```bash
yarn add -D babel-plugin-import-glob
```
- But invalid
```bash
import * as Areas from './areas/**/planner-element.jsx';
```

![image](https://user-images.githubusercontent.com/8563874/103845953-1cb95c80-50d8-11eb-875d-e39405563064.png)

**Comment by sorrycc** [comment]
https://umijs.org/config#extrababelplugins

**Comment by felix-cao** [comment]
@sorrycc 
Thanks very much, you are a man of knowlage!
