### ISSUE TITLE
[Bug] create umi选择ant-design-pro JavaScript之后，eslint通不过

### ISSUE THREAD

**Issue by heran** [umijs/umi#5931]
> tyarn create umi
> 选择 ant-design-pro Pro V4 JavaScript complete
> tyarn install
>  .\node_modules\.bin\eslint .\src\pages\Welcome.jsx

>   1:8   error  'React' is defined but never used                 no-unused-vars
>   2:10  error  'PageContainer' is defined but never used         no-unused-vars
>   3:10  error  'Card' is defined but never used                  no-unused-vars
>   3:16  error  'Alert' is defined but never used                 no-unused-vars
>   3:23  error  'Typography' is defined but never used            no-unused-vars
>   4:19  error  'FormattedMessage' is defined but never used      no-unused-vars
>   7:7   error  'CodePreview' is assigned a value but never used  no-unused-vars

✖ 7 problems (7 errors, 0 warnings)

- **Umi 版本**：umi@3.3.3
- **Node 版本**：v12.18.0
- **操作系统**：windows 10

**Comment by hejun200613224** [comment]
I have got a same issue, watching for a latest fix now.

**Comment by sorrycc** [comment]
lint 优先级低，有兴趣修改可以直接发 PR。

**Comment by YoursOwen** [comment]
> lint 优先级低，有兴趣修改可以直接发 PR。

请问如何修复呢？

**Comment by iloveip** [comment]
I have the same issue.
