### ISSUE TITLE
[Bug] publicPath 或 base 并未对 devServer 生效

### ISSUE THREAD

**Issue by Witee** [umijs/umi#5932]
## What happens?

配置文件中增加 `base` 和 `publicPath` 设置后没有对 `/dev-server/`  路径生效, 请求的还是 `https://域名/dev-server/info?t=1610005672872`

希望可以访问如下路径: 
`https://域名/${publicPath}/dev-server/info?t=1610005672872` 
或
`https://域名/${base}/dev-server/info?t=1610005672872` 

## Context

- **Umi Version**: 3.3.3
- **Node Version**: 10.16
- **Platform**: macOS 10.15

**Comment by sorrycc** [comment]
BY DESIGN。base 是有效的，但是访问 `/` 同样有效；publicPath 在 dev 阶段写死的 `/`。

**Comment by njleonzhang** [comment]
@sorrycc by design 的话，是不是应该改下文档。读来读去都是支持 devServer 单独配置的。
![截屏2021-03-29 上午11 30 10](https://user-images.githubusercontent.com/13174059/112783544-22dd2a80-9082-11eb-9139-3d4529866f49.png)

**Comment by KingPengZero** [comment]
解决了吗，我也遇到这个问题了

**Comment by WuBin88996** [comment]
请问这个问题你们解决了吗
