### ISSUE TITLE
[Feature Request] 动态导入必须要打开dynamicImport吗？我关闭它在其他地方写的动态导入没打包成单独的chunk

### ISSUE THREAD

**Issue by zry754331875** [umijs/umi#5933]
## Background

umi3
## Proposal

因为开启dynamicImport会将我的page变成动态导入，但是我只想将page下引用的某个模块变成动态导入

**Comment by Indomi** [comment]
我也想要这种目的，但是发现全局dynamicImport，甚至导致初始加载loading会闪现到dynamicImport里设置的loading，非常不友好

**Comment by sorrycc** [comment]
可以先加个项目插件实现，

```js
api.modifyBabelPresetOpts(opts => {
    return {
      ...opts,
      dynamicImportNode: false,
    };
  });
```
