### ISSUE TITLE
[Bug] umi3使用@alitajs/hd启动报错

### ISSUE THREAD

**Issue by a3538333** [umijs/umi#5936]
我参照umi的issues对hd的解决方案，新构建了umi3的项目，然后yarn add @alitajs/hd --save了这个插件，按照实例在umirc.js里面配置了
plugins: ['@alitajs/hd'], hd:{},
启动的时候报错

node_modules/@alitajs/hd/lib/index.js: Cannot read property 'getFile' of undefined (47, 29)

请问该怎么处理啊

还有能问一下为什么umi3取消了hd方案吗，是否是因为有更好的方案能替代hd

**Comment by xiaohuoni** [comment]
尝试了一下，不存在你说的这个问题。你提供个demo吧

**Comment by sorrycc** [comment]
无复现，CLOSE。

**Comment by a3538333** [comment]
我是使用的yarn create umi 选的umi-app，看来是创建的问题，现在解决了，应该用yarn create @umijs/umi-app创建才可以
