### ISSUE TITLE
antd pro打包部署后主题用不了是怎么肥事？依赖包umi-plugin-antd-theme没生效？[Bug] say something

### ISSUE THREAD

**Issue by xiaofeizhu1002664427** [umijs/umi#5941]
## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
无复现，Close。
