### ISSUE TITLE
[Bug] 运行时调用patchRoutes，如果使用push在路由数组中添加新的路由，新增的路由无法跳转，页面404

### ISSUE THREAD

**Issue by 2018Cool** [umijs/umi#5943]
## What happens?

patchRoutes(routes )
修改路由。

比如在最前面添加一个 /foo 路由，

export function patchRoutes(routes) {
  routes.push({
    path: '/foo',
    exact: true,
    component: require('@/extraRoutes/foo').default,
  });
}
在app.js中使用上面的方式动态添加路由，页面会报404，使用routes.unshift添加路由正常
## 相关环境信息

- **Umi 版本**：^2.8.7
- **Node 版本**：v12.18.3
- **操作系统**：MacOS

**Comment by sorrycc** [comment]
理解下路由的匹配规则就能知道原因了，先匹配了 `/` 路由，然后进去后又匹配了 `/` 子路由里的 404 fallback 路由，所以 404 。
