### ISSUE TITLE
 通过api.modifyHTML注入的inline scirpt代码被强行format了

### ISSUE THREAD

**Issue by KMBaby-zyl** [umijs/umi#5944]
https://github.com/umijs/umi/blob/2de577ed78c2df2a2a16933e97b77920366fcf6c/packages/core/src/Html/Html.ts#L211

问题：
通过api.modifyHTML引入了第三方库的inline scirpt被强行format会导致html文件变大，html可读性降低。

希望format能支持开关

**Comment by sorrycc** [comment]
加一行 `<!-- prettier-ignore -->`。
