### ISSUE TITLE
[Bug] 无法固定端口号

### ISSUE THREAD

**Issue by s97712** [umijs/umi#5945]
## What happens?
通过　`cross-env PORT=8000 umi dev`　启动还是无法固定端口号，经常使用8001端口，8000端口非常确定没有占用，也没有重复启动。

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by ycjcl868** [comment]
`PORT=8005 yarn start` 没问题

![image](https://user-images.githubusercontent.com/13595509/104088423-b9d0de00-521b-11eb-80d8-e4e6f0838bef.png)

**Comment by s97712** [comment]
> `PORT=8005 yarn start` 没问题
> 
> ![image](https://user-images.githubusercontent.com/13595509/104088423-b9d0de00-521b-11eb-80d8-e4e6f0838bef.png)

随机出现，有时8000有时8001 我的问题是需要固定端口，不要端口变来变去的。

**Comment by TonyMistark** [comment]
@xiaohuoni  close也没个备注提示

**Comment by xiaohuoni** [comment]
@TonyMistark 上面的是正解，没有复现都会被 close
