### ISSUE TITLE
在 onRouteChange 里面怎么使用 hooks 修改 model?

### ISSUE THREAD

**Issue by GreatAuk** [umijs/umi#5972]
## What happens?

我想知道的是在 [`onRouteChange`](https://umijs.org/zh-CN/docs/runtime-config#onroutechange-routes-matchedroutes-location-action-) 里面怎么使用 `hooks` 修改` model`。
![image](https://user-images.githubusercontent.com/20253809/104142455-a6c63580-53f6-11eb-9131-1e690c4915e0.png)

目前项目里完全使用`@umijs/plugin-model`做为数据管理方案，所以这个限制还是挺麻烦的。还是有在非组件，或非 `hooks function` 里使用 `hooks` 修改 `model` 的场景的。

**Comment by williamnie** [comment]
为啥要在这里改变model数据，model数据应该在页面内改动，plugin-model就是一个没有render的hooks，这里肯定不能使用，数据在前一个页面的useEffect里的return函数里改不就行了
