### ISSUE TITLE
[Bug] 添加HTML模板document.ejs后，移动端宽度出现问题，固定980px

### ISSUE THREAD

**Issue by scxslsh** [umijs/umi#5973]
## What happens?
项目添加document.ejs 后，在手机或者浏览器mobile调试时，网页的宽度固定为980px

## 最小可复现仓库
[https://github.com/scxslsh/umijs-html-template-demo](https://github.com/scxslsh/umijs-html-template-demo)
#### 添加document.ejs 之前
![image](https://user-images.githubusercontent.com/30258511/104143808-efccb880-53fb-11eb-90a7-e7536060f272.png)
#### 添加document.ejs 之后，开启移动端调试
![image](https://user-images.githubusercontent.com/30258511/104144030-cbbda700-53fc-11eb-822f-f51fc0c2d4f3.png)

#### 添加document.ejs 之后。通过鼠标缩小屏幕，没有问题
![image](https://user-images.githubusercontent.com/30258511/104144149-10494280-53fd-11eb-895e-28e633000c84.png)

## 相关环境信息

- **Umi **：3.3.4
- **Node 版本**：14.8.0
- **操作系统**：mac

**Comment by sorrycc** [comment]
对比和 https://github.com/umijs/umi/blob/master/packages/core/src/Html/document.ejs 的差异，就会发现少了啥了。

**Comment by scxslsh** [comment]
> 对比和 https://github.com/umijs/umi/blob/master/packages/core/src/Html/document.ejs 的差异，就会发现少了啥了。

直接copy的umi文档上面的内容， 草率了
