### ISSUE TITLE
[Bug] 配置了locale插件之后，会在页面中显示locale的key没有

### ISSUE THREAD

**Issue by iProgramme** [umijs/umi#5977]
devScripts.js:5836 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `SelectLang`. See https://reactjs.org/link/warning-keys for more information.

会报上面的错误，排查发现是defaultLangUConfig中的每一项没有key而下面循环的 Menu.Item 里面却用的是 localeObj.key 。

解决方案：建议把  localeObj.key 改成 localeObj.lang  或者其他的唯一值就好了

**Comment by sorrycc** [comment]
在 #5974 跟进。
