### ISSUE TITLE
[Bug][SSR] headScripts 中包括单引号会导致 require umi.server.js 失败

### ISSUE THREAD

**Issue by Baoyx007** [umijs/umi#5980]
## What happens?

在 umi 的 headScripts 中增加的包括单引号的 script:
```js
headScripts: [`console.log('zzz')`]
```
会导致 umi.server.js 被 require 异常:
```
Uncaught SyntaxError: Invalid or unexpected token
```

原因是:

 https://github.com/umijs/umi/blob/1668478c7df3fc4882fd1f460787d3773f2193be/packages/preset-built-in/src/plugins/features/ssr/templates/server.tpl#L43 

在代码中中的 `DEFAULT_HTML_PLACEHOLDER` 没有将 headScripts 中的单引号 escape

## 相关环境信息

- **Umi 版本**：3.3.3
- **Node 版本**：12.20.1
- **操作系统**：macos

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/105569258-1d1b3f80-5cf5-11eb-8b94-bedf039af919.png)

没复现

**Comment by ycjcl868** [comment]
虽然没复现，html 还是 serialize 下吧，放心
