### ISSUE TITLE
[dva] call 两个接口，只有一个请求发出去了。控制台。报错 "{}", -- index.js :1

### ISSUE THREAD

**Issue by promotion-xu** [umijs/umi#5981]
## What happens?
umi项目dispatch 两个effects, effect触发了两次，但是call 接口时，只有一个发出去了，控制台报错 "{}", -- index.js :1

## Mini Showcase Repository(REQUIRED)
![image](https://user-images.githubusercontent.com/36992764/104422820-35ce7b80-55b8-11eb-9522-f2592f75758c.png)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version*2.4.4*:
- **Node Version*10.12.0*:
- **Platform*macOS*:

**Comment by itellyou-com** [comment]
猜测应该是你代码逻辑问题，最好提供一个重现实例或者贴出代码看看
