### ISSUE TITLE
[Bug] 浏览器报错 Expected server HTML to contain a matching <a> in <div>

### ISSUE THREAD

**Issue by RuoFeng2015** [umijs/umi#5983]
![image](https://user-images.githubusercontent.com/41161634/104458779-c4f28800-55e6-11eb-9270-4b63100ca71a.png)

![image](https://user-images.githubusercontent.com/41161634/104459053-2f0b2d00-55e7-11eb-8ed9-24561b78c642.png)

## 相关环境信息

- **Umi 版本**：3.3.3
- **Node 版本**：12
- **操作系统**：window

**Comment by itellyou-com** [comment]
用了ssr，这只是一个警告，你服务端渲染的内容和浏览器客户端渲染出来的内容不一致

**Comment by RuoFeng2015** [comment]
> 用了ssr，这只是一个警告，你服务端呈现的内容和浏览器客户端渲染出来的内容无关
请问这个有解决的方案吗

**Comment by Jay-G2017** [comment]
渲染的内容里是不是有条件判断,　导致服务端和客户端渲染出来的内容不一致?  可以把条件判断放在useEffect里试试. 
这个链接是next.js里的一个讨论. https://github.com/vercel/next.js/discussions/17443?sort=top

**Comment by ycjcl868** [comment]
用 state 控制
