### ISSUE TITLE
[Feature Request] umi@2 的依赖问题

### ISSUE THREAD

**Issue by keenwon** [umijs/umi#5985]
## Background

umi@2 将 umi-build-dev 作为 `dependencies`，umi-build-dev 依赖的 eslint、eslint plugins 等，会和我们公司内部的工具产生冲突

## Proposal

umi-build-dev 改为 devDependencies

## Additional context

```
└─┬ umi@2.13.16
  └─┬ umi-build-dev@1.18.7
    ├─┬ af-webpack@1.14.9
    │ └── UNMET PEER DEPENDENCY eslint@5.16.0
    └─┬ sylvanas@0.4.4
      ├─┬ @umijs/fabric@2.4.11
      │ └── UNMET PEER DEPENDENCY eslint@7.17.0  deduped
      └── UNMET PEER DEPENDENCY eslint@7.17.0  deduped
```

**Comment by sorrycc** [comment]
umi-build-dev 改为 devDependencies umi 就跑不起来了，只要依赖声明正常，npm 安装时会确保依赖正常存放。
