### ISSUE TITLE
[Bug] umi3.0 src/global.less 未自动引入进来

### ISSUE THREAD

**Issue by chenleyiduo** [umijs/umi#5986]
## What happens?

在global.less里面写了
![image](https://user-images.githubusercontent.com/77134659/104539418-7382e100-5658-11eb-9561-fde71159dbe4.png)但是项目中启动未能看到global.less里面写的样式

```
@import '~antd/dist/antd.compact.css';

.small-table1{
    font-size: 10px;
    :global( .ant-table.ant-table-small){
        font-size: 10px;
    }
}
.ant-table.ant-table-small{
    font-size: 10px;
}
```

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## 相关环境信息

- **Umi 版本**：3.x
- **Node 版本**：12.x.x
- **操作系统**：windows

**Comment by sorrycc** [comment]
重启后有效吗？`umi g tmp` 看下 src/.umi/umi.ts 里有没有 global.less 的引用。

**Comment by chenleyiduo** [comment]
> 重启后有效吗？`umi g tmp` 看下 src/.umi/umi.ts 里有没有 global.less 的引用。

umi.ts里面有global.less的引用

**Comment by sorrycc** [comment]
那就是有效的，可以试着调高优先级，另外 compat 可通过 antd 配置实现，参考 https://umijs.org/zh-CN/plugins/plugin-antd#compact

**Comment by chenleyiduo** [comment]
> 那就是有效的，可以试着调高优先级，另外 compat 可通过 antd 配置实现，参考 https://umijs.org/zh-CN/plugins/plugin-antd#compact

增加了!important就可以了，但是想问下在没有增加!important的时候在浏览器的style中为什么不可见覆盖的样式？就算被划掉了，至少是可见的

我尝试过用配置的方式使用compat，下载@umijs/plugin-antd后启动就会报如下错误

```
D:\ReactWorkspace\iam_v1_uims_iam-web-project\iam-web-frontend>npm run start

> @ start D:\ReactWorkspace\iam_v1_uims_iam-web-project\iam-web-frontend
> umi dev

plugin @umijs/plugin-antd is already registered by D:/ReactWorkspace/iam_v1_uims_iam-web-project/iam-web-frontend/node_modules/@umijs/plugin-antd/lib/index.js, plugin from D:/ReactWorkspace/iam_v1_uims_iam-web-project/iam-web-frontend/node_modules/@umijs/plugin-antd/lib/index.js register failed.
Error: plugin @umijs/plugin-antd is already registered by D:/ReactWorkspace/iam_v1_uims_iam-web-project/iam-web-frontend/node_modules/@umijs/plugin-antd/lib/index.js, plugin from D:/ReactWorkspace/iam_v1_uims_iam-web-project/iam-web-frontend/node_modules/@umijs/plugin-antd/lib/index.js register failed.
    at Service.registerPlugin (D:\ReactWorkspace\iam_v1_uims_iam-web-project\iam-web-frontend\node_modules\@umijs\core\lib\Service\Service.js:457:13)
    at D:\ReactWorkspace\iam_v1_uims_iam-web-project\iam-web-frontend\node_modules\@umijs\core\lib\Service\Service.js:436:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\ReactWorkspace\iam_v1_uims_iam-web-project\iam-web-frontend\node_modules\@umijs\core\lib\Service\Service.js:108:103)
    at _next (D:\ReactWorkspace\iam_v1_uims_iam-web-project\iam-web-frontend\node_modules\@umijs\core\lib\Service\Service.js:110:194)
    at D:\ReactWorkspace\iam_v1_uims_iam-web-project\iam-web-frontend\node_modules\@umijs\core\lib\Service\Service.js:110:364
    at new Promise (<anonymous>)
    at D:\ReactWorkspace\iam_v1_uims_iam-web-project\iam-web-frontend\node_modules\@umijs\core\lib\Service\Service.js:110:97
    at Service.initPlugin (D:\ReactWorkspace\iam_v1_uims_iam-web-project\iam-web-frontend\node_modules\@umijs\core\lib\Service\Service.js:442:7)
    at D:\ReactWorkspace\iam_v1_uims_iam-web-project\iam-web-frontend\node_modules\@umijs\core\lib\Service\Service.js:317:22
```

**Comment by sorrycc** [comment]
> plugin @umijs/plugin-antd is already registered by D:/ReactWorkspace/iam_v1_uims_iam-web-project/iam-web-frontend/node_modules/@umijs/plugin-antd/lib/index.js, plugin from D:/ReactWorkspace/iam_v1_uims_iam-web-project/iam-web-frontend/node_modules/@umijs/plugin-antd/lib/index.js register failed.

这是注册的问题，依赖里不要重复包含 @umijs/plugin-antd 就好。

> 增加了!important就可以了，但是想问下在没有增加!important的时候在浏览器的style中为什么不可见覆盖的样式？就算被划掉了，至少是可见的

调试问题，chrome dev tool 里应该有。

**Comment by WLyKan** [comment]
打包后，global.less的样式在被antdpro的样式覆盖了 
![image](https://user-images.githubusercontent.com/2155093/116508363-c45ed280-a8f3-11eb-857a-0e040413a58b.png)

**Comment by poapoc** [comment]
> 打包后，global.less的样式是在umi.css中， 在被antdpro的basiclayout样式覆盖了。但是开发环境正常 ![image](https://user-images.githubusercontent.com/2155093/116508427-f1ab8080-a8f3-11eb-8395-97e416ba78cf.png)

所以这个要怎么解决？

**Comment by justLearner** [comment]
所以现在这个问题有解决方法了吗？@poapoc
