### ISSUE TITLE
[Help] Umi@2作为qiankun的子应用

### ISSUE THREAD

**Issue by yuki070** [umijs/umi#5987]
## What happens?

请问一个Umi@2的项目，如果作为qiankun的子应用，应该从哪里把bootstrap、mount、unmount导出？

尝试了在`src/app.js`中导出

```js
export async function bootstrap() {
  console.log('bright bootstrap...');
}

export async function mount(props) {
  console.log('bright mount...', props);
}

export async function unmount(props) {
  console.log('bright unmount...', props);
}
```

但跑起来会报如下的错误

![image](https://user-images.githubusercontent.com/656768/104541513-b6df4e80-565c-11eb-847a-05487408cc13.png)

## 相关环境信息

- **Umi 版本**：^2.12.1
- **Node 版本**：v14.15.1
- **操作系统**：Windows

**Comment by sorrycc** [comment]
用错了吧，应该没有文档是要求写在 app.ts 的。问题咨询请到 https://github.com/umijs/umi/discussions 。
