### ISSUE TITLE
umi 在Windows下运行，DvaContainer.js 文件出现bug

### ISSUE THREAD

**Issue by dengsibao** [umijs/umi#599]
![image](https://user-images.githubusercontent.com/6688116/41073623-ba9ab7ae-6a36-11e8-86c8-a668ab9d0c41.png)
npm start 之后找不到目录文件

**Comment by sorrycc** [comment]
试试最新版的 umi-plugin-dva，我看源码是加在 winPath 的处理的，有问题再 reopen 。
