### ISSUE TITLE
[Bug] 官方API好像没有提供动态路由传参方式

### ISSUE THREAD

**Issue by chenleyiduo** [umijs/umi#5992]
****

## What happens?

从列表跳入详情，需要路由动态传参，查看了官方文档并没给出路由传参的方式，比较困惑

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub
> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.x
- **Node Version**:12.x
- **Platform**:windows

**Comment by williamnie** [comment]
从/page 跳转到 /page/:id 或者是/page?size=10 这种么？用history.push 就好了https://umijs.org/zh-CN/api#history

**Comment by chenleyiduo** [comment]
> 从/page 跳转到 /page/:id 或者是/page?size=10 这种么？用history.push 就好了https://umijs.org/zh-CN/api#history

已经解决了
