### ISSUE TITLE
[Bug] Umi@2使用插件@umijs/plugin-qiankun报错

### ISSUE THREAD

**Issue by yuki070** [umijs/umi#5993]
## What happens?

在Umi@2的项目里，使用`@umijs/plugin-qiankun`插件，插件的配置如下：

![image](https://user-images.githubusercontent.com/656768/104568557-33892180-568b-11eb-9e46-0749fef8883f.png)

但启动时会报如下的错误：

![image](https://user-images.githubusercontent.com/656768/104568628-4865b500-568b-11eb-8a27-30ed262795e1.png)

## Context

- **Umi Version**: ^2.12.1
- **Node Version**: v14.15.1
- **Platform**: Windows

**Comment by sorrycc** [comment]
Umi 2 的 qiankun 插件是 umi-plugin-qiankun，不是 @umijs/plugin-qiankun。

**Comment by yuki070** [comment]
> Umi 2 的 qiankun 插件是 umi-plugin-qiankun，不是 @umijs/plugin-qiankun。

没有这样一个插件呢。

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/104838552-9b8f7000-58f6-11eb-866e-dd857fce6f6e.png)
