### ISSUE TITLE
umi 支持 .eslintignore 配置吗？

### ISSUE THREAD

**Issue by Spaceman007** [umijs/umi#600]
希望 eslint 对指定文件不作代码检查，配置 .eslintignore 好像无效。

**Comment by dkvirus** [comment]
这玩意跟 umi 有什么关系，你只要用了 eslint，这个配置文件就有用的。

**Comment by mastercbhw** [comment]
.eslintignore配置是生效的，挡在项目根目录下。如果不生效你检查下是不是你语法有问题

**Comment by xlei1123** [comment]
这个问题最终是怎么解决的呢？
