### ISSUE TITLE
[Bug] ssr 预渲染构建后浏览器访问空白

### ISSUE THREAD

**Issue by helvenk** [umijs/umi#6001]
ssr构建后，用 `serve` 来本地部署，访问时先正常渲染出页面，再变成空白。

查看 F12 工具发现响应的 html 是正确的，确实做到了 ssr，但是在执行 js 后将页面替换为空白了。

调试代码发现 build 后的 umi.js 文件中存在路由映射，可能是这个原因导致的。

```js
[{ path:"/test.html", hideInMenu:!0, component: n("IRZr").default, exact:!0 }]
```
访问路径 /test.html 会正常渲染，但实际访问路径是 /test，似乎是没有匹配到对应组件，React 渲染 root 为空白。

上面是加了 `htmlSuffix: true` 后的效果，path 会自动加上 .html 后缀，导致不能正确渲染，似乎可以接受。

但现在的场景是静态文件会被放到服务器上，可能增加某些前缀，比如 /a/b/c/test，这样就永远匹配不上了，导致上述的 bug 出现。

希望给个解决方案。

umi 版本是 3.2，ssr 相关配置如下：
```js
{    
    dva: false,
    locale: false,
    dynamicImport: false,
    ssr: {},
    esbuild: false,
    model: false,
    initialState: false,
    publicPath: '/',
    outputPath: 'dist',
    exportStatic: {
      dynamicRoot: true,
      htmlSuffix: true,
    },
}
```
路由随便写都行
```js
{ path: 'test', component: './Test' }
```

**Comment by helloinfinitech** [comment]
我的umi3.3.4，htmlSuffix: true设置后，也是所有页面都访问不了，umi3带上html后缀就匹配不了了？看谁来解决下。

**Comment by ycjcl868** [comment]
> 但现在的场景是静态文件会被放到服务器上，可能增加某些前缀，比如 /a/b/c/test

这个需要配 `base`

**Comment by lkspc** [comment]
这个前缀是不固定的，不会预先告知前端，由服务端决定，可以加任意前缀，也可以不加前缀

**Comment by ycjcl868** [comment]
> 这个前缀是不固定的，不会预先告知前端，由服务端决定，可以加任意前缀，也可以不加前缀

你可以这样，服务端下发 

```js
window.serverPrefix = {{ xxxx }}
```

`.umirc.ts` 里配置

```js
scripts: [`window.routerBase = window.serverPrefix || "/"`],
```


![image](https://user-images.githubusercontent.com/13595509/105569024-efcd9200-5cf2-11eb-92de-4a646e8c8f84.png)

**Comment by lkspc** [comment]
上面的办法也没有解决问题，最后用 [mpa 配置项](https://umijs.org/zh-CN/config#mpa) 解决了。cc @helloinfinitech

**Comment by andylei18** [comment]
遇到了同样的问题，目前还是有Bug的，没有关闭

**Comment by andylei18** [comment]
@sorrycc @ycjcl868

**Comment by snowberry001** [comment]
开启mpa，是不是router的wrappers就没有作用了？
