### ISSUE TITLE
[Bug] plugin-webpack-5: Cannot read property 'intercept' of undefined

### ISSUE THREAD

**Issue by fengsx** [umijs/umi#6003]
## What happens?

When I try to use `@umijs/plugin-webpack-5`, somethings happened:

![image](https://user-images.githubusercontent.com/7709602/104696739-b2dd2a80-5749-11eb-8f4b-a5463dea097d.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub
> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/fengsx/umi-plugin-webpack-5-demo

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

```
mkdir myapp && cd myapp
yarn create @umijs/umi-app
yarn add webpack@^5.14.0
yarn add @umijs/plugin-webpack-5 
yarn start
```
## Context

- **Umi Version**:3.3.4
- **Node Version**:14.8.0
- **Platform**: Mac OS Big Sur 11.1 (20C69)

**Comment by sorrycc** [comment]
这个插件有问题，等我们找时间更新吧，也可以提 PR。

**Comment by xijin** [comment]
同遇到问题

**Comment by sorrycc** [comment]
等 @umijs/deps 接入完成会处理 webpack 5 的支持问题。

**Comment by spasalkar** [comment]
what's the solution?

**Comment by fengsx** [comment]
update to 3.4.0 or higher

在 2021年4月24日，下午7:42，tavisca-spasalkar ***@***.***> 写道：

﻿

what's the solution?

**Comment by spasalkar** [comment]
Then Hit cmd:
npm i
Link webpack :
npm link webpack
