### ISSUE TITLE
umi模块中找不到connect

### ISSUE THREAD

**Issue by viewwei** [umijs/umi#6006]
在.umirc.ts开启了dva,但是还是出现umi中找不到connect。而且我的工程是一个新工程

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create @umijs/umi-app` then upload to your GitHub
> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
先检查配置的 dva 是否为 false，是的话去掉；再执行 npx umi dva list model 看看有没有合法的 model，没有就新建一个，有 model 才会开启 dva 功能；

**Comment by viewwei** [comment]
解决了，谢谢
