### ISSUE TITLE
'"../../../../node_modules/umi/types"' has no exported member 'useIntl'

### ISSUE THREAD

**Issue by hosos** [umijs/umi#6015]
**TypeScript Error**
'"../../../../node_modules/umi/types"' has no exported member 'useIntl'.

**.umirc.ts**
```ts
import { defineConfig } from 'umi'

export default defineConfig({
  hash: true,
  locale: {
    default: 'zh-HK'
  },
  nodeModulesTransform: {
    type: 'none',
  },
  title: '做人最緊要有錢',
})

```
<img width="539" alt="Screen Shot 2021-01-17 at 4 23 35 PM" src="https://user-images.githubusercontent.com/2138598/104835290-96272b00-58e0-11eb-95c4-939305e1fd8b.png">

**Version**
umi: "^3.3.4

**Comment by hosos** [comment]
我要用 react-intl locale😭

**Comment by hosos** [comment]
真奇怪，新 create project 好像沒有問題了

**Comment by Leskur** [comment]
![image](https://user-images.githubusercontent.com/33910980/117813460-adc25f00-b295-11eb-8989-4bebb36cfd5d.png)
https://github.com/Leskur/umi-app/blob/main/src/pages/index.tsx
