### ISSUE TITLE
[Bug] nodeModulesTransform 设置了 type 为 none 没有效果

### ISSUE THREAD

**Issue by daoying007** [umijs/umi#6016]
## What happens?

nodeModulesTransform 设置了 type 为 none 希望不编译 node_modules 里的包，但是好像没有效果

## Mini Showcase Repository(REQUIRED)

https://github.com/daoying007/umi-issue-6016-showcase

## How To Reproduce

config.ts 增加如果配置：
```
nodeModulesTransform: {
    type: 'none',
    exclude: [],
  },
```

package.json里 script 的 start 设置为："cross-env UMI_ENV=dev ANALYZE=1 umi dev"

yarn start 后查看：http://127.0.0.1:8888/ 发现好像几乎所有 node_modules 都被编译了

![111](https://user-images.githubusercontent.com/39725475/104837082-50249400-58ed-11eb-8ddb-a38159bf3611.jpg)

## Context

- **Umi Version**:3.3.5
- **Node Version**:v12.14.0
- **Platform**:macOS

**Comment by sorrycc** [comment]
你对被编译的理解可能有误，nodeModulesTransform.type 为 `none` 时是不走 babel 编译（为了提升速度），webpack 还是会编译的。
