### ISSUE TITLE
静态化的场景里离开页面时如何阻止路由（浏览器的后退 点击时加二次确认）

### ISSUE THREAD

**Issue by zhanchengkun** [umijs/umi#602]
想在离开页面时做二次确认， umi 有类似 this.props.router.setRouteLeaveHook的部分？
@sorrycc

**Comment by sorrycc** [comment]
是指一个路由切换到另一个路由之前？

**Comment by zhanchengkun** [comment]
@sorrycc 是当前路由离开之前，进行判断阻止。
需求是 页面离开(卸载)时 给二次确认(阻止)  有没有什么事件或者什么机制处理

**Comment by zhanchengkun** [comment]
配置了exportStatic: { htmlSuffix: true }, 是文件静态路由，并且上述场景是 点击浏览器的后退按钮时 需要做的阻止确认。 文件路由是满足不了？

**Comment by sorrycc** [comment]
和路由配置方式无关。

**Comment by zhanchengkun** [comment]
给个思路，那umi 有类似 this.props.router.setRouteLeaveHook的部分？
