### ISSUE TITLE
[Ask] 我该如果指定 public 下的资源复制到指定的 CDN 目录里

### ISSUE THREAD

**Issue by Hnnphone** [umijs/umi#6023]
## What happens?
如题，
![image](https://user-images.githubusercontent.com/27671537/104876008-ae0ab780-5991-11eb-91e5-57d104f921bf.png)
我想针对 pubic 输出的结构做如此调整，该怎么配置？

## Context

- **Umi Version**:  v3.2.14
- **Node Version**: v12.16.0
- **Platform**: win10

**Comment by ycjcl868** [comment]
放到 `public` 目录，构建时会自动复制的 https://umijs.org/zh-CN/docs/directory-structure#public-%E7%9B%AE%E5%BD%95
