### ISSUE TITLE
 Cannot find module '@@/history' from 'node_modules/umi/lib/router.js'

### ISSUE THREAD

**Issue by catherinezhxj** [umijs/umi#6032]
When using jest, an error is reported as follows:
![image](https://user-images.githubusercontent.com/23161404/104902640-efaf5880-59b9-11eb-9c66-2e5b97333b19.png)
Find the corresponding path file as follows:
![image](https://user-images.githubusercontent.com/23161404/104902758-140b3500-59ba-11eb-9e68-31226d1f85a8.png)
How to solve this situation?

Ask for help, thanks!

**Comment by successgilli** [comment]
I am having this issue.

While running jest, I encounter this same problem

**Comment by wikimo** [comment]
Node modules is not complete installation. You can use yarn instead of npm. I use yarn solved this issue. Good luck!

**Comment by liaojunhong** [comment]
I also encountered this problem

**Comment by WangDianhang** [comment]
我也遇到了这样的问题，打包时报错"Error: Cannot find module '@@/history'", "Require stack:",

**Comment by soeasyjx** [comment]
使用 pnpm workspace 也同样遇到 这个问题
