### ISSUE TITLE
[Bug] extraPostCSSPlugins配置了postcss-px-to-viewport，但没生效

### ISSUE THREAD

**Issue by laojunpeng** [umijs/umi#6033]
extraPostCSSPlugins配置了postcss-px-to-viewport，但没生效

`  extraPostCSSPlugins: [
    require('postcss-px-to-viewport')({
      unitToConvert: 'px', 
      viewportWidth: 375, 
      unitPrecision: 3, 
    }) ],`

**Comment by youngjuning** [comment]
@laojunpeng 后来怎么样了？
