### ISSUE TITLE
[Feature Request] 单独禁用路由功能

### ISSUE THREAD

**Issue by xclw2000** [umijs/umi#6037]
和framework7集成时遇到了如下问题，framework7的入口<App>组件需要传入路由表，这样它的NavBar，Link等路由组件才会有效果，导航跳转时才会有fade的效果，但是umi自己也有路由功能，这样在根据路由创建组件时，两者就打架了。但我又很喜欢umi脚手架中的dva和webpack集成的功能，所以现在很头疼，要么放弃导航特效，要么自己实现redux和webpack打包功能。如果umi能单独把路由功能禁用掉，我把路由表传给framework7，让framework7来实现路由功能，那就太棒了。

**Comment by sorrycc** [comment]
可以试试 `mpa: {}` 配置，这个是不加路由的。

**Comment by xclw2000** [comment]
> 可以试试 `mpa: {}` 配置，这个是不加路由的。

配置完mpa后，routes要怎么配。我现在配置
```
import { defineConfig } from 'umi';
import routes from './routes';
export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  mpa: {},
  routes
});
```

![image](https://user-images.githubusercontent.com/32091566/105260655-24ddc580-5bc9-11eb-9d4f-d819d4dd18b4.png)


并且如果我在组件中使用了connect
![image](https://user-images.githubusercontent.com/32091566/105260769-56ef2780-5bc9-11eb-99b0-eaa261682a16.png)
会报这个错
`Error: Could not find "store" in the context of "Connect(Component)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(Component) in connect options.`
![image](https://user-images.githubusercontent.com/32091566/105260810-6a9a8e00-5bc9-11eb-823d-16f9eb007048.png)

**Comment by georgehpj** [comment]
看起来如果layouts/index.tsx存在，umi会生成嵌套子路由配置。
```
  {
    "path": "/",
    "component": require('@/layouts/index.tsx').default,
    "routes": [
      {
        "path": "/docs.html",
        "exact": true,
        "component": require('@/pages/docs.tsx').default
      },
      {
        "path": "/index.html",
        "exact": true,
        "component": require('@/pages/index.tsx').default
      },
      {
        "path": "/",
        "exact": true,
        "component": require('@/pages/index.tsx').default
      }
    ]
  }
];
```
而删除layouts目录后服务可正常访问。看起来umi3在mpa模式下并未支持layouts公共布局。
