### ISSUE TITLE
[Bug] umi3打包后使用sha256加密任意字符后生成的字符串都一样

### ISSUE THREAD

**Issue by licairen** [umijs/umi#6038]
## What happens?

项目中使用js-sha56加密字符串，本地开发环境加密是ok的，yarn build之后加密任意字符生成的都是同一个字符串
#### yarn dev  本地开发环境加密的字符: 

![image](https://user-images.githubusercontent.com/36987278/104984841-862b5a80-5a4a-11eb-8980-8e8873b27150.png)

#### yarn build之后加密的字符：
打包命令：
![image](https://user-images.githubusercontent.com/36987278/104985975-1074be00-5a4d-11eb-91ed-47052c458fe1.png)

![image](https://user-images.githubusercontent.com/36987278/104985148-487b0180-5a4b-11eb-8b05-8ae93bba2169.png)

## Context

- **Umi Version**: ^3.2.14
- **antd**:  ^4.9.2,
- **yarn Version**: ^1.22.10
- **Node Version**: v14.15.4
- **Platform**: macOS 10.15.7

-  **js-sha256**: ^0.9.0

**Comment by sorrycc** [comment]
自己排查下，非 umi 的范围。

**Comment by licairen** [comment]
问题已经解决。
把js-sha256换成crypto-js即可
