### ISSUE TITLE
Cannot find module \umi\node_modules\af-webpack\lib\debugLoader.js

### ISSUE THREAD

**Issue by vince-fly** [umijs/umi#604]
`Failed to compile
./pages/.umi/router.js
Module build failed: Error: Cannot find module '**\umi-examples\routes\C:\Program Files\nodejs\node_modules\umi\node_modules\af-webpack\lib\debugLoader.js'
This error occurred during the build time and cannot be dismissed.`

这是什么情况？umi的测试例子，运行不了

**Comment by sorrycc** [comment]
在 #545 统一跟进，先把 umi 安装到项目本地吧。
