### ISSUE TITLE
sh: node-waf: 未找到命令，node版本：10.14.1

### ISSUE THREAD

**Issue by 0913raspberry** [umijs/umi#6043]
具体信息如下
[npminstall:runscript] scripts.preinstall umi@3.3.6 › @umijs/preset-built-in@3.3.6 › zlib@1.0.5  "node-waf clean || true; node-waf configure build", root: "-------/node_modules/_zlib@1.0.5@zlib"
sh: node-waf: 未找到命令
sh: node-waf: 未找到命令
✖ Install fail! RunScriptError: Run "sh -c node-waf clean || true; node-waf configure build" error, exit code 127
RunScriptError: Run "sh -c node-waf clean || true; node-waf configure build" error, exit code 127
    at ChildProcess.proc.on.code (/-------------/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

**Comment by sorrycc** [comment]
环境问题，google 解决下，https://www.google.com/search?q=node-waf+command+not+found&oq=node-waf&aqs=chrome.1.69i57j0j0i30j0i10i30j0i30i395l3j69i61.1780j1j7&sourceid=chrome&ie=UTF-8
