### ISSUE TITLE
[Bug] eslint 中添加rules校验不通过

### ISSUE THREAD

**Issue by Statfine** [umijs/umi#6056]
## 添加rules导致校验无法通过

eslintrc 中添加了一个rules : "react/no-children-prop"导致无法提交代码
```
module.exports = {
  extends: [require.resolve('@umijs/fabric/dist/eslint')],
  globals: {
    ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION: true,
    page: true,
    REACT_APP_ENV: true,
  },
  rules: {
    'react/no-children-prop': 0,
  },
};
```

commit的时候提示 如下
```
0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: .eslintrc.js.
The file must be included in at least one of the projects provided
```

网上没查到解决方法也没看到相关文档说明

- **Umi Version**: 3.2.0
- **Node Version**: 12.16.1
- **Platform**: Mac 10.15.7

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/105349614-f1308900-5c24-11eb-800b-a1953e9e87f5.png)
include 中增加  ".eslintrc.js"

**Comment by Statfine** [comment]
@chenshuai2144 
我是直接在eslintrc里面添加createDefaultProgram: true 处理的

因为按照你的方法执行lint的时候会报错
```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: ....tsx.
The file must be included in at least one of the projects provided. 
```

**Comment by chenshuai2144** [comment]
在 include 里加一下，不要createDefaultProgram 性能太差了

**Comment by Statfine** [comment]
include添加后lint的时候报错， 报错的文件是项目文件，并不是第一次的.eslintrc.js文件

The file does not match your project config:  会指到项目下所有文件

**Comment by Statfine** [comment]
升级相关库上面问题就没了
```
umi: 3.2.14
@umijs/fabric: 2.3.0
```
