### ISSUE TITLE
[Bug] pluginMethods中api拼写错误 ，且与文档不一致，应该是addBeforeMiddlewares

### ISSUE THREAD

**Issue by Julyaan** [umijs/umi#6068]
- **Umi Version**:  3.3.1 （@umijs/core）
- **Node Version**:
- **Platform**:

代码里写的是`addBeforeMiddewares`
而官方文档写的是： `addBeforeMiddlewares`
导致开发插件时报错

**Comment by sorrycc** [comment]
做了适配了，两个都能用。
