### ISSUE TITLE
[Bug] 引用第三方库@alifd/next的样式文件， 报错： “pop” of undefined

### ISSUE THREAD

**Issue by promotion-xu** [umijs/umi#6070]
## Mini Showcase Repository(REQUIRED)

> Please provide a link by forking these link [codesandbox umi](https://codesandbox.io/s/umi-2d4js?file=/src/pages/index.tsx) or using `yarn create @umijs/umi-app` then upload to your GitHub
> 请提供一个尽可能精简的链接 [codesandbox umi](https://codesandbox.io/s/umi-2d4js?file=/src/pages/index.tsx) 或使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

1. 安装第三方依赖， yarn add  @alifd/next
2. 在模块中引入
```js
import CascaderSelect from '@alifd/next/lib/cascader-select'
import '@alifd/next/dist/next.css'
```
3. 编译报错。
![image](https://user-images.githubusercontent.com/36992764/105671714-21767100-5f1e-11eb-8e4c-17a46603dbee.png)

## Context

- **Umi Version**: 2.4.4
- **Node Version**:  12.16.3
- **Platform**:  macOS

**Comment by promotion-xu** [comment]
注：这个库的样式是scss写的，是不是要配置什么

**Comment by PeachScript** [comment]
Umi 2 的问题请先在 v2 文档里找：https://v2.umijs.org/zh/guide/faq.html#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8-sass-%EF%BC%9F

Umi 3 已经出来很久了，建议升级：https://umijs.org/zh-CN/docs/upgrade-to-umi-3
