### ISSUE TITLE
[Bug] qiankun-plugin安装后显示cannot find module "@@/history" 

### ISSUE THREAD

**Issue by YimingXieUSC** [umijs/umi#6073]
## What happens?
项目：微前端qiankun vue主项目+umijs子项目 
           umijs版本为2.0，配备了dva和qiankun-plugin
           安装qiankun-plugin之前子项目可以顺利运行，然而安装之后compile失败，终端显示cannot find module "@@/history" 
           虽然无法提供代码仓库，下面附了一些代码的截图，希望有大佬可以帮忙解答，谢谢！
![package_json](https://user-images.githubusercontent.com/68513408/105689952-5f7f8f00-5f36-11eb-8ff1-5ed40183002a.png)
![企业微信截图_20210125175521](https://user-images.githubusercontent.com/68513408/105690060-83db6b80-5f36-11eb-92cd-360b9c79c37c.png)
![企业微信截图_20210125175611](https://user-images.githubusercontent.com/68513408/105691768-9ce51c00-5f38-11eb-8d7b-0e660462fb71.png)

**Comment by PeachScript** [comment]
`@umijs/plugin-qiankun` 是用于 Umi 3 的，请升级你的 Umi 版本或者使用旧版的 https://github.com/umijs/umi-plugin-qiankun
