### ISSUE TITLE
[Bug] umi 3.2.23 无法热更新

### ISSUE THREAD

**Issue by bocai-h** [umijs/umi#6074]
yarn start启动项目后，更新代码保存，不会触发重新编译

**Comment by williamnie** [comment]
提交一个复现仓库吧，我没复现出来，是csr还是ssr模式？

**Comment by bocai-h** [comment]
> 提交一个复现仓库吧，我没复现出来，是csr还是ssr模式？

 csr模式，以前都可以的，突然就不行了，但是修改.umirc.dev.ts却可以触发重新编译

**Comment by williamnie** [comment]
重装下依赖呢，有试过么

**Comment by bocai-h** [comment]
> 重装下依赖呢，有试过么

没有 我试试

**Comment by bocai-h** [comment]
> 重装下依赖呢，有试过么

我把node_modules删了重装， 依然没用

**Comment by williamnie** [comment]
给我来个复现吧，很难猜到哪里的问题

**Comment by bocai-h** [comment]
> 给我来个复现吧，很难猜到哪里的问题

https://github.com/suterusu-team/suterusu-protocol-website.git  源代码在这里  求帮忙看看

**Comment by bocai-h** [comment]
> > > 给我来个复现吧，很难猜到哪里的问题
> > 
> > 
> > https://github.com/suterusu-team/suterusu-protocol-website.git 源代码在这里 求帮忙看看
> 
> 貌似是个私有库吧，我打开是404

公司的项目，目前不能开源，我自己再看看吧 多谢

**Comment by williamnie** [comment]
采用二分法找bug，先删除一部分代码，看看有没有好，没有就再删，直到删到正常了，就能定位到是哪里的问题了

**Comment by williamnie** [comment]
issue先关闭了，实在找不到，就得提供下复现仓库才可以了

**Comment by bocai-h** [comment]
> 采用二分法找bug，先删除一部分代码，看看有没有好，没有就再删，直到删到正常了，就能定位到是哪里的问题了

好的 多谢 我也可以新建一个项目看看是不是我本地环境有问题

**Comment by williamnie** [comment]
我想到一种可能性，可能和文件大小写有关，我不知道你的系统是啥，mac还是windows，你可以看看是不是文件名大小写问题，比如你的文件名是testNode，但是你import的时候写的是TestNode，在mac上也不会报错，但可能会造成无法热更新

**Comment by andylei18** [comment]
遇到一样的问题，还是Open把？

**Comment by williamnie** [comment]
> 遇到一样的问题，还是Open把？

参照我上面说的debug一下试试或者是提供一个最小复现，我这块没法复现这个bug，不太好定位

**Comment by gx28ga** [comment]
> yarn start启动项目后，更新代码保存，不会触发重新编译

我今天也遇到这个问题了。
解决方法：文件名目录名和路由配置path字段都检查一下，确认大小写都是一样的

**Comment by renwangT** [comment]
用着用着就不热更新了，会检测到重新编译，但是页面不会刷新。
