### ISSUE TITLE
[Feature Request] Upgrade Dependencies

### ISSUE THREAD

**Issue by ycjcl868** [umijs/umi#6078]
### Major

- [x] `jest` 26 https://github.com/umijs/umi/pull/6272 @ycjcl868
- [ ] `less` 4 and `less-loader` 7
  - [ ] should verify `antd` whether ok
- [ ] `postcss` 8  https://github.com/umijs/umi/pull/6297 @ycjcl868
- [ ] `@hapi/joi` @ycjcl868 
- [x] `webpack` 5 @sorrycc 
- [ ] `react` 17 @ycjcl868 
- [ ] `react-intl` 5  @chenshuai2144 

### Minor

- [ ] chokidar 3.5.1 

--

## :recycle: Hi, It's time to update the npm package!

**28 npm packages** are outdated.
Let's begin maintenance to maintain a fresh package!

---
<details>
  <summary>Packages</summary>
  <ul>
    <li><a href="https://github.com/testing-library/react-testing-library#readme">@testing-library/react</a></li>
    <li><a href="https://github.com/DefinitelyTyped/DefinitelyTyped.git">@types/react</a></li>
    <li><a href="https://github.com/DefinitelyTyped/DefinitelyTyped.git">@types/react</a></li>
    <li><a href="https://github.com/DefinitelyTyped/DefinitelyTyped.git">@types/react-dom</a></li>
    <li><a href="https://github.com/DefinitelyTyped/DefinitelyTyped.git">@types/react-dom</a></li>
    <li><a href="https://github.com/SBoudrias/Inquirer.js#readme">inquirer</a></li>
    <li><a href="https://github.com/lerna/lerna#readme">lerna</a></li>
    <li><a href="https://github.com/sindresorhus/normalize-url#readme">normalize-url</a></li>
    <li><a href="https://github.com/webpack-contrib/postcss-loader">postcss-loader</a></li>
    <li><a href="https://reactjs.org/">react</a></li>
    <li><a href="https://reactjs.org/">react-dom</a></li>
    <li><a href="https://babel.dev/docs/en/next/babel-core">@babel/core</a></li>
    <li><a href="https://babel.dev/docs/en/next/babel-core">@babel/core</a></li>
    <li><a href="https://babel.dev/docs/en/next/babel-runtime">@babel/runtime</a></li>
    <li><a href="https://babel.dev/docs/en/next/babel-traverse">@babel/traverse</a></li>
    <li><a href="https://babel.dev/docs/en/next/babel-traverse">@babel/traverse</a></li>
    <li><a href="https://babel.dev/docs/en/next/babel-types">@babel/types</a></li>
    <li><a href="https://github.com/DefinitelyTyped/DefinitelyTyped.git">@types/babel__traverse</a></li>
    <li><a href="https://github.com/DefinitelyTyped/DefinitelyTyped.git">@types/sockjs-client</a></li>
    <li><a href="https://github.com/zloirock/core-js#readme">core-js</a></li>
    <li><a href="https://github.com/zloirock/core-js#readme">core-js</a></li>
    <li><a href="https://github.com/facebook/regenerator/tree/master/packages/regenerator-runtime">regenerator-runtime</a></li>
    <li><a href="https://github.com/DefinitelyTyped/DefinitelyTyped.git">@types/babel__core</a></li>
    <li><a href="https://github.com/DefinitelyTyped/DefinitelyTyped.git">@types/jest</a></li>
    <li><a href="https://github.com/DefinitelyTyped/DefinitelyTyped.git">@types/node</a></li>
    <li><a href="http://github.com/umijs/dumi">@umijs/preset-dumi</a></li>
    <li><a href="https://github.com/sindresorhus/open#readme">open</a></li>
    <li><a href="https://terser.org">terser</a></li>
  </ul>
</details>
---

## :warning: Major (11 packages)

| Package | Current | Wanted | Latest | Type | CHANGELOG |
|:----|:----|:----|:----|:----|:----|
| [@testing-library/react](https://github.com/testing-library/react-testing-library#readme) | `10.4.9` | `10.4.9` | `11.2.5` | `devDependencies` | - |
| [@types/react](https://github.com/DefinitelyTyped/DefinitelyTyped.git) | `16.14.5` | `16.14.5` | `17.0.3` | `dependencies` | - |
| [@types/react](https://github.com/DefinitelyTyped/DefinitelyTyped.git) | `16.14.5` | `16.14.5` | `17.0.3` | `dependencies` | - |
| [@types/react-dom](https://github.com/DefinitelyTyped/DefinitelyTyped.git) | `16.9.11` | `16.9.11` | `17.0.2` | `dependencies` | - |
| [@types/react-dom](https://github.com/DefinitelyTyped/DefinitelyTyped.git) | `16.9.11` | `16.9.11` | `17.0.2` | `dependencies` | - |
| [inquirer](https://github.com/SBoudrias/Inquirer.js#readme) | `7.3.3` | `7.3.3` | `8.0.0` | `devDependencies` | - |
| [lerna](https://github.com/lerna/lerna#readme) | `3.22.1` | `3.22.1` | `4.0.0` | `devDependencies` | - |
| [normalize-url](https://github.com/sindresorhus/normalize-url#readme) | `1.9.1` | `1.9.1` | `5.3.0` | `dependencies` | - |
| [postcss-loader](https://github.com/webpack-contrib/postcss-loader) | `4.2.0` | `4.2.0` | `5.2.0` | `dependencies` | - |
| [react](https://reactjs.org/) | `16.14.0` | `16.14.0` | `17.0.1` | `dependencies` | - |
| [react-dom](https://reactjs.org/) | `16.14.0` | `16.14.0` | `17.0.1` | `dependencies` | - |

## :zap: Minor (11 packages)

| Package | Current | Wanted | Latest | Type | CHANGELOG |
|:----|:----|:----|:----|:----|:----|
| [@babel/core](https://babel.dev/docs/en/next/babel-core) | `7.10.4` | `7.10.4` | `7.13.10` | `devDependencies` | - |
| [@babel/core](https://babel.dev/docs/en/next/babel-core) | `7.12.10` | `7.12.10` | `7.13.10` | `dependencies` | - |
| [@babel/runtime](https://babel.dev/docs/en/next/babel-runtime) | `7.12.5` | `7.12.5` | `7.13.10` | `dependencies` | - |
| [@babel/traverse](https://babel.dev/docs/en/next/babel-traverse) | `7.12.5` | `7.12.5` | `7.13.0` | `devDependencies` | - |
| [@babel/traverse](https://babel.dev/docs/en/next/babel-traverse) | `7.12.5` | `7.12.5` | `7.13.0` | `devDependencies` | - |
| [@babel/types](https://babel.dev/docs/en/next/babel-types) | `7.12.6` | `7.12.6` | `7.13.0` | `devDependencies` | - |
| [@types/babel__traverse](https://github.com/DefinitelyTyped/DefinitelyTyped.git) | `7.0.13` | `7.0.13` | `7.11.1` | `devDependencies` | - |
| [@types/sockjs-client](https://github.com/DefinitelyTyped/DefinitelyTyped.git) | `1.1.1` | `1.1.1` | `1.5.0` | `devDependencies` | - |
| [core-js](https://github.com/zloirock/core-js#readme) | `3.6.5` | `3.6.5` | `3.9.1` | `dependencies` | - |
| [core-js](https://github.com/zloirock/core-js#readme) | `3.8.2` | `3.8.2` | `3.9.1` | `dependencies` | - |
| [regenerator-runtime](https://github.com/facebook/regenerator/tree/master/packages/regenerator-runtime) | `0.13.5` | `0.13.5` | `0.13.7` | `dependencies` | - |

## :beginner: Patch (6 packages)

| Package | Current | Wanted | Latest | Type | CHANGELOG |
|:----|:----|:----|:----|:----|:----|
| [@types/babel__core](https://github.com/DefinitelyTyped/DefinitelyTyped.git) | `7.1.9` | `7.1.9` | `7.1.13` | `devDependencies` | - |
| [@types/jest](https://github.com/DefinitelyTyped/DefinitelyTyped.git) | `26.0.20` | `26.0.21` | `26.0.21` | `devDependencies` | - |
| [@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped.git) | `14.14.33` | `14.14.35` | `14.14.35` | `devDependencies` | - |
| [@umijs/preset-dumi](http://github.com/umijs/dumi) | `1.1.7` | `1.1.9` | `1.1.9` | `devDependencies` | - |
| [open](https://github.com/sindresorhus/open#readme) | `8.0.2` | `8.0.3` | `8.0.3` | `devDependencies` | - |
| [terser](https://terser.org) | `5.6.0` | `5.6.0` | `5.6.1` | `dependencies` | - |

**Comment by sorrycc** [comment]
时间过去有点久了，这个还在跟吗？

**Comment by ycjcl868** [comment]
跟进
