### ISSUE TITLE
[Feature Request] umi打包后生成的html可以异步加载脚本，样式文件吗

### ISSUE THREAD

**Issue by promotion-xu** [umijs/umi#6080]
## Background
umi分包后，有些文件不需要在登录页就加载。这个时候可以用异步加载的方式来提高首屏加载速度

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by PeachScript** [comment]
请详细描述具体场景，以及看你其他 issue 还在使用 Umi 2，这个也是 Umi 2 相关的问题？

**Comment by sorrycc** [comment]
配置 dynamicImport 就好了。

**Comment by cloudyan** [comment]
@sorrycc 

开启，dynamicImport: {}，umi 过大，且有这个问题（https://github.com/umijs/umi/discussions/6086）
其他文件过小, 这里不给开放自定义分组了吗，每个文件都不到 10k,太小

**Comment by promotion-xu** [comment]
@sorrycc 
像这些script脚本，在Umi打包后能不能 加上async
![image](https://user-images.githubusercontent.com/36992764/106120876-e0869280-6191-11eb-8502-725caa1df2e4.png)

**Comment by SpiritQAQ** [comment]
> @sorrycc
> 像这些script脚本，在Umi打包后能不能 加上async
> ![image](https://user-images.githubusercontent.com/36992764/106120876-e0869280-6191-11eb-8502-725caa1df2e4.png)

老哥弄成了吗

**Comment by cloudyan** [comment]
> @sorrycc
> 像这些script脚本，在Umi打包后能不能 加上async
> ![image](https://user-images.githubusercontent.com/36992764/106120876-e0869280-6191-11eb-8502-725caa1df2e4.png)

加async 会异步加载执行 无法保证执行顺序 反而有问题
