### ISSUE TITLE
[Bug] 约定路由生成错误问题

### ISSUE THREAD

**Issue by sharh** [umijs/umi#6090]
## What happens?

umi约定路由生成错误，无法生成/index这样的路径，如果创建了index目录，如index/index.tsx则会产品路由错误，有2个组件映射到同一个路由/上
![image](https://user-images.githubusercontent.com/7692602/106224350-2721ce80-621e-11eb-905d-ed933f47d5ee.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub
> 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

Git仓库：https://github.com/sharh/umi-demo.git

## How To Reproduce
复现Git仓库：https://github.com/sharh/umi-demo.git

## Context

- **Umi Version**: ^3.3.7
- **Node Version**: v12.16.1
- **Platform**: windows10

**Comment by williamnie** [comment]
/ 默认就指向index啊，你在浏览器里输入/ 和 /index效果是一样的，你的文件夹就叫index，里面的内容还叫index，肯定会被替换成/的啊，你看你下面的index/index2就没问题吧，这不是bug
