### ISSUE TITLE
[Bug] UmiJS与yarn workspace集成，当子项目名称存在@时报错。

### ISSUE THREAD

**Issue by veici** [umijs/umi#6093]
## What happens?
UmiJS与yarn workspace集成，当子项目名称存在@时报错。只Windows下会报错，macos下不会。

当子项目存在@时，yarn install  安装依赖时报错
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub
> 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/veici/report
## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

1. 创建package.json、packages
2. 在packages下分别创建bug、home文件夹，依次使用 `yarn create @umijs/umi-app`创建项目
3. 修改子项目名称为`@report/bug` `@report/home`
4. 执行yarn install安装依赖 

## Context

- **Umi Version**:^3.3.7
- **Node Version**:v15.0.1
- **Platform**:windows

**Comment by sorrycc** [comment]
yarn 安装报错应该在 yarn 的 issue 里提。

**Comment by wangchaoHeart** [comment]
> yarn 安装报错应该在 yarn 的 issue 里提。

应该不是yarn的问题，只有创建的umijs项目（package.json里name带@）才会出现报错，
我现在也遇到了这个问题
