### ISSUE TITLE
[Bug] Invalid config key: dynamicImportSyntax

### ISSUE THREAD

**Issue by cajan** [umijs/umi#6096]
配置：
![image](https://user-images.githubusercontent.com/4647608/106250279-6405b980-624e-11eb-9fc7-4b88521f4576.png)

疑似有bug，ts定义中存在dynamicImportSyntax，但实际并不支持dynamicImportSyntax

## Context

- **Umi Version**: 3.3.7
- **Node Version**: 14.15.4
- **Platform**: mac os 10.15.7

**Comment by prettyboyweiwei** [comment]
+1 ，官网有这个配置，但是 umi 的 types 里没有这一项定义，build 时也不认识这个 key 而报错。有大佬吗
https://umijs.org/zh-CN/config#dynamicimportsyntax

**Comment by AlisonZXQ** [comment]
> +1 ，官网有这个配置，但是 umi 的 types 里没有这一项定义，build 时也不认识这个 key 而报错。有大佬吗
> https://umijs.org/zh-CN/config#dynamicimportsyntax

+1
