### ISSUE TITLE
[Bug] 遇到了一些IE 的问题配置 targets:{ie : 10} 在IE10 出现了 语法错误  Umi@3

### ISSUE THREAD

**Issue by shxinlei** [umijs/umi#6099]
## What happens?

在 配置 IE 10 后出现 SCRIPT1002 的语法错误  在 devScripts.js 中
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub
> 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

git clone https://github.com/shxinlei/demo-umi.git

npm install

npm run start

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

![image](https://user-images.githubusercontent.com/54462126/106377574-e15d3580-63d8-11eb-9cc4-42714fda38e8.png)

## Context

- **Umi Version**: v3.3.7
- **Node Version**:v14.13.1
- **Platform**:
-  "dependencies": {
    "@ant-design/pro-layout": "^6.5.0",
    "@hookform/error-message": "0.0.5",
    "@umijs/preset-react": "1.x",
    "react-hook-form": "^6.14.2",
    "umi": "^3.3.7"
  },
"devDependencies": {
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "@umijs/test": "^3.3.7",
    "lint-staged": "^10.0.7",
    "prettier": "^2.2.0",
    "react": "17.x",
    "react-dom": "17.x",
    "typescript": "^4.1.2",
    "yorkie": "^2.0.0"
  }

**Comment by shxinlei** [comment]
初始化 umi 创建的 也会出现语法错误的问题

**Comment by free-pan** [comment]
请问你解决了吗？应该如何解决，我也遇到了这个类似问题.

**Comment by guanyuan** [comment]
+1

**Comment by simplast** [comment]
+1

**Comment by guanyuan** [comment]
已解决，参考配置如下：
`
dva: {
    hmr: true,
    immer: { enableES5: true }, // 表示是否启用 immer 以方便修改 reducer,如需兼容 IE11，需配置 { immer: { enableES5: true }}。
  },
`

**Comment by simplast** [comment]
请问怎么解决的？就关闭了吗

**Comment by FelicityGao** [comment]
怎么解决的？

**Comment by azx1985** [comment]
> 已解决，参考配置如下： `dva: { hmr: true, immer: { enableES5: true }, // 表示是否启用 immer 以方便修改 reducer,如需兼容 IE11，需配置 { immer: { enableES5: true }}。 },`

我试了没用；

SCRIPT1002: 语法错误
devScripts.js (25,5)
SCRIPT1002: 语法错误
umi.js (79343,29)

用谷歌、edge、360的兼容模式也都没问题，就IE浏览器会报错

**Comment by 0MrDream0** [comment]
把mfsu去掉
