### ISSUE TITLE
Premature public directory check for copying at af-webpack/lib/getConfig.js

### ISSUE THREAD

**Issue by tsuijie** [umijs/umi#61]
```
af-webpack/lib/getConfig.js, line 185-191:
  if ((0, _fs.existsSync)((0, _path.resolve)(opts.cwd, 'public'))) {
    copyPlugins.push(new _copyWebpackPlugin.default([{
      from: (0, _path.resolve)(opts.cwd, 'public'),
      to: outputPath,
      toType: 'dir'
    }]));
  }
```
If ```public``` directory is set as the destination directory, webpack will remove the directory after fs.existsSync check, which will cause copy-webpack-plugin compile error.
Suggestion: either externalize this configuration, or disable this feature completely since the ```copy``` configuration for copy-webpack-plugin is already externalized.

https://github.com/sorrycc/roadhog/issues/30
https://github.com/sorrycc/roadhog/issues/341
https://github.com/sorrycc/roadhog/issues/464

**Comment by sorrycc** [comment]
How to reproduce it?

**Comment by sorrycc** [comment]
Feel free to reopen it have any progress.

**Comment by tsuijie** [comment]
Using roadhog configuration, at .webpackrc.js:
```
  "outputPath": "./public",
  "publicPath": "/",
  "copy": [
    {
      "from": path.resolve(__dirname + '/someDirectory'),
      "to": path.resolve(__dirname + '/public')
    }
  ],
```
