### ISSUE TITLE
请问umi如何增加 index.ts作为入口文件

### ISSUE THREAD

**Issue by birdycn** [umijs/umi#6100]
import 只会找index.js文件

请问umi如何增加 index.ts作为入口文件

在config/config.ts配置extensions: ['.ts', '.js', '.json'],，提示没有该配置项

**Comment by osinglee** [comment]
用 .tsx 能解决吗

**Comment by youtiao66** [comment]
- 建议通过 yarn create @umijs/umi-app 初始化项目，自动包含 tsconfig.json
- 你也可以尝试手动添加 tsconfig.json
