### ISSUE TITLE
[代理]希望 本地代理支持http-proxy-middleware  context的全部能力

### ISSUE THREAD

**Issue by blanky01** [umijs/umi#6102]
## Background

现在的proxy配置数据是{key:value}的形式，key会被转化成proxy 的 context，但是这限制了原http-proxy-middleware context支持的一些能力，比如函数式context。希望能补充这部分能力。

**Comment by sorrycc** [comment]
@ycjcl868 需要加的直接 PR 加吧，ISSUE 先关了。
