### ISSUE TITLE
[Bug] history 配置getUserConfirmation没有用

### ISSUE THREAD

**Issue by liuxiansheng2018** [umijs/umi#6103]
history 中options配置 getUserConfirmation:(message:string, callback:Function) => callback(window.confirm(message)) 没有效果， 但是通过ant design pro5脚手架下面发现  src/.umi/core/history.ts 新增getUserConfirmation参数配置是可以的， 但是每次重新启动项目的时候会重新把配置恢复初始状态
![image](https://user-images.githubusercontent.com/35281468/106420179-0e6f1e00-6495-11eb-9e7c-84829ba0626c.png)

**Comment by sorrycc** [comment]
参考文档，https://umijs.org/zh-CN/docs/directory-structure#umi-%E7%9B%AE%E5%BD%95
