### ISSUE TITLE
build 生成js文件问题

### ISSUE THREAD

**Issue by changyijie** [umijs/umi#611]
> 嵌套路由中 也出现 #467 这种问题， 下面是路由配置  umi版本` "1.3.5"`

```
[
  {
    "path": "/",
    "exact": "true",
    "component": "./src/pages/_layout",
    "routes": []
  },
  {
    "path": "/users",
    "component": "./src/pages/users/_layout",
    "routes":[
      {
        "path":"/users/posts",
        "component":"./src/pages/posts/_layout",
        "routes":[
          {
            "path":"/users/posts/post",
            "component":"./src/pages/post/index"
          }
        ]
      }
    ]
  },
  {
    "path": "/404",
    "component": "./src/pages/404"
  }
]
```

> build 之后应该会有 post对应的 `post_async` 文件 ， 但是只有 `posts_layout.async.js`  如下图

![image](https://user-images.githubusercontent.com/31202798/41144032-0c5fe6ac-6b2e-11e8-88f1-7930f191f092.png)

**Comment by sorrycc** [comment]
配置式还是约定式的？给个可重现的代码？

**Comment by changyijie** [comment]
https://github.com/changyijie/umiTest  可重现代码

**Comment by changyijie** [comment]
@sorrycc  大佬 这个问题看了没

**Comment by sorrycc** [comment]
仔细看了下，原因是 umi 只做了一级路由的按需编译，访问应该是正常的吧。

**Comment by changyijie** [comment]
恩恩 访问是正常的  不过umi.js有点大了  不知道是不是这个原因引起的呢

**Comment by sorrycc** [comment]
你可以试试 `CODE_SPLITTING_LEVEL=3 umi build`。

**Comment by changyijie** [comment]
好的 Thanks♪(･ω･)ﾉ

**Comment by changyijie** [comment]
`CODE_SPLITTING_LEVEL=3 umi build`  这个不行哦    umi.js文件大小比之前大了    只能改下路由liao
