### ISSUE TITLE
invalid config key dynamicImportSyntax 报错

### ISSUE THREAD

**Issue by AlisonZXQ** [umijs/umi#6113]
## What happens?

dynamicImportSyntax配置不存在
![image](https://user-images.githubusercontent.com/17682217/106694158-f7563a80-6612-11eb-8b84-aca933b93844.png)

## Mini Showcase Repository(REQUIRED)
随意的umi 3.3.7项目

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.3.7
- **Node Version**:
- **Platform**:

**Comment by feiaaa** [comment]
https://github.com/umijs/umi/issues/10027
