### ISSUE TITLE
[Bug] plugin-model: Invoking '@@initialState' model failed: TypeError: 对象不支持此操作

### ISSUE THREAD

**Issue by chenghangcong** [umijs/umi#6118]
ie 11 报这个错 版本umi3.3.3

我升到3.3.7也还是报这个错

packjson 如下

{
  "name": "ant-design-pro",
  "version": "4.2.1",
  "private": true,
  "description": "An out-of-box UI solution for enterprise applications",
  "scripts": {
    "start:mock": "cross-env REACT_APP_ENV=jc umi dev UMI_UI=none",
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ],
  "dependencies": {
    "@ant-design/icons": "4.3.0",
    "@ant-design/pro-descriptions": "1.0.22",
    "@ant-design/pro-layout": "6.5.1",
    "@ant-design/pro-table": "2.9.2",
    "@ant-design/pro-card": "1.4.2",
    "@umijs/route-utils": "1.0.34",
    "antd": "4.10.2",
    "axios": "0.21.1",
    "classnames": "2.2.6",
    "lodash": "4.17.20",
    "moment": "2.29.1",
    "omit.js": "2.0.2",
    "qs": "6.9.4",
    "react": "16.14.0",
    "react-dom": "16.14.0",
    "react-helmet-async": "1.0.7",
    "react-cookies": "0.1.1",
    "umi": "3.3.3",
    "umi-request": "1.3.5",
    "use-merge-value": "1.0.2"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "1.0.23",
    "@types/classnames": "2.2.11",
    "@types/express": "4.17.9",
    "@types/history": "4.7.8",
    "@types/jest": "26.0.19",
    "@types/lodash": "4.14.161",
    "@types/qs": "6.9.5",
    "@types/react": "16.14.2",
    "@types/react-cookies": "0.1.0",
    "@types/react-dom": "16.9.10",
    "@types/react-helmet": "6.1.0",
    "@umijs/fabric": "2.4.5",
    "@umijs/plugin-blocks": "2.2.2",
    "@umijs/preset-ant-design-pro": "1.3.0",
    "@umijs/preset-react": "1.7.9",
    "@umijs/preset-ui": "2.2.9",
    "@umijs/yorkie": "2.0.5",
    "carlo": "0.9.46",
    "chalk": "4.1.0",
    "cross-env": "7.0.3",
    "cross-port-killer": "1.2.1",
    "detect-installer": "1.0.2",
    "enzyme": "3.11.0",
    "eslint": "7.16.0",
    "express": "4.17.1",
    "gh-pages": "3.1.0",
    "jsdom-global": "3.0.2",
    "lint-staged": "10.5.3",
    "mockjs": "1.1.0",
    "prettier": "2.1.1",
    "pro-download": "1.0.1",
    "puppeteer-core": "5.5.0",
    "stylelint": "13.8.0",
    "typescript": "3.9.7"
  },
  "engines": {
    "node": ">=10.0.0"
  },
  "checkFiles": [
    "src/**/*.js*",
    "src/**/*.ts*",
    "src/**/*.less",
    "config/**/*.js*",
    "scripts/**/*.js"
  ],
  "create-umi": {
    "ignoreScript": [
      "docker*",
      "functions*",
      "site",
      "generateMock"
    ],
    "ignoreDependencies": [
      "netlify*",
      "serverless"
    ],
    "ignore": [
      ".dockerignore",
      ".git",
      ".github",
      ".gitpod.yml",
      "CODE_OF_CONDUCT.md",
      "Dockerfile",
      "Dockerfile.*",
      "lambda",
      "LICENSE",
      "netlify.toml",
      "README.*.md",
      "azure-pipelines.yml",
      "docker",
      "CNAME",
      "create-umi"
    ]
  }
}

**Comment by ttys026** [comment]
需要提供下可复现仓库
