### ISSUE TITLE
自动生成路由问题

### ISSUE THREAD

**Issue by taizhengfs** [umijs/umi#612]
目录如下：
```
+blocks
  - $id
    - models
       - detail.js
    - index.js
    - index.less
```
我看到一个umi+dva的后台，会自动生成如下的路由，但是我这么配置总是无法生成，不知道为啥
`      {
        "path": "/blocks/:id",
        "exact": true,
        "component": require('../blocks/$id/index.js').default
      },`

**Comment by taizhengfs** [comment]
只有我写在page下一级目录才会自动生成，我在page>blocks 下面新增任何JS或者文件夹都不会自动更新路由，有啥解决方案吗

**Comment by sorrycc** [comment]
有问题再 reopen 。
