### ISSUE TITLE
[Bug] 引入less文件提示找不到模块‘xxx’或其相应的类型声明

### ISSUE THREAD

**Issue by hjf0923** [umijs/umi#6124]
## What happens?
引入less文件提示找不到模块‘xxx’或其相应的类型声明，如下图：
![image](https://user-images.githubusercontent.com/40063001/106861605-f13e8780-6700-11eb-97de-d725ffcd5d34.png)
虽然报错，然是样式引用能生效，如下图：
![image](https://user-images.githubusercontent.com/40063001/106861712-1632fa80-6701-11eb-8848-d62ceb2a0edc.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub
> 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.2.10
- **Node Version**: 12.18.0
- **Platform**:

**Comment by youtiao66** [comment]
是由于 `typescript` 检测到没有该模块导致的：
- 建议通过 `yarn create @umijs/umi-app` 初始化项目，自动包含 `typings.d.ts`
- 或者在根目录手动添加 `typings.d.ts`

```
declare module '*.less';
```
