### ISSUE TITLE
[Bug] 运行时配置 中的onRouteChange 函数 首次加载会执行两次

### ISSUE THREAD

**Issue by youtiao66** [umijs/umi#6135]
## What happens?

运行时配置 中的onRouteChange 函数 首次加载会执行两次

## Mini Showcase Repository(REQUIRED)

https://github.com/youtiao66/umi-route-change-twice

## How To Reproduce

1. `onRouteChange`执行一次
2. 开启dva配置 `{ dva: {} }`
3. 在`src/models`新建全局`GlobalModel`
4. `onRouteChange`执行两次

## Context

- **Umi Version**: v3.3.7
- **Node Version**: v10.23.0
- **Platform**: Windows 10

**Comment by airwaycai** [comment]
没人解决吗？

**Comment by minwe** [comment]
@sorrycc 这个有什么修复思路不？

看了一下代码，初始化的时候 https://github.com/umijs/umi/blob/master/packages/renderer-react/src/renderClient/renderClient.tsx#L61 这里会触发一次 change，其他没找到哪里触发 change 了。
