### ISSUE TITLE
[Bug] Unsafe inline scripts - CSP violation

### ISSUE THREAD

**Issue by crudo** [umijs/umi#6139]
## What happens?

Umi adds unsafe inline scripts to HTML.

Sources of those violations:

https://github.com/umijs/umi/blob/37980800b8b0a9b69faf6e65b82fca5402c7f0f9/packages/preset-built-in/src/plugins/commands/htmlUtils.ts#L141

https://github.com/umijs/umi/blob/2de577ed78c2df2a2a16933e97b77920366fcf6c/packages/preset-built-in/src/plugins/features/umiInfo.ts#L4

Resulting into 

```html
 <script> window.routerBase = "/"; </script>
 <script> //! umi version: 3.3.7 </script>
```

## Mini Showcase Repository

https://preview.pro.ant.design

## How To Reproduce

How to reproduce: Build and app.

Expected: There will be no inline scripts or at least they will have `nonce` or hash `sha`.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_inline_script

## Context

- **Umi Version**: 3+
- **Node Version**: any
- **Platform**: any

**Comment by ycjcl868** [comment]
Maybe you can add `Content-Security-Policy: script-src 'unsafe-inline';` in dev server response header.

**Comment by crudo** [comment]
Yeah, I can allow unsafe scripts, but that is exactly against the all security recommendations and best practices.

**Comment by ccapeng** [comment]
What is the solution?

My app is root level. Looks like I can get it work. But browser still complaint about it.
