### ISSUE TITLE
关于model动态加载的问题

### ISSUE THREAD

**Issue by yoyooyooo** [umijs/umi#614]
如果我有a，b 两个页面，分别对应2个model，a页面用到了b页面的组件，也用到了b的model。
如果我进首页后直接进a页面，这时候a页面，这时候b的model还没加载，就出错了。

请问我是应该把b页面里a用到的相关代码都挪到global上吗，但是这样感觉不太好，，这些代码是b页面带的，放b的model比较直观。。
我的项目结构是这样的：
```
+ pages
    + a
        + components
        - index.js
        - model.js
    + b
        + components
        - index.js
        - model.js
```
还是有更合理的解决方法吗？

**Comment by sorrycc** [comment]
page 之前不能相互引的，需要相互引的提到全局 model 里吧，详见 https://umijs.org/guide/with-dva.html#model-%E6%B3%A8%E5%86%8C
