### ISSUE TITLE
[Feature Request] Add package.json path to plugin api

### ISSUE THREAD

**Issue by jctaoo** [umijs/umi#6147]
## Background

插件 Api 类型 IApi 中的，`IApi.cwd` 与 `IApi.paths.cwd` 具有迷惑性，在未设置 APP_ROOT 变量时指向项目根，在设置 APP_ROOT 时指向 APP_ROOT，在插件中获取 package.json 困难。为了获取 package.json 并处理特殊情况，在开发插件的时候总是在 `api.cwd` 与 `process.cwd()` 中徘徊。

## Proposal

IApi 有提供 `absNodeModulesPath`，我想可以提供 `absPackageJSONPath` 字段 

## Additional context

如果这可行，我可以创建一个 pr 来实现它

**Comment by sorrycc** [comment]
api.cwd 区分 APP_ROOT 是正确的，如果要始终取当前目录，建议直接用 process.cwd() 。
