### ISSUE TITLE
[HELP]如何在dev下开启eslint检查？

### ISSUE THREAD

**Issue by codingbycat** [umijs/umi#6155]
![image](https://user-images.githubusercontent.com/46668343/108585502-cd777480-7383-11eb-806f-4d4177d5c132.png)
编辑器有报错提醒，但是编译的时候并没有完成检查

#### 环境
- 系统： Mac OS big sur
- "umi": "3.3.7"
- "@umijs/fabric": "^2.5.6",

**Comment by sorrycc** [comment]
Umi 3 在编译时没有做 eslint 检查。

**Comment by Mis-tian** [comment]
umi dev 本地服务器环境 无法进行eslint检查么？

**Comment by zemelLeong** [comment]
没有`.umi`目录生成的时候第一次启动有eslint报错，之后就没有了
```javascript
  chainWebpack(config) {
    config
      .plugin('eslint-webpack-plugin')
      .use(new ESLintPlugin({}));
  },
```

**Comment by lyj505** [comment]
> Umi 3 在编译时没有做 eslint 检查。

现在支持了嘛

**Comment by zemelLeong** [comment]
> > Umi 3 在编译时没有做 eslint 检查。
> 
> 现在支持了嘛

如果这是个疑问句的话，应该是支持的，我的配置如下
```js
  import ESLintPlugin from 'eslint-webpack-plugin';
  
  chainWebpack(config) {
    config.plugin('eslint-webpack-plugin').use(
      new ESLintPlugin({
        fix: true,
        extensions: ['ts', 'tsx', 'js', 'jsx'],
      }),
    );
    ...
```
