### ISSUE TITLE
Uncaught TypeError: Cannot read property 'store' of null

### ISSUE THREAD

**Issue by whereiscode** [umijs/umi#6161]
## 编译完之后说没有store ，dev模式下没问题

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/55313887/108796877-c3908400-75c4-11eb-8928-40e2ec3f35df.png">

## Context

- **Umi Version**:
- 3.3.7
- **Node Version**:
- 14
- **Platform**:
- Mac

**Comment by whereiscode** [comment]
只要是 用了 import { connect } from "umi";  就会报错    想不到是为什么  以前用就没事  我前几天升级了umi到3.3.7 部署的时候才发现这个问题

**Comment by whereiscode** [comment]
<img width="954" alt="image" src="https://user-images.githubusercontent.com/55313887/108800749-f17ac600-75ce-11eb-8c39-660e99da9065.png">
<img width="914" alt="image" src="https://user-images.githubusercontent.com/55313887/108800790-09524a00-75cf-11eb-8ef7-307004a2d544.png">

**Comment by whereiscode** [comment]
<img width="607" alt="image" src="https://user-images.githubusercontent.com/55313887/108800832-2850dc00-75cf-11eb-81b1-fd5f597ff4e1.png">
<img width="492" alt="image" src="https://user-images.githubusercontent.com/55313887/108800847-3141ad80-75cf-11eb-8911-ad01c6267312.png">

**Comment by whereiscode** [comment]
只要用connect就会报错

**Comment by whereiscode** [comment]
@sorrycc 大神可以看一秒吗 打扰啦 我实在是调不出来了 才圈的您    我用umi也有4年了

**Comment by whereiscode** [comment]
getDvaApp() 获得的是null

**Comment by whereiscode** [comment]
重新创建项目，把代码再都复制过去就可以了，不理解为什么，如果有知道的希望能说下 ：D

**Comment by wsz7777** [comment]
我遇到一次，是因为我在调用 getDvaApp 的时候写在组件外了。我理解是只有dva初始化数据完成后执行这个方法才能获取到数据
