### ISSUE TITLE
SelectLang组件默认的“繁体中文”四字能否改成真正的繁体：“繁體中文” ？

### ISSUE THREAD

**Issue by xjb258** [umijs/umi#6162]
应该在： node_modules\@umijs\plugin-locale\lib\templates\SelectLang.tpl

  'zh-TW': {
    lang: 'zh-TW',
    label: '繁体中文',
    icon: '🇭🇰',
    title: '語言'
  }

“体”字在繁体应该是“體”。

**Comment by xiaohuoni** [comment]
这里改 https://github.com/umijs/plugins/blob/10236bad419261d8a244616e9bf085770327dce5/packages/plugin-locale/src/templates/SelectLang.tpl#L369

**Comment by sorrycc** [comment]
感兴趣直接提 PR 就好。
