### ISSUE TITLE
[Bug]开启ssr，getInitialProps方法里面请求数据，并把请求到的数据return到页面，报以下的错误

### ISSUE THREAD

**Issue by RuoFeng2015** [umijs/umi#6177]
开启ssr，getInitialProps方法里面请求数据，并把请求到的数据return到页面，报以下的错误

![image](https://user-images.githubusercontent.com/41161634/109123067-62afaa00-7784-11eb-8cf1-f1979cc80619.png)
![image](https://user-images.githubusercontent.com/41161634/109123110-6ba07b80-7784-11eb-834e-822d142013f0.png)
umi 版本 3.37
windows

**Comment by williamnie** [comment]
没有对应的model啊，你的model里并没有叫data的model，你需要return到一个指定的model内，在页面渲染的时候，umi会从页面上的拿到renturn 的数据，序列化回对应的model内，在对比的时候才不会出现重新渲染

**Comment by ananiy** [comment]
> 没有对应的model啊，你的model里并没有叫data的model，你需要return到一个指定的model内，在页面渲染的时候，umi会从页面上的拿到renturn 的数据，序列化回对应的model内，在对比的时候才不会出现重新渲染

getInitialProps 必须返回和model一样的结构? 

这样限制是不是有点太大了

参考下nextjs的[实现](https://nextjs.org/docs/api-reference/data-fetching/getInitialProps) 可以返回任意结构直接注入到props

还细分出了: getStaticProps 和 getServerSideProps
