### ISSUE TITLE
[Bug] I Can't run project Ant Design Pro

### ISSUE THREAD

**Issue by ohmygod481999** [umijs/umi#6180]
## What happens?
When I "npm run dev" i found this bug

![image](https://user-images.githubusercontent.com/42038296/109252796-f636b880-7820-11eb-8d63-1aecd282c079.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

yarn create umi myApp

npm install

npm run dev

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.2.14
- **Node Version**: 14.16.0
- **Platform**: linux, windows, I tested on both environments

**Comment by yerled** [comment]
我也遇到了这个问题，今天新创建的ant design pro项目无法启动。

对比了一下之前创建的ant design pro旧项目，旧项目在启动时会创建src/.umi并执行，今天的新项目会同时在src目录和根目录创建 .umi文件夹（并执行？）
执行根目录下的.umi会报错，因为代码里相对路径都是不对的，找不到src目录的的文件

尝试拿旧项目的yarn.lock来重新安装依赖，成功启动

**Comment by Zhang-Haoran** [comment]
We have the same issue. While webpack the project, it generate two .umi files. One is in project level, the other one is in src folder. 我们有同样的问题

**Comment by bluevariant** [comment]
我们有同样的问题

**Comment by sorrycc** [comment]
给复现，我试了下正常，yarn create @umijs/umi-app，安装依赖，然后启动。

**Comment by fly4us** [comment]
是 yarn create umi myApp 失败，不是yarn create @umijs/umi-app 失败

**Comment by caijf** [comment]
umi@3.3.9 有问题，编译的 `.umi` 跟 `src` 目录同级 导致找不到

使用 umi@3.3.7 没这个问题

```bash
npm install umi@3.3.7
```

**Comment by codering** [comment]
+1

**Comment by zjh599245299** [comment]
+1 yarn create umi myapp 创建的项目就有这个问题

**Comment by sorrycc** [comment]
@codering @zjh599245299 能帮忙确认下最近哪个版本是好的吗？

**Comment by fly4us** [comment]
3.3.3 也是不行的，以前可以的，有个旧的项目就是3.3.3，看起来不一定是这个版本问题

**Comment by sorrycc** [comment]
感觉是啥插件改的。

**Comment by zjh599245299** [comment]
试了好几个版本 都是这个问题 3.2的版本也试了 也是有问题

**Comment by codering** [comment]
我找原来的项目中的yarn.lock，用的3.3.3就可以。

![image](https://user-images.githubusercontent.com/2271825/109273438-2b590000-784d-11eb-8599-501bc771e5bc.png)

**Comment by caijf** [comment]
@sorrycc  我用之前的package-lock.json 也正常

![image](https://user-images.githubusercontent.com/5070722/109274261-437d4f00-784e-11eb-8903-31a269293f6f.png)

**Comment by sorrycc** [comment]
@umijs/preset-dumi 更新引起的，如果没用到相关功能，可以在 package.json 中先删除，或者等 @PeachScript 更新修复。

**Comment by JethroCao** [comment]
> @umijs/preset-dumi 更新引起的，如果没用到相关功能，可以在 package.json 中先删除，或者等 @PeachScript 更新修复。

试了下，可以了，感谢！！！

**Comment by PeachScript** [comment]
dumi 已撤回对 Umi 临时目录的修改，辛苦各位重新安装下依赖，可以解决此问题

**Comment by ohmygod481999** [comment]
I try again and everything is doing fine. Thanks every one.
