### ISSUE TITLE
plugin-model: Invoking '@@initialState' model failed: TypeError

### ISSUE THREAD

**Issue by YUD1112** [umijs/umi#6183]
umi 3.3+ 

ie11报错

plugin-model: Invoking '@@initialState' model failed: TypeError
请问是什么原因呢

3.3.9最新版本也有复现此问题。。。请问是哪个版本解决的呢

**Comment by YUD1112** [comment]
node version: 10.16.3
npm version: 6.9.0
react: 16+

**Comment by sorrycc** [comment]
看下是不是相关问题，https://github.com/umijs/umi/issues/6180#issuecomment-786493761 ，不是的话给复现步骤。

**Comment by YUD1112** [comment]
> 看下是不是相关问题，[#6180 (comment)](https://github.com/umijs/umi/issues/6180#issuecomment-786493761) ，不是的话给复现步骤。

暂时回退umi版本到3.2.27，解决了应用场景中的问题

有空的时候我能不能写个demo复现出来
