### ISSUE TITLE
[Bug] use Pro V5 模板plugin-initital-state报错：路径依赖不对，每次编译后都需要手动改

### ISSUE THREAD

**Issue by diveDylan** [umijs/umi#6184]
## bug现象
ant design pro V5模板，`yarn start`后出现
![image](https://user-images.githubusercontent.com/28706090/109280518-1a60bc80-7856-11eb-9dbc-55da84e64cf9.png)

## 复现仓库
[复现仓库](https://github.com/diveDylan/umiBug-antdV5) 
或者直接如下操作即可复现
```bash
yarn create umi
## select antd pro v5
yarn add all
yarn start

```

## 版本
umi: ^3.2.14

## 尝试修正
plugin-initial-state/models/initialState.ts  ---> line 4
```diff
- import * as app from '../../../app';
+ import * as app from '../../../src/app';
```
umi.ts

```diff
## line 4
- import '../global.tsx';
+ import '../src/global.tsx';

## line 13
- require('../global.less');
+ require('../src/global.less');

```

**Comment by sorrycc** [comment]
重复 ISSUE，参考 https://github.com/umijs/umi/issues/6180#issuecomment-786493761
