### ISSUE TITLE
[Feature Request] 是否应该在开发环境下启用 memory 缓存？

### ISSUE THREAD

**Issue by yingzhiji** [umijs/umi#6185]
webpack 的缓存分为两种，filesystem 和 memory。现在开发环境和生产环境使用的都是 filesystem 缓存。
在开发环境使用 filesystem 缓存我能想到的好处是，每一次运行 umi dev 时都会从缓存目录读取，可以加快启动速度，但是开发环境下我们一般不关心第一次启动的速度，而更在意每次重新编译的速度，所以在开发环境下使用 memory 缓存是不是更合理一点，毕竟从内存中读取缓存会更快一点。
顺便提一句，webpack 默认在开发环境使用的也是 memory 缓存。

**Comment by sorrycc** [comment]
现在就是 memory cache，怎么判断出是 file cache 的？

**Comment by yingzhiji** [comment]
https://github.com/umijs/umi/blob/0b386752387f5aa19905ca69f3d6a0ccf3b10a59/packages/preset-built-in/src/plugins/features/webpack5.ts#L51

**Comment by yingzhiji** [comment]
从这行代码看出的：
https://github.com/umijs/umi/blob/0b386752387f5aa19905ca69f3d6a0ccf3b10a59/packages/preset-built-in/src/plugins/features/webpack5.ts#L51
webpack 文档：https://webpack.js.org/configuration/other-options/#cachetype

**Comment by sorrycc** [comment]
filesystem 是 memory 的增强，让二次启动时更快，不需要可通过环境变量关掉。

**Comment by jiyingzhi** [comment]
我想表达的是内存里的缓存肯定比硬盘的缓存要快，而开发环境我们一般不太关心首次启动的速度，而更关心修改代码后热更新的速度，所以我觉得开发环境使用 memory 更合理点。

**Comment by KellenHe** [comment]
> webpack 的缓存分为两种，filesystem 和 memory。现在开发环境和生产环境使用的都是 filesystem 缓存。 在开发环境使用 filesystem 缓存我能想到的好处是，每一次运行 umi dev 时都会从缓存目录读取，可以加快启动速度，但是开发环境下我们一般不关心第一次启动的速度，而更在意每次重新编译的速度，所以在开发环境下使用 memory 缓存是不是更合理一点，毕竟从内存中读取缓存会更快一点。 顺便提一句，webpack 默认在开发环境使用的也是 memory 缓存。

你好，请问怎么实现生产环境线上使用缓存，生产环境部署在docker里，每次部署都会清空。
