### ISSUE TITLE
[Bug] 添加 dynamicImport 后，页面render两次

### ISSUE THREAD

**Issue by programmer-yang** [umijs/umi#6186]
初始化 `yarn create @umijs/umi-app` 项目后，在 `.umirc.ts` 添加 `dynamicImport` 属性，然后进入不同的页面，会render两次

![image](https://user-images.githubusercontent.com/8612167/109286699-8eeb2980-785d-11eb-926d-4194f1ebae01.png)

重现地址：
https://github.com/programmer-yang/test-umi-double-render

## Context

- **Umi Version**: 3.3.9
- **Node Version**: v14.15.0
- **Platform**: mac

**Comment by handycode** [comment]
同遇到， 第一次进入渲染一次， 第二次再进入就会 render 两次。 
目前在 page组件上增加 React.memo 外包临时解决

**Comment by ISBN9527** [comment]
@handycode 在page上增加memo，每个组件加memeo？大佬

**Comment by ISBN9527** [comment]
我加上memo也没用

**Comment by handycode** [comment]
> @handycode 在page上增加memo，每个组件加memo？大佬

只在page的组件上加
