### ISSUE TITLE
[Feature Request] 支持 webpack profile

### ISSUE THREAD

**Issue by Rlagnl** [umijs/umi#6187]
## Background

目前工程编译效率不高，需要优化性能，但是缺乏抓手。
umi 版本： 2.12.2

## Proposal

可否暴露 webpack 的 profile 属性，方便分析编译过程呢？
目前情况是无法准确确定消耗的准确位置。
感谢。

## Additional context

* SPEED_MEASURE=CONSOLE umi dev 的结果如下，总耗时15秒，但 plugin 和 loader 的消耗远没有那么多。

`✔ Webpack
  Compiled successfully in 15.43s

 DONE  Compiled successfully in 15430ms                                                                                                     6:02:27 ├F10: PM┤

 SMP  ⏱
General output time took 15.43 secs

 SMP  ⏱  Plugins
WebpackBarPlugin took 0.059 secs
MiniCssExtractPlugin took 0.028 secs
IgnorePlugin took 0.004 secs
CopyPlugin took 0.002 secs
FriendlyErrorsWebpackPlugin took 0 secs
DefinePlugin took 0 secs
HotModuleReplacementPlugin took 0 secs
FilterCSSConflictingWarning took 0 secs

 SMP  ⏱  Loaders
babel-loader, and
@***/plugin took 0.619 secs
  module count = 1
`

* WEBPACK_PROFILE=verbose umi build 仅提供打包产物的大小，不足以完全定位问题。

**Comment by sorrycc** [comment]
提个 PR 吧。
