### ISSUE TITLE
[Bug] api.chainWebpack is not a function

### ISSUE THREAD

**Issue by Huhui-coder** [umijs/umi#6190]
在进行安装依赖时报错。
api.chainWebpack is not a function
TypeError: api.chainWebpack is not a function

版本为"@umijs/preset-ant-design-pro": "1.2.0",

**Comment by sorrycc** [comment]
umi 是 2 吧，umi 2 不能用 3 的插件。

**Comment by juxuny** [comment]
> 

我已经是 umi 3了，pnpm install 就会出这个错误

**Comment by qs12580** [comment]
有解决方案吗
