### ISSUE TITLE
[Bug] route bug

### ISSUE THREAD

**Issue by LeoHuiyi** [umijs/umi#6193]
1.![image](https://user-images.githubusercontent.com/8001457/109593757-85f3a400-7b4c-11eb-871f-591354f25c3c.png)
watchers 始终是空的 

2.
![image](https://user-images.githubusercontent.com/8001457/109594515-e505e880-7b4d-11eb-90f6-c1f162665466.png)生成routes能否加下缓存，使用约定routes, 文件一多 热更新有点慢

3.![image](https://user-images.githubusercontent.com/8001457/109594663-28f8ed80-7b4e-11eb-94b5-0657016c1cc6.png)
能否把event, path传到出来
![image](https://user-images.githubusercontent.com/8001457/109594987-a290db80-7b4e-11eb-93ee-cc5b1e45f72c.png)
api.onGenerateFiles arg里面判断是否更新

**Comment by sorrycc** [comment]
都是好建议，👍
