### ISSUE TITLE
[Bug] @umijs/runtime 没有输出报错信息，导致页面白屏控制台却没有报错，通过dynamic加载的页面都存在这个问题

### ISSUE THREAD

**Issue by lys623** [umijs/umi#6194]
如题描述。
代码见：https://github.com/umijs/umi/blob/cf8053c45e2bda56e1d90d48873151b3b0519578/packages/runtime/src/dynamic/loadable.js
![image](https://user-images.githubusercontent.com/4364314/109605767-a299d700-7b60-11eb-9a7a-a58eb93d1dd4.png)

代码中不知道为什么加了 // eslint-disable-next-line handle-callback-err，而没有输出error信息，很不友好。

当遇到页面白屏的时候，就不知所措，只能凭记忆和review代码寻找。

@umijs/runtime 版本3.2.28
umi 版本 3.2.28

**Comment by sorrycc** [comment]
给个复现。
