### ISSUE TITLE
[Bug] routes 中path  配制时 “/:id?”  这种写法不生效

### ISSUE THREAD

**Issue by tianzhiqing** [umijs/umi#6195]
通过routes path配制动太参数时将":id"做为参数传入了
![image](https://user-images.githubusercontent.com/2231669/109612101-2c9a6d80-7b6a-11eb-80c4-54b75452042b.png)

**Comment by kekeon** [comment]
路由配置的有问题吧，看看你前面是不是包含了"?参数1=1&pwa=false"， 正确方式：path: '/main/list/:id', [umi 动态路由](https://v2.umijs.org/zh/guide/router.html#%E5%8A%A8%E6%80%81%E8%B7%AF%E7%94%B1)

**Comment by Eliuak-wu** [comment]
> 路由配置的有问题吧，看看你前面是不是包含了“?参数1=1&pwa=false”，正确方式：path: '/main/list/:id', [umi 动态路由](https://v2.umijs.org/zh/guide/router.html#%E5%8A%A8%E6%80%81%E8%B7%AF%E7%94%B1)

![Snipaste_2024-04-22_16-39-14](https://github.com/umijs/umi/assets/77195650/6c729284-4638-44e3-8c1b-e01c8bf58720)
![Snipaste_2024-04-22_16-40-04](https://github.com/umijs/umi/assets/77195650/fe192096-5087-4e5f-8564-b711b19ebebf)
![Snipaste_2024-04-22_16-40-30](https://github.com/umijs/umi/assets/77195650/6acd3c9a-4563-479b-9a9f-890e66397d49)

我使用的是约定是路由，umi版本4.1.10,不知道为啥
