### ISSUE TITLE
配置 版本umi3   umi-plugin-apollo  报 Path must be a string

### ISSUE THREAD

**Issue by hqylss111** [umijs/umi#6202]
配置如下:
import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  routes: [
    { path: '/', component: '@/pages/index' },
  ],
  fastRefresh: {},
  publicPath: '/',
  plugins: [
    ['umi-plugin-apollo', {/*
      uri: 'https://my.endpoint.com/graphql',
      mock: true,
      hooksImportFrom: 'react-apollo-hooks',
      options: 'path/to/options/file',
    */}],
  ]
});

**Comment by sorrycc** [comment]
umi-plugin-apollo 是 umi 2 的插件，不适用于 umi 3。
