### ISSUE TITLE
Is it possible to setup a global AuthRoute for all routes?

### ISSUE THREAD

**Issue by leftstick** [umijs/umi#621]
As documented, AuthRoute shall be configured as below:

```javascript
export default {
  pages: {
    '/list': { Route: './routes/AuthRoute.js' },
  },
}
```

I am wondering if it is possible to give a global AuthRoute for all routes instead, and config each exception individually?

Let's say i have 20 routes, and 17 of them should be rendered via `<AuthRoute />`(which is my customized version), only the left 3 routes need plain `<Route />`, i think it would be good if something like below is supported:

**.umirc.js**

```javascript
export default {
 globalCustmizedRoute: './src/components/Auth/AuthRoute.js',
  pages: {
    '/a': { Route: null },
    '/b': { Route: null },
    '/c': { Route: null },
  },
}
```
`globalCustmizedRoute` would add `"Route": require('/path/src/components/Auth/AuthRoute.js').default` to each generated route.

And for three specified routes `/a`, `/b`, `/c`, the original `<Route />` component will be used instead because of `{ Route: null }`

**Comment by sorrycc** [comment]
You can set permissions routing programmatically.

First, install the plugin,

```bash
$ yarn add umi-plugin-routes
```

Then,

```js
export default {
  plugins: [
    ['umi-plugin-routes', {
      update(routes) {
        // add Route to route via code
        // e.g. routes[0].Route = './GlobalRoute.js';
        return routes;
      },
    }],
  ],
}
```

**Comment by leftstick** [comment]
Thanks

**Comment by CharishmaReddy30** [comment]
Can we perform routing on some condition?
