### ISSUE TITLE
[Bug] chrome浏览器断点调试网页, 步进不规则

### ISSUE THREAD

**Issue by codeoneline** [umijs/umi#6217]
您好, 我新学umi. 现在遇到如下困惑
## What happens?
新建工程,  我用页面显示`fee`和`timestamp`
 ```
 const [fee, setFee] = useState(0);
  const [timestamp, setTimestamp] = useState(0);

  const refreshFee = async function() {
    const tmpFee = await sdk.getFee()
    const tmpTS = await sdk.getTimeStamp()
    setFee(tmpFee)
    setTimestamp(tmpTS)
  }

  useEffect(() => {
    let timer = setInterval(refreshFee, 10000);
    return () => {
      clearInterval(timer)
    }
  }, [fee, timestamp])
```
修改`.umirc.js`文件,添加`devtool: 'source-map',`, 生成map文件,
然后,启动服务, 在chrome中断点调试, 发现代码跟踪异常, 乱跳.
而我用`create-react-app`创建的react程序, 断点处能正常跟踪测试

## Mini Showcase Repository(REQUIRED)

难以调试 refreshFee函数

[myumi](https://github.com/codeoneline/myumi)

正常调试 refreshFee函数

[myreact](https://github.com/codeoneline/myreact)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:  3.3.9 或 2.13.17
- **Node Version**: 14.15.1
- **Platform**: ubuntu

**Comment by sorrycc** [comment]
用 umi 3 也有问题吗？你给的示例是 umi 2 的。

**Comment by codeoneline** [comment]
> 用 umi 3 也有问题吗？你给的示例是 umi 2 的。
umi3也有一模一样的问题

**Comment by lianyzhou** [comment]
我也遇到这个问题了，感觉umi能支持，对开发者将是一个福音。毕竟现在写async代码的地方太多了。
现在一到async代码调试，就把await注释掉，有一次不小心忘记还原了，还造成一个线上事故。

**Comment by lianyzhou** [comment]
希望大佬能支持。

**Comment by lianyzhou** [comment]
解决了，配置这个。
![image](https://github.com/umijs/umi/assets/6295633/48f3195f-805f-468b-96cf-de8dff3291ac)
主要是不写ie:false，默认好像会支持ie11，导致async会被翻译，调试就有问题了。
