### ISSUE TITLE
umi build怎么去掉项目中的console.log

### ISSUE THREAD

**Issue by mastercbhw** [umijs/umi#622]
如题，开发环境下代码中会写一些console方便调试，打包的时候要一个一个删除太麻烦了

**Comment by sorrycc** [comment]
https://www.google.com/search?q=babel+plugin+strip+console&oq=babel+plugin+strip+console&aqs=chrome..69i57j0l2.4827j0j7&sourceid=chrome&ie=UTF-8

**Comment by weishijun14** [comment]
`npm i babel-plugin-transform-remove-console --save-dev `
confug,js:
`extraBabelPlugins: ['transform-remove-console'],`

**Comment by qq1073830130** [comment]
要在外面再加一层
extraBabelPlugins: [['transform-remove-console', { "exclude": [ "error", "warn"] }]],

**Comment by wtchaos** [comment]
uglifyJSOptions(opts) {
    opts.uglifyOptions.compress.drop_debugger = true;
    opts.uglifyOptions.compress.drop_console = true;
    return opts;
  },

**Comment by blueju** [comment]
> uglifyJSOptions(opts) {
> opts.uglifyOptions.compress.drop_debugger = true;
> opts.uglifyOptions.compress.drop_console = true;
> return opts;
> },

[umi 3 中已删除该配置项](https://umijs.org/zh-CN/docs/upgrade-to-umi-3)

**Comment by gujiwuqing** [comment]
经测验。。貌似现在没用

**Comment by leehomeok** [comment]
> 经测验。。貌似现在没用



> `npm i babel-plugin-transform-remove-console --save-dev `
> config,js:
> `extraBabelPlugins: ['transform-remove-console'],`

在umi3 版本貌似没用

**Comment by Amigosen** [comment]
不管用了，有人研究出来请@我

**Comment by hardmanhong** [comment]
fuck docs

**Comment by hardmanhong** [comment]
项目用的 esbuild 压缩，这是我的配置，版本4.0.11
```js
  jsMinifier: 'esbuild',
  jsMinifierOptions: {
    drop: ['console', 'debugger'],
  },
```
terser的应该是
```js
  jsMinifier: 'esbuild',
  jsMinifierOptions: {
    drop_console: true,
   drop_debugger : true
  },
```
