### ISSUE TITLE
升级到umi3.4开启webpack5 项目就挂了 请问需要怎么配置呢

### ISSUE THREAD

**Issue by whereiscode** [umijs/umi#6238]
## What happens?

升级后项目后运行start 跑不起来

## Mini Showcase Repository(REQUIRED)

<img width="1591" alt="image" src="https://user-images.githubusercontent.com/55313887/110562667-e904bc80-8184-11eb-87d0-9791fe74e356.png">

## How To Reproduce

是否有大神兼容过了 我参考下

## Context

- **Umi Version**: 3.4
- **Node Version**:v14.15.5
- **Platform**: MacOS

**Comment by sorrycc** [comment]
清下 babel 缓存，rm -rf src/.umi 试试。

**Comment by whereiscode** [comment]
@sorrycc 解决了  具体为什么我也不知道   我先创建一个新项目把代码复制进去  再复制回来就可以了
我1个月前升级umi也遇到类似的问题    也是这么解决的  具体问啥俺也不知道了    或许是有隐藏文件，感谢大佬回复，我去愉快的体验umi3.4+webpack5了  我心飞翔

**Comment by whereiscode** [comment]
@sorrycc 这个问题不是我一个人遇到哈   我朋友在外地 他的项目升级也是和我同样
