### ISSUE TITLE
[Bug] 自定义setlocale时，调用updater 国际化状态无法在不刷新页面的情况下更新

### ISSUE THREAD

**Issue by hopperhuang** [umijs/umi#6243]
## What happens?

此功能无法实现:https://umijs.org/zh-CN/plugins/plugin-locale#setlocale

为了在不刷新页面的可以更新国际化状态的情景，我像umi文档描述那样，自定义了getlocale和setlocale的方法，希望通过url的qs获取语言，并在不刷新页面的状态下，更新国际化状态。

代码如下：
src/app.js
```
/** 自定义语言获取逻辑 */
export const locale = {
  getLocale() {
    const { search } = window.location;
    const { locale: language = 'en-US' } = qs.parse(search, {
      ignoreQueryPrefix: true,
    });
    console.log(language, 'language');
    return language;
  },
  setLocale({ lang, updater }) {
    history.push(`/?locale=${lang}`);
    updater();
  },
};

```

结果:
qs 改变了，但是组件的语言并没有跟着变化
![image](https://user-images.githubusercontent.com/20254356/110593030-fe460f00-81b5-11eb-83a0-a271dcc719c9.png)

手动刷新一下（可见我的配置应该是无误的。）：
![image](https://user-images.githubusercontent.com/20254356/110593525-a5c34180-81b6-11eb-94c5-a2574dcc353f.png)

## Mini Showcase Repository(REQUIRED)
https://github.com/hopperhuang/umi_locale_bug

## How To Reproduce
```
git clone https://github.com/hopperhuang/umi_locale_bug
npm install
npm start
```

在首页点击change language的按钮即可复现

**Steps to reproduce the behavior:** 1. 2.

入上述所言

**Expected behavior** 1. 2.
点击按钮后，应该在不刷新页面的情况下，更新国际化状态。

![image](https://user-images.githubusercontent.com/20254356/110593525-a5c34180-81b6-11eb-94c5-a2574dcc353f.png)

在debug的过程中，我发现在初始化和页面刷新时，getlocale方法会被调用4次，
但是在setlocale 调用updater不刷新页面时，仅仅调用getlocale 1 次，是不是哪里出了问题，调用有问题。导致没法更新状态?
<img width="473" alt="截屏2021-03-10 下午3 40 21" src="https://user-images.githubusercontent.com/20254356/110593764-f33fae80-81b6-11eb-9ece-528765b8f927.png">

## Context

- **Umi Version**: 3.3.9
- **Node Version**: 14.15.0
- **Platform**: macOs Big Sur 11.0.1

**Comment by hopperhuang** [comment]
@sorrycc 分配个同学帮忙看看什么情况？谢谢啦。

**Comment by leftstick** [comment]
@hopperhuang  文档这个部分可能需要修改下，你代码这么改下:

```typescript
export const locale = {
  getLocale() {
    const { search } = window.location;
    const { locale: language = 'en-US' } = qs.parse(search, {
      ignoreQueryPrefix: true,
    });
    console.log(language, 'language');
    return language;
  },
  setLocale({ lang, updater }) {
    // 先 call updater
    updater();
   // 然后再改url
    history.push(`/?locale=${lang}`);
  },
};
```

这样应该就没问题了
