### ISSUE TITLE
windows创建项目报错

### ISSUE THREAD

**Issue by YC725968** [umijs/umi#6246]
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "@umijs/create-umi-app@3.4.0" with binaries:
      - create-umi-app
'C:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
error Command failed.
Exit code: 1
Command: C:\Program Files\nodejs\node-global\bin\create-umi-app
Arguments:
Directory: C:\Program Files\nodejs\node-global\bin
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

这个问题该怎么解决，安装就报错，无法进行下一步啊

- [ ]

**Comment by sorrycc** [comment]
看起来不是 umi 的问题，而是 yarn 的问题。
