### ISSUE TITLE
升级到umi3.4, webpack5 构建失败

### ISSUE THREAD

**Issue by codering** [umijs/umi#6248]
升级到 umi 3.4， 开启webpack5 。 
![image](https://user-images.githubusercontent.com/2271825/110626393-a0c4b900-81db-11eb-9de0-7dbdb2034693.png)

![image](https://user-images.githubusercontent.com/2271825/110730652-c8f3fc80-825b-11eb-8e96-66f17439ea4c.png)

![image](https://user-images.githubusercontent.com/2271825/110730838-24be8580-825c-11eb-8f33-be823b80388f.png)

删除node_modules ,  src/.umi  重建，问题依旧。

## Context

- **Umi Version**: 3.4
- **Node Version**: 12.18.3
- **Platform**: macos

**Comment by codering** [comment]
sorry，图贴错了，我晚点再改下。

**Comment by kokiy** [comment]
`ANALYZE=1 umi build` 在3.4版本也报错. 
![image](https://user-images.githubusercontent.com/15773714/110643189-ca3b1000-81ee-11eb-8f8c-0ba00b5b91f2.png)

**Comment by 104gogo** [comment]
@kokiy 我也遇到这个问题了

**Comment by codering** [comment]
我遇到的好像是这个问题 https://github.com/shellscape/webpack-manifest-plugin/issues/219
