### ISSUE TITLE
[Bug]  初始化依赖报错

### ISSUE THREAD

**Issue by 15167103105** [umijs/umi#6251]
## What happens?
按照官网教程，下载项目，通过yarn安装项目依赖，报错

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:"^3.4.0"
- **Node Version**:12.12.0
- **Platform**:darwin arm64

yarn-error.log 文件：
Arguments: 
  /Users/hetingting/.nvm/versions/node/v12.12.0/bin/node /Users/hetingting/.nvm/versions/node/v12.12.0/bin/yarn

PATH: 
  /Users/hetingting/.nvm/versions/node/v12.12.0/bin:/Users/hetingting/.oh-my-zsh/custom/plugins/git-open:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Yarn version: 
  1.22.10

Node version: 
  12.12.0

Platform: 
  darwin arm64

Trace: 
  Error: https://registry.npm.taobao.org/@ant-design/icons-svg/download/@ant-design/icons-svg-4.1.0.tgz: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (/Users/hetingting/.nvm/versions/node/v12.12.0/lib/node_modules/yarn/lib/cli.js:141289:19)
      at Object.onceWrapper (events.js:299:28)
      at ClientRequest.emit (events.js:210:5)
      at TLSSocket.emitRequestTimeout (_http_client.js:690:9)
      at Object.onceWrapper (events.js:299:28)
      at TLSSocket.emit (events.js:210:5)
      at TLSSocket.Socket._onTimeout (net.js:468:8)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

npm manifest: 
  {
    "private": true,
    "scripts": {
      "start": "umi dev",
      "build": "umi build",
      "postinstall": "umi generate tmp",
      "prettier": "prettier --write '**/*.{js,jsx,tsx,ts,less,md,json}'",
      "test": "umi-test",
      "test:coverage": "umi-test --coverage"
    },
    "gitHooks": {
      "pre-commit": "lint-staged"
    },
    "lint-staged": {
      "*.{js,jsx,less,md,json}": [
        "prettier --write"
      ],
      "*.ts?(x)": [
        "prettier --parser=typescript --write"
      ]
    },
    "dependencies": {
      "@ant-design/pro-layout": "^6.5.0",
      "@umijs/preset-react": "1.x",
      "umi": "^3.4.0"
    },
    "devDependencies": {
      "@types/react": "^17.0.0",
      "@types/react-dom": "^17.0.0",
      "@umijs/test": "^3.4.0",
      "lint-staged": "^10.0.7",
      "prettier": "^2.2.0",
      "react": "17.x",
      "react-dom": "17.x",
      "typescript": "^4.1.2",
      "yorkie": "^2.0.0"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by sorrycc** [comment]
ESOCKETTIMEDOUT，网络问题。
