### ISSUE TITLE
[Bug] 有些插件和loader使用了webpack的模块，多个webpack导致错误

### ISSUE THREAD

**Issue by duan602728596** [umijs/umi#6254]
## What happens?

有些插件和loader引入了webpack的模块（比如monaco-editor-webpack-plugin、worker-loader），会有`The 'compilation' argument must be an instance of Compilation`错误。这个错误是由存在多个webpack引起的。   

目前临时的解决方案是[@bbkkbkk/umi-webpack5-export](https://www.npmjs.com/package/@bbkkbkk/umi-webpack5-export)，重定向webpack模块，导出@umijs/deps的webpack5 bundle，并且导出所有插件，并保证和webpack5的目录一致。在我的项目上测试，可以正确编译发版。

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/duan602728596/umi-3.4-demo
worker-loader里面使用了webpack的插件，启动会导致问题

## How To Reproduce

**Steps to reproduce the behavior:**
 1. 运行`npm run start`
 2. 报错 `The 'compilation' argument must be an instance of Compilation`

**Expected behavior**

## Context

- **Umi Version**: v3.4.0
- **Node Version**: v14.15.1
- **Platform**:

**Comment by sorrycc** [comment]
worker-loader 在 #6253 修了。

**Comment by sorrycc** [comment]
monaco-editor 有问题再提个 issue 给复现吧。

**Comment by yuxiang2629** [comment]
> worker-loader 在 #6253 修了。
麻烦给个配置 示例
