### ISSUE TITLE
3.4.0 版本 chainWebpack  无法拿到less-loader等loader

### ISSUE THREAD

**Issue by fatehuanchen** [umijs/umi#6255]
const lessModulesUses = config.module.rule('less').oneOfs.get('css-modules').uses;

const LOADERS = [
            'style-loader',
            'extract-css-loader',
            'css-modules-typescript-loader',
            'css-loader',
            'postcss-loader',
            'less-loader',
          ];

这其中  extract-css-loader， css-modules-typescript-loader，less-loader等几个loader 无法拿到，并且less-loader被改名为绝对路径的umi/deps/compiled/less-loader 

这样无法自定义这些loader ，请问如何解决？

**Comment by sorrycc** [comment]
要如何自定义？

**Comment by fatehuanchen** [comment]
config.module.rule('less').exclude.add(/\/@bit\/(.+)\.less(\?.*)?$/);
 const lessModulesUses = config.module.rule('less').oneOfs.get('css-modules').uses;
   if (lessModulesUses) {
          const rule = config.module.rule('bit-less').test(/\/@bit\/(.+)\.less(\?.*)?$/);

          const LOADERS = [
            'style-loader',
            'extract-css-loader',
            'css-modules-typescript-loader',
            'css-loader',
            'postcss-loader',
            'less-loader',
          ];

          LOADERS.forEach((loaderName) => {
            const loaderObj = lessModulesUses.get(loaderName);
            if (loaderObj) {
              rule
                .use(loaderName)
                .loader(loaderObj.get('loader'))
                .options(loaderObj.get('options'));
            }
          });
        }
这样？ 自定义下node_modules 下的部分库进行less编译

**Comment by sorrycc** [comment]
没 get 到你的问题。

**Comment by mybedhome** [comment]
有同样的问题，node_modules下的第三方组件库的less样式无法编译

**Comment by ycjcl868** [comment]
让 node_modules 的 less 文件走 CSS Modules 编译
