### ISSUE TITLE
[Bug]开启dynamicImport时，ssr生成的文件注入css不全的bug

### ISSUE THREAD

**Issue by ikun** [umijs/umi#6259]
当页面依赖 b.css 时，生成的代码有 `p_detail_index.css` 和 `p_index_index~p_detail_index.css`，此时 `p_index_index~p_detail_index.css` 希望也可以注入到html中，但是只有  `p_detail_index.css` 被注入了

问题代码：

```
manifestChunk.startsWith(chunk)
```

问题代码所在位置：

https://github.com/umijs/umi/blob/36c0a333ebc9650a6f899b7034939f9039633d6f/packages/preset-built-in/src/plugins/features/ssr/templates/utils.ts#L88

**Comment by ikun** [comment]
还有个问题，生成的文件名长度好像有限制。

如果文件名被截断了，也会出现找不到的问题，就不会被引入到html里面了。

**Comment by ycjcl868** [comment]
也有问题，不能 indexOf() 取，这样会加载不必要的 chunks

**Comment by ikun** [comment]
```
/(^|~)p_detail_index/.test('p_index_index~p_detail_index.css');
```

但是asset-manifest中的key的文件名被截断了，还是会有找不全的问题

**Comment by xue-chao** [comment]
同样遇到了这个问题

**Comment by xue-chao** [comment]
> 也有问题，不能 indexOf() 取，这样会加载不必要的 chunks

有没有地方能标记一下页面用到的所有js和css资源，通过asset-manifest文件名取终归不是办法

**Comment by ycjcl868** [comment]
这个我看下，怎么找到确定的chunks

**Comment by ycjcl868** [comment]
来一个复现案例，测试下

**Comment by ikun** [comment]
> Hello @ikun. In order to facilitate location and troubleshooting, we need you to provide a realistic example. Please forking these link [codesandbox umi](https://codesandbox.io/s/umi-2d4js?file=/src/pages/index.tsx) or using `yarn create @umijs/umi-app` to create and upload it to your GitHub repository.
> 
> 你好 @ikun, 为了方便定位和排查问题，我们需要你提供一个重现实例，请提供一个尽可能精简的链接 [codesandbox umi](https://codesandbox.io/s/umi-2d4js?file=/src/pages/index.tsx) 或使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

改了一下

**Comment by 104gogo** [comment]
可以在打包完成之后，手动修改umi.server.js里面的html模板
