### ISSUE TITLE
[Bug] 升级 umi 3.4.2 后开启 webpack 5，运行报错

### ISSUE THREAD

**Issue by BBBigCat** [umijs/umi#6277]
## What happens?

本地 umi 项目从 3.2.25 升级到 3.4.2 后，开启 webpack 5 后启动项目，报错

![image](https://user-images.githubusercontent.com/31910599/111252988-49946d80-864d-11eb-88dc-d364280a48fd.png)

## Mini Showcase Repository(REQUIRED)

这里先提供我搜到到一些记录，看能否提供帮助

在查阅了 webpack 5 的一些 issue 后，发现问题可能是 babel 版本的问题，有的解决办法是把 babel 全部升级到 7.12.x

- [[5.0.0] Several (Module not found) errors in @babel packages after upgrade to webpack 5 ](https://github.com/webpack/webpack/issues/11636#issuecomment-708996327)
- [Update babel to 7.12.x](https://github.com/sghall/react-compound-slider/pull/126)
- [webpack 5.0.0-beta.30 Module not found: Error: Can't resolve '../../core-js/object/define-property'](https://github.com/webpack/webpack/issues/11636#issuecomment-708996327)

反观自己的项目，我只对 umi 进行了升级，lock 文件中对 babel 还有很多是低版本，不知道是不是这个问题，查看 umi/deps 依赖，babel 是被升级到了 7.12.x 以上，但是是在 devDependencies 中

> umi/deps -> package.json
![image](https://user-images.githubusercontent.com/31910599/111253561-5b2a4500-864e-11eb-915b-21706f8021bc.png)

> 本地项目 yarn.lock
![image](https://user-images.githubusercontent.com/31910599/111253582-65e4da00-864e-11eb-9074-18cdeb238254.png)

不知道是不是这里可以修改下放在 dependencies 中，然后使安装项目直接升级 babel 依赖

如果不是的这里的话，可以看下是其他的什么问题

## Context

- **Umi Version**: 3.4.2
- **Node Version**: 12.18.1
- **Platform**: macOS Big Sur 11.0.1

**Comment by BBBigCat** [comment]
升级后开启 webpack5 的另一个问题我提了个 [pr](https://github.com/umijs/deps/pull/1) 在 umi/deps 里

**Comment by sorrycc** [comment]
lock 文件删了试试？需确保 @umijs/babel-preset-umi 依赖的 @babel/runtime 是最新的。

**Comment by BBBigCat** [comment]
> lock 文件删了试试？需确保 @umijs/babel-preset-umi 依赖的 @babel/runtime 是最新的。

lock 删过了。刚看了下，本地项目里确实是 @umijs/babel-preset-umi 下的 @babel/runtime 版本有点低，是 7.10.4 的，这里的话，我直接升级 @umijs/babel-preset-umi 吗？

**Comment by BBBigCat** [comment]
> lock 文件删了试试？需确保 @umijs/babel-preset-umi 依赖的 @babel/runtime 是最新的。

又删除了一遍 lock 文件，再 yarn 就没有报错了。多谢🙏

**Comment by jiangxiaoqiang** [comment]
能解释下是什么愿意么？
