### ISSUE TITLE
umi使用国际化，提示'umi/locale'不能识别

### ISSUE THREAD

**Issue by chenleyiduo** [umijs/umi#6283]
import {   formatMessage } from 'umi/locale';
提示'umi/locale'不能识别

umi+antd的项目，
umi:3.x
antd:3.x

**Comment by leftstick** [comment]
使用官方指导方法，创造性使用可能会有问题。

官方指导意见，参考：

![Screen Shot 2021-03-17 at 10 47 10](https://user-images.githubusercontent.com/1059956/111406989-267dc280-870e-11eb-931d-40ca2f0f3bd6.png)

**Comment by chenleyiduo** [comment]
umi版本问题
