### ISSUE TITLE
umi ssr 开启之后，运行报错： [SSR] TypeError: Reflect.metadata is not a function

### ISSUE THREAD

**Issue by peterzhai** [umijs/umi#6284]
umi ssr 开启之后，运行报错： [SSR] TypeError: Reflect.metadata is not a function
请问什么情况会报 这个错误呢？怎么解决？

**Comment by leftstick** [comment]
提供有效的可稳定复现问题的demo project，以及复现步骤

**Comment by peterzhai** [comment]
刚发现凡是使用了@connect @createForm 修饰符都会报TypeError: Reflect.metadata is not a function。如果直接使用connect()(组件),creatForm()(组件)就不会有问题。

**Comment by hanwenbo** [comment]
我怀疑你升级了项目，如果是，那这个就是老bug了，  你重新弄个umi项目 然后再把代码一点点复制过去  就没问题了   再或者你就是对一下新版本和旧版本文件的差异 

每次升级umi都会报这个错误的  至少我的

**Comment by peterzhai** [comment]
@hanwenbo 有可能。这个项目之前是js项目没用ts。现在的版本是
 umi@3.4.2 
 node v14.12.0
 mac

**Comment by peterzhai** [comment]
https://codesandbox.io/s/quiet-violet-hs505?file=/src/pages/index.tsx
麻烦大家看看

**Comment by hanwenbo** [comment]
@peterzhai 用umi命令行新创建个项目 然后把代码一点点复制进去试试

**Comment by Hankeheng** [comment]
example中的ssr-koa中的demo，首页改成如下代码，打包后回复现这个错误。
复现的原因是加上了constructor。

import React, { Component } from 'react';
import { connect } from 'dva';

@connect(({ product }) => ({
  product,
}))
class Product extends Component {
  constructor(props) {
    super(props);
    this.state = {
      name: 'hkh',
    };
  }
  componentDidMount() {}

  render() {
    const { name } = this.state;
    return (
      <React.Fragment>
        <div>首页</div>
        <div>{name}</div>
      </React.Fragment>
    );
  }
}
export default Product;
