### ISSUE TITLE
[Feature Request] umi国际化，在非组件的ts中怎么使用？？useIntl必须使用在类组件，injectIntl必须在class中使用。

### ISSUE THREAD

**Issue by chenleyiduo** [umijs/umi#6286]
## Background

umi国际化，在非组件的ts中怎么使用？？useIntl必须使用在类组件，injectIntl必须在class中使用。
## Proposal

希望提供在ts中使用国际化的方法，并且可以根据语言变化

## Additional context

umi3.x版本

**Comment by ycjcl868** [comment]
用 `getIntl`
