### ISSUE TITLE
[Bug] favicon配置都是按照文档配置的，图标就是没有

### ISSUE THREAD

**Issue by ISBN9527** [umijs/umi#6295]
## What happens?

favicon配置都是按照文档配置的，图片就是没有；
跟录下创建public / assets,但是本地标签页就是没有图标

## How To Reproduce

![image](https://user-images.githubusercontent.com/30942709/111595847-84420580-8807-11eb-867d-5a1f6695e4e8.png)
![image](https://user-images.githubusercontent.com/30942709/111595885-8dcb6d80-8807-11eb-837b-65b9d82f66f8.png)
![image](https://user-images.githubusercontent.com/30942709/111736307-8b751c00-88b8-11eb-8d2c-6c0efe1d8274.png)

## Context

- **Umi Version**: 3.4.2
- **Node Version**:  15.4.0
- **Platform**:

**Comment by ISBN9527** [comment]
有哪位大佬能拯救下我吗？

**Comment by leftstick** [comment]
需要可复现repo

**Comment by ISBN9527** [comment]
@leftstick 复现链接：https://codesandbox.io/s/weathered-framework-0br83?file=/.umirc.ts

**Comment by ISBN9527** [comment]
已解决

**Comment by lling2** [comment]
请问怎么解决的？我按照这个方式还是没有出来效果

**Comment by helloyoucan** [comment]
> 已解决

请问是如何解决的？

**Comment by TwistedLC** [comment]
> 

一样的问题，想问一下怎么解决的

**Comment by ISBN9527** [comment]
> > 
> 
> 一样的问题，想问一下怎么解决的

清除缓存，重新yarn start
