### ISSUE TITLE
umi文档中关于路由描述属性exact的默认值为true

### ISSUE THREAD

**Issue by zsn6034** [umijs/umi#6296]
## What happens?
umi文档中关于路由描述属性exact的默认值为true：https://umijs.org/zh-CN/docs/routing#exact

## Mini Showcase Repository(REQUIRED)
[文档中](https://umijs.org/zh-CN/docs/routing#exact) 说exact默认值为true，但是实际用起来发现默认值(即不写的情况下)应该是false，并没有完成路由的严格匹配

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
`
export default {
  routes: [
    { path: '/one', },  // url 为 /one/two 时匹配成功
    { path: '/one', exact: true },  // url 为 /one/two 时匹配失败
  ],
}
`
**Expected behavior** 1. 2.
`export default {
  routes: [
    { path: '/one', }, // url 为 /one/two 时匹配失败
    { path: '/one', exact: false }, // url 为 /one/two 时匹配成功
  ],
}`

## Context

- **Umi Version**: 3.4.2
- **Node Version**: 12.19.0
- **Platform**: macOS 10.15.7

**Comment by jc1102** [comment]
没有人回答吗
