### ISSUE TITLE
[Bug] 使用 GitHub Action 的时候 @ 无法识别

### ISSUE THREAD

**Issue by G233** [umijs/umi#6298]
## What happens?
在 github action 中  build 的时候报错(生成静态网站)，本地构建的时候是没问题的

![image](https://user-images.githubusercontent.com/39009225/111604989-dcc9d080-8810-11eb-8840-aad661c750cd.png)

- **Umi Version** : 3.3.9
- **Node Version** : 14

**Comment by AlisonZXQ** [comment]
请问怎么解决的

**Comment by G233** [comment]
后来发现其实不是 @ 的问题，而是本地编译的时候，路由路径是大小写不敏感的，而在 GA 中则为大小写敏感，我把路径大小写写正确了就好了

**Comment by AlisonZXQ** [comment]
> 后来发现其实不是 @ 的问题，而是本地编译的时候，路由路径是大小写不敏感的，而在 GA 中则为大小写敏感，我把路径大小写写正确了就好了

是的 我也发现了 是大小写文件名的问题
