### ISSUE TITLE
求问如何切换主题色

### ISSUE THREAD

**Issue by gujiwuqing** [umijs/umi#6304]
大佬们 求问如何动态切换主题色 试了umi的各种方法 不得行
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by kisoua** [comment]
```js
config = {
 theme: {
   '@primary': red
 }
}

```

配置里面加这个

**Comment by wangchenyi1996** [comment]
在umijs中切换 确实不是很好实现，我之前用cra实现过

**Comment by banchichen** [comment]
调研了一圈，发现没有简单的方案，打算采用CSS Variables来做了，试了下这个插件，小而美
https://github.com/wxul/umi-plugin-theme-switch
