### ISSUE TITLE
[Bug] css中设置的字体打包后无法加载

### ISSUE THREAD

**Issue by 544751779** [umijs/umi#6305]
在src/global.css中定义
```
@font-face {
	font-family: 'DS-Digital';
	src: url('/font/DS-DIGIB.TTF');
}
```
打包后http加载字体的路径为  http://xxx.com/font/xxxx.ttf

**Comment by xiaohuoni** [comment]
可以尝试使用别名看看是否有效，https://umijs.org/zh-CN/docs/upgrade-to-umi-3#css-%E9%87%8C%E5%BC%95%E7%94%A8%E5%88%AB%E5%90%8D%E6%88%96%E4%B8%89%E6%96%B9%E5%BA%93
