### ISSUE TITLE
[Feature Request] cache last right yarn.lock

### ISSUE THREAD

**Issue by superlbr** [umijs/umi#6310]
## Background

umi build could cause error because of upgrade of dep

## Proposal

umi could try again with last right yarn.lock, instead of lock dep version

**Comment by sorrycc** [comment]
What's the problem?

**Comment by superlbr** [comment]
white screen only with loading txt after upgrade to umi@3.4.3 yesterday.
rollback to umi@3.4.2, but build error.
finally copy last right yarn.lock.

**Comment by sorrycc** [comment]
> white screen only with loading txt after upgrade to umi@3.4.3 yesterday.

Please provide the detail or the reproduceable example, so we can fix it.

> rollback to umi@3.4.2, but build error.

umi have lock it's deps, the release of 3.4.3 should not broken 3.4.2, have you found the cause of the problem?

**Comment by superlbr** [comment]
>  have you found the cause of the problem?

yes, @ant-design/icons 4.5.0 > 4.6.2

**Comment by superlbr** [comment]
well, in my opinion:
1. umi know yarn.lock or package-lock.json which is using, and what happen to package.json
2. umi could make a distinction between umi's family dep and other dep，so lock umi's family could be safe, one copy is enough, easy to rollbak if umi's build error. Uncontroller part is other dep.
3. like cache, extend it's expire time when build once
4. cache last three prod yarn.lock, use command like `last_try =1 umi build` and cut it's expire time
5. so it would be a right one to build
