### ISSUE TITLE
[Bug] umi@3.4.4 process is not defined

### ISSUE THREAD

**Issue by jiechud** [umijs/umi#6318]
`umi@3.4.4` 编辑进度会出现 99%， 访问出现 ` process is not defined`

编译进度截图
![image](https://user-images.githubusercontent.com/9709396/111976122-43662b80-8b3c-11eb-8657-2a518b7f49ff.png)

访问浏览器报错
![image](https://user-images.githubusercontent.com/9709396/111976171-511bb100-8b3c-11eb-95d0-713b8a4519cf.png)

**Comment by muyiyang1** [comment]
@sorrycc

**Comment by jiechud** [comment]
![image](https://user-images.githubusercontent.com/9709396/112105941-fd66a180-8be7-11eb-81f5-75d949760362.png)

@sorrycc 麻烦在加下 Stream 模块吧

**Comment by sorrycc** [comment]
为啥会依赖到 stream，我故意没加的，要不要考虑换个依赖，https://github.com/umijs/umi/blob/e3f1c426516ab15ceacd338310233cffb6c0fbfa/packages/bundler-webpack/src/getConfig/getConfig.ts#L622

**Comment by jiechud** [comment]
https://github.com/mwilliamson/mammoth.js  这个库需要

![image](https://user-images.githubusercontent.com/9709396/112114699-51c34e80-8bf3-11eb-9d1a-859a3b3c0cba.png)

**Comment by jiechud** [comment]
@sorrycc 还是希望能放开stream 模块
