### ISSUE TITLE
[Feature Request] 支持检测 `jest.config.ts` 与 暴露运行时 `jest.config`

### ISSUE THREAD

**Issue by aquariuslt** [umijs/umi#6319]
## Background

此 issue 包含2点述求:

目前使用 `umi-test` 命令执行单元测试，`@umijs/test` 会将项目目录下的 `jest.config.js` 与 `createDefaultConfig()` 生成的 jest 配置进行 merge，作为 jest 的运行时配置。

希望支持以下功能 

1. 支持 `jest.config.ts` 的读取与 merge (Jest@26 已支持 `jest.config.ts` )
2. 支持暴露运行时用到的 jest.config 内容到某特定路径pattern 下(目前使用 Jetbrains 系 IDE 进行项目开发，希望使用 IDE 支持的 Jest Plugin 方便的对某个 testsuite/testcase 进行 run/debug,  但由于 `jest.config` 无法自动从现有项目路径中自动发现而无法成功运行)

### 1. 添加对 `jest.config.ts` 支持。

在 https://github.com/umijs/umi/blob/2de577ed78c2df2a2a16933e97b77920366fcf6c/packages/test/src/index.ts#L34
新增对 `jest.config.ts`的检测，检测顺序为

```
jest.config.ts
jest.config.js
package.json 中的 jest 字段
```

### 2. 支持暴露 jest.config 到特定路径/路径表达式中

搜索了下文档和issue，没有类似 `eject` 配置的设计，个人希望能暴露到项目构建时的 `src/.umi` 下的某个文件，或遵循框架设计的其他位置。

## Additional context

无

**Comment by chen-jianpeng** [comment]
请问配置文件最终被暴露到什么位置了？
