### ISSUE TITLE
[Bug] umii@3.4.4 启动就报错

### ISSUE THREAD

**Issue by suedar** [umijs/umi#6321]
## What happens?

umii@3.4.4 启动就报错

## How To Reproduce

``` js
./node_modules/umi/dist/index.esm.js
Module not found: Can't resolve '@@/core/umiExports' in '/xxxxxxx/node_modules/umi/dist'
```

## Context

- **Umi Version**: 3.4.4
- **Node Version**: v14.16.0
- **Platform**: mac
- **antd**: 4.14.0

**Comment by zhouJiecode** [comment]
我也遇到了这个问题，请问怎么解决的？
