### ISSUE TITLE
[Bug] webpack5开起后，启动项目报错

### ISSUE THREAD

**Issue by muyiyang1** [umijs/umi#6322]
## What happens?
![image](https://user-images.githubusercontent.com/48230500/112090041-c2f00b00-8bcd-11eb-89df-0f5588e6586a.png)

![image](https://user-images.githubusercontent.com/48230500/112090018-b8357600-8bcd-11eb-8cf8-c59ae1ca14ed.png)

## Context

- **Umi Version**:3.4.4
- **Node Version**:14.15.0
- **Platform**:macOs big sur 1.2.3

**Comment by muyiyang1** [comment]
删除lock 和.umi文件夹 都试过

**Comment by superlbr** [comment]
检查下react-dnd相关依赖，有break change

**Comment by sorrycc** [comment]
react-dnd 升到最新，低版本不支持 webpack 5。
