### ISSUE TITLE
[Bug] UnhandledPromiseRejectionWarning: Error: not support Intl or zh-CN language.

### ISSUE THREAD

**Issue by GreatAuk** [umijs/umi#6323]
## What happens?
运行 `yarn openapi`

报错 `UnhandledPromiseRejectionWarning: Error: not support Intl or zh-CN language.`

## Mini Showcase Repository(REQUIRED)
`yarn create umi myapp` 生成的原始项目就能复现

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: "umi": "^3.4.0", "@umijs/openapi": "^1.1.14",
- **Node Version**: 12.13.1
- **Platform**: mac os

**Comment by sorrycc** [comment]
@chenshuai2144 看下。

**Comment by chenshuai2144** [comment]
也是node版本的问题 我换个库吧

**Comment by GreatAuk** [comment]
哈哈，两个仓库的页面同时开关， issue 不小心提错仓库了，应该在 `antd pro ` 合适点

**Comment by crashsol** [comment]
这个问题是怎么解决的呢，安装node14？
