### ISSUE TITLE
[Bug] yarn install error with umi-webpack-bundle-analyzer

### ISSUE THREAD

**Issue by XiaoYouEr** [umijs/umi#6324]
![image](https://user-images.githubusercontent.com/33562582/112095910-52022080-8bd8-11eb-8b9b-3fdb1cfb2fff.png)

如图所示，从旧项目中复制一份代码出来，无法正常使用umi-webpack-bundle-analyzer；注释下面两行代码才能正常运行，尝试删除原项目的node_moduels包重新拉取依赖，同样会出现此问题
```
let BundleAnalyzerPlugin = require("umi-webpack-bundle-analyzer").BundleAnalyzerPlugin;
const CompressionWebpackPlugin = require("compression-webpack-plugin");
```

**Comment by sorrycc** [comment]
不要手动依赖  umi-webpack-bundle-analyzer 并且不依赖他。
