### ISSUE TITLE
umi 3.0配置了proxy 接口报错404 为什么呀？

### ISSUE THREAD

**Issue by jingchenlucky** [umijs/umi#6328]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by jingchenlucky** [comment]
![image](https://user-images.githubusercontent.com/46475722/112159727-6cfa8200-8c24-11eb-9a0e-0b893128dc34.png)

**Comment by jingchenlucky** [comment]
![image](https://user-images.githubusercontent.com/46475722/112159830-84d20600-8c24-11eb-86c7-252730686c8d.png)

**Comment by uWydnA** [comment]
如何解决的？我也遇到了同样的问题
