### ISSUE TITLE
自定义404 未生效

### ISSUE THREAD

**Issue by Rpeanut** [umijs/umi#633]
dev 下我输入错误地址没有触发自定义的404页面，而是显示： umi development 404 page....
然后我 build 后 本地起个 server访问 dist 下的   @@html，404也没有生效，然后我有部署到测试环境也没有生效。用的版本如下
   "dva": "^2.3.0",
    "umi": "^1.3.8",
    "umi-plugin-dva": "^0.9.0"

**Comment by Rpeanut** [comment]
@sorrycc 云谦大大麻烦看下，多谢

**Comment by yutingzhao1991** [comment]
https://umijs.org/guide/add-404-page.html

> 开发模式下，umi 会添加一个默认的 404 页面，但你仍可通过精确地访问 /404 来验证 404 页面。

另外你 build 之后本地起一个 server 需要你这个 server 把所有的请求都指向构建出来的 html 才行。

**Comment by jiahangLee** [comment]
@Rpeanut 你好，我前后端都部署到测试的tomcat上，一切顺利，可以通过 '/404' 访问到自定义的404.html(通过设置exportStatic: {}将js转的html)，但是输入一个不存在的url仍然无法自动跳到自定义的404.js,问下和你这个是不是一个问题，有没有解决方案，还是说还要手动设置404路由

**Comment by yutingzhao1991** [comment]
你需要让你的所有的请求都要路由到 umi 生成的 html。

**Comment by jiahangLee** [comment]
@yutingzhao1991 我umi1.0的route.js是自动创建的，难道要手写route.js,请先生教我

**Comment by wanyuwen** [comment]
同求方案，也是遇到同样的问题
