### ISSUE TITLE
动态菜单访问问题

### ISSUE THREAD

**Issue by lizhongkun** [umijs/umi#6333]
项目初次加载时，后台会有校验，如果没有token后台只返回一个登录的路由，等用户登录成功后，再去请求该用户对应权限的路由数组，这时怎么把这个数组添加到umi管理的路由里面去？

**Comment by xiaohuoni** [comment]
把路由信息和菜单信息分清楚来。你权限控制的是用户访问菜单，不是项目编译文件。

**Comment by lizhongkun** [comment]
我理解菜单是由路由生成的，我应该怎么动态修改菜单呢

**Comment by lizhongkun** [comment]
@xiaohuoni

**Comment by lizhongkun** [comment]
@xiaohuoni 项目没有使用本地的routes，全是后台配置的，页面也是后台配置的。在项目初始化的时候，前端会动态生成路由和菜单

**Comment by xiaohuoni** [comment]
我觉得这不是一个难以理解的点，但是好像很多人有这个疑问。先开着吧。看看有没有其他朋友能够很好的描述。

**Comment by xiaohuoni** [comment]
这么说吧，菜单可以动态。路由一定是静态的，一定是提前写死的，不管是路由配置还是约定式。他都是要穷尽你项目中的可访问路由的。然后菜单才是可选的，比如你只给A用户显示三个路由菜单。然后在菜单权限这里判断，用户当前访问路由，不在这个权限列表中时，跳转到403页面。

**Comment by lizhongkun** [comment]
@xiaohuoni
1、本地使用umijs自定义了一个项目模板，这个项目模板里面没有页面、也没有路由;
2、有另一个开发平台，这个平台可以配置页面的路由结构和页面的JSON（这个JSON是生成页面使用）;
3、在项目模板初始化的时候，我们会在app.tsx里面，把我们在开发平台上配置的路由结构和JSON，分别生成umijs的路由和页面；
也就是说，如果有10个项目，你只要在开发平台把路由结构和页面JSON配置出来，就可以通过一个项目模板生成10个不同项目；
上面3个步骤已经全部实现，且项目模板里面没有写死“静态路由”；

**Comment by xiaohuoni** [comment]
没懂，有demo吗？

**Comment by lishaoh** [comment]
@xiaohuoni 你的意思是服务器返回的菜单只是单一控制左侧菜单是否显示？访问那些没有显示的菜单时，需要手动判断一下是否存在于权限列表中？

**Comment by xiaohuoni** [comment]
@lishaoh 我一直觉得需要一个类似路由守卫的东西 https://angular.cn/api/router/CanActivate

**Comment by lishaoh** [comment]
@xiaohuoni 目前我的处理方式是直接在onPageChange方法里面对访问路由验证权限，如果没有直接跳转到/404页面

![image](https://user-images.githubusercontent.com/20917295/116496000-a59e1300-a8d6-11eb-8e31-ba58f06362e3.png)

![image](https://user-images.githubusercontent.com/20917295/116496023-b2226b80-a8d6-11eb-8b29-467e3c243ca9.png)

**Comment by xiaofuliang** [comment]
@lishaoh 请问你这菜单的数据是从InitialState里面拿 的吗，然后通过menuDataRender配置的吗

**Comment by hyzx86** [comment]
@sorrycc  建议更新下文档。。不少人在这个问题上浪费时间呀。。

**Comment by komorebi-cqd** [comment]
> @xiaohuoni 目前我的处理方式是直接在onPageChange方法里面对访问路由验证权限，如果没有直接跳转到/404页面
> 
> ![image](https://user-images.githubusercontent.com/20917295/116496000-a59e1300-a8d6-11eb-8e31-ba58f06362e3.png)
> 
> ![image](https://user-images.githubusercontent.com/20917295/116496023-b2226b80-a8d6-11eb-8b29-467e3c243ca9.png)

这个onPagechange会先执行，动态菜单还没请求过来，导致初始化里面的动态菜单是空，第一次对比就没用了

**Comment by xXAvoraXx** [comment]
> @sorrycc 建议更新下文档。。不少人在这个问题上浪费时间呀。。

https://github.com/ant-design/ant-design-pro/discussions/10898
