### ISSUE TITLE
请问一下umi3 以后如何配置public 目录不压缩呢

### ISSUE THREAD

**Issue by duwei54** [umijs/umi#6340]
如题: public目录下放了一些额外的原生js.希望在打包的时候这块不压缩.COMPRESS=none会导致全部都不压缩.不配置COMPRESS=none 全部都会压缩.
ps: 放discussion没人理啊

**Comment by xiaohuoni** [comment]
我记得这个好像是原样 copy 的？但是在代码中引入的话，会被打包。你应该要在 html 的模版中使用相对路径引入这些额外的 js。不能在项目中使用如 import A from './public/a' 这种方式。

**Comment by duwei54** [comment]
@xiaohuoni 我用了umi配置中的`copy` ,也试过了chainWebpack中配置`copy-webpack-plugin`.但是都不行.  public下放了一个独立angular应用,在项目中没有应用.打包编译后无法执行. 😕

**Comment by vnimy** [comment]
同样的问题，public里面的js文件打包后发给客户居然被客户电脑上的杀毒软件检测出病毒了。那个文件本来是一个加密过的，打包之后被处理过的加密js居然还原了部分的变量名称，也不知道客户那杀毒软件什么毛病，js也能检测出病毒，搞得大家都很尴尬。

**Comment by zjjjavascript** [comment]
我现在document.ejs中引用，也会自动压缩的，headScripts也是同样的情况，没有个配置项可以制定某个js文件或者目录下不压缩吗

**Comment by citrusjunoss** [comment]
> 我现在document.ejs中引用，也会自动压缩的，headScripts也是同样的情况，没有个配置项可以制定某个js文件或者目录下不压缩吗

为啥我的ejs 饮用直接不生效呢。
![image](https://user-images.githubusercontent.com/18432488/124536806-3fd88500-de4b-11eb-8a5e-34dd675cf47b.png)

**Comment by zjjjavascript** [comment]
> > 我现在document.ejs中引用，也会自动压缩的，headScripts也是同样的情况，没有个配置项可以制定某个js文件或者目录下不压缩吗
> 
> 为啥我的ejs 饮用直接不生效呢。
> ![image](https://user-images.githubusercontent.com/18432488/124536806-3fd88500-de4b-11eb-8a5e-34dd675cf47b.png)

src写错了 应该是
`<script src="<%= context.config.publicPath +'TCaptcha.js'%>"></script>`

**Comment by zhfish** [comment]
mark，同问

**Comment by pxim** [comment]
同问

**Comment by mjkohoh** [comment]
同问

**Comment by Shiluodexiaobaitu** [comment]
同问

**Comment by Zhang-haohua** [comment]
如果设置js不压缩呢

**Comment by chenkuangkuang** [comment]
看来只能写一个copyfile的nodejs放在build后面执行了

**Comment by duwei54** [comment]
antd pro 这边我看有反馈 https://github.com/ant-design/ant-design-pro/issues/9460
