### ISSUE TITLE
umi3.4.6 打包是没有将public文件夹复制到dist文件夹下

### ISSUE THREAD

**Issue by yangslmp** [umijs/umi#6344]
按照快速上手教程，快速创建了一个项目，src下没有public文件夹，于是手动创建public文件夹，并放入两个jpg图片，最后运行build打包命令，dist下没有我放入的两个jpg图片，不知道需要在那里配置？急等

**Comment by fangqibin** [comment]
可以放上你的配置看一下

**Comment by liaoyinglong** [comment]
https://umijs.org/zh-CN/docs/directory-structure#%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84

`<rootdir>`下的`public`才会copy过去。

**Comment by yangslmp** [comment]
.umirc.ts文件
import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  routes: [
    { path: '/', component: '@/pages/index' },
  ]
});
图片目录为 /src/public/图片文件

**Comment by yangslmp** [comment]
我配置就是默认生成的，没修改过

**Comment by fangqibin** [comment]
> .umirc.ts文件
> import { defineConfig } from 'umi';
> 
> export default defineConfig({
> nodeModulesTransform: {
> type: 'none',
> },
> routes: [
> { path: '/', component: '@/pages/index' },
> ]
> });
> 图片目录为 /src/public/图片文件
你public目录放的跟src同级试一下

**Comment by yangslmp** [comment]
我刚才试下了，可以了，为什么啊~~~~这个以前不是一直放在src下的吗

**Comment by fangqibin** [comment]
> 我刚才试下了，可以了，为什么啊~~~~这个以前不是一直放在src下的吗

这个我不知道怎么跟你解释，默认只会复制根目录的public文件

**Comment by yangslmp** [comment]
发现这个问题后，我在配置里面加了    publicPath:"/src/"  也没用

**Comment by fangqibin** [comment]
> publicPath

这个是打包的时候用的，你打包出来是没有src这个文件夹的，除非自己创建一个

**Comment by berlin1704** [comment]
文档写的不是给别人看的，是给自己看的
