### ISSUE TITLE
[Bug] 配置chunck过后页面一片白板，浏览器控制台不报错。node控制台也不报错 

### ISSUE THREAD

**Issue by codedart2018** [umijs/umi#6345]
## What happens?
```
chunks: ['vendors', 'umi'],
  chainWebpack: function(config: any, { webpack }: any) {
    config.merge({
      optimization: {
        splitChunks: {
          chunks: 'all',
          minSize: 20000,
          minChunks: 1,
          automaticNameDelimiter: '.',
          cacheGroups: {
            vendor: {
              name: 'vendors',
              test({ resource }: any) {
                return /[\\/]node_modules[\\/]/.test(resource);
              },
              priority: 10,
            },
          },
        },
      },
    });
  }

```
不论是开发还是打包过后都不报错，页面就是一片白。我打包也能正常分包，但是运行起来还是一片空白，跟开发的时候一样。浏览器控制台和node都不报错。不知道什么情况！
## Context

- **Umi Version**:3.4.6
- **Node Version**: 11.9.0
- **Platform**:macos

**Comment by xiaohuoni** [comment]
先删除配置 chunks: ['vendors', 'umi'], 然后编译一下，看看文件是否生成。

**Comment by xiaohuoni** [comment]
可以看看这里 https://zhuanlan.zhihu.com/p/157540425#%E8%B0%83%E6%95%B4%20splitChunks%20%E7%AD%96%E7%95%A5

**Comment by chiefLit** [comment]
遇到相同问题，请问问题解决了吗？

**Comment by 77629296** [comment]
我也遇到了，后面发现因为自定义的chunks，少了默认的"umi"，umi是入口js，没有的话是不会加载其他模块的。
打包后可以看下dist/index.html，有没有umi_xxxx.js引入
![image](https://user-images.githubusercontent.com/22374488/115979224-44fd9600-a5b7-11eb-91b7-d751ef96bfa6.png)

每个项目手动配置比较麻烦，容易出错，我搞了个插件，根据chunks，自动配置分包 [umi-plugin-chuns](https://www.npmjs.com/package/@rainbowfish/umi-plugin-chunks)

**Comment by xiaohuoni** [comment]
@77629296 你的 npm 包里的 git 地址错误。

**Comment by 77629296** [comment]
😊大意了，用了umi插件的架子，已修改。感谢指出 @xiaohuoni

**Comment by fengjingjing1** [comment]
请问下最后是怎么解决的呢，我这边也遇到了相同的问题， dist/index.html 文件里也引入了 umi.js，但还是页面空白

**Comment by fengjingjing1** [comment]
> 遇到相同问题，请问问题解决了吗？

请问你的问题解决了吗，我也遇见了 一样的问题
