### ISSUE TITLE
umi3编译时 图片资源引用抛错

### ISSUE THREAD

**Issue by Quanzhitong** [umijs/umi#6347]
![image](https://user-images.githubusercontent.com/41983846/112603345-d7433a80-8e4f-11eb-9a3c-6d528a52a566.png)
![image](https://user-images.githubusercontent.com/41983846/112603373-df9b7580-8e4f-11eb-93fb-c2ff25e21553.png)

‘@’ 这个符号不是内置了吗? 是src目录

**Comment by xiaohuoni** [comment]
不要重复提 https://github.com/umijs/umi/issues/6348
