### ISSUE TITLE
umi3编译时 相对路径引用图片资源模块找不到

### ISSUE THREAD

**Issue by Quanzhitong** [umijs/umi#6348]
![image](https://user-images.githubusercontent.com/41983846/112603925-9566c400-8e50-11eb-92b5-e38ba52068d0.png)
![image](https://user-images.githubusercontent.com/41983846/112603941-9b5ca500-8e50-11eb-9de6-d52c4e7cbdd3.png)

**Comment by xiaohuoni** [comment]
给复现
