### ISSUE TITLE
关于Umi编译的问题

### ISSUE THREAD

**Issue by amily4555** [umijs/umi#635]
我现在有个项目，是在umi的基础上进行再开发，是一个多项目的集成开发环境
简单的理解是 项目共用 components,  每个项目有单独的route配置以及其他，
根据不同的部署命令生成不同的项目。

但问题来了，在（umi dev 以及 umi build) 编译文件都是对所有的component进行编译（预编译），
随着我的components越来越多，umi 编译是越来越慢

![image](https://user-images.githubusercontent.com/2802841/41454270-5acce330-70ab-11e8-902a-7aea5c983e6d.png)

![image](https://user-images.githubusercontent.com/2802841/41454126-db859996-70aa-11e8-9fa4-474d2792ad40.png)

![image](https://user-images.githubusercontent.com/2802841/41454629-b3747f74-70ac-11e8-8774-d14b43bf6d2c.png)

![image](https://user-images.githubusercontent.com/2802841/41454668-d62b25e0-70ac-11e8-9389-2daa5f49a48e.png)

**Comment by amily4555** [comment]
如上图显示，不同的 pages 编译的时间几乎差不多，以及生成的 umi.js umi.css 一模一样；
请问，是否可以配置 按路由配置的component 进行编译文件呢？

**Comment by amily4555** [comment]
找到原因了
require + expression (动态路劲)，引入资源文件，导致所有的模块都被打包

**Comment by ksh033** [comment]
@amily4555 你是怎么解决这个慢的问题，难道不用动态路径？

**Comment by wangxiansheng001** [comment]
这个是怎么解决的呢？

**Comment by Luxiaoshi** [comment]
@amily4555  想问一下楼主是如何实现多项目开发的

**Comment by Liu992** [comment]
这个问题怎么解决的？急急急
