### ISSUE TITLE
[Bug] 打包后编译代码IE11不兼容

### ISSUE THREAD

**Issue by vilisper** [umijs/umi#6359]
新umi+ ant design pro工程build后的js不兼容ie11
步骤:
1. tyarn create umi  选择ant design pro > typescript > antd4 > simple
2. tyarn 下载依赖
3. npm run build 打包

打包出来的 umi.e3f7830c.js 文件里面还有es6字符串"Loading CSS chunk "+h+` failed.
(`+U+")") IE11不支持报错了。

**Comment by qivhou** [comment]
同样问题 + 1

**Comment by vilisper** [comment]
> 同样问题 + 1

先在config.js里面注释掉 esbuild: {} 不使用esbuild打包出来的可以。

**Comment by ycjcl868** [comment]
有开 esbuild 吗？
