### ISSUE TITLE
[Bug] #2608 IE9  下new ArrayBuffer() 报错 umijs 白屏

### ISSUE THREAD

**Issue by zhanchengkun** [umijs/umi#6360]
## What happens?

[Bug] #2608 IE9  下new ArrayBuffer() 报错 umijs 白屏

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

export default {
  targets: {
    ie: 9,
  },

## Context

- **Umi Version**: umi@3.2.22
- **Node Version**:v12.18.4
- **Platform**: windows 10  专业工作站版

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/1421#issuecomment-516762499 定位一下是哪个库报错。
