### ISSUE TITLE
如何配置umi3路由，使编译后路由可以不包括pages下index.js文件之外的js文件

### ISSUE THREAD

**Issue by yang200258** [umijs/umi#6366]
比如文件结构：
<img width="214" alt="截屏2021-03-31 上午10 56 37" src="https://user-images.githubusercontent.com/38518538/113083981-c576e400-920f-11eb-9b04-762e22b100fe.png">
编译后路由为：
/home，即可访问home文件下的组件，因为index.js作用仅仅引入了HomePage组件

**Comment by xiaohuoni** [comment]
看起来，你的问题是，如何在约定式下只识别index文件。
装这个插件 @alitajs/routes
config/confg.js
```
{
   plugins:['@alitajs/routes'],
   routesExtend: {
      // 规定只有index文件会被识别成路由
      exclude: [
        /(?<!(index|\[index\]|404)(\.(js|jsx|ts|tsx)))$/,
        /model\.(j|t)sx?$/,
        /\.test\.(j|t)sx?$/,
        /service\.(j|t)sx?$/,
        /models\//,
        /components\//,
        /services\//,
      ],
    },
}
```
