### ISSUE TITLE
[Bug] umi-qiankun子应用配置了代理，父应用访问子应用页面可展示，http请求失败

### ISSUE THREAD

**Issue by chenleyiduo** [umijs/umi#6368]
## What happens?

父应用：umi 3.x
安装了@umijs/plugin-qiankun、qiankun
在config中配置：
```
qiankun: {
    master: {
      // 注册子应用信息
      apps: [
        {
          name: 'acss', // 唯一 id
          entry: '//localhost:8121', // html entry
        },
      ],
    },
  },
```
在routes.ts中配置
```
{
      name: 'acss',
      path: '/acss',
      microApp: 'acss',
    }
```

子应用：umi 3.x
安装了@umijs/plugin-qiankun
config.ts中配置：
```
qiankun: {
    slave: {},
  },
proxy:{
'/travelsky-audit': {
      target: 'http://172.22.22.22:80',
      changeOrigin: true,
      secure: false,
    },
...
}
```
在父应用中访问的子应用的路由，子应用中页面能正常显示，但是http请求发送失败

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:3.x
- **Node Version**:12.x
- **Platform**:vs code

**Comment by jxbb** [comment]
子应用接入后访问的是主应用域名，代理也是走主应用了。
把代理移动到主应用或者把接口代理从主应用代理到子应用的域名就行了。

**Comment by AnberLu** [comment]
@jxbb  你好，可以举个例子不
