### ISSUE TITLE
统一 dev 和 build 的 publicPath

### ISSUE THREAD

**Issue by FEliuyg** [umijs/umi#637]
copy配置项`to`配置为根目录文件，但是打包的时候却在`static`目录下
```javascript
"copy": [
    {
      "from": __dirname+'/favicon.ico',
      "to": __dirname+ "/favicon.ico"
    }
  ]
```
在dev环境下，`favicon.ico`是在根目录下的，
但是`favicon.ico`文件在**run build**输出的时候会在`static`目录下
期望两者是一直的，但现在dev环境和production目录不同

**Comment by sorrycc** [comment]
在 umi@2.0 里一起考虑，现在 dev 和 build 的 publicPath 是不一样的。

**Comment by sorrycc** [comment]
umi@2-beta.x 里已无 `static` 目录。
