### ISSUE TITLE
[Bug] SyntaxError: Unexpected token '...'. Expected a property name. 

### ISSUE THREAD

**Issue by spricity** [umijs/umi#6371]
ios10下 safari打开报这个错，应该是构建结果不兼容，加了这两个插件仍然有问题，求帮助
{
extraBabelPlugins: [
    '@babel/proposal-object-rest-spread',
    '@babel/plugin-transform-destructuring'
  ],
}

**Comment by cloudyan** [comment]
targets https://umijs.org/config#targets

{
  ios: 7,
}

**Comment by 15666795711** [comment]
我遇到了同样的问题，"umi": "^3.5.37"，targets配置如下
![image](https://user-images.githubusercontent.com/41468544/223898605-1a26e893-2abc-4d70-8ee8-334065283937.png)
