### ISSUE TITLE
我想问一下umi打包 怎么给index.html加哈希值呢 现在只有js css加了

### ISSUE THREAD

**Issue by yinyijing** [umijs/umi#6374]
想给打包后的index.html也加哈希值

**Comment by xiaohuoni** [comment]
index.html 加 hash 是什么操作？入口文件为什么要带hash，部署了之后不就访问不到了吗？

**Comment by yaoqicaicaicai** [comment]
启用manifest会把html加入缓存列表？怎么从缓存列表里删除index.html？ @xiaohuoni @yinyijing @sorrycc @jrschumacher @crudo
