### ISSUE TITLE
约定式路由无法识别pages目录下子目录的路由

### ISSUE THREAD

**Issue by yang200258** [umijs/umi#6382]
如图为pages下目录结构及pages/home/index.js文件内容，约定式路由无法识别
<img width="189" alt="截屏2021-04-06 下午3 53 25" src="https://user-images.githubusercontent.com/38518538/113677581-51957980-96f0-11eb-8bbe-79ab0f5392fb.png">
<img width="555" alt="截屏2021-04-06 下午3 53 29" src="https://user-images.githubusercontent.com/38518538/113677512-3d517c80-96f0-11eb-8f51-f9f7762dbef1.png">

**Comment by xiaohuoni** [comment]
看这里 https://github.com/umijs/umi/issues/4045
