### ISSUE TITLE
[Bug] 升级3.4.8开启webpack5之后，编译不报错，打开页面报错

### ISSUE THREAD

**Issue by CaanDoll** [umijs/umi#6383]
## What happens?

升级3.4.8开启webpack5之后，编译不报错，打开页面报错：
TypeError: Cannot read property 'FormattedDate' of undefined
![image](https://user-images.githubusercontent.com/23540471/113706966-d2b13880-9711-11eb-8ecd-faed7234ad56.png)
![image](https://user-images.githubusercontent.com/23540471/113707005-e197eb00-9711-11eb-8204-7233a8ba795a.png)

项目中确实用到了react-intl，直接从umi中引用的useIntl。

## How To Reproduce

升级umi@3.4.8后开启webpack5。
```javascript
{
    webpack5: {}
}
```

## Context

- **Umi Version**:3.4.8
- **Node Version**:14.8.0
- **Platform**:windows10

**Comment by CaanDoll** [comment]
目前发现是fastRefresh报的错，关掉就好了

**Comment by huyawei** [comment]
反正3.4.3-3.4.6 重新安装node_modules 直接gg
必须用3.4.8 挺恶心的

**Comment by sorrycc** [comment]
@CaanDoll 给个复现步骤或者给下出错组件的源码？方便我们看下是否 fastRefresh 有问题。

**Comment by sorrycc** [comment]
@huyawei umi 每个版本都是可以锁的，为啥会强制要求 3.4.8?
