### ISSUE TITLE
[Bug] 使用umi初始化的项目 在ie11打不开

### ISSUE THREAD

**Issue by holleword** [umijs/umi#6389]
配置如下： 
![image](https://user-images.githubusercontent.com/20741163/113839920-ba4d2680-97c2-11eb-983f-9e9aac58783c.png)
错误如下：
![image](https://user-images.githubusercontent.com/20741163/113839940-c1743480-97c2-11eb-8151-aaf4c7b822ac.png)

**Comment by holleword** [comment]
![Uploading image.png…]()

**Comment by holleword** [comment]
![image](https://user-images.githubusercontent.com/20741163/113840090-e8cb0180-97c2-11eb-9a83-a1ea0e613296.png)

**Comment by cxf0505** [comment]
我也遇到了这个问题
 "umi": "^3.4.0"

**Comment by lvqi0724** [comment]
我也遇到了这个错误  "umi": "^3.4.8"
![image](https://user-images.githubusercontent.com/50160159/114679458-c004b800-9d3e-11eb-9965-ae92fbbf36a1.png)

**Comment by wuyouhuaz** [comment]
同错已提问题，配置无效

**Comment by cl1107** [comment]
同样遇到这个错误

**Comment by cxf0505** [comment]
> 配置如下： 错误如下：
> ![图像](https://user-images.githubusercontent.com/20741163/113839920-ba4d2680-97c2-11eb-983f-9e9aac58783c.png)
> 
> ![图像](https://user-images.githubusercontent.com/20741163/113839940-c1743480-97c2-11eb-8151-aaf4c7b822ac.png)

升级到“ umi”：“ ^ 3.4.20” 版本，还是有上图这个问题，不清楚是哪里配置出了问题
