### ISSUE TITLE
Add support for .mjs file extension

### ISSUE THREAD

**Issue by baohouse** [umijs/umi#639]
I'm trying to add apollo-upload-client, a plugin for the Apollo GraphQL client, to Ant Design Pro. I'm getting an error which ultimately comes from a lack of proper handling of .mjs files in the webpack configuration. See https://github.com/facebook/create-react-app/pull/3537

Since Ant Design Pro uses roadhog, and roadhog uses af-webpack, it looks like we should add .mjs support here.

**Comment by baohouse** [comment]
I was able to get it working by supplying to my `.webpackrc.js` file the following:
```
extraResolveExtensions: [
  '.mjs',
],
urlLoaderExcludes: [
  /\.mjs$/,
],
```

Although I'll leave this issue open because I think we'll want to add it to babel-loader with the configurable babel plugins.

**Comment by yutingzhao1991** [comment]
You can use `extraBabelPlugins ` for add babel plugin: https://umijs.org/config/#extrababelplugins
