### ISSUE TITLE
[Bug] umi3动态路由影响css module模式下的样式

### ISSUE THREAD

**Issue by cschensai** [umijs/umi#6393]
![image](https://user-images.githubusercontent.com/38218964/113989492-137c8f00-9883-11eb-8ab4-830350513732.png)
### umi2的时候是class="antd-pro-pages-ads-advertise-baidu-step3-$plan-id-components-image-select-index-imageSelectContent"，这种是正常的

**Comment by sorrycc** [comment]
给个最简复现？可能是 [] 转义的问题。
