### ISSUE TITLE
[Bug] umi 3.4.8 antd-design-pro 项目V5版本中使用webpack5后 开发模式 出现OOM 

### ISSUE THREAD

**Issue by bxvs888** [umijs/umi#6397]
## What happens?

dev模式出现内存溢出

● Webpack █████████████████████████ sealing (92%)  
 asset processing

 WAIT  Compiling...                                                                                                                                                                              下午5:48:21

 WAIT  Compiling...                                                                                                                                                                              下午5:48:21

<--- Last few GCs --->

[37069:0x1046c6000]  9483566 ms: Mark-sweep 4078.9 (4129.0) -> 4072.6 (4130.2) MB, 3279.4 / 0.1 ms  (average mu = 0.108, current mu = 0.038) allocation failure scavenge might not succeed
[37069:0x1046c6000]  9486039 ms: Mark-sweep (reduce) 4089.0 (4130.2) -> 4077.0 (4134.5) MB, 2383.6 / 0.3 ms  (+ 0.1 ms in 250 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 2473 ms) (average mu = 0.079, current mu = 0.0

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1012e4da5 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000a6239 node::Abort() [/usr/local/bin/node]
 3: 0x1000a639f node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1001e9007 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1001e8fa3 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 6: 0x100397e95 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 7: 0x10039995a v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 8: 0x100395029 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x1003928c1 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
10: 0x1003a115a v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x1003a11e1 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
12: 0x10036eb87 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
13: 0x1006ed8d8 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x100a7a239 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
15: 0x100a7b177 Builtins_StringAdd_CheckNone [/usr/local/bin/node]
16: 0x5547c09d5dd 
✨  Done in 9489.97s.

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.4.8
- **Node Version**: v14.16.0
- **Platform**: macOS

**Comment by sorrycc** [comment]
是不是用的 cnpm？

**Comment by bxvs888** [comment]
@sorrycc  没有用cnpm ，用的是.  yarn    v1.22.5

**Comment by sorrycc** [comment]
WEBPACK_FS_CACHE=none 试试。

**Comment by bxvs888** [comment]
好的，我试试，谢谢

**Comment by wcxz520** [comment]
> WEBPACK_FS_CACHE=none 试试。

我看不懂。。能不能告诉下怎么加？ "start": "WEBPACK_FS_CACHE=none umi dev", ？？？？

**Comment by wcxz520** [comment]
> WEBPACK_FS_CACHE=none 试试。

噢，umi的参数，不启用物理缓存，但是我加上就会报错~

$ WEBPACK_FS_CACHE=none umi dev
'WEBPACK_FS_CACHE' 不是内部或外部命令，也不是可运行的程序

**Comment by bxvs888** [comment]
在新版本中，还在存溢出，没有以前频繁了。
