### ISSUE TITLE
[Bug] umi3.4.8加入monaco-editor-webpack-plugin会报找不到webpack模块的错误

### ISSUE THREAD

**Issue by wcxz520** [umijs/umi#6398]
操作步骤：
mkdir myapp && cd myapp
yarn add monaco-editor monaco-editor-webpack-plugin
yarn就会报错： 
Cannot find module 'webpack'  
Require stack:
- C:\xzProject\myapp\node_modules\monaco-editor-webpack-plugin\out\index.js

![image](https://user-images.githubusercontent.com/52689177/114130445-2babe700-9933-11eb-8c70-dbe3013a5430.png)

**Comment by wcxz520** [comment]
还漏了步骤~
要在config中加const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

复现的代码仓库~
https://github.com/wcxz520/umi-monaco-editor.git

**Comment by wcxz520** [comment]
有没有人帮帮忙呀~ 我手动add webpack5.x的话，就好像不会有缓存效果， 第二次后启动还是很慢~

**Comment by dbfu** [comment]
遇到同样的问题

**Comment by lxh-wind** [comment]
遇到同样的问题 +1

**Comment by dbfu** [comment]
把项目里的yarn.lock删掉 重新装一下依赖就行了

**Comment by wcxz520** [comment]
> 把项目里的yarn.lock删掉 重新装一下依赖就行了

没用的，不是问题的根本。。。我比较low的方式是： 把config中引入plugin注释掉执行 yarn， 然后放开注释，能够启动项目， 就是每次依赖必报错。。。想知道正确的方式。。问题的根本。。

**Comment by dbfu** [comment]
> > 把项目里的yarn.lock删掉 重新装一下依赖就行了
> 
> 没用的，不是问题的根本。。。我比较low的方式是： 把config中引入plugin注释掉执行 yarn， 然后放开注释，能够启动项目， 就是每次依赖必报错。。。想知道正确的方式。。问题的根本。。

我这边上午试了一下 是可以的 现在能够正常运行

**Comment by sorrycc** [comment]
这个问题早修复了，安装最新的 umi 试试。

**Comment by wcxz520** [comment]
> 这个问题早修复了，安装最新的 umi 试试。

你好，我还没好，我用的3.4.8，能不能具体说下是哪个版本？
