### ISSUE TITLE
English/translated documentation website?

### ISSUE THREAD

**Issue by aletus** [umijs/umi#640]
I am all for keeping documentation / instructions up to date. If documentation Chinese is the easiest to do that, that's fine too if we can use translate to understand.

Before Google Translate worked on umijs.org.

But the new website does NOT support Google translate or Bing translate.  I'm getting an error: 

https://translate.google.com/translate?sl=zh-CN&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=umijs.org&edit-text=&act=url

**Comment by sorrycc** [comment]
I don't know why, we will add an English version of documentation after 2.0 is released.
