### ISSUE TITLE
[Bug] 默认语言选择“繁体中文”四字请改成真正的繁体：“繁體中文”

### ISSUE THREAD

**Issue by xjb258** [umijs/umi#6403]
所有版本都存在：
@umijs\plugin-locale\lib\templates\SelectLang.tpl  369行

  'zh-TW': {
    lang: 'zh-TW',
    label: '繁体中文',
    icon: '🇭🇰',
    title: '語言'
  }

“体”字请改成真正的繁体：“體”，每次更新都要手动来修改，比较麻烦，谢谢。

**Comment by drizzlesconsin** [comment]
Upgrade your version
```ts
"name": "@umijs/plugin-locale",
"version": "0.11.0",
```
https://github.com/umijs/plugins/blob/master/packages/plugin-locale/src/templates/SelectLang.tpl#L369-L370

**Comment by pgsteven** [comment]
中国人不会中文

**Comment by xiaohuoni** [comment]
@xjb258 你提个PR，修复掉就好
