### ISSUE TITLE
[Bug] 服务端渲染，有一定概率，组件未能获取到最新 store 数据

### ISSUE THREAD

**Issue by robinv8** [umijs/umi#6404]
## What happens?

根据返回的 html 发现，window.g_initialProps  中能返回数据，但组件无法通过最新 store 渲染出正确 html

异常情况：

![image](https://user-images.githubusercontent.com/12277531/114305612-7bdda180-9b0b-11eb-9518-411c902c5ef0.png)

正常情况：

![image](https://user-images.githubusercontent.com/12277531/114305571-433dc800-9b0b-11eb-9b7c-0a564418b672.png)

该问题集中出现在高并发的情况下，因此无法提供最小复现仓库，我也看了 umi 源码，大概锁定其出问题的位置：

![image](https://user-images.githubusercontent.com/12277531/114306025-15598300-9b0d-11eb-826f-94128a4fa2b2.png)

## Mini Showcase Repository(REQUIRED)

https://github.com/robinv8/umi-ssr-bug

操作步骤：
1.  ab -n 2000 -c 5 http://127.0.0.1:8000/page2
2. 浏览器访问 http://127.0.0.1:8000

page2 组件的数据，被写入 index 组件的模板

![image](https://user-images.githubusercontent.com/12277531/114348294-ebe63900-9b98-11eb-846d-ed06e36c3c7c.png)

page2 的数据 

## Context

- **Umi Version**:  v3.4.7
- **Node Version**: v12.18.3
- **Platform**: centos

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/114795483-7f5b6d80-9d43-11eb-8a34-76374132102e.png)

**Comment by robinv8** [comment]
![image](https://user-images.githubusercontent.com/12277531/115134484-0c077380-a043-11eb-9487-66d2682392c0.png)

问题出在 dva.tpl 这里共用了 app 对象，在执行到 runtime.tpl 文件时，看似 modifyGetInitialPropsCtx 方法都会在 rootContainer 前执行完，但遇到异步且高并发的时候，多个请求 只有一个 app 对象，store 就错乱了

**Comment by ycjcl868** [comment]
根本原因

![image](https://user-images.githubusercontent.com/13595509/116233717-82c20200-a710-11eb-9672-59a24cc7ec5f.png)

问题出在 server 端的 app 是全局的，被所有请求共用
