### ISSUE TITLE
[Bug] Unhandled Rejection (Invariant Violation): [app.model] namespace should be unique

### ISSUE THREAD

**Issue by KoreSamuel** [umijs/umi#6413]
问题同 #5767
升级umi2.x到umi 3.4.8后出现同样问题

项目执行`npm run build`正常，执行`npm start`报错如下
```
×
Unhandled Rejection (Invariant Violation): [app.model] namespace should be unique
▼ 3 stack frames were expanded.
invariant
./node_modules/invariant/browser.js:38
checkModel
./node_modules/dva-core/dist/index.esm.js:54
model
./node_modules/dva-core/dist/index.esm.js:927
▲ 3 stack frames were expanded.
_callee$
./src/.umi/plugin-dva/dva.ts:47
  44 | app.model({ namespace: 'sysConfig', ...ModelSysConfig1 });
  45 | app.model({ namespace: 'index', ...ModelIndex2 });
  46 | app.model({ namespace: 'models', ...ModelModels3 });
> 47 | app.model({ namespace: 'index', ...ModelIndex4 });
  48 | app.model({ namespace: 'models', ...ModelModels5 });
  49 | app.model({ namespace: 'models', ...ModelModels6 });
  50 | app.model({ namespace: 'models', ...ModelModels7 });
View compiled
▼ 5 stack frames were expanded.
tryCatch
./node_modules/@umijs/preset-built-in/node_modules/regenerator-runtime/runtime.js:45
Generator.invoke [as _invoke]
./node_modules/@umijs/preset-built-in/node_modules/regenerator-runtime/runtime.js:274
Generator.prototype.<computed> [as next]
./node_modules/@umijs/preset-built-in/node_modules/regenerator-runtime/runtime.js:97
asyncGeneratorStep
./node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3
_next
./node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25
```

以下是项目中各个model的namespace，并无重复
![image](https://user-images.githubusercontent.com/9254851/114536900-25e03980-9c84-11eb-9132-88096389e6f4.png)

而在`src/.umi/plugin-dva/dva.ts`中如图
![image](https://user-images.githubusercontent.com/9254851/114537158-75266a00-9c84-11eb-9cab-d2b0ccd5a90b.png)

**Comment by KoreSamuel** [comment]
请问除了把modle文件名改了，还有别的方式吗

**Comment by KoreSamuel** [comment]
版本升级到3.4.11后不再出现了，不知道是不是在这里面修复了，issue就先关了

**Comment by jsoncode** [comment]
今天是2025年2月27号，用umi3.5.43 (v3的最后一个版本)，仍然存在相同问题。我真的服了，几百个model.ts我可怎么改。最关键的是每一个model.ts中的namespance都是独立命名的，为什么不用用户声明的namespace而是用文件名作为namespace？ 这是什么奇葩操作

**Comment by jsoncode** [comment]
我写了一个脚本，来批量处理几百个model

`import fs from 'fs';
import path from 'path';

// 将 model.ts 重命名为[namespace].ts，这里的明明空间是从model里读取的

let basePath = path.resolve('./src/pages');

function migrateToModelsPage(basePath) {
  fs.readdirSync(basePath).forEach(file => {
    var pathname = path.join(basePath, file);
    if (fs.statSync(pathname).isDirectory()) {
      migrateToModelsPage(pathname);
    } else {
      if (file === 'model.ts') {
        const file = fs.readFileSync(pathname, { encoding: 'utf-8' });
        const newName = file.match(/namespace:\s*'([^'"]+)'/)[1]
        const newPath = path.join(basePath, newName + '.ts');
        fs.renameSync(pathname, newPath);
      }
    }
  });
}

migrateToModelsPage(basePath);
`
