### ISSUE TITLE
开启ssr和dynamicImport之后，css加载有问题

### ISSUE THREAD

**Issue by ibandeng** [umijs/umi#6414]
开启ssr和dynamicImport之后，css加载有问题。导致渲染有问题。
![image](https://user-images.githubusercontent.com/47233643/114570434-6782db80-9ca8-11eb-8522-50347a7310d4.png)
![image](https://user-images.githubusercontent.com/47233643/114570510-75386100-9ca8-11eb-9d1f-616e0e4ae959.png)
![image](https://user-images.githubusercontent.com/47233643/114570554-7d909c00-9ca8-11eb-89fa-9edadae98dca.png)

![image](https://user-images.githubusercontent.com/47233643/114569380-80d75800-9ca7-11eb-8a8a-294cb4564f8c.png)

实例地址：
https://github.com/ibandeng/test

复现步骤：从地址栏访问/link就能复现，如果无法复现，复制link，新建一个路由访问即可复现

- **Umi Version**: 3.4.8
- **Node Version**: 14.16.0
- **Platform**: win10

**Comment by ycjcl868** [comment]
老问题了，这个 https://github.com/umijs/umi/issues/6259
