### ISSUE TITLE
[Bug] alias配置别名后没有生效，报错：This dependency was not found type，没人解决么😭

### ISSUE THREAD

**Issue by lishaoh** [umijs/umi#6418]
版本：
"@umijs/fabric": "^2.3.0",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/plugin-esbuild": "^1.0.1",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-react": "^1.4.8",
    "@umijs/preset-ui": "^2.2.9",
    "@umijs/yorkie": "^2.0.3",

### 在config.js、.umirc.js中都配置了alias，但是编译一直报错
![image](https://user-images.githubusercontent.com/20917295/114839014-de82b600-9e07-11eb-9806-b82a89c5addf.png)

![image](https://user-images.githubusercontent.com/20917295/114839177-0e31be00-9e08-11eb-8a27-422048832b53.png)

![image](https://user-images.githubusercontent.com/20917295/114838929-c57a0500-9e07-11eb-9a7e-4c345a5608b2.png)

![image](https://user-images.githubusercontent.com/20917295/114837354-302a4100-9e06-11eb-8001-81572af27f98.png)

**Comment by lishaoh** [comment]
有没有umi相关交流群哦

**Comment by sorrycc** [comment]
1. 代码里不要依赖 config 里的文件
2. .umirc.ts 和 config/config.ts 同时存在时，会用 .umirc.ts
3. .umirc.ts 是根目录的，从 __dirname 开始向上找 ../config 会找到项目外去，所以找不到
