### ISSUE TITLE
升级到umi3的时候,使用命令启动时报错不显示错误，请问如何去找错误

### ISSUE THREAD

**Issue by BINAIMENG** [umijs/umi#6419]
![image](https://user-images.githubusercontent.com/19889708/114840446-674e2180-9e09-11eb-81ad-77fc7be3e953.png)

{
    "@antv/g6": "^4.2.6",
    "@tinymce/tinymce-react": "^3.12.2",
    "@umijs/preset-react": "^1.8.4",
    "axios": "^0.18.0",
    "classnames": "2.2.6",
    "codemirror": "^5.54.0",
    "cron-parser": "^2.17.0",
    "echarts": "4.2.1",
    "eslint-plugin-react-hooks": "^4.2.0",
    "file": "^0.2.2",
    "gg-editor": "^3.1.3",
    "is-json": "^2.0.1",
    "jsrsasign": "^8.0.15",
    "lodash": "4.17.11",
    "md5": "^2.2.1",
    "moment": "^2.26.0",
    "nprogress": "^0.2.0",
    "numeral": "2.0.6",
    "prop-types": "^15.7.2",
    "qs": "6.6.0",
    "rc-texty": "^0.2.0",
    "react": "^16.8.0",
    "react-codemirror2": "^6.0.1",
    "react-document-title": "2.0.3",
    "react-dom": "^16.8.0",
    "react-fittext": "^1.0.0",
    "screenfull": "^5.0.2",
    "sortablejs": "^1.10.2",
    "system": "^2.0.1",
    "three": "^0.120.1",
    "uuid": "^8.3.1",
    "@types/codemirror": "0.0.77",
    "@types/jest": "^23.3.12",
    "@types/react": "^16.9.35",
    "@types/react-dom": "^16.9.8",
    "@types/react-test-renderer": "^16.9.2",
    "babel-eslint": "^9.0.0",
    "babel-jest": "^26.3.0",
    "babel-polyfill": "^6.26.0",
    "cross-env": "^5.2.0",
    "eslint": "^5.4.0",
    "eslint-config-umi": "^1.6.0",
    "eslint-plugin-flowtype": "^2.50.0",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.20.0",
    "husky": "^0.14.3",
    "jest-canvas-mock": "^2.2.0",
    "jest-transform-stub": "^2.0.0",
    "js-cookie": "^2.2.0",
    "lint-staged": "^7.2.2",
    "mockjs": "^1.1.0",
    "path-to-regexp": "^3.2.0",
    "rc-queue-anim": "^1.8.5",
    "react-test-renderer": "^16.7.0",
    "regenerator-runtime": "^0.13.7",
    "tslint": "^5.20.1",
    "tslint-eslint-rules": "^5.4.0",
    "tslint-react": "^3.6.0",
    "umi": "^3.4.8"
}

**Comment by xiaohuoni** [comment]
你提供的这个没有什么帮助，你可以使用 `DEBUG=* umi dev` 看看日志。找不到的话，提供一个可以复现的 repo
