### ISSUE TITLE
umi3.x SSR 缓存

### ISSUE THREAD

**Issue by zfhslfgit** [umijs/umi#6426]
服务器端渲染，存在并发问题。
有没有缓存之类的方法提供？
希望能提供服务端相关demo，比如egg.js

**Comment by itellyou-com** [comment]
这个也就自己服务端处理吧

**Comment by zfhslfgit** [comment]
> 这个也就自己服务端处理吧

您好，能详细点吗？服务端怎么处理有没egg.js案例？

**Comment by itellyou-com** [comment]
umi.server 渲染后返回的是数据流或者html字符串，这个数据要经过egg 输出后才到浏览器。所以在服务端你想咋缓存都可以

**Comment by williamnie** [comment]
采用renderString的方式，把render好的string，扔到redis里（虽然不是很好）但是也没啥问题，已经在线上测试过了，用页面的url作为key，如果有国际化，记得把语言的key加上，不同语音分开缓存
