### ISSUE TITLE
.umirc.js中配置全局context无效

### ISSUE THREAD

**Issue by NexxLuo** [umijs/umi#643]
1. umirc.js中配置全局context
![qq 20180620101001](https://user-images.githubusercontent.com/18549980/41633561-1dda01a4-7472-11e8-9f1d-04425b0a9fb5.png)

2.document.ejs使用context
![qq 20180620101119](https://user-images.githubusercontent.com/18549980/41633616-4f3ba02c-7472-11e8-8e3c-7cb84a27ff36.png)

3.生成的html中并没有context中设置的值
![qq 20180620101155](https://user-images.githubusercontent.com/18549980/41633642-61dede7e-7472-11e8-8b1f-56c44851f0f2.png)

4.更改umirc.js 加上pages的context配置 ， html正常显示
![qq 20180620101400](https://user-images.githubusercontent.com/18549980/41633706-b5c97116-7472-11e8-81cb-618aba555e95.png)
 
 结论：使用全局context时，必须在pages中对各个路由进行context设置，如若不设置，全局context将不     生效

**Comment by NexxLuo** [comment]
补充：第4步中的 pages下的testContext 哪怕改成任意字符串，也能正常显示，故得出最终结论

**Comment by webup** [comment]
@NexxLuo #335

**Comment by NexxLuo** [comment]
@webup #335 这里面说要配置exportStatic ，但是我是配置了的

**Comment by Ende93** [comment]
#778

**Comment by sorrycc** [comment]
Fixed in umi@2.
