### ISSUE TITLE
[Feature Request] 增加devTools文档解释说明

### ISSUE THREAD

**Issue by innocces** [umijs/umi#6432]
## Background

=。-  低版本的`React-DevTools`会引发`react-refresh-webpack-plugin`报错。
```
// 报错
TypeError: Cannot read property 'forEach' of undefined
```
原因是旧版本占据了`renderer`的命名空间。
具体`bug`传送门
- [react-refresh-webpack-plugin/issues/333](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/333)
- [facebook/react/issues/19072](https://github.com/facebook/react/issues/19072#issuecomment-639884030)
- [facebook/react/issues/19072](https://github.com/facebook/react/issues/19072#issuecomment-639884030)

## Proposal
=。-  解决办法是升级或者关闭旧版本的`React-Devtools`。
希望作者可以在ReadMe或者文档里添加说明，小伙伴们在初始使用架子的时候就不会疑惑初次启动失败了。只是建议~

## Additional context
nopo~

**Comment by Map1en** [comment]
感觉只要联网，浏览器的扩展程序都会自动更新？

**Comment by innocces** [comment]
> 感觉只要联网，浏览器的扩展程序都会自动更新？

自己编译的不会的，如果是由于维护旧版本的react专门自己编译的插件就不会了～
