### ISSUE TITLE
[Bug] umi兼容ie11开启不生效，targets:{ie: 11}

### ISSUE THREAD

**Issue by wuyouhuaz** [umijs/umi#6433]
## What happens?

umi兼容ie11开启不生效，targets:{ie: 11}

## Mini Showcase Repository(REQUIRED)

umi兼容ie11开启不生效，targets:{ie: 11}

## Context

- **Umi Version**:  3.4
- **Node Version**:  14
- **Platform**: ie11

**Comment by chokingwin** [comment]
nodeModulesTransform 的 type 设置成 all ，再试试
```
nodeModulesTransform: {
    type: 'all'
}
```
