### ISSUE TITLE
umi项目 nginx部署到非根目录下，采用按需加载，p_index.js路径不对，引入错误

### ISSUE THREAD

**Issue by zhaoxiyang** [umijs/umi#6436]
设置按需加载后，打包如下
![image](https://user-images.githubusercontent.com/29749706/115223506-718c5a80-a13e-11eb-9181-6c63071b292d.png)
p_case.js 和p_index.js是umi.js中引入的
nginx部署到非根目录下，umi.js可以正常引入，路径是对的，但是p_case.js 和p_index.js路径不对，引入错误
报错信息如下
![image](https://user-images.githubusercontent.com/29749706/115223647-9ed90880-a13e-11eb-87af-80a35f697c20.png)
我的.umirc.ts配置
![image](https://user-images.githubusercontent.com/29749706/115223882-df388680-a13e-11eb-85a3-c25fb2a41f5c.png)

**Comment by xiaohuoni** [comment]
应该少了配置 base 。https://umijs.org/zh-CN/docs/deployment#%E9%83%A8%E7%BD%B2-html-%E5%88%B0%E9%9D%9E%E6%A0%B9%E7%9B%AE%E5%BD%95
