### ISSUE TITLE
[Bug]umi3.4版本兼容ie11报错问题

### ISSUE THREAD

**Issue by wuyouhuaz** [umijs/umi#6439]
## What happens?
按照官方提供的解决ie11引入，polyfill在ie11浏览器报错，无法加载项目中的js文件

“报错， ``无法识别”

经过对比，不管是dev还是build下的代码，如下所示，加入"\n"换行（查询源码不知道为啥加这个换行操作），均被解析为 `xxx` 模版字符串的格式

正常情况：throw new Error('This is a error test. Now have a method.');
正常情况：throw new TypeError('This is a error test. Now have a method.');

报错情况：throw new Error('This is a error test. **\n**Now have a method.');
报错情况：throw new TypeError('This is a error test. \nNow have a method.');

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

代码是官方提供的umi+antdprov5版本的基本模版

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

throw new TypeError('This is a error test. Now have a method.');

throw new TypeError('This is a error test. \nNow have a method.');

## Context

- **Umi Version**: 3.4
- **Node Version**: 14.16
- **Platform**: pc--ie11

**Comment by Map1en** [comment]
你看一下是不是用了esbuild，如果用的了话，关掉或者在esbuild-target里手动设置为es5。
目前已经修复plugin-esbuild，等publish。

**Comment by wzc0x0** [comment]
`config.ts` remove esbuild:{}

**Comment by wuyouhuaz** [comment]
> `config.ts` remove esbuild:{}

试过了，还是不行的
