### ISSUE TITLE
[Bug] 疑似route关键字导致的报错

### ISSUE THREAD

**Issue by BluesVN** [umijs/umi#6448]
#### 背景
使用umi3+antd搭建的后台应用
#### 版本
    "umi": "^3.4.0",
   "antd": "^4.14.0",

#### 现象
![image](https://user-images.githubusercontent.com/27759401/115349440-70166d00-a1e6-11eb-8a6e-cd9fa9c9e91e.png)

如图，当路由根结点已‘api’开头是会出现报错 【开发环境】

```
 
Uncaught SyntaxError: Unexpected token '<'
﻿
umi.aa093161.js:1 
​
```
疑似api关键字导致 
不已api开头无此报错

**Comment by yxf007** [comment]
我也遇到了 昨天打包没问题 今天就不行了 把路由都改成一级可以了...

**Comment by sorrycc** [comment]
这是部署的问题，和 umi 无关。
