### ISSUE TITLE
ModuleBuildError, 一个老问题

### ISSUE THREAD

**Issue by amily4555** [umijs/umi#645]
我有一个component,  包含一个 less 文件，
该 less 文件 引用了一个 变量  比如 @abcde

在我某种机制部署 deploy， 该component 未被引用或使用，即使该 component 中有语法错误等，都是被忽略的，未被使用的；但 less 未定义的 @abcde 却被编译时报错 ModuleBuildError: Module build failed；

请问是否 less 文件也如 component 一样未被调用时，不处理？

**Comment by sorrycc** [comment]
这问题看起来和 umi 没啥关系，less 文件也是有引用才交给 webpack 处理的。

**Comment by amily4555** [comment]
@sorrycc 经你提醒，我重新过了下代码，发现是手下某人不按规范操作，造成我编译测试的时候没通过， 

谢谢··
