### ISSUE TITLE
[Bug] 路由中的access没有效果

### ISSUE THREAD

**Issue by hzhijun** [umijs/umi#6451]
这是我的项目地址：https://github.com/hzhijun/demo/tree/test

**Comment by wangyongsong** [comment]
+1 @sorrycc

**Comment by hzhijun** [comment]
我中午部署了一次，到现在一直都不行。

**Comment by wangyongsong** [comment]
## What happens?

[config.ts] routes，路由里面的access属性无效

## Mini Showcase Repository(REQUIRED)

https://github.com/hzhijun/demo/tree/test

## 期望结果

路由无权限的时候，不显示此路由

**Comment by pgsteven** [comment]
这项目的版本完全是没有用的，每次更新一堆breaking changes...

**Comment by pgsteven** [comment]
@sorrycc  why is this issue closed? the bug is still there

@umijs/preset-react  v1.8.6
@umijs/plugin-locale v0.11.2

**Comment by hzhijun** [comment]
@sorrycc  问题还没有解决，怎么关闭了呢？

**Comment by wangyongsong** [comment]
> @sorrycc 问题还没有解决，怎么关闭了呢？
我早上试了下，可以了，删除lock文件，重新安装下。

**Comment by hzhijun** [comment]
> +1 @sorrycc
> 昨天是好的，今天下午5点部署了一下，阵亡

我正要找你呢，问下你的啥情况。

**Comment by hzhijun** [comment]
删除所有的缓存文件，昨天我都试过了，还是不行。

**Comment by wangyongsong** [comment]
和你是一样的问题，access失效，所有用户都能看到路由问题。
今天早上我删了lock文件，重新安装下，已经可以了。
之后我把umi、pro-componets这类包全部回退到1个月前的版本，
最后把yarn.lock文件上传到仓库。
@hzhijun

**Comment by wangyongsong** [comment]
> 删除所有的缓存文件，昨天我都试过了，还是不行。

umi团队是昨天23：00左右修好的 ，你现在再试试，不行的话在反馈一下？
@hzhijun

**Comment by hzhijun** [comment]
好的 我试下

**Comment by DAOLIDEWONIU** [comment]
解决了吗 ？我的还是有问题

**Comment by DAOLIDEWONIU** [comment]
> 好的 我试下

请问你的可以了吗 ？

**Comment by pgsteven** [comment]
@wangyongsong  可以分享一下回退到1个月前的版本package.json吗 ？

**Comment by wangyongsong** [comment]
![image](https://user-images.githubusercontent.com/58172091/115503095-7836e100-a2a8-11eb-92a7-956df3098507.png)
"umi": "~3.4.7"
@pgsteven

**Comment by wangyongsong** [comment]
umi我刚刚看了下，没回退，用的是3.4.11最新版， pro-componets倒是回退到一个月前
```json
  "dependencies": {
    "@ant-design/charts": "1.1.1",
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-card": "^1.10.3",
    "@ant-design/pro-descriptions": "1.6.9",
    "@ant-design/pro-form": "1.19.1",
    "@ant-design/pro-layout": "6.15.5",
    "@ant-design/pro-table": "2.30.8",
    "@umijs/route-utils": "1.0.36",
    "ali-oss": "^6.13.1",
    "antd": "~4.14.1",
    "classnames": "^2.2.6",
    "immutability-helper": "^3.1.1",
    "lodash": "^4.17.11",
    "moment": "^2.29.1",
    "omit.js": "^2.0.2",
    "qs": "^6.9.0",
    "react": "^17.0.0",
    "react-dnd": "^11.1.3",
    "react-dnd-html5-backend": "^11.1.3",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "umi": "~3.4.7",
    "umi-request": "^1.0.8",
    "use-merge-value": "^1.0.1"
  },
```

**Comment by sorrycc** [comment]
还有问题的给复现步骤。

**Comment by pgsteven** [comment]
@sorrycc  直接npm install然后啟动就是了

**Comment by BluesVN** [comment]
遇到了同样的问题，本地开发环境access正常，发布到生产环境就会失效。

**Comment by BluesVN** [comment]
遇到了同样的问题，本地开发环境access正常，发布到生产环境就会失效。
    "umi": "^3.4.0",

**Comment by fgprodigal** [comment]
> 还有问题的给复现步骤。

https://github.com/fgprodigal/LibrarySystemWeb

yarn start:mock

路由access配置没有生效

**Comment by hong418884611** [comment]
![image](https://user-images.githubusercontent.com/25003355/146856700-7bcdb72a-3808-4c6a-b04a-4f8e7e77503b.png)
要配置这个
