### ISSUE TITLE
[Bug] prov5 打包出问题  但是本地build 正常

### ISSUE THREAD

**Issue by xdyz** [umijs/umi#6462]
## What happens?

部署打包 出现问题 但是本地 build 是正常的
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

![image](https://user-images.githubusercontent.com/23496206/115666850-a7685380-a377-11eb-9f7f-6147e1879863.png)

## Context

- **Umi Version**:3.4.0
- **Node Version**:
- **Platform**:

**Comment by jiangyh1024** [comment]
我也出现了 类似的问题
本地没有问题 打包后出问题了
![image](https://user-images.githubusercontent.com/34930870/115986260-f31e3580-a5e1-11eb-8b26-a4acba54b941.png)


调试发现 箭头函数的 a 使用的时候 是 this.props的值
