### ISSUE TITLE
开启 eslint 校验时, ts 转义与eslint 校验，互相矛盾

### ISSUE THREAD

**Issue by amily4555** [umijs/umi#647]
如图，在ts中使用 let {a, ...props} = props, 默认方法放置在编译后的头部，但与 eslint 的 import/first 矛盾 

![image](https://user-images.githubusercontent.com/2802841/41668037-08224000-74e1-11e8-9b3c-d854f3b5573e.png)

![image](https://user-images.githubusercontent.com/2802841/41670634-68b88824-74e7-11e8-884a-5f9858f53495.png)

另：在错误的地方能标明是 eslint 或 tslint 校验错误么？

**Comment by sorrycc** [comment]
这不是 js 文件吗？js 文件为啥会做 ts 校验？

**Comment by amily4555** [comment]
ts 文件编译后转为 js 文件，又被 eslint 校验，结果出错

**Comment by sorrycc** [comment]
使用 ts 的情况下，禁用 eslint 校验吧。
