### ISSUE TITLE
为什么hd配置不工作？

### ISSUE THREAD

**Issue by gaoqiang19514** [umijs/umi#6478]
## 如下配置，我期望的行为是，html的font-size会随着设备的宽度自动修改，可是我按照如下配置，再修改屏幕尺寸，html的font-size纹丝不动，这是怎么回事？（修改后有刷新页面）
![image](https://user-images.githubusercontent.com/13738577/116000751-0c47d600-a624-11eb-8b1e-f708af120082.png)

![image](https://user-images.githubusercontent.com/13738577/116000722-f0dccb00-a623-11eb-86ac-417cb6ce2b97.png)

**Comment by xiaohuoni** [comment]
umi-hd 的逻辑，在模拟器上iphone 5 和 6的这两个都是 100px。你可以切换一下，其他屏幕大小。比如6 plus
![image](https://user-images.githubusercontent.com/11746742/116016796-4ccd4100-a670-11eb-89a2-9e8473812c58.png)

**Comment by YuShai** [comment]
extraPostCSSPlugins

**Comment by YuShai** [comment]
extraPostCSSPlugins

**Comment by gaoqiang19514** [comment]
> umi-hd 的逻辑，在模拟器上iphone 5 和 6的这两个都是 100px。你可以切换一下，其他屏幕大小。比如6 plus
> ![image](https://user-images.githubusercontent.com/11746742/116016796-4ccd4100-a670-11eb-89a2-9e8473812c58.png)

我咨询了下@alitajs/hd，目前需要在chorme的iphone 6/7/8模式上预览，真机上不会有问题
