### ISSUE TITLE
[Bug] 二次封装的antd组件的className没有加载上

### ISSUE THREAD

**Issue by mybedhome** [umijs/umi#6488]
## What happens?

二次封装的antd组件的className没有加载，用自己webpack搭建的框架没有此问题

## How To Reproduce

**Steps to reproduce the behavior:**  加载<MyButton /> 组件内部渲染的antd的Button组件，并传了className

**Expected behavior** 1. 2. className应该正常加到Button组件上

## Context

- **Umi Version**: 3.2.20
- **Node Version**: v12.18.1
- **Platform**: Win 10

**Comment by xiaohuoni** [comment]
随便找了个二次封装的例子，这里应该是需要引入样式的。https://github.com/alitajs/antd-mobile-plus/blob/bd5a56fdbea739e2b71747a7b5a67e4ae7888b4f/packages/antd-mobile-plus/src/CopyBtn/index.less#L2

如果你不是这个情况，那请提供更加详细的信息。
