### ISSUE TITLE
[Bug] umi目录下缺失index.js

### ISSUE THREAD

**Issue by asurance** [umijs/umi#6497]
## What happens?

根据官网教程`快速上手`,执行到`yarn`,报错`Cannot find module '/***/umi-start/node_modules/umi/index.js'. Please verify that the package.json has a valid "main" entry`

1. 查看`node_modules/umi`目录结构确实不存在`index.js`,
2. 查看`node_modules/umi/package.json`里面`main`配置确实是`index.js`

初步判断是发包的时候漏了`index.js`把`dist`目录下内容导出

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

同What happends

**Expected behavior** 1. 2.

无报错

## Context

- **Umi Version**: 3.4.12
- **Node Version**: v14.16.0
- **Platform**:Mac

**Comment by asurance** [comment]
切换至3.4.11后重新`yarn`就正常了

**Comment by xiaohuoni** [comment]
umi@3.4.13 已修复
