### ISSUE TITLE
配置收敛和 umi-plugin-react

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#650]
## 缘起

现在的 umi 其实混扎了很多业务元素的东西，看起来会有些复杂，比如为了云凤蝶发布处理的 route base，为了 h5 离线包处理的本地 file:// 打开的运行模式，以及 antd、hd 方案等等很多功能，这些的东西糅合在一起让 umi 并不那么纯粹。

在开发了一段时间，以及有了社区的积累和反馈之后，我觉得 umi 在 2.0 应该回到一个相对纯粹的开发框架上，找到属于 umi 的核心功能，其他扩展均通过插件的方式存在。

所以，umi 的核心是啥？

我觉得有这些：

* 路由处理
* 插件机制
* 从源码 -> bundle -> html 的生命周期管理

然后与这些有关的配置会内置在 umi 中，而其他的则提取到插件里。

## umi-plugin-react

现在插件比较散，大家在使用时有反馈更新比较麻烦，所以我希望通过 umi-plugin-react 把这些插件集合在一起处理。之所以取名叫 react，意味着后面可能会有 react-native、vue、miniapp 等。

## 默认方案对初学者更友好

目前的 umi 内置了很多优化方案，比如按需编译、按需加载、ESLINT 校验等等，这些方案能提升开发体验和运行效率，但同时也会带来认知上的成本。比如按需加载，用户需要配置正确的 publicPath 才可以。

所以 umi@2 会默认关闭掉很多优化方案：

* 按需编译
* 按需加载
* serviceWorker
* 待补充...

## 配置

内置配置：

* plugins
* history: hash | browser (default)
* routes: { excludes, update, authorize }
* singular
* outputPath

umi-plugin-react 配置：

* hd
* fastClick（默认关闭）
* serviceWorker（默认关闭）
* dynamicImport: true | false (default)
* library: react (default) | preact | anujs | nerv
* base
* publicPath
* runtimePublicPath: true | false (default)
* loading (? 待定，应该可以有更通用的方案)
* pages (? 待定)
* context (? 待定）
* dva: false (default) | true | { immer: true }
* polyfills: ['ie9'] （默认不加 polyfill）

简单项目例子：

```js
export default {
  plugins: ['react'],
}
```

复杂项目例子：

```js
export default {
  sigular: false,

  // build
  base: null,
  hash: false,
  publicPath: '/',
  runtimePublicPath: false,
  outputPath: './dist',

  // plugins
  plugins: ['react'],
  
  // router
  history: 'browser',
  routes: [],
  routesExclude: [],
  routesAuthorize: {
    '/admin': ['./Routes/Admin'],
  },
  
  // config for umi-plugin-react
  react: {
    // mobile
    hd: false,
    fastClick: false,
  
    // performace
    serviceWorker: false,
    dynamicImport: false,
    dll: false,
    hardSource: false,
    library: 'react',
  
    // deploy
    loading: null,
  
    // misc
    dva: false,
    polyfills: [],
  },

  // webpack
  // ...
}
```

**Comment by yutingzhao1991** [comment]
路由处理 相关抽出去为一个插件，但是路由处理还在 umi 的核心中，路由处理这个可以独立于 React 之外存在？还是说路由处理也需要拆分，解构掉和 react 相关的内容。

**Comment by yutingzhao1991** [comment]
也就是说把按照目录约定生成配置这块放到 umi 的核心部分，根据配置生成代码的部分放到外面。但是生成代码这部分我觉得也应该有更官方的支持，因为更上层的一些插件可能会依赖这部分暴露的 API。这样能够让最上层的插件在不同框架上的实现方式能够保持基本的一致性。

就是说 umi-plugin-react 和 umi-plugin-vue 这样的东西应该也是偏核心边官方的。算是一个框架适配层吧。
