### ISSUE TITLE
[Feature Request] svgr-webpack无法开启svgo

### ISSUE THREAD

**Issue by lovewxz** [umijs/umi#6502]
## Background

svgr-webapck中默认svgo是fasle，config没提供如何开启svgo, 满足不了一些自定义svg的场景

## Proposal

config加入修改svgo的参数

## Additional context

config加入修改svgo的参数

**Comment by Cyberhan123** [comment]
我提了一个pr，感觉跟你这个类似，你可以参考一下，emmm,估计最近会把依赖更新到最新版 https://github.com/umijs/plugins/pull/551
