### ISSUE TITLE
[Bug]  external 掉 react、react-dom 后，hmr 在组件名大写的情况下会失效

### ISSUE THREAD

**Issue by zhumengyue** [umijs/umi#6503]
## What happens?

在 `.umirc` 文件中将 `react` 和 `react-dom` external 掉后，如果 `pages/` 目录下的文件 `export default` 出的**名字首字母为大写**，则对应路由的 hrm 疑似失效。

我只能发现这个“规律”，具体原因和表现不清楚。

## Mini Showcase Repository(REQUIRED)

demo 参考：https://github.com/zhumengyue/umi-bug-demo

master 上有两个 commit，第一个为执行 `yarn create @umijs/umi-app` 后提交，可以忽略。主要的 diff 可以看第二个 commit。主要改动包括：
1. 声明 `document.ejs` 文件，引入 `react` 和 `react-dom` 的 `cdn` 链接
2. `.umirc.ts` 中重新声明了几个路由，external 掉了 `react` 和 `react-dom`
3. `/pages` 下补充路由文件，被 `export default` 的名字 `Home` 为大驼峰 `PageHome`，`About` 为小驼峰 `pageAbout`

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
启动项目，分别在 `/about` 和 `/home` 路由下，修改对应的文件，观察页面是否自动更新。

可以发现 `/about` 路由下正常，`/home` 路由下无反应，需要手动刷新。

如果将两个文件被 `export default` 的名字分别改为 `pageHome` 和 `PageAbout`，则现象会相反。

如果不 external 掉 `react` 和 `react-dom`，则所有路由都表现正常。

不太明白导致这个现象的具体原因，只能发现上面这一点规律。

## Context

- **Umi Version**: ^3.4.13
- **Node Version**: 14.2.0
- **Platform**: macOS 10.14.6

**Comment by zhumengyue** [comment]
如果不在 `ejs` 文件中引入 cdn 链接，通过 `scripts` 或 `headScripts` 声明，仍然会有这个现象

**Comment by xiaohuoni** [comment]
确实存在这个问题，不管是大小写，都有触发 hot-update，且修改后的内容有正确被发送到浏览器。只是如果是上述的大写，会多一个 register 导致，导致页面重绘失效。

```
_c = PageHome;
var _c;
__webpack_require__.$Refresh$.register(_c, "PageHome");
```

**Comment by zhumengyue** [comment]
@xiaohuoni 所以这确实是个 bug，后面会修复是吗

**Comment by xiaohuoni** [comment]
@zhumengyue 等大佬看下

**Comment by zhumengyue** [comment]
这个有什么进展嘛，或者有没有暂时的解决方案，现在有点难受

**Comment by xiaohuoni** [comment]
@sorrycc help！

**Comment by zhangchao828** [comment]
react的cdn不能用production的，开发环境要用development的，热更新才会有效
