### ISSUE TITLE
[Bug] tyarn create umi report error: 404

### ISSUE THREAD

**Issue by jackple** [umijs/umi#6507]
## What happens?

```
 tyarn create umi
yarn create v1.22.10
[1/4] 🔍  Resolving packages...
warning create-umi > yeoman-environment > globby > fast-glob > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning create-umi > yeoman-environment > globby > fast-glob > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning create-umi > sylvanas > @umijs/fabric > stylelint-config-rational-order > stylelint > postcss-markdown > remark > unified > @types/vfile > @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://codeload.github.com/teambit/librarian/tar.gz/17d971e4b3f478a407bb7b589a4ec3a5e4dd6dc1: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/shanghaitao/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:v14.15.5
- **Platform**:mac

**Comment by ycjcl868** [comment]
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://codeload.github.com/teambit/librarian/tar.gz/17d971e4b3f478a407bb7b589a4ec3a5e4dd6dc1: Request failed \"404 Not Found\"".

看下是不是源问题

**Comment by jackple** [comment]
> [2/4] 🚚 Fetching packages...
> error An unexpected error occurred: "https://codeload.github.com/teambit/librarian/tar.gz/17d971e4b3f478a407bb7b589a4ec3a5e4dd6dc1: Request failed "404 Not Found"".
> 
> 看下是不是源问题

怎么设置源? 这条链接在浏览器直接打开也是404
