### ISSUE TITLE
umi3，路由配置中的layout设置为false时，页面组件的useEffect依赖[]里的回调会执行两次

### ISSUE THREAD

**Issue by diandian18** [umijs/umi#6508]
umi3，路由配置中的layout设置为false时，页面组件的useEffect依赖[]里的回调会执行两次

**Comment by SteveWangzx** [comment]
同样的情况

**Comment by sunjiesama** [comment]
同样的问题，请问解决了吗

**Comment by SteveWangzx** [comment]
> 同样的问题，请问解决了吗
直接用drawer吧

**Comment by sunjiesama** [comment]
> > 同样的问题，请问解决了吗
> > 直接用drawer吧

不好意思，没明白drawer具体是？

**Comment by zyanfly** [comment]
同样的问题，没人解答下吗？有没有解决方案？

**Comment by vespex** [comment]
同样遇到了，目前主观猜测，是用了什么其他NPM包或者某个版本引起的，具体哪个还没排查出来；因为另外一个简单搭建的，没有过多NPM包的项目，没有这个情况。
大佬们有解决了的么？

**Comment by hejinguo** [comment]
2024-06-21 还是有这样的问题
