### ISSUE TITLE
[Bug] 文档真的不清晰

### ISSUE THREAD

**Issue by yanghuilong** [umijs/umi#6509]
## What happens?

App.ts 到底能配置哪些东西? 文档中也没有说明
dva 配置, 到底配置在.umirc.ts plugins[] 中呢, 还是 配置根对象(defineConfig) 中, 还是在app.ts 中, 我完全看不到有说明

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
不是找能配置什么东西，而是找你需要什么东西。比如你说的 dva 配置，你可以从 https://umijs.org/plugins/plugin-dva#%E9%85%8D%E7%BD%AE 这里看到他支持的配置，在下面有对应的运行时配置，就是在 app.ts 中支持的配置，这些东西都是有插件自己实现和支持的。
