### ISSUE TITLE
[Feature Request] 支持 yarn2 

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#6514]
## Background
* [ ] Yarn 2 支持 https://github.com/umijs/umi/issues/6303
  * WHY：充分利用缓存，提升安装速度
  * HOW：增加相关 resolve 插件，参考 create-react-app 和 storybook 6.2
 
进展：
因为 pnp 支持 webpack5，所以开启了umi 的 webpack5 配置。有些包缺少的，先在项目安装跳过了。
现在卡在了 @ahooksjs/request 这个包的路径错误上，不知道接下去如何修复。

![image](https://user-images.githubusercontent.com/11746742/116529960-11e93880-a910-11eb-854c-055a168b9de0.png)

当前错误：

`/Users/xiaohuoni/Desktop/桌面/nextAlitaApp/.yarn/$virtual/@ahooksjs-use-request-virtual-d397cd4d18/0/cache/@ahooksjs-use-request-npm-2.8.5-3b3b001ac9-9e9d44e016.zip/node_modules/@ahooksjs/use-request`

正确的路径1（其他包的路径都是 $$virtual 而不是 $virtual ）

`/Users/xiaohuoni/Desktop/桌面/nextAlitaApp/.yarn/$$virtual/@ahooksjs-use-request-virtual-d397cd4d18/0/cache/@ahooksjs-use-request-npm-2.8.5-3b3b001ac9-9e9d44e016.zip/node_modules/@ahooksjs/use-request`

正确的路径2

`/Users/xiaohuoni/Desktop/桌面/nextAlitaApp/.yarn/cache/@ahooksjs-use-request-npm-2.8.5-3b3b001ac9-9e9d44e016.zip/node_modules/@ahooksjs/use-request`

不知道 yarn2 怎么定义是从 cache 这个目录找，有些包是 cache 有些包是 $$virtual

通过手动修改 `src/.umi/plugin-request/request.ts` 里面的路径，项目可以正确运行。

被这个问题卡了一天了，不知道接下去如何进行，因此在这里求助，有想法的朋友，麻烦指导一下。

**Comment by xiaohuoni** [comment]
最搞笑的一个 bug 是它 monkey patch resolve 返回的 path 里面故意加了 $$
然后如果你用这个 path 作为 replace 的值
会导致 $$ 被当作是 $ 的 escape
然后又爆了
对 pnp 还有个问题就是本地 debug 极其不方便
包默认都在 zip 里面
看不到源码
要 unplug 出来才行
本地 link 也不如 yarn 1 友好

百度内部yarn 2的策略，直接否掉了不用

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/116547259-3ef41600-a925-11eb-8ecf-5c41abb23a18.png)

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/116547705-cfcaf180-a925-11eb-970a-53e0fa5a3318.png)

**Comment by xrkffgg** [comment]
@xiaohuoni $ 会触发 markdown 的数学公式，给你编辑了~

**Comment by sorrycc** [comment]
可以按这个步骤验，

* [ ] umi 本身通过
* [ ] umi test 通过
* [ ] umi + preset-react 通过

request 的问题会不会是 request 包自身的问题，尝试改 request 包呢？

**Comment by xiaohuoni** [comment]
> @xiaohuoni $ 会触发 markdown 的数学公式，给你编辑了~

@xrkffgg 你不要骗我了，只有这一个被修改。

**Comment by xrkffgg** [comment]
> > @xiaohuoni $ 会触发 markdown 的数学公式，给你编辑了~
> 
> @xrkffgg 你不要骗我了，只有这一个被修改。

See 2楼

**Comment by xiaohuoni** [comment]
> > > @xiaohuoni $ 会触发 markdown 的数学公式，给你编辑了~
> > 
> > 
> > @xrkffgg 你不要骗我了，只有这一个被修改。
> 
> See 2楼

这是群里大佬的吐槽，我就是无法理解为什么只有这一个地方被修改！

**Comment by xiaohuoni** [comment]
@sorrycc 最简 demo 能够支持，安装 @umijs/preset-react 就报错了，https://github.com/umi-hub/umi-base-pnp 我放弃了
