### ISSUE TITLE
[Bug] 设置base和publicPath后部分链接未增加前缀，部分地方前缀出现多余

### ISSUE THREAD

**Issue by quicklearning123** [umijs/umi#6516]
## What happens?

我设置了base和publicPath：
```
  base: '/workbench/',
  publicPath: '/workbench/',
```
效果1：
a href='/xxx.png'未自动增加前缀
![image](https://user-images.githubusercontent.com/70048681/116553005-3f43df80-a92c-11eb-9c4e-3524f4984fab.png)
![image](https://user-images.githubusercontent.com/70048681/116552946-2fc49680-a92c-11eb-8395-ea3f4ea0c80d.png)

.asset方式引入会增加
![image](https://user-images.githubusercontent.com/70048681/116553080-51258280-a92c-11eb-838f-29045be4386a.png)
![image](https://user-images.githubusercontent.com/70048681/116552715-e83e0a80-a92b-11eb-870c-2f23f3a06dad.png)

效果2：面包屑的地址是错的

![image](https://user-images.githubusercontent.com/70048681/116553448-b4afb000-a92c-11eb-97d9-88af63d5bafc.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.3.    (ant design pro v5)
- **Node Version**: 14
- **Platform**:mac os
-

**Comment by panyushan-jade** [comment]
请问解决了吗，我也出现了这个问题

**Comment by Lsnsh** [comment]
在网上查了一圈，看了一些别人提的 issue 和这篇[ 19 年的文章][0]，引用两句 Vue CLI 文档的说明：

> 任何放置在 public 文件夹的静态资源都会被简单的复制，而不经过 webpack。你需要通过绝对路径来引用它们。
>
> 如果 URL 是一个绝对路径 (例如 /images/foo.png)，它将会被保留不变。—— [Vue CLI - URL 转换规则][1]

---

此前我也因为这个问题而困惑，Umi/Ant design pro 文档提及 public 文件夹不会被处理，但没说以绝对路径的形式引用 public 文件夹内的文件的链接不会处理；

进而就误以为设置 publicPath 后，绝对路径的链接会自动追加上 publicPath 设置的基础路径；

然后实际上是不会的，publicPath 不是 public 文件夹的 path，我理解是经过构建后的各种产物的「公共路径」，public 文件夹内的文件不参与构建，跟它们无关。

关于 **public 文件夹**、**绝对路径引用**、**publicPath** 背后隐含的概念，应该是约定俗成的，理解 Umi 文档为啥没对这块详细说明。

[0]: https://blog.csdn.net/qappleh/article/details/103005111
[1]: https://cli.vuejs.org/zh/guide/html-and-static-assets.html#url-%E8%BD%AC%E6%8D%A2%E8%A7%84%E5%88%99

**Comment by Lsnsh** [comment]
至于你说的 `@/assets/***.png` 的方式引入图片，构建后链接部分出现“多余”，这不是多余；

归集一下，将项目构建后的静态资源都输出到 static 目录下，文件一多都摊开不太好，是 Umi 有意为之的。

**Comment by panyushan-jade** [comment]
> 至于你说的 `@/assets/***.png` 的方式引入图片，构建后链接部分出现“多余”，这不是多余；
> 
> 归集一下，将项目构建后的静态资源都输出到 static 目录下，文件一多都摊开不太好，是 Umi 有意为之的。

你好，我配置了path和publicPath，地址栏的路由就会重复，可能重复二次、三次或者更多，但是这种情况不是必然的，偶尔会出现一次，这是什么情况

**Comment by Lsnsh** [comment]
> > 至于你说的 `@/assets/***.png` 的方式引入图片，构建后链接部分出现“多余”，这不是多余；
> > 归集一下，将项目构建后的静态资源都输出到 static 目录下，文件一多都摊开不太好，是 Umi 有意为之的。
> 
> 你好，我配置了path和publicPath，地址栏的路由就会重复，可能重复二次、三次或者更多，但是这种情况不是必然的，偶尔会出现一次，这是什么情况

建议多看看文档，删减一下配置，实际对比下效果

- base 适用于路由的基础路径设置，设置过 ，就不必再为每个路由再设置一遍
- publicPath 适用于打包后资源的基础路径设置

理清一下几个配置的作用之后，确定是 Umi 的问题的话，直接提 issue 呗
