### ISSUE TITLE
umi-plugin-polyfills 引入全部polyfills导致体积过大

### ISSUE THREAD

**Issue by wuomzfx** [umijs/umi#652]
为了兼容IE或者其他低端浏览器，需要引入umi-plugin-polyfills，但是这个插件会加载 一整个 babel-polyfill ，即会加上 所有的 core-js 与 regenerator-runtime 。

对于移动端用户来说，这体积比较大，建议只要针对当前umi底层的一些不兼容问题引入对应的polyfill即可。至于 自己工程内部的不兼容性问题，则在工程内部自己引入polyfill。 

![image](https://user-images.githubusercontent.com/8017237/41756884-65ab2d14-7611-11e8-9005-d3944cbaa78b.png)

**Comment by wuomzfx** [comment]
@xiaohuoni @sorrycc

**Comment by wuomzfx** [comment]
react16 需要支持Set, Map，有些机型可能不支持 @amily4555

**Comment by okoala** [comment]
单独出 set,map polyfills cdn 挂到模板上吧~ 或者弄成插件也行
