### ISSUE TITLE
[Bug] plugin-qiankun examples 热更新之后页面白屏 控制台报错

### ISSUE THREAD

**Issue by h541184072** [umijs/umi#6521]
## What happens?

plugin-qiankun examples 服务起来之后正常 但是随便在一个地方改一下东西保存之后 热更新之后页面白屏 控制台报错

![image](https://user-images.githubusercontent.com/22488992/116657777-8cbe5c00-a9c1-11eb-9a5c-5cd728442940.png)

## Mini Showcase Repository(REQUIRED)

https://github.com/umijs/plugins

## How To Reproduce

**Steps to reproduce the behavior:

yarn
yarn build
cd packages/plugin-qiankun && yarn && yarn start

http://localhost:8000/app2

在 /plugin-qiankun/examples/master/pages/app2/index.js  随便改下代码 console一下 保存之后页面热更新白屏

**Expected behavior** 没报错.

## Context

- **Umi Version**:^3.2.21
- **Node Version**:v12.19.0
- **Platform**:webstorm

**Comment by fxxjdedd** [comment]
Try to fix it in https://github.com/umijs/plugins/pull/629
