### ISSUE TITLE
[Bug] @umijs/plugin-layout 插件国际化bug

### ISSUE THREAD

**Issue by lifegit** [umijs/umi#6523]
## What happens?

@umijs/plugin-layout 插件，如果配置 locale = false，自动生成的 renderRightContent 函数中会导包 SelectLang 组件。这就导致代码报警告

## Mini Showcase Repository(REQUIRED)

https://github.com/lifegit/test2

![image](https://user-images.githubusercontent.com/33006878/117255727-9261e900-ae7c-11eb-900c-c5cf0e976176.png)

**Comment by lifegit** [comment]
目前来看，如果不需要国际化，renderRightContent 只能自己重写。

**Comment by lifegit** [comment]
是否支持 locale = false，时不导 SelectLang 呢？

**Comment by lifegit** [comment]
另外 package.json 中 i18n-remove 这个命令，去除国际化去除不完全。好多文件都没有去。例：src/global.tsx

**Comment by vvni** [comment]
+1
