### ISSUE TITLE
[Bug] 是用history.push 单个元素的数组。在目标页面刷新之后，location.query取到的是字符串，不是数组

### ISSUE THREAD

**Issue by 690591397** [umijs/umi#6526]
## What happens?
单个元素数组情况下。query获取到的参数类型不对

使用history.push 参数如下
```tsx
      <Button
        onClick={() => {
          history.push({
            pathname: '/about',
            query: {
              arraySingle: ['1'],
              arr: ['1', '2', '3'],
            },
          });
        }}
      >
        click me
    </Button>
```
```tsx
// about.tsx
console.info(history.location.query);
// url: https://5u35k.sse.codesandbox.io/about?arr=1&arr=2&arr=3&arraySingle=1
// 正常获取： {arraySingle: Array(1), arr: Array(3)}
// 刷新当前页面 {arr: Array(3), arraySingle: "1"}
```
## Mini Showcase Repository(REQUIRED)
https://codesandbox.io/s/bold-leftpad-5u35k?file=/src/pages/About/index.tsx

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

https://5u35k.sse.codesandbox.io/
1. 点击click me跳转到 /about
2. 刷新页面

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
如果是 `url: https://5u35k.sse.codesandbox.io/about?arraySingle=1`
获取： `{arraySingle: Array(1)}` 那才是 bug 吧。我觉得还是规避掉这种用法比较好。

**Comment by ZenoTian** [comment]
> 如果是 `url: https://5u35k.sse.codesandbox.io/about?arraySingle=1`
> 获取： `{arraySingle: Array(1)}` 那才是 bug 吧。我觉得还是规避掉这种用法比较好。

你好像没有get到他的意思。
放个gif图，方便理解下
![May-07-2021 15-39-33](https://user-images.githubusercontent.com/18542374/117415280-b4c23800-af4a-11eb-97df-8cdbd96dde32.gif)

**Comment by ZenoTian** [comment]
点击按钮解析出来是`{arraySingle: Array(1)} `
刷新解析出来是正确的`arraySingle: "1"`
