### ISSUE TITLE
[Bug] umi 2.13.17 使用 sass 编译失败

### ISSUE THREAD

**Issue by SimonXinw** [umijs/umi#6527]
## What happens?
umijs 的脚手架安装了 sass 模块之后无法编译通过

## Mini Showcase Repository(REQUIRED)
[https://github.com/SimonXinw/react-umi](url)

## How To Reproduce
1. 
```bash
npm install --save-dev @umijs/plugin-sass
 npm i --save-dev node-sass sass-loader
```

2. 
```javascript
.umirc.ts
export default {
sass:{},
}
```
 3.1 
import styles from './index.css';

vscode 报错 -> 找不到模块“./index.scss”或其相应的类型声明。

 ERROR  Failed to compile with 1 errors                                                                         17:29:53

 error  in ./src/layouts/index.scss

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (C:\Users\辛望\Desktop\xw\react-umi\node_modules\sass-loader\dist\index.js:25:24)
    at runLoaders (C:\Users\辛望\Desktop\xw\react-umi\node_modules\webpack\lib\NormalModule.js:316:20)
    at C:\Users\辛望\Desktop\xw\react-umi\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\辛望\Desktop\xw\react-umi\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at process._tickCallback (internal/process/next_tick.js:68:7)

 @ ./src/layouts/index.tsx 11:0-34 16:15-21
 @ ./src/pages/.umi/router.js
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js

 3.2
import './index.scss';

vscode 不报错

ERROR  Failed to compile with 1 errors                                                                         17:31:50

 error  in ./src/layouts/index.scss

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (C:\Users\辛望\Desktop\xw\react-umi\node_modules\sass-loader\dist\index.js:25:24)
    at runLoaders (C:\Users\辛望\Desktop\xw\react-umi\node_modules\webpack\lib\NormalModule.js:316:20)
    at C:\Users\辛望\Desktop\xw\react-umi\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\辛望\Desktop\xw\react-umi\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at process._tickCallback (internal/process/next_tick.js:68:7)

 @ ./src/layouts/index.tsx 11:0-22
 @ ./src/pages/.umi/router.js
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js

## Context

- **Umi Version**:  2.13.17
- **Node Version**: v10.13.0
- **Platform**: window

## 想要得到的结果
1. 希望 sass 能用
2. 希望知道 sass 能用 import 'xxx.scss' ，还是可以用 import styles from 'xxx.scss', 还是两者都能用

**Comment by xiaohuoni** [comment]
请使用低版本的 sass-loader，新版的需要 webpack5 ，相关issues https://github.com/webpack-contrib/sass-loader/issues/932
推荐安装
```
  "node-sass": "^4.9.0",
  "sass-loader": "^7.0.1",
```

> 出现问题注意看报错，很容易找到原因的。TypeError: this.getOptions is not a function
