### ISSUE TITLE
[Bug] URGENT  TypeError: (0 , _umi.formatMessage) is not a function in JEST test framework

### ISSUE THREAD

**Issue by tejparekh** [umijs/umi#6528]
I am trying to write the JEST test cases for my Component. 

component.test.js
`describe('CustomComponent tests cases', () => {
    it('should show the Add Button', () => {
        const wrapper = shallow(<CustomComponent />);
        const instance = wrapper.instance();
        // expect(wrapper.state('visions')).arrayContaining([expect.objectContaining({Priority : '01'})]);
        instance.onSortEnd({oldIndex, newIndex});
        expect(wrapper.find('Button')).toExist();
      });
});`

CustomComponent.js has the code where I am importing the UMI package
import { formatMessage, useIntl, FormattedMessage } from 'umi'

There is no issue in the UI the language file returns the string values. 

When I am running the command `npm test ` (jest and enzyme)
I am thrown the error the as following 

<img width="757" alt="formatMessageError" src="https://user-images.githubusercontent.com/13714772/117388530-47a0a980-af2e-11eb-913b-1180bc9af7d4.png">

Package Json 
`
 "dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-descriptions": "^1.2.0",
    "@ant-design/pro-form": "^1.3.0",
    "@ant-design/pro-layout": "^6.16.1",
    "@ant-design/pro-table": "^2.17.0",
    "@umijs/route-utils": "^1.0.33",
    "antd": "^4.12.0",
    "array-move": "^3.0.1",
    "react": "^16.14.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "react-sortable-hoc": "^2.0.0",
    "umi": "^3.4.1",
    "umi-request": "^1.0.8"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^1.0.28",
    "@types/classnames": "^2.2.7",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.2",
    "@types/lodash": "^4.14.144",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.5.1",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/plugin-esbuild": "^1.0.1",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-react": "^1.4.8",
    "@umijs/yorkie": "^2.0.3",
    "carlo": "^0.9.46",
    "chalk": "^4.0.0",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.1.1",
    "detect-installer": "^1.0.1",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.6",
    "eslint": "^7.1.0",
    "express": "^4.17.1",
    "gh-pages": "^3.0.0",
    "jest": "^26.6.3",
    "jest-environment-enzyme": "^7.1.2",
    "jest-enzyme": "^7.1.2",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.0.1-beta3",
    "nyc": "^15.1.0",
    "prettier": "^2.0.1",
    "puppeteer-core": "^8.0.0",
    "react-addons-test-utils": "^15.6.2",
    "stylelint": "^13.0.0",
    "typescript": "^4.0.3"
  },
`

Thanks for your help

**Comment by xiaohuoni** [comment]
疑似相同问题https://github.com/umijs/umi/issues/5138

**Comment by sonce** [comment]
``` TypeError: umi_1.request is not a function ```

解决了吗？我也遇到类似这个问题。

**Comment by tejparekh** [comment]
No. It’s still unsolved.   
  
  

  
>

**Comment by sajjadshahi** [comment]
@xiaohuoni Yeah it exactly is the same problem. I think the main problem is that the plugins are built runtime and are not accessible directly from `umi` node_modules directory.

**Comment by xiaohuoni** [comment]
我觉得这个方法能够解决问题 https://github.com/umijs/umi/issues/5138#issuecomment-851773630

**Comment by httol** [comment]
> 我觉得这个方法能够解决问题 [#5138 (comment)](https://github.com/umijs/umi/issues/5138#issuecomment-851773630)

不可以
