### ISSUE TITLE
umi-plugin-react 在全局安装成功后任然无法使用

### ISSUE THREAD

**Issue by dataangel** [umijs/umi#6529]
全局安装:Cannot find module 'umi-plugin-react' from '
但是在本目录下安装就没事。

**Comment by dataangel** [comment]
![image](https://user-images.githubusercontent.com/587849/117413393-804d7c80-af48-11eb-89a4-703eec8b54c9.png)

**Comment by dataangel** [comment]
https://blog.csdn.net/qq_45365492/article/details/102821455
这个问题跟我一样问题是他装在本目录下，我想装到全局里

**Comment by xiaohuoni** [comment]
为什么要把这个装到全局？那你umi也要从全局执行才是，比如这里不是 yarn start，而是 umi dev 应该就可以找到。

**Comment by dataangel** [comment]
"start": "umi dev",就是这个命令啊

**Comment by dataangel** [comment]
问题是我每次都要~~搞一个500M左右的库在本目录下才能执行吗

**Comment by dataangel** [comment]
好了 umi dev 就可以了

**Comment by dataangel** [comment]
额发现本目录下已经安装了~~~所以没报错但是我删除了还是报错了。
![image](https://user-images.githubusercontent.com/587849/117417580-14b9de00-af4d-11eb-9d59-d73d0666333c.png)

**Comment by xiaohuoni** [comment]
我只是举一个例子，这个和 umi 找插件的机制有关。如果自己尝试多种方式，那就要自己跟进代码去看看怎么支持。
