### ISSUE TITLE
使用 commons 导出 vender.js/css 后 启动项目报错

### ISSUE THREAD

**Issue by amily4555** [umijs/umi#653]
如题
```javascript

commons: [{
        name: 'vendor',
        minChunks: function (module) {
            return module.context && module.context.indexOf('node_modules') !== -1;
        }
    }],
```

![image](https://user-images.githubusercontent.com/2802841/41757785-d328194c-7616-11e8-8a3f-dd6355f5636e.png)

![image](https://user-images.githubusercontent.com/2802841/41757796-e031bf12-7616-11e8-8fc3-62a8a1a206ff.png)

另 编译打包后 发现生成的 vendor 没有自动写入 index.html 文件

![image](https://user-images.githubusercontent.com/2802841/41757822-1dda606c-7617-11e8-8402-0177ff8f17f2.png)

**Comment by sorrycc** [comment]
别配 commons，umi 默认就有抽公共部分。

**Comment by amily4555** [comment]
umi 默认就有抽公共部分的 规则是什么样?
我早已注意到了，但在我的架构里，因为pages 我只是做了一个中间层，所以目前项目没有生产 common-umi.js

一般 umi 项目，可以抽取公共部分
![image](https://user-images.githubusercontent.com/2802841/41771720-9af317ca-7648-11e8-8f13-ea2a7e43b6aa.png)

但在我的MRI架构下 pages 只是一个中间层，引入 component , 造成不能生产 common-umi.js 文件

![image](https://user-images.githubusercontent.com/2802841/41772364-e4dc0ad4-764a-11e8-8498-9656177a6cb7.png)
