### ISSUE TITLE
Umi Examples TODOS

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#6530]
## Contributing to umi examples

Such as creating example `hello-world`.

```bash
$ mkdir -p examples/hello-world
$yarn bootstrap:example
```

Then you will find the `README.md` and `package.json` is generated in `examples/hello-world`.

```bash
$ tree examples/hello-world
examples/hello-world
├── pages/index.tsx
├── README.md
└── package.json
```

- [x] bootstrap examples https://github.com/umijs/umi/pull/6535

## How to use

Execute [`@umijs/create-umi-app`](https://github.com/umijs/umi/tree/master/packages/create-umi-app) with [npm](https://docs.npmjs.com/cli/init) or [Yarn](https://yarnpkg.com/lang/en/docs/cli/create/) to bootstrap the example:

```bash
npx @umijs/create-umi-app --example hello-world hello-world-app
# or
yarn create @umijs/umi-app --example hello-world hello-world-app
```

- [ ] create-umi-app --example https://github.com/umijs/umi/pull/6549

关于命名，请按以下分类添加前缀，第一个单词作为用例名称，如 `config-404`、`convention-route`、`with-dva`。

### 配置 config-*

- [x] 404 约定式路由中 404 页面的生效规则 https://github.com/umijs/umi/pull/6557
- [x] alias 配置别名，对引用路径进行映射 https://github.com/umijs/umi/pull/6558
- [x] base 主要是非根目录部署的演示 https://github.com/umijs/umi/pull/6664
- [ ] define 要在组件中使用环境变量，要在这里配置
- [x] dynamicImport 演示按路由拆包 https://github.com/umijs/umi/pull/6696
- [ ] dynamicImportSyntax 支持动态引入包
- [ ] exportStatic 每个路由单独输出 html 文件
- [x] favicon 配置 favicon 地址
- [ ] hash 让生成的文件包含 hash 后缀
- [ ] history 配置 history 类型和配置项
- [ ] inlineLimit 配置图片文件是否走 base64 编译的阈值
- [x] proxy 请求代理 https://github.com/umijs/umi/pull/6682
- [ ] ssr 服务端渲染
- [ ] theme 配置 less 变量
- [ ] title 配置页面标题

### 约定 convention-*

- [ ] route 约定路由
- [ ] document 默认模板
- [ ] runtime-config app.ts 内置的运行时配置
- [x] mock Mock 文件 https://github.com/umijs/umi/pull/6686
- [ ] global-css global.css
- [ ] global-js global.js
- [ ] layouts 布局
- [ ] components 组件(这个不是约定，但是可以作为推荐的目录结构)

### 基础能力 basic-*

- [ ] data-fetch 数据请求
- [ ] dynamic-routing 动态路由 [id]
- [ ] environment-variables 环境变量 .env.xxxx
- [ ] fast-refresh 快速刷新 https://umijs.org/config#fastrefresh
- [ ] css css 样式
- [ ] image 图片(和配置的 inlineLimit 可以写到一起)
- [ ] svg svg组件
- [ ] redirect 路由重定向
- [ ] wrappers 路由权限(类似路由守卫) https://umijs.org/docs/routing#wrappers https://github.com/umijs/umi/pull/6570
- [ ] dynamic-layout 多 layouts，不同的页面用不同的 layout
- [ ] dynamic-import 动态组件
- [ ] https 支持 https
- [ ] i18n 国际化
- [ ] csp Content-Security-Policy 主要是演示添加 mata
- [ ] web-worker Web Worker

## 内置插件 plugin-*

- [x] @umijs/plugin-initial-state https://github.com/umijs/umi/pull/6569

## 热门库 with-*

- [x] dva https://github.com/dvajs/dva https://github.com/umijs/umi/pull/6672
- [x] kea https://github.com/keajs/kea https://github.com/umijs/umi/pull/6698
- [x] mobx https://github.com/mobxjs/mobx https://github.com/umijs/umi/pull/6711
- [ ] mobx-state-tree https://github.com/mobxjs/mobx-state-tree
- [ ] redux https://github.com/reduxjs/redux
- [ ] useReducer 自定义的context，主要是和上面的redux做一个对比
- [x] sentry https://github.com/getsentry/sentry https://github.com/umijs/umi/pull/6721
- [x] antd https://github.com/ant-design/ant-design https://github.com/umijs/umi/pull/6717
- [ ] antd-mobile https://github.com/ant-design/ant-design-mobile
- [x] tailwind https://github.com/tailwindlabs/tailwindcss https://github.com/umijs/umi/pull/6589
- [ ] material-ui https://github.com/mui-org/material-ui
- [ ] carbon https://github.com/carbon-design-system/carbon
- [ ] chakra-ui https://github.com/chakra-ui/chakra-ui
- [x] less https://github.com/less/less.js
- [ ] sass https://github.com/sass/sass
- [ ] alifd/next https://github.com/alibaba-fusion/next
- [ ] unstated https://github.com/jamiebuilds/unstated
- [ ] remark https://github.com/remarkjs/remark
- [ ] gh-pages https://www.npmjs.com/package/umi-plugin-gh-pages
- [ ] react-helmet https://umijs.org/plugins/plugin-helmet
- [ ] preact https://github.com/preactjs/preact 
- [ ] aphrodite https://github.com/Khan/aphrodite
- [ ] astroturf https://github.com/4Catalyzer/astroturf
- [ ] aws-amplify https://github.com/aws-amplify/amplify-js
- [ ] babel-macros https://github.com/kentcdodds/babel-plugin-macros
- [ ] cerebral https://github.com/cerebral/cerebral
- [ ] @compiled/react https://github.com/atlassian-labs/compiled
- [ ] draft-js https://github.com/facebook/draft-js
- [ ] electron https://github.com/electron/electron
- [ ] @emotion/react https://github.com/emotion-js/emotion
- [ ] fela https://github.com/robinweser/fela
- [ ] framer/motion https://github.com/framer/motion
- [ ] google-analytics [plugin-analytics](https://umijs.org/plugins/plugin-analytics)
- [ ] graphql-react https://github.com/jaydenseric/graphql-react 
- [ ] grommet https://github.com/grommet/grommet
- [ ] gsap https://github.com/greensock/GSAP
- [ ] hls.js https://github.com/video-dev/hls.js
- [ ] ionic https://github.com/ionic-team/ionic-framework
- [ ] jest umi-test 
- [ ] mdbreact https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design
- [ ] mdx https://github.com/mdx-js/mdx
- [ ] monaco-editor https://github.com/Microsoft/monaco-editor
- [ ] mongodb https://github.com/mongodb/mongo
- [ ] mongoose https://github.com/Automattic/mongoose
- [ ] mqtt https://github.com/mqttjs/MQTT.js
- [ ] msw https://github.com/mswjs/msw
- [ ] overmind https://github.com/cerebral/overmind
- [ ] react-quill https://github.com/quilljs/quill
- [ ] react-bootstrap https://github.com/react-bootstrap/react-bootstrap
- [ ] react-jss https://github.com/cssinjs/jss
- [ ] react-md https://github.com/mlaursen/react-md
- [ ] react-native-web https://github.com/necolas/react-native-web
- [ ] react-relay https://github.com/facebook/relay
- [ ] react-toolbox https://github.com/react-toolbox/react-toolbox
- [ ] react-with-styles https://github.com/airbnb/react-with-styles
- [ ] reactstrap https://github.com/reactstrap/reactstrap
- [ ] realm-web https://github.com/realm/realm-js
- [ ] reasonml https://github.com/reasonml/reason-react
- [ ] rebass https://github.com/rebassjs/rebass
- [ ] recoil https://github.com/facebookexperimental/recoil
- [ ] reflexjs https://github.com/reflexjs/reflexjs
- [ ] rematch https://github.com/rematch/rematch
- [ ] semantic-ui https://github.com/Semantic-Org/Semantic-UI-React
- [ ] slate https://github.com/ianstormtaylor/slate
- [ ] stencil https://github.com/ionic-team/stencil
- [ ] stitches https://github.com/modulz/stitches
- [ ] storybook https://github.com/storybookjs/storybook
- [ ] styletron https://github.com/styletron/styletron
- [ ] emotion https://github.com/emotion-js/emotion/
- [ ] three-js https://github.com/mrdoob/three.js
- [ ] typescript https://github.com/Microsoft/TypeScript
- [ ] typestyle https://github.com/typestyle/typestyle
- [ ] urql https://github.com/FormidableLabs/urql
- [ ] userbase-js https://github.com/smallbets/userbase
- [ ] video.js https://github.com/videojs/video.js
- [ ] why-did-you-render https://github.com/welldone-software/why-did-you-render
- [ ] xstate https://github.com/davidkpiano/xstate
- [ ] yarn-workspaces https://github.com/umijs/umi/issues/5735
- [ ] zustand https://github.com/pmndrs/zustand

> 此清单是一些比较热门的前端库，欢迎推荐和自荐。

**Comment by empty916** [comment]
建议一个新的状态管理器的库：[natur](https://empty916.site/zh/natur/), 配套有对应的umi插件[umi-natur](https://empty916.site/zh/umi-natur/)

**Comment by xiaohuoni** [comment]
> 建议一个新的状态管理器的库：[natur](https://empty916.site/zh/natur/), 配套有对应的umi插件[umi-natur](https://empty916.site/zh/umi-natur/)

可以按规范自己 PR

**Comment by ycjcl868** [comment]
ssr 有 example, 直接单独改个配置

**Comment by xiaohuoni** [comment]
> ssr 有 example, 直接单独改个配置

PR welcome 😊

**Comment by wangyuan0108** [comment]
@xiaohuoni 请问这个是用来做什么呢，支持umi自定义生成项目的文件夹模版吗？

**Comment by wangyuan0108** [comment]
如果用户想在用create-umi-app脚手架生成项目的时候，想生成自己定义的文件夹目录文件，这个能支持吗？

**Comment by xiaohuoni** [comment]
@wangyuan0108 脚本PR合并的话是支持的，现在这个PR还没有合并。https://github.com/umijs/umi/pull/6549

**Comment by cnyballk** [comment]
是停止了？

**Comment by xiaohuoni** [comment]
剩下的等 umi@4 之后实现

**Comment by Hfimy** [comment]
@xiaohuoni umi@4大致会在什么时间点呢？
目前准备在新项目使用umi了，希望后续能有更丰富的文档以及examples

**Comment by xiaohuoni** [comment]
@Hfimy 正式发布时间，可以等通知。后续的文档和 examples 都会尽量补充的

**Comment by StringKe** [comment]
请求支持 https://nx.dev/
