### ISSUE TITLE
ssr的时候，使用static getInitialProps分发完action， window.g_initialProps = null；这个属性为null，不应该更新仓库的状态嘛？

### ISSUE THREAD

**Issue by zhaoshuaidong** [umijs/umi#6531]
static getInitialProps = (async (ctx) => {
    const { store, route, isServer } = ctx;
    if (!isServer) {
      return;
    }
    if(route.path !== "/"){
      return ;
    }
    await store.dispatch({ type: 'home/getDatas' });
    const { home } = store.getState();
    return {
      home
    }
  })

**Comment by robinv8** [comment]
我们项目也重度依赖 ssr，但未发现该问题

**Comment by zhaoshuaidong** [comment]
> 我们项目也重度依赖ssr，但未发现该问题

我已经解决改问题了

**Comment by guanyuan** [comment]
> > 我们项目也重度依赖ssr，但未发现该问题
> 
> 我已经解决改问题了

我也遇到类似的问题，请问是哪里出问题了吗？

**Comment by ycjcl868** [comment]
> > 我们项目也重度依赖ssr，但未发现该问题
> 
> 我已经解决改问题了

怎么解决的
