### ISSUE TITLE
[Bug] presets 插件集中设置 api.modifyDefaultConfig 不生效

### ISSUE THREAD

**Issue by fengsx** [umijs/umi#6533]
## What happens?

> 参照 `@umijs/preset-ant-design-pro` 实现的。

新建一个 presets 后(`src/index.ts`)，同时自定义一个插件 (`src/base.ts`)。
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/fengsx/umi-preset-demo
## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
`yarn start` 之后，发现自定义的插件并没有生效。

**Expected behavior** 1. 2.
希望能看到`@umijs/plugin-analytics`产生的统计代码。

## Context

- **Umi Version**:3.4.15
- **Node Version**:14.16.1
- **Platform**:macOS BigSur 11.1

**Comment by xiaohuoni** [comment]
这有效的。
```
const defaultOptions = {};
api.modifyDefaultConfig((memo) => {
    return {
      ...memo,
      ...defaultOptions,
    };
  });
```

> 希望能看到@umijs/plugin-analytics产生的统计代码。

这个指的是什么？

**Comment by xiaohuoni** [comment]
另外你给的 demo 是plugin 的写法，不是 preset 。可以参考 https://github.com/umijs/plugins/blob/fdd62e428ea6af87045c390921b9cc6e93890e2d/packages/preset-ant-design-pro/src/index.ts#L26
