### ISSUE TITLE
[Bug] 使用addUmiExports添加导出ts类型，报出没有此类型的警告，其实是存在的

### ISSUE THREAD

**Issue by empty916** [umijs/umi#6536]
## What happens?

在我的插件[umi-natur](https://github.com/empty916/umi-natur)中，有使用`api.addUmiExports`这个API导出一个ts类型
![image](https://user-images.githubusercontent.com/20120130/117533814-5e73f880-b021-11eb-993f-551c495b9121.png)

这个`Store`类型在`../store`中是存在的，并且正常运行
![image](https://user-images.githubusercontent.com/20120130/117533866-8a8f7980-b021-11eb-89ec-655a44248b2f.png)

但是在控制台会报警告
![image](https://user-images.githubusercontent.com/20120130/117533933-dd693100-b021-11eb-87ef-94d36e1705e6.png)

## Mini Showcase Repository(REQUIRED)

https://github.com/empty916/umi-app

## How To Reproduce

在我的插件[umi-natur](https://github.com/empty916/umi-natur)代码中
![image](https://user-images.githubusercontent.com/20120130/117534713-37b7c100-b025-11eb-95fa-735c2ff25ccf.png)

## Context

- **Umi Version**: 3.4.15
- **Node Version**: v12.19.0
- **Platform**: macos

**Comment by xiaohuoni** [comment]
类型导出的话，试试 `export *` 或者 `export type`

**Comment by empty916** [comment]
@xiaohuoni 如果是`export type { Store } from '../store';`就不会警告了。但其实我觉得为什么现在会报警告，有点奇怪

**Comment by xiaohuoni** [comment]
现在的是正确逻辑，只是 api 没支持，我来补充下。
关于这个问题的更多信息，可以看看这里 https://flow.org/blog/2015/02/18/Import-Types/
