### ISSUE TITLE
梳理和改进插件体系

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#654]
## 缘起

umi 的插件现在功能**似乎有点太强大**，感觉什么都能做，什么都能改，现在大部分插件由我们自己开发还好，如果社区参与的人多了，可能会有冲突的情况发生。所以得加一些约束，明确什么能做，什么不能做。

## 改进

* [x] 梳理插件体系，更多约束，考虑冲突的可能性、提示和报错
* [x] 文档
* [ ] 脚手架
* [ ] 插件的测试方案
* [x] 支持通过插件添加命令
* [ ] 内部插件通过命名分类，区分 config、html、webpack、deploy 等，比如 umi-plugin-deploy-egg
* [ ] 配置时可以省略 `umi-plugin-`，支持类似 `@ali` 和 `@alipay` 这种域
* [ ] 和 `umi ui` 打通

## 插件接口梳理

TODO

## 参考

* #87

**Comment by yutingzhao1991** [comment]
插件直接的依赖关系我觉得也要改进下。现在的插件大部分都是使用了内置的一些 API，但是未来应该会有更多的插件会对外暴露 API，包括现在有的部分 API 也应该独立为插件来支持。这样就会使得未来插件之间的依赖可能更加复杂。现在需要应用开发者在 `plugins` 中维护插件的顺序，很容易出错。

还有就是插件暴露的 API 应该更严格一点，尤其是一些常用的内部暴露的 API。比如 modifyHTML 就可以再封装为 insertBeforeMainScript 之类的。

**Comment by yutingzhao1991** [comment]
cc @chenshuai2144

**Comment by yutingzhao1991** [comment]
举一个最简单的例子来尝试优化，在 `umi-plugin-locale` 这个插件中用到了 `modifyRouterFile` API，参考代码：https://github.com/umijs/umi-plugin-locale/blob/master/src/index.js#L71 。

其实可以把 `modifyRouterFile` 改为 `afterEntryBuilt.wrapperRouterWithComponent`

```js
api.register('afterEntryBuilt', ({ wrapperAppWithComponent }) => {
  wrapperAppWithComponent('../xxx/xxx/wrapper.js');
})
```

**Comment by yutingzhao1991** [comment]
另外 `modifyRouteComponent` 也是常用的方法，现在也是字符串修改，参考： https://github.com/umijs/umi/blob/master/packages/umi-build-dev/src/routes/routesToJSON.js#L76 。

未来可能会有很多插件需要对路由组件进行包装，所以应该提供如下的方法：

```js
api.register('generateRouteComponent', ({ wrapperRouteComponent }) => {
  wrapperRouteComponent('./xxx/xxx/wrapper.js');
})
```

`wrapper.js` 由插件实现，类似下面这样：

```js
export default (props) => {
  const { umi_RouteComponent, umi_route } = props;
  return (
       <DocumentTitle title={umi_route.title}>
         <umi_RouteComponent ...props/>
       </DocumentTitle>
  );
}
```

**Comment by yutingzhao1991** [comment]
插件也可以重新整理下：

插件机制核心：

- umi-core 

内置核心插件：

- umi-plugin-webpack webpack 构建插件
- umi-plugin-html html 相关插件
- umi-plugin-devserver 调试相关插件
- umi-plugin-routes 路由
- umi-plugin-routes-react 路由的 react 实现，未来可能有 umi-plugin-routes-vue
- umi-plugin-routes-yueding 约定式路由实现

外围插件：

- umi-plugin-dva
- umi-plugin-locale
- umi-plugin-datahub

**Comment by yutingzhao1991** [comment]
还有包括现在一些全局的 `g_app` 之类的全局变量最好不要作为插件对外暴露的对象，如果要这么做最好整理一套规范出来。专门用于插件在运行时的时候暴露一些内容出去。

**Comment by yutingzhao1991** [comment]
关于插件的测试就可以提供一个测试包：

```js
const { api, mocker } = require('umi-plugin-test-tool');
const plugin = require('umi-plugin-locale');

mocker.setConfig({
  locale: {},
});
const mockFn = jest.fn();
mocker.setRigister('modifyRouteFile', mockFn);

plugin(api);

expect(mockFn).toBeCalledWith(...);

```

**Comment by yutingzhao1991** [comment]
![image](https://user-images.githubusercontent.com/1061968/42978436-5e01a0e4-8bff-11e8-8e7f-4b377f22ecd4.png)

还有类似 dva 里面这样的代码，会导致 `RENDER` 只能被使用一次。

**Comment by elvisxiao** [comment]
希望能提供ui 插件的调试能力，目前来讲 开发ui插件需要执行下build才能刷新看到效果，是否支持下热重置
