### ISSUE TITLE
@umijs/openapi interface.njk模板转bug

### ISSUE THREAD

**Issue by Grart** [umijs/umi#6540]
在继承一个类型不增加任何属性的情况下。子类型定义出错
改成

`/* eslint-disable */

declare namespace {{ namespace }} {
  {% for type in list -%}
{%- if type.props.length %}
  type {{ type.typeName | safe }} = {{ '' if type.parent === undefined else type.parent + ' & '  }} {
    {%- for prop in type.props %}
    {%- if prop.desc %}
    /** {{ prop.desc }} */
    {%- endif %}
    '{{ prop.name }}'
    {{ '' if prop.required else '?' }}: {{ prop.type | safe }};
    {%- endfor %}
  }
{%- else %}
  type {{ type.typeName | safe }} = {% if type.parent !== undefined %} {{ type.parent }} {% else %} {{ type.type }} {% endif %};
{%- endif %}
{% endfor %}
}`

**Comment by chenshuai2144** [comment]
直接来个pr吧

**Comment by lcysgsg** [comment]
请问 ”`.njk` 模板“ 相关知识在哪里可以看到？
`openapi` 生成的代码有些问题——比如调文件接口 `blob` 被判断成 `object` 进行了 `JSON.stringify` 导致上传接口不能使用，想看看更多内容和源码，说好的文档也打不开 [https://umijs.org/plugins/plugin-openapi](https://umijs.org/zh-CN/plugins/plugin-openapi) ...
你是在哪里找到 `@umijs/openapi` 的？我找不到它的仓库，只能找到 `@umijs/plugin-openapi`...
