### ISSUE TITLE
使用umi dev打包构建，每次保存都非常非常卡，到后面就电脑崩了

### ISSUE THREAD

**Issue by LemonTree-shine** [umijs/umi#6543]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
你指 umi dev 启动后？还没有收到类似反馈，是不是和你的编辑器有关。

**Comment by LemonTree-shine** [comment]
本地开发的时候，打包的资源都是在内存中的，每次改变内容，重新打包，刷新浏览器就会导致非常卡（window特别明显）
