### ISSUE TITLE
[Bug] 升级umi3后编译进度卡93%

### ISSUE THREAD

**Issue by s13382570** [umijs/umi#6546]
如图所示
![image](https://user-images.githubusercontent.com/41321033/117618773-05cb6980-b1a1-11eb-828f-7b20dd6a7156.png)

- **Umi Version**:3.2.28
- **Node Version**:14
- **Platform**:win10

**Comment by sorrycc** [comment]
复现步骤呢？

**Comment by s13382570** [comment]
> 复现步骤呢？

这边直接调用npm start后就会卡住，每次都会这样，是否需要我这边帖package和config呢

**Comment by s13382570** [comment]
> 复现步骤呢？

先帖一下config吧
`import {IConfig} from 'umi-types';
import pageRoutes from './router.config';

import theme from "./theme";

const packageInfo = require('../package.json');
// ref: https://umijs.org/config/
const config: IConfig = {
    outputPath: `./dist/${packageInfo.version}`,
    publicPath: `/${packageInfo.version}/`,
    copy: [{
        from: "public",
        to: ".."
    }],
    runtimePublicPath: false,
    // treeShaking: true,
    routes: pageRoutes,
    hash: true,
    antd: { },
    dva: {
        // 开启dva-immer，用于代理currentState和nextState之间的改变，即当前状态修改副本
        immer: true,
        // 开启模块热加载(热更新)
        hmr: true,
    },
    // dynamicImport: {},
    // dynamicImport: {
    //     loadingComponent: './components/PageLoading/index',
    //     webpackChunkName: true,
    //     level: 3,
    // },
    title: 'PinjamanNow',
    // dll: {
    //     exclude: ['cashloan-ui', 'cashloan-api', 'cashloan-context', 'cashloan-metadata', 'cashloan-utils', 'cashloan-global']
    // },
    // hd: true,
    locale: {
        default: 'en-US',
        // default: 'zh-CN',
    },
    // plugins:['cashloan-ui','cashloan-api','cashloan-context','cashloan-metadata','cashloan-utils'],
    // plugins: [

        // ref: https://umijs.org/plugin/umi-plugin-react.html
        // ['umi-plugin-react', {
        //     antd: false,
        //     dva: true,
        //     dynamicImport: {
        //         loadingComponent: './components/PageLoading/index',
        //         webpackChunkName: true,
        //         level: 3,
        //     },
        //     title: 'PinjamanNow',
        //     dll: {
        //         exclude: ['cashloan-ui', 'cashloan-api', 'cashloan-context', 'cashloan-metadata', 'cashloan-utils']
        //     },
        //     hd: true,
        //     locale: {
        //         enable: true,
        //         // default: 'zh-CN',
        //         default: 'id-ID',
        //     },
        //     routes: {
        //         exclude: [
        //             /models\//,
        //             /services\//,
        //             /model\.(t|j)sx?$/,
        //             /service\.(t|j)sx?$/,
        //             /components\//,
        //             /define\//,
        //             /utils\//
        //         ],
        //     },
        // }],
        // ['./config/plugins/afterBuild.ts', {}]
    // ],
 
    define: {
        APP_TYPE: process.env.APP_TYPE || '',
    },
    history: {type:'browser'}, // 默认是 browser
    ignoreMomentLocale: true,
    lessLoader: {
        javascriptEnabled: true,
    },
    // disableRedirectHoist: true,
    manifest: {
        basePath: '/',
    },
    theme,
    extraBabelPlugins: [
        ['import', {libraryName: 'antd-mobile', style: true}]  //按需加载antd-mobile样式文件
    ],
    targets: {chrome: 43,ios: 9},
    proxy: {
        "/h5/": {
            // target: "http://192.168.0.40:7000/h5/",
            target: "http://testapi.id.jiaozifin.com:88/h5/",
            changeOrigin: true
        }
    },
    chainWebpack(config){
        config.merge({
            optimization: {
                minimize: true,
                splitChunks: {
                    chunks: 'all',
                    automaticNameDelimiter: '.',
                    name: true,
                    minSize: 30000,
                    maxSize: 0,
                    minChunks: 2,
                    maxAsyncRequests: 10,
                    maxInitialRequests: 5,
                    cacheGroups: {
                        vendor: {
                            name: 'vendors',
                            test: /^.*node_modules[\\/](?!react-virtualized|rc-select|rc-drawer|rc-time-picker|rc-tree|rc-table|rc-calendar|antd|antd-mobile).*$/,
                            chunks: "all",
                            priority: 10,
                        },
                    }
                }
            }
        });
    }
};

export default config;
`

**Comment by s13382570** [comment]
> 复现步骤呢？

`{
  "name": "PinjamanNow",
  "version": "1.0.0",
  "description": "1.0.0",
  "private": true,
  "scripts": {
    "start": "umi dev",
    "build": "umi build",
    "test": "umi test",
    "lint": "eslint {src,mock,tests}/**/*.{ts,tsx} --fix",
    "precommit": "lint-staged"
  },
  "dependencies": {
    "antd-mobile": "^2.3.1",
    "cashloan-api": "^1.0.0",
    "cashloan-context": "^1.0.0",
    "cashloan-ui": "^1.0.0",
    "classnames": "^2.2.6",
    "copy-to-clipboard": "^3.3.1",
    "crypto-js": "^4.0.0",
    "dva": "^2.6.0-beta.6",
    "dva-model-extend": "^0.1.2",
    "nprogress": "^0.2.0",
    "qrcode.react": "^1.0.0",
    "rc-form": "^2.4.11",
    "rc-gesture": "0.0.22",
    "react": "^16.8.6",
    "react-countup": "^4.3.3",
    "react-dom": "^16.8.6",
    "react-sticky": "^6.0.3",
    "react-tooltip": "^4.2.7",
    "react-transition-group": "^4.3.0"
  },
  "devDependencies": {
    "@types/classnames": "^2.2.9",
    "@types/crypto-js": "^3.1.43",
    "@types/jest": "^23.3.12",
    "@types/mockjs": "^1.0.2",
    "@types/nprogress": "^0.2.0",
    "@types/path-to-regexp": "^1.7.0",
    "@types/react": "^16.7.18",
    "@types/react-countup": "^4.0.1",
    "@types/react-dom": "^16.0.11",
    "@types/react-test-renderer": "^16.0.3",
    "@types/react-transition-group": "^4.2.4",
    "babel-eslint": "^9.0.0",
    "cashloan-api": "^1.0.0",
    "cashloan-context": "^1.0.0",
    "cashloan-event": "^1.0.0",
    "cashloan-metadata": "^1.0.0",
    "cashloan-utils": "^1.0.0",
    "eslint": "^5.4.0",
    "eslint-config-umi": "^1.4.0",
    "eslint-plugin-flowtype": "^2.50.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.11.1",
    "husky": "^0.14.3",
    "lint-staged": "^7.2.2",
    "mockjs": "^1.1.0",
    "native-api": "^1.0.0",
    "path-to-regexp": "^6.1.0",
    "react-test-renderer": "^16.7.0",
    "umi": "^3.2.28",
    "@umijs/preset-react":"^1",
    "umi-types": "^0.3.0"
  },
  "lint-staged": {
    "*.{ts,tsx}": [
      "eslint --fix",
      "git add"
    ],
    "*.{js,jsx}": [
      "eslint --fix",
      "git add"
    ]
  },
  "engines": {
    "node": ">=10.13.0"
  }
}
`

**Comment by sorrycc** [comment]
这些信息并不能复现你的问题。
