### ISSUE TITLE
[Bug] Cannot read property 'prefix_exceptions' of undefined

### ISSUE THREAD

**Issue by amberZhaoCN** [umijs/umi#6548]
## What happens?

按照官网「快速上手」步骤创建新工程，运行yarn start 提示 "TypeError: Cannot read property 'prefix_exceptions' of undefined"

步骤：按照官网步骤「[快速上手](https://umijs.org/zh-CN/docs/getting-started)」，操作至yarn start时报错
错误日志：
![image](https://user-images.githubusercontent.com/19767864/117630997-5bf2d980-b1ae-11eb-949b-4470a3e05c9d.png)

## Context

- **Umi Version**: 3.4.16
- **Node Version**: 14.15.4
- **Platform**: macOS 11.1

**Comment by sorrycc** [comment]
底层依赖的 bug，记得他们已经修了。

**Comment by sorrycc** [comment]
重装 node_modules 后试下。

**Comment by sorrycc** [comment]
给个复现仓库。

**Comment by amberZhaoCN** [comment]
升级node到14.16.1后，问题解决了。

**Comment by amberZhaoCN** [comment]
node14.15.4，umi3.4.16版本，重新创建umi工程，yarn start成功执行。npmjs和taobao镜像均表现正常，未能成功复现 @sorrycc
