### ISSUE TITLE
改进多页的静态文件生成

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#655]
## 缘起

目前的方式比较不灵活，而且**不支持动态路由**的方式。

## 注意点

1. 启 ssr-server，然后通过接口生成各 HTML
1. 估计得和 SSR 一起做

## 参考

1. next.js，[相关代码](https://github.com/zeit/next.js/blob/canary/server/export.js)
2. vuepress, [相关代码](https://github.com/vuejs/vuepress/blob/master/lib/build.js)

**Comment by sorrycc** [comment]
等做 SSR 的时候一起考虑。

**Comment by WinterWoods** [comment]
ssr什么时候做.有规划 日期么.
