### ISSUE TITLE
[Bug] Module '"umi"' has no exported member 'useIntl'.

### ISSUE THREAD

**Issue by Leskur** [umijs/umi#6561]
## What happens?

Module '"umi"' has no exported member 'useIntl'.
![image](https://user-images.githubusercontent.com/33910980/117814559-080fef80-b297-11eb-8774-98b10aeb0afa.png)

## Mini Showcase Repository(REQUIRED)
https://github.com/Leskur/umi-app

## How To Reproduce

**Steps to reproduce the behavior:** 
1. git clone https://github.com/Leskur/umi-app.git && cd umi-app
2. yarn
3. open src/pages/index.tsx

**Expected behavior** 
1. 正常的使用 useIntl

## Context

- **Umi Version**: ^3.4.20
- **Node Version**: 14.16.0
- **Platform**: macOS

**Comment by xiaohuoni** [comment]
Configure locale to enable.
https://umijs.org/plugins/plugin-locale#how-to-enable

```diff
import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
+  locale:{},
  routes: [
    { path: '/', component: '@/pages/index' },
  ],
  fastRefresh: {},
});

```

**Comment by Leskur** [comment]
THX
