### ISSUE TITLE
约定式路由设置wrappers失效

### ISSUE THREAD

**Issue by QianXiaL** [umijs/umi#6562]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
有效的，给你一个最简例子 https://github.com/umijs/umi/pull/6570
点击下载 [basic-wrappers.zip](https://github.com/umijs/umi/files/6472021/basic-wrappers.zip)

**Comment by guoenyue** [comment]
配置式有效，约定式例子无效，
umi@3.5.17
umi-plugin-keep-alive@0.0.1-beta.29

router.config.ts中对Route配置wrappers字段的方式有效

但在PageComponent:FC  设置静态属性wrappers无效
