### ISSUE TITLE
 地址栏的地址已经刷新了，但是UI没有任何响应，需要手动refresh才行。

### ISSUE THREAD

**Issue by herechc** [umijs/umi#657]
yield put(routerRedux.push('/markdown'))

**Comment by herechc** [comment]
layouts/index.js已经用了withRouter还是不行

**Comment by herechc** [comment]
找到问题了：layouts/index 用class创建的就会出现这个问题，这是bug？

**Comment by sorrycc** [comment]
用 withRouter 包一下。
