### ISSUE TITLE
[Bug] extraBabelIncludes not work

### ISSUE THREAD

**Issue by worldzhao** [umijs/umi#6576]
## What happens?

`extraBabelIncludes` not work in my monorepo(Rush and pnpm).

I hava a package named `@rush-monorepo/example-feat-comp` which did not process the building, so the app needs to  compile the package. 

But it not works.

![image](https://user-images.githubusercontent.com/25662450/118359984-47508000-b5b8-11eb-8697-1f9f6c120317.png)

![image](https://user-images.githubusercontent.com/25662450/118360041-79fa7880-b5b8-11eb-8ca0-072ee22f1ab2.png)

![image](https://user-images.githubusercontent.com/25662450/118360052-85e63a80-b5b8-11eb-93e5-3b6f4fc0a92a.png)

## Mini Showcase Repository(REQUIRED)

Repository: https://github.com/worldzhao/rush-monorepo-example

## How To Reproduce

```shell
npm i @microsoft/rush@5.47.0 pnpm -g

git clone git@github.com:worldzhao/rush-monorepo-example.git

cd rush-monorepo-example

rush update

rush rebuild -T @rush-monorepo/umi-app

cd apps/umi-app

rushx start
```

## Context

- **Umi Version**: ^3.4.20
- **Node Version**: 14.15.3
- **Platform**: 0.15.6 Beta版(19G46c)
- **Monorepo Tool**: Rush@5.47.0
- **Package Manager**: PNPM@6.3.0

**Comment by worldzhao** [comment]
I found [feat: support extraBabelIncludes #5942](https://github.com/umijs/umi/pull/5942/) that only js|mjs|jsx can be compiled, is there something I missed?

**Comment by worldzhao** [comment]
![image](https://user-images.githubusercontent.com/25662450/118395970-dd9ba900-b67f-11eb-9a03-4c4ad082ebc2.png)
暂时通过这个方式解决了。

**Comment by giscafer** [comment]
`config.module.rules.get('ts-in-node_modules')` 目前umi4是 `undefined` 了。

**Comment by worldzhao** [comment]
> `config.module.rules.get('ts-in-node_modules')` 目前umi4是 `undefined` 了。
看看这个配置？我看 umi4 支持了重定向子包源码，那肯定也会有转译过程吧
https://umijs.org/docs/api/config#monoreporedirect

**Comment by yuanguandong** [comment]
> ![image](https://user-images.githubusercontent.com/25662450/118395970-dd9ba900-b67f-11eb-9a03-4c4ad082ebc2.png) 暂时通过这个方式解决了。

话说 ts-in-node_modules 这个rule 有相关文档吗？没有找到相关说明

**Comment by worldzhao** [comment]
> > ![image](https://user-images.githubusercontent.com/25662450/118395970-dd9ba900-b67f-11eb-9a03-4c4ad082ebc2.png) 暂时通过这个方式解决了。
> 
> 话说 ts-in-node_modules 这个rule 有相关文档吗？没有找到相关说明

应该是 umi 内部自己取的名字，不对开发者暴露，我应该是看 PR 找到的。

**Comment by giscafer** [comment]
目前去掉了这个相关配置，运行正常

**Comment by stefango** [comment]
借楼问下，我的应用从lerna迁到pnpm（monorepo架构）后，umi3子应用无法用上其 extraBabelIncludes 配置的子package里的新代码，是不是umi热更新有问题

**Comment by worldzhao** [comment]
> 借楼问下，我的应用从lerna迁到pnpm（monorepo架构）后，umi3子应用无法用上其 extraBabelIncludes 配置的子package里的新代码，是不是umi热更新有问题

我只用 umi3 跑过一下 demo，后面删掉了，当时应该是可以热更新的...有点久了记不太清了

**Comment by stefango** [comment]
> > 借楼问下，我的应用从lerna迁到pnpm（monorepo架构）后，umi3子应用无法用上其 extraBabelIncludes 配置的子package里的新代码，是不是umi热更新有问题
> 
> 我只用 umi3 跑过一下 demo，后面删掉了，当时应该是可以热更新的...有点久了记不太清了

应该不行，看来要自己写个plugin
https://github.com/umijs/umi/issues/8569#issuecomment-1225560633

**Comment by giscafer** [comment]
@stefango 我这里也有多包管理 ，但是采用的是 yarn workspaces 。使用正常，可以看看 https://github.com/giscafer/rh-template-umi
