### ISSUE TITLE
[Feature Request] openapi生成post请求，必填params不太方便

### ISSUE THREAD

**Issue by quicklearning123** [umijs/umi#6577]
## Background
一般公共参数都是在拦截器赋值了。

![image](https://user-images.githubusercontent.com/70048681/118364735-475a7b00-b5cc-11eb-8107-f3ccf1940e69.png)

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by chenshuai2144** [comment]
直接来个pr吧

**Comment by baabaaox** [comment]
@chenshuai2144 @umijs/openapi 代码仓库在哪？
