### ISSUE TITLE
[Bug] umi3 设置publicPath，css和js加载正常，图片加载不出来

### ISSUE THREAD

**Issue by kuangyuliang** [umijs/umi#6581]
## What happens?
config设置：
![image](https://user-images.githubusercontent.com/23513410/118393453-d79ecb80-b671-11eb-8e5f-371d36383e33.png)
js能按照publicPath加载：
![image](https://user-images.githubusercontent.com/23513410/118393464-ea190500-b671-11eb-98b4-4d7a4e158f00.png)
图片加载不出来，前面没有自动加publicPath：
![image](https://user-images.githubusercontent.com/23513410/118393473-f00ee600-b671-11eb-9586-40c568f3223c.png)
![image](https://user-images.githubusercontent.com/23513410/118393477-f8ffb780-b671-11eb-937b-dbdc92b6dc87.png)

## Context

- **Umi Version**:^3.2.14

**Comment by xiaohuoni** [comment]
https://umijs.org/docs/assets-image#use-image

**Comment by kuangyuliang** [comment]
解决了。
设置一个alias指向public
`alias: {
    public: '/public',
  }`
然后通过`require('public/x.svg')`引用图片
