### ISSUE TITLE
umi 3.4.20 在IE11下打开报错

### ISSUE THREAD

**Issue by ALL-STACK** [umijs/umi#6582]
![image](https://user-images.githubusercontent.com/24264872/118424105-19bf2000-b6f9-11eb-86dc-e4368f1bc952.png)

按照umi官方的步骤 “yarn create @umijs/umi-app” 创建umi项目， 下载依赖后运行，IE11下报错
![image](https://user-images.githubusercontent.com/24264872/118424415-cbf6e780-b6f9-11eb-8416-c10ef8f8350c.png)
![image](https://user-images.githubusercontent.com/24264872/118424416-cbf6e780-b6f9-11eb-9893-dcac7894e585.png)

- **Umi Version**: 3.4.20
- **Node Version**: 12.10.0
- **Platform**: windows系统下IE浏览器

**Comment by xiaohuoni** [comment]
target 设置了嘛？

**Comment by ALL-STACK** [comment]
> target 设置了嘛？

![image](https://user-images.githubusercontent.com/24264872/118450254-94526480-b726-11eb-89ef-8e03ce82d636.png)
已设置

**Comment by code00Way** [comment]
解决了吗？我也碰到这个问题

**Comment by ALL-STACK** [comment]
> 解决了吗？我也碰到这个问题

还没有，等官网修复

**Comment by code00Way** [comment]
找到问题了！手动设置不压缩代码，编译后ie就能用了。前提是设置targets。
现在cmd 中
set COMPRESS=none
umi build
然后部署dist（例如node的serve部署），访问发现就不会报错了
所以有没有办法，让ide在dev编译时不压缩呢？这样方便一点

**Comment by code00Way** [comment]
![image](https://user-images.githubusercontent.com/49588126/119750573-3531e400-becc-11eb-8abb-990ae2eab96f.png)
我发现用umi build压缩打包出来，ie也不报错。难道是idea的问题？我平时直接时终端 yarn start

**Comment by abu0726** [comment]
同样的问题，网上能搜到的方法都试了，都不行。

**Comment by code00Way** [comment]
编译完打包出来试试，我的打包后可以在ie运行，但是dev ie会报错




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月10日(星期四) 晚上7:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [umijs/umi] umi 3.4.20 在IE11下打开报错 (#6582)





 
同样的问题，网上能搜到的方法都试了，都不行。

**Comment by abu0726** [comment]
@code00Way 打包也不行

**Comment by xuehu116** [comment]
同样问题，苦恼

**Comment by code00Way** [comment]
打包后ie可以用------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月13日(星期二) 下午5:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umijs/umi] umi 3.4.20 在IE11下打开报错 (#6582)

**Comment by jyxu1016** [comment]
都快八月份了， 这效率是真高。。

**Comment by code00Way** [comment]
附件有一份ie能调试用的空脚手架。你参考一下（2.x的）。最新版的umi没办法调试，但是打包后可以在ie上跑。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/umi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月22日(星期四) 下午3:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umijs/umi] umi 3.4.20 在IE11下打开报错 (#6582)





 
都快八月份了， 这效率是真高。。

**Comment by banchichen** [comment]
我这按照 https://github.com/umijs/umi/issues/6433 里的方法，设置了nodeModulesTransform后可以了
