### ISSUE TITLE
dynamicImport  devScripts.js:6523 Warning: React does not recognize the `isLoading` prop on a DOM element.

### ISSUE THREAD

**Issue by YangYuHub** [umijs/umi#6586]
dynamicImport: {
    loading: '@ant-design/pro-layout/es/PageLoading',
  },

  报错如下：
![image](https://user-images.githubusercontent.com/63183404/118447736-b72f4980-b723-11eb-83ea-dc36502dd3e1.png)

## Context

- **Umi Version**:  3.4.0
- **Node Version**: 14.16.1
- **Platform**:

**Comment by ApsarasX** [comment]
是的，遇到了同样的问题

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/pro-components/issues/2742

**Comment by leex90** [comment]
same issue here

**Comment by xieww** [comment]
@xiaohuoni 这个应该是PageLoading的问题吧
```js
const PageLoading: React.FC<SpinProps> = (props) => (
  <div style={{ paddingTop: 100, textAlign: 'center' }}>
    <Spin size="large" {...props} /> // props不论包含什么参数都扔进Spin里
  </div>
);
```
![image](https://user-images.githubusercontent.com/26969239/118761003-482e2e00-b8a6-11eb-82a4-359445079928.png)

**Comment by JinShuohang** [comment]
请问这个问题大概什么时候可以修复

**Comment by xiaohuoni** [comment]
预计新版本发布就好了

**Comment by ApsarasX** [comment]
@ant-design/pro-layout新版本已经修复了这个问题

**Comment by xu-Aurora** [comment]
这问题修复了嘛？

**Comment by YangYuHub** [comment]
可以自己写一个Loading组件 先用

**Comment by xu-Aurora** [comment]
> 预计新版本发布就好了

现在最新版本解决好了嘛？
