### ISSUE TITLE
从dva升级到umi@3.4.20后引入antd的less变量不能解析

### ISSUE THREAD

**Issue by bao0417** [umijs/umi#6594]
从dva升级到umi@3.4.20后引入antd的less变量不能解析，例如Variable @green-5 is undefined

在global.less 引入@import '~antd/lib/style/themes/default.less';，在umi临时文件中看见有引入global.less，但是引入antd的less变量都找不到

## Context

- **Umi Version**: "3.4.20"

**Comment by xiaohuoni** [comment]
现在的用法是用到的每一个页面都去引用 @import '~antd/lib/style/themes/default.less';
好像没有一个地方全局去引？ @sorrycc

**Comment by pasBone** [comment]
有办法的话踢我一脚

**Comment by heyuuuu** [comment]
看一下使用的@ant-design的依赖版本和antd的版本是否匹配，应该能解决这个问题。

**Comment by baibaibai455** [comment]
我的好像是同样的问题 https://github.com/umijs/umi/issues/7883
