### ISSUE TITLE
[Bug] config.ts analytics 百度统计配置在 SSR 模式下无效

### ISSUE THREAD

**Issue by MakerTED** [umijs/umi#6597]
## config.ts analytics 百度统计配置在 SSR 模式下无效

开启了 SSR，在 config.ts 文件中也正确设置了百度统计代码，但是浏览页面时无效。

目录采取的方案是在 egg 的 view 文件中添加百度统计代码。

analytics: {
  baidu: '6b8***5d7',
},

## 优化后的效果

- 如果 analytics 可以在 SSR 时正常运作，那就最好啦！
- 如果 analytics 配置在 SSR 时是无效的，最好可以在开发文档中说明一下。

## Context

- umi: 3.4.20

**Comment by xiaohuoni** [comment]
应该是可以的，百度统计最终的代码里面有这些代码就行了吧？你看下最终产物里面有没有这些代码生成。

**Comment by MakerTED** [comment]
我是搞错了！在 SSR 模式下 index.html 中也会包含统计代码。
