### ISSUE TITLE
[Bug] 无法通过配置 extraBabelIncludes 和 chainWebpack 属性实现 monorepo

### ISSUE THREAD

**Issue by etbox** [umijs/umi#6598]
## What happens?

我想利用 yarn workspace 的功能实现在 Ant Design Pro 项目之外引入额外的组件。我参考了已有的一些 issue，如 #5876、#5895 等，发现并不能通过配置 extraBabelIncludes 和 chainWebpack 属性来实现我想要的效果。此外，我还发现以前 umi2 看起来是支持 monorepo 的，为此还专门写了一个[repo](https://github.com/umijs/umi-example-monorepo)，但是 #6530 中提到了 #5735，似乎 umi3 还未支持 yarn workspace？

## Mini Showcase Repository(REQUIRED)

https://github.com/etbox/monorepo-antd-pro

## How To Reproduce

1. 新建 yarn workspace，指定在 packages 目录下
2. 在 packages 下根据[官网](https://beta-pro.ant.design/docs/getting-started-cn)新建 Ant Design Pro v5 项目
3. 新建希望多项目复用的组件 @monorepo/my-button 以及 another-button
4. 在项目中[引入组件](https://github.com/etbox/monorepo-antd-pro/blob/bb19229ac4982480bac51bfa31f70fc4e4a1f9f1/packages/antd-pro/src/pages/user/Login/index.tsx#L16-L17)
5. 报错后根据 issue 进行[配置](https://github.com/etbox/monorepo-antd-pro/blob/bb19229ac4982480bac51bfa31f70fc4e4a1f9f1/packages/antd-pro/config/config.ts#L68-L79)
6. 报错截图放在复现 repo 的根目录下

## Context

- **Umi Version**: umi@3.4.21
- **Node Version**: v14.15.0
- **Platform**: Win10 19042.804

**Comment by xiaohuoni** [comment]
@etbox 先看下这个符不符合你的需求？这个是使用workspaces的，还有个 monorepo的，我找时间再看看。 [with-yarn-workspaces.zip](https://github.com/umijs/umi/files/6537457/with-yarn-workspaces.zip)

**Comment by etbox** [comment]
> @etbox 先看下这个符不符合你的需求？这个是使用workspaces的，还有个 monorepo 的，我找时间再看看。 [with-yarn-workspaces.zip](https://github.com/umijs/umi/files/6537457/with-yarn-workspaces.zip)

不太行，我照着[改了一下](https://github.com/etbox/monorepo-antd-pro/commit/c5f0ab75e404ffd725e321af97455881ffe635ad)，但是内存炸了：
![out-of-memory](https://user-images.githubusercontent.com/16815152/119592030-47e3e480-be0a-11eb-8e71-fcb0ecdb3df3.jpg)

**Comment by xiaohuoni** [comment]
@etbox 我修改了一下，现在可以了。https://github.com/etbox/monorepo-antd-pro/pull/1
另外内存爆炸有个bug，我已经修复了。你可以设置一下 `NODE_OPTIONS=--max-old-space-size=8192 umi dev`，或者手动修改一下 `node_modules/@umijs/bundler-webpack/lib/getConfig/getConfig.jsL238` 改成 `return a.includes(include);` 或者等 umi 发新版本。

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/119599315-52f14180-be17-11eb-8219-ebf44b79e57c.png)

**Comment by etbox** [comment]
基本上解决组件复用的问题了，那我就先关掉这个 issue 了。

**Comment by GreatAuk** [comment]
@xiaohuoni 请问下为什么不能运行 `ts` 文件？

**Comment by GreatAuk** [comment]
这个 issue 也是同样的问题 https://github.com/umijs/umi/issues/6576
