### ISSUE TITLE
swiper pagination的less文件样式在umi中打包后失效。

### ISSUE THREAD

**Issue by SunshineH2** [umijs/umi#6611]
## What happens?

在umi脚手架生成的项目中使用swiper组件，本地样式是生效的，build之后样式失效不显示

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库
https://github.com/SunshineH2/swiper-test

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
1. 从仓库中拉下代码，本地start，可以看到网页中是个轮播图，下方有三个白色的点即pagination，这是因为在index.tsx中引入了import 'swiper/components/pagination/pagination.less'; 所以pagination的样式才可以加载出来，此时本地启动可以正常显示
2. 执行yarn build之后，然后执行yarn server ./dist，可以模拟线上情况，此时pagination的样式消失，即看不到这三个白色的点

**Expected behavior** 1. 2.
本地build之后pagination可以正常显示，即可以正常加载swiper/components/pagination/pagination.less文件（因为swiper/swiper.less是可以正常加载的）

## Context

- **Umi Version**:3.4.22
- **Node Version**: 15..6
- **Platform**: macos chrome

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/119618495-8a6ee680-be35-11eb-8b92-095e4b1897c4.png)
![image](https://user-images.githubusercontent.com/11746742/119618512-8f339a80-be35-11eb-8edc-91fb4a0d2f95.png)
![image](https://user-images.githubusercontent.com/11746742/119618533-96f33f00-be35-11eb-9247-a0e5f2445951.png)

**Comment by SunshineH2** [comment]
是的，但是swiper-bundle.css这个文件太大了，我只用到了其中的一个pagination模块，没有必要去加载全部的css，我想只加载pagination的less或者是css，这种情况下编译后样式就失效了，请再帮忙看下是什么原因，谢谢！
raf.setTimeout(() => {

      next();
    }, 1000);

**Comment by SunshineH2** [comment]
因为在组件中加载swiper.less文件是生效的，但是加载类似于component/pagination/pagination.less文件这样的样式就不生效，不明白是什么原因，是umi内部做了什么处理吗

**Comment by xiaohuoni** [comment]
有两种方式处理：

#### 方法一：
```diff
// src/pages/index.tsx
- import 'swiper/swiper.less';
- import 'swiper/components/pagination/pagination.less';
+ import './index.less';
```
```diff
// src/pages/index.less
@import '~swiper/swiper.less';
@import '~swiper/components/pagination/pagination.less';

.title {
  background: rgb(121, 242, 157);
}
```
#### 方法二：
保留现在的代码，增加配置。
```diff
import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  routes: [{ path: '/', component: '@/pages/index' }],
  fastRefresh: {},
+  extraBabelIncludes:['swiper']
});

```
原因是 build 的时候，没有编译 node_module 里面的文件。

**Comment by SunshineH2** [comment]
好的十分感谢🙏，我试试，谢谢

**Comment by SunshineH2** [comment]
大佬，这个第一个方法是管用的，但是第二个方法就是增加extraBabelIncludes:['swiper']这个不管用，能再帮忙看一下吗，谢谢🙏

**Comment by xiaohuoni** [comment]
@SunshineH2 嗯，没有第二种方法了。

**Comment by SunshineH2** [comment]
😂😂
