### ISSUE TITLE
ie11报错

### ISSUE THREAD

**Issue by code00Way** [umijs/umi#6621]
![image](https://user-images.githubusercontent.com/49588126/119309934-9cb81b80-bca1-11eb-969c-06fc448520af.png)
这个配置是在.umirc.ts里加吗？加了反而报错了，都没法启动了。

**Comment by xiaohuoni** [comment]
按文档步骤排查问题吧。

**Comment by code00Way** [comment]
文档的方法试过了，targets没有效果，复现的办法就是直接从官网按命令创建脚手架，然后运行。添加了targets后ie依旧无法显示




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月26日(星期三) 下午3:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [umijs/umi] ie11报错 (#6621)





 
按文档步骤排查问题吧。

**Comment by xiaohuoni** [comment]
> 文档的方法试过了，targets没有效果，复现的办法就是直接从官网按命令创建脚手架，然后运行。添加了targets后ie依旧无法显示

嗯，不是设置targets，还有后续步骤，看看什么包报错呢

**Comment by code00Way** [comment]
所以只能先按官网的办法解决？你们官方想一下办法吧，官网方法对于react新手还是有点麻烦的。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月26日(星期三) 下午3:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [umijs/umi] ie11报错 (#6621)





 
看起来，和这个问题是一样的 #6582

**Comment by xiaohuoni** [comment]
> 所以只能先按官网的办法解决？你们官方想一下办法吧，官网方法对于react新手还是有点麻烦的。

多做一点就不是新手了

**Comment by code00Way** [comment]
最新发现，原来报错的项目用umi build打包出的dist，用serve本地部署后ie不报错。用umi dev调试ie就会报错。所以是umi dev有问题？求解答（另外ie报错的那一行，build后其实没有那么多行）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月27日(星期四) 上午9:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [umijs/umi] ie11报错 (#6621)





  
所以只能先按官网的办法解决？你们官方想一下办法吧，官网方法对于react新手还是有点麻烦的。
  
多做一点就不是新手了

**Comment by xiaohuoni** [comment]
1、umi dev 不支持 ie 环境。2、build 的时候要开不压缩，才会一样的。

**Comment by Quanzhitong** [comment]
> 1、umi dev 不支持 ie 环境。2、build 的时候要开不压缩，才会一样的。
我新创建了一个umi项目，V3.5.20的；
umi dev启动，
IE 11 下可以访问的
