### ISSUE TITLE
umit3.0 删除了hd，官方文档也没说用什么替代呢？？？

### ISSUE THREAD

**Issue by httol** [umijs/umi#6626]

**Comment by xiaohuoni** [comment]
你可以用[plugin-hd](https://www.npmjs.com/package/@alitajs/hd)，就是 umi@2 的 hd 方案。

**Comment by dominicleo** [comment]
https://github.com/dominicleo/umi-plugin-flexible

**Comment by xiaohuoni** [comment]
> https://github.com/dominicleo/umi-plugin-flexible

我们最近也在考虑这个，umi@2的方案，在嵌套页面的时候，会有内外 viewport 导致，缩放错误的问题。
