### ISSUE TITLE
You are using a whole package of antd

### ISSUE THREAD

**Issue by huyawei** [umijs/umi#6628]
umi 配置
antd
类型：Boolean
启用后自动配置 babel-plugin-import 实现 antd, antd-mobile 和 antd-pro 的按需编译，并且内置 antd, antd-mobile 依赖，无需手动在项目中安装。

-----------------------------------------------------------------------------------------
antd官方
按需加载#
antd 默认支持基于 ES modules 的 tree shaking，对于 js 部分，直接引入 import { Button } from 'antd' 就会有按需加载的效果。
如果你在开发环境的控制台看到下面的提示，那么你可能还在使用 webpack@1.x 或者 tree shaking 失效，请升级或检查相关配置。

-----------------------------------------------------------------------------------------
看配置描述，umi 打开antd的话应该就是正常的按需加载才对，
而且umi3.x 还去除了treeshaking的配置说是默认打开。
而且观察了webpack的版本是4.x也没问题
那么umi为什么要给我提示这个警告。
设置antd: false, 更新 babel-plugin-import , 在 extraBabelPlugins 里配置
["import", { "libraryName": "antd", "libraryDirectory": "es", "style": "css" }]
还是无效
网上能查到的方法试了个遍根本解决不了问题

**Comment by huyawei** [comment]
....
antd 4.12.0 更新到 最新的4.16.0 好了
关键看着文档描述跟atnd没关系才对
真是神奇

**Comment by qiutian00** [comment]
> ....
> antd 4.12.0 更新到 最新的4.16.0 好了
> 关键看着文档描述跟antd没关系才对
> 真是神奇

升级之后， 的确可以
