### ISSUE TITLE
Cannot find module 'umi/babel'

### ISSUE THREAD

**Issue by 184609680** [umijs/umi#663]
./src/pages/.umi/umi.js
Module build failed: Error: Cannot find module 'umi/babel' from 'E:\project\gith
ub\antd-admin-master'
    at Array.map (<anonymous>)

**Comment by sorrycc** [comment]
依赖没装好？

**Comment by 184609680** [comment]
这需要额外安装什么？
package.json
`{
  "private": true,
  "name": "antd-admin",
  "version": "5.0.0-beta",
  "dependencies": {
    "antd": "^3.6.4",
    "axios": "^0.18.0",
    "classnames": "^2.2.6",
    "d3-shape": "^1.2.0",
    "draftjs-to-html": "^0.8.4",
    "draftjs-to-markdown": "^0.5.1",
    "dva-model-extend": "^0.1.2",
    "echarts": "^4.1.0",
    "echarts-for-react": "^2.0.13",
    "echarts-gl": "^1.1.1",
    "echarts-liquidfill": "^2.0.0",
    "highcharts-exporting": "^0.1.7",
    "highcharts-more": "^0.1.7",
    "jsonp": "^0.2.1",
    "lodash.clonedeep": "^4.5.0",
    "lodash.isequal": "^4.5.0",
    "nprogress": "^0.2.0",
    "path-to-regexp": "^2.2.0",
    "prop-types": "^15.6.2",
    "qs": "^6.5.2",
    "query-string": "^5.1.1",
    "rc-tween-one": "^1.8.1",
    "react-adsense": "0.0.5",
    "react-countup": "^3.0.3",
    "react-draft-wysiwyg": "^1.12.13",
    "react-helmet": "^5.2.0",
    "react-highcharts": "^16.0.2",
    "recharts": "^1.0.0-beta.10"
  },
  "devDependencies": {
    "@babel/polyfill": "^7.0.0-beta.51",
    "babel-plugin-dev-expression": "^0.2.1",
    "babel-plugin-module-resolver": "^3.1.1",
    "babel-polyfill": "^6.26.0",
    "cross-env": "^5.1.6",
    "eslint": "^4.19.1",
    "eslint-config-umi": "^0.1.4",
    "eslint-plugin-flowtype": "^2.48.0",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.8.2",
    "js-beautify": "^1.7.5",
    "less-vars-to-js": "^1.2.1",
    "mockjs": "^1.0.1-beta3",
    "svg-sprite-loader": "^3.8.0",
    "umi": "^1.3.5",
    "umi-plugin-dll": "^0.2.1",
    "umi-plugin-dva": "^0.8.0",
    "umi-plugin-routes": "^0.1.5"
  },
  "pre-commit": [
    "lint"
  ],
  "scripts": {
    "analyze": "cross-env ANALYZE=1 BABELRC=1 umi build",
    "start": "cross-env BABELRC=1 COMPILE_ON_DEMAND=none BROWSER=none HOST=0.0.0.0 umi dev",
    "lint": "eslint --fix --ext .js src",
    "build": "cross-env BABELRC=1 umi build",
    "test": "umi test"
  }
}
`

**Comment by sorrycc** [comment]
给个重现步骤？没看出来问题在哪里。

**Comment by 184609680** [comment]
可能网络等原因，npm 没装全，重新npm i一样就好了，
麻烦package.json补全下
npm start的时候
加依赖包加的蛋都碎了
