### ISSUE TITLE
[Bug] windows10下，通过脚手架创建项目会报错

### ISSUE THREAD

**Issue by cy188** [umijs/umi#6635]
## What happens?
在windows10系统下，通过脚手架创建项目会报错：
1. 首先nodejs是安装在 C:\Program files\ 目录下的，node_global和node_cache也在该目录下
2. 然后通过npm i yarn tyarn -g命令安装了yarn和tyarn
3. 再使用 tyarn create @umijs/umi-app 命令创建项目时，就会报错，报错内容如下：

![20201118103217158](https://user-images.githubusercontent.com/37726036/119605012-a0bf7700-be22-11eb-9e88-c9efeae182fd.png)

4. 提示C:\Program不是内部或外部命令
5. **原因**：nodejs的安装目录 C:\Program files\ 中间含有 **空格** 导致报错
6. **已解决方法**：重新安装了nodejs，并且安装在 C:\Program\ 目录下，node_global和node_cache也在该目录下，**中间没有空格，就不会报错**

## Mini Showcase Repository(REQUIRED)
根据上面的步骤就可以在windows10系统下复现

## Context

- **umi 3.4.22**:
- **nodejs 14.16.1**:
- **windows10**:

**Comment by xiaohuoni** [comment]
应该和空格无关，这个问题是，需要配置 path。你第二次装的时候，选了添加到path里。

**Comment by xiaohuoni** [comment]
同理可以参考这里 https://umijs.org/docs/faq#umi-%E4%B8%8D%E6%98%AF%E5%86%85%E9%83%A8%E6%88%96%E5%A4%96%E9%83%A8%E5%91%BD%E4%BB%A4

**Comment by cy188** [comment]
重新安装之前已经添加到PATH了

**Comment by cy188** [comment]
> 应该和空格无关，这个问题是，需要配置 path。你第二次装的时候，选了添加到path里。

重新安装之前已经添加到PATH了

**Comment by xiaohuoni** [comment]
那就不确定了，需要window电脑重现，但感觉和空格无关。是不是使用 tyarn 的问题？
