### ISSUE TITLE
ssr服务端数据欲获取后，会挂载到客户端window.g_initialProp，请问有其他方案吗？

### ISSUE THREAD

**Issue by birdycn** [umijs/umi#6638]
ssr服务端数据欲获取后，会挂载到客户端window.g_initialProp，请问有其他方案吗？

可以ssr获取数据后再渲染到html里，而不是挂载到window变量里，渲染成html之后再返回吗？

**Comment by wangjiangs** [comment]
你咋解决的啊，你现在是可以直接将数据渲染成html返回了吗？在g_initialProp里面根本没法做seo。

**Comment by leftstick** [comment]
你最好得先明白`挂载到客户端window.g_initialProp`的目的是什么。

理解ssr在react里工作原理很重要

**Comment by wangjiangs** [comment]
我知道了，我之前是因为代码逻辑中有条件表达式，在服务器端时没法通过判断，才导致页面html在服务端没渲染出来。
