### ISSUE TITLE
开启removeWindowInitialProps:true后，前端会再一次获取数据，请问正常吗？

### ISSUE THREAD

**Issue by birdycn** [umijs/umi#6640]
开启removeWindowInitialProps:true后，后端已经完成渲染了，但是前端会再一次获取数据，请问正常吗？

**Comment by robinv8** [comment]
removeWindowInitialProps: HTML 中移除 window.getInitialProps 变量，避免 HTML 中有大量数据影响 SEO 效果，场景：静态站点  —— 来自官方的描述

如果需要 ssr 和 csr 配合渲染，是不能移除 initialProps 的，数据从服务端透传到前端的目的就是为了配合客户端渲染，在不请求数据的情况下让组件获得状态及属性
