### ISSUE TITLE
[Bug] 用脚手架创建的项目中无法使用webrtc的相关api

### ISSUE THREAD

**Issue by zrx1118** [umijs/umi#6641]
## What happens?
使用脚手架搭建的项目，访问navigator时去除了mediaDevices
版本 @3.4.22
1、使用 yarn create @umijs/umi-app
2、打开界面后，直接在控制台输入navigator，会找不到mediaDevices api，
![1622090229174](https://user-images.githubusercontent.com/32211201/119766827-4c7eca80-bee8-11eb-81a8-181af54b89b0.jpg)
3、打开一个空页面时
![nosite](https://user-images.githubusercontent.com/32211201/119767139-e9416800-bee8-11eb-8c6e-2094621daadb.jpg)
4、问题：用脚手架创建的项目中无法使用webrtc的相关api

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/120255778-583f0800-c2bf-11eb-8c8e-a9b3bdcc5397.png)

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/120256085-f763ff80-c2bf-11eb-8c51-391fbad6c3c1.png)
你在看下，我这边试了都是有的。

**Comment by shenyinabcd** [comment]
> ![image](https://user-images.githubusercontent.com/11746742/120256085-f763ff80-c2bf-11eb-8c51-391fbad6c3c1.png)
> 你在看下，我这边试了都是有的。

网页使用 localhost 去访问，是有 navigator.mediaDevices 的。如果用 IP 地址访问页面，navigator.mediaDevices 是 undefined 。将前端部署到 nginx，也是如此。
