### ISSUE TITLE
umi官网脚手架创建的项目，打包之后放到nginx里面，页面直接空白，没有报错，请求也是200，请问是什么原因？

### ISSUE THREAD

**Issue by raohuangxing** [umijs/umi#6645]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by robinv8** [comment]
可以排查下文件路径是否正确

**Comment by sialvsic** [comment]
参考：[为什么我本地开发是好的，部署后就没反应了，而且没有报错？](https://umijs.org/zh-CN/docs/deployment#%E9%83%A8%E7%BD%B2-html-%E5%88%B0%E9%9D%9E%E6%A0%B9%E7%9B%AE%E5%BD%95)

**Comment by leftstick** [comment]
这种问题，你至少应该弄明白，并且提供以下信息，才有助于别人帮你排查问题。

1. 是否部署在根路径下，关于这个，需要仔细理解上面 @sialvsic 提供的文档
2. `nginx` 的配置里，静态资源的配置目录和 代码存放的目录是否一致
3. `nginx` 的配置是否正确的 SPA 配置
4. 你代码带包的配置是否正确

我目前只想到这些。所以不是简单问一句『为什么空白』，别人就能给出答案。编程里涉及的因素太多了。

还有，issue不是 问答社区，要求助的话，去其他问答社区更合适

**Comment by robinv8** [comment]
> 这种问题，你至少应该弄明白，并且提供以下信息，才有助于别人帮你排查问题。
> 
>     1. 是否部署在根路径下，关于这个，需要仔细理解上面 @sialvsic 提供的文档
> 
>     2. `nginx` 的配置里，静态资源的配置目录和 代码存放的目录是否一致
> 
>     3. `nginx` 的配置是否正确的 SPA 配置
> 
>     4. 你代码带包的配置是否正确
> 
> 
> 我目前只想到这些。所以不是简单问一句『为什么空白』，别人就能给出答案。编程里涉及的因素太多了。
> 
> 还有，issue不是 问答社区，要求助的话，去其他问答社区更合适



> 这种问题，你至少应该弄明白，并且提供以下信息，才有助于别人帮你排查问题。
> 
>     1. 是否部署在根路径下，关于这个，需要仔细理解上面 @sialvsic 提供的文档
> 
>     2. `nginx` 的配置里，静态资源的配置目录和 代码存放的目录是否一致
> 
>     3. `nginx` 的配置是否正确的 SPA 配置
> 
>     4. 你代码带包的配置是否正确
> 
> 
> 我目前只想到这些。所以不是简单问一句『为什么空白』，别人就能给出答案。编程里涉及的因素太多了。
> 
> 还有，issue不是 问答社区，要求助的话，去其他问答社区更合适

可以来我们思否社区提问 https://segmentfault.com/t/umi
