### ISSUE TITLE
umi 的useRequest  和ahooks的 useRequest的问题

### ISSUE THREAD

**Issue by k983551019** [umijs/umi#6650]
UMI的 useRequest 使用中给onSuccess 给data类型会有错误提示 
![image](https://user-images.githubusercontent.com/48147837/120054627-9dff9480-c063-11eb-81f5-f4c836ab2c68.png)
![image](https://user-images.githubusercontent.com/48147837/120054685-e74fe400-c063-11eb-8636-ca3d24f12600.png)

使用ahooks的useReques如下 没有提示
![image](https://user-images.githubusercontent.com/48147837/120054696-fc2c7780-c063-11eb-9964-4b9c17b9c246.png)

 
## Context

- **Umi Version**:3.3.9
- **Node Version**:14.16.1
- **Platform**:

**Comment by xiaohuoni** [comment]
要看插件版本，不一定都是 ahooks

**Comment by k983551019** [comment]
> 要看插件版本，不一定都是 ahooks

现在就是使用umi的useReques + openApi生成的servier  会出现这个问题

**Comment by xiaohuoni** [comment]
先看你插件的版本

**Comment by k983551019** [comment]
> 先看你插件的版本

UMI 3.4.22

**Comment by xiaohuoni** [comment]
plugin-request 或者 @umijs/preset-react

**Comment by xiaohuoni** [comment]
升 preset-react 到最新的 `1.8.10`。再定位问题。

**Comment by k983551019** [comment]
> preset-react

依旧出现这个问题，
![image](https://user-images.githubusercontent.com/48147837/120257457-e072dc80-c2c2-11eb-950d-8afcef6cef1a.png)

.umi   plugin-request  里的request 用的@ahooksjs/use-request

**Comment by xiaohuoni** [comment]
https://github.com/umijs/plugins/blob/ecf3bfa223bb8c073d40402cea222de5257ac98e/packages/plugin-request/src/request.ts#L41
 
在我的项目中，这个data 是 any 类型。看源码也没看到你的这个类型

**Comment by k983551019** [comment]
> https://github.com/umijs/plugins/blob/ecf3bfa223bb8c073d40402cea222de5257ac98e/packages/plugin-request/src/request.ts#L41
> 
> 在我的项目中，这个data 是 any 类型。看源码也没看到你的这个类型

![image](https://user-images.githubusercontent.com/48147837/120260318-3c8c2f80-c2c8-11eb-889c-e6a44d77995a.png)
我这边 如果返回的是Promise<API.CustomerPickupAddress>  这种的  他的data就会是data: unknown,

如果是Promise<boolean>这种
![image](https://user-images.githubusercontent.com/48147837/120260385-62193900-c2c8-11eb-9bf2-e5ebc4bb66b2.png)
就是any

**Comment by xiaohuoni** [comment]
给个复现demo吧。

**Comment by k983551019** [comment]
> 给个复现demo吧。

我发现了，在npm start后出现。 我等下上传复现

**Comment by k983551019** [comment]
https://github.com/k983551019/useRequestOnSuccessErr
最后 start 后就会出现

**Comment by k983551019** [comment]
https://github.com/k983551019/useRequestOnSuccessErr
最后 start 后就会出现   我不回复了吗

**Comment by k983551019** [comment]
> Hello @k983551019. In order to facilitate location and troubleshooting, we need you to provide a realistic example. Please forking these link [codesandbox umi](https://codesandbox.io/s/umi-2d4js?file=/src/pages/index.tsx) or using `yarn create @umijs/umi-app` to create and upload it to your GitHub repository.
> 
> 你好 @k983551019, 为了方便定位和排查问题，我们需要你提供一个重现实例，请提供一个尽可能精简的链接 [codesandbox umi](https://codesandbox.io/s/umi-2d4js?file=/src/pages/index.tsx) 或使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://github.com/k983551019/useRequestOnSuccessErr
最后 start 后就会出现
