### ISSUE TITLE
[Bug] 使用 ssr 时不支持 hash，不支持挂载点不为空的情况

### ISSUE THREAD

**Issue by justable** [umijs/umi#6653]
## What happens?

1. 同时开启 ssr 和 hash，最终请求的资源是不带 hash 的，导致404；
2. 在 pages 目录下自定义 document.ejs，如果 root 节点有子节点就无法服务端渲染。

## Mini Showcase Repository(REQUIRED)

我用官方的 example 试了也是有问题的。

## How To Reproduce

不知道这算不算 bug，还是本来就这么设计的。

## Context

- **Umi Version**: 3.4.23
- **Node Version**: 12
- **Platform**: Windows 10

**Comment by robinv8** [comment]
这是个 bug，我已反馈官方人员，正在处理中
