### ISSUE TITLE
umi3 如何改变自定义loader在css处理过程中的顺序

### ISSUE THREAD

**Issue by Augkit** [umijs/umi#6654]
特殊的开发需求导致需要对css文件的进行AST解析后进行单位转换，所以需要自定义的testLoader在less-loader转换成css资源后对资源进行处理。

    memo.module.rules.get('less')
      .use('test-loader')
      .after(require.resolve('@umijs/deps/compiled/less-loader'))
      .loader(require.resolve('../loader/testLoader'))
但是通过如上配置对less的loader处理顺序如下：
less-loader -> postcss-loader -> css-loader -> mini-css-extract-plugin -> testLoader

期望
less-loader -> testLoader -> postcss-loader -> css-loader -> mini-css-extract-plugin

**Comment by RunningCoderLee** [comment]
试下 

```js
memo.module
  .rule('less')
  .oneOf('css')
  .use('test-loader')
  .loader(require.resolve('../loader/testLoader'))
  .after('postcss-loader')
```
