### ISSUE TITLE
SSR配合KOA如何使用nginx配置静态目录呢？

### ISSUE THREAD

**Issue by birdycn** [umijs/umi#6656]
我看到这里有注解：这里最好是用nginx配置静态目录，如果是用cdn方式部署，这里可以忽略

我尝试使用nginx的方式去部署静态文件，
```
    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        alias /www/wwwroot/abc.com/dist/;
    }
```
![image](https://user-images.githubusercontent.com/32201961/120203789-aa017700-c25a-11eb-87cb-7d41f1210c76.png)

实际上请求并没有到达nginx，在koa就被拦截处理了，因为返回koa的Not Found。

**Comment by williamnie** [comment]
如果使用nginx做静态目录，那所有的流量都要先到nginx，在有nginx转发到koa，也就是说得在nginx里配置反向代理koa的地址
