### ISSUE TITLE
路由配置按需加载的规则

### ISSUE THREAD

**Issue by lilonghe** [umijs/umi#666]
如下图, 加上 redirect 之后打包会变成一个文件, 所以对这个按需加载的规则有些疑问  
我应该怎样在路由里面配置这个 redirect 呢
![image](https://user-images.githubusercontent.com/12867278/41958599-1e449996-7a1d-11e8-85d6-94ce96e8e639.png)

有根目录重定向的 ` { path: '/', exact: true, redirect: '/users' } `
![image](https://user-images.githubusercontent.com/12867278/41958686-6073b220-7a1d-11e8-9bb7-edba33aa0226.png)

没有根目录重定向的
![image](https://user-images.githubusercontent.com/12867278/41958874-fa906e20-7a1d-11e8-95fd-63d5679fc025.png)

**Comment by amelonsamy** [comment]
同问

**Comment by sorrycc** [comment]
这是个问题，需要梳理下。

**Comment by sorrycc** [comment]
内部有个猜 CODE_SPLITTING_LEVEL 的逻辑的，会决定按需加载到路由的哪一层，这块的逻辑需要再梳理下。
