### ISSUE TITLE
升级 @umijs/preset-react@1.8.9 后，强制用户使用 access 功能

### ISSUE THREAD

**Issue by sunjiesama** [umijs/umi#6667]
![image](https://user-images.githubusercontent.com/54022918/120418566-59416980-c393-11eb-9fe6-3e6de91edc66.png)

奇怪的是，我将版本回退至升级前的版本@3.4.11,这些错误依然存在，.umi也删除了，依赖也重装了好几次，依然不行
不知道是哪里除了问题，有没有大佬指点下，谢谢了

**Comment by SturdyCat** [comment]
@umijs/plugin-layout 降到 1.8.8 不报错

**Comment by sunjiesama** [comment]
> @umijs/plugin-layout

你好，@umijs/plugin-layout是基于@ant-design/pro-layout这个依赖的吧，这个我也回退版本了，依然报错

如果你是指回退@umijs/plugin-layout，请问是怎么回退呢，我项目中没找到这个依赖

**Comment by SadWood** [comment]
> > @umijs/plugin-layout
> 
> 你好，@umijs/plugin-layout是基于@ant-design/pro-layout这个依赖的吧，这个我也回退版本了，依然报错
> 
> 如果你是指回退@umijs/plugin-layout，请问是怎么回退呢，我项目中没找到这个依赖

缺少`src/access.ts`文件，按文档加上就可以了。

[@umijs/plugin-access](https://umijs.org/zh-CN/plugins/plugin-access#%E5%90%AF%E7%94%A8%E6%96%B9%E5%BC%8F)

**Comment by sunjiesama** [comment]
> > > @umijs/plugin-layout
> > 
> > 
> > 你好，@umijs/plugin-layout是基于@ant-design/pro-layout这个依赖的吧，这个我也回退版本了，依然报错
> > 如果你是指回退@umijs/plugin-layout，请问是怎么回退呢，我项目中没找到这个依赖
> 
> 缺少`src/access.ts`文件，按文档加上就可以了。
> 
> [@umijs/plugin-access](https://umijs.org/zh-CN/plugins/plugin-access#%E5%90%AF%E7%94%A8%E6%96%B9%E5%BC%8F)


此方案实测可行

非常感谢这位**大佬**，一下子就解决了困惑了我一上午的问题
