### ISSUE TITLE
@umijs/test 依赖升级，将jest-environment-jsdom-fourteen升级为jest-environment-jsdom@^26.6.2

### ISSUE THREAD

**Issue by jackluson** [umijs/umi#6668]
用@testing-library/user-event 时，https://github.com/testing-library/user-event/issues/391 这个问题的修复依赖底层库的更新

![image](https://user-images.githubusercontent.com/36684351/120421991-eedff780-c399-11eb-8ded-c00f60255bbb.png)

**Comment by leshalv** [comment]
我这安装也报错了，还没解决吗？
yarn 1.22.17
