### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by chenfengyanyu** [umijs/umi#667]
抱歉，查看了所有该问题的方案，并没有解决问题，所以这里又提出来。
依赖如下：
```
"dva": "^2.2.3",
"umi": "^1.3.11",
"umi-plugin-dva": "^0.1.6",
"umi-plugin-routes": "^0.1.5"
```
然后，启动 npm run start，就会报出这个错：
```
Uncaught SyntaxError: Unexpected token <
```
根据以往的issues来看，作者认为public/index.html 中重复引用了index.js导致了问题：
```
<script src="index.js"></script>
```
所以，将其注释。重启npm run start之后，
http://localhost:8000/ 成了白屏，并没有任何错误（pages目录下的路由都可以访问，也都正常。）

到这里，问题就变成了启动之后首页白屏，不知道有没有遇到同样问题的童鞋。在线等待高手解答，挺着急的🙈

**Comment by sorrycc** [comment]
先把 umi-plugin-dva 更新到 0.9.x 试试。

**Comment by chenfengyanyu** [comment]
@sorrycc umi-plugin-dva 已经更新到0.9.1，启动后 http://localhost:8000/ 依然是白屏，这里提供一个可复现的demo，麻烦大神看看是哪里用的不对。

**Comment by okoala** [comment]
删除 public/index.html
删除 package-lock.json

依赖如下：
"dependencies": {
    "antd": "^3.6.4",
    "antd-mobile": "^2.2.1",
    "dva": "^2.3.1",
    "react": "^16.4.1",
    "umi": "^1.3.12",
    "umi-plugin-dva": "^0.9.1"
  }

删除 node-modules 重新 install 运行

最后~

![image](https://user-images.githubusercontent.com/2127199/42017371-5778e7d4-7ae1-11e8-84c3-461b06bc1518.png)

**Comment by chenfengyanyu** [comment]
@okoala 确实可以了，感谢～
