### ISSUE TITLE
似乎是 import 动态加载的问题

### ISSUE THREAD

**Issue by amily4555** [umijs/umi#668]
似乎我很容易碰到怪异问题

import 的资源，似乎有个等待时间~~ 在其他情况下 都可以直接读出，在此页面不行~~ 
setTimeout 下有内容读出·~~

![image](https://user-images.githubusercontent.com/2802841/41973588-f959dcba-7a47-11e8-90b1-e812f1d0344d.png)

![image](https://user-images.githubusercontent.com/2802841/41973556-e0ed79f2-7a47-11e8-985d-9578f1e89331.png)

**Comment by sorrycc** [comment]
import 的内容不能直接打印的，需要在函数里吧。

**Comment by amily4555** [comment]
如果不能打印 那么赋值也是非法操作了~~~~

import {Menu} from 'antd';
const SubMenu = Menu.SubMenu;
const MenuItemGroup = Menu.ItemGroup;

**Comment by zjxpcyc** [comment]
@amily4555 你应该去看下 import 与 require 的区别
