### ISSUE TITLE
Umi2 / Umi3如何在路由上添加国际化语言

### ISSUE THREAD

**Issue by yuanjiangzhjh** [umijs/umi#6694]
例如: localhost:8000/zh-CN/demo
可通过修改路由进行跳转
也可以点击国际化语言进行切换
用的是locale没有使用i18n进行切换

**Comment by xiaohuoni** [comment]
配置路由的直接配就好了。约定式的按约定目录分级。

**Comment by yuanjiangzhjh** [comment]
如何直接配置呀

**Comment by xiaohuoni** [comment]
配置 [routes](https://umijs.org/config#routes) 啊！多写一遍路由。

**Comment by yuanjiangzhjh** [comment]
有demo吗 大佬

**Comment by xiaohuoni** [comment]
可以随便跑一个 dumi 项目，看生成的 routes 配置。

**Comment by xiaohuoni** [comment]
是的啊。
![image](https://user-images.githubusercontent.com/11746742/121160409-a5eae000-c87e-11eb-8c40-703bab7ccf06.png)

**Comment by yuanjiangzhjh** [comment]
谢谢

**Comment by hold-baby** [comment]
约定式路由可以写在顶级吗
比如：/pages/[local]/demo
@xiaohuoni

**Comment by hold-baby** [comment]
/pages/[local$]/demo 解决问题
