### ISSUE TITLE
如何去除 npm build 后的输出？umi version    

### ISSUE THREAD

**Issue by 1c7** [umijs/umi#6697]
去除这个
```
<script>      
 //! umi version: 3.4.25     
</script>
```

![image](https://user-images.githubusercontent.com/1804755/120881726-decc5000-c605-11eb-8d6f-c5986e9b8a93.png)

**Comment by 1c7** [comment]
本地当然可以直接修改 `dist/index.html`，但是一些其他地方（比如 Github Action 里 build 的时候）就不好改。
问一下有没有配置项直接关掉。

**Comment by xiaohuoni** [comment]
有什么影响吗？

**Comment by 1c7** [comment]
没有功能上的影响，只有心理上的影响，希望整个页面可以自己掌控，而不是用了某个框架之后有一些自己无法控制的东西。

**Comment by 1c7** [comment]
文档里并没有提到如何去掉 `//! umi version [版本号]` 的配置。

顺带咨询一下什么是`补丁方案` 和 `自动化 external `
![image](https://user-images.githubusercontent.com/1804755/120970446-07874d80-c79e-11eb-91a2-c82961614dda.png)

**Comment by serenespring** [comment]
> 有什么影响吗？

应该怎么去掉呢，安全扫描说这个有安全风险

**Comment by xiaohuoni** [comment]
@sorrycc

**Comment by 1c7** [comment]
@sorrycc

**Comment by 303394539** [comment]
可以在modifyDevHTMLContent和modifyProdHTMLContent的先去掉html中的注释，然后replace空的<script>标签就可以了

**Comment by haoxiaoshu6** [comment]
没解决吧@1c7

**Comment by iainlau** [comment]
配置文件里加个 `umiInfo: false` 就行了。

**Comment by 1c7** [comment]
@iainlau 感谢答疑
