### ISSUE TITLE
初始化的新项目 为什么 umi.css 有 ant的css

### ISSUE THREAD

**Issue by too-cdn** [umijs/umi#6700]
![image](https://user-images.githubusercontent.com/72249285/120987509-3ad2d800-c7b0-11eb-9cfd-2e8884489c7a.png)

## Context

"umi": "^3.4.25"

**Comment by ahwgs** [comment]
好像是默认使用了 @umijs/preset-react 插件，你看下你的配置文件 `antd ` 有没有打开
https://umijs.org/zh-CN/plugins/plugin-antd

**Comment by too-cdn** [comment]
@ahwgs  我没配置

**Comment by MakerTED** [comment]
默认会开启整合 antd 组件库。

插件说明文档： https://umijs.org/zh-CN/plugins/plugin-antd。

如果不希望使用 antd，需要在配置文件中设置 `antd: false`。
