### ISSUE TITLE
umi 的useRequest 和ahooks的 useRequest的问题

### ISSUE THREAD

**Issue by k983551019** [umijs/umi#6701]
UMI的 useRequest 使用中给onSuccess 给data类型会有错误提示 
![image](https://user-images.githubusercontent.com/48147837/120054627-9dff9480-c063-11eb-81f5-f4c836ab2c68.png)
![image](https://user-images.githubusercontent.com/48147837/120054685-e74fe400-c063-11eb-8636-ca3d24f12600.png)

使用ahooks的useReques如下 没有提示
![image](https://user-images.githubusercontent.com/48147837/120054696-fc2c7780-c063-11eb-9964-4b9c17b9c246.png)

 复现仓库
https://github.com/k983551019/useRequestOnSuccessErr
最后 start 后就会出现

## Context

- **Umi Version**:3.3.9
- **Node Version**:14.16.1
- **Platform**:

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/121180362-582ca280-c893-11eb-9cfe-ded0c4ffae40.png)

umijs 里面导出的 useRequest，要求返回数据包一层 data~

**Comment by k983551019** [comment]
> ![image](https://user-images.githubusercontent.com/12526493/121180362-582ca280-c893-11eb-9cfe-ded0c4ffae40.png)
> 
> umijs 里面导出的 useRequest，要求返回数据包一层 data~

我返回的数据是data里的。所以怎么解决这个提醒错误

**Comment by brickspert** [comment]
> > ![image](https://user-images.githubusercontent.com/12526493/121180362-582ca280-c893-11eb-9cfe-ded0c4ffae40.png)
> > umijs 里面导出的 useRequest，要求返回数据包一层 data~
> 
> 我返回的数据是data里的。所以怎么解决这个提醒错误

`onSuccess: (data: API.CustomerGoodsNameManage['data'])=>{}`

**Comment by k983551019** [comment]
> > > ![image](https://user-images.githubusercontent.com/12526493/121180362-582ca280-c893-11eb-9cfe-ded0c4ffae40.png)
> > > umijs 里面导出的 useRequest，要求返回数据包一层 data~
> > 
> > 
> > 我返回的数据是data里的。所以怎么解决这个提醒错误
> 
> `onSuccess: (data: API.CustomerGoodsNameManage['data'])=>{}`

不行，  依旧会出 错误提示

**Comment by k983551019** [comment]
![image](https://user-images.githubusercontent.com/48147837/121647623-33ba0b80-cac9-11eb-9253-64ed450fc78c.png)
使用 fetchKey 同样出现该问题

**Comment by oyhk** [comment]
为什么我的请求成功了，Network也看到接口有数据返回了，onSuccess 没有数据返回呢？
`    const loginUseRequest = useRequest((payload) => ({
      url: `http://localhost:8001/business/user_business/login`,
      method: HttpMethod.post,
      data: payload,
    }), {
      manual: true,
      onSuccess: (r, p) => {
        console.log('onSuccess', r);
      }
    },
  );`
