### ISSUE TITLE
[Bug] public 文件下新增了一个index.html文件, build的时候并未直接覆盖过去

### ISSUE THREAD

**Issue by jiujiaonuannan** [umijs/umi#6704]
## What happens?

在public 文件下新增了一个html文件, build的时候并未直接覆盖过去
https://umijs.org/zh-CN/docs/cli#umi-build 和这里描述不相符

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

// https://umijs.org/config/
import { defineConfig } from 'umi'
import webpackPlugin from './webpack.config'
import theme from './theme.config'
import proxy from './proxy'
import routes from './routes'

const { REACT_APP_ENV } = process.env

export default defineConfig({
  sula: {
    locale: {
      default: 'zh-CN',
    },
  },
  extraBabelPlugins: [
    // libraryDirectory: 'es' 必须这样写
    ['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }],
  ],
  hash: true,
  antd: {},
  dva: {
    hmr: true,
  },
  locale: {
    default: 'zh-CN',
    antd: true,
    // default true, when it is true, will use `navigator.language` overwrite default
    baseNavigator: true,
  },
  targets: {
    ie: 11,
  },
  // umi routes: https://umijs.org/docs/routing
  routes,
  // Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme,
  // // @ts-ignore
  title: false,
  ignoreMomentLocale: true,
  proxy: proxy[REACT_APP_ENV || 'dev'],
  chainWebpack: webpackPlugin,
})

## Context

- **Umi Version**:  3.2.14
- **Node Version**: v12.14.1
- **Platform**: web

**Comment by PeachScript** [comment]
要定制入口 html 请使用 document.ejs，public 是用来拷贝静态资源的，参考：https://umijs.org/zh-CN/docs/html-template

**Comment by jiujiaonuannan** [comment]
用这种方式的话 想要根据不同环境自定义cdn地址 好像不奏效
步骤:
1. 在config.ts runtimePublicPath: true
2. 在document.ejs中添加下面这一段
```
<script>
    window.publicPath = <%= '%PUBLIC_URL%/static/admin' %>
  </script>
```

但是最终打包出来的路径并未包含cdn地址

**Comment by PeachScript** [comment]
`runtimePublicPath` 只是告诉 webpack 加载异步资源的时候拼上 window.publicPath，具体 CDN 地址仍然需要自己配置到 publicPath 变量上，可以通过 config 配、也可以自己写 headScript 在 runtime 配
