### ISSUE TITLE
[Bug] 加载页面时有时候一直显示loading，手动刷新可恢复

### ISSUE THREAD

**Issue by quicklearning123** [umijs/umi#6712]
## What happens?
```
  dynamicImport: {
    loading: '@ant-design/pro-layout/es/PageLoading',
  },
```

![image](https://user-images.githubusercontent.com/70048681/121316802-45ba7380-c93c-11eb-9203-57283819eaa7.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.3.7
- **Node Version**: 14
- **Platform**:mac

**Comment by xiaoshui222** [comment]
> ## What happens?
> ```
>   dynamicImport: {
>     loading: '@ant-design/pro-layout/es/PageLoading',
>   },
> ```
> 
> ![image](https://user-images.githubusercontent.com/70048681/121316802-45ba7380-c93c-11eb-9203-57283819eaa7.png)
> 
> ## Mini Showcase Repository(REQUIRED)
> > Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库
> 
> ## How To Reproduce
> **Steps to reproduce the behavior:** 1. 2.
> 
> **Expected behavior** 1. 2.
> 
> ## Context
> * **Umi Version**: 3.3.7
> * **Node Version**: 14
> * **Platform**:mac

请问你解决了吗，我也是这样

**Comment by Jeannette0217** [comment]
我也遇到这种无限loading ,手动刷新的问题

**Comment by huyawei** [comment]
现在服务器构建如果把构建缓存留着偶尔还会卡图片

**Comment by marong1997** [comment]
> 老哥解决了没，我现在都不是手动刷新的问题了 卡loading 有的模块 刷了也没用

请问你们的问题解决了吗？

**Comment by zhidali** [comment]
现在还有这个问题，偶现
umi：3.5.20
react: 17.x

**Comment by marong1997** [comment]
> 现在还有这个问题，偶现 umi：3.5.20 react: 17.x

我的是 umi 3.5.30
react： 17.x
