### ISSUE TITLE
[Bug] 通过define定义的环境变量不能使用解构

### ISSUE THREAD

**Issue by jiujiaonuannan** [umijs/umi#6718]
## What happens?

通过define定义的环境变量解构的时候都是undefined

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

1. 在config文件下面创建不同环境的环境变量, 使用A方法拿不到值 B方法可以获取到
2. 在app.ts下面render 方法使用
A: const { accountsUrl } = process.env
B: process.env.accountsUrl

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
你配置怎么写的？
```
define: {
    REACT_APP: process.env.REACT_APP
  }
```
这么写的话，在项目中取值是 `REACT_APP`

**Comment by jiujiaonuannan** [comment]
define: {
    'process.env.publicPath': 'https://xxx.devfdg.net',
  }

**Comment by jiujiaonuannan** [comment]
这样写的

**Comment by xiaohuoni** [comment]
那他就是一个字符串 `process.env.publicPath`

**Comment by jiujiaonuannan** [comment]
噢噢明白了!
