### ISSUE TITLE
ssr-with-eggjs 例子中 开启 dynamicImport 页面出错

### ISSUE THREAD

**Issue by LaughingZhu** [umijs/umi#6722]
目的：在拆分build后的文件。
![image](https://user-images.githubusercontent.com/20132891/121778446-84189280-cbc9-11eb-83ac-bd6db4c805bb.png)

结果如下：
![image](https://user-images.githubusercontent.com/20132891/121778495-a9a59c00-cbc9-11eb-98b0-49f0c61e161c.png)

**Comment by falcon11** [comment]
the same problem

**Comment by falcon11** [comment]
> the same problem

I solve this problem by setting public path as follow

```js
export default defineConfig({
  ssr: {
    devServerRender: false,
  },
  hash: true,
  outputPath: '../public',
  manifest: {
    fileName: '../../config/manifest.json',
  },
  dynamicImport: {},
  publicPath: process.env.NODE_ENV === 'development' ? process.env.PUBLIC_PATH : '/public/',
});
```
