### ISSUE TITLE
[Bug] 环境变量PORT不起作用

### ISSUE THREAD

**Issue by Grart** [umijs/umi#6724]
配置如下：

    "start": "cross-env UMI_ENV=dev PORT=8100 umi dev",

输出了下process.env.PORT，参数确实已经输入了，但启动后端口是另一个

  App running at:
  - Local:   http://localhost:8186 (copied to clipboard)

运行环境：
WINDOWS10 专业版
node v14.15.5
npm 6.14.11

包：
    "umi": "^3.4.25",
    "@umijs/fabric": "^2.5.2",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/plugin-esbuild": "^1.0.1",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-dumi": "^1.1.7",
    "@umijs/preset-react": "^1.7.4",
    "@umijs/yorkie": "^2.0.3",
    "carlo": "^0.9.46",
    "cross-env": "^7.0.3",
    "cross-port-killer": "^1.1.1",
    "detect-installer": "^1.0.1",
    "enzyme": "^3.11.0",
    "eslint": "^7.1.0",
    "express": "^4.17.1",
    "gh-pages": "^3.0.0",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.0.1-beta3",
    "prettier": "^2.0.1",
    "puppeteer-core": "^8.0.0",
    "stylelint": "^13.0.0",
    "typescript": "^4.2.2"

**Comment by xiaohuoni** [comment]
我这边是有效的，你看看你8100端口是否被占用了，然后看下是不是有其他的地方写了使用 `8186` 端口
![image](https://user-images.githubusercontent.com/11746742/121979645-25b40580-cdbd-11eb-9886-fa9ea8c5150d.png)

**Comment by Grart** [comment]
今天端口变成 8286了，不存在端口占用。用netstat -ano |findstr 8100 查过了

![1](https://user-images.githubusercontent.com/6634875/122037453-2d000100-ce07-11eb-9708-8a1812b0944d.png)

**Comment by Grart** [comment]
没事了，是系统问题。
看了下代码，在文件 @umijs\preset-built-in\lib\plugins\commands\dev\dev.js 下
会调用portfinder.js 从设置端口开始查找可用端口。
port = yield portfinder.getPortPromise({
          port: defaultPort ? parseInt(String(defaultPort), 10) : 8000
        }); 
发现很多端口使用返回 EACCES 错误，应该跟我本地VPN或虚拟有关。

建议出现这种需要自动更换端口的情况，最好给个warn.
