### ISSUE TITLE
[Feature Request] 当启用按需加载后，怎样把很小（几KB）的 chunk.css 文件合并为单个文件，async.js 同样。

### ISSUE THREAD

**Issue by DQ-Mac** [umijs/umi#6727]
当启用按需加载后，会生成很多很小的  chunk.css 和 async.js 文件，只有几 KB。 

如果可以把较小的 chunk.css 和 async.js 合并成单个文件，这样可以减少浏览器的请求次数。

**Comment by xiaoyierle** [comment]
+1

**Comment by xiaoyierle** [comment]
![截屏2021-07-21 下午6 16 22](https://user-images.githubusercontent.com/24968758/126473208-5ec828e9-0066-4489-8fe4-4d02257701d3.png)
我打包出来有这么多文件，基本上每个都差不多
