### ISSUE TITLE
[Bug] @umijs/bundler-webpack中引用的normalize-url版本过低，有安全漏洞

### ISSUE THREAD

**Issue by liuzhuang-bud** [umijs/umi#6733]
![image](https://user-images.githubusercontent.com/81223346/122166613-75252f00-ceac-11eb-9f28-9d3a99d562b1.png)

![image](https://user-images.githubusercontent.com/81223346/122166638-7b1b1000-ceac-11eb-8389-f4b427865de7.png)

请将normalize-url版本升至6.0.1

**Comment by dqrjz** [comment]
同求，一年多了，麻烦升级一下吧

**Comment by HaishengLiang** [comment]
fix by https://github.com/umijs/umi/pull/11398
