### ISSUE TITLE
[Bug] 关于@umijs/plugin-access路由权限bug

### ISSUE THREAD

**Issue by ISBN9527** [umijs/umi#6738]
## What happens?
后端返回权限字段permList:["1","2","3"] (比如说每个数字对应该菜单显示与否)

### access.ts
简单处理后得到 `{"1":true,"2":true,"3":true};`

### routes.ts
`{`
    `path: '/admin',`
    `name: '管理页',`
   ` icon: 'SafetyCertificateOutlined',`
    `component: './admin/Admin',`
    `access: '4',`
`}`

 处理时发现access没有对应4的权限为什么也会显示呢，在我的理解没有就应该不显示啊

### 复现地址
https://github.com/ISBN9527/umi-access-demo

## Context

- **Umi Version**: 3.4.0
- **Node Version**: 16.0
- **Platform**: 谷歌浏览器

**Comment by ISBN9527** [comment]
@sorrycc @xiaohuoni 
请大佬赐教

**Comment by xiaohuoni** [comment]
plugin-access 这个插件的特性就是没有写明表示有访问权限。你加上`{"4":false}`就可以拦截了。不过我觉得应该有个什么api控制，当不写时表示没有访问权限，所以我加了一个严格模式。https://github.com/umijs/plugins/pull/636

**Comment by ISBN9527** [comment]
umi: 3.4.25
在routes.ts的添加属性可用吗？
`{`
`path: '/admin',`
`name: '管理页',`
`icon: 'SafetyCertificateOutlined',`
`component: './admin/Admin',`
`access: '4',`
strictMode:true
`}`

**Comment by xiaohuoni** [comment]
不是这样用的，是config里面 { access:{ strictMode:true }}

**Comment by ISBN9527** [comment]
pro现在还有人维护吗？大佬

**Comment by ISBN9527** [comment]
[#8613](https://github.com/ant-design/ant-design-pro/issues/8613)

**Comment by ISBN9527** [comment]
> 不是这样用的，是config里面 { access:{ strictMode:true }}

报错啊

**Comment by ISBN9527** [comment]
> access:{ strictMode:true }



> > 不是这样用的，是config里面 { access:{ strictMode:true }}
> 
> 报错啊`Error: Invalid config key: access`

**Comment by xiaohuoni** [comment]
没有发包啊。你自己搞个私包玩玩？

**Comment by HeiShuXianSheng** [comment]
请问你怎么解决的呀？

**Comment by ISBN9527** [comment]
我好长时间没有用umi了，当时好像是处理了下后端返回的格式，符合umi的数据格式

**Comment by feiyu1995** [comment]
请问解决了吗

**Comment by ISBN9527** [comment]
弃用了

> 请问解决了吗

**Comment by xiaohuoni** [comment]
更新包之后，使用 { access:{ strictMode:true }} 解决

**Comment by vespex** [comment]
> 更新包之后，使用 { access:{ strictMode:true }} 解决

请问更新到那个版本？我更新umi到3.5.20都还是提示 `Invalid config key: access`

**Comment by sakura-flutter** [comment]
> > 更新包之后，使用 { access:{ strictMode:true }} 解决
> 
> 请问更新到那个版本？我更新umi到3.5.20都还是提示 `Invalid config key: access`

用 Proxy 先代替一下吧，手动改为没值的时候返回 false，我升级 @umijs/preset-react 和 @umijs/plugin-access 都会报错

**Comment by itsstudio** [comment]
Invalid config key: access 也是出现这个问题，以下是临时解决办法

routes.js
path:'xxxx',
name:'A',
component:'@/xxxx/xxx',
access:'CAN_ACCESS_A'

access.js
export default function access(initialState) {
    const { 检测Obj } = initialState || {};

    return {
        CAN_ACCESS_A: () => 检测Obj?.A ?? false,
    };
}
总结：就是把所有页面都access值都写在access.js里，如果检测obj里没有，就返回false

**Comment by JbfGod** [comment]
> > 更新包之后，使用 { access:{ strictMode:true }} 解决
> 
> 请问更新到那个版本？我更新umi到3.5.20都还是提示 `Invalid config key: access`

将 @umijs/preset-react 升级至 >= 2.1.0版本

**Comment by Lsnsh** [comment]
> > > 更新包之后，使用 { access:{ strictMode:true }} 解决
> > 
> > 
> > 请问更新到那个版本？我更新umi到3.5.20都还是提示 `Invalid config key: access`
> 
> 将 @umijs/preset-react 升级至 >= 2.1.0版本

亲测可行，具体可以参考这个 issue https://github.com/umijs/umi/issues/8043#issuecomment-1109301893
