### ISSUE TITLE
[Bug] 编译时如何把routes部分代码分离出来

### ISSUE THREAD

**Issue by ArcherWong** [umijs/umi#6739]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
什么需求，能不能描述清楚一点？

**Comment by ArcherWong** [comment]
在同一个umi应用下，分别有A、B两个产品页面，打包时我想分别输出A、B两个产品各自的页面文件和路由配置文件，配合基座文件可以自由组合成A页面应用，B页面应用，AB页面应用

**Comment by ArcherWong** [comment]
@xiaohuoni 大佬，帮忙看下是否可行
