### ISSUE TITLE
[Bug]@umijs/plugin-access路由权限bug，跳转无权限页面时，会出现空白内容，而不是403页面

### ISSUE THREAD

**Issue by zhgt1997** [umijs/umi#6741]
在a页面中点击一个按钮，可以跳转到其他菜单中的二级页面b
但是在配置权限时，没有配置b页面的权限，导致跳转页面时会出现空白内容，只有重新刷新才会出现403页面

期望解决的问题：跳转无权限的页面时，直接出现403页面，而不是空白内容；

![image](https://user-images.githubusercontent.com/39938981/122388936-f363fd00-cfa2-11eb-864f-3da7a81968c1.png)

![image](https://user-images.githubusercontent.com/39938981/122389323-67060a00-cfa3-11eb-980b-38ea59ca31d2.png)

**Comment by xiaohuoni** [comment]
你升级到最新试试，我在看另一个[问题](https://github.com/umijs/umi/issues/6738)时，发现会正确跳准，你可以看看这个 demo:https://github.com/ISBN9527/umi-access-demo
