### ISSUE TITLE
[Bug] IE 11 ERROR

### ISSUE THREAD

**Issue by 0123cf** [umijs/umi#6752]
```
defineConfig({
  fastRefresh: {}, 
  title: '',
  favicon: '/favicon.ico',
  hash: true,
  targets: {
    ie: 9,
  },
  history: {
    type: 'hash',
  },
  define: {
    interval: 50,
  },
  nodeModulesTransform: {
    type: 'all',
  },
  dva: {
    immer: false
  },
  theme: {
    '@primary-color': '#5C7E57',
  },
})
```

![image](https://user-images.githubusercontent.com/22963895/122863751-f6217200-d355-11eb-9ccd-36475290a21a.png)

**Comment by 0123cf** [comment]
error --- >  webpack:///src/.umi/core/devScripts.ts

**Comment by 0123cf** [comment]
package.json
```
{
"dependencies": {
    "@ant-design/charts": "^1.1.4",
    "@ant-design/pro-layout": "^6.5.0",
    "@umijs/preset-react": "1.x",
    "umi": "^3.4.22"
  }
}
```

**Comment by 0123cf** [comment]
经过排查，注释 fastRefresh: {},就可以了。
但是其他项目开了这个也可以，请问开发者，这个是什么原因？

**Comment by xu-Aurora** [comment]
我也碰到这个问题了，注释 fastRefresh: {}还是不可以，请问有解决嘛？

**Comment by 0123cf** [comment]
> 我也碰到这个问题了，注释 fastRefresh: {}还是不可以，请问有解决嘛？

你是什么错误，如果像监头函数\class之类的报错，可以设置targets, 记得配合nodeModulesTransform。

**Comment by xu-Aurora** [comment]
> > 我也碰到这个问题了，注释 fastRefresh: {}还是不可以，请问有解决嘛？
> 
> 你是什么错误，如果像监头函数\class之类的报错，可以设置targets, 记得配合nodeModulesTransform。

就是你你上面ie的截图的错误

**Comment by WLyKan** [comment]
我在讨论区提了一个疑问，https://github.com/umijs/umi/discussions/6761

**Comment by cecil-su** [comment]
好像是@umijs/utils/lib/ssr.js 造成的，打包完还有const 和 箭头函数的语法，手动改完好像就可以了

**Comment by simplast** [comment]
+1
