### ISSUE TITLE
Umi 3 开启webpack5 使用 Module Federation  遇到的一些问题

### ISSUE THREAD

**Issue by miroku-y** [umijs/umi#6753]
## Background

"umi": "3.4.25"
.umirc.ts 开启 webpack5: {}  ，目的是使用 模块联邦

## Proposal

1.模块联邦的提供方无需修改publicPath ，每一个环境都得去定义，包括使用侧，默认是"/",如果不修改，加载不了对应的remoteEntry.js
    
2.使用侧不应该额外的去配置dynamicImport，目的是使用webpack5 的模块联邦，但是前提得开启dynamicImport，开启后loading +空白页不是很友好

## Additional context

1.模块联邦提供方配置：
const { ModuleFederationPlugin } = require("webpack").container;
![image](https://user-images.githubusercontent.com/28189459/122865117-64ffca80-d358-11eb-81a4-76546612eac1.png)

2.调用侧配置：
![image](https://user-images.githubusercontent.com/28189459/122866593-cc1e7e80-d35a-11eb-885d-12d3dc1e5ffc.png)

调用侧在不开启dynamicImport 的情况下又能正常加载remoteEntry.js 需额外处理成：
````
api.modifyBabelPresetOpts(opts => {
    return {
      ...opts,
      dynamicImportNode: false,
    };
  });
  ````
## 
当前已在umi 3 中正常跑起 webpack5 的模块联邦，过程不是很顺畅(可能是用法不对)，官方能否有一个合适的demo 以方便大家接入。

**Comment by miroku-y** [comment]
重新提一个带复现demo 的

**Comment by zhaoxiyang** [comment]
关注一下 umi3 + Federation

**Comment by jiechud** [comment]
@miroku-y 
1.模块联邦的提供方无需修改publicPath ，每一个环境都得去定义，包括使用侧，默认是"/",如果不修改，加载不了对应的remoteEntry.js

这个问题可以配置为`auto`，可以参考 https://juejin.cn/post/6980238993296195621#heading-11

**Comment by mokinzhao** [comment]
umi3 + Federation +1  多关注一下

**Comment by Lisheri** [comment]
> @miroku-y 1.模块联邦的提供方无需修改publicPath ，每一个环境都得去定义，包括使用侧，默认是"/",如果不修改，加载不了对应的remoteEntry.js
> 
> 这个问题可以配置为`auto`，可以参考 https://juejin.cn/post/6980238993296195621#heading-11

如果是auto, 如何解决刷新后请求模块的问题呢?请求会从当前url发出, 导致找不到对应的模块
