### ISSUE TITLE
tsx使用class报ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by yyyyy210** [umijs/umi#676]
![1d](https://user-images.githubusercontent.com/4918883/42071176-96d06f82-7b8c-11e8-8487-a2808fa3aa37.jpg)

###class：报错 ReferenceError: exports is not defined
```javascript
class Login extends React.Component {
  render() {
    return (
      <div> Button </div>
    );
  }
}
export default Login
```
###function 正常
```javascript
function Login() {
 
  return (
    <div>
      Hello
    </div>
  );
}
export default Login
```

**Comment by yutingzhao1991** [comment]
是不是自己加了什么 webpack 的插件？有没有可以复现的 repo。

**Comment by yyyyy210** [comment]
用的是这个 https://github.com/umijs/umi-dva-user-dashboard

**Comment by yyyyy210** [comment]
@yutingzhao1991 用的是这个 https://github.com/umijs/umi-dva-user-dashboard 看蛮干净的

**Comment by iceberg211** [comment]
是export吧
`export default A`
