### ISSUE TITLE
[Bug] umi 3.4.25 中使用 webpack5 module federation 报错

### ISSUE THREAD

**Issue by miroku-y** [umijs/umi#6763]
## What happens?

umi 3.4.25 中开启webpack5 使用其模块联邦

## Mini Showcase Repository(REQUIRED)

重现demo: git@github.com:hubinfo123/module-federation-umi.git

## How To Reproduce

1. 分别在app1, app2 中执行 
yarn 

    yarn start 

2. 获得以下错误
![image](https://user-images.githubusercontent.com/60164480/123033939-2f6fe580-d41b-11eb-8844-0a358b4fcffa.png)

同webpack  官方故障一样，但是umi 目前无法模拟webpack 官方bootstrap.js ，使入口文件异步加载
https://webpack.js.org/concepts/module-federation/

目前是通过自定义插件的形式修改了umi.ts,模拟了webpack官方场景，是可用的。

**Comment by xiaohuoni** [comment]
试试 umi@3.5.0-beta.9 的 mfsu 功能

**Comment by baoman** [comment]
@miroku-y 自定义插件能分享一下吗？使用webpack5的webpack5 module federation都有入口文件异步加载的问题

**Comment by jiechud** [comment]
@miroku-y @baoman 可以看下这个 https://juejin.cn/post/6980238993296195621#heading-12 
插件地址： https://github.com/jiechud/umi-plugin-mf-bootstrap

还有个问题，就是和微前端qiankun结合的时候还有问题

**Comment by miroku-y** [comment]
> @miroku-y 自定义插件能分享一下吗？使用webpack5的module federation都有入口文件异步加载的问题

1.步 建一个 entry.js 
2. entry.js import ("./umi") 
3.把入口entry改了 改为 entry.js

**Comment by BH-M87** [comment]
也遇到了这个问题，这个问题应该是存在的。为啥close了？

**Comment by zjjjjjjjjjjd** [comment]
> > @miroku-y 自定义插件能分享一下吗？使用webpack5的module federation都有入口文件异步加载的问题
> 
> 1. 建一个 entry.js
> 2. entry.js import ("./umi")
> 3. 把入口entry改了 改为 entry.js

这么做没问题，但这样无法和qiankun一起使用

**Comment by miroku-y** [comment]
> > > @miroku-y 自定义插件能分享一下吗？使用webpack5的module federation都有入口文件异步加载的问题
> > 
> > 
> > 
> > 1. 建一个 entry.js
> > 2. entry.js import ("./umi")
> > 3. 把入口entry改了 改为 entry.js
> 
> 这么做没问题，但这样无法和qiankun一起使用

可以同时使用，我项目里面就同时存在，主要是看你出现了哪些问题

**Comment by Anglay** [comment]
> > > > @miroku-y 自定义插件能分享一下吗？使用webpack5的module federation都有入口文件异步加载的问题
> > > 
> > > 
> > > 
> > > 1. 建一个 entry.js
> > > 2. entry.js import ("./umi")
> > > 3. 把入口entry改了 改为 entry.js
> > 
> > 
> > 这么做没问题，但这样无法和qiankun一起使用
> 
> 可以同时使用，我项目里面就同时存在，主要是看你出现了哪些问题

案例分享一下，大佬

**Comment by caojialuo** [comment]
> > 这么做没问题，但这样无法和qiankun一起使用



> 

有工具可以在qiankun修改入口文件吗，自动生成的umi.ts
