### ISSUE TITLE
[Bug] 升级umi至3.5.0-beta.8开启mfsu出错

### ISSUE THREAD

**Issue by ISBN9527** [umijs/umi#6764]
## What happens?
升级umi至3.5.0-beta.8开启mfsu出错
在antd-pro使用mfsu

1. 升级umi从3.4.25-->3.5.0-beta.8
2. 使用的是antd-pro，根据umi官方配置，在config.ts配置如步骤3
3. `mfsu: {
  includes: [
    'rc-util/es/hooks/useMergedState',
    'swagger-ui-react',
    'moment',
    'moment/locale/*',
    'events',
    'lodash',
    '@ant-design/pro-layout/es/PageLoading',
    'antd/es/locale/*',
    'querystring',
  ],
  redirect: {
    '@umijs/plugin-request/lib/ui': {
      message: 'antd',
      notification: 'antd',
    },
  },
},
`

## 报错日志
`Validate config "mfsu" failed, "includes" is not allowed`

## 还是在antd-pro，如果直接开启mfsu:{}会报如下错误
![image](https://user-images.githubusercontent.com/30942709/123051906-d01ecf00-d434-11eb-998a-703f7784e0d5.png)

## Context

- **Umi Version**:  "^3.5.0-beta.8"
- **Node Version**:  16.3
- **Platform**: mac

**Comment by sorrycc** [comment]
node_modules/@umijs 下有 runtime 目录吗？

**Comment by ISBN9527** [comment]
直接配置mfsu:{}，安装@umijs/runtime后还是报错，用的yarn

**Comment by sorrycc** [comment]
没解答第二个问题，另外给个复现？

**Comment by ISBN9527** [comment]
`node_modules/@umijs`没有runtime目录

**Comment by ISBN9527** [comment]
复现地址`https://github.com/ISBN9527/test`

**Comment by xiefengnian** [comment]
> 复现地址`https://github.com/ISBN9527/test`

我拉下来跑了一下，没有出错，建议删除 node_modules 和 .umi 后重试

**Comment by sorrycc** [comment]
@ISBN9527 yarn -v 看下是啥？

**Comment by ISBN9527** [comment]
yarn -v
// output
1.22.10

**Comment by sorrycc** [comment]
yarn.lock 贴出来看下？

**Comment by ISBN9527** [comment]
太大了，贴不出来

**Comment by ISBN9527** [comment]
好了，复现地址里就有yarn.lock

**Comment by ISBN9527** [comment]
> > 复现地址`https://github.com/ISBN9527/test`
> 
> 我拉下来跑了一下，没有出错，建议删除 node_modules 和 .umi 后重试

在升级之前项目运行是ok的，删除node_modules及.umi后能跑起来了，但是项目页面出不来

**Comment by sorrycc** [comment]
复现了。

**Comment by sorrycc** [comment]
+ umi@3.5.0-beta.9， @umijs/runtime 找不到的问题修复了。

**Comment by ISBN9527** [comment]
收到

**Comment by ISBN9527** [comment]
![image](https://user-images.githubusercontent.com/30942709/123087237-e50c5a00-d456-11eb-9c6d-abc26e4ce27a.png)
@sorrycc 升级后退出到首页报这样的错

**Comment by sorrycc** [comment]
看起来是 dayjs 插件的问题。

**Comment by ISBN9527** [comment]
确实是antd-dayjs-webpack-plugin和dayjs插件引起的，删了这两个就好了

**Comment by ISBN9527** [comment]
![image](https://user-images.githubusercontent.com/30942709/123192334-46730e00-d4d5-11eb-97a0-614d851731e2.png)
疑问
1. 为啥那么多warning呢
2. moment包好大，想用dayjs转换，哈哈

**Comment by sorrycc** [comment]
umi 啥版本？beta.9 应该没这个了吧，不生成 sourcemap。

**Comment by ISBN9527** [comment]
确实是beta.9

**Comment by xiefengnian** [comment]
> ![image](https://user-images.githubusercontent.com/30942709/123192334-46730e00-d4d5-11eb-97a0-614d851731e2.png)
> 疑问
> 
> 1. 为啥那么多warning呢

看起来是因为 map 文件没有找到，导致返回了 html，建议删了 .umi，重新启动一下

**Comment by ISBN9527** [comment]
怎么删除都没用，都会出现这一堆warning
