### ISSUE TITLE
[Bug] umi MFSU 功能启动失败

### ISSUE THREAD

**Issue by fengyun2** [umijs/umi#6769]
## What happens?

升级umi至 ^3.5.0-beta.8 且开启 mfsu 及 webpack5 后，项目没法正常启动访问

```json
   mfsu: {},
  webpack5: {},
  esbuild: {},
  dynamicImport: {
    loading: '@/components/PageLoading/index'
  }
```

## Mini Showcase Repository(REQUIRED)

https://github.com/ly2011/umi-mfsu-issue

## How To Reproduce

```shell
# 安装依赖包
yarn

# 启动
yarn start
```

![image](https://user-images.githubusercontent.com/8147202/123085923-6531c000-d455-11eb-88f2-351f607ffc1d.png)

**在浏览器访问 http://localhost:8000**

![image](https://user-images.githubusercontent.com/8147202/123086020-84c8e880-d455-11eb-8763-a52a8c46dc09.png)

## Context

- **Umi Version**: ^3.5.0-beta.8
- **Node Version**: v14.15.4
- **Platform**: Mac 10.15.7

**Comment by xiefengnian** [comment]
![image](https://user-images.githubusercontent.com/20136563/123090638-f9525600-d45a-11eb-9f2b-7ed80022c992.png)
通过 script 引用了 React，产生了多实例，注释掉就可以了

**Comment by fengyun2** [comment]
@xiefengnian 

![image](https://user-images.githubusercontent.com/8147202/123188104-03fa0300-d4ce-11eb-8855-81278f63bd96.png)

**Comment by ISBN9527** [comment]
建议升级umi至beat.9，然后删除node_modules及.umi，重新跑下

**Comment by fengyun2** [comment]
> 建议升级umi至beat.9，然后删除node_modules及.umi，重新跑下

![image](https://user-images.githubusercontent.com/8147202/123194888-ca2ef980-d4d9-11eb-95fb-6cfd9240bb71.png)


升级umi至beat.9，并按以上步骤操作了，依然报这个错：

![image](https://user-images.githubusercontent.com/8147202/123194888-ca2ef980-d4d9-11eb-95fb-6cfd9240bb71.png)

**Comment by sorrycc** [comment]
先不用试了，external 的问题，我们排查下。

**Comment by xiefengnian** [comment]
经过排查，原因是：设置了 externals 后，项目代码使用了 MFSU 构建的 React；但是预编译的依赖，例如 react-router-dom 使用了 external 的 React，产生了多实例的问题。解决方案正在商讨中。

**Comment by sorrycc** [comment]
Fixed via https://github.com/umijs/umi/pull/6772

**Comment by fengyun2** [comment]
> Fixed via #6772

以下操作均在：MacOS系统，yarn 安装、运行进行。

源代码如下：

https://github.com/ly2011/umi-mfsu-issue

已升级umi至beat.11，然后删除node_modules及.umi，重新安装依赖包(`yarn`)且重新运行 `yarn start`

配置如下： 
![image](https://user-images.githubusercontent.com/8147202/123364566-3b88ae00-d5a7-11eb-8215-be3ca6f57859.png)

![image](https://user-images.githubusercontent.com/8147202/123364442-fc5a5d00-d5a6-11eb-85cf-b95c40a779d6.png)

http://localhost:8000 运行报错信息如下：

![image](https://user-images.githubusercontent.com/8147202/123364394-e51b6f80-d5a6-11eb-9810-259508dcfe80.png)

**Comment by xiefengnian** [comment]
@fengyun2 经过排查，已经不是 externals 的问题了，是 echarts-for-react/lib/core 的导出问题。和 #6778 #6780 等价。

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/123406236-465e3580-d5dd-11eb-9e91-33368be10fa9.png)
试了，没问题了。
