### ISSUE TITLE
[Feature Request] plugin-locale支持忽略moment，使用umi写Chrome插件，使用到了国际化这个插件，打包之后发现moment始终在

### ISSUE THREAD

**Issue by MatrixAge** [umijs/umi#6770]
## Background

研究源码发现locale插件为了antd的国际化的正确性，会使用moment.locale方法，但事实上，在不使用antd，或者不用antd的locale的情况下，是不需要moment的，一个将近200K的包（ignoreMomentLocale: true的情况下），对于一些对尺寸有要求的应用，”负担“还是蛮总的。

## Proposal

另外，locale插件与antd的locale属性这样耦合在一起，并不合适，对于umi的使用场景造成了限制。

fork了一份，支持 locale: { antd: false, default: 'en-US', ignoreMoment: true } 这样配置，希望官方能够考虑一下这点，扩展一下umi的使用场景，不至于打包进去很多没用到的东西。

![image](https://user-images.githubusercontent.com/25472851/123198913-825fa080-d4e0-11eb-805b-0208832b3018.png)

**Comment by ISBN9527** [comment]
分包出去啊

**Comment by MatrixAge** [comment]
external无效

**Comment by topwood** [comment]
+1
