### ISSUE TITLE
[Bug] MFSU  --  antdPro 开启MFSU就报错 

### ISSUE THREAD

**Issue by chengluliu** [umijs/umi#6778]
在 config.ts 中 开启 mfsu: {}, 之后 编译成功  页面报错, 关掉之后可以正常显示

复现仓库
https://github.com/chengluliu/mfsu_error.git

**Comment by xiefengnian** [comment]
windows or mac？

**Comment by chengluliu** [comment]
@xiefengnian  Mac

**Comment by xiaohuoni** [comment]
我看下

**Comment by xiaohuoni** [comment]
react-dev-inspector 的 Inspector 不兼容。

https://github.com/ant-design/ant-design-pro/blob/09ca467444dea9415f15d2859f41a9b231a4e01d/src/layouts/BlankLayout.tsx#L7

**Comment by xiaohuoni** [comment]
原因是 react-dev-inspector 的入口是按以下方式组织的。
package.json
```json
  "main": "es/index.js",
  "module": "es/index.js",
  "types": "es/index.d.ts",
```
es/index.js
```
export * from './Inspector';
```
es/Inspector.js
```
export const Inspector = ()=>{}
```
![image](https://user-images.githubusercontent.com/11746742/123363162-7dfcbb80-d5a4-11eb-80f5-36560e5904e8.png)
尝试改了一下导出如下：
```
  "main": "es/Inspector.js",
  "module": "es/Inspector.js",
  "types": "es/Inspector.d.ts",
```
项目可以正常运行。
然后这东西怎么修，不知道！@sorrycc

**Comment by sorrycc** [comment]
这个修复了。
