### ISSUE TITLE
配置式路由怎么配置layout

### ISSUE THREAD

**Issue by hu-zhi-hang** [umijs/umi#678]
配置式不会自动加载 layout，怎么配置比较好呢没找到推荐方案

**Comment by hu-zhi-hang** [comment]
{
    path: '/*',
    component: '../layout/',
    exact: true,
  }, {
    path: '/',
    component: '/index',
    exact: true,
  }, 
配置 layout 似乎并不行，后面的路由都没有匹配到，children 没有传进来

**Comment by yutingzhao1991** [comment]
要通过嵌套来实现。

```js
{
  path: "/*",
  component: "../layout/",
  exact: true,
  routes: [
    {
      path: "/",
      component: "/index",
      exact: true
    }
  ]
};

```
