### ISSUE TITLE
[Bug] 升级umi至3.5.0-beta.9,echarts找不到api

### ISSUE THREAD

**Issue by ISBN9527** [umijs/umi#6780]
## What happens?
echarts: 5.1.2
一样的代码，在3.4.25里，`import * as echarts from 'echarts/core';`引入echarts打印如图一
但是升级umi至3.5.0-beta.9，开启mfsu，同样`import * as echarts from 'echarts/core'`，打印如图二
找不到echarts相关api，譬如registerTheme

## 复现链接
[链接](https://github.com/ISBN9527/test)

## 补充信息图片
umi: 3.4.25
![image](https://user-images.githubusercontent.com/30942709/123236824-b4d4c200-d50f-11eb-821d-1598473b3eab.png)

umi: 3.5.0-beta.9
![image](https://user-images.githubusercontent.com/30942709/123236786-adadb400-d50f-11eb-8ae9-c7fd250dfde6.png)

## Context

- **Umi Version**:  3.5.0-beta.9
- **Node Version**: 16.x
- **Platform**: mac

**Comment by ISBN9527** [comment]
大佬，有什么进展吗？

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/123405723-ad2f1f00-d5dc-11eb-854e-3647f2bad6d8.png)
这个项目跑不起来，有内部请求卡主了。

你用最新的 umi beta 跑跑看，还有没有问题。

**Comment by ISBN9527** [comment]
> ![image](https://user-images.githubusercontent.com/35128/123405723-ad2f1f00-d5dc-11eb-854e-3647f2bad6d8.png)
> 这个项目跑不起来，有内部请求卡主了。
> 
> 你用最新的 umi beta 跑跑看，还有没有问题。

修复了👍
