### ISSUE TITLE
[文档] 请问lint扫描规则有文字说明吗？想给新人系统学习下。看扫描的报错太散了。 #89

### ISSUE THREAD

**Issue by quicklearning123** [umijs/umi#6782]
## What happens?

类似这样的：
https://guide.aotu.io/docs/js/language.html
https://github.com/lin-123/javascript

## Context

- **Umi Version**:3.4.7
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
umi 不内置 lint 规则，是不是 pro 的还是其他的 lint 规则？
