### ISSUE TITLE
[Bug]   执行`yarn run build` 出现警告：npx browserslist@latest --update-db

### ISSUE THREAD

**Issue by nsuedu** [umijs/umi#6785]
## What happens?

执行`yarn run build` 出现如下警告，阻断了CD流程

>Browserslist: caniuse-lite is outdated. Please run:
>npx browserslist@latest --update-db
>
>Why you should do it regularly:
>https://github.com/browserslist/browserslist#browsers-data-updating

## How To Reproduce

**Steps to reproduce the behavior:** 

1. 使用 `yarn create @umijs/umi-app` 创建项目
2. 执行`yarn run build` 就会出现警告：npx browserslist@latest --update-db
![20210625110515](https://user-images.githubusercontent.com/19920673/123363504-46dada00-d5a5-11eb-88ac-26b6db43d306.jpg)

解决方式一： 按照提示执行 `npx browserslist@latest --update-db` 后，没有任何效果

解决方式二： 删除`node_modules`文件夹，重新手动安装 `browserslist`  `caniuse-lite`  也没有没有任何效果

**Expected behavior**  不希望出现这样的警告⚠️

## Context

- **Umi Version**: "^3.4.25"
- **Node Version**: v14.16.1
- **Platform**: mac13

**Comment by nsuedu** [comment]
@sorrycc 云谦老师，麻烦看看呢

**Comment by ClenLu** [comment]
> ## 怎么了？
> 执行`yarn run build`出现如下警告，过了CD流程
> 
> > 浏览器列表：caniuse-lite 已过时。请运行：
> > npx browserslist@latest --update-db
> > 为什么你应该定期这样做：[https](https://github.com/browserslist/browserslist#browsers-data-updating) : 
> > [//github.com/browserslist/browserslist#browsers-data-updating](https://github.com/browserslist/browserslist#browsers-data-updating)
> 
> ## 迷你展示库（必需）
> ## 如何繁殖
> **重现行为的步骤：**
> 
> 1. 使用`yarn create @umijs/umi-app`创建项目
> 2. 执行开始`yarn run build`出现警告：npx browserslist@latest --update-db
>    ![20210625110515](https://user-images.githubusercontent.com/19920673/123363504-46dada00-d5a5-11eb-88ac-26b6db43d306.jpg)
> 
> 解决方式一：按照提示执行`npx browserslist@latest --update-db`后，没有任何效果
> 
> 解决方式二：删除`node_modules`文件夹，手动安装`browserslist` `caniuse-lite` 也没有任何效果
> 
> **预期行为** 不希望出现这样的警告⚠️
> 
> ## 语境
> * **乌米版本**：“^3.4.25”
> * **节点版本**：v14.16.1
> * **平台**：mac13

解决了吗？？

**Comment by ClenLu** [comment]
解决了吗 @nsuedu

**Comment by nsuedu** [comment]
> 解决了吗 @nsuedu

没有呢。 只是通过修改CD脚本暂时跳过了报错信息

**Comment by zcSkr** [comment]
插个眼，也不知到哪个版本突然就出现了

**Comment by CliffKnight** [comment]
遇到同样的问题

**Comment by Measy** [comment]
这个有什么进展吗？

**Comment by Measy** [comment]
遇到了同样的问题

**Comment by Ireland999** [comment]
大家是怎么解决的？

**Comment by bigflybrother** [comment]
大家是怎么解决的？

**Comment by Josie-ljw** [comment]
same here, also occur in umi dev

**Comment by guonanci** [comment]
Can you help me to remove such warning when every time I run `yarn start`

From view of autoprefixer-issue: https://github.com/postcss/autoprefixer/issues/1184 and my yarn.lock diff between postcss-preset-env@^7.1.0 and postcss-preset-env@^6.7.0.

I find @umijs/bundler-webpack@3.5.20（latest version) has the dependency of postcss-preset-env@^6.7.0. and I think the most important point is that postcss-preset-env@^6.7.0 imports browserslist@4.6.4 and postcss-preset-env@^7.1.0 imports browserslist@4.19.1.
Maybe we could upgrade @umi.
Maybe my suggestion is wrong, but I need your help to get rid of this warning

**Comment by liangtao-top** [comment]
这是当前 Next.js 版本 (10.0.5) 中的虚假警告。

**Comment by YMingF** [comment]
遇到了同样的问题，如果运行 npx browserslist@latest --update-db 不仅没半点用，而且会出错得更离谱，

**Comment by YMingF** [comment]
> 遇到了同样的问题，如果运行 npx browserslist@latest --update-db 不仅没半点用，而且会出错得更离谱，
在这个链接里找到一个解决方法：https://github.com/browserslist/browserslist/issues/492
运行npm update 
然后再启动试试？

**Comment by yancongwen** [comment]
npm run build 命令添加环境变量：BROWSERSLIST_IGNORE_OLD_DATA=true 即可跳过这个问题
"build": "cross-env BROWSERSLIST_IGNORE_OLD_DATA=1 umi build",

**Comment by iceberg211** [comment]
2022年还是有这个问题

**Comment by ChenDaitao** [comment]
2023年还遇到这个问题

**Comment by yulu-999** [comment]
2024年还遇到这个问题

**Comment by lovewinders** [comment]
2024年最新umijs版本还存在该问题
<img width="622" alt="image" src="https://github.com/umijs/umi/assets/22837419/4ebe96a4-50f6-4eb5-a16a-ede22c2d135f">

**Comment by fz6m** [comment]
我使用最新的 umi 4 版本 `4.1.1` 并没有这个提示的问题，确保你的 umi 版本是最新的，若还有这个提示，可以看下 `caniuse-lite` 是什么依赖的：

```ts
  pnpm why caniuse-lite
```

确认好依赖的链路，如果是 umi 相关的，可以开一个 issue ，如果是自己用到的某些依赖涉及到的，就把这个依赖升级下，或者尝试运行：

```bash
  pnpm up -L caniuse-lite
```

**Comment by chenjin2018** [comment]
我删除了public文件夹就能打包了
![QQ浏览器截图20240526201129](https://github.com/umijs/umi/assets/45862595/df78d6fa-d5c4-426e-8e2b-c3597adda50e)
![QQ浏览器截图20240526201144](https://github.com/umijs/umi/assets/45862595/a39fb523-d76e-41e8-be02-5ccb1dcce93f)

**Comment by sparkle3021** [comment]
自己尝试出一个解决方案，先删除pnpm-lock.yaml和node_modules，再去pnpm i 下载依赖并启动项目，提示就消失了。

**Comment by chenjin2018** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lifengsbotlp** [comment]
2025年了此问题还存在

**Comment by chenjin2018** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
