### ISSUE TITLE
[Feature Request] umi-plugin-qiankun 对于 umi 工程 prefetch 的优化

### ISSUE THREAD

**Issue by maquannene** [umijs/umi#6792]
## Background

在使用  umi-plugin-qiankun 的 prefetch 预加载功能时，对于 umi 打出来的子应用作用不是很大。

因为通常情况下通过 umi 打出来的资源分为：
vendors.js （这个最大）
umi.js （次之）
somePage.js （最小）

但是 umi-plugin-qiankun 的 prefetch 只会预先加载 html 中 umi.js. 这个文件，对于 vendors 并不会预加载，所以对于子应用之间的首次切换，对于首屏加载的提升并不是特别明显。

## Proposal

提升通过 umi-plugin-qiankun 的 prefetch 功能预加载 umi 应用时的资源覆盖量

## Additional context

暂时想到的方案：
把 vendors 里面的东西跟 umi.js 进行合并，打在一起，但是现不知道要怎么配置 umi config 才能做到这一点；而且打在一起，由于 umi.js 的变大， 导致 loading 意义就不大了；

**Comment by hejialianghe** [comment]
有解决方案么，umi中配置prefetch
