### ISSUE TITLE
[Bug] config/config.ts未生效

### ISSUE THREAD

**Issue by poapoc** [umijs/umi#6793]
![image](https://user-images.githubusercontent.com/4936534/123415681-33049780-d5e8-11eb-9f03-d267f5cca232.png)

![image](https://user-images.githubusercontent.com/4936534/123415728-43b50d80-d5e8-11eb-97ed-43ca1d4fe0ed.png)

如图，当访问http://127.0.0.1:8000/test 时404了按照路由配置应该展示Page Index，我已经删掉了.umirs.ts文件,但是config/config.ts里面配置的路由还是未生效。umi 版本 3.4.25

**Comment by sorrycc** [comment]
config 目录得放在 src 外面。

**Comment by poapoc** [comment]
好的，感谢
