### ISSUE TITLE
还是一个第三方插件的ES模块化问题

### ISSUE THREAD

**Issue by lettywiterock** [umijs/umi#680]
这个问题是从antd-pro找af-webpack 过来的
报错：Build failed: Configuration item module is not valid, please remove it.
文件：.webpackrc.js
配置内容：
module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules\/(?!(dom7|ssr-window|swiper)\/).*/,
        loader: "babel-loader"
      }
    ]
  },

第三方提供的ES模块化方案:
As an ES module
Swiper package comes with ES module version which can be used where supported or with bundlers like Webpack or Rollup:

import Swiper from 'swiper';

var mySwiper = new Swiper('.swiper-container', { /* ... */ });
In case you use it as an ES module make sure:

you have enabled Babel or Buble to transpile it to ES5 syntax,
you have enabled node modules resolving for Swiper as it uses Dom7 and ssr-window packages as dependencies.
Example of Webpack cofiguration for babel-loader with Swiper and Dom7:

module: {
  rules: [
    {
      test: /\.js$/, // Check for all js files
      exclude: /node_modules\/(?!(dom7|ssr-window|swiper)\/).*/,
      loader: 'babel-loader'
    }
  ]
}

**Comment by xiaohuoni** [comment]
webpack的配置现在都重写了使用webpack 4，你可以等发布新版本之后，再处理
