### ISSUE TITLE
怎样通过umi调试react的源码？

### ISSUE THREAD

**Issue by cike8899** [umijs/umi#6817]
怎样通过umi调试react的源码？不构建react，直接调试packages目录下的源码

**Comment by xiefengnian** [comment]
可以再详细描述一下吗？

**Comment by cike8899** [comment]
> 可以再详细描述一下吗？
不通过npm安装react  直接使用react 源码  从而达到直接调试react 源码的目的

**Comment by xiefengnian** [comment]
使用 yarn link 试一下

**Comment by cike8899** [comment]
> 使用 yarn link 试一下

用了 各种报错

**Comment by xiaohuoni** [comment]
调试源码用 react 官方的测试用例吧。本身就很复杂了，你在 umi 上，就算 link 好了也很多情况。你很难确认是哪个库的问题。

**Comment by cike8899** [comment]
> 调试源码用 react 官方的测试用例吧。本身就很复杂了，你在 umi 上，就算 link 好了也很多情况。你很难确认是哪个库的问题。

我想在项目中直接学习react 源码，cra有相关的配置 希望也有大佬给出配置
