### ISSUE TITLE
[Bug] 新建的Umi项目使用openapi报错

### ISSUE THREAD

**Issue by yuanye4017** [umijs/umi#6819]
## 问题场景
使用yarn create @umijs/umi-app创建项目后，直接使用openapi失败

## 复现步骤
+ yarn create @umijs/umi-app创建项目
+ yarn add @umijs/plugin-openapi -D
+ 在.umirc.ts下增加配置
```js
  openAPI: {
      requestLibPath: "import { request } from 'umi'",
      schemaPath: "https://gw.alipayobjects.com/os/antfincdn/M%24jrzTTYJN/oneapi.json",
      mock: false,
  }
```
+  在`package.json`中增加命令
```js
"script": {
    "openapi": "umi openapi"
}
```
## 错误提示
![image](https://user-images.githubusercontent.com/43987769/123731101-1b6c2e00-d8ca-11eb-9400-f0bc53a18f13.png)

- **@umijs/plugin-openapi Version**:  ^1.3.0

## Context

- **Umi Version**: ^3.4.25
- **Node Version**: 16.4.0
- **Platform**: Mac os 11.2.2

**Comment by PeachScript** [comment]
openapi 插件依赖 `package.json` 中的 name 生成 `projectName`，但 `@umijs/umi-app` 默认不带 name，需要手动配上

refer: https://github.com/umijs/plugins/blob/master/packages/plugin-openapi/src/index.ts#L140
