### ISSUE TITLE
[Bug] mfsu方案，但是页面显示空白

### ISSUE THREAD

**Issue by cschensai** [umijs/umi#6820]
"umi": "^3.5.0-beta.19", antd-pro 是v4版本

## 没有进行挂载页面，控制台无报错
![image](https://user-images.githubusercontent.com/38218964/123735296-8f5e0480-d8d1-11eb-8c68-0249a36e49aa.png)

**Comment by xiefengnian** [comment]
console 报错可以发一下吗

**Comment by cschensai** [comment]
> console 报错可以发一下吗

我大概定位到是chainWebpack的问题，大概可以先关掉了
