### ISSUE TITLE
[Bug]umi/qiankun在mfsu方案不适用

### ISSUE THREAD

**Issue by cschensai** [umijs/umi#6823]
### 版本
"umi": "^3.5.0-beta.20"

### 最小复现单元
https://github.com/cschensai/musu_qiankun_demo

### 页面展示
![image](https://user-images.githubusercontent.com/38218964/123761146-1f14aa80-d8f4-11eb-96a6-cddf06d7d23e.png)

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/123898662-49b83f00-d998-11eb-9e4d-760595148643.png)
这是正常的？

**Comment by sorrycc** [comment]
在 https://github.com/umijs/plugins/pull/645 里修复了。
