### ISSUE TITLE
怎么让打包出来的js是按需加载的，但项目css只打包一个css？

### ISSUE THREAD

**Issue by hellojayjay** [umijs/umi#6829]
启用dynamicImport后，打包结果是
```
umi.***.js
p__A__B.***.async.js
p__C__D.***.async.js
umi.***.css
p__A__B.***.chunk.css
p__C__D.***.async.css
```

能不能让打包完成后成：
```
umi.***.js
p__A__B.***.async.js
p__C__D.***.async.js
umi.***.css // 这里面包含所有的css
```

_Originally posted by @hellojayjay in https://github.com/umijs/umi/discussions/6828_

**Comment by PeachScript** [comment]
把样式表文件提取到同一个 webpack chunk 里，可以实现 CSS 不分片，配置方式参考：https://umijs.org/config#chunks

**Comment by hellojayjay** [comment]
> 把样式表文件提取到同一个 webpack chunk 里，可以实现 CSS 不分片，配置方式参考：https://umijs.org/config#chunks

当配置了打包到一个css中，打包没有问题了，但是umi dev启动是白屏的了
```
export default defineConfig({
  chainWebpack: function (config, { webpack }) {
    config.merge({
      optimization: {
        splitChunks: {
          cacheGroups: {
            styles: {
              name: 'styles',
              test: /\.(le|c)ss$/,
              chunks: 'all',
              enforce: true,
            },
          },
        },
      },
    });
  },
...
});
```
 File                       Size                    Gzipped

 dist\umi.js                505.8 KB                164.5 KB
 dist\p__index.js           308.0 B                 226.0 B
 dist\styles.js             249.0 B                 165.0 B
 dist\p__other.js           224.0 B                 196.0 B
 dist\styles.chunk.css      25.9 KB                 4.3 KB

**Comment by hellojayjay** [comment]
![image](https://user-images.githubusercontent.com/42774792/123945159-6f613a80-d9d0-11eb-91e6-adf2a49ff039.png)

**Comment by PeachScript** [comment]
> 把样式表文件提取到同一个 webpack chunk 里，可以实现 CSS 不分片，配置方式参考：https://umijs.org/config#chunks

链接里的 chunks 也要配上，CSS 是个单独的 chunk

**Comment by hellojayjay** [comment]
> > 把样式表文件提取到同一个 webpack chunk 里，可以实现 CSS 不分片，配置方式参考：https://umijs.org/config#chunks
> 
> 链接里的 chunks 也要配上，CSS 是个单独的 chunk

感谢，可以了
```
export default defineConfig({
  chunks: ['styles', 'umi'],
  chainWebpack: function (config, { webpack }) {
    config.merge({
      optimization: {
        splitChunks: {
          cacheGroups: {
            styles: {
              name: 'styles',
              test: /\.(le|c)ss$/,
              chunks: 'all',
              enforce: true,
            },
          },
        },
      },
    });
  },
...
});
```
