### ISSUE TITLE
[Bug] [app.model] namespace should be unique

### ISSUE THREAD

**Issue by huyawei** [umijs/umi#6830]
![image](https://user-images.githubusercontent.com/23353032/123915377-04edd180-d9b3-11eb-8c66-91a5939655de.png)
umi 3.5.0
3.3.11是好的，看到更新构建提速
就更新了下直接报这个错误

**Comment by huyawei** [comment]
自己试了试 只要开mfsu就报错
只开webpack5没问题关掉webpack5也没问题

**Comment by sorrycc** [comment]
看这截图没看到冲突，给个复现仓库？

**Comment by huyawei** [comment]
> 看这截图没看到冲突，给个复现仓库？

"dependencies": {
    "antd": "4.16.0",
    "react-amap": "1.2.8",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "tslib": "2.1.0"
  },
  "devDependencies": {
    "@umijs/fabric": "2.2.2",
    "@umijs/preset-react": "1.4.8",
    "babel-eslint": "10.0.1",
    "babel-plugin-import": "1.13.3",
    "cross-env": "6.0.0",
    "eslint": "6.8.0",
    "eslint-config-umi": "1.6.0",
    "eslint-loader": "4.0.2",
    "eslint-plugin-flowtype": "4.6.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsx-a11y": "6.2.1",
    "eslint-plugin-react": "7.14.0",
    "eslint-plugin-react-hooks": "2.5.0",
    "husky": "4.2.0",
    "less-vars-to-js": "1.3.0",
    "lint-staged": "10.0.0",
    "umi": "3.5.0"
  }

这是用的包
我把page全部删掉就留个登录 全局的model 就会报错但是不是这个错误
pages下有2个以及2个以上的model 就会namespace唯一键冲突

**Comment by huyawei** [comment]
import { resolve } from 'path'

export default {
  favicon: '/favicon.ico',
  title: '测试',
  metas: [
    { 'http-equiv': 'Cache-Control', 'content': 'no-cache, no-store, must-revalidate' },
    { 'http-equiv': 'Pragma', 'content': 'no-cache', },
    { 'http-equiv': 'Expires', 'content': '0' },
  ],
  ignoreMomentLocale: true,
  antd: {},
  dva: { hmr: true },
  // mfsu: {},
  // webpack5: {},
  dynamicImport: {},
  pwa: false,
  outputPath: `./dist/${process.env.APP_KEY}`,
  lessLoader: { javascriptEnabled: true },
  alias: {
    components: resolve(__dirname, './src/components'),
    utils: resolve(__dirname, './src/utils'),
  },
  nodeModulesTransform: { type: 'none' },
  extraBabelPlugins: [
    [
      'import',
      {
        libraryName: 'lodash',
        libraryDirectory: '',
        camel2DashComponentName: false,
      },
      'lodash',
    ],
  ],
  devtool: false,
  define: {
    "process.env.APP_KEY": '0',
    "process.env.API": ['develop', 'pre', 'master'].indexOf(process.env.APP_KEY),
  },
  chainWebpack(config) {
    config.module
      .rule('lint')
      .test(/\.js(x)?$/)
      .pre()
      .include.add(resolve(__dirname, './src/pages'))
      .end()
      .use('eslint')
      .loader('eslint-loader');
  },
}

**Comment by sorrycc** [comment]
能给个复现仓库吗？
