### ISSUE TITLE
[Bug]umi@3.5.0搭配 qiankun 插件，开启 mfsu 功能报错

### ISSUE THREAD

**Issue by wwpeng520** [umijs/umi#6831]
## What happens?

![baocuo1](https://user-images.githubusercontent.com/18344282/124054063-e1c72e80-da53-11eb-9ee2-4cb8950efb6a.png)
![baocuo2](https://user-images.githubusercontent.com/18344282/124054070-e4298880-da53-11eb-8d88-78903f8f5cc2.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

复现仓库：https://github.com/wwpeng520/test-umi-qiankun.git

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

开启 mfsu 和 webpack5 配置就报错，关闭重新启动不报错

## Context

- **Umi Version**:v3.5.0
- **Node Version**:v16.1.0
- **Platform**:mac OS

**Comment by sorrycc** [comment]
有三个问题，

1. [x] mfsu 不支持热更新，https://github.com/umijs/umi/pull/6847
2. [ ] 主应用和子应用 mf 冲突，需要支持自定义
3. [ ] 主应用开启 sandbox 时，子应用加载失败，这个需要前两个解了后，找 qiankun 排查

**Comment by sorrycc** [comment]
@kuitos 看下这个问题。

复现步骤，

1. git clone git@github.com:wwpeng520/test-umi-qiankun.git
2. cd test-umi-qiankun

分别进入 app1，

1. tnpm i
2. tnpm start

分别进入 main，

1. tnpm i
2. 编辑 config/config.ts，修改 `mfsu: {}` 为 `mfsu: { mfName: 'mfMain' }`，修改 `qiankun: { master: {} }` 为 `qiankun: { master: { sandbox: false } }`
3. tnpm start
4. 访问 http://localhost:8004/app1，正常

![image](https://user-images.githubusercontent.com/35128/124893449-529ab780-e00d-11eb-9917-79f9caa35d3a.png)

main 验证关闭 sandbox 报错，

1. 编辑 config/config.ts，修改 `qiankun: { master: { sandbox: false } }` 为 `qiankun: { master: {  } }`
2. dev server 自动重启
3. 访问 http://localhost:8004/app1，报错

![image](https://user-images.githubusercontent.com/35128/124893741-92fa3580-e00d-11eb-9fec-6a64b6794c85.png)

**Comment by Tan90Qian** [comment]
我也在尝试给使用qiankun的项目加入mfsu功能，通过给.umirc.ts的mfsu添加一个exclude配置来排除monorepo下的本地子模块，然后通过require.resolve这个node原生api而不是pkg-up这个库来检索三方库的包版本号。这样改造之后umi+qiankun的项目已经能通过编译阶段，但是运行时遇到了新的报错
`Module "./qs" does not exist in container. while loading "./qs" from webpack/container/reference/mf
Error: Module "./qs" does not exist in container. while loading "./qs" from webpack/container/reference/mf at http://localhost:9000/mf-va_remoteEntry.js:447:11`
初步排查后发现是slave模块的umi.js在引入remoteEntry.js时，没有去slave模块自己端口寻找对应的entry文件，而是去了master模块寻找，而在子模块引入的一部分三方库并没有写入master模块的remoteEntry文件
关闭沙箱也无效，暂时找不到解决这个运行时报错的办法。
@sorrycc

**Comment by Tan90Qian** [comment]
master应用启动，加载9000端口下的umi.js -> 
加载9000端口下的remoteEntry.js ->
umi.js初始化项目，注册slave apps -> 
10010端口下的slave app被加载 ->
加载10010端口下的umi.js -> 
由于10010端口下的umi.js在9000端口被解析，`__webpack_require__.p + "mf-va_remoteEntry.js"`输出`/mf-va_remoteEntry.js` -> 
发现该文件已经被加载，跳过 ->
slave app初始化，发现remoteEntry.js文件下没有自己需要的依赖记录 -> 运行时报错，初始化中断
目前卡在最后这个阶段

**Comment by Tan90Qian** [comment]
另外还有一个问题，在使用require.resolve来检索三方库的版本号时。像`assert`、`url`这样与node核心模块同名的三方库，在用这个api调用时，会返回原名称而不是具体的文件路径，可能是被当作核心模块处理了。不知道还有什么更好的办法去解决monorepo下，package.json的检索问题。

**Comment by wbyuhan** [comment]
##配置mfsu 后 国际化失效<img width="494" alt="截屏2021-07-12 下午5 10 01" src="https://user-images.githubusercontent.com/40864785/125261622-006ed480-e334-11eb-8b3e-16c13b7da940.png">### 按照步骤：
<img width="612" alt="截屏2021-07-12 下午5 02 26" src="https://user-images.githubusercontent.com/40864785/125260477-f13b5700-e332-11eb-94b8-1e931f7d3348.png">
然后安装依赖，删除src/.umi
<img width="1188" alt="截屏2021-07-12 下午5 03 30" src="https://user-images.githubusercontent.com/40864785/125260623-192aba80-e333-11eb-9a9c-0d60cd703286.png">
<img width="1181" alt="截屏2021-07-12 下午5 03 51" src="https://user-images.githubusercontent.com/40864785/125260665-234cb900-e333-11eb-9a8c-b669a0a1e74a.png">
启动成功，进入页面，打开控制台
<img width="1495" alt="截屏2021-07-12 下午5 04 41" src="https://user-images.githubusercontent.com/40864785/125260784-41b2b480-e333-11eb-8d39-7d6479988a82.png">
### package.json如下：`{
    "name": "ant-design-pro",
    "version": "5.0.0-beta.2",
    "private": true,
    "description": "An out-of-box UI solution for enterprise applications",
    "scripts": {
        "analyze": "cross-env ANALYZE=1 umi build",
        "build": "umi build",
        "build:dev": "cross-env NODE_ENV=local umi build",
        "deploy": "npm run site && npm run gh-pages",
        "dev": "npm run start:dev",
        "gh-pages": "gh-pages -d dist",
        "i18n-remove": "pro i18n-remove --locale=zh-CN --write",
        "postinstall": "umi g tmp",
        "lint": "umi g tmp && npm run lint:js && npm run lint:style && npm run lint:prettier",
        "lint-staged": "lint-staged",
        "lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
        "lint:fix": "eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src && npm run lint:style",
        "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
        "lint:prettier": "prettier --check \"src/**/*\" --end-of-line auto",
        "lint:style": "stylelint --fix \"src/**/*.less\" --syntax less",
        "openapi": "umi openapi",
        "precommit": "lint-staged",
        "prettier": "prettier -c --write \"src/**/*\"",
        "start": "cross-env UMI_ENV=dev umi dev --open",
        "start:dev": "cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev umi dev",
        "start:no-mock": "cross-env MOCK=none UMI_ENV=dev umi dev",
        "start:no-ui": "cross-env UMI_UI=none UMI_ENV=dev umi dev",
        "start:pre": "cross-env REACT_APP_ENV=pre UMI_ENV=dev umi dev",
        "start:test": "cross-env REACT_APP_ENV=test MOCK=none UMI_ENV=dev umi dev",
        "pretest": "node ./tests/beforeTest",
        "test": "umi test",
        "test:all": "node ./tests/run-tests.js",
        "test:component": "umi test ./src/components",
        "tsc": "tsc --noEmit"
    },
    "lint-staged": {
        "**/*.less": "stylelint --syntax less",
        "**/*.{js,jsx,ts,tsx}": "npm run lint-staged:js",
        "**/*.{js,jsx,tsx,ts,less,md,json}": [
            "prettier --write"
        ]
    },
    "browserslist": [
        "> 1%",
        "last 2 versions",
        "not ie <= 10"
    ],
    "dependencies": {
        "@ant-design/charts": "^1.1.2",
        "@ant-design/icons": "^4.5.0",
        "@ant-design/pro-descriptions": "^1.6.8",
        "@ant-design/pro-form": "^1.18.3",
        "@ant-design/pro-layout": "^6.15.3",
        "@ant-design/pro-table": "^2.30.8",
        "@antv/data-set": "^0.11.8",
        "@umijs/openapi": "^1.1.14",
        "@umijs/plugin-openapi": "^1.2.0",
        "@umijs/route-utils": "^1.0.36",
        "antd": "^4.14.0",
        "classnames": "^2.2.6",
        "lodash": "^4.17.11",
        "moment": "^2.29.1",
        "omit.js": "^2.0.2",
        "rc-hooks": "^0.8.3",
        "react": "^17.0.0",
        "react-dev-inspector": "^1.1.1",
        "react-dom": "^17.0.0",
        "react-helmet-async": "^1.0.4",
        "react-infinite-scroller": "^1.2.4",
        "umi": "^3.5.0",
        "umi-request": "^1.0.8",
        "webpack": "^5.35.1"
    },
    "devDependencies": {
        "@ant-design/pro-cli": "^2.0.2",
        "@types/classnames": "^2.2.7",
        "@types/express": "^4.17.0",
        "@types/history": "^4.7.2",
        "@types/jest": "^26.0.0",
        "@types/lodash": "^4.14.144",
        "@types/react": "^17.0.0",
        "@types/react-dom": "^17.0.0",
        "@types/react-helmet": "^6.1.0",
        "@types/react-infinite-scroller": "^1.2.1",
        "@umijs/fabric": "^2.5.2",
        "@umijs/plugin-blocks": "^2.0.5",
        "@umijs/plugin-esbuild": "^1.0.1",
        "@umijs/preset-ant-design-pro": "^1.2.0",
        "@umijs/preset-dumi": "^1.1.7",
        "@umijs/preset-react": "^1.7.4",
        "@umijs/yorkie": "^2.0.3",
        "babel-plugin-import": "^1.13.3",
        "carlo": "^0.9.46",
        "cross-env": "^7.0.0",
        "cross-port-killer": "^1.1.1",
        "detect-installer": "^1.0.1",
        "enzyme": "^3.11.0",
        "eslint": "^7.1.0",
        "express": "^4.17.1",
        "gh-pages": "^3.0.0",
        "jsdom-global": "^3.0.2",
        "lint-staged": "^10.0.0",
        "mockjs": "^1.0.1-beta3",
        "prettier": "^2.0.1",
        "puppeteer-core": "^8.0.0",
        "stylelint": "^13.0.0",
        "typescript": "^4.2.2",
        "webpack-bundle-analyzer": "^4.4.2",
        "zip-webpack-plugin": "^4.0.1"
    },`

使用的是ant-design-v5 为基础模版

## 第二个问题：恢复到原来的状态
删除msfu 配置,um恢复为3.4.0
<img width="842" alt="截屏2021-07-12 下午5 10 39" src="https://user-images.githubusercontent.com/40864785/125261691-17152b80-e334-11eb-8d54-ae774145cf00.png">
<img width="531" alt="截屏2021-07-12 下午5 10 58" src="https://user-images.githubusercontent.com/40864785/125261732-21cfc080-e334-11eb-8523-d8ad04042b59.png">
### 删除src/.umi 删除依赖
### 重装依赖
<img width="1022" alt="截屏2021-07-12 下午5 13 12" src="https://user-images.githubusercontent.com/40864785/125262080-72dfb480-e334-11eb-909c-4b3f4fb7ecaa.png">

执行yarn start
出现如下情况：webpack报错
<img width="1195" alt="截屏2021-07-12 下午5 12 26" src="https://user-images.githubusercontent.com/40864785/125261971-58a5d680-e334-11eb-8802-db72ebab71b1.png">

**Comment by sorrycc** [comment]
修复了。

**Comment by Lcj-space** [comment]
> 修复了。

请问怎么修复的是升级哪个包，还是升级一组包
