### ISSUE TITLE
当我在.scss或者.less文件下保存的时候就会报 punycode.toASCII is not a function

### ISSUE THREAD

**Issue by 17628368021** [umijs/umi#6834]
![image](https://user-images.githubusercontent.com/35300738/124079387-a3de0080-da7b-11eb-8380-8427a959f4fb.png)
[](url)

**Comment by sorrycc** [comment]
给复现仓库。

**Comment by 17628368021** [comment]
> 给复现仓库。

![image](https://user-images.githubusercontent.com/35300738/124085653-d6d7c280-da82-11eb-9315-052f067423e6.png)

**Comment by 17628368021** [comment]
![image](https://user-images.githubusercontent.com/35300738/124086056-46e64880-da83-11eb-9998-0d52358d698d.png)

**Comment by nannan0109** [comment]
遇到了同样的问题 请问解决了吗？

**Comment by 17628368021** [comment]
> 遇到了同样的问题 请问解决了吗？

还没有

**Comment by ahauzq** [comment]
先写死版本吧，别用最新的3.3.5  "umi": "3.3.4"

**Comment by ahauzq** [comment]
别用最新的3.5.0，我现在锁死之前的3.3.3没问题

**Comment by 17628368021** [comment]
> 别用最新的3.5.0，我现在锁死之前的3.3.3没问题

好的 感谢大佬 我马上试试先

**Comment by 17628368021** [comment]
> > 别用最新的3.5.0，我现在锁死之前的3.3.3没问题
> 
> 好的 感谢大佬 我马上试试先

感谢，问题已经解决

**Comment by nannan0109** [comment]
> 别用最新的3.5.0，我现在锁死之前的3.3.3没问题

但是不用3.5的话 就用不了mfsu了 哎

**Comment by Superman-wc** [comment]
> 给复现仓库。
我也出现这个问题了， 在使用dumi时出现的。

**Comment by Superman-wc** [comment]
此问题必现的 步骤如下：
```npx @umijs/create-dumi-lib ```
创建一个dumi的项目
安装完依赖后修改.umirc.ts文件 如下
```
import { defineConfig } from 'dumi';

export default defineConfig({
  title: 'umi-mfsu-bug',
  favicon: 'https://user-images.githubusercontent.com/9554297/83762004-a0761b00-a6a9-11ea-83b4-9c8ff721d4b8.png',
  logo: 'https://user-images.githubusercontent.com/9554297/83762004-a0761b00-a6a9-11ea-83b4-9c8ff721d4b8.png',
  outputPath: 'docs-dist',
  // more config: https://d.umijs.org/config
  //新增以下三行
  mfsu:{},
  webpack5: {},
  dynamicImport: {},
});
```
新增一个less文件
src/Foo/index.less
```
.index{
  background-color: #f00;
  font-size:12px;
}
```
修改原有的src/Foo/index.tsx文件
```
import React from 'react';
import styles from './index.less'; // 引入样式文件

export default ({ title }: { title: string }) => <h1 className={styles['index']} >{title}</h1>;  // 应用样式到组件上

```

启动项目
```npm start ```

打开 Food页面
```http://localhost:8000/foo```

再去修改 src/Foo/index.less文件，保存后就会出现BUG了
```
Uncaught TypeError: punycode.toASCII is not a function
    at Url.parse (hotModuleReplacement.js:532)
    at Object.urlParse [as parse] (hotModuleReplacement.js:417)
    at module2.exports (hotModuleReplacement.js:1429)
    at getReloadUrl (hotModuleReplacement.js:1586)
    at hotModuleReplacement.js:1601
    at NodeList.forEach (<anonymous>)
    at reloadStyle (hotModuleReplacement.js:1597)
    at update (hotModuleReplacement.js:1638)
    at functionCall2 (hotModuleReplacement.js:1510)
```

**Comment by Superman-wc** [comment]
@17628368021  @nannan0109  
非官方解决方法 
找到文件 node_moduls/@umijs/bundler-webpack/bundled/css/hotModuleReplacement.js
第
218行到第222行去除或注释，防止以amd形式引用组件
