### ISSUE TITLE
[Bug] node-modules 中依赖的 .jsx 编译报错

### ISSUE THREAD

**Issue by xiaofuzi** [umijs/umi#6844]
## What happens?

依赖 node-modules 中的 .jsx 文件编译不支持
![image](https://user-images.githubusercontent.com/4171913/124102306-d0514700-da92-11eb-830d-a93c8b0cacf9.png)

* 出现问题版本：umi@3.4.25
* 配置文件中加上`nodeModulesTransform` all 配置也不生效
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by PeachScript** [comment]
`nodeModulesTransform` 是用来转换不符合 es5 语法的 JS 的，要编译三方依赖的 JSX 需要走 babel，配置 `babelExtraIncludes`：https://umijs.org/config#extrababelincludes
