### ISSUE TITLE
[Bug] UMI3.5打包体积变大

### ISSUE THREAD

**Issue by phoema** [umijs/umi#6845]
## What happens?

升级后 打包50M左右
![image](https://user-images.githubusercontent.com/8730272/124207286-c32a6b80-db17-11eb-8e9a-69bad52e31ae.png)
升级前 打包11M左右
![image](https://user-images.githubusercontent.com/8730272/124207309-ce7d9700-db17-11eb-84c5-0773080fd572.png)

修改了依赖从umi3.4. 到3.5开启了
  mfsu: {},
  webpack5: {},
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by peterzhai** [comment]
我用了document.ejs 启动就报错了mf-va_remoteEntry.js 里是html。

**Comment by theDoinb** [comment]
解决了吗？我最近也是升级umi3.5后，开启了 MFSU.production， 然后打包体积增大了一倍不知为什么
