### ISSUE TITLE
是否有监听历史路由的功能，像浏览器一样打开新标签一样的功能

### ISSUE THREAD

**Issue by robin536180** [umijs/umi#6848]
<img width="847" alt="截屏2021-07-02 上午11 21 08" src="https://user-images.githubusercontent.com/8565176/124215955-ab5ae380-db27-11eb-846c-2d6b469c09fa.png">

**Comment by robin536180** [comment]
有没有思路或者建议，请教下

**Comment by Ling-Hu-Chongi** [comment]
看下dva的subscriptions
