### ISSUE TITLE
build   到 91% 就卡住  就一直停着不动了

### ISSUE THREAD

**Issue by wangxiansheng001** [umijs/umi#685]
![image](https://user-images.githubusercontent.com/30206377/42292030-1bdebc96-8002-11e8-96ce-0756dd41551f.png)

**Comment by wangxiansheng001** [comment]
为什么build无法通过，一直卡住在91%，怎么办

**Comment by sorrycc** [comment]
91% 是在压缩，依赖太大了，把一部分走 externals 吧，参考 https://hackmd.io/YHK_yuRtT0ePPVLY0_kUzw
