### ISSUE TITLE
[Bug] 启用了mfsu后，Theme配置无效

### ISSUE THREAD

**Issue by tonny008** [umijs/umi#6851]
## What happens?
ant design pro config.ts启用mfsu，并自定义primary-color。没有生效

## Mini Showcase Repository(REQUIRED)

```
  mfsu: {},
  theme: {
    'primary-color': 'red',
  }
```

## Context

- **Umi Version**:3.5.0
- **Node Version**:16
- **Platform**:macOS

**Comment by sorrycc** [comment]
强刷下页面，其实已经生效了，是缓存的问题。

**Comment by wen-haoming** [comment]
我也遇到过这种情况，但我强制刷新还是没有效果，最后的解决办法是，删除掉 .umi 的文件夹，重新 ` npm start ` 就可以了。
