### ISSUE TITLE
启用mfsu后splitChunks配置不可以用了

### ISSUE THREAD

**Issue by Ling-Hu-Chongi** [umijs/umi#6852]
报错信息
Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration[0].optimization.splitChunks should be one of these:
   false | object { automaticNameDelimiter?, cacheGroups?, chunks?, defaultSizeTypes?, enforceSizeThreshold?, fallbackCacheGroup?, filename?, hidePathInfo?, maxAsyncRequests?, maxAsyncSize?, maxInitialRequests?, maxInitialSize?, maxSize?, minChunks?, minRemainingSize?, 
minSize?, name?, usedExports? }
   -> Optimize duplication and caching by splitting chunks by shared modules and cache group.
   Details:
    * configuration[0].optimization.splitChunks.name should be one of these:
      false | string | function
      -> Give chunks created a name (chunks with equal name are merged).
      Details:
       * configuration[0].optimization.splitChunks.name should be false.
       * configuration[0].optimization.splitChunks.name should be a string.
       * configuration[0].optimization.splitChunks.name should be an instance of function.

配置
`config.merge({
            optimization: {
                splitChunks: {
                    chunks: 'all',
                    automaticNameDelimiter: '.',
                    name: true,
                    minSize: 30000,
                    maxSize: 0,
                    minChunks: 1,
                    maxAsyncRequests: 10,
                    maxInitialRequests: 5,
                    cacheGroups: {
                        vendors: {
                            name: 'vendors',
                            test: /[\\/]node_modules[\\/](react|react-dom|react-router|react-router-dom|lodash|lodash-decorators|redux-saga|re-select|dva|moment)[\\/]/,
                            priority: -10,
                        },
                        antdesigns: {
                            name: 'antdesigns',
                            test: /[\\/]node_modules[\\/](@ant-design|antd|@antd)[\\/]/,
                            priority: -11,
                        },
                        default: {
                            minChunks: 1,
                            priority: -12,
                            reuseExistingChunk: true,
                        },
                    },
                },
            },
        });`

**Comment by sorrycc** [comment]
这是自定义的配置不兼容 webpack 5。
