### ISSUE TITLE
使用mfsu以后dumi组件展示报错

### ISSUE THREAD

**Issue by BarrySong97** [umijs/umi#6853]
## What happens?

开启mfsu以后dumi 组件展示报错，关闭以后就恢复
![image](https://user-images.githubusercontent.com/23427423/124227492-588c2680-db3d-11eb-976d-6f1b3baabae7.png)
nvalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem. at Object.throwInvalidHookError (http://localhost:8000/mf-dep_vendors-node_modules_react-dom_index_js.dc58d0bf.async.js:14915:13) at Object.useRef (http://localhost:8000/mf-dep_vendors-node_modules_react_index_js.699149b9.async.js:1626:21) at useForm (http://localhost:8000/mf-dep_vendors-node_modules_rc-field-form_es_index_js.dbcb1766.async.js:3701:52) at Object.useForm (http://localhost:8000/mf-dep_vendors-node_modules_antd_es_form_index_js.42221d29.async.js:1191:74) at _callee$ (http://localhost:8000/dumi_demos.js:75:46) at tryCatch (http://localhost:8000/mf-dep_vendors-node_modules_umi_node_modules_regenerator-runtime_runtime_js.62774c63.async.js:53:40) at Generator.invoke [as _invoke] (http://localhost:8000/mf-dep_vendors-node_modules_umi_node_modules_regenerator-runtime_runtime_js.62774c63.async.js:282:22) at Generator.prototype.<computed> [as next] (http://localhost:8000/mf-dep_vendors-node_modules_umi_node_modules_regenerator-runtime_runtime_js.62774c63.async.js:105:21) at asyncGeneratorStep (http://localhost:8000/mf-dep_src_umi_cache_mfsu_mf-va_D__code_technology-and-economy_node_modules__umijs_babel-preset-umi_-c9ffba.12b8779d.async.js:16:24) at _next (http://localhost:8000/mf-dep_src_umi_cache_mfsu_mf-va_D__code_technology-and-economy_node_modules__umijs_babel-preset-umi_-c9ffba.12b8779d.async.js:38:9)

![image](https://user-images.githubusercontent.com/23427423/124227541-7063aa80-db3d-11eb-9681-456b70c84e16.png)
![image](https://user-images.githubusercontent.com/23427423/124227561-778ab880-db3d-11eb-9a1a-89e51ec63e08.png)

**Comment by xiefengnian** [comment]
我在默认的 antd-pro v5 项目中没有复现这个问题，需要提供更详细的复现信息例如 config 文件

**Comment by BarrySong97** [comment]
> 我在默认的 antd-pro v5 项目中没有复现这个问题，需要提供更详细的复现信息例如 config 文件

![image](https://user-images.githubusercontent.com/23427423/124442733-9d1ef880-ddaf-11eb-8d5a-7d78799b386c.png)
![image](https://user-images.githubusercontent.com/23427423/124443038-ea02cf00-ddaf-11eb-904c-77653a100dfc.png)
![image](https://user-images.githubusercontent.com/23427423/124443050-ec652900-ddaf-11eb-8595-335feeba10dd.png)

**Comment by yangzhenxi** [comment]
在config上添加mfsu后dumi报错
![image](https://user-images.githubusercontent.com/41821001/124700839-0de52280-df20-11eb-9e9f-c36343431119.png)

**Comment by sorrycc** [comment]
@yangzhenxi 需要给复现步骤或仓库。
