### ISSUE TITLE
[Bug] 启用msfu之后，swiper加载报错

### ISSUE THREAD

**Issue by SunshineH2** [umijs/umi#6855]
## What happens?

umi: 3.5
swiper: 6.7.1
报错：[@umijs/runtime] load component failed Error: Module "./swiper/react" does not exist in container.
while loading "./swiper/react" from webpack/container/reference/mf

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by ppxu** [comment]
这边也遇到了一样的问题，Module "./mathjs" does not exist in container. while loading "./mathjs" from webpack/container/reference/mf

**Comment by LeoHuiyi** [comment]
Module Federation 加上splitChunks官方都很多问题

**Comment by sorrycc** [comment]
mfsu 支持 splitChunks，有问题的都是因为加的配置和 webpack 5 不兼容。 @LeoHuiyi

**Comment by sorrycc** [comment]
需要复现步骤。

**Comment by xiefengnian** [comment]
无法复现，需要提供实际的使用场景

**Comment by huya666** [comment]
我也遇到这样的问题，如何解决的呢？

**Comment by htank-wang** [comment]
[@umijs/runtime] load component failed Error: Module "./antd/es/calendar/style" does not exist in container.
while loading "./antd/es/calendar/style" from webpack/container/reference/mf

关闭MFSU就好了。

**Comment by jdz321** [comment]
解决办法：删除src/.umi/.cache，重新跑就可以了。

我有空了看看啥问题。  @sorrycc @xiefengnian 可以帮忙看看，我很久不用umi了不太熟悉

复现步骤为：
1. 安装并引入Swiper，启动项目
  ```ts
  import { Swiper, SwiperSlide } from 'swiper/react'
  ```
2. 引入Swiper其它组件（任意文件即可，包括css）
  ```ts
  import { Swiper as SwiperCore, Pagination } from 'swiper/core'
  ```

可以看到`Module "./swiper/xxx" does not exist in container.`报错信息。

**Comment by jdz321** [comment]
> 解决办法：删除src/.umi/.cache，重新跑就可以了。
> 
> 我有空了看看啥问题。 @sorrycc @xiefengnian 可以帮忙看看，我很久不用umi了不太熟悉
> 
> 复现步骤为：
> 
> 1. 安装并引入Swiper，启动项目
> 
> ```ts
> import { Swiper, SwiperSlide } from 'swiper/react'
> ```
> 
> 1. 引入Swiper其它组件（任意文件即可，包括css）
> 
> ```ts
> import { Swiper as SwiperCore, Pagination } from 'swiper/core'
> ```
> 
> 可以看到`Module "./swiper/xxx" does not exist in container.`报错信息。

删除src/.umi/.cache，重新跑， css貌似没有正常加载，但是也没有报错

**Comment by yqcs** [comment]
删除src/.umi/.cache之后样式就没了，怎么搞

**Comment by SunshineH2** [comment]
有时经常会报这个错误，我都是把node包删掉，重新安装，这样多试几次就好了

**Comment by jdz321** [comment]
> 删除src/.umi/.cache之后样式就没了，怎么搞

猜测可能是路径太长。。 配了个alias解决了，感觉好奇怪
```js
// .umirc.ts
{
  alias: {
    'swiper.pagination': 'swiper/components/pagination'
  },
}
```
```js
import 'swiper.pagination/pagination.less'
```
反正好了  摊手

**Comment by crazyair** [comment]
https://github.com/umijs/umi/issues/6611#issuecomment-848545109

**Comment by thisTom** [comment]
> 需要复现步骤。
![微信截图_20220518152254](https://user-images.githubusercontent.com/19346741/169023202-21305283-7fc9-4e87-990a-b5c8a676496d.png)
umi不支持swiper8得引入方式？
![image](https://user-images.githubusercontent.com/19346741/169023496-1d3bb2fd-fde4-4a88-b947-8e98cefed5f7.png)

如果使用如下引入方式，代码能跑，但是无法开启mfsu， antd项目 太慢了，希望帮忙解决下这个问题
![image](https://user-images.githubusercontent.com/19346741/169023595-28750f5a-f025-4df3-a9e3-2be8bdd03889.png)

**Comment by qiutian00** [comment]
@thisTom  可以参考这个， 用的是swiper6的版本， https://github.com/umijs/umi/issues/6855#issuecomment-894755935  
![image](https://user-images.githubusercontent.com/24382500/173020834-f0e04f99-c40a-4fa1-90e7-a999c0f2222f.png)
