### ISSUE TITLE
这个问题怎么解决### 在 _ant design pro_  中修改MFSU相关配置后报这个错误！！！

### ISSUE THREAD

**Issue by Brightchild** [umijs/umi#6859]
### CC大佬 在 _ant design pro_  中修改MFSU相关配置后报这个错误！！！
![image](https://user-images.githubusercontent.com/55118447/123224206-30307680-d504-11eb-87b7-9f3ba0b34b49.png)

_Originally posted by @ChrisAndTracy in https://github.com/umijs/umi/issues/6766#issuecomment-867422277_

**Comment by sorrycc** [comment]
试试 umi@3.5.2

**Comment by twinkle77** [comment]
已升级到 3.5.2，还是同样的报错

![image](https://user-images.githubusercontent.com/17792166/124407654-13533900-dd77-11eb-8b05-d7fefde87ac6.png)

![image](https://user-images.githubusercontent.com/17792166/124408402-c2444480-dd78-11eb-975b-40b2e1e7a2e9.png)

**Comment by PeachScript** [comment]
@twinkle77 是 Ant Design Pro 的初始化脚手架吗，本地有自定义 dumi 主题引入 `dumi-theme-default/src/builtins/Previewer.tsx` 么

**Comment by xiefengnian** [comment]
麻烦提供一下 preset-dumi 的版本

**Comment by Brightchild** [comment]
> 麻烦提供一下 preset-dumi 的版本
1.1.0-rc.6

![image](https://user-images.githubusercontent.com/20610232/124415851-4ce07000-dd88-11eb-878c-0fcdb3f1c38f.png)

**Comment by Brightchild** [comment]
> 麻烦提供一下 preset-dumi 的版本

1.1.0-rc.6
![image](https://user-images.githubusercontent.com/20610232/124415950-8618e000-dd88-11eb-9121-297db589bc81.png)

**Comment by xiefengnian** [comment]
现在最新的 1.1.23，试一下升级到最新：

**Comment by twinkle77** [comment]
@PeachScript  是的，是ant-desgin-pro脚手架生成的模板。
“本地有自定义 dumi 主题引入 dumi-theme-default/src/builtins/Previewer.tsx 么” - 没有哦，搜索相关代码并没找到

---

```
"umi": "^3.5.2",
"@umijs/preset-dumijs": "^1.1.23"
````

@xiefengnian  尝试升级 ```@umijs/preset-dumijs``` 后，报下面的错误


![image](https://user-images.githubusercontent.com/17792166/124427292-cafb4180-dd9d-11eb-9d84-c5e1dbd64f9b.png)

**Comment by sorrycc** [comment]
https://github.com/umijs/umi/issues/6766 FAQ 里有。
