### ISSUE TITLE
[Bug] 开启mfsu, dumi-theme-default报错

### ISSUE THREAD

**Issue by shaodushu** [umijs/umi#6866]
## What happens?

![image](https://user-images.githubusercontent.com/26360246/124374292-a6836480-dccc-11eb-979f-da396a1b6746.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

![image](https://user-images.githubusercontent.com/26360246/124374339-1b569e80-dccd-11eb-88d5-493101b4c8c1.png)

- **Umi Version**:3.5.2
- **Node Version**:14.15.0
- **Platform**:ubuntu20

**Comment by sorrycc** [comment]
dumi 或 dumi preset 版本需要更新。

**Comment by codering** [comment]
升级了 preset-dumi到最新版本(1.1.23) ， 还是有错
![image](https://user-images.githubusercontent.com/2271825/124449665-3f41df00-ddb6-11eb-8091-2dd2252a5e41.png)

**Comment by codering** [comment]
> 升级了 preset-dumi到最新版本(1.1.23) ， 还是有错
> ![image](https://user-images.githubusercontent.com/2271825/124449665-3f41df00-ddb6-11eb-8091-2dd2252a5e41.png)

删除 .umi 后重新运就可以了。
