### ISSUE TITLE
[Bug]  npm run build 告警

### ISSUE THREAD

**Issue by hihuangwei** [umijs/umi#6870]
````
(node:22840) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:22840) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS
_STAGE_* as stage option)
(node:22840) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader

````

**Comment by zcSkr** [comment]
插个眼，目前告警好像没影响打包出的产物

**Comment by hihuangwei** [comment]
"umi": "^3.5.8",  依然没有解决 @jrschumacher

**Comment by raintygao** [comment]
> "umi": "^3.5.8", 依然没有解决 @jrschumacher

有复现的repo么，表示用3.5.8的umi `yarn create @umijs/umi-app`没能复现

**Comment by furylee** [comment]
今天clone了一个新的下来,build的时也有这个warning, DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS .

**Comment by pendulm** [comment]
这个问题有解决方案吗？

**Comment by jackge0323** [comment]
同样遇到了这个问题，强迫症好难受，有解决方案吗？

**Comment by s464446877** [comment]
现在一样同样遇到这个问题

**Comment by RThong** [comment]
插个眼

**Comment by zhouzyc** [comment]
插个眼

**Comment by xiaoheikejj** [comment]
插个眼

**Comment by qiliangya** [comment]
插

**Comment by daidi** [comment]
插

**Comment by xyy7260** [comment]
+1

**Comment by azx1985** [comment]
[DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors
(Use `node --trace-deprecation ...` to show where the warning was created)

请问解决了吗？

**Comment by zcSkr** [comment]
👀

**Comment by mastercbhw** [comment]
👀

**Comment by wangerwang** [comment]
👀

**Comment by fengluhome** [comment]
同问，啥时候给解决啊

**Comment by zhuguibiao** [comment]
.umirc.ts 文件添加chainWebpack生产环境配置就可以了
```js
chainWebpack(config, { env }) {
    if (env === 'production') {
      config.optimization.delete('noEmitOnErrors');
      config.plugins.delete('optimize-css');

      // 因为删除原来适配webpack4的css压缩插件，css压缩可以用 mini-css-extract-plugin
     config.optimization.minimize(true)
     config.optimization.minimizer(`css-esbuildMinify`).use(CSSMinimizerWebpackPlugin);
    }
    console.log(config.toConfig());
  },
```

**Comment by houchaowei** [comment]
> .umirc.ts 文件添加chainWebpack生产环境配置就可以了
> 
> ```js
> chainWebpack(config, { env }) {
>     if (env === 'production') {
>       config.optimization.delete('noEmitOnErrors');
>       config.plugins.delete('optimize-css');
> 
>       // 因为删除原来适配webpack4的css压缩插件，css压缩可以用 mini-css-extract-plugin
>      config.optimization.minimize(true)
>      config.optimization.minimizer(`css-esbuildMinify`).use(CSSMinimizerWebpackPlugin);
>     }
>     console.log(config.toConfig());
>   },
> ```

这个对我来说管用了
