### ISSUE TITLE
用户想在用create-umi-app脚手架生成项目的时候，想生成自己定义的文件夹目录文件，这个能支持吗？或者有什么简单的方案可以实现？

### ISSUE THREAD

**Issue by wangyuan0108** [umijs/umi#6875]
在初始化创建项目的时候，默认的文件目录太简单，很多需要去配置开启，有没有什么方法可以生成自定义的文件夹目录和配置，这样在使用脚手架生成项目目录的时候可以只配置一次就可以了

**Comment by sorrycc** [comment]
不能支持，建议手动维护一个脚手架。
