### ISSUE TITLE
[Bug] require 在启用 mfsu 后，页面白屏，组件加载不到

### ISSUE THREAD

**Issue by twinkle77** [umijs/umi#6877]
## What happens?

背景：
由于多国家复用同一套代码，在代码中使用了 require方法 + 环境变量region 来动态加载组件

现象：
路由对应的页面组件加载不出来，表现为浏览器白屏（未升级 mfsu之前，项目是正常跑的，可能是使用了 require 动态加载导致的？）

## Mini Showcase Repository(REQUIRED)

需要可提供

## How To Reproduce

1. 使用 antd-pro 脚手架生成项目模块

2. 配置路由
![image](https://user-images.githubusercontent.com/17792166/124466331-24c53100-ddc9-11eb-9580-6b8af5376fcc.png)

3.  新增```loan/list```组件，
![image](https://user-images.githubusercontent.com/17792166/124466684-6eae1700-ddc9-11eb-90ee-1ed47143326c.png)

4. 配置 config.ts， 打包成功
```
mfsu: {},
webpack5: {},
chainWebpack(config) {
    config.module.rule('mjs-rule').test(/.m?js/).resolve.set('fullySpecified', false)
 }
```

5. 访问 ```localhost:8888/seller/loan```，页面白屏

6. 现象截图
![image](https://user-images.githubusercontent.com/17792166/124467044-e7ad6e80-ddc9-11eb-8f9d-6726c361a20e.png)

7. console 报错信息，看起get component得到undefined导致页面渲染不出来？
![image](https://user-images.githubusercontent.com/17792166/124467105-fbf16b80-ddc9-11eb-9d76-6a9df5b8b4b1.png)

## Context

- **Umi Version**: 3.5.2
- **Node Version**: v12.18.3
- **Platform**: mac

**Comment by sorrycc** [comment]
require 在 esm 场景下不能使用，你看有通过 import 动态加载模块的方法吗/

**Comment by sorrycc** [comment]
改成这种写法，

```
const test = 'test';
const foo = (await import((`../${test}`))).default;
```

**Comment by YiField** [comment]
代码里面用requre引用的资源怎么修改呢
`
const loadingGif = require('./imgs/loading.gif');
改成
const loadingGif = (await import('./imgs/loading.gif')).default;
loading.gif没有写导出呀
`

**Comment by HeyShinner** [comment]
> 代码里面用requre引用的资源怎么修改呢 `const loadingGif = require('./imgs/loading.gif'); 改成 const loadingGif = (await import('./imgs/loading.gif')).default; loading.gif没有写导出呀`

解决了吗？我看我项目里好多 require 写法
