### ISSUE TITLE
[Bug] yarn build 页面白屏

### ISSUE THREAD

**Issue by henryzp** [umijs/umi#6878]
## What happens?

运行`yarn build`命令后，访问URL，页面白屏

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/henryzp/umi3-test

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

1. 运行yarn build
2. mv ./dist ./new-front
3. hs -p 8003   (hs为http-server)

访问http: //localhost:8003/new-front，页面白屏

## Context

- **Umi Version**: 3.5.2
- **Node Version**:  v10.21.0
- **Platform**:  mac

**Comment by xiefengnian** [comment]
这个项目好像不开 mfsu 也无法访问？

**Comment by xiefengnian** [comment]
经过测试，是 optimization.splitChunks 的问题

**Comment by henryzp** [comment]
@xiefengnian ，确实是。。。然后用3.5.0的版本，是正常的。。

**Comment by henryzp** [comment]
所以现在的问题是说：到了最新的版本之后，不建议有这个`optimization.splitChunks`的配置么？
@xiefengnian

**Comment by henryzp** [comment]
另外在去掉这个配置之后，页面只会显示：loading...

请问要怎么解决？

**Comment by sorrycc** [comment]
试了下，build 就报错了，还不能复现白屏的问题。

产物如下，但 chunks 里配了 reactVendor 等，找不到所以报错。
![image](https://user-images.githubusercontent.com/35128/125223985-3f366780-e2ff-11eb-8ce8-e5fc0799213c.png)

**Comment by henryzp** [comment]
@sorrycc ，去掉optimization.splitChunks的配置

然后上传.mfsu-prod文件夹到远程服务器就好了
