### ISSUE TITLE
mfsu 一些bug

### ISSUE THREAD

**Issue by LeoHuiyi** [umijs/umi#6885]
复现仓库包：
[umi-msfu-bugs.zip](https://github.com/umijs/umi/files/6766928/umi-msfu-bugs.zip)

 
bug1: css加载顺序出问题:
复现步骤：
1.注释~/config/config.ts中的mfsu:{}, npm run start, ~/src/layout/index.tsx中的btn color颜色生效
![image](https://user-images.githubusercontent.com/8001457/124532989-254edd80-de44-11eb-82cf-d2d00927aeac.png)

2.打开~/config/config.ts中的mfsu:{}, 删除~/.umi缓存， npm run start, ~/src/layout/index.tsx中的btn color颜色失效
![image](https://user-images.githubusercontent.com/8001457/124533244-88d90b00-de44-11eb-8ef6-5b285b6481f6.png)

bug2: @umijs/babel-plugin-import-to-await-require， 不支持export { Button as default } from 'antd'; 这种导出方式ast解析
复现步骤：
~/src/pages/index.tsx 打开 // import Btn from '../components/btn' ，{/*<Btn/>*/} 注释会报错.

Umi Version: 3.5.3
Node Version: v12.18.3
Platform: window10

**Comment by xiefengnian** [comment]
bug1: https://github.com/umijs/umi/pull/6898
bug2: 很必须写成这样吗，能不能拆成两句写？

**Comment by LeoHuiyi** [comment]
> bug2: 很必须写成这样吗，能不能拆成两句写？
可以拆开，但是旧项目改动较大，还是希望官方能支持下。
