### ISSUE TITLE
[Bug] MFSU开启后, 引入braft-editor失败

### ISSUE THREAD

**Issue by 3lang3** [umijs/umi#6887]
## What happens?
```tsx
// 开启msfu后，引入的BraftEditor为undefined
import BraftEditor from 'braft-editor';
```

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

[复现代码](https://github.com/3lang3/report-bug-umi)

## How To Reproduce

1. clone code
2. yarn  && yarn start

## Context

- **Umi Version**: 3.5.3
- **Node Version**: 15.8.0
- **Platform**: macOs

**Comment by sorrycc** [comment]
复现了，是有问题。

**Comment by 3lang3** [comment]
@sorrycc 升级到3.5之后不开启mfsu，比之前3.4.x要慢好多啊 同一个项目以前大概30s左右，现在要80-90s。

**Comment by sorrycc** [comment]
@3lang3 应该不会，没相关逻辑改动，需要给复现步骤。

**Comment by 3lang3** [comment]
@sorrycc 做了对比 确实没区别，之前启动是有缓存的，印象流了。

**Comment by zcSkr** [comment]
解决方案
const BraftEditor = require('braft-editor').default;
const { ContentUtils } = require('braft-utils');
const Table = require('braft-extensions/dist/table').default;

**Comment by sorrycc** [comment]
@zcSkr 别改代码，等我们修复。

**Comment by sorrycc** [comment]
也别用 require，require 走不了 mfsu 。
