### ISSUE TITLE
Way to test if location.pathname is a 404 route in layouts/index.js

### ISSUE THREAD

**Issue by leftstick** [umijs/umi#689]
Once we provide our own `404.js`, like below:

```
├── mock/ 
└── src/ 
    ├── layouts/index.js
    ├── pages/
        ├── document.ejs
        ├── 404.js                 // not found page
        └── page1.js
├── .umirc.js
└── package.json
```

It will be used  when no routes matched. This is cool, but the thing is, `404.js` rendered via `layouts/index.js`, and there is no easy way to test if current `location.pathname` is a `404` page or not.

I am thinking if it is possible to pass a variable/function to tell this result, something like

```javascript
export default function Layouts(props) {

  if (props.noRoutesMatched) {
    return props.children
  }
  
  return <OtherLayout >{props.children}</OtherLayout>
}
```

**Comment by xiaohuoni** [comment]
尝试使用
```js
export default ({ children ,match}) => {
  if(!match.isExact) {
    return (
      <div>
      {
        children
      }
    </div>
    )
  }
  return (
    <div>
      <div>Header (layouts/index.js)</div>
      <hr/>
      {
        children
      }
      <hr/>
      <div>Footer (layouts/index.js)</div>
    </div>
  );
}
```
不知道能否满足你的需求。

**Comment by leftstick** [comment]
@xiaohuoni ，谢谢。不过我这边的情况有点不同，这个方法不行。我试了下，`match.isExact`返回全部都是`false`，这点我也没弄明白到底什么鬼

**Comment by xiaohuoni** [comment]
我实在这个文件修改的，可以区分。你可以试试[examples/routes](https://github.com/umijs/umi-examples/blob/master/routes/layouts/index.js)

**Comment by leftstick** [comment]
我试了下这个例子代码，还是不行，录了个gif

![issue](https://user-images.githubusercontent.com/1059956/42404832-6e6251a8-81bf-11e8-82d0-2ee2d229dfc2.gif)

我在`layouts/index.js`打印`match`对象，可以看到，路由变化时，对于能找到的路由也多次返回了`isExact: false`，估计我得再多做些细节调研，顺便说下，我把依赖更新到最新了：

```javascript
{
  "scripts": {
    "start": "umi dev"
  },
  "devDependencies": {
    "umi-plugin-routes": "^0.1.5"
  },
  "dependencies": {
    "react-router-breadcrumbs-hoc": "^2.1.4",
    "react-transition-group": "^2.4.0",
    "umi": "^1.3.13"
  }
}
```

**Comment by sorrycc** [comment]
我觉得应该通过 #832 来解决。
