### ISSUE TITLE
[Bug] 开启MFSU后，fastRefresh失效

### ISSUE THREAD

**Issue by IronKinoko** [umijs/umi#6896]
## What happens?

开启MFSU后，react-refresh失效。能热更新，但是不会保留值

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

```tsx
const App = () => {
  return (
    <div>
      <input type="text" />
      123
    </div>
  )
}
```

1. 关闭mfsu的时候，每次修改123文字，input里的值还保留的
2. 开启mfsu后，每次修改123文字，input里的值都被清空

**Expected behavior** 1. 2.

## Context

- **Umi Version**: v3.5.3
- **Node Version**: v15.5
- **Platform**: mac

**Comment by zcSkr** [comment]
同问，插眼关注

**Comment by sorrycc** [comment]
用不用 mfsu 都一样吧？fast refresh 不能用匿名函数的。

**Comment by IronKinoko** [comment]
关闭mfsu的时候是有效果的

直接`yarn create @umijs/umi-app` 创建一个新的app
```tsx
const App = () => {
  return (
    <div>
      <input type="text" />
      123
    </div>
  )
}
export default App
```
修改123文本的时候
这段代码在 mfsu 开启和关闭两种状态表现不同

**Comment by IronKinoko** [comment]
热更新获得的文件里看到这些代码
```js
const currentExports = __react_refresh_utils__.getModuleExports(module.id);
__react_refresh_utils__.registerExportsForReactRefresh(
  currentExports,
  module.id,
);
```

msfu开启前 获取到的是个`Module`对象 `registerExportsForReactRefresh`执行到了`Refresh.register`

![A0C2BF78-2235-4D69-9911-E1BBA77EC54F](https://user-images.githubusercontent.com/32838658/124564761-f6506000-de73-11eb-8187-8f71270fdf6b.png)

msfu开启后 获取到的是个`Promise`对象 `registerExportsForReactRefresh`没执行到`Refresh.register`
![D28695A5-F7AD-4F6C-A1C9-A4C584E6E2D5](https://user-images.githubusercontent.com/32838658/124564838-0a945d00-de74-11eb-9b91-b75c1d21659f.png)

**Comment by sorrycc** [comment]
ref: https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/435

**Comment by nannan0109** [comment]
同问 解决了没

**Comment by ratelgogo** [comment]
插眼👀

**Comment by handycode** [comment]
插眼👀

**Comment by majian159** [comment]
+1

**Comment by ILuZhangKun** [comment]
+1

**Comment by ILuZhangKun** [comment]
merge之后好像也没解决呀

**Comment by wmy94827** [comment]
+1
