### ISSUE TITLE
[Bug] 同时使用qiankun和msfu时，在主应用中子应用模块无法加载

### ISSUE THREAD

**Issue by Onion17** [umijs/umi#6909]
## What happens?

同时使用qiankun和msfu时，在主应用中子应用模块无法加载（umi版本3.5.4，已关闭沙箱）

复现仓库：https://github.com/Onion17/demo.git

复现步骤：启动主应用和子应用，在主应用中访问子应用

![image](https://user-images.githubusercontent.com/40941533/124691174-f9982a00-df0d-11eb-8c65-97ae5e75c111.png)

**Comment by wzxm** [comment]
我这边也遇到了这个问题，使用了 msfu 模式后，就无法访问子应用。

**Comment by zhangsai521314** [comment]
我这边4.5版本的可以加载最新react pro v5的子应用，v5主应用加载不了v5的子应用。已经关闭了mfsu

**Comment by zhangsai521314** [comment]
@Onion17 你这个错误在mfsu发布第一天就存在了....

**Comment by Shino161** [comment]
同样存在这样的问题，开发环境是正常的，打包之后就无法加载子应用模块了
