### ISSUE TITLE
[Bug] 开启MFSU后，dumi的Markdown里<API /> 功能报错

### ISSUE THREAD

**Issue by IronKinoko** [umijs/umi#6913]
## What happens?

开启MFSU后，dumi的Markdown里<API /> 功能报错

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

```md
## Scheme

### 基础布局

<code src="./demos/layout.tsx" />

<API src="./index.tsx"/>
```

md里仅有这些内容。开启mfsu的时候报错。关闭后能正常渲染

![image](https://user-images.githubusercontent.com/32838658/124706814-70dbb700-df2a-11eb-8e17-af9e0c69bad6.png)

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.5.4
- **DUmi version**: 1.0.16
- **Node Version**: 15
- **Platform**: mac

**Comment by sorrycc** [comment]
需要给复现。

**Comment by sorrycc** [comment]
解决了？

**Comment by IronKinoko** [comment]
我无法重现这个问题，就先关闭了
