### ISSUE TITLE
[Bug] 开启webpack5后提示Buffer is not defined

### ISSUE THREAD

**Issue by silentim** [umijs/umi#6914]
## What happens?

开启webpack5后，编译提示Buffer is not defined

项目中有用到Buffer，直接将 buffer: 6.0.3 加入依赖并安装，仍然提示错误

```
ReferenceError: Buffer is not defined
./node_modules/core-util-is/lib/util.js
./node_modules/core-util-is/lib/util.js:103
```

- **Umi Version**: 3.5.4
- **Node Version**: v14.16.0
- **Platform**: windows

**Comment by yingjieg** [comment]
应该是umi新版本用了webpack5，导致不再默认对node core modules进行polyfill，我只能通过插件来主动做这件事

1. npm install buffer
2.   new webpack.ProvidePlugin({
          Buffer: ['buffer', 'Buffer'],
      }),

**Comment by silentim** [comment]
我也这样配置过，但没用，包括webpack官网提过的方法
