### ISSUE TITLE
[Bug] mfsu 开启并没有把node_modules里面的所有的包都打包出来

### ISSUE THREAD

**Issue by LeoHuiyi** [umijs/umi#6915]
mfsu 开启并没有把node_modules里面的所有的包都打包出来

![image](https://user-images.githubusercontent.com/8001457/124715041-18f67d80-df35-11eb-9ee5-c5869b06b9a7.png)

## Context

Umi Version: 3.5.4
Node Version: v12.18.3
Platform: window10

**Comment by sorrycc** [comment]
core-js-pure 是啥？给复现。其他是正常的，之后会优化。

**Comment by LeoHuiyi** [comment]
> core-js-pure 是啥？给复现。其他是正常的，之后会优化。

复现代码：
[umi-msfu-bugs.zip](https://github.com/umijs/umi/files/6776110/umi-msfu-bugs.zip)
npm run start:debug；

![image](https://user-images.githubusercontent.com/8001457/124737461-8cef5080-df4a-11eb-8ada-940eb8ffbb59.png)

sourceMap也有问题

@sorrycc

**Comment by LeoHuiyi** [comment]
我认为：msfu + lazyCompilation 才是最快的

**Comment by sorrycc** [comment]
1. 这几个依赖是 by design 的，来自 mini-css-extract-plugin 和 fast-refresh，会找时间优化，但优先级不高
2. mfsu + lazyCompilation 用起来有点问题，访问页面需要等的时间较长
