### ISSUE TITLE
[Bug] 不使用 @umijs/preset-react情况下， 使用plugin-initial-state 启动报错

### ISSUE THREAD

**Issue by sandercage** [umijs/umi#6916]
## What happens?

使用yarn create @umijs/umi-app创建项目后。由于是小项目， 对@umijs/preset-react中的插件不是全部必须， 所以项目中仅依赖了以下三个umi插件：

```
  "@umijs/plugin-initial-state": "^2.3.1",
  "@umijs/plugin-model": "^2.6.1",
  "@umijs/plugin-sass": "^1.1.1",
```

项目启动后报错：Cannot read property '@@initialState' of undefined

## Mini Showcase Repository(REQUIRED)

https://github.com/sandercage/scaffold-h5

## How To Reproduce

1 git clone https://github.com/sandercage/scaffold-h5.git
2 cd scaffold-h5 && yarn
3 yarn dev

启动后报错：

![image](https://user-images.githubusercontent.com/36032199/124727462-5103bd80-df41-11eb-8356-0f12cb24ee8c.png)

## Context

- **Umi Version**: 3.5.4
- **Node Version**: 14.16.1
- **Platform**: 

![image](https://user-images.githubusercontent.com/36032199/124727628-77c1f400-df41-11eb-97a4-2e0aafa79095.png)

- **package.json**: package.json

```json
{
    "dependencies": {
        "antd-mobile": "^2.3.4",
        "classnames": "^2.3.1",
        "dayjs": "^1.10.6",
        "react": "^17.0.2",
        "react-dom": "^17.0.2",
        "umi": "^3.5.4"
    },
    "devDependencies": {
        "@types/classnames": "^2.3.1",
        "@types/react": "^17.0.13",
        "@types/react-dom": "^17.0.8",
        "@umijs/fabric": "^2.6.2",
        "@umijs/plugin-model": "^2.6.1",
        "@umijs/plugin-sass": "^1.1.1",
        "@umijs/plugin-initial-state": "^2.3.1",
        "@umijs/test": "^3.5.3",
        "cross-env": "^7.0.3",
        "lint-staged": "^11.0.0",
        "node-sass": "4.14.1",
        "prettier": "^2.3.2",
        "typescript": "^4.3.5",
        "yorkie": "^2.0.0"
    }
}
```

**Comment by xiaohuoni** [comment]
这个和插件的加载顺序有关，如果没有使用preset，可以修改在package.json中的顺序，如 https://github.com/sandercage/scaffold-h5/pull/1
