### ISSUE TITLE
动态路由生成router.js顺序出错，导致页面显示问题

### ISSUE THREAD

**Issue by ksh033** [umijs/umi#692]
如果图示
正常情况
`  {
        "path": "/basic/developer",
        "exact": true,
        "component": require('../basic/developer/index.js').default
      },
      {
        "path": "/basic/developer/:action?",
        "exact": true,
        "component": require('../basic/developer/$action$.js').default
      },`
异常情况
`   {
        "path": "/basic/rmerchant/:action?",
        "exact": true,
        "component": require('../basic/rmerchant/$action$.js').default
      },{
        "path": "/basic/rmerchant",
        "exact": true,
        "component": require('../basic/rmerchant/index.js').default
      }`
路由地址->/basic/rmerchant 应该进入列表页，结果进去了详情页

![avatar](https://raw.githubusercontent.com/ksh033/test/master/rrouter.js.png)

**Comment by ksh033** [comment]
业务冲突？

**Comment by xiaohuoni** [comment]
看错了，抱歉

**Comment by ksh033** [comment]
@sorrycc 我问题是找到了但是不知道什么原因,请指导一下,是我的目录定义有问题吗？
看了源码，在递归查找合并文件的时候做了排序。我不知道npm start的时候怎么调试你们的代码，不然我就自己找一下原因，哈哈这个看能不能也指导一下。
我是window环境上的。

**问题可以重现目录如下图**

错误文件目录
![avatar](https://raw.githubusercontent.com/ksh033/test/master/bugroute.png)
正确文件目录（我就在models下删除掉一上文件就又可以了）
![avatar](https://raw.githubusercontent.com/ksh033/test/master/successroute.png)

**Comment by suiyi8760** [comment]
@ksh033 请问最后怎么解决的呢

**Comment by snokier** [comment]
同问怎么解决的？
