### ISSUE TITLE
打包后，umi.js包含 ` 字符，在IE11下无法识别

### ISSUE THREAD

**Issue by Cancerbin** [umijs/umi#6921]
本地服务在IE11下可以预览操作，打包后，umi.js会出现 ` 字符，但是在IE11不识别该字符，要怎么解决？

**Comment by Cancerbin** [comment]
可以参考ant design pro 的预览界面，在ie11下面打开开发工具，会报无效字符，经过排查，我发现是 ` 字符不被识别
![image](https://user-images.githubusercontent.com/14088361/124854678-4812fa80-dfda-11eb-9a82-acb846116db0.png)

**Comment by Cancerbin** [comment]
> Hello @Cancerbin. In order to facilitate location and troubleshooting, we need you to provide a realistic example. Please forking these link [codesandbox umi](https://codesandbox.io/s/umi-2d4js?file=/src/pages/index.tsx) or using `yarn create @umijs/umi-app` to create and upload it to your GitHub repository.
> 
> 你好 @Cancerbin, 为了方便定位和排查问题，我们需要你提供一个重现实例，请提供一个尽可能精简的链接 [codesandbox umi](https://codesandbox.io/s/umi-2d4js?file=/src/pages/index.tsx) 或使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

可以通过ant design pro 的官网点击预览，用IE11浏览器打开，umi.js会报无效字符的错误，经过排查，是 ` 字符不被IE浏览器识别
![image](https://user-images.githubusercontent.com/14088361/124855574-b60bf180-dfdb-11eb-9e28-95ea9943ee3f.png)

**Comment by qiaoyuwen** [comment]
我也遇到相同的问题，将config.ts里的esbuild配置去掉就可以了

**Comment by Cancerbin** [comment]
> 我也遇到相同的问题，将config.ts里的esbuild配置去掉就可以了

^o^，厉害啦，感谢大佬的帮助。

**Comment by Cancerbin** [comment]
> 我也遇到相同的问题，将config.ts里的esbuild配置去掉就可以了

^o^，厉害啦，感谢大佬的帮助。
