### ISSUE TITLE
[Bug] mfsu下export * 导出问题

### ISSUE THREAD

**Issue by LeoHuiyi** [umijs/umi#6922]
复现代码：
[umi-msfu-bugs.zip](https://github.com/umijs/umi/files/6780951/umi-msfu-bugs.zip)

复现代码：
~/src/layouts/index.tsx下 import {xxxx} from '../xxx'引用个单独导出export * from 'xxx'的文件导致。感觉没有打包到Module Federation中

![image](https://user-images.githubusercontent.com/8001457/124851389-0af83980-dfd5-11eb-9f30-447a8498217a.png)

Context
Umi Version: 3.5.5
Node Version: v12.18.3
Platform: window10

**Comment by LeoHuiyi** [comment]
![image](https://user-images.githubusercontent.com/8001457/124857065-37fd1a00-dfde-11eb-8a6a-4569e324206b.png)

需要传exportAllMembers，感觉不够智能，希望能解析所有包出来

**Comment by LeoHuiyi** [comment]
![image](https://user-images.githubusercontent.com/8001457/124858194-2d438480-dfe0-11eb-9464-4a8b8846d22d.png)

要加exportAllMembers：{xxx: ['xxx']}才行，感觉不够智能，希望能自动解析出来

**Comment by LeoHuiyi** [comment]
如果引用了@umijs/preset-umi2-compatible，他的umiExports 是 export * from 'xxx/historyAdapater.ts'; 也不会被打包

**Comment by sorrycc** [comment]
给的示例里没找到 `export *`，确定有？

**Comment by sorrycc** [comment]
src/layout/index.tsx 里是这个，

```
import { Button} from 'antd'
import React from "react"
// import {useSelector} from 'dva'
import {useSelector} from '../dva'
import styles from './index.less'



function BaseLayout(props) {

    const state = useSelector((state)=>{
        return state
    })

    console.log(state)

    return(
        <>
            <Button type="primary" className={styles.btn}>
                layout btn
            </Button>
            {props.children}
        </>
    )
}



export default BaseLayout
```

**Comment by LeoHuiyi** [comment]
> import {useSelector} from '../dva'

这个引用的文件~/src/dva/index.js，代码是 export * from 'dva'

**Comment by sorrycc** [comment]
项目里为啥会用 `export *`？先绕过吧，这部分后面也会优化的。

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/124892073-1f0b5d80-e00c-11eb-887b-c9a7c58a47fc.png)

**Comment by LeoHuiyi** [comment]
> 项目里为啥会用 `export *`？先绕过吧，这部分后面也会优化的。

好的，还有就是引用了@umijs/preset-umi2-compatible，在umiExports引入代码是 export * from 'xxx/historyAdapater.ts'; 也不会被打包。这个包也会有问题。

**Comment by 1eeing** [comment]
这个问题解决了吗？
