### ISSUE TITLE
mfsu 模式下，.json not support

### ISSUE THREAD

**Issue by Nick930826** [umijs/umi#6923]
@umijs/preset-built-in/lib/plugins/features/mfsu/getDepReExportContent.js 第 80 行

![image](https://user-images.githubusercontent.com/10228553/124851829-d8027580-dfd5-11eb-9096-06a7bcbbe03f.png)

**Comment by xiefengnian** [comment]
可以描述一下你的使用场景吗？

**Comment by sorrycc** [comment]
`import 'antd/package'` 或者 `import 'antd/package.json'`。

**Comment by Nick930826** [comment]
> 可以描述一下你的使用场景吗？

云谦大大已经描述了，我就是引入了一个 json 文件，报错了。

**Comment by Nick930826** [comment]
> 可以描述一下你的使用场景吗？

云谦大大已经描述了，我就是引入了一个 json 文件，报错了。

**Comment by leftstick** [comment]
我正好在看类似的问题，顺手改了
