### ISSUE TITLE
[Bug] mfsu模式下fastRefresh和global.less问题

### ISSUE THREAD

**Issue by zcSkr** [umijs/umi#6926]
## What happens?

1.如果global.less中写了全局样式，优先级仍然不是最高的
![image](https://user-images.githubusercontent.com/30515821/124870166-d8f6cf80-dff4-11eb-8f5c-97c9b900529c.png)

2.如果引入了自己封装的业务组件，组件目录为pages/xxx/components。则导致fastRefresh失效，不引入则正常。
![image](https://user-images.githubusercontent.com/30515821/124870473-5cb0bc00-dff5-11eb-85cf-69ff418f35fc.png)

## Context

- **Umi Version**: 3.5.5
- **Node Version**: 14.17.1
- **Platform**:macOS 10.15.7

**Comment by sorrycc** [comment]
需要有复现步骤。

**Comment by zcSkr** [comment]
> 需要有复现步骤。

1.yarn create umi myapp
2.写一个测试菜单页面，配置道路由中
3.在该页面的目录中创建components，写一个任意内容组件
4.如图2所示，只要不引入组件fastRefresh正常，如果引入则导致fastRefresh无法刷新

配上 项目地址 https://github.com/zcSkr/antdPro5_umi.git

**Comment by codedart2018** [comment]
> > 需要有复现步骤。
> 
> 1.yarn create umi myapp
> 2.写一个测试菜单页面，配置道路由中
> 3.在该页面的目录中创建components，写一个任意内容组件
> 4.如图2所示，只要不引入组件fastRefresh正常，如果引入则导致fastRefresh无法刷新；（在不引入任何组件的页面中fastRefresh也是正常的，比如create出来项目中的Welcome.js页面）
> 5.在global.less写全局覆盖antd的样式，在global.less中保存则生效，若保存编译过其他任意文件，则如图1，mf-开头的样式优先级高于global.less
> 
> 目前已经升级umi3.5.8 配上 项目地址 https://github.com/zcSkr/antdPro5_umi.git

同样遇见自定义组件引入导致无法更新页面情况、

**Comment by aruldd** [comment]
+1 issue goes away temporarily if you refresh the global.less file.
