### ISSUE TITLE
[Bug] mfsu模式下，antd替换moment报错。

### ISSUE THREAD

**Issue by lujie291231730** [umijs/umi#6930]
antd替换moment，使用antd-dayjs-webpack-plugin插件，mfsu启动后，出现报错。
![image](https://user-images.githubusercontent.com/42669488/124883626-19117e80-e004-11eb-8e89-2038daf01b16.png)

**Comment by sorrycc** [comment]
需要有复现步骤。

**Comment by cl1107** [comment]
> 需要有复现步骤。
https://github.com/cl1107/antd-pro-dayjs-mfsu.git 
yarn start后 
![image](https://user-images.githubusercontent.com/21985353/125940945-f4b0c03f-e251-4796-ba44-7f6d890a8336.png)

打开页面点击分步表单新建就会报错：moment__WEBPACK_IMPORTED_MODULE_0___default(...).isMoment is not a function
@sorrycc

**Comment by sorrycc** [comment]
这个插件和 pro 组件的实现有冲突，开了 mfsu 时先别用吧。

**Comment by NicholasNC** [comment]
> 这个插件和 pro 组件的实现有冲突，开了 mfsu 时先别用吧。

大佬，这个目前有解决方案吗？

还是说在开发环境下开启 mfsu 就不启用  antd-dayjs-webpack-plugin 插件

生产环境下才启用 antd-dayjs-webpack-plugin 替换 moment？

**Comment by hong418884611** [comment]
同样问题
