### ISSUE TITLE
[Bug] config define 失效,.env文件配置的环境参数还是成功的

### ISSUE THREAD

**Issue by furylee** [umijs/umi#6931]
## What happens?
使用umi创建的模板,无论是否开启mfsu,define定义的环境参数都不生效

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.5.7
- **Node Version**:14.17.1
- **Platform**: windows

**Comment by furylee** [comment]
### https://github.com/furylee/defineBug.git

在 app.jsx 第 100行,我打印了process.env,有.env配置的环境参数,但是没有 define配置的环境参数

**Comment by furylee** [comment]
> ``

**Comment by sorrycc** [comment]
需要用 define 配置下的。

**Comment by sorrycc** [comment]
console.log(J);
console.log(H);

改成这样就能打印出来，试着理解下原因。
