### ISSUE TITLE
请问该问题修复了吗

### ISSUE THREAD

**Issue by Ling-Hu-Chongi** [umijs/umi#6933]
> > @sorrycc > @13500Jin 给复现步骤。
> > ### 在ant design pro 提供的 模板项目中：
> > 
> > 1. 将package.json中的umi升级为^3.5.0-beta.9
> >    ![image](https://user-images.githubusercontent.com/55118447/123235191-388daf00-d50e-11eb-9262-a49abcb8a848.png)
> > 2. 在config.ts中添加MFSU相关配置
> >    ![image](https://user-images.githubusercontent.com/55118447/123235099-257adf00-d50e-11eb-96a5-0c970817f11d.png)
> > 
> > ### [模板项目长这样](https://preview.pro.ant.design/dashboard/analysis?primaryColor=%231890ff&fixSiderbar=true&colorWeak=false&pwa=false)
> > ![image](https://user-images.githubusercontent.com/55118447/123235377-62df6c80-d50e-11eb-85d7-d673ebea7985.png)
> > ### 启动项目后，打开项目就会报错！！！
> > ![image](https://user-images.githubusercontent.com/55118447/123235538-8bfffd00-d50e-11eb-9190-b5b21f790833.png)
> > ### 另外：多次尝试删除 node_modules 以及 .umi 目录并重启项目后 访问页面还是报错！！！！
> 
> 命令行有报错信息吗？

### 没有

_Originally posted by @ChrisAndTracy in https://github.com/umijs/umi/issues/6766#issuecomment-868165434_

**Comment by sorrycc** [comment]
给复现步骤，如何提问可参考 https://github.com/umijs/umi/issues/6831#issuecomment-876262448
