### ISSUE TITLE
umi build把项目绝对路径打包到产物中

### ISSUE THREAD

**Issue by shaoqiwang-fe** [umijs/umi#6936]
umi build把项目绝对路径打包到产物中

**Comment by shaoqiwang-fe** [comment]
core_plugin["a" /* plugin */].register({
  apply: app_namespaceObject,
  path: '/Users/xxx/src/app.ts'
});
core_plugin["a" /* plugin */].register({
  apply: plugin_initial_state_runtime_namespaceObject,
  path: '../plugin-initial-state/runtime'
});
core_plugin["a" /* plugin */].register({
  apply: plugin_locale_runtime_namespaceObject,
  path: '/Users/xxx/src/.umi-production/plugin-locale/runtime.tsx'
});

**Comment by shaoqiwang-fe** [comment]
@sorrycc 请问为什么关了呢，在生产环境容易把内网域名暴露，我理解这是个问题吧

**Comment by sorrycc** [comment]
完全没复现步骤，理解不了问题。。建议参考这个 issue 的提问方式，https://github.com/umijs/umi/issues/6831#issuecomment-876262448

**Comment by shaoqiwang-fe** [comment]
1. https://github.com/shaoqiwang-fe/umi-demo
2. npm i && npm run build
3. 进入到dist文件夹下搜索'umi-demo'
4. 发下注册插件比如locale插件的注册
![image](https://user-images.githubusercontent.com/59658783/125257025-95bb9a00-e32f-11eb-918e-311c3e791abe.png)
