### ISSUE TITLE
[Bug] mfsu 模式下启动报错 Check the render method of `LoadableComponent`.

### ISSUE THREAD

**Issue by Jsmond2016** [umijs/umi#6938]
## What happens?

在参考 release 推荐文章 [umi 3.5，让研发重新变得美好](https://zhuanlan.zhihu.com/p/385272270) 尝试对已有项目升级

升级 umijs

```json
"umi": "^3.5.7"
```

`.umirc.ts` 文件新增以下三行代码配置：

```js
 mfsu: {},
 webpack5: {},
 dynamicImport: {},
```

项目启动后浏览器控制台报错为：

```js
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `LoadableComponent`.

...
```

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

复现仓库：https://github.com/Jsmond2016/umi-antd-backend

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

复现方式：

```bash
git clone https://github.com/Jsmond2016/umi-antd-backend.git

cd umi-antd-backend

yarn

yarn start
```
预览地址

```
http://localhost:8000
```

启动后页面无法正确展示，控制台报错

## Context

- **Umi Version**: `    "^3.5.7`
- **Node Version**:  `v12.18.0`
- **Platform**: `windows 10`

**Comment by sorrycc** [comment]
https://github.com/Jsmond2016/umi-antd-backend/blob/main/src/pages/404/index.tsx
这个文件咋是空的？

**Comment by Jsmond2016** [comment]
感谢指正，问题解决

**Comment by hyzx86** [comment]
dynamicImport: {},

这个东西不能用了，删了就好了 ，貌似还没发现有啥影响
