### ISSUE TITLE
[Bug] React+umi(v3.5.7)运行报错

### ISSUE THREAD

**Issue by charminghiker** [umijs/umi#6939]
## React+umi(v3.5.7)运行报错
原来项目用的umi(v3.4.22)没问题，新拉取代码install后umi版本为3.5.7，运行报错。

## npm start报错入下
```shell
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0] has an unknown property 'experiments'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0] has an unknown property 'experiments'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }
    at Object.webpack (D:\WXapp\front\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:138983:9)
    at Bundler.setupDevServerOpts (D:\WXapp\front\node_modules\@umijs\bundler-webpack\lib\index.js:193:40)
    at D:\WXapp\front\node_modules\@umijs\preset-built-in\lib\plugins\commands\dev\dev.js:300:30
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\WXapp\front\node_modules\@umijs\preset-built-in\lib\plugins\commands\dev\dev.js:74:103)
    at _next (D:\WXapp\front\node_modules\@umijs\preset-built-in\lib\plugins\commands\dev\dev.js:76:194)
```

**Comment by Wmstone** [comment]
同问

**Comment by keveon** [comment]
@charminghiker @Wmstone 我的做法是把 `webpack5: {}` 删了就好了，你们可以试试。

**Comment by Curitis** [comment]
同问 3.4.0 也有这样的问题

**Comment by sorrycc** [comment]
没有复现步骤，先关了。

**Comment by guwan** [comment]
> @charminghiker @Wmstone 我的做法是把 `webpack5: {}` 删了就好了，你们可以试试。

我也用你这个方式解决了，但我没明白问题出在哪里。

**Comment by hanwenbo** [comment]
3.5.13 也遇到这个问题

**Comment by phoema** [comment]
3.5.13 注释了webpack5: {}
yarn start还是启动webpack5，报同上的问题

**Comment by furylee** [comment]
从config-dev挪到config里面又可以,不知道为撒

**Comment by JorjanLLT** [comment]
我也遇到了、3月份搭建的项目拉好了依赖没问题。但是现在重新拉依赖可能是什么更新了，umi这边报错了这个问题，我只想说大哥们你们给点力吧...

**Comment by Ireland999** [comment]
我也遇到了、3月份搭建的项目拉好了依赖没问题。但是现在重新拉依赖可能是什么更新了，umi这边报错了这个问题，去掉 webpack5: {} 就不报错了。

**Comment by JorjanLLT** [comment]
> 我也遇到了同样问题，5月份搭建的项目拉好了依赖没问题。但是现在重新拉依赖可能是什么更新了，umi这边报错了这个问题，去掉 webpack5: {} 就不报错了。

我把npm版本降低了继续使用的。我个人用的nvm来管理node版本。然后用node v14.16.0 (npm v6.14.11)这个版本一直用着。你可以试一试这个解决方案

**Comment by Ireland999** [comment]
config.dev.ts 文件中的这项配置 
webpack5: {
    // lazyCompilation: {},
  },
挪到config.ts文件中确实也不报错了

**Comment by JorjanLLT** [comment]
> config.dev.ts 文件中的这项配置
> webpack5: {
> // lazyCompilation: {},
> },
> 挪到config.ts文件中确实也不报错了

我当时这样做也不报错、但是其他引用的antd还是有报错、一些样式好像全部乱了。我是看antd那边的解答让降低版本我才全部好的。

**Comment by Ireland999** [comment]
> > config.dev.ts 文件中的这项配置
> > webpack5: {
> > // lazyCompilation: {},
> > },
> > 挪到config.ts文件中确实也不报错了
> 
> 我当时这样做也不报错、但是其他引用的antd还是有报错、一些样式好像全部乱了。我是看antd那边的解答让降低版本我才全部好的。

使用umi创建的新项目的

> > config.dev.ts 文件中的这项配置
> > webpack5: {
> > // lazyCompilation: {},
> > },
> > 挪到config.ts文件中确实也不报错了
> 
> 我当时这样做也不报错、但是其他引用的antd还是有报错、一些样式好像全部乱了。我是看antd那边的解答让降低版本我才全部好的。

我看使用umi创建的新项目
webpack5: {
// lazyCompilation: {},
},
已经从config.dev.ts中移到config.ts文件中了

**Comment by Ireland999** [comment]
> > 我也遇到了同样问题，5月份搭建的项目拉好了依赖没问题。但是现在重新拉依赖可能是什么更新了，umi这边报错了这个问题，去掉 webpack5: {} 就不报错了。
> 
> 我把npm版本降低了继续使用的。我个人用的nvm来管理node版本。然后用node v14.16.0 (npm v6.14.11)这个版本一直用着。你可以试一试这个解决方案

我试了降低node版本也不行，使用的版本和你描述的版本一模一样

**Comment by JorjanLLT** [comment]
> > > 我也遇到了同样问题，5月份搭建的项目拉好了依赖没问题。但是现在重新拉依赖可能是什么更新了，umi这边报错了这个问题，去掉 webpack5: {} 就不报错了。
> > 
> > 
> > 我把npm版本降低了继续使用的。我个人用的nvm来管理node版本。然后用node v14.16.0 (npm v6.14.11)这个版本一直用着。你可以试一试这个解决方案
> 
> 我试了降低node版本也不行，使用的版本和你描述的版本一模一样

我给你发一下我的package.json
[package-json.txt](https://github.com/umijs/umi/files/7168868/package-json.txt)

**Comment by Ireland999** [comment]
> > config.dev.ts 文件中的这项配置
> > webpack5: {
> > // lazyCompilation: {},
> > },
> > 挪到config.ts文件中确实也不报错了
> 
> 我当时这样做也不报错、但是其他引用的antd还是有报错、一些样式好像全部乱了。我是看antd那边的解答让降低版本我才全部好的。

你当时项目中antd版本用的是多少，共享一下，避免踩坑，谢啦。

**Comment by Ireland999** [comment]
> > config.dev.ts 文件中的这项配置
> > webpack5: {
> > // lazyCompilation: {},
> > },
> > 挪到config.ts文件中确实也不报错了
> 
> 我当时这样做也不报错、但是其他引用的antd还是有报错、一些样式好像全部乱了。我是看antd那边的解答让降低版本我才全部好的。

你当时项目中antd版本用的是多少，共享一下，避免踩坑，谢啦。

**Comment by JorjanLLT** [comment]
> > > config.dev.ts 文件中的这项配置
> > > webpack5: {
> > > // lazyCompilation: {},
> > > },
> > > 挪到config.ts文件中确实也不报错了
> > 
> > 
> > 我当时这样做也不报错、但是其他引用的antd还是有报错、一些样式好像全部乱了。我是看antd那边的解答让降低版本我才全部好的。
> 
> 你当时项目中antd版本用的是多少，共享一下，避免踩坑，谢啦。

"dependencies": {
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-descriptions": "^1.2.0",
    "@ant-design/pro-form": "^1.3.0",
    "@ant-design/pro-layout": "6.15.4",
    "@ant-design/pro-table": "^2.17.0",
    "@umijs/openapi": "1.1.12",
    "@umijs/plugin-openapi": "^1.2.0",
    "@umijs/route-utils": "^1.0.33",
    "antd": "^4.12.0",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "omit.js": "^2.0.2",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "umi": "^3.4.0",
    "umi-request": "^1.0.8"
  },

大概就是这些、上个回复我放了我配置文件的

**Comment by Ireland999** [comment]
> > > > config.dev.ts 文件中的这项配置
> > > > webpack5: {
> > > > // lazyCompilation: {},
> > > > },
> > > > 挪到config.ts文件中确实也不报错了
> > > 
> > > 
> > > 我当时这样做也不报错、但是其他引用的antd还是有报错、一些样式好像全部乱了。我是看antd那边的解答让降低版本我才全部好的。
> > 
> > 
> > 你当时项目中antd版本用的是多少，共享一下，避免踩坑，谢啦。
> 
> "dependencies": {
> "@ant-design/icons": "^4.0.0",
> "@ant-design/pro-descriptions": "^1.2.0",
> "@ant-design/pro-form": "^1.3.0",
> "@ant-design/pro-layout": "6.15.4",
> "@ant-design/pro-table": "^2.17.0",
> "@umijs/openapi": "1.1.12",
> "@umijs/plugin-openapi": "^1.2.0",
> "@umijs/route-utils": "^1.0.33",
> "antd": "^4.12.0",
> "classnames": "^2.2.6",
> "lodash": "^4.17.11",
> "moment": "^2.25.3",
> "omit.js": "^2.0.2",
> "react": "^17.0.0",
> "react-dev-inspector": "^1.1.1",
> "react-dom": "^17.0.0",
> "react-helmet-async": "^1.0.4",
> "umi": "^3.4.0",
> "umi-request": "^1.0.8"
> },
> 
> 大概就是这些、上个回复我放了我配置文件的

嗯嗯，好的，谢啦！

**Comment by jumpingFinger** [comment]
3.5.0 遇到同样的问题

**Comment by EricWong1994** [comment]
我遇到的更奇葩，引用了antd-mobile-v5的Form 后，更改Form.Item的label后页面都不会刷新

**Comment by EricWong1994** [comment]
> 我遇到的更奇葩，引用了antd-mobile-v5的Form 后，更改Form.Item的label后页面都不会刷新

我直接把 mfsu: {},   webpack5: {}, 都注释了才好
