### ISSUE TITLE
[Feature Request] mfsu 开启后允许关闭dynamicImport

### ISSUE THREAD

**Issue by ratelgogo** [umijs/umi#6940]
## Background

动态加载文件太多了，我们代码体量不大，多数都是用cdn引入的，但是打包比较慢（打包机器配置不好），mfsu打包可以加速，但是默认开启dynamicImport，文件太多了。

## Proposal

希望可以增加配置可以手动关闭dynamicImport。

## Additional context

![image](https://user-images.githubusercontent.com/23555154/125030877-605c4580-e0be-11eb-96ed-66c38ef80e4d.png)

**Comment by sorrycc** [comment]
这个做不到，但我们下个 mirror 版本会做 mfsu 的请求和文件的合并。
