### ISSUE TITLE
[Bug] 开启MFSU后 Jenkins编译报错

### ISSUE THREAD

**Issue by baieceo** [umijs/umi#6943]
开启MFSU后本地没问题
用Jenkins编译报错
TypeError: _jestWorker.Worker is not a constructor

`Started by user chenxi
Building in workspace /u01/.jenkins/workspace/test-winter-olympics
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@inside-git.01zhuanche.com:web/winter-olympics.git # timeout=10
Fetching upstream changes from git@inside-git.01zhuanche.com:web/winter-olympics.git
 > git --version # timeout=10
 > git fetch --tags --progress git@inside-git.01zhuanche.com:web/winter-olympics.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/test^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/test^{commit} # timeout=10
Checking out Revision 525afde9883c3d48ce1be8a311ca430cdb256ee1 (refs/remotes/origin/test)
Commit message: "Merge branch 'dev-v1.0.5' into test"
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 525afde9883c3d48ce1be8a311ca430cdb256ee1
 > git rev-list 6f07cfced7851bcfd0886a98e83eba27bbc65e12 # timeout=10
[test-winter-olympics] $ /bin/sh -xe /u01/tomcat-jenkins/temp/jenkins719316951756038161.sh
+ yarn
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ umi g tmp
Done in 6.98s.
+ yarn build
yarn run v1.22.4
$ umi build
拆包
[info] [webpackbar] Compiling Webpack
(node:1971) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors
(node:1971) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
[success] [webpackbar] Webpack: Compiled with some errors in 2.64m
 ERROR  Failed to compile with 122 errors3:53:08 PM

 error  

umi.3130c8a4.js from Terser
TypeError: _jestWorker.Worker is not a constructor
    at getWorker (/u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:51319:9)
    at /u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:51420:41
    at /u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/p-limit/index.js:1:743
    at new Promise (<anonymous>)
    at t (/u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/p-limit/index.js:1:725)
    at i (/u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/p-limit/index.js:1:383)
    at s (/u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/p-limit/index.js:1:440)
    at /u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/p-limit/index.js:1:522
    at new Promise (<anonymous>)
    at u (/u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/p-limit/index.js:1:507)
    at TerserPlugin.optimize (/u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:51356:27)

 error  

layouts__index.3da9ca1e.async.js from Terser
TypeError: _jestWorker.Worker is not a constructor
    at getWorker (/u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:51319:9)
    at /u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:51420:41
    at /u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/p-limit/index.js:1:743
    at new Promise (<anonymous>)
    at t (/u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/p-limit/index.js:1:725)
    at i (/u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/p-limit/index.js:1:383)
    at s (/u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/p-limit/index.js:1:440)
    at /u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/p-limit/index.js:1:522
    at new Promise (<anonymous>)
    at u (/u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/p-limit/index.js:1:507)
    at TerserPlugin.optimize (/u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:51356:27)

 error  

p__403.8f10733f.async.js from Terser
TypeError: _jestWorker.Worker is not a constructor
    at getWorker (/u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:51319:9)
    at /u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:51420:41
    at /u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/p-limit/index.js:1:743
    at new Promise (<anonymous>)
    at t (/u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/p-limit/index.js:1:725)
    at i (/u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/p-limit/index.js:1:383)
    at s (/u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/p-limit/index.js:1:440)
    at /u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/p-limit/index.js:1:522
    at new Promise (<anonymous>)
    at u (/u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/p-limit/index.js:1:507)
    at TerserPlugin.optimize (/u01/.jenkins/workspace/test-winter-olympics/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:51356:27)

 error  ...`

**Comment by sorrycc** [comment]
看这个报错，不开 mfsu 应该也会报错。

**Comment by baieceo** [comment]
> 看这个报错，不开 mfsu 应该也会报错。

不开编译正常

**Comment by baieceo** [comment]
> Hello @baieceo. In order to facilitate location and troubleshooting, we need you to provide a realistic example. Please forking these link [codesandbox umi](https://codesandbox.io/s/umi-2d4js?file=/src/pages/index.tsx) or using `yarn create @umijs/umi-app` to create and upload it to your GitHub repository.
> 
> 你好 @baieceo, 为了方便定位和排查问题，我们需要你提供一个重现实例，请提供一个尽可能精简的链接 [codesandbox umi](https://codesandbox.io/s/umi-2d4js?file=/src/pages/index.tsx) 或使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

webpack开启minimize即可复现

config.merge({
        optimization: {
          minimize: true,
          splitChunks: {
            chunks: 'all',
            minSize: 10000,
            minChunks: 3,
            automaticNameDelimiter: '.',
            cacheGroups: {
              vendor: {
                name: 'vendors',
                test({ resource }) {
                  return /[\\/]node_modules[\\/]/.test(resource);
                },
                priority: 10,
              },
            },
          },
        },
      });

**Comment by sorrycc** [comment]
估计得再配个 webpack5: {} 。

**Comment by baieceo** [comment]
> 估计得再配个 webpack5: {} 。

配了
// https://umijs.org/config/
import { defineConfig } from 'umi';
import defaultSettings from './defaultSettings';
import proxy from './proxy';

const pkg = require('./../package.json');
const path = require('path');

const { NODE_ENV, REACT_APP_ENV } = process.env;

// import eslintFormatter from 'react-dev-utils/eslintFormatter'
// import { findLastKey } from 'lodash';
export default defineConfig({
  hash: true,
  antd: {},
  mfsu: { production: { output: '.mfsu-production' } },
  webpack5: {},
  dva: {
    hmr: true,
  },
  locale: {
    // default zh-CN
    default: 'zh-CN',
    // default true, when it is true, will use `navigator.language` overwrite default
    antd: true,
    baseNavigator: true,
  },
  dynamicImport: {
    loading: '@/components/PageLoading/index',
  },
  targets: {
    ie: 11,
  },
  // umi routes: https://umijs.org/docs/routing
  // Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme: {
    // ...darkTheme,
    'primary-color': defaultSettings.primaryColor,
  },
  // @ts-ignore
  title: false,
  ignoreMomentLocale: true,
  proxy: proxy[REACT_APP_ENV || 'dev'],
  manifest: {
    basePath: '/',
  },
  outputPath: `/${pkg.name}/${pkg.name}`,

  chainWebpack(config, opts) {
    if (process.env.ESLINT === 'true') {
      config.module
        .rule('lint')
        .test(/\.js(x)?$/)
        .pre()
        .exclude.add(/\/node_modules\/|\/\.mui\//)
        .end()
        .include.add(/src/)
        .end()
        .use('eslint')
        .loader(require.resolve('eslint-loader'));
      // .options({
      //     formatter: eslintFormatter,
      //     baseConfig: {
      //       extends: [require.resolve('eslint-config-umi')],
      //     },
      //     ignore: false,
      //     eslintPath: require.resolve('eslint'),
      //     useEslintrc: false,
      // });
    }

    if (NODE_ENV === 'production') {
      console.log('拆包');

      config.merge({
        optimization: {
          minimize: true,
          splitChunks: {
            chunks: 'all',
            minSize: 10000,
            minChunks: 3,
            automaticNameDelimiter: '.',
            cacheGroups: {
              vendor: {
                name: 'vendors',
                test({ resource }) {
                  return /[\\/]node_modules[\\/]/.test(resource);
                },
                priority: 10,
              },
            },
          },
        },
      });
    }
  },
  externals: {
    AMap: 'window.AMap',
    AMapUI: 'window.AMapUI',
  },
});

**Comment by sorrycc** [comment]
看不出问题了，没有复现步骤我没法排查。

**Comment by 303394539** [comment]
如果node_modules和jenkins的一致的话，你本地都可以复现，不太可能出现安装包与环境一致，执行出不一致的结果。
1、如果本地复现不了肯定就是环境问题了，jenkins删了node_modules重新装一下也许可以解决。不然就把jenkins的node_modules的具体文件拿到本地来复现检查。
2、如果本地可以复现了，沿着提示在node_modules里面找到执行文件查这个_jestWorker.Worker或者其他问题到底是什么，基本也可以确定是不是安装到node_modules的相应库的具体版本问题了，怎么都可以找到不一致报错的原因。

**Comment by baieceo** [comment]
> _jestWorker.Worker

不是Jenkins的问题，是webpack开启minimize后压缩报错，Terser这个模块导致的。

**Comment by baieceo** [comment]
> 如果node_modules和jenkins的一致的话，你本地都可以复现，不太可能出现安装包与环境一致，执行出不一致的结果。
> 1、如果本地复现不了肯定就是环境问题了，jenkins删了node_modules重新装一下也许可以解决。不然就把jenkins的node_modules的具体文件拿到本地来复现检查。
> 2、如果本地可以复现了，沿着提示在node_modules里面找到执行文件查这个_jestWorker.Worker或者其他问题到底是什么，基本也可以确定是不是安装到node_modules的相应库的具体版本问题了，怎么都可以找到不一致报错的原因。

不是Jenkins的问题，是webpack开启minimize后压缩报错，Terser这个模块导致的。

**Comment by baieceo** [comment]
> 看不出问题了，没有复现步骤我没法排查。

本地也有问题，只要开启minimize这个就会报错

**Comment by leftstick** [comment]
我有一个不成熟的建议，不知道当不当讲，算了，我说吧，『尽量不要配置自定义的 optimization』

**Comment by baieceo** [comment]
> 我有一个不成熟的建议，不知道当不当讲，算了，我说吧，『尽量不要配置自定义的 optimization』

optimization需要配，包太大了，加载慢，需要拆，暂时把minimize关了

**Comment by 303394539** [comment]
拆包并不需要配置minimize，适当配置optimization.splitChunks就可以了
