### ISSUE TITLE
[Bug] 路由扩展属性不支持ts类

### ISSUE THREAD

**Issue by Nokecy** [umijs/umi#6949]
https://github.com/Nokecy/TestUmi.git

```
export class Users {
  public static Default: string = 'Identity.Users';
}

function HomePage() {
  return <h1>Home Page</h1>;
}

HomePage.title = Users.Default;

export default HomePage;

```

**Comment by leftstick** [comment]
你是说这句话不工作对吧

`HomePage.title = Users.Default;`

我印象里这是个limitation，这里赋值只能是静态的值，不能是变量引用。没记错的话，扩展属性的解析处理是在编译的时候，不太容易做到复杂的引用变量分析。

**Comment by Nokecy** [comment]
那这算使用方式不对吗

**Comment by leftstick** [comment]
@Nokecy 嗯，是这个样子。目前支持的扩展属性只能是直接赋值，不能是引用。

源码在此
https://github.com/umijs/umi/blob/master/packages/ast/src/getExportProps/getExportProps.ts#L30
