### ISSUE TITLE
[Bug] 升级后vendors.css如何配置

### ISSUE THREAD

**Issue by phoema** [umijs/umi#6950]
v3.5.7
在根据说明文档配置后
https://umijs.org/config#chunks
  chunks: ['vendors', 'umi'],
  chainWebpack: function (config, { webpack }) {
    config.merge({
      optimization: {
        splitChunks: {
          chunks: 'all',
          minSize: 30000,
          minChunks: 3,
          automaticNameDelimiter: '.',
          cacheGroups: {
            vendor: {
              name: 'vendors',
              test({ resource }) {
                return /[\\/]node_modules[\\/]/.test(resource);
              },
              priority: 10,
            },
          },
        },
      },
    });
  },

之前的某个版本（具体不清楚了）我可以打包成如下文件：
![image](https://user-images.githubusercontent.com/8730272/125158711-76910100-e1a5-11eb-98ba-779349e97848.png)

现在新版本打包结果如下
![image](https://user-images.githubusercontent.com/8730272/125158744-afc97100-e1a5-11eb-82c3-1703c8707c1a.png)

请问，该如何配置才能出来之前的vendors.ac918fa2.chunk.css文件

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
帮忙排查是 umi 哪个小版本开始的？

**Comment by phoema** [comment]
我试了几个版本，可能之前描述的不准确，目前来看
可能出在webpack5对配置文件的兼容性上

在webpack5配置未打开时，我为了能够打包出vendor.css
在splitChunks属性中增加了name: 'vendors',
  chunks: ['vendors', 'umi'],
  chainWebpack: function (config, { webpack }) {
    config.merge({
      optimization: {
        splitChunks: {
          chunks: 'all',
          name: 'vendors',
          minSize: 30000,
          minChunks: 3,
          automaticNameDelimiter: '.',
          cacheGroups: {
            vendor: {
              // name: 'vendors',
              test({ resource }) {
                return /[\\/]node_modules[\\/]/.test(resource);
              },
              priority: 10,
            },
          },
        },
      },
    });
  },

在升级了3.5.*之后，我开启了webpack5，这个属性不支持了，只好配置文件取消了这个属性，
回退到3.4.*，没有这个属性，直接内存溢出
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
有这个属性，可以打包出vendor.css

请问在开启webpack5后，如何打包vendor.css
其他朋友有这个现象吗？

**Comment by skyblue** [comment]
File                          Size                  Gzipped

 dist/vendors.3742ec01.js      2.0 MB                617.6 KB
 dist/umi.4e07286c.js          175.1 KB              43.1 KB
 **dist/844.9c08db72.css         453.2 KB              57.9 KB**
 dist/umi.7e9672ef.css         4.8 KB                1.6 KB

使用webpack5之前的配置 生成的css多出了844这个文件，内容应该是node_modules下的所有样式，
在index.html也没有被引入
