### ISSUE TITLE
@xiaohuoni  可以邀请进群吗

### ISSUE THREAD

**Issue by Loomark** [umijs/umi#6953]
@xiaohuoni 

1. 不要出现 require 等 cjs 写法
2. 依赖了包注意声明依赖

_Originally posted by @sorrycc in https://github.com/umijs/umi/issues/6766#issuecomment-866651860_

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi#feedback
关注公众号-云谦（微信号yunqianorz），回复 umi
