### ISSUE TITLE
[Bug] 基于umi3.5+qiankun的项目，开启mfsu后，slave应用无法加载remoteEntry

### ISSUE THREAD

**Issue by Tan90Qian** [umijs/umi#6961]
## What happens?

使用umi3.5+qiankun+@umijs/plugin-qiankun构建了一个微前端项目，在对umi源码进行一定调整后，master应用可以成功开启mfsu功能并在运行时正常加载。但slave应用错误的加载了master应用的remoteEntry，导致运行时无法完成初始化。

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

repo地址：https://github.com/Tan90Qian/qiankun-mfsu

## How To Reproduce

**Steps to reproduce the behavior:** 
1. 通过`yarn`安装master与slave应用的依赖
2. `cd umi && yarn && yarn build`安装umi的依赖并进行构建
3.  `cd umi/packages/preset-built-in && yarn link`和`cd umi/packages/babel-plugin-import-to-await-require && yarn link`创建symlink
4. `yarn link "@umijs/babel-plugin-import-to-await-require"`在root下建立symlink
5. `cd node_modules/umi && yarn link "@umijs/preset-built-in" `在umi下建立symlink
6. yarn start将master与slave应用启动
7. 打开浏览器

**Expected behavior** 1. master应用正常渲染 2. slave应用正常渲染

![image](https://user-images.githubusercontent.com/20704473/125251896-60f91400-e32a-11eb-8219-bab4a8076b0c.png)
![image](https://user-images.githubusercontent.com/20704473/125251931-68202200-e32a-11eb-8ac8-8898400524c4.png)

## Context

- **Umi Version**:3.5+
- **Node Version**:12+
- **Platform**:macOS

**Comment by sorrycc** [comment]
参考 https://github.com/umijs/umi/issues/6831#issuecomment-872684431，除了 sandbox 应该没有问题，另外给复现步骤不要用 link 的方式。

**Comment by Tan90Qian** [comment]
关闭sandbox配置，运行时仍然报错。
感觉是html entry的引入方式，导致slave应用的umi.js在被master应用引入后，已经改成以master应用的路径去执行后续逻辑了，但静态的remoteEntry文件其实还是得以原端口路径去获取。
或许较为原始的iframe微前端方案反而不会产生这个问题？

**Comment by Tan90Qian** [comment]
用link的原因是项目用了monorepo的形式。现在的mfsu实现还不支持这种方式，会在检索依赖版本的时候抛异常。我改了一部分检索形式，并且加了一些逻辑来剔除monorepo下的本地模块防止意外的缓存。这样才让master应用能运行时跑通（虽然调整的逻辑里面还是有些问题）。

**Comment by GreatAuk** [comment]
@Tan90Qian 问下，所有的子应用如果用 monorepo 的方式组织， 各个子应用的公共依赖被提升到根目录的 `node_modules`, 那么各个应用的依赖版本应该都是统一的。如果我今天有一个项目是用 umi 2.0 创建的，过几天后，我想用 umi 3 创建一个项目，是不是意味着我也要更新之前使用 umi 创建的项目，这就不符合微前端的『技术栈无关』原则吧，更新 B 项目，我必要把 A 项目也更新
