### ISSUE TITLE
[Bug] 配置mfsu 后 国际化失效 并且删除mfsu 导致webpack 报错

### ISSUE THREAD

**Issue by wbyuhan** [umijs/umi#6963]
## 配置mfsu 后 国际化失效
 <img width="494" alt="截屏2021-07-12 下午5 10 01" src="https://user-images.githubusercontent.com/40864785/125261622-006ed480-e334-11eb-8b3e-16c13b7da940.png">
### 按照步骤：
<img width="1148" alt="截屏2021-07-12 下午5 19 40" src="https://user-images.githubusercontent.com/40864785/125263140-5abc6500-e335-11eb-8f97-56b3178faa7a.png">

### 然后安装依赖，删除src/.umi
<img width="1188" alt="截屏2021-07-12 下午5 03 30" src="https://user-images.githubusercontent.com/40864785/125260623-192aba80-e333-11eb-9a9c-0d60cd703286.png">
<img width="1181" alt="截屏2021-07-12 下午5 03 51" src="https://user-images.githubusercontent.com/40864785/125260665-234cb900-e333-11eb-9a8c-b669a0a1e74a.png">
启动成功，进入页面，打开控制台
<img width="1495" alt="截屏2021-07-12 下午5 04 41" src="https://user-images.githubusercontent.com/40864785/125260784-41b2b480-e333-11eb-8d39-7d6479988a82.png">
###  package.json如下：
<img width="568" alt="截屏2021-07-12 下午5 17 39" src="https://user-images.githubusercontent.com/40864785/125262820-1204ac00-e335-11eb-96ec-2a6fedd37929.png">

使用的是ant-design-v5 为基础模版

## 第二个问题：恢复到原来的状态
删除msfu 配置,um恢复为3.4.0
<img width="842" alt="截屏2021-07-12 下午5 10 39" src="https://user-images.githubusercontent.com/40864785/125261691-17152b80-e334-11eb-8d54-ae774145cf00.png">
<img width="531" alt="截屏2021-07-12 下午5 10 58" src="https://user-images.githubusercontent.com/40864785/125261732-21cfc080-e334-11eb-8523-d8ad04042b59.png">
### 重装依赖
<img width="1022" alt="截屏2021-07-12 下午5 13 12" src="https://user-images.githubusercontent.com/40864785/125262080-72dfb480-e334-11eb-909c-4b3f4fb7ecaa.png">

执行yarn start
出现如下情况：webpack报错
<img width="1195" alt="截屏2021-07-12 下午5 12 26" src="https://user-images.githubusercontent.com/40864785/125261971-58a5d680-e334-11eb-8802-db72ebab71b1.png">

<img width="1078" alt="截屏2021-07-12 下午5 25 27" src="https://user-images.githubusercontent.com/40864785/125264115-28f7ce00-e336-11eb-808f-485587cad35f.png">

**Comment by sorrycc** [comment]
已线下沟通， config.dev.ts 里删除 webpack5: {} 解决。
