### ISSUE TITLE
umi开启mfsu第三方库require方式未覆盖导致无法使用

### ISSUE THREAD

**Issue by junyingyi** [umijs/umi#6966]
require引用第三方无法使用
![image](https://user-images.githubusercontent.com/45717189/125403240-e393d900-e3e7-11eb-971e-7ea08b645726.png)
![image](https://user-images.githubusercontent.com/45717189/125402915-813ad880-e3e7-11eb-959a-eba93fb5937f.png)
![image](https://user-images.githubusercontent.com/45717189/125403140-be9f6600-e3e7-11eb-832f-2272eba7040f.png)

**Comment by afc163** [comment]
请提供复现。

**Comment by junyingyi** [comment]
改写成import方式也无法找到
![image](https://user-images.githubusercontent.com/45717189/125404493-40dc5a00-e3e9-11eb-9fa9-b4a1bc99afed.png)
![image](https://user-images.githubusercontent.com/45717189/125404536-4df94900-e3e9-11eb-894d-0b3db43d406d.png)
