### ISSUE TITLE
[Bug] 启用 mfsu production 模式构建打包后页面报错

### ISSUE THREAD

**Issue by wzc0x0** [umijs/umi#6967]
- **Umi Version**: 3.5.8
- **Node Version**: v12.19.0
- **Platform**: Windows 10

> 启用 mfsu production 模式时，建议在本地环境将预编译过程完成，并将产物同步到 git，这样在服务器部署的速度将会得到约 30 倍 的提升！

1. 启用并提交git
2. 构建机器Linux环境打包正常
3. 打开页面报错如下：

```js 
Uncaught (in promise) Error: Module "./$CWD$/node_modules/@umijs/preset-built-in/node_modules/@umijs/runtime" does not exist in container.
while loading "./$CWD$/node_modules/@umijs/preset-built-in/node_modules/@umijs/runtime" from 6326
    at mf-va_remoteEntry.js:3
```

**Comment by yinbaoqiang** [comment]
- Umi Version: 3.5.17
- Node Version: v14.15.3
- Platform: Ubuntu 20.04 LTS

我也遇到了这个问题，之前使用  react16没有问题，升级到react17 不使用 mfsu 没有问题，使用mfsu后报一样的错误
