### ISSUE TITLE
[Bug] 项目启用 mfsu, 命令行不报错 项目启动页面报错

### ISSUE THREAD

**Issue by FengXiaoLin123** [umijs/umi#6971]
项目启用 mfsu一直卡在99%，命令行不报错， 项目启动页面报错
已经按照 https://github.com/umijs/umi/issues/6766 操作试过多次 仍然报错
项目配置： 
![image](https://user-images.githubusercontent.com/30145621/125439602-4285fb8b-dbe0-46b0-b3f8-537a053465fe.png)

页面报错：
![image](https://user-images.githubusercontent.com/30145621/125439386-3b2a5874-c655-4e85-9c9a-48dc07555cdd.png)

## Context

- **Umi Version**: 3.5.0
- **Node Version**: 14.15.4
- **Platform**: antd

**Comment by sorrycc** [comment]
需要给复现步骤。
