### ISSUE TITLE
升级到 umi3 之后 access 未生效

### ISSUE THREAD

**Issue by YingJiangHui** [umijs/umi#6982]
## What happens?

我将公司项目从umi2升级到umi3后发现路由配置中的access没有生效。

**调试中发现的问题**:
src\\.umi\plugin-access\AccessProvider.ts 中的 `traverseModifyRoutes(props.routes, access)` 执行返回的结果确实对路由添加了unaccessible属性(我创建了一个测试组件用AccessProvider组件包裹子组件，打印出子组件的props，实测有效)，但是我将src\\.umi\plugin-layout\Layout.tsx中的`props.route`打印出来却发现没有unaccessible属性(Layout没有用到修改后的路由)。
相对的在其他的项目测试中使用相同的步骤打印Layout的`props.route`的结果是存在unaccessible属性的。

然后我查看了access-plugin@v2.3.2中生成的src\\.umi\plugin-access\AccessProvider.ts 的代码与我当前项目中使用的access-plugin@v2.4.2进行了对比，并加上了红框中的那行代码（红框中的代码是我从2.3.2复制到2.4.2的），添加了代码之后权限控制就生效了。
![image](https://user-images.githubusercontent.com/46065657/125419644-ba475d6f-b114-49dd-8792-bb8980aef2ba.png)

我认为这是两种写法是不同的，估计是某些依赖的版本不支持access-plugin@2.4.2这种写法？我也将大部分有关umijs的依赖和都升级了。但是还是没能解决...也试过删除node_modules和yarn.lock重新install。

**我还能做什么**：
1. 将access-plugin回退到之前的版本如2.3.2，使用旧版本的access-plugin吗。但是我该如何在umi安装的时候控制@umijs/plugin-access的版本。
2. 依赖和配置还是存在问题吗。

## Mini Showcase Repository(REQUIRED)

**Repository**: https://github.com/YingJiangHui/invalid-access-demo
## How To Reproduce
**Steps to reproduce the behavior:**
1. yarn;yarn start
2. 进入页面
3. 点击管理员路由

**Expected behavior**:
1. 403无权限
## Context

- **Umi Version**: ^3.5.8
- **Node Version**: v14.17.1
- **Platform**: win10家庭

**Comment by z384647062** [comment]
我也遇到同样的问题

**Comment by z384647062** [comment]
> 我也遇到同样的问题

解决了，我是由于自定义了rootContainer，写法错误导致的

**Comment by YingJiangHui** [comment]
> > 我也遇到同样的问题
> 
> 解决了，我是由于自定义了rootContainer，写法错误导致的

我当时用wrappers属性手动做了权限控制暂时应付了。我最后在清理代码的时候也把rootContainer去除了，回头把wrappers方案去掉看看效果

**Comment by YingJiangHui** [comment]
> > 我也遇到同样的问题
> 
> 解决了，我是由于自定义了rootContainer，写法错误导致的

权限确实生效了，但是menu导航Link

**Comment by beatlesD** [comment]
大佬你好，请问这个问题如何解决，你们写的我没看懂。。。

**Comment by YingJiangHui** [comment]
app.tsx 里的 rootContainer 去掉就好了

**Comment by beatlesD** [comment]
> app.tsx 里的 rootContainer 去掉就好了

但是我在app.ts里面压根没有加rootcontainer啊

**Comment by beatlesD** [comment]
> app.tsx 里的 rootContainer 去掉就好了

所以我改了access插件的文件，但是那个保存不了，也提交不了啊，哭了。。或者说可以降access插件的版本么，到2.3.2

**Comment by zhaofang** [comment]
同样的问题，怎么没有解决方案呢

**Comment by laozhu** [comment]
官方都不解决，access 和 rootContainer 冲突。

**Comment by skyblue** [comment]
> app.tsx 里的 rootContainer 去掉就好了

并没有用到这个东西啊

**Comment by YingJiangHui** [comment]
解决步骤：
1. 删除rootContainer
2. 升级@ant-design/pro-layout（如果出现antd版本问题可能还需要升级antd）

**Comment by raotaohub** [comment]
> 解决步骤：
> 
> 1. 删除rootContainer
> 2. 升级@ant-design/pro-layout（如果出现antd版本问题可能还需要升级antd）

3.5 版本 目前依旧有这个问题
