### ISSUE TITLE
[Bug] 修改antd的dark主题后, 使用mfsu导致页面颜色错乱, 注释掉mfsu又变正常

### ISSUE THREAD

**Issue by jinhgg** [umijs/umi#6986]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
修改 theme 后强刷下试试。

**Comment by leftstick** [comment]
我这也有这个问题，貌似是开启`mfsu`之后一些css的加载顺序变了，导致个别样式的覆盖逻辑不正常了。

我也懒得研究，就直接找到不正常的样式，加`!important`让它脱离css加载顺序的束缚

**Comment by jinhgg** [comment]
过段时间自动变正常了

**Comment by zhouwenwu30** [comment]
极有可能是在项目组件中引入了antd.css，引入后编译的时候会把antd.css整个编译一遍，这里面全是默认颜色，这样会导致自定义的主题色被覆盖。
`import 'antd/dist/antd.css';`
