### ISSUE TITLE
[Bug] umi 中找不到 MicroAppWithMemoHistory 

### ISSUE THREAD

**Issue by topwood** [umijs/umi#6989]
## What happens?

umi 中找不到 MicroAppWithMemoHistory

umi版本： 3.5.8
![image](https://user-images.githubusercontent.com/13791267/125582621-6c47fc85-c90b-49b9-abea-cf68d1b68a34.png)

## Mini Showcase Repository(REQUIRED)

见以上截图

## How To Reproduce

直接使用最新的umi，尝试

import { MicroAppWithMemoHistory } from 'umi';

## Context

- **Umi Version**: 3.5.8
- **Node Version**:  12.x
- **Platform**: mac os

**Comment by hbxks18** [comment]
+1

**Comment by hbxks18** [comment]
> +1

解决。
我这边配置文件写到config/config.js里之后就导出MicroAppWithMemoHistory。
![image](https://user-images.githubusercontent.com/23228604/128657936-c49a4280-7fe3-48b6-a994-5e75f49f6021.png)
