### ISSUE TITLE
[Bug] 修改内容打包，出现99%进度条，显示是webpack的进度，其实已经成功

### ISSUE THREAD

**Issue by wangyuan0108** [umijs/umi#6991]
![image](https://user-images.githubusercontent.com/22407253/125599563-0ecc6690-bbd9-42ef-be42-6ba30d49c1aa.png)

**Comment by wangyuan0108** [comment]
版本是v3.5.9

**Comment by xiefengnian** [comment]
试试 3.5.10

**Comment by wangyuan0108** [comment]
@xiefengnian 好的

**Comment by wangyuan0108** [comment]
3.5.10依然是这个样子

**Comment by zeekrs** [comment]
3.5.18 也不行啊...
