### ISSUE TITLE
[Bug] 开启mfsu时使用echarts-for-react报错

### ISSUE THREAD

**Issue by BoWang816** [umijs/umi#6993]
## What happens?

在config.ts中配置了mfsu，但是如果使用到echarts-for-react，则直接报错，关闭mfsu则可正常使用

错误提示：
`devScripts.js:6523 [@umijs/runtime] load component failed Error: Module "./echarts-for-react" does not exist in container.
while loading "./echarts-for-react" from webpack/container/reference/mf`

![image](https://user-images.githubusercontent.com/26587649/125719561-a62c370f-a46d-43a3-b54f-fd3b3b50f3eb.png)

![image](https://user-images.githubusercontent.com/26587649/125719586-8da160ab-28e5-475a-9be0-b8a1c7de1d06.png)

![image](https://user-images.githubusercontent.com/26587649/125719612-d7305863-50f5-4b91-a0df-eab044f2b470.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiefengnian** [comment]
删掉 .umi 重试一下

**Comment by EricWong1994** [comment]
> 

niubi，but why?
