### ISSUE TITLE
[Bug] 动态 import 在 webpack5 下编译时报错，而且会报在 src/pages/document.ejs 上

### ISSUE THREAD

**Issue by Aliveing** [umijs/umi#6994]
## What happens?
动态 import 在 webpack5 下编译时报错，而且会报在 document.ejs 上

### 问题描述
使用 `yarn create umi` 创建了 [复现工程](https://github.com/Aliveing/umi-webpack5-bug)，在其中写了一个自定义 layout 用于将访问的路由以 tab 的展现，为了保存页面状态使用了动态 import 生成 dom 实例存储在对象中，这种写法在 webpack5 下编译报错，虽然报错报在  `src/pages/document.ejs` 上，但是经过工程文件逐个对比最终问题锁定在 [动态 import](https://github.com/Aliveing/umi-webpack5-bug/blob/main/src/utils/route-elements.tsx#L45) 中，报错截图如下图，报错后运行 `rm -rf ./src/.umi` 后再次编译会一直卡在 99%。
![image](https://user-images.githubusercontent.com/11768879/125720584-2c364c11-00a4-4ea0-b87f-80d47c8c802a.png)

### 问题现象
将 [动态 import](https://github.com/Aliveing/umi-webpack5-bug/blob/main/src/utils/route-elements.tsx#L45) 与 [下方return](https://github.com/Aliveing/umi-webpack5-bug/blob/main/src/utils/route-elements.tsx#L54) 注释掉就可以编译就通过

or

注释掉 `config/config.ts` 中的 `mfsu: {}` 以及 `webpack5: {}` 可以编译通过

## Mini Showcase Repository(REQUIRED)

[复现工程](https://github.com/Aliveing/umi-webpack5-bug)

## How To Reproduce

**Steps to reproduce the behavior:**
1. `git clone https://github.com/Aliveing/umi-webpack5-bug`
2. `yarn install`
3. `npm start`

**Expected behavior**
1. 希望报错定位准确，不是报在 ` src/pages/document.ejs` 上
2. 希望能解决 webpack5 下的编译问题

## Context

- **Umi Version**: 3.5.10
- **Node Version**: 16.4.1
- **Platform**: 7.18.1

**Comment by hyzx86** [comment]
我有个相同问题。。动态创建路由的时候也会这样 

https://github.com/ant-design/ant-design-pro/issues/9920

**Comment by xiahller** [comment]
> 我有个相同问题。。动态创建路由的时候也会这样
> 
> [ant-design/ant-design-pro#9920](https://github.com/ant-design/ant-design-pro/issues/9920)
蹲

**Comment by hyzx86** [comment]
> > 我有个相同问题。。动态创建路由的时候也会这样
> > [ant-design/ant-design-pro#9920](https://github.com/ant-design/ant-design-pro/issues/9920)
> > 蹲

一起来尝试啊。。
