### ISSUE TITLE
[Bug] 打开 mfsu 后，浏览器控制台会出现找不到 *.map 的警告

### ISSUE THREAD

**Issue by moonou** [umijs/umi#6996]
## What happens?

![image](https://user-images.githubusercontent.com/6938877/125734921-3082f506-4695-445d-929d-e4ca0412c269.png)
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/moonou/report_umi_issue
## How To Reproduce

**Steps to reproduce the behavior:**
1. 打开 msfu
2. 在启动页面中打开控制台

**Expected behavior** 
1. 在控制台中无 map 丢失的警告

## Context

- **Umi Version**: 3.5.10
- **Node Version**: 14.15.0
- **Platform**: macOS

**Comment by zzx0106** [comment]
确实有这个问题，下载的ant-design-pro v5也存在这个问题。

**Comment by wangyuan0108** [comment]
我也有这个问题，不知是不是打开msfu的原因

**Comment by 7kms** [comment]
应该是由于`sourceMap`的相[绝]对路径造成的,  这种情况的话,  不启动mfsu也会有问题.

**Comment by moonou** [comment]
> 应该是由于`sourceMap`的相[绝]对路径造成的, 这种情况的话, 不启动mfsu也会有问题.

目前在我提供的例子仓库里面，如果关掉msfu是可以正常使用map的，不会出现警告。

**Comment by sorrycc** [comment]
已知问题。

**Comment by handycode** [comment]
一样的问题

**Comment by Surprise-ling** [comment]
一样的问题，解决了吗

**Comment by baibaibai455** [comment]
现在还有这个问题，解决了么？  关闭mfsu之后就可以了，打印也能正确跳转，不然就是下面这样
![image](https://user-images.githubusercontent.com/47173675/132938703-757a6892-993e-418e-83e4-d5445b5d667d.png)
![image](https://user-images.githubusercontent.com/47173675/132938710-90d1d141-0b46-49f7-9ee2-62524494cd23.png)

**Comment by Surprise-ling** [comment]
> 现在还有这个问题，解决了么？ 关闭mfsu之后就可以了，打印也能正确跳转，不然就是下面这样
> ![image](https://user-images.githubusercontent.com/47173675/132938703-757a6892-993e-418e-83e4-d5445b5d667d.png)
> ![image](https://user-images.githubusercontent.com/47173675/132938710-90d1d141-0b46-49f7-9ee2-62524494cd23.png)
> 
> 好像关闭了浏览器插件 React Developer Tools
> 就可用了
> 虽然还是有警告
> 但是可跳转了

关闭了react developer tools，可以定位到准确位置

**Comment by YiField** [comment]
这个问题解决了嘛 发现修改代码后没办法自动更新了（不加mfsu正常热更新），一直报错这个。
而且启动时间和热更新时间还是很慢 
![image](https://user-images.githubusercontent.com/29118425/220301160-b6174bde-75ad-4112-8931-a0418c75d97e.png)

**Comment by qq34347476** [comment]
这是你们浏览器设置的有问题,setting =>  perferences 里面  enable tab moves focus 和 enable css source maps 去掉勾选就行了

**Comment by YiField** [comment]
确实没有报错了,控制台答应不能正常映射到代码。而且不会热更新。

**Comment by zjp123** [comment]
这个问题没有解决啊，为啥关掉啊 @sorrycc

**Comment by simplast** [comment]
+1
