### ISSUE TITLE
[Bug] MFSU模式下通过import * as moment from 'moment'方式引入moment报moment is not a function错误

### ISSUE THREAD

**Issue by baieceo** [umijs/umi#6997]
### 开启mfsu模式后
`import * as moment from 'moment'`

### 报错
![image](https://user-images.githubusercontent.com/19337357/125750247-db72d174-4b7f-4a8e-bd2f-83aad6b31e94.png)

### 完整报错信息
`mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:5221 Uncaught (in promise) Error: Error: TypeError: moment is not a function
    at _callee$ (mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:5221)
    at tryCatch (mf-dep_vendors-node_modules_umijs_preset-built-in_node_modules_regenerator-runtime_runtime_js.4032ed9c.async.js:53)
    at Generator.invoke [as _invoke] (mf-dep_vendors-node_modules_umijs_preset-built-in_node_modules_regenerator-runtime_runtime_js.4032ed9c.async.js:273)
    at Generator.prototype.<computed> [as throw] (mf-dep_vendors-node_modules_umijs_preset-built-in_node_modules_regenerator-runtime_runtime_js.4032ed9c.async.js:106)
    at asyncGeneratorStep (mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:4881)
    at _throw (mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:4907)
_callee$ @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:5221
tryCatch @ mf-dep_vendors-node_modules_umijs_preset-built-in_node_modules_regenerator-runtime_runtime_js.4032ed9c.async.js:53
invoke @ mf-dep_vendors-node_modules_umijs_preset-built-in_node_modules_regenerator-runtime_runtime_js.4032ed9c.async.js:273
prototype.<computed> @ mf-dep_vendors-node_modules_umijs_preset-built-in_node_modules_regenerator-runtime_runtime_js.4032ed9c.async.js:106
asyncGeneratorStep @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:4881
_throw @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:4907
Promise.then (async)
asyncGeneratorStep @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:7292
_next @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:7304
(anonymous) @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:7311
(anonymous) @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:7300
setTimeout (async)
(anonymous) @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:7362
_callee2$ @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:7360
tryCatch @ mf-dep_vendors-node_modules_umijs_preset-built-in_node_modules_regenerator-runtime_runtime_js.4032ed9c.async.js:53
invoke @ mf-dep_vendors-node_modules_umijs_preset-built-in_node_modules_regenerator-runtime_runtime_js.4032ed9c.async.js:273
prototype.<computed> @ mf-dep_vendors-node_modules_umijs_preset-built-in_node_modules_regenerator-runtime_runtime_js.4032ed9c.async.js:106
asyncGeneratorStep @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:7282
_next @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:7304
(anonymous) @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:7311
(anonymous) @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:7300
_callee3$ @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:5368
tryCatch @ mf-dep_vendors-node_modules_umijs_preset-built-in_node_modules_regenerator-runtime_runtime_js.4032ed9c.async.js:53
invoke @ mf-dep_vendors-node_modules_umijs_preset-built-in_node_modules_regenerator-runtime_runtime_js.4032ed9c.async.js:273
prototype.<computed> @ mf-dep_vendors-node_modules_umijs_preset-built-in_node_modules_regenerator-runtime_runtime_js.4032ed9c.async.js:106
asyncGeneratorStep @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:4881
_next @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:4903
(anonymous) @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:4910
(anonymous) @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:4899
reload @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:5379
_callee$ @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:6389
tryCatch @ mf-dep_vendors-node_modules_umijs_preset-built-in_node_modules_regenerator-runtime_runtime_js.4032ed9c.async.js:53
invoke @ mf-dep_vendors-node_modules_umijs_preset-built-in_node_modules_regenerator-runtime_runtime_js.4032ed9c.async.js:273
prototype.<computed> @ mf-dep_vendors-node_modules_umijs_preset-built-in_node_modules_regenerator-runtime_runtime_js.4032ed9c.async.js:106
asyncGeneratorStep @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:6206
_next @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:6228
(anonymous) @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:6235
(anonymous) @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:6224
reload @ mf-dep_vendors-node_modules_ant-design_pro-table_es_index_js-node_modules_antd_es_alert_style_index_-388ceb.80ff4c71.async.js:6400
(anonymous) @ index.jsx:29
commitHookEffectListMount @ mf-dep_vendors-node_modules_react-dom_index_js.a69c7b5a.async.js:20996
commitPassiveHookEffects @ mf-dep_vendors-node_modules_react-dom_index_js.a69c7b5a.async.js:21034
callCallback @ mf-dep_vendors-node_modules_react-dom_index_js.a69c7b5a.async.js:1453
invokeGuardedCallbackDev @ mf-dep_vendors-node_modules_react-dom_index_js.a69c7b5a.async.js:1502
invokeGuardedCallback @ mf-dep_vendors-node_modules_react-dom_index_js.a69c7b5a.async.js:1557
flushPassiveEffectsImpl @ mf-dep_vendors-node_modules_react-dom_index_js.a69c7b5a.async.js:24118
unstable_runWithPriority @ mf-dep_vendors-node_modules_react-dom_index_js.a69c7b5a.async.js:1025
runWithPriority$1 @ mf-dep_vendors-node_modules_react-dom_index_js.a69c7b5a.async.js:12304
flushPassiveEffects @ mf-dep_vendors-node_modules_react-dom_index_js.a69c7b5a.async.js:24085
(anonymous) @ mf-dep_vendors-node_modules_react-dom_index_js.a69c7b5a.async.js:23964
workLoop @ mf-dep_vendors-node_modules_react-dom_index_js.a69c7b5a.async.js:969
flushWork @ mf-dep_vendors-node_modules_react-dom_index_js.a69c7b5a.async.js:925
performWorkUntilDeadline @ mf-dep_vendors-node_modules_react-dom_index_js.a69c7b5a.async.js:528
Show 21 more frames`

**Comment by leftstick** [comment]
改成这样写呢？

```ts
import  moment from 'moment'
```

**Comment by baieceo** [comment]
> 改成这样写呢？
> 
> ```ts
> import  moment from 'moment'
> ```

直接import没问题，就是不太明白为什么as方式不行

**Comment by leftstick** [comment]
@baieceo 那可能不是bug，而是这个事：

https://www.typescriptlang.org/tsconfig#esModuleInterop

**Comment by baieceo** [comment]
> @baieceo 那可能不是bug，而是这个事：
> 
> https://www.typescriptlang.org/tsconfig#esModuleInterop

确实是，改成moment.default()调用就可以了
