### ISSUE TITLE
[Bug] 开启MFSU模式less文件通过background: url('~@/assets/login-bg.jpg')，webpack-dev-server下报404

### ISSUE THREAD

**Issue by baieceo** [umijs/umi#6998]
### style.less
![image](https://user-images.githubusercontent.com/19337357/125749954-aa9a1ac3-f03f-4211-97fb-5f6d0d07fc61.png)

### 网络请求报404
![image](https://user-images.githubusercontent.com/19337357/125749798-14ec5e66-d855-48ba-ab99-64d9caa280c4.png)

### config.js
![image](https://user-images.githubusercontent.com/19337357/125750039-b1e576e5-e5fb-4159-beaf-b772b1b5979f.png)

**Comment by sorrycc** [comment]
试了下，不能复现，需要给复现。

**Comment by guojunhao118** [comment]
我也遇到了这个问题，关闭MFSU图片正常显示，但是codesandbox 没有复现，很奇怪

**Comment by hocko333** [comment]
+1

**Comment by lincong1498** [comment]
+1
