### ISSUE TITLE
关于环境变量的建议

### ISSUE THREAD

**Issue by amily4555** [umijs/umi#700]
比如 

BROWSER，默认为打开，值为 'none' 的时候关闭

TS_CONFIG_PATHS_PLUGIN 默认为关闭 值为 1 为打开，

于是我设置 BROWSER=1 的时候，以为是打开，but 不生效

所以，是否将这些 开关值 进行统一 

（我将所有的环境变量放在一个文件里进行配置管理，启动的时候调用这个文件，如果没有开关值，有点尴尬，其实可以自己写的值进行判断，但终究不优雅）

**Comment by sorrycc** [comment]
这个应该统一不了，配置就是有些默认开有些默认关的。umi@2 会支持 `.env` 的配置方法。

**Comment by amily4555** [comment]
可能没明白我的意思，默认开和默认关 都可以的
但每个环境变量应该有开关值 比如 BROWSER 它默认是开，
BROWSER='none' 配置时关，但没有配置开的值 BROWSER=1 没有效果

**Comment by amily4555** [comment]
或说 BROWSER=1 与 BROWSER='none' 是一样的结果（关）

这有点不合理
