### ISSUE TITLE
打包产物里有项目绝对路径

### ISSUE THREAD

**Issue by shaoqiwang-fe** [umijs/umi#7000]
辛苦帮忙看下哈

1. https://github.com/shaoqiwang-fe/umi-demo
2. npm i && npm run build
3. 进入到dist文件夹下搜索'umi-demo'
4. 发下注册插件比如locale插件的注册 path包含了项目路径
![image](https://user-images.githubusercontent.com/59658783/125257025-95bb9a00-e32f-11eb-918e-311c3e791abe.png)
5. 这样的问题在开发环境没问题，如果在生产环境会暴露内网域名

**Comment by sorrycc** [comment]
两个地方有问题：

1. app.ts
2. plugin-locale

**Comment by shaoqiwang-fe** [comment]
> 两个地方有问题：
> 
> 1. app.ts
> 2. plugin-locale

请问题有修复预期吗，谢谢

**Comment by zcrun** [comment]
> > 两个地方有问题：
> > 
> > 1. app.ts
> > 2. plugin-locale
> 
> 请问题有修复预期吗，谢谢

依然存在这个问题啊，还没解决嘛？

**Comment by maoxiaodun** [comment]
@sorrycc 

能帮忙修复下这个问题吗，谢谢

**Comment by maoxiaodun** [comment]
> > > 两个地方有问题：
> > > 
> > > 1. app.ts
> > > 2. plugin-locale
> > 
> > 
> > 请问题有修复预期吗，谢谢
> 
> 在文件[preset-built-in/src/plugins/generateFiles/core/pluginRegister.tpl](https://github.com/umijs/umi/blob/master/packages/preset-built-in/src/plugins/generateFiles/core/pluginRegister.tpl#L9)中的`path`字段在实际运行时应该是无用的，但是会暴露项目绝对路径，望修复一下，谢谢！
> 
> @sorrycc

只能写个脚本在build后自动删除项目路径了

**Comment by zcrun** [comment]
> > > > 两个地方有问题：
> > > > 
> > > > 1. app.ts
> > > > 2. plugin-locale
> > > 
> > > 
> > > 请问题有修复预期吗，谢谢
> > 
> > 
> > 在文件[preset-built-in/src/plugins/generateFiles/core/pluginRegister.tpl](https://github.com/umijs/umi/blob/master/packages/preset-built-in/src/plugins/generateFiles/core/pluginRegister.tpl#L9)中的`path`字段在实际运行时应该是无用的，但是会暴露项目绝对路径，望修复一下，谢谢！
> > @sorrycc
> 
> 只能写个脚本在build后自动删除项目路径了

写了个`plugin`移除绝对路径，你可以试下
```
import { IApi } from 'umi';
import { join } from 'path';
import { readFileSync, writeFileSync } from 'fs';

export default function (api: IApi) {
  api.onGenerateFiles(({ stats, type }) => {
    var path = join(api.paths.absTmpPath!, 'core/pluginRegister.ts');
    const data = readFileSync(path, 'utf-8');
    var result = data.replace(/path:.+,/g, "path: 'path',");
    writeFileSync(path, result, 'utf-8');
  });
}
```

**Comment by maoxiaodun** [comment]
> > > > > 两个地方有问题：
> > > > > 
> > > > > 1. app.ts
> > > > > 2. plugin-locale
> > > > 
> > > > 
> > > > 请问题有修复预期吗，谢谢
> > > 
> > > 
> > > 在文件[preset-built-in/src/plugins/generateFiles/core/pluginRegister.tpl](https://github.com/umijs/umi/blob/master/packages/preset-built-in/src/plugins/generateFiles/core/pluginRegister.tpl#L9)中的`path`字段在实际运行时应该是无用的，但是会暴露项目绝对路径，望修复一下，谢谢！
> > > @sorrycc
> > 
> > 
> > 只能写个脚本在build后自动删除项目路径了
> 
> 写了个`plugin`移除绝对路径，你可以试下
> 
> ```
> import { IApi } from 'umi';
> import { join } from 'path';
> import { readFileSync, writeFileSync } from 'fs';
> 
> export default function (api: IApi) {
>   api.onGenerateFiles(({ stats, type }) => {
>     var path = join(api.paths.absTmpPath!, 'core/pluginRegister.ts');
>     const data = readFileSync(path, 'utf-8');
>     var result = data.replace(/path:.+,/g, "path: 'path',");
>     writeFileSync(path, result, 'utf-8');
>   });
> }
> ```

谢谢哈 我自己写了个脚本移除了项目路径，已经解决了

**Comment by tdida** [comment]
同样的问题，期待修复
