### ISSUE TITLE
[Bug] 项目启动后提示 does not exist in container.

### ISSUE THREAD

**Issue by iamzhoufei** [umijs/umi#7001]
遇到的问题：项目启动后，控制台提示错误
![image](https://user-images.githubusercontent.com/81286048/125777826-dce4e116-b99a-4b78-bfbf-c81fccc334ed.png)

复现仓库：https://github.com/iamzhoufei/bug_report
复现步骤：yarn && yarn start:dev

Umi Version：^3.5.11
Node Version：v14.16.1
Platform：macOS Big Sur 11.2.3

**Comment by iamzhoufei** [comment]
在开启 mfsu: {} 后会出现这个问题，关闭之后就不再提示错误

**Comment by iamzhoufei** [comment]
在仅开启 webpack5: {} 时也会出现问题
![image](https://user-images.githubusercontent.com/81286048/125881759-9207ce6f-0107-4536-bc21-162089db957d.png)

**Comment by sorrycc** [comment]
不能复现。

![image](https://user-images.githubusercontent.com/35128/125886659-d3288eaa-0d98-4901-b477-16818dc5904e.png)

**Comment by MachoManCk** [comment]
我也复线了

**Comment by zhaozeq** [comment]
我配置了别名 就正常了 你们可以试试   mfsu: { mfName: 'mfMain' },
