### ISSUE TITLE
[Bug] umi 3.5.0 SSR严重bug

### ISSUE THREAD

**Issue by xuqianjin** [umijs/umi#7002]
umi升级到3.5.0会导致ssr的页面html没有hash值
![image](https://user-images.githubusercontent.com/12406066/125787250-bd60a50f-44fe-4a0f-ab34-cb13d16d9227.png)

```
import { defineConfig } from 'umi';

export default defineConfig({
  routes: [
    {
      path: '/',
      component: '@/layouts',
      routes: [{ path: '/home', component: '@/pages/index' }],
    },
  ],
  ssr: {},
  hash: true,
  fastRefresh: {},
});
```

**Comment by 7kms** [comment]
是开发环境下吗,  开发环境是没有hash的

**Comment by xuqianjin** [comment]
> 是开发环境下吗, 开发环境是没有hash的

生产环境生产环境生产环境

**Comment by 104gogo** [comment]
+1

**Comment by remberi** [comment]
+1 我也遇到了这种问题， 我是3.2.9版本，而且会多出一个umi.server.d.ts文件，但是我本地打包是好的，服务器上打包就会出这种问题，暂时不知道如何解决

**Comment by 7kms** [comment]
升级之后还有问题吗,  现在是3.5.15了

**Comment by 104gogo** [comment]
> +1 我也遇到了这种问题， 我是3.2.9版本，而且会多出一个umi.server.d.ts文件，但是我本地打包是好的，服务器上打包就会出这种问题，暂时不知道如何解决

有2个方法临时方法
1. 拷一份umi.xxxx.js和umi.xxxx.css，然后新增umi.js和umi.css文件
2. 修改umi.server.js里面的htmlTemplate..

**Comment by 104gogo** [comment]
> 升级之后还有问题吗, 现在是3.5.15了

还是一样的问题

**Comment by jxiangji** [comment]
是的！同样的问题！！！昨天遇到搞了好久，换到3.4.x才正常

**Comment by weitangli** [comment]
是的！同样的问题！！！
我使用的是3.5.17

**Comment by royall** [comment]
版本3.5.17，同样的问题。
大佬们都解决了吗

**Comment by FeSeason** [comment]
还没解决吗 ？？？ 都 3.5.20 了还是有同样的问题

**Comment by wotermelon** [comment]
同样的问题！一开始以为是拆包的问题，拆包之后路径也全都是乱的

**Comment by yangsendyx** [comment]
回退版本到3.4.x可以解决ssr无hash的问题

**Comment by WheelerLee** [comment]
都2023年了，还没解决

**Comment by Baoyx007** [comment]
都2024年了，还没解决
