### ISSUE TITLE
开发环境的umi.js很大，是否有办法优化？

### ISSUE THREAD

**Issue by Ryan-Shz** [umijs/umi#7009]
通过yarn start生成的umi.js，达到13+MB，是否有办法可以优化？

![image](https://user-images.githubusercontent.com/12422273/125904034-2a274d31-7398-4d9f-9f77-a0b508de5610.png)

我希望可以通过其他设备来远程加载当前PC上开发环境的资源，以达到快速调试的目的。

**Comment by xiefengnian** [comment]
splitChunks 试一下？
