### ISSUE TITLE
开启mfsu后，部分antd组件报错

### ISSUE THREAD

**Issue by Ryan-Shz** [umijs/umi#7010]
具体的错误如下：
![image](https://user-images.githubusercontent.com/12422273/125904407-9afe3315-1399-4ed3-8d38-6251246a4952.png)
console:
![image](https://user-images.githubusercontent.com/12422273/125904492-7544faf1-8bc8-47c9-b4b4-f7d9a16340fc.png)

关闭mfsu后正常。

**Comment by sorrycc** [comment]
需要给复现步骤。
