### ISSUE TITLE
[Bug] 更新之后导致qiankun插件无法再app.tsx中导出useQiankunStateForSlave

### ISSUE THREAD

**Issue by skyintree** [umijs/umi#7015]
## What happens?

将项目更新到antd pro v5（umi3.5.0）之后出现一个报错。
`Uncaught Error: register failed, invalid key useQiankunStateForSlave from plugin xxx/src/app.tsx.`
看报错信息是乾坤这个umi插件导出 useQiankunStateForSlave 函数错误，这一问题在旧版本（antd pro v4）没有出现。

## Mini Showcase Repository(REQUIRED)

https://github.com/skyintree/bug-someBugForUmi.git

## Context

- **Umi Version**:3.5.0
- **Node Version**:14.16.1

**Comment by skyintree** [comment]
抱歉，是我唐突了，我们在项目中少配置了些东西导致的错误

**Comment by qhanw** [comment]
我也遇到这个问题，能问一下你们是如何解决的吗？

**Comment by qhanw** [comment]
> 抱歉，是我唐突了，我们在项目中少配置了些东西导致的错误


我也遇到这个问题，能问一下你们是如何解决的吗？
