### ISSUE TITLE
[Bug] 在项目中使用import导入本地excel资源时会报错

### ISSUE THREAD

**Issue by Cancerbin** [umijs/umi#7016]
在jsx代码中import tempFile from '@/assets/template.xlsx'时会报错，请问是要使用什么loaders插件进行加载
![image](https://user-images.githubusercontent.com/14088361/126032268-f9f19f49-732e-4261-88db-dcec6a29ab85.png)

**Comment by leftstick** [comment]
取决于你期待的引入效果是什么
