### ISSUE TITLE
只有首屏的内容ssr 首页其余的还是走csr

### ISSUE THREAD

**Issue by Magic-zhu** [umijs/umi#7017]
## Background

不需要整个页面完全ssr 只需要首屏ssr 

## Proposal

只需要首屏ssr  首页其余内容还是走csr

**Comment by williamnie** [comment]
只在首屏写getintl的方法获取数据就好了，其他的别写，或者只给首页路由走node server render，其他的路由都转到原来的部署方式就好了

**Comment by Magic-zhu** [comment]
我的意思是  一个页面很长 可能有两个屏幕高度+  但是只有首屏ssr 下面的还是走csr 首屏!==首页

**Comment by williamnie** [comment]
你是如何确定第二屏走的csr的？

**Comment by Magic-zhu** [comment]
想要这个功能

**Comment by williamnie** [comment]
想多了，你可以先去了解下react ssr的原理，就知道不可能的了，当用户请求时，服务端怎么知道用户的屏幕高度是多高，是渲染多少内容

**Comment by Magic-zhu** [comment]
不需要完全精确 可以在服务端固定一个高度  已经用nextjs实现过了 是可以实现的

**Comment by williamnie** [comment]
> 不需要完全精确 可以在服务端固定一个高度 已经用nextjs实现过了 是可以实现的

我好奇你是咋实现的，如果nextjs能实现，umi就能实现，nextjs是有什么参数配置能实现？

**Comment by Magic-zhu** [comment]
和框架本身没有关系 用umi也是可以实现的 这个功能是自己写的
