### ISSUE TITLE
开启ssr和exportStatic失败😩😩

### ISSUE THREAD

**Issue by giter-chenpan** [umijs/umi#7018]
## Mini Showcase Repository(REQUIRED)

[https://github.com/giter-chenpan/umi-test](https://github.com/giter-chenpan/umi-test)

## How To Reproduce

![image](https://user-images.githubusercontent.com/22983183/126072342-3f2f3cde-cbda-452f-895b-d701d7b5a782.png)
![image](https://user-images.githubusercontent.com/22983183/126072348-1f7e128b-be39-47d8-8779-a1d30665d979.png)

## Context

- **Umi Version**:3.5.13
- **Node Version**:12.13.0
- **Platform**:mac
 
错误日志：  
![image](https://user-images.githubusercontent.com/22983183/126072417-3c44d4c5-6cbb-4b18-8208-da55b9c06618.png)

**Comment by PeachScript** [comment]
使用 dva 要单独安装插件到 `devDependencies`，refer: https://umijs.org/zh-CN/plugins/plugin-dva
