### ISSUE TITLE
约定大于配置

### ISSUE THREAD

**Issue by kaoding** [umijs/umi#702]
1.  src 目录是可选的，可以有，也可以没有。

2.  umi 允许在 .umirc.js 或 config/config.js （二选一）中进行配置，支持 ES6 语法。

**上面2条有什么特别使用场景吗？如果紧紧是多一个选择，基于约定大于配置的理念，定死一种感觉更好。**
1.  src 目录是必选的。
2.  umi 只允许在 .umirc.js 中进行配置，支持 ES6 语法。
@sorrycc

**Comment by arvinxx** [comment]
说说我的看法

1. src 可选的原因主要是考虑了项目简单的情况下，没有必要多 N 个层级。比如很简单的一个静态页面，可能只要一个 pages 下的若干 js 文件和若干 css 文件就能搞定了，那么其实没有必要把这个 pages 文件夹再放进 src 里面，直接平铺即可，目录组织上会更加清晰一些。

2. umi 允许 config/config.js 我猜测是参考了 egg 的文件夹命名规范。为未来提供不同环境不同配置做了一点铺垫。( 详细可以参考下 egg的 config 部分 [Config 配置](https://eggjs.org/zh-cn/basics/config.html) ) 相信你看完之后应该会有所感觉。

**Comment by xiaohuoni** [comment]
关于第二点，之前有人提到过以点开头的文件在某些系统为隐藏文件

**Comment by kaoding** [comment]
以点开头的文件很多的
![default](https://user-images.githubusercontent.com/18542211/42681298-e21eb5f6-86b9-11e8-9d20-98a05d1bf19e.png)
