### ISSUE TITLE
umi能否支持设置ssr的范围，比如按照目录设置需要服务端渲染的页面，而没有在设置范围内的页面则不按ssr处理？

### ISSUE THREAD

**Issue by wldos** [umijs/umi#7023]
一个完整的互联网运营项目中存在中后台和前端，中后台不需要seo，而前端需要公开发布到公网必须支持seo，现在的问题是采用umi作为框架开发的项目中同时存在中后台和前端应用，umi能否支持设置ssr的范围，比如按照目录设置需要服务端渲染的页面，而没有在设置范围内的页面则不按ssr处理？

**Comment by fexlab** [comment]
强烈需求！！！

**Comment by williamnie** [comment]
有两种解决方案：
