### ISSUE TITLE
[Bug] 无关代码被自动引入并打包

### ISSUE THREAD

**Issue by jdz321** [umijs/umi#7026]
## What happens?

未使用任何antd等功能时，antd、helmet等部分代码依然被自动引入并打包

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

使用@umijs/create-umi-app创建新工程即可

## How To Reproduce

**Steps to reproduce the behavior:** 
1. `yarn create @umijs/umi-app`创建新工程
2. `yarn build`执行打包，查看构建产物
  ![image](https://user-images.githubusercontent.com/8564681/126182371-f06757a6-b8a4-4e34-a494-aece4b42da5b.png)
  ![image](https://user-images.githubusercontent.com/8564681/126184610-6d90a08a-676f-4a1b-bf99-f05c0e93b5b5.png)

可以看到umi.js包含了antd、antdIcon、helmet等等未使用的模块代码，查看umi.css同样包含antd部分代码

**Expected behavior** 
不自动引入和打包无关模块代码

## Context

- **Umi Version**:3.5.13
- **Node Version**:14.5.0
- **Platform**:macOS 11.0.1

**Comment by xiaohuoni** [comment]
给复现仓库吧。非使用任何antd，是这样的。看你这截图，大概率是需要在config中使用 `antd:false`
![image](https://user-images.githubusercontent.com/11746742/126256381-4a7d66ad-c698-4c35-a4e6-791116d1b02a.png)

**Comment by jdz321** [comment]
复现仓库：https://github.com/jdz321/pure-umi

根据提示，配置`antd:false`后，相关代码被移除，但仍然有`helmet`等代码，删除项目所有代码，并尝试添加如下配置后，无关代码基本清除干净，**但仍比 @xiaohuoni 的截图多出红框部分**，不清楚原因。

```js
{
  antd: false,
  helmet: false,
  request: false,
  model: false,
  initialState: false,
}
```

![image](https://user-images.githubusercontent.com/8564681/126282906-95892955-68cb-40f3-ba39-a81be406a1f0.png)

根据官网文档，antd等插件为配置开启，经查阅文档，是由于[该规则](https://umijs.org/zh-CN/docs/plugin#packagejson-%E4%BE%9D%E8%B5%96)使相关插件自动开启，所以需要通过[该规则](https://umijs.org/zh-CN/docs/plugin#%E9%85%8D%E7%BD%AE-key-%E4%B8%BA-false)手动关闭。

**Comment by xiaohuoni** [comment]
配置优先的，package中自动生效，你配置 false 他就没用了。感觉你并没有“未使用任何antd”。你用到了什么组件库，有依赖 antd 的话，肯定会被打包

**Comment by jdz321** [comment]
> 配置优先的，package中自动生效，你配置 false 他就没用了。感觉你并没有“未使用任何antd”。你用到了什么组件库，有依赖 antd 的话，肯定会被打包

为了测试新建的工程，一个字没写。。  yarn create && yarn && yarn build  然后双手离开键盘🙌，甚至连pages目录都全删掉了

**Comment by FeSeason** [comment]
我也是  咋关了 ？
