### ISSUE TITLE
[Bug]  yarn 2 安装依赖出现异常

### ISSUE THREAD

**Issue by thjxs** [umijs/umi#7027]
## What happens?
@umijs/utils 使用了未声明的依赖 @umijs/babel-preset-umi 导致 yarn 2 安装依赖出现异常

## How To Reproduce

* yarn create @umijs/umi-app
* yarn set version berry
* yarn

**Comment by xiaohuoni** [comment]
还没支持 yarn2 ，请关注这里的进度 https://github.com/umijs/umi/issues/6303
