### ISSUE TITLE
[Bug] 开启mfsu，添加splitchunks报错

### ISSUE THREAD

**Issue by victorWuxz** [umijs/umi#7029]
## What happens?

开启mfsu，添加splitchunks报错
![image](https://user-images.githubusercontent.com/36194121/126256267-ba7f4d69-4e30-460d-a20a-44b8a2ca90c9.png)

## 最小复现仓库
https://github.com/victorWuxz/umi-bug

## How To Reproduce

npm i
npm start

## Context

- **Umi Version**:3.5.13
- **Node Version**:12.13.1
- **Platform**:mac

**Comment by victorWuxz** [comment]
![image](https://user-images.githubusercontent.com/36194121/126256372-dcd38d87-ee49-494b-a20b-f9e3dd43b497.png)
splitchunks配置

**Comment by xiaohuoni** [comment]
感觉是因为 webpack5 的原因，你看看这文档 https://webpack.docschina.org/plugins/split-chunks-plugin/

不行给个重现。

**Comment by victorWuxz** [comment]
> 感觉是因为 webpack5 的原因，你看看这文档 https://webpack.docschina.org/plugins/split-chunks-plugin/
> 
> 不行给个重现。
复现仓库，只保留webpack5，注释掉mfsu构建没有问题
https://github.com/victorWuxz/umi-bug

**Comment by sorrycc** [comment]
需要调整 code splitting 策略，开启 mfsu 后没有 node_modules 依赖了，所以打不出 vendor 。

**Comment by livelybone** [comment]
该怎么调整
