### ISSUE TITLE
[Bug] 开启ssr后报错Cannot read property 'readFile' of undefined

### ISSUE THREAD

**Issue by rubyisapm** [umijs/umi#7032]
![image](https://user-images.githubusercontent.com/5107016/126297025-2f868f1a-095d-4a2c-9147-db5ca1ebb375.png)
umijs版本3.5.13
复现步骤：
1. 创建一个新项目
2. 配置ssr:{}开启ssr
3. 运行yarn start

**Comment by ycjcl868** [comment]
node 版本 >= 10
