### ISSUE TITLE
[Bug] umi项目中使用qiankun插件，子应用开启MFSU后报错

### ISSUE THREAD

**Issue by Jackwew** [umijs/umi#7035]
umi项目中使用qiankun插件，子应用开启MFSU后报错

开启方式如下: 
```js
  mfsu: {},
  qiankun: {
    slave: {},
  },
```
报错信息如下: 

![ac89e5d7b62c9190b99e9950d0ec693](https://user-images.githubusercontent.com/50656464/126442721-a24f3916-0e00-4482-aa9d-f486f8070c9d.png)

**Comment by sorrycc** [comment]
该升的依赖度升一下，qiankun 可以跑通的，搞不定得提供复现步骤。
