### ISSUE TITLE
[Bug] 构建报错服务退出

### ISSUE THREAD

**Issue by irongiants** [umijs/umi#7036]
hi，各位好
我按照快速上手，结合自己的领悟（umi升级到3.x版本没法用umi ui）
倒是可以启动umi UI，并成功创建项目，访问http://localhost:8000/看到运行效果。
但是当 点击任务-构建，开始构建时
后台报错，并直接关闭
E:\antd\app1>umi ui
 Starting Umi UI using umi@2.13.17...
 Ready on http://localhost:3000/
/  find block list form https://gitee.com/ant-design/ant-design-blocks/raw/master/umi-block.jsonevents.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn sh ENOENT
    at notFoundError (E:\antd\myapp\demo\node_modules\[4mcross-spawn[24m\lib\enoent.js:6:26)
    at verifyENOENT (E:\antd\myapp\demo\node_modules\[4mcross-spawn[24m\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (E:\antd\myapp\demo\node_modules\[4mcross-spawn[24m\lib\enoent.js:27:25)
[90m    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)[39m
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (E:\antd\myapp\demo\node_modules\[4mcross-spawn[24m\lib\enoent.js:30:37)
[90m    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)[39m {
  code: [32m'ENOENT'[39m,
  errno: [32m'ENOENT'[39m,
  syscall: [32m'spawn sh'[39m,
  path: [32m'sh'[39m,
  spawnargs: [ [32m'-c'[39m, [32m'umi build'[39m ]
}

环境搭建过程如下：
安装node.js 10.13以上，当前使用12.22.2
安装yarn
$ npm i yarn -g

创建应用目录
$ mkdir myapp 

创建umi应用
$ yarn create umi myapp

$ cd myapp
项目中安装preset-ui
$ yarn add @umijs/preset-ui -D
系统会提示升级umi从2.13到3.5 ，没有升级。

进入umi研发工作台

$ umi ui

**Comment by MasterBran** [comment]
why closed, there still have no solution。
