### ISSUE TITLE
[Bug] umi3.x eslint 如何开启，如何配置，有没有详细的文档

### ISSUE THREAD

**Issue by topLiwh** [umijs/umi#7037]
### umi3.x 如何开启eslint检查

 	1. umi3.x 项目生成后，发现没有eslint检查，于是在官网找到`修改eslint配置`一栏，如下图所示：
![Snipaste_2021-07-21_16-51-21](https://user-images.githubusercontent.com/69612441/126460553-17297919-07e3-4d9d-a609-6a6a37030bda.png)
![Snipaste_2021-07-21_16-53-17](https://user-images.githubusercontent.com/69612441/126460832-1467474a-da13-4a0f-8c97-07fdab57bfaa.png)
![Snipaste_2021-07-21_17-00-19](https://user-images.githubusercontent.com/69612441/126461833-b975fb47-082e-4671-9455-90a957c4e1ed.png)

 	2. 按照说明配置以后发现无效，该生效的地方没效果，不该生效的地方一片红，按照vscode的提示，一一进行了修复，（难道eslint的规则都需要一条一条的自己加上去？？？），如下图所示：
 	
![Snipaste_2021-07-21_17-03-38](https://user-images.githubusercontent.com/69612441/126462925-45d9a74a-d309-4a92-b913-e12bf14b5ede.png)
![Snipaste_2021-07-21_17-04-54](https://user-images.githubusercontent.com/69612441/126462938-929ff2ff-3dfc-4d04-90c4-50d1c6a7334f.png)
![Snipaste_2021-07-21_17-07-16](https://user-images.githubusercontent.com/69612441/126462941-71c0d01e-ee7d-4cfb-b7dd-2d3b5eb96987.png)

 	3. 并且安装`@umijs/fabric`插件以后，less文件格式化也不生效了……，我想知道这个依赖包到底是干嘛的，需要的东西一样也没拿到，不需要的东西，全都有了……
![Snipaste_2021-07-21_17-09-38](https://user-images.githubusercontent.com/69612441/126463328-f70c5ed1-ca7d-4f41-9d5b-e41ac648ba0b.png)
![Snipaste_2021-07-21_17-10-07](https://user-images.githubusercontent.com/69612441/126463338-854d543c-0d66-4bdd-8fd2-fb58b965dfc7.png)
 	4. 有没有解决的朋友，给个解决办法吧
 
### 环境说明
umi@3.5.13
windows10
@umijs/fabric": "^2.6.2"

搭建项目日期：2021/7/21

**Comment by xiefengnian** [comment]
cc @chenshuai2144

**Comment by 1247748612** [comment]
手动运行eslint检查看看有用吗

**Comment by xlei1123** [comment]
+1

**Comment by chenglianjie** [comment]
我也遇到了这个问题 哈哈哈 如果我解决了 我再来给你留言

**Comment by chenxiaoyao6228** [comment]
注意eslint-loader已经废弃,换[eslint-webpack-plugin](https://www.npmjs.com/package/eslint-webpack-plugin)

config.local.js

```js
const ESLintPlugin = require('eslint-webpack-plugin');

const config = {
  chainWebpack: (config: any) => {
    config
      .plugin('eslint')
      .use(ESLintPlugin, [
        {
          extensions: ['js', 'jsx', 'ts', 'tsx', 'less'], // 不再使用use
          fix: true,
          emitError: true,
          emitWarning: true,
        },
      ])
      .end();
  },
};

export default config;
```

**Comment by fanyongsir** [comment]
我加了个插件就对了: `eslint-plugin-prettier`

然后把 `.eslintrc.js` 改成了下面这样：

```js
```

**Comment by seveneElevenup** [comment]
> 我加了两个插件就对了: `eslint-plugin-prettier`和`@umijs/fabric`
> 
> 然后把 `.eslintrc.js` 改成了下面这样：
> 
> ```js
> module.exports = {
>   extends: [require.resolve('@umijs/fabric/dist/eslint')],
>   globals: {
>     ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION: true,
>     page: true,
>     REACT_APP_ENV: true,
>   },
>   plugins: ['prettier'],
>   rules: {
>     'prettier/prettier': 'error',
>   },
> };
> ```
> 
> 代码检测、保存自动格式化都起作用了，具体原因不晓得为啥

麻了，搞了一下午还是不生效

**Comment by wangchaoHeart** [comment]
> 注意eslint-loader已经废弃,换[eslint-webpack-plugin](https://www.npmjs.com/package/eslint-webpack-plugin)
> 
> config.local.js
> 
> ```js
> const ESLintPlugin = require('eslint-webpack-plugin');
> 
> const config = {
>   chainWebpack: (config: any) => {
>     config
>       .plugin('eslint')
>       .use(ESLintPlugin, [
>         {
>           extensions: ['js', 'jsx', 'ts', 'tsx', 'less'], // 不再使用use
>           fix: true,
>           emitError: true,
>           emitWarning: true,
>         },
>       ])
>       .end();
>   },
> };
> 
> export default config;
> ```

我用的v4版本 就是此方法解决的
