### ISSUE TITLE
[Bug] 升级mfsu 报promise不存在

### ISSUE THREAD

**Issue by 1247748612** [umijs/umi#7041]
## What happens?

启用msfu后报 
![image](https://user-images.githubusercontent.com/29533304/126469769-ced92f73-d689-4321-a331-bdf409af6b3e.png)
定位到这里报错了
![image](https://user-images.githubusercontent.com/29533304/126469516-447bd266-f387-4abe-a377-3fa7c695e409.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: v3.5.13
- **Node Version**:  v14.16.1
- **Platform**: Windows10

**Comment by 1247748612** [comment]
![image](https://user-images.githubusercontent.com/29533304/126470464-3447f0a5-8e6c-41bf-8a5b-48e80aa05973.png)
![image](https://user-images.githubusercontent.com/29533304/126470473-b5b02e78-ea2e-4897-ba76-a37de21c247e.png)

运行到这，再走两步就进finally了

**Comment by xiefengnian** [comment]
给一下复现步骤

**Comment by 1247748612** [comment]
目前我发现，我退回到之前的版本还是同样的问题，不是mfsu引发的。
我关闭fast refresh后正常。
#### 猜测原因
我把pages的目录名称改成了features，不知道是不是这个原因引发的？

**Comment by 1247748612** [comment]
@xiefengnian

**Comment by 1247748612** [comment]
{

  webpack5: {
    lazyCompilation: {
      entries: false,
      imports: true,
    },
  }
}

**Comment by 1247748612** [comment]
```typescript
{
  webpack5: {
    lazyCompilation: {
      entries: true,
      imports: true,
    },
  }
}
```

**Comment by 1247748612** [comment]
### umi: v3.5.13

> 排查发现，entries设置为false就正常了

```typescript
{
  webpack5: {
    lazyCompilation: {
      entries: false,
      imports: true,
    },
  }
}
```

但开启mfsu报错和 https://github.com/umijs/umi/issues/7052#issue-950515854 一样
