### ISSUE TITLE
[Bug] mfsu 使用umi>3.5.8报错， Unhandled Rejection (ChunkLoadError): Loading chunk mf-dep_vendors failed.

### ISSUE THREAD

**Issue by liangskyli** [umijs/umi#7042]
## What happens?

mfsu,开发报错：
Unhandled Rejection (ChunkLoadError): Loading chunk mf-dep_vendors failed.
(missing: http://127.0.0.1:8001/vendors.1990e8e6.async.js)
while loading "./$CWD$/node_modules/umi/node_modules/@umijs/runtime" from webpack/container/reference/mf
while loading "./dva" from webpack/container/reference/mf
while loading "./antd-mobile/lib/toast/style" from webpack/container/reference/mf
while loading "./react" from webpack/container/reference/mf

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

复现最小仓库：https://github.com/liangskyli/test

## Context

- **Umi Version**:>3.5.8
- **Node Version**:12.14
- **Platform**:windows,mac

**Comment by xiefengnian** [comment]
开启 mfsu 不需要再配置 splitChunks

**Comment by rimsila** [comment]
> ## What happens?
> mfsu,开发报错：
> Unhandled Rejection (ChunkLoadError): Loading chunk mf-dep_vendors failed.
> (missing: http://127.0.0.1:8001/vendors.1990e8e6.async.js)
> while loading "./$CWD$/node_modules/umi/node_modules/@umijs/runtime" from webpack/container/reference/mf
> while loading "./dva" from webpack/container/reference/mf
> while loading "./antd-mobile/lib/toast/style" from webpack/container/reference/mf
> while loading "./react" from webpack/container/reference/mf
> 
> ## Mini Showcase Repository(REQUIRED)
> > A using the Provide A Repository Please `yarn create @umijs/umi-app`the then the Upload to your GitHub Please provide a reproducible warehouse use `yarn create @umijs/umi-app`to create and upload to your GitHub repository
> 
> ## How To Reproduce
> **Steps to reproduce the behavior:** 1. 2.
> 
> **Expected behavior** 1. 2.
> 
> Reproduce the smallest warehouse: https://github.com/liangskyli/test
> 
> ## Context
> * **Umi Version**:>3.5.8
> * **Node Version**:12.14
> * **Platform**:windows,mac

Do you still error? 
I have the same error update to umijs 3.5.8 but after I deleted file src/.umi then run yarn start again it working.

**Comment by PeakFish** [comment]
这个问题好像是个 bug ，mfsu 更新有问题，我写了一个有问题的代码 `import { RequestConfig } from 'umi';` import 后面没加 type，然后就报错了，更新不过来，最后把 .umi 文件夹删掉 重新跑 好了。

**Comment by 57coder** [comment]
> 

可以解释下为啥吗

**Comment by 57coder** [comment]
> 开启 mfsu 不需要再配置 splitChunks

可以解释下为啥吗
