### ISSUE TITLE
build 后 src 下面的 assets 里面的图片，被改名打包到 dist 的根目录下

### ISSUE THREAD

**Issue by nuoer2048** [umijs/umi#7045]
umi 版本：1.1.8
问题：
src 新建一个 assets 文件夹，并放入一张图片
在 app.tsx 使用该图片(通过 import 方式引入图片)
build 之后 assets 并没有打包到 dist 的 assets 文件夹下，而是直接将 引用图片改名放在 dist 的根目录

**Comment by xiaohuoni** [comment]
因为默认的 [publicPath](https://umijs.org/zh-CN/config#publicpath) 就是'/'
