### ISSUE TITLE
mfsu 下 主题色不生效

### ISSUE THREAD

**Issue by kaoding** [umijs/umi#7048]
使用antd-pro v5 最新版本，启用 mfsu: {} 后，修改主题色（primaryColor）不生效

**Comment by sorrycc** [comment]
强刷，缓存问题。

**Comment by kaoding** [comment]
强刷也不行的。

**Comment by bobbychan** [comment]
> 强刷，缓存问题。

亲测，有效！

**Comment by kaoding** [comment]
> > 强刷，缓存问题。
> 
> 亲测，有效！

后面我也亲测子，强刷有时候行，有时候不行。不是每次刷都行。

**Comment by bobbychan** [comment]
我是有把src目录下的.umi删掉过

**Comment by sorrycc** [comment]
是个 bug。

**Comment by LoveEocding** [comment]
使用plugin-layout 设置布局以后改变 primaryColor 整体主题 无效

**Comment by zjfresh** [comment]
primary-color在 config/config.ts中设置成 theme: { '@primary-color': '#FFF'}能改变具体使用到该变量的，但其余衍生的就不行如 input:hover { color: primary-5 }

**Comment by GODOFZHZ** [comment]
赶紧解决，出了坑货玩意儿，阿里内装逼劲呢，接着装啊

**Comment by windman-only** [comment]
> 

hellow ， 请问解决了这个问题嘛，我也遇到了，改theme 配置也不行，崩溃辣~

**Comment by chihm** [comment]
这个问题什么时候可以解决？

**Comment by kaoding** [comment]
到时候使用 umi 4

**Comment by windman-only** [comment]
> 到时候使用 umi 4

噗，哈哈哈哈，这么说现在还是没解决呢呗？

**Comment by zhouwenwu30** [comment]
极有可能是在项目组件中引入了antd.css，引入后编译的时候会把antd.css整个编译一遍，这里面全是默认颜色，这样会导致自定义的主题色被覆盖。
`import 'antd/dist/antd.css';`

**Comment by 429299291** [comment]
我也是，本地打包正常，发布后，颜色失效

**Comment by feargadh** [comment]
23年了，umi4开启mfsu后是正常的，但是把esbuild打开就又来了。。。。
