### ISSUE TITLE
umi dev 和 build 均无任何错误，但是dist 的serve报 Minified React error #130

### ISSUE THREAD

**Issue by aleafo** [umijs/umi#705]
很简单个项目。。。 
umi dev 和 build 均无任何错误，但是dist 的serve后，访问，报 Minified React error #130
package.json
`
{
  "scripts": {
    "precommit": "npm run lint-staged",
    "start": "umi dev && roadhog dev"
  },
  "dependencies": {
    "antd-mobile": "^2.2.1",
    "axios": "^0.18.0",
    "jsonp": "^0.2.1",
    "lodash": "^4.17.10",
    "path-to-regexp": "^2.2.1",
    "qs": "^6.5.2",
    "rc-form": "^2.2.0",
    "umi-plugin-dva": "^0.9.1"
  },
  "devDependencies": {
    "roadhog-api-doc": "^1.1.0"
  }
}
`
有没有 可以提供个排查错误的思路 - -

**Comment by sorrycc** [comment]
https://reactjs.org/docs/error-decoder.html?invariant=130
有组件返回的是 undefined 吧。
