### ISSUE TITLE
[Bug] umi在IE11下打开报错

### ISSUE THREAD

**Issue by jyxu1016** [umijs/umi#7050]
github:  [https://github.com/jyxu1016/umi-test](url)
  Umi: "^3.5.13"
  Node : v10.24.1
  Platform: window 10
  
  按照umi文档快速上手@umijs/create-umi-app初始化，start 后在ie 11下跑不起来
  
![image](https://user-images.githubusercontent.com/84429503/126604101-2f564de9-20f7-48f9-87c6-02981943952a.png)
 @sorrycc  帮看看

**Comment by jyxu1016** [comment]
哎。。。。只能就这样一直等。。。。。。项目还等着上线呢，真是在屋檐下不得不低头

**Comment by dengnan123** [comment]
可以开启非压缩模式，看下是什么JS报错

**Comment by Iwouldliketobeapig** [comment]
看下是哪个包在报错，我这样解决的，devScript.js哪个不管也能在ie上跑起来，都是es语法的问题
![image](https://user-images.githubusercontent.com/20534862/151168631-1a4886bc-b860-4cab-81cc-530d4a369fbf.png)
分析到是@umi/bundler-webpack，然后做了如下操作
![image](https://user-images.githubusercontent.com/20534862/151168695-a883ef45-dad2-4454-a2cf-d91266749619.png)

**Comment by Zhang-haohua** [comment]
> 可以开启非压缩模式，看下是什么JS报错

请问怎么开启呢
