### ISSUE TITLE
[Bug] [mfsu] Error: Cannot find module './types.json' 

### ISSUE THREAD

**Issue by miaopeng** [umijs/umi#7052]
## What happens?

使用

```
npm install umi -D
npx umi g page index
vi .umirc.js (仅开启mfsu)
npx umi dev
```

 创建一个最小的umi项目时，开启mfsu, 此时命令行正常，但刷新页面后报错：

![Screen Shot 2021-07-22 at 6 21 03 PM](https://user-images.githubusercontent.com/506368/126624783-6484869f-61d0-422d-ac0d-dac87abd5338.png)

此时项目无法运行。

然后，如果删除 node_modules , 使用 yarn 进行安装，则可以正常启动项目！

这和@umijs/preset-built-in 的依赖 mime 有关。
我注意到 mime 的 1.3.0版本是有问题的, 这个版本的 package.json 中 scripts 字段写了两次。在umi 3.5.0-beta.1 的版本中，mime 的版本是1.6.0, 在接着后面的一个fix中改到了 1.3.0, 为什么呢？

## Mini Showcase Repository(REQUIRED)

复现仓库：
https://github.com/miaopeng/mfsu-projects

进入其中的 mini 目录下，进行安装和复现操作。

## Context

- **Umi Version**: 3.5.13
- **Node Version**: 15.0.1
- **NPM**: 7.20.0
- **Yarn**: 1.22.5
- **Platform**: Mac BigSur

**Comment by sorrycc** [comment]
没能复现，但看实现确实少了个文件，我升级下到 1.3.6 。
