### ISSUE TITLE
[Feature Request] mfsu 对 lerna 多包工程的支持

### ISSUE THREAD

**Issue by yunqiangwu** [umijs/umi#7058]
## Background

希望 mfsu 特性能够支持 lerna 的多包工程

我工程是一个 lerna 的多包管理的前端工程， lodash 在 父目录的 node_modules 下面， 
子模块启动 mfsu 时报错：

![image](https://user-images.githubusercontent.com/26475774/126747095-a2a70cb8-fef5-487a-8e6d-0f1afa60dd80.png)

![image](https://user-images.githubusercontent.com/26475774/126745336-38e4893b-bf83-48c3-915c-81e0f4f47951.png)

测试工程目录结构：
```
- node_modules
  - lodash
    - package.json
- packages
  - umi-app
    - package.json
- lerna.json

```

## Proposal

我本地做了如下修改之后

![image](https://user-images.githubusercontent.com/26475774/128536997-e00c209d-5945-4f8e-9d4f-845a6fb03487.png)

![image](https://user-images.githubusercontent.com/26475774/128537060-6ac8336d-4048-4f3c-b6a3-0ea5c34d66b6.png)

已经可以实现了 mfsu 对 lerna 工程的适配的需求。

希望 umi@3.5.x 能 支持一下 mfsu 对 lerna 工程的优化。

**Comment by yunqiangwu** [comment]
lerna 多包微前工程的 mfsu cache 配置到同一个一个地方，有没有提供相应的 umirc 配置。

**Comment by hangaoke1** [comment]
mark
