### ISSUE TITLE
[Bug] [mfsu] Official document demo error: Can't resolve '@@/plugin-antd-icon/icons'

### ISSUE THREAD

**Issue by xmasong** [umijs/umi#7060]
## What happens?

想体验 mfsu 特性，按照[umi官方文档-mfsu](https://umijs.org/zh-CN/docs/mfsu) 操作，初始化ant-design-pro v5 项目，开启 mfsu.production={} 后构建报错:
![image](https://user-images.githubusercontent.com/22997127/126863145-fd660fa8-9e85-403e-8a10-db0739eabf9f.png)

## How To Reproduce

1. `yarn create umi test-mfsu`，选择ant-design-pro、TypeScript、Simple

2. `cd test-mfsu && yarn add umi`，这里装最新 umi^3.5.0也有个报错 oas-linter 不存在 ^3.2.2，选了3.2.1
    
![image](https://user-images.githubusercontent.com/22997127/126863285-a75349f4-9cb3-4fdb-a792-ef53dbfc04e4.png)

3. 修改 config.ts，开启 mfsu.production={} 
4. yarn build 复现错误
![image](https://user-images.githubusercontent.com/22997127/126863145-fd660fa8-9e85-403e-8a10-db0739eabf9f.png)

## Context

- **Umi Version**: 3.5.13
- **Node Version**: v14.15.1
- **Platform**: mac os

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/126951024-7b049352-22b7-429a-945d-4d9594dccc17.png)
不能复现。

**Comment by WangXQ-git** [comment]
看看开发依赖时有没有 @umijs/preset-ant-design-pro，如果有的话移除了试试
`yarn remove @umijs/preset-ant-design-pro`

**Comment by DanileQin** [comment]
同样的问题。

**Comment by DanileQin** [comment]
> 看看开发依赖时有没有 @umijs/preset-ant-design-pro，如果有的话移除了试试
> `yarn remove @umijs/preset-ant-design-pro`

移除啦，打包也是有同样的问题。
