### ISSUE TITLE
[Feature Request] 模拟文件如何校验真实文件名/How to verify the real file name in mock file

### ISSUE THREAD

**Issue by LY1806620741** [umijs/umi#7062]
## Background

昨天我朋友找我帮忙看ant design的upload控件上传文件怎么携带路径的问题，她的需求是上传一个目录的文件并携带完整的目录结构信息，我解决了。但我是用umi构建的项目，使用其mock能力的时候希望能够模拟服务端校验文件是否携带路径返回成功或者失败
/
Yesterday, my friend asked me for help to see how the upload control of ant design carried the path of uploaded files. Her demand was to upload a directory file and carry complete directory structure information. I solved it. However, I make test project built with UMI. When using its mock capability, I hope to simulate the server to verify whether the file carries the path and returns success or failure

## Proposal

提供动态mock中req解析上传文件路径的功能/It provides the function of req parsing upload file path in dynamic mock

## Additional context

我上传的内容是(可以看到里面具有目录信息)/The content I uploaded is (you can see the directory information in it)
![image](https://user-images.githubusercontent.com/25952861/126930103-2e29b05f-f68c-4c79-9201-ceebd53c9d41.png)

我mock文件代码是/My mock file code is

```javascript
'POST /v1/upload': (req, res) => {
      res.send(req.files);
    },
```
打印结果是/The print result is

![image](https://user-images.githubusercontent.com/25952861/126930182-cd99c0cf-a5db-45c3-b250-fd2b2750c161.png)

可以看到路径信息没有了，我可能要从源码层去解决问题，但是这太花时间了，能提供这个功能么/You can see that there is no path information. I may have to solve the problem from the source code layer, but it takes too much time. Can you provide this function

**Comment by williamnie** [comment]
这个貌似和umi没啥关系吧，顶多算是跟antd 的upload有关系，可以自己写个form上传，还得确定浏览器的api是否支持这种，这个umi咋提供这个功能呢，跟他没什么关系

**Comment by LY1806620741** [comment]
> 这个貌似和umi没啥关系吧，顶多算是跟antd 的upload有关系，可以自己写个form上传，还得确定浏览器的api是否支持这种，这个umi咋提供这个功能呢，跟他没什么关系

我的意思是需要动态mock功能，我目前无法获取上传的携带目录信息的文件名来返回不同mock数据,因为它只解析了originalname

**Comment by leftstick** [comment]
@LY1806620741 你是怎么在上传时把文件目录也带过去的，代码贴出来看看

**Comment by LY1806620741** [comment]
之前是重写ant-desingn方法
```typescript
beforeUpload(file) {
    return new Promise(resolve => {
      try{
        Object.defineProperty(file, 'name',  {
          value: file.webkitRelativePath,
          writable: false,
          configurable: true,
          enumerable: true,
        });//修改只读属性
      }catch(e){
        console.log(e);
      }
}
```
