### ISSUE TITLE
[Feature Request] 能否暴露一个ReactDom.render方法 

### ISSUE THREAD

**Issue by leehomeok** [umijs/umi#7066]
## Background

目前我们需要做keepAlive, 想使用react-router-cache-route 通过包裹一层 《CaseRoute》进行路由匹配
做到页面路由缓存
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by juanfu1997** [comment]
+1，基于约定式路由的情况想使用react-router-cache-route还得配置路由文件

**Comment by xiaohuoni** [comment]
基于约定的路由，可以使用约定的 [layouts](https://umijs.org/zh-CN/docs/convention-routing#%E5%85%A8%E5%B1%80-layout)
也可以在运行时配置中[rootcontainer](https://umijs.org/zh-CN/docs/runtime-config#rootcontainerlastrootcontainer-args)添加 Provider

**Comment by xiaohuoni** [comment]
另外如果 [@alitajs/keep-alive](https://www.npmjs.com/package/@alitajs/keep-alive) 插件就满足需求的话，可以考虑使用，省事。

```
yarn add @alitajs/keep-alive
```
```js
export default {
  plugins: ['@alitajs/keep-alive'],
  keepalive: ['/pathname'],
};
```

**Comment by kokiy** [comment]
现在我们的应用作为remote 要放在host 应用里面 我们需要在host 提供的mount hook 里面 执行`ReactDom.render(<App/>)` @xiaohuoni 应该如何实现

**Comment by xiaohuoni** [comment]
看起来和乾坤好像，你可以看下乾坤插件的实现，关注子应用部分
