### ISSUE TITLE
可以只让某个页面ssr吗，怎么降级成客户端渲染

### ISSUE THREAD

**Issue by s464446877** [umijs/umi#7074]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by williamnie** [comment]
![image](https://user-images.githubusercontent.com/26871884/127418384-9a2e35d7-041b-4eed-a271-b0d010333daf.png)
文档里有介绍：https://umijs.org/zh-CN/docs/ssr     只要不获取数据，那个页面就不会走ssr

**Comment by s464446877** [comment]
就是不太理解这个渲染降级是自动的吗，还是node server需要写什么，现在看一直都是ssr，没有降级到csr。还有个问题需要帮忙，localstorage在ssr的时候怎么用，怎么在node上获取window等对象

**Comment by s464446877** [comment]
还有个问题需要帮忙，localstorage在ssr的时候怎么用，怎么在node上获取window等对象

**Comment by leftstick** [comment]
@s464446877  node 运行在服务器端，不会有 `localstorage` 和 `window`的。两点需要你自己思考

1. 你为什么要在 node 端 用 `localstorage` 和 `window`?
2. 这俩东西如果真出现在服务器端，你用什么来保证不会造成数据污染？ 举例：用户A发来请求，向`localstorage` 里存了数据，结果用户B发来的请求从 `localstorage` 里读了出来，这不是乱了么？如果真有这东西，他怎么做到请求级别的数据隔离？

**Comment by s464446877** [comment]
> @s464446877 node 运行在服务器端，不会有 `localstorage` 和 `window`的。两点需要你自己思考
> 
> 1. 你为什么要在 node 端 用 `localstorage` 和 `window`?
> 2. 这俩东西如果真出现在服务器端，你用什么来保证不会造成数据污染？ 举例：用户A发来请求，向`localstorage` 里存了数据，结果用户B发来的请求从 `localstorage` 里读了出来，这不是乱了么？如果真有这东西，他怎么做到请求级别的数据隔离？

那请求里封装的统一从localstorage里取token，服务端渲染的话localstorage肯定是不能用的，需要怎么带上token呢

**Comment by williamnie** [comment]
> > @s464446877 node 运行在服务器端，不会有 `localstorage` 和 `window`的。两点需要你自己思考
> > 
> > 1. 你为什么要在 node 端 用 `localstorage` 和 `window`?
> > 2. 这俩东西如果真出现在服务器端，你用什么来保证不会造成数据污染？ 举例：用户A发来请求，向`localstorage` 里存了数据，结果用户B发来的请求从 `localstorage` 里读了出来，这不是乱了么？如果真有这东西，他怎么做到请求级别的数据隔离？
> 
> 那请求里封装的统一从localstorage里取token，服务端渲染的话localstorage肯定是不能用的，需要怎么带上token呢

cookie里携带过去

**Comment by vipliucheng** [comment]
ssr渲染失败，在控制台能console出来出错的原因吗
