### ISSUE TITLE
[Bug] 2.x升级到3.x后只能在pages下面拿到 umi 其他地方如models里面 import{history} from 'umi' history undefined

### ISSUE THREAD

**Issue by JserZbf** [umijs/umi#7077]
2.x升级到3.x后只能在pages下面拿到 umi 其他地方如models里面 import{history} from 'umi' history undefined

**Comment by JserZbf** [comment]
![image](https://user-images.githubusercontent.com/35788814/127158379-da2db617-39f3-4a77-9572-e037e62b7e81.png)

**Comment by JserZbf** [comment]
import { resolve } from 'path';
export const TARGETS = {
  dev: {
    ems: 'http://172.17.40.154:9500',
  },
};
const TARGET = TARGETS[process.env.PROXY_TARGET] || {};
// ref: https://umijs.org/config/
export default {
  proxy: {
    context: (pathname, req) => {
      return req.headers['x-requested-with'] === 'XMLHttpRequest';
    },
    target: TARGET.ems,
    changeOrigin: true,
    ws: true,
    onProxyReqWs: (proxyReq) => {
      proxyReq.setHeader('origin', TARGET.ems);
    },
    secure: false,
    // 需要转发的API前缀
  },
  hash: true,
  antd: {
    dark:true
  },
  dva: {
    disableModelsReExport: true,
    lazyLoad: true,
  },
  dynamicImport:{} ,
  title: 'ems',
  headScripts: [
    // header里面插入script脚本
  ].filter((i) => i),
  links: [{ rel: 'stylesheet', href: '//at.alicdn.com/t/font_2681856_0b19j5gwny89.css' }],
  chainWebpack(config) {
    config.resolve.modules.add(resolve(__dirname, './src'));
    config.module
      .rule('worker-loader')
      .test(/\.worker\.js$/i)
      .use('worker-loader')
      .loader('file-loader');
  },
  define: {
    'process.env.dev': 'Y',
  },
};

**Comment by JserZbf** [comment]
找不到原因了。。求指点

**Comment by JserZbf** [comment]
"umi": "^3.5.13", 
"dva": "^2.6.0-beta.6",

**Comment by xiefengnian** [comment]
需要提供一个最小重现仓库

**Comment by iamwjj** [comment]
@JserZbf 我也遇到了，你解决了吗？

**Comment by zhl2liuli** [comment]
相同问题

**Comment by yituxiu** [comment]
相同的问题，pages以外的文件夹， import umi from 'umi' 。 console.log(umi) 结果undefined。求解

**Comment by starlikerain** [comment]
这一条是没有人处理吗，拿不到无法 import 进来的话，只能一层层把 history 传到子组件用了
