### ISSUE TITLE
[Feature Request] 能否支持一下vite

### ISSUE THREAD

**Issue by xuelei4122** [umijs/umi#7079]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by LeoHuiyi** [comment]
个人认为 原生ESM是解决热更新速度会随着应用体积增长而直线下降最优方案。

**Comment by xiefengnian** [comment]
try mfsu

**Comment by CodingOnStar** [comment]
> try mfsu

关于这一点，我也想考虑mfsu和vite的对比，你有什么想法吗？可否展开说说

**Comment by wsz7777** [comment]
+1

**Comment by transtone** [comment]
+1

**Comment by Aliveing** [comment]
+1

**Comment by zhangchao828** [comment]
这种深度耦合webpack定制的，很难迁移到vite了，vite说白了就是开发时启动和编译快，，这里可以开启webpack5的LazyCompilation再加上文件缓存，再加上mfsu，没慢到哪里去啊，

**Comment by xiaohuoni** [comment]
umi@4 支持了

**Comment by alvin0216** [comment]
> umi@4 支持了

还是 beta 版本，不知道怎么用～～请问计划什么时候会有正式版呢

**Comment by Mrcxt** [comment]
umi能否放弃webpack方案，所谓的mfsu性能真的不行，

**Comment by wozien** [comment]
> umi能否放弃webpack方案，所谓的mfsu性能真的不行，

主要是不稳定，各种踩坑报错

**Comment by yzfpf** [comment]
你们吹嘘的mfsu不太行，有时候会报莫名其妙的错误，有时候根本没效果

**Comment by Mrcxt** [comment]
> 你们吹嘘的mfsu不太行，有时候会报莫名其妙的错误，有时候根本没效果

这个umi就是个大黑盒，问题太多了，阿里的东西都这样，看着好用，真用起来了遇到问题改动成本很高。已经基本都迁移到vite上了，老项目建议使用rspack代替
