### ISSUE TITLE
[Bug] mfsu下alias的问题

### ISSUE THREAD

**Issue by kinchan2** [umijs/umi#7080]
## 如果alias映射node_modules下的组件，会报react错误

  
![截图](https://user-images.githubusercontent.com/15630672/127318232-f5ac1d2e-0cae-495c-a4ff-92017f9e5294.png)

## 复现代码

[test_mfsu.zip](https://github.com/umijs/umi/files/6892856/test_mfsu.zip)
/src/pages/index.tsx里通过正常antd引入和alias映射过后的antd引入的组件
正常从antd引入正常执行和渲染
通过alias映射过的路径引入组件会报错

## Context

- **Umi Version : 3.5.13
- **Node Version  : v14.15.0
- **Platform : win10

**Comment by sorrycc** [comment]
alias 没支持好，换绝对路径可以。

e.g.

```
  alias: {
    '@aliasAntd': dirname(require.resolve('antd/package'))
  },
```
