### ISSUE TITLE
webpack5，引用的样式顺序这里有点问题

### ISSUE THREAD

**Issue by cloudyan** [umijs/umi#7086]
## What happens?

开启 webpack5，这里引用的样式顺序有点问题，自定义的样式是后引入的，但打包引入的顺序不对，导致样式被覆盖

而关闭 webpack5，效果就对了，截图如下

开启 webpack5 
![image](https://user-images.githubusercontent.com/912821/127447550-e0372452-f0d8-4b85-97db-d5fb25c58070.png)

关闭 webpack5
![image](https://user-images.githubusercontent.com/912821/127447271-90c9fe3c-ae33-4efe-b5ad-df3c3dd9ea1c.png)

复现仓库
https://github.com/cloudyan/ant-design-mobile/tree/feature-webpack5

安装依赖，npm start 后，打开 http://localhost:8001/~demos/switch-demos

可以重现场景，通过开关 webpack5: {} 配置, 可以查看样式顺序区别

**Comment by cloudyan** [comment]
@sorrycc 这个问题有空帮看下，webpack4 好的，webpack5 坏的，给出复现仓库了

**Comment by cloudyan** [comment]
另外，开启 `dynamicImport: {}` 则 ant-design-mobile 中dialog 组件，样式加载也有问题了

目前官站[ant-design-mobile v5 分支](https://github.com/ant-design/ant-design-mobile/tree/v5)最新版（commit: 59d87dc）开启此项也是有问题的

http://localhost:8000/components/dialog

![image](https://user-images.githubusercontent.com/912821/127971014-13b21e3a-9d27-42ba-b6d3-e112a5f341cd.png)

**Comment by renkunx** [comment]
把样式聚合会好一点，其他的需要手动修改。
