### ISSUE TITLE
[Bug] mfsu filePath not found

### ISSUE THREAD

**Issue by huangkairan** [umijs/umi#7088]
## What happens?

![image](https://user-images.githubusercontent.com/56213366/127593346-b34eee3b-33b8-4bae-b50b-fa63fba649a7.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by Zach-Lu** [comment]
so am I

**Comment by huangkairan** [comment]
> so am I

delete .umi then try again
