### ISSUE TITLE
umi3.5.8 开启mfsu 报错

### ISSUE THREAD

**Issue by KinBill** [umijs/umi#7091]
<img width="1029" alt="问题" src="https://user-images.githubusercontent.com/32724798/127614437-01192361-e73b-4965-b9dc-e8d61774bc89.png">
umi3.5.10开启会发生此错误，我把版本降到了3.5.8还是报错，不启动mfsu是正常不报错的，其他版本暂时未尝试

**Comment by sorrycc** [comment]
应该是有些插件依赖不是最新的。

**Comment by Zach-Lu** [comment]
这就算是解决了？

**Comment by sorrycc** [comment]
@Zach-Lu 没有复现步骤，猜不到问题。
