### ISSUE TITLE
[Bug]MFSU react-virtualized AutoSizer

### ISSUE THREAD

**Issue by luoyifanff** [umijs/umi#7092]
## What happens?

开启MFSU，使用react-virtualized AutoSizer组件报错

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

![image](https://user-images.githubusercontent.com/31697066/127614496-6d57613b-173d-42c5-95d5-2bcfe9be1a7c.png)

## Context

- **Umi Version**: 3.5.3
- **Node Version**: v14.11.0
- **Platform**:

**Comment by sorrycc** [comment]
给复现仓库。

**Comment by luoyifanff** [comment]
删除.mfsu重新编译后解决
