### ISSUE TITLE
[Feature Request] Global Layout 404 page

### ISSUE THREAD

**Issue by h-a-n-a** [umijs/umi#7093]
## Background

pages/404.tsx does not support Layout level 404 page, in which case, component 404 only shows under the current layout itself

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

add conventional 404 Layout in src/layout/404.tsx, which will add a global 404 page

**Comment by hurryhuang1007** [comment]
I can use a full screen fixed 404 page
