### ISSUE TITLE
加入一个编译时，忽略某些文件夹的配置项

### ISSUE THREAD

**Issue by Jeggery** [umijs/umi#7094]
能否像webpack一样，配置下exclude，就可以忽略某些文件夹编译，这样开发模式下启动项目会快肯多.umi.js虽然有nodeModulesTransform配置，但是不适用与我这个，我的是src文件下，有个别人文件夹里的js不需要进行编译

**Comment by xiefengnian** [comment]
try mfsu

**Comment by 7kms** [comment]
mfsu大发虽好,  但是exclude功能应该也可以有.  

目前可以使用自定义插件来模拟实现,  当route读取完成之后,  在modifyRoute钩子中,  修改route的整体配置,  可以达到exclude效果.

我司目前就是这样做的,  不过dva其实不是很兼容,  dva会读取`src`下面的全量配置来初始化`model`

**Comment by 7kms** [comment]
工程有100多个页面, 每次开发的时候, 其实用上的就一两个页面, 所以开发的时候我们做了一个trick.  相当于隔离了一层`include/exclude`吧.  

如果官方能支持这个`feature`挺好.  

目前感觉mfsu不那么稳定, 有些边界情况可能会出问题,  再迭代几个版本会好很多.

**Comment by peng2018** [comment]
@7kms 有可以参考的demo吗？谢谢

**Comment by zhangchao828** [comment]
> 工程有100多个页面, 每次开发的时候, 其实用上的就一两个页面, 所以开发的时候我们做了一个trick. 相当于隔离了一层`include/exclude`吧.
> 
> 如果官方能支持这个`feature`挺好.
> 
> 目前感觉mfsu不那么稳定, 有些边界情况可能会出问题, 再迭代几个版本会好很多.

这种情况使开启webpack5的LazyCompilation不就好了，没访问的路由，就不会去编译了
