### ISSUE TITLE
[Feature Request] can `import { routes } from 'umi';`

### ISSUE THREAD

**Issue by hurryhuang1007** [umijs/umi#7104]
我准备使用sentry对项目页面性能进行监测，需要与 react-router 进行集成。

根据[sentry文档](https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/react-router/#parameterized-transaction-names)，我使用 传递路由配置对象 方式处理特殊路由。

![image](https://user-images.githubusercontent.com/21291247/127847324-0ceacf6d-a773-4a4a-b5f6-b0f81e072f9d.png)

但是他需要 routes 配置项 (`Sentry.reactRouterV5Instrumentation(history, routes, matchPath)`)。我使用的是约定式路由，并且初始化sentry的逻辑是写在了app.js中 (也本该如此)。

但是我现在无法直接拿到 routes ... (或许是我没找到？)

**Comment by PeachScript** [comment]
`import { getRoutes } from '@@/core/routes'`
