### ISSUE TITLE
[Bug]  开启 mfsu 后紧凑样式及暗黑主题失效

### ISSUE THREAD

**Issue by jszyy** [umijs/umi#7112]
## 当我在应用中开启 mfsu 后，暗黑主题和紧凑主题产生了错误

.umirc.ts 配置如下：
```
import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  dynamicImport: {},
  routes: [],
  fastRefresh: {},
  mfsu: {},
  // antd: {
  //   dark: true, // 开启暗色主题
  //   compact: true, // 开启紧凑主题
  // },
});
```

> GitHub 仓库： https://github.com/jszyy/blog_frontend.git

## How To Reproduce

**Steps to reproduce the behavior:** 

1. yarn start 启动项目
2. 将.umirc.ts 中 mfsu 选项解除注释
3. 查看页面效果

**Expected behavior** 

1. 暗黑主题下，Typography 组件字体应为白色，紧凑布局下字号应为12号
2. 紧凑布局下 posts 页面列表间隔应较小，并且字号应为12号

## Context

- **Umi Version**: 3.5.14
- **Node Version**: 16.4.0
- **Platform**: macOS

**Comment by qlniu** [comment]
现在是如何解决的， 我添加暗黑配置并不生效
antd: {
    dark: true,
  },
