### ISSUE TITLE
@umijs/plugin-antd-dayjs替换后，打包体积和原来一样大，dep: antd v3，umi:3.5.0，moment:^2.24.0

### ISSUE THREAD

**Issue by cschensai** [umijs/umi#7113]
![image](https://user-images.githubusercontent.com/38218964/127996767-026bfded-d1cb-403b-b9c8-155f077e509f.png)

**Comment by cl1107** [comment]
![image](https://user-images.githubusercontent.com/21985353/127998532-3d969de0-392a-43b6-a414-2803a1067855.png)
上图这是用了antd-dayjs-webpack-plugin的效果
![image](https://user-images.githubusercontent.com/21985353/127999110-71031641-468d-41e4-98b1-3f909bfea5fd.png)
这是用@umijs/plugin-antd-dayjs的效果
这是能复现的仓库 https://github.com/cl1107/antd-pro-dayjs-mfsu

**Comment by kokiy** [comment]
我项目中没有引用 antd & antd mobile 和 moment,只是开启了 locale ,moment 就被打入进入了,不知道为啥locale plugin depends moment, @sorrycc

**Comment by topwood** [comment]
+1
