### ISSUE TITLE
在models中添加数据源之后、刷新当前页面，页面会渲染两次

### ISSUE THREAD

**Issue by lizhihaoerdaye** [umijs/umi#7115]
## 开发环境
- node v12.8.1
- umi v3.5.15
- 操作系统 windows10
## 在models文件夹中新建js后页面渲染两次
![image](https://user-images.githubusercontent.com/47618476/128014374-d6b9f465-f91e-4437-9ad7-aef6d18a804a.png)
![image](https://user-images.githubusercontent.com/47618476/128014657-34db9d62-941f-4998-bfc1-eced84200d70.png)
![image](https://user-images.githubusercontent.com/47618476/128014569-af11a66f-5516-4129-8010-a536926ebc5c.png)
## 删除掉models中的js后刷新当前页正常渲染
![image](https://user-images.githubusercontent.com/47618476/128014889-f0395563-2544-4868-95c8-54d82fccf148.png)

**Comment by mgsod** [comment]
请问这问题有解决吗
