### ISSUE TITLE
[mfsu] 开启 mfsu 后，疑似并不能拉取和缓存依赖中的依赖？导致 Cannot find module，系统报错

### ISSUE THREAD

**Issue by GiserTangqin** [umijs/umi#7118]
报错信息：
![image](https://user-images.githubusercontent.com/20224381/128145546-0f8c69eb-27cf-4e75-875c-938e48d92dfc.png)

依赖信息：
![image](https://user-images.githubusercontent.com/20224381/128145768-8bda3707-46b5-40a1-b09c-437ca5cc4ee1.png)

配置信息：
![image](https://user-images.githubusercontent.com/20224381/128147240-29ab29d4-2db3-4184-b223-0bb64c73bbaf.png)

关闭 mfsu 后，系统运行正常。

- **Umi Version ：3.5.15**:
- **Node Version：14.4.0 **:

**Comment by GiserTangqin** [comment]
https://github.com/GiserTangqin/mfsuTest
抱歉未及时回复，以上为复现实例，请查看

**Comment by peterzhai** [comment]
我这也遇到了。自己开发的组件库，库里引入了第三方的css，现在主项目上就找不到第三方的css，关了mfsu就没有问题
