### ISSUE TITLE
AssertionError [ERR_ASSERTION]: filePath not found of ~/node_modules/umi/node_modules/@umijs/renderer-react

### ISSUE THREAD

**Issue by teamco** [umijs/umi#7119]
## What happens?
Clean install after updating umijs to the latest version - got the following error in a few projects (same issue)

IMHO - invalid path to: ./node_modules/umi/node_modules/@umijs/renderer-react
It must be changed to: ./node_modules/@umijs/renderer-react

AssertionError [ERR_ASSERTION]: filePath not found of ./node_modules/umi/node_modules/@umijs/renderer-react
at ./node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:115:27
at Generator.next ()
at asyncGeneratorStep (./node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:64:103)
at _next (./node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:66:194)
at ./node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:66:364
at new Promise ()
at ./node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:66:97
at figureOutExport (./node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:125:17)
at ./node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:184:201
at Generator.next ()

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce
yarn start

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.5.15
- **Node Version**: v14.8.0
- **Platform**: macOs 11.5

**Comment by teamco** [comment]
ls ./node_modules/umi/node_modules/@umijs
preset-built-in 
renderer-mpa    
runtime

**Comment by teamco** [comment]
ls ./node_modules/umi/node_modules/@umijs
preset-built-in 
renderer-mpa    
runtime

**Comment by teamco** [comment]
The issue happened only when MFSU is enabled

Starting the development server...

✔ Webpack
  Compiled successfully in 41.99s

 DONE  Compiled successfully in 41994ms                                                            9:31:54 PM

  App running at:
  - Local:   http://localhost:8001 (copied to clipboard)
  - Network: http://192.168.3.20:8001

启动时间有点慢，试试新出的 MFSU 方案，1s+ 完成启动，详见 https://github.com/umijs/umi/issues/6766
 WAIT  Compiling...                                                                                9:31:55 PM

✔ Webpack
  Compiled successfully in 1.44s

 DONE  Compiled successfully in 1436ms

**Comment by yorickshan** [comment]
same issue

**Comment by teamco** [comment]
found the issue - removing ./src/.umi folder solve the problem
