### ISSUE TITLE
执行 npm run start 后，编译时出现  @umijs\deps\compiled\webpack\4\bundle4.js:64  throw new Error('Callback was already called.');

### ISSUE THREAD

**Issue by sunnnnnner** [umijs/umi#7120]
## What happens?
执行 npm run start 后，编译时出现  @umijs\deps\compiled\webpack\4\bundle4.js:64  throw new Error('Callback was already called.');
@umijs/deps took 13.54 secs
  module count = 29
@umijs/preset-built-in, and
@umijs/deps took 9.43 secs
  module count = 39
@umijs/deps took 3.054 secs
  module count = 3

  App running at:
  - Local:   http://localhost:7000 (copied to clipboard)
  - Network: http://10.21.13.199:7000

* Webpack █████████████████████████ building (70%) 29/29 modules 0 active

E:\zohocrm_qianduan\src\1627557258476981_crm-master\crm-master\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:64
297
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (E:\zohocrm_qianduan\src\1627557258476981_crm-master\crm-master\node_modules\@umijs\deps\compiled\webp
ack\4\bundle4.js:64297:11)
    at E:\zohocrm_qianduan\src\1627557258476981_crm-master\crm-master\node_modules\@umijs\deps\compiled\webpack\4\bundle
4.js:67099:7
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.5.15
- **Node Version**: v14.16.1
- **Platform**:

**Comment by majia007** [comment]
same question. node@12.22.1, umi@3.5.14. win10 pro@18362.1082

**Comment by scZhengChao** [comment]
same question
