### ISSUE TITLE
[Bug] deps/compiled 的 getSourceForScriptExternal 跟 webpack 的不同

### ISSUE THREAD

**Issue by fengsx** [umijs/umi#7122]
## What happens?

RT.
在 `deps/compiled/webpack/5/bundle5.js` 中的函数 getSourceForScriptExternal 里多了一个 L103744 `RuntimeGlobals.publicPath`，与 webpack 主工程同名函数 [getSourceForScriptExternal](https://github.com/webpack/webpack/blob/main/lib/ExternalModule.js#L280) 不同。请更新 webpack 5 版本吧~

做了一个组件，需要用到 webpack 5 的 script external 做按需引入。
- umi 的
![image](https://user-images.githubusercontent.com/7709602/128319198-68a73fcb-cf42-40b7-82b3-2e1b8fc9bef2.png)

- webpack 的

![image](https://user-images.githubusercontent.com/7709602/128319307-2e75e6d9-a1a4-4962-80f2-1d680fa31a78.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/webpack/webpack/blob/main/lib/ExternalModule.js#L280
## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.5.15
- **Node Version**: 14
- **Platform**: mac

**Comment by sorrycc** [comment]
复现步骤：

1. git clone https://github.com/fengsx/umi-plugin-runtime-import
2. npm i
3. npm start
