### ISSUE TITLE
[Bug] 开启mfsu功能后，以组件形式加载svg资源时，在windows上编译报错

### ISSUE THREAD

**Issue by astonishqft** [umijs/umi#7126]
## What happens?

在windows下，开启了mfsu功能，只要页面中引入了svg格式的资源，打包的时候会报错。试了一下，当svg以React组件形式使用的时候就会报错。

```js
import React from 'react';
import styles from './index.less';
import { Link } from 'umi';
import { Button } from 'antd';
import { ReactComponent as Logo } from './upload_setting.svg';

export default () => {
  return (
    <div>
      <Logo width={90} height={120} />
      <Button type="primary">Click me</Button>
      <Link to="/test">Test</Link>
      <h1 className={styles.title}>Page index55</h1>
    </div>
  );
}
```
![bug-mfsu](https://user-images.githubusercontent.com/15138753/128341690-2d3a9d17-230d-400f-94cd-43101d568763.png)

## Context

- **Umi Version**:3.5.0-beta.20
- **Node Version**:v14.16.1
- **Platform**:windows

**Comment by astonishqft** [comment]
看起来像是windows下的路径问题

**Comment by sorrycc** [comment]
这个问题修过，更新到 umi 最新吧。
