### ISSUE TITLE
umi3 国际化只提供了useIntl 和injectIntl别的情况下怎么办？

### ISSUE THREAD

**Issue by liangshuiying** [umijs/umi#7133]
### Discussed in https://github.com/umijs/umi/discussions/7124

<div type='discussions-op-text'>

<sup>Originally posted by **liangshuiying** August  5, 2021</sup>
现在在utils中定义了一些公共方法：如
export const getTitle = ( route: any, path: string) => {
  if (route && route[path] && route[path].locale) {
    return `${formatMessage({ id: route[path].locale }) } - $formatMessage({ id: 'zhilan' })}`;
  } if(route && route[path] && route[path].name) {
    return `${route[path].name } - ${formatMessage({ id: 'zhilan' })}`;
  }
    return formatMessage({ id: 'zhilan' });
};
和封装了request 中的国际化直接报错
/**
 * request 网络请求工具
 * 更详细的 api 文档: https://github.com/umijs/umi-request
 */

import { extend } from 'umi-request';
import { notification } from 'antd';
import Cookies from 'js-cookie';
import moment from 'moment';
import md5 from 'md5';
import { history } from 'umi';
import { sortByAscll } from './utils';
import { useIntl } from 'umi'

interface MD5Datas {
  background_type?: string;
  domain_id?: string;
  Timestamp?: string;
}
const intl = useIntl();
const codeMessage = {
  200: intl.formatMessage({ id: '200' }), // '服务器成功返回请求的数据。',
  201: intl.formatMessage({ id: '201' }), // '新建或修改数据成功。',
  202: intl.formatMessage({ id: '202' }), // '一个请求已经进入后台排队（异步任务）。',
  204: intl.formatMessage({ id: '204' }), // '删除数据成功。',
  400: intl.formatMessage({ id: '400' }), // '发出的请求有错误，服务器没有进行新建或修改数据的操作。',
  401: intl.formatMessage({ id: '401' }), // '用户没有权限（令牌、用户名、密码错误）。',
  403: intl.formatMessage({ id: '403' }), // '用户无权限访问。',
  404: intl.formatMessage({ id: '404' }), // '发出的请求针对的是不存在的记录，服务器没有进行操作。',
  406: intl.formatMessage({ id: '406' }), // '请求的格式不可得。',
  410: intl.formatMessage({ id: '410' }), // '请求的资源被永久删除，且不会再得到的。',
  422: intl.formatMessage({ id: '422' }), // '当创建一个对象时，发生一个验证错误。',
  500: intl.formatMessage({ id: '500' }), // '服务器发生错误，请检查服务器。',
  502: intl.formatMessage({ id: '502' }), // '网关错误。',
  503: intl.formatMessage({ id: '503' }), // '服务不可用，服务器暂时过载或维护。',
  504: intl.formatMessage({ id: '504' }), // '网关超时。',
};

console.log(process.env.ENV_FLAG);
const apiRoot = process.env.ENV_FLAG === 'wechat' ? '/application' : '';

/**
 * 异常处理程序
 */
const errorHandler = (error: { response: Response }): Response => {
  const { response } = error;
  // 响应体有业务提示
  if (response && response.status) {
    const errorText = codeMessage[response.status] || response.statusText;
    const { status, url } = response;

    notification.error({
      message: `${intl.formatMessage({ id: 'request_error' })}${status}: ${url}`,
      description: errorText,
    });
  } else if (!response) {
    notification.error({
      description: intl.formatMessage({ id: 'no_connent' }), // '您的网络发生异常，无法连接服务器',
      message: intl.formatMessage({ id: 'error_network' }), // '网络异常',
    });
  }
  return response;
};

/**
 * 配置request请求时的默认参数
 */

const OMOrequest = extend({
  errorHandler, // 默认错误处理
  credentials: 'omit', // credentials,omit,same-origin,include 请求是否带上cookie
});

export function requestInterceptors(url: string, options: any) {
  let domainId: string | null = null;
  let accessToken: string | null = null;

  // 登录信息
  if (Cookies.get('currentAuthority') && JSON.parse(Cookies.get('currentAuthority') || '{}').access_token) {
    domainId = JSON.parse(Cookies.get('currentAuthority') || '{}').domain_id;
    accessToken = JSON.parse(Cookies.get('currentAuthority') || '{}').access_token;
  }

  const { method, data, headers: tempHeader = {}, params } = options;
  let extData = {};
  let md5Data: MD5Datas = {};
  let timestamp = moment().unix() * 1000;

  // 非get方式加上额外数据
  if (method !== 'get') {
    extData = {
      domain_id: domainId || null,
      background_type: '0',
    };
  }

  // 开发模式下，将/api/删除
  if (process.env.API_ENV !== 'development') {
    url = url.replace(/\/api\//g, '');
  }

  // get与delete下，md5Data加上传参
  if (method === 'get' || method === 'delete') {
    md5Data = { ...params };
    md5Data.background_type = '0';
    md5Data.domain_id = domainId ? domainId + '' : 'null';
    md5Data = { ...md5Data, ...params };
  }

  md5Data.Timestamp = timestamp + '';
  let sortData = JSON.stringify(sortByAscll(md5Data));
  let headers = {
      Authorization: 'Bearer ' + accessToken,
      Timestamp: timestamp,
      Sign: md5(sortData).toUpperCase(),
      domain_id: domainId || null,
    ...tempHeader,
  };

  let reqParam = {};
  if (method === 'get' || method === 'delete') {
    reqParam = { background_type: '0', domain_id: domainId || 'null', ...params };
  }
  if (DEBUG) {
    console.log('data=====post======', data);
  }

  return {
    url: apiRoot + url,
    options: {
      ...options,
      headers,
      params: reqParam,
      data: { ...extData, ...data },
    },
  };
}

OMOrequest.interceptors.request.use(requestInterceptors, { global: false });

OMOrequest.interceptors.response.use(async response => {
  let httpStatus = '';
  try {
    const { status } = response as any;
    // eslint-disable-next-line @typescript-eslint/await-thenable
    const responseClone = await response.clone();
    const contentType = responseClone.headers.get('Content-Type') as any;
    if (contentType.includes('application/json')) {
      // 不是下载
      const data = await responseClone.json();
      // console.log('data====response==========', data);
      if (status === 400 && data && data.error && data.error.code === '010008') {
        history.replace('/users/login');
        httpStatus = intl.formatMessage({ id: 'login_again' }) // '请重新登录';
        return;
      }
      if(status === 200 && data && data.error && data.error.code === '000009') {
        history.replace('/selectSpace');
        httpStatus = intl.formatMessage({ id: 'select_space' }) // '请选择空间';
        return;
      }
      return await response.json();
    }
  } catch (error) {
    notification.error({
      message: `${intl.formatMessage({ id: 'request_error' })} ${httpStatus}`,
      description: intl.formatMessage({ id: 'unknown_error' }), // '未知错误',
    });
  }

  return response;
}, { global: false });

export default OMOrequest;

想要这个方法正常运行应该怎么办</div>

**Comment by PeachScript** [comment]
Umi 3 仍然提供 `import { formatMessage } from 'umi'` 的用法，只是不建议使用了，参考 [plugin-locale 文档说明](https://umijs.org/zh-CN/plugins/plugin-locale#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E8%A6%81%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8-formatmessage-%E8%BF%99%E4%B8%AA%E8%AF%AD%E6%B3%95%E7%B3%96%EF%BC%9F)
