### ISSUE TITLE
关于mfsu的一点疑问

### ISSUE THREAD

**Issue by astonishqft** [umijs/umi#7139]
关于mfsu有个疑问，umi一旦开启了mfsu之后，会进行依赖预编译，然后访问应用的时候，会通过network的形式去加载这些js。就像下面这个例子中体现的：
![image](https://user-images.githubusercontent.com/15138753/128607996-1e88af48-6461-470e-a47e-920fb22d9c02.png)
我的问题是，如果应用复杂了之后，那么浏览器一次性请求的静态资源就会非常多，并且有的依赖包可能会比较大。浏览器又存在请求并发数的限制，chrome一般最大网络并行请求资源数是6，这种情况下是否会导致页面的加载性能受影响？希望有人能给个解答，万分感谢！

**Comment by sorrycc** [comment]
目前是个问题，后续版本是会做优化的。

**Comment by nightsu** [comment]
是的，尤其是业务代码以及依赖包很多的时候，部署以后某种程度上可以说更慢了。但是技术方向是对的，希望后续可以优化

**Comment by LukeLiou** [comment]
> 目前是个问题，后续版本是会做优化的。

请问使用mfsu后 每次切分支都会出现编译过久的情况，此问题有解决方案吗
多人合作时，可以配置 mfsu.development.output 配置预编译依赖输出目录并添加到 git 中，在其他开发者启动时，就可以免去再次编译依赖的过程。

这个点没看懂

**Comment by pangxiaolong** [comment]
> umi 3 不维护了，建议升级到 umi 4

我现在也遇到这个问题，require引用改为import后项目可以加载，但是每个页面加载都很慢，甚至有大概率可能会直接页面卡死奔溃，关闭devtool的情况下好一些，不会卡死，但是每个页面还是要加载10秒以上才加载成功，所以除了升级到umi4还有设么其他方式吗，还是这个问题已经在umi中得到解决了？
