### ISSUE TITLE
umi @3.5.15 在IE11下打开报错

### ISSUE THREAD

**Issue by ALL-STACK** [umijs/umi#7140]
## What happens?
umi @3.5.15 在IE11下打开报错

![image](https://user-images.githubusercontent.com/24264872/128653891-5e3dff28-c69e-40a8-8d4d-272a52d5f2a3.png)

按照官网流程新建项目，下载依赖，yarn start 后 IE11下报错，以前也提过相同的bug，现在umi都不支持IE了？
![image](https://user-images.githubusercontent.com/24264872/128653921-873760ad-7fc7-482e-b68e-057c296ea40b.png)

## How To Reproduce

复现库：https://github.com/ALL-STACK/umi-latest-Demo.git

## Context

- **Umi Version**: 3.5.15
- **Node Version**: 12.18.3 
- **Platform**: IE11

**Comment by banchichen** [comment]
+1, same issue

**Comment by banchichen** [comment]
我这按照 https://github.com/umijs/umi/issues/6433 里的方法，设置了nodeModulesTransform后可以了

**Comment by hurryhuang1007** [comment]
看你设置了 nodeModulesTransform: none。
感觉大概率是因为你装了一些发布到npm但是没有把dist代码转换成es5的库 导致的。

**Comment by fybchristasker** [comment]
试了你的配置，要把nodeModulesTransform换成all，MFSU配置也去掉再编译就可以了
