### ISSUE TITLE
[Bug] 开启mfsu的问题

### ISSUE THREAD

**Issue by zhaolei2013** [umijs/umi#7150]
1.开启mfsu后启动变快了但是热更还是很慢。
2.项目启动的时候，打开浏览器调试窗口，再点浏览器左上角的刷新按钮，页面会白屏一段时间，很慢得很久才能显示，关闭mfsu则不会出现这个问题

**Comment by sorrycc** [comment]
需要复现步骤。

**Comment by 7kms** [comment]
这个问题我司也有遇到,  是由于dva收集到的model太多了造成的(页面比较多).  初步debug了一下, 与webpack5有一定关系.  

可以上传一个demo, 让作者看看情况

**Comment by astonishqft** [comment]
这个问题我们也遇到了，工程复杂了之后，打开浏览器的调试模式，页面会一直白屏，要过很久才能显示页面。初步分析是因为浏览器的请求太多了（因为mfsu请求的预编译自资源是在太多了），处理请求需要足够多的时间才有返回，之前也建过[issue](https://github.com/umijs/umi/issues/7139)反馈过这个问题。

**Comment by hehuasa** [comment]
>  这个问题我们也遇到了，工程复杂了之后，打开浏览器的调试模式，页面会一直白屏，要过很久才能显示页面。初步分析是因为浏览器的请求太多了（因为mfsu请求的预编译自资源是在太多了），处理请求需要足够多的时间才有返回，之前也建过[issue](https://github.com/umijs/umi/issues/7139)反馈过这个问题。

+1

**Comment by LeoHuiyi** [comment]
![image](https://user-images.githubusercontent.com/8001457/129151626-6b921111-7e9f-40bf-acde-d03b0ea9234d.png)

chrome devTools settings 这个勾了试试

**Comment by 7kms** [comment]
我们得到的结果并不是请求慢,  而是执行慢. 关掉debug会好一点

**Comment by astonishqft** [comment]
> 我们得到的结果并不是请求慢, 而是执行慢. 关掉debug会好一点

那代码怎么调试呢？

**Comment by LeoHuiyi** [comment]
> > 我们得到的结果并不是请求慢, 而是执行慢. 关掉debug会好一点
> 
> 那代码怎么调试呢？

勾上就可以调试了把。上面那个应该是热更新编译的慢。一种是把代码多打包到npm里面去，mfsu就会快了。一种是开启webpack5的lazyCompilation。

**Comment by furylee** [comment]
引入新的antd组件,或者加入新的包,总是提示找不到对应的module或者less,必须要删掉.umi重新启动才行,大家有遇到吗?

**Comment by yuzhigang** [comment]
茫茫多的问题：

1. mfsu开启后，SettingDraw.tsx里有一段 required的语法，吐警告：
`[MFSU] require('/Users/zigzag/Sovi/sovi-frontend/node_modules/umi-plugin-setting-drawer/lib/layout/index.js') found in /Users/zigzag/Sovi/sovi-frontend/src/.umi/plugin-setting-drawer/SettingDrawer.tsx, which will broken the MFSU prebuild match, please change to esm module import.`
2. 修改config.ts里的less变量一会有效果一会没有，猜想是缓存问题。
3. 第一次start速度很慢，稍微改个config.ts又是半天。热更新倒是很快。
4. antd design pro 的模板里有很多错误，不手动修改有些页面出不来。比如： 'ignorItemProps'属性不识别。

**Comment by Newbit13** [comment]
> ![image](https://user-images.githubusercontent.com/8001457/129151626-6b921111-7e9f-40bf-acde-d03b0ea9234d.png)
> 
> chrome devTools settings 这个勾了试试

开启禁用后有什么影响吗

**Comment by little-fafa** [comment]
> ![image](https://user-images.githubusercontent.com/8001457/129151626-6b921111-7e9f-40bf-acde-d03b0ea9234d.png)
> 
> chrome devTools settings 这个勾了试试

貌似有用，感谢❤️❤️💕

**Comment by xiaoquanquanxin** [comment]
> ![image](https://user-images.githubusercontent.com/8001457/129151626-6b921111-7e9f-40bf-acde-d03b0ea9234d.png)
> 
> chrome devTools settings 这个勾了试试

天呐，你是天你是光，你是唯一的神话

**Comment by pleiades-embers** [comment]
> ![image](https://user-images.githubusercontent.com/8001457/129151626-6b921111-7e9f-40bf-acde-d03b0ea9234d.png)
> 
> chrome devTools settings 这个勾了试试

真的变快了很多 1min 30s ==> 10s

**Comment by linhf123** [comment]
> ![image](https://user-images.githubusercontent.com/8001457/129151626-6b921111-7e9f-40bf-acde-d03b0ea9234d.png)
> 
> chrome devTools settings 这个勾了试试

感谢大佬！

**Comment by fireMan-34** [comment]
测试了一下。关闭 msfu

**Comment by fireMan-34** [comment]
碰到相同的问题，一段读取国际化代码使用通知在写入后产生这种长时间白屏，目前也不清楚具体原因到底是什么。
总结上面的答案，目前三个处理方式。
1. 关闭 msfu 选项。
2. 关闭开发者工具异步堆栈追踪。
3. 不在打开浏览器打开页面的情况下刷新页面不会触发白屏。
