### ISSUE TITLE
@umijs/plugin-access不能隐藏菜单

### ISSUE THREAD

**Issue by sandercage** [umijs/umi#7154]
## What happens?

使用@umijs/plugin-access 控制路由对应的页面的权限时，如果该路由对应的菜单的access字段值设置为 src/access.ts 中value设置为false的key时，访问页面可以看到403页面， 但菜单不吟隐藏。

## Mini Showcase Repository(REQUIRED)

https://github.com/sandercage/scaffold-pc.git

## How To Reproduce

1. git clone https://github.com/sandercage/scaffold-pc.git
2. cd  scaffold-pc && yarn
3. yarn dev
4. 打开http://localhost:8000/module2/c

期望 ：module2/c 对应的页面访问时为内容为403， 同时它对应的菜单被隐藏
实际： module2/c 对应的菜单仍然存在

## Context

```
"@ant-design/pro-layout": "^6.23.0",
"antd": "^4.16.10",
"classnames": "^2.3.1",
"dayjs": "^1.10.6",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"umi": "^3.5.14"

"@umijs/plugin-access": "^2.4.2",
"@umijs/plugin-antd": "^0.10.0",
"@umijs/plugin-initial-state": "^2.4.0",
"@umijs/plugin-layout": "^0.17.2",
"@umijs/plugin-model": "^2.6.1",
```

**Comment by beatlesD** [comment]
你好，我也遇到了一样的问题，请问你解决了么

**Comment by HeiShuXianSheng** [comment]
> 你好，我也遇到了一样的问题，请问你解决了么

请问你解决了吗？

**Comment by zhouzyc** [comment]
插个眼

**Comment by HeiShuXianSheng** [comment]
> 请问你解决了吗？

我是因为根组件的Provider出问题了，解决后：
`export const rootContainer = (
  container: React.ReactNode,
) => {
  const Provider = ({ children, routes }: any) => {
    const newChildren = React.cloneElement(children, {
      ...children.props,
      routes,
    });

    return <ApolloProvider client={apolloClient}>{newChildren}</ApolloProvider>;
  };

  return React.createElement(Provider, null, container);
};`

**Comment by hong418884611** [comment]
你好我也遇到这个问题，发现在access.ts设置的function没有被触发，后面修改config加上access: {
    strictMode: true,
  },这个之后才能权限控制，但是这个我开始是不用加的，加了之后我每个路由都要写权限

**Comment by hong418884611** [comment]
设置access: {
    strictMode: false
  },要写上，不写控制不了

**Comment by zjfresh** [comment]
查一下午，结果最后发现已经发布的 @umijs/preset-react@2.1.3 已解决，pnpm upgrade 竟然只到 2.1.2，不然在那个 说要配config.js 里 access:{} （这个方法是错的），报错问题那要升级，直接到到2.1.3，这问题也就顺便解决了……浪费时间
