### ISSUE TITLE
@umijs/plugin-access 插件为何一定要依赖 initial-state 和 model 插件呢 ？

### ISSUE THREAD

**Issue by sandercage** [umijs/umi#7156]
最近在开发一个PC项目时， 基于umi相关技术栈搭建了一套， 由于是小型项目所以希望引入更少的依赖。

目前只依赖了@umijs/plugin-layout 来快速完成项目外框架， 由于涉及到菜单、页面的权限控制，自然而然的引入了@umijs/plugin-access以期用简单方式可以搞定。 却发现@umijs/plugin-acces 又依赖了 initial-state 和 model 两个插件。 这其实是我不希望看到的。 因为按照@umijs/plugin-acces 的方式，对于在 src/access.ts 中生成权限配置时依赖的数据， 我并不希望从initial-state中获取数据， 而是我从接口， 项目中或已有的轻量级状态管理库等方式中获取。

个人觉得@umijs/plugin-acces 可以独立于其他插件来与@umijs/plugin-layout配合实现简单的权限控制。 而不用为了这样一个简单需求引入其他插件依赖。 plugin-acces依赖的数据应该由用户自主选择。

以上是我的浅见， 望大神指正。

**Comment by xiaohuoni** [comment]
其实是为了获取的初始化的用户权限数据，所以需要 `initial-state`。
而要使用 `initial-state`，需要 useModel

**Comment by sandercage** [comment]
> 其实是为了获取的初始化的用户权限数据，所以需要 `initial-state`。
> 而要使用 `initial-state`，需要 useModel

这点我充分理解到了。实际上个人认为 **@umijs/plugin-acces** 为了获取的初始化的用户权限数据不一定非要依赖**init-state**是吧？比如直接依赖服务端提供的权限接口返回的数据， dva的数据等等是吧。 让使用者自己决定是否更好？这样  **@umijs/plugin-access** 的依赖更少，更加独立你说是吧？

**Comment by zpaimon** [comment]
plugin-access 不是异步函数啊
