### ISSUE TITLE
mfsu 开启后antd样式加载错误

### ISSUE THREAD

**Issue by ALL-STACK** [umijs/umi#7157]
## What happens?
mfsu 开启后antd样式加载错误
![image](https://user-images.githubusercontent.com/24264872/129126334-16ec92e8-c4e8-44a3-a6fa-a513d24f5e9e.png)

## How To Reproduce
https://github.com/ALL-STACK/umi-latest-Demo.git

## Context

- **Umi Version**:  v3.5.15
- **Node Version**: v12.18.3
- **Platform**: chrome

**Comment by zdQAQ** [comment]
any progress?
