### ISSUE TITLE
Github Pages server returns 404.

### ISSUE THREAD

**Issue by codetopper** [umijs/umi#7158]
### Discussed in https://github.com/umijs/umi/discussions/7152

<div type='discussions-op-text'>

<sup>Originally posted by **codetopper** August 11, 2021</sup>
![image](https://user-images.githubusercontent.com/57386096/128970682-e3a00989-5f39-4c91-93b7-0b1c7d3fd0c3.png)
</div>

**Comment by codetopper** [comment]
Hi, please check out the following link!
https://github.com/codetopper/stonksweb/tree/gh-pages

> Hello @codetopper. In order to facilitate location and troubleshooting, we need you to provide a realistic example. Please forking these link [codesandbox umi](https://codesandbox.io/s/umi-2d4js?file=/src/pages/index.tsx) or using `yarn create @umijs/umi-app` to create and upload it to your GitHub repository.
> 
> 你好 @codetopper, 为了方便定位和排查问题，我们需要你提供一个重现实例，请提供一个尽可能精简的链接 [codesandbox umi](https://codesandbox.io/s/umi-2d4js?file=/src/pages/index.tsx) 或使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

**Comment by xrkffgg** [comment]
你部署到哪里的？

**Comment by codetopper** [comment]
@xrkffgg github pages

**Comment by xrkffgg** [comment]
要设 `base` `publicPath`

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi-plugin-gh-pages
