### ISSUE TITLE
发布到动态非根目录的问题，已修改好，测试没问题，我很快上传代码

### ISSUE THREAD

**Issue by niaoge** [umijs/umi#716]
发布到动态非根目录的问题，特别是当前项目作为一个大项目的子项目发布时很有用，已修改好，测试没问题了，我在研究一下怎么修改源代码上传，应该很快就上传代码

**Comment by xiaohuoni** [comment]
我很好奇，问题是什么🤔

**Comment by sorrycc** [comment]
没理解是啥问题。。
