### ISSUE TITLE
[Bug] mf-va_remoteEntry.js:2 Uncaught (in promise) ChunkLoadError: Loading chunk mf-dep_vendors failed.

### ISSUE THREAD

**Issue by renwangT** [umijs/umi#7164]
![企业微信截图_16288175281006](https://user-images.githubusercontent.com/30031959/129291379-055575aa-46be-4b1b-b217-5c769f1e10d2.png)

开启 msfu 后，启动成功，浏览器报这个错？ 

哪位大佬遇到过， 怎么解决的嘞？

**Comment by miroku-y** [comment]
应该是定义了publicPath 导致的

**Comment by hong418884611** [comment]
同样的问题

**Comment by ZengJun-cloud** [comment]
> 应该是定义了publicPath 导致的

那打包咋解决呀？

**Comment by hong418884611** [comment]
![image](https://user-images.githubusercontent.com/25003355/146305803-e1a56e14-603b-4f65-9f7e-726cb1cdb496.png)
这里隐藏就好了

**Comment by ZengJun-cloud** [comment]
> ![image](https://user-images.githubusercontent.com/25003355/146305803-e1a56e14-603b-4f65-9f7e-726cb1cdb496.png) 这里隐藏就好了

我没有用分包 - -

**Comment by ZengJun-cloud** [comment]
开启了msfu就会报错，不开启就正常的

**Comment by ONEGISER** [comment]
> 开启了msfu就会报错，不开启就正常的

有办法解决吗？

**Comment by lefeye** [comment]
> 开启了msfu就会报错，不开启就正常的

确实，关闭mfsu就不会报错了，但是编译速度慢了很多。右办法解决吗
