### ISSUE TITLE
Uncaught (in promise) Error: Module "./antd/es/notification/style" does not exist in container. while loading "./antd/es/notification/style" from webpack/container/reference/mf[Bug] say something

### ISSUE THREAD

**Issue by MachoManCk** [umijs/umi#7165]
项目中使用了umi/qiankun，主应用采用的ant-design-pro v5,运行的时候开启了  **mfsu: {},**  报错Uncaught (in promise) Error: Module "./antd/es/notification/style" does not exist in container. while loading "./antd/es/notification/style" from webpack/container/reference/mf[Bug] say something

**Comment by MachoManCk** [comment]
主应用config.ts

`// https://umijs.org/config/
import { defineConfig } from 'umi';
import { join } from 'path';

import defaultSettings from './defaultSettings';
import proxy from './proxy';
import routes from './routes';

const { REACT_APP_ENV } = process.env;

export default defineConfig({
  hash: true,
  antd: {},
  dva: {
    hmr: true,
  },
  layout: {
    // https://umijs.org/zh-CN/plugins/plugin-layout
    locale: false,
    siderWidth: 208,
    ...defaultSettings,
  },
  // https://umijs.org/zh-CN/plugins/plugin-locale
  locale: {
    // default zh-CN
    default: 'zh-CN',
    antd: true,
    // default true, when it is true, will use `navigator.language` overwrite default
    baseNavigator: true,
  },
  dynamicImport: {
    loading: '@ant-design/pro-layout/es/PageLoading',
  },
  targets: {
    ie: 11,
  },
  // umi routes: https://umijs.org/docs/routing
  routes,
  // Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme: {
    'primary-color': defaultSettings.primaryColor,
  },
  // esbuild is father build tools
  // https://umijs.org/plugins/plugin-esbuild
  esbuild: {},
  title: false,
  ignoreMomentLocale: true,
  proxy: proxy[REACT_APP_ENV || 'dev'],
  manifest: {
    basePath: '/',
  },
  // Fast Refresh 热更新
  fastRefresh: {},
  openAPI: [
    {
      requestLibPath: "import { request } from 'umi'",
      // 或者使用在线的版本
      // schemaPath: "https://gw.alipayobjects.com/os/antfincdn/M%24jrzTTYJN/oneapi.json"
      schemaPath: join(__dirname, 'oneapi.json'),
      mock: false,
    },
    {
      requestLibPath: "import { request } from 'umi'",
      schemaPath: 'https://sandbox.api-v2.mdlr8.com/doc/swagger.json',
      projectName: 'swagger',
    },
  ],
  nodeModulesTransform: { type: 'none' },
  webpack5: {},
  exportStatic: {},
  mfsu: {},
  qiankun: {
    // qiankun.master.apps 配置了子应用的唯一名称，及入口 html 地址
    master: {
      apps: [{
        name: 'activity',
        entry: 'http://localhost:3000'
      }],
      sandbox:true
    },
  },
});
`

**Comment by MachoManCk** [comment]
![image](https://user-images.githubusercontent.com/34299788/129324415-bddcc6ac-baf7-4904-b32b-e0b20a68f532.png)

**Comment by annieh12** [comment]
我也遇到同样的问题，我在routes里加icon就会报这样的错
![image](https://user-images.githubusercontent.com/13465448/129856178-b0e24c3b-527f-4e63-94c7-01f1a4474bec.png)
{
	  path: '/myCall',
	  name: 'myCall',
	  icon: 'phone',   // <--- 就是这个
	  component: './TableList',
},
我的umi:^3.5.0，antd:^4.16.11，但我用的是ant-design-pro v4

**Comment by MachoManCk** [comment]
删除config.js里的mfsu

**Comment by annieh12** [comment]
> 删除config.js里的mfsu

嗯，有效。谢谢了！

**Comment by MachoManCk** [comment]
你们有用qiankun吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月18日(星期三) 下午4:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [umijs/umi] Uncaught (in promise) Error: Module &quot;./antd/es/notification/style&quot; does not exist in container. while loading &quot;./antd/es/notification/style&quot; from webpack/container/reference/mf[Bug] say something (#7165)





  
删除config.js里的mfsu
  
嗯，有效。谢谢了！
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by doubleLLL3** [comment]
如果想继续使用msfu，可以尝试删除src下的.umi，重新运行即可

**Comment by MachoManCk** [comment]
thank you
