### ISSUE TITLE
chainWebpack自定义loader和plugins问题

### ISSUE THREAD

**Issue by beyong** [umijs/umi#7168]
场景： 启用mfsu后，dev模式下html head中css文件全部是link方式引入，出现的问题是：
1、ant-design-pro样式和antd组件样式重复引用
2、顺序的不同导致组件样式和ant-design-pro覆盖

尝试关闭mfsu一切正常(生成了umi.css一个文件)

目前想尝试通过chainWebpack方法改变loader和plugins 将生成一个css文件，webpack配置如下

chainWebpack看了官方文档后此方法摸不着头脑，希望得到解决

@sorrycc

**Comment by luojiong** [comment]
请问你的问题解决了吗 我也碰到了同样的问题

**Comment by beyong** [comment]
@luojiong 没有解决

**Comment by luojiong** [comment]
好吧 我已经在使用 create-react-app了 umi似乎不太适合我
