### ISSUE TITLE
[Bug] "export 'utils' was not found in 'umi'

### ISSUE THREAD

**Issue by himanhimao** [umijs/umi#7169]
代码中引入utils报错 版本3.5.17
import { Link, utils}from 'umi' 

报错 export 'utils' was not found in 'umi'

devtools: " 'umi' does not contain an export named 'utils'

**Comment by himanhimao** [comment]
什么情况啊

**Comment by PeachScript** [comment]
`utils` 是 Node 侧的导出，通常用于辅助 Umi 插件开发，不能用在浏览器侧

**Comment by himanhimao** [comment]
有些库可以用啊，我还是继续使用了 而且文档里说明可以用啊

**Comment by himanhimao** [comment]
> `utils` 是 Node 侧的导出，通常用于辅助 Umi 插件开发，不能用在浏览器侧

有些库客户端可以用啊 我直接用了 比如import clipboardy from '@umijs/deps/reexported/clipboardy';

**Comment by PeachScript** [comment]
<img width="465" alt="图片" src="https://user-images.githubusercontent.com/5035925/129506446-5ec2a637-c07e-4b65-babe-fcd80ae9cb4a.png">
