### ISSUE TITLE
发布到动态非根目录

### ISSUE THREAD

**Issue by niaoge** [umijs/umi#717]
通常，为节约资源成本，在jboss或tomcat容器（容器的目的是保证前后端代码配合一致,也可以避免诸如跨域等问题）中布置多个项目，以根目录的文件名区分，这个工作由运维维护的，开发人员开发时并不知道和关心根目录是什么，这个根目录不能写入前端代码中，否则开发时即绑死(类似的问题还有数据库密码，取支付款凭证)，这个根目录就叫动态非根目录，我现在上传有代码就是解决这个问题，达到项目任意发布到非根目录（或者多级目录）下可以运行

**Comment by sorrycc** [comment]
It's supported in umi@2 .
