### ISSUE TITLE
umi如何接入父应用为single-spa的微前端

### ISSUE THREAD

**Issue by librajt** [umijs/umi#7177]
### Discussed in https://github.com/umijs/umi/discussions/6223

<div type='discussions-op-text'>

<sup>Originally posted by **yjp1105286534** March  7, 2021</sup>
umi是子项目接入，不能用qian-kun这个插件  因为父应用使用的single-spa来实现的 里面有很多子项目都是这个方案 ，umi有咩有可能使用single-spa-react呢</div>

**Comment by theecn** [comment]
ice 了解下

**Comment by librajt** [comment]
写了个简易插件，代码基本是这样，不够通用，只是调试代码顺通了逻辑
抛砖引玉，欢迎讨论

umi-plugin-single-spa-react.js

    export default api => {
    
        api.addEntryCode(
            () => `
    import React from 'react';
    import ReactDOM from 'react-dom';
    import singleSpaReact from 'single-spa-react';
    let reactLifecycles;
    reactLifecycles =  singleSpaReact({
        React,
        ReactDOM,
        loadRootComponent: () => Promise.resolve(clientRender),
    });
    `,
        );
    
        api.addEntryCode(
            () => `
    export const bootstrap = [
        reactLifecycles.bootstrap,
    ];
    window.g_umi.bootstrap = bootstrap;
    
    export const mount = [
        reactLifecycles.mount,
    ];
    window.g_umi.mount = mount;
    
    export const unmount = [
        reactLifecycles.unmount,
    ];
    window.g_umi.unmount = unmount;
    `,
        );
    };



/src/app.tsx
    
    const isSubApp = 'condition when is sub app';
    export function modifyClientRenderOpts(memo: any) {
        return {
            ...memo,
            rootElement: isSubApp ? '' : memo.rootElement,
        };
    }
