### ISSUE TITLE
反向代理设置

### ISSUE THREAD

**Issue by wingsico** [umijs/umi#719]
umi 如何进行反向代理，比如 '/api' 代理到 'http://www.xxx.com/api'

**Comment by sorrycc** [comment]
参考 https://umijs.org/config/#proxy

**Comment by timmyz** [comment]
> 参考 https://umijs.org/config/#proxy

@sorrycc 我想这位兄是想知道生产部署如何代理，能介绍下么？

**Comment by concefly** [comment]
umi 代理是方便本地开发，生产部署不能依赖它

**Comment by timmyz** [comment]
我觉得proxy那一章节可以介绍下build以后生产部署的方案，比如结合nginx是一种方案，用express等框架似乎也能实现，但具体细节还要摸索，如果脚手架中能有参数配置可以与express结合就太棒了
