### ISSUE TITLE
[Bug] ant pro 自定义组件后会导致页面无法热更新，mfsu: {},关闭是可以更新的

### ISSUE THREAD

**Issue by codedart2018** [umijs/umi#7193]
## What happens?

一些自定义组件。然后在别的地方调用，功能正常，就是间歇性无法热更新。有可能A页面调用不更新，但是B页面调用又更新。但只要不调用一切又正常会自动热更新它。控制台也不报错，完全摸不着头脑是因为什么问题导致不更新的。排查都没得办法排查。哪怕是写一个简单的 <div>123</div>的组件都可能导致无法热更新
尝试注释上　// @refresh reset　这个也不生效。好歹有个报错什么的。这样子我才知道哪里的问题呀！

下面提供一个简单的示例组件
```
import React from 'react';
import { Form } from 'antd';
import { CusFormProps } from '@/components/CusForm/data';
import CusFormFooter from './CusFormFooter';

// @refresh reset
const CusForm: React.FC<CusFormProps> = (props) => {
  const { form, fixedFooter, children, ...other } = props;

  return (
    <Form form={form} {...other}>
      {children}
      {fixedFooter && <CusFormFooter form={form} />}
    </Form>
  );
};

export default CusForm;
```

就这样我实在没看出哪里写的不对，哪里有问题之类的。

后面折腾了很久，我把　mfsu: {},　注释掉了，哪里引入它都热更新，就是慢一点。屏幕抖动一点。证明代码是没有问题的。能正常运行，能热更新，就是加上　mfsu　之后就会间歇性的不更新。

    "umi": "^3.5.0",
    "umi-serve": "^1.9.10",

**Comment by codedart2018** [comment]
早上我对比下刷新加载的js和更改后加载的js。通过js来看是输出了变更的内容，但浏览器就是没有刷新。不知道为什么、
```
"src/pages/merchant/setting/settlement/index.tsx",
      title: "结算设2222置",
      headerBordered: true,
      children: /*#__PURE__*/_jsxDEV(_components_CusForm__WEBPACK_IMPORTED_MODULE_1
```

```
"src/pages/merchant/setting/settlement/index.tsx",
      title: "结算设置111",
      headerBordered: true,
      children: /*#__PURE__*/_jsxDEV(_components_CusForm__WEBPACK_IMPORTED_MODULE_1
```

**Comment by majian159** [comment]
+1

**Comment by liruiqiang666** [comment]
+1

**Comment by cike8899** [comment]
+1 手动刷新都没效果

**Comment by JamieMing** [comment]
我已经折腾了两天，只要是用上两个自己写的组件，热更新立马失效，只保留一个刷新以后就能恢复热更新。莫名其妙的。
`
import MessageCard from '../Main/components/MessageCard'

import PersonInfoCard from '../Main/components/PersonInfoCard'

const Test = () => {
    // @refresh reset
    return (
        <div>
            12345123
            <MessageCard />
            <PersonInfoCard />
        </div>
    )
}
export default Test

`
`
const MessageCard = () => {
    return (
        // <Card>
        <div>MessageCard12</div>
        // </Card>
    )
}
export default MessageCard
`
`
const PersonInfoCard = () => {
    // const { initialState } = useModel('@@initialState')
    return (
        <div className={styles.content}>
            <div className={styles.subDesc}>祝你开心每一天</div>
        </div>
    )
}
export default PersonInfoCard`
就这样，热更新都是会失效的，

**Comment by codedart2018** [comment]
> 我已经折腾了两天，只要是用上两个自己写的组件，热更新立马失效，只保留一个刷新以后就能恢复热更新。莫名其妙的。
> `
> import MessageCard from '../Main/components/MessageCard'
> 
> import PersonInfoCard from '../Main/components/PersonInfoCard'
> 
> const Test = () => {
> // @refresh reset
> return (
> 
> 12345123
> 
> 
> 
> )
> }
> export default Test
> ` `
> const MessageCard = () => {
> return (
> //
> MessageCard12
> 
> //
> )
> }
> export default MessageCard
> ` `
> const PersonInfoCard = () => {
> // const { initialState } = useModel('@@initialstate')
> return (
> 
> 祝你开心每一天
> 
> 
> )
> }
> export default PersonInfoCard`
> 就这样，热更新都是会失效的，

我现在都是command + r 先不管它了。开发着走吧

**Comment by JamieMing** [comment]
基本上，只要引入两个自定义组件，再同时使用，就会出问题，如果没出问题刷新一下就一定能出现，除非在父组件内部创建一个组件，但是就没啥意义了，mfsu这东西bug也太多了

**Comment by JamieMing** [comment]
心累，还是关掉mfsu算了，省下来的编译时间，还不够cmd R浪费的时间

**Comment by Timlcy** [comment]
+1热更新不了

**Comment by ifmos** [comment]
> > 心累，还是关掉mfsu算了，省下来的编译时间，还不够cmd R浪费的时间
> 
> 我是没有关，主要是关闭后抖动厉害，有的简单页面用它还是比较好的。等他们修复吧

亲测在`config`里面把 mfsu和webpack5同时注释就不会抖动了，不过重启就会慢很多

**Comment by beginnerJq** [comment]
+1

**Comment by zdouble** [comment]
和文件大小写有关

**Comment by codedart2018** [comment]
> 和文件大小写有关

绝对不是这个文件大小写有问的

**Comment by mastercbhw** [comment]
关注一下~ +1

**Comment by yuyic** [comment]
+1

**Comment by JamieMing** [comment]
> +1

官方不管，这种程度的问题，普通开发者也提不出能解决问题的pr，晾着吧

**Comment by yituxiu** [comment]
+1

**Comment by LilianShi** [comment]
我这边遇到的问题是：加上运行时配置相关动态路由功能，配置mfsu，webpack就不定期间隔1分钟左右（间隔时间不定）就重新编译下，界面刷新下，注释掉mfsu，就没有这个问题。这个不知道大家有没有遇到过，有没有解决方案

**Comment by TangDeYu** [comment]
+1

**Comment by xueerli** [comment]
+1

**Comment by 571881145** [comment]
+1

**Comment by handycode** [comment]
这个 bug 已经很久了， 还是没有修复。 我已经放弃新项目中使用 umi, 切换回 next 了

**Comment by Zwahxf** [comment]
+1

**Comment by qianZir** [comment]
+1
