### ISSUE TITLE
[Feature Request]  增加 devServer 的配置项来支持 headers 的设置

### ISSUE THREAD

**Issue by jaspertian** [umijs/umi#7195]
## Background

UMI 版本： 3.5.17

 目前的 config 中对于 devServer 的配置项需增加对 headers 的支持。

## Proposal

开发环境中，为简化跨域问题，需要设置 Access-Control-Allow-Origin 等信息，但目前 umi 中无论如何设置都不能生效，包括 chainWebpack 方式。

## Additional context

或者，设置 devServer 默认允许跨域访问。

**Comment by jdfdcc** [comment]
怎么解决的啊？
