### ISSUE TITLE
[Bug] 在配置表中define的变量如何在代码中消除ts警告

### ISSUE THREAD

**Issue by Jay-G2017** [umijs/umi#7196]
## What happens?

现象: 在配置表中define的变量, 在代码中使用时会有ts的警告.

期望: 有没有办法能够消除ts的警告.

```
export default {
  define: {
    SITE_NAME: 'bar',
  },
};
```
<img src="https://user-images.githubusercontent.com/28147625/130194165-b5aafe5c-034d-4006-8225-1f648b6d6077.jpg"  width=600 />

**Comment by wansuiasdn** [comment]
同问

**Comment by PeachScript** [comment]
https://stackoverflow.com/questions/12709074/how-do-you-explicitly-set-a-new-property-on-window-in-typescript
