### ISSUE TITLE
[Bug] 3.4.22升级最新版本后，怀疑在app.ts前执行的组件运行时umi没有初始化，导致前面的组件引入umi的api报错

### ISSUE THREAD

**Issue by Indomi** [umijs/umi#7201]
### Discussed in https://github.com/umijs/umi/discussions/7200

<div type='discussions-op-text'>

<sup>Originally posted by **Indomi** August 20, 2021</sup>
> 背景是我升级了最新版，开发环境启动以后，报`Object(...) is not a function`错误，查了一下是组件内引入umi的dynamic为undefined

我已经尝试包括但不限于 重启IDE，删除node_modules / lock文件，安装3.4.x最后一个版本没有任何问题

然后仔细排查了下，发现这个报错的组件，是在app.ts执行前就被执行了，而3.4.x的版本引入是正常的，具体的图片如下：

1. 3.4.x的版本。async-component引入dynamic成功
![image](https://user-images.githubusercontent.com/22163049/130226399-410c232f-714b-4dac-9024-2e1e7bc58556.png)
2. 新装版本3.5.17，async-component引入dynamic为undefined
![image](https://user-images.githubusercontent.com/22163049/130226501-2324a8f6-5a43-467a-857a-1b4bae6f424b.png)

所以我现在比较懵，可不可以提供一下思路，另外为什么app.ts前还会有组件被渲染呢？

感谢
</div>

**Comment by xiaohuoni** [comment]
给个复现或者代码片段？不太清楚你在说啥？你可以试试配置 `  dynamicImportSyntax: {},`

**Comment by knoxnoe** [comment]
有解决办法吗？同样遇到这类问题，umi 3.4.22 -> 3.5.20
