### ISSUE TITLE
[Bug] 求解: 想要在 request.ts 中获取到getInitialState 返回的初始数据

### ISSUE THREAD

**Issue by jiujiaonuannan** [umijs/umi#7202]
## What happens?

对request 函数二次封装 但是需要用到getInitialState 函数中的初始数据才行
useModel 和 useDispatch 均没办法使用

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by iceycc** [comment]
我也想

**Comment by WheelerLee** [comment]
有解决办法没
