### ISSUE TITLE
[Bug] umi site cannot achived

### ISSUE THREAD

**Issue by postbird** [umijs/umi#7209]
## What happens?

- https://umijs.org/
- https://d.umijs.org/

site cannot achived，does anyone have the same problem? 

![image](https://user-images.githubusercontent.com/16200574/130385570-e32e81df-646a-4564-9ef6-12cd0d24561d.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaohuoni** [comment]
可以临时访问一下这个链接。https://umijs.vercel.app/

**Comment by PeachScript** [comment]
Cannot reproduce this problem, please check your network, issue closed
