### ISSUE TITLE
[Bug] 开启mfsu后浏览器报错：jsonpScript is not defined

### ISSUE THREAD

**Issue by liyaxuanliyaxuan** [umijs/umi#7212]
## What happens?
开启mfsu后浏览器报错：jsonpScript is not defined
![image](https://user-images.githubusercontent.com/44548177/130545838-e11d08b2-8611-411c-a6b6-f867c527acdc.png)

![image](https://user-images.githubusercontent.com/44548177/130545770-4a06637c-c21a-480e-989b-d54320b00f46.png)

## 相关配置
`const config: IConfig = {
  history: { type: 'hash' },
  exportStatic: false,
  mountElementId: 'app',

  // ref: https://umijs.org/plugin/umi-plugin-react.html

  antd: {
    dark: false,
  },
  dva: {
    immer: true,
  },
  title: '资源库',
  dynamicImport: {},

  routes,
  alias: {
    '@': path.resolve(__dirname, './src'),
  },

  chainWebpack: umiChainWebpack,
  extraBabelPlugins: ['babel-plugin-styled-components'],
  externals: externals,
  theme,
  devServer: devServerConfig,
  proxy,
  webpack5: {},
  mfsu: {},
};`

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:3.5.17
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
如果确定是 mfsu 开启后的问题，需要给复现。

**Comment by chzng** [comment]
我也遇到同样的错误

**Comment by chzng** [comment]
太多太多太多人反馈这个mfsu开启的问题了，肯定有问题

**Comment by liyaxuanliyaxuan** [comment]
升级umi3的相关记录

1. 版本修改并安装

   1.  umi
   2. @umi-plugin-react

2. 修改.umirc.ts配置

   npm start产生报错

   ![image-20210824170313061](/Users/liyaxuan/Library/Application Support/typora-user-images/image-20210824170313061.png)

   安装alife-logger后无报错

3. webpack 打包运行正常

   1. 若不使用mfsu

      ![image-20210824170805332](/Users/liyaxuan/Library/Application Support/typora-user-images/image-20210824170805332.png)

      https://localhost:1024 可以正常访问

   2. 若开启

      ![image-20210824171014287](/Users/liyaxuan/Library/Application Support/typora-user-images/image-20210824171014287.png)

      ![image-20210824171116259](/Users/liyaxuan/Library/Application Support/typora-user-images/image-20210824171116259.png)

      **浏览器报错**：**jsonpScriptSrc is not defined**

      ![image-20210824171159667](/Users/liyaxuan/Library/Application Support/typora-user-images/image-20210824171159667.png)

      webpack运行正常

4. 目前配置如下：

   ```typescript
   export default defineConfig({
     history: { type: 'hash' },
     exportStatic: false,
     mountElementId: 'dingapp',
   
     // ref: https://umijs.org/plugin/umi-plugin-react.html
   
     antd: {
       dark: false,
     },
     dva: {
       immer: true,
     },
     title: '资源库',
     dynamicImport: {},
     nodeModulesTransform: {
       type: 'none',
     },
     routes,
     alias: {
       '@': path.resolve(__dirname, './src'),
     },
   
     chainWebpack: umiChainWebpack,
     extraBabelPlugins: ['babel-plugin-styled-components'],
     externals: externals,
     theme,
     devServer: devServerConfig,
     proxy,
     mfsu: {},
     // webpack5: {},
   });
   
   ```

**Comment by liyaxuanliyaxuan** [comment]
> 我也遇到同样的错误

你也是升级后开启吗？

**Comment by sorrycc** [comment]
@liyaxuanliyaxuan 

两个问题，

1. chainWebpack 里的处理不要针对 mfsu 生效，

```diff
- const umiChainWebpack: IConfig['chainWebpack'] = (config) => {
+ const umiChainWebpack: IConfig['chainWebpack'] = (config, { mfsu }) => {
+   if (mfsu) return;
```

2. [alife-logger@1.8.11](https://unpkg.com/browse/alife-logger@1.8.11/package.json) 里的 exports 属性有问题，他们已在 1.8.30 里修复了，需要做的是推动 @ali/we-logger 升级前者到依赖

**Comment by sorrycc** [comment]
@chzng 你肯定不是**相同**问题。

**Comment by sorrycc** [comment]
> 太多太多太多人反馈这个mfsu开启的问题了，肯定有问题

有 bug，但基本都不是关键 bug，内网 700+ 项目在用。

**Comment by liyaxuanliyaxuan** [comment]
感谢 @sorrycc 。目前删除 chainwebpack 的配置，项目运行正常，浏览器无报错。但是增加 chainWebpack 对

> @liyaxuanliyaxuan
> 
> 两个问题，
> 
> 1. chainWebpack 里的处理不要针对 mfsu 生效，
> 
> ```diff
> - const umiChainWebpack: IConfig['chainWebpack'] = (config) => {
> + const umiChainWebpack: IConfig['chainWebpack'] = (config, { mfsu }) => {
> +   if (mfsu) return;
> ```
> 
> 1. [alife-logger@1.8.11](https://unpkg.com/browse/alife-logger@1.8.11/package.json) 里的 exports 属性有问题，他们已在 1.8.30 里修复了，需要做的是推动 @ali/we-logger 升级前者到依赖

感谢 @sorrycc 。目前删除 chainwebpack 的配置，项目运行正常，浏览器无报错。但是增加 chainWebpack 配置，按照上面的修改方式，还是会产生同样的报错。
