### ISSUE TITLE
[Bug] 使用 msfu之后，低版本的umi-plugin-keep-alive会报错

### ISSUE THREAD

**Issue by DanileQin** [umijs/umi#7216]
项目原来的：keep-alive的版本如下：
"umi-plugin-keep-alive": "0.0.1-beta.16",

会报问题：react: Invalid hook call. Hooks can only be called inside of the body of a function component这个问题。

修复方案：
将其升级到 ”0.0.1-beta.29“ ： "umi-plugin-keep-alive": "0.0.1-beta.29", 则好使用。

1、问题一：请问这块对于keep-alive是做了什么改变或者之前有问题的原理是什么？
2、问题二：官网提供的解决办法“在 ANALYZE=1 umi dev 启动项目时，可以判断项目是否在 node_modules 中引入 React。如果是，需要尝试修改引入语句。”。这句你没看懂，判断它是否在node_modules有什么关系，以及要如何修改引入语句。

**Comment by PeachScript** [comment]
请到插件对应仓库提交 issue：https://github.com/alitajs/umi-plugin-keep-alive
