### ISSUE TITLE
msfu 添加 production 之后，build会报错.

### ISSUE THREAD

**Issue by DanileQin** [umijs/umi#7217]
配置信息：
在config.ts 中：
  mfsu: {
    production: {}
  },

报错信息：
![image](https://user-images.githubusercontent.com/34501848/130562614-13db7c46-657c-4a02-bf85-c2d7298f6e57.png)

**Comment by ILuZhangKun** [comment]
因为生成的是本地路径。。。把/node_modules之前的改成$CWD$，试一试。

**Comment by jiasijiamn** [comment]
可以具体说下怎么改才不是生成本地路径吗？ 
/node_modules之前的路径是项目本地路径，要怎么改成$CWD$呢？

**Comment by jiasijiamn** [comment]
> 因为生成的是本地路径。。。把/node_modules之前的改成$CWD$，试一试。

可以具体说下怎么改才不是生成本地路径吗？
/node_modules之前的路径是项目本地路径，要怎么改成$CWD$呢？

**Comment by florencemu** [comment]
我也这样 楼主怎么解决的
