### ISSUE TITLE
antd按需加载问题

### ISSUE THREAD

**Issue by wingsico** [umijs/umi#722]
## 我遇到了什么？
在引入 `ant-design-pro` 中 `Login` 组件，使用其中的 `UserName` 和 `Password` 组件时，其内部使用的 `Input` 的样式无法加载出来，`Submit` 组件样式正常。

## 我的发现
当我主动 `import { Input } from 'antd'`，并且在 `render`中用上 `Input` 组件，`UserName` 和 `Password` 组件样式渲染正常

## 疑问
一下没搞清楚是 `antd-pro` 的问题还是 `umi`的问题，所以先到这边问一下。

**Comment by chenshuai2144** [comment]
pro的问题，你用的 pro包版本？

**Comment by wingsico** [comment]
@chenshuai2144 
"ant-design-pro": "^2.0.0-beta.2",
