### ISSUE TITLE
[Bug] 项目路由配置access不生效

### ISSUE THREAD

**Issue by zhouzyc** [umijs/umi#7226]
## What happens?

项目中配置路由权限控制
`
{
    path: '/tabel',
    name: '表格',
    icon: 'BarChartOutlined',
    component: '@/pages/tabel/index',
    access: 'checkMenusAuth', //验证的权限
 }
`
权限返回
`
return {
    checkMenusAuth: false,
 };
`

菜单没有隐藏

## Mini Showcase Repository(REQUIRED)

复现demo
https://gitee.com/umijs-admin-react/react-umijs-admin.git

**Comment by beatlesD** [comment]
你好，这个问题解决了么

**Comment by HeiShuXianSheng** [comment]
> 你好，这个问题解决了么

同问，请问解决了吗？？？
