### ISSUE TITLE
umi3.5.17中添加@alitajs/hd在iPhone6默认font-size为50px

### ISSUE THREAD

**Issue by Web-Delevan** [umijs/umi#7229]
plugins: ['@alitajs/hd'],
  hd: {
    'px2rem': {
      rootValue: 100
    }
  },
或者
hd: {}
在在iPhone6下都是font-size为50px

**Comment by xiaohuoni** [comment]
px2rem 的配置是传递给 `postcss-plugin-px2rem`。 font-size 仅仅根据设计稿的宽度计算得出。
这是正确的逻辑，你遇到了什么问题？

**Comment by xiaohuoni** [comment]
试试 @alitajs/hd@2.8.19 虚拟键盘弹出，页面响应 reset ，这个是之前兼容横屏模式的时候又遇到类似的问题。后来 fix 了。
我没有你这个复现环境，你试试。
