### ISSUE TITLE
[Bug] Browserslist: caniuse-lite is outdated. Please run: npx browserslist@latest --update-db

### ISSUE THREAD

**Issue by xiesantao** [umijs/umi#7238]
npm run buiild
后出现 Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

执行了npx browserslist@latest --update-db后打包还是报这个错误

**Comment by WongYuYe** [comment]
同问，从2.x升级为3.x，相关升级工作已参照https://umijs.org/zh-CN/docs/upgrade-to-umi-3修改。
在umi dev就报这个错误，并且行为一样

**Comment by liangtao-top** [comment]
这是当前 Next.js 版本 (10.0.5) 中的虚假警告。x下一个版本已经修复

**Comment by lx815** [comment]
我也出现了这个问题，但是这个警告会导致我在CI/CD的时候打包失败，这要怎么解决呢？
