### ISSUE TITLE
[Bug] 开启webpack5配置，导致mathjs引入错误

### ISSUE THREAD

**Issue by lzsheng** [umijs/umi#7239]
## Mini Showcase Repository(REQUIRED)
Module not found: Error: Can't resolve '~/demoapp/node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/esm/toConsumableArray' in '~/demoapp/node_modules/mathjs/lib/esm/expression/node'
Did you mean 'toConsumableArray.js'?
BREAKING CHANGE: The request '~/demoapp/node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/esm/toConsumableArray' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

复现仓库：
https://github.com/lzsheng/puppetter-demo/tree/bug/umi-webpack5-mathjs

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

安装依赖 yarn
启动项目yarn start

## Context

- **Umi Version**: 3.5.17
- **Node Version**: 12.22.5
- **Platform**: MacBook Pro (Intel Core i7)

**Comment by Dolov** [comment]
@sorrycc 同样遇到了这个问题，请问有处理方案么 ~

**Comment by lzsheng** [comment]
> @sorrycc 同样遇到了这个问题，请问有处理方案么 ~

@Dolov 我这边找到解决方案了，你看看是否适用 ---- [Can not resolve ..., Do you mean ... 报错](https://github.com/umijs/umi/issues/6766#issue-927966336)
方法1：需要更新相关依赖到最新，因为这个版本的依赖和 webpack5 不兼容
方法2：chainWebpack 里配上 config.module.rule('mjs-rule').test(/.m?js/).resolve.set('fullySpecified', false);

我这边是用的方法2解决了，现在能正常使用

**Comment by lzsheng** [comment]
这个issue我close掉吧~~已经找到解决方法

**Comment by ZengJun-cloud** [comment]
想要改图片的打包输出路径怎么处理啊？
