### ISSUE TITLE
MFSU 开启后启动变快，热更新速度无变化

### ISSUE THREAD

**Issue by Flyers1** [umijs/umi#7240]
![image](https://user-images.githubusercontent.com/43061006/131305949-742955fa-1b70-4440-ad69-7d4445a9d9ff.png)

**Comment by PeachScript** [comment]
refer: https://umijs.org/zh-CN/docs/mfsu#%E6%88%91%E6%AD%A3%E7%A1%AE%E5%BC%80%E5%90%AF%E4%BA%86-mfsu-%E5%90%97%EF%BC%9F

只有截图没法诊断，先根据上述文档自行排查原因，如果仍有问题需附上最小可复现仓库

**Comment by haoxinjieFE** [comment]
也遇到了这个问题，请问解决了吗
