### ISSUE TITLE
[Bug] config 设置base之后。面包屑地址多了前缀

### ISSUE THREAD

**Issue by jingxiawl** [umijs/umi#7243]
config配置base后，地址跳转正常，生成的面包屑地址多了一节前缀
![微信图片_20210830162001](https://user-images.githubusercontent.com/11657532/131309086-0c6e3378-ec7f-4a2a-a8ec-cc2316ef207a.png)

**Comment by PeachScript** [comment]
Ant Design Pro 相关问题请到对应仓库提问：https://github.com/ant-design/ant-design-pro

**Comment by jingxiawl** [comment]
？？？不是因为umi注入的router原因么？

**Comment by PeachScript** [comment]
可能性不大，router 配置如果本身有问题，Umi 应用的路由也会出错；如果确认过是 Umi 的问题，请提供最小可复现仓库
