### ISSUE TITLE
css 打包 \9 缺失

### ISSUE THREAD

**Issue by xrkffgg** [umijs/umi#7249]
当使用  `\9`

![image](https://user-images.githubusercontent.com/29775873/131433546-25afee21-dd7d-4f8d-9904-bb624e927ba2.png)

默认打包后，umi.css 中 9 缺失，导致整个 css 失效。

![image](https://user-images.githubusercontent.com/29775873/131434141-4be27871-d7c6-4dbd-bfea-eb595c47e7f2.png)

![image](https://user-images.githubusercontent.com/29775873/131434156-804efa67-32b1-40a4-bee1-345b1650a8b9.png)

可通过 `COMPRESS=none` 关闭 css 压缩

有可能是 cssnano 配置引起的

先暂时记录

**Comment by xiaohuoni** [comment]
https://github.com/cssnano/cssnano/issues/342
