### ISSUE TITLE
dispatch().then()在build之后报错

### ISSUE THREAD

**Issue by redrum1900** [umijs/umi#725]
开发环境没有问题，打包之后会有这个错误
Uncaught (in promise) TypeError: t(...).then is not a function

**Comment by xiaohuoni** [comment]
能给一个可重现的例子嘛？

**Comment by jogasa** [comment]
同样遇到一样的问题

**Comment by jogasa** [comment]
当去调用别的model里的reducer的时候，通过`.then`去处理返回的数据，就会有这样的错误发生，之前只使用dva的时候并不会有这种情况出现。
