### ISSUE TITLE
[Bug] getExportProps 在 TypeScript 中类型断言时不生效

### ISSUE THREAD

**Issue by zitudu** [umijs/umi#7255]
## Mini Showcase Repository(REQUIRED)

使用约定式路由时必须存在 `_layout` 文件才会生成嵌套菜单，如

```js
[
  ...,
  {
    component: '_layout.ts',
    routes: [...]
  },
  ...
]
```

为了添加菜单信息，同时简化 `_layout` 的编写，我通过 `_layout.ts` 传递菜单信息，而后在 `patchRoutes` 时删去 `component` 字段来保证应用正确运行（`object` 非合法的 react 组件），于是 `_layout.ts` 如下：

```typescript
import { LayoutDummy } from "@/typings";

export default {
  custom: true,
  menu: {
    name: 'THIS-IS-MENU-NAME',
  },
} as LayoutDummy;
```

app patchRoutes 如下：

```typescript
export function patchRoutes({routes}: any) {
  function t(route: any) {
    if (route.custom) {
      delete route.component
    }
    if (route.routes) {
      route.routes.forEach(t)
    }
  }
  routes.forEach(t)
}
```

但是这样并不能正确返回信息，而把类型信息去掉后可以：

```typescript
export default {
  custom: true,
  menu: {
    name: 'THIS-IS-MENU-NAME',
  },
}
```

因此判断是 `getExportProps` 在处理带类型断言的对象时没有按预期返回正确结果。

期望值：
```javascript
{
  custom: true,
  menu: {
    name: 'THIS-IS-MENU-NAME',
  },
} ;
```

实际值：`undefined`

REPL 操作如下：

```js
> const ast = require('@umijs/ast')
undefined
> ast.getExportProps(`export default {
...   custom: true,
...   menu: {
.....     name: 'THIS-IS-MENU-NAME',
.....   },
... } as any;`)
undefined
> ast.getExportProps(`export default {
...   custom: true,
...   menu: {
.....     name: 'THIS-IS-MENU-NAME',
.....   },
... };`)
{ custom: true, menu: { name: 'THIS-IS-MENU-NAME' } }
```

## Context

- @umijs/ast 版本 3.5.17

**Comment by leftstick** [comment]
没太明白，使用场景是什么，这个 `undefined` 是哪里来的？ 它和你说的 『类型断言不生效』  的关系是怎么提现的?

**Comment by leftstick** [comment]
@zitudu 模拟你这个场景太难了，提供一个可复现的repo吧

**Comment by zitudu** [comment]
> @zitudu 如果你的分析没错的话，`@umijs/ast` 这个是个小问题，我来处理下。但这个处理完是否就解决你的问题了，不好说。
> 你最好再来一个可复现的repo

感谢修复，这个结论证实过了，并且你的修复我也证实过是有效的了。可复现仓库：<https://github.com/zitudu/umi-getexportprops-ts-as>，生成的 route 中并没有将 object Merge 到 Route 对象中，将修复后的 umi Link 进去后 Merge 到了 Route中（fixed）分支。
