### ISSUE TITLE
请问build的文件名能只保留hash部分？

### ISSUE THREAD

**Issue by xjdata** [umijs/umi#726]
比如 ` static/src__pages__document__index.08706d8c.async.js `

能否修改配置 使build的结果变化为 ` static/08706d8c.async.js `

谢谢。

**Comment by xiaohuoni** [comment]
现在只支持去掉hash部分，https://umijs.org/config/#disablehash

**Comment by sorrycc** [comment]
umi@2 里已支持这种方式，umi@1 就不做新功能开发了。
