### ISSUE TITLE
多环境设置config文件不生效

### ISSUE THREAD

**Issue by houmao** [umijs/umi#7261]
## What happens?
多环境设置时使用.umirc.local.ts的方式生效，但是使用config/config.local.ts的方式会报错：
> get user config failed, undefined does not exist, but process.env.UMI_ENV is set to local.  

package.json的配置如下：
![image](https://user-images.githubusercontent.com/20122487/131777690-254de7ac-a2fb-41d5-84d7-0962b48e0401.png)
报错信息如下：
![image](https://user-images.githubusercontent.com/20122487/131777778-b85db93c-43bb-4fff-8602-74d9e75aab91.png)
config文件夹文件如下：
![image](https://user-images.githubusercontent.com/20122487/131777861-2f6a384a-4eba-4f7c-a5f8-5314fb77591a.png)

**Comment by PeachScript** [comment]
<img width="679" alt="图片" src="https://user-images.githubusercontent.com/5035925/131790414-5df5ba20-2637-497e-8cd6-226650c90aaf.png">

临时配置在本地直接生效，不需要 UMI_ENV 指定

**Comment by houmao** [comment]
那如何解决，当设置UMI_ENV时config/下的配置不生效的问题？提示如下信息：
get user config failed, undefined does not exist, but process.env.UMI_ENV is set to local.

**Comment by houmao** [comment]
> <img alt="图片" width="679" src="https://user-images.githubusercontent.com/5035925/131790414-5df5ba20-2637-497e-8cd6-226650c90aaf.png">
> 
> 临时配置在本地直接生效，不需要 UMI_ENV 指定

那该如何解决UMI_ENV指定的时候，config/下文件不生效的问题，且报错信息为： get user config failed, undefined does not exist, but process.env.UMI_ENV is set to local.

**Comment by hanwenbo** [comment]
+ 1 ,umi4 打包会将local一起打包 ，bug
