### ISSUE TITLE
useSelector无法从umi导出

### ISSUE THREAD

**Issue by wcxz520** [umijs/umi#7262]
目前最新版本，yarn create @umijs/umi-app

![image](https://user-images.githubusercontent.com/52689177/131801397-af62f8f6-f641-4cec-b9a9-8a1ee4819767.png)

![image](https://user-images.githubusercontent.com/52689177/131801863-e174f5c7-279c-4030-b1e0-8f825f091fb9.png)

**Comment by PeachScript** [comment]
dva 要手动安装插件到 devDependencies 才能使用：https://umijs.org/plugins/plugin-dva

**Comment by wcxz520** [comment]
> dva 要手动安装插件到 devDependencies 才能使用：https://umijs.org/plugins/plugin-dva

是手动再装plugin-dva还是dva？  plugin-dva的话会报错的，说存在。  能不能稍微清楚描述一下具体步骤.

**Comment by hanwenbo** [comment]
> dva 要手动安装插件到 devDependencies 才能使用：https://umijs.org/plugins/plugin-dva

没测就回复了吧。肯定不行的
