### ISSUE TITLE
config.ts动态配置开启mfsu报错

### ISSUE THREAD

**Issue by lawxy** [umijs/umi#7265]
## What happens?

在contfig.ts或者.umirc.ts中想动态配置是否开启mfsu 会报Cannot read property 'ModuleFederationPlugin' of undefined

## How To Reproduce

1. 直接在配置文件中写入mfsu:{} 没有问题
![3](https://user-images.githubusercontent.com/23738528/131939472-2befb1a3-7fd1-45bf-b1e7-b4edf6e092b2.png)

2. 通过对象解构就报错
![4](https://user-images.githubusercontent.com/23738528/131939487-a1bd3eb0-86f1-4467-bcbd-0470b3008870.png)

## Context

Environment | Info
-- | --
umi | 3.5.0
System | macOS

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by whereiscode** [comment]
删除 重新安装 最好是新建项目 把代码复制进去

**Comment by xiefengnian** [comment]
开 `webpack5 : {}`

**Comment by lawxy** [comment]
> 开 `webpack5 : {}`

还真是。不懂这个问题的原理，让我对js的认识产生怀疑

**Comment by yaochenyang007** [comment]
![image](https://user-images.githubusercontent.com/26396969/140274632-48695983-8794-4b5b-b937-4d63a8548610.png)
![image](https://user-images.githubusercontent.com/26396969/140274657-aa3f6876-5318-400e-812b-33c5abf3cdc6.png)
config.js 中配置好了 webpack5 : {},mfsu: {}, 还是会报这个错

**Comment by leoner** [comment]
+1

**Comment by xiefengnian** [comment]
主要的问题是，开启了 mfsu 之后，会自动开启 webapck5:{}，但是不知道为什么存在失败的可能。手动设置 webpack5 可以，如果再出现的话，在命令行强制开启：
```shell
USE_WEBPACK_5=1 umi dev
```

**Comment by xiefengnian** [comment]
> > 开 `webpack5 : {}`
> 
> 还真是。不懂这个问题的原理，让我对js的认识产生怀疑

ModuleFederationPlugin 是 webpack5 的 feature

**Comment by ILiZihan** [comment]
> 

可能是没有开webpack5, 它没有能够使用联邦属性的云阿姨NBA
