### ISSUE TITLE
配置了mfsu: {}以后 热更新没有了

### ISSUE THREAD

**Issue by machinister** [umijs/umi#7266]
## What happens?
umi3  重新安装依赖并配置了mfsu: {}以后项目启动并没有变快，并且热更新功能没有了

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.5.17
- **Node Version**: 14.17.5
- **Platform**: umi3

**Comment by JamieMing** [comment]
ant-design-pro的项目就能复现问题，我也遇到了

**Comment by Fidelgithub** [comment]
umi init出来的项目也能复现，要么热更新不生效，要么就是一些dom重复渲染：比如我页面引入了一个antd table，当我做更改时热更新在页面上渲染出了四五个table

**Comment by nuoer2048** [comment]
发现开启 msfu 后，重新更新依赖版本也不会更新

**Comment by ILuZhangKun** [comment]
> create umi出来的项目也能复现，要么热更新不生效，要么就是一些dom重复渲染：比如我页面引入了一个antd table，当我做更改时热更新在页面上渲染出了四五个table

请问问题解决了吗。我也遇到这个问题了。

**Comment by ILuZhangKun** [comment]
> > > create umi出来的项目也能复现，要么热更新不生效，要么就是一些dom重复渲染：比如我页面引入了一个antd table，当我做更改时热更新在页面上渲染出了四五个table
> > 
> > 
> > 请问问题解决了吗。我也遇到这个问题了。
> 
> 未解决，我的项目现在放弃使用mfsu了

sad...那有没有尝试迁移vite呀。

**Comment by Zach-Lu** [comment]
没解决就close是什么鬼？这个mfsu如果一开启就无法热更新，只能说适得其反。效率大大的降低。

**Comment by six006** [comment]
已经关闭这个mfsu功能，用了后编译也要10秒，不用编译也就15秒，最要命的是用了后不刷新，如果开启控制台，需要手动刷新整个页面，幸运的话能打开，但至少要等30秒以上，所以关闭mfsu,问题解决。

**Comment by GiserDing** [comment]
我之前也遇到过，msfu自动开启webpack5， 我将配置webpack5配置去掉只有热更新就正常了，不知道是不是这个原因

**Comment by zcSkr** [comment]
> 我之前也遇到过，msfu自动开启webpack5， 我将配置webpack5配置去掉只有热更新就正常了，不知道是不是这个原因
请问下mfsu自动开启webpack5之后，怎么把webpack5配置去掉，不能写 webpack5: false吧，

**Comment by GiserDing** [comment]
> 
直接把配置中webpack5:{}删掉啊


> > 我之前也遇到过，msfu自动开启webpack5，我将配置webpack5配置不热更新就正常了，知道是不是这个原因
> 
> 勃下mfsu自动开启webpack5，怎么把webpack5配置关闭后，不能写webpack5：假吧，

**Comment by zcSkr** [comment]
> > 
> 
> 直接把配置中webpack5:{}删掉啊
> 
> > > 我之前也遇到过，msfu自动开启webpack5，我将配置webpack5配置不热更新就正常了，知道是不是这个原因
> > 
> > 
> > 勃下mfsu自动开启webpack5，怎么把webpack5配置关闭后，不能写webpack5：假吧，

本来就不用写，只要写了mfsu：{}, webpack5都是开启的，热更新还是不正常，这解决不了。

**Comment by GiserDing** [comment]
> > > 
> > 
> > 
> > 直接把配置中webpack5:{}删掉啊
> > > > 我之前也遇到过，msfu自动开启webpack5，我将配置webpack5配置不热更新就正常了，知道是不是这个原因
> > > 
> > > 
> > > 勃下mfsu自动开启webpack5，怎么把webpack5配置关闭后，不能写webpack5：假吧，
> 
> 本来就不用写，只要写了mfsu：{}, webpack5都是开启的，热更新还是不正常，这解决不了。

![image](https://user-images.githubusercontent.com/35087072/147727202-9d684333-f25a-4338-bc35-72eb517c4cf7.png)
![image](https://user-images.githubusercontent.com/35087072/147727225-74825e3f-e683-4200-a953-e25b3c635d0e.png)

**Comment by GiserDing** [comment]
> > > > 
> > > 
> > > 
> > > 直接把配置中webpack5:{}删掉啊
> > > > > 我之前也遇到过，msfu自动开启webpack5，我将配置webpack5配置不热更新就正常了，知道是不是这个原因
> > > > 
> > > > 
> > > > 勃下mfsu自动开启webpack5，怎么把webpack5配置关闭后，不能写webpack5：假吧，
> > 
> > 
> > 本来就不用写，只要写了mfsu：{}, webpack5都是开启的，热更新还是不正常，这解决不了。
> 
> ![image](https://user-images.githubusercontent.com/35087072/147727202-9d684333-f25a-4338-bc35-72eb517c4cf7.png) ![image](https://user-images.githubusercontent.com/35087072/147727225-74825e3f-e683-4200-a953-e25b3c635d0e.png)

这是我的配置，我热更新是正常的

**Comment by zcSkr** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 直接把配置中webpack5:{}删掉啊
> > > > > > 我之前也遇到过，msfu自动开启webpack5，我将配置webpack5配置不热更新就正常了，知道是不是这个原因
> > > > > 
> > > > > 
> > > > > 勃下mfsu自动开启webpack5，怎么把webpack5配置关闭后，不能写webpack5：假吧，
> > > 
> > > 
> > > 本来就不用写，只要写了mfsu：{}, webpack5都是开启的，热更新还是不正常，这解决不了。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/35087072/147727202-9d684333-f25a-4338-bc35-72eb517c4cf7.png) ![image](https://user-images.githubusercontent.com/35087072/147727225-74825e3f-e683-4200-a953-e25b3c635d0e.png)
> 
> 这是我的配置，我热更新是正常的

好的，知道了。如果你封装了自定义组件。且共同使用的话热更新也是不生效的。这个问题我已经持续关注4个月了。现在还有帖子再说。就算umi create 出的antpro的例子 自己封装个组件 引入使用也会复现无法热更新。

**Comment by GiserDing** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 直接把配置中webpack5:{}删掉啊
> > > > > > > 我之前也遇到过，msfu自动开启webpack5，我将配置webpack5配置不热更新就正常了，知道是不是这个原因
> > > > > > 
> > > > > > 
> > > > > > 勃下mfsu自动开启webpack5，怎么把webpack5配置关闭后，不能写webpack5：假吧，
> > > > 
> > > > 
> > > > 本来就不用写，只要写了mfsu：{}, webpack5都是开启的，热更新还是不正常，这解决不了。
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/35087072/147727202-9d684333-f25a-4338-bc35-72eb517c4cf7.png) ![image](https://user-images.githubusercontent.com/35087072/147727225-74825e3f-e683-4200-a953-e25b3c635d0e.png)
> > 
> > 
> > 这是我的配置，我热更新是正常的
> 
> 好的，知道了。如果你封装了自定义组件。且共同使用的话热更新也是不生效的。这个问题我已经持续关注4个月了。现在还有帖子再说。就算umi create 出的antpro的例子 自己封装个组件 引入使用也会复现无法热更新。

封装了自己的组件，是有特殊写法吗，正常的写自己的组件，没啥问题，只要是import引入就没问题，不要使用require

**Comment by GiserDing** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 直接把配置中webpack5:{}删掉啊
> > > > > > > 我之前也遇到过，msfu自动开启webpack5，我将配置webpack5配置不热更新就正常了，知道是不是这个原因
> > > > > > 
> > > > > > 
> > > > > > 勃下mfsu自动开启webpack5，怎么把webpack5配置关闭后，不能写webpack5：假吧，
> > > > 
> > > > 
> > > > 本来就不用写，只要写了mfsu：{}, webpack5都是开启的，热更新还是不正常，这解决不了。
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/35087072/147727202-9d684333-f25a-4338-bc35-72eb517c4cf7.png) ![image](https://user-images.githubusercontent.com/35087072/147727225-74825e3f-e683-4200-a953-e25b3c635d0e.png)
> > 
> > 
> > 这是我的配置，我热更新是正常的
> 
> 好的，知道了。如果你封装了自定义组件。且共同使用的话热更新也是不生效的。这个问题我已经持续关注4个月了。现在还有帖子再说。就算umi create 出的antpro的例子 自己封装个组件 引入使用也会复现无法热更新。

封装了自己的组件，是有特殊写法吗，正常的写自己的组件，没啥问题，只要是import引入就没问题，不要使用require

**Comment by Fidelgithub** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 直接把配置中webpack5:{}删掉啊
> > > > > > > > 我之前也遇到过，msfu自动开启webpack5，我将配置webpack5配置不热更新就正常了，知道是不是这个原因
> > > > > > > 
> > > > > > > 
> > > > > > > 勃下mfsu自动开启webpack5，怎么把webpack5配置关闭后，不能写webpack5：假吧，
> > > > > 
> > > > > 
> > > > > 本来就不用写，只要写了mfsu：{}, webpack5都是开启的，热更新还是不正常，这解决不了。
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/35087072/147727202-9d684333-f25a-4338-bc35-72eb517c4cf7.png) ![image](https://user-images.githubusercontent.com/35087072/147727225-74825e3f-e683-4200-a953-e25b3c635d0e.png)
> > > 
> > > 
> > > 这是我的配置，我热更新是正常的
> > 
> > 
> > 好的，知道了。如果你封装了自定义组件。且共同使用的话热更新也是不生效的。这个问题我已经持续关注4个月了。现在还有帖子再说。就算umi create 出的antpro的例子 自己封装个组件 引入使用也会复现无法热更新。
> 
> 封装了自己的组件，是有特殊写法吗，正常的写自己的组件，没啥问题，只要是import引入就没问题，不要使用require

比如一个组件最外层是一个antd的抽屉，然后在这个抽屉内容做修改的时候就无法触发热更新

**Comment by zcSkr** [comment]
@Fidelgithub 啊对对对，大哥说的完全就是我实际做的情况。我把Modal和Drawer弄了个GlobalModal和GlobalDrawer。大部分页面都用了，然后往里面塞不同的表单。这样做热更新完全不行。每当umi跟新我就开启mfsu试试。一直都不行。

**Comment by zcSkr** [comment]
@GiserDing [这里有别的帖子用umi create 的脚手架都能复现问题](https://github.com/umijs/umi/issues/7193)
特殊写法不至于，组件都取了名字的，不是匿名。导入导出都是es6语法

**Comment by JamieMing** [comment]
@zcSkr 别管了，这就是个bug，一直也不修复，umi也很久没更新了，感觉项目组都不维护了

**Comment by soulcm** [comment]
请问下，mfsu这个对热更新的影响以还修复吗

**Comment by XueMeijing** [comment]
umi真的用的我想吐，一堆没用的东西，编译还那么慢，出现各种奇怪的问题，怪不得知乎上说把一堆优秀方案集成起来搅拌成狗屎这就是umi

**Comment by LOU-4599** [comment]
23年了还没人解决吗？？？

**Comment by BloquearaLua** [comment]
我把配置里的fastRefresh关了就可以热更新了
