### ISSUE TITLE
umi3通过extraBabelPlugins配置插件属性无效

### ISSUE THREAD

**Issue by yunguo** [umijs/umi#7267]
升级到umi3由于项目里面使用了大量的管道操作符(Pipeline Operator),导致报错如下

> ```Dva model src/pages/crm/models/dashboard.js parse failed, SyntaxError: This experimental syntax requires enabling the parser plugin: 'pipelineOperator' (401:48)
> Error: Dva model src/pages/crm/models/dashboard.js parse failed, SyntaxError: This experimental syntax requires enabling the parser plugin: 'pipelineOperator' (401:48)
>     at C:\workspace\boss-rms\node_modules\@umijs\plugin-dva\lib\getModels\getModels.js:66:13
>     at Array.filter (<anonymous>)
>     at getModels (C:\workspace\boss-rms\node_modules\@umijs\plugin-dva\lib\getModels\getModels.js:55:106)
>     at getAllModels (C:\workspace\boss-rms\node_modules\@umijs\plugin-dva\lib\index.js:111:48)
>     at Object.fn (C:\workspace\boss-rms\node_modules\@umijs\plugin-dva\lib\index.js:125:17)
>     at C:\workspace\boss-rms\node_modules\@umijs\core\lib\Service\Service.js:623:28
>     at Generator.next (<anonymous>)
>     at asyncGeneratorStep (C:\workspace\boss-rms\node_modules\@umijs\core\lib\Service\Service.js:110:103)
>     at _next (C:\workspace\boss-rms\node_modules\@umijs\core\lib\Service\Service.js:112:194)
>     at C:\workspace\boss-rms\node_modules\@umijs\core\lib\Service\Service.js:112:364
> Done in 5.43s.
> ```

加了Babel插件也同样报错
这是devDependencies:

> ```
>"devDependencies": {
>     "@babel/plugin-proposal-pipeline-operator": "^7.15.0",
> } 
>```

这是config.js配置文件
这种写法

> ```extraBabelPlugins: [['@babel/plugin-proposal-pipeline-operator', { proposal: 'minimal' }]],```

和这种写法都同样不起作用

> ```extraBabelPlugins: ['lodash', '@babel/plugin-proposal-pipeline-operator']```

**Comment by PeachScript** [comment]
配置 `dva: { skipModelValidate: true }` 试试，原因是 `plugin-dva` 会基于 babel ast 对 model 做校验，此时的 babel 配置不会读取 `extraBabelPlugins`
