### ISSUE TITLE
加入插件后启动报错，Module parse failed: Unexpected token (8:46)

### ISSUE THREAD

**Issue by YC725968** [umijs/umi#7270]
Module parse failed: Unexpected token (8:46)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export function useLayerLifecycle(element, context) {
|   useEffect(function addLayer() {
>     const container = context.layerContainer ?? context.map;
|     container.addLayer(element.instance);
|     return function removeLayer() {

 @ ./node_modules/@react-leaflet/core/esm/index.js 12:0-61 12:0-61 12:0-61
 @ ./node_modules/react-leaflet/esm/hooks.js
 @ ./node_modules/react-leaflet/esm/index.js
 @ ./src/pages/L7Map/index.tsx
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./node_modules/umi/node_modules/@umijs/preset-built-in/bundled/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./src/.umi/umi.ts
，这个问题该怎么解决呢？

**Comment by PeachScript** [comment]
依赖产物没编译成 es5，要走一次 babel 编译，refer: https://umijs.org/config#extrababelincludes

**Comment by jiyingzhi** [comment]
@PeachScript 我试了这个选项没效果，我的依赖是通过monorepo引入的
