### ISSUE TITLE
[Bug] 文档不是最新的，导致初步使用时有很多问题

### ISSUE THREAD

**Issue by cmdparkour** [umijs/umi#7277]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by PeachScript** [comment]
请提出具体问题点，也可以提 PR 参与优化
