### ISSUE TITLE
eslint配置不生效

### ISSUE THREAD

**Issue by xlei1123** [umijs/umi#7278]
## What happens?
按照文档的eslint配置  eslint并没有生效, 不要关闭 不要关闭 请给出解决方案， 我看issues里面好几个了

**Comment by PeachScript** [comment]
Umi 及 create-umi-app 脚手架没有提供 eslint 能力，遇到问题请到 eslint 社区或搜索引擎寻找答案

**Comment by 1247748612** [comment]
我这样是生效的
```javascript
module.exports = {
  extends: [
    require.resolve('@umijs/fabric/dist/eslint'),
    'plugin:import/typescript',
    'plugin:prettier/recommended',
  ],
  plugins: ['import'],
  globals: {
    ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION: true,
    page: true,
    REACT_APP_ENV: true,
  },
  rules: {
    'prettier/prettier': 'error',
    'import/order': [
      'warn',
      {
        groups: ['index', 'sibling', 'parent', 'internal', 'external', 'builtin', 'object', 'type'],
      },
    ],
    // 'import/order': 'off',
    // 'no-console': process.env.UMI_ENV === 'production' ? 'error' : 'off',
    'no-console': 'off',
    '@typescript-eslint/no-non-null-asserted-optional-chain': 'off',
  },
};

```

**Comment by seveneElevenup** [comment]
> ## What happens?
> 按照文档的eslint配置 eslint并没有生效, 不要关闭 不要关闭 请给出解决方案， 我看issues里面好几个了

请问你解决了吗？

**Comment by seveneElevenup** [comment]
> 我这样是生效的
> 
> ```js
> module.exports = {
>   extends: [
>     require.resolve('@umijs/fabric/dist/eslint'),
>     'plugin:import/typescript',
>     'plugin:prettier/recommended',
>   ],
>   plugins: ['import'],
>   globals: {
>     ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION: true,
>     page: true,
>     REACT_APP_ENV: true,
>   },
>   rules: {
>     'prettier/prettier': 'error',
>     'import/order': [
>       'warn',
>       {
>         groups: ['index', 'sibling', 'parent', 'internal', 'external', 'builtin', 'object', 'type'],
>       },
>     ],
>     // 'import/order': 'off',
>     // 'no-console': process.env.UMI_ENV === 'production' ? 'error' : 'off',
>     'no-console': 'off',
>     '@typescript-eslint/no-non-null-asserted-optional-chain': 'off',
>   },
> };
> ```

还是不生效
