### ISSUE TITLE
[Bug]开启mfsu后设置theme无效

### ISSUE THREAD

**Issue by s464446877** [umijs/umi#7279]
开启mfsu后，设置theme里变量主题颜色和ant-prefix，均无效，关闭mfsu后可以正常使用

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:3.5.17
- **Node Version**:12.18
- **Platform**: macos chrome

**Comment by PeachScript** [comment]
Duplicate of #7048
