### ISSUE TITLE
[Bug] 新增的文件不会触发自动编译

### ISSUE THREAD

**Issue by 915898885yx** [umijs/umi#7280]
从git上拉下来的项目，新增的文件内容发生改变不会触发自动编译，之前项目中的文件发生改变会自动编译，导致新开发需求改一个地方就必须要重启才生效，然后就一直需要重启，一直需要重启

**Comment by s464446877** [comment]
那是因为这个文件没有地方引用吧，用到的文件会自动编译，没有用到的不会
