### ISSUE TITLE
typescript 定义中有问题

### ISSUE THREAD

**Issue by zww-v5** [umijs/umi#7284]
在写插件的时候发现引入的 umi ts 定义存在着同名变量的问题。

![image](https://user-images.githubusercontent.com/9295948/132466996-f0d5d838-960f-4656-8e05-eed622fbeb02.png)

![image](https://user-images.githubusercontent.com/9295948/132466929-a64af2a1-647b-4433-b6a7-90417b1d50ff.png)

**Comment by zww-v5** [comment]
![image](https://user-images.githubusercontent.com/9295948/132467626-3390ae45-b3e9-41e5-8225-9629a6724b89.png)

**Comment by xiaohuoni** [comment]
什么版本呢？

**Comment by zww-v5** [comment]
umi@3.5.17
