### ISSUE TITLE
[Bug] 引入react-three-fiber 报错，cra搭建的项目，一模一样的代码展示没问题

### ISSUE THREAD

**Issue by lsshavedream** [umijs/umi#7292]
## What happens?
引入react-three-fiber 报错，用cra搭建的项目，一模一样的代码展示没问题

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/lsshavedream/umi-gltf.git

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- 3.5.0
- **Node Version**:
- 14.17.0
- **Platform**:

**Comment by lsshavedream** [comment]
![image](https://user-images.githubusercontent.com/22446043/132611167-e9e0594e-de48-4969-a4b4-eceb5b7d7a82.png)

**Comment by baiDog** [comment]
仔细检查下了代码，发现是umi对prop.children的处理问题，没有兼容@react-three/fiber的写法
`<Canvas
      style={{ background: '#272727', touchAction: 'none' }}
      camera={{ position: [0, 0, 500], zoom: 1 }}
    >
       <pointLight />
      {/*<pointLight position={[10, 10, 10]} />
      <Box position={[-1.2, 0, 0]} />
      <Box position={[1.2, 0, 0]} /> */}
    </Canvas>`

**Comment by YC725968** [comment]
解决了吗

**Comment by lsshavedream** [comment]
@baiDog 谢谢大佬，有解决方案吗

**Comment by lsshavedream** [comment]
@YC725968 没有，暂时没有时间去看

**Comment by baiDog** [comment]
> 

我是菜鸡····，我暂时没用react-three-fiber。直接用three原生写了·····
