### ISSUE TITLE
Add example of redux

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#73]
考虑以下：

* 一个全局的 store，共享
* 全局 reducer
* 每个页面自己的 reducer
* 加入一个简单的中间件，redux-thunk
* 例子里实现简单的同步和异步操作

**Comment by sorrycc** [comment]
Done via 31ffdf206dfa049af24be7b6bd68751ece2e8bf8.

**Comment by sorrycc** [comment]
## 如何使用 umi + redux

1. 请确保 umi >= 1.0.0-rc.1
1. 参考 with-redux 的例子，https://github.com/umijs/umi/tree/master/examples/with-redux

**Comment by SyuTingSong** [comment]
moved to https://github.com/umijs/umi-examples/tree/master/with-redux
