### ISSUE TITLE
MFSU theme 部分工作

### ISSUE THREAD

**Issue by Jiahua33** [umijs/umi#7304]
我目前使用的是UMI + AntD Pro的脚手架，
这里是配置文件 目前mfsu工作状态， 我的想法是这样 首先引入 dark 和compact 主题然后再定制一下其中的一些 样式
```
{
antd: {
    dark: true, // 开启暗色主题
    compact: true, // 开启紧凑主题
  },
  theme: {
    '@primary-color': defaultSettings.primaryColor,
    '@text-color': '#ffc918',
    '@menu-dark-item-active-bg': '#ffc918',
    '@pro-header-hover-bg': '#18ff2b',
  },
}
```
目前的效果是这个样子 其中中间的白色是Antd的Card
![Screen Shot 2021-09-12 at 4 07 35 PM](https://user-images.githubusercontent.com/88690670/133005640-5ed2a6bc-77c6-4bea-b906-09d8d8bd0a58.png)

我期待的效果是
![Screen Shot 2021-09-12 at 4 14 46 PM](https://user-images.githubusercontent.com/88690670/133005759-df5b6ad8-7ab3-44a7-aafd-984c120023c5.png)

我看了下代码好像mfsu cache中的文件覆盖了本来应该生成的样式
![Screen Shot 2021-09-12 at 4 11 49 PM](https://user-images.githubusercontent.com/88690670/133005783-253567cb-467c-4a40-abcf-b944fb03cf2a.png)

如果我关闭mfsu 代码就会正常工作 只是编译会慢很多
如果有需要补充的资料请留言

**Comment by 2018Cool** [comment]
+1 我也遇到类似问题

**Comment by sofakeer** [comment]
+1 我也遇到类似问题

**Comment by s464446877** [comment]
同样遇到这个问题

**Comment by xiefengnian** [comment]
给个复现仓库

**Comment by SturdyCat** [comment]
@umijs/preset-react  版本 1.8.30 正常 2.xx 以上暗黑样式失效
