### ISSUE TITLE
配置extraBabelPlugins 报错，

### ISSUE THREAD

**Issue by leehomeok** [umijs/umi#7313]
## What happens?
config.js 配置 extraBabelPlugins: [['transform-remove-console', { exclude: ['error'] }]]

报错：
Module build failed (from ./node_modules/@umijs/deps/compiled/babel-loader/index.js):
Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.x
- **Node Version**:12.13.0
- **Platform**: win10

**Comment by mwj610** [comment]
@sorrycc 这个怎解决？
