### ISSUE TITLE
[Bug] 开启mfsu的时候引入node_modules中的图片，在开发环境下图片无法显示

### ISSUE THREAD

**Issue by AboyL** [umijs/umi#7319]
## What happens?

开启mfsu的时候引入node_modules中的图片，在开发环境下图片无法显示
```
import styles from './index.less';
import img from 'l-lerna-test-base/lib/test.jpg';

export default function IndexPage() {
  return (
    <div>
      <h1 className={styles.title}>Page index</h1>
      <img src={img} />
    </div>
  );
}

```

图片无法显示
代码的错误位置应该是
umijs/packages/preset-built-in/src/plugins/features/mfsu/mfsu.ts
的api.addBeforeMiddlewares出
在这里没有对二进制的文件进行处理，因此包括图片以及字体都没有正确的加载

## Mini Showcase Repository(REQUIRED)

https://github.com/AboyL/demo

## How To Reproduce

cd 到umi-test目录
yarn
执行 yarn start 启动后可以看到现象
![image](https://user-images.githubusercontent.com/20349115/133210913-f0373406-2de4-40c3-9ed3-70764dda1ef3.png)

## Context

- **Umi Version**: 3.5.18
- **Node Version**: 12.18.3
- **Platform**: MacOS

**Comment by xiefengnian** [comment]
用 node_modules 中的图片不是一个好习惯，暂不考虑支持
