### ISSUE TITLE
[Feature Request] 打包问题

### ISSUE THREAD

**Issue by ratelgogo** [umijs/umi#7320]
## Background
现在项目有很多页面，使用动态打包的方式，每个页面都有很多文件，一次打包几百个文件。
## Proposal
有没有一种方式用动态打包，又能聚合一些文件？

**Comment by ratelgogo** [comment]
![image](https://user-images.githubusercontent.com/23555154/133216243-877e5739-128e-4daf-b65a-6ded53e3e9d4.png)
这些都是组件的js代码么？

**Comment by 1247748612** [comment]
都是动态组件
