### ISSUE TITLE
[Bug] mfsu breaks source map

### ISSUE THREAD

**Issue by cagen** [umijs/umi#7321]
## What happens?

There are warning about source maps when turn on mfsu. And lots of node_modules packages cannot be mapped.

```
DevTools failed to load source map: Could not parse content for http://localhost:8000/react-router.js.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for http://localhost:8000/index.js.map: Unexpected token < in JSON at position 0
DevTools failed to load source map: Could not parse content for http://localhost:8000/react-router-config.js.map: Unexpected token < in JSON at position 0
```
![image](https://user-images.githubusercontent.com/5174809/133218348-d9cc7160-7a37-4000-9583-8293b630f5f4.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/cagen/umi-test

## How To Reproduce

**Steps to reproduce the behavior:** 
1. npx @umijs/create-umi-app
2. add `mfsu: {}` in .umirc.ts
3. npm start
4. open chrome devtools to see the warnings 

**Expected behavior** 
There should not be any source maps warnings, and node_modules packages can be mapped correctly.

## Context

- **Umi Version**:3.5.18
- **Node Version**:12.22.1
- **Platform**:macOS

**Comment by chenzio** [comment]
Have the same problem

**Comment by perny** [comment]
同样的问题
按照AntdPro官网初始化的项目，结果出现了这个问题
1.npx create-umi xxx
2.? Select the boilerplate type (Use arrow keys) -> ant-design-pro
3.? 🤓 Which language do you want to use? (Use arrow keys) -> JavaScript
4. ? 🚀 Do you need all the blocks or a simple scaffold? (Use arrow keys) -> simple
5. cd xxx && npm install
6. npm run start
环境
nodejs12
macOS
![WechatIMG4](https://user-images.githubusercontent.com/3123626/134475569-27dd4f24-f073-4790-8f94-6f9632632c75.png)

**Comment by flycj** [comment]
> 同样的问题 按照AntdPro官网初始化的项目，结果出现了这个问题 1.npx create-umi xxx 2.? Select the boilerplate type (Use arrow keys) -> ant-design-pro 3.? 🤓 Which language do you want to use? (Use arrow keys) -> JavaScript 4. ? 🚀 Do you need all the blocks or a simple scaffold? (Use arrow keys) -> simple 5. cd xxx && npm install 6. npm run start 环境 nodejs12 macOS ![WechatIMG4](https://user-images.githubusercontent.com/3123626/134475569-27dd4f24-f073-4790-8f94-6f9632632c75.png)

你好，你解决这个问题了吗？

**Comment by xakxak007** [comment]
我也遇到了相同的问题

**Comment by Alt-er** [comment]
遇到同样的问题 请问解决了吗？

**Comment by perny** [comment]
> > 同样的问题 按照AntdPro官网初始化的项目，结果出现了这个问题 1.npx create-umi xxx 2.? Select the boilerplate type (Use arrow keys) -> ant-design-pro 3.? 🤓 Which language do you want to use? (Use arrow keys) -> JavaScript 4. ? 🚀 Do you need all the blocks or a simple scaffold? (Use arrow keys) -> simple 5. cd xxx && npm install 6. npm run start 环境 nodejs12 macOS ![WechatIMG4](https://user-images.githubusercontent.com/3123626/134475569-27dd4f24-f073-4790-8f94-6f9632632c75.png)
> 
> 你好，你解决这个问题了吗？

并没有

**Comment by hb1707** [comment]
Have the same problem

**Comment by KrishnaPG** [comment]
How to make the source-map files work? Getting the same error.

**Comment by codering** [comment]
+1 !!

**Comment by licoded** [comment]
+1
感觉使用ant-design-pro的人挺多，却没人给点帮助，比较失望

**Comment by zhenghub** [comment]
+1

**Comment by hlsky1988** [comment]
umi: 3.5.20
Have the same problem

**Comment by beatzcs** [comment]
Have the same problem.

**Comment by Mistrain-y-y** [comment]
+1

**Comment by Mistrain-y-y** [comment]
+1

**Comment by SmileKill** [comment]
+1

**Comment by Cyrusky** [comment]
Why? Closed?

**Comment by Cyrusky** [comment]
@sorrycc , 为啥关了啊？

**Comment by Cyrusky** [comment]
Refer to: https://github.com/umijs/umi/issues/6996 a similar issue.

Known issue, so, just ignore it.
