### ISSUE TITLE
使用chainWebpack后运行白屏

### ISSUE THREAD

**Issue by yaodong5063** [umijs/umi#7323]
chunks: ['vendors', 'umi'],
    chainWebpack(memo) {
      memo.merge({
        optimization: {
          splitChunks: {
            chunks: 'all',
            minSize: 30000,
            minChunks: 3,
            automaticNameDelimiter: '.',
            cacheGroups: {
              vendor: {
                name: 'vendors',
                test({ resource }) {
                  return /[\\/]node_modules[\\/]/.test(resource);
                },
                priority: 10,
              },
            },
          },
        },
      });

**Comment by yaodong5063** [comment]
![image](https://user-images.githubusercontent.com/37628562/133231920-7af96928-90dc-41cb-94b6-bf152825af6b.png)
![企业微信截图_16316114439919](https://user-images.githubusercontent.com/37628562/133232065-c282aab2-d156-4975-ab4c-e30f4ede58b7.png)


umi.js加载是正常的，但是后面就不运行了

**Comment by yaodong5063** [comment]
使用的是最新的3.5.18，我回退到3.4.18就好了

**Comment by qiutian00** [comment]
@yaodong5063 , 可以分享你的配置么？ build总是报错`AssertionError [ERR_ASSERTION]: chunk of index not found.` ； 没有找到是本地环境哪里影响了。

我的配置
![image](https://user-images.githubusercontent.com/24382500/136530805-d63e0e08-2e14-4040-948b-676c199efc88.png)

**Comment by peakandyuri** [comment]
3.5.20仍然存在这个问题

**Comment by Lzengp** [comment]
> 3.5.20仍然存在这个问题

有没有什么解决方案没 @peakandyuri

**Comment by peakandyuri** [comment]
> > 3.5.20仍然存在这个问题
> 
> 有没有什么解决方案没 @peakandyuri

我已经换成自己搭webpack配置来开发了，我的项目路由很少，替换相对比较简单

**Comment by peakandyuri** [comment]
> > 3.5.20仍然存在这个问题
> 
> 有没有什么解决方案没 @peakandyuri

白屏是由于未加载webpack记录各模块文件名称的文件

**Comment by bluehymn** [comment]
#https://github.com/umijs/umi/issues/7650#issuecomment-1061555349
