### ISSUE TITLE
esbuild压缩安装不上

### ISSUE THREAD

**Issue by SkyWongHZ** [umijs/umi#7324]
项目版本  umi 3.5.17   
esbuild插件 @umijs/plugin-esbuild   1.3.1
node版本  14.16.0

yarn build安装项目卡在92%,提示报错如下:
![image](https://user-images.githubusercontent.com/20575355/133233188-2f5534ea-f63c-4372-810b-31bb058d8b5f.png)

**Comment by renkunx** [comment]
定义的target不支持吧，
esbuild:{}试试

**Comment by xiaohuoni** [comment]
给复现给复现给复现

**Comment by mschenhe** [comment]
安装esbuild之后项目启不起来了
![image](https://user-images.githubusercontent.com/31650065/137665298-844933fe-9b39-418f-ab92-2546785dcfe0.png)
