### ISSUE TITLE
[Bug] 开启 mfsu 之后， 运行两次 build， dist 下会产生 .webpackFSCache 文件。

### ISSUE THREAD

**Issue by wuyun1** [umijs/umi#7326]
## What happens?

开启 mfsu 之后， 连续运行两次 build， dist 下会产生 .webpackFSCache 文件。

只运行一次 yarn run build , dist 文件夹下 不会出现 .webpackFSCache

![image](https://user-images.githubusercontent.com/12711404/133254232-59617cd2-68e7-471a-ace6-d80aee94c342.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

创建项目
```
mkdir myapp && cd myapp
yarn create @umijs/umi-app
yarn install 
```
开启 mfsu

```
// .umirc.ts
import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  mfsu: {
    production: {}
  },
  routes: [
    { path: '/', component: '@/pages/index' },
  ],
  fastRefresh: {},
});

```

编译两次
```
yarn run build
yarn run build
```

## Context

- **Umi Version**: 3.5.18
- **Node Version**: *
- **Platform**: *

**Comment by showtan001** [comment]
+1

**Comment by TianBM** [comment]
俺也一样

**Comment by WangDianhang** [comment]
也出现了
