### ISSUE TITLE
[Bug] ssr 模式，访问特殊链接报错

### ISSUE THREAD

**Issue by robinv8** [umijs/umi#7329]
## What happens?
访问一个不存在的链接报错，`http://localhost:8000/product/search--%B6%D4%E4%E5%C1%AA%B1%BD--0.html`

![image](https://user-images.githubusercontent.com/12277531/133367458-cb11445d-f0a6-4c01-8d49-421d31d514a7.png)

## Context

- **Umi Version**: v3.5.0
- **Node Version**: v12.18.3
- **Platform**: linux

**Comment by PeachScript** [comment]
和 SSR 无关，提示得很明显了，URI 没法 decode，哪怕关掉 SSR 一样访问不了
