### ISSUE TITLE
[Bug] 无法通过配置 extraBabelIncludes 属性实现monorepo并且编译外部tsx文件

### ISSUE THREAD

**Issue by zytqyb** [umijs/umi#7332]
## What happens?
我想利用 lerna 的功能实现在多个Ant Design Pro 项目共享某些组件,步骤基本顺利,但是最后如果编写的组件使用tsx编写将无法进行编译.

## Mini Showcase Repository(REQUIRED)
[https://github.com/zytqyb/monorepo-antd-pro](url)

## How To Reproduce

1. 新建 yarn workspace，指定在 packages 目录下
2. 在 packages 下根据官网新建 Ant Design Pro v5 项目
3. 新建希望多项目复用的组件common/components/PageSearch组件
4. 在项目中引入组件
5. PageSearch使用jsx编写时可以通过编译,但是使用tsx编写编译报错

## Context

- **Umi Version**:3.5
- **Node Version**:14.17.6
- **Platform**:win10 20H2

**Comment by GreatAuk** [comment]
这个 issue 也是一样的问题，https://github.com/umijs/umi/issues/6576，好像 umi 现在 extraBabelIncludes 不支持 ts 文件

**Comment by GreatAuk** [comment]
我试了这个方法可用 https://github.com/umijs/umi/issues/6576#issuecomment-841806511

**Comment by zytqyb** [comment]
> 我试了这个方法可用[#6576（评论）](https://github.com/umijs/umi/issues/6576#issuecomment-841806511)

好的,尝试下

**Comment by zytqyb** [comment]
> 我试了这个方法可用[#6576（评论）](https://github.com/umijs/umi/issues/6576#issuecomment-841806511)
解决了,非常感谢,我先关闭这个issues

**Comment by GreatAuk** [comment]
@zytqyb 你也在整 qiankun 吗？

**Comment by zytqyb** [comment]
> @zytqyb 你也在整 qiankun 吗？
暂时只是有个想要方便的的多项目复用一些公用的组件

**Comment by zytqyb** [comment]
> @zytqyb 你也在整 qiankun 吗？

暂时只是有个想要方便的的多项目复用一些公用的组件
