### ISSUE TITLE
@finalreturn  https://www.npmjs.com/package/@alitajs/@alitajs/tabs-layout 同样技术实现的，多tabs 。可以尝试能否解决，预览页面 https://pro.alitajs.com/

### ISSUE THREAD

**Issue by XinYueXiao** [umijs/umi#7336]
@finalreturn  https://www.npmjs.com/package/@alitajs/@alitajs/tabs-layout 同样技术实现的，多tabs 。可以尝试能否解决，预览页面 https://pro.alitajs.com/

_Originally posted by @xiaohuoni in https://github.com/umijs/umi/issues/3091#issuecomment-627688475_

打不开了 404了

**Comment by xiaohuoni** [comment]
https://www.npmjs.com/package/@alitajs/tabs-layout

**Comment by Aaron52077** [comment]
https://wuli-admin.gitee.io/react-antd-template/#/dashboard 感受下缓存iframe页签的tab
