### ISSUE TITLE
chainWebpack使用entry和merge后白屏

### ISSUE THREAD

**Issue by yaodong5063** [umijs/umi#7337]
chainWebpack(memo) {
    memo
      .entry(['transfer'])
      .add(path.resolve(__dirname, '../src/transfer.ts'))
      .end();
    memo.merge({
      optimization: {
        splitChunks: {
          chunks: 'initial', //提取chunks的时候配置
          minSize: 30000,
          minChunks: 1, //最少y引用数量
          automaticNameDelimiter: '.', //文件分割名
          cacheGroups: {

去掉任何一个都会正常

**Comment by yaodong5063** [comment]
两个同时存在就会白屏

**Comment by yaodong5063** [comment]
@sorrycc

**Comment by yaodong5063** [comment]
![企业微信截图_16317752631927](https://user-images.githubusercontent.com/37628562/133564395-de708fb8-77c8-4be4-9db1-47e204876cfc.png)
一个新的项目也是这样的

**Comment by xiaohuoni** [comment]
入口是 `src/.umi/umi.ts` 不允许修改的
