### ISSUE TITLE
[缺少] es5-imcompatible-versions 

### ISSUE THREAD

**Issue by pisyell** [umijs/umi#7338]
es5-imcompatible-versions  
关于 react-pdf 没有收录进。
目前只有 react-pdf-js

![image](https://user-images.githubusercontent.com/37040920/133568289-dc8192ac-0284-43b2-8912-06c3ef2744ee.png)

**Comment by xiaohuoni** [comment]
react-pdf 这个包有问题的话，可以自己PR添加。
