### ISSUE TITLE
路由配置（缓存？）不能自动刷新

### ISSUE THREAD

**Issue by byan** [umijs/umi#734]
在 pages 目录新增Example 目录，并添加页面 Example/One.js、Example/Two.js，然后在配置文件的路由配置项指向的路由配置文件里新增一个 entry：

``
{ 
name: 'example', 
path: '/example',  
routes: [
{ name: 'example-one',  path: '/example/one',  component: './Example/One' },
{ name: 'example-two',  path: '/example/two',  component: './Example/Two' },
]
}
``

热更新后，左边菜单可以出现 Example One/Two ，但是点击任何一个就会报错说找不到  Example/One.js 。似乎是因为 .umi 里面的 router 文件没有更新。如果这时关闭并重新运行 npm run start 就可以正常打开 Example One/Two。

**Comment by wwjd2016** [comment]
我也遇到了同样的问题，请问你怎么解决的？

**Comment by byan** [comment]
当时是换 dvajs 了
