### ISSUE TITLE
引用 @umijs/plugin-qiankun插件 和 qiankun  提示 [MFSU] require('path-to-regexp') found in D:\SourceCode\MicroApp\MainApp\src\.umi\plugin-qiankun\common.ts, which will broken the MFSU prebuild match, please change to esm module import.

### ISSUE THREAD

**Issue by lecd** [umijs/umi#7340]
## What happens?

引用 @umijs/plugin-qiankun插件 和 qiankun  提示 [MFSU] require('path-to-regexp') found in D:\SourceCode\MicroApp\MainApp\src\.umi\plugin-qiankun\common.ts, which will broken the MFSU prebuild match, please change to esm module import.，这咋回事？

![image](https://user-images.githubusercontent.com/17017158/133593403-9ad694d4-de27-42de-83d5-d44f61baf511.png)

版本信息
 "umi": "^3.5.0",
 "qiankun": "^2.4.10"，
 "@umijs/plugin-qiankun": "^2.31.1"

**Comment by xiefengnian** [comment]
不影响使用，具体见 https://github.com/umijs/plugins/pull/665
