### ISSUE TITLE
Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by huyawei** [umijs/umi#7346]
一开始最终版本是3.5.17 发布一切ok
然后3.5.18出来 再发布 Class extends value undefined is not a constructor or null
好吧改成3.5.18 ok了
现在3.5.19出来 再发布 又是 Class extends value undefined is not a constructor or null
好吧改成3.5.19 又好了
说实话有点无语

**Comment by xiaohuoni** [comment]
你在说啥？

**Comment by kwzm** [comment]
3.5.20 构建的时候也会报同样的错误

**Comment by zhouccccc** [comment]
> 3.5.20 构建的时候也会报同样的错误

我也遇到了，你是怎么解决的？

**Comment by zhouccccc** [comment]
又出现这个问题了，真的是奇了怪了，明明已经锁版本了还会出现这个问题。只要有新版本release，100%出现这个问题
<img width="152" alt="image" src="https://user-images.githubusercontent.com/25141787/162962323-3b2d1caf-9eea-40bf-ba4c-c8dbc8678086.png">

<img width="550" alt="image" src="https://user-images.githubusercontent.com/25141787/162962368-824e2bf6-1d68-44c4-b3f7-49928c73709c.png">

**Comment by wuranxu** [comment]
> 又出现这个问题了，真的是奇了怪了，明明已经锁版本了还会出现这个问题。只要有新版本release，100%出现这个问题 <img alt="image" width="152" src="https://user-images.githubusercontent.com/25141787/162962323-3b2d1caf-9eea-40bf-ba4c-c8dbc8678086.png">
> 
> <img alt="image" width="550" src="https://user-images.githubusercontent.com/25141787/162962368-824e2bf6-1d68-44c4-b3f7-49928c73709c.png">

同，你是怎么解决的呀~

**Comment by zhouccccc** [comment]
升级了，目前没发现别的办法



发自我的iPhone


------------------ Original ------------------
From: 米洛 ***@***.***&gt;
Date: Tue,Apr 12,2022 10:35 PM
To: umijs/umi ***@***.***&gt;
Cc: zhouccccc ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [umijs/umi] Class extends value undefined is not a constructor ornull (#7346)





  
又出现这个问题了，真的是奇了怪了，明明已经锁版本了还会出现这个问题。只要有新版本release，100%出现这个问题 
   
同，你是怎么解决的呀~

**Comment by wuranxu** [comment]
> 升级了，目前没发现别的办法 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: 米洛 ***@***.***&gt; Date: Tue,Apr 12,2022 10:35 PM To: umijs/umi ***@***.***&gt; Cc: zhouccccc ***@***.***&gt;, Comment ***@***.***&gt; Subject: Re: [umijs/umi] Class extends value undefined is not a constructor ornull (#7346) 又出现这个问题了，真的是奇了怪了，明明已经锁版本了还会出现这个问题。只要有新版本release，100%出现这个问题 同，你是怎么解决的呀~ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

👍 好的，感谢~~

**Comment by dontdrinkmylemontea** [comment]
😂真的有，当前umi锁死版本3.5.23，3.5.24发布后直接报错
![image](https://user-images.githubusercontent.com/25890927/169970837-9be0cd5d-300d-43de-9ca0-ab0e36dc8f47.png)
![image](https://user-images.githubusercontent.com/25890927/169970966-76f7894c-d9f6-45d9-aa1b-31ad3d1af3a5.png)

**Comment by zhouccccc** [comment]
> 😂真的有，当前umi锁死版本3.5.23，3.5.24发布后直接报错 ![image](https://user-images.githubusercontent.com/25890927/169970837-9be0cd5d-300d-43de-9ca0-ab0e36dc8f47.png) ![image](https://user-images.githubusercontent.com/25890927/169970966-76f7894c-d9f6-45d9-aa1b-31ad3d1af3a5.png)

就很离谱！！！！

**Comment by zhouccccc** [comment]
@xiaohuoni @sorrycc 导致这种情况的原因是什么呢？

**Comment by xiaohuoni** [comment]
很离谱，我复现不出来。是锁定版本之后，umi 发新版本之后，重新 install 嘛？

**Comment by zhouccccc** [comment]
不一定要锁定版本，不需要重新install。只要是umi发布新版本，本地重新build就会出现


------------------ Original ------------------
From: 小虎oni ***@***.***&gt;
Date: Sat,May 28,2022 4:27 PM
To: umijs/umi ***@***.***&gt;
Cc: zhouccccc ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [umijs/umi] Class extends value undefined is not a constructor or null (#7346)






很离谱，我复现不出来。是锁定版本之后，umi 发新版本之后，重新 install 嘛？

**Comment by xiaohuoni** [comment]
@sorrycc 我没法重现，这个可能是什么原因导致的？

**Comment by dontdrinkmylemontea** [comment]
@xiaohuoni 我这边用的tnpm, 相关版本如下：

| pkg | version |
|---|---|
| tnpm | 8.1.6  |
| node | 16.15.1  |

umi锁死版本，然后 umi 发布新版本后，重新安装依赖，然后执行 `npm run build`，就会出现如上报错。100%出现

**Comment by zhouccccc** [comment]
> @sorrycc 我没法重现，这个可能是什么原因导致的？

这个需要在每次发布新版本时候执行`npm run build`才会重现

**Comment by zhouccccc** [comment]
所以问题不解决就直接close掉issue？

**Comment by kongqueshi** [comment]
@sorrycc 我今天也碰到了同样的问题。之前是3.5.26版本的，build报上面的错误。然后升级到了3.5.27后还是这个错误。最后升级到了最新的版本3.5.30就好了。其他什么也没有动过。这个怎么看都是有问题的吧？

**Comment by huyawei** [comment]
> @sorrycc 我今天也碰到了同样的问题。之前是3.5.26版本的，build报上面的错误。然后升级到了3.5.27后还是这个错误。最后升级到了最新的版本3.5.30就好了。其他什么也没有动过。这个怎么看都是有问题的吧？

用yarn吧

**Comment by kongqueshi** [comment]
> > @sorrycc 我今天也碰到了同样的问题。之前是3.5.26版本的，build报上面的错误。然后升级到了3.5.27后还是这个错误。最后升级到了最新的版本3.5.30就好了。其他什么也没有动过。这个怎么看都是有问题的吧？
> 
> 用yarn吧

今天发布了个新版本，果然。。。

**Comment by wuranxu** [comment]
> 很离谱，我复现不出来。是锁定版本之后，umi 发新版本之后，重新 install 嘛？

虎哥，这个问题目前还有的。（我自己有个github action项目都会遇到的，应该不止windows会出现，而且每次都是发新版本出现）
可以想办法复现一下么？（我会爱上你的）我目前是这样会出现, 用的是cnpm/npm
1. 指定umi版本比如3.5.20
2. umi发新版本
3. `npm install`后umi dev/build都会遇到这个问题

**Comment by dickeylth** [comment]
+1，尝试锁死了 umi 几个版本都还是报这个错，1 个月前还是正常的构建，也没改什么东西

**Comment by xiaohuoni** [comment]
谁给一个完整一点的日志或者能重现的 demo ？

**Comment by sorrycc** [comment]
Umi 3 不要锁死版本，要锁就用 lock 文件锁。

**Comment by echoloyuk** [comment]
+1

**Comment by cpdeam** [comment]
2023年 8月了 之前一个没有锁版本的老项目报这个错还有救吗。。。没有精力升级umi到4.0版本了。

> Umi 3 不要锁死版本，要锁就用 lock 文件锁。
