### ISSUE TITLE
[Feature Request] antd-mobile V5的支持

### ISSUE THREAD

**Issue by 1998feng** [umijs/umi#7352]
大概什么时间@umijs/plugin-antd内置的antd-mobile会更新为V5（白杨）版本？

**Comment by zhangchao828** [comment]
antd-mobile5发布了？

**Comment by zhangchao828** [comment]
antd-mobile5发布了？

**Comment by xiaohuoni** [comment]
antd-mobile@5 还没正式发布，内置的话，就是这样子，你可以看看。https://github.com/ant-design/ant-design-mobile/issues/3972
