### ISSUE TITLE
[Bug] 按照官方文档安装umii3  发现丢失了 @umijs/fabric

### ISSUE THREAD

**Issue by chenglianjie** [umijs/umi#7358]
## What happens?
![1631970740(1)](https://user-images.githubusercontent.com/49651525/133890113-d571ae31-894e-48f6-bc52-e6bb4bb6bef7.png)
依赖里面缺少@umijs/fabric  

按照官方文档快速上手 创建了umi3项目，缺少依赖，导致eslint无法运行
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by GreatAuk** [comment]
默认是没有的，自己安装呗，配置参考 antd pro 的
