### ISSUE TITLE
Cannot read property 'ModuleFederationPlugin' of undefined

### ISSUE THREAD

**Issue by 007jiang7442262** [umijs/umi#7361]
![image](https://user-images.githubusercontent.com/38500885/134444947-74928604-55c5-41f9-90fa-86f812a2cc6a.png)
配置
![image](https://user-images.githubusercontent.com/38500885/134445027-5f422b9d-c1a1-49a7-ad15-fa4980038e18.png)
![image](https://user-images.githubusercontent.com/38500885/134445377-e2aa3785-1d95-4377-838c-2b16cef63d49.png)

**Comment by xiaohuoni** [comment]
这个错误的话，是没有用上 webpack5 看你的配置应该有使用，你还有其他环境变量设置吗？或者给一个可以复现的demo

**Comment by 007jiang7442262** [comment]
> 这个错误的话，是没有用上 webpack5 看你的配置应该有使用，你还有其他环境变量设置吗？或者给一个可以复现的demo


我没有设置其它环境变量，我是用 npm run dev 启动的

<img width="945" alt="WeChat3f9137726f32cd640f3a4996cfbc2e1e" src="https://user-images.githubusercontent.com/38500885/134448438-a8fb3e54-da58-4b88-a268-521f86b1ed0e.png">



我的其他umi配置
<img width="2708" alt="WeChat09df2c8a23e7bc2a07c7a3add87b7661" src="https://user-images.githubusercontent.com/38500885/134448303-25ddc26c-a03a-4e7e-bc7f-5afa9b13afd9.png">

**Comment by xiefengnian** [comment]
在配置文件加上
`webpack5:{}`

**Comment by xiaohuoni** [comment]
@xiefengnian 他的配置已经有了

**Comment by leoner** [comment]
https://github.com/eggjs/egg-ant-design-pro

用这个 demo 应该就可以复现， 就是用这个例子， 升级了 mfsu 就会报这个错误

**Comment by hejintaoaiyulan** [comment]
config.js中添加 `webpack5: {}` 就可以了
