### ISSUE TITLE
[Bug] 配置chainWebpack里的optimization，用户配置被覆盖

### ISSUE THREAD

**Issue by DENNIE-HONG** [umijs/umi#7362]
#### 1、config.ts里配置了chainWebpack里的optimization，开发环境development，js被压缩了
![image](https://user-images.githubusercontent.com/23476088/134451236-f4138f17-568a-42be-be11-a33eae085758.png)

#### 2、以为是splitChunks问题，所以只配置了minimize:false, 无法生效
![image](https://user-images.githubusercontent.com/23476088/134451356-4da9cae0-3a6a-4bb0-8380-8ccd87cfc544.png)

#### 3、打印出配置信息，发现minimizer已经被配置了，用户的配置优先级不是最高？
![image](https://user-images.githubusercontent.com/23476088/134451521-c8142c93-063d-455f-a0a7-03b6ff8e5055.png)
![image](https://user-images.githubusercontent.com/23476088/134451724-6e11913f-254e-4382-a3fb-a70af0431c3c.png)
![image](https://user-images.githubusercontent.com/23476088/134451799-97efc426-6b45-4619-988a-614ff03d3492.png)

url：https://github.com/umijs/umi/blob/master/packages/preset-built-in/src/plugins/commands/buildDevUtils.ts

- **Umi Version**:3.2.14
- **Node Version**:12.13.0
- **Platform**:mac

**Comment by aeroxy** [comment]
不愧是阿里出品
