### ISSUE TITLE
代理请求的bug，正好有请求接口是 "/u/*/*" 这种的，结果设置代理后报错umi.js报404错误？

### ISSUE THREAD

**Issue by Jude214** [umijs/umi#738]
应该是设置了 "/u":{"target": "https://*.**.*", "changeOrigin": true}之后，本地请求umi.js的时候也给代理到我设置的服务器上去了，所以报404错误，请问该如何解决这种请求接口是"/u"开头与umi.js的冲突？？

**Comment by sorrycc** [comment]
proxy 的优先级应该是最高的，直接访问代理服务器可以访问到吗？

**Comment by Jude214** [comment]
我的意思，代理请求时，某个接口正好是以 /u 开头的，这时候设置 /u 代理，本地开发模式umi.js的请求也被代理到应用服务器，而应用服务器中没有umi.js资源导致报404错误。
我的解决方案是将 /u 开头的接口代理拆分为更具体的 /u/a、/u/b、/u/c这种形式，umi.js的请求就不会被匹配上
