### ISSUE TITLE
[Bug] npm run start for new ant design pro with umi is not working

### ISSUE THREAD

**Issue by ChendyRewa** [umijs/umi#7391]
I am getting a following error, while starting the ant design pro project with umi:-

AssertionError [ERR_ASSERTION]: chunk of umi not found.
    at \node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:104:27
    at Array.forEach (<anonymous>)
    at chunksToFiles (\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:93:14)
    at \node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:189:32
    at Generator.next (<anonymous>)
    at asyncGeneratorStep \node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:62:103)
    at _next (\node_modules\umi\node_modules\@umijs\preset-built-in\lib\plugins\commands\htmlUtils.js:64:194) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}

I am following below steps :- 
https://pro.ant.design/docs/getting-started

**Comment by xiefengnian** [comment]
Probably because mfSU is turned on, the dependency is being precompiled
