### ISSUE TITLE
[Bug] 开启MFSU时使用require('')出现bug, 无法正常得到require的返回内容

### ISSUE THREAD

**Issue by undo-nothing** [umijs/umi#7393]
## What happens?
当我使用antd-pro 5.0（"umi": "^3.5.0"）,配置开启MFSU功能，并根据umijs文档配置动态路由（https://umijs.org/zh-CN/docs/runtime-config#patchroutes-routes-）

```
export function patchRoutes({ routes }) {
  routes.unshift({
    path: '/foo',
    exact: true,
    component: require('@/pages/Welcome').default,
  });
}
```
无法正常工作，页面访问'/foo' 没有提示404，没有任何输出
cmd提示：[MFSU] require('@/pages/Welcome') found in D:\Git\sweet-taro-react\src\app.tsx, which will broken the MFSU prebuild match, please change to esm module import.
猜测路由配置正确，component错误
尝试直接import Welcome '@/pages/Welcome', 页面正常显示'@/pages/Welcome'内容
尝试使用await import代替require，代码如下
```
let extraRoutes = {
  path: '/foo',
  exact: true,
  component: (await import('@/pages/Welcome')).default,
};

export async function patchRoutes({ routes }) {
  routes.unshift(extraRoutes);
}
```
页面正常显示'@/pages/Welcome'
cmd有报错提示：(node:22412) UnhandledPromiseRejectionWarning: SyntaxError: 'await' is only allowed within async functions.

## Context

- **Umi Version**: ^3.5.0
- **Node Version**: v14.17.0
- **Platform**: windous

**Comment by xiefengnian** [comment]
麻烦提供一个最小复现仓库

**Comment by undo-nothing** [comment]
> 麻烦提供一个最小复现仓库

https://github.com/undo-nothing/antd-pro-bug.git
一共两个提交
1. ant design init
2. 重现bug提交

**Comment by 1247748612** [comment]
mfsu不支持require

**Comment by 1247748612** [comment]
可采用[dynamic引入](https://umijs.org/zh-CN/api#dynamic)
```typescript
dynamic({
  loader: async () => import(`./features/xxxx.tsx`),
})
```

**Comment by undo-nothing** [comment]
> 可采用[dynamic引入](https://umijs.org/zh-CN/api#dynamic)
> 
> ```ts
> dynamic({
>   loader: async () => import(`./features/xxxx.tsx`),
> })
> ```
谢谢，测试可行！

**Comment by undo-nothing** [comment]
> 麻烦提供一个最小复现仓库

楼上方法dynamic引入测试正常工作，能否作为方案，修改到官方文档呢

**Comment by undo-nothing** [comment]
> 可采用[dynamic引入](https://umijs.org/zh-CN/api#dynamic)
> 
> ```ts
> dynamic({
>   loader: async () => import(`./features/xxxx.tsx`),
> })
> ```

不过这个办法也有一定的局限性，如果要传入import是一个变量，必须局限在一定的范围，也会影响webpack打包这个范围内的所有文件。
参考：https://stackoverflow.com/questions/49121053/how-to-use-a-webpack-dynamic-import-with-a-variable-query-string

**Comment by 1247748612** [comment]
> > 可采用[dynamic引入](https://umijs.org/zh-CN/api#dynamic)
> > ```ts
> > dynamic({
> >   loader: async () => import(`./features/xxxx.tsx`),
> > })
> > ```
> 
> 不过这个办法也有一定的局限性，如果要传入import是一个变量，必须局限在一定的范围，也会影响webpack打包这个范围内的所有文件。
> 参考：https://stackoverflow.com/questions/49121053/how-to-use-a-webpack-dynamic-import-with-a-variable-query-string

是的，不过不影响使用
