### ISSUE TITLE
[Bug] IE11运行dev报错

### ISSUE THREAD

**Issue by quicklearning123** [umijs/umi#7394]
## What happens?

![image](https://user-images.githubusercontent.com/70048681/134863614-209a6f8a-bf3c-480b-bd03-b3202e9bef0f.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

按官网默认生成的demo

## Context

- **Umi Version**: 3.5.19
- **Node Version**: 14.7
- **Platform**: mac os

**Comment by quicklearning123** [comment]
求求大佬们了~更新版本前先在IE11上跑下，毕竟咱们官方还是声明支持IE11的吧

**Comment by shareisall** [comment]
同样遇到这个问题。

**Comment by shareisall** [comment]
哎，umi.js，想说爱你不容易。就只想说垃圾了，还是好好去学angular

**Comment by ILiZihan** [comment]
> 哎，umi.js，想说爱你不容易。就只想说垃圾了，还是好好去学angular

你用angular的项目在iE11上面不报错吗

**Comment by 0x457** [comment]
我也遇到这样子问题，急啊，客户只有11

**Comment by Iwouldliketobeapig** [comment]
同款报错，build是可以的，但是本地开发start就不行，来issues看看有没得已经解决了的

**Comment by Iwouldliketobeapig** [comment]
看下是哪个包在报错，我这样解决的，devScript.js哪个不管也能在ie上跑起来，都是es语法的问题
![image](https://user-images.githubusercontent.com/20534862/151168631-1a4886bc-b860-4cab-81cc-530d4a369fbf.png)
分析到是@umi/bundler-webpack，然后做了如下操作
![image](https://user-images.githubusercontent.com/20534862/151168695-a883ef45-dad2-4454-a2cf-d91266749619.png)

**Comment by yang-chuanjiang** [comment]
@Iwouldliketobeapig 请问path怎么定义的，以及@hz是node_modules文件夹下哪个文件

**Comment by Iwouldliketobeapig** [comment]
> @Iwouldliketobeapig 请问path怎么定义的，以及@hz是node_modules文件夹下哪个文件

@hz是我司自己的npm包，你不用关心，你看我截图里面用红色圈起来的部分，分别是发现问题的地方和解决问题的方法，看能不能帮助到你
