### ISSUE TITLE
使用次加速方案后，有时候会报错，导致项目无法启动，上面是正常启动的，下面加上后加报错了

### ISSUE THREAD

**Issue by doulongfei** [umijs/umi#7406]
Compiled successfully in 194889ms                                                                    上午11:04:51

  App running at:
  - Local:   http://localhost:8000 (copied to clipboard)
  - Network: http://169.254.172.156:8000

启动时间有点慢，试试新出的 MFSU 方案，1s+ 完成启动，详见 https://github.com/umijs/umi/issues/6766

√ Webpack
  Compiled successfully in 1.08m

√ Webpack

 DONE  Compiled successfully in 64997ms                                                                     上午11:08:34

  App running at:
  - Local:   http://localhost:8000 (copied to clipboard)
  - Network: http://169.254.172.156:8000
AssertionError [ERR_ASSERTION]: filePath not found of E:/IUES/IUESDemo666/IUES/ClientApp/node_modules/@umijs/bundler-utils/node_modules/@babel/runtime/helpers/esm/asyncToGenerator

**Comment by uniubi-ui** [comment]
我也报错 开启mfsu就报错
![image](https://user-images.githubusercontent.com/67054876/135245095-dfa0cd22-c01c-4473-b62d-bbc07af7f228.png)
