### ISSUE TITLE
动态路由 如何获取路由参数

### ISSUE THREAD

**Issue by zhanchengkun** [umijs/umi#741]
route : "path": "/business/:id?/:test"

如何 获取id 跟test的参数值

**Comment by sorrycc** [comment]
`match.params.id` 和 `match.params.test`，参考 https://reacttraining.com/react-router/web/example/url-params

**Comment by lehug** [comment]
match 和computedMatch差别是啥呢？

**Comment by noscripter** [comment]
> match 和computedMatch差别是啥呢？

@lehug computedMatch 其实是个内部属性，在 Switch 和 Route 之间用到，公开的 API 参数要用 match。

`computedMatch`会触发开发版本 React 的`unknown prop`⚠️。
