### ISSUE TITLE
mfsu缓存了node_modules里面的内容

### ISSUE THREAD

**Issue by henryzp** [umijs/umi#7410]
## Background

业务组件通过yarn link到业务工程的node_modules中，期望能进行代码调试

## Proposal

mfsu能提供配置某些npm包能不用缓存的方法。不然每次需要删除整个mfsu的文件，再重启项目

## Additional context

另外想问一下碰到我上面这样的需求，有没有更好的解法？因为业务组件光写DEMO，可能测试面不全，有些还是得放到业务工程里面去校验一下的

**Comment by xiefengnian** [comment]
mfsu 并没有缓存 node_modules，是通过 ast 分析导入进行预编译。是不是你的业务组件需要配置 main, modules 或者其他入口？

**Comment by henryzp** [comment]
啊？？那不应该啊。。我的业务组件配置了main、modules这些入口了。。

但是我对比了一下，如果关闭mfsu，改了业务组件的内容，只要重启业务工程就行了（yarn dev），就会生效了。

不关闭mfsu，则会有缓存，必须强行删除文件夹才行（.mfsu-dev和src/.umi），然后重启工程就OK了。

.mfsu-dev是我配置的mfsu的dev的output

另外，还有一个问题是：为了方便调试，我指向的是src里面的源码来进行调试，不开启mfsu是我想要的效果，但开启mfsu是babel转了一层的代码。

**Comment by xiefengnian** [comment]
确实没有考虑开 mfsu 调试包的问题... mfsu 做了预编译实际上就是把你的组件预编译进去了，建议还是关掉 mfsu 研发组件吧

**Comment by henryzp** [comment]
@xiefengnian ，问一下，关掉mfsu的话，每次改了组件，都要关掉服务，重启服务（或者改config.ts文件来重新restart），有更好的方式没？ @

**Comment by xiefengnian** [comment]
可以考虑设置一个 webpack 的 alias 直接指向包？

**Comment by henryzp** [comment]
@xiefengnian ，木用。。不确定是不是我的配法有问题：

我是这样写的：

```js
{
  alias: {
       '@dzg/dawn': join(__dirname, '../node_modules/@dzg/dawn')
  },
}
```

`@dzg/dawn`是我的组件包名。。另外我在下面配了一个按需加载：

```js
extraBabelPlugins: [
    [
      'babel-plugin-import',
      { libraryName: 'antd', libraryDirectory: 'es', style: true },
      'antd',
    ],
    [
      'babel-plugin-import',
      { libraryName: '@dzg/dawn', libraryDirectory: 'src', camel2DashComponentName: false, style: false },
      '@dzg/dawn',
    ]
  ]
```

理论上按你说的，我修改了node_modules里面的@dzg/dawn下面的文件后，会进行热更新代码的。。但是并没有

**Comment by darknessjs** [comment]
同样需求，求个后续

**Comment by sunxia628** [comment]
同问，搞了半天，打包、删文件，不知道究竟是哪里缓存了-_-

**Comment by jasonHzq** [comment]
没解决问题也关闭 issue 吗= =，好不专业
