### ISSUE TITLE
[Feature Request] 插件的引入支持 exports

### ISSUE THREAD

**Issue by wen-haoming** [umijs/umi#7414]
## Background

希望 umi 能够支持这样的插件引入格式？

```ts

import { defineConfig } from 'umi';

export default defineConfig({
   plugins:[('my-plugin/umi')],
});

```

比如很多库都利用了 package.json 的 exports 字段

```json
  "exports": {
    ".": {
      "node:": "./dist/index.js",
      "default": "./dist/index.cjs.js"
    },
    "./umi": {
      "import": "./dist/plugins/umi/index.js",
      "require": "./dist/plugins/umi/index.cjs.js"
    },
    "./webpack": {
      "import": "./dist/plugins/webpack/index.js",
      "require": "./dist/plugins/webpack/index.cjs.js"
    }
  },
```

引用的时候

```ts
import umiplugin  from 'my-plugin/umi'
```

这样的好处就是一个包就能包含众多环境的插件配置，同时还能根据环境到底是 cjs 引入还是 esm的模块引入

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by wen-haoming** [comment]
可以使用  plugins:[`require.resolve('pkg/umi')`]  的形式来支持

**Comment by hugeorange** [comment]
> 可以使用 plugins:[`require.resolve('pkg/umi')`] 的形式来支持

@wen-haoming 你好，请问上面写法是什么意思呀，按照上面的写法写在 .umirc 里面并没有效果，好像也没有 `pkg/umi`这个plugin呀

**Comment by jinmmd** [comment]
我的解决方法是开启 webpack5，然后在 chainWebpack 中写 resolve.fallback 支持用 ‘path-browserify’
