### ISSUE TITLE
export 'MicroApp' (imported as 'MicroApp') was not found in 'umi'

### ISSUE THREAD

**Issue by 3338606790** [umijs/umi#7415]
```
 import React from 'react';
import { MicroApp } from 'umi';

const TemplateEditor = () => {
  return (
    <MicroApp name="template_editor" autoSetLoading />
  )
}
```

export default TemplateEditor;

WARNING  Compiled with 1 warnings                                                                                                                           上午12:24:09 warning  in ./src/pages/template/index.tsx export 'MicroApp' (imported as 'MicroApp') was not found in 'umi' 

```
"umi": "3.5.20",
 "@umijs/plugin-qiankun": "^2.33.1",
```

**Comment by PingZaiDotTse** [comment]
+1 无解中.....

**Comment by NoobWhite** [comment]
这个为啥关掉了，我也有这个问题，不过我用的是umi/max
