### ISSUE TITLE
路由search发生变化但是withRouter包裹的组件render没被触发

### ISSUE THREAD

**Issue by suiyi8760** [umijs/umi#742]
开始以为是跟这个issue差不多问题 #245 ，但后来发现connect即使去掉了也一样

具体表现:
点击按钮跳转到加了`?xx=xx`的链接但是withRouter包裹下的组件的render过了一会才触发，如果给按钮加上forceUpdate会发现`props.location`没有变化，但实际上地址栏已经加上了`?xx=xx`并且`window.location`的search已经立即变更了。观察redux-devtool发现似乎是routing这个state更新了才会触发withRouter包裹下的组件的router。

上codesandbox随手找了个react-router-demo测试下好像没这个问题。目前因为要根据location.query更新一些页面内容，路由改变不能立即render比较难搞，暂时用query-string吧window.location.search转一下，但是万一要兼容hashhistory会比较麻烦

**Comment by sorrycc** [comment]
给个可重现的例子吧。

**Comment by suiyi8760** [comment]
@sorrycc 可以，周末试试补一个能重现的demo

**Comment by suiyi8760** [comment]
找到原因了不是umi的问题，是由于connect包裹的组件shouldComponentUpdate为false后子组件获取不到context导致withRouter没更新，connect包裹的组件前再套一个withRouter就好了
