### ISSUE TITLE
[Feature Request] umi3.0文档，不知道去哪儿找，2.0文档部分资料已失效，无法正常使用umi

### ISSUE THREAD

**Issue by cmdparkour** [umijs/umi#7425]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by xiaohuoni** [comment]
现在官网的就是 umi@3 的文档 https://umijs.org/
你是有什么资料找不到？

**Comment by cmdparkour** [comment]
懂啦，我一直以为这个是1.0版本的文档
