### ISSUE TITLE
[Bug] mfsu开启，当有公用包中使用import('xxx')无法加载

### ISSUE THREAD

**Issue by 1247748612** [umijs/umi#7434]
## What happens?

有个方法在一个公用包下，使用了import 方法动态引入

```typescript
export async function authing() {
  return import(/* webpackChunkName: "AuthingComponent" */ '@authing/react-ui-components').then(
    (module) => {
      module.initAuthClient({
        appId: AUTHING_APPID,
      });
      // eslint-disable-next-line @typescript-eslint/consistent-type-imports
      return module as typeof import('@authing/react-ui-components');
    },
  );
}
```

.mfsu文件有AuthingComponent.xxx.async.js
但项目加载不到这个文件

尝试更改文件名为 mf_dep-AuthingComponent.xxx.async.js
然后主动去访问这个文件地址后成功

看情况好像是限制了mf文件前缀？

![image](https://user-images.githubusercontent.com/29533304/136643572-c63c1e8a-3fca-4244-a65c-7955af63b0d2.png)

**Comment by 1247748612** [comment]
去掉了webpackChunkName正常能访问了又出现了新的问题
然后lazyCompilation 报错
更改配置为：
```js
{
  webpack5: {
    lazyCompilation: {
      entries: false,
      imports: false,
    },
  }
}
```
后正常跑起来

### 新的问题

1. 多个包都使用了umi，components package 的 使用umi 的 useAccess 无法找到对应的access
2. mfsu缓存了一个common package的文件更改文件无法重新编译，没有排除某些node_modules的方法

**Comment by 1247748612** [comment]
> 我这边似乎也是这个问题，
> 
> 1. 将umi多语言的设置封到了二方包里，统一提供一个设置多语言的初始化方法
> 2. 使用了mfsu后，原先起作用的多语言就失效了，看了下拿到的多语言messages映射对象是空的，其Provider的value也是空的
> 3. 但是如果我单独将那串封装的方法拿到项目里用又是可以的
> 
> 似乎在mfsu启动时，二方包里的umi和mf里的umi不是一个样子

对的，已经放弃mfsu了

**Comment by comewithl** [comment]
> > 我这边似乎也是这个问题，
> > 
> > 1. 将umi多语言的设置封到了二方包里，统一提供一个设置多语言的初始化方法
> > 2. 使用了mfsu后，原先起作用的多语言就失效了，看了下拿到的多语言messages映射对象是空的，其Provider的value也是空的
> > 3. 但是如果我单独将那串封装的方法拿到项目里用又是可以的
> > 
> > 似乎在mfsu启动时，二方包里的umi和mf里的umi不是一个样子
> 
> 对的，已经放弃mfsu了

这种情况暂时先不开吧，不知道是不是没有支持二方包的umi处理还是自己使用得问题，整个依赖预编译体验还是可以

**Comment by programmer-yang** [comment]
> 去掉了webpackChunkName正常能访问了又出现了新的问题 然后lazyCompilation 报错 更改配置为：
> 
> ```js
> {
>   webpack5: {
>     lazyCompilation: {
>       entries: false,
>       imports: false,
>     },
>   }
> }
> ```
> 
> 后正常跑起来
> 
> ### 新的问题
> 1. 多个包都使用了umi，components package 的 使用umi 的 useAccess 无法找到对应的access
> 2. mfsu缓存了一个common package的文件更改文件无法重新编译，没有排除某些node_modules的方法

使用mfsu遇到了一个类似的问题，按文档配置了`src/access.ts`文件，启动项目后报：`export 'useAccess' (imported as 'useAccess') was not found in 'umi'`，检查后发现是插件没有正常挂载，在配置文件里添加`access: {}`后解决
