### ISSUE TITLE
为啥我开启了SSR，但是还是渲染的csr

### ISSUE THREAD

**Issue by livelyPeng** [umijs/umi#7436]
![image](https://user-images.githubusercontent.com/32978177/136777120-750edc36-fe92-414c-a8ce-9f27a04f6aa1.png)

<html>
<body>

<body>
--
  | <div id="root"></div>  为啥我这里没有东西啊，为啥啊
  | <script>
  | window.g_useSSR = true;
  | window.g_initialProps = {};
  | </script>
  |  
  | <script src="http://127.0.0.1:3000/umi.js"></script>
  |  
  |  
  | </body>

</body>
</html>

我发现了很严重的问题：在APP。js入口  使用       umijs3.2.1 ssr 添加 getInitialState 后无法获得ssr渲染   就是这个问题导致的

**Comment by liucong1** [comment]
一旦使用了 getInitialState 就会在渲染的时候降级为 CSR
