### ISSUE TITLE
急啊，求作者解决下，为啥我使用SSR后，然后项目请求接口跨域，然后我去配置proxy，但是启动服务后，请求接口默认把我的接口当做是页面在访问呢？

### ISSUE THREAD

**Issue by livelyPeng** [umijs/umi#7440]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

BUG很多啊，为啥我使用SSR后，然后项目请求接口跨域，然后我去配置proxy，但是启动服务后，请求接口默认把我的接口当做是页面在访问呢？
![image](https://user-images.githubusercontent.com/32978177/136877172-36bd9db1-f4de-4d00-8d7a-d6e2e4c53a2d.png)

![image](https://user-images.githubusercontent.com/32978177/136877085-6eb12b58-f0cb-40e9-b2ac-1ebba867de99.png)
![image](https://user-images.githubusercontent.com/32978177/136877105-a25d678a-3620-426a-a5f2-acca5346b241.png)
他会给我当为是404页面访问了啊、

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by Simoon-F** [comment]
需要在nginx做转发？
