### ISSUE TITLE
[Feature Request] ssr渲染时从path中获取语言

### ISSUE THREAD

**Issue by ilp64** [umijs/umi#7442]
## Background

比如访问不同的路径 /zh/news /en/news，可以从路径中获取到当前语言是zh还是en。
我现在使用umi 3，把baseNavigator和useLocalStorage都设置成了false，在app.ts中重写getLocale方法，但是不知道如何获取到路径相关的信息。
```typescript
export const locale = {
  getLocale: () => {
    // 这里如何获取到路径相关的信息呢?
    return 'lang code';
  }
}

```
## Proposal

能否在getLocale中加入路径相关信息的参数，比如
```typescript
export const locale = {
  getLocale: (url: string) => {
    if (url.startsWith('/zh/')) {
      return 'zh-CN';
    }
    ......
  }
}
```

**Comment by tdw143** [comment]
@ilp64 有解决的方法了吗

**Comment by ilp64** [comment]
> @ilp64 有解决的方法了吗

没想到这么久过去了，还会有这个问题，我已经很久没有使用umi了，所有现在官方有没有提供相关的方法我不太清楚。
依稀记得我那个时候好像是在做ssr的node服务中获取的，有2种情况：
1. 比如访问/zh/news，然后解析出lang是zh，把这个lang注入到ssr render的context中
2. 如果路径中没有带语言代码路径，比如直接访问/news，那会从request headers中获取语言lang，然后重定向到/:lang/news，变成第一种情况
