### ISSUE TITLE
SecurityError: An insecure SockJS connection may not be initiated from a page loaded over HTTPS

### ISSUE THREAD

**Issue by nxg916** [umijs/umi#7445]
## What happens?
![image](https://user-images.githubusercontent.com/7166587/136914375-0e54203d-dc24-4b05-b7fe-997bc905a62d.png)

访问的url 地址是 https 开头的， 实际访问是通过nginx代理转发到127.0.0.1。 如果使用http://localhost访问没有问题， 如果用https访问就会报上面的错误，导致页面白屏。
有什么方法屏蔽这个问题或者解决这个问题？？？

## Context

- **Umi Version**: 3.5.20
- **Node Version**:14.15.1
- **Platform**:mac-chorme

**Comment by flyingFlowers** [comment]
+1

**Comment by WLyKan** [comment]
我用`@umijs/create-umi-app`创建了两个项目，然后配置`https: true`，两个项目都启动后，只有一个8000端口的项目能访问，8001端口就报错❌：`Uncaught Error: SecurityError: An insecure SockJS connection may not be initiated from a page loaded over HTTPS`。debug发现 new SockJS传入的url`http://localhost:8001/dev-server`不是https的，是什么原因呢?

**Comment by jianghai** [comment]
为什么关了，有解决方法吗

**Comment by jianghai** [comment]
先关了 HMR 吧
