### ISSUE TITLE
服务端渲染，为啥dva报错啊？

### ISSUE THREAD

**Issue by parlay96** [umijs/umi#7452]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

 
这是代码： 

// 服务端渲染请求数据
HomePage.getInitialProps = (async ({ isServer }) => {
  // getInitialProps 在服务端。没有跨域的限制。
  // 判断是否为服务端在执行该方法。
  if (!isServer) {
    return { data: [],}
  }
  const data = await FetchBanners({
    account: "",
    area_id: 0,
    classify_id: "",
    down_flush: 0,
    is_full: 0,
    joblisttype: "newest",
    keywords: "",
    location: "",
    page: 1,
    pageSize: 15,
  })
  if (data.head.code == 200) {
    return {
      data: data.data.list,
    }
  }
  return {
    data: [],
  }
}) as IGetInitialProps

Unexpected key "data" found in preloadedState argument passed to createStore. Expected to find one of the known reducer keys instead: "router", "@@dva", "textModel", "loading". Unexpected keys will be ignored.

这是错误：不返回data 就不报错！

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by zemelLeong** [comment]
大佬解决了吗？我也遇到同样的问题

**Comment by livelyPeng** [comment]
解决了啊  https://umijs.org/zh-CN/docs/ssr#数据预获取

**Comment by zemelLeong** [comment]
怎么解决的啊？这份文档看不出来可以怎么做  
我是如果使用了dva的model就会报类似这样的警告，或者用了`getInitialProps`不return数据也不会报警告

**Comment by zemelLeong** [comment]
报这个警告以为无伤大雅，结果发现它把我`getInitialProps`返回的数据都清除了
