### ISSUE TITLE
umi在production时是对没有传递props的函数做了优化吗？

### ISSUE THREAD

**Issue by icarusysuper** [umijs/umi#746]
@sorrycc 

> src/pages/index.js

```
import React from 'react'

export default class IndexPage extends React.Component {
  state = {
    val: 5
  }

  componentDidMount() {
    setInterval(() => {
      const val = this.state.val + Math.ceil(Math.random() * 10)
      this.setState({ val })
    }, 1000)
  }

  render() {
    console.log('d render')
    return (
      <div>
        <h1>{this.state.val}</h1>
        <Test />
      </div>
    )
  }
}

class Test extends React.Component {
  render() {
    console.log('s render')
    return <div>{Math.random()}</div>
  }
}
```

这段代码，在umi dev时，会打印
d render
s render
d render
s render
...
但在umi build后，serve运行dist目录，只会打印
d render
...
umi在development与production表现不一致。

在create-react-app中进行测试，无论development还是production都表现一样。

**Comment by icarusysuper** [comment]
如果对这段代码的`<Test />`传递val作为其props（但这个props没有被Test使用到，是无意义的），则是development与production都会触发Test组件的render。

猜测是：外层state变化，重新render，但由于<Test />不收外层state影响，没有传递props进去，所以Test Component没有render。

**Comment by sorrycc** [comment]
重装依赖试试，之前在 production 下有两个 babel 插件做优化的，在 [umi@1.3.17](https://github.com/umijs/umi/releases/tag/umi%401.3.17) 里去掉了。

**Comment by icarusysuper** [comment]
thx
