### ISSUE TITLE
[BUG]openapi1.3.0自定义customClassName问题

### ISSUE THREAD

**Issue by quicklearning123** [umijs/umi#7463]
## What happens?

生成的文件名用的是customClassName。但自定义入参太少，只有tag。通常tag我们用中文。不适合用来做文件名。
自定义customClassName返回值后，生成的index.ts里面没有用自定义的名称。还是自定义前的默认名称即tag。

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context
@umijs/openapi 1.3.0
- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sun-shu** [comment]
同问
