### ISSUE TITLE
[Bug] mfsu在umi build之后，为什么MFSU_CACHE.json的tmpDeps不是{}?

### ISSUE THREAD

**Issue by ILuZhangKun** [umijs/umi#7470]
## What happens?
我的操作是：
1. 在.umirc中配置`mfsu: { production: {} }`
2. 执行umi build，生成～/.mfsu-procuction

发现第一遍执行umi build的时候，生成的MFSU_CACHE.json中deps是{}, tmpDeps中是依赖的本地路径和版本号
再次执行umi build后，deps中会生成依赖的路径，是把tmpDeps中的本地路径替换成$CWD$，tmpDeps没有改变

我看了一下源码，在packages/preset-built-in/src/plugins/features/mfsu/DepInfo.ts中，loadTmpDeps执行后会把tmpDeps清空
```javascript
  loadTmpDeps(): { shouldBuild: boolean } {
    const shouldBuild = this.shouldBuild();
    if (shouldBuild) {
      Object.assign(this.data.deps, this.data.tmpDeps);
      this.data.config = this.getConfig();
      // clear tmp deps
      this.data.tmpDeps = {};
    }
    return { shouldBuild };
  }
```
我的问题是，为啥temDeps没有被清空呢？

这个导致的问题是，会报找不到文件的错误。
![image](https://user-images.githubusercontent.com/32009694/137469289-a6a7d686-fccc-4723-a919-3ece4eebed8c.png)
我目前的解决方式是，手动把tmpDeps清空后再部署。

## Context

- **Umi Version**: 3.4.25
- **Node Version**: v14.18.0
- **Platform**: macOS

**Comment by devenliu** [comment]
我大胆的猜测一下，有可能是因为 umi 的插件机制导致的，因为可以看到 .umi/ 目录下的 (.js | .ts) 文件当中，有的 import 是采用的绝对路径，

再对照 MFSU_CACHE.json 文件的 tmpDeps ，发现和 .umi/ 目录下 import 的绝对路径一样

**Comment by wangzhengbo** [comment]
没有修复怎么就close了呢？
