### ISSUE TITLE
[Bug] 配置publicPath后，打开mfsu，build后static文件上传三方cdn后，前端访问出现".xxxxxxxxxxxxxxx/_@umijs_runtime@3.5.20@@umijs/runtime" does not exist in container

### ISSUE THREAD

**Issue by paul-xia** [umijs/umi#7473]
## Mini Showcase Repository(REQUIRED)

> rep: https://github.com/paul-xia/umibug-unwork-publicpath

## How To Reproduce

npm i && npm run build
上传dist目录资源到publicPath对应目录.
serve dist
浏览器访问serve port
出现如下图
![image](https://user-images.githubusercontent.com/12042999/137588606-2d2d284f-b67c-436b-bf2b-44de5c4a63ea.png)
## Context

- **Umi Version**: 3.5.20
- **Node Version**: 14.16.1
- **Platform**:  eve

**Comment by paul-xia** [comment]
mf-va_remoteEntry.js
这个文件内容在变，然而文件不带自身hash，造成缓存冲突，这怎么处理

**Comment by dashaowang** [comment]
请问下有结果吗？我也是报了这个错误

**Comment by SoldierAb** [comment]
怎么就关了呢， 一样的问题

**Comment by vaynevayne** [comment]
同样的问题, 有什么办法清空缓存吗
