### ISSUE TITLE
[Bug] 热更新太慢，

### ISSUE THREAD

**Issue by jimStyle88** [umijs/umi#7474]
本地开发热更新太慢 !!! 

首次启动：
Compiled successfully in 217289ms 
修改一个文字耗时
 DONE  Compiled successfully in 47202ms 

 umi 版本：3.5.20 
项目路由：100+

 已阅读过 https://github.com/umijs/umi/issues/5827   ，
 并对项目依据 https://umijs.org/zh-CN/guide/boost-compile-speed  进行优化，还是没能提升编译速度。
 MFSU 方案   目前还有坑，暂不考虑使用
 期望：
 1、官方可以提供优化方案

感谢大佬。

**Comment by yaodong5063** [comment]
同，路由差不多，热更新要10秒，去了sourcemap会快很多

**Comment by zhangchao828** [comment]
多大的项目啊，那么慢，我们差不多有100个路由页面，也不慢啊

**Comment by Tenodec** [comment]
> 



> 多大的项目啊，那么慢，我们差不多有100个路由页面，也不慢啊

这个跟项目依赖有关系的。100多个全是自己实现和100多个用了很多第三方包区别还是很大的

**Comment by Tenodec** [comment]
> 同，路由差不多，热更新要10秒，去了sourcemap会快很多

项目不大可以考虑往ice迁移

**Comment by RegExpRegExp** [comment]
[https://umijs.org/zh-CN/docs/env-variables#watch]
"dev": "cross-env UMI_ENV=dev WATCH=none npm run start:dev",
绝了：WATCH = none 依然监听热加载，并且速度上去了。笑死我了。哈哈哈哈。真牛鼻。

**Comment by RegExpRegExp** [comment]
[https://umijs.org/zh-CN/docs/env-variables#watch](url)
"dev": "cross-env UMI_ENV=dev WATCH=none npm run start:dev",
绝了：WATCH = none 依然监听热加载，并且速度上去了。笑死我了。哈哈哈哈。真牛鼻。

**Comment by bobsivian** [comment]
> [https://umijs.org/zh-CN/docs/env-variables#watch](url) "dev": "cross-env UMI_ENV=dev WATCH=none npm run start:dev", 绝了：WATCH = none 依然监听热加载，并且速度上去了。笑死我了。哈哈哈哈。真牛鼻。

感谢!!!!!    30s=>5s

**Comment by w493189140** [comment]
umirc试着加一下如下配置
nodeModulesTransform: {
    type: 'none',
    exclude: [],
  },
  targets: {  
    chrome: 79,
    firefox: false,
    safari: false,
    edge: false,
    ios: false,
  },
  devtool: 'eval'
