### ISSUE TITLE
[Feature Request] show unaccessible router in the menu

### ISSUE THREAD

**Issue by talentjeff** [umijs/umi#7479]
## Background

I use plugin-access and plugin-layout to control the routers. In current design, the unaccessible routers won't be shown.
But I want to show the unaccessible routers in the menu and these routers are clickable. The routers will show 503 page.(This part is already achieved)

## Proposal

Add a key in router, make the router alway be visible.
Example: define a new key 'visible' to make the router alway be visible. even if the router is unaccessible
`{ path: '/user/detail', component: './user/detail', access: 'abc', visible: true  }`

## Additional context

I‘m in an emergency to complete the feature. It will be better that someone cloud give me around to achieve the feature.
Thanks a lot!
目前无权限的路由在菜单不显示，业务上目前希望在菜单上显示，并且可点击，进入该页面仍旧显示无权限页面

**Comment by hackers267** [comment]
这个情况可以使用Access组件来包裹页面文件，路由不做配置就行
