### ISSUE TITLE
Maybe need to support custom SSL certificates locally for https.

### ISSUE THREAD

**Issue by BeAce** [umijs/umi#748]
I make a web app that interact with the hardware, like u2f. I need my own certificates config. So this is a little bit modify for the code in [af-webpack](https://github.com/umijs/umi/tree/master/packages/af-webpack) which I think it will be better.

```javascript
const serverConfig = {
  https: !!process.env.HTTPS,
  cert:!!process.env.HTTPS ? fs.readFileSync('/Users/beace/Desktop/cert/localhost+1.pem') : '',
  key: !!process.env.HTTPS ? fs.readFileSync('/Users/beace/Desktop/cert/localhost+1-key.pem') : '',
}
```

**Comment by sorrycc** [comment]
Interested in submiting a PR?

**Comment by BeAce** [comment]
@sorrycc I don't know how to give a friendly tip for custom certificates, but only to add some environment variables.   Here is the [commit diff](https://github.com/umijs/umi/pull/759/commits/464d13d77d738c01734c36842c9c57c79315bd5e).

**Comment by sorrycc** [comment]
Closed via https://github.com/umijs/umi/pull/759
