### ISSUE TITLE
[Bug] 插件里的方法 api.registerGenerator 不存在

### ISSUE THREAD

**Issue by limi58** [umijs/umi#7480]
## What happens?

文档里是有的：https://umijs.org/zh-CN/docs/cli#umi-generate 

但实际上，插件里的方法 api.registerGenerator 不存在

所以，现在生成器还可以扩展吗？

## Context

- **Umi Version**: 3.5.20
- **Node Version**: 14.18.1
- **Platform**: windows 10

**Comment by dxlyf** [comment]
可以的，估计你写错了。除了插件文件本身支持es6，导入的其它文件必须是cjs格式的，如果你非要使用es6 请使用 api.babelRegister.setOnlyMap 注册再使用require导入
