### ISSUE TITLE
不同操作系统，打包的文件内容一致，但是hash不一致

### ISSUE THREAD

**Issue by xf564246963** [umijs/umi#7481]
## What happens?

umi初始化的新项目，umi版本3.5.20，在windows和linux上打包生成的文件名hash不一样。
但是文件内容完全一样（我了解的是umi的配置用的contenthash）。window上是umi.52f0d702.js，linux上是umi.e5a02910.js。

## Mini Showcase Repository(REQUIRED)
仓库地址：https://github.com/xf564246963/umi-hash-test
只是用npx @umijs/create-umi-app新建了一个项目

## How To Reproduce
1.在不同操作系统拉取项目
2.在各个系统上npm install
3.修改.umirc.ts配置的hash:true
4.分别在各自系统上打包
生成的文件hash不一致

## Context

- **Umi Version**:  ^3.5.20
- **Node Version**:  windows上是14.15.4；linux上是14.16.0
- **Platform**: windows是win10；linux是CentOS Linux release 7.7.1908

**Comment by zFitness** [comment]
是啊，效果似乎都不一样

**Comment by prophetw** [comment]
> 理论上不一样才是正常的现象。
* 基于node打包，然后 node 针对 win linux 可能部分子库是有一些区别的。
* 其他有区别的地方多了去了，win默认换行和linux换行的区别，node版本，node库不同等等都有可能导致区别。

> 另外为了保证打包一致，可以考虑，单独的打包服务器，打包一般都是由 类似 jenkins 去单独执行，一台专门编译的机器去处理，保证缓存的最大有效性。

> 还有一点你要是测试，`是否win和linux打包有区别`，最起码也得保证所有的依赖都完全一样的版本吧。

**Comment by xf564246963** [comment]
如果是用webpack打包，就不会有hash不一样的问题。umi不一样是因为umi.js里面的register是写的绝对路径，导致所有生成的chunk的hash也不一样了

**Comment by xf564246963** [comment]
不是说绝对路径会影响整个hash的生成，而是umi生成文件内容的时候把本机的绝对路径写到了文件里面

**Comment by xf564246963** [comment]
> > 理论上不一样才是正常的现象。
> 
> * 基于node打包，然后 node 针对 win linux 可能部分子库是有一些区别的。
> * 其他有区别的地方多了去了，win默认换行和linux换行的区别，node版本，node库不同等等都有可能导致区别。
> 
> > 另外为了保证打包一致，可以考虑，单独的打包服务器，打包一般都是由 类似 jenkins 去单独执行，一台专门编译的机器去处理，保证缓存的最大有效性。
> 
> > 还有一点你要是测试，`是否win和linux打包有区别`，最起码也得保证所有的依赖都完全一样的版本吧。
> 
> 推荐你看下这篇文章，[从源码看webpack的hash策略](https://juejin.cn/post/6844903942384517127)，作者提到代码的绝对路径不同都会影响到hash

我理解的理论，应该是webpack + react + typescript的组合在不同系统上打出来的包hash是一样的，那么其他的依赖都是可以兼容保证文件内容的生成跟系统无关。
