### ISSUE TITLE
文档示例错误

### ISSUE THREAD

**Issue by amazing416** [umijs/umi#7482]
文档中[Umi基础/路由章节 ](https://umijs.org/zh-CN/docs/routing)
`
    // url 为 /one/two 时匹配成功
    { path: '/one' },
    { path: '/one', exact: false },
 `
其中{ path: '/one' } 应该匹配失败，因为exact默认值为true

**Comment by xiaohuoni** [comment]
你官网是不是没刷新，我看到的和你不一样的页面
![image](https://user-images.githubusercontent.com/11746742/138056577-21bc05e9-880c-4d6f-9634-150f8919a9ad.png)
