### ISSUE TITLE
Umi build部署在Github pages后因为引导缺失当前目录“./”导致无法加载

### ISSUE THREAD

**Issue by soqt** [umijs/umi#749]
Umi build后在index.html 里面的加载JS文件是这样的 <script src="/static/umi.b883e77a.js"></script> 但是如果放在github pages，路由地址是  https://username.github.io/projectName ，加载JS和CSS文件的时候是直接加载了  https://username.github.io/static/umi.b883e77a.js ， 路由缺少了项目名称导致404无法加载。手动在/static 加点表示当前目录之后就能加载了（ <script src="./static/umi.b883e77a.js"></script>）。有没有办法在build的时候就直接加上点表示当前目录？已经试过build的时候用BASE_URL但是还是不能解决问题

**Comment by sorrycc** [comment]
这个问题在 umi@2 里解决了，可以等这周的 beta 版。

**Comment by soqt** [comment]
好的，谢谢！
