### ISSUE TITLE
路由切换会导致父组件layout重新渲染

### ISSUE THREAD

**Issue by hunanzhoujielun** [umijs/umi#7493]
![image](https://user-images.githubusercontent.com/48546899/138430449-b8f0062b-beaa-4a0a-ad33-ba801cf21c26.png)
这个是在layout组件的componentDidMount方法里面打印的，在同一路由中切换子级路由不会出现layout重新渲染。
如果父路由地址不一致，layout会重新渲染，导致layout里面所有的子组件里面的方法会重新执行

这是我的路由配置
![image](https://user-images.githubusercontent.com/48546899/138431382-6cd0ddc3-4b01-43d4-81ed-1249faf37e7b.png)

- **Umi Version**:3.5.20
- **Node Version**:14.14.0
- **Platform**:windows

**Comment by lurongze** [comment]
老哥，怎么关闭了问题，是解决了吗

**Comment by hunanzhoujielun** [comment]
> 老哥，怎么关闭了问题，是解决了吗

解决了

**Comment by lurongze** [comment]
怎么解决的啊，我也遇到这个问题了，不知道解决思路是什么

**Comment by hunanzhoujielun** [comment]
> 怎么解决的啊，我也遇到这个问题了，不知道解决思路是什么

![image](https://user-images.githubusercontent.com/48546899/148715587-da207c0e-896f-438a-a073-5174b5ee3a93.png)
看这个你就明白了

**Comment by lurongze** [comment]
哦哦，这样改啊，谢谢
