### ISSUE TITLE
[Bug] 执行 umi dev 指令报错依赖不存在

### ISSUE THREAD

**Issue by define9527** [umijs/umi#7503]
执行 umi dev 命令报错:

These dependencies were not found:

* umi/_runtimePlugin in ./src/pages/.umi/umi.js, ./src/pages/.umi/router.js
* umi/dynamic in ./src/pages/.umi/router.js
* umi/link in ./node_modules/umi-build-dev/lib/plugins/404/NotFound.js
* umi/withRouter in ./node_modules/umi-build-dev/lib/plugins/404/NotFound.js

To install them, you can run: npm install --save umi/_runtimePlugin umi/dynamic umi/link umi/withRouter

 ERROR CODE  ERR_WEBPACK_MODULE_NOT_FOUND

 DETAILS 

## 错误原因

    1. 文件确实不存在
    2. 大小写问题

如果 mac 下构建成功，而在 linux 下或云构建平台上构建失败，则基本可断定为大小写问题。

## 解决方案

如果是大小写问题，请仔细检查 import 或 require 的文件和目标文件的大小写是否一致。

复现仓库地址: git@github.com:define9527/umi-demo.git

运行环境:
window10
node v14.18.1
umi v2.2.4

**Comment by yuanbolin** [comment]
我也同样遇到类似的问题，请问有解决方式吗

**Comment by yuanbolin** [comment]
ERROR  Failed to compile with 3 errors                                                                                                                                                                                         13:36:15

These dependencies were not found:

* intl-messageformat in ./node_modules/umi-plugin-locale/node_modules/react-intl/lib/index.es.js
* intl-relativeformat in ./node_modules/umi-plugin-locale/node_modules/react-intl/lib/index.es.js

To install them, you can run: npm install --save intl-messageformat intl-relativeformat
