### ISSUE TITLE
关于 public 文件夹打包后的路径

### ISSUE THREAD

**Issue by remotesc2** [umijs/umi#751]
在打包过程中碰到个问题

如果 src/public 下有个 a.png 文件，我在代码中通过 src="/a.png" 进行使用，打包后，public 的内容被复制到了 dist/static 导致路径不对，这个有办法配置吗？

之前用 ant-design-pro，public 文件时直接复制到 dist 下，并没有增加一级目录

**Comment by sorrycc** [comment]
这个会有 break-change，在 umi@2 里不会有一级 static 目录了。

**Comment by remotesc2** [comment]
在当前的版本下，是没有办法通过一些手段暂时解决吗？
比如我想利用 webpack-plugin-copy，那默认的行为能覆盖吗？
