### ISSUE TITLE
[Bug] 开启msuf后，我的静态资源被裁切了

### ISSUE THREAD

**Issue by daifuyang** [umijs/umi#7513]
## 我开发了一个node_modules包，包中包含了一些基础样式。样式是通过图片import插入到style的background属性的。预览的时候图片被裁切了。就像这样

<img width="1434" alt="截屏2021-10-28 08 42 22" src="https://user-images.githubusercontent.com/19951467/139167314-9fe0b46d-bab5-452c-a3bf-d4fd5ca35518.png">

编译后的项目是这样，关闭mfsu就没有问题。

![截屏2021-10-28 08 47 38](https://user-images.githubusercontent.com/19951467/139167480-dd9d6eff-d1e6-49af-bd01-e104755cf7c6.png)

**Comment by zzzzyp** [comment]
我也遇到了+1

**Comment by heyuuuu** [comment]
问题是还没办法去修改构建图片的配置，这就比较致命了。。。
