### ISSUE TITLE
开启生产mfsu，上传.mfsu-production至git,其他人无法根据此依赖打包

### ISSUE THREAD

**Issue by zyieng** [umijs/umi#7517]
## What happens?

开启生产mfsu，上传.mfsu-production至git,其他人无法根据此依赖打包。

## Repositories
https://github.com/zyieng/umi-mfsu-production

## How To Reproduce
  我已将.mfsu-production文件上传上面仓库中，拉取代码并打包，将打包好的静态跑在本地nginx服务上，依赖加载失败。
  我自己排查了一下，虽然MFSU_CACHE.json里写的是相对路径，但是mf_va_前缀开头的文件是开发环境下的绝对路径。将这些删除后再打包则没有问题。但是这样的话速度跟普通的打包速度是没有区别的，甚至要更久。
![image](https://user-images.githubusercontent.com/50657898/139393432-e2729447-2156-4c1e-95ad-b80b81bc538e.png)
  官网上写的是把这个文件丢到git，另一个开发者就可以使用。不清楚是官网叙述有误，还是说这是个bug，当然也不排除我使用有误。麻烦大佬看一下！

## Context

- **Umi Version**:3.5.20
- **Node Version**:14.8.0

**Comment by zyieng** [comment]
comment for track

**Comment by jiangdexiao** [comment]
官网文档写的就是个坑,官网如果没写错, 这就是个bug, 好多人遇到这问题

**Comment by jiangdexiao** [comment]
是bug

**Comment by wangzhengbo** [comment]
这个bug在3.x版本修复了吗？

**Comment by wangzhengbo** [comment]
4.x版本还是有问题，这么长时间没修复，看来没人处理了。
