### ISSUE TITLE
[Feature Request]希望能支持离线应用

### ISSUE THREAD

**Issue by mybedhome** [umijs/umi#7518]
## Background
离线模式下报这个错误:
```
umi.js:1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('file://') does not match the recipient window's origin ('null').
```
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by lilangkit** [comment]
离线模式  最好路由用hash 
这个报错无关紧要 估计是内嵌情况下上报 父窗口的

// 静态文件路径
  publicPath: `./`,
  // 配置 favicon 地址
  favicon: false,
  // 路由模式
  history: { type: 'hash' },
