### ISSUE TITLE
[Bug] React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

### ISSUE THREAD

**Issue by buyili** [umijs/umi#7522]
## What happens?

UmiJs开启mfsu后，react-weui组件库不能使用，报错：  

Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/buyili/umijs-bug.git

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
1. git clone https://github.com/buyili/umijs-bug.git
2. 
2. tyarn install
3. tyarn start

配置：  
配置文件 `.umirc.ts` 开启 mfsu  
```
import { defineConfig } from 'umi';

export default defineConfig({
  nodeModulesTransform: {
    type: 'none',
  },
  routes: [
    { path: '/', component: '@/pages/index' },
  ],
  fastRefresh: {},

  mfsu: {}
});
```
`index.tsx` 文件使用组件
```
import styles from './index.less';
import { Button } from 'react-weui'
import 'weui'
import 'react-weui/build/packages/react-weui.css';

export default function IndexPage() {
  return (
    <div>
      <h1 className={styles.title}>umijs mfsu错误</h1>

      <Button>Button</Button>
    </div>
  );
}
```

**Expected behavior** 1. 2.
开启 mfsu 时的错误情况：
![image](https://user-images.githubusercontent.com/31640546/139566640-237fad92-a556-43dd-9e32-48feb9f41d25.png)

关闭 mfsu 时的正常情况：  
![image](https://user-images.githubusercontent.com/31640546/139566655-792bcc76-c625-4ff2-abf9-3444c12ff421.png)

## Context

- **Umi Version**: ^3.5.20
- **Node Version**: v14.18.1
- **Platform**: Windows 10

**Comment by wozien** [comment]
所以又为啥莫名奇妙关闭issue，至少给个答复啊
