### ISSUE TITLE
umi router 部署到服务器 pathname后面多了一个/的符号

### ISSUE THREAD

**Issue by MachoManCk** [umijs/umi#7523]
umi router部署到服务器之后 pathname后多了一个/的符号 比如本地开发的时候pathname为/user/login 部署到服务器上就变成/user/login/ 是什么原因导致的呢

**Comment by 104gogo** [comment]
可能是nginx重定向了

**Comment by MachoManCk** [comment]
排查了nginx 没有做重定向的配置 而且部署到两台服务器都会有这个问题 看了下社区也有这种问题

**Comment by zzcbnz** [comment]
https://github.com/ant-design/ant-design-pro/issues/9140#issuecomment-927683997
