### ISSUE TITLE
[Bug] plugin-qiankun 子应用嵌套，孙应用未渲染

### ISSUE THREAD

**Issue by ALL-STACK** [umijs/umi#7526]
## 子应用渲染成功，孙子项目加载了但是未渲染

![image](https://user-images.githubusercontent.com/24264872/139630825-42e28cc2-6a1d-41ae-8e06-abeb54a2ed4e.png)
![image](https://user-images.githubusercontent.com/24264872/139630839-34666cd1-06f9-48c0-a18c-400737230c47.png)

## 复现仓库：
git@github.com:ALL-STACK/plugin-qiankun-demo.git

## Context

- **Umi Version**: 3.5.18
- **Node Version**: 12.x
- **Platform**: chrome

**Comment by draco-china** [comment]
孙应用 history 是用 memory ？
