### ISSUE TITLE
[Bug] Jenkins 自动化部署报错

### ISSUE THREAD

**Issue by KingThq** [umijs/umi#7531]
## What happens?
ant design pro v4 项目在 Jenkins 上自动化打包时会报 python 错误，虽然有这个报错，最后还是打包成功了。请问如何解决这个报错？哪里用到 python 呢？
![image](https://user-images.githubusercontent.com/39801991/139829799-d60d9690-e1e3-4624-96f0-6bd2aae85dfb.png)

## Context

- **Umi Version**: 2.13.13
- **Node Version**: 12.18.3
- **Platform**:

**Comment by robinv8** [comment]
这需要 docker 环境安装了python，可以试试我这个
```
FROM nikolaik/python-nodejs:python2.7-nodejs12-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache git build-base  g++  cairo-dev  jpeg-dev  pango-dev  giflib-dev \
    && yarn config set registry https://registry.npm.taobao.org/ 
```

**Comment by KingThq** [comment]
> 这需要 docker 环境安装了python，可以试试我这个
> 
> ```
> FROM nikolaik/python-nodejs:python2.7-nodejs12-alpine
> 
> WORKDIR /usr/src/app
> 
> RUN apk add --no-cache git build-base  g++  cairo-dev  jpeg-dev  pango-dev  giflib-dev \
>     && yarn config set registry https://registry.npm.taobao.org/ 
> ```

umi 打包内部有用到 python 吗？

**Comment by robinv8** [comment]
> > 这需要 docker 环境安装了python，可以试试我这个
> > ```
> > FROM nikolaik/python-nodejs:python2.7-nodejs12-alpine
> > 
> > WORKDIR /usr/src/app
> > 
> > RUN apk add --no-cache git build-base  g++  cairo-dev  jpeg-dev  pango-dev  giflib-dev \
> >     && yarn config set registry https://registry.npm.taobao.org/ 
> > ```
> 
> umi 打包内部有用到 python 吗？

安装  node-sass 用到了，不过我忽略了一个问题，我们这使用 gitlab ci/cd 部署的，不清楚跟 jenkins 有啥区别，但确定的是是，你打包的环境需要安装 python，估计还要安装我上面提到的那一堆依赖

**Comment by KingThq** [comment]
好的，谢谢了

**Comment by Zero-Qi** [comment]
> 好的，谢谢了

想问下 是怎么解决alias引入问题，我在jenkins中构建报大小写和alias的别名找不到路径
