### ISSUE TITLE
umi自定义的二级路由被动态路由覆盖

### ISSUE THREAD

**Issue by LilyGuo** [umijs/umi#755]
![image](https://user-images.githubusercontent.com/2328749/43568471-422aff42-9667-11e8-8c69-15b05cfa7263.png)

以上目录结构打出来的 .umi/router.js 顺序如下
    {
        "path": "/:team/:suite/new",
        "exact": true,
        "component": require('../$team/$suite/new.js').default
      },
      {
        "path": "/:team/plan/new",
        "exact": true,
        "component": require('../$team/plan/new.js').default
      }

访问  /abc/plan/new 被 "path": "/:team/:suite/new" 截获。到不了 require('../$team/plan/new.js')

**Comment by LilyGuo** [comment]
加了锚点之后，竟然好了。。
hashHistory:true

**Comment by sorrycc** [comment]
疑是 bug，我写个用例测试下。

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/44293442-b68cce80-a2bd-11e8-84a3-345a733259dd.png)
试过没有问题，`/:team/:plan/new` 在前。
