### ISSUE TITLE
[Bug] mfsu状态下解析这种模块报错

### ISSUE THREAD

**Issue by yuyic** [umijs/umi#7550]
## What happens?
一个简单的模块：
```javascript
const namespace = module.exports = {};
module.exports.name = "Mike";
```

开启mfsu报错：
`Unhandled Rejection (Error): ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead`

exports也会报错
```javascript
const name = exports.name = "Mike";
```

`Unhandled Rejection (ReferenceError): exports is not defined`

## Mini Showcase Repository(REQUIRED)

No need

## How To Reproduce

Step1:
新建一个cjs模块
```javascript
// test.js
var namespace = module.exports = {};
module.exports.name = "Mike";
```
Step2:
import这个模块，开启mfsu运行

## Context

- **Umi Version**:3.5.20
- **Node Version**: 14.4.0
- **Platform**: mac os

**Comment by sorrycc** [comment]
有哪个模块是这么写的？之前没遇到过。

**Comment by yuyic** [comment]
> 有哪个模块是这么写的？之前没遇到过。

Thrift生成的模块有这种情况
