### ISSUE TITLE
[Bug] dynamicImport打开和关闭都会初始一个loading，能否加个配置关闭这个loading

### ISSUE THREAD

**Issue by poyiding** [umijs/umi#7551]
## Background

dynamicImport打开和关闭，页面刷新或切换路由都会出现loading...闪动，这非常不友好

## Proposal

能否加个配置关闭这个loading，有些issue也提到了这个loading带来的体验很不好。虽然文档有提 dynamicImport 打开 可以引入一个空组件替换，dynamicImport 关闭这种情况最好也能禁用loading

**Comment by xiaohuoni** [comment]
dev 的时候？

**Comment by poyiding** [comment]
> dev 的时候？

dynamicImport 关闭，线上部署不会，dev会初始loading，先关了

**Comment by yanye411325** [comment]
chuank加载会默认生成一个<p>loading...</p>
**```
const ChunkLoading = () => {
  return <></>;
};

export default ChunkLoading;
```**

配置上边的空组件
**`dynamicImport: { loading: '@/components/common/chunkloading' }`**
