### ISSUE TITLE
打包成静态文件后，通过nginx部署，docker映射，一刷新页面就会出现301

### ISSUE THREAD

**Issue by wwqking** [umijs/umi#7553]
![e3c3084d579756840c55282518b6a3e](https://user-images.githubusercontent.com/20062330/140872594-45bca3af-e694-4312-bb60-9d5acc2fee2c.png)

**Comment by caoxiemeihao** [comment]
你这个不是 301 的问题吧，页面直接 404 了
是 nginx 那边配置没重定向到 index.html 上面？

**Comment by yaoxiantong** [comment]
今天我也遇到了这个问题，看了下nginx的配置是正常的，查了下是需要配置config.ts那个hsah，或者通过配置.umirc.ts来解决，目前是通过第一种方法解决的，再次打包部署就没问题了。

**Comment by prophetw** [comment]
建议先看看文档 [umi部署文档](https://umijs.org/zh-CN/docs/deployment)
