### ISSUE TITLE
[Bug] vscode智能提示的一些问题

### ISSUE THREAD

**Issue by huhm** [umijs/umi#7564]
## What happens?

![image](https://user-images.githubusercontent.com/3477901/141222934-a058602f-4809-4128-beb4-a0faba851c11.png)

## Mini Showcase Repository(REQUIRED)

项目（ts项目）的react版本是"^17.0.0",umi版本是3.5.20. umijs自动引入了`@umijs/renderer-react`,版本为`3.5.20`.
`@umijs/renderer-react`这个包虽然将react作为peerDependencies，但是`"@types/react":"^16.9.43"` 作为其dependencies,由于和项目react版本不一致，会被安装在`node_modules/xxx/@umijs/renderer-react/node_modules/@types/react`下
能否将`@types/react`移出dependencies?

## Context

- **Umi Version**:3.5.20
- **Node Version**:14.16.0
- **Platform**:  Windows_NT x64 10.0.19042
- **VsCode**: 1.62.0

**Comment by prophetw** [comment]
1. package.json  指定下 react 版本 比如 17 版本
```json package.json 
  "resolutions": {
    "react": "^17" 
  },
```
2. 修改完了 重新执行下 yarn 即可

**Comment by fx-fusion** [comment]
应该将 @types/* 更改为 devDependencies
