### ISSUE TITLE
[Bug]  caniuse-lite

### ISSUE THREAD

**Issue by kaoding** [umijs/umi#7565]
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

**Comment by yancongwen** [comment]
npm run build 命令添加环境变量：BROWSERSLIST_IGNORE_OLD_DATA=true
"build": "cross-env BROWSERSLIST_IGNORE_OLD_DATA=1 umi build",

**Comment by C-guard** [comment]
> npm run build 命令添加环境变量：BROWSERSLIST_IGNORE_OLD_DATA=true "build": "cross-env BROWSERSLIST_IGNORE_OLD_DATA=1 umi build",
![image](https://github.com/umijs/umi/assets/101534997/b44ba1ef-c71b-4e92-8293-394b10077e28)
还是有问题
