### ISSUE TITLE
[Bug] 开启 mfsu 后，有 switch 结构的代码不会正确渲染

### ISSUE THREAD

**Issue by GOWxx** [umijs/umi#7572]
初始化一个 umijs 项目，在 @/page/index.tsx 里 写了一段包含 switch-case 的代码来控制渲染，更改代码重新编译后，页面并不会刷新出正确的内容

仓库地址：
https://github.com/GOWxx/umijs_mfsu_bug

复现步骤：
1. 启动项目，目前页面上渲染的是 “正确更新”
2. 在 @/pages/index.tsx 内，修改 renderContent 方法下 switch 的 default分支内容，例如 “正确更新” 修改成 “不能正确更新”，保存，重新编译
3. 终端提示 “Compiled successfully” 但页面没有正确更新，需要手动刷新才能正确展示
4. 在 .umirc.ts 里 关闭 mfsu，删除 .umi 下的缓存文件 重复步骤 1~3，可以正确渲染。

观察：
1. 如果 switch 中的 case 只有一个，那么会正确渲染，有两个或两个以上 case 时，不会正确渲染。
2. 不止default，更新 ChildPage 的内容也是一样的，并不会正确渲染。

## Context

"umi": "^3.5.20"
Node Version: 16.12.0
Platform: windows 10

**Comment by sorrycc** [comment]
在重构后的新版 mfsu 中已修复，会随着 umi 4 发布。

**Comment by GOWxx** [comment]
> 请问umi4大约在什么时间发布呢？

可以关注项目
[umi-next](https://github.com/umijs/umi-next)
以及它的进度
https://github.com/umijs/umi-next/projects/2
