### ISSUE TITLE
[Bug] 3.5.20 ssr hash 404 问题

### ISSUE THREAD

**Issue by FeSeason** [umijs/umi#7573]
## What happens?

配置了 hash ， 开启 ssr  服务端模板写死的 umi.js/css ....  这都 3.5.20了 

好多人反馈这个问题 。。。。  #7002 #6653

## Context

- **Umi Version**: 3.5.20
- **Node Version**: 14.17.0
- **Platform**: mac

**Comment by luoweii** [comment]
我也遇到了  这个问题不解决吗？等了好久了

**Comment by FeSeason** [comment]
@luoweii  降到3.5.x 版本都有这个问题 也可以自己解决 把  manifest.json 传入 自己处理  但是还是希望官方处理一下吧 或者直接降到3.4.x版本...  感觉 umi 用作ssr 的人实在不多...  官方不知道是在解决下一个大版本还是 直接忽视 ...

**Comment by congwa** [comment]
我也遇到了这个问题，希望官方人员能够快点解决。

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/pull/7256
