### ISSUE TITLE
[Bug] 开启mfsu后，antd组件样式出现问题

### ISSUE THREAD

**Issue by 79percent** [umijs/umi#7589]
## 开启mfsu后，antd组件样式问题

用脚手架创建的ant-design-pro项目  
> yarn create umi myapp  

项目启动后样式没有正常加载出来
![image](https://user-images.githubusercontent.com/49113650/142348284-40829a10-ad81-4433-b8f6-44bb7086a2fe.png)
![image](https://user-images.githubusercontent.com/49113650/142348311-4da272a2-e908-4e3a-88a2-0789b95c4929.png)

在配置文件中关闭mfsu后，样式变正常了。

难道和操作系统有关？
mac系统上有这个问题，换了Windows上是正常的。

**Comment by LemonTree-shine** [comment]
不知道这个umi是不是已经没有人维护了

**Comment by xgj1988** [comment]
这个项目是不是凉凉了？

**Comment by sorrycc** [comment]
umi 4 开发中，这边关注较少。mfsu 的问题已集中在重构后的 mfsu 版本中修复，会随着 umi 4 发布。遇到问题的话，先关闭 mfsu 吧。

**Comment by summmmer** [comment]
同样的问题
