### ISSUE TITLE
umi转发请求有时候时间特别长，10次会出现4次很慢

### ISSUE THREAD

**Issue by LemonTree-shine** [umijs/umi#7590]
Queued at 0
--
Started at 0.50 ms
Resource Scheduling |   | DURATION
Queueing | ​ | 0.50 ms
Connection Start |   | DURATION
Stalled | ​ | 0.38 ms
DNS Lookup | ​ | 0
Initial connection | ​ | 0.25 ms
Request/Response |   | DURATION
Request sent | ​ | 0
Waiting (TTFB) | ​ | 35.86 s
Content Download | ​ | 0.38 ms
Explanation |   | 35.86 s

这是一个请求的整个耗时情况，其中有一个用了35秒，有时候一分多钟，没法开发，只有umi转发是会这样的，求解决

我用postman直接调接口是不会存在这个问题的

**Comment by LemonTree-shine** [comment]
在mac pro上会出现这个问题，window上面不会出这个问题

**Comment by LemonTree-shine** [comment]
![image](https://user-images.githubusercontent.com/20238337/142386901-ab237128-a8f6-4939-b9fc-9f74d4cba4e6.png)
经常出现这种1.1分钟的，评率特别高

**Comment by LemonTree-shine** [comment]
![screenshot-20211118-175116](https://user-images.githubusercontent.com/20238337/142392834-8f770d40-5f33-4adc-b02d-1c7992abeb29.png)
这个是相关的系统信息

**Comment by LemonTree-shine** [comment]
![screenshot-20211118-175418](https://user-images.githubusercontent.com/20238337/142392941-fd8f3094-9f0c-47de-a80d-ef5b8667673e.png)
这个是现象，同样的接口调了7次，有3次是出现一分钟以上的

**Comment by mortalYoung** [comment]
me too！有解决吗？

**Comment by hpc1071123837** [comment]
这个问题是解决了吗  怎么关闭了？

**Comment by xuzhouchen1104** [comment]
这个问题是解决了吗 怎么关闭了？
