### ISSUE TITLE
umi 打包后拆分chunk后，umi.js并没有减少

### ISSUE THREAD

**Issue by Maolipeng** [umijs/umi#7595]
umi config配置如下
```
 chunks: ['vendors-test', 'umi'],
  chainWebpack: (config) => {
    config.merge({
      optimization: {
        minimize: true,
        splitChunks: {
          chunks: 'all',
          minSize: 30000,
          minChunks: 3,
          automaticNameDelimiter: '.',
          cacheGroups: {
            vendors: {
              name: 'vendors-test',
              chunks: 'all',
              // test: /[\\/]node_modules[\\/](?!lodash|antd|monaco-editor).*$/,
              test: /[\\/]node_modules[\\/]/,
              priority: 120
            },

```
![image](https://user-images.githubusercontent.com/26518143/142556792-13236efd-682e-4a65-9813-f1175e988012.png)
仍然包含antd等资源

**Comment by zooeyking** [comment]
你好，你这个栗子umi 是那个版本的？ 为什么我按照你这个配置  chunks: ['vendors-test', 'umi'],  一旦加上这个配置项就报打包错误，我这边用的  "umi": "3.5.20",   
可是不加这个配置的话，怎么分包，闹心  查了两天了，怎么配置都分不出来

**Comment by zooeyking** [comment]
![image](https://user-images.githubusercontent.com/16650705/148345093-d9f68f10-2b3a-4dd1-b57a-18f6cae1ba4d.png)
chunks: ['vendorBase', 'bizCharts', 'umi'],
  chainWebpack: (memo) => {
    memo.merge({
      optimization: {
        // 压缩模块
        minimize: true,
        // 表示只导出那些外部使用了的那些成员
        usedExports: true,
        splitChunks: {
          chunks: 'all',
          // maxSize: 500000,
          minSize: 30000, //文件最小打包体积，单位byte，默认30000，若单个文件不满足会合并其他文件组成一个
          minChunks: 1, //最小使用到次数，超过2次执行
          maxAsyncRequests: 10,
          maxInitialRequests: 10,
          automaticNameDelimiter: '~',
          name: true,
          cacheGroups: {
            vendor: {
              name: 'vendorBase',
              chunks: 'all',
              test: (it: any) => {
                const { resource } = it;
                return /^.*(?=lodash|antd|react).*$/.test(resource);
              },
              priority: 150,
            },
            bizCharts: {
              name: 'bizCharts',
              chunks: 'all',
              test: (it: any) => {
                const { resource } = it;
                return /^.*(?=bizcharts|aliyun|elk|cpexcel).*$/.test(resource);
              },
              priority: 120,
            },
            default: {
              minChunks: 2,
              priority: 10,
              reuseExistingChunk: true
            }
          }
        }
      }
    });
  },

**Comment by zooeyking** [comment]
![image](https://user-images.githubusercontent.com/16650705/148345331-741b4ff9-aef8-430b-bd93-b6af752acc01.png)
你可以shi's试试这个配置，这是我打包出来的；
`
export default defineConfig({
  dynamicImport: {
    loading: '@/components/DynamicImportLoading',
  },
  outputPath: './dist',
  hash: true,
  chunks: ['vendorBase', 'bizCharts', 'umi'],
  chainWebpack: (memo) => {
    memo.merge({
      optimization: {
        // 压缩模块
        minimize: true,
        // 表示只导出那些外部使用了的那些成员
        usedExports: true,
        splitChunks: {
          chunks: 'all',
          // maxSize: 500000,
          minSize: 30000, //文件最小打包体积，单位byte，默认30000，若单个文件不满足会合并其他文件组成一个
          minChunks: 1, //最小使用到次数，超过2次执行
          maxAsyncRequests: 10,
          maxInitialRequests: 10,
          automaticNameDelimiter: '~',
          name: true,
          cacheGroups: {
            vendor: {
              name: 'vendorBase',
              chunks: 'all',
              test: (it: any) => {
                const { resource } = it;
                return /^.*(?=lodash|antd|react).*$/.test(resource);
              },
              priority: 150,
            },
            bizCharts: {
              name: 'bizCharts',
              chunks: 'all',
              test: (it: any) => {
                const { resource } = it;
                return /^.*(?=bizcharts|aliyun|elk|cpexcel).*$/.test(resource);
              },
              priority: 120,
            },
            default: {
              minChunks: 2,
              priority: 10,
              reuseExistingChunk: true
            }
          }
        }
      }
    });
  },
});`
