### ISSUE TITLE
[Feature Request] 支持配置 webpack5

### ISSUE THREAD

**Issue by jing-wu** [umijs/umi#7605]
## Background

在配置文件开启 webpack5 后，没法通过 chainWebpack 针对 webpack5 进行配置。

目前 chainWebpack 官方是不支持生成 webpack5 的配置项的。

## Proposal

能否通过其他方式让开发者针对 webpack5 进行配置

**Comment by sorrycc** [comment]
在 umi 4 中会修复这个问题，issue 先关了。

**Comment by jing-wu** [comment]
> 在 umi 4 中会修复这个问题，issue 先关了。

大佬，umi4大概什么时候能出来啊
