### ISSUE TITLE
模块“"umi"”没有导出的成员“useSelector”

### ISSUE THREAD

**Issue by a982564562** [umijs/umi#7630]
## What happens?
新建的项目提示错误模块“"umi"”没有导出的成员“useSelector”

## 最小可复现仓库
```
import { useSelector } from 'umi';
import equal from 'fast-deep-equal';

export function useDeepEqualSelector<TState = {}, TSelected = unknown>(
  selector: (state: TState) => TSelected,
) {
  return useSelector(selector, (left, right) => equal(left, right));
}
```

[https://github.com/a982564562/umi-test/tree/master](https://github.com/a982564562/umi-test/tree/master)

## 相关环境信息

- **Umi Version**: 3.5.20
- **Node Version**: v12.16.0
- **Platform**: window

**Comment by SharidaLi** [comment]
没有 models，是不会加载 [@umijs/plugin-dva](https://github.com/umijs/plugins/blob/b841fcbc7fa9ab4eee11e8e06433e3acdd0ec144/packages/plugin-dva/src/index.ts#L100) 插件的，文档里也有写 https://umijs.org/zh-CN/plugins/plugin-dva#faq

**Comment by Memories-SlowFever** [comment]
> 没有 models，是不会加载 [@umijs/plugin-dva](https://github.com/umijs/plugins/blob/b841fcbc7fa9ab4eee11e8e06433e3acdd0ec144/packages/plugin-dva/src/index.ts#L100) 插件的，文档里也有写 https://umijs.org/zh-CN/plugins/plugin-dva#faq
导入都没有
