### ISSUE TITLE
umi升级到了3.5.20，且webpack升级到了5.64.4,在项目中如何使用webwork

### ISSUE THREAD

**Issue by wh1246935943** [umijs/umi#7635]
按照webpack的web-workers章节中的例子：https://webpack.js.org/guides/web-workers/

编写代码：和示例中的代码一致；

运行后报错：
```
意外令牌（35:63）
已使用以下加载程序处理文件：
Module parse failed: Unexpected token (35:63)
File was processed with these loaders:
 * ./node_modules/@umijs/deps/compiled/babel-loader/index.js
You may need an additional loader to handle the result of these loaders.
|
|     this.creatWorker = () => {
>       var worker = new Worker(new URL('./aic_worker.js', import.meta.url));
|       worker.postMessage({
|         question: 'The Answer to the Ultimate Question of Life, The Universe, and Everything.'
 @ ./src/.umi/core/routes.ts 55:19-53
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts
```
**请问这是为什么?** 
我也尝试在config.js的defineConfig({})中添加workerLoader: {}，但依然如此！

**Comment by daochouwangu** [comment]
1. 使用workLoader要直接引入worker
```import Worker from './deep-thought.worker.js'
const worker = new Worker();```
注意改名为 *.worker.js
2. 你可以什么都不改，启用webpack5模式, webpack5自带worker-loader
在配置文件中加入 `webpack5: {}`

**Comment by wh1246935943** [comment]
第二个方法我有点疑惑：

我得webpack已经升级到了5.x了，还需要在config.js中配置webpack5：{}这个选项吗，
意思是只有这么做才能启用5.x如果不配置依然是4.x，即使本地安装的是5.x的版本?

我配置了这个选项后 ，项目编译时控制台输出大量错误，都是找不到模块这样的报错，我重新安装了依赖也依然如此，报错如下：
![3a4a70a2d0614cb207476df91234c57](https://user-images.githubusercontent.com/26916703/143841585-26d4fc98-8b2d-4b22-9796-e23b06a2cb0d.png)
@daochouwangu

**Comment by hurryhuang1007** [comment]
> 第二个方法我有点疑惑：
> 
> 我得webpack已经升级到了5.x了，还需要在config.js中配置webpack5：{}这个选项吗， 意思是只有这么做才能启用5.x如果不配置依然是4.x，即使本地安装的是5.x的版本?
> 
> 我配置了这个选项后 ，项目编译时控制台输出大量错误，都是找不到模块这样的报错，我重新安装了依赖也依然如此，报错如下： ![3a4a70a2d0614cb207476df91234c57](https://user-images.githubusercontent.com/26916703/143841585-26d4fc98-8b2d-4b22-9796-e23b06a2cb0d.png) @daochouwangu

试着把lock文件删了，再重新装一下依赖试试。

**Comment by wnbupt** [comment]
> 1. 使用workLoader要直接引入worker
>    `import Worker from './deep-thought.worker.js'`
>    `const worker = new Worker();`
>    注意改名为 *.worker.js
> 2. 你可以什么都不改，启用webpack5模式, webpack5自带worker-loader
>    在配置文件中加入 `webpack5: {}`

亲测还是需要先按照 [Webpack5 Web Worker](https://webpack.js.org/guides/web-workers/) 使用方法创建 worker，然后再启用 webpack5 模式，问题就解决了。

**Comment by 1209823208** [comment]
> > 1. 使用workLoader要直接引入worker
> >    `import Worker from './deep-thought.worker.js'`
> >    `const worker = new Worker();`
> >    注意改名为 *.worker.js
> > 2. 你可以什么都不改，启用webpack5模式, webpack5自带worker-loader
> >    在配置文件中加入 `webpack5: {}`
> 
> 亲测还是需要先按照 [Webpack5 Web Worker](https://webpack.js.org/guides/web-workers/) 使用方法创建 worker，然后再启用 webpack5 模式，问题就解决了。

报错ERROR  Failed to compile with 0 errors  不知道什么原因
umi版本 :3.5.24
