### ISSUE TITLE
[Bug] pages model 变成了全局 model

### ISSUE THREAD

**Issue by hanxiansen** [umijs/umi#7646]
## pages model 变成了全局 model

1. 在全局models 中声明  model 文件
2. 在 pages/user//Login/models 中声明 model 文件
3. 在 profile/basic 中通过 connect 可以同时获取到 user中声明的局部model 和全局中声明的 global model

## Mini Showcase Repository(REQUIRED)
> model 分两类，一是全局 model，二是页面 model。全局 model 存于 /src/models/ 目录，所有页面都可引用；页面 model 不能被其他页面所引用。

看umi的[文档描述](https://v2.umijs.org/zh/guide/with-dva.html#model-%E6%B3%A8%E5%86%8C)，如果是页面model是不能被其他页面model访问的，但现在却可以自由访问。pages 下的model 和全局model没有任何区分？

## How To Reproduce

1. 在全局models 中声明  model 文件
2. 在 pages/user/Login/models 中声明 model 文件
3. 在 profile/basic 中通过 connect 可以同时获取到 user 页面中声明的局部 model 和全局中声明的 global model
4. 理论上 profile 页面级中应该获取不到 user 中的 model 了

## Context

- **Umi Version**: 3.5.20
- **Node Version**: v12.22.3
- **Platform**: mac

**Comment by morepowerful** [comment]
所以这个问题怎么被解决的，大佬？

**Comment by morepowerful** [comment]
我也碰到啦
