### ISSUE TITLE
[Bug] Helmet SSR 没有插入 script 标签的能力

### ISSUE THREAD

**Issue by limi58** [umijs/umi#7648]
## What happens?

开启 SSR，Helmet 没有把 script 输出给 HTML

source:
```html
<Helmet>
  <script>console.log(123)</script>
  <style>html{color:#000}</style>
</Helmet>
```

output HTML（只有 style）：
```html
<style>html{color:#000}</style>
```

在[源码](https://github.com/umijs/plugins/blob/master/packages/plugin-helmet/src/templates/runtime.tpl#L11)里发现没有输出 script，所以，有什么办法输出 script 标签吗

## Context

- **Umi Version**: 3.4.25
- **Node Version**: 16.0.0
- **Platform**: wls ubuntu

**Comment by DLErice** [comment]
我也同样遇到这个问题，可以直接添加在模板文件里或者使用 umirc里使用headScripts:['*******'],但是这样使用不能控制需要在哪个页面中显示

**Comment by limi58** [comment]
@DLErice 提了 PR，看看会不会 merge。实在不行我就把 plugin-helmet 的源码复制过来改一下，放本地 plugin 也可以

**Comment by DLErice** [comment]
ok，谢谢

**Comment by limi58** [comment]
[PR 已 Merge](https://github.com/umijs/plugins/pull/756)，close 了
