### ISSUE TITLE
[Bug] 配置splitChunks后，dev和build均白屏

### ISSUE THREAD

**Issue by xueerli** [umijs/umi#7650]
## 配置splitChunks后，dev和build均白屏
```
 config.optimization.splitChunks({
    chunks: 'all',
    minSize: 30000,
    minChunks: 1,
    cacheGroups: {
      react: {
        chunks: 'all',
        name: 'react',
        test: /[\\/]node_modules[\\/](react|react-dom)[\\/]/,
        priority: 10,
      },
    },
  });
```

[复现地址: https://github.com/xueerli/umi3-test](https://github.com/xueerli/umi3-test)

- yarn
- yarn dev (开发环境白屏)
- yarn build & cd dist & http-server (生产环境白屏)

## Context

- **Umi Version**: 3.5.20
- **Node Version**: 14.15.0
- **Platform**: mac

**Comment by xueerli** [comment]
@xiaohuoni

**Comment by jing-wu** [comment]
试试在 `config.ts` 中添加 `chunks`配置项：
`chunks: ['react', 'umi'],`

**Comment by xueerli** [comment]
@jing-wu 添加了 chunks: ['react', 'umi'] 和 chunks: ['react'] 都不行

**Comment by xueerli** [comment]
root 里是空的

**Comment by xueerli** [comment]
问题解决了 更改为以下配置就可以了
我理解的是要把node_modules中除了分包以外的其他包也配置一下，打到vendors中
```
 config.optimization.splitChunks({
    chunks: 'all',
    minSize: 30000,
    minChunks: 1,
    cacheGroups: {
      react: {
        chunks: 'all',
        name: 'react',
        test: /[\\/]node_modules[\\/](react|react-dom)[\\/]/,
        priority: 20,
      },
      vendors: {
        chunks: 'all',
        name: 'vendors',
        test: /[\\/]node_modules[\\/]/,
        priority: 10,
      },
    },
  });
```

**Comment by Quanzhitong** [comment]
> 问题解决了 更改为以下配置就可以了 我理解的是要把node_modules中除了分包以外的其他包也配置一下，打到vendors中 同时在.umirc.ts中配置 `chunks: ['react', 'vendors', 'umi']`
> 
> ```
>  config.optimization.splitChunks({
>     chunks: 'all',
>     minSize: 30000,
>     minChunks: 1,
>     cacheGroups: {
>       react: {
>         chunks: 'all',
>         name: 'react',
>         test: /[\\/]node_modules[\\/](react|react-dom)[\\/]/,
>         priority: 20,
>       },
>       vendors: {
>         chunks: 'all',
>         name: 'vendors',
>         test: /[\\/]node_modules[\\/]/,
>         priority: 10,
>       },
>     },
>   });
> ```

你用的是umi3吗？ 不是不支持chunks了吗？

**Comment by Lzengp** [comment]
> > 问题解决了 更改为以下配置就可以了 我理解的是要把node_modules中除了分包以外的其他包也配置一下，打到vendors中 同时在.umirc.ts中配置 `chunks: ['react', 'vendors', 'umi']`
> > ```
> >  config.optimization.splitChunks({
> >     chunks: 'all',
> >     minSize: 30000,
> >     minChunks: 1,
> >     cacheGroups: {
> >       react: {
> >         chunks: 'all',
> >         name: 'react',
> >         test: /[\\/]node_modules[\\/](react|react-dom)[\\/]/,
> >         priority: 20,
> >       },
> >       vendors: {
> >         chunks: 'all',
> >         name: 'vendors',
> >         test: /[\\/]node_modules[\\/]/,
> >         priority: 10,
> >       },
> >     },
> >   });
> > ```
> 

我目前用的是umi: 3.5.13, 在配置splitChunks的时候也出现了这样的问题, 就是配置了chunks: 'all',之后页面白屏, 换成chunks: 'async'才不会白, .umirc.ts里面配置 `chunks: ['react', 'vendors', 'umi']` 是必须的吗? 因为我目前的项目中是没有.umirc.ts的@xueerli

**Comment by xueerli** [comment]
@Lzengp 
用的是umi3.5.20 没看到umi3不支持chunks的说明
chunks: ['react', 'vendors', 'umi'] 是根据cacheGroups对应配置的 你看我的cacheGroups中分离出了react和vendors，umi是默认的
你的白屏看一下是不是有js文件没加载上

**Comment by bluehymn** [comment]
`chunks: [..., 'vendors.umi', 'umi'],`

我尝试chunks里增加一个vendors.umi就可以了

因为我发现编译出的umi.js里面有这个模块
![image](https://user-images.githubusercontent.com/15361704/157203725-ef3cef2f-a112-4aa2-bb13-d9258d56bb6f.png)

**Comment by peakandyuri** [comment]
> `chunks: [..., 'vendors.umi', 'umi'],`
> 
> 我尝试chunks里增加一个vendors.umi就可以了
> 
> 因为我发现编译出的umi.js里面有这个模块 ![image](https://user-images.githubusercontent.com/15361704/157203725-ef3cef2f-a112-4aa2-bb13-d9258d56bb6f.png)


(node:13892) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of vendors.umi not found.

**Comment by EarthShakers** [comment]
chunks:'all' 修改为'async' 不白屏了
