### ISSUE TITLE
[Bug] 未开启 ssr 时，未调用 getInitialProps 方法

### ISSUE THREAD

**Issue by xiaohp** [umijs/umi#7653]
## What happens?

未开启 ssr 时，页面组件中有 getInitialProps 方法，但未调用

## Mini Showcase Repository(REQUIRED)

https://github.com/xiaohp/umi-demo

## How To Reproduce

yarn start

## Context

- **Umi Version**: 3.5.20
- **Node Version**: v14.17.5
- **Platform**: macOS 11.6

**Comment by wsz7777** [comment]
+1   v3.4.25

**Comment by robinv8** [comment]
getInitialProps 只支持 ssr 渲染
