### ISSUE TITLE
location里是否可以获取title等扩展属性

### ISSUE THREAD

**Issue by nextdooroldwang** [umijs/umi#7667]
location里没有扩展属性，需要从route里获取，但是动态路由的location.pathname和routes.path不一样，无法匹配到当前路由的扩展属性（title）

![image](https://user-images.githubusercontent.com/18671240/145381204-fcd2fe3c-5e07-4ffc-bb95-d06cc230823b.png)
**location ↑**

![image](https://user-images.githubusercontent.com/18671240/145381363-1d70df67-e5af-48d5-aa6e-736d1a34f4d7.png)
**routes↑**

**Comment by echoyl** [comment]
楼主有解决方案了吗？
