### ISSUE TITLE
[Bug]生产~/.mfsu-prodction文件夹下MFSU_CACHE.json文件里的tmpDeps 属性存在本地绝对地址

### ISSUE THREAD

**Issue by jiangdexiao** [umijs/umi#7674]
## What happens?

~/mfsu-production 下的MFSU_CACHE.json文件第一次构建 的时候 tmpDeps 属性是空, 之后的每次构建tmpDeps属性下存在本地绝对地址,这样子的地址同步到git,服务器构建会失败,tmpDeps下存在本地路径这是不是个bug
同这个issue里一样 
https://github.com/umijs/umi/issues/6766#issuecomment-869505801
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by devenliu** [comment]
同问~

**Comment by jiangdexiao** [comment]
这问题是都没人管了吗

**Comment by lipenghu001** [comment]
> 这问题是都没人管了吗

遇到了同样的问题，生产依赖居然存绝对路径，直接凉凉。

**Comment by wangzhengbo** [comment]
bug没人管了
