### ISSUE TITLE
[Bug] 开启 ssr + dynamicImport 时使用 webpack5，服务端渲染的 html 缺少样式

### ISSUE THREAD

**Issue by iwyvi** [umijs/umi#7676]
## What happens?

同时开启 ssr 和 dynamicImport 时，使用 webpack5，服务端直接渲染出的 html 缺少样式，没有引入对应的 css 文件，需要等 js 运行后才能看到样式。使用 webpack4 时正常

简单调试了一下，在 webpack5 下这里 https://github.com/umijs/umi/blob/master/packages/preset-built-in/src/plugins/features/ssr/templates/utils.ts#L129 的 `manifest?._chunksMap` 总是 `undefined`，所以没有在 head 里注入 css 文件

## Mini Showcase Repository(REQUIRED)

https://codesandbox.io/s/umi-webpack5-ssr-u6k9y?file=/.umirc.ts

刷新页面即可看到样式变化

## How To Reproduce

**Steps to reproduce the behavior:** 

1. 在配置中开启 `ssr`, `dynamicImport`, `webpack5`
2. 刷新浏览器查看

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.5.20
- **Node Version**: 14.18.1
- **Platform**:

**Comment by w567675** [comment]
我也遇到了同样的问题， 请问webpack5禁用也不行，怎么切换成webpack4
