### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by wangym0203** [umijs/umi#7678]
## What happens?
umi隐藏了 index.js 入口。 如何添加一个 全局的 provider 
<img width="685" alt="WX20211213-105659@2x" src="https://user-images.githubusercontent.com/26135370/145745421-8555f741-2f11-4244-9cf6-820dff0b7a5d.png">

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by HeiShuXianSheng** [comment]
是的，我也没找到

**Comment by xiaohuoni** [comment]
看这里 https://umijs.org/zh-CN/docs/runtime-config#rootcontainerlastrootcontainer-args
