### ISSUE TITLE
umi2 无法使用 roadhog 的 define 功能

### ISSUE THREAD

**Issue by xiaoxiangmoe** [umijs/umi#768]
在 .webpackrc.js 中无法使用
https://github.com/sorrycc/roadhog#define

**Comment by sorrycc** [comment]
在 `.umirc.js` 里配就好，umi@2 里没有 `.webpackrc.js` 了。

**Comment by p919533** [comment]
> 在 `.umirc.js` 里配就好，umi@2 里没有 `.webpackrc.js` 了。

在umirc.js里面define 这个也不可以用 
![image](https://user-images.githubusercontent.com/26241954/49210590-6fec5b80-f3f8-11e8-8810-1ff932dfd0fa.png)
![Uploading image.png…]()

**Comment by p919533** [comment]
![image](https://user-images.githubusercontent.com/26241954/49210762-e5582c00-f3f8-11e8-8047-362bba5aadb1.png)
![image](https://user-images.githubusercontent.com/26241954/49210776-ebe6a380-f3f8-11e8-9359-a7484a7c9c7a.png)

**Comment by dongze1213** [comment]
> 在 `.umirc.js` 里配就好，umi@2 里没有 `.webpackrc.js` 了。



> 在 .umirc.js 里配就好，umi@2 里没有 .webpackrc.js 了。
> 
> 在umirc.js里面define 这个也不可以用

有没有解决？怎么解决的？
