### ISSUE TITLE
[Bug] umi的 `YUI` 2.9.0 有漏洞，需要升级版本

### ISSUE THREAD

**Issue by hocko333** [umijs/umi#7682]
## What happens?

不确定这个问题到底是否属于umi，我先描述这个问题，希望可以得到解决方法。
我们的产品的在申请 **销售许可证**，在申请的时候需要通过安全审查，用的似乎是 `acunetix` 这个工具。
我们用的是antd pro这个脚手架
截图是检测报告中关于风险的描述
![image](https://user-images.githubusercontent.com/45919606/145767079-b7f4db89-92f6-4a88-9496-ef1c01f4484a.png)
![image](https://user-images.githubusercontent.com/45919606/145767505-46cfb4f3-132d-48dd-8468-ac3a15126ac3.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: ^3.4.1
- **Node Version**: v15.10.0
- **Platform**:

**Comment by hocko333** [comment]
我找了很久，但没找到是哪里引用了 `YUI` 😭

**Comment by hocko333** [comment]
抱歉，这个问题应该不是umi导致的，我正在排查

**Comment by jx-zyf** [comment]
> 抱歉，这个问题应该不是umi导致的，我正在排查

我们项目安全检查也报了这个漏洞，请问找到是哪个模块的依赖了吗？

**Comment by hocko333** [comment]
> > 抱歉，这个问题应该不是umi导致的，我正在排查
> 
> 我们项目安全检查也报了这个漏洞，请问找到是哪个模块的依赖了吗？

@jx-zyf 我已经解决了这个问题，是因为jsencrypt这个库，解决方案看这个issue，[https://github.com/travist/jsencrypt/issues/178](https://github.com/travist/jsencrypt/issues/178)

**Comment by jx-zyf** [comment]
> > > 抱歉，这个问题应该不是umi导致的，我正在排查
> > 
> > 
> > 我们项目安全检查也报了这个漏洞，请问找到是哪个模块的依赖了吗？
> 
> @jx-zyf 我已经解决了这个问题，是因为jsencrypt这个库，解决方案看这个issue，[travist/jsencrypt#178](https://github.com/travist/jsencrypt/issues/178)

谢谢！但我们项目中也没有用到 jsencrypt，我再排查一下。
