### ISSUE TITLE
package中添加了 "homepage": "." ，本地打开打包后的index.html依然是空白的

### ISSUE THREAD

**Issue by HeiShuXianSheng** [umijs/umi#7700]
## What happens?

因为需要打包后的静态文件来进一步打包为手机apk，所以需要build的index可以直接本地访问。

然而在`package.json`中已经添加了`"homepage": "."`，但是本地打开index.html还是空白页面

## Context

- **Umi Version**: 3.5.20
- **Node Version**: v14.17.0
- **Platform**: chrome

**Comment by HeiShuXianSheng** [comment]
在`.umirc.ts`中添加`publicPath: './'`即可。
详情：https://umijs.org/zh-CN/config#publicpath

**Comment by tankpanv** [comment]
> 

问一下，你这边最后问题解决了吗。我也遇到了同样的问题

**Comment by buquan** [comment]
kd

**Comment by buquan** [comment]
本人亲测 ，把包放在本地的nginx完全可以，但liveserver启动包就是空白页面！ 至于为啥，不清楚了～～～

**Comment by wugaoliang1116** [comment]
改为hash模式就可以正常使用了。
<img width="641" alt="image" src="https://user-images.githubusercontent.com/24740506/187103350-5ef99378-205f-4589-8ab2-fd5100bac9c6.png">

**Comment by BellerSun** [comment]
> 
有用，感谢！

**Comment by BellerSun** [comment]
> 改为hash模式就可以正常使用了。 

有用，感谢！
