### ISSUE TITLE
[Bug] ssr预渲染时抛出异常：TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by kaven85** [umijs/umi#7708]
## What happens?

TypeError: Cannot read property 'startsWith' of undefined
    at <隐藏内容>/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/ssr/ssr.js:398:53
    at Array.find (<anonymous>)
    at <隐藏内容>/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/ssr/ssr.js:398:36
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (<隐藏内容>/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/ssr/ssr.js:397:16)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (<隐藏内容>/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/ssr/ssr.js:168:103)
    at _next (<隐藏内容>/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/ssr/ssr.js:170:194)
build failed
Error: build failed
    at <隐藏内容>/node_modules/@umijs/bundler-webpack/lib/index.js:172:29
    at finalCallback (<隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:108196:12)
    at <隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:108217:14
    at <隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:67111:7
    at done (<隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:67206:13)
    at <隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:108128:23
    at <隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:108209:15
    at finalCallback (<隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:98589:39)
    at <隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:98611:21
    at <隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:98824:20
    at eval (eval at create (<隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:147581:10), <anonymous>:68:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## How To Reproduce

1. 开启ssr 和 exportStatic
ssr: {}, 
exportStatic: {}

2. cross-env UMI_ENV=prod REACT_APP_ENV=Prod umi build

## Context

- **Umi Version**:3.5.20
- **Node Version**:v14.18.2
- **Platform**:Mac OS 15.2

**Comment by guanyuan** [comment]
> ## What happens?
> TypeError: Cannot read property 'startsWith' of undefined at <隐藏内容>/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/ssr/ssr.js:398:53 at Array.find () at <隐藏内容>/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/ssr/ssr.js:398:36 at Array.forEach () at Object. (<隐藏内容>/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/ssr/ssr.js:397:16) at Generator.next () at asyncGeneratorStep (<隐藏内容>/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/ssr/ssr.js:168:103) at _next (<隐藏内容>/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/ssr/ssr.js:170:194) build failed Error: build failed at <隐藏内容>/node_modules/@umijs/bundler-webpack/lib/index.js:172:29 at finalCallback (<隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:108196:12) at <隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:108217:14 at <隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:67111:7 at done (<隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:67206:13) at <隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:108128:23 at <隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:108209:15 at finalCallback (<隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:98589:39) at <隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:98611:21 at <隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:98824:20 at eval (eval at create (<隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:147581:10), :68:1) error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> ## How To Reproduce
> 1. 开启ssr 和 exportStatic
>    ssr: {},
>    exportStatic: {}
> 2. cross-env UMI_ENV=prod REACT_APP_ENV=Prod umi build
> 
> ## Context
> * **Umi Version**:3.5.20
> * **Node Version**:v14.18.2
> * **Platform**:Mac OS 15.2

遇到同样问题，请问一下，您这边解决了吗？

**Comment by kaven85** [comment]
> > ## What happens?
> > TypeError: Cannot read property 'startsWith' of undefined at <隐藏内容>/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/ssr/ssr.js:398:53 at Array.find () at <隐藏内容>/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/ssr/ssr.js:398:36 at Array.forEach () at Object. (<隐藏内容>/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/ssr/ssr.js:397:16) at Generator.next () at asyncGeneratorStep (<隐藏内容>/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/ssr/ssr.js:168:103) at _next (<隐藏内容>/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/ssr/ssr.js:170:194) build failed Error: build failed at <隐藏内容>/node_modules/@umijs/bundler-webpack/lib/index.js:172:29 at finalCallback (<隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:108196:12) at <隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:108217:14 at <隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:67111:7 at done (<隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:67206:13) at <隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:108128:23 at <隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:108209:15 at finalCallback (<隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:98589:39) at <隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:98611:21 at <隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:98824:20 at eval (eval at create (<隐藏内容>/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:147581:10), :68:1) error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> > ## How To Reproduce
> > 
> > 1. 开启ssr 和 exportStatic
> >    ssr: {},
> >    exportStatic: {}
> > 2. cross-env UMI_ENV=prod REACT_APP_ENV=Prod umi build
> > 
> > ## Context
> > 
> > * **Umi Version**:3.5.20
> > * **Node Version**:v14.18.2
> > * **Platform**:Mac OS 15.2
> 
> 遇到同样问题，请问一下，您这边解决了吗？

时间太久了，我也忘了当时什么情况了
