### ISSUE TITLE
umi-mfsu-Unhandled Rejection (ChunkLoadError)

### ISSUE THREAD

**Issue by taoqianbao** [umijs/umi#7711]
Unhandled Rejection (ChunkLoadError): Loading chunk mf-dep_vendors-node_modules_core-js_index_js failed.
(missing: http://192.168.31.29:8000/static/js/mf-dep_vendors-node_modules_core-js_index_js.1253c15d.chunk.js)
while loading "./core-js" from webpack/container/reference/mf

Unhandled Rejection (ChunkLoadError): Loading chunk mf-dep_vendors-node_modules_prop-types_index_js failed.
(missing: http://192.168.31.29:8000/static/js/mf-dep_vendors-node_modules_prop-types_index_js.d9a0f465.chunk.js)
while loading "./$CWD$/node_modules/umi/node_modules/@umijs/runtime" from webpack/container/reference/mf
while loading "./$CWD$/node_modules/react-helmet" from webpack/container/reference/mf

Unhandled Rejection (ChunkLoadError): Loading chunk mf-dep_src_umi_cache_mfsu_mf-va__CWD__node_modules__umijs_babel-preset-umi_node_modules__babel_runti-9b8870 failed.
(missing: http://192.168.31.29:8000/static/js/mf-dep_src_umi_cache_mfsu_mf-va__CWD__node_modules__umijs_babel-preset-umi_node_modules__babel_runti-9b8870.1ca85167.chunk.js)
while loading "./$CWD$/node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/esm/objectSpread2" from webpack/container/reference/mf

**Comment by yuganzigogo** [comment]
我也遇到了同样的问题，mac是正常的，window才会有

**Comment by yuganzigogo** [comment]
问题解决了，https://github.com/umijs/umi/issues/7042    msfu打开之后就不用splitChunks了

**Comment by sgknight2020** [comment]
没启用msfu时，编译后只有几十个文件，启用msfu后，编译后文件有几千个o(╥﹏╥)o，这个咋解决。
