### ISSUE TITLE
[Bug] 子应用使用主题色开mfsu失效

### ISSUE THREAD

**Issue by jasonjcwu** [umijs/umi#7712]
## What happens?

子应用使用主题色开mfsu失效

## Mini Showcase Repository(REQUIRED)

```javascript 
  theme: {
    'primary-color': '#3a2be0',
  },
  qiankun: {
    slave: {},
  },
```

## Context

- **Umi Version**: 3.5.20
- **Node Version**: 14
- **Platform**: macos12

**Comment by deerLoves** [comment]
去掉mfsu 就生效了，但是去掉mfsu 好像热更新又不行了，真是无语😓

**Comment by wangshenzhen** [comment]
同上，也遇到了这个问题，查了好久，没有解决办法吗？

**Comment by wangshenzhen** [comment]
3.5.20的版本，删除了.umi，重新启动，不太行，然后看到官方的回复，说是强刷下，然后试了一下，就可以了，应该是某些地方有缓存导致的
