### ISSUE TITLE
[Bug] 开启esbuild后 terserOptions失效

### ISSUE THREAD

**Issue by wang-hang** [umijs/umi#7717]
## What happens?

开启esbuild后 ```terserOptions``` 内设置的 ```drop_console: true``` 失效, 没能正确的移除 ```console.*```
关闭 esbuild后  可以正确的移除 ```consoel.*```

## Mini Showcase Repository(REQUIRED)

最小可复现demo： https://github.com/wang-hang/umi-bug

## How To Reproduce

1. 关闭esbuild， 执行 ```npm run build```, 在打包后的文件搜索console.log,结果： 没搜到
2. 开启esbuild  执行 ```npm run build```, 在打包后的文件搜索 console.log, 结果： 搜到了

## Context

- **Umi Version**:   v3.5.20
- **Node Version**:  v14.18.0
- **Platform**:  MacOS

**Comment by igelar** [comment]
怎么没有任何进度

**Comment by darkfiredarkhalo** [comment]
没解决怎么就关了呢
