### ISSUE TITLE
[Bug] yarn create umi 会报错

### ISSUE THREAD

**Issue by muzea** [umijs/umi#7720]
## What happens?

执行 `create-umi` 报错
```
Error: Failed to load plugin 'react' declared in 'BaseConfig » 我的Yarn\Data\global\node_modules\@umijs\fabric\dist\eslint.js':
Cannot find module 'eslint-plugin-react'
```

## How To Reproduce

在一个全新干净的 Windows 环境下执行 ` yarn create umi my-app`，选择 `antd-pro`

create-umi 0.27.0
Windows 10
yarn 1.12.3
node 16.13.1

**Comment by GOWxx** [comment]
这个 `create-umi` 是什么？

**Comment by muzea** [comment]
@GOWxx 干净的环境中（确保全局 node modules 中没有 eslint-plugin-react），是会报错的

**Comment by GOWxx** [comment]
> @GOWxx 干净的环境中（确保全局 node modules 中没有 eslint-plugin-react），是会报错的

我这估计是没法复现了，等其他人来看看吧

**Comment by bbb169** [comment]
把淘宝镜像关了可以
