### ISSUE TITLE
[Bug] umi 3  和 prolayout 如何配置面包屑？

### ISSUE THREAD

**Issue by zhangjiana** [umijs/umi#7723]
## What happens?

我在umi 的 app.tsx 中配置了breadcrumbRender， 但是没有生效。
```
breadcrumbRender: (router = []) => {
      return [
        {
          path: '/',
          breadcrumbName: '首页',
          showBreadcrumb: true,
          hideInMenu: true,
          component: '@/pages/index'
        },
        ...router
      ]
    }
```
我在umi 的文档上并没有看到具体的面包屑配置。去layout的文档中， 也没有详细看到如何配置面包屑。
请问面包屑功能是如何配置才能生效呢？
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:
umi: 3.5.20
"@ant-design/pro-layout": "6.3.0",
node: v14.11.0
Platform: macos

**Comment by zcSkr** [comment]
antProV4 : breadcrumbRender={(routers = []) => [{ path: '/', breadcrumbName: '首页' }, ...routers]}
antProV5:  breadcrumbRender: (routers = []) => [{ path: '/', breadcrumbName: '首页' }, ...routers]

**Comment by zhidali** [comment]
面包屑 怎样禁用最后一项的点击事件，或者是怎样自定义query参数
