### ISSUE TITLE
[Bug] mfsu 配置 js 文件输出目录后报错， Unhandled Rejection (ChunkLoadError)

### ISSUE THREAD

**Issue by lwQin** [umijs/umi#7725]
## What happens?

```log
Unhandled Rejection (ChunkLoadError): Loading chunk mf-dep_vendors-node_modules_core-js_index_js failed.
(missing: http://localhost:8001/js/mf-dep_vendors-node_modules_core-js_index_js.890fc479abdd62ea2b85.async.js)
while loading "./core-js" from webpack/container/reference/mf
````

## Mini Showcase Repository(REQUIRED)

[demo](https://github.com/lwQin/demo)

## How To Reproduce

1. `yarn `

2. 编辑 `.umirc.ts`
```ts
import { defineConfig } from 'umi';

export default defineConfig({
  chainWebpack(memo) {
    memo.output.filename('js/[name].[contenthash].js').chunkFilename('js/[name].[contenthash].async.js');
  },
  mfsu: {},
  ......
});
```
3. `yarn start`
<img width="1090" alt="Xnip2021-12-23_14-43-09" src="https://user-images.githubusercontent.com/11586662/147199688-cc7a0307-b9f4-4b7d-bca9-bd5e6ce91fa0.png">

## Context

- **Umi Version**: 3.5.20
- **Node Version**: 14.18.1
- **Platform**: macOS

**Comment by conviva-zyang** [comment]
Same here

**Comment by conviva-zyang** [comment]
遇到了同样的问题，也是在config.js里的chainWebpack修改了output.filename。开启mfsu会报错，普通编译没有问题。

**Comment by a958330481** [comment]
遇到了同样的问题

**Comment by Li-mengbo** [comment]
也遇到了同样的问题

**Comment by wozien** [comment]
所以为啥关闭呢？无语
