### ISSUE TITLE
[Bug] 如何开启 webpack 5 中的 expertiments.asyncWebAssembly: true配置 

### ISSUE THREAD

**Issue by litttley** [umijs/umi#7727]
## 问题描述
在引入wasm模块文件时编译如下报错：
 
`error  in ./public/wasm/wasm_bg.wasm

Module parse failed: Unexpected character '' (1:0)
The module seem to be a WebAssembly module, but module is not flagged as WebAssembly module for webpack.
BREAKING CHANGE: Since webpack 5 WebAssembly is not enabled by default and flagged as experimental feature.
You need to enable one of the WebAssembly experiments via 'experiments.asyncWebAssembly: true' (based on async modules) or 'experiments.syncWebAssembly: true' (like webpack 4, deprecated).
For files that transpile to WebAssembly, make sure to set the module type in the 'module.rules' section of the config (e. g. 'type: "webassembly/async"').`

**Comment by Aloento** [comment]
同问

**Comment by banchichen** [comment]
我这边测试，这样是可以的：
```
  chainWebpack(memo) {
    // 配置WebAssembly支持
    memo.set('experiments', {
      asyncWebAssembly: true,
    });
    // 配置WASM文件处理规则
    memo.module
      .rule('wasm')
      .test(/\.wasm$/)
      .type('webassembly/async');
  },
```
