### ISSUE TITLE
[Feature Request] 使用 pnpm 运行 umi dev 时报错

### ISSUE THREAD

**Issue by devenliu** [umijs/umi#7729]
报错内容：

```sh
This dependency was not found:

* @umijs/deps/compiled/path-to-regexp in ./src/.umi/keep-alive/KeepAliveModel.tsx, ./src/.umi/keep-alive/KeepAliveLayout.tsx

To install it, you can run: npm install --save @umijs/deps/compiled/path-to-regexp
```

尝试通过 `npm install --save @umijs/deps/compiled/path-to-regexp` 安装依赖，但无法安装 `@umijs/deps/compiled/path-to-regexp`

希望可以支持一下 `pnpm` 包管理器

**Comment by 1247748612** [comment]
pnpm是天生支持的，我目前没遇到问题

**Comment by McDaddy** [comment]
pnpm应该是没问题的， 我也用过

**Comment by xiaohuoni** [comment]
你好，不存在 @umijs/deps/compiled/path-to-regexp 这个包。只有 @umijs/deps 这个包。
这个包应该是依赖在 umi 里面的，所以你删除 lock 文件和 node_module 文件夹，重新安装所有的依赖。
