### ISSUE TITLE
【控制台报错】Uncaught (in promise) TypeError: e._store.getters.options/getLinkExtsToSniff.indexOf

### ISSUE THREAD

**Issue by dataknower** [umijs/umi#7730]
![image](https://user-images.githubusercontent.com/19550451/147410078-0a32671e-5fcb-4230-9226-93781c19e920.png)

**Comment by ChongYu-Yease** [comment]
同问，最近也遇到了这个问题，开始以为是自己的代码有问题，后来发现其他页面也会报错，又觉得浏览器的版本问题，再后来就换了一台电脑，还是有这个问题

**Comment by AuroraLantean** [comment]
Did you use ReactJs and wrap <XyzProvider>...</XyzProvider> inside <> and </> ?
Try to remove <> and </>
