### ISSUE TITLE
jenkins打包部署失败，本地可以成功

### ISSUE THREAD

**Issue by bnyte** [umijs/umi#7737]
## What happens?

如题本地打包是成功的但是在Jenkins打包时就会失败

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

# 错误日志

```
+ yarn install
yarn install v1.22.17
[1/4] Resolving packages...
success Already up-to-date.
$ umi generate tmp
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Done in 4.84s.
+ yarn build:pro --prefer-offline
yarn run v1.22.17
$ cross-env UMI_ENV=pro umi build --prefer-offline
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Bundle with webpack 5...
[info] [webpackbar] Compiling Webpack
(node:168) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:168) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:168) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

本地node、yarn版本和Jenkins版本一致

## Context

- **Umi Version**:
`^3.5.20`
- **Node Version**:
`v16.13.0`
- **Platform**:
`mac complete but push to linux error`

**Comment by bnyte** [comment]
feat:
- 我尝试将`dist`推送到GitHub 不执行`yarn`和`yarn build:pro`他是可以实现的，处理`ts`和`tsx`所有文件夹都不包含大写及驼峰命名

**Comment by xyy7260** [comment]
我也遇到这样的问题， 本地运行没问题，打包后出错

**Comment by bnyte** [comment]
> 

本地可以 服务器不可以是因为你的服务器配置不够，我已经解决了，我现在关闭这个issue

**Comment by JoMartinezZhu** [comment]
> > 
> 
> 本地可以 服务器不可以是因为你的服务器配置不够，我已经解决了，我现在关闭这个issue

说一下你的解决方案呀

**Comment by yancongwen** [comment]
npm run build 命令添加环境变量：BROWSERSLIST_IGNORE_OLD_DATA=true
`"build": "cross-env BROWSERSLIST_IGNORE_OLD_DATA=1 umi build",`

**Comment by houchaowei** [comment]
并没有解决问题

> npm run build 命令添加环境变量：BROWSERSLIST_IGNORE_OLD_DATA=true `"build": "cross-env BROWSERSLIST_IGNORE_OLD_DATA=1 umi build",`

**Comment by chj-damon** [comment]
我也遇到这个问题了，但是服务器没法加资源，挺惨
