### ISSUE TITLE
[Bug] 发布后的站点，只要有任何JS报错，页面就会白屏，是否有配置项可关闭该行为

### ISSUE THREAD

**Issue by costaq** [umijs/umi#7740]
## What happens?

发布后的站点，只要有任何JS报错，页面就会白屏，是否有配置项可关闭该行为
本地开发过程中，是显示黄页，并提示js错误位置，发布后，有任何js报错，则会白屏，我不希望有这个行为

## Context

- **Umi Version**:3.2.3
- **Node Version**:
- **Platform**:

**Comment by williamnie** [comment]
这个和umi没啥关系，错误处理需要自己去做，js的严重报错会导致堆栈报错，最好在componentDidCatch中捕获一下，走自己的ErrorBoundary

**Comment by costaq** [comment]
> 这个和umi没啥关系，错误处理需要自己去做，js的严重报错会导致堆栈报错，最好在componentDidCatch中捕获一下，走自己的ErrorBoundary

有关系吧，不用umi，js报错仅仅只是在控制台报错，而不会白屏，现在像是把错误拦截了
