### ISSUE TITLE
[Bug] Module '"umi"' has no exported member 'Access'

### ISSUE THREAD

**Issue by PlayApple** [umijs/umi#7745]
升级"@umijs/preset-react": "^2.1.0" 后，.umi下没有plugin-access了。
导致从umi下引入Access会出现不存在。

import { Access } from 'umi';
Module '"umi"' has no exported member 'Access' .ts(2305)

![20211229184816](https://user-images.githubusercontent.com/3360969/147654493-9d956e08-dc54-4949-83ab-e8104509b29b.jpg)

**Comment by PlayApple** [comment]
删除.umi，删除node_modules，删除yarn.lock，都无法解决。

**Comment by xiaohuoni** [comment]
增加配置试试
```
access:{}
```

**Comment by baibaibai455** [comment]
测试 添加 access:{}  可以解决

**Comment by mshauny** [comment]
Please kindly assist, I'm also facing the same issue
![image](https://user-images.githubusercontent.com/3635959/168489400-7ffeb92e-4b18-4bac-a715-c546c8baa94d.png)

**Comment by mshauny** [comment]
请帮忙，我也遇到同样的问题
![168489400-7ffeb92e-4b18-4bac-a715-c546c8baa94d](https://user-images.githubusercontent.com/3635959/169393979-df29bd42-23ab-4a5e-b7d0-bc051b488e7c.png)
