### ISSUE TITLE
[mfsu开启 fastRefresh开启情况下热更新无效]

### ISSUE THREAD

**Issue by cuiaiguanggh** [umijs/umi#7751]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by GOWxx** [comment]
重复 issues
先关掉 mfsu
等更新

**Comment by jiangdexiao** [comment]
同样问题

**Comment by JamieMing** [comment]
这个问题老bug了，一直没解决，也不知道官方是真不知道还是假不知道

**Comment by xiaohuoni** [comment]
> 重复 issues 先关掉 mfsu 等更新

@JamieMing 没看到给过回复了嘛？也不知道你是真看不到还是假看不到

**Comment by yl196356303** [comment]
现在还没解决吗。。。

**Comment by GOWxx** [comment]
> 现在还没解决吗。。。

升级到 umi4
