### ISSUE TITLE
希望官网文档在 typescript 方面可以补全一下

### ISSUE THREAD

**Issue by karmiy** [umijs/umi#7756]
## 背景

umi 创建的项目已集成 typescript，但官方文档在这方面并无特别补全，开发者找不到对应 TS 类型

如：

```tsx
// 并不知道 location, routes, action, matchedRoutes 这些项的类型从哪 import
// import from 'umi' 有些也不一定可以找到，或者不确定自己找的对不对
export function onRouteChange({ location, routes, action, matchedRoutes }) {
  bacon(location.pathname);
}
```

## 期望

官网文档可以补全文档中 typescript 的类型，谢谢

**Comment by geekact** [comment]
除非根据能根据配置在项目中自动生成**.d.ts**文件，否则TS提示就是奢望。这一点可以借鉴ORM [prisma](https://github.com/prisma/prisma) 的完美做法
