### ISSUE TITLE
[Bug] umi use hooks error

### ISSUE THREAD

**Issue by zqran** [umijs/umi#7757]
## What happens?

通过 umi 脚手架创建的新项目，在 pages/index.tsx 中使用 hooks，在两次使用 useState hook 并保存代码后，出现以下错误：
![image](https://user-images.githubusercontent.com/15389209/148328834-185a1189-faef-4024-a0ab-cb8bb7eb3828.png)

## Mini Showcase Repository(REQUIRED)

[可复现仓库地址 https://github.com/zqran/umi-bug-report](https://github.com/zqran/umi-bug-report)

## How To Reproduce

**Steps to reproduce the behavior:** 

1. 在 pages/index.tsx 中，使用 useState 提供第一个状态，并保存代码
2. 在 pages/index.tsx 中，使用 useState 提供第二个状态，并保存代码。**此时，浏览器中就会出现上述错误**

**Expected behavior:**

1. 在 pages/index.tsx 中，使用 useState 提供第一个状态，并保存代码
2. 在 pages/index.tsx 中，使用 useState 提供第二个状态，并保存代码。_此处，热更新时，浏览器不应该报错！_

复现步骤如上，**没有对项目配置做任何修改**，就会出现以上问题。

## Context

- **Umi Version**: 3.5.20
- **Node Version**: 16.6.2
- **Platform**: MacOS

**Comment by GOWxx** [comment]
老问题了，新加个 `useState` 会报这个错 新加状态后刷新下页面就好了 我现在就是刷新解决
可能和 `fastRefresh` 有关 配置项里关一下有用不
```diff
/umi-bug-report/.umirc.ts 

-  fastRefresh: {},
+ // fastRefresh: {},
```
说不定就没这个问题了

不知道 umi@4 修复没
等待中 ...

**Comment by zqran** [comment]
> 老问题了，新加个 `useState` 会报这个错 新加状态后刷新下页面就好了 我现在就是刷新解决 可能和 `fastRefresh` 有关 配置项里关一下有用不
> 
> ```diff
> /umi-bug-report/.umirc.ts 
> 
> -  fastRefresh: {},
> + // fastRefresh: {},
> ```
> 
> 说不定就没这个问题了
> 
> 不知道 umi@4 修复没 等待中 ...

关闭了 fastRefresh，每次保存代码，浏览器都会重新刷新，确实就不会有这个问题了。但热更新就用不了了~ 这太暴力了...

**Comment by GOWxx** [comment]
> @GOWxx 关闭了 fastRefresh，每次保存代码，浏览器都会重新刷新，确实就不会有这个问题了。但热更新就用不了了~ 这太暴力了...

开启 `fastRefresh` 的情况下，报这个错后，刷新一次，就可以继续正常用了，也有热更新
不用每次刷新的，暂时是个 bug 吧

**Comment by zqran** [comment]
> > @GOWxx 关闭了 fastRefresh，每次保存代码，浏览器都会重新刷新，确实就不会有这个问题了。但热更新就用不了了~ 这太暴力了...
> 
> 开启 `fastRefresh` 的情况下，报这个错后，刷新一次，就可以继续正常用了，也有热更新 不用每次刷新的，暂时是个 bug 吧

确实可以，但是，这太影响开发体验了~ 还得手动刷新一下，有点难受！

**Comment by GOWxx** [comment]
> 确实可以，但是，这太影响开发体验了~ 还得手动刷新一下，有点难受！

确实~
