### ISSUE TITLE
[Bug] Seeting "mfsu: {}", The browser network will request all the js, and the web will slow load in first render.

### ISSUE THREAD

**Issue by DuncanXiao** [umijs/umi#7763]
## In develop, Setting "mfsu: {}", the web will slow load in first render.
![企业微信截图_20220107101009](https://user-images.githubusercontent.com/34067083/148480101-6b680766-91b1-4d95-a363-35749987e09a.png)
![企业微信截图_20220107101028](https://user-images.githubusercontent.com/34067083/148480123-e1e322f8-d12a-4530-825f-ea0975595995.png)
![企业微信截图_20220107101055](https://user-images.githubusercontent.com/34067083/148480593-7032c7aa-dae1-47dd-a5d5-815234b2c36b.png)
![企业微信截图_20220107101450](https://user-images.githubusercontent.com/34067083/148480595-74db3bea-fab3-4292-977f-33ecd105ab84.png)

## In develop, Not Setting "mfsu: {}", the network not load hello.js, and fast load in first render.
![企业微信截图_20220107102048](https://user-images.githubusercontent.com/34067083/148481055-df9ae0a3-3362-4c20-961b-a73915b04231.png)
![企业微信截图_20220107102101](https://user-images.githubusercontent.com/34067083/148481282-9846605f-23a0-434f-89d5-64516ba55d4c.png)
![企业微信截图_20220107102109](https://user-images.githubusercontent.com/34067083/148481285-4e5a24f4-6d14-4004-b613-2cf393be28d2.png)
![企业微信截图_20220107102225](https://user-images.githubusercontent.com/34067083/148481286-73c8b898-e192-430f-bf62-f3dc11c6a421.png)

## Context

- **Umi Version: ^3.5.20**:
- **Node Version: v14.15.1**:

**Comment by shiluoma** [comment]
I hava the same question

**Comment by nemo02622** [comment]
有任何进展没
