### ISSUE TITLE
[Bug] 生产环境 mfsu 不能正常使用

### ISSUE THREAD

**Issue by hzfvictory** [umijs/umi#7764]
## What happens?

antd pro v4 ，为了尝鲜 mfsu，umi版本升级到 v3.2.14，本地开发启动正常，生产环境报错 

**打包终端报错**
```
 error  in ./node_modules/umi-plugin-antd-icon-config/lib/app.js

Module not found: Error: Can't resolve '@@/plugin-antd-icon/icons' in '/Users/hzf/workspace/bmh/node_modules/umi-plugin-antd-icon-config/lib'

ERROR in ./node_modules/umi-plugin-antd-icon-config/lib/app.js 8:36-72
Module not found: Error: Can't resolve '@@/plugin-antd-icon/icons' in '/Users/hzf/workspace/bmh/node_modules/umi-plugin-antd-icon-config/lib'
 @ ./.mfsu-production/mf-va_$CWD$_node_modules_umi-plugin-antd-icon-config_lib_app.js.js 1:0-93 1:0-93
 @ container entry ./$CWD$/node_modules/umi-plugin-antd-icon-config/lib/app.js[0]
```

**页面访问**

![](https://tva1.sinaimg.cn/large/008i3skNly1gy53a81q1sj30lu0fj77t.jpg)

**config 配置项**

```
 hash: true,
  antd: {},
  dva: {
    hmr: true,
  },
  mfsu: {
    development: {output: '.mfsu-development'},
    production: {output: '.mfsu-production'},
  },
  webpack5: {},
  fastRefresh: {},
  dynamicImport: {
    loading: '@/components/PageLoading/index',
  },
  targets: {
    chrome: 65,
  },
  locale: {
    default: 'zh-CN',
    title: true,
    baseNavigator: false,
  },
  routes,
  theme: {
    'primary-color': defaultSettings.primaryColor,
  },
  title: false,
  ignoreMomentLocale: true,
  proxy: proxy[REACT_APP_ENV || 'dev'],
  manifest: {
    basePath: '/',
  },
  nodeModulesTransform: {
    type: 'none',
  },
}
```

## Context

- **Umi Version**:  v3.2.14
- **Node Version**:  v14.17.6
- **Platform**: MacOS

**Comment by aierweisi** [comment]
我也是遇到了同样的问题，请问有解决吗

**Comment by io-better** [comment]
我在jenkins上构建时也出现了这个问题
![image](https://user-images.githubusercontent.com/49950459/151643078-77527e1e-353b-4324-924e-c9dd4a1b2554.png)

**Comment by io-better** [comment]
配置
// https://umijs.org/config/
import { defineConfig } from 'umi';
import { join } from 'path';

import defaultSettings from './defaultSettings';
import proxy from './proxy';
import routes from './routes';

const { REACT_APP_ENV } = process.env;

export default defineConfig({
  hash: true,
  antd: {},
  dva: {
    hmr: true,
  },
  history: { type: 'hash' },
  layout: {
    // https://umijs.org/zh-CN/plugins/plugin-layout
    locale: true,
    siderWidth: 208,
    ...defaultSettings,
  },
  // https://umijs.org/zh-CN/plugins/plugin-locale
  locale: {
    // default zh-CN
    default: 'zh-CN',
    antd: true,
    // default true, when it is true, will use `navigator.language` overwrite default
    baseNavigator: true,
  },
  dynamicImport: {
    loading: '@ant-design/pro-layout/es/PageLoading',
  },
  targets: {
    ie: 11,
  },
  // umi routes: https://umijs.org/docs/routing
  routes,
  // Theme for antd: https://ant.design/docs/react/customize-theme-cn
  theme: {
    'primary-color': defaultSettings.primaryColor,
    'root-entry-name': 'default',
  },
  // esbuild is father build tools
  // https://umijs.org/plugins/plugin-esbuild
  esbuild: {},
  title: false,
  ignoreMomentLocale: true,
  proxy: proxy[REACT_APP_ENV || 'dev'],
  manifest: {
    basePath: '/',
  },
  // Fast Refresh 热更新
  fastRefresh: {},
  nodeModulesTransform: { type: 'none' },
  webpack5: {},
  exportStatic: {},
});

**Comment by io-better** [comment]
![image](https://user-images.githubusercontent.com/49950459/151643105-cc1e4811-b856-42b0-9f4d-1e9ef6c4c309.png)

**Comment by prophetw** [comment]
Can't resolve '@@/plugin-antd-icon/icons'    @@ 属于 webpack resolve 部分配置

```bash
# 查看 umi webpack5 的配置 resolve.alias 部分是否有问题
NODE_ENV=production umi webpack 
```
着急解决不妨试试以下
1.测试使用 webpack4 是否有问题（webpack5对resolve部分做了一些变更可能会有问题）
2.@@改成相对路径看是否还有问题

**Comment by hotfireeagle** [comment]
> 我在jenkins上构建时也出现了这个问题 ![image](https://user-images.githubusercontent.com/49950459/151643078-77527e1e-353b-4324-924e-c9dd4a1b2554.png)

请问解决了吗，我这边也是服务器打包遇到了这个问题

**Comment by hotfireeagle** [comment]
> 我在jenkins上构建时也出现了这个问题 ![image](https://user-images.githubusercontent.com/49950459/151643078-77527e1e-353b-4324-924e-c9dd4a1b2554.png)

@io-better hello，请问解决了吗，我这边在服务器上打包时也遇到了这个问题

**Comment by leewanmei** [comment]
您好，您的邮件我已收到，辛苦啦！

**Comment by hpysirius** [comment]
怎么解决的？

**Comment by leewanmei** [comment]
您好，您的邮件我已收到，辛苦啦！
