### ISSUE TITLE
这段代码加载哪个文件里呢

### ISSUE THREAD

**Issue by fullee** [umijs/umi#7765]
https://github.com/umijs/umi/blob/820440f95410501de8e5895fe7595e6c80ac6924/docs/plugins/plugin-access.zh-CN.md?plain=1#L35

**Comment by xiaohuoni** [comment]
你好说有的配置都是加载 umi 的配置文件中 
`Umi 在 .umirc.ts 或 config/config.ts 中配置项目和插件` https://umijs.org/zh-CN/docs/config
