### ISSUE TITLE
3.5.20 启用 mfsu后，workbox-webpack-plugin(pwa) 出错

### ISSUE THREAD

**Issue by jcsofts** [umijs/umi#7772]
环境
"umi": "^3.5.20",
"workbox-cacheable-response": "^6.4.2",
  "workbox-core": "^6.4.2",
  "workbox-expiration": "^6.4.2",
  "workbox-navigation-preload": "^6.4.2",
  "workbox-precaching": "^6.4.2",
  "workbox-routing": "^6.4.2",
  "workbox-strategies": "^6.4.2",
  "workbox-webpack-plugin": "^6.4.2"
  
  npm start后出错
  ERROR  Failed to compile with 7 errors                                                                                                                                       9:47:40 AM

 error  in remote mf/$CWD$/node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/esm/objectSpread2

Module not found: Error: Can't resolve 'webpack/container/reference/mf' in '/Users/lee/Develop/php/app-crm/src/app-crm-frontend/crm-client'

 error  in remote mf/workbox-cacheable-response

Module not found: Error: Can't resolve 'webpack/container/reference/mf' in '/Users/lee/Develop/php/app-crm/src/app-crm-frontend/crm-client'

 error  in remote mf/workbox-core

Module not found: Error: Can't resolve 'webpack/container/reference/mf' in '/Users/lee/Develop/php/app-crm/src/app-crm-frontend/crm-client'

 error  in remote mf/workbox-expiration

Module not found: Error: Can't resolve 'webpack/container/reference/mf' in '/Users/lee/Develop/php/app-crm/src/app-crm-frontend/crm-client'

 error  in remote mf/workbox-precaching

Module not found: Error: Can't resolve 'webpack/container/reference/mf' in '/Users/lee/Develop/php/app-crm/src/app-crm-frontend/crm-client'

 error  in remote mf/workbox-routing

Module not found: Error: Can't resolve 'webpack/container/reference/mf' in '/Users/lee/Develop/php/app-crm/src/app-crm-frontend/crm-client'

 error  in remote mf/workbox-strategies

Module not found: Error: Can't resolve 'webpack/container/reference/mf' in '/Users/lee/Develop/php/app-crm/src/app-crm-frontend/crm-client'

禁用mfsu后可以启动运行

**Comment by sherry007** [comment]
跟我提的这个类似 https://github.com/umijs/umi/issues/7033，有没有大佬出来解决一下啊

**Comment by xuMINGzhi9** [comment]
我也遇到了，不能在service-worker.js文件中，通过import 进行导入 @sherry007 @jcsofts

**Comment by xuMINGzhi9** [comment]
https://developer.chrome.com/docs/workbox/reference/workbox-build/#type-WebpackInjectManifestOptions

**Comment by xuMINGzhi9** [comment]
> 我也遇到了，不能在service-worker.js文件中，通过import 进行导入 @sherry007 @jcsofts

https://developer.chrome.com/docs/workbox/reference/workbox-build/#type-WebpackInjectManifestOptions
InjectManifest 的 compileSrc 为fasle 就可以了 @jcsofts @sherry007
