### ISSUE TITLE
[Bug] 开启mfsu后，样式丢失

### ISSUE THREAD

**Issue by PingZaiDotTse** [umijs/umi#7788]
#### 环境：
umi+ts+antd
"umi": "^3.5.20"
"react": "16.x"

#### 问题详细描述：

```js
    //config
   antd:{
       config:{
           prefixCls: 'kcmp-ant',
           // getPopupContainer:(triggerNode:HTMLElement)=>triggerNode
       }
   },
   lessLoader: {
       modifyVars: { '@ant-prefix': 'kcmp-ant' } 
   }, 
   mfsu:{}

```

**Comment by lyj505** [comment]
我已经关了😄
![image](https://user-images.githubusercontent.com/17819611/149492146-5029cdd4-52f6-4e66-9eaa-7bb32f6ff03e.png)

**Comment by PingZaiDotTse** [comment]
> 我已经关了😄
> 
> ![image](https://user-images.githubusercontent.com/17819611/149492146-5029cdd4-52f6-4e66-9eaa-7bb32f6ff03e.png)
> 
> 

目前我也是只能这样处理

**Comment by Donlei** [comment]
我的也是 procomponent组件的样式 错乱 ，没法 ，关闭了

**Comment by JoMartinezZhu** [comment]
@sorrycc ,
复现步骤，很简单：
1、使用umi ,创建 ant-design-pro simple 版本，yarn create umi demo
2、修改 config.ts文件，如下示例：
<img width="628" alt="image" src="https://user-images.githubusercontent.com/43346131/163075840-fe8ecb8a-5742-46f1-859f-9303f4a82b3e.png">
3、清除 .umi，重启 项目 yarn start

组件的样式，不生效了

**Comment by jkiss** [comment]
我家里的电脑（Mac M1）没问题，在公司电脑（Mac Intel）又起个项目，样式就错乱了，真是醉了。。。

**Comment by JoMartinezZhu** [comment]
> 

每次改变 mfsu 这个配置项的时候，删除一下 .umi ,然后重启，M1 和 Intel 都会 错乱的

**Comment by jkiss** [comment]
> > 
> 
> 每次改变 mfsu 这个配置项的时候，删除一下 .umi ,然后重启，M1 和 Intel 都会 错乱的

暂时关闭了MFSU，坐等Umi4 :clown_face:

**Comment by JoMartinezZhu** [comment]
> 

😂
其实我试着本地去调试，尝试解决这个问题，但是止步于 yarn link umi 一致报错，一步一坑。

**Comment by giscafer** [comment]
Umi 4， 开启msfu 和不开启 prolayout 样式不一致。真是奇怪 ，umi3是从没用过msfu，想试一下Umi4 的，还是有点问题
