### ISSUE TITLE
umi如何引入tailwindCss

### ISSUE THREAD

**Issue by strongyc** [umijs/umi#7789]
## Proposal
umi如何引入tailwindCss,tailwindCss挺好用的
Describe the solution you'd like, better to provide some pseudo code.

**Comment by 986244073** [comment]
不好弄 我也不晓得

**Comment by 986244073** [comment]
用nextjs吧

**Comment by xxdd13** [comment]
可以用tailwind 2.x
[with-tailwind example](https://github.com/umijs/umi/tree/master/examples/with-tailwind)
