### ISSUE TITLE
部署以后，执行dispatch后执行.then()会报错

### ISSUE THREAD

**Issue by jogasa** [umijs/umi#779]
遇到了和 [https://github.com/umijs/umi/issues/725#thread-subscription-status](url) 这个issue一样的问题

页面报的错误信息：
![image](https://user-images.githubusercontent.com/23027247/43763176-a8244c10-9a5c-11e8-8cc7-f592a60aa23f.png)

**Comment by sorrycc** [comment]
怎么重现？

**Comment by sorrycc** [comment]
> 当去调用别的model里的reducer的时候，通过.then去处理返回的数据，就会有这样的错误发生，之前只使用dva的时候并不会有这种情况出现。

dispatch(reducer) 不会返回 Promise 的，只有 dispatch(effect) 会。

**Comment by redrum1900** [comment]
我之前是在subscriptions中dispatch其他model中的effect，然后then出现这个错误。只有在build之后才会出现。
可能是我流程的问题。我想在A使用B的model的数据，然后在subscriptions中调用了B的model的effect，然后debugger时发现没有执行B的effect。然后我点击了一下B页面，然后再次回到A页面，这次在subscriptions中调用了B的model的effect，就可以执行。

**Comment by jogasa** [comment]
@sorrycc 我这边就是在 dispatch(effect) 的时候报的这个错，之前只用dva的时候并不会出现这样的错误

**Comment by jogasa** [comment]
@redrum1900 我是即使调用当前connect的model的时候也会报这样的错误...

**Comment by sorrycc** [comment]
给个可重现例子再 reopen 吧。
