### ISSUE TITLE
[Bug] When @umijs/preset-react upgrade version to 2.1.1, the useAccess and locales was fail.

### ISSUE THREAD

**Issue by JennyLeung030** [umijs/umi#7797]
## What happens?
When  @umijs/preset-react upgrade version to 2.1.1, the useAccess and locales was fail.

Error for useAccess:
export 'useAccess' (imported as 'useAccess') was not found in 'umi' (possible exports: ApplyPluginsType, ErrorShowType, FormattedDate, FormattedDateParts, FormattedrmattedTimeParts, Helmet, IntlContext, IntlProvider, Link, MemoryRouter, NavLink, Plugin, Prompt, RawIntlProvider, Redirect, Route, Router, SelectLang, StaticRouter, Switch, UseRequestProvider, __PLUGIN_INITIAL_STATE, __RouterContext, addLocale, createBrowserHistory, createHashHistory, createIntl, createIntlCache, createMemoryHistory, defineMessages, dynamic, formatMessage, getAllLocales, getDirection, getIntl, getLocale, history, injectIntl, isBrowser, localeInfo, matchPath, plugin, request, setIntl, setLocale, useHistory, useIntl, useLocation, useModel, useParams, useRequest, useRouteMatch, withRouter)

Error for locales:
Warning: The current popular language does not exist, please check the locales folder!

![image](https://user-images.githubusercontent.com/51438629/149894107-057c1642-359a-4dcf-8000-541c6a91f776.png)

![image](https://user-images.githubusercontent.com/51438629/149894134-eacfbe09-8ea3-4ad2-909e-470ae417c6e8.png)

When I upgrade umijs/preset-react upgrade version 1.8.17 to 2.1.1

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.5.0
- **Node Version**: v14.17.6.
- **Platform**:

**Comment by AnoyiX** [comment]
+1

**Comment by PingChou** [comment]
I resolved this problem by modifying the `.umirc.ts`,but it's not consistent with the documentation
```
access: {},
locale: {
    default: 'zh-CN',
    antd: true,
    title: false,
    baseNavigator: true,
    baseSeparator: '-',
 },
```

**Comment by Renjiaxing2613** [comment]
> 我通过修改解决了这个问题，但它与文档不一致`.umirc.ts`
> 
> ```
> access: {},
> locale: {
>     default: 'zh-CN',
>     antd: true,
>     title: false,
>     baseNavigator: true,
>     baseSeparator: '-',
>  },
> ```

very good，keep studying，day day up
