### ISSUE TITLE
[Bug]无法配置自定义的环境变量

### ISSUE THREAD

**Issue by Wangggym** [umijs/umi#7799]
## What happens?
   配置的环境变量没有生效
![image](https://user-images.githubusercontent.com/26135370/149910748-e16d28f6-cd82-480b-91ba-438ea5f77a97.png)
![image](https://user-images.githubusercontent.com/26135370/149910780-2693ece8-f557-4087-8e48-822e67af3799.png)
控制台中无法打印出 自定义的环境变量
![image](https://user-images.githubusercontent.com/26135370/149910862-b26daa78-1800-4857-8dd6-7c194ac6f6da.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by jk4235** [comment]
你可以创建两个和`.umirc.ts`平级的文件, `.umirc.dev.ts` 和 `.umirc.prod.ts`

文件内定义你不同环境下的process.env

example:
```ts
import { defineConfig } from "umi";

export default defineConfig({
  define: {
    "process.env": {
      SOME_KEY: "value",
      APP_COOKIE_TOKEN: 123456,
    },
  },
});
```

之后修改你的package.json命令

```
build: UMI_ENV=prod umi build
start: UMI_ENV=dev umi build
```

当然, dev, prod名称是可以替换的

**Comment by yzwxk** [comment]
@jk4235 为什么不能直接使用process.env 需要在define里设置呢

**Comment by jk4235** [comment]
umi中的环境变量列表只有[这些](https://umijs.org/zh-CN/docs/env-variables)

想要自定义的环境变量, 这是我找到的一个workaround方法

而且可以保持类型,而不是都是字符串

**Comment by ldwonday** [comment]
设置一个环境变量真是麻烦，绕来绕去的，搞的我花了一个多小时才搞明白，真是烦躁，直接通过coss-env设置自己想要的环境变量和值有那么难吗，谁搞的现在的这种设计，拉出来打一顿算了。

**Comment by peter064226** [comment]
> 设置一个环境变量真是麻烦，绕来绕去的，搞的我花了一个多小时才搞明白，真是烦躁，直接通过coss-env设置自己想要的环境变量和值有那么难吗，谁搞的现在的这种设计，拉出来打一顿算了。

深有体会，这个玩意真是好麻烦啊，很简单的东西弄的这么麻烦，弄了好久也不生效

**Comment by tinyzh** [comment]
找了快一天，发现UMI_ENV不能定义为dev,prod,test,得自定义自己的环境变量

**Comment by luoyelusheng** [comment]
最新简洁用法，直接在`.umirc`中加上这一行，直接可以使用`cross-env`环境变量，无需定义多个配置文件
` define: {
        "process.env": {
            ...process.env,
        },
    },`

**Comment by littcc** [comment]
> 最新简洁用法，直接在`.umirc`中加上这一行，直接可以使用`cross-env`环境变量，无需定义多个配置文件 ` define: { "process.env": { ...process.env, }, },`

有效，这个设计相当奇怪。。。

**Comment by mdddj** [comment]
umi4 怎么设置
