### ISSUE TITLE
[Bug] umi 和 tailwindcss3 不兼容，postcss版本问题

### ISSUE THREAD

**Issue by yudonghan** [umijs/umi#7804]
## What happens?
umi项目打算使用tailwindcss的时候，css解析失败，报
```
Module build failed (from ./node_modules/@umijs/bundler-webpack/lib/webpack/plugins/mini-css-extract-plugin/src/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: PostCSS plugin postcss-import requires PostCSS 8.
```
主要是@umijs/bundler-webpack里面引用的postcss版本为7，与tailwindcss3依赖的t版本不一致

**Comment by sunjiesama** [comment]
一样的报错  请问你解决了嘛

**Comment by yudonghan** [comment]
> 一样的报错 请问你解决了嘛

 这个要依赖umi升级自己的依赖，现在还没搞定吗，我目前的解决方法是独立处理tailwindcss，在packagejson里写这样一个脚本：
```
    "buildTwcss": "npx tailwindcss -i ./src/input.css -o ./public/output.css --watch",
    "buildTwcss:product": "npx tailwindcss -i ./src/input.css -o ./public/output.css --minify"
```
参考： https://tailwindcss.com/docs/installation/using-postcss

继承到umi，只能等他们更新自己的postcss

**Comment by CareyToboo** [comment]
安装 4.x预发布版本这个好像问题解决了。 `yarn add -D umi@4.0.0-rc.14 `

**Comment by HaishengLiang** [comment]
umi@3.x 的postcss 有升级到8.x的计划吗? 这块的兼容不太好

**Comment by lijun-wu** [comment]
> [umi@3.x](mailto:umi@3.x) 的postcss 有升级到8.x的计划吗? 这块的兼容不太好

一样遇到了这个问题，umi3下既需要postcss>7.0.36的版本，又需要postcss>8.4.31的版本，这两个版本可以解决umi框架自身的两个问题，啥时候可以修复啊

**Comment by cixiangtao** [comment]
马德，用这个垃圾umi天天一堆问题
