### ISSUE TITLE
[Bug] umi 3.5.x开启mfsu导致global.less样式无法覆盖antd样式.

### ISSUE THREAD

**Issue by ziitar** [umijs/umi#7805]
## What happens?

我有个内部的基于antd封装的组件库 基于antd的class覆盖了一些antd样式，然后这个组件库的样式是在global.less里引入的。
umi 3.5.20 开启mfsu配置，global.less样式在antd的样式之前被引入。导致了无法覆盖antd同名样式。
## Mini Showcase Repository(REQUIRED)

> [Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库](https://codesandbox.io/s/cool-brattain-4q3td?file=/.umirc.ts)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

umirc.ts 配置mfsu:{}, antd: {}
在gloabl.less下添加一个antd的同名样式。
## Context

- **Umi Version**: 3.5.20
- **Node Version**:12.22.3
- **Platform**:window 10

**Comment by kzxuan** [comment]
一样的问题，只要开启 mfsu，global.less 就失效了
