### ISSUE TITLE
[Bug] 路由browser模式下，在开发态，访问页面路径后面会多出一个‘#’结尾

### ISSUE THREAD

**Issue by vtronxy** [umijs/umi#7807]
## What happens?
在默认路由配置，也就是 history: {type: 'browser'} 模式下，
在开发态下，访问路由路径比如 http://localhost:8000/exam-manage/paper/edit
浏览器上最终的地址会变成http://localhost:8000/exam-manage/paper/edit#/

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- v3.5.20
- **Node Version**:
- v16.10.0
- **Platform**:
- macOS 12.1

**Comment by MyAuntIsPost90s** [comment]
同样遇到了这个问题，但是是在打包构建在nginx上时，非根目录
