### ISSUE TITLE
openApi mock数据问题

### ISSUE THREAD

**Issue by remberi** [umijs/umi#7812]
通过openApi自动生成的mock文件，里面的response没有mock数据数据
![image](https://user-images.githubusercontent.com/11532442/150762003-42505128-90e9-4785-9ef6-851ffd5c318c.png)
swagger文件
![image](https://user-images.githubusercontent.com/11532442/150762214-a9c4a465-c518-4b7e-9386-758d7bb03747.png)
映射的返回类型
![image](https://user-images.githubusercontent.com/11532442/150762221-41f75dd3-d3dd-419c-b06a-b4dc5171b2b9.png)

是不是还需要自己实现mock返回数据-。-

**Comment by weilun0510** [comment]
@sorrycc 为什么关闭这个问题，请问怎么解决呢？

**Comment by weilun0510** [comment]
> 通过openApi自动生成的mock文件，里面的response没有mock数据数据 ![image](https://user-images.githubusercontent.com/11532442/150762003-42505128-90e9-4785-9ef6-851ffd5c318c.png) swagger文件 ![image](https://user-images.githubusercontent.com/11532442/150762214-a9c4a465-c518-4b7e-9386-758d7bb03747.png) 映射的返回类型 ![image](https://user-images.githubusercontent.com/11532442/150762221-41f75dd3-d3dd-419c-b06a-b4dc5171b2b9.png)
> 
> 是不是还需要自己实现mock返回数据-。-

解决了吗？

**Comment by weilun0510** [comment]
> 通过openApi自动生成的mock文件，里面的response没有mock数据数据 ![image](https://user-images.githubusercontent.com/11532442/150762003-42505128-90e9-4785-9ef6-851ffd5c318c.png) swagger文件 ![image](https://user-images.githubusercontent.com/11532442/150762214-a9c4a465-c518-4b7e-9386-758d7bb03747.png) 映射的返回类型 ![image](https://user-images.githubusercontent.com/11532442/150762221-41f75dd3-d3dd-419c-b06a-b4dc5171b2b9.png)
> 
> 是不是还需要自己实现mock返回数据-。-

将 "*/*" 全部替换为 "application/json" 即可。

**Comment by weilun0510** [comment]
> 通过openApi自动生成的mock文件，里面的response没有mock数据数据 ![image](https://user-images.githubusercontent.com/11532442/150762003-42505128-90e9-4785-9ef6-851ffd5c318c.png) swagger文件 ![image](https://user-images.githubusercontent.com/11532442/150762214-a9c4a465-c518-4b7e-9386-758d7bb03747.png) 映射的返回类型 ![image](https://user-images.githubusercontent.com/11532442/150762221-41f75dd3-d3dd-419c-b06a-b4dc5171b2b9.png)
> 
> 是不是还需要自己实现mock返回数据-。-

将 "*/*" 全部替换为 "application/json"
