### ISSUE TITLE
[Bug] 如何调试 umi 源码

### ISSUE THREAD

**Issue by robinv8** [umijs/umi#7815]
根据文档执行如下命令：
```
 yarn debug examples/normal dev
```
报错如下：
![image](https://user-images.githubusercontent.com/12277531/150933156-45a5d1a4-fbb7-47b6-8ceb-9ac77b0000e8.png)

跟踪代码发现：
![image](https://user-images.githubusercontent.com/12277531/150933430-d8fe7c60-8cf2-452a-b15e-4c383b74140d.png)
args 参数有问题，`examples/normal` `dev` 两个参数位置不对，但调换两个参数位置，debugger 时不能进入断点，求解答？

**Comment by prophetw** [comment]
看 [umi贡献指南](https://github.com/umijs/umi/blob/master/CONTRIBUTING.md)

```bash
yarn example dev examples/normal
```

**Comment by ggwakaka** [comment]
> 根据文档执行如下命令：
> 
> ```
>  yarn debug examples/normal dev
> ```
> 
> 报错如下： ![image](https://user-images.githubusercontent.com/12277531/150933156-45a5d1a4-fbb7-47b6-8ceb-9ac77b0000e8.png)
> 
> 跟踪代码发现： ![image](https://user-images.githubusercontent.com/12277531/150933430-d8fe7c60-8cf2-452a-b15e-4c383b74140d.png) args 参数有问题，`examples/normal` `dev` 两个参数位置不对，但调换两个参数位置，debugger 时不能进入断点，求解答？

请问下,如何能断点进入umi packages/*/src下的源码, 而不是lib下编译后的代码?
