### ISSUE TITLE
[Bug]约定式路由模式，热更新编译检查到错误后，devserver会断开

### ISSUE THREAD

**Issue by anbingyang** [umijs/umi#7821]
## What happens?

约定式路由模式，热更新编译检查到错误后，devserver会断开

## How To Reproduce

1. yarn create @umijs/umi-app
2. 去掉umi配置文件中的routes配置，改为约定式
3. yarn && yarn start
4. 修改index.tsx 中的第一行的分号 改为中文分号，触发eslint error
5. dev-server断开

reason:

/@umijs/core/lib/Route/getConventionalRoutes.js   判断是抛出异常导出server停下

**Comment by anbingyang** [comment]
目前注释掉 catch块可以解决

**Comment by JakimLi** [comment]
> 目前注释掉 catch块可以解决

请问下在哪里注释？怎么解决的？

**Comment by LolipopJ** [comment]
`node_modules/@umijs/core/lib/Route/getConventionalRoutes.js`:

```js
...
try {
  if (!(0, _ast().isReactComponent)(content)) return false;
} catch (e) {
  // 注释↓
  // throw new Error(`Parse conventional route component ${absFile} failed, ${e.message}`);
}
...
try {
  props = (0, _ast().getExportProps)((0, _fs().readFileSync)(route.component, 'utf-8'));
} catch (e) {
  // 以及↓
  // throw new Error(`Parse conventional route component ${route.component} failed, ${e.message}`);
}
```

触发条件为 `pages` 下的页面路由文件编译错误时。猜测由于路由文件编译失败，导致无法获取对应的 React 组件，会抛出此报错信息。

但理论上应该只在控制台打出错误信息，而**不中止**本地服务。否则重新 `npm run start` 会花费额外时间。
