### ISSUE TITLE
使用mpa配置后，build时 怎么让每个页面有独立的js，css等

### ISSUE THREAD

**Issue by pxim** [umijs/umi#7825]
## Background

**使用mpa配置后，build时 怎么让每个页面有独立的js，css等**

有一些业务，是传统的 MPA（多页应用），并且他们是真的多页，因为每个页面之间的关系不大，强行套 SPA（单页应用）的模式意义并不大，反而多了一些冗余的代码，比如路由。

所以，为了让这些老业务能更容易地升级上来，享受新的技术栈，把 umi 单纯作为 webpack 封装工具来使用。同时，umi 的部分功能会不可用，比如路由、global.js、global.css、app.js 等。

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

## Additional context

build
------ page1
-------------page1.html
-------------page1.js
-------------page1.css
-------------static/images

------ page2
-------------page2.html
-------------page2.js
-------------page2.css
-------------static/images

**Comment by hzyhbk** [comment]
我也有同样的需求
