### ISSUE TITLE
如何配置插件啊

### ISSUE THREAD

**Issue by hqzh** [umijs/umi#783]
比如webpack-bundle-analyzer之类的插件

**Comment by sorrycc** [comment]
webpack-bundle-analyzer 内置了，`ANALYZE=1 umi build` 运行就好。

**Comment by hqzh** [comment]
@sorrycc 
"scripts": {
    "dev": "cross-env PORT=9090 ANALYZE=1 umi dev",
  },
这样?怎么看到webpack-bundle-analyzer官网说的那个效果[https://cloud.githubusercontent.com/assets/302213/20628702/93f72404-b338-11e6-92d4-9a365550a701.gif](url)

**Comment by sorrycc** [comment]
build 不是 dev 。

**Comment by hqzh** [comment]
@sorrycc 设了还是没效果

**Comment by hqzh** [comment]
@sorrycc build设了还是没效果

**Comment by lichenbuliren** [comment]
@sorrycc  请问这个文档在哪里，我找了半天都没找到
