### ISSUE TITLE
[Bug] access 权限问题，使用access函数返回了false，页面依然可以正常访问

### ISSUE THREAD

**Issue by zhidali** [umijs/umi#7838]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

![image](https://user-images.githubusercontent.com/46236834/153330615-bf37c117-a965-4089-bda7-07e9858257d4.png)

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/46236834/153330410-22d1a7e2-68f1-46ba-8cf0-1129bcbf4569.png">

使用access函数返回了false，页面依然可以正常访问

**Comment by leftstick** [comment]
来个可复现demo吧
