### ISSUE TITLE
[Bug] setLocale不起作用

### ISSUE THREAD

**Issue by sujingclg** [umijs/umi#7841]
## Mini Showcase Repository(REQUIRED)
最新版本的umi的setLocale无法切换语言，好像被锁死了。
> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by xiaojun1994** [comment]
我也遇到了这种问题，经过测试好像 umijs 没有对配置进行合并，如果 config 配置了 locale，则直接使用的就是你配置的内容，文档上所说的默认值这些都不生效了 
<img width="796" alt="image" src="https://user-images.githubusercontent.com/24448924/153557038-4f4f2fd7-50bc-444f-aec8-802470980d43.png">
<img width="667" alt="image" src="https://user-images.githubusercontent.com/24448924/153557106-b1725fe4-ac0d-401a-94ca-7e9ff81f5cf9.png">

**Comment by xiaojun1994** [comment]
貌似是合并 config 时候走到这里拿到的  defaultConfig 实际上是 userConfig，另一个项目无此问题

https://github.com/umijs/umi/blob/ce3cde070e38fcbfbb27765b8e673fa050f6eb62/packages/core/src/Config/utils/mergeDefault.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L9

**Comment by xiaojun1994** [comment]
好吧，找了一下午，终于找到了，这个插件导致的

https://github.com/umijs/plugins/blob/a50cd83fabefb164cdbe57ae8bbb1e9bc274f58e/packages/preset-react/src/defaultConfig.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L9

**Comment by sujingclg** [comment]
> 好吧，找了一下午，终于找到了，这个插件导致的
> 
> https://github.com/umijs/plugins/blob/a50cd83fabefb164cdbe57ae8bbb1e9bc274f58e/packages/preset-react/src/defaultConfig.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L9


> 我也遇到了这种问题，经过测试好像 umijs 没有对配置进行合并，如果 config 配置了 locale，则直接使用的就是你配置的内容，文档上所说的默认值这些都不生效了 <img alt="image" width="796" src="https://user-images.githubusercontent.com/24448924/153557038-4f4f2fd7-50bc-444f-aec8-802470980d43.png"> <img alt="image" width="667" src="https://user-images.githubusercontent.com/24448924/153557106-b1725fe4-ac0d-401a-94ca-7e9ff81f5cf9.png">

我按你说的办法把locale的配置项补全了，但还是不起作用啊

**Comment by azx1985** [comment]
setLocale不起作用，默认设置了‘zh-CN’，设置了setLocale(‘en-US’, false)，用getLocale打印出来是zhCN

**Comment by xiaojun1994** [comment]
https://github.com/umijs/plugins/pull/800

尝试改了一下，作者一直不合并，难道有问题

**Comment by sujingclg** [comment]
> [umijs/plugins#800](https://github.com/umijs/plugins/pull/800)
> 
> 尝试改了一下，作者一直不合并，难道有问题

哎，已经准备往ice上迁移了。
