### ISSUE TITLE
初始项目，引用ant-mobile v5 报错

### ISSUE THREAD

**Issue by conkyliu** [umijs/umi#7847]
```
Module not found: Error: Can't resolve 'antd-mobile/es/button/style' in '/Users/mac/Work/ltg-admin/src/pages'

 error  in ./src/pages/index.tsx

Module not found: Error: Can't resolve 'antd-mobile/es/button' in '/Users/mac/Work/ltg-admin/src/pages'

```
安装了"@umijs/plugin-antd-mobile": "^1.2.0",
应该是babel配置按需加载时，style=false，v5没有这个style目录
![image](https://user-images.githubusercontent.com/26617741/154052802-00b11120-c91e-45e7-b22d-18042793f810.png)
![image](https://user-images.githubusercontent.com/26617741/154053121-bdd83d1d-c83b-47c4-80d6-7d9f071c4082.png)

**Comment by conkyliu** [comment]
安装依赖 babel-plugin-import

**Comment by wszdhxh** [comment]
把antd关了, 配置文件里设置:  `antd: false`

**Comment by fankuneee** [comment]
@conkyliu 我安装了babel-plugin-import 但是antd-mobile组件的样式没有生效,除了配置extraBabelPlugins,还有别的需要配置吗?

**Comment by fankuneee** [comment]
antd 和 antd-mobile可以同时使用吗?

**Comment by corrie-70** [comment]
"@umijs/preset-react"版本： "1.x"，不安装plugin antd mobile 的情况下，实现antd mobile V2 和V5共存可以单独安装依赖babel-plugin-import
添加配置项：
```js
  extraBabelPlugins: [
    [
      'import',
      {
        libraryName: 'antd-mobile-v5',
        libraryDirectory: 'es/components',
        style: false,
      },
      'antd-mobile-v5',
    ],
    [
      'import',
      {
        libraryName: 'antd-mobile',
        libraryDirectory: 'es',
        style: true,
      },
      'antd-mobile',
    ],
  ],
```
