### ISSUE TITLE
umi 怎么配置dns-prefech、preload、prefetch

### ISSUE THREAD

**Issue by GODOFZHZ** [umijs/umi#7855]
umi 怎么配置dns-prefech、preload、prefetch

**Comment by JesseCHN** [comment]
+1

**Comment by kaindy7633** [comment]
+1

**Comment by littcc** [comment]
+1

**Comment by crazyair** [comment]
@sorrycc 这个有什么建议吗

**Comment by littcc** [comment]
配合api 自己处理下吧

`
import fs from 'fs';
import { IApi } from '@umijs/max';

const PRELOAD_AND_PREFETCH_FILE_REG = /preload|prefetch/;

export default (api: IApi) => {
    api.addHTMLLinks(() => {
        try {
            const files = fs.readdirSync('dist/static');
            if (files?.length) {
                return files
                    .filter((file) => PRELOAD_AND_PREFETCH_FILE_REG.test(file))
                    .map((path) => {
                        const [rel] = path.match(PRELOAD_AND_PREFETCH_FILE_REG) as RegExpMatchArray;
                        const isVideo = /\.mp4$/.test(path);
                        return { rel, as: isVideo ? 'video' : 'image', href: `/static/${path}` };
                    });
            }
            return [];
        } catch (e) {
            return [];
        }
    });
};
`

**Comment by JoMartinezZhu** [comment]
> 配合api 自己处理下吧 import fs from 'fs'; import { IApi } from '@umijs/max';
> 
> const PRELOAD_AND_PREFETCH_FILE_REG = /preload|prefetch/;
> 
> export default (api: IApi) => { api.addHTMLLinks(() => { try { const files = fs.readdirSync('dist/static'); if (files?.length) { return files .filter((file) => PRELOAD_AND_PREFETCH_FILE_REG.test(file)) .map((path) => { const [rel] = path.match(PRELOAD_AND_PREFETCH_FILE_REG) as RegExpMatchArray; const isVideo = /.mp4$/.test(path); return { rel, as: isVideo ? 'video' : 'image', href: `/static/${path}` }; }); } return []; } catch (e) { return []; } }); };
在 umi3 build 过程中，根本 不执行 addHTMLLinks

**Comment by JoMartinezZhu** [comment]
> > 配合api 自己处理下吧 import fs from 'fs'; import { IApi } from '@umijs/max';
> > const PRELOAD_AND_PREFETCH_FILE_REG = /preload|prefetch/;
> > export default (api: IApi) => { api.addHTMLLinks(() => { try { const files = fs.readdirSync('dist/static'); if (files?.length) { return files .filter((file) => PRELOAD_AND_PREFETCH_FILE_REG.test(file)) .map((path) => { const [rel] = path.match(PRELOAD_AND_PREFETCH_FILE_REG) as RegExpMatchArray; const isVideo = /.mp4$/.test(path); return { rel, as: isVideo ? 'video' : 'image', href: `/static/${path}` }; }); } return []; } catch (e) { return []; } }); };
> > 在 umi3 build 过程中，根本 不执行 addHTMLLinks

执行了，但是 这个时间点，dist 根本没有生成。所以fs.readdirSync('dist/static') 执行会报错
