### ISSUE TITLE
[Bug] 开启mfsu后，import通过export导出的组件报undefined

### ISSUE THREAD

**Issue by murphywuwu** [umijs/umi#7860]
## What happens?

![image](https://user-images.githubusercontent.com/12481194/154437074-cdfe042c-7faa-43e8-a5ed-a9a7ffc0602b.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

复现仓库: [umi-bug-demo1](https://github.com/one-cheese/umi-bug-demo1)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
1. yarn start，启动项目
2. 启动成功后，在浏览器访问项目，并打开控制台
3. 可看到如上报错
4. 关闭mfsu后
![image](https://user-images.githubusercontent.com/12481194/154442601-b9048b1f-cac0-4f30-9897-14b5c101f959.png)
5. 项目成功运行
![image](https://user-images.githubusercontent.com/12481194/154442686-a31ab835-66f4-4622-bd7b-f037a5bb2133.png)
6. 重新开启mfsu
![image](https://user-images.githubusercontent.com/12481194/154443042-bac80c40-97f6-4dc6-a020-27a9f217c61b.png)
7. 在mfsu开启的状态下，打开Header.tsx文件，进行如下修改
![image](https://user-images.githubusercontent.com/12481194/154443331-4bb9b0cd-fdad-4391-9422-4d6fd5e18fa5.png)
8. 项目成功运行，可解决该问题
![image](https://user-images.githubusercontent.com/12481194/154443396-2a8bacf2-7142-494d-9372-8b304f3bc03a.png)

**Expected behavior** 1. 2.
开启mfsu后，依然可以成功引用通过export导出的模块

## Context

- **Umi Version**:  3.5.20
- **Node Version**: v14.15.0
- **Platform**: mac OS

**Comment by zjfresh** [comment]
有一种可能：mfsu 开启后，启动的资源服务器会做 http 的缓存，ctrl +shift + F5 重刷看有没有用……
