### ISSUE TITLE
使用 pnpm 安装 dumi + lerna + mfsu 项目的依赖，启动会报依赖找不到

### ISSUE THREAD

**Issue by Dolov** [umijs/umi#7862]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by liuhao-hrbust** [comment]
mfsu不支持monorepo，应该就是不支持软链接，pnpm同理
