### ISSUE TITLE
umi性能

### ISSUE THREAD

**Issue by jiaozhu303** [umijs/umi#7868]
请教各位大神～
    umijs框架在第一次加载时候，load完umi.js文件后 ， 到加载其他资源或者接口前，会有一个大概800ms-1s的空闲时间，这个时间是在初始化浏览器内存吗？如何优化？ 跪谢～

**Comment by xiaorong61** [comment]
是不是用了 getInitialState？
umi 是等 getInitialState 加载好才渲染的。
