### ISSUE TITLE
umi 3.5.20 版本 unirc中 targets :{ ie: 11} ,配置以后项目出现如下问题

### ISSUE THREAD

**Issue by yyds-yes** [umijs/umi#7869]
![1645429301(1)](https://user-images.githubusercontent.com/24655215/154910014-79ccb832-b8ed-4bca-9146-f2fb3f3cd3dd.png)

**Comment by neil-lei0921** [comment]
me too
![image](https://user-images.githubusercontent.com/92282065/157813883-2f3a61a1-d440-4660-af6d-e963b3f1b864.png)
