### ISSUE TITLE
ie9下构造函数里定义的属性或方法无法被子类正确继承

### ISSUE THREAD

**Issue by linzebin** [umijs/umi#788]
```javascript
class Animal {
  species = 'Animal';
  constructor(name) {
    this.name = name;
  }
  say() {
    console.log(`My name is ${this.name}`)
  }
}
class Cat extends Animal {
  constructor(name) {
    super(name);
    this.say();
  }
}

var bigCat = new Cat('BigCat');
```
ie9下报错`对象不支持“say”属性或方法`，ie10正常。引入了`umi-plugin-polyfill`。
一开始是`bizcharts`组件报的错，后来通过尝试把问题定位到了这里，但是不知道怎么解决...

**Comment by sorrycc** [comment]
* umi-plugin-polyfill 是 0.2.0 ?
* 引入了 umi-plugin-polyfill 之后，say 属性还是不能访问到？

**Comment by linzebin** [comment]
是的，下面是相关依赖的版本
```json
    "umi": "^1.3.17",
    "umi-plugin-dll": "^0.2.1",
    "umi-plugin-dva": "^0.9.1",
    "umi-plugin-polyfill": "^0.2.0",
    "umi-plugin-routes": "^0.1.5"
```

**Comment by linzebin** [comment]
这是我写的简单的例子 https://github.com/linzebin/umi-bug-test

**Comment by linzebin** [comment]
可能是由于@babel/runtime的版本造成的，helpers/inherits.js在7.0.0-beta.46和7.0.0-rc.1间明显有差别
@babel/runtime@7.0.0-rc.1/helpers/inherits.js
```javascript
var setPrototypeOf = require("./setPrototypeOf");

function _inherits(subClass, superClass) {
  if (typeof superClass !== "function" && superClass !== null) {
    throw new TypeError("Super expression must either be null or a function");
  }

  subClass.prototype = Object.create(superClass && superClass.prototype, {
    constructor: {
      value: subClass,
      writable: true,
      configurable: true
    }
  });
  if (superClass) setPrototypeOf(subClass, superClass);
}

module.exports = _inherits;
```
@babel/runtime@7.0.0-beta.46/helpers/inherits.js
```javascript
var setPrototypeOf = require("./setPrototypeOf");

function _inherits(subClass, superClass) {
  if (typeof superClass !== "function" && superClass !== null) {
    throw new TypeError("Super expression must either be null or a function");
  }

  setPrototypeOf(subClass.prototype, superClass && superClass.prototype);
  if (superClass) setPrototypeOf(subClass, superClass);
}

module.exports = _inherits;
```

**Comment by sorrycc** [comment]
在 umi@2 下应该没有问题了，有问题再 reopen 。

**Comment by linzebin** [comment]
umi升级为2.0.0-beta.18还是不行
发现node_modules目录下依赖的@babel/runtime还是7.0.0-beta.46版本
https://github.com/linzebin/umi-bug-test

**Comment by okoala** [comment]
我用 ie9 的仿真没有发现你这个问题，你删除 node_modules 然后重新安装依赖看看~

**Comment by linzebin** [comment]
测了一下发现好像是yarn和npm的区别导致的。
执行`yarn install`后`node_modules`下`@babel/runtime`版本是`7.0.0-beta.46`
而执行`npm install`后是就对了，是`7.0.0-rc.1`。

**Comment by okoala** [comment]
npm 慢你可以使用 taobao 的源~

**Comment by lixuguang1988** [comment]
我也遇到了bizcharts组件报错的问题, [dva issue 1949](https://github.com/dvajs/dva/issues/1949)
```js
// 我注释掉可以了umi-plugin-polyfills/lib/ie9.js中的 解决的
// Object.setPrototypeOf = require('setprototypeof'); 
```
umi的版本
```bash
"umi": "^2.1.2",
"umi-plugin-react": "^1.2.2"
"umi-plugin-polyfill": "^0.2.0"
```

最开始我安装了 <code> npm install @babel/runtime@7.0.0-rc.1 --save-dev </code>,然后注释了<code>Object.setPrototypeOf</code>。后来发布不安装也可以
代码同 [issuecomment-411983508](https://github.com/umijs/umi/issues/788#issuecomment-411983508)

**Comment by lixuguang1988** [comment]
可以不更改umi-plugin-polyfills/lib/ie9.js，我原来是及配置了targets，有配置polyfills
![image](https://user-images.githubusercontent.com/3655386/48254448-0f937b00-e445-11e8-84a8-a76710f93c04.png)
![image](https://user-images.githubusercontent.com/3655386/48254470-1f12c400-e445-11e8-9209-a7529842691a.png)
