### ISSUE TITLE
[Bug] TypeError: Cannot read properties of undefined (reading 'location')

### ISSUE THREAD

**Issue by 0x3Anthony** [umijs/umi#7880]
## 现象

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/100060836/155510229-46cef43c-b697-43a9-a87f-0e52c241d55f.png">

## 仓库

复现仓库地址：https://github.com/CreatorFiNetwork/umijs-debug-app
复现路径见readme

## 补充
"umi": "^3.5.20"

**Comment by fzz14hao** [comment]
你好 这个问题解决了吗 我也遇到了，
