### ISSUE TITLE
umi3会支持 Tailwind CSS吗？

### ISSUE THREAD

**Issue by strongyc** [umijs/umi#7881]
umi3会支持 Tailwind CSS吗？

**Comment by laeni** [comment]
一直支持的，而且现在最新版已经支持postcss8版本了。

**Comment by fullee** [comment]
umi3.x集成tailwindcss

因为umi3目前的最新版还是用postcss7，但tailwindcss已经用上了postcss8导致不兼容umi3
升级umi4的代价太大就引入了postcss相关兼容依赖
参考：https://zhuanlan.zhihu.com/p/489410215
