### ISSUE TITLE
升级到最新的npm版本之后，构建失败Variable @root-entry-name is undefined

### ISSUE THREAD

**Issue by baibaibai455** [umijs/umi#7883]
<img width="951" alt="WX20220225-181227@2x" src="https://user-images.githubusercontent.com/47173675/155698334-88841e95-e48e-4f3b-81a5-e60d88c5318a.png">

"dependencies": {
        "@ant-design/charts": "^1.3.5",
        "@ant-design/icons": "^4.7.0",
        "@ant-design/pro-card": "^1.18.33",
        "@ant-design/pro-descriptions": "^1.10.46",
        "@ant-design/pro-form": "^1.55.0",
        "@ant-design/pro-layout": "^6.33.0",
        "@ant-design/pro-list": "^1.21.31",
        "@ant-design/pro-skeleton": "^1.0.5",
        "@ant-design/pro-table": "^2.64.1",
        "@umijs/route-utils": "^2.0.5",
        "antd": "^4.18.8",
        "blueimp-md5": "^2.19.0",
        "braft-editor": "^2.3.9",
        "classnames": "^2.3.1",
        "lodash": "^4.17.21",
        "moment": "^2.29.1",
        "omit.js": "^2.0.2",
        "react": "^17.0.2",
        "react-dev-inspector": "^1.7.1",
        "react-dom": "^17.0.2",
        "react-helmet-async": "^1.2.3",
        "react-sortable-hoc": "^2.0.0",
        "umi": "^3.5.21",
        "umi-plugin-keep-alive": "^0.0.1-beta.30",
        "umi-serve": "^1.9.10"
    },
    "devDependencies": {
        "@ant-design/pro-cli": "^2.1.5",
        "@types/express": "^4.17.13",
        "@types/history": "^4.7.11",
        "@types/jest": "^27.4.1",
        "@types/lodash": "^4.14.178",
        "@types/react": "^17.0.39",
        "@types/react-dom": "^17.0.11",
        "@types/react-helmet": "^6.1.5",
        "@umijs/fabric": "^2.10.2",
        "@umijs/openapi": "^1.4.0",
        "@umijs/plugin-blocks": "^2.2.2",
        "@umijs/plugin-esbuild": "^1.4.1",
        "@umijs/plugin-openapi": "^1.3.2",
        "@umijs/preset-ant-design-pro": "^1.3.3",
        "@umijs/preset-dumi": "^1.1.38",
        "@umijs/preset-react": "^2.1.1",
        "@umijs/yorkie": "^2.0.5",
        "carlo": "^0.9.46",
        "cross-env": "^7.0.3",
        "cross-port-killer": "^1.4.0",
        "detect-installer": "^1.0.2",
        "enzyme": "^3.11.0",
        "eslint": "^8.9.0",
        "express": "^4.17.3",
        "gh-pages": "^3.2.3",
        "jsdom-global": "^3.0.2",
        "lint-staged": "^12.3.4",
        "mockjs": "^1.1.0",
        "pre-commit": "^1.2.2",
        "prettier": "^2.5.1",
        "pretty-quick": "^3.1.3",
        "puppeteer-core": "^13.4.0",
        "stylelint": "^14.5.3",
        "typescript": "^4.5.5",
        "array-move": "^4.0.0"
    },

**Comment by baibaibai455** [comment]
使用"@umijs/preset-react": "^1.8.17",没有问题；  使用        "@umijs/preset-react": "^2.1.0",  就有问题了

**Comment by baibaibai455** [comment]
最终选用   "@umijs/preset-react": "^1.8.30",  没有问题

**Comment by pkaq** [comment]
一样的问题

**Comment by pkaq** [comment]
升级到最新版之后需要配置这个
```javascript
  lessLoader: {
    // golbalVars: {
    //   'root-entry-name': 'default'
    // }
    modifyVars: {
      'root-entry-name': 'default',
    },
  },
```
