### ISSUE TITLE
开启production「 MFSU 」构建报错node_modules/@umijs/plugin-locale/node_modules/warning/warning.js.

### ISSUE THREAD

**Issue by Kujo-Jotaro-AAAAA** [umijs/umi#7888]
## What happens?

开启production「 MFSU 」构建报错node_modules/@umijs/plugin-locale/node_modules/warning/warning.js.
## Mini Showcase Repository(REQUIRED)
报错信息:
`
[MFSU] Build virtual application failed since filePath not found of /Users/zhangzhichao/work/df-work/insure/front-fuman-sales/node_modules/@umijs/plugin-locale/node_modules/warning/warning.js.
`

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

[MFSU] Build virtual application failed since filePath not found of /Users/zhangzhichao/work/df-work/insure/front-fuman-sales/node_modules/@umijs/plugin-locale/node_modules/warning/warning.js.
## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by Kujo-Jotaro-AAAAA** [comment]
将config/config.ts中的local配置去掉并重新下包build仍然有这个问题

AssertionError [ERR_ASSERTION]: filePath not found of /xxx/node_modules/@umijs/plugin-locale/node_modules/warning/warning.js

找不到warning.js而报错

**Comment by lk0606** [comment]
> 将config/config.ts中的local配置去掉并重新下包build仍然有这个问题
> 
> AssertionError [ERR_ASSERTION]: filePath not found of /xxx/node_modules/@umijs/plugin-locale/node_modules/warning/warning.js
> 
> 找不到warning.js而报错

这个问题解决了吗

**Comment by yipeng2001** [comment]
[MFSU] Build virtual application failed since filePath not found of /Volumes/BOOTCAMP/workFlx/VirtualHallWebConference_Web/node_modules/@umijs/runtime.    
I meet same problem,  who can help me ?
