### ISSUE TITLE
[Bug] MFSU导致out of memory

### ISSUE THREAD

**Issue by supercutcat** [umijs/umi#7891]
## What happens?

在对项目进行修改后会固定出现CPU使用率，内存的飙升并导致out of memory。关闭MFSU后则问题不存在。

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 1. yarn dev/start 后对其内容修改

**Expected behavior** 1. 2. 内存占用不断升高并最终导致内存泄漏

## Context

- **Umi Version**: ^3.5.0
- **Node Version**: v16.13.2
- **Platform**: Manjaro 21.2.4 Qonos
- **antd pro** 5.0.0

**Comment by webPan** [comment]
删除src下的.umi

**Comment by supercutcat** [comment]
我尝试过，并没有用

**Comment by phoebeCodeSpace** [comment]
我也有此问题

**Comment by liaobin312716** [comment]
同样遇到，怎么解决的？
