### ISSUE TITLE
[Bug] TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by lingjieding** [umijs/umi#7903]
## What happens?
@umijs/babel-preset-umi>node_modules>@babel/runtime is out of date;
With umi@ ^3.4.25 which depends dva@2.6.0(which depends  react-redux V7) inside, when i extend a component which is connected by react-redux，like below:
`
// A.jsx
@connect()
export default Class A extends React.Component {
  // you stuff
}

// B.jsx
import A from 'A'
Class B extends A {
  // do some thing
}
`
then, i got Error: "TypeError: Super expression must either be null or a function",
I found the Error msg triggers by @umijs/babel-preset-umi>node_modules>@babel/runtime the inherit function which judges whether the superClass is valid; 
But the method is out of date because any code that assumes components are only functions has been wrong since React 16.6 came out, copy from [react-redux](https://github.com/reduxjs/react-redux/issues/1300#issuecomment-498721541);
 And as of react-redux V7, the connect() returns an Object copy from [react-redux](https://github.com/reduxjs/react-redux/issues/1300#issuecomment-498043137) .

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

1、create a App with umi@ ^3.4.25
2、create two Simple components like below 
`
// A.jsx
@connect()
export default Class A extends React.Component {
  render() {
    return 'A'
  }
}

// B.jsx
import A from 'A'
Class B extends A {
  render() {
    return 'B'
  }
}
`
3、then you will got the Error: 'TypeError: Super expression must either be null or a function'

## Context

- **^3.4.25**:
- **14.19.0**:
- **windows 10**:

**Comment by lvboda** [comment]
这个问题有解决方案了吗
