### ISSUE TITLE
[Bug] mfsu  有事没事热更新失效，浏览器标签会卡死

### ISSUE THREAD

**Issue by aadog** [umijs/umi#7909]
## Mini Showcase Repository(REQUIRED)
mfsu  有事没事热更新失效，浏览器标签会卡死

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

还真不好复现，有时候好又时候坏

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by w578202450** [comment]
把mfsu关了吧，mfsu一打开就会有些莫名的BUG，一关了啥问题都没有了

**Comment by webPan** [comment]
我的跟你一摸一样情况，经常卡死和热更新失效

**Comment by a97077088** [comment]
我再琢磨换icejs了，但是好像没有umijs强大，少了关键得export:"static"

**Comment by a97077088** [comment]
对，关了mfsu会好很多，但是加载速度太慢了。。

**Comment by hoho2017** [comment]
1

**Comment by 15873944157** [comment]
这个解决了吗，我也是卡死，以为是代码问题
