### ISSUE TITLE
请问怎么样在RunTimeLayoutConfig的menu加载远程数据时，动态创建路由而不是在routes.ts里固定配置？

### ISSUE THREAD

**Issue by whiteshader** [umijs/umi#7912]
请问怎么样在RunTimeLayoutConfig的menu加载远程数据时，动态创建路由而不是在routes.ts里固定配置？

**Comment by w578202450** [comment]
menu: { request: async () => loopMenuItem(menuDatas) },

**Comment by hyzx86** [comment]
> menu: { request: async () => loopMenuItem(menuDatas) },

请问这个方法哪里来的哦？
我有个相同问题。。

https://github.com/ant-design/ant-design-pro/issues/9920

**Comment by xiahller** [comment]
> 请问怎么样在RunTimeLayoutConfig的menu加载远程数据时，动态创建路由而不是在routes.ts里固定配置？

请问你解决了吗

**Comment by hyzx86** [comment]
菜单出来了。。但是路由还是404
export function patchRoutes({ routes }) {
  routes[0].routes[7].routes.push({
    name: 'amisEditor111',
    path: '/editor111',
    locale: false,
    meta: { schemaId: '40emtqq91aqe855bydkj268gx6' },
    component: dynamic({
      loader: () => import(/* webpackChunkName: 'README.md' */ './pages/develop/dynamicPage'),
      loading: LoadingComponent,
    }),
  });

  console.log(routes, 'patchRoutespatchRoutes');
  return routes;
}

**Comment by whiteshader** [comment]
官方说没法解决

**Comment by hyzx86** [comment]
但是这哥们儿说解决了呢。。
https://github.com/ant-design/ant-design-pro/issues/9468
我这里也尝试了。。但是不行
https://github.com/ant-design/ant-design-pro/issues/9920

**Comment by xXAvoraXx** [comment]
is there any solution?
