### ISSUE TITLE
umi hook地址404

### ISSUE THREAD

**Issue by fangqibin** [umijs/umi#7932]
https://hooks.umijs.org/zh-CN/hooks 这个地址直接404了，现在umi是用哪个hook，
这个跟ahook的区别是什么，不知道哪个是官方的

**Comment by jk4235** [comment]
直接用ahooks就好了吧

**Comment by fangqibin** [comment]
> 直接用ahooks就好了吧

现在项目都是用umi hook。不是在技术选型阶段
