### ISSUE TITLE
[Bug] 程序打包之后运行报错：Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by wecomgroups** [umijs/umi#7940]
## What happens?

Uncaught SyntaxError: Invalid or unexpected token

## Mini Showcase Repository(REQUIRED)
![image](https://user-images.githubusercontent.com/84605212/158381461-e41b7d12-fc4a-4cb0-8ac1-9971bd4d9416.png)

## How To Reproduce
本地运行没有问题，打包上传服务器之后出现问题

## Context

- **Umi Version**:^3.5.0
- **Node Version**:16.140
- **Platform**:b=s&&(8e-5.toFixed(3)!=="0.000"||.9.toFixed(0)!=="1"||1.255.toFixed(2)!=="1.25"||1000000000000000100.toFixed(0)!=="1000000000000000128")

**Comment by wecomgroups** [comment]
找到问题了，是moment.js的代码片段，moment.js 版本：2.29.1，目前降级到2.8尝试一下

**Comment by bingyang519** [comment]
【momnet】https://www.npmjs.com/package/momnet
【moment】https://www.npmjs.com/package/moment

这是两个包！！！！第一个包只有2.29.1  后一个才是大众用的

被这两个相似包搞了一晚上
