### ISSUE TITLE
关于umi2.x如何升级4.x

### ISSUE THREAD

**Issue by WongYuYe** [umijs/umi#7952]
## What happens?

项目目前为2.x，想问下2.x可直接升级4吗？还是必须先升到3.x

**Comment by sunjiesama** [comment]
都更新到了4x了吗，请问在哪里看到的啊

**Comment by WongYuYe** [comment]
> 都更新到了4x了吗，请问在哪里看到的啊

没有，4还在rc阶段，只是提前问一下，官方对于升级路径的考虑

**Comment by sunjiesama** [comment]
好的，谢谢> > 都更新到了4x了吗，请问在哪里看到的啊
> 
> 
> 
> 没有，4还在rc阶段，只是提前问一下，官方对于升级路径的考虑

**Comment by Loogeek** [comment]
@sunjiesama https://github.com/umijs/umi-next
