### ISSUE TITLE
乾坤插件，路由没办法匹配，子应用页面显示不出来。

### ISSUE THREAD

**Issue by lecd** [umijs/umi#7959]
路由有重定向（/monitorInfo/vehicleState），子应用加载不出来，为什么呢？

LayoutSettings配置： layout: 'mix', splitMenus: true, 
config 配置：
qiankun: {
    master: {

    }
  },
主运用的运行时动态配置子应用和路由如下：
apps: [
            {
                name: 'monitorInfo', 
                entry: '//127.0.0.1:8002', // 子运用地址和端口
            },
        ],
        routes: [
            {
                name: '动态监控',
                path: "/monitorInfo",
                routes: [
                    {
                        path: '/monitorInfo',
                        redirect: '/monitorInfo/vehicleState',
                    },
                    {
                        name: '动态监控',
                        path: '/monitorInfo/dynamicMonitor',
                        microApp: 'monitorInfo',
                    },
                    {
                        name: '车辆状态',
                        path: '/monitorInfo/vehicleState',
                        microApp: 'monitorInfo',
                    },
                    {
                        name: '传感器状态',
                        path: '/monitorInfo/sensorstate',
                        microApp: 'monitorInfo',
                    },
                ]
            },
        ],

子运用config 
  qiankun: {
    slave: {},
  },
子应用路由：
[
  {
    path: '/dynamicMonitor',
    name: '动态监控',
    component: './DynamicMonitor',
  },
  {
    path: '/vehicleState',
    name: '车辆状态',
    component: './VehicleState',
    access: 'normalRouteFilter'
  },
  {
    path: '/sensorstate',
    name: '传感器状态',
    component: './SensorState',
  },
  {
    path: '/signout',
    component: './SignOut',
  },
  {
    path: '/welcome',
    name: 'welcome',
    component: './Welcome',
  },
  {
    component: './404',
  },
];

没办法显示子应用网站页面
![image](https://user-images.githubusercontent.com/17017158/160277100-21832e75-bcae-47d8-a211-f87c8630a41f.png)

  "umi": "^3.5.0",
   "@umijs/plugin-qiankun": "^2.31.1",
    浏览器：google

**Comment by jk4235** [comment]
看起来是你没有在`app.ts`里配置apps
光配置路由是不行的

具体参考[文档](https://umijs.org/zh-CN/plugins/plugin-qiankun#a-%E6%8F%92%E4%BB%B6%E6%9E%84%E5%BB%BA%E6%9C%9F%E9%85%8D%E7%BD%AE%E5%AD%90%E5%BA%94%E7%94%A8)
