### ISSUE TITLE
部署到非根目录，例如配置了publicPath:'/trading/'，favicon 配置是拿不到trading，只会404不知应该如何解决

### ISSUE THREAD

**Issue by OnePieceLiu** [umijs/umi#7964]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by OnePieceLiu** [comment]
<img width="492" alt="截屏2022-03-28 下午5 59 32" src="https://user-images.githubusercontent.com/26754729/160374723-1313c6c8-e008-408c-a9c0-b638068d28f6.png">
如何拿到http://43.129.250.173/tarding/favicon_test.ico，而不是http://43.129.250.173/favicon_test.ico

**Comment by jk4235** [comment]
```ts
// umirc.ts

defineConfig({
...otherConfig,
favicon: '/trading/favicon_test.ico'
})

```

这样最终会在html里生成一个link
上面配置的属性会被透传至href

```html
<link rel="shortcut icon" type="image/x-icon" href="/trading/favicon_test.ico" />
```

如果需要区分dev/prod环境,自己在上面的配置时候区分下

**Comment by Lsnsh** [comment]
将 `publicPath` 定义为配置变量或环境变量，要引用 public 文件夹内静态资源的地方，使用这个变量作为链接前缀。
