### ISSUE TITLE
[Bug] .mjs解析报错

### ISSUE THREAD

**Issue by lovesL** [umijs/umi#7968]
https://github.com/ant-design/ant-design-pro/issues/9717
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

添加minio包就会报错
"minio": "^7.0.26",
## Context

- **Umi Version**:"^3.5.20",
- **Node Version**: v16.13.2
- **Platform**: mac

**Comment by sorrycc** [comment]
试了下，不能复现。
[sorrycc-zIgCxa.zip](https://github.com/umijs/umi/files/8393807/sorrycc-zIgCxa.zip)
