### ISSUE TITLE
umi-plugin-react 插件antd 按需加载css 加载不了

### ISSUE THREAD

**Issue by Nokecy** [umijs/umi#797]

**Comment by sorrycc** [comment]
加载不了是什么表现？antd 组件没有样式？

**Comment by Nokecy** [comment]
是的 antd的样式全部没有 @sorrycc

**Comment by sorrycc** [comment]
用法不对？给个例子看看。umi-plugin-react 是需要配合 umi@2 使用的。

**Comment by Nokecy** [comment]
例子 [https://github.com/Nokecy/test-umi](https://github.com/Nokecy/test-umi) ， 测试发现typescript不行 ，用js是可以的。

**Comment by Nokecy** [comment]
umirc.js 增加配置，用ts-import-plugin 处理按需加载
`    typescript: {
        getCustomTransformers: () => ({
            before: [tsImportPluginFactory({
                libraryDirectory: "es",
                libraryName: "antd",
                styel:true
            })]
        })
    },
`

**Comment by yutingzhao1991** [comment]
```diff
// tsconfig
{
    "compilerOptions": {
+        "module": "esnext",
        "experimentalDecorators": true,
        "jsx": "react",
        "baseUrl": ".",
        "paths": {
            "@/*": [
                "src/*"
            ]
        }
    }
}
```
