### ISSUE TITLE
Variable @primary-color-hover is undefined

### ISSUE THREAD

**Issue by zuoshangs** [umijs/umi#7973]
node -v
v14.19.1
 npm -v
6.14.16
 yarn -v
1.22.18

**package.json**

"dependencies": {
    "@ant-design/icons": "^4.5.0",
    "@ant-design/pro-descriptions": "^1.9.0",
    "@ant-design/pro-form": "^1.43.0",
    "@ant-design/pro-layout": "^6.26.0",
    "@ant-design/pro-table": "^2.56.0",
    "@umijs/route-utils": "^2.0.3",
    "antd": "4.16.13",
    "classnames": "^2.2.6",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.0.13",
    "rc-util": "^5.14.0",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "umi": "^3.5.0",
    "umi-serve": "^1.9.10"
  },
"devDependencies": {
    "@ant-design/pro-cli": "^2.0.2",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.2",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.144",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.6.2",
    "@umijs/openapi": "^1.3.0",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/plugin-esbuild": "^1.0.1",
    "@umijs/plugin-openapi": "^1.2.0",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-dumi": "^1.1.7",
    "@umijs/preset-react": "^1.8.17",
    "@umijs/preset-ui": "^2.2.9",
    "@umijs/yorkie": "^2.0.3",
    "carlo": "^0.9.46",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.1.1",
    "detect-installer": "^1.0.1",
    "enzyme": "^3.11.0",
    "eslint": "^7.1.0",
    "express": "^4.17.1",
    "gh-pages": "^3.0.0",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.0.1-beta3",
    "prettier": "^2.3.2",
    "puppeteer-core": "^8.0.0",
    "stylelint": "^13.0.0",
    "swagger-ui-react": "^3.52.3",
    "typescript": "^4.2.2"
  },

**先执行rimraf node_modules，再yarn没报错，然后在执行yarn dev的时候报错，控制台如下**
% yarn dev
yarn run v1.22.18
$ npm run start:dev
npm WARN lifecycle The node binary used for scripts is /var/folders/nn/lxhqrhg55d9bg3sl0cljntjm0000gp/T/yarn--1648722376874-0.8081802615361451/node but npm is using /Users/xxxxx/.nvm/versions/node/v14.19.1/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> ant-design-pro@5.0.0 start:dev /Users/xxxxxx/workspace/project-name
> cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev umi dev

Bundle with webpack 5...
⏱️  MFSU Enabled
🚀 Starting Umi UI using umi@3.5.21...
🌈 Umi UI mini Ready on port 3000.
Starting the development server...

此处忽略一些日志.......
● Webpack █████████████████████████ done (99%)  

✔ Webpack

✔ Webpack
  Compiled successfully in 15.15s

[MFSU] require('/Users/xxxxxxx/workspace/project-name/node_modules/@umijs/plugin-ui-blocks/lib/sdk/flagBabelPlugin/GUmiUIFlag.js') found in /Users/xxxxxxxxxx/workspace/project-name/src/.umi/umi.ts, which will broken the MFSU prebuild match, please change to esm module import.
[MFSU] require('/Users/xxxxxxx/workspace/project-name/node_modules/@umijs/preset-ui/lib/bubble') found in /Users/xxxxxxx/workspace/project-name/src/.umi/umi.ts, which will broken the MFSU prebuild match, please change to esm module import.

✖ MFSU
  Compiled with some errors in 39.55s

✔ Webpack
  

 DONE  Compiled successfully in 15195ms                                                                                                                                                                 18:26:46

  App running at:
  - Local:   http://localhost:8000 (copied to clipboard)
  - Network: http://192.168.0.106:8000
 ERROR  Failed to compile with 5 errors                                                                                                                                                                            18:27:27

 error  in ./node_modules/@ant-design/pro-card/es/components/Actions/index.less

Module build failed (from ./node_modules/@umijs/bundler-webpack/lib/webpack/plugins/mini-css-extract-plugin/src/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@umijs/deps/compiled/less-loader/cjs.js):

        &:hover {
          color: @primary-color-hover;
               ^
Variable @primary-color-hover is undefined
      in /Users/xxxxxxxxxx/workspace/project-name/node_modules/@ant-design/pro-card/es/components/Actions/index.less (line 34, column 17)
    at processResult (/Users/xxxxxxxxxx/workspace/project-name/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115794:19)
    at /Users/xxxxxxxxxx/workspace/project-name/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115900:5
    at /Users/xxxxxxxxxx/workspace/project-name/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:35125:11
    at /Users/xxxxxxxxxx/workspace/project-name/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34977:18
    at context.callback (/Users/xxxxxxxxxx/workspace/project/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34850:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

 error  in ./node_modules/@ant-design/pro-card/es/components/Card/index.less

Module build failed (from ./node_modules/@umijs/bundler-webpack/lib/webpack/plugins/mini-css-extract-plugin/src/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@umijs/deps/compiled/less-loader/cjs.js):

    :hover {
      color: @primary-color-hover;
           ^
Variable @primary-color-hover is undefined
      in /Users/xxxxxxxxxx/workspace/project-name/node_modules/@ant-design/pro-card/es/components/Card/index.less (line 182, column 13)
    at processResult (/Users/xxxxxxxxxx/workspace/project-name/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115794:19)
    at /Users/xxxxxxxxxx/workspace/project-name/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115900:5
    at /Users/xxxxxxxxxx/workspace/project-name/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:35125:11
    at /Users/xxxxxxxxxx/workspace/project-name/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34977:18
    at context.callback (/Users/xxxxxxxxxx/workspace/project-name/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34850:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

 error  in ./node_modules/@ant-design/pro-form/es/components/List/index.less

Module build failed (from ./node_modules/@umijs/bundler-webpack/lib/webpack/plugins/mini-css-extract-plugin/src/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@umijs/deps/compiled/less-loader/cjs.js):

    &:hover {
      color: @primary-color-hover;
           ^
Variable @primary-color-hover is undefined
      in /Users/xxxxxxxxxx/workspace/project-name/node_modules/@ant-design/pro-form/es/components/List/index.less (line 59, column 13)
    at processResult (/Users/xxxxxxxxxx/workspace/project-name/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115794:19)
    at /Users/xxxxxxxxxx/workspace/project-name/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:115900:5
    at /Users/xxxxxxxxxx/workspace/project-name/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:35125:11
    at /Users/xxxxxxxxxx/workspace/project-name/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34977:18
    at context.callback (/Users/xxxxxxxxxx/workspace/project-name/node_modules/@umijs/deps/compiled/webpack/5/bundle5.js:34850:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by ChinaDragonNB** [comment]
同样的问题，老哥知道是怎么回事吗？

**Comment by ChinaDragonNB** [comment]
> 

升级了antd 版本，就好了

**Comment by zuoshangs** [comment]
升级到哪个版本？

**Comment by ChinaDragonNB** [comment]
> 升级到哪个版本？

我是升的@ant-design/pro-form  

```bash
yarn add @ant-design/pro-form
```
