### ISSUE TITLE
[Bug] /plugin-request/request中的useRequest，参数ready从props传入只有首次生效，之后改变不再生效

### ISSUE THREAD

**Issue by ChinaGrayMan** [umijs/umi#7975]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by drawlean** [comment]
+1
plugin-request似乎一直没维护了，个人目前用ahooks作为上位替代，ready参数运行正常
