### ISSUE TITLE
[Bug] umijs 中使用@monaco-editor/react  不通过

### ISSUE THREAD

**Issue by meikang123** [umijs/umi#7982]
具体步骤如下
**### 使用场景**
![screenshot-20220403-224313](https://user-images.githubusercontent.com/16129828/161433755-7e47549d-40b1-4ac2-a72d-e91deb983faa.png)
**### 插件配置‘**
![微信图片_20220403224229](https://user-images.githubusercontent.com/16129828/161433771-bf4896cb-74a6-464d-8b3a-6542d177323c.png)
**### 报错日志**
![微信图片_20220403224246](https://user-images.githubusercontent.com/16129828/161433779-edf9a14a-b554-499e-8716-bf9b0fbf40e2.png)

**Comment by soolx** [comment]
可以参考这个https://umijs.org/zh-CN/guide/boost-compile-speed#monaco-editor-%E7%BC%96%E8%BE%91%E5%99%A8%E6%89%93%E5%8C%85

**Comment by meikang123** [comment]
> 可以参考这个https://umijs.org/zh-CN/guide/boost-compile-speed#monaco-editor-%E7%BC%96%E8%BE%91%E5%99%A8%E6%89%93%E5%8C%85
和哪个没区别

**Comment by jk4235** [comment]
看下你的tsconfig配置吧,找到出错的地方看了下是class语法,你看下是不是没有配置对class语法相关的支持

**Comment by meikang123** [comment]
> 看下你的tsconfig配置吧,找到出错的地方看了下是class语法,你看下是不是没有配置对class语法相关的支持
![screenshot-20220406-105800](https://user-images.githubusercontent.com/16129828/161887106-c5896673-82bf-43cf-a7ab-23da398b9633.png)
能说一下  具体哪里的配置吗

**Comment by meikang123** [comment]
错误仓库 https://github.com/meikang123/demoMonaco.git

**Comment by jk4235** [comment]
```ts
// umirc.ts

defineConfig: {
..otherConfig,
webpack5: {}, // enable webpack5
}
```

使用webpack5打包可以解决

**Comment by meikang123** [comment]
> ```ts
> // umirc.ts
> 
> defineConfig({
> ..otherConfig,
> webpack5: {}, // enable webpack5
> })
> ```
> 
> 使用webpack5打包可以解决

能具体点吗

**Comment by jk4235** [comment]
umirc.ts里开启[使用webpack5打包](https://umijs.org/zh-CN/config#webpack5)就行了

**Comment by wuranxu** [comment]
> 

请问你是怎么解决的呀~我也是@monaco-react，loader加载不了本地资源，都是去cdn获取，也是import 了monaco，装了webpack插件，也改了chainWebPack和webpack5

**Comment by jk4235** [comment]
@monaco-react 我之前看过,他们不支持从本地加载,因为他们就是希望不打包monaco.我之前看的时候,也有人希望他们支持从本地加载,我不知道现在他们支持了没有

如果你希望打包monaco,直接装monaco这个包就好了,然后自己封装一下

```ts
// editor.ts
import * as monaco from "monaco-editor/esm/vs/editor/editor.api";

export default monaco;

// CustomEditor.tsx

const CustomEditor : React.FC<IProps> = (props) => {
  // some logic
  useEffect(() => {
    // init editor
    editorRef.current = monaco.editor.create(containerRef.current, props.options)
   // other logic
    return () => {
      // destroy editor when unmount
      editorRef.current?.dispose();
      editorRef.current = undefined;
   }
  })
}
```

你根据自己需要定制一个就好了,或者你直接看看@monaco-react里的初始化逻辑,直接copy过来就行了

**Comment by wuranxu** [comment]
> @monaco-react 我之前看过,他们不支持从本地加载,因为他们就是希望不打包monaco.我之前看的时候,也有人希望他们支持从本地加载,我不知道现在他们支持了没有
> 
> 如果你希望打包monaco,直接装monaco这个包就好了,然后自己封装一下
> 
> ```ts
> // editor.ts
> import * as monaco from "monaco-editor/esm/vs/editor/editor.api";
> 
> export default monaco;
> 
> // CustomEditor.tsx
> 
> const CustomEditor : React.FC<IProps> = (props) => {
>   // some logic
>   useEffect(() => {
>     // init editor
>     editorRef.current = monaco.editor.create(containerRef.current, props.options)
>    // other logic
>     return () => {
>       // destroy editor when unmount
>       editorRef.current?.dispose();
>       editorRef.current = undefined;
>    }
>   })
> }
> ```
> 
> 你根据自己需要定制一个就好了,或者你直接看看@monaco-react里的初始化逻辑,直接copy过来就行了

现在支持了，我昨天问的时候是loader.config参数传的有问题，后面解决了。记录一下几个注意点:
- @monaco/react必须是4.4.0以后的版本
- 按照官网用loader加载本地的monaco配置，也就是说还需要装一个monaco的库
- umi的webpack5打开，这个应该是默认打开的，用chainWebPack配置，楼上的例子就是ok的
