### ISSUE TITLE
[Bug] theme 配置后不生效

### ISSUE THREAD

**Issue by cieldon32** [umijs/umi#7997]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

配置方式， 参考https://umijs.org/config#theme

**Comment by tankpanv** [comment]
你解决了吗，我也遇到了统一的问题，在.umirc.js 配置里加上 

  theme: {
    '@primary-color': '#1DA57A',
  },
修改颜色为绿色不生效
不生效

**Comment by ITpandaffm** [comment]
可以检查下代码里是否写了 import 'antd/dist/antd.css';

**Comment by tankpanv** [comment]
> 
没有包含 “ import 'antd/dist/antd.css'”
有代码包含 @import '~antd/es/style/themes/default.less';
但是把@import '~antd/es/style/themes/default.less'; 去掉也是没有生效

**Comment by DR-XiaoV** [comment]
尝试关闭mfsu

**Comment by tankpanv** [comment]
> > 
> 
> 没有包含 “ import 'antd/dist/antd.css'” 有代码包含 @import '~antd/es/style/themes/default.less'; 但是把@import '~antd/es/style/themes/default.less'; 去掉也是没有生效

我的问题找到了。我的问题是因为在
