### ISSUE TITLE
[Bug] wrong latest tag with v3.3.12

### ISSUE THREAD

**Issue by psybor** [umijs/umi#8001]
## What happens?
the version tag is wrong.
why the v3.3.12 was tagged the latest?
![image](https://user-images.githubusercontent.com/74579438/162554552-1a004ffa-e758-45c3-9766-5151d5dc6970.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce
no need to

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by haisapan** [comment]
+1

**Comment by ulion** [comment]
这是重大失误啊，直接导致build失败，即使设置了版本3.5.21，很多依赖库仍然会使用3.3的，简直是灾难

**Comment by psybor** [comment]
fixed, as v3.5.22 was tagged latest
