### ISSUE TITLE
[Bug] metas配置有问题

### ISSUE THREAD

**Issue by guoqirong** [umijs/umi#8002]
在.umirc.ts中配置metas，无法正常解析
  metas: [
    {
      httpEquiv: 'Content-Security-Policy',
      content: "111",
    },
  ],
错误解析成： `<meta httpequiv="Content-Security-Policy" `content="111:">`
浏览器无法识别

**Comment by s209392599** [comment]
https://umijs.org/zh-CN/config#metas

**Comment by s209392599** [comment]
https://umijs.org/zh-CN/config#metas  官方文档

**Comment by guoqirong** [comment]
正常结果应该是`<meta http-equiv="Content-Security-Policy" content="111:">`，这样浏览器才能识别

**Comment by s209392599** [comment]
`{
  httpEquiv: 'Content-Security-Policy',
  content: "111:",// upgrade-insecure-requests
}`
如果需要111:,在配置的时候需要把:也给加进去的,她只是遍历对象给添加属性，没做额外的操作

**Comment by guoqirong** [comment]
我是说httpEquiv这个变量应该解析成http-equiv，不然浏览器无法识别的，会把他当成无效配置

**Comment by s209392599** [comment]
` "http-equiv": 'Content-Security-Policy',`
你用引号包起来就可以了，不包的话就自动驼峰了

**Comment by guoqirong** [comment]
![image](https://user-images.githubusercontent.com/57247313/162575658-7eb9d36b-a790-4f00-a350-6bd4b7793b06.png)

ts校验会报类型错误的

**Comment by s209392599** [comment]
在src/pages/document.ejs模板中写入
