### ISSUE TITLE
qiankun 插件，如何在登录成功后获取路由，根据路由规则在运行时动态配置子应用呢？

### ISSUE THREAD

**Issue by lecd** [umijs/umi#8007]
在官方的运行时动态配置子应用（src/app.ts 里开启），在没登录成功后已经开始执行了，不符合我的需求，如何在登录成功后获取路由，根据路由规则在运行时动态配置子应用呢？

官方的代码 从接口中获取子应用配置，export 出的 qiankun 变量是一个 promise
export const qiankun = fetch('/config').then(({ apps }) => ({
  // 注册子应用信息
  apps,
  // 完整生命周期钩子请看 https://qiankun.umijs.org/zh/api/#registermicroapps-apps-lifecycles
  lifeCycles: {
    afterMount: (props) => {
      console.log(props);
    },
  },
  // 支持更多的其他配置，详细看这里 https://qiankun.umijs.org/zh/api/#start-opts
}));

-    "umi": "^3.5.0",
-  "qiankun": "^2.4.10",
- "@umijs/plugin-qiankun": "^2.31.1",

**Comment by starhu521** [comment]
> 

同样的问题，蹲一下有没有好的方案

**Comment by jk4235** [comment]
```ts
fetch('./config').then(({data }) => {
const appRoutes: any = data.map(({ basePath, displayName }) => ({
        path: `/prefix/${basePath}`,
        microApp: displayName,
        microAppProps: {
          autoSetLoading: true,
          wrapperClassName: "app-wrapper",
          className: "app-container",
        },
      }));
const appsConfig = {
        apps: data.map(({ displayName, staticEntry }) => ({
          name: displayName,
          entry: staticEntry,
        })),
        routes: [
          { path: "/app/login", exact: true, component: Login },
        ].concat(appRoutes),
      };
return appsConfig;
})
```

**Comment by a992681784** [comment]
有解决方案了吗？ 遇到同样的需求了

**Comment by bingjieL** [comment]
mark

**Comment by hyongzheng** [comment]
没有解决方案吗

**Comment by sailor103** [comment]
请问有解决方案了吗？

**Comment by YYL1999** [comment]
有解决方案了嘛

**Comment by 662** [comment]
qiankun 的 applyPlugins 是在 [render](https://umijs.org/docs/api/runtime-config#renderoldrender-function) 中调用的，生命周期太靠前了，好难有效发挥。
