### ISSUE TITLE
[Bug] ssr 模式，使用 splitChunks 配置的问题

### ISSUE THREAD

**Issue by robinv8** [umijs/umi#8017]
## What happens?
开启 ssr 后，使用 splitChunks 配置
```
chunks: ['vendors', 'umi'],
  chainWebpack: function (config, { webpack }) {
    config.merge({
      optimization: {
        splitChunks: {
          chunks: 'all',
          cacheGroups: {
            vendors: {
              name: 'vendors',
              test({ resource }) {
                return /[\\/]node_modules[\\/]/.test(resource);
              },
              priority: 10,
            },
          },
        },
      },
    });
  },
```
打包之后 umi.server.js 中 html 模板中出现，不存在的资源路径
<img width="1503" alt="image" src="https://user-images.githubusercontent.com/12277531/163093739-0091d6e3-e42b-433d-b651-102f6164731f.png">

## Mini Showcase Repository(REQUIRED)

仓库地址：https://github.com/robinv8/umi-ssr-bug

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.5.22
- **Node Version**: v14.19.0
- **Platform**: macos

**Comment by robinv8** [comment]
大佬关了一个还存在的 bug

**Comment by AloneMou** [comment]
我也遇到了，要怎么处理呢？
