### ISSUE TITLE
umi开启了ProLayout后，使用keepalivelayout报错

### ISSUE THREAD

**Issue by perryhong** [umijs/umi#8019]
![image](https://user-images.githubusercontent.com/39239212/163334042-10a2ac70-df10-4178-a090-b462a5b45625.png)

在app.tsx的layout的childrenrender里使用KeepAliveLayout包裹children，页面打不开，报错了

<img width="568" alt="image" src="https://user-images.githubusercontent.com/39239212/163334257-7a405f39-b863-40dd-8a3d-3a3114c7e6d9.png">

**Comment by logyxiao** [comment]
同样的错误
