### ISSUE TITLE
 export 'useAccess' (imported as 'useAccess') was not found in 'umi'

### ISSUE THREAD

**Issue by Loomark** [umijs/umi#8023]
## What happens?
报错： export 'useAccess' (imported as 'useAccess') was not found in 'umi'

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
import { useAccess } from 'umi';    // 这里报错没有导出

const AccessDemo: React.FC = () => {
  const access = useAccess();
}
**Expected behavior**  
1. 期望能够正常使用

- **Umi Version**:   "umi": "3.5.0",  "umi-serve": "^1.9.10"
- **Node Version**:14.0

**Comment by programmer-yang** [comment]
```
export default {
  access: {
    strictMode: true,
  },
}
```

**Comment by skiinaurora** [comment]
> ```
> export default {
>   access: {
>     strictMode: true,
>   },
> }
> ```

没用
