### ISSUE TITLE
[Bug] Umi4中HTML模板功能（document.ejs修改默认模板）失效

### ISSUE THREAD

**Issue by cXiaof** [umijs/umi#8024]
## What happens?

在Umi4中[HTML模板](https://umijs.org/zh-CN/docs/html-template)功能无效，Umi3中正常
这是一个BUG吗？还是Umi4不支持这个功能或这种方式了？

## How To Reproduce

根据Umi4文档创建项目`pnpx create-umi@next`，新建`src/pages/document.ejs`
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Your App</title>
  </head>
  <body>
    <div id="div1"></div>
    <div id="root"></div>
    <div id="div2"></div>
  </body>
</html>
```

**Comment by cXiaof** [comment]
在[umi-next](https://github.com/umijs/umi-next)那找到了相同问题

**Comment by huarse** [comment]
同问，这个问题还没有解决怎么就 close  掉了？

**Comment by kala888** [comment]
怎解关了？  document.ejs确实不生效了。 怎么修改favicon呢？
```
  <link rel="icon" href="<%= context.config.publicPath + 'favicon.svg'; %>" type="image/svg+xml" />
```

**Comment by fz6m** [comment]
favicon：https://umijs.org/docs/api/config#favicons

**Comment by wqpthink** [comment]
> favicon：https://umijs.org/docs/api/config#favicons

按这里的配置操作，还是不能生效

**Comment by fz6m** [comment]
```bash
# 目录结构
./public
└── assets
    └── favicon.png
```

```ts
// .umirc.ts
export default {
  favicons: [
    '/assets/favicon.png'
  ]
};
```

```html
<!-- index.html -->
<head>
  <!-- ... -->
  <link rel="shortcut icon" href="/assets/favicon.png">
  <!-- ... -->
</head>
```

**Comment by wqpthink** [comment]
确认了唯一区别是favicon.ico更换成favicon.png就可以显示了

**Comment by drizzlesconsin** [comment]
https://github.com/umijs/umi-next/issues/868
https://github.com/umijs/umi-next/issues/930
