### ISSUE TITLE
[Bug] tailwindcss在开发模式下不能实时生成样式

### ISSUE THREAD

**Issue by juetan** [umijs/umi#8029]
## What happens?

安装官方示例安装完tailwindcss后，启动开发模式，在启动前添加的类名会生成样式(图中`text-slate-500`)，在启动后添加的类名不会自动生成样式(图中`m-6`，需重新启动才有样式)。
![image](https://user-images.githubusercontent.com/36595085/163748543-6e3c151f-3546-4846-960a-17d2c649c9de.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.5.23
- **Node Version**: 14.17.5
- **Platform**: windows 10

**Comment by laeni** [comment]
开发时也不是完全不生效，一般把umi缓存(`src/.umi`)删除重启后短期内会生效，但是时间长了之后还是会出现不会生成新class的情况。我们目前的解决方案如下为开发阶段配合[Tailwind CLI](https://tailwindcss.com/docs/installation)一起使用，具体使用方式如下：

1. 新开一个命令行窗口通过`Tailwind CLI`命令启动`tailwindcss`实时编译。

   ```sh
   $ tailwindcss -i ./src/global.css -o ./public/output.css --watch
   ```

2. 创建`umi`配置配置`.umirc.local.ts` 或 `config/config.local.ts`，已经存在时可以忽略。

3. 在配置文件中添加如下内容将`tailwindcss`实时编译生成的`css`通过原始方式引入应用。

   ```typescript
   import { defineConfig } from 'umi';
   
   export default defineConfig({
       links: [
           // 这一行时核心，表示引入 /public/output.css 样式文件
           { rel: 'stylesheet', type: 'text/css', href: '/output.css' },
       ],
   });
   ```

4. 重新启动应用即可。

> 这样做实际上会将`tailwindcss`生成的CSS文件引入两次，因为已经通过`PostCSS`插件集成了，但也没关系，因为这仅仅在开发时候生效，构建时不会包含`.umirc.local.ts` 或 `config/config.local.ts`的配置，并且`.local`配置文件会被git忽略掉，从而防止影响他人的配置，详情参见[umi官网](https://umijs.org/zh-CN/docs/config#%E6%9C%AC%E5%9C%B0%E4%B8%B4%E6%97%B6%E9%85%8D%E7%BD%AE)。
>
> 之所以不开发和构建都直接使用`Tailwind CLI`方式是因为这样做会存在问题，那就是当发布新版本的时候由于浏览器缓存原因可能导致用户浏览器没有重新加载新版css文件而导致问题，因为我们输出生成的文件名永远不会变(`output.css`)，这也是为什么现代web应用构建后静态文件名通常带有一串`hash`值的原因。
>
> 此外，这种方式也会存在不一定会即时生效的问题，原因是我们是通过最原始的方式将CSS通过链接引进来的，所以运行过程中浏览器并不知道该文件已经修改并重新加载该文件，所以遇到此类情况是正常的，只需要刷新一下页面即可。但是相比第一种要删除缓存并重启应用来说已经好很多了。

**Comment by juetan** [comment]
感谢回答，不过这个方法我没试过，我找到了另一个解决的办法([链接](https://zhuanlan.zhihu.com/p/489410215))，因为umi使用`postcss7`，而目前3.x的tailwind使用`postcss8`，我暂时回退到了使用2.x的`@tailwindcss/postcss7-compat`，使用起来是没问题的。等后面官方升级到`postcss8`，我后面再迁移回来。

**Comment by laeni** [comment]
目前umi最新版已经是`postcss8`了呢。

**Comment by 775146061** [comment]
> 目前umi最新版已经是`postcss8`了呢。

瞎说，现在3.5.26还是使用的postcss7

**Comment by weypro** [comment]
umi4时代也有这个情况

**Comment by lbyupup** [comment]
> umi4时代也有这个情况

请问这个如何解决呢，我也是开发的时候global.less文件不生效，只有更改到该文件才会生效，打包后发布也是不生效

**Comment by jiuyuanxp** [comment]
现在有其他解决方案了么 部分代码可以更新部分代码无法热更新  umi^4.0.63  tailwindcss^3

**Comment by fz6m** [comment]
如遇不能更新的问题，需要给一个最小复现。
