### ISSUE TITLE
如何在代码中访问到环境变量  UMI_ENV？

### ISSUE THREAD

**Issue by iceberg211** [umijs/umi#803]
例如我想在代码中区分生产环境和开发环境，写在pagajson里面可以配置UMI_ENV，但是我如何访问到这个环境变量？

**Comment by sorrycc** [comment]
可以在 .umirc.js 里配相关的 define 。

**Comment by dongze1213** [comment]
> 可以在 .umirc.js 里配相关的 define 。

问题是怎么在代码访问配的变量？而不是怎么配

**Comment by afc163** [comment]
https://www.google.com/search?newwindow=1&client=firefox-b-d&ei=MTaCXMiXK6HD0PEP6YmIkAc&q=how+to+read+environment+variables+in+node&oq=how+to+read+environment+variables+in+node&gs_l=psy-ab.3..35i39.8049.12692..13035...3.0..0.242.242.2-1......0....1j2..gws-wiz.....6.KvTVH9_JZks
