### ISSUE TITLE
[Bug] 开启mfsu, fastRefresh时，IE11兼容性有解决方案吗？

### ISSUE THREAD

**Issue by quicklearning123** [umijs/umi#8036]
## What happens?

升级3.5.23后，发现IE11上启动会报错

其他人issue也有 #7140 

![image](https://user-images.githubusercontent.com/70048681/164498425-78d5e48f-d048-4e26-b73a-4bd57ffb93b4.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by flyuuo9** [comment]
webpack 官方文档： https://webpack.js.org/migrate/5/#need-to-support-an-older-browser-like-ie-11
但umijs封装成什么不清楚了

**Comment by quicklearning123** [comment]
![image](https://user-images.githubusercontent.com/70048681/164712682-2f99fb4e-03ba-47e7-b0a3-01d23c4f8202.png)
