### ISSUE TITLE
国际化是否能提供代码提示功能

### ISSUE THREAD

**Issue by wenlei0617** [umijs/umi#8037]
Background
在使用umi-locale是，经常因为 记不住ID或则id输入错误，是否考虑新增对 Id的提示功能

Proposal
当本地locales修改的时候，自动生成一个 interface localNames {
"menu.user":string;
"menu.role":string;
...
}
对formatMessage的 ID参数进行验证和提示 比如
export interface MessageDescriptor {
id: keyof localNames ;
description?: string;
defaultMessage?: string;
}

这样在使用本地化时，Id值会自动有提示，可以大大提高开发效率

**Comment by leftstick** [comment]
我之前做过一个工具https://github.com/umijs/umi-locale-doctor，当时的想法是这个东西提供检查服务，然后允许ide的插件，例如：vscode的extension，通过调用我这个sdk来检查字典错误引用和无效定义。
其实也可以拿来生成你说的这个interface。
之所以还单独搞了个repo来实现，是因为多语言文件不是简单地配置文件，扫描一下就好了，他们是代码，里面可能包含了其他模块引用，spread 操作符，函数执行结果等等一系列不那么静态的内容。
所以我想你提的这个问题，或许在umi@4里有更好的思考，让我们拭目以待

**Comment by laoxubuer** [comment]
仅供参考
```typescript
import type Locales from '@/locales/zh-CN';

/**
 * 翻译Key
 */
export type Keys = keyof typeof Locales;

/**
 * 包装后的hook
 */
export default function useFormatMessage() {
  const { formatMessage } = useIntl();
  type FormatMessageParameters = Parameters<typeof formatMessage>;
  type ValuesType = FormatMessageParameters[1];
  const formatMsg = useMemoizedFn(
    (descriptor: Omit<FormatMessageParameters[0], 'id'> & { id: Keys }, values?: ValuesType) => {
      return formatMessage(descriptor, values) as string;
    },
  );
  return {
    formatMessage: formatMsg,
  };
}

```

**Comment by wenlei0617** [comment]
> 仅供参考
> 
> ```ts
> import type Locales from '@/locales/zh-CN';
> 
> /**
>  * 翻译Key
>  */
> export type Keys = keyof typeof Locales;
> 
> /**
>  * 包装后的hook
>  */
> export default function useFormatMessage() {
>   const { formatMessage } = useIntl();
>   type FormatMessageParameters = Parameters<typeof formatMessage>;
>   type ValuesType = FormatMessageParameters[1];
>   const formatMsg = useMemoizedFn(
>     (descriptor: Omit<FormatMessageParameters[0], 'id'> & { id: Keys }, values?: ValuesType) => {
>       return formatMessage(descriptor, values) as string;
>     },
>   );
>   return {
>     formatMessage: formatMsg,
>   };
> }
> ```

现在我们的方式基本基于此来解决，但是其实并没有完全解决痛点：
我们的痛点：
1、校验key的正确性
2、期望能更直观的观察到key对应的value，现在通过defaultMessage来做，有时候会出现大家忘写和忘记更新。如果没有中文，对于其他维护者来说维护不友好，需要反复在key中去切换。

针对上面的问题，我们现在是想通过vscode插件来解决这个问题，类型kiwi的解决方案

**Comment by laoxubuer** [comment]
> > 仅供参考
> > ```ts
> > import type Locales from '@/locales/zh-CN';
> > 
> > /**
> >  * 翻译Key
> >  */
> > export type Keys = keyof typeof Locales;
> > 
> > /**
> >  * 包装后的hook
> >  */
> > export default function useFormatMessage() {
> >   const { formatMessage } = useIntl();
> >   type FormatMessageParameters = Parameters<typeof formatMessage>;
> >   type ValuesType = FormatMessageParameters[1];
> >   const formatMsg = useMemoizedFn(
> >     (descriptor: Omit<FormatMessageParameters[0], 'id'> & { id: Keys }, values?: ValuesType) => {
> >       return formatMessage(descriptor, values) as string;
> >     },
> >   );
> >   return {
> >     formatMessage: formatMsg,
> >   };
> > }
> > ```
> 
> 现在我们的方式基本基于此来解决，但是其实并没有完全解决痛点： 我们的痛点： 1、校验key的正确性 2、期望能更直观的观察到key对应的value，现在通过defaultMessage来做，有时候会出现大家忘写和忘记更新。如果没有中文，对于其他维护者来说维护不友好，需要反复在key中去切换。
> 
> 针对上面的问题，我们现在是想通过vscode插件来解决这个问题，类型kiwi的解决方案

在 WebStorm 里，是可以显示具体的 value 对应的内容的
