### ISSUE TITLE
[Bug] Invalid config key: access

### ISSUE THREAD

**Issue by Lsnsh** [umijs/umi#8043]
## What happens?

![image](https://user-images.githubusercontent.com/26019513/164454771-e1029c18-931e-4a30-a96f-f13bd4131b7c.png)

在 `config/config.ts` 中添加 access 属性，想开启严格模式（strictMode）时报错。

参考文档：https://umijs.org/zh-CN/plugins/plugin-access#strictmode

---

文档没有说明具体应该在哪里配置，从以前的 issue https://github.com/umijs/umi/issues/6738 中才得知应该配置在 config 文件中。

## Mini Showcase Repository(REQUIRED)

**config/config.ts**

```diff
export default defineConfig({
+  access: {
+    strictMode: true,
+  },
});
```

## How To Reproduce

1. 修改 `config/config.ts`，添加上述配置
2. `npm run dev`

**报错日志：**

```bash
➜  projectName git:(feat/***) ✗ npm run dev

> ant-design-pro@5.2.0 dev
> npm run start:dev


> ant-design-pro@5.2.0 start:dev
> cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev umi dev

Bundle with webpack 5...
⏱️  MFSU Enabled
Invalid config key: access
Error: Invalid config key: access
    at Config.getConfig (/Users/projectName/node_modules/@umijs/core/lib/Config/Config.js:183:13)
    at /Users/projectName/node_modules/@umijs/core/lib/Service/Service.js:293:44
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/projectName/node_modules/@umijs/core/lib/Service/Service.js:110:103)
    at _next (/Users/projectName/node_modules/@umijs/core/lib/Service/Service.js:112:194)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Context

- **Umi Version**: v3.5.2
- **Node Version**: v16.14.2
- **Platform**: macOS v12.3

**Comment by Lsnsh** [comment]
## 临时解决方案

我目前的临时解决方案，是升级 `@umijs/preset-react` 到 `v2.1.0` 以上，后面会说原因 ：

**package.json**

```diff
{
  "dependencies": {
-    "@umijs/preset-react": "^1.8.17",
+    "@umijs/preset-react": "^2.1.0",
  }
}
```

config/config.ts

```diff
export default defineConfig({
+  access: {
+    strictMode: true,
+  },
});
```

- npm i
- npm run dev

---

## 原因

项目使用 `ant-design-pro@5.2.0` 搭建。

因为发现 `package.json` 中并没有直接安装 `@umijs/plugin-access`，于是使用 [npm ls](https://docs.npmjs.com/cli/v8/commands/npm-ls) 查看 `@umijs/plugin-access` 在项目依赖中所处的位置：

- npm ls @umijs/plugin-access

```bash
➜  projectName git:(feat/***) ✗ npm ls @umijs/plugin-access
ant-design-pro@5.2.0 /Users/projectPath
└─┬ @umijs/preset-react@1.8.31
  └── @umijs/plugin-access@2.4.3
```

找到在 `@umijs/preset-react` 这个包中，作为依赖存在。加上之前在浏览相关的 issue https://github.com/umijs/umi/issues/6738 的时候，看到过有一个跟升级 `@umijs/preset-react` 相关的回复，当时没在意：

> > > 更新包之后，使用 { access:{ strictMode:true }} 解决
> > 
> > 请问更新到那个版本？我更新umi到3.5.20都还是提示 `Invalid config key: access`
> 
> 将 @umijs/preset-react 升级至 >= 2.1.0版本
> 
> _Originally posted by @JbfGod in https://github.com/umijs/umi/issues/6738#issuecomment-1090152404_

于是看了一下 `@umijs/preset-react` 的 CHANGELOG，到 `v2.1.0` 才正式支持严格模式：

> ## [2.1.0](https://github.com/umijs/plugins/compare/@umijs/preset-react@1.8.30...@umijs/preset-react@2.1.0) (2021-12-14)
> ### Features
> - access add Strict Mode (https://github.com/umijs/plugins/issues/636) ([0a4954f](https://github.com/umijs/plugins/commit/0a4954f86c09d39735b30cc303889ee1a67020b2))
> - remove mobile from plugin-antd & update preset-react (https://github.com/umijs/plugins/issues/760) ([1a312a4](https://github.com/umijs/plugins/commit/1a312a4ef8dcbc7b9853a276761d7b2a0cfb6e3b))
> 
> 参考 [preset-react/CHANGELOG.md](https://github.com/umijs/plugins/blob/master/packages/preset-react/CHANGELOG.md#210-2021-12-14)

**Comment by Lsnsh** [comment]
想去模板仓库提 issue，试了一下发现最新使用 `npm create umi` 基于 simple 模板创建的项目

- ant-design-pro
- TypeScript
- simple

![image](https://user-images.githubusercontent.com/26019513/165254037-84013ffd-5a30-4b19-a7dc-4c782874caea.png)

package.json 中 `@umijs/preset-react` 已经更新到 `^2.1.0` 了。

**Comment by JbfGod** [comment]
看到楼主特意新开了个帖子仔细的描述这个问题，对于我之前那轻飘飘的回答，着实感觉不好意思，所谓授人以鱼不如授人以渔。这里我将解决该问题的过程再次复述如下：
 
 根据官网文档描述配置的 **{ access:{ strictMode:true }}** 。TM居然也能出bug，没办法只能无奈的拿出DEBUG神器通过调试找出问题(╮(╯▽╰)╭) 

![1](https://user-images.githubusercontent.com/42824782/165295329-a4af9827-9bc0-404f-9ab9-2990e652f10a.png)

下面介绍一下如何断点调试，这里使用的是IDEA(大多数开发工具都有DEBUG功能，其他工具参考配置原理大同小异) 。前端开发大多通过终端在项目路径下通过 `yarn start` 启动项目，这样不能断点调试代码。yarn实际是依托node环境运行的，所以咱们新建node application，IDEA中配置启动项如下：
![2](https://user-images.githubusercontent.com/42824782/165295370-9a24153f-c83a-4dac-b950-248eb5304871.png)

找到输出错误信息的代码位置 /node_modules/@umijs/core/lib/Config/Config.js:183:13

下方是出现“Invalid config key: access”的部分代码片段，阅读以下代码片段可知 userConfigKeys.length > 0 导致了该异常的输出。

```JavaScript
①用户在config中配置的插件
const userConfigKeys = Object.keys(userConfig).filter(key => {
  return userConfig[key] !== false;
}); // get config
const pluginIds = Object.keys(this.service.plugins);
②下方代码是对用户启用的umi插件配置进行校验
pluginIds.forEach(pluginId => {
  const _this$service$plugins3 = this.service.plugins[pluginId],
        key = _this$service$plugins3.key,
        _this$service$plugins4 = _this$service$plugins3.config,
        config = _this$service$plugins4 === void 0 ? {} : _this$service$plugins4; // recognize as key if have schema config
  
  if (!config.schema) return;
  ... 省略部分代码
  const index = userConfigKeys.indexOf(key.split('.')[0]);
  ③通过以上代码的层层校验，校验通过的插件会从userConfigKeys中移除
  if (index !== -1) { 
    userConfigKeys.splice(index, 1);
  } // update userConfig with defaultConfig
   
  ... 省略部分代码
});
④最终未通过校验的插件配置会打印错误信息： Invalid config ${key} 出现的地方。
if (userConfigKeys.length) {
  const keys = userConfigKeys.length > 1 ? 'keys' : 'key';
  throw new Error(`Invalid config ${keys}: ${userConfigKeys.join(', ')}`);
}
```

![3](https://user-images.githubusercontent.com/42824782/165296512-cfdb3349-0d89-4de1-b187-490851aa7ada.png)

通过设置断点，我们可以看到当遍历到 plugin-access时，`config.schema` 是 undefined，导致代码运行到这return出去，没办法执行到 `userConfigKeys.splice(index, 1)` 。接下来就是找出 `config.schema` is undefined的源头。

![4](https://user-images.githubusercontent.com/42824782/165295616-483af837-44db-4fe5-8f86-516f23523967.png)

通过观察 `this.service.plugins` 推测plugin的config来源的代码，这里我圈出access以及其他2个我在config.js 中启用配置的插件 `layout` 和 `openapi` 进行对比。

@umijs/plugin-access/lib/index.js、@umijs/plugin-layou/lib/index.js、@umijs/plugin-openapi/lib/index.js。

这里不得佩服，大佬们写的代码----"源代码即文档"。 通过 `api.describe ` 推测是对插件支持配置的描述。 

我在access-plugin/../index.js中全文搜索了 `describe` 关键字，并没有发现有地方使用到，而其他两个能够正常使用的插件都有调用 `api.describe` 且其中都有对于 `config.schema` 的配置。

![5](https://user-images.githubusercontent.com/42824782/165295657-0a8c52f4-c4ae-4b78-af3b-502985aad1d4.png)

到这里首先想到得是通过修改源码解决问题，但是想想，我这项目是最**新稳定版本构建的**，这种问题出现应该不止我一个人，于是去社区issue搜了下，找到了个有趣的评论，有点想哭，大哥，我已经最新版了啊！！！

![image](https://user-images.githubusercontent.com/42824782/165295751-2ac3b634-cea5-469a-a302-ac3de784ca9c.png)

不过也是这个评论给我带来了灵感，**会不会是 plugin-access 版本跟不上？**

于是在yarn.lock文件中全文搜索了下plugin-access。发现plugin-access的版本是被

`@umijs/preset-react@^1.8.17` 带进来的，于是尝试升级了下 `@umijs/preset-react` 。

![7](https://user-images.githubusercontent.com/42824782/165295693-6d4e88ee-aaa3-4ec6-8ef1-239d7dab281c.png)

**升级后**

![8](https://user-images.githubusercontent.com/42824782/165295713-4405a9fb-dd2b-4f77-8af7-ef18f47d881a.png)

再次查看`@umijs/plugin-access/lib/index.js` 幸运的是出现了想要的结果，启动后也不再报错。经过测试`@umijs/preset-react 升级至 >= 2.1.0版本` 不会出现问题。

![9](https://user-images.githubusercontent.com/42824782/165295729-e9f3e50a-d063-483e-bf1f-03cc004ba2c5.png)

**Comment by Lsnsh** [comment]
@JbfGod  从代码调试入手的排查思路不错，学习了。

---

我当时在摸索 ant-design-pro 里的这个权限控制插件，遇到报错的时候，看了一些 issue 都没有很明确的处理方案，看相关的 issue 都已经 closed 了，所以就新提了一个 issue ，暂且先搁置看有没有官方的答复。

过了一阵子，真想用这个严格模式的时候，只能在网上从头查起，相关的方案挨个的试才得以解决，寻找方案的过程中，发现这个“问题——严格模式应该配置在哪 & 严格模式配置后报错”由来已久，并且没有较为详尽或者官方的解决方案，于是回来自问自答，好留下些痕迹，以供遇到同样问题的人们借鉴。

**Comment by kanasite** [comment]
我不小心在 config/config.ts 里加了
context: {} 

也引发了这错误

**Comment by code-lives** [comment]
umi build 报错Invalid config keys
使用 yarn build 成功
是否有规范检测？

**Comment by wangmeijian** [comment]
> 看到楼主特意新开了个帖子仔细的描述这个问题，对于我之前那轻飘飘的回答，着实感觉不好意思，所谓授人以鱼不如授人以渔。这里我将解决该问题的过程再次复述如下：
> 
> 根据官网文档描述配置的 **{ access:{ strictMode:true }}** 。TM居然也能出bug，没办法只能无奈的拿出DEBUG神器通过调试找出问题(╮(╯▽╰)╭)
> 
> ![1](https://user-images.githubusercontent.com/42824782/165295329-a4af9827-9bc0-404f-9ab9-2990e652f10a.png)
> 
> 下面介绍一下如何断点调试，这里使用的是IDEA(大多数开发工具都有DEBUG功能，其他工具参考配置原理大同小异) 。前端开发大多通过终端在项目路径下通过 `yarn start` 启动项目，这样不能断点调试代码。yarn实际是依托node环境运行的，所以咱们新建node application，IDEA中配置启动项如下： ![2](https://user-images.githubusercontent.com/42824782/165295370-9a24153f-c83a-4dac-b950-248eb5304871.png)
> 
> 找到输出错误信息的代码位置 /node_modules/@umijs/core/lib/Config/Config.js:183:13
> 
> 下方是出现“Invalid config key: access”的部分代码片段，阅读以下代码片段可知 userConfigKeys.length > 0 导致了该异常的输出。
> 
> ```js
> ①用户在config中配置的插件
> const userConfigKeys = Object.keys(userConfig).filter(key => {
>   return userConfig[key] !== false;
> }); // get config
> const pluginIds = Object.keys(this.service.plugins);
> ②下方代码是对用户启用的umi插件配置进行校验
> pluginIds.forEach(pluginId => {
>   const _this$service$plugins3 = this.service.plugins[pluginId],
>         key = _this$service$plugins3.key,
>         _this$service$plugins4 = _this$service$plugins3.config,
>         config = _this$service$plugins4 === void 0 ? {} : _this$service$plugins4; // recognize as key if have schema config
>   
>   if (!config.schema) return;
>   ... 省略部分代码
>   const index = userConfigKeys.indexOf(key.split('.')[0]);
>   ③通过以上代码的层层校验，校验通过的插件会从userConfigKeys中移除
>   if (index !== -1) { 
>     userConfigKeys.splice(index, 1);
>   } // update userConfig with defaultConfig
>    
>   ... 省略部分代码
> });
> ④最终未通过校验的插件配置会打印错误信息： Invalid config ${key} 出现的地方。
> if (userConfigKeys.length) {
>   const keys = userConfigKeys.length > 1 ? 'keys' : 'key';
>   throw new Error(`Invalid config ${keys}: ${userConfigKeys.join(', ')}`);
> }
> ```
> 
> ![3](https://user-images.githubusercontent.com/42824782/165296512-cfdb3349-0d89-4de1-b187-490851aa7ada.png)
> 
> 通过设置断点，我们可以看到当遍历到 plugin-access时，`config.schema` 是 undefined，导致代码运行到这return出去，没办法执行到 `userConfigKeys.splice(index, 1)` 。接下来就是找出 `config.schema` is undefined的源头。
> 
> ![4](https://user-images.githubusercontent.com/42824782/165295616-483af837-44db-4fe5-8f86-516f23523967.png)
> 
> 通过观察 `this.service.plugins` 推测plugin的config来源的代码，这里我圈出access以及其他2个我在config.js 中启用配置的插件 `layout` 和 `openapi` 进行对比。
> 
> @umijs/plugin-access/lib/index.js、@umijs/plugin-layou/lib/index.js、@umijs/plugin-openapi/lib/index.js。
> 
> 这里不得佩服，大佬们写的代码----"源代码即文档"。 通过 `api.describe ` 推测是对插件支持配置的描述。
> 
> 我在access-plugin/../index.js中全文搜索了 `describe` 关键字，并没有发现有地方使用到，而其他两个能够正常使用的插件都有调用 `api.describe` 且其中都有对于 `config.schema` 的配置。
> 
> ![5](https://user-images.githubusercontent.com/42824782/165295657-0a8c52f4-c4ae-4b78-af3b-502985aad1d4.png)
> 
> 到这里首先想到得是通过修改源码解决问题，但是想想，我这项目是最**新稳定版本构建的**，这种问题出现应该不止我一个人，于是去社区issue搜了下，找到了个有趣的评论，有点想哭，大哥，我已经最新版了啊！！！
> 
> ![image](https://user-images.githubusercontent.com/42824782/165295751-2ac3b634-cea5-469a-a302-ac3de784ca9c.png)
> 
> 不过也是这个评论给我带来了灵感，**会不会是 plugin-access 版本跟不上？**
> 
> 于是在yarn.lock文件中全文搜索了下plugin-access。发现plugin-access的版本是被
> 
> `@umijs/preset-react@^1.8.17` 带进来的，于是尝试升级了下 `@umijs/preset-react` 。
> 
> ![7](https://user-images.githubusercontent.com/42824782/165295693-6d4e88ee-aaa3-4ec6-8ef1-239d7dab281c.png)
> 
> **升级后**
> 
> ![8](https://user-images.githubusercontent.com/42824782/165295713-4405a9fb-dd2b-4f77-8af7-ef18f47d881a.png)
> 
> 再次查看`@umijs/plugin-access/lib/index.js` 幸运的是出现了想要的结果，启动后也不再报错。经过测试`@umijs/preset-react 升级至 >= 2.1.0版本` 不会出现问题。
> 
> ![9](https://user-images.githubusercontent.com/42824782/165295729-e9f3e50a-d063-483e-bf1f-03cc004ba2c5.png)

感谢，@umijs/preset-react 升级至 >= 2.1.0可用，但升级到2.1.3又会出问题

**Comment by wangmeijian** [comment]
感谢 @JbfGod ，@umijs/preset-react 2.1.0版本可用，如果再升级到2.1.3又有其他问题，国际化不生效
