### ISSUE TITLE
[Bug] pro-layout 路由子菜单设置access无效

### ISSUE THREAD

**Issue by MS-hl** [umijs/umi#8047]
## BUG描述

pro-layout 的route 子路由设置的access在菜单显示中无效.
 {
    path: `/`,
    component: '@/layouts',
    access: 'event',
    routes: [
      // 当前登录用户账号信息
      {
        path: `/settings`,
        component: '@/pages/settings/index',
        access: 'eventSettings',
      },
}
'/settings'菜单的权限无效；

## 版本信息
"@ant-design/pro-layout": "^6.31.7",

umi 版本 "umi": "^3.5.23",
浏览器环境 版本 100.0.4896.127（正式版本）
开发环境 [mac OS]

**Comment by zcSkr** [comment]
同问，但应该不是"^6.31.7"的问题。具体是umi版本问题还是pro-layout版本问题没有尝试出来

**Comment by MS-hl** [comment]
邮件已收到，谢谢

**Comment by johnwayen** [comment]
如何解决的啊 @MS-hl

**Comment by zcSkr** [comment]
> 

今天更新的@umijs/preset-react  2.1.3。同时config里面配置access:{} 打开。就可以了

**Comment by YH-82** [comment]
> > 
> 
> 今天更新的@umijs/preset-react 2.1.3。同时config里面配置access:{} 打开。就可以了
加上access:{}之后，报错Invalid config key: access，这个是怎么回事。。

**Comment by YH-82** [comment]
> > 
> 
> 今天更新的@umijs/preset-react 2.1.3。同时config里面配置access:{} 打开。就可以了

加上access:{}之后，报错Invalid config key: access，这个是怎么回事。。

**Comment by MS-hl** [comment]
邮件已收到，谢谢
