### ISSUE TITLE
[Bug] openapi生成的mock代码里没有实际的数据

### ISSUE THREAD

**Issue by quicklearning123** [umijs/umi#8053]
## What happens?
@umijs/openapi 1.4.3
"@umijs/plugin-openapi" 1.3.2
```
res.status(200).send({});
```
在swagger-ui.html中是可以看到字段成员的

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.5.23
- **Node Version**:
- **Platform**:

**Comment by weilun0510** [comment]
一样的问题，请问解决了吗
