### ISSUE TITLE
Menu警告使用item替换children

### ISSUE THREAD

**Issue by Es-Rell** [umijs/umi#8054]
Menu警告使用item替换children

**Comment by Es-Rell** [comment]
umi v3.5运行项目，antd警告Menu children将废弃，使用item替换。
components 内的 header组件已替换，猜测是umi封装的layout菜单还未修改。

**Comment by zcSkr** [comment]
看看文档吧https://ant.design/components/menu-cn/#header

**Comment by Es-Rell** [comment]
> 看看文档吧https://ant.design/components/menu-cn/#header

我知道antd4.2.0准备废弃Menu children，项目中也改成了item，但是依旧报警告，所以想问是不是umi内置的layout菜单还使用的children？

**Comment by zcSkr** [comment]
> > 看看文档吧https://ant.design/components/menu-cn/#header
> 
> 我知道antd4.2.0准备废弃Menu children，项目中也改成了item，但是依旧报警告，所以想问是不是umi内置的layout菜单还使用的children？

有可能是layout用了老写法，有可能是警告会在4.20.0+一直提示，等我去读一下prolayout源码

**Comment by zcSkr** [comment]
<img width="883" alt="image" src="https://user-images.githubusercontent.com/30515821/165450503-bbaca483-3e04-425d-bb27-1f1aecd2b1e8.png">
<img width="933" alt="image" src="https://user-images.githubusercontent.com/30515821/165450555-a0728668-f8ac-4c83-8a0f-a8be9cc50209.png">
确实是pro-layout在使用了Menu.Item的用法

**Comment by Es-Rell** [comment]
> <img width="883" alt="image" src="https://user-images.githubusercontent.com/30515821/165450503-bbaca483-3e04-425d-bb27-1f1aecd2b1e8.png">
> 
> <img width="933" alt="image" src="https://user-images.githubusercontent.com/30515821/165450555-a0728668-f8ac-4c83-8a0f-a8be9cc50209.png">
> 
> 确实是pro-layout在使用了Menu.Item的用法

是的 我也看了 umi是基于pro的二次封装，目前只有等pro更新或者降级4.19.0
