### ISSUE TITLE
[Bug] umi转发EventSource接口时没立即返回数据

### ISSUE THREAD

**Issue by luzhiy123** [umijs/umi#8055]
## What happens?

通过umi创建的项目，使用EventSource时，在本地不能立即立即获取到数据，总是在断开时才获取到，怀疑是umijs/server中没对EventSource做处理

## How To Reproduce

通过umi创建任意一个简单库，配置转发到一个有效地址，连接一个经过转发的EventSource

## Context

- **Umi Version**: 3.5.20.
- **Node Version**: v12.16.2
- **Platform**: win7，umijs/server@3.5.23 转发问题

**Comment by dalongjason** [comment]
有捷径吗，如何解决的

**Comment by luzhiy123** [comment]
> 有捷径吗，如何解决的

到现在都还是一样，找的其他方式，再起个服务，把接口用那个服务代理，其他的转到这个服务

**Comment by luzhiy123** [comment]
> 有捷径吗，如何解决的

https://github.com/umijs/umi/issues/12144
