### ISSUE TITLE
qiankun插件每次加载子应用页面都会重新加载页面（基座采用的是antd pro v5并采用tabs菜单。现在每次切换tab菜单都会重新加载接口），这个问题直接导致tabs切换没有意义了

### ISSUE THREAD

**Issue by zhoubaibai** [umijs/umi#8060]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by RainManGO** [comment]
解决了吗
