### ISSUE TITLE
在scr/app.ts中使用useModel报错

### ISSUE THREAD

**Issue by WuBin88996** [umijs/umi#8061]
umi.77e701e2.js:1 Uncaught Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

![image](https://user-images.githubusercontent.com/32702573/165900689-92f9b59d-16d7-4ffc-843c-89dfedee6ed9.png)

**Comment by geekact** [comment]
推荐使用[foca](https://github.com/foca-js/foca)，天然支持TS，自带useModel
