### ISSUE TITLE
[Bug] 编译不通过   Can't import the named export 'xxx' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by Deja-vuuu** [umijs/umi#8062]
安装 popmotion 这个库  
```
pnpm i popmotion
```
```
import { animate } from 'popmotion';
useEffect(() => {
    animate({
      from: 0,
      to: 100,
      onUpdate: (latest) => console.log(latest),
    });
  }, []);
```

报错信息
![image](https://user-images.githubusercontent.com/27748682/165986306-04e2a61b-3417-4648-95d5-57ec53e999d9.png)

我可以通过配置webpack编译解决吗？我搜到了类似的问题 https://stackoverflow.com/questions/69343038/cant-import-the-named-export-xxxx-from-non-ecmascript-module-only-default-expo
但是我尝试配置之后还是不行

**Comment by luffyZh** [comment]
相同问题，同问

**Comment by luffyZh** [comment]
@Deja-vuuu  已解决，`config.js` 配置如下代码：

```js
chainWebpack(conf) {
    // ....other config
    conf.module
      .rule('mjs$')
      .test(/\.mjs$/)
      .include
          .add(/node_modules/)
          .end()
      .type('javascript/auto');
  },
```

**Comment by Deja-vuuu** [comment]
> 
.end 啥意思 我之前搜到的 少了这个会报错
![image](https://user-images.githubusercontent.com/27748682/167096766-910b6830-9348-495a-a1d4-c793eb368db3.png)

**Comment by Deja-vuuu** [comment]
> 
差不多看懂了 文档在这里 
https://github.com/neutrinojs/webpack-chain

**Comment by luoye00** [comment]
> ```js
> .module
>       .rule('mjs$')
>       .test(/\.mjs$/)
>       .include
>           .add(/node_modules/)
>           .end()
>       .type('javascript/auto');
> ```

This works for me which I use `umi@^3.4.8`
