### ISSUE TITLE
关于umi权限控制的疑问

### ISSUE THREAD

**Issue by amelonsamy** [umijs/umi#807]
在umi的官方文档中说umi的权限控制是通过配置定制化的 Route 组件来实现权限路由的，在其配置文件中也是按这种配置
![image](https://user-images.githubusercontent.com/29348038/43943794-63473756-9caf-11e8-96b2-0a6a9d547349.png)，有疑问的是在这个地方我的理解是就是配置路由的准入权限，那这个privateRoute就是配置当前路由的准入权限吗，还有就是文件的目录有强制要求吗，关于其中的具体实现能否解答，或者还有一点是不仅要配置是否登录才可以查看，还需要配置不同角色的访问权限又应该怎么实现，望解菜鸟疑惑谢谢！

**Comment by byan** [comment]
umi 仅仅是客户端，权限和菜单这些事还是交给服务端下发吧。
