### ISSUE TITLE
[Bug] WATCH_IGNORED 不生效

### ISSUE THREAD

**Issue by lys623** [umijs/umi#8072]
## What happens?

WATCH_IGNORED 配置后不生效 ，如下图：
![image](https://user-images.githubusercontent.com/4364314/167101822-f5bf0c41-1049-40db-a2a6-3d7709ceeece.png)
![image](https://user-images.githubusercontent.com/4364314/167102121-398a55b9-81d9-4613-8d05-6996b98eb54f.png)

查看相关代码后发现 @umijs/preset-built-in 包里面未读取process.env.WATCH_IGNORED变量，所以实际上代码未生效？不知道是否是这样；

期望效果：当配置了WATCH_IGNORED=onlyDev.js 后，改动onlyDev.js文件内容不用引起devServer 重启和umi webpack重新编译

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:3.2.22
- **Node Version**: v14.17.6
- **Platform**:Mac

**Comment by GGwujun** [comment]
你应该传递一个文件名吧，这么传被解析成onlyDev目录了

**Comment by lys623** [comment]
文件名也不行

**Comment by lys623** [comment]
> 你应该传递一个文件名吧，这么传被解析成onlyDev目录了

你试过用这个参数可以吗？

**Comment by lys623** [comment]
@sorrycc 这个修复了吗？在哪个版本

**Comment by lys623** [comment]
@sorrycc 麻烦帮忙看看，求助
