### ISSUE TITLE
怎么样可以在page或component中获取配置项routes

### ISSUE THREAD

**Issue by bianbao** [umijs/umi#8076]
onRouteChange({ routes, matchedRoutes, location, action })
运行时配置这里可以获取routes，那么在page或component中怎么获取？？没有一个use么？

**Comment by williamnie** [comment]
页面内获取routes是什么场景呢？想实现什么功能？

**Comment by drizzlesconsin** [comment]
在页面组件，通过 `props.routes` 就能拿到。
