### ISSUE TITLE
[Bug] 配置layout后，无法动态加载微前端路由

### ISSUE THREAD

**Issue by rawbin-** [umijs/umi#8080]
## What happens?

umi 配置了layout后，无法动态加载微前端的路由，静态的可以，不配layout也可以

## Mini Showcase Repository(REQUIRED)
https://github.com/rawbin-/umi-layout-debug

## How To Reproduce
yarn && yarn start，然后点击 "/app-react17"
<img width="866" alt="image" src="https://user-images.githubusercontent.com/8169783/167414087-67e683bb-97b9-433c-aedf-a33342778f05.png">
<img width="615" alt="image" src="https://user-images.githubusercontent.com/8169783/167414267-b58f688a-2389-48d1-936d-c9dbc8775f44.png">
<img width="769" alt="image" src="https://user-images.githubusercontent.com/8169783/167414558-95fad1ad-7ff5-499a-9c56-1ca230e38d2d.png">

## Context

- **Umi Version**: umi@3.5.23
- **Node Version**:v16.14.2
- **Platform**: macOS

**Comment by hyzx86** [comment]
同问。。怎么动态创建路由啊。。
https://github.com/ant-design/ant-design-pro/issues/9920
