### ISSUE TITLE
[Bug] uncaught syntaxerror: unexpected token '<'

### ISSUE THREAD

**Issue by ios-lcj** [umijs/umi#8084]
## What happens?

umi的项目放在命名带有空格（%20）的文件夹下，运行项目时，会报错:uncaught syntaxerror: unexpected token '<'。

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

1. yarn create @umijs/umi-app 新建一个umi项目
2. 将该项目放入一个命名带有空格（%20）的文件夹下。
3. yarn start 运行该项目。
4. 打开页面即可发现页面空白，控制台：uncaught syntaxerror: unexpected token '<'。

## Context
umi:3.5.21
最新版本
- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by stormslowly** [comment]
你好 操作系统 是 window 的吗？
我 macos 没有复现

**Comment by ios-lcj** [comment]
![image](https://user-images.githubusercontent.com/72920904/168009754-cc27002f-e784-436b-a091-374731439918.png)

![image](https://user-images.githubusercontent.com/72920904/168009784-f18cd3b3-73ec-416a-a163-691f7792c3ce.png)


![image](https://user-images.githubusercontent.com/72920904/168009815-58b390a6-4dc1-4f5f-89b4-beac8894b814.png)

可以试试这样命名父文件夹
我是必现的bug
系统：Mac OS
windows上没试过

**Comment by stormslowly** [comment]
问题 已经定位到了，是 webpack-dev-middleware 的问题，4.x.x 就没有此问题。我提个 PR 升级下？

@ios-lcj  想问下你是有什么特殊的需求 需要在文件夹名中 有%20 ？

**Comment by 879037282** [comment]
也没有特殊需求。仓库的文件夹命名带有空格，拉出来的时候就是有%20（URI编码）。运行项目的时候发现这个bug。项目放到别的文件夹下就没问题。
