### ISSUE TITLE
[Bug] SSR 打包出现build failed的问题  Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by wangjpLancelote** [umijs/umi#8087]
## What happens?

SSR 模式下，执行 umi build 命令，服务端构建成功，客户端构建失败，报错： Cannot read properties of undefined (reading 'startsWith')

版本："umi": "^3.2.19",
node版本：16
windows11

.umirc.ts配置
![image](https://user-images.githubusercontent.com/29453145/168065298-500d277f-9f11-4721-937e-3631ec5e1c8a.png)

错误截图
![image](https://user-images.githubusercontent.com/29453145/168065033-13045558-7499-4e3f-a340-dda3b9499eab.png)

**Comment by CooLNuanfeng** [comment]
+1

**Comment by tinymins** [comment]
+1

**Comment by zcge** [comment]
+1

**Comment by guanyuan** [comment]
+1

**Comment by zcge** [comment]
> +1
> 
> ```js
> try {
>   // fix: umi 脚本报错
>   // https://github.com/umijs/umi/issues/7708
>   // https://github.com/umijs/umi/issues/8087
>   const filePath = 'node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/ssr/ssr.js';
>   let text = fs.readFileSync(filePath, 'utf8');
>   text = text.replace(
>     'if (chunk && opts.chunks.find(c => c.name.startsWith(chunk))) {',
>     'if (chunk && opts.chunks.find(c => c.name && c.name.startsWith(chunk))) {',
>   );
>   fs.writeFileSync(filePath, text);
> } catch (error) {
>   console.error(error);
> }
> ```
> 
> https://github.com/JDFED/drip-table/blob/0ffbb319f99952bc9fd17b1349a9903145c5cd3b/bin/fix-dep.js#L11-L24 我们已经曲线救国了 😅

你这个方法是真的骚气 ~~~
