### ISSUE TITLE
打包出来的page文件是大写的，怎么转成小写的

### ISSUE THREAD

**Issue by heyizhiyuan** [umijs/umi#8088]
之前的page
<img width="349" alt="image" src="https://user-images.githubusercontent.com/39208129/168192215-ec241bd0-b304-4ef9-9c9d-032d5b5978c4.png">

打包出来的page

<img width="306" alt="image" src="https://user-images.githubusercontent.com/39208129/168192130-190c3c1c-a29e-4dd1-a5cd-df25ea22d503.png">

**Comment by drizzlesconsin** [comment]
如果你用的是 `约定式路由`，建议目录名、页面文件名**用小写**。

**Comment by heyizhiyuan** [comment]
可以做成可配置的吗，之前umi2打包出来就是全小写的
