### ISSUE TITLE
document.ejs入口页问题

### ISSUE THREAD

**Issue by z810276431** [umijs/umi#8090]
背景：
document.ejs引入外部css样式，需要在编译后覆盖项目编译后的umi.css样式，但是目前编译后的入口页umi.css永远是在最下面

提议：

能否在配置中配置固定document.ejs生成。比如一开始就引入umi.js和umi.css，不期望编译过程中在最下面添加

**Comment by drizzlesconsin** [comment]
在 config 里面配置你的外部 CSS 文件，看是不是你想要的。
https://github.com/umijs/umi/blob/5c86b136b551fdc5327536da5ec223c4e936a998/packages/core/src/Html/Html.ts#L144-L154

**Comment by z810276431** [comment]
> 在 config 里面配置你的外部 CSS 文件，看是不是你想要的。
> 
> https://github.com/umijs/umi/blob/5c86b136b551fdc5327536da5ec223c4e936a998/packages/core/src/Html/Html.ts#L144-L154

配置后外部css还是在打包生成的umi.css上面，达不到外部css覆盖umi.css的效果

**Comment by drizzlesconsin** [comment]
雀食
应该是没解决的问题

https://github.com/umijs/umi/issues/1002#issuecomment-599168436
https://github.com/umijs/umi/issues/3166#issuecomment-528732989

**Comment by drizzlesconsin** [comment]
1. 可以先把外部 .css 在 global.less 中 @import。
2. 通过 script 生成 link 注入。
```js
  headScripts: [
    `
      var link = document.createElement('link');
      link.rel = 'stylesheet';
      link.href = url;
      document.querySelector('head').append(link);
    `,
  ]
```

**Comment by z810276431** [comment]
> 1. 可以先把外部 .css 在 global.less 中 @import。
> 2. 通过 script 生成 link 注入。
> 
> ```js
>   headScripts: [
>     `
>       var link = document.createElement('link');
>       link.rel = 'stylesheet';
>       link.href = url;
>       document.querySelector('head').append(link);
>     `,
>   ]
> ```

这个思路可以，我来试试，感觉有点可行性

**Comment by z810276431** [comment]
> 1. 可以先把外部 .css 在 global.less 中 @import。
> 2. 通过 script 生成 link 注入。
> 
> ```js
>   headScripts: [
>     `
>       var link = document.createElement('link');
>       link.rel = 'stylesheet';
>       link.href = url;
>       document.querySelector('head').append(link);
>     `,
>   ]
> ```

不好意思我能再问你一个问题吗，就是这个编译生成后的html会自动在最后补全umi.js的引用，这有办法能让他不加么

**Comment by drizzlesconsin** [comment]
如果都不需要输出的 umi.js，那不要输出 html 文件 `HTML=none`，手动构建。或者写个脚本在 buid 完成后删掉那一行。需求的意图是要做什么。

**Comment by z810276431** [comment]
> 如果都不需要输出的 umi.js，那不要输出 html 文件 `HTML=none`，手动构建。或者写个脚本在 buid 完成后删掉那一行。需求的意图是要做什么。

需求的意图是想自己根据业务场景自己手动用js去加载umi.js，这个build完成后删掉那一行的脚本是写在哪里合适

**Comment by drizzlesconsin** [comment]
`/xxxxx.sh`

```bash
# package.json
"build": "cross-env UMI_ENV=prod npm run clean:dist && umi build && npm run xx",
"xx": 'sh ./xxxxx.sh'
```

**Comment by z810276431** [comment]
> 

已解决，非常感谢
