### ISSUE TITLE
eslint is no work

### ISSUE THREAD

**Issue by programmer-yang** [umijs/umi#81]
环境：vscode
操作：[faq](https://umijs.org/docs/zh-Hans/faq.html#eslint) 按教程
现象：eslint没有工作
期望：eslint能正常工作
其他：是否可以实现一个命令，比如：`umi init eslint`自动生成一个eslint配置和依赖的目标，用户只需要安装一下依赖就可以了

**Comment by sorrycc** [comment]
@zhang740

**Comment by zhang740** [comment]
测试eslint是没问题的，具体什么问题？vscode安装了eslint插件并运行正常么？ @programmer-yang

**Comment by programmer-yang** [comment]
@zhang740 
抱歉，可能是我理解有些问题，我以为`eslint-config-umi`里会包含一些默认规则，配置`"extends": "eslint-config-umi",`后安装好依赖，就会自动有一些默认规则。
是不是还需要自己配置所有的规则？比如：
```
{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "rules": {
    // ...
  }
}
```

**Comment by zhang740** [comment]
有默认规则的 @programmer-yang 
具体规则可见 https://github.com/umijs/umi/blob/master/packages/eslint-config-umi/src/index.js

**Comment by programmer-yang** [comment]
![image](http://p3i654gqw.bkt.clouddn.com/new-eslint-error.gif)

@zhang740 大概是这个情况，别的项目eslint是生效的

**Comment by programmer-yang** [comment]
@zhang740 Hello,请问是我使用方法不对还是配置有问题？

**Comment by zhang740** [comment]
我这没法复现。。。不知道你那vscode的eslint为啥没有生效 @programmer-yang

**Comment by programmer-yang** [comment]
@zhang740 我把`"extends": "eslint-config-umi"`修改为`"extends": "airbnb"`，然后安装`eslint-config-airbnb`，ESlint就生效入了。
如下：
![image](https://user-images.githubusercontent.com/8612167/35785837-7b0b4b7c-0a5e-11e8-91f3-2cad8b066d81.png)
但切换回`"extends": "eslint-config-umi"`就又不生效了

**Comment by sorrycc** [comment]
eslint-config-umi 没安装好？

**Comment by sorrycc** [comment]
你也可以用 airbnb，eslint-config-umi 是可选的。

**Comment by programmer-yang** [comment]
这是我目前的`package.json`
```
{
  "devDependencies": {
    "eslint": "4",
    "eslint-config-umi": "^0.1.2",
    "eslint-plugin-flowtype": "2",
    "eslint-plugin-import": "2",
    "eslint-plugin-jsx-a11y": "5",
    "eslint-plugin-react": "7"
  },
  "dependencies": {
    "eslint-config-airbnb": "^16.1.0"
  }
}
```
@sorrycc 好的，我再试一试，如果实在弄不好就用`airbnb`

**Comment by programmer-yang** [comment]
@sorrycc @zhang740 
是我的理解错误，其实`eslint`已经生效了。
因为之前使用`roadhog`，`roadhog`的`eslint`规则是基于`airbnb`的，像上边儿动图中的：
`import/newline-after-import`
`indent`
`semi`
这些规则在`airbnb`中都设置了默认值。
我以为`umi`中也会有类似的设计，所以看到这些规则没生效，以为是配置有问题。
其实只要自己添加这些规则就好了，哈哈。

---

我在本地`.eslintrc`中添加了
```
{
  "extends": "eslint-config-umi",
  "rules": {
    "semi": ["error", "never"]
  }
}
```
效果：
![image](https://user-images.githubusercontent.com/8612167/35791440-e9c7d516-0a82-11e8-877d-a9b32fe8e89d.png)

---

最后我想问一下，umi关于默认规则这块儿，是怎么想的？是完全抛给使用者自己去定义？还是后期会更新一些默认规则上去？

**Comment by sorrycc** [comment]
https://github.com/umijs/umi/blob/master/packages/eslint-config-umi/src/index.js
umi 的规则在这里。
