### ISSUE TITLE
当有二级或三级以上页面的时候，刷新或者键入URL就会报错。

### ISSUE THREAD

**Issue by limit81995** [umijs/umi#8101]
不打包的时候正常，打包单页面之后就会出现以下情况

如果直接进入根目录  1.1.1.1/的话，是可以进入入口的。
如果是在地址栏直接输入 1.1.1.1/goods/putin  直接报错了。
如果是从根目录1.1.1.1的页面中，鼠标点击某按钮进去的话，那么是可以正常进入1.1.1.1/goods/putin页面的。

![1111](https://user-images.githubusercontent.com/63061177/168997558-a9ed32a2-ffaf-49d9-aa2d-540db2a23212.png)
![2222](https://user-images.githubusercontent.com/63061177/168997567-d67cdc37-2546-4569-9dfa-f868e7be4b66.png)

**Comment by mjhcc365** [comment]
改成哈希路由试试

**Comment by limit81995** [comment]
这个我自己已经解决，只需要在  .umirc.ts 文件中，添加exportStatic:{} 
原理应该是这样： 最开始单页面的时候你只能输入入口地址的时候，才会加载js，css。当你使用domain/xxx/xxx  这种有二级目录的时候，因为未找到模板，所以无法加载umi.js和css，又因为没有js所以无法使用js识别路径，所以就导致报错404.
