### ISSUE TITLE
[Bug] umi3.5 使用swiper8 模块解析错误、且无法开启mfsu

### ISSUE THREAD

**Issue by thisTom** [umijs/umi#8102]
复现方法：
初始化umi项目，按照[swiper官方例子](https://swiperjs.com/react)来。

swiper官方引入方式，报错找不到依赖：
![微信截图_20220518152254](https://user-images.githubusercontent.com/19346741/169025282-e58018f2-a18c-47e9-8b0f-a4c2fe8b0b4e.png)

自己魔改得引入方法，虽然不报错，但是开启不了mfsu，项目大，不开mfsu太慢了
![image](https://user-images.githubusercontent.com/19346741/169025624-54774999-308a-42b1-8977-c5f8d1cacf80.png)

**Comment by thisTom** [comment]
![image](https://user-images.githubusercontent.com/19346741/169026041-bf68f19c-30e2-4c07-a8a7-167d7588344f.png)
swiper在package.json 中有声明exports @sorrycc

**Comment by qiutian00** [comment]
使用swiper8 遇到同样问题
