### ISSUE TITLE
[Bug]create-umi 项目执行 script dev 提示无法解析模块 btoa

### ISSUE THREAD

**Issue by kibuniverse** [umijs/umi#8111]
## What happens?
使用 pnpx create-umi 创建项目，选项为 antd-design-pro => Ts => simple 生成项目
生成后执行 pnpm dev 报错
![image](https://user-images.githubusercontent.com/50582439/169688301-a251dcf7-054a-4443-8817-551cf2041316.png)

使用 yarn create umi 和 pnpx create-umi 测试均稳定复现，目前看来影响范围为 mock 无法使用

github地址： https://github.com/kibuniverse/bug-report-umi

## 复现步骤
- git clone https://github.com/kibuniverse/bug-report-umi
- pnpm i
- pnpm dev

## Context

- **Umi Version**: 3.5.0
- **Node Version**: 16.14.2
- **Platform**: MacOS Apple Silicon

## 个人解决方案
使用 yarn 安装 btoa 包
yarn install btoa

**Comment by peter064226** [comment]
遇到同样的问题

**Comment by kibuniverse** [comment]
> 遇到同样的问题
个人解决方案是yarn可以解决，pnpm依赖应该有点问题

**Comment by maqinghao** [comment]
npm 遇到同样的问题?求解决呀!

**Comment by kibuniverse** [comment]
> install btoa



> npm 遇到同样的问题?求解决呀!

npm install btoa 试试？

**Comment by maqinghao** [comment]
> > 安装 btoa
> 
> > npm 遇到同样的问题?求解决呀!
> 
> npm install btoa 试试？
解决了,但感觉问题的根源不是它,一样的node_modules包,同事启动没有错误,我启动就有错误,node版本不一样,他的14,我的16.
去antd pro 查找,有人合并更新了"swagger-ui-react": "^4.11.0",在安装解决了,但是插件openapi里面依赖依然是3的版本,头大呀!!!
