### ISSUE TITLE
[Bug] 区块和模板一直暂无数据这个功能现在不维护了吗

### ISSUE THREAD

**Issue by NingTang-DaoCloud** [umijs/umi#8121]
## What happens?
试了各种方式区块就是没数据，这个怎么解决啊

![image](https://user-images.githubusercontent.com/76761151/170473547-789c8439-9f2d-4e75-a871-96a1098900ec.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by speedwindandrain** [comment]
这个问题解决了吗？

**Comment by xiaohuoni** [comment]
umi ui 暂停维护了
