### ISSUE TITLE
[Bug] 线上主应用访问子应用跨域问题

### ISSUE THREAD

**Issue by dadtakesmefly** [umijs/umi#8123]
线上主应用和子应用不同的域名，加载时候会出现跨域，请问这个跨域怎么配置，umi的配置文档里也没有看到，自己在网上查了其他方案， 在config.js里增加
headers: {
    'Access-Control-Allow-Origin': '*',
 }，还是不生效，
请问到底该如何正确配置才能不跨域。
谢谢了。

**Comment by jk4235** [comment]
要对应的server设置支持跨域
