### ISSUE TITLE
[Bug] 新项目 umi 3.5.25 不能直接导出 useSelector 和 useDispatch

### ISSUE THREAD

**Issue by lanzhsh** [umijs/umi#8137]
新搭建的 umi 3.5.25 本地运行 .umi文件下面没有 plugin-dva, 不能直接导出 useSelector 和 useDispatch, 之前的旧项目安装 umi 3.5.25 可以导出

- **Umi Version**: 3.5.25
- **Node Version**: 12.9.0
- **Platform**: Chrome

**Comment by Memories-SlowFever** [comment]
我也是
