### ISSUE TITLE
[Bug]umi2升级umi3后打包报错Error: Cannot find module '@@/history'\nRequire stack

### ISSUE THREAD

**Issue by WangDianhang** [umijs/umi#8141]
打包部署时候报错Cannot find module '@@/history'\Require stack \- /root/admxy/node_modules/umi/lib/router.js\- /root/admxyi/node_modules/umi/lib/index.js\ ...

下面是我config配置
![image](https://user-images.githubusercontent.com/100115293/172160516-dfb9823c-581a-4e30-816e-e67b8930c75f.png)

package.json文件
![image](https://user-images.githubusercontent.com/100115293/172160784-fc34828c-f253-43c3-a94a-4487ba998629.png)
![image](https://user-images.githubusercontent.com/100115293/172160838-568eac2e-a814-4526-a90a-4854e8f558a2.png)

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
