### ISSUE TITLE
登录跳转之后需要刷新页面，菜单才会根据权限显示

### ISSUE THREAD

**Issue by Tironzx** [umijs/umi#8145]
umi3.5在登录页面登录获取到用户权限之后跳转到首页，这个时候菜单栏没有根据我在access.ts里面配置的权限去显示/隐藏相应的菜单，需要刷新之后才会生效

**Comment by zhangheng0317** [comment]
umi4也有这个问题

**Comment by ratelgogo** [comment]
是执行顺序的问题吧，怎么没有解决怎么关了呢？

**Comment by wangchao18654941093** [comment]
我也出现这个问题了   umi4

**Comment by huangye0** [comment]
这个解决了吗 我现在也还是这个问题诶

**Comment by tyanbiao** [comment]
v4.0.20 还有这个问题，切换用户之后，要重新刷新才会显示正确的路由
