### ISSUE TITLE
[Bug] 使用 pnpm workspace 和 umi plugin-qiankun 时的依赖问题

### ISSUE THREAD

**Issue by ppxu** [umijs/umi#8148]
## What happens?

使用 pnpm workspace 创建项目，增加一个 umi 的应用并开启 plugin-qiankun，启动项目会报如下依赖错误

<img width="440" alt="image" src="https://user-images.githubusercontent.com/1119778/172513096-adb17e64-0975-4935-982d-52da8b39d190.png">

可以看到这些依赖是在 .umi 的文件中依赖的，不在应用的依赖里面，因为 pnpm 安装包的机制导致找不到这些依赖

## Mini Showcase Repository(REQUIRED)

https://github.com/ppxu/pnpm-umi

## How To Reproduce

* pnpm i
* pnpm start

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
Closed via https://github.com/umijs/plugins/pull/869
