### ISSUE TITLE
BUG 在umi3.5.2 中使用react dnd 时出现以下错误 

### ISSUE THREAD

**Issue by zy546629864** [umijs/umi#8152]
error  in ./node_modules/react-dnd/dist/esm/internals/SourceConnector.mjs

Module not found: Error: Can't resolve 'D:/fhtbase/node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/esm/createClass' in 'D:\fhtbase\node_modules\react-dnd\dist\esm\internals'
Did you mean 'createClass.js'?
BREAKING CHANGE: The request 'D:/fhtbase/node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/esm/createClass' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

 error  in ./node_modules/react-dnd/dist/esm/internals/TargetConnector.mjs

Module not found: Error: Can't resolve 'D:/fhtbase/node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/esm/classCallCheck' in 'D:\fhtbase\node_modules\react-dnd\dist\esm\internals'
Did you mean 'classCallCheck.js'?
BREAKING CHANGE: The request 'D:/fhtbase/node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/esm/classCallCheck' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

 error  in ./node_modules/react-dnd/dist/esm/internals/TargetConnector.mjs

Module not found: Error: Can't resolve 'D:/fhtbase/node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/esm/createClass' in 'D:\fhtbase\node_modules\react-dnd\dist\esm\internals'
Did you mean 'createClass.js'?
BREAKING CHANGE: The request 'D:/fhtbase/node_modules/@umijs/babel-preset-umi/node_modules/@babel/runtime/helpers/esm/createClass' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

- **Umi Version**: v3.5.2
- **Node Version**: v14.19.1
- **Platform**:

**Comment by lhkg1988** [comment]
咋解决的？

**Comment by caoLei1997** [comment]
> 咋解决的？
https://github.com/umijs/umi/issues/7935 老哥看这个issues已经解决了。
