### ISSUE TITLE
UseRequestProvider配置无效

### ISSUE THREAD

**Issue by xu-Aurora** [umijs/umi#8164]
问题：
UseRequestProvider全局配置formatResult无效

这是代码全局配置
`<UseRequestProvider value={{
          formatResult: res => res,
          throttleInterval: 2000,
          loadingDelay: 1000,
          debounceInterval: 500
        }}>`

## Context

- **Umi Version**: 3.5.24
- **Node Version**:16.3.1
- **Platform**:chrome

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
