### ISSUE TITLE
[Bug] @umijs/max 读取本地图片的正确方式是什么？

### ISSUE THREAD

**Issue by taofeifanIT** [umijs/umi#8170]
## 无法读取本地图片
error - ./src/pages/login/index.tsx:15:0-41
Module not found: Error: Can't resolve '../../access/logo.png' in 'D:\WebSpace\weiyu01\src\pages\login'
![image](https://user-images.githubusercontent.com/42193371/174748752-42867d9d-6aa7-4b40-8656-9c0fb5f49608.png)
![image](https://user-images.githubusercontent.com/42193371/174748808-d57e81a8-073d-4a26-b32a-26be0fdcdbc6.png)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by siyi98** [comment]
```js
import logo from './logo.png'

<img src={logo} />
```

**Comment by xiaohuoni** [comment]
```js
import logo from '@/access/logo.png'

<img src={logo} />
```

**Comment by powerfulyang** [comment]
但是 css 里面的 url 引入的图片也会报错，就离大谱了啊。
<img width="810" alt="image" src="https://user-images.githubusercontent.com/21997724/174983380-7760707c-1ff8-4914-8f46-f0fed95817fd.png">

**Comment by powerfulyang** [comment]
css 里面有 url 引入图片的需要在 config.ts 里面加上
```
  cssLoader: {
    url: false,
  }
```
