### ISSUE TITLE
[Doc] 文档不规范，语句不通

### ISSUE THREAD

**Issue by wkylin** [umijs/umi#8178]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

![image](https://user-images.githubusercontent.com/1208330/174918834-65181075-b2c5-450b-9380-88e2d47449e0.png)

"这带来的好处是。通过 ",  多个 “。”
## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
PR Welcome.
