### ISSUE TITLE
[Bug] umi3文档没有了嘛，使用脚手架模式选择antdpro，为啥layout和之前的不一样了

### ISSUE THREAD

**Issue by jinpikaFE** [umijs/umi#8179]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by siyi98** [comment]
https://umijs.org/
右上角有Umi3的文档链接

**Comment by sorrycc** [comment]
之前也有，只不过入口在下方，不明显。 @frontend-winter
