### ISSUE TITLE
[Feature Request]Umi4 如何获取全部路由信息?

### ISSUE THREAD

**Issue by Aicmortal** [umijs/umi#8180]
## Background

Umi4 如何获取全部路由信息?
在使用非Ant组件库的的情况下,想要通过路由信息动态生成菜单,如何获取所有的路由信息?
Umi3的时候可以通过路由组件的props中的routes获取,umi4该如何获取呢?

还是说这种需求目前只能通过编写一个类似的Layout的插件来实现?

## Proposal

getRoutes()

**Comment by Mingholy** [comment]
https://umijs.org/docs/api/api#useappdata
