### ISSUE TITLE
umi 官网跳转链接问题

### ISSUE THREAD

**Issue by doYouHearPeopleSing** [umijs/umi#8181]
此问题无关框架本身: 

umi官网链接 https://umijs.org/zh-CN 里 click Docs之后跳转链接是 https://umijs.org/undefined/docs, click Blog 的跳转链接是 https://umijs.org/undefined/blog, 两个跳转后的链接都无法正确渲染页面内容

**Comment by doYouHearPeopleSing** [comment]
截止2022年06月22日北京时间11: 03这个问题依旧存在

**Comment by siyi98** [comment]
先用这个访问吧：https://umijs.org

**Comment by doYouHearPeopleSing** [comment]
> 先用这个访问吧：https://umijs.org

OK, 但是提醒下这里应该处理下
