### ISSUE TITLE
[Bug] 使用 umi4 构建应用 在 .tsx 文件使用 prettierrc 格式化代码失效

### ISSUE THREAD

**Issue by johnny-en** [umijs/umi#8182]
恭喜期待已久 umi 4 正式发布👋👋👋，我尝试使用  `pnpm create umi my-app` 创建应用 
  构建过程选择：
- [√ ]  Ant Design Pro
- [√ ]  pnpm
- [√ ]  taobao

使用 vscode 对 .tsx 进行编辑，当使用快捷对如下代码进行格式化时
![image](https://user-images.githubusercontent.com/64029524/174936142-480f17fd-92bd-481c-b46d-b9da67ed8945.png)
，prettierrc 报错
![image](https://user-images.githubusercontent.com/64029524/174936203-66ce61fe-6b3d-4e71-9c2f-eb31a2b69a4c.png)

报错信息提示，未找到本地 .prettierrc 配置文件中的两个插件，然后尝试安装这两个插件，安装成功后还是无法进行格式化，所以，现在只好把 prettierrc 配置文件中的 `"plugins": ["prettier-plugin-organize-imports", "prettier-plugin-packagejson"]`这段配置删除就可以正常格式化 .tsx 代码了，请问，如果还使用这两个插件需要怎么配置呢

- **Umi Version**:  4.0
- **Node Version**:  16.13
- **Platform**: window10

**Comment by sorrycc** [comment]
报的错就是找不到依赖，理论上安装之后就可以。

由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

**Comment by ratelgogo** [comment]
同样的问题，安装了还是这样

**Comment by leohxj** [comment]
https://github.com/simonhaenisch/prettier-plugin-organize-imports/issues/34

**Comment by fz6m** [comment]
该问题是 symlink 的依赖不被 vscode prettier 插件识别的问题，已有解决 PR ，如不想使用变通方法（使用 `require.resolve()` 指定插件），可支持该 PR 。

https://github.com/prettier/prettier-vscode/pull/2566

**Comment by xinlanlan** [comment]
> 该问题是 symlink 的依赖不被 vscode prettier 插件识别的问题，已有解决 PR ，如不想使用变通方法（使用 `require.resolve()` 指定插件），可支持该 PR 。
> 
> [prettier/prettier-vscode#2566](https://github.com/prettier/prettier-vscode/pull/2566)

可是我用npm下载的同样会出现 `Cannot find module 'prettier-plugin-organize-imports'`  的问题

**Comment by chj-damon** [comment]
好吧，原来是prettier-vscode的问题。我还想着改一下create-umi的模板混个PR呢...

**Comment by conorzhong** [comment]
这样也可以：

```json
{
  "printWidth": 80,
  "singleQuote": true,
  "trailingComma": "all",
  "proseWrap": "never",
  "overrides": [{ "files": ".prettierrc", "options": { "parser": "json" } }],
  "plugins": [
    "./node_modules/prettier-plugin-organize-imports",
    "./node_modules/prettier-plugin-packagejson"
  ]
}
```

**Comment by fz6m** [comment]
已解决，请重载 vscode 下载最新版本的 prettier 插件。

**Comment by LoisLuo-c** [comment]
还是未解决，ts合tsx都格式化不了

**Comment by fz6m** [comment]
请检查你的 vscode prettier 插件版本是最新的。
