### ISSUE TITLE
[Bug] pro-layout配置透传不了问题

### ISSUE THREAD

**Issue by jinpikaFE** [umijs/umi#8183]
![8aed48b92c496685344915ecbb57f1a](https://user-images.githubusercontent.com/74050087/174953412-f9bf1451-8952-4436-a571-167c36ab52d1.png)
![b20eb1752ae11e86e2839b73da57ce9](https://user-images.githubusercontent.com/74050087/174953454-385a5fc1-9623-47f3-823e-ec3d2399ed56.png)
使用了该配置和 https://procomponents.ant.design/components/layout/#prolayout 官网的样式以及布局都不同，修改配置，布局也没有变。主题色也没变为配置的主题色

**Comment by WuJiY** [comment]
+1

**Comment by Merry74751** [comment]
+1

**Comment by sorrycc** [comment]
layout 变更点：

构建时配置中的 name 更名为 title ，且仅支持 title 和 locale 属性，其他配置需写入运行时配置：

```diff
export default {
  layout: {
-   name: "xxx",
+   title: "xxx",
    // 默认开启，如无需菜单国际化可关闭
+   locale: false,
    // 其他之前透传给 ProLayout 的配置项均移动到运行时配置中，构建时配置不再支持
-   logo: "https://gw-office.alipayobjects.com/basement_prod/c83c53ab-515e-43e2-85d0-4d0da16f11ef.svg",
-   menuRender: false,
-   ...
  },
}
```
