### ISSUE TITLE
[Bug] umi3 升级umi4问题 

### ISSUE THREAD

**Issue by jinpikaFE** [umijs/umi#8184]
按官网步骤修改报错
![image](https://user-images.githubusercontent.com/74050087/174954150-8d16c532-09bc-4760-9c37-c695dcf35493.png)

**Comment by frontend-winter** [comment]
你也是真的敢

**Comment by sereinDS** [comment]
应该是第三方插件不支持umi4导致的。umi4移除了modifyBabelOpts 。所以提示  is not a function。

**Comment by MaelWeb** [comment]
你也真是六

**Comment by jinpikaFE** [comment]
- @umijs/preset-built-in (preset)
    - @umijs/preset-react (preset)
    - ./node_modules/umi/node_modules/@@/registerMethods
    - ./node_modules/umi/node_modules/@@/routes
    - ./node_modules/umi/node_modules/@@/generateFiles/core/history
    - ./node_modules/umi/node_modules/@@/generateFiles/core/plugin
    - ./node_modules/umi/node_modules/@@/generateFiles/core/polyfill
    - ./node_modules/umi/node_modules/@@/generateFiles/core/routes
    - ./node_modules/umi/node_modules/@@/generateFiles/core/umiExports
    - ./node_modules/umi/node_modules/@@/generateFiles/core/configTypes
    - ./node_modules/umi/node_modules/@@/generateFiles/umi
    - ./node_modules/umi/node_modules/@@/features/404
    - ./node_modules/umi/node_modules/@@/features/alias
    - ./node_modules/umi/node_modules/@@/features/analyze
    - ./node_modules/umi/node_modules/@@/features/autoprefixer
    - ./node_modules/umi/node_modules/@@/features/base
    - ./node_modules/umi/node_modules/@@/features/chainWebpack
    - ./node_modules/umi/node_modules/@@/features/chunks
    - ./node_modules/umi/node_modules/@@/features/cssLoader
    - ./node_modules/umi/node_modules/@@/features/cssModulesTypescriptLoader
    - ./node_modules/umi/node_modules/@@/features/cssnano
    - ./node_modules/umi/node_modules/@@/features/copy
    - ./node_modules/umi/node_modules/@@/features/define
    - ./node_modules/umi/node_modules/@@/features/devScripts
    - ./node_modules/umi/node_modules/@@/features/devServer
    - ./node_modules/umi/node_modules/@@/features/devtool
    - ./node_modules/umi/node_modules/@@/features/dynamicImport
    - ./node_modules/umi/node_modules/@@/features/dynamicImportSyntax
    - ./node_modules/umi/node_modules/@@/features/exportStatic
    - ./node_modules/umi/node_modules/@@/features/externals
    - ./node_modules/umi/node_modules/@@/features/extraBabelIncludes
    - ./node_modules/umi/node_modules/@@/features/extraBabelPlugins
    - ./node_modules/umi/node_modules/@@/features/extraBabelPresets
    - ./node_modules/umi/node_modules/@@/features/extraPostCSSPlugins
    - ./node_modules/umi/node_modules/@@/features/forkTSChecker
    - ./node_modules/umi/node_modules/@@/features/fastRefresh
    - ./node_modules/umi/node_modules/@@/features/globalCSS
    - ./node_modules/umi/node_modules/@@/features/globalJS
    - ./node_modules/umi/node_modules/@@/features/hash
    - ./node_modules/umi/node_modules/@@/features/ignoreMomentLocale
    - ./node_modules/umi/node_modules/@@/features/inlineLimit
    - ./node_modules/umi/node_modules/@@/features/lessLoader
    - ./node_modules/umi/node_modules/@@/features/manifest
    - ./node_modules/umi/node_modules/@@/features/mfsu/mfsu
    - ./node_modules/umi/node_modules/@@/features/mountElementId
    - ./node_modules/umi/node_modules/@@/features/mpa
    - ./node_modules/umi/node_modules/@@/features/nodeModulesTransform
    - ./node_modules/umi/node_modules/@@/features/outputPath
    - ./node_modules/umi/node_modules/@@/features/plugins
    - ./node_modules/umi/node_modules/@@/features/postcssLoader
    - ./node_modules/umi/node_modules/@@/features/presets
    - ./node_modules/umi/node_modules/@@/features/proxy
    - ./node_modules/umi/node_modules/@@/features/publicPath
    - ./node_modules/umi/node_modules/@@/features/runtimePublicPath
    - ./node_modules/umi/node_modules/@@/features/ssr/ssr
    - ./node_modules/umi/node_modules/@@/features/singular
    - ./node_modules/umi/node_modules/@@/features/styleLoader
    - ./node_modules/umi/node_modules/@@/features/targets
    - ./node_modules/umi/node_modules/@@/features/terserOptions
    - ./node_modules/umi/node_modules/@@/features/theme
    - ./node_modules/umi/node_modules/@@/features/umiInfo
    - ./node_modules/umi/node_modules/@@/features/runtimeHistory
    - ./node_modules/umi/node_modules/@@/features/webpack5
    - ./node_modules/umi/node_modules/@@/features/workerLoader
    - ./node_modules/umi/node_modules/@@/features/html/favicon
    - ./node_modules/umi/node_modules/@@/features/html/headScripts
    - ./node_modules/umi/node_modules/@@/features/html/links
    - ./node_modules/umi/node_modules/@@/features/html/metas
    - ./node_modules/umi/node_modules/@@/features/html/scripts
    - ./node_modules/umi/node_modules/@@/features/html/styles
    - ./node_modules/umi/node_modules/@@/features/html/title
    - ./node_modules/umi/node_modules/@@/commands/build/build
    - ./node_modules/umi/node_modules/@@/commands/build/applyHtmlWebpackPlugin
    - ./node_modules/umi/node_modules/@@/commands/config/config
    - ./node_modules/umi/node_modules/@@/commands/dev/dev
    - ./node_modules/umi/node_modules/@@/commands/dev/devCompileDone/devCompileDone
    - ./node_modules/umi/node_modules/@@/commands/dev/mock/mock
    - ./node_modules/umi/node_modules/@@/commands/generate/generate
    - ./node_modules/umi/node_modules/@@/commands/help/help
    - ./node_modules/umi/node_modules/@@/commands/plugin/plugin
    - ./node_modules/umi/node_modules/@@/commands/version/version
    - ./node_modules/umi/node_modules/@@/commands/webpack/webpack
    - ./node_modules/@umijs/preset-react/lib/react
    - @umijs/plugin-access
    - @umijs/plugin-analytics
    - @umijs/plugin-antd
    - @umijs/plugin-crossorigin
    - @umijs/plugin-dva
    - @umijs/plugin-initial-state
    - @umijs/plugin-locale
    - @umijs/plugin-layout
    - @umijs/plugin-model
    - @umijs/plugin-request
    - @umijs/plugin-test
    - @umijs/plugin-helmet
    - ./node_modules/umi/lib/plugins/umiAlias

**Comment by jinpikaFE** [comment]
那是不是用的旧插件多了，是没法升级。。。感觉umi3项目肯定会用很多旧插件的

**Comment by xiaohuoni** [comment]
@umijs/plugin-access
@umijs/plugin-analytics
@umijs/plugin-antd
@umijs/plugin-crossorigin
@umijs/plugin-dva
@umijs/plugin-initial-state
@umijs/plugin-locale
@umijs/plugin-layout
@umijs/plugin-model
@umijs/plugin-request
@umijs/plugin-test
@umijs/plugin-helmet

这些插件 umi@4 里面都在 @umijs/plugins 里面

**Comment by viccsen** [comment]
big升级

**Comment by CODEOrz** [comment]
> 你也是真的敢

为啥说真的敢=，=是因为umi4坑太多了？

**Comment by mzvast** [comment]
这也太坑了，我也卡这了

**Comment by mzvast** [comment]
> @umijs/plugin-access @umijs/plugin-analytics @umijs/plugin-antd @umijs/plugin-crossorigin @umijs/plugin-dva @umijs/plugin-initial-state @umijs/plugin-locale @umijs/plugin-layout @umijs/plugin-model @umijs/plugin-request @umijs/plugin-test @umijs/plugin-helmet
> 
> 这些插件 umi@4 里面都在 @umijs/plugins 里面

请问这个咋迁移？文档里啥也没说，就说删掉，然后呢

**Comment by hyzx86** [comment]
这也太坑了，我也卡这了

**Comment by emeiziying** [comment]
删掉 config.dev.ts

**Comment by youtiao66** [comment]
删除`react-dev-inspector`, 并且要删除配置文件中的相应的插件。为后来的升级 umi v4 勇士指路
```
   plugins: [
     // https://github.com/zthxxx/react-dev-inspector
-    'react-dev-inspector/plugins/umi/react-inspector',
+    // 'react-dev-inspector/plugins/umi/react-inspector',
   ],
```

**Comment by curiousbabyMz** [comment]
max setup 阶段报错
`
Can't resolve 'D:/Projects/SeoFrontendWeb/src/.umi/plugin-model' in 'D:\Projects\SeoFrontendWeb\src\.umi\plugin-access' [plugin esbuildAliasPlugin]
`
爆炸
