### ISSUE TITLE
[Bug] 使用vite报错  The requested module '/node_modules/react-dom/client.js' does not provide an export named 'default'

### ISSUE THREAD

**Issue by jinpikaFE** [umijs/umi#8188]
## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by jinpikaFE** [comment]
![image](https://user-images.githubusercontent.com/74050087/174983945-22db9e1d-3634-439c-a261-c57559a98354.png)
![image](https://user-images.githubusercontent.com/74050087/174983970-d032db4b-bf4a-4095-b582-4da764a907ae.png)

**Comment by jinpikaFE** [comment]
1

**Comment by xierenyuan** [comment]
> ![image](https://user-images.githubusercontent.com/74050087/174983945-22db9e1d-3634-439c-a261-c57559a98354.png) ![image](https://user-images.githubusercontent.com/74050087/174983970-d032db4b-bf4a-4095-b582-4da764a907ae.png)

提供一下 复现的demo 吧

**Comment by jinpikaFE** [comment]
https://github.com/jinpikaFE/umi4 

> > ![image](https://user-images.githubusercontent.com/74050087/174983945-22db9e1d-3634-439c-a261-c57559a98354.png) ![image](https://user-images.githubusercontent.com/74050087/174983970-d032db4b-bf4a-4095-b582-4da764a907ae.png)
> 
> 提供一下 复现的demo 吧

**Comment by xierenyuan** [comment]
> https://github.com/jinpikaFE/umi4
> 
> > > ![image](https://user-images.githubusercontent.com/74050087/174983945-22db9e1d-3634-439c-a261-c57559a98354.png) ![image](https://user-images.githubusercontent.com/74050087/174983970-d032db4b-bf4a-4095-b582-4da764a907ae.png)
> > 
> > 
> > 提供一下 复现的demo 吧

通过你提供的demo 未复现问题, 你可以通过访问 fb.umijs.org 添加 `Umi 4 只有提供最简复现的问题会被答疑群`  里面@ 我提供更多信息

**Comment by xieqingtian** [comment]
same question

**Comment by zhanghaoxu** [comment]
same error
