### ISSUE TITLE
[Bug] Array.prototype.at 无法在safari 15.1 上使用, 但是umi的config上写的default是safari:10 

### ISSUE THREAD

**Issue by Valar103769** [umijs/umi#8189]
根据 core-js的指引, safari 15.4 支持.at语法, 我的环境是15.1, 我需要polyfill, umi配置默认的浏览器是safari:10 为什么没有包含polyfill呢?

**Comment by sorrycc** [comment]
umi 3? 应该是 core-js 没有更新，可以先手动加 .at 补丁绕过。
