### ISSUE TITLE
[Bug] Old document site is empty

### ISSUE THREAD

**Issue by nqhd3v** [umijs/umi#8190]
## What happens?

I don't know why, but, when I access some document pages, it is empty (White page)

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/106160187/175006114-ad9303cf-de32-4019-bc87-f472e7799b1b.png">

Example:
- [https://umijs.org/docs/deployment](https://umijs.org/docs/deployment)
- [https://umijs.org/docs/html-template](https://umijs.org/docs/html-template)

But, when I go to `/docs` only, it redirected to `https://umijs.org/docs/introduce/introduce`. So I guess that something went wrong when you upgraded it to version 4.

Please update it to a new route!

**Comment by sushi-su** [comment]
https://v3.umijs.org/
