### ISSUE TITLE
umi4新建项目报错

### ISSUE THREAD

**Issue by strongyc** [umijs/umi#8193]
'umi' 不是内部或外部命令，也不是可运行的程序
或批处理文件。:
![image](https://user-images.githubusercontent.com/51156342/175045001-bec27917-e3b1-495e-8404-4a795e9b766e.png)

**Comment by xierenyuan** [comment]
需要提供一下复现的demo

**Comment by sorrycc** [comment]
依赖没装好，或者其他本地环境问题。
