### ISSUE TITLE
[Bug] umijs/max vite 模式下，文件修改，整个页面刷新

### ISSUE THREAD

**Issue by phillip111** [umijs/umi#8195]
1. 使用 pnpm dlx create-umi 创建项目
2. 根据文档升级umi4
3. 配置umirc.ts vite:{}
4. 修改demo中docs.ts 整个页面重新加载刷新，修改index.ts 刷新效果正常

**Comment by hanwenbo** [comment]
> 模板问题. 修改成这样即可
> 
> ```tsx
> const DocsPage = () => {
>   return (
>     <div>
>       <p>This is umi docs.</p>
>     </div>
>   );
> };
> 
> export default DocsPage;
> ```

大佬为什么要这么写呢？
