### ISSUE TITLE
umi3.5以上在开启mfsu，运行umi dev报错，报错如图

### ISSUE THREAD

**Issue by xxssycyz299** [umijs/umi#8197]
![image](https://user-images.githubusercontent.com/58614657/175206106-e11c2eea-8458-4395-af5b-0d1f89fb4a9d.png)

![image](https://user-images.githubusercontent.com/58614657/175206083-db75e51b-f7d0-434f-8f22-c537bb4688fe.png)

**Comment by sorrycc** [comment]
请关于 mfsu 或者升级到 umi 4。
