### ISSUE TITLE
umi 是 roadhog 对比，还是应该和dva对比。

### ISSUE THREAD

**Issue by kaoding** [umijs/umi#82]
如题。

**Comment by okoala** [comment]
@kaoding kao
官网都说了，umi 是一套开箱即用的 Next.js-like 框架。roadhog 太底层了，dva 是数据流库。都不是一个层面的东西，先仔细看一遍文档吧。

**Comment by sorrycc** [comment]
简单来说，

* dva 是数据流
* roadhog 是通用工具
* umi 是框架，包含路由和工具，很多的约定，很多的性能优化，以及开发体验优化

然后，umi 和 roadhog 共用同一个底层 [af-webpack](https://github.com/umijs/umi/tree/master/packages/af-webpack)，他们在功能上有一定重叠，可以说 umi 包含 roadhog，react 项目我会倾向于推荐用 umi。
