### ISSUE TITLE
umi-request设置timeout后，浏览器initial Connection到1分钟时自动停止请求

### ISSUE THREAD

**Issue by CodingOnStar** [umijs/umi#8204]
设置了10分钟的timeout，但浏览器请求在Initial connection到1分钟时，请求自动断开了
<img width="1788" alt="截屏2022-06-23 22 19 46" src="https://user-images.githubusercontent.com/25198901/175322803-f37cd590-c6c0-4e8f-b553-c65b7919c8fd.png">
浏览器：chrome 版本 102.0.5005.115（正式版本） (x86_64)

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
