### ISSUE TITLE
umi4找不到Prompt及react-helmet

### ISSUE THREAD

**Issue by pai16858** [umijs/umi#8206]
umi4找不到Prompt及react-helmet

**Comment by sorrycc** [comment]
Prompt 没了，参考 react-router 6 的升级文档；react-helmet 自己依赖吧；其他问题请单独提 issue，同时给最简复现。

---

由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

**Comment by leohxj** [comment]
这些代码层面需要的变动, 可以补充到 https://umijs.org/docs/introduce/upgrade-to-umi-4 文档中.
