### ISSUE TITLE
umi4 4.0.1版本，没有setCreateHistoryOptions方法

### ISSUE THREAD

**Issue by liangskyli** [umijs/umi#8207]
umi4 4.0.1版本，没有setCreateHistoryOptions方法，如何在运行时修改子应用的路由前缀？
<img width="800" alt="image" src="https://user-images.githubusercontent.com/31531283/175332606-cbef2d06-cb00-47eb-b1a2-e6959c251215.png">

**Comment by feibi** [comment]
是的，也没有`MicroAppWithMemoHistory`的实现

**Comment by liangskyli** [comment]
4.0.5版本还是没有setCreateHistoryOptions方法

**Comment by xierenyuan** [comment]
> 4.0.5版本还是没有setCreateHistoryOptions方法

目前没有 setCreateHistoryOptions 方法 如果需要修改话 可以参考 https://github.com/umijs/umi/blob/master/packages/plugins/libs/qiankun/slave/lifecycles.ts#L102 这使用 modifyContextOpts api 进行修改

**Comment by liangskyli** [comment]
> > 4.0.5版本还是没有setCreateHistoryOptions方法
> 
> 目前没有 setCreateHistoryOptions 方法 如果需要修改话 可以参考 https://github.com/umijs/umi/blob/master/packages/plugins/libs/qiankun/slave/lifecycles.ts#L102 这使用 modifyContextOpts api 进行修改

如何使用：主应用里props加history参数配置？不能在主应用处理，需要子应用处理

**Comment by liangskyli** [comment]
> > 4.0.5版本还是没有setCreateHistoryOptions方法
> 
> 目前没有 setCreateHistoryOptions 方法 如果需要修改话 可以参考 https://github.com/umijs/umi/blob/master/packages/plugins/libs/qiankun/slave/lifecycles.ts#L102 这使用 modifyContextOpts api 进行修改

还是有问题4.0.7版本，按这个参考 的也不行

**Comment by liangskyli** [comment]
下面代码加一行才可以。
```ts
const context = {
        routes,
        routeComponents,
        pluginManager,
        rootElement: contextOpts.rootElement || document.getElementById('root-zxkp'),
        publicPath,
        runtimePublicPath,
        history: createHistory({
          type: contextOpts.historyType || 'browser',
          basename,
          ...contextOpts.historyOpts,
        }),
        basename,
        // 下面代码加一行才可以。
        ...contextOpts.historyOpts,
      };
```

**Comment by xoptimal** [comment]
> 

请问你这块是怎么写的, 可以提供下较为完整的部分了,  contextOpts 怎么声明的, context 在哪里创建的 ...  so thanks @liangskyli  @xierenyuan

**Comment by liangskyli** [comment]
目前代码不支持，这个功能还是没有，你再提个bug吧！





------------------ 原始邮件 ------------------
发件人: Freddie ***@***.***&gt;
发送时间: 2022年8月2日 00:42
收件人: umijs/umi ***@***.***&gt;
抄送: liangsky ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [umijs/umi] umi4 4.0.1版本，没有setCreateHistoryOptions方法 (Issue #8207)

**Comment by qingzhoufeihu** [comment]
> ```ts
> history: createHistory({
> ```

// 子应用
`export const qiankun = {
  async mount(props: any) {
    props.base = 路径前缀;
  },
};`

**Comment by zhoukai91** [comment]
// 可以在子应用qiankun导出的生命周期，直接运行时修改history类型
```
async mount(props: QianKunProps) {
    props.base = 'baseUrl'
    props.history = 'memory';
}
```
