### ISSUE TITLE
访问mfsu文档页面空白

### ISSUE THREAD

**Issue by acfasj** [umijs/umi#8213]
https://umijs.org/zh-CN/docs/mfsu
![image](https://user-images.githubusercontent.com/20757983/175447751-75bf6d7d-bd76-4e18-9d1e-d116ff64e680.png)

**Comment by luopc1218** [comment]
感觉应该是崩了

**Comment by acfasj** [comment]
> 感觉应该是崩了

控制台没输出错误, 感觉像后续操作没执行

**Comment by xierenyuan** [comment]
切到v4 后文档有调整, 访问v3 的话 需要先访问这个地址 https://v3.umijs.org/zh-CN/docs/mfsu
