### ISSUE TITLE
Questions about umi development documentation

### ISSUE THREAD

**Issue by 1996zzl** [umijs/umi#8214]
Sorry to bother you, I encountered a problem when I was developing, that is, the document could not be opened, such as https://umijs.org/zh-CN/plugins/plugin-layout, https://umijs.org/zh- CN/plugins/plugin-initial-state, it seems a little unfriendly, I hope it can be maintained and look forward to your reply.

**Comment by xierenyuan** [comment]
may need to visit https://v3.umijs.org/zh-CN/plugins/plugin-layout 
https://v3.umijs.org/zh-CN/plugins/plugin-initial-state
