### ISSUE TITLE
umi4, layout plugin 导致 antd 的样式 导入了两次

### ISSUE THREAD

**Issue by lovelyyl** [umijs/umi#8217]
umi4, layout plugin 导致 antd 的样式 导入了两次

![image](https://user-images.githubusercontent.com/45654799/175456305-6a958a24-e0e6-49ed-903f-84900782ed70.png)

**Comment by fz6m** [comment]
这个 [ default.less ](https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less) 里只有 less 变量，没有样式。

**Comment by lovelyyl** [comment]
那应该是哪个库有点问题，构建的样式里，相同的代码有两份
![image](https://user-images.githubusercontent.com/45654799/175471179-b973a27c-da7c-4f80-a0e0-c3778f14f481.png)

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
