### ISSUE TITLE
umi debugger进入断点之后，显示的却是同名组件的less文件

### ISSUE THREAD

**Issue by ohgod1992** [umijs/umi#8220]
![image](https://user-images.githubusercontent.com/33645745/175472656-3896b51e-fa3f-49e5-b396-eb85b67c08f5.png)

**Comment by ohgod1992** [comment]
![image](https://user-images.githubusercontent.com/33645745/175473705-9a0a8b07-352e-4749-93c0-2c825c2782ae.png)

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
