### ISSUE TITLE
There is problems with the umijs documentation description without both options when creating projects through scaffolding

### ISSUE THREAD

**Issue by xiaoqiao112** [umijs/umi#8221]

**Comment by stormslowly** [comment]
i tried to use create-umi  cli to create  empty project.
there  are steps prompting to select package manager and npm registry respectively.
Could you plz provide the cli you use or check  the verion of create-umi by `create-umi --version` first ？

here is my cli output
```bash
# create-umi@4.0.0-canary.20220624.1@local

✔ Pick Umi App Template › Ant Design Pro
? Pick Npm Client › - Use arrow-keys. Return to submit.
    npm
    cnpm
    tnpm
    yarn
❯   pnpm
```

last but not least，i think we can talk in 中文。
