### ISSUE TITLE
umi4 配置dva失效如何解决

### ISSUE THREAD

**Issue by chengbenchao** [umijs/umi#8227]

**Comment by xierenyuan** [comment]
有配置 `dva: {}` 启用吗？ 具体可以看这里 https://umijs.org/docs/max/dva  如果还没有解决, 请提供复现demo

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
