### ISSUE TITLE
QianKun插件与SSR功能不能并存

### ISSUE THREAD

**Issue by bailee2cn** [umijs/umi#8238]
从3.0开始就不能并存，很希望能用UMI来做前端中后台，同时，也想用来做前端SEO页面展示。

如果在config.ts中同时配置qiankun与ssr，在编译时提示：ReferenceError: window is not defined

**Comment by sorrycc** [comment]
是不能并存的，分两个项目吧。

**Comment by bailee2cn** [comment]
> 是不能并存的，分两个项目吧。

好的，谢谢兄弟了！
