### ISSUE TITLE
[Bug] 脚手架初始化的Vue Simple App模版启动白屏

### ISSUE THREAD

**Issue by Miller-Wang** [umijs/umi#8239]
### 环境
- **Umi Version**: v4.0.1
- **Node Version**: v14.18.1
- **Platform**: MacOS 12.0
- **pnpm**: v6.32.3
### 复现步骤
- 1. 执行 `pnpm dlx create-umi@latest`命令
- 2. 选择`Vue Simple App`模版
- 3. 执行 `npm run start` 命令

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/62501739/175554569-f073ebe3-bae2-4927-8547-ba9e13a79f61.png">

### 在`.umirc.ts`中配置`vite`后执行报错
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/62501739/175554904-01137da9-ad12-47b6-aae4-097914b807d6.png">

**Comment by xierenyuan** [comment]
使用这个版本试试 `4.0.0-canary.20220624.1`

**Comment by xierenyuan** [comment]
> `src/.umi/core/route.tsx` 文件 <img alt="image" width="1009" src="https://user-images.githubusercontent.com/62501739/175561612-31b32f4d-04c1-4d40-ab3a-c14e92ecd184.png"> 生成的路由文件还是用React方式加载的，把`React.lazy`去掉就好了
4.0.0-canary.20220624.1 这个版本修复了, 后续会补齐e2e 规避这个问题
