### ISSUE TITLE
[Bug] src/plugin.ts not used, plugin.ts used instead

### ISSUE THREAD

**Issue by lilbumblebear** [umijs/umi#8240]
## What happens?

When I have plugin.ts located in src/ directory, it is not applied.  If I move the file to projectroot/plugin.ts, it applies.

## Mini Showcase Repository(REQUIRED)

WORKING ON THIS

## How To Reproduce

**Steps to Reproduce**
1. Create a minimal plugin.ts file in projectroot/src/plugin.ts
```
//plugin.ts
import { IApi } from 'umi';
export default (api: IApi) => {
    api.addHTMLHeadScripts(() => `console.log('I am in HTML-head')`)
};

```
2. Build

**Expected behavior** 
Either update the documentation [here](https://umijs.org/docs/guides/directory-structure#plugints) so that plugin.ts is not listed under src/ OR the source code should look for plugin.ts within the projectroot/src/ directory. 

## Context

- **Umi Version**: 4.0.1
- **Node Version**: 16.15.1
- **Platform**: linux

**Comment by sorrycc** [comment]
It's the problem of documentation.
