### ISSUE TITLE
[Bug] 用脚手架创建的 umi4 ant design pro 无法启动

### ISSUE THREAD

**Issue by yuantongkang** [umijs/umi#8245]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your 

用脚手架创建 ant design pro 项目，启动 vite选项 ，没有其余配置

## How To Reproduce

用脚手架创建 ant design pro 项目，启动 vite选项 ，没有其余配置

启动访问页面

![image](https://user-images.githubusercontent.com/20579561/175753913-eceda03f-bbaa-41c2-b4a2-4234c2974099.png)

## Context

- **Umi Version**: 4
- **Node Version**: 16
- **Platform**: windows

**Comment by yuantongkang** [comment]
发现内存占用也非常高

**Comment by xierenyuan** [comment]
未复现 你要不使用新版本在试试

**Comment by yuantongkang** [comment]
> 未复现 你要不使用新版本在试试

控制台的输出和这个 issue #8291  一样

**Comment by sorrycc** [comment]
重复问题，在 https://github.com/umijs/umi/issues/8291 跟进。
