### ISSUE TITLE
[Bug] umi4 使用tailwind生成器生成配置后，max build报错

### ISSUE THREAD

**Issue by CaanDoll** [umijs/umi#8246]
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/23540471/175760680-b3afe8c5-db2f-4b15-b49e-5fee01527c48.png">

umi.ts这行
<img width="894" alt="image" src="https://user-images.githubusercontent.com/23540471/175760691-8d362632-abca-43dc-b41b-e3fea6e03fc5.png">

实际上此文件是已经生成在.umi-production里了
<img width="321" alt="image" src="https://user-images.githubusercontent.com/23540471/175760699-a20f8c90-2b4f-47ca-b7bb-58a3749acf4b.png">

**Comment by CaanDoll** [comment]
还有就是umi.ts里为什么不直接这样生成呢
```ts
import './plugin-tailwindcss/tailwind.css';
```

**Comment by fz6m** [comment]
升级到 `4.0.2` ，修复了

**Comment by CaanDoll** [comment]
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/23540471/175844226-225a4e9e-220e-4ae9-9471-69c8f8841506.png">
升级4.0.2之后，dev就直接报错了

**Comment by fz6m** [comment]
你这还是  `v4.0.1` ，看第一行版本提示。

```bash
  # 删除 node_modules
  rm -rf ./node_modules
  # 重新安装依赖
```

**Comment by CaanDoll** [comment]
升成4.0.2之后 不报错了 但是直接tailwind就不生效了。。

**Comment by Johnnnnboy** [comment]
umi4 antd pro 安装tailwind  git commit的时候报错 Unexpected unknown at-rule "@tailwind"，这个要怎么解决呢？

**Comment by fz6m** [comment]
可以参考一下 [这个文章](https://scottspence.com/posts/stylelint-configuration-for-tailwindcss) ，给 stylelint 配置忽略一下 tailwind 的 at-rule 。
