### ISSUE TITLE
[Bug] umi4 没有umi3的chunks配置项

### ISSUE THREAD

**Issue by liangskyli** [umijs/umi#8249]
## What happens?
umi3升级umi4,chunks配置项没有了，现在有其它的配置吗？

<img width="841" alt="image" src="https://user-images.githubusercontent.com/31531283/175765016-8a345752-b46f-4388-876b-8de01ed8a2e1.png">

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:4.0.1
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
umi4 默认按页拆包，不需要分包了。

**Comment by liangskyli** [comment]
哦，我看打包生成的文件都是数字开头的，这个能配置路由路径开头或文件名开头的吗？哪个页面的大包产物不好qu fen区分。
<img width="960" alt="image" src="https://user-images.githubusercontent.com/31531283/175765684-4b9cd052-ea37-4d7e-a061-d5d7c7afc21f.png">

**Comment by fz6m** [comment]
<img src='https://user-images.githubusercontent.com/59400654/175765862-c1798b88-94a4-4cc8-8903-607f9d22f260.png' width='700' />

这有映射关系。

**Comment by liangskyli** [comment]
是，线上只有文件名了，不知道对应哪个页面的文件

**Comment by liangskyli** [comment]
看起来是按routes里的配置顺序，如果每次构建都按这个顺序就可以了，这个bug关了，谢谢！

**Comment by nisnaker** [comment]
> umi4 默认按页拆包，不需要分包了。

还是想打包成一个 umi.js ，请问有办法改默认配置吗？

**Comment by wenlei0617** [comment]
> umi4 默认按页拆包，不需要分包了。

感觉需不需要分包是由开发者决定的，现在不是不需要分包，而是开发者不能自定义分包。
