### ISSUE TITLE
[Bug]  GET http://127.0.0.1:8000/%3Canonymous%3E 404 (Not Found)

### ISSUE THREAD

**Issue by kailong321200875** [umijs/umi#8253]
## What happens?
通过官方工具创建项目，选择  Ant Design Pro，之后启动，控制台就会一直报404，没有做任何更改
![image](https://user-images.githubusercontent.com/32283845/175800991-350023d3-cf63-418d-a078-d5167a00888a.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0.2
- **Node Version**: 16.0.0
- **Platform**:

**Comment by stormslowly** [comment]
提供最小复现 你可以把创建的项目打包上传上来看看

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
