### ISSUE TITLE
[Bug] Umi4.0 useSearchParams, searchParams未取到值

### ISSUE THREAD

**Issue by jassonxian** [umijs/umi#8255]
## What happens?
![image](https://user-images.githubusercontent.com/21199561/175849802-cd1f4591-6ab8-4a54-9cc2-b0ce17847961.png)

## Context

- **Umi Version**: 4.0.0
- **Node Version**: v14.18.1
- **Platform**:MacOs

**Comment by sorrycc** [comment]
不是有 search 吗？怎么叫未取到值？

**Comment by jassonxian** [comment]
> 
![image](https://user-images.githubusercontent.com/21199561/175856589-90e5a644-0e8a-4bb3-a307-fc40e7e0779c.png)
![image](https://user-images.githubusercontent.com/21199561/175856639-097a75ec-1d39-4001-948c-8e6836a99994.png)
search是location打印出来的

**Comment by jassonxian** [comment]
文档又更新了吗，刚才看的还没有呢
![image](https://user-images.githubusercontent.com/21199561/175857211-1cbb8297-9fb2-47dc-80dd-2ba97499dc80.png)
我自己close吧
