### ISSUE TITLE
[Bug] 存在直接依赖prettier plugin

### ISSUE THREAD

**Issue by zzzgydi** [umijs/umi#8256]
## What happens?

![image](https://user-images.githubusercontent.com/27361820/175872066-3aef5943-188e-4699-a0de-3338132abf27.png)

如图，umi4直接依赖了这两个prettier插件，又因为prettier默认会自动导入符合规则的plugin，[文档](https://prettier.io/docs/en/plugins.html#using-plugins)。因此，除非用户设置`pluginSearchDirs: false`，否则均有可能受此插件影响。

## Context

- **Umi Version**: 4.0.2
- **Node Version**: 16.15.0
- **Platform**: Windows 10

**Comment by sorrycc** [comment]
by design，解决方案是「使用 pnpm 避免幽灵依赖」或者设置「pluginSearchDirs: false」。
