### ISSUE TITLE
[Feature Request] config recommend

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi#8260]
## Background

现在的 tsconfig 有些过于复杂了，特别对于本身并不太会的 ts 的朋友来说，更是如此。
从反馈上来看，不少同学都是在不同的项目之间拷贝。

(这里我不太理解，为什么他们不用 create 来新建项目)

然后 umi 和 father 项目也会出现互相拷贝 tsconfig 的情况，显然这会导致错误。

现在 umi 提供了 `g ts` 的能力，用于新建 tsconfig 文件，我想能不能做的更多点。

当我怀疑我现在项目的 tsconfig 可能存在错误时，我能不能执行某个命令，来矫正它。

类似，猜你喜欢，比如识别到是一个 umi 项目，然后推荐出最佳实践中的 tsconfig 配置。

## Proposal

1、执行 umi config recommend 

2、选择 tsconfig，umi config，prettier config

3、选择是否重写当前配置文件

4、如果选择不重写，那就在当前配置的同级目录新建 xxx-recommend 文件

**Comment by sorrycc** [comment]
tsconfig 和 prettier config 不是在 umi 里都有内置了吗？
