### ISSUE TITLE
[Bug] umi4 plugin-locale is no export getIntl 插件没有导出getIntl函数，无法在一个ts文件中的独立函数中如何使用umi的useIntl来实现国际化

### ISSUE THREAD

**Issue by sogud** [umijs/umi#8263]
## What happens?
需要在一个ts文件中的独立函数中如何使用umi的useIntl来实现国际化
[https://github.com/umijs/umi/issues/5555](https://github.com/umijs/umi/issues/5555)

umi4 plugin-locale 插件没有导出getIntl函数

umi3 版本可以
![image](https://user-images.githubusercontent.com/20726419/175917450-5550b835-020b-4985-b414-2e35220c4b03.png)

## Context

- **Umi Version**: 4.0.2
- **Node Version**:4.0.2
- **Platform**: macos

**Comment by z-pfei** [comment]
请问能用了吗，我的项目一调用getIntl就报错

**Comment by fz6m** [comment]
升一下最新版本看看，不能用的话给一个最小复现看看

**Comment by z-pfei** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
