### ISSUE TITLE
[Bug] Umi4: webstorm 显示【在未导入 React 的情况下使用 JSX】

### ISSUE THREAD

**Issue by Lpbzzz** [umijs/umi#8265]
## What happens?
webstorm 显示【在未导入 React 的情况下使用 JSX】

## Mini Showcase Repository(REQUIRED)

新初始化umi4项目即可
![webstorm](https://user-images.githubusercontent.com/28721487/175933404-1fa5c766-15d9-40ae-bdad-c1d60df8a70c.jpg)

## How To Reproduce

应该是要修改tsconfig配置或者eslint里的内容吧

## Context

- **Umi Version**:4
- **Node Version**:LTS
- **Platform**:Macos

**Comment by sorrycc** [comment]
tsconfig 配置的 `"jsx": "react-jsx"`，无需引入 react，这应该是 webstorm 的误报，可忽略。

**Comment by alecthw** [comment]
首先这个警告是webstorm自己报的，和eslint无关。这个问题是由于package json里没有安装版本号大于17的react依赖，如果安装了webstorm会自动禁用。但是我安装17.0.2的react依赖后，运行报错，贼尴尬😅

**Comment by Lpbzzz** [comment]
> 首先这个警告是webstorm自己报的，和eslint无关。这个问题是由于package json里没有安装版本号大于17的react依赖，如果安装了webstorm会自动禁用。但是我安装17.0.2的react依赖后，运行报错，贼尴尬😅

哈哈 谢谢提醒 原来是umi把所有的依赖都集中了。我手动安装了react倒是没报错
