### ISSUE TITLE
[Bug] 配置 navTheme 为 'dark' 不生效

### ISSUE THREAD

**Issue by linjackson78** [umijs/umi#8268]
## What happens?

通过 `npx umi-create@latest` 创建 antd-pro 模版的项目，仅仅是在 layout 配置里加了一行 `navTheme: 'dark'` 的配置，配置改动并没有生效。

## Mini Showcase Repository(REQUIRED)

https://github.com/linjackson78/umi-issue-showcase

## How To Reproduce

打开首页，即可看到左侧菜单没有变成暗色主题

截图见下：
![image](https://user-images.githubusercontent.com/8870680/175947146-07994ffb-7a0b-476d-8879-176c3c5ffcdb.png)

## Context

-  @umijs/max: 4.0.1
- **Node Version**: v16.15.1
- **Platform**: MacOS 12.1
- **Chrome**: 103.0.5060.53（正式版本） (arm64)

**Comment by hanzebang** [comment]
@ant-design/pro-layout v7(目前在beta21) 不再支持 `navTheme: 'dark'` 属性配置，自定义主题颜色参考：https://next-procomponents.ant.design/components/layout#%E9%80%9A%E8%BF%87-token-%E4%BF%AE%E6%94%B9%E6%A0%B7%E5%BC%8F

**Comment by linjackson78** [comment]
按照 umi 官方文档创建的新项目，竟然依赖的是一个 beta 版本的 pro-layout，导致按 pro-layout 正式版本的文档配置的选项无法生效，建议更新官网文档，否则体验太差，根本不敢用 umi 。

**Comment by georgezouq** [comment]
> 这是 pro 团队的考虑，需要 navTheme 请切换到 @ant-design/pro-layout@6 。

@sorrycc 本地安装 @ant-design/pro-layout@6，navTheme: 'dark' 还是无效？如何切换？？
