### ISSUE TITLE
[Feature Request] @umijs/lint 改成默认不启用  --quiet

### ISSUE THREAD

**Issue by PeachScript** [umijs/umi#8269]
## Background

ESLint 在 `--quiet` 时仅输出 Error、同时也不会对 Warning 做自动修复，但部分用户可能需要此功能，而 `@umijs/lint` 是强制开启 `--quiet` 的。

## Proposal

支持 `--no-quiet` 参数，禁用 `--quiet`

**Comment by xiaohuoni** [comment]
友情提示：`--no-quiet` 会被转成 `quiet: false`

**Comment by zzcan** [comment]
认领

**Comment by PeachScript** [comment]
这个问题和 @stormslowly 讨论了下，和社区反着来会造成更多的答疑，比如：

1. 用户配了 `warn` 规则，会奇怪『怎么没反应』
2. 用户执行 `--fix` 也不会修复 `warn` 规则，会奇怪『怎么也不修复』

加上 Umi 内置规则全部都是 `error`，没必要再默认 `-quiet` 来隐藏原本就不存在的 `warn` 了；趁着还没发版，我倾向于把 `--no-quiet` 改成 `--quiet` 了， @zzcan @xiaohuoni 两位也看看
