### ISSUE TITLE
[Bug] windows开启https后，启动报错

### ISSUE THREAD

**Issue by CaanDoll** [umijs/umi#8273]
![image](https://user-images.githubusercontent.com/23540471/176076655-fce24fd5-5294-4d1a-8c2f-b497796005d0.png)
这里ws先使用再实例了
https://github.com/umijs/umi/pull/8271 修改代码顺序后就可以了

**Comment by ClenLu** [comment]
mac 也有同样的问题吧  新创建的项目也开启不了

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/pull/9029
