### ISSUE TITLE
[Bug] umijs/max 布局与菜单 页面中的 ant-page-header 无法隐藏

### ISSUE THREAD

**Issue by zhouzyc** [umijs/umi#8275]
## What happens?

umi3项目升级到umi4 并且使用了umijs/max后，登录页样式有问题，在文档中没找到相关隐藏ant-page-header的方法
![1656388170380](https://user-images.githubusercontent.com/18420689/176087988-b69378a3-7ff5-4888-a88d-397542239b64.jpg)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by ClenLu** [comment]
// 不展示顶栏
    headerRender: false,
    // 不展示页脚
    footerRender: false,
    // 不展示菜单
    menuRender: false,
    // 不展示菜单顶栏
    menuHeaderRender: false,

**Comment by zhouzyc** [comment]
> // 不展示顶栏 headerRender: false, // 不展示页脚 footerRender: false, // 不展示菜单 menuRender: false, // 不展示菜单顶栏 menuHeaderRender: false,
<img width="486" alt="image" src="https://user-images.githubusercontent.com/18420689/176094423-905ca68b-e1ca-4918-be86-e144436df256.png">
我已经配置了这个还是会有

**Comment by xiaohuoni** [comment]
不是配置 layout:false 吗？

**Comment by zhouzyc** [comment]
> 不是配置 layout:false 吗？

config/config.ts 文件下配置的是
layout: {
    title: "Ant Design11",
    locale: false,
},

**Comment by zhouzyc** [comment]
找到原因了，项目以前有个src/layouts/index.tsx 文件，之前版本是
{
    path: "/",
    component: "@/layouts/index",
    flatMenu: true, //隐藏父级 子集上提
    routes: routesMenu,
  }
这样来使用，现在约定式执行了一次，可能是自己用的有问题
