### ISSUE TITLE
umi4升级  Outlet问题

### ISSUE THREAD

**Issue by jiasijiamn** [umijs/umi#8285]
使用Prolayout和配置式嵌套路由，没有嵌套路由的页面可以正常展示，有嵌套路由的页面点击菜单栏就会报错
![image](https://user-images.githubusercontent.com/70948246/176183246-10179809-0e27-40cf-9c6b-eeb4635a71f0.png)

![image](https://user-images.githubusercontent.com/70948246/176182797-d9d3282d-8732-4165-9e2e-88a728d7a6a6.png)
![image](https://user-images.githubusercontent.com/70948246/176183566-70ac38bf-e7fb-4430-ba8e-2806a583d39a.png)

react 版本16.8.6

**Comment by sorrycc** [comment]
感谢反馈。
