### ISSUE TITLE
[Bug] 模块“"umi"”没有导出的成员

### ISSUE THREAD

**Issue by wangzherlf** [umijs/umi#8286]
import { request, useRequest } from 'umi';
import type { RequestConfig } from 'umi';

使用umi官网脚手架搭建，umi官网上的两段示例都报错 提示模块“"umi"”没有导出的成员“request”

tsconfig也是脚手架默认配置的
"paths": {
      "@/*": ["src/*"],
      "@@/*": ["src/.umi/*"]
 },

- **Umi Version**: "@umijs/max": "^4.0.0",
- **Node Version**: v16.14.0
- **Platform**: macOS

**Comment by sorrycc** [comment]
使用 max 就从 @umijs/max 里 import，因为没有直接的 umi 依赖。

```
import { request } from '@umijs/max';
```

如果没能解决问题，请提交最简复现仓库。

---

由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

**Comment by mode365Dong** [comment]
我遇到了同样的问题。
解决方案：
`
import { defineConfig } from "umi";

export default defineConfig({
  routes: [
    { path: "/", component: "index" },
    { path: "/docs", component: "docs" },
  ],
  **request: {},**
  npmClient: "pnpm",
  tailwindcss: {},
  plugins: ["@umijs/plugins/dist/tailwindcss", "**@umijs/plugins/dist/request**"],
});

`

这样在app.ts中使用
`import type { RequestConfig } from "umi";`
就没有问题了。

umi3中关于request的文档就很乱，我在umi4的文档中学习request的相关知识，根据上下文很难解决问题，如果不是我预先了解tailwindcss，我可能要卡1个小时的学习时间。
