### ISSUE TITLE
[Bug] umi4 patchRoutes 无法使用

### ISSUE THREAD

**Issue by textqaz** [umijs/umi#8292]
## What happens?
umi4 patchRoutes 无法使用

## Mini Showcase Repository(REQUIRED)
使用官方示例 examples/max 项目
修改app.tsx 加入patchRoutes代码
![image](https://user-images.githubusercontent.com/16917336/176340209-e8972412-5218-481f-bdb0-97ad7b626708.png)

启动项目后报错

![image](https://user-images.githubusercontent.com/16917336/176340362-c0258c19-db36-4940-948d-d3468f247954.png)

## How To Reproduce

同上

## Context

- **Umi Version**: v4.0.0-canary.20220628.2
- **Node Version**: 16.3.0
- **Platform**: MacOS

**Comment by sorrycc** [comment]
改用 patchClientRoutes。

**Comment by fz6m** [comment]
```ts
import Page from '@/pages/Home/index'

export function patchClientRoutes({ routes }: any) {
  routes.unshift({
    path: '/foo',
    id: 'foo',
    element: <Page />
  });
}
```
