### ISSUE TITLE
umi4使用initialState插件报错

### ISSUE THREAD

**Issue by Aicmortal** [umijs/umi#8294]
### Discussed in https://github.com/umijs/umi/discussions/8288

<div type='discussions-op-text'>

<sup>Originally posted by **Aicmortal** June 29, 2022</sup>
# Umi4使用initialState插件报错
> 使用最新4.0.2版本,使用基础版本Umi,非Max,安装的是@umijs/plugins
### 配置文件如下
![截图_20220629095012](https://user-images.githubusercontent.com/16420004/176334377-bd26e8da-865d-47cd-b860-5316f050d15b.png)
### 启用initialState插件后报错如下,查看.umi目录确实没有生成插件
![微信截图_20220629094936](https://user-images.githubusercontent.com/16420004/176334605-72fcdb75-5af8-4dd2-ae22-8197b3adad80.png)

![微信截图_20220629094952](https://user-images.githubusercontent.com/16420004/176334619-21e51621-7887-49fb-9c31-ab8da2f43385.png)
### 只启用其他三个插件,.umi目录下会正常生成插件
![微信截图_20220629095208](https://user-images.githubusercontent.com/16420004/176334832-1163f5fc-065e-4c9d-92e6-e6aa577e495e.png)
</div>

**Comment by sorrycc** [comment]
umi 4 的插件都是配置开启的，需要在配置里加上 `initialState: {}`。

**Comment by Aicmortal** [comment]
> umi 4 的插件配置都是开启的，需要在配置里添加`initialState: {}`。

我配置了,但依旧报错

**Comment by WillCoco** [comment]
initial-state插件放到model插件前面🐸
