### ISSUE TITLE
[Bug] [umi3] Module not found: Error: Can't resolve '/data/data/dc-v3/dc-v3-fe-plus-build/src/pages/core/summary' in '/data/data/dc-v3/dc-v3-fe-plus-build/src/.umi-production/core'

### ISSUE THREAD

**Issue by Valar103769** [umijs/umi#8298]
```js
 yarn run build
 yarn run v1.21.0
 $ cross-env UPLOAD_SOURCE_MAP=yes  umi build
 Bundle with webpack 5...
 [info] [webpackbar] Compiling Webpack
 (node:65364) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors
 (Use `node --trace-deprecation ...` to show where the warning was created)
 (node:65364) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
 (node:65364) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
 Browserslist: caniuse-lite is outdated. Please run:
 npx browserslist@latest --update-db
 Why you should do it regularly:
 https://github.com/browserslist/browserslist#browsers-data-updating
 [success] [webpackbar] Webpack: Compiled with some errors in 51.53s
  ERROR  Failed to compile with 7 errors12:07:33 PM
  error  in ./src/.umi-production/core/routes.ts
 Module not found: Error: Can't resolve '/data/data/dc-v3/dc-v3-fe-plus-build/src/pages/core/summary' in '/data/data/dc-v3/dc-v3-fe-plus-build/src/.umi-production/core'
  error  in ./src/.umi-production/core/routes.ts
 Module not found: Error: Can't resolve '/data/data/dc-v3/dc-v3-fe-plus-build/src/pages/core/waterSummary' in '/data/data/dc-v3/dc-v3-fe-plus-build/src/.umi-production/core'
  error  in ./src/.umi-production/core/routes.ts
 Module not found: Error: Can't resolve '/data/data/dc-v3/dc-v3-fe-plus-build/src/pages/core/retentionAnalysis' in '/data/data/dc-v3/dc-v3-fe-plus-build/src/.umi-production/core'
  error  in ./src/.umi-production/core/routes.ts
 Module not found: Error: Can't resolve '/data/data/dc-v3/dc-v3-fe-plus-build/src/pages/core/ltvAnalysis' in '/data/data/dc-v3/dc-v3-fe-plus-build/src/.umi-production/core'
```

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

**Comment by Valar103769** [comment]
> 由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

build 报错,怎么给你重新,老哥

**Comment by dashengqi** [comment]
刺激，我也遇到类似的问题了，本地build是可以的，流水线就报错。
大小写也确认了，没有问题。。。

` ERROR  Failed to compile with 1 errors5:18:41 PM
 error  in ./src/.umi-production/core/routes.ts
Module not found: Error: Can't resolve '/home/gitlab-runner/builds/Nd4PX9pf/0/cloud/cloud-frontend/src/pages/admin/service/package/Customer/components/ReChargeRecord' in '/home/gitlab-runner/builds/Nd4PX9pf/0/cloud/cloud-frontend/src/.umi-production/core'`

**Comment by Valar103769** [comment]
> 刺激，我也遇到类似的问题了，本地build是可以的，流水线就报错。 大小写也确认了，没有问题。。。
> 
> 文件路径：src\pages\admin\service\package\Customer\components\RechargeRecord\index.tsx
> 
> 报错信息： ` ERROR Failed to compile with 1 errors5:18:41 PM error in ./src/.umi-production/core/routes.ts Module not found: Error: Can't resolve '/home/gitlab-runner/builds/Nd4PX9pf/0/cloud/cloud-frontend/src/pages/admin/service/package/Customer/components/ReChargeRecord' in '/home/gitlab-runner/builds/Nd4PX9pf/0/cloud/cloud-frontend/src/.umi-production/core'`

别用封装的,特别是kpi项目

**Comment by drizzlesconsin** [comment]
这个问题先排查 `./src/.umi-production/core/routes.ts`

把报错的路由先屏蔽掉，再 build, 如果没问题再一一排除找到问题

有没有可能 build 和 dev 用到的模块引用不一样，e.g build 用的是 cdn, dev 是 npm .... 或者版本不同

这种问题属于业务上的，还很容易排查的

```bash
 error  in ./src/.umi-production/core/routes.ts
 Module not found: Error: Can't resolve '/data/data/dc-v3/dc-v3-fe-plus-build/src/pages/core/summary' in '/data/data/dc-v3/dc-v3-fe-plus-build/src/.umi-production/core'
  error  in ./src/.umi-production/core/routes.ts
```

**Comment by dashengqi** [comment]
> 

不要意思，我定位到问题。我是真瞎，就是大小写的问题。
不过打包确实慢，不知道有无优化方案？

**Comment by dashengqi** [comment]
> > 刺激，我也遇到类似的问题了，本地build是可以的，流水线就报错。 大小写也确认了，没有问题。。。
> > 文件路径：src\pages\admin\service\package\Customer\components\RechargeRecord\index.tsx
> > 报错信息： ` ERROR Failed to compile with 1 errors5:18:41 PM error in ./src/.umi-production/core/routes.ts Module not found: Error: Can't resolve '/home/gitlab-runner/builds/Nd4PX9pf/0/cloud/cloud-frontend/src/pages/admin/service/package/Customer/components/ReChargeRecord' in '/home/gitlab-runner/builds/Nd4PX9pf/0/cloud/cloud-frontend/src/.umi-production/core'`
> 
> 别用封装的,特别是kpi项目,自己用vite或者cra从0写 比想象的快

我是真瞎，RechargeRecord!==ReChargeRecord..就是大小写的问题。不过打包确实挺慢的，不知有没有优化方案。
