### ISSUE TITLE
[Bug] @ant-design/pro-cli umi@4版本启动报错 useKeepOutlets is not function

### ISSUE THREAD

**Issue by yq756530939** [umijs/umi#8305]
使用 @ant-design/pro-cli 脚手架创建的umi@4项目
npm安装所有依赖后 启动报错
`TypeError: (0 , _umijs_max__WEBPACK_IMPORTED_MODULE_0__.useKeepOutlets) is not a function
Layout
.ant-design-pro/src/.umi/plugin-maxtabs/Layout.tsx:7
   4 | import { useKeepOutlets } from '@umijs/max';
   5 | 
   6 |       const Layout = () => {
>  7 |         const element = useKeepOutlets();
   8 |         return <>{element}</>;
   9 |       };
  10 | `

**Comment by xiaohuoni** [comment]
重新建一个项目应该就好了，或者升级 umi-preset-pro 的版本

**Comment by yq756530939** [comment]
今天重新建一个项目确实是可以了，现在src/.umi下没有生成plugin-maxtabs这个目录了
