### ISSUE TITLE
pnpm install deps error

### ISSUE THREAD

**Issue by saxon-y** [umijs/umi#8307]
## Get an error when install deps by pnpm
<img width="922" alt="image" src="https://user-images.githubusercontent.com/49136621/176378177-30853788-32b8-4338-8c57-976d33eff738.png">

## Context

- **Umi Version**:the lastest code of master branch
- **Node Version**:v16.14.2
- **Pnpm Version**:7.4.0

**Comment by sorrycc** [comment]
找了个空目录试也不能复现问题。请检查本地环境或者深入排查下，理论上更多是本地环境的问题，因为 CI 都能过。
