### ISSUE TITLE
[Bug] 开启mfsu后报错export 'default' (imported as '_') was not found in 'react-dnd'

### ISSUE THREAD

**Issue by PineSongCN** [umijs/umi#8310]
## What happens?

开启mfsu后报错export 'default' (imported as '_') was not found in 'react-dnd'
![image](https://user-images.githubusercontent.com/39976617/176419050-6b0d8d22-fb65-4af0-a834-07ff6e8744b6.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub.

 [最小重现](https://github.com/PineSongCN/demo)

## How To Reproduce

1. yarn
2. yarn start
3. 报错

## Context

- **Umi Version**: 3.5.20
- **Node Version**:14.18.2
- **Platform**:mac/windows

**Comment by hughes-hc** [comment]
兄弟，解决了吗，我也遇到了类似的问题

**Comment by PineSongCN** [comment]
> 兄弟，解决了吗，我也遇到了类似的问题

没有，现在用了next框架

**Comment by stormslowly** [comment]
升级到 bigfish 4 试试

**Comment by hughes-hc** [comment]
> 

升级umi4了还是报错啊

**Comment by fz6m** [comment]
```ts
import * as dnd from 'react-dnd'

console.log(dnd)
```

我试了 umi4 是可以正常出值的。
