### ISSUE TITLE
[Bug] umijs/max layout开启后登录页面出现一闪而过的loading显示状态

### ISSUE THREAD

**Issue by zhouzyc** [umijs/umi#8315]
## What happens?

路由配置：
{
    path: "/login",
    component: "@/pages/login/index",
    headerRender: false,
    footerRender: false,
    menuRender: false
  },
在加载过过程中会出现loading闪过
<img width="1673" alt="WX20220628-152459@2x" src="https://user-images.githubusercontent.com/18420689/176120007-22aa81fd-7a93-4d86-a500-3efd68407d1f.png">
然后正常显示登录页面
<img width="1669" alt="WX20220628-152511@2x" src="https://user-images.githubusercontent.com/18420689/176120114-ab39b155-a512-45c0-87c7-1c9f043f2f52.png">

## 复现demo

最小复现demo https://gitee.com/zyc1314/umi4.git

## 复现步骤

启动项目进入127.0.0.1:8000/login 页面，因为demo很小，速度很快，渲染过程中一闪而过

**Comment by sushi-su** [comment]
遇到同样的问题，窗口宽度小于 1920px 时能复现

**Comment by zjfresh** [comment]
边栏 render 改到 app.tsx 通过判断路径是否 /login 设为 false， location.path === '/login' ? false : undefined

**Comment by sorrycc** [comment]
复现 demo 无权限。

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

**Comment by drizzlesconsin** [comment]
确实会一闪而过，建议重新打开。
```ts
{
    name: 'Login',
    path: '/Login',
    component: './Login',
    headerRender: false,
    footerRender: false,
    menuRender: false
}
```
通过 Performance 的截图记录可以抓到
<img width="644" alt="image" src="https://user-images.githubusercontent.com/69514654/183307949-a79d3d7b-089b-445a-8a5e-9894e80f4156.png">

```bash
# 简单 DEMO 步骤
yarn create umi
yarn dev
```

楼上完全可以用 `layout: false` 替换：

```ts
headerRender: false,
footerRender: false,
menuRender: false
```

不过可能又会遇到另一个问题 https://github.com/umijs/umi/issues/8497

**Comment by drizzlesconsin** [comment]
https://pro.ant.design/zh-CN/docs/layout#%E8%8F%9C%E5%8D%95%E5%B1%95%E7%A4%BA
