### ISSUE TITLE
[qiankun]主应用是umi3，子应用umi4，找不到子应用的lifecycle function

### ISSUE THREAD

**Issue by asevenm** [umijs/umi#8318]
## What happens?
qiankun配置正常，但报如下错误：
![image](https://user-images.githubusercontent.com/22423693/176587687-29739f5f-c04c-40cd-bc7f-1df4aee181ec.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 子应用umi4, 主应用umi3
- **Node Version**: 16
- **Platform**: mac

**Comment by feibi** [comment]
增加个配置可解决
```tsx
export const qiankun={
  fetch: async (url: any) => {
    return window.fetch(url, {
      headers: {
        accept: 'text/html',
      },
    });
  }
}
```

**Comment by feibi** [comment]
> ```tsx
> fetch
> ```

fetch加在主应用里

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
