### ISSUE TITLE
建議：基於page component的全局layout系統

### ISSUE THREAD

**Issue by MengWeiChen** [umijs/umi#832]
### 缘起
目前的umi只有一個全局的layout，用起來比較麻煩一點，建議可以參考Nuxt.js的全局layout方式

### 注意点
參考Nuxt.js的做法，透過page component中的static property去決定layout，具體的作法可能會像這樣

```
// pages/login.js
const Login = () => <h1>Login component</h1>;
Login.layout = 'blank'
export default Login
```

或是

```
// pages/login.js

export default class Login extends Component {
  static layout = 'blank'

  render() {
    return (<h1>Login component</h1>)
  }
}

```

目錄結構
```
+ layouts
  - blank.js
  - default.js
```

比較要注意的有兩個部分：

1. HOC 可能會導致router無法順利取得component的layout property
2. 巢狀route要有後蓋前的全局layout特性

### 参考
[Nuxt.js layout](https://nuxtjs.org/api/pages-layout/)

**Comment by yutingzhao1991** [comment]
或者可以用现在的路由配置的方案： https://github.com/umijs/umi/blob/master/packages/umi-build-dev/src/routes/fixtures/file-config/c/c.js

```js
/*
layout: Blank
title:
  - c
  - d
 */
```

**Comment by wangxingkang** [comment]
比较支持类似nuxt.js类似的实现
