### ISSUE TITLE
umi4 public目录下的图片资源路径问题

### ISSUE THREAD

**Issue by zhangfinn** [umijs/umi#8321]
### Discussed in https://github.com/umijs/umi/discussions/8320

<div type='discussions-op-text'>

<sup>Originally posted by **zhangfinn** June 30, 2022</sup>
页面里好像不支持之前那种background-image: url(/xxxxxx.png)的写法。需要../../  有没有解决办法（之前页面里都是简写）</div>

**Comment by sorrycc** [comment]
重装下依赖，4.0.3 里修复了。
