### ISSUE TITLE
让 build 产物的 id 更有意义，参考 Umi 3

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#8324]
## 问题

现在的产物中包含大量「以数字命名」的文件，不好理解，也不方便定位问题。

## 解法

参考 umi 3 的实现，通过 `/* webpackChunkName */` 声明动态加载文件的名字，用比如 `p__foo.js` 的形式，p 表示 pages 目录。

规则是，

1、忽略 src 目录
2、pages 替换为 p
3、替换 / 为 __

比如：

1、src/pages/foo.ts 产物是 p__foo.js

**Comment by xierenyuan** [comment]
认领

**Comment by zhouzyc** [comment]
插眼

**Comment by huarse** [comment]
MARK
