### ISSUE TITLE
支持配置 cache directory，通过 config.cacheDirectoryPath，默认是 node_modules/.cache

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#8325]
## 问题

需求是在一个项目中同时启动多个 umi 实例，期望缓存是分离的。

## 解法

1、新增配置 `cacheDirectoryPath`，默认值和现在的保持一致 `node_modules/.cache`
2、记得用 path.resolve 处理一下，支持绝对路径
3、需要同时处理 webpack 和 mfsu 的缓存路径

**Comment by July-ing** [comment]
认领

**Comment by sorrycc** [comment]
@stormslowly 通过配置，用户有办法自行做区分的。
