### ISSUE TITLE
[Bug] qiankun子应用路由 *配置， 影响主应用和其他子应用

### ISSUE THREAD

**Issue by cuijiudai** [umijs/umi#8328]
如果A子应用路由配置了

```
   {
     path: '*',
     redirect: '/404',
     hidden: true
  },
```
在主应用访问A子应用后，再访问其他子应用或者主应用的路由，都会被重定向到A子应用的404页面。

- **Umi Version**:3.5.24
- **Node Version**:14
- **Platform**:mac os

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

**Comment by kukuyuhai** [comment]
@cuijiudai 遇到相同问题，主应用的umi/max插件，子应用是vue2项目，有解决方案吗？

**Comment by fz6m** [comment]
如果想高级自定义路由的行为，并且搭配微前端，使用 [`<MicroApp  />`](https://umijs.org/docs/max/micro-frontend#microapp--%E7%BB%84%E4%BB%B6%E5%BC%95%E5%85%A5%E5%AD%90%E5%BA%94%E7%94%A8) 在对应的路由手动渲染子应用即可，可以自行判断路径条件渲染等，不需要拘泥于路由表里的配置。
