### ISSUE TITLE
umi@4   设置layout siderWidth不生效 

### ISSUE THREAD

**Issue by yilin1013** [umijs/umi#8330]
.umi > plugin-layout>Lauout.tsx中siderWidth写死了256没有取自定义的siderWidth

**Comment by KiritoXF** [comment]
得在 `app.tsx` 的 layout 导出里配，以前是在 `config.ts` 里，现在好像改了

@umijs/max": "^4.0.4

**Comment by sorrycc** [comment]
写死的默认值，可以在 app.ts 里通过 export const layout 修改。
