### ISSUE TITLE
[Bug] connect exported from umi is underfined

### ISSUE THREAD

**Issue by LanJamRom** [umijs/umi#8332]
## What happens?

@umijs/max从4.0.0-rc22 升级到 4.0.3后出现：
![1656591910956](https://user-images.githubusercontent.com/41603622/176676798-d1a72349-3a1d-472f-af16-d034bb2e1c12.png)

`// import { connect } form '@umijs/max'`
`import { connect } from '@@/plugin-dva'`
目前通过从plugin-dva引入connect，项目正常运行

## Context

- **Umi Version**: 4.0.3
- **Node Version**: 16.12.0
- **Platform**: Windows

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

**Comment by kuake** [comment]
确实必现：
新建一个工程：
运行命令：npx create-umi@latest
Need to install the following packages:
  create-umi@latest
Ok to proceed? (y) y
✔ Pick Umi App Template › Ant Design Pro
✔ Pick Npm Client › yarn
✔ Pick Npm Registry › taobao

yarn dev

随便比如在home页面里面 import { connect } from '@umijs/max';
模块“"@umijs/max"”没有导出的成员“connect”。ts(2305)

**Comment by MohitGevaria** [comment]
Did you find any soln for this?
