### ISSUE TITLE
umi4.0 开启mfsu 引用本地组件库， 使用// @ts-ignore报错

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#8334]
### Discussed in https://github.com/umijs/umi/discussions/8333

<div type='discussions-op-text'>

<sup>Originally posted by **ksh033** June 30, 2022</sup>
引用本地组件库，组件库使用了
问题1
// @ts-ignore
import { history } from 'umi';
报错 Uncaught (in promise) TypeError: __webpack_require__.nmd is not a function，
问题2

显目目录
packages 
---------- web
----------clientplugin
web依赖clientplugin

本地组件clientplugin  watch编译，web项目不会编译更新

demo地址:https://github.com/ksh033/umi-test.git
</div>

**Comment by ksh033** [comment]
可能描述有点问题，应该是只要组件库引用umi开启mfsu 就会报错。感觉webpack_require的作用域变了

**Comment by sorrycc** [comment]
组件库不能依赖 umi，依赖了就关闭 mfsu 吧，mfsu 不支持这个场景。
