### ISSUE TITLE
[Bug]  umi3升级umi4报错，/@umijs/plugins/dist/access.js failed, since Cannot find module 'umi/plugin-utils'

### ISSUE THREAD

**Issue by 1587315093** [umijs/umi#8342]
老项目是Umi3，再修改script命令和依赖包后，npm i在执行到max setup后报错，
![image](https://user-images.githubusercontent.com/77056991/176842572-3bee4794-17d0-40e9-a52c-0c2ccdbf88d0.png)
以下是项目用到的依赖
以下是config配置
![image](https://user-images.githubusercontent.com/77056991/176843121-eeec3971-8b63-4f19-8fa1-f6b96cee1b24.png)

**Comment by 1587315093** [comment]
以下是pacckage.json
![image](https://user-images.githubusercontent.com/77056991/176843368-2b786c21-6db6-41b8-aeb4-252687fca07e.png)

**Comment by stormslowly** [comment]
你好 npm 版本 多少啊 ~   我尝试复现 我有报错

**Comment by 1587315093** [comment]
6.14.16哦
![image](https://user-images.githubusercontent.com/77056991/176851210-1f8cfbde-c312-4452-bf5e-30dcafb80438.png)


> 你好 npm 版本 多少啊 ~ 我尝试复现 我有报错
> 
> `npm config list` 的结果也贴下

**Comment by stormslowly** [comment]
可以升级下 npm 版本  删除 node_modules 重新安装下 ，我用的 npm 8.3.1

**Comment by 1587315093** [comment]
> 可以升级下 npm 版本 删除 node_modules 重新安装下 ，我用的 npm 8.3.1
用npm 8报错了 然后换yarn又行了
![image](https://user-images.githubusercontent.com/77056991/176858193-749739c1-f352-4ea6-920e-bdf790c0232d.png)

**Comment by stormslowly** [comment]
这个是 peer deps  不能统一  braft-editor 接受的 `"react": "^15.0.2\|\| ^16.0.0-rc \|\| ^16.0.0",`  看下错误提示 加下 `--force`  或者  `--legccy-peer-deps` 重试下

**Comment by ksh033** [comment]
你运行下 yarn list umi看一下有没有多个umi版本。这个问题我也找一天才发现老版本没删除干净。具体可以看下，**node_modules/@umijs**,**node_modules/@umijs/preset-umi/node_modules**,肯定会有多个版本

**Comment by Wuriqilang** [comment]
我也遇到这样的问题, 我的项目是一个 使用了  umi(主项目) + dumi(若干组件库) 的 memoRepo. 

因为主项目升级了umi4  导致dumi 启动时会报错(依赖了umi4), 但如果在 dumi指定 umi3版本后, 主项目执行 max setup就会有如上报错.  所以dumi2 赶快安排起来吧~~

**Comment by giscafer** [comment]
dumi 在 umi4报错

**Comment by thinkingc** [comment]
> > 可以升级下 npm 版本 删除 node_modules 重新安装下 ，我用的 npm 8.3.1
> > 用npm 8报错了 然后换yarn又行了
> > ![image](https://user-images.githubusercontent.com/77056991/176858193-749739c1-f352-4ea6-920e-bdf790c0232d.png)

解决了吗？npm8一样不行

**Comment by cl1107** [comment]
> 给一个复现的 demo 看看。

https://github.com/cl1107/umi3-and-umi4

**Comment by fz6m** [comment]
> > 给一个复现的 demo 看看。
> 
> https://github.com/cl1107/umi3-and-umi4

monorepo 多版本共存问题已经解决，请升级到最新版本 `4.0.8` 

示例：https://github.com/MoeYc/umi4-multi-version-monorepo-example

**Comment by Saganon0608** [comment]
> > > 给一个复现的 demo 看看。
> > 
> > 
> > https://github.com/cl1107/umi3-and-umi4
> 
> monorepo 多版本共存问题已经解决，请升级到最新版本 `4.0.8`
> 
> 示例：https://github.com/MoeYc/umi4-multi-version-monorepo-example

测试了下4.0.8版本的monorepo多版本共存
umi4+umi3  可以运行
umi4+umi3+dumi 可以运行
umi4+dumi  dumi起不来

fatal - TypeError: Cannot read properties of undefined (reading 'rimraf')

**Comment by fz6m** [comment]
给一个复现 demo 看看。

**Comment by Saganon0608** [comment]
> 给一个复现 demo 看看。

https://github.com/Saganon0608/umi4-dumi-monorepo


```
packages/dumi1 start$ dumi dev
packages/umi4 start$ npm run dev
packages/umi4 start: > dev
packages/umi4 start: > max dev
packages/dumi1 start: fatal - TypeError: Cannot read properties of undefined (reading 'rimraf')
packages/dumi1 start:     at /Users/g2/umi4-dumi-monorepo/node_modules/.pnpm/@umijs+preset-dumi@1.1.46_react@18.2.0+umi@3.5.31/node_modules/@umijs/preset-dumi/lib/plugins/features/symlink.js:64:17
packages/dumi1 start:     at Array.forEach (<anonymous>)
packages/dumi1 start:     at _default (/Users/g2/umi4-dumi-monorepo/node_modules/.pnpm/@umijs+preset-dumi@1.1.46_react@18.2.0+umi@3.5.31/node_modules/@umijs/preset-dumi/lib/plugins/features/symlink.js:59:16)
packages/dumi1 start:     at Service.initPlugin (/Users/g2/umi4-dumi-monorepo/node_modules/.pnpm/@umijs+core@4.0.9/node_modules/@umijs/core/dist/service/service.js:345:40)
packages/dumi1 start:     at Service.run (/Users/g2/umi4-dumi-monorepo/node_modules/.pnpm/@umijs+core@4.0.9/node_modules/@umijs/core/dist/service/service.js:222:18)
packages/dumi1 start:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
packages/dumi1 start:     at async Service.run2 (/Users/g2/umi4-dumi-monorepo/node_modules/.pnpm/umi@4.0.9_bydnn5hg4wi5mp2wv6srjc7bde/node_modules/umi/dist/service/service.js:74:12)
packages/dumi1 start:     at async /Users/g2/umi4-dumi-monorepo/node_modules/.pnpm/umi@4.0.9_bydnn5hg4wi5mp2wv6srjc7bde/node_modules/umi/dist/cli/forkedDev.js:24:5
packages/dumi1 start: fatal - A complete log of this run can be found in:
packages/dumi1 start: fatal - /Users/g2/umi4-dumi-monorepo/packages/dumi1/node_modules/.cache/logger/umi.log
packages/dumi1 start: fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
packages/umi4 start: info  - Umi v4.0.9
packages/dumi1 start: Done
packages/umi4 start: ready - App listening at http://localhost:8001
packages/umi4 start: event - [Webpack] Compiled in 1349 ms (578 modules)
packages/umi4 start: info  - [MFSU] buildDeps since cacheDependency has changed
packages/umi4 start: wait  - [Webpack] Compiling...
packages/umi4 start: event - [Webpack] Compiled in 86 ms (546 modules)
```

**Comment by fz6m** [comment]
@Saganon0608 

给 dumi 项目安装 `rimraf` 就可以了：

```bash
  pnpm add -D rimraf
```

关于加载不到 rimraf 这个问题去 [dumi](https://github.com/umijs/dumi) 下面反馈吧。
