### ISSUE TITLE
[Bug] 自动注入的 umi.js 文件应该放到通过 scripts 注入的文件后面

### ISSUE THREAD

**Issue by huarse** [umijs/umi#8344]
如题，项目配置里面 externals 了 react 等依赖包，然后需要通过 scripts 注入到HTML里面，但是发现 umi.js 竟然放到了这些文件前面，这样会导致依赖问题；

PS：为什么之前的 document.ejs 的方式不支持了？是出于什么考虑呢？

**Comment by xierenyuan** [comment]
使用这个 https://umijs.org/docs/api/config#headscripts  或者使用 https://umijs.org/docs/api/plugin-api#modifyhtml 这个解决

**Comment by fz6m** [comment]
See https://github.com/umijs/umi-next/issues/868#issuecomment-1151088426

**Comment by huarse** [comment]
楼上的回复我能理解，不过这个 umi.js 插入到最前面的问题确实应该是一个 BUG 吧？（还有 umi.css 也是） 我理解这个的原因是内转的插入 umi.js 的逻辑要比 config-scripts 这个插件先执行的，是不是改一下顺序就可以了？

**Comment by sorrycc** [comment]
externals 的 scripts，通过 headScripts 插入就好，这会有什么问题吗？

**Comment by fz6m** [comment]
此代码片段应该可以满足你的需求：https://github.com/umijs/umi/issues/8442

**Comment by huarse** [comment]
> 此代码片段应该可以满足你的需求：#8442

哈哈，和我实现的一模一样……

**Comment by drizzlesconsin** [comment]
Umi 3 scripts 的文件会在 umi.js 前面

现在
```html
<div id="root"></div>
<script src="/umi.js"></script>
<script src="https://unpkg.com/react@18.0.0/umd/react.production.min.js"></script>

</body></html>
```

**Comment by twinkle77** [comment]
> Umi 3 scripts 的文件会在 umi.js 前面
> 
> 现在
> 
> ```
> <div id="root"></div>
> <script src="/umi.js"></script>
> <script src="https://unpkg.com/react@18.0.0/umd/react.production.min.js"></script>
> 
> </body></html>
> ```

是的  我也发现了这个问题
