### ISSUE TITLE
[Bug] GET http://127.0.0.1:8000/%3Canonymous%3E 404 (Not Found)

### ISSUE THREAD

**Issue by kailong321200875** [umijs/umi#8349]
## What happens?

通过官方工具创建项目，在 win10下启动，控制台就会一直报404，没有做任何更改，mac不会。

## Mini Showcase Repository(REQUIRED)

最小复现地址：https://github.com/kailong321200875/design-pro.git

![image](https://user-images.githubusercontent.com/32283845/176981412-66d2e0dc-9c5d-4539-81e5-2d319e43f4f4.png)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0.5
- **Node Version**: 16.0.0
- **Platform**: win10  Google Chrome 版本 103.0.5060.66（正式版本） （64 位）

**Comment by fz6m** [comment]
试一下无痕模式。

**Comment by kailong321200875** [comment]
@fz6m 无痕是可以的，但是这个应该也算是有问题的吧

**Comment by fz6m** [comment]
排查下你的浏览器插件和代理吧。

**Comment by WuJiY** [comment]
是的，有时候也会这样。不知道是什么引起的

**Comment by kailong321200875** [comment]
没有使用任何代理，mac和win的谷歌插件是完全一致的，但是mac并不会这样

**Comment by fz6m** [comment]
你的请求头里有没有 PNA 相关的 header ？

FYI：https://juejin.cn/post/7111190533942280206

**Comment by sorrycc** [comment]
Closed via https://github.com/umijs/umi/pull/8367

**Comment by WuJiY** [comment]
"@umijs/max": "^4.0.18", 依然存在

![1662598433047](https://user-images.githubusercontent.com/183884/189009994-9fe58eaa-1bf2-4dfc-9b08-63505c99f068.png)
