### ISSUE TITLE
[Bug] 在 WSL2 环境开发，127.0.0.1 无法访问，需更改为 localhost

### ISSUE THREAD

**Issue by Ynewtime** [umijs/umi#8351]
## What happens?

如题，按照官网的 Getting Started 在 WSL2 启动一个工程后，会发现 http://127.0.0.1:8000 无法访问

建议更改默认的启动路径为 http://localhost:8000

![无法访问](https://user-images.githubusercontent.com/27655771/176990912-4c608e74-b8ea-4fe6-ad2d-17d097933b9a.png)

![image](https://user-images.githubusercontent.com/27655771/176990995-42af5094-1d7a-48b6-aa12-711e5964a0e3.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

严格来说不需要新建一个复现仓库，试试在 WSL2 环境启动开发就会发现 BUG。

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: v4.0.5
- **Node Version**: v16.15.1
- **Platform**: Linux 5.10.16.3-microsoft-standard-WSL2

**Comment by kaoding** [comment]
127.0.0.1要走从网络层（TCP/IP）
