### ISSUE TITLE
[Bug] umi4 lost title anchor

### ISSUE THREAD

**Issue by stygian-desolator** [umijs/umi#8357]
## What happens?

umi4 似乎缺失了标题的锚点链接功能，在 umi3 中是有的，但是 umi4 里并未出现

## Mini Showcase Repository(REQUIRED)

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/73412177/177063749-81550f44-955e-4e52-b09f-4e5d70b8a260.png">

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

在最新的官网上就可以复现。

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by ahwgs** [comment]
临时方案可以通过右侧这个实现
![image](https://user-images.githubusercontent.com/26664586/177074483-6da8ee0d-57c1-48d8-8154-55ce0e43b592.png)

**Comment by sorrycc** [comment]
非 bug，感兴趣可以直接提 PR。
