### ISSUE TITLE
[Bug] @umijs/max 配置siderWidth,logo无效,并且自定义favicon始终取到的是umi的icon

### ISSUE THREAD

**Issue by Ggmid** [umijs/umi#8359]
## What happens?

在config.ts里配置pro-layout的siderWidth以及logo未生效，查看.umi/pro-layout/Layout.tsx,发现并未取值，另外还发现在public配置favicon.ico文件，始终取到的是umi的icon

<img width="367" alt="image" src="https://user-images.githubusercontent.com/22318151/177073575-37b303cb-3721-45ea-9a69-d441134fdbce.png">
<img width="346" alt="image" src="https://user-images.githubusercontent.com/22318151/177073657-24c8eeef-e482-4662-9d51-a5a7e17d9a67.png">
![image](https://user-images.githubusercontent.com/22318151/177073819-310409b7-1599-4c04-b901-201820155ae2.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version*@umijs/max: 4.0.5*:
- **Node Version*V16.14.0*:
- **Platform*macos*:

**Comment by wangxingkang** [comment]
另外还发现在public配置favicon.ico文件，始终取到的是umi的icon

这个换个名字 就可以解决

**Comment by KiritoXF** [comment]
现在 `config.ts` 那的 layout 导出是空的，好像 layout 相关的内容得到 `app.tsx` 那去配，不知道是不是换地方了
也可以换后缀 `favicon.png`

**Comment by Ggmid** [comment]
> 另外还发现在public配置favicon.ico文件，始终取到的是umi的icon
> 
> 这个换个名字 就可以解决

那我觉得这样处理还挺尬的

**Comment by Ggmid** [comment]
> 现在 `config.ts` 那的 layout 导出是空的，好像 layout 相关的内容得到 `app.tsx` 那去配，不知道是不是换地方了 也可以换后缀 `favicon.png`
我看文档里也没有特别标注，并且看官方的例子也是写在config里面的，所以不知道是bug还是换地方了

**Comment by LanJamRom** [comment]
![image](https://user-images.githubusercontent.com/41603622/177089249-f3f9adf3-ebea-4147-87cd-128e928dc576.png)
属性都是透传ProLayout的。
umi4是约定式的 favicon，自动识别 src/favicon.ico 文件。(这点好像文档上还没描述)

**Comment by zjfresh** [comment]
Dev 环境默认改写默认favicon 为umi的，@umijs/preset-umi/dist/commands/dev/faviconMiddleware.js

**Comment by Ggmid** [comment]
> ![image](https://user-images.githubusercontent.com/41603622/177089249-f3f9adf3-ebea-4147-87cd-128e928dc576.png) 属性都是透传ProLayout的。 umi4是约定式的 favicon，自动识别 src/favicon.ico 文件。(这点好像文档上还没描述)

icon的问题试了一下可以感谢，但是layout暂时还是在app.tsx下面修改才生效

**Comment by LanJamRom** [comment]
> > ![image](https://user-images.githubusercontent.com/41603622/177089249-f3f9adf3-ebea-4147-87cd-128e928dc576.png) 属性都是透传ProLayout的。 umi4是约定式的 favicon，自动识别 src/favicon.ico 文件。(这点好像文档上还没描述)
> 
> icon的问题试了一下可以感谢，但是layout暂时还是在app.tsx下面修改才生效

![image](https://user-images.githubusercontent.com/41603622/177092231-f3ab816c-d89b-4ee5-b7f1-8bb10f8635ee.png)
构建时配置只允许这两个属性，其他属性都要写在运行时配置上的。

**Comment by Ggmid** [comment]
> 

> > > ![image](https://user-images.githubusercontent.com/41603622/177089249-f3f9adf3-ebea-4147-87cd-128e928dc576.png) 属性都是透传ProLayout的。 umi4是约定式的 favicon，自动识别 src/favicon.ico 文件。(这点好像文档上还没描述)
> > 
> > 
> > icon的问题试了一下可以感谢，但是layout暂时还是在app.tsx下面修改才生效
> 
> ![image](https://user-images.githubusercontent.com/41603622/177092231-f3ab816c-d89b-4ee5-b7f1-8bb10f8635ee.png) 构建时配置只允许这两个属性，其他属性都要写在运行时配置上的。

暂时也只能这样了

**Comment by sorrycc** [comment]
favicon 可以放 src 目录。
