### ISSUE TITLE
[Bug] 国际化配置之后控制台始终报错

### ISSUE THREAD

**Issue by Ggmid** [umijs/umi#8360]
## What happens?

在locales文件下配置国际化信息，控制台始终会报错
![image](https://user-images.githubusercontent.com/22318151/177074135-4e1edad2-c043-4c07-ae71-cae0d9785cc0.png)
<img width="390" alt="image" src="https://user-images.githubusercontent.com/22318151/177074180-bc45d821-e137-4d79-a67e-6f430934fcc9.png">

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version*@umijs@max: 4.0.5*:
- **Node Version*V16.14*:
- **Platform*macos*:

**Comment by KiritoXF** [comment]
你路由里是不是 name 直接配的是中文？如果是的话你得在多语言那配成 `"menu.图表": "图表",`

也就是说路由的 name 相当于 key

这些错误信息 build 后就不显示了，只在开发模式下会提示

**Comment by Ggmid** [comment]
> 

没有的，我是umi3升级上来的，路由里都是英文的，在3的版本里都是没问题的

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

**Comment by songwone** [comment]
请问这个问题解决了吗   我遇到了同样的问题  报错很烦

**Comment by Ggmid** [comment]
> 请问这个问题解决了吗 我遇到了同样的问题 报错很烦

你现在的写法是怎么样子的
