### ISSUE TITLE
[Bug]release版本搞错了吧

### ISSUE THREAD

**Issue by s464446877** [umijs/umi#8371]
## What happens?

release版本从4.0.4 -> 3.5.27吗
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
```
$ npm info umi
dist-tags:
3-3-x: 3.3.14                    canary: 4.0.0-canary.20220628.2  latest: 4.0.5                    next: 4.0.0-rc.24
```

没问题吧。

**Comment by s464446877** [comment]
![image](https://user-images.githubusercontent.com/52397868/177117611-ca0e0f26-1d94-468a-8299-53b78db54af1.png)
npm上的包没错，刚才看git上release变更看到的

**Comment by sorrycc** [comment]
这个是正常的，github 的 latest 和 npm 的 latest 不是同一个意思。
