### ISSUE TITLE
[Bug] UMI 4 配置(.umirc.ts)中的 alias 无法被 typescript 正确识别。

### ISSUE THREAD

**Issue by ye-will** [umijs/umi#8376]
## What happens?

<img width="1021" alt="Screen Shot 2022-07-04 at 21 37 41" src="https://user-images.githubusercontent.com/9099214/177166275-2feacdf6-fe76-49b5-a28e-75a8ab7e181a.png">

如图所示，由于 tsconfig.json 中缺少与 .umirc.ts 中的 alias 对应的 paths 定义，导致 ide 报错，代码本身能正常运行。

## Mini Showcase Repository(REQUIRED)

应该不需要...

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0.5
- **Node Version**: v18.4.0 with yarn 1.22.19
- **Platform**: mac m1 / vscode

**Comment by ye-will** [comment]
@sorrycc 直接在项目根目录中的 `tsconfig.json` 中添加如下定义的话

```
{
  "extends": "./src/.umi/tsconfig.json",
  "compilerOptions": {
    "paths": {
      "@components/*": ["src/components/*"]
    }
  }
}
```

会导致 `@/*`, `@@/*`, `umi`, `umi/typings` 这些定义在 `src/.umi/tsconfig.json` 中的 paths 无法被正确识别，所以需要手动将这些定义拷到外层的 `tsconfig.json` 中

显然这个不是好的做法，因为我们并不清楚 umi.js 会在什么时候去更新 `src/.umi/tsconfig.json`

比好好的做法还是让 umi.js 来将这些配置注入到 `tsconfig.json` 中。

**Comment by cds803** [comment]
```
{
  "compilerOptions": {
    
    "paths": {
      "@/*": [
        "src/*"
      ],
      "@@/*": [
        "src/.umi/*"
      ],
      "@umijs/max": [
        "~/node_modules/.pnpm/umi@4.0.8_bydnn5hg4wi5mp2wv6srjc7bde/node_modules/umi"
      ],
      "@umijs/max/typings": [
        "src/.umi/typings"
      ]
    }
  }
}
```
src/.umi/tsconfig.json 默认生成的配置里，@umijs/max 是一个通过包版本生成的动态路径，无法在项目中直接使用

**Comment by rozbo** [comment]
any update ?

**Comment by fz6m** [comment]
目前的一个解决方案：https://github.com/umijs/umi/pull/9642

**Comment by rozbo** [comment]
太好了（一顿尝试报错才发现还有没有被merge， 这么好的功能呼吁尽快merge）

**Comment by showonne** [comment]
求新年加急😂

**Comment by fz6m** [comment]
最新版本添加了一个 plugin api 来缓解这个问题，详见 https://github.com/umijs/umi/pull/9642#issuecomment-1543277411 ，但不推荐自行配置额外的别名，因为 `@` 已经足够。
