### ISSUE TITLE
在umi@2 Beta版使用antd组件出现一些问题，原因无解。。。

### ISSUE THREAD

**Issue by Instanced** [umijs/umi#838]
DEMO地址 https://github.com/Instanced/temp

使用表格组件固定列，样式似乎出现一些问题，
在不使用的umi的情况下是正常的。 DEMO： https://codesandbox.io/s/jvzkp5wkj9

<del> 还有就是在DEV模式下，刷新浏览器组件会有大概一秒左右的样式丢失的情况，</del> BUILD后无此问题了

**Comment by sorrycc** [comment]
类似问题，![image](https://user-images.githubusercontent.com/35128/44133680-9a769df6-a093-11e8-8de5-7db6503f5df6.png)
