### ISSUE TITLE
umi3  .umirc.ts配置plugins报错 , 请问有解决方法么

### ISSUE THREAD

**Issue by cjzgitHub** [umijs/umi#8380]
plugins: [
    [
      'babel-plugin-import',
      {
        libraryName: '@arco-design/web-react',
        libraryDirectory: 'es',
        camel2DashComponentName: false,
        style: true, // 样式按需加载
      },
    ],
  ],

**Comment by cnyballk** [comment]
plugins是配置umi插件，babel插件可以用extraBabelPlugins进行配置
