### ISSUE TITLE
Umi4 errorThrower不执行

### ISSUE THREAD

**Issue by HalcyonDaysssss** [umijs/umi#8381]
`import type { RequestConfig } from '@umijs/max';

export const request: RequestConfig = {
  timeout: 2000,
  errorConfig: {
    // 错误抛出
    errorThrower: (res) => {
      console.log(res);
    },
    // 错误接收及处理
    errorHandler: (error: any) => {
      console.log(error);
    },
  },
  // 请求拦截器
  requestInterceptors: [
    (url, options) => {
      const headers: any = { ...options.headers };
      const token = localStorage.getItem('access_token');
      if (token) {
        headers['x-token'] = token;
      }
      return { url, options: { ...options, headers } };
    },
  ],
  // 响应拦截器
  responseInterceptors: [
    (response) => {
      // 拦截响应数据，进行个性化处理
      const { data } = response;
      console.log(data);
      return response;
    },
  ],
};

export default request;
`

<img width="490" alt="image" src="https://user-images.githubusercontent.com/24239032/177243358-d5613349-8cb0-4393-bb84-ccf2e4fb078a.png">

<img width="1664" alt="image" src="https://user-images.githubusercontent.com/24239032/177262981-0c4b1b9f-1d96-4909-a704-7711637f4cb0.png">
此报错只执行了errorHandler

**Comment by Ggmid** [comment]
> 
我也遇到了这个问题，还是直接在拦截器直接做吧

**Comment by geyitu** [comment]
> > 
> 
> 我也遇到了这个问题，还是直接在拦截器直接做吧

我也遇到了

**Comment by dongxiaoyong009** [comment]
正在对项目做升级，也遇到这个问题

**Comment by dongxiaoyong009** [comment]
![image](https://user-images.githubusercontent.com/13757451/184318375-f9da61d6-5426-41f1-b9a4-999f880e410d.png)
不执行的原因在这里, 老老实实在响应拦截器里处理一下数据格式吧，至少加一个 success字段

**Comment by zeyueguo** [comment]
这样转换一下就可以进入errorThrower

```
  responseInterceptors: [
    (response: AxiosResponse) => {
      const { code: errorCode, message: errorMessage, data } = response.data;
      response.data = {
        errorCode,
        errorMessage,
        data,
        success: errorCode === 0,
      };
      return response;
    },
  ]

**Comment by JingWZeng** [comment]
我也遇到这个问题，而且我的data里面是有success 字段的，但是为false的时候也是不走该逻辑

**Comment by lzm0x219** [comment]
对的，之前版本不会的

**Comment by dragonwang-hub** [comment]
没错，现在使用还是同类问题，依然和@zengxpang一样处理方案

**Comment by MelindaSssss** [comment]
我的response根本就没有data字段呀
