### ISSUE TITLE
[Bug] layout布局异常

### ISSUE THREAD

**Issue by lazyhero** [umijs/umi#8382]
## What happens?

* https://umijs.org/plugins/plugin-layout 文档访问白屏
* 运行时配置runtimeConfig中的logout配置后 布局异常

## How To Reproduce

* 按[umijs.org](https://umijs.org/docs/tutorials/getting-started) 安装环境
* 修改app.ts，设置layout，按文档添加logout
```typescript
export const layout = () => {
  return {
    logo: 'https://img.alicdn.com/tfs/TB1YHEpwUT1gK0jSZFhXXaAtVXa-28-27.svg',
    menu: {
      locale: false,
    },
    logout: () => {
      console.log('logout')
    },
  };
};

```
* 期望 布局中 “退出登录” 顶部栏右侧
* 实际 “退出登录” 区域在 左侧 aside 组件中 布局错乱
都跑到控制台边上了……
<img width="281" alt="image" src="https://user-images.githubusercontent.com/9362926/177243789-bba6ad69-1e30-465a-bd4c-cd6e3eb9f190.png">
* 检查元素发现“umi-plugin-layout-action”位置貌似不符合预期
* 手动将“umi-plugin-layout-action”调整到“ant-page-header-heading” 后布局正常
<img width="682" alt="image" src="https://user-images.githubusercontent.com/9362926/177243932-8f02b954-325d-4529-bb50-0430c0261da3.png">
<img width="495" alt="image" src="https://user-images.githubusercontent.com/9362926/177244011-904d259a-eb24-4854-9292-3a7d57245515.png">

## Context

- **Umi Version**: 4.0.5
- **Umi Plugin-Layout Version**: "@ant-design/pro-layout": "^7.0.1-beta.20",

**Comment by lazyhero** [comment]
同志们 用layout: mix

**Comment by liqinhua** [comment]
> 同志们用layout: mix

大佬，是否可以具体，没理解layout: mix

**Comment by liqinhua** [comment]
> 同志们使用layout: mix

大佬，是否可以具体，没理解layout: mix
