### ISSUE TITLE
[Bug] Umi4 不支持Yarn直接创建吗？

### ISSUE THREAD

**Issue by Pszz** [umijs/umi#8384]
Umi4 不支持Yarn直接创建吗？

如果支持，能否提供简单的演示案例？

`yarn create create-umi@latest`

`yarn dlx create-umi@latest`

`yarn create-umi@latest`

我使用上述命令都不能创建 Umi4。

我认为如果要强行推`pnpm`, 是否在文档备注：“**只支持pnpm创建**”

当然我只是认为我安装的包管理工具太多

Npm、Yarn、Cnpm、Npx、Wget、Nvm、Brew.....

或许可能出现`anpm、bnpm、cnpm、enpm、dnpm....`

**Comment by fz6m** [comment]
几个基础知识：

 - yarn create 是省略包 `create-` 前缀的写法，比如 `create-umi` 应该使用 `umi`

 - `*px` (`npx` / `pnpx`) 才是使用全称，比如 `npx create-umi`

 - `yarn dlx` 只在 yarn >=2 才有，同理使用全称

所以你需要使用：

```bash
  yarn create umi
```
