### ISSUE TITLE
[Bug] layout在手机模式下无法展开菜单

### ISSUE THREAD

**Issue by reusu** [umijs/umi#8385]
好像菜单这个按钮就缩在了奇怪的地方
点击无效
使用 mix/side 都是这样子
用的umi-max示例

![QQ20220705-131015](https://user-images.githubusercontent.com/8424240/177253793-87987ec3-a654-45a0-80eb-07d4e581bbe6.png)

**Comment by reusu** [comment]
另外pro-layout在使用默认logout的TableDropdown时
唤出会提示如下警告
Warning: [antd: Menu] `children` will be removed in next major version. Please use `items` instead.

**Comment by sorrycc** [comment]
这属于 pro-layout 的问题，请到 https://github.com/ant-design/ant-design-pro/issues 提 issue。
