### ISSUE TITLE
[Docs] 升级到UMI4文档补充

### ISSUE THREAD

**Issue by PassionPI** [umijs/umi#8390]
## What happens?
https://umijs.org/docs/introduce/upgrade-to-umi-4
此文档, 需要补充一点
umi3与umi4在app.ts和global.ts, 以及这两个文件, 依赖的其他文件, 存在差异
- umi3
可以`import { XXX } from 'umi';`并使用
- umi4
可以`import { XXX } from 'umi';`但 `XXX == undefined`
如果是插件导出的方法, 并执行的话, 还会因为插件尚未初始化而导致页面报错
`Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'applyPlugins')`

## ----------
- 不知道这种差异, 是否属于正常
- 如正常, 希望文档补充
- 如不正常, 希望修复

**Comment by sorrycc** [comment]
XXX 给个具体的例子？
