### ISSUE TITLE
[Bug] Invalid config keys: qiankun, initialState, model

### ISSUE THREAD

**Issue by PhilipDing** [umijs/umi#8392]
## What happens?

执行 umi lint 会提示异常

```
fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: qiankun, initialState, model
```

.umirc.ts 内容为

```
export default {
    qiankun: {
        slave: {},
    },
    initialState: {},
    model: {},
    routes,
    proxy: proxy[REACT_APP_ENV || 'dev'],
    runtimePublicPath: {},
    mock: {}
};
```

## How To Reproduce

执行 umi lint，就会提示异常

## Context

- **Umi Version**: v4.0.5
- **Node Version**: v16.15.1

**Comment by ahwgs** [comment]
看下有安装@umijs/max插件吗

https://umijs.org/docs/max/introduce#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8

**Comment by luobinhang** [comment]
同样的问题
`AssertionError [ERR_ASSERTION]: Invalid config keys: nodeModulesTransform, favicon, van, dynamicImportSyntax`
umi 4.0.5
@umijs/max 4.0.5

**Comment by fz6m** [comment]
max 需要用 `max lint`
