### ISSUE TITLE
umi4 使用Request中new Error()报错

### ISSUE THREAD

**Issue by HalcyonDaysssss** [umijs/umi#8394]
<img width="709" alt="image" src="https://user-images.githubusercontent.com/24239032/177287369-497e1bef-27b7-462c-8f84-889662cc0dbb.png">
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/24239032/177293483-12873ca0-3a79-4489-aff2-fea2c748a84c.png">

**Comment by YdreamW** [comment]
这个看上去像是错误处理生成的异常没有被 catch 到。你在使用 request 的地方 catch 一下就行。
