### ISSUE TITLE
[Bug] 配置通用布局文件layout获取的props中为空对象

### ISSUE THREAD

**Issue by oneFox399** [umijs/umi#8399]
## What happens?

根据文档在项目中手动创建通用布局文件Layout后，在layout组件中获取的props为空对象，无法获取到路由信息？请问应该如何配置使用
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

![image](https://user-images.githubusercontent.com/108709872/177350504-42908a85-5ae0-4ae5-92b4-51c9ecb1117b.png)
![image](https://user-images.githubusercontent.com/108709872/177350536-f9260c92-e8bd-45c1-a44c-83c710262c6a.png)
![image](https://user-images.githubusercontent.com/108709872/177350565-a5891186-344f-4d99-ac4a-3d09eba78ff1.png)

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
通过 hooks 的方式获取，比如 useAppData, useRouteData, useParams, useMatch 等。
