### ISSUE TITLE
Umi 3 & 4：报错时引导到 fb.umijs.org

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#8402]
## 问题

在报错时，加一行文案引导到 [fb.umijs.org](https://fb.umijs.org/)，让 Umi 用户更容易找到渠道反馈问题。

## 解法

1、处理各种类型的报错，包括 1）process.exit，2）webpack 编译报错
2、需同时处理 Umi 3 和 Umi 4

比如 Umi 4 的 process.exit 处理，在[这里](https://github.com/umijs/umi/blob/3ba8e82aea4fbc30ed2f415e00a768feea3ac74a/packages/umi/src/cli/printHelp.ts#L8)加一行。

```diff
+ logger.fatal('如果你需要进交流群，请访问 https://fb.umijs.org 。');
```

**Comment by timeTravelCYN** [comment]
认领

**Comment by sorrycc** [comment]
已支持。
