### ISSUE TITLE
[Bug] useModel 没有热更新

### ISSUE THREAD

**Issue by ZHUIMEN** [umijs/umi#8405]
ts 环境下useModel umi热更新没有动态的加载 model 文件

### 问题
使用 umi4 的数据流 useModel  在开发模式下 使用 src/models 或者 src/pages/xxx/ 定义model.ts(xxx.ts)文件，
 使用时 ts报类型错误。
 
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/30618748/177357747-b28fcb8a-1bb9-4be4-98f5-481ea90b0660.png">

### 解诀
 必须把 .umi 缓存删 重新编译（yarn dev） ts才不报错
<img width="1568" alt="image" src="https://user-images.githubusercontent.com/30618748/177361020-82679afe-96bc-4643-aa73-654bdcdd6785.png">
类型报错也没有了
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/30618748/177361514-32d011a2-72d2-4486-ae40-ac19ea5bcc67.png">

##期望  
 每次建model文件不需要手动 删除.umi 文件在 yarn dev
## Context

- **@umijs/max Version**: 4.0.0-rc.22
- **Node Version**: v16.15.0.
- **Platform**: macos

**Comment by hanzebang** [comment]
https://user-images.githubusercontent.com/46307343/177502035-59e9982d-8cd8-4bf3-bc25-e790173eb7a5.mov

我这里没有复现，model 文件是实时更新的

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

请给明确的复现步骤。
