### ISSUE TITLE
[Bug] umi3升级到umi4路由切换，页面渲染两次

### ISSUE THREAD

**Issue by Ggmid** [umijs/umi#8408]
## What happens?

路由切换时，页面会渲染两次，
![image](https://user-images.githubusercontent.com/22318151/177453792-4f0f34c9-8bda-4fbb-8b10-0a4893e84ff3.png)
<img width="572" alt="image" src="https://user-images.githubusercontent.com/22318151/177453835-88a2f746-f894-47ae-a3f8-45d3e3378f45.png">

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version*4.0.5*:
- **Node Version*16.14*:
- **Platform*macos*:

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

请给最简复现。
