### ISSUE TITLE
怎么消除警告的

### ISSUE THREAD

**Issue by zb201307** [umijs/umi#8409]
> 📣📣📣Outlet的问题是我个人的问题，已解决，请忽略； 另外补充: 本项目启动时，终端日志里：Directory ./src/api exists, but config.apiRoute is not set. API route feature will not be enabled! 是啥意思呢，怎么消除这个警告

src/api 是一个新的约定目录

_Originally posted by @xiaohuoni in https://github.com/umijs/umi/issues/8172#issuecomment-1161633603_

怎么消除警告的

**Comment by zb201307** [comment]
解决了，换个名字

**Comment by xierenyuan** [comment]
> 解决了，换个名字

云谦老师会改下warning 的时机 先关了
