### ISSUE TITLE
[Feature Request] Umi4的apiRoutes能否提供对formdata等数据请求的解析方式

### ISSUE THREAD

**Issue by lipenghu001** [umijs/umi#8410]
## Background

注册POST请求后，发现无法处理带有FormData数据的POST请求

## Proposal

能否对apiRequest类添加新的方法用来解析 FormData等数据

**Comment by sorrycc** [comment]
@yuaanlin 有空可以看看。

**Comment by yuaanlin** [comment]
@sorrycc 做好了 👍 #8432

**Comment by lipenghu001** [comment]
> 

PR里的代码我copy到本地试了一下哈，图片文件最终解析出的Buffer写入文件无法正常打开显示，源图片与POST解析的Buffer不一致。
源文件：
![image](https://user-images.githubusercontent.com/51285649/177683514-a3e1671e-0381-4607-8406-b82fa0230d7d.png)
最新PR解析后：
![image](https://user-images.githubusercontent.com/51285649/177683690-bb833237-5724-4336-bd82-bb076ba32004.png)
会不会是 body += chunk这样的操作带来的自动编码转换导致的

**Comment by lipenghu001** [comment]
@yuaanlin 辛苦~有空的时候看看最新回复哈

**Comment by yuaanlin** [comment]
> PR里的代码我copy到本地试了一下哈，图片文件最终解析出的Buffer写入文件无法正常打开显示，源图片与POST解析的Buffer不一致。 

@lipenghu001 应该修好了，测试了一下能够正常显示

<img width="554" alt="image" src="https://user-images.githubusercontent.com/21105863/177694863-8be8e9db-68b8-4556-887c-1e6b551a2d82.png">

<img width="842" alt="image" src="https://user-images.githubusercontent.com/21105863/177694849-5f7b0024-08f4-4773-a2a1-68adc8f6635d.png">

再麻烦帮我测试一下哈 🙏

**Comment by lipenghu001** [comment]
@yuaanlin pass  👍 😁
