### ISSUE TITLE
[Bug] externals没有真正的把react-dom剔掉，还没测试过react是不是

### ISSUE THREAD

**Issue by CaanDoll** [umijs/umi#8417]
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/23540471/177495499-2bc30d79-a0af-4eaf-a628-82afdd5b5b65.png">

配置如下：
<img width="233" alt="image" src="https://user-images.githubusercontent.com/23540471/177495572-859dff11-7567-417f-9cc2-32ae4a95e15f.png">
<img width="549" alt="image" src="https://user-images.githubusercontent.com/23540471/177495659-f896d1c8-e606-48e0-8aeb-a47163381c06.png">

且在开发环境会导致出现这个警告：
![image](https://user-images.githubusercontent.com/23540471/177495840-d4d83d24-b547-4e26-8aab-237b7fa719fb.png)

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

请给最简复现。
