### ISSUE TITLE
能否提供iccStack子应用改造的插件

### ISSUE THREAD

**Issue by jumpingFinger** [umijs/umi#8426]
团队微前端主应用为iceStark基座，团队ice项目占多数 ，需要把3个antd pro项目改造为iceStark子应用，可目前没有入口可挂载iceStark子应用生命周期的入口，有什么办法可以把react挂载根节点放出来嘛

**Comment by sorrycc** [comment]
icestark 没用过，不清楚他的具体要求是什么。理论上是可以实现的，建议参考这个仓库中的 qiankun/slave 插件。
