### ISSUE TITLE
[Bug] umi3作为主应用，umi4作为子应用，需要在umi3中自定义fetch才能成功加载子应用

### ISSUE THREAD

**Issue by cl1107** [umijs/umi#8427]
## What happens?
umi3作为主应用，umi4作为子应用，需要在umi3中自定义fetch才能成功加载子应用,

## Mini Showcase Repository(REQUIRED)
https://github.com/cl1107/umi3-main-with-umi4-slave

## How To Reproduce
复现仓库的例子打开页面：http://127.0.0.1:8000/slave/app1 能够正常访问
注释 master3/src/app.ts 中的如下代码则无法访问，页面显示 Cannot GET /slave
![image](https://user-images.githubusercontent.com/21985353/177514307-a3d7009c-b30f-4fe3-90a2-55cf193347fd.png)

## Context

- **Umi Version**: 主应用 3.5.27 子应用 4.0.5
- **Node Version**: 16.14.2
- **Platform**: Macos 10.15

**Comment by fz6m** [comment]
1. 看看这个对你有帮助没：https://github.com/umijs/umi/issues/8318

2. umi4 中需要 fetch 请求标头明确指定 `accept: 'text/html'` 才能加载（仅本地开发环境有此限制）

**Comment by cl1107** [comment]
> 

我的例子就是加了accept可以了，我就是觉得这样有点麻烦，希望能默认就支持

**Comment by sorrycc** [comment]
@PeachScript text/html 的限制如果移除会有什么问题吗？

**Comment by PeachScript** [comment]
判断 `text/html` 是为了让非 HTML 资源可以显式 404，可以在 qiankun 里默认加头

**Comment by PeachScript** [comment]
> umi4 中需要 fetch 请求标头明确指定 accept: 'text/html' 才能加载（仅本地开发环境有此限制）

上面有解释，仅 dev 有这个限制；Umi 3 做主应用的场景之前确实没考虑到，下个版本会改成对 `/` 或 `/{base}` 的请求不判断 `accept`

**Comment by yuu2lee4** [comment]
@sorrycc   @umijs/max 4.0.7还是有这个问题

**Comment by PeachScript** [comment]
@yuu2lee4 提供下复现仓库和步骤
