### ISSUE TITLE
Less 文件无法格式化

### ISSUE THREAD

**Issue by Superman-wc** [umijs/umi#8436]
.prettierrc 文件
其中的
```
"plugins": ["prettier-plugin-organize-imports", "prettier-plugin-packagejson"],
```
会导致vscode无法格式化less文件， 而tsx文件可以正常可以化
去除这行，可以正常格式化less文件

"@umijs/max": "^4.0.5",

vscode 1.66.2
右键菜单 ---> 格式化文档 , 执行无效果

使用
```prettier --write '**/*.{js,jsx,tsx,ts,less,md,json}```
命令可以正常格式化

**Comment by fz6m** [comment]
目前你可以使用 https://github.com/umijs/umi/issues/8182#issuecomment-1171840512 的方式 workaround 解决

该问题是 symlink 的依赖不被 vscode prettier 插件识别的问题，已有解决 PR ，如不想使用变通方法（使用 `require.resolve()` 指定插件），可支持该 PR 。

https://github.com/prettier/prettier-vscode/pull/2566

**Comment by Superman-wc** [comment]
> 目前你可以使用 [#8182 (comment)](https://github.com/umijs/umi/issues/8182#issuecomment-1171840512) 的方式 workaround 解决
> 
> 该问题是 symlink 的依赖不被 vscode prettier 插件识别的问题，已有解决 PR ，如不想使用变通方法（使用 `require.resolve()` 指定插件），可支持该 PR 。
> 
> [prettier/prettier-vscode#2566](https://github.com/prettier/prettier-vscode/pull/2566)

那目前只能使用js的方式来解决吧

**Comment by fz6m** [comment]
已解决，请重载 vscode 下载最新版本的 prettier 插件。
