### ISSUE TITLE
[Bug] umi4 app.ts 子应用配置生命周期钩子afterMount无效

### ISSUE THREAD

**Issue by liangskyli** [umijs/umi#8437]
## What happens?
app.ts 子应用配置生命周期钩子afterMount无效

按文档配置，afterMount无效
<img width="741" alt="image" src="https://user-images.githubusercontent.com/31531283/177586707-8733f8af-c6de-4095-8b2a-9d2a26610bee.png">

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:4.0.5
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
应该是文档有误，搜了下代码，没找到 afterMount 。
