### ISSUE TITLE
[Bug] vite 模式下，scripts、headScripts、styles 配置行内有问题

### ISSUE THREAD

**Issue by ahwgs** [umijs/umi#8438]
## What happens?

配置如：
```ts
export default {
  npmClient: 'pnpm',
  presets: [require.resolve('@umijs/preset-vue')],
  vite: {},
  headScripts: [
    `var msg = 'head script'
 console.log(msg);`,
  ],
  scripts: [
    `var msg = 'body script'
 console.log(msg);`,
  ],
  styles: [`body { color: #fff; };*{ margin: 0px }`],
};
```
vite模式下现象：
![image](https://user-images.githubusercontent.com/26664586/177588557-195e45bb-c9f6-4889-af29-bfa8fe204200.png)
非vite模式下现象：
![image](https://user-images.githubusercontent.com/26664586/177588775-bf11f652-ec9d-493a-98eb-0db7ebba010b.png)

期望
![image](https://user-images.githubusercontent.com/26664586/177589400-f5bd2c9e-f4b7-4c20-ae29-aa8e73ff398d.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

新建一个最简vue项目，修改为vite模式，然后如上配置行内配置。即可复现
## Context

- **Umi Version**: 4.0.5
- **Node Version**: 16
- **Platform**: windows

**Comment by xierenyuan** [comment]
虽然处理了 但是并不影响使用, 你是使用上有问题吗

**Comment by ahwgs** [comment]
vite 开发模式下会吧inline css scripts 都改成html-proxy
开发环境的表现好像就是跟webpack 不一致的，我先关掉了
