### ISSUE TITLE
[Bug] umi 3升级umi 4问题

### ISSUE THREAD

**Issue by cjdxhjj** [umijs/umi#8441]
## What happens?

1.layout失效，之前在当前目录上写个_layout.ts就能写个框架页，从而重用逻辑，目前测试原方式无效
2.document.ejs被移除,无法引入一些旧的，在window上设置变量的库，现有程序无法启动，无法调试
![image](https://user-images.githubusercontent.com/5616997/177671839-61233d80-d779-4aea-893d-8035542beac6.png)
3.无法写.d.ts,因一些使用的库没有types,但发现tsconfig.json的数据为
![image](https://user-images.githubusercontent.com/5616997/177671963-c3e08de4-9a70-48ad-a824-047afd2956c5.png)
来源于一个临时文件，无法重写
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0.5
- **Node Version**: v14.18.2
- **Platform**: win 10

**Comment by cjdxhjj** [comment]
![30877971eef5eedc8237cb23f271714](https://user-images.githubusercontent.com/5616997/177672140-1a59b153-2c60-4fdb-8157-47c999c5bcd3.png)
_layout上的withRouter无法找到，_layout无法使用，Helmet无法找到
新的@connect 如何支持type?
dva, intl等全部到了max,需要调整import {xx} from 'umi' 到 import { xx } from "@umijs/max"; script也需要调整，不能像原方案那样按配置启用+显示安装插件的方式吗？那么umi存在的意义是啥，要不将@umijs/max调整成umi,然后将现umi删除，一个啥都没有的umi的价值是什么？

**Comment by cjdxhjj** [comment]
![image](https://user-images.githubusercontent.com/5616997/177672831-3deab389-e486-4401-93d5-0a787c8f5f9b.png)
Link的这种用法被删除，只想调整path,不丢失query的写法变得麻烦
![image](https://user-images.githubusercontent.com/5616997/177672958-b4a63f8e-1c29-46e1-b5d0-0bf916e8070d.png)
query获取目前推荐使用
![image](https://user-images.githubusercontent.com/5616997/177673032-140175c7-0b66-4881-bdb0-11818d3b6857.png)
获取多个参数非常麻烦，还要考虑是否有值，并且还不兼容ie
目前ie完全不能用，很多写法没有考虑ie

**Comment by cjdxhjj** [comment]
request从umi_request迁移到axios好多请求需要调整，application/x-www-form-urlencoded方式的请求需要手工将数据转化为字符串再请求，或使用qs(需要单独安装)，这个不能给个处理吗和以前一样requestType,由框架层统一处理，使用方不需要关注axios还是umi-request之前的fetch

**Comment by cjdxhjj** [comment]
build产物目前多个文件，没有hash,如果项目里有多个前端工程，更新资源非常不方便，还有以数字命名的文件
![image](https://user-images.githubusercontent.com/5616997/177675215-1bce2a17-56fe-4d7b-913a-b39bbc73a312.png)
希望可以支持合并的js,带hash,生成的html没有使用document.ejs模板

**Comment by xierenyuan** [comment]
> build产物目前多个文件，没有hash,如果项目里有多个前端工程，更新资源非常不方便，还有以数字命名的文件 ![image](https://user-images.githubusercontent.com/5616997/177675215-1bce2a17-56fe-4d7b-913a-b39bbc73a312.png) 希望可以支持合并的js,带hash,生成的html没有使用document.ejs模板

产物带hash 需要开启 可以看这里 https://umijs.org/docs/api/config#hash  , 数字命名的文件 已处理 下个版本 更新即可

**Comment by cjdxhjj** [comment]
请问如何配置context-path,项目的根路径有个前缀，之前部署在tomcat,由于部署了多应用有个前缀，之前一直使用hash方式，现在想迁移到browser模式，如何支持context-path

**Comment by cjdxhjj** [comment]
@xierenyuan 谢谢，hash的问题已解决

**Comment by xierenyuan** [comment]
> 请问如何配置context-path,项目的根路径有个前缀，之前部署在tomcat,由于部署了多应用有个前缀，之前一直使用hash方式，现在想迁移到browser模式，如何支持context-path

https://umijs.org/docs/api/config#base 我猜你想要的是这个

**Comment by cjdxhjj** [comment]
![image](https://user-images.githubusercontent.com/5616997/177681967-bca74136-f2c4-4bf2-bebe-dafd6495f003.png)
![image](https://user-images.githubusercontent.com/5616997/177681999-c4bee92b-4001-412c-8c7d-3faa7deec49c.png)
![image](https://user-images.githubusercontent.com/5616997/177682019-52ade4a9-78ae-4dac-bc0f-7bc87d020384.png)
目前有一些bug,umi.js引用其它的js路径出错，context被舍弃，如果有context无论放哪个目录都不会成功，建议使用相对url来加载其它js,或允许打包成一个js,如果必需打包成多个js,允许将它放在某个子文件夹中，要不然，一个项目里多个js前端会出现很多问题，升级替换不方便

**Comment by cjdxhjj** [comment]
我目前使用了urlrewiter来处理html browser.
项目里使用了多个前端，多套样式，有pc,有手机端的
不可避免有多套样式，多套前端，都是生成一堆文件，全部要放在一起的话升级是恶梦

**Comment by cjdxhjj** [comment]
@xierenyuan 谢谢你的回答，目前第一步好像是通了，不过加载其它js有问题

**Comment by cjdxhjj** [comment]
![image](https://user-images.githubusercontent.com/5616997/177682745-f21d67f8-4992-48ab-b1d4-4e9ecac1a5de.png)
目前由于document.ejs不生效，无法调试，只能先编译出产物放项目里运行

**Comment by cjdxhjj** [comment]
刚详细看了遍配置，
![image](https://user-images.githubusercontent.com/5616997/177684069-a5f73ff1-9d27-4ee7-967a-107ddd3797ef.png)
添加了headScripts和links，目前可以调试了，不过觉得不如原来的document.ejs方便直接，有较多的配置,meta, title等，让umirc.ts配置膨胀，也不直观

**Comment by xierenyuan** [comment]
> 刚详细看了遍配置， ![image](https://user-images.githubusercontent.com/5616997/177684069-a5f73ff1-9d27-4ee7-967a-107ddd3797ef.png) 添加了headScripts和links，目前可以调试了，不过觉得不如原来的document.ejs方便直接，有较多的配置,meta, title等，让umirc.ts配置膨胀，也不直观

可以使用这个 https://umijs.org/docs/api/plugin-api#modifyhtml

**Comment by cjdxhjj** [comment]
@xierenyuan 谢谢，那个umi.js引入其它js目前有没有办法解决？

**Comment by cjdxhjj** [comment]
希望以相对路径引入的资源可以在产物添加contextpath如果不为/，“”等情况下，开发服务器能支持contextpath访问资源

**Comment by sorrycc** [comment]
群里回复了，最后一个有问题请单独提 issue 并给最简复现步骤。

**Comment by sherry007** [comment]
> 群里回复了，最后一个有问题请单独提 issue 并给最简复现步骤。
请问第一个问题， 子路由的 _layout.tsx 不渲染的问题是怎么解决的呀

**Comment by sherry007** [comment]
> 

what?? 那这个要咋解决啊😭

**Comment by sherry007** [comment]
> 那个不支持了，试过_layout, index都不行

你好，你这个是怎么解决的，可以告知一下不，我们项目很多子路由都用到 _layout 做托底

**Comment by cjdxhjj** [comment]
多写点代码，其实整体上看下来，这个机制并没有想象中那么重写，其实好多还是一个大layout

**Comment by cjdxhjj** [comment]
支持子路由阿

**Comment by cjdxhjj** [comment]
外面写Outlet，子路由实现Outlet要呈现的内容就行了
