### ISSUE TITLE
umi配置了beforeMiddlewares会热更新失效

### ISSUE THREAD

**Issue by victor-h** [umijs/umi#8446]
## What happens?
用umi3文档上的脚手架新建的项目，配置了beforeMiddlewares会热更新失效
<img width="568" alt="image" src="https://user-images.githubusercontent.com/4351768/177681980-917c83de-07d1-42d7-92f2-c05a9f9dbce5.png">

## How To Reproduce
yarn create @umijs/umi-app 创建一个项目后
在.umirc.ts 下增加
devServer: {
    beforeMiddlewares: [],
  },
热更新失效，
去掉beforeMiddlewares就是好的

## Context

- **Umi Version**:^3.5.27
- **Node Version**: v16.13.1
- **Platform**:mac chorme

**Comment by hbrls** [comment]
[这一行](https://github.com/umijs/umi/blob/3.4.x/packages/preset-built-in/src/plugins/commands/dev/dev.ts#L159)定义了默认的 `beforeMiddlewares`，即 `[devServer, mock]`。

[这一行](https://github.com/umijs/umi/blob/3.4.x/packages/preset-built-in/src/plugins/commands/dev/dev.ts#L201) 使用了 spread，因此 `.umirc` 里的 `beforeMiddlewares` 会覆盖上面说的这个默认的 `beforeMiddlewares`。是覆盖，不是合并。

结果就是只有你自己定义的 `.umirc` 里的会生效，默认的 `devServer` 没了。

**Comment by xiaohuoni** [comment]
这里逻辑不会修改，可以使用插件 api 支持需要的功能
