### ISSUE TITLE
自定义文件夹作为路由页面，现在所有的路由都要从pages开始查找吗

### ISSUE THREAD

**Issue by bici-fed** [umijs/umi#8451]
## Background

应用有很多模块，我们希望创建一个封闭的文件夹，他包含这个模块所有的页面、api、store、components等等，以方便我们拷贝代码到其他项目复用

## Proposal
希望如下的项目结构：
src：
  features:
     system:
         pages:
             userManage
             dictionary
             roleManage
         store
         components
    otherBus
        pages:
             a
             b
             c
         store
         components

**Comment by fz6m** [comment]
可以自定义配置路由表：

 - config：https://umijs.org/docs/api/config#routes

仓库 `examples/*` 下示例项目的 `.umirc.ts` > `routes` 供参考，如：

https://github.com/umijs/umi/blob/2504250d0aebb169f33b72421c4fdaf3fcb81a09/examples/boilerplate/.umirc.ts#L6-L39
