### ISSUE TITLE
[Bug] 模块“"umi"”没有导出的成员“useModel”。

### ISSUE THREAD

**Issue by Pszz** [umijs/umi#8454]
##  问题描述
- 使用**官方最新教程**安装UMI4，但是依旧无法导出useModel.
- 查找相关Issues/Discussions/官方文档，依旧无法解决。
- 
<img width="926" alt="image" src="https://user-images.githubusercontent.com/12093551/177713250-c81ff43f-d941-4632-9dae-fff453382441.png">

##   相关问题
- https://github.com/umijs/umi/discussions/6568
- https://github.com/umijs/umi/issues/8424
- https://github.com/umijs/umi/discussions/8416
- https://umijs.org/docs/max/data-flow

## 演示代码(REQUIRED)

- https://github.com/Pszz/umi4-bug-example

## 期望结果
- 能正常使用
- 使用指南？

**Comment by fz6m** [comment]
给的复现项目是 umi2 ，不是 umi4 。

**Comment by Pszz** [comment]
> 给的复现项目是 umi2 ，不是 umi4 。

目录结构是umi4 构建的，是因为umi没升级吗？

**Comment by Pszz** [comment]
问题已经解决，确实是因为版本未升级成功。
- https://github.com/umijs/umi/issues/8384
因为使用的
`yarn create umi`
所以实际安装的不是umi4的环境。


- 如果是正确安装umi4环境，那么如下安装插件即可。
https://github.com/umijs/umi/discussions/8416
