### ISSUE TITLE
[Bug] 配置base后请求路径错误

### ISSUE THREAD

**Issue by cjdxhjj** [umijs/umi#8460]
## What happens?
配置base，umi.js处其它js加载路径错误，从根处加载。配置publicPath后js加载成功，但项目内资源路径不正确

## Mini Showcase Repository(REQUIRED)
1.使用脚手架创建一个工程,配置如下
![image](https://user-images.githubusercontent.com/5616997/177744082-5a2aec42-4064-48af-8c95-76636cee1882.png)
将项目放在apache http server的htddoc目录，脚本，样式和图片我们分开放在不同的文件夹下，目录结构如下
![image](https://user-images.githubusercontent.com/5616997/177744277-fd6dcb96-b702-4279-b9f1-19d229e47aa5.png)
html内容修改为
![image](https://user-images.githubusercontent.com/5616997/177745397-c829a728-c00e-45d4-9f3b-829da2e74d9c.png)
直接访问,发现import的css无法引入，没有考虑base选项，并且也没有配置项
![image](https://user-images.githubusercontent.com/5616997/177744464-662ed746-062c-43a1-9064-cb684c6b26ca.png)
移除掉tsx里面import的样式,错误提示js无法加载,依然没考虑base选项，也不管当前脚本位置，也无配置指定脚本加载位置
![image](https://user-images.githubusercontent.com/5616997/177745494-15c28345-7caa-42e3-993d-e5e07e96e3e9.png)
配置上publicPath为/cas/script后脚本正常加载
![image](https://user-images.githubusercontent.com/5616997/177746293-c4c4a4a4-b4eb-45c4-aa71-f22d88f62d1f.png)
但是在public里的css, image无法正常加载
![image](https://user-images.githubusercontent.com/5616997/177746512-44d2f14b-515c-4036-8bfa-e4860e031550.png)
![image](https://user-images.githubusercontent.com/5616997/177746642-f218164d-b861-467c-9c07-2995c7bd7792.png)
pnpm start启动的项目js可正常加载，public下的资源无法加载
![image](https://user-images.githubusercontent.com/5616997/177747338-f582700b-df95-4565-a4a3-1fd147d4af5a.png)
手工加上base路径，依然无法加载，但这个路径可在http server中加载
![image](https://user-images.githubusercontent.com/5616997/177747680-fc496fb5-412c-4a9b-9f48-615e0202947b.png)
![1657188364431](https://user-images.githubusercontent.com/5616997/177748666-887458ef-4af6-4a73-a180-fa0a6304cafe.png)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
https://github.com/cjdxhjj/context-path-test.git

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.
希望可定制脚本，图片的位置，base配置时引用的相对路径资源在测试和构建时考虑base选项

## Context

- **Umi Version**: 4.0.6
- **Node Version**: v14.18.2
- **Platform**: windows 10

**Comment by xierenyuan** [comment]
刚试了下 未复现你的问题 
<img width="1575" alt="image" src="https://user-images.githubusercontent.com/7599351/177784357-dcd9ad6e-72f8-4f53-8f4b-fe90bb5d36a0.png">

**Comment by cjdxhjj** [comment]
目前的情况是加了base后开发会加载不了资源，不加base实际项目有问题，还有就是如果都是靠import的话，那么css里的资源怎么办，import少量的资源没问题，大量图片import代码看着并不好

**Comment by fz6m** [comment]
不是开了 base 无法加载资源，而是因为静态资源的路径是基于 `publicPath` 的，你的静态资源提供服务要符合这个路径规则。

**Comment by cjdxhjj** [comment]
那意思是只能把js，css等资源放在同一个目录中

**Comment by cjdxhjj** [comment]
我试试，不过那个情况下，我的资源更新有很大问题，我一个后端项目，有多个前端项目，比如因为css不兼容，前端，后台，手机端等，分了不同的前端项目，使用urlrewrite前不同的地址映射到不同的html,如果全放在根目录上，我更新资源就太乱了，目前我是把那个项目目录下的产物全部删除再放上新的资源，多个项目挺麻烦

**Comment by cjdxhjj** [comment]
我的问题其实是说，开发和部署时配置不一致。开发时加了base,导致我前台资源路径得调整，目前我写了个函数计算图片路径，使用env的变量来兼容不同端的需求，开发时base,publicPath为/,部署时通过通过base,publicPath来计算正确的资源路径，已经可以正常工作，遇到一点不太好的地方，env的数据在代码里使用process.env. 取不到，使用define配置时报变量找不到的问题（IDE）.使用declear const xx: string 解决
不过我想的是，这个base设置后开发环境及打包的产物能不能自动处理引用路径

**Comment by cjdxhjj** [comment]
@sorrycc

**Comment by cjdxhjj** [comment]
![image](https://user-images.githubusercontent.com/5616997/178442824-3f107fb5-c7e9-4bab-9e11-e51fa71a411b.png)
![image](https://user-images.githubusercontent.com/5616997/178442881-e845edc2-a785-4ff6-8596-a93b2a4a8044.png)
![image](https://user-images.githubusercontent.com/5616997/178443004-0e1777da-cbe7-4722-bef0-ea8c6b081c05.png)
![image](https://user-images.githubusercontent.com/5616997/178443088-e8375341-ce72-4506-906b-0677b9022b4e.png)
![image](https://user-images.githubusercontent.com/5616997/178443197-4afbadcd-234f-4206-b7b0-f8ed3f74c199.png)

**Comment by cjdxhjj** [comment]
@fz6m
