### ISSUE TITLE
js 打包时是否可以去除后面的随机数

### ISSUE THREAD

**Issue by lsdiao** [umijs/umi#847]
如题，目前生成的js是这样的
```
src__pages__AfterSale__AfterSearch__index.1557af37.async.js
```
想问是否可以去除随机数
```
src__pages__AfterSale__AfterSearch__index.async.js
```

**Comment by okoala** [comment]
1.x  设置 disableHash: true
https://umijs.org/config/#disablehash

2.x 设置 hash: false

**Comment by sorrycc** [comment]
2.x 默认不开 hash 。

**Comment by superlbr** [comment]
@okoala 文档里没有。。。
@sorrycc 默认不开，刷新就不能立即生效了，额。。。
