### ISSUE TITLE
用域名不带端口号访问，页面会不断刷新

### ISSUE THREAD

**Issue by jovysun** [umijs/umi#8470]
步骤：
1，按照官方的“快速上手”，选择“Ant Design Pro”模板，启动项目，http://localhost:8000/可以正常访问，没有问题。
2，然后开始配置域名访问（实现应该没问题，因为一直都在用）：hosts添加127.0.0.1 doba.vemic.com，nginx配置
server {
    listen 80;
    server_name 'xxx.yyy.com';

    location / {
        proxy_pass http://127.0.0.1:8000/;
    }
}
3，启动nginx，不带端口号访问http://xxx.yyy.com/，页面会不断刷新，带上端口则没问题。

**Comment by jovysun** [comment]
应该是HMR问题，关闭了就好了：环境变量设置cross-env HMR=none

**Comment by mwj610** [comment]
> 正确的解法是配置 `SOCKET_SERVER=http://xxx.yyy.com/`。
![image](https://user-images.githubusercontent.com/52907799/180676784-1d9bfede-5ea5-45fe-9d6d-86c25c22b333.png)

.env  SOCKET_SERVER=http://xxx.yyy.com/platformweb/

通过域名访问的时候没有加 /platformweb/
![image](https://user-images.githubusercontent.com/52907799/180677194-4124523b-33c6-4436-9d1e-e83838313718.png)
