### ISSUE TITLE
[Bug] 组件调用dispatch失败

### ISSUE THREAD

**Issue by KaerElementye** [umijs/umi#8471]
组件下调用this.props.dispatch(Action) 调用 model下对应的Effect 后，当request 报错，再次调用相同的 Action 无法成功调用model下的该Effect

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
