### ISSUE TITLE
[Bug] RequestConfig.errorConfig.errorThrower 类型错误导致提示：Type '(res: MyResponse) => void' is not assignable to type '<T = any>(res: T) => void'.

### ISSUE THREAD

**Issue by darylgo** [umijs/umi#8472]
## What happens?

在是使用 RequestConfig 配置网络请求参数时发现 errorThrower 要求参数类型是 <T = any>( res: T ) => void，这是一个泛型方法会导致实际配置的时候无法指定具体类型，并且提示：Type '(res: MyResponse) => void' is not assignable to type '<T = any>(res: T) => void'.

## Mini Showcase Repository(REQUIRED)

```typescript
  timeout: 10000,
  errorConfig: {
    errorThrower: (res: MyResponse) => { // 此处会报错：Type '(res: MyResponse) => void' is not assignable to type '<T = any>(res: T) => void'.

    },
  },
}

## Context

- **Umi Version**: 4.0.6
- **Node Version**: v18.4.0
- **Platform**:

**Comment by YdreamW** [comment]
没有复现这个问题，麻烦你提供下完整的 request 运行时配置。
