### ISSUE TITLE
[Bug] history.location 不能正确获取当前的location

### ISSUE THREAD

**Issue by zix2002** [umijs/umi#8479]
## What happens?

当页面切换后，history.location 还是落地的路径信息，不会发送变化，但是有 userLocation 则是正常的

## Mini Showcase Repository(REQUIRED)

// 修改 /src/pages/docs.tsx 添加 log
```ts
import { history, useLocation } from "umi";

const DocsPage = () => {
  const location = useLocation();
  console.log("history", history.location.pathname);
  console.log("useLocation", location.pathname);

  return (
    <div>
      <p>This is umi docs.</p>
    </div>
  );
};

export default DocsPage;
```

## How To Reproduce

访问 / 会log
```
history /
useLocation /
```

访问 /docs 会log
```
history /
useLocation /docs
```

## Context

- **Umi Version: 4.0.6
- **Node Version : 16.15.0
- **Platform: MacOS 12.4

**Comment by sorrycc** [comment]
1、useLocation 是正解
2、组件内别用 history.location，history.location 是静态的，不会变
