### ISSUE TITLE
[Bug] create-umi创建的项目内置了openapi，不知道怎么启动openapi，umi官方没有文档

### ISSUE THREAD

**Issue by skyunBoss** [umijs/umi#8482]
## What happens?

create-umi创建的项目内置了openapi，不知道怎么启动openapi，umi官方没有文档

![image](https://user-images.githubusercontent.com/29365288/178129854-1860de68-e5eb-4a8a-ae0a-c5e3ed513076.png)
就想知道生成的步骤

## Context

- **Umi Version**: 4.x
- **Node Version**: 16.x
- **Platform**:

**Comment by li9269391** [comment]
https://github.com/umijs/umi/discussions/6646

**Comment by sorrycc** [comment]
搜了下代码，没有发现 create-umi 有内置 oneapi。

**Comment by sorryjs** [comment]
> create-umi 有内置 oneapi。
"dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "^1.1.3",
    "@umijs/max": "^4.0.12",
    "@umijs/openapi": "^1.3.0",
    "antd": "^4.20.7"
  },

![image](https://user-images.githubusercontent.com/23518734/185098857-a15c61a1-acd9-44b9-9a81-95f3c3156aa2.png)
这样配置了，还是不行

**Comment by CaresRcs** [comment]
同样的问题，请问解决了没？ @sorryjs

**Comment by xiaohuoni** [comment]
https://pro.ant.design/zh-CN/docs/openapi

**Comment by CaresRcs** [comment]
> https://pro.ant.design/zh-CN/docs/openapi

配置中没有openapi,直接按照umi3中的启动方法umi openapi，会报错Invalid command openapi, it's not registered.请大神赐教 @xiaohuoni

**Comment by xiaohuoni** [comment]
加上配置呗？还能咋？插件时配置开启的。

**Comment by lovewinders** [comment]
用umijs4执行npm run build后，发现swagger-ui-dist代码也会被打包进去

**Comment by Bill-sh** [comment]
umi4 如何配置？

**Comment by xiaohuoni** [comment]
上面发的就是 umi4 的配置

**Comment by xiaohuoni** [comment]
> 用umijs4执行npm run build后，发现swagger-ui-dist代码也会被打包进去

有重现的话，建议重新发一个issues

**Comment by microCloudCode** [comment]
同样的问题

**Comment by Sep29-L** [comment]
找到解决方法了，可以加入@umijs/max-plugin-openapi插件并进行配置，详情可以参考[issues](https://github.com/umijs/umi/issues/11811)
