### ISSUE TITLE
[Bug] UMI4 Module Federation热更新失效

### ISSUE THREAD

**Issue by kevinpursuing** [umijs/umi#8484]
## What happens?
umi4项目通过MF向外expose模块，在本地开发时修改代码没有触发host项目的热更新
![image](https://user-images.githubusercontent.com/20419163/178142550-6d51a0b1-5871-4eea-8390-a67033dbf2e4.png)

## Mini Showcase Repository(REQUIRED)

暴露的remoteEntry.js没有检索到websocket相关字样，但是用create-react-app是可以的检索到的，说明mf暴露出来的入口文件并没有建立websocket链接
![image](https://user-images.githubusercontent.com/20419163/178142636-8d51611c-47c3-4996-af8e-9f9747f66210.png)

## How To Reproduce

1. 初始化umi4
2. .umirc.ts新增配置
```
  chainWebpack: (config) => {
    config
    .plugin('ModuleFederationPlugin')
    .use(ModuleFederationPlugin, [{
      name: "reactMicro",
      library: { type: 'var', name: 'reactMicro' },
      filename: 'remoteEntry.js',
      exposes: {
        "./UmiReactMicro": './src/components/UmiReactMicro/index',
        "./Guide": './src/components/Guide/Guide',
      },
    }])
  }
```
3. 访问localhost:8000/remoteEntry.js
4. 检索websocket，无相关逻辑

## Context

- **Umi Version**:
-"@umijs/max": "^4.0.6",
- **Node Version**:
- 16.15.0

**Comment by fz6m** [comment]
MF 可以等一下这个 PR ，正在实施更即开即用的支持：https://github.com/umijs/umi/pull/8450

**Comment by kevinpursuing** [comment]
> MF 可以等一下这个 PR ，正在实施更即开即用的支持：#8450

可以解决热更的问题吗

**Comment by kevinpursuing** [comment]
> MF 可以等一下这个 PR ，正在实施更即开即用的支持：#8450

@fz6m  可以解决热更的问题吗

**Comment by kevinpursuing** [comment]
![image](https://user-images.githubusercontent.com/20419163/178149594-3b61cb51-65ee-4a46-919a-f4e8d3c8a736.png)
我用原生的cra启动也是有websocket链接的，umi4就没有，这是为什么呢？
@fz6m @sorrycc

**Comment by kevinpursuing** [comment]
@fz6m 我试了下，umi3也是失效的，暴露出去的组件无法热更

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

**Comment by kevinpursuing** [comment]
@sorrycc @fz6m  已提pr哈，MF下支持热更 #8805

**Comment by WhatIsSpark** [comment]
想问下现在moduelfederation 的exposes组件热更新生效了吗 @sorrycc @fz6m

**Comment by WhatIsSpark** [comment]
> ## What happens?
> umi4项目通过MF向外expose模块，在本地开发时修改代码没有触发host项目的热更新 ![image](https://user-images.githubusercontent.com/20419163/178142550-6d51a0b1-5871-4eea-8390-a67033dbf2e4.png)
> 
> ## Mini Showcase Repository(REQUIRED)
> 暴露的remoteEntry.js没有检索到websocket相关字样，但是用create-react-app是可以的检索到的，说明mf暴露出来的入口文件并没有建立websocket链接 ![image](https://user-images.githubusercontent.com/20419163/178142636-8d51611c-47c3-4996-af8e-9f9747f66210.png)
> 
> ## How To Reproduce
> 1. 初始化umi4
> 2. .umirc.ts新增配置
> 
> ```
>   chainWebpack: (config) => {
>     config
>     .plugin('ModuleFederationPlugin')
>     .use(ModuleFederationPlugin, [{
>       name: "reactMicro",
>       library: { type: 'var', name: 'reactMicro' },
>       filename: 'remoteEntry.js',
>       exposes: {
>         "./UmiReactMicro": './src/components/UmiReactMicro/index',
>         "./Guide": './src/components/Guide/Guide',
>       },
>     }])
>   }
> ```
> 
> 3. 访问localhost:8000/remoteEntry.js
> 4. 检索websocket，无相关逻辑
> 
> ## Context
> * **Umi Version**:
>   -"@umijs/max": "^4.0.6",
> * **Node Version**:
> * 16.15.0

请问下 这个问题最后怎么解决的

**Comment by fz6m** [comment]
由于 mf 作者表示近期将进行较大的新版本更新和全新的架构设计，为了防止产生严重的历史债，现在不推荐使用 mf 。

**Comment by WhatIsSpark** [comment]
> 由于 mf 作者表示近期将进行较大的新版本更新和全新的架构设计，为了防止产生严重的历史债，现在不推荐使用 mf 。

那我们该如何让umi像webpack-dev-server一样，remote的改动可以热更新到host的项目呢，请回复下哈，感谢

**Comment by fz6m** [comment]
mf 方案据我所知并未在蚂蚁内部成功落地，目前文档也未公开，属于实验性功能，目前没有进一步迭代，不支持热更新，同时考虑到 mf v1.5 将大幅改版，不推荐使用 MF 此功能。

**Comment by WhatIsSpark** [comment]
Mf 1.5大概什么时候更新呢？

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月04日 05:18 |
| 收件人 | umijs/umi ***@***.***> |
| 抄送人 | 十年人间 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [umijs/umi] [Bug] UMI4 Module Federation热更新失效 (Issue #8484) |

mf 方案据我所知并未在蚂蚁内部成功落地，目前文档也未公开，属于实验性功能，目前没有进一步迭代，不支持热更新，同时考虑到 mf v1.5 将大幅改版，不推荐使用 MF 此功能。

**Comment by fz6m** [comment]
通过关注 ScriptedAlchemy 来获取 mf v1.5 的进展信息，目前仅在 rspack 中有具体实现，后面预计会推动至 webpack mf 插件和 nextjs ，最后经过较长的时间得到实际使用，目前 umi 没有 mf 相关的计划，因为如上文回答所述， mf 存在很多问题，难以在企业中台得到最优实践，故 mf 方案没有成功落地。

**Comment by WhatIsSpark** [comment]
我该如何在umi中使用webpack自带的module Federation 而不使用umi自带的mf功能呢？

**Comment by fz6m** [comment]
如需独立使用 mf 功能，参考 mf 的官方使用文档即可，大概分为两部分，修改 umi 的 webpack 配置，添加 mf 插件；修订应用入口（参考内置 [`mf 插件`](https://github.com/umijs/umi/blob/master/packages/plugins/src/mf.ts) 编写自己的插件或添加 [项目级插件](https://umijs.org/docs/guides/use-plugins#%E9%A1%B9%E7%9B%AE%E7%BA%A7%E6%8F%92%E4%BB%B6) 修改应用入口，让应用入口符合 mf 官方文档要求即可）
