### ISSUE TITLE
umi4，路由跳转页面，出错

### ISSUE THREAD

**Issue by liangskyli** [umijs/umi#8488]
## What happens?

页面路由跳转，出错
![image](https://user-images.githubusercontent.com/31531283/178210445-552696b1-e3d2-4300-a209-37bd2ee5b966.png)

base-layout页面里window.stop()在umi3没有问题，umi4有问题。使用window.stop解决路由跳转，大图片加载和接口请求没完成时，取消图片或接口请求，这个umi4应该要兼容适配
```ts
useEffect(() => {
    return () => {
      // 资源取消请求（如图片）
      window.stop();
    };
  }, [href]);
```

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

复现仓库：https://github.com/liangskyli/umi4-bug
看里面readme说明

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0.6
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/stop
window.stop 会阻止所有资源加载，包括 js，所以开启按需编译之后，会会出现这个问题，不建议用 `window.stop`。

**Comment by liangskyli** [comment]
> https://developer.mozilla.org/en-US/docs/Web/API/Window/stop window.stop 会阻止所有资源加载，包括 js，所以开启按需编译之后，会会出现这个问题，不建议用 `window.stop`。

主要是umi3 路由跳转，也是按需加载下一个页面的JS，umi3没有问题。如果换掉window.stop，图片资源取消请求有什么好的别的方式？

**Comment by sorrycc** [comment]
想办法在跳转之前做 stop？

**Comment by fz6m** [comment]
图片资源：[`<img loading="lazy" />`](https://developer.mozilla.org/zh-CN/docs/Web/Performance/Lazy_loading) or [`IntersectionObserver`](https://developer.mozilla.org/zh-CN/docs/Web/API/IntersectionObserver) 可以帮你避免不必要的加载。

请求：[fetch abort](https://developer.mozilla.org/zh-CN/docs/Web/API/fetch) / [axios abort cancel](https://axios-http.com/docs/cancellation) 取消请求。

通常情况下，如果没有大量请求，不需要在切换页面时取消之前的请求。

**Comment by liangskyli** [comment]
好，谢谢各位，大图片页面跳转其它页面需要取消图片资源，我想到路由的权限控制那里可以在跳转前统一取消





------------------ 原始邮件 ------------------
发件人: Yingci ***@***.***&gt;
发送时间: 2022年7月13日 12:12
收件人: umijs/umi ***@***.***&gt;
抄送: liangsky ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [umijs/umi] umi4，路由跳转页面，出错 (Issue #8488)





 
图片资源：<img loading="lazy" /&gt; or IntersectionObserver 可以帮你避免不必要的加载。
 
请求：fetch abort / axios abort cancel 取消请求。
 
通常情况下，如果没有大量请求，不需要在切换页面时取消之前的请求。
