### ISSUE TITLE
mfsu开启懒加载慢

### ISSUE THREAD

**Issue by eevin** [umijs/umi#8496]
<img width="933" alt="image" src="https://user-images.githubusercontent.com/21354993/178373333-d2a16e05-d5e5-4cbd-8f8a-8cd96e9476fb.png">

开启mfsu后，切换稍微复杂点的页面明显卡顿。关闭后正常

**Comment by eevin** [comment]
中间长达1秒多空白，没有任何请求

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
