### ISSUE TITLE
[Enhancer] mock file reload fail

### ISSUE THREAD

**Issue by sun0day** [umijs/umi#8499]
## What happens?

在 `umi dev` 运行期间，修改 `mock` 目录下某个文件，如 `mock/user.ts`，当修改 `mock/user.ts` 的内容出错时，`umi` 会报错，重新修改文件内容至正确后，`umi` 无法重新加载该文件内容，必须手动 kill 后重启 `umi dev` 才行。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

case 比较简单，就不上传仓库了，照着下面的步骤复现即可。

## How To Reproduce

**Steps to reproduce the behavior:** 

1. 执行 `npx create-umi@latest` 随便选个模版初始化工程
2. 新建文件 `mock/user.ts`, 输入以下内容

```ts
export default {
  'GET /user': [{ name: 'xxx', age: 20}]
}
```

3. 启动 `umi dev` 
4. 修改 `mock/user.ts` 文件后保存, 内容如下

```ts
export default {
  'GET /user': [{ name: 'xxx', age: 20}],
  'GET /user/1': 'xxxx'
}
```

此时控制台会输出 `error - AssertionError [ERR_ASSERTION]: Mock handler must be function or array or object, but got string for...` 的错误提示

5. 修改 `mock/user.ts` 文件后保存, 内容如下

```ts
export default {
  'GET /user': [{ name: 'xxx', age: 20}],
  'GET /user/1': {name: 'xxx', age: 20}
}
```

此时控制台依旧输出 `error - AssertionError [ERR_ASSERTION]: Mock handler must be function or array or object, but got string for...` 的错误提示

**Expected behavior** 

在上述第 5 步后，能重新正确加载 `mock/user.ts` 文件而不是必须手动 kill 进程后重新 `umi dev`。

## Context

- **Umi Version**: v4.0.1
- **Node Version**: v16.16.0
- **Platform**: macos

## 问题定位

https://github.com/umijs/umi/blob/master/packages/preset-umi/src/features/mock/getMockData.ts

```ts
// L40
 try {
        m = require(mockFile);
      } catch (e) {
        throw new Error(
          `Mock file ${mockFile} parse failed.\n${(e as Error).message}`,
        );
      }

// L74
for (const file of register.getFiles()) {
   delete require.cache[file];
 }
```

当前的逻辑是先获取文件，解析成功才会删除文件缓存，如果失败，缓存是不会清空的。

是不是可以把删除文件缓存的逻辑提到 `require` 文件内容之前，先删后读？如果可以，我可以提个 PR。

**Comment by sorrycc** [comment]
> 如果可以，我可以提个 PR。

可以的，改下顺序吧。
