### ISSUE TITLE
umi-plugin-dva

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#85]
## Features Roadmap

0.1.0

* [x] 内置 dva
* [x] ~~配 alias `"dva": "dva-no-router"`~~
* [x] 内置 dva-loading
* [x] 自动载 model，包括 global model 和 page model

0.2.0

* [ ] 按需加载 model
* [ ] dva-hmr

0.3.0

* [ ] 实现之前 `dva g` 的功能，比如 `dva g model user`

0.4.0 or later

* [ ] 自动 connect，细粒度需 ast 并改造 connect

## 目录结构

```bash
.
├── models
│   └── global.js
├── plugins
│   └── errorHandler.js
└── pages
    ├── index
    │   ├── models
    │   └── page.js
    └── user
        ├── models
        └── page.js
```

### 生成 .umi/DvaContainer.js

* 找在前置的处理时机
* 读取 templates/DvaContainer.js，其中 model 和 plugin 的注册动态生成的，然后生成到 .umi 下
* 监听 models 和 plugins 目录，变动时重新生成

### 支持配 ExtraLayout（内部参数），然后在 FilesGenerator 里支持

* 如果有 ExtraLayout 的配置，那么在 FilesGenerator 里 addLayout() 时多处理一层
* 配置 ExtraLayout 为 .umi/DvaContainer.js

### DvaContainer 内容

```js
import { Component } from 'react';
import dva from 'dva';

const app = dva();
<%= ModelRegister %>

class DvaContainer extends Component {
  render() {
    app.router(() => this.props.children);
    return app.start()();
  }
}

export default DvaContainer;
```

### 额外的 webpack 配置

```js
{
  alias: { dva: 'dva-no-router' }
}
```

### 按需加载 model

TODO

* 修改 router.js 的生成
* 在 FilesGenerator.js 的 getRouterContent() 里处理
* models 支持往上找

### 其他

* pages 下的 models 目录不作为路由查找

### 自动 connect

TODO

### 实现 `dva g` 功能

TODO

**Comment by arvinxx** [comment]
好像使用 react-hot-loader 可以在使用 umi-plugin-dva 时兼容实现 HMR 和 RHL，不过下面这条报错信息仍然存在。
```console
<Provider> does not support changing `store` on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically. See https://github.com/reactjs/react-redux/releases/tag/v2.0.0 for the migration instructions. index.js:2177
```

配置是在 `.webpackrc.js` 添加：
```
extraBabelPlugins:['react-hot-loader/babel']
```

在 React Hot Loader V4 中本来需要加入 `hot(module)(App)` 来包裹
```jsx
import { hot } from 'react-hot-loader'

const App = () => 'xxx'

export default hot(module)(App)
```
但是我发现没有包裹也能够自动刷新。应该是 `umi.js` 下面这段代码的关系
```js
// hot module replacement
if (module.hot) {
  module.hot.accept('./router', () => {
    render();
  });
}
```
RHL 能够调用 HMR 的 API 来实现热加载。
这样在开发的时候不在 Dva 中的数据也可以保留状态了。

详情：[React-Hot-Loader](https://github.com/gaearon/react-hot-loader#appcontainer-vs-hot)
