### ISSUE TITLE
非 umi server 访问会不断刷新的问题

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#8500]
## 问题

1、dev 时，用户访问非 umi server host+port，会导致 HMR 失效，然后页面一致不停刷新
2、此问题答疑量不少

## 方案

TODO

**Comment by huarse** [comment]
我也遇到这个问题了，建议 websocket 的地址不要跟随当前 host

**Comment by coderwlin** [comment]
请问这个问题（非umi server 访问会不断刷新的问题）的解决方法是什么呢？

**Comment by coderwlin** [comment]
你好，请问上述这个问题（非umi server访问会不断出现刷新）的解决方法是什么呢？

**Comment by DragonLLLL-W** [comment]
https://umijs.org/docs/introduce/faq#%E4%BB%A3%E7%90%86%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90%E5%88%B0%E6%9C%AC%E5%9C%B0%E5%90%8E%E4%B8%80%E7%9B%B4-restart-%E5%88%B7%E6%96%B0%E9%A1%B5%E9%9D%A2
感觉可以尝试一下
