### ISSUE TITLE
[Bug] 当我的umi3 子应用开启dynamicImport: {} 的时候无法请求子应用的p_index 资源

### ISSUE THREAD

**Issue by lgh-qt** [umijs/umi#8518]
## What happens?

我的主应用在端口8000
子应用在端口8001
当我的子应用(umi3)开启了dynamicImport:{}的时候，主应用请求的还是8000/p_index,正确的应该是请求8001/p_index
请问我应该怎么操作
我在文档上并没有找到这一处理方案，也可能是我看漏了，请指正。
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

#app.js
![image](https://user-images.githubusercontent.com/33716733/178714215-5b5cfdf3-573a-4ec3-a7ef-d2e5df408a69.png)
#umirc.ts
![image](https://user-images.githubusercontent.com/33716733/178714332-7fb02270-541d-40ff-a326-891116879e97.png)

## Context

- **Umi Version**: 4.0.5
- **Node Version**:16.13.1
- **Platform**:macos

**Comment by sorrycc** [comment]
如果有复现才能看。

由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
