### ISSUE TITLE
bug: mime模块拒绝服务漏洞 - mime@1.3.6 - 间接引入 

### ISSUE THREAD

**Issue by Leo-Shaoqiang** [umijs/umi#8528]
### Versions

- dumi: 1.1.40
- node: v14.19.1
- npm: v6.14.16
- OS: windows 10
- Browser: 103.0.5060.114（正式版本） （64 位）

### Steps to reproduce
在拉下项目之后，安装依赖出现以下问题：
![image](https://user-images.githubusercontent.com/41110654/178884864-7393c4ac-b277-4f3d-932b-ecc504346d30.png)

### What is Expected?
该组件存在漏洞，是否需要升级组件以修复改问题。
完整报告：https://www.oscs1024.com/cd/1530221122195529728?sign=7c3f1921&report=1
漏洞详情：https://www.oscs1024.com/hd/MPS-2018-7211?s=m

**Comment by williamnie** [comment]
@sorrycc  这个漏洞在umi3版本上也存在，有大概的修复时间么？

**Comment by xiaohuoni** [comment]
umi3 没有修复计划，可以通过 resolutions 强制指定版本覆盖
