### ISSUE TITLE
Upgrade umi v3 to v4

### ISSUE THREAD

**Issue by mleister97** [umijs/umi#8542]
I tried umi 1-2 years ago and now need to update the project to v4. Unfortunately the documentation is in chinese and even with translator i don't understand word. I followed all the steps in the tutorial, but I don't know how to proceed with the plugins I use.

The following plugins I used from umi:
``` 
import {request} from "@@/plugin-request/request";
import {useModel} from "@@/plugin-model/useModel";
import {formatMessage} from "@@/plugin-locale/localeExports";
```

Could you guys please give me a hint how to include the plugins in v4? Thanks a lot. I appreciate it very much.

**Comment by cjdxhjj** [comment]
import all of things from @umijs/max

**Comment by mleister97** [comment]
@cjdxhjj thank you so much
