### ISSUE TITLE
[Bug] 关于打包的奇怪反应

### ISSUE THREAD

**Issue by phoema** [umijs/umi#8548]
打包时出现两种情况，
app.tsx中有一个组件SettingDrawer

我将此组件删掉，打包大小是100M，保留它的时候打包是15M。
但是保留的时候，打包后的页面右侧出现主题设置按钮，不想出现这个按钮。

目前的解决办法是靠一个无法进入的分支让他不出现的：
          {!props.location?.pathname?.includes('/login') && props.location?.pathname == 'test' && (
            <SettingDrawer
---
            />
          )}

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

**Comment by phoema** [comment]
4.0.7我上面的邪招还好用，升到4.0.9，不论什么方法，固定打包100M+
