### ISSUE TITLE
[Possible Bug] 重复挂载 layout

### ISSUE THREAD

**Issue by sun0day** [umijs/umi#8553]
## What happens?

当照着官网 https://umijs.org/docs/guides/routes 配置路由时，如果将 `src/layouts/index.tsx` 文件作为路由配置到 `.umirc.ts` 时，会和 umi 默认提供的 `global-layout` 根路由发生重复，从而导致 `src/layouts/index.tsx`组件会被分别挂载两次。

<img width="805" alt="image" src="https://user-images.githubusercontent.com/102238922/179145374-54cc9e1b-1516-4aac-87ec-d8598ffcd4d2.png">
<img width="440" alt="image" src="https://user-images.githubusercontent.com/102238922/179144890-5d517f79-e735-4850-898c-032d4832d93e.png">

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

case 比较简单，照着下面步骤即可复现

## How To Reproduce

**Steps to reproduce the behavior:** 
1. 执行 npx create-umi@latest 随便选个模版初始化工程
2. 配置 `.umirc.ts` 

```js
export default {
  routes: [
    {
      path: '/',
      component: '@/layouts/index'
    },
  ],
};
```
3. 修改 `src/layouts/index.tsx` 文件

```ts
export default function Layout() {
  return (
     <div>
      <h1>出现两次</h1>
      <Outlet />
    </div>
  );
}
```
4.  执行 `umi dev` 页面访问 `/` 路径，会发现页面上有两个 `h1` 

**Expected behavior** 

1.  `h1` 只挂载一次

## Context

- **Umi Version**: v4.0.1
- **Node Version**: v16.16.0
- **Platform**: macos

## 讨论

不清楚这是文档问题还是代码逻辑问题，如果是文档问题，建议更新下官网文档注明下这种 case 是不允许的; 如果是[代码](https://github.com/umijs/umi/blob/master/packages/preset-umi/src/features/tmpFiles/routes.ts#L137)问题，是不是可以考虑当 `.umirc.ts` 配置的 `routes` 字段非空时，不往里面加入 `global-layout`。

**Comment by xierenyuan** [comment]
layouts 是约定式路由布局文件 详细可以看这里  https://umijs.org/docs/guides/directory-structure#layoutsindextsx 可以选择使用他 或者 给你的layouts 改个名字

**Comment by sorrycc** [comment]
layouts/index.tsx 是约定的，自动加载，不要手动配。

**Comment by jin-benben** [comment]
文档这么写确实有让人迷惑，我也遇到这个重复挂载的问题，但是文档中一句没提，配置式路由文件路径不能这么配（例子还这么写，你说气不气）。

**Comment by codedart2018** [comment]
气呀　我说为啥重复两份。意思自定义路由不能嵌套？？？
