### ISSUE TITLE
[Bug] UMI_ENV 在v4 不生效

### ISSUE THREAD

**Issue by kokiy** [umijs/umi#8557]
## What happens?

v3 的功能 多环境多份配置 在v4 不生效
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your  

https://github.com/kokiy/umi4

 
## How To Reproduce

run `npm run build-prod` 我在 `prod.config.ts` 定义了 `NAME` 为'prod' ,查看打包之后的文件是 `local`
<img width="950" alt="image" src="https://user-images.githubusercontent.com/15773714/179197584-ebf32f82-d3cb-40d4-950b-bbbda82bcd5b.png">

## Context

- **Umi Version**: 4.0.7
- **Node Version**:16.13.2
- **Platform**: mac

**Comment by fz6m** [comment]
FYI：
 - https://github.com/umijs/umi/discussions/8341

**Comment by sorrycc** [comment]
.local 的优先级更好，这是 by design 的。

**Comment by xierenyuan** [comment]
local 有点问题 我修复一下
