### ISSUE TITLE
主应用vue，子应用umi4 报错 Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by chuangwei** [umijs/umi#8559]
在子应用的mount函数中，查找不到 props?.history
<img width="769" alt="image" src="https://user-images.githubusercontent.com/5902016/179203563-e9db33db-4b70-4c8d-9ee1-885835f81164.png">
![image](https://user-images.githubusercontent.com/5902016/179203667-e72922fe-c5bd-40ee-878b-bbe84b5aa08c.png)

**Comment by sorrycc** [comment]
请给复现步骤。

由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
