### ISSUE TITLE
[Bug] export 'request' (imported as 'request') was not found in 'umi'

### ISSUE THREAD

**Issue by max-end** [umijs/umi#8563]
## What happens?

export 'request' (imported as 'request') was not found in 'umi' (possible exports: ApplyPluginsType, Link, NavLink, Navigate, Outlet, PluginManager, __useFetcher, createBrowserHistory, createHashHistory, createHistory, createMemoryHistory, createSearchParams, history, matchPath, matchRoutes, renderClient, resolvePath, terminal, useAppData, useClientLoaderData, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRouteData, useRoutes, useSearchParams, useServerLoaderData)

## Mini Showcase Repository(REQUIRED)
`import yayJpg from '../assets/yay.jpg';
import { request } from 'umi';

import {useEffect} from "react";

export default function HomePage() {
    useEffect(()=>{
        request('https://test.com')
    },[])
    return (
        <div>
            <h2>Yay! Welcome to umi!</h2>
            <p>
                <img src={yayJpg} width="388"/>
            </p>
            <p>
                To get started, edit <code>pages/index.tsx</code> and save to reload.
            </p>
        </div>
    );
}`

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

import { request } from 'umi';

## Context

- **Umi 4.0.7**:
- **Node v16.3.0**:
- **Platform macOS**:

**Comment by LeoZRYau** [comment]
Hi, I have the same issues with you, have you solve it now?  how to solve this issue, thanks.
I add  `plugins: [require.resolve("@umijs/plugins/dist/request"),]`  and request: {} in .umirc.ts . but when I access the page, I got this error, 
```
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'applyPlugins')
getConfig
./src/.umi/plugin-request/request.ts:135
  132 | let config: RequestConfig;
  133 | const getConfig = (): RequestConfig => {
  134 |   if (config) return config;
> 135 |   config = getPluginManager().applyPlugins({
  136 |     key: 'request',
  137 |     type: ApplyPluginsType.modify,
  138 |     initialValue: {},
View compiled
getRequestInstance
./src/.umi/plugin-request/request.ts:145
  142 | 
  143 | const getRequestInstance = (): AxiosInstance => {
  144 |   if (requestInstance) return requestInstance;
> 145 |   const config = getConfig();
  146 |   requestInstance = axios.create(config);
  147 | 
  148 |   config?.requestInterceptors?.forEach((interceptor) => {
```
