### ISSUE TITLE
umi4+tailwindcss+headlessui/react

### ISSUE THREAD

**Issue by caicai1998** [umijs/umi#8564]
## What happens?

headlessui/react不能正常运行
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
https://codesandbox.io/s/interesting-silence-8013zp?file=/src/pages/Home/index.tsx

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

![image](https://user-images.githubusercontent.com/64702233/179346627-4243ce61-1afd-4268-a5d4-f178406f9a92.png)

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
在下次发布版本修复前，你可以通过关闭 mfsu 继续编码：

```ts
// .umirc.ts

export default {
  mfsu: false
}
```

注：`.umirc.ts` > `routes` 路由表中的 `./Access` 和 `./Table`  文件是缺失的，你应该从 `routes` 中删除它们。

**Comment by caicai1998** [comment]
>感谢回复

**Comment by caicai1998** [comment]
> 在下次发布版本修复前，你可以通过关闭 mfsu 继续编码：
> 
> ```ts
> // .umirc.ts
> 
> export default {
>   mfsu: false
> }
> ```
> 
> 注：`.umirc.ts` > `routes` 路由表中的 `./Access` 和 `./Table` 文件是缺失的，你应该从 `routes` 中删除它们。

感谢回复
