### ISSUE TITLE
[Bug] umi 2.11.3 版本build报错

### ISSUE THREAD

**Issue by sinianzhiren** [umijs/umi#8566]
## What happens?

umi2 build fail

[4/4] Building fresh packages...
success Saved lockfile.
Done in 487.76s.
+ npm run build

> lms@0.0.1 build /data1/jenkins_data/workspace/版本构建/1.PRE-版本交付/cms-node2/frontend
> cross-env umi build

?  error     Plugin user:node_modules/umi-plugin-react/lib/index.js initialize failed

Cannot find module '../modules/es6.object.to-string'
Require stack:
- /data1/jenkins_data/workspace/版本构建/1.PRE-版本交付/cms-node2/frontend/node_modules/core-js/library/fn/promise.js
- /data1/jenkins_data/workspace/版本构建/1.PRE-版本交付/cms-node2/frontend/node_modules/babel-runtime/core-js/promise.js
- /data1/jenkins_data/workspace/版本构建/1.PRE-版本交付/cms-node2/frontend/node_modules/babel-runtime/helpers/asyncToGenerator.js
- /data1/jenkins_data/workspace/版本构建/1.PRE-版本交付/cms-node2/frontend/node_modules/umi-plugin-react/node_modules/workbox-webpack-plugin/build/generate-sw.js
- /data1/jenkins_data/workspace/版本构建/1.PRE-版本交付/cms-node2/frontend/node_modules/umi-plugin-react/node_modules/workbox-webpack-plugin/

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:  2.11.2
- **Node Version**: node 12.16.1
- **Platform**: docker 
- **umi-plugin-react**: 1.8.4

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
