### ISSUE TITLE
[Bug] ts-in-node_modules no longer works in Umi 4

### ISSUE THREAD

**Issue by smddzcy** [umijs/umi#8569]
We just updated Umi from v3 to v4, and our custom rule with "ts-in-node_modules" no longer works:

```
config.module
      .rule('ts-in-node_modules')
      .test(/\.(js|jsx|ts|tsx)$/)
      .exclude.add(require('path').join(__dirname, '../node_modules'))
      .end()
      .include.clear()
      .add(require('path').join(__dirname, '../../../packages'));
```

Here's the config and the error message:

<img width="711" alt="image" src="https://user-images.githubusercontent.com/13895224/179360242-fddea9d5-28a5-4612-a906-20e7fc5de381.png">

<img width="582" alt="image" src="https://user-images.githubusercontent.com/13895224/179360256-5f4c8e6d-6384-4369-84ad-942d8f98c967.png">

The project is in a monorepo managed with Lerna, and we're simply trying to include a file from another package and include it in the webpack bundle.

**Comment by fz6m** [comment]
1. The `.ts` files in `node_modules` are translated by default. Not need config `chainWebpack`.

2.  Use `monorepoRedirect` to implement HMR.

    FYI : https://github.com/MoeYc/umi4-monorepo-hmr

**Comment by smddzcy** [comment]
Yeah the problem is not `.ts` files actually, we were using this to compile JSX in `.js` and `.ts` files. But as you can see from the screenshot, JSX in a `.js` file is no longer compiled.

**Comment by sorrycc** [comment]
If you need the files under node_modules to go babel compilation, try configuring them with `extraBabelIncludes`.

**Comment by smddzcy** [comment]
@sorrycc thanks a lot, that solves the issue!

By the way, there are 2 other changes that I couldn't see how to fix in Umi 4:

1. We're using https://github.com/pbeshai/use-query-params/ and the `QueryParamProvider` component needs to be put directly under `<Router>`. Is there any way to do this using Umi 4?

<img width="502" alt="image" src="https://user-images.githubusercontent.com/13895224/179557077-e7b969c7-bda2-
4172-a7cc-953d2ee2be33.png">

2. In our layouts, Umi was providing a `route` prop so we could directly give it to `ProLayout` in ant design pro. Now that prop is gone and we couldn't find a way to build that `route` prop. Currently the routes on the left menu are gone. How can we provide the `route` / `routes` prop to `ProLayout` in Umi 4?

**Comment by stefango** [comment]
> 1. The `.ts` files in `node_modules` are translated by default. Not need config `chainWebpack`.
> 2. Use `monorepoRedirect` to implement HMR.
>    FYI : https://github.com/MoeYc/umi4-monorepo-hmr

Umi 3 didn't offer configs like `monorepoRedirect`? Is there a way to implement HMR under umi3? I've configured `externalBabelIncludes`, but sub package that umi v3 app imports couldn't update.

**Comment by fz6m** [comment]
你可以参考这个给自己写一个插件：

https://github.com/umijs/umi/blob/master/packages/preset-umi/src/features/monorepo/redirect.ts
