### ISSUE TITLE
qiankun 主项目和子项目之间的切换，导致子项目被执行的次数增多

### ISSUE THREAD

**Issue by ybrelax** [umijs/umi#8570]
## What happens?
qiankun 主项目和子项目之间的切换，随着切换次数增多导致子项目被执行的次数增多

>测试代码仓库
项目测试代码为官方的例子：
 https://github.com/umijs/umi/tree/master/examples/ 的 max 和 qiankun-slave，前者是主应用，后者是子应用。

![image](https://user-images.githubusercontent.com/31029938/179384969-4a106727-a3b0-4b77-a4af-97efa917aae1.png)
![image](https://user-images.githubusercontent.com/31029938/179385095-9d6d30cf-01b1-4bad-88f8-83eb416aea7a.png)

而且卸载的时候抛出的警告，也能看下吗
![image](https://user-images.githubusercontent.com/31029938/179385038-64787eeb-af42-4d2a-b67b-ebbab2a430e2.png)
这个卸载的方法能调整下不？

## Context
- **"@umijs/max": "4.0.7"

**Comment by feibi** [comment]
每次切换渲染就多增加一次

**Comment by xierenyuan** [comment]
> ## What happens?
> qiankun 主项目和子项目之间的切换，随着切换次数增多导致子项目被执行的次数增多
> 
> > 测试代码仓库
> > 项目测试代码为官方的例子：
> > https://github.com/umijs/umi/tree/master/examples/ 的 max 和 qiankun-slave，前者是主应用，后者是子应用。
> 
> ![image](https://user-images.githubusercontent.com/31029938/179384969-4a106727-a3b0-4b77-a4af-97efa917aae1.png) ![image](https://user-images.githubusercontent.com/31029938/179385095-9d6d30cf-01b1-4bad-88f8-83eb416aea7a.png)
> 
> 而且卸载的时候抛出的警告，也能看下吗 ![image](https://user-images.githubusercontent.com/31029938/179385038-64787eeb-af42-4d2a-b67b-ebbab2a430e2.png) 这个卸载的方法能调整下不？
> 
> ## Context
> * **"@umijs/max": "4.0.7"

可以先把 react 降到 17 版本, 18版本的卸载 最近会支持

**Comment by ybrelax** [comment]
大概什么时候能修复哈，4.0.9版本吗？
