### ISSUE TITLE
externals 设置 'react-dom': 'ReactDOM'  不生效

### ISSUE THREAD

**Issue by wangxingkang** [umijs/umi#8572]
## What happens?

问题如上

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/14227679/179391691-2ea554dd-82dc-4612-a21e-f5b2aaab59a4.png">

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

1. pnpm dlx create-umi@latest 
2. 选择  Simple App
3. 添加如下配置
```
externals: {
    react: 'React',
    'react-dom': 'ReactDOM',
  },
  headScripts: [
    'https://unpkg.com/react@17.0.2/umd/react.production.min.js',
    'https://unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js',
  ]
```
4. 执行 `ANALYZE=1 umi build`

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:  v4.0.7
- **Node Version**: v16.15.1
- **Platform**: mac

**Comment by Niofh** [comment]
题主最后怎么解决呢，我还没有找到方法

**Comment by wangxingkang** [comment]
umi 还没发版 着急的话 可以用 每天发布的验证版本
