### ISSUE TITLE
TypeError: Cannot read property 'rimraf' of undefined 

### ISSUE THREAD

**Issue by 595624187** [umijs/umi#8577]
重装了依赖然后就报这个错。
![image](https://user-images.githubusercontent.com/38000873/179433238-fb169f81-d73b-4fa7-a1f7-57d3a877c080.png)
![image](https://user-images.githubusercontent.com/38000873/179433255-a3e42c74-89d1-4c0d-87a4-b7b69523e0ea.png)

**Comment by sorrycc** [comment]
@PeachScript 看下，dumi + umi 4 不能共用吗？

**Comment by 595624187** [comment]
> 

我把umi降到@3.5.0就好了

**Comment by sorrycc** [comment]
已在 canary 版本中修复。
