### ISSUE TITLE
IE9环境下，页面内链接跳转（Umi/Link）页面会全部刷新问题

### ISSUE THREAD

**Issue by JevonYang** [umijs/umi#858]
在自己写的应用中，页面内的跳转会导致页面中所有元素刷新，相应的请求也会重新请求，但是在Chrome环境下不会，请问有没有解决办法，或者相关的资料链接参考一下。

## 描述
我的应用类似于ant-design-pro有layout，Header、SiderMenu用的是React.PureComponent。在IE9的环境下，点SiderMenu中的菜单链接（使用Umi/Link）显示另外一个组件，此时会重新渲染整个页面，layout中的请求后台数据也会重新请求，例如menu、currenUser都是重新请求。

这些情况在chrome、firefox环境下都不会出现。

我在IE9的环境下，看了一下weibo.com，链接跳转不会导致全屏刷新，应该不是IE9的问题。

**Comment by sorrycc** [comment]
试过，不能重新啊，我猜应该是你的代码问题。

**Comment by JevonYang** [comment]
> 试过，不能重新啊，我猜应该是你的代码问题。

问题找到了：有一处link还是使用dva/router，如果是用umi/link的link就没有问题。

感谢！
