### ISSUE TITLE
[Bug] umi@4 config.ts配置文件的ts类型报错问题汇总

### ISSUE THREAD

**Issue by mumuwen520** [umijs/umi#8580]
## What happens?

项目从Umi3 升级到 Umi4 后，config.ts配置文件里出现了很多ts类型问题，但是查看数据格式和对应的类型声明又并没有问题。

这里是我项目里遇到的一些问题：

1、
<img width="730" alt="image" src="https://user-images.githubusercontent.com/37792954/179441546-8f53e77d-0eb4-47c9-a30d-f5a56ee5dd1f.png">

2、boolean值会报错，改成undefined和string就好了。
<img width="738" alt="image" src="https://user-images.githubusercontent.com/37792954/179441596-d62a33f2-2f73-4589-923f-09f07cf64faf.png">

## Context

- **Umi Version**:"^4.0.7",  
- **Node Version**: v14.17.0
- **Platform**:

**Comment by sorrycc** [comment]
修复了。
