### ISSUE TITLE
[Bug] patchClientRoutes dose not support patch route with redirect

### ISSUE THREAD

**Issue by wangzhengbo** [umijs/umi#8591]
export const patchRoutes = ({ routes }) => {
      routes[0].routes[0].routes = [
        {
          path: '/',
          redirect: '/homepage',
          exact: true,
        },
        ...routes[0].routes[0].routes,
      ];
}
以上代码在umi 3没问题。访问/会被重定向到/homepage。在umi 4做类似的处理不会生效。umi4的routes结构体中的元素可能包含了routes和children属性，不管是修改哪个里面的内容，都不生效。

**Comment by sorrycc** [comment]
使用 patchClientRoutes。
