### ISSUE TITLE
[Bug]直接使用svg地址作为img地址报错

### ISSUE THREAD

**Issue by 94ashui** [umijs/umi#8593]
## What happens?

通过create-umi创建的模板直接使用asserts下面的svg文件作为img地址报错

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
![image](https://user-images.githubusercontent.com/89236888/179497964-f91f6fc1-6aa5-4989-be69-472e8e8ad599.png)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
通过create-umi创建vue项目即可
**Expected behavior** 1. 2.
直接使用svg图片不报错

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
通常是用法不对，怎么使用的，给个最简复现。

由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

**Comment by 94ashui** [comment]
@sorrycc https://github.com/94ashui/umi-vue.git 复现仓库
