### ISSUE TITLE
umi@4 版本安卓手机浏览器有问题

### ISSUE THREAD

**Issue by lecd** [umijs/umi#8598]
umi@4 版本安卓手机浏览器有问题

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

**Comment by ratelgogo** [comment]
要配置
`{
    targets: {
  andriod: 4
}
}`

**Comment by hanwenbo** [comment]
> config中添加配置试试，默认的低版本安卓是不兼容的 `{ targets: { andriod: 4 } }`


config中添加配置试试，默认的低版本安卓是不兼容的
{ targets: { andriod: 4 } }
没有这个 targets吧

**Comment by ratelgogo** [comment]
> > config中添加配置试试，默认的低版本安卓是不兼容的 `{ targets: { andriod: 4 } }`
> 
> config中添加配置试试，默认的低版本安卓是不兼容的 { targets: { andriod: 4 } } 没有这个 targets吧

https://esbuild.github.io/api/#target
哈哈，好像是没有的，安卓手机也是用的浏览器，指定需要支持的版本就行了，umi的文档写得还是太简单了
