### ISSUE TITLE
[Bug] 配置publicPath相对路径后白屏

### ISSUE THREAD

**Issue by txp1035** [umijs/umi#8599]
## What happens?

umi4配置publicPath:'./',后页面白屏。umi3正常。dev服务是webpack
配置前：
![image](https://user-images.githubusercontent.com/9554297/179518877-4efca89b-a763-4407-81d0-5c53492ed13e.png)
配置后：
![image](https://user-images.githubusercontent.com/9554297/179519081-74f1b6ec-fa53-4775-a242-e3860ac0ddfc.png)
看情况是配置后umj.js解析成了html的文件？ @sorrycc 

## Mini Showcase Repository(REQUIRED)

 
![image](https://user-images.githubusercontent.com/9554297/179519207-35883e8a-918c-4a08-b354-8bb8d6b74282.png)

## How To Reproduce

1. 在umi example文件test-test中增加一个属性
`publicPath:'./`
2. 运行 npx umi dev
3. 打开网页就是错误

## Context

- **Umi Version**: 4.0.0-canary.20220718.2
- **Node Version**: v16.15.0
- **Platform**: mac

**Comment by txp1035** [comment]
静态资源因为也用的./，现在方案也是基于process.env.NODE_ENV来做了，话说能了解下dev不支持./的原因吗？

**Comment by xiaohuoni** [comment]
https://v3.umijs.org/docs/faq#%E9%83%A8%E7%BD%B2%E5%9C%A8%E9%9D%99%E6%80%81%E6%96%87%E4%BB%B6%E6%9C%8D%E5%8A%A1%E6%97%B6%EF%BC%8C%E5%A6%82%E6%90%AD%E9%85%8D-cordova-%E4%BD%BF%E7%94%A8%EF%BC%8C%E9%A1%B5%E9%9D%A2%E7%A9%BA%E7%99%BD%EF%BC%8C%E6%8F%90%E7%A4%BA%E6%89%BE%E4%B8%8D%E5%88%B0%E6%96%87%E4%BB%B6%EF%BC%9F
需要配置

**Comment by Hfimy** [comment]
It should not be checked during umi setup. @sorrycc
