### ISSUE TITLE
[Bug] umi webpack 不生效，提示Invalid command webpack, it's not registered

### ISSUE THREAD

**Issue by fantasy525** [umijs/umi#8603]
## What happens?

我想查看 webpack 的配置，参考文档 https://v3.umijs.org/zh-CN/docs/cli 使用 umi webpack --rules
报错提示 AssertionError [ERR_ASSERTION]: Invalid command webpack, it's not registered.

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 
1. 安装 umi, yarn add global umi
2. yarn add global webpack
3. umi webpack --rules

**Expected behavior** 出现 webpack 配置

## Context

- **Umi Version**:4.0.7
- **Node Version**: 16.13.0
- **Platform**:  macos

**Comment by sorrycc** [comment]
umi 4 没有提供这个命令。
