### ISSUE TITLE
node_modules里面的组件引用问题

### ISSUE THREAD

**Issue by yaodong5063** [umijs/umi#8616]
我在node_modules里的组件里面使用import styles from "./index.less";
这个styles 获取不到

使用最新4.0.7版本的包
稍等传先复现包

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
