### ISSUE TITLE
[Bug] 获取路由错误

### ISSUE THREAD

**Issue by txp1035** [umijs/umi#8618]
## What happens?

![123](https://user-images.githubusercontent.com/9554297/179785122-70003356-f979-4b83-91f1-56c14fec08de.gif)
路由改变了，但是通过history获取的location中的pathname并没有改变，拿不到最新的路由值
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

example中的ant-design-pro
![image](https://user-images.githubusercontent.com/9554297/179785549-953bcf04-001c-4b87-a39d-4786761f3044.png)

## How To Reproduce

1. 直接启动
2. 切换路由，看打印的路由

## Context

- **Umi Version**: 4.0.0-canary.20220718.2
- **Node Version**: v16.15.0
- **Platform**: mac

**Comment by txp1035** [comment]
刚开始以为是不是创建的实例和实际拿到的不一样，试了下给模板加了标识符，发现实例是刚开始创建的那个。
![image](https://user-images.githubusercontent.com/9554297/179786987-67df5013-dd0c-4b77-a0df-4beea796b80c.png)
然后去单独测试history，单独测试路由是改变了的

**Comment by txp1035** [comment]
@sorrycc

**Comment by txp1035** [comment]
从表现来看像是深拷贝了，pathname一直是刚开始创建路由时候的值，esm导出应该是浅拷贝啊

**Comment by sorrycc** [comment]
history 是静态的，组件或 hooks 里用 useLocation 取，其他地方就用 window.location 获取吧。
