### ISSUE TITLE
[Bug] 根据配置文档配置clientLoader 后没有反应

### ISSUE THREAD

**Issue by ReinhardChen93** [umijs/umi#8619]
## What happens?

根据配置文档配置clientLoader 后没有反应
useClientLoaderData 也没有返回数据

![image](https://user-images.githubusercontent.com/43949619/179789082-5a967713-a5bc-4fd6-a646-5b4f1934d411.png)

![image](https://user-images.githubusercontent.com/43949619/179789297-36bb415c-e760-4cbf-84ae-f77a9175c4f5.png)

## Context

- **Umi Version**: "@umijs/max": "^4.0.7",
- **Node Version**: v16.14.0
- **Platform**: window10

**Comment by imwangming** [comment]
好像 clientLoader 中不能使用 hooks

**Comment by fz6m** [comment]
`clientLoader` 是一个函数，会在 hook 中运行，不能嵌套 hooks，使用方法可参考：

https://github.com/umijs/umi/blob/8e337a0a5d87096621be29fc3d2fd36ca6f38853/examples/client-loader/src/pages/index.tsx#L41-L49
