### ISSUE TITLE
[Bug] UMI4 missing viewbox when loading svg 

### ISSUE THREAD

**Issue by kenzung** [umijs/umi#8628]
## What happens?
svg load as component missing viewBox

![image](https://user-images.githubusercontent.com/6317307/179890588-b30a2e53-ff3a-42f3-9332-6dc666a607e9.png)
viewBox attribute is missing here

![image](https://user-images.githubusercontent.com/6317307/179889229-b95918c1-6335-43fe-b3d6-ce965b699846.png)
I use this way to load svg

![image](https://user-images.githubusercontent.com/6317307/179889369-a6add60e-1a42-4a06-8ea0-9f532259da48.png)
this is the original file with the viewBox attr

## Mini Showcase Repository(REQUIRED)
import svg as ReactComponent

## How To Reproduce
import svg as ReactComponent

- **Umi Version**:  4.0.6
- **Node Version**: 14
- **Platform**: MACOS

**Comment by fz6m** [comment]
你需要 viewBox 做啥？这是 svgo 的默认 svg 优化策略。

```ts
// .umirc.ts

export default {
  svgo: {
    plugins: [
      {
        name: 'preset-default',
        params: {
          overrides: {
            // more options see https://github.com/svg/svgo#built-in-plugins
            removeViewBox: false,
          },
        },
      },
      'prefixIds',
    ]
  }
}
```

**Comment by kenzung** [comment]
> ```ts
> svgo
> ```

谢谢，刚升级UMI4，发现配置稍有不同，close了

**Comment by laeni** [comment]
我从umi3迁移都umi4也出现相同的问题，升级后发现svg图片大小发生了变化，因为umi3中加载的svg是有viewbox的，所以要想不动太多代码的话还是需要在umi4中也需要保留viewbox属性。

**Comment by fz6m** [comment]
需要给一个最小复现。

**Comment by cxOrz** [comment]
> 需要给一个最小复现。

在给复现的过程中找到了原因，我的错哈哈，自己不小心把viewBox属性传空覆盖了
