### ISSUE TITLE
[Bug] routers中不同路由使用相同组件不能重新渲染

### ISSUE THREAD

**Issue by imwangming** [umijs/umi#8631]
` routes: [
    { path: '/a', component: '@/pages/index' },
    { path: '/b', component: '@/pages/index' },
  ]
`
例如a、b两个共同引入index页面，路由切换跳转后，页面会缓存上一次的结果，请问这种情况如何处理？

**Comment by fz6m** [comment]
```ts
// pages/index.tsx

import { useEffect, useState } from 'react'
import { usePrevious } from 'ahooks'
import { useLocation, useNavigate } from 'umi'

const EMPTY = { a: 1 }

export default function HomePage() {
  const [state, setState] = useState(EMPTY)

  const location = useLocation()
  const prevPathname = usePrevious(location.pathname)
  useEffect(() => {
    if (prevPathname && prevPathname !== location.pathname) {
      // reset state
      setState(EMPTY)
    }
  }, [location.pathname])

}
```

or:

```ts
// pages/index.tsx

import C from '../components/C'

export default function HomePage() {
  const location = useLocation()

  return (
    <C key={location.pathname} />
  )
}
```

**Comment by imwangming** [comment]
> ```ts
> // pages/index.tsx
> 
> import { useEffect, useState } from 'react'
> import { usePrevious } from 'ahooks'
> import { useLocation, useNavigate } from 'umi'
> 
> const EMPTY = { a: 1 }
> 
> export default function HomePage() {
>   const [state, setState] = useState(EMPTY)
> 
>   const location = useLocation()
>   const prevPathname = usePrevious(location.pathname)
>   useEffect(() => {
>     if (prevPathname && prevPathname !== location.pathname) {
>       // reset state
>       setState(EMPTY)
>     }
>   }, [location.pathname])
> 
> }
> ```
> 
> or:
> 
> ```ts
> // pages/index.tsx
> 
> import C from '../components/C'
> 
> export default function HomePage() {
>   const location = useLocation()
> 
>   return (
>     <C key={location.pathname} />
>   )
> }
> ```

谢谢大师指点迷经
