### ISSUE TITLE
umi4不支持@umijs/plugin-analytics？

### ISSUE THREAD

**Issue by qingfengmy** [umijs/umi#8635]
报错如下：
```
 AssertionError [ERR_ASSERTION]: Invalid config keys: analytics
```

**Comment by hqin06** [comment]
有相同错误
umi version 4.0.53 
node version v16.18.1
报错信息：fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: analytics

配置代码：
    analytics: {
        plugins: ['@umijs/plugins/dist/analytics'],
        baidu: '5a66cxxxxxxxxxx9e13',
    },

**Comment by hqin06** [comment]
@xiaohuoni

**Comment by xiaohuoni** [comment]
```diff
+ plugins: [require.resolve('@umijs/plugins/dist/analytics')],
analytics: {
- plugins: ['@umijs/plugins/dist/analytics'],
baidu: '5a66cxxxxxxxxxx9e13',
},
```

**Comment by xiaohuoni** [comment]
> Parse config file failed

这个错误一般与配置无关，多是在 文件中 import 了一些什么文件导致的，你可以从这个角度看看问题，或者给一个 git demo
