### ISSUE TITLE
[Bug] Cannot find module 'react-refresh/babel'

### ISSUE THREAD

**Issue by qiliangya** [umijs/umi#8637]
## What happens?
在monorepo结构中， 无法运行

## Mini Showcase Repository(REQUIRED)

https://github.com/qiliangya/umi-monorepo-bug

## Context

- **4.0.7**:
- **16.15.0**:
- **mac**:

**Comment by fz6m** [comment]
monorepo 结构不标准，一个正常的例子：

```bash
 > root
 - apps
    - project-a
    - project-b
    - ...
 - package.json
 - pnpm-workspace.yaml
 - pnpm-lock.yaml
```

```yaml
# pnpm-workspace.yaml

packages:
  - apps/*
```
