### ISSUE TITLE
[Bug] umi4 dva插件问题反馈

### ISSUE THREAD

**Issue by dong-516** [umijs/umi#8638]
## What happens?

umi 4 model中无法引入Reducer,Effect等类

## Mini Showcase Repository(REQUIRED)
https://github.com/dong-516/umi4_test

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

umi 3 .umi/plugin-dva 目录如下图
![image](https://user-images.githubusercontent.com/42528738/179948210-b9f28487-3673-4000-a3fc-06366dcd2e2f.png)
umi4 .umi/plugin-dva 目录如下图
![image](https://user-images.githubusercontent.com/42528738/179948379-a139bbf9-64ff-4e58-9950-92676f2cbf2d.png)

问题是connect.ts不见了，导致Effect,Reducer等一些列dva的类型申明不见了，想在model中引入，报错，如下图
![image](https://user-images.githubusercontent.com/42528738/179948942-b4e38c16-2575-4aa5-9efa-af8bdef0b00c.png)

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:4.0.7
- **Node Version**:16.15.1
- **Platform**:windows 11

**Comment by yunyi1895** [comment]
同样遇到了v4.0.8，希望快点解决

**Comment by mumuwen520** [comment]
同样遇到了 v4.0.8 希望快点解决

**Comment by hmilin** [comment]
同求🥺

**Comment by huangsheng001** [comment]
同样的问题 4.0.12

**Comment by HaiBoWon** [comment]
改为 import { xxx } from '@umijs/max'

> ## What happens?
> umi 4 model中无法引入Reducer,Effect等类
> 
> ## Mini Showcase Repository(REQUIRED)
> https://github.com/dong-516/umi4_test
> 
> > Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
> 
> ## How To Reproduce
> umi 3 .umi/plugin-dva 目录如下图 ![image](https://user-images.githubusercontent.com/42528738/179948210-b9f28487-3673-4000-a3fc-06366dcd2e2f.png) umi4 .umi/plugin-dva 目录如下图 ![image](https://user-images.githubusercontent.com/42528738/179948379-a139bbf9-64ff-4e58-9950-92676f2cbf2d.png)
> 
> 问题是connect.ts不见了，导致Effect,Reducer等一些列dva的类型申明不见了，想在model中引入，报错，如下图 ![image](https://user-images.githubusercontent.com/42528738/179948942-b4e38c16-2575-4aa5-9efa-af8bdef0b00c.png)
> 
> **Steps to reproduce the behavior:** 1. 2.
> 
> **Expected behavior** 1. 2.
> 
> ## Context
> * **Umi Version**:4.0.7
> * **Node Version**:16.15.1
> * **Platform**:windows 11

**Comment by dong-516** [comment]
> 改为 import { xxx } from '@umijs/max'
一样的报错
![image](https://user-images.githubusercontent.com/42528738/185517826-7f572f6c-2104-46f4-bcbd-e1cfe0baacf0.png)
即使升级到4.0.13
![image](https://user-images.githubusercontent.com/42528738/185517848-ad7489c3-b0a4-4bd4-8397-c33dd5c37aa1.png)

**Comment by dong-516** [comment]
> 改为 import { xxx } from '@umijs/max'
> 
> >一样的报错
>>
>>![image](https://user-images.githubusercontent.com/42528738/185517998-fa05db0b-2790-42a8-8a93-17b7e3b39fcf.png)
>>即使升级到4.0.13
>>
>>![image](https://user-images.githubusercontent.com/42528738/185518029-4a6dd6d8-e13c-42e3-8e42-72a2a13bd23d.png)
@HaiBoWon

**Comment by HaishengLiang** [comment]
+1

**Comment by liangskyli** [comment]
import { useDispatch, useSelector } from 'umi';
这两个类型也没用TS类型

**Comment by BennnZhang** [comment]
3.5.30同

**Comment by jounzhang** [comment]
同求，最终如何解决啊大神们？

**Comment by wangwufan** [comment]
求助，使用了umi4，我这里 连connect都引用不了，
![image](https://user-images.githubusercontent.com/12657738/189014147-d583575e-af05-4861-8b43-f55ac1d68500.png)

**Comment by wangwufan** [comment]
这个问题太扯了，我放弃升级umi4了，累

**Comment by wangwufan** [comment]
升级卡在这里了，关注中，

**Comment by zhangXiaolizi** [comment]
@sorrycc 您好，确实是没有Effect和Reducer这些类型了，在@umijs/max中也没有，这个是个bug呢还是我们用的方式不对啊？用ts定义dva的model，不能引入类型好多红线啊。求个解决方法。

**Comment by travelclover** [comment]
各位大神有解决了的吗~头发掉的只剩一半了还没解决~

**Comment by jounzhang** [comment]
我是从原始包中引用的，程序能正常工作，但是就没有 all from umi的既视感了

**Comment by Sissi-ok** [comment]
有解决办法了么？import { useDispatch, useSelector } from '@umijs/max'; 
也同样Module '"@umijs/max"' has no exported member 'useSelector'.

**Comment by wangwufan** [comment]
这么久才加上这个类型输出，是原打算抛弃dva的吗？



***@***.***
 
发件人： chencheng (云谦)
发送时间： 2022-09-28 12:00
收件人： umijs/umi
抄送： wangwufan; Comment
主题： Re: [umijs/umi] [Bug] umi4 dva插件问题反馈 (Issue #8638)
Closed #8638 as completed via #9444.
