### ISSUE TITLE
[Feature Request] history难以维护

### ISSUE THREAD

**Issue by skczjun** [umijs/umi#8651]
有个需求，启动项目后进入A页面有多条不同路由，如A->B->C->D->A，A->B->A，A->B->E->A，但最终仍会回到A页面，从A页面再按浏览器后退按钮，希望不返回到上一级路由E、D、B，但从目前umijs的构架，很难处理这个需求。有什么改善的方案吗

**Comment by fz6m** [comment]
```ts
import { useNavigate } from 'umi'

const navigate = useNavigate()

navigate('/path', {
  replace: true
})
```

react router v6 中，应该使用 `useNavigate` 切换路由，在最后一个将跳转 `A` 的页面进行 `navigate` 时，`replace` 置为 `true` 即可防止浏览器后退回跳。

**Comment by bowencool** [comment]
把 PD 打一顿就好了
