### ISSUE TITLE
[Bug] Can not get history if not under pages folder

### ISSUE THREAD

**Issue by BH-M87** [umijs/umi#8655]
## What happens?
![CleanShot 2022-07-21 at 10 43 23@2x](https://user-images.githubusercontent.com/16903266/180119259-647e8b34-987e-4254-9ce8-0ec5b93c89ff.png)

## Mini Showcase Repository(REQUIRED)
https://github.com/BH-M87/umi4-bug-showcase

## How To Reproduce

1. `import { history } from 'umi';`
2. `console.log(history);`
3. if under pages folder, the history can be accessed but if out of pages folder, history is undefined.

## Context

- **Umi Version**:  "@umijs/max": "^4.0.6", 
- **Node Version**: v16.14.2
- **Platform**: MacBook Pro (13-inch, M1, 2020)

**Comment by BH-M87** [comment]
<img width="769" alt="CleanShot 2022-07-21 at 15 25 36@2x" src="https://user-images.githubusercontent.com/16903266/180157089-ca937f04-84bd-44f0-af39-eeb9337476f3.png">

大致看了下，原因在这，history是在render中才初始化了出来，但是我有些请求是在render前写的，判断没登录要history.push('/login')，这里的history就一直是undefined。umi3不会有这个问题的。
<img width="572" alt="CleanShot 2022-07-21 at 15 27 28@2x" src="https://user-images.githubusercontent.com/16903266/180157127-43ffbc41-ee66-40df-8ebf-f1481b898b7c.png">

临时可以通过手动调用下createHistory来fix：
![CleanShot 2022-07-21 at 15 38 38@2x](https://user-images.githubusercontent.com/16903266/180157507-c99bfeec-0962-45f6-8c43-f5fbe22da415.png)

**Comment by BH-M87** [comment]
https://github.com/BH-M87/umi4-bug-showcase

Add Mini Showcase Repository!

**Comment by xinpingwang** [comment]
> 大致看了下，原因在这，history是在render中才初始化了出来，但是我有些请求是在render前写的，判断没登录要history.push('/login')，这里的history就一直是undefined。umi3不会有这个问题的。

确实 history 在 render 之后才创建，目前看来除了  umi 内部做调整之外没有什么好的方式

---
示例仓库的问题 2 是代码使用问题：

https://github.com/BH-M87/umi4-bug-showcase/blob/0fa7423771c349ce64d38d8a71812ec491b150a6/src/app.ts#L7-L9 

参照[文档](https://umijs.org/docs/api/runtime-config#onroutechange-routes-clientroutes-location-action-)，正确的方式应该是：

```javascript
export function onRouteChange({ location, clientRoutes, routes, action }) {
  console.log(location.pathname);
}
```

**Comment by BH-M87** [comment]
@xinpingwang history还是应该在定义的时候就初始化呀，history是否可用和render之间并不存在相互依赖关系的。

第二个问题，我知道传入的参数中是有location的，这个问题不是在这个方法中使用发现的，而是在一个函数中，render里面判断了是否高亮，如下图，location变化，layout中的render方法中去取`history.location.pathname`，一直都是首次进入的那个pathname。
<img width="492" alt="CleanShot 2022-07-25 at 16 45 18@2x" src="https://user-images.githubusercontent.com/16903266/180736318-c45c7a59-4610-4f7d-9a0f-8e71b2e8cfb0.png">

这里写在`onRouteChange `中只是因为是个showcase的demo来展示问题的。

**Comment by BH-M87** [comment]
@sorrycc Please help and have a look at this issue.

**Comment by sorrycc** [comment]
Where you can't use history, if you're getting path, just use `location` to get it.

**Comment by BH-M87** [comment]
> 

@sorrycc The fact is you can get the `history.location.pathname`, but it won't change when route change.

**Comment by BH-M87** [comment]
Even use in render method

**Comment by BH-M87** [comment]
@sorrycc If use `location` to get the path, the `base` config of `history` is not considered.
