### ISSUE TITLE
[Bug] layout rightContentRender 位置异常

### ISSUE THREAD

**Issue by zeusyaoyao** [umijs/umi#8663]
## What happens?

umi4 在 app.tsx 下 layout 配置 rightContentRender，渲染出来的组件在页面左下角而不是右上角

app.ts 配置

<img width="939" alt="Screenshot 2022-07-21 at 6 05 15 PM" src="https://user-images.githubusercontent.com/109730486/180188368-8d900df8-9dc6-47db-84b1-63087bc8d377.png">

.umirc.ts 配置
<img width="447" alt="Screenshot 2022-07-21 at 6 06 04 PM" src="https://user-images.githubusercontent.com/109730486/180188537-f1a72989-f831-47b8-a5e9-6d7874fe3f9d.png">

具体效果
<img width="806" alt="Screenshot 2022-07-21 at 6 07 06 PM" src="https://user-images.githubusercontent.com/109730486/180188745-3418b59c-9519-4c8d-a471-5683476d25ac.png">

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

按照官网快速开始 + 上面的配置即可复现

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- 4.0.6
- **Node Version**:
- 16
- **Platform**:

**Comment by jianjian-commits** [comment]
你可以试试 navTheme: 'dark'也没效果，我得到的反馈是 side模式下，header也没有了，dark模式也没有了，感觉变化有点大啊，我们这产品ui都不能接受light模式～～～

**Comment by xierenyuan** [comment]
> 你可以试试 navTheme: 'dark'也没效果，我得到的反馈是 side模式下，header也没有了，dark模式也没有了，感觉变化有点大啊，我们这产品ui都不能接受light模式～～～

默认 pro-layout 使用的是 v7 在项目安装 `@ant-design/pro-layout` 依赖版本 为 `6.38.15` 比如yarn 客户端 `yarn add @ant-design/pro-layout@6.38.15 -S`

**Comment by jianjian-commits** [comment]
他是会先去读取根目录下的pro-layout ,如果没有再去读取pro-components/pro-layout嘛？ 只要pro-layout版本>6.38.7就可以了

**Comment by xierenyuan** [comment]
> 他是会先去读取根目录下的pro-layout ,如果没有再去读取pro-components/pro-layout嘛？ 只要pro-layout版本>6.38.7就可以了

有一个读取规则 具体可以看这里 https://github.com/umijs/umi/blob/master/packages/plugins/src/layout.ts#L54

**Comment by 1337968347** [comment]
是不是产品  & 研发对 right 有什么误解？
