### ISSUE TITLE
[Bug] @umijs/max": "^4.0.7 升 @umijs/max": "^4.0.8 报错

### ISSUE THREAD

**Issue by gggso** [umijs/umi#8664]
错误如下
<img width="748" alt="image" src="https://user-images.githubusercontent.com/6212790/180243619-5f38ad74-1921-45c9-90bf-06978e6cf111.png">

mf-va_remoteEntry.js:1688 Uncaught (in promise) Error: Module ".//Users/gggso/wwwroot/meiranlive_business/node_modules/.pnpm/@umijs+utils@4.0.8/node_modules/@umijs/utils/compiled/strip-ansi/index.js" does not exist in container.
while loading ".//Users/gggso/wwwroot/meiranlive_business/node_modules/.pnpm/@umijs+utils@4.0.8/node_modules/@umijs/utils/compiled/strip-ansi/index.js" from webpack/container/reference/mf
    at mf-va_remoteEntry.js:1688:11f

**Comment by xierenyuan** [comment]
删除 项目 `node_modules/.cache` 试试呢

**Comment by gggso** [comment]
帮啊。。删掉 node_modules/.cache 就好了
