### ISSUE TITLE
[Bug] umi React项目中使用react-monaco-editor没有输入提示

### ISSUE THREAD

**Issue by PLUTO06210331** [umijs/umi#8680]
![image](https://user-images.githubusercontent.com/33271366/180410999-0e7d8f67-26a1-4cab-896c-592aedf46372.png)
![image](https://user-images.githubusercontent.com/33271366/180411048-c2c8c418-6e37-41d3-a3cf-6a65d065fcf0.png)

**Comment by xinpingwang** [comment]
看代码是使用了 [react-monaco-editor](https://github.com/react-monaco-editor/react-monaco-editor/) 这个库，其代码本身使用 ts 编写，相关类型定义可以参考 [src/types.ts](https://github.com/react-monaco-editor/react-monaco-editor/blob/3cf4d02ea08ac7e102a27fd3e5507c68947544cf/src/types.ts#L65)。

可以尝试以下方法解决：

- 如果是编辑器完全没有提示，可以关掉重启试试；
- 如果是代码类型补全不够完善，可以考虑到对应仓库提 MR，补全对应类型定义。

> PS: 第三方组件能否补全和使用什么框架没有关系，而是和该组件库的类型定义以及所使用的编辑器有关

**Comment by CloudVolume** [comment]
chainWebpack:memo => {
    memo.plugin('monaco-editor-webpack-plugin')
        .use(new MonacoWebpackPlugin({
          languages: ["json", "javascript", "typescript"]
        }))
  }

import MonacoEditor from "react-monaco-editor";
import * as monaco from 'monaco-editor'
export {monaco}
这样调用，monaco-editor-webpack-plugin 版本7.0.1，需要把插件中mocaco给export出来，与插件方法导出有关系，与框架无关

**Comment by Lillian-Yo** [comment]
如果sql需要提示怎么办

**Comment by Lillian-Yo** [comment]
> 如果sql需要提示怎么办

而且我是用的vite
