### ISSUE TITLE
[Bug] @max/umijs husky eslint error

### ISSUE THREAD

**Issue by skyunBoss** [umijs/umi#8691]
## What happens?

![image](https://user-images.githubusercontent.com/29365288/180636454-379f552c-7f8a-4bcc-89f3-2ab289e27714.png)

## Context

- **Umi Version**: v4.0.7
- **Node Version**: v16.0.0
- **Platform**: mac

**Comment by skyunBoss** [comment]
yarn 1.22.19

**Comment by PeachScript** [comment]
@skyunBoss 大概率本地有多个 ESLint，提供下最小可复现仓库

**Comment by xiaohuoni** [comment]
超过三个月未提供复现，先关闭，有后续再 reopen
