### ISSUE TITLE
[Bug] defaultSettings.ts中设置primatyColor后主题颜色变成了“科技蓝”

### ISSUE THREAD

**Issue by whyont** [umijs/umi#8699]
## What happens?

直接通过pro create xxx命令创建的umi4 antd pro项目，然后设置默认背景颜色，没有变化
![image](https://user-images.githubusercontent.com/55822025/180731277-68c5c850-b63a-4601-8f42-94b356c223f9.png)
这个是基础配置
![image](https://user-images.githubusercontent.com/55822025/180731444-3e0c135b-c0f7-4dde-a7cc-54c6679d3e95.png)
这个是问题图

发现我设置的颜色为“明青”，色值从拂晓蓝变为了科技蓝，而且不管我的primaryColor设置为什么色值，全部都是科技蓝

配置为基础配置，直接通过pro create XX 创建的项目，然后直接改主题色发现这个问题

**Comment by calimanco** [comment]
我遇到类似的情况，但我是在 umi4 的项目里在 theme 配置里改颜色的。
后面发现把 @ant-design/pro-layout 依赖移除（@umijs/max 自带），或者换成最新的 7.x 版本就好了。

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
