### ISSUE TITLE
[Bug] 在antd pro里面的 umi 3.5 使用     "start:dev": "cross-env REACT_APP_ENV=dev UMI_ENV=dev umi dev", 一直报错 找不到 './data' module

### ISSUE THREAD

**Issue by leonyi168** [umijs/umi#8700]
## What happens?

[Bug] 在antd pro里面的 umi 3.5 使用     "start:dev": "cross-env REACT_APP_ENV=dev UMI_ENV=dev umi dev", 一直报错 找不到 './data' module
如果 是 "start:dev": "cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev umi dev", 就执行正常。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:  ^3.5.0
- **Node Version**: v16.15.0
- **Platform**: mac ,chrome

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
