### ISSUE TITLE
umi 4版本开启ssr后，程序无法正常运行

### ISSUE THREAD

**Issue by shanhuaji** [umijs/umi#8701]
![image](https://user-images.githubusercontent.com/63954007/180749618-21ee9ed4-be7f-4393-bca4-30fdc33d6cee.png)
![image](https://user-images.githubusercontent.com/63954007/180750878-b8dfe762-2db4-4b7f-89ba-a6b387752af9.png)

**Comment by shanhuaji** [comment]
@sorrycc

**Comment by sorrycc** [comment]
我还没试过 ssr + antd，建议试试不加载 antd 的 less，通过 link 的方式引入 antd 的 css 。

**Comment by shanhuaji** [comment]
> 我加载方式提示ssr + antd，建议尝试不要antd的，通过链接antd的cs。

是这样吗？
![image](https://user-images.githubusercontent.com/63954007/181677424-bf31baab-e7cc-4a12-800f-d4edd57666e9.png)
![image](https://user-images.githubusercontent.com/63954007/181677476-d2b10f38-d632-4e2b-a241-e7ea47828d8b.png)
还是报上边那个错误

**Comment by shanhuaji** [comment]
> 我还没试过 ssr + antd，建议试试不加载 antd 的 less，通过 link 的方式引入 antd 的 css 。
是这样吗？
![image](https://user-images.githubusercontent.com/63954007/181677966-a7b8411c-e9d9-4ff4-972a-e48541e05e20.png)
依然报错

**Comment by shengbenqiang** [comment]
> > 我还没试过 ssr + antd，建议试试不加载 antd 的 less，通过 link 的方式引入 antd 的 css 。
> > 是这样吗？
> > ![image](https://user-images.githubusercontent.com/63954007/181677966-a7b8411c-e9d9-4ff4-972a-e48541e05e20.png)
> > 依然报错

请问你解决了吗？我开启 ssr 后也是各种 less 报错

**Comment by shanhuaji** [comment]
没有，项目体积不大，还用next了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月09日 10:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [umijs/umi] umi 4版本开启ssr后，程序无法正常运行 (Issue #8701) |

我还没试过 ssr + antd，建议试试不加载 antd 的 less，通过 link 的方式引入 antd 的 css 。
是这样吗？

依然报错

请问你解决了吗？我开启 ssr 后也是各种 less 报错

**Comment by shengbenqiang** [comment]
> 没有，项目体积不大，还用next了
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年08月09日 10:22 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [umijs/umi] umi 4版本开启ssr后，程序无法正常运行 (Issue #8701) | 我还没试过 ssr + antd，建议试试不加载 antd 的 less，通过 link 的方式引入 antd 的 css 。 是这样吗？ 依然报错 请问你解决了吗？我开启 ssr 后也是各种 less 报错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

那问下你最终 ssr 没有去用 umi 的 ssr 而是用 next 吗？ umi 内还是嵌入 next 架子？还是直接用 next 重写？

**Comment by shengbenqiang** [comment]
我无法绕开 ssr 这个需求，但是这个配置问题我不知道该如何解决，已经完成了最关键部分的代码这个时候迁移去用 next.js 成本太高


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/umi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月9日(星期二) 上午10:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umijs/umi] umi 4版本开启ssr后，程序无法正常运行 (Issue #8701)





 没有，项目体积不大，还用next了
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 日期 | 2022年08月09日 10:22 |
 | 收件人 | ***@***.***&gt; |
 | 抄送至 | ***@***.******@***.***&gt; |
 | 主题 | Re: [umijs/umi] umi 4版本开启ssr后，程序无法正常运行 (Issue #8701) |
 
 我还没试过 ssr + antd，建议试试不加载 antd 的 less，通过 link 的方式引入 antd 的 css 。
 是这样吗？
 
 依然报错
 
 请问你解决了吗？我开启 ssr 后也是各种 less 报错

**Comment by shanhuaji** [comment]
重写



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月09日 10:29 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [umijs/umi] umi 4版本开启ssr后，程序无法正常运行 (Issue #8701) |

没有，项目体积不大，还用next了
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2022年08月09日 10:22 | | 收件人 | @.> | | 抄送至 | @.@.> | | 主题 | Re: [umijs/umi] umi 4版本开启ssr后，程序无法正常运行 (Issue #8701) | 我还没试过 ssr + antd，建议试试不加载 antd 的 less，通过 link 的方式引入 antd 的 css 。 是这样吗？ 依然报错 请问你解决了吗？我开启 ssr 后也是各种 less 报错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

那问下你最终 ssr 没有去用 umi 的 ssr 而是用 next 吗？ umi 内还是嵌入 next 架子？还是直接用 next 重写？
