### ISSUE TITLE
[Bug] umi@4.0.8 i18n

### ISSUE THREAD

**Issue by magickeyyy** [umijs/umi#8705]
windows10 
1. npm i pnpm -g
2. pnpm dlx create-umi@latest  
Simple APP
✔ Pick Npm Client › pnpm
✔ Pick Npm Registry › taobao
3. src/pages/locales创建ts(官网步骤)
4. 删除.umirc.ts(校验有问题，说locale字段是错误的字段)使用config  
``` ts
import { defineConfig } from 'umi';

export default defineConfig({
    npmClient: 'pnpm',
    locale: {
        default: 'en-US',
    },
    routes: [{ path: '/', component: '@pages/index' }],
    mfsu: false,
});
```  
5. pages/index.tsx,import {useIntl} from 'umi'
6. pnpm start
7. 报错：./src/pages/index.tsx:12:13-20
export 'useIntl' (imported as 'useIntl') was not found in 'umi' (possible exports: ApplyPluginsType, Link, NavLink, Navigate, Outlet, PluginManager, __useFetcher, createBrowserHistory, createHashHistory, createHistory, createMemoryHistory, createSearchParams, history, matchPath, matchRoutes, renderClient, resolvePath, terminal, useAppData, useClientLoaderData, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRouteData, useRoutes, useSearchParams, useServerLoaderData, withRouter) 

在这之前使用的yarn步骤，结果一样的。yarn、pnpm清除了缓存一样的。  
看来问题还很多

**Comment by PassionPI** [comment]
你用的是Simple umi, 这个应该是需要手动装插件.
你应该选择安装@umijs/max, 这个会自动装插件

**Comment by sorrycc** [comment]
1、选择 @umijs/max
2、选择 Simple App 的话，需要 1）pnpm i @umijs/plugins，2）配置里加上 plugins: ['@umijs/plugins/dist/locale']
