### ISSUE TITLE
umi4配置tailwindcss后再webstorm中没有智能提示

### ISSUE THREAD

**Issue by 775146061** [umijs/umi#8706]
## What happens?
tailwindcss没有智能提示，请问什么情况

## Context

- **Umi Version**: 4.*
- **Node Version**:  v16.16.0
- **Platform**: Mac
- **WebStorm**: WebStorm 2021.3 Build #WS-213.5744.224, built on November 27, 2021

**Comment by fz6m** [comment]
tailwind 的提示需要插件，找下？

FYI：

 - https://www.jetbrains.com/help/webstorm/tailwind-css.html
