### ISSUE TITLE
[Bug] Umi Max Jenkins 打包报错，本地没有问题

### ISSUE THREAD

**Issue by zeusyaoyao** [umijs/umi#8708]
## What happens?
在本地 max build 打包没有问题，部署时报错。

<img width="1161" alt="Screenshot 2022-07-26 at 1 09 38 PM" src="https://user-images.githubusercontent.com/109730486/180928051-62c64910-6447-457c-87c4-34ad5f16dd88.png">

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0.8
- **Node Version**: 12
- **Platform**:

**Comment by sorrycc** [comment]
node 版本不够，需要 14 或以上。
