### ISSUE TITLE
[Feature Request] verifyCommit: 文档中体现一下默认的 scope，有用户会问究竟可以写哪些 scope

### ISSUE THREAD

**Issue by hanzebang** [umijs/umi#8709]
## Background

模板添加 verifyCommit 后，有用户会问提交的时候究竟可以写哪些 scope。

## Proposal

配置说明中提示一下默认 scope：`feat,fix,docs,style,refactor,perf,test,workflow,build,ci,chore,types,wip,release,dep,example,Merge`

**Comment by fz6m** [comment]
另希望支持：

 - 单复数：`deps?` 、`examples?`

 - 大小写 merge 与 revert ：`revert` / `Revert` / `merge` /  `Merge` ( 如 git 工具会自动默认创建大写开头的提交 )

 - changesets 的发版 merge 格式：`Version` 开头的提交

FYI：

```ts
  const reg  = `/^(((feat|fix|docs|style|refactor|perf|test|workflow|build|ci|chore|types|wip|release|deps?|merge|examples?|revert)(\(.+\))?:)|(Merge|Revert|Version)) .{1,50}$/i`
```

**Comment by zzcan** [comment]
认领
