### ISSUE TITLE
使用resolutions后出现打包过慢，包体积增大的问题

### ISSUE THREAD

**Issue by BeautyInNorth** [umijs/umi#8712]
## What happens?
```
"resolutions": {
  "**/af-webpack/typescript": "3.7.2"
}
```
替换typescript版本后出现打包过慢，包体积增大的问题

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 2.9.0
- **Node Version**: 14.17.0
- **Platform**: w10

**Comment by sorrycc** [comment]
使用 resolutions 非正常使用场景，遇到问题请自行排查。

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
