### ISSUE TITLE
Umi Issue 检测机器人

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#8718]
## 问题

不少 issue 没有复现步骤，目前是手动看到后关闭并提示。这对于用户来说比较「滞后」，对于 Umi 维护者来说也是手动的重复劳动。

## 方案

1、新增 Github CI 机器人
2、在 issue 新增或主贴被编辑后触发
3、如果没有包含 github.com 或 stackblitz 链接，并且 issue 是 open 状态，关闭 issue 并回复「由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。」
4、如果包含 github.com 或 stackblitz 链接，并且 issue 是 close 状态，reopen issue

**Comment by xrkffgg** [comment]
> 4、如果包含 github.com 或 stackblitz 链接，并且 issue 是 close 状态，reopen issue

@sorrycc 需要删除原来的提示评论吗？

**Comment by sorrycc** [comment]
@xrkffgg 不用。
