### ISSUE TITLE
[Bug] umi4 给 react 18 配置 externals 后打包构建，会报错，白屏

### ISSUE THREAD

**Issue by twinkle77** [umijs/umi#8719]
## What happens?

umi4 给 react 18 配置 externals 打包构建后，会报错，白屏

![image](https://user-images.githubusercontent.com/17792166/181144801-99a08ab5-0fbe-49ec-b113-4c250641866e.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/twinkle77/umi4-external

## How To Reproduce

1.   生成项目
![image](https://user-images.githubusercontent.com/17792166/181144032-c20e849b-80fb-4a9d-963f-b91e82e6980e.png)
2. .umirc.ts 配置 externals 配置如下
```bash
  externals: {
    react: 'var window.React',
    'react-dom': 'var window.ReactDOM'
  },
  scripts: [
    'https://g.alicdn.com/code/lib/react/18.0.0/umd/react.production.min.js',
    'https://g.alicdn.com/code/lib/react-dom/18.0.0/umd/react-dom.production.min.js'
  ]
```
3. 执行  pnpm build
4. 通过静态资源服务渲染 dist 目录，发现页面白屏，报错如下
![image](https://user-images.githubusercontent.com/17792166/181144219-d1a14d2e-4add-447a-8ca8-badf83130d41.png)

## Context

- **Umi Version**:  @latest
- **Node Version**: 14.17.0
- **Platform**: mac

**Comment by twinkle77** [comment]
![image](https://user-images.githubusercontent.com/17792166/181145955-f58ddada-f59c-4341-adbf-4deb3a712e94.png)

**Comment by sorrycc** [comment]
react-dom 改成 react-dom/client，react 18 之后引的是这个路径。
