### ISSUE TITLE
umi dev时提示错误'@babel/runtime/helpers/interopRequireDefault module not found' 错误

### ISSUE THREAD

**Issue by Renderz** [umijs/umi#872]
### 依赖版本
now@11.3.10
serve@9.6.0
umi@2.0.0-beta.13
yarn@1.6.0
node@v10.9.0

### 系统
macOS high Sierra 10.13.6

### 如何复现
1. mkdir temp
2. umi g page test
3. umi dev

### 期待结果
dev服务能正常启动

### 实际结果
```
 WAIT  Compiling...                                                                                                                           09:09:05

✔ success webpack compiled in 104ms


 ERROR  Failed to compile with 3 errors                                                                                                       09:09:05

This dependency was not found:

* @babel/runtime/helpers/interopRequireDefault in ./pages/test.js, ./pages/.umi/umi.js and 1 other

To install it, you can run: npm install --save @babel/runtime/helpers/interopRequireDefault
```

### 附加
1. .config/yarn/global/node_modules内可以看到@babel/runtime依赖.
2. 在temp项目下安装@babel/runtime 依赖后项目可以成功启动

**Comment by AndyKong207** [comment]
操作步骤同issue主
使用umi dev

✖ Webpack
  Compiled with some errors in 2.47s

Starting the development server...

 ERROR  Failed to compile with 4 errors                                        3:20:38 PM

This dependency was not found:

* @babel/runtime/helpers/interopRequireDefault in ./pages/index.js, ./pages/users.js and2 others

To install it, you can run: npm install --save @babel/runtime/helpers/interopRequireDefault
 WAIT  Compiling...                                                            3:20:39 PM

umi -v
2.3.1
node -v
v11.6.0

**Comment by Renderz** [comment]
> 操作步骤同issue主
> 使用umi dev
> 
> ✖ Webpack
> Compiled with some errors in 2.47s
> 
> Starting the development server...
> 
> ERROR Failed to compile with 4 errors 3:20:38 PM
> 
> This dependency was not found:
> 
> * @babel/runtime/helpers/interopRequireDefault in ./pages/index.js, ./pages/users.js and2 others
> 
> To install it, you can run: npm install --save @babel/runtime/helpers/interopRequireDefault
> WAIT Compiling... 3:20:39 PM
> 
> umi -v
> 2.3.1
> node -v
> v11.6.0

方案1. 删除 yarn.lock 重装 node_modules 
方案2. 升级umi版本
