### ISSUE TITLE
[Bug] route菜单不显示

### ISSUE THREAD

**Issue by see** [umijs/umi#8721]
## What happens?

routes菜单不显示

![截屏2022-07-27 11 23 24](https://user-images.githubusercontent.com/19725091/181153859-e16cb303-f63c-4a9a-99ce-bc382d1d593c.png)

## Mini Showcase Repository(REQUIRED)

https://github.com/see/umijs-route-issue

## How To Reproduce

**Steps to reproduce the behavior:**
1. pnpm i
2. pnpm dev

**Expected behavior** 
左侧菜单正常显示

## Context

- **Umi Version**: 4.0.8
- **Node Version**: v14.19.0
- **Platform**: macos

**Comment by fz6m** [comment]
正确的路由：

```ts
  routes: [
    {
      path: '/',
      redirect: '/home',
    },
    {
      name: '首页',
      path: '/home',
      component: './Home',
    },
  }
```

**Comment by see** [comment]
但是v3正常

**Comment by sorrycc** [comment]
@stormslowly 有空定位下原因？

**Comment by xierenyuan** [comment]
> 但是v3正常，v4就不正常了

目前的v4 版本是不支持 这种的 菜单配置方式的. 如果路由不包含 name 是不会被显示 你目前的场景可以新建约定式布局文件 `layouts/index.tsx` 来解决
<img width="847" alt="image" src="https://user-images.githubusercontent.com/7599351/181694137-b630dbaf-2ed7-4835-b5f6-fdae9104299b.png">

**Comment by xierenyuan** [comment]
我先关闭了 有问题在打开吧

**Comment by see** [comment]
但是这样也有问题
1. 我可以排出某些路由不是用这个布局吗？
2. 布局可以嵌套吗？
