### ISSUE TITLE
[Bug]ssr.js使用es6的startsWith特性报错

### ISSUE THREAD

**Issue by zhxhdean** [umijs/umi#8722]
## What happens?

使用build模式打包代码。 源码在ssr.js文件中的311行，
` if (chunk && opts.chunks.find(c => c.name.startsWith(chunk))) {`

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context
启用build模式进行打包的时候，会有打包失败错误。
- **Umi Version**:3.3.7
- **Node Version**:16
- **Platform**:ios

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
