### ISSUE TITLE
[Bug] 路由component 为同一组件，只渲染一次

### ISSUE THREAD

**Issue by leshalv** [umijs/umi#8723]
<img width="399" alt="image" src="https://user-images.githubusercontent.com/30397655/181182036-de71a423-03ce-4538-bdec-7cda6abb0bbf.png">

**Comment by cc7gs** [comment]
1. 你检查下路由配置文件是否有 对 /list, 存在redirect操作；
` {
          path: '/list',
          redirect: 'xx'
        }` 
2. 如果还存在问题给个最小复现demo

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
