### ISSUE TITLE
[Bug] App.tsx 配置默认插件函数 getInitialState 报错

### ISSUE THREAD

**Issue by shiqkuangsan** [umijs/umi#8724]
## 截图

<img width="702" alt="image" src="https://user-images.githubusercontent.com/18481623/181182414-d584c7cb-d971-428a-9dc1-6e3d1e0ac098.png">

## 复现
使用 pnpm 按照 umi 官网创建默认项目然后运行

## 排查

.umi/plugins.ts 文件中

export function getValidKeys() {
  return ['patchRoutes','patchClientRoutes','modifyContextOpts','rootContainer','innerProvider','i18nProvider','accessProvider','dataflowProvider','outerProvider','render','onRouteChange',];
}

函数 getValidKeys() 没有 getInitialState 项目

## 疑问
initial state 插件不是默认开启的嘛？

- **Umi Version**: 4.0.7
- **Node Version**: 18.5.0
- **Platform**: macos

**Comment by fz6m** [comment]
使用 `@umijs/max` 或手动安装并启用 `initialState` 功能：

```bash
  pnpm add -D @umijs/plugins
```

```ts
// .umirc.ts

export default {
  plugins: ['@umijs/plugins/dist/initial-state'],
  initialState: {}
}
```

**Comment by shiqkuangsan** [comment]
ok  本来一直自带默认开启的，官网看到内置了该插件以为不用配置的，原来该配置和 model 需要同时自己开启了现在。

**Comment by shiqkuangsan** [comment]
@fz6m  抱歉打扰，问下咱现在还有 umi 技术交流群嘛？感觉这种小问题再来提 issue 怪不好意思的？

**Comment by fz6m** [comment]
[Umi 反馈和交流群](https://fb.umijs.org/)
