### ISSUE TITLE
[Bug] 子应用加载 css、js 时，没有使用 public path

### ISSUE THREAD

**Issue by PhilipDing** [umijs/umi#8733]
## What happens?

子应用加载 css、js 时，没有使用 public path，如下所示：

![image](https://user-images.githubusercontent.com/4457568/181216893-cd46872f-a57d-4fa1-8c1f-5e97dd0ee1c5.png)

config/config.ts  中已经加了 runtimePublicPath 插件：

![image](https://user-images.githubusercontent.com/4457568/181218291-8631a088-adc2-4b25-9c11-be84c7f1a18a.png)

子应用的 html 中也包含

![image](https://user-images.githubusercontent.com/4457568/181218494-fa8779a7-4695-4826-a671-da9af8a81079.png)

其他：

当不引入 runtimePublicPath 插件 ，并且将 html 中的 __INJECTED_PUBLIC_PATH_BY_QIANKUN__ 删除，就可以加载成功了。

![image](https://user-images.githubusercontent.com/4457568/181221346-656142d1-d149-4bdc-b063-86f3c7c4c215.png)

## Context

- **Umi Version**: 4.0.7
- **Node Version**: v16.15.1
- **Platform**: MacOS

**Comment by sorrycc** [comment]
1、INJECTED_PUBLIC_PATH_BY_QIANKUN 是 qiankun 注入的，会将 entry 作为默认的 publicPath
2、不需要的话不配置 runtimePublicPath 或者配置 runtimePublicPath:false 就好了，这样不会使用 window.publicPath

**Comment by coderew** [comment]
没有配置runtimePublicPath，打包后生成的html文件还有window.publicPath = window.INJECTED_PUBLIC_PATH_BY_QIANKUN，怎么去掉呢？

**Comment by JohnPorter** [comment]
> 没有配置runtimePublicPath，打包后生成的html文件还有window.publicPath = window.INJECTED_PUBLIC_PATH_BY_QIANKUN，怎么去掉呢？

老哥解决了，这个问题

**Comment by JohnPorter** [comment]
> 没有配置runtimePublicPath，打包后生成的html文件还有window.publicPath = window.INJECTED_PUBLIC_PATH_BY_QIANKUN，怎么去掉呢？

老哥解决了吗，这个问题

**Comment by bingyang519** [comment]
> > 没有配置runtimePublicPath，打包后生成的html文件还有window.publicPath = window.INJECTED_PUBLIC_PATH_BY_QIANKUN，怎么去掉呢？
> 
> 老哥解决了吗，这个问题

已解决
https://github.com/umijs/umi/issues/4352#issuecomment-2022620239
