### ISSUE TITLE
[Bug] umi4 配置targets:{ie:11}后，build后的代码中，依然含有 ?? , ?. 等es2020语法

### ISSUE THREAD

**Issue by Cherry-Peng** [umijs/umi#8744]
umi4 配置targets:{ie:11}后，build后的代码中，依然含有 ?? , ?. 等es2020语法，会导致不兼容
<img width="566" alt="image" src="https://user-images.githubusercontent.com/52364774/181401546-7d01ed1c-f9a3-4464-bc4a-fec0d07307e0.png">
<img width="452" alt="image" src="https://user-images.githubusercontent.com/52364774/181401627-224b0139-3654-4c97-97a9-6c34d7255d25.png">

**Comment by fz6m** [comment]
解决方案：

```ts
// .umirc.ts

export default {
  jsMinifier: 'terser'
}
```
