### ISSUE TITLE
当 node_modules 根目录和子目录共同存在 antd 的依赖时，本地服务依赖路径有问题

### ISSUE THREAD

**Issue by 1eeing** [umijs/umi#8747]
### Discussed in https://github.com/umijs/umi/discussions/8746

<div type='discussions-op-text'>

<sup>Originally posted by **1eeing** July 28, 2022</sup>
问题描述：
我的 umi 项目，node_modules 根目录下有一个 antd 4.0.0 版本，node_modules 下的子包 A 因为 dependencies 了 antd@4.18.0，因此在 node_modules/A/node_modules/ 存在一份 antd@4.18.0 。

我的疑问：
存在两份 antd 我觉得没问题，这是 npm 的一个规则。但是使用 umi 启动后，子包却是在根目录引用 antd@4.0.0，从而导致报错。

期望：
这个场景，应该从子包的 node_modules 中引用 antd@4.18.0 才对。（vscode 中提示的引用路径就是对的，但是实际启动后路径就是错的）

麻烦帮忙看看</div>

**Comment by 1eeing** [comment]
使用 CRA，webpack 版本 5.0.0 发现就没有这个问题。估计是内置的 webpack 的版本或者某些配置导致了这个引用问题

**Comment by sorrycc** [comment]
antd 用多个版本？这会导致奇怪问题的。Umi 中只能用一个版本，如果一定要用多个版本，可通过 chainWebpack 把 alias 里的 antd 删掉。

**Comment by 1eeing** [comment]
> antd 用多个版本？这会导致奇怪问题的。Umi 中只能用一个版本，如果一定要用多个版本，可通过 chainWebpack 把 alias 里的 antd 删掉。

感觉对于一个依赖 antd 的 UI 组件来说，external antd 并且将 antd 写入 dependencies 是个最优的选择了。对此您有什么更好的建议吗？

**Comment by sorrycc** [comment]
externals 会有尺寸问题，额外加载没有用到的 antd 组件。
