### ISSUE TITLE
[Bug] Umi 中使用babel-plugin-macros插件，umi build报错 Error: Duplicate plugin/preset detected.

### ISSUE THREAD

**Issue by Pcxy** [umijs/umi#8748]
## What happens?

umi两个环境dev, prod， 均添加extraBabelPlugins: ['babel-plugin-macros'], .umirc.ts文件 build正常， .umirc.prod.ts文件build报错：Error: Duplicate plugin/preset detected.

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/Pcxy/hello-umi-glsl

## How To Reproduce

1. npm run build 正常， npm run build:prod 报错

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

Module build failed (from ./node_modules/@umijs/deps/compiled/babel-loader/index.js):
Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

## Context

- **Umi Version**: 3.5
- **Node Version**: 16.13
- **Platform**:

**Comment by sorrycc** [comment]
可能加了两遍？如果 dev 和 prod 都需要，为啥要分开加？

**Comment by sorrycc** [comment]
加两遍的原因是，extraBabelPlugins 在有 UMI_ENV 添加额外配置时是对数组做 merge 的操作。
