### ISSUE TITLE
[Bug] @umijs/max v4.0.8 国际化API类型失效

### ISSUE THREAD

**Issue by PassionPI** [umijs/umi#8751]
## What happens?
国际化相关API的类型标注失效

![image](https://user-images.githubusercontent.com/50688829/181410092-b2a1d015-fdd5-496a-beca-6e3c90189e8e.png)

在`src/.umi/exports.ts`文件中, 增加这块, 类型就生效了

![image](https://user-images.githubusercontent.com/50688829/181411125-62676a10-d580-4123-8bde-498336677341.png)

复现流程

1. pnpm dlx create-umi@latest
2. 选择antd-pro
3. 增加国际化配置

## Context

- **Umi Version**: 4.0.8

**Comment by sorrycc** [comment]
这个需要修复下，插件下需要额外生成 types.d.ts 作为类型导出，才能通过 import from umi 的方式使用。 @YdreamW

**Comment by YdreamW** [comment]
该问题是因为reexport的时候用了文件名，这导致了 ts 类型的丢失。修改方法是将文件名改成模块名。并不是纯类型的导出，故不需要 .d.ts
https://github.com/umijs/umi/pull/8778
