### ISSUE TITLE
Invalid config keys: favicon

### ISSUE THREAD

**Issue by little-bears** [umijs/umi#8752]
.umirc.ts文件设置favicon配置项，编译失败
`export default {
  favicon: '/assets/favicon.ico',
};`

提示 Invalid config keys: favicon
`AssertionError [ERR_ASSERTION]: Invalid config keys: favicon
 at Function.validateConfig (D:\game\gameManage\node_modules\@umijs\core\dist\config\config.js:179:31).....`

哪位大佬帮我看看 umi4 网站 favicon.ico 该怎么设置呢？ 万分感谢！

**Comment by xierenyuan** [comment]
api 变更了  可以看这个  https://umijs.org/docs/api/config#favicons

**Comment by Echo-minn** [comment]
> 
fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: antd, favicon
遇到了同样的问题，还有一个说antd配置不对，在新的api文档没找到对应的配置说明
favicon的配置从
`favicon: "https_url",` 改成了` favicon: ["https_url"]`
重新npm start之后还是报了同样的错，下面是今天才更新的依赖版本信息：
`"dependencies": {
    "antd": "^4.22.1",
    "umi": "^4.0.8",
    "umi-request": "^1.4.0"
  },`
