### ISSUE TITLE
umi在启动的时候，执行getInitialState的时候白屏

### ISSUE THREAD

**Issue by forget-forever** [umijs/umi#8755]
## What happens?

umi应用在启动的时候会调用getInitialState，这个方法会阻止页面的其他代码运行，然后这个时候就会有一个页面的白屏。

## How To Reproduce

在app.ts中如果getInitialState里面运行的接口延时非常长的时候会有一个较长时间的白屏
```typescript
/**
* 获取项目初始值的函数
*/
export function getInitialState() {

  /** 用来模拟一个很高延时的请求 */
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({name: 'aa', age: '100'})
    }, 30000)
  })
}
```

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by ihavecoke** [comment]
添加个 loading 过渡动画？

**Comment by sorrycc** [comment]
目前是这样的，umi 3 也一样。有需求可直接提 PR 或者给方案。

**Comment by drizzlesconsin** [comment]
@sorrycc umi3 在运行时配置里，是有个 `initialStateConfig` 可以用。
```tsx
export const initialStateConfig = {
  loading: <Spin />,
};
```

**Comment by drizzlesconsin** [comment]
Umi4 可以这样
```ts
// config/config.ts
initialState: {
  loading: '@ant-design/pro-layout/es/PageLoading',
},
```

**Comment by a992681784** [comment]
> Umi4 可以这样
> 
> ```ts
> // config/config.ts
> initialState: {
>   loading: '@ant-design/pro-layout/es/PageLoading',
> },
> ```

试了下这样配置报错了 显示webpack解析路径报错？是还要配置什么吗？

**Comment by jimwong666** [comment]
> ```ts
> loading
> ```

很赞👍谢谢

**Comment by jimwong666** [comment]
> Umi4 可以这样
> 
> ```ts
> // config/config.ts
> initialState: {
>   loading: '@ant-design/pro-layout/es/PageLoading',
> },
> ```

很赞👍谢谢

**Comment by a1159717508** [comment]
> 

请问解决了吗

**Comment by oubinke** [comment]
> > Umi4 可以这样
> > ```ts
> > // config/config.ts
> > initialState: {
> >   loading: '@ant-design/pro-layout/es/PageLoading',
> > },
> > ```
> 
> 试了下这样配置报错了 显示webpack解析路径报错？是还要配置什么吗？

把 .umi 删了再重新启动一下项目试试
