### ISSUE TITLE
[Feature Request] 有些只能使用 formatMessage 的情况会遇到错误提示，体验可以优化一下

### ISSUE THREAD

**Issue by hanzebang** [umijs/umi#8756]
## Background

有些情况比如说运行时 function（request 拦截器，layout 运行时等）或者一些运行时调用的 util 方法等，使用 formatMessage 是河里的，这种红色提醒可能过于绝对了，用户反馈感受不好
![image](https://user-images.githubusercontent.com/46307343/181449099-7ffa8ac5-3ffc-4392-97ab-9ad719ce7403.png)

## Proposal

可以降级为黄色 warning，或者完善一下说明，或者区分是否在组件内使用（这个可能比较麻烦）

**Comment by YdreamW** [comment]
https://github.com/umijs/umi/pull/8759
