### ISSUE TITLE
umi 3 启用  mfsu 报下面警告

### ISSUE THREAD

**Issue by kaoding** [umijs/umi#8764]
warning (@babel/preset-env): the `corejs` option only has an effect when the `usebuiltins` option is not `false`

**Comment by sorrycc** [comment]
警告先忽略吧，另外建议升级到 umi 4 再用 mfsu 。

**Comment by IsDyh01** [comment]
我的umi版本是3.5.15，会在临时文件.umi中的umi.ts中使用require加载模块，然后当开启mfsu时会有警告替换require，其它无报错，但是为什么打开项目的时候一直是空白页
