### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by manooog** [umijs/umi#8770]
## What happens?

安装 @umijs/utils 会失败：

yarn global add @umijs/utils@3.5.31
<img width="678" alt="image" src="https://user-images.githubusercontent.com/19320239/181672963-717e0efd-06b6-4067-82d1-e11279cb8edd.png">

但是 npm 查看 @umijs/utils 的版本是有 3.5.31的？https://www.npmjs.com/package/@umijs/utils

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by sorrycc** [comment]
用了 npm 镜像吧，请检查镜像的 npm 包同步情况。

**Comment by manooog** [comment]
确实是镜像同步的问题，感谢。
