### ISSUE TITLE
 umi3 开启ssr后，root节点中没有内容，查看网页源代码非ssr形式

### ISSUE THREAD

**Issue by shanhuaji** [umijs/umi#8772]
复现：只需要新建一个umi3项目，config文件中配置ssr:{}，就可以了
![image](https://user-images.githubusercontent.com/63954007/181675089-aca0a7ab-c297-4bd2-ab62-0456741fe280.png)
![image](https://user-images.githubusercontent.com/63954007/181675111-423d4ca8-dab9-4b43-aa8d-25ee91fbaa50.png)

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

另外建议升级到 umi 4 之后再使用 ssr。
