### ISSUE TITLE
qiankun 主项目和子项目之间的切换，会抛出路径不匹配警告

### ISSUE THREAD

**Issue by ybrelax** [umijs/umi#8784]
qiankun 主项目和子项目之间的切换，会抛出路径不匹配警告

测试代码仓库
项目测试代码为官方的例子：
https://github.com/umijs/umi/tree/master/examples/ 的 max 和 qiankun-slave，前者是主应用，后者是子应用。

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/31029938/181734254-089b4ac1-c848-4947-a669-0ec8216e0f32.png">

## Context

 "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@umijs/max": "^4.0.9",
    "react": "18.1.0",
    "react-dom": "18.1.0"
  },
  "devDependencies": {
    "cypress": "^10.3.1",
    "start-server-and-test": "^1.14.0",
    "tailwindcss": "^3.1.6"
  }

**Comment by bazingaedward** [comment]
测试正常：
![image](https://user-images.githubusercontent.com/6486768/182159802-d80b6d0e-b89e-43ab-9c8b-55ca0f1e8767.png)

可以尝试：
1. git pull最新分支
2. qiankun-slave修改base，默认会读取package.json的name
`qiankun-slave/.umirc`
![image](https://user-images.githubusercontent.com/6486768/182160371-96b4e821-63e5-447a-bfb0-cb9d3a0575b6.png)

**Comment by ybrelax** [comment]
> 测试正常： ![image](https://user-images.githubusercontent.com/6486768/182159802-d80b6d0e-b89e-43ab-9c8b-55ca0f1e8767.png)
> 
> 可以尝试：
> 
> 1. git pull最新分支
> 2. qiankun-slave修改base，默认会读取package.json的name
>    `qiankun-slave/.umirc`
>    ![image](https://user-images.githubusercontent.com/6486768/182160371-96b4e821-63e5-447a-bfb0-cb9d3a0575b6.png)

还是会有，我拉了最新的测试了，还是会出现
自应用的配置我也改了
![Uploading image.png…]()
多切换几次就出现

版本：
    "@umijs/max": "4.0.11",

**Comment by jk4235** [comment]
通常来说子应用增加`base: ‘/’`就好了

https://github.com/umijs/umi/issues/8838#issuecomment-1207594907

你可以参考上面这个链接里的配置,我之前试了没什么问题
