### ISSUE TITLE
[Bug] wrappers 不兼容 * 号路由  页面无法渲染

### ISSUE THREAD

**Issue by lc-999** [umijs/umi#8787]
1 复现步骤
路由
{ path: '/files/*', component: 'user',
      wrappers: [
        '@/wrappers/auth',
      ],
},

页面无法渲染
![image](https://user-images.githubusercontent.com/110093535/181738627-8b9733e4-5f71-4a67-82d3-454589193561.png)

**Comment by lc-999** [comment]
未修复

**Comment by fz6m** [comment]
给复现看一下。

这是我测试的 demo：https://github.com/MoeYc/umi4-star-wrappers.git
