### ISSUE TITLE
[Bug] layout menuItemRender的参数menuItemProps没有默认选中某一个菜单项

### ISSUE THREAD

**Issue by Echo-minn** [umijs/umi#8794]
## What happens?
我重写了app.tsx的layout配置的menuItemRender方法，目的是根据item是否选中显示不同的icon，判断方法是menuItemProps.replace属性是否为true，本地环境测试通过，部署后失效，打印 `{console.log(menuItemProps.name, menuItemProps.replace, menuItemProps)}`，结果如下，所有menuItem的replace都是false
![image](https://user-images.githubusercontent.com/32877946/182007722-1fbcab29-1df7-435c-bd1e-e12bb7a6c6d9.png)

当我手动点击切换菜单后，被选中菜单项replace的值就为true了，但如果这时候刷新页面所有菜单项的replace值又都是false了

因为不清楚layout这块底层是如何实现的，也不清楚menuItemProps是如何在进入页面时判断哪个被选中病修改replace属性的，想知道该怎么debug

## Context

- **Umi Version**: 3.5.20
- **Node Version**: v16.15.1
- **Platform**: ubuntu

**Comment by Echo-minn** [comment]
我听过判断`window.location.pathname`和`menuItemProps.path`是否一致解决了这个问题
但我依然很好奇上面这个问题产生的原因

**Comment by sorrycc** [comment]
先关了。这不是 plugin-layout 里的实现，是 layout 组件里的。估计要到 ant-design-pro 的 issue 里提才能找到答案。
