### ISSUE TITLE
[Bug] plugin-locale export 出的api 比 react-intl 原生的api 缺失很多

### ISSUE THREAD

**Issue by kokiy** [umijs/umi#8809]
## What happens?
react-intl 提供了很多api ,但是 plugin-locale 只export 部分,
```js
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales } from './localeExports.ts';```

 比如 FormattedNumber 就没有export 出来
```js
export {
  FormattedDate,
  FormattedDateParts,
  FormattedDisplayName,
  FormattedHTMLMessage,
  FormattedList,
  FormattedMessage,
  FormattedNumber,
  FormattedNumberParts,
  FormattedPlural,
  FormattedRelativeTime,
  FormattedTime,
  FormattedTimeParts,
  IntlContext,
  IntlProvider,
  RawIntlProvider,
  createIntlCache,
  defineMessages,
  injectIntl,
  useIntl,
} from 'umi-max/node_modules/react-intl';
```

<img width="895" alt="image" src="https://user-images.githubusercontent.com/15773714/182128726-d39398f2-56c0-49d4-a4ad-8e7c3e193759.png">

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
https://github.com/kokiy/umi4

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:4.0.9
- **Node Version**: 14.16.0
- **Platform**:windows

**Comment by kokiy** [comment]
@fz6m  pr 已提https://github.com/umijs/umi/pull/8820

**Comment by sorrycc** [comment]
Resolved via https://github.com/umijs/umi/pull/8822 .
