### ISSUE TITLE
[bug] Can't resolve './antd/dist/antd.less'

### ISSUE THREAD

**Issue by zzy1661** [umijs/umi#8810]
umi3 引入'@ant-design/compatible/assets/index.less'报错

报错截图
![d246f3fb119704feb3f2b9c368310c4](https://user-images.githubusercontent.com/24517456/182132003-53ae6024-797e-41d2-852e-8613b99a2f87.png)

复现链接
[https://github.com/zzy1661/umi3-bugs.git](https://github.com/zzy1661/umi3-bugs.git)

复现步骤
```
yarn
yarn start
```

**Comment by sorrycc** [comment]
需要安装 @ant-design/compatible 的 peerDependencies 依赖 antd。
