### ISSUE TITLE
[Bug] 子应用使用 useModel 无法获取到 qiankunStateFromMaster 命名空间参数

### ISSUE THREAD

**Issue by guoqqqi** [umijs/umi#8814]
## What happens?
我使用 `pnpm-workspace.yaml` 在同一个仓库下管理主应用和子应用，

1. 添加 pnpm-workspace.yaml 文件：

```
packages:
  - 'packages/*'
  - 'micro-app/*'
```

3. 根据官方文档，在主应用中 app.ts 文件中导出 useQiankunStateForSlave 函数：

```
export function useQiankunStateForSlave() {
  const [globalState, setGlobalState] = useState<any>({
    slogan: 'Hello MicroFrontend',
  });

  return {
    globalState,
    setGlobalState,
  };
}
```

4. 子应用中使用 useMode 获取 qiankunStateFromMaster 命名空间参数失败
5. 
```
  const masterProps = useModel('@@qiankunStateFromMaster');
```

![image](https://user-images.githubusercontent.com/72343596/182288037-0738c8dd-bfe6-4009-8b89-bc101748c703.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/guoqqqi/Umi-Max

## Context

- **Umi Version**: 4.0.8
- **Node Version**: 14.18.0
- **Platform**: Mac Apple M1

**Comment by guoqqqi** [comment]
猜测可能是因为在子应用中引入 `umijs/max` 姿势不对，可能是由于 pnpm 安装依赖将相同依赖链接到一起导致的 🤔；
查看 useModel 的引用时，发现会直接进入到主应用的 .umi/plugin-model 文件中，没有找到如何正确导入子应用的 plugin-model 依赖方法

**Comment by fz6m** [comment]
子应用根目录没有 `tsconfig.json` 无法进行 ts type 索引，创建如下文件解决：

```ts
// micro-app/app1/tsconfig.json
{
  "extends": "./.umi/tsconfig.json"
}
```

注：monorepo 目录结构不规范，正确的多项目目录结构是：

```bash
- apps
  - master-app
  - micro-app
- pnpm-workspace.yaml
```

**Comment by guoqqqi** [comment]
添加完 `tsconfig.json` 后解决
