### ISSUE TITLE
[Bug] vite 模式和 react 新的转换不兼容

### ISSUE THREAD

**Issue by urielvan** [umijs/umi#8819]
## What happens?

配置中启用 vite 模式后，无法正常使用 react 新的转换模式。
控制台中报错 The requested module '/node_modules/react/jsx-runtime.js' does not provide an export named 'jsx'

## Mini Showcase Repository(REQUIRED)

[repo](https://github.com/urielvan/umi-vite-jsx)

## How To Reproduce

**Steps to reproduce the behavior:**
执行 npm start 之后在浏览器中打开，无法正常显示页面

**Expected behavior**
和使用 webpack 时一样可以正常打开页面

## Context

- **Umi Version**: 4.0.9
- **Node Version**: 16.16.0
- **Platform**: win10

**Comment by zhanghaoxu** [comment]
same issue

**Comment by fz6m** [comment]
在最新版本（umi `4.0.41`）已经可用。
