### ISSUE TITLE
[Bug] 使用 qiankun 报 iframe 异常

### ISSUE THREAD

**Issue by sy296565890** [umijs/umi#8838]
## What happens?
 umimax使用qiankun报iframe异常【主应用和子应用均是由umimax +antd pro创建的项目】
[项目创建步骤参考地址](https://umijs.org/docs/max/introduce)
## 错误报告
<img width="1920" alt="lQLPJxaOLSfYjzTNBoDNDwCw6mN3NbN0ISoC6gISqwAnAA_3840_1664" src="https://user-images.githubusercontent.com/85245446/182515877-de296d53-500e-4c7c-a7f6-dadcdccc13f3.png">

> Gitee [最小重现地址](https://gitee.com/cy296565890/umimax-qiankun)

**Comment by jk4235** [comment]
根据我以前遇到的情况分析,可能是代码报错被react-error-overlay捕获,react-error-overlay会展示一个iframe,上面会显示具体错误,但是由于某些原因,这个iframe经常出问题,你可以在node_modules/@umijs/bundler-webpack/bundled/js/webpackHotDevClient.js 找到这个报错,这是被打包过的代码,你也可以自行寻找源码查看
你可以参考这个issue试试 https://github.com/umijs/qiankun/issues/1804

**Comment by sy296565890** [comment]
> 根据我以前遇到的情况分析,可能是代码报错被react-error-overlay捕获,react-error-overlay会展示一个iframe,上面会显示具体错误,但是由于某些原因,这个iframe经常出问题,你可以在node_modules/@umijs/bundler-webpack/bundled/js/webpackHotDevClient.js 找到这个报错,这是被打包过的代码,你也可以自行寻找源码查看 你可以参考这个issue试试 [umijs/qiankun#1804](https://github.com/umijs/qiankun/issues/1804)

非常感谢大佬的解答，但我依然没能解决这个问题，希望大佬能帮忙再看看能不能处理一下，谢谢大佬！

**Comment by jk4235** [comment]
子应用
<img width="739" alt="image" src="https://user-images.githubusercontent.com/18319040/183328753-430efb45-5a47-4248-b17c-2cdfc89a1f6d.png">
子应用关掉mfsu,否则会有点问题

主应用
<img width="605" alt="image" src="https://user-images.githubusercontent.com/18319040/183328845-3c9bf71d-671e-4a01-bfb6-0d7ec1d1c0e1.png">

最后效果

<img width="1751" alt="image" src="https://user-images.githubusercontent.com/18319040/183328932-1d74a744-1cba-439b-ab01-e838fbc5728f.png">

**Comment by sy296565890** [comment]
> 子应用 <img alt="image" width="739" src="https://user-images.githubusercontent.com/18319040/183328753-430efb45-5a47-4248-b17c-2cdfc89a1f6d.png"> 子应用关掉mfsu,否则会有点问题
> 
> 主应用 <img alt="image" width="605" src="https://user-images.githubusercontent.com/18319040/183328845-3c9bf71d-671e-4a01-bfb6-0d7ec1d1c0e1.png">
> 
> 最后效果
> 
> <img alt="image" width="1751" src="https://user-images.githubusercontent.com/18319040/183328932-1d74a744-1cba-439b-ab01-e838fbc5728f.png">

感谢大佬！
