### ISSUE TITLE
[Bug] less 文件 commit 后，丢失了全部的兼容样式

### ISSUE THREAD

**Issue by 17671881483** [umijs/umi#8839]
## What happens?

![image](https://user-images.githubusercontent.com/61647474/182517387-f60120ad-d670-4d0b-b2d2-01bdd9545fcf.png)
ccommit后
![image](https://user-images.githubusercontent.com/61647474/182517568-d674d9c9-0b7d-460a-bf8c-b0cc1ea9539f.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
postcss 自带 autoprefixer ，跟随 targets 适配，不需要手写供应商前缀。
