### ISSUE TITLE
[Bug] umi3 在 macOS 上的 dev server 无法处理大并发

### ISSUE THREAD

**Issue by xiaody** [umijs/umi#8860]
## What happens?

`umi dev` 启动的 server 响应静态资源请求时会随机出现链接断开。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/xiaody/umi-dev-server-backlog

这个仓库没什么特别的，是刚刚按 https://v3.umijs.org/docs/getting-started 的步骤创建的。除了 readme 没有改其他东西。

## How To Reproduce

**Steps to reproduce the behavior:** 
1. `npm start` 
2. 使用 Apache HTTP server benchmarking tool 压测，这里触发问题的具体并发数可能和机器性能、配置有关 `ab -n 20 -c 20 http://127.0.0.1:8000/umi.js`
3. 压测意外失败，日志如下
```
➜  umi-dev-server-backlog git:(main) ab -n 20 -c 20 http://127.0.0.1:8000/umi.js
This is ApacheBench, Version 2.3 <$Revision: 1879490 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)...apr_socket_recv: Connection reset by peer (54)
```

**Expected behavior**
压测应该通过。

## Context

- **Umi Version**: 3.5.32
- **Node Version**: 16.14.2
- **Platform**: macOS 12.4

**Comment by sorrycc** [comment]
Resolved via https://github.com/umijs/umi/pull/8861.
