### ISSUE TITLE
[Bug] umi项目重新安装依赖后启动报错

### ISSUE THREAD

**Issue by Z3FisherX** [umijs/umi#8864]
## What happens?

安装依赖后，start报错

<img width="989" alt="image" src="https://user-images.githubusercontent.com/39040945/182796953-903ff314-7ada-429f-8a4b-2f681fdc3610.png">
问题指向 node_modules/@babel/helper-wrap-function/lib/index.js  报错node参数为undefined 

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/Z3FisherX/report-error

## How To Reproduce

1. yarn install 更新依赖
2. yarn start 报错

## Context

- **Umi Version**: v3.5.32
- **Node Version**: v16.14.0
- **Platform**: Mac OS 12.4

**Comment by YdreamW** [comment]
```
    extraBabelPresets: ['@babel/env', '@babel/react'],
    extraBabelPlugins: [
        ['@babel/plugin-proposal-decorators', { legacy: true }],
        ['babel-plugin-import', { libraryName: 'antd', style: true }, 'antd']
    ],
```
配置中这些额外的 Babel 插件集和插件 umi 都是有提供的。去掉以后就可以了。
```
    extraBabelPlugins: [
        ['babel-plugin-import', { libraryName: 'antd', style: true }, 'antd']
    ],
```

至于该报错的原因，猜测大概率是由于用户自己的 babel 依赖和 umi 预编译的 babel 产生的多实例问题。排查比较困难，有空的时候我再看看具体是哪个包产生的。

**Comment by Z3FisherX** [comment]
> 

也有几个其他项目，没有配置额外的babel插件，也会出现类似的错误。但是使用之前的lock文件安装则暂时不会，可能是babel部分插件的版本更新问题？

**Comment by YdreamW** [comment]
umi 的 babel 都是预编译好的，应该不需要额外依赖。如果你没有特别的需求添加的话，依赖里最好不要加 babel。
你其他的项目如果没有配置额外的 babel 插件的话，把 pacakge.json 里的 babel 相关的依赖去掉试试。

**Comment by Z3FisherX** [comment]
> 

好的，谢谢
