### ISSUE TITLE
[Bug] 升级4.0.10后直接打不开项目了

### ISSUE THREAD

**Issue by see** [umijs/umi#8865]
## What happens?

![截屏2022-08-04 16 49 50](https://user-images.githubusercontent.com/19725091/182805332-88340ee3-10bb-4f1d-b387-343331939165.png)

## Mini Showcase Repository(REQUIRED)

https://github.com/see/umijs-outlet-issue

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0.10
- **Node Version**: v14.19.0
- **Platform**: macOS

**Comment by kokiy** [comment]
+1

**Comment by kokiy** [comment]
msfu 先close

**Comment by teamco** [comment]
+1

**Comment by artisanship** [comment]
果然不是只有我一个这样

**Comment by sorrycc** [comment]
Resolved via https://github.com/umijs/umi/pull/8872 .

**Comment by tangbzai** [comment]
更新之后运行dev 再在局域网的别的电脑上使用ip访问也是会报错

**Comment by fz6m** [comment]
局域网访问需要指定 `HOST=0.0.0.0`
