### ISSUE TITLE
Duplicate namespace in models: @@initialState, global, global

### ISSUE THREAD

**Issue by xmjike** [umijs/umi#8878]
PS E:\umi-ant> npm run dev
> dev
> max dev

info  - Umi v4.0.11
fatal - Error: Duplicate namespace in models: @@initialState, global, global
    at ModelUtils.getAllModels (E:\umi-ant\node_modules\@umijs\plugins\dist\utils\modelUtils.js:120:13)
    at getAllModels (E:\umi-ant\node_modules\@umijs\plugins\dist\model.js:96:6)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Hook.fn (E:\umi-ant\node_modules\@umijs\plugins\dist\model.js:46:20)
    at async E:\umi-ant\node_modules\@umijs\core\dist\service\service.js:152:13
fatal - A complete log of this run can be found in:
fatal - E:\umi-ant\node_modules\.cache\logger\umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues

## Context
刚刚初始化的项目.
npx create-umi@latest
-> ant design pro
启动后就报该问题.

- **Umi Version**:4.0.11
- **Node Version**:16.14.2
- **Platform**:win10

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。

**Comment by lianbuzi** [comment]
umi3 升级umi4时也提示这个错误，求解答

**Comment by fz6m** [comment]
如果有 model 的名字（可能是按约定生成的，详见 [model 命名空间](https://umijs.org/docs/max/data-flow#%E5%88%9B%E5%BB%BA-model) ）重复了，自行排查下 model 和报错提示即可。
