### ISSUE TITLE
[Bug] fatal - Error: Cannot find module 'click-to-react-component'

### ISSUE THREAD

**Issue by oxygen-xx** [umijs/umi#8879]
今天升级"@umijs/max": "^4.0.11",，又出现经常出现的问题。
fatal - Error: Cannot find module 'click-to-react-component'
/node_modules/umi/node_modules/@umijs/preset-umi/dist/features/clickToComponent/clickToComponent.js

解决方法就是把node_modules中的umi, @umijs这二个目录全删除了。重新yarn install。
这个问题是经常发生，一升级umi就可能发生。

- **Umi Version**: @umijs/max": "^4.0.11"
- **Node Version**: v16.15.1
- **Platform**: Macos 12.5

**Comment by fz6m** [comment]
尝试删除 `src/.umi` ？
