### ISSUE TITLE
[Bug] umi4 4.0.10 mock 修改内容或加文件，window不重启无效，mac正常

### ISSUE THREAD

**Issue by liangskyli** [umijs/umi#8882]
## What happens?

umi4 mock 修改内容或加文件，windows不重启无效，mac正常

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
windows10 复现仓库：https://github.com/liangskyli/umi4-bug

## How To Reproduce

#8803 的bug还是存在

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: "@umijs/max": "^4.0.10",
- **Node Version**:14.17.0
- **Platform**:window 10

**Comment by PengQingYao** [comment]
是因为缓存未删掉。从require.cache 删除缓存时， 在windows下， 使用的路径是\\， 而reqire.cache 缓存使用的路径是\，和mac一致, 导致require.cache的缓存删除不掉。 所以修改文件无效。 
相关代码在这里:https://github.com/umijs/umi/blob/2f926a1490ba6182c270078dd14d12c7451168dc/packages/preset-umi/src/features/mock/getMockData.ts#L41  
mockFile的路径是windows的路径了。

**Comment by PengQingYao** [comment]
是因为缓存未删掉。从require.cache 删除缓存时， 在windows下， 使用的路径是\\\， 而reqire.cache 缓存使用的路径是\，和mac一致, 导致require.cache的缓存删除不掉。 所以修改文件无效。
相关代码在这里:

[umi/packages/preset-umi/src/features/mock/getMockData.ts](https://github.com/umijs/umi/blob/2f926a1490ba6182c270078dd14d12c7451168dc/packages/preset-umi/src/features/mock/getMockData.ts#L41)

Line 41 in [2f926a1](https://github.com/umijs/umi/commit/2f926a1490ba6182c270078dd14d12c7451168dc)

 delete require.cache[mockFile]; 

mockFile的路径是windows的路径了。

**Comment by liangskyli** [comment]
v4.0.13版本修复了
