### ISSUE TITLE
[Feature Request] chainWebpack use 插件调用时机问题

### ISSUE THREAD

**Issue by drizzlesconsin** [umijs/umi#8894]
## Background

Umi3 在 `chainWebpack ` 添加 webpack 插件 [(filemanager-webpack-plugin@last)](https://github.com/gregnb/filemanager-webpack-plugin), 是能 build index.html 之后运行的。

现在 Umi4 好像不支持这个，**Webpack 插件总是在 输出 index.html 之前调用**。

目前除了写 Umi 插件，还有别的办法吗？各位支支招。

https://github.com/umijs/umi/blob/1a371c38fe7137b7469c1fcb4e85142ff063ca3b/packages/preset-umi/src/commands/build.ts#L100-L151

## Proposal

```ts
chainWebpack(memo) {
  memo.plugin("FileManagerPlugin").use(
    new FileManagerPlugin({
      events: {
        onEnd: { copy: [], move: [], },
      },
    })
  );
}
```

## Additional context

https://github.com/umijs/umi/blob/1a371c38fe7137b7469c1fcb4e85142ff063ca3b/packages/preset-umi/src/commands/build.ts#L154-L157

https://github.com/gregnb/filemanager-webpack-plugin/blob/master/src/index.js#L135

**Comment by fz6m** [comment]
你要移动文件？写项目级插件吧：

```ts
// ${root}/plugin.ts

export default (api) => {
  api.onBuildHtmlComplete(() => {
    // ...
  })
}
```

**Comment by drizzlesconsin** [comment]
`${root}/plugin.ts` 如果是放在这个位置，Umi 加载的顺序也迷了。

> 场景: 移动完再上传部署.

1. `${root}/plugin.ts` 处理 `index.html`
2. `config/config.ts` 里的 chainWebpack 上传部署.

调用顺序会变成 `2.` ---> `1.`

----

**想要达到期望顺序 `1` ---> `2`**，只能手动引入插件 ` plugins: ['./plugin.ts']`

但是吧，看了这个代码
https://github.com/umijs/umi/blob/master/packages/bundler-webpack/src/config/config.ts#L291-L318

按说应该也会是 `chainWebpack` -> `modifyWebpackConfig`, 这样确能达到想要的。。。看懵了

https://github.com/umijs/umi/blob/1a371c38fe7137b7469c1fcb4e85142ff063ca3b/packages/preset-umi/src/commands/build.ts#L72-L86

https://github.com/umijs/umi/blob/1a371c38fe7137b7469c1fcb4e85142ff063ca3b/packages/preset-umi/src/commands/build.ts#L102

**Comment by fz6m** [comment]
1. 定制 `index.html` 写插件就可以解决。

2. 需要在 `chainWebpack` 的某些环节前拷贝文件，你可以使用 https://umijs.org/docs/api/config#copy

**Comment by drizzlesconsin** [comment]
copy 多数情况是将别的资源复制 dist 目录。

在这种场景实现不了，比如打包完成需要复制 `dist/xx/index.html` --> `dist/index.html`. https://github.com/umijs/umi/issues/3186#issuecomment-530333837

Umi 4 `copy` 这些配置都是在 `onBuildHtmlComplete` 之前做的。

**Comment by fz6m** [comment]
给一个最小复现看看场景。

**Comment by drizzlesconsin** [comment]
@fz6m 已更新 [umi4-issue-mini-example](https://github.com/drizzlesconsin/umi4-issue-mini-example/commit/aaf2db1bf870eccd0bfbc50c5a94872d47f75d1b)

```bash
yarn build
```

**Comment by fz6m** [comment]
umi4 webpack build 完成后拿到结果才能写 `index.html` ，写 `index.html` 的时候 webpack 流程已经结束了，写插件解决移动文件问题吧：

```ts
// ${root}/plugin.ts

import { IApi } from "@umijs/max";
import path from 'path'
import fs from 'fs'

export default (api: IApi) => {
    api.onBuildHtmlComplete(() => {
        fs.copyFileSync(
            path.join(__dirname, './dist/xxxx/index.html'),
            path.join(__dirname, './dist/index.html')
        )
    })
}
```

**Comment by drizzlesconsin** [comment]
ok! 看来也只能这样了。
