### ISSUE TITLE
[Bug] umi3不支持 useModel的使用方式了么？

### ISSUE THREAD

**Issue by iHaroro** [umijs/umi#8902]
## What happens?
在升级umi3中不支持使用 useModel的方式使用数据流了么？
![image](https://user-images.githubusercontent.com/22785090/183325901-71fd30a2-d791-40cc-98de-505af687ee43.png)

在使用useModel时报错：`TS2345: Argument of type '"userModel"' is not assignable to parameter of type '"@@initialState"'.`
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

预定式model，并使用对应命名空间进行获取，ts报错。
## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 3.5.26
- **Node Version**: v16.15.1
- **Platform**: OSX 11.6

**Comment by topwood** [comment]
+1
