### ISSUE TITLE
jenkins 执行 max setup 命令报错

### ISSUE THREAD

**Issue by twinkle77** [umijs/umi#8903]
## What happens?

本地打包正常，但到 jenkins 执行 max setup 命令报错，报错结果如下:

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/17792166/183335557-cfc66a34-d785-4eeb-b8c8-22bbbfd5b9e2.png">

## Context

- **Umi Version**: "@umijs/max": "^4.0.6"
- **Node Version**:  node:14.17.5-slim
- **Platform**:

**Comment by fz6m** [comment]
换成 node 16 完整版再试
