### ISSUE TITLE
[Bug] 关于 jest 的一些问题

### ISSUE THREAD

**Issue by kokiy** [umijs/umi#8906]
### bug 1. 
 `Invalid value "automatic" in "--jsx=automatic"`
<img width="846" alt="image" src="https://user-images.githubusercontent.com/15773714/183353182-0109f4d7-1658-4771-8541-1d3c2990ddba.png">

### bug 2 .
测试覆盖率一直是0 
<img width="619" alt="image" src="https://user-images.githubusercontent.com/15773714/183353322-c79c1548-19bf-44dd-9971-2c974a2043eb.png">

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
https://github.com/kokiy/umi-test
 

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

npm run test

## Context

- **Umi Version**: 4.0.11 
- **Node Version**: 16.13.2
- **Platform**: mac & windows

**Comment by stormslowly** [comment]
bug1  应该是esbuild 么有升级 或者影子依赖了，建议删除 node_modules 再试试

bug2 我需要点时间

**Comment by stormslowly** [comment]
@kokiy   coverage 的问题有点麻烦 原来的  esbuild-jest 会支持 coverage 的（但是补不支持  --jsx 参数）
新换的 jest-esbuild 虽然支持了 jsx 参数的透传，当时没有考虑到 coverage 的问题。

明天和我cc讨论下。（感觉需要自己 fork 一个到 umi 里面去了

**Comment by sorrycc** [comment]
@stormslowly 在 packages/testing 下手写一个 esbuild-jest ？

**Comment by sorrycc** [comment]
@stormslowly 在 packages/testing 下手写一个 esbuild-jest ？

**Comment by stormslowly** [comment]
> @stormslowly 在 packages/testing 下手写一个 esbuild-jest ？

在做了 在做了（进度 0%  。。。 😂😂😂

**Comment by kokiy** [comment]
@stormslowly  还发现一个问题 我在vscode 用jest-runner 单独debug 一个case, 打的断点就不在源码所在位置了
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/15773714/184091322-42eef623-5bb8-4c1e-bab0-4c1373156413.png">
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/15773714/184091352-34f1e06d-ad44-4dfe-978f-8ad50138a734.png">

**Comment by stormslowly** [comment]
> @stormslowly 还发现一个问题 我在vscode 用jest-runner 单独debug 一个case, 打的断点就不在源码所在位置了 <img alt="image" width="1162" src="https://user-images.githubusercontent.com/15773714/184091322-42eef623-5bb8-4c1e-bab0-4c1373156413.png"> <img alt="image" width="1156" src="https://user-images.githubusercontent.com/15773714/184091352-34f1e06d-ad44-4dfe-978f-8ad50138a734.png">

这也一起解决了 你可以试试 link pr 的那个分支试试看
