### ISSUE TITLE
[Bug] 路由不支持大小写 设置 sensitive 无效

### ISSUE THREAD

**Issue by ClenLu** [umijs/umi#8911]
### Description
设置 sensitive 无效

<img width="602" alt="image" src="https://user-images.githubusercontent.com/17354771/183535865-ba1fe99f-6dd9-4c67-8257-f1d711ce5aa4.png">

http://localhost:8003/HoMe 依然能正常访问

### reproduce
https://github.com/ClenLu/umi4-router

**Comment by sorrycc** [comment]
用 caseSensitive 属性。
