### ISSUE TITLE
[Bug] VerifyCommit regexp does not match all emoji

### ISSUE THREAD

**Issue by drizzlesconsin** [umijs/umi#8912]
## What happens?

```ts
const emoji = `(((\ud83c[\udf00-\udfff])|(\ud83d[\udc00-\ude4f\ude80-\udeff])|[\u2600-\u2B55]) )?`;
const scope = ['feat', 'fix', 'docs', 'style', 'refactor', 'perf', 'test', 'workflow', 'build', 'ci', 'chore', 'types', 'wip', 'release', 'dep', 'deps', 'example', 'examples', 'merge', 'revert'];
const commitRE = new RegExp(`^((${emoji}(${scope.join('|')})(\\(.+\\))?:)|(Merge|Revert|Version)) .{1,50}`, 'i');

commitRE.test('⬆️ feat: xx')
false
commitRE.test('🚨 feat: xx')
true
commitRE.test('♻ feat: xx')
false
commitRE.test('♻ feat: xx')
true
commitRE.test('🎉 feat: xx')
true
commitRE.test('⬇️ feat: xx')
false
```

## Mini Showcase Repository(REQUIRED)

https://www.regextester.com/106421
```ts
/(\ud83c[\udf00-\udfff])|(\ud83d[\udc00-\ude4f\ude80-\udeff])|[\u2600-\u2B55]/ // 3038

/(\u00a9|\u00ae|[\u2000-\u3300]|\ud83c[\ud000-\udfff]|\ud83d[\ud000-\udfff]|\ud83e[\ud000-\udfff])/ // 4683
```
<img width="897" alt="image" src="https://user-images.githubusercontent.com/69514654/183540529-7d6d3090-f46b-4963-b577-c5222a0f85ff.png">

## How To Reproduce

**Expected behavior**
```ts
commitRE.test('⬆️ feat: xx')
true
commitRE.test('⬇️ feat: xx')
true
```

## Context

- **Umi Version**: 4.0.11

https://github.com/umijs/umi/blob/95c0f75aa03a972ec2a3d1c23fadfb471a7950af/packages/preset-umi/src/commands/verify-commit.ts#L39-L71

**Comment by fz6m** [comment]
可以用这个 https://github.com/mathiasbynens/emoji-regex/blob/main/index.js#L3

**Comment by drizzlesconsin** [comment]
@fz6m 借楼请教个问题

Umi4 targets 默认为 `chrome 87`

https://github.com/umijs/umi/blob/2ae7c7dc4efb94a2ab4da4408ef92d8d3ec3c7ab/examples/boilerplate/pages/global.less#L6-L12

## 预期

按这里的意思应该输出 `inset: 0`

## 实际结果

实际结果为原样输出

1. clone [repo](https://github.com/drizzlesconsin/umi4-issue-mini-example)
2. yarn build
3. open `dist/umi.js`
4. search `ant-modal-mask{position:fixed;top:0;right:0;`

**Comment by fz6m** [comment]
这个是用了 parcel css 的优化：

```ts
  cssMinifier: 'parcelCSS'
```

**Comment by drizzlesconsin** [comment]
Umi3 `targets: { ie: 11 }` 和 Umi4 `targets: { ie: 11 }` 输出结果不一样，不知道是做了什么变动。

在 Umi3 https://github.com/ant-design/ant-design/blob/master/components/style/mixins/box.less 这个 mixins 不会转成 `inset: 0`, Umi4 会转成 `inset: 0`.

@fz6m 想问下这块配置在哪看。

**Comment by drizzlesconsin** [comment]
在 Umi4 配置 `targets: { ie: 11 }`, 想要达到与 Umi3 `targets: { ie: 11 }` 一致的结果。
还需要将 [cssMinifier](https://umijs.org/docs/api/config#cssminifier) 配置为 `cssnano` [v3 cssnano](https://v3.umijs.org/config#cssnano), 否则可能会出现这个问题 https://github.com/ant-design/ant-design/issues/36744

**Comment by fz6m** [comment]
兼容性的问题在这里讨论：https://github.com/umijs/umi/issues/8658
