### ISSUE TITLE
[Feature Request] monorepo 中支持 max setup 关闭 husky install 功能

### ISSUE THREAD

**Issue by yunsii** [umijs/umi#8918]
## Background

monorepo 中配置 husky 应该是自行配置，参考文档：https://typicode.github.io/husky/#/?id=monorepo

## Proposal

max setup 支持关闭部分功能，目前看了源码好像都会走 onGenerateFiles 的回调？

**Comment by yunsii** [comment]
Feature Request 也要最小重现？\_(:з」∠)\_

**Comment by fz6m** [comment]
在 monorepo 中初始化项目是不会附带 husky 的，如果需要关闭，请使用：

```bash
  pnpm create umi --no-git
```
