### ISSUE TITLE
[Bug] 自定义运行时文件，getInitialState 方法不执行？

### ISSUE THREAD

**Issue by zengqingzhuang** [umijs/umi#8920]
## What happens?
// 通过插件的方式，添加了个运行时文件
api.addRuntimePlugin(() => [require.resolve('./runtime.tsx')]);

// runtime.tsx
export async function getInitialState() {
    console.log('runtime');
    return {
        userName: '用户名',
        userId: '用户 ID',
    };
}

export const layout: any = config => {
    const { initialState } = config;
    console.log('app', config);
    return {
        rightContentRender: () => <div>22222222222</div>,
        disableContentMargin: false,
        waterMarkProps: {
            content: initialState?.currentUser?.user_name,
        },
        footerRender: () => null,
        ...config,
    };
};

但是getInitialState没有执行，layout方法可以执行

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by zengqingzhuang** [comment]
> ## What happens?
> 自定义运行时文件 getInitialState没有执行，layout方法可以执行
> 
> ## Mini Showcase Repository(REQUIRED)
> > Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
> 
> ## How To Reproduce
> // 通过插件的方式，添加了个运行时文件 api.addRuntimePlugin(() => [require.resolve('./runtime.tsx')]);
> 
> // runtime.tsx export async function getInitialState() { console.log('runtime'); return { userName: '用户名', userId: '用户 ID', }; }
> 
> export const layout: any = config => { const { initialState } = config; console.log('app', config); return { rightContentRender: () =>
> 
> 22222222222
> ,
> disableContentMargin: false,
> waterMarkProps: {
> content: initialState?.currentUser?.user_name,
> },
> footerRender: () => null,
> ...config,
> };
> };
> 但是getInitialState没有执行，layout方法可以执行
> 
> **Steps to reproduce the behavior:** 1. 2.
> 
> **Expected behavior** 1. 2.
> 
> ## Context
> * **Umi Version**:
> * 4.0.11
> * **Node Version**:
> * 16.0.0
> * **Platform**:
> * mac

**Comment by xierenyuan** [comment]
`getInitialState` 只会读取 `app.tsx` 中的

**Comment by zengqingzhuang** [comment]
你好，项目里有个app.tsx，但是我还想自定义一个运行时文件用于做一些公共的事情，比如请求数据，所以想在getInitialState里做，如果自定义的getInitialState方法不执行的话，那我这种情况应该在那个方法里操作呢？

**Comment by zengqingzhuang** [comment]
> `getInitialState` 只会读取 `app.tsx` 中的

你好，项目里有个app.tsx，但是我还想自定义一个运行时文件用于做一些公共的事情，比如请求数据，所以想在getInitialState里做，如果自定义的getInitialState方法不执行的话，那我这种情况应该在那个方法里操作呢？

**Comment by xierenyuan** [comment]
> > `getInitialState` 只会读取 `app.tsx` 中的
> 
> 你好，项目里有个app.tsx，但是我还想自定义一个运行时文件用于做一些公共的事情，比如请求数据，所以想在getInitialState里做，如果自定义的getInitialState方法不执行的话，那我这种情况应该在那个方法里操作呢？
getInitialState 实现的是 useModel 你可以自定义一个对等能力的  从运行时读取 
 可以参考这里  https://github.com/umijs/umi/blob/master/packages/plugins/src/initial-state.ts
