### ISSUE TITLE
> `getInitialState` 只会读取 `app.tsx` 中的

### ISSUE THREAD

**Issue by zengqingzhuang** [umijs/umi#8922]
> `getInitialState` 只会读取 `app.tsx` 中的

你好，项目里有个app.tsx，但是我还想自定义一个运行时文件用于做一些公共的事情，比如请求数据，所以想在getInitialState里做，如果自定义的getInitialState方法不执行的话，那我这种情况应该在那个方法里操作呢？

_Originally posted by @zengqingzhuang in https://github.com/umijs/umi/issues/8920#issuecomment-1209003245_

**Comment by drizzlesconsin** [comment]
不知道这个是不是你想要的：https://github.com/ant-design/ant-design-pro/blob/all-blocks/src/app.tsx#L23-L51

**Comment by zengqingzhuang** [comment]
> 不知道这个是不是你想要的：https://github.com/ant-design/ant-design-pro/blob/all-blocks/src/app.tsx#L23-L51

我想在自定义的运行时文件中初始化数据

**Comment by zengqingzhuang** [comment]
> 不知道这个是不是你想要的：https://github.com/ant-design/ant-design-pro/blob/all-blocks/src/app.tsx#L23-L51

export const layout: RunTimeLayoutConfig = ({ initialState, setInitialState }) => {
    // const { initialState, setInitialState } = config;
    console.log('app', initialState, setInitialState);
    // const { initialState, loading, error, refresh, setInitialState } =
    // useModel('@@initialState');
    // setInitialState({
    //     a: 1,
    // });
    return {
        rightContentRender: () => <div>22222222222</div>,
        disableContentMargin: false,
        waterMarkProps: {
            content: initialState?.currentUser?.user_name,
        },
        footerRender: () => null,
        // ...config,
    };
};
自定义运行时文件里 { initialState, setInitialState } 这两个参数都是 undefined ?

**Comment by jianzhouf** [comment]
app.tsx 已经是约定的运行时扩展了，只是独立一个文件出来，在app.tsx里再引入你的文件不行吗

**Comment by jianzhouf** [comment]
> > `getInitialState` 只会读取 `app.tsx` 中的
> 
> 你好，项目里有个app.tsx，但是我还想自定义一个运行时文件用于做一些公共的事情，比如请求数据，所以想在getInitialState里做，如果自定义的getInitialState方法不执行的话，那我这种情况应该在那个方法里操作呢？
> 
> _Originally posted by @zengqingzhuang in [#8920 (comment)](https://github.com/umijs/umi/issues/8920#issuecomment-1209003245)_


app.tsx 已经是约定的运行时扩展了，只是独立一个文件出来，在app.tsx里再引入你的文件不行吗
