### ISSUE TITLE
umi@2 .env 没有生效？

### ISSUE THREAD

**Issue by yxqme** [umijs/umi#893]
umi@2 会支持 .env 的配置方法

这个的意思是在 `process.env` 可以访问到 `.env`里的常量吗？

umi@2.0.0-beta.17 发现并没有生效

**Comment by okoala** [comment]
提供可复现的方式

**Comment by yxqme** [comment]
配置环境 `.umirc.js` 里面是可以访问的到的

我的意思是 如果要在项目里访问 需要通过 `webpack define` 

这个不考虑设置成默认吗？

**Comment by okoala** [comment]
@yxqme 你要了解编译期和运行时的区别，几乎所有的配置都会编译期消化掉。
而项目可以访问到的配置只能是运行时的配置，`webpack define` 就是其中一个。
如果在项目中能访问到 process.env 对象是有安全风险的，你只能手动显式地透露出哪些配置是可以访问到的。

**Comment by weihomechen** [comment]
@okoala  请教一下，`umi`如何通过`webpack define`自定义变量，以便运行时可以访问到，我在`.umirc.js`里面这样定义：
```
  define: {
    'process.env.MOCK': '1234',
  },
  chainWebpack(config) {
    config
      .plugin('define')
      .use(webpack.DefinePlugin, [{ 'process.env.MOCK': '1234' }])
  },

```
项目运行时尝试访问`process.env.MOCK`,报错process为undefined，谢谢🙏

**Comment by okoala** [comment]
@weihomechen 你没理解啊，代码中是把 process.env.MOCK 整串替换成 1234

**Comment by weihomechen** [comment]
@okoala  这样啊，😂，大神那我该怎么自定义变量

**Comment by weishijun14** [comment]
@weihomechen `console.log(process.env.MOCK)` 你就能看见结果：'1234'

**Comment by songchengen** [comment]
我是这样使用的

```JavaScript
// .umi.js
define: {
        'window.API_HOST': process.env.API_HOST,
},

// package.json
"mock": "cross-env API_HOST=/api umi dev"

// usage

fetch(window.API_HOST + '/uri', {})
```
