### ISSUE TITLE
[Bug] UMI4.0.5以后的版本打包体积变大，命名规则差异较大

### ISSUE THREAD

**Issue by phoema** [umijs/umi#8931]
4.0.5打包17M
4.0.11打包118M

app.tsx中的childrenRender
    childrenRender: (children:any, props:any) => {
      // if (initialState?.loading) return <PageLoading />;
      let isHome = window.location.pathname == "/workflow/center" || window.location.pathname == "/" || window.location.pathname == "/dashboard/mydesk" ;
      return (
        <>
         <Outlet />
          {!window.location?.pathname?.includes('/login') && window.location?.pathname == ('/system/other/tools') && (
            <SettingDrawer
              disableUrlParams
              enableDarkTheme
              colorList = {colorList}
              settings={initialState?.settings}
              onSettingChange={(settings) => {
                setInitialState((preInitialState) => ({
                  ...preInitialState,
                  settings,
                }));
              }}
            />
          )}
        </>
      );
    },

UMI4.0.5打包效果
![image](https://user-images.githubusercontent.com/8730272/183836245-92cdfa2d-2f8e-4063-b5c9-605b01b57149.png)

UMI4.0.11打包效果
![image](https://user-images.githubusercontent.com/8730272/183836062-972b9b4e-a83a-4f15-acf7-47bd4807c0aa.png)

yarn.lock对比
![image](https://user-images.githubusercontent.com/8730272/183836371-e50ed0f7-5669-469b-ac23-8617ec773236.png)
[smart-frontend-company-umi4.zip](https://github.com/umijs/umi/files/9297608/smart-frontend-company-umi4.zip)

**Comment by phoema** [comment]
不知道为什么，版本升级上去以后，改回旧版本，编译不过去了。
改回4.0.5，yarn通过
yarn build 报如下错误
info  - Umi v4.0.5
fatal - TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at join (node:path:429:7)
    at Proxy.fn (D:\mywork\gitee\phoema\smart-frontend-company-umi4\node_modules\@umijs\max\node_modules\@umijs\preset-umi\dist\registerMethods.js:71:45)
    at Hook.fn (D:\mywork\gitee\phoema\smart-frontend-company-umi4\node_modules\@umijs\max\node_modules\@umijs\plugins\dist\initial-state.js:139:9)
    at D:\mywork\gitee\phoema\smart-frontend-company-umi4\node_modules\@umijs\max\node_modules\@umijs\core\dist\service\service.js:136:36
    at _next6 (eval at create (D:\mywork\gitee\phoema\smart-frontend-company-umi4\node_modules\@umijs\max\node_modules\@umijs\bundler-utils\compiled\tapable\index.js:1:8410), <anonymous>:102:17)
    at eval (eval at create (D:\mywork\gitee\phoema\smart-frontend-company-umi4\node_modules\@umijs\max\node_modules\@umijs\bundler-utils\compiled\tapable\index.js:1:8410), <anonymous>:127:1) {
  code: 'ERR_INVALID_ARG_TYPE'
}
fatal - A complete log of this run can be found in:
fatal - D:\mywork\gitee\phoema\smart-frontend-company-umi4\node_modules\.cache\logger\umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by drizzlesconsin** [comment]
可以试试
```bash
rm -rf src/.umi* node_modules yarn.lock
yarn
yarn build
```

**Comment by phoema** [comment]
也不行，我使用备份的yarn.lock恢复了，
感觉个别引用的npm包没有锁版本，有某个npm包版本更新导致的问题。

**Comment by xierenyuan** [comment]
可以使用   analyze  `"analyze": "ANALYZE=1 umi build"`  分析一下依赖构成, chunkName 命名规则是已知的变更不会影响打包体积

**Comment by phoema** [comment]
谢谢，主要是不太清楚是什么原因导致体积这么大的，之前UMI3的时候也遇到过，导致生产环境一直用的UMI2.

**Comment by phoema** [comment]
换回4.0.5打包体积实大实小，最早的时候yarn是比较小的，回退版本后大部分时候是体积大的。
实在是没有头绪。

**Comment by phoema** [comment]
formily在每个里面都有一份，另外，感觉就是把整个项目的src在每个js里面都打了一份。

![image](https://user-images.githubusercontent.com/8730272/183946642-84ab5199-0f80-4dcb-9e33-7d7021520d79.png)

**Comment by xierenyuan** [comment]
> formily在每个里面都有一份，另外，感觉就是把整个项目的src在每个js里面都打了一份。
> 
> ![image](https://user-images.githubusercontent.com/8730272/183946642-84ab5199-0f80-4dcb-9e33-7d7021520d79.png)

提供一个可以最小复现的 demo 吧

**Comment by sorrycc** [comment]
由于缺乏足够的信息，我们暂时关闭了该 Issue。请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example) 以重新开启 Issue。谢谢。
