### ISSUE TITLE
[Bug] umi4.0.11 启动antd样式丢失

### ISSUE THREAD

**Issue by oneplusonecy** [umijs/umi#8935]
项目中使用antd不加载样式，之前v3的时候
`defineConfig({
    fastRefresh: true,
    mfsu: {},
    history: { type: 'browser' },
    theme: {
        '@primary-color': '#2e74ff',
    },
    routes: routes，
    antd:true // v3可用，v4报错Invalid config keys: antd
})`

**Comment by drizzlesconsin** [comment]
https://umijs.org/docs/max/antd#antd

`antd: true` --> `antd: {}`

**Comment by oneplusonecy** [comment]
我没有使用umijs/max，
使用的umi
 import { defineConfig } from '@umijs/max';
import { defineConfig } from 'umi';
umi 的defineConfig  不支持antd属性，会报错fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: antd

**Comment by drizzlesconsin** [comment]
[Umi4 doc](https://umijs.org/docs/introduce/upgrade-to-umi-4#%E9%85%8D%E7%BD%AE%E5%B1%82%E8%BF%81%E7%A7%BB)

**Comment by oneplusonecy** [comment]
文档确实有写，但是允许就报错
$ npm run dev

> dev
> umi dev

fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: antd
    at Function.validateConfig (E:\codeup\qb\qb_web\node_modules\@umijs\core\dist\config\config.js:179:31)
    at Config.getConfig (E:\codeup\qb\qb_web\node_modules\@umijs\core\dist\config\config.js:60:12)
    at Service.resolveConfig (E:\codeup\qb\qb_web\node_modules\@umijs\core\dist\service\service.js:279:97)
    at Service.run (E:\codeup\qb\qb_web\node_modules\@umijs\core\dist\service\service.js:236:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Service.run2 (E:\codeup\qb\qb_web\node_modules\umi\dist\service\service.js:74:12)
    at async E:\codeup\qb\qb_web\node_modules\umi\dist\cli\forkedDev.js:24:5 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
fatal - A complete log of this run can be found in:
fatal - E:\codeup\qb\qb_web\node_modules\.cache\logger\umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues

**Comment by xierenyuan** [comment]
> 文档确实有写，但是运行就报错 $ npm run dev
> 
> > dev
> > umi dev
> 
> fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: antd at Function.validateConfig (E:\codeup\qb\qb_web\node_modules@umijs\core\dist\config\config.js:179:31) at Config.getConfig (E:\codeup\qb\qb_web\node_modules@umijs\core\dist\config\config.js:60:12) at Service.resolveConfig (E:\codeup\qb\qb_web\node_modules@umijs\core\dist\service\service.js:279:97) at Service.run (E:\codeup\qb\qb_web\node_modules@umijs\core\dist\service\service.js:236:50) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async Service.run2 (E:\codeup\qb\qb_web\node_modules\umi\dist\service\service.js:74:12) at async E:\codeup\qb\qb_web\node_modules\umi\dist\cli\forkedDev.js:24:5 { generatedMessage: false, code: 'ERR_ASSERTION', actual: false, expected: true, operator: '==' } fatal - A complete log of this run can be found in: fatal - E:\codeup\qb\qb_web\node_modules.cache\logger\umi.log fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues

参考这个  单独使用 https://github.com/umijs/umi/blob/master/examples/with-antd/.umirc.ts

**Comment by chenxlkamino** [comment]
同样使用umi4加载不出antd的样式，试了上面几个方案还是不行，请问这个问题有解决方案吗

**Comment by 8tme** [comment]
感觉antd升级到v5就可以，只不过人说v5不建议用到生产

**Comment by 8tme** [comment]
`
import { defineConfig } from '@umijs/max'

defineConfig({
   antd：{},
   ...
})
`

装antd4.x 和 antd5.x重新启动一下，应该OK的呀

**Comment by chenxlkamino** [comment]
您的邮件已经收到，我会尽快给您回复-------陈孝亮
祝您生活愉快！

**Comment by raexigaewe** [comment]
最近在从 umi v3 升级到 umi v4，按照官网文档，我理解应该只需要写 antd: {} 就可以使用 antd 的。
但我的项目启动后，antd 的样式全都没了，没找到任何解决办法，我又不想额外安装一下 antd 的依赖。
先降回 v3 + yarn 了，新项目再试试 v4

**Comment by chenxlkamino** [comment]
您的邮件已经收到，我会尽快给您回复-------陈孝亮
祝您生活愉快！

**Comment by Thulof** [comment]
@raexigaewe @chenxlkamino 我遇到了同样的问题，已解决。
在从 v3 升级到 v4 的时候，我把配置文件的形式从 ```.umirc.ts``` 转为了 `config/config.ts`，但我把它误放到了 src 目录下，所以事实上配置文件并没有生效。当我意识到这个问题之后，将 config 目录移出 src 目录后，一切都恢复了正常
