### ISSUE TITLE
[Feature Request] Umi文档Api的类型定义说明错误以及格式错误

### ISSUE THREAD

**Issue by Neptune-Krimy** [umijs/umi#8943]
## Background

Umi文档里，useOutletContext()的类型定义说明错误，以及useResolvedPath()的类型定义显示格式错误，少了ts格式

## Proposal

修改说明以为md文档增加ts格式

### useOutletContext()

https://umijs.org/docs/api/api#useoutletcontext

`declare function useOutlet(): React.ReactElement | null;`

![image](https://user-images.githubusercontent.com/93699620/183873528-d1bcf687-b623-464e-8ef2-7e9b3bec7d9b.png)

### useResolvedPath()

https://umijs.org/docs/api/api#useresolvedpath

![image](https://user-images.githubusercontent.com/93699620/183878283-238de9d4-39a7-45e6-959f-6758f6433172.png)

**Comment by sorrycc** [comment]
Resolved via #8937
