### ISSUE TITLE
[Bug] Module not found: Error: [CaseSensitivePathsPlugin]

### ISSUE THREAD

**Issue by flyingmylo** [umijs/umi#8945]
## What happens?

```
error in ./src/.umi/core/routes.ts
Module not found: Error: [CaseSensitivePathsPlugin] `desktop/project/demo/list/index.jsx` does not match the corresponding path on disk `List`
```

I got this error after `npm install` and `npm run dev` when I clone my project to a new directory. But it worked in another directory where the dependencies have been installed, so I think the reason is, that the old project's dependencies have not been updated, in other words, my project in the new directory has installed the latest update(latest version of umi).

## Mini Showcase Repository(REQUIRED)

> [https://github.com/flyingmylo/bug-report-to-umi](https://github.com/flyingmylo/bug-report-to-umi)

## How To Reproduce

> `package.json` in root direcotry:
> `/project/package.json`:   `"umi": "^3.5.8"`

The version of umi in `node_modules` is different:

`package.json` in old directory:
`/node_modules/@umi/package.json`: `"version": "3.5.27"`

`package.json` in new directory after `npm install`:
`/node_modules/umi/package.json`: `"version": "3.5.32"`

## Solution for now
I changed the version from `"umi": "^3.5.8"` to `"umi": "3.5.8"`

## Context

- **Umi Version**: ^3.5.8
- **Node Version**: v14.19.1
- **Platform**: Mac M1Pro

**Comment by sorrycc** [comment]
Why not fix this case problem?
