### ISSUE TITLE
[Bug] @umijs/max开启mfsu，resolve.modules失效。关闭mfsu生效

### ISSUE THREAD

**Issue by lvwei666** [umijs/umi#8948]
## What happens?
升级umi4后，resolve.modules失效
![image](https://user-images.githubusercontent.com/48077410/184060241-4930a9d2-72ce-4b2b-9357-4a32e99d6944.png)
![image](https://user-images.githubusercontent.com/48077410/184060291-05e91a79-995c-412b-a36b-56f51a57e717.png)
![image](https://user-images.githubusercontent.com/48077410/184060354-6f2a4ae0-557c-47c4-bd0b-6d2e0eb748b3.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
[github地址](https://github.com/lvwei666/umi4)

## How To Reproduce
**Steps to reproduce the behavior:** 1. 2.
yarn dev 即可复现

**Expected behavior** 1. 2.

## Context

- **Umi Version**: "@umijs/max": "^4.0.11"
- **Node Version**: 16.16.0
- **Platform**: mac M1

**Comment by sorrycc** [comment]
mfsu 暂不支持这种定制用法。
