### ISSUE TITLE
[Feature Request] umi 4.0版本的官方上，缺少“约定式路由”的相关文档，官方是准备逐步抛弃约定是路由的做法了吗？

### ISSUE THREAD

**Issue by Fuphoenixes** [umijs/umi#8952]
## Background

![image](https://user-images.githubusercontent.com/27912232/184077914-bb0810e9-444c-447b-a2ff-2e842b7474d0.png)

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by sorrycc** [comment]
在我的「TODO」里躺了好久了，会找时间写。
