### ISSUE TITLE
umi4   history.push({pathname: '/list',state:'aaa'})  不能传state了吗？

### ISSUE THREAD

**Issue by mwj610** [umijs/umi#8953]
![image](https://user-images.githubusercontent.com/52907799/184114019-1522aebb-e4ab-482b-bd6c-eef2d08d2525.png)

**Comment by drizzlesconsin** [comment]
看下写法 https://github.com/remix-run/history/blob/main/docs/api-reference.md#history.push

```ts
// Push a new entry onto the history stack with a query string
// and some state. Location state does not appear in the URL.
history.push("/home?the=query", { some: "state" });
```

**Comment by zhanchengkun** [comment]
> 看下写法 https://github.com/remix-run/history/blob/main/docs/api-reference.md#history.push
> 
> ```ts
> // Push a new entry onto the history stack with a query string
> // and some state. Location state does not appear in the URL.
> history.push("/home?the=query", { some: "state" });
> ```

使用history.push("/home?the=query", { some: "state" }); 后 页面取值history.location不会自动更新 一直都是F5后的第一个也页面信息，后续的 路由跳转都拿的是同一组数据
[重现] git@github.com:zhanchengkun/historyBug.git
