### ISSUE TITLE
[Bug] Dev banner not aligned

### ISSUE THREAD

**Issue by drizzlesconsin** [umijs/umi#8956]
## What happens?

<img width="485" alt="image" src="https://user-images.githubusercontent.com/69514654/184271162-a1c22e25-8763-461a-ab0b-80968d25116d.png">

## Mini Showcase Repository(REQUIRED)

https://github.com/umijs/umi/blob/abb06f2ccd1923169cdd2a72733005e5ee43cc8c/packages/utils/src/getDevBanner.ts#L50-L52
## How To Reproduce

或许不需要加 `+ 1`

```diff
-  maxLen - stripAnsi(footer).length + 1,
+  maxLen - stripAnsi(footer).length,
```

<img width="409" alt="image" src="https://user-images.githubusercontent.com/69514654/184271517-c4c5fe8f-8418-4185-9428-812d2f5786db.png">

## Context

- **Umi Version**: 4.0.12
- **Node Version**: 14
- **Platform**: macOS

**Comment by PeachScript** [comment]
我这里不 +1 有问题，看来去掉 emoji 是最好的选择…

**Comment by fz6m** [comment]
> 我这里不 +1 有问题，看来去掉 emoji 是最好的选择…

试试白皮肤，其他肤色是混合的，字符多
