### ISSUE TITLE
umi升级2.0版本antd由内置变配置，导致antd样式优先级高于global.css样式

### ISSUE THREAD

**Issue by Jude214** [umijs/umi#896]
umi 2.0版本以前通过global.css覆盖antd组件默认样式的方式来自定义组件样式，升级umi 2.0版本后自定义样式失效，推测2.0版本antd由内置变为配置后在global.css后加载，优先级高于glocal.css.

**Comment by sorrycc** [comment]
glocal.css 应该在 antd 之后引入？

**Comment by Jude214** [comment]
现在问题就是没有方案覆盖antd组件默认样式

**Comment by yutingzhao1991** [comment]
`global.css` 这个优先级应该是最高的。

**Comment by Jude214** [comment]
global.css自定义的样式：![image](https://user-images.githubusercontent.com/13598600/44521979-a46cbf00-a707-11e8-9bde-bfdf5b7a8db1.png)
![image](https://user-images.githubusercontent.com/13598600/44521980-a6368280-a707-11e8-8c62-7053da6aa86c.png)
运行结果：![image](https://user-images.githubusercontent.com/13598600/44521981-a898dc80-a707-11e8-9cdf-cabc4ce10534.png)

**Comment by superlbr** [comment]
如果在layout里的样式呢?

**Comment by superlbr** [comment]
遇到一个bug，本地dev的umi.css里没有antd的样式。。。

**Comment by Jude214** [comment]
2.0是需要自己手动配置是否使用antd的，你的.umirc.js中是否有如下配置：
![image](https://user-images.githubusercontent.com/13598600/44560862-521db380-a784-11e8-85ed-558bc473b676.png)

**Comment by superlbr** [comment]
@Jude214 这里只是配置是否按需加载antd

**Comment by sorrycc** [comment]
@superlbr umi dev 时候没有 antd 的样式？怎么重现？我记得跑 antd-admin 和 antd-pro 都没遇到啊。

**Comment by sorrycc** [comment]
通过以下命令可以有一些额外信息，

* `DEBUG=umi*,af-webpack* umi dev`
* umi -v --verbose

**Comment by okoala** [comment]
直接提供能复现的最小代码仓库

**Comment by superlbr** [comment]
来来来，都到坑里来 @sorrycc  @okoala

`yarn install react-umeditor --save`

**Comment by Viin-zx** [comment]
额，之前为了防止自定义样式被覆盖，选择在Layout加载之后再引入css，现在升级到2.0之后。这样都不行了。
![image](https://user-images.githubusercontent.com/19523605/44640223-0ae92a00-a9f3-11e8-9546-3e6de6dc5935.png)

**Comment by xiaohuoni** [comment]
@superlbr @sorrycc 
关于react插件的antd配置
https://umijs.org/plugin/umi-plugin-react.html#antd
这里写的是
> 启用后自动配置 babel-plugin-import 实现 antd 和 antd-mobile 的按需编译，并且内置 antd 和 antd-mobile 依赖，无需手动在项目中安装。 

而在[如何从umi1.0迁移到2.0中的示例代码](https://umijs.org/guide/migration.html#%E9%85%8D%E7%BD%AE)里，写的却是
>// antd 默认不开启，如有使用需自行配置

**Comment by Viin-zx** [comment]
@xiaohuoni 额，我这边实测，global.css里面的样式是被antd样式覆盖了的，beta18版本。 

在1.x中，因为antd样式优先，所以我选择在layout->app.js 组件加载完之后再引入自定义样式，如上图。

但是在2.0中这样也不行了，按正常情况，组件都加载完了，antd样式也应该加载完了，这时候我再加载自定义样式，这样应该是可行的吧。

**Comment by xiaohuoni** [comment]
@Viin-zx 假设一种场景，所有的样式都记载完成了，然后又引入一个新的组建，antd是按需加载的，所以最后的这个antd的样式，是不是就存在问题了。根据场景解释一下：假设我的应用里面所有的按钮，都要大小是500的。然后我全局定义了antd的按钮样式是500.初始化页面的时候，没有问题。然后再访问另一个页面。按钮大小就变成了antd的默认值。

**Comment by Viin-zx** [comment]
@xiaohuoni 您说的组件是按需加载，但是样式没有吧，样式应该还是一次性引入的，所以不会影响后面加入的组件样式。

然后我刚刚测试到了一个问题，请教一下，2.0中代码里面的require和import是不是会被提到了组件的最顶端引入。看我这个代码。
![image](https://user-images.githubusercontent.com/19523605/44699959-35051f80-aab9-11e8-8138-139bab521bf5.png)

1，require有条件判断，应该不会执行。
2，我在debugger断点查看dom的时候，require已经执行了。

**Comment by feibi** [comment]
确实存在这个问题，umi@1.3.18版本的global.less会覆盖掉antd，升级到umi@2就不行了

**Comment by NexxLuo** [comment]
这个问题最终应该怎么处理，现在2.0.1，依然存在这个问题。因为global.css中的样式太多，都加important并不是解决方式，而且如果antd中的样式也加了important，global.css中加important就无效了。

**Comment by sorrycc** [comment]
global.css 是在后面的，但如果开启按需加载，那就没啥好办法了，通过优先级处理。优先级不一定是加 !important，也可以加 id 前缀。

**Comment by smithyj** [comment]
2.2.7 依旧不行

**Comment by smithyj** [comment]
开启了 dynamicImport 就会导致失效

**Comment by zjafei** [comment]
#root{
  .antd-btn {
    自定义...
  }
}

**Comment by gitofrenlu** [comment]
> 现在问题就是没有方案覆盖antd组件默认样式
请问现在找到解决办法了吗

**Comment by exvu** [comment]
@superlbr 我的也是引入react-umeditor出现global。less异常，你是怎么解决的。

**Comment by superlbr** [comment]
@exvu umi升到最新

**Comment by exvu** [comment]
@superlbr 依然不行，能否给我看一下你的package.json

**Comment by superlbr** [comment]
@exvu 
```  
"dependencies": {
    "ant-design-pro": "^2.2.1",
    "antd": "^3.15.1",
    "axios": "^0.18.0",
    "classnames": "^2.2.6",
    "dragm": "^0.0.5",
    "dva-model-extend": "^0.1.2",
    "echarts": "^4.2.1",
    "echarts-for-react": "^2.0.15-beta.0",
    "jsonp": "^0.2.1",
    "lodash": "^4.17.11",
    "nprogress": "^0.2.0",
    "path-to-regexp": "^3.0.0",
    "prop-types": "^15.7.2",
    "qs": "^6.7.0",
    "react-amap": "^1.2.8",
    "react-countup": "^4.1.1",
    "react-dnd-touch-backend": "^0.8.1",
    "react-easy-print": "^0.6.0",
    "react-helmet": "^5.2.0",
    "react-highlight-words": "^0.16.0",
    "react-perfect-scrollbar": "^1.4.4",
    "react-sortable-tree": "^2.6.2",
    "react-umeditor": "^1.0.15",
    "screenfull": "^4.1.0",
    "store": "^2.0.12"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "babel-plugin-dev-expression": "^0.2.1",
    "babel-plugin-module-resolver": "^3.2.0",
    "cross-env": "^5.2.0",
    "eslint": "^5.15.3",
    "eslint-config-react-app": "^3.0.8",
    "eslint-plugin-flowtype": "^3.4.2",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.12.4",
    "husky": "^1.3.1",
    "jsinspect": "^0.12.7",
    "less-vars-to-js": "^1.3.0",
    "mockjs": "^1.0.1-beta3",
    "module": "^1.2.5",
    "prettier": "^1.16.4",
    "stylelint": "^9.10.1",
    "stylelint-config-prettier": "^5.0.0",
    "stylelint-config-standard": "^18.2.0",
    "umi": "^2.6.8",
    "umi-plugin-react": "^1.7.2"
  }
```

**Comment by exvu** [comment]
@superlbr 升级并没有解决问题，后台我发现是dll的问题，希望给大家一个参考
`
...(!TEST && os.platform() === 'darwin'
      ? {
          dll: {
            include: ['dva', 'dva/router', 'dva/saga', 'dva/fetch',],
            exclude: ['@babel/runtime','react-umeditor'],
          },
          hardSource: false,
        }
      : {}),
`

**Comment by Jarryxin** [comment]
目前把全局的 global.css 中的文件，写在 layout中的 scss文件中，
.root{
  :global{
     ...golbal.css
  }
} 然后把root写在layout的组件上

**Comment by itellyou-com** [comment]
将 
```
dll:true
```
改为
```
dll: {
       exclude:[
           'antd',
           'antd-mobile'
      ]
}
```
解决问题

**Comment by CheneyZhangCH** [comment]
> 目前把全局的 global.css 中的文件，写在 layout中的 scss文件中，
> .root{
> :global{
> ...golbal.css
> }
> } 然后把root写在layout的组件上

Modal, Popover 等组件是挂在body下面的， 如果写成
```
.root{
:global{
...golbal.css
}
} 
``` 权重又不够了

**Comment by li5tun** [comment]
global.less中部分样式规则需要加上 #root, 增加权重

**Comment by mikedeng** [comment]
@li5tun 如果是popover和modal，又不行了。

**Comment by tangsengrouyidai** [comment]
> global.less中部分样式规则需要加上#root，增加权重

不可取，这样会导致全局样式规则权重高于页面样式

**Comment by WLyKan** [comment]
我用的好好的，突然就出现这个问题了。把lock文件，node_modules全部干掉重装都不行，升级到了最新版的umi，还是不行
