### ISSUE TITLE
[Bug] 如果设置了rootContainer，对route的权限配置会失效

### ISSUE THREAD

**Issue by chenjianfang** [umijs/umi#8960]
设置了rootContainer，对route的权限配置会失效

![image](https://user-images.githubusercontent.com/13289959/184304777-63fd6090-e8ff-4d55-9b6f-779342809730.png)
access插件对权限的控制会失效

- **Umi Version**: 3.5.32

**Comment by weicong** [comment]
这个问题怎么解决？
