### ISSUE TITLE
[Bug] 微前端 umi max 主应用，cra 子应用，子应用路由访问不了。

### ISSUE THREAD

**Issue by giscafer** [umijs/umi#8965]
## What happens?

umi max 微前端 子应用加载正常，但无法进入子应用路由

## Mini Showcase Repository(REQUIRED)

https://github.com/giscafer/micro-umi-max-cra

> sub-app 为 cra 子应用

## How To Reproduce

 加载子应用后，点击子应用路由。

<img width="753" alt="demo0" src="https://user-images.githubusercontent.com/8676711/184467365-1a7c7779-84a2-4ab1-89e9-61a86d7351f7.png">

<img width="834" alt="demo" src="https://user-images.githubusercontent.com/8676711/184527791-7691e8c2-a6dd-4bc3-9fa0-862f18731087.png">

## Context

- **Umi Version**: 4.0.12
- **Node Version**: 18.5.0
- **Platform**: win & macos

**Comment by jk4235** [comment]
子应用设置`base: "/"`试试

**Comment by giscafer** [comment]
> 子应用设置`base: "/"`试试

这样不行的。

**Comment by SubinY** [comment]
![1660579355940](https://user-images.githubusercontent.com/21135159/184671397-717d55d9-ffec-4977-a787-dcefda53a63e.png)
![image](https://user-images.githubusercontent.com/21135159/184671480-c2db067d-1557-4134-b507-38ad9bf4665d.png)

**Comment by giscafer** [comment]
插件缺少没生效，需要手动配置一下通配符子路由。可解决。感谢大佬 @SubinY

**Comment by PeachScript** [comment]
> qiankun插件自动添加确实没生效

qiankun 的自动添加逻辑不是用于用户的路由配置的，Umi 4 升级到 react-router@6 了，子路径匹配是需要手动加通配符的

**Comment by giscafer** [comment]
> 子路径匹配

那建议这个应该在新版文档说清楚。

**Comment by kgloveyou** [comment]
> qiankun插件自动添加确实没生效，需要手动配置一下通配符子路由。可解决问题。感谢大佬 @SubinY

大佬，能在上面那个仓库里面说明下怎么修改吗？

**Comment by kgloveyou** [comment]
微前端 @umijs/plugin-qiankun 主应用，cra 子应用，可行吗？

**Comment by giscafer** [comment]
@kgloveyou  可行的。参考工程https://github.com/giscafer/rh-template-gis
