### ISSUE TITLE
根据文档跑Umi4新建项目，尝试使用微生成器 报错[Bug] say something

### ISSUE THREAD

**Issue by gaomeng965** [umijs/umi#8977]
## What happens?

根据文档跑Umi4新建项目项目安装完后，尝试使用微生成器 报错
```
Invalid config keys: antd, access, model, initialState, request, layout, npmClient
```

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
步骤为：

```
// 执行
 pnpm dlx create-umi@latest

// 选择 pnm ----->  antd design pro ----->  taobao

// 执行
umi generate  
// 或者 umi g
// 报错
Invalid config keys: antd, access, model, initialState, request, layout, npmClient
```

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0
- **Node Version**: 16.7.0
- **Platform**: MAC OS

**Comment by gaomeng965** [comment]
文档中 没有相关的介绍说明，如果 使用 微生成器 有其它依赖或者环境 要求的话，也希望能得到一些提示指引

**Comment by fz6m** [comment]
max 项目需要使用 `max g`

**Comment by gaomeng965** [comment]
> max 项目需要使用 `max g`

应该是跟 pnpm有关，我使用yarn重新初始化项目 可以成功运行
