### ISSUE TITLE
我到底要不要升级umi2.0

### ISSUE THREAD

**Issue by jiahangLee** [umijs/umi#898]
umi1.0+dva@2的项目刚写了一周，umi2.0就出来了，我觉得1.0用着还好，业务不很复杂，作为一个后端，0配置框架很适合上手，我粗略看了下升级的文档，好像很多东西都需要手动配置了，并没有深究，我想问下2.0升级的意义，我到底该不该升级

**Comment by okoala** [comment]
要往前看，之后的新特性只会在最新版，包括插件等生态~ 在升级成本不大的情况下就升
觉得 beta 版不稳定，可以先 Ready，等正式版也是可以的。

**Comment by zjxpcyc** [comment]
建议不要, 先用 umi1.0 。等 2.x 版本稳定了，并且你熟悉了一些前端工具，再选择升级。

**Comment by sorrycc** [comment]
有疑虑的先 Hold，等 2.0 正式发布时参考 chenglog，认同后再更新。
