### ISSUE TITLE
[Bug] Chrome低版本浏览器兼容性

### ISSUE THREAD

**Issue by kjxbyz** [umijs/umi#8985]
## What happens?

无法在Chrome 78打开umi项目，设置targets无效

![截屏2022-08-16 15 09 43](https://user-images.githubusercontent.com/47768002/184818928-e59bb567-32c0-455b-97ca-86d63186ad1d.png)

## Mini Showcase Repository(REQUIRED)

https://github.com/see/umijs-outlet-issue

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:  4.0.11
- **Node Version**: v14.19.0
- **Platform**: macos

**Comment by fz6m** [comment]
代理关了试试。

**Comment by see** [comment]
关闭`mfsu`就可以了

**Comment by smpower** [comment]
@fz6m 我们也遇到了相关问题。关闭代理打包发布到线上也会报错，而且 Chrome 78 同样无法访问你们的官网 [umijs.ocm](https://umijs.org/)。
![image](https://user-images.githubusercontent.com/24548536/185016343-9236c1ac-4a3a-4766-97e2-83c510da06cc.png)

## Context
- Umi Version: 4.0.11
- Node Version: v14.19.0
- Platform: Windows 10
- Chrom Version: 78.0.3904.97（正式版）（64位）

**Comment by fz6m** [comment]
当你需要兼容某个版本浏览器时，需要指定：

```ts
// .umirc.ts

export default {
  targets: {
    chrome: 78
  }
}
```

当你需要兼容 es5 时，可参考：https://umijs.org/docs/introduce/faq#ie-%E5%85%BC%E5%AE%B9%E6%80%A7%E9%97%AE%E9%A2%98

**Comment by yaodong5063** [comment]
target里面设置了ie:false,firfox:false直接给报没这两个属性

**Comment by drizzlesconsin** [comment]
> target里面设置了ie:false,firfox:false直接给报没这两个属性

不要 不加就好了，或者版本加高点。

https://esbuild.github.io/api/#target
https://github.com/umijs/umi/blob/master/packages/bundler-webpack/src/utils/browsersList.test.ts
https://github.com/umijs/umi/blob/master/packages/bundler-vite/src/config/transformer/target.test.ts

**Comment by xiaohuoni** [comment]
低浏览器相关的兼容，可以使用配置 [legacy](https://umijs.org/docs/api/config#legacy) 
有其他异常欢迎新开 issues 讨论
