### ISSUE TITLE
umi run 命令

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#8987]
## 问题

项目和 npm 包研发时，都需要写脚本。目前推荐的用法是 tsx（源 esno） + zx，希望把这种方式通过框架/工具的形式推荐给更多人，开箱即用。同时 zx 4 以上是 pure esm 的产物，和 tsx 不能结合使用，所以需要一个 cjs 的版本，这一层可以在封装时抹平掉。

## 方案

最终用法是在 umi 和 father 层提供 `run` 子命令，比如。

```bash
$ umi run scripts/release.ts
$ father run scripts/release.ts
```

实现方案，

1、新增子包 @umijs/plugin-run，然后在 father 和 @umijs/preset-umi 中引入这个插件
2、@umijs/plugin-run 封装 tsx，支持配置 `run: { globals: string[] }` 自动注入全局脚本，比如注入 `umi/run-globals`
~~3、提供 umi/run-globals 和 father/run-globals 文件，reexport 自 zx/globals~~
4、umi pr ok 且发布之后再处理 father

## 参考

* https://github.com/umijs/umi/pull/8975
* https://github.com/Kikobeats/zx-cjs

**Comment by txp1035** [comment]
认领

**Comment by txp1035** [comment]
![image](https://user-images.githubusercontent.com/9554297/185154153-7bf2d822-652e-467f-b509-f1ea32d85d3c.png)
问题1：自动注入脚本作用是什么？我有两个理解：1. 用户的几个脚本并行运行，如果是这样应该在什么阶段执行 2. 脚本里面的第一行`import 'umi/run-globals';`，可以基于缓存实现，但是如果不带这一行用户写脚本没有提示好像也不太友好。
