### ISSUE TITLE
[Bug] umi 3； SCRIPT5022: 引发了异常但未捕获  IE10 IE9

### ISSUE THREAD

**Issue by ijisen** [umijs/umi#8988]
## What happens?
`以下都是使用 yarn create @umijs/umi-app 创建的demo环境，没有额外配置。`
### umi3 按照官方文档配置， 设置 targets: {   ie: 10 }；打包后，可以正常访问。
配置如下：
```
// .umirc.ts
{
  hash: true,
  nodeModulesTransform: {
    type: 'all',
  },
  routes: [
    { path: '/', component: '@/pages/index' },
  ],
  dynamicImport: {},
  exportStatic: {},
  fastRefresh: {},
  targets: {
    ie: 10,
  },
}
```
### 配置国际化打包后，在IE下会报错：`SCRIPT5022: 引发了异常但未捕获`
```
// .umirc.ts 添加如下配置， 同时在 src下添加 src/locales/en-US.ts 和 src/locales/zh-CN.ts
{
  locale: {
    default: 'zh-CN',
    antd: false,
    title: false,
    baseNavigator: true,
    baseSeparator: '-',
  },
}
```
### 原因
在IE10 IE9下，会执行插件的这段代码； 这里获取到availableLocales.length的值为0；

PS: 在 IE11 和其它浏览器都不会执行这段代码。
```
// node_modules/intl/lib/core.js
function /* 9.2.5 */ResolveLocale(availableLocales, requestedLocales, options, relevantExtensionKeys, localeData) {
    if (availableLocales.length === 0) {
        throw new ReferenceError('No locale data has been provided for this object yet.');
    } 
 ...
```

## Mini Showcase Repository(REQUIRED)
https://github.com/ijisen/umijs-ie-issue

## How To Reproduce
yarn build
IE 10 访问

## Context

- **Umi Version**: ^3.5.32
- **Node Version**: v16.14.0
- **Platform**: windows

**Comment by sorrycc** [comment]
IE 最低到 11，不支持 9 和 10。因为 react 也不支持了。
