### ISSUE TITLE
[Feature Request] dva 增加 skipModelValidate，跳过model文件有效性检查

### ISSUE THREAD

**Issue by feibi** [umijs/umi#8992]
## Background

model文件可能导出的是函数，比如
```tsx
export default getModel();

//getModel() 返回值符合model定义要求
```

## Proposal

AST分析做不到，不如像umi3一样给参数跳过检查？

**Comment by Soundmark** [comment]
同认为有需要

**Comment by feibi** [comment]
[v4.0.22](https://github.com/umijs/umi/releases/tag/v4.0.22) 已增加, #9388
