### ISSUE TITLE
umi4 创建的项目在手机浏览器访问白屏

### ISSUE THREAD

**Issue by HurriedOn** [umijs/umi#8997]
## What happens?

umi4 创建项目后在PC端浏览器打开正常，使用手机浏览器打开是白屏且没有报错信息。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

手机浏览器访问效果：
<div align="center">
<img src="https://user-images.githubusercontent.com/26838083/185017255-0ca99bc5-1d57-46e8-9d70-372f2a87e3f4.jpeg" width='40%'   />
</div>

## How To Reproduce

1. 按照官网流程创建项目：
```base
mkdir myapp && cd myapp
yarn create umi
```
![image](https://user-images.githubusercontent.com/26838083/184794662-61f20e76-5ea7-4671-83bc-7ff8d0d923c4.png)
2. 运行 `yarn start`
3. 使用手机iPhone 11 safari浏览器访问是白屏
## Context

- **Umi Version**: 4.0.12
- **Node Version**: 16.13.1
- **Platform**: Mac

**Comment by fz6m** [comment]
通过指定 targets 来降低适配，尝试解决你的部分问题：https://umijs.org/docs/api/config#targets

**Comment by HurriedOn** [comment]
> 通过指定 targets 来降低适配，尝试解决你的部分问题：https://umijs.org/docs/api/config#targets

没有设置targets，现在的问题是项目打包后在生产环境下手机访问是正常的，开发环境访问白屏。而且手机是ios 15.6.1最新版本

**Comment by wushanchao** [comment]
umi4脚手架自带的开发服务器配置问题，那边的socket写死localhost了

**Comment by fz6m** [comment]
目前 `4.0.15` 版本，我用手机访问局域网地址，开发环境是正常运行的。

<img src='https://user-images.githubusercontent.com/59400654/187610374-fca9f624-ef90-42c5-85d2-97ba63f063df.png' width='35%' />

**Comment by HurriedOn** [comment]
> 目前 `4.0.15` 版本，我用手机访问局域网地址，开发环境是正常运行的。
> 
> <img alt="" width="35%" src="https://user-images.githubusercontent.com/59400654/187610374-fca9f624-ef90-42c5-85d2-97ba63f063df.png">

是的，我现在用"umi": "^4.0.15"创建项目也没有这个问题了

**Comment by hanwenbo** [comment]
"umi": "^4.0.15" 存在这个bug，在安卓设备上无法显示，升级到"umi": "4.0.15" 能显示错误，但提示globalThis is not defined
![image](https://user-images.githubusercontent.com/5869741/187683374-4deb0942-6338-49e3-b6ad-917348df74f1.png)

**Comment by hanwenbo** [comment]
每次刷新报错都不太一样
![image](https://user-images.githubusercontent.com/5869741/187684973-2a7f9df7-c6c6-45e6-bc6a-2d222395647f.png)

**Comment by fz6m** [comment]
现在把 `globalThis` 去掉了，可以看下最新版本有没有问题。
