### ISSUE TITLE
支持 es5 语法检测

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#8999]
## 问题

有些场景还需要支持 es5，目前没有 es5 语法校验，开发者只能在 build 之后到浏览器里才能看到是否报错。

## 解法

1、提供一个插件，比如 @umijs/plugin-es-check，通过配置 `esCheck` 开启，在编译时（build）做 es 语法校验
2、校验不通过时提供文件和行号信息
3、加分：用 @babel/code-frame 显示出错信息
4、考虑用 https://github.com/yowainwright/es-check ，但尺寸较大（es-check size: 17M+）

**Comment by ahwgs** [comment]
直接使用 `acorn` 跑一下呢？
比如
```js
acorn.parse(code,{
  ecmaVersion:5
})
```
报错的话用 code-frame 显示下错误行数？

**Comment by 2239559319** [comment]
不应该是检查es6吗，只能跑es5所有得检测有没有es6的语法或者api
