### ISSUE TITLE
pages 文件夹下定义 test.js，/test 路由正确匹配，/test/ 路由匹配失败

### ISSUE THREAD

**Issue by ThaddeusJiang** [umijs/umi#90]
![umi route bug](https://user-images.githubusercontent.com/17308201/35767086-6b6507b2-0928-11e8-9a04-d6fa9fc19cab.gif)

期待结果：
/test/ 也应该匹配 test.js

**Comment by sorrycc** [comment]
用 react-router@4 也不会自动匹配吧？

**Comment by ThaddeusJiang** [comment]
@sorrycc 用 react-router@4 是可以自动匹配的。

我简单的试了一下：
![umi route bug-2](https://user-images.githubusercontent.com/17308201/35774616-38b63bde-09b8-11e8-9c8c-ca14d6ba8766.gif)

**Comment by sorrycc** [comment]
你没有加上 exact，所以是模糊匹配的。

**Comment by ThaddeusJiang** [comment]
你好，我又确认了一下。
只追加 exact 依旧可以匹配，但是如果同时 exact+strict 就不能匹配了。

我觉得 umi 现在的路由匹配规则有点像同时 exact+strict。
[react-router api](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Route.md#exact-bool)

path | location.pathname | matches?
-- | -- | --
/one | /one | yes
/one | /one/ | no
/one | /one/two | no

![umi route bug-3](https://user-images.githubusercontent.com/17308201/35775582-d3ce3e1c-09ce-11e8-83a7-f2c3a19dbba8.gif)

**Comment by sorrycc** [comment]
+ umi@1.0.0-rc.13
