### ISSUE TITLE
umiv4 register failed, invalid key request from plugin src/app.tsx

### ISSUE THREAD

**Issue by hanxzi** [umijs/umi#9003]
## What happens?

Unhandled Rejection (Error): register failed, invalid key request from plugin /Users/xxx/src/app.tsx.
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/15724884/185090130-b4d0b0c6-702a-4a4d-b28b-e214b9bbc64c.png">

## How To Reproduce

```
 pnpm dlx create-umi@latest
 + create-umi 4.0.12
✔ Pick Umi App Template › Simple App
✔ Pick Npm Client › pnpm
✔ Pick Npm Registry › taobao

```
```
//src/app.ts
import type { RequestConfig } from 'umi'; 
export const request: RequestConfig = {
    timeout: 1000,
    // other axios options you want
    errorConfig: {
      errorHandler(){
      },
      errorThrower(){
      }
    },
    requestInterceptors: [],
    responseInterceptors: []
};
```

## Context

- **Umi Version**:  "^4.0.12"
- **Node Version**: v14.17.5
- **Platform**: mac

**Comment by hanxzi** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hanxzi** [comment]
> ## What happens?
> Unhandled Rejection (Error): register failed, invalid key request from plugin /Users/xxx/src/app.tsx. <img alt="image" width="1105" src="https://user-images.githubusercontent.com/15724884/185090130-b4d0b0c6-702a-4a4d-b28b-e214b9bbc64c.png">
> 
## Mini Showcase Repository(REQUIRED)

> ```
> 
> ```
> //src/app.ts
> import type { RequestConfig } from 'umi'; 
> export const request: RequestConfig = {
>     timeout: 1000,
>     // other axios options you want
>     errorConfig: {
>       errorHandler(){
>       },
>       errorThrower(){
>       }
>     },
>     requestInterceptors: [],
>     responseInterceptors: []
> };
> ```
> ## How To Reproduce
> ```
>  pnpm dlx create-umi@latest
>  + create-umi 4.0.12
> ✔ Pick Umi App Template › Simple App
> ✔ Pick Npm Client › pnpm
> ✔ Pick Npm Registry › taobao

> 
> ## Context
> * **Umi Version**:  "^4.0.12"
> * **Node Version**: v14.17.5
> * **Platform**: mac

**Comment by kungege** [comment]
same issue

**Comment by kungege** [comment]
@hanxzi  use `import type { RequestConfig } from 'umi';`, maybe can help you.

**Comment by frank367** [comment]
遇到同样的问题

**Comment by zl802925** [comment]
> RequestConfig

请问解决了吗

**Comment by hanxzi** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zl802925** [comment]
> 遇到同样的问题

请问你解决了吗
