### ISSUE TITLE
能支持离线文档吗？gh-pages ，sgo --fallback

### ISSUE THREAD

**Issue by srarlight** [umijs/umi#9004]
公司内网 访问不了外网文档，我看ant-design有个ant-design-gh-pages分支 支持sgo本地启动

**Comment by fz6m** [comment]
clone 仓库之后：

```bash
  pnpm i
  pnpm build
  pnpm doc:build
```

把 `dist` 产物跳板机传到内网部署即可，注意有些公网图片可能需要手动在 `docs/*` 下面改成本地的。
