### ISSUE TITLE
umi v4 register failed, invalid key request from plugin src/app.ts

### ISSUE THREAD

**Issue by hanxzi** [umijs/umi#9008]
> ## What happens?
> Unhandled Rejection (Error): register failed, invalid key request from plugin /Users/xxx/src/app.tsx. <img alt="image" width="1105" src="https://user-images.githubusercontent.com/15724884/185090130-b4d0b0c6-702a-4a4d-b28b-e214b9bbc64c.png">
> 
## Mini Showcase Repository(REQUIRED)

> ```
> 
> ```
> //src/app.ts
> import type { RequestConfig } from 'umi'; 
> export const request: RequestConfig = {
>     timeout: 1000,
>     // other axios options you want
>     errorConfig: {
>       errorHandler(){
>       },
>       errorThrower(){
>       }
>     },
>     requestInterceptors: [],
>     responseInterceptors: []
> };
> ```
> ## How To Reproduce
> ```
>  pnpm dlx create-umi@latest
>  + create-umi 4.0.12
> ✔ Pick Umi App Template › Simple App
> ✔ Pick Npm Client › pnpm
> ✔ Pick Npm Registry › taobao

> 
> ## Context
> * **Umi Version**:  "^4.0.12"
> * **Node Version**: v14.17.5
> * **Platform**: mac

**Comment by zl802925** [comment]
> > ## What happens?
> > Unhandled Rejection (Error): register failed, invalid key request from plugin /Users/xxx/src/app.tsx. <img alt="image" width="1105" src="https://user-images.githubusercontent.com/15724884/185090130-b4d0b0c6-702a-4a4d-b28b-e214b9bbc64c.png">
> 
> ## Mini Showcase Repository(REQUIRED)
> > ```
> > 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > //src/app.ts
> > import type { RequestConfig } from 'umi';
> > export const request: RequestConfig = {
> > timeout: 1000,
> > // other axios options you want
> > errorConfig: {
> > errorHandler(){
> > },
> > errorThrower(){
> > }
> > },
> > requestInterceptors: [],
> > responseInterceptors: []
> > };
> > ```
> > ## How To Reproduce
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > pnpm dlx create-umi@latest
> > 
> > * create-umi 4.0.12
> >   ✔ Pick Umi App Template › Simple App
> >   ✔ Pick Npm Client › pnpm
> >   ✔ Pick Npm Registry › taobao
> 
> > ## Context
> > 
> > * **Umi Version**:  "^4.0.12"
> > * **Node Version**: v14.17.5
> > * **Platform**: mac

Did you solve that problem?

**Comment by xhua007** [comment]
解决了吗？，我也遇到了同样的问题

**Comment by hanxzi** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zl802925** [comment]
> 
解决了，用simple app的模版，request的插件不会注册。要手动注册，建议拉下umi代码。代码里面的example中有request的例子

**Comment by zl802925** [comment]
> 解决了吗？，我也遇到了同样的问题

解决了，用simple app的模版，request的插件不会注册。要手动注册，建议拉下umi代码。代码里面的example中有request的例子

**Comment by mode365Dong** [comment]
楼上所说的可以参考我这个：https://github.com/umijs/umi/issues/8286#issuecomment-1653056872

**Comment by wangyungang29** [comment]
应该是umi 项目（非官方直接拉的案例）从头构建的时候部分插件未配置。增加一下在config.ts中 的配置 request: {},
  plugins: [
    "@umijs/plugins/dist/request"
  ],
