### ISSUE TITLE
支持 mpa

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#9018]
## 问题

有些场景不需要 spa，不需要路由和 history，只需要用 umi 作为单纯的构建工具。比如 sketch 插件、electron、chrome 插件、传统 h5 应用等。

## 方案

umi 支持 mpa。

1、内置支持 mpa，通过 `mpa: {}` 开启
2、不生成 umi.ts、core/routes.ts 等
3、修改 webpack entry 为 src/pages 下的所有带 index.ts 的一级目录（暂不做 watch 热更支持，增删 entry 时需手动重启 umi dev）
4、entry 的配置通过解析 entry 文件 export 的 const 属性获取

```
export const config = {
  title,
  mountElementId,
  layout,
  // 页头属性
  head,
  // 插入到 body 的脚本
  scripts,
}
```

5、通过 webpack 插件的方式为每个 entry 生成 html

**Comment by xierenyuan** [comment]
如果 在 index.ts 平级 或者  内部导出一个  `Document` 是不是以是一种选项比如

```tsx
// document.tsx
import { Meta, Title, Links, HeadScripts, Main, Scripts  } from 'umi';

function Document() {
  return (
     <html lang="en">
      <head>
        <Title />
        <Meta />
        <Links />
       <HeadScripts/>
      </head>
      <body>
        <Main />
        <Scripts />
      </body>
    </html>
  );
}
export default Document;
``` 

或者 index.tsx 中

```tsx
import { Meta, Title, Links, HeadScripts, Main, Scripts  } from 'umi';

export  function Document() {
  return (
     <html lang="en">
      <head>
        <Title />
        <Meta />
        <Links />
       <HeadScripts/>
      </head>
      <body>
        <Main />
        <Scripts />
      </body>
    </html>
  );
}
```

**Comment by sorrycc** [comment]
通过 jsx 声明 html 就需要走 ssr 渲染了，mpa 感觉没必要这么复杂。

**Comment by arvinxx** [comment]
可以给一个使用哪个 template 的配置？ 这样其实灵活性也有了。

**Comment by xierenyuan** [comment]
> 通过 jsx 声明 html 就需要走 ssr 渲染了，mpa 感觉没必要这么复杂。

只是处理模板 应该是把这个交给  `@umijs/server` 处理 就可以了, 或者是 `modifyHTML` 支持按 `entry` 定制  好像以可以解决问题

**Comment by poyiding** [comment]
需要给个mpa的模板的demo

**Comment by huarse** [comment]
mpa 应该不是不需要路由，而是不需要默认集成路由

比如一个工程承载了多个域的业务场景，每个场景有若干个子页面，这种情况下开发者可以使用 MPA，但是可以自己按需使用自己喜欢的路由方案

所以这个诉求可以分为两个点

```ts
export default defineConfig({
    // 表示默认不集成路由（用户甚至可以再去引老版本的路由方案）
    route: false,

    // 最后打包出来的主文件会是 aaaa.js、bbbb.js
    mpa: {
        aaaa: ['./src/pages/aaaa'],
        bbbb: ['./src/pages/bbbb'],
    }
})
```
