### ISSUE TITLE
支持 ie11 等传统浏览器

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#9019]
## 问题

有些场景需要这个。

## 方案

启动方式，

1、新增 `legacy: { buildOnly?: Boolean }` 配置
2、如果有 buildOnly，则只在 build 时开启，因为 dev 时全量编译 node_modules 会很慢

如果开启，

1、node_modules 走 babel 编译
2、~~render-* 和 client/client 改成 es5 格式~~，有前者之后，这个不需要，改了反而对非 legacy 场景有影响
3、强制切换 srcTranspiler 为 babel、jsMinifier 为 terser、cssMinifier 为 nano
4、svgr 改用 babel 解析 svg

其他，

1、支持使用 externals 的场景，之前有场景反馈是引入相关 babel polyfill 就可以了
2、补充相关文档

## 参考

https://github.com/umijs/umi/issues/8658
https://github.com/umijs/umi-next/pull/793

**Comment by ikonan** [comment]
## What happens?

### 开发模式下：
![image](https://user-images.githubusercontent.com/20334137/187020098-f94481b7-69a1-458c-b5ca-bf711a509d74.png)
### build 之后
![image](https://user-images.githubusercontent.com/20334137/187020254-2cd9647a-a96e-4323-a83f-04215441609a.png)

配置如下
```
export default {
  npmClient: 'pnpm',
  legacy: {
    buildOnly: false
  }
};
```
## Mini Showcase Repository(REQUIRED)
直接用umi4.0.15 初始化一个项目





## How To Reproduce
1.直接用umi4.0.15 初始化一个项目， 开启 `legacy:{buildOnly:false}`
2.在360浏览器兼容模式，选择IE11 控制台报错 SCRIPT5009: “Symbol”未定义
3.build 之后 用serve 做本地验证还是 ， 控制台报错 SCRIPT5022: 引发了异常但未捕获



## Context

- **Umi Version**:  4.0.15
- **Node Version**: 16.10.0
- **Platform**: windows
