### ISSUE TITLE
[Feature Request] support dynamicImport config

### ISSUE THREAD

**Issue by poyiding** [umijs/umi#9033]
## Background

umi 3.x 支持 dynamicImport 配置关闭和开启，在 umi 4.x 没有该配置，默认的是开启了dynamicImport

## Proposal

支持 dynamicImport 配置 开启和关闭

**Comment by fz6m** [comment]
See https://umijs.org/docs/introduce/faq#%E5%8F%AF%E4%BB%A5%E5%85%B3%E9%97%AD-dynamicimport-%E5%90%97

**Comment by poyiding** [comment]
thanks
