### ISSUE TITLE
[Bug] 约定式路由404页面build后无效

### ISSUE THREAD

**Issue by radeon8** [umijs/umi#9037]
## What happens?
```
|-pages
|--404.tsx
```
约定式路由404页面，本地调试访问404正常，build后线上访问不存在路由，页面空白

## Mini Showcase Repository(REQUIRED)
https://github.com/radeon8/umi

## How To Reproduce

**Steps to reproduce the behavior:** 
1. ```pnpm dev``` 访问 ```/404```正常
2. ```pnpm build```
3. ```pnpm preview``` 浏览器访问不存在路由如```/asdfasdf```,页面空白

**Expected behavior** 
1. 线上访问不存在路由，正常显示404

## Context

- **Umi Version**: 4.0.13
- **Node Version**: 16.11.0
- **Platform**: mac m1pro

**Comment by fz6m** [comment]
最新版本已经修复了，可升级到 `4.0.18`
