### ISSUE TITLE
[Bug]  使用ip访问devServer，mf-va_remoteEntry.js请求错误

### ISSUE THREAD

**Issue by Mr-SPM** [umijs/umi#9038]
局域网访问应用，但是mf-va_remoteEntry仍然请求的是localhost
![image](https://user-images.githubusercontent.com/25722226/185587063-b8f283d2-8f6b-4395-9ef8-e3c524b321a0.png)

![949a23a3af40e48712fe2e82f032293](https://user-images.githubusercontent.com/25722226/185587081-adf28adf-fec5-4e88-9903-36dc4eff40d4.jpg)

**Comment by fz6m** [comment]
可以尝试使用 `4.0.0-canary.20220819.1` 版本，已经修复了相关问题
