### ISSUE TITLE
使用 config.chainWebpack 中遇到的一些问题

### ISSUE THREAD

**Issue by Runtu4378** [umijs/umi#904]
## package version

umi: 2.0.0-beta.17

---

## 情况描述

在使用 umi 的时候遇到需要通过 html 的 `<script />` 标签引入静态资源并且配置 publicPath 的需求

在单独使用 webpack 配置时的配置是

```html
<!-- document.ejs -->
<title>editor</title>
  <script src="<%= htmlWebpackPlugin.options.PUBLIC_PATH%>pdfjs/pdf.js"></script>
</head>
```

```javascript
// webpack.config.js
...othercode
new HtmlWebpackPlugin({
    template: resolve(__dirname, './src/pages/document.ejs'),
   PUBLIC_PATH： ‘/web/dist/’,
})
```

或者是

```html
<!-- document.ejs -->
<title>editor</title>
</head>
```

```javascript
// webpack.config.js
...othercode
new HtmlWebpackPlugin({
    template: resolve(__dirname, './src/pages/document.ejs'),
}),
new HtmlWebpackIncludeAssetsPlugin({
    assets: ['pdfjs/pdf.js'],
    append: true,
    publicPath:  ‘/web/dist/’,
}),
```

在 umi 中，想通过上述思路实现需求可以利用 `config.chainWebpack ` 来实现 webpack plugin 的定制或修改，不过遇到以下两个问题

- 在 `.umirc.js` 中通过 `config.chainWebpack ` 获取到的 `config` 对象好像并不是最终的 webpack config （获取到的 config 中的 plugins 列表中没有处理 `src/pages/document.ejs` 的 `html-webpack-plugin`  但是 document.ejs 确实是被处理过的, 应该是有用到 html-webpack-plugin）
- 暂时获取不到 umi 通过 [webpack-chain](https://github.com/neutrinojs/webpack-chain) 所定义的插件的名称列表（通过名称列表来精粒度修改某个插件的配置, 如 config.plugin(某个插件名).tap(args => [...args, 自定义更新配置])

---

## 建议的解决方法

- umi 本身的配置已经很完善了，有时候可能只是需要在它的基础上改一小部分，可能会有一个文档专门陈列 umi 用到的配置（或者是指明保存在哪个项目下），这样可能也能解决容易发生的配置项冲突或者是重复定义
- 可能 umi 可以加一些生命周期之类的钩子？比如可以知道 .umirc.js 文件的配置项是在哪个阶段并入的，让用户可以在不同的生命周期传参或是进行自定的的其他NodeJS脚本操作

**Comment by sorrycc** [comment]
#1086 可以通过 chunks 解决这个问题，在 #1086 里继续跟进。
