### ISSUE TITLE
请问如何配置js压缩

### ISSUE THREAD

**Issue by lovesL** [umijs/umi#9048]
https://github.com/umijs/umi/issues/2909
那个文档的链接似乎失效了
按照官网配的不起作用
<img width="700" alt="image" src="https://user-images.githubusercontent.com/27960630/185918072-74babe48-af3f-48b5-a832-d722ba35810f.png">
## 下面是我的依赖
<img width="821" alt="image" src="https://user-images.githubusercontent.com/27960630/185918324-6a06f7f1-1ad3-428b-b203-ebc90657527f.png">

**Comment by PeachScript** [comment]
dumi 项目请参考 dumi 的文档：https://v3.umijs.org/config#terseroptions
dumi 项目使用 esbuild 压缩：https://v3.umijs.org/plugins/plugin-esbuild

dumi 基于 Umi 3.0，现在 Umi 官网的文档是 4.0 版本，没有参考意义
