### ISSUE TITLE
内置类型无法导出

### ISSUE THREAD

**Issue by strongyc** [umijs/umi#9052]
## What happens?

模块“"umi"”没有导出的成员“request”
![image](https://user-images.githubusercontent.com/51156342/185864678-ec0f8cdd-67f4-43f5-b1f3-c01521b06865.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
使用 request 需要安装 request 的插件：

```bash
  pnpm add @umijs/plugins
```

```ts
// .umirc.ts

export default {
  plugins: ['@umijs/plugins/dist/request'],
  request: {}
}
```

**Comment by strongyc** [comment]
> 使用 request 需要安装 request 的插件：
> 
> ```shell
>   pnpm add @umijs/plugins
> ```
> 
> ```ts
> // .umirc.ts
> 
> export default {
>   plugins: ['@umijs/plugins/dist/request'],
>   request: {}
> }
> ```

感谢
