### ISSUE TITLE
[Bug] layout的配置中关于rightContentRender显示在侧边栏

### ISSUE THREAD

**Issue by yangxiaoqiao2016** [umijs/umi#9060]
## What happens?
layout的配置中关于rightContentRender显示在侧边栏

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://github.com/yangxiaoqiao2016/umi4-cli)，并上传到你的 GitHub 仓库
[最小重现](https://github.com/yangxiaoqiao2016/umi4-cli)

app.tsx的配置如下
```typescript
export const layout = () => {
  return {
    logo: 'https://img.alicdn.com/tfs/TB1YHEpwUT1gK0jSZFhXXaAtVXa-28-27.svg',
    menu: {
      locale: false,
    },
    menuExtraRender: () => <span>menuExtraRender</span>,
    rightContentRender: () => <span>rightContentRender</span>,
    menuFooterRender: () => <span>menuFooterRender</span>,
    footerRender: () => <span>footerRender</span>,
    // headerRender: () => <span>headerRender</span>,
    headerContentRender: () => <span>headerContentRender</span>,
  };
};
```

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/20087598/185903293-91a5615a-171b-485b-ab89-6e6b9731e841.png">
想要的效果：
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/20087598/185904349-16662aab-9882-45ee-bd29-8835ee50ee2c.png">

经查验@umijs/plugins会把@ant-design/pro-layout下载到next tag的版本与本身@ant-design/pro-components的pro-layout冲突
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/20087598/185904750-b3d29c73-4eb6-48ef-ab78-d5220537f89f.png">

<img width="894" alt="image" src="https://user-images.githubusercontent.com/20087598/185905072-cc16b8d0-18d6-43ee-a2aa-bcfb09f523e7.png">

## Context

- **Umi Version**:  4.0.13
- **Node Version**:  16.17.0
- **Platform**: macos

**Comment by drizzlesconsin** [comment]
```ts
layout: 'mix',
splitMenus: true,
```
这样配置才能在右边

**Comment by yangxiaoqiao2016** [comment]
layout: 'side',的模式，整个headerRender不渲染。是bug吧？虽然你说的配置确实能在右边。但是解决不了layout: 'side'模式下是有问题的

**Comment by yangxiaoqiao2016** [comment]
> ```ts
> layout: 'mix',
> splitMenus: true,
> ```
> 
> 这样配置才能在右边

layout: 'side',的模式，整个headerRender不渲染。是bug吧？虽然你说的配置确实能在右边。但是解决不了layout: 'side'模式下是有问题的。而且为什么安装到beta版本的layout？umi4现在还不能用于生产环境吗？
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/20087598/185911193-de304007-bfa1-4142-8c9e-0dbecc5862c3.png">

**Comment by lyndonliu89757** [comment]
umi本身很好了，耐何插件的bug太多，集成也经常出问题，感觉layout自己写更靠谱，不然后面一更新又不知哪冒出个bug。

**Comment by yangxiaoqiao2016** [comment]
是@ant-design/pro-layout@7.0.1-beta.29 版本的API变动问题
https://github.com/ant-design/pro-components/discussions/4945
> rightContentRender修改为 avatarProps 和 actionsRender, 对头像模式做了默认抽象。
layout=sider 模式下，header 消失，只保留了侧边栏，增大可视面积。
layout=sider 模式下，header 消失后，右侧操作区域修改为左下角。

**Comment by yangxiaoqiao2016** [comment]
pnpm add @ant-design/pro-layout  可以解决umi plugin用的是beta版本的pro-layout，只要项目根目录安装了这个包，就用项目根目录安装的这个包
