### ISSUE TITLE
[Bug] The priority of the config files is not in right sequence during umi build.

### ISSUE THREAD

**Issue by BH-M87** [umijs/umi#9066]
## What happens?

配置文件的优先级顺序不对。`config.prod.ts`的优先级高于任何其它config文件，即使已经指定了`UMI_ENV=xxx`。这样导致，在执行打包命令的时候，环境配置无法生效。

## Mini Showcase Repository(REQUIRED)

[git@github.com:BH-M87/umi4-bug-showcase.git](https://github.com/BH-M87/umi4-bug-showcase)

## How To Reproduce

1.  config目录下存在三个配置文件，分别是：`config.new.ts`,  `config.prod.ts`, `config.ts`.
2. 执行打包命令：`UMI_ENV=new umi build`
3. prod文件里的配置优先级一直是最高的，如果删除掉prod文件，那么会读取到正确的new文件中的配置。

## Context

- **Umi Version**: 4.0.13
- **Node Version**: 16.14.2
- **Platform**:  macOS

**Comment by BH-M87** [comment]
`config.prod.ts` & `config.production.ts` 会有一样的问题

**Comment by fz6m** [comment]
See https://github.com/umijs/umi/discussions/8341#discussioncomment-3062844

**Comment by BH-M87** [comment]
> See [#8341 (comment)](https://github.com/umijs/umi/discussions/8341#discussioncomment-3062844)

这个合并顺序和umi@3有所不同了。

另外，明确指定了环境变量的配置文件，优先级应该高于默认的配置文件，包括config.ts, config.dev.ts或者config.prod.ts，我认为合理的顺序应该是：
- config.ts
- config.${dev | prod}.ts
- config.${UMI_ENV}.ts
- config.${dev | prod}.${UMI_ENV}.ts
- config.local.ts

或者，其实只要考虑4个配置就可以：
- config.ts
- config.${dev | prod}.ts
- config.${UMI_ENV}.ts
- config.local.ts

毕竟，- config.${dev | prod}.${UMI_ENV}.ts 这个写法官方文档并没有，算一个彩蛋了，而且也增加了理解成本。

**Comment by sorrycc** [comment]
绕一下吧。

Action：

1、增加相关文档
2、新增规则，让 UMI_ENV 不允许设置 dev、prod、test 等值

**Comment by BH-M87** [comment]
2、新增规则，让 UMI_ENV 不允许设置 dev、prod、test 等值

这个不能解决问题的啊。

因为现在的问题不是这个：
指定了UMI_ENV=new，但是这个不会生效的，因为prod的配置会覆盖掉所有设置UMI_ENV的情况啊。

@sorrycc

**Comment by sorrycc** [comment]
细想了下两种方式，感觉都没啥问题。于 Umi 3 是 break change，但 Umi 4 已经上了，就不改了，不能在非 major 上加 break change。建议调整组织方式，在 .dev 或 .prod 下引用之前 .new 的配置。

**Comment by BH-M87** [comment]
@sorrycc 恩，了解了原因之后已经绕过去了。

其实产生这个配置的原因是因为有一个默认的打包配置，占用了prod，然后别的打包配置，就有新的UMI_ENV配置了。
