### ISSUE TITLE
[Bug] max request 插件配置 dataField: '' 后，动态类型没有相应变化

### ISSUE THREAD

**Issue by tolerance-go** [umijs/umi#9074]
## What happens?

.umirc.ts

```
request: {
    dataField: ''
  },
```

好像是因为这里的类型写死了

https://github.com/umijs/umi/blob/master/packages/plugins/src/request.ts#L66

我现在的需求是这样的 希望静态类型上 useRequest 返回的 run 可以执行并返回原始请求返回值

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: latest
- **Node Version**: 16.16
- **Platform**: macOS

**Comment by xiaorong61** [comment]
你好，我也遇到这个问题了，你如何解决的

**Comment by lhzbxx** [comment]
这个问题怎么 Close 了，很影响体验啊，要解决的话只能再安装 ahooks 依赖。

**Comment by tolerance-go** [comment]
@xiaorong61 我换 nextjs 了=。= @lhzbxx 你可以重新 open 一个 issue 跟踪一下吧

**Comment by wanglianjie91** [comment]
同样遇到这个问题 ，  不知道umi-request一定要返回res.data这种画蛇添足的行为是什么意义。
