### ISSUE TITLE
[Feature Request] GET 请求的参数处理与 Umi3 保持一致

### ISSUE THREAD

**Issue by drizzlesconsin** [umijs/umi#9086]
## What happens?

```ts
// Umi3
import { useRequest } from 'umi'

GET params: { a: [1, 2, 3] }

url=?a=1&a=2&a=3

expect(querystring.stringify(ctx.req.options.data)).toBe('a=1&b=1&b=2&b=3&b=4');
```

```ts
// Umi4
import { useRequest } from '@umijs/max';

GET params: { a: [1, 2, 3] }

url=?a[]=1&a[]=2&a[]=3
```

GET 请求的参数处理，是否可以考虑与 Umi3 保持一致。
不然升级起来也是个坑

## Mini Showcase Repository(REQUIRED)

https://github.com/umijs/umi-request/blob/6773ef1104d46417b14562072167edc0f54822d7/test/middleware/simplePost.test.js#L29

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0.x
- **Node Version**: last
- **Platform**:

**Comment by ALongLi** [comment]
axios配置自己转换吧，用的也是axios

**Comment by hmilin** [comment]
```
export const request: RequestConfig = {
  // params格式化规则
  paramsSerializer: (params) =>
    new URLSearchParams(pickBy(params, negate(isNil))).toString(),
  ...
}
```
