### ISSUE TITLE
[Bug] 使用cross-env UMI_ENV=XX max build打包时 .umirc.prod.ts 会覆盖其它环境配置

### ISSUE THREAD

**Issue by gbyuxia** [umijs/umi#9089]
## What happens?
.umirc.prod.ts存在时 会在执行build-sit 时覆盖了.umirc.sit.ts里的process.env.UMI_ENV值

我在package.json中script里定义了
 "start-sit": "cross-env UMI_ENV=sit max dev",
    "start-uat": "cross-env UMI_ENV=uat max dev",
    "build-sit": "cross-env UMI_ENV=sit max build",
    "build-uat": "cross-env UMI_ENV=uat max build",
    "build-prod": "cross-env UMI_ENV=prod max build",
根目录下分别有.umirc.sit.ts、.umirc.uat.ts、.umirc.prod.ts，里面分别   
define: {
    'process.env.UMI_ENV': 'sit'  //（ 'uat'/'prod'）
  },
当执行start时所有环境都很正常；
但执行build-sit 或build-uat 时，在src目录下的app.ts里直接打印process.env.UMI_ENV 显示都是prod而不是期望的sit或uat；但如果先取env 再取env.UMI_ENV 就可以正确取到sit或uat 如下：
const env = process.env;
const UMI_ENV = env.UMI_ENV;  
console.log('UMI_ENV',UMI_ENV) //UMI_ENV sit   //如果运行build-uat则是UMI_ENV uat
console.log('process.env.UMI_ENV',process.env.UMI_ENV)    //process.env.UMI_ENV prod——就是这个”prod“不符合预期，也许不是bug，但我很疑惑，如果有人能帮忙解释一下原理不胜感激。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: "@umijs/max": "^4.0.2",
- **Node Version**:v16.11.1
- **Platform**:Windows 64

**Comment by fz6m** [comment]
See https://umijs.org/docs/guides/env-variables#umi_env

**Comment by bowencool** [comment]
+1
建议你重新提一个Issue
