### ISSUE TITLE
umi4的request的responseInterceptors无法拦截到非200响应

### ISSUE THREAD

**Issue by darkfiredarkhalo** [umijs/umi#9094]
### Discussed in https://github.com/umijs/umi/discussions/9093

<div type='discussions-op-text'>

<sup>Originally posted by **darkfiredarkhalo** August 25, 2022</sup>
## What happens?

非常感谢!   
后端使用`go zero`框架, 前端使用`antd pro`, 在处理请求时使用`@umijs/max`的`request`,发送请求时参数只有`url`/`method`/`data`, 然后在`app.ts`中做运行时配置, 如下:  
```
export const request: RequestConfig = {
  timeout: 8000,
  // 不起作用, 在requestInterceptors中依据环境修改url可以达到同等效果
  // prefix: serverUrl[ApiEnv?.env || 'production'],
  errorConfig: {
    errorThrower: (res: any) => {
      console.log('拦截错误>>>', res);
    },
    errorHandler: (error: any, opts: any) => {
      if (opts?.skipErrorHandler) throw error;
      console.log('处理错误>>>', { error, opts });
      const { response } = error;
      if (response && !response.data) {
        setLocalStorage(storageKey.userInfo, '');
        setLocalStorage(storageKey.token, '');
        history.push(loginPath);
      }
    },
  },
  // @ts-ignore
  requestInterceptors: [requestHandler],
  // @ts-ignore
  responseInterceptors: [
    responseHandler,
    (error: any) => {
      console.log('response error', error);
      return Promise.reject(error);
    },
  ],
};
```  
发现如下几个问题:  
- 非200请求进不到响应拦截器`responseInterceptors`, 也进不到`responseInterceptors`的错误处理; 正常的200请求,`responseInterceptors`中的错误处理也能接收到, 如果按官方示例, 此时的正常请求也无法处理, 因为在错误处理中返回了`reject`  
- `errorConfig`中的`errorHandler`拿不到http`status`.  非200会直接进入`errorHandler`, 但是此时的响应体内`status`始终是`0`, 如下图:  

![20220825-101521](https://user-images.githubusercontent.com/13959162/186559291-fc968075-feb4-432c-bb7e-b18655d9a91f.jpg)

## Mini Showcase Repository(REQUIRED)
- 新建`ant design pro`项目: `npx @ant-design/pro-cli create myapp`, 选择`umi4`模板;  
- `app.ts`添加运行时配置如下:
```
export const request: RequestConfig = {
  timeout: 8000,
  // 不起作用, 在requestInterceptors中依据环境修改url可以达到同等效果
  // prefix: serverUrl[ApiEnv?.env || 'production'],
  errorConfig: {
    errorThrower: (res: any) => {
      console.log('拦截错误>>>', res);
    },
    errorHandler: (error: any, opts: any) => {
      if (opts?.skipErrorHandler) throw error;
      console.log('处理错误>>>', { error, opts });
    },
  },
  requestInterceptors: [(url: string, options: any)=>{
console.log("拦截请求>>", {url, options})
return {url, options}
}],
  responseInterceptors: [
    (response: any) => {
console.log("拦截响应>>", response);
return response
},
    (error: any) => {
      console.log('response error', error);
      return Promise.reject(error);
    },
  ],
};
```    
- 发起非200响应的请求, 如`401`等

## Context

- **Umi Version**: 4.0.9
- **Node Version**: 16.16.0
- **Platform**: windows 11</div>

**Comment by YdreamW** [comment]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/43460525/186564847-98c86083-e4ac-4fee-a069-292e26c5ad3a.png">

参考  https://axios-http.com/docs/req_config

request 插件基于 axios，config 配一下 `validateStatus` 就好了。可以配置哪些 status 进 catch 哪些进 then

**Comment by darkfiredarkhalo** [comment]
> 

@YdreamW 这个配置了也不行, `umi`的处理优先于`axios`, 如下图:  
![飞书20220825-130328](https://user-images.githubusercontent.com/13959162/186579163-4767097c-c893-4c4f-b248-3118eec89bd7.jpg)

**Comment by YdreamW** [comment]
按照描述没有复现
<img width="507" alt="image" src="https://user-images.githubusercontent.com/43460525/186806265-0b924c87-628d-4897-9821-c0775d7399b0.png">
umi 是不会做这种拦截的。如果可以的话提供一个完整的最小复现仓库。

**Comment by darkfiredarkhalo** [comment]
不好意思, 是后端接口的问题, 后端用了`go zero`框架, 在配置了统一的跨域处理后, 在遇到`401`请求时, 跳过了跨域.... 所以如果请求报`401`, 前端就直接跨域了... 所以根本拿不到响应, 抱歉抱歉!

**Comment by hejinguo** [comment]
umi4  request的prefix 不起作用？  @darkfiredarkhalo

**Comment by YdreamW** [comment]
> 

umi4 request 改用了 axios 作为请求库，prefix 是 umi-request 的配置项，axios 没有该配置项

**Comment by kaisawind** [comment]
> umi4 request的prefix 不起作用？ @darkfiredarkhalo

prefix -> baseURL
