### ISSUE TITLE
How to config the route that requires authority?

### ISSUE THREAD

**Issue by HeskeyBaozi** [umijs/umi#91]
I used the ant-design-pro component [AuthorizedRoute](https://pro.ant.design/components/Authorized#Authorized.AuthorizedRoute) in a roadhog based project.

I am wondering how to migrate these codes into umi preferred codes. thanks!
https://github.com/ant-design/ant-design-pro/blob/9c4e9c1b39ceacd9e0efdb666d4b6d1663b0daf6/src/router.js#L22-L35

————
我在一个roadhog项目中使用了[AuthorizedRoute](https://pro.ant.design/components/Authorized#Authorized.AuthorizedRoute)这个ant-design-pro组件，但是怎Umi文档中无论是约定还是配置都没有详细的说明，有权限的路由应该怎么处理？想知道怎么无痛迁移这一类型的代码？谢谢大大

**Comment by sorrycc** [comment]
感觉可以在 page component 里做权限判断？AuthorizedRoute 需要改造下，不用判断基于 route，直接判断权限就好。
