### ISSUE TITLE
[Bug] 初始化的项目，一堆ts报错

### ISSUE THREAD

**Issue by taoliujun** [umijs/umi#9108]
2022-08-26，参照：https://umijs.org/docs/tutorials/getting-started，使用pnpm或yarn方式安装umi4，然后执行`yarn tsc -p ./tsconfig.json --noEmit`，得到一堆ts报错。
![image](https://user-images.githubusercontent.com/5689134/186803354-c06e27b5-6008-4684-b1c4-1cd239be4f9d.png)

随便检查一个错误，比如：`node_modules/@umijs/bundler-webpack/compiled/http-proxy-middleware/dist/index.d.ts`，根本不存在`./handlers`目录。源码在此：https://github.com/umijs/umi/blob/master/packages/bundler-webpack/compiled/http-proxy-middleware/dist/index.d.ts

**Comment by fz6m** [comment]
tsconfig 需要排除掉 node_modules 或者指定 includes src 。

**Comment by xiaorong61** [comment]
```
  forkTSChecker: {},
```

umirc 开这个选项来类型检查 ts 吧

**Comment by LaughingZhu** [comment]
> ```
>   forkTSChecker: {},
> ```
> 
> umirc 开这个选项来类型检查 ts 吧

这个好像和 tsc 的规则不一样
