### ISSUE TITLE
[BUG] MFSU 不支持 worker

### ISSUE THREAD

**Issue by stormslowly** [umijs/umi#9116]

**Comment by ShinChven** [comment]
mfsu 连 ssr 都不兼容

**Comment by stormslowly** [comment]
> mfsu 连 ssr 都不兼容

有复现的 case 吗？

**Comment by ShinChven** [comment]
umi3 建个工程同时配置 ssr:{} 和 mfsu:{} 启动就挂。

**Comment by ShinChven** [comment]
https://github.com/ShinChven/Umijs3-SSR-with-MFSU-Crush-Example/commit/da4c3f422ae7adab02a3f476ea209f02a0e3c3ff

**Comment by stormslowly** [comment]
sorry for late response
1. mfsu 的机制天然不支持 worker，mf 模块共享是通过 window 来实现的，但是worker 中没有 window
2. Umi3 目前低频维护，如果使用中 ssr 和 mfsu 冲突，建议关闭 mfsu `mfsu: false`
