### ISSUE TITLE
你知道吗

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#9132]
## 为什么做

Umi 做了很多功能，很多开发者并不知道，需要找机会曝光下。比如 `/__umi` 路由，比如本地调试 umi.js 产物的方法，比如 clientLoader 功能，比如 Low Import，比如微生成器，等等。

## 计划

* [x] 梳理第一批「你知道吗」x 10 20m
* [ ] 征集更多「你知道吗」，通过 PR 的方式
* [x] 完成 @umijs/did-you-know 插件 2h https://github.com/umijs/did-you-know/pull/1
* [x] 完成 umi 4 接入 30m https://github.com/umijs/umi/pull/9147
* [x] 完成 umi 3 接入 30m https://github.com/umijs/umi/pull/9149

## 方案

* 提供 @umijs/did-you-know 包，放 umijs org 下，单独维护和发包，属于保存在 package.json 的 didYouKnow 字段里，格式为 `{ text: string, url?: string, majorVersion?: number, framework?: string[] }[]`

```
"didYouKnow": [
  { "text": "", url: "", majorVersion: 4, framework: ['umi', '@umijs/max'] },
  { "text": "" },
]
```

* @umijs/did-you-know 包提供两个脚本，1）校验 package.json 和字段的合法性，PR 和发布时执行，2）发布脚本，自动 bump bugfix version
* @umijs/did-you-know 还需提供 umi 插件，在插件注册阶段打印 「did you know」日志，兼容 umi 3 和 4

目录结构，

```
+ src
  - plugin.ts
+ scripts
  - release.ts
  - check.ts
- package.json
```

核心代码，

```ts
import data from '../package.json';
export default (api) => {
  const isUmi3 = !!api.utils;
  const isUmi4 = !api.utils;
  const logger = isUmi3 ? api.utils.logger : require('umi/plugin-utils').logger;
  
  const item = getDidYouKnow(data.didYouKnow, framework, majorVersion);
  assert(item, ``);
  const { text, url } = item;
  const info = [
    `[DidYouKnow]`,
    `${text}${url ? ',' : ''}`,
    url && `More on ${url}`,
  ].filter(Boolean);
  logger.info(info.join(' ') + '。');

  function getDidYouKnow(items, framwork, majorVersion) {
    // 1、get matched
    // 2、matched.length ? random : null
  }
}
```

效果见，

```
[DidYouKnow] dev 模式下访问 /__umi 路由，可以发现很多有用的内部信息。
```

* umi 3 和 4 分别内置这个插件。

### 第一批「Did You Know」

* dev 模式下访问 /\_\_umi 路由，可以发现很多有用的内部信息
	* majorVersion: 4
* father 4 正式发布了
	* url: https://zhuanlan.zhihu.com/p/558192063
* @umijs/max 是蚂蚁内网框架 Bigfish 的对外版本
* Umi 3 的 MFSU 可能会遇到奇怪的问题，升级到 Umi 4 后就没了
	* majorVersion: 3
* 如果要支持低版本浏览器，可尝试新出的 legacy 配置项
	* url: https://umijs.org/docs/api/config#legacy
	* majorVersion: 4
* 如果想点击组件跳转至编辑器源码位置，可尝试新出的 clickToComponent 配置项
	* url: https://umijs.org/docs/api/config#clicktocomponent
	* majorVersion: 4
* 如果想检测未使用的文件和导出，可尝试新出的 deadCode 配置项
	* url: https://umijs.org/docs/api/config#deadcode
	* majorVersion: 4
* 默认使用 esbuild 作为 JavaScript 压缩工具，也可通过 jsMinifier 配置项切换到 terser 或 uglifyJs 等
	* url: https://umijs.org/docs/api/config#jsminifier-webpack
	* majorVersion: 4
* %%framework%% g tsconfig 可一键完成项目的 TypeScript 配置
	* majorVersion: 4
* 如果你有 MPA（多页应用）需求，可尝试新出的 mpa 配置项
	* url: https://umijs.org/docs/guides/mpa
	* majorVersion: 4

## 参考

* https://github.com/umijs/did-you-know

**Comment by drizzlesconsin** [comment]
借楼

deadCode  `exclude` 似乎是无效的，配置了还是会提示该目录下的文件. https://github.com/umijs/umi/blob/master/packages/bundler-webpack/src/config/detectDeadCode.ts#L29-L37
```ts
deadCode: {
  exclude: ['**/mock/**', 'mock/x.ts', '**/mock/**/*.*', 'x.ts'],
  failOnHint: true,
},
```

**Comment by sogud** [comment]
如何关闭此功能？

**Comment by calefy-chen** [comment]
你知道吗，即使到了umi4，涉及umi包的单元测试还是不能做。。。

**Comment by zjfresh** [comment]
> 如何关闭此功能？

[v4.0.20](https://umijs.org/docs/guides/env-variables#did_you_know)  process.env.DID_YOU_KNOW=none

**Comment by sogud** [comment]
可以把文档写的更完善一点
