### ISSUE TITLE
[Bug]  RangeError: Wrong length!

### ISSUE THREAD

**Issue by Pszz** [umijs/umi#9134]
Runtime errors！！！

## What happens?
<img width="1731" alt="image" src="https://user-images.githubusercontent.com/12093551/187123066-c39a548b-5f64-41f5-8bca-1aaf40396c82.png">

## Mini Showcase Repository(REQUIRED)
[https://github.com/Pszz/umijs-run-error](https://github.com/Pszz/umijs-run-error)

## How To Reproduce
 - `yarn install`
 - `yarn start`

## Context

- **Umi Version**:  v4.0.6
- **Node Version**: v16.16.0

## 期望
- 错误提示有没有办法具像化一些，根据错误栈比较难以追踪。

**Comment by fz6m** [comment]
老哥，`hellojs` 这个包目前只支持 [cjs](https://github.com/MrSwitch/hello.js#npm) 的用法：

![screenshot_2022-08-29_12-55-12](https://user-images.githubusercontent.com/59400654/187125844-391d2a02-58b4-425b-9d3e-a4fa5d0df83f.png)

```ts
const hello = require('hellojs/dist/hello.all.js')

// ...

hello.init()
```

他这个包 [官方推荐的用法](https://github.com/MrSwitch/hello.js#2-include-hellojs-script-in-your-page) 是通过 script 放到全局去再调 `window.hello` 的。

**Comment by Pszz** [comment]
> 
这样吗，我试试看，之前好像没问题。
我在_layout.tsx 里面加入了Web3的引入和使用就报错。

注释掉
import Web3 from 'web3';
以及下面的使用，貌似也可以。。。

**Comment by fz6m** [comment]
### 别人引入使用好久，貌似没报错，也用了一段时间，我引入和使用就报错

可能和顺序有关。

```ts
// 🔴
import hello from 'hellojs'
import Web3 from 'web3';

// 🟢
import Web3 from 'web3';
import hello from 'hellojs'

// 🟢
const hello = require('hellojs/dist/hello.all.js')
import Web3 from 'web3';
```

hellojs 产物只有 cjs 的（官方也推荐用 cjs require 或者 script 引入）。

怎么和 web3 冲突的我也不知道，但是 hellojs 这个包下载量也不多，你可以自己研究下。

### 这类错误是如何定位问题的

关闭 `mfsu: false` 后排查出来是 hellojs 的问题：

![screenshot_2022-08-29_16-02-56](https://user-images.githubusercontent.com/59400654/187153813-b8610553-c8d3-4c34-b5a2-6065504d0140.png)

**Comment by Pszz** [comment]
感谢～
