### ISSUE TITLE
[Bug] 4.0.15 PublicPath调整之后打包的script、link地址不对

### ISSUE THREAD

**Issue by wulibaibao** [umijs/umi#9135]
4.0.15改动PbulicPath打包后地址不对！感觉是升级后带来的问题呀
![image](https://user-images.githubusercontent.com/22147011/187128412-cc6bd672-3560-4434-a6b1-56d2f6f0e317.png)
![image](https://user-images.githubusercontent.com/22147011/187128437-1c1ef382-cffb-42c6-97f7-83dc7aaf925b.png)
![image](https://user-images.githubusercontent.com/22147011/187128495-34ed20a8-d7df-4d5f-869b-337c343fa1c9.png)

**Comment by fz6m** [comment]
```ts
// .umirc.ts

const isProd = process.env.NODE_ENV === 'production';
const PREFIX = `/prefix`
const CDN_PREFIX = `https://cdn.domain.com` // or //cdn.domain.com

export default {
  publicPath: isProd ? `${CDN_PREFIX}/` : `${PREFIX}/`
};
```

**Comment by wulibaibao** [comment]
> 
我项目比较特殊CDN地址我并不知道，只能拿字符串去替换，字符串前面必须加个/或者是http(|s)是有点麻烦
