### ISSUE TITLE
[Bug] 修改config文件中publicPath打包路径不对

### ISSUE THREAD

**Issue by wulibaibao** [umijs/umi#9140]
## What happens?

umi4.0.15
config文件修改直接改publicPath，dist/index.html内css\js打包到了标签里面

## Mini Showcase Repository(REQUIRED)

![image](https://user-images.githubusercontent.com/22147011/187140451-39d0dc12-ae90-4a50-926c-74e9f47218b2.png)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

新建Umi4.0.15项目，config.ts中增加publicPath: "REPLACE_STRING/",

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by charcoal-zt** [comment]
publicPath: `/REPLACE_STRING/`  改成这个试试
