### ISSUE TITLE
[Bug] 使用mfsu报错js文件中不支持使用JSX语法

### ISSUE THREAD

**Issue by GrinZero** [umijs/umi#9161]
## What happens?

babel配置了允许在js中直接写JSX语法的情况下，使用mfsu会报错js文件中不支持使用JSX语法

## How To Reproduce

1. 任意一个配置了`@babel/preset-react`来在Js中编写JSX语法的React-webpack5项目
2. 按照官网指示接入mfsu
3. 不管是通过babel接入还是esbuild接入都会报错

## Context

- **@umijs/mfsu**: "^4.0.15",
- **Node Version**: 16.x
- **Platform**: MAC

**Comment by yuanliu147** [comment]
请问，楼主解决了吗，我也遇到类似问题了
