### ISSUE TITLE
[Bug] Umi4 的 .umirc.ts  defineConfig 在 VSCode 中  没有智能提示.

### ISSUE THREAD

**Issue by fz6m** [umijs/umi#9170]
## Bug 描述 （ From Discussed in https://github.com/umijs/umi/discussions/9167 ）

<div type='discussions-op-text'>

<sup>Originally posted by **xxxxue** August 30, 2022</sup>
[官网文档](https://umijs.org/docs/guides/typescript)
`.umirc.ts`  的 `defineConfig`  在 VSCode 中 没有智能提示.  (在 Jetbrains IDE 中是有的)

手动导出两个类型, 有智能提示了

具体情况如下图:

![image](https://user-images.githubusercontent.com/32764266/187423799-7a7429cd-281c-46df-8afc-e2ab8fed6500.png)

- **Umi Version**: v4.0.15
- **Node Version**: v16.14.2
- **Platform**: Windows 11
- **VSCode**: v1.70.0

补充说明:
pnpm 需要在  `.npmrc` 中配置 `public-hoist-pattern[]="@umijs/preset-umi"`</div>

## 问题

```ts
// umi/dist/defineConfig.d.ts

import { IConfigFromPlugins } from '@@/core/pluginConfig';
import type { IConfig } from '@umijs/preset-umi';
declare type ConfigType = IConfigFromPlugins & IConfig;
export declare function defineConfig(config: ConfigType): ConfigType;
export {};
```

vscode 不支持识别 `node_modules` 中的 alias ：`import { IConfigFromPlugins } from '@@/core/pluginConfig';`

## 可能的解决方案

`IConfigFromPlugins` 生成效果并不是很好，`object` 类型一律产出 `any` ，建议删除 `IConfigFromPlugins` ，只保留 `IConfig` 。

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/188346148-25fac56a-689c-4102-b74b-e50c51ccb508.png)
我的是正常的

**Comment by Jeepeng** [comment]
@xiaohuoni 
`.umirc.ts` 不行
`config/config.ts` 可以

**Comment by xiaohuoni** [comment]
@Jeepeng 因为.开头的默认不会被 include ，我来加一下。
