### ISSUE TITLE
[Bug] Umi4 中没有从 @umijs/max 中导出 setLocale 吗？ 

### ISSUE THREAD

**Issue by myadmin** [umijs/umi#9174]
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:
![image](https://user-images.githubusercontent.com/6794499/187603709-5561a921-b680-4aec-af54-8fcb68bdc704.png)
直接从 umi3 升级到 umi4，使用的是 @umijs/max，之前是直接从 umi 中导出，现在文档中显示也是从 umi 中导出，但是从3升级到4以后，umi已经被删除了，那么 setLocale 该从哪导出呢？

**Comment by fz6m** [comment]
导出了，确认一下你的 i18n 配置是否开启：

```ts
// .umirc.ts

export default {
  locale: {}
}
```

再 cmd/ctrl + shift + p 调出控制台 reload 下 vscode 看看。
