### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by txp1035** [umijs/umi#9185]
## 背景

可以在官网看到历史版本。[例子](https://tr.imtxp.cn/version/version)
因为正好是文档，changelog可以直接生成到docs里作为文档使用。

## 实现方案

conventional-changelog 生成日志
可以自定义模板

**Comment by sorrycc** [comment]
Umi Changelog 方案

1、基于 https://github.com/unjs/changelogen  
2、生成和 Umi 现有 release note 相似的 markdown 格式，参考 https://github.com/umijs/umi/releases/tag/v4.0.16  
3、按 feat、fix 做排序，删除 chore 和 docs 的改动  
3、和 release.ts 脚本结合，发布完成后打开 Github 的 Release 页面，自动包含相关内容

**Comment by txp1035** [comment]
![Uploading image.png…]()
这个接口直接生成的changelog，逻辑处理在服务器端，不够灵活
