### ISSUE TITLE
[Feature Request] 支持监听文件修改路径的参数

### ISSUE THREAD

**Issue by tolerance-go** [umijs/umi#9187]
## Background

pnpm 的多包项目，修改包里面的内容，umi 不会自动热更新

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by tolerance-go** [comment]
extraBabelIncludes 好像也不行

**Comment by fz6m** [comment]
给一个复现看看。monorepo 项目使用 [`monorepoRedirect`](https://umijs.org/docs/api/config#monoreporedirect) 可以支持热更新。

**Comment by tolerance-go** [comment]
@fz6m 文档看的不仔细，可以了，谢谢

**Comment by buquan** [comment]
> 给一个复现看看。monorepo 项目使用 [`monorepoRedirect`](https://umijs.org/docs/api/config#monoreporedirect) 可以支持热更新。

请问这是哪个版本支持的，umi3.0配置  monorepoRedirect: {},报错
`
ifss-supervision-front:start: Invalid config key: monorepoRedirect
ifss-supervision-front:start:  info  如果你需要进交流群，请访问 https://fb.umijs.org
ifss-supervision-front:start: Error: Invalid config key: monorepoRedirect
ifss-supervision-front:start:     at Config.getConfig (/Users/buquan/Desktop/githubs/ifss/node_modules/.pnpm/@umijs+core@3.5.36/node_modules/@umijs/core/lib/Config/Config.js:183:13)
`

**Comment by fz6m** [comment]
umi 4 支持 `monorepoRedirect` ，umi 3 不支持这个选项。
