### ISSUE TITLE
umi-plugin-dva情况下，如何配置404.js

### ISSUE THREAD

**Issue by jiahangLee** [umijs/umi#919]
"antd": "^3.8.1",
    "dva": "^2.4.0",
    "mockjs": "^1.0.1-beta3",
    "react": "latest",
    "umi": "^1.0.0",
    "umi-plugin-dva": "^0.7.1"

**Comment by xiaohuoni** [comment]
不知道你指定如何配置，是指什么？404 是默认开启的，在开发环境下，可以使用/404，查看404.js的效果。发布环境下，app的fallback就是404.js的效果。

**Comment by jiahangLee** [comment]
你好，我的项目不是直接使用umi来构建的，dav2.4➕umi1.0下使用后发现开发模式下一切正常，部署到测试环境后，404.js无效，以前有人回答我说把所有路由指向生成的html，可是理由是自动生成的，我不想手写理由，不知道有没有说清

**Comment by xiaohuoni** [comment]
1.0好像存在404页面的问题，忘记是哪个版本了。
你可以参考 https://github.com/umijs/umi-examples/tree/master/routes尝试修复。
如果还不行，就只能更新umi版本了。
