### ISSUE TITLE
umi4 qiankun 微应用使用useModel通信，报dispatcher找不到的错误

### ISSUE THREAD

**Issue by lbyupup** [umijs/umi#9192]
### Discussed in https://github.com/umijs/umi/discussions/9191

<div type='discussions-op-text'>

<sup>Originally posted by **lbyupup** September  1, 2022</sup>
"@umijs/plugins": "^4.0.15",
"@umijs/max": "^4.0.0",
"@umijs/plugin-qiankun": "^2.24.1",
我在微应用中使用useModel，内部源码报错，求助下大佬
```ts
import { useModel } from 'umi';
const { data } = useModel('@@qiankunStateFromMaster') ?? {};
```
报错如下
![image](https://user-images.githubusercontent.com/72724939/187852448-633ea4cb-40f6-4873-a0eb-f5d27a8615bf.png)
</div>

**Comment by cl1107** [comment]
你乾坤插件也应该要用 umi4的吧， @umijs/plugins下面就有 qiankun插件，@umijs/max 都安装了那已经自带乾坤插件了，不需要@umijs/plugin-qiankun 了， umi +  @umijs/plugins  差不多就是@umijs/max了， 没必要重复安装啊

**Comment by lbyupup** [comment]
> 

嗯嗯 插件确实重复了，导入也应该从@umijs/max导入，不过这里是一个keep-alive的依赖引起的问题
https://github.com/umijs/umi/discussions/9191
