### ISSUE TITLE
[Bug] babel-preset-umi  dependencies core-js locked version 3.22.4

### ISSUE THREAD

**Issue by lzbabd** [umijs/umi#9196]
core-js 3.23.0 fiexd "throw error Cannot redefine property: DEG_PER_RAD"
https://github.com/zloirock/core-js/issues/1091

**Comment by fz6m** [comment]
3.22 系列没有问题的，有问题的是 `3.23.0` ，在有问题的页面用 `window['__core-js_shared__']` 看一下加载了哪些 `core-js` 版本吧。
