### ISSUE TITLE
[Bug] history.location.pathname 和 window.location.pathname 不一致

### ISSUE THREAD

**Issue by tolerance-go** [umijs/umi#9207]
## What happens?

不知道是不是 bug，如题

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/tolerance-go/maybe-umi-bug-history-pathname

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

1. 在 /home 页面，点击左下角“退出”按钮
2. 自动跳转到 /table 页面后，查看 searchParams 内容

![image](https://user-images.githubusercontent.com/37258382/187967402-a4a7c475-e2ae-45ba-93bd-da896bfacc2f.png)

**Expected behavior** 1. 2.

## Context

- **Umi Version**:   "@umijs/max": "^4.0.17",
- **Node Version**: v16.16.0
- **Platform**: macOS

**Comment by fz6m** [comment]
react router v6 中 history 是 immutable 的，使用 location 时：

```ts
import { useLocation } from 'umi'

// ...

  const location = useLocation()
```

FYI :

 - [useLocation](https://reactrouter.com/en/main/hooks/use-location)

 - https://zenn.dev/khale/articles/react-router-update-v6

**Comment by tolerance-go** [comment]
> react router v6 中 history 是 immutable 的，使用 location 时：
> 
> ```ts
> import { useLocation } from 'umi'
> 
> // ...
> 
>   const location = useLocation()
> ```
> 
> FYI :
> 
> * [useLocation](https://reactrouter.com/en/main/hooks/use-location)
> * https://zenn.dev/khale/articles/react-router-update-v6

谢谢回复

实验了一下 没问题了 https://github.com/tolerance-go/maybe-umi-bug-history-pathname/tree/fix

**Comment by fz6m** [comment]
用不了的地方传导下去。

可以参考这个 HOC 让使用更简单：

https://github.com/umijs/umi/blob/53dc7c0daf212d4b92439fb68437452891ce326f/packages/renderer-react/src/withRouter.tsx#L19-L52

**Comment by tolerance-go** [comment]
> 用不了的地方传导下去。
> 
> 可以参考这个 HOC 让使用更简单：
> 
> https://github.com/umijs/umi/blob/53dc7c0daf212d4b92439fb68437452891ce326f/packages/renderer-react/src/withRouter.tsx#L19-L52

👍
