### ISSUE TITLE
document.ejs 识别不到  <div id="root"></div>

### ISSUE THREAD

**Issue by Viin-zx** [umijs/umi#921]
升级到beta.18版本后，在document.ejs 中这样写识别不到
` <div id="root" style="height: 100%;"></div>
`
`error: Document src\pages\document.ejs must contain <div id="root"></div>`

 一定要这样写才行 `<div id="root"></div>`，希望修复下。

**Comment by Viin-zx** [comment]
@sorrycc

**Comment by okoala** [comment]
建议你样式最好和 dom 分开

**Comment by Viin-zx** [comment]
@okoala 现在已经分开了，但是之前是可以的，所以这个还是一个小BUG吧。

**Comment by okoala** [comment]
@Viin-zx 其实这只是个约定

**Comment by Viin-zx** [comment]
不只是style，dom加任何属性都不行。
