### ISSUE TITLE
[Bug] max 配置alias，报错“AssertionError [ERR_ASSERTION]: filePath not found of @@/exports”

### ISSUE THREAD

**Issue by ysyonline** [umijs/umi#9211]
## What happens?
umi max 在 config/config.ts中配置alias，启动报错

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce
1.在config/config.ts中配置alias
![QQ截图20220902104028](https://user-images.githubusercontent.com/20297037/188048634-e4a40398-c8ed-4045-8cfb-fde51131680d.png)

2. 启动项目
![2](https://user-images.githubusercontent.com/20297037/188048676-4c72cadf-83fc-4986-bb07-88d3b80ea612.png)

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:v4.0.15
- **Node Version**:v16.16.0
- **Platform**:win10

**Comment by 0fan** [comment]
+1
