### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by wxufei** [umijs/umi#9213]
## What happens?

umi项目 添加lodash 和类型声明，启动会报错

复现步骤：
1. pnpm dlx create-umi@latest
2. sudo yarn add lodash
3. sudo yarn add @types/lodash

结果：
Failed to compile
Module not found: Error: Can't resolve '/Users/xufei/LABORER/Study/Stock/src/.umi/umi.ts' in '/Users/xufei/LABORER/Study/Stock/mfsu-virtual-entry'

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:"@umijs/max": "^4.0.17",
- **Node Version**:16.16.0
- **Platform**: mac电脑 谷歌浏览器

**Comment by buquan** [comment]
请问解决了吗，我也一样的问题

**Comment by fz6m** [comment]
提供一个最小复现看看。
