### ISSUE TITLE
[Bug] 今天跑项目，重新安装了nodejs16.0.0，重新install了项目，跑不起来了，fatal - TypeError: api.modifyBabelOpts is not a function报这个错

### ISSUE THREAD

**Issue by FrancisFeng-dot** [umijs/umi#9214]
## What happens?

fatal - TypeError: api.modifyBabelOpts is not a function
    at inspectorPlugin (***\node_modules\react-dev-inspector\plugins\umi\react-inspector.js:18:9)
    at Service.initPlugin ***\node_modules\umi\node_modules\@umijs\core\dist\service\service.js:346:40)
    at Service.run (***\node_modules\umi\node_modules\@umijs\core\dist\service\service.js:223:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Service.run2 (***\node_modules\umi\dist\service\service.js:74:12)
    at async ***\node_modules\umi\dist\cli\forkedDev.js:24:5
fatal - A complete log of this run can be found in:
fatal - D:\anewprogrom\kongzhi\stca-web\node_modules\.cache\logger\umi.log
fatal - Consider reporting a GitHub issue on https://github.com/umijs/umi/issues
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce
运行npm start产生
**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi 4.0.1**:
- **Node 16.0.0**:
- **Platform**:

**Comment by xiaohuoni** [comment]
和node版本没关系啊，是你重新 install 之后，umi 用到了最新版本，没有更新之前先锁版本号

**Comment by aibps** [comment]
使用ant-design-pro的pro-cli创建的脚手架选umi4，把react-dev-inspector插件配置开启后，就会报上面相同的错误  @xiaohuoni

**Comment by fz6m** [comment]
给一个复现看看

**Comment by xiaohuoni** [comment]
`api.modifyBabelOpts` 这个问题就是在 umi@4 项目中用到了 umi@3 的插件

**Comment by qugan09** [comment]
怎么解决啊

**Comment by caoxuccc** [comment]
这个问题没有解决办法了吗

**Comment by xiaohuoni** [comment]
别在 umi@4 的项目里面用umi@3 的插件就好了。要解决什么？？

**Comment by MUMU46** [comment]
不要用umi4, 换成umi3
