### ISSUE TITLE
开发模式下,public文件夹的疑问。

### ISSUE THREAD

**Issue by Viin-zx** [umijs/umi#922]
请问开发模式下，最外层public文件夹会编译是吗？

问题： 在public文件夹下放了两个公共库，什么都没干，没引用。然后改代码保存的时候编译时间就特别长了，编译时间和public文件夹下面的内容大小成正比，基本上是在这等好久。

![image](https://user-images.githubusercontent.com/19523605/44653417-4ef32380-aa21-11e8-9dde-5ff798c59388.png)

**Comment by okoala** [comment]
提供下可以重现问题的代码仓库

**Comment by xiaohuoni** [comment]
@Viin-zx public下的文件会被完全拷贝

**Comment by Viin-zx** [comment]
@xiaohuoni 哦哦，谢谢，那请问下开发模式下，有没有什么配置可以屏蔽这个重复拷贝吗。因为public下都是不需要编译的静态文件。

**Comment by xiaohuoni** [comment]
@Viin-zx public下面的应该是约定式的，你可以考虑放到别的文件夹里面去，然后使用copy配置来实现
https://umijs.org/config/#copy
