### ISSUE TITLE
generate files阶段报错，这个大概是什么问题

### ISSUE THREAD

**Issue by yaodong5063** [umijs/umi#9224]
info  - generate files
fatal - Error: [BABEL] C:\work\polyfill.ts: @babel/helper-compilation-targets: 'false' is not a valid value for 'targets.edge'. (While processing: "C:\\work\\node_modules\\@umijs\\bundler-utils\\compiled\\babel\\preset-env.js")

**Comment by undefined996** [comment]
> info - generate files fatal - Error: [BABEL] C:\work\polyfill.ts: @babel/helper-compilation-targets: 'false' is not a valid value for 'targets.edge'. (While processing: "C:\work\node_modules\@umijs\bundler-utils\compiled\babel\preset-env.js")

最后解决了么
