### ISSUE TITLE
umi4 路由跳转 query传参

### ISSUE THREAD

**Issue by lbyupup** [umijs/umi#9234]
## What happens?
升级umi4，使用 @umijs/max 在使用路由跳转传递query参数时，跳转页面后，拿到的query为空对象，刷新页面后query正常获取

## How To Reproduce

** 路由跳转
```ts
import { history, createSearchParams } from '@umijs/max';
history.push({
    pathname: '/test,
    search: `${createSearchParams({
    id: record.id,
  })}`
});
```

**获取query
```ts
import { parse } from 'query-string';
const query = parse(history.location.search);
```
跳转页面初始化后query为空对象，刷新后query正常

"@umijs/max": "4.0.15",

**Comment by lbyupup** [comment]
有用到react-activation来做keepalive，怀疑是这个引起，但升级umi4之前是正常的，尝试去掉keepalive后也出现该问题

**Comment by xierenyuan** [comment]
可以看看 react-router v6 的api 比如试试  https://reactrouter.com/en/main/hooks/use-search-params 这个看看

**Comment by lbyupup** [comment]
> 可以看看 react-router v6 的api 比如试试 https://reactrouter.com/en/main/hooks/use-search-params 这个看看

感谢，使用改hook就正常了
有同样问题的可以用下面的方式获取query(search) 参数
```ts
const [searchParams] = useSearchParams();
searchParams.get('id');
```

**Comment by lbyupup** [comment]
> 可以看看 react-router v6 的api 比如试试 https://reactrouter.com/en/main/hooks/use-search-params 这个看看

![image](https://user-images.githubusercontent.com/72724939/188609162-5c1eb8f2-8e9c-48a4-a7ff-41daf011a5a7.png)
感觉文档的这里可以调整一下，我一开始就是参照这个改的 :scream:
