### ISSUE TITLE
[Bug] 自定义权限403页面配置文档描述错误

### ISSUE THREAD

**Issue by aaron-cwt** [umijs/umi#9235]
## What happens?
unAccessible参数不生效
改用noAccessible生效

## Mini Showcase Repository(REQUIRED)

[layout.ts](https://github.com/umijs/umi/blob/master/packages/plugins/src/layout.ts)

```
const Exception: React.FC<{
  children: React.ReactNode;
  route?: IRoute;
  notFound?: React.ReactNode;
  noAccessible?: React.ReactNode;
  unAccessible?: React.ReactNode;
  noFound?: React.ReactNode;
}> = (props) => (
  // render custom 404
  (!props.route && (props.noFound || props.notFound)) ||
  // render custom 403
  (props.route.unaccessible && (props.unAccessible || props.noAccessible)) ||
  // render default exception
  ((!props.route || props.route.unaccessible) && (
    <Result
      status={props.route ? '403' : '404'}
      title={props.route ? '403' : '404'}
      subTitle={props.route ? '抱歉，你无权访问该页面' : '抱歉，你访问的页面不存在'}
      extra={
        <Button type="primary" onClick={() => history.push('/')}>
          返回首页
        </Button>
      }
    />
  )) ||
  // normal render
  props.children
);
```

![image](https://user-images.githubusercontent.com/16553706/188577938-0e1c6b22-a994-4b50-9304-6e9ff6c93bec.png)

## Context

- **Umi Version**: 4.0.6
- **Node Version**: v16.16.0
- **Platform**:

**Comment by chenwei-p** [comment]
noFound 好像也改为了 notFound ，但是我使用notFound也无效，请问你是怎么配置的？

**Comment by aaron-cwt** [comment]
> noFound 好像也改为了 notFound ，但是我使用notFound也无效，请问你是怎么配置的？

`  {
    path: '/*',
    component: './404',
  }
`
用路由匹配

**Comment by chenwei-p** [comment]
> > noFound 好像也改为了 notFound ，但是我使用notFound也无效，请问你是怎么配置的？
> 
> ` { path: '/*', component: './404', }` 用路由匹配

我也是这么解决的

**Comment by fz6m** [comment]
1. 配置式路由必须显示自己配置 `/*` 匹配想要的 404 页面

2. `noAccessible` 和 `unAccessible` 现在应该都兼容了，可以尝试下最新版本 `4.0.47` 。

**Comment by Laurieliuren** [comment]
附议，太气了，搜了半天才找到是这个问题，我是4.0.24版本

**Comment by zp-0711** [comment]
@fz6m unAccessible 目前还是不能用，noAccessible配置了是可以的

**Comment by fz6m** [comment]
更新到最新版本 `4.0.76` 看一下，如果还有问题，开一个新的 issue 给一个最小复现看看吧。

**Comment by zp-0711** [comment]
@fz6m 还有一个问题，noAccessible只能写组件吗，如果通过URL访问没有权限的页面会拦截跳转自定义组件上，如果想要给noAccessible写一个函数，函数处理跳转到一个html文件的地址，好像目前实现不了

**Comment by fz6m** [comment]
你在这个没有权限的组件 `useEffect` 里面新开一个 html 窗口或者直接跳转当页就可以

**Comment by zp-0711** [comment]
@fz6m 好滴，谢谢
