### ISSUE TITLE
[Bug] layout 配置到底是函数还是对象,有文档吗?

### ISSUE THREAD

**Issue by Valar103769** [umijs/umi#9237]
这里是对象
![image](https://user-images.githubusercontent.com/36926073/188595075-ffe18bee-96c1-41b0-a68f-934e3eedc379.png)
点过去,变成了函数,

![image](https://user-images.githubusercontent.com/36926073/188595193-092cfd14-87b0-49eb-9f20-e5ab08267605.png)

另外,到底哪里来的logout属性

[重现链接](https://codesandbox.io/s/6tl4lx)

**Comment by Valar103769** [comment]
@chenshuai2144  大佬, umi的文档,是不是要找umi的人看呢? 还是说你们antd的部门也可以

**Comment by drizzlesconsin** [comment]
logout https://github.com/umijs/umi/blob/master/packages/plugins/src/layout.ts#L420-L430

https://umijs.org/docs/api/runtime-config#typescript-%E6%8F%90%E7%A4%BA

**Comment by Valar103769** [comment]
> 

我还是没看懂, 
1. layout配置哪里来的? 
2. 对象还有函数靠ts吗,没有文档是这个意思吗?
@drizzlesconsin

**Comment by Valar103769** [comment]
> `函数返回个对象` 认真读第一个文档，你会找到第二个文档，最后会摸到第三个文档。绝对不会错的
> 
> 1. https://umijs.org/docs/api/runtime-config#layout
> 2. https://umijs.org/docs/max/layout-menu#%E8%BF%90%E8%A1%8C%E6%97%B6%E9%85%8D%E7%BD%AE
> 3. https://procomponents.ant.design/components/layout/#prolayout

不着急关issue吧, 都没解决问题呢
我再描述一下我的问题, 关于layout是函数还是对象,文档在哪里?
```
export const layout = {}
```
vs 
```
export const layout =()=>({})
```
第二个问题, api参数在第三个链接, 里面并没有叫`logout` 的参数 @drizzlesconsin @chenshuai2144

**Comment by drizzlesconsin** [comment]
https://github.com/umijs/umi/blob/master/packages/plugins/src/layout.ts#L24-L27

logout Umi@3就有的功能 [plugin-layout#logout](https://v3.umijs.org/zh-CN/plugins/plugin-layout#logout)
