### ISSUE TITLE
这种写法报错的原因是什么呢？我看文档上的例子就是这样写的

### ISSUE THREAD

**Issue by JokerYYY** [umijs/umi#9238]
![image](https://user-images.githubusercontent.com/31911076/188598338-0823eb6d-2f56-4a78-86f6-0ce11a4bee6a.png)

**Comment by fz6m** [comment]
文件名称是否是 tsx 格式 `app.tsx` ？

**Comment by JokerYYY** [comment]
ts，这个是直接通过yarn create umi创建的项目，什么都没动，看文档上改了图片中的代码，但看起来不太行，node版本14.20.0
