### ISSUE TITLE
[Bug] clientLoader和useModel冲突报错

### ISSUE THREAD

**Issue by xifanii** [umijs/umi#9239]
## What happens?
代码如下：
![image](https://user-images.githubusercontent.com/9626111/188605035-b70e2027-1cbc-4cdf-bd32-bb418261e887.png)

当使用了clientLoader，想把对应的逻辑都放model里处理的时候，会报错，报错信息如下：
![image](https://user-images.githubusercontent.com/9626111/188605527-9f49f6e9-39f1-4536-874c-3cff9473fc0f.png)

希望能有解决方案，也希望能出多些clientLoader的用例以及clientLoader配合useModel使用的用例

## Mini Showcase Repository(REQUIRED)
https://github.com/xifanii/umi-issue-demo/blob/master/src/pages/Home/index.tsx

## How To Reproduce

1、直接加载页面就会报错

## Context

- **Umi Version**: "@umijs/max": "^4.0.13"
- **Node Version**: v18.7.0
- **Platform**: chrome

**Comment by fz6m** [comment]
umi 里 use model 的东西现在都是全局独立存在的，所以它才可以保持持久性在各个组件共享，model 里拿不到应用里的上下文。

此处可以下放逻辑到局部的 context 去，或者使用 [hox](https://github.com/umijs/hox) ，该方案可以让逻辑局部持久存在，而不是像 umi 的 model 一样存在于全局拿不到上下文。
