### ISSUE TITLE
mock 文件报错的情况下 dev server 没有终止

### ISSUE THREAD

**Issue by yutingzhao1991** [umijs/umi#924]
mock 文件如果有语法错误，umi dev 还是会基于启动，最后会正常显示启动信息，但是访问不了。

**Comment by xiaohuoni** [comment]
重现demo：https://github.com/umi-cli-test/umi-mock-bug
表现如下：
```
umi dev

  App running at:
  - Local:   http://localhost:8000/
  - Network: http://192.168.199.196:8000/
```
然后修改一下mock文件，导致出错。
dev server 就终止了。

再次启动（不修复语法错误）
```
umi dev

  App running at:
  - Local:   http://localhost:8000/
  - Network: http://192.168.199.196:8000/
```
还是显示正常启动，但是无法访问。就是这时候修复了错误。还是无法访问。

**Comment by xiaohuoni** [comment]
其他文件，出现语法错误，应该是报错，但是服务并没有关闭，修复错误之后，就恢复正常了

**Comment by leijingdao** [comment]
@yutingzhao1991  有语法错误，虽然顺利启动的服务器，但之前命令行还是会提示plugin apply failed 吧？

**Comment by leijingdao** [comment]
因为你之前没有提供复现的仓库，我按照我自己的想法，尝试复现错误。 然后把我看到的现象和你描述一下，看是不是理解的有问题。

**Comment by leijingdao** [comment]
![_20180910114115](https://user-images.githubusercontent.com/12496382/45275298-84eada00-b4ee-11e8-8374-e2d107fa1f73.png)
@yutingzhao1991

**Comment by yutingzhao1991** [comment]
嗯 就是这样的。

**Comment by sorrycc** [comment]
想了想，我觉得不退出应该是正常的，只是出错提示没有提示到位，应该在启动完成后，把 mock 的出错信息也打印下。

**Comment by yutingzhao1991** [comment]
嗯，另外如果错误修复了能恢复正常就行。

**Comment by leijingdao** [comment]
我现在也刚好像找到了问题的关键，如果你还没有开始改代码， 能给我一次提PR的机会吗？  @sorrycc
