### ISSUE TITLE
build 打包不可以修改文件名字吗？

### ISSUE THREAD

**Issue by Zmoonpie** [umijs/umi#925]
请问一下可以修改打包文件名字吗

**Comment by xiaohuoni** [comment]
应该可以的，在html中也要修改一下饮用文件名

**Comment by Zmoonpie** [comment]
@xiaohuoni  可以说的详细一点吗 感谢 我用的1.x

**Comment by xiaohuoni** [comment]
你说的不是手动修改吗？
自动修改，暂时好像不支持

**Comment by Zmoonpie** [comment]
恩恩 谢谢  我说的自动修改

**Comment by Zmoonpie** [comment]
@xiaohuoni  大佬在问一个问题 打包后的文件部署必须每个文件都引用吗？ 我没引用完的话报错：loading chunk 0 failed

**Comment by xiaohuoni** [comment]
（没试过，不引用文件）这个问题应该不值得考虑吧。就算你有些文件没有引用，可以运行，但是在按需加载触发时，没有这些文件，应该也会报错。
