### ISSUE TITLE
v4 使用约定式路由时，传递给ProLayout组件的route.routes没有name属性，无法正常显示layout的menu。

### ISSUE THREAD

**Issue by laoriy** [umijs/umi#9268]
## What happens?
v4 使用约定式路由时，传递给ProLayout组件的route.routes没有name属性，无法正常显示layout的menu。

## Mini Showcase Repository(REQUIRED)

> 官方脚手架生成的代码将.umirc.ts 移除routes配置即可复现

## Context

- **Umi Version**:@umijs/max v4.0.11
- **Node Version**:v14.19.0
- **Platform**: window

**Comment by drizzlesconsin** [comment]
预期结果

ref: https://pro.ant.design/zh-CN/docs/layout/#%E8%8F%9C%E5%8D%95%E5%B1%95%E7%A4%BA
