### ISSUE TITLE
[Bug] 从4.0.18开始，启动后报，fatal - TypeError: (0 , import_bundler_utils.createProxy) is not a function

### ISSUE THREAD

**Issue by oxygen-xx** [umijs/umi#9278]
从4.0.18开始，启动后报，fatal - TypeError: (0 , import_bundler_utils.createProxy) is not a function

## Context

- **Umi Version**: 4.0.18  4.0.19
- **Node Version**: 16.17.0
- **Platform**: Macos

**Comment by ldwonday** [comment]
遇到同样的问题

**Comment by ldwonday** [comment]
![image](https://user-images.githubusercontent.com/4630157/197977955-43c5f556-6c54-460d-8076-4de88d821f1e.png)

**Comment by fz6m** [comment]
提供一个最小复现看看
