### ISSUE TITLE
umi2.x实现热加载问题

### ISSUE THREAD

**Issue by Zmoonpie** [umijs/umi#928]
请问一下umi2.x怎么实现热加载，在umi dev 情况下一改动代码就自动打包

**Comment by okoala** [comment]
那不得卡死~

**Comment by Zmoonpie** [comment]
@okoala  因为之前公司react项目就是一改代码就打包呈现出来……如果不实现热加载，那前后端怎么调试啦

**Comment by Zmoonpie** [comment]
@okoala  大佬我说错了 不会打包  就跟react-hot-loader一个效果

**Comment by okoala** [comment]
哦，你是问怎么实现？

**Comment by Zmoonpie** [comment]
是的……

**Comment by xiaohuoni** [comment]
@Zmoonpie 不是本来就是热更新的嘛？

**Comment by Zmoonpie** [comment]
@xiaohuoni  场景是这样的，前后端分离，后端读取的是前端build的文件，需要实现的效果是在前端代码运行起来的时候，改动前端代码，后端启动的网站能实时的读取到改动的内容

**Comment by Zmoonpie** [comment]
@Viin-zx  这个问题先放着吧，还有一个问题就是我前端代码document.ejs里面引用了一个外部font-awesome  css文件，文件 放在根目录下的wwwroot下面.之前还能用 现在怎么也读取不到了，是设置publicpath吗？

**Comment by sorrycc** [comment]
部署问题先看这个文档，https://umijs.org/guide/deploy.html
