### ISSUE TITLE
[Bug] vite build运行时抛错

### ISSUE THREAD

**Issue by wkeylin** [umijs/umi#9280]
## What happens?  

用vite build构建后的产物无法正常执行

<img width="773" alt="image" src="https://user-images.githubusercontent.com/21221921/189118954-cd0ff582-269d-4a42-a7d9-ad9103fbb85a.png">

## Mini Showcase Repository(REQUIRED)
[初始化demo](https://github.com/wkeylin/umi-demo)  

## How To Reproduce
1.  npx create-umi@latest
2. .umirc.ts 配置：vite: {}
3.  npm run build
4. npx umi-serve

## Context

- **Umi Version**: 4.0.19
- **Node Version**: 16.17.0
- **Platform**: mac, edge浏览器v105.0.1343.27

**Comment by hustcer** [comment]
@fz6m 请问下这个问题大概什么时候能解决呢？现在生产环境亟需解决这个问题，谢谢

**Comment by wkeylin** [comment]
打开sourcemap

**Comment by wkeylin** [comment]
build 生成的产物包含了vite?

**Comment by 15835196981** [comment]
@wkeylin   大佬   这个问题你解决了吗？  求指教~~~

**Comment by wkeylin** [comment]
> @wkeylin 大佬 这个问题你解决了吗？ 求指教~~~

看着是vite的预编译产物有问题，只能他们解决

**Comment by fz6m** [comment]
可以尝试下 umi 最新版本 `4.0.41` 是否还存在这个问题。
