### ISSUE TITLE
[Bug] umi3升级umi4后，多个umi内置功能找不到

### ISSUE THREAD

**Issue by junglehuang** [umijs/umi#9286]
## What happens?

根据文档将umi3 升级到 umi4 后出现以下报错信息
![image](https://user-images.githubusercontent.com/16217730/189288015-24d9dd59-33d5-4a22-950b-0357942ad40a.png)
![image](https://user-images.githubusercontent.com/16217730/189288063-d9d527e7-013a-4854-9a3a-a6fcb9c56839.png)

版本
"@umijs/max": "^4.0.19",

删除 node_module 等操作后还是一样

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
使用 model 需要配置开启 `model: {}` ，可以初始化一个 max 项目对比下。
