### ISSUE TITLE
为什么升级到4.0.19就降不到4.0.11了

### ISSUE THREAD

**Issue by mwj610** [umijs/umi#9289]
![image](https://user-images.githubusercontent.com/52907799/189298994-7d912dd9-2682-402f-8622-dc86a3250b43.png)
![image](https://user-images.githubusercontent.com/52907799/189298943-598373f9-a338-42a0-8721-df019ed13987.png)

我把node_modules删了  重新安装也是4.0.19

**Comment by fz6m** [comment]
`^` 的语义是安装最新的，如果要回退使用精准版本号
