### ISSUE TITLE
umi4.0.19 创建项目设置base 为 /admin/ 之后所有页面默认路由都会变成 http://localhost:8001/admin/admin/home

### ISSUE THREAD

**Issue by WillWuWeijie** [umijs/umi#9293]
![image](https://user-images.githubusercontent.com/14213206/189324337-c852d9ae-5fc9-4b34-ad7e-e68d9b07d91b.png)
[demo](https://codesandbox.io/p/github/WillWuWeijie/umi-4.0.19-base-route/draft/hungry-burnell?file=%2F.umirc.ts&selection=%5B%7B%22endColumn%22%3A24%2C%22endLineNumber%22%3A16%2C%22startColumn%22%3A24%2C%22startLineNumber%22%3A16%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl7ty0qwz001dlnhtbppo3b88%2522%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522key%2522%253A%2522cl7uaz7j4000k3b6kjh8y2tqn%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Atrue%257D%255D%257D)

**Comment by telanflow** [comment]
我也碰到这种情况。

我还碰到了 在登录页登录成功后，使用 setInitializeState 保存用户信息到全局state 不成功的问题。在 app.tsx 文件中的 layout 事件里面 参数传进来的 initializeState 是 undefined。

**Comment by fz6m** [comment]
@telanflow 给复现看看。

**Comment by telanflow** [comment]
@fz6m  #9295

**Comment by fz6m** [comment]
修复于 `4.0.20`
