### ISSUE TITLE
[Bug] umi 4.0.19  login登录成功后首次 setInitialState 未成功，导致跳回login页面。第二次登录才进入首页

### ISSUE THREAD

**Issue by telanflow** [umijs/umi#9295]
## What happens?
2个问题

1. setInitialState问题：login.tsx 登录成功后 setInitialState() 首次未生效，导致app.tsx layout事件中的 initialState.currentUser 为 undefined，从而login 跳转回login，再次去点击登录才进入welcome页面。
2. base路由前缀问题（/admin）：登录成功后跳转页面，或者点击左侧菜单，都会重复 /admin/admin 从而找不到页面，显示空白页。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

1. `pro create umi` 使用antd pro 创建的项目
2. 修改了 react 依赖版本 18.2.0，以及更新umi为最新版本

![log](https://github.com/telanflow/umi-4.0.19-bug/raw/master/debug.png) 

复现项目见：[参见此项目](https://github.com/telanflow/umi-4.0.19-bug)

## Context

- **Umi Version**: ^4.0.19
- **Node Version**: 16.15.0
- **Platform**: windows x64
- **React Version**: ^18.2.0

**Comment by telanflow** [comment]
react 17：没有第一个setInitialState的问题，但是还是存在base路由前缀的问题。
react 18：两个问题同时存在。

**Comment by fz6m** [comment]
1. initialState `undefined` 是 ant pro 那边的问题，可能需要调整下那边的逻辑，找 [ant-design-pro](https://github.com/ant-design/ant-design-pro) 反馈吧。

    目前的临时解决办法 ( react 18 only ) ：
    
    ```ts
    import { flushSync } from 'react-dom';
    
    // ...
    
    flushSync(() => {
      setInitialState((s) => ({
        ...s,
        currentUser: userInfo,
      }));
    })
    ```

2. 第二个 base 问题在 #9296 修复。

**Comment by telanflow** [comment]
@fz6m 好的 非常感谢！

**Comment by liuyurong-hub** [comment]
我看啦一下.umi中的实现，initialState的变更貌似没有在runtimeConfig中没有去做响应式更新
![image](https://github.com/umijs/umi/assets/125435650/9e92cf58-6cdd-4eeb-a5a4-cad0f570c0e6)
