### ISSUE TITLE
嵌套路由页面访问时的闪烁或跳跃问题

### ISSUE THREAD

**Issue by silentim** [umijs/umi#9304]
如下代码：

```
/** umi4 布局页 */
/** /src/layouts/index.umi4.jsx */
export default function Layout(){
    return (
        <div>
            <Outlet />
        </div>
    )
}
```

```
/** umi3 布局页 */
/** /src/layouts/index.umi3.jsx */
export default function Layout({children}){
    return (
        <div>
            {children}
        </div>
    )
}
```

```
/** 页面 */
/** /src/pages/page1.jsx */
export default function Page1(){
    return (
        <div>一段长长的内容....</div>
    )
}

/** /src/pages/page2.jsx */
export default function Page2(){
    return (
        <div>另一段长长的内容....</div>
    )
}
```

在umi4中，当访问完 http://localhost:8000/page1 ，路由切换（使用Link或history.push）至 http://localhost:8000/page2 时，outlet位置会有很明显的闪烁或跳跃，象是先清除outlet处原有内容，然后再把page2的内容插入outlet。而umi3的时候没有闪烁或跳跃的感觉，umi3感觉象是直接replace，而不是先clear再insert。

不管umi4有没有src/loading.jsx，都一样明显闪烁，只是有loading.jsx的话，会出现loading状态，仍然是闪烁的（先clear再insert的既视感）

想知道这种现象是属于正常的吗？是outlet的原因还是别的？能否避免？

**Comment by PikachuGits** [comment]
我也遇到一样的问题，原因是因为，loading加载是按页加载，当你的loading样式是百分比的话，会被已经加载出的模块挤出当前位置。只需要做绝对定位，宽高设置最大就可以了
