### ISSUE TITLE
[Bug] @umijs/plugin-qiankun不兼容umi4.x

### ISSUE THREAD

**Issue by rfw** [umijs/umi#9307]
## What happens?

@umijs/plugin-qiankun不兼容umi4.x 

因为@umijs/max包含很多插件，仅想使用qiankun

## Mini Showcase Repository(REQUIRED)

https://github.com/rfw/umijs4.x-umijs-plugin-qiankun/tree/main

## How To Reproduce
```
yarn 

yarn setup

 ```

## Context

- **Umi Version**: ^4.0.20
- **Node Version**: v14.17.6
- **@umijs/plugin-qiankun**: "^2.40.0",

**Comment by fz6m** [comment]
umi 4 的用法：

```bash
  pnpm add @umijs/plugins
```

```ts
// .umirc.ts

export default {
  plugins: ['@umijs/plugins/dist/qiankun'],
  qiankun: {
    // ...
  }
}
```

**Comment by wangxingkang** [comment]
qiankun 插件不是内置了吗
