### ISSUE TITLE
umi升级到4.0后原来菜单配置中的wrappers全部失效了

### ISSUE THREAD

**Issue by bianbao** [umijs/umi#9321]
umi升级到4.0后，整个项目的route中的wrappers配置无效了
`wrappers: ['@/wrappers/authentication']`
根本进不去了

"dependencies": {
    "@ant-design/plots": "^1.0.9",
    "@umijs/route-utils": "^2.0.0",
    "antd": "^4.20.0",
    "copy-to-clipboard": "^3.3.1",
    "react": "17.x",
    "react-dom": "17.x",
    "@umijs/max": "^4.0.0"
  },
  "devDependencies": {
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@umijs/test": "^3.5.21",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.3.0",
    "lint-staged": "^10.0.7",
    "prettier": "^2.2.0",
    "typescript": "^4.1.2",
    "yorkie": "^2.0.0"
  }

**Comment by Alioth1017** [comment]
我也遇到了该情况，只有 layout配置 false时，wrappers 才会生效
