### ISSUE TITLE
[Feature Request] umi4如何配置cssModulesExcludes

### ISSUE THREAD

**Issue by hmilin** [umijs/umi#9323]
在umi4中如何对部分css文件关闭cssModules，像umi2的 [cssModulesExcludes配置](https://v2.umijs.org/config/#extrapostcssplugins)

**Comment by xierenyuan** [comment]
现在不是 import styles from 'xx' 才走 cssModules  吗 不写这个语法 直接 import 'xx'

**Comment by fz6m** [comment]
现在会根据导入方式自动识别是否使用 css modules ：

```ts
import './index.less' // 不使用 css modules
import styles from './index.less' // 使用 css modules
```
