### ISSUE TITLE
umi约定式路由中添加高阶组件的问题

### ISSUE THREAD

**Issue by kelekexiao123** [umijs/umi#934]
约定式路由中有什么办法能对路由指向的组件添加高阶组件包裹呢

**Comment by kelekexiao123** [comment]
另外由于router.js也为自动生成，那么如果需要监听进入某个route的钩子事件该如何实现呢

**Comment by kelekexiao123** [comment]
在dva()中添加中间件的问题已解决，可以通过导出的dva.js的config配置。

route的钩子，如onenter，onleave仍然不知道从何写入

**Comment by sorrycc** [comment]
好像没啥特殊需要考虑的，可参考 https://github.com/zuiidea/antd-admin/blob/master/src/pages/dashboard/index.js#L110

**Comment by kelekexiao123** [comment]
可能我没描述清楚问题，我希望在Routes的配置式路由里对路由的component组件进行包裹，
例如
` 
import NotFound from '404.js'
export default {
     routes: [
        {
          path: '/404',
          exact: true,
          component: HOC(NotFound),
        }
    ]
`
其中HOC为希望加入的高阶函数。
这样编译无法通过，请问有没有什么实现的办法呢
