### ISSUE TITLE
[Bug] 最新 create-umi vite dev 报 'module is not defined'

### ISSUE THREAD

**Issue by YiFeng-Developer** [umijs/umi#9350]
## What happens?

`npx create-umi@latest` 使用脚手架新建应用 开启vite 执行 `npm run dev` 等待预编译之后页面报错

查看本地 node_modules 依赖实际安装版本：@ant-design/cssinjs: 0.0.0-alpha.52

![image](https://user-images.githubusercontent.com/29992392/190610839-d221bf01-3f5c-46a6-a638-0439ff3573dc.png)

![image](https://user-images.githubusercontent.com/29992392/190611071-0a5d25cd-7fcd-4930-8e4f-e2cc2c7d36de.png)

## Mini Showcase Repository(REQUIRED)

[仓库地址](https://github.com/YiFeng-Developer/umi-demo)

## How To Reproduce

```
npm i
npm run dev
```
打开浏览器访问 http://localhost:8000

## Context

- **Umi Version**: 4.0.21
- **Node Version**: 16.16.0
- **Platform**: macOS

**Comment by YiFeng-Developer** [comment]
目前只能暂时在 package.json 里锁版本解决 "@ant-design/cssinjs": "0.0.0-alpha.45"

**Comment by fz6m** [comment]
我测试了下，最新版本 umi `4.0.41` 没有这个问题了。
