### ISSUE TITLE
[Feature Request] vite dev 请求瀑布流优化

### ISSUE THREAD

**Issue by YiFeng-Developer** [umijs/umi#9359]
## Background

执行 `npx create-umi@latest` 选择 Ant Design Pro 作为 umi app 的模板后，修改 config 开启 vite 打包，执行 `npm run dev`

存在请求瀑布流问题，600+ js 文件请求，3s+本地加载时间

![image](https://user-images.githubusercontent.com/29992392/190940131-cd2e02fd-6814-4977-8b8f-fd47bc5c2fe3.png)

是不是可以做一下优化，或者有什么建议 怎么配置 umi 或者 vite 的配置项 可以达到比较好开发体验

## Proposal

看了下 js 文件主要分为两类：1. polyfill；2.antd 各组件的样式文件 index.less

第一类目前想到的是两种方法：1.关闭 vite dev 时 umi 的 polyfill 选项；2.使用 vite 时，改用 @vitejs/plugin-legacy 处理 polyfill

第二个暂未想到好的方法

## Additional context

关闭 polyfill 后的请求数，以及剩下来的 index.less 请求

![image](https://user-images.githubusercontent.com/29992392/190944691-d5816ecd-175b-4bec-bd82-96fc9ddb7aa0.png)

**Comment by xierenyuan** [comment]
印象中 我应该 在vite dev 关闭了 polyfill 我在看看 , antd 的less 样式的话 可以引入 antd 的时候 style 配置成 css 看看https://github.com/umijs/umi/blob/master/packages/plugins/src/antd.ts#L181

**Comment by YiFeng-Developer** [comment]
> 印象中 我应该 在vite dev 关闭了 polyfill 我在看看 , antd 的less 样式的话 可以引入 antd 的时候 style 配置成 css 看看https://github.com/umijs/umi/blob/master/packages/plugins/src/antd.ts#L181

@xierenyuan 感谢回复 我稍后试试这个 less 的解决方案
