### ISSUE TITLE
HTML模板中引入iconfont.css，无法正常使用

### ISSUE THREAD

**Issue by lxtzxd** [umijs/umi#936]
1.环境:
 系统： windows 10，
 "umi": "^1.3.3",
 "umi-plugin-dva": "^0.7.1",
 "dva": "^2.2.3",

2.下载阿里 iconfont 上面图标样式，在static文件夹下创建 font 文件夹存储下载下来的图标相关文件。

3.在pages下的HTML模板文件 document.ejs 添加iconfont.css文件引用：
第一种引入方式：
<link rel="stylesheet" type="text/css" href="/static/font/iconfont.css"/>
第二种引入方式：
<link rel="stylesheet" type="text/css" href="../static/font/iconfont.css"/>

4.启动项目查看结果无法正常显示图标，查看network中的数据返回：
![image](https://user-images.githubusercontent.com/18571325/44768732-d7460580-ab94-11e8-880c-295a9425817b.png)

从数据返回来看显然返回的内容不是正确的css文件,请问这是怎么回事，正确的引入外部字体样式应该怎么做，是否有相关示例？

**Comment by laizhenhai88** [comment]
iconfont.css的语法比较飘逸，经过webpack的处理后，会出问题
一个变通的解决方法是，在global.css中做一下import，这样iconfont.css就会保持不变

@import url('./asserts/font/iconfont.css')

**Comment by xiaohuoni** [comment]
@laizhenhai88 试过了，上面的方法可行。
