### ISSUE TITLE
[Bug] 支持自定义 runtimePublicPath 指向的window属性

### ISSUE THREAD

**Issue by Valar103769** [umijs/umi#9362]
qiankun主应用导出的publicpath放在了 `window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__`, 
我需要子应用从`__INJECTED_PUBLIC_PATH_BY_QIANKUN__`属性上取,而不是你们写死的 `__webpack_public_path__ = window.resourceBaseUrl || window.publicPath`
你们的文档地址: 
https://v3.umijs.org/zh-CN/config#runtimepublicpath

我在 `src/app.tsx`中写了`__webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__`, 
但是他只对第一个页面有用
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/36926073/190961160-09eaa14c-c954-4ee8-b58f-9bf26d8da7cc.png">

当跳转到home页面时, 它失效了,所以需要你们提供编译选项,以便编译时读取它,并编译到每一个路由的html文件中
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/36926073/190960935-6fee24d6-1e49-4926-9b4b-55cb2afd6629.png">
应该是`localhost:8000`,

**Comment by Valar103769** [comment]
@sorrycc

**Comment by bingyang519** [comment]
我现在也被这个问题困扰着。

umi4搭建的子应用，在嵌入主应用时，只有umi.css 和 umi.js 的路径是对的，加上了publicpath
![11111](https://user-images.githubusercontent.com/23712401/191160198-e0448a15-a273-44f2-9dd7-95e1f0601f9d.png)


其他静态资源路径，缺少publicpath，导致404
![22222](https://user-images.githubusercontent.com/23712401/191160220-1a180657-a20a-4a15-94d2-b1281769bbf3.png)

大概搜索了一下，是webpack5的 tree sharking 把路径干掉了，
参考  https://cloud.tencent.com/developer/article/1961012
目前不知道怎么解决

**Comment by Valar103769** [comment]
> 我现在也被这个问题困扰着。
> 
> umi4搭建的子应用，在嵌入主应用时，只有umi.css 和 umi.js 的路径是对的，加上了publicpath ![11111](https://user-images.githubusercontent.com/23712401/191160198-e0448a15-a273-44f2-9dd7-95e1f0601f9d.png)
> 
> 其他静态资源路径，缺少publicpath，导致404 ![22222](https://user-images.githubusercontent.com/23712401/191160220-1a180657-a20a-4a15-94d2-b1281769bbf3.png)
> 
> 大概搜索了一下，是webpack5的 tree sharking 把路径干掉了， 参考 https://cloud.tencent.com/developer/article/1961012 目前不知道怎么解决

好的, 我也看看, 问个问题, 你的baseRoute怎么解决的, 不会是写死config文件里的base属性吧? 我用的antd pro 搭建的

**Comment by bingyang519** [comment]
> 

你是说这个吗？写死的
![333333](https://user-images.githubusercontent.com/23712401/191162585-334733f6-30fa-4f16-84ce-e653f8f02ff2.png)

**Comment by Valar103769** [comment]
> 

他这个webpack的问题 跟我的不一样, 我在子应用app.js 文件的onPageChange打印了publicPath 是正确的, 
1. 图片资源路径没有正确指向子应用
2. devScripts 路径没有正确指向子应用
3. api接口,没有正确指向子应用,导致不会走子应用的proxy代理

**Comment by Valar103769** [comment]
> > 
> 
> 你是说这个吗？写死的 ![333333](https://user-images.githubusercontent.com/23712401/191162585-334733f6-30fa-4f16-84ce-e653f8f02ff2.png)

这个写死了, 那你子应用就没办法单独运行了啊 还是说子应用不想单独运行了?

**Comment by bingyang519** [comment]
> > 
> 
> 他这个webpack的问题 跟我的不一样, 我在子应用app.js 文件的onPageChange打印了publicPath 是正确的,
> 
> 1. 图片资源路径没有正确指向子应用
> 2. devScripts 路径没有正确指向子应用
> 3. api接口,没有正确指向子应用,导致不会走子应用的proxy代理

那咱俩的问题貌似不太一样，我是有些文件的publicPath 缺失

**Comment by bingyang519** [comment]
> 

我这都是新项目，所以子应用是用Nginx配置的，直接在base目录下访问，xxx.com/base  这么访问子应用，没问题。老项目就不知道了，估计不太好搞。

**Comment by Valar103769** [comment]
> > > 
> > 
> > 
> > 他这个webpack的问题 跟我的不一样, 我在子应用app.js 文件的onPageChange打印了publicPath 是正确的,
> > 
> > 1. 图片资源路径没有正确指向子应用
> > 2. devScripts 路径没有正确指向子应用
> > 3. api接口,没有正确指向子应用,导致不会走子应用的proxy代理
> 
> 那咱俩的问题貌似不太一样，我是有些文件的publicPath 缺失

差不多的问题, 我的虽然打印出来了,只能说明 `__webpack_public_path__ = window.__INJECTED_PUBLIC_PATH_BY_QIANKUN__` 这句代码生效了, 但是并没有使用__webpack_public_path__去替换资源的publicpath

**Comment by Valar103769** [comment]
> > 
> 
> 我这都是新项目，所以子应用是用Nginx配置的，直接在base目录下访问，xxx.com/base 这么访问子应用，没问题。老项目就不知道了，估计不太好搞。

真是曲线救国啊, 不过这个base的问题, 你试试在主应用里写上props.base, 子应用不用动, 貌似可以解决base的问题
```js
registerMicroApps([
    {
      name: 'react app', // app name registered
      entry: '//localhost:8000',
      container: '#yourContainer',
      activeRule: '/bi-v3',
      props:{
        base:'/bi-v3'
      }
    },
   
  ]);
```

**Comment by bingyang519** [comment]
> 

感谢建议，我试了下，我这还是不行。我再调调

**Comment by bingyang519** [comment]
经过两个的各种摸索，终于跑起来了，分享下经验，以备后来人之需

概况：我父、子应用时umi4搭建的，都是独立部署的新项目。

我在子应用的qiankun 的生命周期打印了下参数，发现__INJECTED_PUBLIC_PATH_BY_QIANKUN__ 是 子应用的域名，并不带base！！！！
所以，只能手动拼一个上去了。

![22222](https://user-images.githubusercontent.com/23712401/191199958-47b98624-f8ce-4614-9e0c-240f8d54d455.png)
![1111111113333](https://user-images.githubusercontent.com/23712401/191199978-47fe43de-5727-4276-a063-af1606585790.png)


参考链接：https://segmentfault.com/a/1190000042063582?sort=newest


遇到问题太难排查了，😌

**Comment by Valar103769** [comment]
你有app.ts 的入口文件, 总能搞定,话说你试试 micoe-app呢 
我用的antd pro 搭建的,入口文件都没有,全靠插件,我是搞不下去了

**Comment by bingyang519** [comment]
> 
1、你看下上面的图片打印，umi4会自动通过props注入base
2、入口文件应该都有，默认不自动创建app.ts，你得自己创建，看下文档，有说明的。

**Comment by Valar103769** [comment]
> > 
> 
> 1、你看下上面的图片打印，umi4会自动通过props注入base 2、入口文件应该都有，默认不自动创建app.ts，你得自己创建，看下文档，有说明的。

我用的是antd pro, umi的配置都被配置化到项目里了, app.ts并不是他的入口文件 哈哈, 有个.umi/index.ts 但是貌似是编译出来的, 她妈的, 够恶心
