### ISSUE TITLE
[Bug] 初始化项目 umi/max，pro-component都是最新版本，提示未导出（pnpm安装）

### ISSUE THREAD

**Issue by JaylanChen** [umijs/umi#9374]
## What happens?

使用官方脚手架初始化项目
```
$ pnpm dlx create-umi@latest
✔ Install the following package: create-umi? (Y/n) · true
✔ Pick Npm Client › pnpm
✔ Pick Npm Registry › taobao
```
使用VS Code 打开项目后，src\pages\Access\index.tsx 提示 `模块“"@ant-design/pro-components"”没有导出的成员“PageContainer”。ts(2305)`
![image](https://user-images.githubusercontent.com/7055008/191148311-dde71e79-1c7c-4162-8e58-1974a70dc4fb.png)

![image](https://user-images.githubusercontent.com/7055008/191148439-d34881f1-dedc-4002-b8a3-18b0330f6f97.png)

## Mini Showcase Repository(REQUIRED)
[https://github.com/JaylanChen/umi4-error](https://github.com/JaylanChen/umi4-error)
1. 初始化项目
```
$ pnpm dlx create-umi@latest
✔ Install the following package: create-umi? (Y/n) · true
✔ Pick Npm Client › pnpm
✔ Pick Npm Registry › taobao
```

2. 使用VS code 打开，查看 src\pages\Access\index.tsx

## How To Reproduce

**Steps to reproduce the behavior:** 初始化项目
```
$ pnpm dlx create-umi@latest
✔ Install the following package: create-umi? (Y/n) · true
✔ Pick Npm Client › pnpm
✔ Pick Npm Registry › taobao
```

**Expected behavior**: 使用VS code 打开，查看 src\pages\Access\index.tsx

## Context

- **Umi Version**: v4.0.21
- **Node Version**: v16.17.0
- **pnpm Version**: v7.12.0
- **@ant-design/pro-components Version**: v2.3.9
- **Platform**: win 10
- **VS Code Versio**: v1.71.2
- ** TypeScript Version**: v4.8.3

**Comment by JaylanChen** [comment]
#https://github.com/ant-design/pro-components/issues/5939

**Comment by xiaorong61** [comment]
pnpm 问题不少，去年我用过一段时间的 pnpm，但导致了 vscode 补全体验更差，经常某个包存在却不能自动导入，后面就直接使用 npm 了。

**Comment by JaylanChen** [comment]
npm 安装慢，占用磁盘空间大，存在引用幻影问题；

**Comment by fz6m** [comment]
尝试一下 cmd + shift + p > reload ？

**Comment by JaylanChen** [comment]
> 

不行，重启VS Code 也不行

**Comment by shenchao890216** [comment]
如果使用pnpm的话，在.npmrc添加shamefully-hoist=true，然后删除node_modules，重新安装试试

**Comment by xiaorong61** [comment]
> > 如果使用pnpm的话，在.npmrc添加shamefully-hoist=true，然后删除node_modules，重新安装试试
> 
> 这可以解决，但这样依赖幻影隐患还在；

幻影依赖是 bug 还是 feature ? 😂

**Comment by JaylanChen** [comment]
> 

用了间接依赖的库，我认为幻影依赖应该算bug

**Comment by WuJiY** [comment]
无解吗?

**Comment by ywzou** [comment]
+1

**Comment by WuJiY** [comment]
今天升级了之后变成 找不到模块“antd”或其相应的类型声明。ts(2307)

**Comment by vegawong** [comment]
`.npmrc`文件里加下这个配置临时处理一下
```
public-hoist-pattern[]=@ant-design/*
```

**Comment by xierenyuan** [comment]
可以在工作区中 安装@ant-design/pro-components 依赖， umi 插件读取时 如果发现工作区中存在 会以工作区的依赖为准

**Comment by JaylanChen** [comment]
> 可以在工作区中 安装@ant-design/pro-components 依赖， umi 插件读取时 如果发现工作区中存在 会以工作区的依赖为准

初始化的项目有依赖   @ant-design/pro-components  的，[代码](https://github.com/JaylanChen/umi4-error/blob/4ec504033dbeb691bcef0486614a3ef504c3aab8/package.json#L15)

**Comment by genghanqiang** [comment]
安装了@ant-design/pro-components后继续安装@ant-design/pro-card等所需的组件

**Comment by conorzhong** [comment]
目前新拉下来的 antd pro 模版就有这个问题
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/39456642/197717554-1ed1cafd-9a89-4885-96fa-f9f74fe1fa79.png">
