### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by JasonWang1998** [umijs/umi#9375]
## What happens?

umi文档描述有app.ts/app.tsx误解的部分，具体如图所示
![image](https://user-images.githubusercontent.com/24191303/191152309-0000aa67-1a28-484a-8ec8-bbb4a8b4d2e5.png)
![image](https://user-images.githubusercontent.com/24191303/191152353-aade11e2-9150-4536-aee2-c16971be7aac.png)

具体地址：https://umijs.org/docs/max/layout-menu#%E9%85%8D%E7%BD%AE

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
当需定义 layout 运行时的 jsx 节点时，应该使用 `app.tsx` ，当不使用 jsx 时，可以写为 `app.ts` 。

使用 layout 功能 + 需要自定义 时，大多数情况应该使用 `app.tsx` （这也是 max 文档中的建议做法）。

不使用 layout 功能时，大多数情况应该使用 `app.ts` 。
