### ISSUE TITLE
[Bug] 本地yarn start可以正常运行，build以后白屏

### ISSUE THREAD

**Issue by sxyshirly** [umijs/umi#9378]
本地yarn start可以正常运行，build以后白屏

操作是
yarn create umi，
然后在.umirc.ts配置文件中配置以下内容
export default {
  npmClient: 'yarn',
  base: '/new/',
  publicPath: '/new/',
  history: { type: 'hash' },
  mfsu: false
};

手机端通过/new/index.html#/访问，白屏。观察index文件，umi.js都正常加载，但页面无法显示。本地运行没问题
，没有添加任何三方库

**Comment by fz6m** [comment]
检查 build 以后的部署方式是否符合 spa 标准，是否重定向到 `index.html`
