### ISSUE TITLE
umi dev 等半天没反应

### ISSUE THREAD

**Issue by changyijie** [umijs/umi#938]
> umi版本 1.3.18

  使用umi dev命令后 无反应 ，但是umi build就可以用。 之前是没有问题的

**Comment by sorrycc** [comment]
给可重现的库，或者参考 https://umijs.org/guide/migration.html 尝试升级到 umi@2。

**Comment by changyijie** [comment]
我先试试 升到2  不行的话 在弄个重现的库

**Comment by sorrycc** [comment]
有问题再 reopen 。
