### ISSUE TITLE
动态路由覆盖问题

### ISSUE THREAD

**Issue by Luxiaoshi** [umijs/umi#941]
![image](https://user-images.githubusercontent.com/8713879/44825110-9d7c0a00-ac3b-11e8-904b-260744e963bd.png)
这个会生成这样的路由文件
![image](https://user-images.githubusercontent.com/8713879/44825138-c13f5000-ac3b-11e8-92c8-6f0205dda396.png)
这样生成的顺序导致动态路由覆盖了后面的路由

ps：
当我删去export.js时：
![image](https://user-images.githubusercontent.com/8713879/44825213-2135f680-ac3c-11e8-874a-593139e04179.png)
生成的动态路由在最后，所以不会覆盖
![image](https://user-images.githubusercontent.com/8713879/44825248-56424900-ac3c-11e8-91a5-e245f2eebe3b.png)

但是我的需要还是需要我再添加一个路由的，不知如何解决。

**Comment by Luxiaoshi** [comment]
目前我的做法是为每个:id的动态路由再嵌套一层，可以解决这个问题，但是上述问题还是存在。

**Comment by sorrycc** [comment]
方便给个可重现的代码吗？

**Comment by sorrycc** [comment]
这是 umi@1 的项目，尝试升级到 umi@2 吧。
