### ISSUE TITLE
4.0动态路由规则是否能兼容3.0

### ISSUE THREAD

**Issue by ksh033** [umijs/umi#9419]
3.0动态路由
约定 [] 包裹的文件或文件夹为动态路由。

└── pages
└── [post]
├── index.tsx
└── comments.tsx
└── users
└── [id].tsx
└── index.tsx
4.0动态路由

pages/
foo/
$slug.js
$bar/
$.js
index.js
Proposal
Describe the solution you'd like, better to provide some pseudo code.
4.0是否也额能兼容[edit].tsx的动态路由

Additional context
动态路由规则是否能兼容一下.

**Comment by asdw741111** [comment]
同问
