### ISSUE TITLE
[Bug] jest.mock 不生效

### ISSUE THREAD

**Issue by kokiy** [umijs/umi#9422]
## What happens?

umi 结合 reamatch , dispatch 时候 call 一个function ,对这个function 进行mock 没有生效 ,注释掉 `import "umi/test-setup";`是生效的,应该是最近才改出来的问题 之前是好的

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
https://github.com/kokiy/umi4-demo

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

执行pages /_tests_/index.test.js , result is true data

**Expected behavior** 1. 2.
result is mock

## Context

- **Umi Version**: latest
- **Node Version**: 16
- **Platform**: mac & windows

**Comment by kokiy** [comment]
补充一下  如果mock fun 直接加到 jest-setup.ts 也是生效的 就是普通文件不生效

**Comment by kokiy** [comment]
@stormslowly  大佬帮忙看一下?

**Comment by stormslowly** [comment]
1.  jest.config.ts 正则需要修改下
```diff
-      "/node_modules/(?!antd|@ant-design|rc-.+?|@babel/runtime|@umijs/renderer-react|@umijs/preset-umi|umi).+(js|jsx)$",
+      "/node_modules/(?!.*(antd|@ant-design|rc-.+?|@babel/runtime|@umijs/renderer-react|@umijs/preset-umi|umi))",
```
2.  `@/service.js` mock 不生效的原因是在于，jest.setup.ts 中有如下依赖 关系 jest.setup.ts > app.ts > @/models/store >  question.ts > @/services 
在 case 执行的时候，已经缓存了一份原来的实现在 question中了。所以 jest.mock 不会生效。

1.  如果不需要 umi 运行时插件的初始化，可以先注释掉 test-setup 的代码
2. 等待 umi 页面级测试框架 https://github.com/orgs/umijs/projects/3/views/1

**Comment by fz6m** [comment]
在 `jest-setup` 里 mock 也可以。

**Comment by kokiy** [comment]
@stormslowly  现在umi 页面级测试框架 已经release 了 但是这个mock 的依旧不行, `TestBrowser` 没有给出mock api的解决办法

**Comment by kokiy** [comment]
曲线救国 不mock service 了 直接mock axios ,哈哈

**Comment by stormslowly** [comment]
> @stormslowly 现在umi 页面级测试框架 已经release 了 但是这个mock 的依旧不行, `TestBrowser` 没有给出mock api的解决办法

@chenshuai2144  需求来了
