### ISSUE TITLE
[Bug] say something

### ISSUE THREAD

**Issue by jiushigo01** [umijs/umi#9423]
## What happens?

max模式下设置prefixCls后样式混乱

## Mini Showcase Repository(REQUIRED)

1. 使用`yarn` + `create-umi` 新建项目，选择 `Ant Design Pro `模板

2. 在`.umirc.ts`中更改配置
```
...
  antd: {
    configProvider: {
      prefixCls: 'vpx',
    },
  },
  theme: { '@ant-prefix': 'vpx' },
...
```
3. yarn start 页面样式乱了

## Context

- **Umi Version**: @umijs/max 4.0.22
- **Node Version**: 16.15.1
- **Platform**: mac

**Comment by ywzou** [comment]
同样问题

**Comment by ywzou** [comment]
使用 "@umijs/max": "^4.0.24",
