### ISSUE TITLE
umi4编译速度如何分析、提升？

### ISSUE THREAD

**Issue by ELLEXSHEN** [umijs/umi#9424]
历史工程采用dva，积累200个model及对应的services，光这部分就是400多个文件，之前umi2时候编译速度最快，几十秒级编译，升级为umi3后是1分多钟的编译时间，但无法使用mfsu，因为mfsu经常出现问题，本来期待umi4的500ms的速度，但是，umi3升级为umi4之后，编译速度未见明显的提升，umi4编译时卡在src的扫描上，进度极慢，正常是1-2分钟的编译速度.
请问，各位大神，如何进行工程分析，提升编译速度，我也期待回到500ms的性能，感谢！！

**Comment by mushroomlb** [comment]
放到jenkins下慢慢编译吧，不报错就行了

**Comment by herbertxy** [comment]
超慢的，一直在bundling, network 里每个api/bundle-status 200-600B

**Comment by fz6m** [comment]
dva 已经多年不维护了，不推荐使用 dva 和 use-request ，现代数据流更推荐使用 [react-query](https://umijs.org/docs/max/react-query) / [swr](https://github.com/vercel/swr) 管理请求状态，用 [valtio](https://umijs.org/docs/max/valtio) / [jotai](https://github.com/pmndrs/jotai) 管理全局数据。
