### ISSUE TITLE
[Feature Request] 支持将处理ts|tsx的loader变更为ts-loader，ts-loader支持getCustomTransformers，通过该方法，可以在umi中使用@deepkit/type

### ISSUE THREAD

**Issue by MatrixAge** [umijs/umi#9425]
## Background

在一些业务场景场景（根据元数据也就是类型定义来渲染界面）下，需要提供运行时 类型 => 值 的能力，刚好之前在技术周报上看到过deepkit这个框架，他宣称的运行时类型能力，后来去研究了一下，发现它提供了@deepkit/type这个包，然后用tsc和ts-loader试了一下，是行得通的，它通过 @deepkit/type和@deepkit/type-compiler，在编译阶段注入额外类型信息来实现。

目前我的解决方案是，把一些需要使用的元数据在外部types项目下通过ts-loader打包之后，导出，然后主项目引入，这样有很多不方便的地方，虽然也能凑合着用，如果umi能提供这样的支持就再好不过了。目前umi的webpack-bundler部分主要使用的是babel-loader和esbuild。

另外，如果支持上述feature的话，umi自身的类型能力也能得到极大的加强，可以直接抛弃掉Jio了，typescript“一镜到底”！

运行时typescript类型，我觉得有很大的想象空间和广泛的使用场景，特别是在像低代码这样的领域，结合ts“类型体操”，我们可以延展出很多好的玩法和想法，对业务也会产生极大的帮助。

## Proposal

支持如下配置：

```ts
{
    useTsLoader?:{ options:{} }
}
```

## Additional context

deepkit运行时类型的一些介绍，这个方案依托typescript进行降维打击，完爆jio，zod这些第三方的类型库。

https://docs.deepkit.io/chinese/runtime-types.html

![image](https://user-images.githubusercontent.com/25472851/192068624-40d28957-05e5-42f1-9229-87209d663dea.png)

![image](https://user-images.githubusercontent.com/25472851/192068688-11d5defc-7293-4dff-a2ee-66efead2fa9f.png)

**Comment by fz6m** [comment]
```bash
  pnpm add -D ts-loader
```

```ts
// .umirc.ts

import tsImportPluginFactory from 'ts-import-plugin'

export default {
  chainWebpack(config: any) {
    config.module
      .rule('jsx-ts-tsx')
      .use('ts-loader')
      .loader(require.resolve('ts-loader'))
      .before('babel-loader')
      .options({
        transpileOnly: true,
        getCustomTransformers: () => ({
          before: [tsImportPluginFactory()],
        }),
      })
  },
}
```

**Comment by MatrixAge** [comment]
![image](https://user-images.githubusercontent.com/25472851/192361797-805a42a2-20f5-4130-8e6f-6b005a70438f.png)

![image](https://user-images.githubusercontent.com/25472851/192361889-83c9d4d6-852e-4044-bef1-a6e2b373bcd5.png)

![image](https://user-images.githubusercontent.com/25472851/192361943-89ac1db6-a7fe-4a99-abab-0508b0182205.png)

上述配置是after('babel-loader') 之后，可以看到，ts-loader的自定义transformer是生效了的，但是由于使用了tsyringe，所以引入了babel-plugin-transform-typescript-metadata来让依赖注入可用，但上述配置之后导致babel插件失效。

如果before('babel-loader')：

![image](https://user-images.githubusercontent.com/25472851/192363892-c58a649e-9fc0-44b1-901a-8c69c6f914c3.png)

看起来这种情况下完全不可用。

**Comment by MatrixAge** [comment]
![image](https://user-images.githubusercontent.com/25472851/192394721-96a1a9ba-b933-4a9e-a8eb-e73617638c54.png)

![image](https://user-images.githubusercontent.com/25472851/192394781-7edaead2-ac38-4bc8-b63d-10b41ea1918d.png)

确认是缺少metadata导致的报错（未使用ts-loader后置的情况下是引入 'babel-plugin-transform-typescript-metadata', import 'reflect-metadata'了的），使用ts-loader做为babel-loader后置之后，就出现了这种情况。

**Comment by fz6m** [comment]
给一个复现看看。

**Comment by MatrixAge** [comment]
https://github.com/MatrixAge/test-deepkit-compiler-with-umi

引起报错的点在这：

![image](https://user-images.githubusercontent.com/25472851/192576889-fff060c0-db55-42fd-b861-9bba29f13fcb.png)

**Comment by fz6m** [comment]
#### 1. Install dep

```bash
  pnpm add -D react-refresh-typescript 
```

#### 2. Modify `tsconfig.json`

```diff
{
	"extends": "./src/.umi/tsconfig.json",
	"compilerOptions": {
+		"experimentalDecorators": true,
+		"emitDecoratorMetadata": true
	},
	"reflection": true
}
```

#### 3. Create `src/global.ts`

```ts
// src/global.ts

import 'reflect-metadata'
```

Refer ：https://github.com/Microsoft/tsyringe#installation

#### 4. Config file

```ts
// .umirc.ts

import { defineConfig } from '@umijs/max'
import * as typeCompiler from '@deepkit/type-compiler'
import { join } from 'path'

export default defineConfig({
  chainWebpack(config: Config) {
    config.module
      .rule('jsx-ts-tsx')
      .use('ts-loader')
      .loader(require.resolve('ts-loader'))
      .after('babel-loader')
      .options({
        getCustomTransformers: () => ({
          before: [
            require('react-refresh-typescript')(),
            typeCompiler.transformer,
          ],
          afterDeclarations: [typeCompiler.declarationTransformer],
        }),
        configFile: join(__dirname, './tsconfig.json'),
      })
  },
})
```

#### 5. Clean cache

```bash
  rm -rf ./node_modules/.cache
```


注：`tsyringe` 、`@deepkit/type-compiler` 、`react-refresh-typescript` 等包都很脆弱，不保证以后项目复杂后不出现问题。

**Comment by MatrixAge** [comment]
👍 可以了，牛啊，虽然不懂为啥是react-refresh-typescript，但用了umi之后就从没自己折腾过太多配置了，被umi惯坏了。。。

另外，为什么非要整这么麻烦用上面这些“看起来还不稳定”的包，主要是我个人强迫症，喜欢代码整洁点（因为team太小，所以一肩挑所有，没有写单元测试的时间），工程架构上也整洁点，为的是极致的维护性和代码健壮性。

最开始写代码用原始redux，一堆“野生”的actions，代码dirty的不行。后来接触了umi，用上了dva，当时感觉是最好的方案，后来项目写多了，有一些项目很复杂，而dva和umi耦合严重，且都是页面级别的model，虽然dva能够给组件单独使用，但一个是文档，另一个是单独用就和redux差不多了，工程上没啥优势。

后来做了很长时间的调研，使用了一下jotai、zustand这些新兴的状态库，不够用，没法做到脱离react完全“数据驱动”（为什么要做到纯数据驱动，这个与我们业务有很大的关系），后来从Vue获得了灵感，用上了mobx，不得不说，维护class是真的爽多了，但工程上还是有很多依赖react的，跨模型数据共享不能依赖react的context，而且要写法上优雅，不能到处实例化，没法维护。

后来就参考了一下Angular，开始研究依赖注入的方案power-di、inversify这些，power-di太简单，满足不了某些场景，inversify啰里八嗦，不够简洁，最后还是tsyringe，更贴近java的一些语法和概念，更符合我的认知和使用喜欢。

脱离UI库，纯数据驱动是做大型前端项目的必要条件，这样通过架构把业务复杂度打平，把复杂度隐藏到数据模型里，离UI库远点，你不用纠结一些UI库本身的问题，后续业务扩展的时候，扩展数据模型就行了。

运行时类型，有两类，一类是validate，以ajv、joi、jsonschema为代表；另一类是io-ts、zod、yup这类比较完整的类型系统库。上述两类运行时类型库，只有第二类才能拥有全类型能力。

但是同时维护一个zod的类型object和ts相关类型定义，太啰嗦（虽然可以互转，但很多限制，用起来不行），冗余度爆炸，我强迫症，必须clean code，几个月前有了解过deepkit他们做的一些事情，就尝试一下，能不能直接使用ts运行时类型。

做工程就是平衡，平衡架构的健壮性和资源的稳定性，现在JS生态发展这么快，我相信都会有解决方案的。

只管用，只要能更好滴解决问题。
