### ISSUE TITLE
[Bug]umi4暗黑模式经常莫名其妙的就失效了，测试了半天也无法知道是什么引起的，一但失效，就怎样也无法起效了

### ISSUE THREAD

**Issue by su1924** [umijs/umi#9427]
## 暗黑模式经常莫名其妙的就失效了，测试了半天也无法知道是什么引起的，一但失效，就怎样也无法起效了

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by drizzlesconsin** [comment]
https://github.com/ant-design/ant-design-pro/issues/10151#issuecomment-1256887296
