### ISSUE TITLE
新拉项目 buld 打包时，指定 UMI_ENV 为 dev ， cross-env UMI_ENV=dev build , .umirc.prod.ts 会覆盖 dev 的环境配置

### ISSUE THREAD

**Issue by sumbyKB** [umijs/umi#9428]
"build:dev": "cross-env UMI_ENV=dev REACT_APP_ENV=dev umi build",
    "build": "umi build"
    
    在根目录新建
    .umirc.dev.ts
    .umirc.prod.ts
    
    执行 pnpm build:dev  的时候既走了 dev 配置，也走了 prod 配置

**Comment by fz6m** [comment]
See https://umijs.org/docs/guides/env-variables#umi_env

**Comment by sumbyKB** [comment]
对，现在我新建 prod 配置 会覆盖 dev 的配置，意思是不能指定 dev 只走 dev 的配置吗，是和 umi3 不一样了吗？umi4 目前是覆盖的状态
