### ISSUE TITLE
新拉项目 buld 打包时，指定 UMI_ENV 为 dev ， cross-env UMI_ENV=dev build , .umirc.prod.ts 会覆盖 dev 的环境配置 

### ISSUE THREAD

**Issue by sumbyKB** [umijs/umi#9429]
## What happens?

新拉项目 buld 打包时，指定 UMI_ENV 为 dev ，cross-env UMI_ENV=dev max build,  .umirc.prod.ts 会覆盖 dev 的环境配置 

## Mini Showcase Repository(REQUIRED)

[新拉项目新建就会复现](https://github.com/sumbyKB/testUmiEnv)

## How To Reproduce

    "build": "max build",
    "build:dev": "cross-env UMI_ENV=dev max build",

在根目录新建
.umirc.dev.ts
.umirc.prod.ts

执行 pnpm build:dev  的时候既走了 dev 配置，也走了 prod 配置

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/issues/9430
