### ISSUE TITLE
新拉项目 buld 打包时，指定 UMI_ENV 为 dev ，cross-env UMI_ENV=dev max build  , .umirc.prod.ts 会覆盖 dev 的环境配置

### ISSUE THREAD

**Issue by sumbyKB** [umijs/umi#9430]
## What happens?

新拉项目 buld 打包时，指定 UMI_ENV 为 dev ，cross-env UMI_ENV=dev max build,  .umirc.prod.ts 会覆盖 dev 的环境配置 

## Mini Showcase Repository(REQUIRED)

[新拉项目新建就会复现](https://github.com/sumbyKB/testUmiEnv)

## How To Reproduce

    "build": "max build",
    "build:dev": "cross-env UMI_ENV=dev max build",

在根目录新建
.umirc.dev.ts
.umirc.prod.ts

执行 pnpm build:dev  的时候既走了 dev 配置，也走了 prod 配置

**Comment by sumbyKB** [comment]
还是说有什么其他的方案，可以实现，根据不同环境去读取，对应的配置

**Comment by BENcorry** [comment]
可以仔细看这个部分：https://umijs.org/docs/guides/env-variables#umi_env

如果你想实现上面的需求，可以将.umirc.dev.ts 修改为 config.prod.dev.ts. .umirc.prod.ts 修改为 config.prod.prod.ts。将config文件放在{pwd}/config目录下
