### ISSUE TITLE
[Bug] umi 4.0.22 + pro-components 2.3.12  layouts下配置了index.tsx 菜单消失

### ISSUE THREAD

**Issue by Ruboyq** [umijs/umi#9434]
## What happens?
ant-design-pro的脚手架，umi 4.0.22 + pro-components 2.3.12，layouts下配置了index.tsx后菜单消失

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/Ruboyq/bugrepo

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
1. yarn
2. yarn start
3. admin登录 菜单消失
![image](https://user-images.githubusercontent.com/26861176/192217815-3ade2af4-4dcb-4914-844f-ba0f28310234.png)
![image](https://user-images.githubusercontent.com/26861176/192217974-40077ee2-dafb-4e3d-9777-266d8802c2b7.png)
脚手架新建的工程，改了下umi和pro-components版本，然后新增了layouts/index.tsx，菜单就消失了，其他什么都没改
因为之前工程通过这种方式在页面的最外面统一包了一层，之前的工程也都有这个问题

## Context

- **Umi Version**: 4.0.22
- **Node Version**:14.17.3
- **Platform**:mac
- **Pro-Components: 2.3.12

**Comment by SturdyCat** [comment]
Pro-Components 回退 2.3.11 就恢复正常

**Comment by Zila-itc** [comment]
> ## What happens?
> ant-design-pro的脚手架，umi 4.0.22 + pro-components 2.3.12，layouts下配置了index.tsx后菜单消失
> 
> ## Mini Showcase Repository(REQUIRED)
> > Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
> 
> https://github.com/Ruboyq/bugrepo
> 
> ## How To Reproduce
> **Steps to reproduce the behavior:** 1. 2.
> 
> 1. yarn
> 2. yarn start
> 3. admin登录 菜单消失
>    ![image](https://user-images.githubusercontent.com/26861176/192217815-3ade2af4-4dcb-4914-844f-ba0f28310234.png)
>    ![image](https://user-images.githubusercontent.com/26861176/192217974-40077ee2-dafb-4e3d-9777-266d8802c2b7.png)
>    脚手架新建的工程，改了下umi和pro-components版本，然后新增了layouts/index.tsx，菜单就消失了，其他什么都没改
>    因为之前工程通过这种方式在页面的最外面统一包了一层，之前的工程也都有这个问题
> 
> ## Context
> * **Umi Version**: 4.0.22
> * **Node Version**:14.17.3
> * **Platform**:mac
> * **Pro-Components: 2.3.12

+1

**Comment by fz6m** [comment]
我试了下，在最新版本没有这个问题了：

```diff
// package.json

+   "@ant-design/pro-components": "^2.3.30",
+   "@umijs/max": "^4.0.30",
```
