### ISSUE TITLE
[Feature Request] 如何单独渲染 /login 路由，而不是嵌套在 prolayout 里

### ISSUE THREAD

**Issue by Xekin97** [umijs/umi#9436]
## Background

场景：

![image](https://user-images.githubusercontent.com/25792845/192250764-17e38f67-6afa-4371-b1e2-ff1ea928eac7.png)

目前 /login 和 /regis，没有找到可以配置到 prolayout 之外的方法

## Proposal

可以将 layout 组件暴露在 /layouts/index.tsx 中，例如

```typescript
const Layout = ({ Wrapper }) => {
if (location.pathname === '/login') return <Outlet />
    return (
          <Wrapper>
            <Outlet />
          </Wrapper>
    )
}
```

**Comment by drizzlesconsin** [comment]
`layout: false`

**Comment by Xekin97** [comment]
> `layout: false`

如果这样的话，只能手写一遍 routes ，相应的菜单名称也不能使用自带的 locale 了。

**Comment by dayTimeAffect** [comment]
我也想了解，翻了很久文档，就必须在prolayout中

**Comment by xierenyuan** [comment]
layout: false 是指当前的路由配置 不走 layout 布局  可以看 这里  https://github.com/umijs/umi/blob/master/examples/ant-design-pro/config/routes.ts#L4

**Comment by dayTimeAffect** [comment]
> layout: false 是指当前的路由配置 不走 layout 布局 可以看 这里 https://github.com/umijs/umi/blob/master/examples/ant-design-pro/config/routes.ts#L4

我发现layout: false在umi4脚手架创建的项目，与antdPro脚手架创建的项目中有不同的表现。
在antdPro创建的项目中我就能自由的布局。

**Comment by zhansingsong** [comment]
> layout: false 是指当前的路由配置 不走 layout 布局 可以看 这里 https://github.com/umijs/umi/blob/master/examples/ant-design-pro/config/routes.ts#L4

文档中也没有记录 `layout: false` 属性啊，查看类型声明也没有记录。这个属性好随性，感觉只有维护人知道似的

**Comment by God-F** [comment]
如果使用约定式路由 有什么方法在某个路由禁用layouts吗？
