### ISSUE TITLE
支持运行时扩展路由数据

### ISSUE THREAD

**Issue by afc163** [umijs/umi#944]
鉴于之前在 Ant Design Pro 里有大量的提问是关于如何从后台读取路由、菜单、权限信息。现在菜单是放在 config 目录里的，不太容易和 dva model 层进行互动，官方应该有一个简单可操作的解决方案：

https://github.com/ant-design/ant-design-pro/issues/751
https://github.com/ant-design/ant-design-pro/issues/965
https://github.com/ant-design/ant-design-pro/issues/1306
https://github.com/ant-design/ant-design-pro/issues/1485
https://github.com/ant-design/ant-design-pro/pull/1290
https://github.com/ant-design/ant-design-pro/issues/1916
https://github.com/ant-design/ant-design-pro/issues/1861
https://github.com/ant-design/ant-design-pro/issues/1858
https://github.com/ant-design/ant-design-pro/issues/2049

**Comment by afc163** [comment]
最好能补充到 v2 的路由文档里去。

**Comment by sorrycc** [comment]
在 #1051 里跟进。
