### ISSUE TITLE
router.config.js 中无法使用 import 等 es 语法

### ISSUE THREAD

**Issue by afc163** [umijs/umi#945]
以及 JSX。

**Comment by afc163** [comment]
需求是 router.config.js 里的 icon 可以是 ReactNode

**Comment by ChieveiT** [comment]
@sorrycc 请问JSX语法可以支持了吗？相关commits没看到这个，我踩中这个坑了...

我在master分支追踪了一下代码，发现是[routesToJSON.js 23行使用了deepClone](https://github.com/umijs/umi/blob/774f498e687739c9b326f9446efab2021bfca963/packages/umi-build-dev/src/routes/routesToJSON.js#L23)，导致ReactElement对象被转成plainObject了，这问题看起来不太好搞。

因为为了更好看的动态加载写法，搞个router的预处理loader，大体是一条不归路。

我也做过类似的轮子，个人经验是基本不可能做到完整支持js语义，因为这就是个JSON反序列化和序列化的过程，plainObject就是边界，函数，类和对象，统统支持不了。要简单支持也可以，类似做个锚，字符串特征替换，强撸一波，但假的终究是假的，都有边界情况。它终究不是js，只是js中的plainObject。

所以我以前的做法是用yaml做路由定义，把特性框死在json这个范围，对，连变量也不支持...

所以如果它不是js，还是建议一开始就在文档告诉大家，它不是js。
