### ISSUE TITLE
valtio 怎么配置？真的是写的一手好文档啊 写得很牛逼 但是我看完不知道怎么用

### ISSUE THREAD

**Issue by hinego** [umijs/umi#9458]
## What happens?

看完文档后我很疑惑，应该怎么配置？

#### 基本用法
极其简单。

```
import { proxy, useSnapshot } from 'umi';
 
// 1、定义数据
const state = proxy({ count: 0 });
// 2、使用数据
const snap = useSnapshot(state);
snap.count;
// 3、更新数据
state.count += 1;
```
是啊 及其简单 ，但是你能不能把这代码放哪里提一下？

我真的服气。。。。。能做就做！不能做就算了，能不能别弄东西出来恶心人？

## How To Reproduce

https://umijs.org/docs/max/valtio#%E5%90%AF%E7%94%A8-valtio

## Context

node 19

**Comment by fz6m** [comment]
这个功能现在还没发布，预计会在本周四发布。

使用方法和 [valtio](https://github.com/pmndrs/valtio) 一致。现代全局状态管理库的使用方式和繁琐的旧时代已然不同，使用方法都十分简单，无需长篇说明。

供学习：

  - [valtio](https://github.com/pmndrs/valtio)

 - [jotai](https://github.com/pmndrs/jotai)
 
 - [recoil](https://github.com/facebookexperimental/Recoil)

 - [zustand](https://github.com/pmndrs/zustand)
