### ISSUE TITLE
生成的 router.js 包含多余的路由

### ISSUE THREAD

**Issue by 104gogo** [umijs/umi#946]
![image](https://user-images.githubusercontent.com/8522646/44838181-1b590900-ac6e-11e8-81e2-03c909409341.png)
问题如图，model.js 被添加到了 router.js 中。

在看 umi 的文档的时候，感觉引用的路径特别别扭，代码结构也比较疑惑，没有友好的体现出特定书写规律。

在此提个建议，希望 pages 中的每个组件文件夹中都包含一些特定的文件（可以支持自定义哪些是特定的文件），如：
```
ChildComponent.js // 子页面组件文件
ChildComponent // 子页面组件文件夹，目前的 components 有点累赘了
model.js
services.js
...
```
定义一个组件由上面的文件构成，每个组件都可以有个自己的 model.js 和 services.js，这样的目录结构感觉更加简单适用一点。

**Comment by sorrycc** [comment]
可以通过 https://umijs.org/plugin/umi-plugin-react.html#routes exclude 掉不需要的路由，参考 [antd-admin 的配置](https://github.com/zuiidea/antd-admin/blob/master/.umirc.js)。
