### ISSUE TITLE
[Bug] 使用scss报错

### ISSUE THREAD

**Issue by dingff** [umijs/umi#9462]
## What happens?

使用scss时启动报错
![image](https://user-images.githubusercontent.com/69964024/192957101-7505ec49-db2a-48bf-9aaa-3873f4957b52.png)

## Mini Showcase Repository(REQUIRED)

https://github.com/dingff/umi4-demo

## How To Reproduce

**Steps to reproduce the behavior:** 1. npm start

**Expected behavior** 1. 希望不报错

## Context

- **Umi Version**: 4.0.22
- **Node Version**: 14.19.1
- **Platform**: macOS 12.5.1

**Comment by xierenyuan** [comment]
我看看

**Comment by xierenyuan** [comment]
需要安装 sass 依赖 可以看 https://github.com/umijs/umi/blob/master/examples/with-sass/package.json#L15 这

**Comment by xierenyuan** [comment]
需要安装 sass 依赖 https://github.com/umijs/umi/blob/master/examples/with-sass/package.json#L15 可以看这

**Comment by dingff** [comment]
好的，可以考虑修正下文档哈
![image](https://user-images.githubusercontent.com/69964024/192962334-779a32ec-379b-4439-a9c8-4264b52ae772.png)

**Comment by xierenyuan** [comment]
> 好的，可以考虑修正下文档哈 ![image](https://user-images.githubusercontent.com/69964024/192962334-779a32ec-379b-4439-a9c8-4264b52ae772.png)

感谢反馈 我更新下
