### ISSUE TITLE
在运行时app.ts ，如何取路径？

### ISSUE THREAD

**Issue by lecd** [umijs/umi#9467]
1.我的项目是部署在非根目录下，在配置必须上base。
在运行时app.ts 取路径时， 使用 import { history } from '@umijs/max';
const { location } = history; 返回的pathname 加上非必要的base，需要做路径判断都要加上base这一级，太难了。

2.运行时app.ts 不允许使用hooks， const location = useLocation();

![image](https://user-images.githubusercontent.com/17017158/192973907-b1249181-2ae8-4e23-8ec2-93f8c0aaa685.png)

© 版本信息
![image](https://user-images.githubusercontent.com/17017158/192973951-c2645c7c-d39a-4d82-98e2-d247993370a1.png)

**Comment by fz6m** [comment]
```ts
import { history } from '@umijs/max'

// 从 `history.location` 中获取路径信息
history.location
```

**Comment by xiaofuliang** [comment]
遇到同样的问题，使用history.location会带base，很苦恼

**Comment by AtLastDopamine** [comment]
老铁们，有没有什么办法可以拿到 [配置信息](https://umijs.org/docs/api/config#alias)。
因为我是分了环境的，我想拿到最终合成后的配置。例如：base

**Comment by fz6m** [comment]
作为环境变量注入进去，定义在 [define](https://umijs.org/docs/api/config#define) 里。
