### ISSUE TITLE
[Bug] 开启mpa后，global.scss不生效

### ISSUE THREAD

**Issue by dingff** [umijs/umi#9470]
## What happens?

开启mpa后，global.scss不生效
![image](https://user-images.githubusercontent.com/69964024/192980973-cc3f59f3-ceb9-4ced-b683-171f6c646027.png)

## Mini Showcase Repository(REQUIRED)
https://github.com/dingff/umi4-demo

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0.22
- **Node Version**: 14.19.1
- **Platform**: macOS 12.5.1

**Comment by fz6m** [comment]
`global.scss` 不支持 mpa ，在 layout 中引入吧。

**Comment by dingff** [comment]
layout 里怎么引入啊

**Comment by fz6m** [comment]
1. Create layout `src/layouts/index.tsx` :

```ts
// src/layouts/index.tsx

import './index.scss'

export default function Layout(props: any) {
  return props.children
}
```

```scss
// src/layouts/index.scss

// ... some styles
```

2. Create mpa page config file `src/index/config.json` :

```ts
// src/index/config.json

{
  "layout": "@/layouts/index"
}
```

参考：https://umijs.org/docs/guides/mpa#%E5%85%A5%E5%8F%A3%E6%96%87%E4%BB%B6%E9%85%8D%E7%BD%AE
