### ISSUE TITLE
[Bug] umi4 login页面title不能正常显示

### ISSUE THREAD

**Issue by Teeoo** [umijs/umi#9475]
## What happens?

login页面title不能正常显示
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
```ts
export const routes = [
  {
    path: '/auth',
    layout: false,
    routes: [
      {
        path: '/auth/login',
        component: './auth/login',
      }
    ],
  },
  {
    name: '智慧工厂',
    path: '/factory',
    routes: [
      {
        name: '生产管理',
        path: '/factory/production',
        access: 'FactoryProduction',
        routes: [
          {
            name: '检查清单',
            path: '/factory/production/Checklist',
            component: './factory/production/check-list',
            access: 'FactoryProductionChecklist',
          },
          {
            name: '产品分类',
            path: '/factory/production/category',
            component: './factory/production/category',
            access: 'FactoryProductionCategory',
          }
        ]
      },
    ]
  }
];

```
**Expected behavior** 1. 2.

## Context

- **Umi Version**:4.0.22
- **Node Version**:16.4
- **Platform**:win10

**Comment by Hexi1997** [comment]
我也

**Comment by Teeoo** [comment]
@fz6m [https://codesandbox.io/s/intelligent-gates-kgzb2u?file=/.umirc.ts](https://codesandbox.io/s/intelligent-gates-kgzb2u?file=/.umirc.ts)

**Comment by fz6m** [comment]
到 antd-pro 反馈吧，https://github.com/ant-design/ant-design-pro

暂时的解决办法可以自己设置标题：https://ahooks.js.org/zh-CN/hooks/use-title

**Comment by Teeoo** [comment]
@fz6m 这个不应该是umi的问题么,咋去pro那边

**Comment by haohuaZhang** [comment]
<img width="716" alt="image" src="https://github.com/umijs/umi/assets/126741760/a0df8d41-9e84-4f1b-ab75-709a39760b08">
