### ISSUE TITLE
[Bug] 给二级路由配置上wrappers后，菜单中没有渲染该路由

### ISSUE THREAD

**Issue by qq79952008** [umijs/umi#9479]
## 问题描述
在二级路由中配置上wrappers属性后，菜单无法渲染该路由

![image](https://user-images.githubusercontent.com/29473553/193230083-428bedd3-41e0-4d0c-9978-59198b3f41d2.png)
![image](https://user-images.githubusercontent.com/29473553/193230150-b3dca577-c32d-4560-8943-4085a4c7058b.png)
![image](https://user-images.githubusercontent.com/29473553/193230310-962eec4a-cc3f-4aa9-ae5d-00c38affef70.png)

## 复现代码
https://github.com/qq79952008/umi-wrapper-test

**Comment by fz6m** [comment]
到这里反馈吧：https://github.com/ant-design/pro-components/tree/master/packages/components

**Comment by fz6m** [comment]
最新版本已经解决了这个问题：

```diff
// package.json

  "dependencies": {
+   "@ant-design/pro-components": "^2.3.30",
+   "@umijs/max": "^4.0.30"
  }
```

```diff
// .umirc.ts

    {
      name: ' 一级路由',
      path: '/route',
-     component: './Table',
      routes: [
        {
          name: ' 二级路由1',
          path: '/route/test1',
          component: './Table',
          // 去掉这一行菜单就会正常展示
          wrappers: ['@/wrappers/Wrapper.tsx'],
        },
        {
          name: ' 二级路由2',
          path: '/route/test2',
          component: './Table',
        },
      ],
    }
```

**Comment by junlin365** [comment]
一级菜单也有这个bug，真就不多测一下呀。。。
