### ISSUE TITLE
[Bug] js使用link标签导入的本地css文件无法找到

### ISSUE THREAD

**Issue by QWYZ** [umijs/umi#9480]
## What happens?
**js使用link标签动态导入的本地css文件时，css文件无法找到**

**具体如下图：**
![1664613040493](https://user-images.githubusercontent.com/61998381/193400679-f8098c97-0ddd-4e91-a4d4-0ce7b12d47bd.png)

![1664612476282](https://user-images.githubusercontent.com/61998381/193400303-4606ee3d-2e05-4403-9bfb-5e1530f3bd32.png)

## Mini Showcase Repository(REQUIRED)

>  [最小重现：https://github.com/QWYZ/umi4-test-case](https://github.com/QWYZ/umi4-test-case)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
这样加载 css 是不对的，如果需要懒加载，请使用：

1. Create `src/components/style.tsx` :

```ts
// src/components/style.tsx

import '../assets/test.css';

export default function Style() {
  return null;
}
```

2. Lazy import style component :

```ts
// src/pages/Home/index.tsx

import React, { useState } from 'react';

const LazyStyle = React.lazy(() => import('@/components/style'));

const HomePage: React.FC = () => {
  const [show, setShow] = useState(false);

  return (
    <PageContainer ghost>
      {/* ... */}
      <Button
        onClick={() => {
          setShow(true);
        }}
      >
        点击
      </Button>
      {show && (
        <React.Suspense>
          <LazyStyle />
        </React.Suspense>
      )}
      {/* ... */}
    </PageContainer>
  );
};
```

或是将 `test.css` 作为静态资源放入 `public` 文件夹，再根据路径导入（这种方式需要自己考虑 `publicPath` 、css 的浏览器兼容性）。

**Comment by QWYZ** [comment]
@fz6m  感谢大佬指导^_^
