### ISSUE TITLE
@umijs@4 doesn't support exportStatic

### ISSUE THREAD

**Issue by cwtuan** [umijs/umi#9481]
## What happens?
In "@umijs/max": "^4.0.24", use `exportStatic` in config.
```
> max build

fatal - AssertionError [ERR_ASSERTION]: Invalid config keys: exportStatic
```

## Mini Showcase Repository(REQUIRED)
https://github.com/umijs/umi/

## How To Reproduce
1. config:
```
 ssr: {
  },
  exportStatic: {
    htmlSuffix: true
  },
```
2. npm run build

## Context

- **Umi Version**:
```
"@umijs/max": "^4.0.24"
```
- **Node Version**:
v14.19.2
- **Platform**:
mac

**Comment by fz6m** [comment]
See https://github.com/umijs/umi/issues/8617

**Comment by cwtuan** [comment]
I give up using `umi.js@4` since it doesn't support SSG (Static Site Generation).
[Next.js](https://nextjs.org/docs/basic-features/data-fetching/get-static-paths) would be one of the alternatives.

**Comment by RobelChina** [comment]
期待···

**Comment by xiaohuoni** [comment]
https://github.com/umijs/umi/pull/9602
