### ISSUE TITLE
[Bug] v4 配置 base 后 ，history 命令式路由跳转出错，没有过滤掉 base 设置

### ISSUE THREAD

**Issue by satanrabbit** [umijs/umi#9484]
## What happens?

在 umijs v4 设置路由 base后，再通过 **history.push** 或 **history.replace** 方法进行路由跳转时，总会在路由下增加 base 目录。
例如 base 设置为 `app` ,默认页面 会正确进入 `http://localhost:8000/app/` ,但是通过 `history.push('/docs')` 时路由会变成 `http://localhost:8000/app/app/docs`

这个问题好像在前几个版本上 Link 上也存在，升级最新版本后 Link 的路由跳转没有问题，但是 history 仍然存在。

## Mini Showcase Repository(REQUIRED)

使用 umi 初始化简简单项目后，按照下方代码修改  `.umirc.ts` 和 `/src/layouts/index.tsx` 即可复现

.umirc.ts
```` 
export default {
  base: `app`,
  npmClient: 'yarn'
};
````
`/src/layouts/index.tsx`
````
import { Link, Outlet,history } from 'umi';
import styles from './index.less';

export default function Layout() {
  return (
    <div className={styles.navs}>
      <ul><li><Link to="/">Home</Link></li>
        <li><Link to="/docs">Docs</Link></li>
        <li><a onClick={()=>{ history.push('/docs');}}>Push Docs</a></li>
        <li><a onClick={()=>{ history.replace('/docs');}}>Replace Docs</a></li>
        <li><a href="https://github.com/umijs/umi">Github</a></li>
      </ul>
      <Outlet />
    </div>
  );
}
````

出现问题的 `pakage.json`:
````
{
  "private": true,
  "author":"SatanRabbit <satanrabbit@gmail.com>",
  "scripts": {
    "dev": "umi dev",
    "build": "umi build",
    "postinstall": "umi setup",
    "setup": "umi setup",
    "start": "npm run dev"
  },
  "dependencies": {
    "umi": "^4.0.24"
  },
  "devDependencies": {
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "typescript": "^4.1.2"
  }
}
````
> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

**Comment by fz6m** [comment]
```ts
  base: '/app'
```

**Comment by satanrabbit** [comment]
> 

有效，谢谢！

**Comment by satanrabbit** [comment]
> ```ts
>   base: '/app'
> ```

有效，谢谢~！
