### ISSUE TITLE
[有偿1000] 有大佬可以把 midway & umi 结合起来吗？

### ISSUE THREAD

**Issue by 18583952605** [umijs/umi#9485]
需要了解 midway 这个框架的，就知道我说的结合是什么意思~~~
就是midway前后端一体化的那种

可以的大佬联系下，这个比较难，有偿(500 - 1000)求
ps: 我自己搞了好久，没有搞定
希望大佬们帮帮忙~

**Comment by xiaohuoni** [comment]
https://github.com/midwayjs/midway-serverless-examples/tree/master/integration/react

**Comment by 18583952605** [comment]
@xiaohuoni  不行哇 这个是react的   想用umi的 它们差距还挺大的  不好改
