### ISSUE TITLE
[Bug] umi 4 运行时配置中 patchRoutes 早于 render 执行

### ISSUE THREAD

**Issue by elton11220** [umijs/umi#9486]
## What happens?

我计划在app.tsx中 export function render 并在该函数中获取服务器的路由列表，获取到路由列表后执行 patchRoutes 进行动态路由配置。
经过实践，patchRoutes 函数中得到的由 render 函数赋值的 路由列表 始终为 null / undefined。
经过测试发现 patchRoutes 的执行 早于 render，导致无法在 render 获取路由数据后在 patchRoutes 中进行 merge

![图片](https://user-images.githubusercontent.com/46066977/193623803-c04436c6-d00b-4890-9890-b60cb7c20312.png)

![图片](https://user-images.githubusercontent.com/46066977/193623715-26efe145-d0b3-40ea-9dd8-79aa8409a089.png)

查看umi源代码后，怀疑以下代码导致该现象发生：
[https://github.com/umijs/umi/blob/82e81a7772e04516423305885966e9012d257a73/packages/preset-umi/templates/umi.tpl#L16-L33](https://github.com/umijs/umi/blob/82e81a7772e04516423305885966e9012d257a73/packages/preset-umi/templates/umi.tpl#L16-L33)

首先会 await patchRoutes，执行后才会继续执行 render

在umi 3环境下测试，函数执行顺序正常：

render -> patchRoutes

![图片](https://user-images.githubusercontent.com/46066977/193623510-654c408f-4891-4d42-9174-aa07adb92f05.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

[https://github.com/elton11220/umiissue/blob/master/src/app.tsx](https://github.com/elton11220/umiissue/blob/master/src/app.tsx)

## How To Reproduce

**Steps to reproduce the behavior:**
1. 使用 pnpm dlx create-umi 命令，simple 模板创建 umi 4 项目
2. 创建 app.tsx
3. 输入上段中相关代码
4. 运行后输出
```
patchRoutes
render
```

**Expected behavior** 
输出
```
render
patchRoutes
```
在执行 render 函数时从服务器获取到路由数据赋值给全局变量，执行 patchRoutes 并 mergeRoutes 实现动态路由

## Context

- **Umi Version**: 4.0.24
- **Node Version**: 16.17.0
- **Platform**: windows

**Comment by fz6m** [comment]
可以用 initial state 等全局状态，获取到服务端 routes 列表前不渲染或者 loading 即可。

**Comment by elton11220** [comment]
> 可以用 initial state 等全局状态，获取到服务端 routes 列表前不渲染或者 loading 即可。

umi 提供的 getInitialState 方法发生于 render 后且需要在 render 中调用 oldRender 才可以继续执行 getInitialState

patchRoutes -> render --(oldRender)--> getInitialState

![图片](https://user-images.githubusercontent.com/46066977/193713451-3a78ecdc-3013-4f66-b09b-b12e65cac0a6.png)

我在 global.ts 中发送请求实现了想要的效果

![图片](https://user-images.githubusercontent.com/46066977/193717196-c7121f21-64a0-44e2-ac63-24a3636135a5.png)

但patchRoutes 发生在 render 前这一现象属于umi4的特性还是bug

**Comment by fz6m** [comment]
需要在 render 后执行的是 [patchClientRoutes](https://umijs.org/docs/api/runtime-config#patchclientroutes-routes-)

**Comment by a992681784** [comment]
@fz6m 请教下如何实现登录后根据从服务器拿到的路由配置，动态注册子应用和配置路由？

**Comment by fz6m** [comment]
动态添加路由表的例子：https://github.com/umijs/umi/discussions/9717#discussioncomment-4078053

**Comment by a992681784** [comment]
> 

谢谢解答 但是我没完全看懂  app.tsx是在刚进页面就会执行，我点击登录之后是不会执行app.tsx里的代码的，这个应该处理呢？

**Comment by fz6m** [comment]
1. 第一次没有权限 -> 跳转到登录页。

2. 登录完成后会赋予 cookie / auth 等唯一标识到本地，登录成功后刷新页面。

3. 第二次进入有权限 -> 在 render 前，请求接口就获取到了这个人的路由表，跳转到你想要的页面即可。

注：如果是 sso 登录，无权的情况应该跳到 sso 登录。

**Comment by a992681784** [comment]
> 1. 第一次没有权限 -> 跳转到登录页。
> 2. 登录完成后会赋予 cookie / auth 等唯一标识到本地，登录成功后刷新页面。
> 3. 第二次进入有权限 -> 在 render 前，请求接口就获取到了这个人的路由表，跳转到你想要的页面即可。
> 
> 注：如果是 sso 登录，无权的情况应该跳到 sso 登录。

再次非常感谢你的解答 我理解了 我之前没往这方面想是因为 我之前的做法是登录后直接路由跳转到内容页，而不是刷新整个页面。刷新整个页面或多或少会给用户产生一些突兀感。
再次致谢！

**Comment by a992681784** [comment]
@fz6m 请问下，发到生产环境后 子应用无法正常响应主应用的路由是什么原因？开发环境是正常的 能够正常响应。
我的主子应用都是umi4。
···
path: '/pedestal',
  component: './PedestalApp',
  routes: [
    {
      path: '/pedestal/*',
      microApp: 'pedestal',
      microAppProps: {
        // base: '/pedestal',
        autoSetLoading: true,
        wrapperClassName: 'microAppWrapperCls',
      },
    },
  ],
···

**Comment by fz6m** [comment]
多给些上下文信息帮助判断问题，配置，报错，表现，最小复现。

nginx 配置是否正确，加载地址是否正确等。

**Comment by a992681784** [comment]
> 多给些上下文信息帮助判断问题，配置，报错，表现，最小复现。
> 
> nginx 配置是否正确，加载地址是否正确等。

不好意思，描述起来有点复杂，我晚点整理下。我大概说下情况。
主子应用都是部署在非根目录下，我都已经配好了base和publicPath，主子应用单独跑起来都是正常的，可以访问对应的路由。现在是在主应用加载子应用时，主应用的路由切换成功，但是子应用没有匹配，但是我看到子应用的地址是加载成功了的。然后开发环境是正常的，没有这个问题。
路由都是采用BrowserHistory Nginx都配置了 重定向到index.html。
（生产环境的图死活传不上来了。。。也是子应用地址加载成功了，但是子应用内容区域是空的）

![image](https://user-images.githubusercontent.com/20497118/204787650-b137462b-2ba6-4ee3-8302-6021fd2eb7b5.png)

**Comment by a992681784** [comment]
> 多给些上下文信息帮助判断问题，配置，报错，表现，最小复现。
> 
> nginx 配置是否正确，加载地址是否正确等。

@fz6m  不好意思，描述起来有点复杂，我晚点整理下。我大概说下情况。
主子应用都是部署在非根目录下，我都已经配好了base和publicPath，主子应用单独跑起来都是正常的，可以访问对应的路由。现在是在主应用加载子应用时，主应用的路由切换成功，但是子应用没有匹配，但是我看到子应用的地址是加载成功了的。然后开发环境是正常的，没有这个问题。
路由都是采用BrowserHistory Nginx都配置了 重定向到index.html。
（生产环境的图死活传不上来了。。。也是子应用地址加载成功了，但是子应用内容区域是空的）

![image](https://user-images.githubusercontent.com/20497118/204787650-b137462b-2ba6-4ee3-8302-6021fd2eb7b5.png)

**Comment by a992681784** [comment]
![0C7C71F8-426D-4914-B00A-98E181AB6C20](https://user-images.githubusercontent.com/20497118/204791055-601e1f7b-2168-47f7-8c2b-9ea5bf44d9a7.png)

**Comment by a992681784** [comment]
@fz6m 我看文档上，通过路由绑定子应用的方式子应用会自动匹配路由。
![image](https://user-images.githubusercontent.com/20497118/204791926-2ea09c12-8d64-4589-a11c-76f82dd5d755.png)

**Comment by a992681784** [comment]
@fz6m 主要是也没有什么任何报错

**Comment by a992681784** [comment]
@fz6m 
![image](https://user-images.githubusercontent.com/20497118/204794637-b098bb8e-209f-43e3-9314-f8e9b9719957.png)

**Comment by fz6m** [comment]
感觉是路由匹配问题，在路由路径匹配上多寻找下问题吧，没有匹配出来路由，这个这么长的路径，从这个角度排查下。

**Comment by a992681784** [comment]
> 感觉是路由匹配问题，在路由路径匹配上多寻找下问题吧，没有匹配出来路由，这个这么长的路径，从这个角度排查下。

好的 谢谢
我这边主应用部署在服务器非根目录/app/base/下，子应用在/app/sub1/下，分别配置了主子应用的base和publicPath为/app/base/,/app/sub1。请问下这样部署有问题吗？
主子应用的路由应该怎么进行匹配？我根据文档教程试了通过basename传递主应用的前缀到子应用，然后想调setCreateHistoryOptions方法设置子应用的路由。但是发现max里没有setCreateHistoryOptions这个方法。
![image](https://user-images.githubusercontent.com/20497118/204944268-cb7ef2c4-743c-4dab-a70f-6299a2477988.png)

**Comment by fz6m** [comment]
`base` 应该是网页 url 上的 `pathname` 前缀部分

比如 `http://domain.com/a/b/c/d/e/app/base` ，你的 `base` 应该从 `/a/b/c ...` 开始到应用根页面的路径位置

**Comment by elton11220** [comment]
> @elton11220 你是如何解决这个问题的？

我把代码放到 global.ts(x) 里面了，这里的会最先执行

**Comment by xXAvoraXx** [comment]
> > @elton11220 你是如何解决这个问题的？
> 
> 我把代码放到 global.ts(x) 里面了，这里的会最先执行 @xXAvoraXx

你能检查下面的代码吗？
https://github.com/ant-design/ant-design-pro/discussions/10898

下面我找到了一个关于 umi3 动态路由的插件。 我目前正在尝试编写一个从 api 调用路由的插件。
https://github.com/exvu/umi-plugin-dynamic-route

**Comment by colansd** [comment]
> 1. 第一次没有权限 -> 跳转到登录页。
> 2. 登录完成后会赋予 cookie / auth 等唯一标识到本地，登录成功后刷新页面。
> 3. 第二次进入有权限 -> 在 render 前，请求接口就获取到了这个人的路由表，跳转到你想要的页面即可。
> 
> 注：如果是 sso 登录，无权的情况应该跳到 sso 登录。

要刷新页面有点难受，不顺滑了 @fz6m
