### ISSUE TITLE
[Bug] Do not see the images for `Technology convergence` and `Plugins and plugin sets`

### ISSUE THREAD

**Issue by nitinreddy3** [umijs/umi#9487]
## What happens?
Do not see the images that are responsible to describe the following
- Technology convergence
- Plugins and plugin sets
![How-Umi-Works](https://user-images.githubusercontent.com/5886208/194237090-30a8d36d-054c-4707-bf5b-3aa1c8ca116d.png)

## How To Reproduce

**Steps to reproduce the behavior:** 
- Navigate to `https://v3.umijs.org/docs/how-umi-works` 
- Check for the images under `Technology convergence` and `Plugins and plugin sets`
- The images are broken

**Expected behavior**
The images shall show up.

**Comment by fz6m** [comment]
<img src='https://user-images.githubusercontent.com/59400654/194290413-e1779538-e90d-460f-850c-ae8c2e8f1fea.png' width='60%' />

work for me, check your network ?

**Comment by nitinreddy3** [comment]
Not sure if the CDN is blocked in India. I tried accessing the images from different browsers and devices and still get the images broken. Seems that the CDN might not accessible in my region.
