### ISSUE TITLE
react18 umiji集成qiankun微前端时，子应用内使用history.push跳转路由会自动带上子应用的package-name

### ISSUE THREAD

**Issue by Godguns** [umijs/umi#9493]
react18 umiji集成qiankun微前端时，子应用内使用history.push跳转路由会自动带上子应用的package-name
复现步骤
![image](https://user-images.githubusercontent.com/46049685/194703229-00b2602b-f17b-4bb2-8e37-47973424c00a.png)
![image](https://user-images.githubusercontent.com/46049685/194703250-2ef32a8e-3136-456f-9ca9-5cf35bb773bd.png)
umi版本"umi": "^3.5.26",
react版本  "18.1.0",

**Comment by a992681784** [comment]
遇到了同样的问题 有解决办法了吗
