### ISSUE TITLE
[Bug] antd table和protable 的filter过滤下拉框没有重置和确定按钮

### ISSUE THREAD

**Issue by XueMeijing** [umijs/umi#9501]
不知道其他人碰到过没有，也懒得弄复现仓库了，在这里记录下，其他人碰到这个问题了可以试试

原因貌似是umi的config设置国际化无效, 最起码对这个问题无效
```
locale: {
  default: 'zh-CN',
  antd: true,
  // default true, when it is true, will use `navigator.language` overwrite default
  baseNavigator: true,
},
```

antd下拉框的代码是这样的，找不到locale所以显示空白
```
<div className={`${prefixCls}-dropdown-btns`}>
  <Button type="link" size="small" disabled={getResetDisabled()} onClick={() => onReset()}>
    {locale.filterReset}
  </Button>
  <Button type="primary" size="small" onClick={onConfirm}>
    {locale.filterConfirm}
  </Button>
</div>
```

在table外面加一层ConfigProvider下拉框的重置按钮就正常显示了
```
<ConfigProvider locale={zhCN}>
  <Table />
</ConfigProvider>
```

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: "umi": "^3.5.0"   "antd": "^4.21.4",
- **Node Version**:
- **Platform**:

**Comment by BENcorry** [comment]
遇到类似的问题，不过需要在umi4下的locale配置中添加添加如下配置即可
```ts
 locale: {
    antd: true,
  },
```
