### ISSUE TITLE
[Bug] [plugin-access] 更新权限后菜单未同步更新

### ISSUE THREAD

**Issue by cc7gs** [umijs/umi#9502]
## What happens?
![权限演示 - @umijs_max](https://user-images.githubusercontent.com/36002392/194767201-1d571f09-645e-4e82-b12c-24652c5a4994.gif)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

[https://github.com/cc7gs/umi-access-demo/commit/c0cbd3869aa02b0e823c5f43d2322a7292ad65a7](https://github.com/cc7gs/umi-access-demo/commit/c0cbd3869aa02b0e823c5f43d2322a7292ad65a7)

## How To Reproduce
**Steps to reproduce the behavior:** 

1. 在 `access` 文件设置权限，下文中`canSeeHome`
```ts
export default (initialState: IInitialState) => {
  return {
    canSeeHome: initialState.canSeeHome,
  };
};
```
2. 在页面更改上文定义的`canSeeHome`值
```ts
import { PageContainer } from '@ant-design/pro-components';
import { useModel } from '@umijs/max';
import { Button } from 'antd';

const AccessPage: React.FC = () => {
  const { initialState, setInitialState } = useModel('@@initialState');
  return (
    <PageContainer
      ghost
      header={{
        title: '权限示例',
      }}
    >
      <pre>{JSON.stringify(initialState)}</pre>
      <Button
        onClick={() => {
          setInitialState({
            ...initialState!,
            canSeeHome: !initialState?.canSeeHome,
          });
        }}
      >
        改变Home页面权限
      </Button>
    </PageContainer>
  );
};

export default AccessPage;

```
**Expected behavior** 1. 2.

点击将 `canSeeHome` 值改为 false 后，如下图1 内部已经将为 unaccessible 改为 true,但是最终输出如图2，还是未标记的

**图一：**
<img width="1291" alt="截屏2022-10-10 00 29 51" src="https://user-images.githubusercontent.com/36002392/194768399-3807c775-f4e7-4ac6-9828-c93f14d9b5dc.png">

**图二：**
<img width="1018" alt="截屏2022-10-10 00 30 36" src="https://user-images.githubusercontent.com/36002392/194768441-687030c3-897a-4bb1-98f5-7d0561ceb319.png">

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by jiazhuangle** [comment]
我也遇到同样的问题，我是换不同权限人登录，菜单显示的不对，刷新一下页面就对了

**Comment by xiaorong61** [comment]
我也遇到了

**Comment by vominhtrius** [comment]
I have the same problem with @jiazhuangle. Has anyone solved this problem?

**Comment by leftstick** [comment]
不是plugin-access的bug。

 如果是prolayout的功能的话，那大概率就是pro-layout 里的bug了。
 
我没用prolayout，布局是自己写的，更新没有问题

**Comment by jiazhuangle** [comment]
确实如 @leftstick  所说，试了一下，把pro版本改成2.0 问题就没有了  

> "@ant-design/pro-components": "^2.0.0"

@vominhtrius

**Comment by chenwei-p** [comment]
> 

我也是自己写的布局，但是一旦在 .umirc.ts 中 开启layout`layout: {}` ，就会跟随layout的侧边栏布局，这时候路由中的权限是生效的，无权限时会会出现layout的权限错误页面。我不想要layout的侧边栏，请问改如何配置呢？umi4.0.13

**Comment by cc7gs** [comment]
> 

1. layout权限错误页面，可以在 `layout: { noAccessible: <>无权限展示</>} ` 
2. 如果你不需要菜单渲染，可以通过 查看文档进行配置，proLayout会把这些属性透传进去 https://procomponents.ant.design/components/layout#%E8%87%AA%E5%AE%9A%E4%B9%89-menu-%E7%9A%84%E5%86%85%E5%AE%B9

**Comment by chenwei-p** [comment]
> 
昨天是因为我写了两个文件app.ts和app.tsx，导致app.tsx不生效，现在没问题了，谢谢

**Comment by xiaofeisss** [comment]
> 我也遇到同样的问题，我是换不同权限人登录，菜单显示的不对，刷新一下页面就对了

兄弟  同样的问题  你解决了吗？
