### ISSUE TITLE
本地引入mp4会报错

### ISSUE THREAD

**Issue by chunyangyang** [umijs/umi#9505]
## What happens?
本地引入的mp4文件无法加载

![image](https://user-images.githubusercontent.com/20843521/194797930-0defd294-a738-4c51-9bea-f24de9a4df9b.png)
[demo](https://github.com/chunyangyang/umi-mp4-demo/tree/main)

**Comment by sorrycc** [comment]
umi 3 不支持 mp4，需要自己写 webpack 配置实现。

**Comment by chunyangyang** [comment]
能否提供一个示例呢
