### ISSUE TITLE
引入本地mp4文件会报错

### ISSUE THREAD

**Issue by chunyangyang** [umijs/umi#9507]
## What happens?
根据文档安装后，运行正常，但是当我把本地mp4文件引入进来就报错了

## Mini Showcase Repository(REQUIRED)

[最小重现](https://github.com/chunyangyang/umi-mp4-demo/tree/main)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
1.安装好依赖
2.运行 npm start

错误信息
```js
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ./src/pages/index.tsx 5:0-38 23:15-20
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./node_modules/umi/node_modules/@umijs/preset-built-in/bundled/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./src/.umi/umi.ts
```
## Context

- **Umi Version**:3.5.34
- **Node Version**:16.14.2
- **Platform**:web

**Comment by sorrycc** [comment]
umi 3 需要通过 chainWebpack 配置自行配置这类文件的 loader。

**Comment by chunyangyang** [comment]
> i 3 需要通过 chainWebpack 配置自行配置这类文件的 loa
看了文档，还是没配置出来，可以提供示例代码吗

**Comment by chunyangyang** [comment]
可以有一段代码告知怎么配置吗
