### ISSUE TITLE
[Bug] umi4 Nested locale string ids do not work as shown in examples

### ISSUE THREAD

**Issue by jwmann** [umijs/umi#9514]
## What happens?

Using Nested Locale ids do not work, only non-nested ids work.

e.g.:
```
id: 'foobar' // Works
id: 'foo.bar' // Does not work
```

## Mini Showcase Repository(REQUIRED)

CodeSandbox:  
https://codesandbox.io/s/umijs-4-max-nested-locale-not-working-8jif5z

GitHub Repo:  
https://github.com/jwmann/umi4-nested-locale-broken

## How To Reproduce

**Steps to reproduce the behavior:** 
Try and use any nested localized string

**Expected behavior**
Nested ids work like they do in examples (https://umijs.org/docs/max/i18n#%E6%A0%BC%E5%BC%8F%E5%8C%96%E5%AD%97%E7%AC%A6%E4%B8%B2)

## Context

- **Umi Version**:  4.0.24 (latest)
- **Node Version**: v16.17.1 (lts/gallium)
- **Platform**: Chrome

**Comment by hanzebang** [comment]
Nested message objects are no longer supported since react-intl v2. Reference https://formatjs.io/docs/react-intl/upgrade-guide-2x/#flatten-messages-object

**Comment by hanzebang** [comment]
We'll fix the documentation later
