### ISSUE TITLE
[Bug] umi4 build编译后包含swagger-ui-dist代码导致浏览器兼容问题

### ISSUE THREAD

**Issue by lovewinders** [umijs/umi#9516]
## What happens?
umi4执行npm run build编译后dist代码包含swagger-ui-dist编译后代码，生产环境不应该存在swagger-ui代码

查看dist内umi.xxx.js文件内会包含swagger-ui-dist的代码，该代码内有??操作符（nullish-coalescing-operator）导致360极速最新浏览器无法识别??符号，页面出现白屏
> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库
![image](https://user-images.githubusercontent.com/22837419/195277968-c5788e6c-cc9a-4bf0-988a-8379640b3e65.png)
![image](https://user-images.githubusercontent.com/22837419/195277992-744cb03d-f2d4-47ac-b1c7-f558b47bdb45.png)

## Mini Showcase Repository(REQUIRED)
https://github.com/ant-design/ant-design-pro

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

第一步：使用最新版本antd pro最新master代码
第二步：执行npm run build编辑命令
第三步：分析dist里umi.xxx.js编译后的文件即可看到上述截图问题

## Context

- **Umi Version**:"@umijs/max": "^4.0.17"
- **Node Version**:16.13.1
- **Platform**:mac/window

**Comment by sorrycc** [comment]
用 extraBabelIncludes 配置额外需要做 Babel 编译的 NPM 包或目录，参考 https://umijs.org/docs/api/config#extrababelincludes 。
