### ISSUE TITLE
[umijs/plugins] 建议升级 umi 的同时把 umijs/plugins 中的依赖版本也升级一下

### ISSUE THREAD

**Issue by hqwlkj** [umijs/umi#9525]
例：
本地安装了  @ant-design/pro-components 新的包后，新的工却使用不了

```
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ @ant-design/pro-components@2.3.17
└─ @umijs/plugins@4.0.20
   └─ @ant-design/pro-components@2.3.7
✨  Done in 1.56s.

```

**Comment by fz6m** [comment]
如果安装了 `@ant-design/pro-components` 会优先使用用户安装的 `@ant-design/pro-components` 版本。

**Comment by hqwlkj** [comment]
如果能同步更新那不是更好吗😄

**Comment by fz6m** [comment]
`@umijs/plugins` 依赖的 `@ant-design/pro-components` 没有锁版本，这与你第一次初始化项目时 `@ant-design/pro-components` 的最新版本有关。

如果锁死，会导致升级 umi 时 `@ant-design/pro-components` 被意外提升版本，会造成  Breaking change ，如需新版本时，用户应该自己管理。

**Comment by hqwlkj** [comment]
> 果锁死，会导致升级 umi 时 `@ant-design/pro-components` 被意外提升版本，会造成 B

好吧
