### ISSUE TITLE
[Bug] wrappers中使用model,state不更新

### ISSUE THREAD

**Issue by loser1046** [umijs/umi#9526]
## What happens?

wrappers路由检验未通过,查询原因为:
在model中使用useState定义的user信息未被更新成功,如果在此处user信息换为let普通定义,则能通过

项目中使用如下:

首先在model中定义用户信息:
![image](https://user-images.githubusercontent.com/22904669/195761615-fa9ef38c-3472-42b2-9777-1d0b5e560780.png)

在登陆步骤做用户信息更新:
![image](https://user-images.githubusercontent.com/22904669/195761704-a2c2ffdb-1ac3-4507-ba22-290df20fbb2c.png)

 在路由中使用wrappers做状态检查:
![image](https://user-images.githubusercontent.com/22904669/195761789-70c1f9c4-e5a0-4b89-b0d8-3ed59219c56a.png)

## Mini Showcase Repository(REQUIRED)

> https://github.com/loser1046/umi-app

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

1. 启动项目进入login页面,
![image](https://user-images.githubusercontent.com/22904669/195762359-199798ad-6b1c-4288-91c6-1ed81735f823.png)

2. 点击登录即可查看,更新user信息前后,该值都为空
![image](https://user-images.githubusercontent.com/22904669/195762541-382130f2-f398-4315-ba5f-a4ca60ac9844.png)

**Expected behavior** 1. 2.
预期为:登录后更新用户信息,拿到的user最新信息为登录返回的用户信息

## Context

- **Umi Version**:4.0.24
- **Node Version**:v16.14.2
- **Platform**:Windows

**Comment by loser1046** [comment]
有没有大佬能解答一下我的疑惑,难道是我使用方法有问题吗?

**Comment by fz6m** [comment]
react 18 里 `setState` 是异步的，会 auto batch 合并， 如果需要保持同步，可以用 [`flushSync`](https://react.dev/reference/react-dom/flushSync) 自己设定同步 `setState` 的逻辑。

先关闭了，如最新版本还有问题，再提一个新的 issue 给一个最小复现吧。
