### ISSUE TITLE
2.0 require global.less bug

### ISSUE THREAD

**Issue by wgwxf** [umijs/umi#953]
1.环境:
系统： windows 10，
"umi": "^2.0.0-beta.20"

2.问题
tyarn start生成的.umi/umi.js里global.less引用如下：
require('..\..\global.less');
导致无法启动

3.期望
require('../../global.less');

**Comment by soolx** [comment]
![17761535630088_ pic](https://user-images.githubusercontent.com/7274864/44850222-1f495300-ac8f-11e8-92f7-f63c7c2aae0d.jpg)
![17811535630154_ pic](https://user-images.githubusercontent.com/7274864/44850225-207a8000-ac8f-11e8-9692-7a9a0ab6323d.jpg)
有同样问题，`\g`被转译
