### ISSUE TITLE
[Bug] 升级umi4后umi中的dynamic没有了？

### ISSUE THREAD

**Issue by qingfengmy** [umijs/umi#9530]
## What happens?

```
import { dynamic } from 'umi'

export default dynamic({
  async loader() {
    // 这里的注释 webpackChunkName 可以指导 webpack 将该组件 HugeA 以这个名字单独拆出去
    const { default: Upload } = await import(/* webpackChunkName: "Upload" */ './upload');
    return Upload;
  },
  loading: PageLoading,
});
```
之前某一个组件如果太大需要单独打包，通过上面的代码可以实现。升级umi4后，提示 dynamic没有导出。

**Comment by fz6m** [comment]
现在的手动拆包方法见：[umi4-我怎么分包](https://umijs.org/docs/introduce/faq#umi4-%E6%88%91%E6%80%8E%E4%B9%88%E5%88%86%E5%8C%85)

**Comment by a992681784** [comment]
@fz6m 请问下umi4 getInitialState从服务端获取数据时间比较久怎么添加loading？我看antd pro里是可以配置的，但是umi4不支持这样配置。
https://pro.ant.design/zh-CN/docs/title-landing#%E4%B8%9A%E5%8A%A1%E4%B8%AD%E7%9A%84%E5%8A%A0%E8%BD%BD

**Comment by fz6m** [comment]
```ts
// .umirc.ts

export default {
  initialState: {
    // loading 组件的路径，这里是 src/components/loading.tsx
    loading: '@/components/loading'
  }
}
```
