### ISSUE TITLE
[Bug] umi3.5文档上的api没法导出。

### ISSUE THREAD

**Issue by zl802925** [umijs/umi#9536]
![1665972279992(1)](https://user-images.githubusercontent.com/82135011/196074214-f5ba86fc-14af-4298-ae1c-687e44053ca0.jpg)
如上图所示，我在本地用脚手架建了一个umi的项目，但是却无法导出useNavigate这个api但是文档中写着是可以导出这个api的呀。请各位大佬指点一下这是咋回事呢

**Comment by fz6m** [comment]
`useNavigate` 是 react router v6 的 api ，你确定看的是 umi v3 的文档吗？

 - [v3 文档](https://v3.umijs.org/)

**Comment by zl802925** [comment]
> `useNavigate` 是 react router v6 的 api ，你确定看的是 umi v3 的文档吗？
> 
> * [v3 文档](https://v3.umijs.org/)

已经解决了，我之前的脚手架我看安装的是3版本的umi.js，然后我看3版本的文档，发现好多api不能用，怀疑是版本的问题，然后重新创建了一个项目，umi是4版本，然后在用v3文档的api发现就可以使用了。
