### ISSUE TITLE
[Bug] 默认的 /404 路由似乎并不存在

### ISSUE THREAD

**Issue by jiangkaifree** [umijs/umi#9537]
## What happens?

umi4 在 dev 下 似乎并不存在 `/404` 路由页面。

按着 [快速开始](https://umijs.org/docs/tutorials/getting-started) 创建了项目，访问 `/404` 并不存在。按着官方文档 [目录结构](https://umijs.org/docs/guides/directory-structure#srcpages404js) 讲解，dev 模式下应当会有默认的 404 页面，但实际似乎并没有。 下面是控制台打印
![image](https://user-images.githubusercontent.com/50451924/196079879-9ef43dd2-e11e-4a17-a26a-938bcd896f82.png)。 

复现demo中是umi v4.0.25 , 另外 4.0.24 似乎有着相同的问题，下面是我新创建项目的 `package.json` 的相关信息：

```js
  "dependencies": {
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "^2.0.1",
    "@umijs/max": "^4.0.25",
    "antd": "^4.20.7"
  },
```

```js
// umirc.ts

import { defineConfig } from '@umijs/max';

export default defineConfig({
  antd: {},
  access: {},
  model: {},
  initialState: {},
  request: {},
  layout: {
    title: '@umijs/max',
  },
  routes: [
    {
      path: '/',
      redirect: '/home',
    },
    {
      name: '首页',
      path: '/home',
      component: './Home',
    },
    {
      name: '权限演示',
      path: '/access',
      component: './Access',
    },
    {
        name: ' CRUD 示例',
        path: '/table',
        component: './Table',
    },
  ],
  npmClient: 'pnpm',
});
```

## Mini Showcase Repository(REQUIRED)
最小demo
[Github](https://github.com/jiangkaifree/umiTest)

## How To Reproduce

1.  按着 [快速开始](https://umijs.org/docs/tutorials/getting-started) 创建新项目。使用 pnpm 
2.  运行 `pnpm dev`， 访问 `/404` 路由，页面空白。控制台输出 `No routes matched location "/404"` 。

**Comment by fz6m** [comment]
`src/404.tsx` 页面仅在 约定式 路由下生效，如果自己指定 `routes` 路由表，需要自己配置 404 页面路由：

```ts
export default {
  routes: [
     {
        name: '404',
        path: '/*',
        component: '@/pages/404.tsx'
     }
  ]
}
```

**Comment by cat-kun** [comment]
> `src/404.tsx` 页面仅在 约定式 路由下生效，如果自己指定 `routes` 路由表，需要自己配置 404 页面路由：
> 
> ```ts
> export default {
>   routes: [
>      {
>         name: '404',
>         path: '/*',
>         component: '@/pages/404.tsx'
>      }
>   ]
> }
> ```

搞定，可以解决
