### ISSUE TITLE
关于 .umirc.js文件中的proxy问题。 在项目中，用serve运行起来已经没有再代理去'http://jsonplaceholder.typicode.com/'

### ISSUE THREAD

**Issue by zibuyu69** [umijs/umi#954]
运行

npm run bulid
npm i serve -g
cd dist
serve
发现项目可以启动，但是有个问题
![image](https://user-images.githubusercontent.com/37107112/44848321-e312f400-ac88-11e8-8ea9-c4d933325908.png)

关于 .umirc.js文件中的proxy问题
在项目中，用serve运行起来已经没有再代理去'http://jsonplaceholder.typicode.com/'，求问该怎么去配置

#

**Comment by sorrycc** [comment]
给可重现的库，发我或者传到 github 上。

**Comment by zibuyu69** [comment]
你好，我直接下载的是你的教程代码https://github.com/sorrycc/blog/issues/62

**Comment by zibuyu69** [comment]
你好，我直接下载的你的教程代码https://github.com/umijs/umi-dva-user-dashboard

**Comment by xiaohuoni** [comment]
build之后本来就不工作的吧！proxy

**Comment by zibuyu69** [comment]
啊谢谢，新手许多常识性的东西都不清楚的·····
