### ISSUE TITLE
[Bug] 当设置 dataField 后，useRequest 类型推导错误

### ISSUE THREAD

**Issue by StephenPCG** [umijs/umi#9543]
## What happens?

在 config.ts 中设置了：

```ts
export default {
    request: {
        dataField: "",
    }
}
```

在代码中：

```ts
// service.ts
import { request } from "@umijs/max"

export function getFoo() {
    return request<{id: number}>("/api/foo")
}

// component.ts
import { useRequest } from "@umijs/max"

function foo() {
    const { data } = useRequest(service.getFoo)  // <= 这里的 data 推导类型为 unknown
}
```

命中的类型声明在 `src/.umi/plugin-request/request.ts` 中：

```ts
type ResultWithData< T = any > = { data?: T; [key: string]: any };

function useRequest<R extends ResultWithData = any, P extends any[] = any>(
  service: CombineService<R, P>,
  options?: BaseOptions<R['data'], P>,
): BaseResult<R['data'], P>;
```

## 补充说明

在 umi 3 中不存在这个问题。umi 3 使用 `@umijs/plugin-request`，生成 `request.ts` 的代码中会根据 `dataField` 配置修改上述类型声明，代码在这里：

https://github.com/umijs/plugins/blob/c8c2fa28ca09dd5c8169e3e955547aef11c2e470/packages/plugin-request/src/index.ts#L97-L98

```ts
      api.writeTmpFile({
        path: winPath(join(namespace, 'request.ts')),
        content: requestTemplate
          .replace(/\/\*FRS\*\/(.+)\/\*FRE\*\//, formatResultStr)
          .replace(/\['data'\]/g, dataField ? `['${dataField}']` : '')
          .replace(/data\?: T;/, dataField ? `${dataField}?: T;` : '')
          ...
      });
```

在 umi 4 中，request plugin 的代码直接内置，这部分代码没有做同样的处理。代码在这里：

https://github.com/umijs/umi/blob/1c4b2310401d8a21e2c77aa1a54df73b582b1d6e/packages/plugins/src/request.ts#L300-L307

建议修复方式，增加 umi3 中相似的处理逻辑。

**Comment by xiaorong61** [comment]
我也遇到这个问题了

**Comment by fz6m** [comment]
#9747 这个 PR 是不是解决这个问题了，升级到最新 umi 版本（`4.0.41`）再尝试下。

**Comment by StephenPCG** [comment]
经验证，`4.0.41` 已解决该问题。

**Comment by lzm0x219** [comment]
这个问题又来了

**Comment by katoto** [comment]
在4.0.69 也会，推导多了一层data,，是啥原因

**Comment by purple-force** [comment]
4.0.81 未设置dataField，也多了一层 data
<img width="650" alt="image" src="https://github.com/umijs/umi/assets/16146970/e6ed1893-6e20-483f-ae48-5bba04ca2b83">

**Comment by weilun0510** [comment]
useRequest 不能在判断语句或函数中使用吗？感觉在函数组件内顶部使用的场景比较少

**Comment by fz6m** [comment]
`useXXX` 是 react 中 hook 的命名约定，必须只能在组件或者其他 hook 的顶层使用，同时遵循 react 的一些基本规定，其中一条限制是不可以在条件中使用。如果需要在函数中发起请求，可以使用 `request` 这个请求函数方法，但他不包含状态管理且不能解决竟态问题，一般情况下，无论如何查询请求（RUD请求除外）都应该在 hook 中发送以解决静态问题。

**Comment by weilun0510** [comment]
帮忙看下这种情况
https://github.com/umijs/umi/discussions/12068
