### ISSUE TITLE
antd input 受控模式下在umi的 models存input的value和change时中文输入不了

### ISSUE THREAD

**Issue by QDyanbing** [umijs/umi#9544]
### Reproduction link

[https://github.com/QDyanbing/antd-input](https://github.com/QDyanbing/antd-input)

### Steps to reproduce

在输入框中输入 "测试"

### What is expected?

可以输入中文

### What is actually happening?

不能输入中文

| Environment | Info |
| --- | --- |
| antd | 4.23.6 |
| React | ^18.0.0 |
| System | mac |
| Browser | 106.0.5249.119（正式版本） (arm64) |

**Comment by sorrycc** [comment]
和 umi 也无关，把 useModel 替换成 useState 一样有问题。建议 google 下「input 受控 输入中文」。

参考：
https://www.tangshuang.net/7840.html
https://github.com/suhaotian/react-input

**Comment by QDyanbing** [comment]
我换成useState是没问题的，可以正常输入中文；按照上面的方案确实可以修复在useModel中的使用；反馈到antd那边得到如下回馈https://github.com/ant-design/ant-design/issues/38081

**Comment by zhupp034** [comment]
遇到同样的问题，使用v3版本是没有问题的，v4的plugin-model有问题

**Comment by zhupp034** [comment]
react18版本的问题，换成17就没问题了

**Comment by YanSheng1127** [comment]
> 和 umi 也无关，把 useModel 替换成 useState 一样有问题。建议 google 下「input 受控 输入中文」。
> 
> 参考： https://www.tangshuang.net/7840.html https://github.com/suhaotian/react-input

建议你试一下

**Comment by 54huanan** [comment]
> 遇到同样的问题，react18版本的问题，换成17就没问题了。但是普通useState在17和18都没有问题，还是useModel的plugin有问题的
原来用useState的写法能正常工作，换成useModel就不能输入中文了。
问下怎么降到React17的？
Umi4的很多插件都使用18了。

**Comment by fz6m** [comment]
不推荐继续使用 useModel 、useRequest 、dva 等 umi 3 原保留的数据方案，这些是为了升级而保留的上古遗留，现代数据流更推荐使用 [jotai](https://github.com/pmndrs/jotai) / [valtio](https://umijs.org/docs/max/valtio) 管理全局状态，使用 [react-query](https://umijs.org/docs/max/react-query) / [swr](https://github.com/vercel/swr) 管理请求状态。
