### ISSUE TITLE
[Bug] 按照文档快速安装 antd 启动服务报错

### ISSUE THREAD

**Issue by helloLance** [umijs/umi#9563]
## What happens?
按照 https://umijs.org/docs/tutorials/getting-started 快速创建项目
是用yarn 创建antd 项目
执行yarn dev  报错

Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

照着文档都起不来服务。。。。。

## Context
![Uploading iShot_2022-10-20_00.22.28.png…]()

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by Agr-0Z** [comment]
同上使用官方的命令工具，写了一个页面就报这个错误，但有时候重新start一下又好了再start一下就又报这个错了，同时还有Uncaught TypeError: Cannot read properties of null (reading 'useContext')这个错误存在。
