### ISSUE TITLE
[Bug] umi4 simple初始化使用antd

### ISSUE THREAD

**Issue by Lpbzzz** [umijs/umi#9564]
```
 npmClient: 'pnpm',
  plugins: [
    '@umijs/plugins/dist/antd',
  ],
  antd: {},
```
用这个config时，引入antd使用报错
![image](https://user-images.githubusercontent.com/28721487/196757851-9c68b044-c4f8-4c56-8f00-ddad3c0e68d9.png)

example 
https://github.com/Lpbzzz/_umi.git

**Comment by sorrycc** [comment]
你好，已修复。

**Comment by GitAlphabet** [comment]
遇到同样问题，没后续了？

**Comment by Lpbzzz** [comment]
> 遇到同样问题，没后续了？

云谦回复说修复了，然后我删掉依赖重新装确实没报错了
