### ISSUE TITLE
[Bug] 更新umi后项目启动报错

### ISSUE THREAD

**Issue by qjekingstar** [umijs/umi#9568]
## What happens?
node_modules/@playwright 报 Module not found: Error: Can't resolve 'v8'

## How To Reproduce

npm i @ant-design/pro-cli -g
pro create myapp

? 🐂 使用 umi@4 还是 umi@3 ? (Use arrow keys)
❯ umi@4
  umi@3

cd myapp
yarn install
yarn start

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
暂时的解决办法：

 - 删除 `src/e2e` 目录

@stormslowly 可以看下这个问题，mfsu 收集了测试文件 `baseLayout.e2e.spec.ts` 的依赖，错误包含了 `playwright` 的样式（复现方法如上文中所述，使用 pro 脚手架创建一个 pro 项目）

**Comment by stormslowly** [comment]
```
mfsu: {
exclude: ['playwright']
}
```
这样可以不编译进 远端模块，先绕过

我提个 PR 把 `*.spec.(ts|js|jsx|tsx)` 也 ignore 起来，
