### ISSUE TITLE
[Bug] 使用npx create-umi@latest 创建的项目无法运行

### ISSUE THREAD

**Issue by mgu-x** [umijs/umi#9569]
### 环境
```text
node: v14.18.2
nvm: v6.14.15
```
### 问题
我在使用官方提供的[命令](https://umijs.org/docs/max/introduce#:~:text=%E5%9C%A8%E4%BD%BF%E7%94%A8%20create%2D-,umi,-%E9%80%89%E6%8B%A9%20Ant%20Design)创建基础项目，使用`npm run dev`并不能运行项目，我发现在控制台有许多问题。

## Mini Showcase Repository(REQUIRED)

这个是我上传的[案例](https://github.com/mgu-x/umi-example)

## Context

- **Umi Version**: 4.0.25
- **Node Version**: 14.18.2
- **Platform**:Mac Pro

**Comment by zhouzhounice** [comment]
我也遇到这个问题了

**Comment by benlypan** [comment]
#9562

**Comment by Lpbzzz** [comment]
#9564

**Comment by zjfresh** [comment]
mfsu 在umi@4.0.25 切换到默认 strategy eager 了，等待4.0.26发版吧

**Comment by poyiding** [comment]
同样的问题

**Comment by mgu-x** [comment]
好的 谢谢
