### ISSUE TITLE
[Feature Request] getUserConfig输出错误信息

### ISSUE THREAD

**Issue by Gumplefik** [umijs/umi#9572]
## Background

jest启动报错没有具体错误信息，实际上就是TS的类型检查错误，但是没有输出错误具体信息，就很难排查修复

## Proposal
```
static getUserConfig(opts) {
    let config = {};
    let files = [];
    for (const configFile of opts.configFiles) {
      if ((0, import_fs.existsSync)(configFile)) {
        import_utils.register.register({
          implementor: import_esbuild.default
        });
        import_utils.register.clearFiles();
        try {
          config = import_utils.lodash.merge(config, require(configFile).default);
        } catch (e) {
         //   提供开关输出详细错误信息或者默认打开
          console.log(e);
          throw new Error(`Parse config file failed: [${configFile}]`, {
            cause: e
          });
        }
        for (const file of import_utils.register.getFiles()) {
          delete require.cache[file];
        }
        files.push(...import_utils.register.getFiles());
        import_utils.register.restore();
      } else {
        files.push(configFile);
      }
    }
    return {
      config,
      files
    };
  }
```

## Additional context

![image](https://user-images.githubusercontent.com/19474332/196875744-dc0d8650-3aa0-477c-9543-4f5151aca192.png)

**Comment by fz6m** [comment]
给一个最小复现看看。

**Comment by Yyunfan** [comment]
同问题，也是debug到这个函数，require根路径.umirc.ts文件会报错就跳到catch了，控制台就同样输出Failed to parse the Typescript config.

![image](https://github.com/umijs/umi/assets/11605443/90aba962-487d-4ebb-80f6-3612dfb73ada)

**Comment by Yyunfan** [comment]
在重现最小showcase过程中，发现把.umirc.ts文件的配置删到足够精简，才能不出现报错。一旦.umirc.ts有chainWebpack、plugins、externals、mf 等复杂配置就会报错

**Comment by fz6m** [comment]
需要给一个会报错的最小复现才能帮助排查问题。

**Comment by killdada** [comment]
也出现了这个问题，这个问题在window下有，再服务器linux正常

**Comment by killdada** [comment]
window10
![image](https://github.com/umijs/umi/assets/16487810/f5a95e51-2bfd-4d9b-894a-8cf27353363d)
linux

**Comment by fz6m** [comment]
node 是什么版本的。

**Comment by killdada** [comment]
> node 是什么版本的。

都是 16.10.0

**Comment by fz6m** [comment]
删除 `node_modules` 重装一遍依赖试试吧。

**Comment by killdada** [comment]
> 删除 `node_modules` 重装一遍依赖试试吧。

重装试了下正常
