### ISSUE TITLE
[Bug] 设置 base 后，history.location.pathname  会携带 base ?

### ISSUE THREAD

**Issue by olvvlo** [umijs/umi#9581]
https://github.com/umijs/umi/blob/master/examples/ant-design-pro/src/app.tsx#L38

设置 config.ts

```ts
base: '/demo/'
```

代码中获取 history.location.pathname 会携带 base

history.location.pathname => '/demo/user/login'

**Comment by xartd** [comment]
[#9529](https://github.com/umijs/umi/pull/9529)

**Comment by fz6m** [comment]
目前的不一致出现在当配制了 `base` 时，`history` 和 react-router 的 `useLocation` 这俩方法能获取到的 pathname 不一致，因为 react-router 是内部的，不包含 base ，而 history 是全局的，包含 base 。

这个问题已经存在很久了，再改会有 Breaking change ，所以自己注意下吧，可以通过 define 注入 base 值然后自己 trim 掉，或者复写一下 history 方法都可以。
