### ISSUE TITLE
build后任何页面都无限请求 /__umi_ping 后并刷新

### ISSUE THREAD

**Issue by hinego** [umijs/umi#9589]
build后任何页面都无限请求 /__umi_ping 后并刷新

**Comment by hinego** [comment]
https://github.com/umijs/umi/search?q=%2F__umi_ping

**Comment by hinego** [comment]
https://github.com/umijs/umi/search?q=%2F__umi_ping

**Comment by shanhexi** [comment]
Motherfucker, I had the same problem

**Comment by yang-chuanjiang** [comment]
=请问这个后面怎么解决的

**Comment by xiaohuoni** [comment]
@yang-chuanjiang 给个复现看看
