### ISSUE TITLE
webpack-bundle-analyzer  will prevent other webpack plugin

### ISSUE THREAD

**Issue by ouxu** [umijs/umi#96]
When I edit the `webpack.config.js` to add some plugin, but some of them didn't work well. For example, `qiniu-webpack-plugin` will prevent by `webpack-bundle-analyzer`. 
Can add an API to custom the `webpack-bundle-analyzer` such as `analyzerMode`?

**Comment by sorrycc** [comment]
Do you specify the process.env.ANALYZE env variable? webpack-bundle-analyzer is only included when process.env.ANALYZE is true.

**Comment by ouxu** [comment]
In production env, I hope both the `webpack-bundle-analyzer` and my custom plugin take use. So I set the ANALYZE=1, and add my plugin in `webpack.config.js`, but my plugin have been prevented by `webpack-bundle-analyzer`.
And I just read the source code in `af-webpack`, I think the  `webpack-bundle-analyzer` should use in the latest, just after other plugin take use. See #97
