### ISSUE TITLE
请问你后来怎么解决的？我也遇到了同样的问题

### ISSUE THREAD

**Issue by shanzheng1991** [umijs/umi#9605]
请问你后来怎么解决的？我也遇到了同样的问题

_Originally posted by @xieyt203 in https://github.com/umijs/umi/issues/7839#issuecomment-1245064195_

**Comment by xiaohuoni** [comment]
有疑问回复跟进，不要发这种奇怪的 issues

**Comment by shanzheng1991** [comment]
> 有疑问回复跟进，不要发这种奇怪的 issues

咋奇怪了？我是在跟进和提问啊。我的确遇到这个问题了。无法解决啊。

**Comment by xiaohuoni** [comment]
@shanzheng1991 你的标题和详情看不出什么信息。就跟遇到问题一直发 issues，“为什么不行啊”，“为什么这样啊”，“出错啦”这种没有什么意义。

**Comment by shanzheng1991** [comment]
哥，是显示问题吗？我是跟在这个问题后面的啊。https://github.com/umijs/umi/issues/7839。这个问题，标题，详情，原因，错误提示，都很清晰啊。
