### ISSUE TITLE
修改主题色不生效

### ISSUE THREAD

**Issue by cdx0512** [umijs/umi#9613]
umi版本：4.0.24.

**Comment by lx815** [comment]
我在app.tsx的layout里面配置了colorPrimary就生效了。

**Comment by cdx0512** [comment]
> 我在app.tsx的layout里面配置了colorPrimary就生效了。

layout里面是不是只对侧边栏生效

**Comment by lx815** [comment]
> > 我在app.tsx的layout里面配置了colorPrimary就生效了。
> 
> layout里面是不是只对侧边栏生效

我是整个项目都生效了，我的是umi4搭的max项目。然后antd是用的V5版本的
