### ISSUE TITLE
[Bug] 路由更改，触发dev server重启时，端口号自动 + 1

### ISSUE THREAD

**Issue by RainThinks** [umijs/umi#9623]
## What happens?

修改路由后，触发Dev Server自动重启，端口号总是自动+1。
推测是重启时，前一个进程尚未释放端口，后一个进程已经被启动，检测到了端口冲突。

<img width="615" alt="image" src="https://user-images.githubusercontent.com/1291788/197923707-1991ab75-8b66-4b49-bc09-d4b9f14e6f15.png">

## Mini Showcase Repository(REQUIRED)

使用最新pro-cli创建新项目即可重现。
https://github.com/ant-design/ant-design-pro.git

## How To Reproduce

1. npm run start启动dev server
2. 修改config/routes.ts文件并保存
3. 此时可以看到dev server自动尝试在原端口重启，但新启的dev server实际端口号+1了。

**Expected behavior**

应该正常在原端口号启动

## Context

- Umi v4.0.24
- Node v16.18.0
- MacOS 12.6 (arm)

**Comment by xierenyuan** [comment]
未能复现问题, 可以提供更多信息吗

**Comment by RainThinks** [comment]
```
npm i @ant-design/pro-cli -g
pro create myapp
select umi@4
cd myapp
yarn
yarn start
```

编辑routes.ts，删除 /user 这条路由，保存。
此时服务自动尝试在8000端口重启，但应该是检测到8000端口被占，重新启动在了8001端口。
<img width="614" alt="image" src="https://user-images.githubusercontent.com/1291788/201943035-73fec1d6-928a-4584-93b0-a55599e93c21.png">

将上述修改撤销并保存，服务再次自动重启，且端口号+1。
<img width="754" alt="image" src="https://user-images.githubusercontent.com/1291788/201943393-79541bab-0bc0-41dc-a824-1262a8c49020.png">

手动关闭服务，手动再次启动服务，成功在8000端口启动。说明端口未被其他服务占用。
<img width="637" alt="image" src="https://user-images.githubusercontent.com/1291788/201943718-d18f1ed0-bb22-4bf5-bdcb-4434130fc2ea.png">

我们团队所有人都是这样，都是M1 Pro CPU的MBP。

**Comment by fz6m** [comment]
我没有这个问题，检查下机器的代理配置？是不是占用了

**Comment by RainThinks** [comment]
> 我没有这个问题，检查下机器的代理配置？是不是占用了

确定没有占用。我这有3台MBP，系统设置各不相同，都能稳定重现上述步骤。

**Comment by fz6m** [comment]
在这个帖子里，有多人在不同网络环境、不同设备上都不能复现。

故可以确认下，你那边的多台机器是不是在一个网络环境里，和网络环境有关？在家里的电脑上创建一个新项目再复现一下？

如果也不是网络环境问题，可以二分排查下，只修改 `routes` 会导致这个问题，还是任意的配置？如果只是 `routes` ，是那部分 `routes` ，是不是和特殊的 `routes` 写法有关，可以排查下，提供更多信息帮助排查。

**Comment by zaleweb** [comment]
@fz6m 我这里遇到，更改router和config都会触发端口+1
修改src文件夹下的好像不会触发

系统也是mac m1芯片

**Comment by zaleweb** [comment]
@fz6m 刚才用window电脑试了一下，也会重启8000端口，重启后端口号没+1

是不是mac m1或者最新的系统有关系？

**Comment by zaleweb** [comment]
> 

同一个项目

**Comment by fz6m** [comment]
win 应该没问题，我的设备是 mac intel 12.6 。

现在没有 m1 设备，没法测试 m1 。

**Comment by zaleweb** [comment]
> 个 stick

@stormslowly 如何搞

**Comment by RainThinks** [comment]
各种自动重启都会出现同样的情况，修改config，修改routes等。
重现使用的代码是完全无修改的ant design pro脚手架代码，不存在特殊写法。

我们团队都在不同的地方远程办公，macOS版本也不太一样，环境配置也有些许差别。唯一共同点，就是使用M1芯片的MBP，怀疑和这个有关。

我的主观推测和 @stormslowly 和一样，是"forkedDevServer kill 端口还没有马上释放，新起来的 devServer 就换了端口"
