### ISSUE TITLE
[Bug] 版本升级后，主题色变暗了

### ISSUE THREAD

**Issue by 429299291** [umijs/umi#9624]
主题色一直没变，现在颜色变暗了一点点，怎么处理
而且，我发现配置的主题色，生成后，和真实的颜色有点出入
<img width="323" alt="image" src="https://user-images.githubusercontent.com/29189973/197926751-f218a7d0-b4db-44f7-b46b-cc07cb3d423b.png">

**Comment by drizzlesconsin** [comment]
两个值都试试看
```ts
// config/config.ts
theme: {
  'root-entry-name': 'default',
  // 'root-entry-name': 'variable',
}```

**Comment by 429299291** [comment]
很感谢，可以了，@drizz

**Comment by 429299291** [comment]
本地可以啦，但是发布后，颜色失效了

**Comment by 429299291** [comment]
> 两个值都试试看
> 
> ```ts
> // config/config.ts
> theme: {
>   'root-entry-name': 'default',
>   // 'root-entry-name': 'variable',
> }```
> ```


本地可以啦，但是发布后，颜色失效了
