### ISSUE TITLE
[Bug] umi关闭mfsu后，启动项目报错

### ISSUE THREAD

**Issue by wcleye** [umijs/umi#9626]
## What happens?

使用umijs 集成 lowcode-engine 项目时，在 .umirc.js 文件中设置 mfsu: false 时，打开页面报错：
![image](https://user-images.githubusercontent.com/1748091/197959631-6aeb9a71-4af6-47b2-a762-9806519a195d.png)

控制台提示错误如下：
![image](https://user-images.githubusercontent.com/1748091/197959526-a3d32dad-7d7d-4949-a587-74d813f8d9f1.png)

## Mini Showcase Repository(REQUIRED)
项目git 地址：https://github.com/wcleye/umi-lowcode.git

## How To Reproduce

**npm install --legacy-peer-deps

**npm run dev

## 启动项目后，打开 http://localhost:8000

- **Umi Version**: 4.0.6
- **Node Version**: 16.17.0
- **Platform**: React

**Comment by fz6m** [comment]
删除所有的 `defer: false`

**Comment by WHSnhcZDYRZC** [comment]
可以去看下这个库的解决方案哦
https://github.com/WHSnhcZDYRZC/umi4-lowcode-engine-solutions
