### ISSUE TITLE
[Bug] Cannot start service: Host version "0.14.49" does not match binary version "0.14.36"

### ISSUE THREAD

**Issue by fatesq** [umijs/umi#9635]
## What happens?

![A~P`VYBA1_9}8@@F9%JTBBC](https://user-images.githubusercontent.com/11306229/198232297-64653bd2-1d07-48cf-97da-788109b000ed.png)

## Mini Showcase Repository(REQUIRED)
pnpm install & start  umi 对 esbuild版本报错

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
给一个复现看看，你是手动又安装了 `esbuild` 吗。

**Comment by fatesq** [comment]
> 给一个复现看看，你是手动又安装了 `esbuild` 吗。

没有，只是pro create myapp后 install就这样了

**Comment by fz6m** [comment]
这个问题已经在 https://github.com/umijs/umi-presets-pro/pull/8 被修复，等待 [umi-presets-pro](https://www.npmjs.com/package/umi-presets-pro) 发版升级后解决。

相关问题：

 - https://github.com/ant-design/ant-design-pro/issues/10165
