### ISSUE TITLE
[Feature Request] more progress log in loading page

### ISSUE THREAD

**Issue by PeachScript** [umijs/umi#9653]
## Background

现在默认的 loading 页面只有百分比，在大项目中可能会长时间卡在某个百分比不动，让人以为编译已经卡死了

<img width="493" alt="图片" src="https://user-images.githubusercontent.com/5035925/198924451-72e5fa06-141d-4acf-a55f-bd33f3a664a5.png">

## Proposal

参考 [webpackbar](https://github.com/unjs/webpackbar)，把编译的额外信息放在 loading 进度下方：

![图片](https://user-images.githubusercontent.com/5035925/198924237-a3ab2b32-3e5e-4383-901a-1459a09533cc.png)

印象中它在资源 hash 等阶段还会输出额外的信息，最好也能复用

**Comment by rovoskarl** [comment]
1111 认领

**Comment by fz6m** [comment]
在 https://github.com/umijs/umi/pull/9666 已实现。
