### ISSUE TITLE
umi-max无法使用Google Analytics 4

### ISSUE THREAD

**Issue by qm921** [umijs/umi#9654]
我使用的是    "@umijs/max": "^4.0.28
我看文档说这个ga插件是默认开启的
我按照文档配置了相关参数但是当我检查网络请求时发现没有ga的统计
export default {
  npmClient: 'yarn',
  request: {},
  mock: {},
  model: {},
  antd: {},
  access: {},
  initialState: {},
  favicons: ['/favicon.ico'],
  publicPath: '/',
  locale: {
    antd: true, // 如果项目依赖中包含 `antd`，则默认为 true
    baseNavigator: true,
    baseSeparator: '-',
    default: 'en-US',
    title: true,
    useLocalStorage: true,
  },
  analytics: {
    ga: 'G-VH486N2GF7',
  },
<img width="342" alt="image" src="https://user-images.githubusercontent.com/99302509/198943575-7e758d98-4025-43be-8419-445cdae58395.png">

<img width="247" alt="image" src="https://user-images.githubusercontent.com/99302509/198940654-d046e1cf-7351-4e37-a810-3577c23ce04a.png">

**Comment by fz6m** [comment]
只有在构建完，并且部署到没有端口的域名上时，才会上报数据

**Comment by qm921** [comment]
> 只有在构建完，并且部署到没有端口的域名上时，才会上报数据

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/99302509/198948498-e0ae5133-0a63-4ab4-b46d-46fbf9151eb4.png">  
有这个请求 但是感觉请求不是到ga4的   而且我看统计也没有任何数据

**Comment by fz6m** [comment]
明天再看看，GA 的数据不是实时的，还没有数据的话再反馈。

**Comment by qm921** [comment]
> 明天再看看，GA 的数据不是实时的，还没有数据的话再反馈。

没有的，这个问题从上周三我就看到了，上周三页是有这个请求但是到现在了都没数据

**Comment by qm921** [comment]
> 明天再看看，GA 的数据不是实时的，还没有数据的话再反馈。

这是其他网站可以统计成功的(collect?v=2),用umi-max请求的是collect?v=1     感觉差好多啊
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/99302509/198952702-2c954e6c-5ffd-4708-8b4e-3ad3a10e6bfe.png">

**Comment by fz6m** [comment]
周四发版后可使用 `ga_v2` 配置 v2 版本的上报。见 ：https://umijs.org/docs/max/analytics

**Comment by qm921** [comment]
> 周四发版后可使用 `ga_v2` 配置 v2 版本的上报。见 ：https://umijs.org/docs/max/analytics

好的  谢谢
![image](https://user-images.githubusercontent.com/99302509/199171430-16bde107-4efc-45d6-8d07-9f7404acf32f.png)

**Comment by qm921** [comment]
> 

不是周四发布吗？
![image](https://user-images.githubusercontent.com/99302509/199864524-b2ceeff6-75cf-4906-b292-6284e6d88945.png)
