### ISSUE TITLE
4.0.19升级到4.0.21 启动有报错

### ISSUE THREAD

**Issue by pleiades-embers** [umijs/umi#9667]
## What happens?

```
atal - Error: ENOENT: no such file or directory, open '/Users/Desktop/code/umi4/node_modules/.cache/mfsu/v4/loading.js'
    at Object.openSync (node:fs:590:3)
    at readFileSync (node:fs:458:35)
    at AutoUpdateFolderCache.filesLoader (/Users/Desktop/code/umi4/node_modules/.pnpm/@umijs+preset-umi@4.0.28_cc724207499d9661b3e92923d65d0d93/node_modules/@umijs/preset-umi/dist/libs/folderCache/AutoUpdateSourceCodeCache.js:64:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Context

- **Umi Version**: 4.0.28
- **Node Version**: 16.18.0
- **Platform**:  mac

**Comment by fz6m** [comment]
这个问题应该和 https://github.com/umijs/umi/discussions/9601#discussioncomment-4024608 是一个问题。

有时间的时候可以辛苦看下 @stormslowly  🌹

**Comment by pleiades-embers** [comment]
启动的时候找不到loading.js  .cache里找不到,删了.cache重新启动也没有

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/44309088/200221593-0e02b93f-0c7e-4532-a461-74c1e9a07081.png">


我的loading.tsx 代码
```
import { Spin } from 'antd';

export default function () {
  return (
    <div style={{ paddingTop: 300, textAlign: 'center', width: '100%',position:"relative",zIndex:99999,height:"100vh" }}>
      <Spin />
    </div>
  );
}
```

**Comment by stormslowly** [comment]
@pleiades-embers  你看下 pages/workspace/index.*  有几文件，

预编译的时候 index.tsx, index.js 都会写到  index.js 会冲突的，如果想用 eager 模式的话，需要重命名下

![image](https://user-images.githubusercontent.com/415655/200228329-dd1affbb-8e71-48dd-a3ee-9e8d6d12f379.png)

**Comment by pleiades-embers** [comment]
> @pleiades-embers 你看下 pages/workspace/index.* 有几文件，
> 
> 预编译的时候 index.tsx, index.js 都会写到 index.js 会冲突的，如果想用 eager 模式的话，需要重命名下
> 
> ![image](https://user-images.githubusercontent.com/415655/200228329-dd1affbb-8e71-48dd-a3ee-9e8d6d12f379.png)

确实有个index.js 和index.tsx 解决了 谢谢大佬

**Comment by pleiades-embers** [comment]
eager 还有一个问题 注释了的引用  也会检查包依赖？

一个文件夹注释了导入
```
// import xlsxHelper, { TSheetColumn } from './xlsxHelper';
```

xlsxHelper.ts
```
import XLSX from 'xlsx';
```
<img width="589" alt="image" src="https://user-images.githubusercontent.com/44309088/200240839-51896c4f-b9d7-46b9-acde-1c9f85135aa5.png">

**Comment by stormslowly** [comment]
是的  他是基于文本扫描的，如果代码里面有合法的 import 语句就认为是一个依赖
