### ISSUE TITLE
[Feature Request] umi@4 生成的html无法配置lang属性

### ISSUE THREAD

**Issue by webarn** [umijs/umi#9669]
在umi@4中废弃ejs模板, 默认生成的lang属性无法设置

**Comment by zhengtan2003** [comment]
+1

**Comment by fz6m** [comment]
[如何自定义 HTML 模板](https://umijs.org/docs/introduce/faq#documentejs-%E5%8E%BB%E5%93%AA%E4%BA%86%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89-html-%E6%A8%A1%E6%9D%BF)
