### ISSUE TITLE
[Feature Request] 没有路由守卫功能，无法实现切换页面时退出确认

### ISSUE THREAD

**Issue by voidjay** [umijs/umi#9677]
## 功能描述

umi4的max中无法导入withRoute，也没有prompt，
有一个比较重要的页面，需要退出时进行二次确认，通过现有的api无法实现

**Comment by xierenyuan** [comment]
reactrouter v6 移除了  prompt  https://reactrouter.com/en/v6.3.0/upgrading/v5#prompt-is-not-currently-supported 现在要实现的话 可能的 自行实现一下

**Comment by fz6m** [comment]
可以看一下这个 `Prompt` 实现，应该能实现你的需求：

https://github.com/umijs/umi/discussions/10237#discussioncomment-4625915
