### ISSUE TITLE
【Bug】MFSU eager 模式 HMR 速度慢

### ISSUE THREAD

**Issue by fz6m** [umijs/umi#9679]
复现步骤如下。

创建一个 simple umi 项目并加入 antd ：

```bash
  pnpm create umi demo
  cd ./demo
  pnpm add antd @umijs/plugins
```

配置：

```ts
// .umirc.ts

export default {
  npmClient: 'pnpm',
  antd: {},
  plugins: [
    '@umijs/plugins/dist/antd'
  ]
}
```

复现代码：

```ts
// src/pages/index.tsx

import { Button } from 'antd'

export default function HomePage() {
  return (
    <div>
      <h2>Yay! Welcome to umi!</h2>
      <Button type='primary'>kk333k111</Button>
    </div>
  );
}
```

复现步骤：

1. 删除 `<Button type='primary'>` 中的 `type='primary'` ，等待页面 HMR 完成，再添加回来，再等待完成，如此反复删增几次就会引发 MFSU 的 warn 警告：

    <img src='https://user-images.githubusercontent.com/59400654/199465812-873123be-7425-430a-a62b-7e3c325309a4.png' width='40%' />

2. 出现警告后，任何改动都需要 5s 时间延迟。

注：MFSU normal 、不启用 MFSU 无此问题，HMR 在 300ms 。

_Originally posted by @fz6m in https://github.com/umijs/umi/discussions/9676#discussioncomment-4035475_
    
相关讨论：

 - https://github.com/umijs/umi/discussions/9676

**Comment by xierenyuan** [comment]
这个 我给 @stormslowly 反馈过 pshu 老师应该 在跟进
