### ISSUE TITLE
umi 找不到 keepalive [Bug] say something

### ISSUE THREAD

**Issue by big-bomp** [umijs/umi#9697]
![image](https://user-images.githubusercontent.com/76605831/199879419-1d2fdb98-2c9a-4201-8443-c66b8b7acb92.png)

## What happens?

![image](https://user-images.githubusercontent.com/76605831/199879366-7eae699c-66b9-432a-b3f3-dd891b784258.png)

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

直接按照官网创建项目 然后 导出 keepalive
## Context
node 16
umi4
- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
umi4 没有 keep alive ，你在找的是不是 https://github.com/alitajs/alita/blob/master/packages/plugins/src/keepalive.ts

**Comment by big-bomp** [comment]
![image](https://user-images.githubusercontent.com/76605831/199918970-59a73684-1871-43be-85c9-259597bab103.png)
![image](https://user-images.githubusercontent.com/76605831/199918985-e71d7ae3-78c0-4544-b5a5-62866b23ebfd.png)
安装了 umi-plugin-keep-alive 插件也没有吗？

**Comment by fz6m** [comment]
在哪里看到的文档
