### ISSUE TITLE
【bug】AutoUpdateFolderCache.filesLoader  找不到文件

### ISSUE THREAD

**Issue by pleiades-embers** [umijs/umi#9711]
## umi4 4.0.19 升级到 umi4 4.0.29 启动项目会报以下错误

<img width="655" alt="image" src="https://user-images.githubusercontent.com/44309088/200219952-9e8b0f61-5e61-4391-85f6-53610329f32f.png">

## Context

- **Umi Version**: 4.0.29
- **Node Version**:  16.18.0
- **Platform**:  mac

**Comment by fz6m** [comment]
在这里跟进：https://github.com/umijs/umi/issues/9678

@stormslowly 有时间的时候可以新库看下，这三个 issue 反馈好像都是一个问题（见 https://github.com/umijs/umi/issues/9678 ）。

**Comment by fz6m** [comment]
现在的解决办法：删除 `node_modules/.cache` 重启项目

**Comment by pleiades-embers** [comment]
重复啦  #9667  已经解决
