### ISSUE TITLE
[Bug] plugin-qiankun-master

### ISSUE THREAD

**Issue by DevilMayDead** [umijs/umi#9712]
getMicroAppRouteComponent

RouteComponent中的useMatch获取不到对应路由，将抛出Cannot read properties of null (reading 'useContext')

** 最小库复现 **
[https://github.com/DevilMayDead/IntegrationPlaform.git](url)

**Comment by fz6m** [comment]
https://github.com/DevilMayDead/IntegrationPlaform

这个链接，404 打不开，提供一个有效的最小复现。

**Comment by fz6m** [comment]
试一下：

```ts
  const C = () => {
      return getMicroAppRouteComponent({
        // ...
      })();
  }
  routes[0].children[index].element = <C />
```

**Comment by DevilMayDead** [comment]
> 试一下：
> 
> ```ts
>   const C = () => {
>       return getMicroAppRouteComponent({
>         // ...
>       })();
>   }
>   routes[0].children[index].element = <C />
> ```

虽然useMatch还是空，但是这次不报异常了，这是为啥

**Comment by DevilMayDead** [comment]
> 试一下：
> 
> ```ts
>   const C = () => {
>       return getMicroAppRouteComponent({
>         // ...
>       })();
>   }
>   routes[0].children[index].element = <C />
> ```

还是不行呀，还是异常

**Comment by DevilMayDead** [comment]
> 试一下：
> 
> ```ts
>   const C = () => {
>       return getMicroAppRouteComponent({
>         // ...
>       })();
>   }
>   routes[0].children[index].element = <C />
> ```

往前一点版本的plugin-qiankun-master的getMicroAppRouteComponent是可以用的
  // 默认取静态配置的 base
    let umiConfigBase = base === '/' ? '' : base;

    // 拼接子应用挂载路由
    let runtimeMatchedBase = umiConfigBase + routePath.replace('/*', '');

**Comment by fz6m** [comment]
给一个全的复现，上面提供的没有子应用不完整。

**Comment by DevilMayDead** [comment]
> 给一个全的复现，上面提供的没有子应用不完整。

包含子应用
https://github.com/DevilMayDead/IntegrationPlaform

**Comment by fz6m** [comment]
我本地可以的：

![screenshot_2022-11-10_16-55-11](https://user-images.githubusercontent.com/59400654/201033385-5ec5b400-080d-4396-80cf-36e0b2e6b18c.png)

区别是给子应用添加对应旧版的 `@ant-design/pro-layout` ：

```diff
// package.json
+  "@ant-design/pro-layout": "^6.0.0"
```

**Comment by DevilMayDead** [comment]
> 我本地可以的：
> 
> ![screenshot_2022-11-10_16-55-11](https://user-images.githubusercontent.com/59400654/201033385-5ec5b400-080d-4396-80cf-36e0b2e6b18c.png)
> 
> 区别是给子应用添加对应旧版的 `@ant-design/pro-layout` ，同时加上我上面的那个组件更改 ( [#9712 (comment)](https://github.com/umijs/umi/issues/9712#issuecomment-1308417331) ) ：
> 
> ```diff
> // package.json
> +  "@ant-design/pro-layout": "^6.0.0"
> ```

子应用是antd pro V5版本的脚手架生成的，用的是最新的@antd-design/pro-components
所以说是组件版本的问题吗

**Comment by DevilMayDead** [comment]
> 我本地可以的：
> 
> ![screenshot_2022-11-10_16-55-11](https://user-images.githubusercontent.com/59400654/201033385-5ec5b400-080d-4396-80cf-36e0b2e6b18c.png)
> 
> 区别是给子应用添加对应旧版的 `@ant-design/pro-layout` ，同时加上我上面的那个组件更改 ( [#9712 (comment)](https://github.com/umijs/umi/issues/9712#issuecomment-1308417331) ) ：
> 
> ```diff
> // package.json
> +  "@ant-design/pro-layout": "^6.0.0"
> ```

我这里试了一下，还是不行啊。。。
我已经按照您说的改并且提到库里了
