### ISSUE TITLE
Change the size of the browsing window, the page will appear blank, and the console will report an error

### ISSUE THREAD

**Issue by Connor-lipalater** [umijs/umi#9733]
Error message:
Uncaught TypeError: Cannot read properties of undefined (reading 'apply')
The above error occurred in the <BaseProLayout> component:
Consider adding an error boundary to your tree to customize error handling behavior.

Framework：
Umi4.0+ant-design/pro@2.0+react18

Reproduction link：
https://spdev.lipalaterapis.com/order

Github:
https://github.com/lipa-later/web-store-admin.git

Error screenshot:
https://chinatestocr.s3.amazonaws.com/sp/mall/16680488245791668048771033.png

Error component:
BaseProLayout

**Comment by fz6m** [comment]
1. 这个 git repo 打不开。

2. 我打开这个网址试了一下，改变浏览器窗口并没有控制台报错。

**Comment by Connor-lipalater** [comment]
> 

改变窗口幅度大一点，直接拖拽缩小三分之二立马白屏。

**Comment by Connor-lipalater** [comment]
@fz6m Pls have a look into these two issues,they are same project.I have added the permission you

**Comment by fz6m** [comment]
`src/app.ts` 中 `onCollapse` 是一个函数。
