### ISSUE TITLE
ProFormUploadButton组件 在Modal关闭的时候会报错： Uncaught TypeError: (fileList || []).forEach is not a function

### ISSUE THREAD

**Issue by Connor-lipalater** [umijs/umi#9734]
问题描述：
在使用Umi4.0框架下，在model中使用ProForm进行数据新增和编辑，ProForm是通过表单受控来维护数据，ProForm表单包含ProFormUploadButton组件没有使用fileList数据维护，新增的时候是正常的，当时再次编辑ProForm,ProFormUploadButton数据进行了回显，，然后点击右上角关闭弹窗,会调用handleCancel方法，页面就出现报错，当去掉该方法中的form.resetFields()方法，页面功能就正常，目前问题定位是表单数据清空的时候这个ProFormUploadButton组件清空会报错。

const handleCancel = () => {
    props.onCancel();
    form.resetFields();
  };

项目地址：
https://spdev.lipalaterapis.com/Products

复现方法：
进入products列表，编辑任意一条商品，然后点击cancel或者关闭弹窗右上角关闭，页面立马报错。

报错信息：
Uncaught TypeError: (fileList || []).forEach is not a function

报错截图：
https://chinatestocr.s3.amazonaws.com/sp/mall/16680496154541668049606354.jpg

Github:
https://github.com/lipa-later/web-store-admin.git

**Comment by fz6m** [comment]
`resetFields` 方法只是把 form 恢复到初始值，这个地方因为设定了 `Form` 的 `initialValues` ，所以回到了 `initialValues` ，这个值和预期的格式不匹配。

1. 理论上不需要清数据，下次开窗口的时候会 set 新值进去。

2. 这里可以用 initial value ，但是要 tramsform 到指定格式。也可以不用 initial value ，加载进来监听发生改变了再 set 进去。

3. 另外其他的代码也有一些问题。。比如用 object 做 `useEffect` 的 deps 依赖，应该换成 `useDeepCompareEffect` ，或者换其他的逻辑等。
