### ISSUE TITLE
.d.ts是全局的，不需要import，一旦import了他就不是全局的了，在这行下面定义的类型无效

### ISSUE THREAD

**Issue by tonny008** [umijs/umi#9748]
这个import的作用只是把src/.umi/typing.d.ts include（全局）进来。因为他本身用到了import，在这个文件中申明的类型就不是全局的了，在这行下面定义的类型必须import 它才能生效，不然无效

https://github.com/umijs/umi/blob/2ae7c7dc4efb94a2ab4da4408ef92d8d3ec3c7ab/packages/create-umi/templates/max/typings.d.ts#L1

应该直接在tsconfig中include src/.umi/typing.d.ts include

**Comment by fz6m** [comment]
声明全局的方法：

```ts
declare global {
  const __DEV__: boolean

  interface Window {
    a: number
  }
}
```

**Comment by tonny008** [comment]
你这个是声明JS的global类型，和全局typescript类型声明不是一回事, 全局typescript类型声明是不需要import也可以使用的意思。
这里错误的umi生成的 tsconfig 中配置错误，没有把 .umi/typings.d.ts include（mac是如此，应该是.umi是隐藏文件，windows没有试过）就是下面的配置并没有include .umi隐藏文件夹。编译不报错是因为文件通过import引入了。.umi/typings.d.ts没有引入，所以里面的类型定义不会生效。
```json
  {"include": [
    "../../.umirc.ts",
    "../../**/*.d.ts",
    "../../**/*.ts",
    "../../**/*.tsx"
  ]}
```
.umi/typings.d.ts 本身就是全局的，上面的 ` import '@umijs/max/typings'; `只是相当于把这个文件include了。
然后因为/typings.d.ts使用了import, 它就不是全局的了。在里面声明的类型就必须import才能用了。

**Comment by fz6m** [comment]
全局的 ts 类型声明方法：

```ts
// typings.d.ts

declare global {
  interface ISomeType {
    a: number
  }
}
```

在任意 ts 文件内，不需要 import ：

```ts
const a: ISomeType = { a: 1 }
```

**Comment by tonny008** [comment]
你这个是声明JS的global类型, 和全局typescript类型声明不是一回事

下面的代码你能写么？不报错么
```ts
declare global {
  declare module '*?raw'{
    const content: string;
    export default content;
  }
  
}
```

**Comment by fz6m** [comment]
你说得对，这种情况下，新建一个 `.d.ts` 文件声明即可：

```ts
// ${project-root}/some-name.d.ts

declare module '*?raw' {
  const content: string
  export default content
}
```

**Comment by fz6m** [comment]
为了防止 Breaking change ，不会调整现有的 `typing.d.ts` 了，如果有定义全局类型的情况可以参照如上描述再创建一个 `.d.ts` 文件。
