### ISSUE TITLE
【Bug】MFSU 与 monorepo 子包的依赖兼容性

### ISSUE THREAD

**Issue by fz6m** [umijs/umi#9752]
主要是依赖处理的问题。

来自于 https://github.com/umijs/umi/issues/9356 ：

### 发生的新问题

@stormslowly  有时间可以辛苦看下这个问题 🌹

在 monorepo 中，**改动引用子包内容** 的时候，mfsu 会报依赖错误：

```bash
error - MFSU[eager] analyze dependencies failed with error Error: ENOENT: no such file or directory, open '.../umi4-monorepo/packages/app/node_modules/.cache/lib/src/index.js'
```

将子包添加到 `mfsu.exclude` 也无法解决：

```ts
// .umirc.ts

export default {
  // 当改动子包内容时，仍然会出现依赖错误
  mfsu: {
    exclude: ['@mono/lib']
  }
}
```

### 复现方法

1. 拉下本 issue 中的仓库 https://github.com/twinkle77/umi4-monorepo

2. 将应用 `packages/app/package.json` 的 umi 版本改为最新：

    ```diff
    // packages/app/package.json
    +  "umi": "^4.0.30",
    ```

3. 启动项目
    
    ```bash
      pnpm i
      cd ./packages/app && pnpm dev
    ```

4. 改动子包 `packages/lib/src/index.ts` 代码，即可复现。

_Originally posted by @fz6m in https://github.com/umijs/umi/issues/9356#issuecomment-1312309846_

**Comment by stormslowly** [comment]
目前monorepo 情况下使用 mfsu 的话 还是推荐使用  strategy: 'normal' 配置。

eager  模式下的 monorepo  还需要再讨论下；

分两种情况

## 情况1： 子包的依赖和项目代码一起编译

目前的方案是，采用 exclude 的方式 或者 靠包管理工具将包软连接到实际的路径，因为 eager 只会扫描自己包下的依赖，所以 monorepo 中的其他包的依赖不会打包进远端组件中，就会和项目代码一起编译打包，如果其他子包的依赖数量较多的话，mfsu 提速的依赖比例就很低，加速的实际意义就不大了。
（当然一部分依赖和项目打包，一部分在远端打包，还有会多实例问题；但可以通过通过 shared 配置来解决，就不讨论了）

## 情况2： 子包整个和项目依赖一起编译

即 monorepo 中的包当做和其他依赖同等处理，统一打包进远端包中。

目前可行的方案是，使用 eager 特有的 include 配置，强制放进远端包。

但是这样的方案有一个问题是，monorepo 中的子包如果有更新or 重新构建过的话，需要远端包重新构建；因为依赖的条目并没有变化，所以要有一个新的机制来触发远端包重新构建。目前 watch 机制不能判断出依赖是否更新，所以可能是个手动的方案。

@sorrycc  @fz6m [暗中观察]

**Comment by fz6m** [comment]
目前 `normal` 策略还是会报 `axios` 依赖找不到的问题，这个问题有解么（如本 Issue 中的复现方式）。

```bash
error - Can not resolve dependence : 'axios', please install it
error - AssertionError [ERR_ASSERTION]: dependence not found: axios
```

**Comment by stormslowly** [comment]
解 ing ~ 
目前 依赖 resolve 的时候 只有一个 cwd 的参数，在 monorepo 中显然就不对了。
现代 resove 需要把 importer 带过来，从 impoter 的 dir作为 context 来 resovle 才合理。

**Comment by fz6m** [comment]
能让应用的第三方包不走 mfsu 吗，这样就不会有这个问题了吧。

用户在同一 monorepo 内使用的子包数量是有限的，性能可以接受，需要忽略哪些可以在扫描的时候自动配置。
