### ISSUE TITLE
[Bug] umi layout 设置为 top 不

### ISSUE THREAD

**Issue by yuruotong1** [umijs/umi#9760]
## Mini Showcase Repository(REQUIRED)
我的配置如下

`import { defineConfig } from '@umijs/max';
import routes from './routes'
export default defineConfig({
  antd: {},
  access: {},
  model: {},
  initialState: {},
  request: {},
  layout: {
    "title": "demo",
    "navTheme": "light",
    "primaryColor": "#1890ff",
    "layout": "top",
    "contentWidth": "Fixed",
    "fixedHeader": false,
    "fixSiderbar": true,
    "pwa": false,
    "logo": "https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg",
    "headerHeight": 48,
    "splitMenus": true
  },
  routes,
  npmClient: 'npm',
});
`

## Context
我想去除菜单栏（或者将菜单栏上移），如上配置是从 ProLayout 中粘贴过来的，但是 "layout": "top" 貌似没有效果，请问有别的解决方法吗？

**Comment by fz6m** [comment]
umi4 中关于 layout 的运行时配置需要写在 `src/app.ts` 中：

```ts
// src/app.ts

export const layout = () => {
  return {
    // ...
  }
}
```

不需要 layout 的时候，在 `.umirc.ts` > `routes` 路由表中设置 `layout: false` 。

FYI ：

 - https://github.com/ant-design/ant-design-pro/blob/master/src/app.tsx#L51

 - https://github.com/ant-design/ant-design-pro/blob/master/config/routes.ts#L14
