### ISSUE TITLE
[Bug] umi@4插件里require项目里的某个esModule模块的ts报错找不到

### ISSUE THREAD

**Issue by qiujie8092916** [umijs/umi#9762]
## What happens?
如题，插件里使用`require`项目里的某个`esModule`模块的`ts`报错找不到，`require`的路径是到文件夹层面，文件夹下面包含了`index.ts`，但是`require`提示找不到

## How To Reproduce

**Steps to reproduce the behavior:** 
1. `umi@4`插件里使用`require`引入项目里`ts`模块提示找不到
2. 在补充完`ts`完整路径后，提示`require`引入的不是有效模块
3. `umi@3`下没问题
4. 尝试在插件入口开头加入
```ts
import { register } from '@umijs/utils';

register.register({ 
  implementor: esbuild,
}); \
register.clearFiles();
```
后便可以

1. 不知是否是在umi@4中去掉了对插件的module.extensions的扩展，导致`require`只支持默认的`js`、`node`、`json`；并且去掉了对esmodule模块的引入支持
2. 不知目前上述这种解决方案是否可行

## Context

- **Umi Version**: 4.0.30
- **Node Version**:16.18.1
- **Platform**: mac/win

**Comment by fz6m** [comment]
应该遵循 esm 使用 import 。

若还有疑问，可以提供一个复现看看。

**Comment by qiujie8092916** [comment]
> 应该遵循 esm 使用 import 。
> 
> 若还有疑问，可以提供一个复现看看。

https://github.com/qiujie8092916/umi-plugin-example/tree/umi3 （正常）
https://github.com/qiujie8092916/umi-plugin-example/tree/umi4 （异常）

**Comment by fz6m** [comment]
umi 4 现在的 ts 导入支持仅仅 hook 了 umi 4 这一层，在运行你的文件时本质上还是 `require()` ，所以要求后续的内容都是 cjs 或被转为 cjs ，但是动态导入了 esm 的内容，是预期之外的非 cjs 内容，故无法实现 cjs import esm 。

所以如题所述，手动再启动 hook 一下是可以的。

另外，不是可以从 `api.userConfig.routes` 中取到吗，为啥要动态加载。

**Comment by qiujie8092916** [comment]
> umi 4 现在的 ts 导入支持仅仅 hook 了 umi 4 这一层，在运行你的文件时本质上还是 `require()` ，所以要求后续的内容都是 cjs 或被转为 cjs ，但是动态导入了 esm 的内容，是预期之外的非 cjs 内容，故无法实现 cjs import esm 。
> 
> 所以如题所述，手动再启动 hook 一下是可以的。
> 
```ts
register.register({ 
  implementor: esbuild,
});
register.clearFiles();
```
意思这种方式是可行的吗？

> 另外，不是可以从 `api.userConfig.routes` 中取到吗，为啥要动态加载。

hhhhhhh 还真是个好问题
