### ISSUE TITLE
运行编译报错

### ISSUE THREAD

**Issue by Jeggery** [umijs/umi#9764]
![image](https://user-images.githubusercontent.com/39072827/201536204-afcbc686-1d5b-4ca2-ac4b-02cbe2677823.png)
![image](https://user-images.githubusercontent.com/39072827/201536225-7036e3f4-4206-4434-8a9b-5da543ec7f67.png)

报错：Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'create')，
这是直接用umi4版本不行吗？还是得用@umijs/max?

**Comment by fz6m** [comment]
有使用 `defineApp` 吗？

给一个最小复现看看。

**Comment by Jeggery** [comment]
> 有使用 `defineApp` 吗？
> 
> 给一个最小复现看看。

我又重新搭建了个环境，清理了一下，，又不报错了

**Comment by fz6m** [comment]
什么 umi 版本？可以提供一下信息帮助排查问题。

**Comment by Jeggery** [comment]
> 什么 umi 版本

4.0.30的. 我是把原先umi3项目的代码直接拉过来运行的，结果运行不起来，里面有用到dva，我以为是dva的原因，后来搭建了个纯净的环境试下dva，又可以了。具体产生那个报错的原因还不知道。反正要一点一点挪吧
