### ISSUE TITLE
Umi layout 组件右上角“退出登录”中文可以在哪里修改？

### ISSUE THREAD

**Issue by Connor-lipalater** [umijs/umi#9766]
app.ts 里面配置logout后，右上角弹出“退出登录”中文在哪里可以修改？

**Comment by fz6m** [comment]
是这里吧，提 PR 改个通用方案吧。

https://github.com/ant-design/ant-design-pro/blob/6641f4424fa16f4306d0cb4c671c56b58107fc9a/src/components/RightContent/AvatarDropdown.tsx#LL97
