### ISSUE TITLE
[Feature Request] Encode special url

### ISSUE THREAD

**Issue by wangyi12358** [umijs/umi#9768]
请问下这种带有特殊符号的路径可以 decodeURIComponent一下吗
正常访问：
![image](https://user-images.githubusercontent.com/39055759/201572550-fcc52bb8-ddf8-4dbb-8566-0cc823b379f9.png)
无法访问：
![image](https://user-images.githubusercontent.com/39055759/201572774-0147d2d9-b8fa-4403-8e64-4701ea42653a.png)

**Comment by fz6m** [comment]
在 PR #9743 解决，等待下次发版吧。

**Comment by wangyi12358** [comment]
> 在 PR #9743 解决，等待下次 (本周四) 发版吧。

好的，谢谢
