### ISSUE TITLE
packages/umi/prettier中pluginSearchDirs的配置会影响prettier-plugin-organize-imports插件起作用

### ISSUE THREAD

**Issue by winedk** [umijs/umi#9779]
https://github.com/umijs/umi/blob/master/packages/umi/prettier.js#L12

**Comment by mysteryven** [comment]
请问是你的项目使用了 prettier-plugin-organize-imports，但是没有起作用吗？

如果是的话，你的项目是怎么开启的 prettier-plugin-organize-imports？

**Comment by fz6m** [comment]
在最新的 prettier v3 版本里已经把这个选项 [废除](https://prettier.io/blog/2023/07/05/3.0.0.html#plugin-search-feature-has-been-removed-14759httpsgithubcomprettierprettierpull14759-by-fiskerhttpsgithubcomfisker) 了，升级到 v3 然后配置自己想要的 prettier 配置吧。
