### ISSUE TITLE
[Bug] 确定 FormattedMessage 这些接口能用？

### ISSUE THREAD

**Issue by sk142857** [umijs/umi#9781]
https://github.com/umijs/umi/blob/v4.0.30/examples/ant-design-pro/src/pages/user/Login/index.tsx

```ts
import { FormattedMessage, history, SelectLang, useIntl, useModel } from 'umi';
```
TS2305: Module '"umi"' has no exported member 'FormattedMessage'.

**Comment by johnsmithsren** [comment]
如果是umijs-max ，umirc.ts 中加上 locale:{},应该可以，我是这么解决的。
