### ISSUE TITLE
[Feature Request] 希望暴漏一个全局的在路由层之上的dom挂载点。比如我有一个弹窗，只要点开后，不管哪个页面都会显示

### ISSUE THREAD

**Issue by liu071900** [umijs/umi#9788]
## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by fz6m** [comment]
放在 layout 里就行了，layout 应该每个文件都有。

或者用 [react-portal](https://github.com/tajo/react-portal) 之类的库把它送到 html 上一个固定的节点，这个节点创建的时候，可以通过创建 or 改写 `index.html` 来实现。

**Comment by liu071900** [comment]
非常感谢您的回复。
我的实际需求是这样：有一个ws链接，然后需要ws的回调函数里调用 reacthook；
我想在app.tsx 的 render 函数里实现代码逻辑，但是react说不允许在非函数组件使用hook,
如果写在layout 的 childrenRender方法里 每次跳转路由我都需要 重新绑定事件(因为每次hook拿到的函数地址都不一样?)
我期望的结构是这样

<app>
//全局组件
<topComponent></topComponent>

<oulet>
    {业务组件}
</oulet>

</app>

另：如果用portal方式，它创建的组件生命周期还是在 路由组件之下，跳转路由后会销毁这个组件。

**Comment by fz6m** [comment]
需要脱离 react 的情况，选取一款状态管理库，如使用 [valtio](https://github.com/pmndrs/valtio) 来管理状态即可在任意地方修改数据。

**Comment by liu071900** [comment]
thanks, that is what i want~

**Comment by JinghuiS** [comment]
我之前也有这种需求，不如试试nice-modal-react？
