### ISSUE TITLE
分布表单包含一个ProTable的时候会报错，目前定位是form嵌套form导致的，但是有这个需求，请问如何解决

### ISSUE THREAD

**Issue by Connor-lipalater** [umijs/umi#9795]
Desciption：
1.使用轻量筛选ProTable组件的时候，右上方自带搜索想渲染出ProFormTreeSelect这样二级分类样式，如果配置？如下图：
https://lipalater-dev.s3.amazonaws.com/sp/mall/product/20221117114115309_1668656439426.jpg

2.分布表单包含一个ProTable的时候会报错，目前定位是form嵌套form导致的，但是有这个需求，请问如何解决？报错如下图：
https://lipalater-dev.s3.amazonaws.com/sp/mall/product/20221117114838537_1668656909678.jpg

Framework：
Umi4.0+ant-design/pro@2.0+react18

Reproduction link：
https://spdev.lipalaterapis.com/order

Github:
https://github.com/lipa-later/web-store-admin.git

**Comment by fz6m** [comment]
antd Form 是不可以嵌套的。

1. 我不了解 pro table 的实现，可以到 https://github.com/ant-design/pro-components 寻求意见。

2. 使用 antd 手写表单，也不是很复杂。
