### ISSUE TITLE
[Bug] 开发环境和变异后的CSS的位置不一样

### ISSUE THREAD

**Issue by fanmingfei** [umijs/umi#9796]
开发环境：
<img width="423" alt="image" src="https://user-images.githubusercontent.com/4632277/202351434-2360740e-9044-4e3f-a955-3dc4ff710e7e.png">

编译后：
![image](https://user-images.githubusercontent.com/4632277/202351444-88cc3995-bbb6-42ec-975e-e08353676033.png)

**Comment by fz6m** [comment]
对于覆写全局样式（如组件库）的情况，可能出现优先级不一致，目前解决不一致的方法是：

1. 关闭 `mfsu: false` 。

2. 在 `src/overrides.(css|less|scss)` 覆写全局样式。

以上方法二选一即可。
