### ISSUE TITLE
sass有出现某些代码不编译和仍然嵌套的问题

### ISSUE THREAD

**Issue by allan-hx** [umijs/umi#980]
![image](https://user-images.githubusercontent.com/37947922/44974701-07c1e100-af93-11e8-9d39-b16966a52ae9.png)

clone了官方[sass](https://github.com/umijs/umi-examples/tree/master/sass)案例也有这种情况

**Comment by sorrycc** [comment]
试了下 [umi-examples/sass](https://github.com/umijs/umi-examples/tree/master/sass)，不能重现，生成的代码是这样的。

```
.index__container___2py_l, .index__exc___73_0R {
  color: #f90; }
  .index__container___2py_l p, .index__exc___73_0R p {
    color: red; }

.index__exc___73_0R p {
  color: blue; }

.NotFound__wrapper___1uXkD {
  font-size: 18px;
  font-family: "Helvetica Neue", "Luxi Sans", "DejaVu Sans", Tahoma, "Hiragino Sans GB", "Microsoft Yahei", sans-serif;
}
.NotFound__wrapper___1uXkD code {
  background: #7898f3;
}
.NotFound__wrapper___1uXkD h1 {
  font-size: 40px;
  background: #78f191;
  margin-bottom: 30px;
}
.NotFound__wrapper___1uXkD h2 {
  color: #c803fd;
  font-size: 22px;
  margin-top: 40px;
}
.NotFound__wrapper___1uXkD ul {
  margin: 0;
  padding: 0;
  margin-left: 40px;
}


/*# sourceMappingURL=umi.css.map*/
```

**Comment by allan-hx** [comment]
你用的是线上发布了的umi么？ 我刚刚重新试了下发现还是存在的
![image](https://user-images.githubusercontent.com/37947922/44993784-68224400-afce-11e8-96b0-e8517e7b9ffb.png)
![image](https://user-images.githubusercontent.com/37947922/44993813-7cfed780-afce-11e8-9a91-39dd0e273d7e.png)
![image](https://user-images.githubusercontent.com/37947922/44993833-8ee07a80-afce-11e8-863f-3243f92c2d18.png)

**Comment by sorrycc** [comment]
试着重现安装了一遍也不能重现。

**Comment by allan-hx** [comment]
你是mac还是windows， 我是mac环境， 晚上我回家用windows试试

**Comment by sorrycc** [comment]
mac 。

**Comment by yutingzhao1991** [comment]
我的 mac 也试了下，没能复现这个问题：

![image](https://user-images.githubusercontent.com/1061968/45022034-c0585500-b065-11e8-9303-941fe63551ab.png)

**Comment by sorrycc** [comment]
@allan-hx 感觉是你的环境问题，找边上的人试试看？有问题再 reopen 。

**Comment by allan-hx** [comment]
你们node什么版本呢？ 我在找找看是不是sass的bug

**Comment by okoala** [comment]
@allan-hx 你运行 `umi -v --verbose` 看看

**Comment by allan-hx** [comment]
这是结果
![image](https://user-images.githubusercontent.com/37947922/45129848-a418fd00-b1b8-11e8-89a1-377ec23caf7d.png)

**Comment by okoala** [comment]
@allan-hx 
我用官方的 sass 同样没有重现这个问题，你重新安装下依赖吧:
1. `npm cache clean`
2. `rm -rf node_modules`
3. `npm install`

**Comment by yuyic** [comment]
在umi 2.9.6版本下确实有这个问题，退回到2.1.1就正常了。 @sorrycc @okoala
