### ISSUE TITLE
使用 create-umi 的项目生产依赖缓存无效

### ISSUE THREAD

**Issue by yuantongkang** [umijs/umi#9810]
使用 create-umi  初始化项目 ant design pro，多次执行 pnpm build，构建时间不变

**Comment by fz6m** [comment]
`build` 是没有开启物理缓存的。因为判定依据复杂，缓存很可能不失效导致出问题，一般情况只能在限定条件下，企业内使用。

**Comment by yuantongkang** [comment]
> `build` 是没有开启物理缓存的。因为判定依据复杂，缓存很可能不失效导致出问题，一般情况只能在限定条件下，企业内使用。

有什么途径可以开启吗

**Comment by fz6m** [comment]
```ts
// .umirc.ts
import { join } from 'path'
import { defineConfig } from 'umi'
import { createHash } from 'crypto'

export default defineConfig({
  chainWebpack(config, { env }) {
    if (env === 'production') {
      config.cache({
        type: 'filesystem',
        store: 'pack',
        version: createEnvironmentHash(),
        buildDependencies: {
          config: [__filename],
          tsconfig: [join(__dirname, 'tsconfig.json')],
          packagejson: [join(__dirname, 'package.json')],
          umirc: [join(__dirname, '.umirc.ts')],
        },
      })
    }
  },
})

function createEnvironmentHash() {
  const env = process.env
  const hash = createHash('md5')
  hash.update(JSON.stringify(env))
  const result = hash.digest('hex')
  return result
}
```

上述例子并没有真正考虑到所有可能的依赖，请综合考虑到自己的所有可能的依赖后，理解 [配置选项的作用](https://webpack.js.org/configuration/cache/) 基础上，经过配置，再谨慎使用。

否则会产生构建产物不是最新的问题。

**Comment by KellenHe** [comment]
> ```ts
> // .umirc.ts
> import { join } from 'path'
> import { defineConfig } from 'umi'
> import { createHash } from 'crypto'
> 
> export default defineConfig({
>   chainWebpack(config, { env }) {
>     if (env === 'production') {
>       config.cache({
>         type: 'filesystem',
>         store: 'pack',
>         version: createEnvironmentHash(),
>         buildDependencies: {
>           config: [__filename],
>           tsconfig: [join(__dirname, 'tsconfig.json')],
>           packagejson: [join(__dirname, 'package.json')],
>           umirc: [join(__dirname, '.umirc.ts')],
>         },
>       })
>     }
>   },
> })
> 
> function createEnvironmentHash() {
>   const env = process.env
>   const hash = createHash('md5')
>   hash.update(JSON.stringify(env))
>   const result = hash.digest('hex')
>   return result
> }
> ```
> 
> 上述例子并没有真正考虑到所有可能的依赖，请综合考虑到自己的所有可能的依赖后，理解 [配置选项的作用](https://webpack.js.org/configuration/cache/) 基础上，经过配置，再谨慎使用。
> 
> 否则会产生构建产物不是最新的问题。

大佬请问，缓存之后本地第二次构建速度确实很快
但是每次重新clone之后，首次构建还是很慢，没有命中缓存。

我是把缓存生成的文件上库了，请问这块一般怎么处理，每次clone之后可以命中上次的缓存文件。
