### ISSUE TITLE
[Bug] antd5.0配置了colorPrimary不生效

### ISSUE THREAD

**Issue by mwj610** [umijs/umi#9815]
配置了colorPrimary不生效，button也只是正常状态颜色变了，hover的时候还是会变成默认的蓝色
![image](https://user-images.githubusercontent.com/52907799/202880767-69b2df69-6b76-4960-9fe0-fea636d18688.png)

![image](https://user-images.githubusercontent.com/52907799/202880683-96f99c9b-4e23-4d92-9cd0-4a79ba0abcbf.png)

**Comment by fz6m** [comment]
位置错了，再看看文档。https://ant.design/components/config-provider-cn

```ts
import type { ConfigProviderProps } from 'antd/es/config-provider'

export default {
  antd: {
    theme: {
      token: {
        colorPrimary: 'red'
      }
    } as ConfigProviderProps['theme']
  }
};
```

**Comment by lx815** [comment]
我这边也是配置了不生效，不知道大佬有解决吗？

**Comment by yyz945947732** [comment]
<img width="297" alt="image" src="https://github.com/umijs/umi/assets/47586954/24811bb4-159f-4eb8-9249-9a1d1507de5d">

同样 `colorPrimary` 无法生效，试了其他的类似 `colorBgContainer` 就可以生效。

**Comment by fz6m** [comment]
如果使用了 max 的 layout ，实际上使用的是 pro layout 这个组件，pro component 系列的组件有独立的配置，详见 https://procomponents.ant.design/components/layout#settings

**Comment by heaxo** [comment]
被选中的颜色在哪配置

**Comment by zphtown** [comment]
> 位置错了，再看看文档。https://ant.design/components/config-provider-cn
> 
> ```ts
> import type { ConfigProviderProps } from 'antd/es/config-provider'
> 
> export default {
>   antd: {
>     theme: {
>       token: {
>         colorPrimary: 'red'
>       }
>     } as ConfigProviderProps['theme']
>   }
> };
> ```



> 位置错了，再看看文档。https://ant.design/components/config-provider-cn
> 
> ```ts
> import type { ConfigProviderProps } from 'antd/es/config-provider'
> 
> export default {
>   antd: {
>     theme: {
>       token: {
>         colorPrimary: 'red'
>       }
>     } as ConfigProviderProps['theme']
>   }
> };
> ```

config/config.ts 配置theme和antd:{theme:{}}都是无效的，官方遗留的问题一直不解决，只有在app.tsx export antd:{theme:{colorPrimary:'red'}}这种方式才能生效，umi这么明细的bug也不修复，真是不忍直视中国最大的互联网公司

**Comment by fz6m** [comment]
如有问题，需要给一个最小复现仓库。
