### ISSUE TITLE
[Bug] umimax 移动端菜单出现BUG（导致展开菜单后 关闭菜单的按钮 只能显示一小半）

### ISSUE THREAD

**Issue by hinego** [umijs/umi#9820]
## What happens?

umimax 移动端菜单出现BUG（导致展开菜单后 关闭菜单的按钮 只能显示一小半）

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

![dddd](https://os.skyqq.cc/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202022-11-21%20072631.png)

https://github.com/hinego/umitest
https://umitest-one.vercel.app/home

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: latest
- **Node Version**: latest
- **Platform**: windows

**Comment by fz6m** [comment]
最新版本的 max 没有这个问题了。
