### ISSUE TITLE
[Feature Request] umi3升级umi4，好多配置没有了，怎么办？

### ISSUE THREAD

**Issue by pxim** [umijs/umi#9832]
## Background

umi3升级umi4，好多配置没有了，怎么办？

umi 3.5.20 中的配置
![image](https://user-images.githubusercontent.com/5111701/203235975-4d98cb5b-d01e-4555-b7b9-0e41dcf14b74.png)
![image](https://user-images.githubusercontent.com/5111701/203236031-2843b87a-694a-4005-a78e-9dae20b5f939.png)
![image](https://user-images.githubusercontent.com/5111701/203236093-a0efde2d-57c4-4db6-9737-de053cb6a422.png)

## Proposal

Describe the solution you'd like, better to provide some pseudo code.

**Comment by fz6m** [comment]
#### port

用命令行环境变量来改变启动端口：

```bash
  pnpm add -D cross-env
```

```ts
// package.json
  "dev": "cross-env PORT=3000 umi dev"
```

#### terser options

umi 4 的默认 js 压缩器已经升级为 esbuild ，有更快的速度。

如果要使用 terser ，请做以下配置：

```ts
// .umirc.ts

export default {
  jsMinifier: 'terser',
  jsMinifierOptions: {
    // terser options
  }
}
```

#### nodeModulesTransform

umi 4 默认不转译 `node_modules` 的 js 资源，默认的编译目标不支持非现代浏览器。

若非要支持非现代浏览器，umi 4 也给出了一种解决方案，详见：[非现代浏览器兼容](https://umijs.org/blog/legacy-browser)

#### 其他

列出来你都需要什么选项，更多迁移说明请查看：[升级到 Umi 4](https://umijs.org/docs/introduce/upgrade-to-umi-4)

**Comment by zzinx58** [comment]
为什么 Umi3&4 通过 chainWebpack 都无法改变项目启动的端口号？

**Comment by fz6m** [comment]
端口号是开发服务器的设定，不是 webpack 的设定，详见 [PORT](https://umijs.org/docs/guides/env-variables#port) 。

**Comment by zzinx58** [comment]
> 端口号是开发服务器的设定，不是 webpack 的设定，详见 [PORT](https://umijs.org/docs/guides/env-variables#port) 。

感谢回复

**Comment by zzinx58** [comment]
> 端口号是开发服务器的设定，不是 webpack 的设定，详见 [PORT](https://umijs.org/docs/guides/env-variables#port) 。

你好，我尝试在 global.js 中进行简单 serviceworker 的注册工作，但是会报错。
<img width="477" alt="image" src="https://user-images.githubusercontent.com/77034104/224913822-9d96c9fa-96e4-4c2d-a896-eab0a602905f.png">
报错信息：The script has an unsupported MIME type ('text/html').
我不知道如何解决，单独的 html 页面中写注册逻辑是正常可用的。
test/src/pwa/sw.js 
sw.js 文件存放路径结构也是一致的。

**Comment by fz6m** [comment]
`sw.js` 放到 `public/sw.js` 下面，这样通过 `http://localhost:port/{base(可选)}/sw.js` 能访问到，你从 `src/global.ts` 里注册这个 sw 就行了，sw 的加载 url 要求必须和当前 domain 相同，仅限 https 。

**Comment by zzinx58** [comment]
> `sw.js` 放到 `public/sw.js` 下面，这样通过 `http://localhost:port/{base(可选)}/sw.js` 能访问到，你从 `src/global.ts` 里注册这个 sw 就行了，sw 的加载 url 要求必须和当前 domain 相同，仅限 https 。

谢谢回复

**Comment by pxim** [comment]
> #### port
> 用命令行环境变量来改变启动端口：
> 
> ```shell
>   pnpm add -D cross-env
> ```
> 
> ```ts
> // package.json
>   "dev": "cross-env PORT=3000 umi dev"
> ```
> 
> #### terser options
> umi 4 的默认 js 压缩器已经升级为 esbuild ，有更快的速度。
> 
> 如果要使用 terser ，请做以下配置：
> 
> ```ts
> // .umirc.ts
> 
> export default {
>   jsMinifier: 'terser',
>   jsMinifierOptions: {
>     // terser options
>   }
> }
> ```
> 
> #### nodeModulesTransform
> umi 4 默认不转译 `node_modules` 的 js 资源，默认的编译目标不支持非现代浏览器。
> 
> 若非要支持非现代浏览器，umi 4 也给出了一种解决方案，详见：[非现代浏览器兼容](https://umijs.org/blog/legacy-browser)
> 
> #### 其他
> 列出来你都需要什么选项，更多迁移说明请查看：[升级到 Umi 4](https://umijs.org/docs/introduce/upgrade-to-umi-4)

怎么关闭 compress  开启会导致 模型的加载进度里的总进度一直是0

**Comment by fz6m** [comment]
需要给一个最小复现
