### ISSUE TITLE
[Bug] umi4 设置iPhone安全距离不生效

### ISSUE THREAD

**Issue by Sean529** [umijs/umi#9833]
## What happens?
在普通 html 中设置安全距离可以正常生效，但 umi4 中设置 iPhone 安全距离无效。

## Mini Showcase Repository(REQUIRED)
重现仓库代码：https://github.com/Sean529/test-umi4-tailwindcss
> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by fz6m** [comment]
#### safe-area-inset-bottom 不生效

我试了下是生效的，提供一个不生效的图片看看。

#### tailwind 不生效

```ts
// .umirc.ts

import { defineConfig } from 'umi'

export default defineConfig({
  extraPostCSSPlugins: ['tailwindcss'],
})
```
