### ISSUE TITLE
[Bug] umijs/max 4.0.32 无法修改logo, app.tsx export的layout无效

### ISSUE THREAD

**Issue by nxboo** [umijs/umi#9848]
## What happens?

umijs/max 4.0.32 无法修改logo, app.tsx export的layout无效

![WX20221124-102232@2x](https://user-images.githubusercontent.com/4253172/203679952-337e350e-74f2-432d-b876-dcfc790b57d0.png)
![WX20221124-102209@2x](https://user-images.githubusercontent.com/4253172/203679955-c97b75e4-fe65-40ef-b67d-30e37ccd0615.png)
![WX20221124-102148@2x](https://user-images.githubusercontent.com/4253172/203679962-ee871e94-e02d-4c22-827d-72f0145d0a62.png)

- umijs/max 4.0.32
- **Node Version**: v14.19.3
- **Platform**: macOS

**Comment by fz6m** [comment]
给一下最小复现看看。
