### ISSUE TITLE
[Feature Request] 请问umi-max何时支持最新的AntDesign5.0

### ISSUE THREAD

**Issue by Longder** [umijs/umi#9854]
请问umi-max脚手架何时支持最新的AntDesign5.0

**Comment by fz6m** [comment]
要用 antd 5 的话把 `dependencies` 的 `antd` 升到 5 就行了，umi 是支持 antd 5 的：

```ts
// package.json

  "antd": "^5.0.0"
```

```ts
// .umirc.ts

export default {
  antd: {}
}
```

`@ant-design/pro-components` 我看也支持 antd 5 了：

https://github.com/ant-design/pro-components/blob/3e0652738e6993973aba34af118ffd8a9af5815c/package.json#L91

**Comment by zydest** [comment]
为啥message组件用不了啊，什么都弹不出来

**Comment by fz6m** [comment]
弹不出来的最小复现给一个。

**Comment by zydest** [comment]
ok 了
