### ISSUE TITLE
[Bug] 升级 4.033 报错

### ISSUE THREAD

**Issue by leshalv** [umijs/umi#9855]
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/30397655/203754549-aa976ad3-4960-47d6-80cb-6f14a45dc11a.png">

**Comment by leshalv** [comment]
@sorrycc @marcosalberto

**Comment by leshalv** [comment]
@sorrycc @stormslowly

**Comment by fz6m** [comment]
删除缓存看一下有用没：

```bash
  rm -rf ./node_modules/.cache
```

**Comment by leshalv** [comment]
> 删除缓存看一下有用没：
> 
> ```shell
>   rm -rf ./node_modules/.cache
>   rm -rf ./src/.umi
> ```

不行

**Comment by fz6m** [comment]
提供一下最小复现帮助排查。

**Comment by stormslowly** [comment]
估计有一个语法  mfsu 分析不出来依赖~   
可以通过删代码的方式 二分法确定下 是哪个源码文件造成的 

可以先通过 mfsu: { strategy: "normal" } 的配置先绕过

**Comment by leshalv** [comment]
如果是三方依赖的话，应该不太好排查吧。

**Comment by stormslowly** [comment]
不出的  这个部分只分析源码的文本 不会分析依赖的代码的

**Comment by stormslowly** [comment]
> 如果是三方依赖的话，应该不太好排查吧。

有空还是帮忙 二分查查看~ 到底是什么语法，我也能继续改进

**Comment by stormslowly** [comment]
@leshalv  排查出来 应该是你的 tsconifg 文件里面配置了 jsx: preserve 然后 mfsu eager 就分析不了了~ 

下一个版本 4.0.34 会 fix ，到时候帮忙验证下

**Comment by leshalv** [comment]
> @leshalv 排查出来 应该是你的 tsconifg 文件里面配置了 jsx: preserve 然后 mfsu eager 就分析不了了~
> 
> 下一个版本 4.0.34 会 fix ，到时候帮忙验证下

我检查了下，最近确实将  jsx: 配置改为了preserve。
