### ISSUE TITLE
[Bug] pluginAPI 里面的 onGenerateFiles 传参定义有问题

### ISSUE THREAD

**Issue by blankmanp** [umijs/umi#9856]
在开发 plugin 的时候，发现 onGenerateFiles 的传参里面的 files 类型定义有问题；
files 类型定义为 { event: string; path: string }
但实际获取到的是 Array<{ event: string; path: string }>

使用版本 `@umijs/core@4.0.32`

**Comment by fz6m** [comment]
https://github.com/umijs/umi/blob/d5952db4372213375c567c762c59175b25c89019/packages/preset-umi/src/types.ts#L178

在这里，PR Welcome

**Comment by mysteryven** [comment]
@blankmanp  你在处理了吗？如果没有的话，我可以认领一下，不过可能要下周才有时间改这个 ~
