### ISSUE TITLE
[BUG] vite 构建时报错：[vite:resolve] Missing "./preload-helper" export in "vite" package

### ISSUE THREAD

**Issue by zengqingzhuang** [umijs/umi#9867]
## What happens?

config/config.ts 开启了 vite 模式，本地开发没问题，配置如下：

```javascript
export default defineConfig({
    hash: true,
    initialState: {},
    model: {},
    plugins: [],
    layout: {
        locale: true,
    },
    antd: {
        import: true,
    },
    codeSplitting: {
        jsStrategy: 'granularChunks',
    },
    vite: { },
    mfsu: false,
    routes,
    theme: {
        '@primary-color': '#fa493d',
    },
    ignoreMomentLocale: true,
    proxy: proxy.dev,
    manifest: {
        basePath: '/',
    },
    presets: ['umi-presets-pro'],
});
```

但是执行 max build 的时候报错
<img width="766" alt="image" src="https://user-images.githubusercontent.com/12510482/203894536-5875f53d-4164-41d5-870c-226496940588.png">

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://github.com/umijs/umi/issues/9867

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**: 4.0.30
- **Node Version**: 16.16.0
- **Platform**: mac

**Comment by zengqingzhuang** [comment]
刚又试了试 @umijs/max@4.0.33版本, vite本地启动服务报错：
<img width="1639" alt="image" src="https://user-images.githubusercontent.com/12510482/203899187-8b677b60-4b2c-44c9-b8a4-19104e55019a.png">

**Comment by Ray-56** [comment]
mark

**Comment by fz6m** [comment]
使用最新版本再尝试一下，我测试了 max 项目使用 `4.0.41` 版本可以启动和构建。
