### ISSUE TITLE
[Bug] Max 项目模板 Vite 模式启动失败 

### ISSUE THREAD

**Issue by fz6m** [umijs/umi#9869]
#### 错误描述

        升级完报这个错误，vite 模式报错
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/12510482/203898601-663b2d6b-a03d-48f5-9098-625ec51dda86.png">

_Originally posted by @zengqingzhuang in https://github.com/umijs/umi/issues/9850#issuecomment-1326997545_
      

#### 如何复现

创建一个 max 模板新项目，开启 `vite: {}` 模式即可复现。

**Comment by zjfresh** [comment]
原因是在生成 .umi目录的 runtime 代码时，统一用自定义的 @fs/ 指向了 node_moduels 中实际的包，而有部分包是 Vite optimizeDeps.include 预处理 cjs 的包，这里是 `@ant-design/pro-components`，可以查看 `node_modules/.vite/deps/`，造成某些依赖 import 了 cjs 代码

https://github.com/umijs/umi/blob/87854d8d467959b5aa2a5a9eeb51e05358eed464/packages/preset-umi/src/utils/transformIEAR.ts#L101-L103

验证方法：
src/.umi/plugin-layout/Layout.tsx
```diff
import {
  ProLayout,
- } from "@fs/node_modules/@ant-design/pro-components";
+ } from "@ant-design/pro-components";
```

处理：

找了下，没找到相关 api 来判断哪些包是被  Vite optimizeDeps.include 预处理的包

或许可以先给 writeTmpFile 添加个参数 skipTransformIEAR 来允许上层跳过？

https://github.com/umijs/umi/blob/87854d8d467959b5aa2a5a9eeb51e05358eed464/packages/preset-umi/src/registerMethods.ts#L123-L125

```diff
// packages/plugins/src/layout.ts
api.writeTmpFile({
      path: 'Layout.tsx',
+    skipTransformIEAR: true,
      content: `xxx`
})
// packages/preset-umi/src/registerMethods.ts
- if (api.appData.vite && isJsFile) {
+ if (api.appData.vite && isJsFile && !skipTransformIEAR) {
    content = transformIEAR({ content, path: absPath }, api);
}
```

**Comment by fz6m** [comment]
@xierenyuan 有空的时候可以辛苦看下是不是某些包可以跳过 `optimize` 。

**Comment by xierenyuan** [comment]
> @xierenyuan 有空的时候可以辛苦看下是不是某些包可以跳过 `optimize` 🌹 。

3.x 合入后我好好验证下吧

**Comment by fz6m** [comment]
在最新版本 `4.0.41` 中 max 项目可以用 `vite: {}` 模式启动了。
