### ISSUE TITLE
[Bug] 升级antd V5后，umi报错Cannot find module 'antd/dist/theme'

### ISSUE THREAD

**Issue by kav012375** [umijs/umi#9872]
报错堆栈如下：
![image](https://user-images.githubusercontent.com/11656089/203925580-c7d51263-e4b6-447b-ac9b-b170303c9d84.png)

已经尝试过清除缓存，清除node_modules，清除.umi等各种办法，均不奏效，是否还有其他配置？

**Comment by kav012375** [comment]
这个报错是在tnpm install阶段产生

**Comment by kav012375** [comment]
发现引用代码如下：
`if (antd.dark || antd.compact) {
      const { getThemeVariables } = require("antd/dist/theme");
      memo.theme = {
        ...getThemeVariables(antd),
        ...memo.theme
      };
    }`
是因为项目开启紧凑主题？那么升级到V5后，紧凑主题如何配置？

**Comment by fz6m** [comment]
还没有好的解决方案，目前的解决方法如下：

```ts
// src/app.tsx

import { ConfigProvider, theme } from 'antd';
import React from 'react';

export function rootContainer(container: React.ReactNode) {
  return (
    <ConfigProvider
      theme={{
        algorithm: theme.compactAlgorithm,
      }}
    >
      {container}
    </ConfigProvider>
  );
}
```

```ts
// .umirc.ts

export default {
  antd: {
    configProvider: undefined
  }
}
```

**Comment by mwj610** [comment]
> 还没有好的解决方案，目前的解决方法如下：
> 
> ```ts
> // src/app.tsx
> 
> import { ConfigProvider, theme } from 'antd';
> import React from 'react';
> 
> export function rootContainer(container: React.ReactNode) {
>   return (
>     <ConfigProvider
>       theme={{
>         algorithm: theme.compactAlgorithm,
>       }}
>     >
>       {container}
>     </ConfigProvider>
>   );
> }
> ```
> 
> ```ts
> // .umirc.ts
> 
> export default {
>   antd: {
>     configProvider: undefined
>   }
> }
> ```
> 
> FYI ：
> 
> * https://ant.design/docs/react/customize-theme-cn
按照这个配置好像layout没有发生改变 只是里面children的组件改变了，还有怎样可以动态切换暗黑主题

**Comment by fz6m** [comment]
#### layout 不生效

我创建了一个 max 项目，这么写是全局生效的，这个 provider 会在最外层。layout 内不生效给一个最小复现看看。

#### 动态切换主题，需要全局变量

```ts
// src/app.tsx

import { ConfigProvider } from 'antd';
import { type MappingAlgorithm } from 'antd/es/config-provider/context';
import React from 'react';
import { globalState } from './globalState';
import { useSnapshot } from '@umijs/max';

const AntdProvider = ({ children }: { children: React.ReactNode }) => {
  const { algorithm } = useSnapshot(globalState);
  return (
    <ConfigProvider
      theme={{
        algorithm: algorithm as MappingAlgorithm[],
      }}
    >
      {children}
    </ConfigProvider>
  );
};

export function rootContainer(container: React.ReactNode) {
  return <AntdProvider>{container}</AntdProvider>;
}
```

```ts
// src/globalState.ts

import { proxy } from '@umijs/max';
import { theme } from 'antd';

export const globalState = proxy({
  algorithm: [theme.darkAlgorithm],
});
```

```ts
// some-component.tsx

import { Button, theme } from 'antd';
import { globalState } from '@/globalState';

// ...

    <Button
      onClick={() => {
        globalState.algorithm = [theme.compactAlgorithm];
      }}
    >
      change theme
    </Button>
  );

```

**Comment by mwj610** [comment]
> 
layout 不生效，layout 内生效了
https://github.com/mwj610/umi-theme-demo

**Comment by mwj610** [comment]
> #### layout 不生效
> 我创建了一个 max 项目，这么写是全局生效的，这个 provider 会在最外层。layout 内不生效给一个最小复现看看。
> 
> #### 动态切换主题，需要全局变量
> ```diff
> // .umirc.ts
> 
> export default {
> +  valtio: {}
> }
> ```
> 
> ```ts
> // src/app.tsx
> 
> import { ConfigProvider } from 'antd';
> import { type MappingAlgorithm } from 'antd/es/config-provider/context';
> import React from 'react';
> import { globalState } from './globalState';
> import { useSnapshot } from '@umijs/max';
> 
> const AntdProvider = ({ children }: { children: React.ReactNode }) => {
>   const { algorithm } = useSnapshot(globalState);
>   return (
>     <ConfigProvider
>       theme={{
>         algorithm: algorithm as MappingAlgorithm[],
>       }}
>     >
>       {children}
>     </ConfigProvider>
>   );
> };
> 
> export function rootContainer(container: React.ReactNode) {
>   return <AntdProvider>{container}</AntdProvider>;
> }
> ```
> 
> ```ts
> // src/globalState.ts
> 
> import { proxy } from '@umijs/max';
> import { theme } from 'antd';
> 
> export const globalState = proxy({
>   algorithm: [theme.darkAlgorithm],
> });
> ```
> 
> ```ts
> // some-component.tsx
> 
> import { Button, theme } from 'antd';
> import { globalState } from '@/globalState';
> 
> // ...
> 
>     <Button
>       onClick={() => {
>         globalState.algorithm = [theme.compactAlgorithm];
>       }}
>     >
>       change theme
>     </Button>
>   );
> ```
> 
> FYI ：
> 
> * https://umijs.org/docs/max/valtio

layout 不生效，layout 内生效了
https://github.com/mwj610/umi-theme-demo

**Comment by fz6m** [comment]
初始化一个 https://github.com/ant-design/ant-design-pro 项目研究下吧。侧边栏有切换主题。

**Comment by mwj610** [comment]
> #### layout 不生效
> 我创建了一个 max 项目，这么写是全局生效的，这个 provider 会在最外层。layout 内不生效给一个最小复现看看。
> 
> #### 动态切换主题，需要全局变量
> ```diff
> // .umirc.ts
> 
> export default {
> +  valtio: {}
> }
> ```
> 
> ```ts
> // src/app.tsx
> 
> import { ConfigProvider } from 'antd';
> import { type MappingAlgorithm } from 'antd/es/config-provider/context';
> import React from 'react';
> import { globalState } from './globalState';
> import { useSnapshot } from '@umijs/max';
> 
> const AntdProvider = ({ children }: { children: React.ReactNode }) => {
>   const { algorithm } = useSnapshot(globalState);
>   return (
>     <ConfigProvider
>       theme={{
>         algorithm: algorithm as MappingAlgorithm[],
>       }}
>     >
>       {children}
>     </ConfigProvider>
>   );
> };
> 
> export function rootContainer(container: React.ReactNode) {
>   return <AntdProvider>{container}</AntdProvider>;
> }
> ```
> 
> ```ts
> // src/globalState.ts
> 
> import { proxy } from '@umijs/max';
> import { theme } from 'antd';
> 
> export const globalState = proxy({
>   algorithm: [theme.darkAlgorithm],
> });
> ```
> 
> ```ts
> // some-component.tsx
> 
> import { Button, theme } from 'antd';
> import { globalState } from '@/globalState';
> 
> // ...
> 
>     <Button
>       onClick={() => {
>         globalState.algorithm = [theme.compactAlgorithm];
>       }}
>     >
>       change theme
>     </Button>
>   );
> ```
> 
> FYI ：
> 
> * https://umijs.org/docs/max/valtio

ProComponents升级到2.3.36之后这种写法就失效了，ProConfigProvider这个黑色主题也不生效
![image](https://user-images.githubusercontent.com/52907799/205025807-325921bf-eb1f-4061-9172-b5914050f1f7.png)

**Comment by lx815** [comment]
我直接按照umi4的文档新建了umi/max的项目，然后再umirc里面配置antd的主题色，也配置不成功。
umi：4.0.32
antd: 5.0.4

// umirc

antd:{
  theme:{
    token:{
     colorPrimary: '#6743D5'
}
}
}

**Comment by Lukiya** [comment]
去掉
  antd: {
     compact: true,
  }

后恢复正常
