### ISSUE TITLE
微生成器的 模版自定义是否支持

### ISSUE THREAD

**Issue by gaoyangy** [umijs/umi#9875]
Background
目前生产出来页面的时候, 文件里面的 组件名称都是一样的, 有没有功能 就是 可以定制 

这样的话 可以根据路由匹配出来代码 aaa/bbb => const AaaBbb: React.FC() = () => {}

Proposal
这样的话 可以根据路由匹配出来代码 aaa/bbb => const AaaBbb: React.FC() = () => {}

Additional context
例如 umi.g.addtpl("page", "tpl path")

**Comment by fz6m** [comment]
用 `umi g page Abc/Cde` ，手动复制一下。
