### ISSUE TITLE
[Bug] SelectLang overlay is deprecated

### ISSUE THREAD

**Issue by codesignist** [umijs/umi#9878]
## What happens?
When we use SelectLang this warning appeared on console:
```Warning: [antd: Dropdown] `overlay` is deprecated. Please use `menu` instead. ```

## Mini Showcase

```javascript
import { SelectLang } from '@umijs/max';

const Component = () => (<SelectLang />);

export default Component;
```

## How To Reproduce

In dropdown component, **overlay** prop should convert to **menu**. Here:
https://4x.ant.design/components/dropdown/#Usage-upgrade-after-4.24.0

## Context

- **Umi Version**: @umijs/max 4.0.24
- **Node Version**: 16.16.0
- **OS**: Windows 11

**Comment by tigershinny** [comment]
+1
