### ISSUE TITLE
[Feature Request] 微生成器支持使用自定义的模板

### ISSUE THREAD

**Issue by stormslowly** [umijs/umi#9890]
## Background

目前  ` umi  g page/component` 命令使用的是 hard code 的模板，在具体的业务开发中还自己写一堆 import 信息和模板代码。
还不够的方便

### 约定
项目根目录 `templates` 作为生成器的模板文件夹， `templates/page/index.tsx.tpl` 和 `templates/page/index.less.tpl` 作为 page 生成的模板文件。如果没有约定模板文件，则回退到代码hard code 的内容

### 变量支持

`tpl` 模板中支持定义变量
```ts
// index.tsx.tpl
export default ()=>{
   return  <div>'{{{ foo }}}'</div>
}
```
使用时 可以通过  `umi g page  --foo bar` 的形式填充模板

component、model 模板依次类推

## Additional context

null

**Comment by mysteryven** [comment]
请问一下，像这种你们自己提的需求，是已经排期要实现了，还是和普通 Feture Request 一样，等待社区认领呢？

**Comment by stormslowly** [comment]
等社区的有缘人了， 我看你就是有缘人来吧~

**Comment by mysteryven** [comment]
没问题，我来尝试一下 ~
