### ISSUE TITLE
[Feature Request] 希望能暴露 setIntl api 供用户动态修改国际化语言

### ISSUE THREAD

**Issue by wangru-chen** [umijs/umi#9894]
## Background

国际化语言需要从后台获取后做覆盖

## Proposal
希望能暴露 setIntl api 供用户动态修改国际化语言

**Comment by fz6m** [comment]
在这里：

https://github.com/umijs/umi/blob/25c4e0e72fbc8d7a33d3ddf964ec225b0ad651f8/packages/plugins/src/locale.ts#L243

PR welcome

**Comment by mysteryven** [comment]
我可以帮你实现，但是我看了 [umi 国际化文档](https://umijs.org/docs/max/i18n#addlocale-%E5%8A%A8%E6%80%81%E6%B7%BB%E5%8A%A0%E5%A4%9A%E8%AF%AD%E8%A8%80%E6%94%AF%E6%8C%81) 后还是不太清楚你的需求。

> ## Background
> 国际化语言需要从后台获取后做覆盖

意思是国际化语言的文件是通过接口获取的吗？如果可以的话，可不可以提供一个表明问题的在线示例

> 
> ## Proposal
> 希望能暴露 setIntl api 供用户动态修改国际化语言

如何提供 API 才能适合你的场景，也希望再详细描述一下。

**Comment by wangru1993** [comment]
是需要从后台获取的，然后覆盖本地定义的国际化语言中的某个key

**Comment by wangru1993** [comment]
目前可以通过setLocale设置为true刷新页面实现
