### ISSUE TITLE
[Bug] antd@5 build 产物分析仍包涵 moment.js

### ISSUE THREAD

**Issue by topaz-h** [umijs/umi#9896]
## What happens?

`antd@5` 默认dayjs，但是 `umi4` build 产物分析仍包涵 `moment.js`

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

![11111](https://user-images.githubusercontent.com/54789070/204565849-3f535cf7-0f59-4bbd-a58e-2a56160bd6f2.jpeg)

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

```json
{
"scripts": {
    "build": "umi build",
  },
  "dependencies": {
    "antd": "^5.0.2",
    "dayjs": "^1.11.6",
    "umi": "^4.0.33"
  },
  "devDependencies": {
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "@umijs/plugins": "^4.0.33",
    "cross-env": "^7.0.3",
    "eslint": "^8.28.0",
    "javascript-stringify": "^2.1.0",
    "typescript": "^4.1.2"
  }
}
```

**Expected behavior** 1. 2.

尝试添加 
  `externals: { moment: 'moment' },`
  或者
  `plugins: [require.resolve('@umijs/plugins/dist/moment2dayjs')]`
 都不能够忽略moment.js

## Context

- **Umi Version**: 4.0.33
- **Node Version**: 16
- **Platform**: m1

**Comment by topaz-h** [comment]
@fz6m 你好，提供了最小复现后，机器人还会重新扫描，修改成打开状态吗？

**Comment by fz6m** [comment]
```diff
// .umirc.ts

export default {
  plugins: [
    require.resolve('@umijs/plugins/dist/antd'),
    require.resolve('@umijs/plugins/dist/locale'),
+   '@umijs/plugins/dist/moment2dayjs'
  ],
+ moment2dayjs: {}
}
```

原因是 i18n (locale) 插件里面用到了 moment ，需要开启 `moment2dayjs` 做替换。

**Comment by fz6m** [comment]
> @fz6m 你好，提供了最小复现后，机器人还会重新扫描，修改成打开状态吗？

创建 issue 时，请在正文中提供 github repo 最小复现链接。 codesandbox 的不好调试，机器人不会识别。

**Comment by topazur** [comment]
谢谢，引入插件了忘记使用，感谢告诉了原因

**Comment by topazur** [comment]
> 
下次注意！

**Comment by topazur** [comment]
> > @fz6m 你好，提供了最小复现后，机器人还会重新扫描，修改成打开状态吗？
> 
> 创建 issue 时，请在正文中提供 github repo 最小复现链接。 codesandbox 的不好调试，机器人不会识别。

下次注意！
