### ISSUE TITLE
4.0.11升级到4.0.33  layout不是@ant-design/pro-layout指定的版本

### ISSUE THREAD

**Issue by mwj610** [umijs/umi#9898]
4.0.11 "@ant-design/pro-layout": "6.38.18"  使用指定的layout版本会生效  ，升级4.0.33 以后layout样式就变了
![1669773789664](https://user-images.githubusercontent.com/52907799/204689529-78ce272a-0bcb-44ad-b88f-a07b073301d6.jpg)

**Comment by fz6m** [comment]
pro-component 包含了 pro-layout ，版本是定死的，应该调整对 pro-component 的版本。

https://github.com/ant-design/pro-components/blob/0044bcdba504f4c7c610a9d3720995a4d4d40460/packages/components/package.json#LL37C39-L37C39
