### ISSUE TITLE
[Bug] react umi项目，antd升级到v5后运行直接报错

### ISSUE THREAD

**Issue by Curry3O** [umijs/umi#9899]
<img width="1184" alt="WeChat926f1d98f8b780e5466122cd3943643a" src="https://user-images.githubusercontent.com/51936110/204693635-ed270b1a-4c3a-4ead-8656-2ecff327bf3f.png">

**Comment by tankpanv** [comment]
> <img alt="WeChat926f1d98f8b780e5466122cd3943643a" width="1184" src="https://user-images.githubusercontent.com/51936110/204693635-ed270b1a-4c3a-4ead-8656-2ecff327bf3f.png">
> 
> 项目跑不起来，好像是关于 less 变量的报错，用antd官网的方法没解决。

我也遇到这个问题了。你这边有解决方法了吗
