### ISSUE TITLE
Improve hd config

### ISSUE THREAD

**Issue by sorrycc** [umijs/umi#99]
目前是全部走这个 vw+flex 的配置：

```js
if (document.documentElement.clientWidth >= 750) {
  vw(100, 750);
} else {
  flex();
}
```

需要支持多种类型：

* default(vw+flex)、vw、flex、vl、vh、custom
* custom 可以通过 JS 文件手写 hd 策略
* 对每个页面配置不同的 hd 策略，在 pages 上配置
* 单页模式下切换页面需切换高清方案（需调研，可能出现闪屏情况）

**Comment by xoptimal** [comment]
开启高清方案后, 所有 css/less 都经过了处理, 将 px 转换成 rem ,  我想请教, 有什么办法可以过滤掉不需要转换的 css 文件 ~

**Comment by xoptimal** [comment]
还有各种每个页面配置不同的HD策略,  能否给个示例指导下,

**Comment by Barretem** [comment]
> 还有各种每个页面配置不同的HD策略, 能否给个示例指导下,
npm install umi-hd --save
然后在每个页面中加入vl(100, 640); // 设计稿是640的
我是这样处理的，不知道对不对。。
缺点：会闪一次屏

**Comment by PuShaoWei** [comment]
同问
