### ISSUE TITLE
请问umi max 4是否支持不同的route配置不同的layout组件

### ISSUE THREAD

**Issue by Longder** [umijs/umi#9904]
请问umi4是否支持不同的route配置不同的layout组件
比如一些url可能需要不使用AntPro的的默认带菜单的layout，而是想自己定义layout引入

**Comment by fz6m** [comment]
1. 在配置式路由中，可以尝试 [wrappers](https://umijs.org/docs/guides/routes#wrappers) 配置 

2. 在配置式路由中，可以通过 `layout: false` 禁用当前路由的 layout 

3. 在 layout 中，可以使用 [useMatch](https://umijs.org/docs/api/api#usematch) 获取当前路由信息，进而条件渲染
