### ISSUE TITLE
[Feature Request] 更新 @umi/max 对 antd 的版本依赖为 >= 4.20.6

### ISSUE THREAD

**Issue by zix2002** [umijs/umi#9906]
## Background

ant design 已经升级到 5.x

## Proposal

希望更新 @umi/max 对 antd 的版本依赖为 >= 4.20.6

**Comment by fz6m** [comment]
https://github.com/umijs/umi/blob/12d57ef43ba15aaea6e10695912bd8f95196f526/packages/create-umi/templates/max/package.json.tpl#L17

在这里，PR Welcome 。

但不应该改为 `>= 4.20.6` ，至少要保证大版本稳定，应该考虑：

1. 改成 `^5.0.0`

2. 或新增交互式选项，支持选择 antd v4 或 v5

**Comment by mysteryven** [comment]
认领一下 ~

我会尝试看看如何使用第二种方式解决
