### ISSUE TITLE
umi4启动的时候报错，publicPath can not start with './' in development environment

### ISSUE THREAD

**Issue by zhupp034** [umijs/umi#9908]
## What happens?
```
{
 publicPath: './',
  history: {
    type: "hash"
  },
}
```
设置hash模式，publicPath设置`./` 会报错 。

## Mini Showcase Repository(REQUIRED)
umi初始化项目即可重现
> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

https://github.com/zhupp034/bugPreview/tree/main/expamle/umiv4

![image](https://user-images.githubusercontent.com/33925263/204944047-3d4a1bcc-0c8b-4899-acd9-9c249168da85.png)

启动之后报如下错误

![image](https://user-images.githubusercontent.com/33925263/204943731-a14f70df-6c87-4c65-a293-3f3040f80e6a.png)

## Context

- **Umi Version**: 4.0.33
- **Node Version**: 14.17.0
- **Platform**: win 11

**Comment by fz6m** [comment]
参考 https://github.com/umijs/umi/issues/9858#issuecomment-1326308975 解决
