### ISSUE TITLE
[Bug]开发环境启动项目登陆时initialState为undefined，需要刷新才能正常取值

### ISSUE THREAD

**Issue by tiancaizs** [umijs/umi#9909]
## What happens?

登陆时需要获取在app.tsx设置的initialState的某些值，但是现在的遇到的问题是每次启动项目登录时打印initialState为undefined，导致无法正常取值，需要刷新才能取到值
开发环境：两个项目都有相同问题
测试环境：一个正常、一个也存在相关问题

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 首次加载无法正常获取initialState值

**Expected behavior** 首次加载正常获取initialState值

## Context

- **Umi Version**:  4.0.12
- **Node Version**:  16.15.0
- **Platform**: w

**Comment by fz6m** [comment]
请提供最小复现帮助解决问题。
