### ISSUE TITLE
[Feature Request] collapsedButtonRender 支持返回reactnode

### ISSUE THREAD

**Issue by wangru-chen** [umijs/umi#9921]
## Background
umi3支持collapsedButtonRender返回reactnode,umi4返回就编译报错
![截屏2022-12-01 17 22 42](https://user-images.githubusercontent.com/15643700/205016800-ed319db4-5f1c-490e-9d33-c88909a02de4.png)

## Proposal
umi4 collapsedButtonRender 支持返回reactnode

**Comment by fz6m** [comment]
给复现看看，我尝试了一下，返回 `React.ReactNode` 正常运行。

**Comment by wangru1993** [comment]
> 给复现看看，我尝试了一下，返回 `React.ReactNode` 正常运行。

我把代码上传到这里了，麻烦给看一下 https://github.com/wangru1993/demo_umi4

**Comment by fz6m** [comment]
要写 jsx 语法，需要以 x 结尾文件名，`app.ts` -> `app.tsx` ，你的 IDE 不会报错么
