### ISSUE TITLE
[Feature Request]  transpile modules

### ISSUE THREAD

**Issue by nfwyst** [umijs/umi#9926]
## Background

在 monorepo 中希望 sub module 改动后能不重新运行 umi dev,  希望能提供一个类似 next-transpile-modules 的插件, v3 有一个 nodeModulesTransform, 但 v4 不可用

**Comment by fz6m** [comment]
给复现看看。

**Comment by fz6m** [comment]
目前这个问题有 [monorepoRedirect](https://umijs.org/docs/api/config#monoreporedirect) 可以解决热更新的问题。
