### ISSUE TITLE
[Bug] Firebase firestore stopped working since 4.0.33

### ISSUE THREAD

**Issue by teamco** [umijs/umi#9943]
After update to 4.0.33 (and later 4.0.34 - not fixed) I found the strange issue with firestore
Unhandled Rejection (Error): Service firestore is not available

## Mini Showcase Repository

![image](https://user-images.githubusercontent.com/18106/205479953-ece88dbf-82ed-41d1-b547-fdf6f2e8ffd4.png)

## How To Reproduce
Simple implementation
`
import { initializeApp } from 'firebase/app';
import {
  getFirestore,
  ...
} from 'firebase/firestore';
const firebaseApp = initializeApp({...});
const db = getFirestore(firebaseApp);
`

**Expected behavior** 1. 2.
Should works as expected (worked fine with version **4.0.32**)

## Context

- **Umi Version**: 4.0.34
- **Node Version**: 16.14.0
- **Platform**: Osx

**Comment by fz6m** [comment]
try remove cache and close mfsu :

```bash
  rm -rf ./node_modules/.cache
  rm -rf ./src/.umi
```

```ts
// .umirc.ts

export default {
  mfsu: false
}
```

**Comment by neekey** [comment]
@fz6m this worked for me!

I'm using firebase v11 now, and just wanted to share it here in case anyone else is having the issue:

```
// const firebase = window.firebase;
import { initializeApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import * as fs from 'firebase/firestore';

export const firebaseApp = initializeApp({...});
export const firebaseAuth = getAuth(firebaseApp);
```

I got the error "Error: Component auth has not been registered yet firebase getAuth" when calling `getAuth()`
