### ISSUE TITLE
[Bug] 新建 umi 脚手架无法开启 Dva 

### ISSUE THREAD

**Issue by mysteryven** [umijs/umi#9959]
## What happens?

初始化一个 umi 项目后，不做任何配置，去开启 Dva ，控制台出现报错。

## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

[复现地址](https://stackblitz.com/edit/node-hbnerh?file=.umirc.ts)

复现地址可以直接运行 `pnpm umi g dva` 出现报错

下面是一小段报错信息：
```
 TypeError: Property value expected type of string but got object
    at Object.validate (/private/tmp/umi-3/node_modules/.pnpm/@umijs+bundler-utils@4.0.34/node_modules/@umijs/bundler-utils/compiled/babel/index.js:137866:13)
```

## How To Reproduce

**Steps to reproduce the behavior:** 

依次执行了下面的命令：

```bash
cd /tmp
mkdir umi-test && cd umi-test
pnpm dlx create-umi@latest
pnpm umi g dva 
```

选择 Simple App 和 Ant Design Pro 都会出现问题。

**Expected behavior** 1. 2.

期待正常开启 Dva

## Context

- **Umi Version**: 4.0.34
- **Node Version**: v18.12.1
- **Platform**: mac os

**Comment by fz6m** [comment]
现在 `umi g` 系列命令都有问题，在 #9939 修复了，等待这周发版解决吧。
