### ISSUE TITLE
umi1.3升级到2.0，每次刷新重新加载时，会有一瞬间的loading页面。

### ISSUE THREAD

**Issue by zhangqianliang** [umijs/umi#997]
如图：
![image](https://user-images.githubusercontent.com/1147839/45017169-76697200-b059-11e8-83ea-05f0f3a26f95.png)

简单例子：https://github.com/zhangqianliang/umi-with-global-layout-demo

**Comment by sorrycc** [comment]
这个默认的 loading 效果，配下 [dynamicImport 的 loadingComponent](https://umijs.org/plugin/umi-plugin-react.html#dynamicimport) 试试。

**Comment by zhoushaobo1015** [comment]
我也同样遇到这个困扰的问题，但是多次创建项目发现在创建项目时候将dva安装就不会出现loading... 或者之后安装dva并在.umirc.js设置dva: true，同样不会出现loading... ,但会出现较长一段时间的空白页面, 希望现在还能帮到你或者更多的朋友解惑，虽然目前我不清楚这是为何.
