### ISSUE TITLE
umi3.5是否可能使用独立MFSU V3？

### ISSUE THREAD

**Issue by rpyoyo** [umijs/umi#9977]
### Discussed in https://github.com/umijs/umi/discussions/9932

<div type='discussions-op-text'>

<sup>Originally posted by **rpyoyo** December  2, 2022</sup>
umi3的MFSU不好用，各种热更新失效
项目从umi3.5升级到umi4目前要踩的坑还有点多
知乎上宣传umi4的帖子里介绍说umi3中MFSU的坑已经在MFSU V3中全解，且MFSU已经可以独立使用
那么umi3.5有可能结合MFSU V3独立使用么？
![image](https://user-images.githubusercontent.com/4035181/205260898-8dd2aeaa-7938-4689-8500-3942003dc3e2.png)
</div>

**Comment by vaezc** [comment]
同样需要

**Comment by M76chao** [comment]
这都快过去一年了，还没解决吗
