### ISSUE TITLE
[Bug] 升级Umi 4之后Wrappers里无法获取routers信息

### ISSUE THREAD

**Issue by kav012375** [umijs/umi#9978]
升级到umi4之前，可以通过如下方式获取
`export default (props: IRouteComponentProps) => {
    const { initialState } = useModel('@@initialState');
    const { currentUser } = initialState || {};
    const { children, route } = props;
    //use route do something
};`
但是我升级到umi4之后，这个props无论怎么获取都是空的，我已经尝试了如下方式：
`export default (props: any) => {  }`
也尝试了使用 `const props = useOutletContext ();`

所以，umi4 中我应该怎么做才能在wrappers中获取到当前route的信息

**Comment by kav012375** [comment]
当我尝试使用useSelectedRoutes这个hook时，会报错   “模块“"umi"”没有导出的成员“useSelectedRoutes”

**Comment by fz6m** [comment]
`useSelectedRoutes` 是昨天新增的，这周四发版了才有。

现在可以自己实现一个：

```ts
import { useLocation, matchRoutes, useAppData } from 'umi'

export function useSelectedRoutes() {
  const location = useLocation();
  const { clientRoutes } = useAppData();
  // use `useLocation` get location without `basename`, not need `basename` param
  const routes = matchRoutes(clientRoutes, location.pathname);
  return routes || [];
}
```
