### ISSUE TITLE
[Bug] 紧凑布局开启失败

### ISSUE THREAD

**Issue by kav012375** [umijs/umi#9980]
## What happens?

紧凑布局开启之后，界面无任何变化

## Mini Showcase Repository(REQUIRED)

App.ts中新增了如下代码：
![image](https://user-images.githubusercontent.com/11656089/206103199-963abe23-86c9-4914-b201-1d8252bc4db1.png)

http://gitlab.alibaba-inc.com/intime-qa/mos-watcher-client.git

## How To Reproduce

**升级umi/max到4.0.34版本

**升级atnd 到 5.0.4版本

**在app.ts增加开启紧凑算法的代码

**没有任何效果，界面仍是非紧凑布局状态

## Context

- **Umi Version**:4.0.34
- **Node Version**:14.21.1
- **Platform**: mac os

**Comment by fz6m** [comment]
如果使用 layout 插件，在 `app.ts` 里 layout 对应的 `export const layout` 运行时配置处配置，不需要自己手动添加一层 Provider
