### ISSUE TITLE
[Bug] umi3 升级到 umi4 问题

### ISSUE THREAD

**Issue by jiangkaifree** [umijs/umi#9985]
## What happens?

你好，我在按照[官方文档](https://umijs.org/docs/introduce/upgrade-to-umi-4) umi3 升级到umi4 过程中， 更改了依赖， 以及启动命令后， 发生如下报错：

```js
 Can not resolve dependence : '@tmp/history',
```
![image](https://user-images.githubusercontent.com/50451924/206135373-7d5d51a0-d056-445e-b074-dfe25236db77.png)

看起来似乎是缺少了 依赖，我是需要单独 **install** 吗

## How To Reproduce

按照文档进行修改，[官方文档](https://umijs.org/docs/introduce/upgrade-to-umi-4)

1. 移除旧依赖， 改为 `@umijs/max`
2. 修改启动命令 `"start": "umi dev" 为 "start": "max dev",`

## Context

- **Umi Version**: 4.0.0
- **Node Version**:  16.18.1
- **Platform**: windows

**Comment by fz6m** [comment]
搜一下代码里有没有 `@tmp/history` 这个包。

提供一个最小复现排查问题。

**Comment by jiangkaifree** [comment]
> 搜一下代码里有没有 `@tmp/history` 这个包。
> 
> 提供一个最小复现排查问题。

你好！我是从 umi2 升级上来的 ，删除了 pages 文件夹下的 **.umi** 文件 （这好像很重要），重新运行 `start` 问题似乎得到了解决， 但是 antd 的样式却丢失了。由于项目使用的是 `antd3` 。所以我在 `package.json`中指定了版本，这导致出现了问题。
```json
  "dependencies": {
    "@ant-design/charts": "^1.4.2",
    "antd": "^3.19.5",
    "dva": "^2.6.0-beta.6",
    "echarts": "^5.3.3",
    "jsencrypt": "^3.0.0-rc.1",
    "qs": "^6.11.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
```
![image](https://user-images.githubusercontent.com/50451924/206396140-59cc4bf7-722b-435f-9baa-5df94898404b.png)

在我移除 `package.json` 中 `antd` 之后 得到了恢复， 应该是使用了 umi4 中整合的 antd4 版本。所以我这边得到的问题是 **不能指定对应的antd版本，会造成问题**，这是[最小demo](https://github.com/jiangkaifree/umi-update)

**Comment by LukeLiou** [comment]
> 

请问是将"antd": "^3.16.6",删除后重新install即可生效吗，我也遇到此问题，尝试无果

**Comment by jiangkaifree** [comment]
> > 
> 
> 请问是将"antd": "^3.16.6",删除后重新install即可生效吗，我也遇到此问题，尝试无果

两个点： 一个是 .umirc.js 中需要有antd 配置:

```js
targets: { ie: 11, chrome: 70 },
  proxy: {},
  dva: {},
  antd: {}, // 需要
route: []
... // other
```

2.  `package.json` 当中并不需要包含 `antd`,  而且我不建议指定 antd 的版本，因为umi4中使用的是4版本， 而现在antd最新的是5， 我曾经尝试指定5， 适合并没有成功。

**Comment by LukeLiou** [comment]
你好，我这边工程没有umirc.js文件，需要自己手动建吗？

> 2023年2月13日 17:05，xiaocaiji ***@***.***> 写道：
> 
> umirc.js

**Comment by jiangkaifree** [comment]
> 

或许你先尝试移除 `package.json` 当中的 `antd` , 依赖，看看能不能正常， 如果不行，再尝试创建配置文件。个人认为 不应该没有吧。 这是umi的配置文件。 根目录下`.umirc.js` 或者是 `.umirc.ts`
![1676280163610](https://user-images.githubusercontent.com/50451924/218419681-4ad35a44-d561-4ef5-8fa7-bac88fe30b30.jpg)

**Comment by LukeLiou** [comment]
问题已找到，我工程的umi配置文件体现在config.js，将msfu值改成false，再回true 重新start，运行成功，只是访问页面有大量的报错，需要关注代码层的修改了
￼
