### ISSUE TITLE
用file-loader处理iconfont的css引入路径，umi4没有正确处理,与在umi3下不符

### ISSUE THREAD

**Issue by wssgchungang** [umijs/umi#9986]
## What happens?

用file-loader处理iconfont的css引入路径，umi4没有正确处理 
fileloader配置
![image](https://user-images.githubusercontent.com/29122164/206170155-a08766b4-3323-434f-9388-eed27f038b44.png)

错误结果：打包结果是新建了字体文件，并在字体文件里做了js的文件引入，woff文件执行不了js，导致icon出不来，而不是直接在umi.css中替换引入地址

![image](https://user-images.githubusercontent.com/29122164/206170649-36b61d83-6790-44c1-aeda-7cb05462a4ce.png)

正确结果应该是css中对字体文件引入的地址做替换 ：
打完包的umi.css文件中 src: url(./static/iconfont.bf43c7cc.woff2) =>src: url(/workorder/iconfont.bf43c7cc.woff2)
umi3中是正常的

## Context

- **Umi Version**: 4.0.24
- **Node Version**: 14.x
- **Platform**: windows

**Comment by fz6m** [comment]
webpack 5 没有 `file-loader` 了：

```ts
// .umirc.ts

export default {
  chainWebpack(config) {
    const FONT_REG = /\.(ttf|otf|eot|woff|woff2)$/
    config.module.rule('asset').exclude.add(FONT_REG)

    config.module
      .rule('fonts')
      .test(FONT_REG)
      .type('asset/resource')
      .generator({
        publicPath: '/prefix/',
      })
  },
}
```

自己配一下这里的 `publicPath` ，如果不行的话就改成函数，参考：https://webpack.js.org/configuration/module/#rulegeneratorpublicpath

注意这会作用到所有的 fonts 引用，要保证所有的字体都符合从 `publicPath` 加载的条件，如果想部分作用，同样的使用 `publicPath` 的函数配制方法去判断。
