### ISSUE TITLE
[react-vant] 使用 umi v4.0.33 及之后的版本创建 react-vant 应用样式不生效

### ISSUE THREAD

**Issue by bowen-wu** [umijs/umi#9991]
## What happens?

when creating react-vant application with umi. umi version 4.0.32 and before version style working, but version 4.0.33 and after version style not working 

使用 umi 创建 react-vant 应用，在 v4.0.32 及之前的版本样式生效，但是在 v4.0.33 及之后的版本样式不生效

## Mini Showcase Repository(REQUIRED)

[最小重现](https://github.com/bowen-wu/test-umi-react-vant)

## How To Reproduce

- umi current version is 4.0.33 in package.json, Button style is not working after the start
- change umi version to 4.0.32 in package.json, delete the node_modules directory and pnpm-lock.yaml file, then install the dependency, Button style working after starting

- 上述仓库中 package.json 中的 umi 版本为 4.0.33，启动之后页面中的 Button 没有任何样式
- 将 package.json 中 umi 版本改为 4.0.32，之后删除 node_modules 和 pnpm-lock.yaml 重新安装依赖，启动之后页面中的 Button 有样式

## Context

- **v4.0.33** & **v4.0.32**:
- **Chrome Browser**:

**Comment by bowen-wu** [comment]
我发现在 v4.0.32 和 v4.0.33 版本中的：
- [commit 92680e740](https://github.com/umijs/umi/commit/92680e7403ab46970e9a8810b9dd9c38a4dffff7) 样式是不生效的
- [commit 24ff9336f](https://github.com/umijs/umi/commit/24ff9336ff778c8bacc3ce1f333b40e9894f7d29) 样式是生效的

修复的大佬可以测试一下

**Comment by congwa** [comment]
同样遇到了这个问题，先降级处理吧

**Comment by stormslowly** [comment]
@congwa  @bowen-wu   https://github.com/umijs/umi/releases/tag/v4.0.35 修复了此问题 

可以尝试开启 mfsu 再试试~ 

具体 PR  https://github.com/umijs/umi/pull/9976
